Xonotic: menu/xonotic/charmap.qh File Reference
charmap.qh File Reference
#include "picker.qh"
Functions
METHOD (XonoticCharmap, configureXonoticCharmap, void(entity, entity))
METHOD (XonoticCharmap, focusLeave, void(entity))
METHOD (XonoticCharmap, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticCharmap, keyDown, float(entity, float, float, float))
METHOD (XonoticCharmap, cellSelect, void(entity, vector))
METHOD (XonoticCharmap, cellIsValid, bool(entity, vector))
METHOD (XonoticCharmap, cellDraw, void(entity, vector, vector))
entity makeXonoticCharmap (entity controlledInputBox)
Function Documentation
entity makeXonoticCharmap (entity controlledInputBox)
Definition at line 32 of file charmap.qc.
References entity(), me, and NEW.
Referenced by XonoticFirstRunDialog_fill(), and XonoticProfileTab_fill().
 {
     entity me;
     me = NEW(XonoticCharmap);
     me.configureXonoticCharmap(me, controlledInputBox);
     return me;
 }
METHOD (XonoticCharmap , configureXonoticCharmap , void(entity, entity))
METHOD (XonoticCharmap , focusLeave , void(entity))
METHOD (XonoticCharmap , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticCharmap , keyDown , float(entity, float, float, float))
METHOD (XonoticCharmap , cellSelect , void(entity, vector))
METHOD (XonoticCharmap , cellIsValid , bool(entity, vector))
METHOD (XonoticCharmap , cellDraw , void(entity, vector, vector))