Xonotic: common/minigames/minigame/bd.qc File Reference
bd.qc File Reference
#include "bd.qh"
Functions
void bd_activate_editor (entity minigame, entity player)
bool bd_canfill (int ttype)
void bd_check_winner (entity minig)
void bd_close_editor (entity minigame, entity player)
void bd_controller_update (entity controller, int number)
int bd_dir_fromname (string bdir)
void bd_do_fill (entity minigame, entity player, string dir, string thetile)
void bd_do_move (entity minigame, entity player, string dir, string thetile, string thedir)
void bd_do_next_match (entity minigame, entity player)
void bd_editor_place (entity minigame, entity player, string pos, int thetile, string thedir)
void bd_fill_recurse (entity minigame, entity player, int thetype, int letter, int number)
entity bd_find_controller (entity minig, int letter)
entity bd_find_dozer (entity minig)
entity bd_find_piece (entity minig, string tile, bool check_target)
int bd_fix_dir (vector dir)
vector bd_get_dir (int bdir)
string bd_get_dir_name (int bdir)
void bd_load_level (entity minigame)
void bd_load_piece (entity minigame, string s)
void bd_move (entity minigame, entity player, string dir)
bool bd_move_dozer (entity minigame, entity dozer)
void bd_next_match (entity minigame, entity player, string next)
void bd_reset_moves (entity minigame)
void bd_restart_match (entity minigame, entity player)
string bd_save_controller_piece (entity minigame, entity e, int number)
bool bd_save_level (entity minigame)
string bd_save_piece (entity minigame, entity e)
void bd_set_next_match (entity minigame, string next)
void bd_set_nextlevel (entity minigame, string s)
void bd_setup_pieces (entity minigame)
void bd_unfill_recurse (entity minigame, entity player, int thetype, int letter, int number)
bool bd_valid_tile (string tile)
REGISTER_MINIGAME (bd, _("Bulldozer"))
Variables
int bd_dir
const int BD_DIR_DN = 1
const int BD_DIR_LF = 2
const int BD_DIR_RT = 3
const int BD_DIR_UP = 0
int bd_dirs [BD_NUM_CNT]
const int BD_LET_CNT = 20
string bd_levelname
int bd_moves
string bd_nextlevel
const int BD_NUM_CNT = 20
const int BD_SF_PLAYERMOVES = MINIG_SF_CUSTOM
const int BD_SF_UPDATE_ALL = MINIG_SF_CUSTOM<<2
const int BD_SF_UPDATE_SINGLE = MINIG_SF_CUSTOM<<1
const int BD_SPECTATOR_TEAM = 255
const int BD_TEAMS = 1
const int BD_TILE_BOULDER = 3
const int BD_TILE_BRICK1 = 4
const int BD_TILE_BRICK2 = 5
const int BD_TILE_BRICK3 = 6
const int BD_TILE_BRICK4 = 7
const int BD_TILE_BRICK5 = 8
const int BD_TILE_BRICK6 = 9
const int BD_TILE_BRICK7 = 10
const int BD_TILE_BRICK8 = 11
const int BD_TILE_DOZER = 1
const int BD_TILE_LAST = 11
const int BD_TILE_SIZE = 20
const int BD_TILE_TARGET = 2
int bd_tilelet
int bd_tiletype
int bd_tiletypes [BD_NUM_CNT]
const int BD_TURN_EDIT = 0x0800
const int BD_TURN_LOSS = 0x0400
const int BD_TURN_MOVE = 0x0100
const int BD_TURN_TYPE = 0x0f00
const int BD_TURN_WIN = 0x0200
Function Documentation
bd_activate_editor()
void bd_activate_editor (entity minigame, entity player)
Definition at line 632 of file bd.qc.
References bd_reset_moves(), bd_setup_pieces(), BD_TURN_EDIT, MINIG_SF_UPDATE, minigame_server_sendflags(), and sprint().
Referenced by bd_close_editor().
 {
 #ifdef SVQC
     if(!player.minigame_players.bd_canedit)
     {
         sprint(player.minigame_players, "You're not allowed to edit levels, sorry!\n");
         return;
     }
 #endif
     minigame.minigame_flags = BD_TURN_EDIT;
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     bd_reset_moves(minigame);
     bd_setup_pieces(minigame);
 }
bd_canfill()
bool bd_canfill (int ttype)
Definition at line 235 of file bd.qc.
References BD_TILE_BRICK1, BD_TILE_BRICK2, BD_TILE_BRICK3, BD_TILE_BRICK4, BD_TILE_BRICK5, BD_TILE_BRICK6, BD_TILE_BRICK7, and BD_TILE_BRICK8.
Referenced by bd_do_fill(), bd_editor_place(), and bd_load_piece().
 {
     switch(ttype)
     {
         case BD_TILE_BRICK8:
         case BD_TILE_BRICK7:
         case BD_TILE_BRICK6:
         case BD_TILE_BRICK5:
         case BD_TILE_BRICK4:
         case BD_TILE_BRICK3:
         case BD_TILE_BRICK2:
         case BD_TILE_BRICK1: return true;
     }
     return false;
 }
bd_check_winner()
void bd_check_winner (entity minig)
Definition at line 178 of file bd.qc.
References bd_find_piece(), BD_TURN_WIN, entity(), findentity(), MINIG_SF_UPDATE, minigame_server_sendflags(), NULL, and owner.
Referenced by bd_move().
 {
     int total = 0, valid = 0;
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.bd_tiletype == BD_TILE_TARGET )
         {
             ++total;
             if(bd_find_piece(minig, e.netname, false).bd_tiletype == BD_TILE_BOULDER)
                 ++valid;
         }
     if(valid >= total)
     {
         minig.minigame_flags = BD_TURN_WIN;
         minigame_server_sendflags(minig,MINIG_SF_UPDATE);
     }
 }
bd_close_editor()
void bd_close_editor (entity minigame, entity player)
Definition at line 817 of file bd.qc.
References active_minigame, argv(), bd_activate_editor(), BD_DIR_DN, BD_DIR_LF, BD_DIR_RT, BD_DIR_UP, bd_do_fill(), bd_do_move(), bd_find_dozer(), bd_find_piece(), bd_next_match(), BD_NUM_CNT, bd_restart_match(), bd_save_level(), bd_setup_pieces(), BD_SF_PLAYERMOVES, BD_SPECTATOR_TEAM, BD_TILE_BOULDER, BD_TILE_BRICK1, BD_TILE_BRICK2, BD_TILE_BRICK3, BD_TILE_BRICK4, BD_TILE_BRICK5, BD_TILE_BRICK6, BD_TILE_BRICK7, BD_TILE_BRICK8, BD_TILE_DOZER, BD_TILE_TARGET, BD_TURN_EDIT, BD_TURN_LOSS, BD_TURN_MOVE, BD_TURN_WIN, bd_valid_tile(), DRAWFLAG_NORMAL, entity(), findentity(), FOREACH_MINIGAME_ENTITY, hud_fontsize, int, LOG_INFO, M_PI, MINIG_SF_UPDATE, minigame_count_players(), minigame_drawpic_centered(), minigame_hud_denormalize(), minigame_hud_denormalize_size(), minigame_hud_fitsqare, minigame_hud_simpleboard(), minigame_server_sendflags(), minigame_texture(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), minigame_tile_pos(), NULL, number, owner, panel_fg_alpha, sprint(), strcpy, strfree, string_null, vector(), WriteByte(), and WriteShort().
 {
 #ifdef SVQC
     if(!player.minigame_players.bd_canedit)
     {
         sprint(player.minigame_players, "You're not allowed to edit levels, sorry!\n");
         return;
     }
 #endif
     entity dozer = bd_find_dozer(minigame);
     if(!dozer)
     {
         LOG_INFO("You need to place a bulldozer on the level to save it!");
         return;
     }
     if(bd_save_level(minigame))
     {
         minigame.minigame_flags = BD_TURN_MOVE;
         minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     }
     else
     {
         LOG_INFO("You need to set the level name!");
         return;
     }
 }
bd_controller_update()
void bd_controller_update (entity controller, int number)
Definition at line 96 of file bd.qc.
References BD_SF_UPDATE_SINGLE, minigame_server_sendflags(), and number.
Referenced by bd_editor_place(), and bd_load_piece().
 {
 #ifdef SVQC
     controller.bd_forceupdate = number;
 #endif
     minigame_server_sendflags(controller,BD_SF_UPDATE_SINGLE);
 }
bd_dir_fromname()
int bd_dir_fromname (string bdir)
down
Definition at line 221 of file bd.qc.
References BD_DIR_DN, BD_DIR_LF, BD_DIR_RT, and BD_DIR_UP.
Referenced by bd_editor_place(), and bd_move().
 {
     if(bdir == "up" || bdir == "u")
         return BD_DIR_UP; // up
     if(bdir == "down" || bdir == "dn" || bdir == "d")
         return BD_DIR_DN;
     if(bdir == "left" || bdir == "lt" || bdir == "l")
         return BD_DIR_LF; // left
     if(bdir == "right" || bdir == "rt" || bdir == "r")
         return BD_DIR_RT; // right
     return BD_DIR_DN; // down
 }
bd_do_fill()
void bd_do_fill (entity minigame, entity player, string dir, string thetile)
Definition at line 506 of file bd.qc.
References bd_canfill(), bd_fill_recurse(), bd_find_piece(), BD_TURN_EDIT, bd_unfill_recurse(), entity(), minigame_tile_letter(), minigame_tile_number(), number, sprint(), and stof().
Referenced by bd_close_editor().
 {
 #ifdef SVQC
     if(!player.minigame_players.bd_canedit)
     {
         sprint(player.minigame_players, "You're not allowed to edit levels, sorry!\n");
         return;
     }
 #endif
     if(minigame.minigame_flags & BD_TURN_EDIT)
     {
         int thetype = stof(thetile);
         entity targ = bd_find_piece(minigame, dir, true);
         entity piece = bd_find_piece(minigame, dir, false);
         if(!bd_canfill(thetype) || (piece || targ))
         {
             int killtype = 0;
             if(targ) { killtype = targ.bd_tiletype; }
             if(piece) { killtype = piece.bd_tiletype; }
             if(killtype)
             {
                 int letter = minigame_tile_letter(dir);
                 int number = minigame_tile_number(dir);
                 bd_unfill_recurse(minigame, player, killtype, letter, number);
             }
             return;
         }
         int letter = minigame_tile_letter(dir);
         int number = minigame_tile_number(dir);
         bd_fill_recurse(minigame, player, thetype, letter, number);
     }
 }
bd_do_move()
void bd_do_move (entity minigame, entity player, string dir, string thetile, string thedir)
Definition at line 454 of file bd.qc.
References bd_editor_place(), bd_move(), BD_TURN_EDIT, BD_TURN_MOVE, and stof().
Referenced by bd_close_editor().
 {
     if(minigame.minigame_flags & BD_TURN_MOVE)
         bd_move(minigame, player, dir);
     if(minigame.minigame_flags & BD_TURN_EDIT)
         bd_editor_place(minigame, player, dir, stof(thetile), thedir);
 }
bd_do_next_match()
void bd_do_next_match (entity minigame, entity player)
Definition at line 593 of file bd.qc.
References bd_reset_moves(), bd_setup_pieces(), BD_TURN_MOVE, MINIG_SF_UPDATE, minigame_server_sendflags(), and strcpy.
Referenced by bd_next_match().
 {
     minigame.minigame_flags = BD_TURN_MOVE;
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     if(minigame.bd_nextlevel && minigame.bd_nextlevel != "")
     {
         strcpy(minigame.bd_levelname, minigame.bd_nextlevel);
     }
     bd_setup_pieces(minigame);
     bd_reset_moves(minigame);
 }
bd_editor_place()
void bd_editor_place (entity minigame, entity player, string pos, int thetile, string thedir)
Definition at line 382 of file bd.qc.
References bd_canfill(), bd_controller_update(), bd_dir_fromname(), bd_find_controller(), bd_find_piece(), BD_TURN_EDIT, bd_valid_tile(), entity(), MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_letter(), minigame_tile_number(), msle_spawn(), number, strfree, and strzone().
Referenced by bd_do_move(), and bd_fill_recurse().
 {
     if ( minigame.minigame_flags & BD_TURN_EDIT )
     if ( pos && thetile )
     {
         if ( bd_valid_tile(pos) )
         {
             entity found_piece = bd_find_piece(minigame, pos, false);
             entity targ = bd_find_piece(minigame, pos, true);
             if(found_piece.bd_tiletype == BD_TILE_DOZER && thedir != "")
             {
                 string newdir = strtolower(thedir);
                 int bdir = bd_dir_fromname(newdir);
                 found_piece.bd_dir = bdir;
                 minigame_server_sendflags(found_piece,MINIG_SF_UPDATE); // update anyway
                 return;
             }
             //entity dozer = bd_find_dozer(minigame);
             //if(dozer && thetile == BD_TILE_DOZER && pos != dozer.netname)
                 //return; // nice try
             int tlet = minigame_tile_letter(pos);
             int tnum = minigame_tile_number(pos);
             entity controller = bd_find_controller(minigame, tlet);
             if(controller.bd_tiletypes[tnum])
             {
                 controller.bd_tiletypes[tnum] = 0;
                 controller.bd_dirs[tnum] = 0;
                 bd_controller_update(controller, tnum);
                 return;
             }
             if(found_piece || (targ && thetile != BD_TILE_BOULDER))
             {
                 entity piece = bd_find_piece(minigame, pos, false);
                 if(!piece) piece = bd_find_piece(minigame, pos, true);
                 if(!piece)
                     return; // how?!
                 strfree(piece.netname);
                 delete(piece);
                 minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
                 return;
             }
             if(bd_canfill(thetile))
             {
                 int number = minigame_tile_number(pos);
                 int letter = minigame_tile_letter(pos);
                 entity controller = bd_find_controller(minigame, letter);
                 controller.bd_tiletypes[number] = thetile;
                 controller.bd_dirs[number] = 0;
                 bd_controller_update(controller, number);
             }
             else
             {
                 entity piece = msle_spawn(minigame,new(minigame_board_piece));
                 piece.team = 1;
                 piece.netname = strzone(pos);
                 piece.bd_tiletype = thetile;
                 piece.bd_dir = 0;
                 minigame_server_sendflags(piece,MINIG_SF_UPDATE);
             }
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         }
     }
 }
bd_fill_recurse()
void bd_fill_recurse (entity minigame, entity player, int thetype, int letter, int number)
Definition at line 463 of file bd.qc.
References bd_editor_place(), bd_find_piece(), bd_valid_tile(), and minigame_tile_buildname().
Referenced by bd_do_fill().
 {
     string pos = minigame_tile_buildname(letter,number);
     if(!bd_valid_tile(pos))
         return;
     if(bd_find_piece(minigame, pos, false) || bd_find_piece(minigame, pos, true))
         return;
     bd_editor_place(minigame, player, pos, thetype, "");
     bd_fill_recurse(minigame, player, thetype, letter - 1, number);
     bd_fill_recurse(minigame, player, thetype, letter + 1, number);
     bd_fill_recurse(minigame, player, thetype, letter, number - 1);
     bd_fill_recurse(minigame, player, thetype, letter, number + 1);
 }
bd_find_controller()
entity bd_find_controller (entity minig, int letter)
Definition at line 77 of file bd.qc.
References entity(), findentity(), NULL, and owner.
Referenced by bd_editor_place(), bd_load_piece(), and bd_move_dozer().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "bd_controller" && e.bd_tilelet == letter )
             return e;
     return NULL;
 }
bd_find_dozer()
entity bd_find_dozer (entity minig)
Definition at line 104 of file bd.qc.
References bd_dirs, BD_NUM_CNT, BD_SF_UPDATE_ALL, BD_SF_UPDATE_SINGLE, bd_tiletypes, classname, dir, entity(), findentity(), minigame_read_owner(), NET_HANDLE, NULL, number, owner, to, WriteByte(), and WriteString().
Referenced by bd_close_editor(), and bd_move().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.bd_tiletype == BD_TILE_DOZER )
             return e;
     return NULL;
 }
bd_find_piece()
entity bd_find_piece (entity minig, string tile, bool check_target)
Definition at line 68 of file bd.qc.
References entity(), findentity(), NULL, and owner.
Referenced by bd_check_winner(), bd_close_editor(), bd_do_fill(), bd_editor_place(), bd_fill_recurse(), bd_move_dozer(), and bd_unfill_recurse().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile && ((check_target) ? e.bd_tiletype == BD_TILE_TARGET : e.bd_tiletype != BD_TILE_TARGET) )
             return e;
     return NULL;
 }
bd_fix_dir()
int bd_fix_dir (vector dir)
Definition at line 681 of file bd.qc.
References BD_DIR_DN, BD_DIR_LF, BD_DIR_RT, and BD_DIR_UP.
 {
     if(dir.x == 0 && dir.y == 1) { return BD_DIR_UP; } // up
     if(dir.x == 0 && dir.y == -1) { return BD_DIR_DN; } // down
     if(dir.x == -1 && dir.y == 0) { return BD_DIR_LF; } // left
     if(dir.x == 1 && dir.y == 0) { return BD_DIR_RT; } // right
     return BD_DIR_DN; // down if all else fails
 }
bd_get_dir()
vector bd_get_dir (int bdir)
Definition at line 197 of file bd.qc.
References BD_DIR_DN, BD_DIR_LF, BD_DIR_RT, and BD_DIR_UP.
Referenced by bd_move_dozer().
 {
     switch(bdir)
     {
         case BD_DIR_UP: return '0 1 0'; // up
         default:
         case BD_DIR_DN: return '0 -1 0'; // down
         case BD_DIR_LF: return '-1 0 0'; // left
         case BD_DIR_RT: return '1 0 0'; // right
     }
 }
bd_get_dir_name()
string bd_get_dir_name (int bdir)
Definition at line 209 of file bd.qc.
References BD_DIR_DN, BD_DIR_LF, BD_DIR_RT, and BD_DIR_UP.
 {
     switch(bdir)
     {
         case BD_DIR_UP: return "u"; // up
         default:
         case BD_DIR_DN: return "d"; // down
         case BD_DIR_LF: return "l"; // left
         case BD_DIR_RT: return "r"; // right
     }
 }
bd_load_level()
void bd_load_level (entity minigame)
Definition at line 782 of file bd.qc.
References bd_load_piece(), bd_set_nextlevel(), fclose(), fgets(), FILE_READ, fopen(), LOG_INFO, strcat(), and substring().
Referenced by bd_reset_moves(), and bd_setup_pieces().
 {
     // loads all items from the database file
     string file_read, file_name;
     float file_get;
     file_name = strcat("minigames/bulldozer/storage_", minigame.bd_levelname, ".txt");
     file_get = fopen(file_name, FILE_READ);
     if(file_get < 0)
     {
         LOG_INFO("^3BULLDOZER: ^7could not find storage file ^3", file_name, "^7, no items were loaded");
     }
     else
     {
         for(;;)
         {
             file_read = fgets(file_get);
             if(file_read == "")
                 break;
             if(substring(file_read, 0, 2) == "//")
                 continue;
             if(substring(file_read, 0, 1) == "#")
                 continue;
             if(substring(file_read, 0, 9) == "nextlevel")
             {
                 bd_set_nextlevel(minigame, file_read);
                 continue;
             }
             bd_load_piece(minigame, file_read);
         }
     }
     fclose(file_get);
 }
bd_load_piece()
void bd_load_piece (entity minigame, string s)
Definition at line 691 of file bd.qc.
References argv(), bd_canfill(), bd_controller_update(), bd_find_controller(), dir, entity(), MINIG_SF_ALL, minigame_server_sendflags(), minigame_tile_letter(), minigame_tile_number(), msle_spawn(), number, stoi, strzone(), and tokenize_console.
Referenced by bd_load_level().
 {
     // separate pieces between the ; symbols
     string bd_string = s;
     tokenize_console(bd_string);
     int argv_num = 0;
     string tilename = strzone(argv(argv_num)); ++argv_num;
     int tiletype = stoi(argv(argv_num)); ++argv_num;
     int dir = stoi(argv(argv_num)); ++argv_num;
     if(bd_canfill(tiletype))
     {
         int letter = minigame_tile_letter(tilename);
         int number = minigame_tile_number(tilename);
         entity controller = bd_find_controller(minigame, letter);
         controller.bd_tiletypes[number] = tiletype;
         controller.bd_dirs[number] = dir;
         bd_controller_update(controller, number);
     }
     else
     {
         entity e = msle_spawn(minigame,new(minigame_board_piece));
         e.netname = tilename;
         e.team = 1;
         e.bd_dir = dir;
         e.bd_tiletype = tiletype;
         minigame_server_sendflags(e,MINIG_SF_ALL);
     }
 }
bd_move()
void bd_move (entity minigame, entity player, string dir)
Definition at line 339 of file bd.qc.
References bd_check_winner(), bd_dir_fromname(), bd_find_dozer(), bd_move_dozer(), BD_SF_PLAYERMOVES, BD_TURN_MOVE, entity(), findentity(), LOG_INFO, MINIG_SF_UPDATE, minigame_server_sendflags(), NULL, and owner.
Referenced by bd_do_move().
 {
     if ( minigame.minigame_flags & BD_TURN_MOVE )
     if ( dir )
     {
         //if ( bd_valid_tile(pos) )
         //if ( bd_find_piece(minigame, pos, false) )
         {
             entity dozer = bd_find_dozer(minigame);
             if(!dozer)
             {
                 LOG_INFO("Dozer wasn't found!");
                 return; // should not happen... TODO: end match?
             }
             string thedir = strtolower(dir);
             int bdir = bd_dir_fromname(thedir);
             int moved = 0;
             entity e = NULL;
             while ( ( e = findentity(e,owner,minigame) ) )
                 if ( e.classname == "minigame_board_piece" && e.bd_tiletype == BD_TILE_DOZER )
                 {
                     e.bd_dir = bdir;
                     if(bd_move_dozer(minigame, e))
                         ++moved;
                     minigame_server_sendflags(e,MINIG_SF_UPDATE); // update anyway
                 }
             if(moved)
                 player.bd_moves++;
             bd_check_winner(minigame);
             minigame_server_sendflags(player,BD_SF_PLAYERMOVES);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         }
     }
 }
bd_move_dozer()
bool bd_move_dozer (entity minigame, entity dozer)
Definition at line 252 of file bd.qc.
References bd_find_controller(), bd_find_piece(), bd_get_dir(), BD_TILE_BOULDER, BD_TILE_BRICK1, BD_TILE_BRICK2, BD_TILE_BRICK3, BD_TILE_BRICK4, BD_TILE_BRICK5, BD_TILE_BRICK6, BD_TILE_BRICK7, BD_TILE_BRICK8, BD_TILE_DOZER, bd_valid_tile(), dir, entity(), MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), number, strcpy, and vector().
Referenced by bd_move().
 {
     //if(!dozer.bd_dir)
         //return false; // nope!
     int myx = minigame_tile_letter(dozer.netname);
     int myy = minigame_tile_number(dozer.netname);
     vector dir = bd_get_dir(dozer.bd_dir);
     myx += dir.x;
     myy += dir.y;
     string newpos = minigame_tile_buildname(myx, myy);
     if(!bd_valid_tile(newpos))
         return false;
     entity hit = bd_find_piece(minigame, newpos, false);
     if(hit)
     switch(hit.bd_tiletype)
     {
         case BD_TILE_DOZER: // wtf, but let's do this incase
         case BD_TILE_BRICK8:
         case BD_TILE_BRICK7:
         case BD_TILE_BRICK6:
         case BD_TILE_BRICK5:
         case BD_TILE_BRICK4:
         case BD_TILE_BRICK3:
         case BD_TILE_BRICK2:
         case BD_TILE_BRICK1: return false;
         case BD_TILE_BOULDER:
         {
             string testpos;
             int tx = minigame_tile_letter(hit.netname);
             int ty = minigame_tile_number(hit.netname);
             tx += dir.x;
             ty += dir.y;
             testpos = minigame_tile_buildname(tx, ty);
             if(!bd_valid_tile(testpos))
                 return false;
             entity testhit = bd_find_piece(minigame, testpos, false);
             if(testhit)
                 return false;
             entity controller = bd_find_controller(minigame, minigame_tile_letter(testpos));
             int tnum = minigame_tile_number(testpos);
             switch(controller.bd_tiletypes[tnum])
             {
                 case BD_TILE_BRICK8:
                 case BD_TILE_BRICK7:
                 case BD_TILE_BRICK6:
                 case BD_TILE_BRICK5:
                 case BD_TILE_BRICK4:
                 case BD_TILE_BRICK3:
                 case BD_TILE_BRICK2:
                 case BD_TILE_BRICK1: return false;
             }
             strcpy(hit.netname, testpos);
             minigame_server_sendflags(hit,MINIG_SF_UPDATE);
             break;
         }
     }
     entity controller = bd_find_controller(minigame, minigame_tile_letter(newpos));
     int number = minigame_tile_number(newpos);
     switch(controller.bd_tiletypes[number])
     {
         case BD_TILE_BRICK8:
         case BD_TILE_BRICK7:
         case BD_TILE_BRICK6:
         case BD_TILE_BRICK5:
         case BD_TILE_BRICK4:
         case BD_TILE_BRICK3:
         case BD_TILE_BRICK2:
         case BD_TILE_BRICK1: return false;
     }
     strcpy(dozer.netname, newpos);
     return true;
 }
bd_next_match()
void bd_next_match (entity minigame, entity player, string next)
Definition at line 613 of file bd.qc.
References bd_do_next_match(), bd_set_next_match(), BD_TURN_EDIT, and BD_TURN_WIN.
Referenced by bd_close_editor().
 {
     if(minigame.minigame_flags & BD_TURN_WIN)
         bd_do_next_match(minigame, player);
     if(minigame.minigame_flags & BD_TURN_EDIT)
         bd_set_next_match(minigame, next);
 }
bd_reset_moves()
void bd_reset_moves (entity minigame)
Definition at line 547 of file bd.qc.
References bd_load_level(), BD_SF_PLAYERMOVES, entity(), findentity(), minigame_server_sendflags(), NULL, and owner.
Referenced by bd_activate_editor(), bd_do_next_match(), and bd_restart_match().
 {
     entity e;
 #ifdef SVQC
     for(e = minigame.minigame_players; e; e = e.list_next)
 #elif defined(CSQC)
     e = NULL;
     while( (e = findentity(e,owner,minigame)) )
         if ( e.classname == "minigame_player" )
 #endif
         {
             e.bd_moves = 0;
             minigame_server_sendflags(e,BD_SF_PLAYERMOVES);
         }
 }
bd_restart_match()
void bd_restart_match (entity minigame, entity player)
Definition at line 622 of file bd.qc.
References bd_reset_moves(), bd_setup_pieces(), BD_TURN_MOVE, MINIG_SF_UPDATE, and minigame_server_sendflags().
Referenced by bd_close_editor().
 {
     minigame.minigame_flags = BD_TURN_MOVE;
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     bd_setup_pieces(minigame);
     bd_reset_moves(minigame);
 }
bd_save_controller_piece()
string bd_save_controller_piece (entity minigame, entity e, int number)
Definition at line 650 of file bd.qc.
References ftos(), minigame_tile_buildname(), and strcat().
Referenced by bd_save_level().
 {
     string bd_string = "";
     string tilename = minigame_tile_buildname(e.bd_tilelet, number);
     bd_string = strcat(bd_string, "\"", tilename, "\" ");
     bd_string = strcat(bd_string, ftos(e.bd_tiletypes[number]), " ");
     bd_string = strcat(bd_string, ftos(e.bd_dirs[number]));
     return bd_string;
 }
bd_save_level()
bool bd_save_level (entity minigame)
Definition at line 724 of file bd.qc.
References BD_NUM_CNT, bd_save_controller_piece(), bd_save_piece(), entity(), fclose(), fexists(), FILE_WRITE, findentity(), fopen(), fputs(), LOG_INFO, NULL, owner, and strcat().
Referenced by bd_close_editor().
 {
     if(minigame.bd_levelname && minigame.bd_levelname != "")
     {
         int target_count = 0, boulder_count = 0;
         entity piece = NULL;
         while((piece = findentity(piece,owner,minigame)))
             if(piece.classname == "minigame_board_piece")
             {
                 if(piece.bd_tiletype == BD_TILE_BOULDER)
                     ++boulder_count;
                 else if(piece.bd_tiletype == BD_TILE_TARGET)
                     ++target_count;
             }
         if(boulder_count != target_count)
         {
             LOG_INFO("Not enough targets or boulders, fix your level!");
             return false;
         }
         // saves all objects to the database file
         string file_name;
         float file_get;
         file_name = strcat("minigames/bulldozer/storage_", minigame.bd_levelname, ".txt");
         file_get = fopen(file_name, FILE_WRITE);
         fputs(file_get, strcat("// bulldozer storage \"", minigame.bd_levelname, "\" last updated ", strftime(true, "%d-%m-%Y %H:%M:%S"), "\n"));
         if(minigame.bd_nextlevel && minigame.bd_nextlevel != "" && fexists(strcat("minigames/bulldozer/storage_", minigame.bd_nextlevel, ".txt")))
             fputs(file_get, strcat("nextlevel = \"", minigame.bd_nextlevel, "\"\n"));
         entity e = NULL;
         while ( ( e = findentity(e,owner,minigame) ) )
         if ( e.classname == "bd_controller" )
         {
             for(int j = 0; j < BD_NUM_CNT; ++j)
             {
                 // use a line of text for each object, listing all properties
                 fputs(file_get, strcat(bd_save_controller_piece(minigame, e, j), "\n"));
             }
         }
         e = NULL;
         while ( ( e = findentity(e,owner,minigame) ) )
         if ( e.classname == "minigame_board_piece" )
         {
             // use a line of text for each object, listing all properties
             fputs(file_get, strcat(bd_save_piece(minigame, e), "\n"));
         }
         fclose(file_get);
         return true;
     }
     return false;
 }
bd_save_piece()
string bd_save_piece (entity minigame, entity e)
Definition at line 663 of file bd.qc.
References ftos(), and strcat().
Referenced by bd_save_level().
 {
     string bd_string = "";
     bd_string = strcat(bd_string, "\"", e.netname, "\" ");
     bd_string = strcat(bd_string, ftos(e.bd_tiletype), " ");
     bd_string = strcat(bd_string, ftos(e.bd_dir));
     return bd_string;
 }
bd_set_next_match()
void bd_set_next_match (entity minigame, string next)
Definition at line 608 of file bd.qc.
References strcpy.
Referenced by bd_next_match().
 {
     strcpy(minigame.bd_nextlevel, next);
 }
bd_set_nextlevel()
void bd_set_nextlevel (entity minigame, string s)
Definition at line 674 of file bd.qc.
References argv(), strcpy, and tokenize_console.
Referenced by bd_load_level().
 {
     tokenize_console(s);
     strcpy(minigame.bd_nextlevel, argv(2));
 }
bd_setup_pieces()
void bd_setup_pieces (entity minigame)
Definition at line 564 of file bd.qc.
References BD_LET_CNT, bd_load_level(), entity(), findentity(), new_pure, NULL, owner, and strfree.
Referenced by bd_activate_editor(), bd_close_editor(), bd_do_next_match(), and bd_restart_match().
 {
     entity e = NULL;
     while( (e = findentity(e, owner, minigame)) )
         if(e.classname == "minigame_board_piece")
         {
             strfree(e.netname);
             delete(e);
         }
     e = NULL;
     while( (e = findentity(e, owner, minigame)) )
         if(e.classname == "bd_controller")
         {
             delete(e);
         }
     for(int letter = 0; letter < BD_LET_CNT; ++letter)
     {
         entity controller = new_pure(bd_controller);
         controller.owner = minigame;
         controller.bd_tilelet = letter;
     #ifdef SVQC
         Net_LinkEntity(controller, false, 0, bd_controller_send);
     #endif
     }
     bd_load_level(minigame);
 }
bd_unfill_recurse()
void bd_unfill_recurse (entity minigame, entity player, int thetype, int letter, int number)
Definition at line 479 of file bd.qc.
References bd_find_piece(), bd_valid_tile(), entity(), minigame_tile_buildname(), and strfree.
Referenced by bd_do_fill().
 {
     string pos = minigame_tile_buildname(letter,number);
     if(!bd_valid_tile(pos))
         return;
     entity targ = bd_find_piece(minigame, pos, true);
     entity piece = bd_find_piece(minigame, pos, false);
     if(targ && thetype == targ.bd_tiletype)
     {
         strfree(targ.netname);
         delete(targ);
     }
     else if(piece && thetype == piece.bd_tiletype)
     {
         strfree(piece.netname);
         delete(piece);
     }
     else return;
     bd_unfill_recurse(minigame, player, thetype, letter - 1, number);
     bd_unfill_recurse(minigame, player, thetype, letter + 1, number);
     bd_unfill_recurse(minigame, player, thetype, letter, number - 1);
     bd_unfill_recurse(minigame, player, thetype, letter, number + 1);
 }
bd_valid_tile()
bool bd_valid_tile (string tile)
Definition at line 87 of file bd.qc.
References BD_LET_CNT, minigame_tile_letter(), minigame_tile_number(), and number.
Referenced by bd_close_editor(), bd_editor_place(), bd_fill_recurse(), bd_move_dozer(), and bd_unfill_recurse().
 {
     if ( !tile )
         return false;
     int number = minigame_tile_number(tile);
     int letter = minigame_tile_letter(tile);
     return 0 <= number && number < BD_NUM_CNT && 0 <= letter && letter < BD_LET_CNT;
 }
REGISTER_MINIGAME()
REGISTER_MINIGAME (bd , _("Bulldozer"))
Variable Documentation
bd_dir
int bd_dir
Definition at line 26 of file bd.qc.
BD_DIR_DN
const int BD_DIR_DN = 1
Definition at line 59 of file bd.qc.
Referenced by bd_close_editor(), bd_dir_fromname(), bd_fix_dir(), bd_get_dir(), and bd_get_dir_name().
BD_DIR_LF
const int BD_DIR_LF = 2
Definition at line 60 of file bd.qc.
Referenced by bd_close_editor(), bd_dir_fromname(), bd_fix_dir(), bd_get_dir(), and bd_get_dir_name().
BD_DIR_RT
const int BD_DIR_RT = 3
Definition at line 61 of file bd.qc.
Referenced by bd_close_editor(), bd_dir_fromname(), bd_fix_dir(), bd_get_dir(), and bd_get_dir_name().
BD_DIR_UP
const int BD_DIR_UP = 0
Definition at line 58 of file bd.qc.
Referenced by bd_close_editor(), bd_dir_fromname(), bd_fix_dir(), bd_get_dir(), and bd_get_dir_name().
bd_dirs
int bd_dirs[BD_NUM_CNT]
Definition at line 28 of file bd.qc.
Referenced by bd_find_dozer().
BD_LET_CNT
const int BD_LET_CNT = 20
Definition at line 18 of file bd.qc.
Referenced by bd_setup_pieces(), and bd_valid_tile().
bd_levelname
string bd_levelname
Definition at line 34 of file bd.qc.
bd_moves
int bd_moves
Definition at line 30 of file bd.qc.
bd_nextlevel
string bd_nextlevel
Definition at line 35 of file bd.qc.
BD_NUM_CNT
const int BD_NUM_CNT = 20
Definition at line 19 of file bd.qc.
Referenced by bd_close_editor(), bd_find_dozer(), and bd_save_level().
BD_SF_PLAYERMOVES
const int BD_SF_PLAYERMOVES = MINIG_SF_CUSTOM
Definition at line 13 of file bd.qc.
Referenced by bd_close_editor(), bd_move(), and bd_reset_moves().
BD_SF_UPDATE_ALL
const int BD_SF_UPDATE_ALL = MINIG_SF_CUSTOM<<2
Definition at line 15 of file bd.qc.
Referenced by bd_find_dozer().
BD_SF_UPDATE_SINGLE
const int BD_SF_UPDATE_SINGLE = MINIG_SF_CUSTOM<<1
Definition at line 14 of file bd.qc.
Referenced by bd_controller_update(), and bd_find_dozer().
BD_SPECTATOR_TEAM
const int BD_SPECTATOR_TEAM = 255
Definition at line 24 of file bd.qc.
Referenced by bd_close_editor().
BD_TEAMS
const int BD_TEAMS = 1
Definition at line 23 of file bd.qc.
BD_TILE_BOULDER
const int BD_TILE_BOULDER = 3
Definition at line 47 of file bd.qc.
Referenced by bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK1
const int BD_TILE_BRICK1 = 4
Definition at line 48 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK2
const int BD_TILE_BRICK2 = 5
Definition at line 49 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK3
const int BD_TILE_BRICK3 = 6
Definition at line 50 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK4
const int BD_TILE_BRICK4 = 7
Definition at line 51 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK5
const int BD_TILE_BRICK5 = 8
Definition at line 52 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK6
const int BD_TILE_BRICK6 = 9
Definition at line 53 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK7
const int BD_TILE_BRICK7 = 10
Definition at line 54 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_BRICK8
const int BD_TILE_BRICK8 = 11
Definition at line 55 of file bd.qc.
Referenced by bd_canfill(), bd_close_editor(), and bd_move_dozer().
BD_TILE_DOZER
const int BD_TILE_DOZER = 1
Definition at line 45 of file bd.qc.
Referenced by bd_close_editor(), and bd_move_dozer().
BD_TILE_LAST
const int BD_TILE_LAST = 11
Definition at line 56 of file bd.qc.
BD_TILE_SIZE
const int BD_TILE_SIZE = 20
Definition at line 21 of file bd.qc.
BD_TILE_TARGET
const int BD_TILE_TARGET = 2
Definition at line 46 of file bd.qc.
Referenced by bd_close_editor().
bd_tilelet
int bd_tilelet
Definition at line 32 of file bd.qc.
bd_tiletype
int bd_tiletype
Definition at line 44 of file bd.qc.
bd_tiletypes
int bd_tiletypes[BD_NUM_CNT]
Definition at line 42 of file bd.qc.
Referenced by bd_find_dozer().
BD_TURN_EDIT
const int BD_TURN_EDIT = 0x0800
Definition at line 9 of file bd.qc.
Referenced by bd_activate_editor(), bd_close_editor(), bd_do_fill(), bd_do_move(), bd_editor_place(), and bd_next_match().
BD_TURN_LOSS
const int BD_TURN_LOSS = 0x0400
Definition at line 8 of file bd.qc.
Referenced by bd_close_editor().
BD_TURN_MOVE
const int BD_TURN_MOVE = 0x0100
Definition at line 6 of file bd.qc.
Referenced by bd_close_editor(), bd_do_move(), bd_do_next_match(), bd_move(), and bd_restart_match().
BD_TURN_TYPE
const int BD_TURN_TYPE = 0x0f00
Definition at line 10 of file bd.qc.
BD_TURN_WIN
const int BD_TURN_WIN = 0x0200
Definition at line 7 of file bd.qc.
Referenced by bd_check_winner(), bd_close_editor(), and bd_next_match().