Xonotic: common/gamemodes/gamemode/onslaught/sv_onslaught.qh File Reference
sv_onslaught.qh File Reference
Macros
#define CPGEN_SPAWN_OFFSET ('0 0 1' * (PL_MAX_CONST.z - 13))
Functions
void havocbot_goalrating_enemyplayers (entity this, float ratingscale, vector org, float sradius)
void havocbot_goalrating_items (entity this, float ratingscale, vector org, float sradius)
void havocbot_ons_reset_role (entity this)
void havocbot_role_ons_assistant (entity this)
void havocbot_role_ons_defense (entity this)
void havocbot_role_ons_offense (entity this)
bool ons_ControlPoint_Attackable (entity cp, int teamnumber)
void ons_ControlPoint_UpdateSprite (entity e)
void ons_Generator_UpdateSprite (entity e)
void ons_Initialize ()
REGISTER_MUTATOR (ons, false)
Variables
float autocvar_g_onslaught_point_limit
entity bot_basewaypoint
const vector CPGEN_WAYPOINT_OFFSET = ('0 0 128')
const vector CPICON_OFFSET = ('0 0 96')
const float GEN_THINKRATE = 1
float havocbot_attack_time
const int HAVOCBOT_ONS_ROLE_ASSISTANT = 4
const int HAVOCBOT_ONS_ROLE_DEFENSE = 2
const int HAVOCBOT_ONS_ROLE_NONE = 0
const int HAVOCBOT_ONS_ROLE_OFFENSE = 8
entity havocbot_ons_target
int havocbot_role_flags
int iscaptured
bool iscpneighbor [17]
bool isgenneighbor [17]
int islinked
int isshielded
int lastcaptured
float lasthealth
int lastshielded
int lastteam
float ons_captureshield_force
const float ONS_CP_THINKRATE = 0.2
vector ons_deathloc
float ons_notification_time [17]
float ons_overtime_damagedelay
entity ons_spawn_by
entity ons_stalecpnext
entity ons_stalelinknext
bool ons_stalemate
entity ons_toucher
entity ons_worldcplist
entity ons_worldcpnext
entity ons_worldgeneratorlist
entity ons_worldgeneratornext
entity ons_worldlinklist
entity ons_worldlinknext
entity sprite
const int ST_ONS_CAPS = 1
string target2
float teleport_antispam
bool waslinked
Macro Definition Documentation
#define CPGEN_SPAWN_OFFSET ('0 0 1' * (PL_MAX_CONST.z - 13))
Definition at line 40 of file sv_onslaught.qh.
Referenced by ons_GeneratorSetup().
Function Documentation
void havocbot_goalrating_enemyplayers (entity this, float ratingscale, vector org, float sradius)
Definition at line 121 of file roles.qc.
Referenced by havocbot_role_ast_defense(), havocbot_role_ast_offense(), havocbot_role_ctf_defense(), havocbot_role_ctf_middle(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_ka_carrier(), havocbot_role_ka_collector(), and havocbot_role_ons_offense().
 {
     if (autocvar_bot_nofire)
         return;
     // don't chase players if we're under water
     if(this.waterlevel>WATERLEVEL_WETFEET)
         return;
     int t;
     FOREACH_CLIENT(IS_PLAYER(it) && bot_shouldattack(this, it), LAMBDA(
         // TODO: Merge this logic with the bot_shouldattack function
         if(vdist(it.origin - org, <, 100) || vdist(it.origin - org, >, sradius))
             continue;
         // rate only visible enemies
         /*
         traceline(this.origin + this.view_ofs, it.origin, MOVE_NOMONSTERS, this);
         if (trace_fraction < 1 || trace_ent != it)
             continue;
         */
         if((it.flags & FL_INWATER) || (it.flags & FL_PARTIALGROUND))
             continue;
         // not falling
         if((IS_ONGROUND(it)) == 0)
         {
             traceline(it.origin, it.origin + '0 0 -1500', true, NULL);
             t = pointcontents(trace_endpos + '0 0 1');
             if(t != CONTENT_SOLID )
             if(t & CONTENT_WATER || t & CONTENT_SLIME || t & CONTENT_LAVA)
                 continue;
             if(tracebox_hits_trigger_hurt(it.origin, it.mins, it.maxs, trace_endpos))
                 continue;
         }
         // TODO: rate waypoints near the targetted player at that moment, instead of the player itthis
         //       adding a player as a goal seems to be quite dangerous, especially on space maps
         //       remove hack in navigation_poptouchedgoals() after performing this change
         t = (this.health + this.armorvalue ) / (it.health + it.armorvalue );
         navigation_routerating(this, it, t * ratingscale, 2000);
     ));
 }
void havocbot_goalrating_items (entity this, float ratingscale, vector org, float sradius)
Definition at line 16 of file roles.qc.
Referenced by havocbot_goalrating_kh(), havocbot_role_ast_defense(), havocbot_role_ast_offense(), havocbot_role_ctf_defense(), havocbot_role_ctf_escort(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), havocbot_role_dom(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_ka_carrier(), and havocbot_role_ka_collector().
 {
     float rating, d, discard, friend_distance, enemy_distance;
     vector o;
     ratingscale = ratingscale * 0.0001; // items are rated around 10000 already
     IL_EACH(g_items, it.bot_pickup,
     {
         o = (it.absmin + it.absmax) * 0.5;
         friend_distance = 10000; enemy_distance = 10000;
         rating = 0;
         if(!it.solid || vdist(o - org, >, sradius) || (it == this.ignoregoal && time < this.ignoregoaltime) )
             continue;
         // Check if the item can be picked up safely
         if(it.classname == "droppedweapon")
         {
             traceline(o, o + '0 0 -1500', true, NULL);
             d = pointcontents(trace_endpos + '0 0 1');
             if(d & CONTENT_WATER || d & CONTENT_SLIME || d & CONTENT_LAVA)
                 continue;
             if(tracebox_hits_trigger_hurt(it.origin, it.mins, it.maxs, trace_endpos))
                 continue;
         }
         else
         {
             // Ignore items under water
             traceline(it.origin + it.maxs, it.origin + it.maxs, MOVE_NORMAL, it);
             if(trace_dpstartcontents & DPCONTENTS_LIQUIDSMASK)
                 continue;
         }
         if(teamplay)
         {
             discard = false;
             entity picker = it;
             FOREACH_CLIENT(IS_PLAYER(it) && it != this && !IS_DEAD(it),
             {
                 d = vlen(it.origin - o); // distance between player and item
                 if ( it.team == this.team )
                 {
                     if ( !IS_REAL_CLIENT(it) || discard )
                         continue;
                     if( d > friend_distance)
                         continue;
                     friend_distance = d;
                     discard = true;
                     if( picker.health && it.health > this.health )
                         continue;
                     if( picker.armorvalue && it.armorvalue > this.armorvalue)
                         continue;
                     if( picker.weapons )
                     if( picker.weapons & ~it.weapons )
                         continue;
                     if (picker.ammo_shells && it.ammo_shells > this.ammo_shells)
                         continue;
                     if (picker.ammo_nails && it.ammo_nails > this.ammo_nails)
                         continue;
                     if (picker.ammo_rockets && it.ammo_rockets > this.ammo_rockets)
                         continue;
                     if (picker.ammo_cells && it.ammo_cells > this.ammo_cells)
                         continue;
                     if (picker.ammo_plasma && it.ammo_plasma > this.ammo_plasma)
                         continue;
                     discard = false;
                 }
                 else
                 {
                     // If enemy only track distances
                     // TODO: track only if visible ?
                     if( d < enemy_distance )
                         enemy_distance = d;
                 }
             });
             // Rate the item only if no one needs it, or if an enemy is closer to it
             if ( (enemy_distance < friend_distance && vdist(o - org, <, enemy_distance)) ||
                 (friend_distance > autocvar_bot_ai_friends_aware_pickup_radius ) || !discard )
                 rating = it.bot_pickupevalfunc(this, it);
         }
         else
             rating = it.bot_pickupevalfunc(this, it);
         if(rating > 0)
             navigation_routerating(this, it, rating * ratingscale, 2000);
     });
 }
void havocbot_ons_reset_role (entity this)
Definition at line 1458 of file sv_onslaught.qc.
References HAVOCBOT_ONS_ROLE_OFFENSE, havocbot_ons_target, havocbot_role_ons_setrole(), IS_DEAD, and NULL.
Referenced by havocbot_role_ons_assistant(), havocbot_role_ons_defense(), havocbot_role_ons_offense(), and MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     this.havocbot_ons_target = NULL;
     // TODO: Defend control points or generator if necessary
     havocbot_role_ons_setrole(this, HAVOCBOT_ONS_ROLE_OFFENSE);
 }
void havocbot_role_ons_assistant (entity this)
Definition at line 1448 of file sv_onslaught.qc.
References havocbot_ons_reset_role().
Referenced by havocbot_role_ons_setrole().
 {
     havocbot_ons_reset_role(this);
 }
void havocbot_role_ons_defense (entity this)
Definition at line 1453 of file sv_onslaught.qc.
References havocbot_ons_reset_role().
Referenced by havocbot_role_ons_setrole().
 {
     havocbot_ons_reset_role(this);
 }
void havocbot_role_ons_offense (entity this)
Definition at line 1413 of file sv_onslaught.qc.
References autocvar_bot_ai_strategyinterval, bot_strategytime, havocbot_attack_time, havocbot_goalrating_enemyplayers(), havocbot_goalrating_ons_controlpoints_attack(), havocbot_goalrating_ons_generator_attack(), havocbot_goalrating_ons_offenseitems(), havocbot_ons_reset_role(), havocbot_role_timeout, IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), origin, and time.
Referenced by havocbot_role_ons_setrole().
 {
     if(IS_DEAD(this))
     {
         this.havocbot_attack_time = 0;
         havocbot_ons_reset_role(this);
         return;
     }
     // Set the role timeout if necessary
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + 120;
     if (time > this.havocbot_role_timeout)
     {
         havocbot_ons_reset_role(this);
         return;
     }
     if(this.havocbot_attack_time>time)
         return;
     if (this.bot_strategytime < time)
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_enemyplayers(this, 20000, this.origin, 650);
         if(!havocbot_goalrating_ons_generator_attack(this, 20000))
             havocbot_goalrating_ons_controlpoints_attack(this, 20000);
         havocbot_goalrating_ons_offenseitems(this, 10000, this.origin, 10000);
         navigation_goalrating_end(this);
         this.bot_strategytime = time + autocvar_bot_ai_strategyinterval;
     }
 }
bool ons_ControlPoint_Attackable (entity cp, int teamnumber)
Definition at line 321 of file sv_onslaught.qc.
References ons_ControlPoint_CanBeLinked().
Referenced by MUTATOR_HOOKFUNCTION(), ons_CaptureShield_Customize(), ons_CaptureShield_Touch(), ons_ControlPoint_Touch(), and ons_ControlPoint_Waypoint().
 {
     int a;
     if(cp.isshielded)
     {
         return 0;
     }
     else if(cp.goalentity)
     {
         // if there's already an icon built, nothing happens
         if(cp.team == teamnumber)
         {
             a = ons_ControlPoint_CanBeLinked(cp, teamnumber);
             if(a) // attackable by enemy?
                 return -2; // EMERGENCY!
             return -1;
         }
         // we know it can be linked, so no need to check
         // but...
         a = ons_ControlPoint_CanBeLinked(cp, teamnumber);
         if(a == 2) // near our generator?
             return 3; // EMERGENCY!
         return 1;
     }
     else
     {
         // free point
         if(ons_ControlPoint_CanBeLinked(cp, teamnumber))
         {
             a = ons_ControlPoint_CanBeLinked(cp, teamnumber); // why was this here NUM_TEAM_1 + NUM_TEAM_2 - t
             if(a == 2)
                 return 4; // GET THIS ONE NOW!
             else
                 return 2; // TOUCH ME
         }
     }
     return 0;
 }
void ons_ControlPoint_UpdateSprite (entity e)
Definition at line 614 of file sv_onslaught.qc.
References colormapPaletteColor, entity(), NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, ons_ControlPoint_CanBeLinked(), ons_ControlPoint_Waypoint(), and s1.
Referenced by onslaught_updatelinks().
 {
     entity s1 = ons_ControlPoint_Waypoint(e);
     WaypointSprite_UpdateSprites(e.sprite, s1, s1, s1);
     bool sh;
     sh = !(ons_ControlPoint_CanBeLinked(e, NUM_TEAM_1) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_2) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_3) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_4));
     if(e.lastteam != e.team + 2 || e.lastshielded != sh || e.iscaptured != e.lastcaptured)
     {
         if(e.iscaptured) // don't mess up build bars!
         {
             if(sh)
             {
                 WaypointSprite_UpdateMaxHealth(e.sprite, 0);
             }
             else
             {
                 WaypointSprite_UpdateMaxHealth(e.sprite, e.goalentity.max_health);
                 WaypointSprite_UpdateHealth(e.sprite, e.goalentity.health);
             }
         }
         if(e.lastshielded)
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, 0.5 * colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, '0.5 0.5 0.5');
         }
         else
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, '0.75 0.75 0.75');
         }
         WaypointSprite_Ping(e.sprite);
         e.lastteam = e.team + 2;
         e.lastshielded = sh;
         e.lastcaptured = e.iscaptured;
     }
 }
void ons_Generator_UpdateSprite (entity e)
Definition at line 793 of file sv_onslaught.qc.
References colormapPaletteColor, entity(), ons_Generator_Waypoint(), and s1.
Referenced by onslaught_updatelinks().
 {
     entity s1 = ons_Generator_Waypoint(e);
     WaypointSprite_UpdateSprites(e.sprite, s1, s1, s1);
     if(e.lastteam != e.team + 2 || e.lastshielded != e.isshielded)
     {
         e.lastteam = e.team + 2;
         e.lastshielded = e.isshielded;
         if(e.lastshielded)
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, 0.5 * colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, '0.5 0.5 0.5');
         }
         else
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, '0.75 0.75 0.75');
         }
         WaypointSprite_Ping(e.sprite);
     }
 }
void ons_Initialize ()
Definition at line 2135 of file sv_onslaught.qc.
References autocvar_g_onslaught_shield_force, g_onslaught, InitializeEntity(), INITPRIO_GAMETYPE, NULL, ons_captureshield_force, and ons_DelayedInit().
Referenced by REGISTER_MUTATOR().
 {
     g_onslaught = true;
     ons_captureshield_force = autocvar_g_onslaught_shield_force;
     InitializeEntity(NULL, ons_DelayedInit, INITPRIO_GAMETYPE);
 }
REGISTER_MUTATOR (ons , false)
Definition at line 6 of file sv_onslaught.qh.
References ActivateTeamplay(), autocvar_g_onslaught_point_limit, autocvar_leadlimit_override, autocvar_timelimit_override, error, have_team_spawns, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, ons_Initialize(), SetLimits(), and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         ons_Initialize();
         ActivateTeamplay();
         SetLimits(autocvar_g_onslaught_point_limit, autocvar_leadlimit_override, autocvar_timelimit_override, -1);
         have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back ons_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return false;
 }
Variable Documentation
float autocvar_g_onslaught_point_limit
Definition at line 3 of file sv_onslaught.qh.
Referenced by REGISTER_MUTATOR().
entity bot_basewaypoint
Definition at line 76 of file sv_onslaught.qh.
Referenced by ctf_DelayedFlagSetup(), and ons_DelayedGeneratorSetup().
const vector CPGEN_WAYPOINT_OFFSET = ('0 0 128')
Definition at line 41 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Setup(), and ons_GeneratorSetup().
const vector CPICON_OFFSET = ('0 0 96')
Definition at line 42 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Icon_Spawn().
const float GEN_THINKRATE = 1
Definition at line 39 of file sv_onslaught.qh.
Referenced by ons_GeneratorReset(), ons_GeneratorSetup(), and ons_GeneratorThink().
float havocbot_attack_time
Definition at line 105 of file sv_onslaught.qh.
Referenced by havocbot_goalrating_ons_controlpoints_attack(), havocbot_goalrating_ons_generator_attack(), havocbot_role_ast_defense(), havocbot_role_ast_offense(), and havocbot_role_ons_offense().
const int HAVOCBOT_ONS_ROLE_ASSISTANT = 4
Definition at line 99 of file sv_onslaught.qh.
Referenced by havocbot_role_ons_setrole().
const int HAVOCBOT_ONS_ROLE_DEFENSE = 2
Definition at line 98 of file sv_onslaught.qh.
Referenced by havocbot_role_ons_setrole().
const int HAVOCBOT_ONS_ROLE_NONE = 0
Definition at line 97 of file sv_onslaught.qh.
const int HAVOCBOT_ONS_ROLE_OFFENSE = 8
Definition at line 100 of file sv_onslaught.qh.
Referenced by havocbot_goalrating_ons_controlpoints_attack(), havocbot_ons_reset_role(), and havocbot_role_ons_setrole().
entity havocbot_ons_target
Definition at line 102 of file sv_onslaught.qh.
Referenced by havocbot_goalrating_ons_controlpoints_attack(), and havocbot_ons_reset_role().
int havocbot_role_flags
Definition at line 104 of file sv_onslaught.qh.
Referenced by havocbot_role_ast_setrole(), and havocbot_role_ons_setrole().
int iscaptured
Definition at line 61 of file sv_onslaught.qh.
bool iscpneighbor[17]
Definition at line 79 of file sv_onslaught.qh.
bool isgenneighbor[17]
Definition at line 78 of file sv_onslaught.qh.
int islinked
Definition at line 62 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Reset(), ons_GeneratorDamage(), and ons_GeneratorReset().
int isshielded
Definition at line 63 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Reset(), ons_GeneratorDamage(), ons_GeneratorReset(), and ons_GeneratorThink().
int lastcaptured
Definition at line 67 of file sv_onslaught.qh.
float lasthealth
Definition at line 64 of file sv_onslaught.qh.
Referenced by ons_GeneratorDamage(), and ons_GeneratorReset().
int lastshielded
Definition at line 66 of file sv_onslaught.qh.
int lastteam
Definition at line 65 of file sv_onslaught.qh.
float ons_captureshield_force
Definition at line 94 of file sv_onslaught.qh.
Referenced by ons_CaptureShield_Touch(), and ons_Initialize().
const float ONS_CP_THINKRATE = 0.2
Definition at line 38 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Spawn(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_Reset(), ons_ControlPoint_Setup(), and ons_ControlPoint_Think().
vector ons_deathloc
Definition at line 84 of file sv_onslaught.qh.
float ons_notification_time[17]
Definition at line 80 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Icon_Damage().
float ons_overtime_damagedelay
Definition at line 82 of file sv_onslaught.qh.
entity ons_spawn_by
Definition at line 86 of file sv_onslaught.qh.
entity ons_stalecpnext
Definition at line 51 of file sv_onslaught.qh.
entity ons_stalelinknext
Definition at line 56 of file sv_onslaught.qh.
bool ons_stalemate
Definition at line 71 of file sv_onslaught.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and Onslaught_CheckWinner().
entity ons_toucher
Definition at line 35 of file sv_onslaught.qh.
Referenced by ons_ControlPoint_Reset(), and ons_ControlPoint_Touch().
entity ons_worldcplist
Definition at line 49 of file sv_onslaught.qh.
Referenced by havocbot_goalrating_ons_controlpoints_attack(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Setup(), ons_Count_SelfControlPoints(), ons_Nearest_ControlPoint(), ons_Nearest_ControlPoint_2D(), Onslaught_CheckWinner(), Onslaught_RoundStart(), and onslaught_updatelinks().
entity ons_worldcpnext
Definition at line 50 of file sv_onslaught.qh.
entity ons_worldgeneratorlist
Definition at line 45 of file sv_onslaught.qh.
Referenced by havocbot_goalrating_ons_generator_attack(), MUTATOR_HOOKFUNCTION(), ons_Count_SelfControlPoints(), ons_GeneratorSetup(), ons_Nearest_ControlPoint(), ons_Nearest_ControlPoint_2D(), Onslaught_CheckWinner(), Onslaught_count_generators(), Onslaught_RoundStart(), and onslaught_updatelinks().
entity ons_worldgeneratornext
Definition at line 46 of file sv_onslaught.qh.
entity ons_worldlinklist
Definition at line 54 of file sv_onslaught.qh.
Referenced by onslaught_updatelinks(), and spawnfunc().
entity ons_worldlinknext
Definition at line 55 of file sv_onslaught.qh.
Referenced by spawnfunc().
entity sprite
Definition at line 59 of file sv_onslaught.qh.
Referenced by dom_controlpoint_setup(), dompoint_captured(), dompointtouch(), Monster_Damage(), Monster_Move(), Monster_Remove(), Monster_Spawn_Setup(), ons_ControlPoint_Reset(), ons_ControlPoint_Setup(), ons_GeneratorDamage(), ons_GeneratorReset(), and ons_GeneratorSetup().
const int ST_ONS_CAPS = 1
Definition at line 116 of file sv_onslaught.qh.
Referenced by ons_ScoreRules(), and Onslaught_CheckWinner().
string target2
Definition at line 60 of file sv_onslaught.qh.
Referenced by ons_DelayedLinkSetup(), spawnfunc(), SUB_UseTargets_Ex(), trigger_keylock_touch(), and WarpZone_Touch().
float teleport_antispam
Definition at line 73 of file sv_onslaught.qh.
bool waslinked
Definition at line 69 of file sv_onslaught.qh.