Xonotic: lib/string.qh File Reference
string.qh File Reference
#include "nil.qh"
#include "sort.qh"
#include "oo.qh"
Macros
#define DAYS_UP_TO_EPOCH 719469
#define DEC_TO_HEXDIGIT(d) (substring(HEXDIGITS_MINSET, (d), 1))
#define endsWith(this, suffix) (_endsWith_suffix = suffix, substring(this, -strlen(_endsWith_suffix), -1) == _endsWith_suffix)
#define HEXDIGIT_TO_DEC(d) ((HEXDIGIT_TO_DEC_RAW(d) | 0x10) - 0x10)
#define HEXDIGIT_TO_DEC_RAW(d) (strstrofs(HEXDIGITS, (d), 0))
#define IS_DIGIT(d) (strstrofs(DIGITS, (d), 0) >= 0)
#define IS_HEXDIGIT(d) (strstrofs(HEXDIGITS_MINSET, (d), 0) >= 0)
#define startsWith(haystack, needle) (strstrofs(haystack, needle, 0) == 0)
#define strcpy(this, s)
#define strfree(this)
#define strhasword(s, w) (strstrofs(strcat(" ", s, " "), strcat(" ", w, " "), 0) >= 0)
Functions
ERASEABLE void _shufflewords_swapfunc (float i, float j, entity pass)
ERASEABLE int buf_load (string pFilename)
ERASEABLE void buf_save (float buf, string pFilename)
ERASEABLE string car (string s)
returns first word
ERASEABLE string cdr (string s)
returns all but first word
ERASEABLE vector checkColorCode (string theText, int text_len, int pos, bool check_at_the_end)
ERASEABLE string ColorTranslateRGB (string s)
ERASEABLE string cons (string a, string b)
ERASEABLE string cons_mid (string a, string mid, string b)
ERASEABLE int days_up_to_date (int Y, int M, int D)
ERASEABLE string format_time (float seconds)
ERASEABLE string fstrunzone (string s)
unzone the string, and return it as tempstring.
ERASEABLE string ftos_decimals (float number, int decimals)
converts a number to a string with the indicated number of decimals
ERASEABLE string ftos_mindecimals (float number)
converts a number to a string with the minimum number of decimals
ERASEABLE bool isCaretEscaped (string theText, float pos)
ERASEABLE bool isInvisibleString (string s)
ERASEABLE bool isValidColorCodeValue (string theText, int cc_len, int tag_start)
ERASEABLE string mmsss (float tenths)
ERASEABLE string mmssss (float hundredths)
ERASEABLE string seconds_tostring (float sec)
ERASEABLE string shufflewords (string str)
ERASEABLE bool startsWithNocase (string haystack, string needle)
ERASEABLE string strftime_s ()
ERASEABLE string strwords (string s, int w)
ERASEABLE string substring_range (string s, float b, float e)
ERASEABLE string swapwords (string str, float i, float j)
ERASEABLE int u8_strsize (string s)
ERASEABLE string unescape (string in)
ERASEABLE int vercmp (string v1, string v2)
ERASEABLE int vercmp_recursive (string v1, string v2)
Variables
noref string _endsWith_suffix
string _shufflewords_str
int ColorTranslateMode
const string DIGITS = "0123456789"
const string HEXDIGITS = "0123456789ABCDEF0123456789abcdef"
const string HEXDIGITS_MINSET = "0123456789ABCDEFabcdef"
Macro Definition Documentation
DAYS_UP_TO_EPOCH
#define DAYS_UP_TO_EPOCH 719469
Definition at line 82 of file string.qh.
Referenced by strftime_s().
DEC_TO_HEXDIGIT
#define DEC_TO_HEXDIGIT (d) (substring(HEXDIGITS_MINSET, (d), 1))
Definition at line 491 of file string.qh.
Referenced by rgb_to_hexcolor().
endsWith
#define endsWith (this, suffix) (_endsWith_suffix = suffix, substring(this, -strlen(_endsWith_suffix), -1) == _endsWith_suffix)
Definition at line 214 of file string.qh.
Referenced by spawnfunc(), and SUB_CalcAngleMoveEnt().
HEXDIGIT_TO_DEC
#define HEXDIGIT_TO_DEC (d) ((HEXDIGIT_TO_DEC_RAW(d) | 0x10) - 0x10)
Definition at line 490 of file string.qh.
Referenced by InputBox_draw().
HEXDIGIT_TO_DEC_RAW
#define HEXDIGIT_TO_DEC_RAW (d) (strstrofs(HEXDIGITS, (d), 0))
Definition at line 489 of file string.qh.
IS_DIGIT
#define IS_DIGIT (d) (strstrofs(DIGITS, (d), 0) >= 0)
Definition at line 495 of file string.qh.
Referenced by bot_cmd_eval(), find_last_color_code(), InputBox_draw(), isValidColorCodeValue(), and XonoticServerList_drawListBoxItem().
IS_HEXDIGIT
#define IS_HEXDIGIT (d) (strstrofs(HEXDIGITS_MINSET, (d), 0) >= 0)
Definition at line 492 of file string.qh.
Referenced by find_last_color_code(), and isValidColorCodeValue().
startsWith
#define startsWith (haystack, needle) (strstrofs(haystack, needle, 0) == 0)
Definition at line 205 of file string.qh.
Referenced by _MapInfo_Generate(), spawnfunc(), WarpZoneLib_BadEntity(), and XonoticKeyBinder_drawListBoxItem().
strcpy
#define strcpy (this, s)
Value:
MACRO_BEGIN \
    if (this) { \
        strunzone(this); \
    } \
    this = strzone(s); \
MACRO_END
Definition at line 49 of file string.qh.
Referenced by Accuracy_LoadLevels(), bd_close_editor(), bd_do_next_match(), bd_move_dozer(), bd_set_next_match(), bd_set_nextlevel(), bot_custom_weapon_priority_setup(), bot_decodecommand(), centerprint_Add(), Cmd_Scoreboard_SetFields(), DamageText::DamageText_update(), GENERIC_COMMAND(), GetCvars_handleString(), GetCvars_handleString_Fixup(), getwelcomemessage(), HUD_Chat(), HUD_Main(), HUD_Panel_FirstInDrawQ(), HUD_Radar(), HUD_Weapons(), Label_draw(), Label_setText(), LoadPlayerSounds(), Local_Notification_sprintf(), LocalCommand_sendcvar(), m_goto(), m_tooltip(), Maplist_Init(), Model::Model ::model_precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), OnlineBanList_Think(), PlayerPreThink(), ps_move_piece(), queue_to_execute_next_frame(), QuickMenu_Page_Load(), QuickMenu_Page_LoadEntry(), QuickMenu_skip_submenu(), race_checkAndWriteName(), race_deleteTime(), race_SendTime(), race_setTime(), sandbox_ObjectPort_Load(), Scoreboard_Draw(), Sound::Sound ::sound_precache(), spawnfunc(), swapInPriorityList(), UpdatePlayerSounds(), W_FixWeaponOrder_ForceComplete_AndBuildImpulseList(), W_Reload(), waypoint_loadall(), waypoint_saveall(), WinningConditionHelper(), XonoticCampaignList_loadCvars(), XonoticCrosshairPreview_draw(), XonoticCvarList_setSelected(), XonoticMapInfoDialog_loadMapInfo(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticPlayerModelSelector_go(), XonoticScreenshotBrowserTab_loadPreviewScreenshot(), XonoticScreenshotImage_load(), XonoticScreenshotViewerDialog_loadScreenshot(), XonoticServerList_draw(), and XonoticServerList_setSelected().
strfree
#define strfree (this)
Value:
MACRO_BEGIN \
    if (this) { \
        strunzone(this); \
    } \
    this = string_null; \
MACRO_END
Definition at line 56 of file string.qh.
Referenced by bd_close_editor(), bd_editor_place(), bd_setup_pieces(), bd_unfill_recurse(), BGMScript_InitEntity(), bot_clientdisconnect(), c4_move(), CampaignFile_Unload(), centerprint_KillAll(), ClearPlayerSounds(), ClientDisconnect(), Cmd_Scoreboard_SetFields(), cvar_changes_init(), DamageText::DamageText ::~ DamageText(), DelayThink(), DemoList_Filter_Change(), end_minigame(), execute_next_frame(), func_ladder_think(), GameType_ConfigureSliders(), GENERIC_COMMAND(), GetCvars_handleString(), HUD_Crosshair(), HUDSkinList_Filter_Change(), HUDSkinList_SavedName_Change(), InputBox_setText(), ItemRemove(), Local_Notification_WOVA(), LocalCommand_sendcvar(), m_init_delayed(), m_tooltip(), MapList_StringFilterBox_Change(), MapVote_UnzoneStrings(), MUTATOR_HOOKFUNCTION(), MX_Say_(), NET_HANDLE(), nmm_kill_tiles(), pp_move(), pp_next_match(), ps_move(), ps_move_piece(), QuickMenu_Close(), QuickMenu_Page_ClearEntry(), QuickMenu_skip_submenu(), race_CheckName(), race_ClearRecords(), rewrapCampaign(), sandbox_ObjectPort_Load(), sandbox_ObjectRemove(), Scoreboard_Rankings_Draw(), ScreenshotList_Filter_Change(), ServerList_Filter_Change(), setZonedTooltip(), SL_ProcessCategoryOverrides(), SoundList_Filter_Change(), STATIC_INIT(), trigger_push_findtarget(), ttt_next_match(), url_fclose(), url_multi_ready(), url_single_fopen(), url_URI_Get_Callback(), VoteReset(), XonoticCvarList_setSelected(), XonoticKeyBinder_destroy(), XonoticServerInfoDialog_loadServerInfo(), and XonoticServerList_setSortOrder().
strhasword
#define strhasword (s, w) (strstrofs(strcat(" ", s, " "), strcat(" ", w, " "), 0) >= 0)
Definition at line 340 of file string.qh.
Referenced by CvarList_Revert_Click(), GL_CheckExtension(), Map_IsRecent(), W_HitPlotOpen(), XonoticCvarList_drawListBoxItem(), and XonoticCvarList_updateCvarType().
Function Documentation
_shufflewords_swapfunc()
ERASEABLE void _shufflewords_swapfunc (float i, float j, entity pass)
Definition at line 289 of file string.qh.
References _shufflewords_str, ERASEABLE, and swapwords().
Referenced by shufflewords().
 {
     _shufflewords_str = swapwords(_shufflewords_str, i, j);
 }
buf_load()
ERASEABLE int buf_load (string pFilename)
Definition at line 406 of file string.qh.
References buf_create, ERASEABLE, fclose(), fgets(), FILE_READ, and fopen().
 {
     int buf = buf_create();
     if (buf < 0) return -1;
     int fh = fopen(pFilename, FILE_READ);
     if (fh < 0)
     {
         buf_del(buf);
         return -1;
     }
     string l;
     for (int i = 0; (l = fgets(fh)); ++i)
         bufstr_set(buf, i, l);
     fclose(fh);
     return buf;
 }
buf_save()
ERASEABLE void buf_save (float buf, string pFilename)
Definition at line 424 of file string.qh.
References ERASEABLE, error(), fclose(), FILE_WRITE, fopen(), fputs(), and strcat().
 {
     int fh = fopen(pFilename, FILE_WRITE);
     if (fh < 0) error(strcat("Can't write buf to ", pFilename));
     int n = buf_getsize(buf);
     for (int i = 0; i < n; ++i)
         fputs(fh, strcat(bufstr_get(buf, i), "\n"));
     fclose(fh);
 }
car()
ERASEABLE string car (string s)
returns first word
Definition at line 228 of file string.qh.
References ERASEABLE, strstrofs, and substring().
Referenced by _MapInfo_Generate(), _MapInfo_Map_ApplyGametype(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), GameCommand_adminmsg(), GameCommand_moveplayer(), get_model_parameters(), GlobalSound_sample(), Local_Notification_sprintf(), MapInfo_Get_ByName_NoFallbacks(), matchacl(), PrecacheGlobalSound(), Process_Notif_Args(), STATIC_INIT_LATE(), and W_GetCycleWeapon().
 {
     int o = strstrofs(s, " ", 0);
     if (o < 0) return s;
     return substring(s, 0, o);
 }
cdr()
ERASEABLE string cdr (string s)
returns all but first word
Definition at line 237 of file string.qh.
References ERASEABLE, string_null, strlen(), strstrofs, and substring().
Referenced by _MapInfo_Generate(), _MapInfo_Map_ApplyGametype(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), GameCommand_adminmsg(), GameCommand_moveplayer(), get_model_parameters(), GlobalSound_sample(), Local_Notification_sprintf(), MapInfo_Get_ByName_NoFallbacks(), matchacl(), PrecacheGlobalSound(), Process_Notif_Args(), STATIC_INIT_LATE(), and W_GetCycleWeapon().
 {
     int o = strstrofs(s, " ", 0);
     if (o < 0) return string_null;
     return substring(s, o + 1, strlen(s) - (o + 1));
 }
checkColorCode()
ERASEABLE vector checkColorCode (string theText, int text_len, int pos, bool check_at_the_end)
Definition at line 528 of file string.qh.
References eX, eY, isCaretEscaped(), isValidColorCodeValue(), LABEL, strlen(), and substring().
Referenced by textLengthUpToLength(), textLengthUpToWidth(), and XonoticColorpicker_mouseDrag().
 {
     if (text_len == 0)
         text_len = strlen(theText);
     string tag_type = "^";
     int cc_len = 2;
     int tag_len = 1;
     LABEL(check_color_tag)
     int ofs = cc_len;
     if (!check_at_the_end)
         ofs--;
     for (; ofs >= 1; ofs--)
     {
         if (!(pos >= ofs && text_len >= pos + (cc_len - ofs)))
             continue;
         if(substring(theText, pos - ofs, tag_len) == tag_type)
         {
             if (!isCaretEscaped(theText, pos - ofs) && isValidColorCodeValue(theText, cc_len, pos - ofs))
                 return eX * cc_len + eY * ofs;
         }
     }
     if (cc_len == 2)
     {
         tag_type = "^x";
         cc_len = 5;
         tag_len = 2;
         goto check_color_tag;
     }
     return '0 0 0';
 }
ColorTranslateRGB()
ERASEABLE string ColorTranslateRGB (string s)
Definition at line 165 of file string.qh.
References ColorTranslateMode, and strcat().
Referenced by CSQC_Parse_Print(), and Scoreboard_Rankings_Draw().
 {
     return (ColorTranslateMode & 1) ? strdecolorize(s) : s;
 }
cons()
ERASEABLE string cons (string a, string b)
Definition at line 245 of file string.qh.
References ERASEABLE, and strcat().
Referenced by _json_parse_pair(), Gametype::Gametype ::gametype_init(), GenericCommand_addtolist(), GenericCommand_maplist(), GenericCommand_removefromlist(), Map_MarkAsRecent(), Say(), spawnfunc(), W_Apply_Weaponreplace(), waypoint_loadall(), and waypoint_saveall().
 {
     if (a == "") return b;
     if (b == "") return a;
     return strcat(a, " ", b);
 }
cons_mid()
ERASEABLE string cons_mid (string a, string mid, string b)
Definition at line 253 of file string.qh.
References ERASEABLE, and strcat().
Referenced by XonoticMutatorsDialog_toString().
 {
     if (a == "") return b;
     if (b == "") return a;
     return strcat(a, mid, b);
 }
days_up_to_date()
ERASEABLE int days_up_to_date (int Y, int M, int D)
Definition at line 67 of file string.qh.
References floor().
Referenced by strftime_s().
 {
     int years = (M <= 2) ? Y - 1 : Y;
     int leap_days = floor(years / 4) - floor(years / 100) + floor(years / 400);
     // using these 2 formulas to save 2 arrays or switches (performance isn't important here)
     int months = (M <= 2) ? (M + 9) : (M - 3); // 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
     int leftover_days = (M <= 2) ? (M + 5) : floor(0.58 * M - 1.1); // 6, 7, 0, 1, 1, 2, 2, 3, 4, 4, 5, 5
     int month_days = 30 * months + leftover_days;
     return 365 * years + month_days + D + leap_days;
 }
format_time()
ERASEABLE string format_time (float seconds)
Definition at line 129 of file string.qh.
References floor().
 {
     seconds = floor(seconds + 0.5);
     float days = floor(seconds / 864000);
     seconds -= days * 864000;
     float hours = floor(seconds / 36000);
     seconds -= hours * 36000;
     float minutes = floor(seconds / 600);
     seconds -= minutes * 600;
     if (days > 0) return sprintf(_("%d days, %02d:%02d:%02d"), days, hours, minutes, seconds);
     else return sprintf(_("%02d:%02d:%02d"), hours, minutes, seconds);
 }
fstrunzone()
ERASEABLE string fstrunzone (string s)
unzone the string, and return it as tempstring.
Safe to be called on string_null
Definition at line 218 of file string.qh.
References ERASEABLE, strcat(), and strunzone().
 {
     if (!s) return s;
     string sc = strcat(s, "");
     strunzone(s);
     return sc;
 }
ftos_decimals()
ERASEABLE string ftos_decimals (float number, int decimals)
converts a number to a string with the indicated number of decimals
Definition at line 438 of file string.qh.
References ERASEABLE.
Referenced by DrawDomItem(), HUD_Physics(), HUD_Score(), HUD_StrafeHUD(), MakeRaceString(), MUTATOR_HOOKFUNCTION(), Slider_valueToText(), waypoint_save_links(), and waypoint_saveall().
 {
     // inhibit stupid negative zero
     if (number == 0) number = 0;
     return sprintf("%.*f", decimals, number);
 }
ftos_mindecimals()
ERASEABLE string ftos_mindecimals (float number)
converts a number to a string with the minimum number of decimals
Definition at line 449 of file string.qh.
References ERASEABLE.
Referenced by XonoticCheckBox_saveCvars(), and XonoticSlider_saveCvars().
 {
     // inhibit stupid negative zero
     if (number == 0) number = 0;
     return sprintf("%.7g", number);
 }
isCaretEscaped()
ERASEABLE bool isCaretEscaped (string theText, float pos)
Definition at line 499 of file string.qh.
References ERASEABLE, and substring().
Referenced by checkColorCode(), and XonoticColorpicker_mouseDrag().
 {
     // count all the previous carets
     int carets = 0;
     while(pos - carets >= 1 && substring(theText, pos - carets - 1, 1) == "^")
         ++carets;
     // if number of previous carets is odd then this carets is escaped
     return (carets & 1);
 }
isInvisibleString()
ERASEABLE bool isInvisibleString (string s)
Definition at line 357 of file string.qh.
References cvar(), ERASEABLE, str2chr, and strlen().
Referenced by PlayerPreThink().
 {
     s = strdecolorize(s);
     bool utf8 = cvar("utf8_enable");
     for (int i = 0, n = strlen(s); i < n; ++i)
     {
         int c = str2chr(s, i);
         switch (c)
         {
             case 0:
             case 32:           // space
                 break;
             case 192:          // charmap space
                 if (!utf8) break;
                 return false;
             case 0xE000: // invisible char of the utf8 quake charmap
             case 0xE00A: // invisible char of the utf8 quake charmap
             case 0xE0A0: // invisible char of the utf8 quake charmap
             case 0xE020: // invisible char of the utf8 quake charmap
             case 0x00A0: // NO-BREAK SPACE
             //case 0x1680: // OGHAM SPACE MARK
             case 0x180E: // MONGOLIAN VOWEL SEPARATOR
             case 0x2000: // EN QUAD
             case 0x2001: // EM QUAD
             case 0x2002: // EN SPACE
             case 0x2003: // EM SPACE
             case 0x2004: // THREE-PER-EM SPACE
             case 0x2005: // FOUR-PER-EM SPACE
             case 0x2006: // SIX-PER-EM SPACE
             case 0x2007: // FIGURE SPACE
             case 0x2008: // PUNCTUATION SPACE
             case 0x2009: // THIN SPACE
             case 0x200A: // HAIR SPACE
             case 0x200B: // ZERO WIDTH SPACE
             case 0x202F: // NARROW NO-BREAK SPACE
             case 0x205F: // MEDIUM MATHEMATICAL SPACE
             case 0x3000: // IDEOGRAPHIC SPACE
             case 0xFEFF: // ZERO WIDTH NO-BREAK SPACE
                 if (utf8) break;
             default:
                 return false;
         }
     }
     return true;
 }
isValidColorCodeValue()
ERASEABLE bool isValidColorCodeValue (string theText, int cc_len, int tag_start)
Definition at line 510 of file string.qh.
References ERASEABLE, IS_DIGIT, IS_HEXDIGIT, and substring().
Referenced by checkColorCode().
 {
     if (cc_len == 2)
         return IS_DIGIT(substring(theText, tag_start + 1, 1));
     if (cc_len == 5)
         return (IS_HEXDIGIT(substring(theText, tag_start + 2, 1))
             && IS_HEXDIGIT(substring(theText, tag_start + 3, 1))
             && IS_HEXDIGIT(substring(theText, tag_start + 4, 1)));
     return false;
 }
mmsss()
ERASEABLE string mmsss (float tenths)
Definition at line 143 of file string.qh.
References ERASEABLE, floor(), ftos(), strcat(), and substring().
 {
     tenths = floor(tenths + 0.5);
     float minutes = floor(tenths / 600);
     tenths -= minutes * 600;
     string s = ftos(1000 + tenths);
     return strcat(ftos(minutes), ":", substring(s, 1, 2), ".", substring(s, 3, 1));
 }
mmssss()
ERASEABLE string mmssss (float hundredths)
Definition at line 153 of file string.qh.
References floor(), ftos(), strcat(), and substring().
 {
     hundredths = floor(hundredths + 0.5);
     float minutes = floor(hundredths / 6000);
     hundredths -= minutes * 6000;
     string s = ftos(10000 + hundredths);
     return strcat(ftos(minutes), ":", substring(s, 1, 2), ".", substring(s, 3, 2));
 }
seconds_tostring()
ERASEABLE string seconds_tostring (float sec)
Definition at line 121 of file string.qh.
References ERASEABLE, and floor().
Referenced by formatmessage(), and HUD_Timer().
 {
     float minutes = floor(sec / 60);
     sec -= minutes * 60;
     return sprintf("%d:%02d", minutes, sec);
 }
shufflewords()
ERASEABLE string shufflewords (string str)
Definition at line 295 of file string.qh.
References _shufflewords_str, _shufflewords_swapfunc(), ERASEABLE, NULL, shuffle(), string_null, and tokenizebyseparator.
Referenced by GenericCommand_maplist(), and ShuffleMaplist().
 {
     _shufflewords_str = str;
     int n = tokenizebyseparator(str, " ");
     shuffle(n, _shufflewords_swapfunc, NULL);
     str = _shufflewords_str;
     _shufflewords_str = string_null;
     return str;
 }
startsWithNocase()
ERASEABLE bool startsWithNocase (string haystack, string needle)
Definition at line 208 of file string.qh.
References strcasecmp, strlen(), and substring().
Referenced by MapInfo_FindName().
 {
     return strcasecmp(substring(haystack, 0, strlen(needle)), needle) == 0;
 }
strftime_s()
ERASEABLE string strftime_s ()
Definition at line 91 of file string.qh.
References days_up_to_date(), DAYS_UP_TO_EPOCH, ERASEABLE, floor(), ftos(), stof(), strcat(), and substring().
Referenced by IntermissionThink(), and spawnfunc().
 {
     string date = strftime(false, "%Y-%m-%d %H:%M:%S");
     int i, seconds = 0;
     i =0; int Y = stof(substring(date, i, 4)); // years
     i+=5; int M = stof(substring(date, i, 2)); // months
     i+=3; int D = stof(substring(date, i, 2)); // days
     i+=3; seconds += stof(substring(date, i, 2)) * 60 * 60; // hours
     i+=3; seconds += stof(substring(date, i, 2)) * 60; // minutes
     i+=3; seconds += stof(substring(date, i, 2)); // seconds
     // doing so we loose precision
     //seconds += (days_up_to_date(Y, M, D) - DAYS_UP_TO_EPOCH) * 24 * 60 * 60;
     //return ftos(seconds);
     int days_since_epoch = days_up_to_date(Y, M, D) - DAYS_UP_TO_EPOCH;
     // use hundreds of seconds as unit to avoid precision loss
     int hundreds_of_seconds = days_since_epoch * 24 * 6 * 6;
     hundreds_of_seconds += floor(seconds / 100);
     // tens of seconds and seconds
     string seconds_str = ftos(seconds % 100);
     if ((seconds % 100) < 10)
         seconds_str = strcat("0", seconds_str);
     return strcat(ftos(hundreds_of_seconds), seconds_str);
 }
strwords()
ERASEABLE string strwords (string s, int w)
Definition at line 331 of file string.qh.
References strstrofs, and substring().
Referenced by Map_MarkAsRecent().
 {
     int endpos = 0;
     for ( ; w && endpos >= 0; --w)
         endpos = strstrofs(s, " ", endpos + 1);
     if (endpos < 0) return s;
     return substring(s, 0, endpos);
 }
substring_range()
ERASEABLE string substring_range (string s, float b, float e)
Definition at line 261 of file string.qh.
References ERASEABLE, and substring().
Referenced by DamageText::DamageText_update(), and swapwords().
 {
     return substring(s, b, e - b);
 }
swapwords()
ERASEABLE string swapwords (string str, float i, float j)
Definition at line 267 of file string.qh.
References argv_end_index, argv_start_index, s1, s2, strcat(), substring_range(), and tokenizebyseparator.
Referenced by _shufflewords_swapfunc().
 {
     float n;
     string s1, s2, s3, s4, s5;
     float si, ei, sj, ej, s0, en;
     n = tokenizebyseparator(str, " ");  // must match g_maplist processing in ShuffleMaplist and "shuffle"
     si = argv_start_index(i);
     sj = argv_start_index(j);
     ei = argv_end_index(i);
     ej = argv_end_index(j);
     s0 = argv_start_index(0);
     en = argv_end_index(n - 1);
     s1 = substring_range(str, s0, si);
     s2 = substring_range(str, si, ei);
     s3 = substring_range(str, ei, sj);
     s4 = substring_range(str, sj, ej);
     s5 = substring_range(str, ej, en);
     return strcat(s1, s4, s3, s2, s5);
 }
u8_strsize()
ERASEABLE int u8_strsize (string s)
Definition at line 343 of file string.qh.
References ERASEABLE, and str2chr.
Referenced by InputBox_enterText().
 {
     int l = 0;
     for (int i = 0, c; (c = str2chr(s, i)) > 0; ++i, ++l)
     {
         l += (c >= 0x80);
         l += (c >= 0x800);
         l += (c >= 0x10000);
     }
     return l;
 }
unescape()
ERASEABLE string unescape (string in)
Definition at line 306 of file string.qh.
References ERASEABLE, strcat(), strlen(), strunzone(), strzone(), and substring().
 {
     in = strzone(in);  // but it doesn't seem to be necessary in my tests at least
     int len = strlen(in);
     string str = "";
     for (int i = 0; i < len; ++i)
     {
         string s = substring(in, i, 1);
         if (s == "\\")
         {
             s = substring(in, i + 1, 1);
             if (s == "n") str = strcat(str, "\n");
             else if (s == "\\") str = strcat(str, "\\");
             else str = strcat(str, substring(in, i, 2));
             ++i;
             continue;
         }
         str = strcat(str, s);
     }
     strunzone(in);
     return str;
 }
vercmp()
ERASEABLE int vercmp (string v1, string v2)
Definition at line 476 of file string.qh.
References strcasecmp, and vercmp_recursive().
Referenced by PlayerPreThink(), and UpdateNotification_URI_Get_Callback().
 {
     if (strcasecmp(v1, v2) == 0) return 0;  // early out check
     // "git" beats all
     if (v1 == "git") return 1;
     if (v2 == "git") return -1;
     return vercmp_recursive(v1, v2);
 }
vercmp_recursive()
ERASEABLE int vercmp_recursive (string v1, string v2)
Definition at line 457 of file string.qh.
References ERASEABLE, s1, s2, stof(), strcasecmp, strstrofs, and substring().
Referenced by vercmp().
 {
     int dot1 = strstrofs(v1, ".", 0);
     int dot2 = strstrofs(v2, ".", 0);
     string s1 = (dot1 == -1) ? v1 : substring(v1, 0, dot1);
     string s2 = (dot2 == -1) ? v2 : substring(v2, 0, dot2);
     float r;
     r = stof(s1) - stof(s2);
     if (r != 0) return r;
     r = strcasecmp(s1, s2);
     if (r != 0) return r;
     if (dot1 == -1) return (dot2 == -1) ? 0 : -1;
     else return (dot2 == -1) ? 1 : vercmp_recursive(substring(v1, dot1 + 1, 999), substring(v2, dot2 + 1, 999));
 }
Variable Documentation
_endsWith_suffix
noref string _endsWith_suffix
Definition at line 213 of file string.qh.
_shufflewords_str
string _shufflewords_str
Definition at line 287 of file string.qh.
Referenced by _shufflewords_swapfunc(), and shufflewords().
ColorTranslateMode
int ColorTranslateMode
Definition at line 162 of file string.qh.
Referenced by ColorTranslateRGB(), and CSQC_UpdateView().
DIGITS
const string DIGITS = "0123456789"
Definition at line 494 of file string.qh.
HEXDIGITS
const string HEXDIGITS = "0123456789ABCDEF0123456789abcdef"
Definition at line 488 of file string.qh.
HEXDIGITS_MINSET
const string HEXDIGITS_MINSET = "0123456789ABCDEFabcdef"
Definition at line 487 of file string.qh.