Xonotic: server/g_world.qh File Reference
g_world.qh File Reference
Functions
void CheckRules_World ()
float DoNextMapOverride (float reinit)
void DumpStats (float final)
string GetGametype ()
string GetNextMap ()
void GotoNextMap (float reinit)
void IntermissionThink (entity this)
void Map_Goto (float reinit)
void Map_Goto_SetStr (string nextmapname)
float Map_IsRecent (string m)
void Map_MarkAsRecent (string m)
void ReadyRestart ()
float RedirectionThink ()
void SetWinners (.float field, float value)
void ShuffleMaplist ()
float WinningCondition_Scores (float limit, float leadlimit)
Variables
string cache_lastmutatormsg
string cache_mutatormsg
float checkrules_equality
float checkrules_overtimesadded
float checkrules_suddendeathend
float checkrules_suddendeathwarning
const int WINNING_NEVER = 2
const int WINNING_NO = 0
const int WINNING_STARTSUDDENDEATHOVERTIME = 3
const int WINNING_YES = 1
Function Documentation
void CheckRules_World ()
Definition at line 1907 of file g_world.qc.
References autocvar_fraglimit, autocvar_timelimit, bprint(), checkrules_overtimesadded, checkrules_suddendeathend, checkrules_suddendeathwarning, CheckRules_World(), ClearWinners(), FOREACH_CLIENT, g_race, g_race_qualifying, game_completion_ratio, GameRules_scoring_add, InitiateOvertime(), InitiateSuddenDeath(), intermission_running, IS_PLAYER, M_ARGV, MapVote_Start(), MapVote_Think(), MUTATOR_CALLHOOK, NextLevel(), NULL, player_count, ReadyRestart(), SetDefaultAlpha(), time, VoteThink(), warmup_stage, WINNING_NEVER, WINNING_STARTSUDDENDEATHOVERTIME, WINNING_YES, WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
Referenced by CheckRules_World(), and StartFrame().
 {
     float timelimit;
     float fraglimit;
     float leadlimit;
     VoteThink();
     MapVote_Think();
     SetDefaultAlpha();
     if (intermission_running) // someone else quit the game already
     {
         if(player_count == 0) // Nobody there? Then let's go to the next map
             MapVote_Start();
             // this will actually check the player count in the next frame
             // again, but this shouldn't hurt
         return;
     }
     timelimit = autocvar_timelimit * 60;
     fraglimit = autocvar_fraglimit;
     leadlimit = autocvar_leadlimit;
     if(warmup_stage || time <= game_starttime) // NOTE: this is <= to prevent problems in the very tic where the game starts
     {
         if(timelimit > 0)
             timelimit = 0; // timelimit is not made for warmup
         if(fraglimit > 0)
             fraglimit = 0; // no fraglimit for now
         leadlimit = 0; // no leadlimit for now
     }
     if(timelimit > 0)
     {
         timelimit += game_starttime;
     }
     else if (timelimit < 0)
     {
         // endmatch
         NextLevel();
         return;
     }
     float wantovertime;
     wantovertime = 0;
     if(timelimit > game_starttime)
         game_completion_ratio = (time - game_starttime) / (timelimit - game_starttime);
     else
         game_completion_ratio = 0;
     if(checkrules_suddendeathend)
     {
         if(!checkrules_suddendeathwarning)
         {
             checkrules_suddendeathwarning = true;
             if(g_race && !g_race_qualifying)
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_RACE_FINISHLAP);
             else
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_OVERTIME_FRAG);
         }
     }
     else
     {
         if (timelimit && time >= timelimit)
         {
             if(g_race && (g_race_qualifying == 2) && timelimit > 0)
             {
                 float totalplayers;
                 float playerswithlaps;
                 float readyplayers;
                 totalplayers = playerswithlaps = readyplayers = 0;
                 FOREACH_CLIENT(IS_PLAYER(it), {
                     ++totalplayers;
                     if(GameRules_scoring_add(it, RACE_FASTEST, 0))
                         ++playerswithlaps;
                     if(it.ready)
                         ++readyplayers;
                 });
                 // at least 2 of the players have completed a lap: start the RACE
                 // otherwise, the players should end the qualifying on their own
                 if(readyplayers || playerswithlaps >= 2)
                 {
                     checkrules_suddendeathend = 0;
                     ReadyRestart(); // go to race
                     return;
                 }
                 else
                     wantovertime |= InitiateSuddenDeath();
             }
             else
                 wantovertime |= InitiateSuddenDeath();
         }
     }
     if (checkrules_suddendeathend && time >= checkrules_suddendeathend)
     {
         NextLevel();
         return;
     }
     int checkrules_status = WinningCondition_RanOutOfSpawns();
     if(checkrules_status == WINNING_YES)
         bprint("Hey! Someone ran out of spawns!\n");
     else if(MUTATOR_CALLHOOK(CheckRules_World, checkrules_status, timelimit, fraglimit))
         checkrules_status = M_ARGV(0, float);
     else
         checkrules_status = WinningCondition_Scores(fraglimit, leadlimit);
     if(checkrules_status == WINNING_STARTSUDDENDEATHOVERTIME)
     {
         checkrules_status = WINNING_NEVER;
         checkrules_overtimesadded = -1;
         wantovertime |= InitiateSuddenDeath();
     }
     if(checkrules_status == WINNING_NEVER)
         // equality cases! Nobody wins if the overtime ends in a draw.
         ClearWinners();
     if(wantovertime)
     {
         if(checkrules_status == WINNING_NEVER)
             InitiateOvertime();
         else
             checkrules_status = WINNING_YES;
     }
     if(checkrules_suddendeathend)
         if(checkrules_status != WINNING_NEVER || time >= checkrules_suddendeathend)
             checkrules_status = WINNING_YES;
     if(checkrules_status == WINNING_YES)
     {
         //print("WINNING\n");
         NextLevel();
     }
 }
float DoNextMapOverride (float reinit)
Definition at line 1302 of file g_world.qc.
References alreadychangedlevel, autocvar_g_campaign, autocvar_lastlevel, autocvar_nextmap, autocvar_quit_and_redirect, autocvar_quit_when_empty, autocvar_samelevel, autocvar_sv_vote_gametype, CampaignPostIntermission(), currentbots, cvar_set(), cvar_settemp_restore(), gametypevote, GameTypeVote_MapInfo_FixName(), localcmd, Map_Goto(), Map_Goto_SetStr(), MapInfo_CheckMap(), player_count, redirection_target, and strzone().
Referenced by GotoFirstMap(), GotoMap(), and MapVote_Think().
 {
     if(autocvar_g_campaign)
     {
         CampaignPostIntermission();
         alreadychangedlevel = true;
         return true;
     }
     if(autocvar_quit_when_empty)
     {
         if(player_count <= currentbots)
         {
             localcmd("quit\n");
             alreadychangedlevel = true;
             return true;
         }
     }
     if(autocvar_quit_and_redirect != "")
     {
         redirection_target = strzone(autocvar_quit_and_redirect);
         alreadychangedlevel = true;
         return true;
     }
     if (!reinit && autocvar_samelevel) // if samelevel is set, stay on same level
     {
         localcmd("restart\n");
         alreadychangedlevel = true;
         return true;
     }
     if(autocvar_nextmap != "")
     {
         string m;
         m = GameTypeVote_MapInfo_FixName(autocvar_nextmap);
         cvar_set("nextmap",m);
         if(!m || gametypevote)
             return false;
         if(autocvar_sv_vote_gametype)
         {
             Map_Goto_SetStr(m);
             return false;
         }
         if(MapInfo_CheckMap(m))
         {
             Map_Goto_SetStr(m);
             Map_Goto(reinit);
             alreadychangedlevel = true;
             return true;
         }
     }
     if(!reinit && autocvar_lastlevel)
     {
         cvar_settemp_restore();
         localcmd("set lastlevel 0\ntogglemenu 1\n");
         alreadychangedlevel = true;
         return true;
     }
     return false;
 }
void DumpStats (float final)
Definition at line 1468 of file g_world.qc.
References autocvar_sv_eventlog, autocvar_sv_eventlog_console, autocvar_sv_logscores_bots, autocvar_sv_logscores_console, autocvar_sv_logscores_file, autocvar_sv_logscores_filename, CS(), fclose(), FILE_APPEND, fopen(), FOREACH_CLIENT, fputs(), ftos(), GameLogEcho(), GetGametype(), GetMapname(), GetPlayerScoreString(), GetTeamScoreString(), IS_BOT_CLIENT, IS_PLAYER, IS_REAL_CLIENT, jointime, LOG_INFO, MUTATOR_CALLHOOK, NULL, playername(), rint(), strcat(), teamplay, and time.
Referenced by GameCommand_printstats(), and NextLevel().
 {
     float file;
     string s;
     float to_console;
     float to_eventlog;
     float to_file;
     float i;
     to_console = autocvar_sv_logscores_console;
     to_eventlog = autocvar_sv_eventlog;
     to_file = autocvar_sv_logscores_file;
     if(!final)
     {
         to_console = true; // always print printstats replies
         to_eventlog = false; // but never print them to the event log
     }
     if(to_eventlog)
         if(autocvar_sv_eventlog_console)
             to_console = false; // otherwise we get the output twice
     if(final)
         s = ":scores:";
     else
         s = ":status:";
     s = strcat(s, GetGametype(), "_", GetMapname(), ":", ftos(rint(time)));
     if(to_console)
         LOG_INFO(s);
     if(to_eventlog)
         GameLogEcho(s);
     file = -1;
     if(to_file)
     {
         file = fopen(autocvar_sv_logscores_filename, FILE_APPEND);
         if(file == -1)
             to_file = false;
         else
             fputs(file, strcat(s, "\n"));
     }
     s = strcat(":labels:player:", GetPlayerScoreString(NULL, 0));
     if(to_console)
         LOG_INFO(s);
     if(to_eventlog)
         GameLogEcho(s);
     if(to_file)
         fputs(file, strcat(s, "\n"));
     FOREACH_CLIENT(IS_REAL_CLIENT(it) || (IS_BOT_CLIENT(it) && autocvar_sv_logscores_bots), {
         s = strcat(":player:see-labels:", GetPlayerScoreString(it, 0), ":");
         s = strcat(s, ftos(rint(time - CS(it).jointime)), ":");
         if(IS_PLAYER(it) || MUTATOR_CALLHOOK(GetPlayerStatus, it))
             s = strcat(s, ftos(it.team), ":");
         else
             s = strcat(s, "spectator:");
         if(to_console)
             LOG_INFO(s, playername(it, false));
         if(to_eventlog)
             GameLogEcho(strcat(s, ftos(it.playerid), ":", playername(it, false)));
         if(to_file)
             fputs(file, strcat(s, playername(it, false), "\n"));
     });
     if(teamplay)
     {
         s = strcat(":labels:teamscores:", GetTeamScoreString(0, 0));
         if(to_console)
             LOG_INFO(s);
         if(to_eventlog)
             GameLogEcho(s);
         if(to_file)
             fputs(file, strcat(s, "\n"));
         for(i = 1; i < 16; ++i)
         {
             s = strcat(":teamscores:see-labels:", GetTeamScoreString(i, 0));
             s = strcat(s, ":", ftos(i));
             if(to_console)
                 LOG_INFO(s);
             if(to_eventlog)
                 GameLogEcho(s);
             if(to_file)
                 fputs(file, strcat(s, "\n"));
         }
     }
     if(to_console)
         LOG_INFO(":end");
     if(to_eventlog)
         GameLogEcho(":end");
     if(to_file)
     {
         fputs(file, ":end\n");
         fclose(file);
     }
 }
string GetGametype ()
Definition at line 1004 of file g_world.qc.
References MapInfo_LoadedGametype, and MapInfo_Type_ToString().
Referenced by DumpStats(), readlevelcvars(), spawnfunc(), WeaponStats_ready(), WinningConditionHelper(), and write_recordmarker().
 {
     return MapInfo_Type_ToString(MapInfo_LoadedGametype);
 }
string GetNextMap ()
Definition at line 1274 of file g_world.qc.
References autocvar_g_maplist_selectrandom, autocvar_g_maplist_shuffle, getmapname_stored, Map_Goto_SetFloat(), Maplist_Init(), MaplistMethod_Iterate(), MaplistMethod_Random(), MaplistMethod_Repeat(), and MaplistMethod_Shuffle().
Referenced by GotoNextMap(), and MapVote_Init().
 {
     Maplist_Init();
     float nextMap = -1;
     if(nextMap == -1)
         if(autocvar_g_maplist_shuffle > 0)
             nextMap = MaplistMethod_Shuffle(autocvar_g_maplist_shuffle + 1);
     if(nextMap == -1)
         if(autocvar_g_maplist_selectrandom)
             nextMap = MaplistMethod_Random();
     if(nextMap == -1)
         nextMap = MaplistMethod_Iterate();
     if(nextMap == -1)
         nextMap = MaplistMethod_Repeat();
     if(nextMap >= 0)
     {
         Map_Goto_SetFloat(nextMap);
         return getmapname_stored;
     }
     return "";
 }
void GotoNextMap (float reinit)
Definition at line 1363 of file g_world.qc.
References alreadychangedlevel, error, GetNextMap(), and Map_Goto().
Referenced by GotoFirstMap(), MapVote_Think(), and SelectSpawnPoint().
 {
     //string nextmap;
     //float n, nummaps;
     //string s;
     if (alreadychangedlevel)
         return;
     alreadychangedlevel = true;
     string nextMap = GetNextMap();
     if(nextMap == "")
         error("Everything is broken - cannot find a next map. Please report this to the developers.");
     Map_Goto(reinit);
 }
void IntermissionThink (entity this)
Definition at line 1387 of file g_world.qc.
References autocvar_sv_autoscreenshot, autoscreenshot, CS(), FixIntermissionClient(), GetMapname(), intermission_exittime, IS_REAL_CLIENT, mapvote_initialized, MapVote_Start(), PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_HOOK, PHYS_INPUT_BUTTON_JUMP, PHYS_INPUT_BUTTON_USE, stuffcmd, and time.
Referenced by PlayerPreThink(), and PlayerThink().
 {
     FixIntermissionClient(this);
     float server_screenshot = (autocvar_sv_autoscreenshot && CS(this).cvar_cl_autoscreenshot);
     float client_screenshot = (CS(this).cvar_cl_autoscreenshot == 2);
     if( (server_screenshot || client_screenshot)
         && ((this.autoscreenshot > 0) && (time > this.autoscreenshot)) )
     {
         this.autoscreenshot = -1;
         if(IS_REAL_CLIENT(this)) { stuffcmd(this, sprintf("\nscreenshot screenshots/autoscreenshot/%s-%s.jpg; echo \"^5A screenshot has been taken at request of the server.\"\n", GetMapname(), strftime(false, "%s"))); }
         return;
     }
     if (time < intermission_exittime)
         return;
     if(!mapvote_initialized)
         if (time < intermission_exittime + 10 && !(PHYS_INPUT_BUTTON_ATCK(this) || PHYS_INPUT_BUTTON_JUMP(this) || PHYS_INPUT_BUTTON_ATCK2(this) || PHYS_INPUT_BUTTON_HOOK(this) || PHYS_INPUT_BUTTON_USE(this)))
             return;
     MapVote_Start();
 }
void Map_Goto (float reinit)
Definition at line 1149 of file g_world.qc.
References getmapname_stored, and MapInfo_LoadMap().
Referenced by DoNextMapOverride(), GotoNextMap(), and MapVote_Finished().
 {
     MapInfo_LoadMap(getmapname_stored, reinit);
 }
void Map_Goto_SetStr (string nextmapname)
Definition at line 1133 of file g_world.qc.
References getmapname_stored, strunzone(), and strzone().
Referenced by DoNextMapOverride(), Map_Goto_SetFloat(), and MapVote_Finished().
 {
     if(getmapname_stored != "")
         strunzone(getmapname_stored);
     if(nextmapname == "")
         getmapname_stored = "";
     else
         getmapname_stored = strzone(nextmapname);
 }
float Map_IsRecent (string m)
Definition at line 1103 of file g_world.qc.
References autocvar_g_maplist_mostrecent, and strhasword.
Referenced by Map_Check(), MapVote_Suggest(), and ValidateMap().
 {
     return strhasword(autocvar_g_maplist_mostrecent, m);
 }
void Map_MarkAsRecent (string m)
Definition at line 1098 of file g_world.qc.
References autocvar_g_maplist_mostrecent, autocvar_g_maplist_mostrecent_count, cvar_set(), max(), strcat(), and strwords().
Referenced by InitGameplayMode(), and spawnfunc().
 {
     cvar_set("g_maplist_mostrecent", strwords(strcat(m, " ", autocvar_g_maplist_mostrecent), max(0, autocvar_g_maplist_mostrecent_count)));
 }
void ReadyRestart ()
Definition at line 477 of file vote.qc.
References localcmd, MUTATOR_CALLHOOK, race_completing, ReadyRestart_force(), Score_ClearAll(), and sv_ready_restart_after_countdown.
Referenced by CheckRules_World(), GameCommand_allready(), ReadyCount(), and StartFrame().
 {
     if (MUTATOR_CALLHOOK(ReadyRestart_Deny) || game_stopped || race_completing) localcmd("restart\n");
     else localcmd("\nsv_hook_gamerestart\n");
     // Reset ALL scores, but only do that at the beginning of the countdown if sv_ready_restart_after_countdown is off!
     // Otherwise scores could be manipulated during the countdown.
     if (!sv_ready_restart_after_countdown) Score_ClearAll();
     ReadyRestart_force();
 }
float RedirectionThink ()
Definition at line 2187 of file g_world.qc.
References autocvar_quit_and_redirect_timer, bprint(), cvar_set(), FOREACH_CLIENT, ftos(), IS_REAL_CLIENT, localcmd, LOG_INFO, redirection_nextthink, redirection_target, redirection_timeout, strcat(), stuffcmd, and time.
Referenced by StartFrame().
 {
     float clients_found;
     if(redirection_target == "")
         return false;
     if(!redirection_timeout)
     {
         cvar_set("sv_public", "-2");
         redirection_timeout = time + 0.6; // this will only try twice... should be able to keep more clients
         if(redirection_target == "self")
             bprint("^3SERVER NOTICE:^7 restarting the server\n");
         else
             bprint("^3SERVER NOTICE:^7 redirecting everyone to ", redirection_target, "\n");
     }
     if(time < redirection_nextthink)
         return true;
     redirection_nextthink = time + 1;
     clients_found = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         // TODO add timer
         LOG_INFO("Redirecting: sending connect command to ", it.netname);
         if(redirection_target == "self")
             stuffcmd(it, "\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " reconnect\n");
         else
             stuffcmd(it, strcat("\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " \"connect ", redirection_target, "\"\n"));
         ++clients_found;
     });
     LOG_INFO("Redirecting: ", ftos(clients_found), " clients left.");
     if(time > redirection_timeout || clients_found == 0)
         localcmd("\nwait; wait; wait; quit\n");
     return true;
 }
void SetWinners (.float field, float value)
Definition at line 1724 of file g_world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), { it.winning = (it.(field) == value); });
 }
void ShuffleMaplist ()
Definition at line 1744 of file g_world.qc.
References autocvar_g_maplist, cvar_set(), and shufflewords().
Referenced by GameTypeVote_SetGametype(), GotoFirstMap(), Maplist_Init(), and MapVote_Init().
 {
     cvar_set("g_maplist", shufflewords(autocvar_g_maplist));
 }
float WinningCondition_Scores (float limit, float leadlimit)
Definition at line 1750 of file g_world.qc.
References autocvar_leadlimit_and_fraglimit, bound(), ClearWinners(), game_completion_ratio, GetWinningCode(), leaderfrags, max(), MUTATOR_CALLHOOK, NULL, SetWinners(), team, Team_GetTeamFromIndex(), Team_IndexToTeam(), Team_SetTeamScore(), teamplay, TeamScore_GetCompareValue(), WinningConditionHelper(), WinningConditionHelper_equality, WinningConditionHelper_lowerisbetter, WinningConditionHelper_secondscore, WinningConditionHelper_topscore, WinningConditionHelper_winner, WinningConditionHelper_winnerteam, and WinningConditionHelper_zeroisworst.
Referenced by CheckRules_World(), WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
 {
     float limitreached;
     // TODO make everything use THIS winning condition (except LMS)
     WinningConditionHelper(NULL);
     if(teamplay)
     {
         for (int i = 1; i < 5; ++i)
         {
             Team_SetTeamScore(Team_GetTeamFromIndex(i),
                 TeamScore_GetCompareValue(Team_IndexToTeam(i)));
         }
     }
     ClearWinners();
     if(WinningConditionHelper_winner)
         WinningConditionHelper_winner.winning = 1;
     if(WinningConditionHelper_winnerteam >= 0)
         SetWinners(team, WinningConditionHelper_winnerteam);
     if(WinningConditionHelper_lowerisbetter)
     {
         WinningConditionHelper_topscore = -WinningConditionHelper_topscore;
         WinningConditionHelper_secondscore = -WinningConditionHelper_secondscore;
         limit = -limit;
     }
     if(WinningConditionHelper_zeroisworst)
         leadlimit = 0; // not supported in this mode
     if(MUTATOR_CALLHOOK(Scores_CountFragsRemaining))
     // these modes always score in increments of 1, thus this makes sense
     {
         if(leaderfrags != WinningConditionHelper_topscore)
         {
             leaderfrags = WinningConditionHelper_topscore;
             if (limit)
             {
                 if (leaderfrags == limit - 1)
                     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_1);
                 else if (leaderfrags == limit - 2)
                     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_2);
                 else if (leaderfrags == limit - 3)
                     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_3);
             }
         }
     }
     limitreached = false;
     if (limit && WinningConditionHelper_topscore >= limit)
         limitreached = true;
     if(leadlimit)
     {
         float leadlimitreached;
         leadlimitreached = (WinningConditionHelper_topscore - WinningConditionHelper_secondscore >= leadlimit);
         if(autocvar_leadlimit_and_fraglimit)
             limitreached = (limitreached && leadlimitreached);
         else
             limitreached = (limitreached || leadlimitreached);
     }
     if(limit)
         game_completion_ratio = max(game_completion_ratio, bound(0, WinningConditionHelper_topscore / limit, 1));
     return GetWinningCode(
         WinningConditionHelper_topscore && limitreached,
         WinningConditionHelper_equality
     );
 }
Variable Documentation
string cache_lastmutatormsg
Definition at line 9 of file g_world.qh.
Referenced by getwelcomemessage(), and InitGameplayMode().
string cache_mutatormsg
Definition at line 8 of file g_world.qh.
Referenced by getwelcomemessage(), and InitGameplayMode().
float checkrules_equality
Definition at line 3 of file g_world.qh.
Referenced by CampaignPreIntermission(), and WinningCondition_RanOutOfSpawns().
float checkrules_overtimesadded
Definition at line 6 of file g_world.qh.
Referenced by CheckRules_World(), InitiateOvertime(), InitiateSuddenDeath(), and ReadyRestart_force().
float checkrules_suddendeathend
Definition at line 5 of file g_world.qh.
Referenced by CheckRules_World(), InitiateSuddenDeath(), and ReadyRestart_force().
float checkrules_suddendeathwarning
Definition at line 4 of file g_world.qh.
Referenced by CheckRules_World(), and ReadyRestart_force().
const int WINNING_NEVER = 2
Definition at line 13 of file g_world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_LMS(), and WinningCondition_Race().
const int WINNING_NO = 0
Definition at line 11 of file g_world.qh.
Referenced by GetWinningCode(), WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), and WinningCondition_RanOutOfSpawns().
const int WINNING_STARTSUDDENDEATHOVERTIME = 3
Definition at line 14 of file g_world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
const int WINNING_YES = 1
Definition at line 12 of file g_world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), WinningCondition_QualifyingThenRace(), WinningCondition_Race(), and WinningCondition_RanOutOfSpawns().