Xonotic: common/mapobjects/func/conveyor.qc File Reference
conveyor.qc File Reference
#include "conveyor.qh"
Functions
void conveyor_think (entity this)
Function Documentation
void conveyor_think (entity this)
Definition at line 4 of file conveyor.qc.
References absmax, absmin, active, ACTIVE_ACTIVE, ACTIVE_NOT, boxesoverlap(), drawmask, entity(), EXACTTRIGGER_INIT, g_conveyed, g_drawables, IL_EACH, IL_PUSH(), isPushable(), MASK_NORMAL, maxs, mins, model, move_time, movedir, MOVETYPE_NONE, NET_HANDLE, nextthink, origin, ReadString, sendflags, set_movetype(), setorigin(), setthink, SF_TRIGGER_INIT, SF_TRIGGER_UPDATE, solid, SOLID_BSP, SOLID_TRIGGER, spawnfunc(), speed, strzone(), target, targetname, time, to, use, vector(), vlen(), warpzone_isboxy, WarpZoneLib_BoxTouchesBrush(), WriteByte(), and WriteString().
 {
 #ifdef CSQC
     // TODO: check if this is what is causing the glitchiness when switching between them
     float dt = time - this.move_time;
     this.move_time = time;
     if(dt <= 0) { return; }
 #endif
     // set myself as current conveyor where possible
     IL_EACH(g_conveyed, it.conveyor == this,
     {
         it.conveyor = NULL;
         IL_REMOVE(g_conveyed, it);
     });
     if(this.active == ACTIVE_ACTIVE)
     {
         FOREACH_ENTITY_RADIUS((this.absmin + this.absmax) * 0.5, vlen(this.absmax - this.absmin) * 0.5 + 1, it.conveyor.active == ACTIVE_NOT && isPushable(it),
         {
             vector emin = it.absmin;
             vector emax = it.absmax;
             if(this.solid == SOLID_BSP)
             {
                 emin -= '1 1 1';
                 emax += '1 1 1';
             }
             if(boxesoverlap(emin, emax, this.absmin, this.absmax)) // quick
                 if(WarpZoneLib_BoxTouchesBrush(emin, emax, this, it)) // accurate
                 {
                     if(!it.conveyor)
                         IL_PUSH(g_conveyed, it);
                     it.conveyor = this;
                 }
         });
         IL_EACH(g_conveyed, it.conveyor == this,
         {
             if(IS_CLIENT(it)) // doing it via velocity has quite some advantages
                 continue; // done in SV_PlayerPhysics   continue;
             setorigin(it, it.origin + this.movedir * PHYS_INPUT_FRAMETIME);
             move_out_of_solid(it);
 #ifdef SVQC
             UpdateCSQCProjectile(it);
 #endif
             /*
             // stupid conveyor code
             tracebox(it.origin, it.mins, it.maxs, it.origin + this.movedir * sys_frametime, MOVE_NORMAL, it);
             if(trace_fraction > 0)
                 setorigin(it, trace_endpos);
             */
         });
     }
 #ifdef SVQC
     this.nextthink = time;
 #endif
 }