Xonotic: Slider Class Reference
Slider Class Reference
Public Member Functions
ATTRIB (Label, text, string)
ATTRIB (Label, currentText, string)
ATTRIB (Slider, src, string)
ATTRIB (Item, parent, entity)
ATTRIB (Label, textEntity, entity)
ATTRIB (Slider, sliderAnim, entity)
ATTRIB (Item, tooltip, string)
virtual void configureLabel ()
virtual void configureSliderValues ()
virtual void configureSliderVisuals ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void setSliderValue ()
virtual void setText ()
virtual void setValue ()
virtual void setValue_allowAnim ()
virtual void setValue_noAnim ()
virtual void showNotify ()
virtual void toString ()
virtual void valueToText ()
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = 0.7
float animated = 1
vector color = '1 1 1'
vector color2 = '1 1 1'
vector colorC = '1 1 1'
vector colorD = '1 1 1'
vector colorF = '1 1 1'
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
float controlWidth = 0
float disabled = 0
float disabledAlpha = 0.3
float focusable = 1
float focused = 0
float fontSize = 8
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
float marginLeft = 0
float marginRight = 0
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
vector size = '0 0 0'
float sliderValue = 0
float textSpace = 0
vector tolerance = '0 0 0'
float value = 0
float valueDigits = 0
float valueDisplayMultiplier = 1.0
float valueKeyStep = 0
float valueMax = 0
float valueMin = 0
float valuePageStep = 0
float valueStep = 0
Detailed Description
Definition at line 6 of file slider.qh.
Member Function Documentation
Label::ATTRIB (Label , text , string) inherited
Label::ATTRIB (Label , currentText , string) inherited
Slider::ATTRIB (Slider , src , string)
Item::ATTRIB (Item , parent , entity) inherited
Label::ATTRIB (Label , textEntity , entity) inherited
Slider::ATTRIB (Slider , sliderAnim , entity)
Item::ATTRIB (Item , tooltip , string) inherited
virtual void Label::configureLabel () virtual inherited
virtual void Slider::configureSliderValues () virtual
virtual void Slider::configureSliderVisuals () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Slider::draw () virtual
Reimplemented from Label.
Reimplemented in XonoticResolutionSlider, and XonoticPicmipSlider.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void Item::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void Slider::keyDown () virtual
Reimplemented from Item.
virtual void Slider::keyUp () virtual
Reimplemented from Item.
virtual void Slider::mouseDrag () virtual
Reimplemented from Item.
void Item::mouseMove () virtual inherited
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void Slider::mousePress () virtual
Reimplemented from Item.
virtual void Slider::mouseRelease () virtual
Reimplemented from Item.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Slider::resizeNotify () virtual
Reimplemented from Label.
virtual void Slider::setSliderValue () virtual
virtual void Label::setText () virtual inherited
Reimplemented in InputBox, and XonoticInputBox.
virtual void Slider::setValue () virtual
Reimplemented in XonoticSlider, and XonoticTextSlider.
virtual void Slider::setValue_allowAnim () virtual
virtual void Slider::setValue_noAnim () virtual
Reimplemented in XonoticSlider, and XonoticTextSlider.
virtual void Slider::showNotify () virtual
Reimplemented from Item.
virtual void Slider::toString () virtual
Reimplemented from Label.
virtual void Slider::valueToText () virtual
Reimplemented in TextSlider, and XonoticDecibelsSlider.
Member Data Documentation
float Label::align = 0.5 inherited
Definition at line 15 of file label.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float Slider::allowFocusSound = 1
Definition at line 25 of file slider.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float Label::alpha = 0.7 inherited
Definition at line 24 of file label.qh.
float Slider::animated = 1
Definition at line 27 of file slider.qh.
vector Slider::color = '1 1 1'
Definition at line 44 of file slider.qh.
vector Slider::color2 = '1 1 1'
Definition at line 45 of file slider.qh.
vector Slider::colorC = '1 1 1'
Definition at line 47 of file slider.qh.
vector Slider::colorD = '1 1 1'
Definition at line 46 of file slider.qh.
vector Slider::colorF = '1 1 1'
Definition at line 48 of file slider.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
float Slider::controlWidth = 0
Definition at line 38 of file slider.qh.
float Slider::disabled = 0
Definition at line 43 of file slider.qh.
float Slider::disabledAlpha = 0.3
Definition at line 49 of file slider.qh.
float Slider::focusable = 1
Definition at line 24 of file slider.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
float Label::fontSize = 8 inherited
Definition at line 14 of file label.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
float Label::marginLeft = 0 inherited
Definition at line 20 of file label.qh.
float Label::marginRight = 0 inherited
Definition at line 21 of file label.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Slider::pressed = 0
Definition at line 39 of file slider.qh.
float Slider::pressOffset = 0
Definition at line 40 of file slider.qh.
float Slider::previousValue = 0
Definition at line 41 of file slider.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
float Slider::sliderValue = 0
Definition at line 28 of file slider.qh.
float Slider::textSpace = 0
Definition at line 37 of file slider.qh.
vector Slider::tolerance = '0 0 0'
Definition at line 42 of file slider.qh.
float Slider::value = 0
Definition at line 26 of file slider.qh.
float Slider::valueDigits = 0
Definition at line 33 of file slider.qh.
float Slider::valueDisplayMultiplier = 1.0
Definition at line 36 of file slider.qh.
float Slider::valueKeyStep = 0
Definition at line 34 of file slider.qh.
float Slider::valueMax = 0
Definition at line 31 of file slider.qh.
float Slider::valueMin = 0
Definition at line 30 of file slider.qh.
float Slider::valuePageStep = 0
Definition at line 35 of file slider.qh.
float Slider::valueStep = 0
Definition at line 32 of file slider.qh.
The documentation for this class was generated from the following file:
menu/item/slider.qh