Xonotic: common/minigames/minigame/ttt.qc File Reference
ttt.qc File Reference
#include "ttt.qh"
Functions
REGISTER_MINIGAME (ttt,"Tic Tac Toe")
entity ttt_find_piece (entity minig, string tile)
void ttt_move (entity minigame, entity player, string pos)
void ttt_next_match (entity minigame, entity player)
bool ttt_valid_tile (string tile)
bool ttt_winning_piece (entity piece)
Variables
int ttt_ai
const int TTT_LET_CNT = 3
int ttt_nexteam
int ttt_npieces
const int TTT_NUM_CNT = 3
const int TTT_SF_PLAYERSCORE = MINIG_SF_CUSTOM
const int TTT_SF_SINGLEPLAYER = MINIG_SF_CUSTOM<<1
const int TTT_TILE_SIZE = 3
const int TTT_TURN_DRAW = 0x0400
const int TTT_TURN_NEXT = 0x0800
const int TTT_TURN_PLACE = 0x0100
const int TTT_TURN_TEAM = 0x000f
const int TTT_TURN_TEAM1 = 0x0001
const int TTT_TURN_TEAM2 = 0x0002
const int TTT_TURN_TYPE = 0x0f00
const int TTT_TURN_WIN = 0x0200
Function Documentation
REGISTER_MINIGAME (ttt , "Tic Tac Toe")
entity ttt_find_piece (entity minig, string tile)
Definition at line 27 of file ttt.qc.
References entity(), findentity(), NULL, and owner.
Referenced by ttt_move(), and ttt_winning_piece().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile )
             return e;
     return NULL;
 }
void ttt_move (entity minigame, entity player, string pos)
Definition at line 78 of file ttt.qc.
References entity(), MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_next_team(), minigame_server_sendflags(), msle_spawn(), strzone(), ttt_find_piece(), TTT_LET_CNT, TTT_NUM_CNT, TTT_SF_PLAYERSCORE, TTT_TURN_DRAW, TTT_TURN_PLACE, TTT_TURN_TEAM, TTT_TURN_WIN, ttt_valid_tile(), and ttt_winning_piece().
 {
     if ( minigame.minigame_flags & TTT_TURN_PLACE )
     if ( pos && player.team == (minigame.minigame_flags & TTT_TURN_TEAM) )
     {
         if ( ttt_valid_tile(pos) )
         if ( !ttt_find_piece(minigame,pos) )
         {
             entity piece = msle_spawn(minigame,"minigame_board_piece");
             piece.team = player.team;
             piece.netname = strzone(pos);
             minigame_server_sendflags(piece,MINIG_SF_ALL);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
             minigame.ttt_npieces++;
             minigame.ttt_nexteam = minigame_next_team(player.team,2);
             if ( ttt_winning_piece(piece) )
             {
                 player.minigame_flags++;
                 minigame_server_sendflags(player, TTT_SF_PLAYERSCORE);
                 minigame.minigame_flags = TTT_TURN_WIN | player.team;
             }
             else if ( minigame.ttt_npieces >= (TTT_LET_CNT * TTT_NUM_CNT) )
                 minigame.minigame_flags = TTT_TURN_DRAW;
             else
                 minigame.minigame_flags = TTT_TURN_PLACE | minigame.ttt_nexteam;
         }
     }
 }
void ttt_next_match (entity minigame, entity player)
Definition at line 108 of file ttt.qc.
References entity(), findentity(), MINIG_SF_UPDATE, minigame_server_sendflags(), NULL, owner, TTT_TURN_DRAW, TTT_TURN_NEXT, TTT_TURN_PLACE, and TTT_TURN_WIN.
 {
 #ifdef SVQC
     // on multiplayer matches, wait for both players to agree
     if ( minigame.minigame_flags & (TTT_TURN_WIN|TTT_TURN_DRAW) )
     {
         minigame.minigame_flags = TTT_TURN_NEXT | player.team;
         minigame.SendFlags |= MINIG_SF_UPDATE;
     }
     else if ( (minigame.minigame_flags & TTT_TURN_NEXT) &&
             !( minigame.minigame_flags & player.team ) )
 #endif
     {
         minigame.minigame_flags = TTT_TURN_PLACE | minigame.ttt_nexteam;
         minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         minigame.ttt_npieces = 0;
         entity e = NULL;
         while ( ( e = findentity(e,owner,minigame) ) )
             if ( e.classname == "minigame_board_piece" )
                 delete(e);
     }
 }
bool ttt_valid_tile (string tile)
Definition at line 68 of file ttt.qc.
References minigame_tile_letter(), minigame_tile_number(), TTT_LET_CNT, and TTT_NUM_CNT.
Referenced by ttt_move().
 {
     if ( !tile )
         return 0;
     int number = minigame_tile_number(tile);
     int letter = minigame_tile_letter(tile);
     return 0 <= number && number < TTT_NUM_CNT && 0 <= letter && letter < TTT_LET_CNT;
 }
bool ttt_winning_piece (entity piece)
Definition at line 37 of file ttt.qc.
References minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), team, and ttt_find_piece().
Referenced by ttt_move().
 {
     int number = minigame_tile_number(piece.netname);
     int letter = minigame_tile_letter(piece.netname);
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(0,number)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(1,number)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(2,number)).team == piece.team )
         return true;
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(letter,0)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(letter,1)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(letter,2)).team == piece.team )
         return true;
     if ( number == letter )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(0,0)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(1,1)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(2,2)).team == piece.team )
         return true;
     if ( number == 2-letter )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(0,2)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(1,1)).team == piece.team )
     if ( ttt_find_piece(piece.owner,minigame_tile_buildname(2,0)).team == piece.team )
         return true;
     return false;
 }
Variable Documentation
int ttt_ai
Definition at line 24 of file ttt.qc.
const int TTT_LET_CNT = 3
Definition at line 18 of file ttt.qc.
Referenced by ttt_move(), and ttt_valid_tile().
int ttt_nexteam
Definition at line 23 of file ttt.qc.
int ttt_npieces
Definition at line 22 of file ttt.qc.
const int TTT_NUM_CNT = 3
Definition at line 19 of file ttt.qc.
Referenced by ttt_move(), and ttt_valid_tile().
const int TTT_SF_PLAYERSCORE = MINIG_SF_CUSTOM
Definition at line 15 of file ttt.qc.
Referenced by ttt_move().
const int TTT_SF_SINGLEPLAYER = MINIG_SF_CUSTOM<<1
Definition at line 16 of file ttt.qc.
const int TTT_TILE_SIZE = 3
Definition at line 20 of file ttt.qc.
const int TTT_TURN_DRAW = 0x0400
Definition at line 6 of file ttt.qc.
Referenced by ttt_move(), and ttt_next_match().
const int TTT_TURN_NEXT = 0x0800
Definition at line 7 of file ttt.qc.
Referenced by ttt_next_match().
const int TTT_TURN_PLACE = 0x0100
Definition at line 4 of file ttt.qc.
Referenced by ttt_move(), and ttt_next_match().
const int TTT_TURN_TEAM = 0x000f
Definition at line 12 of file ttt.qc.
Referenced by ttt_move().
const int TTT_TURN_TEAM1 = 0x0001
Definition at line 10 of file ttt.qc.
const int TTT_TURN_TEAM2 = 0x0002
Definition at line 11 of file ttt.qc.
const int TTT_TURN_TYPE = 0x0f00
Definition at line 8 of file ttt.qc.
const int TTT_TURN_WIN = 0x0200
Definition at line 5 of file ttt.qc.
Referenced by ttt_move(), and ttt_next_match().