Xonotic: lib/file.qh File Reference
file.qh File Reference
Functions
ERASEABLE bool fexists (string f)
Function Documentation
fexists()
ERASEABLE bool fexists (string f)
Definition at line 4 of file file.qh.
References fclose(), FILE_READ, and fopen().
Referenced by bd_save_level(), CheckPlayerModel(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), GenericCommand_maplist(), GenericCommand_rpn(), InstantAction_LoadMap(), MapHasRightSize(), Model::Model ::model_precache(), MUTATOR_HOOKFUNCTION(), precache_playermodel(), PreviewExists(), spawnfunc(), updateCheck(), and updateCompression().
 {
     int fh = fopen(f, FILE_READ);
     if (fh < 0) return false;
     fclose(fh);
     return true;
 }