Xonotic: common/gamemodes/sv_rules.qc File Reference
sv_rules.qc File Reference
#include "sv_rules.qh"
#include <server/teamplay.qh>
Functions
float _GameRules_scoring_add (entity client, entity sp, float value)
float _GameRules_scoring_add_team (entity client, entity sp, int st, float value)
void _GameRules_scoring_begin (int teams, float spprio, float stprio)
void _GameRules_scoring_end ()
void _GameRules_scoring_field (entity i, string label, int scoreflags)
void _GameRules_scoring_field_team (float i, string label, int scoreflags)
void GameRules_limit_fallbacks ()
Set any unspecified rules to their defaults.
void GameRules_limit_lead (int limit)
void GameRules_limit_score (int limit)
void GameRules_limit_time (int limit)
void GameRules_limit_time_qualifying (int limit)
void GameRules_score_enabled (bool value)
Disabling score disables the "score" column on the scoreboard.
bool GameRules_scoring_is_vip (entity player)
void GameRules_scoring_vip (entity player, bool value)
Mark a player as being 'important' (flag carrier, ball carrier, etc)
void GameRules_spawning_teams (bool value)
Used to disable team spawns in team modes.
void GameRules_teams (bool value)
Variables
bool _GameRules_score_enabled = true
bool GameRules_limit_lead_initialized
bool GameRules_limit_score_initialized
bool GameRules_limit_time_initialized
bool GameRules_limit_time_qualifying_initialized
bool m_GameRules_scoring_vip
Function Documentation
float _GameRules_scoring_add (entity client, entity sp, float value)
Definition at line 105 of file sv_rules.qc.
References PlayerScore_Add().
 {
     return PlayerScore_Add(client, sp, value);
 }
float _GameRules_scoring_add_team (entity client, entity sp, int st, float value)
Definition at line 109 of file sv_rules.qc.
References PlayerTeamScore_Add().
 {
     return PlayerTeamScore_Add(client, sp, st, value);
 }
void _GameRules_scoring_begin (int teams, float spprio, float stprio)
Definition at line 78 of file sv_rules.qc.
References _GameRules_score_enabled, and ScoreRules_basics().
 {
     ScoreRules_basics(teams, spprio, stprio, _GameRules_score_enabled);
 }
void _GameRules_scoring_end ()
Definition at line 90 of file sv_rules.qc.
References ScoreRules_basics_end().
 {
     ScoreRules_basics_end();
 }
void _GameRules_scoring_field (entity i, string label, int scoreflags)
Definition at line 82 of file sv_rules.qc.
References ScoreInfo_SetLabel_PlayerScore().
 {
     ScoreInfo_SetLabel_PlayerScore(i, label, scoreflags);
 }
void _GameRules_scoring_field_team (float i, string label, int scoreflags)
Definition at line 86 of file sv_rules.qc.
References ScoreInfo_SetLabel_TeamScore().
 {
     ScoreInfo_SetLabel_TeamScore(i, label, scoreflags);
 }
void GameRules_limit_fallbacks ()
Set any unspecified rules to their defaults.
Definition at line 71 of file sv_rules.qc.
References autocvar_fraglimit_override, autocvar_leadlimit_override, autocvar_timelimit_override, GameRules_limit_lead(), GameRules_limit_score(), and GameRules_limit_time().
Referenced by spawnfunc().
 {
     GameRules_limit_score(autocvar_fraglimit_override);
     GameRules_limit_lead(autocvar_leadlimit_override);
     GameRules_limit_time(autocvar_timelimit_override);
 }
void GameRules_limit_lead (int limit)
Definition at line 42 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_lead_initialized.
Referenced by GameRules_limit_fallbacks(), rc_SetLimits(), and REGISTER_MUTATOR().
 {
     if (GameRules_limit_lead_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("leadlimit", ftos(limit));
     GameRules_limit_lead_initialized = true;
 }
void GameRules_limit_score (int limit)
Definition at line 32 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_score_initialized.
Referenced by GameRules_limit_fallbacks(), rc_SetLimits(), and REGISTER_MUTATOR().
 {
     if (GameRules_limit_score_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("fraglimit", ftos(limit));
     GameRules_limit_score_initialized = true;
 }
void GameRules_limit_time (int limit)
Definition at line 52 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_time_initialized.
Referenced by GameRules_limit_fallbacks(), and rc_SetLimits().
 {
     if (GameRules_limit_time_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("timelimit", ftos(limit));
     GameRules_limit_time_initialized = true;
 }
void GameRules_limit_time_qualifying (int limit)
Definition at line 62 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_time_qualifying_initialized.
Referenced by rc_SetLimits().
 {
     if (GameRules_limit_time_qualifying_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("g_race_qualifying_timelimit", ftos(limit));
     GameRules_limit_time_qualifying_initialized = true;
 }
void GameRules_score_enabled (bool value)
Disabling score disables the "score" column on the scoreboard.
Definition at line 26 of file sv_rules.qc.
References _GameRules_score_enabled.
Referenced by cts_ScoreRules(), invasion_ScoreRules(), race_ScoreRules(), and REGISTER_MUTATOR().
 {
     _GameRules_score_enabled = value;
 }
bool GameRules_scoring_is_vip (entity player)
Definition at line 100 of file sv_rules.qc.
 {
     return player.m_GameRules_scoring_vip;
 }
void GameRules_scoring_vip (entity player, bool value)
Mark a player as being 'important' (flag carrier, ball carrier, etc)
Parameters
player the entity to mark
value VIP status
Definition at line 96 of file sv_rules.qc.
Referenced by ctf_Handle_Pickup(), ctf_Handle_Retrieve(), ctf_Handle_Throw(), ctf_RespawnFlag(), DropBall(), GiveBall(), ka_PlayerReset(), and ka_TouchEvent().
 {
     player.m_GameRules_scoring_vip = value;
 }
void GameRules_spawning_teams (bool value)
Used to disable team spawns in team modes.
Definition at line 20 of file sv_rules.qc.
References have_team_spawns.
Referenced by GameRules_teams(), and REGISTER_MUTATOR().
 {
     have_team_spawns = value ? -1 : 0;
 }
void GameRules_teams (bool value)
Definition at line 5 of file sv_rules.qc.
References cvar_set(), GameRules_spawning_teams(), SERVERFLAG_TEAMPLAY, serverflags, and teamplay.
Referenced by InitGameplayMode(), rc_SetLimits(), and REGISTER_MUTATOR().
 {
     if (value) {
         serverflags |= SERVERFLAG_TEAMPLAY;
         teamplay = 1;
         cvar_set("teamplay", "2");  // DP needs this for sending proper getstatus replies.
         GameRules_spawning_teams(true);
     } else {
         serverflags &= ~SERVERFLAG_TEAMPLAY;
         teamplay = 0;
         cvar_set("teamplay", "0");  // DP needs this for sending proper getstatus replies.
         GameRules_spawning_teams(false);
     }
 }
Variable Documentation
bool _GameRules_score_enabled = true
Definition at line 25 of file sv_rules.qc.
Referenced by _GameRules_scoring_begin(), and GameRules_score_enabled().
bool GameRules_limit_lead_initialized
Definition at line 41 of file sv_rules.qc.
Referenced by GameRules_limit_lead().
bool GameRules_limit_score_initialized
Definition at line 31 of file sv_rules.qc.
Referenced by GameRules_limit_score().
bool GameRules_limit_time_initialized
Definition at line 51 of file sv_rules.qc.
Referenced by GameRules_limit_time().
bool GameRules_limit_time_qualifying_initialized
Definition at line 61 of file sv_rules.qc.
Referenced by GameRules_limit_time_qualifying().
bool m_GameRules_scoring_vip
Definition at line 95 of file sv_rules.qc.