Xonotic: common/mapobjects/triggers.qc File Reference
triggers.qc File Reference
#include "triggers.qh"
Functions
void DelayThink (entity this)
bool isPushable (entity e)
void SUB_DontUseTargets (entity this, entity actor, entity trigger)
void SUB_UseTargets (entity this, entity actor, entity trigger)
void SUB_UseTargets_Ex (entity this, entity actor, entity trigger, bool preventReuse, int skiptargets)
void SUB_UseTargets_PreventReuse (entity this, entity actor, entity trigger)
void SUB_UseTargets_SkipTargets (entity this, entity actor, entity trigger, int skiptargets)
Function Documentation
DelayThink()
void DelayThink (entity this)
Definition at line 39 of file triggers.qc.
References active, ACTIVE_ACTIVE, ACTIVE_NOT, ACTIVE_TOGGLE, angles, BIT, BITSET_ASSIGN, bound(), EF_NODEPTHTEST, effects, enemy, entity(), EXACTTRIGGER_INIT, killtarget, maxs, mins, model, modelindex, movedir, NULL, origin, ReadString, scale, sendflags, setorigin(), setSendEntity, SF_TRIGGER_UPDATE, spawnflags, START_ENABLED, strfree, string_null, strzone(), SUB_UseTargets(), target, target2, target3, target4, targetname, to, warpzone_isboxy, WriteByte(), WriteShort(), and WriteString().
Referenced by SUB_UseTargets_Ex().
 {
     SUB_UseTargets (this, this.enemy, NULL);
     delete(this);
 }
isPushable()
bool isPushable (entity e)
Definition at line 3 of file triggers.qc.
References IS_VEHICLE, and Item_IsLoot().
Referenced by conveyor_think(), jumppad_push(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), and trigger_impulse_touch_radial().
 {
     if(e.pushable)
         return true;
 #ifdef SVQC
     if(IS_VEHICLE(e))
         return false;
     if(e.iscreature)
         return true;
     if (Item_IsLoot(e))
     {
         return true;
     }
     switch(e.classname)
     {
         case "body":
             return true;
         case "bullet": // antilagged bullets can't hit this either
             return false;
     }
     if (e.projectiledeathtype)
         return true;
 #endif
 #ifdef CSQC
     if(e.flags & FL_PROJECTILE)
         return true;
     if(e.isplayermodel)
         return true;
 #endif
     return false;
 }
SUB_DontUseTargets()
void SUB_DontUseTargets (entity this, entity actor, entity trigger)
Definition at line 35 of file triggers.qc.
References entity(), and SUB_UseTargets().
 { }
SUB_UseTargets()
void SUB_UseTargets (entity this, entity actor, entity trigger)
Definition at line 366 of file triggers.qc.
References SUB_UseTargets_Ex().
Referenced by assault_objective_decrease_use(), assault_roundstart_use(), CheatCommand(), checkpoint_passed(), DelayThink(), dompoint_captured(), door_go_up(), fragsfilter_use(), Item_Touch(), jumppad_push(), Monster_Damage(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_Reset(), PutPlayerInServer(), SUB_DontUseTargets(), target_init_use(), Teleport_Touch(), and train_wait().
 { SUB_UseTargets_Ex(this, actor, trigger, false, 0); }
SUB_UseTargets_Ex()
void SUB_UseTargets_Ex (entity this, entity actor, entity trigger, bool preventReuse, int skiptargets)
Definition at line 270 of file triggers.qc.
References antiwall_flag, BIT, centerprint(), delay, DelayThink(), entity(), find(), IS_PLAYER, IS_REAL_CLIENT, killtarget, message, new_pure, noise, NULL, RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), setthink, SND, target, target2, target3, target4, target_random, targetname, and time.
Referenced by SUB_UseTargets(), SUB_UseTargets_PreventReuse(), and SUB_UseTargets_SkipTargets().
 {
 //
 // check for a delay
 //
     if (this.delay)
     {
         // create a temp object to fire at a later time
         entity t = new_pure(DelayedUse);
         t.nextthink = time + this.delay;
         setthink(t, DelayThink);
         t.enemy = actor;
         t.message = this.message;
         t.killtarget = this.killtarget;
         if(!(skiptargets & BIT(1))) t.target = this.target;
         if(!(skiptargets & BIT(2))) t.target2 = this.target2;
         if(!(skiptargets & BIT(3))) t.target3 = this.target3;
         if(!(skiptargets & BIT(4))) t.target4 = this.target4;
         t.antiwall_flag = this.antiwall_flag;
         return;
     }
     string s;
 //
 // print the message
 //
 #ifdef SVQC
     if(this)
     if(IS_PLAYER(actor) && this.message != "")
     if(IS_REAL_CLIENT(actor))
     {
         centerprint(actor, this.message);
         if (this.noise == "")
             play2(actor, SND(TALK));
     }
 //
 // kill the killtagets
 //
     s = this.killtarget;
     if (s != "")
     {
         for(entity t = NULL; (t = find(t, targetname, s)); )
             delete(t);
     }
 #endif
 //
 // fire targets
 //
     if(this.target_random)
         RandomSelection_Init();
     for(int i = 0; i < 4; ++i)
     {
         if(skiptargets & BIT(i + 1))
             continue;
         switch(i)
         {
             default:
             case 0: s = this.target; break;
             case 1: s = this.target2; break;
             case 2: s = this.target3; break;
             case 3: s = this.target4; break;
         }
         if (s != "")
         {
             for(entity t = NULL; (t = find(t, targetname, s)); )
             {
                 if(t != this && t.use && (t.sub_target_used != time || !preventReuse))
                 {
                     if(this.target_random)
                     {
                         RandomSelection_AddEnt(t, 1, 0);
                     }
                     else
                     {
                         t.use(t, actor, this);
                         if(preventReuse)
                             t.sub_target_used = time;
                     }
                 }
             }
         }
     }
     if(this.target_random && RandomSelection_chosen_ent)
     {
         RandomSelection_chosen_ent.use(RandomSelection_chosen_ent, actor, this);
         if(preventReuse)
             RandomSelection_chosen_ent.sub_target_used = time;
     }
 }
SUB_UseTargets_PreventReuse()
void SUB_UseTargets_PreventReuse (entity this, entity actor, entity trigger)
Definition at line 367 of file triggers.qc.
References SUB_UseTargets_Ex().
 { SUB_UseTargets_Ex(this, actor, trigger, true, 0); }
SUB_UseTargets_SkipTargets()
void SUB_UseTargets_SkipTargets (entity this, entity actor, entity trigger, int skiptargets)
Definition at line 368 of file triggers.qc.
References SUB_UseTargets_Ex().
Referenced by WarpZone_Touch().
 { SUB_UseTargets_Ex(this, actor, trigger, false, skiptargets); }