Xonotic: common/effects/all.inc File Reference
all.inc File Reference
#include "../teams.qh"
Functions
entity EFFECT_CAP (int teamid)
entity EFFECT_FLAG_TOUCH (int teamid)
entity EFFECT_PASS (int teamid)
entity EFFECT_ROCKETMINSTA_LASER (int teamid)
entity EFFECT_SPAWN (int teamid)
entity EFFECT_SPAWNPOINT (int teamid)
entity EFFECT_VAPORIZER (int teamid)
entity EFFECT_VAPORIZER_HIT (int teamid)
Function Documentation
entity EFFECT_CAP (int teamid)
Definition at line 220 of file all.inc.
References EF_FLAME, EF_STARDUST, EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and TE_EXPLOSION.
Referenced by ctf_FlagSetup(), and ons_ControlPoint_Icon_BuildThink().
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_CAP_RED;
         case NUM_TEAM_2:    return EFFECT_CAP_BLUE;
         case NUM_TEAM_3:    return EFFECT_CAP_YELLOW;
         case NUM_TEAM_4:    return EFFECT_CAP_PINK;
         default:            return EFFECT_CAP_NEUTRAL;
     }
 }
entity EFFECT_FLAG_TOUCH (int teamid)
Definition at line 188 of file all.inc.
References EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
Referenced by ctf_FlagSetup(), and ons_ControlPoint_Icon_Spawn().
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_FLAG_TOUCH_RED;
         case NUM_TEAM_2:    return EFFECT_FLAG_TOUCH_BLUE;
         case NUM_TEAM_3:    return EFFECT_FLAG_TOUCH_YELLOW;
         case NUM_TEAM_4:    return EFFECT_FLAG_TOUCH_PINK;
         default:            return EFFECT_FLAG_TOUCH_NEUTRAL;
     }
 }
entity EFFECT_PASS (int teamid)
Definition at line 204 of file all.inc.
References EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
Referenced by ctf_FlagSetup().
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_PASS_RED;
         case NUM_TEAM_2:    return EFFECT_PASS_BLUE;
         case NUM_TEAM_3:    return EFFECT_PASS_YELLOW;
         case NUM_TEAM_4:    return EFFECT_PASS_PINK;
         default:            return EFFECT_PASS_NEUTRAL;
     }
 }
entity EFFECT_ROCKETMINSTA_LASER (int teamid)
Definition at line 273 of file all.inc.
References entity(), NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, particleeffectnum, and Team_IsValidTeam().
Referenced by NET_HANDLE().
 {
     entity e;
     switch (teamid) {
         case NUM_TEAM_1:    e = EFFECT_ROCKETMINSTA_LASER_RED; break;
         case NUM_TEAM_2:    e = EFFECT_ROCKETMINSTA_LASER_BLUE; break;
         case NUM_TEAM_3:    e = EFFECT_ROCKETMINSTA_LASER_YELLOW; break;
         case NUM_TEAM_4:    e = EFFECT_ROCKETMINSTA_LASER_PINK; break;
         default:            e = EFFECT_ROCKETMINSTA_LASER_NEUTRAL; break;
     }
     if (particleeffectnum(e) < 0 || !Team_IsValidTeam(teamid)) { e = EFFECT_TR_NEXUIZPLASMA; }
     return e;
 }
entity EFFECT_SPAWN (int teamid)
Definition at line 163 of file all.inc.
References EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_SPAWN_RED;
         case NUM_TEAM_2:    return EFFECT_SPAWN_BLUE;
         case NUM_TEAM_3:    return EFFECT_SPAWN_YELLOW;
         case NUM_TEAM_4:    return EFFECT_SPAWN_PINK;
         default:            return EFFECT_SPAWN_NEUTRAL;
     }
 }
entity EFFECT_SPAWNPOINT (int teamid)
Definition at line 147 of file all.inc.
References EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
Referenced by Spawn_Draw().
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_SPAWNPOINT_RED;
         case NUM_TEAM_2:    return EFFECT_SPAWNPOINT_BLUE;
         case NUM_TEAM_3:    return EFFECT_SPAWNPOINT_YELLOW;
         case NUM_TEAM_4:    return EFFECT_SPAWNPOINT_PINK;
         default:            return EFFECT_SPAWNPOINT_NEUTRAL;
     }
 }
entity EFFECT_VAPORIZER (int teamid)
Definition at line 66 of file all.inc.
References NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_VAPORIZER_RED;
         case NUM_TEAM_2:    return EFFECT_VAPORIZER_BLUE;
         case NUM_TEAM_3:    return EFFECT_VAPORIZER_YELLOW;
         case NUM_TEAM_4:    return EFFECT_VAPORIZER_PINK;
         default:            return EFFECT_VAPORIZER_NEUTRAL;
     }
 }
entity EFFECT_VAPORIZER_HIT (int teamid)
Definition at line 76 of file all.inc.
References EFFECT, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, and NUM_TEAM_4.
 {
     switch (teamid) {
         case NUM_TEAM_1:    return EFFECT_VAPORIZER_HIT_RED;
         case NUM_TEAM_2:    return EFFECT_VAPORIZER_HIT_BLUE;
         case NUM_TEAM_3:    return EFFECT_VAPORIZER_HIT_YELLOW;
         case NUM_TEAM_4:    return EFFECT_VAPORIZER_HIT_PINK;
         default:            return EFFECT_VAPORIZER_HIT_NEUTRAL;
     }
 }