Xonotic: menu/xonotic/checkbox.qc File Reference
checkbox.qc File Reference
#include "checkbox.qh"
Functions
entity makeXonoticCheckBox (float isInverted, string theCvar, string theText)
entity makeXonoticCheckBox_T (float isInverted, string theCvar, string theText, string theTooltip)
entity makeXonoticCheckBoxEx (float theYesValue, float theNoValue, string theCvar, string theText)
entity makeXonoticCheckBoxEx_T (float theYesValue, float theNoValue, string theCvar, string theText, string theTooltip)
void XonoticCheckBox_configureXonoticCheckBox (entity me, float theYesValue, float theNoValue, string theCvar, string theText, string theTooltip)
void XonoticCheckBox_loadCvars (entity me)
void XonoticCheckBox_saveCvars (entity me)
void XonoticCheckBox_setChecked (entity me, float val)
Function Documentation
entity makeXonoticCheckBox (float isInverted, string theCvar, string theText)
Definition at line 28 of file checkbox.qc.
References makeXonoticCheckBox_T(), and string_null.
Referenced by dialog_hudpanel_main_checkbox(), dialog_hudpanel_main_settings(), XonoticDamageTextSettings::fill(), GameType_GetIcon(), XonoticAudioSettingsTab_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticServerListTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCheckBox_T(isInverted, theCvar, theText, string_null);
 }
entity makeXonoticCheckBox_T (float isInverted, string theCvar, string theText, string theTooltip)
Definition at line 3 of file checkbox.qc.
References makeXonoticCheckBoxEx_T().
Referenced by makeXonoticCheckBox(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticServerListTab_fill(), XonoticUserSettingsTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     float m, n;
     if(isInverted > 1)
     {
         n = isInverted - 1;
         m = -n;
     }
     else if(isInverted < -1)
     {
         n = isInverted + 1;
         m = -n;
     }
     else if(isInverted == 1)
     {
         n = 1;
         m = 0;
     }
     else
     {
         n = 0;
         m = 1;
     }
     return makeXonoticCheckBoxEx_T(m, n, theCvar, theText, theTooltip);
 }
entity makeXonoticCheckBoxEx (float theYesValue, float theNoValue, string theCvar, string theText)
Definition at line 40 of file checkbox.qc.
References makeXonoticCheckBoxEx_T(), and string_null.
Referenced by XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticScreenshotBrowserTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCheckBoxEx_T(theYesValue, theNoValue, theCvar, theText, string_null);
 }
entity makeXonoticCheckBoxEx_T (float theYesValue, float theNoValue, string theCvar, string theText, string theTooltip)
Definition at line 33 of file checkbox.qc.
References entity(), and NEW.
Referenced by makeXonoticCheckBox_T(), makeXonoticCheckBoxEx(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), and XonoticGameViewSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticCheckBox);
     me.configureXonoticCheckBox(me, theYesValue, theNoValue, theCvar, theText, theTooltip);
     return me;
 }
void XonoticCheckBox_configureXonoticCheckBox (entity me, float theYesValue, float theNoValue, string theCvar, string theText, string theTooltip)
Definition at line 45 of file checkbox.qc.
References setZonedTooltip(), and string_null.
 {
     me.yesValue = theYesValue;
     me.noValue = theNoValue;
     me.checked = 0;
     me.cvarName = (theCvar) ? theCvar : string_null;
     me.loadCvars(me);
     setZonedTooltip(me, theTooltip, theCvar);
     me.configureCheckBox(me, theText, me.fontSize, me.image);
 }
void XonoticCheckBox_loadCvars (entity me)
Definition at line 65 of file checkbox.qc.
References cvar().
 {
     float m, d;
     if (!me.cvarName)
         return;
     m = (me.yesValue + me.noValue) * 0.5;
     d = (cvar(me.cvarName) - m) / (me.yesValue - m);
     me.checked = (d > 0);
 }
void XonoticCheckBox_saveCvars (entity me)
Definition at line 76 of file checkbox.qc.
References CheckSendCvars(), cvar_set(), and ftos_mindecimals().
 {
     if (!me.cvarName)
         return;
     if(me.checked)
         cvar_set(me.cvarName, ftos_mindecimals(me.yesValue));
     else
         cvar_set(me.cvarName, ftos_mindecimals(me.noValue));
     CheckSendCvars(me, me.cvarName);
 }
void XonoticCheckBox_setChecked (entity me, float val)
Definition at line 55 of file checkbox.qc.
 {
     if(val != me.checked)
     {
         me.checked = val;
         me.saveCvars(me);
         if(me.linkedCheckBox)
             me.linkedCheckBox.loadCvars(me.linkedCheckBox);
     }
 }