Xonotic: menu/item.qc File Reference
item.qc File Reference
#include "item.qh"
#include "item/container.qh"
#include "item/borderimage.qh"
Functions
if (this.instanceOfContainer||this.instanceOfBorderImage)
if (autocvar_menu_showboxes< 0)
else if (autocvar_menu_showboxes > 0)
Variables
vector rgb = '1 0 1'
float a = fabs(autocvar_menu_showboxes)
Function Documentation
if (this.instanceOfContainer||this. instanceOfBorderImage)
Definition at line 32 of file item.qc.
         {
             rgb = '0 0 0';
             a = 0;
         }
if ()
Definition at line 45 of file item.qc.
References draw_Fill().
         {
             draw_Fill('0 0 0', '0.5 0.5 0', rgb, a);
             draw_Fill('0.5 0.5 0', '0.5 0.5 0', rgb, a);
         }
else if (autocvar_menu_showboxes , 0)
Definition at line 50 of file item.qc.
References draw_Fill().
         {
             draw_Fill('0 0 0', '1 1 0', rgb, a);
         }
Variable Documentation
float a = fabs(autocvar_menu_showboxes)
Definition at line 29 of file item.qc.
Referenced by _MapInfo_FilterList_cmp(), accuracy_add(), accuracy_init(), accuracy_send(), adaptor_think2use(), angc(), animdecide_getloweranim(), animdecide_getupperanim(), animfixfps(), beamsweep(), bot_serverframe(), CampaignFile_Load(), cons(), Container_enterLieSubitem(), CSQC_UpdateView(), Draw_ShowNames(), explosion_calcpush_getmultiplier(), FullTraceFraction(), GetAttackDecaySustainAmplitude(), GetAttackTime(), gsl_ran_gaussian(), HitSound(), HUD_CenterPrint(), HUD_Chat(), HUD_InfoMessages(), HUD_Mod_Race(), HUD_Powerups(), HUD_RaceTimer(), HUD_Vote(), HUD_Weapons(), info_autoscreenshot_findtarget(), ListBox_keyDown(), MapInfo_Get_ByName_NoFallbacks(), Monster_Move_2D(), movelib_groundalign4point(), Nexposee_draw(), nextafter(), pathlib_walknode(), Projectile_Draw(), RadarMapAtPoint_Sample(), RadarMapAtPoint_Trace(), RadiusDamageForSource(), sharpen_get(), solve_cubic_pq(), solve_quadratic(), turret_draw2d(), viewmodel_draw(), W_ThrowWeapon(), weapon_thinkf(), xdecode(), xencode(), XonoticCrosshairPreview_draw(), and XonoticMapList_g_maplistCacheToggle().
vector rgb = '1 0 1'
Definition at line 28 of file item.qc.
Referenced by GameTypeVote_DrawGameTypeItem(), GenericCommand(), HUD_DrawScoreboard(), HUD_PrintScoreboardItem(), HUD_Score_Rankings(), hue_mi_ma_to_rgb(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), Porto_Draw(), turret_draw2d(), vehicles_showwp(), XonoticCrosshairPreview_draw(), and XonoticPlayerList_drawListBoxItem().