Xonotic: common/animdecide.qh File Reference
animdecide.qh File Reference
Classes
class Animation
Macros
#define ReadAnimation() ReadRegistered(Animations)
#define REGISTER_ANIMATION(id, framenames)
#define WriteAnimation(to, it) WriteRegistered(Animations, to, it)
Functions
vector anim_vec (Animation anim, int mdlidx, int numframes, float framerate)
void animdecide_load_if_needed (entity e)
void animdecide_setaction (entity e, float action, float restart)
void animdecide_setframes (entity e, bool support_blending,.int fld_frame,.int fld_frame1time,.int fld_frame2,.int fld_frame2time)
void animdecide_setimplicitstate (entity e, float onground)
void animdecide_setstate (entity e, int newstate, float restart)
REGISTER_ANIMATION (die1, "dieone groupified_0_anim")
player dies
REGISTER_ANIMATION (die2, "dietwo groupified_1_anim")
player dies differently
REGISTER_ANIMATION (draw, "draw groupified_2_anim")
player pulls out a weapon
REGISTER_ANIMATION (duck, "duck groupified_3_anim")
REGISTER_ANIMATION (duckwalk, "duckwalk groupified_4_anim")
player walking while crouching
REGISTER_ANIMATION (duckjump, "duckjump groupified_5_anim")
player jumping from a crouch
REGISTER_ANIMATION (duckidle, "duckidle groupified_6_anim")
player idling while crouching
REGISTER_ANIMATION (idle, "idle groupified_7_anim")
player standing
REGISTER_ANIMATION (jump, "jump groupified_8_anim")
player jump
REGISTER_ANIMATION (pain1, "painone groupified_9_anim")
player flinches from pain
REGISTER_ANIMATION (pain2, "paintwo groupified_10_anim")
player flinches from pain, differently
REGISTER_ANIMATION (shoot, "shoot groupified_11_anim")
player shoots
REGISTER_ANIMATION (taunt, "taunt groupified_12_anim")
player taunts others (FIXME: no code references this)
REGISTER_ANIMATION (run, "run groupified_13_anim")
player running forward
REGISTER_ANIMATION (runbackwards, "runbackwards groupified_14_anim")
player running backward
REGISTER_ANIMATION (strafeleft, "strafeleft groupified_15_anim")
player shuffling left quickly
REGISTER_ANIMATION (straferight, "straferight groupified_16_anim")
player shuffling right quickly
REGISTER_ANIMATION (dead1, "deadone groupified_17_anim")
REGISTER_ANIMATION (dead2, "deadtwo groupified_18_anim")
REGISTER_ANIMATION (forwardright, "forwardright groupified_19_anim")
player running forward and right
REGISTER_ANIMATION (forwardleft, "forwardleft groupified_20_anim")
player running forward and left
REGISTER_ANIMATION (backright, "backright groupified_21_anim")
player running backward and right
REGISTER_ANIMATION (backleft, "backleft groupified_22_anim")
player running back and left
REGISTER_ANIMATION (melee, "melee groupified_23_anim")
player doing the melee action
REGISTER_ANIMATION (duckwalkbackwards, "duckwalkbackwards groupified_24_anim")
REGISTER_ANIMATION (duckwalkstrafeleft, "duckwalkstrafeleft duckstrafeleft groupified_25_anim")
REGISTER_ANIMATION (duckwalkstraferight, "duckwalkstraferight duckstraferight groupified_26_anim")
REGISTER_ANIMATION (duckwalkforwardright, "duckwalkforwardright duckforwardright groupified_27_anim")
REGISTER_ANIMATION (duckwalkforwardleft, "duckwalkforwardleft groupified_28_anim")
REGISTER_ANIMATION (duckwalkbackright, "duckwalkbackright duckbackwardright groupified_29_anim")
REGISTER_ANIMATION (duckwalkbackleft, "duckwalkbackleft duckbackwardleft groupified_30_anim")
Variables
int anim_implicit_state
float anim_implicit_time
float anim_lower_action
float anim_lower_implicit_action
float anim_lower_implicit_time
float anim_lower_time
int anim_state
float anim_time
float anim_upper_action
float anim_upper_implicit_action
float anim_upper_implicit_time
float anim_upper_time
const int ANIMACTION_DRAW = 1
const int ANIMACTION_JUMP = -1
const int ANIMACTION_MELEE = 6
const int ANIMACTION_PAIN1 = 2
const int ANIMACTION_PAIN2 = 3
const int ANIMACTION_SHOOT = 4
const int ANIMACTION_TAUNT = 5
float animdecide_modelindex
const int ANIMIMPLICITSTATE_BACKWARDS = BIT(2)
const int ANIMIMPLICITSTATE_FORWARD = BIT(1)
const int ANIMIMPLICITSTATE_INAIR = BIT(0)
const int ANIMIMPLICITSTATE_JUMPRELEASED = BIT(5)
const int ANIMIMPLICITSTATE_LEFT = BIT(3)
const int ANIMIMPLICITSTATE_RIGHT = BIT(4)
const int ANIMSTATE_DEAD1 = BIT(0)
const int ANIMSTATE_DEAD2 = BIT(1)
const int ANIMSTATE_DUCK = BIT(2)
const int ANIMSTATE_FOLLOW = BIT(4)
const int ANIMSTATE_FROZEN = BIT(3)
Macro Definition Documentation
ReadAnimation
#define ReadAnimation () ReadRegistered(Animations)
Definition at line 30 of file animdecide.qh.
REGISTER_ANIMATION
#define REGISTER_ANIMATION (id, framenames)
Value:
.vector anim_##id; \
    REGISTER(Animations, ANIM_##id, m_id, NEW(Animation)) { \
        this.m_framenames = framenames; \
    }
Definition at line 31 of file animdecide.qh.
Referenced by anim_vec().
WriteAnimation
#define WriteAnimation (to, it) WriteRegistered(Animations, to, it)
Definition at line 29 of file animdecide.qh.
Function Documentation
anim_vec()
vector anim_vec (Animation anim, int mdlidx, int numframes, float framerate)
Definition at line 37 of file animdecide.qh.
References REGISTER_ANIMATION, v, and vector().
 {
     vector v;
     v.x = Animation_getframe(anim, mdlidx);
     v.y = numframes;
     v.z = framerate;
     return v;
 }
animdecide_load_if_needed()
void animdecide_load_if_needed (entity e)
Definition at line 53 of file animdecide.qc.
References ANIM_VEC, monsters_animoverride(), substring(), and vector().
Referenced by CopyBody(), CSQCModel_Hook_PreDraw(), and player_setupanimsformodel().
 {
     int mdlidx = e.modelindex;
     if (mdlidx == e.animdecide_modelindex) return;
     e.animdecide_modelindex = mdlidx;
     if(substring(e.model, 0, 16) == "models/monsters/")
     {
         if(monsters_animoverride(e))
             return;
     }
 #define ANIM_VEC(a, frames, rate) anim_vec(ANIM_##a, mdlidx, frames, rate)
     vector none = '0 0 0';
     e.anim_die1 = animfixfps(e, ANIM_VEC(die1, 1, 0.5), none); // 2 seconds
     e.anim_die2 = animfixfps(e, ANIM_VEC(die2, 1, 0.5), none); // 2 seconds
     e.anim_draw = animfixfps(e, ANIM_VEC(draw, 1, 3), none);
     e.anim_duckwalk = animfixfps(e, ANIM_VEC(duckwalk, 1, 1), none);
     e.anim_duckjump = animfixfps(e, ANIM_VEC(duckjump, 1, 10), none);
     e.anim_duckidle = animfixfps(e, ANIM_VEC(duckidle, 1, 1), none);
     e.anim_idle = animfixfps(e, ANIM_VEC(idle, 1, 1), none);
     e.anim_jump = animfixfps(e, ANIM_VEC(jump, 1, 10), none);
     e.anim_pain1 = animfixfps(e, ANIM_VEC(pain1, 1, 2), none); // 0.5 seconds
     e.anim_pain2 = animfixfps(e, ANIM_VEC(pain2, 1, 2), none); // 0.5 seconds
     e.anim_shoot = animfixfps(e, ANIM_VEC(shoot, 1, 5), none); // analyze models and set framerate
     e.anim_taunt = animfixfps(e, ANIM_VEC(taunt, 1, 0.33), none);
     e.anim_run = animfixfps(e, ANIM_VEC(run, 1, 1), none);
     e.anim_runbackwards = animfixfps(e, ANIM_VEC(runbackwards, 1, 1), none);
     e.anim_strafeleft = animfixfps(e, ANIM_VEC(strafeleft, 1, 1), none);
     e.anim_straferight = animfixfps(e, ANIM_VEC(straferight, 1, 1), none);
     e.anim_forwardright = animfixfps(e, ANIM_VEC(forwardright, 1, 1), ANIM_VEC(straferight, 1, 1));
     e.anim_forwardleft = animfixfps(e, ANIM_VEC(forwardleft, 1, 1), ANIM_VEC(strafeleft, 1, 1));
     e.anim_backright = animfixfps(e, ANIM_VEC(backright, 1, 1), ANIM_VEC(straferight, 1, 1));
     e.anim_backleft  = animfixfps(e, ANIM_VEC(backleft , 1, 1), ANIM_VEC(strafeleft, 1, 1));
     e.anim_melee = animfixfps(e, ANIM_VEC(melee, 1, 1), ANIM_VEC(shoot, 1, 1));
     e.anim_duckwalkbackwards = animfixfps(e, ANIM_VEC(duckwalkbackwards, 1, 1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkstrafeleft = animfixfps(e, ANIM_VEC(duckwalkstrafeleft, 1, 1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkstraferight = animfixfps(e, ANIM_VEC(duckwalkstraferight, 1, 1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkforwardright = animfixfps(e, ANIM_VEC(duckwalkforwardright, 1, 1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkforwardleft = animfixfps(e, ANIM_VEC(duckwalkforwardleft, 1, 1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkbackright = animfixfps(e, ANIM_VEC(duckwalkbackright, 1,  1), ANIM_VEC(duckwalk, 1, 1));
     e.anim_duckwalkbackleft  = animfixfps(e, ANIM_VEC(duckwalkbackleft , 1,  1), ANIM_VEC(duckwalk, 1, 1));
 #undef ANIM_VEC
     // these anims ought to stay until stopped explicitly by weaponsystem
     e.anim_shoot_z = 0.001;
     e.anim_melee_z = 0.001;
 }
animdecide_setaction()
void animdecide_setaction (entity e, float action, float restart)
Definition at line 338 of file animdecide.qc.
References time.
Referenced by jumppad_push(), PlayerDamage(), PlayerJump(), PM_dodging(), UpdatePlayerSounds(), and weapon_thinkf().
 {
     if(action < 0)
     {
         if(!restart)
             if(action == e.anim_lower_action)
                 return;
         e.anim_lower_action = action;
         e.anim_lower_time = time;
     }
     else
     {
         if(!restart)
             if(action == e.anim_upper_action)
                 return;
         e.anim_upper_action = action;
         e.anim_upper_time = time;
     }
 }
animdecide_setframes()
void animdecide_setframes (entity e, bool support_blending, .int fld_frame, .int fld_frame1time, .int fld_frame2, .int fld_frame2time)
animdecide_setimplicitstate()
void animdecide_setimplicitstate (entity e, float onground)
Definition at line 248 of file animdecide.qc.
References ANIMACTION_JUMP, ANIMIMPLICITSTATE_BACKWARDS, ANIMIMPLICITSTATE_FORWARD, ANIMIMPLICITSTATE_INAIR, ANIMIMPLICITSTATE_LEFT, ANIMIMPLICITSTATE_RIGHT, fabs(), makevectors, time, v, v_forward, v_right, vdist, and vector().
Referenced by CSQCModel_Hook_PreDraw(), Monster_Anim(), and player_anim().
 {
     int s = 0;
     makevectors(e.angles);
     vector v;
     v.x = e.velocity * v_forward;
     v.y = e.velocity * v_right;
     v.z = 0;
     // we want to match like this:
     // the 8 directions shall be "evenly spaced"
     // that means, the forward key includes anything from -67.5 to +67.5 degrees
     // which then means x > |y| * cot(3pi/8)
     //
     // BUT, the engine's clip-movement-to-keyboard function uses 0.5 here,
     // which would be an angle range from -63.43 to +63.43 degrees, making
     // it slightly less likely to "hit two keys at once", so let's do this
     // here too
     if(vdist(v, >, 10))
     {
         if(v.x >  fabs(v.y) * 0.5)
             s |= ANIMIMPLICITSTATE_FORWARD;
         if(v.x < -fabs(v.y) * 0.5)
             s |= ANIMIMPLICITSTATE_BACKWARDS;
         if(v.y >  fabs(v.x) * 0.5)
             s |= ANIMIMPLICITSTATE_RIGHT;
         if(v.y < -fabs(v.x) * 0.5)
             s |= ANIMIMPLICITSTATE_LEFT;
     }
     if(!onground)
         s |= ANIMIMPLICITSTATE_INAIR;
     // detect some kinds of otherwise misdetected jumps (ground to air transition)
     // NOTE: currently, in CSQC this is the only jump detection, as the explicit jump action is never called!
     if(!(e.anim_implicit_state & ANIMIMPLICITSTATE_INAIR) && (s & ANIMIMPLICITSTATE_INAIR))
     {
         e.anim_lower_implicit_action = ANIMACTION_JUMP;
         e.anim_lower_implicit_time = time;
     }
     if(s != e.anim_implicit_state)
     {
         e.anim_implicit_state = s;
         e.anim_implicit_time = time;
     }
 }
animdecide_setstate()
void animdecide_setstate (entity e, int newstate, float restart)
Definition at line 330 of file animdecide.qc.
References time.
Referenced by CSQCModel_Hook_PreDraw(), Monster_Anim(), player_anim(), player_setupanimsformodel(), and PlayerDamage().
 {
     if(!restart)
         if(newstate == e.anim_state)
             return;
     e.anim_state = newstate;
     e.anim_time = time;
 }
REGISTER_ANIMATION() [1/31]
REGISTER_ANIMATION (die1 , "dieone groupified_0_anim")
player dies
REGISTER_ANIMATION() [2/31]
REGISTER_ANIMATION (die2 , "dietwo groupified_1_anim")
player dies differently
REGISTER_ANIMATION() [3/31]
REGISTER_ANIMATION (draw , "draw groupified_2_anim")
player pulls out a weapon
REGISTER_ANIMATION() [4/31]
REGISTER_ANIMATION (duck , "duck groupified_3_anim")
REGISTER_ANIMATION() [5/31]
REGISTER_ANIMATION (duckwalk , "duckwalk groupified_4_anim")
player walking while crouching
REGISTER_ANIMATION() [6/31]
REGISTER_ANIMATION (duckjump , "duckjump groupified_5_anim")
player jumping from a crouch
REGISTER_ANIMATION() [7/31]
REGISTER_ANIMATION (duckidle , "duckidle groupified_6_anim")
player idling while crouching
REGISTER_ANIMATION() [8/31]
REGISTER_ANIMATION (idle , "idle groupified_7_anim")
player standing
REGISTER_ANIMATION() [9/31]
REGISTER_ANIMATION (jump , "jump groupified_8_anim")
player jump
REGISTER_ANIMATION() [10/31]
REGISTER_ANIMATION (pain1 , "painone groupified_9_anim")
player flinches from pain
REGISTER_ANIMATION() [11/31]
REGISTER_ANIMATION (pain2 , "paintwo groupified_10_anim")
player flinches from pain, differently
REGISTER_ANIMATION() [12/31]
REGISTER_ANIMATION (shoot , "shoot groupified_11_anim")
player shoots
REGISTER_ANIMATION() [13/31]
REGISTER_ANIMATION (taunt , "taunt groupified_12_anim")
player taunts others (FIXME: no code references this)
REGISTER_ANIMATION() [14/31]
REGISTER_ANIMATION (run , "run groupified_13_anim")
player running forward
REGISTER_ANIMATION() [15/31]
REGISTER_ANIMATION (runbackwards , "runbackwards groupified_14_anim")
player running backward
REGISTER_ANIMATION() [16/31]
REGISTER_ANIMATION (strafeleft , "strafeleft groupified_15_anim")
player shuffling left quickly
REGISTER_ANIMATION() [17/31]
REGISTER_ANIMATION (straferight , "straferight groupified_16_anim")
player shuffling right quickly
REGISTER_ANIMATION() [18/31]
REGISTER_ANIMATION (dead1 , "deadone groupified_17_anim")
REGISTER_ANIMATION() [19/31]
REGISTER_ANIMATION (dead2 , "deadtwo groupified_18_anim")
REGISTER_ANIMATION() [20/31]
REGISTER_ANIMATION (forwardright , "forwardright groupified_19_anim")
player running forward and right
REGISTER_ANIMATION() [21/31]
REGISTER_ANIMATION (forwardleft , "forwardleft groupified_20_anim")
player running forward and left
REGISTER_ANIMATION() [22/31]
REGISTER_ANIMATION (backright , "backright groupified_21_anim")
player running backward and right
REGISTER_ANIMATION() [23/31]
REGISTER_ANIMATION (backleft , "backleft groupified_22_anim")
player running back and left
REGISTER_ANIMATION() [24/31]
REGISTER_ANIMATION (melee , "melee groupified_23_anim")
player doing the melee action
REGISTER_ANIMATION() [25/31]
REGISTER_ANIMATION (duckwalkbackwards , "duckwalkbackwards groupified_24_anim")
REGISTER_ANIMATION() [26/31]
REGISTER_ANIMATION (duckwalkstrafeleft , "duckwalkstrafeleft duckstrafeleft groupified_25_anim")
REGISTER_ANIMATION() [27/31]
REGISTER_ANIMATION (duckwalkstraferight , "duckwalkstraferight duckstraferight groupified_26_anim")
REGISTER_ANIMATION() [28/31]
REGISTER_ANIMATION (duckwalkforwardright , "duckwalkforwardright duckforwardright groupified_27_anim")
REGISTER_ANIMATION() [29/31]
REGISTER_ANIMATION (duckwalkforwardleft , "duckwalkforwardleft groupified_28_anim")
REGISTER_ANIMATION() [30/31]
REGISTER_ANIMATION (duckwalkbackright , "duckwalkbackright duckbackwardright groupified_29_anim")
REGISTER_ANIMATION() [31/31]
REGISTER_ANIMATION (duckwalkbackleft , "duckwalkbackleft duckbackwardleft groupified_30_anim")
Variable Documentation
anim_implicit_state
int anim_implicit_state
Definition at line 116 of file animdecide.qh.
Referenced by CopyBody().
anim_implicit_time
float anim_implicit_time
Definition at line 117 of file animdecide.qh.
Referenced by CopyBody().
anim_lower_action
float anim_lower_action
Definition at line 110 of file animdecide.qh.
Referenced by CopyBody().
anim_lower_implicit_action
float anim_lower_implicit_action
Definition at line 118 of file animdecide.qh.
Referenced by CopyBody().
anim_lower_implicit_time
float anim_lower_implicit_time
Definition at line 119 of file animdecide.qh.
Referenced by CopyBody().
anim_lower_time
float anim_lower_time
Definition at line 111 of file animdecide.qh.
Referenced by CopyBody().
anim_state
int anim_state
Definition at line 108 of file animdecide.qh.
Referenced by CopyBody(), CSQCModel_Hook_PreDraw(), CSQCPlayer_AnimDecide_PostUpdate(), Monster_Anim(), player_anim(), and PlayerDamage().
anim_time
float anim_time
Definition at line 109 of file animdecide.qh.
Referenced by CopyBody().
anim_upper_action
float anim_upper_action
Definition at line 112 of file animdecide.qh.
Referenced by CopyBody().
anim_upper_implicit_action
float anim_upper_implicit_action
Definition at line 120 of file animdecide.qh.
Referenced by CopyBody().
anim_upper_implicit_time
float anim_upper_implicit_time
Definition at line 121 of file animdecide.qh.
Referenced by CopyBody().
anim_upper_time
float anim_upper_time
Definition at line 113 of file animdecide.qh.
Referenced by CopyBody().
ANIMACTION_DRAW
const int ANIMACTION_DRAW = 1
Definition at line 142 of file animdecide.qh.
Referenced by animdecide_getupperanim().
ANIMACTION_JUMP
const int ANIMACTION_JUMP = -1
Definition at line 141 of file animdecide.qh.
Referenced by animdecide_getloweranim(), animdecide_setimplicitstate(), jumppad_push(), PlayerJump(), and PM_dodging().
ANIMACTION_MELEE
const int ANIMACTION_MELEE = 6
Definition at line 147 of file animdecide.qh.
Referenced by animdecide_getupperanim(), and weapon_thinkf().
ANIMACTION_PAIN1
const int ANIMACTION_PAIN1 = 2
Definition at line 143 of file animdecide.qh.
Referenced by animdecide_getupperanim(), and PlayerDamage().
ANIMACTION_PAIN2
const int ANIMACTION_PAIN2 = 3
Definition at line 144 of file animdecide.qh.
Referenced by animdecide_getupperanim(), and PlayerDamage().
ANIMACTION_SHOOT
const int ANIMACTION_SHOOT = 4
Definition at line 145 of file animdecide.qh.
Referenced by animdecide_getupperanim(), and weapon_thinkf().
ANIMACTION_TAUNT
const int ANIMACTION_TAUNT = 5
Definition at line 146 of file animdecide.qh.
Referenced by animdecide_getupperanim(), and UpdatePlayerSounds().
animdecide_modelindex
float animdecide_modelindex
Definition at line 105 of file animdecide.qh.
ANIMIMPLICITSTATE_BACKWARDS
const int ANIMIMPLICITSTATE_BACKWARDS = BIT(2)
Definition at line 134 of file animdecide.qh.
Referenced by animdecide_getloweranim(), and animdecide_setimplicitstate().
ANIMIMPLICITSTATE_FORWARD
const int ANIMIMPLICITSTATE_FORWARD = BIT(1)
Definition at line 133 of file animdecide.qh.
Referenced by animdecide_getloweranim(), and animdecide_setimplicitstate().
ANIMIMPLICITSTATE_INAIR
const int ANIMIMPLICITSTATE_INAIR = BIT(0)
Definition at line 132 of file animdecide.qh.
Referenced by animdecide_getloweranim(), animdecide_setimplicitstate(), bobmodel_ofs(), and HUD_StrafeHUD().
ANIMIMPLICITSTATE_JUMPRELEASED
const int ANIMIMPLICITSTATE_JUMPRELEASED = BIT(5)
Definition at line 137 of file animdecide.qh.
ANIMIMPLICITSTATE_LEFT
const int ANIMIMPLICITSTATE_LEFT = BIT(3)
Definition at line 135 of file animdecide.qh.
Referenced by animdecide_getloweranim(), and animdecide_setimplicitstate().
ANIMIMPLICITSTATE_RIGHT
const int ANIMIMPLICITSTATE_RIGHT = BIT(4)
Definition at line 136 of file animdecide.qh.
Referenced by animdecide_getloweranim(), and animdecide_setimplicitstate().
ANIMSTATE_DEAD1
const int ANIMSTATE_DEAD1 = BIT(0)
Definition at line 125 of file animdecide.qh.
Referenced by animdecide_getloweranim(), animdecide_getupperanim(), CSQCPlayer_AnimDecide_PostUpdate(), Monster_Anim(), player_anim(), and PlayerDamage().
ANIMSTATE_DEAD2
const int ANIMSTATE_DEAD2 = BIT(1)
Definition at line 126 of file animdecide.qh.
Referenced by animdecide_getloweranim(), animdecide_getupperanim(), CSQCPlayer_AnimDecide_PostUpdate(), Monster_Anim(), player_anim(), and PlayerDamage().
ANIMSTATE_DUCK
const int ANIMSTATE_DUCK = BIT(2)
Definition at line 127 of file animdecide.qh.
Referenced by animdecide_getloweranim(), CSQCModel_Hook_PreDraw(), Monster_Anim(), and player_anim().
ANIMSTATE_FOLLOW
const int ANIMSTATE_FOLLOW = BIT(4)
Definition at line 129 of file animdecide.qh.
Referenced by animdecide_getloweranim(), and player_anim().
ANIMSTATE_FROZEN
const int ANIMSTATE_FROZEN = BIT(3)
Definition at line 128 of file animdecide.qh.
Referenced by animdecide_getloweranim(), animdecide_getupperanim(), Monster_Anim(), and player_anim().