Xonotic: common/turrets/checkpoint.qc File Reference
checkpoint.qc File Reference
#include "checkpoint.qh"
Functions
spawnfunc (turret_checkpoint)
spawnfunc (walker_checkpoint)
void turret_checkpoint_init (entity this)
void turret_checkpoint_use ()
Variables
entity pathgoal
turret_checkpoint
Function Documentation
spawnfunc (turret_checkpoint)
Definition at line 67 of file checkpoint.qc.
References nextthink, origin, setorigin(), setthink, time, and turret_checkpoint_init().
 {
     setorigin(this, this.origin);
     setthink(this, turret_checkpoint_init);
     this.nextthink = time + 0.2;
 }
spawnfunc (walker_checkpoint)
Definition at line 75 of file checkpoint.qc.
References classname.
 {
     this.classname = "turret_checkpoint";
     spawnfunc_turret_checkpoint(this);
 }
void turret_checkpoint_init (entity this)
Definition at line 51 of file checkpoint.qc.
References enemy, find(), LOG_TRACE(), MOVE_WORLDONLY, NULL, origin, setorigin(), target, targetname, and trace_endpos.
Referenced by spawnfunc().
 {
     traceline(this.origin + '0 0 16', this.origin - '0 0 1024', MOVE_WORLDONLY, this);
     setorigin(this, trace_endpos + '0 0 32');
     if(this.target != "")
     {
         this.enemy = find(NULL, targetname, this.target);
         if(this.enemy == NULL)
             LOG_TRACE("A turret_checkpoint faild to find its target!");
     }
     //setthink(this, turret_checkpoint_think);
     //this.nextthink = time + tc_acum + 0.25;
     //tc_acum += 0.25;
 }
void turret_checkpoint_use ()
Definition at line 28 of file checkpoint.qc.
 {
 }
Variable Documentation
entity pathgoal
turret_checkpoint
Definition at line 15 of file checkpoint.qc.