Xonotic: FreezeTag Class Reference
FreezeTag Class Reference
Public Member Functions
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
FreezeTag ::FreezeTag ()
virtual void FreezeTag ::m_configuremenu ()
virtual void FreezeTag ::m_isAlwaysSupported ()
virtual void FreezeTag ::m_parse_mapinfo ()
virtual void FreezeTag ::m_setTeams ()
virtual void Gametype ::describe ()
virtual void Gametype ::display ()
virtual void Gametype ::gametype_init ()
virtual void Gametype ::m_configuremenu ()
virtual void Gametype ::m_generate_mapinfo ()
virtual void Gametype ::m_isAlwaysSupported ()
virtual void Gametype ::m_isForcedSupported ()
virtual void Gametype ::m_isTwoBaseMode ()
virtual void Gametype ::m_parse_mapinfo ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
bool m_hidelimits = false
should this gametype display a score limit in the scoreboard?
int m_id = 0
string m_legacydefaults = "10 20 0"
int m_priority = 0
game type priority in random selections
bool m_weaponarena = false
does this gametype enforce its own weapon arena?
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 12 of file freezetag.qh.
Member Function Documentation
ATTRIB() [1/6]
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
ATTRIB() [2/6]
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
ATTRIB() [3/6]
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
ATTRIB() [4/6]
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
ATTRIB() [5/6]
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
ATTRIB() [6/6]
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
FreezeTag ::FreezeTag()
FreezeTag::FreezeTag ::FreezeTag () inline
Definition at line 13 of file freezetag.qh.
     {
         this.gametype_init(this, _("Freeze Tag"),"ft","g_freezetag",GAMETYPE_FLAG_TEAMPLAY | GAMETYPE_FLAG_USEPOINTS,"","timelimit=20 pointlimit=10 teams=2 leadlimit=6",_("Kill enemies to freeze them, stand next to frozen teammates to revive them; freeze all enemies to win"));
     }
FreezeTag ::m_configuremenu()
virtual void FreezeTag::FreezeTag ::m_configuremenu () inline virtual
Definition at line 40 of file freezetag.qh.
References TC.
     {
         TC(Gametype, this);
         returns(menu, _("Frag limit:"),      5,  100,  5, "fraglimit_override",        "g_freezetag_teams_override",   _("The amount of frags needed before the match will end"));
     }
FreezeTag ::m_isAlwaysSupported()
virtual void FreezeTag::FreezeTag ::m_isAlwaysSupported () inline virtual
Definition at line 30 of file freezetag.qh.
     {
         if(spawnpoints >= 8 && diameter > 4096)
             return true;
         return false;
     }
FreezeTag ::m_parse_mapinfo()
virtual void FreezeTag::FreezeTag ::m_parse_mapinfo () inline virtual
Definition at line 17 of file freezetag.qh.
References cvar_defstring(), and cvar_set().
     {
         if (!k) {
             cvar_set("g_freezetag_teams", cvar_defstring("g_freezetag_teams"));
             return true;
         }
         switch (k) {
             case "teams":
                 cvar_set("g_freezetag_teams", v);
                 return true;
         }
         return false;
     }
FreezeTag ::m_setTeams()
virtual void FreezeTag::FreezeTag ::m_setTeams () inline virtual
Definition at line 36 of file freezetag.qh.
References cvar_set().
     {
         cvar_set("g_freezetag_teams", sa);
     }
Gametype ::describe()
virtual void Gametype::Gametype ::describe () inline virtual inherited
Definition at line 89 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
Gametype ::display()
virtual void Gametype::Gametype ::display () inline virtual inherited
Definition at line 95 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
Gametype ::gametype_init()
virtual void Gametype::Gametype ::gametype_init () inline virtual inherited
Definition at line 101 of file mapinfo.qh.
References cons(), ENDCLASS, GAMETYPE_FLAG_HIDELIMITS, GAMETYPE_FLAG_PREFERRED, GAMETYPE_FLAG_PRIORITY, GAMETYPE_FLAG_TEAMPLAY, GAMETYPE_FLAG_USEPOINTS, GAMETYPE_FLAG_WEAPONARENA, m_flags, MAPINFO_TYPE_ALL, NULL, REGISTER_REGISTRY, REGISTRY, REGISTRY_CHECK(), REGISTRY_DEFINE_GET, and REGISTRY_SORT().
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = (gflags & GAMETYPE_FLAG_TEAMPLAY);
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = (gflags & GAMETYPE_FLAG_USEPOINTS);
         this.m_priority = ((gflags & GAMETYPE_FLAG_PREFERRED) ? 2 : ((gflags & GAMETYPE_FLAG_PRIORITY) ? 1 : 0));
         this.m_hidelimits = (gflags & GAMETYPE_FLAG_HIDELIMITS);
         this.m_weaponarena = (gflags & GAMETYPE_FLAG_WEAPONARENA);
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
Gametype ::m_configuremenu()
virtual void Gametype::Gametype ::m_configuremenu () inline virtual inherited
Definition at line 83 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         returns(menu, _("Frag limit:"),      5,  100,  5, "fraglimit_override",        string_null,                    _("The amount of frags needed before the match will end"));
     }
Gametype ::m_generate_mapinfo()
virtual void Gametype::Gametype ::m_generate_mapinfo () inline virtual inherited
Definition at line 67 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
Gametype ::m_isAlwaysSupported()
virtual void Gametype::Gametype ::m_isAlwaysSupported () inline virtual inherited
Definition at line 75 of file mapinfo.qh.
     {
         return false;
     }
Gametype ::m_isForcedSupported()
virtual void Gametype::Gametype ::m_isForcedSupported () inline virtual inherited
Definition at line 79 of file mapinfo.qh.
     {
         return false;
     }
Gametype ::m_isTwoBaseMode()
virtual void Gametype::Gametype ::m_isTwoBaseMode () inline virtual inherited
Definition at line 71 of file mapinfo.qh.
     {
         return false;
     }
Gametype ::m_parse_mapinfo()
virtual void Gametype::Gametype ::m_parse_mapinfo () inline virtual inherited
Definition at line 63 of file mapinfo.qh.
     {
         return false;
     }
Member Data Documentation
frags
bool Gametype::frags = true inherited
does this gametype use a point limit?
Definition at line 42 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
items
int Gametype::items = 0 inherited
game type ID
Definition at line 32 of file mapinfo.qh.
m_hidelimits
bool Gametype::m_hidelimits = false inherited
should this gametype display a score limit in the scoreboard?
Definition at line 44 of file mapinfo.qh.
m_id
int Gametype::m_id = 0 inherited
Definition at line 30 of file mapinfo.qh.
m_legacydefaults
string FreezeTag::m_legacydefaults = "10 20 0"
Definition at line 49 of file freezetag.qh.
m_priority
int Gametype::m_priority = 0 inherited
game type priority in random selections
Definition at line 52 of file mapinfo.qh.
m_weaponarena
bool Gametype::m_weaponarena = false inherited
does this gametype enforce its own weapon arena?
Definition at line 46 of file mapinfo.qh.
team
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 40 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/gamemodes/gamemode/freezetag/freezetag.qh