Xonotic: server/bot/havocbot/roles.qh File Reference
roles.qh File Reference
Macros
#define ROLES_H
Functions
void havocbot_goalrating_controlpoints (float ratingscale, vector org, float sradius)
Macro Definition Documentation
#define ROLES_H
Definition at line 2 of file roles.qh.
Function Documentation
void havocbot_goalrating_controlpoints (float ratingscale, vector org, float sradius)
Definition at line 132 of file roles.qc.
References classname, entity(), navigation_routerating(), SELFPARAM, and vlen().
 {SELFPARAM();
     entity head;
     head = findchain(classname, "dom_controlpoint");
     while (head)
     {
         if (vlen(( ( head.absmin + head.absmax ) * 0.5 ) - org) < sradius)
         {
             if(head.cnt > -1) // this is just being fought for
                 navigation_routerating(head, ratingscale, 5000);
             else if(head.goalentity.cnt == 0) // unclaimed point
                 navigation_routerating(head, ratingscale * 0.5, 5000);
             else if(head.goalentity.team != self.team) // other team's point
                 navigation_routerating(head, ratingscale * 0.2, 5000);
         }
         head = head.chain;
     }
 }