Xonotic: common/gamemodes/gamemode/lms/sv_lms.qh File Reference
sv_lms.qh File Reference
#include <common/mutators/base.qh>
#include <common/scores.qh>
Macros
#define autocvar_g_lms_lives_override cvar("g_lms_lives_override")
Functions
void lms_Initialize ()
int LMS_NewPlayerLives ()
REGISTER_MUTATOR (lms, false)
Variables
string autocvar_g_lms_weaponarena = "most_available"
int lms_lowest_lives
int lms_spectate_warning
Macro Definition Documentation
#define autocvar_g_lms_lives_override cvar("g_lms_lives_override")
Definition at line 11 of file sv_lms.qh.
Referenced by REGISTER_MUTATOR().
Function Documentation
void lms_Initialize ()
Definition at line 447 of file sv_lms.qc.
References lms_lowest_lives.
Referenced by REGISTER_MUTATOR().
 {
     lms_lowest_lives = 999;
 }
int LMS_NewPlayerLives ()
Definition at line 13 of file sv_lms.qc.
References autocvar_fraglimit, autocvar_g_lms_join_anytime, autocvar_g_lms_last_join, bound(), ClearWinners(), floor(), lms_lowest_lives, and max().
Referenced by MUTATOR_HOOKFUNCTION(), and WinningCondition_LMS().
 {
     int fl = floor(autocvar_fraglimit);
     if(fl == 0 || fl > 999)
         fl = 999;
     // first player has left the game for dying too much? Nobody else can get in.
     if(lms_lowest_lives < 1)
         return 0;
     if(!autocvar_g_lms_join_anytime)
         if(lms_lowest_lives < fl - max(0, floor(autocvar_g_lms_last_join)))
             return 0;
     return bound(1, lms_lowest_lives, fl);
 }
REGISTER_MUTATOR (lms , false)
Definition at line 16 of file sv_lms.qh.
References autocvar_g_lms_lives_override, GameRules_limit_lead(), GameRules_limit_score(), GameRules_score_enabled(), GameRules_scoring, lms_Initialize(), MUTATOR_ONADD, MUTATOR_STATIC, SFL_ALLOW_HIDE, SFL_LOWER_IS_BETTER, SFL_RANK, SFL_SORT_PRIO_PRIMARY, and SFL_SORT_PRIO_SECONDARY.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_limit_score(((!autocvar_g_lms_lives_override) ? -1 : autocvar_g_lms_lives_override));
         GameRules_limit_lead(0);
         GameRules_score_enabled(false);
         GameRules_scoring(0, 0, 0, {
             field(SP_LMS_LIVES, "lives", SFL_SORT_PRIO_SECONDARY);
             field(SP_LMS_RANK, "rank", SFL_LOWER_IS_BETTER | SFL_RANK | SFL_SORT_PRIO_PRIMARY | SFL_ALLOW_HIDE);
         });
         lms_Initialize();
     }
     return 0;
 }
Variable Documentation
string autocvar_g_lms_weaponarena = "most_available"
Definition at line 12 of file sv_lms.qh.
Referenced by MUTATOR_HOOKFUNCTION().
int lms_lowest_lives
Definition at line 35 of file sv_lms.qh.
Referenced by lms_Initialize(), LMS_NewPlayerLives(), and MUTATOR_HOOKFUNCTION().
int lms_spectate_warning
Definition at line 9 of file sv_lms.qh.