Xonotic: client/commands/cl_cmd.qc File Reference
cl_cmd.qc File Reference
#include "cl_cmd.qh"
#include <common/command/_mod.qh>
#include "../autocvars.qh"
#include "../defs.qh"
#include <client/hud/_mod.qh>
#include "../main.qh"
#include "../mapvoting.qh"
#include "../miscfunctions.qh"
#include "../mutators/events.qh"
#include <common/mapinfo.qh>
Macros
#define CONSOLE_COMMAND(name, execution) { registercommand(name); }
#define CONSOLE_COMMAND(name, execution) registercommand(name);
#define CONSOLE_COMMAND(name, execution) { if (name == s) { { execution } return true; } }
#define CONSOLE_COMMAND(name, execution) { if (name == s) { { execution } return true; } }
#define CONSOLE_COMMANDS_MOVEMENT()
#define CONSOLE_COMMANDS_NORMAL()
Functions
CLIENT_COMMAND (blurtest,"Feature for testing blur postprocessing")
CLIENT_COMMAND (boxparticles,"Spawn particles manually")
CLIENT_COMMAND (create_scrshot_ent,"Create an entity at this location for automatic screenshots")
CLIENT_COMMAND (debugmodel,"Spawn a debug model manually")
CLIENT_COMMAND (handlevote,"System to handle selecting a vote or option")
CLIENT_COMMAND (hud,"Commands regarding/controlling the HUD system")
CLIENT_COMMAND (localprint,"Create your own centerprint sent to yourself")
CLIENT_COMMAND (mv_download,"Retrieve mapshot picture from the server")
CLIENT_COMMAND (sendcvar,"Send a cvar to the server (like weaponpriority)")
void ConsoleCommand_macro_init ()
bool ConsoleCommand_macro_movement (string s, int argc)
bool ConsoleCommand_macro_normal (string s, int argc)
bool CSQC_ConsoleCommand (string command)
void DrawDebugModel (entity this)
void GameCommand (string command)
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
bool HUD_MinigameMenu_IsOpened ()
void HUD_MinigameMenu_Open ()
void HUD_Radar_Show_Maximized (bool doshow, bool clickable)
void LocalCommand_blurtest (int request)
void LocalCommand_boxparticles (int request, int argc)
void LocalCommand_create_scrshot_ent (int request)
void LocalCommand_debugmodel (int request, int argc)
void LocalCommand_handlevote (int request, int argc)
void LocalCommand_hud (int request, int argc)
void LocalCommand_localprint (int request, int argc)
bool LocalCommand_macro_command (int argc, string command)
void LocalCommand_macro_help ()
bool LocalCommand_macro_usage (int argc)
void LocalCommand_macro_write_aliases (int fh)
void LocalCommand_mv_download (int request, int argc)
void LocalCommand_sendcvar (int request, int argc)
void QuickMenu_Close ()
bool QuickMenu_IsOpened ()
bool QuickMenu_Open (string mode, string submenu, string file)
Macro Definition Documentation
#define CONSOLE_COMMAND (name, execution) { registercommand(name); }
#define CONSOLE_COMMAND (name, execution) registercommand(name);
#define CONSOLE_COMMAND (name, execution) { if (name == s) { { execution } return true; } }
#define CONSOLE_COMMAND (name, execution) { if (name == s) { { execution } return true; } }
#define CONSOLE_COMMANDS_MOVEMENT ()
Value:
CONSOLE_COMMAND("+forward", { ++camera_direction.x; }) \
    CONSOLE_COMMAND("-forward", { --camera_direction.x; }) \
    CONSOLE_COMMAND("+back", { --camera_direction.x; }) \
    CONSOLE_COMMAND("-back", { ++camera_direction.x; }) \
    CONSOLE_COMMAND("+moveup", { ++camera_direction.z; }) \
    CONSOLE_COMMAND("-moveup", { --camera_direction.z; }) \
    CONSOLE_COMMAND("+movedown", { --camera_direction.z; }) \
    CONSOLE_COMMAND("-movedown", { ++camera_direction.z; }) \
    CONSOLE_COMMAND("+moveright", { --camera_direction.y; }) \
    CONSOLE_COMMAND("-moveright", { ++camera_direction.y; }) \
    CONSOLE_COMMAND("+moveleft", { ++camera_direction.y; }) \
    CONSOLE_COMMAND("-moveleft", { --camera_direction.y; }) \
    CONSOLE_COMMAND("+roll_right", { ++camera_roll; }) \
    CONSOLE_COMMAND("-roll_right", { --camera_roll; }) \
    CONSOLE_COMMAND("+roll_left", { --camera_roll; }) \
    CONSOLE_COMMAND("-roll_left", { ++camera_roll; }) \
    /* nothing */
Definition at line 578 of file cl_cmd.qc.
Referenced by ConsoleCommand_macro_init(), and ConsoleCommand_macro_movement().
#define CONSOLE_COMMANDS_NORMAL ()
Value:
CONSOLE_COMMAND("+showscores", { scoreboard_showscores = true; }) \
    CONSOLE_COMMAND("-showscores", { scoreboard_showscores = false; }) \
    CONSOLE_COMMAND("+showaccuracy", { scoreboard_showaccuracy = true; }) \
    CONSOLE_COMMAND("-showaccuracy", { scoreboard_showaccuracy = false; }) \
    /* nothing */
Definition at line 571 of file cl_cmd.qc.
Referenced by ConsoleCommand_macro_init(), and ConsoleCommand_macro_normal().
Function Documentation
CLIENT_COMMAND (blurtest , "Feature for testing blur postprocessing")
Definition at line 475 of file cl_cmd.qc.
References LocalCommand_blurtest().
 { LocalCommand_blurtest(request); }
CLIENT_COMMAND (boxparticles , "Spawn particles manually")
Definition at line 476 of file cl_cmd.qc.
References LocalCommand_boxparticles().
 { LocalCommand_boxparticles(request, arguments); }
CLIENT_COMMAND (create_scrshot_ent , "Create an entity at this location for automatic screenshots")
Definition at line 477 of file cl_cmd.qc.
References LocalCommand_create_scrshot_ent().
 { LocalCommand_create_scrshot_ent(request); }
CLIENT_COMMAND (debugmodel , "Spawn a debug model manually")
Definition at line 478 of file cl_cmd.qc.
References LocalCommand_debugmodel().
 { LocalCommand_debugmodel(request, arguments); }
CLIENT_COMMAND (handlevote , "System to handle selecting a vote or option")
Definition at line 479 of file cl_cmd.qc.
References LocalCommand_handlevote().
 { LocalCommand_handlevote(request, arguments); }
CLIENT_COMMAND (hud , "Commands regarding/controlling the HUD system")
Definition at line 480 of file cl_cmd.qc.
References LocalCommand_hud().
 { LocalCommand_hud(request, arguments); }
CLIENT_COMMAND (localprint , "Create your own centerprint sent to yourself")
Definition at line 481 of file cl_cmd.qc.
References LocalCommand_localprint().
 { LocalCommand_localprint(request, arguments); }
CLIENT_COMMAND (mv_download , "Retrieve mapshot picture from the server")
Definition at line 482 of file cl_cmd.qc.
References LocalCommand_mv_download().
 { LocalCommand_mv_download(request, arguments); }
CLIENT_COMMAND (sendcvar , "Send a cvar to the server (like weaponpriority)")
Definition at line 483 of file cl_cmd.qc.
References LocalCommand_sendcvar().
 { LocalCommand_sendcvar(request, arguments); }
void ConsoleCommand_macro_init ()
Definition at line 597 of file cl_cmd.qc.
References CONSOLE_COMMANDS_MOVEMENT, CONSOLE_COMMANDS_NORMAL, and isdemo().
Referenced by CSQC_Init().
 {
     // first init normal commands
     #define CONSOLE_COMMAND(name, execution) \
         { registercommand(name); }
     CONSOLE_COMMANDS_NORMAL();
     #undef CONSOLE_COMMAND
     // then init movement commands
     #ifndef CAMERATEST
     if (isdemo())
     {
     #endif
     #define CONSOLE_COMMAND(name, execution) \
         registercommand(name);
     CONSOLE_COMMANDS_MOVEMENT();
         #undef CONSOLE_COMMAND
     #ifndef CAMERATEST
 }
     #endif
 }
bool ConsoleCommand_macro_movement (string s, int argc)
Definition at line 632 of file cl_cmd.qc.
References camera_active, and CONSOLE_COMMANDS_MOVEMENT.
Referenced by CSQC_ConsoleCommand().
 {
     if (camera_active)
     {
         #define CONSOLE_COMMAND(name, execution) \
             { if (name == s) { { execution } return true; } }
         CONSOLE_COMMANDS_MOVEMENT();
         #undef CONSOLE_COMMAND
     }
     return false;
 }
bool ConsoleCommand_macro_normal (string s, int argc)
Definition at line 621 of file cl_cmd.qc.
References CONSOLE_COMMANDS_NORMAL.
Referenced by CSQC_ConsoleCommand().
 {
     #define CONSOLE_COMMAND(name, execution) \
         { if (name == s) { { execution } return true; } }
     CONSOLE_COMMANDS_NORMAL();
     #undef CONSOLE_COMMAND
     return false;
 }
bool CSQC_ConsoleCommand (string command)
Definition at line 652 of file cl_cmd.qc.
References argv(), ConsoleCommand_macro_movement(), ConsoleCommand_macro_normal(), and tokenize_console.
Referenced by GameCommand().
 {
     int argc = tokenize_console(command);
     string s = strtolower(argv(0));
     // Return value should be true if CSQC handled the command, otherwise return false to have the engine handle it.
     return ConsoleCommand_macro_normal(s, argc)
            || ConsoleCommand_macro_movement(s, argc)
     ;
 }
void DrawDebugModel (entity this)
Definition at line 21 of file cl_cmd.qc.
References drawmask, floor(), MASK_NORMAL, PolyDrawModel(), renderflags, and time.
Referenced by LocalCommand_debugmodel().
 {
     if (time - floor(time) > 0.5)
     {
         PolyDrawModel(this);
         this.drawmask = 0;
     }
     else
     {
         this.renderflags = 0;
         this.drawmask = MASK_NORMAL;
     }
 }
void GameCommand (string command)
Definition at line 521 of file cl_cmd.qc.
 {
     int argc = tokenize_console(command);
     // Guide for working with argc arguments by example:
     // argc:   1    - 2      - 3     - 4
     // argv:   0    - 1      - 2     - 3
     // cmd     vote - master - login - password
     string s = strtolower(argv(0));
     if (s == "help")
     {
         if (argc == 1)
         {
             LOG_INFO("\nClient console commands:\n");
             LocalCommand_macro_help();
             LOG_INFO("\nGeneric commands shared by all programs:\n");
             GenericCommand_macro_help();
             LOG_INFO("\nUsage:^3 cl_cmd COMMAND...^7, where possible commands are listed above.\n");
             LOG_INFO("For help about a specific command, type cl_cmd help COMMAND\n");
             return;
         }
         else if (GenericCommand_macro_usage(argc))  // Instead of trying to call a command, we're going to see detailed information about it
         {
             return;
         }
         else if (LocalCommand_macro_usage(argc))  // now try for normal commands too
         {
             return;
         }
     }
     // continue as usual and scan for normal commands
     if (GenericCommand(command)                                    // handled by common/command/generic.qc
         || LocalCommand_macro_command(argc, command)               // handled by one of the above LocalCommand_* functions
         || MUTATOR_CALLHOOK(CSQC_ConsoleCommand, s, argc, command) // handled by a mutator
        ) return;
     // nothing above caught the command, must be invalid
     LOG_INFO(((command != "") ? strcat("Unknown client command \"", command, "\"") : "No command provided"), ". For a list of supported commands, try cl_cmd help.\n");
 }
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
Definition at line 346 of file cl_minigames_hud.qc.
Referenced by deactivate_minigame(), MUTATOR_HOOKFUNCTION(), and Shutdown().
 {
     if ( HUD_MinigameMenu_IsOpened() )
     {
         entity e, p;
         for ( e = HUD_MinigameMenu_entries; e != NULL; e = p )
         {
             p = e.list_next;
             delete(e);
         }
         HUD_MinigameMenu_entries = NULL;
         HUD_MinigameMenu_last_entry = NULL;
         HUD_MinigameMenu_activeitem = NULL;
         if(autocvar_hud_cursormode)
         if ( !autocvar__hud_configure )
             setcursormode(0);
     }
 }
bool HUD_MinigameMenu_IsOpened ()
Definition at line 340 of file cl_minigames_hud.qc.
Referenced by activate_minigame(), CSQC_UpdateView(), HUD_Crosshair(), HUD_Panel_Draw(), minigame_prompt(), and MUTATOR_HOOKFUNCTION().
 {
     return HUD_MinigameMenu_entries != NULL;
 }
void HUD_MinigameMenu_Open ()
Definition at line 410 of file cl_minigames_hud.qc.
References autocvar_hud_cursormode, hud_fontsize, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, HUD_MinigameMenu_SpawnEntry(), and NULL.
Referenced by activate_minigame(), and MUTATOR_HOOKFUNCTION().
 {
     if ( !HUD_MinigameMenu_IsOpened() )
     {
         HUD_MinigameMenu_InsertEntry( HUD_MinigameMenu_SpawnEntry(
             _("Create"), '0 0 0', hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickCreate),
             HUD_MinigameMenu_last_entry );
         HUD_MinigameMenu_InsertEntry ( HUD_MinigameMenu_SpawnEntry(
             _("Join"),'0 0 0',hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickJoin),
             HUD_MinigameMenu_last_entry );
         HUD_MinigameMenu_CurrentButton();
         HUD_MinigameMenu_activeitem = NULL;
         if(autocvar_hud_cursormode)
             setcursormode(1);
     }
 }
void HUD_Radar_Show_Maximized (bool doshow, bool clickable)
Definition at line 16 of file radar.qc.
References autocvar_hud_cursormode, hud_panel_radar_maximized, hud_panel_radar_mouse, hud_panel_radar_temp_hidden, localcmd, mouseClicked, mv_active, and TC.
Referenced by HUD_Radar_Hide_Maximized(), and LocalCommand_hud().
 {
     TC(bool, doshow);
     hud_panel_radar_maximized = doshow;
     hud_panel_radar_temp_hidden = 0;
     if ( doshow )
     {
         if (clickable)
         {
             if(autocvar_hud_cursormode)
                 setcursormode(1);
             hud_panel_radar_mouse = 1;
             // we must unset the player's buttons, as they aren't released elsewhere
             localcmd("-fire\n");
             localcmd("-fire2\n");
             localcmd("-use\n");
             localcmd("-hook\n");
             localcmd("-jump\n");
         }
     }
     else if ( hud_panel_radar_mouse )
     {
         hud_panel_radar_mouse = 0;
         mouseClicked = 0;
         if(autocvar_hud_cursormode)
         if(!mv_active)
             setcursormode(0);
     }
 }
void LocalCommand_blurtest (int request)
Definition at line 40 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_INFO, stof(), TC, and time.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request);
     // Simple command to work with postprocessing temporarily... possibly completely pointless, the glsl shader is used for a real feature now...
     // Anyway, to enable it, just compile the client with -DBLURTEST and then you can use the command.
     #ifdef BLURTEST
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             blurtest_time0 = time;
             blurtest_time1 = time + stof(argv(1));
             blurtest_radius = stof(argv(2));
             blurtest_power = stof(argv(3));
             LOG_INFO("Enabled blurtest\n");
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd blurtest\n");
             LOG_INFO("  No arguments required.\n");
             return;
         }
     }
     #else
     if (request)
     {
         LOG_INFO("Blurtest is not enabled on this client.\n");
         return;
     }
     #endif
 }
void LocalCommand_boxparticles (int request, int argc)
Definition at line 76 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, entity(), entnum, findfloat(), flags, LOG_INFO, NULL, stoi, stov(), TC, and vector().
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argc == 9)
             {
                 int effect = _particleeffectnum(argv(1));
                 if (effect >= 0)
                 {
                     int index = stoi(argv(2));
                     entity own;
                     if (index <= 0)
                         own = entitybyindex(-index);
                     else
                         own = findfloat(NULL, entnum, index);
                     vector org_from = stov(argv(3));
                     vector org_to = stov(argv(4));
                     vector dir_from = stov(argv(5));
                     vector dir_to = stov(argv(6));
                     int countmultiplier = stoi(argv(7));
                     int flags = stoi(argv(8));
                     boxparticles(effect, own, org_from, org_to, dir_from, dir_to, countmultiplier, flags);
                     return;
                 }
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2boxparticles^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 lv_cmd boxparticles effectname own org_from org_to, dir_from, dir_to, countmultiplier, flags\n");
             LOG_INFO("  'effectname' is the name of a particle effect in effectinfo.txt\n");
             LOG_INFO("  'own' is the entity number of the owner (negative for csqc ent, positive for svqc ent)\n");
             LOG_INFO("  'org_from' is the starting origin of the box\n");
             LOG_INFO("  'org_to' is the ending origin of the box\n");
             LOG_INFO("  'dir_from' is the minimum velocity\n");
             LOG_INFO("  'dir_to' is the maximum velocity\n");
             LOG_INFO("  'countmultiplier' defines a multiplier for the particle count (affects count only, not countabsolute or trailspacing)\n");
             LOG_INFO("  'flags' can contain:\n");
             LOG_INFO("    1 to respect globals particles_alphamin, particles_alphamax (set right before via prvm_globalset client)\n");
             LOG_INFO("    2 to respect globals particles_colormin, particles_colormax (set right before via prvm_globalset client)\n");
             LOG_INFO("    4 to respect globals particles_fade (set right before via prvm_globalset client)\n");
             LOG_INFO("    128 to draw a trail, not a box\n");
             return;
         }
     }
 }
void LocalCommand_create_scrshot_ent (int request)
Definition at line 130 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, fclose(), FILE_APPEND, fopen(), fputs(), ftos(), LOG_INFO, MapInfo_Map_bspname, strcat(), TC, view_angles, and view_origin.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             string path = ((argv(1) == "") ? "" : strcat(argv(1), "/"));
             string filename = strcat(path, MapInfo_Map_bspname, "_scrshot_ent.txt");
             int fh = fopen(filename, FILE_APPEND);
             if (fh >= 0)
             {
                 fputs(fh, "{\n");
                 fputs(fh, strcat("\"classname\" \"info_autoscreenshot\"\n"));
                 fputs(fh, strcat("\"origin\" \"", strcat(ftos(view_origin.x), " ", ftos(view_origin.y), " ", ftos(view_origin.z)), "\"\n"));
                 fputs(fh, strcat("\"angles\" \"", strcat(ftos(view_angles.x), " ", ftos(view_angles.y), " ", ftos(view_angles.z)), "\"\n"));
                 fputs(fh, "}\n");
                 LOG_INFO("Completed screenshot entity dump in ^2data/data/", path, MapInfo_Map_bspname, "_scrshot_ent.txt^7.\n");
                 fclose(fh);
             }
             else
             {
                 LOG_INFO("^1Error: ^7Could not dump to file!\n");
             }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd create_scrshot_ent [path]\n");
             LOG_INFO("  Where 'path' can be the subdirectory of data/data in which the file is saved.\n");
             return;
         }
     }
 }
void LocalCommand_debugmodel (int request, int argc)
Definition at line 170 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, DrawDebugModel(), entity(), g_drawables, IL_PUSH(), LOG_INFO, setorigin(), TC, view_angles, and view_origin.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             string modelname = argv(1);
             entity debugmodel_entity = new(debugmodel);
             precache_model(modelname);
             _setmodel(debugmodel_entity, modelname);
             setorigin(debugmodel_entity, view_origin);
             debugmodel_entity.angles = view_angles;
             debugmodel_entity.draw = DrawDebugModel;
             IL_PUSH(g_drawables, debugmodel_entity);
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd debugmodel model\n");
             LOG_INFO("  Where 'model' is a string of the model name to use for the debug model.\n");
             return;
         }
     }
 }
void LocalCommand_handlevote (int request, int argc)
Definition at line 200 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, ftos(), InterpretBoolean(), localcmd, LOG_INFO, strcat(), TC, uid2name_dialog, vote_active, vote_change, vote_prev, and vote_selection.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             int vote_selection;
             string vote_string;
             if (InterpretBoolean(argv(1)))
             {
                 vote_selection = 2;
                 vote_string = "yes";
             }
             else
             {
                 vote_selection = 1;
                 vote_string = "no";
             }
             if (vote_selection)
             {
                 if (uid2name_dialog)  // handled by "uid2name" option
                 {
                     vote_active = 0;
                     vote_prev = 0;
                     vote_change = -9999;
                     localcmd(strcat("setreport cl_allow_uid2name ", ftos(vote_selection - 1), "\n"));
                     uid2name_dialog = 0;
                 }
                 else { localcmd(strcat("cmd vote ", vote_string, "\n")); }
                 return;
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2handlevote^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd handlevote vote\n");
             LOG_INFO("  Where 'vote' is the selection for either the current poll or uid2name.\n");
             return;
         }
     }
 }
void LocalCommand_hud (int request, int argc)
Definition at line 260 of file cl_cmd.qc.
References argv(), autocvar__hud_configure, autocvar_hud_panel_quickmenu_file, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, Cmd_Scoreboard_Help(), Cmd_Scoreboard_SetFields(), cvar_set(), ftos(), HUD_Panel_ExportCfg(), hud_panel_radar_maximized, hud_panel_radar_mouse, HUD_Radar_Show_Maximized(), InterpretBoolean(), LOG_INFO, MUTATOR_CALLHOOK, QuickMenu_Close(), QuickMenu_IsOpened(), QuickMenu_Open(), and TC.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if(MUTATOR_CALLHOOK(HUD_Command, argc))
                 return;
             switch (argv(1))
             {
                 case "configure":
                 {
                     cvar_set("_hud_configure", ftos(!autocvar__hud_configure));
                     return;
                 }
                 case "quickmenu":
                 {
                     if (argv(2) == "help")
                     {
                         LOG_INFO(" quickmenu [[default | file | \"\"] submenu file]\n");
                         LOG_INFO("Called without options (or with \"\") loads either the default quickmenu or a quickmenu file if hud_panel_quickmenu_file is set to a valid filename.\n");
                         LOG_INFO("A submenu name can be given to open the quickmenu directly in a submenu; it requires to specify 'default', 'file' or '\"\"' option.\n");
                         LOG_INFO("A file name can also be given to open a different quickmenu\n");
                         return;
                     }
                     string file = ((argv(4) == "") ? autocvar_hud_panel_quickmenu_file : argv(4));
                     if (QuickMenu_IsOpened())
                         QuickMenu_Close();
                     else
                         QuickMenu_Open(argv(2), argv(3), file);  // mode, submenu
                     return;
                 }
                 case "save":
                 {
                     if (argv(2))
                     {
                         HUD_Panel_ExportCfg(argv(2));
                         return;
                     }
                     else
                     {
                         break;  // go to usage, we're missing the paramater needed here.
                     }
                 }
                 case "scoreboard_columns_set":
                 {
                     Cmd_Scoreboard_SetFields(argc);
                     return;
                 }
                 case "scoreboard_columns_help":
                 {
                     Cmd_Scoreboard_Help();
                     return;
                 }
                 case "radar":
                 {
                     if (argv(2))
                         HUD_Radar_Show_Maximized(InterpretBoolean(argv(2)), 0);
                     else
                         HUD_Radar_Show_Maximized(!hud_panel_radar_maximized, 0);
                     return;
                 }
                 case "clickradar":
                 {
                     HUD_Radar_Show_Maximized(!hud_panel_radar_mouse, 1);
                     return;
                 }
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2hud^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd hud action [configname | radartoggle | layout]\n");
             LOG_INFO("  Where 'action' is the command to complete,\n");
             LOG_INFO("  'configname' is the name to save to for \"save\" action,\n");
             LOG_INFO("  'radartoggle' is to control hud_panel_radar_maximized for \"radar\" action,\n");
             LOG_INFO("  and 'layout' is how to organize the scoreboard columns for the set action.\n");
             LOG_INFO("  Full list of commands here: \"configure, quickmenu, minigame, save, scoreboard_columns_help, scoreboard_columns_set, radar.\"\n");
             return;
         }
     }
 }
void LocalCommand_localprint (int request, int argc)
Definition at line 355 of file cl_cmd.qc.
References argv(), centerprint_hud(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_INFO, and TC.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argv(1))
             {
                 centerprint_hud(argv(1));
                 return;
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2localprint^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd localprint \"message\"\n");
             LOG_INFO("  'message' is the centerprint message to send to yourself.\n");
             return;
         }
     }
 }
bool LocalCommand_macro_command (int argc, string command)
Definition at line 490 of file cl_cmd.qc.
References argv(), CLIENT_COMMANDS, CMD_REQUEST_COMMAND, FOREACH, and NULL.
Referenced by GameCommand().
 {
     string c = strtolower(argv(0));
     FOREACH(CLIENT_COMMANDS, it.m_name == c, {
         it.m_invokecmd(it, CMD_REQUEST_COMMAND, NULL, argc, command);
         return true;
     });
     return false;
 }
void LocalCommand_macro_help ()
Definition at line 485 of file cl_cmd.qc.
References CLIENT_COMMANDS, FOREACH, and LOG_INFOF.
Referenced by GameCommand().
 {
     FOREACH(CLIENT_COMMANDS, true, LOG_INFOF("  ^2%s^7: %s\n", it.m_name, it.m_description));
 }
bool LocalCommand_macro_usage (int argc)
Definition at line 500 of file cl_cmd.qc.
References argv(), CLIENT_COMMANDS, CMD_REQUEST_USAGE, FOREACH, and NULL.
Referenced by GameCommand().
 {
     string c = strtolower(argv(1));
     FOREACH(CLIENT_COMMANDS, it.m_name == c, {
         it.m_invokecmd(it, CMD_REQUEST_USAGE, NULL, argc, "");
         return true;
     });
     return false;
 }
void LocalCommand_macro_write_aliases (int fh)
Definition at line 510 of file cl_cmd.qc.
References CLIENT_COMMANDS, CMD_Write_Alias, and FOREACH.
Referenced by GENERIC_COMMAND().
 {
     FOREACH(CLIENT_COMMANDS, true, CMD_Write_Alias("qc_cmd_cl", it.m_name, it.m_description));
 }
void LocalCommand_mv_download (int request, int argc)
Definition at line 382 of file cl_cmd.qc.
References argv(), Cmd_MapVote_MapDownload(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_INFO, and TC.
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argv(1))
             {
                 Cmd_MapVote_MapDownload(argc);
                 return;
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2mv_download^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd mv_download mapid\n");
             LOG_INFO("  Where 'mapid' is the id number of the map to request an image of on the map vote selection menu.\n");
             return;
         }
     }
 }
void LocalCommand_sendcvar (int request, int argc)
Definition at line 409 of file cl_cmd.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, cvar_string(), localcmd, LOG_INFO, strlen(), strunzone(), strzone(), substring(), TC, W_FixWeaponOrder(), and W_NumberWeaponOrder().
Referenced by CLIENT_COMMAND().
 {
     TC(int, request); TC(int, argc);
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argv(1))
             {
                 // W_FixWeaponOrder will trash argv, so save what we need.
                 string thiscvar = strzone(argv(1));
                 string s = cvar_string(thiscvar);
                 if (thiscvar == "cl_weaponpriority")
                     s = W_FixWeaponOrder(W_NumberWeaponOrder(s), 1);
                 else if (substring(thiscvar, 0, 17) == "cl_weaponpriority" && strlen(thiscvar) == 18)
                     s = W_FixWeaponOrder(W_NumberWeaponOrder(s), 0);
                 localcmd("cmd sentcvar ", thiscvar, " \"", s, "\"\n");
                 strunzone(thiscvar);
                 return;
             }
         }
         default:
         {
             LOG_INFO("Incorrect parameters for ^2sendcvar^7\n");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd sendcvar <cvar>\n");
             LOG_INFO("  Where 'cvar' is the cvar plus arguments to send to the server.\n");
             return;
         }
     }
 }
void QuickMenu_Close ()
Definition at line 195 of file quickmenu.qc.
References autocvar_hud_cursormode, hud_panel_quickmenu, mouseClicked, mv_active, prevMouseClicked, QuickMenu_Buffer_Close(), QuickMenu_CurrentSubMenu, QUICKMENU_MAXLINES, QuickMenu_Page_ClearEntry(), QuickMenu_Page_Entries, string_null, and strunzone().
Referenced by HUD_QuickMenu(), LocalCommand_hud(), QuickMenu_InputEvent(), QuickMenu_Mouse(), and QuickMenu_Page_Load().
 {
     if (QuickMenu_CurrentSubMenu)
         strunzone(QuickMenu_CurrentSubMenu);
     QuickMenu_CurrentSubMenu = string_null;
     int i;
     for (i = 0; i < QUICKMENU_MAXLINES; ++i)
         QuickMenu_Page_ClearEntry(i);
     QuickMenu_Page_Entries = 0;
     hud_panel_quickmenu = 0;
     mouseClicked = 0;
     prevMouseClicked = 0;
     QuickMenu_Buffer_Close();
     if(autocvar_hud_cursormode)
     if(!mv_active)
         setcursormode(0);
 }
bool QuickMenu_IsOpened ()
Definition at line 231 of file quickmenu.qc.
Referenced by CSQC_UpdateView(), LocalCommand_hud(), and Scoreboard_WouldDraw().
 {
     return (QuickMenu_Page_Entries > 0);
 }
bool QuickMenu_Open (string mode, string submenu, string file)
Definition at line 67 of file quickmenu.qc.
References argv(), autocvar_hud_cursormode, autocvar_hud_panel_quickmenu_time, buf_create, fclose(), fgets(), FILE_READ, fopen(), ftos(), hud_panel_quickmenu, hudShiftState, LOG_INFO, LOG_INFOF, LOG_WARNF, QM_TAG_COMMAND, QM_TAG_PLCOMMAND, QM_TAG_SUBMENU, QM_TAG_TITLE, QuickMenu_Buffer, QUICKMENU_BUFFER_MAXENTRIES, QuickMenu_Buffer_Set, QuickMenu_Buffer_Size, QuickMenu_Default(), QuickMenu_Page_Load(), QuickMenu_TimeOut, strcat(), time, and tokenize_console.
Referenced by LocalCommand_hud().
 {
     int fh = -1;
     string s;
     if(mode == "")
     {
         if(file == "" || file == "0")
             mode = "default";
         else
             mode = "file";
     }
     if(mode == "file")
     {
         if(file == "" || file == "0")
             LOG_INFO("No file name is set in hud_panel_quickmenu_file, loading default quickmenu\n");
         else
         {
             fh = fopen(file, FILE_READ);
             if(fh < 0)
                 LOG_INFOF("Couldn't open file \"%s\", loading default quickmenu\n", file);
         }
         if(fh < 0)
             mode = "default";
     }
     if(mode == "default")
     {
         QuickMenu_Buffer = buf_create();
         if(QuickMenu_Buffer < 0)
             return false;
         QuickMenu_Default(submenu);
     }
     else if(mode == "file")
     {
         QuickMenu_Buffer = buf_create();
         if(QuickMenu_Buffer < 0)
         {
             fclose(fh);
             return false;
         }
         QuickMenu_Buffer_Size = 0;
         while((s = fgets(fh)) && QuickMenu_Buffer_Size < QUICKMENU_BUFFER_MAXENTRIES)
         {
             // first skip invalid entries, so we don't check them anymore
             float argc;
             argc = tokenize_console(s);
             if(argc == 0 || argv(0) == "")
                 continue;
             if(argc == 1)
                 QuickMenu_Buffer_Set(QM_TAG_SUBMENU, argv(0));
             else if(argc == 2)
             {
                 if(argv(1) == "")
                     continue;
                 QuickMenu_Buffer_Set(QM_TAG_TITLE, argv(0));
                 ++QuickMenu_Buffer_Size;
                 QuickMenu_Buffer_Set(QM_TAG_COMMAND, argv(1));
             }
             else if(argc == 3)
             {
                 // check for special keywords
                 float teamplayers = 0, without_me = 0;
                 switch(argv(2))
                 {
                     case "ALLPLAYERS_BUT_ME":       without_me = 1; // fall through
                     case "ALLPLAYERS":              teamplayers = 0; break;
                     case "OWNTEAMPLAYERS_BUT_ME":   without_me = 1; // fall through
                     case "OWNTEAMPLAYERS":          teamplayers = 1; break;
                     case "ENEMYTEAMPLAYERS":        teamplayers = 2; break;
                     default: continue;
                 }
                 if(QuickMenu_Buffer_Size + 3 < QUICKMENU_BUFFER_MAXENTRIES)
                 {
                     QuickMenu_Buffer_Set(QM_TAG_SUBMENU, argv(0));
                     ++QuickMenu_Buffer_Size;
                     QuickMenu_Buffer_Set(QM_TAG_TITLE, strcat(ftos(teamplayers), ftos(without_me))); // put PLCOMMAND arguments in the title string
                     ++QuickMenu_Buffer_Size;
                     QuickMenu_Buffer_Set(QM_TAG_PLCOMMAND, argv(1));
                     ++QuickMenu_Buffer_Size;
                     QuickMenu_Buffer_Set(QM_TAG_SUBMENU, argv(0));
                 }
             }
             ++QuickMenu_Buffer_Size;
         }
         fclose(fh);
     }
     else
     {
         LOG_WARNF("Unrecognized mode %s", mode);
         return false;
     }
     if (QuickMenu_Buffer_Size <= 0)
     {
         buf_del(QuickMenu_Buffer);
         QuickMenu_Buffer = -1;
         return false;
     }
     if(mode == "file")
         QuickMenu_Page_Load(submenu, 0);
     else
         QuickMenu_Page_Load("", 0);
     hud_panel_quickmenu = 1;
     if(autocvar_hud_cursormode)
         setcursormode(1);
     hudShiftState = 0;
     QuickMenu_TimeOut = ((autocvar_hud_panel_quickmenu_time > 0) ? time + autocvar_hud_panel_quickmenu_time : 0);
     return true;
 }