Xonotic: common/mutators/mutator/midair/sv_midair.qc File Reference
sv_midair.qc File Reference
#include "sv_midair.qh"
Functions
MUTATOR_HOOKFUNCTION (midair, Damage_Calculate)
MUTATOR_HOOKFUNCTION (midair, PlayerPowerups)
MUTATOR_HOOKFUNCTION (midair, PlayerSpawn)
MUTATOR_HOOKFUNCTION (midair, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (midair, BuildMutatorsPrettyString)
REGISTER_MUTATOR (midair, expr_evaluate(autocvar_g_midair))
Variables
string autocvar_g_midair
float autocvar_g_midair_shieldtime
float midair_shieldtime
Function Documentation
MUTATOR_HOOKFUNCTION (midair , Damage_Calculate)
Definition at line 10 of file sv_midair.qc.
References entity(), IS_PLAYER, M_ARGV, and time.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     if(IS_PLAYER(frag_attacker))
     if(IS_PLAYER(frag_target))
     if(time < frag_target.midair_shieldtime)
         M_ARGV(4, float) = 0;
 }
MUTATOR_HOOKFUNCTION (midair , PlayerPowerups)
Definition at line 21 of file sv_midair.qc.
References autocvar_g_midair_shieldtime, EF_ADDITIVE, EF_FULLBRIGHT, entity(), IS_ONGROUND, M_ARGV, max(), and time.
 {
     entity player = M_ARGV(0, entity);
     if(time >= game_starttime)
     if(IS_ONGROUND(player))
     {
         player.effects |= (EF_ADDITIVE | EF_FULLBRIGHT);
         player.midair_shieldtime = max(player.midair_shieldtime, time + autocvar_g_midair_shieldtime);
     }
 }
MUTATOR_HOOKFUNCTION (midair , PlayerSpawn)
Definition at line 33 of file sv_midair.qc.
References entity(), IS_BOT_CLIENT, and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(IS_BOT_CLIENT(player))
         player.bot_moveskill = 0; // disable bunnyhopping
 }
MUTATOR_HOOKFUNCTION (midair , BuildMutatorsString)
Definition at line 41 of file sv_midair.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":midair");
 }
MUTATOR_HOOKFUNCTION (midair , BuildMutatorsPrettyString)
Definition at line 46 of file sv_midair.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Midair");
 }
REGISTER_MUTATOR (midair , expr_evaluate(autocvar_g_midair))
Variable Documentation
string autocvar_g_midair
Definition at line 3 of file sv_midair.qc.
float autocvar_g_midair_shieldtime
Definition at line 4 of file sv_midair.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float midair_shieldtime
Definition at line 8 of file sv_midair.qc.