Xonotic: ecs/systems/cl_physics.qc File Reference
cl_physics.qc File Reference
#include "physics.qh"
Functions
void sys_phys_ai (entity this)
void sys_phys_fix (entity this, float dt)
void sys_phys_fixspeed (entity this, float maxspeed_mod)
void sys_phys_monitor (entity this, float dt)
bool sys_phys_override (entity this, float dt)
void sys_phys_pregame_hold (entity this)
void sys_phys_spectator_control (entity this)
Function Documentation
void sys_phys_ai (entity this)
Definition at line 23 of file cl_physics.qc.
Referenced by sys_phys_update().
 {}
void sys_phys_fix (entity this, float dt)
Definition at line 3 of file cl_physics.qc.
Referenced by sys_phys_update().
 {
     this.team = myteam + 1; // is this correct?
     PHYS_WATERJUMP_TIME(this) -= dt;
     this.movement = PHYS_INPUT_MOVEVALUES(this);
     this.items = STAT(ITEMS, this);
     this.spectatorspeed = STAT(SPECTATORSPEED, this);
     if (!(PHYS_INPUT_BUTTON_JUMP(this))) // !jump
         UNSET_JUMP_HELD(this);           // canjump = true
     PM_ClientMovement_UpdateStatus(this);
 }
void sys_phys_fixspeed (entity this, float maxspeed_mod)
Definition at line 29 of file cl_physics.qc.
Referenced by sys_phys_update().
 {}
void sys_phys_monitor (entity this, float dt)
Definition at line 21 of file cl_physics.qc.
Referenced by sys_phys_update().
 {}
bool sys_phys_override (entity this, float dt)
Definition at line 15 of file cl_physics.qc.
Referenced by sys_phys_update().
 {
     // no vehicle prediction
     return hud != HUD_NORMAL;
 }
void sys_phys_pregame_hold (entity this)
Definition at line 25 of file cl_physics.qc.
Referenced by sys_phys_update().
 {}
void sys_phys_spectator_control (entity this)
Definition at line 27 of file cl_physics.qc.
Referenced by sys_phys_update().
 {}