Xonotic: XonoticDamageTextSettings Class Reference
XonoticDamageTextSettings Class Reference
Public Member Functions
XonoticDamageTextSettings ()
virtual void _changeFocusXY ()
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
virtual void addItemSimple ()
ATTRIB (Tab, title, string)
ATTRIB (InputContainer, mouseFocusedChild, entity)
ATTRIB (XonoticTab, backgroundImage, string)
ATTRIB (Tab, backgroundImage, string)
ATTRIB (Item, parent, entity)
ATTRIB (XonoticTab, titleTooltip, string)
ATTRIB (Item, tooltip, string)
ATTRIB (Container, firstChild, entity)
ATTRIB (Container, lastChild, entity)
ATTRIB (Container, focusedChild, entity)
ATTRIB (Container, savedFocus, entity)
ATTRIB (Dialog, closeButton, entity)
ATTRIB (Dialog, backgroundImage, string)
ATTRIB (Dialog, closeButtonImage, string)
ATTRIB (Dialog, frame, entity)
virtual void close ()
virtual void configureDialog ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void fill ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void gotoRC ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
REGISTER_SETTINGS (damagetext, NEW(XonoticDamageTextSettings))
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFirstColumn ()
virtual void setFocus ()
virtual void showNotify ()
virtual void TD ()
virtual void TDempty ()
virtual void TDNoMargin ()
virtual void toString ()
virtual void TR ()
Public Attributes
float allowFocusSound = 0
float borderLines = 1
float closable = 0
vector color = '1 0.5 1'
float columns = 5
float columnSpacing = SKINMARGIN_COLUMNS
float currentColumn = 0
float currentRow = 0
float firstColumn = 0
float focusable = 0
float focused = 0
bool hideMenuOnClose = false
float intendedHeight = 0
float intendedWidth = 0.9
float isTabRoot = 0
vector itemOrigin = '0 0 0'
vector itemSize = '0 0 0'
vector itemSpacing = '0 0 0'
float marginBottom = 0
float marginLeft = 0
float marginRight = 0
float marginTop = 0
vector origin = '0 0 0'
float preferredFocusPriority = 0
float requiresConnection = 0
float rootDialog = 0
float rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL
float rows = 15.5
float rowSpacing = SKINMARGIN_ROWS
float shown = 0
vector size = '0 0 0'
string title = _("Damage text")
float titleFontSize = 0
float titleHeight = 0
float zoomedOutTitleBar = 0
float zoomedOutTitleBarPosition = 0
Detailed Description
Definition at line 6 of file ui_damagetext.qc.
Constructor & Destructor Documentation
XonoticDamageTextSettings::XonoticDamageTextSettings () inline
Definition at line 12 of file ui_damagetext.qc.
 { this.configureDialog(this); }
Member Function Documentation
virtual void InputContainer::_changeFocusXY () virtual inherited
virtual void Container::addItem () virtual inherited
Reimplemented in ModalController, and Nexposee.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
virtual void Dialog::addItemSimple () virtual inherited
Tab::ATTRIB (Tab , title , string) inherited
InputContainer::ATTRIB (InputContainer , mouseFocusedChild , entity) inherited
XonoticTab::ATTRIB (XonoticTab , backgroundImage , string) inherited
Item::ATTRIB (Item , parent , entity) inherited
Tab::ATTRIB (Tab , backgroundImage , string) inherited
XonoticTab::ATTRIB (XonoticTab , titleTooltip , string) inherited
Item::ATTRIB (Item , tooltip , string) inherited
Container::ATTRIB (Container , firstChild , entity) inherited
Container::ATTRIB (Container , lastChild , entity) inherited
Container::ATTRIB (Container , focusedChild , entity) inherited
Container::ATTRIB (Container , savedFocus , entity) inherited
Dialog::ATTRIB (Dialog , closeButton , entity) inherited
Dialog::ATTRIB (Dialog , backgroundImage , string) inherited
Dialog::ATTRIB (Dialog , closeButtonImage , string) inherited
Dialog::ATTRIB (Dialog , frame , entity) inherited
virtual void Dialog::close () virtual inherited
Reimplemented in XonoticRootDialog, XonoticScreenshotViewerDialog, and XonoticMutatorsDialog.
virtual void Dialog::configureDialog () virtual inherited
Reimplemented in XonoticDialog.
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 295 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 309 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Container::draw () virtual inherited
Reimplemented from Item.
Reimplemented in ModalController, MainWindow, XonoticProfileTab, and Nexposee.
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
virtual void XonoticDamageTextSettings::fill () inline virtual
Reimplemented from Dialog.
Definition at line 14 of file ui_damagetext.qc.
References entity(), makeXonoticCheckBox(), makeXonoticColorpickerString(), makeXonoticSlider(), makeXonoticTextLabel(), setDependent(), and setDependentAND().
     {
         entity e;
         this.gotoRC(this, 0, 1); this.setFirstColumn(this, this.currentColumn);
             this.TD(this, 1, 3, makeXonoticCheckBox(0, "cl_damagetext", _("Draw damage numbers")));
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Font size minimum:")));
                 setDependent(e, "cl_damagetext", 1, 1);
             this.TD(this, 1, 2, e = makeXonoticSlider(0, 50, 1, "cl_damagetext_size_min"));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Font size maximum:")));
                 setDependent(e, "cl_damagetext", 1, 1);
             this.TD(this, 1, 2, e = makeXonoticSlider(0, 50, 1, "cl_damagetext_size_max"));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Accumulate range:")));
                 setDependent(e, "cl_damagetext", 1, 1);
             this.TD(this, 1, 2, e = makeXonoticSlider(0, 500, 1, "cl_damagetext_accumulate_range"));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Lifetime:")));
                 setDependent(e, "cl_damagetext", 1, 1);
             this.TD(this, 1, 2, e = makeXonoticSlider(0, 10, 1, "cl_damagetext_alpha_lifetime"));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Color:")));
                 setDependent(e, "cl_damagetext", 1, 1);
             this.TD(this, 2, 2, e = makeXonoticColorpickerString("cl_damagetext_color", "cl_damagetext_color"));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
         this.TR(this);
         // friendly fire
             this.TD(this, 1, 3, e = makeXonoticCheckBox(0, "cl_damagetext_friendlyfire", _("Draw damage numbers for friendly fire")));
                 setDependent(e, "cl_damagetext", 1, 1);
         this.TR(this);
             this.TD(this, 1, 1, e = makeXonoticTextLabel(0, _("Color:")));
                 setDependentAND(e, "cl_damagetext", 1, 1, "cl_damagetext_friendlyfire", 1, 1);
             this.TD(this, 2, 2, e = makeXonoticColorpickerString("cl_damagetext_friendlyfire_color", "cl_damagetext_friendlyfire_color"));
                 setDependentAND(e, "cl_damagetext", 1, 1, "cl_damagetext_friendlyfire", 1, 1);
         this.TR(this);
     }
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void InputContainer::focusLeave () virtual inherited
Reimplemented from Container.
virtual void Dialog::gotoRC () virtual inherited
virtual void Container::hideNotify () virtual inherited
Reimplemented from Item.
virtual void Container::itemFromPoint () virtual inherited
virtual void Dialog::keyDown () virtual inherited
Reimplemented from InputContainer.
Reimplemented in XonoticScreenshotViewerDialog.
virtual void Container::keyUp () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual inherited
virtual void InputContainer::mouseDrag () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseMove () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mousePress () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseRelease () virtual inherited
Reimplemented from Container.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
XonoticDamageTextSettings::REGISTER_SETTINGS (damagetext , NEW(XonoticDamageTextSettings))
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void InputContainer::resizeNotify () virtual inherited
Reimplemented from Container.
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Dialog::setFirstColumn () virtual inherited
virtual void Container::setFocus () virtual inherited
virtual void XonoticDamageTextSettings::showNotify () inline virtual
Reimplemented from XonoticTab.
Definition at line 13 of file ui_damagetext.qc.
References loadAllCvars().
 { loadAllCvars(this); }
virtual void Dialog::TD () virtual inherited
virtual void Dialog::TDempty () virtual inherited
virtual void Dialog::TDNoMargin () virtual inherited
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void Dialog::TR () virtual inherited
Member Data Documentation
float Item::allowFocusSound = 0 inherited
Definition at line 24 of file item.qh.
float Dialog::borderLines = 1 inherited
Definition at line 66 of file dialog.qh.
float Tab::closable = 0 inherited
Definition at line 6 of file tab.qh.
vector Dialog::color = '1 0.5 1' inherited
Definition at line 46 of file dialog.qh.
float XonoticDamageTextSettings::columns = 5
Definition at line 11 of file ui_damagetext.qc.
float XonoticTab::columnSpacing = SKINMARGIN_COLUMNS inherited
Definition at line 17 of file tab.qh.
float Dialog::currentColumn = 0 inherited
Definition at line 40 of file dialog.qh.
float Dialog::currentRow = 0 inherited
Definition at line 39 of file dialog.qh.
float Dialog::firstColumn = 0 inherited
Definition at line 41 of file dialog.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
bool Dialog::hideMenuOnClose = false inherited
Definition at line 69 of file dialog.qh.
float Dialog::intendedHeight = 0 inherited
Definition at line 35 of file dialog.qh.
float XonoticDamageTextSettings::intendedWidth = 0.9
Definition at line 9 of file ui_damagetext.qc.
float Tab::isTabRoot = 0 inherited
Definition at line 5 of file tab.qh.
vector Dialog::itemOrigin = '0 0 0' inherited
Definition at line 36 of file dialog.qh.
vector Dialog::itemSize = '0 0 0' inherited
Definition at line 37 of file dialog.qh.
vector Dialog::itemSpacing = '0 0 0' inherited
Definition at line 38 of file dialog.qh.
float XonoticTab::marginBottom = 0 inherited
Definition at line 14 of file tab.qh.
float XonoticTab::marginLeft = 0 inherited
Definition at line 15 of file tab.qh.
float XonoticTab::marginRight = 0 inherited
Definition at line 16 of file tab.qh.
float XonoticTab::marginTop = 0 inherited
Definition at line 13 of file tab.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Dialog::requiresConnection = 0 inherited
Definition at line 63 of file dialog.qh.
float Tab::rootDialog = 0 inherited
Definition at line 7 of file tab.qh.
float XonoticTab::rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL inherited
Definition at line 19 of file tab.qh.
float XonoticDamageTextSettings::rows = 15.5
Definition at line 10 of file ui_damagetext.qc.
float XonoticTab::rowSpacing = SKINMARGIN_ROWS inherited
Definition at line 18 of file tab.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
string XonoticDamageTextSettings::title = _("Damage text")
Definition at line 8 of file ui_damagetext.qc.
float Tab::titleFontSize = 0 inherited
Definition at line 9 of file tab.qh.
float Tab::titleHeight = 0 inherited
Definition at line 23 of file tab.qh.
float Dialog::zoomedOutTitleBar = 0 inherited
Definition at line 61 of file dialog.qh.
float Dialog::zoomedOutTitleBarPosition = 0 inherited
Definition at line 60 of file dialog.qh.
The documentation for this class was generated from the following file:
common/mutators/mutator/damagetext/ui_damagetext.qc