Xonotic: menu/xonotic/dialog_multiplayer_media_screenshot.qc File Reference
dialog_multiplayer_media_screenshot.qc File Reference
#include "dialog_multiplayer_media_screenshot.qh"
#include "dialog_multiplayer_media_screenshot_viewer.qh"
#include "screenshotlist.qh"
#include "textlabel.qh"
#include "inputbox.qh"
#include "checkbox.qh"
#include "button.qh"
Functions
entity makeXonoticScreenshotBrowserTab ()
void XonoticScreenshotBrowserTab_fill (entity me)
void XonoticScreenshotBrowserTab_loadPreviewScreenshot (entity me, string scrImage)
Function Documentation
entity makeXonoticScreenshotBrowserTab ()
Definition at line 11 of file dialog_multiplayer_media_screenshot.qc.
References entity(), and NEW.
Referenced by XonoticMediaTab_fill().
 {
     entity me;
     me = NEW(XonoticScreenshotBrowserTab);
     me.configureDialog(me);
     return me;
 }
void XonoticScreenshotBrowserTab_fill (entity me)
Definition at line 25 of file dialog_multiplayer_media_screenshot.qc.
References entity(), main, makeXonoticButton(), makeXonoticCheckBoxEx(), makeXonoticInputBox(), makeXonoticScreenshotList(), makeXonoticTextLabel(), ScreenshotList_Filter_Would_Change(), ScreenshotList_Refresh_Click(), StartScreenshot_Click(), and string_null.
 {
     entity e, slist;
     slist = makeXonoticScreenshotList();
     float slist_height = me.rows - 2;
     me.TR(me);
         me.TD(me, 1, 0.6, e = makeXonoticTextLabel(1, _("Filter:")));
         me.TD(me, 1, 2.4, e = makeXonoticInputBox(0, string_null));
             e.onChange = ScreenshotList_Filter_Would_Change;
             e.onChangeEntity = slist;
             slist.screenshotViewerDialog = main.screenshotViewerDialog;
             main.screenshotViewerDialog.scrList = slist;
     me.gotoRC(me, 0, 3.1);
         me.TD(me, 1, 1.9, e = makeXonoticCheckBoxEx(2, 1, "cl_autoscreenshot", _("Auto screenshot scoreboard")));
         me.TD(me, 1, 1, e = makeXonoticButton(_("Refresh"), '0 0 0'));
             e.onClick = ScreenshotList_Refresh_Click;
             e.onClickEntity = slist;
     /*me.TR(me);
         me.TD(me, 1, 0.5, e = makeXonoticTextLabel(0, "Filter:"));
         me.TD(me, 1, me.columns - 1.5, e = makeXonoticInputBox(0, string_null));
             e.onChange = ScreenshotList_Filter_Would_Change;
             e.onChangeEntity = slist;
             slist.screenshotViewerDialog = main.screenshotViewerDialog;
             main.screenshotViewerDialog.scrList = slist;
         me.TD(me, 1, 1, e = makeXonoticButton(_("Refresh"), '0 0 0'));
             e.onClick = ScreenshotList_Refresh_Click;
             e.onClickEntity = slist;*/
     me.gotoRC(me, 1.5, 0);
         me.TD(me, me.rows - 2.5, me.columns, slist);
     me.gotoRC(me, slist_height + 1, 0);
         me.TD(me, 1, me.columns, e = makeXonoticButton(_("Open in the viewer"), '0 0 0'));
             e.onClick = StartScreenshot_Click;
             e.onClickEntity = slist;
 /*
     me.TR(me);
         me.TD(me, me.rows - me.currentRow, me.columns, e = makeXonoticScreenshotImage());
             e.showTitle = 0;
             me.screenshotImage = e;
             slist.screenshotPreview = e;
             slist.screenshotBrowserDialog = me;
 */
 }
void XonoticScreenshotBrowserTab_loadPreviewScreenshot (entity me, string scrImage)
Definition at line 18 of file dialog_multiplayer_media_screenshot.qc.
References strcpy.
 {
     if (me.currentScrPath == scrImage)
         return;
     strcpy(me.currentScrPath, scrImage);
     me.screenshotImage.load(me.screenshotImage, me.currentScrPath);
 }