Xonotic: client/bgmscript.qc File Reference
bgmscript.qc File Reference
#include "bgmscript.qh"
Macros
#define CONSTANT_SPEED_DECAY
Functions
void BGMScript_Init ()
void BGMScript_InitEntity (entity e)
class (BGMScript).float bgmscriptline
float doBGMScript (entity e)
float GetAttackDecaySustainAmplitude (float a, float d, float s, float t)
float GetAttackTime (float a, float amp)
float GetCurrentAmplitude (entity e, float trel)
float GetReleaseAmplitude (float d, float s, float r, float t)
float GetReleaseTime (float d, float s, float r, float amp)
float GetTimeForAmplitude (entity e, float amp)
Variables
float bgmscriptbuf
float bgmscriptbufloaded
float bgmscriptbufsize
Macro Definition Documentation
#define CONSTANT_SPEED_DECAY
Definition at line 3 of file bgmscript.qc.
Function Documentation
void BGMScript_Init ()
Definition at line 94 of file bgmscript.qc.
References bgmscriptbuf, bgmscriptbufloaded, bgmscriptbufsize, buf_create, fclose(), fgets(), FILE_READ, fopen(), and strcat().
Referenced by BGMScript_InitEntity().
 {
     string s;
     float fh;
     bgmscriptbuf = bgmscriptbufsize = 0;
     bgmscriptbufloaded = 1;
     s = strcat("maps/", mi_shortname, ".bgs");
     fh = fopen(s, FILE_READ);
     if(fh < 0)
         return;
     bgmscriptbuf = buf_create();
     while((s = fgets(fh)))
     {
         bufstr_set(bgmscriptbuf, bgmscriptbufsize, s);
         ++bgmscriptbufsize;
     }
     fclose(fh);
 }
void BGMScript_InitEntity (entity e)
Definition at line 113 of file bgmscript.qc.
References BGMScript_Init(), bgmscriptbuf, bgmscriptbufloaded, bgmscriptbufsize, LOG_INFOF, strcat(), string_null, strlen(), strunzone(), and substring().
Referenced by NET_HANDLE().
 {
     float l;
     string m;
     if(e.bgmscript != "")
     {
         if(!bgmscriptbufloaded)
             BGMScript_Init();
         float i;
         m = strcat(e.bgmscript, " ");
         l = strlen(m);
         e.bgmscriptline0 = -1;
         for(i = 0; i < bgmscriptbufsize; ++i)
         {
             if(substring(bufstr_get(bgmscriptbuf, i), 0, l) == m)
                 break;
         }
         e.bgmscriptline = e.bgmscriptline0 = i;
         if(i >= bgmscriptbufsize)
         {
             LOG_INFOF("ERROR: bgmscript does not define %s\n", e.bgmscript);
             strunzone(e.bgmscript);
             e.bgmscript = string_null;
         }
     }
 }
class (BGMScript)
float doBGMScript (entity e)
Definition at line 171 of file bgmscript.qc.
References argv(), autocvar_bgmvolume, bgmscriptbuf, bgmtime, drawframetime, GetCurrentAmplitude(), GetTimeForAmplitude(), stof(), and tokenize_console.
Referenced by Ent_Wall_Draw().
 {
     float amp, vel;
     if(e.bgmscript == "")
         return 1;
     if(autocvar_bgmvolume <= 0)
         return -1;
     e.just_toggled = false;
     if(bgmtime < 0)
         return -1;
     if(bgmtime < e.bgmscripttime)
     {
         amp = GetCurrentAmplitude(e, e.bgmscripttime - e.bgmscriptstatetime + drawframetime);
         e.bgmscriptline = e.bgmscriptline0;
         e.bgmscripttime = bgmtime;
         // treat this as a stop event for all notes, to prevent sticking keys
         e.bgmscriptstate = false;
         e.bgmscriptvolume = 1;
         e.bgmscriptstatetime = bgmtime - GetTimeForAmplitude(e, amp);
     }
     // find the CURRENT line
     for (;;)
     {
         tokenize_console(bufstr_get(bgmscriptbuf, e.bgmscriptline));
         if(stof(argv(1)) >= bgmtime || argv(0) != e.bgmscript)
         {
             e.bgmscripttime = bgmtime;
             return GetCurrentAmplitude(e, bgmtime - e.bgmscriptstatetime);
         }
         else if(bgmtime >= stof(argv(1)))
         {
             e.bgmscriptline += 1;
             e.bgmscripttime = stof(argv(1));
             amp = GetCurrentAmplitude(e, e.bgmscripttime - e.bgmscriptstatetime);
             // time code reached!
             vel = stof(argv(2));
             if(vel > 0)
             {
                 e.just_toggled = e.bgmscriptstate = true;
                 e.bgmscriptvolume = vel;
             }
             else
                 e.just_toggled = e.bgmscriptstate = false;
             e.bgmscriptstatetime = e.bgmscripttime - GetTimeForAmplitude(e, amp);
         }
     }
 }
float GetAttackDecaySustainAmplitude (float a, float d, float s, float t)
Definition at line 16 of file bgmscript.qc.
Referenced by GetCurrentAmplitude().
 {
     // phase:
     //   attack: from 0 to 1, in time a for a full length
     //   decay: from 1 to s, in time d
     //   sustain: s
     if(t < 0)
         return 0;
     if(a)
         if(t <= a)
             return t / a;
     if(d)
         if(t <= a + d)
             return ((t - a) / d) * (s - 1) + 1;
     return s;
 }
float GetAttackTime (float a, float amp)
Definition at line 64 of file bgmscript.qc.
Referenced by GetTimeForAmplitude().
 {
     return amp * a;
 }
float GetCurrentAmplitude (entity e, float trel)
Definition at line 143 of file bgmscript.qc.
References GetAttackDecaySustainAmplitude(), and GetReleaseAmplitude().
Referenced by doBGMScript().
 {
     if(e.bgmscriptstate)
         return GetAttackDecaySustainAmplitude(e.bgmscriptattack, e.bgmscriptdecay, e.bgmscriptsustain, trel) * e.bgmscriptvolume;
     else
     {
 #ifdef CONSTANT_SPEED_DECAY
         return GetReleaseAmplitude(e.bgmscriptdecay, e.bgmscriptsustain * e.bgmscriptvolume, e.bgmscriptrelease, trel);
 #else
         return GetReleaseAmplitude(e.bgmscriptdecay, e.bgmscriptsustain, e.bgmscriptrelease, trel) * e.bgmscriptvolume;
 #endif
     }
 }
float GetReleaseAmplitude (float d, float s, float r, float t)
Definition at line 37 of file bgmscript.qc.
References max().
Referenced by GetCurrentAmplitude().
 {
     float decayval, releaseval;
     if(!r)
         return 0;
     if(t > r)
         return 0;
     releaseval = s * (1 - t / r);
     if(t < -d)
         return 1;
     if(t < 0 && t >= -d)
     {
         // pre-time decay
         // value is s at time  0
         //          1 at time -d
         decayval = ((t + d) / d) * (s - 1) + 1;
         return max(decayval, releaseval);
     }
     return releaseval;
 }
float GetReleaseTime (float d, float s, float r, float amp)
Definition at line 69 of file bgmscript.qc.
References max().
Referenced by GetTimeForAmplitude().
 {
     float decaytime, releasetime;
     if(!s)
         return 0;
     // if amp > s, we may be in the attack or in the prolonged decay curve
     releasetime = (1 - amp / s) * r;
     if(amp > s)
     {
         if(s == 1) // gracefully handle division by zero here
             return 0;
         // pre-time decay
         // value is s at time  0
         //          1 at time -d
         decaytime = (amp - 1) / (s - 1) * d - d;
         return max(decaytime, releasetime);
     }
     return releasetime;
 }
float GetTimeForAmplitude (entity e, float amp)
Definition at line 157 of file bgmscript.qc.
References GetAttackTime(), and GetReleaseTime().
Referenced by doBGMScript().
 {
     if(e.bgmscriptstate)
         return GetAttackTime(e.bgmscriptattack, amp / e.bgmscriptvolume);
     else
     {
 #ifdef CONSTANT_SPEED_DECAY
         return GetReleaseTime(e.bgmscriptdecay, e.bgmscriptsustain * e.bgmscriptvolume, e.bgmscriptrelease, amp);
 #else
         return GetReleaseTime(e.bgmscriptdecay, e.bgmscriptsustain, e.bgmscriptrelease, amp / e.bgmscriptvolume);
 #endif
     }
 }
Variable Documentation
float bgmscriptbuf
Definition at line 5 of file bgmscript.qc.
Referenced by BGMScript_Init(), BGMScript_InitEntity(), and doBGMScript().
float bgmscriptbufloaded
Definition at line 7 of file bgmscript.qc.
Referenced by BGMScript_Init(), and BGMScript_InitEntity().
float bgmscriptbufsize
Definition at line 6 of file bgmscript.qc.
Referenced by BGMScript_Init(), and BGMScript_InitEntity().