Xonotic: AnimHost Class Reference
AnimHost Class Reference
Public Member Functions
virtual void addAnim ()
ATTRIB (AnimHost, firstChild, entity)
ATTRIB (AnimHost, lastChild, entity)
virtual void finishAllAnim ()
virtual void finishObjAnim ()
virtual void removeAllAnim ()
virtual void removeAnim ()
virtual void removeObjAnim ()
virtual void resumeAllAnim ()
virtual void resumeObjAnim ()
virtual void stopAllAnim ()
virtual void stopObjAnim ()
virtual void tickAll ()
Detailed Description
Definition at line 5 of file animhost.qh.
Member Function Documentation
void AnimHost::addAnim () virtual
Definition at line 8 of file animhost.qc.
References entity(), error(), firstChild, NULL, and other.
     {
         if (other.parent) error("Can't add already added anim!");
         if (other.isFinished(other)) error("Can't add finished anim!");
         other.parent = this;
         entity l = this.lastChild;
         if (l) l.nextSibling = other;
         else this.firstChild = other;
         other.prevSibling = l;
         other.nextSibling = NULL;
         this.lastChild = other;
     }
AnimHost::ATTRIB (AnimHost , firstChild , entity)
AnimHost::ATTRIB (AnimHost , lastChild , entity)
void AnimHost::finishAllAnim () virtual
Definition at line 90 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
         {
             entity tmp = e;
             e = tmp.prevSibling;
             tmp.finishAnim(tmp);
         }
     }
void AnimHost::finishObjAnim () virtual
Definition at line 100 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
         {
             if (e.object == obj)
             {
                 entity tmp = e;
                 e = tmp.prevSibling;
                 tmp.finishAnim(tmp);
             }
         }
     }
void AnimHost::removeAllAnim () virtual
Definition at line 43 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
         {
             entity tmp = e;
             e = tmp.prevSibling;
             this.removeAnim(this, tmp);
         }
     }
void AnimHost::removeAnim () virtual
Definition at line 26 of file animhost.qc.
References entity(), error(), firstChild, NULL, and other.
     {
         if (other.parent != this) error("Can't remove from wrong AnimHost!");
         other.parent = NULL;
         entity n = other.nextSibling;
         entity p = other.prevSibling;
         if (p) p.nextSibling = n;
         else this.firstChild = n;
         if (n) n.prevSibling = p;
         else this.lastChild = p;
         delete(other);
     }
void AnimHost::removeObjAnim () virtual
Definition at line 53 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
         {
             if (e.object == obj)
             {
                 entity tmp = e;
                 e = tmp.prevSibling;
                 this.removeAnim(this, tmp);
             }
         }
     }
void AnimHost::resumeAllAnim () virtual
Definition at line 78 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
             e.resumeAnim(e);
     }
void AnimHost::resumeObjAnim () virtual
Definition at line 84 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
             if (e.object == obj) e.resumeAnim(e);
     }
void AnimHost::stopAllAnim () virtual
Definition at line 66 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
             e.stopAnim(e);
     }
void AnimHost::stopObjAnim () virtual
Definition at line 72 of file animhost.qc.
References entity(), and firstChild.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
             if (e.object == obj) e.stopAnim(e);
     }
void AnimHost::tickAll () virtual
Definition at line 113 of file animhost.qc.
References entity(), firstChild, and time.
     {
         for (entity e = this.firstChild; e; e = e.nextSibling)
         {
             e.tick(e, time);
             if (e.isFinished(e))
             {
                 entity tmp = e;
                 e = tmp.prevSibling;
                 this.removeAnim(this, tmp);
             }
         }
     }
The documentation for this class was generated from the following files:
menu/anim/animhost.qh
menu/anim/animhost.qc