Xonotic: menu/xonotic/commandbutton.qh File Reference
commandbutton.qh File Reference
#include "button.qh"
Classes
class XonoticCommandButton
Macros
#define COMMANDBUTTON_APPLY 2
#define COMMANDBUTTON_CLOSE 1
Functions
entity makeXonoticCommandButton (string theText, vector theColor, string theCommand, float closesMenu)
entity makeXonoticCommandButton_T (string theText, vector theColor, string theCommand, float closesMenu, string theTooltip)
Macro Definition Documentation
#define COMMANDBUTTON_APPLY 2
Definition at line 15 of file commandbutton.qh.
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticProfileTab_fill(), and XonoticVideoSettingsTab_fill().
#define COMMANDBUTTON_CLOSE 1
Definition at line 14 of file commandbutton.qh.
Referenced by XonoticCommandButton_Click(), and XonoticUid2NameDialog_fill().
Function Documentation
entity makeXonoticCommandButton (string theText, vector theColor, string theCommand, float closesMenu)
Definition at line 10 of file commandbutton.qc.
References makeXonoticCommandButton_T(), and string_null.
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticLanguageWarningDialog_fill(), XonoticMonsterToolsDialog_fill(), XonoticProfileTab_fill(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticTeamSelectDialog_fill(), XonoticUid2NameDialog_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCommandButton_T(theText, theColor, theCommand, theFlags, string_null);
 }
entity makeXonoticCommandButton_T (string theText, vector theColor, string theCommand, float closesMenu, string theTooltip)
Definition at line 3 of file commandbutton.qc.
References entity(), and NEW.
Referenced by makeXonoticCommandButton(), and XonoticQuitDialog_fill().
 {
     entity me;
     me = NEW(XonoticCommandButton);
     me.configureXonoticCommandButton(me, theText, theColor, theCommand, theFlags, theTooltip);
     return me;
 }