Xonotic: client/hud/panel/powerups.qh File Reference
powerups.qh File Reference
#include "../panel.qh"
Functions
void addPowerupItem (string name, string icon, vector color, float currentTime, float lifeTime)
Function Documentation
void addPowerupItem (string name, string icon, vector color, float currentTime, float lifeTime)
Definition at line 38 of file powerups.qc.
References color, entity(), name, powerupItems, powerupItemsCount, and spawn().
Referenced by HUD_Powerups().
 {
     if(!powerupItems)
         powerupItems = spawn();
     entity item;
     for(item = powerupItems; item.count; item = item.chain)
         if(!item.chain)
             item.chain = spawn();
     item.message  = name;
     item.netname  = icon;
     item.colormod = color;
     item.count    = currentTime;
     item.lifetime = lifeTime;
     ++powerupItemsCount;
 }