Xonotic: Health Class Reference
Health Class Reference
Public Member Functions
virtual void describe ()
virtual void display ()
void ITEM_HANDLE (Show, GameItem this)
virtual void show ()
Public Attributes
vector m_color = '1 1 1'
string m_icon = string_null
int m_id = 0
Model m_model = NULL
string m_name = string_null
Sound m_sound = SND_ITEMPICKUP
string m_waypoint = string_null
int m_waypointblink = 1
Detailed Description
Definition at line 4 of file health.qh.
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void GameItem::display () inline virtual inherited
Reimplemented from Object.
Reimplemented in Buff.
Definition at line 49 of file item.qh.
References cvar_string(), string_null, and TC.
     {
         TC(GameItem, this);
         returns(this.m_name, this.m_icon ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.m_icon) : string_null);
     }
void GameItem::ITEM_HANDLE (Show , GameItem this) inline inherited
Definition at line 59 of file item.qh.
 { this.show(this); }
virtual void Pickup::show () inline virtual inherited
Reimplemented from GameItem.
Definition at line 11 of file pickup.qh.
References etos(), LOG_INFOF, and TC.
     {
         TC(Pickup, this);
         LOG_INFOF("%s: %s\n", etos(this), this.m_name);
     }
Member Data Documentation
vector GameItem::m_color = '1 1 1' inherited
Definition at line 46 of file item.qh.
string GameItem::m_icon = string_null inherited
Definition at line 45 of file item.qh.
int GameItem::m_id = 0 inherited
Definition at line 43 of file item.qh.
Model Pickup::m_model = NULL inherited
Definition at line 7 of file pickup.qh.
string Pickup::m_name = string_null inherited
Definition at line 10 of file pickup.qh.
Sound Pickup::m_sound = SND_ITEMPICKUP inherited
Definition at line 8 of file pickup.qh.
string GameItem::m_waypoint = string_null inherited
Definition at line 47 of file item.qh.
int GameItem::m_waypointblink = 1 inherited
Definition at line 48 of file item.qh.
The documentation for this class was generated from the following file:
common/items/item/health.qh