Xonotic: common/minigames/cl_minigames_hud.qc File Reference
cl_minigames_hud.qc File Reference
#include "cl_minigames_hud.qh"
#include <common/ent_cs.qh>
#include "minigames.qh"
#include <client/hud/hud_config.qh>
#include <client/mapvoting.qh>
Functions
float HUD_Minigame_InputEvent (float bInputType, float nPrimary, float nSecondary)
void HUD_Minigame_Mouse ()
void HUD_MinigameBoard ()
void HUD_MinigameHelp ()
void HUD_MinigameMenu ()
void HUD_MinigameMenu_Click (entity menuitem)
bool HUD_MinigameMenu_Click_ExpandCollapse (entity this)
void HUD_MinigameMenu_ClickCreate (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickCreate_Entry (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickCurrentGame (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickCustomEntry (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickInvite (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickInvite_Entry (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickJoin (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickJoin_Entry (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_ClickQuit (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_CurrentButton ()
void HUD_MinigameMenu_CustomEntry (entity parent, string menumessage, string event_arg)
void HUD_MinigameMenu_DrawColoredEntry (vector pos, string s, vector fontsize)
void HUD_MinigameMenu_DrawEntry (vector pos, string s, vector fontsize, vector color)
void HUD_MinigameMenu_EraseEntry (entity e)
void HUD_MinigameMenu_InsertEntry (entity newentry, entity prev)
bool HUD_MinigameMenu_IsOpened ()
void HUD_MinigameMenu_MouseInput ()
void HUD_MinigameMenu_Open ()
entity HUD_MinigameMenu_SpawnEntry (string s, vector offset, vector fontsize, vector color, void(entity, entity, entity) click)
entity HUD_MinigameMenu_SpawnSubEntry (string s, void(entity, entity, entity) click, entity parent)
void HUD_MinigameStatus ()
bool HUD_mouse_over (entity somepanel)
Variables
vector colormod
entity HUD_MinigameMenu_activeitem
entity HUD_MinigameMenu_entries
entity HUD_MinigameMenu_last_entry
Function Documentation
float HUD_Minigame_InputEvent (float bInputType, float nPrimary, float nSecondary)
TODO: bInputType == 2?
Definition at line 568 of file cl_minigames_hud.qc.
References active_minigame, argv(), autocvar__hud_configure, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_Click(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, HUD_mouse_over(), HUD_PANEL, hudShiftState, K_ALT, K_CTRL, K_DOWNARROW, K_END, K_ENTER, K_ESCAPE, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_ENTER, K_KP_HOME, K_KP_UPARROW, K_MOUSE1, K_MOUSE16, K_MOUSE2, K_SHIFT, K_SPACE, K_UPARROW, mouseClicked, mousepos, NULL, S_ALT, S_CTRL, S_MOUSE1, S_MOUSE2, S_SHIFT, stof(), strcat(), and tokenize().
Referenced by CSQC_InputEvent().
 {
     if( !HUD_MinigameMenu_IsOpened() || autocvar__hud_configure )
         return false;
     if(bInputType == 3)
     {
         mousepos_x = nPrimary;
         mousepos_y = nSecondary;
         if ( active_minigame && HUD_mouse_over(HUD_PANEL(MINIGAMEBOARD)) )
             active_minigame.minigame_event(active_minigame,"mouse_moved",mousepos);
         return true;
     }
     else
     {
         if(bInputType == 0) {
             if(nPrimary == K_ALT) hudShiftState |= S_ALT;
             if(nPrimary == K_CTRL) hudShiftState |= S_CTRL;
             if(nPrimary == K_SHIFT) hudShiftState |= S_SHIFT;
             if(nPrimary == K_MOUSE1) mouseClicked |= S_MOUSE1;
             if(nPrimary == K_MOUSE2) mouseClicked |= S_MOUSE2;
         }
         else if(bInputType == 1) {
             if(nPrimary == K_ALT) hudShiftState -= (hudShiftState & S_ALT);
             if(nPrimary == K_CTRL) hudShiftState -= (hudShiftState & S_CTRL);
             if(nPrimary == K_SHIFT) hudShiftState -= (hudShiftState & S_SHIFT);
             if(nPrimary == K_MOUSE1) mouseClicked -= (mouseClicked & S_MOUSE1);
             if(nPrimary == K_MOUSE2) mouseClicked -= (mouseClicked & S_MOUSE2);
         }
         // allow some binds
         string con_keys = findkeysforcommand("toggleconsole", 0);
         int keys = tokenize(con_keys); // findkeysforcommand returns data for this
         int i;
         for (i = 0; i < keys; ++i)
         {
             if(nPrimary == stof(argv(i)))
                 return false;
         }
         if ( active_minigame && ( bInputType == 0 || bInputType == 1 ) )
         {
             string device = "";
             string action = bInputType == 0 ? "pressed" : "released";
             if ( nPrimary >= K_MOUSE1 && nPrimary <= K_MOUSE16 )
             {
                 if ( HUD_mouse_over(HUD_PANEL(MINIGAMEBOARD)) )
                     device = "mouse";
             }
             else
                 device = "key";
             if ( device && active_minigame.minigame_event(
                     active_minigame,strcat(device,"_",action),nPrimary) )
                 return true;
         }
         if ( bInputType == 0 )
         {
             if ( nPrimary == K_MOUSE1 && HUD_MinigameMenu_activeitem &&
                 HUD_mouse_over(HUD_PANEL(MINIGAMEMENU)) )
             {
                 HUD_MinigameMenu_Click(HUD_MinigameMenu_activeitem);
                 return true;
             }
             if ( nPrimary == K_UPARROW || nPrimary == K_KP_UPARROW )
             {
                 if ( HUD_MinigameMenu_activeitem && HUD_MinigameMenu_activeitem.list_prev )
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_activeitem.list_prev;
                 else
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_last_entry;
                 return true;
             }
             else if ( nPrimary == K_DOWNARROW || nPrimary == K_KP_DOWNARROW )
             {
                 if ( HUD_MinigameMenu_activeitem && HUD_MinigameMenu_activeitem.list_next )
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_activeitem.list_next;
                 else
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_HOME || nPrimary == K_KP_HOME )
             {
                 HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_END || nPrimary == K_KP_END )
             {
                 HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_KP_ENTER || nPrimary == K_ENTER || nPrimary == K_SPACE )
             {
                 HUD_MinigameMenu_Click(HUD_MinigameMenu_activeitem);
                 return true;
             }
             else if ( nPrimary == K_ESCAPE )
             {
                 HUD_MinigameMenu_Close(NULL, NULL, NULL);
                 return true;
             }
         }
     }
     return false;
 }
void HUD_Minigame_Mouse ()
Definition at line 680 of file cl_minigames_hud.qc.
References autocvar__hud_configure, autocvar_hud_cursormode, draw_cursor_normal(), HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_MouseInput(), HUD_mouse_over(), HUD_PANEL, mousepos, mv_active, panel_fg_alpha, and update_mousepos().
Referenced by CSQC_UpdateView().
 {
     if( !HUD_MinigameMenu_IsOpened() || autocvar__hud_configure || mv_active )
         return;
     if (!autocvar_hud_cursormode)
         update_mousepos();
     if ( HUD_MinigameMenu_IsOpened() && HUD_mouse_over(HUD_PANEL(MINIGAMEMENU)) )
         HUD_MinigameMenu_MouseInput();
     draw_cursor_normal(mousepos, '1 1 1', panel_fg_alpha);
 }
void HUD_MinigameBoard ()
Definition at line 26 of file cl_minigames_hud.qc.
References active_minigame, autocvar__hud_configure, entity(), HUD_Panel_LoadCvars(), minigame_get_descriptor(), NULL, panel_pos, panel_size, and vector().
 {
     entity hud_minigame = NULL;
     if(!autocvar__hud_configure)
         hud_minigame = active_minigame.descriptor;
     else
         hud_minigame = minigame_get_descriptor("nmm");
     if ( !hud_minigame )
         return;
     HUD_Panel_LoadCvars();
     vector pos, mySize;
     pos = panel_pos;
     mySize = panel_size;
     hud_minigame.minigame_hud_board(pos,mySize);
 }
void HUD_MinigameHelp ()
Definition at line 536 of file cl_minigames_hud.qc.
References active_minigame, autocvar__hud_configure, DRAWFLAG_NORMAL, hud_fontsize, HUD_Panel_LoadCvars(), minigame_drawcolorcodedstring_wrapped(), panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, and vector().
 {
     string help_message;
     if(!autocvar__hud_configure)
         help_message = active_minigame.message;
     else
         help_message = "Minigame message";
     if ( !help_message )
         return;
     HUD_Panel_LoadCvars();
     vector pos, mySize;
     pos = panel_pos;
     mySize = panel_size;
     if(panel_bg_padding)
     {
         pos += '1 1 0' * panel_bg_padding;
         mySize -= '2 2 0' * panel_bg_padding;
     }
     minigame_drawcolorcodedstring_wrapped( mySize_x, pos, help_message,
         hud_fontsize, panel_fg_alpha, DRAWFLAG_NORMAL, 0.5 );
 }
void HUD_MinigameMenu ()
Definition at line 473 of file cl_minigames_hud.qc.
References color, drawfill(), DRAWFLAG_ADDITIVE, DRAWFLAG_NORMAL, drawpic(), entity(), eX, eY, hud_fontsize, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_DrawColoredEntry(), HUD_MinigameMenu_DrawEntry(), HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_Panel_DrawBg, HUD_Panel_LoadCvars(), HUD_Scale_Disable(), NULL, panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, and vector().
 {
     if ( !HUD_MinigameMenu_IsOpened() )
         return;
     HUD_Panel_LoadCvars();
     HUD_Scale_Disable();
     HUD_Panel_DrawBg();
     if(panel_bg_padding)
     {
         panel_pos += '1 1 0' * panel_bg_padding;
         panel_size -= '2 2 0' * panel_bg_padding;
     }
     HUD_MinigameMenu_DrawEntry(panel_pos,_("Minigames"),hud_fontsize*2,'0.25 0.47 0.72');
     panel_pos_y += hud_fontsize_y*2;
     vector color;
     vector offset;
     float itemh;
     vector imgsz = '22 22 0'; // NOTE: if changed, edit where HUD_MinigameMenu_activeitem is selected
     for ( entity e = HUD_MinigameMenu_entries; e != NULL; e = e.list_next )
     {
         color = e.colormod;
         offset = e.origin;
         itemh = e.size_y;
         if ( e.model )
             itemh = imgsz_y;
         if ( e.flags & 2 )
         {
             drawfill(panel_pos, eX*panel_size_x + eY*itemh, e.colormod,
                     panel_fg_alpha, DRAWFLAG_NORMAL);
             color = '0 0 0';
         }
         if ( e.model )
         {
             drawpic( panel_pos+offset, e.model, imgsz, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL );
             offset_x += imgsz_x;
             offset_y = (imgsz_y-e.size_y) / 2;
         }
         if ( e.flags & 1 )
             HUD_MinigameMenu_DrawColoredEntry(panel_pos+offset,e.message,e.size);
         else
             HUD_MinigameMenu_DrawEntry(panel_pos+offset,e.message,e.size,color);
         if ( e == HUD_MinigameMenu_activeitem )
             drawfill(panel_pos, eX*panel_size_x + eY*itemh,'1 1 1', 0.25, DRAWFLAG_ADDITIVE);
         panel_pos_y += itemh;
     }
 }
void HUD_MinigameMenu_Click (entity menuitem)
Definition at line 115 of file cl_minigames_hud.qc.
References NULL.
Referenced by HUD_Minigame_InputEvent(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_CurrentButton(), and HUD_MinigameMenu_EraseEntry().
 {
     if ( menuitem )
     {
         menuitem.use(menuitem, NULL, NULL);
     }
 }
bool HUD_MinigameMenu_Click_ExpandCollapse (entity this)
Definition at line 182 of file cl_minigames_hud.qc.
References entity(), flags, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_Click(), HUD_MinigameMenu_entries, HUD_MinigameMenu_last_entry, list_next, and NULL.
Referenced by HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_ClickInvite(), and HUD_MinigameMenu_ClickJoin().
 {
     entity e;
     if ( this.flags & 2 )
     {
         if ( HUD_MinigameMenu_activeitem &&
                 HUD_MinigameMenu_activeitem.owner == this )
             HUD_MinigameMenu_activeitem = NULL;
         this.flags &= ~2;
         for ( e = this.list_next; e != NULL && e.owner == this; e = this.list_next )
         {
             if ( e.flags & 2 )
                 HUD_MinigameMenu_Click(e);
             this.list_next = e.list_next;
             delete(e);
         }
         if ( this.list_next )
             this.list_next.list_prev = this;
         else
             HUD_MinigameMenu_last_entry = this;
     }
     else
     {
         for ( e = HUD_MinigameMenu_entries; e != NULL; e = e.list_next )
         {
             if ( e.flags & 2 && e.origin_x == this.origin_x)
                 HUD_MinigameMenu_Click(e);
         }
         this.flags |= 2;
         return true;
     }
     return false;
 }
void HUD_MinigameMenu_ClickCreate (entity this, entity actor, entity trigger)
Definition at line 219 of file cl_minigames_hud.qc.
References entity(), FOREACH, HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickCreate_Entry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_SpawnSubEntry(), minigame_texture(), prev, strcat(), and strzone().
Referenced by HUD_MinigameMenu_Open().
 {
     if ( HUD_MinigameMenu_Click_ExpandCollapse(this) )
     {
         entity curr;
         entity prev = this;
         FOREACH(Minigames, true, {
             curr = HUD_MinigameMenu_SpawnSubEntry(it.message, HUD_MinigameMenu_ClickCreate_Entry, this);
             curr.netname = it.netname;
             curr.model = strzone(minigame_texture(strcat(it.netname,"/icon")));
             HUD_MinigameMenu_InsertEntry( curr, prev );
             prev = curr;
         });
     }
 }
void HUD_MinigameMenu_ClickCreate_Entry (entity this, entity actor, entity trigger)
Definition at line 175 of file cl_minigames_hud.qc.
References minigame_cmd, and netname.
Referenced by HUD_MinigameMenu_ClickCreate().
 {
     minigame_cmd("create ", this.netname);
 }
void HUD_MinigameMenu_ClickCurrentGame (entity this, entity actor, entity trigger)
Definition at line 326 of file cl_minigames_hud.qc.
References active_minigame, HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickQuit(), HUD_MinigameMenu_InsertEntry(), and HUD_MinigameMenu_SpawnSubEntry().
Referenced by HUD_MinigameMenu_CurrentButton().
 {
     if ( HUD_MinigameMenu_Click_ExpandCollapse(this) )
     {
         HUD_MinigameMenu_InsertEntry( HUD_MinigameMenu_SpawnSubEntry(
             _("Quit"), HUD_MinigameMenu_ClickQuit, this ), this);
         active_minigame.minigame_event(active_minigame,"menu_show",this);
         HUD_MinigameMenu_InsertEntry( HUD_MinigameMenu_SpawnSubEntry(
             _("Invite"), HUD_MinigameMenu_ClickInvite, this), this);
     }
 }
void HUD_MinigameMenu_ClickCustomEntry (entity this, entity actor, entity trigger)
Definition at line 309 of file cl_minigames_hud.qc.
References active_minigame, and netname.
Referenced by HUD_MinigameMenu_CustomEntry().
 {
     if ( active_minigame )
         active_minigame.minigame_event(active_minigame,"menu_click",this.netname);
 }
void HUD_MinigameMenu_ClickInvite (entity this, entity actor, entity trigger)
Definition at line 285 of file cl_minigames_hud.qc.
References entity(), findfloat(), ftos(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickInvite_Entry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_SpawnSubEntry(), maxclients, minigame_playerslot, NULL, ping, player_localnum, playerslots, prev, and strzone().
Referenced by HUD_MinigameMenu_ClickCurrentGame().
 {
     if ( HUD_MinigameMenu_Click_ExpandCollapse(this) )
     {
         entity e;
         entity prev = this;
         for(int i = 0; i < maxclients; ++i)
         {
             if ( player_localnum != i && playerslots[i] && entcs_GetName(i) != "" &&
                 !findfloat(NULL,minigame_playerslot,i+1) && playerslots[i].ping )
             {
                 e = HUD_MinigameMenu_SpawnSubEntry(
                     strzone(entcs_GetName(i)), HUD_MinigameMenu_ClickInvite_Entry,
                     this );
                 e.flags |= 1;
                 e.netname = strzone(ftos(i+1));
                 e.origin_x *= 2;
                 HUD_MinigameMenu_InsertEntry(e,prev);
                 prev = e;
             }
         }
     }
 }
void HUD_MinigameMenu_ClickInvite_Entry (entity this, entity actor, entity trigger)
Definition at line 279 of file cl_minigames_hud.qc.
References minigame_cmd, and netname.
Referenced by HUD_MinigameMenu_ClickInvite().
 {
     minigame_cmd("invite #",this.netname);
 }
void HUD_MinigameMenu_ClickJoin (entity this, entity actor, entity trigger)
Definition at line 243 of file cl_minigames_hud.qc.
References active_minigame, classname, entity(), find(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickJoin_Entry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_SpawnSubEntry(), minigame_texture(), NULL, prev, strcat(), and strzone().
Referenced by HUD_MinigameMenu_Open().
 {
     if ( HUD_MinigameMenu_Click_ExpandCollapse(this) )
     {
         entity e = NULL;
         entity curr;
         entity prev = this;
         while( (e = find(e,classname,"minigame")) )
         {
             if ( e != active_minigame )
             {
                 curr = HUD_MinigameMenu_SpawnSubEntry(
                     e.netname, HUD_MinigameMenu_ClickJoin_Entry, this );
                 curr.netname = e.netname;
                 curr.model = strzone(minigame_texture(strcat(e.descriptor.netname,"/icon")));
                 HUD_MinigameMenu_InsertEntry( curr, prev );
                 prev = curr;
             }
         }
     }
 }
void HUD_MinigameMenu_ClickJoin_Entry (entity this, entity actor, entity trigger)
Definition at line 236 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_EraseEntry(), minigame_cmd, and netname.
Referenced by HUD_MinigameMenu_ClickJoin().
 {
     minigame_cmd("join ",this.netname);
     HUD_MinigameMenu_EraseEntry(this);
 }
void HUD_MinigameMenu_ClickQuit (entity this, entity actor, entity trigger)
Definition at line 272 of file cl_minigames_hud.qc.
References deactivate_minigame(), and minigame_cmd.
Referenced by HUD_MinigameMenu_ClickCurrentGame().
 {
     deactivate_minigame();
     minigame_cmd("end");
 }
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
Definition at line 346 of file cl_minigames_hud.qc.
References autocvar__hud_configure, autocvar_hud_cursormode, entity(), HUD_MinigameMenu_activeitem, HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, NULL, and p.
Referenced by deactivate_minigame(), HUD_Minigame_InputEvent(), HUD_MinigameMenu_CurrentButton(), MUTATOR_HOOKFUNCTION(), and Shutdown().
 {
     if ( HUD_MinigameMenu_IsOpened() )
     {
         entity e, p;
         for ( e = HUD_MinigameMenu_entries; e != NULL; e = p )
         {
             p = e.list_next;
             delete(e);
         }
         HUD_MinigameMenu_entries = NULL;
         HUD_MinigameMenu_last_entry = NULL;
         HUD_MinigameMenu_activeitem = NULL;
         if(autocvar_hud_cursormode)
         if ( !autocvar__hud_configure )
             setcursormode(0);
     }
 }
void HUD_MinigameMenu_CurrentButton ()
Definition at line 366 of file cl_minigames_hud.qc.
References active_minigame, entity(), hud_fontsize, HUD_MinigameMenu_Click(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_EraseEntry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_last_entry, HUD_MinigameMenu_SpawnEntry(), minigame_texture(), NULL, p, strcat(), and strzone().
Referenced by activate_minigame(), deactivate_minigame(), and HUD_MinigameMenu_Open().
 {
     entity e;
     if ( active_minigame )
     {
         for ( e = HUD_MinigameMenu_last_entry; e != NULL; e = e.list_prev )
             if ( e.classname == "hud_minigamemenu_exit" )
             {
                 HUD_MinigameMenu_EraseEntry(e);
                 break;
             }
         entity currb = HUD_MinigameMenu_SpawnEntry(
             _("Current Game"), '0 0 0', hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickCurrentGame );
         currb.classname = "hud_minigamemenu_current";
         currb.model = strzone(minigame_texture(strcat(active_minigame.descriptor.netname,"/icon")));
         HUD_MinigameMenu_InsertEntry(currb,HUD_MinigameMenu_last_entry);
         HUD_MinigameMenu_Click(currb);
     }
     else
     {
         entity p;
         for ( e = HUD_MinigameMenu_last_entry; e != NULL; e = p.list_prev )
         {
             p = e;
             if ( e.classname == "hud_minigamemenu_current" )
             {
                 p = e.list_next;
                 if ( !p )
                     p = HUD_MinigameMenu_last_entry;
                 HUD_MinigameMenu_EraseEntry(e);
                 break;
             }
         }
         for ( e = HUD_MinigameMenu_last_entry; e != NULL; e = e.list_prev )
             if ( e.classname == "hud_minigamemenu_exit" )
                 return;
         entity exit = HUD_MinigameMenu_SpawnEntry(
             _("Exit Menu"),'0 0 0',hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_Close);
         exit.classname = "hud_minigamemenu_exit";
         HUD_MinigameMenu_InsertEntry ( exit, HUD_MinigameMenu_last_entry );
     }
 }
void HUD_MinigameMenu_CustomEntry (entity parent, string menumessage, string event_arg)
Definition at line 316 of file cl_minigames_hud.qc.
References entity(), HUD_MinigameMenu_ClickCustomEntry(), HUD_MinigameMenu_InsertEntry(), and HUD_MinigameMenu_SpawnSubEntry().
 {
     entity e = HUD_MinigameMenu_SpawnSubEntry(
         menumessage, HUD_MinigameMenu_ClickCustomEntry, parent );
     e.netname = event_arg;
     HUD_MinigameMenu_InsertEntry(e, parent);
     //dprint("CustomEntry ",ftos(num_for_edict(parent))," ",menumessage," ",event_arg,"\n");
 }
void HUD_MinigameMenu_DrawColoredEntry (vector pos, string s, vector fontsize)
Definition at line 466 of file cl_minigames_hud.qc.
References DRAWFLAG_NORMAL, minigame_drawcolorcodedstring_trunc(), and panel_fg_alpha.
Referenced by HUD_MinigameMenu().
 {
     minigame_drawcolorcodedstring_trunc(panel_size_x-pos_x+panel_pos_x, pos, s,
                               fontsize, panel_fg_alpha, DRAWFLAG_NORMAL);
 }
void HUD_MinigameMenu_DrawEntry (vector pos, string s, vector fontsize, vector color)
Definition at line 460 of file cl_minigames_hud.qc.
References DRAWFLAG_NORMAL, minigame_drawstring_trunc(), and panel_fg_alpha.
Referenced by HUD_MinigameMenu().
 {
     minigame_drawstring_trunc(panel_size_x-pos_x+panel_pos_x, pos, s,
                               fontsize, color, panel_fg_alpha, DRAWFLAG_NORMAL);
 }
void HUD_MinigameMenu_EraseEntry (entity e)
Definition at line 125 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_activeitem, HUD_MinigameMenu_Click(), HUD_MinigameMenu_entries, HUD_MinigameMenu_last_entry, and NULL.
Referenced by HUD_MinigameMenu_ClickJoin_Entry(), and HUD_MinigameMenu_CurrentButton().
 {
     // remove child items (if any)
     if ( e.flags & 2 )
     {
         HUD_MinigameMenu_Click(e);
     }
     if ( e.list_prev )
         e.list_prev.list_next = e.list_next;
     else
         HUD_MinigameMenu_entries = e.list_next;
     if ( e.list_next )
         e.list_next.list_prev = e.list_prev;
     else
         HUD_MinigameMenu_last_entry = e.list_prev;
     if ( HUD_MinigameMenu_activeitem == e )
         HUD_MinigameMenu_activeitem = NULL;
     delete(e);
 }
void HUD_MinigameMenu_InsertEntry (entity newentry, entity prev)
Definition at line 91 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_entries, HUD_MinigameMenu_last_entry, and prev.
Referenced by HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_CustomEntry(), and HUD_MinigameMenu_Open().
 {
     if ( !HUD_MinigameMenu_entries )
     {
         HUD_MinigameMenu_entries = newentry;
         HUD_MinigameMenu_last_entry = newentry;
         return;
     }
     newentry.list_prev = prev;
     newentry.list_next = prev.list_next;
     if ( prev.list_next )
         prev.list_next.list_prev = newentry;
     else
         HUD_MinigameMenu_last_entry = newentry;
     prev.list_next = newentry;
 }
bool HUD_MinigameMenu_IsOpened ()
Definition at line 340 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_entries, and NULL.
Referenced by activate_minigame(), CSQC_UpdateView(), HUD_Crosshair(), HUD_Minigame_InputEvent(), HUD_Minigame_Mouse(), HUD_MinigameMenu(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_Open(), HUD_Panel_Draw(), minigame_prompt(), and MUTATOR_HOOKFUNCTION().
 {
     return HUD_MinigameMenu_entries != NULL;
 }
void HUD_MinigameMenu_MouseInput ()
Definition at line 428 of file cl_minigames_hud.qc.
References entity(), eX, eY, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_entries, HUD_PANEL, HUD_Panel_LoadCvars(), NULL, panel, panel_bg_padding, panel_pos, panel_size, and vector().
Referenced by HUD_Minigame_Mouse().
 {
     panel = HUD_PANEL(MINIGAMEMENU);
     HUD_Panel_LoadCvars();
     if(panel_bg_padding)
     {
         panel_pos += '1 1 0' * panel_bg_padding;
         panel_size -= '2 2 0' * panel_bg_padding;
     }
     entity e;
     panel_pos_y += hud_fontsize_y*2;
     HUD_MinigameMenu_activeitem = NULL;
     vector sz;
     for ( e = HUD_MinigameMenu_entries; e != NULL; e = e.list_next )
     {
         sz = eX*panel_size_x + eY*e.size_y;
         if ( e.model )
             sz_y = 22;
         if ( !HUD_MinigameMenu_activeitem && mousepos_y >= panel_pos_y && mousepos_y <= panel_pos_y + sz_y )
         {
             HUD_MinigameMenu_activeitem = e;
         }
         panel_pos_y += sz_y;
     }
 }
void HUD_MinigameMenu_Open ()
Definition at line 410 of file cl_minigames_hud.qc.
References autocvar_hud_cursormode, hud_fontsize, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, HUD_MinigameMenu_SpawnEntry(), and NULL.
Referenced by activate_minigame(), and MUTATOR_HOOKFUNCTION().
 {
     if ( !HUD_MinigameMenu_IsOpened() )
     {
         HUD_MinigameMenu_InsertEntry( HUD_MinigameMenu_SpawnEntry(
             _("Create"), '0 0 0', hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickCreate),
             HUD_MinigameMenu_last_entry );
         HUD_MinigameMenu_InsertEntry ( HUD_MinigameMenu_SpawnEntry(
             _("Join"),'0 0 0',hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickJoin),
             HUD_MinigameMenu_last_entry );
         HUD_MinigameMenu_CurrentButton();
         HUD_MinigameMenu_activeitem = NULL;
         if(autocvar_hud_cursormode)
             setcursormode(1);
     }
 }
entity HUD_MinigameMenu_SpawnEntry (string s, vector offset, vector fontsize, vector color, void(entity, entity, entity) click)
Definition at line 150 of file cl_minigames_hud.qc.
References color, entity(), and spawn().
Referenced by HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_Open(), and HUD_MinigameMenu_SpawnSubEntry().
 {
     entity entry = spawn();
     entry.message = s;
     entry.origin = offset;
     entry.size = fontsize;
     entry.colormod = color;
     entry.flags = 0;
     entry.use = click;
     panel_pos_y += fontsize_y;
     return entry;
 }
entity HUD_MinigameMenu_SpawnSubEntry (string s, void(entity, entity, entity) click, entity parent)
Definition at line 164 of file cl_minigames_hud.qc.
References entity(), hud_fontsize, HUD_MinigameMenu_SpawnEntry(), parent, and vector().
Referenced by HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickJoin(), and HUD_MinigameMenu_CustomEntry().
 {
     vector item_fontsize = hud_fontsize*1.25;
     vector item_offset = '1 0 0' * item_fontsize_x;
     entity item = HUD_MinigameMenu_SpawnEntry(
                 s,item_offset,item_fontsize,'0.8 0.8 0.8', click );
     item.owner = parent;
     return item;
 }
void HUD_MinigameStatus ()
Definition at line 52 of file cl_minigames_hud.qc.
References active_minigame, autocvar__hud_configure, entity(), HUD_Panel_LoadCvars(), HUD_Scale_Disable(), minigame_get_descriptor(), NULL, panel_bg_padding, panel_pos, panel_size, and vector().
 {
     entity hud_minigame = NULL;
     if(!autocvar__hud_configure)
         hud_minigame = active_minigame.descriptor;
     else
         hud_minigame = minigame_get_descriptor("nmm");
     if ( !hud_minigame )
         return;
     HUD_Panel_LoadCvars();
     vector pos, mySize;
     pos = panel_pos;
     mySize = panel_size;
     if(panel_bg_padding)
     {
         pos += '1 1 0' * panel_bg_padding;
         mySize -= '2 2 0' * panel_bg_padding;
     }
     HUD_Scale_Disable();
     hud_minigame.minigame_hud_status(pos,mySize);
 }
bool HUD_mouse_over (entity somepanel)
Definition at line 13 of file cl_minigames_hud.qc.
References cvar_string(), stov(), strcat(), vector(), and vid_conheight.
Referenced by HUD_Minigame_InputEvent(), and HUD_Minigame_Mouse().
 {
     vector pos = stov(cvar_string(strcat("hud_panel_", somepanel.panel_name, "_pos")));
     vector sz = stov(cvar_string(strcat("hud_panel_", somepanel.panel_name, "_size")));
     return mousepos_x >= pos_x*vid_conwidth  && mousepos_x <= (pos_x+sz_x)*vid_conwidth &&
            mousepos_y >= pos_y*vid_conheight && mousepos_y <= (pos_y+sz_y)*vid_conheight ;
 }
Variable Documentation
vector colormod
Definition at line 7 of file cl_minigames_hud.qc.
entity HUD_MinigameMenu_activeitem
Definition at line 112 of file cl_minigames_hud.qc.
Referenced by HUD_Minigame_InputEvent(), HUD_MinigameMenu(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_EraseEntry(), HUD_MinigameMenu_MouseInput(), and HUD_MinigameMenu_Open().
entity HUD_MinigameMenu_entries
Definition at line 86 of file cl_minigames_hud.qc.
Referenced by HUD_Minigame_InputEvent(), HUD_MinigameMenu(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_EraseEntry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_IsOpened(), and HUD_MinigameMenu_MouseInput().
entity HUD_MinigameMenu_last_entry
Definition at line 88 of file cl_minigames_hud.qc.
Referenced by HUD_Minigame_InputEvent(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_EraseEntry(), HUD_MinigameMenu_InsertEntry(), and HUD_MinigameMenu_Open().