Xonotic: menu/xonotic/dialog_credits.qc File Reference
dialog_credits.qc File Reference
#include "dialog_credits.qh"
#include "credits.qh"
#include "button.qh"
#include "../item/dialog.qh"
Functions
void XonoticCreditsDialog_fill (entity me)
void XonoticCreditsDialog_focusEnter (entity me)
Function Documentation
void XonoticCreditsDialog_fill (entity me)
Definition at line 7 of file dialog_credits.qc.
References Dialog_Close(), entity(), makeXonoticButton(), and makeXonoticCreditsList().
 {
     entity e;
     me.TR(me);
         me.TD(me, me.rows - 1, me.columns, me.creditsList = makeXonoticCreditsList());
     me.gotoRC(me, me.rows - 1, 0);
         me.TD(me, 1, me.columns, e = makeXonoticButton(_("OK"), '0 0 0'));
             e.onClick = Dialog_Close;
             e.onClickEntity = me;
 }
void XonoticCreditsDialog_focusEnter (entity me)
Definition at line 17 of file dialog_credits.qc.
References time.
 {
     me.creditsList.scrolling = time + 1;
 }