Xonotic: common/notifications/all.inc File Reference
all.inc File Reference
Macros
#define A__NEVER 0
#define A_ALWAYS 2
#define A_WARMUP 1
#define BOLD(translatable_msg) strcat(BOLD_OPERATOR, translatable_msg)
#define MULTITEAM_ANNCE(prefix, defaultvalue, sound, channel, volume, position)
#define MULTITEAM_CENTER(prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, normal, gentle, type)
#define MULTITEAM_CHOICE(prefix, defaultvalue, challow, chtype, optiona, optionb)
#define MULTITEAM_INFO(prefix, defaultvalue, strnum, flnum, args, hudargs, icon, normal, gentle, type)
#define MULTITEAM_MULTI(prefix, defaultvalue, anncepre, infopre, centerpre)
#define MURDER_FRAG BOLD(_("^K3%sYou fragged ^BG%s"))
#define MURDER_FRAG2 BOLD(_("^K3%sYou scored against ^BG%s"))
#define MURDER_FRAG_FIRE BOLD(_("^K3%sYou burned ^BG%s"))
#define MURDER_FRAG_FIRE2 BOLD(_("^K3%sYou scored against ^BG%s"))
#define MURDER_FRAG_FREEZE BOLD(_("^K3%sYou froze ^BG%s"))
#define MURDER_FRAG_FREEZE2 BOLD(_("^K3%sYou scored against ^BG%s"))
#define MURDER_FRAGGED BOLD(_("^K1%sYou were fragged by ^BG%s"))
#define MURDER_FRAGGED2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
#define MURDER_FRAGGED_FIRE BOLD(_("^K1%sYou were burned by ^BG%s"))
#define MURDER_FRAGGED_FIRE2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
#define MURDER_FRAGGED_FREEZE BOLD(_("^K1%sYou were frozen by ^BG%s"))
#define MURDER_FRAGGED_FREEZE2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
#define MURDER_TYPEFRAG BOLD(_("^K1%sYou typefragged ^BG%s"))
#define MURDER_TYPEFRAG2 BOLD(_("^K1%sYou scored against ^BG%s^K1 while they were typing"))
#define MURDER_TYPEFRAGGED BOLD(_("^K1%sYou were typefragged by ^BG%s"))
#define MURDER_TYPEFRAGGED2 BOLD(_("^K1%sYou were scored against by ^BG%s^K1 while typing"))
#define N___NEVER 0
#define N__ALWAYS 2
#define N__NORMAL 1
#define N_CHATCON 2
#define N_CONSOLE 1
#define N_DISABL 0
#define N_DISABL 0
#define N_DISABLE 0
#define N_DISABLE 0
#define N_ENABLE 1
#define N_ENABLE 1
#define N_GNTLOFF 1
#define N_VERBOSE 2
#define VERBOSE_MURDER(type) strcat(MURDER_##type, "^BG%s")
Functions
BOLD (_("^BGYou got the ^TC^TT^BG flag!"))
FLAG BOLD (_("^BGYou got your %steam^BG's flag, return it!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^BGYou have been moved into a different team\ou are now on: %s"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Die camper!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Reconsider your tactics, camper!"))) MSG_CENTER_NOTIF(DEATH_SELF_CHEAT
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You unfairly eliminated yourself!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You couldn't catch your breath!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got a little bit too crispy!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You felt a little too hot!"))) MSG_CENTER_NOTIF(DEATH_SELF_GENERIC
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You fragged yourself!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You need to be more careful!"))) MSG_CENTER_NOTIF(DEATH_SELF_LAVA
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You couldn't stand the heat!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You forgot to put the pin back in!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Tastes like chicken!"))) MSG_CENTER_NOTIF(DEATH_SELF_NADE_NAPALM
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Hanging around a napalm explosion is bad!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Your Healing Nade is a bit defective"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You grew too old without taking your medicine"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You need to preserve your health"))) MSG_CENTER_NOTIF(DEATH_SELF_SHOOTING_STAR
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You became a shooting star!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You committed suicide!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You ended it all!"))) MSG_CENTER_NOTIF(DEATH_SELF_SWAMP
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got stuck in a swamp!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You died in an accident!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were fragged by an eWheel turret!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You had an unfortunate run in with an eWheel turret!"))) MSG_CENTER_NOTIF(DEATH_SELF_TURRET_WALK
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You had an unfortunate run in with a Walker turret!"))) MSG_CENTER_NOTIF(DEATH_SELF_VH_BUMB_DEATH
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were fragged by a Walker turret!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Bumblebee explosion!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were caught in a Raptor cluster bomb!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Spiderbot explosion!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Racer explosion!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Watch your step!"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were team killed by ^BG%s"))
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were betrayed by team mate ^BG%s"))) MSG_CENTER_NOTIF(DISCONNECT_IDLING
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Stop idling!\BGDisconnecting in ^COUNT..."))
MSG_CENTER_NOTIF (CTF_CAPTURESHIELD_SHIELDED, N_ENABLE, 0, 0, "", CPID_CTF_CAPSHIELD, "0 0", _("^BGYou are now ^F1shielded^BG from the flag(s)\BGfor ^F2too many unsuccessful attempts^BG to capture.\BGMake some defensive scores before trying again."), "") MULTITEAM_CENTER(CTF_PICKUP
FLAG MSG_CENTER_NOTIF (CTF_PICKUP_NEUTRAL, N_ENABLE, 0, 0, "", CPID_CTF_LOWPRIO, "0 0", BOLD(_("^BGYou got the flag!")), "") MSG_CENTER_NOTIF(CTF_PICKUP_RETURN
FLAG MSG_CENTER_NOTIF (CTF_PICKUP_RETURN_ENEMY, N_ENABLE, 1, 0, "s1", CPID_CTF_LOWPRIO, "0 0", BOLD(_("^BGYou got the %senemy^BG's flag, return it!")), "") MSG_CENTER_NOTIF(CTF_PICKUP_ENEMY_VERBOSE
FLAG s1 s2 MSG_CENTER_NOTIF (CTF_PICKUP_ENEMY_NEUTRAL_VERBOSE, N_ENABLE, 2, 0, "s1 s2 s1", CPID_CTF_LOWPRIO, "0 0", _("^BGThe %senemy (^BG%s%s)^BG got the flag! Retrieve it!"), "") MSG_CENTER_NOTIF(CTF_PICKUP_ENEMY_TEAM_VERBOSE
MSG_CENTER_NOTIF (DEATH_MURDER_FRAGGED_VERBOSE, N_ENABLE, 1, 4, "spree_cen s1 frag_stats", CPID_Null, "0 0", VERBOSE_MURDER(FRAGGED), VERBOSE_MURDER(FRAGGED2)) MSG_CENTER_NOTIF(DEATH_MURDER_FRAG_VERBOSE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_BETRAYAL, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were punished for attacking your team mates!")), "") MSG_CENTER_NOTIF(DEATH_SELF_CAMP
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_CUSTOM, N_ENABLE, 2, 0, "s2", CPID_Null, "0 0", BOLD(_("^K1You were %s")), "") MSG_CENTER_NOTIF(DEATH_SELF_DROWN
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_FALL, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You hit the ground with a crunch!")), "") MSG_CENTER_NOTIF(DEATH_SELF_FIRE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_MONSTER, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were killed by a monster!")), BOLD(_("^K1You need to watch out for monsters!"))) MSG_CENTER_NOTIF(DEATH_SELF_NADE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_NADE_ICE_FREEZE, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You got a little bit too cold!")), BOLD(_("^K1You felt a little chilly!"))) MSG_CENTER_NOTIF(DEATH_SELF_NADE_HEAL
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_NOAMMO, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were killed for running out of ammo...")), BOLD(_("^K1You are respawning for running out of ammo..."))) MSG_CENTER_NOTIF(DEATH_SELF_ROT
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_SLIME, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You melted away in slime!")), "") MSG_CENTER_NOTIF(DEATH_SELF_SUICIDE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_TEAMCHANGE, N_ENABLE, 0, 1, "death_team", CPID_Null, "0 0", BOLD(_("^BGYou are now on: %s")), "") MSG_CENTER_NOTIF(DEATH_SELF_TOUCHEXPLODE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_TURRET, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were fragged by a turret!")), BOLD(_("^K1You had an unfortunate run in with a turret!"))) MSG_CENTER_NOTIF(DEATH_SELF_TURRET_EWHEEL
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_CRUSH, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were crushed by a vehicle!")), "") MSG_CENTER_NOTIF(DEATH_SELF_VH_RAPT_BOMB
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_RAPT_DEATH, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You got caught in the blast of a Raptor explosion!")), "") MSG_CENTER_NOTIF(DEATH_SELF_VH_SPID_DEATH
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_SPID_ROCKET, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You were blasted to bits by a Spiderbot rocket!")), "") MSG_CENTER_NOTIF(DEATH_SELF_VH_WAKI_DEATH
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_WAKI_ROCKET, N_ENABLE, 0, 0, "", CPID_Null, "0 0", BOLD(_("^K1You couldn't find shelter from a Racer rocket!")), "") MSG_CENTER_NOTIF(DEATH_SELF_VOID
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_TEAMKILL_FRAG, N_ENABLE, 1, 0, "s1", CPID_Null, "0 0", BOLD(_("^K1Traitor! You team killed ^BG%s")), BOLD(_("^K1Traitor! You betrayed team mate ^BG%s"))) MSG_CENTER_NOTIF(DEATH_TEAMKILL_FRAGGED
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (MOVETOSPEC_IDLING, N_ENABLE, 0, 1, "", CPID_IDLING, "1 f1", BOLD(_("^K1Stop idling!\BGMoving to spectators in ^COUNT...")), "") MSG_CENTER_NOTIF(MISSING_PLAYERS
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (INSTAGIB_FINDAMMO_FIRST, N_ENABLE, 0, 0, "", CPID_INSTAGIB_FINDAMMO, "1 10", _("^BGGet some ammo or you'll be dead in ^F4^COUNT^BG!"), _("^BGGet some ammo! ^F4^COUNT^BG left!")) MSG_CENTER_NOTIF(CAMPAIGN_MESSAGE
MSG_INFO_NOTIF (DEATH_MURDER_BUFF, N_CONSOLE, 3, 3, "spree_inf s1 s2 f3buffname s3loc spree_end", "s2 s1", "notify_death", _("^BG%s%s^K1 was killed by ^BG%s^K1's ^BG%s^K1 buff ^K1%s%s"), _("^BG%s%s^K1 was scored against by ^BG%s^K1's ^BG%s^K1 buff ^K1%s%s")) MSG_INFO_NOTIF(DEATH_MURDER_FIRE
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points MULTIICON_INFO (MINIGAME_INVITE, N_CONSOLE, 2, 0, "s2 minigame1_name s1", "s2", "minigame1_d", "minigames/%s/icon_notif", _("^F4You have been invited by ^BG%s^F4 to join their game of ^F2%s^F4 (^F1%s^F4)"), "") MSG_INFO_NOTIF(VERSION_BETA
FLAG s1 s2 s1 s2 MULTITEAM_CENTER (CTF_PICKUP_TEAM_VERBOSE, N_ENABLE, 2, 0, "s1 s2 s1", CPID_CTF_LOWPRIO, "0 0", _("^BGYour %steam mate (^BG%s%s)^BG got the ^TC^TT^BG flag! Protect them!"), "", FLAG) MSG_CENTER_NOTIF(CTF_PICKUP_TEAM_VERBOSE_NEUTRAL
string multiteam_info_sprintf (string input, string teamname)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 strcat (_("Level %s: "), "^BG%s\3\, _("^BGPress ^F2%s^BG to enter the game"))
spree_cen s1 VERBOSE_MURDER (FRAG2)) MSG_CENTER_NOTIF(DEATH_MURDER_FRAGGED_FIRE_VERBOSE
spree_cen s1 VERBOSE_MURDER (FRAG)
spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FIRE2)) MSG_CENTER_NOTIF(DEATH_MURDER_FRAG_FIRE_VERBOSE
spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FIRE)
spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FIRE2)) MSG_CENTER_NOTIF(DEATH_MURDER_FRAGGED_FREEZE_VERBOSE
spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FIRE)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FREEZE)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FREEZE2)) MSG_CENTER_NOTIF(DEATH_MURDER_FRAG_FREEZE_VERBOSE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FREEZE2)) MSG_CENTER_NOTIF(DEATH_MURDER_TYPEFRAGGED_VERBOSE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FREEZE)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAGGED2)) MSG_CENTER_NOTIF(DEATH_MURDER_TYPEFRAG_VERBOSE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAGGED)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAG)
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAG2)) MSG_CENTER_NOTIF(DEATH_SELF_AUTOTEAMCHANGE
Variables
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 CPID_CAMPAIGN_MESSAGE
CPID_CTF_LOWPRIO
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 CPID_IDLING
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 CPID_MISSING_PLAYERS
spree_cen s1 CPID_Null
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 death_team
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points f2
spree_cen s1 frag_ping
spree_cen s1 spree_cen s1 frag_stats
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 join_key
N_CONSOLE
N_ENABLE
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc nade_ice
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 nade_napalm
spree_inf s1 s2 s3loc s2 notify_death
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc notify_fall
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc notify_lava
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc notify_outofammo
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 notify_telefrag
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc notify_water
spree_inf s1 s2 s3loc s2 s1
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points s1 s2
spree_inf s1 s2 s3loc spree_end
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc spree_lost
Macro Definition Documentation
A__NEVER
#define A__NEVER 0
A_ALWAYS
#define A_ALWAYS 2
A_WARMUP
#define A_WARMUP 1
BOLD
#define BOLD (translatable_msg) strcat(BOLD_OPERATOR, translatable_msg)
Definition at line 93 of file all.inc.
MULTITEAM_ANNCE
#define MULTITEAM_ANNCE (prefix, defaultvalue, sound, channel, volume, position)
Value:
NOTIF_ADD_AUTOCVAR(ANNCE_##prefix, defaultvalue) \
    MSG_ANNCE_NOTIF_TEAM(NUM_TEAM_1, prefix##_RED, prefix, defaultvalue, sprintf(sound, strtolower(STATIC_NAME_TEAM_1)), channel, volume, position) \
    MSG_ANNCE_NOTIF_TEAM(NUM_TEAM_2, prefix##_BLUE, prefix, defaultvalue, sprintf(sound, strtolower(STATIC_NAME_TEAM_2)), channel, volume, position) \
    MSG_ANNCE_NOTIF_TEAM(NUM_TEAM_3, prefix##_YELLOW, prefix, defaultvalue, sprintf(sound, strtolower(STATIC_NAME_TEAM_3)), channel, volume, position) \
    MSG_ANNCE_NOTIF_TEAM(NUM_TEAM_4, prefix##_PINK, prefix, defaultvalue, sprintf(sound, strtolower(STATIC_NAME_TEAM_4)), channel, volume, position)
Definition at line 101 of file all.inc.
MULTITEAM_CENTER
#define MULTITEAM_CENTER (prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, normal, gentle, type)
Value:
NOTIF_ADD_AUTOCVAR(CENTER_##prefix, defaultvalue) \
    MSG_CENTER_NOTIF_TEAM(NUM_TEAM_1, prefix##_RED, prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, TCR(normal, type, 1), TCR(gentle, type, 1)) \
    MSG_CENTER_NOTIF_TEAM(NUM_TEAM_2, prefix##_BLUE, prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, TCR(normal, type, 2), TCR(gentle, type, 2)) \
    MSG_CENTER_NOTIF_TEAM(NUM_TEAM_3, prefix##_YELLOW, prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, TCR(normal, type, 3), TCR(gentle, type, 3)) \
    MSG_CENTER_NOTIF_TEAM(NUM_TEAM_4, prefix##_PINK, prefix, defaultvalue, strnum, flnum, args, cpid, durcnt, TCR(normal, type, 4), TCR(gentle, type, 4))
Definition at line 515 of file all.inc.
MULTITEAM_CHOICE
#define MULTITEAM_CHOICE (prefix, defaultvalue, challow, chtype, optiona, optionb)
Value:
NOTIF_ADD_AUTOCVAR(CHOICE_##prefix, defaultvalue) \
    NOTIF_ADD_AUTOCVAR(CHOICE_##prefix##_ALLOWED, challow) \
    MSG_CHOICE_NOTIF_TEAM(NUM_TEAM_1, prefix##_RED, prefix, defaultvalue, challow, chtype, optiona##_RED, optionb##_RED) \
    MSG_CHOICE_NOTIF_TEAM(NUM_TEAM_2, prefix##_BLUE, prefix, defaultvalue, challow, chtype, optiona##_BLUE, optionb##_BLUE) \
    MSG_CHOICE_NOTIF_TEAM(NUM_TEAM_3, prefix##_YELLOW, prefix, defaultvalue, challow, chtype, optiona##_YELLOW, optionb##_YELLOW) \
    MSG_CHOICE_NOTIF_TEAM(NUM_TEAM_4, prefix##_PINK, prefix, defaultvalue, challow, chtype, optiona##_PINK, optionb##_PINK)
MULTITEAM_INFO
#define MULTITEAM_INFO (prefix, defaultvalue, strnum, flnum, args, hudargs, icon, normal, gentle, type)
Value:
NOTIF_ADD_AUTOCVAR(INFO_##prefix, defaultvalue) \
    MSG_INFO_NOTIF_TEAM(NUM_TEAM_1, prefix##_RED, prefix, defaultvalue, strnum, flnum, args, hudargs, multiteam_info_sprintf(icon, strtolower(STATIC_NAME_TEAM_1)), TCR(normal, type, 1), TCR(gentle, type, 1)) \
    MSG_INFO_NOTIF_TEAM(NUM_TEAM_2, prefix##_BLUE, prefix, defaultvalue, strnum, flnum, args, hudargs, multiteam_info_sprintf(icon, strtolower(STATIC_NAME_TEAM_2)), TCR(normal, type, 2), TCR(gentle, type, 2)) \
    MSG_INFO_NOTIF_TEAM(NUM_TEAM_3, prefix##_YELLOW, prefix, defaultvalue, strnum, flnum, args, hudargs, multiteam_info_sprintf(icon, strtolower(STATIC_NAME_TEAM_3)), TCR(normal, type, 3), TCR(gentle, type, 3)) \
    MSG_INFO_NOTIF_TEAM(NUM_TEAM_4, prefix##_PINK, prefix, defaultvalue, strnum, flnum, args, hudargs, multiteam_info_sprintf(icon, strtolower(STATIC_NAME_TEAM_4)), TCR(normal, type, 4), TCR(gentle, type, 4))
Definition at line 218 of file all.inc.
MULTITEAM_MULTI
#define MULTITEAM_MULTI (prefix, defaultvalue, anncepre, infopre, centerpre)
Value:
MSG_MULTI_NOTIF(prefix##_RED, defaultvalue, anncepre##_RED, infopre##_RED, centerpre##_RED) \
    MSG_MULTI_NOTIF(prefix##_BLUE, defaultvalue, anncepre##_BLUE, infopre##_BLUE, centerpre##_BLUE) \
    MSG_MULTI_NOTIF(prefix##_YELLOW, defaultvalue, anncepre##YELLOW, infopre##YELLOW, centerpre##YELLOW) \
    MSG_MULTI_NOTIF(prefix##_PINK, defaultvalue, anncepre##PINK, infopre##PINK, centerpre##PINK)
MURDER_FRAG
#define MURDER_FRAG BOLD(_("^K3%sYou fragged ^BG%s"))
Definition at line 576 of file all.inc.
MURDER_FRAG2
#define MURDER_FRAG2 BOLD(_("^K3%sYou scored against ^BG%s"))
Definition at line 577 of file all.inc.
MURDER_FRAG_FIRE
#define MURDER_FRAG_FIRE BOLD(_("^K3%sYou burned ^BG%s"))
MURDER_FRAG_FIRE2
#define MURDER_FRAG_FIRE2 BOLD(_("^K3%sYou scored against ^BG%s"))
MURDER_FRAG_FREEZE
#define MURDER_FRAG_FREEZE BOLD(_("^K3%sYou froze ^BG%s"))
MURDER_FRAG_FREEZE2
#define MURDER_FRAG_FREEZE2 BOLD(_("^K3%sYou scored against ^BG%s"))
MURDER_FRAGGED
#define MURDER_FRAGGED BOLD(_("^K1%sYou were fragged by ^BG%s"))
Definition at line 578 of file all.inc.
MURDER_FRAGGED2
#define MURDER_FRAGGED2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
Definition at line 579 of file all.inc.
MURDER_FRAGGED_FIRE
#define MURDER_FRAGGED_FIRE BOLD(_("^K1%sYou were burned by ^BG%s"))
MURDER_FRAGGED_FIRE2
#define MURDER_FRAGGED_FIRE2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
MURDER_FRAGGED_FREEZE
#define MURDER_FRAGGED_FREEZE BOLD(_("^K1%sYou were frozen by ^BG%s"))
MURDER_FRAGGED_FREEZE2
#define MURDER_FRAGGED_FREEZE2 BOLD(_("^K1%sYou were scored against by ^BG%s"))
MURDER_TYPEFRAG
#define MURDER_TYPEFRAG BOLD(_("^K1%sYou typefragged ^BG%s"))
MURDER_TYPEFRAG2
#define MURDER_TYPEFRAG2 BOLD(_("^K1%sYou scored against ^BG%s^K1 while they were typing"))
MURDER_TYPEFRAGGED
#define MURDER_TYPEFRAGGED BOLD(_("^K1%sYou were typefragged by ^BG%s"))
MURDER_TYPEFRAGGED2
#define MURDER_TYPEFRAGGED2 BOLD(_("^K1%sYou were scored against by ^BG%s^K1 while typing"))
N___NEVER
#define N___NEVER 0
Definition at line 97 of file all.inc.
N__ALWAYS
#define N__ALWAYS 2
Definition at line 99 of file all.inc.
N__NORMAL
#define N__NORMAL 1
N_CHATCON
#define N_CHATCON 2
Definition at line 213 of file all.inc.
N_CONSOLE
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points N_CONSOLE 1
Definition at line 212 of file all.inc.
N_DISABL [1/2]
#define N_DISABL 0
Definition at line 512 of file all.inc.
N_DISABL [2/2]
#define N_DISABL 0
Definition at line 512 of file all.inc.
N_DISABLE [1/2]
#define N_DISABLE 0
Definition at line 211 of file all.inc.
N_DISABLE [2/2]
#define N_DISABLE 0
Definition at line 211 of file all.inc.
N_ENABLE [1/2]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 N_ENABLE 1
Definition at line 513 of file all.inc.
N_ENABLE [2/2]
#define N_ENABLE 1
Definition at line 513 of file all.inc.
N_GNTLOFF
#define N_GNTLOFF 1
Definition at line 98 of file all.inc.
N_VERBOSE
#define N_VERBOSE 2
VERBOSE_MURDER
#define VERBOSE_MURDER (type) strcat(MURDER_##type, "^BG%s")
Definition at line 574 of file all.inc.
Function Documentation
BOLD() [1/35]
BOLD (_("^BGYou got the ^TC^TT^BG flag!"))
BOLD() [2/35]
FLAG BOLD (_("^BGYou got your %steam^BG's flag, return it!"))
BOLD() [3/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^BGYou have been moved into a different team\You are now on: %s"))
BOLD() [4/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Die camper!"))
BOLD() [5/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Reconsider your tactics, camper!"))
BOLD() [6/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You unfairly eliminated yourself!"))
BOLD() [7/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You couldn't catch your breath!"))
BOLD() [8/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got a little bit too crispy!"))
BOLD() [9/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You felt a little too hot!"))
BOLD() [10/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You fragged yourself!"))
BOLD() [11/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You need to be more careful!"))
BOLD() [12/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You couldn't stand the heat!"))
BOLD() [13/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You forgot to put the pin back in!"))
BOLD() [14/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Tastes like chicken!"))
BOLD() [15/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Hanging around a napalm explosion is bad!"))
BOLD() [16/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Your Healing Nade is a bit defective"))
BOLD() [17/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You grew too old without taking your medicine"))
BOLD() [18/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You need to preserve your health"))
BOLD() [19/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You became a shooting star!"))
BOLD() [20/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You committed suicide!"))
BOLD() [21/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You ended it all!"))
BOLD() [22/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got stuck in a swamp!"))
BOLD() [23/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You died in an accident!"))
BOLD() [24/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were fragged by an eWheel turret!"))
BOLD() [25/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You had an unfortunate run in with an eWheel turret!"))
BOLD() [26/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You had an unfortunate run in with a Walker turret!"))
BOLD() [27/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were fragged by a Walker turret!"))
BOLD() [28/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Bumblebee explosion!"))
BOLD() [29/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were caught in a Raptor cluster bomb!"))
BOLD() [30/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Spiderbot explosion!"))
BOLD() [31/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You got caught in the blast of a Racer explosion!"))
BOLD() [32/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Watch your step!"))
BOLD() [33/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were team killed by ^BG%s"))
BOLD() [34/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1You were betrayed by team mate ^BG%s"))
BOLD() [35/35]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 BOLD (_("^K1Stop idling!\^BGDisconnecting in ^COUNT..."))
MSG_CENTER_NOTIF() [1/21]
MSG_CENTER_NOTIF (CTF_CAPTURESHIELD_SHIELDED , N_ENABLE , 0 , 0 , "" , CPID_CTF_CAPSHIELD , "0 0" , _("^BGYou are now ^F1shielded^BG from the flag(s)\^BGfor ^F2too many unsuccessful attempts^BG to capture.\^BGMake some defensive scores before trying again.") , "")
MSG_CENTER_NOTIF() [2/21]
FLAG MSG_CENTER_NOTIF (CTF_PICKUP_NEUTRAL , N_ENABLE , 0 , 0 , "" , CPID_CTF_LOWPRIO , "0 0" , BOLD(_("^BGYou got the flag!")) , "")
MSG_CENTER_NOTIF() [3/21]
FLAG MSG_CENTER_NOTIF (CTF_PICKUP_RETURN_ENEMY , N_ENABLE , 1 , 0 , "s1" , CPID_CTF_LOWPRIO , "0 0" , BOLD(_("^BGYou got the %senemy^BG's flag, return it!")) , "")
MSG_CENTER_NOTIF() [4/21]
FLAG s1 s2 MSG_CENTER_NOTIF (CTF_PICKUP_ENEMY_NEUTRAL_VERBOSE , N_ENABLE , 2 , 0 , "s1 s2 s1" , CPID_CTF_LOWPRIO , "0 0" , _("^BGThe %senemy (^BG%s%s)^BG got the flag! Retrieve it!") , "")
MSG_CENTER_NOTIF() [5/21]
MSG_CENTER_NOTIF (DEATH_MURDER_FRAGGED_VERBOSE , N_ENABLE , 1 , 4 , "spree_cen s1 frag_stats" , CPID_Null , "0 0" , VERBOSE_MURDER(FRAGGED) , VERBOSE_MURDER(FRAGGED2))
MSG_CENTER_NOTIF() [6/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_BETRAYAL , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were punished for attacking your team mates!")) , "")
MSG_CENTER_NOTIF() [7/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_CUSTOM , N_ENABLE , 2 , 0 , "s2" , CPID_Null , "0 0" , BOLD(_("^K1You were %s")) , "")
MSG_CENTER_NOTIF() [8/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_FALL , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You hit the ground with a crunch!")) , "")
MSG_CENTER_NOTIF() [9/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_MONSTER , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were killed by a monster!")) , BOLD(_("^K1You need to watch out for monsters!")))
MSG_CENTER_NOTIF() [10/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_NADE_ICE_FREEZE , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You got a little bit too cold!")) , BOLD(_("^K1You felt a little chilly!")))
MSG_CENTER_NOTIF() [11/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_NOAMMO , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were killed for running out of ammo...")) , BOLD(_("^K1You are respawning for running out of ammo...")))
MSG_CENTER_NOTIF() [12/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_SLIME , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You melted away in slime!")) , "")
MSG_CENTER_NOTIF() [13/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_TEAMCHANGE , N_ENABLE , 0 , 1 , "death_team" , CPID_Null , "0 0" , BOLD(_("^BGYou are now on: %s")) , "")
MSG_CENTER_NOTIF() [14/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_TURRET , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were fragged by a turret!")) , BOLD(_("^K1You had an unfortunate run in with a turret!")))
MSG_CENTER_NOTIF() [15/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_CRUSH , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were crushed by a vehicle!")) , "")
MSG_CENTER_NOTIF() [16/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_RAPT_DEATH , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You got caught in the blast of a Raptor explosion!")) , "")
MSG_CENTER_NOTIF() [17/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_SPID_ROCKET , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You were blasted to bits by a Spiderbot rocket!")) , "")
MSG_CENTER_NOTIF() [18/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_SELF_VH_WAKI_ROCKET , N_ENABLE , 0 , 0 , "" , CPID_Null , "0 0" , BOLD(_("^K1You couldn't find shelter from a Racer rocket!")) , "")
MSG_CENTER_NOTIF() [19/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (DEATH_TEAMKILL_FRAG , N_ENABLE , 1 , 0 , "s1" , CPID_Null , "0 0" , BOLD(_("^K1Traitor! You team killed ^BG%s")) , BOLD(_("^K1Traitor! You betrayed team mate ^BG%s")))
MSG_CENTER_NOTIF() [20/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (MOVETOSPEC_IDLING , N_ENABLE , 0 , 1 , "" , CPID_IDLING , "1 f1" , BOLD(_("^K1Stop idling!\^BGMoving to spectators in ^COUNT...")) , "")
MSG_CENTER_NOTIF() [21/21]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 MSG_CENTER_NOTIF (INSTAGIB_FINDAMMO_FIRST , N_ENABLE , 0 , 0 , "" , CPID_INSTAGIB_FINDAMMO , "1 10" , _("^BGGet some ammo or you'll be dead in ^F4^COUNT^BG!") , _("^BGGet some ammo! ^F4^COUNT^BG left!"))
MSG_INFO_NOTIF()
MSG_INFO_NOTIF (DEATH_MURDER_BUFF , N_CONSOLE , 3 , 3 , "spree_inf s1 s2 f3buffname s3loc spree_end" , "s2 s1" , "notify_death" , _("^BG%s%s^K1 was killed by ^BG%s^K1's ^BG%s^K1 buff ^K1%s%s") , _("^BG%s%s^K1 was scored against by ^BG%s^K1's ^BG%s^K1 buff ^K1%s%s"))
MULTIICON_INFO()
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points MULTIICON_INFO (MINIGAME_INVITE , N_CONSOLE , 2 , 0 , "s2 minigame1_name s1" , "s2" , "minigame1_d" , "minigames/%s/icon_notif" , _("^F4You have been invited by ^BG%s^F4 to join their game of ^F2%s^F4 (^F1%s^F4)") , "")
MULTITEAM_CENTER()
FLAG s1 s2 s1 s2 MULTITEAM_CENTER (CTF_PICKUP_TEAM_VERBOSE , N_ENABLE , 2 , 0 , "s1 s2 s1" , CPID_CTF_LOWPRIO , "0 0" , _("^BGYour %steam mate (^BG%s%s)^BG got the ^TC^TT^BG flag! Protect them!") , "" , FLAG)
multiteam_info_sprintf()
string multiteam_info_sprintf (string input, string teamname)
Definition at line 216 of file all.inc.
 { return ((input != "") ? sprintf(input, teamname) : ""); }
strcat()
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 strcat (_("Level %s: ") , "^BG%s\3\ , _("^BGPress ^F2%s^BG to enter the game"))
Referenced by _dumptree_open(), _getcommandkey(), _json_parse_array(), _json_parse_float(), _json_parse_int(), _json_parse_pair(), _json_parse_string(), _MapInfo_Generate(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), _Sound_fixpath(), ACCUMULATE_call(), Accuracy_LoadColors(), anticheat_display(), anticheat_register_to_playerstats(), anticheat_report_to_eventlog(), anticheat_report_to_playerstats(), AppendItemcodes(), AuditLists(), Ban_Enforce(), Ban_GetClientIP(), Ban_KickBanClient(), Ban_SaveBans(), Ban_View(), bd_load_level(), bd_save_controller_piece(), bd_save_level(), bd_save_piece(), BGMScript_Init(), BGMScript_InitEntity(), bot_execute_commands_once(), bot_getplace(), bot_setnameandstuff(), buf_save(), Buff::Buff ::display(), buff_Available(), BUFF_NAME(), Button_draw(), c4_move(), Campaign_GetMessage(), Campaign_Invalid(), CampaignFile_Load(), CampaignPreInit(), CampaignPreIntermission(), CampaignSaveCvar(), CategoryForEntry(), CheatCommand(), CheckBox_toString(), checkpoint_passed(), CL_ExteriorWeaponentity_Think(), ClientCommand_autoswitch(), ClientCommand_minigame(), ClientCommand_physics(), ClientCommand_sentcvar(), ClientCommand_suggestmap(), ClientCommand_tell(), ClientConnect(), ClientDisconnect(), Cmd_Scoreboard_SetFields(), ColorTranslateRGB(), CommonCommand_cvar_changes(), CommonCommand_cvar_purechanges(), CommonCommand_editmob(), CommonCommand_info(), CommonCommand_ladder(), CommonCommand_lsmaps(), CommonCommand_printmaplist(), CommonCommand_rankings(), CommonCommand_records(), CommonCommand_teamstatus(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), cons(), cons_mid(), CSQC_Init(), CSQCPlayer_LOD_Apply(), ctf_CaptureRecord(), ctf_Initialize(), cts_EventLog(), cvar_changes_init(), CvarList_Revert_Click(), CvarList_Value_Change(), DamageText::DamageText_update(), db_dump(), db_save(), DemoList_Filter_Change(), dialog_hudpanel_main_checkbox(), dom_EventLog(), draw_cursor(), draw_teamradar_icon(), draw_UseSkinFor(), drawBackground(), DrawDomItem(), DumpStats(), end_minigame(), FindConnectedComponent(), FixPlayermodel(), fixPriorityList(), formatmessage(), fstrunzone(), GameCommand(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_bot_cmd(), GameCommand_cointoss(), GameCommand_defer_clear_all(), GameCommand_gettaginfo(), GameCommand_moveplayer(), GameCommand_nospectators(), GameCommand_stuffto(), GameLogEcho(), Gametype::Gametype ::display(), GameType_GetIcon(), GameTypeVote_AvailabilityStatus(), GameTypeVote_ReadOption(), GameTypeVote_SendOption(), GameTypeVote_Type_FromString(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_maplist(), GenericCommand_markup(), GenericCommand_rpn(), get_model_datafilename(), get_model_parameters(), get_monster_model_datafilename(), getAllHUDSkins(), GetAmmoConsumptionQ3(), GetClientErrorString_color(), GetClientVersionMessage(), GetCvars_handleFloat(), GetCvars_handleFloatOnce(), GetCvars_handleString(), getDemos_for_ext(), getHUDSkinFiles(), getladder(), GetLengthUnit(), GetPlayerScoreString(), getrankings(), GetScoreLogLabel(), getScreenshots_for_ext(), GetSpeedUnit(), GetTeamScoreString(), gettooltip(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), GoalTouch(), HUD_Chat(), HUD_Crosshair(), HUD_Main(), HUD_Minigame_InputEvent(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), HUD_Mod_Race(), HUD_mouse_over(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), HUD_Panel_ExportCfg(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_LoadCvars(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Quickmenu_DrawEntry(), HUD_Quickmenu_PlayerListEntries(), HUD_RaceTimer(), HUD_Radar(), HUD_Radar_InputEvent(), HUD_Score(), HUD_StrafeHUD(), HUD_Weapons(), HUDSkinList_Filter_Change(), InitializeEntitiesRun(), InputBox_draw(), InputBox_enterText(), InputBox_keyDown(), InstantAction_LoadMap(), invite_minigame(), isGametypeInFilter(), Item_Model(), Item_Sound(), json_parse(), ka_EventLog(), KeyBinder_Bind_Edit(), kh_Scores_Event(), kh_WinnerTeam(), language_filename(), ListBox_draw(), LoadMenuSkinValues(), LoadPlayerSounds(), Local_Notification_sprintf(), LocalCommand_create_scrshot_ent(), LocalCommand_handlevote(), LogDeath(), LogNB(), m_init_delayed(), M_Model(), MakeRaceString(), Map_Filename(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapInfo_LoadMap(), MapList_Add_All(), MaplistMethod_Shuffle(), mapPriorityList(), MapVote_AddVotable(), MapVote_CheckPK3(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_InputEvent(), MapVote_ReadOption(), MapVote_SendChoice(), MapVote_SendPicture(), MapVote_Suggest(), markdown(), minigame_addplayer(), minigame_cmd_workaround(), minigame_getWrappedLine(), minigame_rmplayer(), minigame_tile_buildname(), mmsss(), mmssss(), Monster_Sound_Precache(), Monster_Sounds_Load(), Monster_Sounds_Precache(), MUTATOR_HOOKFUNCTION(), MX_Handle(), MX_Messages_(), MX_Sync(), MX_Sync_(), nmm_in_mill(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), nt_GetReplacement(), Obituary(), OnlineBanList_SendBan(), OnlineBanList_SendUnban(), OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), PlayerPreThink(), PlayerScore_Add(), PlayerScore_PlayerStats(), PlayerScore_TeamStats(), pp_next_match(), prandom(), precache_playermodel(), PrecachePlayerSounds(), PreviewExists(), print_available_commands_to(), print_to(), PrintToChat(), PrintToChatAll(), PrintToChatTeam(), Process_Notif_Line(), process_time(), PutPlayerInServer(), queue_to_execute_next_frame(), QuickMenu_ActionForNumber(), QuickMenu_Open(), race_checkAndWriteName(), race_deleteTime(), race_EventLog(), race_readName(), race_readTime(), race_readUID(), race_SendAll(), race_SpeedAwardFrame(), race_writeTime(), readlevelcvars(), readplayerstartcvars(), RedirectionThink(), RestoreGame(), rewrapCampaign(), rgb_to_hexcolor(), sandbox_Database_Load(), sandbox_Database_Save(), sandbox_ObjectFunction_Touch(), sandbox_ObjectPort_Save(), Say(), Score_NicePrint_Player(), Score_NicePrint_Spectator(), Score_NicePrint_Team(), Scoreboard_AddPlayerId(), Scoreboard_Draw(), ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScreenshotList_Filter_Change(), ServerList_TypeSort_Click(), Shutdown(), Slider_draw(), SpawnBall(), spawnfunc(), start_minigame(), STATIC_INIT(), StrafeHUD_CenterPanel(), strftime_s(), superspec_msg(), SV_ParseClientCommand(), swapInPriorityList(), swapwords(), sys_phys_fixspeed(), TEST_Run(), textShortenToLength(), textShortenToWidth(), trigger_race_checkpoint_verify(), ttt_next_match(), turret_gibboom(), uid2name(), unescape(), ValidateMap(), Vehicles_drawHUD(), View_CheckButtonStatus(), View_DemoCamera(), View_PostProcessing(), VoteAccept(), VoteCommand(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_checkargs(), VoteCommand_checkinlist(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_no(), VoteCommand_parse(), VoteCommand_status(), VoteCommand_stop(), VoteCommand_yes(), VoteSpam(), VoteStop(), W_FixWeaponOrder_BuildImpulseList(), W_FixWeaponOrder_BuildImpulseList_cmp(), W_HitPlotAnalysis(), W_HitPlotOpen(), W_Model(), W_Reload(), W_Sound(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_load_hardwiredlinks(), waypoint_load_links(), waypoint_loadall(), waypoint_remove_fromeditor(), waypoint_save_hardwiredlinks(), waypoint_save_links(), waypoint_saveall(), waypoint_spawn_fromeditor(), weapon_defaultspawnfunc(), WeaponStats_ready(), WinningConditionHelper(), wordwrap(), wordwrap_buffer_put(), write_recordmarker(), xencode(), XonoticCampaignList_campaignGo(), XonoticCampaignList_drawListBoxItem(), XonoticCampaignList_loadCvars(), XonoticColorpicker_draw(), XonoticColorpicker_mouseDrag(), XonoticColorpickerString_draw(), XonoticColorpickerString_loadCvars(), XonoticColorpickerString_saveCvars(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_configureXonoticCrosshairPreview(), XonoticCrosshairPreview_draw(), XonoticCvarList_updateCvarType(), XonoticHUDSkinList_drawListBoxItem(), XonoticHUDSkinList_setHUDSkin(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_editUserbind(), XonoticMapInfoDialog_loadMapInfo(), XonoticMapList_drawListBoxItem(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticPlayerModelSelector_loadModels(), XonoticPlayList_addToPlayList(), XonoticPlayList_removeSelectedFromPlayList(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_loadCvars(), XonoticScreenshotList_goScreenshot(), XonoticScreenshotList_previewScreenshot(), XonoticScreenshotList_startScreenshot(), XonoticServerList_drawListBoxItem(), XonoticServerList_refreshServerList(), XonoticSoundList_getSounds(), XonoticTextSlider_loadCvars(), XonoticTextSlider_saveCvars(), XonoticWeaponarenaCheckBox_saveCvars(), XonoticWeaponsList_drawListBoxItem(), and XonoticWeaponsList_toString().
VERBOSE_MURDER() [1/14]
spree_cen s1 VERBOSE_MURDER (FRAG2)
VERBOSE_MURDER() [2/14]
spree_cen s1 VERBOSE_MURDER (FRAG)
VERBOSE_MURDER() [3/14]
spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FIRE2)
VERBOSE_MURDER() [4/14]
spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FIRE)
VERBOSE_MURDER() [5/14]
spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FIRE2)
VERBOSE_MURDER() [6/14]
spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FIRE)
VERBOSE_MURDER() [7/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FREEZE)
VERBOSE_MURDER() [8/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAGGED_FREEZE2)
VERBOSE_MURDER() [9/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FREEZE2)
VERBOSE_MURDER() [10/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (FRAG_FREEZE)
VERBOSE_MURDER() [11/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAGGED2)
VERBOSE_MURDER() [12/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAGGED)
VERBOSE_MURDER() [13/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAG)
VERBOSE_MURDER() [14/14]
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 VERBOSE_MURDER (TYPEFRAG2)
Variable Documentation
CPID_CAMPAIGN_MESSAGE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 CPID_CAMPAIGN_MESSAGE
Definition at line 715 of file all.inc.
Referenced by PrintWelcomeMessage().
CPID_CTF_LOWPRIO
FLAG s1 s2 s1 s2 s1 s2 CPID_CTF_LOWPRIO
Definition at line 555 of file all.inc.
CPID_IDLING
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 CPID_IDLING
Definition at line 654 of file all.inc.
Referenced by PlayerPostThink(), and SetPlayerTeam().
CPID_MISSING_PLAYERS
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 CPID_MISSING_PLAYERS
Definition at line 708 of file all.inc.
CPID_Null
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 CPID_Null
Definition at line 583 of file all.inc.
Referenced by Create_Notification_Entity_InfoCenter(), Destroy_All_Notifications(), Local_Notification_WOVA(), and NextLevel().
death_team
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 death_team
Definition at line 615 of file all.inc.
f1
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1
Definition at line 654 of file all.inc.
Referenced by GameCommand_animbench(), GENERIC_COMMAND(), havocbot_ctf_calculate_middlepoint(), lag_additem(), lerp3ratio(), lerpv3ratio(), and Local_Notification_sprintf().
f2
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points f2
Definition at line 348 of file all.inc.
Referenced by GameCommand_animbench(), GENERIC_COMMAND(), GenericCommand_rpn(), havocbot_ctf_calculate_middlepoint(), lag_additem(), Local_Notification_sprintf(), and sys_phys_simulate().
frag_ping
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 frag_ping
Definition at line 583 of file all.inc.
frag_stats
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 frag_stats
Definition at line 591 of file all.inc.
join_key
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 f1 s1 join_key
Definition at line 715 of file all.inc.
N_CONSOLE
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points N_CONSOLE
Definition at line 265 of file all.inc.
N_ENABLE
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 N_ENABLE
Definition at line 555 of file all.inc.
nade_ice
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc nade_ice
Definition at line 313 of file all.inc.
nade_napalm
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc nade_napalm
Definition at line 269 of file all.inc.
notify_death
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc notify_death
Definition at line 265 of file all.inc.
notify_fall
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc notify_fall
Definition at line 298 of file all.inc.
notify_lava
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc notify_lava
Definition at line 301 of file all.inc.
notify_outofammo
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc notify_outofammo
Definition at line 315 of file all.inc.
notify_telefrag
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 notify_telefrag
Definition at line 276 of file all.inc.
notify_water
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc notify_water
Definition at line 297 of file all.inc.
s1
spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 spree_cen s1 s1
Definition at line 265 of file all.inc.
Referenced by GENERIC_COMMAND(), Local_Notification_sprintf(), ons_ControlPoint_UpdateSprite(), ons_Generator_UpdateSprite(), swapwords(), vercmp_recursive(), and XonoticGametypeList_drawListBoxItem().
s2
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2 f1 f1points s1 s2
Definition at line 438 of file all.inc.
Referenced by bot_getplace(), ctf_CaptureShield_CheckStatus(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_rpn(), Local_Notification_sprintf(), Score_NicePrint_Team(), swapwords(), vercmp_recursive(), XonoticGametypeList_drawListBoxItem(), and XonoticHUDSkinList_drawListBoxItem().
spree_end
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc spree_end
Definition at line 265 of file all.inc.
spree_lost
spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 spree_inf s1 s2 s3loc s2 s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc s1 s2loc spree_lost
Definition at line 297 of file all.inc.