Xonotic: server/mutators/mutator/gamemode_lms.qc File Reference
gamemode_lms.qc File Reference
#include "gamemode_lms.qh"
#include <common/mutators/mutator/instagib/items.qc>
#include <server/campaign.qh>
#include <server/command/_mod.qh>
Functions
void ClearWinners ()
void lms_extralife (entity this)
void lms_Initialize ()
float LMS_NewPlayerLives ()
void lms_RemovePlayer (entity player)
void lms_ScoreRules ()
MUTATOR_HOOKFUNCTION (lms, reset_map_global)
MUTATOR_HOOKFUNCTION (lms, reset_map_players)
MUTATOR_HOOKFUNCTION (lms, PutClientInServer)
MUTATOR_HOOKFUNCTION (lms, ForbidSpawn)
MUTATOR_HOOKFUNCTION (lms, PlayerDies)
MUTATOR_HOOKFUNCTION (lms, ClientDisconnect)
MUTATOR_HOOKFUNCTION (lms, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (lms, ClientConnect)
MUTATOR_HOOKFUNCTION (lms, PlayerPreThink)
MUTATOR_HOOKFUNCTION (lms, PlayerRegen)
MUTATOR_HOOKFUNCTION (lms, ForbidThrowCurrentWeapon)
MUTATOR_HOOKFUNCTION (lms, GiveFragsForKill)
MUTATOR_HOOKFUNCTION (lms, SetStartItems)
MUTATOR_HOOKFUNCTION (lms, ForbidPlayerScore_Clear)
MUTATOR_HOOKFUNCTION (lms, FilterItem)
MUTATOR_HOOKFUNCTION (lms, OnEntityPreSpawn)
MUTATOR_HOOKFUNCTION (lms, ItemTouch)
MUTATOR_HOOKFUNCTION (lms, Bot_FixCount, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (lms, ClientCommand_Spectate)
MUTATOR_HOOKFUNCTION (lms, CheckRules_World)
MUTATOR_HOOKFUNCTION (lms, WantWeapon)
MUTATOR_HOOKFUNCTION (lms, GetPlayerStatus)
MUTATOR_HOOKFUNCTION (lms, AddPlayerScore)
int WinningCondition_LMS ()
Variables
int autocvar_g_lms_extra_lives
bool autocvar_g_lms_join_anytime
int autocvar_g_lms_last_join
bool autocvar_g_lms_regenerate
Function Documentation
void ClearWinners ()
Definition at line 1692 of file g_world.qc.
References FOREACH_CLIENT, IS_PLAYER, and LAMBDA.
Referenced by CheckRules_World(), WinningCondition_LMS(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(it.winning = 0));
 }
void lms_extralife (entity this)
Definition at line 327 of file gamemode_lms.qc.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     StartItem(this, ITEM_ExtraLife);
 }
void lms_Initialize ()
Definition at line 431 of file gamemode_lms.qc.
References lms_lowest_lives, and lms_ScoreRules().
Referenced by REGISTER_MUTATOR().
 {
     lms_lowest_lives = 9999;
     lms_ScoreRules();
 }
float LMS_NewPlayerLives ()
Definition at line 13 of file gamemode_lms.qc.
References autocvar_fraglimit, autocvar_g_lms_join_anytime, autocvar_g_lms_last_join, bound(), and lms_lowest_lives.
Referenced by MUTATOR_HOOKFUNCTION(), and WinningCondition_LMS().
 {
     float fl;
     fl = autocvar_fraglimit;
     if(fl == 0)
         fl = 999;
     // first player has left the game for dying too much? Nobody else can get in.
     if(lms_lowest_lives < 1)
         return 0;
     if(!autocvar_g_lms_join_anytime)
         if(lms_lowest_lives < fl - autocvar_g_lms_last_join)
             return 0;
     return bound(1, lms_lowest_lives, fl);
 }
void lms_RemovePlayer (entity player)
Definition at line 169 of file gamemode_lms.qc.
References bot_clear(), FOREACH_CLIENT, FRAGS_LMS_LOSER, FRAGS_SPECTATOR, IS_BOT_CLIENT, IS_PLAYER, lms_lowest_lives, PlayerScore_Add(), TRANSMUTE(), and warmup_stage.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     static int quitters = 0;
     float player_rank = PlayerScore_Add(player, SP_LMS_RANK, 0);
     if (!player_rank)
     {
         int pl_cnt = 0;
         FOREACH_CLIENT(IS_PLAYER(it), { pl_cnt++; });
         if (player.lms_spectate_warning != 2)
         {
             if(IS_BOT_CLIENT(player))
                 bot_clear(player);
             player.frags = FRAGS_LMS_LOSER;
             PlayerScore_Add(player, SP_LMS_RANK, pl_cnt + 1);
         }
         else
         {
             lms_lowest_lives = 999;
             FOREACH_CLIENT(true, {
                 if (it.frags == FRAGS_LMS_LOSER)
                 {
                     float it_rank = PlayerScore_Add(it, SP_LMS_RANK, 0);
                     if (it_rank > player_rank && it_rank <= 256)
                         PlayerScore_Add(it, SP_LMS_RANK, -1);
                     lms_lowest_lives = 0;
                 }
                 else if (it.frags != FRAGS_SPECTATOR)
                 {
                     float tl = PlayerScore_Add(it, SP_LMS_LIVES, 0);
                     if(tl < lms_lowest_lives)
                         lms_lowest_lives = tl;
                 }
             });
             PlayerScore_Add(player, SP_LMS_RANK, 665 - quitters); // different from 666
             if(!warmup_stage)
             {
                 PlayerScore_Add(player, SP_LMS_LIVES, -PlayerScore_Add(player, SP_LMS_LIVES, 0));
                 ++quitters;
             }
             player.frags = FRAGS_LMS_LOSER;
             TRANSMUTE(Observer, player);
         }
         if (pl_cnt == 2 && !warmup_stage) // a player is forfeiting leaving only one player
             lms_lowest_lives = 0; // end the game now!
     }
     if(player.killcount != FRAGS_SPECTATOR)
         if(PlayerScore_Add(player, SP_LMS_RANK, 0) > 0 && player.lms_spectate_warning != 2)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_LMS_NOLIVES, player.netname);
         else
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_LMS_FORFEIT, player.netname);
 }
void lms_ScoreRules ()
Definition at line 423 of file gamemode_lms.qc.
References ScoreInfo_SetLabel_PlayerScore(), ScoreRules_basics(), ScoreRules_basics_end(), SFL_ALLOW_HIDE, SFL_LOWER_IS_BETTER, SFL_RANK, SFL_SORT_PRIO_PRIMARY, and SFL_SORT_PRIO_SECONDARY.
Referenced by lms_Initialize().
 {
     ScoreRules_basics(0, 0, 0, false);
     ScoreInfo_SetLabel_PlayerScore(SP_LMS_LIVES,    "lives",     SFL_SORT_PRIO_SECONDARY);
     ScoreInfo_SetLabel_PlayerScore(SP_LMS_RANK,     "rank",      SFL_LOWER_IS_BETTER | SFL_RANK | SFL_SORT_PRIO_PRIMARY | SFL_ALLOW_HIDE);
     ScoreRules_basics_end();
 }
MUTATOR_HOOKFUNCTION (lms , reset_map_global)
Definition at line 113 of file gamemode_lms.qc.
References lms_lowest_lives.
 {
     lms_lowest_lives = 999;
 }
MUTATOR_HOOKFUNCTION (lms , reset_map_players)
Definition at line 118 of file gamemode_lms.qc.
References FOREACH_CLIENT, FRAGS_PLAYER, LMS_NewPlayerLives(), PlayerScore_Add(), PutClientInServer(), and TRANSMUTE().
 {
     FOREACH_CLIENT(true, {
         TRANSMUTE(Player, it);
         it.frags = FRAGS_PLAYER;
         PlayerScore_Add(it, SP_LMS_LIVES, LMS_NewPlayerLives());
         PutClientInServer(it);
     });
 }
MUTATOR_HOOKFUNCTION (lms , PutClientInServer)
Definition at line 128 of file gamemode_lms.qc.
References entity(), FRAGS_SPECTATOR, lms_lowest_lives, M_ARGV, PlayerScore_Add(), TRANSMUTE(), and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(player.frags == FRAGS_SPECTATOR)
         TRANSMUTE(Observer, player);
     else
     {
         float tl = PlayerScore_Add(player, SP_LMS_LIVES, 0);
         if(tl < lms_lowest_lives)
             lms_lowest_lives = tl;
         if(tl <= 0)
             TRANSMUTE(Observer, player);
         if(warmup_stage)
             PlayerScore_Add(player, SP_LMS_RANK, -PlayerScore_Add(player, SP_LMS_RANK, 0));
     }
 }
MUTATOR_HOOKFUNCTION (lms , ForbidSpawn)
Definition at line 146 of file gamemode_lms.qc.
References entity(), FRAGS_SPECTATOR, M_ARGV, PlayerScore_Add(), and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(warmup_stage)
         return false;
     if(player.frags == FRAGS_SPECTATOR)
         return true;
     if(PlayerScore_Add(player, SP_LMS_LIVES, 0) <= 0)
     {
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_LMS_NOLIVES);
         return true;
     }
     return false;
 }
MUTATOR_HOOKFUNCTION (lms , PlayerDies)
Definition at line 162 of file gamemode_lms.qc.
References entity(), M_ARGV, and RESPAWN_FORCE.
 {
     entity frag_target = M_ARGV(2, entity);
     frag_target.respawn_flags |= RESPAWN_FORCE;
 }
MUTATOR_HOOKFUNCTION (lms , ClientDisconnect)
Definition at line 222 of file gamemode_lms.qc.
References entity(), lms_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     lms_RemovePlayer(player);
 }
MUTATOR_HOOKFUNCTION (lms , MakePlayerObserver)
Definition at line 229 of file gamemode_lms.qc.
References entity(), lms_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     lms_RemovePlayer(player);
     return true;  // prevent team reset
 }
MUTATOR_HOOKFUNCTION (lms , ClientConnect)
Definition at line 237 of file gamemode_lms.qc.
References campaign_bots_may_start, entity(), FRAGS_SPECTATOR, LMS_NewPlayerLives(), M_ARGV, PlayerScore_Add(), and TRANSMUTE().
 {
     entity player = M_ARGV(0, entity);
     TRANSMUTE(Player, player);
     campaign_bots_may_start = true;
     if(PlayerScore_Add(player, SP_LMS_LIVES, LMS_NewPlayerLives()) <= 0)
     {
         PlayerScore_Add(player, SP_LMS_RANK, 666); // mark as forced spectator for the hud code
         player.frags = FRAGS_SPECTATOR;
     }
 }
MUTATOR_HOOKFUNCTION (lms , PlayerPreThink)
Definition at line 251 of file gamemode_lms.qc.
References DEAD_DYING, DEAD_RESPAWNING, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.deadflag == DEAD_DYING)
         player.deadflag = DEAD_RESPAWNING;
 }
MUTATOR_HOOKFUNCTION (lms , PlayerRegen)
Definition at line 259 of file gamemode_lms.qc.
References autocvar_g_lms_regenerate.
 {
     if(autocvar_g_lms_regenerate)
         return false;
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , ForbidThrowCurrentWeapon)
Definition at line 266 of file gamemode_lms.qc.
 {
     // forbode!
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , GiveFragsForKill)
Definition at line 272 of file gamemode_lms.qc.
References bot_clear(), entity(), FOREACH_CLIENT, FRAGS_LMS_LOSER, IS_BOT_CLIENT, IS_PLAYER, lms_lowest_lives, M_ARGV, PlayerScore_Add(), and warmup_stage.
 {
     entity frag_target = M_ARGV(1, entity);
     if (!warmup_stage)
     {
         // remove a life
         int tl = PlayerScore_Add(frag_target, SP_LMS_LIVES, -1);
         if(tl < lms_lowest_lives)
             lms_lowest_lives = tl;
         if(tl <= 0)
         {
             int pl_cnt = 0;
             FOREACH_CLIENT(IS_PLAYER(it), { pl_cnt++; });
             if(IS_BOT_CLIENT(frag_target))
                 bot_clear(frag_target);
             frag_target.frags = FRAGS_LMS_LOSER;
             PlayerScore_Add(frag_target, SP_LMS_RANK, pl_cnt);
         }
     }
     M_ARGV(2, float) = 0; // frag score
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , SetStartItems)
Definition at line 297 of file gamemode_lms.qc.
References cvar(), IT_UNLIMITED_AMMO, start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, and warmup_start_health.
 {
     start_items &= ~IT_UNLIMITED_AMMO;
     start_health       = warmup_start_health       = cvar("g_lms_start_health");
     start_armorvalue   = warmup_start_armorvalue   = cvar("g_lms_start_armor");
     start_ammo_shells  = warmup_start_ammo_shells  = cvar("g_lms_start_ammo_shells");
     start_ammo_nails   = warmup_start_ammo_nails   = cvar("g_lms_start_ammo_nails");
     start_ammo_rockets = warmup_start_ammo_rockets = cvar("g_lms_start_ammo_rockets");
     start_ammo_cells   = warmup_start_ammo_cells   = cvar("g_lms_start_ammo_cells");
     start_ammo_plasma  = warmup_start_ammo_plasma  = cvar("g_lms_start_ammo_plasma");
     start_ammo_fuel    = warmup_start_ammo_fuel    = cvar("g_lms_start_ammo_fuel");
 }
MUTATOR_HOOKFUNCTION (lms , ForbidPlayerScore_Clear)
Definition at line 310 of file gamemode_lms.qc.
 {
     // don't clear player score
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , FilterItem)
Definition at line 316 of file gamemode_lms.qc.
References autocvar_g_lms_extra_lives, entity(), and M_ARGV.
 {
     entity item = M_ARGV(0, entity);
     if(autocvar_g_lms_extra_lives)
     if(item.itemdef == ITEM_ExtraLife)
         return false;
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , OnEntityPreSpawn)
Definition at line 332 of file gamemode_lms.qc.
References autocvar_g_lms_extra_lives, autocvar_g_powerups, entity(), lms_extralife(), M_ARGV, setorigin(), setthink, spawn(), and time.
 {
     if (!autocvar_g_powerups) return false;
     if (!autocvar_g_lms_extra_lives) return false;
     entity ent = M_ARGV(0, entity);
     // Can't use .itemdef here
     if (ent.classname != "item_health_mega") return false;
     entity e = spawn();
     setthink(e, lms_extralife);
     e.nextthink = time + 0.1;
     e.spawnflags = ent.spawnflags;
     e.noalign = ent.noalign;
     setorigin(e, ent.origin);
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , ItemTouch)
Definition at line 353 of file gamemode_lms.qc.
References autocvar_g_lms_extra_lives, entity(), M_ARGV, MUT_ITEMTOUCH_CONTINUE, MUT_ITEMTOUCH_PICKUP, and PlayerScore_Add().
 {
     entity item = M_ARGV(0, entity);
     entity toucher = M_ARGV(1, entity);
     if(item.itemdef == ITEM_ExtraLife)
     {
         Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_EXTRALIVES);
         PlayerScore_Add(toucher, SP_LMS_LIVES, autocvar_g_lms_extra_lives);
         return MUT_ITEMTOUCH_PICKUP;
     }
     return MUT_ITEMTOUCH_CONTINUE;
 }
MUTATOR_HOOKFUNCTION (lms , Bot_FixCount , CBC_ORDER_EXCLUSIVE)
Definition at line 368 of file gamemode_lms.qc.
References FOREACH_CLIENT, IS_REAL_CLIENT, LAMBDA, and M_ARGV.
 {
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(
         ++M_ARGV(0, int); // activerealplayers
         ++M_ARGV(1, int); // realplayers
     ));
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , ClientCommand_Spectate)
Definition at line 378 of file gamemode_lms.qc.
References entity(), FRAGS_LMS_LOSER, FRAGS_SPECTATOR, M_ARGV, MUT_SPECCMD_CONTINUE, MUT_SPECCMD_RETURN, sprint(), and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(warmup_stage || player.lms_spectate_warning)
     {
         // for the forfeit message...
         player.lms_spectate_warning = 2;
     }
     else
     {
         if(player.frags != FRAGS_SPECTATOR && player.frags != FRAGS_LMS_LOSER)
         {
             player.lms_spectate_warning = 1;
             sprint(player, "WARNING: you won't be able to enter the game again after spectating in LMS. Use the same command again to spectate anyway.\n");
         }
         return MUT_SPECCMD_RETURN;
     }
     return MUT_SPECCMD_CONTINUE;
 }
MUTATOR_HOOKFUNCTION (lms , CheckRules_World)
Definition at line 399 of file gamemode_lms.qc.
References M_ARGV, and WinningCondition_LMS().
 {
     M_ARGV(0, float) = WinningCondition_LMS();
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , WantWeapon)
Definition at line 405 of file gamemode_lms.qc.
References M_ARGV.
 {
     M_ARGV(2, bool) = true; // all weapons
 }
MUTATOR_HOOKFUNCTION (lms , GetPlayerStatus)
Definition at line 410 of file gamemode_lms.qc.
 {
     return true;
 }
MUTATOR_HOOKFUNCTION (lms , AddPlayerScore)
Definition at line 415 of file gamemode_lms.qc.
References entity(), and M_ARGV.
 {
     if(game_stopped)
     if(M_ARGV(0, entity) == SP_LMS_RANK) // score field
         return true; // allow writing to this field in intermission as it is needed for newly joining players
 }
int WinningCondition_LMS ()
Definition at line 36 of file gamemode_lms.qc.
References classname, ClearWinners(), entity(), find(), LMS_NewPlayerLives(), LOG_TRACE(), NULL, PlayerScore_Add(), SetWinners(), STR_PLAYER, warmup_stage, winning, WINNING_NEVER, WINNING_NO, WINNING_YES, WinningConditionHelper(), WinningConditionHelper_secondscore, WinningConditionHelper_topscore, and WinningConditionHelper_winner.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity head, head2;
     bool have_player = false;
     bool have_players = false;
     int l = LMS_NewPlayerLives();
     head = find(NULL, classname, STR_PLAYER);
     if(head)
         have_player = true;
     head2 = find(head, classname, STR_PLAYER);
     if(head2)
         have_players = true;
     if(have_player)
     {
         // we have at least one player
         if(have_players)
         {
             // two or more active players - continue with the game
         }
         else
         {
             // exactly one player?
             ClearWinners();
             SetWinners(winning, 0); // NOTE: exactly one player is still "player", so this works out
             if(l)
             {
                 // game still running (that is, nobody got removed from the game by a frag yet)? then continue
                 return WINNING_NO;
             }
             else
             {
                 // a winner!
                 // and assign him his first place
                 PlayerScore_Add(head, SP_LMS_RANK, 1);
                 if(warmup_stage)
                     return WINNING_NO;
                 else
                     return WINNING_YES;
             }
         }
     }
     else
     {
         // nobody is playing at all...
         if(l)
         {
             // wait for players...
         }
         else
         {
             // SNAFU (maybe a draw game?)
             ClearWinners();
             LOG_TRACE("No players, ending game.");
             return WINNING_YES;
         }
     }
     // When we get here, we have at least two players who are actually LIVING,
     // now check if the top two players have equal score.
     WinningConditionHelper(NULL);
     ClearWinners();
     if(WinningConditionHelper_winner)
         WinningConditionHelper_winner.winning = true;
     if(WinningConditionHelper_topscore == WinningConditionHelper_secondscore)
         return WINNING_NEVER;
     // Top two have different scores? Way to go for our beloved TIMELIMIT!
     return WINNING_NO;
 }
Variable Documentation
int autocvar_g_lms_extra_lives
Definition at line 7 of file gamemode_lms.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_lms_join_anytime
Definition at line 8 of file gamemode_lms.qc.
Referenced by LMS_NewPlayerLives().
int autocvar_g_lms_last_join
Definition at line 9 of file gamemode_lms.qc.
Referenced by LMS_NewPlayerLives().
bool autocvar_g_lms_regenerate
Definition at line 10 of file gamemode_lms.qc.
Referenced by MUTATOR_HOOKFUNCTION().