Xonotic: server/playerdemo.qh File Reference
server/playerdemo.qh File Reference
Defines
#define PLAYERDEMO_H
Functions
void playerdemo_init (entity this)
void playerdemo_shutdown ()
void playerdemo_write ()
float playerdemo_read (entity this)
void playerdemo_open_read (string f)
void playerdemo_open_write (string f)
Define Documentation
#define PLAYERDEMO_H
Definition at line 2 of file playerdemo.qh.
Function Documentation
void playerdemo_init (entity this)
Definition at line 15 of file playerdemo.qc.
References playerdemo_mode, and PLAYERDEMO_MODE_OFF.
Referenced by ClientConnect().
{
    this.playerdemo_mode = PLAYERDEMO_MODE_OFF;
}
void playerdemo_open_read (string f)
Definition at line 28 of file playerdemo.qc.
References fgets(), FILE_READ, fopen(), LOG_INFO, MOVETYPE_NONE, netname, playerdemo_fh, PLAYERDEMO_MODE_READING, playerdemo_shutdown(), SELFPARAM, stof(), and time.
Referenced by GameCommand_playerdemo().
{SELFPARAM();
    playerdemo_shutdown();
    self.playerdemo_mode = PLAYERDEMO_MODE_READING;
    self.playerdemo_fh = fopen(f, FILE_READ);
    self.playerdemo_starttime = time - 1;
    self.playerdemo_time = stof(fgets(self.playerdemo_fh));
    self.playerdemo_time += self.playerdemo_starttime;
    self.movetype = MOVETYPE_NONE;
    LOG_INFO("playerdemo: ", self.netname, " reading from ", f, "\n");
}
void playerdemo_open_write (string f)
Definition at line 39 of file playerdemo.qc.
References FILE_WRITE, fopen(), LOG_INFO, netname, PLAYERDEMO_MODE_WRITING, playerdemo_shutdown(), SELFPARAM, and time.
Referenced by GameCommand_playerdemo().
{SELFPARAM();
    playerdemo_shutdown();
    self.playerdemo_mode = PLAYERDEMO_MODE_WRITING;
    self.playerdemo_fh = fopen(f, FILE_WRITE);
    self.playerdemo_starttime = time - 1;
    LOG_INFO("playerdemo: ", self.netname, " writing to ", f, "\n");
    LOG_INFO("WARNING: playerdemo file format is incomplete and not stable yet. DO NOT RELY ON IT!\n");
}
float playerdemo_read (entity this)
Definition at line 136 of file playerdemo.qc.
References entity(), fgets(), playerdemo_fh, PLAYERDEMO_FIELDS, playerdemo_mode, PLAYERDEMO_MODE_READING, playerdemo_starttime, playerdemo_time, PlayerPostThink(), PlayerPreThink(), stof(), time, velocity, and WITH.
Referenced by PM_Main().
{
    if(this.playerdemo_mode != PLAYERDEMO_MODE_READING)
        return 0;
    if(this.playerdemo_time < 0)
        return 1;
    float t;
    t = time;
    while(time >= this.playerdemo_time)
    {
        PLAYERDEMO_FIELDS(playerdemo_read_)
        {
            time = this.playerdemo_time;
            WITH(entity, self, this, PlayerPreThink());
            // not running physics though... this is just so we can run weapon stuff
            WITH(entity, self, this, PlayerPostThink());
        }
        this.playerdemo_time = stof(fgets(this.playerdemo_fh));
        if(this.playerdemo_time == 0)
        {
            this.playerdemo_time = -1;
            return 1;
        }
        this.playerdemo_time += this.playerdemo_starttime;
    }
    this.velocity = '0 0 0';
    time = t;
    return 1;
}
void playerdemo_shutdown ()
Definition at line 19 of file playerdemo.qc.
References fclose(), LOG_INFO, netname, playerdemo_fh, playerdemo_mode, PLAYERDEMO_MODE_OFF, and SELFPARAM.
Referenced by ClientDisconnect(), playerdemo_open_read(), and playerdemo_open_write().
{SELFPARAM();
    if(self.playerdemo_mode != PLAYERDEMO_MODE_OFF)
    {
        LOG_INFO("playerdemo: ", self.netname, " closed\n");
        fclose(self.playerdemo_fh);
    }
    self.playerdemo_mode = 0;
}
void playerdemo_write ()
Definition at line 94 of file playerdemo.qc.
References fputs(), ftos(), playerdemo_fh, PLAYERDEMO_FIELDS, playerdemo_mode, PLAYERDEMO_MODE_WRITING, playerdemo_starttime, SELFPARAM, strcat(), and time.
Referenced by PlayerPostThink().
{SELFPARAM();
    if(self.playerdemo_mode != PLAYERDEMO_MODE_WRITING)
        return;
    fputs(self.playerdemo_fh, strcat(ftos(time - self.playerdemo_starttime), "\n"));
    PLAYERDEMO_FIELDS(playerdemo_write_)
}