Xonotic: menu/xonotic/dialog_termsofservice.qh File Reference
dialog_termsofservice.qh File Reference
#include "rootdialog.qh"
Classes
class XonoticToSDialog
Functions
void XonoticToS_OnGet (entity fh, entity me, int status)
Variables
int autocvar__termsofservice_accepted
const string termsofservice_url = "http://update.xonotic.org/tos.txt"
Function Documentation
XonoticToS_OnGet()
void XonoticToS_OnGet (entity fh, entity me, int status)
Definition at line 31 of file dialog_termsofservice.qc.
References strcat(), strfree, strzone(), url_fclose(), url_fgets(), URL_READY_CANREAD, URL_READY_CLOSED, and URL_READY_ERROR.
Referenced by XonoticToSDialog_loadXonoticToS().
 {
     switch (status) {
         case URL_READY_CLOSED:
         {
             break;
         }
         case URL_READY_ERROR:
         {
             me.text = strzone("Error reading ToS");
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         case URL_READY_CANREAD:
         {
             strfree(me.text);
             string temp = "";
             for (string s; (s = url_fgets(fh)); )
             {
                 if (temp != "")
                     temp = strcat(temp, "\n", s);
                 else
                     temp = s;
             }
             url_fclose(fh);
             me.text = strzone(temp);
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         default:
         {
             break;
         }
     }
 }
Variable Documentation
autocvar__termsofservice_accepted
int autocvar__termsofservice_accepted
Definition at line 3 of file dialog_termsofservice.qh.
Referenced by XonoticToSDialog_fill(), and XonoticToSDialog_shouldShow().
termsofservice_url
const string termsofservice_url = "http://update.xonotic.org/tos.txt"
Definition at line 4 of file dialog_termsofservice.qh.
Referenced by XonoticToSDialog_loadXonoticToS().