Xonotic: server/sv_main.qc File Reference
sv_main.qc File Reference
#include "sv_main.qh"
#include "anticheat.qh"
#include "g_hook.qh"
#include "g_world.qh"
#include "bot/api.qh"
#include "command/common.qh"
#include "mutators/_mod.qh"
#include "weapons/csqcprojectile.qh"
#include "../common/constants.qh"
#include "../common/deathtypes/all.qh"
#include "../common/debug.qh"
#include "../common/mapinfo.qh"
#include "../common/util.qh"
#include "../common/vehicles/all.qh"
#include <common/weapons/_all.qh>
#include "../lib/csqcmodel/sv_model.qh"
#include "../lib/warpzone/common.qh"
#include "../lib/warpzone/server.qh"
Functions
void CreatureFrame_All ()
void CreatureFrame_FallDamage (entity this)
void CreatureFrame_hotliquids (entity this)
void CreatureFrame_Liquids (entity this)
bool DoesQ3ARemoveThisEntity (entity this)
void Pause_TryPause (bool ispaused)
float RedirectionThink ()
void StartFrame ()
void SV_OnEntityPreSpawnFunction (entity this)
void SV_PausedTic (float elapsedtime)
void sys_phys_update (entity this, float dt)
void systems_update ()
void WarpZone_PostInitialize_Callback ()
Variables
float anglejitter
vector anglesjitter
bool autocvar_sv_autopause = false
string cvarfilter
float game_delay
float game_delay_last
string gametypefilter
float lastground
vector originjitter
int state
Function Documentation
void CreatureFrame_All ()
Definition at line 118 of file sv_main.qc.
References CreatureFrame_FallDamage(), CreatureFrame_Liquids(), damagedbycontents, FOREACH_ENTITY_FLOAT, and MOVETYPE_NOCLIP.
Referenced by StartFrame().
 {
     FOREACH_ENTITY_FLOAT(damagedbycontents, true, {
         if (it.move_movetype == MOVETYPE_NOCLIP) continue;
         CreatureFrame_Liquids(it);
         CreatureFrame_FallDamage(it);
         it.oldvelocity = it.velocity;
     });
 }
void CreatureFrame_FallDamage (entity this)
Definition at line 95 of file sv_main.qc.
References autocvar_g_balance_falldamage_deadminspeed, autocvar_g_balance_falldamage_factor, autocvar_g_balance_falldamage_maxdamage, autocvar_g_balance_falldamage_minspeed, autocvar_g_maxspeed, Damage(), FL_PROJECTILE, flags, hook, IS_DEAD, IS_VEHICLE, min(), NULL, oldvelocity, velocity, and vlen().
Referenced by CreatureFrame_All().
 {
     if(!IS_VEHICLE(this) && !(this.flags & FL_PROJECTILE)) // vehicles don't get falling damage
     if(this.velocity || this.oldvelocity) // moving or has moved
     {
         // check for falling damage
         float velocity_len = vlen(this.velocity);
         if(!this.hook.state)
         {
             float dm = vlen(this.oldvelocity) - velocity_len; // dm is now the velocity DECREASE. Velocity INCREASE should never cause a sound or any damage.
             if (IS_DEAD(this))
                 dm = (dm - autocvar_g_balance_falldamage_deadminspeed) * autocvar_g_balance_falldamage_factor;
             else
                 dm = min((dm - autocvar_g_balance_falldamage_minspeed) * autocvar_g_balance_falldamage_factor, autocvar_g_balance_falldamage_maxdamage);
             if (dm > 0)
                 Damage (this, NULL, NULL, dm, DEATH_FALL.m_id, this.origin, '0 0 0');
         }
         if(autocvar_g_maxspeed > 0 && velocity_len > autocvar_g_maxspeed)
             Damage (this, NULL, NULL, 100000, DEATH_SHOOTING_STAR.m_id, this.origin, '0 0 0');
     }
 }
void CreatureFrame_hotliquids (entity this)
Definition at line 31 of file sv_main.qc.
References ATTEN_NORM, autocvar_g_balance_contents_damagerate, autocvar_g_balance_contents_playerdamage_lava, autocvar_g_balance_contents_playerdamage_lava_burn, autocvar_g_balance_contents_playerdamage_lava_burn_time, autocvar_g_balance_contents_playerdamage_slime, autocvar_g_balance_contents_projectiledamage, CH_PLAYER_SINGLE, CONTENT_LAVA, CONTENT_SLIME, Damage(), dmgtime, Fire_AddDamage(), FL_PROJECTILE, flags, NULL, sound, time, VOL_BASE, waterlevel, watersound_finished, and watertype.
Referenced by CreatureFrame_Liquids().
 {
     if (this.dmgtime < time)
     {
         this.dmgtime = time + autocvar_g_balance_contents_damagerate;
         if (this.flags & FL_PROJECTILE)
         {
             if (this.watertype == CONTENT_LAVA)
                 Damage (this, NULL, NULL, autocvar_g_balance_contents_projectiledamage * autocvar_g_balance_contents_damagerate * this.waterlevel, DEATH_LAVA.m_id, this.origin, '0 0 0');
             else if (this.watertype == CONTENT_SLIME)
                 Damage (this, NULL, NULL, autocvar_g_balance_contents_projectiledamage * autocvar_g_balance_contents_damagerate * this.waterlevel, DEATH_SLIME.m_id, this.origin, '0 0 0');
         }
         else
         {
             if (this.watertype == CONTENT_LAVA)
             {
                 if (this.watersound_finished < time)
                 {
                     this.watersound_finished = time + 0.5;
                     sound (this, CH_PLAYER_SINGLE, SND_LAVA, VOL_BASE, ATTEN_NORM);
                 }
                 Damage (this, NULL, NULL, autocvar_g_balance_contents_playerdamage_lava * autocvar_g_balance_contents_damagerate * this.waterlevel, DEATH_LAVA.m_id, this.origin, '0 0 0');
                 if(autocvar_g_balance_contents_playerdamage_lava_burn)
                     Fire_AddDamage(this, NULL, autocvar_g_balance_contents_playerdamage_lava_burn * this.waterlevel, autocvar_g_balance_contents_playerdamage_lava_burn_time * this.waterlevel, DEATH_LAVA.m_id);
             }
             else if (this.watertype == CONTENT_SLIME)
             {
                 if (this.watersound_finished < time)
                 {
                     this.watersound_finished = time + 0.5;
                     sound (this, CH_PLAYER_SINGLE, SND_SLIME, VOL_BASE, ATTEN_NORM);
                 }
                 Damage (this, NULL, NULL, autocvar_g_balance_contents_playerdamage_slime * autocvar_g_balance_contents_damagerate * this.waterlevel, DEATH_SLIME.m_id, this.origin, '0 0 0');
             }
         }
     }
 }
void CreatureFrame_Liquids (entity this)
Definition at line 70 of file sv_main.qc.
References air_finished, CreatureFrame_hotliquids(), dmg, dmgtime, FL_INWATER, flags, and time.
Referenced by CreatureFrame_All().
 {
     if (this.watertype <= CONTENT_WATER && this.waterlevel > 0) // workaround a retarded bug made by id software :P (yes, it's that old of a bug)
     {
         if (!(this.flags & FL_INWATER))
         {
             this.flags |= FL_INWATER;
             this.dmgtime = 0;
         }
         CreatureFrame_hotliquids(this);
     }
     else
     {
         if (this.flags & FL_INWATER)
         {
             // play leave water sound
             this.flags &= ~FL_INWATER;
             this.dmgtime = 0;
         }
         this.air_finished = time + 12;
         this.dmg = 2;
     }
 }
bool DoesQ3ARemoveThisEntity (entity this)
Definition at line 167 of file t_quake3.qc.
References g_ctf, g_tdm, gametype, maxclients, notfree, notq3a, notsingle, notta, notteam, strstrofs, and teamplay.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     // Q3 style filters (DO NOT USE, THIS IS COMPAT ONLY)
     if(this.notq3a)
         if(!teamplay || g_tdm || g_ctf)
             return true;
     if(this.notta)
         if (!(!teamplay || g_tdm || g_ctf))
             return true;
     if(this.notsingle)
         if(maxclients == 1)
             return true;
     if(this.notteam)
         if(teamplay)
             return true;
     if(this.notfree)
         if(!teamplay)
             return true;
     if(this.gametype)
     {
         string gametypename;
         // static char *gametypeNames[] = {"ffa", "tournament", "single", "team", "ctf", "oneflag", "obelisk", "harvester", "teamtournament"}
         gametypename = "ffa";
         if(teamplay)
             gametypename = "team";
         if(g_ctf)
             gametypename = "ctf";
         if(maxclients == 1)
             gametypename = "single";
         // we do not have the other types (oneflag, obelisk, harvester, teamtournament)
         if(strstrofs(this.gametype, gametypename, 0) < 0)
             return true;
     }
     return false;
 }
void Pause_TryPause (bool ispaused)
Definition at line 128 of file sv_main.qc.
References FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, and PHYS_INPUT_BUTTON_CHAT.
Referenced by StartFrame(), and SV_PausedTic().
 {
     int n = 0;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), LAMBDA(
         if (PHYS_INPUT_BUTTON_CHAT(it) != ispaused) return;
         ++n;
     ));
     if (!n) return;
     setpause(ispaused);
 }
float RedirectionThink ()
Definition at line 2099 of file g_world.qc.
References autocvar_quit_and_redirect_timer, bprint(), cvar_set(), FOREACH_CLIENT, ftos(), IS_REAL_CLIENT, LAMBDA, localcmd, LOG_INFO, redirection_target, strcat(), stuffcmd, and time.
Referenced by StartFrame().
 {
     float clients_found;
     if(redirection_target == "")
         return false;
     if(!redirection_timeout)
     {
         cvar_set("sv_public", "-2");
         redirection_timeout = time + 0.6; // this will only try twice... should be able to keep more clients
         if(redirection_target == "self")
             bprint("^3SERVER NOTICE:^7 restarting the server\n");
         else
             bprint("^3SERVER NOTICE:^7 redirecting everyone to ", redirection_target, "\n");
     }
     if(time < redirection_nextthink)
         return true;
     redirection_nextthink = time + 1;
     clients_found = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(
         // TODO add timer
         LOG_INFO("Redirecting: sending connect command to ", it.netname, "\n");
         if(redirection_target == "self")
             stuffcmd(it, "\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " reconnect\n");
         else
             stuffcmd(it, strcat("\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " \"connect ", redirection_target, "\"\n"));
         ++clients_found;
     ));
     LOG_INFO("Redirecting: ", ftos(clients_found), " clients left.\n");
     if(time > redirection_timeout || clients_found == 0)
         localcmd("\nwait; wait; wait; quit\n");
     return true;
 }
void StartFrame ()
Definition at line 159 of file sv_main.qc.
References anticheat_startframe(), autocvar_skill, autocvar_slowmo, autocvar_sv_autopause, autocvar_sv_eventlog, autocvar_sys_ticrate, bot_serverframe(), CheckRules_World(), CreatureFrame_All(), CSQCProjectile_Check(), delete_fn(), execute_next_frame(), FOREACH_CLIENT, frametime, ftos(), g_players, g_projectiles, game_delay, game_delay_last, game_starttime, GameLogEcho(), gameover, IL_EACH, InitializeEntitiesRun(), IS_FAKE_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, LOG_INFO, MUTATOR_CALLHOOK, orig_slowmo, Pause_TryPause(), PlayerPostThink(), PlayerPreThink(), ReadyRestart(), RedirectionThink(), remove_unsafely(), server_is_dedicated, serverframetime, serverprevtime, servertime, skill, solve_quadratic(), sys_frametime, sys_phys_update(), time, TIMEOUT_LEADTIME, timeout_status, warmup_limit, and warmup_stage.
 {
     // TODO: if move is more than 50ms, split it into two moves (this matches QWSV behavior and the client prediction)
     IL_EACH(g_players, IS_FAKE_CLIENT(it), sys_phys_update(it, frametime));
     IL_EACH(g_players, IS_FAKE_CLIENT(it), PlayerPreThink(it));
     execute_next_frame();
     if (autocvar_sv_autopause && !server_is_dedicated) Pause_TryPause(true);
     delete_fn = remove_unsafely; // not during spawning!
     serverprevtime = servertime;
     servertime = time;
     serverframetime = frametime;
 #ifdef PROFILING
     if(time > client_cefc_accumulatortime + 1)
     {
         float t = client_cefc_accumulator / (time - client_cefc_accumulatortime);
         LOG_INFO("CEFC time: ", ftos(t * 1000), "ms; ");
         int c_seeing = 0;
         int c_seen = 0;
         FOREACH_CLIENT(true, LAMBDA(
             if(IS_REAL_CLIENT(it))
                 ++c_seeing;
             if(IS_PLAYER(it))
                 ++c_seen;
         ));
         LOG_INFO("CEFC calls per second: ", ftos(c_seeing * (c_seen - 1) / t), "; ");
         LOG_INFO("CEFC 100% load at: ", ftos(solve_quadratic(t, -t, -1) * '0 1 0'), "\n");
         client_cefc_accumulatortime = time;
         client_cefc_accumulator = 0;
     }
 #endif
     IL_EACH(g_projectiles, it.csqcprojectile_clientanimate, CSQCProjectile_Check(it));
     if (RedirectionThink()) return;
     UncustomizeEntitiesRun();
     InitializeEntitiesRun();
     WarpZone_StartFrame();
     sys_frametime = autocvar_sys_ticrate * autocvar_slowmo;
     if (sys_frametime <= 0) sys_frametime = 1.0 / 60.0; // somewhat safe fallback
     if (timeout_status == TIMEOUT_LEADTIME) // just before the timeout (when timeout_status will be TIMEOUT_ACTIVE)
         orig_slowmo = autocvar_slowmo; // slowmo will be restored after the timeout
     skill = autocvar_skill;
     // detect when the pre-game countdown (if any) has ended and the game has started
     game_delay = (time < game_starttime);
     if (autocvar_sv_eventlog && game_delay_last && !game_delay)
         GameLogEcho(":startdelay_ended");
     game_delay_last = game_delay;
     CreatureFrame_All();
     CheckRules_World();
     if (warmup_stage && !gameover && warmup_limit > 0 && time >= warmup_limit) {
         ReadyRestart();
         return;
     }
     bot_serverframe();
     anticheat_startframe();
     MUTATOR_CALLHOOK(SV_StartFrame);
     FOREACH_CLIENT(true, GlobalStats_update(it));
     IL_EACH(g_players, IS_FAKE_CLIENT(it), PlayerPostThink(it));
 }
void SV_OnEntityPreSpawnFunction (entity this)
Definition at line 241 of file sv_main.qc.
References __spawnfunc_expect, __spawnfunc_expecting, anglejitter, angles, anglesjitter, argv(), cvar(), cvar_string(), cvarfilter, DoesQ3ARemoveThisEntity(), gametypefilter, have_team_spawns, isGametypeInFilter(), LABEL, MapInfo_LoadedGametype, movetype, MUTATOR_CALLHOOK, origin, originjitter, random(), set_movetype(), stof(), strstrofs, substring(), teamplay, and tokenize_console.
 {
     __spawnfunc_expecting = true;
     __spawnfunc_expect = this;
     if (this)
     if (this.gametypefilter != "")
     if (!isGametypeInFilter(MapInfo_LoadedGametype, teamplay, have_team_spawns, this.gametypefilter))
     {
         delete(this);
         __spawnfunc_expecting = false;
         return;
     }
     if(this.cvarfilter != "")
     {
         float n, i, o, inv;
         string s, k, v;
         inv = 0;
         s = this.cvarfilter;
         if(substring(s, 0, 1) == "+")
         {
             s = substring(s, 1, -1);
         }
         else if(substring(s, 0, 1) == "-")
         {
             inv = 1;
             s = substring(s, 1, -1);
         }
         n = tokenize_console(s);
         for(i = 0; i < n; ++i)
         {
             s = argv(i);
             // syntax:
             // var>x
             // var<x
             // var>=x
             // var<=x
             // var==x
             // var!=x
             // var===x
             // var!==x
             if((o = strstrofs(s, ">=", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar(k) < stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "<=", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar(k) > stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, ">", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+1, -1);
                 if(cvar(k) <= stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "<", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+1, -1);
                 if(cvar(k) >= stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "==", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar(k) != stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "!=", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar(k) == stof(v))
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "===", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar_string(k) != v)
                     goto cvar_fail;
             }
             else if((o = strstrofs(s, "!==", 0)) >= 0)
             {
                 k = substring(s, 0, o);
                 v = substring(s, o+2, -1);
                 if(cvar_string(k) == v)
                     goto cvar_fail;
             }
             else if(substring(s, 0, 1) == "!")
             {
                 k = substring(s, 1, -1);
                 if(cvar(k))
                     goto cvar_fail;
             }
             else
             {
                 k = s;
                 if (!cvar(k))
                     goto cvar_fail;
             }
         }
         inv = !inv;
 LABEL(cvar_fail)
         // now inv is 1 if we want to keep the item, and 0 if we want to get rid of it
         if (!inv)
         {
             //print("cvarfilter fail\n");
             delete(this);
             __spawnfunc_expecting = false;
             return;
         }
     }
     if(DoesQ3ARemoveThisEntity(this))
     {
         delete(this);
         __spawnfunc_expecting = false;
         return;
     }
     set_movetype(this, this.movetype);
     // support special -1 and -2 angle from radiant
     if (this.angles == '0 -1 0')
         this.angles = '-90 0 0';
     else if (this.angles == '0 -2 0')
         this.angles = '+90 0 0';
     if(this.originjitter.x != 0)
         this.origin_x = this.origin.x + (random() * 2 - 1) * this.originjitter.x;
     if(this.originjitter.y != 0)
         this.origin_y = this.origin.y + (random() * 2 - 1) * this.originjitter.y;
     if(this.originjitter.z != 0)
         this.origin_z = this.origin.z + (random() * 2 - 1) * this.originjitter.z;
     if(this.anglesjitter.x != 0)
         this.angles_x = this.angles.x + (random() * 2 - 1) * this.anglesjitter.x;
     if(this.anglesjitter.y != 0)
         this.angles_y = this.angles.y + (random() * 2 - 1) * this.anglesjitter.y;
     if(this.anglesjitter.z != 0)
         this.angles_z = this.angles.z + (random() * 2 - 1) * this.anglesjitter.z;
     if(this.anglejitter != 0)
         this.angles_y = this.angles.y + (random() * 2 - 1) * this.anglejitter;
     if(MUTATOR_CALLHOOK(OnEntityPreSpawn, this))
     {
         delete(this);
         __spawnfunc_expecting = false;
         return;
     }
 }
void SV_PausedTic (float elapsedtime)
Definition at line 139 of file sv_main.qc.
References Pause_TryPause(), and server_is_dedicated.
 {
     if (!server_is_dedicated) Pause_TryPause(false);
 }
void sys_phys_update (entity this, float dt)
Definition at line 9 of file physics.qc.
References absmax, absmin, angles, buttons_old, CheckPlayerJump(), classname, com_phys_acc_rate, com_phys_acc_rate_air, com_phys_acc_rate_air_stop, com_phys_acc_rate_air_strafe, com_phys_air, com_phys_friction, com_phys_friction_air, com_phys_gravity, com_phys_ground, com_phys_ladder, com_phys_vel_2d, com_phys_vel_max, com_phys_vel_max_air, com_phys_vel_max_air_strafe, com_phys_water, CONTENT_WATER, conveyor, disableclientprediction, emit, FL_WATERJUMP, flags, in_swamp, IS_CLIENT, IS_DEAD, IS_ONGROUND, IS_PLAYER, IS_SVQC, IsFlying(), IT_USING_JETPACK, ITEMS_STAT, LABEL, ladder_time, lastclassname, lastflags, lastground, min(), move_movetype, move_qcphysics, movedir, movement, movement_old, MOVETYPE_FLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_NOCLIP, MOVETYPE_NONE, MUTATOR_CALLHOOK, PHYS_ACCELERATE, PHYS_AIRACCELERATE, PHYS_AIRSTOPACCELERATE, PHYS_AIRSTRAFEACCELERATE, PHYS_FRICTION, PHYS_FRICTION_ONLAND, PHYS_INPUT_BUTTON_MASK, PHYS_MAXAIRSPEED, PHYS_MAXAIRSTRAFESPEED, PHYS_MAXSPEED, PHYS_TELEPORT_TIME, PHYS_WATERJUMP_TIME, PM_check_blocked(), PM_check_frozen(), PM_check_hitground(), PM_Footsteps(), PM_jetpack(), swamp_slowdown, sys_in_update(), sys_phys_ai(), sys_phys_fix(), sys_phys_fixspeed(), sys_phys_monitor(), sys_phys_override(), sys_phys_pregame_hold(), sys_phys_simulate(), sys_phys_simulate_simple(), sys_phys_spectator_control(), time, v_angle, v_angle_old, vector(), velocity, viewloc_PlayerPhysics(), WAS_ONGROUND, wasFlying, waterlevel, WATERLEVEL_NONE, and WATERLEVEL_SWIMMING.
Referenced by StartFrame().
 {
     if (!IS_CLIENT(this)) {
         sys_phys_simulate_simple(this, dt);
         return;
     }
     sys_in_update(this, dt);
     sys_phys_fix(this, dt);
     if (sys_phys_override(this, dt)) { return; } sys_phys_monitor(this, dt);
     this.buttons_old = PHYS_INPUT_BUTTON_MASK(this);
     this.movement_old = this.movement;
     this.v_angle_old = this.v_angle;
     sys_phys_ai(this);
     sys_phys_pregame_hold(this);
     if (IS_SVQC) {
         if (this.move_movetype == MOVETYPE_NONE) { return; }
         // when we get here, disableclientprediction cannot be 2
         this.disableclientprediction = (this.move_qcphysics) ? -1 : 0;
     }
     viewloc_PlayerPhysics(this);
     PM_check_frozen(this);
     PM_check_blocked(this);
     float maxspeed_mod = (!this.in_swamp) ? 1 : this.swamp_slowdown;  // cvar("g_balance_swamp_moverate");
 // conveyors: first fix velocity
     if (this.conveyor.state) { this.velocity -= this.conveyor.movedir; }
     MUTATOR_CALLHOOK(PlayerPhysics, this, dt);
     if (!IS_PLAYER(this)) {
         sys_phys_spectator_control(this);
         maxspeed_mod = this.spectatorspeed;
     }
     sys_phys_fixspeed(this, maxspeed_mod);
     if (IS_DEAD(this)) {
         // handle water here
         vector midpoint = ((this.absmin + this.absmax) * 0.5);
         if (pointcontents(midpoint) == CONTENT_WATER) {
             this.velocity = this.velocity * 0.5;
             // do we want this?
             // if(pointcontents(midpoint + '0 0 2') == CONTENT_WATER)
             // { this.velocity_z = 70; }
         }
         goto end;
     }
     if (IS_SVQC && !PHYS_FIXANGLE(this)) { this.angles = '0 1 0' * this.v_angle.y; }
     if (IS_PLAYER(this)) {
         if (IS_ONGROUND(this)) {
             PM_check_hitground(this);
             PM_Footsteps(this);
         } else if (IsFlying(this)) {
             this.wasFlying = true;
         }
         CheckPlayerJump(this);
     }
     if (this.flags & FL_WATERJUMP) {
         this.velocity_x = this.movedir.x;
         this.velocity_y = this.movedir.y;
         if (this.waterlevel == WATERLEVEL_NONE
             || time > PHYS_TELEPORT_TIME(this)
             || PHYS_WATERJUMP_TIME(this) <= 0
            ) {
             this.flags &= ~FL_WATERJUMP;
             PHYS_TELEPORT_TIME(this) = 0;
             PHYS_WATERJUMP_TIME(this) = 0;
         }
     } else if (MUTATOR_CALLHOOK(PM_Physics, this, maxspeed_mod, dt)) {
         // handled
     } else if (this.move_movetype == MOVETYPE_NOCLIP
         || this.move_movetype == MOVETYPE_FLY
         || this.move_movetype == MOVETYPE_FLY_WORLDONLY
         || MUTATOR_CALLHOOK(IsFlying, this)) {
         this.com_phys_friction = PHYS_FRICTION(this);
         this.com_phys_vel_max = PHYS_MAXSPEED(this) * maxspeed_mod;
         this.com_phys_acc_rate = PHYS_ACCELERATE(this) * maxspeed_mod;
         this.com_phys_friction_air = true;
         sys_phys_simulate(this, dt);
         this.com_phys_friction_air = false;
     } else if (this.waterlevel >= WATERLEVEL_SWIMMING) {
         this.com_phys_vel_max = PHYS_MAXSPEED(this) * maxspeed_mod;
         this.com_phys_acc_rate = PHYS_ACCELERATE(this) * maxspeed_mod;
         this.com_phys_water = true;
         sys_phys_simulate(this, dt);
         this.com_phys_water = false;
     } else if (time < this.ladder_time) {
         this.com_phys_friction = PHYS_FRICTION(this);
         this.com_phys_vel_max = PHYS_MAXSPEED(this) * maxspeed_mod;
         this.com_phys_acc_rate = PHYS_ACCELERATE(this) * maxspeed_mod;
         this.com_phys_gravity = '0 0 -1' * PHYS_GRAVITY(this) * dt;
         if (PHYS_ENTGRAVITY(this)) { this.com_phys_gravity *= PHYS_ENTGRAVITY(this); }
         this.com_phys_ladder = true;
         this.com_phys_friction_air = true;
         sys_phys_simulate(this, dt);
         this.com_phys_friction_air = false;
         this.com_phys_ladder = false;
         this.com_phys_gravity = '0 0 0';
     } else if (ITEMS_STAT(this) & IT_USING_JETPACK) {
         PM_jetpack(this, maxspeed_mod, dt);
     } else if (IS_ONGROUND(this)) {
         if (!WAS_ONGROUND(this)) {
             emit(phys_land, this);
             if (this.lastground < time - 0.3) {
                 this.velocity *= (1 - PHYS_FRICTION_ONLAND(this));
             }
         }
         this.com_phys_vel_max = PHYS_MAXSPEED(this) * maxspeed_mod;
         this.com_phys_gravity = '0 0 -1' * PHYS_GRAVITY(this) * dt;
         if (PHYS_ENTGRAVITY(this)) { this.com_phys_gravity *= PHYS_ENTGRAVITY(this); }
         this.com_phys_ground = true;
         this.com_phys_vel_2d = true;
         sys_phys_simulate(this, dt);
         this.com_phys_vel_2d = false;
         this.com_phys_ground = false;
         this.com_phys_gravity = '0 0 0';
     } else {
         this.com_phys_acc_rate_air = PHYS_AIRACCELERATE(this) * min(maxspeed_mod, 1);
         this.com_phys_acc_rate_air_stop = PHYS_AIRSTOPACCELERATE(this) * maxspeed_mod;
         this.com_phys_acc_rate_air_strafe = PHYS_AIRSTRAFEACCELERATE(this) * maxspeed_mod;
         this.com_phys_vel_max_air_strafe = PHYS_MAXAIRSTRAFESPEED(this) * maxspeed_mod;
         this.com_phys_vel_max_air = PHYS_MAXAIRSPEED(this) * maxspeed_mod;
         this.com_phys_vel_max = PHYS_MAXAIRSPEED(this) * min(maxspeed_mod, 1);
         this.com_phys_air = true;
         this.com_phys_vel_2d = true;
         sys_phys_simulate(this, dt);
         this.com_phys_vel_2d = false;
         this.com_phys_air = false;
     }
     LABEL(end)
     if (IS_ONGROUND(this)) { this.lastground = time; }
 // conveyors: then break velocity again
     if (this.conveyor.state) { this.velocity += this.conveyor.movedir; }
     this.lastflags = this.flags;
     this.lastclassname = this.classname;
 }
void systems_update ()
Definition at line 7 of file main.qc.
References SYSTEM_UPDATE, and time.
 {
     float realtime = time;
     SYSTEM_UPDATE(phys);
     time = realtime;
 }
void WarpZone_PostInitialize_Callback ()
Definition at line 402 of file sv_main.qc.
References classname, entity(), find(), NULL, v_forward, v_right, vector(), and waypoint_spawnforteleporter_v().
 {
     // create waypoint links for warpzones
     entity e;
     for(e = NULL; (e = find(e, classname, "trigger_warpzone")); )
     {
         vector src, dst;
         src = (e.absmin + e.absmax) * 0.5;
         makevectors(e.warpzone_angles);
         src = src + ((e.warpzone_origin - src) * v_forward) * v_forward + 16 * v_right;
         dst = (e.enemy.absmin + e.enemy.absmax) * 0.5;
         makevectors(e.enemy.warpzone_angles);
         dst = dst + ((e.enemy.warpzone_origin - dst) * v_forward) * v_forward - 16 * v_right;
         waypoint_spawnforteleporter_v(e, src, dst, 0);
     }
 }
Variable Documentation
float anglejitter
Definition at line 237 of file sv_main.qc.
Referenced by SV_OnEntityPreSpawnFunction().
vector anglesjitter
Definition at line 236 of file sv_main.qc.
Referenced by SV_OnEntityPreSpawnFunction().
bool autocvar_sv_autopause = false
Definition at line 155 of file sv_main.qc.
Referenced by StartFrame().
string cvarfilter
Definition at line 239 of file sv_main.qc.
Referenced by SV_OnEntityPreSpawnFunction().
float game_delay
Definition at line 152 of file sv_main.qc.
Referenced by StartFrame().
float game_delay_last
Definition at line 153 of file sv_main.qc.
Referenced by StartFrame().
string gametypefilter
Definition at line 238 of file sv_main.qc.
Referenced by SV_OnEntityPreSpawnFunction().
float lastground
Definition at line 28 of file sv_main.qc.
vector originjitter
Definition at line 235 of file sv_main.qc.
Referenced by SUB(), and SV_OnEntityPreSpawnFunction().
int state
Definition at line 29 of file sv_main.qc.