Xonotic: menu/xonotic/campaign.qh File Reference
campaign.qh File Reference
#include "listbox.qh"
Functions
METHOD (XonoticCampaignList, configureXonoticCampaignList, void(entity))
METHOD (XonoticCampaignList, draw, void(entity))
METHOD (XonoticCampaignList, drawListBoxItem, void(entity, int, vector, bool, bool))
METHOD (XonoticCampaignList, doubleClickListBoxItem, void(entity, float, vector))
METHOD (XonoticCampaignList, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticCampaignList, setSelected, void(entity, float))
METHOD (XonoticCampaignList, keyDown, float(entity, float, float, float))
METHOD (XonoticCampaignList, campaignGo, void(entity, float))
METHOD (XonoticCampaignList, destroy, void(entity))
METHOD (XonoticCampaignList, loadCvars, void(entity))
METHOD (XonoticCampaignList, saveCvars, void(entity))
entity makeXonoticCampaignList ()
void CampaignList_LoadMap (entity btn, entity me)
void MultiCampaign_Next (entity btn, entity me)
void MultiCampaign_Prev (entity btn, entity me)
Function Documentation
void CampaignList_LoadMap (entity btn, entity me)
Definition at line 259 of file campaign.qc.
References CampaignSetup().
Referenced by XonoticCampaignList_doubleClickListBoxItem(), XonoticCampaignList_keyDown(), and XonoticSingleplayerDialog_fill().
 {
     if(me.selectedItem >= me.nItems || me.selectedItem < 0)
         return;
     CampaignSetup(me.selectedItem);
 }
entity makeXonoticCampaignList ()
Definition at line 49 of file campaign.qc.
References entity(), me, and NEW.
Referenced by XonoticSingleplayerDialog_fill().
 {
     entity me;
     me = NEW(XonoticCampaignList);
     me.configureXonoticCampaignList(me);
     return me;
 }
METHOD (XonoticCampaignList , configureXonoticCampaignList , void(entity))
METHOD (XonoticCampaignList , draw , void(entity))
METHOD (XonoticCampaignList , drawListBoxItem , void(entity, int, vector, bool, bool))
METHOD (XonoticCampaignList , doubleClickListBoxItem , void(entity, float, vector))
METHOD (XonoticCampaignList , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticCampaignList , setSelected , void(entity, float))
METHOD (XonoticCampaignList , keyDown , float(entity, float, float, float))
METHOD (XonoticCampaignList , campaignGo , void(entity, float))
METHOD (XonoticCampaignList , destroy , void(entity))
METHOD (XonoticCampaignList , loadCvars , void(entity))
METHOD (XonoticCampaignList , saveCvars , void(entity))
void MultiCampaign_Next (entity btn, entity me)
Definition at line 155 of file campaign.qc.
Referenced by XonoticSingleplayerDialog_fill().
 {
     me.campaignGo(me, +1);
 }
void MultiCampaign_Prev (entity btn, entity me)
Definition at line 159 of file campaign.qc.
Referenced by XonoticSingleplayerDialog_fill().
 {
     me.campaignGo(me, -1);
 }