Xonotic: server/scores_rules.qc File Reference
scores_rules.qc File Reference
#include "scores_rules.qh"
#include "client.qh"
#include "scores.qh"
Functions
int AvailableTeams ()
void CheckAllowedTeams (entity for_whom)
int NumTeams (int teams)
void ScoreRules_basics (int teams, float sprio, float stprio, float score_enabled)
void ScoreRules_basics_end ()
void ScoreRules_generic ()
Variables
int ScoreRules_teams
Function Documentation
int AvailableTeams ()
Definition at line 15 of file scores_rules.qc.
References NumTeams(), and ScoreRules_teams.
Referenced by bot_fixcount(), CheckAllowedTeams(), and ClientConnect().
 {
     return NumTeams(ScoreRules_teams);
     // NOTE: this method is unreliable, as forced teams set the c* globals to weird values
     //return boolean(c1 >= 0) + boolean(c2 >= 0) + boolean(c3 >= 0) + boolean(c4 >= 0);
 }
void CheckAllowedTeams (entity for_whom)
Definition at line 218 of file teamplay.qc.
Referenced by bot_removefromlargestteam(), ClientCommand_selectteam(), ClientConnect(), ctf_ScoreRules(), dom_DelayedInit(), GameCommand_moveplayer(), GameCommand_shuffleteams(), invasion_ScoreRules(), ons_ScoreRules(), and ScoreRules_generic().
 {
     int teams_mask = 0;
     c1 = c2 = c3 = c4 = -1;
     cb1 = cb2 = cb3 = cb4 = 0;
     string teament_name = string_null;
     bool mutator_returnvalue = MUTATOR_CALLHOOK(CheckAllowedTeams, teams_mask, teament_name);
     teams_mask = M_ARGV(0, float);
     teament_name = M_ARGV(1, string);
     if(!mutator_returnvalue)
     {
         if(teams_mask & BIT(0)) c1 = 0;
         if(teams_mask & BIT(1)) c2 = 0;
         if(teams_mask & BIT(2)) c3 = 0;
         if(teams_mask & BIT(3)) c4 = 0;
     }
     // find out what teams are allowed if necessary
     if(teament_name)
     {
         entity head = find(NULL, classname, teament_name);
         while(head)
         {
             switch(head.team)
             {
                 case NUM_TEAM_1: c1 = 0; break;
                 case NUM_TEAM_2: c2 = 0; break;
                 case NUM_TEAM_3: c3 = 0; break;
                 case NUM_TEAM_4: c4 = 0; break;
             }
             head = find(head, classname, teament_name);
         }
     }
     // TODO: Balance quantity of bots across > 2 teams when bot_vs_human is set (and remove next line)
     if(AvailableTeams() == 2)
     if(autocvar_bot_vs_human && for_whom)
     {
         if(autocvar_bot_vs_human > 0)
         {
             // find last team available
             if(IS_BOT_CLIENT(for_whom))
             {
                 if(c4 >= 0) { c3 = c2 = c1 = -1; }
                 else if(c3 >= 0) { c4 = c2 = c1 = -1; }
                 else { c4 = c3 = c1 = -1; }
                 // no further cases, we know at least 2 teams exist
             }
             else
             {
                 if(c1 >= 0) { c2 = c3 = c4 = -1; }
                 else if(c2 >= 0) { c1 = c3 = c4 = -1; }
                 else { c1 = c2 = c4 = -1; }
                 // no further cases, bots have one of the teams
             }
         }
         else
         {
             // find first team available
             if(IS_BOT_CLIENT(for_whom))
             {
                 if(c1 >= 0) { c2 = c3 = c4 = -1; }
                 else if(c2 >= 0) { c1 = c3 = c4 = -1; }
                 else { c1 = c2 = c4 = -1; }
                 // no further cases, we know at least 2 teams exist
             }
             else
             {
                 if(c4 >= 0) { c3 = c2 = c1 = -1; }
                 else if(c3 >= 0) { c4 = c2 = c1 = -1; }
                 else { c4 = c3 = c1 = -1; }
                 // no further cases, bots have one of the teams
             }
         }
     }
     if(!for_whom)
         return;
     // if player has a forced team, ONLY allow that one
     if(for_whom.team_forced == NUM_TEAM_1 && c1 >= 0)
         c2 = c3 = c4 = -1;
     else if(for_whom.team_forced == NUM_TEAM_2 && c2 >= 0)
         c1 = c3 = c4 = -1;
     else if(for_whom.team_forced == NUM_TEAM_3 && c3 >= 0)
         c1 = c2 = c4 = -1;
     else if(for_whom.team_forced == NUM_TEAM_4 && c4 >= 0)
         c1 = c2 = c3 = -1;
 }
int NumTeams (int teams)
Definition at line 10 of file scores_rules.qc.
References BIT, and boolean.
Referenced by AvailableTeams(), ctf_DelayedInit(), kh_GetMissingTeams(), kh_Key_AllOwnedByWhichTeam(), kh_LoserTeam(), kh_StartRound(), and kh_WinnerTeam().
 {
     return boolean(teams & BIT(0)) + boolean(teams & BIT(1)) + boolean(teams & BIT(2)) + boolean(teams & BIT(3));
 }
void ScoreRules_basics (int teams, float sprio, float stprio, float score_enabled)
Definition at line 24 of file scores_rules.qc.
References FOREACH, INDEPENDENT_PLAYERS, ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_teams, SFL_LOWER_IS_BETTER, ST_SCORE, and teams.
Referenced by assault_ScoreRules(), ctf_ScoreRules(), cts_ScoreRules(), freezetag_ScoreRules(), invasion_ScoreRules(), ka_ScoreRules(), kh_ScoreRules(), lms_ScoreRules(), ons_ScoreRules(), race_ScoreRules(), REGISTER_MUTATOR(), ScoreRules_dom(), and ScoreRules_generic().
 {
     FOREACH(Scores, true, {
         ScoreInfo_SetLabel_PlayerScore(it, "", 0);
     });
     for(int i = 0; i < MAX_TEAMSCORE; ++i)
         ScoreInfo_SetLabel_TeamScore(i, "", 0);
     ScoreRules_teams = teams;
     if(score_enabled)
         ScoreInfo_SetLabel_TeamScore  (ST_SCORE,        "score",     stprio);
     if (!INDEPENDENT_PLAYERS)
         ScoreInfo_SetLabel_PlayerScore(SP_KILLS,        "kills",     0);
     ScoreInfo_SetLabel_PlayerScore(SP_DEATHS,       "deaths",    SFL_LOWER_IS_BETTER);
     if (!INDEPENDENT_PLAYERS)
         ScoreInfo_SetLabel_PlayerScore(SP_SUICIDES,     "suicides",  SFL_LOWER_IS_BETTER);
     if(score_enabled)
         ScoreInfo_SetLabel_PlayerScore(SP_SCORE,        "score",     sprio);
     ScoreInfo_SetLabel_PlayerScore(SP_DMG, "dmg", 0);
     ScoreInfo_SetLabel_PlayerScore(SP_DMGTAKEN, "dmgtaken", SFL_LOWER_IS_BETTER);
     ScoreInfo_SetLabel_PlayerScore(SP_ELO, "elo", 0);
 }
void ScoreRules_basics_end ()
Definition at line 52 of file scores_rules.qc.
References ScoreInfo_Init(), and ScoreRules_teams.
Referenced by assault_ScoreRules(), ctf_ScoreRules(), cts_ScoreRules(), freezetag_ScoreRules(), invasion_ScoreRules(), ka_ScoreRules(), kh_ScoreRules(), lms_ScoreRules(), ons_ScoreRules(), race_ScoreRules(), REGISTER_MUTATOR(), ScoreRules_dom(), and ScoreRules_generic().
 {
     ScoreInfo_Init(ScoreRules_teams);
 }
void ScoreRules_generic ()
Definition at line 56 of file scores_rules.qc.
References BIT, c1, c2, c3, c4, CheckAllowedTeams(), NULL, ScoreRules_basics(), ScoreRules_basics_end(), SFL_SORT_PRIO_PRIMARY, teamplay, and teams.
Referenced by default_delayedinit().
 {
     if(teamplay)
     {
         CheckAllowedTeams(NULL);
         int teams = 0;
         if(c1 >= 0) teams |= BIT(0);
         if(c2 >= 0) teams |= BIT(1);
         if(c3 >= 0) teams |= BIT(2);
         if(c4 >= 0) teams |= BIT(3);
         ScoreRules_basics(teams, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_PRIMARY, true);
     }
     else
         ScoreRules_basics(0, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_PRIMARY, true);
     ScoreRules_basics_end();
 }
Variable Documentation
int ScoreRules_teams
Definition at line 6 of file scores_rules.qc.
Referenced by AvailableTeams(), ScoreRules_basics(), and ScoreRules_basics_end().