Xonotic: server/item_key.qc File Reference
item_key.qc File Reference
#include "item_key.qh"
#include "../common/triggers/subs.qh"
#include "../common/monsters/_mod.qh"
#include "../common/notifications/all.qh"
#include "../common/util.qh"
#include "../lib/warpzone/util_server.qh"
Functions
void item_key_touch (entity this, entity toucher)
Key touch handler.
string item_keys_keylist (float keylist)
bool item_keys_usekey (entity l, entity p)
void spawn_item_key (entity this)
Spawn a key with given model, key code and color.
spawnfunc (item_key)
spawnfunc (item_key1)
spawnfunc (item_key2)
Function Documentation
void item_key_touch (entity this, entity toucher)
Key touch handler.
Definition at line 71 of file item_key.qc.
References centerprint(), IS_PLAYER, itemkeys, message, noise, play2(), PS, and SUB_UseTargets().
Referenced by spawn_item_key().
 {
     if (!IS_PLAYER(toucher))
         return;
     // player already picked up this key
     if (PS(toucher).itemkeys & this.itemkeys)
         return;
     PS(toucher).itemkeys |= this.itemkeys;
     play2(toucher, this.noise);
     centerprint(toucher, this.message);
     string oldmsg = this.message;
     this.message = "";
     SUB_UseTargets(this, toucher, toucher); // TODO: should we be using toucher for the trigger here?
     this.message = oldmsg;
 };
string item_keys_keylist (float keylist)
Definition at line 36 of file item_key.qc.
References lowestbit(), and strcat().
Referenced by door_check_keys(), and trigger_keylock_touch().
{
     // no keys
     if (!keylist)
         return "";
     // one key
     if ((keylist & (keylist-1)) == 0)
         return strcat("the ", item_keys_names[lowestbit(keylist)]);
     string n = "";
     int base = 0;
     while (keylist) {
         int l = lowestbit(keylist);
         if (n)
             n = strcat(n, ", the ", item_keys_names[base + l]);
         else
             n = strcat("the ", item_keys_names[base + l]);
         keylist = bitshift(keylist,  -(l + 1));
         base+= l + 1;
     }
     return n;
 }
bool item_keys_usekey (entity l, entity p)
Definition at line 18 of file item_key.qc.
References PS.
Referenced by trigger_keylock_touch().
 {
     int valid = l.itemkeys & PS(p).itemkeys;
     if (!valid) {
         // player has none of the needed keys
         return false;
     } else if (l.itemkeys == valid) {
         // ALL needed keys were given
         l.itemkeys = 0;
         return true;
     } else {
         // only some of the needed keys were given
         l.itemkeys &= ~valid;
         return true;
     }
 }
void spawn_item_key (entity this)
Spawn a key with given model, key code and color.
Definition at line 94 of file item_key.qc.
References droptofloor, EF_LOWPRECISION, effects, item_key_touch(), mdl, MF_ROTATE, model, modelflags, MOVETYPE_NONE, MOVETYPE_TOSS, noalign, noise, origin, precache_sound(), set_movetype(), setorigin(), solid, SOLID_TRIGGER, and spawnflags.
Referenced by spawnfunc().
 {
     precache_model(this.model);
     if (this.spawnflags & 1) // FLOATING
         this.noalign = 1;
     if (this.noalign)
         set_movetype(this, MOVETYPE_NONE);
     else
         set_movetype(this, MOVETYPE_TOSS);
     precache_sound(this.noise);
     this.mdl = this.model;
     this.effects = EF_LOWPRECISION;
     _setmodel(this, this.model);
     //setsize(this, '-16 -16 -24', '16 16 32');
     setorigin(this, this.origin + '0 0 32');
     setsize(this, '-16 -16 -56', '16 16 0');
     this.modelflags |= MF_ROTATE;
     this.solid = SOLID_TRIGGER;
     if (!this.noalign)
     {
         // first nudge it off the floor a little bit to avoid math errors
         setorigin(this, this.origin + '0 0 1');
         // note droptofloor returns false if stuck/or would fall too far
         droptofloor(this);
     }
     settouch(this, item_key_touch);
 };
spawnfunc (item_key)
Definition at line 155 of file item_key.qc.
References BIT, colormod, ITEM_KEY_BIT, itemkeys, lowestbit(), message, model, netname, noise, objerror(), SND, spawn_item_key(), strcat(), string_null, strzone(), and vector().
 {
     string _netname;
     vector _colormod;
     // reject this entity if more than one key was set!
     if (this.itemkeys>0 && (this.itemkeys & (this.itemkeys-1)) != 0) {
         objerror(this, "item_key.itemkeys must contain only 1 bit set specifying the key it represents!");
         delete(this);
         return;
     }
     // find default netname and colormod
     switch(this.itemkeys) {
     case BIT(0):
         _netname = "GOLD key";
         _colormod = '1 .9 0';
         break;
     case BIT(1):
         _netname = "SILVER key";
         _colormod = '.9 .9 .9';
         break;
     case BIT(2):
         _netname = "BRONZE key";
         _colormod = '.6 .25 0';
         break;
     case BIT(3):
         _netname = "RED keycard";
         _colormod = '.9 0 0';
         break;
     case BIT(4):
         _netname = "BLUE keycard";
         _colormod = '0 0 .9';
         break;
     case BIT(5):
         _netname = "GREEN keycard";
         _colormod = '0 .9 0';
         break;
     default:
         _netname = "FLUFFY PINK keycard";
         _colormod = '1 1 1';
         if (this.netname == "") {
             objerror(this, "item_key doesn't have a default name for this key and a custom one was not specified!");
             delete(this);
             return;
         }
         break;
     }
     // find default model
     string _model = string_null;
     if (this.itemkeys <= ITEM_KEY_BIT(2)) {
         _model = "models/keys/key.md3";
     } else if (this.itemkeys >= ITEM_KEY_BIT(3) && this.itemkeys <= ITEM_KEY_BIT(5)) {
         _model = "models/keys/key.md3"; // FIXME: replace it by a keycard model!
     } else if (this.model == "") {
         objerror(this, "item_key doesn't have a default model for this key and a custom one was not specified!");
         delete(this);
         return;
     }
     // set defailt netname
     if (this.netname == "")
         this.netname = _netname;
     // set default colormod
     if (!this.colormod)
         this.colormod = _colormod;
     // set default model
     if (this.model == "")
         this.model = _model;
     // set default pickup message
     if (this.message == "")
         this.message = strzone(strcat("You've picked up the ", this.netname, "!"));
     if (this.noise == "")
         this.noise = strzone(SND(ITEMPICKUP));
     // save the name for later
     item_keys_names[lowestbit(this.itemkeys)] = this.netname;
     // put the key on the map
     spawn_item_key(this);
 }
spawnfunc (item_key1)
Definition at line 262 of file item_key.qc.
References classname, ITEM_KEY_BIT, and itemkeys.
 {
     this.classname = "item_key";
     this.itemkeys = ITEM_KEY_BIT(1);
     spawnfunc_item_key(this);
 };
spawnfunc (item_key2)
Definition at line 281 of file item_key.qc.
References classname, ITEM_KEY_BIT, and itemkeys.
 {
     this.classname = "item_key";
     this.itemkeys = ITEM_KEY_BIT(0);
     spawnfunc_item_key(this);
 };