Xonotic: common/mutators/mutator/vampirehook/sv_vampirehook.qc File Reference
sv_vampirehook.qc File Reference
#include "sv_vampirehook.qh"
Functions
MUTATOR_HOOKFUNCTION (vh, GrappleHookThink)
REGISTER_MUTATOR (vh, expr_evaluate(autocvar_g_vampirehook))
Variables
string autocvar_g_vampirehook
float autocvar_g_vampirehook_damage
float autocvar_g_vampirehook_damagerate
float autocvar_g_vampirehook_health_steal
bool autocvar_g_vampirehook_teamheal
float last_dmg
Function Documentation
MUTATOR_HOOKFUNCTION (vh , GrappleHookThink)
Definition at line 13 of file sv_vampirehook.qc.
References autocvar_g_vampirehook_damage, autocvar_g_vampirehook_damagerate, autocvar_g_vampirehook_teamheal, Damage(), DIFF_TEAM, DMG_NOWEP, entity(), GetResource(), IS_PLAYER, M_ARGV, min(), RES_HEALTH, SAME_TEAM, SetResourceExplicit(), TakeResource(), and time.
 {
     entity thehook = M_ARGV(0, entity);
     entity dmgent = ((SAME_TEAM(thehook.owner, thehook.aiment) && autocvar_g_vampirehook_teamheal) ? thehook.owner : thehook.aiment);
     if(IS_PLAYER(thehook.aiment))
     if(thehook.last_dmg < time)
     if(!STAT(FROZEN, thehook.aiment))
     if(time >= game_starttime)
     if(DIFF_TEAM(thehook.owner, thehook.aiment) || autocvar_g_vampirehook_teamheal)
     if(GetResource(thehook.aiment, RES_HEALTH) > 0)
     if(autocvar_g_vampirehook_damage)
     {
         thehook.last_dmg = time + autocvar_g_vampirehook_damagerate;
         thehook.owner.damage_dealt += autocvar_g_vampirehook_damage;
         Damage(dmgent, thehook, thehook.owner, autocvar_g_vampirehook_damage, WEP_HOOK.m_id, DMG_NOWEP, thehook.origin, '0 0 0');
         entity targ = ((SAME_TEAM(thehook.owner, thehook.aiment)) ? thehook.aiment : thehook.owner);
         // TODO: we can't do this due to an issue with globals and the mutator arguments
         //Heal(targ, thehook.owner, autocvar_g_vampirehook_health_steal, g_pickup_healthsmall_max);
         SetResourceExplicit(targ, RES_HEALTH, min(GetResource(targ, RES_HEALTH) + autocvar_g_vampirehook_health_steal, g_pickup_healthsmall_max));
         if(dmgent == thehook.owner)
             TakeResource(dmgent, RES_HEALTH, autocvar_g_vampirehook_damage); // FIXME: friendly fire?!
     }
 }
REGISTER_MUTATOR (vh , expr_evaluate(autocvar_g_vampirehook))
Variable Documentation
string autocvar_g_vampirehook
Definition at line 3 of file sv_vampirehook.qc.
float autocvar_g_vampirehook_damage
Definition at line 7 of file sv_vampirehook.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_vampirehook_damagerate
Definition at line 8 of file sv_vampirehook.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_vampirehook_health_steal
Definition at line 9 of file sv_vampirehook.qc.
bool autocvar_g_vampirehook_teamheal
Definition at line 6 of file sv_vampirehook.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float last_dmg
Definition at line 11 of file sv_vampirehook.qc.