Xonotic: common/gamemodes/gamemode/keepaway/sv_keepaway.qc File Reference
sv_keepaway.qc File Reference
#include "sv_keepaway.qh"
#include <common/effects/all.qh>
#include <server/client.qh>
#include <server/gamelog.qh>
#include <server/damage.qh>
#include <server/items/items.qh>
#include <server/world.qh>
Functions
void havocbot_goalrating_ball (entity this, float ratingscale, vector org)
void havocbot_role_ka_carrier (entity this)
void havocbot_role_ka_collector (entity this)
bool ka_ballcarrier_waypointsprite_visible_for_player (entity this, entity player, entity view)
void ka_DamageEvent (entity this, entity inflictor, entity attacker, float damage, int deathtype,.entity weaponentity, vector hitloc, vector force)
void ka_DropEvent (entity player)
void ka_EventLog (string mode, entity actor)
void ka_Handler_CheckBall (entity this)
void ka_Initialize ()
void ka_PlayerReset (entity player)
void ka_RemoveBall (entity ball)
void ka_RemoveBalls ()
void ka_RespawnBall (entity this)
void ka_SpawnBall ()
void ka_SpawnBalls (int ballcount)
void ka_TimeScoring (entity this)
void ka_TouchEvent (entity this, entity toucher)
MODEL (KA_BALL, "models/orbs/orbblue.md3")
MUTATOR_HOOKFUNCTION (ka, PlayerDies)
MUTATOR_HOOKFUNCTION (ka, GiveFragsForKill)
MUTATOR_HOOKFUNCTION (ka, Scores_CountFragsRemaining)
MUTATOR_HOOKFUNCTION (ka, PlayerPreThink)
MUTATOR_HOOKFUNCTION (ka, PlayerUseKey)
MUTATOR_HOOKFUNCTION (ka, Damage_Calculate)
MUTATOR_HOOKFUNCTION (ka, ClientDisconnect)
MUTATOR_HOOKFUNCTION (ka, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (ka, PlayerPowerups)
MUTATOR_HOOKFUNCTION (ka, PlayerPhysics_UpdateStats)
MUTATOR_HOOKFUNCTION (ka, BotShouldAttack)
MUTATOR_HOOKFUNCTION (ka, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (ka, DropSpecialItems)
Variables
float autocvar_g_keepaway_ballcarrier_damage
int autocvar_g_keepaway_ballcarrier_effects
float autocvar_g_keepaway_ballcarrier_force
float autocvar_g_keepaway_ballcarrier_highspeed
float autocvar_g_keepaway_ballcarrier_selfdamage
float autocvar_g_keepaway_ballcarrier_selfforce
float autocvar_g_keepaway_noncarrier_damage
float autocvar_g_keepaway_noncarrier_force
float autocvar_g_keepaway_noncarrier_selfdamage
float autocvar_g_keepaway_noncarrier_selfforce
bool autocvar_g_keepaway_noncarrier_warn
int autocvar_g_keepaway_score_bckill
int autocvar_g_keepaway_score_killac
float autocvar_g_keepaway_score_timeinterval
int autocvar_g_keepaway_score_timepoints
float autocvar_g_keepawayball_damageforcescale
int autocvar_g_keepawayball_effects
float autocvar_g_keepawayball_respawntime
int autocvar_g_keepawayball_trail_color
entity ballcarried
bool pushable
Function Documentation
havocbot_goalrating_ball()
void havocbot_goalrating_ball (entity this, float ratingscale, vector org)
Definition at line 295 of file sv_keepaway.qc.
References entity(), g_kaballs, IL_EACH, navigation_routerating(), and NULL.
Referenced by havocbot_role_ka_collector().
 {
     entity ball = NULL, ball_carried = NULL;
     // stops at last ball, prefers ball without carrier
     IL_EACH(g_kaballs, it.owner != this,
     {
         if(it.owner)
             ball_carried = it.owner;
         else
             ball = it;
     });
     if(ball)
         navigation_routerating(this, ball, ratingscale, 2000);
     else if(ball_carried)
         navigation_routerating(this, ball_carried, ratingscale, 2000);
 }
havocbot_role_ka_carrier()
void havocbot_role_ka_carrier (entity this)
Definition at line 314 of file sv_keepaway.qc.
References ballcarried, havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_goalrating_waypoints(), havocbot_role_ka_collector(), IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_expire(), navigation_goalrating_timeout_set(), and origin.
Referenced by havocbot_role_ka_collector(), and MUTATOR_HOOKFUNCTION().
 {
     if (IS_DEAD(this))
         return;
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_items(this, 10000, this.origin, 10000);
         havocbot_goalrating_enemyplayers(this, 10000, this.origin, 10000);
         havocbot_goalrating_waypoints(this, 1, this.origin, 3000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
     if (!this.ballcarried)
     {
         this.havocbot_role = havocbot_role_ka_collector;
         navigation_goalrating_timeout_expire(this, 2);
     }
 }
havocbot_role_ka_collector()
void havocbot_role_ka_collector (entity this)
Definition at line 337 of file sv_keepaway.qc.
References ballcarried, havocbot_goalrating_ball(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_role_ka_carrier(), IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_expire(), navigation_goalrating_timeout_set(), and origin.
Referenced by havocbot_role_ka_carrier(), and MUTATOR_HOOKFUNCTION().
 {
     if (IS_DEAD(this))
         return;
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_items(this, 10000, this.origin, 10000);
         havocbot_goalrating_enemyplayers(this, 500, this.origin, 10000);
         havocbot_goalrating_ball(this, 8000, this.origin);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
     if (this.ballcarried)
     {
         this.havocbot_role = havocbot_role_ka_carrier;
         navigation_goalrating_timeout_expire(this, 2);
     }
 }
ka_ballcarrier_waypointsprite_visible_for_player()
bool ka_ballcarrier_waypointsprite_visible_for_player (entity this, entity player, entity view)
Definition at line 32 of file sv_keepaway.qc.
References IS_SPEC.
Referenced by ka_TouchEvent().
 {
     if(view.ballcarried)
         if(IS_SPEC(player))
             return false; // we don't want spectators of the ballcarrier to see the attached waypoint on the top of their screen
     // TODO: Make the ballcarrier lack a waypointsprite whenever they have the invisibility powerup
     return true;
 }
ka_DamageEvent()
void ka_DamageEvent (entity this, entity inflictor, entity attacker, float damage, int deathtype, .entity weaponentity, vector hitloc, vector force)
Definition at line 92 of file sv_keepaway.qc.
References ITEM_DAMAGE_NEEDKILL, and ka_RespawnBall().
Referenced by ka_DropEvent(), and ka_SpawnBall().
 {
     if(ITEM_DAMAGE_NEEDKILL(deathtype))
         ka_RespawnBall(this);
 }
ka_DropEvent()
void ka_DropEvent (entity player)
Definition at line 173 of file sv_keepaway.qc.
References ATTEN_NONE, autocvar_g_keepawayball_respawntime, CH_TRIGGER, crandom, DAMAGE_YES, EF_NODRAW, entity(), g_damagedbycontents, IL_PUSH(), ka_DamageEvent(), ka_EventLog(), ka_PlayerReset(), ka_RespawnBall(), ka_TouchEvent(), MOVETYPE_BOUNCE, navigation_dynamicgoal_set(), NULL, set_movetype(), setorigin(), setthink, sound, SPRITERULE_DEFAULT, time, and VOL_BASE.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity ball = player.ballcarried;
     if(!ball) { return; }
     // reset the ball
     setattachment(ball, NULL, "");
     set_movetype(ball, MOVETYPE_BOUNCE);
     ball.wait = time + 1;
     settouch(ball, ka_TouchEvent);
     setthink(ball, ka_RespawnBall);
     ball.nextthink = time + autocvar_g_keepawayball_respawntime;
     ball.takedamage = DAMAGE_YES;
     ball.event_damage = ka_DamageEvent;
     ball.damagedbycontents = true;
     IL_PUSH(g_damagedbycontents, ball);
     ball.effects &= ~EF_NODRAW;
     setorigin(ball, player.origin + '0 0 10');
     ball.velocity = '0 0 200' + '0 100 0'*crandom() + '100 0 0'*crandom();
     ball.owner = NULL;
     navigation_dynamicgoal_set(ball, player);
     // messages and sounds
     ka_EventLog("dropped", player);
     Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_KEEPAWAY_DROPPED, player.netname);
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_KEEPAWAY_DROPPED, player.netname);
     sound(NULL, CH_TRIGGER, SND_KA_DROPPED, VOL_BASE, ATTEN_NONE); // ATTEN_NONE (it's a sound intended to be heard anywhere)
     // waypoints
     WaypointSprite_Spawn(WP_KaBall, 0, 0, ball, '0 0 64', NULL, ball.team, ball, waypointsprite_attachedforcarrier, false, RADARICON_FLAGCARRIER);
     WaypointSprite_UpdateRule(ball.waypointsprite_attachedforcarrier, 0, SPRITERULE_DEFAULT);
     WaypointSprite_Ping(ball.waypointsprite_attachedforcarrier);
     ka_PlayerReset(player);
 }
ka_EventLog()
void ka_EventLog (string mode, entity actor)
Definition at line 43 of file sv_keepaway.qc.
References autocvar_sv_eventlog, ftos(), GameLogEcho(), NULL, and strcat().
Referenced by ka_DropEvent(), and ka_TouchEvent().
 {
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":ka:", mode, ((actor != NULL) ? (strcat(":", ftos(actor.playerid))) : "")));
 }
ka_Handler_CheckBall()
void ka_Handler_CheckBall (entity this)
Definition at line 266 of file sv_keepaway.qc.
References g_kaballs, IL_EMPTY, KA_BALL_COUNT, ka_RemoveBalls(), ka_SpawnBalls(), nextthink, and time.
Referenced by ka_Initialize().
 {
     if(time < game_starttime)
     {
         if (!IL_EMPTY(g_kaballs))
             ka_RemoveBalls();
     }
     else
     {
         if (IL_EMPTY(g_kaballs))
             ka_SpawnBalls(KA_BALL_COUNT); // ;)
     }
     this.nextthink = time;
 }
ka_Initialize()
void ka_Initialize ()
Definition at line 282 of file sv_keepaway.qc.
References g_kaballs, IL_NEW, ka_Handler, ka_Handler_CheckBall(), new_pure, setthink, and time.
Referenced by REGISTER_MUTATOR().
 {
     g_kaballs = IL_NEW();
     ka_Handler = new_pure(ka_Handler);
     setthink(ka_Handler, ka_Handler_CheckBall);
     ka_Handler.nextthink = time;
 }
ka_PlayerReset()
void ka_PlayerReset (entity player)
Definition at line 162 of file sv_keepaway.qc.
References autocvar_g_keepaway_ballcarrier_effects, GameRules_scoring_vip(), and NULL.
Referenced by ka_DropEvent(), and ka_RemoveBall().
 {
     player.ballcarried = NULL;
     GameRules_scoring_vip(player, false);
     WaypointSprite_Kill(player.waypointsprite_attachedforcarrier);
     // reset the player effects
     player.glow_trail = false;
     player.effects &= ~autocvar_g_keepaway_ballcarrier_effects;
 }
ka_RemoveBall()
void ka_RemoveBall (entity ball)
Definition at line 214 of file sv_keepaway.qc.
References entity(), and ka_PlayerReset().
Referenced by ka_RemoveBalls().
 {
     entity player = ball.owner;
     if (player) // it was attached
         ka_PlayerReset(player);
     else
         WaypointSprite_DetachCarrier(ball);
     delete(ball);
 }
ka_RemoveBalls()
void ka_RemoveBalls ()
Definition at line 224 of file sv_keepaway.qc.
References g_kaballs, IL_EACH, and ka_RemoveBall().
Referenced by ka_Handler_CheckBall().
 {
     IL_EACH(g_kaballs, true,
     {
         ka_RemoveBall(it);
     });
 }
ka_RespawnBall()
void ka_RespawnBall (entity this)
Definition at line 49 of file sv_keepaway.qc.
References angles, ATTEN_NONE, autocvar_g_keepawayball_effects, autocvar_g_keepawayball_respawntime, CH_TRIGGER, DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_DONOTENTER, DPCONTENTS_LAVA, DPCONTENTS_PLAYERCLIP, DPCONTENTS_SKY, DPCONTENTS_SLIME, DPCONTENTS_SOLID, effects, entity(), ka_TouchEvent(), makevectors, MoveToRandomMapLocation(), MOVETYPE_BOUNCE, navigation_dynamicgoal_set(), nextthink, NULL, origin, Q3SURFACEFLAG_SKY, SelectSpawnPoint(), set_movetype(), setorigin(), setthink, sound, team, time, vector(), velocity, and VOL_BASE.
Referenced by ka_DamageEvent(), ka_DropEvent(), ka_SpawnBall(), and ka_TouchEvent().
 {
     if(game_stopped) return;
     vector oldballorigin = this.origin;
     if(!MoveToRandomMapLocation(this, DPCONTENTS_SOLID | DPCONTENTS_CORPSE | DPCONTENTS_PLAYERCLIP, DPCONTENTS_SLIME | DPCONTENTS_LAVA | DPCONTENTS_SKY | DPCONTENTS_BODY | DPCONTENTS_DONOTENTER, Q3SURFACEFLAG_SKY, 10, 1024, 256))
     {
         entity spot = SelectSpawnPoint(this, true);
         setorigin(this, spot.origin);
         this.angles = spot.angles;
     }
     makevectors(this.angles);
     set_movetype(this, MOVETYPE_BOUNCE);
     this.velocity = '0 0 200';
     this.angles = '0 0 0';
     this.effects = autocvar_g_keepawayball_effects;
     settouch(this, ka_TouchEvent);
     setthink(this, ka_RespawnBall);
     this.nextthink = time + autocvar_g_keepawayball_respawntime;
     navigation_dynamicgoal_set(this, NULL);
     Send_Effect(EFFECT_ELECTRO_COMBO, oldballorigin, '0 0 0', 1);
     Send_Effect(EFFECT_ELECTRO_COMBO, this.origin, '0 0 0', 1);
     WaypointSprite_Spawn(WP_KaBall, 0, 0, this, '0 0 64', NULL, this.team, this, waypointsprite_attachedforcarrier, false, RADARICON_FLAGCARRIER);
     WaypointSprite_Ping(this.waypointsprite_attachedforcarrier);
     sound(this, CH_TRIGGER, SND_KA_RESPAWN, VOL_BASE, ATTEN_NONE); // ATTEN_NONE (it's a sound intended to be heard anywhere)
 }
ka_SpawnBall()
void ka_SpawnBall ()
Definition at line 232 of file sv_keepaway.qc.
References autocvar_g_keepawayball_damageforcescale, autocvar_g_keepawayball_trail_color, DAMAGE_YES, entity(), FL_ITEM, g_damagedbycontents, g_items, g_kaballs, IL_PUSH(), InitializeEntity(), ka_DamageEvent(), ka_RespawnBall(), ka_TouchEvent(), MOVETYPE_BOUNCE, navigation_dynamicgoal_init(), NULL, set_movetype(), setmodel, and SOLID_TRIGGER.
Referenced by ka_SpawnBalls().
 {
     entity e = new(keepawayball);
     setmodel(e, MDL_KA_BALL);
     setsize(e, '-16 -16 -20', '16 16 20'); // 20 20 20 was too big, player is only 16 16 24... gotta cheat with the Z (20) axis so that the particle isn't cut off
     e.damageforcescale = autocvar_g_keepawayball_damageforcescale;
     e.takedamage = DAMAGE_YES;
     e.event_damage = ka_DamageEvent;
     e.damagedbycontents = true;
     IL_PUSH(g_damagedbycontents, e);
     e.solid = SOLID_TRIGGER;
     set_movetype(e, MOVETYPE_BOUNCE);
     e.glow_color = autocvar_g_keepawayball_trail_color;
     e.glow_trail = true;
     e.flags = FL_ITEM;
     IL_PUSH(g_items, e);
     e.pushable = true;
     settouch(e, ka_TouchEvent);
     e.owner = NULL;
     IL_PUSH(g_kaballs, e);
     navigation_dynamicgoal_init(e, false);
     InitializeEntity(e, ka_RespawnBall, INITPRIO_SETLOCATION); // is this the right priority? Neh, I have no idea.. Well-- it works! So.
 }
ka_SpawnBalls()
void ka_SpawnBalls (int ballcount)
Definition at line 257 of file sv_keepaway.qc.
References ka_SpawnBall(), and max().
Referenced by ka_Handler_CheckBall().
 {
     int realballcount = max(1, ballcount); // never allow less than 1 ball to spawn
     for(int j = 0; j < realballcount; ++j)
     {
         ka_SpawnBall();
     }
 }
ka_TimeScoring()
void ka_TimeScoring (entity this)
Definition at line 80 of file sv_keepaway.qc.
References autocvar_g_keepaway_score_timeinterval, autocvar_g_keepaway_score_timepoints, GameRules_scoring_add, nextthink, owner, and time.
Referenced by ka_TouchEvent().
 {
     if(this.owner.ballcarried)
     { // add points for holding the ball after a certain amount of time
         if(autocvar_g_keepaway_score_timepoints)
             GameRules_scoring_add(this.owner, SCORE, autocvar_g_keepaway_score_timepoints);
         GameRules_scoring_add(this.owner, KEEPAWAY_BCTIME, autocvar_g_keepaway_score_timeinterval);
         this.nextthink = time + autocvar_g_keepaway_score_timeinterval;
     }
 }
ka_TouchEvent()
void ka_TouchEvent (entity this, entity toucher)
Definition at line 98 of file sv_keepaway.qc.
References ATTEN_NONE, ATTEN_NORM, autocvar_g_keepaway_ballcarrier_effects, autocvar_g_keepaway_score_timeinterval, autocvar_g_keepawayball_trail_color, CH_TRIGGER, DAMAGE_NO, damagedbycontents, EF_NODRAW, effects, func_null(), g_damagedbycontents, GameRules_scoring_add, GameRules_scoring_vip(), IL_REMOVE(), IS_DEAD, IS_PLAYER, ka_ballcarrier_waypointsprite_visible_for_player(), ka_EventLog(), ka_RespawnBall(), ka_TimeScoring(), MOVETYPE_NONE, navigation_dynamicgoal_unset(), nextthink, NULL, origin, owner, Q3SURFACEFLAG_NOIMPACT, set_movetype(), setorigin(), setthink, sound, SPRITERULE_DEFAULT, takedamage, time, trace_dphitq3surfaceflags, velocity, VOL_BASE, and wait.
Referenced by ka_DropEvent(), ka_RespawnBall(), and ka_SpawnBall().
 {
     if (!this || game_stopped)
         return;
     if(trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOIMPACT)
     { // The ball fell off the map, respawn it since players can't get to it
         ka_RespawnBall(this);
         return;
     }
     if(toucher.ballcarried) { return; }
     if(IS_DEAD(toucher)) { return; }
     if(STAT(FROZEN, toucher)) { return; }
     if (!IS_PLAYER(toucher))
     {  // The ball just touched an object, most likely the world
         Send_Effect(EFFECT_BALL_SPARKS, this.origin, '0 0 0', 1);
         sound(this, CH_TRIGGER, SND_KA_TOUCH, VOL_BASE, ATTEN_NORM);
         return;
     }
     else if(this.wait > time) { return; }
     // attach the ball to the player
     this.owner = toucher;
     toucher.ballcarried = this;
     GameRules_scoring_vip(toucher, true);
     setattachment(this, toucher, "");
     setorigin(this, '0 0 0');
     // make the ball invisible/unable to do anything/set up time scoring
     this.velocity = '0 0 0';
     set_movetype(this, MOVETYPE_NONE);
     this.effects |= EF_NODRAW;
     settouch(this, func_null);
     setthink(this, ka_TimeScoring);
     this.nextthink = time + autocvar_g_keepaway_score_timeinterval;
     this.takedamage = DAMAGE_NO;
     this.event_damage = func_null;
     this.damagedbycontents = false;
     IL_REMOVE(g_damagedbycontents, this);
     navigation_dynamicgoal_unset(this);
     // apply effects to player
     toucher.glow_color = autocvar_g_keepawayball_trail_color;
     toucher.glow_trail = true;
     toucher.effects |= autocvar_g_keepaway_ballcarrier_effects;
     // messages and sounds
     ka_EventLog("pickup", toucher);
     Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_KEEPAWAY_PICKUP, toucher.netname);
     Send_Notification(NOTIF_ALL_EXCEPT, toucher, MSG_CENTER, CENTER_KEEPAWAY_PICKUP, toucher.netname);
     Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_KEEPAWAY_PICKUP_SELF);
     sound(this.owner, CH_TRIGGER, SND_KA_PICKEDUP, VOL_BASE, ATTEN_NONE); // ATTEN_NONE (it's a sound intended to be heard anywhere)
     // scoring
     GameRules_scoring_add(toucher, KEEPAWAY_PICKUPS, 1);
     // waypoints
     WaypointSprite_AttachCarrier(WP_KaBallCarrier, toucher, RADARICON_FLAGCARRIER);
     toucher.waypointsprite_attachedforcarrier.waypointsprite_visible_for_player = ka_ballcarrier_waypointsprite_visible_for_player;
     WaypointSprite_UpdateRule(toucher.waypointsprite_attachedforcarrier, 0, SPRITERULE_DEFAULT);
     WaypointSprite_Ping(toucher.waypointsprite_attachedforcarrier);
     WaypointSprite_Kill(this.waypointsprite_attachedforcarrier);
 }
MODEL()
MODEL (KA_BALL , "models/orbs/orbblue.md3")
MUTATOR_HOOKFUNCTION() [1/13]
MUTATOR_HOOKFUNCTION (ka , PlayerDies)
Definition at line 365 of file sv_keepaway.qc.
References autocvar_g_keepaway_noncarrier_warn, autocvar_g_keepaway_score_bckill, autocvar_g_keepaway_score_killac, entity(), GameRules_scoring_add, IS_PLAYER, ka_DropEvent(), and M_ARGV.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     if((frag_attacker != frag_target) && (IS_PLAYER(frag_attacker)))
     {
         if(frag_target.ballcarried) { // add to amount of times killing carrier
             GameRules_scoring_add(frag_attacker, KEEPAWAY_CARRIERKILLS, 1);
             if(autocvar_g_keepaway_score_bckill) // add bckills to the score
                 GameRules_scoring_add(frag_attacker, SCORE, autocvar_g_keepaway_score_bckill);
         }
         else if(!frag_attacker.ballcarried)
             if(autocvar_g_keepaway_noncarrier_warn)
                 Send_Notification(NOTIF_ONE_ONLY, frag_attacker, MSG_CENTER, CENTER_KEEPAWAY_WARN);
         if(frag_attacker.ballcarried) // add to amount of kills while ballcarrier
             GameRules_scoring_add(frag_attacker, SCORE, autocvar_g_keepaway_score_killac);
     }
     if(frag_target.ballcarried) { ka_DropEvent(frag_target); } // a player with the ball has died, drop it
 }
MUTATOR_HOOKFUNCTION() [2/13]
MUTATOR_HOOKFUNCTION (ka , GiveFragsForKill)
Definition at line 388 of file sv_keepaway.qc.
References M_ARGV.
 {
     M_ARGV(2, float) = 0; // no frags counted in keepaway
     return true; // you deceptive little bugger ;3 This needs to be true in order for this function to even count.
 }
MUTATOR_HOOKFUNCTION() [3/13]
MUTATOR_HOOKFUNCTION (ka , Scores_CountFragsRemaining)
Definition at line 394 of file sv_keepaway.qc.
References autocvar_g_keepaway_score_timepoints.
 {
     // announce remaining frags, but only when timed scoring is off
     return !autocvar_g_keepaway_score_timepoints;
 }
MUTATOR_HOOKFUNCTION() [4/13]
MUTATOR_HOOKFUNCTION (ka , PlayerPreThink)
Definition at line 400 of file sv_keepaway.qc.
References BITSET, entity(), M_ARGV, and NULL.
 {
     entity player = M_ARGV(0, entity);
     // if the player has the ball, make sure they have the item for it (Used for HUD primarily)
     STAT(OBJECTIVE_STATUS, player) = BITSET(STAT(OBJECTIVE_STATUS, player), KA_CARRYING, player.ballcarried != NULL);
 }
MUTATOR_HOOKFUNCTION() [5/13]
MUTATOR_HOOKFUNCTION (ka , PlayerUseKey)
Definition at line 408 of file sv_keepaway.qc.
References entity(), ka_DropEvent(), M_ARGV, and MUTATOR_RETURNVALUE.
 {
     entity player = M_ARGV(0, entity);
     if(MUTATOR_RETURNVALUE == 0)
     if(player.ballcarried)
     {
         ka_DropEvent(player);
         return true;
     }
 }
MUTATOR_HOOKFUNCTION() [6/13]
MUTATOR_HOOKFUNCTION (ka , Damage_Calculate)
Definition at line 420 of file sv_keepaway.qc.
References autocvar_g_keepaway_ballcarrier_damage, autocvar_g_keepaway_ballcarrier_force, autocvar_g_keepaway_ballcarrier_selfdamage, autocvar_g_keepaway_ballcarrier_selfforce, autocvar_g_keepaway_noncarrier_damage, autocvar_g_keepaway_noncarrier_force, autocvar_g_keepaway_noncarrier_selfdamage, autocvar_g_keepaway_noncarrier_selfforce, entity(), IS_PLAYER, M_ARGV, and vector().
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     // as a gamemode rule, only apply scaling to player versus player combat
     if(!IS_PLAYER(frag_attacker) || !IS_PLAYER(frag_target))
         return;
     if(frag_attacker.ballcarried) // if the attacker is a ballcarrier
     {
         if(frag_target == frag_attacker) // damage done to yourself
         {
             M_ARGV(4, float) *= autocvar_g_keepaway_ballcarrier_selfdamage;
             M_ARGV(6, vector) *= autocvar_g_keepaway_ballcarrier_selfforce;
         }
         else // damage done to noncarriers
         {
             M_ARGV(4, float) *= autocvar_g_keepaway_ballcarrier_damage;
             M_ARGV(6, vector) *= autocvar_g_keepaway_ballcarrier_force;
         }
     }
     else // if the target is a noncarrier
     {
         if(frag_target == frag_attacker) // damage done to yourself
         {
             M_ARGV(4, float) *= autocvar_g_keepaway_noncarrier_selfdamage;
             M_ARGV(6, vector) *= autocvar_g_keepaway_noncarrier_selfforce;
         }
         else // damage done to other noncarriers
         {
             M_ARGV(4, float) *= autocvar_g_keepaway_noncarrier_damage;
             M_ARGV(6, vector) *= autocvar_g_keepaway_noncarrier_force;
         }
     }
 }
MUTATOR_HOOKFUNCTION() [7/13]
MUTATOR_HOOKFUNCTION (ka , ClientDisconnect)
Definition at line 457 of file sv_keepaway.qc.
References entity(), ka_DropEvent(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.ballcarried) { ka_DropEvent(player); } // a player with the ball has left the match, drop it
 }
MUTATOR_HOOKFUNCTION() [8/13]
MUTATOR_HOOKFUNCTION (ka , MakePlayerObserver)
Definition at line 464 of file sv_keepaway.qc.
References entity(), ka_DropEvent(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.ballcarried) { ka_DropEvent(player); } // a player with the ball has left the match, drop it
 }
MUTATOR_HOOKFUNCTION() [9/13]
MUTATOR_HOOKFUNCTION (ka , PlayerPowerups)
Definition at line 471 of file sv_keepaway.qc.
References autocvar_g_keepaway_ballcarrier_effects, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // In the future this hook is supposed to allow me to do some extra stuff with waypointsprites and invisibility powerup
     // So bare with me until I can fix a certain bug with ka_ballcarrier_waypointsprite_visible_for_player()
     player.effects &= ~autocvar_g_keepaway_ballcarrier_effects;
     if(player.ballcarried)
         player.effects |= autocvar_g_keepaway_ballcarrier_effects;
 }
MUTATOR_HOOKFUNCTION() [10/13]
MUTATOR_HOOKFUNCTION (ka , PlayerPhysics_UpdateStats)
Definition at line 485 of file sv_keepaway.qc.
References autocvar_g_keepaway_ballcarrier_highspeed, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // these automatically reset, no need to worry
     if(player.ballcarried)
         STAT(MOVEVARS_HIGHSPEED, player) *= autocvar_g_keepaway_ballcarrier_highspeed;
 }
MUTATOR_HOOKFUNCTION() [11/13]
MUTATOR_HOOKFUNCTION (ka , BotShouldAttack)
Definition at line 494 of file sv_keepaway.qc.
References entity(), g_kaballs, IL_EACH, and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     entity targ = M_ARGV(1, entity);
     // if neither player has ball then don't attack unless the ball is on the ground
     bool have_held_ball = false;
     IL_EACH(g_kaballs, it.owner,
     {
         have_held_ball = true;
         break;
     });
     if(!targ.ballcarried && !bot.ballcarried && have_held_ball)
         return true;
 }
MUTATOR_HOOKFUNCTION() [12/13]
MUTATOR_HOOKFUNCTION (ka , HavocBot_ChooseRole)
Definition at line 510 of file sv_keepaway.qc.
References entity(), havocbot_role_ka_carrier(), havocbot_role_ka_collector(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     if (bot.ballcarried)
         bot.havocbot_role = havocbot_role_ka_carrier;
     else
         bot.havocbot_role = havocbot_role_ka_collector;
     return true;
 }
MUTATOR_HOOKFUNCTION() [13/13]
MUTATOR_HOOKFUNCTION (ka , DropSpecialItems)
Definition at line 521 of file sv_keepaway.qc.
References entity(), ka_DropEvent(), and M_ARGV.
 {
     entity frag_target = M_ARGV(0, entity);
     if(frag_target.ballcarried)
         ka_DropEvent(frag_target);
 }
Variable Documentation
autocvar_g_keepaway_ballcarrier_damage
float autocvar_g_keepaway_ballcarrier_damage
Definition at line 13 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_ballcarrier_effects
int autocvar_g_keepaway_ballcarrier_effects
Definition at line 12 of file sv_keepaway.qc.
Referenced by ka_PlayerReset(), ka_TouchEvent(), and MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_ballcarrier_force
float autocvar_g_keepaway_ballcarrier_force
Definition at line 14 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_ballcarrier_highspeed
float autocvar_g_keepaway_ballcarrier_highspeed
Definition at line 15 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_ballcarrier_selfdamage
float autocvar_g_keepaway_ballcarrier_selfdamage
Definition at line 16 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_ballcarrier_selfforce
float autocvar_g_keepaway_ballcarrier_selfforce
Definition at line 17 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_noncarrier_damage
float autocvar_g_keepaway_noncarrier_damage
Definition at line 18 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_noncarrier_force
float autocvar_g_keepaway_noncarrier_force
Definition at line 19 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_noncarrier_selfdamage
float autocvar_g_keepaway_noncarrier_selfdamage
Definition at line 20 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_noncarrier_selfforce
float autocvar_g_keepaway_noncarrier_selfforce
Definition at line 21 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_noncarrier_warn
bool autocvar_g_keepaway_noncarrier_warn
Definition at line 22 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_score_bckill
int autocvar_g_keepaway_score_bckill
Definition at line 23 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_score_killac
int autocvar_g_keepaway_score_killac
Definition at line 24 of file sv_keepaway.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_keepaway_score_timeinterval
float autocvar_g_keepaway_score_timeinterval
Definition at line 26 of file sv_keepaway.qc.
Referenced by ka_TimeScoring(), and ka_TouchEvent().
autocvar_g_keepaway_score_timepoints
int autocvar_g_keepaway_score_timepoints
Definition at line 25 of file sv_keepaway.qc.
Referenced by ka_TimeScoring(), and MUTATOR_HOOKFUNCTION().
autocvar_g_keepawayball_damageforcescale
float autocvar_g_keepawayball_damageforcescale
Definition at line 27 of file sv_keepaway.qc.
Referenced by ka_SpawnBall().
autocvar_g_keepawayball_effects
int autocvar_g_keepawayball_effects
Definition at line 28 of file sv_keepaway.qc.
Referenced by ka_RespawnBall().
autocvar_g_keepawayball_respawntime
float autocvar_g_keepawayball_respawntime
Definition at line 29 of file sv_keepaway.qc.
Referenced by ka_DropEvent(), and ka_RespawnBall().
autocvar_g_keepawayball_trail_color
int autocvar_g_keepawayball_trail_color
Definition at line 30 of file sv_keepaway.qc.
Referenced by ka_SpawnBall(), and ka_TouchEvent().
ballcarried
entity ballcarried
Definition at line 10 of file sv_keepaway.qc.
Referenced by havocbot_role_ka_carrier(), and havocbot_role_ka_collector().
pushable
bool pushable
Definition at line 210 of file sv_keepaway.qc.