Xonotic: menu/item/checkbox.qc File Reference
checkbox.qc File Reference
#include "checkbox.qh"
Functions
void CheckBox_setChecked (entity me, float val)
void CheckBox_Click (entity me, entity other)
string CheckBox_toString (entity me)
void CheckBox_configureCheckBox (entity me, string txt, float sz, string gfx)
void CheckBox_draw (entity me)
void CheckBox_playClickSound (entity me)
Function Documentation
void CheckBox_Click (entity me, entity other)
Definition at line 7 of file checkbox.qc.
Referenced by CheckBox_Click_Redisplay().
     {
         me.setChecked(me, !me.checked);
     }
void CheckBox_configureCheckBox (entity me, string txt, float sz, string gfx)
Definition at line 15 of file checkbox.qc.
     {
         me.configureButton(me, txt, sz, gfx);
         me.align = 0;
     }
void CheckBox_draw (entity me)
Definition at line 20 of file checkbox.qc.
References s, string_null, and SUPER().
     {
         float s;
         s = me.pressed;
         if (me.useDownAsChecked)
         {
             me.srcSuffix = string_null;
             me.forcePressed = me.checked;
         }
         else
         {
             me.srcSuffix = (me.checked ? "1" : "0");
         }
         me.pressed = s;
         SUPER(CheckBox).draw(me);
     }
void CheckBox_playClickSound (entity me)
Definition at line 36 of file checkbox.qc.
References m_play_click_sound(), and MENU_SOUND_SELECT.
     {
         m_play_click_sound(MENU_SOUND_SELECT);
     }
void CheckBox_setChecked (entity me, float val)
Definition at line 3 of file checkbox.qc.
     {
         me.checked = val;
     }
string CheckBox_toString (entity me)
Definition at line 11 of file checkbox.qc.
References strcat(), and SUPER().
     {
         return strcat(SUPER(CheckBox).toString(me), ", ", me.checked ? "checked" : "unchecked");
     }