Xonotic: server/mutators/mutator/gamemode_tdm.qh File Reference
gamemode_tdm.qh File Reference
#include "../gamemode.qh"
Functions
REGISTER_MUTATOR (tdm, false)
void tdm_DelayedInit (entity this)
Variables
int autocvar_g_tdm_point_leadlimit
int autocvar_g_tdm_point_limit
bool autocvar_g_tdm_team_spawns
Function Documentation
REGISTER_MUTATOR (tdm , false)
Definition at line 10 of file gamemode_tdm.qh.
References ActivateTeamplay(), autocvar_g_tdm_point_leadlimit, autocvar_g_tdm_point_limit, autocvar_g_tdm_team_spawns, autocvar_timelimit_override, error, have_team_spawns, InitializeEntity(), INITPRIO_GAMETYPE, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, NULL, SetLimits(), tdm_DelayedInit(), and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         InitializeEntity(NULL, tdm_DelayedInit, INITPRIO_GAMETYPE);
         ActivateTeamplay();
         SetLimits(autocvar_g_tdm_point_limit, autocvar_g_tdm_point_leadlimit, autocvar_timelimit_override, -1);
         if (autocvar_g_tdm_team_spawns)
             have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back tdm_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
void tdm_DelayedInit (entity this)
Definition at line 31 of file gamemode_tdm.qc.
References autocvar_g_tdm_teams, autocvar_g_tdm_teams_override, BIT, bound(), classname, find(), LOG_TRACE(), NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, tdm_SpawnTeam(), and teams.
Referenced by REGISTER_MUTATOR().
 {
     // if no teams are found, spawn defaults
     if(find(NULL, classname, "tdm_team") == NULL)
     {
         LOG_TRACE("No \"tdm_team\" entities found on this map, creating them anyway.");
         int numteams = autocvar_g_tdm_teams_override;
         if(numteams < 2) { numteams = autocvar_g_tdm_teams; }
         numteams = bound(2, numteams, 4);
         int teams = 0;
         if(numteams >= 1) teams |= BIT(0);
         if(numteams >= 2) teams |= BIT(1);
         if(numteams >= 3) teams |= BIT(2);
         if(numteams >= 4) teams |= BIT(3);
         if(teams & BIT(0))
             tdm_SpawnTeam("Red", NUM_TEAM_1);
         if(teams & BIT(1))
             tdm_SpawnTeam("Blue", NUM_TEAM_2);
         if(teams & BIT(2))
             tdm_SpawnTeam("Yellow", NUM_TEAM_3);
         if(teams & BIT(3))
             tdm_SpawnTeam("Pink", NUM_TEAM_4);
     }
 }
Variable Documentation
int autocvar_g_tdm_point_leadlimit
Definition at line 6 of file gamemode_tdm.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_tdm_point_limit
Definition at line 5 of file gamemode_tdm.qh.
Referenced by REGISTER_MUTATOR().
bool autocvar_g_tdm_team_spawns
Definition at line 7 of file gamemode_tdm.qh.
Referenced by REGISTER_MUTATOR().