Xonotic: server/weapons/spawning.qh File Reference
spawning.qh File Reference
#include <common/weapons/_all.qh>
#include <common/stats.qh>
Functions
string W_Apply_Weaponreplace (string in)
void weapon_defaultspawnfunc (entity this, Weapon e)
Function Documentation
W_Apply_Weaponreplace()
string W_Apply_Weaponreplace (string in)
Definition at line 13 of file spawning.qc.
References cons(), FOREACH_WORD, and Weapon_from_name().
Referenced by MUTATOR_HOOKFUNCTION(), and weapon_defaultspawnfunc().
 {
     string out = "";
     FOREACH_WORD(in, true, {
         string replacement = "";
         Weapon w = Weapon_from_name(it);
         if (w)
         {
             replacement = w.weaponreplace;
             if (replacement == "") replacement = it;
         }
         if (replacement == "0") continue;
         out = cons(out, replacement);
     });
     return out;
 }
weapon_defaultspawnfunc()
void weapon_defaultspawnfunc (entity this, Weapon e)
Definition at line 30 of file spawning.qc.
References _StartItem(), ammo, Weapon::ammo_type, argv(), autocvar_g_balance_superweapons_time, classname, copyentity(), count, cvar(), entity(), g_pickup_weapons_anyway, GetAmmoConsumptionQ3(), GetResource(), glowmod, internalteam, Item_IsDefinitionAllowed(), Item_IsLoot(), itemdef, M_ARGV, m_isreplaced, modelindex, MUTATOR_CALLHOOK, Weapon::netname, owner, pickup_anyway, q3compat, respawntime, respawntimejitter, SetResource(), spawn(), Weapon::spawnflags, startitem_failed, strcat(), superweapons_finished, team, tokenize_console, W_Apply_Weaponreplace(), weapon_defaultspawnfunc(), Weapon_from_name(), WEP_FLAG_MUTATORBLOCKED, WEP_FLAG_SUPERWEAPON, WepSet_FromWeapon, and Weapon::wpcolor.
Referenced by W_ThrowNewWeapon(), Weapon::Weapon ::display(), and weapon_defaultspawnfunc().
 {
     wpn = wpn.m_spawnfunc_hookreplace(wpn, this);
     this.classname = wpn.m_canonical_spawnfunc;
     if (!Item_IsLoot(this) && !this.m_isreplaced)
     {
         if (wpn.spawnflags & WEP_FLAG_MUTATORBLOCKED)
         {
             //LOG_WARNF("Attempted to spawn a mutator-blocked weapon rejected: prvm_edict server %i", this);
             startitem_failed = true;
             return;
         }
         string s = W_Apply_Weaponreplace(wpn.netname);
         MUTATOR_CALLHOOK(SetWeaponreplace, this, wpn, s);
         s = M_ARGV(2, string);
         if (s == "")
         {
             delete(this);
             startitem_failed = true;
             return;
         }
         int t = tokenize_console(s);
         if (t >= 2)
         {
             this.team = --internalteam;
             for (int i = 1; i < t; ++i)
             {
                 s = argv(i);
                 Weapon wep = Weapon_from_name(s);
                 if(wep != WEP_Null)
                 {
                     entity replacement = spawn();
                     copyentity(this, replacement);
                     replacement.m_isreplaced = true;
                     weapon_defaultspawnfunc(replacement, wep);
                 }
             }
         }
         if (t >= 1) // always the case!
         {
             s = argv(0);
             wpn = Weapon_from_name(s);
         }
         if (wpn == WEP_Null)
         {
             delete(this);
             startitem_failed = true;
             return;
         }
     }
     if(!Item_IsLoot(this))
         weaponsInMapAll |= WepSet_FromWeapon(wpn);
     if (!Item_IsDefinitionAllowed(wpn.m_pickup))
     {
         delete(this);
         startitem_failed = true;
         return;
     }
     if (!this.respawntime)
     {
         if (wpn.spawnflags & WEP_FLAG_SUPERWEAPON)
         {
             this.respawntime = g_pickup_respawntime_superweapon;
             this.respawntimejitter = g_pickup_respawntimejitter_superweapon;
         }
         else
         {
             this.respawntime = g_pickup_respawntime_weapon;
             this.respawntimejitter = g_pickup_respawntimejitter_weapon;
         }
     }
     if (wpn.spawnflags & WEP_FLAG_SUPERWEAPON)
         if (!this.superweapons_finished)
             this.superweapons_finished = autocvar_g_balance_superweapons_time;
     // if we don't already have ammo, give us some ammo
     // TODO: registry handles
     if ((wpn.ammo_type != RES_NONE) && !GetResource(this, wpn.ammo_type))
     {
         int ammo = 0;
         if (q3compat && this.count > 0)
             ammo = this.count * GetAmmoConsumptionQ3(wpn.netname);
             // WEAPONTODO: magazines of MG, rifle and OK weapons are unaccounted for
         else
         {
             switch (wpn.ammo_type)
             {
                 case RES_SHELLS:  ammo = cvar("g_pickup_shells_weapon");  break;
                 case RES_BULLETS: ammo = cvar("g_pickup_nails_weapon");   break;
                 case RES_ROCKETS: ammo = cvar("g_pickup_rockets_weapon"); break;
                 case RES_CELLS:   ammo = cvar("g_pickup_cells_weapon");   break;
                 case RES_PLASMA:  ammo = cvar("g_pickup_plasma_weapon");  break;
                 case RES_FUEL:    ammo = cvar("g_pickup_fuel_weapon");    break;
             }
         }
         SetResource(this, wpn.ammo_type, ammo);
     }
     #if 0 // WEAPONTODO
     if (wpn.items)
     {
         for (int i = 0, j = 1; i < 24; ++i, j <<= 1)
         {
             if (wpn.items & j)
             {
                 ammotype = Item_CounterField(j);
                 if (!this.ammotype)
                     this.ammotype = cvar(strcat("g_pickup_", Item_CounterFieldName(j), "_weapon"));
             }
         }
     }
     #endif
     // pickup anyway
     if (g_pickup_weapons_anyway)
         this.pickup_anyway = true;
     if(!this.owner)
         this.glowmod = wpn.wpcolor;
     GameItem def = wpn.m_pickup;
     _StartItem(
         this,
         this.itemdef = def,
         this.respawntime, // defaultrespawntime
         this.respawntimejitter // defaultrespawntimejitter
     );
     #if 0 // WEAPONTODO
     if (this.modelindex) { // don't precache if this was removed
         wpn.wr_init(wpn);
     }
     #endif
 }