Xonotic: server/steerlib.qc File Reference
steerlib.qc File Reference
Macros
#define steerlib_push(point) normalize(self.origin - point)
Uniform push from a point.
Functions
vector steerlib_pull (vector point)
Uniform pull towards a point.
vector steerlib_arrive (vector point, float maximal_distance)
Pull toward a point, The further away, the stronger the pull.
vector steerlib_attract (vector point, float maximal_distance)
Pull toward a point increasing the pull the closer we get.
vector steerlib_attract2 (entity this, vector point, float min_influense, float max_distance, float max_influense)
vector steerlib_repell (vector point, float maximal_distance)
Move away from a point.
vector steerlib_standoff (vector point, float ideal_distance)
Try to keep at ideal_distance away from point.
vector steerlib_wander (float range, float tresh, vector oldpoint)
A random heading in a forward halfcicrle.
vector steerlib_dodge (vector point, vector dodge_dir, float min_distance)
Dodge a point.
vector steerlib_flock (float _radius, float standoff, float separation_force, float flock_force)
vector steerlib_flock2d (float _radius, float standoff, float separation_force, float flock_force)
flocking by .flock_id Group will move towards the unified direction while keeping close to eachother.
vector steerlib_swarm (float _radius, float standoff, float separation_force, float swarm_force)
All members want to be in the center, and keep away from eachother.
vector steerlib_traceavoid (float pitch, float length)
Steer towards the direction least obstructed.
vector steerlib_traceavoid_flat (float pitch, float length, vector vofs)
Steer towards the direction least obstructed.
float beamsweep_badpoint (vector point, float waterok)
float beamsweep (vector from, vector dir, float length, float step, float step_up, float step_down)
vector steerlib_beamsteer (vector dir, float length, float step, float step_up, float step_down)
Variables
float flock_id
flocking by .flock_id Group will move towards the unified direction while keeping close to eachother.
Macro Definition Documentation
#define steerlib_push (point) normalize(self.origin - point)
Uniform push from a point.
Definition at line 17 of file steerlib.qc.
Function Documentation
float beamsweep (vector from, vector dir, float length, float step, float step_up, float step_down)
Definition at line 381 of file steerlib.qc.
References beamsweep_badpoint(), MOVE_NORMAL, SELFPARAM, trace_endpos, trace_fraction, vector(), and world.
Referenced by steerlib_beamsteer().
 {SELFPARAM();
     float i;
     vector a,b,u,d;
     u = '0 0 1' * step_up;
     d = '0 0 1' * step_down;
     traceline(from + u, from - d,MOVE_NORMAL,self);
     if(trace_fraction == 1.0)
         return 0;
     if(beamsweep_badpoint(trace_endpos,0))
         return 0;
     a = trace_endpos;
     for(i = 0; i < length; i += step)
     {
         b = a + dir * step;
         tracebox(a + u,'-4 -4 -4','4 4 4', b + u,MOVE_NORMAL,self);
         if(trace_fraction != 1.0)
             return i / length;
         traceline(b + u, b - d,MOVE_NORMAL,self);
         if(trace_fraction == 1.0)
             return i / length;
         if(beamsweep_badpoint(trace_endpos,0))
             return i / length;
 #ifdef BEAMSTEER_VISUAL
         te_lightning1(world,a+u,b+u);
         te_lightning1(world,b+u,b-d);
 #endif
         a = trace_endpos;
     }
     return 1;
 }
float beamsweep_badpoint (vector point, float waterok)
Definition at line 341 of file steerlib.qc.
References CONTENT_EMPTY, CONTENT_LAVA, CONTENT_SKY, CONTENT_SLIME, CONTENT_SOLID, CONTENT_WATER, Q3SURFACEFLAG_SKY, and trace_dphitq3surfaceflags.
Referenced by beamsweep().
 {
     float pc,pc2;
     if(trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY)
         return 1;
     pc  = pointcontents(point);
     pc2 = pointcontents(point - '0 0 1');
     switch(pc)
     {
         case CONTENT_SOLID: break;
         case CONTENT_SLIME: break;
         case CONTENT_LAVA:  break;
         case CONTENT_SKY:
             return 1;
         case CONTENT_EMPTY:
             if (pc2 == CONTENT_SOLID)
                 return 0;
             if (pc2 == CONTENT_WATER)
                 if(waterok)
                     return 0;
             break;
         case CONTENT_WATER:
             if(waterok)
                 return 0;
             break;
     }
     return 1;
 }
vector steerlib_arrive (vector point, float maximal_distance)
Pull toward a point, The further away, the stronger the pull.
Definition at line 27 of file steerlib.qc.
References bound(), normalize(), origin, SELFPARAM, vector(), and vlen().
Referenced by steerlib_flock(), steerlib_flock2d(), and steerlib_swarm().
 {SELFPARAM();
     float distance;
     vector direction;
     distance = bound(0.001,vlen(self.origin - point),maximal_distance);
     direction = normalize(point - self.origin);
     return  direction * (distance / maximal_distance);
 }
vector steerlib_attract (vector point, float maximal_distance)
Pull toward a point increasing the pull the closer we get.
Definition at line 40 of file steerlib.qc.
References bound(), normalize(), origin, SELFPARAM, vector(), and vlen().
 {SELFPARAM();
     float distance;
     vector direction;
     distance = bound(0.001,vlen(self.origin - point),maximal_distance);
     direction = normalize(point - self.origin);
     return  direction * (1-(distance / maximal_distance));
 }
vector steerlib_attract2 (entity this, vector point, float min_influense, float max_distance, float max_influense)
Definition at line 51 of file steerlib.qc.
References bound(), normalize(), origin, vector(), and vlen().
Referenced by Monster_Move().
 {
     float distance;
     vector direction;
     float influense;
     distance  = bound(0.00001,vlen(this.origin - point),max_distance);
     direction = normalize(point - this.origin);
     influense = 1 - (distance / max_distance);
     influense = min_influense + (influense * (max_influense - min_influense));
     return  direction * influense;
 }
vector steerlib_beamsteer (vector dir, float length, float step, float step_up, float step_down)
Definition at line 421 of file steerlib.qc.
References beamsweep(), maxs, mins, MOVE_NOMONSTERS, normalize(), origin, p, SELFPARAM, trace_fraction, v_forward, v_right, vectoangles(), and vector().
 {SELFPARAM();
     float bm_forward, bm_right, bm_left,p;
     vector vr,vl;
     dir.z *= 0.15;
     vr = vectoangles(dir);
     //vr_x *= -1;
     tracebox(self.origin + '0 0 1' * step_up, self.mins, self.maxs, ('0 0 1' * step_up) + self.origin +  (dir * length), MOVE_NOMONSTERS, self);
     if(trace_fraction == 1.0)
     {
         //te_lightning1(self,self.origin,self.origin +  (dir * length));
         return dir;
     }
     makevectors(vr);
     bm_forward = beamsweep(self.origin, v_forward, length, step, step_up, step_down);
     vr = normalize(v_forward + v_right * 0.125);
     vl = normalize(v_forward - v_right * 0.125);
     bm_right = beamsweep(self.origin, vr, length, step, step_up, step_down);
     bm_left  = beamsweep(self.origin, vl, length, step, step_up, step_down);
     p = bm_left + bm_right;
     if(p == 2)
     {
         //te_lightning1(self,self.origin + '0 0 32',self.origin + '0 0 32' + vr * length);
         //te_lightning1(self.tur_head,self.origin + '0 0 32',self.origin + '0 0 32' + vl * length);
         return v_forward;
     }
     p = 2 - p;
     vr = normalize(v_forward + v_right * p);
     vl = normalize(v_forward - v_right * p);
     bm_right = beamsweep(self.origin, vr, length, step, step_up, step_down);
     bm_left  = beamsweep(self.origin, vl, length, step, step_up, step_down);
     if(bm_left + bm_right < 0.15)
     {
         vr = normalize((v_forward*-1) + v_right * 0.75);
         vl = normalize((v_forward*-1) - v_right * 0.75);
         bm_right = beamsweep(self.origin, vr, length, step, step_up, step_down);
         bm_left  = beamsweep(self.origin, vl, length, step, step_up, step_down);
     }
     //te_lightning1(self,self.origin + '0 0 32',self.origin + '0 0 32' + vr * length);
     //te_lightning1(self.tur_head,self.origin + '0 0 32',self.origin + '0 0 32' + vl * length);
     bm_forward *= bm_forward;
     bm_right   *= bm_right;
     bm_left    *= bm_left;
     vr = vr * bm_right;
     vl = vl * bm_left;
     return normalize(vr + vl);
 }
vector steerlib_dodge (vector point, vector dodge_dir, float min_distance)
Dodge a point.
dont work to well.
Definition at line 159 of file steerlib.qc.
References max(), origin, SELFPARAM, and vlen().
 {SELFPARAM();
     float distance;
     distance = max(vlen(self.origin - point),min_distance);
     if (min_distance < distance)
         return '0 0 0';
     return dodge_dir * (min_distance/distance);
 }
vector steerlib_flock (float _radius, float standoff, float separation_force, float flock_force)
Definition at line 175 of file steerlib.qc.
References entity(), origin, SELFPARAM, steerlib_arrive(), steerlib_repell(), and vector().
 {SELFPARAM();
     entity flock_member;
     vector push = '0 0 0', pull = '0 0 0';
     float ccount = 0;
     flock_member = findradius(self.origin, _radius);
     while(flock_member)
     {
         if(flock_member != self)
         if(flock_member.flock_id == self.flock_id)
         {
             ++ccount;
             push = push + (steerlib_repell(flock_member.origin,standoff) * separation_force);
             pull = pull + (steerlib_arrive(flock_member.origin + flock_member.velocity, _radius) * flock_force);
         }
         flock_member = flock_member.chain;
     }
     return push + (pull* (1 / ccount));
 }
vector steerlib_flock2d (float _radius, float standoff, float separation_force, float flock_force)
flocking by .flock_id Group will move towards the unified direction while keeping close to eachother.
xy only version (for ground movers).
Definition at line 201 of file steerlib.qc.
References entity(), origin, SELFPARAM, steerlib_arrive(), steerlib_repell(), and vector().
 {SELFPARAM();
     entity flock_member;
     vector push = '0 0 0', pull = '0 0 0';
     float ccount = 0;
     flock_member = findradius(self.origin,_radius);
     while(flock_member)
     {
         if(flock_member != self)
         if(flock_member.flock_id == self.flock_id)
         {
             ++ccount;
             push = push + (steerlib_repell(flock_member.origin, standoff) * separation_force);
             pull = pull + (steerlib_arrive(flock_member.origin + flock_member.velocity, _radius) * flock_force);
         }
         flock_member = flock_member.chain;
     }
     push.z = 0;
     pull.z = 0;
     return push + (pull * (1 / ccount));
 }
vector steerlib_pull (vector point)
Uniform pull towards a point.
Definition at line 9 of file steerlib.qc.
References normalize(), origin, and SELFPARAM.
 {SELFPARAM();
     return normalize(point - self.origin);
 }
vector steerlib_repell (vector point, float maximal_distance)
Move away from a point.
Definition at line 99 of file steerlib.qc.
References bound(), normalize(), origin, SELFPARAM, vector(), and vlen().
Referenced by steerlib_flock(), steerlib_flock2d(), and steerlib_swarm().
 {SELFPARAM();
     float distance;
     vector direction;
     distance = bound(0.001,vlen(self.origin - point),maximal_distance);
     direction = normalize(self.origin - point);
     return  direction * (1-(distance / maximal_distance));
 }
vector steerlib_standoff (vector point, float ideal_distance)
Try to keep at ideal_distance away from point.
Definition at line 113 of file steerlib.qc.
References normalize(), origin, SELFPARAM, vector(), and vlen().
 {SELFPARAM();
     float distance;
     vector direction;
     distance = vlen(self.origin - point);
     if(distance < ideal_distance)
     {
         direction = normalize(self.origin - point);
         return direction * (distance / ideal_distance);
     }
     direction = normalize(point - self.origin);
     return direction * (ideal_distance / distance);
 }
vector steerlib_swarm (float _radius, float standoff, float separation_force, float swarm_force)
All members want to be in the center, and keep away from eachother.
The furtehr form the center the more they want to be there.
This results in a aligned movement (?!) much like flocking.
Definition at line 232 of file steerlib.qc.
References entity(), origin, SELFPARAM, steerlib_arrive(), steerlib_repell(), and vector().
 {SELFPARAM();
     entity swarm_member;
     vector force = '0 0 0', center = '0 0 0';
     float ccount = 0;
     swarm_member = findradius(self.origin,_radius);
     while(swarm_member)
     {
         if(swarm_member.flock_id == self.flock_id)
         {
             ++ccount;
             center = center + swarm_member.origin;
             force = force + (steerlib_repell(swarm_member.origin,standoff) * separation_force);
         }
         swarm_member = swarm_member.chain;
     }
     center = center * (1 / ccount);
     force = force + (steerlib_arrive(center,_radius) * swarm_force);
     return force;
 }
vector steerlib_traceavoid (float pitch, float length)
Steer towards the direction least obstructed.
Run four tracelines in a forward funnel, bias each diretion negative if something is found there. You need to call makevectors() (or equivalent) before this function to set v_forward and v_right
Definition at line 262 of file steerlib.qc.
References MOVE_NOMONSTERS, origin, pitch, SELFPARAM, trace_fraction, v_forward, v_right, v_up, and vector().
 {SELFPARAM();
     vector vup_left,vup_right,vdown_left,vdown_right;
     float fup_left,fup_right,fdown_left,fdown_right;
     vector upwish,downwish,leftwish,rightwish;
     vector v_left,v_down;
     v_left = v_right * -1;
     v_down = v_up * -1;
     vup_left = (v_forward + (v_left * pitch + v_up * pitch)) * length;
     traceline(self.origin, self.origin +  vup_left,MOVE_NOMONSTERS,self);
     fup_left = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     vup_right = (v_forward + (v_right * pitch + v_up * pitch)) * length;
     traceline(self.origin,self.origin + vup_right ,MOVE_NOMONSTERS,self);
     fup_right = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     vdown_left = (v_forward + (v_left * pitch + v_down * pitch)) * length;
     traceline(self.origin,self.origin + vdown_left,MOVE_NOMONSTERS,self);
     fdown_left = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     vdown_right = (v_forward + (v_right * pitch + v_down * pitch)) * length;
     traceline(self.origin,self.origin + vdown_right,MOVE_NOMONSTERS,self);
     fdown_right = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     upwish    = v_up    * (fup_left   + fup_right);
     downwish  = v_down  * (fdown_left + fdown_right);
     leftwish  = v_left  * (fup_left   + fdown_left);
     rightwish = v_right * (fup_right  + fdown_right);
     return (upwish+leftwish+downwish+rightwish) * 0.25;
 }
vector steerlib_traceavoid_flat (float pitch, float length, vector vofs)
Steer towards the direction least obstructed.
Run tracelines in a forward trident, bias each direction negative if something is found there.
Definition at line 309 of file steerlib.qc.
References MOVE_NOMONSTERS, normalize(), origin, pitch, SELFPARAM, trace_fraction, v_forward, v_right, and vector().
 {SELFPARAM();
     vector vt_left, vt_right,vt_front;
     float f_left, f_right,f_front;
     vector leftwish, rightwish,frontwish, v_left;
     v_left = v_right * -1;
     vt_front = v_forward * length;
     traceline(self.origin + vofs, self.origin + vofs + vt_front,MOVE_NOMONSTERS,self);
     f_front = trace_fraction;
     vt_left = (v_forward + (v_left * pitch)) * length;
     traceline(self.origin + vofs, self.origin + vofs + vt_left,MOVE_NOMONSTERS,self);
     f_left = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     vt_right = (v_forward + (v_right * pitch)) * length;
     traceline(self.origin + vofs, self.origin + vofs + vt_right ,MOVE_NOMONSTERS,self);
     f_right = trace_fraction;
     //te_lightning1(world,self.origin, trace_endpos);
     leftwish  = v_left    * f_left;
     rightwish = v_right   * f_right;
     frontwish = v_forward * f_front;
     return normalize(leftwish + rightwish + frontwish);
 }
vector steerlib_wander (float range, float tresh, vector oldpoint)
A random heading in a forward halfcicrle.
use like: self.target = steerlib_wander(256,32,self.target)
where range is the cicrle radius and tresh is how close we need to be to pick a new heading.
Definition at line 140 of file steerlib.qc.
References bound(), normalize(), origin, randomvec(), SELFPARAM, v_forward, vector(), and vlen().
 {SELFPARAM();
     vector wander_point;
     wander_point = v_forward - oldpoint;
     if (vlen(wander_point) > tresh)
         return oldpoint;
     range = bound(0,range,1);
     wander_point = self.origin + v_forward * 128;
     wander_point = wander_point + randomvec() * (range * 128) - randomvec() * (range * 128);
     return normalize(wander_point - self.origin);
 }
Variable Documentation
float flock_id
flocking by .flock_id Group will move towards the unified direction while keeping close to eachother.
Definition at line 174 of file steerlib.qc.