Xonotic: lib/csqcmodel/cl_model.qh File Reference
cl_model.qh File Reference
#include "common.qh"
Macros
#define CSQCMODEL_ENDIF
#define CSQCMODEL_IF(cond)
#define CSQCMODEL_PROPERTY(flag, t, r, w, f) .t f;
#define CSQCMODEL_PROPERTY_SCALED(flag, t, r, w, f, s, mi, ma) .t f;
Functions
void CSQCModel_InterpolateAnimation_1To2_Do (entity this)
void CSQCModel_InterpolateAnimation_1To2_Note (entity this, int sf, float set_times)
void CSQCModel_InterpolateAnimation_1To2_PreNote (entity this, int sf)
void CSQCModel_InterpolateAnimation_2To4_Do (entity this)
void CSQCModel_InterpolateAnimation_2To4_Note (entity this, int sf, float set_times)
void CSQCModel_InterpolateAnimation_2To4_PreNote (entity this, int sf)
ALLPROPERTIES entity CSQCModel_server2csqc (int i)
Variables
float csqcmodel_teleported
Macro Definition Documentation
CSQCMODEL_ENDIF
#define CSQCMODEL_ENDIF
Definition at line 27 of file cl_model.qh.
CSQCMODEL_IF
#define CSQCMODEL_IF (cond)
Definition at line 26 of file cl_model.qh.
CSQCMODEL_PROPERTY
#define CSQCMODEL_PROPERTY (flag, t, r, w, f) .t f;
Definition at line 28 of file cl_model.qh.
CSQCMODEL_PROPERTY_SCALED
#define CSQCMODEL_PROPERTY_SCALED (flag, t, r, w, f, s, mi, ma) .t f;
Definition at line 30 of file cl_model.qh.
Function Documentation
CSQCModel_InterpolateAnimation_1To2_Do()
void CSQCModel_InterpolateAnimation_1To2_Do (entity this)
Definition at line 156 of file cl_model.qc.
References autocvar_cl_lerpanim_maxdelta_framegroups, autocvar_cl_nolerp, bound(), frame1time, frame2time, lerpfrac, and time.
Referenced by CSQCModel_InterpolateAnimation_Do().
 {
     if(autocvar_cl_nolerp || (autocvar_cl_lerpanim_maxdelta_framegroups == 0))
     {
         this.lerpfrac = 0;
     }
     else
     {
         if(this.frame2time == 0) // if frame2 was not previously displayed, only frame1 can make sense
             this.lerpfrac = 0;
         else
             this.lerpfrac = 1 - bound(0, (time - this.frame1time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
     }
 }
CSQCModel_InterpolateAnimation_1To2_Note()
void CSQCModel_InterpolateAnimation_1To2_Note (entity this, int sf, float set_times)
CSQCModel_InterpolateAnimation_1To2_PreNote()
void CSQCModel_InterpolateAnimation_1To2_PreNote (entity this, int sf)
Definition at line 56 of file cl_model.qc.
References CSQCMODEL_PROPERTY_FRAME, frame, frame1time, frame2, and frame2time.
Referenced by CSQCModel_InterpolateAnimation_PreNote().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         this.frame2 = this.frame;
         this.frame2time = this.frame1time;
     }
 }
CSQCModel_InterpolateAnimation_2To4_Do()
void CSQCModel_InterpolateAnimation_2To4_Do (entity this)
Definition at line 109 of file cl_model.qc.
References autocvar_cl_lerpanim_maxdelta_framegroups, autocvar_cl_nolerp, bound(), csqcmodel_lerpfrac, csqcmodel_lerpfrac2, csqcmodel_lerpfrac2time, csqcmodel_lerpfractime, frame1time, frame2time, frame3time, frame4time, lerpfrac, lerpfrac3, lerpfrac4, and time.
Referenced by CSQCModel_Hook_PreDraw(), and CSQCModel_InterpolateAnimation_Do().
 {
     if(autocvar_cl_nolerp || (autocvar_cl_lerpanim_maxdelta_framegroups == 0))
     {
         this.lerpfrac = this.csqcmodel_lerpfrac;
         this.lerpfrac3 = 0;
         this.lerpfrac4 = 0;
     }
     else
     {
         float l13, l24, llf;
         float l24_13;
         if(this.frame3time == 0) // if frame1/3 were not previously displayed, only frame1 can make sense
             l13 = 1;
         else
             l13 = bound(0, (time - this.frame1time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         if(this.frame4time == 0) // if frame2/4 were not previously displayed, only frame2 can make sense
             l24 = 1;
         else
             l24 = bound(0, (time - this.frame2time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         if(this.csqcmodel_lerpfrac2time == 0) // if there is no old lerpfrac (newly displayed model), only lerpfrac makes sense
             llf = 1;
         else
             llf = bound(0, (time - this.csqcmodel_lerpfractime) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         l24_13 = this.csqcmodel_lerpfrac * llf + this.csqcmodel_lerpfrac2 * (1 - llf);
         this.lerpfrac  = l24 * l24_13;
         this.lerpfrac4 = (1 - l24) * l24_13;
         this.lerpfrac3 = (1 - l13) * (1 - l24_13);
         if(l24_13 == 0) // if frames 2/4 are not displayed, clear their frametime
         {
             this.frame2time = 0;
             this.frame4time = 0;
         }
         if(l24_13 == 1) // if frames 1/3 are not displayed, clear their frametime
         {
             this.frame1time = 0;
             this.frame3time = 0;
         }
     }
 }
CSQCModel_InterpolateAnimation_2To4_Note()
void CSQCModel_InterpolateAnimation_2To4_Note (entity this, int sf, float set_times)
CSQCModel_InterpolateAnimation_2To4_PreNote()
void CSQCModel_InterpolateAnimation_2To4_PreNote (entity this, int sf)
Definition at line 37 of file cl_model.qc.
References csqcmodel_lerpfrac, csqcmodel_lerpfrac2, csqcmodel_lerpfrac2time, csqcmodel_lerpfractime, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_LERPFRAC, frame, frame1time, frame2, frame2time, frame3, frame3time, frame4, frame4time, and lerpfrac.
Referenced by CSQCModel_Hook_PreDraw(), and CSQCModel_InterpolateAnimation_PreNote().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         this.frame3 = this.frame;
         this.frame3time = this.frame1time;
     }
     if(sf & CSQCMODEL_PROPERTY_FRAME2)
     {
         this.frame4 = this.frame2;
         this.frame4time = this.frame2time;
     }
     if(sf & CSQCMODEL_PROPERTY_LERPFRAC)
     {
         this.csqcmodel_lerpfrac2 = this.csqcmodel_lerpfrac;
         this.csqcmodel_lerpfrac2time = this.csqcmodel_lerpfractime;
         this.lerpfrac = this.csqcmodel_lerpfrac;
     }
 }
CSQCModel_server2csqc()
ALLPROPERTIES entity CSQCModel_server2csqc (int i)
Parameters
i zero indexed player
Definition at line 314 of file cl_model.qc.
References CSQCModel_players, entnum, findfloat(), LOG_DEBUGF, maxclients, and NULL.
Referenced by CSQC_UpdateView(), CSQCPlayer_SetCamera(), Hud_Dynamic_Frame(), HUD_StrafeHUD(), viewloc_PlayerPhysics(), viewmodel_animate(), viewmodel_draw(), and W_Model().
 {
     if (i < maxclients) return CSQCModel_players[i];
     ++i;
     LOG_DEBUGF("player out of bounds: %d", i);
     return findfloat(NULL, entnum, i);
 }
Variable Documentation
csqcmodel_teleported
float csqcmodel_teleported
Definition at line 39 of file cl_model.qh.
Referenced by CSQCModel_ApplyStairSmoothing(), CSQCModel_Draw(), CSQCModel_Effects_PostUpdate(), CSQCPlayer_ApplySmoothing(), and NET_HANDLE().