Xonotic: XonoticCheckBox Class Reference
XonoticCheckBox Class Reference
Public Member Functions
void CheckBox_Click (entity me, entity other)
virtual void configureButton ()
virtual void configureCheckBox ()
virtual void configureLabel ()
virtual void configureXonoticCheckBox ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void loadCvars ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void playClickSound ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void saveCvars ()
virtual void setChecked ()
virtual void setText ()
virtual void showNotify ()
virtual void toString ()
void (entity, entity) onClick
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = SKINALPHA_TEXT
float alpha2 = 1
entity applyButton = NULL
float buttonLeftOfText = 0
float checked = 0
float clickTime = 0
vector color = SKINCOLOR_CHECKBOX_N
vector color2 = '1 1 1'
vector colorC = SKINCOLOR_CHECKBOX_C
vector colorD = SKINCOLOR_CHECKBOX_D
vector colorF = SKINCOLOR_CHECKBOX_F
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
string currentText = string_null
string cvarName = string_null
float disabled = 0
float disabledAlpha = SKINALPHA_DISABLED
bool disableOnClick = false
float focusable = 1
float focused = 0
float fontSize = SKINFONTSIZE_NORMAL
float forcePressed = 0
string image = SKINGFX_CHECKBOX
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
entity linkedCheckBox = NULL
float marginLeft = 0
float marginRight = 0
float noValue = 0
entity onClickEntity = NULL
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float pressed = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
float sendCvars = 0
vector size = '0 0 0'
string src = string_null
string src2 = string_null
float src2scale = 1
float srcMulti = 0
string srcSuffix = string_null
string text = string_null
entity textEntity = NULL
string tooltip = string_null
float useDownAsChecked = 0
float yesValue = 1
Detailed Description
Definition at line 4 of file checkbox.qh.
Member Function Documentation
void CheckBox::CheckBox_Click (entity me, entity other) inherited
virtual void Button::configureButton () virtual inherited
virtual void CheckBox::configureCheckBox () virtual inherited
virtual void Label::configureLabel () virtual inherited
virtual void XonoticCheckBox::configureXonoticCheckBox () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 276 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 290 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void CheckBox::draw () virtual inherited
Reimplemented from Button.
Reimplemented in XonoticSliderCheckBox, XonoticColorButton, and XonoticRadioButton.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void Item::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void Button::keyDown () virtual inherited
Reimplemented from Item.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void XonoticCheckBox::loadCvars () virtual
virtual void Button::mouseDrag () virtual inherited
Reimplemented from Item.
void Item::mouseMove () virtual inherited
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void Button::mousePress () virtual inherited
Reimplemented from Item.
virtual void Button::mouseRelease () virtual inherited
Reimplemented from Item.
virtual void CheckBox::playClickSound () virtual inherited
Reimplemented from Button.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Button::resizeNotify () virtual inherited
Reimplemented from Label.
virtual void XonoticCheckBox::saveCvars () virtual
virtual void XonoticCheckBox::setChecked () virtual
Reimplemented from CheckBox.
virtual void Label::setText () virtual inherited
Reimplemented in InputBox, and XonoticInputBox.
virtual void Button::showNotify () virtual inherited
Reimplemented from Item.
virtual void CheckBox::toString () virtual inherited
Reimplemented from Label.
CheckBox::void (entity , entity) inherited
Member Data Documentation
float Label::align = 0.5 inherited
Definition at line 15 of file label.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float Button::allowFocusSound = 1 inherited
Definition at line 25 of file button.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float XonoticCheckBox::alpha = SKINALPHA_TEXT
Definition at line 22 of file checkbox.qh.
float Button::alpha2 = 1 inherited
Definition at line 38 of file button.qh.
entity Button::applyButton = NULL inherited
Definition at line 28 of file button.qh.
float Button::buttonLeftOfText = 0 inherited
Definition at line 23 of file button.qh.
float CheckBox::checked = 0 inherited
Definition at line 11 of file checkbox.qh.
float Button::clickTime = 0 inherited
Definition at line 27 of file button.qh.
vector XonoticCheckBox::color = SKINCOLOR_CHECKBOX_N
Definition at line 12 of file checkbox.qh.
vector Button::color2 = '1 1 1' inherited
Definition at line 37 of file button.qh.
vector XonoticCheckBox::colorC = SKINCOLOR_CHECKBOX_C
Definition at line 13 of file checkbox.qh.
vector XonoticCheckBox::colorD = SKINCOLOR_CHECKBOX_D
Definition at line 15 of file checkbox.qh.
vector XonoticCheckBox::colorF = SKINCOLOR_CHECKBOX_F
Definition at line 14 of file checkbox.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
string Label::currentText = string_null inherited
Definition at line 13 of file label.qh.
string XonoticCheckBox::cvarName = string_null
Definition at line 17 of file checkbox.qh.
float CheckBox::disabled = 0 inherited
Definition at line 15 of file checkbox.qh.
float XonoticCheckBox::disabledAlpha = SKINALPHA_DISABLED
Definition at line 23 of file checkbox.qh.
bool Button::disableOnClick = false inherited
Definition at line 29 of file button.qh.
float Button::focusable = 1 inherited
Definition at line 24 of file button.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
float XonoticCheckBox::fontSize = SKINFONTSIZE_NORMAL
Definition at line 7 of file checkbox.qh.
float Button::forcePressed = 0 inherited
Definition at line 32 of file button.qh.
string XonoticCheckBox::image = SKINGFX_CHECKBOX
Definition at line 8 of file checkbox.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
entity XonoticCheckBox::linkedCheckBox = NULL
Definition at line 24 of file checkbox.qh.
float Label::marginLeft = 0 inherited
Definition at line 20 of file label.qh.
float Label::marginRight = 0 inherited
Definition at line 21 of file label.qh.
float XonoticCheckBox::noValue = 0
Definition at line 10 of file checkbox.qh.
entity Button::onClickEntity = NULL inherited
Definition at line 17 of file button.qh.
vector Button::origin = '0 0 0' inherited
Definition at line 40 of file button.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Button::pressed = 0 inherited
Definition at line 26 of file button.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
float XonoticCheckBox::sendCvars = 0
Definition at line 20 of file checkbox.qh.
vector Button::size = '0 0 0' inherited
Definition at line 41 of file button.qh.
string Button::src = string_null inherited
Definition at line 18 of file button.qh.
string Button::src2 = string_null inherited
Definition at line 20 of file button.qh.
float Button::src2scale = 1 inherited
Definition at line 21 of file button.qh.
float CheckBox::srcMulti = 0 inherited
Definition at line 14 of file checkbox.qh.
string Button::srcSuffix = string_null inherited
Definition at line 19 of file button.qh.
string Label::text = string_null inherited
Definition at line 12 of file label.qh.
entity Label::textEntity = NULL inherited
Definition at line 28 of file label.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
float CheckBox::useDownAsChecked = 0 inherited
Definition at line 10 of file checkbox.qh.
float XonoticCheckBox::yesValue = 1
Definition at line 9 of file checkbox.qh.
The documentation for this class was generated from the following file:
menu/xonotic/checkbox.qh