Xonotic: server/pathlib/main.qh File Reference
main.qh File Reference
Functions
bool buildpath_nodefilter_none (vector n, vector c, vector p)
entity path_build (entity next, vector where, entity prev, entity start)
Function Documentation
bool buildpath_nodefilter_none (vector n, vector c, vector p)
Definition at line 321 of file main.qc.
Referenced by pathlib_waypointpath_step().
 {
     return false;
 }
entity path_build (entity next, vector where, entity prev, entity start)
Definition at line 326 of file main.qc.
References buildpath_nodefilter(), entity(), next, setorigin(), and spawn().
Referenced by pathlib_astar(), and pathlib_waypointpath_step().
 {
     if(prev && next)
         if(buildpath_nodefilter)
             if(buildpath_nodefilter(next.origin,where,prev.origin))
                 return next;
     entity path    = spawn();
     path.owner     = start;
     path.path_next = next;
     setorigin(path, where);
     if(!next)
         path.classname = "path_end";
     else
     {
         if(!prev)
             path.classname = "path_start";
         else
             path.classname = "path_node";
     }
     return path;
 }