Xonotic: menu/xonotic/dialog_multiplayer_media_screenshot_viewer.qc File Reference
dialog_multiplayer_media_screenshot_viewer.qc File Reference
#include "dialog_multiplayer_media_screenshot_viewer.qh"
#include "screenshotlist.qh"
#include "inputbox.qh"
#include "button.qh"
Functions
void decreaseZoom_Click (entity btn, entity me)
void increaseZoom_Click (entity btn, entity me)
void nextScreenshot_Click (entity btn, entity me)
void prevScreenshot_Click (entity btn, entity me)
void resetZoom_Click (entity btn, entity me)
void toggleSlideShow_Click (entity btn, entity me)
void XonoticScreenshotViewerDialog_close (entity me)
void XonoticScreenshotViewerDialog_fill (entity me)
float XonoticScreenshotViewerDialog_keyDown (entity me, float key, float ascii, float shift)
void XonoticScreenshotViewerDialog_loadScreenshot (entity me, string scrImage)
Variables
float music_playlist_index_backup
Function Documentation
void decreaseZoom_Click (entity btn, entity me)
Definition at line 43 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     me.screenshotImage.setZoom(me.screenshotImage, -1/2, false);
 }
void increaseZoom_Click (entity btn, entity me)
Definition at line 39 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     me.screenshotImage.setZoom(me.screenshotImage, -2, false);
 }
void nextScreenshot_Click (entity btn, entity me)
Definition at line 35 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     me.scrList.goScreenshot(me.scrList, +1);
 }
void prevScreenshot_Click (entity btn, entity me)
Definition at line 31 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     me.scrList.goScreenshot(me.scrList, -1);
 }
void resetZoom_Click (entity btn, entity me)
Definition at line 47 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     me.screenshotImage.setZoom(me.screenshotImage, 0, false);
 }
void toggleSlideShow_Click (entity btn, entity me)
Definition at line 51 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_fill(), and XonoticScreenshotViewerDialog_keyDown().
 {
     if (me.slideShowButton.forcePressed)
     {
         me.scrList.stopSlideShow(me.scrList);
         me.slideShowButton.forcePressed = 0;
     }
     else
     {
         me.scrList.startSlideShow(me.scrList);
         me.slideShowButton.forcePressed = 1;
     }
 }
void XonoticScreenshotViewerDialog_close (entity me)
Definition at line 107 of file dialog_multiplayer_media_screenshot_viewer.qc.
References cvar(), cvar_set(), ftos(), localcmd, music_playlist_index_backup, and SUPER.
 {
     // resume music
     if(!cvar("menu_screenshotviewer_enablemusic"))
     if(cvar("music_playlist_index") == 999)
     {
         cvar_set("music_playlist_index", ftos(music_playlist_index_backup));
     }
     else
         localcmd("\ncd resume\n");
     me.scrList.stopSlideShow(me.scrList);
     me.slideShowButton.forcePressed = 0;
     SUPER(XonoticScreenshotViewerDialog).close(me);
 }
void XonoticScreenshotViewerDialog_fill (entity me)
Definition at line 122 of file dialog_multiplayer_media_screenshot_viewer.qc.
References decreaseZoom_Click(), entity(), increaseZoom_Click(), makeXonoticButton(), makeXonoticScreenshotImage(), nextScreenshot_Click(), prevScreenshot_Click(), resetZoom_Click(), and toggleSlideShow_Click().
 {
     entity e;
     me.TR(me);
         me.TD(me, me.rows - 1, me.columns, e = makeXonoticScreenshotImage());
             e.showTitle = 0; // dialog title is enough
             me.screenshotImage = e;
     me.gotoRC(me, me.rows - 1, 0);
         me.TDempty(me, 1/20 * me.columns);
         me.TD(me, 1, 1/20 * me.columns, e = makeXonoticButton("-", '0 0 0'));
             e.onClick = decreaseZoom_Click;
             e.onClickEntity = me;
         me.TD(me, 1, 1/20 * me.columns, e = makeXonoticButton("+", '0 0 0'));
             e.onClick = increaseZoom_Click;
             e.onClickEntity = me;
         me.TD(me, 1, 2/20 * me.columns, e = makeXonoticButton(_("Reset"), '0 0 0'));
             e.onClick = resetZoom_Click;
             e.onClickEntity = me;
         me.TDempty(me, 2/20 * me.columns);
         me.TD(me, 1, 3/20 * me.columns, e = makeXonoticButton(_("Previous"), '0 0 0'));
             e.onClick = prevScreenshot_Click;
             e.onClickEntity = me;
         me.TD(me, 1, 3/20 * me.columns, e = makeXonoticButton(_("Next"), '0 0 0'));
             e.onClick = nextScreenshot_Click;
             e.onClickEntity = me;
         me.TDempty(me, 2/20 * me.columns);
         me.TD(me, 1, 4/20 * me.columns, e = makeXonoticButton(_("Slide show"), '0 0 0'));
             e.onClick = toggleSlideShow_Click;
             e.onClickEntity = me;
             me.slideShowButton = e;
 }
float XonoticScreenshotViewerDialog_keyDown (entity me, float key, float ascii, float shift)
Definition at line 64 of file dialog_multiplayer_media_screenshot_viewer.qc.
References K_ENTER, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_MWHEELDOWN, K_MWHEELUP, K_RIGHTARROW, K_SPACE, NULL, S_CTRL, SUPER, and toggleSlideShow_Click().
 {
     switch(key)
     {
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             me.scrList.goScreenshot(me.scrList, -1);
             return 1;
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             me.scrList.goScreenshot(me.scrList, +1);
             return 1;
         case K_KP_ENTER:
         case K_ENTER:
         case K_SPACE:
             // we cannot use SPACE/ENTER directly, as in a dialog they are needed
             // to press buttons while browsing with only the keyboard
             if (shift & S_CTRL)
             {
                 toggleSlideShow_Click(NULL, me);
                 return 1;
             }
             return SUPER(XonoticScreenshotViewerDialog).keyDown(me, key, ascii, shift);
         default:
             if (key == K_MWHEELUP || ascii == '+')
             {
                 me.screenshotImage.setZoom(me.screenshotImage, -2, (key == K_MWHEELUP));
                 return 1;
             }
             else if (key == K_MWHEELDOWN || ascii == '-')
             {
                 me.screenshotImage.setZoom(me.screenshotImage, -1/2, (key == K_MWHEELDOWN));
                 return 1;
             }
             if (me.scrList.keyDown(me.scrList, key, ascii, shift))
             {
                 // keyDown has already changed the selected item
                 me.scrList.goScreenshot(me.scrList, 0);
                 return 1;
             }
             return SUPER(XonoticScreenshotViewerDialog).keyDown(me, key, ascii, shift);
     }
 }
void XonoticScreenshotViewerDialog_loadScreenshot (entity me, string scrImage)
Definition at line 8 of file dialog_multiplayer_media_screenshot_viewer.qc.
References cvar(), cvar_set(), localcmd, music_playlist_index_backup, and strcpy.
 {
     // disable music as it can lag depending on image loading time
     if(!cvar("menu_screenshotviewer_enablemusic"))
     if(cvar("music_playlist_index") != 999) // if the playlist isn't paused
     {
         // pause music
         if(cvar("music_playlist_index") != -1)
         {
             music_playlist_index_backup = cvar("music_playlist_index");
             cvar_set("music_playlist_sampleposition0", "0");
             cvar_set("music_playlist_index", "999");
         }
         else
             localcmd("\ncd pause\n");
     }
     if (me.currentScrPath == scrImage)
         return;
     strcpy(me.currentScrPath, scrImage);
     me.screenshotImage.load(me.screenshotImage, me.currentScrPath);
     me.frame.setText(me.frame, me.screenshotImage.screenshotTitle);
 }
Variable Documentation
float music_playlist_index_backup
Definition at line 7 of file dialog_multiplayer_media_screenshot_viewer.qc.
Referenced by XonoticScreenshotViewerDialog_close(), and XonoticScreenshotViewerDialog_loadScreenshot().