Xonotic: common/deathtypes/all.qh File Reference
common/deathtypes/all.qh File Reference
#include "../notifications.qh"
#include "all.inc"
Defines
#define DEATHTYPES_ALL_H
#define Deathtypes_from(i) _Deathtypes_from(i, NULL)
#define REGISTER_DEATHTYPE(id, msg_death, msg_death_by, extra)
#define DEATH_ISSPECIAL(t) (t >= DT_FIRST)
#define DEATH_IS(t, dt) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)) == dt)
#define DEATH_ENT(t) (DEATH_ISSPECIAL(t) ? (Deathtypes_from(t - DT_FIRST)) : NULL)
#define DEATH_ISVEHICLE(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "vehicle")
#define DEATH_ISTURRET(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "turret")
#define DEATH_ISMONSTER(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "monster")
#define DEATH_WEAPONOF(t) (DEATH_ISSPECIAL(t) ? WEP_Null : Weapons_from((t) & DEATH_WEAPONMASK))
#define DEATH_ISWEAPON(t, w) (DEATH_WEAPONOF(t) == (w))
Functions
int dt_identity (int i)
string Deathtype_Name (int deathtype)
Variables
entity death_msgself
entity death_msgmurder
string death_msgextra
const int DEATH_WEAPONMASK = BITS(8)
const int HITTYPE_SECONDARY = BITS(1) << 8
const int HITTYPE_SPLASH = BITS(1) << 9
automatically set by RadiusDamage
const int HITTYPE_BOUNCE = BITS(1) << 10
const int HITTYPE_RESERVED = BITS(1) << 11
const int HITTYPE_RESERVED2 = BITS(1) << 12
const int DEATH_HITTYPEMASK = HITTYPE_SECONDARY | HITTYPE_SPLASH | HITTYPE_BOUNCE | HITTYPE_RESERVED | HITTYPE_RESERVED2
const int DT_FIRST = BIT(13)
Define Documentation
#define DEATH_ENT (t) (DEATH_ISSPECIAL(t) ? (Deathtypes_from(t - DT_FIRST)) : NULL)
Definition at line 40 of file all.qh.
Referenced by Obituary().
#define DEATH_IS (t, dt) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)) == dt)
Definition at line 39 of file all.qh.
Referenced by healtharmor_applydamage(), and healtharmor_maxdamage().
#define DEATH_ISMONSTER (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "monster")
Definition at line 43 of file all.qh.
#define DEATH_ISSPECIAL (t) (t >= DT_FIRST)
Definition at line 38 of file all.qh.
Referenced by Damage(), Deathtype_Name(), door_damage(), Obituary(), Obituary_SpecialDeath(), PlayerDamage(), and RadiusDamageForSource().
#define DEATH_ISTURRET (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "turret")
Definition at line 42 of file all.qh.
#define DEATH_ISVEHICLE (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "vehicle")
Definition at line 41 of file all.qh.
#define DEATH_ISWEAPON (t, w) (DEATH_WEAPONOF(t) == (w))
Definition at line 45 of file all.qh.
Referenced by Damage(), PlayerDamage(), and vehicles_damage().
#define DEATH_WEAPONOF (t) (DEATH_ISSPECIAL(t) ? WEP_Null : Weapons_from((t) & DEATH_WEAPONMASK))
Definition at line 44 of file all.qh.
Referenced by Fire_AddDamage(), GiveFrags(), Obituary_WeaponDeath(), PlayerDamage(), RadiusDamageForSource(), and vehicles_damage().
#define DEATHTYPES_ALL_H
Definition at line 2 of file all.qh.
#define Deathtypes_from (i) _Deathtypes_from(i, NULL)
Definition at line 7 of file all.qh.
Referenced by Deathtype_Name(), and Obituary_SpecialDeath().
#define REGISTER_DEATHTYPE (id, msg_death, msg_death_by, extra)
Value:
REGISTER(Deathtypes, DEATH, id, m_id, new_pure(deathtype)) { \
        this.m_id += DT_FIRST; \
        this.nent_name = #id; \
        this.death_msgextra = extra; \
        if (msg_death       != NO_MSG) this.death_msgself   = msg_multi_notifs[dt_identity(msg_death    - 1)]; \
        if (msg_death_by    != NO_MSG) this.death_msgmurder = msg_multi_notifs[dt_identity(msg_death_by - 1)]; \
    }
Definition at line 17 of file all.qh.
Function Documentation
string Deathtype_Name (int deathtype)
Definition at line 3 of file all.qc.
References backtrace, DEATH_ISSPECIAL, Deathtypes_from, DT_FIRST, entity(), and ftos().
Referenced by LogDeath(), and Obituary().
{
    if (DEATH_ISSPECIAL(deathtype)) {
        entity deathent = Deathtypes_from(deathtype - DT_FIRST);
        if (!deathent) { backtrace("Deathtype_Name: Could not find deathtype entity!\n"); return ""; }
        return deathent.nent_name;
    }
    return ftos(deathtype);
}
int dt_identity (int i)
Definition at line 15 of file all.qh.
{ return i; }
Variable Documentation
const int DEATH_HITTYPEMASK = HITTYPE_SECONDARY | HITTYPE_SPLASH | HITTYPE_BOUNCE | HITTYPE_RESERVED | HITTYPE_RESERVED2
Definition at line 34 of file all.qh.
string death_msgextra
Definition at line 13 of file all.qh.
entity death_msgmurder
Definition at line 12 of file all.qh.
entity death_msgself
Definition at line 11 of file all.qh.
const int DEATH_WEAPONMASK = BITS(8)
Definition at line 26 of file all.qh.
const int DT_FIRST = BIT(13)
Definition at line 36 of file all.qh.
Referenced by Deathtype_Name(), and Obituary_SpecialDeath().
const int HITTYPE_BOUNCE = BITS(1) << 10
Definition at line 30 of file all.qh.
Referenced by RadiusDamageForSource().
const int HITTYPE_RESERVED = BITS(1) << 11
Definition at line 32 of file all.qh.
const int HITTYPE_RESERVED2 = BITS(1) << 12
Definition at line 33 of file all.qh.
const int HITTYPE_SECONDARY = BITS(1) << 8
Definition at line 27 of file all.qh.
Referenced by RadiusDamageForSource().
const int HITTYPE_SPLASH = BITS(1) << 9
automatically set by RadiusDamage
Definition at line 29 of file all.qh.
Referenced by adaptor_think2use_hittype_splash(), door_damage(), and RadiusDamageForSource().