Xonotic: menu/xonotic/gametypelist.qc File Reference
gametypelist.qc File Reference
#include "gametypelist.qh"
#include "dialog_multiplayer_create.qh"
#include <common/mapinfo.qh>
Functions
entity makeXonoticGametypeList ()
void XonoticGametypeList_clickListBoxItem (entity me, float i, vector where)
void XonoticGametypeList_configureXonoticGametypeList (entity me)
void XonoticGametypeList_draw (entity me)
void XonoticGametypeList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
void XonoticGametypeList_focusedItemChangeNotify (entity me)
float XonoticGametypeList_keyDown (entity me, float scan, float ascii, float shift)
void XonoticGametypeList_loadCvars (entity me)
void XonoticGametypeList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticGametypeList_saveCvars (entity me)
void XonoticGametypeList_setSelected (entity me, float i)
Function Documentation
entity makeXonoticGametypeList ()
Definition at line 6 of file gametypelist.qc.
References entity(), and NEW.
Referenced by XonoticServerCreateTab_fill().
 {
     entity me;
     me = NEW(XonoticGametypeList);
     me.configureXonoticGametypeList(me);
     return me;
 }
void XonoticGametypeList_clickListBoxItem (entity me, float i, vector where)
Definition at line 126 of file gametypelist.qc.
References m_play_click_sound(), and MENU_SOUND_SELECT.
 {
     m_play_click_sound(MENU_SOUND_SELECT);
 }
void XonoticGametypeList_configureXonoticGametypeList (entity me)
Definition at line 13 of file gametypelist.qc.
References draw_PreloadPictureWithFlags(), GameType_GetCount(), GameType_GetIcon(), GameType_GetTotalCount(), and PRECACHE_PIC_MIPMAP.
 {
     me.configureXonoticListBox(me);
     me.nItems = GameType_GetCount();
     if(SKINBOOL_GAMETYPELIST_ICON_BLUR)
     {
         for(int i = 0; i < GameType_GetTotalCount(); ++i)
             draw_PreloadPictureWithFlags(GameType_GetIcon(i), PRECACHE_PIC_MIPMAP);
     }
     me.loadCvars(me);
 }
void XonoticGametypeList_draw (entity me)
Definition at line 62 of file gametypelist.qc.
References GameType_GetCount(), and SUPER.
 {
     if(me.nItems != GameType_GetCount())
     {
         me.nItems = GameType_GetCount();
         me.setSelected(me, 0);
     }
     SUPER(XonoticGametypeList).draw(me);
 }
void XonoticGametypeList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 71 of file gametypelist.qc.
References _MapInfo_GetTeamPlayBool(), draw_CondensedFontFactor(), draw_Fill(), draw_fontscale, draw_Picture(), draw_Text(), draw_TextWidth(), eX, eY, GameType_GetIcon(), GameType_GetID(), GameType_GetName(), getFadedAlpha(), s1, s2, strcat(), and vector().
 {
     string s1, s2;
     if(isSelected)
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     else if(isFocused)
     {
         me.focusedItemAlpha = getFadedAlpha(me.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, me.focusedItemAlpha);
     }
     draw_Picture(me.columnIconOrigin * eX, GameType_GetIcon(i), me.columnIconSize * eX + eY, '1 1 1', SKINALPHA_LISTBOX_SELECTED);
     s1 = GameType_GetName(i);
     if(_MapInfo_GetTeamPlayBool(GameType_GetID(i)))
         s2 = _("teamplay");
     else
         s2 = _("free for all");
     vector save_fontscale = draw_fontscale;
     float f = draw_CondensedFontFactor(strcat(s1, " ", s2), false, me.realFontSize, 1);
     draw_fontscale.x *= f;
     vector fs = me.realFontSize;
     fs.x *= f;
     draw_Text(me.realUpperMargin * eY + me.columnNameOrigin * eX, s1, fs, '1 1 1', SKINALPHA_TEXT, 0);
     draw_Text(me.realUpperMargin * eY + (me.columnNameOrigin + 1.0 * (me.columnNameSize - draw_TextWidth(s2, 0, fs))) * eX, s2, fs, SKINCOLOR_TEXT, SKINALPHA_TEXT, 0);
     draw_fontscale = save_fontscale;
 }
void XonoticGametypeList_focusedItemChangeNotify (entity me)
Definition at line 130 of file gametypelist.qc.
References clearTooltip(), GameType_GetID(), MapInfo_Type_Description(), setZonedTooltip(), and string_null.
 {
     if(me.focusedItem >= 0)
         setZonedTooltip(me, MapInfo_Type_Description(GameType_GetID(me.focusedItem)), string_null);
     else
         clearTooltip(me);
 }
float XonoticGametypeList_keyDown (entity me, float scan, float ascii, float shift)
Definition at line 115 of file gametypelist.qc.
References K_ENTER, K_KP_ENTER, m_play_click_sound(), MENU_SOUND_EXECUTE, and SUPER.
 {
     if(scan == K_ENTER || scan == K_KP_ENTER)
     {
         m_play_click_sound(MENU_SOUND_EXECUTE);
         me.parent.gameTypeSelectNotify(me.parent);
         return 1;
     }
     return SUPER(XonoticGametypeList).keyDown(me, scan, ascii, shift);
 }
void XonoticGametypeList_loadCvars (entity me)
Definition at line 31 of file gametypelist.qc.
References cnt, GameType_GetCount(), GameType_GetID(), and MapInfo_CurrentGametype().
 {
     Gametype t = MapInfo_CurrentGametype();
     int cnt = GameType_GetCount();
     float i;
     for(i = 0; i < cnt; ++i)
         if(t == GameType_GetID(i))
             break;
     if(i >= cnt)
     {
         for(i = 0; i < cnt; ++i)
             if(t == MAPINFO_TYPE_DEATHMATCH)
                 break;
         if(i >= cnt)
             i = 0;
     }
     me.setSelected(me, i);
     // do we need this: me.parent.gameTypeChangeNotify(me.parent); // to make sure
 }
void XonoticGametypeList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 100 of file gametypelist.qc.
References SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticGametypeList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.itemAbsSize.y = absSize.y * me.itemHeight;
     me.itemAbsSize.x = absSize.x * (1 - me.controlWidth);
     me.realFontSize.y = me.fontSize / me.itemAbsSize.y;
     me.realFontSize.x = me.fontSize / me.itemAbsSize.x;
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
     me.columnIconOrigin = 0;
     me.columnIconSize = me.itemAbsSize.y / me.itemAbsSize.x;
     me.columnNameOrigin = me.columnIconOrigin + me.columnIconSize + (0.5 * me.realFontSize.x);
     me.columnNameSize = 1 - me.columnIconSize - (1.5 * me.realFontSize.x);
 }
void XonoticGametypeList_saveCvars (entity me)
Definition at line 50 of file gametypelist.qc.
References entity(), GameType_GetID(), MapInfo_CurrentGametype(), MapInfo_SwitchGameType(), and owner.
 {
     Gametype t = GameType_GetID(me.selectedItem);
     if (t == MapInfo_CurrentGametype()) {
         return;
     }
     MapInfo_SwitchGameType(t);
     entity owner = me.parent;
     if (owner) { // not set immediately
         owner.gameTypeChangeNotify(owner);
     }
 }
void XonoticGametypeList_setSelected (entity me, float i)
Definition at line 26 of file gametypelist.qc.
References SUPER.
 {
     SUPER(XonoticGametypeList).setSelected(me, i);
     me.saveCvars(me);
 }