Xonotic: menu/anim/animation.qc File Reference
animation.qc File Reference
#include "animation.qh"
#include "../menu.qh"
Functions
METHOD (Animation, configureAnimation, void(entity this, entity obj, void(entity, float) objSetter, float animStartTime, float animDuration, float animStartValue, float animEndValue))
this setValueStartEnd (this, animStartValue, animEndValue)
METHOD (Animation, setObjectSetter, void(entity this, entity o, void(entity, float) s))
if (tickTime >=(this.startTime+this.duration)) this.finishAnim(this)
this setter (this.object, this.value)
Variables
this duration = e - s
this delta = e - s
else this value = this.calcValue(this, (tickTime - this.startTime), this.duration, this.startValue, this.delta)
this finished = true
Function Documentation
if (tickTime >= this.startTime+this.duration)
METHOD (Animation , configureAnimation , void(entity this, entity obj, void(entity, float) objSetter, float animStartTime, float animDuration, float animStartValue, float animEndValue))
Definition at line 5 of file animation.qc.
References setValueStartEnd().
     {
         this.setObjectSetter(this, obj, objSetter);
         this.setTimeStartDuration(this, animStartTime, animDuration);
         this.setValueStartEnd(this, animStartValue, animEndValue);
     }
METHOD (Animation , setObjectSetter , void(entity this, entity o, void(entity, float) s))
Definition at line 42 of file animation.qc.
References s, and setter().
     {
         this.object = o;
         this.setter = s;
     }
this setter (this. object, this. value)
Referenced by METHOD().
this setValueStartEnd (this , animStartValue , animEndValue)
Referenced by METHOD().
Variable Documentation
this delta = e - s
Definition at line 33 of file animation.qc.
Referenced by CSQC_Demo_Camera(), GameCommand_trace(), MoveToRandomLocationWithinBounds(), PingPLReport_Think(), Portal_WillHitPlane(), SUB_CalcAngleMove(), SUB_CalcMove(), and SUB_CalcMove_controller_think().
this duration = e - s
Definition at line 21 of file animation.qc.
Referenced by centerprint_generic(), and getNewChildDuration().
this finished = true
Definition at line 86 of file animation.qc.
else this value = this.calcValue(this, (tickTime - this.startTime), this.duration, this.startValue, this.delta)
Definition at line 53 of file animation.qc.
Referenced by GetTeamCounts(), HUD_QuickMenu(), and if().