Xonotic: menu/xonotic/button.qc File Reference
button.qc File Reference
#include "button.qh"
Functions
entity makeXonoticButton (string theText, vector theColor)
entity makeXonoticButton_T (string theText, vector theColor, string theTooltip)
void XonoticButton_configureXonoticButton (entity me, string theText, vector theColor, string theTooltip)
Function Documentation
makeXonoticButton()
entity makeXonoticButton (string theText, vector theColor)
Definition at line 10 of file button.qc.
References makeXonoticButton_T(), and string_null.
Referenced by XonoticCreditsDialog_fill(), XonoticScreenshotViewerDialog_fill(), and XonoticWinnerDialog_fill().
 {
     return makeXonoticButton_T(theText, theColor, string_null);
 }
makeXonoticButton_T()
entity makeXonoticButton_T (string theText, vector theColor, string theTooltip)
Definition at line 3 of file button.qc.
References entity(), and NEW.
Referenced by makeXonoticButton(), and XonoticTabController_makeTabButton_T().
 {
     entity me;
     me = NEW(XonoticButton);
     me.configureXonoticButton(me, theText, theColor, theTooltip);
     return me;
 }
XonoticButton_configureXonoticButton()
void XonoticButton_configureXonoticButton (entity me, string theText, vector theColor, string theTooltip)
Definition at line 15 of file button.qc.
References setZonedTooltip(), and string_null.
 {
     if(theColor == '0 0 0')
     {
         me.configureButton(me, theText, me.fontSize, me.image);
     }
     else
     {
         me.configureButton(me, theText, me.fontSize, me.grayImage);
         me.color = theColor;
         me.colorC = theColor;
         me.colorF = theColor;
     }
     setZonedTooltip(me, theTooltip, string_null);
 }