Xonotic: common/gamemodes/gamemode/clanarena/sv_clanarena.qc File Reference
sv_clanarena.qc File Reference
#include "sv_clanarena.qh"
Functions
bool CA_CheckTeams ()
float CA_CheckWinner ()
void CA_count_alive_players ()
int CA_GetWinnerTeam ()
bool ca_isEliminated (entity e)
entity ca_LastPlayerForTeam (entity this)
void ca_LastPlayerForTeam_Notify (entity this)
void CA_RoundStart ()
entity CA_SpectateNext (entity player, entity start)
Returns next available player to spectate if g_ca_spectate_enemies == 0.
MUTATOR_HOOKFUNCTION (ca, PlayerSpawn)
MUTATOR_HOOKFUNCTION (ca, ForbidSpawn)
MUTATOR_HOOKFUNCTION (ca, PutClientInServer)
MUTATOR_HOOKFUNCTION (ca, reset_map_players)
MUTATOR_HOOKFUNCTION (ca, ClientConnect)
MUTATOR_HOOKFUNCTION (ca, reset_map_global)
MUTATOR_HOOKFUNCTION (ca, TeamBalance_CheckAllowedTeams, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (ca, PlayerDies)
MUTATOR_HOOKFUNCTION (ca, ClientDisconnect)
MUTATOR_HOOKFUNCTION (ca, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (ca, ForbidThrowCurrentWeapon)
MUTATOR_HOOKFUNCTION (ca, GiveFragsForKill, CBC_ORDER_FIRST)
MUTATOR_HOOKFUNCTION (ca, SetStartItems)
MUTATOR_HOOKFUNCTION (ca, Damage_Calculate)
MUTATOR_HOOKFUNCTION (ca, FilterItem)
MUTATOR_HOOKFUNCTION (ca, PlayerDamage_SplitHealthArmor)
MUTATOR_HOOKFUNCTION (ca, CalculateRespawnTime)
MUTATOR_HOOKFUNCTION (ca, PlayerRegen)
MUTATOR_HOOKFUNCTION (ca, Scores_CountFragsRemaining)
MUTATOR_HOOKFUNCTION (ca, SpectateSet)
MUTATOR_HOOKFUNCTION (ca, SpectateNext)
MUTATOR_HOOKFUNCTION (ca, SpectatePrev)
MUTATOR_HOOKFUNCTION (ca, Bot_FixCount, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (ca, ClientCommand_Spectate)
MUTATOR_HOOKFUNCTION (ca, WantWeapon)
MUTATOR_HOOKFUNCTION (ca, HideTeamNagger)
MUTATOR_HOOKFUNCTION (ca, GetPlayerStatus)
MUTATOR_HOOKFUNCTION (ca, SetWeaponArena)
MUTATOR_HOOKFUNCTION (ca, SV_ParseServerCommand)
void nades_Clear (entity player)
Variables
float autocvar_g_ca_damage2score_multiplier
bool autocvar_g_ca_spectate_enemies
Function Documentation
bool CA_CheckTeams ()
Definition at line 112 of file sv_clanarena.qc.
References allowed_to_spawn, CA_count_alive_players(), ca_teams, NULL, NUM_TEAMS, NumTeams(), Team_GetNumberOfAlivePlayers(), Team_GetNumberOfAliveTeams(), Team_GetTeamFromIndex(), Team_IndexToBit(), and total_players.
Referenced by REGISTER_MUTATOR().
 {
     static int prev_missing_teams_mask;
     allowed_to_spawn = true;
     CA_count_alive_players();
     if (Team_GetNumberOfAliveTeams() == NumTeams(ca_teams))
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return true;
     }
     if(total_players == 0)
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return false;
     }
     int missing_teams_mask = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if ((ca_teams & Team_IndexToBit(i)) &&
             (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(i)) == 0))
         {
             missing_teams_mask |= Team_IndexToBit(i);
         }
     }
     if(prev_missing_teams_mask != missing_teams_mask)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_MISSING_TEAMS, missing_teams_mask);
         prev_missing_teams_mask = missing_teams_mask;
     }
     return false;
 }
float CA_CheckWinner ()
Definition at line 65 of file sv_clanarena.qc.
References allowed_to_spawn, APP_TEAM_NUM, autocvar_g_ca_round_timelimit, autocvar_g_ca_warmup, CA_count_alive_players(), CA_GetWinnerTeam(), FOREACH_CLIENT, IS_PLAYER, nades_Clear(), NULL, round_handler_GetEndTime, round_handler_Init(), ST_CA_ROUNDS, Team_GetNumberOfAliveTeams(), TeamScore_AddToTeam(), and time.
Referenced by REGISTER_MUTATOR().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         FOREACH_CLIENT(IS_PLAYER(it), { nades_Clear(it); });
         allowed_to_spawn = false;
         game_stopped = true;
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         return 1;
     }
     CA_count_alive_players();
     if (Team_GetNumberOfAliveTeams() > 1)
     {
         return 0;
     }
     int winner_team = CA_GetWinnerTeam();
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_CA_ROUNDS, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     allowed_to_spawn = false;
     game_stopped = true;
     round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
     FOREACH_CLIENT(IS_PLAYER(it), { nades_Clear(it); });
     return 1;
 }
void CA_count_alive_players ()
Definition at line 6 of file sv_clanarena.qc.
References entity(), Entity_GetTeam(), Entity_HasValidTeam(), FOREACH_CLIENT, IS_DEAD, IS_PLAYER, IS_REAL_CLIENT, NUM_TEAMS, Team_GetNumberOfAlivePlayers(), Team_GetTeamFromIndex(), Team_SetNumberOfAlivePlayers(), and total_players.
Referenced by CA_CheckTeams(), and CA_CheckWinner().
 {
     total_players = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         Team_SetNumberOfAlivePlayers(Team_GetTeamFromIndex(i), 0);
     }
     FOREACH_CLIENT(IS_PLAYER(it) && Entity_HasValidTeam(it),
     {
         ++total_players;
         if (IS_DEAD(it))
         {
             continue;
         }
         entity team_ = Entity_GetTeam(it);
         int num_alive = Team_GetNumberOfAlivePlayers(team_);
         ++num_alive;
         Team_SetNumberOfAlivePlayers(team_, num_alive);
     });
     FOREACH_CLIENT(IS_REAL_CLIENT(it),
     {
         STAT(REDALIVE, it) = Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(
             1));
         STAT(BLUEALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(2));
         STAT(YELLOWALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(3));
         STAT(PINKALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(4));
     });
 }
int CA_GetWinnerTeam ()
Definition at line 38 of file sv_clanarena.qc.
References NUM_TEAM_1, NUM_TEAMS, Team_GetNumberOfAlivePlayers(), Team_GetTeamFromIndex(), and Team_IndexToTeam().
Referenced by CA_CheckWinner().
 {
     int winner_team = 0;
     if (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(1)) >= 1)
     {
         winner_team = NUM_TEAM_1;
     }
     for (int i = 2; i <= NUM_TEAMS; ++i)
     {
         if (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(i)) >= 1)
         {
             if (winner_team != 0)
             {
                 return 0;
             }
             winner_team = Team_IndexToTeam(i);
         }
     }
     if (winner_team)
     {
         return winner_team;
     }
     return -1; // no player left
 }
bool ca_isEliminated (entity e)
Definition at line 148 of file sv_clanarena.qc.
References FRAGS_PLAYER_OUT_OF_GAME, and IS_DEAD.
Referenced by REGISTER_MUTATOR().
 {
     if(e.caplayer == 1 && (IS_DEAD(e) || e.frags == FRAGS_PLAYER_OUT_OF_GAME))
         return true;
     if(e.caplayer == 0.5)
         return true;
     return false;
 }
entity ca_LastPlayerForTeam (entity this)
Definition at line 251 of file sv_clanarena.qc.
References entity(), FOREACH_CLIENT, IS_DEAD, IS_PLAYER, NULL, and SAME_TEAM.
Referenced by ca_LastPlayerForTeam_Notify().
 {
     entity last_pl = NULL;
     FOREACH_CLIENT(IS_PLAYER(it) && it != this, {
         if (!IS_DEAD(it) && SAME_TEAM(this, it))
         {
             if (!last_pl)
                 last_pl = it;
             else
                 return NULL;
         }
     });
     return last_pl;
 }
void ca_LastPlayerForTeam_Notify (entity this)
Definition at line 266 of file sv_clanarena.qc.
References ca_LastPlayerForTeam(), entity(), round_handler_IsActive, round_handler_IsRoundStarted, and warmup_stage.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if (!warmup_stage && round_handler_IsActive() && round_handler_IsRoundStarted())
     {
         entity pl = ca_LastPlayerForTeam(this);
         if (pl)
             Send_Notification(NOTIF_ONE, pl, MSG_CENTER, CENTER_ALONE);
     }
 }
void CA_RoundStart ()
Definition at line 107 of file sv_clanarena.qc.
References allowed_to_spawn, boolean, and warmup_stage.
Referenced by REGISTER_MUTATOR().
 {
     allowed_to_spawn = boolean(warmup_stage);
 }
entity CA_SpectateNext (entity player, entity start)
Returns next available player to spectate if g_ca_spectate_enemies == 0.
Definition at line 158 of file sv_clanarena.qc.
References classname, entity(), find(), NULL, SAME_TEAM, and STR_PLAYER.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if (SAME_TEAM(start, player)) return start;
     // continue from current player
     for (entity e = start; (e = find(e, classname, STR_PLAYER)); )
     {
         if (SAME_TEAM(player, e)) return e;
     }
     // restart from the beginning
     for (entity e = NULL; (e = find(e, classname, STR_PLAYER)); )
     {
         if (SAME_TEAM(player, e)) return e;
     }
     return start;
 }
MUTATOR_HOOKFUNCTION (ca , PlayerSpawn)
Definition at line 175 of file sv_clanarena.qc.
References eliminatedPlayers, entity(), M_ARGV, and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     player.caplayer = 1;
     if (!warmup_stage)
         eliminatedPlayers.SendFlags |= 1;
 }
MUTATOR_HOOKFUNCTION (ca , ForbidSpawn)
Definition at line 184 of file sv_clanarena.qc.
References allowed_to_spawn, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // spectators / observers that weren't playing can join; they are
     // immediately forced to observe in the PutClientInServer hook
     // this way they are put in a team and can play in the next round
     if (!allowed_to_spawn && player.caplayer)
         return true;
     return false;
 }
MUTATOR_HOOKFUNCTION (ca , PutClientInServer)
Definition at line 196 of file sv_clanarena.qc.
References allowed_to_spawn, CS(), entity(), IS_PLAYER, jointime, M_ARGV, time, and TRANSMUTE().
 {
     entity player = M_ARGV(0, entity);
     if (!allowed_to_spawn && IS_PLAYER(player)) // this is true even when player is trying to join
     {
         TRANSMUTE(Observer, player);
         if (CS(player).jointime != time && !player.caplayer) // not when connecting
         {
             player.caplayer = 0.5;
             Send_Notification(NOTIF_ONE_ONLY, player, MSG_INFO, INFO_CA_JOIN_LATE);
         }
     }
 }
MUTATOR_HOOKFUNCTION (ca , reset_map_players)
Definition at line 211 of file sv_clanarena.qc.
References bot_relinkplayerlist(), CS(), FOREACH_CLIENT, IS_BOT_CLIENT, PutClientInServer(), and TRANSMUTE().
 {
     FOREACH_CLIENT(true, {
         CS(it).killcount = 0;
         if (!it.caplayer && IS_BOT_CLIENT(it))
         {
             it.team = -1;
             it.caplayer = 1;
         }
         if (it.caplayer)
         {
             TRANSMUTE(Player, it);
             it.caplayer = 1;
             PutClientInServer(it);
         }
     });
     bot_relinkplayerlist();
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , ClientConnect)
Definition at line 231 of file sv_clanarena.qc.
References entity(), M_ARGV, and TRANSMUTE().
 {
     entity player = M_ARGV(0, entity);
     TRANSMUTE(Observer, player);
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , reset_map_global)
Definition at line 239 of file sv_clanarena.qc.
References allowed_to_spawn.
 {
     allowed_to_spawn = true;
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , TeamBalance_CheckAllowedTeams , CBC_ORDER_EXCLUSIVE)
Definition at line 245 of file sv_clanarena.qc.
References ca_teams, and M_ARGV.
 {
     M_ARGV(0, float) = ca_teams;
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , PlayerDies)
Definition at line 276 of file sv_clanarena.qc.
References allowed_to_spawn, bot_clear(), ca_LastPlayerForTeam_Notify(), eliminatedPlayers, entity(), IS_BOT_CLIENT, M_ARGV, RESPAWN_FORCE, RESPAWN_SILENT, time, and warmup_stage.
 {
     entity frag_target = M_ARGV(2, entity);
     ca_LastPlayerForTeam_Notify(frag_target);
     if (!allowed_to_spawn)
     {
         frag_target.respawn_flags = RESPAWN_SILENT;
         // prevent unwanted sudden rejoin as spectator and movement of spectator camera
         frag_target.respawn_time = time + 2;
     }
     frag_target.respawn_flags |= RESPAWN_FORCE;
     if (!warmup_stage)
     {
         eliminatedPlayers.SendFlags |= 1;
         if (IS_BOT_CLIENT(frag_target))
             bot_clear(frag_target);
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , ClientDisconnect)
Definition at line 297 of file sv_clanarena.qc.
References ca_LastPlayerForTeam_Notify(), entity(), IS_DEAD, IS_PLAYER, and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if (IS_PLAYER(player) && !IS_DEAD(player))
         ca_LastPlayerForTeam_Notify(player);
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , MakePlayerObserver)
Definition at line 306 of file sv_clanarena.qc.
References ca_LastPlayerForTeam_Notify(), eliminatedPlayers, entity(), FRAGS_PLAYER_OUT_OF_GAME, IS_DEAD, IS_PLAYER, M_ARGV, and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if (IS_PLAYER(player) && !IS_DEAD(player))
         ca_LastPlayerForTeam_Notify(player);
     if (player.killindicator_teamchange == -2) // player wants to spectate
         player.caplayer = 0;
     if (player.caplayer)
         player.frags = FRAGS_PLAYER_OUT_OF_GAME;
     if (!warmup_stage)
         eliminatedPlayers.SendFlags |= 1;
     if (!player.caplayer)
         return false;  // allow team reset
     return true;  // prevent team reset
 }
MUTATOR_HOOKFUNCTION (ca , ForbidThrowCurrentWeapon)
Definition at line 323 of file sv_clanarena.qc.
 {
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , GiveFragsForKill , CBC_ORDER_FIRST)
Definition at line 328 of file sv_clanarena.qc.
References M_ARGV.
 {
     M_ARGV(2, float) = 0; // score will be given to the winner team when the round ends
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , SetStartItems)
Definition at line 334 of file sv_clanarena.qc.
References cvar(), IT_UNLIMITED_AMMO, start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, and warmup_start_health.
 {
     start_items       &= ~IT_UNLIMITED_AMMO;
     start_health       = warmup_start_health       = cvar("g_lms_start_health");
     start_armorvalue   = warmup_start_armorvalue   = cvar("g_lms_start_armor");
     start_ammo_shells  = warmup_start_ammo_shells  = cvar("g_lms_start_ammo_shells");
     start_ammo_nails   = warmup_start_ammo_nails   = cvar("g_lms_start_ammo_nails");
     start_ammo_rockets = warmup_start_ammo_rockets = cvar("g_lms_start_ammo_rockets");
     start_ammo_cells   = warmup_start_ammo_cells   = cvar("g_lms_start_ammo_cells");
     start_ammo_plasma  = warmup_start_ammo_plasma  = cvar("g_lms_start_ammo_plasma");
     start_ammo_fuel    = warmup_start_ammo_fuel    = cvar("g_lms_start_ammo_fuel");
 }
MUTATOR_HOOKFUNCTION (ca , Damage_Calculate)
Definition at line 347 of file sv_clanarena.qc.
References entity(), IS_DEAD, IS_PLAYER, M_ARGV, and SAME_TEAM.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float frag_deathtype = M_ARGV(3, float);
     float frag_damage = M_ARGV(4, float);
     float frag_mirrordamage = M_ARGV(5, float);
     if (IS_PLAYER(frag_target))
     if (!IS_DEAD(frag_target))
     if (frag_target == frag_attacker || SAME_TEAM(frag_target, frag_attacker) || frag_deathtype == DEATH_FALL.m_id)
         frag_damage = 0;
     frag_mirrordamage = 0;
     M_ARGV(4, float) = frag_damage;
     M_ARGV(5, float) = frag_mirrordamage;
 }
MUTATOR_HOOKFUNCTION (ca , FilterItem)
Definition at line 366 of file sv_clanarena.qc.
References autocvar_g_pickup_items, autocvar_g_powerups, entity(), FL_POWERUP, and M_ARGV.
 {
     entity item = M_ARGV(0, entity);
     if (autocvar_g_powerups <= 0)
     if (item.flags & FL_POWERUP)
         return true;
     if (autocvar_g_pickup_items <= 0)
         return true;
 }
MUTATOR_HOOKFUNCTION (ca , PlayerDamage_SplitHealthArmor)
Definition at line 378 of file sv_clanarena.qc.
References autocvar_g_ca_damage2score_multiplier, bound(), DIFF_TEAM, entity(), GameRules_scoring_add_team, GetResource(), IS_PLAYER, M_ARGV, max(), RES_ARMOR, and RES_HEALTH.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float frag_damage = M_ARGV(7, float);
     float damage_take = bound(0, M_ARGV(4, float), GetResource(frag_target, RES_HEALTH));
     float damage_save = bound(0, M_ARGV(5, float), GetResource(frag_target, RES_ARMOR));
     float excess = max(0, frag_damage - damage_take - damage_save);
     if (frag_target != frag_attacker && IS_PLAYER(frag_attacker) && DIFF_TEAM(frag_target, frag_attacker))
         GameRules_scoring_add_team(frag_attacker, SCORE, (frag_damage - excess) * autocvar_g_ca_damage2score_multiplier);
 }
MUTATOR_HOOKFUNCTION (ca , CalculateRespawnTime)
Definition at line 392 of file sv_clanarena.qc.
 {
     // no respawn calculations needed, player is forced to spectate anyway
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , PlayerRegen)
Definition at line 398 of file sv_clanarena.qc.
 {
     // no regeneration in CA
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , Scores_CountFragsRemaining)
Definition at line 404 of file sv_clanarena.qc.
 {
     // announce remaining frags
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , SpectateSet)
Definition at line 410 of file sv_clanarena.qc.
References autocvar_g_ca_spectate_enemies, DIFF_TEAM, entity(), and M_ARGV.
 {
     entity client = M_ARGV(0, entity);
     entity targ = M_ARGV(1, entity);
     if (!autocvar_g_ca_spectate_enemies && client.caplayer)
     if (DIFF_TEAM(targ, client))
         return true;
 }
MUTATOR_HOOKFUNCTION (ca , SpectateNext)
Definition at line 420 of file sv_clanarena.qc.
References autocvar_g_ca_spectate_enemies, CA_SpectateNext(), entity(), Entity_GetTeam(), M_ARGV, and Team_GetNumberOfAlivePlayers().
 {
     entity client = M_ARGV(0, entity);
     if (!autocvar_g_ca_spectate_enemies && client.caplayer
         && Team_GetNumberOfAlivePlayers(Entity_GetTeam(client)))
     {
         entity targ = M_ARGV(1, entity);
         M_ARGV(1, entity) = CA_SpectateNext(client, targ);
         return true;
     }
 }
MUTATOR_HOOKFUNCTION (ca , SpectatePrev)
Definition at line 433 of file sv_clanarena.qc.
References autocvar_g_ca_spectate_enemies, DIFF_TEAM, entity(), Entity_GetTeam(), M_ARGV, MUT_SPECPREV_CONTINUE, MUT_SPECPREV_FOUND, MUT_SPECPREV_RETURN, and Team_GetNumberOfAlivePlayers().
 {
     entity client = M_ARGV(0, entity);
     entity targ = M_ARGV(1, entity);
     entity first = M_ARGV(2, entity);
     if (!autocvar_g_ca_spectate_enemies && client.caplayer
         && Team_GetNumberOfAlivePlayers(Entity_GetTeam(client)))
     {
         do { targ = targ.chain; }
         while(targ && DIFF_TEAM(targ, client));
         if (!targ)
         {
             for (targ = first; targ && DIFF_TEAM(targ, client); targ = targ.chain);
             if (targ == client.enemy)
                 return MUT_SPECPREV_RETURN;
         }
     }
     else
         return MUT_SPECPREV_CONTINUE;
     M_ARGV(1, entity) = targ;
     return MUT_SPECPREV_FOUND;
 }
MUTATOR_HOOKFUNCTION (ca , Bot_FixCount , CBC_ORDER_EXCLUSIVE)
Definition at line 461 of file sv_clanarena.qc.
References FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, and M_ARGV.
 {
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         if (IS_PLAYER(it) || it.caplayer == 1)
             ++M_ARGV(0, int);
         ++M_ARGV(1, int);
     });
     return true;
 }
MUTATOR_HOOKFUNCTION (ca , ClientCommand_Spectate)
Definition at line 471 of file sv_clanarena.qc.
References autocvar_sv_spectate, entity(), IS_OBSERVER, IS_SPEC, M_ARGV, MUT_SPECCMD_CONTINUE, and MUT_SPECCMD_FORCE.
 {
     entity player = M_ARGV(0, entity);
     if (player.caplayer)
     {
         // they're going to spec, we can do other checks
         if (autocvar_sv_spectate && (IS_SPEC(player) || IS_OBSERVER(player)))
             Send_Notification(NOTIF_ONE_ONLY, player, MSG_INFO, INFO_CA_LEAVE);
         return MUT_SPECCMD_FORCE;
     }
     return MUT_SPECCMD_CONTINUE;
 }
MUTATOR_HOOKFUNCTION (ca , WantWeapon)
Definition at line 486 of file sv_clanarena.qc.
References M_ARGV.
 {
     M_ARGV(2, bool) = true; // all weapons
 }
MUTATOR_HOOKFUNCTION (ca , HideTeamNagger)
Definition at line 491 of file sv_clanarena.qc.
 {
     return true; // doesn't work well with the whole spectator as player thing
 }
MUTATOR_HOOKFUNCTION (ca , GetPlayerStatus)
Definition at line 496 of file sv_clanarena.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     return player.caplayer == 1;
 }
MUTATOR_HOOKFUNCTION (ca , SetWeaponArena)
Definition at line 503 of file sv_clanarena.qc.
References M_ARGV.
 {
     // most weapons arena
     if (M_ARGV(0, string) == "0" || M_ARGV(0, string) == "") M_ARGV(0, string) = "most";
 }
MUTATOR_HOOKFUNCTION (ca , SV_ParseServerCommand)
Definition at line 509 of file sv_clanarena.qc.
References allowed_to_spawn, cmd_name, M_ARGV, and shuffleteams_on_reset_map.
 {
     string cmd_name = M_ARGV(0, string);
     if (cmd_name == "shuffleteams")
         shuffleteams_on_reset_map = !allowed_to_spawn;
     return false;
 }
void nades_Clear (entity player)
Referenced by CA_CheckWinner().
Variable Documentation
float autocvar_g_ca_damage2score_multiplier
Definition at line 3 of file sv_clanarena.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_ca_spectate_enemies
Definition at line 4 of file sv_clanarena.qc.
Referenced by MUTATOR_HOOKFUNCTION().