Xonotic: common/effects/effectinfo_gentle_morphed.inc File Reference
effectinfo_gentle_morphed.inc File Reference
Functions
DEF (morphed_damage_hit)
DEF (morphed_damage_dissolve)
SUB (morphed_damage_hit)
SUB (morphed_damage_dissolve)
Function Documentation
DEF() [1/2]
DEF (morphed_damage_hit)
Referenced by SUB().
DEF() [2/2]
DEF (morphed_damage_dissolve)
SUB() [1/2]
SUB (morphed_damage_hit)
Definition at line 3 of file effectinfo_gentle_morphed.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
Referenced by SUB().
{
     MY(airfriction) = 5;
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 292;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0x9271fb";
     MY(count) = 0.500000;
     MY(gravity) = -0.400000;
     MY(liquidfriction) = 10;
     MY(sizeincrease) = -24;
     MY(size_min) = 14;
     MY(size_max) = 24;
     MY(tex_min) = 43;
     MY(tex_max) = 43;
     MY(type) = "spark";
     MY(velocityjitter) = '356.0 356.0 456.0';
 }
SUB() [2/2]
SUB (morphed_damage_dissolve)
Definition at line 40 of file effectinfo_gentle_morphed.inc.
References alpha_max, alpha_min, count, gravity, originjitter, and SUB().
{
     MY(airfriction) = 8;
     MY(alpha_min) = 456;
     MY(alpha_max) = 456;
     MY(alpha_fade) = 1828;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0x9271fb";
     MY(count) = 10;
     MY(gravity) = -1.900000;
     MY(liquidfriction) = 6;
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = -399;
     MY(spin_max) = -99;
     MY(sizeincrease) = -16;
     MY(size_min) = 40;
     MY(size_max) = 40;
     MY(tex_min) = 43;
     MY(tex_max) = 43;
     MY(type) = "smoke";
     MY(velocityjitter) = '256.0 256.0 512.0';
 }