Xonotic: menu/xonotic/slider.qc File Reference
slider.qc File Reference
#include "slider.qh"
Functions
entity makeXonoticSlider (float theValueMin, float theValueMax, float theValueStep, string theCvar)
entity makeXonoticSlider_T (float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
void XonoticSlider_configureXonoticSlider (entity me, float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
void XonoticSlider_loadCvars (entity me)
void XonoticSlider_saveCvars (entity me)
void XonoticSlider_setValue (entity me, float val)
void XonoticSlider_setValue_noAnim (entity me, float val)
Function Documentation
entity makeXonoticSlider (float theValueMin, float theValueMax, float theValueStep, string theCvar)
Definition at line 10 of file slider.qc.
References makeXonoticSlider_T(), and string_null.
Referenced by XonoticDamageTextSettings::fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDVoteDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), and XonoticSandboxToolsDialog_fill().
 {
     return makeXonoticSlider_T(theValueMin, theValueMax, theValueStep, theCvar, string_null);
 }
entity makeXonoticSlider_T (float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
Definition at line 3 of file slider.qc.
References entity(), and NEW.
Referenced by makeXonoticSlider(), XonoticEffectsSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticSlider);
     me.configureXonoticSlider(me, theValueMin, theValueMax, theValueStep, theCvar, theTooltip);
     return me;
 }
void XonoticSlider_configureXonoticSlider (entity me, float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
Definition at line 14 of file slider.qc.
References fabs(), setZonedTooltip(), and string_null.
 {
     float vp;
     vp = theValueStep * 10;
     while(fabs(vp) < fabs(theValueMax - theValueMin) / 40)
         vp *= 10;
     me.configureSliderVisuals(me, me.fontSize, me.align, me.valueSpace, me.image);
     me.cvarName = (theCvar) ? theCvar : string_null;
     if(theCvar)
         // Prevent flickering of the slider button by initialising the
         // slider out of bounds to hide the button before loading the cvar
         me.configureSliderValues(me, theValueMin, theValueMin-theValueStep, theValueMax, theValueStep, theValueStep, vp);
     else
         me.configureSliderValues(me, theValueMin, theValueMin, theValueMax, theValueStep, theValueStep, vp);
     me.loadCvars(me);
     setZonedTooltip(me, theTooltip, theCvar);
 }
void XonoticSlider_loadCvars (entity me)
Definition at line 49 of file slider.qc.
References cvar().
 {
     if (!me.cvarName)
         return;
     me.setValue_noAnim(me, cvar(me.cvarName));
 }
void XonoticSlider_saveCvars (entity me)
Definition at line 56 of file slider.qc.
References CheckSendCvars(), cvar_set(), and ftos_mindecimals().
 {
     if (!me.cvarName)
         return;
     cvar_set(me.cvarName, ftos_mindecimals(me.value));
     CheckSendCvars(me, me.cvarName);
 }
void XonoticSlider_setValue (entity me, float val)
Definition at line 33 of file slider.qc.
References SUPER.
 {
     if(val != me.value)
     {
         SUPER(XonoticSlider).setValue( me, val );
         me.saveCvars(me);
     }
 }
void XonoticSlider_setValue_noAnim (entity me, float val)
Definition at line 41 of file slider.qc.
References SUPER.
 {
     if(val != me.value)
     {
         SUPER(XonoticSlider).setValue_noAnim(me, val);
         me.saveCvars(me);
     }
 }