Xonotic: server/mutators/mutator/gamemode_keepaway.qh File Reference
gamemode_keepaway.qh File Reference
#include "../gamemode.qh"
Functions
void ka_DropEvent (entity plyr)
void ka_Initialize ()
REGISTER_MUTATOR (ka, false)
void (entity this) havocbot_role_ka_carrier
Variables
entity ka_ball
Function Documentation
void ka_DropEvent (entity plyr)
Definition at line 141 of file gamemode_keepaway.qc.
References ATTEN_NONE, autocvar_g_keepaway_ballcarrier_effects, autocvar_g_keepawayball_respawntime, CH_TRIGGER, crandom, DAMAGE_YES, EF_NODRAW, entity(), ka_EventLog(), ka_RespawnBall(), ka_TouchEvent(), MOVETYPE_BOUNCE, NULL, set_movetype(), setthink, sound, time, VOL_BASE, and world.
Referenced by ka_Reset(), and MUTATOR_HOOKFUNCTION().
 {
     entity ball;
     ball = plyr.ballcarried;
     if(!ball) { return; }
     // reset the ball
     setattachment(ball, NULL, "");
     set_movetype(ball, MOVETYPE_BOUNCE);
     ball.wait = time + 1;
     settouch(ball, ka_TouchEvent);
     setthink(ball, ka_RespawnBall);
     ball.nextthink = time + autocvar_g_keepawayball_respawntime;
     ball.takedamage = DAMAGE_YES;
     ball.effects &= ~EF_NODRAW;
     setorigin(ball, plyr.origin + '0 0 10');
     ball.velocity = '0 0 200' + '0 100 0'*crandom() + '100 0 0'*crandom();
     ball.owner.ballcarried = world; // I hope nothing checks to see if the world has the ball in the rest of my code :P
     ball.owner = NULL;
     // reset the player effects
     plyr.glow_trail = false;
     plyr.effects &= ~autocvar_g_keepaway_ballcarrier_effects;
     // messages and sounds
     ka_EventLog("dropped", plyr);
     Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_KEEPAWAY_DROPPED, plyr.netname);
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_KEEPAWAY_DROPPED, plyr.netname);
     sound(NULL, CH_TRIGGER, SND_KA_DROPPED, VOL_BASE, ATTEN_NONE); // ATTEN_NONE (it's a sound intended to be heard anywhere)
     // scoring
     // PlayerScore_Add(plyr, SP_KEEPAWAY_DROPS, 1); Not anymore, this is 100% the same as pickups and is useless.
     // waypoints
     WaypointSprite_Spawn(WP_KaBall, 0, 0, ball, '0 0 64', NULL, ball.team, ball, waypointsprite_attachedforcarrier, false, RADARICON_FLAGCARRIER);
     WaypointSprite_UpdateRule(ball.waypointsprite_attachedforcarrier, 0, SPRITERULE_DEFAULT);
     WaypointSprite_Ping(ball.waypointsprite_attachedforcarrier);
     WaypointSprite_Kill(plyr.waypointsprite_attachedforcarrier);
 }
void ka_Initialize ()
Definition at line 473 of file gamemode_keepaway.qc.
References ka_ScoreRules(), and ka_SpawnBall().
Referenced by REGISTER_MUTATOR().
 {
     ka_ScoreRules();
     ka_SpawnBall();
 }
REGISTER_MUTATOR (ka , false)
Definition at line 7 of file gamemode_keepaway.qh.
References error, ka_Initialize(), LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         ka_Initialize();
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back ka_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return false;
 }
void (entity this)
Variable Documentation
entity ka_ball
Definition at line 33 of file gamemode_keepaway.qh.
Referenced by havocbot_goalrating_ball(), ka_SpawnBall(), and MUTATOR_HOOKFUNCTION().