Xonotic: common/gamemodes/gamemode/tdm/sv_tdm.qh File Reference
sv_tdm.qh File Reference
#include <common/mutators/base.qh>
Functions
REGISTER_MUTATOR (tdm, false)
void tdm_DelayedInit (entity this)
Variables
int autocvar_g_tdm_point_leadlimit
int autocvar_g_tdm_point_limit
bool autocvar_g_tdm_team_spawns
Function Documentation
REGISTER_MUTATOR (tdm , false)
Definition at line 9 of file sv_tdm.qh.
References autocvar_g_tdm_point_leadlimit, autocvar_g_tdm_point_limit, autocvar_g_tdm_team_spawns, GameRules_limit_lead(), GameRules_limit_score(), GameRules_spawning_teams(), GameRules_teams(), InitializeEntity(), INITPRIO_GAMETYPE, MUTATOR_ONADD, MUTATOR_STATIC, NULL, and tdm_DelayedInit().
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_teams(true);
         GameRules_spawning_teams(autocvar_g_tdm_team_spawns);
         GameRules_limit_score(autocvar_g_tdm_point_limit);
         GameRules_limit_lead(autocvar_g_tdm_point_leadlimit);
         InitializeEntity(NULL, tdm_DelayedInit, INITPRIO_GAMETYPE);
     }
     return 0;
 }
void tdm_DelayedInit (entity this)
Definition at line 32 of file sv_tdm.qc.
References autocvar_g_tdm_teams, autocvar_g_tdm_teams_override, BIT, BITS, bound(), classname, find(), LOG_TRACE(), NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, tdm_SpawnTeam(), and teams.
Referenced by REGISTER_MUTATOR().
 {
     // if no teams are found, spawn defaults
     if(find(NULL, classname, "tdm_team") == NULL)
     {
         LOG_TRACE("No \"tdm_team\" entities found on this map, creating them anyway.");
         int numteams = autocvar_g_tdm_teams_override;
         if(numteams < 2) { numteams = autocvar_g_tdm_teams; }
         int teams = BITS(bound(2, numteams, 4));
         if(teams & BIT(0))
             tdm_SpawnTeam("Red", NUM_TEAM_1);
         if(teams & BIT(1))
             tdm_SpawnTeam("Blue", NUM_TEAM_2);
         if(teams & BIT(2))
             tdm_SpawnTeam("Yellow", NUM_TEAM_3);
         if(teams & BIT(3))
             tdm_SpawnTeam("Pink", NUM_TEAM_4);
     }
 }
Variable Documentation
int autocvar_g_tdm_point_leadlimit
Definition at line 5 of file sv_tdm.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_tdm_point_limit
Definition at line 4 of file sv_tdm.qh.
Referenced by REGISTER_MUTATOR().
bool autocvar_g_tdm_team_spawns
Definition at line 6 of file sv_tdm.qh.
Referenced by REGISTER_MUTATOR().