Xonotic: lib/warpzone/util_server.qh File Reference
util_server.qh File Reference
Macros
#define LIB_WARPZONE_UTIL_SERVER_H
Functions
float WarpZoneLib_ExactTrigger_Touch ()
float WarpZoneLib_MoveOutOfSolid (entity e)
Macro Definition Documentation
#define LIB_WARPZONE_UTIL_SERVER_H
Definition at line 2 of file util_server.qh.
Function Documentation
float WarpZoneLib_ExactTrigger_Touch ()
Definition at line 789 of file common.qc.
References other, SELFPARAM, and WarpZoneLib_BoxTouchesBrush().
Referenced by WarpZone_Touch().
 {SELFPARAM();
     return !WarpZoneLib_BoxTouchesBrush(other.absmin, other.absmax, this, other);
 }
float WarpZoneLib_MoveOutOfSolid (entity e)
Definition at line 809 of file common.qc.
References MOVE_WORLDONLY, trace_startsolid, vector(), and WarpZoneLib_MoveOutOfSolid_Expand().
Referenced by WarpZone_Teleport().
 {
     vector o, m0, m1;
     o = e.origin;
     traceline(o, o, MOVE_WORLDONLY, e);
     if (trace_startsolid)
         return false;
     tracebox(o, e.mins, e.maxs, o, MOVE_WORLDONLY, e);
     if (!trace_startsolid)
         return true;
     m0 = e.mins;
     m1 = e.maxs;
     e.mins = '0 0 0';
     e.maxs = '0 0 0';
     WarpZoneLib_MoveOutOfSolid_Expand(e, '1 0 0' * m0_x);
     e.mins_x = m0_x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, '1 0 0' * m1_x);
     e.maxs_x = m1_x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, '0 1 0' * m0_y);
     e.mins_y = m0_y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, '0 1 0' * m1_y);
     e.maxs_y = m1_y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, '0 0 1' * m0_z);
     e.mins_z = m0_z;
     WarpZoneLib_MoveOutOfSolid_Expand(e, '0 0 1' * m1_z);
     e.maxs_z = m1_z;
     setorigin(e, e.origin);
     tracebox(e.origin, e.mins, e.maxs, e.origin, MOVE_WORLDONLY, e);
     if (trace_startsolid)
     {
         setorigin(e, o);
         return false;
     }
     return true;
 }