Xonotic: XonoticCampaignList Class Reference
XonoticCampaignList Class Reference
Public Member Functions
ATTRIB (Item, parent, entity)
ATTRIB (Item, tooltip, string)
ATTRIB (XonoticCampaignList, cvarName, string)
ATTRIB (XonoticCampaignList, buttonNext, entity)
ATTRIB (ListBox, src, string)
ATTRIB (XonoticCampaignList, buttonPrev, entity)
ATTRIB (XonoticCampaignList, labelTitle, entity)
virtual void campaignGo ()
virtual void clickListBoxItem ()
virtual void configureListBox ()
virtual void configureXonoticCampaignList ()
virtual void configureXonoticListBox ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void doubleClickListBoxItem ()
virtual void draw ()
virtual void drawListBoxItem ()
virtual void focusedItemChangeNotify ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void getFirstFullyVisibleItemAtScrollPos ()
virtual void getItemAtPos ()
virtual void getItemHeight ()
virtual void getItemStart ()
virtual void getLastFullyVisibleItemAtScrollPos ()
virtual void getTotalHeight ()
virtual void hideNotify ()
virtual void isScrolling ()
virtual void keyDown ()
virtual void keyUp ()
virtual void loadCvars ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void saveCvars ()
virtual void scrollToItem ()
virtual void setFocusedItem ()
virtual void setSelected ()
virtual void showNotify ()
virtual void toString ()
virtual void updateControlTopBottom ()
Public Attributes
float allowFocusSound = 1
float alphaBG = SKINALPHA_LISTBOX_BACKGROUND
float campaignGlob = 0
float campaignIndex = 0
vector checkMarkOrigin = '0 0 0'
vector checkMarkSize = '0 0 0'
vector color = SKINCOLOR_SCROLLBAR_N
vector color2 = SKINCOLOR_SCROLLBAR_S
vector colorBG = SKINCOLOR_LISTBOX_BACKGROUND
vector colorC = SKINCOLOR_SCROLLBAR_C
vector colorF = SKINCOLOR_SCROLLBAR_F
float columnCheckMarkOrigin = 0
float columnCheckMarkSize = 0
float columnNameOrigin = 0
float columnNameSize = 0
float columnPreviewOrigin = 0
float columnPreviewSize = 0
float controlBottom = 0
float controlTop = 0
float controlWidth = 0
vector dragScrollPos = '0 0 0'
float emptyLineHeight = 0.5
float focusable = 1
float focused = 0
int focusedItem = -1
float focusedItemAlpha = 0.3
float fontSize = SKINFONTSIZE_NORMAL
vector itemAbsSize = '0 0 0'
float itemHeight = 0
float lastClickedItem = -1
float lastClickedTime = 0
float mouseMoveOffset = -1
float needScrollToItem = -1
float nItems = 42
vector origin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
vector realFontSize = '0 0 0'
float realUpperMargin1 = 0
float realUpperMargin2 = 0
float rowsPerItem = 10
float scrollbarWidth = SKINWIDTH_SCROLLBAR
float scrollPos = 0
float scrollPosTarget = 0
int selectedItem = 0
bool selectionDoesntMatter = false
vector size = '0 0 0'
string src = SKINGFX_SCROLLBAR
vector tolerance = SKINTOLERANCE_SLIDER
Detailed Description
Definition at line 4 of file campaign.qh.
Member Function Documentation
Item::ATTRIB (Item , parent , entity) inherited
Item::ATTRIB (Item , tooltip , string) inherited
XonoticCampaignList::ATTRIB (XonoticCampaignList , cvarName , string)
XonoticCampaignList::ATTRIB (XonoticCampaignList , buttonNext , entity)
ListBox::ATTRIB (ListBox , src , string) inherited
XonoticCampaignList::ATTRIB (XonoticCampaignList , buttonPrev , entity)
XonoticCampaignList::ATTRIB (XonoticCampaignList , labelTitle , entity)
virtual void XonoticCampaignList::campaignGo () virtual
virtual void ListBox::clickListBoxItem () virtual inherited
Reimplemented in XonoticGametypeList, and XonoticMapList.
virtual void ListBox::configureListBox () virtual inherited
virtual void XonoticCampaignList::configureXonoticCampaignList () virtual
virtual void XonoticListBox::configureXonoticListBox () virtual inherited
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 295 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void XonoticCampaignList::destroy () virtual
Reimplemented from Item.
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 309 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void XonoticCampaignList::doubleClickListBoxItem () virtual
Reimplemented from ListBox.
virtual void XonoticCampaignList::draw () virtual
Reimplemented from ListBox.
virtual void XonoticCampaignList::drawListBoxItem () virtual
Reimplemented from ListBox.
virtual void ListBox::focusedItemChangeNotify () virtual inherited
Reimplemented in XonoticRegisteredSettingsList, XonoticRegisteredSettingsList, XonoticServerList, and XonoticGametypeList.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void ListBox::focusLeave () virtual inherited
Reimplemented from Item.
virtual void ListBox::getFirstFullyVisibleItemAtScrollPos () virtual inherited
virtual void ListBox::getItemAtPos () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getItemHeight () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getItemStart () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getLastFullyVisibleItemAtScrollPos () virtual inherited
virtual void ListBox::getTotalHeight () virtual inherited
Reimplemented in XonoticServerList.
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void ListBox::isScrolling () virtual inherited
virtual void XonoticCampaignList::keyDown () virtual
Reimplemented from ListBox.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void XonoticCampaignList::loadCvars () virtual
virtual void ListBox::mouseDrag () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticPlayList, and XonoticWeaponsList.
virtual void ListBox::mouseMove () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticServerList.
virtual void ListBox::mousePress () virtual inherited
Reimplemented from Item.
virtual void ListBox::mouseRelease () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticCvarList.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticCampaignList::resizeNotify () virtual
Reimplemented from XonoticListBox.
virtual void XonoticCampaignList::saveCvars () virtual
virtual void ListBox::scrollToItem () virtual inherited
virtual void ListBox::setFocusedItem () virtual inherited
virtual void XonoticCampaignList::setSelected () virtual
Reimplemented from ListBox.
void Item::showNotify () virtual inherited
Reimplemented in Container, Slider, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, InputBox, XonoticSoundList, XonoticDamageTextSettings, XonoticStatsList, XonoticPlayerModelSelector, XonoticTab, XonoticCvarList, XonoticKeyBinder, Button, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
Definition at line 56 of file item.qc.
     {}
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void ListBox::updateControlTopBottom () virtual inherited
Member Data Documentation
float ListBox::allowFocusSound = 1 inherited
Definition at line 19 of file listbox.qh.
float XonoticListBox::alphaBG = SKINALPHA_LISTBOX_BACKGROUND inherited
Definition at line 17 of file listbox.qh.
float XonoticCampaignList::campaignGlob = 0
Definition at line 16 of file campaign.qh.
float XonoticCampaignList::campaignIndex = 0
Definition at line 33 of file campaign.qh.
vector XonoticCampaignList::checkMarkOrigin = '0 0 0'
Definition at line 24 of file campaign.qh.
vector XonoticCampaignList::checkMarkSize = '0 0 0'
Definition at line 25 of file campaign.qh.
vector XonoticListBox::color = SKINCOLOR_SCROLLBAR_N inherited
Definition at line 12 of file listbox.qh.
vector XonoticListBox::color2 = SKINCOLOR_SCROLLBAR_S inherited
Definition at line 14 of file listbox.qh.
vector XonoticListBox::colorBG = SKINCOLOR_LISTBOX_BACKGROUND inherited
Definition at line 16 of file listbox.qh.
vector XonoticListBox::colorC = SKINCOLOR_SCROLLBAR_C inherited
Definition at line 15 of file listbox.qh.
vector XonoticListBox::colorF = SKINCOLOR_SCROLLBAR_F inherited
Definition at line 13 of file listbox.qh.
float XonoticCampaignList::columnCheckMarkOrigin = 0
Definition at line 22 of file campaign.qh.
float XonoticCampaignList::columnCheckMarkSize = 0
Definition at line 23 of file campaign.qh.
float XonoticCampaignList::columnNameOrigin = 0
Definition at line 20 of file campaign.qh.
float XonoticCampaignList::columnNameSize = 0
Definition at line 21 of file campaign.qh.
float XonoticCampaignList::columnPreviewOrigin = 0
Definition at line 18 of file campaign.qh.
float XonoticCampaignList::columnPreviewSize = 0
Definition at line 19 of file campaign.qh.
float ListBox::controlBottom = 0 inherited
Definition at line 34 of file listbox.qh.
float ListBox::controlTop = 0 inherited
Definition at line 33 of file listbox.qh.
float ListBox::controlWidth = 0 inherited
Definition at line 35 of file listbox.qh.
vector ListBox::dragScrollPos = '0 0 0' inherited
Definition at line 36 of file listbox.qh.
float XonoticCampaignList::emptyLineHeight = 0.5
Definition at line 31 of file campaign.qh.
float ListBox::focusable = 1 inherited
Definition at line 14 of file listbox.qh.
float Item::focused = 0 inherited
Definition at line 24 of file item.qh.
int ListBox::focusedItem = -1 inherited
Definition at line 15 of file listbox.qh.
float ListBox::focusedItemAlpha = 0.3 inherited
Definition at line 16 of file listbox.qh.
float XonoticListBox::fontSize = SKINFONTSIZE_NORMAL inherited
Definition at line 6 of file listbox.qh.
vector XonoticCampaignList::itemAbsSize = '0 0 0'
Definition at line 30 of file campaign.qh.
float ListBox::itemHeight = 0 inherited
Definition at line 47 of file listbox.qh.
float ListBox::lastClickedItem = -1 inherited
Definition at line 52 of file listbox.qh.
float ListBox::lastClickedTime = 0 inherited
Definition at line 53 of file listbox.qh.
float ListBox::mouseMoveOffset = -1 inherited
Definition at line 18 of file listbox.qh.
float ListBox::needScrollToItem = -1 inherited
Definition at line 26 of file listbox.qh.
float ListBox::nItems = 42 inherited
Definition at line 46 of file listbox.qh.
vector XonoticCampaignList::origin = '0 0 0'
Definition at line 29 of file campaign.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float ListBox::pressed = 0 inherited
Definition at line 29 of file listbox.qh.
float ListBox::pressOffset = 0 inherited
Definition at line 30 of file listbox.qh.
float ListBox::previousValue = 0 inherited
Definition at line 28 of file listbox.qh.
vector XonoticCampaignList::realFontSize = '0 0 0'
Definition at line 17 of file campaign.qh.
float XonoticCampaignList::realUpperMargin1 = 0
Definition at line 26 of file campaign.qh.
float XonoticCampaignList::realUpperMargin2 = 0
Definition at line 27 of file campaign.qh.
float XonoticCampaignList::rowsPerItem = 10
Definition at line 6 of file campaign.qh.
float XonoticListBox::scrollbarWidth = SKINWIDTH_SCROLLBAR inherited
Definition at line 7 of file listbox.qh.
float ListBox::scrollPos = 0 inherited
Definition at line 23 of file listbox.qh.
float ListBox::scrollPosTarget = 0 inherited
Definition at line 24 of file listbox.qh.
int ListBox::selectedItem = 0 inherited
Definition at line 20 of file listbox.qh.
bool ListBox::selectionDoesntMatter = false inherited
Definition at line 37 of file listbox.qh.
vector ListBox::size = '0 0 0' inherited
Definition at line 21 of file listbox.qh.
string XonoticListBox::src = SKINGFX_SCROLLBAR inherited
Definition at line 8 of file listbox.qh.
vector XonoticListBox::tolerance = SKINTOLERANCE_SLIDER inherited
Definition at line 9 of file listbox.qh.
The documentation for this class was generated from the following file:
menu/xonotic/campaign.qh