Xonotic: server/resources.qc File Reference
resources.qc File Reference
Source file that contains implementation of the resource system.
#include "resources.qh"
#include "autocvars.qh"
#include "miscfunctions.qh"
Functions
float GetResource (entity e, int res_type)
Returns the current amount of resource the given entity has.
float GetResourceField (int res_type)
Converts resource type (a RES_* constant) to entity field.
float GetResourceLimit (entity e, int res_type)
Returns the maximum amount of the given resource.
int GetResourceType (.float res_field)
Converts an entity field to resource type.
void GiveResource (entity receiver, int res_type, float amount)
Gives an entity some resource.
void GiveResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
void SetResource (entity e, int res_type, float amount)
Sets the current amount of resource the given entity will have.
bool SetResourceExplicit (entity e, int res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
void TakeResource (entity receiver, int res_type, float amount)
Takes an entity some resource.
void TakeResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Detailed Description
Source file that contains implementation of the resource system.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file resources.qc.
Function Documentation
float GetResource (entity e, int res_type)
Returns the current amount of resource the given entity has.
Parameters
[in] e Entity to check.
[in] res_type Type of the resource (a RES_* constant).
Returns
Current amount of resource the given entity has.
Definition at line 74 of file resources.qc.
 {
     return e.(GetResourceField(res_type));
 }
float GetResourceField (int res_type)
Converts resource type (a RES_* constant) to entity field.
Parameters
[in] res_type Type of the resource.
Returns
Entity field for that resource.
Definition at line 250 of file resources.qc.
References ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, ammo_shells, armorvalue, error, health, RES_ARMOR, RES_BULLETS, RES_CELLS, RES_FUEL, RES_HEALTH, RES_PLASMA, RES_ROCKETS, and RES_SHELLS.
 {
     switch (res_type)
     {
         case RES_HEALTH: { return health; }
         case RES_ARMOR: { return armorvalue; }
         case RES_SHELLS: { return ammo_shells; }
         case RES_BULLETS: { return ammo_nails; }
         case RES_ROCKETS: { return ammo_rockets; }
         case RES_CELLS: { return ammo_cells; }
         case RES_PLASMA: { return ammo_plasma; }
         case RES_FUEL: { return ammo_fuel; }
     }
     error("GetResourceField: Invalid resource type.");
     return health;
 }
float GetResourceLimit (entity e, int res_type)
Returns the maximum amount of the given resource.
Parameters
[in] e Entity to check.
[in] res_type Type of the resource (a RES_* constant).
Returns
Maximum amount of the given resource.
Definition at line 11 of file resources.qc.
References autocvar_g_balance_armor_limit, autocvar_g_balance_fuel_limit, autocvar_g_balance_health_limit, error, g_pickup_cells_max, g_pickup_nails_max, g_pickup_plasma_max, g_pickup_rockets_max, g_pickup_shells_max, GetResourceLimit(), IS_PLAYER, M_ARGV, MUTATOR_CALLHOOK, RES_AMOUNT_HARD_LIMIT, RES_ARMOR, RES_BULLETS, RES_CELLS, RES_FUEL, RES_HEALTH, RES_LIMIT_NONE, RES_PLASMA, RES_ROCKETS, and RES_SHELLS.
Referenced by GetResourceLimit(), player_regen(), and SetResource().
 {
     if(!IS_PLAYER(e))
         return RES_LIMIT_NONE; // no limits on non-players
     float limit;
     switch (res_type)
     {
         case RES_HEALTH:
         {
             limit = autocvar_g_balance_health_limit;
             break;
         }
         case RES_ARMOR:
         {
             limit = autocvar_g_balance_armor_limit;
             break;
         }
         case RES_SHELLS:
         {
             limit = g_pickup_shells_max;
             break;
         }
         case RES_BULLETS:
         {
             limit = g_pickup_nails_max;
             break;
         }
         case RES_ROCKETS:
         {
             limit = g_pickup_rockets_max;
             break;
         }
         case RES_CELLS:
         {
             limit = g_pickup_cells_max;
             break;
         }
         case RES_PLASMA:
         {
             limit = g_pickup_plasma_max;
             break;
         }
         case RES_FUEL:
         {
             limit = autocvar_g_balance_fuel_limit;
             break;
         }
         default:
         {
             error("GetResourceLimit: Invalid resource type.");
             return 0;
         }
     }
     MUTATOR_CALLHOOK(GetResourceLimit, e, res_type, limit);
     limit = M_ARGV(2, float);
     if (limit > RES_AMOUNT_HARD_LIMIT)
     {
         limit = RES_AMOUNT_HARD_LIMIT;
     }
     return limit;
 }
int GetResourceType (.float res_field)
Converts an entity field to resource type.
Parameters
[in] res_field Entity field to convert.
Returns
Resource type (a RES_* constant).
Definition at line 233 of file resources.qc.
References ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, ammo_shells, armorvalue, error, health, RES_ARMOR, RES_BULLETS, RES_CELLS, RES_FUEL, RES_HEALTH, RES_PLASMA, RES_ROCKETS, and RES_SHELLS.
 {
     switch (res_field)
     {
         case health: { return RES_HEALTH; }
         case armorvalue: { return RES_ARMOR; }
         case ammo_shells: { return RES_SHELLS; }
         case ammo_nails: { return RES_BULLETS; }
         case ammo_rockets: { return RES_ROCKETS; }
         case ammo_cells: { return RES_CELLS; }
         case ammo_plasma: { return RES_PLASMA; }
         case ammo_fuel: { return RES_FUEL; }
     }
     error("GetResourceType: Invalid field.");
     return 0;
 }
void GiveResource (entity receiver, int res_type, float amount)
Gives an entity some resource.
Parameters
[in,out] receiver Entity to give resource to.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to give.
Returns
No return.
Definition at line 118 of file resources.qc.
References autocvar_g_balance_pause_armor_rot, autocvar_g_balance_pause_fuel_rot, autocvar_g_balance_pause_health_rot, GetResource(), GiveResource(), M_ARGV, max(), MUTATOR_CALLHOOK, RES_ARMOR, RES_FUEL, RES_HEALTH, SetResource(), and time.
Referenced by GiveResource(), GiveResourceWithLimit(), Monster_Miniboss_Check(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), ons_ControlPoint_Icon_BuildThink(), and W_ThrowNewWeapon().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResource, receiver, res_type, amount);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     if (amount <= 0)
     {
         return;
     }
     SetResource(receiver, res_type, GetResource(receiver, res_type) + amount);
     switch (res_type)
     {
         case RES_HEALTH:
         {
             receiver.pauserothealth_finished =
                 max(receiver.pauserothealth_finished, time +
                 autocvar_g_balance_pause_health_rot);
             return;
         }
         case RES_ARMOR:
         {
             receiver.pauserotarmor_finished =
                 max(receiver.pauserotarmor_finished, time +
                 autocvar_g_balance_pause_armor_rot);
             return;
         }
         case RES_FUEL:
         {
             receiver.pauserotfuel_finished = max(receiver.pauserotfuel_finished,
                 time + autocvar_g_balance_pause_fuel_rot);
             return;
         }
     }
 }
void GiveResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
Parameters
[in,out] receiver Entity to give resource to.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to give.
[in] limit Limit of resources to give.
Returns
No return.
Definition at line 161 of file resources.qc.
References GetResource(), GiveResource(), GiveResourceWithLimit(), M_ARGV, MUTATOR_CALLHOOK, and RES_LIMIT_NONE.
Referenced by destructible_heal(), GiveResourceWithLimit(), Monster_Heal(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Icon_Heal(), ons_ControlPoint_Icon_Think(), ons_GeneratorHeal(), PlayerHeal(), and vehicles_heal().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResourceWithLimit, receiver, res_type, amount, limit);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     limit = M_ARGV(3, float);
     if (amount <= 0)
     {
         return;
     }
     float current_amount = GetResource(receiver, res_type);
     if (current_amount + amount > limit && limit != RES_LIMIT_NONE)
     {
         amount = limit - current_amount;
     }
     GiveResource(receiver, res_type, amount);
 }
void SetResource (entity e, int res_type, float amount)
Sets the current amount of resource the given entity will have.
Sets the current amount of resource the given entity will have but limited to the max amount allowed for the resource type.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
No return.
Definition at line 90 of file resources.qc.
References GetResourceLimit(), M_ARGV, MUTATOR_CALLHOOK, RES_LIMIT_NONE, SetResource(), and SetResourceExplicit().
 {
     bool forbid = MUTATOR_CALLHOOK(SetResource, e, res_type, amount);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     float max_amount = GetResourceLimit(e, res_type); // TODO: should allow overriding these limits if cheats are enabled!
     float amount_wasted = 0;
     if (amount > max_amount && max_amount != RES_LIMIT_NONE)
     {
         amount_wasted = amount - max_amount;
         amount = max_amount;
     }
     bool changed = SetResourceExplicit(e, res_type, amount);
     if (changed)
     {
         MUTATOR_CALLHOOK(ResourceAmountChanged, e, res_type, amount);
     }
     if (amount_wasted == 0)
     {
         return;
     }
     MUTATOR_CALLHOOK(ResourceWasted, e, res_type, amount_wasted);
 }
bool SetResourceExplicit (entity e, int res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
Boolean for whether the ammo amount was changed
Definition at line 79 of file resources.qc.
References GetResourceField().
 {
     .float res_field = GetResourceField(res_type);
     if (e.(res_field) != amount)
     {
         e.(res_field) = amount;
         return true;
     }
     return false;
 }
void TakeResource (entity receiver, int res_type, float amount)
Takes an entity some resource.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
Returns
No return.
Definition at line 187 of file resources.qc.
References GetResource(), M_ARGV, MUTATOR_CALLHOOK, SetResource(), and TakeResource().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(TakeResource, receiver, res_type, amount);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     if (amount <= 0)
     {
         return;
     }
     SetResource(receiver, res_type, GetResource(receiver, res_type) - amount);
 }
void TakeResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
[in] limit Limit of resources to take.
Returns
No return.
Definition at line 207 of file resources.qc.
References GetResource(), M_ARGV, MUTATOR_CALLHOOK, TakeResource(), and TakeResourceWithLimit().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(TakeResourceWithLimit, receiver, res_type, amount, limit);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     limit = M_ARGV(3, float);
     if (amount <= 0)
     {
         return;
     }
     float current_amount = GetResource(receiver, res_type);
     if (current_amount - amount < -limit)
     {
         amount = -limit + current_amount;
     }
     TakeResource(receiver, res_type, amount);
 }