Xonotic: common/minigames/minigame/c4.qc File Reference
c4.qc File Reference
#include "c4.qh"
Functions
entity c4_find_piece (entity minig, string tile)
string c4_get_lowest_tile (entity minigame, string s)
void c4_move (entity minigame, entity player, string pos)
bool c4_valid_tile (string tile)
bool c4_winning_piece (entity piece)
REGISTER_MINIGAME (c4, _("Connect Four"))
Variables
const int C4_LET_CNT = 7
const int C4_MAX_TILES = 42
int c4_nexteam
int c4_npieces
const int C4_NUM_CNT = 6
const int C4_TEAMS = 2
const int C4_TILE_SIZE = 8
const float C4_TURN_DRAW = 0x0400
const float C4_TURN_PLACE = 0x0100
const float C4_TURN_TEAM = 0x000f
const float C4_TURN_TEAM1 = 0x0001
const float C4_TURN_TEAM2 = 0x0002
const float C4_TURN_WIN = 0x0200
const int C4_WIN_CNT = 4
Function Documentation
entity c4_find_piece (entity minig, string tile)
Definition at line 26 of file c4.qc.
References entity(), findentity(), NULL, and owner.
Referenced by c4_get_lowest_tile(), c4_move(), and c4_winning_piece().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile )
             return e;
     return NULL;
 }
string c4_get_lowest_tile (entity minigame, string s)
Definition at line 139 of file c4.qc.
References c4_find_piece(), minigame_tile_buildname(), and minigame_tile_letter().
Referenced by c4_move().
 {
     int i;
     int end = 0;
     for(i = C4_NUM_CNT; i >= 0; --i)
     {
         if(!c4_find_piece(minigame,minigame_tile_buildname(minigame_tile_letter(s), i)))
         if(c4_find_piece(minigame,minigame_tile_buildname(minigame_tile_letter(s), i - 1)))
         {
             end = i;
             break;
         }
     }
     return minigame_tile_buildname(minigame_tile_letter(s), end);
 }
void c4_move (entity minigame, entity player, string pos)
Definition at line 156 of file c4.qc.
References active_minigame, argv(), c4_find_piece(), c4_get_lowest_tile(), C4_TURN_DRAW, C4_TURN_TEAM1, c4_valid_tile(), c4_winning_piece(), drawfill(), DRAWFLAG_ADDITIVE, DRAWFLAG_NORMAL, drawpic(), entity(), eX, eY, findentity(), FOREACH_MINIGAME_ENTITY, ftos(), hud_fontsize, HUD_Panel_DrawBg, int, K_ENTER, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, K_SPACE, MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_cmd, minigame_count_players(), minigame_drawcolorcodedstring_trunc(), minigame_drawcolorcodedstring_wrapped(), minigame_drawpic_centered(), minigame_drawstring_wrapped(), minigame_hud_denormalize(), minigame_hud_denormalize_size(), minigame_hud_fitsqare, minigame_hud_normalize(), minigame_hud_simpleboard(), minigame_next_team(), minigame_prompt(), minigame_relative_tile(), minigame_self, minigame_server_sendflags(), minigame_texture(), minigame_tile_name(), minigame_tile_pos(), mousepos, msle_spawn(), NULL, owner, panel_fg_alpha, strcat(), strcpy, strfree, string_null, strzone(), and vector().
 {
     pos = c4_get_lowest_tile(minigame, pos);
     if ( minigame.minigame_flags & C4_TURN_PLACE )
     if ( pos && player.team == (minigame.minigame_flags & C4_TURN_TEAM) )
     {
         if ( c4_valid_tile(pos) )
         if ( !c4_find_piece(minigame,pos) )
         {
             entity piece = msle_spawn(minigame,"minigame_board_piece");
             piece.team = player.team;
             piece.netname = strzone(pos);
             minigame_server_sendflags(piece,MINIG_SF_ALL);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
             minigame.c4_npieces++;
             minigame.c4_nexteam = minigame_next_team(player.team,C4_TEAMS);
             if ( c4_winning_piece(piece) )
             {
                 minigame.minigame_flags = C4_TURN_WIN | player.team;
             }
             else if ( minigame.c4_npieces >= C4_MAX_TILES )
                 minigame.minigame_flags = C4_TURN_DRAW;
             else
                 minigame.minigame_flags = C4_TURN_PLACE | minigame.c4_nexteam;
         }
     }
 }
bool c4_valid_tile (string tile)
Definition at line 130 of file c4.qc.
References C4_LET_CNT, minigame_tile_letter(), and minigame_tile_number().
Referenced by c4_move().
 {
     if ( !tile )
         return false;
     float number = minigame_tile_number(tile);
     float letter = minigame_tile_letter(tile);
     return 0 <= number && number < C4_NUM_CNT && 0 <= letter && letter < C4_LET_CNT;
 }
bool c4_winning_piece (entity piece)
Definition at line 36 of file c4.qc.
References c4_find_piece(), C4_NUM_CNT, entity(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), p, and team.
Referenced by c4_move().
 {
     int number = minigame_tile_number(piece.netname);
     int letter = minigame_tile_letter(piece.netname);
     int i;
     entity top = piece;
     entity left = piece;
     entity topleft = piece;
     entity botleft = piece;
     for(i = number; i < C4_NUM_CNT; ++i)
     {
         entity p = c4_find_piece(piece.owner,minigame_tile_buildname(letter, i));
         if(p.team == piece.team)
             top = p;
         else break;
     }
     for(i = letter; i >= 0; --i)
     {
         entity p = c4_find_piece(piece.owner,minigame_tile_buildname(i, number));
         if(p.team == piece.team)
             left = p;
         else break;
     }
     int j;
     for(i = letter, j = number; i >= 0, j >= 0; --i, --j)
     {
         entity p = c4_find_piece(piece.owner,minigame_tile_buildname(i, j));
         if(p.team == piece.team)
             botleft = p;
         else break;
     }
     for(i = letter, j = number; i >= 0, j < C4_NUM_CNT; --i, ++j)
     {
         entity p = c4_find_piece(piece.owner,minigame_tile_buildname(i, j));
         if(p.team == piece.team)
             topleft = p;
         else break;
     }
     // down
     int found = 0;
     for(i = minigame_tile_number(top.netname); i >= 0; --i)
     {
         if(c4_find_piece(piece.owner,minigame_tile_buildname(letter, i)).team == piece.team)
             ++found;
         else break;
     }
     if(found >= C4_WIN_CNT)
         return true;
     // right
     found = 0;
     for(i = minigame_tile_letter(left.netname); i < C4_LET_CNT; ++i)
     {
         if(c4_find_piece(piece.owner,minigame_tile_buildname(i, number)).team == piece.team)
             ++found;
         else break;
     }
     if(found >= C4_WIN_CNT)
         return true;
     // diagright down
     found = 0;
     for(i = minigame_tile_letter(topleft.netname), j = minigame_tile_number(topleft.netname); i < C4_LET_CNT, j >= 0; ++i, --j)
     {
         if(c4_find_piece(piece.owner,minigame_tile_buildname(i, j)).team == piece.team)
             ++found;
         else break;
     }
     if(found >= C4_WIN_CNT)
         return true;
     // diagright up
     found = 0;
     for(i = minigame_tile_letter(botleft.netname), j = minigame_tile_number(botleft.netname); i < C4_LET_CNT, j < C4_NUM_CNT; ++i, ++j)
     {
         if(c4_find_piece(piece.owner,minigame_tile_buildname(i, j)).team == piece.team)
             ++found;
         else break;
     }
     if(found >= C4_WIN_CNT)
         return true;
     return false;
 }
REGISTER_MINIGAME (c4 , _("Connect Four"))
Variable Documentation
const int C4_LET_CNT = 7
Definition at line 12 of file c4.qc.
Referenced by c4_valid_tile().
const int C4_MAX_TILES = 42
Definition at line 16 of file c4.qc.
int c4_nexteam
Definition at line 23 of file c4.qc.
int c4_npieces
Definition at line 22 of file c4.qc.
const int C4_NUM_CNT = 6
Definition at line 13 of file c4.qc.
Referenced by c4_winning_piece().
const int C4_TEAMS = 2
Definition at line 20 of file c4.qc.
const int C4_TILE_SIZE = 8
Definition at line 18 of file c4.qc.
const float C4_TURN_DRAW = 0x0400
Definition at line 6 of file c4.qc.
Referenced by c4_move().
const float C4_TURN_PLACE = 0x0100
Definition at line 4 of file c4.qc.
const float C4_TURN_TEAM = 0x000f
Definition at line 10 of file c4.qc.
const float C4_TURN_TEAM1 = 0x0001
Definition at line 8 of file c4.qc.
Referenced by c4_move().
const float C4_TURN_TEAM2 = 0x0002
Definition at line 9 of file c4.qc.
const float C4_TURN_WIN = 0x0200
Definition at line 5 of file c4.qc.
const int C4_WIN_CNT = 4
Definition at line 14 of file c4.qc.