Xonotic: lib/test.qh File Reference
test.qh File Reference
Macros
#define _TEST_ASSERT(statement)
#define ADD_FAILURE(msg) MACRO_BEGIN { ++TEST_failed; LOG_WARN(msg); } MACRO_END
Add a failure, but continue.
#define ASSERT_EQ(expected, actual) _TEST_ASSERT(EXPECT_EQ(expected, actual))
#define ASSERT_FALSE(condition) ASSERT_EQ(false, condition)
#define ASSERT_GE(val1, val2) _TEST_ASSERT(EXPECT_GE(val1, val2))
#define ASSERT_GT(val1, val2) _TEST_ASSERT(EXPECT_GT(val1, val2))
#define ASSERT_LE(val1, val2) _TEST_ASSERT(EXPECT_LE(val1, val2))
#define ASSERT_LT(val1, val2) _TEST_ASSERT(EXPECT_LT(val1, val2))
#define ASSERT_NE(val1, val2) _TEST_ASSERT(EXPECT_NE(val1, val2))
#define ASSERT_NO_FATAL_FAILURE(statement) EXPECT_NO_FATAL_FAILURE_(statement, { ++TEST_fatal; return; })
#define ASSERT_TRUE(condition) ASSERT_EQ(true, condition)
#define EXPECT_EQ(expected_, actual_)
#define EXPECT_FALSE(condition) EXPECT_EQ(false, condition)
#define EXPECT_GE(val1, val2) EXPECT_TRUE((val1) >= (val2))
#define EXPECT_GT(val1, val2) EXPECT_TRUE((val1) > (val2))
#define EXPECT_LE(val1, val2) EXPECT_TRUE((val1) <= (val2))
#define EXPECT_LT(val1, val2) EXPECT_TRUE((val1) < (val2))
#define EXPECT_NE(val1, val2) EXPECT_TRUE((val1) != (val2))
#define EXPECT_NO_FATAL_FAILURE(statement) EXPECT_NO_FATAL_FAILURE_(statement, { })
#define EXPECT_NO_FATAL_FAILURE_(statement, then)
#define EXPECT_NO_FATAL_FAILURE__(statement, then)
#define EXPECT_TRUE(condition) EXPECT_EQ(true, condition)
#define FAIL(msg) _TEST_ASSERT(ADD_FAILURE(msg))
Add a failure and return.
#define HasFatalFailure() (TEST_fatal > 0)
#define SUCCEED() (TEST_ok = true)
Must be present at the end of a test.
#define TEST(suite, test)
Use UpperCamelCase for suite and test only.
Functions
bool RUN_ALL_TESTS ()
bool TEST_Run (string test)
Variables
int TEST_failed
int TEST_fatal
bool TEST_ok
Macro Definition Documentation
#define _TEST_ASSERT (statement)
Value:
MACRO_BEGIN { \
        LAMBDA(statement); \
        ++TEST_fatal; return; \
    } MACRO_END
Definition at line 74 of file test.qh.
#define ADD_FAILURE (msg) MACRO_BEGIN { ++TEST_failed; LOG_WARN(msg); } MACRO_END
Add a failure, but continue.
Definition at line 18 of file test.qh.
#define ASSERT_EQ (expected, actual) _TEST_ASSERT(EXPECT_EQ(expected, actual))
Definition at line 41 of file test.qh.
#define ASSERT_FALSE (condition) ASSERT_EQ(false, condition)
Definition at line 47 of file test.qh.
#define ASSERT_GE (val1, val2) _TEST_ASSERT(EXPECT_GE(val1, val2))
Definition at line 62 of file test.qh.
#define ASSERT_GT (val1, val2) _TEST_ASSERT(EXPECT_GT(val1, val2))
Definition at line 59 of file test.qh.
#define ASSERT_LE (val1, val2) _TEST_ASSERT(EXPECT_LE(val1, val2))
Definition at line 56 of file test.qh.
#define ASSERT_LT (val1, val2) _TEST_ASSERT(EXPECT_LT(val1, val2))
Definition at line 53 of file test.qh.
#define ASSERT_NE (val1, val2) _TEST_ASSERT(EXPECT_NE(val1, val2))
Definition at line 50 of file test.qh.
#define ASSERT_NO_FATAL_FAILURE (statement) EXPECT_NO_FATAL_FAILURE_(statement, { ++TEST_fatal; return; })
Definition at line 65 of file test.qh.
#define ASSERT_TRUE (condition) ASSERT_EQ(true, condition)
Definition at line 44 of file test.qh.
#define EXPECT_EQ (expected_, actual_)
Value:
MACRO_BEGIN { \
    int expected = expected_; \
    int actual = actual_; \
    if ((expected) != (actual)) { \
        ADD_FAILURE(sprintf( \
            "Value of: " #actual_ "\n" \
            "  Actual: %d\n" \
            "Expected: %d\n", \
            actual, expected \
        )); \
    } \
} MACRO_END
Definition at line 29 of file test.qh.
Referenced by TEST().
#define EXPECT_FALSE (condition) EXPECT_EQ(false, condition)
Definition at line 46 of file test.qh.
#define EXPECT_GE (val1, val2) EXPECT_TRUE((val1) >= (val2))
Definition at line 61 of file test.qh.
#define EXPECT_GT (val1, val2) EXPECT_TRUE((val1) > (val2))
Definition at line 58 of file test.qh.
Referenced by TEST().
#define EXPECT_LE (val1, val2) EXPECT_TRUE((val1) <= (val2))
Definition at line 55 of file test.qh.
#define EXPECT_LT (val1, val2) EXPECT_TRUE((val1) < (val2))
Definition at line 52 of file test.qh.
#define EXPECT_NE (val1, val2) EXPECT_TRUE((val1) != (val2))
Definition at line 49 of file test.qh.
Referenced by MX_Messages_(), MX_Sync_(), TEST(), and test_weapons_hurt().
#define EXPECT_NO_FATAL_FAILURE (statement) EXPECT_NO_FATAL_FAILURE_(statement, { })
Definition at line 64 of file test.qh.
#define EXPECT_NO_FATAL_FAILURE_ (statement, then)
Value:
EXPECT_NO_FATAL_FAILURE__(statement, { \
        LOG_WARNF( \
            "  Actual: %d fatal failures\n" \
            "Expected: no fatal failures\n", \
            TEST_fatal - TEST_prevfatal \
        ); \
        LAMBDA(then); \
    })
Definition at line 88 of file test.qh.
#define EXPECT_NO_FATAL_FAILURE__ (statement, then)
Value:
MACRO_BEGIN { \
        int TEST_prevfatal = TEST_fatal; \
        LAMBDA(statement); \
        if (TEST_fatal != TEST_prevfatal) \
            LAMBDA(then); \
    } MACRO_END
Definition at line 80 of file test.qh.
#define EXPECT_TRUE (condition) EXPECT_EQ(true, condition)
Definition at line 43 of file test.qh.
#define FAIL (msg) _TEST_ASSERT(ADD_FAILURE(msg))
Add a failure and return.
Definition at line 21 of file test.qh.
#define HasFatalFailure () (TEST_fatal > 0)
Definition at line 23 of file test.qh.
#define SUCCEED () (TEST_ok = true)
Must be present at the end of a test.
Definition at line 15 of file test.qh.
Referenced by TEST().
#define TEST (suite, test)
Value:
void _TEST_##suite##_##test(); \
    ACCUMULATE int TEST_RunAll_accumulated(int f) { \
        if (!TEST_Run(#suite "_" #test)) ++f; \
        return = f; \
    } \
    void _TEST_##suite##_##test()
Use UpperCamelCase for suite and test only.
Definition at line 6 of file test.qh.
Function Documentation
bool RUN_ALL_TESTS ()
Definition at line 4 of file test.qc.
References LOG_INFO, LOG_INFOF, and TEST_RunAll_accumulated().
Referenced by GenericCommand_runtest().
 {
     int f = TEST_RunAll_accumulated(0);
     if (f)
     {
         LOG_INFOF("%d tests failed", f);
         return true;
     }
     else
     {
         LOG_INFO("All tests OK");
         return false;
     }
 }
bool TEST_Run (string test)
Definition at line 19 of file test.qc.
References callfunction(), isfunction(), LOG_INFOF, strcat(), TEST_failed, TEST_fatal, and TEST_ok.
Referenced by GenericCommand_runtest().
 {
     LOG_INFOF("%s: testing...", s);
     TEST_failed = 0;
     TEST_fatal = 0;
     TEST_ok = false;
     string fn = strcat("_TEST_", s);
     if (isfunction(fn)) callfunction(fn);
     if (TEST_failed > 0)
     {
         LOG_INFOF("%s: %d items failed.", s, TEST_failed);
         return false;
     }
     else if (!TEST_ok)
     {
         LOG_INFOF("%s: did not complete.", s);
         return false;
     }
     return true;
 }
Variable Documentation
int TEST_failed
Definition at line 72 of file test.qh.
Referenced by TEST_Run().
int TEST_fatal
Definition at line 70 of file test.qh.
Referenced by TEST_Run().
bool TEST_ok
Definition at line 71 of file test.qh.
Referenced by TEST_Run().