Xonotic: common/mutators/mutator/status_effects/sv_status_effects.qc File Reference
sv_status_effects.qc File Reference
#include "sv_status_effects.qh"
Functions
MUTATOR_HOOKFUNCTION (status_effects, SV_StartFrame)
MUTATOR_HOOKFUNCTION (status_effects, PlayerDies)
MUTATOR_HOOKFUNCTION (status_effects, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (status_effects, reset_map_global)
MUTATOR_HOOKFUNCTION (status_effects, SpectateCopy)
MUTATOR_HOOKFUNCTION (status_effects, PutClientInServer)
Function Documentation
MUTATOR_HOOKFUNCTION() [1/6]
MUTATOR_HOOKFUNCTION (status_effects , SV_StartFrame)
Definition at line 53 of file sv_status_effects.qc.
References g_damagedbycontents, and IL_EACH.
 {
     if(game_stopped)
         return;
     // TODO: explicitly only loop through entities with a valid statuseffects object
     // NOTE: due to the way vehicles work currently, this does not function correctly! effect does not tick while inside a vehicle
     IL_EACH(g_damagedbycontents, it.damagedbycontents,
     {
         if (it.move_movetype == MOVETYPE_NOCLIP || !it.statuseffects) continue;
         StatusEffects_tick(it);
     });
 }
MUTATOR_HOOKFUNCTION() [2/6]
MUTATOR_HOOKFUNCTION (status_effects , PlayerDies)
Definition at line 66 of file sv_status_effects.qc.
References entity(), M_ARGV, and STATUSEFFECT_REMOVE_NORMAL.
 {
     entity frag_target = M_ARGV(2, entity);
     StatusEffects_removeall(frag_target, STATUSEFFECT_REMOVE_NORMAL);
 }
MUTATOR_HOOKFUNCTION() [3/6]
MUTATOR_HOOKFUNCTION (status_effects , MakePlayerObserver)
Definition at line 73 of file sv_status_effects.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // no need to network updates, as there is no statuseffects object attached
     StatusEffects_clearall(player.statuseffects_store);
     // don't delete spectatee's effects!
     if(player.statuseffects && player.statuseffects.owner == player)
         StatusEffects_delete(player);
 }
MUTATOR_HOOKFUNCTION() [4/6]
MUTATOR_HOOKFUNCTION (status_effects , reset_map_global)
Definition at line 85 of file sv_status_effects.qc.
References FOREACH_CLIENT, and IS_PLAYER.
 {
     FOREACH_CLIENT(IS_PLAYER(it) && it.statuseffects,
     {
         StatusEffects_clearall(it.statuseffects);
         StatusEffects_update(it);
     });
     return false;
 }
MUTATOR_HOOKFUNCTION() [5/6]
MUTATOR_HOOKFUNCTION (status_effects , SpectateCopy)
Definition at line 95 of file sv_status_effects.qc.
References entity(), and M_ARGV.
 {
     entity spectatee = M_ARGV(0, entity);
     entity client = M_ARGV(1, entity);
     client.statuseffects = spectatee.statuseffects;
 }
MUTATOR_HOOKFUNCTION() [6/6]
MUTATOR_HOOKFUNCTION (status_effects , PutClientInServer)
Definition at line 103 of file sv_status_effects.qc.
References entity(), M_ARGV, and NULL.
 {
     entity player = M_ARGV(0, entity);
     if(player.statuseffects && player.statuseffects.owner == player)
     {
         StatusEffects_clearall(player.statuseffects);
         StatusEffects_update(player);
     }
     else
     {
         StatusEffects_clearall(player.statuseffects_store);
         player.statuseffects = NULL;
     }
 }