Xonotic: lib/bits.qh File Reference
lib/bits.qh File Reference
#include "log.qh"
Defines
#define BIT(n) (1 << (n))
#define BITS(n) (BIT(n) - 1)
#define BITSET(var, mask, flag) (flag ? (var) | (mask) : (var) & ~(mask))
Enumerations
enum {
OP_SET, OP_MIN, OP_MAX, OP_PLUS,
OP_MINUS
}
Functions
int lowestbit (int f)
int randombit (int bits)
int randombits (int bits, int k, bool error_return)
void randombit_test (int bits, int iter)
bool GiveBit (entity e,.int fld, int bit, int op, int val)
bool GiveValue (entity e,.int fld, int op, int val)
Define Documentation
#define BIT (n) (1 << (n))
Definition at line 5 of file bits.qh.
Referenced by ClientConnect(), CSQCPlayer_SetCamera(), g_clientmodel_genericsendentity(), g_clientmodel_setcolormaptoactivator(), g_model_setcolormaptoactivator(), Nagger_ReadyCounted(), Nagger_SendEntity(), Nagger_VoteChanged(), Nagger_VoteCountChanged(), NET_HANDLE(), snake_eat_team(), spawnfunc(), viewloc_PlayerPhysics(), and WarpZone_PostTeleportPlayer_Callback().
#define BITS (n) (BIT(n) - 1)
Definition at line 6 of file bits.qh.
#define BITSET (var, mask, flag) (flag ? (var) | (mask) : (var) & ~(mask))
Definition at line 8 of file bits.qh.
Referenced by CSQCPlayer_Physics(), CSQCPlayer_SetCamera(), GetPressedKeys(), and Movetype_Physics_Spam().
Enumeration Type Documentation
anonymous enum
Enumerator:
OP_SET
OP_MIN
OP_MAX
OP_PLUS
OP_MINUS
Definition at line 68 of file bits.qh.
     {
    OP_SET,
    OP_MIN,
    OP_MAX,
    OP_PLUS,
    OP_MINUS
};
Function Documentation
bool GiveBit (entity e, .int fld, int bit, int op, int val)
Definition at line 76 of file bits.qh.
References OP_MAX, OP_MIN, OP_MINUS, OP_PLUS, and OP_SET.
{
    int v0 = (e.(fld) & bit);
    switch (op)
    {
        case OP_SET:
            if (val > 0) e.(fld) |= bit;
            else e.(fld) &= ~bit;
            break;
        case OP_MIN:
        case OP_PLUS:
            if (val > 0) e.(fld) |= bit;
            break;
        case OP_MAX:
            if (val <= 0) e.(fld) &= ~bit;
            break;
        case OP_MINUS:
            if (val > 0) e.(fld) &= ~bit;
            break;
    }
    int v1 = (e.(fld) & bit);
    return v0 != v1;
}
bool GiveValue (entity e, .int fld, int op, int val)
Definition at line 100 of file bits.qh.
References max(), min(), OP_MAX, OP_MIN, OP_MINUS, OP_PLUS, and OP_SET.
{
    int v0 = e.(fld);
    switch (op)
    {
        case OP_SET:
            e.(fld) = val;
            break;
        case OP_MIN:
            e.(fld) = max(e.(fld), val);  // min 100 cells = at least 100 cells
            break;
        case OP_MAX:
            e.(fld) = min(e.(fld), val);
            break;
        case OP_PLUS:
            e.(fld) += val;
            break;
        case OP_MINUS:
            e.(fld) -= val;
            break;
    }
    int v1 = e.(fld);
    return v0 != v1;
}
int lowestbit (int f)
Definition at line 13 of file bits.qh.
Referenced by item_keys_keylist(), and spawnfunc().
{
    f &= ~(f << 1);
    f &= ~(f << 2);
    f &= ~(f << 4);
    f &= ~(f << 8);
    f &= ~(f << 16);
    return f;
}
int randombit (int bits)
Definition at line 23 of file bits.qh.
References n, and random().
Referenced by randombit_test(), and randombits().
{
    if (!(bits & (bits - 1)))  // this ONLY holds for powers of two!
        return bits;
    int r = random();
    int b = 0;
    int n = 0;
    for (int f = 1; f <= bits; f *= 2)
    {
        if (bits & f)
        {
            ++n;
            r *= n;
            if (r <= 1) b = f;
            else r = (r - 1) / (n - 1);
        }
    }
    return b;
}
void randombit_test (int bits, int iter)
Definition at line 59 of file bits.qh.
References ftos(), LOG_INFO, and randombit().
{
    while (iter > 0)
    {
        LOG_INFO(ftos(randombit(bits)), "\n");
        --iter;
    }
}
int randombits (int bits, int k, bool error_return)
Definition at line 45 of file bits.qh.
References randombit().
{
    int r = 0;
    while (k > 0 && bits != r)
    {
        r += randombit(bits - r);
        --k;
    }
    if (error_return)
        if (k > 0) return -1;
    // all
    return r;
}