Xonotic: lib/bool.qh File Reference
lib/bool.qh File Reference
Defines
#define boolean(value) ((value) != 0)
Functions
float InterpretBoolean (string input)
Variables
const int true = 1
const int false = 0
const bool TRUE
const bool FALSE
Define Documentation
#define boolean (value) ((value) != 0)
Definition at line 13 of file bool.qh.
Referenced by bot_execute_commands_once(), CSQCPlayer_AnimDecide_PostUpdate(), and InterpretBoolean().
Function Documentation
float InterpretBoolean (string input)
Definition at line 16 of file bool.qh.
References boolean, stof(), and strtolower().
Referenced by ClientCommand_autoswitch(), LocalCommand_handlevote(), and LocalCommand_hud().
{
    switch (strtolower(input))
    {
        case "yes":
        case "true":
        case "on":
            return true;
        case "no":
        case "false":
        case "off":
            return false;
        default: return boolean(stof(input));
    }
}
Variable Documentation
const int false = 0
Definition at line 6 of file bool.qh.
const bool FALSE
Definition at line 11 of file bool.qh.
const int true = 1
Definition at line 5 of file bool.qh.
const bool TRUE
Definition at line 10 of file bool.qh.