Xonotic: client/mapvoting.qh File Reference
client/mapvoting.qh File Reference
#include <common/constants.qh>
Defines
#define CLIENT_MAPVOTING_H
Functions
void MapVote_Draw ()
void Cmd_MapVote_MapDownload (float argc)
float MapVote_InputEvent (float bInputType, float nPrimary, float nSecondary)
void Net_MapVote_Picture ()
Variables
float mv_active
Define Documentation
#define CLIENT_MAPVOTING_H
Definition at line 2 of file mapvoting.qh.
Function Documentation
void Cmd_MapVote_MapDownload (float argc)
Definition at line 488 of file mapvoting.qc.
References argv(), entity(), ftos(), localcmd, LOG_INFO, mv_pk3list, mv_preview, PreviewExists(), stof(), and strcat().
Referenced by LocalCommand_mv_download(), and MapVote_CheckPK3().
{
    entity pak;
    if(argc != 2 || !mv_pk3list)
    {
        LOG_INFO(_("mv_mapdownload: ^3You're not supposed to use this command on your own!\n"));
        return;
    }
    int id = stof(argv(1));
    for(pak = mv_pk3list; pak; pak = pak.chain)
        if(pak.sv_entnum == id)
            break;
    if(!pak || pak.sv_entnum != id) {
        LOG_INFO(_("^1Error:^7 Couldn't find pak index.\n"));
        return;
    }
    if(PreviewExists(pak.message))
    {
        mv_preview[id] = true;
        return;
    } else {
        LOG_INFO(_("Requesting preview...\n"));
        localcmd(strcat("\ncmd mv_getpicture ", ftos(id), "\n"));
    }
}
void MapVote_Draw ()
Definition at line 315 of file mapvoting.qc.
References autocvar__menu_alpha, autocvar_hud_cursormode, autocvar_menu_skin, bound(), ceil(), chat_posy, chat_sizey, draw_beginBoldFont, draw_endBoldFont, DRAWFLAG_NORMAL, drawpic(), drawstring(), eX, eY, gametypevote, GameTypeVote_DrawGameTypeItem(), getmousepos(), hud_fontsize, HUD_GetFontsize(), HUD_GetTableSize_BestItemAR(), HUD_Panel_DrawBg, HUD_Panel_UpdateCvars, mapvote_chosenmap, MapVote_DrawAbstain(), MapVote_DrawMapItem(), MapVote_GridVec(), MapVote_Selection(), max(), min(), mv_abstain, mv_active, mv_columns, mv_maps, mv_mousepos, mv_num_maps, mv_pics, mv_preview, mv_selection, mv_selection_keyboard, mv_timeout, mv_top2_alpha, mv_top2_time, mv_votes, panel_bg_border, panel_bg_padding, panel_pos, panel_size, strcat(), stringwidth(), time, vector(), vid_conheight, vid_conwidth, void(), xmax, xmin, ymax, and ymin.
{
    string map;
    int i;
    float tmp;
    vector pos;
    float center;
    float rows;
    vector dist = '0 0 0';
    //if(intermission != 2) return;
    if(!mv_active)
        return;
    if (!autocvar_hud_cursormode)
    {
        vector mpos = mv_mousepos + getmousepos();
        mpos.x = bound(0, mpos.x, vid_conwidth);
        mpos.y = bound(0, mpos.y, vid_conheight);
        if ( mpos.x != mv_mousepos.x || mpos.y != mv_mousepos.y )
            mv_selection_keyboard = 0;
        mv_mousepos = mpos;
    }
    center = (vid_conwidth - 1)/2;
    xmin = vid_conwidth * 0.08;
    xmax = vid_conwidth - xmin;
    ymin = 20;
    ymax = vid_conheight - ymin;
    if(chat_posy + chat_sizey / 2 < vid_conheight / 2)
        ymin += chat_sizey;
    else
        ymax -= chat_sizey;
    hud_fontsize = HUD_GetFontsize("hud_fontsize");
    pos.y = ymin;
    pos.z = 0;
    draw_beginBoldFont();
    map = ((gametypevote) ? _("Decide the gametype") : _("Vote for a map"));
    pos.x = center - stringwidth(map, false, hud_fontsize * 2) * 0.5;
    drawstring(pos, map, hud_fontsize * 2, '1 1 1', 1, DRAWFLAG_NORMAL);
    pos.y += hud_fontsize.y * 2;
    if( mapvote_chosenmap != "" )
    {
        pos.y += hud_fontsize.y * 0.25;
        pos.x = center - stringwidth(mapvote_chosenmap, false, hud_fontsize * 1.5) * 0.5;
        drawstring(pos, mapvote_chosenmap, hud_fontsize * 1.5, '1 1 1', 1, DRAWFLAG_NORMAL);
        pos.y += hud_fontsize.y * 1.5;
        pos.y += hud_fontsize.y * 0.5;
    }
    else
        pos.y += hud_fontsize.y * 0.5;
    draw_endBoldFont();
    i = ceil(max(0, mv_timeout - time));
    map = sprintf(_("%d seconds left"), i);
    pos.x = center - stringwidth(map, false, hud_fontsize * 1.5) * 0.5;
    drawstring(pos, map, hud_fontsize * 1.5, '0 1 0', 1, DRAWFLAG_NORMAL);
    pos.y += hud_fontsize.y * 1.5;
    pos.y += hud_fontsize.y * 0.5;
    HUD_Panel_UpdateCvars();
    // base for multi-column stuff...
    pos.y += hud_fontsize.y;
    pos.x = xmin;
    ymin = pos.y;
    float abstain_spacing = panel_bg_border + hud_fontsize.y;
    if(mv_abstain)
    {
        mv_num_maps -= 1;
        ymax -= abstain_spacing;
    }
    // higher than the image itself ratio for mapvote items to reserve space for long map names
    int item_aspect = (gametypevote) ? 3/1 : 5/3;
    vector table_size = HUD_GetTableSize_BestItemAR(mv_num_maps, eX * (xmax - xmin) + eY * (ymax - ymin), item_aspect);
    mv_columns = table_size.x;
    rows = table_size.y;
    dist.x = (xmax - xmin) / mv_columns;
    dist.y = (ymax - pos.y) / rows;
    // reduce size of too wide items
    tmp = vid_conwidth / 3; // max width
    if(dist.x > tmp)
    {
        dist.x = tmp;
        dist.y = min(dist.y, dist.x / item_aspect);
    }
    tmp = vid_conheight / 3; // max height
    if(dist.y > tmp)
    {
        dist.y = tmp;
        dist.x = min(dist.x, dist.y * item_aspect);
    }
    // reduce size to fix aspect ratio
    if(dist.x / dist.y > item_aspect)
        dist.x = dist.y * item_aspect;
    else
        dist.y = dist.x / item_aspect;
    // adjust table pos and size according to the new size
    float offset;
    offset = ((xmax - pos.x) - dist.x * mv_columns) / 2;
    xmin = pos.x += offset;
    xmax -= offset;
    offset = ((ymax - pos.y) - dist.y * rows) / 2;
    ymax -= 2 * offset;
    // override panel_pos and panel_size
    panel_pos.x = pos.x;
    panel_pos.y = pos.y;
    panel_size.x = xmax - xmin;
    panel_size.y = ymax - ymin;
    HUD_Panel_DrawBg(1);
    if(panel_bg_padding)
    {
        // FIXME item AR gets slightly changed here...
        // it's rather hard to avoid it at this point
        dist.x -= 2 * panel_bg_padding / mv_columns;
        dist.y -= 2 * panel_bg_padding / rows;
        xmin = pos.x += panel_bg_padding;
        ymin = pos.y += panel_bg_padding;
        xmax -= 2 * panel_bg_padding;
        ymax -= 2 * panel_bg_padding;
    }
    mv_selection = MapVote_Selection(pos, dist, rows, mv_columns);
    if (mv_top2_time)
        mv_top2_alpha = max(0.2, 1 - (time - mv_top2_time)*(time - mv_top2_time));
    void (vector, float, float, string, string, float, float) DrawItem;
    if(gametypevote)
        DrawItem = GameTypeVote_DrawGameTypeItem;
    else
        DrawItem = MapVote_DrawMapItem;
    for(i = 0; i < mv_num_maps; ++i)
    {
        tmp = mv_votes[i]; // FTEQCC bug: too many array accesses in the function call screw it up
        map = mv_maps[i];
        if(mv_preview[i])
            DrawItem(pos + MapVote_GridVec(dist, i, mv_columns), dist.y, dist.x, map, mv_pics[i], tmp, i);
        else
            DrawItem(pos + MapVote_GridVec(dist, i, mv_columns), dist.y, dist.x, map, "", tmp, i);
    }
    if(mv_abstain)
        ++mv_num_maps;
    if(mv_abstain && i < mv_num_maps) {
        tmp = mv_votes[i];
        pos.y = ymax + abstain_spacing;
        pos.x = (xmax+xmin)*0.5;
        MapVote_DrawAbstain(pos, dist.x, xmax - xmin, tmp, i);
    }
    drawpic(mv_mousepos, strcat("gfx/menu/", autocvar_menu_skin, "/cursor.tga"), '32 32 0', '1 1 1', 1 - autocvar__menu_alpha, DRAWFLAG_NORMAL);
}
float MapVote_InputEvent (float bInputType, float nPrimary, float nSecondary)
Definition at line 752 of file mapvoting.qc.
References ftos(), K_DOWNARROW, K_ENTER, K_KP_0, K_KP_1, K_KP_2, K_KP_3, K_KP_4, K_KP_5, K_KP_6, K_KP_7, K_KP_8, K_KP_9, K_KP_ENTER, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, K_SPACE, K_UPARROW, localcmd, MapVote_MoveDown(), MapVote_MoveLeft(), MapVote_MoveRight(), MapVote_MoveUp(), MapVote_SendChoice(), min(), mv_active, mv_mouse_selection, mv_mousepos, mv_num_maps, mv_selection, mv_selection_keyboard, and strcat().
Referenced by CSQC_InputEvent().
{
    float imp;
    if (!mv_active)
        return false;
    if(bInputType == 3)
    {
        mv_mousepos.x = nPrimary;
        mv_mousepos.y = nSecondary;
        mv_selection_keyboard = 0;
        return true;
    }
    if (bInputType != 0)
        return false;
    if ('0' <= nPrimary && nPrimary <= '9')
    {
        imp = nPrimary - '0';
        if (imp == 0) imp = 10;
        localcmd(strcat("\nimpulse ", ftos(imp), "\n"));
        return true;
    }
    switch(nPrimary)
    {
        case K_KP_1: localcmd("\nimpulse 1\n"); return true;
        case K_KP_2: localcmd("\nimpulse 2\n"); return true;
        case K_KP_3: localcmd("\nimpulse 3\n"); return true;
        case K_KP_4: localcmd("\nimpulse 4\n"); return true;
        case K_KP_5: localcmd("\nimpulse 5\n"); return true;
        case K_KP_6: localcmd("\nimpulse 6\n"); return true;
        case K_KP_7: localcmd("\nimpulse 7\n"); return true;
        case K_KP_8: localcmd("\nimpulse 8\n"); return true;
        case K_KP_9: localcmd("\nimpulse 9\n"); return true;
        case K_KP_0: localcmd("\nimpulse 10\n"); return true;
        case K_RIGHTARROW:
            mv_selection_keyboard = 1;
            mv_selection = MapVote_MoveRight(mv_selection);
            return true;
        case K_LEFTARROW:
            mv_selection_keyboard = 1;
            mv_selection = MapVote_MoveLeft(mv_selection);
            return true;
        case K_DOWNARROW:
            mv_selection_keyboard = 1;
            mv_selection = MapVote_MoveDown(mv_selection);
            return true;
        case K_UPARROW:
            mv_selection_keyboard = 1;
            mv_selection = MapVote_MoveUp(mv_selection);
            return true;
        case K_KP_ENTER:
        case K_ENTER:
        case K_SPACE:
            if ( mv_selection_keyboard )
                MapVote_SendChoice(mv_selection);
            return true;
    }
    if (nPrimary == K_MOUSE1)
    {
        mv_selection_keyboard = 0;
        mv_selection = mv_mouse_selection;
        if (mv_selection >= 0)
        {
            imp = min(mv_selection + 1, mv_num_maps);
            localcmd(strcat("\nimpulse ", ftos(imp), "\n"));
            return true;
        }
    }
    return false;
}
void Net_MapVote_Picture ()
Definition at line 876 of file mapvoting.qc.
References mv_pics, mv_preview, and strzone().
Referenced by NET_HANDLE().
{
    int type = ReadByte();
    mv_preview[type] = true;
    mv_pics[type] = strzone(ReadPicture());
}
Variable Documentation
float mv_active
Definition at line 13 of file mapvoting.qh.
Referenced by HUD_Minigame_Mouse(), HUD_QuickMenu(), HUD_Radar_InputEvent(), HUD_Radar_Mouse(), HUD_Radar_Show_Maximized(), MapVote_Draw(), MapVote_Init(), MapVote_InputEvent(), QuickMenu_Close(), QuickMenu_InputEvent(), and QuickMenu_Mouse().