Xonotic: client/main.qc File Reference
client/main.qc File Reference
#include "main.qh"
#include <common/effects/qc/all.qh>
#include "hud/all.qh"
#include "mapvoting.qh"
#include "mutators/events.qh"
#include "quickmenu.qh"
#include "scoreboard.qh"
#include "shownames.qh"
#include <common/t_items.qh>
#include "wall.qh"
#include "weapons/projectile.qh"
#include <common/deathtypes/all.qh>
#include <common/items/all.qh>
#include <common/mapinfo.qh>
#include <common/minigames/cl_minigames.qh>
#include <common/minigames/cl_minigames_hud.qh>
#include <common/net_notice.qh>
#include <common/triggers/include.qh>
#include <common/vehicles/all.qh>
#include <lib/csqcmodel/cl_model.qh>
#include <lib/csqcmodel/interpolate.qh>
#include <lib/warpzone/client.qh>
Defines
#define DP_CSQC_ENTITY_REMOVE_IS_B0RKED
Functions
void ConsoleCommand_macro_init ()
void CSQC_Init ()
void Shutdown ()
float SetTeam (entity o, int Team)
void Playerchecker_Think ()
void Porto_Init ()
void TrueAim_Init ()
void PostInit ()
float CSQC_InputEvent (float bInputType, float nPrimary, float nSecondary)
void (entity) predraw_qc = #31
void PreDraw_self ()
void setpredraw (entity this, void(entity) pdfunc)
void Ent_Remove (entity this)
void Ent_RemovePlayerScore (entity this)
NET_HANDLE (ENT_CLIENT_SCORES, bool isnew)
NET_HANDLE (ENT_CLIENT_TEAMSCORES, bool isnew)
NET_HANDLE (ENT_CLIENT_CLIENTDATA, bool isnew)
NET_HANDLE (ENT_CLIENT_NAGGER, bool isnew)
NET_HANDLE (ENT_CLIENT_ELIMINATEDPLAYERS, bool isnew)
NET_HANDLE (ENT_CLIENT_RANDOMSEED, bool isnew)
NET_HANDLE (ENT_CLIENT_ACCURACY, bool isnew)
void Spawn_Draw (entity this)
NET_HANDLE (ENT_CLIENT_SPAWNPOINT, bool is_new)
NET_HANDLE (ENT_CLIENT_SPAWNEVENT, bool is_new)
void CSQC_Ent_Update (bool isnew)
void CSQC_Ent_Remove ()
void Gamemode_Init ()
void CSQC_Parse_StuffCmd (string strMessage)
void CSQC_Parse_Print (string strMessage)
void CSQC_Parse_CenterPrint (string strMessage)
bool CSQC_Parse_TempEntity ()
void Fog_Force ()
NET_HANDLE (ENT_CLIENT_SCORES_INFO, bool isnew)
NET_HANDLE (ENT_CLIENT_INIT, bool isnew)
NET_HANDLE (TE_CSQC_RACE, bool isNew)
NET_HANDLE (TE_CSQC_TEAMNAGGER, bool isNew)
NET_HANDLE (TE_CSQC_PINGPLREPORT, bool isNew)
NET_HANDLE (TE_CSQC_WEAPONCOMPLAIN, bool isNew)
string getcommandkey (string text, string command)
Variables
float has_team
string forcefog
TODO somehow thwart prvm_globalset client ...
Define Documentation
#define DP_CSQC_ENTITY_REMOVE_IS_B0RKED
Definition at line 29 of file main.qc.
Function Documentation
void ConsoleCommand_macro_init ()
Definition at line 609 of file cl_cmd.qc.
References CONSOLE_COMMANDS_MOVEMENT, CONSOLE_COMMANDS_NORMAL, and isdemo().
Referenced by CSQC_Init().
{
    // first init normal commands
    #define CONSOLE_COMMAND(name, execution) \
        { registercommand(name); }
    CONSOLE_COMMANDS_NORMAL();
    #undef CONSOLE_COMMAND
    // then init movement commands
    #ifndef CAMERATEST
    if (isdemo())
    {
    #endif
    #define CONSOLE_COMMAND(name, execution) \
        registercommand(name);
    CONSOLE_COMMANDS_MOVEMENT();
        #undef CONSOLE_COMMAND
    #ifndef CAMERATEST
}
    #endif
}
void CSQC_Ent_Remove ()
Definition at line 807 of file main.qc.
References autocvar_developer_csqcentities, Ent_Remove(), entnum, enttype, LOG_INFOF, LOG_WARNING, and SELFPARAM.
{
    SELFPARAM();
    if (autocvar_developer_csqcentities) LOG_INFOF("CSQC_Ent_Remove() with this=%i {.entnum=%d, .enttype=%d}\n", this, this.entnum, this.enttype);
    if (wasfreed(this))
    {
        LOG_WARNING("CSQC_Ent_Remove called for already removed entity. Packet loss?\n");
        return;
    }
    if (this.enttype) Ent_Remove(this);
    remove(this);
}
void CSQC_Ent_Update (bool isnew)
Definition at line 726 of file main.qc.
References autocvar_developer_csqcentities, classname, clearentity(), Ent_Remove(), entnum, enttype, etof(), FOREACH, LAMBDA, LOG_FATALF, LOG_INFOF, NULL, SELFPARAM, serverdeltatime, serverprevtime, servertime, sourceLoc, STR, and time.
{
    SELFPARAM();
    this.sourceLoc = __FILE__ ":" STR(__LINE__);
    int t = ReadByte();
    // set up the "time" global for received entities to be correct for interpolation purposes
    float savetime = time;
    if(servertime)
    {
        time = servertime;
    }
    else
    {
        serverprevtime = time;
        serverdeltatime = STAT(MOVEVARS_TICRATE) * STAT(MOVEVARS_TIMESCALE);
        time = serverprevtime + serverdeltatime;
    }
#ifdef DP_CSQC_ENTITY_REMOVE_IS_B0RKED
    if (this.enttype)
    {
        if (t != this.enttype || isnew)
        {
            LOG_INFOF("A CSQC entity changed its type! (edict: %d, server: %d, type: %d -> %d)\n", etof(this), this.entnum, this.enttype, t);
            Ent_Remove(this);
            clearentity(this);
            isnew = true;
        }
    }
    else
    {
        if (!isnew)
        {
            LOG_INFOF("A CSQC entity appeared out of nowhere! (edict: %d, server: %d, type: %d)\n", etof(this), this.entnum, t);
            isnew = true;
        }
    }
#endif
    this.enttype = t;
    bool done = false;
    FOREACH(LinkedEntities, it.m_id == t, LAMBDA(
        if (isnew) this.classname = it.netname;
        if (autocvar_developer_csqcentities)
            LOG_INFOF("CSQC_Ent_Update(%d) at %f with this=%i {.entnum=%d, .enttype=%d} t=%s (%d)\n", isnew, savetime, this, this.entnum, this.enttype, this.classname, t);
        done = it.m_read(this, NULL, isnew);
        break;
    ));
    time = savetime;
    if (!done)
    {
        LOG_FATALF("CSQC_Ent_Update(%d) at %f with this=%i {.entnum=%d, .enttype=%d} t=%s (%d)\n", isnew, savetime, this, this.entnum, this.enttype, this.classname, t);
    }
}
void CSQC_Init ()
Definition at line 35 of file main.qc.
References autocvar_cl_reticle, autocvar_hud_skin, binddb, calledhooks, ClientProgsDB, Cmd_HUD_SetFields(), compressShortVector_init(), ConsoleCommand_macro_init(), cvar_string(), db_create(), db_load(), draw_currentSkin, draw_endBoldFont, gametype, get_mi_min_max_texcoords(), GetTeam(), hud_skin_path, hud_title, LOG_INFOF, MAX_HUD_FIELDS, maxclients, mi_center, mi_max, mi_min, mi_scale, mi_shortname, minimapname, NUM_SPECTATOR, players, postinit, precache_pic(), prvm_language, registercvar(), shortmapname, Sort_Spawn(), static_init, static_init_late, static_init_precache, strcat(), strzone(), teams, and tempdb.
{
    prvm_language = strzone(cvar_string("prvm_language"));
#ifdef WATERMARK
    LOG_INFOF("^4CSQC Build information: ^1%s\n", WATERMARK);
#endif
    {
        int i = 0;
        for ( ; i < 255; ++i)
            if (getplayerkeyvalue(i, "viewentity") == "")
                break;
        maxclients = i;
    }
    // needs to be done so early because of the constants they create
    static_init();
    static_init_late();
    static_init_precache();
    binddb = db_create();
    tempdb = db_create();
    ClientProgsDB = db_load("client.db");
    compressShortVector_init();
    draw_endBoldFont();
    //registercommand("hud_configure");
    //registercommand("hud_save");
    //registercommand("menu_action");
    ConsoleCommand_macro_init();
    registercvar("hud_usecsqc", "1");
    registercvar("scoreboard_columns", "default");
    registercvar("cl_nade_type", "3");
    registercvar("cl_pokenade_type", "zombie");
    registercvar("cl_jumpspeedcap_min", "");
    registercvar("cl_jumpspeedcap_max", "");
    registercvar("cl_multijump", "0");
    registercvar("cl_spawn_near_teammate", "1");
    gametype = 0;
    // hud_fields uses strunzone on the titles!
    for(int i = 0; i < MAX_HUD_FIELDS; ++i)
        hud_title[i] = strzone("(null)");
    Cmd_HUD_SetFields(0);
    postinit = false;
    calledhooks = 0;
    teams = Sort_Spawn();
    players = Sort_Spawn();
    GetTeam(NUM_SPECTATOR, true); // add specs first
    // precaches
    if(autocvar_cl_reticle)
    {
        precache_pic("gfx/reticle_normal");
        // weapon reticles are precached in weapon files
    }
    {
        get_mi_min_max_texcoords(1); // try the CLEVER way first
        minimapname = strcat("gfx/", mi_shortname, "_radar.tga");
        shortmapname = mi_shortname;
        if (precache_pic(minimapname) == "")
        {
            // but maybe we have a non-clever minimap
            minimapname = strcat("gfx/", mi_shortname, "_mini.tga");
            if (precache_pic(minimapname) == "")
                minimapname = ""; // FAIL
            else
                get_mi_min_max_texcoords(0); // load new texcoords
        }
        mi_center = (mi_min + mi_max) * 0.5;
        mi_scale = mi_max - mi_min;
        minimapname = strzone(minimapname);
    }
    hud_skin_path = strzone(strcat("gfx/hud/", autocvar_hud_skin));
    draw_currentSkin = strzone(strcat("gfx/menu/", cvar_string("menu_skin")));
}
float CSQC_InputEvent (float bInputType, float nPrimary, float nSecondary)
Definition at line 304 of file main.qc.
References HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_Radar_InputEvent(), MapVote_InputEvent(), and QuickMenu_InputEvent().
{
    if (HUD_Panel_InputEvent(bInputType, nPrimary, nSecondary))
        return true;
    if (QuickMenu_InputEvent(bInputType, nPrimary, nSecondary))
        return true;
    if (HUD_Radar_InputEvent(bInputType, nPrimary, nSecondary))
        return true;
    if (MapVote_InputEvent(bInputType, nPrimary, nSecondary))
        return true;
    if (HUD_Minigame_InputEvent(bInputType, nPrimary, nSecondary))
        return true;
    return false;
}
void CSQC_Parse_CenterPrint (string strMessage)
Definition at line 843 of file main.qc.
References autocvar_developer_csqcentities, centerprint_hud(), and LOG_INFOF.
{
    if (autocvar_developer_csqcentities) LOG_INFOF("CSQC_Parse_CenterPrint(\"%s\")\n", strMessage);
    centerprint_hud(strMessage);
}
void CSQC_Parse_Print (string strMessage)
Definition at line 836 of file main.qc.
References autocvar_developer_csqcentities, ColorTranslateRGB(), LOG_INFOF, and print().
{
    if (autocvar_developer_csqcentities) LOG_INFOF("CSQC_Parse_Print(\"%s\")\n", strMessage);
    print(ColorTranslateRGB(strMessage));
}
void CSQC_Parse_StuffCmd (string strMessage)
Definition at line 830 of file main.qc.
References autocvar_developer_csqcentities, localcmd, and LOG_INFOF.
{
    if (autocvar_developer_csqcentities) LOG_INFOF("CSQC_Parse_StuffCmd(\"%s\")\n", strMessage);
    localcmd(strMessage);
}
bool CSQC_Parse_TempEntity ()
Definition at line 852 of file main.qc.
References autocvar_developer_csqcentities, FOREACH, LAMBDA, LOG_INFOF, and NULL.
{
    // Acquire TE ID
    int nTEID = ReadByte();
    FOREACH(TempEntities, it.m_id == nTEID, LAMBDA(
        if (autocvar_developer_csqcentities)
            LOG_INFOF("CSQC_Parse_TempEntity() nTEID=%s (%d)\n", it.netname, nTEID);
        return it.m_read(NULL, NULL, true);
    ));
    if (autocvar_developer_csqcentities)
        LOG_INFOF("CSQC_Parse_TempEntity() with nTEID=%d\n", nTEID);
    // No special logic for this temporary entity; return 0 so the engine can handle it
    return false;
}
void Ent_Remove (entity this)
Definition at line 784 of file main.qc.
References autocvar_g_jetpack_attenuation, classname, enttype, func_null(), skeletonindex, snd_looping, sound, and VOL_BASE.
Referenced by CSQC_Ent_Remove(), CSQC_Ent_Update(), and NET_HANDLE().
{
    if(this.entremove) this.entremove(this);
    if(this.skeletonindex)
    {
        skel_delete(this.skeletonindex);
        this.skeletonindex = 0;
    }
    if(this.snd_looping > 0)
    {
        sound(this, this.snd_looping, SND_Null, VOL_BASE, autocvar_g_jetpack_attenuation);
        this.snd_looping = 0;
    }
    this.enttype = 0;
    this.classname = "";
    this.draw = func_null;
    this.entremove = func_null;
    // TODO possibly set more stuff to defaults
}
void Ent_RemovePlayerScore (entity this)
Definition at line 345 of file main.qc.
References MAX_SCORE, owner, and SetTeam().
Referenced by NET_HANDLE().
{
    if(this.owner) {
        SetTeam(this.owner, -1);
        this.owner.gotscores = 0;
        for(int i = 0; i < MAX_SCORE; ++i) {
            this.owner.(scores[i]) = 0; // clear all scores
        }
    }
}
void Fog_Force ()
Definition at line 872 of file main.qc.
References autocvar_cl_orthoview, autocvar_cl_orthoview_nofog, and localcmd.
Referenced by CSQC_UpdateView().
{
    if (autocvar_cl_orthoview && autocvar_cl_orthoview_nofog)
        localcmd("\nr_drawfog 0\n");
    else if (forcefog != "")
        localcmd(sprintf("\nfog %s\nr_fog_exp2 0\nr_drawfog 1\n", forcefog));
}
void Gamemode_Init ()
Definition at line 820 of file main.qc.
References calledhooks, gametype, HOOK_START, isdemo(), localcmd, and MapInfo_Type_ToString().
Referenced by NET_HANDLE().
{
    if (!isdemo())
    {
        if(!(calledhooks & HOOK_START))
            localcmd("\n_cl_hook_gamestart ", MapInfo_Type_ToString(gametype), "\n");
        calledhooks |= HOOK_START;
    }
}
string getcommandkey (string text, string command)
Definition at line 1124 of file main.qc.
References argv(), autocvar_hud_showbinds, autocvar_hud_showbinds_limit, binddb, db_get(), db_put(), keynumtostring(), n, stof(), strcat(), and tokenize().
Referenced by HUD_DrawScoreboard(), HUD_InfoMessages(), HUD_Vote(), HUD_Weapons(), and Vehicles_drawHUD().
{
    string keys;
    float n, j, k, l = 0;
    if (!autocvar_hud_showbinds)
        return text;
    keys = db_get(binddb, command);
    if (keys == "")
    {
        n = tokenize(findkeysforcommand(command, 0)); // uses '...' strings
        for(j = 0; j < n; ++j)
        {
            k = stof(argv(j));
            if(k != -1)
            {
                if ("" == keys)
                    keys = keynumtostring(k);
                else
                    keys = strcat(keys, ", ", keynumtostring(k));
                ++l;
                if (autocvar_hud_showbinds_limit > 0 && autocvar_hud_showbinds_limit <= l)
                    break;
            }
        }
        if (keys == "")
            keys = "NO_KEY";
        db_put(binddb, command, keys);
    }
    if (keys == "NO_KEY") {
        if (autocvar_hud_showbinds > 1)
            return sprintf(_("%s (not bound)"), text);
        else
            return text;
    }
    else if (autocvar_hud_showbinds > 1)
        return sprintf("%s (%s)", text, keys);
    else
        return keys;
}
NET_HANDLE (ENT_CLIENT_SCORES , bool isnew)
Definition at line 356 of file main.qc.
References classname, Ent_Remove(), Ent_RemovePlayerScore(), entity(), etof(), HUD_UpdatePlayerPos(), LOG_INFOF, make_pure, MAX_SCORE, n, owner, p, playerslots, and sv_entnum.
{
    make_pure(this);
    int i, n;
    bool isNew;
    entity o;
    // damnit -.- don't want to go change every single .sv_entnum in hud.qc AGAIN
    // (no I've never heard of M-x replace-string, sed, or anything like that)
    isNew = !this.owner; // workaround for DP bug
    n = ReadByte()-1;
#ifdef DP_CSQC_ENTITY_REMOVE_IS_B0RKED
    if(!isNew && n != this.sv_entnum)
    {
        //print("A CSQC entity changed its owner!\n");
        LOG_INFOF("A CSQC entity changed its owner! (edict: %d, classname: %s)\n", etof(this), this.classname);
        isNew = true;
        Ent_Remove(this);
    }
#endif
    this.sv_entnum = n;
    o = playerslots[this.sv_entnum];
    if (!o)
    {
        o = playerslots[this.sv_entnum] = new(playerslot);
        make_pure(o);
    }
    this.owner = o;
    o.sv_entnum = this.sv_entnum;
    o.gotscores = 1;
    //if (!o.sort_prev)
    //  RegisterPlayer(o);
    //playerchecker will do this for us later, if it has not already done so
    int sf, lf;
#if MAX_SCORE <= 8
    sf = ReadByte();
    lf = ReadByte();
#else
    sf = ReadShort();
    lf = ReadShort();
#endif
    int p;
    for(i = 0, p = 1; i < MAX_SCORE; ++i, p *= 2)
        if(sf & p)
        {
            if(lf & p)
                o.(scores[i]) = ReadInt24_t();
            else
                o.(scores[i]) = ReadChar();
        }
    return = true;
    if(o.sort_prev)
        HUD_UpdatePlayerPos(o); // if not registered, we cannot do this yet!
    this.entremove = Ent_RemovePlayerScore;
}
NET_HANDLE (ENT_CLIENT_TEAMSCORES , bool isnew)
Definition at line 420 of file main.qc.
References entity(), GetTeam(), HUD_UpdateTeamPos(), make_pure, MAX_TEAMSCORE, owner, p, and team.
{
    make_pure(this);
    int i;
    entity o;
    this.team = ReadByte();
    o = this.owner = GetTeam(this.team, true); // these team numbers can always be trusted
    int sf, lf;
#if MAX_TEAMSCORE <= 8
    sf = ReadByte();
    lf = ReadByte();
#else
    sf = ReadShort();
    lf = ReadShort();
#endif
    int p;
    for(i = 0, p = 1; i < MAX_TEAMSCORE; ++i, p *= 2)
        if(sf & p)
        {
            if(lf & p)
                o.(teamscores[i]) = ReadInt24_t();
            else
                o.(teamscores[i]) = ReadChar();
        }
    return = true;
    HUD_UpdateTeamPos(o);
}
NET_HANDLE (ENT_CLIENT_CLIENTDATA , bool isnew)
Definition at line 452 of file main.qc.
References angles_held, angles_held_status, autocvar_hud_panel_healtharmor_progressbar_gfx, make_pure, player_localnum, prev_health, prev_p_health, race_checkpointtime, race_laptime, scoreboard_showscores_force, spectatee_status, and spectatorbutton_zoom.
{
    make_pure(this);
    float newspectatee_status;
    int f = ReadByte();
    scoreboard_showscores_force = (f & 1);
    if(f & 2)
    {
        newspectatee_status = ReadByte();
        if(newspectatee_status == player_localnum + 1)
            newspectatee_status = -1; // observing
    }
    else
        newspectatee_status = 0;
    spectatorbutton_zoom = (f & 4);
    if(f & 8)
    {
        angles_held_status = 1;
        angles_held.x = ReadAngle();
        angles_held.y = ReadAngle();
        angles_held.z = 0;
    }
    else
        angles_held_status = 0;
    return = true;
    if(newspectatee_status != spectatee_status)
    {
        // clear race stuff
        race_laptime = 0;
        race_checkpointtime = 0;
    }
    if (autocvar_hud_panel_healtharmor_progressbar_gfx)
    {
        if ( (spectatee_status == -1 && newspectatee_status > 0) //before observing, now spectating
          || (spectatee_status > 0 && newspectatee_status > 0 && spectatee_status != newspectatee_status) //changed spectated player
        )
            prev_p_health = -1;
        else if(spectatee_status && !newspectatee_status) //before observing/spectating, now playing
            prev_health = -1;
    }
    spectatee_status = newspectatee_status;
    // we could get rid of spectatee_status, and derive it from player_localentnum and player_localnum
}
NET_HANDLE (ENT_CLIENT_NAGGER , bool isnew)
Definition at line 504 of file main.qc.
References BIT, ColorTranslateRGB(), make_pure, maxclients, playerslots, ReadString, ready_waiting, ready_waiting_for_me, string_null, strunzone(), strzone(), vote_active, vote_called_vote, vote_highlighted, vote_needed, vote_nocount, vote_waiting, vote_waiting_for_me, vote_yescount, and warmup_stage.
{
    make_pure(this);
    int i, j, b, f;
    int nags = ReadByte(); // NAGS NAGS NAGS NAGS NAGS NAGS NADZ NAGS NAGS NAGS
    if(!(nags & BIT(2)))
    {
        if(vote_called_vote)
            strunzone(vote_called_vote);
        vote_called_vote = string_null;
        vote_active = 0;
    }
    else
    {
        vote_active = 1;
    }
    if(nags & BIT(6))
    {
        vote_yescount = ReadByte();
        vote_nocount = ReadByte();
        vote_needed = ReadByte();
        vote_highlighted = ReadChar();
    }
    if(nags & BIT(7))
    {
        if(vote_called_vote)
            strunzone(vote_called_vote);
        vote_called_vote = strzone(ColorTranslateRGB(ReadString()));
    }
    if(nags & 1)
    {
        for(j = 0; j < maxclients; ++j)
            if(playerslots[j])
                playerslots[j].ready = 1;
        for(i = 1; i <= maxclients; i += 8)
        {
            f = ReadByte();
            for(j = i-1, b = 1; b < 256; b *= 2, ++j)
                if (!(f & b))
                    if(playerslots[j])
                        playerslots[j].ready = 0;
        }
    }
    return = true;
    ready_waiting = (nags & BIT(0));
    ready_waiting_for_me = (nags & BIT(1));
    vote_waiting = (nags & BIT(2));
    vote_waiting_for_me = (nags & BIT(3));
    warmup_stage = (nags & BIT(4));
}
NET_HANDLE (ENT_CLIENT_ELIMINATEDPLAYERS , bool isnew)
Definition at line 562 of file main.qc.
References make_pure, maxclients, and playerslots.
{
    make_pure(this);
    int i, j, b, f;
    int sf = ReadByte();
    if(sf & 1)
    {
        for(j = 0; j < maxclients; ++j)
            if(playerslots[j])
                playerslots[j].eliminated = 1;
        for(i = 1; i <= maxclients; i += 8)
        {
            f = ReadByte();
            for(j = i-1, b = 1; b < 256; b *= 2, ++j)
                if (!(f & b))
                    if(playerslots[j])
                        playerslots[j].eliminated = 0;
        }
    }
    return true;
}
NET_HANDLE (ENT_CLIENT_RANDOMSEED , bool isnew)
Definition at line 585 of file main.qc.
References make_pure, prandom_debug, psrandom(), and s.
{
    make_pure(this);
    prandom_debug();
    float s = ReadShort();
    psrandom(s);
    return true;
}
NET_HANDLE (ENT_CLIENT_ACCURACY , bool isnew)
Definition at line 594 of file main.qc.
References make_pure, weapon_accuracy, WEP_FIRST, and WEP_LAST.
{
    make_pure(this);
    int sf = ReadInt24_t();
    if (sf == 0) {
        for (int w = 0; w <= WEP_LAST - WEP_FIRST; ++w)
            weapon_accuracy[w] = -1;
        return true;
    }
    int f = 1;
    for (int w = 0; w <= WEP_LAST - WEP_FIRST; ++w) {
        if (sf & f) {
            int b = ReadByte();
            if (b == 0)
                weapon_accuracy[w] = -1;
            else if (b == 255)
                weapon_accuracy[w] = 1.0; // no better error handling yet, sorry
            else
                weapon_accuracy[w] = (b - 1.0) / 100.0;
        }
        f = (f == 0x800000) ? 1 : f * 2;
    }
    return true;
}
NET_HANDLE (ENT_CLIENT_SPAWNPOINT , bool is_new)
Definition at line 625 of file main.qc.
References autocvar_cl_spawn_point_particles, cnt, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, origin, particleeffectnum, PL_MAX_CONST, PL_MIN_CONST, SERVERFLAG_TEAMPLAY, serverflags, Spawn_Draw(), and vector().
{
    float teamnum = (ReadByte() - 1);
    vector spn_origin;
    spn_origin.x = ReadShort();
    spn_origin.y = ReadShort();
    spn_origin.z = ReadShort();
    //if(is_new)
    //{
        this.origin = spn_origin;
        setsize(this, PL_MIN_CONST, PL_MAX_CONST);
        //droptofloor();
        /*if(autocvar_cl_spawn_point_model) // needs a model first
        {
            this.mdl = "models/spawnpoint.md3";
            this.colormod = Team_ColorRGB(teamnum);
            precache_model(this.mdl);
            setmodel(this, this.mdl);
            this.drawmask = MASK_NORMAL;
            //this.movetype = MOVETYPE_NOCLIP;
            //this.draw = Spawn_Draw;
        }*/
        if(autocvar_cl_spawn_point_particles)
        {
            if((serverflags & SERVERFLAG_TEAMPLAY))
            {
                switch(teamnum)
                {
                    case NUM_TEAM_1: this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_RED); break;
                    case NUM_TEAM_2: this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_BLUE); break;
                    case NUM_TEAM_3: this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_YELLOW); break;
                    case NUM_TEAM_4: this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_PINK); break;
                    default: this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_NEUTRAL); break;
                }
            }
            else { this.cnt = particleeffectnum(EFFECT_SPAWNPOINT_NEUTRAL); }
            this.draw = Spawn_Draw;
        }
    //}
    //printf("Ent_ReadSpawnPoint(is_new = %d); origin = %s, team = %d, effect = %d\n", is_new, vtos(this.origin), teamnum, this.cnt);
    return true;
}
NET_HANDLE (ENT_CLIENT_SPAWNEVENT , bool is_new)
Definition at line 672 of file main.qc.
References ATTEN_NORM, autocvar_cl_spawn_event_particles, autocvar_cl_spawn_event_sound, autocvar_cl_spawnzoom_factor, autocvar_cl_unpress_zoom_on_spawn, bound(), button_zoom, CH_TRIGGER, current_viewzoom, entnum, HUD_Radar_Hide_Maximized(), localcmd, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, origin, player_localentnum, pointparticles, sound, VOL_BASE, and zoomin_effect.
{
    // If entnum is 0, ONLY do the local spawn actions
    // this way the server can disable the sending of
    // spawn origin or such to clients if wanted.
    float entnum = ReadByte();
    if(entnum)
    {
        this.origin_x = ReadShort();
        this.origin_y = ReadShort();
        this.origin_z = ReadShort();
        if(is_new)
        {
            float teamnum = entcs_GetTeam(entnum - 1);
            if(autocvar_cl_spawn_event_particles)
            {
                switch(teamnum)
                {
                    case NUM_TEAM_1: pointparticles(EFFECT_SPAWN_RED, this.origin, '0 0 0', 1); break;
                    case NUM_TEAM_2: pointparticles(EFFECT_SPAWN_BLUE, this.origin, '0 0 0', 1); break;
                    case NUM_TEAM_3: pointparticles(EFFECT_SPAWN_YELLOW, this.origin, '0 0 0', 1); break;
                    case NUM_TEAM_4: pointparticles(EFFECT_SPAWN_PINK, this.origin, '0 0 0', 1); break;
                    default: pointparticles(EFFECT_SPAWN_NEUTRAL, this.origin, '0 0 0', 1); break;
                }
            }
            if(autocvar_cl_spawn_event_sound)
            {
                sound(this, CH_TRIGGER, SND_SPAWN, VOL_BASE, ATTEN_NORM);
            }
        }
    }
    return = true;
    // local spawn actions
    if(is_new && (!entnum || (entnum == player_localentnum)))
    {
        zoomin_effect = 1;
        current_viewzoom = (1 / bound(1, autocvar_cl_spawnzoom_factor, 16));
        if(autocvar_cl_unpress_zoom_on_spawn)
        {
            localcmd("-zoom\n");
            button_zoom = false;
        }
    }
    HUD_Radar_Hide_Maximized();
    //printf("Ent_ReadSpawnEvent(is_new = %d); origin = %s, entnum = %d, localentnum = %d\n", is_new, vtos(this.origin), entnum, player_localentnum);
}
NET_HANDLE (ENT_CLIENT_SCORES_INFO , bool isnew)
Definition at line 881 of file main.qc.
References Gamemode_Init(), gametype, HUD_InitScores(), HUD_ModIcons_SetFunc(), make_pure, MAX_SCORE, MAX_TEAMSCORE, ReadString, scores_flags, scores_label, strunzone(), strzone(), teamscores_flags, and teamscores_label.
{
    make_pure(this);
    gametype = ReadInt24_t();
    HUD_ModIcons_SetFunc();
    for (int i = 0; i < MAX_SCORE; ++i)
    {
        if (scores_label[i]) strunzone(scores_label[i]);
        scores_label[i] = strzone(ReadString());
        scores_flags[i] = ReadByte();
    }
    for (int i = 0; i < MAX_TEAMSCORE; ++i)
    {
        if (teamscores_label[i]) strunzone(teamscores_label[i]);
        teamscores_label[i] = strzone(ReadString());
        teamscores_flags[i] = ReadByte();
    }
    return = true;
    HUD_InitScores();
    Gamemode_Init();
}
NET_HANDLE (ENT_CLIENT_INIT , bool isnew)
Definition at line 903 of file main.qc.
References arc_shotorigin, armorblockpercent, decompressShotOrigin(), g_trueaim_minrange, hook_shotorigin, MUTATOR_CALLHOOK, nb_pb_period, postinit, PostInit(), ReadString, serverflags, strunzone(), and strzone().
{
    nb_pb_period = ReadByte() / 32; //Accuracy of 1/32th
    hook_shotorigin[0] = decompressShotOrigin(ReadInt24_t());
    hook_shotorigin[1] = decompressShotOrigin(ReadInt24_t());
    hook_shotorigin[2] = decompressShotOrigin(ReadInt24_t());
    hook_shotorigin[3] = decompressShotOrigin(ReadInt24_t());
    arc_shotorigin[0] = decompressShotOrigin(ReadInt24_t());
    arc_shotorigin[1] = decompressShotOrigin(ReadInt24_t());
    arc_shotorigin[2] = decompressShotOrigin(ReadInt24_t());
    arc_shotorigin[3] = decompressShotOrigin(ReadInt24_t());
    if (forcefog) strunzone(forcefog);
    forcefog = strzone(ReadString());
    armorblockpercent = ReadByte() / 255.0;
    serverflags = ReadByte();
    g_trueaim_minrange = ReadCoord();
    return = true;
    MUTATOR_CALLHOOK(Ent_Init);
    if (!postinit) PostInit();
}
NET_HANDLE (TE_CSQC_RACE , bool isNew)
Definition at line 932 of file main.qc.
References ColorTranslateRGB(), grecordholder, grecordtime, player_localnum, race_checkpoint, race_checkpointtime, race_laptime, race_mycheckpoint, race_mycheckpointdelta, race_mycheckpointenemy, race_mycheckpointlapsdelta, race_mycheckpointtime, race_myrank, RACE_NET_CHECKPOINT_CLEAR, RACE_NET_CHECKPOINT_HIT_QUALIFYING, RACE_NET_CHECKPOINT_HIT_RACE, RACE_NET_CHECKPOINT_HIT_RACE_BY_OPPONENT, RACE_NET_CHECKPOINT_NEXT_QUALIFYING, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING, RACE_NET_PENALTY_QUALIFYING, RACE_NET_PENALTY_RACE, RACE_NET_SERVER_RANKINGS, RACE_NET_SERVER_RECORD, RACE_NET_SERVER_STATUS, RACE_NET_SPEED_AWARD, RACE_NET_SPEED_AWARD_BEST, race_nextbestname, race_nextbesttime, race_nextcheckpoint, race_othercheckpoint, race_othercheckpointdelta, race_othercheckpointenemy, race_othercheckpointlapsdelta, race_othercheckpointtime, race_penaltyaccumulator, race_penaltyeventtime, race_penaltyreason, race_penaltytime, race_previousbestname, race_previousbesttime, race_server_record, race_speedaward, race_speedaward_alltimebest, race_speedaward_alltimebest_holder, race_speedaward_holder, race_status, race_status_name, race_time, RANKINGS_CNT, ReadString, string_null, strunzone(), strzone(), and time.
{
    int b = ReadByte();
    switch (b)
    {
        case RACE_NET_CHECKPOINT_HIT_QUALIFYING:
            race_checkpoint = ReadByte();
            race_time = ReadInt24_t();
            race_previousbesttime = ReadInt24_t();
            if(race_previousbestname)
                strunzone(race_previousbestname);
            race_previousbestname = strzone(ColorTranslateRGB(ReadString()));
            race_checkpointtime = time;
            if(race_checkpoint == 0 || race_checkpoint == 254)
            {
                race_penaltyaccumulator = 0;
                race_laptime = time; // valid
            }
            break;
        case RACE_NET_CHECKPOINT_CLEAR:
            race_laptime = 0;
            race_checkpointtime = 0;
            break;
        case RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING:
            race_laptime = ReadCoord();
            race_checkpointtime = -99999;
            // fall through
        case RACE_NET_CHECKPOINT_NEXT_QUALIFYING:
            race_nextcheckpoint = ReadByte();
            race_nextbesttime = ReadInt24_t();
            if(race_nextbestname)
                strunzone(race_nextbestname);
            race_nextbestname = strzone(ColorTranslateRGB(ReadString()));
            break;
        case RACE_NET_CHECKPOINT_HIT_RACE:
            race_mycheckpoint = ReadByte();
            race_mycheckpointtime = time;
            race_mycheckpointdelta = ReadInt24_t();
            race_mycheckpointlapsdelta = ReadByte();
            if(race_mycheckpointlapsdelta >= 128)
                race_mycheckpointlapsdelta -= 256;
            if(race_mycheckpointenemy)
                strunzone(race_mycheckpointenemy);
            race_mycheckpointenemy = strzone(ColorTranslateRGB(ReadString()));
            break;
        case RACE_NET_CHECKPOINT_HIT_RACE_BY_OPPONENT:
            race_othercheckpoint = ReadByte();
            race_othercheckpointtime = time;
            race_othercheckpointdelta = ReadInt24_t();
            race_othercheckpointlapsdelta = ReadByte();
            if(race_othercheckpointlapsdelta >= 128)
                race_othercheckpointlapsdelta -= 256;
            if(race_othercheckpointenemy)
                strunzone(race_othercheckpointenemy);
            race_othercheckpointenemy = strzone(ColorTranslateRGB(ReadString()));
            break;
        case RACE_NET_PENALTY_RACE:
            race_penaltyeventtime = time;
            race_penaltytime = ReadShort();
            //race_penaltyaccumulator += race_penaltytime;
            if(race_penaltyreason)
                strunzone(race_penaltyreason);
            race_penaltyreason = strzone(ReadString());
            break;
        case RACE_NET_PENALTY_QUALIFYING:
            race_penaltyeventtime = time;
            race_penaltytime = ReadShort();
            race_penaltyaccumulator += race_penaltytime;
            if(race_penaltyreason)
                strunzone(race_penaltyreason);
            race_penaltyreason = strzone(ReadString());
            break;
        case RACE_NET_SERVER_RECORD:
            race_server_record = ReadInt24_t();
            break;
        case RACE_NET_SPEED_AWARD:
            race_speedaward = ReadInt24_t();
            if(race_speedaward_holder)
                strunzone(race_speedaward_holder);
            race_speedaward_holder = strzone(ReadString());
            break;
        case RACE_NET_SPEED_AWARD_BEST:
            race_speedaward_alltimebest = ReadInt24_t();
            if(race_speedaward_alltimebest_holder)
                strunzone(race_speedaward_alltimebest_holder);
            race_speedaward_alltimebest_holder = strzone(ReadString());
            break;
        case RACE_NET_SERVER_RANKINGS:
            float prevpos, del;
            int pos = ReadShort();
            prevpos = ReadShort();
            del = ReadShort();
            // move other rankings out of the way
            int i;
            if (prevpos) {
                for (i=prevpos-1;i>pos-1;--i) {
                    grecordtime[i] = grecordtime[i-1];
                    if(grecordholder[i])
                        strunzone(grecordholder[i]);
                    grecordholder[i] = strzone(grecordholder[i-1]);
                }
            } else if (del) { // a record has been deleted by the admin
                for (i=pos-1; i<= RANKINGS_CNT-1; ++i) {
                    if (i == RANKINGS_CNT-1) { // clear out last record
                        grecordtime[i] = 0;
                        if (grecordholder[i])
                            strunzone(grecordholder[i]);
                        grecordholder[i] = string_null;
                    }
                    else {
                        grecordtime[i] = grecordtime[i+1];
                        if (grecordholder[i])
                            strunzone(grecordholder[i]);
                        grecordholder[i] = strzone(grecordholder[i+1]);
                    }
                }
            } else { // player has no ranked record yet
                for (i=RANKINGS_CNT-1;i>pos-1;--i) {
                    grecordtime[i] = grecordtime[i-1];
                    if(grecordholder[i])
                        strunzone(grecordholder[i]);
                    grecordholder[i] = strzone(grecordholder[i-1]);
                }
            }
            // store new ranking
            if(grecordholder[pos-1] != "")
                strunzone(grecordholder[pos-1]);
            grecordholder[pos-1] = strzone(ReadString());
            grecordtime[pos-1] = ReadInt24_t();
            if(grecordholder[pos-1] == entcs_GetName(player_localnum))
                race_myrank = pos;
            break;
        case RACE_NET_SERVER_STATUS:
            race_status = ReadShort();
            if(race_status_name)
                strunzone(race_status_name);
            race_status_name = strzone(ReadString());
    }
    return true;
}
NET_HANDLE (TE_CSQC_TEAMNAGGER , bool isNew)
Definition at line 1087 of file main.qc.
References teamnagger.
{
    teamnagger = 1;
    return true;
}
NET_HANDLE (TE_CSQC_PINGPLREPORT , bool isNew)
Definition at line 1093 of file main.qc.
References entity(), and playerslots.
{
    int i = ReadByte();
    int pi = ReadShort();
    int pl = ReadByte();
    int ml = ReadByte();
    return = true;
    entity e = playerslots[i];
    if (!e) return;
    e.ping = pi;
    e.ping_packetloss = pl / 255.0;
    e.ping_movementloss = ml / 255.0;
}
NET_HANDLE (TE_CSQC_WEAPONCOMPLAIN , bool isNew)
Definition at line 1107 of file main.qc.
References complain_weapon, complain_weapon_time, complain_weapon_type, ITEM_WEAPON_NOAMMO, ITEM_WEAPON_UNAVAILABLE, Local_Notification(), MSG_MULTI, time, and weapontime.
{
    complain_weapon = ReadByte();
    complain_weapon_type = ReadByte();
    return = true;
    complain_weapon_time = time;
    weapontime = time; // ping the weapon panel
    switch(complain_weapon_type)
    {
        case 0: Local_Notification(MSG_MULTI, ITEM_WEAPON_NOAMMO, complain_weapon); break;
        case 1: Local_Notification(MSG_MULTI, ITEM_WEAPON_DONTHAVE, complain_weapon); break;
        default: Local_Notification(MSG_MULTI, ITEM_WEAPON_UNAVAILABLE, complain_weapon); break;
    }
}
void Playerchecker_Think ()
Definition at line 238 of file main.qc.
References entity(), HUD_UpdatePlayerPos(), make_pure, maxclients, nextthink, playerslots, RegisterPlayer(), RemovePlayer(), SELFPARAM, SetTeam(), time, and world.
Referenced by PostInit().
{
    SELFPARAM();
    int i;
    entity e;
    for(i = 0; i < maxclients; ++i)
    {
        e = playerslots[i];
        if(entcs_GetName(i) == "")
        {
            if(e.sort_prev)
            {
                // player disconnected
                SetTeam(e, -1);
                RemovePlayer(e);
                e.sort_prev = world;
                //e.gotscores = 0;
            }
        }
        else
        {
            if (!e.sort_prev)
            {
                // player connected
                if (!e)
                {
                    playerslots[i] = e = new(playerslot);
                    make_pure(e);
                }
                e.sv_entnum = i;
                e.ping = 0;
                e.ping_packetloss = 0;
                e.ping_movementloss = 0;
                //e.gotscores = 0; // we might already have the scores...
                int t = entcs_GetScoreTeam(i);
                if (t) SetTeam(e, t); // will not hurt; later updates come with HUD_UpdatePlayerTeams
                RegisterPlayer(e);
                HUD_UpdatePlayerPos(e);
            }
        }
    }
    this.nextthink = time + 0.2;
}
void Porto_Init ()
Definition at line 427 of file view.qc.
References DPCONTENTS_BODY, DPCONTENTS_PLAYERCLIP, DPCONTENTS_SOLID, make_pure, porto, and Porto_Draw().
Referenced by PostInit().
{
    porto = new(porto);
    make_pure(porto);
    porto.draw = Porto_Draw;
    porto.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_PLAYERCLIP;
}
void PostInit ()
Definition at line 284 of file main.qc.
References entity(), make_pure, Playerchecker_Think(), Porto_Init(), postinit, time, and TrueAim_Init().
Referenced by CSQC_UpdateView(), and NET_HANDLE().
{
    entity playerchecker = new(playerchecker);
    make_pure(playerchecker);
    playerchecker.think = Playerchecker_Think;
    playerchecker.nextthink = time + 0.2;
    Porto_Init();
    TrueAim_Init();
    postinit = true;
}
void PreDraw_self ()
Definition at line 331 of file main.qc.
References SELFPARAM.
Referenced by setpredraw().
{
    SELFPARAM();
    if (this.predraw_qc) this.predraw_qc(this);
}
void setpredraw (entity this, void(entity) pdfunc)
Definition at line 337 of file main.qc.
References PreDraw_self().
Referenced by NET_HANDLE().
{
    this.predraw = PreDraw_self;
    this.predraw_qc = pdfunc;
}
float SetTeam (entity o, int Team)
Definition at line 166 of file main.qc.
References devassert_once, entity(), GetTeam(), LOG_TRACEF, NUM_SPECTATOR, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, teamplay, and world.
Referenced by Ent_RemovePlayerScore(), HUD_UpdatePlayerTeams(), and Playerchecker_Think().
{
    devassert_once(Team);
    entity tm;
    if(teamplay)
    {
        switch(Team)
        {
            case -1:
            case NUM_TEAM_1:
            case NUM_TEAM_2:
            case NUM_TEAM_3:
            case NUM_TEAM_4:
                break;
            default:
                if(GetTeam(Team, false) == world)
                {
                    LOG_TRACEF("trying to switch to unsupported team %d\n", Team);
                    Team = NUM_SPECTATOR;
                }
                break;
        }
    }
    else
    {
        switch(Team)
        {
            case -1:
            case 0:
                break;
            default:
                if(GetTeam(Team, false) == world)
                {
                    LOG_TRACEF("trying to switch to unsupported team %d\n", Team);
                    Team = NUM_SPECTATOR;
                }
                break;
        }
    }
    if(Team == -1) // leave
    {
        if(o.has_team)
        {
            tm = GetTeam(o.team, false);
            tm.team_size -= 1;
            o.has_team = 0;
            return true;
        }
    }
    else
    {
        if (!o.has_team)
        {
            o.team = Team;
            tm = GetTeam(Team, true);
            tm.team_size += 1;
            o.has_team = 1;
            return true;
        }
        else if(Team != o.team)
        {
            tm = GetTeam(o.team, false);
            tm.team_size -= 1;
            o.team = Team;
            tm = GetTeam(Team, true);
            tm.team_size += 1;
            return true;
        }
    }
    return false;
}
void Shutdown ()
Definition at line 132 of file main.qc.
{
    WarpZone_Shutdown();
    remove(teams);
    remove(players);
    db_close(binddb);
    db_close(tempdb);
    if(autocvar_cl_db_saveasdump)
        db_dump(ClientProgsDB, "client.db");
    else
        db_save(ClientProgsDB, "client.db");
    db_close(ClientProgsDB);
    if(camera_active)
        cvar_set("chase_active",ftos(chase_active_backup));
    // unset the event chasecam's chase_active
    if(autocvar_chase_active < 0)
        cvar_set("chase_active", "0");
    if (!isdemo())
    {
        if (!(calledhooks & HOOK_START))
            localcmd("\n_cl_hook_gamestart nop\n");
        if (!(calledhooks & HOOK_END))
            localcmd("\ncl_hook_gameend\n");
    }
    deactivate_minigame();
    HUD_MinigameMenu_Close();
}
void Spawn_Draw (entity this)
Definition at line 620 of file main.qc.
References bound(), cnt, frametime, and origin.
Referenced by NET_HANDLE().
{
    __pointparticles(this.cnt, this.origin + '0 0 28', '0 0 2', bound(0, frametime, 0.1));
}
void TrueAim_Init ()
Definition at line 595 of file view.qc.
References DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, make_pure, trueaim, and trueaim_rifle.
Referenced by PostInit().
{
    trueaim = new(trueaim);
    make_pure(trueaim);
    trueaim.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
    trueaim_rifle = new(trueaim_rifle);
    make_pure(trueaim_rifle);
    trueaim_rifle.dphitcontentsmask = DPCONTENTS_BODY | DPCONTENTS_CORPSE;
}
void (entity) = #31
Variable Documentation
string forcefog
TODO somehow thwart prvm_globalset client ...
Definition at line 871 of file main.qc.
float has_team
Definition at line 165 of file main.qc.