Xonotic: server/weapons/csqcprojectile.qh File Reference
server/weapons/csqcprojectile.qh File Reference
Defines
#define CSQCPROJECTILE_H
Functions
void CSQCProjectile (entity e, float clientanimate, float type, float docull)
void UpdateCSQCProjectile (entity e)
void UpdateCSQCProjectileAfterTeleport (entity e)
void CSQCProjectile_Check (entity e)
Variables
float csqcprojectile_clientanimate
Define Documentation
#define CSQCPROJECTILE_H
Definition at line 2 of file csqcprojectile.qh.
Function Documentation
void CSQCProjectile (entity e, float clientanimate, float type, float docull)
void CSQCProjectile_Check (entity e)
Definition at line 71 of file csqcprojectile.qc.
References IS_ONGROUND, and UpdateCSQCProjectile().
Referenced by StartFrame().
{
    if(e.csqcprojectile_clientanimate)
    if(IS_ONGROUND(e))
    if(e.origin != e.csqcprojectile_oldorigin)
        UpdateCSQCProjectile(e);
    e.csqcprojectile_oldorigin = e.origin;
}
void UpdateCSQCProjectile (entity e)
Definition at line 99 of file csqcprojectile.qc.
References CSQCProjectile_SendEntity().
Referenced by conveyor_think(), CSQCProjectile_Check(), Damage(), GrapplingHookThink(), trigger_impulse_touch1(), trigger_impulse_touch2(), trigger_impulse_touch3(), trigger_push_touch(), and WarpZone_Projectile_Touch_ImpactFilter_Callback().
{
    if(e.SendEntity3 == CSQCProjectile_SendEntity)
    {
        // send new origin data
        e.SendFlags |= 0x01;
    }
// FIXME HACK
    else if(e.SendEntity3 == ItemSend)
    {
        ItemUpdate(e);
    }
// END HACK
}
void UpdateCSQCProjectileAfterTeleport (entity e)
Definition at line 114 of file csqcprojectile.qc.
References CSQCProjectile_SendEntity().
Referenced by WarpZone_PostTeleportPlayer_Callback().
{
    if(e.SendEntity3 == CSQCProjectile_SendEntity)
    {
        // send new origin data
        e.SendFlags |= 0x01;
        // mark as teleported
        e.SendFlags |= 0x08;
    }
}
Variable Documentation
float csqcprojectile_clientanimate
Definition at line 4 of file csqcprojectile.qh.
Referenced by CSQCProjectile_SendEntity(), and StartFrame().