Xonotic: server/g_damage.qh File Reference
server/g_damage.qh File Reference
Defines
#define G_DAMAGE_H
Functions
bool Damage_DamageInfo_SendEntity (entity this, entity to, int sf)
void Damage_DamageInfo (vector org, float coredamage, float edgedamage, float rad, vector force, int deathtype, float bloodtype, entity dmgowner)
float IsFlying (entity a)
void UpdateFrags (entity player, float f)
void W_SwitchWeapon_Force (entity e, Weapon w)
void GiveFrags (entity attacker, entity targ, float f, int deathtype)
string AppendItemcodes (string s, entity player)
void LogDeath (string mode, int deathtype, entity killer, entity killed)
void Obituary_SpecialDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2, float f3)
float Obituary_WeaponDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2)
void Obituary (entity attacker, entity inflictor, entity targ, int deathtype)
void Ice_Think ()
void Freeze (entity targ, float freeze_time, float frozen_type, float show_waypoint)
void Unfreeze (entity targ)
void Damage (entity targ, entity inflictor, entity attacker, float damage, int deathtype, vector hitloc, vector force)
float RadiusDamageForSource (entity inflictor, vector inflictororigin, vector inflictorvelocity, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float inflictorselfdamage, float forceintensity, int deathtype, entity directhitentity)
float RadiusDamage (entity inflictor, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float forceintensity, int deathtype, entity directhitentity)
void fireburner_think ()
float Fire_IsBurning (entity e)
float Fire_AddDamage (entity e, entity o, float d, float t, float dt)
void Fire_ApplyDamage (entity e)
void Fire_ApplyEffect (entity e)
Variables
float dmg
float dmg_edge
float dmg_force
float dmg_radius
float checkrules_firstblood
float yoda
float damage_goodhits
float damage_gooddamage
float dmg_team
float teamkill_complain
float teamkill_soundtime
entity teamkill_soundsource
entity pusher
float istypefrag
float taunt_soundtime
entity GiveFrags_randomweapons
float w_deathtype
entity damage_targ
entity damage_inflictor
entity damage_attacker
float RadiusDamage_running
float fire_damagepersec
float fire_endtime
float fire_deathtype
entity fire_owner
float fire_hitsound
entity fire_burner
Define Documentation
#define G_DAMAGE_H
Definition at line 2 of file g_damage.qh.
Function Documentation
string AppendItemcodes (string s, entity player)
Definition at line 114 of file g_damage.qc.
References ftos(), PS(), s, strcat(), time, and world.
Referenced by LogDeath().
{
    int w = PS(player).m_weapon.m_id;
    //if(w == 0)
    //  w = player.switchweapon;
    if(w == 0)
        w = player.cnt; // previous weapon!
    s = strcat(s, ftos(w));
    if(time < player.strength_finished)
        s = strcat(s, "S");
    if(time < player.invincible_finished)
        s = strcat(s, "I");
    if(player.flagcarried != world)
        s = strcat(s, "F");
    if(player.BUTTON_CHAT)
        s = strcat(s, "T");
    if(player.kh_next)
        s = strcat(s, "K");
    return s;
}
void Damage (entity targ, entity inflictor, entity attacker, float damage, int deathtype, vector hitloc, vector force)
Definition at line 571 of file g_damage.qc.
References ACTIVE_ACTIVE, autocvar_g_balance_armor_blockpercent, autocvar_g_balance_damagepush_speedfactor, autocvar_g_balance_powerup_invincible_takedamage, autocvar_g_balance_powerup_strength_damage, autocvar_g_balance_powerup_strength_force, autocvar_g_balance_powerup_strength_selfdamage, autocvar_g_balance_powerup_strength_selfforce, autocvar_g_balance_selfdamagepercent, autocvar_g_friendlyfire, autocvar_g_friendlyfire_virtual, autocvar_g_friendlyfire_virtual_force, autocvar_g_frozen_damage_trigger, autocvar_g_frozen_force, autocvar_g_frozen_revive_falldamage, autocvar_g_frozen_revive_falldamage_health, autocvar_g_mirrordamage, autocvar_g_mirrordamage_virtual, autocvar_g_teamdamage_threshold, autocvar_teamplay_mode, CENTER_FREEZETAG_REVIVE_SELF, Damage(), DAMAGE_AIM, damage_attacker, damage_explosion_calcpush(), damage_gooddamage, damage_goodhits, damage_inflictor, damage_targ, damageforcescale, DEAD_NO, DEATH_ISSPECIAL, DEATH_ISWEAPON, DIFF_TEAM, EF_TELEPORT_BIT, entity(), FL_GODMODE, FL_ONGROUND, FORCETYPE_FORCEATPOS, frag_damage, frag_force, frag_mirrordamage, FRAGS_SPECTATOR, g_instagib, g_weapondamagefactor, g_weaponforcefactor, gameover, healtharmor_applydamage(), IS_DEAD, IS_INDEPENDENT_PLAYER, IS_MONSTER, IS_PLAYER, IS_TURRET, IS_VEHICLE, IsFlying(), mass, movetype, MOVETYPE_PHYSICS, MSG_CENTER, MSG_INFO, MUTATOR_CALLHOOK, normalize(), origin, RemoveGrapplingHook(), SAME_TEAM, SelectSpawnPoint(), SELFPARAM, setself, spawnshieldtime, SUB_Remove_self(), time, Unfreeze(), UNSET_ONGROUND, UpdateCSQCProjectile(), vector(), vehicles_exit(), velocity, vlen(), world, and yoda.
{SELFPARAM();
    float mirrordamage;
    float mirrorforce;
    float complainteamdamage = 0;
    entity attacker_save;
    mirrordamage = 0;
    mirrorforce = 0;
    if (gameover || targ.killcount == FRAGS_SPECTATOR)
        return;
    setself(targ);
        damage_targ = targ;
        damage_inflictor = inflictor;
        damage_attacker = attacker;
        attacker_save = attacker;
    if(IS_PLAYER(targ))
        if(targ.hook)
            if(targ.hook.aiment)
                if(targ.hook.aiment == attacker)
                    RemoveGrapplingHook(targ); // STOP THAT, you parasite!
    // special rule: gravity bomb does not hit team mates (other than for disconnecting the hook)
    if(DEATH_ISWEAPON(deathtype, WEP_HOOK) || DEATH_ISWEAPON(deathtype, WEP_TUBA))
    {
        if(IS_PLAYER(targ))
            if(SAME_TEAM(targ, attacker))
            {
                setself(this);
                return;
            }
    }
    if(deathtype == DEATH_KILL.m_id || deathtype == DEATH_TEAMCHANGE.m_id || deathtype == DEATH_AUTOTEAMCHANGE.m_id)
    {
        // exit the vehicle before killing (fixes a crash)
        if(IS_PLAYER(targ) && targ.vehicle)
            vehicles_exit(VHEF_RELEASE);
        // These are ALWAYS lethal
        // No damage modification here
        // Instead, prepare the victim for his death...
        targ.armorvalue = 0;
        targ.spawnshieldtime = 0;
        targ.health = 0.9; // this is < 1
        targ.flags -= targ.flags & FL_GODMODE;
        damage = 100000;
    }
    else if(deathtype == DEATH_MIRRORDAMAGE.m_id || deathtype == DEATH_NOAMMO.m_id)
    {
        // no processing
    }
    else
    {
        // nullify damage if teamplay is on
        if(deathtype != DEATH_TELEFRAG.m_id)
        if(IS_PLAYER(attacker))
        {
            if(IS_PLAYER(targ) && targ != attacker && (IS_INDEPENDENT_PLAYER(attacker) || IS_INDEPENDENT_PLAYER(targ)))
            {
                damage = 0;
                force = '0 0 0';
            }
            else if(SAME_TEAM(attacker, targ))
            {
                if(autocvar_teamplay_mode == 1)
                    damage = 0;
                else if(attacker != targ)
                {
                    if(autocvar_teamplay_mode == 3)
                        damage = 0;
                    else if(autocvar_teamplay_mode == 4)
                    {
                        if(IS_PLAYER(targ) && !IS_DEAD(targ))
{
                            attacker.dmg_team = attacker.dmg_team + damage;
                            complainteamdamage = attacker.dmg_team - autocvar_g_teamdamage_threshold;
                            if(complainteamdamage > 0)
                                mirrordamage = autocvar_g_mirrordamage * complainteamdamage;
                            mirrorforce = autocvar_g_mirrordamage * vlen(force);
                            damage = autocvar_g_friendlyfire * damage;
                            // mirrordamage will be used LATER
                            if(autocvar_g_mirrordamage_virtual)
{
                                vector v  = healtharmor_applydamage(attacker.armorvalue, autocvar_g_balance_armor_blockpercent, deathtype, mirrordamage);
                                attacker.dmg_take += v.x;
                                attacker.dmg_save += v.y;
                                attacker.dmg_inflictor = inflictor;
                                mirrordamage = v.z;
                                mirrorforce = 0;
                            }
                            if(autocvar_g_friendlyfire_virtual)
{
                                vector v = healtharmor_applydamage(targ.armorvalue, autocvar_g_balance_armor_blockpercent, deathtype, damage);
                                targ.dmg_take += v.x;
                                targ.dmg_save += v.y;
                                targ.dmg_inflictor = inflictor;
                                damage = 0;
                                if(!autocvar_g_friendlyfire_virtual_force)
                                    force = '0 0 0';
                            }
                        }
                        else
                            damage = 0;
                    }
                }
            }
        }
        if (!DEATH_ISSPECIAL(deathtype))
        {
            damage *= g_weapondamagefactor;
            mirrordamage *= g_weapondamagefactor;
            complainteamdamage *= g_weapondamagefactor;
            force = force * g_weaponforcefactor;
            mirrorforce *= g_weaponforcefactor;
        }
        // should this be changed at all? If so, in what way?
        MUTATOR_CALLHOOK(PlayerDamage_Calculate, inflictor, attacker, targ, deathtype, damage, mirrordamage, force);
        damage = frag_damage;
        mirrordamage = frag_mirrordamage;
        force = frag_force;
        if(STAT(FROZEN, targ))
        if(deathtype != DEATH_HURTTRIGGER.m_id && deathtype != DEATH_TEAMCHANGE.m_id && deathtype != DEATH_AUTOTEAMCHANGE.m_id)
        {
            if(autocvar_g_frozen_revive_falldamage > 0)
            if(deathtype == DEATH_FALL.m_id)
            if(damage >= autocvar_g_frozen_revive_falldamage)
            {
                Unfreeze(targ);
                targ.health = autocvar_g_frozen_revive_falldamage_health;
                Send_Effect(EFFECT_ICEORGLASS, targ.origin, '0 0 0', 3);
                Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_FREEZETAG_REVIVED_FALL, targ.netname);
                Send_Notification(NOTIF_ONE, targ, MSG_CENTER, CENTER_FREEZETAG_REVIVE_SELF);
            }
            damage = 0;
            force *= autocvar_g_frozen_force;
        }
        if(STAT(FROZEN, targ) && deathtype == DEATH_HURTTRIGGER.m_id && !autocvar_g_frozen_damage_trigger)
        {
            Send_Effect(EFFECT_TELEPORT, targ.origin, '0 0 0', 1);
            setself(targ);
            entity spot = SelectSpawnPoint (false);
            if(spot)
            {
                damage = 0;
                self.deadflag = DEAD_NO;
                self.angles = spot.angles;
                self.effects = 0;
                self.effects |= EF_TELEPORT_BIT;
                self.angles_z = 0; // never spawn tilted even if the spot says to
                self.fixangle = true; // turn this way immediately
                self.velocity = '0 0 0';
                self.avelocity = '0 0 0';
                self.punchangle = '0 0 0';
                self.punchvector = '0 0 0';
                self.oldvelocity = self.velocity;
                self.spawnorigin = spot.origin;
                setorigin (self, spot.origin + '0 0 1' * (1 - self.mins.z - 24));
                // don't reset back to last position, even if new position is stuck in solid
                self.oldorigin = self.origin;
                self.prevorigin = self.origin;
                Send_Effect(EFFECT_TELEPORT, self.origin, '0 0 0', 1);
            }
            setself(this);
        }
        if(!g_instagib)
        {
            // apply strength multiplier
            if (attacker.items & ITEM_Strength.m_itemid)
            {
                if(targ == attacker)
                {
                    damage = damage * autocvar_g_balance_powerup_strength_selfdamage;
                    force = force * autocvar_g_balance_powerup_strength_selfforce;
                }
                else
                {
                    damage = damage * autocvar_g_balance_powerup_strength_damage;
                    force = force * autocvar_g_balance_powerup_strength_force;
                }
            }
            // apply invincibility multiplier
            if (targ.items & ITEM_Shield.m_itemid)
                damage = damage * autocvar_g_balance_powerup_invincible_takedamage;
        }
        if (targ == attacker)
            damage = damage * autocvar_g_balance_selfdamagepercent; // Partial damage if the attacker hits himself
        // count the damage
        if(attacker)
        if(!IS_DEAD(targ))
        if(deathtype != DEATH_BUFF.m_id)
        if(targ.takedamage == DAMAGE_AIM)
        if(targ != attacker)
        {
            entity victim;
            if(IS_VEHICLE(targ) && targ.owner)
                victim = targ.owner;
            else
                victim = targ;
            if(IS_PLAYER(victim) || (IS_TURRET(victim) && victim.active == ACTIVE_ACTIVE) || IS_MONSTER(victim) || MUTATOR_CALLHOOK(PlayHitsound, victim))
            {
                if(DIFF_TEAM(victim, attacker) && !STAT(FROZEN, victim))
                {
                    if(damage > 0)
                    {
                        if(deathtype != DEATH_FIRE.m_id)
{
                            if(victim.BUTTON_CHAT)
                                attacker.typehitsound += 1;
                            else
                                attacker.damage_dealt += damage;
                        }
                        damage_goodhits += 1;
                        damage_gooddamage += damage;
                        if (!DEATH_ISSPECIAL(deathtype))
{
                            if(IS_PLAYER(targ)) // don't do this for vehicles
                            if(IsFlying(victim))
                                yoda = 1;
                        }
                    }
                }
                else
                {
                    if(deathtype != DEATH_FIRE.m_id)
                    {
                        attacker.typehitsound += 1;
                    }
                    if(complainteamdamage > 0)
                        if(time > attacker.teamkill_complain)
{
                            attacker.teamkill_complain = time + 5;
                            attacker.teamkill_soundtime = time + 0.4;
                            attacker.teamkill_soundsource = targ;
                        }
                }
            }
        }
    }
    // apply push
    if (self.damageforcescale)
    if (vlen(force))
    if (!IS_PLAYER(self) || time >= self.spawnshieldtime || self == attacker)
    {
        vector farce = damage_explosion_calcpush(self.damageforcescale * force, self.velocity, autocvar_g_balance_damagepush_speedfactor);
        if(self.movetype == MOVETYPE_PHYSICS)
        {
            entity farcent = new(farce);
            farcent.enemy = self;
            farcent.movedir = farce * 10;
            if(self.mass)
                farcent.movedir = farcent.movedir * self.mass;
            farcent.origin = hitloc;
            farcent.forcetype = FORCETYPE_FORCEATPOS;
            farcent.nextthink = time + 0.1;
            farcent.think = SUB_Remove_self;
        }
        else
        {
            self.velocity = self.velocity + farce;
            self.move_velocity = self.velocity;
        }
        UNSET_ONGROUND(self);
        self.move_flags &= ~FL_ONGROUND;
        UpdateCSQCProjectile(self);
    }
    // apply damage
    if (damage != 0 || (self.damageforcescale && vlen(force)))
    if (self.event_damage)
        self.event_damage (self, inflictor, attacker, damage, deathtype, hitloc, force);
    setself(this);
    // apply mirror damage if any
    if(mirrordamage > 0 || mirrorforce > 0)
    {
        attacker = attacker_save;
        force = normalize(attacker.origin + attacker.view_ofs - hitloc) * mirrorforce;
        Damage(attacker, inflictor, attacker, mirrordamage, DEATH_MIRRORDAMAGE.m_id, attacker.origin, force);
    }
}
void Damage_DamageInfo (vector org, float coredamage, float edgedamage, float rad, vector force, int deathtype, float bloodtype, entity dmgowner)
Referenced by fireBullet(), FireRailgunBullet(), and RadiusDamageForSource().
bool Damage_DamageInfo_SendEntity (entity this, entity to, int sf)
float Fire_AddDamage (entity e, entity o, float d, float t, float dt)
Definition at line 1077 of file g_damage.qc.
References accuracy_add(), accuracy_isgooddamage(), DEATH_WEAPONOF, Fire_IsBurning(), fireburner_think(), IS_DEAD, IS_PLAYER, m_id, max(), min(), and time.
Referenced by CreatureFrame_hotliquids(), and Fire_ApplyDamage().
{
    float dps;
    float maxtime, mintime, maxdamage, mindamage, maxdps, mindps, totaldamage, totaltime;
    if(IS_PLAYER(e))
    {
        if(IS_DEAD(e))
            return -1;
    }
    else
    {
        if(!e.fire_burner)
        {
            // print("adding a fire burner to ", e.classname, "\n");
            e.fire_burner = new(fireburner);
            e.fire_burner.think = fireburner_think;
            e.fire_burner.nextthink = time;
            e.fire_burner.owner = e;
        }
    }
    t = max(t, 0.1);
    dps = d / t;
    if(Fire_IsBurning(e))
    {
        mintime = e.fire_endtime - time;
        maxtime = max(mintime, t);
        mindps = e.fire_damagepersec;
        maxdps = max(mindps, dps);
        if(maxtime > mintime || maxdps > mindps)
        {
            // Constraints:
            // damage we have right now
            mindamage = mindps * mintime;
            // damage we want to get
            maxdamage = mindamage + d;
            // but we can't exceed maxtime * maxdps!
            totaldamage = min(maxdamage, maxtime * maxdps);
            // LEMMA:
            // Look at:
            // totaldamage = min(mindamage + d, maxtime * maxdps)
            // We see:
            // totaldamage <= maxtime * maxdps
            // ==> totaldamage / maxdps <= maxtime.
            // We also see:
            // totaldamage / mindps = min(mindamage / mindps + d, maxtime * maxdps / mindps)
            //                     >= min(mintime, maxtime)
            // ==> totaldamage / maxdps >= mintime.
            /*
            // how long do we damage then?
            // at least as long as before
            // but, never exceed maxdps
            totaltime = max(mintime, totaldamage / maxdps); // always <= maxtime due to lemma
            */
            // alternate:
            // at most as long as maximum allowed
            // but, never below mindps
            totaltime = min(maxtime, totaldamage / mindps); // always >= mintime due to lemma
            // assuming t > mintime, dps > mindps:
            // we get d = t * dps = maxtime * maxdps
            // totaldamage = min(maxdamage, maxtime * maxdps) = min(... + d, maxtime * maxdps) = maxtime * maxdps
            // totaldamage / maxdps = maxtime
            // totaldamage / mindps > totaldamage / maxdps = maxtime
            // FROM THIS:
            // a) totaltime = max(mintime, maxtime) = maxtime
            // b) totaltime = min(maxtime, totaldamage / maxdps) = maxtime
            // assuming t <= mintime:
            // we get maxtime = mintime
            // a) totaltime = max(mintime, ...) >= mintime, also totaltime <= maxtime by the lemma, therefore totaltime = mintime = maxtime
            // b) totaltime = min(maxtime, ...) <= maxtime, also totaltime >= mintime by the lemma, therefore totaltime = mintime = maxtime
            // assuming dps <= mindps:
            // we get mindps = maxdps.
            // With this, the lemma says that mintime <= totaldamage / mindps = totaldamage / maxdps <= maxtime.
            // a) totaltime = max(mintime, totaldamage / maxdps) = totaldamage / maxdps
            // b) totaltime = min(maxtime, totaldamage / mindps) = totaldamage / maxdps
            e.fire_damagepersec = totaldamage / totaltime;
            e.fire_endtime = time + totaltime;
            if(totaldamage > 1.2 * mindamage)
            {
                e.fire_deathtype = dt;
                if(e.fire_owner != o)
                {
                    e.fire_owner = o;
                    e.fire_hitsound = false;
                }
            }
            if(accuracy_isgooddamage(o, e))
                accuracy_add(o, DEATH_WEAPONOF(dt).m_id, 0, max(0, totaldamage - mindamage));
            return max(0, totaldamage - mindamage); // can never be negative, but to make sure
        }
        else
            return 0;
    }
    else
    {
        e.fire_damagepersec = dps;
        e.fire_endtime = time + t;
        e.fire_deathtype = dt;
        e.fire_owner = o;
        e.fire_hitsound = false;
        if(accuracy_isgooddamage(o, e))
            accuracy_add(o, DEATH_WEAPONOF(dt).m_id, 0, d);
        return d;
    }
}
void Fire_ApplyDamage (entity e)
Definition at line 1196 of file g_damage.qc.
References autocvar_g_balance_firetransfer_damage, autocvar_g_balance_firetransfer_time, boxesoverlap(), CONTENT_LAVA, Damage(), entity(), Fire_AddDamage(), Fire_IsBurning(), FOREACH_CLIENT, frametime, IS_DEAD, IS_INDEPENDENT_PLAYER, IS_NOT_A_CLIENT, IS_PLAYER, LAMBDA, min(), and time.
Referenced by fireburner_think(), and player_powerups().
{
    float t, d, hi, ty;
    entity o;
    if (!Fire_IsBurning(e))
        return;
    for(t = 0, o = e.owner; o.owner && t < 16; o = o.owner, ++t);
    if(IS_NOT_A_CLIENT(o))
        o = e.fire_owner;
    // water and slime stop fire
    if(e.waterlevel)
    if(e.watertype != CONTENT_LAVA)
        e.fire_endtime = 0;
    // ice stops fire
    if(STAT(FROZEN, e))
        e.fire_endtime = 0;
    t = min(frametime, e.fire_endtime - time);
    d = e.fire_damagepersec * t;
    hi = e.fire_owner.damage_dealt;
    ty = e.fire_owner.typehitsound;
    Damage(e, e, e.fire_owner, d, e.fire_deathtype, e.origin, '0 0 0');
    if(e.fire_hitsound && e.fire_owner)
    {
        e.fire_owner.damage_dealt = hi;
        e.fire_owner.typehitsound = ty;
    }
    e.fire_hitsound = true;
    if(!IS_INDEPENDENT_PLAYER(e))
    if(!STAT(FROZEN, e))
        FOREACH_CLIENT(IS_PLAYER(it) && it != e, LAMBDA(
            if(!IS_DEAD(it))
            if(!IS_INDEPENDENT_PLAYER(it))
            if(boxesoverlap(e.absmin, e.absmax, it.absmin, it.absmax))
            {
                t = autocvar_g_balance_firetransfer_time * (e.fire_endtime - time);
                d = autocvar_g_balance_firetransfer_damage * e.fire_damagepersec * t;
                Fire_AddDamage(it, o, d, t, DEATH_FIRE.m_id);
            }
        ));
}
void Fire_ApplyEffect (entity e)
Definition at line 1244 of file g_damage.qc.
References EF_FLAME, and Fire_IsBurning().
Referenced by fireburner_think(), and player_powerups().
{
    if(Fire_IsBurning(e))
        e.effects |= EF_FLAME;
    else
        e.effects &= ~EF_FLAME;
}
float Fire_IsBurning (entity e)
Definition at line 1072 of file g_damage.qc.
References time.
Referenced by Fire_AddDamage(), Fire_ApplyDamage(), Fire_ApplyEffect(), and fireburner_think().
{
    return (time < e.fire_endtime);
}
void fireburner_think ()
Definition at line 1252 of file g_damage.qc.
References Fire_ApplyDamage(), Fire_ApplyEffect(), Fire_IsBurning(), owner, SELFPARAM, time, and world.
Referenced by Fire_AddDamage().
{SELFPARAM();
    // for players, this is done in the regular loop
    if(wasfreed(self.owner))
    {
        remove(self);
        return;
    }
    Fire_ApplyEffect(self.owner);
    if(!Fire_IsBurning(self.owner))
    {
        self.owner.fire_burner = world;
        remove(self);
        return;
    }
    Fire_ApplyDamage(self.owner);
    self.nextthink = time;
}
void Freeze (entity targ, float freeze_time, float frozen_type, float show_waypoint)
Definition at line 508 of file g_damage.qc.
References entity(), floor(), FOREACH_CLIENT, Ice_Think(), IS_MONSTER, IS_PLAYER, LAMBDA, random(), RemoveGrapplingHook(), SELFPARAM, setmodel, start_health, Team_ColorRGB(), time, WITH, and world.
{SELFPARAM();
    if(!IS_PLAYER(targ) && !IS_MONSTER(targ)) // only specified entities can be freezed
        return;
    if(STAT(FROZEN, targ))
        return;
    float targ_maxhealth = ((IS_MONSTER(targ)) ? targ.max_health : start_health);
    STAT(FROZEN, targ) = frozen_type;
    targ.revive_progress = ((frozen_type == 3) ? 1 : 0);
    targ.health = ((frozen_type == 3) ? targ_maxhealth : 1);
    targ.revive_speed = freeze_time;
    self.bot_attack = false;
    entity ice = new(ice);
    ice.owner = targ;
    ice.scale = targ.scale;
    ice.think = Ice_Think;
    ice.nextthink = time;
    ice.frame = floor(random() * 21); // ice model has 20 different looking frames
    setmodel(ice, MDL_ICE);
    ice.alpha = 1;
    ice.colormod = Team_ColorRGB(targ.team);
    ice.glowmod = ice.colormod;
    targ.iceblock = ice;
    targ.revival_time = 0;
    WITH(entity, self, ice, Ice_Think());
    RemoveGrapplingHook(targ);
    FOREACH_CLIENT(IS_PLAYER(it) && it.hook.aiment == targ, LAMBDA(RemoveGrapplingHook(it)));
    // add waypoint
    if(show_waypoint)
        WaypointSprite_Spawn(WP_Frozen, 0, 0, targ, '0 0 64', world, targ.team, targ, waypointsprite_attached, true, RADARICON_WAYPOINT);
}
void GiveFrags (entity attacker, entity targ, float f, int deathtype)
Definition at line 31 of file g_damage.qc.
References DEATH_WEAPONOF, frag_score, g_weaponarena_random, g_weaponarena_random_with_blaster, gameover, GiveFrags_randomweapons, MUTATOR_CALLHOOK, PlayerScore_Add(), PS(), SELFPARAM, SP_DEATHS, SP_KILLS, SP_SUICIDES, start_weapons, UpdateFrags(), w_getbestweapon, W_RandomWeapons(), W_SwitchWeapon_Force(), warmup_stage, WARMUP_START_WEAPONS, and WepSet_FromWeapon.
Referenced by Obituary().
{SELFPARAM();
    // TODO route through PlayerScores instead
    if(gameover) return;
    if(f < 0)
    {
        if(targ == attacker)
        {
            // suicide
            PlayerScore_Add(attacker, SP_SUICIDES, 1);
        }
        else
        {
            // teamkill
            PlayerScore_Add(attacker, SP_KILLS, -1); // or maybe add a teamkills field?
        }
    }
    else
    {
        // regular frag
        PlayerScore_Add(attacker, SP_KILLS, 1);
        if(targ.playerid)
            PS_GR_P_ADDVAL(attacker, sprintf("kills-%d", targ.playerid), 1);
    }
    PlayerScore_Add(targ, SP_DEATHS, 1);
    if(targ != attacker) // not for suicides
    if(g_weaponarena_random)
    {
        // after a frag, exchange the current weapon (or the culprit, if detectable) by a new random weapon
        Weapon culprit = DEATH_WEAPONOF(deathtype);
        if(!culprit) culprit = PS(attacker).m_weapon;
        else if(!(attacker.weapons & (culprit.m_wepset))) culprit = PS(attacker).m_weapon;
        if(g_weaponarena_random_with_blaster && culprit == WEP_BLASTER) // WEAPONTODO: Shouldn't this be in a mutator?
        {
            // no exchange
        }
        else
        {
            if(!GiveFrags_randomweapons)
            {
                GiveFrags_randomweapons = new(GiveFrags_randomweapons);
            }
            if(warmup_stage)
                GiveFrags_randomweapons.weapons = WARMUP_START_WEAPONS;
            else
                GiveFrags_randomweapons.weapons = start_weapons;
            // all others (including the culprit): remove
            GiveFrags_randomweapons.weapons &= ~attacker.weapons;
            GiveFrags_randomweapons.weapons &= ~(culprit.m_wepset);
            // among the remaining ones, choose one by random
            W_RandomWeapons(GiveFrags_randomweapons, 1);
            if(GiveFrags_randomweapons.weapons)
            {
                attacker.weapons |= GiveFrags_randomweapons.weapons;
                attacker.weapons &= ~(culprit.m_wepset);
            }
        }
        // after a frag, choose another random weapon set
        if (!(attacker.weapons & WepSet_FromWeapon(PS(attacker).m_weapon)))
            W_SwitchWeapon_Force(attacker, w_getbestweapon(attacker));
    }
    // FIXME fix the mess this is (we have REAL points now!)
    if(MUTATOR_CALLHOOK(GiveFragsForKill, self, attacker, targ, f))
    {
        f = frag_score;
    }
    attacker.totalfrags += f;
    if(f)
        UpdateFrags(attacker, f);
}
void Ice_Think ()
Definition at line 497 of file g_damage.qc.
References owner, SELFPARAM, and time.
Referenced by Freeze().
{SELFPARAM();
    if(!STAT(FROZEN, self.owner) || self.owner.iceblock != self)
    {
        remove(self);
        return;
    }
    setorigin(self, self.owner.origin - '0 0 16');
    self.nextthink = time;
}
float IsFlying (entity a)
Definition at line 1274 of file player.qc.
References IS_ONGROUND, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by Damage(), and PM_Main().
{
    if(IS_ONGROUND(this))
        return false;
    if(this.waterlevel >= WATERLEVEL_SWIMMING)
        return false;
    //traceline(this.origin, this.origin - '0 0 48', MOVE_NORMAL, this);
    //if(trace_fraction < 1)
        //return false;
    return true;
}
void LogDeath (string mode, int deathtype, entity killer, entity killed)
Definition at line 135 of file g_damage.qc.
References AppendItemcodes(), autocvar_sv_eventlog, Deathtype_Name(), ftos(), GameLogEcho(), s, and strcat().
Referenced by Obituary().
{
    string s;
    if(!autocvar_sv_eventlog)
        return;
    s = strcat(":kill:", mode);
    s = strcat(s, ":", ftos(killer.playerid));
    s = strcat(s, ":", ftos(killed.playerid));
    s = strcat(s, ":type=", Deathtype_Name(deathtype));
    s = strcat(s, ":items=");
    s = AppendItemcodes(s, killer);
    if(killed != killer)
    {
        s = strcat(s, ":victimitems=");
        s = AppendItemcodes(s, killed);
    }
    GameLogEcho(s);
}
void Obituary (entity attacker, entity inflictor, entity targ, int deathtype)
Definition at line 263 of file g_damage.qc.
References ANNCE_ACHIEVEMENT_BOTLIKE, APP_TEAM_NUM_4, backtrace, CENTER_DEATH_TEAMKILL_FRAGGED, checkrules_firstblood, CHOICE_FRAG, CHOICE_TYPEFRAG, DEATH_ENT, DEATH_ISSPECIAL, deathmessage, Deathtype_Name(), GiveFrags(), IS_BOT_CLIENT, IS_PLAYER, KILL_SPREE_LIST, LogDeath(), MSG_ANNCE, MSG_CENTER, MSG_CHOICE, MSG_INFO, NearestLocation(), NO_MSG, Obituary_SpecialDeath(), Obituary_WeaponDeath(), PlayerScore_Add(), SAME_TEAM, SP_SCORE, strcat(), strstrofs, time, and world.
Referenced by PlayerDamage().
{
    // Sanity check
    if (!IS_PLAYER(targ)) { backtrace("Obituary called on non-player?!\n"); return; }
    // Declarations
    float notif_firstblood = false;
    float kill_count_to_attacker, kill_count_to_target;
    // Set final information for the death
    targ.death_origin = targ.origin;
    if(targ != attacker) { targ.killer_origin = attacker.origin; }
    string deathlocation = (autocvar_notification_server_allows_location ? NearestLocation(targ.death_origin) : "");
    #ifdef NOTIFICATIONS_DEBUG
    Debug_Notification(
        sprintf(
            "Obituary(%s, %s, %s, %s = %d);\n",
            attacker.netname,
            inflictor.netname,
            targ.netname,
            Deathtype_Name(deathtype),
            deathtype
        )
    );
    #endif
    // =======
    // SUICIDE
    // =======
    if(targ == attacker)
    {
        if(DEATH_ISSPECIAL(deathtype))
        {
            if(deathtype == DEATH_TEAMCHANGE.m_id || deathtype == DEATH_AUTOTEAMCHANGE.m_id)
            {
                Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.team, 0, 0);
            }
            else
            {
                switch(DEATH_ENT(deathtype))
                {
                    case DEATH_MIRRORDAMAGE:
                    {
                        Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.killcount, 0, 0);
                        break;
                    }
                    default:
                    {
                        Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.killcount, 0, 0);
                        break;
                    }
                }
            }
        }
        else if (!Obituary_WeaponDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.killcount, 0))
        {
            backtrace("SUICIDE: what the hell happened here?\n");
            return;
        }
        LogDeath("suicide", deathtype, targ, targ);
        GiveFrags(attacker, targ, -1, deathtype);
    }
    // ======
    // MURDER
    // ======
    else if(IS_PLAYER(attacker))
    {
        if(SAME_TEAM(attacker, targ))
        {
            LogDeath("tk", deathtype, attacker, targ);
            GiveFrags(attacker, targ, -1, deathtype);
            attacker.killcount = 0;
            Send_Notification(NOTIF_ONE, attacker, MSG_CENTER, CENTER_DEATH_TEAMKILL_FRAG, targ.netname);
            Send_Notification(NOTIF_ONE, targ, MSG_CENTER, CENTER_DEATH_TEAMKILL_FRAGGED, attacker.netname);
            Send_Notification(NOTIF_ALL, world, MSG_INFO, APP_TEAM_NUM_4(targ.team, INFO_DEATH_TEAMKILL_), targ.netname, attacker.netname, deathlocation, targ.killcount);
            // In this case, the death message will ALWAYS be "foo was betrayed by bar"
            // No need for specific death/weapon messages...
        }
        else
        {
            LogDeath("frag", deathtype, attacker, targ);
            GiveFrags(attacker, targ, 1, deathtype);
            attacker.taunt_soundtime = time + 1;
            attacker.killcount = attacker.killcount + 1;
            #define SPREE_ITEM(counta,countb,center,normal,gentle) \
                case counta: \
                { \
                    Send_Notification(NOTIF_ONE, attacker, MSG_ANNCE, ANNCE_KILLSTREAK_##countb); \
                    PS_GR_P_ADDVAL(attacker, PLAYERSTATS_ACHIEVEMENT_KILL_SPREE_##counta, 1); \
                    break; \
                }
            switch(attacker.killcount)
            {
                KILL_SPREE_LIST
                default: break;
            }
            #undef SPREE_ITEM
            if(!checkrules_firstblood)
            {
                checkrules_firstblood = true;
                notif_firstblood = true; // modify the current messages so that they too show firstblood information
                PS_GR_P_ADDVAL(attacker, PLAYERSTATS_ACHIEVEMENT_FIRSTBLOOD, 1);
                PS_GR_P_ADDVAL(targ, PLAYERSTATS_ACHIEVEMENT_FIRSTVICTIM, 1);
                // tell spree_inf and spree_cen that this is a first-blood and first-victim event
                kill_count_to_attacker = -1;
                kill_count_to_target = -2;
            }
            else
            {
                kill_count_to_attacker = attacker.killcount;
                kill_count_to_target = 0;
            }
            if(targ.istypefrag)
            {
                Send_Notification(
                    NOTIF_ONE,
                    attacker,
                    MSG_CHOICE,
                    CHOICE_TYPEFRAG,
                    targ.netname,
                    kill_count_to_attacker,
                    (IS_BOT_CLIENT(targ) ? NO_MSG : targ.ping)
                );
                Send_Notification(
                    NOTIF_ONE,
                    targ,
                    MSG_CHOICE,
                    CHOICE_TYPEFRAGGED,
                    attacker.netname,
                    kill_count_to_target,
                    attacker.health,
                    attacker.armorvalue,
                    (IS_BOT_CLIENT(attacker) ? NO_MSG : attacker.ping)
                );
            }
            else
            {
                Send_Notification(
                    NOTIF_ONE,
                    attacker,
                    MSG_CHOICE,
                    CHOICE_FRAG,
                    targ.netname,
                    kill_count_to_attacker,
                    (IS_BOT_CLIENT(targ) ? NO_MSG : targ.ping)
                );
                Send_Notification(
                    NOTIF_ONE,
                    targ,
                    MSG_CHOICE,
                    CHOICE_FRAGGED,
                    attacker.netname,
                    kill_count_to_target,
                    attacker.health,
                    attacker.armorvalue,
                    (IS_BOT_CLIENT(attacker) ? NO_MSG : attacker.ping)
                );
            }
            float f3 = 0;
            if(deathtype == DEATH_BUFF.m_id)
                f3 = attacker.buffs;
            if (!Obituary_WeaponDeath(targ, true, deathtype, targ.netname, attacker.netname, deathlocation, targ.killcount, kill_count_to_attacker))
                Obituary_SpecialDeath(targ, true, deathtype, targ.netname, attacker.netname, deathlocation, targ.killcount, kill_count_to_attacker, f3);
        }
    }
    // =============
    // ACCIDENT/TRAP
    // =============
    else
    {
        switch(DEATH_ENT(deathtype))
        {
            // For now, we're just forcing HURTTRIGGER to behave as "DEATH_VOID" and giving it no special options...
            // Later on you will only be able to make custom messages using DEATH_CUSTOM,
            // and there will be a REAL DEATH_VOID implementation which mappers will use.
            case DEATH_HURTTRIGGER:
            {
                Obituary_SpecialDeath(targ, false, deathtype,
                    targ.netname,
                    inflictor.message,
                    deathlocation,
                    targ.killcount,
                    0,
                    0);
                break;
            }
            case DEATH_CUSTOM:
            {
                Obituary_SpecialDeath(targ, false, deathtype,
                    targ.netname,
                    ((strstrofs(deathmessage, "%", 0) < 0) ? strcat("%s ", deathmessage) : deathmessage),
                    deathlocation,
                    targ.killcount,
                    0,
                    0);
                break;
            }
            default:
            {
                Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.killcount, 0, 0);
                break;
            }
        }
        LogDeath("accident", deathtype, targ, targ);
        GiveFrags(targ, targ, -1, deathtype);
        if(PlayerScore_Add(targ, SP_SCORE, 0) == -5)
        {
            Send_Notification(NOTIF_ONE, targ, MSG_ANNCE, ANNCE_ACHIEVEMENT_BOTLIKE);
            PS_GR_P_ADDVAL(attacker, PLAYERSTATS_ACHIEVEMENT_BOTLIKE, 1);
        }
    }
    // reset target kill count
    if(targ.killcount) { targ.killcount = 0; }
}
void Obituary_SpecialDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2, float f3)
Definition at line 154 of file g_damage.qc.
References backtrace, DEATH_ISSPECIAL, Deathtypes_from, DT_FIRST, entity(), MSG_INFO, and MSG_MULTI.
Referenced by Obituary().
{
    if(DEATH_ISSPECIAL(deathtype))
    {
        entity deathent = Deathtypes_from(deathtype - DT_FIRST);
        if (!deathent) { backtrace("Obituary_SpecialDeath: Could not find deathtype entity!\n"); return; }
        if(murder)
        {
            if(deathent.death_msgmurder)
            {
                Send_Notification_WOCOVA(
                    NOTIF_ONE,
                    notif_target,
                    MSG_MULTI,
                    deathent.death_msgmurder.nent_id,
                    s1, s2, s3, "",
                    f1, f2, f3, 0
                );
                Send_Notification_WOCOVA(
                    NOTIF_ALL_EXCEPT,
                    notif_target,
                    MSG_INFO,
                    deathent.death_msgmurder.nent_msginfo.nent_id,
                    s1, s2, s3, "",
                    f1, f2, f3, 0
                );
            }
        }
        else
        {
            if(deathent.death_msgself)
            {
                Send_Notification_WOCOVA(
                    NOTIF_ONE,
                    notif_target,
                    MSG_MULTI,
                    deathent.death_msgself.nent_id,
                    s1, s2, s3, "",
                    f1, f2, f3, 0
                );
                Send_Notification_WOCOVA(
                    NOTIF_ALL_EXCEPT,
                    notif_target,
                    MSG_INFO,
                    deathent.death_msgself.nent_msginfo.nent_id,
                    s1, s2, s3, "",
                    f1, f2, f3, 0
                );
            }
        }
    }
    else { backtrace("Obituary_SpecialDeath called without a special deathtype?\n"); return; }
}
float Obituary_WeaponDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2)
Definition at line 214 of file g_damage.qc.
References DEATH_WEAPONOF, LOG_TRACEF, MSG_INFO, MSG_MULTI, msg_multi_notifs, nent_msginfo, and w_deathtype.
Referenced by Obituary().
{
    Weapon death_weapon = DEATH_WEAPONOF(deathtype);
    if (death_weapon != WEP_Null)
    {
        w_deathtype = deathtype;
        int death_message = ((murder) ? death_weapon.wr_killmessage(death_weapon) : death_weapon.wr_suicidemessage(death_weapon));
        w_deathtype = false;
        if (death_message)
        {
            Send_Notification_WOCOVA(
                NOTIF_ONE,
                notif_target,
                MSG_MULTI,
                death_message,
                s1, s2, s3, "",
                f1, f2, 0, 0
            );
            Send_Notification_WOCOVA(
                NOTIF_ALL_EXCEPT,
                notif_target,
                MSG_INFO,
                msg_multi_notifs[death_message - 1].nent_msginfo.nent_id,
                s1, s2, s3, "",
                f1, f2, 0, 0
            );
        }
        else
        {
            LOG_TRACEF(
                "Obituary_WeaponDeath(): ^1Deathtype ^7(%d)^1 has no notification for weapon %d!\n",
                deathtype,
                death_weapon
            );
        }
        return true;
    }
    return false;
}
float RadiusDamage (entity inflictor, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float forceintensity, int deathtype, entity directhitentity)
Definition at line 1067 of file g_damage.qc.
References RadiusDamageForSource().
Referenced by CheatImpulse(), and vehicles_projectile_explode().
{
    return RadiusDamageForSource (inflictor, (inflictor.origin + (inflictor.mins + inflictor.maxs) * 0.5), inflictor.velocity, attacker, coredamage, edgedamage, rad, cantbe, mustbe, false, forceintensity, deathtype, directhitentity);
}
float RadiusDamageForSource (entity inflictor, vector inflictororigin, vector inflictorvelocity, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float inflictorselfdamage, float forceintensity, int deathtype, entity directhitentity)
Definition at line 878 of file g_damage.qc.
References accuracy_add(), accuracy_isgooddamage(), autocvar_g_throughfloor_damage, autocvar_g_throughfloor_damage_max_stddev, autocvar_g_throughfloor_debug, autocvar_g_throughfloor_force, autocvar_g_throughfloor_force_max_stddev, autocvar_g_throughfloor_max_steps_other, autocvar_g_throughfloor_max_steps_player, autocvar_g_throughfloor_min_steps_other, autocvar_g_throughfloor_min_steps_player, backtrace, bound(), ceil(), CENTER_OR_VIEWOFS, Damage(), Damage_DamageInfo(), DEATH_ISSPECIAL, DEATH_WEAPONOF, entity(), HITTYPE_BOUNCE, HITTYPE_SECONDARY, HITTYPE_SPLASH, IS_PLAYER, LOG_INFOF, m_id, max(), MAX_DAMAGEEXTRARADIUS, min(), MIN_DAMAGEEXTRARADIUS, MOVE_NOMONSTERS, normalize(), pow(), RadiusDamage_running, random(), sqrt(), trace_ent, trace_fraction, vector(), vlen(), WarpZone_FindRadius(), WarpZone_TraceLine(), WarpZone_TransformOrigin(), WarpZone_UnTransformOrigin(), and WEP_CVAR_BOTH.
Referenced by RadiusDamage().
{
    entity  targ;
    vector  force;
    float   total_damage_to_creatures;
    entity  next;
    float   tfloordmg;
    float   tfloorforce;
    float stat_damagedone;
    if(RadiusDamage_running)
    {
        backtrace("RadiusDamage called recursively! Expect stuff to go HORRIBLY wrong.");
        return 0;
    }
    RadiusDamage_running = 1;
    tfloordmg = autocvar_g_throughfloor_damage;
    tfloorforce = autocvar_g_throughfloor_force;
    total_damage_to_creatures = 0;
    if(deathtype != (WEP_HOOK.m_id | HITTYPE_SECONDARY | HITTYPE_BOUNCE)) // only send gravity bomb damage once
        if(DEATH_WEAPONOF(deathtype) != WEP_TUBA) // do not send tuba damage (bandwidth hog)
        {
            force = inflictorvelocity;
            if(vlen(force) == 0)
                force = '0 0 -1';
            else
                force = normalize(force);
            if(forceintensity >= 0)
                Damage_DamageInfo(inflictororigin, coredamage, edgedamage, rad, forceintensity * force, deathtype, 0, attacker);
            else
                Damage_DamageInfo(inflictororigin, coredamage, edgedamage, -rad, (-forceintensity) * force, deathtype, 0, attacker);
        }
    stat_damagedone = 0;
    targ = WarpZone_FindRadius (inflictororigin, rad + MAX_DAMAGEEXTRARADIUS, false);
    while (targ)
    {
        next = targ.chain;
        if ((targ != inflictor) || inflictorselfdamage)
        if (((cantbe != targ) && !mustbe) || (mustbe == targ))
        if (targ.takedamage)
        {
            vector nearest;
            vector diff;
            float power;
            // LordHavoc: measure distance to nearest point on target (not origin)
            // (this guarentees 100% damage on a touch impact)
            nearest = targ.WarpZone_findradius_nearest;
            diff = targ.WarpZone_findradius_dist;
            // round up a little on the damage to ensure full damage on impacts
            // and turn the distance into a fraction of the radius
            power = 1 - ((vlen (diff) - bound(MIN_DAMAGEEXTRARADIUS, targ.damageextraradius, MAX_DAMAGEEXTRARADIUS)) / rad);
            //bprint(" ");
            //bprint(ftos(power));
            //if (targ == attacker)
            //  print(ftos(power), "\n");
            if (power > 0)
            {
                float finaldmg;
                if (power > 1)
                    power = 1;
                finaldmg = coredamage * power + edgedamage * (1 - power);
                if (finaldmg > 0)
                {
                    float a;
                    float c;
                    vector hitloc;
                    vector myblastorigin;
                    vector center;
                    myblastorigin = WarpZone_TransformOrigin(targ, inflictororigin);
                    // if it's a player, use the view origin as reference
                    center = CENTER_OR_VIEWOFS(targ);
                    force = normalize(center - myblastorigin);
                    force = force * (finaldmg / coredamage) * forceintensity;
                    hitloc = nearest;
                    if(deathtype & WEP_BLASTER.m_id)
                        force *= WEP_CVAR_BOTH(blaster, !(deathtype & HITTYPE_SECONDARY), force_zscale);
                    if(targ != directhitentity)
                    {
                        float hits;
                        float total;
                        float hitratio;
                        float mininv_f, mininv_d;
                        // test line of sight to multiple positions on box,
                        // and do damage if any of them hit
                        hits = 0;
                        // we know: max stddev of hitratio = 1 / (2 * sqrt(n))
                        // so for a given max stddev:
                        // n = (1 / (2 * max stddev of hitratio))^2
                        mininv_d = (finaldmg * (1-tfloordmg)) / autocvar_g_throughfloor_damage_max_stddev;
                        mininv_f = (vlen(force) * (1-tfloorforce)) / autocvar_g_throughfloor_force_max_stddev;
                        if(autocvar_g_throughfloor_debug)
                            LOG_INFOF("THROUGHFLOOR: D=%f F=%f max(dD)=1/%f max(dF)=1/%f", finaldmg, vlen(force), mininv_d, mininv_f);
                        total = 0.25 * pow(max(mininv_f, mininv_d), 2);
                        if(autocvar_g_throughfloor_debug)
                            LOG_INFOF(" steps=%f", total);
                        if (IS_PLAYER(targ))
                            total = ceil(bound(autocvar_g_throughfloor_min_steps_player, total, autocvar_g_throughfloor_max_steps_player));
                        else
                            total = ceil(bound(autocvar_g_throughfloor_min_steps_other, total, autocvar_g_throughfloor_max_steps_other));
                        if(autocvar_g_throughfloor_debug)
                            LOG_INFOF(" steps=%f dD=%f dF=%f", total, finaldmg * (1-tfloordmg) / (2 * sqrt(total)), vlen(force) * (1-tfloorforce) / (2 * sqrt(total)));
                        for(c = 0; c < total; ++c)
{
                            //traceline(targ.WarpZone_findradius_findorigin, nearest, MOVE_NOMONSTERS, inflictor);
                            WarpZone_TraceLine(inflictororigin, WarpZone_UnTransformOrigin(targ, nearest), MOVE_NOMONSTERS, inflictor);
                            if (trace_fraction == 1 || trace_ent == targ)
{
                                ++hits;
                                if (hits > 1)
                                    hitloc = hitloc + nearest;
                                else
                                    hitloc = nearest;
                            }
                            nearest.x = targ.origin.x + targ.mins.x + random() * targ.size.x;
                            nearest.y = targ.origin.y + targ.mins.y + random() * targ.size.y;
                            nearest.z = targ.origin.z + targ.mins.z + random() * targ.size.z;
                        }
                        nearest = hitloc * (1 / max(1, hits));
                        hitratio = (hits / total);
                        a = bound(0, tfloordmg + (1-tfloordmg) * hitratio, 1);
                        finaldmg = finaldmg * a;
                        a = bound(0, tfloorforce + (1-tfloorforce) * hitratio, 1);
                        force = force * a;
                        if(autocvar_g_throughfloor_debug)
                            LOG_INFOF(" D=%f F=%f\n", finaldmg, vlen(force));
                    }
                    //if (targ == attacker)
                    //{
                    //  print("hits ", ftos(hits), " / ", ftos(total));
                    //  print(" finaldmg ", ftos(finaldmg), " force ", vtos(force));
                    //  print(" (", ftos(a), ")\n");
                    //}
                    if(finaldmg || vlen(force))
                    {
                        if(targ.iscreature)
{
                            total_damage_to_creatures += finaldmg;
                            if(accuracy_isgooddamage(attacker, targ))
                                stat_damagedone += finaldmg;
                        }
                        if(targ == directhitentity || DEATH_ISSPECIAL(deathtype))
                            Damage (targ, inflictor, attacker, finaldmg, deathtype, nearest, force);
                        else
                            Damage (targ, inflictor, attacker, finaldmg, deathtype | HITTYPE_SPLASH, nearest, force);
                    }
                }
            }
        }
        targ = next;
    }
    RadiusDamage_running = 0;
    if(!DEATH_ISSPECIAL(deathtype))
        accuracy_add(attacker, DEATH_WEAPONOF(deathtype).m_id, 0, min(coredamage, stat_damagedone));
    return total_damage_to_creatures;
}
void Unfreeze (entity targ)
Definition at line 548 of file g_damage.qc.
References FOREACH_CLIENT, IS_PLAYER, LAMBDA, RemoveGrapplingHook(), start_health, time, and world.
Referenced by ClientDisconnect(), Damage(), Monster_Dead(), Monster_Move(), Monster_Reset(), PlayerDamage(), PlayerPreThink(), PutClientInServer(), and PutObserverInServer().
{
    if(!STAT(FROZEN, targ))
        return;
    if(STAT(FROZEN, targ) && STAT(FROZEN, targ) != 3) // only reset health if target was frozen
        targ.health = ((IS_PLAYER(targ)) ? start_health : targ.max_health);
    STAT(FROZEN, targ) = 0;
    targ.revive_progress = 0;
    targ.revival_time = time;
    self.bot_attack = true;
    WaypointSprite_Kill(targ.waypointsprite_attached);
    FOREACH_CLIENT(IS_PLAYER(it) && it.hook.aiment == targ, LAMBDA(RemoveGrapplingHook(it)));
    // remove the ice block
    if(targ.iceblock)
        remove(targ.iceblock);
    targ.iceblock = world;
}
void UpdateFrags (entity player, float f)
Definition at line 26 of file g_damage.qc.
References PlayerTeamScore_AddScore.
{
    PlayerTeamScore_AddScore(player, f);
}
void W_SwitchWeapon_Force (entity e, Weapon w)
Definition at line 227 of file selection.qc.
Referenced by GiveFrags(), W_SwitchToOtherWeapon(), W_SwitchWeapon(), W_ThrowWeapon(), and W_WeaponFrame().
{
    e.cnt = PS(e).m_switchweapon.m_id;
    PS(e).m_switchweapon = wep;
    e.selectweapon = wep.m_id;
}
Variable Documentation
float checkrules_firstblood
Definition at line 40 of file g_damage.qh.
Referenced by Obituary().
entity damage_attacker
Definition at line 93 of file g_damage.qh.
Referenced by Damage().
float damage_gooddamage
Definition at line 44 of file g_damage.qh.
Referenced by Damage().
float damage_goodhits
Definition at line 43 of file g_damage.qh.
Referenced by Damage().
entity damage_inflictor
Definition at line 92 of file g_damage.qh.
Referenced by Damage().
entity damage_targ
Definition at line 91 of file g_damage.qh.
Referenced by Damage().
float dmg
Definition at line 31 of file g_damage.qh.
float dmg_edge
Definition at line 32 of file g_damage.qh.
float dmg_force
Definition at line 33 of file g_damage.qh.
float dmg_radius
Definition at line 34 of file g_damage.qh.
float dmg_team
Definition at line 46 of file g_damage.qh.
Referenced by PlayerPreThink(), and PutClientInServer().
entity fire_burner
Definition at line 108 of file g_damage.qh.
float fire_damagepersec
Definition at line 103 of file g_damage.qh.
float fire_deathtype
Definition at line 105 of file g_damage.qh.
float fire_endtime
Definition at line 104 of file g_damage.qh.
Referenced by PutClientInServer().
float fire_hitsound
Definition at line 107 of file g_damage.qh.
entity fire_owner
Definition at line 106 of file g_damage.qh.
entity GiveFrags_randomweapons
Definition at line 60 of file g_damage.qh.
Referenced by GiveFrags().
float istypefrag
Definition at line 51 of file g_damage.qh.
entity pusher
Definition at line 50 of file g_damage.qh.
float RadiusDamage_running
Definition at line 97 of file g_damage.qh.
Referenced by RadiusDamageForSource().
float taunt_soundtime
Definition at line 52 of file g_damage.qh.
Referenced by PlayerPreThink().
float teamkill_complain
Definition at line 47 of file g_damage.qh.
entity teamkill_soundsource
Definition at line 49 of file g_damage.qh.
float teamkill_soundtime
Definition at line 48 of file g_damage.qh.
Referenced by PlayerPreThink().
float w_deathtype
Definition at line 74 of file g_damage.qh.
float yoda
Definition at line 42 of file g_damage.qh.
Referenced by Damage(), and fireBullet().