Xonotic: server/g_subs.qh File Reference
server/g_subs.qh File Reference
Defines
#define G_SUBS_H
Functions
void SUB_NullThink ()
void () SUB_CalcMoveDone
spawnfunc (info_null)
void SUB_Friction ()
void SUB_VanishOrRemove (entity ent)
void SUB_SetFade_Think ()
void SUB_SetFade (entity ent, float when, float fadetime)
void SUB_CalcMoveDone ()
void SUB_CalcMove_controller_think ()
void SUB_CalcMove_controller_setbezier (entity controller, vector org, vector control, vector dest)
void SUB_CalcMove_controller_setlinear (entity controller, vector org, vector dest)
void SUB_CalcMove_Bezier (vector tcontrol, vector tdest, float tspeedtype, float tspeed, void() func)
void SUB_CalcMove (vector tdest, float tspeedtype, float tspeed, void() func)
void SUB_CalcMoveEnt (entity ent, vector tdest, float tspeedtype, float tspeed, void() func)
void SUB_CalcAngleMoveDone ()
void SUB_CalcAngleMove (vector destangle, float tspeedtype, float tspeed, void() func)
void SUB_CalcAngleMoveEnt (entity ent, vector destangle, float tspeedtype, float tspeed, void() func)
void main ()
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
float tracebox_inverted (vector v1, vector mi, vector ma, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
void traceline_inverted (vector v1, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
vector findbetterlocation (vector org, float mindist)
float angc (float a1, float a2)
float LOD_customize ()
void LOD_uncustomize ()
void LODmodel_attach ()
void ApplyMinMaxScaleAngles (entity e)
void SetBrushEntityModel ()
void SetBrushEntityModelNoLOD ()
void SetMovedir (entity this)
void InitTrigger ()
void InitSolidBSPTrigger ()
float InitMovingBrushTrigger ()
Variables
float friction
float platmovetype_turn
string lodtarget1
string lodtarget2
string lodmodel1
string lodmodel2
float lodmodelindex0
float lodmodelindex1
float lodmodelindex2
float loddistance1
float loddistance2
Define Documentation
#define G_SUBS_H
Definition at line 2 of file g_subs.qh.
Function Documentation
float angc (float a1, float a2)
Definition at line 33 of file math.qh.
{
    while (a1 > 180)
        a1 -= 360;
    while (a1 < -179)
        a1 += 360;
    while (a2 > 180)
        a2 -= 360;
    while (a2 < -179)
        a2 += 360;
    float a = a1 - a2;
    while (a > 180)
        a -= 360;
    while (a < -179)
        a += 360;
    return a;
}
void ApplyMinMaxScaleAngles (entity e)
Definition at line 327 of file g_subs.qc.
References max(), SELFPARAM, and vlen().
Referenced by SetBrushEntityModel(), and SetBrushEntityModelNoLOD().
{SELFPARAM();
    if(e.angles.x != 0 || e.angles.z != 0 || self.avelocity.x != 0 || self.avelocity.z != 0) // "weird" rotation
    {
        e.maxs = '1 1 1' * vlen(
            '1 0 0' * max(-e.mins.x, e.maxs.x) +
            '0 1 0' * max(-e.mins.y, e.maxs.y) +
            '0 0 1' * max(-e.mins.z, e.maxs.z)
        );
        e.mins = -e.maxs;
    }
    else if(e.angles.y != 0 || self.avelocity.y != 0) // yaw only is a bit better
    {
        e.maxs_x = vlen(
            '1 0 0' * max(-e.mins.x, e.maxs.x) +
            '0 1 0' * max(-e.mins.y, e.maxs.y)
        );
        e.maxs_y = e.maxs.x;
        e.mins_x = -e.maxs.x;
        e.mins_y = -e.maxs.x;
    }
    if(e.scale)
        setsize(e, e.mins * e.scale, e.maxs * e.scale);
    else
        setsize(e, e.mins, e.maxs);
}
vector findbetterlocation (vector org, float mindist)
Definition at line 204 of file g_subs.qc.
References trace_endpos, trace_fraction, vector(), and world.
{
    vector  loc;
    vector vec;
    float c, h;
    vec = mindist * '1 0 0';
    c = 0;
    while (c < 6)
    {
        traceline (org, org + vec, true, world);
        vec = vec * -1;
        if (trace_fraction < 1)
        {
            loc = trace_endpos;
            traceline (loc, loc + vec, true, world);
            if (trace_fraction >= 1)
                org = loc + vec;
        }
        if (c & 1)
        {
            h = vec.y;
            vec.y = vec.x;
            vec.x = vec.z;
            vec.z = h;
        }
        c = c + 1;
    }
    return org;
}
float InitMovingBrushTrigger ()
Definition at line 436 of file g_subs.qc.
References modelindex, MOVETYPE_PUSH, objerror, SELFPARAM, SetBrushEntityModel(), and SOLID_BSP.
{SELFPARAM();
// trigger angles are used for one-way touches.  An angle of 0 is assumed
// to mean no restrictions, so use a yaw of 360 instead.
    self.solid = SOLID_BSP;
    SetBrushEntityModel();
    self.movetype = MOVETYPE_PUSH;
    if(self.modelindex == 0)
    {
        objerror("InitMovingBrushTrigger: no brushes found!");
        return 0;
    }
    return 1;
}
void InitSolidBSPTrigger ()
Definition at line 424 of file g_subs.qc.
References MOVETYPE_NONE, SELFPARAM, SetBrushEntityModel(), SetMovedir(), and SOLID_BSP.
{SELFPARAM();
// trigger angles are used for one-way touches.  An angle of 0 is assumed
// to mean no restrictions, so use a yaw of 360 instead.
    SetMovedir(self);
    self.solid = SOLID_BSP;
    SetBrushEntityModel();
    self.movetype = MOVETYPE_NONE; // why was this PUSH? -div0
//  self.modelindex = 0;
    self.model = "";
}
void InitTrigger ()
Definition at line 412 of file g_subs.qc.
References MOVETYPE_NONE, SELFPARAM, SetBrushEntityModel(), SetMovedir(), and SOLID_TRIGGER.
Referenced by spawnfunc().
{SELFPARAM();
// trigger angles are used for one-way touches.  An angle of 0 is assumed
// to mean no restrictions, so use a yaw of 360 instead.
    SetMovedir(self);
    self.solid = SOLID_TRIGGER;
    SetBrushEntityModel();
    self.movetype = MOVETYPE_NONE;
    self.modelindex = 0;
    self.model = "";
}
float LOD_customize ()
Definition at line 236 of file g_subs.qc.
References autocvar_loddebug, lodmodelindex2, NearestPointOnBox(), other, SELFPARAM, vdist, and vector().
Referenced by LODmodel_attach().
{SELFPARAM();
    if(autocvar_loddebug)
    {
        int d = autocvar_loddebug;
        if(d == 1)
            self.modelindex = self.lodmodelindex0;
        else if(d == 2 || !self.lodmodelindex2)
            self.modelindex = self.lodmodelindex1;
        else // if(d == 3)
            self.modelindex = self.lodmodelindex2;
        return true;
    }
    // TODO csqc network this so it only gets sent once
    vector near_point = NearestPointOnBox(self, other.origin);
    if(vdist(near_point - other.origin, <, self.loddistance1))
        self.modelindex = self.lodmodelindex0;
    else if(!self.lodmodelindex2 || vdist(near_point - other.origin, <, self.loddistance2))
        self.modelindex = self.lodmodelindex1;
    else
        self.modelindex = self.lodmodelindex2;
    return true;
}
void LOD_uncustomize ()
Definition at line 262 of file g_subs.qc.
References SELFPARAM.
Referenced by LODmodel_attach().
{SELFPARAM();
    self.modelindex = self.lodmodelindex0;
}
void LODmodel_attach ()
Definition at line 267 of file g_subs.qc.
References autocvar_loddebug, entity(), find(), LOD_customize(), LOD_uncustomize(), loddistance1, loddistance2, lodmodel1, lodmodel2, lodmodelindex1, lodtarget1, lodtarget2, SELFPARAM, SetCustomizer(), targetname, vector(), and world.
Referenced by SetBrushEntityModel().
{SELFPARAM();
    entity e;
    if(!self.loddistance1)
        self.loddistance1 = 1000;
    if(!self.loddistance2)
        self.loddistance2 = 2000;
    self.lodmodelindex0 = self.modelindex;
    if(self.lodtarget1 != "")
    {
        e = find(world, targetname, self.lodtarget1);
        if(e)
        {
            self.lodmodel1 = e.model;
            remove(e);
        }
    }
    if(self.lodtarget2 != "")
    {
        e = find(world, targetname, self.lodtarget2);
        if(e)
        {
            self.lodmodel2 = e.model;
            remove(e);
        }
    }
    if(autocvar_loddebug < 0)
    {
        self.lodmodel1 = self.lodmodel2 = ""; // don't even initialize
    }
    if(self.lodmodel1 != "")
    {
        vector mi, ma;
        mi = self.mins;
        ma = self.maxs;
        precache_model(self.lodmodel1);
        _setmodel(self, self.lodmodel1);
        self.lodmodelindex1 = self.modelindex;
        if(self.lodmodel2 != "")
        {
            precache_model(self.lodmodel2);
            _setmodel(self, self.lodmodel2);
            self.lodmodelindex2 = self.modelindex;
        }
        self.modelindex = self.lodmodelindex0;
        setsize(self, mi, ma);
    }
    if(self.lodmodelindex1)
        if (!self.SendEntity)
            SetCustomizer(self, LOD_customize, LOD_uncustomize);
}
void main ()
Definition at line 21 of file g_subs.qc.
{
}
void SetBrushEntityModel ()
Definition at line 354 of file g_subs.qc.
References ApplyMinMaxScaleAngles(), InitializeEntity(), INITPRIO_FINDTARGET, LODmodel_attach(), maxs, mins, model, origin, SELFPARAM, and vector().
Referenced by InitMovingBrushTrigger(), InitSolidBSPTrigger(), and InitTrigger().
{SELFPARAM();
    if(self.model != "")
    {
        precache_model(self.model);
        if(self.mins != '0 0 0' || self.maxs != '0 0 0')
        {
            vector mi = self.mins;
            vector ma = self.maxs;
            _setmodel(self, self.model); // no precision needed
            setsize(self, mi, ma);
        }
        else
            _setmodel(self, self.model); // no precision needed
        InitializeEntity(self, LODmodel_attach, INITPRIO_FINDTARGET);
    }
    setorigin(self, self.origin);
    ApplyMinMaxScaleAngles(self);
}
void SetBrushEntityModelNoLOD ()
Definition at line 374 of file g_subs.qc.
References ApplyMinMaxScaleAngles(), maxs, mins, model, origin, SELFPARAM, and vector().
{SELFPARAM();
    if(self.model != "")
    {
        precache_model(self.model);
        if(self.mins != '0 0 0' || self.maxs != '0 0 0')
        {
            vector mi = self.mins;
            vector ma = self.maxs;
            _setmodel(self, self.model); // no precision needed
            setsize(self, mi, ma);
        }
        else
            _setmodel(self, self.model); // no precision needed
    }
    setorigin(self, self.origin);
    ApplyMinMaxScaleAngles(self);
}
void SetMovedir (entity this)
Definition at line 399 of file g_subs.qc.
References angles, movedir, normalize(), and v_forward.
Referenced by InitSolidBSPTrigger(), and InitTrigger().
{
    if(this.movedir != '0 0 0')
        this.movedir = normalize(this.movedir);
    else
    {
        makevectors(this.angles);
        this.movedir = v_forward;
    }
    this.angles = '0 0 0';
}
spawnfunc (info_null)
Definition at line 8 of file g_subs.qc.
{
    remove(self);
    // if anything breaks, tell the mapper to fix his map! info_null is meant to remove itself immediately.
}
void SUB_CalcAngleMove (vector destangle, float tspeedtype, float tspeed, void() func)
Definition at line 322 of file subs.qc.
References floor(), objerror, SELFPARAM, SUB_CalcAngleMoveDone(), TSPEED_END, TSPEED_LINEAR, TSPEED_START, TSPEED_TIME, vector(), and vlen().
Referenced by door_rotating_go_down(), door_rotating_go_up(), SUB_CalcAngleMoveEnt(), and train_wait().
{SELFPARAM();
    vector  delta;
    float   traveltime;
    if (!tspeed)
        objerror ("No speed is defined!");
    // take the shortest distance for the angles
    self.angles_x -= 360 * floor((self.angles_x - destangle_x) / 360 + 0.5);
    self.angles_y -= 360 * floor((self.angles_y - destangle_y) / 360 + 0.5);
    self.angles_z -= 360 * floor((self.angles_z - destangle_z) / 360 + 0.5);
    delta = destangle - self.angles;
    switch(tspeedtype)
    {
        default:
        case TSPEED_START:
        case TSPEED_END:
        case TSPEED_LINEAR:
            traveltime = vlen (delta) / tspeed;
            break;
        case TSPEED_TIME:
            traveltime = tspeed;
            break;
    }
    self.think1 = func;
    self.finalangle = destangle;
    self.SUB_THINK = SUB_CalcAngleMoveDone;
    if (traveltime < 0.1)
    {
        self.SUB_AVELOCITY = '0 0 0';
        self.SUB_NEXTTHINK = self.SUB_LTIME + 0.1;
        return;
    }
    self.SUB_AVELOCITY = delta * (1 / traveltime);
    self.SUB_NEXTTHINK = self.SUB_LTIME + traveltime;
}
void SUB_CalcAngleMoveDone ()
Definition at line 311 of file subs.qc.
References SELFPARAM.
Referenced by SUB_CalcAngleMove().
{SELFPARAM();
    // After rotating, set angle to exact final angle
    self.angles = self.finalangle;
    self.SUB_AVELOCITY = '0 0 0';
    self.SUB_NEXTTHINK = -1;
    if (self.think1)
        self.think1 ();
}
void SUB_CalcAngleMoveEnt (entity ent, vector destangle, float tspeedtype, float tspeed, void() func)
Definition at line 364 of file subs.qc.
References entity(), SELFPARAM, SUB_CalcAngleMove(), and WITH.
{SELFPARAM();
    WITH(entity, self, ent, SUB_CalcAngleMove (destangle, tspeedtype, tspeed, func));
}
void SUB_CalcMove (vector tdest, float tspeedtype, float tspeed, void() func)
Definition at line 247 of file subs.qc.
References objerror, platmovetype_end, platmovetype_start, SELFPARAM, SUB_CalcMove_Bezier(), SUB_CalcMoveDone(), TSPEED_END, TSPEED_LINEAR, TSPEED_START, TSPEED_TIME, vector(), and vlen().
Referenced by door_go_down(), door_go_up(), plat_go_down(), plat_go_up(), SUB_CalcMoveEnt(), and train_next().
{SELFPARAM();
    vector  delta;
    float   traveltime;
    if (!tspeed)
        objerror ("No speed is defined!");
    self.think1 = func;
    self.finaldest = tdest;
    self.SUB_THINK = SUB_CalcMoveDone;
    if (tdest == self.SUB_ORIGIN)
    {
        self.SUB_VELOCITY = '0 0 0';
        self.SUB_NEXTTHINK = self.SUB_LTIME + 0.1;
        return;
    }
    delta = tdest - self.SUB_ORIGIN;
    switch(tspeedtype)
    {
        default:
        case TSPEED_START:
        case TSPEED_END:
        case TSPEED_LINEAR:
            traveltime = vlen (delta) / tspeed;
            break;
        case TSPEED_TIME:
            traveltime = tspeed;
            break;
    }
    // Very short animations don't really show off the effect
    // of controlled animation, so let's just use linear movement.
    // Alternatively entities can choose to specify non-controlled movement.
        // The only currently implemented alternative movement is linear (value 1)
    if (traveltime < 0.15 || (self.platmovetype_start == 1 && self.platmovetype_end == 1)) // is this correct?
    {
        self.SUB_VELOCITY = delta * (1/traveltime); // QuakeC doesn't allow vector/float division
        self.SUB_NEXTTHINK = self.SUB_LTIME + traveltime;
        return;
    }
    // now just run like a bezier curve...
    SUB_CalcMove_Bezier((self.SUB_ORIGIN + tdest) * 0.5, tdest, tspeedtype, tspeed, func);
}
void SUB_CalcMove_Bezier (vector tcontrol, vector tdest, float tspeedtype, float tspeed, void() func)
Definition at line 189 of file subs.qc.
References entity(), objerror, owner, SELFPARAM, setself, SUB_CalcMove_controller_setbezier(), SUB_CalcMove_controller_think(), SUB_CalcMoveDone(), SUB_NullThink(), time, TSPEED_END, TSPEED_LINEAR, TSPEED_START, TSPEED_TIME, and vlen().
Referenced by SUB_CalcMove(), and train_next().
{SELFPARAM();
    float   traveltime;
    entity controller;
    if (!tspeed)
        objerror ("No speed is defined!");
    self.think1 = func;
    self.finaldest = tdest;
    self.SUB_THINK = SUB_CalcMoveDone;
    switch(tspeedtype)
    {
        default:
        case TSPEED_START:
            traveltime = 2 * vlen(tcontrol - self.SUB_ORIGIN) / tspeed;
            break;
        case TSPEED_END:
            traveltime = 2 * vlen(tcontrol - tdest)       / tspeed;
            break;
        case TSPEED_LINEAR:
            traveltime = vlen(tdest - self.SUB_ORIGIN)        / tspeed;
            break;
        case TSPEED_TIME:
            traveltime = tspeed;
            break;
    }
    if (traveltime < 0.1) // useless anim
    {
        self.SUB_VELOCITY = '0 0 0';
        self.SUB_NEXTTHINK = self.SUB_LTIME + 0.1;
        return;
    }
    controller = new(SUB_CalcMove_controller);
    controller.owner = self;
    controller.platmovetype = self.platmovetype;
    controller.platmovetype_start = self.platmovetype_start;
    controller.platmovetype_end = self.platmovetype_end;
    SUB_CalcMove_controller_setbezier(controller, self.SUB_ORIGIN, tcontrol, tdest);
    controller.finaldest = (tdest + '0 0 0.125'); // where do we want to end? Offset to overshoot a bit.
    controller.animstate_starttime = time;
    controller.animstate_endtime = time + traveltime;
    controller.think = SUB_CalcMove_controller_think;
    controller.think1 = self.SUB_THINK;
    // the thinking is now done by the controller
    self.SUB_THINK = SUB_NullThink; // for PushMove
    self.SUB_NEXTTHINK = self.SUB_LTIME + traveltime;
    // invoke controller
    setself(controller);
    self.think();
    setself(self.owner);
}
void SUB_CalcMove_controller_setbezier (entity controller, vector org, vector control, vector dest)
Definition at line 155 of file subs.qc.
Referenced by SUB_CalcMove_Bezier().
{
    // 0 * (1-t) * (1-t) + 2 * control * t * (1-t) + destin * t * t
    // 2 * control * t - 2 * control * t * t + destin * t * t
    // 2 * control * t + (destin - 2 * control) * t * t
    setorigin(controller, org);
    control -= org;
    destin -= org;
    controller.destvec = 2 * control; // control point
    controller.destvec2 = destin - 2 * control; // quadratic part required to reach end point
    // also: initial d/dphasepos origin = 2 * control, final speed = 2 * (destin - control)
}
void SUB_CalcMove_controller_setlinear (entity controller, vector org, vector dest)
Definition at line 170 of file subs.qc.
{
    // 0 * (1-t) * (1-t) + 2 * control * t * (1-t) + destin * t * t
    // 2 * control * t - 2 * control * t * t + destin * t * t
    // 2 * control * t + (destin - 2 * control) * t * t
    setorigin(controller, org);
    destin -= org;
    controller.destvec = destin; // end point
    controller.destvec2 = '0 0 0';
}
void SUB_CalcMove_controller_think ()
Definition at line 95 of file subs.qc.
References animstate_endtime, cubic_speedfunc(), entity(), floor(), owner, platmovetype_end, platmovetype_start, SELFPARAM, setself, time, vectoangles(), and vector().
Referenced by SUB_CalcMove_Bezier().
{SELFPARAM();
    entity oldself;
    float traveltime;
    float phasepos;
    float nexttick;
    vector delta;
    vector delta2;
    vector veloc;
    vector angloc;
    vector nextpos;
    delta = self.destvec;
    delta2 = self.destvec2;
    if(time < self.animstate_endtime)
    {
        nexttick = time + PHYS_INPUT_FRAMETIME;
        traveltime = self.animstate_endtime - self.animstate_starttime;
        phasepos = (nexttick - self.animstate_starttime) / traveltime; // range: [0, 1]
        phasepos = cubic_speedfunc(self.platmovetype_start, self.platmovetype_end, phasepos);
        nextpos = self.origin + (delta * phasepos) + (delta2 * phasepos * phasepos);
        // derivative: delta + 2 * delta2 * phasepos (e.g. for angle positioning)
        if(self.owner.platmovetype_turn)
        {
            vector destangle;
            destangle = delta + 2 * delta2 * phasepos;
            destangle = vectoangles(destangle);
            destangle_x = -destangle_x; // flip up / down orientation
            // take the shortest distance for the angles
            vector v = SUB_ANGLES(self.owner);
            v.x -= 360 * floor((v.x - destangle_x) / 360 + 0.5);
            v.y -= 360 * floor((v.y - destangle_y) / 360 + 0.5);
            v.z -= 360 * floor((v.z - destangle_z) / 360 + 0.5);
            SUB_ANGLES(self.owner) = v;
            angloc = destangle - SUB_ANGLES(self.owner);
            angloc = angloc * (1 / PHYS_INPUT_FRAMETIME); // so it arrives for the next frame
            self.owner.SUB_AVELOCITY = angloc;
        }
        if(nexttick < self.animstate_endtime)
            veloc = nextpos - self.owner.SUB_ORIGIN;
        else
            veloc = self.finaldest - self.owner.SUB_ORIGIN;
        veloc = veloc * (1 / PHYS_INPUT_FRAMETIME); // so it arrives for the next frame
        self.owner.SUB_VELOCITY = veloc;
        self.nextthink = nexttick;
    }
    else
    {
        // derivative: delta + 2 * delta2 (e.g. for angle positioning)
        oldself = self;
        self.owner.SUB_THINK = self.think1;
        setself(self.owner);
        remove(oldself);
        self.SUB_THINK();
    }
}
void SUB_CalcMoveDone ()
Definition at line 83 of file subs.qc.
References finaldest, and SELFPARAM.
Referenced by SUB_CalcMove(), and SUB_CalcMove_Bezier().
{SELFPARAM();
    // After moving, set origin to exact final destination
    SUB_SETORIGIN (self, self.finaldest);
    self.SUB_VELOCITY = '0 0 0';
    self.SUB_NEXTTHINK = -1;
    if (self.think1)
        self.think1 ();
}
void SUB_CalcMoveEnt (entity ent, vector tdest, float tspeedtype, float tspeed, void() func)
Definition at line 296 of file subs.qc.
References entity(), SELFPARAM, SUB_CalcMove(), and WITH.
{SELFPARAM();
    WITH(entity, self, ent, SUB_CalcMove(tdest, tspeedtype, tspeed, func));
}
void SUB_Friction ()
Definition at line 15 of file subs.qc.
References FL_ONGROUND, frametime, SELFPARAM, and time.
{SELFPARAM();
    self.SUB_NEXTTHINK = time;
    if(self.SUB_FLAGS & FL_ONGROUND)
        self.SUB_VELOCITY = self.SUB_VELOCITY * (1 - frametime * self.friction);
}
void SUB_NullThink ()
Definition at line 1 of file subs.qc.
Referenced by SUB_CalcMove_Bezier().
{ }
void SUB_SetFade (entity ent, float when, float fadetime)
Definition at line 68 of file subs.qc.
References SUB_SetFade_Think().
Referenced by Monster_Dead_Fade(), monster_dropitem(), PlayerDamage(), Portal_Remove(), respawn(), and thrown_wep_think().
{
    ent.fade_rate = 1/fading_time;
    ent.SUB_THINK = SUB_SetFade_Think;
    ent.SUB_NEXTTHINK = when;
}
void SUB_SetFade_Think ()
Definition at line 48 of file subs.qc.
References alpha, frametime, SELFPARAM, SUB_SetFade_Think(), SUB_VanishOrRemove(), and time.
Referenced by SUB_SetFade(), and SUB_SetFade_Think().
{SELFPARAM();
    if(self.alpha == 0)
        self.alpha = 1;
    self.SUB_THINK = SUB_SetFade_Think;
    self.SUB_NEXTTHINK = time;
    self.alpha -= frametime * self.fade_rate;
    if (self.alpha < 0.01)
        SUB_VanishOrRemove(self);
    else
        self.SUB_NEXTTHINK = time;
}
void SUB_VanishOrRemove (entity ent)
Definition at line 29 of file subs.qc.
References IS_CLIENT.
Referenced by SUB_SetFade_Think(), and thrown_wep_think().
{
    if (IS_CLIENT(ent))
    {
        // vanish
        ent.alpha = -1;
        ent.effects = 0;
#ifdef SVQC
        ent.glow_size = 0;
        ent.pflags = 0;
#endif
    }
    else
    {
        // remove
        remove (ent);
    }
}
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 89 of file g_subs.qc.
References autocvar_g_antilag, and tracebox_antilag_force_wz().
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
{
    if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
        lag = 0;
    tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, false);
}
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
Definition at line 36 of file g_subs.qc.
References antilag_restore(), antilag_takeback(), DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, FL_MONSTER, flags, FOREACH_CLIENT, FOREACH_ENTITY_FLAGS, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, time, and WarpZone_TraceBox().
Referenced by tracebox_antilag(), traceline_antilag_force(), WarpZone_tracebox_antilag(), and WarpZone_traceline_antilag_force().
{
    // check whether antilagged traces are enabled
    if (lag < 0.001)
        lag = 0;
    if (!IS_REAL_CLIENT(forent))
        lag = 0; // only antilag for clients
    // change shooter to SOLID_BBOX so the shot can hit corpses
    int oldsolid = source.dphitcontentsmask;
    if(source)
        source.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
    if (lag)
    {
        // take players back into the past
        FOREACH_CLIENT(IS_PLAYER(it) && it != forent, LAMBDA(antilag_takeback(it, time - lag)));
        FOREACH_ENTITY_FLAGS(flags, FL_MONSTER, LAMBDA(
            if(it != forent)
                antilag_takeback(it, time - lag);
        ));
    }
    // do the trace
    if(wz)
        WarpZone_TraceBox (v1, mi, ma, v2, nomonst, forent);
    else
        tracebox (v1, mi, ma, v2, nomonst, forent);
    // restore players to current positions
    if (lag)
    {
        FOREACH_CLIENT(IS_PLAYER(it) && it != forent, LAMBDA(antilag_restore(it)));
        FOREACH_ENTITY_FLAGS(flags, FL_MONSTER, LAMBDA(
            if(it != forent)
                antilag_restore(it);
        ));
    }
    // restore shooter solid type
    if(source)
        source.dphitcontentsmask = oldsolid;
}
float tracebox_inverted (vector v1, vector mi, vector ma, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
Definition at line 112 of file g_subs.qc.
References entity(), ftos(), LOG_TRACE(), normalize(), trace_endpos, trace_ent, trace_fraction, trace_startsolid, vector(), vlen(), and vtos().
Referenced by FullTraceFraction(), and traceline_inverted().
{
    vector pos, dir, t;
    float nudge;
    entity stopentity;
    //nudge = 2 * cvar("collision_impactnudge"); // why not?
    nudge = 0.5;
    dir = normalize(v2 - v1);
    pos = v1 + dir * nudge;
    float c;
    c = 0;
    for (;;)
    {
        if(pos * dir >= v2 * dir)
        {
            // went too far
            trace_fraction = 1;
            trace_endpos = v2;
            return c;
        }
        tracebox(pos, mi, ma, v2, nomonsters, forent);
        ++c;
        if(c == 50)
        {
            LOG_TRACE("HOLY SHIT! When tracing from ", vtos(v1), " to ", vtos(v2), "\n");
            LOG_TRACE("  Nudging gets us nowhere at ", vtos(pos), "\n");
            LOG_TRACE("  trace_endpos is ", vtos(trace_endpos), "\n");
            LOG_TRACE("  trace distance is ", ftos(vlen(pos - trace_endpos)), "\n");
        }
        stopentity = trace_ent;
        if(trace_startsolid)
        {
            // we started inside solid.
            // then trace from endpos to pos
            t = trace_endpos;
            tracebox(t, mi, ma, pos, nomonsters, forent);
            ++c;
            if(trace_startsolid)
            {
                // t is still inside solid? bad
                // force advance, then, and retry
                pos = t + dir * nudge;
                // but if we hit an entity, stop RIGHT before it
                if(stopatentity && stopentity && stopentity != ignorestopatentity)
                {
                    trace_ent = stopentity;
                    trace_endpos = t;
                    trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
                    return c;
                }
            }
            else
            {
                // we actually LEFT solid!
                trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
                return c;
            }
        }
        else
        {
            // pos is outside solid?!? but why?!? never mind, just return it.
            trace_endpos = pos;
            trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
            return c;
        }
    }
}
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 83 of file g_subs.qc.
{
    if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
        lag = 0;
    traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
}
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 79 of file g_subs.qc.
References tracebox_antilag_force_wz().
Referenced by traceline_antilag(), W_HitPlotAnalysis(), and W_SetupShot_Dir_ProjectileSize_Range().
{
    tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, false);
}
void traceline_inverted (vector v1, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
Definition at line 190 of file g_subs.qc.
References tracebox_inverted().
Referenced by fireBullet().
{
    tracebox_inverted(v1, '0 0 0', '0 0 0', v2, nomonsters, forent, stopatentity, ignorestopatentity);
}
void ()
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 105 of file g_subs.qc.
References autocvar_g_antilag, and tracebox_antilag_force_wz().
{
    if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
        lag = 0;
    tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, true);
}
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 99 of file g_subs.qc.
{
    if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
        lag = 0;
    WarpZone_traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
}
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 95 of file g_subs.qc.
References tracebox_antilag_force_wz().
Referenced by WarpZone_traceline_antilag().
{
    tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, true);
}
Variable Documentation
float friction
Definition at line 19 of file g_subs.qh.
float loddistance1
Definition at line 140 of file g_subs.qh.
Referenced by Ent_Wall_Draw(), g_clientmodel_genericsendentity(), LODmodel_attach(), and NET_HANDLE().
float loddistance2
Definition at line 141 of file g_subs.qh.
string lodmodel1
Definition at line 135 of file g_subs.qh.
Referenced by LODmodel_attach().
string lodmodel2
Definition at line 136 of file g_subs.qh.
Referenced by LODmodel_attach().
float lodmodelindex0
Definition at line 137 of file g_subs.qh.
float lodmodelindex1
Definition at line 138 of file g_subs.qh.
float lodmodelindex2
Definition at line 139 of file g_subs.qh.
string lodtarget1
Definition at line 133 of file g_subs.qh.
Referenced by LODmodel_attach().
string lodtarget2
Definition at line 134 of file g_subs.qh.
Referenced by LODmodel_attach().
float platmovetype_turn
Definition at line 52 of file g_subs.qh.