Xonotic: server/mutators/mutator/gamemode_keepaway.qc File Reference
server/mutators/mutator/gamemode_keepaway.qc File Reference
Defines
#define GAMEMODE_KEEPAWAY_H
Functions
void ka_Initialize ()
REGISTER_MUTATOR (ka, false)
void () havocbot_role_ka_carrier
void ka_DropEvent (entity plyr)
Variables
entity ka_ball
const float SP_KEEPAWAY_PICKUPS = 4
const float SP_KEEPAWAY_CARRIERKILLS = 5
const float SP_KEEPAWAY_BCTIME = 6
Define Documentation
#define GAMEMODE_KEEPAWAY_H
Definition at line 2 of file gamemode_keepaway.qc.
Function Documentation
void ka_DropEvent (entity plyr)
void ka_Initialize ()
Referenced by REGISTER_MUTATOR().
REGISTER_MUTATOR (ka , false)
Definition at line 6 of file gamemode_keepaway.qc.
References error(), ka_Initialize(), LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, and time.
{
    MUTATOR_ONADD
    {
        if (time > 1) // game loads at time 1
            error("This is a game type and it cannot be added at runtime.");
        ka_Initialize();
    }
    MUTATOR_ONROLLBACK_OR_REMOVE
    {
        // we actually cannot roll back ka_Initialize here
        // BUT: we don't need to! If this gets called, adding always
        // succeeds.
    }
    MUTATOR_ONREMOVE
    {
        LOG_INFO("This is a game type and it cannot be removed at runtime.");
        return -1;
    }
    return 0;
}
void ()
Variable Documentation
entity ka_ball
Definition at line 32 of file gamemode_keepaway.qc.
const float SP_KEEPAWAY_BCTIME = 6
Definition at line 36 of file gamemode_keepaway.qc.
const float SP_KEEPAWAY_CARRIERKILLS = 5
Definition at line 35 of file gamemode_keepaway.qc.
const float SP_KEEPAWAY_PICKUPS = 4
Definition at line 34 of file gamemode_keepaway.qc.