Xonotic: common/command/generic.qh File Reference
common/command/generic.qh File Reference
#include "../constants.qh"
Defines
#define COMMAND_GENERIC_H
#define CMD_Write(s) fputs(fh, s)
#define CMD_Write_Alias(execute, command, description) CMD_Write(sprintf("alias %-20s \"%-13s %-20s ${* ?}\" // %s\n", command, execute, command, description))
Functions
void GenericCommand_macro_help ()
float GenericCommand_macro_command (float argc, string command)
float GenericCommand_macro_usage (float argc)
void GenericCommand_macro_write_aliases (float fh)
float GenericCommand (string command)
string GetProgramCommandPrefix ()
void Curl_URI_Get_Callback (int id, float status, string data)
Variables
int curl_uri_get_pos
float curl_uri_get_exec [URI_GET_CURL_END-URI_GET_CURL+1]
string curl_uri_get_cvar [URI_GET_CURL_END-URI_GET_CURL+1]
Define Documentation
#define CMD_Write (s) fputs(fh, s)
Definition at line 28 of file generic.qh.
Referenced by GENERIC_COMMAND().
#define CMD_Write_Alias (execute, command, description) CMD_Write(sprintf("alias %-20s \"%-13s %-20s ${* ?}\" // %s\n", command, execute, command, description))
Definition at line 29 of file generic.qh.
Referenced by CommonCommand_macro_write_aliases(), GameCommand_macro_write_aliases(), GenericCommand_macro_write_aliases(), and LocalCommand_macro_write_aliases().
#define COMMAND_GENERIC_H
Definition at line 2 of file generic.qh.
Function Documentation
void Curl_URI_Get_Callback (int id, float status, string data)
Definition at line 45 of file generic.qc.
References curl_uri_get_cvar, curl_uri_get_exec, cvar_set(), localcmd, LOG_INFO, LOG_TRACEF, strunzone(), and URI_GET_CURL.
Referenced by URI_Get_Callback().
{
    int i = id - URI_GET_CURL;
    float do_exec = curl_uri_get_exec[i];
    string do_cvar = curl_uri_get_cvar[i];
    if(status != 0)
    {
        LOG_TRACEF("error: status is %d\n", status);
        if(do_cvar)
            strunzone(do_cvar);
        return;
    }
    if(do_exec)
        localcmd(data);
    if(do_cvar)
    {
        cvar_set(do_cvar, data);
        strunzone(do_cvar);
    }
    if(!do_exec)
        if (!do_cvar)
            LOG_INFO(data);
}
float GenericCommand (string command)
Definition at line 582 of file generic.qc.
References argv(), argv_end_index, argv_start_index, floor(), GenericCommand_macro_command(), GenericCommand_markup(), hsl_to_rgb(), localcmd, max(), n, random(), rgb_to_hexcolor(), s, s2, strcat(), strlen(), substring(), tokenize_console, and vector().
Referenced by GameCommand().
{
    float argc = tokenize_console(command);
    float n, j, f, i;
    string s, s2, c;
    vector rgb;
    // Guide for working with argc arguments by example:
    // argc:   1    - 2      - 3     - 4
    // argv:   0    - 1      - 2     - 3
    // cmd     vote - master - login - password
    if(GenericCommand_macro_command(argc, command)) // continue as usual and scan for normal commands
    {
        return true; // handled by one of the above GenericCommand_* functions
    }
    else if(argc >= 3 && argv(0) == "red")
    {
        s = substring(command, argv_start_index(2), argv_end_index(-1) - argv_start_index(2));
        localcmd(strcat(argv(1), " ", GenericCommand_markup(s)));
        return true;
    }
    else if(argc >= 3 && crc16(0, argv(0)) == 38566 && crc16(0, strcat(argv(0), argv(0), argv(0))) == 59830)
    {
        // other test case
        s = strconv(2, 0, 0, substring(command, argv_start_index(2), argv_end_index(-1) - argv_start_index(2)));
        n = floor(random() * 6 + 2);
        s2 = "";
        for(i = 0; i < n; ++i)
        {
            s2 = strcat(s2, "AH");
        }
        if(random() < 0.1)
            s2 = strcat(substring(s2, 1, strlen(s2) - 1), "A");
        if(s == "")
            s = s2;
        else
            if(random() < 0.8)
                s = strcat(s, " ", s2);
            else
                s = strcat(s2, " ", s);
        s2 = substring(s, strlen(s) - 2, 2);
        if(s2 == "AH" || s2 == "AY")
            s = strcat(s, "))");
        else
            s = strcat(s, " ))");
        if(random() < 0.1)
            s = substring(s, 0, strlen(s) - 1);
        if(random() < 0.1)
            s = strconv(1, 0, 0, s);
        localcmd(strcat(argv(1), " ", s));
        return true;
    }
    else if(argc >= 3 && crc16(0, argv(0)) == 3826 && crc16(0, strcat(argv(0), argv(0), argv(0))) == 55790)
    {
        // test case for terencehill's color codes
        s = strdecolorize(substring(command, argv_start_index(2), argv_end_index(-1) - argv_start_index(2)));
        s2 = "";
        n = strlen(s);
        j = ((6 * max(1, floor(strlen(s)/32 + random() * 2 - 1))) / n) * (1 - 2 * (random() > 0.5));
        f = random() * 6;
        for(i = 0; i < n; ++i)
        {
            c = substring(s, i, 1);
            if(c == ";")
                c = ":";
            else if(c == "^")
            {
                c = "^^";
                if(substring(s, i+1, 1) == "^")
                    ++i;
            }
            if(c != " ")
            {
                rgb = hsl_to_rgb('1 0 0' * (j * i + f) + '0 1 .5');
                c = strcat(rgb_to_hexcolor(rgb), c);
            }
            s2 = strcat(s2, c);
        }
        localcmd(strcat(argv(1), " ", s2));
        return true;
    }
    return false;
}
float GenericCommand_macro_command (float argc, string command)
Definition at line 551 of file generic.qc.
References argv(), CMD_REQUEST_COMMAND, FOREACH, LAMBDA, NULL, and strtolower().
Referenced by GenericCommand().
{
    string c = strtolower(argv(0));
    FOREACH(GENERIC_COMMANDS, it.m_name == c, LAMBDA(
        it.m_invokecmd(CMD_REQUEST_COMMAND, NULL, argc, command);
        return true;
    ));
    return false;
}
void GenericCommand_macro_help ()
Definition at line 546 of file generic.qc.
References FOREACH, LAMBDA, and LOG_INFOF.
Referenced by GameCommand().
{
    FOREACH(GENERIC_COMMANDS, true, LAMBDA(LOG_INFOF("  ^2%s^7: %s\n", it.m_name, it.m_description)));
}
float GenericCommand_macro_usage (float argc)
Definition at line 561 of file generic.qc.
References argv(), CMD_REQUEST_USAGE, FOREACH, LAMBDA, NULL, and strtolower().
Referenced by GameCommand().
{
    string c = strtolower(argv(1));
    FOREACH(GENERIC_COMMANDS, it.m_name == c, LAMBDA(
        it.m_invokecmd(CMD_REQUEST_USAGE, NULL, argc, "");
        return true;
    ));
    return false;
}
void GenericCommand_macro_write_aliases (float fh)
Definition at line 571 of file generic.qc.
References CMD_Write_Alias, FOREACH, and LAMBDA.
Referenced by GENERIC_COMMAND().
{
    FOREACH(GENERIC_COMMANDS, true, LAMBDA(CMD_Write_Alias("qc_cmd_svmenu", it.m_name, it.m_description)));
}
string GetProgramCommandPrefix ()
Definition at line 31 of file generic.qc.
Referenced by GENERIC_COMMAND(), GenericCommand_addtolist(), GenericCommand_maplist(), GenericCommand_nextframe(), GenericCommand_qc_curl(), GenericCommand_removefromlist(), GenericCommand_restartnotifs(), GenericCommand_rpn(), GenericCommand_runtest(), GenericCommand_settemp(), and GenericCommand_settemp_restore().
{
    #ifdef SVQC
    return "sv_cmd";
    #endif
    #ifdef CSQC
    return "cl_cmd";
    #endif
    #ifdef MENUQC
    return "menu_cmd";
    #endif
}
Variable Documentation
string curl_uri_get_cvar[URI_GET_CURL_END-URI_GET_CURL+1]
Definition at line 35 of file generic.qh.
Referenced by Curl_URI_Get_Callback(), and GenericCommand_qc_curl().
float curl_uri_get_exec[URI_GET_CURL_END-URI_GET_CURL+1]
Definition at line 34 of file generic.qh.
Referenced by Curl_URI_Get_Callback(), and GenericCommand_qc_curl().
int curl_uri_get_pos
Definition at line 33 of file generic.qh.
Referenced by GenericCommand_qc_curl().