Xonotic: server/bot/havocbot/scripting.qh File Reference
server/bot/havocbot/scripting.qh File Reference
Defines
#define HAVOCBOT_SCRIPTING_H
Functions
void bot_clearqueue (entity bot)
Define Documentation
#define HAVOCBOT_SCRIPTING_H
Definition at line 2 of file scripting.qh.
Function Documentation
void bot_clearqueue (entity bot)
Definition at line 12 of file scripting.qc.
References LOG_TRACE().
Referenced by bot_clientdisconnect(), bot_cmd_if(), bot_dequeuecommand(), and bot_resetqueues().
{
    if(!bot.bot_cmdqueuebuf_allocated)
        return;
    buf_del(bot.bot_cmdqueuebuf);
    bot.bot_cmdqueuebuf_allocated = false;
    LOG_TRACE("bot ", bot.netname, " queue cleared\n");
}