Xonotic: lib/csqcmodel/common.qh File Reference
lib/csqcmodel/common.qh File Reference
#include <common/csqcmodel_settings.qh>
Defines
#define LIB_CSQCMODEL_COMMON_H
#define ALLPROPERTIES_COMMON
#define ALLPROPERTIES ALLPROPERTIES_COMMON
Variables
noref string csqcmodel_license
vector glowmod
vector view_ofs
int frame
float frame1time
int frame2
float frame2time
float lerpfrac
const int CSQCMODEL_PROPERTY_FRAME = BIT(23)
const int CSQCMODEL_PROPERTY_TELEPORTED = BIT(22)
const int CSQCMODEL_PROPERTY_MODELINDEX = BIT(21)
const int CSQCMODEL_PROPERTY_ORIGIN = BIT(20)
const int CSQCMODEL_PROPERTY_YAW = BIT(19)
const int CSQCMODEL_PROPERTY_PITCHROLL = BIT(18)
const int CSQCMODEL_PROPERTY_FRAME2 = BIT(17)
const int CSQCMODEL_PROPERTY_LERPFRAC = BIT(16)
const int CSQCMODEL_PROPERTY_SIZE = BIT(15)
Define Documentation
#define ALLPROPERTIES ALLPROPERTIES_COMMON
Definition at line 95 of file common.qh.
Referenced by CSQCModel_CheckUpdate(), CSQCModel_Send(), and NET_HANDLE().
#define ALLPROPERTIES_COMMON
Value:
CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_FRAME, int, ReadByte, WriteByte, frame) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_MODELINDEX, int, ReadShort, WriteShort, modelindex) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_ORIGIN, float, ReadCoord, WriteCoord, origin_x) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_ORIGIN, float, ReadCoord, WriteCoord, origin_y) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_ORIGIN, float, ReadCoord, WriteCoord, origin_z) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, mins_x) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, mins_y) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, mins_z) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, maxs_x) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, maxs_y) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_SIZE, float, ReadShort, WriteShort, maxs_z) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_PITCHROLL, float, ReadAngle, WriteAngle, angles_x) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_YAW, float, ReadAngle, WriteAngle, angles_y) \
    CSQCMODEL_PROPERTY(CSQCMODEL_PROPERTY_PITCHROLL, float, ReadAngle, WriteAngle, angles_z) \
    CSQCMODEL_EXTRAPROPERTIES
Definition at line 67 of file common.qh.
#define LIB_CSQCMODEL_COMMON_H
Definition at line 23 of file common.qh.
Variable Documentation
noref string csqcmodel_license
Initial value:
"\
Copyright (c) 2011 Rudolf Polzer\
\
Permission is hereby granted, free of charge, to any person obtaining a copy\
of this software and associated documentation files (the \"Software\"), to\
deal in the Software without restriction, including without limitation the\
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or\
sell copies of the Software, and to permit persons to whom the Software is\
furnished to do so, subject to the following conditions:\
\
The above copyright notice and this permission notice shall be included in\
all copies or substantial portions of the Software.\
\
THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS\
IN THE SOFTWARE.\
"
Definition at line 27 of file common.qh.
const int CSQCMODEL_PROPERTY_FRAME = BIT(23)
Definition at line 57 of file common.qh.
Referenced by CSQCModel_CheckUpdate(), CSQCModel_Hook_PreDraw(), CSQCModel_InterpolateAnimation_1To2_Note(), CSQCModel_InterpolateAnimation_1To2_PreNote(), CSQCModel_InterpolateAnimation_2To4_Note(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
const int CSQCMODEL_PROPERTY_FRAME2 = BIT(17)
Definition at line 63 of file common.qh.
Referenced by CSQCModel_CheckUpdate(), CSQCModel_Hook_PreDraw(), CSQCModel_InterpolateAnimation_2To4_Note(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
const int CSQCMODEL_PROPERTY_LERPFRAC = BIT(16)
Definition at line 64 of file common.qh.
Referenced by CSQCModel_Hook_PreDraw(), CSQCModel_InterpolateAnimation_2To4_Note(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
const int CSQCMODEL_PROPERTY_MODELINDEX = BIT(21)
Definition at line 59 of file common.qh.
Referenced by NET_HANDLE().
const int CSQCMODEL_PROPERTY_ORIGIN = BIT(20)
Definition at line 60 of file common.qh.
Referenced by CSQCModel_CheckUpdate().
const int CSQCMODEL_PROPERTY_PITCHROLL = BIT(18)
Definition at line 62 of file common.qh.
const int CSQCMODEL_PROPERTY_SIZE = BIT(15)
Definition at line 65 of file common.qh.
const int CSQCMODEL_PROPERTY_TELEPORTED = BIT(22)
Definition at line 58 of file common.qh.
Referenced by CSQCModel_CheckUpdate(), and NET_HANDLE().
const int CSQCMODEL_PROPERTY_YAW = BIT(19)
Definition at line 61 of file common.qh.
int frame
Definition at line 51 of file common.qh.
float frame1time
Definition at line 52 of file common.qh.
int frame2
Definition at line 53 of file common.qh.
float frame2time
Definition at line 54 of file common.qh.
vector glowmod
Definition at line 49 of file common.qh.
float lerpfrac
Definition at line 55 of file common.qh.
vector view_ofs
Definition at line 50 of file common.qh.