Xonotic: common/mutators/mutator/buffs/module.inc File Reference
common/mutators/mutator/buffs/module.inc File Reference
#include "all.qc"
Functions
string BUFF_NAME (int i)
REGISTER_MUTATOR (buffs_flight, true)
MUTATOR_HOOKFUNCTION (buffs_flight, IsFlying)
REGISTER_MUTATOR (cl_buffs, true)
MUTATOR_HOOKFUNCTION (cl_buffs, HUD_Powerups_add)
MUTATOR_HOOKFUNCTION (cl_buffs, WP_Format)
Function Documentation
string BUFF_NAME (int i)
Definition at line 8 of file module.inc.
References Buffs_from, and rgb_to_hexcolor().
{
    Buff b = Buffs_from(i);
    return sprintf("%s%s", rgb_to_hexcolor(b.m_color), b.m_prettyName);
}
MUTATOR_HOOKFUNCTION (buffs_flight , IsFlying)
Definition at line 16 of file module.inc.
References BUFFS_STAT, entity(), and MUTATOR_ARGV.
{
    noref entity e = MUTATOR_ARGV(0, entity);
    return BUFFS_STAT(e) & BUFF_FLIGHT.m_itemid;
}
MUTATOR_HOOKFUNCTION (cl_buffs , HUD_Powerups_add)
Definition at line 25 of file module.inc.
References addPowerupItem(), bound(), FOREACH, LAMBDA, strcat(), and time.
{
    int allBuffs = STAT(BUFFS);
    FOREACH(Buffs, it.m_itemid & allBuffs, LAMBDA(
        addPowerupItem(it.m_prettyName, strcat("buff_", it.m_name), it.m_color, bound(0, STAT(BUFF_TIME) - time, 99), 60);
    ));
}
MUTATOR_HOOKFUNCTION (cl_buffs , WP_Format)
Definition at line 32 of file module.inc.
References Buffs_from, entity(), MUTATOR_ARGV, s, vector(), and wp_extra.
{
    entity this = MUTATOR_ARGV(0, entity);
    string s = MUTATOR_ARGV(0, string);
    if (s == WP_Buff.netname || s == RADARICON_Buff.netname)
    {
        Buff b = Buffs_from(this.wp_extra);
        MUTATOR_ARGV(0, vector) = b.m_color;
        MUTATOR_ARGV(0, string) = b.m_prettyName;
        return true;
    }
}
REGISTER_MUTATOR (buffs_flight , true)
REGISTER_MUTATOR (cl_buffs , true)