Xonotic: client/hud/panel/radar.qc File Reference
client/hud/panel/radar.qc File Reference
Functions
float HUD_Radar_Clickable ()
void HUD_Radar_Show_Maximized (bool doshow, float clickable)
void HUD_Radar_Hide_Maximized ()
float HUD_Radar_InputEvent (float bInputType, float nPrimary, float nSecondary)
void HUD_Radar_Mouse ()
void HUD_Radar ()
Function Documentation
void HUD_Radar ()
Definition at line 163 of file radar.qc.
References autocvar__hud_configure, autocvar_hud_panel_radar, autocvar_hud_panel_radar_maximized_size, bound(), c1, c2, c3, current_zoomfraction, DEG2RAD, draw_teamradar_background(), draw_teamradar_link(), drawpic(), drawsetcliparea(), FOREACH_ENTITY_CLASS, FOREACH_ENTITY_FLAGS, hud_draw_maximized, HUD_Panel_DrawBg, hud_panel_radar_foreground_alpha, hud_panel_radar_maximized, hud_panel_radar_maximized_rotation, hud_panel_radar_maximized_zoommode, hud_panel_radar_mouse, hud_panel_radar_rotation, hud_panel_radar_scale, hud_panel_radar_temp_hidden, hud_panel_radar_zoommode, HUD_Panel_UpdateCvars, hud_skin_path, LAMBDA, max(), mi_center, mi_max, mi_min, mi_picmax, mi_picmin, mi_scale, min(), minimapname, mousepos, panel, panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, precache_pic(), radar_panel_modified, rotate(), strcat(), strunzone(), strzone(), teamplay, teamradar_3dcoord_to_texcoord(), teamradar_angle, teamradar_extraclip_maxs, teamradar_extraclip_mins, teamradar_loadcvars(), teamradar_origin2d, teamradar_origin3d_in_texcoord, teamradar_size, teamradar_size2d, teamradar_texcoord_to_2dcoord(), time, vdist, vec2, vector(), vid_conheight, vid_conwidth, view_angles, view_origin, vlen(), vlen_maxnorm2d(), and vlen_minnorm2d().
{
    if (!autocvar__hud_configure)
    {
        if (hud_panel_radar_maximized)
        {
            if (!hud_draw_maximized) return;
        }
        else
        {
            if (autocvar_hud_panel_radar == 0) return;
            if (autocvar_hud_panel_radar != 2 && !teamplay) return;
            if(radar_panel_modified)
            {
                panel.update_time = time; // forces reload of panel attributes
                radar_panel_modified = false;
            }
        }
    }
    if ( hud_panel_radar_temp_hidden )
        return;
    HUD_Panel_UpdateCvars();
    float f = 0;
    if (hud_panel_radar_maximized && !autocvar__hud_configure)
    {
        panel_size = autocvar_hud_panel_radar_maximized_size;
        panel_size.x = bound(0.2, panel_size.x, 1) * vid_conwidth;
        panel_size.y = bound(0.2, panel_size.y, 1) * vid_conheight;
        panel_pos.x = (vid_conwidth - panel_size.x) / 2;
        panel_pos.y = (vid_conheight - panel_size.y) / 2;
        string panel_bg;
        panel_bg = strcat(hud_skin_path, "/border_default"); // always use the default border when maximized
        if(precache_pic(panel_bg) == "")
            panel_bg = "gfx/hud/default/border_default"; // fallback
        if(!radar_panel_modified && panel_bg != panel.current_panel_bg)
            radar_panel_modified = true;
        if(panel.current_panel_bg)
            strunzone(panel.current_panel_bg);
        panel.current_panel_bg = strzone(panel_bg);
        switch(hud_panel_radar_maximized_zoommode)
        {
            default:
            case 0:
                f = current_zoomfraction;
                break;
            case 1:
                f = 1 - current_zoomfraction;
                break;
            case 2:
                f = 0;
                break;
            case 3:
                f = 1;
                break;
        }
        switch(hud_panel_radar_maximized_rotation)
        {
            case 0:
                teamradar_angle = view_angles.y - 90;
                break;
            default:
                teamradar_angle = 90 * hud_panel_radar_maximized_rotation;
                break;
        }
    }
    if (!hud_panel_radar_maximized && !autocvar__hud_configure)
    {
        switch(hud_panel_radar_zoommode)
        {
            default:
            case 0:
                f = current_zoomfraction;
                break;
            case 1:
                f = 1 - current_zoomfraction;
                break;
            case 2:
                f = 0;
                break;
            case 3:
                f = 1;
                break;
        }
        switch(hud_panel_radar_rotation)
        {
            case 0:
                teamradar_angle = view_angles.y - 90;
                break;
            default:
                teamradar_angle = 90 * hud_panel_radar_rotation;
                break;
        }
    }
    vector pos, mySize;
    pos = panel_pos;
    mySize = panel_size;
    HUD_Panel_DrawBg(1);
    if(panel_bg_padding)
    {
        pos += '1 1 0' * panel_bg_padding;
        mySize -= '2 2 0' * panel_bg_padding;
    }
    int color2;
    float scale2d, normalsize, bigsize;
    teamradar_origin2d = pos + 0.5 * mySize;
    teamradar_size2d = mySize;
    if(minimapname == "")
        return;
    teamradar_loadcvars();
    scale2d = vlen_maxnorm2d(mi_picmax - mi_picmin);
    teamradar_size2d = mySize;
    teamradar_extraclip_mins = teamradar_extraclip_maxs = '0 0 0'; // we always center
    // pixels per world qu to match the teamradar_size2d_x range in the longest dimension
    if((hud_panel_radar_rotation == 0 && !hud_panel_radar_maximized) || (hud_panel_radar_maximized_rotation == 0 && hud_panel_radar_maximized))
    {
        // max-min distance must fit the radar in any rotation
        bigsize = vlen_minnorm2d(teamradar_size2d) * scale2d / (1.05 * vlen(vec2(mi_scale)));
    }
    else
    {
        vector c0, c1, c2, c3, span;
        c0 = rotate(mi_min, teamradar_angle * DEG2RAD);
        c1 = rotate(mi_max, teamradar_angle * DEG2RAD);
        c2 = rotate('1 0 0' * mi_min.x + '0 1 0' * mi_max.y, teamradar_angle * DEG2RAD);
        c3 = rotate('1 0 0' * mi_max.x + '0 1 0' * mi_min.y, teamradar_angle * DEG2RAD);
        span = '0 0 0';
        span.x = max(c0_x, c1_x, c2_x, c3_x) - min(c0_x, c1_x, c2_x, c3_x);
        span.y = max(c0_y, c1_y, c2_y, c3_y) - min(c0_y, c1_y, c2_y, c3_y);
        // max-min distance must fit the radar in x=x, y=y
        bigsize = min(
            teamradar_size2d.x * scale2d / (1.05 * span.x),
            teamradar_size2d.y * scale2d / (1.05 * span.y)
        );
    }
    normalsize = vlen_maxnorm2d(teamradar_size2d) * scale2d / hud_panel_radar_scale;
    if(bigsize > normalsize)
        normalsize = bigsize;
    teamradar_size =
          f * bigsize
        + (1 - f) * normalsize;
    teamradar_origin3d_in_texcoord = teamradar_3dcoord_to_texcoord(
          f * mi_center
        + (1 - f) * view_origin);
    drawsetcliparea(
        pos.x,
        pos.y,
        mySize.x,
        mySize.y
    );
    draw_teamradar_background(hud_panel_radar_foreground_alpha);
    FOREACH_ENTITY_CLASS("radarlink", true, LAMBDA(
        draw_teamradar_link(it.origin, it.velocity, it.team);
    ));
    FOREACH_ENTITY_FLAGS(teamradar_icon, 0xFFFFFF, LAMBDA(
        if ( hud_panel_radar_mouse )
        if ( it.health > 0 )
        if ( it.team == myteam+1 )
        {
            vector coord = teamradar_texcoord_to_2dcoord(teamradar_3dcoord_to_texcoord(it.origin));
            if(vdist((mousepos - coord), <, 8))
            {
                vector brightcolor;
                brightcolor_x = min(1,it.teamradar_color_x*1.5);
                brightcolor_y = min(1,it.teamradar_color_y*1.5);
                brightcolor_z = min(1,it.teamradar_color_z*1.5);
                drawpic(coord - '8 8 0', "gfx/teamradar_icon_glow", '16 16 0', brightcolor, panel_fg_alpha, 0);
            }
        }
        entity icon = RadarIcons_from(it.teamradar_icon);
        draw_teamradar_icon(it.origin, icon, it, spritelookupcolor(it, icon.netname, it.teamradar_color), panel_fg_alpha);
    ));
    AL_EACH(_entcs, e, it != NULL, LAMBDA(
        if (!it.m_entcs_private) continue;
        if (entcs_is_self(it)) continue;
        color2 = entcs_GetTeam(it.sv_entnum);
        draw_teamradar_player(it.origin, it.angles, Team_ColorRGB(color2));
    ));
    draw_teamradar_player(view_origin, view_angles, '1 1 1');
    drawresetcliparea();
    if ( hud_panel_radar_mouse )
    {
        string message = "Click to select teleport destination";
        if ( STAT(HEALTH) <= 0 )
        {
            message = "Click to select spawn location";
        }
        drawcolorcodedstring(pos + '0.5 0 0' * (mySize_x - stringwidth(message, true, hud_fontsize)) - '0 1 0' * hud_fontsize_y * 2,
                             message, hud_fontsize, hud_panel_radar_foreground_alpha, DRAWFLAG_NORMAL);
        hud_panel_radar_bottom = pos_y + mySize_y + hud_fontsize_y;
    }
}
float HUD_Radar_Clickable ()
Definition at line 3 of file radar.qc.
References hud_panel_radar_mouse, and hud_panel_radar_temp_hidden.
Referenced by HUD_CenterPrint(), and HUD_WouldDrawScoreboard().
{
    return hud_panel_radar_mouse && !hud_panel_radar_temp_hidden;
}
void HUD_Radar_Hide_Maximized ()
Definition at line 31 of file radar.qc.
References HUD_Radar_Show_Maximized().
Referenced by HUD_Radar_InputEvent(), HUD_Radar_Mouse(), and NET_HANDLE().
{
    HUD_Radar_Show_Maximized(false,false);
}
float HUD_Radar_InputEvent (float bInputType, float nPrimary, float nSecondary)
Definition at line 37 of file radar.qc.
References argv(), autocvar__hud_configure, hud_panel_radar_maximized, hud_panel_radar_mouse, hud_panel_radar_temp_hidden, HUD_Radar_Hide_Maximized(), K_ESCAPE, K_MOUSE1, K_MOUSE2, mouseClicked, mv_active, S_MOUSE1, S_MOUSE2, stof(), strcat(), and tokenize().
Referenced by CSQC_InputEvent().
{
    if(!hud_panel_radar_maximized || !hud_panel_radar_mouse ||
        autocvar__hud_configure || mv_active)
        return false;
    if(bInputType == 3)
    {
        mousepos_x = nPrimary;
        mousepos_y = nSecondary;
        return true;
    }
    if(nPrimary == K_MOUSE1)
    {
        if(bInputType == 0) // key pressed
            mouseClicked |= S_MOUSE1;
        else if(bInputType == 1) // key released
            mouseClicked -= (mouseClicked & S_MOUSE1);
    }
    else if(nPrimary == K_MOUSE2)
    {
        if(bInputType == 0) // key pressed
            mouseClicked |= S_MOUSE2;
        else if(bInputType == 1) // key released
            mouseClicked -= (mouseClicked & S_MOUSE2);
    }
    else if ( nPrimary == K_ESCAPE && bInputType == 0 )
    {
        HUD_Radar_Hide_Maximized();
    }
    else
    {
        // allow console/use binds to work without hiding the map
        string con_keys;
        float keys;
        float i;
        con_keys = strcat(findkeysforcommand("toggleconsole", 0)," ",findkeysforcommand("+use", 0)) ;
        keys = tokenize(con_keys); // findkeysforcommand returns data for this
        for (i = 0; i < keys; ++i)
        {
            if(nPrimary == stof(argv(i)))
                return false;
        }
        if ( STAT(HEALTH) <= 0 )
        {
            // Show scoreboard
            if ( bInputType < 2 )
            {
                con_keys = findkeysforcommand("+showscores", 0);
                keys = tokenize(con_keys);
                for (i = 0; i < keys; ++i)
                {
                    if ( nPrimary == stof(argv(i)) )
                    {
                        hud_panel_radar_temp_hidden = bInputType == 0;
                        return false;
                    }
                }
            }
        }
        else if ( bInputType == 0 )
            HUD_Radar_Hide_Maximized();
        return false;
    }
    return true;
}
void HUD_Radar_Mouse ()
Definition at line 108 of file radar.qc.
References autocvar_hud_cursormode, autocvar_hud_panel_radar_maximized_size, autocvar_menu_mouse_speed, autocvar_menu_skin, bound(), DRAWFLAG_NORMAL, drawpic(), getmousepos(), hud_panel_radar_mouse, HUD_Panel_UpdateCvars, HUD_Radar_Hide_Maximized(), intermission, localcmd, mouseClicked, mousepos, mv_active, panel_size, S_MOUSE1, S_MOUSE2, strcat(), teamradar_2dcoord_to_texcoord(), teamradar_texcoord_to_3dcoord(), vector(), vid_conheight, and vid_conwidth.
Referenced by CSQC_UpdateView().
{
    if ( !hud_panel_radar_mouse ) return;
    if(mv_active) return;
    if ( intermission )
    {
        HUD_Radar_Hide_Maximized();
        return;
    }
    if(mouseClicked & S_MOUSE2)
    {
        HUD_Radar_Hide_Maximized();
        return;
    }
    if(!autocvar_hud_cursormode)
    {
        mousepos = mousepos + getmousepos() * autocvar_menu_mouse_speed;
        mousepos_x = bound(0, mousepos_x, vid_conwidth);
        mousepos_y = bound(0, mousepos_y, vid_conheight);
    }
    HUD_Panel_UpdateCvars();
    panel_size = autocvar_hud_panel_radar_maximized_size;
    panel_size_x = bound(0.2, panel_size_x, 1) * vid_conwidth;
    panel_size_y = bound(0.2, panel_size_y, 1) * vid_conheight;
    panel_pos_x = (vid_conwidth - panel_size_x) / 2;
    panel_pos_y = (vid_conheight - panel_size_y) / 2;
    if(mouseClicked & S_MOUSE1)
    {
        // click outside
        if ( mousepos_x < panel_pos_x || mousepos_x > panel_pos_x + panel_size_x ||
             mousepos_y < panel_pos_y || mousepos_y > panel_pos_y + panel_size_y )
        {
            HUD_Radar_Hide_Maximized();
            return;
        }
        vector pos = teamradar_texcoord_to_3dcoord(teamradar_2dcoord_to_texcoord(mousepos),view_origin_z);
        localcmd(sprintf("cmd ons_spawn %f %f %f",pos_x,pos_y,pos_z));
        HUD_Radar_Hide_Maximized();
        return;
    }
    const vector cursor_size = '32 32 0';
    drawpic(mousepos-'8 4 0', strcat("gfx/menu/", autocvar_menu_skin, "/cursor.tga"), cursor_size, '1 1 1', 0.8, DRAWFLAG_NORMAL);
}
void HUD_Radar_Show_Maximized (bool doshow, float clickable)
Definition at line 8 of file radar.qc.
References autocvar_hud_cursormode, hud_panel_radar_maximized, hud_panel_radar_mouse, hud_panel_radar_temp_hidden, mouseClicked, and mv_active.
{
    hud_panel_radar_maximized = doshow;
    hud_panel_radar_temp_hidden = 0;
    if ( doshow )
    {
        if (clickable)
        {
            if(autocvar_hud_cursormode)
                setcursormode(1);
            hud_panel_radar_mouse = 1;
        }
    }
    else if ( hud_panel_radar_mouse )
    {
        hud_panel_radar_mouse = 0;
        mouseClicked = 0;
        if(autocvar_hud_cursormode)
        if(!mv_active)
            setcursormode(0);
    }
}