Xonotic: server/mapvoting.qh File Reference
server/mapvoting.qh File Reference
Defines
#define MAPVOTING_H
Functions
void MapVote_Start ()
void MapVote_Spawn ()
void MapVote_Think ()
void MapVote_SendPicture (float id)
float GameTypeVote_Start ()
float GameTypeVote_Finished (float pos)
string GameTypeVote_MapInfo_FixName (string m)
Variables
float gametypevote
string getmapname_stored
float mapvote_initialized
Define Documentation
#define MAPVOTING_H
Definition at line 2 of file mapvoting.qh.
Function Documentation
float GameTypeVote_Finished (float pos)
Definition at line 734 of file mapvoting.qc.
References gametypevote, GameTypeVote_SetGametype(), GameTypeVote_Type_FromString(), localcmd, LOG_TRACE(), and mapvote_maps.
Referenced by MapVote_Finished().
{
    if(!gametypevote || gametypevote_finished)
        return false;
    if ( !GameTypeVote_SetGametype(GameTypeVote_Type_FromString(mapvote_maps[pos])) )
    {
        LOG_TRACE("Selected gametype is not supported by any map");
    }
    localcmd("sv_vote_gametype_hook_all\n");
    localcmd("sv_vote_gametype_hook_", mapvote_maps[pos], "\n");
    gametypevote_finished = true;
    return true;
}
string GameTypeVote_MapInfo_FixName (string m)
Definition at line 90 of file mapvoting.qc.
References autocvar_sv_vote_gametype, GameTypeVote_GetMask(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_FixName(), MapInfo_ForbiddenFlags(), and MapInfo_RequiredFlags().
Referenced by GotoMap(), and MapVote_Suggest().
{
    if ( autocvar_sv_vote_gametype )
    {
        MapInfo_Enumerate();
        MapInfo_FilterGametype(GameTypeVote_GetMask(), 0, MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
    }
    return MapInfo_FixName(m);
}
float GameTypeVote_Start ()
Definition at line 774 of file mapvoting.qc.
References argv(), autocvar_g_maplist_votable_nodetail, autocvar_sv_vote_gametype_keeptwotime, autocvar_sv_vote_gametype_options, autocvar_sv_vote_gametype_timeout, gametypevote, GameTypeVote_AddVotable(), GTV_AVAILABLE, MapInfo_CurrentGametype(), MapInfo_Type_ToString(), mapvote_abstain, MapVote_ClearAllVotes(), mapvote_count, MAPVOTE_COUNT, mapvote_count_real, mapvote_detail, MapVote_Finished(), mapvote_keeptwotime, mapvote_maps, mapvote_maps_flags, MapVote_Spawn(), mapvote_timeout, MapVote_UnzoneStrings(), min(), n, strunzone(), strzone(), time, and tokenizebyseparator.
Referenced by MapVote_Think().
{
    float j;
    MapVote_ClearAllVotes();
    MapVote_UnzoneStrings();
    mapvote_count = 0;
    mapvote_timeout = time + autocvar_sv_vote_gametype_timeout;
    mapvote_abstain = 0;
    mapvote_detail = !autocvar_g_maplist_votable_nodetail;
    float n = tokenizebyseparator(autocvar_sv_vote_gametype_options, " ");
    n = min(MAPVOTE_COUNT, n);
    float really_available, which_available;
    really_available = 0;
    which_available = -1;
    for(j = 0; j < n; ++j)
    {
        if ( GameTypeVote_AddVotable(argv(j)) )
        if ( mapvote_maps_flags[j] & GTV_AVAILABLE )
        {
            really_available++;
            which_available = j;
        }
    }
    mapvote_count_real = mapvote_count;
    gametypevote = 1;
    if ( really_available == 0 )
    {
        if ( mapvote_count > 0 )
            strunzone(mapvote_maps[0]);
        mapvote_maps[0] = strzone(MapInfo_Type_ToString(MapInfo_CurrentGametype()));
        //GameTypeVote_Finished(0);
        MapVote_Finished(0);
        return false;
    }
    if ( really_available == 1 )
    {
        //GameTypeVote_Finished(which_available);
        MapVote_Finished(which_available);
        return false;
    }
    mapvote_count_real = mapvote_count;
    mapvote_keeptwotime = time + autocvar_sv_vote_gametype_keeptwotime;
    if(mapvote_count_real < 3 || mapvote_keeptwotime <= time)
        mapvote_keeptwotime = 0;
    MapVote_Spawn();
    return true;
}
void MapVote_SendPicture (float id)
Definition at line 263 of file mapvoting.qc.
References mapvote_maps, mapvote_maps_screenshot_dir, mapvote_screenshot_dirs, msg_entity, MSG_ONE, SELFPARAM, strcat(), and WriteByte().
Referenced by ClientCommand_mv_getpicture().
{SELFPARAM();
    msg_entity = self;
    WriteHeader(MSG_ONE, TE_CSQC_PICTURE);
    WriteByte(MSG_ONE, id);
    WritePicture(MSG_ONE, strcat(mapvote_screenshot_dirs[mapvote_maps_screenshot_dir[id]], "/", mapvote_maps[id]), 3072);
}
void MapVote_Spawn ()
Definition at line 410 of file mapvoting.qc.
References mapvote_ent, MapVote_SendEntity(), and spawn().
Referenced by GameTypeVote_Start(), and MapVote_Init().
{
    Net_LinkEntity(mapvote_ent = spawn(), false, 0, MapVote_SendEntity);
}
void MapVote_Start ()
Definition at line 633 of file mapvoting.qc.
References MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), and mapvote_run.
Referenced by CheckRules_World(), and IntermissionThink().
{
    // if mapvote is already running, don't do this initialization again
    if(mapvote_run) { return; }
    // don't start mapvote until after playerstats gamereport is sent
    if(PlayerStats_GameReport_DelayMapVote) { return; }
    MapInfo_Enumerate();
    if(MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1))
        mapvote_run = true;
}
void MapVote_Think ()
Definition at line 646 of file mapvoting.qc.
References alreadychangedlevel, autocvar_g_maplist_votable, autocvar_nextmap, autocvar_rescan_pending, autocvar_sv_vote_gametype, cvar_set(), DoNextMapOverride(), GameTypeVote_Start(), GotoNextMap(), localcmd, MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), MapVote_Init(), mapvote_initialized, mapvote_nextthink, mapvote_run, MapVote_Tick(), player_count, and time.
Referenced by CheckRules_World().
{
    if(!mapvote_run)
        return;
    if(alreadychangedlevel)
        return;
    if(time < mapvote_nextthink)
        return;
    //dprint("tick\n");
    mapvote_nextthink = time + 0.5;
    if(!mapvote_initialized)
    {
        if(autocvar_rescan_pending == 1)
        {
            cvar_set("rescan_pending", "2");
            localcmd("fs_rescan\nrescan_pending 3\n");
            return;
        }
        else if(autocvar_rescan_pending == 2)
        {
            return;
        }
        else if(autocvar_rescan_pending == 3)
        {
            // now build missing mapinfo files
            if(!MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1))
                return;
            // we're done, start the timer
            cvar_set("rescan_pending", "0");
        }
        mapvote_initialized = true;
        if(DoNextMapOverride(0))
            return;
        if(!autocvar_g_maplist_votable || player_count <= 0)
        {
            GotoNextMap(0);
            return;
        }
        if(autocvar_sv_vote_gametype) { GameTypeVote_Start(); }
        else if(autocvar_nextmap == "") { MapVote_Init(); }
    }
    MapVote_Tick();
}
Variable Documentation
float gametypevote
Definition at line 13 of file mapvoting.qh.
string getmapname_stored
Definition at line 14 of file mapvoting.qh.
Referenced by Map_Goto(), and Map_Goto_SetStr().
float mapvote_initialized
Definition at line 15 of file mapvoting.qh.
Referenced by GotoMap(), IntermissionThink(), MapVote_Suggest(), and MapVote_Think().