Xonotic: client/shownames.qh File Reference
client/shownames.qh File Reference
Defines
#define CLIENT_SHOWNAMES_H
Functions
entityclass (ShowNames)
class (ShowNames).float healthvalue
void Draw_ShowNames_All ()
Define Documentation
#define CLIENT_SHOWNAMES_H
Definition at line 2 of file shownames.qh.
Function Documentation
class (ShowNames)
void Draw_ShowNames_All ()
Definition at line 168 of file shownames.qc.
References assert, autocvar_hud_shownames, Draw_ShowNames(), entity(), eprint(), LAMBDA, LL_EACH, make_impure, make_pure, shownames_ent, and WITH.
Referenced by CSQC_UpdateView().
{
    if (!autocvar_hud_shownames) return;
    LL_EACH(shownames_ent, true, LAMBDA(
        entity entcs = entcs_receiver(i);
        if (!entcs)
        {
            make_pure(it);
            continue;
        }
        make_impure(it);
        assert(entcs.think, eprint(entcs));
        WITH(entity, self, entcs, entcs.think());
        if (!entcs.has_origin) continue;
        if (entcs.m_entcs_private)
        {
            it.healthvalue = entcs.healthvalue;
            it.armorvalue = entcs.armorvalue;
            it.sameteam = true;
        }
        else
        {
            it.healthvalue = 0;
            it.armorvalue = 0;
            it.sameteam = false;
        }
        bool dead = entcs_IsDead(i) || entcs_IsSpectating(i);
        if (!it.csqcmodel_isdead) setorigin(it, entcs.origin);
        it.csqcmodel_isdead = dead;
        Draw_ShowNames(it);
    ));
}
entityclass (ShowNames)