Xonotic: server/steerlib.qh File Reference
server/steerlib.qh File Reference
Defines
#define STEERLIB_H
Functions
vector steerlib_arrive (vector point, float maximal_distance)
Pull toward a point, The further away, the stronger the pull.
vector steerlib_attract2 (entity this, vector point, float min_influense, float max_distance, float max_influense)
vector steerlib_pull (vector point)
Uniform pull towards a point.
Variables
vector steerto
Define Documentation
#define STEERLIB_H
Definition at line 2 of file steerlib.qh.
Function Documentation
vector steerlib_arrive (vector point, float maximal_distance)
Pull toward a point, The further away, the stronger the pull.
Definition at line 27 of file steerlib.qc.
References bound(), normalize(), origin, SELFPARAM, vector(), and vlen().
Referenced by steerlib_flock(), steerlib_flock2d(), and steerlib_swarm().
{SELFPARAM();
    float distance;
    vector direction;
    distance = bound(0.001,vlen(self.origin - point),maximal_distance);
    direction = normalize(point - self.origin);
    return  direction * (distance / maximal_distance);
}
vector steerlib_attract2 (entity this, vector point, float min_influense, float max_distance, float max_influense)
Definition at line 51 of file steerlib.qc.
References bound(), normalize(), origin, vector(), and vlen().
Referenced by Monster_Move().
{
    float distance;
    vector direction;
    float influense;
    distance  = bound(0.00001,vlen(this.origin - point),max_distance);
    direction = normalize(point - this.origin);
    influense = 1 - (distance / max_distance);
    influense = min_influense + (influense * (max_influense - min_influense));
    return  direction * influense;
}
vector steerlib_pull (vector point)
Uniform pull towards a point.
Definition at line 9 of file steerlib.qc.
References normalize(), origin, and SELFPARAM.
{SELFPARAM();
    return normalize(point - self.origin);
}
Variable Documentation
vector steerto
Definition at line 4 of file steerlib.qh.
Referenced by Monster_Move().