Xonotic: common/turrets/targettrigger.qc File Reference
common/turrets/targettrigger.qc File Reference
Functions
spawnfunc (turret_targettrigger)
void turret_targettrigger_touch ()
Function Documentation
spawnfunc (turret_targettrigger)
Definition at line 30 of file targettrigger.qc.
References autocvar_g_turrets, InitTrigger(), and turret_targettrigger_touch().
{
    if(!autocvar_g_turrets) { remove(self); return; }
    InitTrigger ();
    self.touch = turret_targettrigger_touch;
}
void turret_targettrigger_touch ()
Definition at line 4 of file targettrigger.qc.
References cnt, entity(), find(), other, SELFPARAM, setself, target, targetname, time, TUR_FLAG_RECIEVETARGETS, and world.
Referenced by spawnfunc().
{SELFPARAM();
    entity e;
    if (self.cnt > time) return;
    entity oldself = this;
    e = find(world, targetname, self.target);
    while (e)
    {
        if (e.turret_flags & TUR_FLAG_RECIEVETARGETS)
        {
            setself(e);
            if(e.turret_addtarget)
                e.turret_addtarget(other,oldself);
        }
        e = find(e, targetname, oldself.target);
    }
    oldself.cnt = time + 0.5;
    setself(this);
}