Xonotic: menu/xonotic/textlabel.qh File Reference
textlabel.qh File Reference
#include "../item/label.qh"
Classes
class XonoticTextLabel
Functions
entity makeXonoticHeaderLabel (string theText)
entity makeXonoticTextLabel (float theAlign, string theText)
Function Documentation
entity makeXonoticHeaderLabel (string theText)
Definition at line 10 of file textlabel.qc.
References entity(), and makeXonoticTextLabel().
Referenced by XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticUserSettingsTab_fill().
 {
     entity me;
     me = makeXonoticTextLabel(0.5, theText);
     me.colorL = SKINCOLOR_HEADER;
     me.alpha = SKINALPHA_HEADER;
     me.isBold = true;
     return me;
 }
entity makeXonoticTextLabel (float theAlign, string theText)
Definition at line 3 of file textlabel.qc.
 {
     entity me;
     me = NEW(XonoticTextLabel);
     me.configureXonoticTextLabel(me, theAlign, theText);
     return me;
 }