Xonotic: lib/test.qc File Reference
test.qc File Reference
#include "test.qh"
Functions
bool RUN_ALL_TESTS ()
bool TEST_Run (string s)
int TEST_RunAll_accumulated (int init)
Function Documentation
bool RUN_ALL_TESTS ()
Definition at line 4 of file test.qc.
References LOG_INFO, LOG_INFOF, and TEST_RunAll_accumulated().
Referenced by GenericCommand_runtest().
 {
     int f = TEST_RunAll_accumulated(0);
     if (f)
     {
         LOG_INFOF("%d tests failed\n", f);
         return true;
     }
     else
     {
         LOG_INFO("All tests OK\n");
         return false;
     }
 }
bool TEST_Run (string s)
Definition at line 19 of file test.qc.
References callfunction(), isfunction(), LOG_INFOF, strcat(), TEST_failed, TEST_fatal, and TEST_ok.
Referenced by GenericCommand_runtest().
 {
     LOG_INFOF("%s: testing...\n", s);
     TEST_failed = 0;
     TEST_fatal = 0;
     TEST_ok = false;
     string fn = strcat("_TEST_", s);
     if (isfunction(fn)) callfunction(fn);
     if (TEST_failed > 0)
     {
         LOG_INFOF("%s: %d items failed.\n", s, TEST_failed);
         return false;
     }
     else if (!TEST_ok)
     {
         LOG_INFOF("%s: did not complete.\n", s);
         return false;
     }
     return true;
 }
int TEST_RunAll_accumulated (int init)
Referenced by RUN_ALL_TESTS().