Xonotic: server/impulse.qc File Reference
impulse.qc File Reference
#include "impulse.qh"
#include <common/gamemodes/_mod.qh>
#include <common/minigames/sv_minigames.qh>
#include <common/mutators/mutator/waypoints/waypointsprites.qh>
#include <common/state.qh>
#include <common/vehicles/sv_vehicles.qh>
#include <common/weapons/_all.qh>
#include <server/cheats.qh>
#include <server/client.qh>
#include <server/clientkill.qh>
#include <server/command/common.qh>
#include <server/damage.qh>
#include <server/mutators/_mod.qh>
#include <server/round_handler.qh>
#include <server/weapons/selection.qh>
#include <server/weapons/throwing.qh>
#include <server/weapons/tracing.qh>
#include <server/weapons/weaponsystem.qh>
Macros
#define _IMPULSE(id)
#define IMPULSE(id) _IMPULSE(IMP_##id)
#define X(i)
#define X(i, dir)
#define X(i)
#define X(id) case IMP_##id.impulse:
Functions
for (int slot=0;slot< MAX_WEAPONSLOTS;++slot)
if (IS_DEAD(this))
IMPULSE (weapon_prev_byid)
IMPULSE (weapon_next_bygroup)
IMPULSE (weapon_prev_bygroup)
IMPULSE (weapon_next_bypriority)
IMPULSE (weapon_prev_bypriority)
IMPULSE (weapon_last)
IMPULSE (weapon_best)
IMPULSE (weapon_drop)
IMPULSE (weapon_reload)
IMPULSE (use)
IMPULSE (waypoint_personal_here)
IMPULSE (waypoint_personal_crosshair)
IMPULSE (waypoint_personal_death)
IMPULSE (waypoint_here_follow)
IMPULSE (waypoint_here_here)
IMPULSE (waypoint_here_crosshair)
IMPULSE (waypoint_here_death)
IMPULSE (waypoint_danger_here)
IMPULSE (waypoint_danger_crosshair)
IMPULSE (waypoint_danger_death)
IMPULSE (waypoint_clear_personal)
IMPULSE (waypoint_clear)
void ImpulseCommands (entity this)
prev prev prev prev prev best best best best best next next next next next void weapon_byid_handle (entity this, int number, int imp)
void weapon_group_handle (entity this, int number, int imp)
Impulse map:
X (1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) X(0) void weapon_priority_handle(entity this
X (0, prev) X(1
prev X (2, prev) X(3
prev prev X (4, prev) X(5
prev prev prev X (6, prev) X(7
prev prev prev prev X (8, prev) X(9
prev prev prev prev prev X (0, best) X(1
prev prev prev prev prev best X (2, best) X(3
prev prev prev prev prev best best X (4, best) X(5
prev prev prev prev prev best best best X (6, best) X(7
prev prev prev prev prev best best best best X (8, best) X(9
prev prev prev prev prev best best best best best X (0, next) X(1
prev prev prev prev prev best best best best best next X (2, next) X(3
prev prev prev prev prev best best best best best next next X (4, next) X(5
prev prev prev prev prev best best best best best next next next X (6, next) X(7
prev prev prev prev prev best best best best best next next next next X (8, next) X(9
X (0) X(1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15) X(16) X(17) X(18) X(19) X(20) X(21) X(22) X(23) IMPULSE(weapon_next_byid)
Variables
int dir
int int int imp
int int number
entity vehicle
Macro Definition Documentation
#define _IMPULSE (id)
Value:
void id##_handle(entity this); \
    STATIC_INIT_LATE(id) \
    { \
        id.impulse_handle = id##_handle; \
    } \
    void id##_handle(entity this)
Definition at line 24 of file impulse.qc.
#define IMPULSE (id) _IMPULSE(IMP_##id)
Definition at line 23 of file impulse.qc.
#define X (i)
Value:
IMPULSE(weapon_group_##i) \
    { \
        weapon_group_handle(this, i, IMP_weapon_group_##i.impulse); \
    }
Definition at line 167 of file impulse.qc.
Referenced by for(), ImpulseCommands(), and weapon_group_handle().
#define X (i, dir)
Value:
IMPULSE(weapon_priority_##i##_##dir) \
    { \
        noref int prev = -1; \
        noref int best =  0; \
        noref int next = +1; \
        weapon_priority_handle(this, dir, i, IMP_weapon_priority_##i##_##dir.impulse); \
    }
Definition at line 167 of file impulse.qc.
#define X (i)
Value:
IMPULSE(weapon_byid_##i) \
    { \
        weapon_byid_handle(this, i, IMP_weapon_byid_##i.impulse); \
    }
Definition at line 167 of file impulse.qc.
#define X (id) case IMP_##id.impulse:
Definition at line 167 of file impulse.qc.
Function Documentation
for ()
Definition at line 97 of file impulse.qc.
References autocvar_g_weaponswitch_debug, best, CS(), next, prev, W_CycleWeapon(), weaponentities, and X.
Referenced by Dump_Weapon_Settings().
     {
         .entity weaponentity = weaponentities[slot];
         W_CycleWeapon(this, CS(this).cvar_cl_weaponpriorities[number], dir, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
if (IS_DEAD(this))
Definition at line 92 of file impulse.qc.
References imp, and impulse.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), bot_removefromlargestteam(), botframe_deleteuselesswaypoints(), botframe_showwaypointlinks(), Keyframe::calcValue(), findnearest(), HUD_Panel_DrawProgressBar(), HUD_Radar(), Item_ItemsTime_Allow(), Label_recalcPositionWithText(), lms_RemovePlayer(), MUTATOR_HOOKFUNCTION(), navigation_findnearestwaypoint_withdist_except(), Nexposee_Calc_Scale(), reset_map(), Scoreboard_AccuracyStats_Draw(), Slider_mouseDrag(), STATIC_INIT(), sys_phys_simulate_simple(), target_give_init(), TeamBalance_GetTeamCounts(), trigger_push_test(), trigger_race_checkpoint_verify(), waypoint_remove(), and waypoint_think().
     {
         this.impulse = imp;
         return;
     }
IMPULSE (weapon_prev_byid)
Definition at line 216 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_PreviousWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_byid.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_PreviousWeapon(this, 0, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_next_bygroup)
Definition at line 234 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_NextWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_bygroup.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_NextWeapon(this, 1, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_prev_bygroup)
Definition at line 252 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_PreviousWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_bygroup.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_PreviousWeapon(this, 1, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_next_bypriority)
Definition at line 270 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_NextWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_bypriority.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_NextWeapon(this, 2, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_prev_bypriority)
Definition at line 288 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_PreviousWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_bypriority.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_PreviousWeapon(this, 2, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_last)
Definition at line 306 of file impulse.qc.
References autocvar_g_weaponswitch_debug, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_LastWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_LastWeapon(this, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_best)
Definition at line 320 of file impulse.qc.
References autocvar_g_weaponswitch_debug, IS_DEAD, MAX_WEAPONSLOTS, vehicle, w_getbestweapon, W_SwitchWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_SwitchWeapon(this, w_getbestweapon(this, weaponentity), weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
IMPULSE (weapon_drop)
Definition at line 334 of file impulse.qc.
References autocvar_g_weaponswitch_debug, IS_DEAD, MAX_WEAPONSLOTS, movedir, v_forward, v_right, vector(), vehicle, velocity, W_CalculateProjectileVelocity(), W_DualWielding(), W_ThrowWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     bool is_dualwielding = W_DualWielding(this);
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         vector md = this.(weaponentity).movedir;
         vector vecs = ((md.x > 0) ? md : '0 0 0');
         vector dv = v_right * -vecs.y;
         if(!is_dualwielding)
             dv = '0 0 0'; // don't override!
         W_ThrowWeapon(this, weaponentity, W_CalculateProjectileVelocity(this, this.velocity, v_forward * 750, false), dv, true);
         if(autocvar_g_weaponswitch_debug == 2)
             break; // in this mode, the off-hand weapon is selected based on the primary weapon, don't drop it twice!
     }
 }
IMPULSE (weapon_reload)
Definition at line 354 of file impulse.qc.
References entity(), IS_DEAD, MAX_WEAPONSLOTS, vehicle, weaponentities, weaponLocked(), and Weapon::wr_reload().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     if (weaponLocked(this)) return;
     entity actor = this;
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         Weapon w = this.(weaponentity).m_weapon;
         w.wr_reload(w, actor, weaponentity);
         // allow reloading all active slots?
         //if(autocvar_g_weaponswitch_debug != 1)
             //break;
     }
 }
IMPULSE (use)
Definition at line 481 of file impulse.qc.
References PlayerUseKey().
 {
     PlayerUseKey(this);
 }
IMPULSE (waypoint_personal_here)
Definition at line 486 of file impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, this, this.origin, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at location\n");
 }
IMPULSE (waypoint_personal_crosshair)
Definition at line 493 of file impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace().
 {
     WarpZone_crosshair_trace(this);
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, this, trace_endpos, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at crosshair\n");
 }
IMPULSE (waypoint_personal_death)
Definition at line 501 of file impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, this, this.death_origin, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at death location\n");
 }
IMPULSE (waypoint_here_follow)
Definition at line 509 of file impulse.qc.
References entity(), IS_DEAD, MUTATOR_CALLHOOK, sprint(), and teamplay.
 {
     if (!teamplay) return;
     if (IS_DEAD(this)) return;
     if (!MUTATOR_CALLHOOK(HelpMePing, this))
     {
         entity wp = WaypointSprite_Attach(WP_Helpme, this, true, RADARICON_HELPME);
         if (!wp) WaypointSprite_HelpMePing(this.waypointsprite_attachedforcarrier);
         else WaypointSprite_Ping(wp);
     }
     sprint(this, "HELP ME attached\n");
 }
IMPULSE (waypoint_here_here)
Definition at line 522 of file impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, this, this.origin, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at location\n");
 }
IMPULSE (waypoint_here_crosshair)
Definition at line 529 of file impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace_plusvisibletriggers().
 {
     WarpZone_crosshair_trace_plusvisibletriggers(this);
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, this, trace_endpos, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at crosshair\n");
 }
IMPULSE (waypoint_here_death)
Definition at line 537 of file impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, this, this.death_origin, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at death location\n");
 }
IMPULSE (waypoint_danger_here)
Definition at line 545 of file impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, this, this.origin, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at location\n");
 }
IMPULSE (waypoint_danger_crosshair)
Definition at line 552 of file impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace().
 {
     WarpZone_crosshair_trace(this);
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, this, trace_endpos, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at crosshair\n");
 }
IMPULSE (waypoint_danger_death)
Definition at line 560 of file impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, this, this.death_origin, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at death location\n");
 }
IMPULSE (waypoint_clear_personal)
Definition at line 568 of file impulse.qc.
References autocvar_g_allow_checkpoints, ClientKill(), g_cts, g_race, NULL, personal, and sprint().
 {
     WaypointSprite_ClearPersonal(this);
     if (this.personal)
     {
         delete(this.personal);
         this.personal = NULL;
         if((g_cts || g_race) && autocvar_g_allow_checkpoints)
             ClientKill(this);
     }
     sprint(this, "personal waypoint cleared\n");
 }
IMPULSE (waypoint_clear)
Definition at line 582 of file impulse.qc.
References autocvar_g_allow_checkpoints, ClientKill(), g_cts, g_race, NULL, personal, and sprint().
 {
     WaypointSprite_ClearOwned(this);
     if (this.personal)
     {
         delete(this.personal);
         this.personal = NULL;
         if((g_cts || g_race) && autocvar_g_allow_checkpoints)
             ClientKill(this);
     }
     sprint(this, "all waypoints cleared\n");
 }
void ImpulseCommands (entity this)
Definition at line 372 of file impulse.qc.
References CheatImpulse(), CS(), FOREACH, MinigameImpulse(), round_handler_IsActive, round_handler_IsRoundStarted, TIMEOUT_ACTIVE, timeout_status, vehicle_impulse(), and X.
Referenced by ctf_FlagThink(), PlayerPostThink(), and PutPlayerInServer().
 {
     if (game_stopped) return;
     int imp = CS(this).impulse;
     if (!imp) return;
     CS(this).impulse = 0;
     if (MinigameImpulse(this, imp)) return;
     if (timeout_status == TIMEOUT_ACTIVE) return;  // don't allow any impulses while the game is paused
     // allow only weapon change impulses when not in round time
     if (round_handler_IsActive() && !round_handler_IsRoundStarted())
     {
         #define X(id) case IMP_##id.impulse:
         switch (imp)
         {
             X(weapon_group_0)
             X(weapon_group_1)
             X(weapon_group_2)
             X(weapon_group_3)
             X(weapon_group_4)
             X(weapon_group_5)
             X(weapon_group_6)
             X(weapon_group_7)
             X(weapon_group_8)
             X(weapon_group_9)
             X(weapon_next_byid)
             X(weapon_prev_byid)
             X(weapon_next_bygroup)
             X(weapon_prev_bygroup)
             X(weapon_next_bypriority)
             X(weapon_prev_bypriority)
             X(weapon_last)
             X(weapon_best)
             X(weapon_reload)
             X(weapon_priority_0_prev)
             X(weapon_priority_1_prev)
             X(weapon_priority_2_prev)
             X(weapon_priority_3_prev)
             X(weapon_priority_4_prev)
             X(weapon_priority_5_prev)
             X(weapon_priority_6_prev)
             X(weapon_priority_7_prev)
             X(weapon_priority_8_prev)
             X(weapon_priority_9_prev)
             X(weapon_priority_0_next)
             X(weapon_priority_1_next)
             X(weapon_priority_2_next)
             X(weapon_priority_3_next)
             X(weapon_priority_4_next)
             X(weapon_priority_5_next)
             X(weapon_priority_6_next)
             X(weapon_priority_7_next)
             X(weapon_priority_8_next)
             X(weapon_priority_9_next)
             X(weapon_priority_0_best)
             X(weapon_priority_1_best)
             X(weapon_priority_2_best)
             X(weapon_priority_3_best)
             X(weapon_priority_4_best)
             X(weapon_priority_5_best)
             X(weapon_priority_6_best)
             X(weapon_priority_7_best)
             X(weapon_priority_8_best)
             X(weapon_priority_9_best)
             X(weapon_byid_0)
             X(weapon_byid_1)
             X(weapon_byid_2)
             X(weapon_byid_3)
             X(weapon_byid_4)
             X(weapon_byid_5)
             X(weapon_byid_6)
             X(weapon_byid_7)
             X(weapon_byid_8)
             X(weapon_byid_9)
             X(weapon_byid_10)
             X(weapon_byid_11)
             X(weapon_byid_12)
             X(weapon_byid_13)
             X(weapon_byid_14)
             X(weapon_byid_15)
             X(weapon_byid_16)
             X(weapon_byid_17)
             X(weapon_byid_18)
             X(weapon_byid_19)
             X(weapon_byid_20)
             X(weapon_byid_21)
             X(weapon_byid_22)
             X(weapon_byid_23)
             break;
             default: return;
         }
 #undef X
     }
     if (vehicle_impulse(this, imp)) return;
     if (CheatImpulse(this, imp)) return;
     FOREACH(IMPULSES, it.impulse == imp, {
         void(entity) f = it.impulse_handle;
         if (!f) continue;
         f(this);
         return;
     });
 }
prev prev prev prev prev best best best best best next next next next next void weapon_byid_handle (entity this, int number, int imp)
Definition at line 150 of file impulse.qc.
References autocvar_g_weaponswitch_debug, imp, impulse, IS_DEAD, MAX_WEAPONSLOTS, REGISTRY_GET, vehicle, W_SwitchWeapon_TryOthers(), weaponentities, and WEP_FIRST.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = imp;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_SwitchWeapon_TryOthers(this, REGISTRY_GET(Weapons, WEP_FIRST + number), weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
void weapon_group_handle (entity this, int number, int imp)
Impulse map:
0 reserved (no input)
99: loaded
140: moving clone 141: ctf speedrun 142: fixed clone 143: emergency teleport 148: unfairly eliminate
TODO: 200 to 209: prev weapon shortcuts 210 to 219: best weapon shortcuts 220 to 229: next weapon shortcuts 230 to 253: individual weapons (up to 24)
Definition at line 54 of file impulse.qc.
References autocvar_g_weaponswitch_debug, imp, impulse, IS_DEAD, MAX_WEAPONSLOTS, W_NextWeaponOnImpulse(), weaponentities, and X.
 {
     if (IS_DEAD(this))
     {
         this.impulse = imp;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_NextWeaponOnImpulse(this, number, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
X (1)
X (0 , prev)
prev X (2 , prev)
prev prev X (4 , prev)
prev prev prev X (6 , prev)
prev prev prev prev X (8 , prev)
prev prev prev prev prev X (0 , best)
prev prev prev prev prev best X (2 , best)
prev prev prev prev prev best best X (4 , best)
prev prev prev prev prev best best best X (6 , best)
prev prev prev prev prev best best best best X (8 , best)
prev prev prev prev prev best best best best best X (0 , next)
prev prev prev prev prev best best best best best next X (2 , next)
prev prev prev prev prev best best best best best next next X (4 , next)
prev prev prev prev prev best best best best best next next next X (6 , next)
prev prev prev prev prev best best best best best next next next next X (8 , next)
X (0)
Definition at line 172 of file impulse.qc.
References autocvar_g_weaponswitch_debug, impulse, IS_DEAD, MAX_WEAPONSLOTS, vehicle, W_NextWeapon(), and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_byid.impulse;
         return;
     }
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         W_NextWeapon(this, 0, weaponentity);
         if(autocvar_g_weaponswitch_debug != 1)
             break;
     }
 }
Variable Documentation
int dir
Definition at line 89 of file impulse.qc.
Referenced by _Movetype_FlyMove(), _Movetype_NudgeOutOfSolid_PivotIsKnownGood(), bd_close_editor(), bd_find_dozer(), bd_load_piece(), bd_move_dozer(), CSQC_Demo_Camera(), findtrajectorywithleading(), FireRailgunBullet(), GrapplingHookThink(), havocbot_ai(), havocbot_moveto(), havocbot_movetogoal(), ons_camSetup(), and steerlib_beamsteer().
int int int imp
Initial value:
{
    if (this.vehicle) return
Definition at line 90 of file impulse.qc.
Referenced by if(), KeyBinds_BuildList(), MapVote_InputEvent(), MapVote_MoveDown(), MapVote_MoveLeft(), MapVote_MoveRight(), MapVote_MoveUp(), STATIC_INIT(), weapon_byid_handle(), and weapon_group_handle().
int int number
Definition at line 89 of file impulse.qc.
Referenced by bd_close_editor(), bd_controller_update(), bd_do_fill(), bd_editor_place(), bd_find_dozer(), bd_load_piece(), bd_move_dozer(), bd_valid_tile(), c4_valid_tile(), c4_winning_piece(), minigame_relative_tile(), minigame_tile_name(), nmm_spawn_tile_square(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), pp_valid_move(), pp_valid_tile(), pp_winning_piece(), ps_move(), ps_tile_blacklisted(), ps_valid_tile(), ps_winning_piece(), ShowRespawnCountdown(), Team_SetNumberOfAlivePlayers(), Team_SetNumberOfControlPoints(), ttt_valid_tile(), and ttt_winning_piece().
entity vehicle
Definition at line 21 of file impulse.qc.
Referenced by ClientDisconnect(), ClientKill_Now(), DrownPlayer(), IMPULSE(), player_powerups(), player_regen(), PlayerPreThink(), PlayerUseKey(), PutObserverInServer(), PutPlayerInServer(), TEST(), vehicle_impulse(), weapon_byid_handle(), and X().