Xonotic: menu/anim/keyframe.qc File Reference
keyframe.qc File Reference
#include "keyframe.qh"
#include "../menu.qh"
#include "easing.qh"
#include "../item/container.qh"
Functions
entity makeHostedKeyframe (entity obj, void(entity, float) objSetter, float animDuration, float animStart, float animEnd)
entity makeKeyframe (entity obj, void(entity, float) objSetter, float animDuration, float animStart, float animEnd)
METHOD (Keyframe, addEasing, entity(entity this, float animDurationTime, float animEnd, float(float, float, float, float) func))
float getNewChildStart (entity this)
float getNewChildDuration (entity this, float durationTime)
float getNewChildValue (entity this)
if (other.isFinished(other)) error("Can't add finished anim!")
if (l)
if (this.currentChild)
Variables
entity parent = this
entity l = this.lastChild
else
this firstChild = other
other prevSibling = l
other nextSibling = NULL
this lastChild = other
return animStartValue animDelta
Function Documentation
float getNewChildDuration (entity this, float durationTime)
Definition at line 37 of file keyframe.qc.
References duration, and lastChild.
Referenced by METHOD().
     {
         float maxDura = this.duration;
         if (this.lastChild) maxDura = maxDura - (this.lastChild.startTime + this.lastChild.duration);
         float dura = durationTime;
         if (0 >= dura || dura > maxDura) dura = maxDura;
         return dura;
     }
float getNewChildStart (entity this)
Definition at line 31 of file keyframe.qc.
References lastChild.
Referenced by METHOD().
     {
         if (this.lastChild) return this.lastChild.startTime + this.lastChild.duration;
         else return 0;
     }
float getNewChildValue (entity this)
Definition at line 46 of file keyframe.qc.
References lastChild.
Referenced by METHOD().
     {
         if (this.lastChild) return this.lastChild.startValue + this.lastChild.delta;
         else return this.startValue;
     }
if (other. isFinishedother)
if (l)
Definition at line 62 of file keyframe.qc.
References other.
         {
             l.nextSibling = other;
         }
if (this. currentChild)
Definition at line 82 of file keyframe.qc.
         {
             this.currentChild.tick(this.currentChild, tickTime);
             return this.currentChild.value;
         }
entity makeHostedKeyframe (entity obj, void(entity, float) objSetter, float animDuration, float animStart, float animEnd)
Definition at line 10 of file keyframe.qc.
References anim, entity(), and makeKeyframe().
     {
         entity this = makeKeyframe(obj, objSetter, animDuration, animStart, animEnd);
         anim.addAnim(anim, this);
         return this;
     }
entity makeKeyframe (entity obj, void(entity, float) objSetter, float animDuration, float animStart, float animEnd)
Definition at line 17 of file keyframe.qc.
References entity(), NEW, and time.
Referenced by makeHostedKeyframe().
     {
         entity this = NEW(Keyframe);
         this.configureAnimation(this, obj, objSetter, time, animDuration, animStart, animEnd);
         return this;
     }
METHOD (Keyframe , addEasing , entity(entity this, float animDurationTime, float animEnd, float(float, float, float, float) func))
Definition at line 24 of file keyframe.qc.
References entity(), getNewChildDuration(), getNewChildStart(), getNewChildValue(), makeEasing(), other, and setter().
     {
         entity other = makeEasing(this.object, this.setter, func, getNewChildStart(this), getNewChildDuration(this, animDurationTime), getNewChildValue(this), animEnd);
         this.addAnim(this, other);
         return other;
     }
Variable Documentation
return animStartValue animDelta
Definition at line 88 of file keyframe.qc.
else
Initial value:
{
            this.currentChild = other
Definition at line 67 of file keyframe.qc.
this firstChild = other
Definition at line 69 of file keyframe.qc.
entity l = this.lastChild
Definition at line 60 of file keyframe.qc.
this lastChild = other
Definition at line 74 of file keyframe.qc.
Referenced by getNewChildDuration(), getNewChildStart(), and getNewChildValue().
other nextSibling = NULL
Definition at line 73 of file keyframe.qc.
other parent = this
Definition at line 8 of file keyframe.qc.
other prevSibling = l
Definition at line 72 of file keyframe.qc.