Xonotic: Wyvern Class Reference
Wyvern Class Reference
Public Member Functions
ATTRIB (Monster, m_model, entity)
model
virtual void describe ()
virtual void display ()
virtual void mr_anim ()
(BOTH?) sets animations for monster
virtual void mr_death ()
(SERVER) called when monster dies
virtual void mr_pain ()
(SERVER) called when monster is damaged
virtual void mr_precache ()
(BOTH) precaches models/sounds used by this monster
virtual void mr_setup ()
(SERVER) setup monster data
virtual void mr_think ()
(SERVER) logic to run every frame
Public Attributes
vector maxs = '20 20 20'
vector mins = '-20 -20 -58'
string monster_name = _("Wyvern")
int monsterid = 0
string netname = "wyvern"
int spawnflags = MONSTER_TYPE_FLY | MONSTER_SIZE_BROKEN | MON_FLAG_RANGED | MON_FLAG_RIDE
Detailed Description
Definition at line 9 of file wyvern.qh.
Member Function Documentation
Monster::ATTRIB (Monster , m_model , entity) inherited
model
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Monster::mr_anim () inline virtual inherited
(BOTH?) sets animations for monster
Definition at line 56 of file monster.qh.
References TC.
Referenced by Monster_UpdateModel(), and monsters_animoverride().
 { TC(Monster, this); return false; }
virtual void Monster::mr_death () inline virtual inherited
(SERVER) called when monster dies
Definition at line 50 of file monster.qh.
References TC.
Referenced by Monster_Dead().
 { TC(Monster, this); return false; }
virtual void Monster::mr_pain () inline virtual inherited
(SERVER) called when monster is damaged
Definition at line 54 of file monster.qh.
References TC.
Referenced by Monster_Damage().
 { TC(Monster, this); return damage_take; }
virtual void Monster::mr_precache () inline virtual inherited
(BOTH) precaches models/sounds used by this monster
Definition at line 52 of file monster.qh.
References TC.
 { TC(Monster, this); return false; }
virtual void Monster::mr_setup () inline virtual inherited
(SERVER) setup monster data
Definition at line 46 of file monster.qh.
References TC.
Referenced by Monster_Spawn_Setup().
 { TC(Monster, this); return false; }
virtual void Monster::mr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 48 of file monster.qh.
References TC.
Referenced by Monster_Think().
 { TC(Monster, this); return false; }
Member Data Documentation
vector Wyvern::maxs = '20 20 20'
Definition at line 12 of file wyvern.qh.
vector Wyvern::mins = '-20 -20 -58'
Definition at line 11 of file wyvern.qh.
string Wyvern::monster_name = _("Wyvern")
Definition at line 17 of file wyvern.qh.
int Monster::monsterid = 0 inherited
Definition at line 31 of file monster.qh.
string Wyvern::netname = "wyvern"
Definition at line 16 of file wyvern.qh.
int Wyvern::spawnflags = MONSTER_TYPE_FLY | MONSTER_SIZE_BROKEN | MON_FLAG_RANGED | MON_FLAG_RIDE
Definition at line 10 of file wyvern.qh.
The documentation for this class was generated from the following file:
common/monsters/monster/wyvern.qh