Xonotic: common/minigames/minigame/pp.qc File Reference
pp.qc File Reference
#include "pp.qh"
Functions
entity pp_find_piece (entity minig, string tile)
void pp_move (entity minigame, entity player, string pos)
void pp_next_match (entity minigame, entity player)
void pp_setup_pieces (entity minigame)
bool pp_valid_move (entity minigame, string pos)
bool pp_valid_tile (string tile)
bool pp_winning_piece (entity piece)
REGISTER_MINIGAME (pp, _("Push-Pull"))
Variables
int cnt
const int PP_BLOCKED_TEAM = 5
entity pp_curr_piece
const int PP_LET_CNT = 7
int pp_nexteam
const int PP_NUM_CNT = 7
int pp_team1_score
int pp_team2_score
const int PP_TILE_SIZE = 7
const int PP_TURN_DRAW = 0x0400
const int PP_TURN_NEXT = 0x0800
const int PP_TURN_PLACE = 0x0100
const int PP_TURN_TEAM = 0x000f
const int PP_TURN_TEAM1 = 0x0001
const int PP_TURN_TEAM2 = 0x0002
const int PP_TURN_TYPE = 0x0f00
const int PP_TURN_WIN = 0x0200
Function Documentation
entity pp_find_piece (entity minig, string tile)
Definition at line 31 of file pp.qc.
References entity(), findentity(), NULL, and owner.
Referenced by pp_move(), pp_valid_move(), and pp_winning_piece().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile )
             return e;
     return NULL;
 }
void pp_move (entity minigame, entity player, string pos)
Definition at line 98 of file pp.qc.
References entity(), MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_next_team(), minigame_server_sendflags(), msle_spawn(), pp_find_piece(), PP_TURN_DRAW, pp_valid_move(), pp_winning_piece(), strfree, and strzone().
Referenced by pp_next_match().
 {
     if ( minigame.minigame_flags & PP_TURN_PLACE )
     if ( pos && player.team == (minigame.minigame_flags & PP_TURN_TEAM) )
     {
         if ( pp_valid_move(minigame,pos))
         {
             entity existing = pp_find_piece(minigame,pos);
             if(existing && existing.team != 5)
             {
                 if(existing.team == 1)
                     minigame.pp_team1_score++;
                 if(existing.team == 2)
                     minigame.pp_team2_score++;
             }
             if(minigame.pp_curr_piece)
             {
                 minigame.pp_curr_piece.cnt = 0;
                 minigame.pp_curr_piece.team = 5;
                 minigame_server_sendflags(minigame.pp_curr_piece,MINIG_SF_ALL);
             }
             if(existing)
             {
                 strfree(existing.netname);
                 delete(existing);
             }
             entity piece = msle_spawn(minigame,"minigame_board_piece");
             piece.cnt = 1;
             piece.team = player.team; // temporary
             piece.netname = strzone(pos);
             minigame_server_sendflags(piece,MINIG_SF_ALL);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
             minigame.pp_nexteam = minigame_next_team(player.team,2);
             minigame.pp_curr_piece = piece;
             if ( pp_winning_piece(piece) )
             {
                 if(minigame.pp_team1_score == minigame.pp_team2_score)
                     minigame.minigame_flags = PP_TURN_DRAW;
                 else
                     minigame.minigame_flags = PP_TURN_WIN | ((minigame.pp_team1_score > minigame.pp_team2_score) ? 1 : 2);
             }
             else
                 minigame.minigame_flags = PP_TURN_PLACE | minigame.pp_nexteam;
         }
     }
 }
void pp_next_match (entity minigame, entity player)
Definition at line 172 of file pp.qc.
References active_minigame, argv(), drawfill(), DRAWFLAG_ADDITIVE, DRAWFLAG_NORMAL, drawpic(), drawstring(), entity(), eX, eY, findentity(), FOREACH_MINIGAME_ENTITY, ftos(), hud_fontsize, HUD_MinigameMenu_CustomEntry(), HUD_Panel_DrawBg, int, K_DOWNARROW, K_ENTER, K_KP_DOWNARROW, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, K_SPACE, K_UPARROW, MINIG_SF_UPDATE, minigame_cmd, minigame_count_players(), minigame_drawcolorcodedstring_trunc(), minigame_drawcolorcodedstring_wrapped(), minigame_drawpic_centered(), minigame_drawstring_wrapped(), minigame_hud_denormalize(), minigame_hud_denormalize_size(), minigame_hud_fitsqare, minigame_hud_normalize(), minigame_hud_simpleboard(), minigame_next_team(), minigame_prompt(), minigame_relative_tile(), minigame_self, minigame_server_sendflags(), minigame_texture(), minigame_tile_name(), minigame_tile_pos(), mousepos, NULL, owner, panel_fg_alpha, pp_move(), pp_setup_pieces(), PP_TURN_TEAM1, pp_valid_move(), pp_valid_tile(), strcat(), strcpy, strfree, string_null, strzone(), vector(), and WriteByte().
 {
 #ifdef SVQC
     // on multiplayer matches, wait for both players to agree
     if ( minigame.minigame_flags & (PP_TURN_WIN|PP_TURN_DRAW) )
     {
         minigame.minigame_flags = PP_TURN_NEXT | player.team;
         minigame.SendFlags |= MINIG_SF_UPDATE;
     }
     else if ( (minigame.minigame_flags & PP_TURN_NEXT) &&
             !( minigame.minigame_flags & player.team ) )
 #endif
     {
         minigame.minigame_flags = PP_TURN_PLACE | minigame.pp_nexteam;
         minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         entity e = NULL;
         while ( ( e = findentity(e,owner,minigame) ) )
             if ( e.classname == "minigame_board_piece" )
                 delete(e);
         minigame.pp_team1_score = 0;
         minigame.pp_team2_score = 0;
         pp_setup_pieces(minigame);
     }
 }
void pp_setup_pieces (entity minigame)
Definition at line 149 of file pp.qc.
References entity(), MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_buildname(), msle_spawn(), NULL, PP_LET_CNT, PP_NUM_CNT, and strzone().
Referenced by pp_next_match().
 {
     int i, t; // letter, number
     for(i = 0; i < PP_LET_CNT; ++i)
     for(t = 0; t < PP_NUM_CNT; ++t)
     {
         bool t2_true = ((i == 0 || i == 6) && t > 0 && t < 6);
         bool t1_true = (i > 0 && i < 6 && (t == 0 || t == 6));
         if(t1_true || t2_true)
         {
             entity piece = msle_spawn(minigame,"minigame_board_piece");
             piece.team = ((t1_true) ? 1 : 2);
             piece.netname = strzone(minigame_tile_buildname(i,t));
             minigame_server_sendflags(piece,MINIG_SF_ALL);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         }
     }
     minigame.pp_curr_piece = NULL;
 }
bool pp_valid_move (entity minigame, string pos)
Definition at line 70 of file pp.qc.
References entity(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), pp_find_piece(), pp_valid_tile(), and team.
Referenced by pp_move(), and pp_next_match().
 {
     if(!pp_valid_tile(pos))
         return false;
     if(pp_find_piece(minigame,pos).team == 5)
         return false;
     entity current = minigame.pp_curr_piece;
     if(!current)
         return true; // no current piece? allow the move anywhere
     int number = minigame_tile_number(pos);
     int letter = minigame_tile_letter(pos);
     if( (pp_find_piece(minigame,minigame_tile_buildname(letter-1,number)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter+1,number)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter,number-1)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter,number+1)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter+1,number+1)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter-1,number-1)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter+1,number-1)) == current)
     ||  (pp_find_piece(minigame,minigame_tile_buildname(letter-1,number+1)) == current)
     ) { return true; }
     return false;
 }
bool pp_valid_tile (string tile)
Definition at line 41 of file pp.qc.
References minigame_tile_letter(), minigame_tile_number(), and PP_LET_CNT.
Referenced by pp_next_match(), pp_valid_move(), and pp_winning_piece().
 {
     if ( !tile )
         return 0;
     int number = minigame_tile_number(tile);
     int letter = minigame_tile_letter(tile);
     return 0 <= number && number < PP_NUM_CNT && 0 <= letter && letter < PP_LET_CNT;
 }
bool pp_winning_piece (entity piece)
Definition at line 51 of file pp.qc.
References minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), pp_find_piece(), pp_valid_tile(), and team.
Referenced by pp_move().
 {
     int number = minigame_tile_number(piece.netname);
     int letter = minigame_tile_letter(piece.netname);
     // here goes
     if(!pp_valid_tile(minigame_tile_buildname(letter-1,number)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter-1,number)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter+1,number)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter+1,number)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter,number-1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter,number-1)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter,number+1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter,number+1)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter+1,number+1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter+1,number+1)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter-1,number-1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter-1,number-1)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter+1,number-1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter+1,number-1)).team == 5)
     if(!pp_valid_tile(minigame_tile_buildname(letter-1,number+1)) || pp_find_piece(piece.owner,minigame_tile_buildname(letter-1,number+1)).team == 5)
         return true;
     return false;
 }
REGISTER_MINIGAME (pp , _("Push-Pull"))
Variable Documentation
int cnt
Definition at line 21 of file pp.qc.
Referenced by a_think(), AppendItemcodes(), AuxiliaryXhair_customize(), AuxiliaryXhair_Draw2D(), basketball_touch(), ClientInit_CheckUpdate(), ClientInit_misc(), ctf_SpawnTeam(), dom_controlpoint_setup(), dompoint_captured(), dompointtouch(), DragBox_Think(), football_touch(), InitBall(), kh_Controller_Think(), kh_Key_Think(), KillIndicator_Think(), Monster_Delay_Action(), NET_HANDLE(), physical_item_damage(), physical_item_think(), physical_item_touch(), PingPLReport_Think(), Portal_RemoveLater_Think(), Projectile_Draw(), Projectile_DrawTrail(), PutPlayerInServer(), RandomSeed_Send(), RandomSeed_Think(), relocate_spawnpoint(), ResetBall(), round_handler_Init(), round_handler_Reset(), round_handler_Think(), SendAuxiliaryXhair(), spawnfunc(), target_assault_roundend_reset(), tdm_SpawnTeam(), trigger_push_findtarget(), turret_gib_draw(), vehicles_gib_think(), W_LastWeapon(), W_SwitchWeapon_Force(), and XonoticGametypeList_loadCvars().
const int PP_BLOCKED_TEAM = 5
Definition at line 14 of file pp.qc.
entity pp_curr_piece
Definition at line 28 of file pp.qc.
const int PP_LET_CNT = 7
Definition at line 16 of file pp.qc.
Referenced by pp_setup_pieces(), and pp_valid_tile().
int pp_nexteam
Definition at line 26 of file pp.qc.
const int PP_NUM_CNT = 7
Definition at line 17 of file pp.qc.
Referenced by pp_setup_pieces().
int pp_team1_score
Definition at line 23 of file pp.qc.
int pp_team2_score
Definition at line 24 of file pp.qc.
const int PP_TILE_SIZE = 7
Definition at line 19 of file pp.qc.
const int PP_TURN_DRAW = 0x0400
Definition at line 6 of file pp.qc.
Referenced by pp_move().
const int PP_TURN_NEXT = 0x0800
Definition at line 7 of file pp.qc.
const int PP_TURN_PLACE = 0x0100
Definition at line 4 of file pp.qc.
const int PP_TURN_TEAM = 0x000f
Definition at line 12 of file pp.qc.
const int PP_TURN_TEAM1 = 0x0001
Definition at line 10 of file pp.qc.
Referenced by pp_next_match().
const int PP_TURN_TEAM2 = 0x0002
Definition at line 11 of file pp.qc.
const int PP_TURN_TYPE = 0x0f00
Definition at line 8 of file pp.qc.
const int PP_TURN_WIN = 0x0200
Definition at line 5 of file pp.qc.