Xonotic: common/vehicles/vehicle.qh File Reference
vehicle.qh File Reference
Classes
class Vehicle
Variables
entity tur_head
This ent is a player slot on a multi-person vehicle.
const int VHF_DEATHEJECT = BIT(6)
Vehicles energy regenerates.
const int VHF_DMGHEADROLL = BIT(12)
Add random angles each frame if health < 50%.
const int VHF_DMGROLL = BIT(11)
Add random velocity each frame if health < 50%.
const int VHF_DMGSHAKE = BIT(10)
Vehicle is airborn.
const int VHF_ENERGYREGEN = BIT(5)
Vehicles health regenerates.
const int VHF_HASSHIELD = BIT(2)
Indicates vehicle.
const int VHF_HEALTHREGEN = BIT(4)
Vehicles shield regenerates.
const int VHF_ISVEHICLE = BIT(1)
const int VHF_MOVE_FLY = BIT(9)
Vehicle hover close to gound.
const int VHF_MOVE_GROUND = BIT(7)
Vehicle ejects pilot upon fatal damage.
const int VHF_MOVE_HOVER = BIT(8)
Vehicle moves on gound.
const int VHF_MULTISLOT = BIT(13)
Add random head angles each frame if health < 50%.
const int VHF_PLAYERSLOT = BIT(14)
Vehicle has multiple player slots.
const int VHF_SHIELDREGEN = BIT(3)
Vehicle has shileding.
Variable Documentation
entity tur_head
This ent is a player slot on a multi-person vehicle.
Definition at line 79 of file vehicle.qh.
const int VHF_DEATHEJECT = BIT(6)
Vehicles energy regenerates.
Definition at line 68 of file vehicle.qh.
Referenced by vehicles_damage().
const int VHF_DMGHEADROLL = BIT(12)
Add random angles each frame if health < 50%.
Definition at line 74 of file vehicle.qh.
Referenced by vehicles_painframe().
const int VHF_DMGROLL = BIT(11)
Add random velocity each frame if health < 50%.
Definition at line 73 of file vehicle.qh.
Referenced by vehicles_painframe().
const int VHF_DMGSHAKE = BIT(10)
Vehicle is airborn.
Definition at line 72 of file vehicle.qh.
Referenced by vehicles_painframe().
const int VHF_ENERGYREGEN = BIT(5)
Vehicles health regenerates.
Definition at line 67 of file vehicle.qh.
const int VHF_HASSHIELD = BIT(2)
Indicates vehicle.
Definition at line 64 of file vehicle.qh.
Referenced by vehicles_damage().
const int VHF_HEALTHREGEN = BIT(4)
Vehicles shield regenerates.
Definition at line 66 of file vehicle.qh.
const int VHF_ISVEHICLE = BIT(1)
Definition at line 63 of file vehicle.qh.
Referenced by vehicle_initialize().
const int VHF_MOVE_FLY = BIT(9)
Vehicle hover close to gound.
Definition at line 71 of file vehicle.qh.
const int VHF_MOVE_GROUND = BIT(7)
Vehicle ejects pilot upon fatal damage.
Definition at line 69 of file vehicle.qh.
const int VHF_MOVE_HOVER = BIT(8)
Vehicle moves on gound.
Definition at line 70 of file vehicle.qh.
const int VHF_MULTISLOT = BIT(13)
Add random head angles each frame if health < 50%.
Definition at line 75 of file vehicle.qh.
Referenced by PlayerPreThink(), PlayerUseKey(), vehicle_addplayerslot(), and vehicles_enter().
const int VHF_PLAYERSLOT = BIT(14)
Vehicle has multiple player slots.
Definition at line 76 of file vehicle.qh.
Referenced by antilag_record(), antilag_restore(), antilag_takeback(), vehicle_addplayerslot(), and vehicles_exit().
const int VHF_SHIELDREGEN = BIT(3)
Vehicle has shileding.
Definition at line 65 of file vehicle.qh.
Referenced by vehicles_enter(), and vehicles_exit().