Xonotic: common/mapobjects/func/ladder.qc File Reference
ladder.qc File Reference
#include "ladder.qh"
Functions
void func_ladder_think (entity this)
Function Documentation
void func_ladder_think (entity this)
Definition at line 4 of file ladder.qc.
References absmax, absmin, bot_pickup, boxesoverlap(), classname, DPCONTENTS_BODY, DPCONTENTS_BOTCLIP, DPCONTENTS_PLAYERCLIP, DPCONTENTS_SOLID, drawmask, entity(), g_drawables, g_ladderents, g_ladders, IL_EACH, IL_PUSH(), IS_CSQC, IS_DEAD, IS_PLAYER, jumpstepheightvec, MASK_NORMAL, min(), MOVE_NOMONSTERS, move_time, MOVETYPE_NOCLIP, NET_HANDLE, nextthink, PL_MAX_CONST, PL_MIN_CONST, ReadString, setthink, skin, solid, SOLID_BSP, SOLID_TRIGGER, spawn(), spawnfunc(), speed, stepheightvec, strfree, strzone(), time, to, trace_endpos, trace_startsolid, vector(), vlen(), WarpZoneLib_BoxTouchesBrush(), waypoint_getlinearcost(), waypoint_spawnforteleporter_boxes(), WAYPOINTFLAG_LADDER, WriteByte(), WriteCoord(), and WriteString().
 {
 #ifdef CSQC
     // TODO: check if this is what is causing the glitchiness when switching between them
     float dt = time - this.move_time;
     this.move_time = time;
     if(dt <= 0) { return; }
 #endif
     // set myself as current ladders where possible
     IL_EACH(g_ladderents, it.ladder_entity == this,
     {
         it.ladder_entity = NULL;
         IL_REMOVE(g_ladderents, it);
     });
     FOREACH_ENTITY_RADIUS((this.absmin + this.absmax) * 0.5, vlen(this.absmax - this.absmin) * 0.5 + 1, !it.ladder_entity && IS_PLAYER(it) && it.move_movetype != MOVETYPE_NOCLIP && !IS_DEAD(it),
     {
         vector emin = it.absmin;
         vector emax = it.absmax;
         if(this.solid == SOLID_BSP || (IS_CSQC && this.solid == SOLID_TRIGGER)) // CSQC doesn't expand properly
         {
             emin -= '1 1 1';
             emax += '1 1 1';
         }
         if(boxesoverlap(emin, emax, this.absmin, this.absmax)) // quick
         {
             if(WarpZoneLib_BoxTouchesBrush(emin, emax, this, it)) // accurate
             {
                 if(!it.ladder_entity)
                     IL_PUSH(g_ladderents, it);
                 it.ladder_entity = this;
             }
         }
     });
 #ifdef SVQC
     this.nextthink = time;
 #endif
 }