Xonotic: server/elimination.qh File Reference
elimination.qh File Reference
Functions
void EliminatedPlayers_Init (float(entity) isEliminated_func)
Variables
entity eliminatedPlayers
Function Documentation
EliminatedPlayers_Init()
void EliminatedPlayers_Init (float(entity) isEliminated_func)
Definition at line 27 of file elimination.qc.
References backtrace, eliminatedPlayers, EliminatedPlayers_SendEntity(), and new_pure.
Referenced by freezetag_Initialize(), and REGISTER_MUTATOR().
 {
     if(eliminatedPlayers)
     {
         backtrace("Can't spawn eliminatedPlayers again!");
         return;
     }
     Net_LinkEntity(eliminatedPlayers = new_pure(eliminatedPlayers), false, 0, EliminatedPlayers_SendEntity);
     eliminatedPlayers.isEliminated = isEliminated_func;
 }
Variable Documentation
eliminatedPlayers
entity eliminatedPlayers
Definition at line 3 of file elimination.qh.
Referenced by EliminatedPlayers_Init(), EliminatedPlayers_SendEntity(), freezetag_count_alive_players(), and MUTATOR_HOOKFUNCTION().