Xonotic: menu/xonotic/slider_picmip.qc File Reference
slider_picmip.qc File Reference
#include "slider_picmip.qh"
Functions
entity makeXonoticPicmipSlider ()
float texmemsize (float s3tc)
void XonoticPicmipSlider_autofix (entity me)
void XonoticPicmipSlider_configureXonoticPicmipSlider (entity me)
void XonoticPicmipSlider_draw (entity me)
Function Documentation
entity makeXonoticPicmipSlider ()
Definition at line 3 of file slider_picmip.qc.
References entity(), and NEW.
Referenced by XonoticEffectsSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticPicmipSlider);
     me.configureXonoticPicmipSlider(me);
     return me;
 }
float texmemsize (float s3tc)
Definition at line 17 of file slider_picmip.qc.
References cvar(), and max().
Referenced by XonoticPicmipSlider_autofix().
 {
     return
     (
           2500 * (0.25 ** max(0, cvar("gl_picmip") + cvar("gl_picmip_other")))
         + 1500 * (0.25 ** max(0, cvar("gl_picmip") + cvar("gl_picmip_world")))
     ) * ((s3tc && (cvar("r_texture_dds_load") || cvar("gl_texturecompression"))) ? 0.2 : 1.0); // TC: normalmaps 50%, other 25%, few incompressible, guessing 40% as conservative average
 }
void XonoticPicmipSlider_autofix (entity me)
Definition at line 25 of file slider_picmip.qc.
References cvar(), and texmemsize().
 {
     float max_hard, max_soft;
     if(cvar("menu_picmip_bypass"))
         return;
     max_hard = cvar("sys_memsize_virtual");
     max_soft = cvar("sys_memsize_physical");
     if(max_hard > 0)
     {
         while(me.value > 0 && texmemsize(me.have_s3tc) > max_hard)
             me.setValue(me, me.value - 1);
     }
     // TODO also check the soft limit!
     // TODO better handling than clamping the slider!
 }
void XonoticPicmipSlider_configureXonoticPicmipSlider (entity me)
Definition at line 10 of file slider_picmip.qc.
References GL_Have_TextureCompression().
 {
     me.configureXonoticTextSlider(me, "gl_picmip",
         _("Change the sharpness of the textures. Lowering it will effectively reduce texture memory usage, but make the textures appear very blurry. (default: good)"));
     me.autofix(me);
     me.have_s3tc = GL_Have_TextureCompression();
 }
void XonoticPicmipSlider_draw (entity me)
Definition at line 40 of file slider_picmip.qc.
References SUPER.
 {
     me.autofix(me);
     SUPER(XonoticPicmipSlider).draw(me);
 }