Xonotic: server/weapons/common.qc File Reference
common.qc File Reference
#include "common.qh"
#include <common/constants.qh>
#include <common/deathtypes/all.qh>
#include <common/items/_mod.qh>
#include <common/net_linked.qh>
#include <common/notifications/all.qh>
#include <common/state.qh>
#include <common/stats.qh>
#include <common/util.qh>
#include <common/weapons/_all.qh>
#include <common/wepent.qh>
#include <server/command/common.qh>
#include <server/damage.qh>
#include <server/hook.qh>
#include <server/items/items.qh>
#include <server/mutators/_mod.qh>
#include <server/weapons/csqcprojectile.qh>
Functions
void adaptor_think2use_hittype_splash (entity this)
bool SUB_NoImpactCheck (entity this, entity toucher)
float W_CheckProjectileDamage (entity inflictor, entity projowner, int deathtype, float exception)
bool W_DualWielding (entity player)
void W_GiveWeapon (entity e, int wep)
void W_PlayStrengthSound (entity player)
void W_PrepareExplosionByDamage (entity this, entity attacker, void(entity this) explode)
bool WarpZone_Projectile_Touch_ImpactFilter_Callback (entity this, entity toucher)
Function Documentation
adaptor_think2use_hittype_splash()
void adaptor_think2use_hittype_splash (entity this)
Definition at line 119 of file common.qc.
References HITTYPE_SPLASH, IS_ONGROUND, and projectiledeathtype.
 {
     if(!(IS_ONGROUND(this))) // if onground, we ARE touching something, but HITTYPE_SPLASH is to be networked if the damage causing projectile is not touching ANYTHING
         this.projectiledeathtype |= HITTYPE_SPLASH;
     adaptor_think2use(this);
 }
SUB_NoImpactCheck()
bool SUB_NoImpactCheck (entity this, entity toucher)
Definition at line 126 of file common.qc.
References checkclient, classname, LOG_TRACE, LOG_TRACEF, maxs, mins, MOVE_NORMAL, normalize(), NULL, origin, Q3SURFACEFLAG_NOIMPACT, size, sys_frametime, trace_dphitcontents, trace_dphitq3surfaceflags, trace_fraction, vector(), velocity, and vlen().
Referenced by WarpZone_Projectile_Touch_ImpactFilter_Callback().
 {
     // zero hitcontents = this is not the real impact, but either the
     // mirror-impact of something hitting the projectile instead of the
     // projectile hitting the something, or a touchareagrid one. Neither of
     // these stop the projectile from moving, so...
     if(trace_dphitcontents == 0)
     {
         LOG_TRACEF("A hit from a projectile happened with no hit contents! DEBUG THIS, this should never happen for projectiles! Projectile will self-destruct. (edict: %i, classname: %s, origin: %v)", this, this.classname, this.origin);
         checkclient(this); // TODO: .health is checked in the engine with this, possibly replace with a QC function?
     }
     if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOIMPACT)
         return true;
     if (toucher == NULL && this.size != '0 0 0')
     {
         vector tic;
         tic = this.velocity * sys_frametime;
         tic = tic + normalize(tic) * vlen(this.maxs - this.mins);
         traceline(this.origin - tic, this.origin + tic, MOVE_NORMAL, this);
         if (trace_fraction >= 1)
         {
             LOG_TRACE("Odd... did not hit...?");
         }
         else if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOIMPACT)
         {
             LOG_TRACE("Detected and prevented the sky-grapple bug.");
             return true;
         }
     }
     return false;
 }
W_CheckProjectileDamage()
float W_CheckProjectileDamage (entity inflictor, entity projowner, int deathtype, float exception)
Definition at line 58 of file common.qc.
References autocvar_g_projectiles_damage.
Referenced by GrapplingHook_Damage().
 {
     float is_from_contents = (deathtype == DEATH_SLIME.m_id || deathtype == DEATH_LAVA.m_id);
     float is_from_owner = (inflictor == projowner);
     float is_from_exception = (exception != -1);
     //dprint(strcat("W_CheckProjectileDamage: from_contents ", ftos(is_from_contents), " : from_owner ", ftos(is_from_owner), " : exception ", strcat(ftos(is_from_exception), " (", ftos(exception), "). \n")));
     if(autocvar_g_projectiles_damage <= -2)
     {
         return false; // no damage to projectiles at all, not even with the exceptions
     }
     else if(autocvar_g_projectiles_damage == -1)
     {
         if(is_from_exception)
             return (exception); // if exception is detected, allow it to override
         else
             return false; // otherwise, no other damage is allowed
     }
     else if(autocvar_g_projectiles_damage == 0)
     {
         if(is_from_exception)
             return (exception); // if exception is detected, allow it to override
         else if(!is_from_contents)
             return false; // otherwise, only allow damage from contents
     }
     else if(autocvar_g_projectiles_damage == 1)
     {
         if(is_from_exception)
             return (exception); // if exception is detected, allow it to override
         else if(!(is_from_contents || is_from_owner))
             return false; // otherwise, only allow self damage and damage from contents
     }
     else if(autocvar_g_projectiles_damage == 2) // allow any damage, but override for exceptions
     {
         if(is_from_exception)
             return (exception); // if exception is detected, allow it to override
     }
     return true; // if none of these return, then allow damage anyway.
 }
W_DualWielding()
bool W_DualWielding (entity player)
Definition at line 20 of file common.qc.
References MAX_WEAPONSLOTS, and weaponentities.
Referenced by IMPULSE(), PlayerThink(), W_ResetGunAlign(), W_SetupShot_Dir_ProjectileSize_Range(), and weapon_prepareattack_do().
 {
     int held_weapons = 0;
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         if(player.(weaponentity) && player.(weaponentity).m_switchweapon != WEP_Null)
             ++held_weapons;
     }
     return held_weapons > 1;
 }
W_GiveWeapon()
void W_GiveWeapon (entity e, int wep)
Definition at line 33 of file common.qc.
References IS_PLAYER, REGISTRY_GET, and WepSet_FromWeapon.
Referenced by Item_GiveTo(), and TEST().
 {
     if (!wep) return;
     STAT(WEAPONS, e) |= WepSet_FromWeapon(REGISTRY_GET(Weapons, wep));
     if (IS_PLAYER(e)) {
         Send_Notification(NOTIF_ONE, e, MSG_MULTI, ITEM_WEAPON_GOT, wep);
     }
 }
W_PlayStrengthSound()
void W_PlayStrengthSound (entity player)
Definition at line 44 of file common.qc.
References ATTEN_NORM, autocvar_sv_strengthsound_antispam_refire_threshold, autocvar_sv_strengthsound_antispam_time, CH_TRIGGER, entity(), IS_PLAYER, PS, sound, time, and VOL_BASE.
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     entity store = IS_PLAYER(player) ? PS(player) : player; // because non-player entities can fire, but can they have items? TODO
     if((player.items & ITEM_Strength.m_itemid)
         && ((time > store.prevstrengthsound + autocvar_sv_strengthsound_antispam_time) // prevent insane sound spam
         || (time > store.prevstrengthsoundattempt + autocvar_sv_strengthsound_antispam_refire_threshold)))
         {
             sound(player, CH_TRIGGER, SND_STRENGTH_FIRE, VOL_BASE, ATTEN_NORM);
             store.prevstrengthsound = time;
         }
         store.prevstrengthsoundattempt = time;
 }
W_PrepareExplosionByDamage()
void W_PrepareExplosionByDamage (entity this, entity attacker, void(entity this) explode)
Definition at line 100 of file common.qc.
References autocvar_g_projectiles_keep_owner, DAMAGE_NO, func_null(), IS_CLIENT, MUTATOR_CALLHOOK, nextthink, owner, realowner, setthink, takedamage, and time.
 {
     this.takedamage = DAMAGE_NO;
     this.event_damage = func_null;
     MUTATOR_CALLHOOK(PrepareExplosionByDamage, this, attacker);
     if(IS_CLIENT(attacker) && !autocvar_g_projectiles_keep_owner)
     {
         this.owner = attacker;
         this.realowner = attacker;
     }
     // do not explode NOW but in the NEXT FRAME!
     // because recursive calls to RadiusDamage are not allowed
     this.nextthink = time;
     setthink(this, explode);
 }
WarpZone_Projectile_Touch_ImpactFilter_Callback()
bool WarpZone_Projectile_Touch_ImpactFilter_Callback (entity this, entity toucher)
Definition at line 159 of file common.qc.
References classname, owner, RemoveHook(), SOLID_TRIGGER, SUB_NoImpactCheck(), trace_ent, and UpdateCSQCProjectile().
Referenced by WarpZone_Projectile_Touch().
 {
     // owner check
     if(toucher && toucher == this.owner)
         return true;
     if(SUB_NoImpactCheck(this, toucher))
     {
         if(this.classname == "nade")
             return false; // no checks here
         else if(this.classname == "grapplinghook")
             RemoveHook(this);
         else
             delete(this);
         return true;
     }
     if(trace_ent && trace_ent.solid > SOLID_TRIGGER)
         UpdateCSQCProjectile(this);
     return false;
 }