Xonotic: menu/xonotic/checkbox.qh File Reference
checkbox.qh File Reference
#include "../item/checkbox.qh"
Functions
METHOD (XonoticCheckBox, configureXonoticCheckBox, void(entity, float, float, string, string, string))
METHOD (XonoticCheckBox, setChecked, void(entity, float))
METHOD (XonoticCheckBox, loadCvars, void(entity))
METHOD (XonoticCheckBox, saveCvars, void(entity))
entity makeXonoticCheckBox_T (float, string, string, string)
entity makeXonoticCheckBox (float, string, string)
entity makeXonoticCheckBoxEx_T (float, float, string, string, string)
entity makeXonoticCheckBoxEx (float, float, string, string)
Function Documentation
entity makeXonoticCheckBox (float , string , string)
Definition at line 28 of file checkbox.qc.
 {
     return makeXonoticCheckBox_T(isInverted, theCvar, theText, string_null);
 }
entity makeXonoticCheckBox_T (float , string , string , string)
Definition at line 3 of file checkbox.qc.
References makeXonoticCheckBoxEx_T(), and n.
Referenced by makeXonoticCheckBox(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticServerListTab_fill(), XonoticUserSettingsTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     float y, n;
     if(isInverted > 1)
     {
         n = isInverted - 1;
         y = -n;
     }
     else if(isInverted < -1)
     {
         n = isInverted + 1;
         y = -n;
     }
     else if(isInverted == 1)
     {
         n = 1;
         y = 0;
     }
     else
     {
         n = 0;
         y = 1;
     }
     return makeXonoticCheckBoxEx_T(y, n, theCvar, theText, theTooltip);
 }
entity makeXonoticCheckBoxEx (float , float , string , string)
Definition at line 40 of file checkbox.qc.
References makeXonoticCheckBoxEx_T(), and string_null.
Referenced by XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticScreenshotBrowserTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCheckBoxEx_T(theYesValue, theNoValue, theCvar, theText, string_null);
 }
entity makeXonoticCheckBoxEx_T (float , float , string , string , string)
Definition at line 33 of file checkbox.qc.
References entity(), me, and NEW.
Referenced by makeXonoticCheckBox_T(), makeXonoticCheckBoxEx(), XonoticEffectsSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), and XonoticGameViewSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticCheckBox);
     me.configureXonoticCheckBox(me, theYesValue, theNoValue, theCvar, theText, theTooltip);
     return me;
 }
METHOD (XonoticCheckBox , configureXonoticCheckBox , void(entity, float, float, string, string, string))
METHOD (XonoticCheckBox , setChecked , void(entity, float))
METHOD (XonoticCheckBox , loadCvars , void(entity))
METHOD (XonoticCheckBox , saveCvars , void(entity))