Xonotic: lib/csqcmodel/cl_player.qc File Reference
cl_player.qc File Reference
#include "cl_player.qh"
#include "cl_model.qh"
#include "common.qh"
#include "interpolate.qh"
#include <client/defs.qh>
#include <client/main.qh>
#include <common/constants.qh>
#include <common/physics/player.qh>
#include <common/stats.qh>
#include <common/triggers/trigger/viewloc.qh>
#include <common/util.qh>
#include <common/viewloc.qh>
Functions
void _Movetype_Physics_ClientFrame (entity this, float movedt)
void CSQC_ClientMovement_PlayerMove_Frame (entity this)
void CSQCPlayer_CheckWater (entity this)
vector CSQCPlayer_GetPredictionErrorO ()
vector CSQCPlayer_GetPredictionErrorV ()
bool CSQCPlayer_IsLocalPlayer (entity this)
void CSQCPlayer_Physics (entity this)
bool CSQCPlayer_PostUpdate (entity this)
void CSQCPlayer_PredictTo (entity this, float endframe, bool apply_error)
bool CSQCPlayer_PreUpdate (entity this)
void CSQCPlayer_Remove (entity this)
void CSQCPlayer_SavePrediction (entity this)
void CSQCPlayer_SetCamera ()
Called once per CSQC_UpdateView()
void CSQCPlayer_SetMinsMaxs (entity this)
void CSQCPlayer_SetPredictionError (vector o, vector v, float onground_diff)
void CSQCPlayer_SetViewLocation ()
void CSQCPlayer_Unpredict (entity this)
void Movetype_Physics_Spam (entity this)
Variables
float autocvar_cl_movement_errorcompensation = 0
float csqcplayer_moveframe
vector csqcplayer_origin
float csqcplayer_predictionerrorfactor
vector csqcplayer_predictionerroro
float csqcplayer_predictionerrortime
vector csqcplayer_predictionerrorv
float csqcplayer_sequence
vector csqcplayer_velocity
int player_pmflags
float pmove_onground
Function Documentation
void _Movetype_Physics_ClientFrame (entity this, float movedt)
Definition at line 607 of file movetypes.qc.
References _Movetype_CheckWater(), _Movetype_LinkEdict(), _Movetype_Physics_Follow(), _Movetype_Physics_Pusher(), _Movetype_Physics_Step(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), move_angles, move_avelocity, move_didgravity, move_movetype, move_origin, move_velocity, MOVETYPE_BOUNCE, MOVETYPE_BOUNCEMISSILE, MOVETYPE_FAKEPUSH, MOVETYPE_FLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_FLYMISSILE, MOVETYPE_FOLLOW, MOVETYPE_NOCLIP, MOVETYPE_NONE, MOVETYPE_PHYSICS, MOVETYPE_PUSH, MOVETYPE_STEP, MOVETYPE_TOSS, and MOVETYPE_WALK.
Referenced by Movetype_Physics_Spam().
 {
     this.move_didgravity = -1;
     switch (this.move_movetype)
     {
         case MOVETYPE_PUSH:
         case MOVETYPE_FAKEPUSH:
             _Movetype_Physics_Pusher(this, movedt);
             break;
         case MOVETYPE_NONE:
             break;
         case MOVETYPE_FOLLOW:
             _Movetype_Physics_Follow(this);
             break;
         case MOVETYPE_NOCLIP:
             _Movetype_CheckWater(this);
             this.move_origin = this.move_origin + TICRATE * this.move_velocity;
             this.move_angles = this.move_angles + TICRATE * this.move_avelocity;
             _Movetype_LinkEdict(this, false);
             break;
         case MOVETYPE_STEP:
             _Movetype_Physics_Step(this, movedt);
             break;
         case MOVETYPE_WALK:
         case MOVETYPE_FLY:
         case MOVETYPE_FLY_WORLDONLY:
             _Movetype_Physics_Walk(this, movedt);
             break;
         case MOVETYPE_TOSS:
         case MOVETYPE_BOUNCE:
         case MOVETYPE_BOUNCEMISSILE:
         case MOVETYPE_FLYMISSILE:
             _Movetype_Physics_Toss(this, movedt);
             break;
         case MOVETYPE_PHYSICS:
             break;
     }
 }
void CSQC_ClientMovement_PlayerMove_Frame (entity this)
Referenced by CSQCPlayer_Physics().
void CSQCPlayer_CheckWater (entity this)
Definition at line 150 of file cl_player.qc.
References _Movetype_CheckWater(), move_origin, move_waterlevel, move_watertype, origin, waterlevel, and watertype.
Referenced by CSQCPlayer_Physics().
 {
     this.move_origin = this.origin;
     this.move_waterlevel = this.waterlevel;
     this.move_watertype = this.watertype;
     _Movetype_CheckWater(this);
     this.waterlevel = this.move_waterlevel;
     this.watertype = this.move_watertype;
 }
vector CSQCPlayer_GetPredictionErrorO ()
Definition at line 51 of file cl_player.qc.
References csqcplayer_predictionerrorfactor, csqcplayer_predictionerroro, csqcplayer_predictionerrortime, and time.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_SetPredictionError().
 {
     if (time >= csqcplayer_predictionerrortime) return '0 0 0';
     return csqcplayer_predictionerroro * (csqcplayer_predictionerrortime - time) * csqcplayer_predictionerrorfactor;
 }
vector CSQCPlayer_GetPredictionErrorV ()
Definition at line 57 of file cl_player.qc.
References csqcplayer_predictionerrorfactor, csqcplayer_predictionerrortime, csqcplayer_predictionerrorv, and time.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_SetPredictionError().
 {
     if (time >= csqcplayer_predictionerrortime) return '0 0 0';
     return csqcplayer_predictionerrorv * (csqcplayer_predictionerrortime - time) * csqcplayer_predictionerrorfactor;
 }
bool CSQCPlayer_IsLocalPlayer (entity this)
Definition at line 234 of file cl_player.qc.
References csqcplayer.
Referenced by CSQCModel_Draw().
 {
     return (this == csqcplayer);
 }
void CSQCPlayer_Physics (entity this)
Definition at line 160 of file cl_player.qc.
References angles, autocvar_cl_movement, avelocity, BITSET, CSQC_ClientMovement_PlayerMove_Frame(), CSQCPlayer_CheckWater(), FL_DUCKED, FL_JUMPRELEASED, FL_ONGROUND, FL_WATERJUMP, flags, IS_ONGROUND, move_angles, move_avelocity, move_flags, move_origin, move_velocity, move_waterlevel, move_watertype, Movetype_Physics_Spam(), origin, PMF_DUCKED, PMF_JUMP_HELD, PMF_ONGROUND, pmove_flags, velocity, waterlevel, and watertype.
Referenced by CSQCPlayer_PredictTo().
 {
     if(autocvar_cl_movement)
     {
         if(autocvar_cl_movement == 1)
             CSQCPlayer_CheckWater(this); // we apparently need to check water *before* physics so it can use this for water jump
         CSQC_ClientMovement_PlayerMove_Frame(this);
         if(autocvar_cl_movement == 1)
         {
             this.move_origin = this.origin;
             this.move_angles = this.angles;
             //this.move_movetype = MOVETYPE_WALK; // temp
             this.move_velocity = this.velocity;
             this.move_avelocity = this.avelocity;
             this.move_flags = BITSET(this.move_flags, FL_ONGROUND, IS_ONGROUND(this));
             this.move_flags = BITSET(this.move_flags, FL_WATERJUMP, boolean(this.flags & FL_WATERJUMP));
             this.move_waterlevel = this.waterlevel;
             this.move_watertype = this.watertype;
             Movetype_Physics_Spam(this);
         }
         this.pmove_flags =
                 ((this.flags & FL_DUCKED) ? PMF_DUCKED : 0) |
                 (!(this.flags & FL_JUMPRELEASED) ? PMF_JUMP_HELD : 0) |
                 ((IS_ONGROUND(this)) ? PMF_ONGROUND : 0);
     }
 }
bool CSQCPlayer_PostUpdate (entity this)
Definition at line 355 of file cl_player.qc.
References csqcplayer, CSQCPlayer_Remove(), csqcplayer_status, CSQCPLAYERSTATUS_FROMSERVER, cvar_settemp(), entnum, and player_localnum.
Referenced by NET_HANDLE().
 {
     if (this.entnum != player_localnum + 1) return false;
     csqcplayer = this;
     csqcplayer_status = CSQCPLAYERSTATUS_FROMSERVER;
     cvar_settemp("cl_movement_replay", "0");
     this.entremove = CSQCPlayer_Remove;
     return true;
 }
void CSQCPlayer_PredictTo (entity this, float endframe, bool apply_error)
Definition at line 190 of file cl_player.qc.
References clientcommandframe, CSQCPlayer_GetPredictionErrorO(), CSQCPlayer_GetPredictionErrorV(), csqcplayer_moveframe, CSQCPlayer_Physics(), CSQCPlayer_SetMinsMaxs(), csqcplayer_status, CSQCPlayer_Unpredict(), CSQCPLAYERSTATUS_PREDICTED, input_angles, LOG_INFO, origin, velocity, and view_angles.
Referenced by CSQCPlayer_SetCamera().
 {
     CSQCPlayer_Unpredict(this);
     if (apply_error)
     {
         this.origin += CSQCPlayer_GetPredictionErrorO();
         this.velocity += CSQCPlayer_GetPredictionErrorV();
     }
     CSQCPlayer_SetMinsMaxs(this);
     csqcplayer_status = CSQCPLAYERSTATUS_PREDICTED;
 #if 0
     // we don't need this
     // darkplaces makes servercommandframe == 0 in these cases anyway
     if (STAT(HEALTH) <= 0)
     {
         csqcplayer_moveframe = clientcommandframe;
         getinputstate(csqcplayer_moveframe-1);
         LOG_INFO("the Weird code path got hit\n");
         return;
     }
 #endif
     if (csqcplayer_moveframe >= endframe)
     {
         getinputstate(csqcplayer_moveframe - 1);
     }
     else
     {
         do
         {
             if (!getinputstate(csqcplayer_moveframe)) break;
             CSQCPlayer_Physics(this);
             CSQCPlayer_SetMinsMaxs(this);
             ++csqcplayer_moveframe;
         }
         while (csqcplayer_moveframe < endframe);
     }
     // add in anything that was applied after (for low packet rate protocols)
     input_angles = view_angles;
 }
bool CSQCPlayer_PreUpdate (entity this)
Definition at line 348 of file cl_player.qc.
References csqcplayer, csqcplayer_status, CSQCPlayer_Unpredict(), and CSQCPLAYERSTATUS_FROMSERVER.
Referenced by NET_HANDLE().
 {
     if (this != csqcplayer) return false;
     if (csqcplayer_status != CSQCPLAYERSTATUS_FROMSERVER) CSQCPlayer_Unpredict(this);
     return true;
 }
void CSQCPlayer_Remove (entity this)
Definition at line 342 of file cl_player.qc.
References csqcplayer, cvar_settemp(), and NULL.
Referenced by CSQCPlayer_PostUpdate().
 {
     csqcplayer = NULL;
     cvar_settemp("cl_movement_replay", "1");
 }
void CSQCPlayer_SavePrediction (entity this)
Definition at line 122 of file cl_player.qc.
References csqcplayer_origin, csqcplayer_sequence, csqcplayer_status, csqcplayer_velocity, CSQCPLAYERSTATUS_PREDICTED, flags, origin, player_pmflags, servercommandframe, and velocity.
Referenced by CSQCPlayer_SetCamera().
 {
     player_pmflags = this.flags;
     csqcplayer_origin = this.origin;
     csqcplayer_velocity = this.velocity;
     csqcplayer_sequence = servercommandframe;
     csqcplayer_status = CSQCPLAYERSTATUS_PREDICTED;
 }
void CSQCPlayer_SetCamera ()
Called once per CSQC_UpdateView()
Definition at line 245 of file cl_player.qc.
References BIT, BITSET, clientcommandframe, CSQCModel_server2csqc(), csqcplayer, CSQCPLAYER_HOOK_POSTCAMERASETUP, CSQCPlayer_PredictTo(), CSQCPlayer_SavePrediction(), CSQCPlayer_SetMinsMaxs(), CSQCPlayer_SetPredictionError(), csqcplayer_status, CSQCPLAYERSTATUS_FROMSERVER, CSQCPLAYERSTATUS_PREDICTED, entity(), FL_DUCKED, FL_ONGROUND, IFLAG_ANGLES, IFLAG_ORIGIN, input_angles, input_buttons, intermission, InterpolateOrigin_Do(), IS_ONGROUND, NULL, player_localentnum, pmove_onground, pmove_vel, REFDEFFLAG_DEAD, REFDEFFLAG_INTERMISSION, REFDEFFLAG_JUMPING, REFDEFFLAG_TELEPORTED, servercommandframe, and vector().
Referenced by CSQC_UpdateView().
 {
     const vector v0 = pmove_vel; // TRICK: pmove_vel is set by the engine when we get here. No need to network velocity
     const float vh = STAT(VIEWHEIGHT);
     const vector pl_viewofs = STAT(PL_VIEW_OFS, NULL);
     const vector pl_viewofs_crouch = STAT(PL_CROUCH_VIEW_OFS, NULL);
     const entity e = csqcplayer;
     if (e)
     {
         if (servercommandframe == 0 || clientcommandframe == 0)
         {
             InterpolateOrigin_Do(e);
             e.view_ofs = '0 0 1' * vh;
             // get crouch state from the server
             if (vh == pl_viewofs.z) e.flags &= ~FL_DUCKED;
             else if (vh == pl_viewofs_crouch.z) e.flags |= FL_DUCKED;
             // get onground state from the server
             e.flags = BITSET(e.flags, FL_ONGROUND, pmove_onground);
             CSQCPlayer_SetMinsMaxs(e);
             // override it back just in case
             e.view_ofs = '0 0 1' * vh;
             // set velocity
             e.velocity = v0;
         }
         else
         {
             const int flg = e.iflags; e.iflags &= ~(IFLAG_ORIGIN | IFLAG_ANGLES);
             InterpolateOrigin_Do(e);
             e.iflags = flg;
             if (csqcplayer_status == CSQCPLAYERSTATUS_FROMSERVER)
             {
                 const vector o = e.origin;
                 csqcplayer_status = CSQCPLAYERSTATUS_PREDICTED;
                 CSQCPlayer_PredictTo(e, servercommandframe + 1, false);
                 CSQCPlayer_SetPredictionError(e.origin - o, e.velocity - v0, pmove_onground - IS_ONGROUND(e));
                 e.origin = o;
                 e.velocity = v0;
                 // get crouch state from the server
                 if (vh == pl_viewofs.z) e.flags &= ~FL_DUCKED;
                 else if(vh == pl_viewofs_crouch.z) e.flags |= FL_DUCKED;
                 // get onground state from the server
                 e.flags = BITSET(e.flags, FL_ONGROUND, pmove_onground);
                 CSQCPlayer_SavePrediction(e);
             }
             CSQCPlayer_PredictTo(e, clientcommandframe + 1, true);
 #ifdef CSQCMODEL_SERVERSIDE_CROUCH
             // get crouch state from the server (LAG)
             if (vh == pl_viewofs.z) e.flags &= ~FL_DUCKED;
             else if (vh == pl_viewofs_crouch.z) e.flags |= FL_DUCKED;
 #endif
             CSQCPlayer_SetMinsMaxs(e);
             e.angles_y = input_angles.y;
         }
         // relink
         setorigin(e, e.origin);
     }
     const entity view = CSQCModel_server2csqc(player_localentnum - 1);
     if (view)
     {
         if (view != csqcplayer)
         {
             InterpolateOrigin_Do(view);
             view.view_ofs = '0 0 1' * vh;
         }
         int refdefflags = 0;
         if (view.csqcmodel_teleported) refdefflags |= REFDEFFLAG_TELEPORTED;
         if (input_buttons & BIT(1)) refdefflags |= REFDEFFLAG_JUMPING;
         // note: these two only work in WIP2, but are harmless in WIP1
         if (STAT(HEALTH) <= 0) refdefflags |= REFDEFFLAG_DEAD;
         if (intermission) refdefflags |= REFDEFFLAG_INTERMISSION;
         V_CalcRefdef(view, refdefflags);
     }
     else
     {
         // FIXME by CSQC spec we have to do this:
         // but it breaks chase cam
         /*
         setproperty(VF_ORIGIN, pmove_org + '0 0 1' * vh);
         setproperty(VF_ANGLES, view_angles);
         */
     }
     CSQCPLAYER_HOOK_POSTCAMERASETUP();
 }
void CSQCPlayer_SetMinsMaxs (entity this)
Definition at line 106 of file cl_player.qc.
References FL_DUCKED, flags, isplayermodel, maxs, mins, NULL, and view_ofs.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_SetCamera().
 {
     if ((this.flags & FL_DUCKED) || !this.isplayermodel)
     {
         this.mins = STAT(PL_CROUCH_MIN, NULL);
         this.maxs = STAT(PL_CROUCH_MAX, NULL);
         this.view_ofs = STAT(PL_CROUCH_VIEW_OFS, NULL);
     }
     else
     {
         this.mins = STAT(PL_MIN, NULL);
         this.maxs = STAT(PL_MAX, NULL);
         this.view_ofs = STAT(PL_VIEW_OFS, NULL);
     }
 }
void CSQCPlayer_SetPredictionError (vector o, vector v, float onground_diff)
Definition at line 63 of file cl_player.qc.
References autocvar_cl_movement_errorcompensation, CSQCPlayer_GetPredictionErrorO(), CSQCPlayer_GetPredictionErrorV(), csqcplayer_predictionerrorfactor, csqcplayer_predictionerroro, csqcplayer_predictionerrortime, csqcplayer_predictionerrorv, ticrate, time, and vdist.
Referenced by CSQCPlayer_SetCamera().
 {
     // error too big to compensate, we LIKELY hit a teleport or a
     // jumppad, or it's a jump time disagreement that'll get fixed
     // next frame
     // FIXME we sometimes have disagreement in order of jump velocity. Do not act on them!
     /*
     // commented out as this one did not help
     if(onground_diff)
     {
         printf("ONGROUND MISMATCH: %d x=%v v=%v\n", onground_diff, o, v);
         return;
     }
     */
     if(vdist(o, >, 32) || vdist(v, >, 192))
     {
         //printf("TOO BIG: x=%v v=%v\n", o, v);
         return;
     }
     if(!autocvar_cl_movement_errorcompensation)
     {
         csqcplayer_predictionerrorfactor = 0;
         return;
     }
     csqcplayer_predictionerroro = CSQCPlayer_GetPredictionErrorO() + o;
     csqcplayer_predictionerrorv = CSQCPlayer_GetPredictionErrorV() + v;
     csqcplayer_predictionerrorfactor = autocvar_cl_movement_errorcompensation / ticrate;
     csqcplayer_predictionerrortime = time + 1.0 / csqcplayer_predictionerrorfactor;
 }
void CSQCPlayer_SetViewLocation ()
Definition at line 239 of file cl_player.qc.
 {
     viewloc_SetViewLocation();
 }
void CSQCPlayer_Unpredict (entity this)
Definition at line 96 of file cl_player.qc.
References csqcplayer_moveframe, csqcplayer_origin, csqcplayer_sequence, csqcplayer_status, csqcplayer_velocity, CSQCPLAYERSTATUS_PREDICTED, CSQCPLAYERSTATUS_UNPREDICTED, flags, LOG_FATALF, origin, player_pmflags, and velocity.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_PreUpdate().
 {
     if (csqcplayer_status == CSQCPLAYERSTATUS_UNPREDICTED) return;
     if (csqcplayer_status != CSQCPLAYERSTATUS_PREDICTED) LOG_FATALF("Cannot unpredict in current status (%d)\n", csqcplayer_status);
     this.origin = csqcplayer_origin;
     this.velocity = csqcplayer_velocity;
     csqcplayer_moveframe = csqcplayer_sequence + 1; // + 1 because the recieved frame has the move already done (server side)
     this.flags = player_pmflags;
 }
void Movetype_Physics_Spam (entity this)
Definition at line 134 of file cl_player.qc.
References _Movetype_Physics_ClientFrame(), angles, avelocity, BITSET, FL_ONGROUND, FL_WATERJUMP, flags, move_angles, move_avelocity, move_flags, move_origin, move_velocity, move_waterlevel, move_watertype, velocity, waterlevel, and watertype.
Referenced by CSQCPlayer_Physics().
 {
     _Movetype_Physics_ClientFrame(this, PHYS_INPUT_TIMELENGTH);
     if(wasfreed(this))
         return;
     this.avelocity = this.move_avelocity;
     this.velocity = this.move_velocity;
     this.angles = this.move_angles;
     this.flags = BITSET(this.flags, FL_ONGROUND, boolean(this.move_flags & FL_ONGROUND));
     this.flags = BITSET(this.flags, FL_WATERJUMP, boolean(this.move_flags & FL_WATERJUMP));
     this.waterlevel = this.move_waterlevel;
     this.watertype = this.move_watertype;
     setorigin(this, this.move_origin);
 }
Variable Documentation
float autocvar_cl_movement_errorcompensation = 0
Definition at line 37 of file cl_player.qc.
Referenced by CSQCPlayer_SetPredictionError().
float csqcplayer_moveframe
Definition at line 45 of file cl_player.qc.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_Unpredict().
vector csqcplayer_origin
Definition at line 42 of file cl_player.qc.
Referenced by CSQCPlayer_SavePrediction(), and CSQCPlayer_Unpredict().
float csqcplayer_predictionerrorfactor
Definition at line 49 of file cl_player.qc.
Referenced by CSQCPlayer_GetPredictionErrorO(), CSQCPlayer_GetPredictionErrorV(), and CSQCPlayer_SetPredictionError().
vector csqcplayer_predictionerroro
Definition at line 46 of file cl_player.qc.
Referenced by CSQCPlayer_GetPredictionErrorO(), and CSQCPlayer_SetPredictionError().
float csqcplayer_predictionerrortime
Definition at line 48 of file cl_player.qc.
Referenced by CSQCPlayer_GetPredictionErrorO(), CSQCPlayer_GetPredictionErrorV(), and CSQCPlayer_SetPredictionError().
vector csqcplayer_predictionerrorv
Definition at line 47 of file cl_player.qc.
Referenced by CSQCPlayer_GetPredictionErrorV(), and CSQCPlayer_SetPredictionError().
float csqcplayer_sequence
Definition at line 43 of file cl_player.qc.
Referenced by CSQCPlayer_SavePrediction(), and CSQCPlayer_Unpredict().
vector csqcplayer_velocity
Definition at line 42 of file cl_player.qc.
Referenced by CSQCPlayer_SavePrediction(), and CSQCPlayer_Unpredict().
int player_pmflags
Definition at line 44 of file cl_player.qc.
Referenced by CSQCPlayer_SavePrediction(), and CSQCPlayer_Unpredict().
float pmove_onground
Definition at line 40 of file cl_player.qc.
Referenced by CSQCPlayer_SetCamera().