Xonotic: menu/xonotic/charmap.qc File Reference
charmap.qc File Reference
#include "charmap.qh"
#include "inputbox.qh"
Functions
string charmap_cellToChar (entity me, vector cell)
entity makeXonoticCharmap (entity controlledInputBox)
void XonoticCharmap_cellDraw (entity me, vector cell, vector cellPos)
bool XonoticCharmap_cellIsValid (entity me, vector cell)
void XonoticCharmap_cellSelect (entity me, vector cell)
void XonoticCharmap_configureXonoticCharmap (entity me, entity controlledInputBox)
void XonoticCharmap_focusLeave (entity me)
float XonoticCharmap_keyDown (entity me, float key, float ascii, float shift)
void XonoticCharmap_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Variables
string CHARMAP
Function Documentation
string charmap_cellToChar (entity me, vector cell)
Definition at line 22 of file charmap.qc.
References CHARMAP, and substring().
Referenced by XonoticCharmap_cellDraw(), XonoticCharmap_cellIsValid(), and XonoticCharmap_cellSelect().
 {
     string character = substring(CHARMAP, cell.y * me.columns + cell.x, 1);
     if(character != " ")
         return character;
     else
         return "";
 }
entity makeXonoticCharmap (entity controlledInputBox)
Definition at line 32 of file charmap.qc.
References entity(), and NEW.
Referenced by XonoticFirstRunDialog_fill(), and XonoticProfileTab_fill().
 {
     entity me;
     me = NEW(XonoticCharmap);
     me.configureXonoticCharmap(me, controlledInputBox);
     return me;
 }
void XonoticCharmap_cellDraw (entity me, vector cell, vector cellPos)
Definition at line 95 of file charmap.qc.
References charmap_cellToChar(), and draw_CenterText().
 {
     draw_CenterText(cellPos + me.charOffset, charmap_cellToChar(me, cell), me.realFontSize, SKINCOLOR_CHARMAP_CHAR, SKINALPHA_CHARMAP_CHAR, 0);
 }
bool XonoticCharmap_cellIsValid (entity me, vector cell)
Definition at line 88 of file charmap.qc.
References charmap_cellToChar().
 {
     if(charmap_cellToChar(me, cell) == "")
         return false;
     return true;
 }
void XonoticCharmap_cellSelect (entity me, vector cell)
Definition at line 77 of file charmap.qc.
References charmap_cellToChar().
 {
     string character = charmap_cellToChar(me, cell);
     if(character != "")
     {
         me.inputBox.enterText(me.inputBox, character);
         if(me.inputBox.applyButton)
             me.inputBox.applyButton.disabled = false;
     }
 }
void XonoticCharmap_configureXonoticCharmap (entity me, entity controlledInputBox)
Definition at line 40 of file charmap.qc.
 {
     me.inputBox = controlledInputBox;
     me.configureXonoticPicker(me);
 }
void XonoticCharmap_focusLeave (entity me)
Definition at line 100 of file charmap.qc.
 {
     me.inputBox.saveCvars(me.inputBox);
 }
float XonoticCharmap_keyDown (entity me, float key, float ascii, float shift)
Definition at line 70 of file charmap.qc.
References SUPER.
 {
     if(SUPER(XonoticCharmap).keyDown(me, key, ascii, shift))
         return 1;
     return me.inputBox.keyDown(me.inputBox, key, ascii, shift);
 }
void XonoticCharmap_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 46 of file charmap.qc.
References eX, eY, and SUPER.
 {
     SUPER(XonoticCharmap).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     float maxFontWidth = SKINFONTSIZE_NORMAL / absSize.x;
     float maxFontHeight = SKINFONTSIZE_NORMAL / absSize.y;
     if((me.realCellSize.x * absSize.x) > (me.realCellSize.y * absSize.y))
     {
         me.realFontSize_x = me.realCellSize.y * absSize.y / absSize.x;
         me.realFontSize_y = me.realCellSize.y;
     }
     else
     {
         me.realFontSize_x = me.realCellSize.x;
         me.realFontSize_y = me.realCellSize.x * absSize.x / absSize.y;
     }
     if(me.realFontSize.x > maxFontWidth || me.realFontSize.y > maxFontHeight)
         me.realFontSize = eX * maxFontWidth + eY * maxFontHeight;
     me.charOffset = eX * me.realCellSize.x / 2 + eY * ((me.realCellSize.y - me.realFontSize.y) / 2);
 }
Variable Documentation
string CHARMAP
Initial value:
=
    "★◆■▮▰▬◣◤◥◢◀▲▶▼"
    "🌍🌎🌏🚀🌌👽🔫⌖❇❈←↑→↓"
    "☠☣☢⚛⚡⚙🔥❌⚠⛔❰❱❲❳"
    "😃😊😁😄😆😎😈😇😉😛😝😘❤ "
    "😐😒😕😮😲😞😟😠😣😭😵😴  "
    "\xEE\x83\xA1\xEE\x83\xA2\xEE\x83\xA3\xEE\x83\xA4\xEE\x83\xA5\xEE\x83\xA6\xEE\x83\xA7"
    "\xEE\x83\xA8\xEE\x83\xA9\xEE\x83\xAA\xEE\x83\xAB\xEE\x83\xAC\xEE\x83\xAD\xEE\x83\xAE"
    "\xEE\x83\xAF\xEE\x83\xB0\xEE\x83\xB1\xEE\x83\xB2\xEE\x83\xB3\xEE\x83\xB4\xEE\x83\xB5"
    "\xEE\x83\xB6\xEE\x83\xB7\xEE\x83\xB8\xEE\x83\xB9\xEE\x83\xBA\xEE\x80\x90\xEE\x80\x91"
    "\xEE\x82\xB0\xEE\x82\xB1\xEE\x82\xB2\xEE\x82\xB3\xEE\x82\xB4\xEE\x82\xB5\xEE\x82\xB6"
    "\xEE\x82\xB7\xEE\x82\xB8\xEE\x82\xB9\xEE\x82\xA1\xEE\x82\xBF\xEE\x82\xA6\xEE\x82\xA5"
    "\xEE\x83\x81\xEE\x83\x82\xEE\x83\x83\xEE\x83\x84\xEE\x83\x85\xEE\x83\x86\xEE\x83\x87"
    "\xEE\x83\x88\xEE\x83\x89\xEE\x83\x8A\xEE\x83\x8B\xEE\x83\x8C\xEE\x83\x8D\xEE\x83\x8E"
    "\xEE\x83\x8F\xEE\x83\x90\xEE\x83\x91\xEE\x83\x92\xEE\x83\x93\xEE\x83\x94\xEE\x83\x95"
    "\xEE\x83\x96\xEE\x83\x97\xEE\x83\x98\xEE\x83\x99\xEE\x83\x9A\xEE\x81\x9B\xEE\x81\x9D"
Definition at line 5 of file charmap.qc.
Referenced by charmap_cellToChar().