Xonotic: menu/xonotic/serverlist.qh File Reference
serverlist.qh File Reference
#include "listbox.qh"
Classes
class XonoticServerList
Macros
#define IsFavorite(srv) IsServerInList(cvar_string("net_slist_favorites"), srv)
#define IsPromoted(srv) IsServerInList(_Nex_ExtResponseSystem_PromotedServers, srv)
#define IsRecommended(srv) IsServerInList(_Nex_ExtResponseSystem_RecommendedServers, srv)
#define SLIST_CATEGORIES
#define SLIST_CATEGORY(name, enoverride, dioverride, str)
#define SLIST_CATEGORY_AUTOCVAR(name) autocvar_menu_slist_categories_##name##_override
#define SLIST_FIELD(suffix, name) float SLIST_FIELD_##suffix;
#define SLIST_FIELDS
Functions
float CheckCategoryForEntry (float entry)
float CheckCategoryOverride (float cat)
float IsServerInList (string list, string srv)
float m_gethostcachecategory (float entry)
entity makeXonoticServerList ()
void RegisterSLCategories ()
entity RetrieveCategoryEnt (float catnum)
void ServerList_Categories_Click (entity box, entity me)
void ServerList_Connect_Click (entity btn, entity me)
void ServerList_Favorite_Click (entity btn, entity me)
void ServerList_Filter_Change (entity box, entity me)
void ServerList_Info_Click (entity btn, entity me)
void ServerList_ShowEmpty_Click (entity box, entity me)
void ServerList_ShowFull_Click (entity box, entity me)
void ServerList_Update_favoriteButton (entity btn, entity me)
Variables
SLIST_FIELDS float autocvar_menu_slist_categories
float autocvar_menu_slist_categories_onlyifmultiple
float autocvar_menu_slist_modimpurity
float autocvar_menu_slist_purethreshold
float autocvar_menu_slist_recommendations
float autocvar_menu_slist_recommendations_maxping
float autocvar_menu_slist_recommendations_minfreeslots
float autocvar_menu_slist_recommendations_minhumans
float autocvar_menu_slist_recommendations_purethreshold
float cat_dioverride
string cat_dioverride_string
float cat_enoverride
string cat_enoverride_string
string cat_name
string cat_string
entity categories [MAX_CATEGORIES]
int category_draw_count
int category_ent_count
const int CATEGORY_FIRST = 1
int category_item [MAX_CATEGORIES]
int category_name [MAX_CATEGORIES]
const int MAX_CATEGORIES = 9
const float REFRESHSERVERLIST_ASK = 2
const float REFRESHSERVERLIST_REFILTER = 1
const float REFRESHSERVERLIST_RESET = 3
const float REFRESHSERVERLIST_RESORT = 0
Macro Definition Documentation
#define IsFavorite (srv) IsServerInList(cvar_string("net_slist_favorites"), srv)
Definition at line 123 of file serverlist.qh.
Referenced by ServerList_Update_favoriteButton().
#define IsPromoted (srv) IsServerInList(_Nex_ExtResponseSystem_PromotedServers, srv)
Definition at line 124 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
#define IsRecommended (srv) IsServerInList(_Nex_ExtResponseSystem_RecommendedServers, srv)
Definition at line 125 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
#define SLIST_CATEGORIES
Value:
SLIST_CATEGORY(CAT_FAVORITED,    "",            "",             CTX(_("SLCAT^Favorites"))) \
    SLIST_CATEGORY(CAT_RECOMMENDED,  "",            "",             CTX(_("SLCAT^Recommended"))) \
    SLIST_CATEGORY(CAT_NORMAL,       "",            "CAT_SERVERS",  CTX(_("SLCAT^Normal Servers"))) \
    SLIST_CATEGORY(CAT_SERVERS,      "CAT_NORMAL",  "CAT_SERVERS",  CTX(_("SLCAT^Servers"))) \
    SLIST_CATEGORY(CAT_XPM,          "CAT_NORMAL",  "CAT_SERVERS",  CTX(_("SLCAT^Competitive Mode"))) \
    SLIST_CATEGORY(CAT_MODIFIED,     "",            "CAT_SERVERS",  CTX(_("SLCAT^Modified Servers"))) \
    SLIST_CATEGORY(CAT_OVERKILL,     "",            "CAT_SERVERS",  CTX(_("SLCAT^Overkill Mode"))) \
    SLIST_CATEGORY(CAT_INSTAGIB,     "",            "CAT_SERVERS",  CTX(_("SLCAT^InstaGib Mode"))) \
    SLIST_CATEGORY(CAT_DEFRAG,       "",            "CAT_SERVERS",  CTX(_("SLCAT^Defrag Mode")))
Definition at line 150 of file serverlist.qh.
Referenced by RegisterSLCategories().
#define SLIST_CATEGORY (name, enoverride, dioverride, str)
Value:
int name; \
    string SLIST_CATEGORY_AUTOCVAR(name) = enoverride;
Definition at line 162 of file serverlist.qh.
#define SLIST_CATEGORY_AUTOCVAR (name) autocvar_menu_slist_categories_##name##_override
Definition at line 161 of file serverlist.qh.
#define SLIST_FIELD (suffix, name) float SLIST_FIELD_##suffix;
Definition at line 102 of file serverlist.qh.
#define SLIST_FIELDS
Value:
SLIST_FIELD(CNAME,       "cname") \
    SLIST_FIELD(PING,        "ping") \
    SLIST_FIELD(GAME,        "game") \
    SLIST_FIELD(MOD,         "mod") \
    SLIST_FIELD(MAP,         "map") \
    SLIST_FIELD(NAME,        "name") \
    SLIST_FIELD(MAXPLAYERS,  "maxplayers") \
    SLIST_FIELD(NUMPLAYERS,  "numplayers") \
    SLIST_FIELD(NUMHUMANS,   "numhumans") \
    SLIST_FIELD(NUMBOTS,     "numbots") \
    SLIST_FIELD(PROTOCOL,    "protocol") \
    SLIST_FIELD(FREESLOTS,   "freeslots") \
    SLIST_FIELD(PLAYERS,     "players") \
    SLIST_FIELD(QCSTATUS,    "qcstatus") \
    SLIST_FIELD(CATEGORY,    "category") \
    SLIST_FIELD(ISFAVORITE,  "isfavorite")
Definition at line 84 of file serverlist.qh.
Referenced by XonoticServerList_configureXonoticServerList().
Function Documentation
float CheckCategoryForEntry (float entry)
Referenced by m_gethostcachecategory().
float CheckCategoryOverride (float cat)
Referenced by m_gethostcachecategory().
float IsServerInList (string list, string srv)
Definition at line 77 of file serverlist.qc.
References argv(), p, strlen(), strstrofs, substring(), and tokenize_console.
 {
     string p;
     int i, n;
     if(srv == "")
         return false;
     srv = netaddress_resolve(srv, 26000);
     if(srv == "")
         return false;
     p = crypto_getidfp(srv);
     n = tokenize_console(list);
     for(i = 0; i < n; ++i)
     {
         if(substring(argv(i), 0, 1) != "[" && strlen(argv(i)) == 44 && strstrofs(argv(i), ".", 0) < 0)
         {
             if(p)
                 if(argv(i) == p)
                     return true;
         }
         else
         {
             if(srv == netaddress_resolve(argv(i), 26000))
                 return true;
         }
     }
     return false;
 }
float m_gethostcachecategory (float entry)
Definition at line 130 of file serverlist.qh.
References CheckCategoryForEntry(), and CheckCategoryOverride().
 { return CheckCategoryOverride(CheckCategoryForEntry(entry)); }
entity makeXonoticServerList ()
Definition at line 278 of file serverlist.qc.
References entity(), and NEW.
Referenced by XonoticServerListTab_fill().
 {
     entity me;
     me = NEW(XonoticServerList);
     me.configureXonoticServerList(me);
     return me;
 }
void RegisterSLCategories ()
Definition at line 9 of file serverlist.qc.
References cat_dioverride, cat_dioverride_string, cat_enoverride, cat_enoverride_string, entity(), PROCESS_OVERRIDE, and SLIST_CATEGORIES.
Referenced by m_init().
 {
     entity cat;
     #define SLIST_CATEGORY(name,enoverride,dioverride,str) \
         SET_FIELD_COUNT(name, CATEGORY_FIRST, category_ent_count) \
         CHECK_MAX_COUNT(name, MAX_CATEGORIES, category_ent_count, "SLIST_CATEGORY") \
         cat = categories[name - 1] = new(slist_category); \
         cat.cat_name = #name; \
         cat.cat_enoverride_string = strzone(SLIST_CATEGORY_AUTOCVAR(name)); \
         cat.cat_dioverride_string = strzone(dioverride); \
         cat.cat_string = strzone(str);
     SLIST_CATEGORIES
     #undef SLIST_CATEGORY
     int i, x, catnum;
     string s;
     #define PROCESS_OVERRIDE(override_string,override_field) \
         for(i = 0; i < category_ent_count; ++i) \
         { \
             s = categories[i].override_string; \
             if((s != "") && (s != categories[i].cat_name)) \
             { \
                 catnum = 0; \
                 for(x = 0; x < category_ent_count; ++x) \
                 { if(categories[x].cat_name == s) { \
                     catnum = (x+1); \
                     break; \
                 } } \
                 if(catnum) \
                 { \
                     strunzone(categories[i].override_string); \
                     categories[i].override_string = string_null; \
                     categories[i].override_field = catnum; \
                     continue; \
                 } \
                 else \
                 { \
                     LOG_INFOF( \
                         "RegisterSLCategories(): Improper override '%s' for category '%s'!\n", \
                         s, \
                         categories[i].cat_name \
                     ); \
                 } \
             } \
             strunzone(categories[i].override_string); \
             categories[i].override_string = string_null; \
             categories[i].override_field = 0; \
         }
     PROCESS_OVERRIDE(cat_enoverride_string, cat_enoverride)
     PROCESS_OVERRIDE(cat_dioverride_string, cat_dioverride)
     #undef PROCESS_OVERRIDE
 }
entity RetrieveCategoryEnt (float catnum)
void ServerList_Categories_Click (entity box, entity me)
Definition at line 691 of file serverlist.qc.
References autocvar_menu_slist_categories, and REFRESHSERVERLIST_RESORT.
Referenced by XonoticServerListTab_fill().
 {
     box.setChecked(box, autocvar_menu_slist_categories = !autocvar_menu_slist_categories);
     me.refreshServerList(me, REFRESHSERVERLIST_RESORT);
     me.ipAddressBox.setText(me.ipAddressBox, "");
     me.ipAddressBox.cursorPos = 0;
     me.ipAddressBoxFocused = -1;
 }
void ServerList_Connect_Click (entity btn, entity me)
Definition at line 786 of file serverlist.qc.
References localcmd.
Referenced by XonoticServerList_doubleClickListBoxItem(), XonoticServerList_keyDown(), and XonoticServerListTab_fill().
 {
     localcmd(sprintf("connect %s\n",
         ((me.ipAddressBox.text != "") ?
             me.ipAddressBox.text : me.selectedServer
         )
     ));
 }
void ServerList_Favorite_Click (entity btn, entity me)
Definition at line 794 of file serverlist.qc.
References m_play_click_sound(), and MENU_SOUND_SELECT.
Referenced by XonoticServerListTab_fill().
 {
     string addr = this.ipAddressBox.text;
     string ipstr = netaddress_resolve(addr, 26000);
     if (ipstr == "") return;
     m_play_click_sound(MENU_SOUND_SELECT);
     this.toggleFavorite(this, addr);
     this.ipAddressBoxFocused = -1;
 }
void ServerList_Filter_Change (entity box, entity me)
Definition at line 677 of file serverlist.qc.
References REFRESHSERVERLIST_REFILTER, string_null, strunzone(), and strzone().
Referenced by XonoticServerListTab_fill().
 {
     if(me.filterString)
         strunzone(me.filterString);
     if(box.text != "")
         me.filterString = strzone(box.text);
     else
         me.filterString = string_null;
     me.refreshServerList(me, REFRESHSERVERLIST_REFILTER);
     me.ipAddressBox.setText(me.ipAddressBox, "");
     me.ipAddressBox.cursorPos = 0;
     me.ipAddressBoxFocused = -1;
 }
void ServerList_Info_Click (entity btn, entity me)
Definition at line 803 of file serverlist.qc.
References boxToGlobal(), boxToGlobalSize(), DialogOpenButton_Click_withCoords(), eX, eY, main, and vector().
Referenced by XonoticServerListTab_fill().
 {
     if (me.nItems != 0)
         main.serverInfoDialog.loadServerInfo(main.serverInfoDialog, me.selectedItem);
     vector org = boxToGlobal(eY * (me.selectedItem * me.itemHeight - me.scrollPos), me.origin, me.size);
     vector sz = boxToGlobalSize(eY * me.itemHeight + eX * (1 - me.controlWidth), me.size);
     DialogOpenButton_Click_withCoords(me, main.serverInfoDialog, org, sz);
 }
void ServerList_ShowEmpty_Click (entity box, entity me)
Definition at line 700 of file serverlist.qc.
References REFRESHSERVERLIST_REFILTER.
Referenced by XonoticServerListTab_fill().
 {
     box.setChecked(box, me.filterShowEmpty = !me.filterShowEmpty);
     me.refreshServerList(me, REFRESHSERVERLIST_REFILTER);
     me.ipAddressBox.setText(me.ipAddressBox, "");
     me.ipAddressBox.cursorPos = 0;
     me.ipAddressBoxFocused = -1;
 }
void ServerList_ShowFull_Click (entity box, entity me)
Definition at line 709 of file serverlist.qc.
References REFRESHSERVERLIST_REFILTER.
Referenced by XonoticServerListTab_fill().
 {
     box.setChecked(box, me.filterShowFull = !me.filterShowFull);
     me.refreshServerList(me, REFRESHSERVERLIST_REFILTER);
     me.ipAddressBox.setText(me.ipAddressBox, "");
     me.ipAddressBox.cursorPos = 0;
     me.ipAddressBoxFocused = -1;
 }
void ServerList_Update_favoriteButton (entity btn, entity me)
Definition at line 263 of file serverlist.qc.
References clearTooltip(), entity(), IsFavorite, setZonedTooltip(), and string_null.
Referenced by XonoticServerList_draw(), and XonoticServerListTab_fill().
 {
     entity e = me.favoriteButton;
     if(IsFavorite(me.ipAddressBox.text))
     {
         e.setText(e, _("Remove"));
         clearTooltip(e);
     }
     else
     {
         e.setText(e, _("Favorite"));
         setZonedTooltip(e, _("Bookmark the currently highlighted server so that it's faster to find in the future"), string_null);
     }
 }
Variable Documentation
SLIST_FIELDS float autocvar_menu_slist_categories
Definition at line 106 of file serverlist.qh.
Referenced by CheckCategoryOverride(), ServerList_Categories_Click(), and XonoticServerList_draw().
float autocvar_menu_slist_categories_onlyifmultiple
Definition at line 107 of file serverlist.qh.
Referenced by XonoticServerList_draw().
float autocvar_menu_slist_modimpurity
Definition at line 109 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_purethreshold
Definition at line 108 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_recommendations
Definition at line 110 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_recommendations_maxping
Definition at line 111 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_recommendations_minfreeslots
Definition at line 112 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_recommendations_minhumans
Definition at line 113 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float autocvar_menu_slist_recommendations_purethreshold
Definition at line 114 of file serverlist.qh.
Referenced by CheckCategoryForEntry().
float cat_dioverride
Definition at line 143 of file serverlist.qh.
Referenced by RegisterSLCategories().
string cat_dioverride_string
Definition at line 141 of file serverlist.qh.
Referenced by RegisterSLCategories().
float cat_enoverride
Definition at line 142 of file serverlist.qh.
Referenced by RegisterSLCategories().
string cat_enoverride_string
Definition at line 140 of file serverlist.qh.
Referenced by RegisterSLCategories().
string cat_name
Definition at line 138 of file serverlist.qh.
string cat_string
Definition at line 139 of file serverlist.qh.
entity categories[MAX_CATEGORIES]
Definition at line 136 of file serverlist.qh.
Referenced by RetrieveCategoryEnt().
int category_draw_count
Definition at line 148 of file serverlist.qh.
Referenced by XonoticServerList_draw(), XonoticServerList_drawListBoxItem(), XonoticServerList_getItemAtPos(), XonoticServerList_getItemHeight(), XonoticServerList_getItemStart(), and XonoticServerList_getTotalHeight().
int category_ent_count
Definition at line 137 of file serverlist.qh.
Referenced by RetrieveCategoryEnt(), and XonoticServerList_draw().
const int CATEGORY_FIRST = 1
Definition at line 135 of file serverlist.qh.
int category_item[MAX_CATEGORIES]
Definition at line 147 of file serverlist.qh.
Referenced by XonoticServerList_draw(), XonoticServerList_drawListBoxItem(), XonoticServerList_getItemAtPos(), XonoticServerList_getItemHeight(), and XonoticServerList_getItemStart().
int category_name[MAX_CATEGORIES]
Definition at line 146 of file serverlist.qh.
Referenced by XonoticServerList_draw(), and XonoticServerList_drawListBoxItem().
const int MAX_CATEGORIES = 9
Definition at line 134 of file serverlist.qh.
const float REFRESHSERVERLIST_ASK = 2
Definition at line 118 of file serverlist.qh.
Referenced by XonoticServerList_focusEnter(), and XonoticServerList_refreshServerList().
const float REFRESHSERVERLIST_REFILTER = 1
Definition at line 117 of file serverlist.qh.
Referenced by ServerList_Filter_Change(), ServerList_ShowEmpty_Click(), ServerList_ShowFull_Click(), XonoticServerList_draw(), XonoticServerList_refreshServerList(), and XonoticServerList_setSortOrder().
const float REFRESHSERVERLIST_RESET = 3
Definition at line 119 of file serverlist.qh.
Referenced by XonoticServerList_draw(), and XonoticServerList_refreshServerList().
const float REFRESHSERVERLIST_RESORT = 0
Definition at line 116 of file serverlist.qh.
Referenced by ServerList_Categories_Click(), XonoticServerList::toggleFavorite(), and XonoticServerList_draw().