Xonotic: Nexposee Class Reference
Nexposee Class Reference
Public Member Functions
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
ATTRIB (Nexposee, selectedChild, entity)
ATTRIB (Nexposee, mouseFocusedChild, entity)
ATTRIB (MenuItem, parent, entity)
ATTRIB (Container, firstChild, entity)
ATTRIB (Container, lastChild, entity)
ATTRIB (Container, focusedChild, entity)
ATTRIB (MenuItem, tooltip, string)
ATTRIB (Container, savedFocus, entity)
virtual void calc ()
virtual void close ()
virtual void destroy ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void pullNexposee ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFocus ()
virtual void setNexposee ()
virtual void showNotify ()
virtual void toString ()
Public Attributes
float allowFocusSound = 0
float animationFactor = 0
float animationState = -1
float focusable = 0
float focused = 0
vector mousePosition = '0 0 0'
vector origin = '0 0 0'
float preferredFocusPriority = 0
float shown = 0
vector size = '0 0 0'
Detailed Description
Definition at line 4 of file nexposee.qh.
Member Function Documentation
virtual void Nexposee::addItem () virtual
Reimplemented from Container.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
Nexposee::ATTRIB (Nexposee , selectedChild , entity)
Nexposee::ATTRIB (Nexposee , mouseFocusedChild , entity)
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
Container::ATTRIB (Container , firstChild , entity) inherited
Container::ATTRIB (Container , lastChild , entity) inherited
Container::ATTRIB (Container , focusedChild , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
Container::ATTRIB (Container , savedFocus , entity) inherited
virtual void Nexposee::calc () virtual
virtual void Nexposee::close () virtual
Reimplemented in XonoticNexposee.
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Nexposee::draw () virtual
Reimplemented from Container.
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
virtual void Nexposee::focusEnter () virtual
Reimplemented from MenuItem.
virtual void Container::focusLeave () virtual inherited
Reimplemented from MenuItem.
Reimplemented in InputContainer.
virtual void Container::hideNotify () virtual inherited
Reimplemented from MenuItem.
virtual void Container::itemFromPoint () virtual inherited
virtual void Nexposee::keyDown () virtual
Reimplemented from Container.
virtual void Nexposee::keyUp () virtual
Reimplemented from Container.
virtual void Container::leaveSubitem () virtual inherited
virtual void Nexposee::mouseDrag () virtual
Reimplemented from Container.
virtual void Nexposee::mouseMove () virtual
Reimplemented from Container.
void Nexposee::mousePress () virtual
Reimplemented from Container.
Definition at line 157 of file nexposee.qc.
References m_play_click_sound(), MENU_SOUND_CLOSE, MENU_SOUND_OPEN, Nexposee_mouseMove(), NULL, and SUPER.
     {
         if (this.animationState == 0)
         {
             this.mouseFocusedChild = NULL;
             Nexposee_mouseMove(this, pos);
             if (this.mouseFocusedChild)
             {
                 m_play_click_sound(MENU_SOUND_OPEN);
                 this.animationState = 1;
                 SUPER(Nexposee).setFocus(this, NULL);
             }
             else
             {
                 this.close(this);
             }
             return true;
         }
         else if (this.animationState == 2)
         {
             if (!(SUPER(Nexposee).mousePress(this, pos)))
             {
                 m_play_click_sound(MENU_SOUND_CLOSE);
                 this.animationState = 3;
                 SUPER(Nexposee).setFocus(this, NULL);
             }
             return true;
         }
         return false;
     }
virtual void Nexposee::mouseRelease () virtual
Reimplemented from Container.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
virtual void Nexposee::pullNexposee () virtual
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void Nexposee::resizeNotify () virtual
Reimplemented from Container.
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Container::setFocus () virtual inherited
virtual void Nexposee::setNexposee () virtual
virtual void Container::showNotify () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticDamageTextSettings, XonoticTab, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
void MenuItem::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
Member Data Documentation
float MenuItem::allowFocusSound = 0 inherited
Definition at line 26 of file item.qh.
float Nexposee::animationFactor = 0
Definition at line 17 of file nexposee.qh.
float Nexposee::animationState = -1
Definition at line 16 of file nexposee.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
vector Nexposee::mousePosition = '0 0 0'
Definition at line 23 of file nexposee.qh.
vector MenuItem::origin = '0 0 0' inherited
Definition at line 29 of file item.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector MenuItem::size = '0 0 0' inherited
Definition at line 30 of file item.qh.
The documentation for this class was generated from the following files:
menu/item/nexposee.qh
menu/item/nexposee.qc