Xonotic: common/debug.qh File Reference
debug.qh File Reference
Functions
GENERIC_COMMAND (bufstr_get, "Examine a string buffer object", false)
GENERIC_COMMAND (version, "Print the current version", false)
GENERIC_COMMAND (cvar_localchanges, "Print locally changed cvars", false)
GENERIC_COMMAND (findent, "Search through entities for matching classname", false)
GENERIC_COMMAND (findat, "Search through entities for matching origin", false)
Function Documentation
GENERIC_COMMAND() [1/5]
GENERIC_COMMAND (bufstr_get , "Examine a string buffer object" , false)
Definition at line 201 of file debug.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_HELP, LOG_INFO, and stof().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             int bufhandle = stof(argv(1));
             int string_index = stof(argv(2));
             LOG_INFO(bufstr_get(bufhandle, string_index));
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 ", GetProgramCommandPrefix(), " bufstr_get <bufhandle> <string_index>");
             return;
         }
     }
 }
GENERIC_COMMAND() [2/5]
GENERIC_COMMAND (version , "Print the current version" , false)
Definition at line 223 of file debug.qh.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_HELP, LOG_INFO, and void.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             LOG_INFO(PROGNAME, " version: ", WATERMARK);
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 ", GetProgramCommandPrefix(), " version");
             return;
         }
     }
 }
GENERIC_COMMAND() [3/5]
GENERIC_COMMAND (cvar_localchanges , "Print locally changed cvars" , false)
Definition at line 246 of file debug.qh.
References buf_create, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, cvar_defstring(), cvar_string(), DRAWFLAG_NORMAL, drawstring(), entity(), etof(), FOREACH_CLIENT, FOREACH_ENTITY, g_drawables_2d, IL_PUSH(), LOG_HELP, LOG_INFO, MOVE_NORMAL, MUTATOR_HOOKFUNCTION, new_pure, PHYS_INPUT_BUTTON_HOOK, REGISTER_MUTATOR, REGISTER_STAT(), setorigin(), SOLID_BBOX, STATIC_INIT, strcat(), stuffcmd, trace_ent, v, vector(), and vid_conheight.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             string s = "";
             int h = buf_create();
             buf_cvarlist(h, "", "_"); // exclude all _ cvars as they are temporary
             int n = buf_getsize(h);
             for (int i = 0; i < n; ++i) {
                 string k = bufstr_get(h, i);
                 string v = cvar_string(k);
                 string d = cvar_defstring(k);
                 if (v == d)
                     continue;
                 s = strcat(s, k, " \"", v, "\" // \"", d, "\"\n");
             }
             buf_del(h);
             LOG_INFO(s);
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 ", GetProgramCommandPrefix(), " cvar_localchanges");
             return;
         }
     }
 }
GENERIC_COMMAND() [4/5]
GENERIC_COMMAND (findent , "Search through entities for matching classname" , false)
Definition at line 340 of file debug.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, FOREACH_ENTITY_CLASS_ORDERED, LOG_HELP, LOG_HELPF, and LOG_INFOF.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             int entcnt = 0;
             FOREACH_ENTITY_CLASS_ORDERED(argv(1), true,
             {
                 LOG_HELPF("%i (%s)", it, it.classname);
                 ++entcnt;
             });
             if(entcnt)
                 LOG_HELPF("Found %d entities", entcnt);
             return;
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 " GetProgramCommandPrefix() " find <classname>");
             LOG_HELP("  Where <classname> is the classname to search for.");
             return;
         }
     }
 }
GENERIC_COMMAND() [5/5]
GENERIC_COMMAND (findat , "Search through entities for matching origin" , false)
Definition at line 369 of file debug.qh.
References argv(), ATTRIB, CLASS(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, CONSTRUCT, CONSTRUCTOR, DESTRUCTOR, DRAWFLAG_NORMAL, ENDCLASS, ERASEABLE, eY, fade_rate, FOREACH_ENTITY_ORDERED, g_drawables_2d, GetResource(), health, IL_PUSH(), LOG_HELP, LOG_HELPF, LOG_INFOF, make_impure, message, min(), MSG_BROADCAST, NET_HANDLE, NEW, origin, project_3d_to_2d(), ReadString, REGISTER_NET_TEMP, RES_HEALTH, SetResource(), size, stof(), stov(), strfree, stringwidth, strzone(), time, tokenizebyseparator, vdist, vector(), velocity, and WriteString().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             vector org = stov(argv(1));
             float dist = stof(argv(2));
             int entcnt = 0;
             FOREACH_ENTITY_ORDERED(true,
             {
                 if (dist > 0)
                 {
                     if (!vdist(it.origin - org, <, dist))
                         continue;
                 }
                 else if (it.origin != org)
                     continue;
                 LOG_HELPF("%i (%s)", it, it.classname);
                 ++entcnt;
             });
             if(entcnt)
                 LOG_HELPF("Found %d entities", entcnt);
             return;
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 " GetProgramCommandPrefix() " findat <position> [<dist>]");
             LOG_HELP("  Where <position> is a vector \"x y z\"");
             return;
         }
     }
 }