Xonotic: common/triggers/func/train.qc File Reference
train.qc File Reference
#include "train.qh"
Functions
void train_next (entity this)
entity train_next_find (entity this)
void train_wait (entity this)
Variables
entity future_target
float train_wait_turning
Function Documentation
void train_next (entity this)
Definition at line 83 of file train.qc.
References _sound, ATTEN_IDLE, CH_TRIGGER_SINGLE, entity(), find(), future_target, noise, NULL, objerror(), platmovetype_end, platmovetype_end_default, platmovetype_start, platmovetype_start_default, spawnflags, SUB_CalcMove(), SUB_CalcMove_Bezier(), target, target_random, targetname, train_next_find(), train_wait(), TSPEED_LINEAR, vector(), view_ofs, VOL_BASE, and wait.
Referenced by dynlight_find_path(), and train_wait().
 {
     entity targ = NULL, cp = NULL;
     vector cp_org = '0 0 0';
     targ = this.future_target;
     this.target = targ.target;
     this.target_random = targ.target_random;
     this.future_target = train_next_find(targ);
     if (this.spawnflags & 1)
     {
         if(targ.curvetarget)
         {
             cp = find(NULL, targetname, targ.curvetarget); // get its second target (the control point)
             cp_org = cp.origin - this.view_ofs; // no control point found, assume a straight line to the destination
         }
     }
     if (this.target == "")
         objerror(this, "train_next: no next target");
     this.wait = targ.wait;
     if (!this.wait)
         this.wait = 0.1;
     if(targ.platmovetype)
     {
         // this path_corner contains a movetype overrider, apply it
         this.platmovetype_start = targ.platmovetype_start;
         this.platmovetype_end = targ.platmovetype_end;
     }
     else
     {
         // this path_corner doesn't contain a movetype overrider, use the train's defaults
         this.platmovetype_start = this.platmovetype_start_default;
         this.platmovetype_end = this.platmovetype_end_default;
     }
     if (targ.speed)
     {
         if (cp)
             SUB_CalcMove_Bezier(this, cp_org, targ.origin - this.view_ofs, TSPEED_LINEAR, targ.speed, train_wait);
         else
             SUB_CalcMove(this, targ.origin - this.view_ofs, TSPEED_LINEAR, targ.speed, train_wait);
     }
     else
     {
         if (cp)
             SUB_CalcMove_Bezier(this, cp_org, targ.origin - this.view_ofs, TSPEED_LINEAR, this.speed, train_wait);
         else
             SUB_CalcMove(this, targ.origin - this.view_ofs, TSPEED_LINEAR, this.speed, train_wait);
     }
     if(this.noise != "")
         _sound(this, CH_TRIGGER_SINGLE, this.noise, VOL_BASE, ATTEN_IDLE);
 }
entity train_next_find (entity this)
Definition at line 66 of file train.qc.
References entity(), find(), NULL, RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), target, target_random, and targetname.
Referenced by train_next().
 {
     if(this.target_random)
     {
         RandomSelection_Init();
         for(entity t = NULL; (t = find(t, targetname, this.target));)
         {
             RandomSelection_AddEnt(t, 1, 0);
         }
         return RandomSelection_chosen_ent;
     }
     else
     {
         return find(NULL, targetname, this.target);
     }
 }
void train_wait (entity this)
Definition at line 8 of file train.qc.
References CH_TRIGGER_SINGLE, enemy, entity(), find(), func_null(), future_target, ltime, MSG_BROADCAST, nextthink, noise, NULL, origin, platmovetype_turn, setthink, spawnflags, stopsoundto(), SUB_CalcAngleMove(), SUB_UseTargets(), targetname, time, train_next(), train_wait_turning, TSPEED_TIME, use, vectoangles(), vector(), view_ofs, and wait.
Referenced by train_next().
 {
     SUB_UseTargets(this.enemy, NULL, NULL);
     this.enemy = NULL;
     // if turning is enabled, the train will turn toward the next point while waiting
     if(this.platmovetype_turn && !this.train_wait_turning)
     {
         entity targ, cp;
         vector ang;
         targ = this.future_target;
         if((this.spawnflags & 1) && targ.curvetarget)
             cp = find(NULL, targetname, targ.curvetarget);
         else
             cp = NULL;
         if(cp) // bezier curves movement
             ang = cp.origin - (this.origin - this.view_ofs); // use the origin of the control point of the next path_corner
         else // linear movement
             ang = targ.origin - (this.origin - this.view_ofs); // use the origin of the next path_corner
         ang = vectoangles(ang);
         ang_x = -ang_x; // flip up / down orientation
         if(this.wait > 0) // slow turning
             SUB_CalcAngleMove(this, ang, TSPEED_TIME, this.ltime - time + this.wait, train_wait);
         else // instant turning
             SUB_CalcAngleMove(this, ang, TSPEED_TIME, 0.0000001, train_wait);
         this.train_wait_turning = true;
         return;
     }
 #ifdef SVQC
     if(this.noise != "")
         stopsoundto(MSG_BROADCAST, this, CH_TRIGGER_SINGLE); // send this as unreliable only, as the train will resume operation shortly anyway
 #endif
 #ifdef SVQC
     entity tg = this.future_target;
     if(tg.spawnflags & 4)
     {
         this.use = train_use;
         setthink(this, func_null);
         this.nextthink = 0;
     }
     else
 #endif
          if(this.wait < 0 || this.train_wait_turning) // no waiting or we already waited while turning
     {
         this.train_wait_turning = false;
         train_next(this);
     }
     else
     {
         setthink(this, train_next);
         this.nextthink = this.ltime + this.wait;
     }
 }
Variable Documentation
entity future_target
Definition at line 3 of file train.qc.
Referenced by train_next(), and train_wait().
float train_wait_turning
Definition at line 2 of file train.qc.
Referenced by train_wait().