Xonotic: common/util.qh File Reference
util.qh File Reference
Macros
#define COMMON_UTIL_H
#define TIME_TO_NTHS(t, n) floor((t) * (n) + 0.4)
#define TIME_ENCODED_TOSTRING(n) mmssss(n)
#define RACE_RECORD "/race100record/"
#define CTS_RECORD "/cts100record/"
#define TIME_ENCODE(t) TIME_TO_NTHS(t, TIME_FACTOR)
#define TIME_DECODE(n) ((n) / TIME_FACTOR)
#define FOR_EACH_TAG(v) float tagnum; Skeleton_SetBones(v); for(tagnum = 0; tagnum < v.skeleton_bones; tagnum++, gettaginfo(v, tagnum))
#define XPD(...) __VA_ARGS__
#define fprintf(file,...) fputs(file, sprintf(__VA_ARGS__))
#define bprintf(...) bprint(sprintf(__VA_ARGS__))
#define GENTLE autocvar_sv_gentle
#define normal_or_gentle(normal, gentle) (GENTLE ? ((gentle != "") ? gentle : normal) : normal)
#define APPEND_TO_STRING(list, sep, add) ((list) = (((list) != "") ? strcat(list, sep, add) : (add)))
#define COMPARE_INCREASING(to, from) (to < from ? from + to + 2 : to - from)
Functions
vector real_origin (entity ent)
string wordwrap (string s, float l)
void wordwrap_sprint (string s, float l)
void wordwrap_cb (string s, float l, void(string) callback)
string draw_UseSkinFor (string pic)
void depthfirst (entity start,.entity up,.entity downleft,.entity right, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
float median (float a, float b, float c)
string ftos_decimals (float number, float decimals)
bool fexists (string f)
string fstrunzone (string s)
unzone the string, and return it as tempstring.
void db_save (int db, string filename)
void db_dump (int db, string pFilename)
int db_create ()
int db_load (string filename)
void db_close (int db)
string db_get (int db, string key)
void db_put (int db, string key, string value)
int buf_load (string filename)
void buf_save (int buf, string filename)
string format_time (float seconds)
string mmsss (float t)
string mmssss (float t)
string ScoreString (float vflags, float value)
void compressShortVector_init ()
vector decompressShortVector (float data)
float compressShortVector (vector vec)
float CheckWireframeBox (entity forent, vector v0, vector dvx, vector dvy, vector dvz)
string fixPriorityList (string pl, float from, float to, float subtract, float complete)
string mapPriorityList (string order, string(string) mapfunc)
string swapInPriorityList (string order, float i, float j)
float cvar_value_issafe (string s)
float cvar_settemp (string pKey, string pValue)
float cvar_settemp_restore ()
void get_mi_min_max (float mode)
void get_mi_min_max_texcoords (float mode)
float almost_equals (float a, float b)
float almost_in_bounds (float a, float b, float c)
float power2of (float e)
float log2of (float x)
vector rgb_to_hsl (vector rgb)
vector hsl_to_rgb (vector hsl)
vector rgb_to_hsv (vector rgb)
vector hsv_to_rgb (vector hsv)
string rgb_to_hexcolor (vector rgb)
float boxesoverlap (vector m1, vector m2, vector m3, vector m4)
requires that m2>m1 in all coordinates, and that m4>m3
float boxinsidebox (vector smins, vector smaxs, vector bmins, vector bmaxs)
requires the same as boxesoverlap, but is a stronger condition
typedef float (string s, vector size) textLengthUpToWidth_widthFunction_t
typedef float (string s) textLengthUpToLength_lenFunction_t
float textLengthUpToWidth (string theText, float maxWidth, vector size, textLengthUpToWidth_widthFunction_t tw)
string textShortenToWidth (string theText, float maxWidth, vector size, textLengthUpToWidth_widthFunction_t tw)
float textLengthUpToLength (string theText, float maxWidth, textLengthUpToLength_lenFunction_t tw)
string textShortenToLength (string theText, float maxWidth, textLengthUpToLength_lenFunction_t tw)
string getWrappedLine (float w, vector size, textLengthUpToWidth_widthFunction_t tw)
string getWrappedLineLen (float w, textLengthUpToLength_lenFunction_t tw)
float isGametypeInFilter (float gt, float tp, float ts, string pattern)
string swapwords (string str, float i, float j)
string shufflewords (string str)
string substring_range (string s, float b, float e)
vector solve_quadratic (float a, float b, float c)
ax^2 + bx + c = 0
vector solve_shotdirection (vector myorg, vector myvel, vector eorg, vector evel, float spd, float newton_style)
vector get_shotvelocity (vector myvel, vector mydir, float spd, float newton_style, float mi, float ma)
float compressShotOrigin (vector v)
vector decompressShotOrigin (float f)
vector healtharmor_maxdamage (float h, float a, float armorblock, int deathtype)
vector healtharmor_applydamage (float a, float armorblock, int deathtype, float damage)
string getcurrentmod ()
void WriteInt24_t (float dest, float val)
void WriteInt48_t (float dest, vector val)
void WriteInt72_t (float dest, vector val)
float float2range11 (float f)
continuous function mapping all reals into -1..1
float float2range01 (float f)
continuous function mapping all reals into 0..1
float gsl_ran_gaussian (float sigma)
float matchacl (string acl, string str)
string get_model_datafilename (string mod, float skn, string fil)
float get_model_parameters (string mod, float skn)
vector NearestPointOnBox (entity box, vector org)
float vercmp (string v1, string v2)
float u8_strsize (string s)
string xencode (float f)
float xdecode (string s)
string strtolower (string s)
string MakeConsoleSafe (string input)
escape the string to make it safe for consoles
void Shutdown ()
void Skeleton_SetBones (entity e)
void execute_next_frame ()
void queue_to_execute_next_frame (string s)
float cubic_speedfunc (float startspeedfactor, float endspeedfactor, float x)
float cubic_speedfunc_is_sane (float startspeedfactor, float endspeedfactor)
typedef entity (entity cur, entity near, entity pass) findNextEntityNearFunction_t
typedef float (entity a, entity b, entity pass) isConnectedFunction_t
void FindConnectedComponent (entity e,.entity fld, findNextEntityNearFunction_t nxt, isConnectedFunction_t iscon, entity pass)
string CCR (string input)
color code replace, place inside of sprintf and parse the string
vector animfixfps (entity e, vector a, vector b)
float Announcer_PickNumber (float type, float num)
int Mod_Q1BSP_SuperContentsFromNativeContents (int nativecontents)
int Mod_Q1BSP_NativeContentsFromSuperContents (int supercontents)
vector bezier_quadratic_getpoint (vector a, vector p, vector b, float t)
vector bezier_quadratic_getderivative (vector a, vector p, vector b, float t)
Variables
string draw_currentSkin
const float TIME_DECIMALS = 2
const float TIME_FACTOR = 100
string mi_shortname
vector mi_min
vector mi_max
vector mi_picmin
vector mi_picmax
vector mi_pictexcoord0
vector mi_pictexcoord1
vector mi_pictexcoord2
vector mi_pictexcoord3
string getWrappedLine_remaining
string get_model_parameters_modelname
float get_model_parameters_modelskin
string get_model_parameters_name
float get_model_parameters_species
string get_model_parameters_sex
float get_model_parameters_weight
float get_model_parameters_age
string get_model_parameters_description
string get_model_parameters_bone_upperbody
string get_model_parameters_bone_weapon
const int MAX_AIM_BONES = 4
string get_model_parameters_bone_aim [MAX_AIM_BONES]
float get_model_parameters_bone_aimweight [MAX_AIM_BONES]
float get_model_parameters_fixbone
string get_model_parameters_desc
const float XENCODE_MAX = 21295
const float XENCODE_LEN = 5
float skeleton_bones
noref float unused_float
const float CNT_NORMAL = 1
const float CNT_GAMESTART = 2
const float CNT_IDLE = 3
const float CNT_KILL = 4
const float CNT_RESPAWN = 5
const float CNT_ROUNDSTART = 6
Macro Definition Documentation
#define APPEND_TO_STRING (list, sep, add) ((list) = (((list) != "") ? strcat(list, sep, add) : (add)))
Definition at line 301 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback().
#define bprintf (...) bprint(sprintf(__VA_ARGS__))
Definition at line 261 of file util.qh.
Referenced by CheatsAllowed().
#define COMMON_UTIL_H
Definition at line 2 of file util.qh.
#define COMPARE_INCREASING (to, from) (to < from ? from + to + 2 : to - from)
Definition at line 304 of file util.qh.
Referenced by HitSound(), and UpdateDamage().
#define CTS_RECORD "/cts100record/"
Definition at line 60 of file util.qh.
Referenced by getladder(), getlsmaps(), HUD_Mod_Race(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), and race_writeTime().
#define FOR_EACH_TAG (v) float tagnum; Skeleton_SetBones(v); for(tagnum = 0; tagnum < v.skeleton_bones; tagnum++, gettaginfo(v, tagnum))
Definition at line 224 of file util.qh.
#define fprintf (file, ...) fputs(file, sprintf(__VA_ARGS__))
Definition at line 260 of file util.qh.
#define GENTLE autocvar_sv_gentle
Definition at line 269 of file util.qh.
Referenced by Create_Notification_Entity().
#define normal_or_gentle (normal, gentle) (GENTLE ? ((gentle != "") ? gentle : normal) : normal)
Definition at line 271 of file util.qh.
Referenced by notif_arg_spree_inf().
#define RACE_RECORD "/race100record/"
Definition at line 59 of file util.qh.
Referenced by getladder(), getlsmaps(), HUD_Mod_Race(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), and race_writeTime().
#define TIME_DECODE (n) ((n) / TIME_FACTOR)
Definition at line 62 of file util.qh.
Referenced by HUD_RaceTimer(), and race_setTime().
#define TIME_ENCODE (t) TIME_TO_NTHS(t, TIME_FACTOR)
Definition at line 61 of file util.qh.
Referenced by HUD_RaceTimer(), MakeRaceString(), race_ImposePenaltyTime(), race_SendTime(), and write_recordmarker().
#define TIME_ENCODED_TOSTRING (n) mmssss(n)
Definition at line 58 of file util.qh.
Referenced by getrankings(), HUD_DrawScoreboardRankings(), HUD_Mod_Race(), HUD_RaceTimer(), HUD_Score(), MakeRaceString(), ScoreString(), and write_recordmarker().
#define TIME_TO_NTHS (t, n) floor((t) * (n) + 0.4)
Definition at line 51 of file util.qh.
#define XPD (...) __VA_ARGS__
Definition at line 257 of file util.qh.
Function Documentation
float almost_equals (float a, float b)
Definition at line 173 of file math.qh.
References max().
Referenced by GetCurrentFov().
 {
     float eps = (max(a, -a) + max(b, -b)) * 0.001;
     return a - b < eps && b - a < eps;
 }
float almost_in_bounds (float a, float b, float c)
Definition at line 179 of file math.qh.
References max(), and median().
 {
     float eps = (max(a, -a) + max(c, -c)) * 0.001;
     if (a > c) eps = -eps;
     return b == median(a - eps, b, c + eps);
 }
vector animfixfps (entity e, vector a, vector b)
Definition at line 1466 of file util.qc.
 {
     // multi-frame anim: keep as-is
     if(a.y == 1)
     {
         float dur = frameduration(e.modelindex, a.x);
         if (dur <= 0 && b.y)
         {
             a = b;
             dur = frameduration(e.modelindex, a.x);
         }
         if (dur > 0)
             a.z = 1.0 / dur;
     }
     return a;
 }
float Announcer_PickNumber (float type, float num)
Definition at line 1492 of file util.qc.
References CNT_GAMESTART, CNT_IDLE, CNT_KILL, CNT_RESPAWN, CNT_ROUNDSTART, and NOTIF_ABORT.
Referenced by Announcer_Countdown(), KillIndicator_Think(), PlayerPostThink(), and ShowRespawnCountdown().
 {
     switch(type)
     {
         case CNT_GAMESTART:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_GAMESTART_10;
                 case 9:  return ANNCE_NUM_GAMESTART_9;
                 case 8:  return ANNCE_NUM_GAMESTART_8;
                 case 7:  return ANNCE_NUM_GAMESTART_7;
                 case 6:  return ANNCE_NUM_GAMESTART_6;
                 case 5:  return ANNCE_NUM_GAMESTART_5;
                 case 4:  return ANNCE_NUM_GAMESTART_4;
                 case 3:  return ANNCE_NUM_GAMESTART_3;
                 case 2:  return ANNCE_NUM_GAMESTART_2;
                 case 1:  return ANNCE_NUM_GAMESTART_1;
             }
             break;
         }
         case CNT_IDLE:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_IDLE_10;
                 case 9:  return ANNCE_NUM_IDLE_9;
                 case 8:  return ANNCE_NUM_IDLE_8;
                 case 7:  return ANNCE_NUM_IDLE_7;
                 case 6:  return ANNCE_NUM_IDLE_6;
                 case 5:  return ANNCE_NUM_IDLE_5;
                 case 4:  return ANNCE_NUM_IDLE_4;
                 case 3:  return ANNCE_NUM_IDLE_3;
                 case 2:  return ANNCE_NUM_IDLE_2;
                 case 1:  return ANNCE_NUM_IDLE_1;
             }
             break;
         }
         case CNT_KILL:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_KILL_10;
                 case 9:  return ANNCE_NUM_KILL_9;
                 case 8:  return ANNCE_NUM_KILL_8;
                 case 7:  return ANNCE_NUM_KILL_7;
                 case 6:  return ANNCE_NUM_KILL_6;
                 case 5:  return ANNCE_NUM_KILL_5;
                 case 4:  return ANNCE_NUM_KILL_4;
                 case 3:  return ANNCE_NUM_KILL_3;
                 case 2:  return ANNCE_NUM_KILL_2;
                 case 1:  return ANNCE_NUM_KILL_1;
             }
             break;
         }
         case CNT_RESPAWN:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_RESPAWN_10;
                 case 9:  return ANNCE_NUM_RESPAWN_9;
                 case 8:  return ANNCE_NUM_RESPAWN_8;
                 case 7:  return ANNCE_NUM_RESPAWN_7;
                 case 6:  return ANNCE_NUM_RESPAWN_6;
                 case 5:  return ANNCE_NUM_RESPAWN_5;
                 case 4:  return ANNCE_NUM_RESPAWN_4;
                 case 3:  return ANNCE_NUM_RESPAWN_3;
                 case 2:  return ANNCE_NUM_RESPAWN_2;
                 case 1:  return ANNCE_NUM_RESPAWN_1;
             }
             break;
         }
         case CNT_ROUNDSTART:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_ROUNDSTART_10;
                 case 9:  return ANNCE_NUM_ROUNDSTART_9;
                 case 8:  return ANNCE_NUM_ROUNDSTART_8;
                 case 7:  return ANNCE_NUM_ROUNDSTART_7;
                 case 6:  return ANNCE_NUM_ROUNDSTART_6;
                 case 5:  return ANNCE_NUM_ROUNDSTART_5;
                 case 4:  return ANNCE_NUM_ROUNDSTART_4;
                 case 3:  return ANNCE_NUM_ROUNDSTART_3;
                 case 2:  return ANNCE_NUM_ROUNDSTART_2;
                 case 1:  return ANNCE_NUM_ROUNDSTART_1;
             }
             break;
         }
         default:
         {
             switch(num)
             {
                 case 10: return ANNCE_NUM_10;
                 case 9:  return ANNCE_NUM_9;
                 case 8:  return ANNCE_NUM_8;
                 case 7:  return ANNCE_NUM_7;
                 case 6:  return ANNCE_NUM_6;
                 case 5:  return ANNCE_NUM_5;
                 case 4:  return ANNCE_NUM_4;
                 case 3:  return ANNCE_NUM_3;
                 case 2:  return ANNCE_NUM_2;
                 case 1:  return ANNCE_NUM_1;
             }
             break;
         }
     }
     return NOTIF_ABORT; // abort sending if none of these numbers were right
 }
vector bezier_quadratic_getderivative (vector a, vector p, vector b, float t)
Definition at line 79 of file math.qh.
 {
     return (c - 2 * b + a) * (2 * t)
            + (b - a) * 2;
 }
vector bezier_quadratic_getpoint (vector a, vector p, vector b, float t)
Definition at line 72 of file math.qh.
 {
     return (c - 2 * b + a) * (t * t)
            + (b - a) * (2 * t)
            + a;
 }
float boxesoverlap (vector m1, vector m2, vector m3, vector m4)
requires that m2>m1 in all coordinates, and that m4>m3
Definition at line 73 of file vector.qh.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), botframe_autowaypoints_createwp(), conveyor_think(), Fire_ApplyDamage(), havocbot_movetogoal(), navigation_findnearestwaypoint_withdist_except(), navigation_poptouchedgoals(), tracewalk(), waypoint_spawn(), waypoint_spawnforitem_force(), and waypoint_think().
 { return m2_x >= m3_x && m1_x <= m4_x && m2_y >= m3_y && m1_y <= m4_y && m2_z >= m3_z && m1_z <= m4_z; }
float boxinsidebox (vector smins, vector smaxs, vector bmins, vector bmaxs)
requires the same as boxesoverlap, but is a stronger condition
Definition at line 76 of file vector.qh.
 { return smins.x >= bmins.x && smaxs.x <= bmaxs.x && smins.y >= bmins.y && smaxs.y <= bmaxs.y && smins.z >= bmins.z && smaxs.z <= bmaxs.z; }
int buf_load (string filename)
Definition at line 256 of file string.qh.
References buf_create, fclose(), fgets(), FILE_READ, and fopen().
 {
     int buf = buf_create();
     if (buf < 0) return -1;
     int fh = fopen(pFilename, FILE_READ);
     if (fh < 0)
     {
         buf_del(buf);
         return -1;
     }
     string l;
     for (int i = 0; (l = fgets(fh)); ++i)
         bufstr_set(buf, i, l);
     fclose(fh);
     return buf;
 }
void buf_save (int buf, string filename)
string CCR (string input)
color code replace, place inside of sprintf and parse the string
Definition at line 79 of file string.qh.
References autocvar_hud_colorset_background, autocvar_hud_colorset_foreground_1, autocvar_hud_colorset_foreground_2, autocvar_hud_colorset_foreground_3, autocvar_hud_colorset_foreground_4, autocvar_hud_colorset_kill_1, autocvar_hud_colorset_kill_2, autocvar_hud_colorset_kill_3, and strcat().
Referenced by notif_arg_spree_inf().
 {
     // See the autocvar declarations in util.qh for default values
     // foreground/normal colors
     input = strreplace("^F1", strcat("^", autocvar_hud_colorset_foreground_1), input);
     input = strreplace("^F2", strcat("^", autocvar_hud_colorset_foreground_2), input);
     input = strreplace("^F3", strcat("^", autocvar_hud_colorset_foreground_3), input);
     input = strreplace("^F4", strcat("^", autocvar_hud_colorset_foreground_4), input);
     // "kill" colors
     input = strreplace("^K1", strcat("^", autocvar_hud_colorset_kill_1), input);
     input = strreplace("^K2", strcat("^", autocvar_hud_colorset_kill_2), input);
     input = strreplace("^K3", strcat("^", autocvar_hud_colorset_kill_3), input);
     // background colors
     input = strreplace("^BG", strcat("^", autocvar_hud_colorset_background), input);
     input = strreplace("^N", "^7", input);  // "none"-- reset to white...
     return input;
 }
float CheckWireframeBox (entity forent, vector v0, vector dvx, vector dvy, vector dvz)
Definition at line 353 of file util.qc.
References trace_fraction.
Referenced by Portal_Spawn(), and Porto_Draw().
 {
     traceline(v0, v0 + dvx, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0, v0 + dvy, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0, v0 + dvz, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvx, v0 + dvx + dvy, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvx, v0 + dvx + dvz, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvy, v0 + dvy + dvx, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvy, v0 + dvy + dvz, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvz, v0 + dvz + dvx, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvz, v0 + dvz + dvy, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvx + dvy, v0 + dvx + dvy + dvz, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvx + dvz, v0 + dvx + dvy + dvz, true, forent); if(trace_fraction < 1) return 0;
     traceline(v0 + dvy + dvz, v0 + dvx + dvy + dvz, true, forent); if(trace_fraction < 1) return 0;
     return 1;
 }
float compressShortVector (vector vec)
Definition at line 293 of file util.qc.
References error(), floor(), invertLengthLog(), p, vectoangles(), vector(), and vlen().
Referenced by compressShortVector_init().
 {
     vector ang;
     float p, y, len;
     if(vlen(vec) == 0)
         return 0;
     //print("compress: ", vtos(vec), "\n");
     ang = vectoangles(vec);
     ang.x = -ang.x;
     if(ang.x < -90)
         ang.x += 360;
     if(ang.x < -90 && ang.x > +90)
         error("BOGUS vectoangles");
     //print("angles: ", vtos(ang), "\n");
     p = floor(0.5 + (ang.x + 90) * 16 / 180) & 15; // -90..90 to 0..14
     if(p == 0)
     {
         if(vec.z < 0)
             y = 31;
         else
             y = 30;
     }
     else
         y = floor(0.5 + ang.y * 32 / 360)          & 31; // 0..360 to 0..32
     len = invertLengthLog(vlen(vec));
     //print("compressed: p ", ftos(p)); print("y ", ftos(y)); print("len ", ftos(len), "\n");
     return (p * 0x1000) + (y * 0x80) + len;
 }
void compressShortVector_init ()
Definition at line 325 of file util.qc.
References compressShortVector(), cvar(), decompressShortVector(), error(), ftos(), LOG_INFO, pow(), and vtos().
Referenced by CSQC_Init(), and spawnfunc().
 {
     float l = 1;
     float f = pow(2, 1/8);
     int i;
     for(i = 0; i < 128; ++i)
     {
         lengthLogTable[i] = l;
         l *= f;
     }
     if(cvar("developer"))
     {
         LOG_INFO("Verifying vector compression table...\n");
         for(i = 0x0F00; i < 0xFFFF; ++i)
             if(i != compressShortVector(decompressShortVector(i)))
             {
                 LOG_INFO("BROKEN vector compression: ", ftos(i));
                 LOG_INFO(" -> ", vtos(decompressShortVector(i)));
                 LOG_INFO(" -> ", ftos(compressShortVector(decompressShortVector(i))));
                 LOG_INFO("\n");
                 error("b0rk");
             }
         LOG_INFO("Done.\n");
     }
 }
float compressShotOrigin (vector v)
Definition at line 1082 of file util.qc.
References bound(), LOG_INFO, rint(), and vtos().
Referenced by CL_WeaponEntity_SetModel(), and ClientInit_misc().
 {
     float x, y, z;
     x = rint(v.x * 2);
     y = rint(v.y * 4) + 128;
     z = rint(v.z * 4) + 128;
     if(x > 255 || x < 0)
     {
         LOG_INFO("shot origin ", vtos(v), " x out of bounds\n");
         x = bound(0, x, 255);
     }
     if(y > 255 || y < 0)
     {
         LOG_INFO("shot origin ", vtos(v), " y out of bounds\n");
         y = bound(0, y, 255);
     }
     if(z > 255 || z < 0)
     {
         LOG_INFO("shot origin ", vtos(v), " z out of bounds\n");
         z = bound(0, z, 255);
     }
     return x * 0x10000 + y * 0x100 + z;
 }
float cubic_speedfunc (float startspeedfactor, float endspeedfactor, float x)
Definition at line 85 of file math.qh.
Referenced by SUB_CalcMove_controller_think().
 {
     return (((startspeedfactor + endspeedfactor - 2
              ) * x - 2 * startspeedfactor - endspeedfactor + 3
             ) * x + startspeedfactor
            ) * x;
 }
float cubic_speedfunc_is_sane (float startspeedfactor, float endspeedfactor)
Definition at line 93 of file math.qh.
Referenced by set_platmovetype().
 {
     if (startspeedfactor < 0 || endspeedfactor < 0) return false;
     /*
     // if this is the case, the possible zeros of the first derivative are outside
     // 0..1
     We can calculate this condition as condition
     if(se <= 3)
         return true;
     */
     // better, see below:
     if (startspeedfactor <= 3 && endspeedfactor <= 3) return true;
     // if this is the case, the first derivative has no zeros at all
     float se = startspeedfactor + endspeedfactor;
     float s_e = startspeedfactor - endspeedfactor;
     if (3 * (se - 4) * (se - 4) + s_e * s_e <= 12)  // an ellipse
         return true;
     // Now let s <= 3, s <= 3, s+e >= 3 (triangle) then we get se <= 6 (top right corner).
     // we also get s_e <= 6 - se
     // 3 * (se - 4)^2 + (6 - se)^2
     // is quadratic, has value 12 at 3 and 6, and value < 12 in between.
     // Therefore, above "better" check works!
     return false;
     // known good cases:
     // (0, [0..3])
     // (0.5, [0..3.8])
     // (1, [0..4])
     // (1.5, [0..3.9])
     // (2, [0..3.7])
     // (2.5, [0..3.4])
     // (3, [0..3])
     // (3.5, [0.2..2.3])
     // (4, 1)
     /*
        On another note:
        inflection point is always at (2s + e - 3) / (3s + 3e - 6).
        s + e - 2 == 0: no inflection
        s + e > 2:
        0 < inflection < 1 if:
        0 < 2s + e - 3 < 3s + 3e - 6
        2s + e > 3 and 2e + s > 3
        s + e < 2:
        0 < inflection < 1 if:
        0 > 2s + e - 3 > 3s + 3e - 6
        2s + e < 3 and 2e + s < 3
        Therefore: there is an inflection point iff:
        e outside (3 - s)/2 .. 3 - s*2
        in other words, if (s,e) in triangle (1,1)(0,3)(0,1.5) or in triangle (1,1)(3,0)(1.5,0)
     */
 }
float cvar_settemp (string pKey, string pValue)
Definition at line 584 of file util.qc.
References FOREACH_ENTITY_CLASS, LOG_INFOF, and LOG_TRACE().
Referenced by _MapInfo_Parse_Settemp(), CSQC_UpdateView(), CSQCPlayer_PostUpdate(), CSQCPlayer_Remove(), GameCommand_bot_cmd(), GameCommand_setbots(), GenericCommand_settemp(), and REGISTER_MUTATOR().
 {
     float created_saved_value;
     created_saved_value = 0;
     if (!(tmp_cvar || tmp_value))
     {
         LOG_TRACE("Error: Invalid usage of cvar_settemp(string, string); !\n");
         return 0;
     }
     if(!cvar_type(tmp_cvar))
     {
         LOG_INFOF("Error: cvar %s doesn't exist!\n", tmp_cvar);
         return 0;
     }
     FOREACH_ENTITY_CLASS("saved_cvar_value", it.netname == tmp_cvar,
     {
         created_saved_value = -1; // skip creation
         break; // no need to continue
     });
     if(created_saved_value != -1)
     {
         // creating a new entity to keep track of this cvar
         entity e = new(saved_cvar_value);
         make_pure(e);
         e.netname = strzone(tmp_cvar);
         e.message = strzone(cvar_string(tmp_cvar));
         created_saved_value = 1;
     }
     // update the cvar to the value given
     cvar_set(tmp_cvar, tmp_value);
     return created_saved_value;
 }
float cvar_settemp_restore ()
Definition at line 624 of file util.qc.
References cvar_set(), FOREACH_ENTITY_CLASS, LOG_INFOF, and strunzone().
Referenced by GenericCommand_settemp_restore(), and MapInfo_LoadMap().
 {
     int j = 0;
     // FIXME this new-style loop fails!
 #if 0
     FOREACH_ENTITY_CLASS("saved_cvar_value", true,
     {
         if(cvar_type(it.netname))
         {
             cvar_set(it.netname, it.message);
             strunzone(it.netname);
             strunzone(it.message);
             remove(it);
             ++j;
         }
         else
             LOG_INFOF("Error: cvar %s doesn't exist anymore! It can still be restored once it's manually recreated.\n", it.netname);
     });
 #else
     entity e = world;
     while((e = find(e, classname, "saved_cvar_value")))
     {
         if(cvar_type(e.netname))
         {
             cvar_set(e.netname, e.message);
             remove(e);
             ++j;
         }
         else
             print(sprintf("Error: cvar %s doesn't exist anymore! It can still be restored once it's manually recreated.\n", e.netname));
     }
 #endif
     return j;
 }
float cvar_value_issafe (string s)
Definition at line 9 of file cvar.qh.
References strstrofs.
Referenced by _MapInfo_Parse_Settemp(), InitGameplayMode(), and MapInfo_Get_ByName_NoFallbacks().
 {
     if (strstrofs(s, "\"", 0) >= 0) return false;
     if (strstrofs(s, "\\", 0) >= 0) return false;
     if (strstrofs(s, ";", 0) >= 0) return false;
     if (strstrofs(s, "$", 0) >= 0) return false;
     if (strstrofs(s, "\r", 0) >= 0) return false;
     if (strstrofs(s, "\n", 0) >= 0) return false;
     return true;
 }
void db_close (int db)
Definition at line 78 of file map.qh.
Referenced by CSQC_UpdateView(), db_test(), GameCommand_database(), GameCommand_effectindexdump(), GenericCommand_rpn(), MapInfo_Cache_Destroy(), and Shutdown().
 {
     buf_del(db);
 }
int db_create ()
Definition at line 23 of file map.qh.
References buf_create.
Referenced by CSQC_Init(), CSQC_UpdateView(), GameCommand_effectindexdump(), GenericCommand_rpn(), MapInfo_Cache_Create(), and spawnfunc().
 {
     return buf_create();
 }
void db_dump (int db, string pFilename)
Definition at line 64 of file map.qh.
References argv(), fclose(), FILE_WRITE, fopen(), fputs(), LOG_FATALF, strcat(), and tokenizebyseparator.
Referenced by GameCommand_database(), and Shutdown().
 {
     int fh = fopen(filename, FILE_WRITE);
     if (fh < 0) LOG_FATALF("Can't dump DB to %s\n");
     fputs(fh, "0\n");
     for (int i = 0, n = buf_getsize(db); i < n; ++i)
     {
         int m = tokenizebyseparator(bufstr_get(db, i), "\\");
         for (int j = 2; j < m; j += 2)
             fputs(fh, strcat("\\", argv(j - 1), "\\", argv(j), "\n"));
     }
     fclose(fh);
 }
string db_get (int db, string key)
Definition at line 84 of file map.qh.
References DB_BUCKETS.
Referenced by GameCommand_effectindexdump(), GenericCommand_rpn(), getcommandkey(), getladder(), getlsmaps(), HUD_Mod_Race(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), race_readName(), race_readTime(), race_readUID(), and uid2name().
 {
     int h = crc16(false, key) % DB_BUCKETS;
     return uri_unescape(infoget(bufstr_get(db, h), key));
 }
int db_load (string filename)
Definition at line 31 of file map.qh.
References argv(), buf_create, DB_BUCKETS, db_put(), fclose(), fgets(), FILE_READ, fopen(), stoi, and tokenizebyseparator.
Referenced by CSQC_Init(), db_test(), GameCommand_database(), GenericCommand_rpn(), RestoreGame(), and spawnfunc().
 {
     int db = buf_create();
     if (db < 0) return -1;
     int fh = fopen(filename, FILE_READ);
     if (fh < 0) return db;
     string l = fgets(fh);
     if (stoi(l) == DB_BUCKETS)
     {
         for (int i = 0; (l = fgets(fh)); ++i)
         {
             if (l != "") bufstr_set(db, i, l);
         }
     }
     else
     {
         // different count of buckets, or a dump?
         // need to reorganize the database then (SLOW)
         //
         // note: we also parse the first line (l) in case the DB file is
         // missing the bucket count
         do
         {
             int n = tokenizebyseparator(l, "\\");
             for (int j = 2; j < n; j += 2)
                 db_put(db, argv(j - 1), uri_unescape(argv(j)));
         }
         while ((l = fgets(fh)));
     }
     fclose(fh);
     return db;
 }
void db_put (int db, string key, string value)
Definition at line 93 of file map.qh.
References DB_BUCKETS.
Referenced by db_load(), db_test(), GameCommand_effectindexdump(), GenericCommand_rpn(), getcommandkey(), getladder(), HUD_Mod_Race(), MapInfo_Cache_Store(), race_deleteTime(), race_writeTime(), and uid2name().
 {
     int h = crc16(false, key) % DB_BUCKETS;
     bufstr_set(db, h, infoadd(bufstr_get(db, h), key, uri_escape(value)));
 }
void db_save (int db, string filename)
Definition at line 7 of file map.qh.
References DB_BUCKETS, fclose(), FILE_WRITE, fopen(), fputs(), ftos(), LOG_WARNINGF, and strcat().
Referenced by db_test(), GameCommand_database(), GenericCommand_rpn(), and Shutdown().
 {
     int fh = fopen(filename, FILE_WRITE);
     if (fh < 0)
     {
         LOG_WARNINGF("^1Can't write DB to %s\n", filename);
         return;
     }
     fputs(fh, strcat(ftos(DB_BUCKETS), "\n"));
     for (int i = 0, n = buf_getsize(db); i < n; ++i)
         fputs(fh, strcat(bufstr_get(db, i), "\n"));
     fclose(fh);
 }
vector decompressShortVector (float data)
vector decompressShotOrigin (float f)
void depthfirst (entity start, .entity up, .entity downleft, .entity right, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
Definition at line 157 of file util.qc.
References entity().
Referenced by forAllDescendants(), and GameCommand().
 {
     entity e;
     e = start;
     funcPre(pass, e);
     while (e.(downleft))
     {
         e = e.(downleft);
         funcPre(pass, e);
     }
     funcPost(pass, e);
     while(e != start)
     {
         if (e.(right))
         {
             e = e.(right);
             funcPre(pass, e);
             while (e.(downleft))
             {
                 e = e.(downleft);
                 funcPre(pass, e);
             }
         }
         else
             e = e.(up);
         funcPost(pass, e);
     }
 }
string draw_UseSkinFor (string pic)
Definition at line 83 of file util.qc.
References draw_currentSkin, strcat(), strlen(), and substring().
Referenced by draw_BorderPicture(), draw_ButtonPicture(), draw_Picture(), draw_PictureSize(), draw_PreloadPicture(), draw_PreloadPictureWithFlags(), draw_setMousePointer(), draw_VertButtonPicture(), and MapVote_DrawMapItem().
 {
     if(substring(pic, 0, 1) == "/")
         return substring(pic, 1, strlen(pic)-1);
     else
         return strcat(draw_currentSkin, "/", pic);
 }
typedef entity (entity cur, entity near, entity pass)
Referenced by __spawn(), _Movetype_Impact(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Follow(), _Movetype_Physics_Pusher(), _Movetype_Physics_Walk(), _Movetype_PushMove(), accuracy_add(), accuracy_init(), accuracy_send(), adaptor_think2touch(), adaptor_think2use(), addPowerupItem(), anticheat_endframe(), AuditLists(), Ban_LoadBans(), BanCommand_kickban(), BanCommand_mute(), BanCommand_unmute(), bd_check_winner(), bd_close_editor(), bd_do_fill(), bd_editor_place(), bd_find_dozer(), bd_find_piece(), bd_load_level(), bd_load_piece(), bd_move(), bd_move_dozer(), bd_reset_moves(), bd_save_level(), bd_setup_pieces(), bd_unfill_recurse(), bot_cmd_aimtarget(), bot_cmd_movetotarget(), bot_command_executed(), bot_endgame(), bot_getplace(), bot_relinkplayerlist(), bot_removefromlargestteam(), bot_removenewest(), bot_serverframe(), bot_spawn(), botframe_autowaypoints_createwp(), botframe_autowaypoints_fix_from(), botframe_deleteuselesswaypoints(), botframe_showwaypointlinks(), botframe_updatedangerousobjects(), c4_find_piece(), c4_move(), c4_winning_piece(), CallbackChain_Add(), CheatCommand(), CheatImpulse(), CheckAllowedTeams(), checkpoint_passed(), CL_SpawnWeaponentity(), CL_Weapon_GetShotOrg(), client_hasweapon(), ClientCommand_minigame(), ClientCommand_tell(), ClientCommand_voice(), ClientConnect(), ClientData_Send(), ClientInit_Spawn(), ClientKill_Now_TeamChange(), ClientKill_TeamChange(), Cmd_MapVote_MapDownload(), CommonCommand_editmob(), conveyor_think(), CopyBody(), Create_Effect_Entity(), Create_Notification_Entity(), crosshair_trace_plusvisibletriggers(), CSQC_UpdateView(), CSQCModel_Draw(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_SetCamera(), Damage(), deactivate_minigame(), Deathtype_Name(), debuggoalstack(), defer(), defer_think(), depthfirst(), Destroy_All_Notifications(), dialog_hudpanel_common_notoggle(), door_damage(), door_fire(), door_spawnfield(), door_use(), Drag(), Drag_Finish(), Drag_Update(), Draw_ShowNames_All(), Dump_Notifications(), dynlight_find_aiment(), dynlight_find_path(), dynlight_find_target(), EFFECT_ROCKETMINSTA_LASER(), EliminatedPlayers_SendEntity(), end_minigame(), EndFrame(), find_bot_by_name(), find_bot_by_number(), FindConnectedComponent(), findnearest(), Fire_ApplyDamage(), fireBullet(), FireGrapplingHook(), FireImoBeam(), FireRailgunBullet(), formatmessage(), Freeze(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_animbench(), GameCommand_anticheat(), GameCommand_bot_cmd(), GameCommand_defer_clear(), GameCommand_find(), GameCommand_gettaginfo(), GameCommand_make_mapinfo(), GameCommand_moveplayer(), GameCommand_playerdemo(), GameCommand_stuffto(), GameCommand_trace(), GameTypeVote_DrawGameTypeItem(), GetFilteredEntity(), GetFilteredNumber(), GetIndexedEntity(), GetPlayerScoreString(), GetTeam(), GetTeamScoreString(), GrapplingHookThink(), havocbot_ai(), havocbot_chooseenemy(), havocbot_dodge(), havocbot_goalrating_controlpoints(), havocbot_goalrating_items(), havocbot_moveto(), havocbot_moveto_refresh_route(), havocbot_movetogoal(), HUD_Crosshair(), HUD_DrawScoreboard(), HUD_InfoMessages(), HUD_MinigameBoard(), HUD_MinigameMenu(), HUD_MinigameMenu_Click(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_CustomEntry(), HUD_MinigameMenu_MouseInput(), HUD_MinigameMenu_SpawnEntry(), HUD_MinigameMenu_SpawnSubEntry(), HUD_MinigameStatus(), HUD_Mod_Race(), HUD_Panel_InputEvent(), HUD_Powerups(), HUD_Quickmenu_PlayerListEntries(), HUD_Score(), HUD_Score_Rankings(), HUD_Scoreboard_MakeTable(), HUD_UpdatePlayerTeams(), HUD_Weapons(), IMPULSE(), ImpulseCommands(), info_autoscreenshot_findtarget(), InitializeEntitiesRun(), InitializeEntity(), join_minigame(), KillIndicator_Think(), LinkDoors(), Local_Notification(), LocalCommand_boxparticles(), LocalCommand_debugmodel(), LODmodel_attach(), m_activate_window(), m_findtooltipitem(), m_goto(), m_keydown(), m_setpointerfocus(), m_tooltip(), make_safe_for_remove(), MapVote_CheckPK3(), METHOD(), minigame_addplayer(), minigame_CheckSend(), minigame_count_players(), minigame_find_player(), minigame_resend(), minigame_rmplayer(), minigame_SendEntity(), minigame_setup_snake(), MinigameImpulse(), Monster_Damage(), Monster_Delay(), monster_dropitem(), Monster_FindTarget(), Monster_Move(), Monster_Spawn(), Monster_Spawn_Setup(), MoveToRandomLocationWithinBounds(), msle_spawn(), Nagger_SendEntity(), navigation_findnearestwaypoint(), navigation_findnearestwaypoint_withdist_except(), navigation_markroutes(), navigation_markroutes_inverted(), navigation_markroutes_nearestwaypoints(), navigation_routerating(), navigation_unstuck(), NearestLocation(), NET_HANDLE(), NextLevel(), nmm_find_tile(), nmm_in_mill_string(), nmm_kill_tiles(), nmm_spawn_tile(), nmm_tile_canmove(), Obituary_SpecialDeath(), ons_generator_ray_spawn(), part_minigame(), path_build(), pathlib_astar(), pathlib_cleanup(), pathlib_deletepath(), pathlib_expandnode_starf(), pathlib_getbestopen(), pathlib_makenode_adaptive(), pathlib_mknode(), pathlib_nodeatpoint(), pathlib_showedge(), pathlib_showpath(), pathlib_showsquare(), pathlib_walknode(), pathlib_waypointpath(), pathlib_waypointpath_autostep(), pathlib_waypointpath_step(), pathlib_wpp_bestopen(), PingPLReport_Think(), plat_spawn_inside_trigger(), Playerchecker_Think(), PlayerDamage(), playerdemo_read(), PlayerPreThink(), PlayerScore_Add(), PlayerScore_Attach(), PlayerScore_Clear(), PlayerScore_PlayerStats(), PlayerScore_Sort(), PlayerScore_TeamStats(), PlayerTeamScore_Compare(), PlayerUseKey(), PM_check_hitground(), PM_Footsteps(), PM_Main(), Portal_Remove(), Portal_Spawn(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_Think(), PostInit(), pp_find_piece(), pp_move(), pp_next_match(), pp_setup_pieces(), pp_valid_move(), ps_draw(), ps_find_piece(), ps_move(), ps_move_piece(), ps_setup_pieces(), ps_winning_piece(), PutClientInServer(), PutObserverInServer(), race_ClearRecords(), race_GetFractionalLapCount(), race_SendTime(), RadiusDamageForSource(), RandomSeed_Spawn(), ReadyRestart_force(), real_origin(), RegisterPlayer(), RegisterTeam(), relocate_spawnpoint(), RemovePlayer(), RemoveTeam(), reset_map(), resetPowerupItems(), round_handler_Init(), round_handler_Reset(), round_handler_Spawn(), Score_ClearAll(), Score_NicePrint(), Score_NicePrint_Player(), Score_NicePrint_Team(), SelectSpawnPoint(), SetSpectatee(), SetTeam(), ShufflePlayerOutOfTeam(), Simple_TeleportPlayer(), snake_add_score(), snake_alone(), snake_check_winner(), snake_eat_team(), snake_find_cnt(), snake_find_head(), snake_find_piece(), snake_get_player(), snake_head_think(), snake_move(), snake_move_body(), snake_move_head(), snake_new_mouse(), snake_winning_team(), Sort_Spawn(), Spawn_FilterOutBadSpots(), Spawn_Score(), Spawn_ScoreAll(), Spawn_WeightedPoint(), spawnfunc(), spawnmonster(), SpectatePrev(), start_minigame(), STATIC_INIT(), steerlib_flock(), steerlib_flock2d(), steerlib_swarm(), SUB_CalcAngleMoveEnt(), SUB_CalcMove_Bezier(), SUB_CalcMove_controller_think(), SUB_CalcMoveEnt(), SUB_UseTargets(), target_give_init(), target_init_verify(), TeamScore_AddToTeam(), TeamScore_GetCompareValue(), TeamScore_Spawn(), Teleport_Find(), teleport_findtarget(), Teleport_Touch(), TeleportPlayer(), tracebox_inverted(), train_next(), train_wait(), trigger_impulse_touch1(), trigger_keylock_kill(), trigger_keylock_trigger(), trigger_push_findtarget(), trigger_push_touch(), trigger_race_checkpoint_verify(), TrueAimCheck(), ttt_find_piece(), ttt_move(), ttt_next_match(), turret_construct(), turret_die(), turret_gibtoss(), turret_targettrigger_touch(), UpdateAuxiliaryXhair(), url_multi_fopen(), url_single_fopen(), url_URI_Get_Callback(), vehicle_impulse(), vehicle_tossgib(), vehicles_clearreturn(), vehicles_damage(), vehicles_enter(), vehicles_exit(), vehicles_projectile(), vehicles_reset_colors(), vehicles_setreturn(), vehicles_showwp(), viewmodel_animate(), viewmodel_draw(), VoteCommand_parse(), W_AttachToShotorg(), w_clear(), W_DropEvent(), W_GetCycleWeapon(), W_NameWeaponOrder_MapFunc(), w_ready(), W_Reload(), W_SetupShot_Dir_ProjectileSize_Range(), W_SwitchWeapon(), W_ThrowNewWeapon(), W_WeaponFrame(), WarpZone_Find(), WarpZone_FindRadius(), WarpZone_FindRadius_Recurse(), WarpZone_FixNearClip(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_PostInitialize_Callback(), WarpZone_PostTeleportPlayer_Callback(), WarpZone_Projectile_Touch(), WarpZone_RefSys_SpawnSameRefSys(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_BoxTouchesBrush_Recurse(), waypoint_load_links(), waypoint_load_links_hardwired(), waypoint_removeall(), waypoint_save_links(), waypoint_saveall(), waypoint_schedulerelinkall(), waypoint_spawn(), waypoint_spawnforitem_force(), waypoint_spawnforteleporter_boxes(), waypoint_spawnpersonal(), waypoint_think(), weapon_defaultspawnfunc(), weapon_prepareattack_check(), weapon_prepareattack_checkammo(), weapon_prepareattack_do(), weapon_thinkf(), Weapon_whereis(), weaponorder_swap(), and WinningConditionHelper().
void execute_next_frame ()
Definition at line 1404 of file util.qc.
References localcmd, string_null, and strunzone().
Referenced by CSQC_UpdateView(), m_draw(), and StartFrame().
 {
     if(to_execute_next_frame)
     {
         localcmd("\n", to_execute_next_frame, "\n");
         strunzone(to_execute_next_frame);
         to_execute_next_frame = string_null;
     }
 }
bool fexists (string f)
Definition at line 3 of file file.qh.
References fclose(), FILE_READ, and fopen().
Referenced by bd_save_level(), CheckPlayerModel(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), GenericCommand_maplist(), GenericCommand_rpn(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), METHOD(), precache_playermodel(), PreviewExists(), spawnfunc(), updateCheck(), and updateCompression().
 {
     int fh = fopen(f, FILE_READ);
     if (fh < 0) return false;
     fclose(fh);
     return true;
 }
void FindConnectedComponent (entity e, .entity fld, findNextEntityNearFunction_t nxt, isConnectedFunction_t iscon, entity pass)
Definition at line 1424 of file util.qc.
References entity(), error(), and world.
Referenced by LinkDoors().
 {
     entity queue_start, queue_end;
     // we build a queue of to-be-processed entities.
     // queue_start is the next entity to be checked for neighbors
     // queue_end is the last entity added
     if(e.FindConnectedComponent_processing)
         error("recursion or broken cleanup");
     // start with a 1-element queue
     queue_start = queue_end = e;
     queue_end.(fld) = world;
     queue_end.FindConnectedComponent_processing = 1;
     // for each queued item:
     for (; queue_start; queue_start = queue_start.(fld))
     {
         // find all neighbors of queue_start
         entity t;
         for(t = world; (t = nxt(t, queue_start, pass)); )
         {
             if(t.FindConnectedComponent_processing)
                 continue;
             if(iscon(t, queue_start, pass))
             {
                 // it is connected? ADD IT. It will look for neighbors soon too.
                 queue_end.(fld) = t;
                 queue_end = t;
                 queue_end.(fld) = world;
                 queue_end.FindConnectedComponent_processing = 1;
             }
         }
     }
     // unmark
     for (queue_start = e; queue_start; queue_start = queue_start.(fld))
         queue_start.FindConnectedComponent_processing = 0;
 }
string fixPriorityList (string pl, float from, float to, float subtract, float complete)
Definition at line 371 of file util.qc.
References argv(), floor(), ftos(), stof(), strcat(), strlen(), substring(), and tokenize_console.
Referenced by W_FixWeaponOrder().
 {
     string neworder;
     float i, n, w;
     n = tokenize_console(order);
     neworder = "";
     for(i = 0; i < n; ++i)
     {
         w = stof(argv(i));
         if(w == floor(w))
         {
             if(w >= from && w <= to)
                 neworder = strcat(neworder, ftos(w), " ");
             else
             {
                 w -= subtract;
                 if(w >= from && w <= to)
                     neworder = strcat(neworder, ftos(w), " ");
             }
         }
     }
     if(complete)
     {
         n = tokenize_console(neworder);
         for(w = to; w >= from; --w)
         {
             for(i = 0; i < n; ++i)
                 if(stof(argv(i)) == w)
                     break;
             if(i == n) // not found
                 neworder = strcat(neworder, ftos(w), " ");
         }
     }
     return substring(neworder, 0, strlen(neworder) - 1);
 }
typedef float (string s, vector size)
typedef float (string s)
typedef float (entity a, entity b, entity pass)
float float2range01 (float f)
continuous function mapping all reals into 0..1
Definition at line 163 of file math.qh.
References float2range11().
 {
     return 0.5 + 0.5 * float2range11(f);
 }
float float2range11 (float f)
continuous function mapping all reals into -1..1
Definition at line 157 of file math.qh.
References fabs().
Referenced by float2range01(), and GetCurrentFov().
 {
     return f / (fabs(f) + 1);
 }
string format_time (float seconds)
Definition at line 27 of file string.qh.
References floor().
 {
     seconds = floor(seconds + 0.5);
     float days = floor(seconds / 864000);
     seconds -= days * 864000;
     float hours = floor(seconds / 36000);
     seconds -= hours * 36000;
     float minutes = floor(seconds / 600);
     seconds -= minutes * 600;
     if (days > 0) return sprintf(_("%d days, %02d:%02d:%02d"), days, hours, minutes, seconds);
     else return sprintf(_("%02d:%02d:%02d"), hours, minutes, seconds);
 }
string fstrunzone (string s)
unzone the string, and return it as tempstring.
Safe to be called on string_null
Definition at line 111 of file string.qh.
References s, strcat(), and strunzone().
 {
     if (!s) return s;
     string sc = strcat(s, "");
     strunzone(s);
     return sc;
 }
string ftos_decimals (float number, float decimals)
Referenced by dialog_hudpanel_common_notoggle(), DrawDomItem(), HUD_Physics(), HUD_Score(), and MakeRaceString().
void get_mi_min_max (float mode)
Definition at line 449 of file util.qc.
References MapInfo_Get_ByName(), MapInfo_Map_maxs, MapInfo_Map_mins, mapname, mi_max, mi_min, mi_shortname, MOVE_WORLDONLY, strcasecmp, strlen(), strunzone(), strzone(), substring(), trace_endpos, trace_startsolid, vector(), and world.
Referenced by get_mi_min_max_texcoords(), and InitGameplayMode().
 {
     vector mi, ma;
     if(mi_shortname)
         strunzone(mi_shortname);
     mi_shortname = mapname;
     if(!strcasecmp(substring(mi_shortname, 0, 5), "maps/"))
         mi_shortname = substring(mi_shortname, 5, strlen(mi_shortname) - 5);
     if(!strcasecmp(substring(mi_shortname, strlen(mi_shortname) - 4, 4), ".bsp"))
         mi_shortname = substring(mi_shortname, 0, strlen(mi_shortname) - 4);
     mi_shortname = strzone(mi_shortname);
 #ifdef CSQC
     mi = world.mins;
     ma = world.maxs;
 #else
     mi = world.absmin;
     ma = world.absmax;
 #endif
     mi_min = mi;
     mi_max = ma;
     MapInfo_Get_ByName(mi_shortname, 0, 0);
     if(MapInfo_Map_mins.x < MapInfo_Map_maxs.x)
     {
         mi_min = MapInfo_Map_mins;
         mi_max = MapInfo_Map_maxs;
     }
     else
     {
         // not specified
         if(mode)
         {
             // be clever
             tracebox('1 0 0' * mi.x,
                      '0 1 0' * mi.y + '0 0 1' * mi.z,
                      '0 1 0' * ma.y + '0 0 1' * ma.z,
                      '1 0 0' * ma.x,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_min.x = trace_endpos.x;
             tracebox('0 1 0' * mi.y,
                      '1 0 0' * mi.x + '0 0 1' * mi.z,
                      '1 0 0' * ma.x + '0 0 1' * ma.z,
                      '0 1 0' * ma.y,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_min.y = trace_endpos.y;
             tracebox('0 0 1' * mi.z,
                      '1 0 0' * mi.x + '0 1 0' * mi.y,
                      '1 0 0' * ma.x + '0 1 0' * ma.y,
                      '0 0 1' * ma.z,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_min.z = trace_endpos.z;
             tracebox('1 0 0' * ma.x,
                      '0 1 0' * mi.y + '0 0 1' * mi.z,
                      '0 1 0' * ma.y + '0 0 1' * ma.z,
                      '1 0 0' * mi.x,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_max.x = trace_endpos.x;
             tracebox('0 1 0' * ma.y,
                      '1 0 0' * mi.x + '0 0 1' * mi.z,
                      '1 0 0' * ma.x + '0 0 1' * ma.z,
                      '0 1 0' * mi.y,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_max.y = trace_endpos.y;
             tracebox('0 0 1' * ma.z,
                      '1 0 0' * mi.x + '0 1 0' * mi.y,
                      '1 0 0' * ma.x + '0 1 0' * ma.y,
                      '0 0 1' * mi.z,
                      MOVE_WORLDONLY,
                      world);
             if(!trace_startsolid)
                 mi_max.z = trace_endpos.z;
         }
     }
 }
void get_mi_min_max_texcoords (float mode)
Definition at line 541 of file util.qc.
References get_mi_min_max(), mi_max, mi_min, mi_picmax, mi_picmin, mi_pictexcoord0, mi_pictexcoord1, mi_pictexcoord2, mi_pictexcoord3, and vector().
Referenced by CSQC_Init(), and RadarMap_Think().
 {
     vector extend;
     get_mi_min_max(mode);
     mi_picmin = mi_min;
     mi_picmax = mi_max;
     // extend mi_picmax to get a square aspect ratio
     // center the map in that area
     extend = mi_picmax - mi_picmin;
     if(extend.y > extend.x)
     {
         mi_picmin.x -= (extend.y - extend.x) * 0.5;
         mi_picmax.x += (extend.y - extend.x) * 0.5;
     }
     else
     {
         mi_picmin.y -= (extend.x - extend.y) * 0.5;
         mi_picmax.y += (extend.x - extend.y) * 0.5;
     }
     // add another some percent
     extend = (mi_picmax - mi_picmin) * (1 / 64.0);
     mi_picmin -= extend;
     mi_picmax += extend;
     // calculate the texcoords
     mi_pictexcoord0 = mi_pictexcoord1 = mi_pictexcoord2 = mi_pictexcoord3 = '0 0 0';
     // first the two corners of the origin
     mi_pictexcoord0_x = (mi_min.x - mi_picmin.x) / (mi_picmax.x - mi_picmin.x);
     mi_pictexcoord0_y = (mi_min.y - mi_picmin.y) / (mi_picmax.y - mi_picmin.y);
     mi_pictexcoord2_x = (mi_max.x - mi_picmin.x) / (mi_picmax.x - mi_picmin.x);
     mi_pictexcoord2_y = (mi_max.y - mi_picmin.y) / (mi_picmax.y - mi_picmin.y);
     // then the other corners
     mi_pictexcoord1_x = mi_pictexcoord0_x;
     mi_pictexcoord1_y = mi_pictexcoord2_y;
     mi_pictexcoord3_x = mi_pictexcoord2_x;
     mi_pictexcoord3_y = mi_pictexcoord0_y;
 }
string get_model_datafilename (string mod, float skn, string fil)
Definition at line 1197 of file util.qc.
References ftos(), and strcat().
Referenced by get_model_parameters().
 {
     if(m)
         m = strcat(m, "_");
     else
         m = "models/player/*_";
     if(sk >= 0)
         m = strcat(m, ftos(sk));
     else
         m = strcat(m, "*");
     return strcat(m, ".", fil);
 }
float get_model_parameters (string mod, float skn)
Definition at line 1210 of file util.qc.
References car(), cdr(), fclose(), fgets(), FILE_READ, fopen(), ftos(), get_model_datafilename(), get_model_parameters_age, get_model_parameters_bone_aim, get_model_parameters_bone_aimweight, get_model_parameters_bone_upperbody, get_model_parameters_bone_weapon, get_model_parameters_desc, get_model_parameters_description, get_model_parameters_fixbone, get_model_parameters_modelname, get_model_parameters_modelskin, get_model_parameters_name, get_model_parameters_sex, get_model_parameters_species, get_model_parameters_weight, MAX_AIM_BONES, MUTATOR_CALLHOOK, s, SPECIES_ALIEN, SPECIES_ANIMAL, SPECIES_HUMAN, SPECIES_RESERVED, SPECIES_ROBOT_RUSTY, SPECIES_ROBOT_SHINY, SPECIES_ROBOT_SOLID, stof(), strcat(), string_null, and substring().
Referenced by player_getspecies(), and skeleton_loadinfo().
 {
     get_model_parameters_modelname = string_null;
     get_model_parameters_modelskin = -1;
     get_model_parameters_name = string_null;
     get_model_parameters_species = -1;
     get_model_parameters_sex = string_null;
     get_model_parameters_weight = -1;
     get_model_parameters_age = -1;
     get_model_parameters_desc = string_null;
     get_model_parameters_bone_upperbody = string_null;
     get_model_parameters_bone_weapon = string_null;
     for(int i = 0; i < MAX_AIM_BONES; ++i)
     {
         get_model_parameters_bone_aim[i] = string_null;
         get_model_parameters_bone_aimweight[i] = 0;
     }
     get_model_parameters_fixbone = 0;
 #ifndef MENUQC
     MUTATOR_CALLHOOK(ClearModelParams);
 #endif
     if (!m)
         return 1;
     if(substring(m, -9, 5) == "_lod1" || substring(m, -9, 5) == "_lod2")
         m = strcat(substring(m, 0, -10), substring(m, -4, -1));
     if(sk < 0)
     {
         if(substring(m, -4, -1) != ".txt")
             return 0;
         if(substring(m, -6, 1) != "_")
             return 0;
         sk = stof(substring(m, -5, 1));
         m = substring(m, 0, -7);
     }
     string fn = get_model_datafilename(m, sk, "txt");
     int fh = fopen(fn, FILE_READ);
     if(fh < 0)
     {
         sk = 0;
         fn = get_model_datafilename(m, sk, "txt");
         fh = fopen(fn, FILE_READ);
         if(fh < 0)
             return 0;
     }
     get_model_parameters_modelname = m;
     get_model_parameters_modelskin = sk;
     string s, c;
     while((s = fgets(fh)))
     {
         if(s == "")
             break; // next lines will be description
         c = car(s);
         s = cdr(s);
         if(c == "name")
             get_model_parameters_name = s;
         if(c == "species")
             switch(s)
             {
                 case "human":       get_model_parameters_species = SPECIES_HUMAN;       break;
                 case "alien":       get_model_parameters_species = SPECIES_ALIEN;       break;
                 case "robot_shiny": get_model_parameters_species = SPECIES_ROBOT_SHINY; break;
                 case "robot_rusty": get_model_parameters_species = SPECIES_ROBOT_RUSTY; break;
                 case "robot_solid": get_model_parameters_species = SPECIES_ROBOT_SOLID; break;
                 case "animal":      get_model_parameters_species = SPECIES_ANIMAL;      break;
                 case "reserved":    get_model_parameters_species = SPECIES_RESERVED;    break;
             }
         if(c == "sex")
             get_model_parameters_sex = s;
         if(c == "weight")
             get_model_parameters_weight = stof(s);
         if(c == "age")
             get_model_parameters_age = stof(s);
         if(c == "description")
             get_model_parameters_description = s;
         if(c == "bone_upperbody")
             get_model_parameters_bone_upperbody = s;
         if(c == "bone_weapon")
             get_model_parameters_bone_weapon = s;
     #ifndef MENUQC
         MUTATOR_CALLHOOK(GetModelParams, c, s);
     #endif
         for(int i = 0; i < MAX_AIM_BONES; ++i)
             if(c == strcat("bone_aim", ftos(i)))
             {
                 get_model_parameters_bone_aimweight[i] = stof(car(s));
                 get_model_parameters_bone_aim[i] = cdr(s);
             }
         if(c == "fixbone")
             get_model_parameters_fixbone = stof(s);
     }
     while((s = fgets(fh)))
     {
         if(get_model_parameters_desc)
             get_model_parameters_desc = strcat(get_model_parameters_desc, "\n");
         if(s != "")
             get_model_parameters_desc = strcat(get_model_parameters_desc, s);
     }
     fclose(fh);
     return 1;
 }
vector get_shotvelocity (vector myvel, vector mydir, float spd, float newton_style, float mi, float ma)
Definition at line 1042 of file util.qc.
References bound(), solve_quadratic(), and vector().
Referenced by W_CalculateProjectileVelocity().
 {
     if(!newton_style)
         return spd * mydir;
     if(newton_style == 2)
     {
         // true Newtonian projectiles with automatic aim adjustment
         //
         // solve: |outspeed * mydir - myvel| = spd
         // outspeed^2 - 2 * outspeed * (mydir * myvel) + myvel^2 - spd^2 = 0
         // outspeed = (mydir * myvel) +- sqrt((mydir * myvel)^2 - myvel^2 + spd^2)
         // PLUS SIGN!
         // not defined?
         // then...
         // myvel^2 - (mydir * myvel)^2 > spd^2
         // velocity without mydir component > spd
         // fire at smallest possible spd that works?
         // |(mydir * myvel) * myvel - myvel| = spd
         vector solution = solve_quadratic(1, -2 * (mydir * myvel), myvel * myvel - spd * spd);
         float outspeed;
         if(solution.z)
             outspeed = solution.y; // the larger one
         else
         {
             //outspeed = 0; // slowest possible shot
             outspeed = solution.x; // the real part (that is, the average!)
             //dprint("impossible shot, adjusting\n");
         }
         outspeed = bound(spd * mi, outspeed, spd * ma);
         return mydir * outspeed;
     }
     // real Newtonian
     return myvel + spd * mydir;
 }
string getcurrentmod ()
Definition at line 1151 of file util.qc.
References argv(), cvar_string(), and tokenize_console.
Referenced by resolvemod().
 {
     float n;
     string m;
     m = cvar_string("fs_gamedir");
     n = tokenize_console(m);
     if(n == 0)
         return "data";
     else
         return argv(n - 1);
 }
string getWrappedLine (float w, vector size, textLengthUpToWidth_widthFunction_t tw)
Definition at line 825 of file util.qc.
References find_last_color_code(), getWrappedLine_remaining, s, strcat(), string_null, strlen(), substring(), and textLengthUpToWidth().
Referenced by GameTypeVote_DrawGameTypeItem(), HUD_CenterPrint(), and m_tooltip().
 {
     float cantake;
     float take;
     string s;
     s = getWrappedLine_remaining;
     if(w <= 0)
     {
         getWrappedLine_remaining = string_null;
         return s; // the line has no size ANYWAY, nothing would be displayed.
     }
     cantake = textLengthUpToWidth(s, w, theFontSize, tw);
     if(cantake > 0 && cantake < strlen(s))
     {
         take = cantake - 1;
         while(take > 0 && substring(s, take, 1) != " ")
             --take;
         if(take == 0)
         {
             getWrappedLine_remaining = substring(s, cantake, strlen(s) - cantake);
             if(getWrappedLine_remaining == "")
                 getWrappedLine_remaining = string_null;
             else if (tw("^7", theFontSize) == 0)
                 getWrappedLine_remaining = strcat(find_last_color_code(substring(s, 0, cantake)), getWrappedLine_remaining);
             return substring(s, 0, cantake);
         }
         else
         {
             getWrappedLine_remaining = substring(s, take + 1, strlen(s) - take);
             if(getWrappedLine_remaining == "")
                 getWrappedLine_remaining = string_null;
             else if (tw("^7", theFontSize) == 0)
                 getWrappedLine_remaining = strcat(find_last_color_code(substring(s, 0, take)), getWrappedLine_remaining);
             return substring(s, 0, take);
         }
     }
     else
     {
         getWrappedLine_remaining = string_null;
         return s;
     }
 }
string getWrappedLineLen (float w, textLengthUpToLength_lenFunction_t tw)
Definition at line 871 of file util.qc.
References find_last_color_code(), getWrappedLine_remaining, s, strcat(), string_null, strlen(), substring(), and textLengthUpToLength().
Referenced by Say().
 {
     float cantake;
     float take;
     string s;
     s = getWrappedLine_remaining;
     if(w <= 0)
     {
         getWrappedLine_remaining = string_null;
         return s; // the line has no size ANYWAY, nothing would be displayed.
     }
     cantake = textLengthUpToLength(s, w, tw);
     if(cantake > 0 && cantake < strlen(s))
     {
         take = cantake - 1;
         while(take > 0 && substring(s, take, 1) != " ")
             --take;
         if(take == 0)
         {
             getWrappedLine_remaining = substring(s, cantake, strlen(s) - cantake);
             if(getWrappedLine_remaining == "")
                 getWrappedLine_remaining = string_null;
             else if (tw("^7") == 0)
                 getWrappedLine_remaining = strcat(find_last_color_code(substring(s, 0, cantake)), getWrappedLine_remaining);
             return substring(s, 0, cantake);
         }
         else
         {
             getWrappedLine_remaining = substring(s, take + 1, strlen(s) - take);
             if(getWrappedLine_remaining == "")
                 getWrappedLine_remaining = string_null;
             else if (tw("^7") == 0)
                 getWrappedLine_remaining = strcat(find_last_color_code(substring(s, 0, take)), getWrappedLine_remaining);
             return substring(s, 0, take);
         }
     }
     else
     {
         getWrappedLine_remaining = string_null;
         return s;
     }
 }
float gsl_ran_gaussian (float sigma)
Definition at line 72 of file random.qc.
References cos(), gsl_ran_gaussian_lastvalue, gsl_ran_gaussian_lastvalue_set, log(), M_PI, random(), sin(), and sqrt().
Referenced by W_CalculateSpread().
 {
     if (gsl_ran_gaussian_lastvalue_set)
     {
         gsl_ran_gaussian_lastvalue_set = 0;
         return sigma * gsl_ran_gaussian_lastvalue;
     }
     else
     {
         float a = random() * 2 * M_PI;
         float b = sqrt(-2 * log(random()));
         gsl_ran_gaussian_lastvalue = cos(a) * b;
         gsl_ran_gaussian_lastvalue_set = 1;
         return sigma * sin(a) * b;
     }
 }
vector healtharmor_applydamage (float a, float armorblock, int deathtype, float damage)
Definition at line 1139 of file util.qc.
References bound(), DEATH_IS, and vector().
Referenced by Damage(), Monster_Damage(), PlayerCorpseDamage(), and PlayerDamage().
 {
     vector v;
     if (DEATH_IS(deathtype, DEATH_DROWN))  // Why should armor help here...
         armorblock = 0;
     v.y = bound(0, damage * armorblock, a); // save
     v.x = bound(0, damage - v.y, damage); // take
     v.z = 0;
     return v;
 }
vector healtharmor_maxdamage (float h, float a, float armorblock, int deathtype)
Definition at line 1115 of file util.qc.
References DEATH_IS, and vector().
Referenced by HUD_HealthArmor(), and PlayerPostThink().
 {
     // NOTE: we'll always choose the SMALLER value...
     float healthdamage, armordamage, armorideal;
     if (DEATH_IS(deathtype, DEATH_DROWN))  // Why should armor help here...
         armorblock = 0;
     vector v;
     healthdamage = (h - 1) / (1 - armorblock); // damage we can take if we could use more health
     armordamage = a + (h - 1); // damage we can take if we could use more armor
     armorideal = healthdamage * armorblock;
     v.y = armorideal;
     if(armordamage < healthdamage)
     {
         v.x = armordamage;
         v.z = 1;
     }
     else
     {
         v.x = healthdamage;
         v.z = 0;
     }
     return v;
 }
vector hsl_to_rgb (vector hsl)
Definition at line 154 of file color.qh.
References hue_mi_ma_to_rgb().
Referenced by GenericCommand().
 {
     float mi, ma, maminusmi;
     if (hsl.z <= 0.5) maminusmi = hsl.y * 2 * hsl.z;
     else maminusmi = hsl.y * (2 - 2 * hsl.z);
     // hsl_z     = 0.5 * mi + 0.5 * ma
     // maminusmi =     - mi +       ma
     mi = hsl.z - 0.5 * maminusmi;
     ma = hsl.z + 0.5 * maminusmi;
     return hue_mi_ma_to_rgb(hsl.x, mi, ma);
 }
vector hsv_to_rgb (vector hsv)
Definition at line 130 of file color.qh.
References hue_mi_ma_to_rgb().
 {
     return hue_mi_ma_to_rgb(hsv.x, hsv.z * (1 - hsv.y), hsv.z);
 }
float isGametypeInFilter (float gt, float tp, float ts, string pattern)
Definition at line 933 of file util.qc.
References MapInfo_Type_ToString(), strcat(), string_null, strlen(), strstrofs, and substring().
Referenced by Cmd_HUD_SetFields(), and SV_OnEntityPreSpawnFunction().
 {
     string subpattern, subpattern2, subpattern3, subpattern4;
     subpattern = strcat(",", MapInfo_Type_ToString(gt), ",");
     if(tp)
         subpattern2 = ",teams,";
     else
         subpattern2 = ",noteams,";
     if(ts)
         subpattern3 = ",teamspawns,";
     else
         subpattern3 = ",noteamspawns,";
     if(gt == MAPINFO_TYPE_RACE || gt == MAPINFO_TYPE_CTS)
         subpattern4 = ",race,";
     else
         subpattern4 = string_null;
     if(substring(pattern, 0, 1) == "-")
     {
         pattern = substring(pattern, 1, strlen(pattern) - 1);
         if(strstrofs(strcat(",", pattern, ","), subpattern, 0) >= 0)
             return 0;
         if(strstrofs(strcat(",", pattern, ","), subpattern2, 0) >= 0)
             return 0;
         if(strstrofs(strcat(",", pattern, ","), subpattern3, 0) >= 0)
             return 0;
         if(subpattern4 && strstrofs(strcat(",", pattern, ","), subpattern4, 0) >= 0)
             return 0;
     }
     else
     {
         if(substring(pattern, 0, 1) == "+")
             pattern = substring(pattern, 1, strlen(pattern) - 1);
         if(strstrofs(strcat(",", pattern, ","), subpattern, 0) < 0)
         if(strstrofs(strcat(",", pattern, ","), subpattern2, 0) < 0)
         if(strstrofs(strcat(",", pattern, ","), subpattern3, 0) < 0)
         {
             if (!subpattern4)
                 return 0;
             if(strstrofs(strcat(",", pattern, ","), subpattern4, 0) < 0)
                 return 0;
         }
     }
     return 1;
 }
float log2of (float x)
Definition at line 198 of file math.qh.
 {
     // NOTE: generated code
     if (x > 2048)
         if (x > 131072)
             if (x > 1048576)
                 if (x > 4194304) return 23;
                 else
                     if (x > 2097152) return 22;
                     else return 21;
             else
                 if (x > 524288) return 20;
                 else
                     if (x > 262144) return 19;
                     else return 18;
         else
             if (x > 16384)
                 if (x > 65536) return 17;
                 else
                     if (x > 32768) return 16;
                     else return 15;
             else
                 if (x > 8192) return 14;
                 else
                     if (x > 4096) return 13;
                     else return 12;
     else
         if (x > 32)
             if (x > 256)
                 if (x > 1024) return 11;
                 else
                     if (x > 512) return 10;
                     else return 9;
             else
                 if (x > 128) return 8;
                 else
                     if (x > 64) return 7;
                     else return 6;
         else
             if (x > 4)
                 if (x > 16) return 5;
                 else
                     if (x > 8) return 4;
                     else return 3;
             else
                 if (x > 2) return 2;
                 else
                     if (x > 1) return 1;
                     else return 0;
 }
string MakeConsoleSafe (string input)
escape the string to make it safe for consoles
Definition at line 21 of file cvar.qh.
Referenced by cvar_describe(), GameCommand_adminmsg(), Local_Notification(), and Local_Notification_sprintf().
 {
     input = strreplace("\n", "", input);
     input = strreplace("\\", "\\\\", input);
     input = strreplace("$", "$$", input);
     input = strreplace("\"", "\\\"", input);
     return input;
 }
string mapPriorityList (string order, string(string) mapfunc)
Definition at line 410 of file util.qc.
References argv(), strcat(), strlen(), substring(), and tokenize_console.
Referenced by W_NameWeaponOrder(), and W_NumberWeaponOrder().
 {
     string neworder;
     float i, n;
     n = tokenize_console(order);
     neworder = "";
     for(i = 0; i < n; ++i)
         neworder = strcat(neworder, mapfunc(argv(i)), " ");
     return substring(neworder, 0, strlen(neworder) - 1);
 }
float matchacl (string acl, string str)
Definition at line 1163 of file util.qc.
References car(), cdr(), s, strlen(), and substring().
Referenced by _MapInfo_Parse_Settemp().
 {
     string t, s;
     float r, d;
     r = 0;
     while(acl)
     {
         t = car(acl); acl = cdr(acl);
         d = 1;
         if(substring(t, 0, 1) == "-")
         {
             d = -1;
             t = substring(t, 1, strlen(t) - 1);
         }
         else if(substring(t, 0, 1) == "+")
             t = substring(t, 1, strlen(t) - 1);
         if(substring(t, -1, 1) == "*")
         {
             t = substring(t, 0, strlen(t) - 1);
             s = substring(str, 0, strlen(t));
         }
         else
             s = str;
         if(s == t)
         {
             r = d;
         }
     }
     return r;
 }
float median (float a, float b, float c)
Definition at line 168 of file math.qh.
References bound().
Referenced by almost_in_bounds().
 {
     return (a < c) ? bound(a, b, c) : bound(c, b, a);
 }
string mmsss (float t)
Definition at line 40 of file string.qh.
References floor(), ftos(), s, strcat(), and substring().
 {
     tenths = floor(tenths + 0.5);
     float minutes = floor(tenths / 600);
     tenths -= minutes * 600;
     string s = ftos(1000 + tenths);
     return strcat(ftos(minutes), ":", substring(s, 1, 2), ".", substring(s, 3, 1));
 }
string mmssss (float t)
Definition at line 49 of file string.qh.
References floor(), ftos(), s, strcat(), and substring().
 {
     hundredths = floor(hundredths + 0.5);
     float minutes = floor(hundredths / 6000);
     hundredths -= minutes * 6000;
     string s = ftos(10000 + hundredths);
     return strcat(ftos(minutes), ":", substring(s, 1, 2), ".", substring(s, 3, 2));
 }
int Mod_Q1BSP_NativeContentsFromSuperContents (int supercontents)
Definition at line 1624 of file util.qc.
References CONTENT_EMPTY, CONTENT_LAVA, CONTENT_SKY, CONTENT_SLIME, CONTENT_SOLID, CONTENT_WATER, DPCONTENTS_BODY, DPCONTENTS_LAVA, DPCONTENTS_SKY, DPCONTENTS_SLIME, DPCONTENTS_SOLID, and DPCONTENTS_WATER.
 {
     if(supercontents & (DPCONTENTS_SOLID | DPCONTENTS_BODY))
         return CONTENT_SOLID;
     if(supercontents & DPCONTENTS_SKY)
         return CONTENT_SKY;
     if(supercontents & DPCONTENTS_LAVA)
         return CONTENT_LAVA;
     if(supercontents & DPCONTENTS_SLIME)
         return CONTENT_SLIME;
     if(supercontents & DPCONTENTS_WATER)
         return CONTENT_WATER;
     return CONTENT_EMPTY;
 }
int Mod_Q1BSP_SuperContentsFromNativeContents (int nativecontents)
Definition at line 1604 of file util.qc.
References CONTENT_EMPTY, CONTENT_LAVA, CONTENT_SKY, CONTENT_SLIME, CONTENT_SOLID, CONTENT_WATER, DPCONTENTS_LAVA, DPCONTENTS_NODROP, DPCONTENTS_OPAQUE, DPCONTENTS_SKY, DPCONTENTS_SLIME, DPCONTENTS_SOLID, and DPCONTENTS_WATER.
Referenced by _Movetype_CheckWater().
 {
     switch(nativecontents)
     {
         case CONTENT_EMPTY:
             return 0;
         case CONTENT_SOLID:
             return DPCONTENTS_SOLID | DPCONTENTS_OPAQUE;
         case CONTENT_WATER:
             return DPCONTENTS_WATER;
         case CONTENT_SLIME:
             return DPCONTENTS_SLIME;
         case CONTENT_LAVA:
             return DPCONTENTS_LAVA | DPCONTENTS_NODROP;
         case CONTENT_SKY:
             return DPCONTENTS_SKY | DPCONTENTS_NODROP | DPCONTENTS_OPAQUE; // to match behaviour of Q3 maps, let sky count as opaque
     }
     return 0;
 }
vector NearestPointOnBox (entity box, vector org)
Definition at line 124 of file vector.qh.
References bound(), and vector().
Referenced by Ent_Wall_Draw(), and LOD_customize().
     {
         vector m1 = box.mins + box.origin;
         vector m2 = box.maxs + box.origin;
         vector ret;
         ret.x = bound(m1.x, org.x, m2.x);
         ret.y = bound(m1.y, org.y, m2.y);
         ret.z = bound(m1.z, org.z, m2.z);
         return ret;
     }
float power2of (float e)
Definition at line 193 of file math.qh.
References pow().
Referenced by _WepSet_FromWeapon(), and bot_cmd_keypress_handler().
 {
     return pow(2, e);
 }
void queue_to_execute_next_frame (string s)
Definition at line 1413 of file util.qc.
References strcat(), strunzone(), and strzone().
Referenced by GenericCommand_nextframe().
 {
     if(to_execute_next_frame)
     {
         s = strcat(s, "\n", to_execute_next_frame);
         strunzone(to_execute_next_frame);
     }
     to_execute_next_frame = strzone(s);
 }
vector real_origin (entity ent)
Definition at line 25 of file util.qc.
References entity(), and vector().
Referenced by vehicles_damage().
 {
     entity e;
     vector v = ((ent.absmin + ent.absmax) * 0.5);
     e = ent.tag_entity;
     while(e)
     {
         v = v + ((e.absmin + e.absmax) * 0.5);
         e = e.tag_entity;
     }
     return v;
 }
string rgb_to_hexcolor (vector rgb)
Definition at line 169 of file color.qh.
References DEC_TO_HEXDIGIT, floor(), and strcat().
Referenced by GenericCommand().
 {
     return strcat(
         "^x",
         DEC_TO_HEXDIGIT(floor(rgb.x * 15 + 0.5)),
         DEC_TO_HEXDIGIT(floor(rgb.y * 15 + 0.5)),
         DEC_TO_HEXDIGIT(floor(rgb.z * 15 + 0.5))
                  );
 }
vector rgb_to_hsl (vector rgb)
Definition at line 135 of file color.qh.
References max(), min(), rgb_mi_ma_to_hue(), and vector().
 {
     float mi, ma;
     vector hsl;
     mi = min(rgb.x, rgb.y, rgb.z);
     ma = max(rgb.x, rgb.y, rgb.z);
     hsl.x = rgb_mi_ma_to_hue(rgb, mi, ma);
     hsl.z = 0.5 * (mi + ma);
     if (mi == ma) hsl.y = 0;
     else if (hsl.z <= 0.5) hsl.y = (ma - mi) / (2 * hsl.z);
     else  // if(hsl_z > 0.5)
         hsl.y = (ma - mi) / (2 - 2 * hsl.z);
     return hsl;
 }
vector rgb_to_hsv (vector rgb)
Definition at line 113 of file color.qh.
References max(), min(), rgb_mi_ma_to_hue(), and vector().
 {
     float mi, ma;
     vector hsv;
     mi = min(rgb.x, rgb.y, rgb.z);
     ma = max(rgb.x, rgb.y, rgb.z);
     hsv.x = rgb_mi_ma_to_hue(rgb, mi, ma);
     hsv.z = ma;
     if (ma == 0) hsv.y = 0;
     else hsv.y = 1 - mi / ma;
     return hsv;
 }
string ScoreString (float vflags, float value)
string shufflewords (string str)
Definition at line 172 of file string.qh.
References _shufflewords_str, _shufflewords_swapfunc(), NULL, shuffle(), string_null, and tokenizebyseparator.
Referenced by GenericCommand_maplist(), and ShuffleMaplist().
 {
     _shufflewords_str = str;
     int n = tokenizebyseparator(str, " ");
     shuffle(n, _shufflewords_swapfunc, NULL);
     str = _shufflewords_str;
     _shufflewords_str = string_null;
     return str;
 }
void Shutdown ()
Definition at line 132 of file main.qc.
References __init_dedicated_server_shutdown(), autocvar_chase_active, autocvar_cl_db_saveasdump, autocvar_developer, autocvar_sessionid, autocvar_sv_db_saveasdump, Ban_SaveBans(), binddb, bot_endgame(), calledhooks, camera_active, chase_active_backup, cheatcount_total, CheatShutdown(), ClientProgsDB, cvar_set(), db_close(), db_dump(), db_save(), deactivate_minigame(), FOREACH_ENTITY_ORDERED, ftos(), gameover, HOOK_END, HOOK_START, HUD_MinigameMenu_Close(), isdemo(), LAMBDA, localcmd, LOG_INFO, LOG_TRACE(), m_hide(), MapInfo_Shutdown(), players, ServerProgsDB, strcat(), teams, tempdb, TemporaryDB, WarpZone_Shutdown(), WeaponStats_Shutdown(), and world_initialized.
 {
     WarpZone_Shutdown();
     remove(teams);
     remove(players);
     db_close(binddb);
     db_close(tempdb);
     if(autocvar_cl_db_saveasdump)
         db_dump(ClientProgsDB, "client.db");
     else
         db_save(ClientProgsDB, "client.db");
     db_close(ClientProgsDB);
     if(camera_active)
         cvar_set("chase_active",ftos(chase_active_backup));
     // unset the event chasecam's chase_active
     if(autocvar_chase_active < 0)
         cvar_set("chase_active", "0");
     if (!isdemo())
     {
         if (!(calledhooks & HOOK_START))
             localcmd("\n_cl_hook_gamestart nop\n");
         if (!(calledhooks & HOOK_END))
             localcmd("\ncl_hook_gameend\n");
     }
     deactivate_minigame();
     HUD_MinigameMenu_Close();
 }
void Skeleton_SetBones (entity e)
Definition at line 1389 of file util.qc.
 {
     // set skeleton_bones to the total number of bones on the model
     if(e.skeleton_bones_index == e.modelindex)
         return; // same model, nothing to update
     float skelindex;
     skelindex = skel_create(e.modelindex);
     e.skeleton_bones = skel_get_numbones(skelindex);
     skel_delete(skelindex);
     e.skeleton_bones_index = e.modelindex;
 }
vector solve_quadratic (float a, float b, float c)
ax^2 + bx + c = 0
Definition at line 250 of file math.qh.
References sqrt(), and vector().
Referenced by get_shotvelocity(), solve_shotdirection(), StartFrame(), and trigger_push_calculatevelocity().
 {
     vector v;
     float D;
     v = '0 0 0';
     if (a == 0)
     {
         if (b != 0)
         {
             v.x = v.y = -c / b;
             v.z = 1;
         }
         else
         {
             if (c == 0)
             {
                 // actually, every number solves the equation!
                 v.z = 1;
             }
         }
     }
     else
     {
         D = b * b - 4 * a * c;
         if (D >= 0)
         {
             D = sqrt(D);
             if (a > 0)  // put the smaller solution first
             {
                 v.x = ((-b) - D) / (2 * a);
                 v.y = ((-b) + D) / (2 * a);
             }
             else
             {
                 v.x = (-b + D) / (2 * a);
                 v.y = (-b - D) / (2 * a);
             }
             v.z = 1;
         }
         else
         {
             // complex solutions!
             D = sqrt(-D);
             v.x = -b / (2 * a);
             if (a > 0) v.y =  D / (2 * a);
             else v.y = -D / (2 * a);
             v.z = 0;
         }
     }
     return v;
 }
vector solve_shotdirection (vector myorg, vector myvel, vector eorg, vector evel, float spd, float newton_style)
Definition at line 979 of file util.qc.
References normalize(), solve_quadratic(), and vector().
 {
     vector ret;
     // make origin and speed relative
     eorg -= myorg;
     if(newton_style)
         evel -= myvel;
     // now solve for ret, ret normalized:
     //   eorg + t * evel == t * ret * spd
     // or, rather, solve for t:
     //   |eorg + t * evel| == t * spd
     //   eorg^2 + t^2 * evel^2 + 2 * t * (eorg * evel) == t^2 * spd^2
     //   t^2 * (evel^2 - spd^2) + t * (2 * (eorg * evel)) + eorg^2 == 0
     vector solution = solve_quadratic(evel * evel - spd * spd, 2 * (eorg * evel), eorg * eorg);
     // p = 2 * (eorg * evel) / (evel * evel - spd * spd)
     // q = (eorg * eorg) / (evel * evel - spd * spd)
     if(!solution.z) // no real solution
     {
         // happens if D < 0
         // (eorg * evel)^2 < (evel^2 - spd^2) * eorg^2
         // (eorg * evel)^2 / eorg^2 < evel^2 - spd^2
         // spd^2 < ((evel^2 * eorg^2) - (eorg * evel)^2) / eorg^2
         // spd^2 < evel^2 * (1 - cos^2 angle(evel, eorg))
         // spd^2 < evel^2 * sin^2 angle(evel, eorg)
         // spd < |evel| * sin angle(evel, eorg)
         return '0 0 0';
     }
     else if(solution.x > 0)
     {
         // both solutions > 0: take the smaller one
         // happens if p < 0 and q > 0
         ret = normalize(eorg + solution.x * evel);
     }
     else if(solution.y > 0)
     {
         // one solution > 0: take the larger one
         // happens if q < 0 or q == 0 and p < 0
         ret = normalize(eorg + solution.y * evel);
     }
     else
     {
         // no solution > 0: reject
         // happens if p > 0 and q >= 0
         // 2 * (eorg * evel) / (evel * evel - spd * spd) > 0
         // (eorg * eorg) / (evel * evel - spd * spd) >= 0
         //
         // |evel| >= spd
         // eorg * evel > 0
         //
         // "Enemy is moving away from me at more than spd"
         return '0 0 0';
     }
     // NOTE: we always got a solution if spd > |evel|
     if(newton_style == 2)
         ret = normalize(ret * spd + myvel);
     return ret;
 }
string strtolower (string s)
Referenced by bd_editor_place(), bd_move(), CheckPlayerModel(), ClientCommand_physics(), Cmd_HUD_SetFields(), CommonCommand_editmob(), CommonCommand_macro_command(), CommonCommand_macro_usage(), CSQC_ConsoleCommand(), GameCommand(), GameCommand_macro_command(), GameCommand_macro_usage(), GenericCommand_macro_command(), GenericCommand_macro_usage(), HUD_Weapons(), InterpretBoolean(), Local_Notification_sprintf(), LocalCommand_macro_command(), LocalCommand_macro_usage(), MapInfo_FilterString(), Process_Notif_Args(), SV_ParseClientCommand(), Team_ColorToTeam(), and VoteCommand_master().
string substring_range (string s, float b, float e)
Definition at line 142 of file string.qh.
References substring().
Referenced by swapwords().
 {
     return substring(s, b, e - b);
 }
string swapInPriorityList (string order, float i, float j)
Definition at line 423 of file util.qc.
References argv(), s, strcat(), strlen(), substring(), and tokenize_console.
 {
     string s;
     float w, n;
     n = tokenize_console(order);
     if(i >= 0 && i < n && j >= 0 && j < n && i != j)
     {
         s = "";
         for(w = 0; w < n; ++w)
         {
             if(w == i)
                 s = strcat(s, argv(j), " ");
             else if(w == j)
                 s = strcat(s, argv(i), " ");
             else
                 s = strcat(s, argv(w), " ");
         }
         return substring(s, 0, strlen(s) - 1);
     }
     return order;
 }
string swapwords (string str, float i, float j)
Definition at line 147 of file string.qh.
References argv_end_index, argv_start_index, s1, s2, strcat(), substring_range(), and tokenizebyseparator.
Referenced by _shufflewords_swapfunc().
 {
     float n;
     string s1, s2, s3, s4, s5;
     float si, ei, sj, ej, s0, en;
     n = tokenizebyseparator(str, " ");  // must match g_maplist processing in ShuffleMaplist and "shuffle"
     si = argv_start_index(i);
     sj = argv_start_index(j);
     ei = argv_end_index(i);
     ej = argv_end_index(j);
     s0 = argv_start_index(0);
     en = argv_end_index(n - 1);
     s1 = substring_range(str, s0, si);
     s2 = substring_range(str, si, ei);
     s3 = substring_range(str, ei, sj);
     s4 = substring_range(str, sj, ej);
     s5 = substring_range(str, ej, en);
     return strcat(s1, s4, s3, s2, s5);
 }
float textLengthUpToLength (string theText, float maxWidth, textLengthUpToLength_lenFunction_t tw)
Definition at line 725 of file util.qc.
References floor(), str2chr, strlen(), and substring().
Referenced by getWrappedLineLen(), and textShortenToLength().
 {
     // STOP.
     // The following function is SLOW.
     // For your safety and for the protection of those around you...
     // DO NOT CALL THIS AT HOME.
     // No really, don't.
     if(w(theText) <= maxWidth)
         return strlen(theText); // yeah!
     // binary search for right place to cut string
     float ch;
     float left, right, middle; // this always works
     left = 0;
     right = strlen(theText); // this always fails
     do
     {
         middle = floor((left + right) / 2);
         if(w(substring(theText, 0, middle)) <= maxWidth)
             left = middle;
         else
             right = middle;
     }
     while(left < right - 1);
     if(w("^7") == 0) // detect color codes support in the width function
     {
         // NOTE: when color codes are involved, this binary search is,
         // mathematically, BROKEN. However, it is obviously guaranteed to
         // terminate, as the range still halves each time - but nevertheless, it is
         // guaranteed that it finds ONE valid cutoff place (where "left" is in
         // range, and "right" is outside).
         // terencehill: the following code detects truncated ^xrgb tags (e.g. ^x or ^x4)
         // and decrease left on the basis of the chars detected of the truncated tag
         // Even if the ^xrgb tag is not complete/correct, left is decreased
         // (sometimes too much but with a correct result)
         // it fixes also ^[0-9]
         while(left >= 1 && substring(theText, left-1, 1) == "^")
             left-=1;
         if (left >= 2 && substring(theText, left-2, 2) == "^x") // ^x/
             left-=2;
         else if (left >= 3 && substring(theText, left-3, 2) == "^x")
             {
                 ch = str2chr(theText, left-1);
                 if( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') ) // ^xr/
                     left-=3;
             }
         else if (left >= 4 && substring(theText, left-4, 2) == "^x")
             {
                 ch = str2chr(theText, left-2);
                 if ( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') )
                 {
                     ch = str2chr(theText, left-1);
                     if ( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') ) // ^xrg/
                         left-=4;
                 }
             }
     }
     return left;
 }
float textLengthUpToWidth (string theText, float maxWidth, vector size, textLengthUpToWidth_widthFunction_t tw)
Definition at line 661 of file util.qc.
References floor(), str2chr, strlen(), and substring().
Referenced by draw_TextLengthUpToWidth(), getWrappedLine(), minigame_getWrappedLine(), and textShortenToWidth().
 {
     // STOP.
     // The following function is SLOW.
     // For your safety and for the protection of those around you...
     // DO NOT CALL THIS AT HOME.
     // No really, don't.
     if(w(theText, theSize) <= maxWidth)
         return strlen(theText); // yeah!
     // binary search for right place to cut string
     float ch;
     float left, right, middle; // this always works
     left = 0;
     right = strlen(theText); // this always fails
     do
     {
         middle = floor((left + right) / 2);
         if(w(substring(theText, 0, middle), theSize) <= maxWidth)
             left = middle;
         else
             right = middle;
     }
     while(left < right - 1);
     if(w("^7", theSize) == 0) // detect color codes support in the width function
     {
         // NOTE: when color codes are involved, this binary search is,
         // mathematically, BROKEN. However, it is obviously guaranteed to
         // terminate, as the range still halves each time - but nevertheless, it is
         // guaranteed that it finds ONE valid cutoff place (where "left" is in
         // range, and "right" is outside).
         // terencehill: the following code detects truncated ^xrgb tags (e.g. ^x or ^x4)
         // and decrease left on the basis of the chars detected of the truncated tag
         // Even if the ^xrgb tag is not complete/correct, left is decreased
         // (sometimes too much but with a correct result)
         // it fixes also ^[0-9]
         while(left >= 1 && substring(theText, left-1, 1) == "^")
             left-=1;
         if (left >= 2 && substring(theText, left-2, 2) == "^x") // ^x/
             left-=2;
         else if (left >= 3 && substring(theText, left-3, 2) == "^x")
             {
                 ch = str2chr(theText, left-1);
                 if( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') ) // ^xr/
                     left-=3;
             }
         else if (left >= 4 && substring(theText, left-4, 2) == "^x")
             {
                 ch = str2chr(theText, left-2);
                 if ( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') )
                 {
                     ch = str2chr(theText, left-1);
                     if ( (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F') ) // ^xrg/
                         left-=4;
                 }
             }
     }
     return left;
 }
string textShortenToLength (string theText, float maxWidth, textLengthUpToLength_lenFunction_t tw)
Definition at line 925 of file util.qc.
References strcat(), substring(), and textLengthUpToLength().
 {
     if(tw(theText) <= maxWidth)
         return theText;
     else
         return strcat(substring(theText, 0, textLengthUpToLength(theText, maxWidth - tw("..."), tw)), "...");
 }
string textShortenToWidth (string theText, float maxWidth, vector size, textLengthUpToWidth_widthFunction_t tw)
Definition at line 917 of file util.qc.
References strcat(), substring(), and textLengthUpToWidth().
Referenced by draw_TextShortenToWidth(), HUD_Chat(), HUD_FixScoreboardColumnWidth(), HUD_Mod_Race(), HUD_Notify(), HUD_Quickmenu_DrawEntry(), HUD_Score_Rankings(), HUD_Vote(), MapVote_FormatMapItem(), minigame_drawcolorcodedstring_trunc(), and minigame_drawstring_trunc().
 {
     if(tw(theText, theFontSize) <= maxWidth)
         return theText;
     else
         return strcat(substring(theText, 0, textLengthUpToWidth(theText, maxWidth - tw("...", theFontSize), theFontSize, tw)), "...");
 }
float u8_strsize (string s)
Definition at line 217 of file string.qh.
References str2chr.
 {
     int l = 0;
     for (int i = 0, c; (c = str2chr(s, i)) > 0; ++i, ++l)
     {
         l += (c >= 0x80);
         l += (c >= 0x800);
         l += (c >= 0x10000);
     }
     return l;
 }
float vercmp (string v1, string v2)
Definition at line 313 of file string.qh.
References strcasecmp, and vercmp_recursive().
Referenced by PlayerPreThink(), and UpdateNotification_URI_Get_Callback().
 {
     if (strcasecmp(v1, v2) == 0) return 0;  // early out check
     // "git" beats all
     if (v1 == "git") return 1;
     if (v2 == "git") return -1;
     return vercmp_recursive(v1, v2);
 }
string wordwrap (string s, float l)
Definition at line 48 of file util.qc.
References wordwrap_buffer, wordwrap_buffer_put(), and wordwrap_cb().
 {
     string r;
     wordwrap_buffer = "";
     wordwrap_cb(s, l, wordwrap_buffer_put);
     r = wordwrap_buffer;
     wordwrap_buffer = "";
     return r;
 }
void wordwrap_cb (string s, float l, void(string) callback)
Definition at line 92 of file util.qc.
References strlen(), strunzone(), strzone(), and substring().
Referenced by wordwrap(), and wordwrap_sprint().
 {
     string c;
     float lleft, i, j, wlen;
     s = strzone(s);
     lleft = l;
     for (i = 0;i < strlen(s);++i)
     {
         if (substring(s, i, 2) == "\\n")
         {
             callback("\n");
             lleft = l;
             ++i;
         }
         else if (substring(s, i, 1) == "\n")
         {
             callback("\n");
             lleft = l;
         }
         else if (substring(s, i, 1) == " ")
         {
             if (lleft > 0)
             {
                 callback(" ");
                 lleft = lleft - 1;
             }
         }
         else
         {
             for (j = i+1;j < strlen(s);++j)
                 //    ^^ this skips over the first character of a word, which
                 //       is ALWAYS part of the word
                 //       this is safe since if i+1 == strlen(s), i will become
                 //       strlen(s)-1 at the end of this block and the function
                 //       will terminate. A space can't be the first character we
                 //       read here, and neither can a \n be the start, since these
                 //       two cases have been handled above.
             {
                 c = substring(s, j, 1);
                 if (c == " ")
                     break;
                 if (c == "\\")
                     break;
                 if (c == "\n")
                     break;
                 // we need to keep this tempstring alive even if substring is
                 // called repeatedly, so call strcat even though we're not
                 // doing anything
                 callback("");
             }
             wlen = j - i;
             if (lleft < wlen)
             {
                 callback("\n");
                 lleft = l;
             }
             callback(substring(s, i, wlen));
             lleft = lleft - wlen;
             i = j - 1;
         }
     }
     strunzone(s);
 }
void wordwrap_sprint (string s, float l)
Definition at line 70 of file util.qc.
References SELFPARAM, sprint(), strcat(), wordwrap_buffer, wordwrap_buffer_sprint(), and wordwrap_cb().
Referenced by CommonCommand_info().
 {SELFPARAM();
     wordwrap_buffer = "";
     wordwrap_cb(s, l, wordwrap_buffer_sprint);
     if(wordwrap_buffer != "")
         sprint(self, strcat(wordwrap_buffer, "\n"));
     wordwrap_buffer = "";
     return;
 }
void WriteInt24_t (float dest, float val)
Definition at line 302 of file net.qh.
References floor(), WriteByte(), and WriteShort().
Referenced by accuracy_send(), ClientInit_misc(), CSQCModel_Send(), PlayerScore_SendEntity(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendNextCheckpoint(), race_SendRankings(), race_SendTime(), ScoreInfo_SendEntity(), TeamScore_SendEntity(), WriteInt48_t(), and WriteInt72_t().
         {
             float v;
             WriteShort(dst, (v = floor(val >> 8)));
             WriteByte(dst, val - (v << 8));  // 0..255
         }
void WriteInt48_t (float dest, vector val)
Definition at line 308 of file net.qh.
References WriteInt24_t().
         {
             WriteInt24_t(dst, val.x);
             WriteInt24_t(dst, val.y);
         }
void WriteInt72_t (float dest, vector val)
Definition at line 313 of file net.qh.
References WriteInt24_t().
         {
             WriteInt24_t(dst, val.x);
             WriteInt24_t(dst, val.y);
             WriteInt24_t(dst, val.z);
         }
float xdecode (string s)
Definition at line 1338 of file util.qc.
References strlen(), strstrofs, and substring().
 {
     float a, b, c, d;
     if(substring(s, 0, 1) != "^")
         return -1;
     if(strlen(s) < 5)
         return -1;
     a = strstrofs(XENCODE_2,  substring(s, 1, 1), 0);
     b = strstrofs(XENCODE_22, substring(s, 2, 1), 0);
     c = strstrofs(XENCODE_22, substring(s, 3, 1), 0);
     d = strstrofs(XENCODE_22, substring(s, 4, 1), 0);
     if(a < 0 || b < 0 || c < 0 || d < 0)
         return -1;
     return ((a * 22 + b) * 22 + c) * 22 + d;
 }
string xencode (float f)
Variable Documentation
const float CNT_GAMESTART = 2
Definition at line 284 of file util.qh.
Referenced by Announcer_Countdown(), and Announcer_PickNumber().
const float CNT_IDLE = 3
Definition at line 285 of file util.qh.
Referenced by Announcer_PickNumber(), and PlayerPostThink().
const float CNT_KILL = 4
Definition at line 286 of file util.qh.
Referenced by Announcer_PickNumber(), and KillIndicator_Think().
const float CNT_NORMAL = 1
Definition at line 283 of file util.qh.
const float CNT_RESPAWN = 5
Definition at line 287 of file util.qh.
Referenced by Announcer_PickNumber(), and ShowRespawnCountdown().
const float CNT_ROUNDSTART = 6
Definition at line 288 of file util.qh.
Referenced by Announcer_Countdown(), and Announcer_PickNumber().
string draw_currentSkin
Definition at line 19 of file util.qh.
Referenced by CSQC_Init(), draw_UseSkinFor(), and m_init_delayed().
float get_model_parameters_age
Definition at line 185 of file util.qh.
Referenced by get_model_parameters().
string get_model_parameters_bone_aim[MAX_AIM_BONES]
Definition at line 190 of file util.qh.
Referenced by get_model_parameters(), and skeleton_loadinfo().
float get_model_parameters_bone_aimweight[MAX_AIM_BONES]
Definition at line 191 of file util.qh.
Referenced by get_model_parameters(), and skeleton_loadinfo().
string get_model_parameters_bone_upperbody
Definition at line 187 of file util.qh.
Referenced by get_model_parameters(), and skeleton_loadinfo().
string get_model_parameters_bone_weapon
Definition at line 188 of file util.qh.
Referenced by get_model_parameters(), and skeleton_loadinfo().
string get_model_parameters_desc
Definition at line 193 of file util.qh.
Referenced by get_model_parameters().
string get_model_parameters_description
Definition at line 186 of file util.qh.
Referenced by get_model_parameters().
float get_model_parameters_fixbone
Definition at line 192 of file util.qh.
Referenced by get_model_parameters(), and skeleton_loadinfo().
string get_model_parameters_modelname
Definition at line 179 of file util.qh.
Referenced by get_model_parameters().
float get_model_parameters_modelskin
Definition at line 180 of file util.qh.
Referenced by get_model_parameters().
string get_model_parameters_name
Definition at line 181 of file util.qh.
Referenced by get_model_parameters().
string get_model_parameters_sex
Definition at line 183 of file util.qh.
Referenced by get_model_parameters().
float get_model_parameters_species
Definition at line 182 of file util.qh.
Referenced by get_model_parameters(), and player_getspecies().
float get_model_parameters_weight
Definition at line 184 of file util.qh.
Referenced by get_model_parameters().
string getWrappedLine_remaining
Definition at line 124 of file util.qh.
Referenced by GameTypeVote_DrawGameTypeItem(), getWrappedLine(), getWrappedLineLen(), HUD_CenterPrint(), m_tooltip(), minigame_drawcolorcodedstring_wrapped(), minigame_drawstring_wrapped(), minigame_getWrappedLine(), and Say().
const int MAX_AIM_BONES = 4
Definition at line 189 of file util.qh.
Referenced by get_model_parameters(), skeleton_from_frames(), and skeleton_loadinfo().
vector mi_max
Definition at line 90 of file util.qh.
Referenced by CSQC_Init(), get_mi_min_max(), get_mi_min_max_texcoords(), HUD_Radar(), InitGameplayMode(), and RadarMap_Think().
vector mi_min
Definition at line 89 of file util.qh.
Referenced by CSQC_Init(), get_mi_min_max(), get_mi_min_max_texcoords(), HUD_Radar(), InitGameplayMode(), and RadarMap_Think().
vector mi_picmax
Definition at line 94 of file util.qh.
Referenced by CSQC_UpdateView(), get_mi_min_max_texcoords(), HUD_Radar(), RadarMap_Think(), and teamradar_3dcoord_to_texcoord().
vector mi_picmin
Definition at line 93 of file util.qh.
Referenced by CSQC_UpdateView(), get_mi_min_max_texcoords(), HUD_Radar(), RadarMap_Think(), and teamradar_3dcoord_to_texcoord().
vector mi_pictexcoord0
Definition at line 95 of file util.qh.
Referenced by draw_teamradar_background(), and get_mi_min_max_texcoords().
vector mi_pictexcoord1
Definition at line 96 of file util.qh.
Referenced by draw_teamradar_background(), and get_mi_min_max_texcoords().
vector mi_pictexcoord2
Definition at line 97 of file util.qh.
Referenced by draw_teamradar_background(), and get_mi_min_max_texcoords().
vector mi_pictexcoord3
Definition at line 98 of file util.qh.
Referenced by draw_teamradar_background(), and get_mi_min_max_texcoords().
string mi_shortname
Definition at line 88 of file util.qh.
Referenced by BGMScript_Init(), CSQC_Init(), get_mi_min_max(), and RadarMap_Think().
float skeleton_bones
Definition at line 221 of file util.qh.
const float TIME_DECIMALS = 2
Definition at line 56 of file util.qh.
Referenced by HUD_Score(), and MakeRaceString().
const float TIME_FACTOR = 100
Definition at line 57 of file util.qh.
noref float unused_float
Definition at line 238 of file util.qh.
Referenced by CSQCModel_CheckUpdate(), CSQCModel_Send(), GameType_GetID(), and GenericCommand_markup_init().
const float XENCODE_LEN = 5
Definition at line 207 of file util.qh.
const float XENCODE_MAX = 21295
Definition at line 206 of file util.qh.