Xonotic: Container Class Reference
Container Class Reference
Public Member Functions
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
ATTRIB (MenuItem, parent, entity)
ATTRIB (Container, firstChild, entity)
ATTRIB (Container, lastChild, entity)
ATTRIB (MenuItem, tooltip, string)
ATTRIB (Container, focusedChild, entity)
ATTRIB (Container, savedFocus, entity)
virtual void destroy ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFocus ()
virtual void showNotify ()
virtual void toString ()
Public Attributes
float allowFocusSound = 0
float focusable = 0
float focused = 0
vector origin = '0 0 0'
float preferredFocusPriority = 0
float shown = 0
vector size = '0 0 0'
Detailed Description
Definition at line 5 of file container.qh.
Member Function Documentation
virtual void Container::addItem () virtual
Reimplemented in ModalController, and Nexposee.
virtual void Container::addItemCentered () virtual
virtual void Container::addItemRightCentered () virtual
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
Container::ATTRIB (Container , firstChild , entity)
Container::ATTRIB (Container , lastChild , entity)
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
Container::ATTRIB (Container , focusedChild , entity)
Container::ATTRIB (Container , savedFocus , entity)
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Container::draw () virtual
Reimplemented from MenuItem.
Reimplemented in ModalController, MainWindow, XonoticProfileTab, and Nexposee.
Referenced by XonoticScrollPanel::drawListBoxItem().
virtual void Container::enterLieSubitem () virtual
virtual void Container::enterSubitem () virtual
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void Container::focusLeave () virtual
Reimplemented from MenuItem.
Reimplemented in InputContainer.
virtual void Container::hideNotify () virtual
Reimplemented from MenuItem.
virtual void Container::itemFromPoint () virtual
virtual void Container::keyDown () virtual
Reimplemented from MenuItem.
Reimplemented in Dialog, XonoticScreenshotViewerDialog, Nexposee, and InputContainer.
virtual void Container::keyUp () virtual
Reimplemented from MenuItem.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual
virtual void Container::mouseDrag () virtual
Reimplemented from MenuItem.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::mouseMove () virtual
Reimplemented from MenuItem.
Reimplemented in Nexposee, and InputContainer.
void Container::mousePress () virtual
Reimplemented from MenuItem.
Reimplemented in Nexposee, and InputContainer.
Definition at line 181 of file container.qc.
References entity(), and globalToBox().
     {
         entity f = this.focusedChild;
         if (f)
         {
             this.enterSubitem(this, f);
             bool r = f.mousePress(f, globalToBox(pos, f.Container_origin, f.Container_size));
             this.leaveSubitem(this);
             return r;
         }
         return false;
     }
virtual void Container::mouseRelease () virtual
Reimplemented from MenuItem.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::moveItemAfter () virtual
virtual void Container::preferredFocusedGrandChild () virtual
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual
virtual void Container::resizeNotify () virtual
Reimplemented from MenuItem.
Reimplemented in ModalController, Nexposee, and InputContainer.
virtual void Container::resizeNotifyLie () virtual
virtual void Container::saveFocus () virtual
virtual void Container::setAlphaOf () virtual
virtual void Container::setFocus () virtual
virtual void Container::showNotify () virtual
Reimplemented from MenuItem.
Reimplemented in XonoticDamageTextSettings, XonoticTab, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
void MenuItem::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
Member Data Documentation
float MenuItem::allowFocusSound = 0 inherited
Definition at line 26 of file item.qh.
float Container::focusable = 0
Definition at line 28 of file container.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
vector MenuItem::origin = '0 0 0' inherited
Definition at line 29 of file item.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float Container::shown = 0
Definition at line 33 of file container.qh.
vector MenuItem::size = '0 0 0' inherited
Definition at line 30 of file item.qh.
The documentation for this class was generated from the following files:
menu/item/container.qh
menu/item/container.qc