Xonotic: server-testcase/framework.qc File Reference
framework.qc File Reference
Functions
void error (string e)
string ftos (float f)
void LOG_TRACE (string s,...)
spawnfunc (worldspawn)
float test ()
string vtos (vector v)
Function Documentation
void error (string e)
Referenced by spawnfunc().
string ftos (float f)
void LOG_TRACE (string s, ...)
Referenced by _MapInfo_FilterGametype(), _MapInfo_Generate(), _MapInfo_Parse_Settemp(), activate_minigame(), Ban_Insert(), bot_aim(), bot_clearqueue(), bot_relinkplayerlist(), CommonCommand_timein(), CSQCModel_AutoTagIndex_Apply(), ctf_DelayedInit(), ctf_FlagThink(), ctf_Handle_Pickup(), cvar_settemp(), DistributeEvenly_Init(), dom_DelayedInit(), draw_Text(), end_minigame(), GameCommand_adminmsg(), GameTypeVote_Finished(), GenericCommand_settemp(), GenericCommand_settemp_restore(), havocbot_chooserole(), havocbot_moveto(), havocbot_movetogoal(), havocbot_role_ctf_setrole(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_kh_carrier(), havocbot_role_kh_defense(), havocbot_role_kh_freelancer(), havocbot_role_kh_offense(), HitSound(), HUD_Main(), LinkDoors(), m_init(), m_keydown(), m_keyup(), MapHasRightSize(), minigame_read_owner(), Monster_Sound_Precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), OnlineBanList_URI_Get_Callback(), pathlib_astar(), pathlib_close_node(), pathlib_expandnode_star(), pathlib_makenode_adaptive(), pathlib_walknode(), pathlib_waypointpath(), pathlib_waypointpath_step(), PlayerJump(), prandom(), psrandom(), Shutdown(), skeleton_loadinfo(), Spawn_Score(), spawnfunc(), start_minigame(), SUB_NoImpactCheck(), superspec_save_client_conf(), tdm_DelayedInit(), tracebox_inverted(), turret_checkpoint_init(), updateConwidths(), UpdateDamage(), UpdateNotification_URI_Get_Callback(), vehicles_exit(), W_Reload(), WarpZone_Touch(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_BoxTouchesBrush_Recurse(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), WinningCondition_LMS(), XonoticResolutionSlider_loadResolutions(), and XonoticStatsList_getStats().
spawnfunc (worldspawn)
Definition at line 7 of file framework.qc.
References error(), LOG_TRACE(), and test().
 {
     float r;
     LOG_TRACE("TESTCASE: START");
     r = test();
     if(r == 1)
         error("TESTCASE: PASS");
     else if(r == 0)
         error("TESTCASE: FAIL");
     else
         error("TESTCASE: INVALID");
 }
float test ()
Referenced by MUTATOR_HOOKFUNCTION(), and spawnfunc().
string vtos (vector v)