Xonotic: menu/xonotic/util.qc File Reference
util.qc File Reference
#include "util.qh"
#include "../item.qh"
#include "../menu.qh"
#include <common/campaign_common.qh>
#include <common/constants.qh>
#include <common/mapinfo.qh>
#include <common/util.qh>
#include <common/command/_mod.qh>
Macros
#define GAMETYPE(it) { if (i++ == cnt) return it; }
#define GAMETYPE(id) ++i;
#define GAMETYPE(it) if (cvar("developer")) ++i;
#define GAMETYPE(id) ++i;
#define GAMETYPES
#define HIDDEN_GAMETYPES
Functions
void CheckSendCvars (entity me, string cvarnamestring)
void clearTooltip (entity e)
void dialog_hudpanel_common_notoggle (entity me, string panelname)
void DialogOpenButton_Click_withCoords (entity button, entity tab, vector theOrigin, vector theSize)
void DisableServerBackwardsCompatibility ()
float (entity) func_setDependent
void forAllDescendants (entity root, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
int GameType_GetCount ()
string GameType_GetIcon (int cnt)
Gametype GameType_GetID (int cnt)
string GameType_GetName (int cnt)
int GameType_GetTotalCount ()
string getCvarsMulti (entity me)
float getFadedAlpha (float currentAlpha, float startAlpha, float targetAlpha)
float GL_CheckExtension (string ext)
float GL_Have_TextureCompression ()
void loadAllCvars (entity root)
void loadCvarsOf (entity ignore, entity e)
void makeCallback (entity e, entity cbent, void(entity, entity) cbfunc)
void makeMulti (entity e, string otherCvars)
entity makeXonoticCheckBox (float, string, string)
entity makeXonoticCheckBoxString (string, string, string, string)
entity makeXonoticColorpickerString (string theCvar, string theDefaultCvar)
entity makeXonoticTextLabel (float theAlign, string theText)
entity makeXonoticTextSlider (string)
void postMenuDraw ()
this is run just after the menu is drawn (or not).
void preMenuDraw ()
this is run before the menu is drawn.
float preMenuInit ()
you have to define this for pre-menu initialization.
string resolvemod (string m)
void saveAllCvars (entity root)
void saveCvarsCallback (entity me)
void saveCvarsMulti (entity me)
void saveCvarsOf (entity ignore, entity e)
void setDependent (entity e, string theCvarName, float theCvarMin, float theCvarMax)
void setDependent_Check (entity e)
void setDependent_Draw (entity e)
void setDependentAND (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
void setDependentAND3 (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max, string theCvar3Name, float theCvar3Min, float theCvar3Max)
void setDependentOR (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
void setDependentStringNotEqual (entity e, string theCvarName, string theCvarValue)
void setDependentWeird (entity e, float(entity) func)
void setZonedTooltip (entity e, string theTooltip, string theCvar)
void SUB_Null_ee (entity e1, entity e2)
void updateCheck ()
float updateCompression ()
void UpdateNotification_URI_Get_Callback (float id, float status, string data)
void URI_Get_Callback (float id, float status, string data)
engine callback
void (entity) saveCvars
void (entity me, entity cb) saveCvars_Callback_func
void (entity, float, float, entity) TD
void (entity, float) TDempty
void (entity, string, string) addValue
Variables
string _Nex_ExtResponseSystem_Packs
float _Nex_ExtResponseSystem_PacksStep
float _Nex_ExtResponseSystem_Queried
string _Nex_ExtResponseSystem_UpdateTo
string _Nex_ExtResponseSystem_UpdateToURL
string autocvar_menu_watermark = ""
string campaign_name_previous
float campaign_won_previous
string cvar2_setDependent
float cvar2Max_setDependent
float cvar2Min_setDependent
string cvar3_setDependent
float cvar3Max_setDependent
float cvar3Min_setDependent
string cvar_setDependent
float cvarMax_setDependent
float cvarMin_setDependent
string cvarName
string cvarNames_Multi
string cvarString_setDependent
string cvarValue_setDependent
bool disabled
entity firstChild
entity nextSibling
float op_setDependent
entity parent
entity saveCvars_Callback_ent
bool sendCvars
entity winnerDialog
Macro Definition Documentation
#define GAMETYPE (it) { if (i++ == cnt) return it; }
#define GAMETYPE (id) ++i;
#define GAMETYPE (it) if (cvar("developer")) ++i;
#define GAMETYPE (id) ++i;
#define GAMETYPES
Value:
GAMETYPE(MAPINFO_TYPE_DEATHMATCH) \
    GAMETYPE(MAPINFO_TYPE_TEAM_DEATHMATCH) \
    GAMETYPE(MAPINFO_TYPE_CTF) \
    GAMETYPE(MAPINFO_TYPE_CA) \
    GAMETYPE(MAPINFO_TYPE_FREEZETAG) \
    GAMETYPE(MAPINFO_TYPE_KEEPAWAY) \
    GAMETYPE(MAPINFO_TYPE_KEYHUNT) \
    GAMETYPE(MAPINFO_TYPE_LMS) \
    GAMETYPE(MAPINFO_TYPE_DOMINATION) \
    GAMETYPE(MAPINFO_TYPE_NEXBALL) \
    GAMETYPE(MAPINFO_TYPE_ONSLAUGHT) \
    GAMETYPE(MAPINFO_TYPE_ASSAULT) \
    /* GAMETYPE(MAPINFO_TYPE_INVASION) */ \
Definition at line 675 of file util.qc.
Referenced by GameType_GetCount(), GameType_GetID(), and GameType_GetTotalCount().
#define HIDDEN_GAMETYPES
Value:
GAMETYPE(MAPINFO_TYPE_RACE) \
    GAMETYPE(MAPINFO_TYPE_CTS) \
Definition at line 692 of file util.qc.
Referenced by GameType_GetCount(), GameType_GetID(), and GameType_GetTotalCount().
Function Documentation
void CheckSendCvars (entity me, string cvarnamestring)
Definition at line 821 of file util.qc.
References cmd(), cvar_string(), GAME_CONNECTED, GAME_ISSERVER, gamestatus, and LOG_INFOF.
Referenced by saveCvarsMulti(), XonoticCheckBox_saveCvars(), XonoticCheckBoxString_saveCvars(), XonoticInputBox_saveCvars(), XonoticSlider_saveCvars(), and XonoticTextSlider_saveCvars().
 {
     if(me.sendCvars)
     {
         LOG_INFOF("Sending cvar: %s -> %s\n", cvarnamestring, cvar_string(cvarnamestring));
         if(gamestatus & (GAME_CONNECTED | GAME_ISSERVER))
         {
             cmd(sprintf("\nsendcvar %s\n", cvarnamestring));
         }
     }
 }
void clearTooltip (entity e)
Definition at line 274 of file util.qc.
References setZonedTooltip(), and string_null.
Referenced by XonoticRegisteredSettingsList::focusedItemChangeNotify(), ServerList_Update_favoriteButton(), XonoticGametypeList_focusedItemChangeNotify(), XonoticServerList_focusedItemChangeNotify(), and XonoticServerList_mouseMove().
 {
     setZonedTooltip(e, string_null, string_null);
 }
void dialog_hudpanel_common_notoggle (entity me, string panelname)
Definition at line 753 of file util.qc.
References entity(), ftos(), ftos_decimals(), makeXonoticCheckBox(), makeXonoticCheckBoxString(), makeXonoticColorpickerString(), makeXonoticTextLabel(), makeXonoticTextSlider(), setDependentStringNotEqual(), strcat(), and strzone().
 {
     float i;
     entity e;
     me.TR(me);
         me.TD(me, 1, 1.4, e = makeXonoticTextLabel(0, _("Background:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 e.addValue(e, strzone(strcat("border_", panelname)), strzone(strcat("border_", panelname)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Color:")));
         me.TD(me, 2, 2.6, e = makeXonoticColorpickerString(strzone(strcat("hud_panel_", panelname, "_bg_color")), "hud_panel_bg_color"));
             setDependentStringNotEqual(e, strzone(strcat("hud_panel_", panelname, "_bg_color")), "");
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.0, e = makeXonoticCheckBoxString("", "1 1 1", strzone(strcat("hud_panel_", panelname, "_bg_color")), _("Use default")));
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Border size:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_border"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i * 2, 0)), strzone(ftos(i * 2)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Alpha:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_alpha"))));
                 e.addValue(e, _("Default"), "");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i/10, 1)), strzone(ftos(i/10)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Team Color:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_color_team"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i/10, 1)), strzone(ftos(i/10)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.4);
         me.TD(me, 1, 3.6, e = makeXonoticCheckBox(0, "hud_configure_teamcolorforced", _("Test team color in configure mode")));
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Padding:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_padding"))));
                 e.addValue(e, _("Default"), "");
                 for(i = 0; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i - 5, 0)), strzone(ftos(i - 5)));
                 e.configureXonoticTextSliderValues(e);
 }
void DialogOpenButton_Click_withCoords (entity button, entity tab, vector theOrigin, vector theSize)
Definition at line 35 of file modalcontroller.qc.
Referenced by DemoConfirm_ListClick_Check_Gamestatus(), DialogOpenButton_Click(), MainWindow_draw(), preMenuDraw(), ServerList_Info_Click(), XonoticMapList_doubleClickListBoxItem(), XonoticMapList_keyDown(), XonoticScreenshotList_startScreenshot(), and XonoticServerList_keyDown().
     {
         if (tab.ModalController_state) return;
         if (button) button.forcePressed = 1;
         if (tab.parent.focusedChild) tab.parent.focusedChild.saveFocus(tab.parent.focusedChild);
         tab.ModalController_controllingButton = button;
         tab.parent.showChild(tab.parent, tab, theOrigin, theSize, 0);
     }
void DisableServerBackwardsCompatibility ()
Definition at line 313 of file util.qc.
References cvar(), cvar_set(), floor(), and ftos().
Referenced by UpdateNotification_URI_Get_Callback().
 {
     cvar_set("gameversion_min", ftos(100 * floor(cvar("gameversion") / 100)));
 }
float (entity)
void forAllDescendants (entity root, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
Definition at line 23 of file util.qc.
References depthfirst(), firstChild, nextSibling, and parent.
Referenced by loadAllCvars(), and saveAllCvars().
 {
     depthfirst(root, parent, firstChild, nextSibling, funcPre, funcPost, pass);
 }
int GameType_GetCount ()
Definition at line 707 of file util.qc.
References GAMETYPES, and HIDDEN_GAMETYPES.
Referenced by XonoticGametypeList_configureXonoticGametypeList(), XonoticGametypeList_draw(), and XonoticGametypeList_loadCvars().
 {
     int i = 0;
     #define GAMETYPE(id) ++i;
     GAMETYPES
     #undef GAMETYPE
     #define GAMETYPE(it) if (cvar("developer")) ++i;
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return i;
 }
string GameType_GetIcon (int cnt)
Definition at line 735 of file util.qc.
References GameType_GetID(), MapInfo_Type_ToString(), and strcat().
Referenced by XonoticGametypeList_configureXonoticGametypeList(), and XonoticGametypeList_drawListBoxItem().
 {
     Gametype i = GameType_GetID(cnt);
     return i ? strcat("gametype_", MapInfo_Type_ToString(i)) : "";
 }
Gametype GameType_GetID (int cnt)
Definition at line 697 of file util.qc.
References GAMETYPES, HIDDEN_GAMETYPES, and NULL.
Referenced by GameType_GetIcon(), GameType_GetName(), XonoticGametypeList_drawListBoxItem(), XonoticGametypeList_focusedItemChangeNotify(), XonoticGametypeList_loadCvars(), XonoticGametypeList_saveCvars(), XonoticMapInfoDialog_fill(), and XonoticMapInfoDialog_loadMapInfo().
 {
     int i = 0;
     #define GAMETYPE(it) { if (i++ == cnt) return it; }
     GAMETYPES
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return NULL;
 }
string GameType_GetName (int cnt)
Definition at line 729 of file util.qc.
References GameType_GetID(), and MapInfo_Type_ToText().
Referenced by XonoticGametypeList_drawListBoxItem().
 {
     Gametype i = GameType_GetID(cnt);
     return i ? MapInfo_Type_ToText(i) : "";
 }
int GameType_GetTotalCount ()
Definition at line 719 of file util.qc.
References GAMETYPES, and HIDDEN_GAMETYPES.
Referenced by XonoticGametypeList_configureXonoticGametypeList(), XonoticMapInfoDialog_fill(), and XonoticMapInfoDialog_loadMapInfo().
 {
     int i = 0;
     #define GAMETYPE(id) ++i;
     GAMETYPES
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return i;
 }
string getCvarsMulti (entity me)
Definition at line 57 of file util.qc.
References string_null.
Referenced by gettooltip().
 {
     if (me.cvarNames_Multi)
         return me.cvarNames_Multi;
     return string_null;
 }
float getFadedAlpha (float currentAlpha, float startAlpha, float targetAlpha)
Definition at line 812 of file util.qc.
References frametime, max(), and min().
Referenced by XonoticRegisteredSettingsList::drawListBoxItem(), XonoticCampaignList_drawListBoxItem(), XonoticCvarList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPicker_draw(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), XonoticSoundList_drawListBoxItem(), XonoticStatsList_drawListBoxItem(), and XonoticWeaponsList_drawListBoxItem().
 {
     if(startAlpha < targetAlpha)
         currentAlpha = min(currentAlpha + frametime * 0.5, targetAlpha);
     else
         currentAlpha = max(currentAlpha - frametime * 0.5, targetAlpha);
     return currentAlpha;
 }
float GL_CheckExtension (string ext)
Definition at line 12 of file util.qc.
References cvar_string(), and strhasword.
Referenced by GL_Have_TextureCompression().
 {
     return strhasword(cvar_string("gl_info_extensions"), ext);
 }
float GL_Have_TextureCompression ()
Definition at line 17 of file util.qc.
References GL_CheckExtension().
Referenced by updateCompression(), and XonoticPicmipSlider_configureXonoticPicmipSlider().
 {
     return (GL_CheckExtension("GL_EXT_texture_compression_s3tc") && GL_CheckExtension("GL_ARB_texture_compression"));
 }
void loadAllCvars (entity root)
Definition at line 50 of file util.qc.
References forAllDescendants(), loadCvarsOf(), NULL, and SUB_Null_ee().
Referenced by m_sync(), XonoticCvarsDialog_showNotify(), XonoticGameCrosshairSettingsTab_showNotify(), XonoticGameHUDSettingsTab_showNotify(), XonoticGameMessageSettingsTab_showNotify(), XonoticGameModelSettingsTab_showNotify(), XonoticGameViewSettingsTab_showNotify(), XonoticGameWeaponsSettingsTab_showNotify(), XonoticMutatorsDialog_showNotify(), and XonoticTab_showNotify().
 {
     forAllDescendants(root, loadCvarsOf, SUB_Null_ee, NULL);
 }
void loadCvarsOf (entity ignore, entity e)
Definition at line 41 of file util.qc.
Referenced by loadAllCvars().
 {
     if(e.loadCvars)
         e.loadCvars(e);
 }
void makeCallback (entity e, entity cbent, void(entity, entity) cbfunc)
Definition at line 104 of file util.qc.
References saveCvarsCallback().
Referenced by XonoticServerCreateTab_fill().
 {
     e.saveCvars_Callback = e.saveCvars;
     e.saveCvars = saveCvarsCallback;
     e.saveCvars_Callback_ent = cbent;
     e.saveCvars_Callback_func = cbfunc;
 }
void makeMulti (entity e, string otherCvars)
Definition at line 89 of file util.qc.
References saveCvarsMulti().
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), and XonoticMutatorsDialog_fill().
 {
     e.cvarNames_Multi = otherCvars;
     e.saveCvars_Multi = e.saveCvars;
     e.saveCvars = saveCvarsMulti;
 }
entity makeXonoticCheckBox (float , string , string)
Definition at line 28 of file checkbox.qc.
References makeXonoticCheckBox_T(), and string_null.
Referenced by dialog_hudpanel_common_notoggle(), XonoticAudioSettingsTab_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticServerListTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCheckBox_T(isInverted, theCvar, theText, string_null);
 }
entity makeXonoticCheckBoxString (string , string , string , string)
Definition at line 3 of file checkbox_string.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle().
 {
     entity me;
     me = NEW(XonoticCheckBoxString);
     me.configureXonoticCheckBoxString(me, theYesValue, theNoValue, theCvar, theText);
     return me;
 }
entity makeXonoticColorpickerString (string theCvar, string theDefaultCvar)
Definition at line 5 of file colorpicker_string.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle(), XonoticGameCrosshairSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDWeaponsDialog_fill(), and XonoticSandboxToolsDialog_fill().
 {
     entity me;
     me = NEW(XonoticColorpickerString);
     me.configureXonoticColorpickerString(me, theCvar, theDefaultCvar);
     return me;
 }
entity makeXonoticTextLabel (float theAlign, string theText)
Definition at line 3 of file textlabel.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle(), makeXonoticHeaderLabel(), XonoticAudioSettingsTab_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticDemoStartConfirmDialog_fill(), XonoticDemoTimeConfirmDialog_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDConfirmDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDQuickMenuDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDVoteDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticLanguageWarningDialog_fill(), XonoticMapInfoDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticQuitDialog_fill(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticServerCreateTab_fill(), XonoticServerInfoDialog_fill(), XonoticServerListTab_fill(), XonoticSingleplayerDialog_fill(), XonoticUid2NameDialog_fill(), XonoticUserbindEditDialog_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticTextLabel);
     me.configureXonoticTextLabel(me, theAlign, theText);
     return me;
 }
entity makeXonoticTextSlider (string)
Definition at line 10 of file textslider.qc.
References makeXonoticTextSlider_T(), and string_null.
Referenced by dialog_hudpanel_common_notoggle(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticTextSlider_T(theCvar, string_null);
 }
void postMenuDraw ()
this is run just after the menu is drawn (or not).
Useful to draw something over everything else.
Definition at line 548 of file util.qc.
References draw_CenterText(), draw_scale, and globalToBoxSize().
Referenced by m_draw().
 {
     if(autocvar_menu_watermark != "")
     {
         draw_CenterText('0.5 0.1 0', sprintf(_("^1%s TEST BUILD"), autocvar_menu_watermark), globalToBoxSize('32 32 0', draw_scale), '1 1 1', 0.05, 1);
     }
 }
void preMenuDraw ()
this is run before the menu is drawn.
You may put some stuff there that has to be done every frame.
Definition at line 557 of file util.qc.
References _Nex_ExtResponseSystem_UpdateToURL, bound(), campaign_name, conheight, conwidth, cos(), cvar(), DialogOpenButton_Click_withCoords(), draw_alpha, draw_CenterText(), draw_Fill(), draw_scale, draw_TextWidth(), eX, eY, m_display(), main, max(), NULL, sin(), strcat(), strunzone(), strzone(), time, updateCheck(), and vector().
Referenced by m_draw().
 {
     vector fs, sz = '0 0 0', line, mid;
     updateCheck();
     if(_Nex_ExtResponseSystem_UpdateTo != "")
     {
         // TODO rather turn this into a dialog
         fs = ((1/draw_scale.x) * eX + (1/draw_scale.y) * eY) * 12;
         line = eY * fs.y;
         string l1, l2;
         l1 = sprintf(_("Update to %s now!"), _Nex_ExtResponseSystem_UpdateTo);
         l2 = "http://www.xonotic.org/";
         if(_Nex_ExtResponseSystem_UpdateToURL)
             l2 = _Nex_ExtResponseSystem_UpdateToURL;
         sz_x = draw_TextWidth("    ", 0, fs) + max(
                 draw_TextWidth(l1, 0, fs),
                 draw_TextWidth(l2, 0, fs)
             );
         sz_y = 3 * fs.y;
         draw_alpha = bound(0, sin(time * 0.112 - 0.3) * 10, 1);
         mid = eX * (0.5 + 0.5 * (1 - sz.x) * cos(time * 0.071))
             + eY * (0.5 + 0.5 * (1 - sz.y) * sin(time * 0.071));
         draw_Fill(mid - 0.5 * sz, sz, '1 1 0', 1);
         draw_CenterText(mid - 1 * line, l1, fs, '1 0 0', 1, 0);
         draw_CenterText(mid - 0 * line, l2, fs, '0 0 1', 1, 0);
     }
     if (!campaign_name_previous)
         campaign_name_previous = strzone(strcat(campaign_name, "x")); // force unequal
     if(campaign_name == campaign_name_previous)
     {
         if(cvar(strcat("g_campaign", campaign_name, "_won")))
         {
             if(!campaign_won_previous)
             {
                 m_display();
                 DialogOpenButton_Click_withCoords(NULL, main.winnerDialog, '0 0 0', eX * conwidth + eY * conheight);
             }
             campaign_won_previous = 1;
         }
         else
             campaign_won_previous = 0;
     }
     else
     {
         strunzone(campaign_name_previous);
         campaign_name_previous = strzone(campaign_name);
         campaign_won_previous = cvar(strcat("g_campaign", campaign_name, "_won"));
     }
 }
float preMenuInit ()
you have to define this for pre-menu initialization.
Return 0 if initialization needs to be retried a frame later, 1 if it succeeded.
Definition at line 509 of file util.qc.
References _MapInfo_FilterGametype(), draw_CenterText(), draw_Fill(), draw_reset_cropped(), draw_scale, eX, eY, MapInfo_Cache_Create(), MapInfo_Enumerate(), MapInfo_progress, MAPINFO_TYPE_ALL, updateCheck(), and vector().
Referenced by m_init_delayed().
 {
     vector sz;
     vector boxA, boxB;
     updateCheck();
     MapInfo_Cache_Create();
     MapInfo_Enumerate();
     if(!_MapInfo_FilterGametype(MAPINFO_TYPE_ALL, 0, 0, 0, 1))
     {
         draw_reset_cropped();
         sz = eX * 0.025 + eY * 0.025 * (draw_scale.x / draw_scale.y);
         draw_CenterText('0.5 0.5 0' - 1.25 * sz.y * eY, _("Autogenerating mapinfo for newly added maps..."), sz, '1 1 1', 1, 0);
         boxA = '0.05 0.5 0' + 0.25 * sz.y * eY;
         boxB = '0.95 0.5 0' + 1.25 * sz.y * eY;
         draw_Fill(boxA, boxB - boxA, '1 1 1', 1);
         boxA += sz * 0.1;
         boxB -= sz * 0.1;
         draw_Fill(boxA, boxB - boxA, '0.1 0.1 0.1', 1);
         boxB_x = boxA_x * (1 - MapInfo_progress) + boxB_x * MapInfo_progress;
         draw_Fill(boxA, boxB - boxA, '0 0 1', 1);
         return false;
     }
     return true;
 }
string resolvemod (string m)
Definition at line 612 of file util.qc.
References getcurrentmod().
Referenced by XonoticServerList_refreshServerList().
 {
     if(m == "=")
         return getcurrentmod();
     else
         return m;
 }
void saveAllCvars (entity root)
Definition at line 46 of file util.qc.
References forAllDescendants(), NULL, saveCvarsOf(), and SUB_Null_ee().
 {
     forAllDescendants(root, saveCvarsOf, SUB_Null_ee, NULL);
 }
void saveCvarsCallback (entity me)
Definition at line 99 of file util.qc.
Referenced by makeCallback().
 {
     me.saveCvars_Callback(me);
     me.saveCvars_Callback_func(me.saveCvars_Callback_ent, me);
 }
void saveCvarsMulti (entity me)
Definition at line 63 of file util.qc.
References argv(), CheckSendCvars(), cvar_set(), cvar_string(), strlen(), substring(), and tokenize_console.
Referenced by makeMulti().
 {
     float n, i;
     string s, cvarname;
     me.saveCvars_Multi(me);
     s = cvar_string(me.cvarName);
     n = tokenize_console(me.cvarNames_Multi);
     for(i = 0; i < n; ++i)
     {
         // cvars prefixed with ! get saved with the inverted value
         if(substring(argv(i), 0, 1) == "!")
         {
             cvarname = substring(argv(i), 1, strlen(argv(i)));
             cvar_set(cvarname, ((s == "0") ? "1" : "0"));
         }
         else
         {
             cvarname = argv(i);
             cvar_set(cvarname, s);
         }
         CheckSendCvars(me, cvarname);
     }
 }
void saveCvarsOf (entity ignore, entity e)
Definition at line 34 of file util.qc.
Referenced by saveAllCvars().
 {
     if(e.saveCvars)
         e.saveCvars(e);
 }
void setDependent (entity e, string theCvarName, float theCvarMin, float theCvarMax)
Definition at line 174 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = string_null;
     e.cvar3_setDependent = string_null;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependent_Check (entity e)
Definition at line 127 of file util.qc.
References cvar(), and cvar_string().
Referenced by setDependent(), setDependent_Draw(), setDependentAND(), setDependentAND3(), setDependentOR(), setDependentStringNotEqual(), and setDependentWeird().
 {
     float f;
     string s;
     if(e.func_setDependent)
     {
         e.disabled = !(e.func_setDependent(e));
     }
     else if(e.cvarString_setDependent)
     {
         s = cvar_string(e.cvarString_setDependent);
         e.disabled = (cvar_string(e.cvarString_setDependent) == e.cvarValue_setDependent);
     }
     else
     {
         if(e.cvar_setDependent)
         {
             f = cvar(e.cvar_setDependent);
             if(e.cvarMin_setDependent <= e.cvarMax_setDependent)
                 e.disabled = ((f < e.cvarMin_setDependent) || (f > e.cvarMax_setDependent));
             else
                 e.disabled = ((f >= e.cvarMax_setDependent) && (f <= e.cvarMin_setDependent));
         }
         if(e.cvar2_setDependent)
         {
             f = cvar(e.cvar2_setDependent);
             if(e.cvar2Min_setDependent <= e.cvar2Max_setDependent)
                 e.disabled = (e.disabled + ((f < e.cvar2Min_setDependent) || (f > e.cvar2Max_setDependent)) > e.op_setDependent);
             else
                 e.disabled = (e.disabled + ((f >= e.cvar2Max_setDependent) && (f <= e.cvar2Min_setDependent)) > e.op_setDependent);
         }
         if(e.cvar3_setDependent)
         {
             f = cvar(e.cvar3_setDependent);
             if(e.cvar3Min_setDependent <= e.cvar3Max_setDependent)
                 e.disabled = (e.disabled + ((f < e.cvar3Min_setDependent) || (f > e.cvar3Max_setDependent)) > e.op_setDependent);
             else
                 e.disabled = (e.disabled + ((f >= e.cvar3Max_setDependent) && (f <= e.cvar3Min_setDependent)) > e.op_setDependent);
         }
     }
 }
void setDependent_Draw (entity e)
Definition at line 168 of file util.qc.
References setDependent_Check().
Referenced by setDependent(), setDependentAND(), setDependentAND3(), setDependentOR(), setDependentStringNotEqual(), and setDependentWeird().
 {
     setDependent_Check(e);
     e.draw_setDependent(e);
 }
void setDependentAND (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
Definition at line 198 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = string_null;
     e.op_setDependent = 0;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentAND3 (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max, string theCvar3Name, float theCvar3Min, float theCvar3Max)
Definition at line 228 of file util.qc.
References func_null(), setDependent_Check(), and setDependent_Draw().
Referenced by XonoticEffectsSettingsTab_fill(), and XonoticGameCrosshairSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = theCvar3Name;
     e.cvar3Min_setDependent = theCvar3Min;
     e.cvar3Max_setDependent = theCvar3Max;
     e.op_setDependent = 0;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentOR (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
Definition at line 213 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticEffectsSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = string_null;
     e.op_setDependent = 1;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentStringNotEqual (entity e, string theCvarName, string theCvarValue)
Definition at line 186 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by dialog_hudpanel_common_notoggle(), XonoticAudioSettingsTab_fill(), and XonoticHUDWeaponsDialog_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvarString_setDependent = theCvarName;
     e.cvarValue_setDependent = theCvarValue;
     e.cvar_setDependent = string_null;
     e.cvar2_setDependent = string_null;
     e.cvar3_setDependent = string_null;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentWeird (entity e, float(entity) func)
Definition at line 245 of file util.qc.
References setDependent_Check(), and setDependent_Draw().
Referenced by XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), and XonoticMutatorsDialog_fill().
 {
     e.draw_setDependent = e.draw;
     e.func_setDependent = func;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setZonedTooltip (entity e, string theTooltip, string theCvar)
Definition at line 253 of file util.qc.
References prvm_language, string_null, strunzone(), and strzone().
Referenced by clearTooltip(), XonoticRegisteredSettingsList::focusedItemChangeNotify(), ServerList_Update_favoriteButton(), XonoticButton_configureXonoticButton(), XonoticCheckBox_configureXonoticCheckBox(), XonoticGametypeList_focusedItemChangeNotify(), XonoticInputBox_configureXonoticInputBox(), XonoticRadioButton_configureXonoticRadioButton(), XonoticServerList_drawListBoxItem(), XonoticSlider_configureXonoticSlider(), and XonoticTextSlider_configureXonoticTextSlider().
 {
     if(theTooltip == "") // no tooltip, use cvar description then
     {
         if(theCvar != "" && prvm_language == "en")
         {
             string t = cvar_description(theCvar);
             if(t != "" && t != "custom cvar")
                 theTooltip = t;
         }
     }
     else if(theTooltip == "-") // no cvar description as tooltip
     {
         theTooltip = string_null;
     }
     if(e.tooltip)
         strunzone(e.tooltip);
     e.tooltip = (theTooltip != "") ? strzone(theTooltip) : string_null;
 }
void SUB_Null_ee (entity e1, entity e2)
Definition at line 29 of file util.qc.
Referenced by loadAllCvars(), and saveAllCvars().
 {
 }
void updateCheck ()
Definition at line 459 of file util.qc.
References argv(), cvar(), cvar_set(), cvar_string(), fexists(), floor(), ftos(), localcmd, Menu_Active, random(), tokenize_console, and URI_GET_UPDATENOTIFICATION.
Referenced by preMenuDraw(), and preMenuInit().
 {
     if(cvar("menu_updatecheck"))
     {
         if(!_Nex_ExtResponseSystem_Queried)
         {
             _Nex_ExtResponseSystem_Queried = 1;
             float startcnt;
             string uri;
             cvar_set("cl_startcount", ftos(startcnt = cvar("cl_startcount") + 1));
             // for privacy, munge the start count a little
             startcnt = floor((floor(startcnt / 10) + random()) * 10);
             uri = sprintf("http://update.xonotic.org/checkupdate.txt?version=%s&cnt=%d", uri_escape(cvar_string("g_xonoticversion")), startcnt);
             uri_get(uri, URI_GET_UPDATENOTIFICATION);
         }
     }
     if(_Nex_ExtResponseSystem_PacksStep > 0)
     {
         float n, i;
         float allgood;
         n = tokenize_console(_Nex_ExtResponseSystem_Packs);
         allgood = true;
         for(i = 0; i+1 < n; i += 2)
         {
             if(fexists(argv(i+1)))
                 continue;
             allgood = false;
             if(_Nex_ExtResponseSystem_PacksStep == 1) // first run
                 localcmd("\ncurl --pak \"", argv(i), "\"\n");
         }
         if(allgood)
         {
             if(_Nex_ExtResponseSystem_PacksStep == 2)
             {
                 if(!Menu_Active)
                     cvar_set("_menu_initialized", "0");
                     // HACK: cause m_hide call on next start
                 localcmd("\nmenu_restart\n");
             }
             _Nex_ExtResponseSystem_PacksStep = 0;
         }
         else
             _Nex_ExtResponseSystem_PacksStep = 2;
     }
 }
float updateCompression ()
Definition at line 620 of file util.qc.
References cvar_set(), cvar_string(), fexists(), GL_Have_TextureCompression(), and LOG_INFO.
Referenced by m_init(), m_sync(), and XonoticEffectsSettingsTab_fill().
 {
     float have_dds, have_jpg, have_tga;
     float can_dds;
     have_dds = (fexists("dds/particles/particlefont.dds"));
     have_jpg = (fexists("particles/particlefont.jpg"));
     have_tga = (fexists("particles/particlefont.tga"));
     can_dds = GL_Have_TextureCompression();
     if(have_dds && (have_jpg || have_tga))
     {
         // both? Let's only use good quality precompressed files
         // but ONLY if we actually support it!
         if(can_dds)
         {
             // these builds are meant to have GOOD quality, so let's not compress non-skinframes
             cvar_set("gl_texturecompression", "0");
             return 1;
             //cvar_set("gl_texturecompression", cvar_string("r_texture_dds_load"));
             //return 2;
         }
         else
         {
             cvar_set("gl_texturecompression", "0");
             cvar_set("r_texture_dds_load", "0");
             return 0;
         }
     }
     else if(have_dds)
     {
         // DDS only? We probably always want texture compression
         cvar_set("gl_texturecompression", "1");
         cvar_set("r_texture_dds_load", "1");
         if(!can_dds)
             LOG_INFO(_("^1ERROR: Texture compression is required but not supported.\n^1Expect visual problems.\n"));
         return 0;
     }
     else
     {
         // TGA only? Allow runtime compression
         if(can_dds)
         {
             cvar_set("gl_texturecompression", cvar_string("r_texture_dds_load"));
             return 2;
         }
         else
         {
             cvar_set("gl_texturecompression", "0");
             cvar_set("r_texture_dds_load", "0");
             return 0;
         }
     }
 }
void UpdateNotification_URI_Get_Callback (float id, float status, string data)
Definition at line 318 of file util.qc.
References _Nex_ExtResponseSystem_BannedServers, _Nex_ExtResponseSystem_BannedServersNeedsRefresh, _Nex_ExtResponseSystem_PromotedServers, _Nex_ExtResponseSystem_PromotedServersNeedsRefresh, _Nex_ExtResponseSystem_RecommendedServers, _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh, APPEND_TO_STRING, argv(), cvar(), cvar_string(), DisableServerBackwardsCompatibility(), LOG_INFOF, LOG_TRACE(), LOG_TRACEF, strcmp, strstrofs, strzone(), substring(), tokenizebyseparator, and vercmp().
Referenced by URI_Get_Callback().
 {
     float n;
     if(_Nex_ExtResponseSystem_UpdateTo)
     {
         LOG_TRACE("error: UpdateNotification_URI_Get_Callback has been called before");
         return;
     }
     if(status != 0)
     {
         LOG_TRACEF("error receiving update notification: status is %d", status);
         return;
     }
     if(substring(data, 0, 1) == "<")
     {
         LOG_TRACE("error: received HTML instead of an update notification");
         return;
     }
     if(strstrofs(data, "\r", 0) != -1)
     {
         LOG_TRACE("error: received carriage returns from update notification server");
         return;
     }
     if(data == "")
         n = 0;
     else
         n = tokenizebyseparator(data, "\n");
     float i;
     string s;
     string un_version = "";
     string un_download = "";
     string un_url = "";
     string un_bannedservers = "";
     string un_emergency_pk3s = "";
     string un_promoted = "";
     string un_recommended = "";
     string un_compatexpire = "";
     for(i = 0; i < n; ++i)
     {
         s = substring(argv(i), 2, -1);
         if(s == "") { continue; } // ignore empty lines
         switch(substring(argv(i), 0, 1))
         {
             case "V":
             {
                 un_version = s;
                 break;
             }
             case "C":
             {
                 un_compatexpire = s;
                 break;
             }
             case "D":
             {
                 un_download = s;
                 break;
             }
             case "U":
             {
                 un_url = s;
                 break;
             }
             case "B":
             {
                 APPEND_TO_STRING(un_bannedservers, " ", s);
                 break;
             }
             case "E":
             {
                 if(cvar("menu_updatecheck_getpacks"))
                     APPEND_TO_STRING(un_emergency_pk3s, " ", s);
                 break;
             }
             case "P":
             {
                 APPEND_TO_STRING(un_promoted, " ", s);
                 break;
             }
             case "R":
             {
                 APPEND_TO_STRING(un_recommended, " ", s);
                 break;
             }
         }
     }
     if(un_version != "")
     {
         if(vercmp(cvar_string("g_xonoticversion"), un_version) < 0)
         {
             // update needed
             _Nex_ExtResponseSystem_UpdateTo = strzone(un_version);
             if(un_download) { LOG_INFOF(_("Update can be downloaded at:\n%s\n"), un_download); }
             if(un_url) { _Nex_ExtResponseSystem_UpdateToURL = strzone(un_url); }
             DisableServerBackwardsCompatibility();
         }
         else if(cvar_string("g_xonoticversion") == un_version)
         {
             if(un_compatexpire != "")
             {
                 string curdate = strftime(false, "%Y%m%d%H%M%S");
                 if (strcmp(curdate, un_compatexpire) >= 0)
                     DisableServerBackwardsCompatibility();
             }
         }
     }
     if(un_bannedservers != "")
     {
         _Nex_ExtResponseSystem_BannedServers = strzone(un_bannedservers);
         _Nex_ExtResponseSystem_BannedServersNeedsRefresh = 1;
     }
     if(un_emergency_pk3s != "")
     {
         _Nex_ExtResponseSystem_Packs = strzone(un_emergency_pk3s);
         _Nex_ExtResponseSystem_PacksStep = 1;
     }
     if(un_promoted != "")
     {
         _Nex_ExtResponseSystem_PromotedServers = strzone(un_promoted);
         _Nex_ExtResponseSystem_PromotedServersNeedsRefresh = 1;
     }
     if(un_recommended != "")
     {
         _Nex_ExtResponseSystem_RecommendedServers = strzone(un_recommended);
         _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh = 1;
     }
 }
void URI_Get_Callback (float id, float status, string data)
engine callback
Definition at line 288 of file util.qc.
References Curl_URI_Get_Callback(), LOG_INFOF, UpdateNotification_URI_Get_Callback(), URI_GET_CURL, URI_GET_CURL_END, URI_GET_DISCARD, URI_GET_UPDATENOTIFICATION, and url_URI_Get_Callback().
 {
     if(url_URI_Get_Callback(id, status, data))
     {
         // handled
     }
     else if (id == URI_GET_DISCARD)
     {
         // discard
     }
     else if (id >= URI_GET_CURL && id <= URI_GET_CURL_END)
     {
         // sv_cmd curl
         Curl_URI_Get_Callback(id, status, data);
     }
     else if (id == URI_GET_UPDATENOTIFICATION)
     {
         UpdateNotification_URI_Get_Callback(id, status, data);
     }
     else
     {
         LOG_INFOF("Received HTTP request data for an invalid id %d.\n", id);
     }
 }
void (entity)
void (entity me, entity cb)
void (entity , float , float , entity)
void (entity , float)
void (entity , string , string)
Variable Documentation
string _Nex_ExtResponseSystem_Packs
Definition at line 284 of file util.qc.
float _Nex_ExtResponseSystem_PacksStep
Definition at line 285 of file util.qc.
float _Nex_ExtResponseSystem_Queried
Definition at line 281 of file util.qc.
string _Nex_ExtResponseSystem_UpdateTo
Definition at line 282 of file util.qc.
string _Nex_ExtResponseSystem_UpdateToURL
Definition at line 283 of file util.qc.
Referenced by preMenuDraw().
string autocvar_menu_watermark = ""
Definition at line 546 of file util.qc.
string campaign_name_previous
Definition at line 541 of file util.qc.
float campaign_won_previous
Definition at line 542 of file util.qc.
string cvar2_setDependent
Definition at line 116 of file util.qc.
float cvar2Max_setDependent
Definition at line 118 of file util.qc.
float cvar2Min_setDependent
Definition at line 117 of file util.qc.
string cvar3_setDependent
Definition at line 119 of file util.qc.
float cvar3Max_setDependent
Definition at line 121 of file util.qc.
float cvar3Min_setDependent
Definition at line 120 of file util.qc.
string cvar_setDependent
Definition at line 113 of file util.qc.
float cvarMax_setDependent
Definition at line 115 of file util.qc.
float cvarMin_setDependent
Definition at line 114 of file util.qc.
string cvarName
Definition at line 28 of file util.qc.
string cvarNames_Multi
Definition at line 55 of file util.qc.
string cvarString_setDependent
Definition at line 123 of file util.qc.
string cvarValue_setDependent
Definition at line 124 of file util.qc.
bool disabled
Definition at line 126 of file util.qc.
entity firstChild
Definition at line 22 of file util.qc.
Referenced by forAllDescendants().
entity nextSibling
Definition at line 22 of file util.qc.
Referenced by forAllDescendants().
float op_setDependent
Definition at line 122 of file util.qc.
entity parent
Definition at line 22 of file util.qc.
Referenced by forAllDescendants().
entity saveCvars_Callback_ent
Definition at line 97 of file util.qc.
bool sendCvars
Definition at line 751 of file util.qc.
entity winnerDialog
Definition at line 556 of file util.qc.