Xonotic: server/g_models.qc File Reference
g_models.qc File Reference
#include "g_models.qh"
#include "g_subs.qh"
#include <common/net_linked.qh>
#include "../common/triggers/subs.qh"
#include "../common/triggers/triggers.qh"
#include "../common/constants.qh"
#include "../lib/csqcmodel/sv_model.qh"
Macros
#define G_CLIENTMODEL_INIT(ent, sol)
#define G_MODEL_INIT(ent, sol)
Functions
class (BGMScript).string bgmscript
entityclass (BGMScript)
void g_clientmodel_dropbyspawnflags (entity this)
bool g_clientmodel_genericsendentity (entity this, entity to, int sf)
void g_clientmodel_setcolormaptoactivator (entity this, entity actor, entity trigger)
void g_clientmodel_use (entity this, entity actor, entity trigger)
void g_model_dropbyspawnflags (entity this)
void g_model_setcolormaptoactivator (entity this, entity actor, entity trigger)
spawnfunc (misc_gamemodel)
spawnfunc (misc_clientmodel)
spawnfunc (misc_models)
spawnfunc (func_illusionary)
spawnfunc (func_clientillusionary)
spawnfunc (func_static)
spawnfunc (func_wall)
spawnfunc (func_clientwall)
Variables
float modelscale
Macro Definition Documentation
#define G_CLIENTMODEL_INIT (ent, sol)
Value:
if(ent.geomtype) if(autocvar_physics_ode && checkextension("DP_PHYSICS_ODE")) set_movetype(ent, MOVETYPE_PHYSICS); \
    if(!ent.scale) ent.scale = ent.modelscale; \
    SetBrushEntityModel(ent); \
    ent.use = g_clientmodel_use; \
    InitializeEntity(ent, g_clientmodel_dropbyspawnflags, INITPRIO_DROPTOFLOOR); \
    if(!ent.solid) ent.solid = (sol); else if(ent.solid < 0) ent.solid = SOLID_NOT; \
    if(!ent.bgmscriptsustain) ent.bgmscriptsustain = 1; else if(ent.bgmscriptsustain < 0) ent.bgmscriptsustain = 0; \
    Net_LinkEntity(ent, true, 0, g_clientmodel_genericsendentity); \
    ent.default_solid = sol;
Definition at line 177 of file g_models.qc.
Referenced by spawnfunc().
#define G_MODEL_INIT (ent, sol)
Value:
if(ent.geomtype) if(autocvar_physics_ode && checkextension("DP_PHYSICS_ODE")) set_movetype(ent, MOVETYPE_PHYSICS); \
    if(!ent.scale) ent.scale = ent.modelscale; \
    SetBrushEntityModel(ent); \
    ent.use = g_model_setcolormaptoactivator; \
    InitializeEntity(ent, g_model_dropbyspawnflags, INITPRIO_DROPTOFLOOR); \
    if(!ent.solid) ent.solid = (sol); else if(ent.solid < 0) ent.solid = SOLID_NOT;
Definition at line 169 of file g_models.qc.
Referenced by spawnfunc().
Function Documentation
class (BGMScript)
entityclass (BGMScript)
void g_clientmodel_dropbyspawnflags (entity this)
Definition at line 74 of file g_models.qc.
References g_model_dropbyspawnflags(), origin, and vector().
 {
     vector o0;
     o0 = this.origin;
     g_model_dropbyspawnflags(this);
     if(this.origin != o0)
         this.SendFlags |= 2;
 }
bool g_clientmodel_genericsendentity (entity this, entity to, int sf)
Definition at line 83 of file g_models.qc.
References alpha_max, alpha_min, angles, BIT, bound(), colormap, fade_end, fade_start, fade_vertical_offset, floor(), inactive, lip, loddistance1, loddistance2, lodmodelindex0, lodmodelindex1, lodmodelindex2, maxs, mins, modelindex, movedir, origin, scale, skin, solid, WriteAngle(), WriteByte(), WriteCoord(), WriteShort(), and WriteString().
 {
     sf = sf & 0x0F;
     if(this.angles != '0 0 0')
         sf |= 0x10;
     if(this.mins != '0 0 0' || this.maxs != '0 0 0')
         sf |= 0x20;
     if(this.colormap != 0)
         sf |= 0x40;
     if(this.lodmodelindex1)
         sf |= 0x80;
     WriteHeader(MSG_ENTITY, ENT_CLIENT_WALL);
     WriteByte(MSG_ENTITY, sf);
     if(sf & BIT(0))
     {
         if(sf & 0x40)
             WriteShort(MSG_ENTITY, this.colormap);
         WriteByte(MSG_ENTITY, this.skin);
     }
     if(sf & BIT(1))
     {
         WriteCoord(MSG_ENTITY, this.origin.x);
         WriteCoord(MSG_ENTITY, this.origin.y);
         WriteCoord(MSG_ENTITY, this.origin.z);
     }
     if(sf & BIT(2))
     {
         if(sf & 0x10)
         {
             WriteAngle(MSG_ENTITY, this.angles.x);
             WriteAngle(MSG_ENTITY, this.angles.y);
             WriteAngle(MSG_ENTITY, this.angles.z);
         }
     }
     if(sf & BIT(3))
     {
         if(sf & 0x80)
         {
             WriteShort(MSG_ENTITY, this.lodmodelindex0);
             WriteShort(MSG_ENTITY, bound(0, this.loddistance1, 65535));
             WriteShort(MSG_ENTITY, this.lodmodelindex1);
             WriteShort(MSG_ENTITY, bound(0, this.loddistance2, 65535));
             WriteShort(MSG_ENTITY, this.lodmodelindex2);
         }
         else
             WriteShort(MSG_ENTITY, this.modelindex);
         WriteByte(MSG_ENTITY, this.solid);
         WriteShort(MSG_ENTITY, floor(this.scale * 256));
         if(sf & 0x20)
         {
             WriteCoord(MSG_ENTITY, this.mins.x);
             WriteCoord(MSG_ENTITY, this.mins.y);
             WriteCoord(MSG_ENTITY, this.mins.z);
             WriteCoord(MSG_ENTITY, this.maxs.x);
             WriteCoord(MSG_ENTITY, this.maxs.y);
             WriteCoord(MSG_ENTITY, this.maxs.z);
         }
         WriteString(MSG_ENTITY, this.bgmscript);
         if(this.bgmscript != "")
         {
             WriteByte(MSG_ENTITY, floor(this.bgmscriptattack * 64));
             WriteByte(MSG_ENTITY, floor(this.bgmscriptdecay * 64));
             WriteByte(MSG_ENTITY, floor(this.bgmscriptsustain * 255));
             WriteByte(MSG_ENTITY, floor(this.bgmscriptrelease * 64));
             WriteCoord(MSG_ENTITY, this.movedir.x);
             WriteCoord(MSG_ENTITY, this.movedir.y);
             WriteCoord(MSG_ENTITY, this.movedir.z);
             WriteByte(MSG_ENTITY, floor(this.lip * 255));
         }
         WriteByte(MSG_ENTITY, this.fade_start);
         WriteByte(MSG_ENTITY, this.fade_end);
         WriteByte(MSG_ENTITY, this.alpha_max);
         WriteByte(MSG_ENTITY, this.alpha_min);
         WriteByte(MSG_ENTITY, this.inactive);
         WriteShort(MSG_ENTITY, this.fade_vertical_offset);
     }
     return true;
 }
void g_clientmodel_setcolormaptoactivator (entity this, entity actor, entity trigger)
Definition at line 34 of file g_models.qc.
References BIT, and g_model_setcolormaptoactivator().
Referenced by g_clientmodel_use().
 {
     g_model_setcolormaptoactivator(this, actor, trigger);
     this.SendFlags |= (BIT(3) | BIT(0));
 }
void g_clientmodel_use (entity this, entity actor, entity trigger)
Definition at line 40 of file g_models.qc.
References antiwall_flag, default_solid, g_clientmodel_setcolormaptoactivator(), inactive, solid, and SOLID_NOT.
 {
     if (this.antiwall_flag == 1)
     {
         this.inactive = 1;
         this.solid = SOLID_NOT;
     }
     else if (this.antiwall_flag == 2)
     {
         this.inactive = 0;
         this.solid = this.default_solid;
     }
     g_clientmodel_setcolormaptoactivator(this, actor, trigger);
 }
void g_model_dropbyspawnflags (entity this)
Definition at line 55 of file g_models.qc.
References maxs, mins, MOVE_NOMONSTERS, origin, setorigin(), spawnflags, and trace_endpos.
Referenced by g_clientmodel_dropbyspawnflags().
 {
     if((this.spawnflags & 3) == 1) // ALIGN_ORIGIN
     {
         traceline(this.origin, this.origin - '0 0 4096', MOVE_NOMONSTERS, this);
         setorigin(this, trace_endpos);
     }
     else if((this.spawnflags & 3) == 2) // ALIGN_BOTTOM
     {
         tracebox(this.origin, this.mins, this.maxs, this.origin - '0 0 4096', MOVE_NOMONSTERS, this);
         setorigin(this, trace_endpos);
     }
     else if((this.spawnflags & 3) == 3) // ALIGN_ORIGIN | ALIGN_BOTTOM
     {
         traceline(this.origin, this.origin - '0 0 4096', MOVE_NOMONSTERS, this);
         setorigin(this, trace_endpos - '0 0 1' * this.mins.z);
     }
 }
void g_model_setcolormaptoactivator (entity this, entity actor, entity trigger)
Definition at line 20 of file g_models.qc.
References BIT, colormap, floor(), random(), and teamplay.
Referenced by g_clientmodel_setcolormaptoactivator().
 {
     if(teamplay)
     {
         if(actor.team)
             this.colormap = (actor.team - 1) * 0x11;
         else
             this.colormap = 0x00;
     }
     else
         this.colormap = floor(random() * 256);
     this.colormap |= BIT(10); // RENDER_COLORMAPPED
 }
spawnfunc (misc_gamemodel)
Definition at line 189 of file g_models.qc.
References angles, G_MODEL_INIT, and SOLID_NOT.
 { this.angles_x = -this.angles.x; G_MODEL_INIT      (this, SOLID_NOT) } // model entity
spawnfunc (misc_clientmodel)
Definition at line 190 of file g_models.qc.
References angles, G_CLIENTMODEL_INIT, and SOLID_NOT.
 { this.angles_x = -this.angles.x; G_CLIENTMODEL_INIT(this, SOLID_NOT) } // model entity
spawnfunc (misc_models)
Definition at line 191 of file g_models.qc.
References angles, G_MODEL_INIT, and SOLID_NOT.
 { this.angles_x = -this.angles.x; G_MODEL_INIT      (this, SOLID_NOT) } // DEPRECATED old compat entity with confusing name, do not use
spawnfunc (func_illusionary)
Definition at line 194 of file g_models.qc.
References G_MODEL_INIT, and SOLID_NOT.
 { G_MODEL_INIT      (this, SOLID_NOT) } // Q1 name (WARNING: MISPREDICTED)
spawnfunc (func_clientillusionary)
Definition at line 195 of file g_models.qc.
References G_CLIENTMODEL_INIT, and SOLID_NOT.
 { G_CLIENTMODEL_INIT(this, SOLID_NOT) } // brush entity
spawnfunc (func_static)
Definition at line 196 of file g_models.qc.
References G_MODEL_INIT, and SOLID_NOT.
 { G_MODEL_INIT      (this, SOLID_NOT) } // DEPRECATED old alias name from some other game
spawnfunc (func_wall)
Definition at line 199 of file g_models.qc.
References G_MODEL_INIT, and SOLID_BSP.
 { G_MODEL_INIT      (this, SOLID_BSP) } // Q1 name
spawnfunc (func_clientwall)
Definition at line 200 of file g_models.qc.
References G_CLIENTMODEL_INIT, and SOLID_BSP.
 { G_CLIENTMODEL_INIT(this, SOLID_BSP) } // brush entity (WARNING: MISPREDICTED)
Variable Documentation
float modelscale
Definition at line 18 of file g_models.qc.