Xonotic: common/items/item/jetpack.qh File Reference
jetpack.qh File Reference
#include "ammo.qh"
#include "powerup.qh"
Classes
class Jetpack
class JetpackRegen
Functions
REGISTER_ITEM (Jetpack, Powerup)
REGISTER_ITEM (JetpackFuel, Ammo)
REGISTER_ITEM (JetpackRegen, JetpackRegen)
Variables
int m_itemid
Function Documentation
REGISTER_ITEM (Jetpack , Powerup)
Definition at line 30 of file jetpack.qh.
References entity(), GetResource(), IT_JETPACK, ITEM_FLAG_NORMAL, Item_Model(), m_itemid, m_name, MODEL, netname, PROPERTY, RES_FUEL, SetResourceExplicit(), spawnflags, and SPAWNFUNC_ITEM.
{
     this.m_canonical_spawnfunc = "item_jetpack";
 #ifdef GAMEQC
     this.spawnflags = ITEM_FLAG_NORMAL;
     this.m_model                =   MDL_Jetpack_ITEM;
     this.m_itemid               =   IT_JETPACK;
 #endif
     this.netname                =   "jetpack";
     this.m_name                 =   _("Jetpack");
     this.m_icon                 =   "jetpack";
     this.m_color                =   '0.5 0.5 0.5';
     this.m_waypoint             =   _("Jetpack");
     this.m_waypointblink        =   2;
 #ifdef SVQC
     this.m_botvalue             =   3000;
     this.m_pickupevalfunc       =   ammo_pickupevalfunc;
     this.m_iteminit             =   powerup_jetpack_init;
 #endif
 }
REGISTER_ITEM (JetpackFuel , Ammo)
Definition at line 64 of file jetpack.qh.
References IT_FUEL, ITEM_FLAG_NORMAL, ITEM_FLAG_RESOURCE, Item_Model(), m_itemid, m_name, MODEL, netname, spawnflags, and SPAWNFUNC_ITEM.
{
     this.m_canonical_spawnfunc = "item_fuel";
 #ifdef GAMEQC
     this.spawnflags = ITEM_FLAG_NORMAL | ITEM_FLAG_RESOURCE;
     this.m_model    =   MDL_JetpackFuel_ITEM;
 #endif
     this.netname    =   "fuel";
     this.m_name     =   _("fuel");
     this.m_icon     =   "ammo_fuel";
 #ifdef SVQC
     this.m_botvalue =   2000;
     this.m_itemid   =   IT_FUEL;
     this.m_iteminit =   ammo_fuel_init;
 #endif
 }
REGISTER_ITEM (JetpackRegen , JetpackRegen)
Definition at line 89 of file jetpack.qh.
References IT_FUEL_REGEN, ITEM_FLAG_NORMAL, m_itemid, m_name, netname, spawnflags, and SPAWNFUNC_ITEM.
{
     this.m_canonical_spawnfunc = "item_fuel_regen";
 #ifdef GAMEQC
     this.spawnflags = ITEM_FLAG_NORMAL;
     this.m_model                =   MDL_JetpackRegen_ITEM;
 #endif
     this.netname                =   "fuel_regen";
     this.m_name                 =   _("Fuel regenerator");
     this.m_icon                 =   "fuelregen";
     this.m_color                =   '1 0.5 0';
     this.m_waypoint             =   _("Fuel regen");
     this.m_waypointblink        =   2;
 #ifdef SVQC
     this.m_botvalue             =   3000;
     this.m_itemid               =   IT_FUEL_REGEN;
     this.m_pickupevalfunc       =   ammo_pickupevalfunc;
 #endif
 }
Variable Documentation
int m_itemid
Definition at line 11 of file jetpack.qh.
Referenced by REGISTER_ITEM().