Xonotic: server/weapons/weaponsystem.qc File Reference
weaponsystem.qc File Reference
#include "weaponsystem.qh"
#include "selection.qh"
#include "../command/common.qh"
#include "../mutators/all.qh"
#include "../round_handler.qh"
#include <common/t_items.qh>
#include <common/animdecide.qh>
#include <common/constants.qh>
#include <common/monsters/all.qh>
#include <common/notifications/all.qh>
#include <common/util.qh>
#include <common/weapons/all.qh>
#include <common/state.qh>
#include <lib/csqcmodel/sv_model.qh>
Functions
void CL_ExteriorWeaponentity_Think (entity this)
void CL_SpawnWeaponentity (entity actor,.entity weaponentity)
vector CL_Weapon_GetShotOrg (int wpn)
bool CL_Weaponentity_CustomizeEntityForClient (entity this, entity client)
void CL_Weaponentity_Think (entity this)
bool forbidWeaponUse (entity player)
void W_AttachToShotorg (entity actor, entity flash, vector offset)
void w_clear (Weapon thiswep, entity actor,.entity weaponentity, int fire)
void W_DecreaseAmmo (Weapon wep, entity actor, float ammo_use)
void W_DropEvent (.void(Weapon, entity actor) event, entity player, float weapon_type, entity weapon_item)
void w_ready (Weapon thiswep, entity actor,.entity weaponentity, int fire)
void W_Reload (entity actor, float sent_ammo_min, Sound sent_sound)
void W_ReloadedAndReady (Weapon thiswep, entity actor,.entity weaponentity, int fire)
void W_WeaponFrame (Player actor)
float W_WeaponRateFactor (entity this)
float W_WeaponSpeedFactor (entity this)
bool weapon_prepareattack (Weapon thiswep, entity actor,.entity weaponentity, bool secondary, float attacktime)
bool weapon_prepareattack_check (Weapon thiswep, entity actor,.entity weaponentity, bool secondary, float attacktime)
bool weapon_prepareattack_checkammo (Weapon thiswep, entity actor, bool secondary)
void weapon_prepareattack_do (entity actor,.entity weaponentity, bool secondary, float attacktime)
void weapon_thinkf (entity actor,.entity weaponentity, WFRAME fr, float t, void(Weapon thiswep, entity actor,.entity weaponentity, int fire) func)
void wframe_send (entity actor, entity weaponentity, vector a, bool restartanim)
Variables
bool hook_switchweapon
float m_alpha
float prevdryfire
float prevwarntime
float race_penalty
float reload_ammo_amount
float reload_ammo_min
float reload_complain
string reload_sound
float reload_time
int state
float weapon_frametime
entity weaponentity_fld
Function Documentation
void CL_ExteriorWeaponentity_Think (entity this)
Definition at line 108 of file weaponsystem.qc.
References alpha, colormap, deadflag, default_player_alpha, default_weapon_alpha, dmg, EF_LOWPRECISION, effects, EFMASK_CHEAP, gettagindex, glowmod, IS_DEAD, model, nextthink, owner, PS, strcat(), tag_entity, tag_index, time, W_Model(), weaponentity_glowmod(), and weaponname.
Referenced by CL_SpawnWeaponentity().
 {
     this.nextthink = time;
     if (this.owner.exteriorweaponentity != this)
     {
         remove(this);
         return;
     }
     if (IS_DEAD(this.owner))
     {
         this.model = "";
         return;
     }
     if (this.weaponname != this.owner.weaponname || this.dmg != this.owner.modelindex
         || this.deadflag != this.owner.deadflag)
     {
         this.weaponname = this.owner.weaponname;
         this.dmg = this.owner.modelindex;
         this.deadflag = this.owner.deadflag;
         if (this.owner.weaponname != "")
         {
             _setmodel(this, W_Model(strcat("v_", this.owner.weaponname, ".md3")));
             setsize(this, '0 0 0', '0 0 0');
         }
         else this.model = "";
         int tag_found;
         if ((tag_found = gettagindex(this.owner, "tag_weapon")))
         {
             this.tag_index = tag_found;
             this.tag_entity = this.owner;
         }
         else
         {
             setattachment(this, this.owner, "bip01 r hand");
         }
     }
     this.effects = this.owner.effects;
     this.effects |= EF_LOWPRECISION;
     this.effects = this.effects & EFMASK_CHEAP;  // eat performance
     if (this.owner.alpha == default_player_alpha) this.alpha = default_weapon_alpha;
     else if (this.owner.alpha != 0) this.alpha = this.owner.alpha;
     else this.alpha = 1;
     Weapon wep = PS(this.owner).m_weapon;
     if (wep) this.glowmod = weaponentity_glowmod(wep, this.owner.clientcolors);
     this.colormap = this.owner.colormap;
     CSQCMODEL_AUTOUPDATE(this);
 }
void CL_SpawnWeaponentity (entity actor, .entity weaponentity)
Definition at line 160 of file weaponsystem.qc.
References CL_ExteriorWeaponentity_Think(), CL_Weaponentity_CustomizeEntityForClient(), CL_Weaponentity_Think(), entity(), exteriorweaponentity, setcefc, setmodel, setthink, SOLID_NOT, time, and weaponentities.
Referenced by PutClientInServer().
 {
     entity view = actor.(weaponentity) = new(weaponentity);
     view.solid = SOLID_NOT;
     view.owner = actor;
     setmodel(view, MDL_Null);  // precision set when changed
     setorigin(view, '0 0 0');
     view.weaponentity_fld = weaponentity;
     setthink(view, CL_Weaponentity_Think);
     view.nextthink = time;
     view.viewmodelforclient = actor;
     setcefc(view, CL_Weaponentity_CustomizeEntityForClient);
     if (weaponentity == weaponentities[0])
     {
         entity exterior = actor.exteriorweaponentity = new(exteriorweaponentity);
         exterior.solid = SOLID_NOT;
         exterior.owner = actor;
         setorigin(exterior, '0 0 0');
         setthink(exterior, CL_ExteriorWeaponentity_Think);
         exterior.nextthink = time;
         CSQCMODEL_AUTOINIT(exterior);
     }
 }
vector CL_Weapon_GetShotOrg (int wpn)
Definition at line 50 of file weaponsystem.qc.
References CL_WeaponEntity_SetModel(), entity(), spawn(), vector, and Weapons_from.
Referenced by GrappleHookInit().
 {
     entity wi = Weapons_from(wpn);
     entity e = spawn();
     CL_WeaponEntity_SetModel(e, wi.mdl, false);
     vector ret = e.movedir;
     CL_WeaponEntity_SetModel(e, "", false);
     remove(e);
     return ret;
 }
bool CL_Weaponentity_CustomizeEntityForClient (entity this, entity client)
Definition at line 43 of file weaponsystem.qc.
References IS_SPEC, owner, and viewmodelforclient.
Referenced by CL_SpawnWeaponentity().
 {
     this.viewmodelforclient = this.owner;
     if (IS_SPEC(client) && client.enemy == this.owner) this.viewmodelforclient = client;
     return true;
 }
void CL_Weaponentity_Think (entity this)
Definition at line 64 of file weaponsystem.qc.
References alpha, anim_idle, CL_WeaponEntity_SetModel(), deadflag, default_player_alpha, default_weapon_alpha, dmg, effects, frame, intermission_running, IS_DEAD, m_alpha, model, nextthink, owner, time, weaponchild, weaponentity_fld, and weaponname.
Referenced by CL_SpawnWeaponentity().
 {
     this.nextthink = time;
     if (intermission_running) this.frame = this.anim_idle.x;
     .entity weaponentity = this.weaponentity_fld;
     if (this.owner.(weaponentity) != this)
     {
         // owner has new gun; remove old one
         if (this.weaponchild) remove(this.weaponchild);
         remove(this);
         return;
     }
     if (IS_DEAD(this.owner))
     {
         // owner died; disappear
         this.model = "";
         if (this.weaponchild) this.weaponchild.model = "";
         return;
     }
     if (this.weaponname != this.owner.weaponname
         || this.dmg != this.owner.modelindex
         || this.deadflag != this.owner.deadflag)
     {
         // owner changed weapons; update appearance
         this.weaponname = this.owner.weaponname;
         this.dmg = this.owner.modelindex;
         this.deadflag = this.owner.deadflag;
         CL_WeaponEntity_SetModel(this, this.owner.weaponname, true);
     }
     this.alpha = -1;  // TODO: don't render this entity at all
     if (this.owner.alpha == default_player_alpha) this.m_alpha = default_weapon_alpha;
     else if (this.owner.alpha != 0) this.m_alpha = this.owner.alpha;
     else this.m_alpha  = 1;
     if (this.weaponchild)
     {
         this.weaponchild.alpha = this.alpha;
         this.weaponchild.effects = this.effects;
     }
 }
bool forbidWeaponUse (entity player)
Definition at line 406 of file weaponsystem.qc.
References autocvar_sv_ready_restart_after_countdown, game_starttime, gameover, round_handler_IsActive, round_handler_IsRoundStarted, and time.
Referenced by FireGrapplingHook(), IMPULSE(), vehicles_touch(), W_SwitchWeapon(), and W_WeaponFrame().
 {
     if (time < game_starttime && !autocvar_sv_ready_restart_after_countdown) return true;
     if (round_handler_IsActive() && !round_handler_IsRoundStarted()) return true;
     if (player.player_blocked) return true;
     if (gameover) return true;
     if (STAT(FROZEN, player)) return true;
     if (player.weapon_blocked) return true;
     return false;
 }
void W_AttachToShotorg (entity actor, entity flash, vector offset)
Definition at line 595 of file weaponsystem.qc.
References copyentity(), entity(), gettagindex, random(), spawn(), and weaponentities.
 {
     .entity weaponentity = weaponentities[0];
     flash.owner = actor;
     flash.angles_z = random() * 360;
     entity view = actor.(weaponentity);
     entity exterior = actor.exteriorweaponentity;
     if (gettagindex(view, "shot")) setattachment(flash, view, "shot");
     else setattachment(flash, view, "tag_shot");
     setorigin(flash, offset);
     entity xflash = spawn();
     copyentity(flash, xflash);
     flash.viewmodelforclient = actor;
     if (view.oldorigin.x > 0)
     {
         setattachment(xflash, exterior, "");
         setorigin(xflash, view.oldorigin + offset);
     }
     else
     {
         if (gettagindex(exterior, "shot")) setattachment(xflash, exterior, "shot");
         else setattachment(xflash, exterior, "tag_shot");
         setorigin(xflash, offset);
     }
 }
void w_clear (Weapon thiswep, entity actor, .entity weaponentity, int fire)
Definition at line 187 of file weaponsystem.qc.
References effects, entity(), PS, state, and WS_CLEAR.
Referenced by W_WeaponFrame().
 {
     PS(actor).m_weapon = WEP_Null;
     PS(actor).m_switchingweapon = WEP_Null;
     entity this = actor.(weaponentity);
     if (this)
     {
         this.state = WS_CLEAR;
         this.effects = 0;
     }
 }
void W_DecreaseAmmo (Weapon wep, entity actor, float ammo_use)
Definition at line 626 of file weaponsystem.qc.
References Weapon::ammo_field, ammo_none, backtrace, GetAmmoPicture(), IT_UNLIMITED_WEAPON_AMMO, MUTATOR_CALLHOOK, Weapon::netname, PS, and W_DecreaseAmmo().
Referenced by W_DecreaseAmmo().
 {
     if (MUTATOR_CALLHOOK(W_DecreaseAmmo, actor)) return;
     if ((actor.items & IT_UNLIMITED_WEAPON_AMMO) && !wep.reloading_ammo) return;
     // if this weapon is reloadable, decrease its load. Else decrease the player's ammo
     if (wep.reloading_ammo)
     {
         actor.clip_load -= ammo_use;
         actor.(weapon_load[PS(actor).m_weapon.m_id]) = actor.clip_load;
     }
     else if (wep.ammo_field != ammo_none)
     {
         actor.(wep.ammo_field) -= ammo_use;
         if (actor.(wep.ammo_field) < 0)
         {
             backtrace(sprintf(
                 "W_DecreaseAmmo(%.2f): '%s' subtracted too much %s from '%s', resulting with '%.2f' left... "
                 "Please notify Samual immediately with a copy of this backtrace!\n",
                 ammo_use,
                 wep.netname,
                 GetAmmoPicture(wep.ammo_field),
                 actor.netname,
                 actor.(wep.ammo_field)
                              ));
         }
     }
 }
void W_DropEvent (.void(Weapon, entity actor) event, entity player, float weapon_type, entity weapon_item)
Definition at line 772 of file weaponsystem.qc.
References weapon_dropevent_item, and Weapons_from.
Referenced by W_ThrowNewWeapon().
 {
     Weapon w = Weapons_from(weapon_type);
     weapon_dropevent_item = weapon_item;
     w.event(w, player);
 }
void w_ready (Weapon thiswep, entity actor, .entity weaponentity, int fire)
Definition at line 199 of file weaponsystem.qc.
References entity(), state, weapon_thinkf(), and WS_READY.
Referenced by W_ReloadedAndReady(), W_WeaponFrame(), and weapon_thinkf().
 {
     entity this = actor.(weaponentity);
     if (this) this.state = WS_READY;
     weapon_thinkf(actor, weaponentity, WFRAME_IDLE, 1000000, w_ready);
 }
void W_Reload (entity actor, float sent_ammo_min, Sound sent_sound)
Definition at line 692 of file weaponsystem.qc.
References _sound, ammo_none, ATTEN_NORM, CH_WEAPON_SINGLE, entity(), IS_REAL_CLIENT, IT_UNLIMITED_WEAPON_AMMO, LOG_TRACE(), MUTATOR_CALLHOOK, play2(), PS, SND, Sound_fixpath, Weapon::spawnflags, sprint(), state, strcat(), strunzone(), strzone(), TC, time, VOL_BASE, W_Reload(), W_ReloadedAndReady(), W_SwitchToOtherWeapon(), weapon_thinkf(), weaponentities, WEP_FLAG_RELOADABLE, wframe, Weapon::wr_checkammo1(), Weapon::wr_checkammo2(), and WS_READY.
Referenced by W_Reload().
 {
     TC(Sound, sent_sound);
     .entity weaponentity = weaponentities[0];
     // set global values to work with
     Weapon e = PS(actor).m_weapon;
     if (MUTATOR_CALLHOOK(W_Reload, actor)) return;
     actor.reload_ammo_min = sent_ammo_min;
     actor.reload_ammo_amount = e.reloading_ammo;
     actor.reload_time = e.reloading_time;
     if (actor.reload_sound) strunzone(actor.reload_sound);
     actor.reload_sound = strzone(Sound_fixpath(sent_sound));
     // don't reload weapons that don't have the RELOADABLE flag
     if (!(e.spawnflags & WEP_FLAG_RELOADABLE))
     {
         LOG_TRACE(
             "Warning: Attempted to reload a weapon that does not have the WEP_FLAG_RELOADABLE flag. Fix your code!\n");
         return;
     }
     // return if reloading is disabled for this weapon
     if (!actor.reload_ammo_amount) return;
     // our weapon is fully loaded, no need to reload
     if (actor.clip_load >= actor.reload_ammo_amount) return;
     // no ammo, so nothing to load
     if (actor.ammo_field != ammo_none)
     {
         if (!actor.(actor.ammo_field) && actor.reload_ammo_min)
         {
             if (!(actor.items & IT_UNLIMITED_WEAPON_AMMO))
             {
                 if (IS_REAL_CLIENT(actor) && actor.reload_complain < time)
                 {
                     play2(actor, SND(UNAVAILABLE));
                     sprint(actor, strcat("You don't have enough ammo to reload the ^2", PS(actor).m_weapon.m_name, "\n"));
                     actor.reload_complain = time + 1;
                 }
                 // switch away if the amount of ammo is not enough to keep using this weapon
                 Weapon w = PS(actor).m_weapon;
                 if (!(w.wr_checkammo1(w, actor) + w.wr_checkammo2(w, actor)))
                 {
                     actor.clip_load = -1;  // reload later
                     W_SwitchToOtherWeapon(actor);
                 }
                 return;
             }
         }
     }
     entity this = actor.(weaponentity);
     if (this)
     {
         if (this.wframe == WFRAME_RELOAD) return;
         // allow switching away while reloading, but this will cause a new reload!
         this.state = WS_READY;
     }
     // now begin the reloading process
     _sound(actor, CH_WEAPON_SINGLE, actor.reload_sound, VOL_BASE, ATTEN_NORM);
     // do not set ATTACK_FINISHED in reload code any more. This causes annoying delays if eg: You start reloading a weapon,
     // then quickly switch to another weapon and back. Reloading is canceled, but the reload delay is still there,
     // so your weapon is disabled for a few seconds without reason
     // ATTACK_FINISHED(actor, slot) = max(time, ATTACK_FINISHED(actor, slot)) + actor.reload_time + 1;
     weapon_thinkf(actor, weaponentity, WFRAME_RELOAD, actor.reload_time, W_ReloadedAndReady);
     if (actor.clip_load < 0) actor.clip_load = 0;
     actor.old_clip_load = actor.clip_load;
     actor.clip_load = actor.(weapon_load[PS(actor).m_weapon.m_id]) = -1;
 }
void W_ReloadedAndReady (Weapon thiswep, entity actor, .entity weaponentity, int fire)
Definition at line 662 of file weaponsystem.qc.
References ammo_none, IT_UNLIMITED_WEAPON_AMMO, min(), PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PS, w_ready(), and Weapons_from.
Referenced by W_Reload().
 {
     // finish the reloading process, and do the ammo transfer
     actor.clip_load = actor.old_clip_load;  // restore the ammo counter, in case we still had ammo in the weapon before reloading
     // if the gun uses no ammo, max out weapon load, else decrease ammo as we increase weapon load
     if (!actor.reload_ammo_min || actor.items & IT_UNLIMITED_WEAPON_AMMO || actor.ammo_field == ammo_none)
     {
         actor.clip_load = actor.reload_ammo_amount;
     }
     else
     {
         // make sure we don't add more ammo than we have
         float load = min(actor.reload_ammo_amount - actor.clip_load, actor.(actor.ammo_field));
         actor.clip_load += load;
         actor.(actor.ammo_field) -= load;
     }
     actor.(weapon_load[PS(actor).m_weapon.m_id]) = actor.clip_load;
     // do not set ATTACK_FINISHED in reload code any more. This causes annoying delays if eg: You start reloading a weapon,
     // then quickly switch to another weapon and back. Reloading is canceled, but the reload delay is still there,
     // so your weapon is disabled for a few seconds without reason
     // ATTACK_FINISHED(actor, slot) -= actor.reload_time - 1;
     Weapon wpn = Weapons_from(PS(actor).m_weapon.m_id);
     w_ready(wpn, actor, weaponentity, PHYS_INPUT_BUTTON_ATCK(actor) | (PHYS_INPUT_BUTTON_ATCK2(actor) << 1));
 }
void W_WeaponFrame (Player actor)
Definition at line 419 of file weaponsystem.qc.
References Weapon::ammo_field, ATTACK_FINISHED, ATTN_NORM, bprint(), CH_WEAPON_SINGLE, entity(), forbidWeaponUse(), frametime, INDEPENDENT_ATTACK_FINISHED, LOG_WARNINGF, Weapon::mdl, Client::netname, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_HOOK, PS, sound, Weapon::spawnflags, state, TC, time, v_forward, v_right, v_up, vector, VOL_BASE, w_clear(), w_getbestweapon, w_ready(), W_SwitchWeapon(), W_SwitchWeapon_Force(), W_TICSPERFRAME, weapon_thinkf(), weaponentities, weaponslot(), WEP_FLAG_RELOADABLE, WEPSET, WepSet_FromWeapon, Weapon::wr_gonethink(), Weapon::wr_setup(), Weapon::wr_think(), WS_CLEAR, WS_DROP, WS_INUSE, WS_RAISE, and WS_READY.
 {
     TC(Player, actor);
     TC(PlayerState, PS(actor));
     .entity weaponentity = weaponentities[0];  // TODO: unhardcode
     entity this = actor.(weaponentity);
     if (frametime) actor.weapon_frametime = frametime;
     if (!this || actor.health < 1) return;  // Dead player can't use weapons and injure impulse commands
     if (forbidWeaponUse(actor))
     {
         if (actor.(weaponentity).state != WS_CLEAR)
         {
             Weapon wpn = PS(actor).m_weapon;
             w_ready(wpn, actor, weaponentity, PHYS_INPUT_BUTTON_ATCK(actor) | (PHYS_INPUT_BUTTON_ATCK2(actor) << 1));
             return;
         }
     }
     if (PS(actor).m_switchweapon == WEP_Null)
     {
         PS(actor).m_weapon = WEP_Null;
         PS(actor).m_switchingweapon = WEP_Null;
         this.state = WS_CLEAR;
         actor.weaponname = "";
         // actor.items &= ~IT_AMMO;
         return;
     }
     makevectors(actor.v_angle);
     vector fo = v_forward;  // save them in case the weapon think functions change it
     vector ri = v_right;
     vector up = v_up;
     // Change weapon
     if (PS(actor).m_weapon != PS(actor).m_switchweapon)
     {
         switch (this.state)
         {
             default:
                 LOG_WARNINGF("unhandled weaponentity (%i) state for player (%i): %d\n", this, actor, this.state);
                 break;
             case WS_INUSE:
             case WS_RAISE:
                 break;
             case WS_CLEAR:
             {
                 // end switching!
                 Weapon newwep = PS(actor).m_switchweapon;
                 PS(actor).m_switchingweapon = newwep;
                 // the two weapon entities will notice this has changed and update their models
                 PS(actor).m_weapon = newwep;
                 actor.weaponname = newwep.mdl;
                 actor.bulletcounter = 0;
                 actor.ammo_field = newwep.ammo_field;
                 newwep.wr_setup(newwep, actor);
                 this.state = WS_RAISE;
                 // set our clip load to the load of the weapon we switched to, if it's reloadable
                 if ((newwep.spawnflags & WEP_FLAG_RELOADABLE) && newwep.reloading_ammo)  // prevent accessing undefined cvars
                 {
                     actor.clip_load = actor.(weapon_load[PS(actor).m_switchweapon.m_id]);
                     actor.clip_size = newwep.reloading_ammo;
                 }
                 else
                 {
                     actor.clip_load = actor.clip_size = 0;
                 }
                 weapon_thinkf(actor, weaponentity, WFRAME_IDLE, newwep.switchdelay_raise, w_ready);
                 break;
             }
             case WS_DROP:
             {
                 // in dropping phase we can switch at any time
                 PS(actor).m_switchingweapon = PS(actor).m_switchweapon;
                 break;
             }
             case WS_READY:
             {
                 // start switching!
                 PS(actor).m_switchingweapon = PS(actor).m_switchweapon;
                 entity oldwep = PS(actor).m_weapon;
                 // set up weapon switch think in the future, and start drop anim
                 if (INDEPENDENT_ATTACK_FINISHED || ATTACK_FINISHED(actor, weaponslot(weaponentity)) <= time + actor.weapon_frametime * 0.5)
                 {
                     sound(actor, CH_WEAPON_SINGLE, SND_WEAPON_SWITCH, VOL_BASE, ATTN_NORM);
                     this.state = WS_DROP;
                     weapon_thinkf(actor, weaponentity, WFRAME_DONTCHANGE, oldwep.switchdelay_drop, w_clear);
                 }
                 break;
             }
         }
     }
     // LordHavoc: network timing test code
     // if (actor.button0)
     //  print(ftos(frametime), " ", ftos(time), " >= ", ftos(ATTACK_FINISHED(actor, slot)), " >= ", ftos(this.weapon_nextthink), "\n");
     Weapon w = PS(actor).m_weapon;
     // call the think code which may fire the weapon
     // and do so multiple times to resolve framerate dependency issues if the
     // server framerate is very low and the weapon fire rate very high
     for (int c = 0; c < W_TICSPERFRAME; ++c)
     {
         if (w != WEP_Null && !(actor.weapons & WepSet_FromWeapon(w)))
         {
             if (PS(actor).m_weapon == PS(actor).m_switchweapon) W_SwitchWeapon_Force(actor, w_getbestweapon(actor));
             w = WEP_Null;
         }
         v_forward = fo;
         v_right = ri;
         v_up = up;
         bool block_weapon = false;
         {
             bool key_pressed = PHYS_INPUT_BUTTON_HOOK(actor) && !actor.vehicle;
             Weapon off = actor.offhand;
             if (off && !(actor.weapons & WEPSET(HOOK)))
             {
                 if (off.offhand_think) off.offhand_think(off, actor, key_pressed);
             }
             else
             {
                 if (key_pressed && PS(actor).m_switchweapon != WEP_HOOK && !actor.hook_switchweapon)
                     W_SwitchWeapon(actor, WEP_HOOK);
                 actor.hook_switchweapon = key_pressed;
                 Weapon h = WEP_HOOK;
                 block_weapon = (PS(actor).m_weapon == h && (PHYS_INPUT_BUTTON_ATCK(actor) || key_pressed));
                 h.wr_think(h, actor, weaponentity, block_weapon ? 1 : 0);
             }
         }
         v_forward = fo;
         v_right = ri;
         v_up = up;
         if (!block_weapon)
         {
             Weapon e = PS(actor).m_weapon;
             TC(Weapon, e);
             if (w != WEP_Null)
             {
                 e.wr_think(e, actor, weaponentity, PHYS_INPUT_BUTTON_ATCK(actor) | (PHYS_INPUT_BUTTON_ATCK2(actor) << 1));
             }
             else if (e)
             {
                 e.wr_gonethink(e, actor);
             }
         }
         if (time + actor.weapon_frametime * 0.5 >= this.weapon_nextthink)
         {
             if (this.weapon_think)
             {
                 v_forward = fo;
                 v_right = ri;
                 v_up = up;
                 Weapon wpn = PS(actor).m_weapon;
                 this.weapon_think(wpn, actor, weaponentity,
                     PHYS_INPUT_BUTTON_ATCK(actor) | (PHYS_INPUT_BUTTON_ATCK2(actor) << 1));
             }
             else
             {
                 bprint("\{1}^1ERROR: undefined weapon think function for ", actor.netname, "\n");
             }
         }
     }
 }
float W_WeaponRateFactor (entity this)
Definition at line 22 of file weaponsystem.qc.
References g_weaponratefactor, M_ARGV, and MUTATOR_CALLHOOK.
Referenced by weapon_prepareattack_do(), and weapon_thinkf().
 {
     float t = 1.0 / g_weaponratefactor;
     MUTATOR_CALLHOOK(WeaponRateFactor, t, this);
     t = M_ARGV(0, float);
     return t;
 }
float W_WeaponSpeedFactor (entity this)
Definition at line 32 of file weaponsystem.qc.
References g_weaponspeedfactor, M_ARGV, and MUTATOR_CALLHOOK.
Referenced by bot_aim(), and W_CalculateProjectileVelocity().
 {
     float t = 1.0 * g_weaponspeedfactor;
     MUTATOR_CALLHOOK(WeaponSpeedFactor, t, this);
     t = M_ARGV(0, float);
     return t;
 }
bool weapon_prepareattack (Weapon thiswep, entity actor, .entity weaponentity, bool secondary, float attacktime)
Definition at line 313 of file weaponsystem.qc.
References weapon_prepareattack_check(), and weapon_prepareattack_do().
 {
     if (weapon_prepareattack_check(thiswep, actor, weaponentity, secondary, attacktime))
     {
         weapon_prepareattack_do(actor, weaponentity, secondary, attacktime);
         return true;
     }
     return false;
 }
bool weapon_prepareattack_check (Weapon thiswep, entity actor, .entity weaponentity, bool secondary, float attacktime)
Definition at line 263 of file weaponsystem.qc.
References ATTACK_FINISHED, entity(), game_starttime, NULL, PS, state, time, TIMEOUT_ACTIVE, timeout_status, weapon_prepareattack_checkammo(), weaponslot(), and WS_READY.
Referenced by weapon_prepareattack().
 {
     if (actor.weaponentity == NULL) return true;
     if (!weapon_prepareattack_checkammo(thiswep, actor, secondary)) return false;
     // if sv_ready_restart_after_countdown is set, don't allow the player to shoot
     // if all players readied up and the countdown is running
     if (time < game_starttime || time < actor.race_penalty) return false;
     if (timeout_status == TIMEOUT_ACTIVE)  // don't allow the player to shoot while game is paused
         return false;
     // do not even think about shooting if switching
     if (PS(actor).m_switchweapon != PS(actor).m_weapon) return false;
     if (attacktime >= 0)
     {
         int slot = weaponslot(weaponentity);
         // don't fire if previous attack is not finished
         if (ATTACK_FINISHED(actor, slot) > time + actor.weapon_frametime * 0.5) return false;
         entity this = actor.(weaponentity);
         // don't fire while changing weapon
         if (this.state != WS_READY) return false;
     }
     return true;
 }
bool weapon_prepareattack_checkammo (Weapon thiswep, entity actor, bool secondary)
Definition at line 208 of file weaponsystem.qc.
References ammo, ATTEN_NORM, CH_WEAPON_A, FOREACH_ENTITY_ENT, IT_UNLIMITED_WEAPON_AMMO, Weapon::m_id, owner, PS, sound, time, VOL_BASE, W_SwitchToOtherWeapon(), WEP_CVAR, Weapon::wr_checkammo1(), and Weapon::wr_checkammo2().
Referenced by weapon_prepareattack_check().
 {
     if ((actor.items & IT_UNLIMITED_WEAPON_AMMO)) return true;
     bool ammo = false;
     if (secondary) ammo = thiswep.wr_checkammo2(thiswep, actor);
     else ammo = thiswep.wr_checkammo1(thiswep, actor);
     if (ammo) return true;
     // always keep the Mine Layer if we placed mines, so that we can detonate them
     if (thiswep == WEP_MINE_LAYER)
     {
         FOREACH_ENTITY_ENT(owner, actor,
         {
             if(it.classname != "mine") continue;
             if(it.owner == actor) return false;
         });
     }
     if (thiswep == WEP_SHOTGUN)
         if (!secondary && WEP_CVAR(shotgun, secondary) == 1) return false;           // no clicking, just allow
     if (thiswep == PS(actor).m_switchweapon && time - actor.prevdryfire > 1) // only play once BEFORE starting to switch weapons
     {
         sound(actor, CH_WEAPON_A, SND_DRYFIRE, VOL_BASE, ATTEN_NORM);
         actor.prevdryfire = time;
     }
     // check if the other firing mode has enough ammo
     bool ammo_other = false;
     if (secondary) ammo_other = thiswep.wr_checkammo1(thiswep, actor);
     else ammo_other = thiswep.wr_checkammo2(thiswep, actor);
     if (ammo_other)
     {
         if (time - actor.prevwarntime > 1)
         {
             Send_Notification(
                 NOTIF_ONE,
                 actor,
                 MSG_MULTI,
                 ITEM_WEAPON_PRIMORSEC,
                 thiswep.m_id,
                 secondary,
                 (1 - secondary)
                              );
         }
         actor.prevwarntime = time;
     }
     else  // this weapon is totally unable to fire, switch to another one
     {
         W_SwitchToOtherWeapon(actor);
     }
     return false;
 }
void weapon_prepareattack_do (entity actor, .entity weaponentity, bool secondary, float attacktime)
Definition at line 290 of file weaponsystem.qc.
References ATTACK_FINISHED, entity(), min(), NULL, state, time, W_WeaponRateFactor(), weaponslot(), and WS_INUSE.
Referenced by weapon_prepareattack().
 {
     entity this = actor.(weaponentity);
     if (this == NULL) return;
     this.state = WS_INUSE;
     actor.spawnshieldtime = min(actor.spawnshieldtime, time);  // kill spawn shield when you fire
     // if the weapon hasn't been firing continuously, reset the timer
     if (attacktime >= 0)
     {
         int slot = weaponslot(weaponentity);
         if (ATTACK_FINISHED(actor, slot) < time - actor.weapon_frametime * 1.5)
         {
             ATTACK_FINISHED(actor, slot) = time;
             // dprint("resetting attack finished to ", ftos(time), "\n");
         }
         ATTACK_FINISHED(actor, slot) = ATTACK_FINISHED(actor, slot) + attacktime * W_WeaponRateFactor(actor);
     }
     actor.bulletcounter += 1;
     // dprint("attack finished ", ftos(ATTACK_FINISHED(actor, slot)), "\n");
 }
void weapon_thinkf (entity actor, .entity weaponentity, WFRAME fr, float t, void(Weapon thiswep, entity actor,.entity weaponentity, int fire) func)
Parameters
t defer thinking until time + t
func next think function
Definition at line 329 of file weaponsystem.qc.
References anim_fire1, anim_fire2, anim_idle, anim_reload, ANIMACTION_MELEE, ANIMACTION_SHOOT, animdecide_setaction(), backtrace, entity(), FOREACH_CLIENT, g_weaponratefactor, IS_SPEC, LAMBDA, NULL, PS, state, time, v_forward, v_right, v_up, vector, w_ready(), W_WeaponRateFactor(), weapon_nextthink, weaponentities, wframe, wframe_send(), and WS_RAISE.
Referenced by w_ready(), W_Reload(), and W_WeaponFrame().
 {
     entity this = actor.(weaponentity);
     if (this == NULL) return;
     bool restartanim;
     if (fr == WFRAME_DONTCHANGE)
     {
         fr = this.wframe;
         restartanim = false;
     }
     else
     {
         restartanim = fr != WFRAME_IDLE;
     }
     vector of = v_forward;
     vector or = v_right;
     vector ou = v_up;
     vector a = '0 0 0';
     this.wframe = fr;
     if (fr == WFRAME_IDLE) a = this.anim_idle;
     else if (fr == WFRAME_FIRE1) a = this.anim_fire1;
     else if (fr == WFRAME_FIRE2) a = this.anim_fire2;
     else  // if (fr == WFRAME_RELOAD)
         a = this.anim_reload;
     a.z *= g_weaponratefactor;
     v_forward = of;
     v_right = or;
     v_up = ou;
     if (this.weapon_think == w_ready && func != w_ready && this.state == WS_RAISE) backtrace(
             "Tried to override initial weapon think function - should this really happen?");
     t *= W_WeaponRateFactor(actor);
     // VorteX: haste can be added here
     if (this.weapon_think == w_ready)
     {
         this.weapon_nextthink = time;
         // dprint("started firing at ", ftos(time), "\n");
     }
     if (this.weapon_nextthink < time - actor.weapon_frametime * 1.5
         || this.weapon_nextthink > time + actor.weapon_frametime * 1.5)
     {
         this.weapon_nextthink = time;
         // dprint("reset weapon animation timer at ", ftos(time), "\n");
     }
     this.weapon_nextthink += t;
     if (weaponentity == weaponentities[0]) STAT(WEAPON_NEXTTHINK, actor) = this.weapon_nextthink;
     this.weapon_think = func;
     // dprint("next ", ftos(this.weapon_nextthink), "\n");
     if (this)
     {
         FOREACH_CLIENT(true, LAMBDA(
             if(it == actor || (IS_SPEC(it) && it.enemy == actor))
                 wframe_send(it, this, a, restartanim);
         ));
     }
     if ((fr == WFRAME_FIRE1 || fr == WFRAME_FIRE2) && t)
     {
         int act = (fr == WFRAME_FIRE2 && (PS(actor).m_weapon == WEP_SHOCKWAVE || PS(actor).m_weapon == WEP_SHOTGUN))
             ? ANIMACTION_MELEE
             : ANIMACTION_SHOOT
             ;
         animdecide_setaction(actor, act, restartanim);
     }
     else if (actor.anim_upper_action == ANIMACTION_SHOOT || actor.anim_upper_action == ANIMACTION_MELEE)
     {
         actor.anim_upper_action = 0;
     }
 }
void wframe_send (entity actor, entity weaponentity, vector a, bool restartanim)
Referenced by weapon_thinkf().
Variable Documentation
bool hook_switchweapon
Definition at line 417 of file weaponsystem.qc.
float m_alpha
Definition at line 62 of file weaponsystem.qc.
Referenced by CL_Weaponentity_Think().
float prevdryfire
Definition at line 206 of file weaponsystem.qc.
float prevwarntime
Definition at line 207 of file weaponsystem.qc.
float race_penalty
Definition at line 262 of file weaponsystem.qc.
float reload_ammo_amount
Definition at line 658 of file weaponsystem.qc.
float reload_ammo_min
Definition at line 658 of file weaponsystem.qc.
float reload_complain
Definition at line 659 of file weaponsystem.qc.
string reload_sound
Definition at line 660 of file weaponsystem.qc.
float reload_time
Definition at line 658 of file weaponsystem.qc.
int state
Definition at line 18 of file weaponsystem.qc.
Referenced by w_clear(), w_ready(), W_Reload(), W_WeaponFrame(), weapon_prepareattack_check(), weapon_prepareattack_do(), and weapon_thinkf().
float weapon_frametime
Definition at line 20 of file weaponsystem.qc.
entity weaponentity_fld
Definition at line 61 of file weaponsystem.qc.
Referenced by CL_Weaponentity_Think().