Xonotic: common/notifications.qc File Reference
common/notifications.qc File Reference
Defines
#define CHECKARG_TYPENAME(type)
#define DESTROY_LOOP(type, count)
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_SV(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC(selected, result)
#define ARG_CASE_ARG_CS_SV(selected, result)
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_SV(selected, result)
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE_ARG_CS_SV_HA(selected, result)
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV(selected, result)
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_SV(selected, result)
#define ARG_CASE_ARG_DC(selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define SET_NOTIF_STRING(string, stringname)
#define NOTIF_WRITE(a)
#define NOTIF_WRITE_ENTITY(description)
#define NOTIF_WRITE_ENTITY_CHOICE(descriptiona, descriptionb)
#define NOTIF_WRITE_HARDCODED(cvar, default, description)
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV(selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_SV(selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define VARITEM(stringc, floatc, args)
Functions
string Get_Notif_TypeName (int net_type)
entity Get_Notif_Ent (int net_type, int net_name)
string Notification_CheckArgs_TypeName (float net_type, float net_name)
void Destroy_Notification_Entity (entity notif)
void Destroy_All_Notifications ()
string Process_Notif_Line (int typeId, bool chat, string input, string notiftype, string notifname, string stringtype)
string Process_Notif_Args (float arg_type, string args, string notiftype, string notifname)
void Create_Notification_Entity (float var_default, float var_cvar, int typeId, int nameid, string namestring, int strnum, int flnum, float channel, string snd, float vol, float position, string args, string hudargs, string icon, float cpid, string durcnt, string normal, string gentle, int anncename, int infoname, int centername, float challow_def, float challow_var, int chtype, int optiona, int optionb)
void Dump_Notifications (float fh, float alsoprint)
string Local_Notification_sprintf (string input, string args, string s1, string s2, string s3, string s4, int f1, float f2, float f3, float f4)
void Local_Notification (int net_type, int net_name,...count)
void Local_Notification_WOVA (int net_type, float net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
Define Documentation
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE_ARG_CS (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC (selected, result)
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_CS_SV_HA (selected, result)
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_DC (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_SV (selected, result) case selected: { ++sel_num; break; }
#define ARG_CASE_ARG_SV (selected, result)
#define ARG_CASE_ARG_SV (selected, result)
#define ARG_CASE_ARG_SV (selected, result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
#define CHECKARG_TYPENAME (type)
Value:
case MSG_##type: \
        { if(!net_name || (net_name > NOTIF_##type##_COUNT)) \
        { checkargs = sprintf("Improper name: %d!", net_name); } break; }
Referenced by Notification_CheckArgs_TypeName().
#define DESTROY_LOOP (type, count)
Value:
MACRO_BEGIN { \
        for(i = 1; i <= count; ++i) \
        { \
            notif = Get_Notif_Ent(type, i); \
            if (!notif) { backtrace("Destroy_All_Notifications(): Missing notification entity!\n"); return; } \
            Destroy_Notification_Entity(notif); \
        } \
    } MACRO_END
Referenced by Destroy_All_Notifications().
#define NOTIF_WRITE (a)
Value:
{ \
        fputs(fh, a); \
        if(alsoprint) { LOG_INFO(a); } }
Referenced by Dump_Notifications().
#define NOTIF_WRITE_ENTITY (description)
Value:
{ \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%d\" \"%s\"\n", \
                e.nent_name, e.nent_default, description \
            ); \
        NOTIF_WRITE(notif_msg) }
Referenced by Dump_Notifications().
#define NOTIF_WRITE_ENTITY_CHOICE (descriptiona, descriptionb)
Value:
{ \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%d\" \"%s\"\n" \
                "seta notification_%s_ALLOWED \"%d\" \"%s\"\n", \
                e.nent_name, e.nent_default, descriptiona, \
                e.nent_name, e.nent_challow_def, descriptionb \
            ); \
        NOTIF_WRITE(notif_msg) }
Referenced by Dump_Notifications().
#define NOTIF_WRITE_HARDCODED (cvar, default, description)
Value:
{ \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%s\" \"%s\"\n", \
                cvar, default, description \
            ); \
        NOTIF_WRITE(notif_msg) }
Referenced by Dump_Notifications().
#define SET_NOTIF_STRING (string, stringname)
Value:
MACRO_BEGIN { \
                    notif.nent_string = strzone(CCR( \
                        Process_Notif_Line( \
                            typeId, \
                            (var_cvar > 1), \
                            string, \
                            typestring, \
                            namestring, \
                            stringname \
                        )) \
                    ); \
                } MACRO_END
Referenced by Create_Notification_Entity().
#define VARITEM (stringc, floatc, args)
Value:
if((stringcount == stringc) && (floatcount == floatc)) \
            { Local_Notification(net_type, net_name, args); return; }
Function Documentation
void Create_Notification_Entity (float var_default, float var_cvar, int typeId, int nameid, string namestring, int strnum, int flnum, float channel, string snd, float vol, float position, string args, string hudargs, string icon, float cpid, string durcnt, string normal, string gentle, int anncename, int infoname, int centername, float challow_def, float challow_var, int chtype, int optiona, int optionb)
Definition at line 491 of file notifications.qc.
References AnnouncerOption(), entity(), error(), GENTLE, Get_Notif_TypeName(), LOG_INFOF, max(), MSG_ANNCE, msg_annce_notifs, MSG_CENTER, msg_center_notifs, MSG_CHOICE, msg_choice_notifs, MSG_INFO, msg_info_notifs, MSG_MULTI, msg_multi_notifs, new_pure, NO_MSG, notif_error, notif_global_error, precache_sound(), Process_Notif_Args(), server_is_dedicated, SET_NOTIF_STRING, strcat(), and strzone().
{
    // =====================
    //  Global Entity Setup
    // =====================
    entity notif = new_pure(notification);
    switch(typeId)
    {
        case MSG_ANNCE:
        {
            msg_annce_notifs[nameid - 1] = notif;
            notif.classname = "msg_annce_notification";
            break;
        }
        case MSG_INFO:
        {
            msg_info_notifs[nameid - 1] = notif;
            notif.classname = "msg_info_notification";
            break;
        }
        case MSG_CENTER:
        {
            msg_center_notifs[nameid - 1] = notif;
            notif.classname = "msg_center_notification";
            break;
        }
        case MSG_MULTI:
        {
            msg_multi_notifs[nameid - 1] = notif;
            notif.classname = "msg_multi_notification";
            break;
        }
        case MSG_CHOICE:
        {
            msg_choice_notifs[nameid - 1] = notif;
            notif.classname = "msg_choice_notification";
            break;
        }
        default:
        {
            error(sprintf(
                strcat(
                    "^1NOTIFICATION WITH IMPROPER TYPE: ",
                    "^7net_type = %d, net_name = %s.\n"
                ),
                typeId,
                namestring
            ));
            return; // It's not possible to recover from this one
        }
    }
    notif.nent_default = var_default;
    notif.nent_enabled = (1 <= var_cvar);
    notif.nent_type = typeId;
    notif.nent_id = nameid;
    notif.nent_name = strzone(namestring);
    string typestring = Get_Notif_TypeName(typeId);
    // Other pre-notif-setup requisites
    notif_error = false;
    // ====================
    //  Notification Setup
    // ====================
    switch(typeId)
    {
        case MSG_ANNCE:
        {
            // Set MSG_ANNCE information and handle precaching
            #ifdef CSQC
            if (!(GENTLE && (var_cvar == 1)))
            {
                if(snd != "")
                {
                    if(notif.nent_enabled)
                    {
                        precache_sound(sprintf("announcer/%s/%s.wav", AnnouncerOption(), snd));
                        notif.nent_channel = channel;
                        notif.nent_snd = strzone(snd);
                        notif.nent_vol = vol;
                        notif.nent_position = position;
                    }
                }
                else
                {
                    LOG_INFOF(
                        strcat(
                            "^1NOTIFICATION WITH NO SOUND: ",
                            "^7net_type = %s, net_name = %s.\n"
                        ),
                        typestring,
                        namestring
                    );
                    notif_error = true;
                }
            }
            else { notif.nent_enabled = false; }
            #else
            notif.nent_enabled = false;
            #endif
            break;
        }
        case MSG_INFO:
        case MSG_CENTER:
        {
            // Set MSG_INFO and MSG_CENTER string/float counts
            notif.nent_stringcount = strnum;
            notif.nent_floatcount = flnum;
            // Only initialize arguments if we're either a client or on a dedicated server
            #ifdef SVQC
            float should_process_args = server_is_dedicated;
            #else
            float should_process_args = true;
            #endif
            if(should_process_args)
            {
                // ========================
                //  Process Main Arguments
                // ========================
                if(strnum + flnum)
                {
                    if(args != "")
                    {
                        notif.nent_args = strzone(
                            Process_Notif_Args(1, args, typestring, namestring));
                    }
                    else if((hudargs == "") && (durcnt ==""))
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION HAS ARG COUNTS BUT NO ARGS OR HUDARGS OR DURCNT: ",
                                "^7net_type = %s, net_name = %s, strnum = %d, flnum = %d\n"
                            ),
                            typestring,
                            namestring,
                            strnum,
                            flnum
                        );
                        notif_error = true;
                    }
                }
                else if(args != "")
                {
                    notif.nent_args = strzone(
                        Process_Notif_Args(1, args, typestring, namestring));
                }
                // =======================================
                //  Process HUD and Centerprint Arguments
                //    Only processed on CSQC, as these
                //    args are only for HUD features.
                // =======================================
                #ifdef CSQC
                if(hudargs != "")
                {
                    notif.nent_hudargs = strzone(
                        Process_Notif_Args(2, hudargs, typestring, namestring));
                    if(icon != "") { notif.nent_icon = strzone(icon); }
                    else
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION HAS HUDARGS BUT NO ICON: ",
                                "^7net_type = %s, net_name = %s.\n"
                            ),
                            typestring,
                            namestring
                        );
                        notif_error = true;
                    }
                }
                else if(icon != "")
                {
                    LOG_INFOF(
                        strcat(
                            "^1NOTIFICATION HAS ICON BUT NO HUDARGS: ",
                            "^7net_type = %s, net_name = %s.\n"
                        ),
                        typestring,
                        namestring
                    );
                    notif_error = true;
                }
                if(durcnt != "")
                {
                    notif.nent_durcnt = strzone(
                        Process_Notif_Args(3, durcnt, typestring, namestring));
                    if(cpid != NO_MSG) { notif.nent_cpid = cpid; }
                    else
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION HAS DURCNT BUT NO CPID: ",
                                "^7net_type = %s, net_name = %s.\n"
                            ),
                            typestring,
                            namestring
                        );
                        notif_error = true;
                    }
                }
                else if(cpid != NO_MSG) { notif.nent_cpid = cpid; }
                #endif
                // ======================
                //  Process Notif String
                // ======================
                #define SET_NOTIF_STRING(string,stringname) MACRO_BEGIN { \
                    notif.nent_string = strzone(CCR( \
                        Process_Notif_Line( \
                            typeId, \
                            (var_cvar > 1), \
                            string, \
                            typestring, \
                            namestring, \
                            stringname \
                        )) \
                    ); \
                } MACRO_END
                if(GENTLE)
                {
                    if(gentle != "") { SET_NOTIF_STRING(gentle, "GENTLE"); }
                    else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                }
                else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                #undef SET_NOTIF_STRING
                // Check to make sure a string was chosen
                if(notif.nent_string == "")
                {
                    LOG_INFOF(
                        strcat(
                            "^1EMPTY NOTIFICATION: ",
                            "^7net_type = %s, net_name = %s.\n"
                        ),
                        typestring,
                        namestring
                    );
                    notif_error = true;
                }
            }
            break;
        }
        case MSG_MULTI:
        {
            // Set MSG_MULTI string/float counts
            if((anncename == NO_MSG) && (infoname == NO_MSG) && (centername == NO_MSG))
            {
                LOG_INFOF(
                    strcat(
                        "^1NOTIFICATION WITH NO SUBCALLS: ",
                        "^7net_type = %s, net_name = %s.\n"
                    ),
                    typestring,
                    namestring
                );
                notif_error = true;
            }
            else
            {
                // announcements don't actually need any arguments, so lets not even count them.
                if(anncename != NO_MSG) { notif.nent_msgannce = msg_annce_notifs[anncename - 1]; }
                float infoname_stringcount = 0, infoname_floatcount = 0;
                float centername_stringcount = 0, centername_floatcount = 0;
                if(infoname != NO_MSG)
                {
                    notif.nent_msginfo = msg_info_notifs[infoname - 1];
                    infoname_stringcount = notif.nent_msginfo.nent_stringcount;
                    infoname_floatcount = notif.nent_msginfo.nent_floatcount;
                }
                if(centername != NO_MSG)
                {
                    notif.nent_msgcenter = msg_center_notifs[centername - 1];
                    centername_stringcount = notif.nent_msgcenter.nent_stringcount;
                    centername_floatcount = notif.nent_msgcenter.nent_floatcount;
                }
                // set the requirements of THIS notification to the totals of its subcalls
                notif.nent_stringcount = max(infoname_stringcount, centername_stringcount);
                notif.nent_floatcount = max(infoname_floatcount, centername_floatcount);
            }
            break;
        }
        case MSG_CHOICE:
        {
            if((chtype == NO_MSG) || (optiona == NO_MSG) || (optionb == NO_MSG))
            {
                LOG_INFOF(
                    strcat(
                        "^1NOTIFICATION IS MISSING CHOICE PARAMS: ",
                        "^7net_type = %s, net_name = %s.\n"
                    ),
                    typestring,
                    namestring
                );
                notif_error = true;
            }
            else
            {
                switch(chtype)
                {
                    case MSG_ANNCE:
                    {
                        notif.nent_optiona = msg_annce_notifs[optiona - 1];
                        notif.nent_optionb = msg_annce_notifs[optionb - 1];
                        break;
                    }
                    case MSG_INFO:
                    {
                        notif.nent_optiona = msg_info_notifs[optiona - 1];
                        notif.nent_optionb = msg_info_notifs[optionb - 1];
                        break;
                    }
                    case MSG_CENTER:
                    {
                        notif.nent_optiona = msg_center_notifs[optiona - 1];
                        notif.nent_optionb = msg_center_notifs[optionb - 1];
                        break;
                    }
                    case MSG_MULTI:
                    {
                        notif.nent_optiona = msg_multi_notifs[optiona - 1];
                        notif.nent_optionb = msg_multi_notifs[optionb - 1];
                        break;
                    }
                    case MSG_CHOICE: // should we REALLY allow nested options?...
                    {
                        notif.nent_optiona = msg_choice_notifs[optiona - 1];
                        notif.nent_optionb = msg_choice_notifs[optionb - 1];
                        break;
                    }
                    default:
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION WITH IMPROPER TYPE: ",
                                "^7net_type = %d, net_name = %s.\n"
                            ),
                            typeId,
                            namestring
                        );
                        notif_error = true;
                        break;
                    }
                }
                notif.nent_challow_def = challow_def; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                notif.nent_challow_var = challow_var; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                notif.nent_stringcount = max(notif.nent_optiona.nent_stringcount, notif.nent_optionb.nent_stringcount);
                notif.nent_floatcount = max(notif.nent_optiona.nent_floatcount, notif.nent_optionb.nent_floatcount);
                /*#ifdef NOTIFICATIONS_DEBUG
                Debug_Notification(sprintf(
                    "Create_Notification_Entity(...): MSG_CHOICE: %s\n%s\n%s\n",
                    notif.nent_name,
                    sprintf(
                        "^ optiona: %s %s : %d %d",
                        Get_Notif_TypeName(notif.nent_optiona.nent_type),
                        notif.nent_optiona.nent_name,
                        notif.nent_optiona.nent_stringcount,
                        notif.nent_optiona.nent_floatcount
                    ),
                    sprintf(
                        "^ optionb: %s %s : %d %d",
                        Get_Notif_TypeName(notif.nent_optionb.nent_type),
                        notif.nent_optionb.nent_name,
                        notif.nent_optionb.nent_stringcount,
                        notif.nent_optionb.nent_floatcount
                    )
                ));
                #endif*/
            }
            break;
        }
        default:
        {
            LOG_INFOF(
                strcat(
                    "^1NOTIFICATION WITH IMPROPER TYPE: ",
                    "^7net_type = %d, net_name = %s.\n"
                ),
                typeId,
                namestring
            );
            notif_error = true;
            break;
        }
    }
    // now check to see if any errors happened
    if(notif_error)
    {
        notif.nent_enabled = false; // disable the notification so it can't cause trouble
        notif_global_error = true; // throw the red flag that an error happened on init
    }
}
void Destroy_All_Notifications ()
Definition at line 237 of file notifications.qc.
References DESTROY_LOOP, entity(), MSG_ANNCE, MSG_CENTER, MSG_CHOICE, MSG_INFO, MSG_MULTI, NOTIF_ANNCE_COUNT, NOTIF_CENTER_COUNT, NOTIF_CHOICE_COUNT, NOTIF_INFO_COUNT, NOTIF_MULTI_COUNT, reset_centerprint_messages(), and world.
Referenced by GenericCommand_restartnotifs().
{
    entity notif;
    int i;
    #define DESTROY_LOOP(type,count) MACRO_BEGIN { \
        for(i = 1; i <= count; ++i) \
        { \
            notif = Get_Notif_Ent(type, i); \
            if (!notif) { backtrace("Destroy_All_Notifications(): Missing notification entity!\n"); return; } \
            Destroy_Notification_Entity(notif); \
        } \
    } MACRO_END
    // kill all networked notifications and centerprints
    #ifdef SVQC
    Kill_Notification(NOTIF_ALL, world, 0, 0);
    #else
    reset_centerprint_messages();
    #endif
    // kill all real notification entities
    DESTROY_LOOP(MSG_ANNCE, NOTIF_ANNCE_COUNT);
    DESTROY_LOOP(MSG_INFO, NOTIF_INFO_COUNT);
    DESTROY_LOOP(MSG_CENTER, NOTIF_CENTER_COUNT);
    DESTROY_LOOP(MSG_MULTI, NOTIF_MULTI_COUNT);
    DESTROY_LOOP(MSG_CHOICE, NOTIF_CHOICE_COUNT);
    #undef DESTROY_LOOP
}
void Destroy_Notification_Entity (entity notif)
Definition at line 225 of file notifications.qc.
References strunzone().
{
    if(notif.nent_name != "") { strunzone(notif.nent_name); }
    if(notif.nent_snd != "") { strunzone(notif.nent_snd); }
    if(notif.nent_args != "") { strunzone(notif.nent_args); }
    if(notif.nent_hudargs != "") { strunzone(notif.nent_hudargs); }
    if(notif.nent_icon != "") { strunzone(notif.nent_icon); }
    if(notif.nent_durcnt != "") { strunzone(notif.nent_durcnt); }
    if(notif.nent_string != "") { strunzone(notif.nent_string); }
    remove(notif);
}
void Dump_Notifications (float fh, float alsoprint)
Definition at line 960 of file notifications.qc.
References backtrace, entity(), Get_Notif_Ent(), MSG_ANNCE, MSG_CENTER, MSG_CHOICE, MSG_INFO, MSG_MULTI, NOTIF_ANNCE_COUNT, NOTIF_CENTER_COUNT, NOTIF_CHOICE_COUNT, NOTIF_INFO_COUNT, NOTIF_MULTI_COUNT, NOTIF_WRITE, NOTIF_WRITE_ENTITY, NOTIF_WRITE_ENTITY_CHOICE, NOTIF_WRITE_HARDCODED, and strcat().
Referenced by GENERIC_COMMAND().
{
    #define NOTIF_WRITE(a) { \
        fputs(fh, a); \
        if(alsoprint) { LOG_INFO(a); } }
    #define NOTIF_WRITE_ENTITY(description) { \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%d\" \"%s\"\n", \
                e.nent_name, e.nent_default, description \
            ); \
        NOTIF_WRITE(notif_msg) }
    #define NOTIF_WRITE_ENTITY_CHOICE(descriptiona,descriptionb) { \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%d\" \"%s\"\n" \
                "seta notification_%s_ALLOWED \"%d\" \"%s\"\n", \
                e.nent_name, e.nent_default, descriptiona, \
                e.nent_name, e.nent_challow_def, descriptionb \
            ); \
        NOTIF_WRITE(notif_msg) }
    #define NOTIF_WRITE_HARDCODED(cvar,default,description) { \
        notif_msg = \
            sprintf( \
                "seta notification_%s \"%s\" \"%s\"\n", \
                cvar, default, description \
            ); \
        NOTIF_WRITE(notif_msg) }
    string notif_msg;
    int i;
    entity e;
    // Note: This warning only applies to the notifications.cfg file that is output...
    // You ARE supposed to manually edit this function to add i.e. hard coded
    // notification variables for mutators or game modes or such and then
    // regenerate the notifications.cfg file from the new code.
    NOTIF_WRITE("// ********************************************** //\n");
    NOTIF_WRITE("// ** WARNING - DO NOT MANUALLY EDIT THIS FILE ** //\n");
    NOTIF_WRITE("// **                                          ** //\n");
    NOTIF_WRITE("// **  This file is automatically generated    ** //\n");
    NOTIF_WRITE("// **  by code with the command 'dumpnotifs'.  ** //\n");
    NOTIF_WRITE("// **                                          ** //\n");
    NOTIF_WRITE("// **  If you add a new notification, please   ** //\n");
    NOTIF_WRITE("// **  regenerate this file with that command  ** //\n");
    NOTIF_WRITE("// **  making sure that the output matches     ** //\n");
    NOTIF_WRITE("// **  with the lists and defaults in code.    ** //\n");
    NOTIF_WRITE("// **                                          ** //\n");
    NOTIF_WRITE("// ********************************************** //\n");
    // These notifications will also append their string as a comment...
    // This is not necessary, and does not matter if they vary between config versions,
    // it is just a semi-helpful tool for those who want to manually change their user settings.
    NOTIF_WRITE(sprintf("\n// MSG_ANNCE notifications (count = %d):\n", NOTIF_ANNCE_COUNT));
    for(i = 1; i <= NOTIF_ANNCE_COUNT; ++i)
    {
        e = Get_Notif_Ent(MSG_ANNCE, i);
        if (!e) { backtrace("Dump_Notifications(): Missing notification entity!\n"); return; }
        NOTIF_WRITE_ENTITY(
            "0 = disabled, 1 = enabled if gentle mode is off, 2 = always enabled"
        );
    }
    NOTIF_WRITE(sprintf("\n// MSG_INFO notifications (count = %d):\n", NOTIF_INFO_COUNT));
    for(i = 1; i <= NOTIF_INFO_COUNT; ++i)
    {
        e = Get_Notif_Ent(MSG_INFO, i);
        if (!e) { backtrace("Dump_Notifications(): Missing notification entity!\n"); return; }
        NOTIF_WRITE_ENTITY(
            "0 = off, 1 = print to console, "
            "2 = print to console and chatbox (if notification_allow_chatboxprint is enabled)"
        );
    }
    NOTIF_WRITE(sprintf("\n// MSG_CENTER notifications (count = %d):\n", NOTIF_CENTER_COUNT));
    for(i = 1; i <= NOTIF_CENTER_COUNT; ++i)
    {
        e = Get_Notif_Ent(MSG_CENTER, i);
        if (!e) { backtrace("Dump_Notifications(): Missing notification entity!\n"); return; }
        NOTIF_WRITE_ENTITY(
            "0 = off, 1 = centerprint"
        );
    }
    NOTIF_WRITE(sprintf("\n// MSG_MULTI notifications (count = %d):\n", NOTIF_MULTI_COUNT));
    for(i = 1; i <= NOTIF_MULTI_COUNT; ++i)
    {
        e = Get_Notif_Ent(MSG_MULTI, i);
        if (!e) { backtrace("Dump_Notifications(): Missing notification entity!\n"); return; }
        NOTIF_WRITE_ENTITY(
            "Enable this multiple notification"
        );
    }
    NOTIF_WRITE(sprintf("\n// MSG_CHOICE notifications (count = %d):\n", NOTIF_CHOICE_COUNT));
    for(i = 1; i <= NOTIF_CHOICE_COUNT; ++i)
    {
        e = Get_Notif_Ent(MSG_CHOICE, i);
        if (!e) { backtrace("Dump_Notifications(): Missing notification entity!\n"); return; }
        NOTIF_WRITE_ENTITY_CHOICE(
            "Choice for this notification 0 = off, 1 = default message, 2 = verbose message",
            "Allow choice for this notification 0 = off, 1 = only in warmup mode, 2 = always"
        );
    }
    // edit these to match whichever cvars are used for specific notification options
    NOTIF_WRITE("\n// HARD CODED notification variables:\n");
    NOTIF_WRITE_HARDCODED(
        "allow_chatboxprint", "1",
        "Allow INFO notifications to be printed to chat box"
        "0 = do not allow, "
        "1 = allow only if allowed by individual notification_INFO* cvars, "
        "2 = force all INFO notifications to be printed to the chatbox"
    );
    NOTIF_WRITE_HARDCODED(
        "debug", "0",
        "Print extra debug information on all notification function calls "
        "(Requires -DNOTIFICATIONS_DEBUG flag to be enabled on QCSRC compilation)... "
        "0 = disabled, 1 = dprint, 2 = print"
    );
    NOTIF_WRITE_HARDCODED(
        "errors_are_fatal", "1",
        "If a notification fails upon initialization, cause a Host_Error to stop the program"
    );
    NOTIF_WRITE_HARDCODED(
        "item_centerprinttime", "1.5",
        "How long to show item information centerprint messages (like 'You got the Electro' or such)"
    );
    NOTIF_WRITE_HARDCODED(
        "lifetime_mapload", "10",
        "Amount of time that notification entities last immediately at mapload (in seconds) "
        "to help prevent notifications from being lost on early init (like gamestart countdown)"
    );
    NOTIF_WRITE_HARDCODED(
        "lifetime_runtime", "0.5",
        "Amount of time that notification entities last on the server during runtime (In seconds)"
    );
    NOTIF_WRITE_HARDCODED(
        "server_allows_location", "1",
        "Server side cvar for allowing death messages to show location information too"
    );
    NOTIF_WRITE_HARDCODED(
        "show_location", "0",
        "Append location information to MSG_INFO death/kill messages"
    );
    NOTIF_WRITE_HARDCODED(
        "show_location_string", "",
        "Replacement string piped into sprintf, "
        "so you can do different messages like this: ' at the %s' or ' (near %s)'"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees", "1",
        "Print information about sprees in death/kill messages"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees_center", "1",
        "Show spree information in MSG_CENTER messages... "
        "0 = off, 1 = target (but only for first victim) and attacker"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees_center_specialonly", "1",
        "Don't show spree information in MSG_CENTER messages if it isn't an achievement"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees_info", "3",
        "Show spree information in MSG_INFO messages... "
        "0 = off, 1 = target only, 2 = attacker only, 3 = target and attacker"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees_info_newline", "1",
        "Show attacker spree information for MSG_INFO messages on a separate line than the death notification itself"
    );
    NOTIF_WRITE_HARDCODED(
        "show_sprees_info_specialonly", "1",
        "Don't show attacker spree information in MSG_INFO messages if it isn't an achievement"
    );
    NOTIF_WRITE(sprintf(
        strcat(
            "\n// Notification counts (total = %d): ",
            "MSG_ANNCE = %d, MSG_INFO = %d, MSG_CENTER = %d, MSG_MULTI = %d, MSG_CHOICE = %d\n"
        ),
        (
            NOTIF_ANNCE_COUNT +
            NOTIF_INFO_COUNT +
            NOTIF_CENTER_COUNT +
            NOTIF_MULTI_COUNT +
            NOTIF_CHOICE_COUNT
        ),
        NOTIF_ANNCE_COUNT,
        NOTIF_INFO_COUNT,
        NOTIF_CENTER_COUNT,
        NOTIF_MULTI_COUNT,
        NOTIF_CHOICE_COUNT
    ));
    return;
    #undef NOTIF_WRITE_HARDCODED
    #undef NOTIF_WRITE_ENTITY
    #undef NOTIF_WRITE
}
entity Get_Notif_Ent (int net_type, int net_name)
Definition at line 34 of file notifications.qc.
References backtrace, MSG_ANNCE, msg_annce_notifs, MSG_CENTER, msg_center_notifs, MSG_CHOICE, msg_choice_notifs, MSG_INFO, msg_info_notifs, MSG_MULTI, msg_multi_notifs, and world.
Referenced by Dump_Notifications(), and Local_Notification().
{
    switch(net_type)
    {
        case MSG_ANNCE: return msg_annce_notifs[net_name - 1];
        case MSG_INFO: return msg_info_notifs[net_name - 1];
        case MSG_CENTER: return msg_center_notifs[net_name - 1];
        case MSG_MULTI: return msg_multi_notifs[net_name - 1];
        case MSG_CHOICE: return msg_choice_notifs[net_name - 1];
    }
    backtrace(sprintf("Get_Notif_Ent(%d, %d): Improper net type!\n", net_type, net_name));
    return world;
}
string Get_Notif_TypeName (int net_type)
Definition at line 19 of file notifications.qc.
References backtrace, MSG_ANNCE, MSG_CENTER, MSG_CENTER_CPID, MSG_CHOICE, MSG_INFO, and MSG_MULTI.
Referenced by Create_Notification_Entity(), and Local_Notification().
{
    switch(net_type)
    {
        case MSG_ANNCE: return "MSG_ANNCE";
        case MSG_INFO: return "MSG_INFO";
        case MSG_CENTER: return "MSG_CENTER";
        case MSG_CENTER_CPID: return "MSG_CENTER_CPID";
        case MSG_MULTI: return "MSG_MULTI";
        case MSG_CHOICE: return "MSG_CHOICE";
    }
    backtrace(sprintf("Get_Notif_TypeName(%d): Improper net type!\n", net_type));
    return "";
}
void Local_Notification (int net_type, int net_name, count)
Definition at line 1423 of file notifications.qc.
References backtrace, count, cvar(), entity(), float, Get_Notif_Ent(), Get_Notif_TypeName(), Local_Notification_sprintf(), Local_Notification_WOVA(), MakeConsoleSafe(), MSG_ANNCE, MSG_CENTER, MSG_CHOICE, MSG_INFO, MSG_MULTI, nent_name, NOTIF_ABORT, Notification_CheckArgs_TypeName(), print(), strcat(), strlen(), strzone(), substring(), and warmup_stage.
Referenced by Announcer_Countdown(), Announcer_Gamestart(), Announcer_Time(), Local_Notification_WOVA(), and NET_HANDLE().
{
    // check if this should be aborted
    if(net_name == NOTIF_ABORT)
    {
        #ifdef NOTIFICATIONS_DEBUG
        Debug_Notification(sprintf(
            "Local_Notification(%s, %s, ...);\n",
            Get_Notif_TypeName(net_type),
            "NOTIF_ABORT"
        ));
        #endif
        return;
    }
    // check supplied type and name for errors
    string checkargs = Notification_CheckArgs_TypeName(net_type, net_name);
    if(checkargs != "")
    {
        #ifdef NOTIFICATIONS_DEBUG
        Debug_Notification(sprintf(
            "Local_Notification(%s, %d, ...);\n",
            Get_Notif_TypeName(net_type),
            Get_Notif_Ent(net_type, net_name).nent_name
        ));
        #endif
        backtrace(sprintf("Incorrect usage of Local_Notification: %s\n", checkargs));
        return;
    }
    // retreive entity of this notification
    entity notif = Get_Notif_Ent(net_type, net_name);
    if (!notif)
    {
        #ifdef NOTIFICATIONS_DEBUG
        Debug_Notification(sprintf(
            "Local_Notification(%s, %d, ...);\n",
            Get_Notif_TypeName(net_type),
            net_name
        ));
        #endif
        backtrace("Local_Notification: Could not find notification entity!\n");
        return;
    }
    // check if the notification is enabled
    if (!notif.nent_enabled)
    {
        #ifdef NOTIFICATIONS_DEBUG
        Debug_Notification(sprintf(
            "Local_Notification(%s, %s, ...): Entity was disabled...\n",
            Get_Notif_TypeName(net_type),
            notif.nent_name
        ));
        #endif
        return;
    }
    string s1 = ((0 < notif.nent_stringcount) ? ...(0, string) : "");
    string s2 = ((1 < notif.nent_stringcount) ? ...(1, string) : "");
    string s3 = ((2 < notif.nent_stringcount) ? ...(2, string) : "");
    string s4 = ((3 < notif.nent_stringcount) ? ...(3, string) : "");
    float f1 = ((0 < notif.nent_floatcount) ? ...((notif.nent_stringcount + 0), float) : 0);
    float f2 = ((1 < notif.nent_floatcount) ? ...((notif.nent_stringcount + 1), float) : 0);
    float f3 = ((2 < notif.nent_floatcount) ? ...((notif.nent_stringcount + 2), float) : 0);
    float f4 = ((3 < notif.nent_floatcount) ? ...((notif.nent_stringcount + 3), float) : 0);
    #ifdef NOTIFICATIONS_DEBUG
    Debug_Notification(sprintf(
        "Local_Notification(%s, %s, %s, %s);\n",
        Get_Notif_TypeName(net_type),
        notif.nent_name,
        MakeConsoleSafe(sprintf("'%s^7', '%s^7', '%s^7', '%s^7'", s1, s2, s3, s4)),
        sprintf("%d, %d, %d, %d", f1, f2, f3, f4)
    ));
    #endif
    if((notif.nent_stringcount + notif.nent_floatcount) > count)
    {
        backtrace(sprintf(
            strcat(
                "Not enough arguments for Local_Notification(%s, %s, ...)! ",
                "stringcount(%d) + floatcount(%d) > count(%d)\n",
                "Check the definition and function call for accuracy...?\n"
            ),
            Get_Notif_TypeName(net_type),
            notif.nent_name,
            notif.nent_stringcount,
            notif.nent_floatcount,
            count
        ));
        return;
    }
    else if((notif.nent_stringcount + notif.nent_floatcount) < count)
    {
        backtrace(sprintf(
            strcat(
                "Too many arguments for Local_Notification(%s, %s, ...)! ",
                "stringcount(%d) + floatcount(%d) < count(%d)\n",
                "Check the definition and function call for accuracy...?\n"
            ),
            Get_Notif_TypeName(net_type),
            notif.nent_name,
            notif.nent_stringcount,
            notif.nent_floatcount,
            count
        ));
        return;
    }
    switch(net_type)
    {
        case MSG_ANNCE:
        {
            #ifdef CSQC
            Local_Notification_sound(
                notif.nent_channel,
                notif.nent_snd,
                notif.nent_vol,
                notif.nent_position
            );
            #else
            backtrace("MSG_ANNCE on server?... Please notify Samual immediately!\n");
            #endif
            break;
        }
        case MSG_INFO:
        {
            print(
                Local_Notification_sprintf(
                    notif.nent_string,
                    notif.nent_args,
                    s1, s2, s3, s4,
                    f1, f2, f3, f4)
            );
            #ifdef CSQC
            if(notif.nent_icon != "")
            {
                if ( notif.nent_iconargs != "" )
                {
                    notif.nent_icon = Local_Notification_sprintf(
                        notif.nent_icon,notif.nent_iconargs,
                        s1, s2, s3, s4, f1, f2, f3, f4);
                    // remove the newline added by Local_Notification_sprintf
                    notif.nent_icon = strzone(substring(notif.nent_icon,0,strlen(notif.nent_icon)-1));
                }
                Local_Notification_HUD_Notify_Push(
                    notif.nent_icon,
                    notif.nent_hudargs,
                    s1, s2, s3, s4,
                    f1, f2, f3, f4);
            }
            #endif
            break;
        }
        #ifdef CSQC
        case MSG_CENTER:
        {
            Local_Notification_centerprint_generic(
                Local_Notification_sprintf(
                    notif.nent_string,
                    notif.nent_args,
                    s1, s2, s3, s4,
                    f1, f2, f3, f4),
                notif.nent_durcnt,
                notif.nent_cpid,
                f1, f2);
            break;
        }
        #endif
        case MSG_MULTI:
        {
            if(notif.nent_msginfo)
            if(notif.nent_msginfo.nent_enabled)
            {
                Local_Notification_WOVA(
                    MSG_INFO,
                    notif.nent_msginfo.nent_id,
                    notif.nent_msginfo.nent_stringcount,
                    notif.nent_msginfo.nent_floatcount,
                    s1, s2, s3, s4,
                    f1, f2, f3, f4);
            }
            #ifdef CSQC
            if(notif.nent_msgannce)
            if(notif.nent_msgannce.nent_enabled)
            {
                Local_Notification_WOVA(
                    MSG_ANNCE,
                    notif.nent_msgannce.nent_id,
                    0, 0,
                    "", "", "", "",
                    0, 0, 0, 0);
            }
            if(notif.nent_msgcenter)
            if(notif.nent_msgcenter.nent_enabled)
            {
                Local_Notification_WOVA(
                    MSG_CENTER,
                    notif.nent_msgcenter.nent_id,
                    notif.nent_msgcenter.nent_stringcount,
                    notif.nent_msgcenter.nent_floatcount,
                    s1, s2, s3, s4,
                    f1, f2, f3, f4);
            }
            #endif
            break;
        }
        case MSG_CHOICE:
        {
            entity found_choice;
            if(notif.nent_challow_var && (warmup_stage || (notif.nent_challow_var == 2)))
            {
                switch(cvar(sprintf("notification_%s", notif.nent_name)))
                {
                    case 1: found_choice = notif.nent_optiona; break;
                    case 2: found_choice = notif.nent_optionb; break;
                    default: return; // not enabled anyway
                }
            }
            else { found_choice = notif.nent_optiona; }
            Local_Notification_WOVA(
                found_choice.nent_type,
                found_choice.nent_id,
                found_choice.nent_stringcount,
                found_choice.nent_floatcount,
                s1, s2, s3, s4,
                f1, f2, f3, f4);
        }
    }
}
string Local_Notification_sprintf (string input, string args, string s1, string s2, string s3, string s4, int f1, float f2, float f3, float f4)
Definition at line 1201 of file notifications.qc.
References arg_slot, car(), cdr(), MakeConsoleSafe(), NOTIF_ARGUMENT_LIST, NOTIF_HIT_MAX, NOTIF_HIT_UNKNOWN, NOTIF_MAX_ARGS, strcat(), and strtolower().
Referenced by Local_Notification().
{
    #ifdef NOTIFICATIONS_DEBUG
    Debug_Notification(sprintf(
        "Local_Notification_sprintf('%s^7', '%s', %s, %s);\n",
        MakeConsoleSafe(input),
        args,
        MakeConsoleSafe(sprintf("'%s^7', '%s^7', '%s^7', '%s^7'", s1, s2, s3, s4)),
        sprintf("%d, %d, %d, %d", f1, f2, f3, f4)
    ));
    #endif
    string selected;
    int sel_num;
    for(sel_num = 0; sel_num < NOTIF_MAX_ARGS; ++sel_num) { arg_slot[sel_num] = ""; }
    string tmp_s;
    for(sel_num = 0;(args != "");)
    {
        selected = car(args); args = cdr(args);
        NOTIF_HIT_MAX(NOTIF_MAX_ARGS, "Local_Notification_sprintf");
        switch(strtolower(selected))
        {
            #ifdef CSQC
            #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS_SV(selected,result)    case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS(selected,result)       case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_SV(selected,result)
            #define ARG_CASE_ARG_DC(selected,result)
            #else
            #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS_SV(selected,result)    case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_CS(selected,result)
            #define ARG_CASE_ARG_SV(selected,result)       case selected: { arg_slot[sel_num] = result; ++sel_num; break; }
            #define ARG_CASE_ARG_DC(selected,result)
            #endif
            #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
            NOTIF_ARGUMENT_LIST
            #undef ARG_CASE
            #undef ARG_CASE_ARG_DC
            #undef ARG_CASE_ARG_SV
            #undef ARG_CASE_ARG_CS
            #undef ARG_CASE_ARG_CS_SV
            #undef ARG_CASE_ARG_CS_SV_DC
            #undef ARG_CASE_ARG_CS_SV_HA
            default: NOTIF_HIT_UNKNOWN(NOTIF_MAX_ARGS, "Local_Notification_sprintf")
        }
    }
    return sprintf(
        strcat(input, "\n"),
        arg_slot[0],
        arg_slot[1],
        arg_slot[2],
        arg_slot[3],
        arg_slot[4],
        arg_slot[5],
        arg_slot[6]
    );
}
void Local_Notification_WOVA (int net_type, float net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
Definition at line 1662 of file notifications.qc.
References EIGHT_VARS_TO_VARARGS_VARLIST, and Local_Notification().
Referenced by Local_Notification().
{
    #define VARITEM(stringc,floatc,args) \
        if((stringcount == stringc) && (floatcount == floatc)) \
            { Local_Notification(net_type, net_name, args); return; }
    EIGHT_VARS_TO_VARARGS_VARLIST
    #undef VARITEM
    Local_Notification(net_type, net_name); // some notifications don't have any arguments at all
}
string Notification_CheckArgs_TypeName (float net_type, float net_name)
Definition at line 67 of file notifications.qc.
References CHECKARG_TYPENAME.
Referenced by Local_Notification().
{
    // check supplied type and name for errors
    string checkargs = "";
    #define CHECKARG_TYPENAME(type) case MSG_##type: \
        { if(!net_name || (net_name > NOTIF_##type##_COUNT)) \
        { checkargs = sprintf("Improper name: %d!", net_name); } break; }
    switch(net_type)
    {
        CHECKARG_TYPENAME(ANNCE)
        CHECKARG_TYPENAME(INFO)
        CHECKARG_TYPENAME(CENTER)
        CHECKARG_TYPENAME(MULTI)
        CHECKARG_TYPENAME(CHOICE)
        default: { checkargs = sprintf("Improper type: %d!", checkargs, net_type); break; }
    }
    #undef CHECKARG_TYPENAME
    return checkargs;
}
string Process_Notif_Args (float arg_type, string args, string notiftype, string notifname)
Definition at line 314 of file notifications.qc.
References car(), cdr(), ftos(), LOG_INFOF, NOTIF_ARGUMENT_LIST, notif_error, NOTIF_MAX_ARGS, NOTIF_MAX_DURCNT, NOTIF_MAX_HUDARGS, stof(), strcat(), and strtolower().
Referenced by Create_Notification_Entity().
{
    string selected, remaining = args;
    float sel_num = 0;
    for (;(remaining != "");)
    {
        selected = car(remaining); remaining = cdr(remaining);
        switch(arg_type)
        {
            case 1: // normal args
            {
                if(sel_num == NOTIF_MAX_ARGS)
                {
                    LOG_INFOF(
                        strcat(
                            "^1NOTIFICATION HAS TOO MANY ARGUMENTS: ",
                            "^7net_type = %s, net_name = %s, max args = %d.\n"
                        ),
                        notiftype,
                        notifname,
                        NOTIF_MAX_ARGS
                    );
                    notif_error = true;
                    break;
                }
                switch(strtolower(selected))
                {
                    #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_CS_SV(selected,result)    case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_CS(selected,result)       case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_SV(selected,result)       case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_DC(selected,result)
                    #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                    NOTIF_ARGUMENT_LIST
                    #undef ARG_CASE
                    #undef ARG_CASE_ARG_DC
                    #undef ARG_CASE_ARG_SV
                    #undef ARG_CASE_ARG_CS
                    #undef ARG_CASE_ARG_CS_SV
                    #undef ARG_CASE_ARG_CS_SV_DC
                    #undef ARG_CASE_ARG_CS_SV_HA
                    default:
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: ",
                                "^7net_type = %s, net_name = %s, args arg = '%s'.\n"
                            ),
                            notiftype,
                            notifname,
                            selected
                        );
                        notif_error = true;
                        break;
                    }
                }
                break;
            }
            case 2: // hudargs
            {
                if(sel_num == NOTIF_MAX_HUDARGS)
                {
                    LOG_INFOF(
                        strcat(
                            "^1NOTIFICATION HAS TOO MANY ARGUMENTS: ",
                            "^7net_type = %s, net_name = %s, max hudargs = %d.\n"
                        ),
                        notiftype,
                        notifname,
                        NOTIF_MAX_HUDARGS
                    );
                    notif_error = true;
                    break;
                }
                switch(strtolower(selected))
                {
                    #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_CS_SV_DC(selected,result)
                    #define ARG_CASE_ARG_CS_SV(selected,result)
                    #define ARG_CASE_ARG_CS(selected,result)
                    #define ARG_CASE_ARG_SV(selected,result)
                    #define ARG_CASE_ARG_DC(selected,result)
                    #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                    NOTIF_ARGUMENT_LIST
                    #undef ARG_CASE
                    #undef ARG_CASE_ARG_DC
                    #undef ARG_CASE_ARG_SV
                    #undef ARG_CASE_ARG_CS
                    #undef ARG_CASE_ARG_CS_SV
                    #undef ARG_CASE_ARG_CS_SV_DC
                    #undef ARG_CASE_ARG_CS_SV_HA
                    default:
                    {
                        LOG_INFOF(
                            strcat(
                                "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: ",
                                "^7net_type = %s, net_name = %s, hudargs arg = '%s'.\n"
                            ),
                            notiftype,
                            notifname,
                            selected
                        );
                        notif_error = true;
                        break;
                    }
                }
                break;
            }
            case 3: // durcnt
            {
                if(sel_num == NOTIF_MAX_DURCNT)
                {
                    LOG_INFOF(
                        strcat(
                            "^1NOTIFICATION HAS TOO MANY ARGUMENTS: ",
                            "^7net_type = %s, net_name = %s, max durcnt = %d.\n"
                        ),
                        notiftype,
                        notifname,
                        NOTIF_MAX_DURCNT
                    );
                    notif_error = true;
                    break;
                }
                switch(strtolower(selected))
                {
                    #define ARG_CASE_ARG_CS_SV_HA(selected,result)
                    #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: { ++sel_num; break; }
                    #define ARG_CASE_ARG_CS_SV(selected,result)
                    #define ARG_CASE_ARG_CS(selected,result)
                    #define ARG_CASE_ARG_SV(selected,result)
                    #define ARG_CASE_ARG_DC(selected,result)       case selected: { ++sel_num; break; }
                    #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                    NOTIF_ARGUMENT_LIST
                    #undef ARG_CASE
                    #undef ARG_CASE_ARG_DC
                    #undef ARG_CASE_ARG_SV
                    #undef ARG_CASE_ARG_CS
                    #undef ARG_CASE_ARG_CS_SV
                    #undef ARG_CASE_ARG_CS_SV_DC
                    #undef ARG_CASE_ARG_CS_SV_HA
                    default:
                    {
                        if(ftos(stof(selected)) != "") { ++sel_num; }
                        else
{
                            LOG_INFOF(
                                strcat(
                                    "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: ",
                                    "^7net_type = %s, net_name = %s, durcnt arg = '%s'.\n"
                                ),
                                notiftype,
                                notifname,
                                selected
                            );
                            notif_error = true;
                        }
                        break;
                    }
                }
                break;
            }
        }
    }
    return args;
}
string Process_Notif_Line (int typeId, bool chat, string input, string notiftype, string notifname, string stringtype)
Definition at line 267 of file notifications.qc.
References autocvar_notification_allow_chatboxprint, LOG_INFOF, MSG_INFO, notif_error, strcat(), strlen(), and substring().
{
    #ifdef CSQC
    if(typeId == MSG_INFO)
    {
        if((chat && autocvar_notification_allow_chatboxprint)
            || (autocvar_notification_allow_chatboxprint == 2))
        {
            // pass 1: add ETX char at beginning of line
            input = strcat("\{3}", input);
            // pass 2: add ETX char at end of each new line (so that
            // messages with multiple lines are put through chatbox too)
            input = strreplace("\n", "\n\{3}", input);
            // pass 3: strip trailing ETX char
            if(substring(input, (strlen(input) - 1), 1) == "\{3}")
                { input = substring(input, 0, (strlen(input) - 1)); }
        }
    }
    #endif
    // done to both MSG_INFO and MSG_CENTER
    if(substring(input, (strlen(input) - 1), 1) == "\n")
    {
        LOG_INFOF(
            strcat(
                "^1TRAILING NEW LINE AT END OF NOTIFICATION: ",
                "^7net_type = %s, net_name = %s, string = %s.\n"
            ),
            notiftype,
            notifname,
            stringtype
        );
        notif_error = true;
        input = substring(input, 1, (strlen(input) - 1));
    }
    return input;
}