Xonotic: common/items/item/pickup.qh File Reference
pickup.qh File Reference
#include <common/items/inventory.qh>
#include <common/items/item.qh>
Macros
#define PICKUP_H
Functions
LOG_INFOF ("%s: %s\n", etos(this), this.m_name)
Macro Definition Documentation
#define PICKUP_H
Definition at line 2 of file pickup.qh.
Function Documentation
LOG_INFOF ("%s: %s\n" , etos(this) , this. m_name)
Referenced by BGMScript_InitEntity(), botframe_deleteuselesswaypoints(), CheckSendCvars(), CLIENT_COMMAND(), Cmd_HUD_SetFields(), Create_Notification_Entity(), Create_Notification_Entity_Annce(), Create_Notification_Entity_Choice(), Create_Notification_Entity_InfoCenter(), Create_Notification_Entity_Multi(), CSQC_Ent_Remove(), CSQC_Ent_Update(), CSQC_Init(), CSQC_Parse_CenterPrint(), CSQC_Parse_Print(), CSQC_Parse_StuffCmd(), CSQC_Parse_TempEntity(), CSQCPlayer_ModelAppearance_PostUpdate(), cvar_settemp(), cvar_settemp_restore(), damage_explosion_calcpush(), GameCommand(), GameCommand_macro_help(), GENERIC_COMMAND(), GenericCommand_macro_help(), HUD_Panel_ExportCfg(), IMPULSE(), LocalCommand_macro_help(), m_init(), NET_HANDLE(), Process_Notif_Args(), Process_Notif_Line(), QuickMenu_Open(), RadiusDamageForSource(), RUN_ALL_TESTS(), spawnfunc(), TEST(), TEST_Run(), turret_draw2d(), UpdateNotification_URI_Get_Callback(), URI_Get_Callback(), and url_URI_Get_Callback().