Xonotic: common/gamemodes/gamemode/keepaway/sv_keepaway.qh File Reference
sv_keepaway.qh File Reference
#include <common/mutators/base.qh>
#include <common/scores.qh>
Functions
void ka_DropEvent (entity plyr)
void ka_Initialize ()
REGISTER_MUTATOR (ka, false)
STATIC_INIT (g_kaballs)
void (entity this) havocbot_role_ka_carrier
Variables
IntrusiveList g_kaballs
const int KA_BALL_COUNT = 1
entity ka_Handler
Function Documentation
void ka_DropEvent (entity plyr)
Definition at line 165 of file sv_keepaway.qc.
References ATTEN_NONE, autocvar_g_keepawayball_respawntime, CH_TRIGGER, crandom, DAMAGE_YES, EF_NODRAW, entity(), ka_EventLog(), ka_PlayerReset(), ka_RespawnBall(), ka_TouchEvent(), MOVETYPE_BOUNCE, navigation_dynamicgoal_set(), NULL, set_movetype(), setorigin(), setthink, sound, SPRITERULE_DEFAULT, time, and VOL_BASE.
Referenced by MUTATOR_HOOKFUNCTION(), and STATIC_INIT().
 {
     entity ball = player.ballcarried;
     if(!ball) { return; }
     // reset the ball
     setattachment(ball, NULL, "");
     set_movetype(ball, MOVETYPE_BOUNCE);
     ball.wait = time + 1;
     settouch(ball, ka_TouchEvent);
     setthink(ball, ka_RespawnBall);
     ball.nextthink = time + autocvar_g_keepawayball_respawntime;
     ball.takedamage = DAMAGE_YES;
     ball.effects &= ~EF_NODRAW;
     setorigin(ball, player.origin + '0 0 10');
     ball.velocity = '0 0 200' + '0 100 0'*crandom() + '100 0 0'*crandom();
     ball.owner = NULL;
     navigation_dynamicgoal_set(ball, player);
     // messages and sounds
     ka_EventLog("dropped", player);
     Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_KEEPAWAY_DROPPED, player.netname);
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_KEEPAWAY_DROPPED, player.netname);
     sound(NULL, CH_TRIGGER, SND_KA_DROPPED, VOL_BASE, ATTEN_NONE); // ATTEN_NONE (it's a sound intended to be heard anywhere)
     // waypoints
     WaypointSprite_Spawn(WP_KaBall, 0, 0, ball, '0 0 64', NULL, ball.team, ball, waypointsprite_attachedforcarrier, false, RADARICON_FLAGCARRIER);
     WaypointSprite_UpdateRule(ball.waypointsprite_attachedforcarrier, 0, SPRITERULE_DEFAULT);
     WaypointSprite_Ping(ball.waypointsprite_attachedforcarrier);
     ka_PlayerReset(player);
 }
void ka_Initialize ()
Definition at line 268 of file sv_keepaway.qc.
References ka_Handler, ka_Handler_CheckBall(), setthink, and time.
Referenced by REGISTER_MUTATOR().
 {
     ka_Handler = new(ka_Handler);
     setthink(ka_Handler, ka_Handler_CheckBall);
     ka_Handler.nextthink = time;
 }
REGISTER_MUTATOR (ka , false)
Definition at line 7 of file sv_keepaway.qh.
References GameRules_scoring, ka_Initialize(), MUTATOR_ONADD, MUTATOR_STATIC, SFL_SORT_PRIO_PRIMARY, and SFL_SORT_PRIO_SECONDARY.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_scoring(0, SFL_SORT_PRIO_PRIMARY, 0, {
             field(SP_KEEPAWAY_PICKUPS, "pickups", 0);
             field(SP_KEEPAWAY_CARRIERKILLS, "bckills", 0);
             field(SP_KEEPAWAY_BCTIME, "bctime", SFL_SORT_PRIO_SECONDARY);
         });
         ka_Initialize();
     }
     return false;
 }
STATIC_INIT (g_kaballs)
Definition at line 28 of file sv_keepaway.qh.
References entity(), havocbot_role_ka_carrier(), havocbot_role_ka_collector(), IL_NEW, ka_DropEvent(), and void().
 { g_kaballs = IL_NEW(); }
void (entity this)
Referenced by STATIC_INIT().
Variable Documentation
IntrusiveList g_kaballs
Definition at line 27 of file sv_keepaway.qh.
Referenced by havocbot_goalrating_ball(), ka_Handler_CheckBall(), ka_RemoveBalls(), ka_SpawnBall(), and MUTATOR_HOOKFUNCTION().
const int KA_BALL_COUNT = 1
Definition at line 23 of file sv_keepaway.qh.
Referenced by ka_Handler_CheckBall().
entity ka_Handler
Definition at line 25 of file sv_keepaway.qh.
Referenced by ka_Initialize().