Xonotic: server/g_hook.qh File Reference
g_hook.qh File Reference
Functions
void GrappleHookInit ()
void RemoveGrapplingHooks (entity pl)
void RemoveHook (entity this)
Variables
entity hook
const float HOOK_FIRING = BIT(0)
const float HOOK_PULLING = BIT(2)
const float HOOK_RELEASING = BIT(3)
const float HOOK_REMOVING = BIT(1)
vector hook_shotorigin [4]
float hook_state
float hook_time
const float HOOK_WAITING_FOR_RELEASE = BIT(4)
Function Documentation
void GrappleHookInit ()
Definition at line 428 of file g_hook.qc.
References CL_Weapon_GetShotOrg(), g_grappling_hook, hook_shotorigin, and Weapon::wr_init().
Referenced by spawnfunc().
 {
     if(g_grappling_hook)
     {
         hook_shotorigin[0] = '8 8 -12';
         hook_shotorigin[1] = '8 8 -12';
         hook_shotorigin[2] = '8 8 -12';
         hook_shotorigin[3] = '8 8 -12';
     }
     else
     {
         Weapon w = WEP_HOOK;
         w.wr_init(w);
         hook_shotorigin[0] = shotorg_adjust_values(CL_Weapon_GetShotOrg(WEP_HOOK.m_id), false, false, 1);
         hook_shotorigin[1] = shotorg_adjust_values(CL_Weapon_GetShotOrg(WEP_HOOK.m_id), false, false, 2);
         hook_shotorigin[2] = shotorg_adjust_values(CL_Weapon_GetShotOrg(WEP_HOOK.m_id), false, false, 3);
         hook_shotorigin[3] = shotorg_adjust_values(CL_Weapon_GetShotOrg(WEP_HOOK.m_id), false, false, 4);
     }
 }
void RemoveGrapplingHooks (entity pl)
Definition at line 77 of file g_hook.qc.
References hook, MAX_WEAPONSLOTS, MOVETYPE_FLY, MOVETYPE_WALK, NULL, set_movetype(), and weaponentities.
Referenced by ClientDisconnect(), Freeze(), PlayerDamage(), PutObserverInServer(), Teleport_Touch(), and vehicles_enter().
 {
     if(pl.move_movetype == MOVETYPE_FLY)
         set_movetype(pl, MOVETYPE_WALK);
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         if(!pl.(weaponentity))
             continue; // continue incase other slots exist?
         if(pl.(weaponentity).hook)
             delete(pl.(weaponentity).hook);
         pl.(weaponentity).hook = NULL;
     }
     //pl.disableclientprediction = false;
 }
void RemoveHook (entity this)
Definition at line 95 of file g_hook.qc.
References entity(), MOVETYPE_FLY, MOVETYPE_WALK, NULL, realowner, set_movetype(), and weaponentity_fld.
Referenced by Damage(), Freeze(), GrapplingHook_Damage(), GrapplingHookReset(), GrapplingHookThink(), MUTATOR_HOOKFUNCTION(), Unfreeze(), vehicles_spawn(), and WarpZone_Projectile_Touch_ImpactFilter_Callback().
 {
     entity player = this.realowner;
     .entity weaponentity = this.weaponentity_fld;
     if(player.(weaponentity).hook == this)
         player.(weaponentity).hook = NULL;
     if(player.move_movetype == MOVETYPE_FLY)
         set_movetype(player, MOVETYPE_WALK);
     delete(this);
 }
Variable Documentation
entity hook
Definition at line 4 of file g_hook.qh.
Referenced by CL_Weaponentity_Think(), CreatureFrame_FallDamage(), Damage(), FireGrapplingHook(), PlayerThink(), PM_check_hitground(), and RemoveGrapplingHooks().
const float HOOK_FIRING = BIT(0)
Definition at line 10 of file g_hook.qh.
const float HOOK_PULLING = BIT(2)
Definition at line 12 of file g_hook.qh.
Referenced by GrapplingHookThink().
const float HOOK_RELEASING = BIT(3)
Definition at line 13 of file g_hook.qh.
Referenced by GrapplingHookThink().
const float HOOK_REMOVING = BIT(1)
Definition at line 11 of file g_hook.qh.
vector hook_shotorigin[4]
Definition at line 18 of file g_hook.qh.
float hook_state
Definition at line 15 of file g_hook.qh.
float hook_time
Definition at line 8 of file g_hook.qh.
const float HOOK_WAITING_FOR_RELEASE = BIT(4)
Definition at line 14 of file g_hook.qh.