Xonotic: common/gamemodes/gamemode/race/cl_race.qc File Reference
cl_race.qc File Reference
#include "cl_race.qh"
#include <client/draw.qh>
#include <common/mutators/base.qh>
Functions
void HUD_Mod_Race (vector pos, vector mySize)
MUTATOR_HOOKFUNCTION (cl_race, HUD_Physics_showoptional)
MUTATOR_HOOKFUNCTION (cl_race, HUD_StrafeHUD_showoptional)
MUTATOR_HOOKFUNCTION (cl_race, HUD_Score_show)
MUTATOR_HOOKFUNCTION (cl_race, DrawScoreboardItemStats)
MUTATOR_HOOKFUNCTION (cl_race, ShowRankings)
MUTATOR_HOOKFUNCTION (cl_race, DrawScoreboardAccuracy)
MUTATOR_HOOKFUNCTION (cl_race, ShowRaceTimer)
MUTATOR_HOOKFUNCTION (cl_race, TeamRadar_Draw)
int race_CheckName (string net_name)
void race_showTime (string text, vector pos, vector timeText_ofs, float theTime, vector textSize, float f)
REGISTER_MUTATOR (cl_race, true)
Variables
float crecordtime_change_time
float crecordtime_prev
string race_status_name_prev
int race_status_prev
float race_status_time
float srecordtime_change_time
float srecordtime_prev
Function Documentation
HUD_Mod_Race()
void HUD_Mod_Race (vector pos, vector mySize)
Definition at line 41 of file cl_race.qc.
References autocvar_cl_autodemo_delete, autocvar_cl_autodemo_delete_keeprecords, ClientProgsDB, crecordtime_change_time, crecordtime_prev, CTS_RECORD, cvar_set(), db_get(), db_put(), entity(), ftos(), ISGAMETYPE, max(), min(), mod_active, player_localnum, playerslots, ps_primary, RACE_RECORD, race_showTime(), scores_flags, SFL_TIME, shortmapname, stof(), strcat(), teamplay, time, vec2, and vector().
 {
     entity me = playerslots[player_localnum];
     float score = me.(scores(ps_primary));
     if(!(scores_flags(ps_primary) & SFL_TIME) || teamplay) // race/cts record display on HUD
     {
         mod_active = 0; // hide it in this case!
         return; // no records in the actual race
     }
     mod_active = 1;
     // clientside personal record
     string rr;
     if(ISGAMETYPE(CTS))
         rr = CTS_RECORD;
     else
         rr = RACE_RECORD;
     float t = stof(db_get(ClientProgsDB, strcat(shortmapname, rr, "time")));
     if(score && (score < t || !t)) {
         db_put(ClientProgsDB, strcat(shortmapname, rr, "time"), ftos(score));
         if(autocvar_cl_autodemo_delete_keeprecords)
         {
             float f = autocvar_cl_autodemo_delete;
             f &= ~1;
             cvar_set("cl_autodemo_delete", ftos(f)); // don't delete demo with new record!
         }
     }
     if(t != crecordtime_prev) {
         crecordtime_prev = t;
         crecordtime_change_time = time;
     }
     vector textPos, medalPos;
     float squareSize;
     if(mySize.x > mySize.y) {
         // text on left side
         squareSize = min(mySize.y, mySize.x/2);
         vector ofs = vec2(0.5 * max(0, mySize.x/2 - squareSize), 0.5 * (mySize.y - squareSize));
         textPos = pos + ofs;
         ofs.x += 0.5 * mySize.x;
         medalPos = pos + ofs;
     } else {
         // text on top
         squareSize = min(mySize.x, mySize.y/2);
         vector ofs = vec2(0.5 * (mySize.x - squareSize), 0.5 * max(0, mySize.y/2 - squareSize));
         textPos = pos + ofs;
         ofs.y += 0.5 * mySize.y;
         medalPos = pos + ofs;
     }
     vector textSize = vec2(squareSize, 0.25 * squareSize);
     race_showTime(_("Personal best"), textPos, eY * 0.25 * squareSize, t, textSize, time - crecordtime_change_time);
     // server record
     t = race_server_record;
     if(t != srecordtime_prev) {
         srecordtime_prev = t;
         srecordtime_change_time = time;
     }
     textPos += eY * 0.5 * squareSize;
     race_showTime(_("Server best"), textPos, eY * 0.25 * squareSize, t, textSize, time - srecordtime_change_time);
     if (race_status != race_status_prev || race_status_name != race_status_name_prev) {
         race_status_time = time + 5;
         race_status_prev = race_status;
         strcpy(race_status_name_prev, race_status_name);
     }
     // race "awards"
     float a = bound(0, race_status_time - time, 1);
     string s = textShortenToWidth(ColorTranslateRGB(race_status_name), squareSize, '1 1 0' * 0.1 * squareSize, stringwidth_colors);
     float rank = 0;
     if(race_status > 0)
         rank = race_CheckName(race_status_name);
     string rankname = count_ordinal(rank);
     vector namepos = medalPos + '0 0.8 0' * squareSize;
     vector rankpos = medalPos + '0 0.15 0' * squareSize;
     if(race_status == 0)
         drawpic_aspect_skin(medalPos, "race_newfail", '1 1 0' * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
     else if(race_status == 1) {
         drawpic_aspect_skin(medalPos + '0.1 0 0' * squareSize, "race_newtime", '1 1 0' * 0.8 * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawcolorcodedstring_aspect(namepos, s, '1 0.2 0' * squareSize, panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawstring_aspect(rankpos, rankname, '1 0.15 0' * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
     } else if(race_status == 2) {
         if(strdecolorize(race_status_name) == strdecolorize(entcs_GetName(player_localnum)) || !race_myrank || race_myrank < rank)
             drawpic_aspect_skin(medalPos + '0.1 0 0' * squareSize, "race_newrankgreen", '1 1 0' * 0.8 * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
         else
             drawpic_aspect_skin(medalPos + '0.1 0 0' * squareSize, "race_newrankyellow", '1 1 0' * 0.8 * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawcolorcodedstring_aspect(namepos, s, '1 0.2 0' * squareSize, panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawstring_aspect(rankpos, rankname, '1 0.15 0' * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
     } else if(race_status == 3) {
         drawpic_aspect_skin(medalPos + '0.1 0 0' * squareSize, "race_newrecordserver", '1 1 0' * 0.8 * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawcolorcodedstring_aspect(namepos, s, '1 0.2 0' * squareSize, panel_fg_alpha * a, DRAWFLAG_NORMAL);
         drawstring_aspect(rankpos, rankname, '1 0.15 0' * squareSize, '1 1 1', panel_fg_alpha * a, DRAWFLAG_NORMAL);
     }
     if (race_status_time - time <= 0) {
         race_status_prev = -1;
         race_status = -1;
         strfree(race_status_name);
         strfree(race_status_name_prev);
     }
 }
MUTATOR_HOOKFUNCTION() [1/8]
MUTATOR_HOOKFUNCTION (cl_race , HUD_Physics_showoptional)
Definition at line 154 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // show the optional physics panel
 }
MUTATOR_HOOKFUNCTION() [2/8]
MUTATOR_HOOKFUNCTION (cl_race , HUD_StrafeHUD_showoptional)
Definition at line 159 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // show the optional strafehud
 }
MUTATOR_HOOKFUNCTION() [3/8]
MUTATOR_HOOKFUNCTION (cl_race , HUD_Score_show)
Definition at line 164 of file cl_race.qc.
References ISGAMETYPE, and spectatee_status.
 {
     return spectatee_status == -1 && ISGAMETYPE(RACE); // hide the score panel while observing
 }
MUTATOR_HOOKFUNCTION() [4/8]
MUTATOR_HOOKFUNCTION (cl_race , DrawScoreboardItemStats)
Definition at line 169 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // hide the item stats panel
 }
MUTATOR_HOOKFUNCTION() [5/8]
MUTATOR_HOOKFUNCTION (cl_race , ShowRankings)
Definition at line 174 of file cl_race.qc.
References ISGAMETYPE, and M_ARGV.
 {
     if(ISGAMETYPE(RACE))
     {
         M_ARGV(0, string) = _("Rankings");
         return true;
     }
 }
MUTATOR_HOOKFUNCTION() [6/8]
MUTATOR_HOOKFUNCTION (cl_race , DrawScoreboardAccuracy)
Definition at line 183 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // accuracy is not a factor in this gamemode
 }
MUTATOR_HOOKFUNCTION() [7/8]
MUTATOR_HOOKFUNCTION (cl_race , ShowRaceTimer)
Definition at line 188 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // show the race timer panel
 }
MUTATOR_HOOKFUNCTION() [8/8]
MUTATOR_HOOKFUNCTION (cl_race , TeamRadar_Draw)
Definition at line 193 of file cl_race.qc.
References ISGAMETYPE.
 {
     return ISGAMETYPE(RACE); // show all competitors in a race
 }
race_CheckName()
int race_CheckName (string net_name)
Definition at line 17 of file cl_race.qc.
References grecordholder, player_localnum, strfree, and strzone().
 {
     int rank = 0;
     string zoned_name = strzone(strdecolorize(entcs_GetName(player_localnum)));
     for (int i = RANKINGS_CNT - 1; i >= 0; --i)
         if (strdecolorize(grecordholder[i]) == zoned_name)
         {
             rank = i + 1;
             break;
         }
     strfree(zoned_name);
     return rank;
 }
race_showTime()
void race_showTime (string text, vector pos, vector timeText_ofs, float theTime, vector textSize, float f)
Definition at line 31 of file cl_race.qc.
References DRAWFLAG_NORMAL, drawstring_aspect(), drawstring_aspect_expanding(), panel_fg_alpha, and TIME_ENCODED_TOSTRING.
Referenced by HUD_Mod_Race().
 {
     drawstring_aspect(pos, text, textSize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     drawstring_aspect(pos + timeText_ofs, TIME_ENCODED_TOSTRING(theTime), textSize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     if (f < 1) {
         drawstring_aspect_expanding(pos, text, textSize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL, f);
         drawstring_aspect_expanding(pos + timeText_ofs, TIME_ENCODED_TOSTRING(theTime), textSize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL, f);
     }
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (cl_race , true)
Variable Documentation
crecordtime_change_time
float crecordtime_change_time
Definition at line 8 of file cl_race.qc.
Referenced by HUD_Mod_Race().
crecordtime_prev
float crecordtime_prev
Definition at line 7 of file cl_race.qc.
Referenced by HUD_Mod_Race().
race_status_name_prev
string race_status_name_prev
Definition at line 14 of file cl_race.qc.
race_status_prev
int race_status_prev
Definition at line 13 of file cl_race.qc.
race_status_time
float race_status_time
Definition at line 12 of file cl_race.qc.
srecordtime_change_time
float srecordtime_change_time
Definition at line 10 of file cl_race.qc.
srecordtime_prev
float srecordtime_prev
Definition at line 9 of file cl_race.qc.