Xonotic: menu/xonotic/picker.qc File Reference
picker.qc File Reference
#include "picker.qh"
Functions
entity makeXonoticPicker ()
void XonoticPicker_cellDraw (entity me, vector cell, vector cellPos)
bool XonoticPicker_cellIsValid (entity me, vector cell)
void XonoticPicker_cellSelect (entity me, vector cell)
void XonoticPicker_configureXonoticPicker (entity me)
void XonoticPicker_draw (entity me)
float XonoticPicker_keyDown (entity me, float key, float ascii, float shift)
float XonoticPicker_mouseDrag (entity me, vector coords)
float XonoticPicker_mouseMove (entity me, vector coords)
float XonoticPicker_mouseRelease (entity me, vector coords)
void XonoticPicker_moveFocus (entity me, vector initialCell, vector step)
Variables
bool pressed
Function Documentation
entity makeXonoticPicker ()
Definition at line 5 of file picker.qc.
References entity(), and NEW.
 {
     entity me;
     me = NEW(XonoticPicker);
     me.configureXonoticPicker(me);
     return me;
 }
void XonoticPicker_cellDraw (entity me, vector cell, vector cellPos)
Definition at line 129 of file picker.qc.
 {
 }
bool XonoticPicker_cellIsValid (entity me, vector cell)
Definition at line 124 of file picker.qc.
 {
     return true;
 }
void XonoticPicker_cellSelect (entity me, vector cell)
Definition at line 119 of file picker.qc.
 {
     me.selectedCell = cell;
 }
void XonoticPicker_configureXonoticPicker (entity me)
Definition at line 13 of file picker.qc.
References eX, and eY.
 {
     me.realCellSize = eX / me.columns + eY / me.rows;
 }
void XonoticPicker_draw (entity me)
Definition at line 133 of file picker.qc.
References draw_alpha, draw_Fill(), getFadedAlpha(), mod(), SUPER, and vector().
 {
     float save;
     me.focusable = !me.disabled;
     save = draw_alpha;
     if(me.disabled)
         draw_alpha *= me.disabledAlpha;
     vector cell, cellPos;
     cell = '0 0 0';
     cellPos = '0 0 0';
     for(cell_y = 0; cell.y < me.rows; ++cell.y)
     {
         cellPos_y = mod(cell.y, me.rows) / me.rows;
         for(cell_x = 0; cell.x < me.columns; ++cell.x)
         {
             if(!me.cellIsValid(me, cell))
                 continue;
             cellPos_x = mod(cell.x, me.columns) / me.columns;
             if(cell == me.selectedCell)
                 draw_Fill(cellPos, me.realCellSize, SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
             else if(cell == me.focusedCell && me.focused)
             {
                 if(!me.pressed || me.focusedCell == me.pressedCell)
                 {
                     me.focusedCellAlpha = getFadedAlpha(me.focusedCellAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
                     draw_Fill(cellPos, me.realCellSize, SKINCOLOR_LISTBOX_FOCUSED, me.focusedCellAlpha);
                 }
             }
             me.cellDraw(me, cell, cellPos);
         }
     }
     draw_alpha = save;
     SUPER(XonoticPicker).draw(me);
 }
float XonoticPicker_keyDown (entity me, float key, float ascii, float shift)
Definition at line 69 of file picker.qc.
References eX, eY, K_DOWNARROW, K_END, K_ENTER, K_HOME, K_INS, K_KP_DOWNARROW, K_KP_END, K_KP_ENTER, K_KP_HOME, K_KP_INS, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_RIGHTARROW, and K_UPARROW.
 {
     switch(key)
     {
         case K_END:
         case K_KP_END:
             // lower left cell then left arrow to select the last valid cell
             me.focusedCell = eY * (me.rows - 1);
         case K_LEFTARROW:
         case K_KP_LEFTARROW:
             me.moveFocus(me, me.focusedCell, '-1 0 0');
             return 1;
         case K_HOME:
         case K_KP_HOME:
             // upper right cell then right arrow to select the first valid cell
             me.focusedCell = eX * (me.columns - 1);
         case K_RIGHTARROW:
         case K_KP_RIGHTARROW:
             me.moveFocus(me, me.focusedCell, '1 0 0');
             return 1;
         case K_UPARROW:
         case K_KP_UPARROW:
             me.moveFocus(me, me.focusedCell, '0 -1 0');
             return 1;
         case K_DOWNARROW:
         case K_KP_DOWNARROW:
             me.moveFocus(me, me.focusedCell, '0 1 0');
             return 1;
         case K_ENTER:
         case K_KP_ENTER:
         case K_INS:
         case K_KP_INS:
             me.cellSelect(me, me.focusedCell);
             return 1;
     }
     return 0;
 }
float XonoticPicker_mouseDrag (entity me, vector coords)
Definition at line 37 of file picker.qc.
 {
     return me.mouseMove(me, coords);
 }
float XonoticPicker_mouseMove (entity me, vector coords)
Definition at line 18 of file picker.qc.
References floor(), and vector().
 {
     vector prevFocusedCell = me.focusedCell;
     me.focusedCell_x = floor(coords.x * me.columns);
     me.focusedCell_y = floor(coords.y * me.rows);
     if(me.focusedCell.x < 0 || me.focusedCell.y < 0 ||
        me.focusedCell.x >= me.columns || me.focusedCell.y >= me.rows)
     {
         me.focusedCell = '-1 -1 0';
         return 0;
     }
     if(me.focusedCell != prevFocusedCell)
         me.focusedCellAlpha = SKINALPHA_LISTBOX_FOCUSED;
     return 1;
 }
float XonoticPicker_mouseRelease (entity me, vector coords)
Definition at line 55 of file picker.qc.
 {
     if(!me.pressed)
         return 0;
     me.mouseMove(me, coords);
     if(me.focusedCell == me.pressedCell)
         me.cellSelect(me, me.focusedCell);
     me.pressed = 0;
     return 1;
 }
void XonoticPicker_moveFocus (entity me, vector initialCell, vector step)
Definition at line 107 of file picker.qc.
References mod().
 {
     me.focusedCell_x = mod(me.focusedCell.x + step.x + me.columns, me.columns);
     me.focusedCell_y = mod(me.focusedCell.y + step.y + me.rows, me.rows);
     if(me.focusedCell != initialCell) // Recursion break
         if(!me.cellIsValid(me, me.focusedCell))
             me.moveFocus(me, initialCell, step);
     me.focusedCellAlpha = SKINALPHA_LISTBOX_FOCUSED;
 }
Variable Documentation
bool pressed
Definition at line 3 of file picker.qc.
Referenced by XonoticPicker::mousePress(), ListBox::mousePress(), InputBox::mousePress(), and Slider::mousePress().