Xonotic: server/pathlib/pathlib.qh File Reference
pathlib.qh File Reference
Macros
#define DEBUGPATHING 0
#define inwater(point) (pointcontents(point) == CONTENT_WATER)
Functions
var bool buildpath_nodefilter (vector n, vector c, vector p)
var float pathlib_cost (entity parent, vector to, float static_cost)
var float pathlib_expandnode (entity node, vector start, vector goal)
float pathlib_expandnode_box (entity node, vector start, vector goal)
float pathlib_expandnode_octagon (entity node, vector start, vector goal)
float pathlib_expandnode_star (entity node, vector start, vector goal)
vector pathlib_flynode (entity this, vector start, vector end, float doedge)
float pathlib_g_euclidean (entity parent, vector to, float static_cost)
float pathlib_g_euclidean_water (entity parent, vector to, float static_cost)
float pathlib_g_static (entity parent, vector to, float static_cost)
float pathlib_g_static_water (entity parent, vector to, float static_cost)
float pathlib_h_diagonal (vector a, vector b)
This heuristic consider both stright and disagonal moves to have teh same cost.
float pathlib_h_diagonal2 (vector a, vector b)
This heuristic consider both stright and disagonal moves, But has a separate cost for diagonal moves.
float pathlib_h_diagonal2sdp (vector preprev, vector prev, vector point, vector end)
This heuristic consider both stright and disagonal moves, But has a separate cost for diagonal moves.
float pathlib_h_diagonal3 (vector a, vector b)
float pathlib_h_euclidean (vector a, vector b)
This heuristic only considers the stright line distance.
float pathlib_h_manhattan (vector a, vector b)
Manhattan Menas we expect to move up,down left or right No diagonal moves espected.
float pathlib_h_none (vector preprev, vector prev)
var float pathlib_heuristic (vector from, vector to)
var bool pathlib_makenode (entity parent, vector start, vector to, vector goal, float cost)
var vector pathlib_movenode (entity this, vector start, vector end, float doedge)
vector pathlib_swimnode (entity this, vector start, vector end, float doedge)
vector pathlib_walknode (entity this, vector start, vector end, float doedge)
vector pathlib_wateroutnode (entity this, vector start, vector end, float doedge)
var float pathlib_wpp_waypointcallback (entity wp, entity wp_prev)
var bool tile_check (entity this, vector where)
bool tile_check_cross (entity this, vector where)
bool tile_check_plus (entity this, vector where)
bool tile_check_star (entity this, vector where)
Variables
entity best_open_node
entity closedlist
entity goal_node
bool is_path_node
vector movenode_boxmax
vector movenode_boxmin
vector movenode_boxup
vector movenode_maxdrop
float movenode_stepsize
vector movenode_stepup
entity openlist
entity path_next
entity path_prev
float pathlib_bestcash_hits
float pathlib_bestcash_saved
float pathlib_bestopen_searched
float pathlib_closed_cnt
float pathlib_foundgoal
float pathlib_gridsize
entity pathlib_list
float pathlib_made_cnt
const float pathlib_maxtime = 60
float pathlib_merge_cnt
float pathlib_movecost
float pathlib_movecost_diag
float pathlib_movecost_waterfactor
bool pathlib_movenode_goodnode
float pathlib_node_c
const float pathlib_node_edgeflag_back = BIT(4)
const float pathlib_node_edgeflag_backleft = BIT(5)
const float pathlib_node_edgeflag_backright = BIT(6)
const float pathlib_node_edgeflag_forward = BIT(3)
const float pathlib_node_edgeflag_forwardleft = BIT(7)
const float pathlib_node_edgeflag_forwardright = BIT(8)
const float pathlib_node_edgeflag_left = BIT(1)
const float pathlib_node_edgeflag_none = BIT(9)
const float pathlib_node_edgeflag_right = BIT(2)
const float pathlib_node_edgeflag_unknown = 0
float pathlib_node_edgeflags
float pathlib_node_f
float pathlib_node_g
float pathlib_node_h
float pathlib_open_cnt
float pathlib_searched_cnt
float pathlib_starttime
const vector PLIB_FORWARD = '0 1 0'
const vector PLIB_RIGHT = '1 0 0'
entity start_node
vector tile_check_down
float tile_check_size
vector tile_check_up
Macro Definition Documentation
#define DEBUGPATHING 0
Definition at line 4 of file pathlib.qh.
#define inwater (point) (pointcontents(point) == CONTENT_WATER)
Definition at line 11 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_g_euclidean_water(), pathlib_g_static_water(), and pathlib_makenode_adaptive().
Function Documentation
var bool buildpath_nodefilter (vector n, vector c, vector p)
Referenced by path_build(), pathlib_astar(), and pathlib_waypointpath_step().
var float pathlib_cost (entity parent, vector to, float static_cost)
Referenced by pathlib_astar(), pathlib_expandnode_starf(), and pathlib_makenode_adaptive().
var float pathlib_expandnode (entity node, vector start, vector goal)
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
float pathlib_expandnode_box (entity node, vector start, vector goal)
Definition at line 223 of file expandnode.qc.
References pathlib_gridsize, pathlib_makenode(), pathlib_movecost, pathlib_open_cnt, v, and vector().
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
 {
     vector v;
     for(v.z = node.origin.z - pathlib_gridsize; v.z <= node.origin.z + pathlib_gridsize; v.z += pathlib_gridsize)
     for(v.y = node.origin.y - pathlib_gridsize; v.y <= node.origin.y + pathlib_gridsize; v.y += pathlib_gridsize)
     for(v.x = node.origin.x - pathlib_gridsize; v.x <= node.origin.x + pathlib_gridsize; v.x += pathlib_gridsize)
     {
         //if(vlen(v - node.origin))
             pathlib_makenode(node,start,v,goal,pathlib_movecost);
     }
     return pathlib_open_cnt;
 }
float pathlib_expandnode_octagon (entity node, vector start, vector goal)
Definition at line 174 of file expandnode.qc.
References pathlib_gridsize, pathlib_makenode(), pathlib_movecost, pathlib_open_cnt, PLIB_FORWARD, PLIB_RIGHT, and vector().
 {
     vector point;
     vector where = node.origin;
     vector f = PLIB_FORWARD * pathlib_gridsize;
     vector r = PLIB_RIGHT   * pathlib_gridsize;
     // Forward
     point = where + f;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Back
     point = where - f;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Right
     point = where + r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Left
     point = where - r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     f = PLIB_FORWARD * pathlib_gridsize * 0.5;
     r = PLIB_RIGHT   * pathlib_gridsize * 0.5;
     // Forward-right
     point = where + f + r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Forward-left
     point = where + f - r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Back-right
     point = where - f + r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     // Back-left
     point = where - f - r;
     pathlib_makenode(node, start, point, goal, pathlib_movecost);
     return pathlib_open_cnt;
 }
float pathlib_expandnode_star (entity node, vector start, vector goal)
Definition at line 95 of file expandnode.qc.
References LOG_TRACE(), pathlib_gridsize, pathlib_makenode(), pathlib_movecost, pathlib_movecost_diag, pathlib_node_edgeflag_back, pathlib_node_edgeflag_backleft, pathlib_node_edgeflag_backright, pathlib_node_edgeflag_forward, pathlib_node_edgeflag_forwardleft, pathlib_node_edgeflag_forwardright, pathlib_node_edgeflag_left, pathlib_node_edgeflag_none, pathlib_node_edgeflag_right, pathlib_node_edgeflag_unknown, pathlib_open_cnt, PLIB_FORWARD, PLIB_RIGHT, tile_check_plus2(), vector(), and vtos().
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
 {
     vector point;
     vector where = node.origin;
     vector f = PLIB_FORWARD * pathlib_gridsize;
     vector r = PLIB_RIGHT   * pathlib_gridsize;
     if (node.pathlib_node_edgeflags == pathlib_node_edgeflag_unknown)
         node.pathlib_node_edgeflags = tile_check_plus2(node, node.origin);
     if(node.pathlib_node_edgeflags == pathlib_node_edgeflag_none)
     {
         LOG_TRACE("Node at ", vtos(node.origin), " not expanable");
         return pathlib_open_cnt;
     }
     // Forward
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_forward)
     {
         point = where + f;
         pathlib_makenode(node, start, point, goal, pathlib_movecost);
     }
     // Back
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_back)
     {
         point = where - f;
         pathlib_makenode(node, start, point, goal, pathlib_movecost);
     }
     // Right
         if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_right)
     {
         point = where + r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost);
     }
     // Left
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_left)
     {
         point = where - r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost);
     }
     // Forward-right
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_forwardright)
     {
         point = where + f + r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost_diag);
     }
     // Forward-left
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_forwardleft)
     {
         point = where + f - r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost_diag);
     }
     // Back-right
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_backright)
     {
         point = where - f + r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost_diag);
     }
     // Back-left
     if (node.pathlib_node_edgeflags & pathlib_node_edgeflag_backleft)
     {
         point = where - f - r;
         pathlib_makenode(node, start, point, goal, pathlib_movecost_diag);
     }
     return pathlib_open_cnt;
 }
vector pathlib_flynode (entity this, vector start, vector end, float doedge)
Definition at line 64 of file movenode.qc.
References fsnap(), MOVE_WORLDONLY, movenode_boxmax, movenode_boxmin, pathlib_gridsize, pathlib_movenode_goodnode, and trace_fraction.
 {
     pathlib_movenode_goodnode = false;
     end.x = fsnap(end.x, pathlib_gridsize);
     end.y = fsnap(end.y, pathlib_gridsize);
     tracebox(start, movenode_boxmin,movenode_boxmax, end, MOVE_WORLDONLY, this);
     if(trace_fraction == 1)
         pathlib_movenode_goodnode = true;
     return end;
 }
float pathlib_g_euclidean (entity parent, vector to, float static_cost)
Definition at line 16 of file costs.qc.
References vlen().
 {
     return parent.pathlib_node_g + vlen(parent.origin - to);
 }
float pathlib_g_euclidean_water (entity parent, vector to, float static_cost)
Definition at line 21 of file costs.qc.
References inwater, pathlib_movecost_waterfactor, and vlen().
Referenced by pathlib_astar().
 {
     if(inwater(to))
         return parent.pathlib_node_g + vlen(parent.origin - to) * pathlib_movecost_waterfactor;
     else
         return parent.pathlib_node_g + vlen(parent.origin - to);
 }
float pathlib_g_static (entity parent, vector to, float static_cost)
Definition at line 3 of file costs.qc.
 {
     return parent.pathlib_node_g + static_cost;
 }
float pathlib_g_static_water (entity parent, vector to, float static_cost)
Definition at line 8 of file costs.qc.
References inwater, and pathlib_movecost_waterfactor.
 {
     if(inwater(to))
         return parent.pathlib_node_g + static_cost * pathlib_movecost_waterfactor;
     else
         return parent.pathlib_node_g + static_cost;
 }
float pathlib_h_diagonal (vector a, vector b)
This heuristic consider both stright and disagonal moves to have teh same cost.
Definition at line 49 of file costs.qc.
References fabs(), max(), and pathlib_movecost.
Referenced by pathlib_astar().
 {
     //h(n) = D * max(abs(n.x-goal.x), abs(n.y-goal.y))
     float hx = fabs(a.x - b.x);
     float hy = fabs(a.y - b.y);
     float h = pathlib_movecost * max(hx,hy);
     return h;
 }
float pathlib_h_diagonal2 (vector a, vector b)
This heuristic consider both stright and disagonal moves, But has a separate cost for diagonal moves.
Definition at line 74 of file costs.qc.
References fabs(), min(), pathlib_movecost, and pathlib_movecost_diag.
 {
     /*
     h_diagonal(n) = min(abs(n.x-goal.x), abs(n.y-goal.y))
     h_straight(n) = (abs(n.x-goal.x) + abs(n.y-goal.y))
     h(n) = D2 * h_diagonal(n) + D * (h_straight(n) - 2*h_diagonal(n)))
     */
     float hx = fabs(a.x - b.x);
     float hy = fabs(a.y - b.y);
     float h_diag = min(hx,hy);
     float h_str = hx + hy;
     float h =  pathlib_movecost_diag * h_diag;
     h += pathlib_movecost * (h_str - 2 * h_diag);
     return h;
 }
float pathlib_h_diagonal2sdp (vector preprev, vector prev, vector point, vector end)
This heuristic consider both stright and disagonal moves, But has a separate cost for diagonal moves.
Definition at line 98 of file costs.qc.
References fabs(), normalize(), pathlib_movecost, pathlib_movecost_diag, vector(), and vlen().
 {
     //h_diagonal(n) = min(abs(n.x-goal.x), abs(n.y-goal.y))
     //h_straight(n) = (abs(n.x-goal.x) + abs(n.y-goal.y))
     //h(n) = D2 * h_diagonal(n) + D * (h_straight(n) - 2*h_diagonal(n)))
     float hx = fabs(point.x - end.x);
     float hy = fabs(point.y - end.y);
     float hz = fabs(point.z - end.z);
     float h_diag = min3(hx,hy,hz);
     float h_str = hx + hy + hz;
     float h =  pathlib_movecost_diag * h_diag;
     h += pathlib_movecost * (h_str - 2 * h_diag);
     vector d1 = normalize(preprev - point);
     vector d2 = normalize(prev    - point);
     float m = vlen(d1-d2);
     return h * m;
 }
float pathlib_h_diagonal3 (vector a, vector b)
Definition at line 122 of file costs.qc.
References fabs(), pathlib_movecost, and pathlib_movecost_diag.
 {
     float hx = fabs(a.x - b.x);
     float hy = fabs(a.y - b.y);
     float hz = fabs(a.z - b.z);
     float h_diag = min3(hx,hy,hz);
     float h_str = hx + hy + hz;
     float h =  pathlib_movecost_diag * h_diag;
     h += pathlib_movecost * (h_str - 2 * h_diag);
     return h;
 }
float pathlib_h_euclidean (vector a, vector b)
This heuristic only considers the stright line distance.
Will usualy mean a lower H then G meaning A* Will speand more and run slower.
Definition at line 65 of file costs.qc.
References vlen().
 {
     return vlen(a - b);
 }
float pathlib_h_manhattan (vector a, vector b)
Manhattan Menas we expect to move up,down left or right No diagonal moves espected.
(like moving bewteen city blocks)
Definition at line 34 of file costs.qc.
References fabs(), and pathlib_gridsize.
 {
     //h(n) = D * (abs(n.x-goal.x) + abs(n.y-goal.y))
     float h  = fabs(a.x - b.x);
     h += fabs(a.y - b.y);
     h *= pathlib_gridsize;
     return h;
 }
float pathlib_h_none (vector preprev, vector prev)
Definition at line 100 of file pathlib.qh.
Referenced by pathlib_waypointpath().
 { return 0; }
var float pathlib_heuristic (vector from, vector to)
Referenced by pathlib_astar(), pathlib_expandnode_starf(), pathlib_makenode_adaptive(), pathlib_waypointpath(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
var bool pathlib_makenode (entity parent, vector start, vector to, vector goal, float cost)
Referenced by pathlib_astar(), pathlib_expandnode_box(), pathlib_expandnode_octagon(), pathlib_expandnode_star(), and pathlib_expandnode_starf().
var vector pathlib_movenode (entity this, vector start, vector end, float doedge)
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
vector pathlib_swimnode (entity this, vector start, vector end, float doedge)
Definition at line 44 of file movenode.qc.
References CONTENT_EMPTY, CONTENT_WATER, fsnap(), MOVE_WORLDONLY, movenode_boxmax, movenode_boxmin, pathlib_gridsize, pathlib_movenode_goodnode, pathlib_wateroutnode(), and trace_fraction.
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
 {
     pathlib_movenode_goodnode = false;
     if(pointcontents(start) != CONTENT_WATER)
         return end;
     end.x = fsnap(end.x, pathlib_gridsize);
     end.y = fsnap(end.y, pathlib_gridsize);
     if(pointcontents(end) == CONTENT_EMPTY)
         return pathlib_wateroutnode(this, start, end, doedge);
     tracebox(start, movenode_boxmin,movenode_boxmax, end, MOVE_WORLDONLY, this);
     if(trace_fraction == 1)
         pathlib_movenode_goodnode = true;
     return end;
 }
vector pathlib_walknode (entity this, vector start, vector end, float doedge)
Definition at line 87 of file movenode.qc.
References a_think(), entity(), fsnap(), LOG_DEBUG, LOG_TRACE(), MOVE_WORLDONLY, movenode_boxmax, movenode_boxmin, movenode_boxup, movenode_maxdrop, movenode_stepsize, movenode_stepup, normalize(), pathlib_gridsize, pathlib_movenode_goodnode, rint(), setorigin(), setthink, spawn(), time, trace_endpos, trace_fraction, vector(), vlen(), and vtos().
Referenced by buildpath_nodefilter_moveskip(), pathlib_astar(), pathlib_close_node(), and pathlib_makenode_adaptive().
 {
     vector point;
     LOG_DEBUG("Walking node from ", vtos(start), " to ", vtos(end));
     pathlib_movenode_goodnode = false;
     end.x = fsnap(end.x,pathlib_gridsize);
     end.y = fsnap(end.y,pathlib_gridsize);
     start.x = fsnap(start.x,pathlib_gridsize);
     start.y = fsnap(start.y,pathlib_gridsize);
     // Find the floor
     traceline(start + movenode_stepup, start - movenode_maxdrop, MOVE_WORLDONLY, this);
     if(trace_fraction == 1.0)
     {
         entity a;
         a = spawn();
         setthink(a, a_think);
         a.nextthink = time;
         setorigin(a, start + movenode_stepup);
         a.pos1 = trace_endpos;
         //start - movenode_maxdrop
         a.cnt = time + 10;
         LOG_TRACE("I cant walk on air!");
         return trace_endpos;
     }
     start = trace_endpos;
     // Find the direcion, without Z
     vector s   = start;
     vector e   = end;
     //e_z = 0; s_z = 0;
     vector direction = normalize(e - s);
     float distance  = vlen(start - end);
     int steps     = rint(distance / movenode_stepsize);
     vector last_point = start;
     for(int i = 1; i < steps; ++i)
     {
         point = last_point + (direction * movenode_stepsize);
         traceline(point + movenode_stepup,point - movenode_maxdrop,MOVE_WORLDONLY,this);
         if(trace_fraction == 1.0)
             return trace_endpos;
         last_point = trace_endpos;
     }
     point = last_point + (direction * movenode_stepsize);
     point.x = fsnap(point.x,pathlib_gridsize);
     point.y = fsnap(point.y,pathlib_gridsize);
     //dprint("end_x:  ",ftos(end_x),  "  end_y:  ",ftos(end_y),"\n");
     //dprint("point_x:",ftos(point_x),"  point_y:",ftos(point_y),"\n\n");
     traceline(point + movenode_stepup, point - movenode_maxdrop,MOVE_WORLDONLY,this);
     if(trace_fraction == 1.0)
         return trace_endpos;
     last_point = trace_endpos;
     tracebox(start + movenode_boxup, movenode_boxmin,movenode_boxmax, last_point + movenode_boxup, MOVE_WORLDONLY, this);
     if(trace_fraction != 1.0)
         return trace_endpos;
     pathlib_movenode_goodnode = true;
     return last_point;
 }
vector pathlib_wateroutnode (entity this, vector start, vector end, float doedge)
Definition at line 10 of file movenode.qc.
References CONTENT_EMPTY, CONTENT_SOLID, fabs(), fsnap(), MOVE_WORLDONLY, movenode_boxmax, movenode_boxmin, pathlib_gridsize, pathlib_movenode_goodnode, trace_endpos, trace_fraction, and vector().
Referenced by pathlib_swimnode().
 {
     vector surface;
     pathlib_movenode_goodnode = false;
     end.x = fsnap(end.x, pathlib_gridsize);
     end.y = fsnap(end.y, pathlib_gridsize);
     traceline(end + ('0 0 0.25' * pathlib_gridsize),end - ('0 0 1' * pathlib_gridsize),MOVE_WORLDONLY,this);
     end = trace_endpos;
     if (!(pointcontents(end - '0 0 1') == CONTENT_SOLID))
         return end;
     for(surface = start ; surface.z < (end.z + 32); ++surface.z)
     {
         if(pointcontents(surface) == CONTENT_EMPTY)
             break;
     }
     if(pointcontents(surface + '0 0 1') != CONTENT_EMPTY)
         return end;
     tracebox(start + '0 0 64', movenode_boxmin,movenode_boxmax, end + '0 0 64', MOVE_WORLDONLY, this);
     if(trace_fraction == 1)
         pathlib_movenode_goodnode = true;
     if(fabs(surface.z - end.z) > 32)
         pathlib_movenode_goodnode = false;
     return end;
 }
var float pathlib_wpp_waypointcallback (entity wp, entity wp_prev)
Referenced by pathlib_waypointpath(), and pathlib_wpp_opencb().
var bool tile_check (entity this, vector where)
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
bool tile_check_cross (entity this, vector where)
Definition at line 43 of file utility.qc.
References location_isok(), MOVE_WORLDONLY, p, PLIB_FORWARD, PLIB_RIGHT, tile_check_down, tile_check_size, tile_check_up, trace_endpos, and vector().
Referenced by pathlib_astar(), and tile_check_star().
 {
     vector p;
     vector f = PLIB_FORWARD * tile_check_size;
     vector r = PLIB_RIGHT   * tile_check_size;
     // forward-right
     p = where + f + r;
     traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, this);
     if (!location_isok(trace_endpos, 1, 0))
         return false;
     // Forward-left
     p = where + f - r;
     traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, this);
     if (!location_isok(trace_endpos, 1, 0))
         return false;
     // Back-right
     p = where - f + r;
     traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, this);
     if (!location_isok(trace_endpos, 1 ,0))
         return false;
     //Back-left
     p = where - f - r;
     traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, this);
     if (!location_isok(trace_endpos, 1, 0))
         return false;
     return true;
 }
bool tile_check_plus (entity this, vector where)
Definition at line 77 of file utility.qc.
References location_isok(), MOVE_WORLDONLY, p, PLIB_FORWARD, PLIB_RIGHT, tile_check_down, tile_check_size, tile_check_up, trace_endpos, and vector().
Referenced by tile_check_star().
 {
     vector p;
     vector f = PLIB_FORWARD * tile_check_size;
     vector r = PLIB_RIGHT   * tile_check_size;
     // forward
     p = where + f;
     traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,this);
     if (!location_isok(trace_endpos,1,0))
         return false;
     //left
     p = where - r;
     traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,this);
     if (!location_isok(trace_endpos,1,0))
         return false;
     // Right
     p = where + r;
     traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,this);
     if (!location_isok(trace_endpos,1,0))
         return false;
     //Back
     p = where - f;
     traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,this);
     if (!location_isok(trace_endpos,1,0))
         return false;
     return true;
 }
bool tile_check_star (entity this, vector where)
Definition at line 206 of file utility.qc.
References tile_check_cross(), and tile_check_plus().
 {
     if(tile_check_plus(this, where))
         return tile_check_cross(this, where);
     return false;
 }
Variable Documentation
entity best_open_node
Definition at line 59 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_cleanup(), pathlib_close_node(), pathlib_getbestopen(), pathlib_makenode_adaptive(), pathlib_wpp_bestopen(), pathlib_wpp_close(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
entity closedlist
Definition at line 19 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_waypointpath(), pathlib_wpp_close(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
entity goal_node
Definition at line 21 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_waypointpath(), pathlib_waypointpath_step(), pathlib_wpp_close(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
bool is_path_node
Definition at line 24 of file pathlib.qh.
vector movenode_boxmax
Definition at line 73 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_flynode(), pathlib_swimnode(), pathlib_walknode(), and pathlib_wateroutnode().
vector movenode_boxmin
Definition at line 74 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_flynode(), pathlib_swimnode(), pathlib_walknode(), and pathlib_wateroutnode().
vector movenode_boxup
Definition at line 72 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_walknode().
vector movenode_maxdrop
Definition at line 71 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_walknode().
float movenode_stepsize
Definition at line 69 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_walknode().
vector movenode_stepup
Definition at line 70 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_walknode().
entity openlist
Definition at line 18 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_expandnode_starf(), pathlib_getbestopen(), pathlib_makenode_adaptive(), pathlib_mknode(), pathlib_waypointpath(), pathlib_wpp_bestopen(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
entity path_next
Definition at line 8 of file pathlib.qh.
entity path_prev
Definition at line 9 of file pathlib.qh.
float pathlib_bestcash_hits
Definition at line 48 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_getbestopen().
float pathlib_bestcash_saved
Definition at line 49 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_getbestopen().
float pathlib_bestopen_searched
Definition at line 47 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_getbestopen().
float pathlib_closed_cnt
Definition at line 43 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_waypointpath(), and pathlib_wpp_close().
float pathlib_foundgoal
Definition at line 54 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_waypointpath(), pathlib_waypointpath_step(), pathlib_wpp_close(), pathlib_wpp_opencb(), pathlib_wpp_openncb(), and plas_think().
float pathlib_gridsize
Definition at line 50 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_expandnode_box(), pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_expandnode_starf(), pathlib_flynode(), pathlib_h_manhattan(), pathlib_nodeatpoint(), pathlib_swimnode(), pathlib_walknode(), pathlib_wateroutnode(), and tile_check_plus2().
entity pathlib_list
Definition at line 7 of file pathlib.qh.
Referenced by pathlib_wpp_bestopen().
float pathlib_made_cnt
Definition at line 44 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_mknode().
const float pathlib_maxtime = 60
Definition at line 57 of file pathlib.qh.
Referenced by pathlib_astar().
float pathlib_merge_cnt
Definition at line 45 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
float pathlib_movecost
Definition at line 51 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_expandnode_box(), pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_h_diagonal(), pathlib_h_diagonal2(), pathlib_h_diagonal2sdp(), pathlib_h_diagonal3(), and pathlib_waypointpath().
float pathlib_movecost_diag
Definition at line 52 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_expandnode_star(), pathlib_h_diagonal2(), pathlib_h_diagonal2sdp(), pathlib_h_diagonal3(), and pathlib_waypointpath().
float pathlib_movecost_waterfactor
Definition at line 53 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_g_euclidean_water(), and pathlib_g_static_water().
bool pathlib_movenode_goodnode
Definition at line 75 of file pathlib.qh.
Referenced by buildpath_nodefilter_moveskip(), pathlib_close_node(), pathlib_flynode(), pathlib_makenode_adaptive(), pathlib_swimnode(), pathlib_walknode(), and pathlib_wateroutnode().
float pathlib_node_c
Definition at line 28 of file pathlib.qh.
const float pathlib_node_edgeflag_back = BIT(4)
Definition at line 34 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_backleft = BIT(5)
Definition at line 35 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_backright = BIT(6)
Definition at line 36 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_forward = BIT(3)
Definition at line 33 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_forwardleft = BIT(7)
Definition at line 37 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_forwardright = BIT(8)
Definition at line 38 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_left = BIT(1)
Definition at line 31 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_none = BIT(9)
Definition at line 39 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_right = BIT(2)
Definition at line 32 of file pathlib.qh.
Referenced by pathlib_expandnode_star(), and tile_check_plus2().
const float pathlib_node_edgeflag_unknown = 0
Definition at line 30 of file pathlib.qh.
Referenced by pathlib_expandnode_star().
float pathlib_node_edgeflags
Definition at line 40 of file pathlib.qh.
float pathlib_node_f
Definition at line 27 of file pathlib.qh.
float pathlib_node_g
Definition at line 25 of file pathlib.qh.
float pathlib_node_h
Definition at line 26 of file pathlib.qh.
float pathlib_open_cnt
Definition at line 42 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_close_node(), pathlib_expandnode_box(), pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_expandnode_starf(), pathlib_getbestopen(), pathlib_mknode(), pathlib_waypointpath(), pathlib_wpp_close(), pathlib_wpp_opencb(), and pathlib_wpp_openncb().
float pathlib_searched_cnt
Definition at line 46 of file pathlib.qh.
Referenced by pathlib_astar(), pathlib_makenode_adaptive(), pathlib_nodeatpoint(), and pathlib_waypointpath().
float pathlib_starttime
Definition at line 56 of file pathlib.qh.
Referenced by pathlib_astar(), and pathlib_waypointpath().
const vector PLIB_FORWARD = '0 1 0'
Definition at line 13 of file pathlib.qh.
Referenced by pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_expandnode_starf(), tile_check_cross(), tile_check_plus(), and tile_check_plus2().
const vector PLIB_RIGHT = '1 0 0'
Definition at line 15 of file pathlib.qh.
Referenced by pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_expandnode_starf(), tile_check_cross(), tile_check_plus(), and tile_check_plus2().
entity start_node
Definition at line 22 of file pathlib.qh.
Referenced by pathlib_waypointpath(), and pathlib_waypointpath_step().
vector tile_check_down
Definition at line 62 of file pathlib.qh.
Referenced by pathlib_astar(), tile_check_cross(), tile_check_plus(), and tile_check_plus2().
float tile_check_size
Definition at line 63 of file pathlib.qh.
Referenced by pathlib_astar(), tile_check_cross(), and tile_check_plus().
vector tile_check_up
Definition at line 61 of file pathlib.qh.
Referenced by pathlib_astar(), tile_check_cross(), tile_check_plus(), and tile_check_plus2().