Xonotic: dpdefs/csprogsdefs.qh File Reference
csprogsdefs.qh File Reference
#include "upstream/csprogsdefs.qc"
Macros
#define drawcharacter drawcharacter_builtin
#define drawcolorcodedstring drawcolorcodedstring_builtin
#define drawcolorcodedstring2 drawcolorcodedstring2_builtin
#define drawfill drawfill_builtin
#define drawpic drawpic_builtin
#define drawsetcliparea drawsetcliparea_builtin
#define drawstring drawstring_builtin
#define false _false
#define FALSE _FALSE
#define particleeffectnum _particleeffectnum
#define pointparticles __pointparticles
#define setmodel _setmodel
#define spawn _spawn
#define STAT_FRAGLIMIT _STAT_FRAGLIMIT
#define STAT_MOVEVARS_GRAVITY _STAT_MOVEVARS_GRAVITY
#define STAT_MOVEVARS_TICRATE _STAT_MOVEVARS_TICRATE
#define STAT_MOVEVARS_TIMESCALE _STAT_MOVEVARS_TIMESCALE
#define STAT_TIMELIMIT _STAT_TIMELIMIT
#define stringwidth stringwidth_builtin
#define trailparticles __trailparticles
#define true _true
#define TRUE _TRUE
#define use use1
Functions
vector (float skel, float bonenum) _skel_get_boneabs_hidden = #269
vector (entity ent, float tagindex) _gettaginfo_hidden = #452
void (entity this, entity actor, entity trigger) use
void (vector ang) _makevectors_hidden
void (float skel, float bonenum, vector org) _skel_set_bone_hidden
void (vector org, float radius, vector lightcolours) _adddynamiclight_hidden
Macro Definition Documentation
drawcharacter
#define drawcharacter drawcharacter_builtin
Definition at line 24 of file csprogsdefs.qh.
drawcolorcodedstring
#define drawcolorcodedstring drawcolorcodedstring_builtin
Definition at line 27 of file csprogsdefs.qh.
drawcolorcodedstring2
#define drawcolorcodedstring2 drawcolorcodedstring2_builtin
Definition at line 28 of file csprogsdefs.qh.
drawfill
#define drawfill drawfill_builtin
Definition at line 25 of file csprogsdefs.qh.
drawpic
#define drawpic drawpic_builtin
Definition at line 22 of file csprogsdefs.qh.
drawsetcliparea
#define drawsetcliparea drawsetcliparea_builtin
Definition at line 26 of file csprogsdefs.qh.
drawstring
#define drawstring drawstring_builtin
Definition at line 23 of file csprogsdefs.qh.
false
#define false _false
Definition at line 6 of file csprogsdefs.qh.
FALSE
#define FALSE _FALSE
Definition at line 8 of file csprogsdefs.qh.
particleeffectnum
#define particleeffectnum _particleeffectnum
Definition at line 11 of file csprogsdefs.qh.
pointparticles
#define pointparticles __pointparticles
Definition at line 13 of file csprogsdefs.qh.
Referenced by generator_draw(), NET_HANDLE(), ons_ControlPoint_Icon_Damage(), Spawn_Draw(), turret_die(), turret_draw(), turret_gibboom(), and W_Model().
setmodel
#define setmodel _setmodel
Definition at line 14 of file csprogsdefs.qh.
spawn
#define spawn _spawn
Definition at line 10 of file csprogsdefs.qh.
STAT_FRAGLIMIT
#define STAT_FRAGLIMIT _STAT_FRAGLIMIT
Definition at line 16 of file csprogsdefs.qh.
STAT_MOVEVARS_GRAVITY
#define STAT_MOVEVARS_GRAVITY _STAT_MOVEVARS_GRAVITY
Definition at line 20 of file csprogsdefs.qh.
STAT_MOVEVARS_TICRATE
#define STAT_MOVEVARS_TICRATE _STAT_MOVEVARS_TICRATE
Definition at line 18 of file csprogsdefs.qh.
STAT_MOVEVARS_TIMESCALE
#define STAT_MOVEVARS_TIMESCALE _STAT_MOVEVARS_TIMESCALE
Definition at line 19 of file csprogsdefs.qh.
STAT_TIMELIMIT
#define STAT_TIMELIMIT _STAT_TIMELIMIT
Definition at line 17 of file csprogsdefs.qh.
stringwidth
#define stringwidth stringwidth_builtin
Definition at line 29 of file csprogsdefs.qh.
Referenced by Cmd_Scoreboard_SetFields(), Draw_ShowNames(), GENERIC_COMMAND(), HUD_RaceTimer(), MapStats_DrawKeyValue(), MapVote_DrawMapItem(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawOthers(), Scoreboard_FixColumnWidth(), Scoreboard_initFieldSizes(), and Scoreboard_Rankings_Draw().
trailparticles
#define trailparticles __trailparticles
Definition at line 12 of file csprogsdefs.qh.
Referenced by fireBullet_antilag(), and fireBullet_trace_callback().
true
#define true _true
Definition at line 5 of file csprogsdefs.qh.
Referenced by MapInfo_Get_ByID().
TRUE
#define TRUE _TRUE
Definition at line 7 of file csprogsdefs.qh.
use
#define use use1
Definition at line 50 of file csprogsdefs.qh.
Referenced by _StartItem(), conveyor_think(), door_reset(), Monster_Appear_Check(), Monster_Spawn(), plat_reset(), plat_use(), relocate_spawnpoint(), spawnfunc(), target_checkpoint_setup(), Teleport_Touch(), train_next(), train_wait(), trigger_push_findtarget(), vehicle_initialize(), and WarpZone_Projectile_Touch().
Function Documentation
vector() [1/2]
vector (float skel, float bonenum) = #269
Referenced by _MapInfo_Generate(), _Movetype_CheckStuck(), _Movetype_CheckWater(), _Movetype_FlyMove(), _Movetype_Impact(), _Movetype_LinkEdict(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_NudgeOutOfSolid_PivotIsKnownGood(), _Movetype_Physics_Follow(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), _Movetype_PushEntity(), _Movetype_PushEntityTrace(), _Movetype_PushMove(), _Movetype_TestEntityPosition(), Accuracy_GetColor(), aim_vec(), angle_snap_vec(), angleofs3(), AnglesTransform_Apply(), AnglesTransform_Invert(), AnglesTransform_Multiply(), AnglesTransform_ToVAngles(), anim_vec(), animdecide_getloweranim(), animdecide_getupperanim(), animdecide_load_if_needed(), animdecide_setframes(), animdecide_setimplicitstate(), antilag_takeback(), antilag_takebackavgvelocity(), AuxiliaryXhair_Draw2D(), bd_close_editor(), bd_move_dozer(), beamsweep(), bobmodel_ofs(), BorderImage_draw(), BorderImage_recalcPositionWithText(), bot_aim(), bot_aimdir(), bot_cmd_aimtarget(), botframe_autowaypoints_fix_from(), botframe_updatedangerousobjects(), buff_Inferno_CalculateTime(), buff_Respawn(), buildpath_nodefilter_directional(), Button_draw(), Button_mouseDrag(), c4_move(), calc_followmodel_ofs(), CheatCommand(), CheckWaterJump(), CL_Weapon_GetShotOrg(), color_hslimage(), compressShortVector(), Container_itemFromPoint(), Container_mouseMove(), Container_resizeNotifyLie(), conveyor_think(), crosshair_getcolor(), CSQC_Demo_Camera(), CSQC_UpdateView(), CSQCPlayer_ApplyBobbing(), CSQCPlayer_ApplyChase(), CSQCPlayer_CalcRefdef(), CSQCPlayer_LOD_Apply(), CSQCPlayer_Physics(), CSQCPlayer_SetCamera(), ctf_CalculatePassVelocity(), ctf_CaptureShield_Touch(), ctf_CheckPassDirection(), ctf_FlagThink(), ctf_Handle_Throw(), Damage(), damage_explosion_calcpush(), debuggoalstack(), debugnodestatus(), decompressShortVector(), decompressShotOrigin(), Dialog_addItemSimple(), door_spawnfield(), Drag_Update(), draw_BorderPicture(), draw_ButtonPicture(), draw_Picture_Aligned(), Draw_ShowNames(), draw_teamradar_background(), draw_teamradar_icon(), draw_teamradar_link(), draw_teamradar_player(), draw_TextWidth(), draw_VertButtonPicture(), DrawAmmoItem(), drawBackground(), drawborderlines(), DrawCAItem(), DrawCircleClippedPic(), DrawDomItem(), DrawNumIcon_expanding(), drawpic_tiled(), DrawReticle(), drawstring_expanding(), explosion_calcpush_getmultiplier(), FindConnectedComponent(), findnearest(), findtrajectorywithleading(), fireBullet_antilag(), FireGrapplingHook(), FireRailgunBullet(), FixPlayermodel(), formatmessage(), frexp(), func_ladder_think(), GameCommand_bbox(), GameCommand_gettaginfo(), GameCommand_trace(), GameTypeVote_DrawGameTypeItem(), generator_draw(), GENERIC_COMMAND(), GenericCommand(), get_closer_dest(), get_shotvelocity(), GetCurrentFov(), GrapplingHookThink(), havocbot_ai(), havocbot_aim(), havocbot_bunnyhop(), havocbot_chooseenemy(), havocbot_ctf_calculate_middlepoint(), havocbot_dodge(), havocbot_gettarget(), havocbot_goalrating_ast_targets(), havocbot_goalrating_items(), havocbot_keyboard_movement(), havocbot_moveto(), havocbot_movetogoal(), havocbot_role_ctf_carrier(), havocbot_role_ctf_defense(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), Headshot(), HUD_Ammo(), HUD_Chat(), HUD_Configure_DrawGrid(), HUD_Contents(), HUD_Crosshair(), HUD_Damage(), HUD_Draw(), Hud_Dynamic_Frame(), HUD_EngineInfo(), HUD_Get_Num_Color(), HUD_GetFontsize(), HUD_HealthArmor(), HUD_InfoMessages(), HUD_Main(), HUD_MinigameBoard(), HUD_MinigameMenu_MouseInput(), HUD_MinigameMenu_SpawnSubEntry(), HUD_MinigameStatus(), HUD_Mod_CA_Draw(), HUD_Mod_CTF(), HUD_Mod_Dom(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_Race(), HUD_mouse_over(), HUD_Notify(), HUD_Panel_Arrow_Action(), HUD_Panel_CheckMove(), HUD_Panel_CheckResize(), HUD_Panel_DrawProgressBar(), HUD_Panel_DrawStrafeHUD(), HUD_Panel_HlBorder(), HUD_Panel_InputEvent(), HUD_Panel_Mouse(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Powerups(), HUD_PressedKeys(), HUD_Quickmenu_DrawEntry(), HUD_RaceTimer(), HUD_Radar(), HUD_Radar_Mouse(), HUD_Score(), HUD_Score_Rankings(), HUD_StrafeHUD(), HUD_Timer(), HUD_Weapons(), hue_mi_ma_to_rgb(), Ice_Think(), Image_updateAspect(), IMPULSE(), info_autoscreenshot_findtarget(), InitGameplayMode(), InputBox_draw(), InputBox_mouseDrag(), InputContainer_mouseMove(), InterpolateOrigin_Do(), InterpolateOrigin_Note(), Item_ItemsTime_Allow(), Item_PreDraw(), jumppad_push(), ka_RespawnBall(), Keepaway::Keepaway ::m_isAlwaysSupported(), kh_Key_Think(), kh_WinnerTeam(), Label_draw(), Label_recalcPositionWithText(), leanmodel_ofs(), lgamma(), LinkDoors(), ListBox_draw(), ListBox_mouseDrag(), ListBox_mouseRelease(), LocalCommand_boxparticles(), m_allocatetooltipbox(), m_draw(), m_keydown(), m_tooltip(), MapVote_Draw(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), minigame_drawcolorcodedstring_wrapped(), minigame_drawstring_wrapped(), ModalController_draw(), Monster::Monster ::mr_anim(), Monster_Attack_Leap_Check(), Monster_CalculateVelocity(), Monster_Damage(), monster_dropitem(), Monster_FindTarget(), monster_makevectors(), Monster_Move(), Monster_Move_2D(), Monster_Move_Target(), Monster_ValidTarget(), monsters_animoverride(), movelib_groundalign4point(), MoveToRandomLocationWithinBounds(), MUTATOR_HOOKFUNCTION(), navigation_checkladders(), navigation_findnearestwaypoint_withdist_except(), navigation_goalrating_timeout_can_be_anticipated(), navigation_markroutes(), navigation_markroutes_checkwaypoint(), navigation_markroutes_inverted(), navigation_poptouchedgoals(), navigation_routerating(), navigation_shortenpath(), NET_HANDLE(), Nexposee_calc(), Nexposee_draw(), nmm_in_mill(), ONREMOVE(), ons_camSetup(), ons_CaptureShield_Touch(), ons_Nearest_ControlPoint_2D(), ons_Teleport(), pathlib_close_node(), pathlib_expandnode_box(), pathlib_expandnode_star(), pathlib_h_diagonal2sdp(), pathlib_h_none(), pathlib_makenode_adaptive(), pathlib_walknode(), pathlib_wateroutnode(), plat_spawn_inside_trigger(), PlayerCorpseDamage(), PlayerDamage(), PlayerEdgeDistance(), PlayerScore_Compare(), PlayerTouchExplode(), PM_Accelerate(), PM_AirAccelerate(), PM_dodging(), PM_dodging_checkpressedkeys(), PM_jetpack(), PolyDrawModelSurface(), Portal_ApplyTransformToPlayerAngle(), Portal_FindSafeOrigin(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_TeleportPlayer(), Portal_Think(), Portal_Touch(), Portal_WillHitPlane(), postMenuDraw(), pp_next_match(), prandomvec(), preMenuDraw(), preMenuInit(), Projectile_Draw(), Projectile_DrawTrail(), ps_move(), QuickMenu_Mouse(), race_GetFractionalLapCount(), RadiusDamageForSource(), RandomItems_SpawnLootItem(), randompos(), relocate_nexball(), relocate_spawnpoint(), remquo(), rgb_to_hsl(), rgb_to_hsv(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), Scoreboard_FixColumnWidth(), Scoreboard_MakeTable(), Scoreboard_Rankings_Draw(), ServerList_Info_Click(), set_tracewalk_dest(), set_tracewalk_dest_2(), shortangle_v(), shortangle_vxy(), Simple_TeleportPlayer(), skel_set_boneabs(), skeleton_from_frames(), Slider_mouseDrag(), solve_cubic_abcd(), solve_quadratic(), solve_shotdirection(), Spawn_Draw(), Spawn_Score(), spawnfunc(), STATIC_INIT(), steerlib_arrive(), steerlib_attract(), steerlib_attract2(), steerlib_beamsteer(), steerlib_flock(), steerlib_flock2d(), steerlib_repel(), steerlib_standoff(), steerlib_swarm(), steerlib_traceavoid(), steerlib_traceavoid_flat(), steerlib_wander(), StrafeHUD_CenterPanel(), StrafeHUD_drawGradient(), StrafeHUD_mixColors(), stringwidth(), SUB_CalcAngleMove(), SUB_CalcAngleMoveEnt(), SUB_CalcMove(), SUB_CalcMove_controller_think(), SUB_NoImpactCheck(), swapInPriorityList(), sys_phys_simulate(), sys_phys_simulate_simple(), sys_phys_update(), target_checkpoint_setup(), teamradar_2dcoord_to_texcoord(), teamradar_3dcoord_to_texcoord(), teamradar_texcoord_to_2dcoord(), teamradar_texcoord_to_3dcoord(), TeamScore_Compare(), TeleportPlayer(), textLengthUpToLength(), textLengthUpToWidth(), tgamma(), tile_check_cross(), tile_check_plus(), tile_check_plus2(), tracewalk(), train_next(), train_wait(), trigger_push_calculatevelocity(), trigger_push_test(), trigger_push_touch(), TrueAimCheck(), ttt_next_match(), turret_construct(), turret_draw2d(), updateConwidths(), vec_bias(), vec_bounds_in(), vec_bounds_out(), vec_to_max(), vec_to_min(), vehicle_aimturret(), vehicle_tossgib(), Vehicles_drawCrosshair(), Vehicles_drawHUD(), vehicles_findgoodexit(), vehicles_reset_colors(), vehicles_showwp(), View_EventChase(), View_NightVision(), View_UpdateFov(), viewloc_PlayerPhysics(), viewmodel_draw(), vsnap(), W_CalculateProjectileVelocity(), W_CalculateSpread(), W_HitPlotAnalysis(), W_HitPlotNormalizedUntransform(), W_HitPlotUnnormalizedUntransform(), W_Model(), W_Nexball_Think(), W_SetupShot_Dir_ProjectileSize_Range(), W_WeaponFrame(), WarpZone_Accumulator_AddInverseTransform(), WarpZone_Accumulator_AddTransform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), WarpZone_FindRadius_Recurse(), WarpZone_FixNearClip(), WarpZone_FixView(), WarpZone_Projectile_Touch(), WarpZone_SetUp(), WarpZone_Teleport(), WarpZone_Touch(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZone_TrailParticles(), WarpZoneLib_ExactTrigger_Init(), WarpZoneLib_ExactTrigger_Touch(), WarpZoneLib_MoveOutOfSolid(), WarpZoneLib_NearestPointOnBox(), waypoint_fixorigin_down_dir(), waypoint_getlinkcost(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_getSymmetricalPoint(), waypoint_load_hardwiredlinks(), waypoint_load_links(), waypoint_loadall(), waypoint_remove_fromeditor(), waypoint_setupmodel(), waypoint_spawn(), waypoint_spawn_fromeditor(), waypoint_spawnforteleporter_wz(), waypoint_think(), WeaponStats_ready(), XonoticCampaignList_drawListBoxItem(), XonoticColorpicker_configureXonoticColorpicker(), XonoticColorpicker_mouseDrag(), XonoticColorpickerString_draw(), XonoticColorpickerString_mouseDrag(), XonoticColorpickerString_saveCvars(), XonoticCreditsList_drawListBoxItem(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_draw(), XonoticCvarList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticPicker_draw(), XonoticPicker_mouseDrag(), XonoticPicker_mouseMove(), XonoticPlayerList_drawListBoxItem(), XonoticPlayerModelSelector_draw(), XonoticRegisteredSettingsList_getTooltip_cb(), XonoticResolutionSlider_loadResolutions(), XonoticResolutionSlider_saveCvars(), XonoticScreenshotImage_load(), XonoticScrollPanel::XonoticScrollPanel ::setSelected(), XonoticServerList_drawListBoxItem(), XonoticServerList_keyDown(), XonoticServerList_positionSortButton(), and XonoticWeaponsList_drawListBoxItem().
vector() [2/2]
vector (entity ent, float tagindex) = #452
void() [1/4]
void (entity this, entity actor, entity trigger)
void() [2/4]
void (vector ang)
void() [3/4]
void (float skel, float bonenum, vector org)
void() [4/4]
void (vector org, float radius, vector lightcolours)