Xonotic: menu/xonotic/bigcommandbutton.qc File Reference
bigcommandbutton.qc File Reference
#include "bigcommandbutton.qh"
Functions
entity makeXonoticBigCommandButton (string theText, vector theColor, string theCommand, int theFlags)
entity makeXonoticBigCommandButton_T (string theText, vector theColor, string theCommand, int theFlags, string theTooltip)
void XonoticBigCommandButton_configureXonoticBigCommandButton (entity me, string theText, vector theColor, string theCommand, int theFlags, string theTooltip)
Function Documentation
makeXonoticBigCommandButton()
entity makeXonoticBigCommandButton (string theText, vector theColor, string theCommand, int theFlags)
Definition at line 10 of file bigcommandbutton.qc.
References makeXonoticBigCommandButton_T(), and string_null.
 {
     return makeXonoticBigCommandButton_T(theText, theColor, theCommand, theFlags, string_null);
 }
makeXonoticBigCommandButton_T()
entity makeXonoticBigCommandButton_T (string theText, vector theColor, string theCommand, int theFlags, string theTooltip)
Definition at line 3 of file bigcommandbutton.qc.
References entity(), and NEW.
Referenced by makeTeamButton_T(), and makeXonoticBigCommandButton().
 {
     entity me;
     me = NEW(XonoticBigCommandButton);
     me.configureXonoticBigCommandButton(me, theText, theColor, theCommand, theFlags, theTooltip);
     return me;
 }
XonoticBigCommandButton_configureXonoticBigCommandButton()
void XonoticBigCommandButton_configureXonoticBigCommandButton (entity me, string theText, vector theColor, string theCommand, int theFlags, string theTooltip)
Definition at line 15 of file bigcommandbutton.qc.
 {
     me.configureXonoticCommandButton(me, theText, theColor, theCommand, theFlags, theTooltip);
 }