Xonotic: Monster Class Reference
Monster Class Reference
Public Member Functions
ATTRIB (Monster, m_model, entity)
model
virtual void mr_anim ()
(BOTH?) sets animations for monster
virtual void mr_death ()
(SERVER) called when monster dies
virtual void mr_pain ()
(SERVER) called when monster is damaged
virtual void mr_setup ()
(SERVER) setup monster data
virtual void mr_think ()
(SERVER) logic to run every frame
Public Attributes
vector m_maxs = '0 0 0'
hitbox size
vector m_mins = '-0 -0 -0'
hitbox size
string monster_name = "Monster"
human readable name
int monsterid = 0
string netname = ""
short name
int spawnflags = 0
attributes
Detailed Description
Definition at line 30 of file monster.qh.
Member Function Documentation
Monster::ATTRIB (Monster , m_model , entity)
model
virtual void Monster::mr_anim () inline virtual
(BOTH?) sets animations for monster
Definition at line 54 of file monster.qh.
References ENDCLASS, entity(), TC, and vector().
Referenced by Monster_UpdateModel(), and monsters_animoverride().
 { TC(Monster, this); return false; }
virtual void Monster::mr_death () inline virtual
(SERVER) called when monster dies
Definition at line 50 of file monster.qh.
References TC.
Referenced by Monster_Dead().
 { TC(Monster, this); return false; }
virtual void Monster::mr_pain () inline virtual
(SERVER) called when monster is damaged
Definition at line 52 of file monster.qh.
References TC.
Referenced by Monster_Damage().
 { TC(Monster, this); return damage_take; }
virtual void Monster::mr_setup () inline virtual
(SERVER) setup monster data
Definition at line 46 of file monster.qh.
References TC.
Referenced by Monster_Spawn_Setup().
 { TC(Monster, this); return false; }
virtual void Monster::mr_think () inline virtual
(SERVER) logic to run every frame
Definition at line 48 of file monster.qh.
References TC.
Referenced by Monster_Think().
 { TC(Monster, this); return false; }
Member Data Documentation
vector Monster::m_maxs = '0 0 0'
hitbox size
Definition at line 43 of file monster.qh.
Referenced by invasion_SpawnChosenMonster().
vector Monster::m_mins = '-0 -0 -0'
hitbox size
Definition at line 41 of file monster.qh.
Referenced by invasion_SpawnChosenMonster().
string Monster::monster_name = "Monster"
human readable name
Definition at line 35 of file monster.qh.
int Monster::monsterid = 0
Definition at line 31 of file monster.qh.
Referenced by invasion_SpawnChosenMonster().
string Monster::netname = ""
short name
Definition at line 37 of file monster.qh.
int Monster::spawnflags = 0
attributes
Definition at line 33 of file monster.qh.
The documentation for this class was generated from the following file:
common/monsters/monster.qh