Xonotic: common/turrets/all.qh File Reference
common/turrets/all.qh File Reference
#include "../command/all.qh"
#include "config.qh"
#include "turret.qh"
#include "all.inc"
Defines
#define TURRETS_ALL_H
#define Turrets_from(i) _Turrets_from(i, TUR_Null)
#define get_turretinfo(i) Turrets_from(i)
#define TUR_LAST (Turrets_COUNT - 1)
#define REGISTER_TURRET(id, inst) REGISTER(Turrets, TUR, id, m_id, inst)
Functions
GENERIC_COMMAND (dumpturrets,"Dump all turrets into turrets_dump.txt")
REGISTER_TURRET (Null, NEW(Turret))
Variables
const int TUR_FIRST = 1
Define Documentation
#define get_turretinfo (i) Turrets_from(i)
Definition at line 11 of file all.qh.
Referenced by turret_construct(), turret_die(), and turret_draw2d().
#define REGISTER_TURRET (id, inst) REGISTER(Turrets, TUR, id, m_id, inst)
Definition at line 73 of file all.qh.
#define TUR_LAST (Turrets_COUNT - 1)
Definition at line 71 of file all.qh.
#define TURRETS_ALL_H
Definition at line 2 of file all.qh.
#define Turrets_from (i) _Turrets_from(i, TUR_Null)
Definition at line 10 of file all.qh.
Function Documentation
GENERIC_COMMAND (dumpturrets , "Dump all turrets into turrets_dump.txt")
Definition at line 16 of file all.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, Dump_Turret_Settings(), fclose(), FILE_WRITE, fopen(), GetProgramCommandPrefix(), LOG_INFO, and strcat().
{
    switch(request)
    {
        case CMD_REQUEST_COMMAND:
        {
            #ifdef SVQC
            tur_config_file = -1;
            tur_config_alsoprint = -1;
            string filename = argv(1);
            if(filename == "")
            {
                filename = "turrets_dump.cfg";
                tur_config_alsoprint = false;
            }
            else if(filename == "-")
            {
                filename = "turrets_dump.cfg";
                tur_config_alsoprint = true;
            }
            tur_config_file = fopen(filename, FILE_WRITE);
            if(tur_config_file >= 0)
            {
                Dump_Turret_Settings();
                LOG_INFO(sprintf("Dumping turrets... File located in ^2data/data/%s^7.\n", filename));
                fclose(tur_config_file);
                tur_config_file = -1;
                tur_config_alsoprint = -1;
            }
            else
            {
                LOG_INFO(sprintf("^1Error: ^7Could not open file '%s'!\n", filename));
            }
            #else
            LOG_INFO(_("Turrets dump command only works with sv_cmd.\n"));
            #endif
            return;
        }
        default:
        case CMD_REQUEST_USAGE:
        {
            LOG_INFO(strcat("\nUsage:^3 ", GetProgramCommandPrefix(), " dumpturrets [filename]"));
            LOG_INFO("  Where 'filename' is the file to write (default is turrets_dump.cfg),\n");
            LOG_INFO("  if supplied with '-' output to console as well as default,\n");
            LOG_INFO("  if left blank, it will only write to default.\n");
            return;
        }
    }
}
REGISTER_TURRET (Null , NEW(Turret))
Variable Documentation
const int TUR_FIRST = 1
Definition at line 70 of file all.qh.