Xonotic: common/physics/movetypes/movetypes.qh File Reference
movetypes.qh File Reference
Macros
#define GAMEPLAYFIX_DOWNTRACEONGROUND(s) STAT(GAMEPLAYFIX_DOWNTRACEONGROUND)
#define GAMEPLAYFIX_EASIERWATERJUMP(s) STAT(GAMEPLAYFIX_EASIERWATERJUMP)
#define GAMEPLAYFIX_GRENADEBOUNCESLOPES(s) STAT(GAMEPLAYFIX_GRENADEBOUNCESLOPES)
#define GAMEPLAYFIX_NOAIRBORNCORPSE(s) STAT(GAMEPLAYFIX_NOAIRBORNCORPSE)
#define GAMEPLAYFIX_SLIDEMOVEPROJECTILES(s) STAT(GAMEPLAYFIX_SLIDEMOVEPROJECTILES)
#define GAMEPLAYFIX_STEPDOWN(s) STAT(GAMEPLAYFIX_STEPDOWN)
#define GAMEPLAYFIX_STEPDOWN_MAXSPEED(s) STAT(GAMEPLAYFIX_STEPDOWN_MAXSPEED)
#define GAMEPLAYFIX_STEPMULTIPLETIMES(s) STAT(GAMEPLAYFIX_STEPMULTIPLETIMES)
#define GAMEPLAYFIX_UNSTICKPLAYERS(s) STAT(GAMEPLAYFIX_UNSTICKPLAYERS)
#define GAMEPLAYFIX_WATERTRANSITION(s) STAT(GAMEPLAYFIX_WATERTRANSITION)
#define IS_ONGROUND(s) boolean((s).flags & FL_ONGROUND)
#define IS_ONSLICK(s) boolean((s).flags & FL_ONSLICK)
#define NOAIRBORNCORPSE_ALLOWSUSPENDED(s) STAT(NOAIRBORNCORPSE_ALLOWSUSPENDED)
#define PHYS_JUMPSTEP(s) STAT(MOVEVARS_JUMPSTEP)
#define PHYS_NOSTEP(s) STAT(NOSTEP)
#define PHYS_STEPHEIGHT(s) STAT(MOVEVARS_STEPHEIGHT)
#define PHYS_WALLCLIP(s) STAT(MOVEVARS_WALLCLIP)
#define PHYS_WALLFRICTION(s) STAT(MOVEVARS_WALLFRICTION)
#define SET_ONGROUND(s) ((s).flags |= FL_ONGROUND)
#define SET_ONSLICK(s) ((s).flags |= FL_ONSLICK)
#define UNSET_ONGROUND(s) ((s).flags &= ~FL_ONGROUND)
#define UNSET_ONSLICK(s) ((s).flags &= ~FL_ONSLICK)
#define UPWARD_VELOCITY_CLEARS_ONGROUND(s) STAT(GAMEPLAYFIX_UPVELOCITYCLEARSONGROUND)
Functions
void _Movetype_CheckStuck (entity this)
void _Movetype_CheckVelocity (entity this)
float _Movetype_CheckWater (entity ent)
void _Movetype_CheckWaterTransition (entity ent)
vector _Movetype_ClipVelocity (vector vel, vector norm, float f)
int _Movetype_FlyMove (entity this, float dt, bool applygravity, bool applystepnormal, float stepheight)
void _Movetype_LinkEdict (entity this, float touch_triggers)
void _Movetype_LinkEdict_TouchAreaGrid (entity this)
bool _Movetype_PushEntity (entity this, vector push, float failonstartsolid, bool dolink)
void _Movetype_PushEntityTrace (entity this, vector push)
int _Movetype_UnstickEntity (entity this)
void _Movetype_WallFriction (entity this, vector stepnormal)
void Movetype_Physics_MatchServer (entity this, bool sloppy)
void Movetype_Physics_MatchTicrate (entity this, float tr, bool sloppy)
void Movetype_Physics_NoMatchServer (entity this)
void Movetype_Physics_NoMatchTicrate (entity this, float movedt, bool isclient)
void set_movetype (entity this, int mt)
void (float, float) contentstransition
Variables
entity aiment
const int FL_ONSLICK = BIT(20)
entity groundentity
const int MAX_CLIP_PLANES = 5
float move_didgravity
float move_movetype
float move_nomonsters
vector move_stepnormal
float move_suspendedinair
float move_time
const int MOVEFLAG_GRAVITYUNAFFECTEDBYTICRATE = BIT(2)
const int MOVEFLAG_NOGRAVITYONGROUND = BIT(1)
const int MOVEFLAG_Q2AIRACCELERATE = BIT(0)
const int MOVEFLAG_VALID = BIT(23)
const int MOVETYPE_FAKEPUSH = 13
const int MOVETYPE_QCPLAYER = 150
float pm_time
vector punchangle
const int UNSTICK_FINE = 0
const int UNSTICK_FIXED = 1
const int UNSTICK_STUCK = 2
const int WATERLEVEL_NONE = 0
const int WATERLEVEL_SUBMERGED = 3
const int WATERLEVEL_SWIMMING = 2
const int WATERLEVEL_WETFEET = 1
Macro Definition Documentation
#define GAMEPLAYFIX_DOWNTRACEONGROUND (s) STAT(GAMEPLAYFIX_DOWNTRACEONGROUND)
Definition at line 16 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define GAMEPLAYFIX_EASIERWATERJUMP (s) STAT(GAMEPLAYFIX_EASIERWATERJUMP)
Definition at line 17 of file movetypes.qh.
Referenced by _Movetype_FlyMove().
#define GAMEPLAYFIX_GRENADEBOUNCESLOPES (s) STAT(GAMEPLAYFIX_GRENADEBOUNCESLOPES)
Definition at line 24 of file movetypes.qh.
Referenced by _Movetype_Physics_Toss().
#define GAMEPLAYFIX_NOAIRBORNCORPSE (s) STAT(GAMEPLAYFIX_NOAIRBORNCORPSE)
Definition at line 25 of file movetypes.qh.
Referenced by _Movetype_Physics_Toss().
#define GAMEPLAYFIX_SLIDEMOVEPROJECTILES (s) STAT(GAMEPLAYFIX_SLIDEMOVEPROJECTILES)
Definition at line 23 of file movetypes.qh.
Referenced by _Movetype_Physics_Toss().
#define GAMEPLAYFIX_STEPDOWN (s) STAT(GAMEPLAYFIX_STEPDOWN)
Definition at line 18 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define GAMEPLAYFIX_STEPDOWN_MAXSPEED (s) STAT(GAMEPLAYFIX_STEPDOWN_MAXSPEED)
Definition at line 19 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define GAMEPLAYFIX_STEPMULTIPLETIMES (s) STAT(GAMEPLAYFIX_STEPMULTIPLETIMES)
Definition at line 20 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define GAMEPLAYFIX_UNSTICKPLAYERS (s) STAT(GAMEPLAYFIX_UNSTICKPLAYERS)
Definition at line 21 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define GAMEPLAYFIX_WATERTRANSITION (s) STAT(GAMEPLAYFIX_WATERTRANSITION)
Definition at line 22 of file movetypes.qh.
Referenced by _Movetype_CheckWaterTransition().
#define IS_ONGROUND (s) boolean((s).flags & FL_ONGROUND)
Definition at line 9 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_Step(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), _Movetype_PushEntity(), adaptor_think2use_hittype_splash(), CSQCModel_Hook_PreDraw(), CSQCPlayer_ApplyBobbing(), CSQCPlayer_Physics(), CSQCPlayer_SetCamera(), CSQCProjectile_Check(), CSQCProjectile_SendEntity(), havocbot_bunnyhop(), havocbot_goalrating_items(), havocbot_movetogoal(), is_close_to_ground(), IsFlying(), Monster_Anim(), Monster_Attack_Leap_Check(), Monster_Move(), Monster_Move_2D(), MUTATOR_HOOKFUNCTION(), navigation_markroutes(), navigation_routerating(), player_anim(), PlayerJump(), PM_check_slick(), PM_ClientMovement_UpdateStatus(), Projectile_Draw(), set_tracewalk_dest(), SUB_Friction(), sys_phys_postupdate(), sys_phys_simulate_simple(), and sys_phys_update().
#define IS_ONSLICK (s) boolean((s).flags & FL_ONSLICK)
Definition at line 12 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk(), sys_phys_simulate(), and sys_phys_update().
#define NOAIRBORNCORPSE_ALLOWSUSPENDED (s) STAT(NOAIRBORNCORPSE_ALLOWSUSPENDED)
Definition at line 26 of file movetypes.qh.
Referenced by _Movetype_Physics_Toss().
#define PHYS_JUMPSTEP (s) STAT(MOVEVARS_JUMPSTEP)
Definition at line 32 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define PHYS_NOSTEP (s) STAT(NOSTEP)
Definition at line 31 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define PHYS_STEPHEIGHT (s) STAT(MOVEVARS_STEPHEIGHT)
Definition at line 30 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk(), and CSQCPlayer_ApplySmoothing().
#define PHYS_WALLCLIP (s) STAT(MOVEVARS_WALLCLIP)
Definition at line 35 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), and _Movetype_Physics_Walk().
#define PHYS_WALLFRICTION (s) STAT(MOVEVARS_WALLFRICTION)
Definition at line 33 of file movetypes.qh.
Referenced by _Movetype_Physics_Walk().
#define SET_ONGROUND (s) ((s).flags |= FL_ONGROUND)
Definition at line 10 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), Drag_Finish(), and NET_HANDLE().
#define SET_ONSLICK (s) ((s).flags |= FL_ONSLICK)
Definition at line 13 of file movetypes.qh.
Referenced by PM_check_slick().
#define UNSET_ONGROUND (s) ((s).flags &= ~FL_ONGROUND)
Definition at line 11 of file movetypes.qh.
Referenced by _Movetype_Physics_Step(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), Damage(), Drag_Begin(), Drag_Update(), DropBall(), DropOwner(), GrapplingHookThink(), InitBall(), jumppad_push(), Monster_Attack_Leap(), NET_HANDLE(), PlayerDamage(), PlayerJump(), PM_dodging(), PM_jetpack(), sys_phys_simulate(), TeleportPlayer(), trigger_impulse_touch_directional(), vehicles_enter(), and W_Nexball_Touch().
#define UNSET_ONSLICK (s) ((s).flags &= ~FL_ONSLICK)
Definition at line 14 of file movetypes.qh.
Referenced by PlayerJump(), and PM_check_slick().
#define UPWARD_VELOCITY_CLEARS_ONGROUND (s) STAT(GAMEPLAYFIX_UPVELOCITYCLEARSONGROUND)
Definition at line 27 of file movetypes.qh.
Referenced by _Movetype_Physics_Step(), and _Movetype_Physics_Toss().
Function Documentation
void _Movetype_CheckStuck (entity this)
Definition at line 506 of file movetypes.qc.
References _Movetype_LinkEdict(), _Movetype_TestEntityPosition(), _Movetype_UnstickEntity(), oldorigin, origin, UNSTICK_FINE, UNSTICK_FIXED, UNSTICK_STUCK, and vector().
Referenced by _Movetype_Physics_Walk().
 {
     int unstick = _Movetype_UnstickEntity(this); // sets test position entity
     switch(unstick)
     {
         case UNSTICK_FINE:
             this.oldorigin = this.origin;
             break;
         case UNSTICK_FIXED:
             break; // already sorted
         case UNSTICK_STUCK:
             vector offset = this.oldorigin - this.origin;
             if(!_Movetype_TestEntityPosition(offset))
                 _Movetype_LinkEdict(this, false);
             // couldn't unstick, should we warn about this?
             break;
     }
 }
void _Movetype_CheckVelocity (entity this)
Definition at line 254 of file movetypes.qc.
Referenced by _Movetype_Physics_Step(), _Movetype_Physics_Toss(), and _Movetype_Physics_Walk().
 {
     // if(vlen(this.velocity) < 0.0001)
     // this.velocity = '0 0 0';
 }
float _Movetype_CheckWater (entity ent)
Definition at line 260 of file movetypes.qc.
References CONTENT_EMPTY, DPCONTENTS_LIQUIDSMASK, maxs, mins, origin, vector(), view_ofs, waterlevel, WATERLEVEL_NONE, WATERLEVEL_SUBMERGED, WATERLEVEL_SWIMMING, WATERLEVEL_WETFEET, and watertype.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Walk(), and CSQCPlayer_Physics().
 {
     vector point = this.origin;
     point.z += this.mins.z + 1;
     int nativecontents = pointcontents(point);
     if(this.watertype && this.watertype != nativecontents)
     {
         // dprintf("_Movetype_CheckWater(): Original: '%d', New: '%d'\n", this.watertype, nativecontents);
         if(this.contentstransition)
             this.contentstransition(this.watertype, nativecontents);
     }
     this.waterlevel = WATERLEVEL_NONE;
     this.watertype = CONTENT_EMPTY;
     int supercontents = Mod_Q1BSP_SuperContentsFromNativeContents(nativecontents);
     if(supercontents & DPCONTENTS_LIQUIDSMASK)
     {
         this.watertype = nativecontents;
         this.waterlevel = WATERLEVEL_WETFEET;
         point.z = this.origin.z + (this.mins.z + this.maxs.z) * 0.5;
         if(Mod_Q1BSP_SuperContentsFromNativeContents(pointcontents(point)) & DPCONTENTS_LIQUIDSMASK)
         {
             this.waterlevel = WATERLEVEL_SWIMMING;
             point.z = this.origin.z + this.view_ofs.z;
             if(Mod_Q1BSP_SuperContentsFromNativeContents(pointcontents(point)) & DPCONTENTS_LIQUIDSMASK)
                 this.waterlevel = WATERLEVEL_SUBMERGED;
         }
     }
     return this.waterlevel > 1;
 }
void _Movetype_CheckWaterTransition (entity ent)
Definition at line 294 of file movetypes.qc.
References CONTENT_EMPTY, CONTENT_WATER, and GAMEPLAYFIX_WATERTRANSITION.
Referenced by _Movetype_Physics_Step(), and _Movetype_Physics_Toss().
 {
     int contents = pointcontents(ent.origin);
     if(!ent.watertype)
     {
         // just spawned here
         if(!GAMEPLAYFIX_WATERTRANSITION(ent))
         {
             ent.watertype = contents;
             ent.waterlevel = 1;
             return;
         }
     }
     else if(ent.watertype != contents)
     {
         // dprintf("_Movetype_CheckWaterTransition(): Origin: %s, Direct: '%d', Original: '%d', New: '%d'\n", vtos(ent.origin), pointcontents(ent.origin), ent.watertype, contents);
         if(ent.contentstransition)
             ent.contentstransition(ent.watertype, contents);
     }
     if(contents <= CONTENT_WATER)
     {
         ent.watertype = contents;
         ent.waterlevel = 1;
     }
     else
     {
         ent.watertype = CONTENT_EMPTY;
         ent.waterlevel = (GAMEPLAYFIX_WATERTRANSITION(ent) ? 0 : contents);
     }
 }
vector _Movetype_ClipVelocity (vector vel, vector norm, float f)
Definition at line 525 of file movetypes.qc.
Referenced by _Movetype_FlyMove(), and _Movetype_Physics_Toss().
 {
     vel -= ((vel * norm) * norm) * f;
     if(vel.x > -0.1 && vel.x < 0.1) vel.x = 0;
     if(vel.y > -0.1 && vel.y < 0.1) vel.y = 0;
     if(vel.z > -0.1 && vel.z < 0.1) vel.z = 0;
     return vel;
 }
int _Movetype_FlyMove (entity this, float dt, bool applygravity, bool applystepnormal, float stepheight)
Definition at line 39 of file movetypes.qc.
References _Movetype_ClipVelocity(), _Movetype_PushEntity(), cross, fabs(), FL_WATERJUMP, flags, GAMEPLAYFIX_EASIERWATERJUMP, gravity, groundentity, IS_ONGROUND, MAX_CLIP_PLANES, move_didgravity, move_stepnormal, NULL, origin, PHYS_WALLCLIP, pm_time, SET_ONGROUND, sqrt(), trace_allsolid, trace_endpos, trace_ent, trace_fraction, trace_plane_normal, trace_startsolid, vec3, vector(), and velocity.
Referenced by _Movetype_Physics_Step(), and _Movetype_Physics_Walk().
 {
     move_stepnormal = '0 0 0';
     if(dt <= 0)
         return 0;
     int blocked = 0;
     int i, j, numplanes = 0;
     float time_left = dt, grav = 0;
     vector push;
     vector primal_velocity, original_velocity;
     vector restore_velocity = this.velocity;
     for(i = 0; i < MAX_CLIP_PLANES; ++i)
         planes[i] = '0 0 0';
     if(applygravity)
     {
         this.move_didgravity = 1;
         grav = dt * (this.gravity ? this.gravity : 1) * PHYS_GRAVITY(this);
         if(!GAMEPLAYFIX_NOGRAVITYONGROUND || !IS_ONGROUND(this))
         {
             if(GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
                 this.velocity_z -= grav * 0.5;
             else
                 this.velocity_z -= grav;
         }
     }
     original_velocity = primal_velocity = this.velocity;
     for(int bumpcount = 0;bumpcount < MAX_CLIP_PLANES;bumpcount++)
     {
         if(this.velocity == '0 0 0')
             break;
         push = this.velocity * time_left;
         if(!_Movetype_PushEntity(this, push, true, false))
         {
             // we got teleported by a touch function
             // let's abort the move
             blocked |= 8;
             break;
         }
         // this code is used by MOVETYPE_WALK and MOVETYPE_STEP and SV_UnstickEntity
         // abort move if we're stuck in the world (and didn't make it out)
         if(trace_startsolid && trace_allsolid)
         {
             this.velocity = restore_velocity;
             return 3;
         }
         if(trace_fraction == 1)
             break;
         float my_trace_fraction = trace_fraction;
         vector my_trace_plane_normal = trace_plane_normal;
         if(trace_plane_normal.z)
         {
             if(trace_plane_normal.z > 0.7)
             {
                 // floor
                 blocked |= 1;
                 if(!trace_ent)
                 {
                     //dprint("_Movetype_FlyMove: !trace_ent\n");
                     trace_ent = NULL;
                 }
                 SET_ONGROUND(this);
                 this.groundentity = trace_ent;
             }
         }
         else if(stepheight)
         {
             // step - handle it immediately
             vector org = this.origin;
             vector steppush = '0 0 1' * stepheight;
             if(!_Movetype_PushEntity(this, steppush, true, false))
             {
                 blocked |= 8;
                 break;
             }
             if(!_Movetype_PushEntity(this, push, true, false))
             {
                 blocked |= 8;
                 break;
             }
             float trace2_fraction = trace_fraction;
             steppush = vec3(0, 0, org.z - this.origin_z);
             if(!_Movetype_PushEntity(this, steppush, true, false))
             {
                 blocked |= 8;
                 break;
             }
             // accept the new position if it made some progress...
             if(fabs(this.origin_x - org.x) >= 0.03125 || fabs(this.origin_y - org.y) >= 0.03125)
             {
                 trace_endpos = this.origin;
                 time_left *= 1 - trace2_fraction;
                 numplanes = 0;
                 continue;
             }
             else
                 this.origin = org;
         }
         else
         {
             // step - return it to caller
             blocked |= 2;
             // save the trace for player extrafriction
             if(applystepnormal)
                 move_stepnormal = trace_plane_normal;
         }
         if(my_trace_fraction >= 0.001)
         {
             // actually covered some distance
             original_velocity = this.velocity;
             numplanes = 0;
         }
         time_left *= 1 - my_trace_fraction;
         // clipped to another plane
         if(numplanes >= MAX_CLIP_PLANES)
         {
             // this shouldn't really happen
             this.velocity = '0 0 0';
             blocked = 3;
             break;
         }
         planes[numplanes] = my_trace_plane_normal;
         numplanes++;
         // modify original_velocity so it parallels all of the clip planes
         vector new_velocity = '0 0 0';
         for (i = 0;i < numplanes;i++)
         {
             new_velocity = _Movetype_ClipVelocity(original_velocity, planes[i], 1);
             for (j = 0;j < numplanes;j++)
             {
                 if(j != i)
                 {
                     // not ok
                     if((new_velocity * planes[j]) < 0)
                         break;
                 }
             }
             if(j == numplanes)
                 break;
         }
         if(i != numplanes)
         {
             // go along this plane
             this.velocity = new_velocity;
         }
         else
         {
             // go along the crease
             if(numplanes != 2)
             {
                 this.velocity = '0 0 0';
                 blocked = 7;
                 break;
             }
             vector dir = cross(planes[0], planes[1]);
             // LordHavoc: thanks to taniwha of QuakeForge for pointing out this fix for slowed falling in corners
             float ilength = sqrt((dir * dir));
             if(ilength)
                 ilength = 1.0 / ilength;
             dir.x *= ilength;
             dir.y *= ilength;
             dir.z *= ilength;
             float d = (dir * this.velocity);
             this.velocity = dir * d;
         }
         // if current velocity is against the original velocity,
         // stop dead to avoid tiny occilations in sloping corners
         if((this.velocity * primal_velocity) <= 0)
         {
             this.velocity = '0 0 0';
             break;
         }
     }
     // LordHavoc: this came from QW and allows you to get out of water more easily
     if(GAMEPLAYFIX_EASIERWATERJUMP(this) && (this.flags & FL_WATERJUMP) && !(blocked & 8))
         this.velocity = primal_velocity;
     if(PHYS_WALLCLIP(this) && this.pm_time && !(this.flags & FL_WATERJUMP) && !(blocked & 8))
         this.velocity = primal_velocity;
     if(applygravity)
     {
         if(!GAMEPLAYFIX_NOGRAVITYONGROUND || !IS_ONGROUND(this))
         {
             if(GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
                 this.velocity_z -= grav * 0.5f;
         }
     }
     return blocked;
 }
void _Movetype_LinkEdict (entity this, float touch_triggers)
void _Movetype_LinkEdict_TouchAreaGrid (entity this)
Definition at line 339 of file movetypes.qc.
References absmax, absmin, boxesoverlap(), MOVE_NOMONSTERS, MOVE_WORLDONLY, solid, SOLID_NOT, SOLID_TRIGGER, and vlen().
Referenced by _Movetype_LinkEdict().
 {
     if(this.solid == SOLID_NOT)
         return;
     FOREACH_ENTITY_RADIUS(0.5 * (this.absmin + this.absmax), 0.5 * vlen(this.absmax - this.absmin), true, {
         if (it.solid == SOLID_TRIGGER && it != this)
         if (it.move_nomonsters != MOVE_NOMONSTERS && it.move_nomonsters != MOVE_WORLDONLY)
         if (gettouch(it) && boxesoverlap(it.absmin, it.absmax, this.absmin, this.absmax))
         {
             trace_allsolid = false;
             trace_startsolid = false;
             trace_fraction = 1;
             trace_inwater = false;
             trace_inopen = true;
             trace_endpos = it.origin;
             trace_plane_normal = '0 0 1';
             trace_plane_dist = 0;
             trace_ent = this;
             trace_dpstartcontents = 0;
             trace_dphitcontents = 0;
             trace_dphitq3surfaceflags = 0;
             trace_dphittexturename = string_null;
             gettouch(it)(it, this);
         }
     });
 }
bool _Movetype_PushEntity (entity this, vector push, float failonstartsolid, bool dolink)
void _Movetype_PushEntityTrace (entity this, vector push)
Definition at line 536 of file movetypes.qc.
References max(), maxs, mins, MOVE_MISSILE, move_movetype, move_nomonsters, MOVE_NOMONSTERS, MOVE_NORMAL, MOVE_WORLDONLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_FLYMISSILE, origin, solid, SOLID_NOT, SOLID_TRIGGER, and vector().
Referenced by _Movetype_PushEntity(), and Movetype_Physics_MatchTicrate().
 {
     vector end = this.origin + push;
     int type;
     if(this.move_nomonsters)
         type = max(0, this.move_nomonsters);
     else if(this.move_movetype == MOVETYPE_FLYMISSILE)
         type = MOVE_MISSILE;
     else if(this.move_movetype == MOVETYPE_FLY_WORLDONLY)
         type = MOVE_WORLDONLY;
     else if(this.solid == SOLID_TRIGGER || this.solid == SOLID_NOT)
         type = MOVE_NOMONSTERS;
     else
         type = MOVE_NORMAL;
     tracebox(this.origin, this.mins, this.maxs, end, type, this);
 }
int _Movetype_UnstickEntity (entity this)
Definition at line 479 of file movetypes.qc.
References _Movetype_LinkEdict(), _Movetype_TestEntityPosition(), _Movetype_TestEntityPosition_Offset(), classname, etof(), LOG_DEBUGF, maxs, origin, rint(), UNSTICK_FINE, UNSTICK_FIXED, UNSTICK_STUCK, vtos(), and X.
Referenced by _Movetype_CheckStuck(), and _Movetype_Physics_Toss().
 {
     _Movetype_TestEntityPosition_ent = this;
     if (!_Movetype_TestEntityPosition(' 0  0  0')) {
         return UNSTICK_FINE;
     }
     #define X(v) if (_Movetype_TestEntityPosition(v))
     X('0  0  -1') X(' 0  0  1')
     X('-1  0  0') X(' 1  0  0')
     X(' 0 -1  0') X(' 0  1  0')
     X('-1 -1  0') X(' 1 -1  0')
     X('-1  1  0') X(' 1  1  0')
     #undef X
     {
         if(_Movetype_TestEntityPosition_Offset(rint((this.maxs.z - this.mins.z) * 0.36)))
         {
             LOG_DEBUGF("Can't unstick an entity (edict: %d, classname: %s, origin: %s)",
                 etof(this), this.classname, vtos(this.origin));
             return UNSTICK_STUCK;
         }
     }
     LOG_DEBUGF("Sucessfully unstuck an entity (edict: %d, classname: %s, origin: %s)",
         etof(this), this.classname, vtos(this.origin));
     _Movetype_LinkEdict(this, false);
     return UNSTICK_FIXED;
 }
void _Movetype_WallFriction (entity this, vector stepnormal)
Definition at line 21 of file movetypes.qc.
Referenced by _Movetype_Physics_Walk().
 {
     /*float d, i;
     vector into, side;
     makevectors(this.v_angle);
     d = (stepnormal * v_forward) + 0.5;
     if(d < 0)
     {
         i = (stepnormal * this.velocity);
         into = i * stepnormal;
         side = this.velocity - into;
         this.velocity_x = side.x * (1 * d);
         this.velocity_y = side.y * (1 * d);
     }*/
 }
void Movetype_Physics_MatchServer (entity this, bool sloppy)
Definition at line 697 of file movetypes.qc.
References Movetype_Physics_MatchTicrate().
Referenced by Projectile_Draw(), and train_next().
 {
     Movetype_Physics_MatchTicrate(this, TICRATE, sloppy);
 }
void Movetype_Physics_MatchTicrate (entity this, float tr, bool sloppy)
Definition at line 715 of file movetypes.qc.
References _Movetype_Physics_Frame(), _Movetype_PushEntityTrace(), angles, avelocity, FL_ONGROUND, flags, floor(), gravity, max(), move_didgravity, move_movetype, move_time, MOVETYPE_BOUNCE, MOVETYPE_NOCLIP, MOVETYPE_NONE, Movetype_Physics_NoMatchServer(), MOVETYPE_TOSS, origin, setorigin(), tic_angles, tic_avelocity, tic_flags, tic_origin, tic_saved_angles, tic_saved_avelocity, tic_saved_flags, tic_saved_origin, tic_saved_velocity, tic_velocity, time, trace_endpos, trace_startsolid, velocity, and X.
Referenced by Movetype_Physics_MatchServer(), and turret_gib_draw().
 {
     // this hack exists to contain the physics feature
     // (so entities can place themselves in the world and not need to update .tic_* themselves)
 #define X(s) \
     if(this.(s) != this.tic_saved_##s) \
         this.tic_##s = this.(s)
     X(origin);
     X(velocity);
     X(flags);
     X(avelocity);
     X(angles);
 #undef X
     this.flags = this.tic_flags;
     this.velocity = this.tic_velocity;
     setorigin(this, this.tic_origin);
     this.avelocity = this.tic_avelocity;
     this.angles = this.tic_angles;
     if(tr <= 0)
     {
         Movetype_Physics_NoMatchServer(this);
         this.tic_saved_flags = this.tic_flags = this.flags;
         this.tic_saved_velocity = this.tic_velocity = this.velocity;
         this.tic_saved_origin = this.tic_origin = this.origin;
         this.tic_saved_avelocity = this.tic_avelocity = this.avelocity;
         this.tic_saved_angles = this.tic_angles = this.angles;
         return;
     }
     float dt = time - this.move_time;
     int n = max(0, floor(dt / tr));
     dt -= n * tr;
     this.move_time += n * tr;
     if(!this.move_didgravity)
         this.move_didgravity = ((this.move_movetype == MOVETYPE_BOUNCE || this.move_movetype == MOVETYPE_TOSS) && !(this.tic_flags & FL_ONGROUND));
     for (int j = 0; j < n; ++j)
     {
         _Movetype_Physics_Frame(this, tr);
         if(wasfreed(this))
             return;
     }
     // update the physics fields
     this.tic_origin = this.origin;
     this.tic_velocity = this.velocity;
     this.tic_avelocity = this.avelocity;
     this.tic_angles = this.angles;
     this.tic_flags = this.flags;
     // restore their actual values
     this.flags = this.tic_saved_flags;
     this.velocity = this.tic_saved_velocity;
     setorigin(this, this.tic_saved_origin);
     //this.avelocity = this.tic_saved_avelocity;
     this.angles = this.tic_saved_angles;
     this.avelocity = this.tic_avelocity;
     if(dt > 0 && this.move_movetype != MOVETYPE_NONE && !(this.tic_flags & FL_ONGROUND))
     {
         // now continue the move from move_time to time
         this.velocity = this.tic_velocity;
         if(this.move_didgravity > 0)
         {
             this.velocity_z -= (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE ? 0.5 : 1)
                 * dt
                 * ((this.gravity) ? this.gravity : 1)
                 * PHYS_GRAVITY(this);
         }
         this.angles = this.tic_angles + dt * this.avelocity;
         if(sloppy || this.move_movetype == MOVETYPE_NOCLIP)
         {
             setorigin(this, this.tic_origin + dt * this.velocity);
         }
         else
         {
             setorigin(this, this.tic_origin);
             _Movetype_PushEntityTrace(this, dt * this.velocity);
             if(!trace_startsolid)
                 setorigin(this, trace_endpos);
             else
                 setorigin(this, this.tic_saved_origin);
         }
         if(this.move_didgravity > 0 && GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
             this.velocity_z -= 0.5 * dt * ((this.gravity) ? this.gravity : 1) * PHYS_GRAVITY(this);
     }
     else
     {
         this.velocity = this.tic_velocity;
         this.angles = this.tic_angles;
         setorigin(this, this.tic_origin);
     }
     this.flags = this.tic_flags;
     this.tic_saved_flags = this.flags;
     this.tic_saved_velocity = this.velocity;
     this.tic_saved_origin = this.origin;
     this.tic_saved_avelocity = this.avelocity;
     this.tic_saved_angles = this.angles;
 }
void Movetype_Physics_NoMatchServer (entity this)
Definition at line 685 of file movetypes.qc.
References _Movetype_Physics_Frame(), move_time, origin, setorigin(), and time.
Referenced by Movetype_Physics_MatchTicrate(), and Projectile_Draw().
 {
     float movedt = time - this.move_time;
     this.move_time = time;
     _Movetype_Physics_Frame(this, movedt);
     if(wasfreed(this))
         return;
     setorigin(this, this.origin);
 }
void Movetype_Physics_NoMatchTicrate (entity this, float movedt, bool isclient)
Definition at line 671 of file movetypes.qc.
References _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), move_time, origin, setorigin(), and time.
Referenced by CSQCPlayer_Physics(), Physics_Frame(), and Player_Physics().
 {
     this.move_time = time;
     if(isclient)
         _Movetype_Physics_ClientFrame(this, movedt);
     else
         _Movetype_Physics_Frame(this, movedt);
     if(wasfreed(this))
         return;
     setorigin(this, this.origin);
 }
void set_movetype (entity this, int mt)
Referenced by buff_Init(), buff_Respawn(), CheatCommand(), conveyor_think(), CopyBody(), cpicon_construct(), ctf_CaptureShield_Spawn(), ctf_FlagSetup(), ctf_FlagThink(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_Handle_Retrieve(), ctf_Handle_Throw(), ctf_RespawnFlag(), door_reset(), door_spawnfield(), Drag_Begin(), Drag_Finish(), DropBall(), findtrajectorywithleading(), FireGrapplingHook(), follow_sameorigin(), generator_construct(), GiveBall(), GrapplingHook_Stop(), GrapplingHookThink(), InitBall(), jumppad_push(), ka_DropEvent(), ka_RespawnBall(), ka_SpawnBall(), ka_TouchEvent(), kh_Key_Attach(), kh_Key_Detach(), Monster_Dead(), Monster_Move(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ObserverThink(), ons_CaptureShield_Spawn(), ons_ControlPoint_Setup(), ons_generator_ray_spawn(), ons_GeneratorSetup(), physical_item_think(), plat_spawn_inside_trigger(), player_clear_minigame(), PlayerDamage(), PlayerPostThink(), PutObserverInServer(), PutPlayerInServer(), RemoveGrapplingHooks(), RemoveHook(), ResetBall(), respawn(), sandbox_ObjectAttach_Set(), sandbox_ObjectPort_Load(), sandbox_ObjectSpawn(), SetMovetypeFollow(), SpawnBall(), SpectateSet(), SUB_CalcAngleMoveEnt(), SUB_Stop(), SV_OnEntityPreSpawnFunction(), sys_phys_pregame_hold(), train_next(), turret_construct(), turret_gibtoss(), UnsetMovetypeFollow(), vehicle_tossgib(), vehicles_enter(), vehicles_exit(), vehicles_projectile(), vehicles_spawn(), W_Nexball_Attack2(), and WarpZoneLib_ExactTrigger_Init().
void (float , float)
Variable Documentation
entity aiment
Definition at line 82 of file movetypes.qh.
Referenced by _Movetype_Physics_Follow(), DragBox_Think(), GrapplingHookThink(), GrapplingHookTouch(), Portal_Customize(), Portal_Damage(), Portal_Think(), Portal_Touch(), and WarpZone_Projectile_Touch().
const int FL_ONSLICK = BIT(20)
Definition at line 146 of file movetypes.qh.
entity groundentity
Definition at line 85 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), and _Movetype_PushEntity().
const int MAX_CLIP_PLANES = 5
Definition at line 118 of file movetypes.qh.
Referenced by _Movetype_FlyMove().
float move_didgravity
Definition at line 87 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Toss(), and Movetype_Physics_MatchTicrate().
float move_movetype
Definition at line 68 of file movetypes.qh.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), _Movetype_PushEntityTrace(), _Movetype_TestEntityPosition(), CheatCommand(), CheatImpulse(), CopyBody(), ctf_FlagThink(), Monster_Move(), Movetype_Physics_MatchTicrate(), NET_HANDLE(), player_anim(), Player_Physics(), Projectile_Draw(), sys_phys_pregame_hold(), and sys_phys_update().
float move_nomonsters
Definition at line 80 of file movetypes.qh.
Referenced by _Movetype_PushEntity(), _Movetype_PushEntityTrace(), and NET_HANDLE().
vector move_stepnormal
Definition at line 95 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), and _Movetype_Physics_Walk().
float move_suspendedinair
Definition at line 86 of file movetypes.qh.
Referenced by _Movetype_Physics_Toss().
float move_time
Definition at line 69 of file movetypes.qh.
Referenced by conveyor_think(), cpicon_construct(), cpicon_draw(), door_reset(), func_ladder_touch(), generator_construct(), generator_draw(), Movetype_Physics_MatchTicrate(), Movetype_Physics_NoMatchServer(), Movetype_Physics_NoMatchTicrate(), NET_HANDLE(), ons_generator_ray_draw(), swamp_touch(), Teleport_Touch(), train_next(), trigger_impulse_touch_radial(), trigger_push_findtarget(), and turret_draw().
const int MOVEFLAG_GRAVITYUNAFFECTEDBYTICRATE = BIT(2)
Definition at line 153 of file movetypes.qh.
const int MOVEFLAG_NOGRAVITYONGROUND = BIT(1)
Definition at line 152 of file movetypes.qh.
const int MOVEFLAG_Q2AIRACCELERATE = BIT(0)
Definition at line 151 of file movetypes.qh.
const int MOVEFLAG_VALID = BIT(23)
Definition at line 150 of file movetypes.qh.
const int MOVETYPE_FAKEPUSH = 13
Definition at line 148 of file movetypes.qh.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), and Physics_Frame().
const int MOVETYPE_QCPLAYER = 150
Definition at line 144 of file movetypes.qh.
Referenced by Player_Physics().
float pm_time
Definition at line 66 of file movetypes.qh.
Referenced by _Movetype_FlyMove(), and _Movetype_Physics_Walk().
vector punchangle
Definition at line 83 of file movetypes.qh.
const int UNSTICK_FINE = 0
Definition at line 90 of file movetypes.qh.
Referenced by _Movetype_CheckStuck(), and _Movetype_UnstickEntity().
const int UNSTICK_FIXED = 1
Definition at line 91 of file movetypes.qh.
Referenced by _Movetype_CheckStuck(), and _Movetype_UnstickEntity().
const int UNSTICK_STUCK = 2
Definition at line 92 of file movetypes.qh.
Referenced by _Movetype_CheckStuck(), and _Movetype_UnstickEntity().
const int WATERLEVEL_NONE = 0
Definition at line 4 of file movetypes.qh.
Referenced by _Movetype_CheckWater(), PutPlayerInServer(), sys_phys_simulate(), and sys_phys_update().
const int WATERLEVEL_SUBMERGED = 3
Definition at line 7 of file movetypes.qh.
Referenced by _Movetype_CheckWater(), DrownPlayer(), navigation_check_submerged_state(), and sys_phys_simulate().
const int WATERLEVEL_SWIMMING = 2
Definition at line 6 of file movetypes.qh.
Referenced by _Movetype_CheckWater(), CheckPlayerJump(), havocbot_ai(), havocbot_movetogoal(), IsFlying(), PlayerJump(), PM_check_hitground(), PM_dodging(), sys_phys_simulate(), and sys_phys_update().
const int WATERLEVEL_WETFEET = 1
Definition at line 5 of file movetypes.qh.
Referenced by _Movetype_CheckWater(), havocbot_bunnyhop(), havocbot_goalrating_enemyplayers(), havocbot_movetogoal(), Monster_Move(), navigation_routerating(), and sys_phys_simulate().