Xonotic: menu/xonotic/dialog_multiplayer_media_demo.qc File Reference
dialog_multiplayer_media_demo.qc File Reference
#include "dialog_multiplayer_media_demo.qh"
#include "demolist.qh"
#include "textlabel.qh"
#include "inputbox.qh"
#include "checkbox.qh"
#include "button.qh"
Functions
void DemoConfirm_Check_Gamestatus (entity btn, entity me)
entity makeXonoticDemoBrowserTab ()
void XonoticDemoBrowserTab_fill (entity me)
Variables
const float DMO_PLAY = 1
const float DMO_TIME = 2
Function Documentation
void DemoConfirm_Check_Gamestatus (entity btn, entity me)
Definition at line 11 of file dialog_multiplayer_media_demo.qc.
References demolist, DialogOpenButton_Click(), DMO_PLAY, DMO_TIME, GAME_CONNECTED, GAME_ISSERVER, gamestatus, and main.
Referenced by XonoticDemoBrowserTab_fill().
 {
     if(!(gamestatus & (GAME_CONNECTED | GAME_ISSERVER))) // we're not in a match, lets watch the demo
     {
         if(btn.democlicktype == DMO_PLAY)
             { demolist.startDemo(demolist); }
         else if(btn.democlicktype == DMO_TIME)
             { demolist.timeDemo(demolist); }
     }
     else // already in a match, player has to confirm
     {
         if(btn.democlicktype == DMO_PLAY)
             { DialogOpenButton_Click(btn, main.demostartconfirmDialog); }
         else if(btn.democlicktype == DMO_TIME)
             { DialogOpenButton_Click(btn, main.demotimeconfirmDialog); }
     }
 }
entity makeXonoticDemoBrowserTab ()
Definition at line 29 of file dialog_multiplayer_media_demo.qc.
References entity(), and NEW.
Referenced by XonoticMediaTab_fill().
 {
     entity me;
     me = NEW(XonoticDemoBrowserTab);
     me.configureDialog(me);
     return me;
 }
void XonoticDemoBrowserTab_fill (entity me)
Definition at line 36 of file dialog_multiplayer_media_demo.qc.
References DemoConfirm_Check_Gamestatus(), demolist, DemoList_Filter_Change(), DemoList_Refresh_Click(), DMO_PLAY, DMO_TIME, entity(), makeXonoticButton(), makeXonoticButton_T(), makeXonoticCheckBox(), makeXonoticDemoList(), makeXonoticInputBox(), makeXonoticTextLabel(), string_null, and ZCTX.
 {
     entity e;
     demolist = makeXonoticDemoList();
     me.TR(me);
         me.TD(me, 1, 0.6, e = makeXonoticTextLabel(1, _("Filter:")));
         me.TD(me, 1, 2.9, e = makeXonoticInputBox(0, string_null));
             e.onChange = DemoList_Filter_Change;
             e.onChangeEntity = demolist;
     me.gotoRC(me, 0, 3.7);
         me.TD(me, 1, 1.5, e = makeXonoticCheckBox(0, "cl_autodemo", _("Auto record demos")));
         me.TD(me, 1, 1, e = makeXonoticButton(_("Refresh"), '0 0 0'));
             e.onClick = DemoList_Refresh_Click;
             e.onClickEntity = demolist;
     me.gotoRC(me, 1.5, 0);
         me.TD(me, me.rows - 2.5, me.columns, demolist);
     me.gotoRC(me, me.rows - 1, 0);
         me.TD(me, 1, me.columns / 2, e = makeXonoticButton_T(_("Timedemo"), '0 0 0',
             _("Benchmark how fast your computer can run the highlighted demo")));
             e.democlicktype = DMO_TIME;
             e.onClick = DemoConfirm_Check_Gamestatus;
             e.onClickEntity = me; // demolist is global anyway
         me.TD(me, 1, me.columns / 2, e = makeXonoticButton(ZCTX(_("DEMO^Play")), '0 0 0'));
             e.democlicktype = DMO_PLAY;
             e.onClick = DemoConfirm_Check_Gamestatus;
             e.onClickEntity = me; // demolist is global anyway
 }
Variable Documentation
const float DMO_PLAY = 1
Definition at line 9 of file dialog_multiplayer_media_demo.qc.
Referenced by DemoConfirm_Check_Gamestatus(), and XonoticDemoBrowserTab_fill().
const float DMO_TIME = 2
Definition at line 10 of file dialog_multiplayer_media_demo.qc.
Referenced by DemoConfirm_Check_Gamestatus(), and XonoticDemoBrowserTab_fill().