Xonotic: menu/xonotic/slider.qh File Reference
slider.qh File Reference
#include "../item/slider.qh"
Classes
class XonoticSlider
Functions
entity makeXonoticSlider (float, float, float, string)
entity makeXonoticSlider_T (float, float, float, string, string theTooltip)
Function Documentation
entity makeXonoticSlider (float , float , float , string)
Definition at line 10 of file slider.qc.
References makeXonoticSlider_T(), and string_null.
Referenced by XonoticDamageTextSettings::fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDVoteDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), and XonoticSandboxToolsDialog_fill().
 {
     return makeXonoticSlider_T(theValueMin, theValueMax, theValueStep, theCvar, string_null);
 }
entity makeXonoticSlider_T (float , float , float , string , string theTooltip)
Definition at line 3 of file slider.qc.
References entity(), and NEW.
Referenced by makeXonoticSlider(), XonoticEffectsSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticSlider);
     me.configureXonoticSlider(me, theValueMin, theValueMax, theValueStep, theCvar, theTooltip);
     return me;
 }