Xonotic: common/gamemodes/gamemode/freezetag/cl_freezetag.qc File Reference
cl_freezetag.qc File Reference
#include "cl_freezetag.qh"
#include <common/gamemodes/gamemode/clanarena/cl_clanarena.qh>
Functions
void HUD_Mod_FreezeTag (vector myPos, vector mySize)
void HUD_Mod_FreezeTag_Export (int fh)
Function Documentation
void HUD_Mod_FreezeTag (vector myPos, vector mySize)
Definition at line 10 of file cl_freezetag.qc.
References autocvar_hud_panel_modicons_freezetag_layout, HUD_Mod_CA_Draw(), and mod_active.
Referenced by FreezeTag::m_configuremenu().
 {
     mod_active = 1; // required in each mod function that always shows something
     HUD_Mod_CA_Draw(myPos, mySize, autocvar_hud_panel_modicons_freezetag_layout);
 }
void HUD_Mod_FreezeTag_Export (int fh)
Definition at line 5 of file cl_freezetag.qc.
References HUD_Write_Cvar.
Referenced by FreezeTag::m_configuremenu().
 {
     HUD_Write_Cvar("hud_panel_modicons_freezetag_layout");
 }