Xonotic: PlasmaDualAttack Class Reference
PlasmaDualAttack Class Reference
Public Member Functions
ATTRIB (Weapon, m_canonical_spawnfunc, string)
the canonical spawnfunc name
ATTRIB (Weapon, m_model, entity)
M: model MDL_id_ITEM.
ATTRIB (Weapon, m_pickup, entity)
virtual void display ()
virtual void m_spawnfunc_hookreplace ()
control what happens when this weapon is spawned
virtual void wr_aim ()
(SERVER) runs bot aiming code for this weapon
virtual void wr_checkammo1 ()
(SERVER) checks ammo for weapon primary
virtual void wr_checkammo2 ()
(SERVER) checks ammo for weapon second
virtual void wr_config ()
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
virtual void wr_drop ()
(SERVER) the weapon is dropped
virtual void wr_glow ()
(CLIENT) weapon specific glow
virtual void wr_gonethink ()
(SERVER) logic to run when weapon is lost
virtual void wr_impacteffect ()
(CLIENT) impact effect for weapon explosion
virtual void wr_init ()
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
virtual void wr_killmessage ()
(SERVER) notification number for kill message (may inspect w_deathtype for details)
virtual void wr_pickup ()
(SERVER) a weapon is picked up
virtual void wr_playerdeath ()
(SERVER) called whenever a player dies
virtual void wr_reload ()
(SERVER) handles reloading for weapon
virtual void wr_resetplayer ()
(SERVER) clears fields that the weapon may use
virtual void wr_setup ()
(SERVER) setup weapon data
virtual void wr_suicidemessage ()
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
virtual void wr_think ()
(SERVER) logic to run every frame
virtual void wr_update ()
(SERVER) update cvar based properties
virtual void wr_viewmodel ()
(CLIENT) weapon specific view model
virtual void wr_zoom ()
(BOTH) weapon specific zoom reticle
virtual void wr_zoomdir ()
(CLIENT) check whether the weapon should zoom (special handling)
Public Attributes
int ammo_type = RESOURCE_NONE
float bot_pickupbasevalue = 0
int impulse = 5
string m_canonical_spawnfunc = "weapon_porto"
int m_id = 0
string m_name = _("Dual plasma")
string mdl = "porto"
string model2 = "weaponporto"
string netname = "turret_plasma_dual"
int spawnflags = WEP_FLAG_HIDDEN | WEP_FLAG_MUTATORBLOCKED
string w_crosshair = "gfx/crosshairporto"
float w_crosshair_size = 0.6
string w_reticle = string_null
A: reticle : per-weapon zoom reticle.
WepSet weapons = '0 0 0'
A: WEPSET_id : WEPSET_...
vector wpcolor = '0.5 0.5 0.5'
Detailed Description
Definition at line 5 of file plasma_dual.qh.
Member Function Documentation
Weapon::ATTRIB (Weapon , m_canonical_spawnfunc , string) inherited
the canonical spawnfunc name
Weapon::ATTRIB (Weapon , m_model , entity) inherited
M: model MDL_id_ITEM.
Weapon::ATTRIB (Weapon , m_pickup , entity) inherited
virtual void Weapon::display () inline virtual inherited
Definition at line 123 of file weapon.qh.
References cvar_string(), m_name, and string_null.
{
         returns(this.m_name, this.model2 ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.model2) : string_null);
     }
virtual void Weapon::m_spawnfunc_hookreplace () inline virtual inherited
control what happens when this weapon is spawned
Definition at line 46 of file weapon.qh.
Referenced by weapon_defaultspawnfunc().
 { return this; }
virtual void Weapon::wr_aim () inline virtual inherited
(SERVER) runs bot aiming code for this weapon
Definition at line 87 of file weapon.qh.
 {}
virtual void Weapon::wr_checkammo1 () inline virtual inherited
(SERVER) checks ammo for weapon primary
Definition at line 83 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_checkammo2 () inline virtual inherited
(SERVER) checks ammo for weapon second
Definition at line 85 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_config () inline virtual inherited
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
Definition at line 105 of file weapon.qh.
 {}
virtual void Weapon::wr_drop () inline virtual inherited
(SERVER) the weapon is dropped
Definition at line 118 of file weapon.qh.
 {}
virtual void Weapon::wr_glow () inline virtual inherited
(CLIENT) weapon specific glow
Definition at line 116 of file weapon.qh.
 { return '0 0 0'; }
virtual void Weapon::wr_gonethink () inline virtual inherited
(SERVER) logic to run when weapon is lost
Definition at line 103 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_impacteffect () inline virtual inherited
(CLIENT) impact effect for weapon explosion
Definition at line 99 of file weapon.qh.
 {}
virtual void Weapon::wr_init () inline virtual inherited
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
Definition at line 89 of file weapon.qh.
Referenced by GrappleHookInit().
 {}
virtual void Weapon::wr_killmessage () inline virtual inherited
(SERVER) notification number for kill message (may inspect w_deathtype for details)
Definition at line 93 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_pickup () inline virtual inherited
(SERVER) a weapon is picked up
Definition at line 120 of file weapon.qh.
 {}
virtual void Weapon::wr_playerdeath () inline virtual inherited
(SERVER) called whenever a player dies
Definition at line 101 of file weapon.qh.
Referenced by PlayerDamage().
 {}
virtual void Weapon::wr_reload () inline virtual inherited
(SERVER) handles reloading for weapon
Definition at line 95 of file weapon.qh.
Referenced by IMPULSE(), and W_SwitchWeapon().
 {}
virtual void Weapon::wr_resetplayer () inline virtual inherited
(SERVER) clears fields that the weapon may use
Definition at line 97 of file weapon.qh.
 {}
virtual void Weapon::wr_setup () inline virtual inherited
(SERVER) setup weapon data
Definition at line 79 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_suicidemessage () inline virtual inherited
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
Definition at line 91 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 81 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_update () inline virtual inherited
(SERVER) update cvar based properties
Definition at line 122 of file weapon.qh.
 {}
virtual void Weapon::wr_viewmodel () inline virtual inherited
(CLIENT) weapon specific view model
Definition at line 114 of file weapon.qh.
References string_null.
Referenced by viewmodel_draw().
 { return string_null; }
virtual void Weapon::wr_zoom () inline virtual inherited
(BOTH) weapon specific zoom reticle
Definition at line 107 of file weapon.qh.
Referenced by CSQC_UpdateView().
{
         // no weapon specific image for this weapon
         return false;
     }
virtual void Weapon::wr_zoomdir () inline virtual inherited
(CLIENT) check whether the weapon should zoom (special handling)
Definition at line 112 of file weapon.qh.
Referenced by GetCurrentFov().
 {return false;}
Member Data Documentation
int PortoLaunch::ammo_type = RESOURCE_NONE inherited
Definition at line 5 of file porto.qh.
float PortoLaunch::bot_pickupbasevalue = 0 inherited
Definition at line 8 of file porto.qh.
int PlasmaAttack::impulse = 5 inherited
Definition at line 5 of file plasma_weapon.qh.
string PortoLaunch::m_canonical_spawnfunc = "weapon_porto" inherited
Definition at line 4 of file porto.qh.
int Weapon::m_id = 0 inherited
Definition at line 42 of file weapon.qh.
Referenced by client_hasweapon(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), SpawnThrownWeapon(), TEST(), W_SetupShot_Dir_ProjectileSize_Range(), W_SwitchWeapon(), W_SwitchWeapon_Force(), and W_ThrowWeapon().
string PlasmaDualAttack::m_name = _("Dual plasma")
Definition at line 8 of file plasma_dual.qh.
string PortoLaunch::mdl = "porto" inherited
Definition at line 10 of file porto.qh.
string PortoLaunch::model2 = "weaponporto" inherited
Definition at line 16 of file porto.qh.
string PlasmaDualAttack::netname = "turret_plasma_dual"
Definition at line 7 of file plasma_dual.qh.
int PlasmaDualAttack::spawnflags = WEP_FLAG_HIDDEN | WEP_FLAG_MUTATORBLOCKED
Definition at line 6 of file plasma_dual.qh.
string PortoLaunch::w_crosshair = "gfx/crosshairporto" inherited
Definition at line 14 of file porto.qh.
float PortoLaunch::w_crosshair_size = 0.6 inherited
Definition at line 15 of file porto.qh.
string Weapon::w_reticle = string_null inherited
A: reticle : per-weapon zoom reticle.
Definition at line 68 of file weapon.qh.
Referenced by CSQC_UpdateView().
WepSet Weapon::weapons = '0 0 0' inherited
A: WEPSET_id : WEPSET_...
Definition at line 48 of file weapon.qh.
vector PortoLaunch::wpcolor = '0.5 0.5 0.5' inherited
Definition at line 9 of file porto.qh.
The documentation for this class was generated from the following file:
common/turrets/turret/plasma_dual.qh