Xonotic: lib/urllib.qc File Reference
urllib.qc File Reference
#include "urllib.qh"
Functions
void url_fclose (entity e)
string url_fgets (entity e)
void url_fputs (entity e, string s)
void url_multi_fopen (string url, int mode, url_ready_func rdy, entity pass)
void url_multi_ready (entity fh, entity me, float status)
void url_single_fopen (string url, int mode, url_ready_func rdy, entity pass)
float url_URI_Get_Callback (int id, float status, string data)
Variables
int autocvar__urllib_nextslot
int url_attempt
string url_content_type
float url_fh
const float URL_FH_CURL = -1
const float URL_FH_STDOUT = -2
entity url_fromid [NUM_URL_ID]
float url_id
int url_mode
float url_rbuf
float url_rbufpos
url_ready_func url_ready
entity url_ready_pass
string url_url
string url_verb
float url_wbuf
float url_wbufpos
Function Documentation
void url_fclose (entity e)
Definition at line 204 of file urllib.qc.
References autocvar__urllib_nextslot, cvar_set(), error, fclose(), ftos(), LOG_INFO, MIN_URL_ID, NULL, NUM_URL_ID, strunzone(), URL_FH_CURL, URL_FH_STDOUT, url_fromid, URL_READY_CLOSED, and URL_READY_ERROR.
Referenced by MX_JLF_(), MX_Messages_(), MX_Nick_(), MX_Say_(), MX_Sync_(), MX_Typing_(), and WeaponStats_ready().
 {
     int i;
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_rbuf == -1 || e.url_wbuf != -1)     // not(post GET/POST request)
             if (e.url_rbuf != -1 || e.url_wbuf == -1) // not(pre POST request)
                 error("url_fclose: not closable in current state");
         // closing an URL!
         if (e.url_wbuf >= 0)
         {
             // we are closing the write end (HTTP POST request)
             // get slot for HTTP request
             for (i = autocvar__urllib_nextslot; i < NUM_URL_ID; ++i)
                 if (url_fromid[i] == NULL) break;
             if (i >= NUM_URL_ID)
             {
                 for (i = 0; i < autocvar__urllib_nextslot; ++i)
                     if (url_fromid[i] == NULL) break;
                 if (i >= autocvar__urllib_nextslot)
                 {
                     LOG_INFO("url_fclose: too many concurrent requests\n");
                     e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
                     buf_del(e.url_wbuf);
                     strunzone(e.url_url);
                     delete(e);
                     return;
                 }
             }
             // POST the data
             if (!crypto_uri_postbuf(e.url_url, i + MIN_URL_ID, e.url_content_type, e.url_verb, e.url_wbuf, 0))
             {
                 LOG_INFO("url_fclose: failure in crypto_uri_postbuf\n");
                 e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
                 buf_del(e.url_wbuf);
                 strunzone(e.url_url);
                 delete(e);
                 return;
             }
             // delete write end. File handle is now in unusable
             // state. Wait for data to come from the server, then
             // call the callback
             buf_del(e.url_wbuf);
             e.url_wbuf = -1;
             e.url_id = i;
             url_fromid[i] = e;
             // make sure this slot won't be reused quickly even on map change
             cvar_set("_urllib_nextslot", ftos((i + 1) % NUM_URL_ID));
         }
         else
         {
             // we have READ all data, just close
             e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);
             buf_del(e.url_rbuf);
             strunzone(e.url_url);
             delete(e);
         }
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);  // closing creates no reading handle
         delete(e);
     }
     else
     {
         // file
         fclose(e.url_fh);
         e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);  // closing creates no reading handle
         delete(e);
     }
 }
string url_fgets (entity e)
Definition at line 283 of file urllib.qc.
References error, fgets(), string_null, URL_FH_CURL, and URL_FH_STDOUT.
Referenced by MX_Messages_(), MX_Sync_(), and WeaponStats_ready().
 {
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_rbuf == -1) error("url_fgets: not readable in current state");
         // curl
         string s;
         s = bufstr_get(e.url_rbuf, e.url_rbufpos);
         e.url_rbufpos += 1;
         return s;
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         // stdout
         return string_null;
     }
     else
     {
         // file
         return fgets(e.url_fh);
     }
 }
void url_fputs (entity e, string s)
Definition at line 307 of file urllib.qc.
References error, fputs(), print(), URL_FH_CURL, and URL_FH_STDOUT.
Referenced by MX_JLF_(), MX_Nick_(), MX_Say_(), MX_Typing_(), and WeaponStats_ready().
 {
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_wbuf == -1) error("url_fputs: not writable in current state");
         // curl
         bufstr_set(e.url_wbuf, e.url_wbufpos, s);
         e.url_wbufpos += 1;
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         // stdout
         print(s);
     }
     else
     {
         // file
         fputs(e.url_fh, s);
     }
 }
void url_multi_fopen (string url, int mode, url_ready_func rdy, entity pass)
Definition at line 356 of file urllib.qc.
References argv(), entity(), LOG_INFO, new_pure, NULL, pass, strzone(), tokenize_console, url_multi_ready(), URL_READY_ERROR, and url_single_fopen().
Referenced by WeaponStats_Shutdown().
 {
     float n;
     n = tokenize_console(url);
     if (n <= 0)
     {
         LOG_INFO("url_multi_fopen: need at least one URL\n");
         rdy(NULL, pass, URL_READY_ERROR);
         return;
     }
     entity me = new_pure(url_multi);
     me.url_url = strzone(url);
     me.url_attempt = 0;
     me.url_mode = mode;
     me.url_ready = rdy;
     me.url_ready_pass = pass;
     url_single_fopen(argv(0), mode, url_multi_ready, me);
 }
void url_multi_ready (entity fh, entity me, float status)
Definition at line 329 of file urllib.qc.
References argv(), LOG_INFO, strunzone(), tokenize_console, URL_READY_ERROR, and url_single_fopen().
Referenced by url_multi_fopen().
 {
     float n;
     if (status == URL_READY_ERROR || status < 0)
     {
         if (status == -422)  // Unprocessable Entity
         {
             LOG_INFO("uri_multi_ready: got HTTP error 422, data is in unusable format - not continuing\n");
             me.url_ready(fh, me.url_ready_pass, status);
             strunzone(me.url_url);
             delete(me);
             return;
         }
         me.url_attempt += 1;
         n = tokenize_console(me.url_url);
         if (n <= me.url_attempt)
         {
             me.url_ready(fh, me.url_ready_pass, status);
             strunzone(me.url_url);
             delete(me);
             return;
         }
         url_single_fopen(argv(me.url_attempt), me.url_mode, url_multi_ready, me);
         return;
     }
     me.url_ready(fh, me.url_ready_pass, status);
 }
void url_single_fopen (string url, int mode, url_ready_func rdy, entity pass)
Definition at line 85 of file urllib.qc.
References autocvar__urllib_nextslot, buf_create, cvar_set(), entity(), FILE_APPEND, FILE_READ, FILE_WRITE, fopen(), ftos(), LOG_INFO, MIN_URL_ID, new_pure, NULL, NUM_URL_ID, pass, string_null, strstrofs, strunzone(), strzone(), URL_FH_CURL, URL_FH_STDOUT, url_fromid, URL_READY_CANREAD, URL_READY_CANWRITE, and URL_READY_ERROR.
Referenced by MX_Forget(), MX_Join(), MX_Leave(), MX_Messages(), MX_Nick(), MX_Say(), MX_Sync(), MX_Typing(), url_multi_fopen(), and url_multi_ready().
 {
     entity e;
     int i;
     if (strstrofs(url, "://", 0) >= 0)
     {
         switch (mode)
         {
             case FILE_WRITE:
             case FILE_APPEND:
                 // collect data to a stringbuffer for a POST request
                 // attempts to close will result in a reading handle
                 // create a writing end that does nothing yet
                 e = new_pure(url_single_fopen_file);
                 e.url_url = strzone(url);
                 e.url_content_type = "text/plain";
                 e.url_verb = "";
                 e.url_fh = URL_FH_CURL;
                 e.url_wbuf = buf_create();
                 if (e.url_wbuf < 0)
                 {
                     LOG_INFO("url_single_fopen: out of memory in buf_create\n");
                     rdy(e, pass, URL_READY_ERROR);
                     strunzone(e.url_url);
                     delete(e);
                     return;
                 }
                 e.url_wbufpos = 0;
                 e.url_rbuf = -1;
                 e.url_ready = rdy;
                 e.url_ready_pass = pass;
                 rdy(e, pass, URL_READY_CANWRITE);
                 break;
             case FILE_READ:
                 // read data only
                 // get slot for HTTP request
                 for (i = autocvar__urllib_nextslot; i < NUM_URL_ID; ++i)
                     if (url_fromid[i] == NULL) break;
                 if (i >= NUM_URL_ID)
                 {
                     for (i = 0; i < autocvar__urllib_nextslot; ++i)
                         if (url_fromid[i] == NULL) break;
                     if (i >= autocvar__urllib_nextslot)
                     {
                         LOG_INFO("url_single_fopen: too many concurrent requests\n");
                         rdy(NULL, pass, URL_READY_ERROR);
                         return;
                     }
                 }
                 // GET the data
                 if (!crypto_uri_postbuf(url, i + MIN_URL_ID, string_null, string_null, -1, 0))
                 {
                     LOG_INFO("url_single_fopen: failure in crypto_uri_postbuf\n");
                     rdy(NULL, pass, URL_READY_ERROR);
                     return;
                 }
                 // Make a dummy handle object (no buffers at
                 // all). Wait for data to come from the
                 // server, then call the callback
                 e = new_pure(url_single_fopen_file);
                 e.url_url = strzone(url);
                 e.url_fh = URL_FH_CURL;
                 e.url_rbuf = -1;
                 e.url_wbuf = -1;
                 e.url_ready = rdy;
                 e.url_ready_pass = pass;
                 e.url_id = i;
                 url_fromid[i] = e;
                 // make sure this slot won't be reused quickly even on map change
                 cvar_set("_urllib_nextslot", ftos((i + 1) % NUM_URL_ID));
                 break;
         }
     }
     else if (url == "-")
     {
         switch (mode)
         {
             case FILE_WRITE:
             case FILE_APPEND:
                 e = new_pure(url_single_fopen_stdout);
                 e.url_fh = URL_FH_STDOUT;
                 e.url_ready = rdy;
                 e.url_ready_pass = pass;
                 rdy(e, pass, URL_READY_CANWRITE);
                 break;
             case FILE_READ:
                 LOG_INFO("url_single_fopen: cannot open '-' for reading\n");
                 rdy(NULL, pass, URL_READY_ERROR);
                 break;
         }
     }
     else
     {
         float fh;
         fh = fopen(url, mode);
         if (fh < 0)
         {
             rdy(NULL, pass, URL_READY_ERROR);
             return;
         }
         else
         {
             e = new_pure(url_single_fopen_file);
             e.url_fh = fh;
             e.url_ready = rdy;
             e.url_ready_pass = pass;
             if (mode == FILE_READ) rdy(e, pass, URL_READY_CANREAD);
             else rdy(e, pass, URL_READY_CANWRITE);
         }
     }
 }
float url_URI_Get_Callback (int id, float status, string data)
Definition at line 27 of file urllib.qc.
References argv(), buf_create, entity(), error, fabs(), LOG_INFO, LOG_INFOF, MIN_URL_ID, NULL, NUM_URL_ID, strunzone(), tokenizebyseparator, URL_FH_CURL, url_fromid, URL_READY_CANREAD, and URL_READY_ERROR.
Referenced by URI_Get_Callback().
 {
     if (id < MIN_URL_ID) return 0;
     id -= MIN_URL_ID;
     if (id >= NUM_URL_ID) return 0;
     entity e;
     e = url_fromid[id];
     if (!e) return 0;
     if (e.url_rbuf >= 0 || e.url_wbuf >= 0)
     {
         LOG_INFOF("WARNING: handle %d (%s) has already received data?!?\n", id + NUM_URL_ID, e.url_url);
         return 0;
     }
     // whatever happens, we will remove the URL from the list of IDs
     url_fromid[id] = NULL;
     // if we get here, we MUST have both buffers cleared
     if (e.url_rbuf != -1 || e.url_wbuf != -1 || e.url_fh != URL_FH_CURL) error("url_URI_Get_Callback: not a request waiting for data");
     if (status == 0)
     {
         // WE GOT DATA!
         float n, i;
         n = tokenizebyseparator(data, "\n");
         e.url_rbuf = buf_create();
         if (e.url_rbuf < 0)
         {
             LOG_INFO("url_URI_Get_Callback: out of memory in buf_create\n");
             e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
             strunzone(e.url_url);
             delete(e);
             return 1;
         }
         e.url_rbufpos = 0;
         if (e.url_rbuf < 0)
         {
             LOG_INFO("url_URI_Get_Callback: out of memory in buf_create\n");
             e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
             strunzone(e.url_url);
             delete(e);
             return 1;
         }
         for (i = 0; i < n; ++i)
             bufstr_set(e.url_rbuf, i, argv(i));
         e.url_ready(e, e.url_ready_pass, URL_READY_CANREAD);
         return 1;
     }
     else
     {
         // an ERROR
         e.url_ready(e, e.url_ready_pass, -fabs(status));
         strunzone(e.url_url);
         delete(e);
         return 1;
     }
 }
Variable Documentation
int autocvar__urllib_nextslot
Definition at line 25 of file urllib.qc.
Referenced by url_fclose(), and url_single_fopen().
int url_attempt
Definition at line 21 of file urllib.qc.
string url_content_type
Definition at line 10 of file urllib.qc.
float url_fh
Definition at line 4 of file urllib.qc.
const float URL_FH_CURL = -1
Definition at line 5 of file urllib.qc.
Referenced by url_fclose(), url_fgets(), url_fputs(), url_single_fopen(), and url_URI_Get_Callback().
const float URL_FH_STDOUT = -2
Definition at line 6 of file urllib.qc.
Referenced by url_fclose(), url_fgets(), url_fputs(), and url_single_fopen().
entity url_fromid[NUM_URL_ID]
Definition at line 24 of file urllib.qc.
Referenced by url_fclose(), url_single_fopen(), and url_URI_Get_Callback().
float url_id
Definition at line 16 of file urllib.qc.
int url_mode
Definition at line 22 of file urllib.qc.
float url_rbuf
Definition at line 14 of file urllib.qc.
float url_rbufpos
Definition at line 15 of file urllib.qc.
url_ready_func url_ready
Definition at line 17 of file urllib.qc.
entity url_ready_pass
Definition at line 18 of file urllib.qc.
string url_url
Definition at line 9 of file urllib.qc.
string url_verb
Definition at line 11 of file urllib.qc.
float url_wbuf
Definition at line 12 of file urllib.qc.
float url_wbufpos
Definition at line 13 of file urllib.qc.