Xonotic: common/mutators/mutator/touchexplode/sv_touchexplode.qc File Reference
sv_touchexplode.qc File Reference
#include "sv_touchexplode.qh"
Functions
MUTATOR_HOOKFUNCTION (touchexplode, PlayerPreThink)
void PlayerTouchExplode (entity p1, entity p2)
REGISTER_MUTATOR (touchexplode, cvar("g_touchexplode"))
Variables
float autocvar_g_touchexplode_damage
float autocvar_g_touchexplode_edgedamage
float autocvar_g_touchexplode_force
float autocvar_g_touchexplode_radius
float touchexplode_time
Function Documentation
MUTATOR_HOOKFUNCTION (touchexplode , PlayerPreThink)
Definition at line 26 of file sv_touchexplode.qc.
References boxesoverlap(), entity(), FOREACH_CLIENT, gameover, IS_DEAD, IS_INDEPENDENT_PLAYER, IS_PLAYER, LAMBDA, M_ARGV, PlayerTouchExplode(), and time.
 {
     entity player = M_ARGV(0, entity);
     if(time > player.touchexplode_time)
     if(!gameover)
     if(!STAT(FROZEN, player))
     if(IS_PLAYER(player))
     if(!IS_DEAD(player))
     if(!IS_INDEPENDENT_PLAYER(player))
         FOREACH_CLIENT(IS_PLAYER(it) && it != player, LAMBDA(
             if(time > it.touchexplode_time)
             if(!STAT(FROZEN, it))
             if(!IS_DEAD(it))
             if (!IS_INDEPENDENT_PLAYER(it))
             if(boxesoverlap(player.absmin, player.absmax, it.absmin, it.absmax))
             {
                 PlayerTouchExplode(player, it);
                 player.touchexplode_time = it.touchexplode_time = time + 0.2;
             }
         ));
 }
void PlayerTouchExplode (entity p1, entity p2)
Definition at line 12 of file sv_touchexplode.qc.
References ATTEN_NORM, autocvar_g_touchexplode_damage, autocvar_g_touchexplode_edgedamage, autocvar_g_touchexplode_force, autocvar_g_touchexplode_radius, CH_TRIGGER, entity(), NULL, RadiusDamage(), sound, spawn(), vector(), and VOL_BASE.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     vector org = (p1.origin + p2.origin) * 0.5;
     org.z += (p1.mins.z + p2.mins.z) * 0.5;
     sound(p1, CH_TRIGGER, SND_GRENADE_IMPACT, VOL_BASE, ATTEN_NORM);
     Send_Effect(EFFECT_EXPLOSION_SMALL, org, '0 0 0', 1);
     entity e = spawn();
     setorigin(e, org);
     RadiusDamage(e, NULL, autocvar_g_touchexplode_damage, autocvar_g_touchexplode_edgedamage, autocvar_g_touchexplode_radius, NULL, NULL, autocvar_g_touchexplode_force, DEATH_TOUCHEXPLODE.m_id, NULL);
     delete(e);
 }
REGISTER_MUTATOR (touchexplode , cvar("g_touchexplode"))
Variable Documentation
float autocvar_g_touchexplode_damage
Definition at line 4 of file sv_touchexplode.qc.
Referenced by PlayerTouchExplode().
float autocvar_g_touchexplode_edgedamage
Definition at line 5 of file sv_touchexplode.qc.
Referenced by PlayerTouchExplode().
float autocvar_g_touchexplode_force
Definition at line 6 of file sv_touchexplode.qc.
Referenced by PlayerTouchExplode().
float autocvar_g_touchexplode_radius
Definition at line 3 of file sv_touchexplode.qc.
Referenced by PlayerTouchExplode().
float touchexplode_time
Definition at line 10 of file sv_touchexplode.qc.