Xonotic: client/bgmscript.qh File Reference
bgmscript.qh File Reference
#include <common/mapobjects/bgmscript.qh>
Functions
void BGMScript_InitEntity (entity e)
classfield (BGMScript).float just_toggled
float doBGMScript (entity e)
Variables
float autocvar_bgmvolume
float bgmtime
Function Documentation
void BGMScript_InitEntity (entity e)
Definition at line 116 of file bgmscript.qc.
References BGMScript_Init(), bgmscriptbuf, bgmscriptbufloaded, bgmscriptbufsize, LOG_INFOF, strcat(), strfree, strlen(), and substring().
 {
     float l;
     string m;
     if(e.bgmscript != "")
     {
         if(!bgmscriptbufloaded)
             BGMScript_Init();
         float i;
         m = strcat(e.bgmscript, " ");
         l = strlen(m);
         e.bgmscriptline0 = -1;
         for(i = 0; i < bgmscriptbufsize; ++i)
         {
             if(substring(bufstr_get(bgmscriptbuf, i), 0, l) == m)
                 break;
         }
         e.bgmscriptline = e.bgmscriptline0 = i;
         if(i >= bgmscriptbufsize)
         {
             LOG_INFOF("ERROR: bgmscript does not define %s", e.bgmscript);
             strfree(e.bgmscript);
         }
     }
 }
classfield (BGMScript)
float doBGMScript (entity e)
Definition at line 173 of file bgmscript.qc.
References argv(), autocvar_bgmvolume, bgmscriptbuf, bgmtime, drawframetime, GetCurrentAmplitude(), GetTimeForAmplitude(), stof(), and tokenize_console.
 {
     float amp, vel;
     if(e.bgmscript == "")
         return 1;
     if(autocvar_bgmvolume <= 0)
         return -1;
     e.just_toggled = false;
     if(bgmtime < 0)
         return -1;
     if(bgmtime < e.bgmscripttime)
     {
         amp = GetCurrentAmplitude(e, e.bgmscripttime - e.bgmscriptstatetime + drawframetime);
         e.bgmscriptline = e.bgmscriptline0;
         e.bgmscripttime = bgmtime;
         // treat this as a stop event for all notes, to prevent sticking keys
         e.bgmscriptstate = false;
         e.bgmscriptvolume = 1;
         e.bgmscriptstatetime = bgmtime - GetTimeForAmplitude(e, amp);
     }
     // find the CURRENT line
     for (;;)
     {
         tokenize_console(bufstr_get(bgmscriptbuf, e.bgmscriptline));
         if(stof(argv(1)) >= bgmtime || argv(0) != e.bgmscript)
         {
             e.bgmscripttime = bgmtime;
             return GetCurrentAmplitude(e, bgmtime - e.bgmscriptstatetime);
         }
         else if(bgmtime >= stof(argv(1)))
         {
             e.bgmscriptline += 1;
             e.bgmscripttime = stof(argv(1));
             amp = GetCurrentAmplitude(e, e.bgmscripttime - e.bgmscriptstatetime);
             // time code reached!
             vel = stof(argv(2));
             if(vel > 0)
             {
                 e.just_toggled = e.bgmscriptstate = true;
                 e.bgmscriptvolume = vel;
             }
             else
                 e.just_toggled = e.bgmscriptstate = false;
             e.bgmscriptstatetime = e.bgmscripttime - GetTimeForAmplitude(e, amp);
         }
     }
 }
Variable Documentation
float autocvar_bgmvolume
Definition at line 5 of file bgmscript.qh.
Referenced by doBGMScript().
float bgmtime
Definition at line 9 of file bgmscript.qh.
Referenced by doBGMScript().