Xonotic: common/items/all.qc File Reference
all.qc File Reference
#include "all.qh"
Functions
void Dump_Items ()
string Item_Model (string item_mdl)
string Item_Sound (string it_snd)
Function Documentation
void Dump_Items ()
Definition at line 3 of file all.qc.
References FOREACH, and ITEM_HANDLE.
Referenced by GENERIC_COMMAND(), and STATIC_INIT().
 {
     FOREACH(Items, true, ITEM_HANDLE(Show, it));
 }
string Item_Model (string item_mdl)
Definition at line 8 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
Referenced by GENERIC_COMMAND(), and REGISTER_ITEM().
 {
     string output = strcat("models/items/", item_mdl);
 #ifdef SVQC
     MUTATOR_CALLHOOK(ItemModel, item_mdl, output);
     output = M_ARGV(1, string);
 #endif
     return output;
 }
string Item_Sound (string it_snd)
Definition at line 18 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
Referenced by REGISTER_ITEM(), and SND_CTF_TAKEN().
 {
     string output = strcat("misc/", it_snd);
 #ifdef SVQC
         MUTATOR_CALLHOOK(ItemSound, it_snd, output);
         return M_ARGV(1, string);
 #else
         return output;
 #endif
 }