Xonotic: Duel Class Reference
Duel Class Reference
Public Member Functions
Duel ()
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_configuremenu ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isForcedSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
int m_id = 0
string m_legacydefaults = ""
DO NOT USE, this is compatibility for legacy maps!
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 586 of file mapinfo.qh.
Constructor & Destructor Documentation
Duel::Duel () inline
Definition at line 587 of file mapinfo.qh.
     {
         this.gametype_init(this, _("Duel"),"duel","g_duel",false,true,"","timelimit=10 pointlimit=0 leadlimit=0",_("Fight in a one versus one arena battle to decide the winner"));
     }
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
virtual void Gametype::describe () inline virtual inherited
Definition at line 75 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual inherited
Definition at line 81 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual inherited
Definition at line 87 of file mapinfo.qh.
References cons(), m_flags, and MAPINFO_TYPE_ALL.
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = gteamplay;
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = gusepoints;
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void Gametype::m_configuremenu () inline virtual inherited
Reimplemented in Invasion, FreezeTag, NexBall, Onslaught, Assault, KeyHunt, Domination, ClanArena, CaptureTheFlag, TeamDeathmatch, RaceCTS, Race, and LastManStanding.
Definition at line 69 of file mapinfo.qh.
References string_null, and TC.
Referenced by GameType_ConfigureSliders_for_CurrentGametype().
     {
         TC(Gametype, this);
         returns(menu, _("Frag limit:"),      5,  100,  5, "fraglimit_override",        string_null,                    _("The amount of frags needed before the match will end"));
     }
virtual void Gametype::m_generate_mapinfo () inline virtual inherited
Reimplemented in Invasion, NexBall, Onslaught, Assault, Domination, CaptureTheFlag, RaceCTS, and Race.
Definition at line 53 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
virtual void Duel::m_isAlwaysSupported () inline virtual
Reimplemented from Gametype.
Definition at line 591 of file mapinfo.qh.
     {
         return (diameter < 16384);
     }
virtual void Duel::m_isForcedSupported () inline virtual
Reimplemented from Gametype.
Definition at line 595 of file mapinfo.qh.
References m_flags, and MapInfo_Map_supportedGametypes.
     {
         // force all DM maps to work in duel?!
         // TODO: we should really check the size of maps, some DM maps do not work for duel!
         if(!(MapInfo_Map_supportedGametypes & this.m_flags) && (MapInfo_Map_supportedGametypes & MAPINFO_TYPE_DEATHMATCH.m_flags))
             return true;
         return false;
     }
virtual void Gametype::m_isTwoBaseMode () inline virtual inherited
Reimplemented in NexBall, Assault, CaptureTheFlag, and Race.
Definition at line 57 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_parse_mapinfo () inline virtual inherited
Reimplemented in Invasion, FreezeTag, KeyHunt, Domination, ClanArena, TeamDeathmatch, and Race.
Definition at line 49 of file mapinfo.qh.
     {
         return false;
     }
Member Data Documentation
bool Gametype::frags = true inherited
does this gametype use a point limit?
Definition at line 35 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
int Gametype::items = 0 inherited
game type ID
Definition at line 25 of file mapinfo.qh.
int Gametype::m_id = 0 inherited
Definition at line 23 of file mapinfo.qh.
Referenced by MapInfo_LoadMapSettings_SaveGameType().
string Gametype::m_legacydefaults = "" inherited
DO NOT USE, this is compatibility for legacy maps!
Definition at line 46 of file mapinfo.qh.
Referenced by _MapInfo_GetDefault().
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 33 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/mapinfo.qh