Xonotic: menu/xonotic/inputbox.qh File Reference
inputbox.qh File Reference
#include "../item/inputbox.qh"
Classes
class XonoticInputBox
Functions
entity makeXonoticInputBox (float, string)
entity makeXonoticInputBox_T (float, string, string theTooltip)
Function Documentation
entity makeXonoticInputBox (float , string)
Definition at line 10 of file inputbox.qc.
References makeXonoticInputBox_T(), and string_null.
Referenced by XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticHUDExitDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticServerListTab_fill(), and XonoticUserbindEditDialog_fill().
 {
     return makeXonoticInputBox_T(doEditColorCodes, theCvar, string_null);
 }
entity makeXonoticInputBox_T (float , string , string theTooltip)
Definition at line 3 of file inputbox.qc.
References entity(), and NEW.
Referenced by makeXonoticInputBox(), XonoticFirstRunDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), and XonoticServerCreateTab_fill().
 {
     entity me;
     me = NEW(XonoticInputBox);
     me.configureXonoticInputBox(me, doEditColorCodes, theCvar, theTooltip);
     return me;
 }