Xonotic: WyvernAttack Class Reference
WyvernAttack Class Reference
Public Member Functions
virtual void describe ()
virtual void display ()
virtual void wr_aim ()
(SERVER) runs bot aiming code for this weapon
virtual void wr_checkammo1 ()
(SERVER) checks ammo for weapon primary
virtual void wr_checkammo2 ()
(SERVER) checks ammo for weapon second
virtual void wr_config ()
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
virtual void wr_drop ()
(SERVER) the weapon is dropped
virtual void wr_glow ()
(CLIENT) weapon specific glow
virtual void wr_gonethink ()
(SERVER) logic to run when weapon is lost
virtual void wr_impacteffect ()
(CLIENT) impact effect for weapon explosion
virtual void wr_init ()
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
virtual void wr_killmessage ()
(SERVER) notification number for kill message (may inspect w_deathtype for details)
virtual void wr_pickup ()
(SERVER) a weapon is picked up
virtual void wr_playerdeath ()
(SERVER) called whenever a player dies
virtual void wr_reload ()
(SERVER) handles reloading for weapon
virtual void wr_resetplayer ()
(SERVER) clears fields that the weapon may use
virtual void wr_setup ()
(SERVER) setup weapon data
virtual void wr_suicidemessage ()
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
virtual void wr_think ()
(SERVER) logic to run every frame
virtual void wr_update ()
(SERVER) update cvar based properties
virtual void wr_zoomreticle ()
(CLIENT) weapon specific zoom reticle
Public Attributes
int ammo_field = ammo_none
float bot_pickupbasevalue = 0
int impulse = 9
int m_id = 0
Model m_model = MDL_PORTO_ITEM
string m_name = _("Wyvern attack")
entity m_pickup = NULL
string mdl = "porto"
string model2 = "weaponporto"
string netname = "wyvern"
int spawnflags = WEP_TYPE_OTHER | WEP_FLAG_HIDDEN | WEP_FLAG_MUTATORBLOCKED
string w_crosshair = "gfx/crosshairporto"
float w_crosshair_size = 0.6
WepSet weapons = '0 0 0'
A: WEPSET_id : WEPSET_...
vector wpcolor = '0.5 0.5 0.5'
Detailed Description
Definition at line 27 of file wyvern.qc.
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 276 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Weapon::display () inline virtual inherited
Reimplemented from Object.
Definition at line 128 of file weapon.qh.
References cvar_string(), and string_null.
{
         returns(this.m_name, this.model2 ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.model2) : string_null);
     }
virtual void Weapon::wr_aim () inline virtual inherited
(SERVER) runs bot aiming code for this weapon
Definition at line 96 of file weapon.qh.
Referenced by havocbot_ai().
 {}
virtual void Weapon::wr_checkammo1 () inline virtual inherited
(SERVER) checks ammo for weapon primary
Definition at line 92 of file weapon.qh.
Referenced by client_hasweapon(), W_Reload(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_checkammo2 () inline virtual inherited
(SERVER) checks ammo for weapon second
Definition at line 94 of file weapon.qh.
Referenced by client_hasweapon(), W_Reload(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_config () inline virtual inherited
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
Definition at line 114 of file weapon.qh.
 {}
virtual void Weapon::wr_drop () inline virtual inherited
(SERVER) the weapon is dropped
Definition at line 123 of file weapon.qh.
 {}
virtual void Weapon::wr_glow () inline virtual inherited
(CLIENT) weapon specific glow
Definition at line 121 of file weapon.qh.
Referenced by weaponentity_glowmod().
 { return '0 0 0'; }
virtual void Weapon::wr_gonethink () inline virtual inherited
(SERVER) logic to run when weapon is lost
Definition at line 112 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_impacteffect () inline virtual inherited
(CLIENT) impact effect for weapon explosion
Definition at line 108 of file weapon.qh.
 {}
virtual void Weapon::wr_init () inline virtual inherited
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
Definition at line 98 of file weapon.qh.
Referenced by GrappleHookInit().
 {}
virtual void Weapon::wr_killmessage () inline virtual inherited
(SERVER) notification number for kill message (may inspect w_deathtype for details)
Definition at line 102 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_pickup () inline virtual inherited
(SERVER) a weapon is picked up
Definition at line 125 of file weapon.qh.
 {}
virtual void Weapon::wr_playerdeath () inline virtual inherited
(SERVER) called whenever a player dies
Definition at line 110 of file weapon.qh.
Referenced by PlayerDamage().
 {}
virtual void Weapon::wr_reload () inline virtual inherited
(SERVER) handles reloading for weapon
Definition at line 104 of file weapon.qh.
Referenced by IMPULSE(), and W_SwitchWeapon().
 {}
virtual void Weapon::wr_resetplayer () inline virtual inherited
(SERVER) clears fields that the weapon may use
Definition at line 106 of file weapon.qh.
 {}
virtual void Weapon::wr_setup () inline virtual inherited
(SERVER) setup weapon data
Definition at line 88 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_suicidemessage () inline virtual inherited
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
Definition at line 100 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 90 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_update () inline virtual inherited
(SERVER) update cvar based properties
Definition at line 127 of file weapon.qh.
 {}
virtual void Weapon::wr_zoomreticle () inline virtual inherited
(CLIENT) weapon specific zoom reticle
Definition at line 116 of file weapon.qh.
{
         // no weapon specific image for this weapon
         return false;
     }
Member Data Documentation
int PortoLaunch::ammo_field = ammo_none inherited
Definition at line 3 of file porto.qc.
float PortoLaunch::bot_pickupbasevalue = 0 inherited
Definition at line 6 of file porto.qc.
int WyvernAttack::impulse = 9
Definition at line 29 of file wyvern.qc.
int Weapon::m_id = 0 inherited
Definition at line 57 of file weapon.qh.
Referenced by client_hasweapon(), PlayerDamage(), TEST(), W_SwitchWeapon(), W_SwitchWeapon_Force(), W_ThrowWeapon(), and weapon_prepareattack_checkammo().
Model PortoLaunch::m_model = MDL_PORTO_ITEM inherited
Definition at line 10 of file porto.qc.
string WyvernAttack::m_name = _("Wyvern attack")
Definition at line 31 of file wyvern.qc.
entity Weapon::m_pickup = NULL inherited
Definition at line 85 of file weapon.qh.
string PortoLaunch::mdl = "porto" inherited
Definition at line 8 of file porto.qc.
string PortoLaunch::model2 = "weaponporto" inherited
Definition at line 14 of file porto.qc.
string WyvernAttack::netname = "wyvern"
Definition at line 30 of file wyvern.qc.
int WyvernAttack::spawnflags = WEP_TYPE_OTHER | WEP_FLAG_HIDDEN | WEP_FLAG_MUTATORBLOCKED
Definition at line 28 of file wyvern.qc.
string PortoLaunch::w_crosshair = "gfx/crosshairporto" inherited
Definition at line 12 of file porto.qc.
float PortoLaunch::w_crosshair_size = 0.6 inherited
Definition at line 13 of file porto.qc.
WepSet Weapon::weapons = '0 0 0' inherited
A: WEPSET_id : WEPSET_...
Definition at line 59 of file weapon.qh.
vector PortoLaunch::wpcolor = '0.5 0.5 0.5' inherited
Definition at line 7 of file porto.qc.
The documentation for this class was generated from the following file:
common/monsters/monster/wyvern.qc