Xonotic: menu/xonotic/dialog_termsofservice.qc File Reference
dialog_termsofservice.qc File Reference
#include "dialog_termsofservice.qh"
#include "../menu.qh"
#include "mainwindow.qh"
#include "dialog_firstrun.qh"
#include "textbox.qh"
#include "textlabel.qh"
#include "button.qh"
#include "util.qh"
Functions
void Close_Clicked (entity btn, entity me)
void DontAccept_Clicked (entity btn, entity me)
void XonoticToS_OnGet (entity fh, entity me, int status)
void XonoticToSDialog_fill (entity me)
void XonoticToSDialog_loadXonoticToS (entity me)
bool XonoticToSDialog_shouldShow ()
Function Documentation
Close_Clicked()
void Close_Clicked (entity btn, entity me)
Definition at line 11 of file dialog_termsofservice.qc.
References _Nex_ExtResponseSystem_NewToS, cvar_set(), Dialog_Close(), ftos(), localcmd, LOG_INFOF, and main.
 {
     LOG_INFOF("Accepted ToS version %d", _Nex_ExtResponseSystem_NewToS);
     cvar_set("_termsofservice_accepted", ftos(_Nex_ExtResponseSystem_NewToS));
     localcmd("saveconfig\n");
     if (main.firstRunDialog.shouldShow())
         main.firstDraw = true;
     Dialog_Close(btn, me);
 }
DontAccept_Clicked()
void DontAccept_Clicked (entity btn, entity me)
Definition at line 21 of file dialog_termsofservice.qc.
References localcmd.
 {
     localcmd("quit\n");
 }
XonoticToS_OnGet()
void XonoticToS_OnGet (entity fh, entity me, int status)
Definition at line 31 of file dialog_termsofservice.qc.
References strcat(), strfree, strzone(), url_fclose(), url_fgets(), URL_READY_CANREAD, URL_READY_CLOSED, and URL_READY_ERROR.
Referenced by XonoticToSDialog_loadXonoticToS().
 {
     switch (status) {
         case URL_READY_CLOSED:
         {
             break;
         }
         case URL_READY_ERROR:
         {
             me.text = strzone("Error reading ToS");
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         case URL_READY_CANREAD:
         {
             strfree(me.text);
             string temp = "";
             for (string s; (s = url_fgets(fh)); )
             {
                 if (temp != "")
                     temp = strcat(temp, "\n", s);
                 else
                     temp = s;
             }
             url_fclose(fh);
             me.text = strzone(temp);
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         default:
         {
             break;
         }
     }
 }
XonoticToSDialog_fill()
void XonoticToSDialog_fill (entity me)
Definition at line 72 of file dialog_termsofservice.qc.
References autocvar__termsofservice_accepted, and entity().
 {
     entity e;
     string subtitle;
     if (autocvar__termsofservice_accepted > 0)
         subtitle = _("Terms of Service have been updated. Please read them before continuing:");
     else
         subtitle = _("Welcome to Xonotic! Please read the following Terms of Service:");
     me.TR(me);
         me.TD(me, 1, 5, e = makeXonoticTextLabel(0, subtitle));
         e.allowWrap = 1;
     me.TR(me);
     me.TR(me);
         me.TD(me, me.rows - 4, me.columns, me.textBox = makeXonoticTextBox());
     me.TR(me);
     me.gotoRC(me, me.rows - 1, 0);
         me.TD(me, 1, me.columns/2, e = makeXonoticButton(_("Accept"), '0 1 0'));
         e.onClick = Close_Clicked;
         e.onClickEntity = me;
         me.TD(me, 1, me.columns/2, e = makeXonoticButton(_("Don't accept (quit the game)"), '1 0 0'));
         e.onClick = DontAccept_Clicked;
         e.onClickEntity = me;
 }
XonoticToSDialog_loadXonoticToS()
void XonoticToSDialog_loadXonoticToS (entity me)
Definition at line 26 of file dialog_termsofservice.qc.
References FILE_READ, termsofservice_url, url_single_fopen(), and XonoticToS_OnGet().
 {
     url_single_fopen(termsofservice_url, FILE_READ, XonoticToS_OnGet, me);
 }
XonoticToSDialog_shouldShow()
bool XonoticToSDialog_shouldShow ()
Definition at line 67 of file dialog_termsofservice.qc.
References _Nex_ExtResponseSystem_NewToS, and autocvar__termsofservice_accepted.
 {
     return (_Nex_ExtResponseSystem_NewToS && _Nex_ExtResponseSystem_NewToS > autocvar__termsofservice_accepted);
 }