Xonotic: server/cl_client.qc File Reference
cl_client.qc File Reference
#include "cl_client.qh"
#include "anticheat.qh"
#include "cl_impulse.qh"
#include "cl_player.qh"
#include "ipban.qh"
#include "miscfunctions.qh"
#include "portals.qh"
#include "teamplay.qh"
#include "playerdemo.qh"
#include "spawnpoints.qh"
#include "g_damage.qh"
#include "g_hook.qh"
#include "command/common.qh"
#include "cheats.qh"
#include "g_world.qh"
#include "race.qh"
#include "antilag.qh"
#include "campaign.qh"
#include "bot/bot.qh"
#include "bot/navigation.qh"
#include "../common/ent_cs.qh"
#include "../common/state.qh"
#include "../common/triggers/teleporters.qh"
#include "../common/vehicles/all.qh"
#include "weapons/hitplot.qh"
#include "weapons/weaponsystem.qh"
#include "../common/net_notice.qh"
#include "../common/physics/player.qh"
#include "../common/items/all.qc"
#include "../common/mutators/mutator/waypoints/all.qh"
#include "../common/triggers/subs.qh"
#include "../common/triggers/triggers.qh"
#include "../common/triggers/trigger/secret.qh"
#include "../common/minigames/sv_minigames.qh"
#include "../common/items/inventory.qh"
#include "../common/monsters/sv_monsters.qh"
#include "../lib/warpzone/server.qh"
Functions
void send_CSQC_teamnagger ()
bool ClientData_Send (entity this, entity to, int sf)
void ClientData_Attach (entity this)
void ClientData_Detach (entity this)
void ClientData_Touch (entity e)
void SetSpectatee (entity player, entity spectatee)
string CheckPlayerModel (string plyermodel)
void setplayermodel (entity e, string modelname)
void FixPlayermodel (entity player)
void PutObserverInServer ()
int player_getspecies (entity this)
void PutClientInServer ()
Called when a client spawns in the server.
void ClientInit_misc ()
bool ClientInit_SendEntity (entity this, entity to, int sf)
void ClientInit_CheckUpdate ()
void ClientInit_Spawn ()
void SetNewParms ()
void SetChangeParms ()
void DecodeLevelParms (entity this)
void ClientKill_Now_TeamChange (entity this)
void ClientKill_Now ()
void KillIndicator_Think ()
void ClientKill_TeamChange (float targetteam)
void ClientKill ()
void FixClientCvars (entity e)
float PlayerInIDList (entity p, string idlist)
void ClientConnect ()
ClientConnect
void ReadyCount ()
void ClientDisconnect ()
void ChatBubbleThink ()
void UpdateChatBubble ()
void respawn ()
void play_countdown (float finished, string samp)
void player_powerups ()
float CalcRegen (float current, float stable, float regenfactor, float regenframetime)
float CalcRot (float current, float stable, float rotfactor, float rotframetime)
float CalcRotRegen (float current, float regenstable, float regenfactor, float regenlinear, float regenframetime, float rotstable, float rotfactor, float rotlinear, float rotframetime, float limit)
void player_regen ()
void SetZoomState (float z)
void GetPressedKeys ()
void SpectateCopy (entity this, entity spectatee)
bool SpectateUpdate ()
bool SpectateSet ()
bool Spectate (entity pl)
bool SpectateNext ()
bool SpectatePrev ()
void ShowRespawnCountdown ()
void LeaveSpectatorMode ()
bool nJoinAllowed (entity this, entity ignore)
Determines whether the player is allowed to join.
void checkSpectatorBlock ()
Checks whether the client is an observer or spectator, if so, he will get kicked after g_maxplayers_spectator_blocktime seconds.
void PrintWelcomeMessage ()
void ObserverThink ()
void SpectatorThink ()
void vehicles_enter (entity pl, entity veh)
void PlayerUseKey ()
void () nexball_setstatus
void PlayerPreThink ()
void DrownPlayer (entity this)
void PlayerPostThink ()
Variables
string netname_previous
string FallbackPlayerModel
float model_randomizer
float ebouncefactor
float ebouncestop
float clientkill_nexttime
float clientkilltime
entity chatbubbleentity
float BUTTON_CHAT
float zoomstate_set
float usekeypressed
float last_vehiclecheck
int items_added
float idlekick_lasttimeleft
Function Documentation
float CalcRegen (float current, float stable, float regenfactor, float regenframetime)
Definition at line 1465 of file cl_client.qc.
References min().
Referenced by CalcRotRegen().
 {
     if(current > stable)
         return current;
     else if(current > stable - 0.25) // when close enough, "snap"
         return stable;
     else
         return min(stable, current + (stable - current) * regenfactor * regenframetime);
 }
float CalcRot (float current, float stable, float rotfactor, float rotframetime)
Definition at line 1475 of file cl_client.qc.
References max().
Referenced by CalcRotRegen().
 {
     if(current < stable)
         return current;
     else if(current < stable + 0.25) // when close enough, "snap"
         return stable;
     else
         return max(stable, current + (stable - current) * rotfactor * rotframetime);
 }
float CalcRotRegen (float current, float regenstable, float regenfactor, float regenlinear, float regenframetime, float rotstable, float rotfactor, float rotlinear, float rotframetime, float limit)
Definition at line 1485 of file cl_client.qc.
References CalcRegen(), CalcRot(), max(), and min().
Referenced by player_regen().
 {
     if(current > rotstable)
     {
         if(rotframetime > 0)
         {
             current = CalcRot(current, rotstable, rotfactor, rotframetime);
             current = max(rotstable, current - rotlinear * rotframetime);
         }
     }
     else if(current < regenstable)
     {
         if(regenframetime > 0)
         {
             current = CalcRegen(current, regenstable, regenfactor, regenframetime);
             current = min(regenstable, current + regenlinear * regenframetime);
         }
     }
     if(current > limit)
         current = limit;
     return current;
 }
void ChatBubbleThink ()
Definition at line 1253 of file cl_client.qc.
References IS_DEAD, IS_PLAYER, mdl, model, owner, SELFPARAM, time, and world.
Referenced by UpdateChatBubble().
 {SELFPARAM();
     self.nextthink = time;
     if ((self.owner.alpha < 0) || self.owner.chatbubbleentity != self)
     {
         if(self.owner) // but why can that ever be world?
             self.owner.chatbubbleentity = world;
         remove(self);
         return;
     }
     self.mdl = "";
     if ( !IS_DEAD(self.owner) && IS_PLAYER(self.owner) )
     {
         if ( self.owner.active_minigame )
             self.mdl = "models/sprites/minigame_busy.iqm";
         else if ( self.owner.BUTTON_CHAT )
             self.mdl = "models/misc/chatbubble.spr";
     }
     if ( self.model != self.mdl )
         _setmodel(self, self.mdl);
 }
string CheckPlayerModel (string plyermodel)
Definition at line 123 of file cl_client.qc.
References autocvar_sv_servermodelsonly, cvar_defstring(), FallbackPlayerModel, fexists(), strtolower(), strzone(), and substring().
Referenced by FixPlayermodel().
{
     if(FallbackPlayerModel != cvar_defstring("_cl_playermodel"))
     {
         // note: we cannot summon Don Strunzone here, some player may
         // still have the model string set. In case anyone manages how
         // to change a cvar default, we'll have a small leak here.
         FallbackPlayerModel = strzone(cvar_defstring("_cl_playermodel"));
     }
     // only in right path
     if( substring(plyermodel,0,14) != "models/player/")
         return FallbackPlayerModel;
     // only good file extensions
     if(substring(plyermodel,-4,4) != ".zym")
     if(substring(plyermodel,-4,4) != ".dpm")
     if(substring(plyermodel,-4,4) != ".iqm")
     if(substring(plyermodel,-4,4) != ".md3")
     if(substring(plyermodel,-4,4) != ".psk")
         return FallbackPlayerModel;
     // forbid the LOD models
     if(substring(plyermodel, -9,5) == "_lod1")
         return FallbackPlayerModel;
     if(substring(plyermodel, -9,5) == "_lod2")
         return FallbackPlayerModel;
     if(plyermodel != strtolower(plyermodel))
         return FallbackPlayerModel;
     // also, restrict to server models
     if(autocvar_sv_servermodelsonly)
     {
         if(!fexists(plyermodel))
             return FallbackPlayerModel;
     }
     return plyermodel;
 }
void checkSpectatorBlock ()
Checks whether the client is an observer or spectator, if so, he will get kicked after g_maxplayers_spectator_blocktime seconds.
Definition at line 1887 of file cl_client.qc.
References autocvar_g_maxplayers_spectator_blocktime, caplayer, IS_OBSERVER, IS_REAL_CLIENT, IS_SPEC, MSG_INFO, SELFPARAM, spectatortime, and time.
Referenced by PlayerPreThink().
 {SELFPARAM();
     if(IS_SPEC(self) || IS_OBSERVER(self))
     if(!self.caplayer)
     if(IS_REAL_CLIENT(self))
     {
         if( time > (self.spectatortime + autocvar_g_maxplayers_spectator_blocktime) ) {
             Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_QUIT_KICK_SPECTATING);
             dropclient(self);
         }
     }
 }
void ClientConnect ()
ClientConnect
Called when a client connects to the server
Definition at line 985 of file cl_client.qc.
References accuracy_init(), allowed_timeouts, anticheat_init(), APP_TEAM_ENT_4, assert, autocvar_bot_vs_human, autocvar_g_balance_teams, autocvar_g_campaign, autocvar_g_campaign_forceteam, autocvar_g_forced_team_blue, autocvar_g_forced_team_otherwise, autocvar_g_forced_team_pink, autocvar_g_forced_team_red, autocvar_g_forced_team_yellow, autocvar_g_maxplayers_spectator_blocktime, autocvar_sv_eventlog, autocvar_sv_spectate, autocvar_sv_teamnagger, autocvar_sv_timeout_number, Ban_MaybeEnforceBanOnce(), BIT, blockSpectators, bot_clientconnect(), bot_relinkplayerlist(), c1, c2, c3, c4, campaign_bots_may_start, CheckAllowedTeams(), classname, ClientData_Attach(), ClientState_attach(), clientstuff, DecodeLevelParms(), entity(), etof(), FixClientCvars(), FL_CLIENT, flags, FOREACH_ENTITY_FLOAT, ftos(), g_ca, g_cts, g_race, g_weaponarena_weapons, GameLogEcho(), GetCvars(), getwelcomemessage(), init_for_player_needed, IS_BOT_CLIENT, IS_CLIENT, IS_REAL_CLIENT, JoinBestTeam(), jointime, just_joined, LogTeamchange(), model_randomizer, motd_actived_time, MSG_CENTER, MSG_INFO, MUTATOR_CALLHOOK, netaddress, netname, netname_previous, NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, player_count, playerdemo_init(), playerid, playerid_last, PlayerInIDList(), PlayerScore_Attach(), random(), SELFPARAM, send_CSQC_teamnagger(), spectatortime, STR_OBSERVER, STR_PLAYER, strcat(), strzone(), sv_foginterval, team, team_forced, teamplay, time, version_nagtime, W_HitPlotOpen(), WEPSET, WITH, and world.
Referenced by bot_spawn().
 {
     SELFPARAM();
     if (Ban_MaybeEnforceBanOnce(this)) return;
     assert(!IS_CLIENT(this), return);
     assert(player_count >= 0, player_count = 0);
     this.classname = "player_joining";
     this.flags = FL_CLIENT;
 #ifdef WATERMARK
     Send_Notification(NOTIF_ONE_ONLY, this, MSG_INFO, INFO_WATERMARK, WATERMARK);
 #endif
     this.version_nagtime = time + 10 + random() * 10;
     // TODO: xonstat elo.txt support, until then just 404s
     if (false && IS_REAL_CLIENT(this)) { PlayerStats_PlayerBasic_CheckUpdate(this); }
     ClientState_attach(this);
     // TODO: fold all of these into ClientState
     DecodeLevelParms(this);
     PlayerScore_Attach(this);
     ClientData_Attach(this);
     accuracy_init(this);
     Inventory_new(this);
     playerdemo_init(this);
     anticheat_init(this);
     entcs_attach(this);
     W_HitPlotOpen(this);
     bot_clientconnect(this);
     // identify the right forced team
     if (autocvar_g_campaign)
     {
         if (IS_REAL_CLIENT(this)) // only players, not bots
         {
             switch (autocvar_g_campaign_forceteam)
             {
                 case 1: this.team_forced = NUM_TEAM_1; break;
                 case 2: this.team_forced = NUM_TEAM_2; break;
                 case 3: this.team_forced = NUM_TEAM_3; break;
                 case 4: this.team_forced = NUM_TEAM_4; break;
                 default: this.team_forced = 0;
             }
         }
     }
     else if (PlayerInIDList(this, autocvar_g_forced_team_red))    this.team_forced = NUM_TEAM_1;
     else if (PlayerInIDList(this, autocvar_g_forced_team_blue))   this.team_forced = NUM_TEAM_2;
     else if (PlayerInIDList(this, autocvar_g_forced_team_yellow)) this.team_forced = NUM_TEAM_3;
     else if (PlayerInIDList(this, autocvar_g_forced_team_pink))   this.team_forced = NUM_TEAM_4;
     else switch (autocvar_g_forced_team_otherwise)
     {
         default: this.team_forced = 0; break;
         case "red": this.team_forced = NUM_TEAM_1; break;
         case "blue": this.team_forced = NUM_TEAM_2; break;
         case "yellow": this.team_forced = NUM_TEAM_3; break;
         case "pink": this.team_forced = NUM_TEAM_4; break;
         case "spectate":
         case "spectator":
             this.team_forced = -1;
             break;
     }
     if (!teamplay && this.team_forced > 0) this.team_forced = 0;
     JoinBestTeam(this, false, false); // if the team number is valid, keep it
     if (autocvar_sv_spectate || autocvar_g_campaign || this.team_forced < 0) {
         this.classname = STR_OBSERVER;
     } else {
         if (!teamplay || autocvar_g_balance_teams)
         {
             this.classname = STR_PLAYER;
             campaign_bots_may_start = 1;
         }
         else
         {
             this.classname = STR_OBSERVER; // do it anyway
         }
     }
     this.playerid = ++playerid_last;
     PlayerStats_GameReport_AddEvent(sprintf("kills-%d", this.playerid));
     // always track bots, don't ask for cl_allow_uidtracking
     if (IS_BOT_CLIENT(this)) PlayerStats_GameReport_AddPlayer(this);
     if (autocvar_sv_eventlog)
         GameLogEcho(strcat(":join:", ftos(this.playerid), ":", ftos(etof(this)), ":", ((IS_REAL_CLIENT(this)) ? this.netaddress : "bot"), ":", this.netname));
     LogTeamchange(this.playerid, this.team, 1);
     this.just_joined = true;  // stop spamming the eventlog with additional lines when the client connects
     this.netname_previous = strzone(this.netname);
     Send_Notification(NOTIF_ALL, NULL, MSG_INFO, (teamplay ? APP_TEAM_ENT_4(this, INFO_JOIN_CONNECT_TEAM_) : INFO_JOIN_CONNECT), this.netname);
     stuffcmd(this, clientstuff, "\n");
     stuffcmd(this, "cl_particles_reloadeffects\n"); // TODO do we still need this?
     FixClientCvars(this);
     // Grappling hook
     stuffcmd(this, "alias +hook +button6\n");
     stuffcmd(this, "alias -hook -button6\n");
     // Jetpack binds
     stuffcmd(this, "alias +jetpack +button10\n");
     stuffcmd(this, "alias -jetpack -button10\n");
     // get version info from player
     stuffcmd(this, "cmd clientversion $gameversion\n");
     // get other cvars from player
     GetCvars(0);
     // notify about available teams
     if (teamplay)
     {
         CheckAllowedTeams(this);
         int t = 0;
         if (c1 >= 0) t |= BIT(0);
         if (c2 >= 0) t |= BIT(1);
         if (c3 >= 0) t |= BIT(2);
         if (c4 >= 0) t |= BIT(3);
         stuffcmd(this, sprintf("set _teams_available %d\n", t));
     }
     else
     {
         stuffcmd(this, "set _teams_available 0\n");
     }
     bot_relinkplayerlist();
     this.spectatortime = time;
     if (blockSpectators)
     {
         Send_Notification(NOTIF_ONE_ONLY, this, MSG_INFO, INFO_SPECTATE_WARNING, autocvar_g_maxplayers_spectator_blocktime);
     }
     this.jointime = time;
     this.allowed_timeouts = autocvar_sv_timeout_number;
     if (IS_REAL_CLIENT(this))
     {
         if (!autocvar_g_campaign)
         {
             this.motd_actived_time = -1;
             Send_Notification(NOTIF_ONE_ONLY, this, MSG_CENTER, CENTER_MOTD, getwelcomemessage());
         }
         if (g_weaponarena_weapons == WEPSET(TUBA))
             stuffcmd(this, "cl_cmd settemp chase_active 1\n");
     }
     if (!sv_foginterval && world.fog != "")
         stuffcmd(this, strcat("\nfog ", world.fog, "\nr_fog_exp2 0\nr_drawfog 1\n"));
     if (autocvar_sv_teamnagger && !(autocvar_bot_vs_human && (c3==-1 && c4==-1)))
         if (!g_ca && !g_cts && !g_race) // teamnagger is currently bad for ca, race & cts
             send_CSQC_teamnagger();
     CSQCMODEL_AUTOINIT(this);
     this.model_randomizer = random();
     if (IS_REAL_CLIENT(this))
         sv_notice_join(this);
     FOREACH_ENTITY_FLOAT(init_for_player_needed, true, {
         WITH(entity, self, it, it.init_for_player(it));
     });
     MUTATOR_CALLHOOK(ClientConnect, this);
 }
void ClientData_Attach (entity this)
Definition at line 87 of file cl_client.qc.
References clientdata, ClientData_Send(), and make_pure.
Referenced by ClientConnect().
 {
     Net_LinkEntity(this.clientdata = new(clientdata), false, 0, ClientData_Send);
     make_pure(this.clientdata);
     self.clientdata.drawonlytoclient = this;
     self.clientdata.owner = this;
 }
void ClientData_Detach (entity this)
Definition at line 95 of file cl_client.qc.
References clientdata, and NULL.
Referenced by ClientDisconnect().
 {
     remove(this.clientdata);
     self.clientdata = NULL;
 }
bool ClientData_Send (entity this, entity to, int sf)
Definition at line 59 of file cl_client.qc.
References assert, entity(), IS_SPEC, owner, WriteAngle(), and WriteByte().
Referenced by ClientData_Attach().
 {
     assert(to == this.owner, return false);
     entity e = to;
     if (IS_SPEC(e)) e = e.enemy;
     sf = 0;
     if (e.race_completed)       sf |= 1; // forced scoreboard
     if (to.spectatee_status)    sf |= 2; // spectator ent number follows
     if (e.zoomstate)            sf |= 4; // zoomed
     if (e.porto_v_angle_held)   sf |= 8; // angles held
     WriteHeader(MSG_ENTITY, ENT_CLIENT_CLIENTDATA);
     WriteByte(MSG_ENTITY, sf);
     if (sf & 2)
     {
         WriteByte(MSG_ENTITY, to.spectatee_status);
     }
     if (sf & 8)
     {
         WriteAngle(MSG_ENTITY, e.v_angle.x);
         WriteAngle(MSG_ENTITY, e.v_angle.y);
     }
     return true;
 }
void ClientData_Touch (entity e)
Definition at line 101 of file cl_client.qc.
References FOREACH_CLIENT, IS_REAL_CLIENT, IS_SPEC, and LAMBDA.
Referenced by PlayerPreThink(), race_AbandonRaceCheck(), race_SendTime(), and SetZoomState().
 {
     e.clientdata.SendFlags = 1;
     // make it spectatable
     FOREACH_CLIENT(IS_REAL_CLIENT(it) && it != e && IS_SPEC(it) && it.enemy == e, LAMBDA(it.clientdata.SendFlags = 1));
 }
void ClientDisconnect ()
Definition at line 1170 of file cl_client.qc.
References accuracy_free(), active_minigame, anticheat_report(), anticheat_shutdown(), autocvar_sv_eventlog, bot_clientdisconnect(), bot_relinkplayerlist(), chatbubbleentity, CheatShutdownClient(), ClientData_Detach(), ClientState_detach(), clientstatus, FL_CLIENT, ftos(), GameLogEcho(), GetCvars(), IS_CLIENT, IS_PLAYER, killindicator, LOG_INFO, MSG_INFO, MUTATOR_CALLHOOK, netname, netname_previous, origin, part_minigame(), personal, playerdemo_shutdown(), playerid, PlayerScore_Detach(), Portal_ClearAll(), ReadyCount(), RemoveGrapplingHook(), SELFPARAM, strcat(), strunzone(), Unfreeze(), vehicle, vehicles_exit(), W_HitPlotClose(), weaponorder_byimpulse, and world.
 {
     SELFPARAM();
     ClientState_detach(this);
     if(self.vehicle)
         vehicles_exit(VHEF_RELEASE);
     if (!IS_CLIENT(self))
     {
         LOG_INFO("Warning: ClientDisconnect without ClientConnect\n");
         return;
     }
     PlayerStats_GameReport_FinalizePlayer(self);
     if ( self.active_minigame )
         part_minigame(self);
     if(IS_PLAYER(self)) { Send_Effect(EFFECT_SPAWN_NEUTRAL, self.origin, '0 0 0', 1); }
     CheatShutdownClient();
     W_HitPlotClose(self);
     anticheat_report();
     anticheat_shutdown();
     playerdemo_shutdown();
     bot_clientdisconnect();
     entcs_detach(self);
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":part:", ftos(self.playerid)));
     Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_QUIT_DISCONNECT, self.netname);
     MUTATOR_CALLHOOK(ClientDisconnect);
     Portal_ClearAll(self);
     Unfreeze(self);
     RemoveGrapplingHook(self);
     // Here, everything has been done that requires this player to be a client.
     self.flags &= ~FL_CLIENT;
     if (self.chatbubbleentity)
         remove (self.chatbubbleentity);
     if (self.killindicator)
         remove (self.killindicator);
     WaypointSprite_PlayerGone();
     bot_relinkplayerlist();
     accuracy_free(self);
     Inventory_delete(self);
     ClientData_Detach(this);
     PlayerScore_Detach(self);
     if(self.netname_previous)
         strunzone(self.netname_previous);
     if(self.clientstatus)
         strunzone(self.clientstatus);
     if(self.weaponorder_byimpulse)
         strunzone(self.weaponorder_byimpulse);
     if(self.personal)
         remove(self.personal);
     self.playerid = 0;
     ReadyCount();
     // free cvars
     GetCvars(-1);
 }
void ClientInit_CheckUpdate ()
Definition at line 660 of file cl_client.qc.
References autocvar_g_balance_armor_blockpercent, count, SELFPARAM, and time.
Referenced by ClientInit_Spawn().
 {SELFPARAM();
     self.nextthink = time;
     if(self.count != autocvar_g_balance_armor_blockpercent)
     {
         self.count = autocvar_g_balance_armor_blockpercent;
         self.SendFlags |= 1;
     }
 }
void ClientInit_misc ()
Definition at line 637 of file cl_client.qc.
References arc_shotorigin, autocvar_g_trueaim_minrange, compressShotOrigin(), count, g_nexball_meter_period, hook_shotorigin, MSG_ONE, serverflags, sv_foginterval, world, WriteByte(), WriteCoord(), WriteInt24_t(), and WriteString().
Referenced by ClientInit_SendEntity().
 {
     int channel = MSG_ONE;
     WriteHeader(channel, ENT_CLIENT_INIT);
     WriteByte(channel, g_nexball_meter_period * 32);
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[0]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[1]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[2]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[3]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[0]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[1]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[2]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[3]));
     if(sv_foginterval && world.fog != "")
         WriteString(channel, world.fog);
     else
         WriteString(channel, "");
     WriteByte(channel, self.count * 255.0); // g_balance_armor_blockpercent
     WriteByte(channel, serverflags); // client has to know if it should zoom or not
     WriteCoord(channel, autocvar_g_trueaim_minrange);
 }
bool ClientInit_SendEntity (entity this, entity to, int sf)
Definition at line 625 of file cl_client.qc.
References ClientInit_misc(), msg_entity, MSG_ONE, MUTATOR_CALLHOOK, and Registry_send_all().
Referenced by ClientInit_Spawn().
 {
     WriteHeader(MSG_ENTITY, _ENT_CLIENT_INIT);
     return = true;
     msg_entity = to;
     // MSG_INIT replacement
     // TODO: make easier to use
     Registry_send_all();
     W_PROP_reload(MSG_ONE, to);
     ClientInit_misc();
     MUTATOR_CALLHOOK(Ent_Init);
 }
void ClientInit_Spawn ()
Definition at line 670 of file cl_client.qc.
References ClientInit_CheckUpdate(), ClientInit_SendEntity(), entity(), make_pure, SELFPARAM, and WITH.
Referenced by spawnfunc().
 {SELFPARAM();
     entity e = new(clientinit);
     make_pure(e);
     e.think = ClientInit_CheckUpdate;
     Net_LinkEntity(e, false, 0, ClientInit_SendEntity);
     WITH(entity, self, e, ClientInit_CheckUpdate());
 }
void ClientKill ()
Definition at line 915 of file cl_client.qc.
References ClientKill_TeamChange(), gameover, player_blocked, SELFPARAM, and STAT().
Referenced by ClientKill_TeamChange().
 {SELFPARAM();
     if(gameover) return;
     if(self.player_blocked) return;
     if(STAT(FROZEN, self)) return;
     ClientKill_TeamChange(0);
 }
void ClientKill_Now ()
Definition at line 751 of file cl_client.qc.
References ClientKill_Now_TeamChange(), Damage(), IS_PLAYER, killindicator, killindicator_teamchange, SELFPARAM, vehicle, vehicles_exit(), and world.
Referenced by ClientKill_TeamChange(), and KillIndicator_Think().
 {SELFPARAM();
     if(self.vehicle)
     {
         vehicles_exit(VHEF_RELEASE);
         if(!self.killindicator_teamchange)
         {
             self.vehicle_health = -1;
             Damage(self, self, self, 1 , DEATH_KILL.m_id, self.origin, '0 0 0');
         }
     }
     if(self.killindicator && !wasfreed(self.killindicator))
         remove(self.killindicator);
     self.killindicator = world;
     if(self.killindicator_teamchange)
         ClientKill_Now_TeamChange(self);
     if(IS_PLAYER(self))
         Damage(self, self, self, 100000, DEATH_KILL.m_id, self.origin, '0 0 0');
     // now I am sure the player IS dead
 }
void ClientKill_Now_TeamChange (entity this)
Definition at line 734 of file cl_client.qc.
References autocvar_g_maxplayers_spectator_blocktime, blockSpectators, entity(), JoinBestTeam(), killindicator_teamchange, MSG_INFO, PutObserverInServer(), SV_ChangeTeam(), and WITH.
Referenced by ClientKill_Now(), and PlayerDamage().
 {
     if(this.killindicator_teamchange == -1)
     {
         JoinBestTeam( this, false, true );
     }
     else if(this.killindicator_teamchange == -2)
     {
         if(blockSpectators)
             Send_Notification(NOTIF_ONE_ONLY, this, MSG_INFO, INFO_SPECTATE_WARNING, autocvar_g_maxplayers_spectator_blocktime);
         WITH(entity, self, this, PutObserverInServer());
     }
     else
         WITH(entity, self, this, SV_ChangeTeam(this.killindicator_teamchange - 1));
     this.killindicator_teamchange = 0;
 }
void ClientKill_TeamChange (float targetteam)
Definition at line 817 of file cl_client.qc.
References APP_TEAM_NUM_4, autocvar_g_balance_kill_antispam, autocvar_g_balance_kill_delay, bound(), ceil(), classname, ClientKill(), clientkill_nexttime, ClientKill_Now(), clientkilltime, entity(), find(), g_cts, g_race_qualifying, gameover, IS_DEAD, IS_PLAYER, IS_REAL_CLIENT, killindicator, KillIndicator_Think(), max(), MSG_CENTER, MUTATOR_CALLHOOK, SELFPARAM, spawn(), Team_ColorRGB(), time, and world.
Referenced by ClientCommand_clientversion(), ClientCommand_selectteam(), ClientCommand_spectate(), and ClientKill().
 {SELFPARAM();
     float killtime;
     float starttime;
     entity e;
     if (gameover)
         return;
     killtime = autocvar_g_balance_kill_delay;
     if(g_race_qualifying || g_cts)
         killtime = 0;
     if(MUTATOR_CALLHOOK(ClientKill, self, killtime))
         return;
     self.killindicator_teamchange = targetteam;
     if(!self.killindicator)
     {
         if(!IS_DEAD(self))
         {
             killtime = max(killtime, self.clientkill_nexttime - time);
             self.clientkill_nexttime = time + killtime + autocvar_g_balance_kill_antispam;
         }
         if(killtime <= 0 || !IS_PLAYER(self) || IS_DEAD(self))
         {
             ClientKill_Now();
         }
         else
         {
             starttime = max(time, clientkilltime);
             self.killindicator = spawn();
             self.killindicator.owner = self;
             self.killindicator.scale = 0.5;
             setattachment(self.killindicator, self, "");
             setorigin(self.killindicator, '0 0 52');
             self.killindicator.think = KillIndicator_Think;
             self.killindicator.nextthink = starttime + (self.lip) * 0.05;
             clientkilltime = max(clientkilltime, self.killindicator.nextthink + 0.05);
             self.killindicator.cnt = ceil(killtime);
             self.killindicator.count = bound(0, ceil(killtime), 10);
             //sprint(self, strcat("^1You'll be dead in ", ftos(self.killindicator.cnt), " seconds\n"));
             for(e = world; (e = find(e, classname, "body")) != world; )
             {
                 if(e.enemy != self)
                     continue;
                 e.killindicator = spawn();
                 e.killindicator.owner = e;
                 e.killindicator.scale = 0.5;
                 setattachment(e.killindicator, e, "");
                 setorigin(e.killindicator, '0 0 52');
                 e.killindicator.think = KillIndicator_Think;
                 e.killindicator.nextthink = starttime + (e.lip) * 0.05;
                 clientkilltime = max(clientkilltime, e.killindicator.nextthink + 0.05);
                 e.killindicator.cnt = ceil(killtime);
             }
             self.lip = 0;
         }
     }
     if(self.killindicator)
     {
         if(targetteam == 0) // just die
         {
             self.killindicator.colormod = '0 0 0';
             if(IS_REAL_CLIENT(self))
             if(self.killindicator.cnt > 0)
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_TEAMCHANGE_SUICIDE, self.killindicator.cnt);
         }
         else if(targetteam == -1) // auto
         {
             self.killindicator.colormod = '0 1 0';
             if(IS_REAL_CLIENT(self))
             if(self.killindicator.cnt > 0)
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_TEAMCHANGE_AUTO, self.killindicator.cnt);
         }
         else if(targetteam == -2) // spectate
         {
             self.killindicator.colormod = '0.5 0.5 0.5';
             if(IS_REAL_CLIENT(self))
             if(self.killindicator.cnt > 0)
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_TEAMCHANGE_SPECTATE, self.killindicator.cnt);
         }
         else
         {
             self.killindicator.colormod = Team_ColorRGB(targetteam);
             if(IS_REAL_CLIENT(self))
             if(self.killindicator.cnt > 0)
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, APP_TEAM_NUM_4(targetteam, CENTER_TEAMCHANGE_), self.killindicator.cnt);
         }
     }
 }
void DecodeLevelParms (entity this)
Definition at line 712 of file cl_client.qc.
References max(), MUTATOR_CALLHOOK, parm1, parm_idlesince, sv_maxidle, and time.
Referenced by ClientConnect().
 {
     // load parms
     this.parm_idlesince = parm1;
     if (this.parm_idlesince == -(86400 * 366))
         this.parm_idlesince = time;
     // whatever happens, allow 60 seconds of idling directly after connect for map loading
     this.parm_idlesince = max(this.parm_idlesince, time - sv_maxidle + 60);
     MUTATOR_CALLHOOK(DecodeLevelParms);
 }
void DrownPlayer (entity this)
Definition at line 2466 of file cl_client.qc.
References air_finished, autocvar_g_balance_contents_damagerate, autocvar_g_balance_contents_drowndelay, autocvar_g_balance_contents_playerdamage_drowning, CH_PLAYER, Damage(), dmg, IS_DEAD, pain_finished, time, VOICETYPE_PLAYERSOUND, waterlevel, WATERLEVEL_SUBMERGED, and world.
Referenced by PlayerPostThink().
 {
     if(IS_DEAD(this))
         return;
     if (this.waterlevel != WATERLEVEL_SUBMERGED)
     {
         if(this.air_finished < time)
             PlayerSound(this, playersound_gasp, CH_PLAYER, VOICETYPE_PLAYERSOUND);
         this.air_finished = time + autocvar_g_balance_contents_drowndelay;
         this.dmg = 2;
     }
     else if (this.air_finished < time)
     {   // drown!
         if (this.pain_finished < time)
         {
             Damage (this, world, world, autocvar_g_balance_contents_playerdamage_drowning * autocvar_g_balance_contents_damagerate, DEATH_DROWN.m_id, this.origin, '0 0 0');
             this.pain_finished = time + 0.5;
         }
     }
 }
void FixClientCvars (entity e)
Definition at line 924 of file cl_client.qc.
References autocvar_g_antilag, autocvar_sv_gentle, FixClientCvars(), and MUTATOR_CALLHOOK.
Referenced by ClientConnect(), FixClientCvars(), and MapVote_Finished().
 {
     // send prediction settings to the client
     stuffcmd(e, "\nin_bindmap 0 0\n");
     if(autocvar_g_antilag == 3) // client side hitscan
         stuffcmd(e, "cl_cmd settemp cl_prydoncursor_notrace 0\n");
     if(autocvar_sv_gentle)
         stuffcmd(e, "cl_cmd settemp cl_gentle 1\n");
     MUTATOR_CALLHOOK(FixClientCvars, e);
 }
void FixPlayermodel (entity player)
Definition at line 317 of file cl_client.qc.
References argv(), autocvar_sv_defaultcharacter, autocvar_sv_defaultplayercolors, autocvar_sv_defaultplayermodel, autocvar_sv_defaultplayerskin, CheckPlayerModel(), cvar(), cvar_string(), floor(), MUTATOR_CALLHOOK, oldskin, player_getspecies(), ret_int, ret_string, s, setplayermodel(), Static_Team_ColorName_Lower, stof(), strcat(), strlen(), strstrofs, substring(), teamplay, tokenize_console, and vector().
Referenced by PlayerPreThink(), PutClientInServer(), and PutObserverInServer().
 {
     string defaultmodel = "";
     int defaultskin = 0;
     if(autocvar_sv_defaultcharacter)
     {
         if(teamplay)
         {
             string s = Static_Team_ColorName_Lower(player.team);
             if (s != "neutral")
             {
                 defaultmodel = cvar_string(strcat("sv_defaultplayermodel_", s));
                 defaultskin = cvar(strcat("sv_defaultplayerskin_", s));
             }
         }
         if(defaultmodel == "")
         {
             defaultmodel = autocvar_sv_defaultplayermodel;
             defaultskin = autocvar_sv_defaultplayerskin;
         }
         int n = tokenize_console(defaultmodel);
         if(n > 0)
         {
             defaultmodel = argv(floor(n * player.model_randomizer));
             // However, do NOT randomize if the player-selected model is in the list.
             for (int i = 0; i < n; ++i)
                 if ((argv(i) == player.playermodel && defaultskin == stof(player.playerskin)) || argv(i) == strcat(player.playermodel, ":", player.playerskin))
                     defaultmodel = argv(i);
         }
         int i = strstrofs(defaultmodel, ":", 0);
         if(i >= 0)
         {
             defaultskin = stof(substring(defaultmodel, i+1, -1));
             defaultmodel = substring(defaultmodel, 0, i);
         }
     }
     MUTATOR_CALLHOOK(FixPlayermodel, defaultmodel, defaultskin);
     defaultmodel = ret_string;
     defaultskin = ret_int;
     bool chmdl = false;
     int oldskin;
     if(defaultmodel != "")
     {
         if (defaultmodel != player.model)
         {
             vector m1 = player.mins;
             vector m2 = player.maxs;
             setplayermodel (player, defaultmodel);
             setsize (player, m1, m2);
             chmdl = true;
         }
         oldskin = player.skin;
         player.skin = defaultskin;
     } else {
         if (player.playermodel != player.model || player.playermodel == "")
         {
             player.playermodel = CheckPlayerModel(player.playermodel); // this is never "", so no endless loop
             vector m1 = player.mins;
             vector m2 = player.maxs;
             setplayermodel (player, player.playermodel);
             setsize (player, m1, m2);
             chmdl = true;
         }
         oldskin = player.skin;
         player.skin = stof(player.playerskin);
     }
     if(chmdl || oldskin != player.skin) // model or skin has changed
     {
         player.species = player_getspecies(player); // update species
     }
     if(!teamplay)
         if(strlen(autocvar_sv_defaultplayercolors))
             if(player.clientcolors != stof(autocvar_sv_defaultplayercolors))
                 setcolor(player, stof(autocvar_sv_defaultplayercolors));
 }
void GetPressedKeys ()
Definition at line 1581 of file cl_client.qc.
References BITSET, KEY_ATCK, KEY_ATCK2, KEY_BACKWARD, KEY_CROUCH, KEY_FORWARD, KEY_JUMP, KEY_LEFT, KEY_RIGHT, movement, MUTATOR_CALLHOOK, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_CROUCH, PHYS_INPUT_BUTTON_JUMP, pressedkeys, and SELFPARAM.
Referenced by PlayerPostThink().
 {
     SELFPARAM();
     MUTATOR_CALLHOOK(GetPressedKeys);
     int keys = this.pressedkeys;
     keys = BITSET(keys, KEY_FORWARD,    this.movement.x > 0);
     keys = BITSET(keys, KEY_BACKWARD,   this.movement.x < 0);
     keys = BITSET(keys, KEY_RIGHT,      this.movement.y > 0);
     keys = BITSET(keys, KEY_LEFT,       this.movement.y < 0);
     keys = BITSET(keys, KEY_JUMP,       PHYS_INPUT_BUTTON_JUMP(this));
     keys = BITSET(keys, KEY_CROUCH,     PHYS_INPUT_BUTTON_CROUCH(this));
     keys = BITSET(keys, KEY_ATCK,       PHYS_INPUT_BUTTON_ATCK(this));
     keys = BITSET(keys, KEY_ATCK2,      PHYS_INPUT_BUTTON_ATCK2(this));
     this.pressedkeys = keys;
 }
void KillIndicator_Think ()
Definition at line 776 of file cl_client.qc.
References Announcer_PickNumber(), ClientKill_Now(), cnt, CNT_KILL, entity(), g_cts, gameover, health, IS_REAL_CLIENT, MDL_NUM(), MSG_ANNCE, owner, SELFPARAM, setmodel, time, WITH, and world.
Referenced by ClientKill_TeamChange().
 {SELFPARAM();
     if (gameover)
     {
         self.owner.killindicator = world;
         remove(self);
         return;
     }
     if (self.owner.alpha < 0 && !self.owner.vehicle)
     {
         self.owner.killindicator = world;
         remove(self);
         return;
     }
     if(self.cnt <= 0)
     {
         WITH(entity, self, self.owner, ClientKill_Now());
         return;
     }
     else if(g_cts && self.health == 1) // health == 1 means that it's silent
     {
         self.nextthink = time + 1;
         self.cnt -= 1;
     }
     else
     {
         if(self.cnt <= 10)
             setmodel(self, MDL_NUM(self.cnt));
         if(IS_REAL_CLIENT(self.owner))
         {
             if(self.cnt <= 10)
                 { Send_Notification(NOTIF_ONE, self.owner, MSG_ANNCE, Announcer_PickNumber(CNT_KILL, self.cnt)); }
         }
         self.nextthink = time + 1;
         self.cnt -= 1;
     }
 }
void LeaveSpectatorMode ()
Definition at line 1810 of file cl_client.qc.
References autocvar_g_balance_teams, autocvar_g_campaign, autocvar_g_changeteam_banned, campaign_bots_may_start, caplayer, CPID_PREVENT_JOIN, IS_PLAYER, JoinBestTeam(), MSG_CENTER, MSG_CENTER_CPID, MSG_INFO, netname, nJoinAllowed(), PutClientInServer(), SELFPARAM, STR_PLAYER, team_forced, teamplay, wasplayer, and world.
Referenced by ObserverThink(), and SpectatorThink().
 {SELFPARAM();
     if(self.caplayer)
         return;
     if(nJoinAllowed(self, self))
     {
         if(!teamplay || autocvar_g_campaign || autocvar_g_balance_teams || (self.wasplayer && autocvar_g_changeteam_banned) || self.team_forced > 0)
         {
             self.classname = STR_PLAYER;
             if(autocvar_g_campaign || autocvar_g_balance_teams)
                 { JoinBestTeam(self, false, true); }
             if(autocvar_g_campaign)
                 { campaign_bots_may_start = 1; }
             Kill_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER_CPID, CPID_PREVENT_JOIN);
             PutClientInServer();
             if(IS_PLAYER(self)) { Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_JOIN_PLAY, self.netname); }
         }
         else
             stuffcmd(self, "menu_showteamselect\n");
     }
     else
     {
         // Player may not join because g_maxplayers is set
         Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_JOIN_PREVENT);
     }
 }
bool nJoinAllowed (entity this, entity ignore)
Determines whether the player is allowed to join.
This depends on cvar g_maxplayers, if it isn't used this function always return true, otherwise it checks whether the number of currently playing players exceeds g_maxplayers.
Returns
int number of free slots for players, 0 if none
Definition at line 1848 of file cl_client.qc.
References autocvar_g_forced_team_otherwise, autocvar_g_maxplayers, FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, maxclients, min(), and team_forced.
Referenced by ClientCommand_join(), LeaveSpectatorMode(), and WinningConditionHelper().
 {
     if(!ignore)
     // this is called that way when checking if anyone may be able to join (to build qcstatus)
     // so report 0 free slots if restricted
     {
         if(autocvar_g_forced_team_otherwise == "spectate")
             return false;
         if(autocvar_g_forced_team_otherwise == "spectator")
             return false;
     }
     if(this.team_forced < 0)
         return false; // forced spectators can never join
     // TODO simplify this
     int totalClients = 0;
     int currentlyPlaying = 0;
     FOREACH_CLIENT(true, LAMBDA(
         if(it != ignore)
             ++totalClients;
         if(IS_REAL_CLIENT(it))
         if(IS_PLAYER(it) || it.caplayer)
             ++currentlyPlaying;
     ));
     if (!autocvar_g_maxplayers)
         return maxclients - totalClients;
     if(currentlyPlaying < autocvar_g_maxplayers)
         return min(maxclients - totalClients, autocvar_g_maxplayers - currentlyPlaying);
     return false;
 }
void ObserverThink ()
Definition at line 1947 of file cl_client.qc.
References BUTTON_ATCK, BUTTON_JUMP, FL_JUMPRELEASED, FL_SPAWNING, flags, impulse, LeaveSpectatorMode(), MinigameImpulse(), movetype, MOVETYPE_FLY_WORLDONLY, MOVETYPE_NOCLIP, SELFPARAM, SpectateNext(), STR_SPECTATOR, and version_mismatch.
Referenced by PlayerPreThink().
 {SELFPARAM();
     if ( self.impulse )
     {
         MinigameImpulse(self, self.impulse);
         self.impulse = 0;
     }
     float prefered_movetype;
     if (self.flags & FL_JUMPRELEASED) {
         if (self.BUTTON_JUMP && !self.version_mismatch) {
             self.flags &= ~FL_JUMPRELEASED;
             self.flags |= FL_SPAWNING;
         } else if(self.BUTTON_ATCK && !self.version_mismatch) {
             self.flags &= ~FL_JUMPRELEASED;
             if(SpectateNext()) {
                 self.classname = STR_SPECTATOR;
             }
         } else {
             prefered_movetype = ((!self.BUTTON_USE ? self.cvar_cl_clippedspectating : !self.cvar_cl_clippedspectating) ? MOVETYPE_FLY_WORLDONLY : MOVETYPE_NOCLIP);
             if (self.movetype != prefered_movetype)
                 self.movetype = prefered_movetype;
         }
     } else {
         if (!(self.BUTTON_ATCK || self.BUTTON_JUMP)) {
             self.flags |= FL_JUMPRELEASED;
             if(self.flags & FL_SPAWNING)
             {
                 self.flags &= ~FL_SPAWNING;
                 LeaveSpectatorMode();
                 return;
             }
         }
     }
 }
void play_countdown (float finished, string samp)
Definition at line 1339 of file cl_client.qc.
References _sound, ATTEN_NORM, CH_INFO, floor(), frametime, IS_REAL_CLIENT, SELFPARAM, time, and VOL_BASE.
Referenced by player_powerups().
 {SELFPARAM();
     if(IS_REAL_CLIENT(self))
         if(floor(finished - time - frametime) != floor(finished - time))
             if(finished - time < 6)
                 _sound (self, CH_INFO, samp, VOL_BASE, ATTEN_NORM);
 }
int player_getspecies (entity this)
Definition at line 307 of file cl_client.qc.
References get_model_parameters(), get_model_parameters_species, model, s, skin, SPECIES_HUMAN, and string_null.
Referenced by FixPlayermodel().
 {
     get_model_parameters(this.model, this.skin);
     int s = get_model_parameters_species;
     get_model_parameters(string_null, 0);
     if (s < 0) return SPECIES_HUMAN;
     return s;
 }
void player_powerups ()
Definition at line 1347 of file cl_client.qc.
References alpha, autocvar_g_fullbrightplayers, autocvar_g_nodepthtestplayers, EF_ADDITIVE, EF_BLUE, EF_FLAME, EF_FULLBRIGHT, EF_NODEPTHTEST, EF_RED, Fire_ApplyDamage(), Fire_ApplyEffect(), g_instagib, game_starttime, gameover, invincible_finished, IS_DEAD, IT_SUPERWEAPON, IT_UNLIMITED_SUPERWEAPONS, IT_USING_JETPACK, items, MF_ROCKET, MSG_CENTER, MSG_INFO, MUTATOR_CALLHOOK, netname, play_countdown(), SELFPARAM, SND, spawnshieldtime, strength_finished, superweapons_finished, time, weapons, WEPSET_SUPERWEAPONS, and world.
Referenced by PlayerPreThink().
 {SELFPARAM();
     // add a way to see what the items were BEFORE all of these checks for the mutator hook
     int items_prev = self.items;
     if((self.items & IT_USING_JETPACK) && !IS_DEAD(self) && !gameover)
         self.modelflags |= MF_ROCKET;
     else
         self.modelflags &= ~MF_ROCKET;
     self.effects &= ~(EF_RED | EF_BLUE | EF_ADDITIVE | EF_FULLBRIGHT | EF_FLAME | EF_NODEPTHTEST);
     if((self.alpha < 0 || IS_DEAD(self)) && !self.vehicle) // don't apply the flags if the player is gibbed
         return;
     Fire_ApplyDamage(self);
     Fire_ApplyEffect(self);
     if (!g_instagib)
     {
         if (self.items & ITEM_Strength.m_itemid)
         {
             play_countdown(self.strength_finished, SND(POWEROFF));
             self.effects = self.effects | (EF_BLUE | EF_ADDITIVE | EF_FULLBRIGHT);
             if (time > self.strength_finished)
             {
                 self.items = self.items - (self.items & ITEM_Strength.m_itemid);
                 //Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_POWERDOWN_STRENGTH, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_POWERDOWN_STRENGTH);
             }
         }
         else
         {
             if (time < self.strength_finished)
             {
                 self.items = self.items | ITEM_Strength.m_itemid;
                 Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_POWERUP_STRENGTH, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_POWERUP_STRENGTH);
             }
         }
         if (self.items & ITEM_Shield.m_itemid)
         {
             play_countdown(self.invincible_finished, SND(POWEROFF));
             self.effects = self.effects | (EF_RED | EF_ADDITIVE | EF_FULLBRIGHT);
             if (time > self.invincible_finished)
             {
                 self.items = self.items - (self.items & ITEM_Shield.m_itemid);
                 //Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_POWERDOWN_SHIELD, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_POWERDOWN_SHIELD);
             }
         }
         else
         {
             if (time < self.invincible_finished)
             {
                 self.items = self.items | ITEM_Shield.m_itemid;
                 Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_POWERUP_SHIELD, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_POWERUP_SHIELD);
             }
         }
         if (self.items & IT_SUPERWEAPON)
         {
             if (!(self.weapons & WEPSET_SUPERWEAPONS))
             {
                 self.superweapons_finished = 0;
                 self.items = self.items - (self.items & IT_SUPERWEAPON);
                 //Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_SUPERWEAPON_LOST, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_SUPERWEAPON_LOST);
             }
             else if (self.items & IT_UNLIMITED_SUPERWEAPONS)
             {
                 // don't let them run out
             }
             else
             {
                 play_countdown(self.superweapons_finished, SND(POWEROFF));
                 if (time > self.superweapons_finished)
                 {
                     self.items = self.items - (self.items & IT_SUPERWEAPON);
                     self.weapons &= ~WEPSET_SUPERWEAPONS;
                     //Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_SUPERWEAPON_BROKEN, self.netname);
                     Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_SUPERWEAPON_BROKEN);
                 }
             }
         }
         else if(self.weapons & WEPSET_SUPERWEAPONS)
         {
             if (time < self.superweapons_finished || (self.items & IT_UNLIMITED_SUPERWEAPONS))
             {
                 self.items = self.items | IT_SUPERWEAPON;
                 Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_SUPERWEAPON_PICKUP, self.netname);
                 Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_SUPERWEAPON_PICKUP);
             }
             else
             {
                 self.superweapons_finished = 0;
                 self.weapons &= ~WEPSET_SUPERWEAPONS;
             }
         }
         else
         {
             self.superweapons_finished = 0;
         }
     }
     if(autocvar_g_nodepthtestplayers)
         self.effects = self.effects | EF_NODEPTHTEST;
     if(autocvar_g_fullbrightplayers)
         self.effects = self.effects | EF_FULLBRIGHT;
     if (time >= game_starttime)
     if (time < self.spawnshieldtime)
         self.effects = self.effects | (EF_ADDITIVE | EF_FULLBRIGHT);
     MUTATOR_CALLHOOK(PlayerPowerups, self, items_prev);
 }
void player_regen ()
Definition at line 1510 of file cl_client.qc.
References ammo_fuel, armorvalue, autocvar_g_balance_armor_limit, autocvar_g_balance_armor_regen, autocvar_g_balance_armor_regenlinear, autocvar_g_balance_armor_regenstable, autocvar_g_balance_armor_rot, autocvar_g_balance_armor_rotlinear, autocvar_g_balance_armor_rotstable, autocvar_g_balance_fuel_limit, autocvar_g_balance_fuel_regen, autocvar_g_balance_fuel_regenlinear, autocvar_g_balance_fuel_regenstable, autocvar_g_balance_fuel_rot, autocvar_g_balance_fuel_rotlinear, autocvar_g_balance_fuel_rotstable, autocvar_g_balance_health_limit, autocvar_g_balance_health_regen, autocvar_g_balance_health_regenlinear, autocvar_g_balance_health_regenstable, autocvar_g_balance_health_rot, autocvar_g_balance_health_rotlinear, autocvar_g_balance_health_rotstable, CalcRotRegen(), frametime, health, IT_UNLIMITED_WEAPON_AMMO, items, MUTATOR_CALLHOOK, pauseregen_finished, pauserotarmor_finished, pauserothealth_finished, regen_health, regen_health_linear, regen_health_rot, regen_health_rotlinear, regen_health_rotstable, regen_health_stable, regen_mod_limit, regen_mod_max, regen_mod_regen, regen_mod_rot, SELFPARAM, STAT(), time, vehicle, and vehicles_exit().
Referenced by PlayerPreThink().
 {SELFPARAM();
     float max_mod, regen_mod, rot_mod, limit_mod;
     max_mod = regen_mod = rot_mod = limit_mod = 1;
     regen_mod_max = max_mod;
     regen_mod_regen = regen_mod;
     regen_mod_rot = rot_mod;
     regen_mod_limit = limit_mod;
     regen_health = autocvar_g_balance_health_regen;
     regen_health_linear = autocvar_g_balance_health_regenlinear;
     regen_health_rot = autocvar_g_balance_health_rot;
     regen_health_rotlinear = autocvar_g_balance_health_rotlinear;
     regen_health_stable = autocvar_g_balance_health_regenstable;
     regen_health_rotstable = autocvar_g_balance_health_rotstable;
     if(!MUTATOR_CALLHOOK(PlayerRegen))
     if(!STAT(FROZEN, self))
     {
         float mina, maxa, limith, limita;
         maxa = autocvar_g_balance_armor_rotstable;
         mina = autocvar_g_balance_armor_regenstable;
         limith = autocvar_g_balance_health_limit;
         limita = autocvar_g_balance_armor_limit;
         max_mod = regen_mod_max;
         regen_mod = regen_mod_regen;
         rot_mod = regen_mod_rot;
         limit_mod = regen_mod_limit;
         regen_health_rotstable = regen_health_rotstable * max_mod;
         regen_health_stable = regen_health_stable * max_mod;
         limith = limith * limit_mod;
         limita = limita * limit_mod;
         self.armorvalue = CalcRotRegen(self.armorvalue, mina, autocvar_g_balance_armor_regen, autocvar_g_balance_armor_regenlinear, regen_mod * frametime * (time > self.pauseregen_finished), maxa, autocvar_g_balance_armor_rot, autocvar_g_balance_armor_rotlinear, rot_mod * frametime * (time > self.pauserotarmor_finished), limita);
         self.health = CalcRotRegen(self.health, regen_health_stable, regen_health, regen_health_linear, regen_mod * frametime * (time > self.pauseregen_finished), regen_health_rotstable, regen_health_rot, regen_health_rotlinear, rot_mod * frametime * (time > self.pauserothealth_finished), limith);
     }
     // if player rotted to death...  die!
     // check this outside above checks, as player may still be able to rot to death
     if(self.health < 1)
     {
         if(self.vehicle)
             vehicles_exit(VHEF_RELEASE);
         if(self.event_damage)
             self.event_damage(self, self, self, 1, DEATH_ROT.m_id, self.origin, '0 0 0');
     }
     if (!(self.items & IT_UNLIMITED_WEAPON_AMMO))
     {
         float minf, maxf, limitf;
         maxf = autocvar_g_balance_fuel_rotstable;
         minf = autocvar_g_balance_fuel_regenstable;
         limitf = autocvar_g_balance_fuel_limit;
         self.ammo_fuel = CalcRotRegen(self.ammo_fuel, minf, autocvar_g_balance_fuel_regen, autocvar_g_balance_fuel_regenlinear, frametime * (time > self.pauseregen_finished) * ((self.items & ITEM_JetpackRegen.m_itemid) != 0), maxf, autocvar_g_balance_fuel_rot, autocvar_g_balance_fuel_rotlinear, frametime * (time > self.pauserotfuel_finished), limitf);
     }
 }
float PlayerInIDList (entity p, string idlist)
Definition at line 936 of file cl_client.qc.
References argv(), s, strlen(), substring(), and tokenize_console.
Referenced by ClientConnect().
 {
     float n, i;
     string s;
     // NOTE: we do NOT check crypto_idfp_signed here, an unsigned ID is fine too for this
     if (!p.crypto_idfp)
         return 0;
     // this function allows abbreviated player IDs too!
     n = tokenize_console(idlist);
     for(i = 0; i < n; ++i)
     {
         s = argv(i);
         if(s == substring(p.crypto_idfp, 0, strlen(s)))
             return 1;
     }
     return 0;
 }
void PlayerPostThink ()
Definition at line 2496 of file cl_client.qc.
References Announcer_PickNumber(), armorvalue, autocvar_g_balance_armor_blockpercent, ceil(), CheatFrame(), CheckRules_Player(), CNT_IDLE, CPID_IDLING, DrownPlayer(), frametime, GetPressedKeys(), health, healtharmor_maxdamage(), idlekick_lasttimeleft, impulse, ImpulseCommands(), intermission_running, IS_PLAYER, IS_REAL_CLIENT, min(), MSG_ANNCE, MSG_CENTER, MSG_CENTER_CPID, MSG_INFO, netname, parm_idlesince, playerdemo_write(), SELFPARAM, sv_maxidle, sv_maxidle_spectatorsareidle, time, UpdateChatBubble(), and world.
Referenced by playerdemo_read().
 {SELFPARAM();
     if(sv_maxidle > 0 && frametime) // WORKAROUND: only use dropclient in server frames (frametime set). Never use it in cl_movement frames (frametime zero).
     if(IS_REAL_CLIENT(self))
     if(IS_PLAYER(self) || sv_maxidle_spectatorsareidle)
     {
         if (time - self.parm_idlesince < 1) // instead of (time == self.parm_idlesince) to support sv_maxidle <= 10
         {
             if(self.idlekick_lasttimeleft)
             {
                 self.idlekick_lasttimeleft = 0;
                 Kill_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER_CPID, CPID_IDLING);
             }
         }
         else
         {
             float timeleft;
             timeleft = ceil(sv_maxidle - (time - self.parm_idlesince));
             if(timeleft == min(10, sv_maxidle - 1)) // - 1 to support sv_maxidle <= 10
             {
                 if(!self.idlekick_lasttimeleft)
                     Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_DISCONNECT_IDLING, timeleft);
             }
             if(timeleft <= 0)
             {
                 Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_QUIT_KICK_IDLING, self.netname);
                 dropclient(self);
                 return;
             }
             else if(timeleft <= 10)
             {
                 if(timeleft != self.idlekick_lasttimeleft)
                     { Send_Notification(NOTIF_ONE, self, MSG_ANNCE, Announcer_PickNumber(CNT_IDLE, timeleft)); }
                 self.idlekick_lasttimeleft = timeleft;
             }
         }
     }
     CheatFrame();
     //CheckPlayerJump();
     if(IS_PLAYER(self)) {
         DrownPlayer(self);
         CheckRules_Player();
         UpdateChatBubble();
         if (self.impulse)
             ImpulseCommands(self);
         if (intermission_running)
             return;     // intermission or finale
         GetPressedKeys();
     }
     /*
     float i;
     for(i = 0; i < 1000; ++i)
     {
         vector end;
         end = self.origin + '0 0 1024' + 512 * randomvec();
         tracebox(self.origin, self.mins, self.maxs, end, MOVE_NORMAL, self);
         if(trace_fraction < 1)
         if(!(trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOIMPACT))
         {
             print("I HIT SOLID: ", vtos(self.origin), " -> ", vtos(end), "\n");
             break;
         }
     }
     */
     if(self.waypointsprite_attachedforcarrier)
         WaypointSprite_UpdateHealth(self.waypointsprite_attachedforcarrier, '1 0 0' * healtharmor_maxdamage(self.health, self.armorvalue, autocvar_g_balance_armor_blockpercent, DEATH_WEAPON.m_id));
     playerdemo_write();
     CSQCMODEL_AUTOUPDATE(self);
 }
void PlayerPreThink ()
Definition at line 2097 of file cl_client.qc.
References anticheat_prethink(), autocvar_g_allow_oldvortexbeam, autocvar_g_nades_ice_health, autocvar_g_respawn_delay_max, autocvar_g_teamdamage_resetspeed, autocvar_g_xonoticversion, autocvar_leadlimit, autocvar_sv_eventlog, blockSpectators, bound(), BUTTON_ATCK2, BUTTON_USE, BUTTON_ZOOM, BUTTON_ZOOMSCRIPT, CH_VOICE, CheckRules_Player(), checkSpectatorBlock(), ClientData_Touch(), crouch, cvar_cl_newusekeysupported, cvar_g_xonoticversion, DAMAGE_NO, DEAD_DEAD, DEAD_DYING, DEAD_RESPAWNABLE, DEAD_RESPAWNING, deadflag, dmg_team, enemy, entity(), etof(), findflags(), FixPlayermodel(), FL_GODMODE, flags, frametime, frozen_by, ftos(), g_cts, g_race, g_race_qualifying, game_starttime, GameLogEcho(), gameover, health, hook, intermission_running, IntermissionThink(), IS_DEAD, IS_OBSERVER, IS_PLAYER, IS_REAL_CLIENT, IS_SPEC, isInvisibleString(), IT_FUEL, items, LOG_INFO, LOG_TRACE(), max(), max_armorvalue, monsters_setstatus(), MSG_CENTER, MSG_INFO, MUTATOR_CALLHOOK, netname, netname_previous, ObserverThink(), origin, personal, player_anim(), player_powerups(), player_regen(), playerid, PlayerUseKey(), PrintWelcomeMessage(), PS(), race_InitSpectator(), respawn(), respawn_flags, RESPAWN_FORCE, RESPAWN_SILENT, respawn_time, respawn_time_max, revive_progress, revive_speed, round_starttime, SAME_TEAM, self, SELFPARAM, SetZoomState(), ShowRespawnCountdown(), spectatee_status, SpectatorThink(), start_health, STAT(), stat_respawn_time, strcat(), strstr, strunzone(), strzone(), taunt_soundtime, teamkill_soundtime, time, TIMEOUT_ACTIVE, timeout_status, trace_startsolid, Unfreeze(), usekeypressed, vehicle, vehicles_exit(), vercmp(), version_nagtime, VHF_ISVEHICLE, VHF_MULTISLOT, vlen(), VOICETYPE_AUTOTAUNT, VOICETYPE_LASTATTACKER_ONLY, vortex_charge, vortex_charge_rottime, W_TICSPERFRAME, W_WeaponFrame(), weapon_nextthink, weaponentities, weaponsInMap, WEP_CVAR, wframe, and world.
Referenced by playerdemo_read().
 {SELFPARAM();
     WarpZone_PlayerPhysics_FixVAngle();
     self.stat_game_starttime = game_starttime;
     self.stat_round_starttime = round_starttime;
     self.stat_allow_oldvortexbeam = autocvar_g_allow_oldvortexbeam;
     self.stat_leadlimit = autocvar_leadlimit;
     self.weaponsinmap = weaponsInMap;
     if(frametime)
     {
         // physics frames: update anticheat stuff
         anticheat_prethink();
     }
     if(blockSpectators && frametime)
         // WORKAROUND: only use dropclient in server frames (frametime set). Never use it in cl_movement frames (frametime zero).
         checkSpectatorBlock();
     zoomstate_set = 0;
     // Savage: Check for nameless players
     if (isInvisibleString(self.netname)) {
         string new_name = strzone(strcat("Player@", ftos(self.playerid)));
         if(autocvar_sv_eventlog)
             GameLogEcho(strcat(":name:", ftos(self.playerid), ":", new_name));
         if(self.netname_previous)
             strunzone(self.netname_previous);
         self.netname_previous = strzone(new_name);
         self.netname = self.netname_previous;
         // stuffcmd(self, strcat("name ", self.netname, "\n"));
     } else if(self.netname_previous != self.netname) {
         if(autocvar_sv_eventlog)
             GameLogEcho(strcat(":name:", ftos(self.playerid), ":", self.netname));
         if(self.netname_previous)
             strunzone(self.netname_previous);
         self.netname_previous = strzone(self.netname);
     }
     // version nagging
     if(self.version_nagtime)
         if(self.cvar_g_xonoticversion)
             if(time > self.version_nagtime)
             {
                 // don't notify git users
                 if(strstr(self.cvar_g_xonoticversion, "git", 0) < 0 && strstr(self.cvar_g_xonoticversion, "autobuild", 0) < 0)
                 {
                     if(strstr(autocvar_g_xonoticversion, "git", 0) >= 0 || strstr(autocvar_g_xonoticversion, "autobuild", 0) >= 0)
                     {
                         // notify release users if connecting to git
                         LOG_TRACE("^1NOTE^7 to ", self.netname, "^7 - the server is running ^3Xonotic ", autocvar_g_xonoticversion, " (beta)^7, you have ^3Xonotic ", self.cvar_g_xonoticversion, "^1\n");
                         Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_VERSION_BETA, autocvar_g_xonoticversion, self.cvar_g_xonoticversion);
                     }
                     else
                     {
                         float r;
                         r = vercmp(self.cvar_g_xonoticversion, autocvar_g_xonoticversion);
                         if(r < 0)
{
                             // give users new version
                             LOG_TRACE("^1NOTE^7 to ", self.netname, "^7 - ^3Xonotic ", autocvar_g_xonoticversion, "^7 is out, and you still have ^3Xonotic ", self.cvar_g_xonoticversion, "^1 - get the update from ^4http://www.xonotic.org/^1!\n");
                             Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_VERSION_OUTDATED, autocvar_g_xonoticversion, self.cvar_g_xonoticversion);
                         }
                         else if(r > 0)
{
                             // notify users about old server version
                             LOG_INFO("^1NOTE^7 to ", self.netname, "^7 - the server is running ^3Xonotic ", autocvar_g_xonoticversion, "^7, you have ^3Xonotic ", self.cvar_g_xonoticversion, "^1\n");
                             Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_VERSION_OLD, autocvar_g_xonoticversion, self.cvar_g_xonoticversion);
                         }
                     }
                 }
                 self.version_nagtime = 0;
             }
     // GOD MODE info
     if(!(self.flags & FL_GODMODE)) if(self.max_armorvalue)
     {
         Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_GODMODE_OFF, self.max_armorvalue);
         self.max_armorvalue = 0;
     }
     if(STAT(FROZEN, self) == 2)
     {
         self.revive_progress = bound(0, self.revive_progress + frametime * self.revive_speed, 1);
         self.health = max(1, self.revive_progress * start_health);
         self.iceblock.alpha = bound(0.2, 1 - self.revive_progress, 1);
         if(self.revive_progress >= 1)
             Unfreeze(self);
     }
     else if(STAT(FROZEN, self) == 3)
     {
         self.revive_progress = bound(0, self.revive_progress - frametime * self.revive_speed, 1);
         self.health = max(0, autocvar_g_nades_ice_health + (start_health-autocvar_g_nades_ice_health) * self.revive_progress );
         if(self.health < 1)
         {
             if(self.vehicle)
                 vehicles_exit(VHEF_RELEASE);
             self.event_damage(self, self, self.frozen_by, 1, DEATH_NADE_ICE_FREEZE.m_id, self.origin, '0 0 0');
         }
         else if ( self.revive_progress <= 0 )
             Unfreeze(self);
     }
     MUTATOR_CALLHOOK(PlayerPreThink);
     if(autocvar_g_vehicles_enter)
     if(time > self.last_vehiclecheck)
     if(IS_PLAYER(self))
     if(!gameover)
     if(!STAT(FROZEN, self))
     if(!self.vehicle)
     if(!IS_DEAD(self))
     {
         entity veh;
         for(veh = world; (veh = findflags(veh, vehicle_flags, VHF_ISVEHICLE)); )
         if(vlen(veh.origin - self.origin) < autocvar_g_vehicles_enter_radius)
         if(!IS_DEAD(veh))
         if(veh.takedamage != DAMAGE_NO)
         if((veh.vehicle_flags & VHF_MULTISLOT) && SAME_TEAM(veh.owner, self))
             Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_VEHICLE_ENTER_GUNNER);
         else if(!veh.owner)
         if(!veh.team || SAME_TEAM(self, veh))
             Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_VEHICLE_ENTER);
         else if(autocvar_g_vehicles_steal)
             Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_VEHICLE_ENTER_STEAL);
         self.last_vehiclecheck = time + 1;
     }
     if(!self.cvar_cl_newusekeysupported) // FIXME remove this - it was a stupid idea to begin with, we can JUST use the button
     {
         if(self.BUTTON_USE && !self.usekeypressed)
             PlayerUseKey();
         self.usekeypressed = self.BUTTON_USE;
     }
     if(IS_REAL_CLIENT(self))
         PrintWelcomeMessage();
     if(IS_PLAYER(self))
     {
         CheckRules_Player();
         if (intermission_running)
         {
             IntermissionThink ();   // otherwise a button could be missed between
             return;                 // the think tics
         }
         //don't allow the player to turn around while game is paused!
         if(timeout_status == TIMEOUT_ACTIVE) {
             // FIXME turn this into CSQC stuff
             self.v_angle = self.lastV_angle;
             self.angles = self.lastV_angle;
             self.fixangle = true;
         }
         if(frametime)
         {
             player_powerups();
         }
         if (IS_DEAD(self))
         {
             if(self.personal && g_race_qualifying)
             {
                 if(time > self.respawn_time)
                 {
                     self.respawn_time = time + 1; // only retry once a second
                     self.stat_respawn_time = self.respawn_time;
                     respawn();
                     self.impulse = 141;
                 }
             }
             else
             {
                 float button_pressed;
                 if(frametime)
                     player_anim();
                 button_pressed = (self.BUTTON_ATCK || self.BUTTON_JUMP || self.BUTTON_ATCK2 || self.BUTTON_HOOK || self.BUTTON_USE);
                 if (self.deadflag == DEAD_DYING)
                 {
                     if((self.respawn_flags & RESPAWN_FORCE) && !autocvar_g_respawn_delay_max)
                         self.deadflag = DEAD_RESPAWNING;
                     else if(!button_pressed)
                         self.deadflag = DEAD_DEAD;
                 }
                 else if (self.deadflag == DEAD_DEAD)
                 {
                     if(button_pressed)
                         self.deadflag = DEAD_RESPAWNABLE;
                     else if(time >= self.respawn_time_max && (self.respawn_flags & RESPAWN_FORCE))
                         self.deadflag = DEAD_RESPAWNING;
                 }
                 else if (self.deadflag == DEAD_RESPAWNABLE)
                 {
                     if(!button_pressed)
                         self.deadflag = DEAD_RESPAWNING;
                 }
                 else if (self.deadflag == DEAD_RESPAWNING)
                 {
                     if(time > self.respawn_time)
                     {
                         self.respawn_time = time + 1; // only retry once a second
                         self.respawn_time_max = self.respawn_time;
                         respawn();
                     }
                 }
                 ShowRespawnCountdown();
                 if(self.respawn_flags & RESPAWN_SILENT)
                     self.stat_respawn_time = 0;
                 else if((self.respawn_flags & RESPAWN_FORCE) && autocvar_g_respawn_delay_max)
                     self.stat_respawn_time = self.respawn_time_max;
                 else
                     self.stat_respawn_time = self.respawn_time;
             }
             // if respawning, invert stat_respawn_time to indicate this, the client translates it
             if(self.deadflag == DEAD_RESPAWNING && self.stat_respawn_time > 0)
                 self.stat_respawn_time *= -1;
             return;
         }
         self.prevorigin = self.origin;
         float do_crouch = self.BUTTON_CROUCH;
         if(self.hook.state)
             do_crouch = 0;
         if(self.vehicle)
             do_crouch = 0;
         if(STAT(FROZEN, self))
             do_crouch = 0;
         // WEAPONTODO: THIS SHIT NEEDS TO GO EVENTUALLY
         // It cannot be predicted by the engine!
         .entity weaponentity = weaponentities[0]; // TODO: unhardcode
         if((PS(self).m_weapon == WEP_SHOCKWAVE || PS(self).m_weapon == WEP_SHOTGUN) && self.(weaponentity).wframe == WFRAME_FIRE2 && time < self.(weaponentity).weapon_nextthink)
             do_crouch = 0;
         if (do_crouch)
         {
             if (!self.crouch)
             {
                 self.crouch = true;
                 self.view_ofs = STAT(PL_CROUCH_VIEW_OFS, self);
                 setsize (self, STAT(PL_CROUCH_MIN, self), STAT(PL_CROUCH_MAX, self));
                 // setanim(self, self.anim_duck, false, true, true); // this anim is BROKEN anyway
             }
         }
         else
         {
             if (self.crouch)
             {
                 tracebox(self.origin, STAT(PL_MIN, self), STAT(PL_MAX, self), self.origin, false, self);
                 if (!trace_startsolid)
                 {
                     self.crouch = false;
                     self.view_ofs = STAT(PL_VIEW_OFS, self);
                     setsize (self, STAT(PL_MIN, self), STAT(PL_MAX, self));
                 }
             }
         }
         FixPlayermodel(self);
         // LordHavoc: allow firing on move frames (sub-ticrate), this gives better timing on slow servers
         //if(frametime)
         {
             self.items &= ~self.items_added;
             W_WeaponFrame(self);
             self.items_added = 0;
             if(self.items & ITEM_Jetpack.m_itemid)
                 if(self.items & ITEM_JetpackRegen.m_itemid || self.ammo_fuel >= 0.01)
                     self.items_added |= IT_FUEL;
             self.items |= self.items_added;
         }
         player_regen();
         // WEAPONTODO: Add a weapon request for this
         // rot vortex charge to the charge limit
         if(WEP_CVAR(vortex, charge_rot_rate) && self.vortex_charge > WEP_CVAR(vortex, charge_limit) && self.vortex_charge_rottime < time)
             self.vortex_charge = bound(WEP_CVAR(vortex, charge_limit), self.vortex_charge - WEP_CVAR(vortex, charge_rot_rate) * frametime / W_TICSPERFRAME, 1);
         if(frametime)
             player_anim();
         // secret status
         secrets_setstatus();
         // monsters status
         monsters_setstatus(self);
         self.dmg_team = max(0, self.dmg_team - autocvar_g_teamdamage_resetspeed * frametime);
         //self.angles_y=self.v_angle_y + 90;   // temp
     } else if(gameover) {
         if (intermission_running)
             IntermissionThink ();   // otherwise a button could be missed between
         return;
     } else if(IS_OBSERVER(self)) {
         ObserverThink();
     } else if(IS_SPEC(self)) {
         SpectatorThink();
     }
     // WEAPONTODO: Add weapon request for this
     if(!zoomstate_set)
         SetZoomState(
             self.BUTTON_ZOOM
             || self.BUTTON_ZOOMSCRIPT
             || (self.BUTTON_ATCK2 && PS(self).m_weapon == WEP_VORTEX)
             || (self.BUTTON_ATCK2 && PS(self).m_weapon == WEP_RIFLE && WEP_CVAR(rifle, secondary) == 0)
         ); // WEAPONTODO
     float oldspectatee_status;
     oldspectatee_status = self.spectatee_status;
     if(IS_SPEC(self))
         self.spectatee_status = etof(self.enemy);
     else if(IS_OBSERVER(self))
         self.spectatee_status = etof(self);
     else
         self.spectatee_status = 0;
     if(self.spectatee_status != oldspectatee_status)
     {
         ClientData_Touch(self);
         if(g_race || g_cts)
             race_InitSpectator();
     }
     if(self.teamkill_soundtime)
     if(time > self.teamkill_soundtime)
     {
         self.teamkill_soundtime = 0;
         entity e = self.teamkill_soundsource;
         entity oldpusher = e.pusher;
         e.pusher = this;
         PlayerSound(e, playersound_teamshoot, CH_VOICE, VOICETYPE_LASTATTACKER_ONLY);
         e.pusher = oldpusher;
     }
     if(self.taunt_soundtime)
     if(time > self.taunt_soundtime)
     {
         self.taunt_soundtime = 0;
         PlayerSound(self, playersound_taunt, CH_VOICE, VOICETYPE_AUTOTAUNT);
     }
     target_voicescript_next(self);
     // WEAPONTODO: Move into weaponsystem somehow
     // if a player goes unarmed after holding a loaded weapon, empty his clip size and remove the crosshair ammo ring
     if (PS(self).m_weapon == WEP_Null)
         self.clip_load = self.clip_size = 0;
 }
void PlayerUseKey ()
Definition at line 2037 of file cl_client.qc.
References DAMAGE_NO, entity(), gameover, IS_DEAD, IS_PLAYER, MUTATOR_CALLHOOK, origin, PlayerUseKey(), SAME_TEAM, SELFPARAM, STAT(), vehicle, vehicles_enter(), vehicles_exit(), VHF_ISVEHICLE, VHF_MULTISLOT, vlen(), WarpZone_FindRadius(), and world.
Referenced by IMPULSE(), PlayerPreThink(), and PlayerUseKey().
 {SELFPARAM();
     if (!IS_PLAYER(self))
         return;
     if(self.vehicle)
     {
         if(!gameover)
         {
             vehicles_exit(VHEF_NORMAL);
             return;
         }
     }
     else if(autocvar_g_vehicles_enter)
     {
         if(!STAT(FROZEN, self))
         if(!IS_DEAD(self))
         if(!gameover)
         {
             entity head, closest_target = world;
             head = WarpZone_FindRadius(self.origin, autocvar_g_vehicles_enter_radius, true);
             while(head) // find the closest acceptable target to enter
             {
                 if(head.vehicle_flags & VHF_ISVEHICLE)
                 if(!IS_DEAD(head))
                 if(!head.owner || ((head.vehicle_flags & VHF_MULTISLOT) && SAME_TEAM(head.owner, self)))
                 if(head.takedamage != DAMAGE_NO)
                 {
                     if(closest_target)
                     {
                         if(vlen(self.origin - head.origin) < vlen(self.origin - closest_target.origin))
                         { closest_target = head; }
                     }
                     else { closest_target = head; }
                 }
                 head = head.chain;
             }
             if(closest_target) { vehicles_enter(self, closest_target); return; }
         }
     }
     // a use key was pressed; call handlers
     MUTATOR_CALLHOOK(PlayerUseKey);
 }
void PrintWelcomeMessage ()
Definition at line 1900 of file cl_client.qc.
References autocvar_g_campaign, BUTTON_INFO, campaign_message, CPID_MOTD, getwelcomemessage(), IS_PLAYER, IS_SPEC, motd_actived_time, MSG_CENTER, MSG_CENTER_CPID, SELFPARAM, and time.
Referenced by PlayerPreThink().
 {SELFPARAM();
     if(self.motd_actived_time == 0)
     {
         if (autocvar_g_campaign) {
             if ((IS_PLAYER(self) && self.BUTTON_INFO) || (!IS_PLAYER(self))) {
                 self.motd_actived_time = time;
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_MOTD, campaign_message);
             }
         } else {
             if (self.BUTTON_INFO) {
                 self.motd_actived_time = time;
                 Send_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER, CENTER_MOTD, getwelcomemessage());
             }
         }
     }
     else if(self.motd_actived_time > 0) // showing MOTD or campaign message
     {
         if (autocvar_g_campaign) {
             if (self.BUTTON_INFO)
                 self.motd_actived_time = time;
             else if ((time - self.motd_actived_time > 2) && IS_PLAYER(self)) { // hide it some seconds after BUTTON_INFO has been released
                 self.motd_actived_time = 0;
                 Kill_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER_CPID, CPID_MOTD);
             }
         } else {
             if (self.BUTTON_INFO)
                 self.motd_actived_time = time;
             else if (time - self.motd_actived_time > 2) { // hide it some seconds after BUTTON_INFO has been released
                 self.motd_actived_time = 0;
                 Kill_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER_CPID, CPID_MOTD);
             }
         }
     }
     else //if(self.motd_actived_time < 0) // just connected, motd is active
     {
         if(self.BUTTON_INFO) // BUTTON_INFO hides initial MOTD
             self.motd_actived_time = -2; // wait until BUTTON_INFO gets released
         else if(self.motd_actived_time == -2 || IS_PLAYER(self) || IS_SPEC(self))
         {
             // instanctly hide MOTD
             self.motd_actived_time = 0;
             Kill_Notification(NOTIF_ONE_ONLY, self, MSG_CENTER_CPID, CPID_MOTD);
         }
     }
 }
void PutClientInServer ()
Called when a client spawns in the server.
Definition at line 403 of file cl_client.qc.
References accuracy_resend(), activator, air_finished, alivetime, alpha, ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, ammo_shells, angles, antilag_clear(), armorvalue, autocvar__notarget, autocvar_g_balance_pause_armor_rot_spawn, autocvar_g_balance_pause_fuel_rot_spawn, autocvar_g_balance_pause_health_regen_spawn, autocvar_g_balance_pause_health_rot_spawn, autocvar_g_balance_superweapons_time, autocvar_g_ballistics_density_player, autocvar_g_botclip_collisions, autocvar_g_player_brightness, autocvar_g_playerclip_collisions, autocvar_g_spawnshieldtime, autocvar_spawn_debug, autocvar_sv_player_scale, autocvar_sv_ready_restart_after_countdown, avelocity, ballistics_density, bot_attack, BUTTON_ATCK, BUTTON_ATCK2, BUTTON_JUMP, CH_PLAYER_SINGLE, CL_SpawnWeaponentity(), classname, cnt, colormod, crouch, DAMAGE_AIM, damagedbycontents, damageforcescale, DEAD_NO, deadflag, death_time, default_player_alpha, default_weapon_alpha, dmg, dmg_team, DPCONTENTS_BODY, DPCONTENTS_BOTCLIP, DPCONTENTS_PLAYERCLIP, DPCONTENTS_SOLID, dphitcontentsmask, drawonlytoclient, EF_RESTARTANIM_BIT, EF_TELEPORT_BIT, effects, entity(), exteriorweaponentity, fade_time, fire_endtime, fixangle, FixPlayermodel(), FL_CLIENT, FL_NOTARGET, FL_PICKUPITEMS, flags, FOREACH, frags, FRAGS_PLAYER, FRAGS_SPECTATOR, func_null(), game_starttime, gameover, health, hud, HUD_NORMAL, INDEPENDENT_PLAYERS, invincible_finished, IS_BOT_CLIENT, IS_OBSERVER, IS_PLAYER, IS_REAL_CLIENT, iscreature, itemkeys, items, JoinBestTeam(), killcount, LAMBDA, lastteleporttime, MAKE_INDEPENDENT_PLAYER, make_pure, MAX_WEAPONSLOTS, model, monster_attack, movetype, MOVETYPE_WALK, MSG_CENTER, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, nextthink, NULL, oldorigin, oldvelocity, origin, pain_finished, pain_frame, pauseregen_finished, pauserotarmor_finished, pauserotfuel_finished, pauserothealth_finished, PlayerDamage(), PlayerScore_Clear(), PlayerState_attach(), prevorigin, PS(), punchangle, punchvector, pushltime, PutObserverInServer(), respawn_flags, respawn_time, revival_time, s, scale, SelectSpawnPoint(), SELFPARAM, SetSpectatee(), solid, SOLID_SLIDEBOX, SpawnEvent_Send(), spawnorigin, spawnshieldtime, speedrunning, sprint(), start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, start_weapons, STAT(), stat_respawn_time, stopsound(), STR_OBSERVER, STR_PLAYER, strcat(), strength_finished, string_null, SUB_UseTargets(), superweapons_finished, SVC_SETVIEW, takedamage, team, TELEPORT_NORMAL, teleportable, time, Unfreeze(), v_angle, velocity, view_ofs, vtos(), w_getbestweapon, warmup_stage, warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, warmup_start_health, WARMUP_START_WEAPONS, wasplayer, weapon_load, weaponentities, weaponname, weapons, WEP_FLAG_RELOADABLE, WEPSET_SUPERWEAPONS, WITH, WriteByte(), and WriteEntity().
Referenced by bot_spawn(), ClientCommand_join(), LeaveSpectatorMode(), respawn(), and SpectatorThink().
 {
     SELFPARAM();
     if (IS_BOT_CLIENT(this)) {
         this.classname = STR_PLAYER;
     } else if (IS_REAL_CLIENT(this)) {
         msg_entity = this;
         WriteByte(MSG_ONE, SVC_SETVIEW);
         WriteEntity(MSG_ONE, this);
     }
     if (gameover) {
         this.classname = STR_OBSERVER;
     }
     SetSpectatee(this, NULL);
     // reset player keys
     this.itemkeys = 0;
     MUTATOR_CALLHOOK(PutClientInServer, this);
     if (IS_OBSERVER(this)) {
         PutObserverInServer();
     } else if (IS_PLAYER(this)) {
         PlayerState_attach(this);
         accuracy_resend(this);
         if (this.team < 0)
             JoinBestTeam(this, false, true);
         entity spot = SelectSpawnPoint(false);
         if (!spot) {
             Send_Notification(NOTIF_ONE_ONLY, this, MSG_CENTER, CENTER_JOIN_NOSPAWNS);
             return; // spawn failed
         }
         this.classname = STR_PLAYER;
         this.wasplayer = true;
         this.iscreature = true;
         this.teleportable = TELEPORT_NORMAL;
         this.damagedbycontents = true;
         this.movetype = MOVETYPE_WALK;
         this.solid = SOLID_SLIDEBOX;
         this.dphitcontentsmask = DPCONTENTS_BODY | DPCONTENTS_SOLID;
         if (autocvar_g_playerclip_collisions)
             this.dphitcontentsmask |= DPCONTENTS_PLAYERCLIP;
         if (IS_BOT_CLIENT(this) && autocvar_g_botclip_collisions)
             this.dphitcontentsmask |= DPCONTENTS_BOTCLIP;
         this.frags = FRAGS_PLAYER;
         if (INDEPENDENT_PLAYERS) MAKE_INDEPENDENT_PLAYER(this);
         this.flags = FL_CLIENT | FL_PICKUPITEMS;
         if (autocvar__notarget)
             this.flags |= FL_NOTARGET;
         this.takedamage = DAMAGE_AIM;
         this.effects = EF_TELEPORT_BIT | EF_RESTARTANIM_BIT;
         this.dmg = 2; // WTF
         if (warmup_stage) {
             this.ammo_shells = warmup_start_ammo_shells;
             this.ammo_nails = warmup_start_ammo_nails;
             this.ammo_rockets = warmup_start_ammo_rockets;
             this.ammo_cells = warmup_start_ammo_cells;
             this.ammo_plasma = warmup_start_ammo_plasma;
             this.ammo_fuel = warmup_start_ammo_fuel;
             this.health = warmup_start_health;
             this.armorvalue = warmup_start_armorvalue;
             this.weapons = WARMUP_START_WEAPONS;
         } else {
             this.ammo_shells = start_ammo_shells;
             this.ammo_nails = start_ammo_nails;
             this.ammo_rockets = start_ammo_rockets;
             this.ammo_cells = start_ammo_cells;
             this.ammo_plasma = start_ammo_plasma;
             this.ammo_fuel = start_ammo_fuel;
             this.health = start_health;
             this.armorvalue = start_armorvalue;
             this.weapons = start_weapons;
         }
         this.superweapons_finished = (this.weapons & WEPSET_SUPERWEAPONS) ? time + autocvar_g_balance_superweapons_time : 0;
         this.items = start_items;
         this.spawnshieldtime = time + autocvar_g_spawnshieldtime;
         this.pauserotarmor_finished = time + autocvar_g_balance_pause_armor_rot_spawn;
         this.pauserothealth_finished = time + autocvar_g_balance_pause_health_rot_spawn;
         this.pauserotfuel_finished = time + autocvar_g_balance_pause_fuel_rot_spawn;
         this.pauseregen_finished = time + autocvar_g_balance_pause_health_regen_spawn;
         // extend the pause of rotting if client was reset at the beginning of the countdown
         if (!autocvar_sv_ready_restart_after_countdown && time < game_starttime) { // TODO why is this cvar NOTted?
             float f = game_starttime - time;
             this.spawnshieldtime += f;
             this.pauserotarmor_finished += f;
             this.pauserothealth_finished += f;
             this.pauseregen_finished += f;
         }
         this.damageforcescale = 2;
         this.death_time = 0;
         this.respawn_flags = 0;
         this.respawn_time = 0;
         this.stat_respawn_time = 0;
         this.scale = autocvar_sv_player_scale;
         this.fade_time = 0;
         this.pain_frame = 0;
         this.pain_finished = 0;
         this.pushltime = 0;
         this.think = func_null; // players have no think function
         this.nextthink = 0;
         this.dmg_team = 0;
         this.ballistics_density = autocvar_g_ballistics_density_player;
         this.deadflag = DEAD_NO;
         this.angles = spot.angles;
         this.angles_z = 0; // never spawn tilted even if the spot says to
         if (IS_BOT_CLIENT(this))
             this.v_angle = this.angles;
         this.fixangle = true; // turn this way immediately
         this.oldvelocity = this.velocity = '0 0 0';
         this.avelocity = '0 0 0';
         this.punchangle = '0 0 0';
         this.punchvector = '0 0 0';
         this.strength_finished = 0;
         this.invincible_finished = 0;
         this.fire_endtime = -1;
         this.revival_time = 0;
         this.air_finished = time + 12;
         entity spawnevent = new(spawnevent);
         make_pure(spawnevent);
         spawnevent.owner = this;
         Net_LinkEntity(spawnevent, false, 0.5, SpawnEvent_Send);
         // Cut off any still running player sounds.
         stopsound(this, CH_PLAYER_SINGLE);
         this.model = "";
         FixPlayermodel(this);
         this.drawonlytoclient = NULL;
         this.crouch = false;
         this.view_ofs = STAT(PL_VIEW_OFS, NULL);
         setsize(this, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL));
         this.spawnorigin = spot.origin;
         setorigin(this, spot.origin + '0 0 1' * (1 - this.mins.z - 24));
         // don't reset back to last position, even if new position is stuck in solid
         this.oldorigin = this.origin;
         this.prevorigin = this.origin;
         this.lastteleporttime = time; // prevent insane speeds due to changing origin
         this.hud = HUD_NORMAL;
         this.event_damage = PlayerDamage;
         this.bot_attack = true;
         this.monster_attack = true;
         this.BUTTON_ATCK = this.BUTTON_JUMP = this.BUTTON_ATCK2 = false;
         if (this.killcount == FRAGS_SPECTATOR) {
             PlayerScore_Clear(this);
             this.killcount = 0;
         }
         for (int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             CL_SpawnWeaponentity(this, weaponentities[slot]);
         }
         this.alpha = default_player_alpha;
         this.colormod = '1 1 1' * autocvar_g_player_brightness;
         this.exteriorweaponentity.alpha = default_weapon_alpha;
         this.speedrunning = false;
         target_voicescript_clear(this);
         // reset fields the weapons may use
         FOREACH(Weapons, true, LAMBDA(
             it.wr_resetplayer(it);
             // reload all reloadable weapons
             if (it.spawnflags & WEP_FLAG_RELOADABLE) {
                 this.weapon_load[it.m_id] = it.reloading_ammo;
             }
         ));
         {
             string s = spot.target;
             spot.target = string_null;
             WITH(entity, activator, this, LAMBDA(
                 WITH(entity, self, spot, SUB_UseTargets())
             ));
             spot.target = s;
         }
         Unfreeze(this);
         MUTATOR_CALLHOOK(PlayerSpawn, spot);
         if (autocvar_spawn_debug)
         {
             sprint(this, strcat("spawnpoint origin:  ", vtos(spot.origin), "\n"));
             remove(spot); // usefull for checking if there are spawnpoints, that let drop through the floor
         }
         PS(this).m_switchweapon = w_getbestweapon(this);
         this.cnt = -1; // W_LastWeapon will not complain
         PS(this).m_weapon = WEP_Null;
         this.weaponname = "";
         PS(this).m_switchingweapon = WEP_Null;
         if (!warmup_stage && !this.alivetime)
             this.alivetime = time;
         antilag_clear(this);
     }
 }
void PutObserverInServer ()
Definition at line 172 of file cl_client.qc.
References accuracy_resend(), alivetime, autocvar_g_balance_armor_start, autocvar_g_chat_nospectators, DAMAGE_NO, DEAD_NO, entity(), error(), FixPlayermodel(), FL_CLIENT, FL_NOTARGET, FRAGS_SPECTATOR, func_null(), gameover, HUD_NORMAL, intermission_running, IS_PLAYER, IS_REAL_CLIENT, just_joined, killcount, LogTeamchange(), MAX_WEAPONSLOTS, MOVETYPE_FLY_WORLDONLY, msg_entity, MSG_INFO, MSG_ONE, MUTATOR_CALLHOOK, netname, NULL, origin, playerid, PlayerScore_Clear(), PlayerState_detach(), Portal_ClearAll(), PS(), RemoveGrapplingHook(), SelectSpawnPoint(), SELFPARAM, setmodel, SOLID_NOT, STAT(), STR_OBSERVER, SVC_SETVIEW, TELEPORT_SIMPLE, time, Unfreeze(), vehicle, vehicles_exit(), warmup_stage, world, WriteByte(), and WriteEntity().
Referenced by ClientKill_Now_TeamChange(), GameCommand_allspec(), GameCommand_moveplayer(), minigame_addplayer(), PutClientInServer(), SpectateSet(), and SpectatorThink().
 {
     SELFPARAM();
     PlayerState_detach(this);
     entity  spot;
     self.hud = HUD_NORMAL;
     if(IS_PLAYER(self)) { Send_Effect(EFFECT_SPAWN_NEUTRAL, self.origin, '0 0 0', 1); }
     spot = SelectSpawnPoint (true);
     if(!spot)
         error("No spawnpoints for observers?!?\n");
     RemoveGrapplingHook(self); // Wazat's Grappling Hook
     if(IS_REAL_CLIENT(self))
     {
         msg_entity = self;
         WriteByte(MSG_ONE, SVC_SETVIEW);
         WriteEntity(MSG_ONE, self);
     }
     self.frags = FRAGS_SPECTATOR;
     self.bot_attack = false;
     bool mutator_returnvalue = MUTATOR_CALLHOOK(MakePlayerObserver);
     Portal_ClearAll(self);
     Unfreeze(self);
     if(self.alivetime)
     {
         if(!warmup_stage)
             PS_GR_P_ADDVAL(self, PLAYERSTATS_ALIVETIME, time - self.alivetime);
         self.alivetime = 0;
     }
     if(self.vehicle)
         vehicles_exit(VHEF_RELEASE);
     WaypointSprite_PlayerDead(self);
     if(!mutator_returnvalue)  // mutator prevents resetting teams
         self.team = -1;  // move this as it is needed to log the player spectating in eventlog
     if(self.killcount != FRAGS_SPECTATOR)
     {
         Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_QUIT_SPECTATE, self.netname);
         if(!intermission_running)
         if(autocvar_g_chat_nospectators == 1 || (!(warmup_stage || gameover) && autocvar_g_chat_nospectators == 2))
             Send_Notification(NOTIF_ONE_ONLY, self, MSG_INFO, INFO_CHAT_NOSPECTATORS);
         if(self.just_joined == false) {
             LogTeamchange(self.playerid, -1, 4);
         } else
             self.just_joined = false;
     }
     PlayerScore_Clear(self); // clear scores when needed
     accuracy_resend(self);
     self.spectatortime = time;
     self.classname = STR_OBSERVER;
     self.iscreature = false;
     self.teleportable = TELEPORT_SIMPLE;
     self.damagedbycontents = false;
     self.health = FRAGS_SPECTATOR;
     self.takedamage = DAMAGE_NO;
     self.solid = SOLID_NOT;
     self.movetype = MOVETYPE_FLY_WORLDONLY; // user preference is controlled by playerprethink
     self.flags = FL_CLIENT | FL_NOTARGET;
     self.armorvalue = 666;
     self.effects = 0;
     self.armorvalue = autocvar_g_balance_armor_start;
     self.pauserotarmor_finished = 0;
     self.pauserothealth_finished = 0;
     self.pauseregen_finished = 0;
     self.damageforcescale = 0;
     self.death_time = 0;
     self.respawn_flags = 0;
     self.respawn_time = 0;
     self.stat_respawn_time = 0;
     self.alpha = 0;
     self.scale = 0;
     self.fade_time = 0;
     self.pain_frame = 0;
     self.pain_finished = 0;
     self.strength_finished = 0;
     self.invincible_finished = 0;
     self.superweapons_finished = 0;
     self.pushltime = 0;
     self.istypefrag = 0;
     self.think = func_null;
     self.nextthink = 0;
     self.hook_time = 0;
     self.deadflag = DEAD_NO;
     self.angles = spot.angles;
     self.angles_z = 0;
     self.fixangle = true;
     self.crouch = false;
     self.revival_time = 0;
     setorigin (self, (spot.origin + STAT(PL_VIEW_OFS, NULL))); // offset it so that the spectator spawns higher off the ground, looks better this way
     self.prevorigin = self.origin;
     self.items = 0;
     self.weapons = '0 0 0';
     self.model = "";
     FixPlayermodel(self);
     setmodel(self, MDL_Null);
     self.drawonlytoclient = self;
     setsize (self, STAT(PL_CROUCH_MIN, NULL), STAT(PL_CROUCH_MAX, NULL)); // give the spectator some space between walls for MOVETYPE_FLY_WORLDONLY
     self.view_ofs = '0 0 0'; // so that your view doesn't go into the ceiling with MOVETYPE_FLY_WORLDONLY, previously "PL_VIEW_OFS"
     PS(self).m_weapon = WEP_Null;
     self.weaponname = "";
     PS(self).m_switchingweapon = WEP_Null;
     self.weaponmodel = "";
     for (int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         self.weaponentities[slot] = NULL;
     }
     self.exteriorweaponentity = world;
     self.killcount = FRAGS_SPECTATOR;
     self.velocity = '0 0 0';
     self.avelocity = '0 0 0';
     self.punchangle = '0 0 0';
     self.punchvector = '0 0 0';
     self.oldvelocity = self.velocity;
     self.fire_endtime = -1;
     self.event_damage = func_null;
 }
void ReadyCount ()
Definition at line 477 of file vote.qc.
Referenced by ClientCommand_ready(), and ClientDisconnect().
 {
     float ready_needed_factor, ready_needed_count;
     float t_ready = 0, t_players = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it) && (IS_PLAYER(it) || it.caplayer == 1), LAMBDA(
         ++t_players;
         if (it.ready) ++t_ready;
     ));
     readycount = t_ready;
     Nagger_ReadyCounted();
     ready_needed_factor = bound(0.5, cvar("g_warmup_majority_factor"), 0.999);
     ready_needed_count = floor(t_players * ready_needed_factor) + 1;
     if (readycount >= ready_needed_count) ReadyRestart();
 }
void respawn ()
Definition at line 1318 of file cl_client.qc.
References alpha, autocvar_g_respawn_ghosts, autocvar_g_respawn_ghosts_maxtime, autocvar_g_respawn_ghosts_speed, CopyBody(), CSQCMODEL_EF_RESPAWNGHOST, DAMAGE_NO, EF_NODRAW, MOVETYPE_FLY, origin, PutClientInServer(), random(), randomvec(), SELFPARAM, SOLID_NOT, SUB_SetFade(), and time.
Referenced by PlayerPreThink().
 {SELFPARAM();
     if(self.alpha >= 0 && autocvar_g_respawn_ghosts)
     {
         self.solid = SOLID_NOT;
         self.takedamage = DAMAGE_NO;
         self.movetype = MOVETYPE_FLY;
         self.velocity = '0 0 1' * autocvar_g_respawn_ghosts_speed;
         self.avelocity = randomvec() * autocvar_g_respawn_ghosts_speed * 3 - randomvec() * autocvar_g_respawn_ghosts_speed * 3;
         self.effects |= CSQCMODEL_EF_RESPAWNGHOST;
         Send_Effect(EFFECT_RESPAWN_GHOST, self.origin, '0 0 0', 1);
         if(autocvar_g_respawn_ghosts_maxtime)
             SUB_SetFade (self, time + autocvar_g_respawn_ghosts_maxtime / 2 + random () * (autocvar_g_respawn_ghosts_maxtime - autocvar_g_respawn_ghosts_maxtime / 2), 1.5);
     }
     CopyBody(1);
     self.effects |= EF_NODRAW; // prevent another CopyBody
     PutClientInServer();
 }
void send_CSQC_teamnagger ()
Definition at line 55 of file cl_client.qc.
References MSG_BROADCAST.
Referenced by ClientConnect().
{
     WriteHeader(MSG_BROADCAST, TE_CSQC_TEAMNAGGER);
 }
void SetChangeParms ()
Definition at line 699 of file cl_client.qc.
References MUTATOR_CALLHOOK, parm1, SELFPARAM, and time.
 {SELFPARAM();
     // save parms for level change
     parm1 = self.parm_idlesince - time;
     MUTATOR_CALLHOOK(SetChangeParms);
 }
void SetNewParms ()
Definition at line 686 of file cl_client.qc.
References MUTATOR_CALLHOOK, and parm1.
 {
     // initialize parms for a new player
     parm1 = -(86400 * 366);
     MUTATOR_CALLHOOK(SetNewParms);
 }
void setplayermodel (entity e, string modelname)
Definition at line 157 of file cl_client.qc.
References player_setupanimsformodel().
Referenced by FixPlayermodel().
 {
     precache_model(modelname);
     _setmodel(e, modelname);
     player_setupanimsformodel();
 }
void SetSpectatee (entity player, entity spectatee)
Definition at line 1712 of file cl_client.qc.
References ARC_SF_SETTINGS, and entity().
Referenced by PutClientInServer(), Spectate(), SpectateNext(), SpectatePrev(), and SpectateUpdate().
 {
     entity old_spectatee = player.enemy;
     player.enemy = spectatee;
     // WEAPONTODO
     // these are required to fix the spectator bug with arc
     if(old_spectatee && old_spectatee.arc_beam) { old_spectatee.arc_beam.SendFlags |= ARC_SF_SETTINGS; }
     if(player.enemy && player.enemy.arc_beam) { player.enemy.arc_beam.SendFlags |= ARC_SF_SETTINGS; }
 }
void SetZoomState (float z)
Definition at line 1571 of file cl_client.qc.
References ClientData_Touch(), SELFPARAM, and zoomstate.
Referenced by PlayerPreThink(), and SpectateCopy().
 {SELFPARAM();
     if(z != self.zoomstate)
     {
         self.zoomstate = z;
         ClientData_Touch(self);
     }
     zoomstate_set = 1;
 }
void ShowRespawnCountdown ()
Definition at line 1791 of file cl_client.qc.
References Announcer_PickNumber(), ceil(), CNT_RESPAWN, IS_DEAD, MSG_ANNCE, respawn_countdown, respawn_time, SELFPARAM, and time.
Referenced by PlayerPreThink().
 {SELFPARAM();
     float number;
     if(!IS_DEAD(self)) // just respawned?
         return;
     else
     {
         number = ceil(self.respawn_time - time);
         if(number <= 0)
             return;
         if(number <= self.respawn_countdown)
         {
             self.respawn_countdown = number - 1;
             if(ceil(self.respawn_time - (time + 0.5)) == number) // only say it if it is the same number even in 0.5s; to prevent overlapping sounds
                 { Send_Notification(NOTIF_ONE, self, MSG_ANNCE, Announcer_PickNumber(CNT_RESPAWN, number)); }
         }
     }
 }
bool Spectate (entity pl)
Definition at line 1724 of file cl_client.qc.
References MUTATOR_CALLHOOK, SELFPARAM, SetSpectatee(), spec_player, and SpectateSet().
 {SELFPARAM();
     if(MUTATOR_CALLHOOK(SpectateSet, self, pl))
         return false;
     pl = spec_player;
     SetSpectatee(self, pl);
     return SpectateSet();
 }
void SpectateCopy (entity this, entity spectatee)
Definition at line 1604 of file cl_client.qc.
References anticheat_spectatecopy(), BUTTON_USE, EFMASK_CHEAP, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, PS(), SetZoomState(), STAT(), WriteAngle(), and WriteByte().
Referenced by SpectateUpdate().
 {
     MUTATOR_CALLHOOK(SpectateCopy, spectatee, self);
     self.armortype = spectatee.armortype;
     self.armorvalue = spectatee.armorvalue;
     self.ammo_cells = spectatee.ammo_cells;
     self.ammo_plasma = spectatee.ammo_plasma;
     self.ammo_shells = spectatee.ammo_shells;
     self.ammo_nails = spectatee.ammo_nails;
     self.ammo_rockets = spectatee.ammo_rockets;
     self.ammo_fuel = spectatee.ammo_fuel;
     self.clip_load = spectatee.clip_load;
     self.clip_size = spectatee.clip_size;
     self.effects = spectatee.effects & EFMASK_CHEAP; // eat performance
     self.health = spectatee.health;
     self.impulse = 0;
     self.items = spectatee.items;
     self.last_pickup = spectatee.last_pickup;
     self.hit_time = spectatee.hit_time;
     self.strength_finished = spectatee.strength_finished;
     self.invincible_finished = spectatee.invincible_finished;
     self.pressedkeys = spectatee.pressedkeys;
     self.weapons = spectatee.weapons;
     PS(self).m_switchweapon = PS(spectatee).m_switchweapon;
     PS(self).m_switchingweapon = PS(spectatee).m_switchingweapon;
     PS(self).m_weapon = PS(spectatee).m_weapon;
     self.vortex_charge = spectatee.vortex_charge;
     self.vortex_chargepool_ammo = spectatee.vortex_chargepool_ammo;
     self.hagar_load = spectatee.hagar_load;
     self.arc_heat_percent = spectatee.arc_heat_percent;
     self.minelayer_mines = spectatee.minelayer_mines;
     self.punchangle = spectatee.punchangle;
     self.view_ofs = spectatee.view_ofs;
     self.velocity = spectatee.velocity;
     self.dmg_take = spectatee.dmg_take;
     self.dmg_save = spectatee.dmg_save;
     self.dmg_inflictor = spectatee.dmg_inflictor;
     self.v_angle = spectatee.v_angle;
     self.angles = spectatee.v_angle;
     STAT(FROZEN, self) = STAT(FROZEN, spectatee);
     self.revive_progress = spectatee.revive_progress;
     if(!self.BUTTON_USE)
         self.fixangle = true;
     setorigin(self, spectatee.origin);
     setsize(self, spectatee.mins, spectatee.maxs);
     SetZoomState(spectatee.zoomstate);
     anticheat_spectatecopy(spectatee);
     self.hud = spectatee.hud;
     if(spectatee.vehicle)
     {
         self.fixangle = false;
         //self.velocity = spectatee.vehicle.velocity;
         self.vehicle_health = spectatee.vehicle_health;
         self.vehicle_shield = spectatee.vehicle_shield;
         self.vehicle_energy = spectatee.vehicle_energy;
         self.vehicle_ammo1 = spectatee.vehicle_ammo1;
         self.vehicle_ammo2 = spectatee.vehicle_ammo2;
         self.vehicle_reload1 = spectatee.vehicle_reload1;
         self.vehicle_reload2 = spectatee.vehicle_reload2;
         msg_entity = self;
         WriteByte (MSG_ONE, SVC_SETVIEWANGLES);
             WriteAngle(MSG_ONE,  spectatee.v_angle.x);
             WriteAngle(MSG_ONE,  spectatee.v_angle.y);
             WriteAngle(MSG_ONE,  spectatee.v_angle.z);
         //WriteByte (MSG_ONE, SVC_SETVIEW);
         //    WriteEntity(MSG_ONE, self);
         //makevectors(spectatee.v_angle);
         //setorigin(self, spectatee.origin - v_forward * 400 + v_up * 300);*/
     }
 }
bool SpectateNext ()
Definition at line 1734 of file cl_client.qc.
References classname, enemy, find(), MUTATOR_CALLHOOK, other, SELFPARAM, SetSpectatee(), spec_player, SpectateSet(), and STR_PLAYER.
Referenced by ObserverThink(), and SpectatorThink().
 {SELFPARAM();
     other = find(self.enemy, classname, STR_PLAYER);
     if (MUTATOR_CALLHOOK(SpectateNext, self, other))
         other = spec_player;
     else if (!other)
         other = find(other, classname, STR_PLAYER);
     if(other) { SetSpectatee(self, other); }
     return SpectateSet();
 }
bool SpectatePrev ()
Definition at line 1748 of file cl_client.qc.
References classname, enemy, entity(), MUT_SPECPREV_CONTINUE, MUT_SPECPREV_FOUND, MUT_SPECPREV_RETURN, MUTATOR_CALLHOOK, other, SELFPARAM, SetSpectatee(), spec_player, SpectateSet(), and STR_PLAYER.
Referenced by SpectatorThink().
 {SELFPARAM();
     // NOTE: chain order is from the highest to the lower entnum (unlike find)
     other = findchain(classname, STR_PLAYER);
     if (!other) // no player
         return false;
     entity first = other;
     // skip players until current spectated player
     if(self.enemy)
     while(other && other != self.enemy)
         other = other.chain;
     switch (MUTATOR_CALLHOOK(SpectatePrev, self, other, first))
     {
         case MUT_SPECPREV_FOUND:
             other = spec_player;
             break;
         case MUT_SPECPREV_RETURN:
             other = spec_player;
             return true;
         case MUT_SPECPREV_CONTINUE:
         default:
         {
             if(other.chain)
                 other = other.chain;
             else
                 other = first;
             break;
         }
     }
     SetSpectatee(self, other);
     return SpectateSet();
 }
bool SpectateSet ()
Definition at line 1695 of file cl_client.qc.
References accuracy_resend(), enemy, IS_PLAYER, MOVETYPE_NONE, msg_entity, MSG_ONE, PutObserverInServer(), SELFPARAM, SpectateUpdate(), SVC_SETVIEW, WriteByte(), and WriteEntity().
Referenced by Spectate(), SpectateNext(), and SpectatePrev().
 {SELFPARAM();
     if(!IS_PLAYER(self.enemy))
         return false;
     msg_entity = self;
     WriteByte(MSG_ONE, SVC_SETVIEW);
     WriteEntity(MSG_ONE, self.enemy);
     self.movetype = MOVETYPE_NONE;
     accuracy_resend(self);
     if(!SpectateUpdate())
         PutObserverInServer();
     return true;
 }
bool SpectateUpdate ()
Definition at line 1679 of file cl_client.qc.
References enemy, IS_PLAYER, NULL, SELFPARAM, SetSpectatee(), and SpectateCopy().
Referenced by SpectateSet(), and SpectatorThink().
 {SELFPARAM();
     if(!self.enemy)
         return false;
     if(!IS_PLAYER(self.enemy) || self == self.enemy)
     {
         SetSpectatee(self, NULL);
         return false;
     }
     SpectateCopy(this, this.enemy);
     return true;
 }
void SpectatorThink ()
Definition at line 1982 of file cl_client.qc.
References BUTTON_ATCK, BUTTON_ATCK2, BUTTON_JUMP, FL_CLIENT, FL_JUMPRELEASED, FL_NOTARGET, FL_SPAWNING, flags, impulse, LeaveSpectatorMode(), MinigameImpulse(), PutClientInServer(), PutObserverInServer(), SELFPARAM, SpectateNext(), SpectatePrev(), SpectateUpdate(), STR_OBSERVER, STR_SPECTATOR, and version_mismatch.
Referenced by PlayerPreThink().
 {SELFPARAM();
     if ( self.impulse )
     {
         if(MinigameImpulse(self, self.impulse))
             self.impulse = 0;
     }
     if (self.flags & FL_JUMPRELEASED) {
         if (self.BUTTON_JUMP && !self.version_mismatch) {
             self.flags &= ~FL_JUMPRELEASED;
             self.flags |= FL_SPAWNING;
         } else if(self.BUTTON_ATCK || self.impulse == 10 || self.impulse == 15 || self.impulse == 18 || (self.impulse >= 200 && self.impulse <= 209)) {
             self.flags &= ~FL_JUMPRELEASED;
             if(SpectateNext()) {
                 self.classname = STR_SPECTATOR;
             } else {
                 self.classname = STR_OBSERVER;
                 PutClientInServer();
             }
             self.impulse = 0;
         } else if(self.impulse == 12 || self.impulse == 16  || self.impulse == 19 || (self.impulse >= 220 && self.impulse <= 229)) {
             self.flags &= ~FL_JUMPRELEASED;
             if(SpectatePrev()) {
                 self.classname = STR_SPECTATOR;
             } else {
                 self.classname = STR_OBSERVER;
                 PutClientInServer();
             }
             self.impulse = 0;
         } else if (self.BUTTON_ATCK2) {
             self.flags &= ~FL_JUMPRELEASED;
             self.classname = STR_OBSERVER;
             PutClientInServer();
         } else {
             if(!SpectateUpdate())
                 PutObserverInServer();
         }
     } else {
         if (!(self.BUTTON_ATCK || self.BUTTON_ATCK2)) {
             self.flags |= FL_JUMPRELEASED;
             if(self.flags & FL_SPAWNING)
             {
                 self.flags &= ~FL_SPAWNING;
                 LeaveSpectatorMode();
                 return;
             }
         }
         if(!SpectateUpdate())
             PutObserverInServer();
     }
     self.flags |= FL_CLIENT | FL_NOTARGET;
 }
void UpdateChatBubble ()
Definition at line 1279 of file cl_client.qc.
References alpha, chatbubbleentity, ChatBubbleThink(), EF_LOWPRECISION, SELFPARAM, setmodel, and time.
Referenced by PlayerPostThink().
 {SELFPARAM();
     if (self.alpha < 0)
         return;
     // spawn a chatbubble entity if needed
     if (!self.chatbubbleentity)
     {
         self.chatbubbleentity = new(chatbubbleentity);
         self.chatbubbleentity.owner = self;
         self.chatbubbleentity.exteriormodeltoclient = self;
         self.chatbubbleentity.think = ChatBubbleThink;
         self.chatbubbleentity.nextthink = time;
         setmodel(self.chatbubbleentity, MDL_CHAT); // precision set below
         //setorigin(self.chatbubbleentity, self.origin + '0 0 15' + self.maxs_z * '0 0 1');
         setorigin(self.chatbubbleentity, '0 0 15' + self.maxs_z * '0 0 1');
         setattachment(self.chatbubbleentity, self, "");  // sticks to moving player better, also conserves bandwidth
         self.chatbubbleentity.mdl = self.chatbubbleentity.model;
         //self.chatbubbleentity.model = "";
         self.chatbubbleentity.effects = EF_LOWPRECISION;
     }
 }
void vehicles_enter (entity pl, entity veh)
Definition at line 963 of file sv_vehicles.qc.
References antilag_clear(), CSQCModel_UnlinkEntity(), CSQCVehicleSetup(), DAMAGE_NO, DIFF_TEAM, entity(), FL_NOTARGET, FOREACH_CLIENT, func_null(), IS_BOT_CLIENT, IS_DEAD, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, MOVETYPE_NOCLIP, MSG_CENTER, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, NULL, other, PS(), RemoveGrapplingHook(), SAME_TEAM, SELFPARAM, setself, SOLID_NOT, STAT(), Team_ColorRGB(), teamplay, time, UNSET_ONGROUND, vehicles_clearreturn(), vehicles_damage(), Vehicles_from, VHF_MULTISLOT, world, WriteAngle(), WriteByte(), and WriteEntity().
Referenced by PlayerUseKey(), and vehicles_touch().
 {SELFPARAM();
    // Remove this when bots know how to use vehicles
     if((IS_BOT_CLIENT(pl) && !autocvar_g_vehicles_allow_bots))
         return;
     if((!IS_PLAYER(pl))
     || (veh.phase >= time)
     || (pl.vehicle_enter_delay >= time)
     || (STAT(FROZEN, pl))
     || (IS_DEAD(pl))
     || (pl.vehicle)
     ) { return; }
     if(autocvar_g_vehicles_enter) // vehicle's touch function should handle this if entering via use key is disabled (TODO)
     if(veh.vehicle_flags & VHF_MULTISLOT)
     if(veh.owner)
     {
         setself(veh);
         other = pl; // TODO: fix
         if(!veh.gunner1)
         if(time >= veh.gun1.phase)
         if(veh.gun1.vehicle_enter)
         if(veh.gun1.vehicle_enter())
         {
             setself(this);
             return;
         }
         if(!veh.gunner2)
         if(time >= veh.gun2.phase)
         if(veh.gun2.vehicle_enter)
         if(veh.gun2.vehicle_enter())
         {
             setself(this);
             return;
         }
         setself(this);
     }
     if(teamplay)
     if(veh.team)
     if(DIFF_TEAM(pl, veh))
     if(autocvar_g_vehicles_steal)
     {
         FOREACH_CLIENT(IS_PLAYER(it) && SAME_TEAM(it, veh), LAMBDA(Send_Notification(NOTIF_ONE, it, MSG_CENTER, CENTER_VEHICLE_STEAL)));
         Send_Notification(NOTIF_ONE, pl, MSG_CENTER, CENTER_VEHICLE_STEAL_SELF);
         if (autocvar_g_vehicles_steal_show_waypoint) {
             entity wp = WaypointSprite_Spawn(WP_VehicleIntruder, 0, 0, pl, '0 0 68', world, veh.team, veh, wps_intruder, true, RADARICON_DANGER);
             wp.colormod = Team_ColorRGB(pl.team);
         }
     }
     else return;
     RemoveGrapplingHook(pl);
     veh.vehicle_ammo1 = 0;
     veh.vehicle_ammo2 = 0;
     veh.vehicle_reload1 = 0;
     veh.vehicle_reload2 = 0;
     veh.vehicle_energy = 0;
     veh.owner = pl;
     pl.vehicle = veh;
     // .viewmodelforclient works better.
     //veh.vehicle_hudmodel.drawonlytoclient = veh.owner;
     veh.vehicle_hudmodel.viewmodelforclient = pl;
     tracebox(pl.origin, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL), pl.origin, false, pl);
     pl.crouch = false;
     pl.view_ofs = STAT(PL_VIEW_OFS, NULL);
     setsize (pl, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL));
     veh.event_damage    = vehicles_damage;
     veh.nextthink       = 0;
     pl.angles           = veh.angles;
     pl.takedamage       = DAMAGE_NO;
     pl.solid            = SOLID_NOT;
     pl.movetype         = MOVETYPE_NOCLIP;
     pl.teleportable     = false;
     pl.alpha            = -1;
     pl.event_damage     = func_null;
     pl.view_ofs         = '0 0 0';
     veh.colormap        = pl.colormap;
     if(veh.tur_head)
         veh.tur_head.colormap = pl.colormap;
     veh.m_switchweapon = PS(pl).m_switchweapon;
     pl.hud = veh.vehicleid;
     pl.PlayerPhysplug = veh.PlayerPhysplug;
     pl.vehicle_ammo1 = veh.vehicle_ammo1;
     pl.vehicle_ammo2 = veh.vehicle_ammo2;
     pl.vehicle_reload1 = veh.vehicle_reload1;
     pl.vehicle_reload2 = veh.vehicle_reload2;
     pl.vehicle_energy = veh.vehicle_energy;
     // Cant do this, hides attached objects too.
     //veh.exteriormodeltoclient = veh.owner;
     //veh.tur_head.exteriormodeltoclient = veh.owner;
     UNSET_ONGROUND(pl);
     UNSET_ONGROUND(veh);
     veh.team = pl.team;
     veh.flags -= FL_NOTARGET;
     if (IS_REAL_CLIENT(pl))
     {
         Send_Notification(NOTIF_ONE, pl, MSG_CENTER, CENTER_VEHICLE_ENTER);
         msg_entity = pl;
         WriteByte (MSG_ONE, SVC_SETVIEWPORT);
         WriteEntity(MSG_ONE, veh.vehicle_viewport);
         WriteByte (MSG_ONE, SVC_SETVIEWANGLES);
         if(veh.tur_head)
         {
             WriteAngle(MSG_ONE, veh.tur_head.angles_x + veh.angles_x); // tilt
             WriteAngle(MSG_ONE, veh.tur_head.angles_y + veh.angles_y); // yaw
             WriteAngle(MSG_ONE, 0);                                   // roll
         }
         else
         {
             WriteAngle(MSG_ONE, veh.angles_x * -1); // tilt
             WriteAngle(MSG_ONE, veh.angles_y);    // yaw
             WriteAngle(MSG_ONE, 0);               // roll
         }
     }
     vehicles_clearreturn(veh);
     CSQCVehicleSetup(pl, veh.vehicleid);
     MUTATOR_CALLHOOK(VehicleEnter, pl, veh);
     setself(veh);
     CSQCModel_UnlinkEntity(veh);
     Vehicle info = Vehicles_from(veh.vehicleid);
     info.vr_enter(info, veh);
     setself(this);
     antilag_clear(pl);
 }
void ()
Variable Documentation
float BUTTON_CHAT
Definition at line 1252 of file cl_client.qc.
entity chatbubbleentity
Definition at line 1168 of file cl_client.qc.
Referenced by ClientDisconnect(), and UpdateChatBubble().
float clientkill_nexttime
Definition at line 733 of file cl_client.qc.
Referenced by ClientKill_TeamChange().
float clientkilltime
Definition at line 816 of file cl_client.qc.
Referenced by ClientKill_TeamChange().
float ebouncefactor
Definition at line 622 of file cl_client.qc.
float ebouncestop
Definition at line 622 of file cl_client.qc.
string FallbackPlayerModel
Definition at line 122 of file cl_client.qc.
Referenced by CheckPlayerModel().
float idlekick_lasttimeleft
Definition at line 2495 of file cl_client.qc.
Referenced by PlayerPostThink().
int items_added
Definition at line 2096 of file cl_client.qc.
float last_vehiclecheck
Definition at line 2095 of file cl_client.qc.
float model_randomizer
Definition at line 316 of file cl_client.qc.
Referenced by ClientConnect().
string netname_previous
Definition at line 109 of file cl_client.qc.
Referenced by ClientConnect(), ClientDisconnect(), and PlayerPreThink().
float usekeypressed
Definition at line 2093 of file cl_client.qc.
Referenced by PlayerPreThink().
float zoomstate_set
Definition at line 1570 of file cl_client.qc.