Xonotic: server/mutators/mutator/gamemode_keyhunt.qh File Reference
gamemode_keyhunt.qh File Reference
#include "../gamemode.qh"
Macros
#define autocvar_g_keyhunt_point_limit cvar("g_keyhunt_point_limit")
#define FOR_EACH_KH_KEY(v) for(v = kh_worldkeylist; v; v = v.kh_worldkeynext)
Typedefs
using kh_Think_t) = void(
Functions
void kh_Controller_SetThink (float t, kh_Think_t func)
void kh_Initialize ()
void kh_StartRound ()
REGISTER_MUTATOR (kh, false)
Variables
int autocvar_g_keyhunt_point_leadlimit
bool autocvar_g_keyhunt_team_spawns
entity kh_next
bool kh_tracking_enabled
Macro Definition Documentation
#define autocvar_g_keyhunt_point_limit cvar("g_keyhunt_point_limit")
Definition at line 5 of file gamemode_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
#define FOR_EACH_KH_KEY (v) for(v = kh_worldkeylist; v; v = v.kh_worldkeynext)
Definition at line 40 of file gamemode_keyhunt.qh.
Referenced by kh_FinishRound(), kh_Key_AllOwnedByWhichTeam(), kh_Key_AssignTo(), kh_Key_Think(), kh_LoserTeam(), kh_update_state(), and kh_WinnerTeam().
Typedef Documentation
using kh_Think_t = void(
Definition at line 48 of file gamemode_keyhunt.qh.
Function Documentation
void kh_Controller_SetThink (float t, kh_Think_t func)
Definition at line 150 of file gamemode_keyhunt.qc.
References ceil(), kh_controller, kh_Controller_Thinkfunc, and time.
Referenced by kh_FinishRound(), kh_Initialize(), kh_StartRound(), and kh_WaitForPlayers().
 {
     kh_Controller_Thinkfunc = func;
     kh_controller.cnt = ceil(t);
     if(t == 0)
         kh_controller.nextthink = time; // force
 }
void kh_Initialize ()
Definition at line 978 of file gamemode_keyhunt.qc.
References autocvar_g_keyhunt_teams_override, BIT, bound(), cvar(), kh_controller, kh_Controller_SetThink(), kh_Controller_Think(), kh_key_carried, kh_key_dropped, kh_ScoreRules(), kh_teams, kh_WaitForPlayers(), setmodel, setthink, spawn(), and teams.
Referenced by REGISTER_MUTATOR().
 {
     // setup variables
     kh_teams = autocvar_g_keyhunt_teams_override;
     if(kh_teams < 2)
         kh_teams = cvar("g_keyhunt_teams"); // read the cvar directly as it gets written earlier in the same frame
     kh_teams = bound(2, kh_teams, 4);
     int teams = 0;
     if(kh_teams >= 1) teams |= BIT(0);
     if(kh_teams >= 2) teams |= BIT(1);
     if(kh_teams >= 3) teams |= BIT(2);
     if(kh_teams >= 4) teams |= BIT(3);
     kh_teams = teams; // now set it?
     // make a KH entity for controlling the game
     kh_controller = spawn();
     setthink(kh_controller, kh_Controller_Think);
     kh_Controller_SetThink(0, kh_WaitForPlayers);
     setmodel(kh_controller, MDL_KH_KEY);
     kh_key_dropped = kh_controller.modelindex;
     /*
     dprint(vtos(kh_controller.mins));
     dprint(vtos(kh_controller.maxs));
     dprint("\n");
     */
 #ifdef KH_PLAYER_USE_CARRIEDMODEL
     setmodel(kh_controller, MDL_KH_KEY_CARRIED);
     kh_key_carried = kh_controller.modelindex;
 #else
     kh_key_carried = kh_key_dropped;
 #endif
     kh_controller.model = "";
     kh_controller.modelindex = 0;
     kh_ScoreRules(kh_teams);
 }
void kh_StartRound ()
Definition at line 915 of file gamemode_keyhunt.qc.
References entity(), FOREACH_CLIENT, game_starttime, IS_DEAD, IS_PLAYER, kh_Controller_SetThink(), kh_GetMissingTeams(), kh_Key_Spawn(), kh_Team_ByID(), kh_teams, kh_WaitForPlayers(), LAMBDA, NULL, NumTeams(), PHYS_INPUT_BUTTON_CHAT, players, random(), and time.
Referenced by kh_FinishRound(), and kh_WaitForPlayers().
 {
     if(time < game_starttime)
     {
         kh_Controller_SetThink(game_starttime - time + 0.1, kh_WaitForPlayers);
         return;
     }
     if(kh_GetMissingTeams())
     {
         kh_Controller_SetThink(1, kh_WaitForPlayers);
         return;
     }
     Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_KEYHUNT);
     Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_KEYHUNT_OTHER);
     for(int i = 0; i < NumTeams(kh_teams); ++i)
     {
         int teem = kh_Team_ByID(i);
         int players = 0;
         entity my_player = NULL;
         FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(
             if(!IS_DEAD(it) && !PHYS_INPUT_BUTTON_CHAT(it) && it.team == teem)
             {
                 ++players;
                 if(random() * players <= 1)
                     my_player = it;
             }
         ));
         kh_Key_Spawn(my_player, 360 * i / NumTeams(kh_teams), i);
     }
     kh_tracking_enabled = false;
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_KEYHUNT_SCAN, autocvar_g_balance_keyhunt_delay_tracking);
     kh_Controller_SetThink(autocvar_g_balance_keyhunt_delay_tracking, kh_EnableTrackingDevice);
 }
REGISTER_MUTATOR (kh , false)
Definition at line 10 of file gamemode_keyhunt.qh.
References ActivateTeamplay(), autocvar_g_keyhunt_point_leadlimit, autocvar_g_keyhunt_point_limit, autocvar_g_keyhunt_team_spawns, autocvar_timelimit_override, error, have_team_spawns, kh_Initialize(), LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, SetLimits(), and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         kh_Initialize();
         ActivateTeamplay();
         SetLimits(autocvar_g_keyhunt_point_limit, autocvar_g_keyhunt_point_leadlimit, autocvar_timelimit_override, -1);
         if (autocvar_g_keyhunt_team_spawns)
             have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back kh_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
Variable Documentation
int autocvar_g_keyhunt_point_leadlimit
Definition at line 6 of file gamemode_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
bool autocvar_g_keyhunt_team_spawns
Definition at line 7 of file gamemode_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
entity kh_next
Definition at line 46 of file gamemode_keyhunt.qh.
bool kh_tracking_enabled
Definition at line 45 of file gamemode_keyhunt.qh.
Referenced by havocbot_goalrating_kh(), kh_EnableTrackingDevice(), kh_Key_waypointsprite_visible_for_player(), and kh_KeyCarrier_waypointsprite_visible_for_player().