Xonotic: common/mutators/mutator/offhand_blaster/sv_offhand_blaster.qc File Reference
sv_offhand_blaster.qc File Reference
#include "sv_offhand_blaster.qh"
Functions
MUTATOR_HOOKFUNCTION (offhand_blaster, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (offhand_blaster, BuildMutatorsPrettyString)
MUTATOR_HOOKFUNCTION (offhand_blaster, BuildGameplayTipsString)
MUTATOR_HOOKFUNCTION (offhand_blaster, PlayerSpawn)
REGISTER_MUTATOR (offhand_blaster, expr_evaluate(autocvar_g_offhand_blaster))
Variables
string autocvar_g_offhand_blaster = "0"
Function Documentation
MUTATOR_HOOKFUNCTION() [1/4]
MUTATOR_HOOKFUNCTION (offhand_blaster , BuildMutatorsString)
Definition at line 7 of file sv_offhand_blaster.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":offhand_blaster");
 }
MUTATOR_HOOKFUNCTION() [2/4]
MUTATOR_HOOKFUNCTION (offhand_blaster , BuildMutatorsPrettyString)
Definition at line 12 of file sv_offhand_blaster.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Offhand blaster");
 }
MUTATOR_HOOKFUNCTION() [3/4]
MUTATOR_HOOKFUNCTION (offhand_blaster , BuildGameplayTipsString)
Definition at line 17 of file sv_offhand_blaster.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), "\n\n^3offhand blaster^8 is enabled, press 'e' (+hook) to use it\n");
 }
MUTATOR_HOOKFUNCTION() [4/4]
MUTATOR_HOOKFUNCTION (offhand_blaster , PlayerSpawn)
Definition at line 22 of file sv_offhand_blaster.qc.
References entity(), M_ARGV, and OFFHAND_BLASTER.
 {
     entity player = M_ARGV(0, entity);
     player.offhand = OFFHAND_BLASTER;
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (offhand_blaster , expr_evaluate(autocvar_g_offhand_blaster))
Variable Documentation
autocvar_g_offhand_blaster
string autocvar_g_offhand_blaster = "0"
Definition at line 3 of file sv_offhand_blaster.qc.