Xonotic: menu/xonotic/weaponarenacheckbox.qc File Reference
weaponarenacheckbox.qc File Reference
#include "weaponarenacheckbox.qh"
Functions
entity makeXonoticWeaponarenaCheckBox (string theWeapon, string theText)
void XonoticWeaponarenaCheckBox_configureXonoticWeaponarenaCheckBox (entity me, string theWeapon, string theText)
void XonoticWeaponarenaCheckBox_loadCvars (entity me)
void XonoticWeaponarenaCheckBox_saveCvars (entity me)
void XonoticWeaponarenaCheckBox_setChecked (entity me, float foo)
Function Documentation
entity makeXonoticWeaponarenaCheckBox (string theWeapon, string theText)
Definition at line 3 of file weaponarenacheckbox.qc.
References entity(), and NEW.
Referenced by XonoticMutatorsDialog_fill().
 {
     entity me;
     me = NEW(XonoticWeaponarenaCheckBox);
     me.configureXonoticWeaponarenaCheckBox(me, theWeapon, theText);
     return me;
 }
void XonoticWeaponarenaCheckBox_configureXonoticWeaponarenaCheckBox (entity me, string theWeapon, string theText)
Definition at line 10 of file weaponarenacheckbox.qc.
 {
     me.netname = theWeapon;
     me.checked = false;
     me.loadCvars(me);
     me.configureCheckBox(me, theText, me.fontSize, me.image);
 }
void XonoticWeaponarenaCheckBox_loadCvars (entity me)
Definition at line 22 of file weaponarenacheckbox.qc.
References argv(), cvar_string(), and tokenize_console.
 {
     int n = tokenize_console(cvar_string("menu_weaponarena"));
     for (int i = 0; i < n; i++)
     {
         if(argv(i) == me.netname)
         {
             me.checked = true;
             break;
         }
     }
 }
void XonoticWeaponarenaCheckBox_saveCvars (entity me)
Definition at line 35 of file weaponarenacheckbox.qc.
References localcmd, and strcat().
 {
     if(me.checked)
         localcmd(strcat("\nmenu_cmd addtolist menu_weaponarena ", me.netname, "\n"));
     else
         localcmd(strcat("\nmenu_cmd removefromlist menu_weaponarena ", me.netname, "\n"));
     localcmd("\ng_weaponarena \"$menu_weaponarena\"\n");
 }
void XonoticWeaponarenaCheckBox_setChecked (entity me, float foo)
Definition at line 17 of file weaponarenacheckbox.qc.
 {
     me.checked = !me.checked;
     me.saveCvars(me);
 }