Xonotic: common/gamemodes/gamemode/keyhunt/sv_keyhunt.qh File Reference
sv_keyhunt.qh File Reference
#include <common/mutators/base.qh>
Macros
#define autocvar_g_keyhunt_point_limit cvar("g_keyhunt_point_limit")
#define FOR_EACH_KH_KEY(v) for(v = kh_worldkeylist; v; v = v.kh_worldkeynext)
Typedefs
using kh_Think_t = void()
Functions
void kh_Controller_SetThink (float t, kh_Think_t func)
void kh_Initialize ()
void kh_StartRound ()
REGISTER_MUTATOR (kh, false)
Variables
int autocvar_g_keyhunt_point_leadlimit
bool autocvar_g_keyhunt_team_spawns
entity kh_next
bool kh_tracking_enabled
entity kh_worldkeylist
entity kh_worldkeynext
Macro Definition Documentation
autocvar_g_keyhunt_point_limit
#define autocvar_g_keyhunt_point_limit cvar("g_keyhunt_point_limit")
Definition at line 4 of file sv_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
FOR_EACH_KH_KEY
#define FOR_EACH_KH_KEY (v) for(v = kh_worldkeylist; v; v = v.kh_worldkeynext)
Definition at line 27 of file sv_keyhunt.qh.
Referenced by kh_FinishRound(), kh_Key_AllOwnedByWhichTeam(), kh_Key_AssignTo(), kh_Key_Think(), kh_LoserTeam(), kh_update_state(), and kh_WinnerTeam().
Typedef Documentation
kh_Think_t
using kh_Think_t = void()
Definition at line 35 of file sv_keyhunt.qh.
Function Documentation
kh_Controller_SetThink()
void kh_Controller_SetThink (float t, kh_Think_t func)
Definition at line 148 of file sv_keyhunt.qc.
References ceil(), kh_controller, kh_Controller_Thinkfunc, kh_WaitForPlayers(), and time.
Referenced by kh_FinishRound(), kh_Initialize(), kh_StartRound(), and kh_WaitForPlayers().
 {
     kh_Controller_Thinkfunc = func;
     kh_controller.cnt = ceil(t);
     if(t == 0)
         kh_controller.nextthink = time; // force
 }
kh_Initialize()
void kh_Initialize ()
Definition at line 975 of file sv_keyhunt.qc.
References autocvar_g_keyhunt_teams_override, BITS, bound(), cvar(), kh_controller, kh_Controller_SetThink(), kh_Controller_Think(), kh_key_carried, kh_key_dropped, kh_ScoreRules(), kh_teams, kh_WaitForPlayers(), new_pure, setmodel, and setthink.
Referenced by REGISTER_MUTATOR().
 {
     // setup variables
     kh_teams = autocvar_g_keyhunt_teams_override;
     if(kh_teams < 2)
         kh_teams = cvar("g_keyhunt_teams"); // read the cvar directly as it gets written earlier in the same frame
     kh_teams = BITS(bound(2, kh_teams, 4));
     // make a KH entity for controlling the game
     kh_controller = new_pure(kh_controller);
     setthink(kh_controller, kh_Controller_Think);
     kh_Controller_SetThink(0, kh_WaitForPlayers);
     setmodel(kh_controller, MDL_KH_KEY);
     kh_key_dropped = kh_controller.modelindex;
     /*
     dprint(vtos(kh_controller.mins));
     dprint(vtos(kh_controller.maxs));
     dprint("\n");
     */
 #ifdef KH_PLAYER_USE_CARRIEDMODEL
     setmodel(kh_controller, MDL_KH_KEY_CARRIED);
     kh_key_carried = kh_controller.modelindex;
 #else
     kh_key_carried = kh_key_dropped;
 #endif
     kh_controller.model = "";
     kh_controller.modelindex = 0;
     kh_ScoreRules(kh_teams);
 }
kh_StartRound()
void kh_StartRound ()
Definition at line 912 of file sv_keyhunt.qc.
References autocvar_g_balance_keyhunt_delay_tracking, entity(), FOREACH_CLIENT, IS_DEAD, IS_PLAYER, kh_Controller_SetThink(), kh_EnableTrackingDevice(), kh_GetMissingTeams(), kh_Key_Spawn(), kh_Team_ByID(), kh_teams, kh_tracking_enabled, kh_WaitForPlayers(), NULL, NumTeams(), PHYS_INPUT_BUTTON_CHAT, players, and time.
Referenced by kh_FinishRound(), and kh_WaitForPlayers().
 {
     if(time < game_starttime)
     {
         kh_Controller_SetThink(game_starttime - time + 0.1, kh_WaitForPlayers);
         return;
     }
     if(kh_GetMissingTeams())
     {
         kh_Controller_SetThink(1, kh_WaitForPlayers);
         return;
     }
     Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_KEYHUNT);
     Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_KEYHUNT_OTHER);
     for(int i = 0; i < NumTeams(kh_teams); ++i)
     {
         int teem = kh_Team_ByID(i);
         int players = 0;
         entity my_player = NULL;
         FOREACH_CLIENT(IS_PLAYER(it), {
             if(!IS_DEAD(it) && !PHYS_INPUT_BUTTON_CHAT(it) && it.team == teem)
             {
                 ++players;
                 if(random() * players <= 1)
                     my_player = it;
             }
         });
         kh_Key_Spawn(my_player, 360 * i / NumTeams(kh_teams), i);
     }
     kh_tracking_enabled = false;
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_KEYHUNT_SCAN, autocvar_g_balance_keyhunt_delay_tracking);
     kh_Controller_SetThink(autocvar_g_balance_keyhunt_delay_tracking, kh_EnableTrackingDevice);
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (kh , false)
Definition at line 9 of file sv_keyhunt.qh.
References autocvar_g_keyhunt_point_leadlimit, autocvar_g_keyhunt_point_limit, autocvar_g_keyhunt_team_spawns, GameRules_limit_lead(), GameRules_limit_score(), GameRules_spawning_teams(), GameRules_teams(), kh_Initialize(), MUTATOR_ONADD, and MUTATOR_STATIC.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_teams(true);
         GameRules_spawning_teams(autocvar_g_keyhunt_team_spawns);
         GameRules_limit_score(autocvar_g_keyhunt_point_limit);
         GameRules_limit_lead(autocvar_g_keyhunt_point_leadlimit);
         kh_Initialize();
     }
     return 0;
 }
Variable Documentation
autocvar_g_keyhunt_point_leadlimit
int autocvar_g_keyhunt_point_leadlimit
Definition at line 5 of file sv_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
autocvar_g_keyhunt_team_spawns
bool autocvar_g_keyhunt_team_spawns
Definition at line 6 of file sv_keyhunt.qh.
Referenced by REGISTER_MUTATOR().
kh_next
entity kh_next
Definition at line 33 of file sv_keyhunt.qh.
kh_tracking_enabled
bool kh_tracking_enabled
Definition at line 32 of file sv_keyhunt.qh.
Referenced by havocbot_goalrating_kh(), kh_EnableTrackingDevice(), kh_Key_waypointsprite_visible_for_player(), kh_KeyCarrier_waypointsprite_visible_for_player(), and kh_StartRound().
kh_worldkeylist
entity kh_worldkeylist
Definition at line 24 of file sv_keyhunt.qh.
Referenced by havocbot_goalrating_kh(), kh_Key_Remove(), and kh_Key_Spawn().
kh_worldkeynext
entity kh_worldkeynext
Definition at line 25 of file sv_keyhunt.qh.