Xonotic: server/race.qh File Reference
race.qh File Reference
Functions
void race_AbandonRaceCheck (entity p)
void race_ClearRecords ()
float race_GetFractionalLapCount (entity e)
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
void race_InitSpectator ()
float race_NextCheckpoint (float f)
void race_PreparePlayer (entity this)
float race_PreviousCheckpoint (float f)
string race_readName (string map, float pos)
float race_readTime (string map, float pos)
string race_readUID (string map, float pos)
void race_RetractPlayer (entity this)
void race_send_recordtime (float msg)
void race_send_speedaward (float msg)
void race_send_speedaward_alltimebest (float msg)
void race_SendNextCheckpoint (entity e, float spec)
void race_SendRankings (float pos, float prevpos, float del, float msg)
void race_setTime (string map, float t, string myuid, string mynetname, entity e, bool showmessage)
void race_StartCompleting ()
STATIC_INIT (g_racecheckpoints)
Variables
bool g_race_qualifying
IntrusiveList g_racecheckpoints
float race_completed
float race_completing
float race_fraglimit
float race_highest_place_spawn
float race_laptime
float race_leadlimit
float race_lowest_place_spawn
float race_movetime
float race_movetime_count
float race_movetime_frac
float race_place
float race_respawn_checkpoint
entity race_respawn_spotref
float race_spawns
float race_started
float race_teams
float race_timelimit
float speedaward_alltimebest
string speedaward_alltimebest_holder
string speedaward_alltimebest_uid
string speedaward_holder
float speedaward_lastsent
float speedaward_lastupdate
float speedaward_speed
string speedaward_uid
const float ST_RACE_LAPS = 1
Function Documentation
void race_AbandonRaceCheck (entity p)
Definition at line 1038 of file race.qc.
References ClientData_Touch(), MAKE_INDEPENDENT_PLAYER, NULL, and race_completing.
Referenced by MUTATOR_HOOKFUNCTION(), and race_StartCompleting().
 {
     if(race_completing && !p.race_completed)
     {
         p.race_completed = 1;
         MAKE_INDEPENDENT_PLAYER(p);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_ABANDONED, p.netname);
         ClientData_Touch(p);
     }
 }
void race_ClearRecords ()
Definition at line 1085 of file race.qc.
References FOREACH_CLIENT, LAMBDA, MAX_CHECKPOINTS, p, race_checkpoint_recordholders, race_checkpoint_records, race_PreparePlayer(), string_null, and strunzone().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     float i;
     for(i = 0; i < MAX_CHECKPOINTS; ++i)
     {
         race_checkpoint_records[i] = 0;
         if(race_checkpoint_recordholders[i])
             strunzone(race_checkpoint_recordholders[i]);
         race_checkpoint_recordholders[i] = string_null;
     }
     FOREACH_CLIENT(true, LAMBDA(
         float p = it.race_place;
         race_PreparePlayer(it);
         it.race_place = p;
     ));
 }
float race_GetFractionalLapCount (entity e)
Definition at line 1168 of file race.qc.
References bound(), entity(), g_racecheckpoints, IL_EACH, max(), PlayerScore_Add(), race_highest_checkpoint, race_timed_checkpoint, vector(), and vlen().
 {
     // interesting metrics (idea by KrimZon) to maybe sort players in the
     // scoreboard, immediately updates when overtaking
     //
     // requires the track to be built so you never get farther away from the
     // next checkpoint, though, and current Xonotic race maps are not built that
     // way
     //
     // also, this code is slow and would need optimization (i.e. "next CP"
     // links on CP entities)
     float l;
     l = PlayerScore_Add(e, SP_RACE_LAPS, 0);
     if(e.race_completed)
         return l; // not fractional
     vector o0, o1;
     float bestfraction, fraction;
     entity lastcp;
     float nextcpindex, lastcpindex;
     nextcpindex = max(e.race_checkpoint, 0);
     lastcpindex = e.race_respawn_checkpoint;
     lastcp = e.race_respawn_spotref;
     if(nextcpindex == lastcpindex)
         return l; // finish
     bestfraction = 1;
     IL_EACH(g_racecheckpoints, true,
     {
         if(it.race_checkpoint != lastcpindex)
             continue;
         if(lastcp)
             if(it != lastcp)
                 continue;
         o0 = (it.absmin + it.absmax) * 0.5;
         IL_EACH(g_racecheckpoints, true,
         {
             if(it.race_checkpoint != nextcpindex)
                 continue;
             o1 = (it.absmin + it.absmax) * 0.5;
             if(o0 == o1)
                 continue;
             fraction = bound(0.0001, vlen(e.origin - o1) / vlen(o0 - o1), 1);
             if(fraction < bestfraction)
                 bestfraction = fraction;
         });
     });
     // we are at CP "nextcpindex - bestfraction"
     // race_timed_checkpoint == 4: then nextcp==4 means 0.9999x, nextcp==0 means 0.0000x
     // race_timed_checkpoint == 0: then nextcp==0 means 0.9999x
     float c, nc;
     nc = race_highest_checkpoint + 1;
     c = ((nextcpindex - race_timed_checkpoint + nc + nc - 1) % nc) + 1 - bestfraction;
     return l + c / nc;
 }
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
Definition at line 1104 of file race.qc.
References g_race_qualifying, IS_REAL_CLIENT, msg_entity, MSG_ONE, RACE_NET_PENALTY_QUALIFYING, RACE_NET_PENALTY_RACE, time, TIME_ENCODE, WriteByte(), WriteShort(), and WriteString().
Referenced by CheatCommand(), checkpoint_passed(), penalty_touch(), and penalty_use().
 {
     if(g_race_qualifying)
     {
         pl.race_penalty_accumulator += penalty;
         if(IS_REAL_CLIENT(pl))
         {
             msg_entity = pl;
             WRITESPECTATABLE_MSG_ONE(msg_entity, {
                 WriteHeader(MSG_ONE, TE_CSQC_RACE);
                 WriteByte(MSG_ONE, RACE_NET_PENALTY_QUALIFYING);
                 WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                 WriteString(MSG_ONE, reason);
             });
         }
     }
     else
     {
         pl.race_penalty = time + penalty;
         if(IS_REAL_CLIENT(pl))
         {
             msg_entity = pl;
             WRITESPECTATABLE_MSG_ONE(msg_entity, {
                 WriteHeader(MSG_ONE, TE_CSQC_RACE);
                 WriteByte(MSG_ONE, RACE_NET_PENALTY_RACE);
                 WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                 WriteString(MSG_ONE, reason);
             });
         }
     }
 }
void race_InitSpectator ()
Definition at line 21 of file race.qc.
References g_race_qualifying, msg_entity, and race_SendNextCheckpoint().
Referenced by SetSpectatee_status().
 {
     if(g_race_qualifying)
         if(msg_entity.enemy.race_laptime)
             race_SendNextCheckpoint(msg_entity.enemy, 1);
 }
float race_NextCheckpoint (float f)
Definition at line 125 of file race.qc.
References race_highest_checkpoint.
Referenced by checkpoint_passed(), and trigger_race_checkpoint_verify().
 {
     if(f >= race_highest_checkpoint)
         return 0;
     else
         return f + 1;
 }
void race_PreparePlayer (entity this)
Definition at line 1055 of file race.qc.
References NULL, race_ClearTime(), race_place, race_respawn_checkpoint, race_respawn_spotref, and race_started.
Referenced by MUTATOR_HOOKFUNCTION(), and race_ClearRecords().
 {
     race_ClearTime(this);
     this.race_place = 0;
     this.race_started = 0;
     this.race_respawn_checkpoint = 0;
     this.race_respawn_spotref = NULL;
 }
float race_PreviousCheckpoint (float f)
Definition at line 133 of file race.qc.
References race_highest_checkpoint.
 {
     if(f == -1)
         return 0;
     else if(f == 0)
         return race_highest_checkpoint;
     else
         return f - 1;
 }
string race_readName (string map, float pos)
Definition at line 93 of file race.qc.
References CTF_RECORD, CTS_RECORD, db_get(), ftos(), g_ctf, g_cts, RACE_RECORD, ServerProgsDB, strcat(), and uid2name().
Referenced by getrankings(), MUTATOR_HOOKFUNCTION(), race_SendRankings(), and race_setTime().
 {
     string rr = ((g_cts) ? CTS_RECORD : ((g_ctf) ? CTF_RECORD : RACE_RECORD));
     return uid2name(db_get(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(pos))));
 }
float race_readTime (string map, float pos)
Definition at line 30 of file race.qc.
References CTF_RECORD, CTS_RECORD, db_get(), ftos(), g_ctf, g_cts, RACE_RECORD, ServerProgsDB, stof(), and strcat().
Referenced by getladder(), getrankings(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_readPos(), race_send_recordtime(), race_SendRankings(), race_setTime(), and race_writeTime().
 {
     string rr = ((g_cts) ? CTS_RECORD : ((g_ctf) ? CTF_RECORD : RACE_RECORD));
     return stof(db_get(ServerProgsDB, strcat(map, rr, "time", ftos(pos))));
 }
string race_readUID (string map, float pos)
Definition at line 37 of file race.qc.
References CTF_RECORD, CTS_RECORD, db_get(), ftos(), g_ctf, g_cts, RACE_RECORD, ServerProgsDB, and strcat().
Referenced by getladder(), race_deleteTime(), race_setTime(), and race_writeTime().
 {
     string rr = ((g_cts) ? CTS_RECORD : ((g_ctf) ? CTF_RECORD : RACE_RECORD));
     return db_get(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(pos)));
 }
void race_RetractPlayer (entity this)
Definition at line 1064 of file race.qc.
References g_cts, g_race, race_checkpoint, race_ClearTime(), race_respawn_checkpoint, and race_timed_checkpoint.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(!g_race && !g_cts)
         return;
     if(this.race_respawn_checkpoint == 0 || this.race_respawn_checkpoint == race_timed_checkpoint)
         race_ClearTime(this);
     this.race_checkpoint = this.race_respawn_checkpoint;
 }
void race_send_recordtime (float msg)
Definition at line 195 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RECORD, race_readTime(), and WriteByte().
Referenced by MUTATOR_HOOKFUNCTION(), race_deleteTime(), and race_setTime().
 {
     // send the server best time
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SERVER_RECORD);
     WriteInt24_t(msg, race_readTime(GetMapname(), 1));
 }
void race_send_speedaward (float msg)
Definition at line 204 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD, speedaward_holder, speedaward_speed, WriteByte(), and WriteString().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     // send the best speed of the round
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SPEED_AWARD);
     WriteInt24_t(msg, floor(speedaward_speed+0.5));
     WriteString(msg, speedaward_holder);
 }
void race_send_speedaward_alltimebest (float msg)
Definition at line 213 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD_BEST, speedaward_alltimebest, speedaward_alltimebest_holder, WriteByte(), and WriteString().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     // send the best speed
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SPEED_AWARD_BEST);
     WriteInt24_t(msg, floor(speedaward_alltimebest+0.5));
     WriteString(msg, speedaward_alltimebest_holder);
 }
void race_SendNextCheckpoint (entity e, float spec)
Definition at line 159 of file race.qc.
References IS_REAL_CLIENT, msg_entity, MSG_ONE, race_checkpoint_recordholders, race_checkpoint_records, race_CheckpointNetworkID(), RACE_NET_CHECKPOINT_NEXT_QUALIFYING, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING, time, WriteByte(), WriteCoord(), and WriteString().
Referenced by checkpoint_passed(), race_InitSpectator(), and race_SendTime().
 {
     float recordtime;
     string recordholder;
     float cp;
     if(!e.race_laptime)
         return;
     cp = e.race_checkpoint;
     recordtime = race_checkpoint_records[cp];
     recordholder = race_checkpoint_recordholders[cp];
     if(recordholder == e.netname)
         recordholder = "";
     if(!IS_REAL_CLIENT(e))
         return;
     if(!spec)
         msg_entity = e;
     WRITESPECTATABLE_MSG_ONE(msg_entity, {
         WriteHeader(MSG_ONE, TE_CSQC_RACE);
         if(spec)
         {
             WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING);
             //WriteCoord(MSG_ONE, e.race_laptime - e.race_penalty_accumulator);
             WriteCoord(MSG_ONE, time - e.race_movetime - e.race_penalty_accumulator);
         }
         else
             WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_QUALIFYING);
         WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player will be at next
         WriteInt24_t(MSG_ONE, recordtime);
         WriteString(MSG_ONE, recordholder);
     });
 }
void race_SendRankings (float pos, float prevpos, float del, float msg)
Definition at line 222 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RANKINGS, race_readName(), race_readTime(), WriteByte(), WriteShort(), and WriteString().
Referenced by MUTATOR_HOOKFUNCTION(), race_deleteTime(), and race_setTime().
 {
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SERVER_RANKINGS);
     WriteShort(msg, pos);
     WriteShort(msg, prevpos);
     WriteShort(msg, del);
     WriteString(msg, race_readName(GetMapname(), pos));
     WriteInt24_t(msg, race_readTime(GetMapname(), pos));
 }
void race_setTime (string map, float t, string myuid, string mynetname, entity e, bool showmessage)
Definition at line 252 of file race.qc.
References GetMapname(), getrankings(), MSG_ALL, NULL, race_readName(), race_readPos(), race_readTime(), race_readUID(), race_send_recordtime(), race_SendRankings(), race_SendStatus(), race_writeTime(), RANKINGS_CNT, strunzone(), strzone(), time, TIME_DECODE, uid2name(), and write_recordmarker().
Referenced by ctf_CaptureRecord(), and race_SendTime().
 {
     // netname only used TEMPORARILY for printing
     int newpos = race_readPos(map, t);
     int player_prevpos = 0;
     for(int i = 1; i <= RANKINGS_CNT; ++i)
     {
         if(race_readUID(map, i) == myuid)
             player_prevpos = i;
     }
     float oldrec;
     string oldrec_holder;
     if (player_prevpos && (player_prevpos < newpos || !newpos))
     {
         oldrec = race_readTime(GetMapname(), player_prevpos);
         race_SendStatus(0, e); // "fail"
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_FAIL_RANKED, mynetname, player_prevpos, t, oldrec);
         return;
     }
     else if (!newpos)
     {
         // no ranking, time worse than the worst ranked
         oldrec = race_readTime(GetMapname(), RANKINGS_CNT);
         race_SendStatus(0, e); // "fail"
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_FAIL_UNRANKED, mynetname, RANKINGS_CNT, t, oldrec);
         return;
     }
     // if we didn't hit a return yet, we have a new record!
     // if the player does not have a UID we can unfortunately not store the record, as the rankings system relies on UIDs
     if(myuid == "")
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_MISSING_UID, mynetname, t);
         return;
     }
     if(uid2name(myuid) == "^1Unregistered Player")
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_MISSING_NAME, mynetname, t);
         return;
     }
     oldrec = race_readTime(GetMapname(), newpos);
     oldrec_holder = race_readName(GetMapname(), newpos);
     // store new ranking
     race_writeTime(GetMapname(), t, myuid);
     if (newpos == 1 && showmessage)
     {
         write_recordmarker(e, time - TIME_DECODE(t), TIME_DECODE(t));
         race_send_recordtime(MSG_ALL);
     }
     race_SendRankings(newpos, player_prevpos, 0, MSG_ALL);
     if(rankings_reply)
         strunzone(rankings_reply);
     rankings_reply = strzone(getrankings());
     if(newpos == player_prevpos)
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_IMPROVED, mynetname, newpos, t, oldrec);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(1, e); } // "new time"
     }
     else if(oldrec == 0)
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_SET, mynetname, newpos, t);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(2, e); } // "new rank"
     }
     else
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_BROKEN, mynetname, oldrec_holder, newpos, t, oldrec);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(2, e); } // "new rank"
     }
 }
void race_StartCompleting ()
Definition at line 1049 of file race.qc.
References FOREACH_CLIENT, IS_DEAD, IS_PLAYER, LAMBDA, race_AbandonRaceCheck(), and race_completing.
Referenced by InitiateSuddenDeath(), and race_SendTime().
 {
     race_completing = 1;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_DEAD(it), LAMBDA(race_AbandonRaceCheck(it)));
 }
STATIC_INIT (g_racecheckpoints)
Definition at line 33 of file race.qh.
References IL_NEW.
 { g_racecheckpoints = IL_NEW(); }
Variable Documentation
bool g_race_qualifying
Definition at line 8 of file race.qh.
Referenced by checkpoint_passed(), CheckRules_World(), ClientCommand_ready(), ClientKill_TeamChange(), cts_ScoreRules(), InitiateSuddenDeath(), MUTATOR_HOOKFUNCTION(), race_ImposePenaltyTime(), race_Initialize(), race_InitSpectator(), race_ScoreRules(), race_SendTime(), rc_SetLimits(), ReadyRestart_force(), REGISTER_MUTATOR(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
IntrusiveList g_racecheckpoints
Definition at line 32 of file race.qh.
Referenced by havocbot_role_cts(), havocbot_role_race(), race_GetFractionalLapCount(), and spawnfunc().
float race_completed
Definition at line 21 of file race.qh.
float race_completing
Definition at line 23 of file race.qh.
Referenced by race_AbandonRaceCheck(), race_SendTime(), race_StartCompleting(), and ReadyRestart().
float race_fraglimit
Definition at line 16 of file race.qh.
Referenced by rc_SetLimits().
float race_highest_place_spawn
Definition at line 14 of file race.qh.
Referenced by spawnfunc(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
float race_laptime
Definition at line 22 of file race.qh.
float race_leadlimit
Definition at line 17 of file race.qh.
Referenced by rc_SetLimits().
float race_lowest_place_spawn
Definition at line 15 of file race.qh.
Referenced by spawnfunc(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
float race_movetime
Definition at line 25 of file race.qh.
float race_movetime_count
Definition at line 27 of file race.qh.
float race_movetime_frac
Definition at line 26 of file race.qh.
float race_place
Definition at line 19 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), race_PreparePlayer(), and spawnfunc().
float race_respawn_checkpoint
Definition at line 29 of file race.qh.
Referenced by race_PreparePlayer(), and race_RetractPlayer().
entity race_respawn_spotref
Definition at line 30 of file race.qh.
Referenced by race_PreparePlayer().
float race_spawns
Definition at line 13 of file race.qh.
Referenced by Spawn_Score(), and spawnfunc().
float race_started
Definition at line 20 of file race.qh.
Referenced by race_PreparePlayer().
float race_teams
Definition at line 3 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), race_ScoreRules(), and rc_SetLimits().
float race_timelimit
Definition at line 18 of file race.qh.
Referenced by rc_SetLimits().
float speedaward_alltimebest
Definition at line 56 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and race_send_speedaward_alltimebest().
string speedaward_alltimebest_holder
Definition at line 57 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and race_send_speedaward_alltimebest().
string speedaward_alltimebest_uid
Definition at line 58 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION().
string speedaward_holder
Definition at line 53 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and race_send_speedaward().
float speedaward_lastsent
Definition at line 10 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION().
float speedaward_lastupdate
Definition at line 11 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION().
float speedaward_speed
Definition at line 52 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and race_send_speedaward().
string speedaward_uid
Definition at line 54 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION().
const float ST_RACE_LAPS = 1
Definition at line 6 of file race.qh.
Referenced by race_ScoreRules(), and race_SendTime().