Xonotic: common/notifications/all.qh File Reference
all.qh File Reference
#include <common/command/_mod.qh>
#include <common/constants.qh>
#include <common/teams.qh>
#include <common/util.qh>
#include <common/sounds/sound.qh>
#include <common/weapons/all.qh>
#include "all.inc"
Macros
#define ACVNN(name) autocvar_notification_##name
#define APP_NUM(num, prefix) ((num) ? APP_TEAM_NUM(num, prefix) : prefix##_NEUTRAL)
#define APP_TEAM_NUM(num, prefix) ((num == NUM_TEAM_1) ? prefix##_RED : ((num == NUM_TEAM_2) ? prefix##_BLUE : ((num == NUM_TEAM_3) ? prefix##_YELLOW : prefix##_PINK)))
#define EIGHT_VARS_TO_VARARGS_VARLIST
#define KILL_SPREE_LIST
#define MSG_ANNCE_NOTIF(name, default, sound, channel, volume, position)
#define MSG_ANNCE_NOTIF_(teamnum, name, cvarname, default, sound, channel, volume, position)
#define MSG_ANNCE_NOTIF_TEAM(teamnum, name, cvarname, default, sound, channel, volume, position) MSG_ANNCE_NOTIF_(teamnum, ANNCE_##name, ANNCE_##cvarname, default, sound, channel, volume, position)
#define MSG_CENTER_NOTIF(name, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
#define MSG_CENTER_NOTIF_(teamnum, name, cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
#define MSG_CENTER_NOTIF_TEAM(teamnum, name, cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle) MSG_CENTER_NOTIF_(teamnum, CENTER_##name, CENTER_##cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
#define MSG_CHOICE_NOTIF(name, default, challow, chtype, optiona, optionb)
#define MSG_CHOICE_NOTIF_(teamnum, name, cvarname, default, challow, chtype, optiona, optionb)
#define MSG_CHOICE_NOTIF_TEAM(teamnum, name, cvarname, default, challow, chtype, optiona, optionb) MSG_CHOICE_NOTIF_(teamnum, CHOICE_##name, CHOICE_##cvarname, default, challow, chtype, optiona, optionb)
#define MSG_INFO_NOTIF(name, default, strnum, flnum, args, hudargs, icon, normal, gentle)
#define MSG_INFO_NOTIF_(teamnum, name, cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle)
#define MSG_INFO_NOTIF_TEAM(teamnum, name, cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle) MSG_INFO_NOTIF_(teamnum, INFO_##name, INFO_##cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle)
#define MSG_MULTI_NOTIF(name, default, anncename, infoname, centername)
#define MULTIICON_INFO(name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle) MULTIICON_INFO_(INFO_##name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle)
#define MULTIICON_INFO_(name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle)
#define NOTIF_ADD_AUTOCVAR(name, default) float autocvar_notification_##name = default;
#define NOTIF_ARGUMENT_LIST
#define NOTIF_HIT_MAX(count, funcname)
#define NOTIF_HIT_UNKNOWN(token, funcname) { backtrace(sprintf("%s: Hit unknown token in selected string! '%s'\n", funcname, selected)); break; }
#define SPREE_ITEM(counta, countb, center, normal, gentle) case counta: { return sprintf(CCR(normal_or_gentle(normal, gentle)), player, spree_newline); }
Typedefs
using Notification = entity
always last
Functions
string BUFF_NAME (int i)
void Create_Notification_Entity (entity notif, float var_default, float var_cvar, MSG typeId, string namestring, int teamnum)
void Create_Notification_Entity_Annce (entity notif, float var_cvar, string namestring, float channel, string snd, float vol, float position)
void Create_Notification_Entity_Choice (entity notif, float var_cvar, string namestring, float challow_def, float challow_var, MSG chtype, Notification optiona, Notification optionb)
void Create_Notification_Entity_InfoCenter (entity notif, float var_cvar, string namestring, int strnum, int flnum, string args, string hudargs, string icon, CPID cpid, string durcnt, string normal, string gentle)
void Create_Notification_Entity_Multi (entity notif, float var_cvar, string namestring, Notification anncename, Notification infoname, Notification centername)
void Destroy_All_Notifications ()
void Dump_Notifications (int fh, bool alsoprint)
used to output notifications.cfg file
GENERIC_COMMAND (dumpnotifs,"Dump all notifications into notifications_dump.txt")
string Get_Notif_CvarName (Notification notif)
Notification Get_Notif_Ent (MSG net_type, int net_name)
string Get_Notif_TypeName (MSG net_type)
main types/groups of notifications
void Local_Notification (MSG net_type, Notification net_name,...count)
void Local_Notification_WOVA (MSG net_type, Notification net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
glue for networking, forwards to Local_Notification
string notif_arg_item_wepammo (float f1, float f2)
string notif_arg_spree_inf (float type, string input, string player, float spree)
REGISTRY_BEGIN (Notifications)
REGISTRY_END (Notifications)
REGISTRY_SORT (Notifications)
STATIC_INIT (Notifications)
STATIC_INIT_LATE (Notif_Choices)
Variables
const float ARG_CS = 4
const float ARG_CS_SV = 3
const float ARG_CS_SV_DC = 2
const float ARG_CS_SV_HA = 1
const float ARG_DC = 6
string arg_slot [NOTIF_MAX_ARGS]
const float ARG_SV = 5
float autocvar_notification_allow_chatboxprint = 0
float autocvar_notification_errors_are_fatal = true
float autocvar_notification_item_centerprinttime = 1.5
float autocvar_notification_show_location = false
string autocvar_notification_show_location_string = ""
float autocvar_notification_show_sprees = true
float autocvar_notification_show_sprees_center = true
float autocvar_notification_show_sprees_center_specialonly = true
float autocvar_notification_show_sprees_info = 3
float autocvar_notification_show_sprees_info_newline = true
float autocvar_notification_show_sprees_info_specialonly = true
int msg_choice_choices [NOTIF_CHOICE_MAX]
string nent_args
float nent_challow_def
float nent_challow_var
int nent_channel
int nent_choice_count = 0
int nent_choice_idx
entity nent_client
CPID nent_cpid
int nent_default
string nent_durcnt
bool nent_enabled
int nent_floatcount
float nent_floats [4]
string nent_hudargs
string nent_icon
string nent_iconargs
entity nent_msgannce
entity nent_msgcenter
entity nent_msginfo
string nent_name
float nent_net_name
MSG nent_net_type
entity nent_optiona
entity nent_optionb
float nent_position
string nent_snd
string nent_string
int nent_stringcount
string nent_strings [4]
int nent_teamnum
MSG nent_type
float nent_vol
const int NOTIF_CHOICE_MAX = 50
bool notif_error
bool notif_global_error
const float NOTIF_MAX_ARGS = 7
const float NOTIF_MAX_DURCNT = 2
const float NOTIF_MAX_HUDARGS = 2
Macro Definition Documentation
#define ACVNN (name) autocvar_notification_##name
Definition at line 694 of file all.qh.
#define APP_NUM (num, prefix) ((num) ? APP_TEAM_NUM(num, prefix) : prefix##_NEUTRAL)
Definition at line 85 of file all.qh.
Referenced by ctf_CheckFlagReturn(), ctf_Handle_Capture(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_Handle_Retrieve(), and MUTATOR_HOOKFUNCTION().
#define APP_TEAM_NUM (num, prefix) ((num == NUM_TEAM_1) ? prefix##_RED : ((num == NUM_TEAM_2) ? prefix##_BLUE : ((num == NUM_TEAM_3) ? prefix##_YELLOW : prefix##_PINK)))
Definition at line 84 of file all.qh.
Referenced by CA_CheckWinner(), ctf_CaptureRecord(), ctf_Handle_Pickup(), ctf_Handle_Return(), Domination_CheckWinner(), freezetag_CheckWinner(), kh_Key_Collect(), kh_Key_DropAll(), kh_Key_DropOne(), kh_Key_Spawn(), kh_Key_Think(), kh_WinnerTeam(), Obituary(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_GeneratorDamage(), ons_GeneratorThink(), Onslaught_CheckWinner(), and SetPlayerTeam().
#define EIGHT_VARS_TO_VARARGS_VARLIST
Value:
VARITEM(1, 0, s1) \
    VARITEM(2, 0, XPD(s1, s2)) \
    VARITEM(3, 0, XPD(s1, s2, s3)) \
    VARITEM(4, 0, XPD(s1, s2, s3, s4)) \
    VARITEM(0, 1, f1) \
    VARITEM(1, 1, XPD(s1, f1)) \
    VARITEM(2, 1, XPD(s1, s2, f1)) \
    VARITEM(3, 1, XPD(s1, s2, s3, f1)) \
    VARITEM(4, 1, XPD(s1, s2, s3, s4, f1)) \
    VARITEM(0, 2, XPD(f1, f2)) \
    VARITEM(1, 2, XPD(s1, f1, f2)) \
    VARITEM(2, 2, XPD(s1, s2, f1, f2)) \
    VARITEM(3, 2, XPD(s1, s2, s3, f1, f2)) \
    VARITEM(4, 2, XPD(s1, s2, s3, s4, f1, f2)) \
    VARITEM(0, 3, XPD(f1, f2, f3)) \
    VARITEM(1, 3, XPD(s1, f1, f2, f3)) \
    VARITEM(2, 3, XPD(s1, s2, f1, f2, f3)) \
    VARITEM(3, 3, XPD(s1, s2, s3, f1, f2, f3)) \
    VARITEM(4, 3, XPD(s1, s2, s3, s4, f1, f2, f3)) \
    VARITEM(0, 4, XPD(f1, f2, f3, f4)) \
    VARITEM(1, 4, XPD(s1, f1, f2, f3, f4)) \
    VARITEM(2, 4, XPD(s1, s2, f1, f2, f3, f4)) \
    VARITEM(3, 4, XPD(s1, s2, s3, f1, f2, f3, f4)) \
    VARITEM(4, 4, XPD(s1, s2, s3, s4, f1, f2, f3, f4))
Definition at line 87 of file all.qh.
Referenced by Local_Notification_WOVA().
#define KILL_SPREE_LIST
Value:
SPREE_ITEM(3, 03, _("TRIPLE FRAG! "), _("%s^K1 made a TRIPLE FRAG! %s^BG"), _("%s^K1 made a TRIPLE SCORE! %s^BG")) \
    SPREE_ITEM(5, 05, _("RAGE! "), _("%s^K1 unlocked RAGE! %s^BG"), _("%s^K1 made FIVE SCORES IN A ROW! %s^BG")) \
    SPREE_ITEM(10, 10, _("MASSACRE! "), _("%s^K1 started a MASSACRE! %s^BG"), _("%s^K1 made TEN SCORES IN A ROW! %s^BG")) \
    SPREE_ITEM(15, 15, _("MAYHEM! "), _("%s^K1 executed MAYHEM! %s^BG"), _("%s^K1 made FIFTEEN SCORES IN A ROW! %s^BG")) \
    SPREE_ITEM(20, 20, _("BERSERKER! "), _("%s^K1 is a BERSERKER! %s^BG"), _("%s^K1 made TWENTY SCORES IN A ROW! %s^BG")) \
    SPREE_ITEM(25, 25, _("CARNAGE! "), _("%s^K1 inflicts CARNAGE! %s^BG"), _("%s^K1 made TWENTY FIVE SCORES IN A ROW! %s^BG")) \
    SPREE_ITEM(30, 30, _("ARMAGEDDON! "), _("%s^K1 unleashes ARMAGEDDON! %s^BG"), _("%s^K1 made THIRTY SCORES IN A ROW! %s^BG"))
Definition at line 449 of file all.qh.
Referenced by notif_arg_spree_inf(), and Obituary().
#define MSG_ANNCE_NOTIF (name, default, sound, channel, volume, position)
Value:
NOTIF_ADD_AUTOCVAR(ANNCE_##name, default) \
    MSG_ANNCE_NOTIF_(0, ANNCE_##name, ANNCE_##name, default, sound, channel, volume, position)
Definition at line 742 of file all.qh.
#define MSG_ANNCE_NOTIF_ (teamnum, name, cvarname, default, sound, channel, volume, position)
Value:
REGISTER(Notifications, name, m_id, new_pure(msg_annce_notification)) { \
        Create_Notification_Entity      (this, default, ACVNN(cvarname), MSG_ANNCE, strtoupper(#name), teamnum); \
        Create_Notification_Entity_Annce(this, ACVNN(cvarname), strtoupper(#name), \
            channel,   /* channel  */ \
            sound,     /* snd      */ \
            volume,    /* vol      */ \
            position); /* position */ \
    }
Definition at line 746 of file all.qh.
#define MSG_ANNCE_NOTIF_TEAM (teamnum, name, cvarname, default, sound, channel, volume, position) MSG_ANNCE_NOTIF_(teamnum, ANNCE_##name, ANNCE_##cvarname, default, sound, channel, volume, position)
Definition at line 739 of file all.qh.
#define MSG_CENTER_NOTIF (name, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
Value:
NOTIF_ADD_AUTOCVAR(CENTER_##name, default) \
    MSG_CENTER_NOTIF_(0, CENTER_##name, CENTER_##name, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
Definition at line 797 of file all.qh.
#define MSG_CENTER_NOTIF_ (teamnum, name, cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
Value:
REGISTER(Notifications, name, m_id, new_pure(msg_center_notification)) { \
        Create_Notification_Entity           (this, default, ACVNN(cvarname), MSG_CENTER, strtoupper(#name), teamnum); \
        Create_Notification_Entity_InfoCenter(this, ACVNN(cvarname), strtoupper(#name), strnum, flnum, \
            args,    /* args    */ \
            "",      /* hudargs */ \
            "",      /* icon    */ \
            cpid,    /* cpid    */ \
            durcnt,  /* durcnt  */ \
            normal,  /* normal  */ \
            gentle); /* gentle  */ \
    }
Definition at line 801 of file all.qh.
#define MSG_CENTER_NOTIF_TEAM (teamnum, name, cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle) MSG_CENTER_NOTIF_(teamnum, CENTER_##name, CENTER_##cvarname, default, strnum, flnum, args, cpid, durcnt, normal, gentle)
Definition at line 794 of file all.qh.
#define MSG_CHOICE_NOTIF (name, default, challow, chtype, optiona, optionb)
Value:
NOTIF_ADD_AUTOCVAR(CHOICE_##name, default) \
    NOTIF_ADD_AUTOCVAR(CHOICE_##name##_ALLOWED, challow) \
    MSG_CHOICE_NOTIF_(0, CHOICE_##name, CHOICE_##name, default, challow, chtype, optiona, optionb)
Definition at line 827 of file all.qh.
#define MSG_CHOICE_NOTIF_ (teamnum, name, cvarname, default, challow, chtype, optiona, optionb)
Value:
REGISTER(Notifications, name, m_id, new_pure(msg_choice_notification)) { \
        this.nent_choice_idx = nent_choice_count++; \
        Create_Notification_Entity       (this, default, ACVNN(cvarname), MSG_CHOICE, strtoupper(#name), teamnum); \
        Create_Notification_Entity_Choice(this, ACVNN(cvarname), strtoupper(#name), \
            challow,                                 /* challow_def */ \
            autocvar_notification_##cvarname##_ALLOWED,  /* challow_var */ \
            chtype,                                  /* chtype      */ \
            optiona,                                 /* optiona     */ \
            optionb);                                /* optionb     */ \
    }
Definition at line 832 of file all.qh.
#define MSG_CHOICE_NOTIF_TEAM (teamnum, name, cvarname, default, challow, chtype, optiona, optionb) MSG_CHOICE_NOTIF_(teamnum, CHOICE_##name, CHOICE_##cvarname, default, challow, chtype, optiona, optionb)
Definition at line 824 of file all.qh.
#define MSG_INFO_NOTIF (name, default, strnum, flnum, args, hudargs, icon, normal, gentle)
Value:
NOTIF_ADD_AUTOCVAR(INFO_##name, default) \
    MSG_INFO_NOTIF_(0, INFO_##name, INFO_##name, default, strnum, flnum, args, hudargs, icon, normal, gentle)
Definition at line 759 of file all.qh.
#define MSG_INFO_NOTIF_ (teamnum, name, cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle)
Value:
REGISTER(Notifications, name, m_id, new_pure(msg_info_notification)) { \
        Create_Notification_Entity           (this, default, ACVNN(cvarname), MSG_INFO, strtoupper(#name), teamnum); \
        Create_Notification_Entity_InfoCenter(this, ACVNN(cvarname), strtoupper(#name), strnum, flnum, \
            args,     /* args    */ \
            hudargs,  /* hudargs */ \
            icon,     /* icon    */ \
            CPID_Null,/* cpid    */ \
            "",       /* durcnt  */ \
            normal,   /* normal  */ \
            gentle);  /* gentle  */ \
    }
Definition at line 763 of file all.qh.
#define MSG_INFO_NOTIF_TEAM (teamnum, name, cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle) MSG_INFO_NOTIF_(teamnum, INFO_##name, INFO_##cvarname, default, strnum, flnum, args, hudargs, icon, normal, gentle)
Definition at line 756 of file all.qh.
#define MSG_MULTI_NOTIF (name, default, anncename, infoname, centername)
Value:
NOTIF_ADD_AUTOCVAR(name, default) \
    REGISTER(Notifications, name, m_id, new_pure(msg_multi_notification)) { \
        Create_Notification_Entity      (this, default, ACVNN(name), MSG_MULTI, strtoupper(#name), 0); \
        Create_Notification_Entity_Multi(this, ACVNN(name), strtoupper(#name), \
            anncename,   /* anncename  */ \
            infoname,    /* infoname   */ \
            centername); /* centername */ \
    }
Definition at line 814 of file all.qh.
#define MULTIICON_INFO (name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle) MULTIICON_INFO_(INFO_##name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle)
Definition at line 777 of file all.qh.
#define MULTIICON_INFO_ (name, default, strnum, flnum, args, hudargs, iconargs, icon, normal, gentle)
Value:
NOTIF_ADD_AUTOCVAR(name, default) \
    REGISTER(Notifications, name, m_id, new_pure(msg_info_notification)) { \
        Create_Notification_Entity           (this, default, ACVNN(name), MSG_INFO, strtoupper(#name), 0); \
        Create_Notification_Entity_InfoCenter(this, ACVNN(name), strtoupper(#name), strnum, flnum, \
            args,     /* args    */ \
            hudargs,  /* hudargs */ \
            icon,     /* icon    */ \
            CPID_Null,/* cpid    */ \
            "",       /* durcnt  */ \
            normal,   /* normal  */ \
            gentle);  /* gentle  */ \
        this.nent_iconargs = iconargs; \
    }
Definition at line 779 of file all.qh.
#define NOTIF_ADD_AUTOCVAR (name, default) float autocvar_notification_##name = default;
Definition at line 298 of file all.qh.
#define NOTIF_ARGUMENT_LIST
Definition at line 399 of file all.qh.
Referenced by Local_Notification_sprintf(), and Process_Notif_Args().
#define NOTIF_HIT_MAX (count, funcname)
Value:
MACRO_BEGIN \
    if(sel_num == count) { backtrace(sprintf("%s: Hit maximum arguments!\n", funcname)); break; } \
MACRO_END
Definition at line 443 of file all.qh.
Referenced by Local_Notification_sprintf().
#define NOTIF_HIT_UNKNOWN (token, funcname) { backtrace(sprintf("%s: Hit unknown token in selected string! '%s'\n", funcname, selected)); break; }
Definition at line 447 of file all.qh.
Referenced by Local_Notification_sprintf().
#define SPREE_ITEM (counta, countb, center, normal, gentle) case counta: { return sprintf(CCR(normal_or_gentle(normal, gentle)), player, spree_newline); }
Typedef Documentation
using Notification = entity
always last
Definition at line 81 of file all.qh.
Function Documentation
string BUFF_NAME (int i)
Definition at line 3 of file buffs.qc.
References Buffs_from, Buff::m_color, Buff::m_name, rgb_to_hexcolor(), and strcat().
 {
     Buff b = Buffs_from(i);
     return strcat(rgb_to_hexcolor(b.m_color), b.m_name);
 }
void Create_Notification_Entity (entity notif, float var_default, float var_cvar, MSG typeId, string namestring, int teamnum)
Definition at line 393 of file all.qc.
References LOG_INFOF, notif_error, notif_global_error, and strzone().
 {
     // =====================
     //  Global Entity Setup
     // =====================
     notif.nent_default = var_default;
     notif.nent_enabled = (var_cvar >= 1);
     notif.nent_type = typeId;
     notif.nent_name = strzone(namestring);
     notif.nent_teamnum = teamnum;
     // Other pre-notif-setup requisites
     notif_error = false;
     switch (typeId)
     {
         case MSG_ANNCE:
         case MSG_INFO:
         case MSG_CENTER:
         case MSG_MULTI:
         case MSG_CHOICE:
             break;
         default:
             LOG_INFOF(
                 (
                     "^1NOTIFICATION WITH IMPROPER TYPE: "
                     "^7net_type = %d, net_name = %s."
                 ),
                 typeId,
                 namestring
             );
             notif_error = true;
             break;
     }
     // now check to see if any errors happened
     if (notif_error)
     {
         notif.nent_enabled = false; // disable the notification so it can't cause trouble
         notif_global_error = true; // throw the red flag that an error happened on init
     }
 }
void Create_Notification_Entity_Annce (entity notif, float var_cvar, string namestring, float channel, string snd, float vol, float position)
Definition at line 443 of file all.qc.
References AnnouncerFilename, Get_Notif_TypeName(), LOG_INFOF, notif_error, precache_sound(), and strzone().
         {
             // Set MSG_ANNCE information and handle precaching
             #ifdef CSQC
             MSG typeId = MSG_ANNCE;
             if (!(GENTLE && (var_cvar == 1)))
             {
                 if(snd != "")
                 {
                     if(notif.nent_enabled)
                     {
                         precache_sound(AnnouncerFilename(snd));
                         notif.nent_channel = channel;
                         notif.nent_snd = strzone(snd);
                         notif.nent_vol = vol;
                         notif.nent_position = position;
                     }
                 }
                 else
                 {
                     string typestring = Get_Notif_TypeName(typeId);
                     LOG_INFOF(
                         (
                             "^1NOTIFICATION WITH NO SOUND: "
                             "^7net_type = %s, net_name = %s."
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
             }
             else { notif.nent_enabled = false; }
             #else
             notif.nent_enabled = false;
             #endif
         }
void Create_Notification_Entity_Choice (entity notif, float var_cvar, string namestring, float challow_def, float challow_var, MSG chtype, Notification optiona, Notification optionb)
Definition at line 699 of file all.qc.
References Get_Notif_TypeName(), LOG_INFOF, max(), and notif_error.
         {
             MSG typeId = MSG_CHOICE;
             if (chtype == MSG_Null || !optiona || !optionb)
             {
                 string typestring = Get_Notif_TypeName(typeId);
                 LOG_INFOF(
                     (
                         "^1NOTIFICATION IS MISSING CHOICE PARAMS: "
                         "^7net_type = %s, net_name = %s."
                     ),
                     typestring,
                     namestring
                 );
                 notif_error = true;
             }
             else
             {
                 notif.nent_optiona = optiona;
                 notif.nent_optionb = optionb;
                 notif.nent_challow_def = challow_def; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                 notif.nent_challow_var = challow_var; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                 notif.nent_stringcount = max(notif.nent_optiona.nent_stringcount, notif.nent_optionb.nent_stringcount);
                 notif.nent_floatcount = max(notif.nent_optiona.nent_floatcount, notif.nent_optionb.nent_floatcount);
                 /*#ifdef NOTIFICATIONS_DEBUG
                 Debug_Notification(sprintf(
                     "Create_Notification_Entity(...): MSG_CHOICE: %s\n%s\n%s\n",
                     notif.nent_name,
                     sprintf(
                         "^ optiona: %s %s : %d %d",
                         Get_Notif_TypeName(notif.nent_optiona.nent_type),
                         notif.nent_optiona.nent_name,
                         notif.nent_optiona.nent_stringcount,
                         notif.nent_optiona.nent_floatcount
                     ),
                     sprintf(
                         "^ optionb: %s %s : %d %d",
                         Get_Notif_TypeName(notif.nent_optionb.nent_type),
                         notif.nent_optionb.nent_name,
                         notif.nent_optionb.nent_stringcount,
                         notif.nent_optionb.nent_floatcount
                     )
                 ));
                 #endif*/
             }
         }
void Create_Notification_Entity_InfoCenter (entity notif, float var_cvar, string namestring, int strnum, int flnum, string args, string hudargs, string icon, CPID cpid, string durcnt, string normal, string gentle)
Definition at line 489 of file all.qc.
References CPID_Null, Get_Notif_TypeName(), LOG_INFOF, LOG_WARNF, notif_error, Process_Notif_Args(), server_is_dedicated, SET_NOTIF_STRING, and strzone().
         {
             MSG typeId = notif.nent_type;
             // Set MSG_INFO and MSG_CENTER string/float counts
             notif.nent_stringcount = strnum;
             notif.nent_floatcount = flnum;
             // Only initialize arguments if we're either a client or on a dedicated server
             #ifdef SVQC
             float should_process_args = server_is_dedicated;
             #else
             float should_process_args = true;
             #endif
             string typestring = Get_Notif_TypeName(typeId);
             if(should_process_args)
             {
                 // ========================
                 //  Process Main Arguments
                 // ========================
                 if(strnum + flnum)
                 {
                     if(args != "")
                     {
                         notif.nent_args = strzone(
                             Process_Notif_Args(1, args, typestring, namestring));
                     }
                     else if((hudargs == "") && (durcnt ==""))
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION HAS ARG COUNTS BUT NO ARGS OR HUDARGS OR DURCNT: "
                                 "^7net_type = %s, net_name = %s, strnum = %d, flnum = %d"
                             ),
                             typestring,
                             namestring,
                             strnum,
                             flnum
                         );
                         notif_error = true;
                     }
                 }
                 else if(args != "")
                 {
                     notif.nent_args = strzone(
                         Process_Notif_Args(1, args, typestring, namestring));
                 }
                 // =======================================
                 //  Process HUD and Centerprint Arguments
                 //    Only processed on CSQC, as these
                 //    args are only for HUD features.
                 // =======================================
                 #ifdef CSQC
                 if(hudargs != "")
                 {
                     notif.nent_hudargs = strzone(
                         Process_Notif_Args(2, hudargs, typestring, namestring));
                     if(icon != "") { notif.nent_icon = strzone(icon); }
                     else
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION HAS HUDARGS BUT NO ICON: "
                                 "^7net_type = %s, net_name = %s."
                             ),
                             typestring,
                             namestring
                         );
                         notif_error = true;
                     }
                 }
                 else if(icon != "")
                 {
                     LOG_WARNF(
                         (
                             "^1NOTIFICATION HAS ICON BUT NO HUDARGS: "
                             "^7net_type = %s, net_name = %s.\n"
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
                 if (durcnt != "")
                 {
                     notif.nent_durcnt = strzone(Process_Notif_Args(3, durcnt, typestring, namestring));
                     if (cpid == CPID_Null && durcnt != "0 0")
                     {
                         LOG_WARNF(
                             (
                                 "Notification has durcnt but no cpid: "
                                 "net_type = %s, net_name = %s."
                             ),
                             typestring,
                             namestring
                         );
                         notif_error = true;
                     }
                 }
                 notif.nent_cpid = cpid;
                 #endif
                 // ======================
                 //  Process Notif String
                 // ======================
                 #define SET_NOTIF_STRING(string,stringname) MACRO_BEGIN \
                     notif.nent_string = strzone(CCR( \
                         Process_Notif_Line( \
                             typeId, \
                             (var_cvar > 1), \
                             string, \
                             typestring, \
                             namestring, \
                             stringname \
                         )) \
                     ); \
                 MACRO_END
                 if(GENTLE)
                 {
                     if(gentle != "") { SET_NOTIF_STRING(gentle, "GENTLE"); }
                     else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                 }
                 else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                 #undef SET_NOTIF_STRING
                 // Check to make sure a string was chosen
                 if(notif.nent_string == "")
                 {
                     LOG_INFOF(
                         (
                             "^1EMPTY NOTIFICATION: "
                             "^7net_type = %s, net_name = %s."
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
             }
         }
void Create_Notification_Entity_Multi (entity notif, float var_cvar, string namestring, Notification anncename, Notification infoname, Notification centername)
Definition at line 648 of file all.qc.
References Get_Notif_TypeName(), LOG_INFOF, max(), and notif_error.
         {
             MSG typeId = MSG_MULTI;
             // Set MSG_MULTI string/float counts
             if (!anncename && !infoname && !centername)
             {
                 string typestring = Get_Notif_TypeName(typeId);
                 LOG_INFOF(
                     (
                         "^1NOTIFICATION WITH NO SUBCALLS: "
                         "^7net_type = %s, net_name = %s."
                     ),
                     typestring,
                     namestring
                 );
                 notif_error = true;
             }
             else
             {
                 // announcements don't actually need any arguments, so lets not even count them.
                 if (anncename) { notif.nent_msgannce = anncename; }
                 float infoname_stringcount = 0, infoname_floatcount = 0;
                 float centername_stringcount = 0, centername_floatcount = 0;
                 if (infoname)
                 {
                     notif.nent_msginfo = infoname;
                     infoname_stringcount = notif.nent_msginfo.nent_stringcount;
                     infoname_floatcount = notif.nent_msginfo.nent_floatcount;
                 }
                 if (centername)
                 {
                     notif.nent_msgcenter = centername;
                     centername_stringcount = notif.nent_msgcenter.nent_stringcount;
                     centername_floatcount = notif.nent_msgcenter.nent_floatcount;
                 }
                 // set the requirements of THIS notification to the totals of its subcalls
                 notif.nent_stringcount = max(infoname_stringcount, centername_stringcount);
                 notif.nent_floatcount = max(infoname_floatcount, centername_floatcount);
             }
         }
void Destroy_All_Notifications ()
Definition at line 156 of file all.qc.
References CPID_Null, Destroy_Notification_Entity(), FOREACH, NULL, and reset_centerprint_messages().
Referenced by GenericCommand_restartnotifs().
 {
     // kill all networked notifications and centerprints
     #ifdef SVQC
     Kill_Notification(NOTIF_ALL, NULL, MSG_Null, CPID_Null);
     #else
     reset_centerprint_messages();
     #endif
     // kill all real notification entities
     FOREACH(Notifications, true, { Destroy_Notification_Entity(it); });
 }
void Dump_Notifications (int fh, bool alsoprint)
used to output notifications.cfg file
Definition at line 778 of file all.qc.
References FOREACH, and NOTIF_WRITE.
Referenced by GENERIC_COMMAND().
 {
     #define NOTIF_WRITE(str) write_String_To_File(fh, str, alsoprint)
     #define NOTIF_WRITE_ENTITY(e, description) \
         NOTIF_WRITE(sprintf( \
             "seta notification_%s \"%d\" \"%s\"\n", \
             Get_Notif_CvarName(e), e.nent_default, description \
         ))
     #define NOTIF_WRITE_ENTITY_CHOICE(e, descriptiona, descriptionb) \
         NOTIF_WRITE(sprintf( \
             "seta notification_%s \"%d\" \"%s\"\n" \
             "seta notification_%s_ALLOWED \"%d\" \"%s\"\n", \
             Get_Notif_CvarName(e), e.nent_default, descriptiona, \
             Get_Notif_CvarName(e), e.nent_challow_def, descriptionb \
         ))
     #define NOTIF_WRITE_HARDCODED(cvar, default, description) \
         NOTIF_WRITE("seta notification_" cvar " \"" default "\" \"" description "\"\n")
     // Note: This warning only applies to the notifications.cfg file that is output...
     // You ARE supposed to manually edit this function to add i.e. hard coded
     // notification variables for mutators or game modes or such and then
     // regenerate the notifications.cfg file from the new code.
     NOTIF_WRITE(
         "// ********************************************** //\n"
         "// ** WARNING - DO NOT MANUALLY EDIT THIS FILE ** //\n"
         "// **                                          ** //\n"
         "// **  This file is automatically generated    ** //\n"
         "// **  by code with the command 'dumpnotifs'.  ** //\n"
         "// **                                          ** //\n"
         "// **  If you add a new notification, please   ** //\n"
         "// **  regenerate this file with that command  ** //\n"
         "// **  making sure that the output matches     ** //\n"
         "// **  with the lists and defaults in code.    ** //\n"
         "// **                                          ** //\n"
         "// ********************************************** //\n");
     // These notifications will also append their string as a comment...
     // This is not necessary, and does not matter if they vary between config versions,
     // it is just a semi-helpful tool for those who want to manually change their user settings.
     int NOTIF_ANNCE_COUNT = 0;
     int NOTIF_INFO_COUNT = 0;
     int NOTIF_CENTER_COUNT = 0;
     int NOTIF_MULTI_COUNT = 0;
     int NOTIF_CHOICE_COUNT = 0;
     FOREACH(Notifications, true, {
         switch (it.nent_type)
         {
             case MSG_ANNCE: ++NOTIF_ANNCE_COUNT; break;
             case MSG_INFO: ++NOTIF_INFO_COUNT; break;
             case MSG_CENTER: ++NOTIF_CENTER_COUNT; break;
             case MSG_MULTI: ++NOTIF_MULTI_COUNT; break;
             case MSG_CHOICE: ++NOTIF_CHOICE_COUNT; break;
         }
     });
     NOTIF_WRITE(sprintf("\n// MSG_ANNCE notifications (count = %d):\n", NOTIF_ANNCE_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_ANNCE && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = disabled, 1 = enabled if gentle mode is off, 2 = always enabled"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_INFO notifications (count = %d):\n", NOTIF_INFO_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_INFO && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = off, 1 = print to console, "
             "2 = print to console and chatbox (if notification_allow_chatboxprint is enabled)"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_CENTER notifications (count = %d):\n", NOTIF_CENTER_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_CENTER && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = off, 1 = centerprint"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_MULTI notifications (count = %d):\n", NOTIF_MULTI_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_MULTI && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "Enable this multiple notification"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_CHOICE notifications (count = %d):\n", NOTIF_CHOICE_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_CHOICE && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY_CHOICE(it,
             "Choice for this notification 0 = off, 1 = default message, 2 = verbose message",
             "Allow choice for this notification 0 = off, 1 = only in warmup mode, 2 = always"
         );
     });
     // edit these to match whichever cvars are used for specific notification options
     NOTIF_WRITE("\n// HARD CODED notification variables:\n");
     NOTIF_WRITE_HARDCODED(
         "allow_chatboxprint", "1",
         "Allow INFO notifications to be printed to chat box "
         "0 = do not allow, "
         "1 = allow only if allowed by individual notification_INFO* cvars, "
         "2 = force all INFO notifications to be printed to the chatbox"
     );
     NOTIF_WRITE_HARDCODED(
         "debug", "0",
         "Print extra debug information on all notification function calls "
         "(Requires -DNOTIFICATIONS_DEBUG flag to be enabled on QCSRC compilation)... "
         "0 = disabled, 1 = dprint, 2 = print"
     );
     NOTIF_WRITE_HARDCODED(
         "errors_are_fatal", "1",
         "If a notification fails upon initialization, cause a Host_Error to stop the program"
     );
     NOTIF_WRITE_HARDCODED(
         "item_centerprinttime", "1.5",
         "How long to show item information centerprint messages (like 'You got the Electro' or such)"
     );
     NOTIF_WRITE_HARDCODED(
         "lifetime_mapload", "10",
         "Amount of time that notification entities last immediately at mapload (in seconds) "
         "to help prevent notifications from being lost on early init (like gamestart countdown)"
     );
     NOTIF_WRITE_HARDCODED(
         "lifetime_runtime", "0.5",
         "Amount of time that notification entities last on the server during runtime (In seconds)"
     );
     NOTIF_WRITE_HARDCODED(
         "server_allows_location", "1",
         "Server side cvar for allowing death messages to show location information too"
     );
     NOTIF_WRITE_HARDCODED(
         "show_location", "0",
         "Append location information to MSG_INFO death/kill messages"
     );
     NOTIF_WRITE_HARDCODED(
         "show_location_string", "",
         "Replacement string piped into sprintf, "
         "so you can do different messages like this: ' at the %s' or ' (near %s)'"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees", "1",
         "Print information about sprees in death/kill messages"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_center", "1",
         "Show spree information in MSG_CENTER messages... "
         "0 = off, 1 = target (but only for first victim) and attacker"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_center_specialonly", "1",
         "Don't show spree information in MSG_CENTER messages if it isn't an achievement"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info", "3",
         "Show spree information in MSG_INFO messages... "
         "0 = off, 1 = target only, 2 = attacker only, 3 = target and attacker"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info_newline", "1",
         "Show attacker spree information for MSG_INFO messages on a separate line than the death notification itself"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info_specialonly", "1",
         "Don't show attacker spree information in MSG_INFO messages if it isn't an achievement"
     );
     NOTIF_WRITE(sprintf(
         (
             "\n// Notification counts (total = %d): "
             "MSG_ANNCE = %d, MSG_INFO = %d, MSG_CENTER = %d, MSG_MULTI = %d, MSG_CHOICE = %d\n"
         ),
         (
             NOTIF_ANNCE_COUNT +
             NOTIF_INFO_COUNT +
             NOTIF_CENTER_COUNT +
             NOTIF_MULTI_COUNT +
             NOTIF_CHOICE_COUNT
         ),
         NOTIF_ANNCE_COUNT,
         NOTIF_INFO_COUNT,
         NOTIF_CENTER_COUNT,
         NOTIF_MULTI_COUNT,
         NOTIF_CHOICE_COUNT
     ));
     #undef NOTIF_WRITE_HARDCODED
     #undef NOTIF_WRITE_ENTITY
     #undef NOTIF_WRITE
 }
GENERIC_COMMAND (dumpnotifs , "Dump all notifications into notifications_dump.txt")
Definition at line 163 of file all.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, Dump_Notifications(), fclose(), FILE_WRITE, fopen(), LOG_INFO, and LOG_INFOF.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             #ifdef GAMEQC
             string filename = argv(1);
             bool alsoprint = false;
             if (filename == "")
             {
                 filename = "notifications_dump.cfg";
                 alsoprint = false;
             }
             else if (filename == "-")
             {
                 filename = "notifications_dump.cfg";
                 alsoprint = true;
             }
             int fh = fopen(filename, FILE_WRITE);
             if (fh >= 0)
             {
                 Dump_Notifications(fh, alsoprint);
                 LOG_INFOF("Dumping notifications... File located in ^2data/data/%s^7.", filename);
                 fclose(fh);
             }
             else
             {
                 LOG_INFOF("^1Error: ^7Could not open file '%s'!", filename);
             }
             #else
             LOG_INFO(_("Notification dump command only works with cl_cmd and sv_cmd."));
             #endif
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("Usage:^3 ", GetProgramCommandPrefix(), " dumpnotifs [filename]");
             LOG_INFO("  Where 'filename' is the file to write (default is notifications_dump.cfg),");
             LOG_INFO("  if supplied with '-' output to console as well as default,");
             LOG_INFO("  if left blank, it will only write to default.");
             return;
         }
     }
 }
string Get_Notif_CvarName (Notification notif)
Definition at line 718 of file all.qh.
References Static_Team_ColorName(), strlen(), and substring().
Referenced by Local_Notification().
 {
     if(!notif.nent_teamnum)
         return notif.nent_name;
     return substring(notif.nent_name, 0, -strlen(Static_Team_ColorName(notif.nent_teamnum)) - 2);
 }
Notification Get_Notif_Ent (MSG net_type, int net_name)
Definition at line 725 of file all.qh.
References Get_Notif_TypeName(), LOG_WARNF, and NULL.
 {
     Notification it = _Notifications_from(net_name, NULL);
     if (it.nent_type != net_type) {
         LOG_WARNF("Get_Notif_Ent(%s (%d), %s (%d)): Improper net type '%s'!",
             Get_Notif_TypeName(net_type), net_type,
             it.registered_id, net_name,
             Get_Notif_TypeName(it.nent_type)
         );
         return NULL;
     }
     return it;
 }
string Get_Notif_TypeName (MSG net_type)
main types/groups of notifications
"Global" AND "personal" announcer messages "Global" information messages "Personal" centerprint messages Subcall MSG_INFO and/or MSG_CENTER notifications Choose which subcall wrapper to activate Kill centerprint message
Deprecated:
Definition at line 31 of file all.qh.
References LOG_WARNF, and ORDINAL.
Referenced by Create_Notification_Entity_Annce(), Create_Notification_Entity_Choice(), Create_Notification_Entity_InfoCenter(), Create_Notification_Entity_Multi(), Get_Notif_Ent(), and Local_Notification().
 {
     switch (net_type)
     {
         case MSG_ANNCE: return "MSG_ANNCE";
         case MSG_INFO: return "MSG_INFO";
         case MSG_CENTER: return "MSG_CENTER";
         case MSG_MULTI: return "MSG_MULTI";
         case MSG_CHOICE: return "MSG_CHOICE";
     }
     LOG_WARNF("Get_Notif_TypeName(%d): Improper net type!", ORDINAL(net_type));
     return "";
 }
void Local_Notification (MSG net_type, Notification net_name, count)
Definition at line 1182 of file all.qc.
References backtrace, count, cvar(), entity(), float(), Get_Notif_CvarName(), Get_Notif_TypeName(), Local_Notification_sprintf(), Local_Notification_WOVA(), LOG_WARNF, MakeConsoleSafe(), print(), strzone(), substring(), and warmup_stage.
Referenced by Announcer_Countdown(), Announcer_Gamestart(), Local_Notification_WOVA(), and NET_HANDLE().
 {
     // retreive entity of this notification
     entity notif = net_name;
     if (!notif)
     {
         #ifdef NOTIFICATIONS_DEBUG
         Debug_Notification(sprintf(
             "Local_Notification(%s, NULL, ...);\n",
             Get_Notif_TypeName(net_type)
         ));
         #endif
         LOG_WARNF("Incorrect usage of Local_Notification: %s", "Null notification");
         return;
     }
     // check if the notification is enabled
     if (!notif.nent_enabled)
     {
         #ifdef NOTIFICATIONS_DEBUG
         Debug_Notification(sprintf(
             "Local_Notification(%s, %s, ...): Entity was disabled...\n",
             Get_Notif_TypeName(net_type),
             notif.nent_name
         ));
         #endif
         return;
     }
     string s1 = CCR((notif.nent_stringcount > 0) ? ...(0, string) : "");
     string s2 = CCR((notif.nent_stringcount > 1) ? ...(1, string) : "");
     string s3 = CCR((notif.nent_stringcount > 2) ? ...(2, string) : "");
     string s4 = CCR((notif.nent_stringcount > 3) ? ...(3, string) : "");
     float f1 =  ((notif.nent_floatcount  > 0) ? ...((notif.nent_stringcount + 0), float) : 0);
     float f2 =  ((notif.nent_floatcount  > 1) ? ...((notif.nent_stringcount + 1), float) : 0);
     float f3 =  ((notif.nent_floatcount  > 2) ? ...((notif.nent_stringcount + 2), float) : 0);
     float f4 =  ((notif.nent_floatcount  > 3) ? ...((notif.nent_stringcount + 3), float) : 0);
     #ifdef NOTIFICATIONS_DEBUG
     Debug_Notification(sprintf(
         "Local_Notification(%s, %s, %s, %s);\n",
         Get_Notif_TypeName(net_type),
         notif.nent_name,
         MakeConsoleSafe(sprintf("'%s^7', '%s^7', '%s^7', '%s^7'", s1, s2, s3, s4)),
         sprintf("%d, %d, %d, %d", f1, f2, f3, f4)
     ));
     #endif
     if ((notif.nent_stringcount + notif.nent_floatcount) != count)
     {
         backtrace(sprintf(
             (
                 "Arguments mismatch for Local_Notification(%s, %s, ...)! "
                 "stringcount(%d) + floatcount(%d) != count(%d)\n"
                 "Check the definition and function call for accuracy...?\n"
             ),
             Get_Notif_TypeName(net_type),
             notif.nent_name,
             notif.nent_stringcount,
             notif.nent_floatcount,
             count
         ));
         return;
     }
     switch (net_type)
     {
         case MSG_ANNCE:
         {
             #ifdef CSQC
             Local_Notification_sound(notif.nent_channel, notif.nent_snd, notif.nent_vol, notif.nent_position);
             #else
             backtrace("MSG_ANNCE on server?... Please notify Samual immediately!\n");
             #endif
             break;
         }
         case MSG_INFO:
         {
             print(
                 Local_Notification_sprintf(
                     notif.nent_string,
                     notif.nent_args,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4)
             );
             #ifdef CSQC
             if (notif.nent_icon != "")
             {
                 if (notif.nent_iconargs != "")
                 {
                     string s = Local_Notification_sprintf(
                         notif.nent_icon,notif.nent_iconargs,
                         s1, s2, s3, s4, f1, f2, f3, f4);
                     // remove the trailing newline
                     notif.nent_icon = strzone(substring(s, 0, -1));
                 }
                 Local_Notification_HUD_Notify_Push(
                     notif.nent_icon,
                     notif.nent_hudargs,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #endif
             break;
         }
         #ifdef CSQC
         case MSG_CENTER:
         {
             Local_Notification_centerprint_generic(
                 Local_Notification_sprintf(
                     notif.nent_string,
                     notif.nent_args,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4),
                 notif.nent_durcnt,
                 notif.nent_cpid,
                 f1, f2);
             break;
         }
         #endif
         case MSG_MULTI:
         {
             if (notif.nent_msginfo && notif.nent_msginfo.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_INFO,
                     notif.nent_msginfo,
                     notif.nent_msginfo.nent_stringcount,
                     notif.nent_msginfo.nent_floatcount,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #ifdef CSQC
             if (notif.nent_msgannce && notif.nent_msgannce.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_ANNCE,
                     notif.nent_msgannce,
                     0, 0,
                     "", "", "", "",
                     0, 0, 0, 0);
             }
             if (notif.nent_msgcenter && notif.nent_msgcenter.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_CENTER,
                     notif.nent_msgcenter,
                     notif.nent_msgcenter.nent_stringcount,
                     notif.nent_msgcenter.nent_floatcount,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #endif
             break;
         }
         case MSG_CHOICE:
         {
             entity found_choice = notif.nent_optiona;
             if (notif.nent_challow_var && (warmup_stage || (notif.nent_challow_var == 2))) {
                 switch (cvar(sprintf("notification_%s", Get_Notif_CvarName(notif))))
                 {
                     case 1: break;
                     case 2: found_choice = notif.nent_optionb; break;
                     default: return; // not enabled anyway
                 }
             }
             Local_Notification_WOVA(
                 found_choice.nent_type,
                 found_choice,
                 found_choice.nent_stringcount,
                 found_choice.nent_floatcount,
                 s1, s2, s3, s4,
                 f1, f2, f3, f4);
         }
     }
 }
void Local_Notification_WOVA (MSG net_type, Notification net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
glue for networking, forwards to Local_Notification
Definition at line 1365 of file all.qc.
References EIGHT_VARS_TO_VARARGS_VARLIST, and Local_Notification().
Referenced by Local_Notification().
 {
     #define VARITEM(stringc, floatc, args) \
         if ((stringcount == stringc) && (floatcount == floatc)) \
         { Local_Notification(net_type, net_name, args); return; }
     EIGHT_VARS_TO_VARARGS_VARLIST
     #undef VARITEM
     Local_Notification(net_type, net_name); // some notifications don't have any arguments at all
 }
string notif_arg_item_wepammo (float f1, float f2)
Definition at line 628 of file all.qh.
References Weapon::ammo_type, RES_BULLETS, RES_CELLS, RES_FUEL, RES_PLASMA, RES_ROCKETS, RES_SHELLS, and Weapons_from.
 {
     string ammoitems = "";
     Weapon wep = Weapons_from(f1);
     switch (wep.ammo_type)
     {
         case RES_SHELLS:  ammoitems = ITEM_Shells.m_name;      break;
         case RES_BULLETS: ammoitems = ITEM_Bullets.m_name;     break;
         case RES_ROCKETS: ammoitems = ITEM_Rockets.m_name;     break;
         case RES_CELLS:   ammoitems = ITEM_Cells.m_name;       break;
         case RES_PLASMA:  ammoitems = ITEM_Plasma.m_name;      break;
         case RES_FUEL:    ammoitems = ITEM_JetpackFuel.m_name; break;
         default: return ""; // doesn't use ammo
     }
     return sprintf(_(" with %d %s"), f2, ammoitems);
 }
string notif_arg_spree_inf (float type, string input, string player, float spree)
Definition at line 531 of file all.qh.
References KILL_SPREE_LIST, and substring().
 {
     switch(type)
     {
         case 1: // attacker kill spree
         {
             // 0 = off, 1 = target only, 2 = attacker only, 3 = target and attacker
             // this conditional (& 2) is true for 2 and 3
             if(autocvar_notification_show_sprees_info & 2)
             {
                 #ifdef CSQC
                 string spree_newline =
                     ( autocvar_notification_show_sprees_info_newline ?
                         ((substring(input, 0, 1) == "\{3}") ? "\n\{3}" : "\n") : "" );
                 #else
                 string spree_newline =
                     (autocvar_notification_show_sprees_info_newline ? "\n" : "");
                 #endif
                 if(spree > 1)
                 {
                     #define SPREE_ITEM(counta,countb,center,normal,gentle) \
                         case counta: { return sprintf(CCR(normal_or_gentle(normal, gentle)), player, spree_newline); }
                     switch(spree)
                     {
                         KILL_SPREE_LIST
                         default:
{
                             if (!autocvar_notification_show_sprees_info_specialonly)
{
                                 return
                                     sprintf(
                                         CCR(normal_or_gentle(
                                             _("%s^K1 has %d frags in a row! %s^BG"),
                                             _("%s^K1 made %d scores in a row! %s^BG")
                                         )),
                                         player,
                                         spree,
                                         spree_newline
                                     );
                             }
                             else { return ""; } // don't show spree information if it isn't an achievement
                         }
                     }
                     #undef SPREE_ITEM
                 }
                 else if(spree == -1) // firstblood
                 {
                     return
                         sprintf(
                             CCR(normal_or_gentle(
                                 _("%s^K1 drew first blood! %s^BG"),
                                 _("%s^K1 got the first score! %s^BG")
                             )),
                             player,
                             spree_newline
                         );
                 }
             }
             break;
         }
         case -1: // kill spree ended
         {
             if((spree > 1) && (autocvar_notification_show_sprees_info & 1))
             {
                 return
                     sprintf(normal_or_gentle(
                         _(", ending their %d frag spree"),
                         _(", ending their %d score spree")
                         ),
                         spree
                     );
             }
             break;
         }
         case -2: // kill spree lost
         {
             if((spree > 1) && (autocvar_notification_show_sprees_info & 1))
             {
                 return
                     sprintf(normal_or_gentle(
                         _(", losing their %d frag spree"),
                         _(", losing their %d score spree")
                         ),
                         spree
                     );
             }
             break;
         }
     }
     return "";
 }
REGISTRY_BEGIN (Notifications)
Definition at line 844 of file all.qh.
References notif_global_error.
 {
     notif_global_error = false;
 }
REGISTRY_END (Notifications)
Definition at line 849 of file all.qh.
References LOG_FATAL, LOG_SEVERE, and notif_global_error.
 {
     if (!notif_global_error) return;
     // shit happened... stop the loading of the program now if this is unacceptable
     if (autocvar_notification_errors_are_fatal)
         LOG_FATAL("Notification initialization failed! Read above and fix the errors!");
     else
         LOG_SEVERE("Notification initialization failed! Read above and fix the errors!");
 }
REGISTRY_SORT (Notifications)
STATIC_INIT (Notifications)
Definition at line 699 of file all.qh.
References FOREACH.
 { FOREACH(Notifications, true, it.m_id = i); }
STATIC_INIT_LATE (Notif_Choices)
Definition at line 710 of file all.qh.
References FOREACH.
{
     int c = 0;
     FOREACH(Notifications, it.nent_type == MSG_CHOICE, { c++; });
     if (c > NOTIF_CHOICE_MAX) {
         LOG_FATALF("Too many MSG_CHOICE notifications (%d)", c);
     }
 }
Variable Documentation
const float ARG_CS = 4
Definition at line 390 of file all.qh.
const float ARG_CS_SV = 3
Definition at line 389 of file all.qh.
const float ARG_CS_SV_DC = 2
Definition at line 388 of file all.qh.
const float ARG_CS_SV_HA = 1
Definition at line 387 of file all.qh.
const float ARG_DC = 6
Definition at line 392 of file all.qh.
string arg_slot[NOTIF_MAX_ARGS]
Definition at line 385 of file all.qh.
Referenced by Local_Notification_sprintf().
const float ARG_SV = 5
Definition at line 391 of file all.qh.
float autocvar_notification_allow_chatboxprint = 0
Definition at line 320 of file all.qh.
Referenced by Process_Notif_Line().
float autocvar_notification_errors_are_fatal = true
Definition at line 306 of file all.qh.
float autocvar_notification_item_centerprinttime = 1.5
Definition at line 316 of file all.qh.
float autocvar_notification_show_location = false
Definition at line 300 of file all.qh.
string autocvar_notification_show_location_string = ""
Definition at line 301 of file all.qh.
float autocvar_notification_show_sprees = true
Definition at line 302 of file all.qh.
float autocvar_notification_show_sprees_center = true
Definition at line 322 of file all.qh.
float autocvar_notification_show_sprees_center_specialonly = true
Definition at line 323 of file all.qh.
float autocvar_notification_show_sprees_info = 3
Definition at line 303 of file all.qh.
float autocvar_notification_show_sprees_info_newline = true
Definition at line 304 of file all.qh.
float autocvar_notification_show_sprees_info_specialonly = true
Definition at line 305 of file all.qh.
int msg_choice_choices[NOTIF_CHOICE_MAX]
Definition at line 705 of file all.qh.
string nent_args
Definition at line 666 of file all.qh.
float nent_challow_def
Definition at line 679 of file all.qh.
float nent_challow_var
Definition at line 680 of file all.qh.
int nent_channel
Definition at line 660 of file all.qh.
int nent_choice_count = 0
Definition at line 703 of file all.qh.
int nent_choice_idx
Definition at line 704 of file all.qh.
entity nent_client
Definition at line 688 of file all.qh.
CPID nent_cpid
Definition at line 669 of file all.qh.
int nent_default
Definition at line 651 of file all.qh.
string nent_durcnt
Definition at line 670 of file all.qh.
bool nent_enabled
Definition at line 652 of file all.qh.
int nent_floatcount
Definition at line 656 of file all.qh.
float nent_floats[4]
Definition at line 692 of file all.qh.
string nent_hudargs
Definition at line 667 of file all.qh.
string nent_icon
Definition at line 668 of file all.qh.
string nent_iconargs
Definition at line 776 of file all.qh.
entity nent_msgannce
Definition at line 674 of file all.qh.
entity nent_msgcenter
Definition at line 676 of file all.qh.
entity nent_msginfo
Definition at line 675 of file all.qh.
string nent_name
Definition at line 654 of file all.qh.
float nent_net_name
Definition at line 690 of file all.qh.
MSG nent_net_type
Definition at line 689 of file all.qh.
entity nent_optiona
Definition at line 681 of file all.qh.
entity nent_optionb
Definition at line 682 of file all.qh.
float nent_position
Definition at line 663 of file all.qh.
string nent_snd
Definition at line 661 of file all.qh.
string nent_string
Definition at line 671 of file all.qh.
int nent_stringcount
Definition at line 655 of file all.qh.
string nent_strings[4]
Definition at line 691 of file all.qh.
int nent_teamnum
Definition at line 657 of file all.qh.
MSG nent_type
Definition at line 653 of file all.qh.
float nent_vol
Definition at line 662 of file all.qh.
const int NOTIF_CHOICE_MAX = 50
Definition at line 702 of file all.qh.
bool notif_error
Definition at line 707 of file all.qh.
Referenced by Create_Notification_Entity(), Create_Notification_Entity_Annce(), Create_Notification_Entity_Choice(), Create_Notification_Entity_InfoCenter(), Create_Notification_Entity_Multi(), Process_Notif_Args(), and Process_Notif_Line().
bool notif_global_error
Definition at line 708 of file all.qh.
Referenced by Create_Notification_Entity(), REGISTRY_BEGIN(), and REGISTRY_END().
const float NOTIF_MAX_ARGS = 7
Definition at line 381 of file all.qh.
Referenced by Local_Notification_sprintf(), and Process_Notif_Args().
const float NOTIF_MAX_DURCNT = 2
Definition at line 383 of file all.qh.
Referenced by Process_Notif_Args().
const float NOTIF_MAX_HUDARGS = 2
Definition at line 382 of file all.qh.
Referenced by Process_Notif_Args().