Xonotic: common/monsters/monster.qh File Reference
monster.qh File Reference
Classes
class Monster
Functions
bool (int, entity actor, entity targ,.entity weaponentity) monster_attackfunc
Variables
vector anim_blockend
vector anim_blockstart
vector anim_melee1
vector anim_melee2
vector anim_melee3
vector anim_spawn
vector anim_walk
const int MON_FLAG_CRUSH = BIT(11)
const int MON_FLAG_HIDDEN = BIT(16)
const int MON_FLAG_MELEE = BIT(10)
const int MON_FLAG_RANGED = BIT(9)
const int MON_FLAG_RIDE = BIT(12)
const int MON_FLAG_SUPERMONSTER = BIT(8)
const int MONSTER_RESPAWN_DEATHPOINT = BIT(4)
const int MONSTER_SIZE_BROKEN = BIT(7)
const int MONSTER_SIZE_QUAKE = BIT(13)
const int MONSTER_TYPE_FLY = BIT(5)
const int MONSTER_TYPE_PASSIVE = BIT(14)
const int MONSTER_TYPE_SWIM = BIT(6)
const int MONSTER_TYPE_UNDEAD = BIT(15)
entity monsterdef
Function Documentation
bool()
bool (int , entity actor, entity targ, .entity weaponentity)
Variable Documentation
anim_blockend
vector anim_blockend
Definition at line 23 of file monster.qh.
anim_blockstart
vector anim_blockstart
Definition at line 24 of file monster.qh.
anim_melee1
vector anim_melee1
Definition at line 25 of file monster.qh.
anim_melee2
vector anim_melee2
Definition at line 26 of file monster.qh.
anim_melee3
vector anim_melee3
Definition at line 27 of file monster.qh.
anim_spawn
vector anim_spawn
Definition at line 29 of file monster.qh.
anim_walk
vector anim_walk
Definition at line 28 of file monster.qh.
Referenced by Monster_Move(), Monster_Move_2D(), and monsters_animoverride().
MON_FLAG_CRUSH
const int MON_FLAG_CRUSH = BIT(11)
Definition at line 11 of file monster.qh.
MON_FLAG_HIDDEN
const int MON_FLAG_HIDDEN = BIT(16)
Definition at line 16 of file monster.qh.
Referenced by getmonsterlist(), invasion_PickMonster(), and spawnmonster().
MON_FLAG_MELEE
const int MON_FLAG_MELEE = BIT(10)
Definition at line 10 of file monster.qh.
MON_FLAG_RANGED
const int MON_FLAG_RANGED = BIT(9)
Definition at line 9 of file monster.qh.
Referenced by Monster_ValidTarget().
MON_FLAG_RIDE
const int MON_FLAG_RIDE = BIT(12)
Definition at line 12 of file monster.qh.
MON_FLAG_SUPERMONSTER
const int MON_FLAG_SUPERMONSTER = BIT(8)
Definition at line 8 of file monster.qh.
Referenced by Invasion_CheckWinner(), invasion_PickMonster(), and MUTATOR_HOOKFUNCTION().
MONSTER_RESPAWN_DEATHPOINT
const int MONSTER_RESPAWN_DEATHPOINT = BIT(4)
Definition at line 4 of file monster.qh.
Referenced by Monster_Dead_Fade().
MONSTER_SIZE_BROKEN
const int MONSTER_SIZE_BROKEN = BIT(7)
Definition at line 7 of file monster.qh.
Referenced by Monster_Spawn().
MONSTER_SIZE_QUAKE
const int MONSTER_SIZE_QUAKE = BIT(13)
Definition at line 13 of file monster.qh.
Referenced by invasion_PickMonster(), and Monster_Spawn().
MONSTER_TYPE_FLY
const int MONSTER_TYPE_FLY = BIT(5)
Definition at line 5 of file monster.qh.
Referenced by invasion_PickMonster(), and Monster_Spawn().
MONSTER_TYPE_PASSIVE
const int MONSTER_TYPE_PASSIVE = BIT(14)
Definition at line 14 of file monster.qh.
Referenced by invasion_PickMonster(), and spawnmonster().
MONSTER_TYPE_SWIM
const int MONSTER_TYPE_SWIM = BIT(6)
Definition at line 6 of file monster.qh.
Referenced by invasion_PickMonster(), and Monster_Spawn().
MONSTER_TYPE_UNDEAD
const int MONSTER_TYPE_UNDEAD = BIT(15)
Definition at line 15 of file monster.qh.
Referenced by invasion_PickMonster().
monsterdef
entity monsterdef
Definition at line 20 of file monster.qh.
Referenced by Monster_Appear(), Monster_Appear_Check(), Monster_Damage(), Monster_Dead(), Monster_Respawn(), Monster_Sounds_Precache(), Monster_Spawn(), Monster_Spawn_Setup(), Monster_Think(), Monster_UpdateModel(), and Monster_ValidTarget().