Xonotic: common/viewloc.qc File Reference
viewloc.qc File Reference
#include "viewloc.qh"
#include "util.qh"
Functions
void viewloc_PlayerPhysics (entity this)
Function Documentation
void viewloc_PlayerPhysics (entity this)
Definition at line 13 of file viewloc.qc.
References BIT, FL_DUCKED, flags, input_buttons, normalize(), PHYS_INPUT_BUTTON_CROUCH, time, vectoangles(), vector(), viewloc, VIEWLOC_FREEAIM, and VIEWLOC_FREEMOVE.
Referenced by sys_phys_update().
 {
     if(this.viewloc)
     {
         if(this.viewloc.goalentity == this.viewloc.enemy)
             return; // we can't side-scroll in this case
         vector old_movement = PHYS_CS(this).movement;
         PHYS_CS(this).movement_x = old_movement_y;
         if((this.viewloc.spawnflags & VIEWLOC_FREEMOVE) && !(time < this.ladder_time))
             PHYS_CS(this).movement_y = old_movement_x;
         else
             PHYS_CS(this).movement_y = 0;
         vector level_start, level_end;
         level_start = this.viewloc.enemy.origin;
         level_end = this.viewloc.goalentity.origin;
         vector forward = vectoangles(normalize(level_end - level_start));
         vector backward = vectoangles(normalize(level_start - level_end));
         if((this.viewloc.spawnflags & VIEWLOC_FREEMOVE) && this.angles_y < 0 && !(time < this.ladder_time))
             PHYS_CS(this).movement_y = -PHYS_CS(this).movement_y;
         if(this.viewloc.spawnflags & VIEWLOC_FREEAIM)
         {
             if(this.angles_y > 0)
                 PHYS_CS(this).movement_x = -PHYS_CS(this).movement_x;
         }
         else
         {
             if(PHYS_CS(this).movement_x < 0)
                 PHYS_CS(this).movement_x = -PHYS_CS(this).movement_x;
             if(PHYS_CS(this).movement_x < 0) // left
                 this.angles_y = backward.y;
             if(PHYS_CS(this).movement_x > 0) // right
                 this.angles_y = forward.y;
         }
     #if 0
         //if(!PHYS_INPUT_BUTTON_CROUCH(this) && !IS_DUCKED(this))
         if(!(this.viewloc.spawnflags & VIEWLOC_FREEMOVE))
         {
 #ifdef SVQC
             //PHYS_INPUT_BUTTON_CROUCH(this) = (old_movement_x < 0);
             if (old_movement.x < 0)
                 PHYS_INPUT_BUTTON_CROUCH(this) = true;
 #elif defined(CSQC)
             if (old_movement.x < 0)
             {
                 input_buttons |= BIT(4);
                 this.flags |= FL_DUCKED;
             }
             //else { input_buttons &= ~16; this.flags &= ~FL_DUCKED; }
 #endif
         }
     #endif
     }
 }