Xonotic: menu/xonotic/skinlist.qc File Reference
skinlist.qc File Reference
#include "skinlist.qh"
Functions
entity makeXonoticSkinList ()
void SetSkin_Click (entity btn, entity me)
void XonoticSkinList_configureXonoticSkinList (entity me)
void XonoticSkinList_destroy (entity me)
void XonoticSkinList_doubleClickListBoxItem (entity me, float i, vector where)
void XonoticSkinList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
void XonoticSkinList_getSkins (entity me)
float XonoticSkinList_keyDown (entity me, float scan, float ascii, float shift)
void XonoticSkinList_loadCvars (entity me)
void XonoticSkinList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticSkinList_saveCvars (entity me)
void XonoticSkinList_setSkin (entity me)
string XonoticSkinList_skinParameter (entity me, float i, float key)
Variables
const float SKINPARM_AUTHOR = 2
const float SKINPARM_COUNT = 4
const float SKINPARM_NAME = 0
const float SKINPARM_PREVIEW = 3
const float SKINPARM_TITLE = 1
Function Documentation
entity makeXonoticSkinList ()
Definition at line 9 of file skinlist.qc.
References entity(), and NEW.
Referenced by XonoticUserSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticSkinList);
     me.configureXonoticSkinList(me);
     return me;
 }
void SetSkin_Click (entity btn, entity me)
Definition at line 157 of file skinlist.qc.
Referenced by XonoticUserSettingsTab_fill().
 {
     me.setSkin(me);
 }
void XonoticSkinList_configureXonoticSkinList (entity me)
Definition at line 17 of file skinlist.qc.
 {
     me.configureXonoticListBox(me);
     me.getSkins(me);
     me.loadCvars(me);
 }
void XonoticSkinList_destroy (entity me)
Definition at line 104 of file skinlist.qc.
 {
     buf_del(me.skinlist);
 }
void XonoticSkinList_doubleClickListBoxItem (entity me, float i, vector where)
Definition at line 162 of file skinlist.qc.
References m_play_click_sound(), and MENU_SOUND_EXECUTE.
 {
     m_play_click_sound(MENU_SOUND_EXECUTE);
     me.setSkin(me);
 }
void XonoticSkinList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 127 of file skinlist.qc.
References draw_Fill(), draw_Picture(), draw_Text(), draw_TextShortenToWidth(), draw_TextWidth(), eX, eY, getFadedAlpha(), SKINPARM_AUTHOR, SKINPARM_PREVIEW, and SKINPARM_TITLE.
 {
     string s;
     if(isSelected)
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     else if(isFocused)
     {
         me.focusedItemAlpha = getFadedAlpha(me.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, me.focusedItemAlpha);
     }
     s = me.skinParameter(me, i, SKINPARM_PREVIEW);
     draw_Picture(me.columnPreviewOrigin * eX, s, me.columnPreviewSize * eX + eY, '1 1 1', 1);
     s = me.skinParameter(me, i, SKINPARM_TITLE);
     s = draw_TextShortenToWidth(s, me.columnNameSize, 0, me.realFontSize);
     draw_Text(me.realUpperMargin1 * eY + (me.columnNameOrigin + 0.00 * (me.columnNameSize - draw_TextWidth(s, 0, me.realFontSize))) * eX, s, me.realFontSize, SKINCOLOR_SKINLIST_TITLE, SKINALPHA_TEXT, 0);
     s = me.skinParameter(me, i, SKINPARM_AUTHOR);
     s = draw_TextShortenToWidth(s, me.columnNameSize, 0, me.realFontSize);
     draw_Text(me.realUpperMargin2 * eY + (me.columnNameOrigin + 1.00 * (me.columnNameSize - draw_TextWidth(s, 0, me.realFontSize))) * eX, s, me.realFontSize, SKINCOLOR_SKINLIST_AUTHOR, SKINALPHA_TEXT, 0);
 }
void XonoticSkinList_getSkins (entity me)
Definition at line 50 of file skinlist.qc.
References buf_create, cvar_defstring(), draw_PictureSize(), fclose(), fgets(), FILE_READ, fopen(), LOG_INFO, name, search_begin(), search_end(), search_getfilename(), search_getsize(), SKINPARM_AUTHOR, SKINPARM_COUNT, SKINPARM_NAME, SKINPARM_PREVIEW, SKINPARM_TITLE, strcat(), strlen(), and substring().
 {
     float glob, buf, i, n, fh;
     string s, name;
     buf = buf_create();
     glob = search_begin("gfx/menu/*/skinvalues.txt", true, true);
     if(glob < 0)
     {
         me.skinlist = buf;
         me.nItems = 0;
         return;
     }
     n = search_getsize(glob);
     for(i = 0; i < n; ++i)
     {
         s = search_getfilename(glob, i);
         name = substring(s, 9, strlen(s) - 24); // the * part
         bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_NAME, name);
         bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_TITLE, _("<TITLE>"));
         bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_AUTHOR, _("<AUTHOR>"));
         if(draw_PictureSize(strcat("/gfx/menu/", substring(s, 9, strlen(s) - 24), "/skinpreview")) == '0 0 0')
             bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_PREVIEW, "nopreview_menuskin");
         else
             bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_PREVIEW, strcat("/gfx/menu/", substring(s, 9, strlen(s) - 24), "/skinpreview"));
         fh = fopen(s, FILE_READ);
         if(fh < 0)
         {
             LOG_INFO("Warning: can't open skinvalues.txt file");
             continue;
         }
         while((s = fgets(fh)))
         {
             // these two are handled by skinlist.qc
             if(substring(s, 0, 6) == "title ")
             {
                 if (name == cvar_defstring("menu_skin"))
                     bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_TITLE, strcat(substring(s, 6, strlen(s) - 6), " (", _("Default"), ")"));
                 else
                     bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_TITLE, substring(s, 6, strlen(s) - 6));
             }
             else if(substring(s, 0, 7) == "author ")
                 bufstr_set(buf, i * SKINPARM_COUNT + SKINPARM_AUTHOR, substring(s, 7, strlen(s) - 7));
         }
         fclose(fh);
     }
     search_end(glob);
     me.skinlist = buf;
     me.nItems = n;
 }
float XonoticSkinList_keyDown (entity me, float scan, float ascii, float shift)
Definition at line 168 of file skinlist.qc.
References K_ENTER, K_KP_ENTER, m_play_click_sound(), MENU_SOUND_EXECUTE, and SUPER.
 {
     if(scan == K_ENTER || scan == K_KP_ENTER)
     {
         m_play_click_sound(MENU_SOUND_EXECUTE);
         me.setSkin(me);
         return 1;
     }
     else
         return SUPER(XonoticSkinList).keyDown(me, scan, ascii, shift);
 }
void XonoticSkinList_loadCvars (entity me)
Definition at line 24 of file skinlist.qc.
References cvar_string(), and SKINPARM_NAME.
 {
     string s;
     float i, n;
     s = cvar_string("menu_skin");
     n = me.nItems;
     for(i = 0; i < n; ++i)
     {
         if(me.skinParameter(me, i, SKINPARM_NAME) == s)
         {
             me.setSelected(me, i);
             break;
         }
     }
 }
void XonoticSkinList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 109 of file skinlist.qc.
References SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticSkinList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.itemAbsSize.y = absSize.y * me.itemHeight;
     me.itemAbsSize.x = absSize.x * (1 - me.controlWidth);
     me.realFontSize.y = me.fontSize / me.itemAbsSize.y;
     me.realFontSize.x = me.fontSize / me.itemAbsSize.x;
     me.realUpperMargin1 = 0.5 * (1 - 2.5 * me.realFontSize.y);
     me.realUpperMargin2 = me.realUpperMargin1 + 1.5 * me.realFontSize.y;
     me.columnPreviewOrigin = 0;
     me.columnPreviewSize = me.itemAbsSize.y / me.itemAbsSize.x * 4 / 3;
     me.columnNameOrigin = me.columnPreviewOrigin + me.columnPreviewSize + me.realFontSize.x;
     me.columnNameSize = 1 - me.columnPreviewSize - 2 * me.realFontSize.x;
 }
void XonoticSkinList_saveCvars (entity me)
Definition at line 40 of file skinlist.qc.
References cvar_set(), and SKINPARM_NAME.
 {
     cvar_set("menu_skin", me.skinParameter(me, me.selectedItem, SKINPARM_NAME));
 }
void XonoticSkinList_setSkin (entity me)
Definition at line 151 of file skinlist.qc.
References localcmd.
 {
     me.saveCvars(me);
     localcmd("\nmenu_restart\nmenu_cmd skinselect\n");
 }
string XonoticSkinList_skinParameter (entity me, float i, float key)
Definition at line 45 of file skinlist.qc.
References SKINPARM_COUNT.
 {
     return bufstr_get(me.skinlist, i * SKINPARM_COUNT + key);
 }
Variable Documentation
const float SKINPARM_AUTHOR = 2
Definition at line 5 of file skinlist.qc.
Referenced by XonoticSkinList_drawListBoxItem(), and XonoticSkinList_getSkins().
const float SKINPARM_COUNT = 4
Definition at line 7 of file skinlist.qc.
Referenced by XonoticSkinList_getSkins(), and XonoticSkinList_skinParameter().
const float SKINPARM_NAME = 0
Definition at line 3 of file skinlist.qc.
Referenced by XonoticSkinList_getSkins(), XonoticSkinList_loadCvars(), and XonoticSkinList_saveCvars().
const float SKINPARM_PREVIEW = 3
Definition at line 6 of file skinlist.qc.
Referenced by XonoticSkinList_drawListBoxItem(), and XonoticSkinList_getSkins().
const float SKINPARM_TITLE = 1
Definition at line 4 of file skinlist.qc.
Referenced by XonoticSkinList_drawListBoxItem(), and XonoticSkinList_getSkins().