Xonotic: server/items.qc File Reference
items.qc File Reference
Source file that contains implementation of the functions related to game items.
#include "items.qh"
#include <server/mutators/_mod.qh>
#include <common/weapons/all.qh>
#include <common/mapobjects/subs.qh>
Functions
entity Item_Create (string class_name, vector position, bool no_align)
Creates a new item.
entity Item_CreateLoot (string class_name, vector position, vector vel, float time_to_live)
Creates a loot item.
entity Item_FindDefinition (string class_name)
Returns the item definition corresponding to the given class name.
void Item_Initialize (entity item, string class_name)
Initializes the item according to class name.
bool Item_InitializeLoot (entity item, string class_name, vector position, vector vel, float time_to_live)
Initializes the loot item.
bool Item_IsAllowed (string class_name)
Checks whether the items with the specified class name are allowed to spawn.
bool Item_IsDefinitionAllowed (entity definition)
Checks whether the items with the specified definition are allowed to spawn.
bool Item_IsExpiring (entity item)
Returns whether the item is expiring (i.e.
bool Item_IsLoot (entity item)
Returns whether the item is loot.
void Item_SetExpiring (entity item, bool expiring)
Sets the item expiring status (i.e.
void Item_SetLoot (entity item, bool loot)
Sets the item loot status.
bool Item_ShouldKeepPosition (entity item)
Returns whether item should keep its position or be dropped to the ground.
Variables
bool m_isexpiring
Holds whether strength, shield or superweapon timers expire while this item is on the ground.
bool m_isloot
Holds whether item is loot.
Detailed Description
Source file that contains implementation of the functions related to game items.
Copyright
GNU GPLv2 or any later version.
Definition in file items.qc.
Function Documentation
entity Item_Create (string class_name, vector position, bool no_align)
Creates a new item.
Parameters
[in] class_name Class name of the item.
[in] position Position of the item.
[in] no_align True if item should be placed directly at specified position, false to let it drop to the ground.
Returns
Item on success, NULL otherwise.
Definition at line 45 of file items.qc.
References entity(), Item_Initialize(), NULL, setorigin(), and spawn().
Referenced by RandomItems_ReplaceMapItem().
 {
     entity item = spawn();
     item.classname = class_name;
     item.spawnfunc_checked = true;
     setorigin(item, position);
     item.noalign = no_align;
     Item_Initialize(item, class_name);
     if (wasfreed(item))
     {
         return NULL;
     }
     return item;
 }
entity Item_CreateLoot (string class_name, vector position, vector vel, float time_to_live)
Creates a loot item.
Parameters
[in] class_name Class name of the item.
[in] position Position of the item.
[in] velocity of the item.
[in] time_to_live Amount of time after which the item will disappear.
Returns
Item on success, NULL otherwise.
Definition at line 75 of file items.qc.
References entity(), Item_InitializeLoot(), NULL, and spawn().
Referenced by RandomItems_SpawnLootItem().
 {
     entity item = spawn();
     if (!Item_InitializeLoot(item, class_name, position, vel, time_to_live))
     {
         return NULL;
     }
     return item;
 }
entity Item_FindDefinition (string class_name)
Returns the item definition corresponding to the given class name.
Parameters
[in] class_name Class name to search for.
Returns
Item definition corresponding to the given class name or NULL is not found.
Definition at line 17 of file items.qc.
References FOREACH, and NULL.
Referenced by Item_IsAllowed().
 {
     FOREACH(Items, it.m_canonical_spawnfunc == class_name,
     {
         return it;
     });
     FOREACH(Weapons, it.m_canonical_spawnfunc == class_name,
     {
         return it.m_pickup;
     });
     return NULL;
 }
void Item_Initialize (entity item, string class_name)
Initializes the item according to class name.
Parameters
[in,out] item Item to initialize.
[in] class_name Class name to use.
Returns
No return. This function is useful if you want to set some item properties before initialization.
Definition at line 60 of file items.qc.
References FOREACH, and LOG_FATALF.
Referenced by Item_Create(), Item_InitializeLoot(), MUTATOR_HOOKFUNCTION(), and RandomItems_ReplaceMapItem().
 {
     FOREACH(Weapons, it.m_canonical_spawnfunc == class_name,
     {
         weapon_defaultspawnfunc(item, it);
         return;
     });
     FOREACH(Items, it.m_canonical_spawnfunc == class_name,
     {
         StartItem(item, it);
         return;
     });
     LOG_FATALF("Item_Initialize: Invalid classname: %s", class_name);
 }
bool Item_InitializeLoot (entity item, string class_name, vector position, vector vel, float time_to_live)
Initializes the loot item.
Parameters
[in] class_name Class name of the item.
[in] position Position of the item.
[in] velocity of the item.
[in] time_to_live Amount of time after which the item will disappear.
Returns
True on success, false otherwise. This function is useful if you want to set some item properties before initialization.
Definition at line 86 of file items.qc.
References Item_Initialize(), Item_SetLoot(), setorigin(), SUB_SetFade(), and time.
Referenced by Item_CreateLoot(), ok_DropItem(), and RandomItems_SpawnLootItem().
 {
     item.classname = class_name;
     Item_SetLoot(item, true);
     item.noalign = true;
     setorigin(item, position);
     item.pickup_anyway = true;
     item.spawnfunc_checked = true;
     Item_Initialize(item, class_name);
     if (wasfreed(item))
     {
         return false;
     }
     item.gravity = 1;
     item.velocity = vel;
     SUB_SetFade(item, time + time_to_live, 1);
     return true;
 }
bool Item_IsAllowed (string class_name)
Checks whether the items with the specified class name are allowed to spawn.
Parameters
[in] class_name Item class name to check.
Returns
True items with the specified class name are allowed to spawn, false otherwise.
Definition at line 30 of file items.qc.
References entity(), Item_FindDefinition(), Item_IsDefinitionAllowed(), and NULL.
 {
     entity definition = Item_FindDefinition(class_name);
     if (definition == NULL)
     {
         return false;
     }
     return Item_IsDefinitionAllowed(definition);
 }
bool Item_IsDefinitionAllowed (entity definition)
Checks whether the items with the specified definition are allowed to spawn.
Parameters
[in] definition Item definition to check.
Returns
True items with the specified definition are allowed to spawn, false otherwise.
Definition at line 40 of file items.qc.
References MUTATOR_CALLHOOK.
Referenced by Item_IsAllowed(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), and weapon_defaultspawnfunc().
 {
     return !MUTATOR_CALLHOOK(FilterItemDefinition, definition);
 }
bool Item_IsExpiring (entity item)
Returns whether the item is expiring (i.e.
its strength, shield and superweapon timers expire while it is on the ground).
Parameters
[in] item Item to check.
Returns
True if the item is expiring, false otherwise.
Definition at line 121 of file items.qc.
 {
     return item.m_isexpiring;
 }
bool Item_IsLoot (entity item)
Returns whether the item is loot.
Parameters
[in] item Item to check.
Returns
True if the item is loot, false otherwise.
Definition at line 106 of file items.qc.
Referenced by havocbot_goalrating_items(), havocbot_movetogoal(), isPushable(), MUTATOR_HOOKFUNCTION(), and weapon_defaultspawnfunc().
 {
     return item.m_isloot;
 }
void Item_SetExpiring (entity item, bool expiring)
Sets the item expiring status (i.e.
whether its strength, shield and superweapon timers expire while it is on the ground).
Parameters
[in,out] item Item to adjust.
[in] expiring Whether item is expiring.
Returns
No return.
Definition at line 126 of file items.qc.
References SPAWNFUNC_ITEM.
Referenced by W_ThrowNewWeapon().
 {
     item.m_isexpiring = expiring;
 }
void Item_SetLoot (entity item, bool loot)
Sets the item loot status.
Parameters
[in,out] item Item to adjust.
[in] loot Whether item is loot.
Returns
No return.
Definition at line 111 of file items.qc.
Referenced by Item_InitializeLoot(), monster_dropitem(), and W_ThrowNewWeapon().
 {
     item.m_isloot = loot;
 }
bool Item_ShouldKeepPosition (entity item)
Returns whether item should keep its position or be dropped to the ground.
Parameters
[in] item Item to check.
Returns
True if item should keep its position or false if it should be dropped to the ground.
Definition at line 116 of file items.qc.
Referenced by buff_SpawnReplacement(), MUTATOR_HOOKFUNCTION(), RandomItems_ReplaceMapItem(), and replace_with_insta_cells().
 {
     return item.noalign || (item.spawnflags & 1);
 }
Variable Documentation
bool m_isexpiring
Holds whether strength, shield or superweapon timers expire while this item is on the ground.
Definition at line 15 of file items.qc.
bool m_isloot
Holds whether item is loot.
Definition at line 12 of file items.qc.