Xonotic: MachineGun Class Reference
MachineGun Class Reference
Public Member Functions
ATTRIB (Weapon, m_canonical_spawnfunc, string)
the canonical spawnfunc name
ATTRIB (Weapon, m_model, entity)
M: model MDL_id_ITEM.
ATTRIB (Weapon, m_pickup, entity)
virtual void display ()
virtual void m_spawnfunc_hookreplace ()
control what happens when this weapon is spawned
virtual void wr_aim ()
(SERVER) runs bot aiming code for this weapon
virtual void wr_checkammo1 ()
(SERVER) checks ammo for weapon primary
virtual void wr_checkammo2 ()
(SERVER) checks ammo for weapon second
virtual void wr_config ()
(SERVER) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
virtual void wr_drop ()
(SERVER) the weapon is dropped
virtual void wr_glow ()
(BOTH) weapon specific glow
virtual void wr_gonethink ()
(SERVER) logic to run when weapon is lost
virtual void wr_impacteffect ()
(CLIENT) impact effect for weapon explosion
virtual void wr_init ()
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
virtual void wr_killmessage ()
(SERVER) notification number for kill message (may inspect w_deathtype for details)
virtual void wr_pickup ()
(SERVER) a weapon is picked up
virtual void wr_playerdeath ()
(SERVER) called whenever a player dies
virtual void wr_reload ()
(SERVER) handles reloading for weapon
virtual void wr_resetplayer ()
(SERVER) clears fields that the weapon may use
virtual void wr_setup ()
(SERVER) setup weapon data
virtual void wr_suicidemessage ()
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
virtual void wr_think ()
(SERVER) logic to run every frame
virtual void wr_update ()
(SERVER) update cvar based properties
virtual void wr_viewmodel ()
(CLIENT) weapon specific view model
virtual void wr_zoom ()
(BOTH) weapon specific zoom reticle
virtual void wr_zoomdir ()
(CLIENT) check whether the weapon should zoom (special handling)
Public Attributes
int ammo_type = RES_BULLETS
float bot_pickupbasevalue = 7000
int impulse = 3
string m_canonical_spawnfunc = "weapon_machinegun"
int m_id = 0
string m_name = _("MachineGun")
string mdl = "uzi"
string model2 = "weaponuzi"
string netname = "machinegun"
int spawnflags = WEP_FLAG_NORMAL | WEP_FLAG_RELOADABLE | WEP_TYPE_HITSCAN | WEP_FLAG_PENETRATEWALLS | WEP_FLAG_BLEED
string w_crosshair = "gfx/crosshairuzi"
float w_crosshair_size = 0.6
string w_reticle = string_null
A: reticle : per-weapon zoom reticle.
vector wpcolor = '1 1 0'
Detailed Description
Definition at line 3 of file machinegun.qh.
Member Function Documentation
Weapon::ATTRIB (Weapon , m_canonical_spawnfunc , string) inherited
the canonical spawnfunc name
Weapon::ATTRIB (Weapon , m_model , entity) inherited
M: model MDL_id_ITEM.
Weapon::ATTRIB (Weapon , m_pickup , entity) inherited
virtual void Weapon::display () inline virtual inherited
Definition at line 121 of file weapon.qh.
References cvar_string(), ENDCLASS, entity(), m_name, string_null, and weapon_defaultspawnfunc().
{
         returns(this.m_name, this.model2 ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.model2) : string_null);
     }
virtual void Weapon::m_spawnfunc_hookreplace () inline virtual inherited
control what happens when this weapon is spawned
Definition at line 46 of file weapon.qh.
Referenced by weapon_defaultspawnfunc().
 { return this; }
virtual void Weapon::wr_aim () inline virtual inherited
(SERVER) runs bot aiming code for this weapon
Definition at line 85 of file weapon.qh.
Referenced by havocbot_ai().
 {}
virtual void Weapon::wr_checkammo1 () inline virtual inherited
(SERVER) checks ammo for weapon primary
Definition at line 81 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_checkammo2 () inline virtual inherited
(SERVER) checks ammo for weapon second
Definition at line 83 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_config () inline virtual inherited
(SERVER) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
Definition at line 103 of file weapon.qh.
 {}
virtual void Weapon::wr_drop () inline virtual inherited
(SERVER) the weapon is dropped
Definition at line 116 of file weapon.qh.
 {}
virtual void Weapon::wr_glow () inline virtual inherited
(BOTH) weapon specific glow
Definition at line 114 of file weapon.qh.
Referenced by STATIC_INIT().
 { return '0 0 0'; }
virtual void Weapon::wr_gonethink () inline virtual inherited
(SERVER) logic to run when weapon is lost
Definition at line 101 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_impacteffect () inline virtual inherited
(CLIENT) impact effect for weapon explosion
Definition at line 97 of file weapon.qh.
 {}
virtual void Weapon::wr_init () inline virtual inherited
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
Definition at line 87 of file weapon.qh.
Referenced by GrappleHookInit(), and weapon_defaultspawnfunc().
 {}
virtual void Weapon::wr_killmessage () inline virtual inherited
(SERVER) notification number for kill message (may inspect w_deathtype for details)
Definition at line 91 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_pickup () inline virtual inherited
(SERVER) a weapon is picked up
Definition at line 118 of file weapon.qh.
 {}
virtual void Weapon::wr_playerdeath () inline virtual inherited
(SERVER) called whenever a player dies
Definition at line 99 of file weapon.qh.
Referenced by PlayerDamage().
 {}
virtual void Weapon::wr_reload () inline virtual inherited
(SERVER) handles reloading for weapon
Definition at line 93 of file weapon.qh.
Referenced by IMPULSE(), and W_SwitchWeapon().
 {}
virtual void Weapon::wr_resetplayer () inline virtual inherited
(SERVER) clears fields that the weapon may use
Definition at line 95 of file weapon.qh.
Referenced by GiveBall(), and MUTATOR_HOOKFUNCTION().
 {}
virtual void Weapon::wr_setup () inline virtual inherited
(SERVER) setup weapon data
Definition at line 77 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_suicidemessage () inline virtual inherited
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
Definition at line 89 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 79 of file weapon.qh.
Referenced by MUTATOR_HOOKFUNCTION(), Turret::tr_precache(), and W_WeaponFrame().
 {}
virtual void Weapon::wr_update () inline virtual inherited
(SERVER) update cvar based properties
Definition at line 120 of file weapon.qh.
 {}
virtual void Weapon::wr_viewmodel () inline virtual inherited
(CLIENT) weapon specific view model
Definition at line 112 of file weapon.qh.
References string_null.
Referenced by viewmodel_draw().
 { return string_null; }
virtual void Weapon::wr_zoom () inline virtual inherited
(BOTH) weapon specific zoom reticle
Definition at line 105 of file weapon.qh.
Referenced by DrawReticle(), and PlayerPreThink().
{
         // no weapon specific image for this weapon
         return false;
     }
virtual void Weapon::wr_zoomdir () inline virtual inherited
(CLIENT) check whether the weapon should zoom (special handling)
Definition at line 110 of file weapon.qh.
Referenced by GetCurrentFov().
 {return false;}
Member Data Documentation
int MachineGun::ammo_type = RES_BULLETS
Definition at line 5 of file machinegun.qh.
float MachineGun::bot_pickupbasevalue = 7000
Definition at line 8 of file machinegun.qh.
int MachineGun::impulse = 3
Definition at line 6 of file machinegun.qh.
string MachineGun::m_canonical_spawnfunc = "weapon_machinegun"
Definition at line 4 of file machinegun.qh.
int Weapon::m_id = 0 inherited
Definition at line 42 of file weapon.qh.
Referenced by accuracy_add(), client_hasweapon(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), SpawnThrownWeapon(), TEST(), W_SwitchWeapon(), W_SwitchWeapon_Force(), W_ThrowWeapon(), and weapon_prepareattack_checkammo().
string MachineGun::m_name = _("MachineGun")
Definition at line 18 of file machinegun.qh.
string MachineGun::mdl = "uzi"
Definition at line 10 of file machinegun.qh.
string MachineGun::model2 = "weaponuzi"
Definition at line 16 of file machinegun.qh.
string MachineGun::netname = "machinegun"
Definition at line 17 of file machinegun.qh.
int MachineGun::spawnflags = WEP_FLAG_NORMAL | WEP_FLAG_RELOADABLE | WEP_TYPE_HITSCAN | WEP_FLAG_PENETRATEWALLS | WEP_FLAG_BLEED
Definition at line 7 of file machinegun.qh.
string MachineGun::w_crosshair = "gfx/crosshairuzi"
Definition at line 14 of file machinegun.qh.
float MachineGun::w_crosshair_size = 0.6
Definition at line 15 of file machinegun.qh.
string Weapon::w_reticle = string_null inherited
A: reticle : per-weapon zoom reticle.
Definition at line 66 of file weapon.qh.
Referenced by DrawReticle().
vector MachineGun::wpcolor = '1 1 0'
Definition at line 9 of file machinegun.qh.
The documentation for this class was generated from the following file:
common/weapons/weapon/machinegun.qh