Xonotic: Vehicle Class Reference
Vehicle Class Reference
Public Member Functions
bool (entity) PlayerPhysplug
player physics mod
virtual void describe ()
virtual void display ()
virtual void vr_crosshair ()
(CLIENT) logic to run every frame
virtual void vr_death ()
(SERVER) called when vehicle dies
virtual void vr_enter ()
(SERVER) called when a player enters this vehicle
virtual void vr_gunner_enter ()
(SERVER) called when a player enters this vehicle while occupied
virtual void vr_hud ()
(CLIENT) logic to run every frame
virtual void vr_impact ()
(SERVER) called when a vehicle hits something
virtual void vr_precache ()
(BOTH) precaches models/sounds used by this vehicle
virtual void vr_setup ()
(BOTH) setup vehicle data
virtual void vr_spawn ()
(SERVER) called when the vehicle re-spawns
virtual void vr_think ()
(SERVER) logic to run every frame
Public Attributes
string head_model = ""
full name of tur_head model
float height = 0
vehicle 3rd person view distance
string hud_model = ""
cockpit model
string m_icon = string_null
hud icon
vector maxs = '0 0 0'
vehicle hitbox size
string mdl = ""
currently a copy of the model
vector mins = '-0 -0 -0'
vehicle hitbox size
string model = ""
full name of model
string netname = ""
short name
int spawnflags = 0
string tag_head = string_null
tur_head model tag
string tag_hud = string_null
hud model tag
string tag_view = string_null
cockpit model tag
string vehicle_name = "Vehicle"
human readable name
int vehicleid = 0
vector view_ofs = '0 0 0'
vehicle 3rd person view offset
Detailed Description
Definition at line 4 of file vehicle.qh.
Member Function Documentation
Vehicle::bool (entity)
player physics mod
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Vehicle::vr_crosshair () inline virtual
(CLIENT) logic to run every frame
Definition at line 58 of file vehicle.qh.
Referenced by HUD_Crosshair_Vehicle().
 { }
virtual void Vehicle::vr_death () inline virtual
(SERVER) called when vehicle dies
Definition at line 44 of file vehicle.qh.
Referenced by vehicles_damage().
 { }
virtual void Vehicle::vr_enter () inline virtual
(SERVER) called when a player enters this vehicle
Definition at line 48 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_gunner_enter () inline virtual
(SERVER) called when a player enters this vehicle while occupied
Definition at line 50 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_hud () inline virtual
(CLIENT) logic to run every frame
Definition at line 56 of file vehicle.qh.
Referenced by HUD_Vehicle().
 { }
virtual void Vehicle::vr_impact () inline virtual
(SERVER) called when a vehicle hits something
Definition at line 54 of file vehicle.qh.
Referenced by vehicles_touch().
 { }
virtual void Vehicle::vr_precache () inline virtual
(BOTH) precaches models/sounds used by this vehicle
Definition at line 46 of file vehicle.qh.
Referenced by vehicle_initialize().
 { }
virtual void Vehicle::vr_setup () inline virtual
(BOTH) setup vehicle data
Definition at line 40 of file vehicle.qh.
Referenced by NET_HANDLE(), and vehicle_initialize().
 { }
virtual void Vehicle::vr_spawn () inline virtual
(SERVER) called when the vehicle re-spawns
Definition at line 52 of file vehicle.qh.
Referenced by vehicles_spawn().
 { }
virtual void Vehicle::vr_think () inline virtual
(SERVER) logic to run every frame
Definition at line 42 of file vehicle.qh.
Referenced by vehicles_think().
 { }
Member Data Documentation
string Vehicle::head_model = ""
full name of tur_head model
Definition at line 17 of file vehicle.qh.
Referenced by vehicle_initialize().
float Vehicle::height = 0
vehicle 3rd person view distance
Definition at line 37 of file vehicle.qh.
Referenced by CSQC_UpdateView().
string Vehicle::hud_model = ""
cockpit model
Definition at line 19 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::m_icon = string_null
hud icon
Definition at line 7 of file vehicle.qh.
vector Vehicle::maxs = '0 0 0'
vehicle hitbox size
Definition at line 33 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::mdl = ""
currently a copy of the model
Definition at line 15 of file vehicle.qh.
vector Vehicle::mins = '-0 -0 -0'
vehicle hitbox size
Definition at line 31 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::model = ""
full name of model
Definition at line 13 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::netname = ""
short name
Definition at line 9 of file vehicle.qh.
int Vehicle::spawnflags = 0
Definition at line 29 of file vehicle.qh.
string Vehicle::tag_head = string_null
tur_head model tag
Definition at line 21 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::tag_hud = string_null
hud model tag
Definition at line 23 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::tag_view = string_null
cockpit model tag
Definition at line 25 of file vehicle.qh.
Referenced by vehicle_initialize().
string Vehicle::vehicle_name = "Vehicle"
human readable name
Definition at line 11 of file vehicle.qh.
int Vehicle::vehicleid = 0
Definition at line 5 of file vehicle.qh.
Referenced by vehicle_initialize().
vector Vehicle::view_ofs = '0 0 0'
vehicle 3rd person view offset
Definition at line 35 of file vehicle.qh.
Referenced by CSQC_UpdateView().
The documentation for this class was generated from the following file:
common/vehicles/vehicle.qh