Xonotic: MenuItem Class Reference
MenuItem Class Reference
Public Member Functions
ATTRIB (MenuItem, parent, entity)
ATTRIB (MenuItem, tooltip, string)
virtual void destroy ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void showNotify ()
virtual void toString ()
Public Attributes
float allowFocusSound = 0
float focusable = 0
float focused = 0
vector origin = '0 0 0'
float preferredFocusPriority = 0
vector size = '0 0 0'
Detailed Description
Definition at line 8 of file item.qh.
Member Function Documentation
MenuItem::ATTRIB (MenuItem , parent , entity)
MenuItem::ATTRIB (MenuItem , tooltip , string)
void MenuItem::destroy () virtual
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
void MenuItem::draw () virtual
Reimplemented in ModalController, XonoticColorpickerString, XonoticColorpicker, XonoticPicker, Slider, XonoticResolutionSlider, BorderImage, XonoticPlayerModelSelector, XonoticScreenshotList, Button, XonoticHUDSkinList, XonoticPlayList, XonoticWeaponsList, ListBox, XonoticCampaignList, XonoticSliderCheckBox, XonoticColorButton, XonoticCreditsList, XonoticGametypeList, MainWindow, XonoticMapList, XonoticScreenshotImage, XonoticServerList, CheckBox, Container, Image, InputBox, Label, XonoticCrosshairPreview, XonoticProfileTab, XonoticRadioButton, XonoticPicmipSlider, XonoticTextLabel, and Nexposee.
Definition at line 25 of file item.qc.
References draw_Fill(), fabs(), random(), and vector().
     {
         if (!autocvar_menu_showboxes) return;
         vector rgb = '1 0 1';
         float a = fabs(autocvar_menu_showboxes);
         // don't draw containers and border images
         if (this.instanceOfContainer || this.instanceOfBorderImage)
         {
             rgb = '0 0 0';
             a = 0;
         }
         #if 0
             // hack to detect multi drawing
             float r = random() * 3;
             if (r >= 2) rgb = '1 0 0';
             else if (r >= 1) rgb = '0 1 0';
             else rgb = '0 0 1';
         #endif
         if (autocvar_menu_showboxes < 0)
         {
             draw_Fill('0 0 0', '0.5 0.5 0', rgb, a);
             draw_Fill('0.5 0.5 0', '0.5 0.5 0', rgb, a);
         }
         else if (autocvar_menu_showboxes > 0)
         {
             draw_Fill('0 0 0', '1 1 0', rgb, a);
         }
     }
void MenuItem::focusEnter () virtual
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void MenuItem::focusLeave () virtual
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
void MenuItem::hideNotify () virtual
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
void MenuItem::keyDown () virtual
Reimplemented in Dialog, XonoticLanguageList, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, XonoticPlayList, XonoticSkinList, XonoticColorpicker, XonoticMapList, XonoticGametypeList, XonoticCampaignList, XonoticKeyBinder, XonoticSoundList, Button, Slider, XonoticServerList, XonoticStatsList, XonoticWeaponsList, XonoticCreditsList, XonoticPicker, InputBox, XonoticCvarList, XonoticScreenshotViewerDialog, Container, ListBox, XonoticCharmap, XonoticInputBox, Nexposee, and InputContainer.
Definition at line 62 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::keyUp () virtual
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::mouseDrag () virtual
Reimplemented in XonoticPlayList, Slider, XonoticWeaponsList, Button, InputBox, Container, ListBox, Nexposee, XonoticColorpickerString, XonoticScreenshotImage, InputContainer, XonoticPicker, and XonoticColorpicker.
Definition at line 82 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::mouseMove () virtual
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::mousePress () virtual
Reimplemented in Slider, Button, InputBox, Container, ListBox, XonoticScreenshotImage, Nexposee, XonoticColorpickerString, InputContainer, XonoticColorpicker, and XonoticPicker.
Definition at line 77 of file item.qc.
     {
         return false;  // unhandled
     }
void MenuItem::mouseRelease () virtual
Reimplemented in XonoticCvarList, Slider, Button, Container, ListBox, InputBox, Nexposee, XonoticColorpickerString, InputContainer, XonoticColorpicker, and XonoticPicker.
Definition at line 87 of file item.qc.
References m_play_focus_sound().
     {
         return 0;  // unhandled
     }
void MenuItem::relinquishFocus () virtual
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
void MenuItem::resizeNotify () virtual
Reimplemented in XonoticRegisteredSettingsList, ModalController, XonoticScrollPanel, InputBox, Container, Nexposee, XonoticScreenshotImage, InputContainer, XonoticListBox, XonoticMapList, Button, XonoticCampaignList, XonoticPlayerModelSelector, XonoticServerList, XonoticWeaponsList, XonoticCreditsList, XonoticGametypeList, XonoticKeyBinder, Image, XonoticCvarList, XonoticDemoList, XonoticLanguageList, Label, Slider, XonoticCharmap, XonoticHUDSkinList, XonoticPlayList, XonoticScreenshotList, XonoticSkinList, XonoticSoundList, XonoticStatsList, BorderImage, XonoticPlayerList, and ListBox.
Definition at line 18 of file item.qc.
References origin, and size.
     {
         this.origin = absOrigin;
         this.size = absSize;
     }
void MenuItem::showNotify () virtual
Reimplemented in Container, Slider, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, InputBox, XonoticSoundList, XonoticDamageTextSettings, XonoticStatsList, XonoticPlayerModelSelector, XonoticTab, XonoticCvarList, XonoticKeyBinder, Button, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
Definition at line 56 of file item.qc.
     {}
void MenuItem::toString () virtual
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
Member Data Documentation
float MenuItem::allowFocusSound = 0
Definition at line 26 of file item.qh.
float MenuItem::focusable = 0
Definition at line 25 of file item.qh.
float MenuItem::focused = 0
Definition at line 24 of file item.qh.
vector MenuItem::origin = '0 0 0'
Definition at line 29 of file item.qh.
float MenuItem::preferredFocusPriority = 0
Definition at line 28 of file item.qh.
vector MenuItem::size = '0 0 0'
Definition at line 30 of file item.qh.
The documentation for this class was generated from the following files:
menu/item.qh
menu/item.qc