Xonotic: server/bot/default/bot.qh File Reference
bot.qh File Reference
Macros
#define IN_LAVA(pos) (_content_type = pointcontents(pos), (_content_type == CONTENT_LAVA || _content_type == CONTENT_SLIME))
#define IN_LIQUID(pos) (_content_type = pointcontents(pos), (_content_type == CONTENT_WATER || _content_type == CONTENT_LAVA || _content_type == CONTENT_SLIME))
#define SUBMERGED(pos) IN_LIQUID(pos + autocvar_sv_player_viewoffset)
#define WETFEET(pos) IN_LIQUID(pos + eZ * (m1.z + 1))
Functions
void autoskill (float factor)
void bot_calculate_stepheightvec ()
void bot_clear (entity this)
void bot_clientconnect (entity this)
void bot_clientdisconnect (entity this)
void bot_custom_weapon_priority_setup ()
void bot_endgame ()
bool bot_fixcount ()
void bot_relinkplayerlist ()
void bot_removefromlargestteam ()
void bot_removenewest ()
void bot_serverframe ()
void bot_setnameandstuff (entity this)
entity bot_spawn ()
void bot_think (entity this)
float (entity player, entity item) bot_pickupevalfunc
void (entity this) bot_ai
Variables
int _content_type
const int AI_STATUS_ATTACKING = BIT(1)
const int AI_STATUS_DANGER_AHEAD = BIT(3)
const int AI_STATUS_JETPACK_FLYING = BIT(9)
const int AI_STATUS_JETPACK_LANDING = BIT(10)
const int AI_STATUS_OUT_JUMPPAD = BIT(4)
const int AI_STATUS_OUT_WATER = BIT(5)
const int AI_STATUS_ROAMING = BIT(0)
const int AI_STATUS_RUNNING = BIT(2)
const int AI_STATUS_STUCK = BIT(11)
const int AI_STATUS_WAYPOINT_PERSONAL_GOING = BIT(7)
const int AI_STATUS_WAYPOINT_PERSONAL_LINKING = BIT(6)
const int AI_STATUS_WAYPOINT_PERSONAL_REACHED = BIT(8)
int aistatus
float autoskill_nextthink
float bot_aggresskill
float bot_aimskill
float bot_aiskill
float bot_attack
float bot_canfire
float bot_config_loaded
float bot_distance_close
float bot_distance_far
float bot_dodge
float bot_dodgerating
float bot_dodgeskill
float bot_forced_team
float bot_jump_time
entity bot_list
float bot_mouseskill
float bot_moveskill
float bot_nextthink
float bot_offsetskill
float bot_pickup
bool bot_pickup_respawning
float bot_pickupbasevalue
float bot_pingskill
float bot_preferredcolors
float bot_rangepreference
float bot_strategytime
entity bot_strategytoken
float bot_strategytoken_taken
float bot_thinkskill
float bot_weaponskill
float botframe_nextdangertime
float botframe_nextthink
float botframe_spawnedwaypoints
string cleanname
float createdtime
bool isbot
string netname_freeme
entity nextbot
string playermodel_freeme
string playerskin_freeme
float totalfrags_lastcheck
Macro Definition Documentation
#define IN_LAVA (pos) (_content_type = pointcontents(pos), (_content_type == CONTENT_LAVA || _content_type == CONTENT_SLIME))
Definition at line 81 of file bot.qh.
Referenced by havocbot_goalrating_items(), and tracewalk().
#define IN_LIQUID (pos) (_content_type = pointcontents(pos), (_content_type == CONTENT_WATER || _content_type == CONTENT_LAVA || _content_type == CONTENT_SLIME))
Definition at line 82 of file bot.qh.
#define SUBMERGED (pos) IN_LIQUID(pos + autocvar_sv_player_viewoffset)
Definition at line 83 of file bot.qh.
Referenced by navigation_check_submerged_state(), and tracewalk().
#define WETFEET (pos) IN_LIQUID(pos + eZ * (m1.z + 1))
Definition at line 84 of file bot.qh.
Referenced by resurface_limited(), and tracewalk().
Function Documentation
void autoskill (float factor)
Definition at line 538 of file bot.qc.
References autocvar_skill, bprint(), cvar_set(), FOREACH_CLIENT, ftos(), IS_PLAYER, IS_REAL_CLIENT, LOG_DEBUG, and max().
Referenced by bot_serverframe().
 {
     float bestbot;
     float bestplayer;
     bestbot = -1;
     bestplayer = -1;
     FOREACH_CLIENT(IS_PLAYER(it), {
         if(IS_REAL_CLIENT(it))
             bestplayer = max(bestplayer, it.totalfrags - it.totalfrags_lastcheck);
         else
             bestbot = max(bestbot, it.totalfrags - it.totalfrags_lastcheck);
     });
     LOG_DEBUG("autoskill: best player got ", ftos(bestplayer), ", ");
     LOG_DEBUG("best bot got ", ftos(bestbot), "; ");
     if(bestbot < 0 || bestplayer < 0)
     {
         LOG_DEBUG("not doing anything");
         // don't return, let it reset all counters below
     }
     else if(bestbot <= bestplayer * factor - 2)
     {
         if(autocvar_skill < 17)
         {
             LOG_DEBUG("2 frags difference, increasing skill");
             cvar_set("skill", ftos(autocvar_skill + 1));
             bprint("^2SKILL UP!^7 Now at level ", ftos(autocvar_skill), "\n");
         }
     }
     else if(bestbot >= bestplayer * factor + 2)
     {
         if(autocvar_skill > 0)
         {
             LOG_DEBUG("2 frags difference, decreasing skill");
             cvar_set("skill", ftos(autocvar_skill - 1));
             bprint("^1SKILL DOWN!^7 Now at level ", ftos(autocvar_skill), "\n");
         }
     }
     else
     {
         LOG_DEBUG("not doing anything");
         return;
         // don't reset counters, wait for them to accumulate
     }
     FOREACH_CLIENT(IS_PLAYER(it), { it.totalfrags_lastcheck = it.totalfrags; });
 }
void bot_calculate_stepheightvec ()
Definition at line 587 of file bot.qc.
References autocvar_sv_gravity, autocvar_sv_jumpvelocity, autocvar_sv_stepheight, jumpheight_time, jumpheight_vec, jumpstepheightvec, and stepheightvec.
Referenced by bot_serverframe(), STATIC_INIT(), and waypoint_think().
 {
     stepheightvec = autocvar_sv_stepheight * '0 0 1';
     jumpheight_vec = (autocvar_sv_jumpvelocity ** 2) / (2 * autocvar_sv_gravity) * '0 0 1';
     jumpstepheightvec = stepheightvec + jumpheight_vec * 0.85; // reduce it a bit to make the jumps easy
     jumpheight_time = autocvar_sv_jumpvelocity / autocvar_sv_gravity;
 }
void bot_clear (entity this)
Definition at line 683 of file bot.qc.
References AI_STATUS_STUCK, aistatus, bot_remove_from_bot_list(), bot_waypoint_queue_owner, and NULL.
 {
     bot_remove_from_bot_list(this);
     if(bot_waypoint_queue_owner == this)
         bot_waypoint_queue_owner = NULL;
     this.aistatus &= ~AI_STATUS_STUCK; // otherwise bot_waypoint_queue_owner will be set again to this by navigation_unstuck
 }
void bot_clientconnect (entity this)
Definition at line 427 of file bot.qc.
References bot_config_loaded, bot_forced_team, bot_lagfunc(), bot_nextthink, bot_preferredcolors, bot_setclientfields(), bot_setnameandstuff(), clientcolors, createdtime, havocbot_setupbot(), IS_BOT_CLIENT, isbot, random(), SetPlayerTeam(), TEAM_CHANGE_MANUAL, Team_IsValidIndex(), TeamBalance_JoinBestTeam(), teamplay, and time.
 {
     if (!IS_BOT_CLIENT(this)) return;
     this.bot_preferredcolors = this.clientcolors;
     this.bot_nextthink = time - random();
     this.lag_func = bot_lagfunc;
     this.isbot = true;
     this.createdtime = this.bot_nextthink;
     if(!this.bot_config_loaded) // This is needed so team overrider doesn't break between matches
     {
         bot_setnameandstuff(this);
         bot_setclientfields(this);
     }
     if (teamplay && Team_IsValidIndex(this.bot_forced_team))
     {
         SetPlayerTeam(this, this.bot_forced_team, TEAM_CHANGE_MANUAL);
     }
     else
     {
         this.bot_forced_team = 0;
         TeamBalance_JoinBestTeam(this);
     }
     havocbot_setupbot(this);
 }
void bot_clientdisconnect (entity this)
Definition at line 412 of file bot.qc.
References bot_clearqueue(), bot_cmd_current, bot_waypoint_queue_owner, cleanname, IS_BOT_CLIENT, netname_freeme, NULL, playermodel_freeme, playerskin_freeme, and strfree.
 {
     if (!IS_BOT_CLIENT(this))
         return;
     bot_clearqueue(this);
     strfree(this.cleanname);
     strfree(this.netname_freeme);
     strfree(this.playermodel_freeme);
     strfree(this.playerskin_freeme);
     if(this.bot_cmd_current)
         delete(this.bot_cmd_current);
     if(bot_waypoint_queue_owner == this)
         bot_waypoint_queue_owner = NULL;
 }
void bot_custom_weapon_priority_setup ()
Definition at line 311 of file bot.qc.
References argv(), autocvar_bot_ai_custom_weapon_priority_close, autocvar_bot_ai_custom_weapon_priority_distances, autocvar_bot_ai_custom_weapon_priority_far, autocvar_bot_ai_custom_weapon_priority_mid, bot_custom_weapon, bot_distance_close, bot_distance_far, PARSE_WEAPON_PRIORITIES, stof(), strcpy, and tokenizebyseparator.
Referenced by bot_serverframe().
 {
     static string bot_priority_far_prev;
     static string bot_priority_mid_prev;
     static string bot_priority_close_prev;
     static string bot_priority_distances_prev;
     float tokens, i, w;
     bot_custom_weapon = false;
     if( autocvar_bot_ai_custom_weapon_priority_far == "" ||
         autocvar_bot_ai_custom_weapon_priority_mid == "" ||
         autocvar_bot_ai_custom_weapon_priority_close == "" ||
         autocvar_bot_ai_custom_weapon_priority_distances == ""
     )
         return;
     if (bot_priority_distances_prev != autocvar_bot_ai_custom_weapon_priority_distances)
     {
         strcpy(bot_priority_distances_prev, autocvar_bot_ai_custom_weapon_priority_distances);
         tokens = tokenizebyseparator(autocvar_bot_ai_custom_weapon_priority_distances," ");
         if (tokens!=2)
             return;
         bot_distance_far = stof(argv(0));
         bot_distance_close = stof(argv(1));
         if(bot_distance_far < bot_distance_close){
             bot_distance_far = stof(argv(1));
             bot_distance_close = stof(argv(0));
         }
     }
     int c;
     #define PARSE_WEAPON_PRIORITIES(dist) MACRO_BEGIN \
         if (bot_priority_##dist##_prev != autocvar_bot_ai_custom_weapon_priority_##dist) { \
             strcpy(bot_priority_##dist##_prev, autocvar_bot_ai_custom_weapon_priority_##dist); \
             tokens = tokenizebyseparator(W_NumberWeaponOrder(autocvar_bot_ai_custom_weapon_priority_##dist)," "); \
             bot_weapons_##dist[0] = -1; \
             c = 0; \
             for(i = 0; i < tokens && c < REGISTRY_COUNT(Weapons); ++i) { \
                 w = stof(argv(i)); \
                 if (w >= WEP_FIRST && w <= WEP_LAST) { \
                     bot_weapons_##dist[c] = w; \
                     ++c; \
                 } \
             } \
             if (c < REGISTRY_COUNT(Weapons)) \
                 bot_weapons_##dist[c] = -1; \
         } \
     MACRO_END
     PARSE_WEAPON_PRIORITIES(far);
     PARSE_WEAPON_PRIORITIES(mid);
     PARSE_WEAPON_PRIORITIES(close);
     bot_custom_weapon = true;
 }
void bot_endgame ()
Definition at line 372 of file bot.qc.
References bot_list, bot_relinkplayerlist(), entity(), and setcolor.
 {
     bot_relinkplayerlist();
     entity e = bot_list;
     while (e)
     {
         setcolor(e, e.bot_preferredcolors);
         e = e.nextbot;
     }
     // if dynamic waypoints are ever implemented, save them here
 }
bool bot_fixcount ()
Definition at line 595 of file bot.qc.
References autocvar_bot_join_empty, autocvar_bot_number, autocvar_bot_vs_human, autocvar_minplayers, autocvar_minplayers_per_team, AvailableTeams(), bot_removenewest(), bot_spawn(), botframe_nextthink, bots_would_leave, bprint(), ceil(), currentbots, fabs(), floor(), FOREACH_CLIENT, GetPlayerLimit(), IS_PLAYER, IS_REAL_CLIENT, M_ARGV, max(), maxclients, min(), MUTATOR_CALLHOOK, NULL, teamplay, and time.
Referenced by bot_serverframe().
 {
     int activerealplayers = 0;
     int realplayers = 0;
     if (MUTATOR_CALLHOOK(Bot_FixCount, activerealplayers, realplayers)) {
         activerealplayers = M_ARGV(0, int);
         realplayers = M_ARGV(1, int);
     } else {
         FOREACH_CLIENT(IS_REAL_CLIENT(it), {
             if(IS_PLAYER(it))
                 ++activerealplayers;
             ++realplayers;
         });
     }
     int bots;
     // But don't remove bots immediately on level change, as the real players
     // usually haven't rejoined yet
     bots_would_leave = false;
     if (teamplay && autocvar_bot_vs_human && AvailableTeams() == 2)
         bots = min(ceil(fabs(autocvar_bot_vs_human) * activerealplayers), maxclients - realplayers);
     else if ((realplayers || autocvar_bot_join_empty || (currentbots > 0 && time < 5)))
     {
         int minplayers = max(0, floor(autocvar_minplayers));
         if (teamplay)
             minplayers = max(0, floor(autocvar_minplayers_per_team) * AvailableTeams());
         int minbots = max(0, floor(autocvar_bot_number));
         // add bots to reach minplayers if needed
         bots = max(minbots, minplayers - activerealplayers);
         // cap bots to the max players allowed by the server
         int player_limit = GetPlayerLimit();
         if(player_limit)
             bots = min(bots, max(player_limit - activerealplayers, 0));
         bots = min(bots, maxclients - realplayers);
         if(bots > minbots)
             bots_would_leave = true;
     }
     else
     {
         // if there are no players, remove bots
         bots = 0;
     }
     // only add one bot per frame to avoid utter chaos
     if(time > botframe_nextthink)
     {
         if (currentbots < bots)
         {
             if (bot_spawn() == NULL)
             {
                 bprint("Can not add bot, server full.\n");
                 return false;
             }
         }
         while (currentbots > bots && bots >= 0)
             bot_removenewest();
     }
     return true;
 }
void bot_relinkplayerlist ()
Definition at line 384 of file bot.qc.
References bot_list, bot_strategytoken, bot_strategytoken_taken, currentbots, entity(), FOREACH_CLIENT, ftos(), IS_BOT_CLIENT, LOG_TRACE(), NULL, and player_count.
Referenced by bot_endgame().
 {
     player_count = 0;
     currentbots = 0;
     bot_list = NULL;
     entity prevbot = NULL;
     FOREACH_CLIENT(true,
     {
         ++player_count;
         if(IS_BOT_CLIENT(it))
         {
             if(prevbot)
                 prevbot.nextbot = it;
             else
                 bot_list = it;
             prevbot = it;
             ++currentbots;
         }
     });
     if(prevbot)
         prevbot.nextbot = NULL;
     LOG_TRACE("relink: ", ftos(currentbots), " bots seen.");
     bot_strategytoken = bot_list;
     bot_strategytoken_taken = true;
 }
void bot_removefromlargestteam ()
Definition at line 455 of file bot.qc.
References best, entity(), FOREACH_CLIENT, NULL, Team_IsValidTeam(), TeamBalance_CheckAllowedTeams(), and TeamBalance_GetTeamCounts().
Referenced by bot_removenewest().
 {
     entity balance = TeamBalance_CheckAllowedTeams(NULL);
     TeamBalance_GetTeamCounts(balance, NULL);
     entity best = NULL;
     float besttime = 0;
     int bestcount = 0;
     int bcount = 0;
     FOREACH_CLIENT(it.isbot,
     {
         ++bcount;
         if(!best)
         {
             best = it;
             besttime = it.createdtime;
         }
         int thiscount = 0;
         if (Team_IsValidTeam(it.team))
         {
             thiscount = TeamBalance_GetNumberOfPlayers(balance,
                 Team_TeamToIndex(it.team));
         }
         if(thiscount > bestcount)
         {
             bestcount = thiscount;
             besttime = it.createdtime;
             best = it;
         }
         else if(thiscount == bestcount && besttime < it.createdtime)
         {
             besttime = it.createdtime;
             best = it;
         }
     });
     TeamBalance_Destroy(balance);
     if(!bcount)
         return; // no bots to remove
     currentbots = currentbots - 1;
     dropclient(best);
 }
void bot_removenewest ()
Definition at line 502 of file bot.qc.
References best, bot_removefromlargestteam(), currentbots, entity(), FOREACH_CLIENT, NULL, and teamplay.
Referenced by bot_fixcount().
 {
     if(teamplay)
     {
         bot_removefromlargestteam();
         return;
     }
     float besttime = 0;
     entity best = NULL;
     int bcount = 0;
     FOREACH_CLIENT(it.isbot,
     {
         ++bcount;
         if(!best)
         {
             best = it;
             besttime = it.createdtime;
         }
         if(besttime < it.createdtime)
         {
             besttime = it.createdtime;
             best = it;
         }
     });
     if(!bcount)
         return; // no bots to remove
     currentbots = currentbots - 1;
     dropclient(best);
 }
void bot_serverframe ()
Definition at line 691 of file bot.qc.
References autocvar_bot_ai_bunnyhop_skilloffset, autocvar_bot_ai_dangerdetectioninterval, autocvar_bot_ai_dangerdetectionupdates, autocvar_bot_navigation_ignoreplayers, autocvar_g_waypointeditor, autocvar_g_waypointeditor_auto, autocvar_skill, autocvar_skill_auto, autocvar_waypoint_benchmark, autoskill(), autoskill_nextthink, bot_calculate_stepheightvec(), bot_custom_weapon_priority_setup(), bot_fixcount(), bot_list, bot_navigation_movemode, bot_strategytoken, bot_strategytoken_taken, botframe_autowaypoints(), botframe_cachedwaypointlinks, botframe_loadedforcedlinks, botframe_nextdangertime, botframe_nextthink, botframe_showwaypointlinks(), botframe_spawnedwaypoints, botframe_updatedangerousobjects(), currentbots, entity(), FOREACH_CLIENT, g_waypoints, IL_EACH, intermission_running, IS_BOT_CLIENT, IS_DEAD, IS_REAL_CLIENT, localcmd, MOVE_NOMONSTERS, MOVE_NORMAL, NULL, skill, time, waypoint_load_hardwiredlinks(), waypoint_load_links(), waypoint_loadall(), and waypoint_updatecost_foralllinks().
 {
     if (intermission_running && currentbots > 0)
     {
         // after the end of the match all bots stay unless all human players disconnect
         int realplayers = 0;
         FOREACH_CLIENT(IS_REAL_CLIENT(it), { ++realplayers; });
         if (!realplayers)
         {
             FOREACH_CLIENT(IS_BOT_CLIENT(it), { dropclient(it); });
             currentbots = 0;
         }
         return;
     }
     if (game_stopped)
         return;
     // Added 0.5 to avoid possible addition + immediate removal of bots that would make them appear as
     // spectators in the scoreboard and never go away. This issue happens at time 2 if map is changed
     // with the gotomap command, minplayers is > 1 and human clients join as players very soon
     // either intentionally or automatically (sv_spectate 0)
     if (time < 2.5)
     {
         currentbots = -1;
         return;
     }
     if (currentbots == -1)
     {
         // count bots already in the server from the previous match
         currentbots = 0;
         FOREACH_CLIENT(IS_BOT_CLIENT(it), { ++currentbots; });
     }
     if(autocvar_skill != skill)
     {
         float wpcost_update = false;
         if(skill >= autocvar_bot_ai_bunnyhop_skilloffset && autocvar_skill < autocvar_bot_ai_bunnyhop_skilloffset)
             wpcost_update = true;
         if(skill < autocvar_bot_ai_bunnyhop_skilloffset && autocvar_skill >= autocvar_bot_ai_bunnyhop_skilloffset)
             wpcost_update = true;
         skill = autocvar_skill;
         if (wpcost_update)
             waypoint_updatecost_foralllinks();
     }
     bot_calculate_stepheightvec();
     bot_navigation_movemode = ((autocvar_bot_navigation_ignoreplayers) ? MOVE_NOMONSTERS : MOVE_NORMAL);
     if(time > autoskill_nextthink)
     {
         float a;
         a = autocvar_skill_auto;
         if(a)
             autoskill(a);
         autoskill_nextthink = time + 5;
     }
     if(time > botframe_nextthink)
     {
         if(!bot_fixcount())
             botframe_nextthink = time + 10;
     }
     if(botframe_spawnedwaypoints)
     {
         if(autocvar_waypoint_benchmark)
             localcmd("quit\n");
     }
     if (currentbots > 0 || autocvar_g_waypointeditor || autocvar_g_waypointeditor_auto)
     if (botframe_spawnedwaypoints)
     {
         if(botframe_cachedwaypointlinks)
         {
             if(!botframe_loadedforcedlinks)
                 waypoint_load_hardwiredlinks();
         }
         else
         {
             // TODO: Make this check cleaner
             IL_EACH(g_waypoints, time - it.nextthink > 10,
             {
                 waypoint_save_links();
                 break;
             });
         }
     }
     else
     {
         botframe_spawnedwaypoints = true;
         waypoint_loadall();
         waypoint_load_links();
     }
     if (bot_list)
     {
         // cycle the goal token from one bot to the next each frame
         // (this prevents them from all doing spawnfunc_waypoint searches on the same
         //  frame, which causes choppy framerates)
         if (bot_strategytoken_taken)
         {
             // give goal token to the first bot without goals; if all bots don't have
             // any goal (or are dead/frozen) simply give it to the next one
             bot_strategytoken_taken = false;
             entity bot_strategytoken_save = bot_strategytoken;
             while (true)
             {
                 if (bot_strategytoken)
                     bot_strategytoken = bot_strategytoken.nextbot;
                 if (!bot_strategytoken)
                     bot_strategytoken = bot_list;
                 if (!(IS_DEAD(bot_strategytoken) || STAT(FROZEN, bot_strategytoken))
                     && !bot_strategytoken.goalcurrent)
                     break;
                 if (!bot_strategytoken_save) // break loop if all the bots are dead or frozen
                     break;
                 if (bot_strategytoken == bot_strategytoken_save)
                     bot_strategytoken_save = NULL; // looped through all the bots
             }
         }
         if (botframe_nextdangertime < time)
         {
             float interval;
             interval = autocvar_bot_ai_dangerdetectioninterval;
             if (botframe_nextdangertime < time - interval * 1.5)
                 botframe_nextdangertime = time;
             botframe_nextdangertime = botframe_nextdangertime + interval;
             botframe_updatedangerousobjects(autocvar_bot_ai_dangerdetectionupdates);
         }
     }
     if (autocvar_g_waypointeditor)
         botframe_showwaypointlinks();
     if (autocvar_g_waypointeditor_auto)
         botframe_autowaypoints();
     if (currentbots > 0)
         bot_custom_weapon_priority_setup();
 }
void bot_setnameandstuff (entity this)
Definition at line 146 of file bot.qc.
References argv(), autocvar_bot_config_file, autocvar_bot_prefix, autocvar_bot_suffix, autocvar_bot_usemodelnames, autocvar_bot_vs_human, autocvar_g_campaign, AvailableTeams(), bot_aggresskill, bot_aimskill, bot_aiskill, bot_config_loaded, bot_dodgeskill, bot_forced_team, bot_mouseskill, bot_moveskill, bot_offsetskill, bot_pingskill, bot_preferredcolors, bot_rangepreference, bot_thinkskill, bot_weaponskill, cleanname, clientcolors, count, entity(), etof(), fclose(), fgets(), FILE_READ, floor(), fopen(), FOREACH_CLIENT, ftos(), havocbot_keyboardskill, IS_BOT_CLIENT, LOG_INFOF, name, netname, netname_freeme, NULL, playermodel, playermodel_freeme, playerskin, playerskin_freeme, random(), RandomSelection_AddString, RandomSelection_chosen_string, RandomSelection_Init(), READSKILL, setcolor, stof(), strcat(), strzone(), substring(), Team_IsValidIndex(), TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetNumberOfPlayers(), TeamBalance_GetTeamCounts(), teamplay, and tokenizebyseparator.
Referenced by bot_clientconnect(), and bot_spawn().
 {
     string readfile, s;
     int file, tokens, prio;
     file = fopen(autocvar_bot_config_file, FILE_READ);
     if(file < 0)
     {
         LOG_INFOF("Error: Can not open the bot configuration file '%s'", autocvar_bot_config_file);
         readfile = "";
     }
     else
     {
         entity balance = TeamBalance_CheckAllowedTeams(NULL);
         TeamBalance_GetTeamCounts(balance, NULL);
         int smallest_team = -1;
         int smallest_count = -1;
         if (teamplay)
         {
             for (int i = 1; i <= AvailableTeams(); ++i)
             {
                 // NOTE if (autocvar_g_campaign && autocvar_g_campaign_forceteam == i)
                 // TeamBalance_GetNumberOfPlayers(balance, i); returns the number of players + 1
                 // since it keeps a spot for the real player in the desired team
                 int count = TeamBalance_GetNumberOfPlayers(balance, i);
                 if (smallest_count < 0 || count < smallest_count)
                 {
                     smallest_team = i;
                     smallest_count = count;
                 }
             }
         }
         TeamBalance_Destroy(balance);
         RandomSelection_Init();
         while((readfile = fgets(file)))
         {
             if(substring(readfile, 0, 2) == "//")
                 continue;
             if(substring(readfile, 0, 1) == "#")
                 continue;
             // NOTE if the line is empty tokenizebyseparator(readfile, "\t")
             // will create 1 empty token because there's no separator (bug?)
             if (readfile == "")
                 continue;
             tokens = tokenizebyseparator(readfile, "\t");
             if(tokens == 0)
                 continue;
             s = argv(0);
             prio = 0;
             bool conflict = false;
             FOREACH_CLIENT(IS_BOT_CLIENT(it), {
                 if (s == it.cleanname)
                 {
                     conflict = true;
                     break;
                 }
             });
             if (!conflict)
                 prio += 1;
             if (teamplay && !(autocvar_bot_vs_human && AvailableTeams() == 2))
             {
                 int forced_team = stof(argv(5));
                 if (!Team_IsValidIndex(forced_team))
                     forced_team = 0;
                 if (!forced_team || forced_team == smallest_team)
                     prio += 2;
             }
             RandomSelection_AddString(readfile, 1, prio);
         }
         readfile = RandomSelection_chosen_string;
         fclose(file);
     }
     string bot_name, bot_model, bot_skin, bot_shirt, bot_pants;
     tokens = tokenizebyseparator(readfile, "\t");
     if(argv(0) != "") bot_name = argv(0);
     else bot_name = "Bot";
     if(argv(1) != "") bot_model = argv(1);
     else bot_model = "";
     if(argv(2) != "") bot_skin = argv(2);
     else bot_skin = "0";
     if(argv(3) != "" && stof(argv(3)) >= 0) bot_shirt = argv(3);
     else bot_shirt = ftos(floor(random() * 15));
     if(argv(4) != "" && stof(argv(4)) >= 0) bot_pants = argv(4);
     else bot_pants = ftos(floor(random() * 15));
     if (teamplay && !(autocvar_bot_vs_human && AvailableTeams() == 2))
         this.bot_forced_team = stof(argv(5));
     else
         this.bot_forced_team = 0;
     prio = 6;
     #define READSKILL(f, w, r) MACRO_BEGIN \
         if(argv(prio) != "") \
             this.f = stof(argv(prio)) * w; \
         else \
             this.f = (!autocvar_g_campaign) * (2 * random() - 1) * r * w; \
         prio++; \
     MACRO_END
     //print(bot_name, ": ping=", argv(9), "\n");
     READSKILL(havocbot_keyboardskill, 0.5, 0.5); // keyboard skill
     READSKILL(bot_moveskill, 2, 0); // move skill
     READSKILL(bot_dodgeskill, 2, 0); // dodge skill
     READSKILL(bot_pingskill, 0.5, 0); // ping skill
     READSKILL(bot_weaponskill, 2, 0); // weapon skill
     READSKILL(bot_aggresskill, 1, 0); // aggre skill
     READSKILL(bot_rangepreference, 1, 0); // read skill
     READSKILL(bot_aimskill, 2, 0); // aim skill
     READSKILL(bot_offsetskill, 2, 0.5); // offset skill
     READSKILL(bot_mouseskill, 1, 0.5); // mouse skill
     READSKILL(bot_thinkskill, 1, 0.5); // think skill
     READSKILL(bot_aiskill, 2, 0); // "ai" skill
     if (file >= 0 && argv(prio) != "")
         LOG_INFOF("^1Warning^7: too many parameters for bot %s, please check format of %s", bot_name, autocvar_bot_config_file);
     this.bot_config_loaded = true;
     // this is really only a default, TeamBalance_JoinBestTeam is called later
     setcolor(this, stof(bot_shirt) * 16 + stof(bot_pants));
     this.bot_preferredcolors = this.clientcolors;
     string prefix = (autocvar_g_campaign ? "" : autocvar_bot_prefix);
     string suffix = (autocvar_g_campaign ? "" : autocvar_bot_suffix);
     string name = (autocvar_bot_usemodelnames ? bot_model : bot_name);
     if (name == "")
     {
         name = ftos(etof(this));
         this.netname = this.netname_freeme = strzone(strcat(prefix, name, suffix));
     }
     else
     {
         // number bots with identical names
         int j = 0;
         FOREACH_CLIENT(IS_BOT_CLIENT(it), {
             if(it.cleanname == name)
                 ++j;
         });
         if (j)
             this.netname = this.netname_freeme = strzone(strcat(prefix, name, "(", ftos(j), ")", suffix));
         else
             this.netname = this.netname_freeme = strzone(strcat(prefix, name, suffix));
     }
     this.cleanname = strzone(name);
     // pick the model and skin
     if(substring(bot_model, -4, 1) != ".")
         bot_model = strcat(bot_model, ".iqm");
     this.playermodel = this.playermodel_freeme = strzone(strcat("models/player/", bot_model));
     this.playerskin = this.playerskin_freeme = strzone(bot_skin);
 }
entity bot_spawn ()
Definition at line 53 of file bot.qc.
References bot_setclientfields(), bot_setnameandstuff(), ClientConnect(), currentbots, entity(), and PutClientInServer().
Referenced by bot_fixcount().
 {
     entity bot = spawnclient();
     if (bot)
     {
         setItemGroupCount();
         currentbots = currentbots + 1;
         bot_setnameandstuff(bot);
         ClientConnect(bot);
         bot_setclientfields(bot);
         PutClientInServer(bot);
     }
     return bot;
 }
void bot_think (entity this)
Definition at line 68 of file bot.qc.
References AI_STATUS_STUCK, aistatus, angles, autocvar_bot_ai_thinkinterval, autocvar_bot_god, autocvar_g_campaign, bot_aiskill, bot_jump_time, bot_nextthink, bot_pingskill, bot_waypoint_queue_owner, bound(), campaign_bots_may_start, CS(), DEAD_DEAD, deadflag, dmg_inflictor, dmg_save, dmg_take, fixangle, FL_GODMODE, flags, IS_DEAD, IS_PLAYER, max(), min(), navigation_goalrating_timeout_force(), navigation_unstuck(), NULL, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_CHAT, PHYS_INPUT_BUTTON_CROUCH, PHYS_INPUT_BUTTON_DRAG, PHYS_INPUT_BUTTON_HOOK, PHYS_INPUT_BUTTON_INFO, PHYS_INPUT_BUTTON_JUMP, PHYS_INPUT_BUTTON_USE, PHYS_INPUT_BUTTON_ZOOM, random(), skill, time, and v_angle.
 {
     if (this.bot_nextthink > time)
         return;
     this.flags &= ~FL_GODMODE;
     if(autocvar_bot_god)
         this.flags |= FL_GODMODE;
     this.bot_nextthink = max(time, this.bot_nextthink) + max(0.01, autocvar_bot_ai_thinkinterval * (0.5 ** this.bot_aiskill) * min(14 / (skill + 14), 1));
     if (!IS_PLAYER(this) || (autocvar_g_campaign && !campaign_bots_may_start))
     {
         CS(this).movement = '0 0 0';
         this.bot_nextthink = time + 0.5;
         return;
     }
     if (this.fixangle)
     {
         this.v_angle = this.angles;
         this.v_angle_z = 0;
         this.fixangle = false;
     }
     this.dmg_take = 0;
     this.dmg_save = 0;
     this.dmg_inflictor = NULL;
     // calculate an aiming latency based on the skill setting
     // (simulated network latency + naturally delayed reflexes)
     //this.ping = 0.7 - bound(0, 0.05 * skill, 0.5); // moved the reflexes to bot_aimdir (under the name 'think')
     // minimum ping 20+10 random
     CS(this).ping = bound(0,0.07 - bound(0, (skill + this.bot_pingskill) * 0.005,0.05)+random()*0.01,0.65); // Now holds real lag to server, and higer skill players take a less laggy server
     // skill 10 = ping 0.2 (adrenaline)
     // skill 0 = ping 0.7 (slightly drunk)
     // clear buttons
     PHYS_INPUT_BUTTON_ATCK(this) = false;
     // keep jump button pressed for a short while, useful with ramp jumps
     PHYS_INPUT_BUTTON_JUMP(this) = (!IS_DEAD(this) && time < this.bot_jump_time + 0.2);
     PHYS_INPUT_BUTTON_ATCK2(this) = false;
     PHYS_INPUT_BUTTON_ZOOM(this) = false;
     PHYS_INPUT_BUTTON_CROUCH(this) = false;
     PHYS_INPUT_BUTTON_HOOK(this) = false;
     PHYS_INPUT_BUTTON_INFO(this) = false;
     PHYS_INPUT_BUTTON_DRAG(this) = false;
     PHYS_INPUT_BUTTON_CHAT(this) = false;
     PHYS_INPUT_BUTTON_USE(this) = false;
     if (time < game_starttime)
     {
         // block the bot during the countdown to game start
         CS(this).movement = '0 0 0';
         this.bot_nextthink = game_starttime;
         return;
     }
     // if dead, just wait until we can respawn
     if (IS_DEAD(this))
     {
         if (bot_waypoint_queue_owner == this)
             bot_waypoint_queue_owner = NULL;
         this.aistatus = 0;
         CS(this).movement = '0 0 0';
         if (this.deadflag == DEAD_DEAD)
         {
             PHYS_INPUT_BUTTON_JUMP(this) = true; // press jump to respawn
             navigation_goalrating_timeout_force(this);
         }
     }
     else if(this.aistatus & AI_STATUS_STUCK)
         navigation_unstuck(this);
     // now call the current bot AI (havocbot for example)
     this.bot_ai(this);
 }
float (entity player, entity item)
void (entity this)
Variable Documentation
int _content_type
Definition at line 80 of file bot.qh.
const int AI_STATUS_ATTACKING = BIT(1)
Definition at line 7 of file bot.qh.
Referenced by havocbot_ai(), and havocbot_bunnyhop().
const int AI_STATUS_DANGER_AHEAD = BIT(3)
Definition at line 9 of file bot.qh.
Referenced by havocbot_bunnyhop(), and havocbot_movetogoal().
const int AI_STATUS_JETPACK_FLYING = BIT(9)
Definition at line 15 of file bot.qh.
Referenced by havocbot_movetogoal().
const int AI_STATUS_JETPACK_LANDING = BIT(10)
Definition at line 16 of file bot.qh.
Referenced by havocbot_movetogoal().
const int AI_STATUS_OUT_JUMPPAD = BIT(4)
Definition at line 10 of file bot.qh.
Referenced by havocbot_movetogoal().
const int AI_STATUS_OUT_WATER = BIT(5)
Definition at line 11 of file bot.qh.
Referenced by havocbot_ai(), and havocbot_movetogoal().
const int AI_STATUS_ROAMING = BIT(0)
Definition at line 6 of file bot.qh.
Referenced by havocbot_ai(), and havocbot_movetogoal().
const int AI_STATUS_RUNNING = BIT(2)
Definition at line 8 of file bot.qh.
Referenced by havocbot_bunnyhop(), havocbot_movetogoal(), navigation_get_really_close_waypoint(), and navigation_poptouchedgoals().
const int AI_STATUS_STUCK = BIT(11)
Definition at line 17 of file bot.qh.
Referenced by bot_clear(), bot_think(), navigation_goalrating_end(), navigation_goalrating_start(), and navigation_unstuck().
const int AI_STATUS_WAYPOINT_PERSONAL_GOING = BIT(7)
Definition at line 13 of file bot.qh.
Referenced by havocbot_moveto(), and navigation_poptouchedgoals().
const int AI_STATUS_WAYPOINT_PERSONAL_LINKING = BIT(6)
Definition at line 12 of file bot.qh.
Referenced by havocbot_moveto().
const int AI_STATUS_WAYPOINT_PERSONAL_REACHED = BIT(8)
Definition at line 14 of file bot.qh.
Referenced by havocbot_moveto(), and navigation_poptouchedgoals().
int aistatus
Definition at line 20 of file bot.qh.
Referenced by bot_clear(), bot_think(), havocbot_ai(), havocbot_bunnyhop(), havocbot_moveto(), havocbot_movetogoal(), navigation_get_really_close_waypoint(), navigation_goalrating_end(), navigation_goalrating_start(), navigation_poptouchedgoals(), and navigation_unstuck().
float autoskill_nextthink
Definition at line 23 of file bot.qh.
Referenced by bot_serverframe().
float bot_aggresskill
Definition at line 32 of file bot.qh.
Referenced by bot_aimdir(), and bot_setnameandstuff().
float bot_aimskill
Definition at line 35 of file bot.qh.
Referenced by bot_aimdir(), and bot_setnameandstuff().
float bot_aiskill
Definition at line 40 of file bot.qh.
Referenced by bot_setnameandstuff(), and bot_think().
float bot_attack
Definition at line 59 of file bot.qh.
float bot_canfire
Definition at line 66 of file bot.qh.
Referenced by bot_lagfunc().
float bot_config_loaded
Definition at line 71 of file bot.qh.
Referenced by bot_clientconnect(), and bot_setnameandstuff().
float bot_distance_close
Definition at line 46 of file bot.qh.
Referenced by bot_custom_weapon_priority_setup(), and havocbot_chooseweapon().
float bot_distance_far
Definition at line 45 of file bot.qh.
Referenced by bot_custom_weapon_priority_setup(), and havocbot_chooseweapon().
float bot_dodge
Definition at line 60 of file bot.qh.
float bot_dodgerating
Definition at line 61 of file bot.qh.
float bot_dodgeskill
Definition at line 27 of file bot.qh.
Referenced by bot_setnameandstuff(), and havocbot_movetogoal().
float bot_forced_team
Definition at line 70 of file bot.qh.
float bot_jump_time
Definition at line 68 of file bot.qh.
Referenced by bot_think(), havocbot_bunnyhop(), and havocbot_movetogoal().
entity bot_list
Definition at line 48 of file bot.qh.
Referenced by bot_endgame(), bot_relinkplayerlist(), bot_remove_from_bot_list(), and bot_serverframe().
float bot_mouseskill
Definition at line 37 of file bot.qh.
Referenced by bot_aimdir(), and bot_setnameandstuff().
float bot_moveskill
Definition at line 26 of file bot.qh.
float bot_nextthink
Definition at line 55 of file bot.qh.
Referenced by bot_clientconnect(), and bot_think().
float bot_offsetskill
Definition at line 36 of file bot.qh.
Referenced by bot_aimdir(), and bot_setnameandstuff().
float bot_pickup
Definition at line 63 of file bot.qh.
bool bot_pickup_respawning
Definition at line 65 of file bot.qh.
float bot_pickupbasevalue
Definition at line 64 of file bot.qh.
Referenced by buff_Init().
float bot_pingskill
Definition at line 29 of file bot.qh.
Referenced by bot_setnameandstuff(), and bot_think().
float bot_preferredcolors
Definition at line 58 of file bot.qh.
Referenced by bot_clientconnect(), and bot_setnameandstuff().
float bot_rangepreference
Definition at line 33 of file bot.qh.
Referenced by bot_setnameandstuff(), and havocbot_chooseweapon().
float bot_strategytime
Definition at line 67 of file bot.qh.
Referenced by navigation_goalrating_timeout(), navigation_goalrating_timeout_can_be_anticipated(), navigation_goalrating_timeout_expire(), navigation_goalrating_timeout_extend_if_needed(), and navigation_goalrating_timeout_set().
entity bot_strategytoken
Definition at line 74 of file bot.qh.
Referenced by bot_relinkplayerlist(), bot_remove_from_bot_list(), bot_serverframe(), havocbot_ai(), and navigation_unstuck().
float bot_strategytoken_taken
Definition at line 73 of file bot.qh.
Referenced by bot_relinkplayerlist(), bot_remove_from_bot_list(), bot_serverframe(), havocbot_ai(), and havocbot_moveto().
float bot_thinkskill
Definition at line 39 of file bot.qh.
Referenced by bot_aimdir(), and bot_setnameandstuff().
float bot_weaponskill
Definition at line 31 of file bot.qh.
Referenced by bot_setnameandstuff(), and havocbot_chooseweapon().
float botframe_nextdangertime
Definition at line 78 of file bot.qh.
Referenced by bot_serverframe().
float botframe_nextthink
Definition at line 77 of file bot.qh.
Referenced by bot_fixcount(), and bot_serverframe().
float botframe_spawnedwaypoints
Definition at line 76 of file bot.qh.
Referenced by bot_serverframe().
string cleanname
Definition at line 50 of file bot.qh.
float createdtime
Definition at line 57 of file bot.qh.
Referenced by bot_clientconnect().
bool isbot
Definition at line 19 of file bot.qh.
string netname_freeme
Definition at line 51 of file bot.qh.
Referenced by bot_clientdisconnect(), and bot_setnameandstuff().
entity nextbot
Definition at line 49 of file bot.qh.
Referenced by bot_remove_from_bot_list().
string playermodel_freeme
Definition at line 52 of file bot.qh.
Referenced by bot_clientdisconnect(), and bot_setnameandstuff().
string playerskin_freeme
Definition at line 53 of file bot.qh.
Referenced by bot_clientdisconnect(), and bot_setnameandstuff().
float totalfrags_lastcheck
Definition at line 42 of file bot.qh.