Xonotic: server/command/banning.qh File Reference
banning.qh File Reference
Macros
#define GET_BAN_ARG(v, d) if (argc > reason_arg) { if ((v = stof(argv(reason_arg))) != 0) ++reason_arg; else v = d; } else { v = d; }
#define GET_BAN_REASON(v, d) if (argc > reason_arg) v = substring(command, argv_start_index(reason_arg), strlen(command) - argv_start_index(reason_arg)); else v = d;
Functions
float Ban_Delete (float i)
float Ban_Insert (string ip, float bantime, string reason, float dosync)
void Ban_KickBanClient (entity client, float bantime, float masksize, string reason)
void Ban_View ()
void BanCommand_macro_help ()
float BanCommand_macro_usage (float argc)
void BanCommand_macro_write_aliases (float fh)
Macro Definition Documentation
#define GET_BAN_ARG (v, d) if (argc > reason_arg) { if ((v = stof(argv(reason_arg))) != 0) ++reason_arg; else v = d; } else { v = d; }
Definition at line 8 of file banning.qh.
Referenced by BanCommand_ban(), and BanCommand_kickban().
#define GET_BAN_REASON (v, d) if (argc > reason_arg) v = substring(command, argv_start_index(reason_arg), strlen(command) - argv_start_index(reason_arg)); else v = d;
Definition at line 9 of file banning.qh.
Referenced by BanCommand_ban(), and BanCommand_kickban().
Function Documentation
float Ban_Delete (float i)
Definition at line 284 of file ipban.qc.
References ban_count, ban_expire, ban_ip, Ban_SaveBans(), OnlineBanList_SendUnban(), and strunzone().
Referenced by Ban_Insert(), Ban_LoadBans(), and BanCommand_unban().
 {
     if(i < 0)
         return false;
     if(i >= ban_count)
         return false;
     if(ban_expire[i] == 0)
         return false;
     if(ban_expire[i] > 0)
     {
         OnlineBanList_SendUnban(ban_ip[i]);
         strunzone(ban_ip[i]);
     }
     ban_expire[i] = 0;
     ban_ip[i] = "";
     Ban_SaveBans();
     return true;
 }
float Ban_Insert (string ip, float bantime, string reason, float dosync)
Definition at line 496 of file ipban.qc.
References ban_count, Ban_Delete(), Ban_Enforce(), ban_expire, ban_ip, BAN_MAX, Ban_SaveBans(), ftos(), LOG_INFO, LOG_TRACE(), max(), OnlineBanList_SendBan(), strzone(), substring(), and time.
Referenced by Ban_KickBanClient(), BanCommand_ban(), and OnlineBanList_URI_Get_Callback().
 {
     float i;
     float j;
     float bestscore;
     // already banned?
     for(i = 0; i < ban_count; ++i)
         if(ban_ip[i] == ip)
         {
             // prolong the ban
             if(time + bantime > ban_expire[i])
             {
                 ban_expire[i] = time + bantime;
                 LOG_TRACE(ip, "'s ban has been prolonged to ", ftos(bantime), " seconds from now");
             }
             else
                 LOG_TRACE(ip, "'s ban is still active until ", ftos(ban_expire[i] - time), " seconds from now");
             // and enforce
             reason = Ban_Enforce(i, reason);
             // and abort
             if(dosync)
                 if(reason != "")
                     if(substring(reason, 0, 1) != "~") // like IRC: unauthenticated banner
                         OnlineBanList_SendBan(ip, bantime, reason);
             return false;
         }
     // do we have a free slot?
     for(i = 0; i < ban_count; ++i)
         if(time > ban_expire[i])
             break;
     // no free slot? Then look for the one who would get unbanned next
     if(i >= BAN_MAX)
     {
         i = 0;
         bestscore = ban_expire[i];
         for(j = 1; j < ban_count; ++j)
         {
             if(ban_expire[j] < bestscore)
             {
                 i = j;
                 bestscore = ban_expire[i];
             }
         }
     }
     // if we replace someone, will we be banned longer than him (so long-term
     // bans never get overridden by short-term bans)
     if(i < ban_count)
     if(ban_expire[i] > time + bantime)
     {
         LOG_INFO(ip, " could not get banned due to no free ban slot\n");
         return false;
     }
     // okay, insert our new victim as i
     Ban_Delete(i);
     LOG_TRACE(ip, " has been banned for ", ftos(bantime), " seconds");
     ban_expire[i] = time + bantime;
     ban_ip[i] = strzone(ip);
     ban_count = max(ban_count, i + 1);
     Ban_SaveBans();
     reason = Ban_Enforce(i, reason);
     // and abort
     if(dosync)
         if(reason != "")
             if(substring(reason, 0, 1) != "~") // like IRC: unauthenticated banner
                 OnlineBanList_SendBan(ip, bantime, reason);
     return true;
 }
void Ban_KickBanClient (entity client, float bantime, float masksize, string reason)
Definition at line 573 of file ipban.qc.
References Ban_GetClientIP(), ban_idfp, Ban_Insert(), ban_ip1, ban_ip2, ban_ip3, ban_ip4, sprint(), strcat(), strcat1(), and string_null.
Referenced by BanCommand_kickban().
 {
     string ip, id;
     if(!Ban_GetClientIP(client))
     {
         sprint(client, strcat("Kickbanned: ", reason, "\n"));
         dropclient(client);
         return;
     }
     // who to ban?
     switch(masksize)
     {
         case 1:
             ip = strcat1(ban_ip1);
             break;
         case 2:
             ip = strcat1(ban_ip2);
             break;
         case 3:
             ip = strcat1(ban_ip3);
             break;
         case 4:
         default:
             ip = strcat1(ban_ip4);
             break;
     }
     if(ban_idfp)
         id = strcat1(ban_idfp);
     else
         id = string_null;
     Ban_Insert(ip, bantime, reason, 1);
     if(id)
         Ban_Insert(id, bantime, reason, 1);
     /*
      * not needed, as we enforce the ban in Ban_Insert anyway
     // and kick him
     sprint(client, strcat("Kickbanned: ", reason, "\n"));
     dropclient(client);
      */
 }
void Ban_View ()
Definition at line 326 of file ipban.qc.
References ban_count, ban_expire, ban_ip, ftos(), LOG_INFO, strcat(), and time.
Referenced by BanCommand_banlist().
 {
     float i, n;
     string msg;
     LOG_INFO("^2Listing all existing active bans:\n");
     n = 0;
     for(i = 0; i < ban_count; ++i)
     {
         if(time > ban_expire[i])
             continue;
         ++n; // total number of existing bans
         msg = strcat("#", ftos(i), ": ");
         msg = strcat(msg, ban_ip[i], " is still banned for ");
         msg = strcat(msg, ftos(ban_expire[i] - time), " seconds");
         LOG_INFO("  ", msg, "\n");
     }
     LOG_INFO("^2Done listing all active (", ftos(n), ") bans.\n");
 }
void BanCommand_macro_help ()
Definition at line 275 of file banning.qc.
References BAN_COMMANDS.
Referenced by GameCommand().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (strtolower(description) != "") { LOG_INFO("  ^2", name, "^7: ", description, "\n"); } }
     BAN_COMMANDS(0, 0, "");
 #undef BAN_COMMAND
 }
float BanCommand_macro_usage (float argc)
Definition at line 295 of file banning.qc.
References BAN_COMMANDS, and CMD_REQUEST_USAGE.
Referenced by GameCommand().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (name == strtolower(argv(1))) { function; return true; } }
     BAN_COMMANDS(CMD_REQUEST_USAGE, argc, "");
 #undef BAN_COMMAND
     return false;
 }
void BanCommand_macro_write_aliases (float fh)
Definition at line 306 of file banning.qc.
References BAN_COMMANDS.
Referenced by GENERIC_COMMAND().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (strtolower(description) != "") { CMD_Write_Alias("qc_cmd_sv", name, description); } }
     BAN_COMMANDS(0, 0, "");
 #undef BAN_COMMAND
 }