Xonotic: client/view.qh File Reference
view.qh File Reference
#include <common/weapons/weapon.qh>
Functions
void calc_followmodel_ofs (entity view)
vector crosshair_getcolor (entity this, float health_stat)
void CSQC_Demo_Camera ()
void Porto_Draw (entity this)
void TrueAim_Init ()
Variables
int cursor_active
const int CURSOR_MOVE = 1
const int CURSOR_NORMAL = 0
const int CURSOR_RESIZE = 2
const int CURSOR_RESIZE2 = 3
int cursor_type
vector viewloc_mousepos
entity viewmodels [MAX_WEAPONSLOTS]
Function Documentation
void calc_followmodel_ofs (entity view)
Definition at line 128 of file view.qc.
References autocvar_cl_followmodel_highpass, autocvar_cl_followmodel_limit, autocvar_cl_followmodel_lowpass, autocvar_cl_followmodel_speed, autocvar_cl_followmodel_velocity_absolute, autocvar_cl_followmodel_velocity_lowpass, avg_factor, bound(), cl_followmodel_ofs, cl_followmodel_time, highpass3, lowpass3, MAKEVECTORS, time, vector(), and view_angles.
Referenced by Hud_Dynamic_Frame(), and viewmodel_animate().
 {
     if(cl_followmodel_time == time)
         return; // cl_followmodel_ofs already calculated for this frame
     float frac;
     vector gunorg = '0 0 0';
     static vector vel_average;
     static vector gunorg_adjustment_highpass;
     static vector gunorg_adjustment_lowpass;
     vector vel;
     if (autocvar_cl_followmodel_velocity_absolute)
         vel = view.velocity;
     else
     {
         vector forward = '0 0 0', right = '0 0 0', up = '0 0 0';
         MAKEVECTORS(makevectors, view_angles, forward, right, up);
         vel.x = view.velocity * forward;
         vel.y = view.velocity * right * -1;
         vel.z = view.velocity * up;
     }
     vel.x = bound(vel_average.x - autocvar_cl_followmodel_limit, vel.x, vel_average.x + autocvar_cl_followmodel_limit);
     vel.y = bound(vel_average.y - autocvar_cl_followmodel_limit, vel.y, vel_average.y + autocvar_cl_followmodel_limit);
     vel.z = bound(vel_average.z - autocvar_cl_followmodel_limit, vel.z, vel_average.z + autocvar_cl_followmodel_limit);
     frac = avg_factor(autocvar_cl_followmodel_velocity_lowpass);
     lowpass3(vel, frac, vel_average, gunorg);
     gunorg *= -autocvar_cl_followmodel_speed * 0.042;
     // perform highpass/lowpass on the adjustment vectors (turning velocity into acceleration!)
     // trick: we must do the lowpass LAST, so the lowpass vector IS the final vector!
     frac = avg_factor(autocvar_cl_followmodel_highpass);
     highpass3(gunorg, frac, gunorg_adjustment_highpass, gunorg);
     frac = avg_factor(autocvar_cl_followmodel_lowpass);
     lowpass3(gunorg, frac, gunorg_adjustment_lowpass, gunorg);
     if (autocvar_cl_followmodel_velocity_absolute)
     {
         vector fixed_gunorg;
         vector forward = '0 0 0', right = '0 0 0', up = '0 0 0';
         MAKEVECTORS(makevectors, view_angles, forward, right, up);
         fixed_gunorg.x = gunorg * forward;
         fixed_gunorg.y = gunorg * right * -1;
         fixed_gunorg.z = gunorg * up;
         gunorg = fixed_gunorg;
     }
     cl_followmodel_ofs = gunorg;
     cl_followmodel_time = time;
 }
vector crosshair_getcolor (entity this, float health_stat)
Definition at line 945 of file view.qc.
References armorblockpercent, autocvar_crosshair_color, autocvar_crosshair_color_special, autocvar_crosshair_color_special_rainbow_brightness, autocvar_crosshair_color_special_rainbow_delay, floor(), hud, HUD_NORMAL, LABEL, randomvec(), stov(), time, v, and vector().
Referenced by HUD_Crosshair(), and Vehicles_drawCrosshair().
 {
     static float rainbow_last_flicker;
     static vector rainbow_prev_color;
     vector wcross_color = '0 0 0';
     switch(autocvar_crosshair_color_special)
     {
         case 1: // crosshair_color_per_weapon
         {
             if(this != WEP_Null && hud == HUD_NORMAL)
             {
                 wcross_color = this.wpcolor;
                 break;
             }
             else { goto normalcolor; }
         }
         case 2: // crosshair_color_by_health
         {
             vector v = healtharmor_maxdamage(health_stat, STAT(ARMOR), armorblockpercent, DEATH_WEAPON.m_id);
             float hp = floor(v.x + 1);
             //x = red
             //y = green
             //z = blue
             wcross_color.z = 0;
             if(hp > 200)
             {
                 wcross_color.x = 0;
                 wcross_color.y = 1;
             }
             else if(hp > 150)
             {
                 wcross_color.x = 0.4 - (hp-150)*0.02 * 0.4;
                 wcross_color.y = 0.9 + (hp-150)*0.02 * 0.1;
             }
             else if(hp > 100)
             {
                 wcross_color.x = 1 - (hp-100)*0.02 * 0.6;
                 wcross_color.y = 1 - (hp-100)*0.02 * 0.1;
                 wcross_color.z = 1 - (hp-100)*0.02;
             }
             else if(hp > 50)
             {
                 wcross_color.x = 1;
                 wcross_color.y = 1;
                 wcross_color.z = 0.2 + (hp-50)*0.02 * 0.8;
             }
             else if(hp > 20)
             {
                 wcross_color.x = 1;
                 wcross_color.y = (hp-20)*90/27/100;
                 wcross_color.z = (hp-20)*90/27/100 * 0.2;
             }
             else
             {
                 wcross_color.x = 1;
                 wcross_color.y = 0;
             }
             break;
         }
         case 3: // crosshair_color_rainbow
         {
             if(time >= rainbow_last_flicker)
             {
                 rainbow_prev_color = randomvec() * autocvar_crosshair_color_special_rainbow_brightness;
                 rainbow_last_flicker = time + autocvar_crosshair_color_special_rainbow_delay;
             }
             wcross_color = rainbow_prev_color;
             break;
         }
 LABEL(normalcolor)
         default: { wcross_color = stov(autocvar_crosshair_color); break; }
     }
     return wcross_color;
 }
void CSQC_Demo_Camera ()
Definition at line 2542 of file view.qc.
References autocvar_camera_chase_smoothly, autocvar_camera_forward_follows, autocvar_camera_free, autocvar_camera_look_attenuation, autocvar_camera_look_player, autocvar_camera_mouse_threshold, autocvar_camera_reset, autocvar_camera_speed_attenuation, autocvar_camera_speed_chase, autocvar_camera_speed_free, autocvar_camera_speed_roll, CAMERA_CHASE, camera_direction, CAMERA_FREE, camera_mode, camera_offset, camera_roll, cos(), current_angles, current_camera_offset, current_origin, current_position, cvar_set(), DEG2RAD, getmousepos(), max(), mouse_angles, normalize(), sin(), speed, sqrt(), vdist, vectoangles(), vector(), VF_ANGLES, VF_ORIGIN, and view_origin.
Referenced by CSQC_UpdateView().
 {
     float speed, attenuation, dimensions;
     vector tmp, delta;
     if( autocvar_camera_reset || !camera_mode )
     {
         camera_offset = '0 0 0';
         current_angles = '0 0 0';
         camera_direction = '0 0 0';
         camera_offset.z += 30;
         camera_offset.x += 30 * -cos(current_angles.y * DEG2RAD);
         camera_offset.y += 30 * -sin(current_angles.y * DEG2RAD);
         current_origin = view_origin;
         current_camera_offset  = camera_offset;
         cvar_set("camera_reset", "0");
         camera_mode = CAMERA_CHASE;
     }
     // Camera angles
     if( camera_roll )
         mouse_angles.z += camera_roll * autocvar_camera_speed_roll;
     if(autocvar_camera_look_player)
     {
         vector dir;
         float n;
         dir = normalize(view_origin - current_position);
         n = mouse_angles.z;
         mouse_angles = vectoangles(dir);
         mouse_angles.x = mouse_angles.x * -1;
         mouse_angles.z = n;
     }
     else
     {
         tmp = getmousepos() * 0.1;
         if(vdist(tmp, >, autocvar_camera_mouse_threshold))
         {
             mouse_angles.x += tmp.y * cos(mouse_angles.z * DEG2RAD) + (tmp.x * sin(mouse_angles.z * DEG2RAD));
             mouse_angles.y -= tmp.x * cos(mouse_angles.z * DEG2RAD) + (tmp.y * -sin(mouse_angles.z * DEG2RAD));
         }
     }
     while (mouse_angles.x < -180) mouse_angles.x = mouse_angles.x + 360;
     while (mouse_angles.x > 180) mouse_angles.x = mouse_angles.x - 360;
     while (mouse_angles.y < -180) mouse_angles.y = mouse_angles.y + 360;
     while (mouse_angles.y > 180) mouse_angles.y = mouse_angles.y - 360;
     // Fix difference when angles don't have the same sign
     delta = '0 0 0';
     if(mouse_angles.y < -60 && current_angles.y > 60)
         delta = '0 360 0';
     if(mouse_angles.y > 60 && current_angles.y < -60)
         delta = '0 -360 0';
     if(autocvar_camera_look_player)
         attenuation = autocvar_camera_look_attenuation;
     else
         attenuation = autocvar_camera_speed_attenuation;
     attenuation = 1 / max(1, attenuation);
     current_angles += (mouse_angles - current_angles + delta) * attenuation;
     while (current_angles.x < -180) current_angles.x = current_angles.x + 360;
     while (current_angles.x > 180) current_angles.x = current_angles.x - 360;
     while (current_angles.y < -180) current_angles.y = current_angles.y + 360;
     while (current_angles.y > 180) current_angles.y = current_angles.y - 360;
     // Camera position
     tmp = '0 0 0';
     dimensions = 0;
     if( camera_direction.x )
     {
         tmp.x = camera_direction.x * cos(current_angles.y * DEG2RAD);
         tmp.y = camera_direction.x * sin(current_angles.y * DEG2RAD);
         if( autocvar_camera_forward_follows && !autocvar_camera_look_player )
             tmp.z = camera_direction.x * -sin(current_angles.x * DEG2RAD);
         ++dimensions;
     }
     if( camera_direction.y )
     {
         tmp.x += camera_direction.y * -sin(current_angles.y * DEG2RAD);
         tmp.y += camera_direction.y * cos(current_angles.y * DEG2RAD) * cos(current_angles.z * DEG2RAD);
         tmp.z += camera_direction.y * sin(current_angles.z * DEG2RAD);
         ++dimensions;
     }
     if( camera_direction.z )
     {
         tmp.z += camera_direction.z * cos(current_angles.z * DEG2RAD);
         ++dimensions;
     }
     if(autocvar_camera_free)
         speed = autocvar_camera_speed_free;
     else
         speed = autocvar_camera_speed_chase;
     if(dimensions)
     {
         speed = speed * sqrt(1 / dimensions);
         camera_offset += tmp * speed;
     }
     current_camera_offset += (camera_offset - current_camera_offset) * attenuation;
     // Camera modes
     if( autocvar_camera_free )
     {
         if ( camera_mode == CAMERA_CHASE )
         {
             current_camera_offset = current_origin + current_camera_offset;
             camera_offset = current_origin + camera_offset;
         }
         camera_mode = CAMERA_FREE;
         current_position = current_camera_offset;
     }
     else
     {
         if ( camera_mode == CAMERA_FREE )
         {
             current_origin = view_origin;
             camera_offset = camera_offset - current_origin;
             current_camera_offset = current_camera_offset - current_origin;
         }
         camera_mode = CAMERA_CHASE;
         if(autocvar_camera_chase_smoothly)
             current_origin += (view_origin - current_origin) * attenuation;
         else
             current_origin = view_origin;
         current_position = current_origin + current_camera_offset;
     }
     setproperty(VF_ANGLES, current_angles);
     setproperty(VF_ORIGIN, current_position);
 }
void Porto_Draw (entity this)
Definition at line 413 of file view.qc.
References autocvar_chase_active, DPCONTENTS_PLAYERCLIP, DRAWFLAG_NORMAL, entity(), intermission, max(), MAX_WEAPONSLOTS, p, polyline_length, Q3SURFACEFLAG_NOIMPACT, Q3SURFACEFLAG_SLICK, reflect(), spectatee_status, trace_dphitcontents, trace_dphitq3surfaceflags, trace_endpos, trace_plane_normal, v_forward, v_right, v_up, vector(), view_angles, view_forward, view_origin, view_up, viewmodels, warpzone_save_view_angles, and WEP_CVAR.
Referenced by STATIC_INIT().
 {
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         entity wepent = viewmodels[slot];
         if (wepent.activeweapon != WEP_PORTO) continue;
         if (spectatee_status) continue;
         if (WEP_CVAR(porto, secondary)) continue;
         if (intermission == 1) continue;
         if (intermission == 2) continue;
         if (STAT(HEALTH) <= 0) continue;
         vector pos = view_origin;
         vector dir = view_forward;
         makevectors(((autocvar_chase_active) ? warpzone_save_view_angles : view_angles));
         pos += v_right * -wepent.movedir.y
             +  v_up * wepent.movedir.z;
         if (wepent.angles_held_status)
         {
             makevectors(wepent.angles_held);
             dir = v_forward;
         }
         wepent.polyline[0] = pos;
         int portal_number = 0, portal1_idx = 1, portal_max = 2;
         int n = 1 + 2;  // 2 lines == 3 points
         for (int idx = 0; idx < n && idx < polyline_length - 1; )
         {
             traceline(pos, pos + 65536 * dir, true, this);
             dir = reflect(dir, trace_plane_normal);
             pos = trace_endpos;
             wepent.polyline[++idx] = pos;
             if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_SLICK || trace_dphitcontents & DPCONTENTS_PLAYERCLIP)
             {
                 n += 1;
                 continue;
             }
             if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOIMPACT)
             {
                 n = max(2, idx);
                 break;
             }
             // check size
             {
                 vector ang = vectoangles2(trace_plane_normal, dir);
                 ang.x = -ang.x;
                 makevectors(ang);
                 if (!CheckWireframeBox(this, pos - 48 * v_right - 48 * v_up + 16 * v_forward, 96 * v_right, 96 * v_up, 96 * v_forward))
                 {
                     n = max(2, idx);
                     break;
                 }
             }
             portal_number += 1;
             if (portal_number >= portal_max) break;
             if (portal_number == 1) portal1_idx = idx;
         }
         for (int idx = 0; idx < n - 1; ++idx)
         {
             vector p = wepent.polyline[idx], q = wepent.polyline[idx + 1];
             if (idx == 0) p -= view_up * 16;  // line from player
             vector rgb = (idx < portal1_idx) ? '1 0 0' : '0 0 1';
             Draw_CylindricLine(p, q, 4, "", 1, 0, rgb, 0.5, DRAWFLAG_NORMAL, view_origin);
         }
     }
 }
void TrueAim_Init ()
Definition at line 660 of file view.qc.
References DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, dphitcontentsmask, new_pure, trueaim, and trueaim_rifle.
Referenced by PostInit().
 {
     (trueaim = new_pure(trueaim)).dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
     (trueaim_rifle = new_pure(trueaim_rifle)).dphitcontentsmask = DPCONTENTS_BODY | DPCONTENTS_CORPSE;
 }
Variable Documentation
int cursor_active
Definition at line 19 of file view.qh.
Referenced by HUD_Main(), HUD_Mouse(), and PM_UpdateButtons().
const int CURSOR_MOVE = 1
Definition at line 22 of file view.qh.
Referenced by HUD_Cursor_Show(), and HUD_Panel_Check_Mouse_Pos().
const int CURSOR_NORMAL = 0
Definition at line 21 of file view.qh.
Referenced by HUD_Configure_Exit_Force(), HUD_Cursor_Show(), HUD_Panel_Check_Mouse_Pos(), and HUD_Panel_Mouse().
const int CURSOR_RESIZE = 2
Definition at line 23 of file view.qh.
Referenced by HUD_Cursor_Show(), and HUD_Panel_Check_Mouse_Pos().
const int CURSOR_RESIZE2 = 3
Definition at line 24 of file view.qh.
Referenced by HUD_Cursor_Show(), and HUD_Panel_Check_Mouse_Pos().
int cursor_type
Definition at line 20 of file view.qh.
Referenced by HUD_Configure_Exit_Force(), HUD_Cursor_Show(), and HUD_Panel_Mouse().
vector viewloc_mousepos
Definition at line 17 of file view.qh.
Referenced by HUD_Crosshair(), and ViewLocation_Mouse().
entity viewmodels[MAX_WEAPONSLOTS]
Definition at line 15 of file view.qh.
Referenced by CSQC_UpdateView(), GetCurrentFov(), HitSound(), HUD_Ammo(), HUD_Crosshair(), HUD_Weapons(), PM_ClientMovement_UpdateStatus(), Porto_Draw(), and STATIC_INIT().