Xonotic: ecs/systems/sv_physics.qc File Reference
sv_physics.qc File Reference
#include "physics.qh"
Functions
STATIC_INIT (sys_phys)
void sys_phys_ai (entity this)
void sys_phys_fix (entity this, float dt)
void sys_phys_fixspeed (entity this, float maxspeed_mod)
void sys_phys_land (entity this)
void sys_phys_monitor (entity this, float dt)
bool sys_phys_override (entity this, float dt)
void sys_phys_pregame_hold (entity this)
void sys_phys_spectator_control (entity this)
Function Documentation
STATIC_INIT (sys_phys)
Definition at line 118 of file sv_physics.qc.
References entity(), new_pure, subscribe, and sys_phys_land().
 {
     entity listener = new_pure(sys_phys);
     subscribe(listener, phys_land, sys_phys_land);
 }
void sys_phys_ai (entity this)
Definition at line 35 of file sv_physics.qc.
References bot_think(), IS_BOT_CLIENT, and playerdemo_read().
 {
     if (!IS_BOT_CLIENT(this)) { return; }
     if (playerdemo_read(this)) { return; }
     bot_think(this);
 }
void sys_phys_fix (entity this, float dt)
Definition at line 3 of file sv_physics.qc.
References autocvar_g_movement_highspeed, items, movement, MUTATOR_CALLHOOK, PHYS_HIGHSPEED, PHYS_INPUT_BUTTON_JUMP, PHYS_WATERJUMP_TIME, PM_ClientMovement_UpdateStatus(), team, and UNSET_JUMP_HELD.
 {
     WarpZone_PlayerPhysics_FixVAngle(this);
     STAT(MOVEVARS_HIGHSPEED, this) = autocvar_g_movement_highspeed;
     MUTATOR_CALLHOOK(PlayerPhysics_UpdateStats, this); // do it BEFORE the function so we can modify highspeed!
     Physics_UpdateStats(this, PHYS_HIGHSPEED(this));
 }
void sys_phys_fixspeed (entity this, float maxspeed_mod)
Definition at line 85 of file sv_physics.qc.
References autocvar_sv_jumpspeedcap_max, autocvar_sv_jumpspeedcap_min, ftos(), max(), PHYS_MAXAIRSPEED, PHYS_MAXSPEED, speed, strcat(), and stuffcmd.
 {
     float spd = max(PHYS_MAXSPEED(this), PHYS_MAXAIRSPEED(this)) * maxspeed_mod;
     if (this.speed != spd) {
         this.speed = spd;
         string temps = ftos(spd);
         stuffcmd(this, strcat("cl_forwardspeed ", temps, "\n"));
         stuffcmd(this, strcat("cl_backspeed ", temps, "\n"));
         stuffcmd(this, strcat("cl_sidespeed ", temps, "\n"));
         stuffcmd(this, strcat("cl_upspeed ", temps, "\n"));
     }
     if (this.jumpspeedcap_min != autocvar_sv_jumpspeedcap_min) {
         this.jumpspeedcap_min = autocvar_sv_jumpspeedcap_min;
         stuffcmd(this, sprintf("\ncl_jumpspeedcap_min \"%s\"\n", autocvar_sv_jumpspeedcap_min));
     }
     if (this.jumpspeedcap_max != autocvar_sv_jumpspeedcap_max) {
         this.jumpspeedcap_max = autocvar_sv_jumpspeedcap_max;
         stuffcmd(this, sprintf("\ncl_jumpspeedcap_max \"%s\"\n", autocvar_sv_jumpspeedcap_max));
     }
 }
void sys_phys_land (entity this)
Definition at line 107 of file sv_physics.qc.
References autocvar_speedmeter, jumppadcount, LOG_TRACEF, velocity, and vlen().
Referenced by STATIC_INIT().
 {
     if (autocvar_speedmeter) {
         LOG_TRACEF("landing velocity: %v (abs: %f)", this.velocity, vlen(this.velocity));
     }
     if (this.jumppadcount > 1) {
         LOG_TRACEF("%dx jumppad combo", this.jumppadcount);
     }
     this.jumppadcount = 0;
 }
void sys_phys_monitor (entity this, float dt)
Definition at line 22 of file sv_physics.qc.
References anticheat_physics(), buttons_old, movement, movement_old, parm_idlesince, PHYS_INPUT_BUTTON_MASK, PM_check_nickspam(), PM_check_punch(), sv_maxidle, time, v_angle, and v_angle_old.
 {
     int buttons = PHYS_INPUT_BUTTON_MASK(this);
     anticheat_physics(this);
     if (sv_maxidle > 0) {
         if (buttons != this.buttons_old
             || this.movement != this.movement_old
             || this.v_angle != this.v_angle_old) { this.parm_idlesince = time; }
     }
     PM_check_nickspam(this);
     PM_check_punch(this, dt);
 }
bool sys_phys_override (entity this, float dt)
Definition at line 11 of file sv_physics.qc.
References hud, HUD_NORMAL, parm_idlesince, PHYS_INPUT_BUTTON_MASK, PM_check_specialcommand(), and time.
 {
     int buttons = PHYS_INPUT_BUTTON_MASK(this);
     float idlesince = this.parm_idlesince;
     this.parm_idlesince = time; // in the case that physics are overridden
     if (PM_check_specialcommand(this, buttons)) { return true; }
     if (this.PlayerPhysplug && this.PlayerPhysplug(this, dt)) { return true; }
     this.parm_idlesince = idlesince;
     return false;
 }
void sys_phys_pregame_hold (entity this)
Definition at line 42 of file sv_physics.qc.
References disableclientprediction, game_starttime, IS_PLAYER, move_movetype, MOVETYPE_NONE, MOVETYPE_WALK, set_movetype(), time, and velocity.
 {
     if (!IS_PLAYER(this)) { return; }
     const bool allowed_to_move = (time >= game_starttime && !game_stopped);
     if (!allowed_to_move) {
         this.velocity = '0 0 0';
         set_movetype(this, MOVETYPE_NONE);
         this.disableclientprediction = 2;
     } else if (this.disableclientprediction == 2) {
         if (this.move_movetype == MOVETYPE_NONE) { set_movetype(this, MOVETYPE_WALK); }
         this.disableclientprediction = 0;
     }
 }
void sys_phys_spectator_control (entity this)
Definition at line 56 of file sv_physics.qc.
References autocvar_sv_spectator_speed_multiplier, bound(), impulse, lastclassname, and STR_PLAYER.
 {
     float maxspeed_mod = autocvar_sv_spectator_speed_multiplier;
     if (!this.spectatorspeed) { this.spectatorspeed = maxspeed_mod; }
     if ((this.impulse >= 1 && this.impulse <= 19)
         || (this.impulse >= 200 && this.impulse <= 209)
         || (this.impulse >= 220 && this.impulse <= 229)
        ) {
         if (this.lastclassname != STR_PLAYER) {
             if (this.impulse == 10
                 || this.impulse == 15
                 || this.impulse == 18
                 || (this.impulse >= 200 && this.impulse <= 209)
                ) { this.spectatorspeed = bound(1, this.spectatorspeed + 0.5, 5); } else if (this.impulse == 11) {
                 this.spectatorspeed = maxspeed_mod;
             } else if (this.impulse == 12
                 || this.impulse == 16
                 || this.impulse == 19
                 || (this.impulse >= 220 && this.impulse <= 229)
                       ) {
                 this.spectatorspeed = bound(1, this.spectatorspeed - 0.5, 5);
             } else if (this.impulse >= 1 && this.impulse <= 9) {
                 this.spectatorspeed = 1 + 0.5 * (this.impulse - 1);
             }
         }  // otherwise just clear
         this.impulse = 0;
     }
 }