Xonotic: lib/warpzone/mathlib.qh File Reference
mathlib.qh File Reference
Macros
#define LIB_WARPZONE_MATHLIB_H
#define M_PI 3.14159265358979323846 /* pi */
Functions
float acosh (float x)
float asinh (float x)
float atanh (float x)
float cbrt (float x)
float copysign (float x, float y)
float cosh (float x)
float erf (float x)
float erfc (float x)
float exp (float x)
float exp2 (float x)
float expm1 (float x)
float fdim (float x, float y)
float fma (float x, float y, float z)
float fmax (float x, float y)
float fmin (float x, float y)
float fmod (float x, float y)
int fpclassify (float x)
vector frexp (float x)
float hypot (float x, float y)
int ilogb (float x)
bool isfinite (float x)
int isgreater (float x, float y)
int isgreaterequal (float x, float y)
bool isinf (float x)
int isless (float x, float y)
int islessequal (float x, float y)
int islessgreater (float x, float y)
bool isnan (float x)
bool isnormal (float x)
int isunordered (float x, float y)
float ldexp (float x, int e)
vector lgamma (float x)
float log10 (float x)
float log1p (float x)
float log2 (float x)
float logb (float x)
float logn (float x, float base)
vector modf (float f)
float nan (string tag)
float nearbyint (float x)
float nextafter (float x, float y)
float nexttoward (float x, float y)
float pymod (float x, float y)
Pythonic mod: TODO: %% operator?
float remainder (float x, float y)
vector remquo (float x, float y)
float scalbn (float x, int n)
bool signbit (float x)
float sinh (float x)
float tanh (float x)
float tgamma (float x)
float trunc (float x)
Variables
const int FP_INFINITE = 1
const int FP_NAN = 0
const int FP_NORMAL = 4
const int FP_SUBNORMAL = 3
const int FP_ZERO = 2
const float M_1_PI = 0.31830988618379067154
const float M_2_PI = 0.63661977236758134308
const float M_2_SQRTPI = 1.12837916709551257390
const float M_E = 2.7182818284590452354
const float M_LN10 = 2.30258509299404568402
const float M_LN2 = 0.69314718055994530942
const float M_LOG10E = 0.43429448190325182765
const float M_LOG2E = 1.4426950408889634074
const float M_PI_2 = 1.57079632679489661923
const float M_PI_4 = 0.78539816339744830962
const float M_SQRT1_2 = 0.70710678118654752440
const float M_SQRT2 = 1.41421356237309504880
Macro Definition Documentation
#define LIB_WARPZONE_MATHLIB_H
Definition at line 2 of file mathlib.qh.
#define M_PI 3.14159265358979323846 /* pi */
Definition at line 109 of file mathlib.qh.
Function Documentation
float acosh (float x)
Definition at line 40 of file mathlib.qc.
References log(), and sqrt().
 {
     return log(x + sqrt(x*x - 1));
 }
float asinh (float x)
Definition at line 44 of file mathlib.qc.
References log(), and sqrt().
 {
     return log(x + sqrt(x*x + 1));
 }
float atanh (float x)
Definition at line 48 of file mathlib.qc.
References log().
 {
     return 0.5 * log((1+x) / (1-x));
 }
float cbrt (float x)
Definition at line 124 of file mathlib.qc.
References copysign(), fabs(), and pow().
Referenced by solve_cubic_pq().
 {
     return copysign(pow(fabs(x), 1.0/3.0), x);
 }
float copysign (float x, float y)
Definition at line 218 of file mathlib.qc.
References fabs().
Referenced by AdjustAirAccelQW(), cbrt(), erf(), and lgamma().
 {
     return fabs(x) * ((y>0) ? 1 : -1);
 }
float cosh (float x)
Definition at line 52 of file mathlib.qc.
References exp().
Referenced by tanh().
 {
     return 0.5 * (exp(x) + exp(-x));
 }
float erf (float x)
Definition at line 133 of file mathlib.qc.
References copysign(), exp(), and sqrt().
Referenced by erfc().
 {
     // approximation taken from wikipedia
     float y;
     y = x*x;
     return copysign(sqrt(1 - exp(-y * (1.273239544735163 + 0.14001228868667 * y) / (1 + 0.14001228868667 * y))), x);
 }
float erfc (float x)
Definition at line 140 of file mathlib.qc.
References erf().
 {
     return 1.0 - erf(x);
 }
float exp (float x)
Definition at line 65 of file mathlib.qc.
References M_E, and pow().
Referenced by anticheat_physics(), cosh(), erf(), expm1(), fromDecibelOfSquare(), GenericCommand_rpn(), GetCurrentFov(), ListBox_draw(), sinh(), tgamma(), and toDecibelOfSquare().
 {
     return pow(M_E, x);
 }
float exp2 (float x)
Definition at line 69 of file mathlib.qc.
References pow().
Referenced by frexp().
 {
     return pow(2, x);
 }
float expm1 (float x)
Definition at line 73 of file mathlib.qc.
References exp().
 {
     return exp(x) - 1;
 }
float fdim (float x, float y)
Definition at line 252 of file mathlib.qc.
References max().
 {
     return max(x-y, 0);
 }
float fma (float x, float y, float z)
Definition at line 264 of file mathlib.qc.
 {
     return x * y + z;
 }
float fmax (float x, float y)
Definition at line 256 of file mathlib.qc.
References max().
 {
     return max(x, y);
 }
float fmin (float x, float y)
Definition at line 260 of file mathlib.qc.
References min().
 {
     return min(x, y);
 }
float fmod (float x, float y)
Definition at line 201 of file mathlib.qc.
References trunc().
Referenced by CSQCModel_Effects_Apply().
 {
     return x - y * trunc(x / y);
 }
int fpclassify (float x)
Definition at line 7 of file mathlib.qc.
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_ZERO, isinf(), and isnan().
 {
     if(isnan(x))
         return FP_NAN;
     if(isinf(x))
         return FP_INFINITE;
     if(x == 0)
         return FP_ZERO;
     return FP_NORMAL;
 }
vector frexp (float x)
Definition at line 78 of file mathlib.qc.
References exp2(), ilogb(), and vector.
 {
     vector v;
     v.z = 0;
     v.y = ilogb(x) + 1;
     v.x = x / exp2(v.y);
     return v;
 }
float hypot (float x, float y)
Definition at line 128 of file mathlib.qc.
References sqrt().
 {
     return sqrt(x*x + y*y);
 }
int ilogb (float x)
Definition at line 86 of file mathlib.qc.
References fabs(), floor(), and log2().
Referenced by frexp().
 {
     return floor(log2(fabs(x)));
 }
bool isfinite (float x)
Definition at line 17 of file mathlib.qc.
References isinf(), and isnan().
Referenced by isnormal(), and lgamma().
 {
     return !(isnan(x) || isinf(x));
 }
int isgreater (float x, float y)
Definition at line 269 of file mathlib.qc.
 {
     return x > y;
 }
int isgreaterequal (float x, float y)
Definition at line 273 of file mathlib.qc.
 {
     return x >= y;
 }
bool isinf (float x)
Definition at line 21 of file mathlib.qc.
Referenced by fpclassify(), and isfinite().
 {
     return (x != 0) && (x + x == x);
 }
int isless (float x, float y)
Definition at line 277 of file mathlib.qc.
 {
     return x < y;
 }
int islessequal (float x, float y)
Definition at line 281 of file mathlib.qc.
 {
     return x <= y;
 }
int islessgreater (float x, float y)
Definition at line 285 of file mathlib.qc.
 {
     return x < y || x > y;
 }
bool isnan (float x)
Definition at line 25 of file mathlib.qc.
Referenced by fpclassify(), and isfinite().
 {
     float y;
     y = x;
     return (x != y);
 }
bool isnormal (float x)
Definition at line 31 of file mathlib.qc.
References isfinite().
 {
     return isfinite(x);
 }
int isunordered (float x, float y)
Definition at line 289 of file mathlib.qc.
 {
     return !(x < y || x == y || x > y);
 }
float ldexp (float x, int e)
Definition at line 90 of file mathlib.qc.
References pow().
 {
     return x * pow(2, e);
 }
vector lgamma (float x)
Definition at line 144 of file mathlib.qc.
References copysign(), fabs(), floor(), isfinite(), lgamma(), log(), M_PI, nan(), sin(), and vector.
Referenced by lgamma(), and tgamma().
 {
     // TODO improve accuracy
     if(!isfinite(x))
         return fabs(x) * '1 0 0' + copysign(1, x) * '0 1 0';
     if(x < 1 && x == floor(x))
         return nan("gamma") * '1 1 1';
     if(x < 0.1)
     {
         vector v;
         v = lgamma(1.0 - x);
         // reflection formula:
         // gamma(1-z) * gamma(z) = pi / sin(pi*z)
         // lgamma(1-z) + lgamma(z) = log(pi) - log(sin(pi*z))
         // sign of gamma(1-z) = sign of gamma(z) * sign of sin(pi*z)
         v.z = sin(M_PI * x);
         v.x = log(M_PI) - log(fabs(v.z)) - v.x;
         if(v.z < 0)
             v.y = -v.y;
         v.z = 0;
         return v;
     }
     if(x < 1.1)
         return lgamma(x + 1) - log(x) * '1 0 0';
     x -= 1;
     return (0.5 * log(2 * M_PI * x) + x * (log(x) - 1)) * '1 0 0' + '0 1 0';
 }
float log10 (float x)
Definition at line 98 of file mathlib.qc.
References log(), and M_LOG10E.
 {
     return log(x) * M_LOG10E;
 }
float log1p (float x)
Definition at line 102 of file mathlib.qc.
References log().
 {
     return log(x + 1);
 }
float log2 (float x)
Definition at line 106 of file mathlib.qc.
References log(), and M_LOG2E.
Referenced by ilogb(), and logb().
 {
     return log(x) * M_LOG2E;
 }
float logb (float x)
Definition at line 110 of file mathlib.qc.
References fabs(), floor(), and log2().
 {
     return floor(log2(fabs(x)));
 }
float logn (float x, float base)
Definition at line 94 of file mathlib.qc.
References log().
 {
     return log(x) / log(base);
 }
vector modf (float f)
Definition at line 114 of file mathlib.qc.
References trunc().
 {
     return '1 0 0' * (f - trunc(f)) + '0 1 0' * trunc(f);
 }
float nan (string tag)
Definition at line 222 of file mathlib.qc.
References sqrt().
Referenced by lgamma(), and nextafter().
 {
     return sqrt(-1);
 }
float nearbyint (float x)
Definition at line 192 of file mathlib.qc.
References rint().
 {
     return rint(x);
 }
float nextafter (float x, float y)
Definition at line 226 of file mathlib.qc.
References fabs(), max(), nan(), and nextafter().
Referenced by nextafter(), and nexttoward().
 {
     // TODO very crude
     if(x == y)
         return nan("nextafter");
     if(x > y)
         return -nextafter(-x, -y);
     // now we know that x < y
     // so we need the next number > x
     float d, a, b;
     d = max(fabs(x), 0.00000000000000000000001);
     a = x + d;
     do
     {
         d *= 0.5;
         b = a;
         a = x + d;
     }
     while(a != x);
     return b;
 }
float nexttoward (float x, float y)
Definition at line 247 of file mathlib.qc.
References nextafter().
 {
     return nextafter(x, y);
 }
float pymod (float x, float y)
Pythonic mod: TODO: %% operator?
1 % 2 == 1 -1 % 2 == 1 1 % -2 == -1 -1 % -2 == -1
Definition at line 187 of file mathlib.qc.
References floor().
 {
     return x - y * floor(x / y);
 }
float remainder (float x, float y)
Definition at line 205 of file mathlib.qc.
References rint().
Referenced by IsMoveInDirection().
 {
     return x - y * rint(x / y);
 }
vector remquo (float x, float y)
Definition at line 209 of file mathlib.qc.
References rint(), and vector.
 {
     vector v;
     v.z = 0;
     v.y = rint(x / y);
     v.x = x - y * v.y;
     return v;
 }
float scalbn (float x, int n)
Definition at line 119 of file mathlib.qc.
References pow().
 {
     return x * pow(2, n);
 }
bool signbit (float x)
Definition at line 35 of file mathlib.qc.
 {
     return (x < 0);
 }
float sinh (float x)
Definition at line 56 of file mathlib.qc.
References exp().
Referenced by tanh().
 {
     return 0.5 * (exp(x) - exp(-x));
 }
float tanh (float x)
Definition at line 60 of file mathlib.qc.
References cosh(), and sinh().
 {
     return sinh(x) / cosh(x);
 }
float tgamma (float x)
Definition at line 171 of file mathlib.qc.
References exp(), lgamma(), and vector.
 {
     vector v;
     v = lgamma(x);
     return exp(v.x) * v.y;
 }
float trunc (float x)
Definition at line 196 of file mathlib.qc.
References ceil(), and floor().
Referenced by fmod(), and modf().
 {
     return (x>=0) ? floor(x) : ceil(x);
 }
Variable Documentation
const int FP_INFINITE = 1
Definition at line 10 of file mathlib.qh.
Referenced by fpclassify().
const int FP_NAN = 0
Definition at line 9 of file mathlib.qh.
Referenced by fpclassify().
const int FP_NORMAL = 4
Definition at line 13 of file mathlib.qh.
Referenced by fpclassify().
const int FP_SUBNORMAL = 3
Definition at line 12 of file mathlib.qh.
const int FP_ZERO = 2
Definition at line 11 of file mathlib.qh.
Referenced by fpclassify().
const float M_1_PI = 0.31830988618379067154
Definition at line 112 of file mathlib.qh.
const float M_2_PI = 0.63661977236758134308
Definition at line 113 of file mathlib.qh.
const float M_2_SQRTPI = 1.12837916709551257390
Definition at line 114 of file mathlib.qh.
const float M_E = 2.7182818284590452354
Definition at line 103 of file mathlib.qh.
Referenced by exp().
const float M_LN10 = 2.30258509299404568402
Definition at line 107 of file mathlib.qh.
const float M_LN2 = 0.69314718055994530942
Definition at line 106 of file mathlib.qh.
const float M_LOG10E = 0.43429448190325182765
Definition at line 105 of file mathlib.qh.
Referenced by log10().
const float M_LOG2E = 1.4426950408889634074
Definition at line 104 of file mathlib.qh.
Referenced by log2().
const float M_PI_2 = 1.57079632679489661923
Definition at line 110 of file mathlib.qh.
const float M_PI_4 = 0.78539816339744830962
Definition at line 111 of file mathlib.qh.
const float M_SQRT1_2 = 0.70710678118654752440
Definition at line 116 of file mathlib.qh.
const float M_SQRT2 = 1.41421356237309504880
Definition at line 115 of file mathlib.qh.