Xonotic: menu/xonotic/crosshairpicker.qc File Reference
crosshairpicker.qc File Reference
#include "crosshairpicker.qh"
Functions
string crosshairpicker_cellToCrosshair (entity me, vector cell)
vector crosshairpicker_crosshairToCell (entity me, string crosshair_str)
entity makeXonoticCrosshairPicker ()
void XonoticCrosshairPicker_cellDraw (entity me, vector cell, vector cellPos)
bool XonoticCrosshairPicker_cellIsValid (entity me, vector cell)
void XonoticCrosshairPicker_cellSelect (entity me, vector cell)
void XonoticCrosshairPicker_configureXonoticCrosshairPicker (entity me)
Function Documentation
string crosshairpicker_cellToCrosshair (entity me, vector cell)
Definition at line 3 of file crosshairpicker.qc.
References ftos().
Referenced by XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPicker_cellIsValid(), and XonoticCrosshairPicker_cellSelect().
 {
     if(cell.x < 0 || cell.x >= me.columns || cell.y < 0 || cell.y >= me.rows)
         return "";
     return ftos(31 + cell.y * me.columns + cell.x);
 }
vector crosshairpicker_crosshairToCell (entity me, string crosshair_str)
Definition at line 10 of file crosshairpicker.qc.
References eX, eY, floor(), mod(), and stof().
Referenced by XonoticCrosshairPicker_configureXonoticCrosshairPicker().
 {
     float crosshair = stof(crosshair_str) - 31;
     if(crosshair - floor(crosshair) > 0)
         return '-1 -1 0';
     return mod(crosshair, me.columns) * eX + floor(crosshair / me.columns) * eY;
 }
entity makeXonoticCrosshairPicker ()
Definition at line 18 of file crosshairpicker.qc.
References entity(), and NEW.
Referenced by XonoticGameCrosshairSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticCrosshairPicker);
     me.configureXonoticCrosshairPicker(me);
     return me;
 }
void XonoticCrosshairPicker_cellDraw (entity me, vector cell, vector cellPos)
Definition at line 45 of file crosshairpicker.qc.
References crosshairpicker_cellToCrosshair(), cvar(), draw_Picture(), draw_PictureSize(), globalToBoxSize(), strcat(), and vector().
 {
     string s = strcat("/gfx/crosshair", crosshairpicker_cellToCrosshair(me, cell));
     vector sz = draw_PictureSize(s);
     sz = globalToBoxSize(sz, me.size);
     float ar = sz.x / sz.y;
     sz.x = me.realCellSize.x;
     sz.y = sz.x / ar;
     sz *= 0.95;
     vector crosshairPos = cellPos + 0.5 * me.realCellSize;
     draw_Picture(crosshairPos - 0.5 * sz, s, sz, SKINCOLOR_CROSSHAIRPICKER_CROSSHAIR, SKINALPHA_CROSSHAIRPICKER_CROSSHAIR);
     if(cvar("crosshair_dot"))
         draw_Picture(crosshairPos - 0.5 * sz * cvar("crosshair_dot_size"), "/gfx/crosshairdot", sz * cvar("crosshair_dot_size"), SKINCOLOR_CROSSHAIRPICKER_CROSSHAIR, SKINALPHA_CROSSHAIRPICKER_CROSSHAIR);
 }
bool XonoticCrosshairPicker_cellIsValid (entity me, vector cell)
Definition at line 38 of file crosshairpicker.qc.
References crosshairpicker_cellToCrosshair().
 {
     if(crosshairpicker_cellToCrosshair(me, cell) == "")
         return false;
     return true;
 }
void XonoticCrosshairPicker_cellSelect (entity me, vector cell)
Definition at line 32 of file crosshairpicker.qc.
References crosshairpicker_cellToCrosshair(), cvar_set(), and SUPER.
 {
     cvar_set("crosshair", crosshairpicker_cellToCrosshair(me, me.focusedCell));
     SUPER(XonoticCrosshairPicker).cellSelect(me, me.focusedCell);
 }
void XonoticCrosshairPicker_configureXonoticCrosshairPicker (entity me)
Definition at line 26 of file crosshairpicker.qc.
References crosshairpicker_crosshairToCell(), cvar_string(), and SUPER.
 {
     me.configureXonoticPicker(me);
     SUPER(XonoticCrosshairPicker).cellSelect(me, crosshairpicker_crosshairToCell(me, cvar_string("crosshair")));
 }