Xonotic: lib/defer.qh File Reference
defer.qh File Reference
#include "oo.qh"
#include "self.qh"
Functions
entityclass (Defer)
class (Defer).entity owner
void SUB_Remove (entity this)
Remove self.
void SUB_Remove_self ()
Remove self.
void defer_think ()
void defer (entity this, float fdelay, void() func)
Function Documentation
class (Defer)
void defer (entity this, float fdelay, void() func)
Definition at line 38 of file defer.qh.
References defer_think(), entity(), make_pure, and time.
Referenced by trigger_push_findtarget().
     {
         entity e    = new(deferred);
         make_pure(e);
         e.owner     = this;
         e.use       = func;
         e.think     = defer_think;
         e.nextthink = time + fdelay;
     }
void defer_think ()
Definition at line 26 of file defer.qh.
References entity(), nextthink, owner, SELFPARAM, SUB_Remove_self(), time, and WITH.
Referenced by defer().
     {
         SELFPARAM();
         this.think     = SUB_Remove_self;
         this.nextthink = time;
         WITH(entity, self, this.owner, this.use());
     }
entityclass (Defer)
void SUB_Remove (entity this)
Remove self.
Definition at line 14 of file defer.qh.
Referenced by CopyBody(), and monster_dropitem().
     {
         remove(this);
     }
void SUB_Remove_self ()
Remove self.
Definition at line 20 of file defer.qh.
References SELFPARAM.
Referenced by Damage(), defer_think(), dumpnode(), Monster_Damage(), Monster_Dead_Damage(), Monster_Delay_Action(), pathlib_deletepath(), pathlib_mknode(), pathlib_showedge(), pathlib_showsquare(), target_give_init(), trigger_push_touch(), vehicles_clearreturn(), vehicles_projectile(), and WarpZone_Teleport().
     {
         SELFPARAM();
         remove(this);
     }