Xonotic: lib/matrix/matrix.qh File Reference
matrix.qh File Reference
Functions
void MX_Forget (string room)
void MX_Join (string room)
void MX_Leave (string room)
void MX_Messages (string from)
void MX_Nick (string name)
void MX_Say (string body)
void MX_Sync (string since)
void MX_Typing (bool state)
var void (int buf, string ancestor) MX_Handle
Variables
string autocvar_matrix_server = "http://matrix.org"
string matrix_access_token
string matrix_room
string matrix_user
Function Documentation
void MX_Forget (string room)
Definition at line 135 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/forget?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_Join (string room)
Definition at line 115 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/join?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_Leave (string room)
Definition at line 125 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/leave?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_Messages (string from)
Definition at line 34 of file matrix.qc.
References autocvar_matrix_server, FILE_READ, matrix_access_token, matrix_room, MX_Messages_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND(), and MX_Messages_().
 {
     if (!matrix_access_token) return;
     string s = sprintf("%s/_matrix/client/r0/events?room_id=%s&limit=50&timeout=30000&from=%s&access_token=%s", autocvar_matrix_server, matrix_room, from, matrix_access_token);
     url_single_fopen(
         s,
         FILE_READ,
         MX_Messages_,
         NULL
     );
 }
void MX_Nick (string name)
Definition at line 6 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_user, MX_Nick_(), name, new_pure, pass, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     entity pass = new_pure(mx);
     pass.message = name;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/profile/%s/displayname?access_token=%s", autocvar_matrix_server, matrix_user, matrix_access_token),
         FILE_WRITE,
         MX_Nick_,
         pass
     );
 }
void MX_Say (string body)
Definition at line 187 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_room, MX_Say_(), new_pure, pass, strzone(), and url_single_fopen().
Referenced by GENERIC_COMMAND(), and Say().
 {
     if (!matrix_access_token) return;
     static int txnid;
     entity pass = new_pure(mx);
     pass.message = strzone(body);
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/send/m.room.message/%d?access_token=%s", autocvar_matrix_server, matrix_room, ++txnid, matrix_access_token),
         FILE_WRITE,
         MX_Say_,
         pass
     );
 }
void MX_Sync (string since)
Definition at line 70 of file matrix.qc.
References autocvar_matrix_server, FILE_READ, matrix_access_token, matrix_room, MX_Sync_(), NULL, strcat(), and url_single_fopen().
Referenced by GENERIC_COMMAND(), and MX_Sync_().
 {
     if (!matrix_access_token) return;
     string s = strcat(autocvar_matrix_server, "/_matrix/client/r0/sync?");
     if (since) {
         s = strcat(s,
             "since=", since, "&",
             "timeout=30000&",
             sprintf("filter={\"account_data\":{\"types\":[]},\"presence\":{\"types\":[]},\"room\":{\"rooms\":[\"%s\"]}}&", matrix_room)
         );
     } else {
         s = strcat(s,
             "timeout=0&",
             "filter={\"account_data\":{\"types\":[]},\"presence\":{\"types\":[]},\"room\":{\"rooms\":[]}}&"
         );
     }
     s = strcat(s, "access_token=", matrix_access_token);
     url_single_fopen(s, FILE_READ, MX_Sync_, NULL);
 }
void MX_Typing (bool state)
Definition at line 159 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_room, matrix_user, MX_Typing_(), new_pure, pass, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     entity pass = new_pure(mx);
     pass.message = state ? "true" : "false";
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/typing/%s?access_token=%s", autocvar_matrix_server, matrix_room, matrix_user, matrix_access_token),
         FILE_WRITE,
         MX_Typing_,
         pass
     );
 }
var void (int buf, string ancestor)
Variable Documentation
string autocvar_matrix_server = "http://matrix.org"
Definition at line 3 of file matrix.qh.
Referenced by MX_Forget(), MX_Join(), MX_Leave(), MX_Messages(), MX_Nick(), MX_Say(), MX_Sync(), and MX_Typing().
string matrix_access_token
Definition at line 5 of file matrix.qh.
Referenced by GENERIC_COMMAND(), MX_Forget(), MX_Join(), MX_Leave(), MX_Messages(), MX_Nick(), MX_Say(), MX_Sync(), and MX_Typing().
string matrix_room
Definition at line 6 of file matrix.qh.
Referenced by GENERIC_COMMAND(), MX_Forget(), MX_Join(), MX_Leave(), MX_Messages(), MX_Say(), MX_Sync(), MX_Sync_(), and MX_Typing().
string matrix_user
Definition at line 4 of file matrix.qh.
Referenced by GENERIC_COMMAND(), MX_Handle(), MX_Nick(), and MX_Typing().