Xonotic: server/handicap.qc File Reference
handicap.qc File Reference
Source file that contains implementation of the handicap system.
#include "handicap.qh"
#include <common/state.qh>
#include "client.qh"
Functions
float Handicap_GetForcedHandicap (entity player)
Returns the forced handicap of the player.
float Handicap_GetTotalHandicap (entity player)
Returns the total handicap of the player.
float Handicap_GetVoluntaryHandicap (entity player)
Returns the voluntary handicap of the player.
void Handicap_Initialize (entity player)
Initializes handicap to its default value.
void Handicap_SetForcedHandicap (entity player, float value)
Sets the forced handicap of the player.
Variables
float m_handicap
Holds the handicap value.
Detailed Description
Source file that contains implementation of the handicap system.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file handicap.qc.
Function Documentation
float Handicap_GetForcedHandicap (entity player)
Returns the forced handicap of the player.
Parameters
[in] player Player to check.
Returns
Forced handicap of the player.
Definition at line 23 of file handicap.qc.
References CS().
Referenced by Handicap_GetTotalHandicap().
 {
     return (CS(player)) ? CS(player).m_handicap : 1;
 }
float Handicap_GetTotalHandicap (entity player)
Returns the total handicap of the player.
Parameters
[in] player Player to check.
Returns
Total handicap of the player.
Definition at line 37 of file handicap.qc.
References Handicap_GetForcedHandicap(), and Handicap_GetVoluntaryHandicap().
Referenced by PlayerDamage().
 {
     return Handicap_GetForcedHandicap(player) * Handicap_GetVoluntaryHandicap(
         player);
 }
float Handicap_GetVoluntaryHandicap (entity player)
Returns the voluntary handicap of the player.
Parameters
[in] player Player to check.
Returns
Voluntary handicap of the player.
Definition at line 18 of file handicap.qc.
References bound(), CS(), and cvar_cl_handicap.
Referenced by Handicap_GetTotalHandicap().
 {
     return bound(1.0, CS(player).cvar_cl_handicap, 10.0);
 }
void Handicap_Initialize (entity player)
Initializes handicap to its default value.
Parameters
[in,out] player Player to initialize.
Returns
No return.
Definition at line 13 of file handicap.qc.
References CS().
 {
     CS(player).m_handicap = 1;
 }
void Handicap_SetForcedHandicap (entity player, float value)
Sets the forced handicap of the player.
Parameters
[in] player Player to alter.
[in] value Handicap value to set.
Returns
No return.
Definition at line 28 of file handicap.qc.
References CS(), and error.
Referenced by DynamicHandicap_UpdateHandicap().
 {
     if (value <= 0)
     {
         error("Handicap_SetForcedHandicap: Invalid handicap value.");
     }
     CS(player).m_handicap = value;
 }
Variable Documentation
float m_handicap
Holds the handicap value.
Definition at line 11 of file handicap.qc.