Xonotic: server/scores_rules.qh File Reference
scores_rules.qh File Reference
Functions
int AvailableTeams ()
bool IsTeamAvailable (int team_num)
int NumTeams (int teams)
void ScoreRules_basics (int teams, float sprio, float stprio, float score_enabled)
void ScoreRules_basics_end ()
void ScoreRules_generic ()
Function Documentation
AvailableTeams()
int AvailableTeams ()
Definition at line 22 of file scores_rules.qc.
References NumTeams(), and ScoreRules_teams.
Referenced by bot_fixcount(), bot_setnameandstuff(), ClientConnect(), MapHasRightSize(), and TeamBalance_CheckAllowedTeams().
 {
     return NumTeams(ScoreRules_teams);
 }
IsTeamAvailable()
bool IsTeamAvailable (int team_num)
Definition at line 12 of file scores_rules.qc.
References boolean, ScoreRules_teams, and Team_TeamToBit().
Referenced by GameCommand_moveplayer().
 {
     return boolean(ScoreRules_teams & Team_TeamToBit(team_num));
 }
NumTeams()
int NumTeams (int teams)
Definition at line 17 of file scores_rules.qc.
References BIT, and boolean.
Referenced by AvailableTeams(), CA_CheckTeams(), ctf_DelayedInit(), freezetag_CheckTeams(), GoalTouch(), kh_GetMissingTeams(), kh_Key_AllOwnedByWhichTeam(), kh_LoserTeam(), kh_StartRound(), and kh_WinnerTeam().
 {
     return boolean(teams & BIT(0)) + boolean(teams & BIT(1)) + boolean(teams & BIT(2)) + boolean(teams & BIT(3));
 }
ScoreRules_basics()
void ScoreRules_basics (int teams, float sprio, float stprio, float score_enabled)
Definition at line 29 of file scores_rules.qc.
References FOREACH, INDEPENDENT_PLAYERS, MAX_TEAMSCORE, ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_teams, SFL_LOWER_IS_BETTER, ST_SCORE, and teams.
Referenced by _GameRules_scoring_begin().
 {
     FOREACH(Scores, true, {
         ScoreInfo_SetLabel_PlayerScore(it, "", 0);
     });
     for(int i = 0; i < MAX_TEAMSCORE; ++i)
         ScoreInfo_SetLabel_TeamScore(i, "", 0);
     ScoreRules_teams = teams;
     if(score_enabled)
         ScoreInfo_SetLabel_TeamScore(ST_SCORE, "score", stprio);
     if (!INDEPENDENT_PLAYERS)
         ScoreInfo_SetLabel_PlayerScore(SP_KILLS, "kills", 0);
     ScoreInfo_SetLabel_PlayerScore(SP_DEATHS, "deaths", SFL_LOWER_IS_BETTER);
     if (!INDEPENDENT_PLAYERS)
     {
         ScoreInfo_SetLabel_PlayerScore(SP_SUICIDES, "suicides", SFL_LOWER_IS_BETTER);
         ScoreInfo_SetLabel_PlayerScore(SP_TEAMKILLS, "teamkills", SFL_LOWER_IS_BETTER);
     }
     if(score_enabled)
         ScoreInfo_SetLabel_PlayerScore(SP_SCORE, "score", sprio);
     ScoreInfo_SetLabel_PlayerScore(SP_DMG, "dmg", 0);
     ScoreInfo_SetLabel_PlayerScore(SP_DMGTAKEN, "dmgtaken", SFL_LOWER_IS_BETTER);
     ScoreInfo_SetLabel_PlayerScore(SP_ELO, "elo", 0);
     if(STAT(SHOWFPS))
         ScoreInfo_SetLabel_PlayerScore(SP_FPS, "fps", 0);
 }
ScoreRules_basics_end()
void ScoreRules_basics_end ()
Definition at line 64 of file scores_rules.qc.
References ScoreInfo_Init(), and ScoreRules_teams.
Referenced by _GameRules_scoring_end().
 {
     ScoreInfo_Init(ScoreRules_teams);
 }
ScoreRules_generic()
void ScoreRules_generic ()
Definition at line 69 of file scores_rules.qc.
References entity(), GameRules_scoring, NULL, SFL_SORT_PRIO_PRIMARY, TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetAllowedTeams(), teamplay, and teams.
Referenced by GameplayMode_DelayedInit().
 {
     int teams = 0;
     if (teamplay)
     {
         entity balance = TeamBalance_CheckAllowedTeams(NULL);
         teams = TeamBalance_GetAllowedTeams(balance);
         TeamBalance_Destroy(balance);
     }
     GameRules_scoring(teams, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_PRIMARY, {});
 }