Xonotic: server/pathlib/main.qc File Reference
server/pathlib/main.qc File Reference
#include "pathlib.qh"
#include "utility.qh"
#include "../command/common.qh"
Functions
void pathlib_deletepath (entity start)
void dumpnode (entity n)
void pathlib_showsquare (vector where, float goodsquare, float _lifetime)
void pathlib_showsquare2 (entity node, vector ncolor, float align)
entity pathlib_mknode (vector where, entity parent)
float pathlib_makenode_adaptive (entity parent, vector start, vector to, vector goal, float cost)
entity pathlib_getbestopen ()
void pathlib_close_node (entity node, vector goal)
void pathlib_cleanup ()
float Cosine_Interpolate (float a, float b, float x)
float buildpath_nodefilter_directional (vector n, vector c, vector p)
float buildpath_nodefilter_moveskip (vector n, vector c, vector p)
float buildpath_nodefilter_none (vector n, vector c, vector p)
entity path_build (entity next, vector where, entity prev, entity start)
entity pathlib_astar (vector from, vector to)
Variables
const float PATHLIB_NODEEXPIRE = 20
Function Documentation
float buildpath_nodefilter_directional (vector n, vector c, vector p)
Definition at line 320 of file main.qc.
References normalize(), vector(), and vlen().
Referenced by pathlib_astar().
{
    vector d1,d2;
    d2 = normalize(p - c);
    d1 = normalize(c - n);
    if(vlen(d1-d2) < 0.25)
    {
        //mark_error(c,30);
        return 1;
    }
    //mark_info(c,30);
    return 0;
}
float buildpath_nodefilter_moveskip (vector n, vector c, vector p)
Definition at line 336 of file main.qc.
References pathlib_movenode_goodnode, and pathlib_walknode().
{
    pathlib_walknode(p,n,1);
    if(pathlib_movenode_goodnode)
        return 1;
    return 0;
}
float buildpath_nodefilter_none (vector n, vector c, vector p)
Definition at line 345 of file main.qc.
Referenced by pathlib_waypointpath_step().
{
    return 0;
}
float Cosine_Interpolate (float a, float b, float x)
Definition at line 310 of file main.qc.
References cos().
{
    float ft,f;
    ft = x * 3.1415927;
    f = (1 - cos(ft)) * 0.5;
    return  a*(1-f) + b*f;
}
void dumpnode (entity n)
Definition at line 22 of file main.qc.
References SUB_Remove_self(), and time.
Referenced by pathlib_cleanup().
{
    n.is_path_node = false;
    n.think        = SUB_Remove_self;
    n.nextthink    = time;
}
entity path_build (entity next, vector where, entity prev, entity start)
Definition at line 350 of file main.qc.
References buildpath_nodefilter(), entity(), and spawn().
Referenced by pathlib_astar(), and pathlib_waypointpath_step().
{
    entity path;
    if(prev && next)
        if(buildpath_nodefilter)
            if(buildpath_nodefilter(next.origin,where,prev.origin))
                return next;
    path           = spawn();
    path.owner     = start;
    path.path_next = next;
    setorigin(path,where);
    if(!next)
        path.classname = "path_end";
    else
    {
        if(!prev)
            path.classname = "path_start";
        else
            path.classname = "path_node";
    }
    return path;
}
entity pathlib_astar (vector from, vector to)
Definition at line 379 of file main.qc.
References best_open_node, buildpath_nodefilter(), buildpath_nodefilter_directional(), ceil(), closedlist, entity(), fsnap(), ftos(), gettime(), GETTIME_REALTIME, goal_node, inwater, LOG_TRACE(), movenode_boxmax, movenode_boxmin, movenode_boxup, movenode_maxdrop, movenode_stepsize, movenode_stepup, n, openlist, path_build(), pathlib_bestcash_hits, pathlib_bestcash_saved, pathlib_bestopen_seached, pathlib_cleanup(), pathlib_close_node(), pathlib_closed_cnt, pathlib_cost(), pathlib_expandnode(), pathlib_expandnode_box(), pathlib_expandnode_star(), pathlib_foundgoal, pathlib_g_euclidean_water(), pathlib_getbestopen(), pathlib_gridsize, pathlib_h_diagonal(), pathlib_heuristic(), pathlib_made_cnt, pathlib_makenode(), pathlib_makenode_adaptive(), pathlib_maxtime, pathlib_merge_cnt, pathlib_mknode(), pathlib_movecost, pathlib_movecost_diag, pathlib_movecost_waterfactor, pathlib_movenode(), pathlib_open_cnt, pathlib_searched_cnt, pathlib_showpath2(), pathlib_starttime, pathlib_swimnode(), pathlib_walknode(), SELFPARAM, spawn(), sys_frametime, tile_check(), tile_check_cross(), tile_check_down, tile_check_size, tile_check_up, vlen(), and world.
{SELFPARAM();
    entity path, start, end, open, n, ln;
    float ptime, ftime, ctime;
    ptime = gettime(GETTIME_REALTIME);
    pathlib_starttime = ptime;
    pathlib_cleanup();
    // Select water<->land capable node make/link
    pathlib_makenode     = pathlib_makenode_adaptive;
    // Select XYZ cost estimate
    //pathlib_heuristic    = pathlib_h_diagonal3;
    pathlib_heuristic    = pathlib_h_diagonal;
    // Select distance + waterfactor cost
    pathlib_cost         = pathlib_g_euclidean_water;
    // Select star expander
    pathlib_expandnode   = pathlib_expandnode_star;
    // Select walk simulation movement test
    pathlib_movenode     = pathlib_walknode;
    // Filter final nodes by direction
    buildpath_nodefilter = buildpath_nodefilter_directional;
    // Filter tiles with cross pattern
    tile_check = tile_check_cross;
    // If the start is in water we need diffrent settings
    if(inwater(from))
    {
        // Select volumetric node expaner
        pathlib_expandnode = pathlib_expandnode_box;
        // Water movement test
        pathlib_movenode   = pathlib_swimnode;
    }
    if (!openlist)
        openlist       = spawn();
    if (!closedlist)
        closedlist     = spawn();
    pathlib_closed_cnt       = 0;
    pathlib_open_cnt         = 0;
    pathlib_made_cnt         = 0;
    pathlib_merge_cnt        = 0;
    pathlib_searched_cnt     = 0;
    pathlib_bestopen_seached = 0;
    pathlib_bestcash_hits    = 0;
    pathlib_bestcash_saved   = 0;
    pathlib_gridsize       = 128;
    pathlib_movecost       = pathlib_gridsize;
    pathlib_movecost_diag  = vlen(('1 1 0' * pathlib_gridsize));
    pathlib_movecost_waterfactor = 25000000;
    pathlib_foundgoal      = 0;
    movenode_boxmax   = self.maxs * 1.1;
    movenode_boxmin   = self.mins * 1.1;
    movenode_stepsize = pathlib_gridsize * 0.25;
    tile_check_size = pathlib_gridsize * 0.5;
    tile_check_up   = '0 0 2' * pathlib_gridsize;
    tile_check_up   = '0 0 128';
    tile_check_down = '0 0 3' * pathlib_gridsize;
    tile_check_down = '0 0 256';
    //movenode_stepup   = '0 0 128';
    movenode_stepup   = '0 0 36';
    movenode_maxdrop  = '0 0 512';
    //movenode_maxdrop  = '0 0 512';
    movenode_boxup    = '0 0 72';
    from.x = fsnap(from.x, pathlib_gridsize);
    from.y = fsnap(from.y, pathlib_gridsize);
    //from_z += 32;
    to.x = fsnap(to.x, pathlib_gridsize);
    to.y = fsnap(to.y, pathlib_gridsize);
    //to_z += 32;
    LOG_TRACE("AStar init\n");
    path = pathlib_mknode(from, world);
    pathlib_close_node(path, to);
    if(pathlib_foundgoal)
    {
        LOG_TRACE("AStar: Goal found on first node!\n");
        open           = new(path_end);
        open.owner     = open;
        setorigin(open,path.origin);
        pathlib_cleanup();
        return open;
    }
    if(pathlib_expandnode(path, from, to) <= 0)
    {
        LOG_TRACE("AStar path fail.\n");
        pathlib_cleanup();
        return world;
    }
    best_open_node = pathlib_getbestopen();
    n = best_open_node;
    pathlib_close_node(best_open_node, to);
    if(inwater(n.origin))
        pathlib_expandnode_box(n, from, to);
    else
        pathlib_expandnode_star(n, from, to);
    while(pathlib_open_cnt)
    {
        if((gettime(GETTIME_REALTIME) - pathlib_starttime) > pathlib_maxtime)
        {
            LOG_TRACE("Path took to long to compute!\n");
            LOG_TRACE("Nodes - created: ", ftos(pathlib_made_cnt),"\n");
            LOG_TRACE("Nodes -    open: ", ftos(pathlib_open_cnt),"\n");
            LOG_TRACE("Nodes -  merged: ", ftos(pathlib_merge_cnt),"\n");
            LOG_TRACE("Nodes -  closed: ", ftos(pathlib_closed_cnt),"\n");
            pathlib_cleanup();
            return world;
        }
        best_open_node = pathlib_getbestopen();
        n = best_open_node;
        pathlib_close_node(best_open_node,to);
        if(inwater(n.origin))
            pathlib_expandnode_box(n,from,to);
        else
            pathlib_expandnode(n,from,to);
        if(pathlib_foundgoal)
        {
            LOG_TRACE("Target found. Rebuilding and filtering path...\n");
            ftime = gettime(GETTIME_REALTIME);
            ptime = ftime - ptime;
            start = path_build(world,path.origin,world,world);
            end   = path_build(world,goal_node.origin,world,start);
            ln    = end;
            open = goal_node;
            for(open = goal_node; open.path_prev != path; open = open.path_prev)
            {
                n    = path_build(ln,open.origin,open.path_prev,start);
                ln.path_prev = n;
                ln = n;
            }
            start.path_next = n;
            n.path_prev = start;
            ftime = gettime(GETTIME_REALTIME) - ftime;
            ctime = gettime(GETTIME_REALTIME);
            pathlib_cleanup();
            ctime = gettime(GETTIME_REALTIME) - ctime;
#ifdef DEBUGPATHING
            pathlib_showpath2(start);
            LOG_TRACE("Time used -      pathfinding: ", ftos(ptime),"\n");
            LOG_TRACE("Time used - rebuild & filter: ", ftos(ftime),"\n");
            LOG_TRACE("Time used -          cleanup: ", ftos(ctime),"\n");
            LOG_TRACE("Time used -            total: ", ftos(ptime + ftime + ctime),"\n");
            LOG_TRACE("Time used -         # frames: ", ftos(ceil((ptime + ftime + ctime) / sys_frametime)),"\n\n");
            LOG_TRACE("Nodes -         created: ", ftos(pathlib_made_cnt),"\n");
            LOG_TRACE("Nodes -            open: ", ftos(pathlib_open_cnt),"\n");
            LOG_TRACE("Nodes -          merged: ", ftos(pathlib_merge_cnt),"\n");
            LOG_TRACE("Nodes -          closed: ", ftos(pathlib_closed_cnt),"\n");
            LOG_TRACE("Nodes -        searched: ", ftos(pathlib_searched_cnt),"\n");
            LOG_TRACE("Nodes bestopen searched: ", ftos(pathlib_bestopen_seached),"\n");
            LOG_TRACE("Nodes bestcash -   hits: ", ftos(pathlib_bestcash_hits),"\n");
            LOG_TRACE("Nodes bestcash -   save: ", ftos(pathlib_bestcash_saved),"\n");
            LOG_TRACE("AStar done.\n");
#endif
            return start;
        }
    }
    LOG_TRACE("A* Faild to find a path! Try a smaller gridsize.\n");
    pathlib_cleanup();
    return world;
}
void pathlib_cleanup ()
Definition at line 276 of file main.qc.
References best_open_node, closedlist, dumpnode(), entity(), findfloat(), is_path_node, openlist, and world.
Referenced by pathlib_astar().
{
    best_open_node = world;
    //return;
    entity node;
    node = findfloat(world,is_path_node, true);
    while(node)
    {
        /*
        node.owner = openlist;
        node.pathlib_node_g = 0;
        node.pathlib_node_h = 0;
        node.pathlib_node_f = 0;
        node.path_prev = world;
        */
        dumpnode(node);
        node = findfloat(node,is_path_node, true);
    }
    if(openlist)
        remove(openlist);
    if(closedlist)
        remove(closedlist);
    openlist       = world;
    closedlist     = world;
}
void pathlib_close_node (entity node, vector goal)
Definition at line 246 of file main.qc.
References best_open_node, closedlist, goal_node, LOG_TRACE(), pathlib_closed_cnt, pathlib_foundgoal, pathlib_gridsize, pathlib_movenode_goodnode, pathlib_open_cnt, pathlib_walknode(), vector(), vlen(), and world.
Referenced by pathlib_astar().
{
    if(node.owner == closedlist)
    {
        LOG_TRACE("Pathlib: Tried to close a closed node!\n");
        return;
    }
    if(node == best_open_node)
        best_open_node = world;
    ++pathlib_closed_cnt;
    --pathlib_open_cnt;
    node.owner = closedlist;
    if(vlen(node.origin - goal) <= pathlib_gridsize)
    {
        vector goalmove;
        goalmove = pathlib_walknode(node.origin,goal,1);
        if(pathlib_movenode_goodnode)
        {
            goal_node         = node;
            pathlib_foundgoal = true;
        }
    }
}
void pathlib_deletepath (entity start)
Definition at line 6 of file main.qc.
References entity(), findchainentity(), owner, SUB_Remove_self(), and time.
{
    entity e;
    e = findchainentity(owner, start);
    while(e)
    {
        e.think = SUB_Remove_self;
        e.nextthink = time;
        e = e.chain;
    }
}
entity pathlib_getbestopen ()
Definition at line 216 of file main.qc.
References best_open_node, entity(), findchainentity(), openlist, owner, pathlib_bestcash_hits, pathlib_bestcash_saved, pathlib_bestopen_seached, pathlib_open_cnt, and world.
Referenced by pathlib_astar().
{
    entity node;
    entity bestnode;
    if(best_open_node)
    {
        ++pathlib_bestcash_hits;
        pathlib_bestcash_saved += pathlib_open_cnt;
        return best_open_node;
    }
    node = findchainentity(owner,openlist);
    if(!node)
        return world;
    bestnode = node;
    while(node)
    {
        ++pathlib_bestopen_seached;
        if(node.pathlib_node_f < bestnode.pathlib_node_f)
            bestnode = node;
        node = node.chain;
    }
    return bestnode;
}
float pathlib_makenode_adaptive (entity parent, vector start, vector to, vector goal, float cost)
Definition at line 71 of file main.qc.
References best_open_node, entity(), ftos(), inwater, LOG_TRACE(), openlist, parent, pathlib_cost(), pathlib_expandnode(), pathlib_expandnode_box(), pathlib_expandnode_star(), pathlib_heuristic(), pathlib_merge_cnt, pathlib_mknode(), pathlib_movenode(), pathlib_movenode_goodnode, pathlib_nodeatpoint(), pathlib_searched_cnt, pathlib_showsquare(), pathlib_swimnode(), pathlib_walknode(), tile_check(), vector(), vlen(), and vtos().
Referenced by pathlib_astar().
{
    entity node;
    float h,g,f,doedge = 0;
    vector where;
    ++pathlib_searched_cnt;
    if(inwater(parent.origin))
    {
        LOG_TRACE("FromWater\n");
        pathlib_expandnode = pathlib_expandnode_box;
        pathlib_movenode   = pathlib_swimnode;
    }
    else
    {
        if(inwater(to))
        {
            LOG_TRACE("ToWater\n");
            pathlib_expandnode = pathlib_expandnode_box;
            pathlib_movenode   = pathlib_walknode;
        }
        else
        {
            LOG_TRACE("LandToLoand\n");
            //if(edge_check(parent.origin))
            //    return 0;
            pathlib_expandnode = pathlib_expandnode_star;
            pathlib_movenode   = pathlib_walknode;
            doedge = 1;
        }
    }
    node = pathlib_nodeatpoint(to);
    if(node)
    {
        LOG_TRACE("NodeAtPoint\n");
        ++pathlib_merge_cnt;
        if(node.owner == openlist)
        {
            h = pathlib_heuristic(node.origin,goal);
            g = pathlib_cost(parent,node.origin,cost);
            f = g + h;
            if(node.pathlib_node_g > g)
            {
                node.pathlib_node_h = h;
                node.pathlib_node_g = g;
                node.pathlib_node_f = f;
                node.path_prev = parent;
            }
            if (!best_open_node)
                best_open_node = node;
            else if(best_open_node.pathlib_node_f > node.pathlib_node_f)
                best_open_node = node;
        }
        return 1;
    }
    where = pathlib_movenode(parent.origin, to, 0);
    if (!pathlib_movenode_goodnode)
    {
        //pathlib_showsquare(where, 0 ,30);
        //pathlib_showsquare(parent.origin, 1 ,30);
        LOG_TRACE("pathlib_movenode_goodnode = 0\n");
        return 0;
    }
    //pathlib_showsquare(where, 1 ,30);
    if(pathlib_nodeatpoint(where))
    {
        LOG_TRACE("NAP WHERE :",vtos(where),"\n");
        LOG_TRACE("not NAP TO:",vtos(to),"\n");
        LOG_TRACE("NAP-NNAP:",ftos(vlen(to-where)),"\n\n");
        return 0;
    }
    if(doedge)
        if (!tile_check(where))
        {
            LOG_TRACE("tile_check fail\n");
            pathlib_showsquare(where, 0 ,30);
            return 0;
        }
    h = pathlib_heuristic(where,goal);
    g = pathlib_cost(parent,where,cost);
    f = g + h;
    /*
    node = findradius(where,pathlib_gridsize * 0.5);
    while(node)
    {
        if(node.is_path_node == true)
        {
            ++pathlib_merge_cnt;
            if(node.owner == openlist)
            {
                if(node.pathlib_node_g > g)
                {
                    //pathlib_movenode(where,node.origin,0);
                    //if(pathlib_movenode_goodnode)
                    //{
                        //mark_error(node.origin + '0 0 128',30);
                        node.pathlib_node_h = h;
                        node.pathlib_node_g = g;
                        node.pathlib_node_f = f;
                        node.path_prev = parent;
                    //}
                }
                if (!best_open_node)
                    best_open_node = node;
                else if(best_open_node.pathlib_node_f > node.pathlib_node_f)
                    best_open_node = node;
            }
            return 1;
        }
        node = node.chain;
    }
    */
    node = pathlib_mknode(where, parent);
    node.pathlib_node_h = h;
    node.pathlib_node_g = g;
    node.pathlib_node_f = f;
    if (!best_open_node)
        best_open_node = node;
    else if(best_open_node.pathlib_node_f > node.pathlib_node_f)
        best_open_node = node;
    return 1;
}
entity pathlib_mknode (vector where, entity parent)
Definition at line 37 of file main.qc.
References entity(), openlist, parent, pathlib_made_cnt, pathlib_nodeatpoint(), PATHLIB_NODEEXPIRE, pathlib_open_cnt, pathlib_showsquare(), spawn(), SUB_Remove_self(), and time.
Referenced by pathlib_astar(), and pathlib_makenode_adaptive().
{
    entity node;
    node = pathlib_nodeatpoint(where);
    if(node)
    {
        #ifdef TURRET_DEBUG
        mark_error(where, 60);
        #endif
        return node;
    }
    node = spawn();
    node.think        = SUB_Remove_self;
    node.nextthink    = time + PATHLIB_NODEEXPIRE;
    node.is_path_node = true;
    node.owner        = openlist;
    node.path_prev    = parent;
    setsize(node, '0 0 0', '0 0 0');
    setorigin(node, where);
    node.medium = pointcontents(where);
    pathlib_showsquare(where, 1 ,15);
    ++pathlib_made_cnt;
    ++pathlib_open_cnt;
    return node;
}
void pathlib_showsquare (vector where, float goodsquare, float _lifetime)
Definition at line 73 of file debug.qc.
References entity(), MOVE_WORLDONLY, pathlib_gridsize, s, setmodel, SOLID_NOT, spawn(), SUB_Remove_self(), time, trace_plane_normal, and vectoangles().
Referenced by pathlib_makenode_adaptive(), and pathlib_mknode().
{
    entity s;
    if(!_lifetime)
        _lifetime = time + 30;
    else
        _lifetime += time;
    s           = spawn();
    s.alpha     = 0.25;
    s.think     = SUB_Remove_self;
    s.nextthink = _lifetime;
    s.scale     = pathlib_gridsize / 512.001;
    s.solid     = SOLID_NOT;
    setmodel(s, goodsquare ? MDL_SQUARE_GOOD : MDL_SQUARE_BAD);
    traceline(where + '0 0 32',where - '0 0 128',MOVE_WORLDONLY,s);
    s.angles = vectoangles(trace_plane_normal);
    s.angles_x -= 90;
    setorigin(s,where);
}
void pathlib_showsquare2 (entity node, vector ncolor, float align)
Definition at line 54 of file debug.qc.
References MOVE_WORLDONLY, pathlib_gridsize, setmodel, SOLID_NOT, trace_plane_normal, and vectoangles().
{
    node.alpha     = 0.25;
    node.scale     = pathlib_gridsize / 512.001;
    node.solid     = SOLID_NOT;
    setmodel(node, MDL_SQUARE);
    setorigin(node,node.origin);
    node.colormod = ncolor;
    if(align)
    {
        traceline(node.origin + '0 0 32', node.origin - '0 0 128', MOVE_WORLDONLY, node);
        node.angles = vectoangles(trace_plane_normal);
        node.angles_x -= 90;
    }
}
Variable Documentation
const float PATHLIB_NODEEXPIRE = 20
Definition at line 20 of file main.qc.
Referenced by pathlib_mknode().