Xonotic: common/minigames/cl_minigames.qc File Reference
cl_minigames.qc File Reference
#include "cl_minigames.qh"
Macros
#define FIELD(Flags, Type, Name) MSLE_CLEAN_##Type(this.Name)
#define FIELD(Flags, Type, Name) if (sf & (Flags)) self.Name = Read##Type();
#define MSLE(Name, Fields) void msle_entremove_##Name(entity this) { strunzone(this.netname); Fields }
#define MSLE(Name, Fields)
#define MSLE_CLEAN_Angle(x)
#define MSLE_CLEAN_Byte(x)
#define MSLE_CLEAN_Char(x)
#define MSLE_CLEAN_Coord(x)
#define MSLE_CLEAN_Float(x)
#define MSLE_CLEAN_Long(x)
#define MSLE_CLEAN_Short(x)
#define MSLE_CLEAN_String(x) strunzone(x);
#define MSLE_CLEAN_Vector(x)
#define MSLE_CLEAN_Vector2D(x)
#define ReadString ReadString_Zoned
Functions
void activate_minigame (entity minigame)
void deactivate_minigame ()
void HUD_MinigameMenu_CurrentButton ()
MINIGAME_SIMPLELINKED_ENTITIES void minigame_autoclean_entity (entity e)
void minigame_cmd_workaround (float dummy, string...cmdargc)
void minigame_drawcolorcodedstring_trunc (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags)
vector minigame_drawcolorcodedstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags, float align)
void minigame_drawpic_centered (vector pos, string texture, vector sz, vector color, float thealpha, int drawflags)
void minigame_drawstring_trunc (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags)
vector minigame_drawstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags, float align)
void minigame_entremove (entity this)
string minigame_getWrappedLine (float w, vector theFontSize, textLengthUpToWidth_widthFunction_t tw)
vector minigame_hud_denormalize (vector v, vector pos, vector mySize)
vector minigame_hud_denormalize_size (vector v, vector pos, vector mySize)
bool minigame_hud_mouse_in (vector pos, vector sz)
vector minigame_hud_normalize (vector v, vector pos, vector mySize)
void minigame_hud_simpleboard (vector pos, vector mySize, string board_texture)
void minigame_player_entremove (entity this)
void minigame_prompt ()
void minigame_read_owner ()
string minigame_texture (string name)
string minigame_texture_skin (string skinname, string name)
MUTATOR_HOOKFUNCTION (minigames, HUD_Command)
NET_HANDLE (ENT_CLIENT_MINIGAME, bool isnew)
string ReadString_Zoned ()
REGISTER_MUTATOR (minigames, true)
string () ReadString_Raw = #501
Variables
bool auto_close_minigamemenu
Macro Definition Documentation
#define FIELD (Flags, Type, Name) MSLE_CLEAN_##Type(this.Name)
Definition at line 159 of file cl_minigames.qc.
#define FIELD (Flags, Type, Name) if (sf & (Flags)) self.Name = Read##Type();
Definition at line 159 of file cl_minigames.qc.
#define MSLE (Name, Fields) void msle_entremove_##Name(entity this) { strunzone(this.netname); Fields }
Definition at line 160 of file cl_minigames.qc.
#define MSLE (Name, Fields)
Value:
else if (self.classname == #Name) { \
        if ( sf & MINIG_SF_CREATE ) { \
            minigame_read_owner(); \
            self.entremove = msle_entremove_##Name; \
        } \
        minigame_ent = self.owner; \
        Fields \
    }
Definition at line 160 of file cl_minigames.qc.
#define MSLE_CLEAN_Angle (x)
Definition at line 64 of file cl_minigames.qc.
#define MSLE_CLEAN_Byte (x)
Definition at line 59 of file cl_minigames.qc.
#define MSLE_CLEAN_Char (x)
Definition at line 60 of file cl_minigames.qc.
#define MSLE_CLEAN_Coord (x)
Definition at line 63 of file cl_minigames.qc.
#define MSLE_CLEAN_Float (x)
Definition at line 65 of file cl_minigames.qc.
#define MSLE_CLEAN_Long (x)
Definition at line 62 of file cl_minigames.qc.
#define MSLE_CLEAN_Short (x)
Definition at line 61 of file cl_minigames.qc.
#define MSLE_CLEAN_String (x) strunzone(x);
Definition at line 58 of file cl_minigames.qc.
#define MSLE_CLEAN_Vector (x)
Definition at line 66 of file cl_minigames.qc.
#define MSLE_CLEAN_Vector2D (x)
Definition at line 67 of file cl_minigames.qc.
#define ReadString ReadString_Zoned
Definition at line 158 of file cl_minigames.qc.
Referenced by GameTypeVote_ReadOption(), MapVote_Init(), MapVote_ReadOption(), and NET_HANDLE().
Function Documentation
void activate_minigame (entity minigame)
Definition at line 114 of file cl_minigames.qc.
References active_minigame, auto_close_minigamemenu, deactivate_minigame(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_Open(), LOG_TRACE(), minigame_self, and world.
Referenced by NET_HANDLE().
 {
     if ( !minigame )
     {
         deactivate_minigame();
         return;
     }
     if ( !minigame.descriptor || minigame.classname != "minigame" )
     {
         LOG_TRACE("Trying to activate unregistered minigame ",minigame.netname," in client\n");
         return;
     }
     if ( minigame == active_minigame )
         return;
     if ( active_minigame )
     {
         deactivate_minigame();
     }
     if ( minigame_self.owner != minigame )
         minigame_self = world;
     active_minigame = minigame;
     active_minigame.minigame_event(active_minigame,"activate");
     if ( HUD_MinigameMenu_IsOpened() )
         HUD_MinigameMenu_CurrentButton();
     else
     {
         auto_close_minigamemenu = 1;
         HUD_MinigameMenu_Open();
     }
 }
void deactivate_minigame ()
Definition at line 83 of file cl_minigames.qc.
References active_minigame, auto_close_minigamemenu, entity(), findentity(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), minigame_autoclean_entity(), minigame_self, owner, and world.
Referenced by activate_minigame(), HUD_MinigameMenu_ClickQuit(), minigame_entremove(), minigame_player_entremove(), and Shutdown().
 {
     if ( !active_minigame )
         return;
     active_minigame.minigame_event(active_minigame,"deactivate");
     entity e = world;
     while( (e = findentity(e, owner, active_minigame)) )
         if ( e.minigame_autoclean )
         {
             minigame_autoclean_entity(e);
         }
     minigame_self = world;
     active_minigame = world;
     if ( auto_close_minigamemenu )
     {
         HUD_MinigameMenu_Close();
         auto_close_minigamemenu = 0;
     }
     else
         HUD_MinigameMenu_CurrentButton();
 }
void HUD_MinigameMenu_CurrentButton ()
Definition at line 365 of file cl_minigames_hud.qc.
References active_minigame, entity(), hud_fontsize, HUD_MinigameMenu_Click(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_EraseEntry(), HUD_MinigameMenu_InsertEntry(), HUD_MinigameMenu_last_entry, HUD_MinigameMenu_SpawnEntry(), minigame_texture(), p, strcat(), strzone(), and world.
Referenced by activate_minigame(), deactivate_minigame(), and HUD_MinigameMenu_Open().
 {
     entity e;
     if ( active_minigame )
     {
         for ( e = HUD_MinigameMenu_last_entry; e != world; e = e.list_prev )
             if ( e.classname == "hud_minigamemenu_exit" )
             {
                 HUD_MinigameMenu_EraseEntry(e);
                 break;
             }
         entity currb = HUD_MinigameMenu_SpawnEntry(
             _("Current Game"), '0 0 0', hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_ClickCurrentGame );
         currb.classname = "hud_minigamemenu_current";
         currb.model = strzone(minigame_texture(strcat(active_minigame.descriptor.netname,"/icon")));
         HUD_MinigameMenu_InsertEntry(currb,HUD_MinigameMenu_last_entry);
         HUD_MinigameMenu_Click(currb);
     }
     else
     {
         entity p;
         for ( e = HUD_MinigameMenu_last_entry; e != world; e = p.list_prev )
         {
             p = e;
             if ( e.classname == "hud_minigamemenu_current" )
             {
                 p = e.list_next;
                 if ( !p )
                     p = HUD_MinigameMenu_last_entry;
                 HUD_MinigameMenu_EraseEntry(e);
                 break;
             }
         }
         for ( e = HUD_MinigameMenu_last_entry; e != world; e = e.list_prev )
             if ( e.classname == "hud_minigamemenu_exit" )
                 return;
         entity exit = HUD_MinigameMenu_SpawnEntry(
             _("Exit Menu"),'0 0 0',hud_fontsize*1.5,'0.7 0.84 1', HUD_MinigameMenu_Close);
         exit.classname = "hud_minigamemenu_exit";
         HUD_MinigameMenu_InsertEntry ( exit, HUD_MinigameMenu_last_entry );
     }
 }
MINIGAME_SIMPLELINKED_ENTITIES void minigame_autoclean_entity (entity e)
Definition at line 75 of file cl_minigames.qc.
References etof(), ftos(), and LOG_DEBUG.
Referenced by deactivate_minigame().
 {
     LOG_DEBUG("CL Auto-cleaned: ",ftos(etof(e)), " (",e.classname,")\n");
     remove(e);
 }
void minigame_cmd_workaround (float dummy, string... cmdargc)
Definition at line 365 of file cl_minigames.qc.
References cmd(), localcmd, and strcat().
 {
     string cmd;
     cmd = "cmd minigame ";
     float i;
     for ( i = 0; i < cmdargc; i++ )
         cmd = strcat(cmd,...(i,string));
     localcmd(strcat(cmd,"\n"));
 }
void minigame_drawcolorcodedstring_trunc (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags)
Definition at line 350 of file cl_minigames.qc.
References drawcolorcodedstring(), stringwidth_colors(), and textShortenToWidth().
Referenced by HUD_MinigameMenu_DrawColoredEntry().
 {
     string line = textShortenToWidth(text,maxwidth,fontsize,stringwidth_colors);
     drawcolorcodedstring(pos, line, fontsize, theAlpha, drawflags);
 }
vector minigame_drawcolorcodedstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags, float align)
Definition at line 324 of file cl_minigames.qc.
References drawcolorcodedstring(), getWrappedLine_remaining, minigame_getWrappedLine(), stringwidth_colors(), and vector().
Referenced by HUD_MinigameHelp().
 {
     getWrappedLine_remaining = text;
     vector mypos = pos;
     while ( getWrappedLine_remaining )
     {
         string line = minigame_getWrappedLine(maxwidth,fontsize,stringwidth_colors);
         if ( line == "" )
             break;
         mypos_x = pos_x + (maxwidth - stringwidth_colors(line, fontsize)) * align;
         drawcolorcodedstring(mypos, line, fontsize, theAlpha, drawflags);
         mypos_y += fontsize_y;
     }
     mypos_x = maxwidth;
     mypos_y -= pos_y;
     return mypos;
 }
void minigame_drawpic_centered (vector pos, string texture, vector sz, vector color, float thealpha, int drawflags)
Definition at line 357 of file cl_minigames.qc.
References drawpic().
 {
     drawpic( pos-sz/2, texture, sz, color, thealpha, drawflags );
 }
void minigame_drawstring_trunc (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags)
Definition at line 343 of file cl_minigames.qc.
References drawstring(), stringwidth_nocolors(), and textShortenToWidth().
Referenced by HUD_MinigameMenu_DrawEntry().
 {
     string line = textShortenToWidth(text,maxwidth,fontsize,stringwidth_nocolors);
     drawstring(pos, line, fontsize, color, theAlpha, drawflags);
 }
vector minigame_drawstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags, float align)
Definition at line 305 of file cl_minigames.qc.
References drawstring(), getWrappedLine_remaining, minigame_getWrappedLine(), stringwidth_nocolors(), and vector().
 {
     getWrappedLine_remaining = text;
     vector mypos = pos;
     while ( getWrappedLine_remaining )
     {
         string line = minigame_getWrappedLine(maxwidth,fontsize,stringwidth_nocolors);
         if ( line == "" )
             break;
         mypos_x = pos_x + (maxwidth - stringwidth_nocolors(line, fontsize)) * align;
         drawstring(mypos, line, fontsize, color, theAlpha, drawflags);
         mypos_y += fontsize_y;
     }
     mypos_x = maxwidth;
     mypos_y -= pos_y;
     return mypos;
 }
void minigame_entremove (entity this)
Definition at line 108 of file cl_minigames.qc.
References active_minigame, and deactivate_minigame().
Referenced by NET_HANDLE().
 {
     if ( this == active_minigame )
         deactivate_minigame();
 }
string minigame_getWrappedLine (float w, vector theFontSize, textLengthUpToWidth_widthFunction_t tw)
Definition at line 248 of file cl_minigames.qc.
References find_last_color_code(), getWrappedLine_remaining, strcat(), string_null, strlen(), substring(), and textLengthUpToWidth().
Referenced by minigame_drawcolorcodedstring_wrapped(), and minigame_drawstring_wrapped().
 {
     int last_word;
     string s;
     int take_until;
     int skip = 0;
     s = getWrappedLine_remaining;
     if(w <= 0)
     {
         getWrappedLine_remaining = string_null;
         return s; // the line has no size ANYWAY, nothing would be displayed.
     }
     take_until = textLengthUpToWidth(s, w, theFontSize, tw);
     if ( take_until > strlen(s) )
         take_until = strlen(s);
     for ( int i = 0; i < take_until; i++ )
         if ( substring(s,i,1) == "\n" )
         {
             take_until = i;
             skip = 1;
             break;
         }
     if ( take_until > 0 || skip > 0 )
     {
         if ( skip == 0 && take_until < strlen(s) )
         {
             last_word = take_until;
             while(last_word > 0 && substring(s, last_word, 1) != " ")
                 --last_word;
             if ( last_word != 0 )
             {
                 take_until = last_word;
                 skip = 1;
             }
         }
         getWrappedLine_remaining = substring(s, take_until+skip, strlen(s) - (take_until+skip));
         if(getWrappedLine_remaining == "")
             getWrappedLine_remaining = string_null;
         else if (tw("^7", theFontSize) == 0)
             getWrappedLine_remaining = strcat(find_last_color_code(substring(s, 0, take_until)), getWrappedLine_remaining);
         return substring(s, 0, take_until);
     }
     else
     {
         getWrappedLine_remaining = string_null;
         return s;
     }
 }
vector minigame_hud_denormalize (vector v, vector pos, vector mySize)
Definition at line 16 of file cl_minigames.qc.
 {
     v_x = pos_x + v_x * mySize_x;
     v_y = pos_y + v_y * mySize_y;
     return v;
 }
vector minigame_hud_denormalize_size (vector v, vector pos, vector mySize)
Definition at line 23 of file cl_minigames.qc.
 {
     v_x = v_x * mySize_x;
     v_y = v_y * mySize_y;
     return v;
 }
bool minigame_hud_mouse_in (vector pos, vector sz)
Definition at line 39 of file cl_minigames.qc.
 {
     return mousepos_x >= pos_x && mousepos_x < pos_x + sz_x &&
            mousepos_y >= pos_y && mousepos_y < pos_y + sz_y ;
 }
vector minigame_hud_normalize (vector v, vector pos, vector mySize)
Definition at line 31 of file cl_minigames.qc.
 {
     v_x = ( v_x - pos_x ) / mySize_x;
     v_y = ( v_y - pos_y ) / mySize_y;
     return v;
 }
void minigame_hud_simpleboard (vector pos, vector mySize, string board_texture)
Definition at line 4 of file cl_minigames.qc.
References BORDER_MULTIPLIER, draw_BorderPicture(), DRAWFLAG_NORMAL, drawpic(), panel, panel_bg_alpha, panel_bg_border, and panel_bg_color.
 {
     if(panel.current_panel_bg != "0" && panel.current_panel_bg != "")
         draw_BorderPicture(pos - '1 1 0' * panel_bg_border,
                     panel.current_panel_bg,
                     mySize + '1 1 0' * 2 * panel_bg_border,
                     panel_bg_color, panel_bg_alpha,
                      '1 1 0' * (panel_bg_border/BORDER_MULTIPLIER));
     drawpic(pos, board_texture, mySize, '1 1 1', panel_bg_alpha, DRAWFLAG_NORMAL);
 }
void minigame_player_entremove (entity this)
Definition at line 150 of file cl_minigames.qc.
References active_minigame, deactivate_minigame(), minigame_playerslot, owner, and player_localentnum.
Referenced by NET_HANDLE().
 {
     if ( this.owner == active_minigame && this.minigame_playerslot == player_localentnum )
         deactivate_minigame();
 }
void minigame_prompt ()
Definition at line 377 of file cl_minigames.qc.
References active_minigame, HUD_MinigameMenu_IsOpened(), and HUD_Notify_Push().
 {
     if ( active_minigame && ! HUD_MinigameMenu_IsOpened() )
     {
         HUD_Notify_Push(sprintf("minigames/%s/icon_notif",active_minigame.descriptor.netname),
             _("It's your turn"), "");
     }
 }
void minigame_read_owner ()
Definition at line 169 of file cl_minigames.qc.
References find(), LOG_TRACE(), netname, owner, SELFPARAM, and world.
Referenced by NET_HANDLE().
 {SELFPARAM();
     string owner_name = ReadString_Raw();
     self.owner = world;
     do
         self.owner = find(self.owner,netname,owner_name);
     while ( self.owner && self.owner.classname != "minigame" );
     if ( !self.owner )
         LOG_TRACE("Got a minigame entity without a minigame!\n");
 }
string minigame_texture (string name)
Definition at line 49 of file cl_minigames.qc.
References autocvar_menu_skin, minigame_texture_skin(), and precache_pic().
Referenced by HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), and HUD_MinigameMenu_CurrentButton().
 {
     string path = minigame_texture_skin(autocvar_menu_skin,name);
     if ( precache_pic(path) == "" )
         path = minigame_texture_skin("default", name);
     return path;
 }
string minigame_texture_skin (string skinname, string name)
Definition at line 45 of file cl_minigames.qc.
Referenced by minigame_texture().
 {
     return sprintf("gfx/hud/%s/minigames/%s", skinname, name);
 }
MUTATOR_HOOKFUNCTION (minigames , HUD_Command)
Definition at line 389 of file cl_minigames.qc.
References argv(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_Open(), and MUTATOR_RETURNVALUE.
 {
     if(MUTATOR_RETURNVALUE) { return false; } // command was already handled
     if(argv(1) == "minigame")
     {
         if (HUD_MinigameMenu_IsOpened())
             HUD_MinigameMenu_Close();
         else
             HUD_MinigameMenu_Open();
         return true;
     }
     return false;
 }
NET_HANDLE (ENT_CLIENT_MINIGAME , bool isnew)
Definition at line 179 of file cl_minigames.qc.
References activate_minigame(), active_minigame, classname, descriptor, entity(), enttype, etof(), ftos(), LOG_DEBUG, LOG_TRACE(), MINIG_SF_CREATE, MINIG_SF_UPDATE, minigame_entremove(), minigame_get_descriptor(), minigame_player_entremove(), minigame_read_owner(), minigame_self, MINIGAME_SIMPLELINKED_ENTITIES, msle_classname(), netname, owner, player_localnum, ReadString_Zoned(), and world.
 {
     float sf = ReadByte();
     if ( sf & MINIG_SF_CREATE )
     {
         self.classname = msle_classname(ReadShort());
         self.netname = ReadString_Zoned();
     }
     entity minigame_ent = world;
     if ( self.classname == "minigame" )
     {
         minigame_ent = self;
         if ( sf & MINIG_SF_CREATE )
         {
             self.entremove = minigame_entremove;
             self.descriptor = minigame_get_descriptor(ReadString_Raw());
             if ( !self.descriptor )
                 LOG_TRACE("Got a minigame without a client-side descriptor!\n");
             else
                 self.minigame_event = self.descriptor.minigame_event;
         }
         if ( sf & MINIG_SF_UPDATE )
             self.minigame_flags = ReadLong();
     }
     else if ( self.classname == "minigame_player" )
     {
         float activate = 0;
         if ( sf & MINIG_SF_CREATE )
         {
             self.entremove = minigame_player_entremove;
             minigame_read_owner();
             float ent = ReadLong();
             self.minigame_playerslot = ent;
             LOG_DEBUG("Player: ",entcs_GetName(ent-1),"\n");
             activate = (ent == player_localnum+1 && self.owner && self.owner != active_minigame);
         }
         minigame_ent = self.owner;
         if ( sf & MINIG_SF_UPDATE )
             self.team = ReadByte();
         if ( activate )
         {
             minigame_self = self;
             activate_minigame(self.owner);
         }
     }
     MINIGAME_SIMPLELINKED_ENTITIES
     if ( minigame_ent )
         minigame_ent.minigame_event(minigame_ent,"network_receive",self,sf);
     if ( sf & MINIG_SF_CREATE )
     {
         LOG_DEBUG("CL Reading entity: ",ftos(etof(self)),
             " classname:",self.classname," enttype:",ftos(self.enttype) );
         LOG_DEBUG(" sf:",ftos(sf)," netname:",self.netname,"\n\n");
     }
     return true;
 }
string ReadString_Zoned ()
Definition at line 157 of file cl_minigames.qc.
References strzone().
Referenced by NET_HANDLE().
 { return strzone(ReadString_Raw()); }
REGISTER_MUTATOR (minigames , true)
string () = #501
Variable Documentation
bool auto_close_minigamemenu
Definition at line 82 of file cl_minigames.qc.
Referenced by activate_minigame(), and deactivate_minigame().