Xonotic: lib/csqcmodel/cl_model.qc File Reference
cl_model.qc File Reference
#include "cl_model.qh"
#include "cl_player.qh"
#include "common.qh"
#include "interpolate.qh"
#include <common/csqcmodel_settings.qh>
Macros
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_IF(cond) if(cond) {
#define CSQCMODEL_PROPERTY(flag, t, r, w, f)
#define CSQCMODEL_PROPERTY_SCALED(flag, t, r, w, f, s, mi, ma)
Functions
void CSQCModel_Draw (entity this)
void CSQCModel_InterpolateAnimation_1To2_Do (entity this)
void CSQCModel_InterpolateAnimation_1To2_Note (entity this, int sf, bool set_times)
void CSQCModel_InterpolateAnimation_1To2_PreNote (entity this, int sf)
void CSQCModel_InterpolateAnimation_2To4_Do (entity this)
void CSQCModel_InterpolateAnimation_2To4_Note (entity this, int sf, bool set_times)
void CSQCModel_InterpolateAnimation_2To4_PreNote (entity this, int sf)
void CSQCModel_InterpolateAnimation_Do (entity this)
void CSQCModel_InterpolateAnimation_Note (entity this, int sf)
void CSQCModel_InterpolateAnimation_PreNote (entity this, int sf)
void CSQCModel_remove (entity this)
entity CSQCModel_server2csqc (int i)
NET_HANDLE (ENT_CLIENT_MODEL, bool isnew)
Variables
float autocvar_cl_lerpanim_maxdelta_framegroups = 0.1
float autocvar_cl_nolerp = 0
float csqcmodel_lerpfrac
float csqcmodel_lerpfrac2
float csqcmodel_lerpfrac2time
float csqcmodel_lerpfractime
entity CSQCModel_players [255]
Macro Definition Documentation
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_IF (cond) if(cond) {
#define CSQCMODEL_PROPERTY (flag, t, r, w, f)
Value:
if(sf & flag) \
        this.f = r();
#define CSQCMODEL_PROPERTY_SCALED (flag, t, r, w, f, s, mi, ma)
Value:
if(sf & flag) \
        this.f = (r() + mi) / s;
Function Documentation
void CSQCModel_Draw (entity this)
Definition at line 179 of file cl_model.qc.
References CSQCModel_Hook_PreDraw(), CSQCModel_InterpolateAnimation_Do(), csqcmodel_teleported, CSQCPlayer_IsLocalPlayer(), entity(), entnum, InterpolateOrigin_Do(), ISPLAYER_CLIENT, isplayermodel, player_localentnum, player_localnum, renderflags, RF_EXTERNALMODEL, and RF_VIEWMODEL.
Referenced by NET_HANDLE().
 {
     // some nice flags for CSQCMODEL_IF and the hooks
     bool isplayer = (this.isplayermodel & ISPLAYER_CLIENT);
     noref bool islocalplayer = (this.entnum == player_localnum + 1);
     noref bool isnolocalplayer = (isplayer && (this.entnum != player_localnum + 1));
     // we don't do this for the local player as that one is already handled
     // by CSQCPlayer_SetCamera()
     if (!CSQCPlayer_IsLocalPlayer(this)) InterpolateOrigin_Do(this);
     CSQCModel_InterpolateAnimation_Do(this);
     CSQCModel_Hook_PreDraw(this, isplayer);
     if(isplayer)
     {
         if(this.entnum == player_localentnum)
             this.renderflags |= RF_EXTERNALMODEL;
         else
             this.renderflags &= ~RF_EXTERNALMODEL;
     }
     // inherit draw flags easily
     entity root = this;
     while(root.tag_entity)
         root = root.tag_entity;
     if(this != root)
     {
         this.renderflags &= ~(RF_EXTERNALMODEL | RF_VIEWMODEL);
         this.renderflags |= (root.renderflags & (RF_EXTERNALMODEL | RF_VIEWMODEL));
     }
     // we're drawn, now teleporting is over
     this.csqcmodel_teleported = 0;
 }
void CSQCModel_InterpolateAnimation_1To2_Do (entity this)
Definition at line 156 of file cl_model.qc.
References autocvar_cl_lerpanim_maxdelta_framegroups, autocvar_cl_nolerp, bound(), frame1time, frame2time, lerpfrac, and time.
Referenced by CSQCModel_InterpolateAnimation_Do().
 {
     if(autocvar_cl_nolerp || (autocvar_cl_lerpanim_maxdelta_framegroups == 0))
     {
         this.lerpfrac = 0;
     }
     else
     {
         if(this.frame2time == 0) // if frame2 was not previously displayed, only frame1 can make sense
             this.lerpfrac = 0;
         else
             this.lerpfrac = 1 - bound(0, (time - this.frame1time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
     }
 }
void CSQCModel_InterpolateAnimation_1To2_Note (entity this, int sf, bool set_times)
Definition at line 92 of file cl_model.qc.
References CSQCMODEL_PROPERTY_FRAME, frame1time, and time.
Referenced by CSQCModel_InterpolateAnimation_Note().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         if(set_times)
             this.frame1time = time;
     }
 }
void CSQCModel_InterpolateAnimation_1To2_PreNote (entity this, int sf)
Definition at line 56 of file cl_model.qc.
References CSQCMODEL_PROPERTY_FRAME, frame, frame1time, frame2, and frame2time.
Referenced by CSQCModel_InterpolateAnimation_PreNote().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         this.frame2 = this.frame;
         this.frame2time = this.frame1time;
     }
 }
void CSQCModel_InterpolateAnimation_2To4_Do (entity this)
Definition at line 109 of file cl_model.qc.
References autocvar_cl_lerpanim_maxdelta_framegroups, autocvar_cl_nolerp, bound(), csqcmodel_lerpfrac, csqcmodel_lerpfrac2, csqcmodel_lerpfrac2time, csqcmodel_lerpfractime, frame1time, frame2time, frame3time, frame4time, lerpfrac, lerpfrac3, lerpfrac4, and time.
Referenced by CSQCModel_Hook_PreDraw(), and CSQCModel_InterpolateAnimation_Do().
 {
     if(autocvar_cl_nolerp || (autocvar_cl_lerpanim_maxdelta_framegroups == 0))
     {
         this.lerpfrac = this.csqcmodel_lerpfrac;
         this.lerpfrac3 = 0;
         this.lerpfrac4 = 0;
     }
     else
     {
         float l13, l24, llf;
         float l24_13;
         if(this.frame3time == 0) // if frame1/3 were not previously displayed, only frame1 can make sense
             l13 = 1;
         else
             l13 = bound(0, (time - this.frame1time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         if(this.frame4time == 0) // if frame2/4 were not previously displayed, only frame2 can make sense
             l24 = 1;
         else
             l24 = bound(0, (time - this.frame2time) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         if(this.csqcmodel_lerpfrac2time == 0) // if there is no old lerpfrac (newly displayed model), only lerpfrac makes sense
             llf = 1;
         else
             llf = bound(0, (time - this.csqcmodel_lerpfractime) / autocvar_cl_lerpanim_maxdelta_framegroups, 1);
         l24_13 = this.csqcmodel_lerpfrac * llf + this.csqcmodel_lerpfrac2 * (1 - llf);
         this.lerpfrac  = l24 * l24_13;
         this.lerpfrac4 = (1 - l24) * l24_13;
         this.lerpfrac3 = (1 - l13) * (1 - l24_13);
         if(l24_13 == 0) // if frames 2/4 are not displayed, clear their frametime
         {
             this.frame2time = 0;
             this.frame4time = 0;
         }
         if(l24_13 == 1) // if frames 1/3 are not displayed, clear their frametime
         {
             this.frame1time = 0;
             this.frame3time = 0;
         }
     }
 }
void CSQCModel_InterpolateAnimation_2To4_Note (entity this, int sf, bool set_times)
Definition at line 73 of file cl_model.qc.
References csqcmodel_lerpfrac, csqcmodel_lerpfractime, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_LERPFRAC, frame1time, frame2time, lerpfrac, and time.
Referenced by CSQCModel_Hook_PreDraw(), and CSQCModel_InterpolateAnimation_Note().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         if(set_times)
             this.frame1time = time;
     }
     if(sf & CSQCMODEL_PROPERTY_FRAME2)
     {
         if(set_times)
             this.frame2time = time;
     }
     if(sf & CSQCMODEL_PROPERTY_LERPFRAC)
     {
         this.csqcmodel_lerpfrac = this.lerpfrac;
         if(set_times)
             this.csqcmodel_lerpfractime = time;
     }
 }
void CSQCModel_InterpolateAnimation_2To4_PreNote (entity this, int sf)
Definition at line 37 of file cl_model.qc.
References csqcmodel_lerpfrac, csqcmodel_lerpfrac2, csqcmodel_lerpfrac2time, csqcmodel_lerpfractime, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_LERPFRAC, frame, frame1time, frame2, frame2time, frame3, frame3time, frame4, frame4time, and lerpfrac.
Referenced by CSQCModel_Hook_PreDraw(), and CSQCModel_InterpolateAnimation_PreNote().
 {
     if(sf & CSQCMODEL_PROPERTY_FRAME)
     {
         this.frame3 = this.frame;
         this.frame3time = this.frame1time;
     }
     if(sf & CSQCMODEL_PROPERTY_FRAME2)
     {
         this.frame4 = this.frame2;
         this.frame4time = this.frame2time;
     }
     if(sf & CSQCMODEL_PROPERTY_LERPFRAC)
     {
         this.csqcmodel_lerpfrac2 = this.csqcmodel_lerpfrac;
         this.csqcmodel_lerpfrac2time = this.csqcmodel_lerpfractime;
         this.lerpfrac = this.csqcmodel_lerpfrac;
     }
 }
void CSQCModel_InterpolateAnimation_Do (entity this)
Definition at line 170 of file cl_model.qc.
References CSQCModel_InterpolateAnimation_1To2_Do(), and CSQCModel_InterpolateAnimation_2To4_Do().
Referenced by CSQCModel_Draw(), and NET_HANDLE().
 {
 #ifdef CSQCMODEL_HAVE_TWO_FRAMES
     CSQCModel_InterpolateAnimation_2To4_Do(this);
 #else
     CSQCModel_InterpolateAnimation_1To2_Do(this);
 #endif
 }
void CSQCModel_InterpolateAnimation_Note (entity this, int sf)
Definition at line 100 of file cl_model.qc.
References CSQCModel_InterpolateAnimation_1To2_Note(), and CSQCModel_InterpolateAnimation_2To4_Note().
Referenced by NET_HANDLE().
 {
 #ifdef CSQCMODEL_HAVE_TWO_FRAMES
     CSQCModel_InterpolateAnimation_2To4_Note(this, sf, true);
 #else
     CSQCModel_InterpolateAnimation_1To2_Note(this, sf, true);
 #endif
 }
void CSQCModel_InterpolateAnimation_PreNote (entity this, int sf)
Definition at line 64 of file cl_model.qc.
References CSQCModel_InterpolateAnimation_1To2_PreNote(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
Referenced by NET_HANDLE().
 {
 #ifdef CSQCMODEL_HAVE_TWO_FRAMES
     CSQCModel_InterpolateAnimation_2To4_PreNote(this, sf);
 #else
     CSQCModel_InterpolateAnimation_1To2_PreNote(this, sf);
 #endif
 }
void CSQCModel_remove (entity this)
Definition at line 218 of file cl_model.qc.
References CSQCModel_players, entnum, and NULL.
Referenced by NET_HANDLE().
 {
     CSQCModel_players[this.entnum - 1] = NULL;
 }
entity CSQCModel_server2csqc (int i)
Parameters
i zero indexed player
Definition at line 315 of file cl_model.qc.
References CSQCModel_players, entnum, findfloat(), LOG_DEBUGF, maxclients, and NULL.
Referenced by CSQC_UpdateView(), CSQCPlayer_SetCamera(), Hud_Dynamic_Frame(), viewmodel_animate(), and viewmodel_draw().
 {
     if (i < maxclients) return CSQCModel_players[i];
     ++i;
     LOG_DEBUGF("player out of bounds: %d", i);
     return findfloat(NULL, entnum, i);
 }
NET_HANDLE (ENT_CLIENT_MODEL , bool isnew)
Definition at line 223 of file cl_model.qc.
References ALLPROPERTIES, alpha, BIT, BITSET, classname, CSQCModel_Draw(), CSQCModel_Hook_PostUpdate(), CSQCModel_Hook_PreUpdate(), CSQCModel_InterpolateAnimation_Do(), CSQCModel_InterpolateAnimation_Note(), CSQCModel_InterpolateAnimation_PreNote(), CSQCModel_players, CSQCMODEL_PROPERTY_MODELINDEX, CSQCMODEL_PROPERTY_TELEPORTED, CSQCModel_remove(), csqcmodel_teleported, CSQCPlayer_PostUpdate(), CSQCPlayer_PreUpdate(), drawmask, entnum, IFLAG_ANGLES, IFLAG_AUTOVELOCITY, IFLAG_ORIGIN, IFLAG_TELEPORTED, IFLAG_VELOCITY, iflags, InterpolateOrigin_Do(), InterpolateOrigin_Note(), InterpolateOrigin_Undo(), ISPLAYER_CLIENT, ISPLAYER_LOCAL, ISPLAYER_PLAYER, isplayermodel, m_alpha, MASK_NORMAL, maxclients, maxs, mins, modelindex, origin, player_localentnum, player_localnum, renderflags, RF_EXTERNALMODEL, setorigin(), setpredraw, and vector().
 {
     int sf = ReadInt24_t();
     int psf = ReadByte();
     // some nice flags for CSQCMODEL_IF and the hooks
     bool isplayer = (psf & ISPLAYER_CLIENT) || (this.entnum >= 1 && this.entnum <= maxclients);
     if (isnew && isplayer)
     {
         CSQCModel_players[this.entnum - 1] = this;
         this.entremove = CSQCModel_remove;
     }
     bool islocalplayer = (this.entnum == player_localnum + 1);
     noref bool isnolocalplayer = (isplayer && !islocalplayer);
     this.isplayermodel = BITSET(this.isplayermodel, ISPLAYER_CLIENT, isplayer);
     this.isplayermodel = BITSET(this.isplayermodel, ISPLAYER_LOCAL, islocalplayer);
     this.isplayermodel = BITSET(this.isplayermodel, ISPLAYER_PLAYER, (psf & ISPLAYER_PLAYER));
     this.classname = "csqcmodel";
     this.iflags |= IFLAG_ORIGIN; // interpolate origin too
     this.iflags |= IFLAG_ANGLES; // interpolate angles too
     this.iflags |= IFLAG_VELOCITY | IFLAG_AUTOVELOCITY; // let's calculate velocity automatically
     CSQCModel_Hook_PreUpdate(this, isnew, isplayer, islocalplayer);
     CSQCPlayer_PreUpdate(this);
     InterpolateOrigin_Undo(this);
     CSQCModel_InterpolateAnimation_PreNote(this, sf);
 #define CSQCMODEL_IF(cond) if(cond) {
 #define CSQCMODEL_ENDIF }
 #define CSQCMODEL_PROPERTY(flag,t,r,w,f) \
     if(sf & flag) \
         this.f = r();
 #define CSQCMODEL_PROPERTY_SCALED(flag,t,r,w,f,s,mi,ma) \
     if(sf & flag) \
         this.f = (r() + mi) / s;
     ALLPROPERTIES
 #undef CSQCMODEL_PROPERTY_SCALED
 #undef CSQCMODEL_PROPERTY
 #undef CSQCMODEL_ENDIF
 #undef CSQCMODEL_IF
     if(sf & CSQCMODEL_PROPERTY_MODELINDEX)
     {
         vector pmin = this.mins, pmax = this.maxs;
         setmodelindex(this, this.modelindex); // this retrieves the .model key and sets mins/maxs/absmin/absmax
         setsize(this, pmin, pmax);
     }
     if(sf & CSQCMODEL_PROPERTY_TELEPORTED)
     {
         this.iflags |= IFLAG_TELEPORTED;
         this.csqcmodel_teleported = 1;
     }
     if(sf & BIT(3))
         this.alpha = this.m_alpha;
     if(sf & BIT(14))
         viewloc_SetTags(this);
     CSQCModel_InterpolateAnimation_Note(this, sf);
     InterpolateOrigin_Note(this);
     CSQCPlayer_PostUpdate(this);
     CSQCModel_Hook_PostUpdate(this, isnew, isplayer, islocalplayer);
 #ifdef CSQCMODEL_SUPPORT_GETTAGINFO_BEFORE_DRAW
     InterpolateOrigin_Do(this);
     CSQCModel_InterpolateAnimation_Do(this);
 #endif
     // relink
     setorigin(this, this.origin);
     // set obvious render flags
     if(this.entnum == player_localentnum)
         this.renderflags |= RF_EXTERNALMODEL;
     else
         this.renderflags &= ~RF_EXTERNALMODEL;
     // draw it
     this.drawmask = MASK_NORMAL;
     setpredraw(this, CSQCModel_Draw);
     return true;
 }
Variable Documentation
float autocvar_cl_lerpanim_maxdelta_framegroups = 0.1
Definition at line 29 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_1To2_Do(), and CSQCModel_InterpolateAnimation_2To4_Do().
float autocvar_cl_nolerp = 0
Definition at line 30 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_1To2_Do(), and CSQCModel_InterpolateAnimation_2To4_Do().
float csqcmodel_lerpfrac
Definition at line 32 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_2To4_Do(), CSQCModel_InterpolateAnimation_2To4_Note(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
float csqcmodel_lerpfrac2
Definition at line 33 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_2To4_Do(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
float csqcmodel_lerpfrac2time
Definition at line 35 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_2To4_Do(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
float csqcmodel_lerpfractime
Definition at line 34 of file cl_model.qc.
Referenced by CSQCModel_InterpolateAnimation_2To4_Do(), CSQCModel_InterpolateAnimation_2To4_Note(), and CSQCModel_InterpolateAnimation_2To4_PreNote().
entity CSQCModel_players[255]
Definition at line 216 of file cl_model.qc.
Referenced by CSQCModel_remove(), CSQCModel_server2csqc(), and NET_HANDLE().