Xonotic: common/mutators/mutator/vampire/sv_vampire.qc File Reference
sv_vampire.qc File Reference
#include "sv_vampire.qh"
Functions
MUTATOR_HOOKFUNCTION (vampire, PlayerDamage_SplitHealthArmor)
MUTATOR_HOOKFUNCTION (vampire, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (vampire, BuildMutatorsPrettyString)
REGISTER_MUTATOR (vampire, expr_evaluate(autocvar_g_vampire)&&!MUTATOR_IS_ENABLED(mutator_instagib))
Variables
string autocvar_g_vampire
float autocvar_g_vampire_factor = 1.0
bool autocvar_g_vampire_use_total_damage = false
Function Documentation
MUTATOR_HOOKFUNCTION (vampire , PlayerDamage_SplitHealthArmor)
Definition at line 9 of file sv_vampire.qc.
References autocvar_g_vampire_factor, autocvar_g_vampire_use_total_damage, bound(), entity(), GetResource(), GiveResource(), IS_DEAD, IS_PLAYER, M_ARGV, RES_ARMOR, RES_HEALTH, and time.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float health_take = bound(0, M_ARGV(4, float), GetResource(frag_target, RES_HEALTH));
         float armor_take = bound(0, M_ARGV(5, float), GetResource(frag_target, RES_ARMOR));
         float damage_take = (autocvar_g_vampire_use_total_damage) ? health_take + armor_take : health_take;
         if(time >= frag_target.spawnshieldtime &&
            frag_target != frag_attacker &&
            IS_PLAYER(frag_attacker) &&
            !IS_DEAD(frag_target))
     {
         GiveResource(frag_attacker, RES_HEALTH,
             autocvar_g_vampire_factor * damage_take);
     }
 }
MUTATOR_HOOKFUNCTION (vampire , BuildMutatorsString)
Definition at line 27 of file sv_vampire.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":Vampire");
 }
MUTATOR_HOOKFUNCTION (vampire , BuildMutatorsPrettyString)
Definition at line 32 of file sv_vampire.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Vampire");
 }
REGISTER_MUTATOR (vampire , expr_evaluate(autocvar_g_vampire)&&!MUTATOR_IS_ENABLED(mutator_instagib))
Variable Documentation
string autocvar_g_vampire
Definition at line 3 of file sv_vampire.qc.
float autocvar_g_vampire_factor = 1.0
Definition at line 4 of file sv_vampire.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_vampire_use_total_damage = false
Definition at line 5 of file sv_vampire.qc.
Referenced by MUTATOR_HOOKFUNCTION().