Xonotic: common/mutators/mutator/invincibleproj/sv_invincibleproj.qc File Reference
sv_invincibleproj.qc File Reference
#include "sv_invincibleproj.qh"
Functions
MUTATOR_HOOKFUNCTION (invincibleprojectiles, EditProjectile)
MUTATOR_HOOKFUNCTION (invincibleprojectiles, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (invincibleprojectiles, BuildMutatorsPrettyString)
REGISTER_MUTATOR (invincibleprojectiles, expr_evaluate(autocvar_g_invincible_projectiles))
Variables
string autocvar_g_invincible_projectiles
Function Documentation
MUTATOR_HOOKFUNCTION (invincibleprojectiles , EditProjectile)
Definition at line 6 of file sv_invincibleproj.qc.
References entity(), GetResource(), M_ARGV, RES_HEALTH, and SetResourceExplicit().
 {
     entity proj = M_ARGV(1, entity);
     if(GetResource(proj, RES_HEALTH))
     {
         // disable health which in effect disables damage calculations
         SetResourceExplicit(proj, RES_HEALTH, 0);
     }
 }
MUTATOR_HOOKFUNCTION (invincibleprojectiles , BuildMutatorsString)
Definition at line 17 of file sv_invincibleproj.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":InvincibleProjectiles");
 }
MUTATOR_HOOKFUNCTION (invincibleprojectiles , BuildMutatorsPrettyString)
Definition at line 22 of file sv_invincibleproj.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Invincible Projectiles");
 }
REGISTER_MUTATOR (invincibleprojectiles , expr_evaluate(autocvar_g_invincible_projectiles))
Variable Documentation
string autocvar_g_invincible_projectiles
Definition at line 3 of file sv_invincibleproj.qc.