Xonotic: common/sounds/all.inc File Reference
all.inc File Reference
#include "../teams.qh"
Macros
#define SND_NADE_BONUS SND_KH_ALARM
#define SND_ONS_GENERATOR_ALARM SND_KH_ALARM
Functions
string Item_Sound (string it_snd)
Sound SND_CTF_CAPTURE (int teamid)
Sound SND_CTF_DROPPED (int teamid)
Sound SND_CTF_RETURNED (int teamid)
Sound SND_CTF_TAKEN (int teamid)
Sound SND_GIB_SPLAT_RANDOM ()
Sound SND_GRENADE_BOUNCE_RANDOM ()
Sound SND_HAGEXP_RANDOM ()
Sound SND_NEXWHOOSH_RANDOM ()
Sound SND_RIC_RANDOM ()
SOUND (ARC_FIRE, W_Sound("arc_fire"))
SOUND (ARC_LOOP, W_Sound("arc_loop"))
SOUND (ARC_LOOP_OVERHEAT, W_Sound("arc_loop_overheat"))
SOUND (ARC_STOP, W_Sound("arc_stop"))
SOUND (CAMPINGRIFLE_FIRE2, W_Sound("campingrifle_fire2"))
SOUND (CAMPINGRIFLE_FIRE, W_Sound("campingrifle_fire"))
SOUND (CRYLINK_FIRE2, W_Sound("crylink_fire2"))
SOUND (CRYLINK_FIRE, W_Sound("crylink_fire"))
SOUND (CRYLINK_IMPACT2, W_Sound("crylink_impact2"))
SOUND (CRYLINK_IMPACT, W_Sound("crylink_impact"))
SOUND (CRYLINK_LINKJOIN, W_Sound("crylink_linkjoin"))
SOUND (DRYFIRE, W_Sound("dryfire"))
SOUND (ELECTRO_BOUNCE, W_Sound("electro_bounce"))
SOUND (ELECTRO_FIRE2, W_Sound("electro_fire2"))
SOUND (ELECTRO_FIRE, W_Sound("electro_fire"))
SOUND (ELECTRO_FLY, W_Sound("electro_fly"))
SOUND (ELECTRO_IMPACT, W_Sound("electro_impact"))
SOUND (ELECTRO_IMPACT_COMBO, W_Sound("electro_impact_combo"))
SOUND (FIREBALL_FIRE2, W_Sound("fireball_fire2"))
SOUND (FIREBALL_FIRE, W_Sound("fireball_fire"))
SOUND (FIREBALL_FLY2, W_Sound("fireball_fly2"))
SOUND (FIREBALL_FLY, W_Sound("fireball_fly"))
SOUND (FIREBALL_IMPACT2, W_Sound("fireball_impact2"))
SOUND (FIREBALL_PREFIRE2, W_Sound("fireball_prefire2"))
SOUND (FLAC_FIRE, W_Sound("flac_fire"))
SOUND (GRENADE_BOUNCE1, W_Sound("grenade_bounce1"))
SOUND (GRENADE_BOUNCE2, W_Sound("grenade_bounce2"))
SOUND (GRENADE_BOUNCE3, W_Sound("grenade_bounce3"))
SOUND (GRENADE_BOUNCE4, W_Sound("grenade_bounce4"))
SOUND (GRENADE_BOUNCE5, W_Sound("grenade_bounce5"))
SOUND (GRENADE_BOUNCE6, W_Sound("grenade_bounce6"))
SOUND (GRENADE_FIRE, W_Sound("grenade_fire"))
SOUND (GRENADE_IMPACT, W_Sound("grenade_impact"))
SOUND (GRENADE_STICK, W_Sound("grenade_stick"))
SOUND (HAGAR_BEEP, W_Sound("hagar_beep"))
SOUND (HAGAR_FIRE, W_Sound("hagar_fire"))
SOUND (HAGAR_LOAD, W_Sound("hagar_load"))
SOUND (HAGEXP1, W_Sound("hagexp1"))
SOUND (HAGEXP2, W_Sound("hagexp2"))
SOUND (HAGEXP3, W_Sound("hagexp3"))
SOUND (HOOKBOMB_FIRE, W_Sound("hookbomb_fire"))
SOUND (HOOKBOMB_IMPACT, W_Sound("hookbomb_impact"))
SOUND (HOOK_FIRE, W_Sound("hook_fire"))
SOUND (HOOK_IMPACT, W_Sound("hook_impact"))
SOUND (LASERGUN_FIRE, W_Sound("lasergun_fire"))
SOUND (LASERIMPACT, W_Sound("laserimpact"))
SOUND (LGBEAM_FLY, W_Sound("lgbeam_fly"))
SOUND (MINE_DET, W_Sound("mine_det"))
SOUND (MINE_EXP, W_Sound("mine_exp"))
SOUND (MINE_FIRE, W_Sound("mine_fire"))
SOUND (MINE_STICK, W_Sound("mine_stick"))
SOUND (MINE_TRIGGER, W_Sound("mine_trigger"))
SOUND (MINSTANEXFIRE, W_Sound("minstanexfire"))
SOUND (NEXCHARGE, W_Sound("nexcharge"))
SOUND (NEXFIRE, W_Sound("nexfire"))
SOUND (NEXIMPACT, W_Sound("neximpact"))
SOUND (NEXWHOOSH1, W_Sound("nexwhoosh1"))
SOUND (NEXWHOOSH2, W_Sound("nexwhoosh2"))
SOUND (NEXWHOOSH3, W_Sound("nexwhoosh3"))
SOUND (RELOAD, W_Sound("reload"))
SOUND (RIC1, W_Sound("ric1"))
SOUND (RIC2, W_Sound("ric2"))
SOUND (RIC3, W_Sound("ric3"))
SOUND (ROCKET_DET, W_Sound("rocket_det"))
SOUND (ROCKET_FIRE, W_Sound("rocket_fire"))
SOUND (ROCKET_FLY, W_Sound("rocket_fly"))
SOUND (ROCKET_IMPACT, W_Sound("rocket_impact"))
SOUND (ROCKET_MODE, W_Sound("rocket_mode"))
SOUND (SEEKEREXP1, W_Sound("seekerexp1"))
SOUND (SEEKEREXP2, W_Sound("seekerexp2"))
SOUND (SEEKEREXP3, W_Sound("seekerexp3"))
SOUND (SEEKER_FIRE, W_Sound("seeker_fire"))
SOUND (SHOTGUN_FIRE, W_Sound("shotgun_fire"))
SOUND (SHOTGUN_MELEE, W_Sound("shotgun_melee"))
SOUND (STRENGTH_FIRE, W_Sound("strength_fire"))
SOUND (TAGEXP1, W_Sound("tagexp1"))
SOUND (TAGEXP2, W_Sound("tagexp2"))
SOUND (TAGEXP3, W_Sound("tagexp3"))
SOUND (TAG_FIRE, W_Sound("tag_fire"))
SOUND (TAG_IMPACT, W_Sound("tag_impact"))
SOUND (TAG_ROCKET_FLY, W_Sound("tag_rocket_fly"))
SOUND (UNAVAILABLE, W_Sound("unavailable"))
SOUND (UZI_FIRE, W_Sound("uzi_fire"))
SOUND (WEAPONPICKUP, W_Sound("weaponpickup"))
SOUND (WEAPONPICKUP_NEW_TOYS, W_Sound("weaponpickup_new_toys"))
SOUND (WEAPON_SWITCH, W_Sound("weapon_switch"))
SOUND (CTF_CAPTURE_NEUTRAL, "ctf/capture")
SOUND (CTF_CAPTURE_RED, "ctf/red_capture")
SOUND (CTF_CAPTURE_BLUE, "ctf/blue_capture")
SOUND (CTF_CAPTURE_YELLOW, "ctf/yellow_capture")
SOUND (CTF_CAPTURE_PINK, "ctf/pink_capture")
SOUND (CTF_DROPPED_NEUTRAL, "ctf/neutral_dropped")
SOUND (CTF_DROPPED_RED, "ctf/red_dropped")
SOUND (CTF_DROPPED_BLUE, "ctf/blue_dropped")
SOUND (CTF_DROPPED_YELLOW, "ctf/yellow_dropped")
SOUND (CTF_DROPPED_PINK, "ctf/pink_dropped")
SOUND (CTF_PASS, "ctf/pass")
SOUND (CTF_RESPAWN, "ctf/flag_respawn")
SOUND (CTF_RETURNED_NEUTRAL, "ctf/return")
SOUND (CTF_RETURNED_RED, "ctf/red_returned")
SOUND (CTF_RETURNED_BLUE, "ctf/blue_returned")
SOUND (CTF_RETURNED_YELLOW, "ctf/yellow_returned")
SOUND (CTF_RETURNED_PINK, "ctf/pink_returned")
SOUND (CTF_TAKEN_NEUTRAL, "ctf/neutral_taken")
SOUND (CTF_TAKEN_RED, "ctf/red_taken")
SOUND (CTF_TAKEN_BLUE, "ctf/blue_taken")
SOUND (CTF_TAKEN_YELLOW, "ctf/yellow_taken")
SOUND (CTF_TAKEN_PINK, "ctf/pink_taken")
SOUND (CTF_TOUCH, "ctf/touch")
SOUND (DOM_CLAIM, "domination/claim")
SOUND (KA_DROPPED, "keepaway/dropped")
SOUND (KA_PICKEDUP, "keepaway/pickedup")
SOUND (KA_RESPAWN, "keepaway/respawn")
SOUND (KA_TOUCH, "keepaway/touch")
SOUND (KH_ALARM, "kh/alarm")
SOUND (KH_CAPTURE, "kh/capture")
SOUND (KH_COLLECT, "kh/collect")
SOUND (KH_DESTROY, "kh/destroy")
SOUND (KH_DROP, "kh/drop")
SOUND (NB_BOUNCE, "nexball/bounce")
SOUND (NB_DROP, "nexball/drop")
SOUND (NB_SHOOT1, "nexball/shoot1")
SOUND (NB_SHOOT2, "nexball/shoot2")
SOUND (NB_STEAL, "nexball/steal")
SOUND (ONS_CONTROLPOINT_BUILD, "onslaught/controlpoint_build")
SOUND (ONS_CONTROLPOINT_BUILT, "onslaught/controlpoint_built")
SOUND (ONS_CONTROLPOINT_UNDERATTACK, "onslaught/controlpoint_underattack")
SOUND (ONS_DAMAGEBLOCKEDBYSHIELD, "onslaught/damageblockedbyshield")
SOUND (ONS_ELECTRICITY_EXPLODE, "onslaught/electricity_explode")
SOUND (ONS_GENERATOR_DECAY, "onslaught/generator_decay")
SOUND (ONS_GENERATOR_UNDERATTACK, "onslaught/generator_underattack")
SOUND (ONS_HIT1, "onslaught/ons_hit1")
SOUND (ONS_HIT2, "onslaught/ons_hit2")
SOUND (ONS_SPARK1, "onslaught/ons_spark1")
SOUND (ONS_SPARK2, "onslaught/ons_spark2")
SOUND (ONS_SHOCKWAVE, "onslaught/shockwave")
SOUND (PORTO_BOUNCE, "porto/bounce")
SOUND (PORTO_CREATE, "porto/create")
SOUND (PORTO_EXPIRE, "porto/expire")
SOUND (PORTO_EXPLODE, "porto/explode")
SOUND (PORTO_FIRE, "porto/fire")
SOUND (PORTO_UNSUPPORTED, "porto/unsupported")
SOUND (TUR_PHASER, "turrets/phaser")
SOUND (VEH_ALARM, "vehicles/alarm")
SOUND (VEH_ALARM_SHIELD, "vehicles/alarm_shield")
SOUND (VEH_MISSILE_ALARM, "vehicles/missile_alarm")
SOUND (VEH_BUMBLEBEE_FIRE, W_Sound("flacexp3"))
SOUND (VEH_RACER_BOOST, "vehicles/racer_boost")
SOUND (VEH_RACER_IDLE, "vehicles/racer_idle")
SOUND (VEH_RACER_MOVE, "vehicles/racer_move")
SOUND (VEH_RAPTOR_FLY, "vehicles/raptor_fly")
SOUND (VEH_RAPTOR_SPEED, "vehicles/raptor_speed")
SOUND (VEH_SPIDERBOT_DIE, "vehicles/spiderbot_die")
SOUND (VEH_SPIDERBOT_IDLE, "vehicles/spiderbot_idle")
SOUND (VEH_SPIDERBOT_JUMP, "vehicles/spiderbot_jump")
SOUND (VEH_SPIDERBOT_LAND, "vehicles/spiderbot_land")
SOUND (VEH_SPIDERBOT_STRAFE, "vehicles/spiderbot_strafe")
SOUND (VEH_SPIDERBOT_WALK, "vehicles/spiderbot_walk")
SOUND (NADE_BEEP, "overkill/grenadebip")
SOUND (BUFF_LOST, "relics/relic_effect")
SOUND (POWEROFF, Item_Sound("poweroff"))
SOUND (POWERUP, Item_Sound("powerup"))
SOUND (SHIELD_RESPAWN, Item_Sound("shield_respawn"))
SOUND (STRENGTH_RESPAWN, Item_Sound("strength_respawn"))
SOUND (ARMOR25, Item_Sound("armor25"))
SOUND (ARMORIMPACT, "misc/armorimpact")
SOUND (BODYIMPACT1, "misc/bodyimpact1")
SOUND (BODYIMPACT2, "misc/bodyimpact2")
SOUND (ITEMPICKUP, Item_Sound("itempickup"))
SOUND (ITEMRESPAWNCOUNTDOWN, Item_Sound("itemrespawncountdown"))
SOUND (ITEMRESPAWN, Item_Sound("itemrespawn"))
SOUND (MEGAHEALTH, Item_Sound("megahealth"))
SOUND (LAVA, "player/lava")
SOUND (SLIME, "player/slime")
SOUND (GIB, "misc/gib")
SOUND (GIB_SPLAT01, "misc/gib_splat01")
SOUND (GIB_SPLAT02, "misc/gib_splat02")
SOUND (GIB_SPLAT03, "misc/gib_splat03")
SOUND (GIB_SPLAT04, "misc/gib_splat04")
SOUND (HIT, "misc/hit")
SOUND (TYPEHIT, "misc/typehit")
SOUND (KILL, "misc/kill")
SOUND (SPAWN, "misc/spawn")
SOUND (TALK, "misc/talk")
SOUND (TELEPORT, "misc/teleport")
SOUND (INVSHOT, "misc/invshot")
SOUND (JETPACK_FLY, "misc/jetpack_fly")
string W_Sound (string w_snd)
Macro Definition Documentation
SND_NADE_BONUS
#define SND_NADE_BONUS SND_KH_ALARM
Definition at line 241 of file all.inc.
SND_ONS_GENERATOR_ALARM
#define SND_ONS_GENERATOR_ALARM SND_KH_ALARM
Definition at line 201 of file all.inc.
Function Documentation
Item_Sound()
string Item_Sound (string it_snd)
Definition at line 18 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
 {
     string output = strcat("misc/", it_snd);
 #ifdef SVQC
         MUTATOR_CALLHOOK(ItemSound, it_snd, output);
         return M_ARGV(1, string);
 #else
         return output;
 #endif
 }
SND_CTF_CAPTURE()
Sound SND_CTF_CAPTURE (int teamid)
Definition at line 117 of file all.inc.
References NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and SOUND().
{
     switch (teamid) {
         case NUM_TEAM_1:    return SND_CTF_CAPTURE_RED;
         case NUM_TEAM_2:    return SND_CTF_CAPTURE_BLUE;
         case NUM_TEAM_3:    return SND_CTF_CAPTURE_YELLOW;
         case NUM_TEAM_4:    return SND_CTF_CAPTURE_PINK;
         default:            return SND_CTF_CAPTURE_NEUTRAL;
     }
 }
SND_CTF_DROPPED()
Sound SND_CTF_DROPPED (int teamid)
Definition at line 132 of file all.inc.
References NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and SOUND().
{
     switch (teamid) {
         case NUM_TEAM_1:    return SND_CTF_DROPPED_RED;
         case NUM_TEAM_2:    return SND_CTF_DROPPED_BLUE;
         case NUM_TEAM_3:    return SND_CTF_DROPPED_YELLOW;
         case NUM_TEAM_4:    return SND_CTF_DROPPED_PINK;
         default:            return SND_CTF_DROPPED_NEUTRAL;
     }
 }
SND_CTF_RETURNED()
Sound SND_CTF_RETURNED (int teamid)
Definition at line 150 of file all.inc.
References NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and SOUND().
{
     switch (teamid) {
         case NUM_TEAM_1:    return SND_CTF_RETURNED_RED;
         case NUM_TEAM_2:    return SND_CTF_RETURNED_BLUE;
         case NUM_TEAM_3:    return SND_CTF_RETURNED_YELLOW;
         case NUM_TEAM_4:    return SND_CTF_RETURNED_PINK;
         default:            return SND_CTF_RETURNED_NEUTRAL;
     }
 }
SND_CTF_TAKEN()
Sound SND_CTF_TAKEN (int teamid)
Definition at line 165 of file all.inc.
References NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and SOUND().
{
     switch (teamid) {
         case NUM_TEAM_1:    return SND_CTF_TAKEN_RED;
         case NUM_TEAM_2:    return SND_CTF_TAKEN_BLUE;
         case NUM_TEAM_3:    return SND_CTF_TAKEN_YELLOW;
         case NUM_TEAM_4:    return SND_CTF_TAKEN_PINK;
         default:            return SND_CTF_TAKEN_NEUTRAL;
     }
 }
SND_GIB_SPLAT_RANDOM()
Sound SND_GIB_SPLAT_RANDOM ()
Definition at line 269 of file all.inc.
References floor(), prandom(), REGISTRY_GET, and SOUND().
{
     return REGISTRY_GET(Sounds, SND_GIB_SPLAT01.m_id + floor(prandom() * 4));
 }
SND_GRENADE_BOUNCE_RANDOM()
Sound SND_GRENADE_BOUNCE_RANDOM ()
Definition at line 41 of file all.inc.
References random(), REGISTRY_GET, rint(), SOUND(), and W_Sound().
{
     return REGISTRY_GET(Sounds, SND_GRENADE_BOUNCE1.m_id + rint(random() * 5));
 }
SND_HAGEXP_RANDOM()
Sound SND_HAGEXP_RANDOM ()
Definition at line 53 of file all.inc.
References random(), REGISTRY_GET, rint(), SOUND(), and W_Sound().
{
     return REGISTRY_GET(Sounds, SND_HAGEXP1.m_id + rint(random() * 2));
 }
SND_NEXWHOOSH_RANDOM()
Sound SND_NEXWHOOSH_RANDOM ()
Definition at line 76 of file all.inc.
References random(), REGISTRY_GET, rint(), SOUND(), and W_Sound().
{
     return REGISTRY_GET(Sounds, SND_NEXWHOOSH1.m_id + rint(random() * 2));
 }
SND_RIC_RANDOM()
Sound SND_RIC_RANDOM ()
Definition at line 84 of file all.inc.
References random(), REGISTRY_GET, rint(), SOUND(), and W_Sound().
{
     return REGISTRY_GET(Sounds, SND_RIC1.m_id + rint(random() * 2));
 }
SOUND() [1/187]
SOUND (ARC_FIRE , W_Sound("arc_fire"))
Referenced by SND_CTF_CAPTURE(), SND_CTF_DROPPED(), SND_CTF_RETURNED(), SND_CTF_TAKEN(), SND_GIB_SPLAT_RANDOM(), SND_GRENADE_BOUNCE_RANDOM(), SND_HAGEXP_RANDOM(), SND_NEXWHOOSH_RANDOM(), and SND_RIC_RANDOM().
SOUND() [2/187]
SOUND (ARC_LOOP , W_Sound("arc_loop"))
SOUND() [3/187]
SOUND (ARC_LOOP_OVERHEAT , W_Sound("arc_loop_overheat"))
SOUND() [4/187]
SOUND (ARC_STOP , W_Sound("arc_stop"))
SOUND() [5/187]
SOUND (CAMPINGRIFLE_FIRE2 , W_Sound("campingrifle_fire2"))
SOUND() [6/187]
SOUND (CAMPINGRIFLE_FIRE , W_Sound("campingrifle_fire"))
SOUND() [7/187]
SOUND (CRYLINK_FIRE2 , W_Sound("crylink_fire2"))
SOUND() [8/187]
SOUND (CRYLINK_FIRE , W_Sound("crylink_fire"))
SOUND() [9/187]
SOUND (CRYLINK_IMPACT2 , W_Sound("crylink_impact2"))
SOUND() [10/187]
SOUND (CRYLINK_IMPACT , W_Sound("crylink_impact"))
SOUND() [11/187]
SOUND (CRYLINK_LINKJOIN , W_Sound("crylink_linkjoin"))
SOUND() [12/187]
SOUND (DRYFIRE , W_Sound("dryfire"))
SOUND() [13/187]
SOUND (ELECTRO_BOUNCE , W_Sound("electro_bounce"))
SOUND() [14/187]
SOUND (ELECTRO_FIRE2 , W_Sound("electro_fire2"))
SOUND() [15/187]
SOUND (ELECTRO_FIRE , W_Sound("electro_fire"))
SOUND() [16/187]
SOUND (ELECTRO_FLY , W_Sound("electro_fly"))
SOUND() [17/187]
SOUND (ELECTRO_IMPACT , W_Sound("electro_impact"))
SOUND() [18/187]
SOUND (ELECTRO_IMPACT_COMBO , W_Sound("electro_impact_combo"))
SOUND() [19/187]
SOUND (FIREBALL_FIRE2 , W_Sound("fireball_fire2"))
SOUND() [20/187]
SOUND (FIREBALL_FIRE , W_Sound("fireball_fire"))
SOUND() [21/187]
SOUND (FIREBALL_FLY2 , W_Sound("fireball_fly2"))
SOUND() [22/187]
SOUND (FIREBALL_FLY , W_Sound("fireball_fly"))
SOUND() [23/187]
SOUND (FIREBALL_IMPACT2 , W_Sound("fireball_impact2"))
SOUND() [24/187]
SOUND (FIREBALL_PREFIRE2 , W_Sound("fireball_prefire2"))
SOUND() [25/187]
SOUND (FLAC_FIRE , W_Sound("flac_fire"))
SOUND() [26/187]
SOUND (GRENADE_BOUNCE1 , W_Sound("grenade_bounce1"))
SOUND() [27/187]
SOUND (GRENADE_BOUNCE2 , W_Sound("grenade_bounce2"))
SOUND() [28/187]
SOUND (GRENADE_BOUNCE3 , W_Sound("grenade_bounce3"))
SOUND() [29/187]
SOUND (GRENADE_BOUNCE4 , W_Sound("grenade_bounce4"))
SOUND() [30/187]
SOUND (GRENADE_BOUNCE5 , W_Sound("grenade_bounce5"))
SOUND() [31/187]
SOUND (GRENADE_BOUNCE6 , W_Sound("grenade_bounce6"))
SOUND() [32/187]
SOUND (GRENADE_FIRE , W_Sound("grenade_fire"))
SOUND() [33/187]
SOUND (GRENADE_IMPACT , W_Sound("grenade_impact"))
SOUND() [34/187]
SOUND (GRENADE_STICK , W_Sound("grenade_stick"))
SOUND() [35/187]
SOUND (HAGAR_BEEP , W_Sound("hagar_beep"))
SOUND() [36/187]
SOUND (HAGAR_FIRE , W_Sound("hagar_fire"))
SOUND() [37/187]
SOUND (HAGAR_LOAD , W_Sound("hagar_load"))
SOUND() [38/187]
SOUND (HAGEXP1 , W_Sound("hagexp1"))
SOUND() [39/187]
SOUND (HAGEXP2 , W_Sound("hagexp2"))
SOUND() [40/187]
SOUND (HAGEXP3 , W_Sound("hagexp3"))
SOUND() [41/187]
SOUND (HOOKBOMB_FIRE , W_Sound("hookbomb_fire"))
SOUND() [42/187]
SOUND (HOOKBOMB_IMPACT , W_Sound("hookbomb_impact"))
SOUND() [43/187]
SOUND (HOOK_FIRE , W_Sound("hook_fire"))
SOUND() [44/187]
SOUND (HOOK_IMPACT , W_Sound("hook_impact"))
SOUND() [45/187]
SOUND (LASERGUN_FIRE , W_Sound("lasergun_fire"))
SOUND() [46/187]
SOUND (LASERIMPACT , W_Sound("laserimpact"))
SOUND() [47/187]
SOUND (LGBEAM_FLY , W_Sound("lgbeam_fly"))
SOUND() [48/187]
SOUND (MINE_DET , W_Sound("mine_det"))
SOUND() [49/187]
SOUND (MINE_EXP , W_Sound("mine_exp"))
SOUND() [50/187]
SOUND (MINE_FIRE , W_Sound("mine_fire"))
SOUND() [51/187]
SOUND (MINE_STICK , W_Sound("mine_stick"))
SOUND() [52/187]
SOUND (MINE_TRIGGER , W_Sound("mine_trigger"))
SOUND() [53/187]
SOUND (MINSTANEXFIRE , W_Sound("minstanexfire"))
SOUND() [54/187]
SOUND (NEXCHARGE , W_Sound("nexcharge"))
SOUND() [55/187]
SOUND (NEXFIRE , W_Sound("nexfire"))
SOUND() [56/187]
SOUND (NEXIMPACT , W_Sound("neximpact"))
SOUND() [57/187]
SOUND (NEXWHOOSH1 , W_Sound("nexwhoosh1"))
SOUND() [58/187]
SOUND (NEXWHOOSH2 , W_Sound("nexwhoosh2"))
SOUND() [59/187]
SOUND (NEXWHOOSH3 , W_Sound("nexwhoosh3"))
SOUND() [60/187]
SOUND (RELOAD , W_Sound("reload"))
SOUND() [61/187]
SOUND (RIC1 , W_Sound("ric1"))
SOUND() [62/187]
SOUND (RIC2 , W_Sound("ric2"))
SOUND() [63/187]
SOUND (RIC3 , W_Sound("ric3"))
SOUND() [64/187]
SOUND (ROCKET_DET , W_Sound("rocket_det"))
SOUND() [65/187]
SOUND (ROCKET_FIRE , W_Sound("rocket_fire"))
SOUND() [66/187]
SOUND (ROCKET_FLY , W_Sound("rocket_fly"))
SOUND() [67/187]
SOUND (ROCKET_IMPACT , W_Sound("rocket_impact"))
SOUND() [68/187]
SOUND (ROCKET_MODE , W_Sound("rocket_mode"))
SOUND() [69/187]
SOUND (SEEKEREXP1 , W_Sound("seekerexp1"))
SOUND() [70/187]
SOUND (SEEKEREXP2 , W_Sound("seekerexp2"))
SOUND() [71/187]
SOUND (SEEKEREXP3 , W_Sound("seekerexp3"))
SOUND() [72/187]
SOUND (SEEKER_FIRE , W_Sound("seeker_fire"))
SOUND() [73/187]
SOUND (SHOTGUN_FIRE , W_Sound("shotgun_fire"))
SOUND() [74/187]
SOUND (SHOTGUN_MELEE , W_Sound("shotgun_melee"))
SOUND() [75/187]
SOUND (STRENGTH_FIRE , W_Sound("strength_fire"))
SOUND() [76/187]
SOUND (TAGEXP1 , W_Sound("tagexp1"))
SOUND() [77/187]
SOUND (TAGEXP2 , W_Sound("tagexp2"))
SOUND() [78/187]
SOUND (TAGEXP3 , W_Sound("tagexp3"))
SOUND() [79/187]
SOUND (TAG_FIRE , W_Sound("tag_fire"))
SOUND() [80/187]
SOUND (TAG_IMPACT , W_Sound("tag_impact"))
SOUND() [81/187]
SOUND (TAG_ROCKET_FLY , W_Sound("tag_rocket_fly"))
SOUND() [82/187]
SOUND (UNAVAILABLE , W_Sound("unavailable"))
SOUND() [83/187]
SOUND (UZI_FIRE , W_Sound("uzi_fire"))
SOUND() [84/187]
SOUND (WEAPONPICKUP , W_Sound("weaponpickup"))
SOUND() [85/187]
SOUND (WEAPONPICKUP_NEW_TOYS , W_Sound("weaponpickup_new_toys"))
SOUND() [86/187]
SOUND (WEAPON_SWITCH , W_Sound("weapon_switch"))
SOUND() [87/187]
SOUND (CTF_CAPTURE_NEUTRAL , "ctf/capture")
SOUND() [88/187]
SOUND (CTF_CAPTURE_RED , "ctf/red_capture")
SOUND() [89/187]
SOUND (CTF_CAPTURE_BLUE , "ctf/blue_capture")
SOUND() [90/187]
SOUND (CTF_CAPTURE_YELLOW , "ctf/yellow_capture")
SOUND() [91/187]
SOUND (CTF_CAPTURE_PINK , "ctf/pink_capture")
SOUND() [92/187]
SOUND (CTF_DROPPED_NEUTRAL , "ctf/neutral_dropped")
SOUND() [93/187]
SOUND (CTF_DROPPED_RED , "ctf/red_dropped")
SOUND() [94/187]
SOUND (CTF_DROPPED_BLUE , "ctf/blue_dropped")
SOUND() [95/187]
SOUND (CTF_DROPPED_YELLOW , "ctf/yellow_dropped")
SOUND() [96/187]
SOUND (CTF_DROPPED_PINK , "ctf/pink_dropped")
SOUND() [97/187]
SOUND (CTF_PASS , "ctf/pass")
SOUND() [98/187]
SOUND (CTF_RESPAWN , "ctf/flag_respawn")
SOUND() [99/187]
SOUND (CTF_RETURNED_NEUTRAL , "ctf/return")
SOUND() [100/187]
SOUND (CTF_RETURNED_RED , "ctf/red_returned")
SOUND() [101/187]
SOUND (CTF_RETURNED_BLUE , "ctf/blue_returned")
SOUND() [102/187]
SOUND (CTF_RETURNED_YELLOW , "ctf/yellow_returned")
SOUND() [103/187]
SOUND (CTF_RETURNED_PINK , "ctf/pink_returned")
SOUND() [104/187]
SOUND (CTF_TAKEN_NEUTRAL , "ctf/neutral_taken")
SOUND() [105/187]
SOUND (CTF_TAKEN_RED , "ctf/red_taken")
SOUND() [106/187]
SOUND (CTF_TAKEN_BLUE , "ctf/blue_taken")
SOUND() [107/187]
SOUND (CTF_TAKEN_YELLOW , "ctf/yellow_taken")
SOUND() [108/187]
SOUND (CTF_TAKEN_PINK , "ctf/pink_taken")
SOUND() [109/187]
SOUND (CTF_TOUCH , "ctf/touch")
SOUND() [110/187]
SOUND (DOM_CLAIM , "domination/claim")
SOUND() [111/187]
SOUND (KA_DROPPED , "keepaway/dropped")
SOUND() [112/187]
SOUND (KA_PICKEDUP , "keepaway/pickedup")
SOUND() [113/187]
SOUND (KA_RESPAWN , "keepaway/respawn")
SOUND() [114/187]
SOUND (KA_TOUCH , "keepaway/touch")
SOUND() [115/187]
SOUND (KH_ALARM , "kh/alarm")
SOUND() [116/187]
SOUND (KH_CAPTURE , "kh/capture")
SOUND() [117/187]
SOUND (KH_COLLECT , "kh/collect")
SOUND() [118/187]
SOUND (KH_DESTROY , "kh/destroy")
SOUND() [119/187]
SOUND (KH_DROP , "kh/drop")
SOUND() [120/187]
SOUND (NB_BOUNCE , "nexball/bounce")
SOUND() [121/187]
SOUND (NB_DROP , "nexball/drop")
SOUND() [122/187]
SOUND (NB_SHOOT1 , "nexball/shoot1")
SOUND() [123/187]
SOUND (NB_SHOOT2 , "nexball/shoot2")
SOUND() [124/187]
SOUND (NB_STEAL , "nexball/steal")
SOUND() [125/187]
SOUND (ONS_CONTROLPOINT_BUILD , "onslaught/controlpoint_build")
SOUND() [126/187]
SOUND (ONS_CONTROLPOINT_BUILT , "onslaught/controlpoint_built")
SOUND() [127/187]
SOUND (ONS_CONTROLPOINT_UNDERATTACK , "onslaught/controlpoint_underattack")
SOUND() [128/187]
SOUND (ONS_DAMAGEBLOCKEDBYSHIELD , "onslaught/damageblockedbyshield")
SOUND() [129/187]
SOUND (ONS_ELECTRICITY_EXPLODE , "onslaught/electricity_explode")
SOUND() [130/187]
SOUND (ONS_GENERATOR_DECAY , "onslaught/generator_decay")
SOUND() [131/187]
SOUND (ONS_GENERATOR_UNDERATTACK , "onslaught/generator_underattack")
SOUND() [132/187]
SOUND (ONS_HIT1 , "onslaught/ons_hit1")
SOUND() [133/187]
SOUND (ONS_HIT2 , "onslaught/ons_hit2")
SOUND() [134/187]
SOUND (ONS_SPARK1 , "onslaught/ons_spark1")
SOUND() [135/187]
SOUND (ONS_SPARK2 , "onslaught/ons_spark2")
SOUND() [136/187]
SOUND (ONS_SHOCKWAVE , "onslaught/shockwave")
SOUND() [137/187]
SOUND (PORTO_BOUNCE , "porto/bounce")
SOUND() [138/187]
SOUND (PORTO_CREATE , "porto/create")
SOUND() [139/187]
SOUND (PORTO_EXPIRE , "porto/expire")
SOUND() [140/187]
SOUND (PORTO_EXPLODE , "porto/explode")
SOUND() [141/187]
SOUND (PORTO_FIRE , "porto/fire")
SOUND() [142/187]
SOUND (PORTO_UNSUPPORTED , "porto/unsupported")
SOUND() [143/187]
SOUND (TUR_PHASER , "turrets/phaser")
SOUND() [144/187]
SOUND (VEH_ALARM , "vehicles/alarm")
SOUND() [145/187]
SOUND (VEH_ALARM_SHIELD , "vehicles/alarm_shield")
SOUND() [146/187]
SOUND (VEH_MISSILE_ALARM , "vehicles/missile_alarm")
SOUND() [147/187]
SOUND (VEH_BUMBLEBEE_FIRE , W_Sound("flacexp3"))
SOUND() [148/187]
SOUND (VEH_RACER_BOOST , "vehicles/racer_boost")
SOUND() [149/187]
SOUND (VEH_RACER_IDLE , "vehicles/racer_idle")
SOUND() [150/187]
SOUND (VEH_RACER_MOVE , "vehicles/racer_move")
SOUND() [151/187]
SOUND (VEH_RAPTOR_FLY , "vehicles/raptor_fly")
SOUND() [152/187]
SOUND (VEH_RAPTOR_SPEED , "vehicles/raptor_speed")
SOUND() [153/187]
SOUND (VEH_SPIDERBOT_DIE , "vehicles/spiderbot_die")
SOUND() [154/187]
SOUND (VEH_SPIDERBOT_IDLE , "vehicles/spiderbot_idle")
SOUND() [155/187]
SOUND (VEH_SPIDERBOT_JUMP , "vehicles/spiderbot_jump")
SOUND() [156/187]
SOUND (VEH_SPIDERBOT_LAND , "vehicles/spiderbot_land")
SOUND() [157/187]
SOUND (VEH_SPIDERBOT_STRAFE , "vehicles/spiderbot_strafe")
SOUND() [158/187]
SOUND (VEH_SPIDERBOT_WALK , "vehicles/spiderbot_walk")
SOUND() [159/187]
SOUND (NADE_BEEP , "overkill/grenadebip")
SOUND() [160/187]
SOUND (BUFF_LOST , "relics/relic_effect")
SOUND() [161/187]
SOUND (POWEROFF , Item_Sound("poweroff"))
SOUND() [162/187]
SOUND (POWERUP , Item_Sound("powerup"))
SOUND() [163/187]
SOUND (SHIELD_RESPAWN , Item_Sound("shield_respawn"))
SOUND() [164/187]
SOUND (STRENGTH_RESPAWN , Item_Sound("strength_respawn"))
SOUND() [165/187]
SOUND (ARMOR25 , Item_Sound("armor25"))
SOUND() [166/187]
SOUND (ARMORIMPACT , "misc/armorimpact")
SOUND() [167/187]
SOUND (BODYIMPACT1 , "misc/bodyimpact1")
SOUND() [168/187]
SOUND (BODYIMPACT2 , "misc/bodyimpact2")
SOUND() [169/187]
SOUND (ITEMPICKUP , Item_Sound("itempickup"))
SOUND() [170/187]
SOUND (ITEMRESPAWNCOUNTDOWN , Item_Sound("itemrespawncountdown"))
SOUND() [171/187]
SOUND (ITEMRESPAWN , Item_Sound("itemrespawn"))
SOUND() [172/187]
SOUND (MEGAHEALTH , Item_Sound("megahealth"))
SOUND() [173/187]
SOUND (LAVA , "player/lava")
SOUND() [174/187]
SOUND (SLIME , "player/slime")
SOUND() [175/187]
SOUND (GIB , "misc/gib")
SOUND() [176/187]
SOUND (GIB_SPLAT01 , "misc/gib_splat01")
SOUND() [177/187]
SOUND (GIB_SPLAT02 , "misc/gib_splat02")
SOUND() [178/187]
SOUND (GIB_SPLAT03 , "misc/gib_splat03")
SOUND() [179/187]
SOUND (GIB_SPLAT04 , "misc/gib_splat04")
SOUND() [180/187]
SOUND (HIT , "misc/hit")
SOUND() [181/187]
SOUND (TYPEHIT , "misc/typehit")
SOUND() [182/187]
SOUND (KILL , "misc/kill")
SOUND() [183/187]
SOUND (SPAWN , "misc/spawn")
SOUND() [184/187]
SOUND (TALK , "misc/talk")
SOUND() [185/187]
SOUND (TELEPORT , "misc/teleport")
SOUND() [186/187]
SOUND (INVSHOT , "misc/invshot")
SOUND() [187/187]
SOUND (JETPACK_FLY , "misc/jetpack_fly")
W_Sound()
string W_Sound (string w_snd)
Definition at line 263 of file all.qc.
Referenced by SND_GRENADE_BOUNCE_RANDOM(), SND_HAGEXP_RANDOM(), SND_NEXWHOOSH_RANDOM(), and SND_RIC_RANDOM().
 {
     string output = strcat("weapons/", w_snd);
     MUTATOR_CALLHOOK(WeaponSound, w_snd, output);
     return M_ARGV(1, string);
 }