Xonotic: menu/menu.qh File Reference
menu.qh File Reference
#include "draw.qh"
#include "skin.qh"
#include "xonotic/util.qh"
#include <common/constants.qh>
#include <common/util.qh>
Functions
void draw_reset_cropped ()
void m_display ()
void m_goto (string name)
void m_hide ()
void m_play_click_sound (string soundfile)
void m_play_focus_sound ()
void m_sync ()
void postMenuDraw ()
this is run just after the menu is drawn (or not).
void preMenuDraw ()
this is run before the menu is drawn.
float preMenuInit ()
you have to define this for pre-menu initialization.
void (entity this, float key, float ascii) keyGrabbed
Variables
entity anim
float conheight
float conwidth
float frametime
const int GAME_CONNECTED = BIT(1)
const int GAME_DEVELOPER = BIT(2)
const int GAME_ISSERVER = BIT(0)
int gamestatus
entity keyGrabber
entity main
bool Menu_Active
const string MENU_SOUND_CLEAR = "sound/menu/clear.wav"
const string MENU_SOUND_CLOSE = "sound/menu/close.wav"
const string MENU_SOUND_EXECUTE = "sound/menu/execute.wav"
const string MENU_SOUND_FOCUS = "sound/menu/focus.wav"
const string MENU_SOUND_OPEN = "sound/menu/open.wav"
const string MENU_SOUND_SELECT = "sound/menu/select.wav"
const string MENU_SOUND_SLIDE = "sound/menu/slide.wav"
const string MENU_SOUND_WINNER = "sound/menu/winner.wav"
string name
const int S_ALT = 4
const int S_CTRL = 2
const int S_SHIFT = 1
float time
Function Documentation
void draw_reset_cropped ()
Definition at line 109 of file menu.qc.
References conheight, conwidth, draw_reset(), realconheight, and realconwidth.
Referenced by m_draw(), m_init_delayed(), m_keydown(), m_keyup(), preMenuInit(), and UpdateConWidthHeight().
 {
     draw_reset(conwidth, conheight, 0.5 * (realconwidth - conwidth), 0.5 * (realconheight - conheight));
 }
void m_display ()
Definition at line 855 of file menu.qc.
References KEY_MENU, main, Menu_Active, menuInitialized, menuMouseMode, menuMousePos, mouseButtonsPressed, MT_CLIENT, MT_MENU, setkeydest(), and setmousetarget().
Referenced by m_goto(), m_init(), m_init_delayed(), m_toggle(), and preMenuDraw().
 {
     Menu_Active = true;
     setkeydest(KEY_MENU);
     setmousetarget((menuMouseMode ? MT_CLIENT : MT_MENU));
     if (!menuInitialized) return;
     if (mouseButtonsPressed) main.mouseRelease(main, menuMousePos);
     mouseButtonsPressed = 0;
     main.focusEnter(main);
     main.showNotify(main);
 }
void m_goto (string name)
Definition at line 952 of file menu.qc.
References entity(), find(), GAME_CONNECTED, GAME_ISSERVER, gamestatus, m_activate_window(), m_display(), m_goto_buffer, m_hide(), m_setpointerfocus(), main, menuInitialized, name, NULL, strunzone(), and strzone().
Referenced by GameCommand(), m_init_delayed(), XonoticCommandButton_Click(), XonoticNexposee_close(), and XonoticRootDialog_close().
 {
     if (!menuInitialized)
     {
         if (m_goto_buffer) strunzone(m_goto_buffer);
         m_goto_buffer = strzone(itemname);
         return;
     }
     if (itemname == "")  // this can be called by GameCommand
     {
         if (gamestatus & (GAME_ISSERVER | GAME_CONNECTED))
         {
             m_hide();
         }
         else
         {
             m_activate_window(main.mainNexposee);
             m_display();
         }
     }
     else
     {
         entity e;
         for (e = NULL; (e = find(e, name, itemname)); )
             if (e.classname != "vtbl") break;
         if ((e) && (!e.requiresConnection || (gamestatus & (GAME_ISSERVER | GAME_CONNECTED))))
         {
             m_hide();
             m_activate_window(e);
             m_setpointerfocus(e);
             m_display();
         }
     }
 }
void m_hide ()
Definition at line 870 of file menu.qc.
References KEY_GAME, main, Menu_Active, menuInitialized, MT_CLIENT, setkeydest(), and setmousetarget().
Referenced by m_draw(), m_goto(), m_init(), m_keydown(), m_toggle(), and Shutdown().
 {
     Menu_Active = false;
     setkeydest(KEY_GAME);
     setmousetarget(MT_CLIENT);
     if (!menuInitialized) return;
     main.focusLeave(main);
     main.hideNotify(main);
 }
void m_play_click_sound (string soundfile)
Definition at line 997 of file menu.qc.
References cvar(), and localsound().
Referenced by Button_playClickSound(), CheckBox_playClickSound(), Dialog_keyDown(), GameCommand(), InputBox_keyDown(), InputBox_mouseRelease(), KeyBinder_Bind_Clear(), Nexposee_keyDown(), Nexposee_mousePress(), ServerList_Favorite_Click(), Slider_keyUp(), Slider_mouseRelease(), XonoticColorpicker_mouseRelease(), XonoticColorpickerString_mouseRelease(), XonoticGametypeList_clickListBoxItem(), XonoticGametypeList_keyDown(), XonoticHUDSkinList_doubleClickListBoxItem(), XonoticKeyBinder_keyGrabbed(), XonoticLanguageList_doubleClickListBoxItem(), XonoticLanguageList_keyDown(), XonoticMapList_clickListBoxItem(), XonoticMapList_doubleClickListBoxItem(), XonoticMapList_keyDown(), XonoticServerList_keyDown(), XonoticSkinList_doubleClickListBoxItem(), XonoticSkinList_keyDown(), and XonoticWinnerDialog_focusEnter().
 {
     if (!cvar("menu_sounds")) return;
     localsound(soundfile);
 }
void m_play_focus_sound ()
Definition at line 988 of file menu.qc.
References cvar(), localsound(), MENU_SOUND_FOCUS, and time.
 {
     static float menuLastFocusSoundTime;
     if (cvar("menu_sounds") < 2) return;
     if (time - menuLastFocusSoundTime <= 0.25) return;
     localsound(MENU_SOUND_FOCUS);
     menuLastFocusSoundTime = time;
 }
void m_sync ()
Definition at line 40 of file menu.qc.
References loadAllCvars(), main, updateCompression(), vidheight_s, vidpixelheight_s, and vidwidth_s.
Referenced by GameCommand(), and m_init_delayed().
 {
     updateCompression();
     vidwidth_s = vidheight_s = vidpixelheight_s = 0;  // Force updateConwidths on next draw
     loadAllCvars(main);
 }
void postMenuDraw ()
this is run just after the menu is drawn (or not).
Useful to draw something over everything else.
Definition at line 548 of file util.qc.
References draw_CenterText(), draw_scale, and globalToBoxSize().
Referenced by m_draw().
 {
     if(autocvar_menu_watermark != "")
     {
         draw_CenterText('0.5 0.1 0', sprintf(_("^1%s TEST BUILD"), autocvar_menu_watermark), globalToBoxSize('32 32 0', draw_scale), '1 1 1', 0.05, 1);
     }
 }
void preMenuDraw ()
this is run before the menu is drawn.
You may put some stuff there that has to be done every frame.
Definition at line 557 of file util.qc.
References _Nex_ExtResponseSystem_UpdateToURL, bound(), campaign_name, conheight, conwidth, cos(), cvar(), DialogOpenButton_Click_withCoords(), draw_alpha, draw_CenterText(), draw_Fill(), draw_scale, draw_TextWidth(), eX, eY, m_display(), main, max(), NULL, sin(), strcat(), strunzone(), strzone(), time, updateCheck(), and vector().
Referenced by m_draw().
 {
     vector fs, sz = '0 0 0', line, mid;
     updateCheck();
     if(_Nex_ExtResponseSystem_UpdateTo != "")
     {
         // TODO rather turn this into a dialog
         fs = ((1/draw_scale.x) * eX + (1/draw_scale.y) * eY) * 12;
         line = eY * fs.y;
         string l1, l2;
         l1 = sprintf(_("Update to %s now!"), _Nex_ExtResponseSystem_UpdateTo);
         l2 = "http://www.xonotic.org/";
         if(_Nex_ExtResponseSystem_UpdateToURL)
             l2 = _Nex_ExtResponseSystem_UpdateToURL;
         sz_x = draw_TextWidth("    ", 0, fs) + max(
                 draw_TextWidth(l1, 0, fs),
                 draw_TextWidth(l2, 0, fs)
             );
         sz_y = 3 * fs.y;
         draw_alpha = bound(0, sin(time * 0.112 - 0.3) * 10, 1);
         mid = eX * (0.5 + 0.5 * (1 - sz.x) * cos(time * 0.071))
             + eY * (0.5 + 0.5 * (1 - sz.y) * sin(time * 0.071));
         draw_Fill(mid - 0.5 * sz, sz, '1 1 0', 1);
         draw_CenterText(mid - 1 * line, l1, fs, '1 0 0', 1, 0);
         draw_CenterText(mid - 0 * line, l2, fs, '0 0 1', 1, 0);
     }
     if (!campaign_name_previous)
         campaign_name_previous = strzone(strcat(campaign_name, "x")); // force unequal
     if(campaign_name == campaign_name_previous)
     {
         if(cvar(strcat("g_campaign", campaign_name, "_won")))
         {
             if(!campaign_won_previous)
             {
                 m_display();
                 DialogOpenButton_Click_withCoords(NULL, main.winnerDialog, '0 0 0', eX * conwidth + eY * conheight);
             }
             campaign_won_previous = 1;
         }
         else
             campaign_won_previous = 0;
     }
     else
     {
         strunzone(campaign_name_previous);
         campaign_name_previous = strzone(campaign_name);
         campaign_won_previous = cvar(strcat("g_campaign", campaign_name, "_won"));
     }
 }
float preMenuInit ()
you have to define this for pre-menu initialization.
Return 0 if initialization needs to be retried a frame later, 1 if it succeeded.
Definition at line 509 of file util.qc.
References _MapInfo_FilterGametype(), draw_CenterText(), draw_Fill(), draw_reset_cropped(), draw_scale, eX, eY, MapInfo_Cache_Create(), MapInfo_Enumerate(), MapInfo_progress, MAPINFO_TYPE_ALL, updateCheck(), and vector().
Referenced by m_init_delayed().
 {
     vector sz;
     vector boxA, boxB;
     updateCheck();
     MapInfo_Cache_Create();
     MapInfo_Enumerate();
     if(!_MapInfo_FilterGametype(MAPINFO_TYPE_ALL, 0, 0, 0, 1))
     {
         draw_reset_cropped();
         sz = eX * 0.025 + eY * 0.025 * (draw_scale.x / draw_scale.y);
         draw_CenterText('0.5 0.5 0' - 1.25 * sz.y * eY, _("Autogenerating mapinfo for newly added maps..."), sz, '1 1 1', 1, 0);
         boxA = '0.05 0.5 0' + 0.25 * sz.y * eY;
         boxB = '0.95 0.5 0' + 1.25 * sz.y * eY;
         draw_Fill(boxA, boxB - boxA, '1 1 1', 1);
         boxA += sz * 0.1;
         boxB -= sz * 0.1;
         draw_Fill(boxA, boxB - boxA, '0.1 0.1 0.1', 1);
         boxB_x = boxA_x * (1 - MapInfo_progress) + boxB_x * MapInfo_progress;
         draw_Fill(boxA, boxB - boxA, '0 0 1', 1);
         return false;
     }
     return true;
 }
void (entity this, float key, float ascii)
Variable Documentation
entity anim
Definition at line 25 of file menu.qh.
Referenced by m_draw(), m_init_delayed(), makeHostedEasing(), makeHostedKeyframe(), and Slider_draw().
float conheight
Definition at line 36 of file menu.qh.
Referenced by BorderImage_recalcPositionWithText(), Dialog_configureDialog(), draw_reset_cropped(), m_allocatetooltipbox(), m_init_delayed(), m_setpointerfocus(), m_tooltip(), MainWindow_configureMainWindow(), MainWindow_draw(), preMenuDraw(), and UpdateConWidthHeight().
float conwidth
Definition at line 36 of file menu.qh.
Referenced by BorderImage_recalcPositionWithText(), Dialog_configureDialog(), draw_reset_cropped(), m_allocatetooltipbox(), m_init_delayed(), m_setpointerfocus(), m_tooltip(), MainWindow_draw(), preMenuDraw(), and UpdateConWidthHeight().
float frametime
Definition at line 22 of file menu.qh.
const int GAME_CONNECTED = BIT(1)
Definition at line 12 of file menu.qh.
Referenced by CheckSendCvars(), DemoConfirm_Check_Gamestatus(), DemoConfirm_ListClick_Check_Gamestatus(), HUDSetup_Check_Gamestatus(), HUDSetup_Start(), m_draw(), m_gamestatus(), m_goto(), m_keydown(), and XonoticLanguageList_setLanguage().
const int GAME_DEVELOPER = BIT(2)
Definition at line 13 of file menu.qh.
Referenced by m_gamestatus().
const int GAME_ISSERVER = BIT(0)
Definition at line 11 of file menu.qh.
Referenced by CheckSendCvars(), DemoConfirm_Check_Gamestatus(), DemoConfirm_ListClick_Check_Gamestatus(), HUDSetup_Check_Gamestatus(), HUDSetup_Start(), m_draw(), m_gamestatus(), m_goto(), and m_keydown().
int gamestatus
Definition at line 16 of file menu.qh.
Referenced by CheckSendCvars(), DemoConfirm_Check_Gamestatus(), DemoConfirm_ListClick_Check_Gamestatus(), HUDSetup_Check_Gamestatus(), HUDSetup_Start(), m_draw(), m_gamestatus(), m_goto(), m_keydown(), and XonoticLanguageList_setLanguage().
entity keyGrabber
Definition at line 32 of file menu.qh.
Referenced by KeyBinder_Bind_Change(), m_draw(), m_keydown(), and XonoticKeyBinder_drawListBoxItem().
entity main
Definition at line 26 of file menu.qh.
Referenced by DemoConfirm_Check_Gamestatus(), DemoConfirm_ListClick_Check_Gamestatus(), drawBackground(), HUDSetup_Check_Gamestatus(), m_display(), m_draw(), m_goto(), m_hide(), m_init_delayed(), m_keydown(), m_keyup(), m_sync(), m_tooltip(), preMenuDraw(), ServerList_Info_Click(), UpdateConWidthHeight(), XonoticInputSettingsTab_fill(), XonoticLanguageList_setLanguage(), XonoticMapList_doubleClickListBoxItem(), XonoticMapList_keyDown(), XonoticMiscSettingsTab_fill(), XonoticScreenshotBrowserTab_fill(), XonoticServerCreateTab_fill(), and XonoticServerList_keyDown().
bool Menu_Active
Definition at line 15 of file menu.qh.
Referenced by m_display(), m_draw(), m_hide(), m_init_delayed(), m_keydown(), m_keyup(), m_toggle(), and updateCheck().
const string MENU_SOUND_CLEAR = "sound/menu/clear.wav"
Definition at line 49 of file menu.qh.
Referenced by InputBox_keyDown(), InputBox_mouseRelease(), and KeyBinder_Bind_Clear().
const string MENU_SOUND_CLOSE = "sound/menu/close.wav"
Definition at line 50 of file menu.qh.
Referenced by Button_playClickSound(), Dialog_keyDown(), Nexposee_keyDown(), and Nexposee_mousePress().
const string MENU_SOUND_EXECUTE = "sound/menu/execute.wav"
Definition at line 51 of file menu.qh.
Referenced by Button_playClickSound(), XonoticGametypeList_keyDown(), XonoticHUDSkinList_doubleClickListBoxItem(), XonoticLanguageList_doubleClickListBoxItem(), XonoticLanguageList_keyDown(), XonoticSkinList_doubleClickListBoxItem(), and XonoticSkinList_keyDown().
const string MENU_SOUND_FOCUS = "sound/menu/focus.wav"
Definition at line 52 of file menu.qh.
Referenced by m_play_focus_sound().
const string MENU_SOUND_OPEN = "sound/menu/open.wav"
Definition at line 53 of file menu.qh.
Referenced by Button_playClickSound(), GameCommand(), Nexposee_keyDown(), Nexposee_mousePress(), XonoticMapList_doubleClickListBoxItem(), XonoticMapList_keyDown(), and XonoticServerList_keyDown().
const string MENU_SOUND_SELECT = "sound/menu/select.wav"
Definition at line 54 of file menu.qh.
Referenced by CheckBox_playClickSound(), ServerList_Favorite_Click(), XonoticGametypeList_clickListBoxItem(), XonoticKeyBinder_keyGrabbed(), XonoticMapList_clickListBoxItem(), and XonoticMapList_keyDown().
const string MENU_SOUND_SLIDE = "sound/menu/slide.wav"
Definition at line 55 of file menu.qh.
Referenced by Slider_keyUp(), Slider_mouseRelease(), XonoticColorpicker_mouseRelease(), and XonoticColorpickerString_mouseRelease().
const string MENU_SOUND_WINNER = "sound/menu/winner.wav"
Definition at line 56 of file menu.qh.
Referenced by XonoticWinnerDialog_focusEnter().
string name
Definition at line 30 of file menu.qh.
Referenced by ACCUMULATE_call(), addPowerupItem(), bot_setnameandstuff(), Client::Client(), XonoticRegisteredSettingsList::drawListBoxItem(), GameTypeVote_ReadOption(), m_goto(), MX_Nick(), TeamScore_Spawn(), viewmodel_draw(), and XonoticSkinList_getSkins().
const int S_ALT = 4
Definition at line 20 of file menu.qh.
const int S_CTRL = 2
Definition at line 19 of file menu.qh.
const int S_SHIFT = 1
Definition at line 18 of file menu.qh.
float time
Definition at line 23 of file menu.qh.