Xonotic: server/spawnpoints.qc File Reference
spawnpoints.qc File Reference
#include "spawnpoints.qh"
#include <common/constants.qh>
#include <common/gamemodes/_mod.qh>
#include <common/mapobjects/subs.qh>
#include <common/mapobjects/target/spawnpoint.qh>
#include <common/mapobjects/triggers.qh>
#include <common/net_linked.qh>
#include <common/stats.qh>
#include <common/teams.qh>
#include <common/util.qh>
#include <common/weapons/_all.qh>
#include <lib/warpzone/common.qh>
#include <lib/warpzone/util_server.qh>
#include <server/command/vote.qh>
#include <server/intermission.qh>
#include <server/mutators/_mod.qh>
#include <server/race.qh>
#include <server/utils.qh>
#include <server/world.qh>
Functions
void link_spawnpoint (entity this)
void relocate_spawnpoint (entity this)
entity SelectSpawnPoint (entity this, bool anypoint)
entity Spawn_FilterOutBadSpots (entity this, entity firstspot, float mindist, float teamcheck, bool targetcheck)
vector Spawn_Score (entity this, entity spot, float mindist, float teamcheck, bool targetcheck)
void Spawn_ScoreAll (entity this, entity firstspot, float mindist, float teamcheck, bool targetcheck)
entity Spawn_WeightedPoint (entity firstspot, float lower, float upper, float exponent)
bool SpawnEvent_Send (entity this, entity to, int sf)
spawnfunc (info_player_survivor)
spawnfunc (info_player_start)
spawnfunc (info_player_deathmatch)
spawnfunc (info_player_team1)
spawnfunc (info_player_team2)
spawnfunc (info_player_team3)
spawnfunc (info_player_team4)
void spawnpoint_reset (entity this)
bool SpawnPoint_Send (entity this, entity to, int sf)
void spawnpoint_think (entity this)
void spawnpoint_use (entity this, entity actor, entity trigger)
Variables
vector spawnpoint_prevorigin
bool testspawn_checked
entity testspawn_point
Function Documentation
void link_spawnpoint (entity this)
Definition at line 82 of file spawnpoints.qc.
References autocvar_g_spawn_useallspawns, have_team_spawns, SpawnPoint_Send(), team, Team_IsValidTeam(), and teamplay.
Referenced by relocate_spawnpoint().
 {
     bool anypoint = (autocvar_g_spawn_useallspawns || (teamplay && have_team_spawns <= 0)); // TODO: check if available teams is equal to spawnpoints available
     // Don't show team spawns in non-team matches,
     // and don't show non-team spawns in team matches.
     // (Unless useallspawns is activated)
     if(anypoint || !((teamplay && !Team_IsValidTeam(this.team)) || (!teamplay && Team_IsValidTeam(this.team))))
         Net_LinkEntity(this, false, 0, SpawnPoint_Send);
 }
void relocate_spawnpoint (entity this)
Definition at line 93 of file spawnpoints.qc.
References angles, autocvar_g_spawnpoints_auto_move_out_of_solid, autocvar_r_showbboxes, BIT, cnt, entity(), g_saved_team, have_team_spawns, have_team_spawns_forteams, IL_PUSH(), InitializeEntity(), link_spawnpoint(), LOG_INFO, LOG_INFOF, maxs, mins, move_out_of_solid, nextthink, objerror(), origin, random(), setorigin(), setthink, SOLID_TRIGGER, spawnpoint_nag, spawnpoint_reset(), spawnpoint_think(), spawnpoint_use(), team, team_saved, time, trace_startsolid, use, vector(), and vtos().
Referenced by spawnfunc().
 {
     // nudge off the floor
     setorigin(this, this.origin + '0 0 1');
     tracebox(this.origin, PL_MIN_CONST, PL_MAX_CONST, this.origin, true, this);
     if (trace_startsolid)
     {
         vector o;
         o = this.origin;
         this.mins = PL_MIN_CONST;
         this.maxs = PL_MAX_CONST;
         if (!move_out_of_solid(this))
             objerror(this, "could not get out of solid at all!");
         LOG_INFOF(
             "^1NOTE: this map needs FIXING. Spawnpoint at %s needs to be moved out of solid, e.g. by %s",
             vtos(o - '0 0 1'),
             vtos(this.origin - o)
         );
         if (autocvar_g_spawnpoints_auto_move_out_of_solid)
         {
             if (!spawnpoint_nag)
                 LOG_INFO("\{1}^1NOTE: this map needs FIXING (it contains spawnpoints in solid, see server log)");
             spawnpoint_nag = 1;
         }
         else
         {
             setorigin(this, o);
             this.mins = this.maxs = '0 0 0';
             objerror(this, "player spawn point in solid, mapper sucks!\n");
             return;
         }
     }
     this.use = spawnpoint_use;
     setthink(this, spawnpoint_think);
     this.nextthink = time + 0.5 + random() * 2; // shouldn't need it for a little second
     this.reset2 = spawnpoint_reset; // restores team, allows re-sending the spawnpoint
     this.team_saved = this.team;
     IL_PUSH(g_saved_team, this);
     if (!this.cnt)
         this.cnt = 1;
     if (have_team_spawns != 0)
         if (this.team)
             have_team_spawns = 1;
     have_team_spawns_forteams |= BIT(this.team);
     if (autocvar_r_showbboxes)
     {
         // show where spawnpoints point at too
         vector forward, right, up;
         MAKE_VECTORS(this.angles, forward, right, up);
         entity e = new(info_player_foo);
         setorigin(e, this.origin + forward * 24);
         setsize(e, '-8 -8 -8', '8 8 8');
         e.solid = SOLID_TRIGGER;
     }
     // network it after all spawnpoints are setup, so that we can check if team spawnpoints are used
     InitializeEntity(this, link_spawnpoint, INITPRIO_FINDTARGET);
 }
entity SelectSpawnPoint (entity this, bool anypoint)
Definition at line 329 of file spawnpoints.qc.
References autocvar_g_spawn_furthest, autocvar_g_spawn_useallspawns, autocvar_spawn_debug, BIT, classname, entity(), error(), find(), g_spawnpoints, GotoNextMap(), have_team_spawns, have_team_spawns_forteams, IL_EACH, IL_FIRST, NULL, prev, random(), some_spawn_has_been_used, Spawn_FilterOutBadSpots(), Spawn_WeightedPoint(), team, testspawn_checked, and testspawn_point.
Referenced by buff_Respawn(), Damage(), ka_RespawnBall(), PutObserverInServer(), and PutPlayerInServer().
 {
     float teamcheck;
     entity spot = NULL;
     if(!testspawn_checked)
     {
         testspawn_point = find(NULL, classname, "testplayerstart");
         testspawn_checked = true;
     }
     if(testspawn_point)
         return testspawn_point;
     if(this.spawnpoint_targ)
         return this.spawnpoint_targ;
     if(anypoint || autocvar_g_spawn_useallspawns)
         teamcheck = -1;
     else if(have_team_spawns > 0)
     {
         if(!(have_team_spawns_forteams & BIT(this.team)))
         {
             // we request a spawn for a team, and we have team
             // spawns, but that team has no spawns?
             if(have_team_spawns_forteams & BIT(0))
                 // try noteam spawns
                 teamcheck = 0;
             else
                 // if not, any spawn has to do
                 teamcheck = -1;
         }
         else
             teamcheck = this.team; // MUST be team
     }
     else if(have_team_spawns == 0 && (have_team_spawns_forteams & BIT(0)))
         teamcheck = 0; // MUST be noteam
     else
         teamcheck = -1;
         // if we get here, we either require team spawns but have none, or we require non-team spawns and have none; use any spawn then
     // get the entire list of spots
     //entity firstspot = findchain(classname, "info_player_deathmatch");
     entity firstspot = IL_FIRST(g_spawnpoints);
     entity prev = NULL;
     IL_EACH(g_spawnpoints, true,
     {
         if(prev)
             prev.chain = it;
         it.chain = NULL;
         prev = it;
     });
     // filter out the bad ones
     // (note this returns the original list if none survived)
     if(anypoint)
     {
         spot = Spawn_WeightedPoint(firstspot, 1, 1, 1);
     }
     else
     {
         firstspot = Spawn_FilterOutBadSpots(this, firstspot, 100, teamcheck, true);
         // emergency fallback! double check without targets
         // fixes some crashes with improperly repacked maps
         if(!firstspot)
         {
             firstspot = IL_FIRST(g_spawnpoints);
             prev = NULL;
             IL_EACH(g_spawnpoints, true,
             {
                 if(prev)
                     prev.chain = it;
                 it.chain = NULL;
                 prev = it;
             });
             firstspot = Spawn_FilterOutBadSpots(this, firstspot, 100, teamcheck, false);
         }
         // there is 50/50 chance of choosing a random spot or the furthest spot
         // (this means that roughly every other spawn will be furthest, so you
         // usually won't get fragged at spawn twice in a row)
         if (random() > autocvar_g_spawn_furthest)
             spot = Spawn_WeightedPoint(firstspot, 1, 1, 1);
         else
             spot = Spawn_WeightedPoint(firstspot, 1, 5000, 5); // chooses a far far away spawnpoint
     }
     if (!spot)
     {
         if(autocvar_spawn_debug)
             GotoNextMap(0);
         else
         {
             if(some_spawn_has_been_used)
                 return NULL; // team can't spawn any more, because of actions of other team
             else
                 error("Cannot find a spawn point - please fix the map!");
         }
     }
     return spot;
 }
entity Spawn_FilterOutBadSpots (entity this, entity firstspot, float mindist, float teamcheck, bool targetcheck)
Definition at line 281 of file spawnpoints.qc.
References entity(), NULL, and Spawn_ScoreAll().
Referenced by SelectSpawnPoint(), and trigger_race_checkpoint_verify().
 {
     entity spot, spotlist, spotlistend;
     spotlist = NULL;
     spotlistend = NULL;
     Spawn_ScoreAll(this, firstspot, mindist, teamcheck, targetcheck);
     for(spot = firstspot; spot; spot = spot.chain)
     {
         if(spot.spawnpoint_score.x >= 0) // spawning allowed here
         {
             if(spotlistend)
                 spotlistend.chain = spot;
             spotlistend = spot;
             if(!spotlist)
                 spotlist = spot;
         }
     }
     if(spotlistend)
         spotlistend.chain = NULL;
     return spotlist;
 }
vector Spawn_Score (entity this, entity spot, float mindist, float teamcheck, bool targetcheck)
Definition at line 213 of file spawnpoints.qc.
References entity(), FOREACH_CLIENT, g_cts, IS_DEAD, IS_PLAYER, IS_REAL_CLIENT, LOG_TRACE, M_ARGV, MUTATOR_CALLHOOK, race_spawns, SPAWN_PRIO_GOOD_DISTANCE, targetname, vector(), vlen(), vtos(), and world.
Referenced by Spawn_ScoreAll().
 {
     // filter out spots for the wrong team
     if(teamcheck >= 0)
         if(spot.team != teamcheck)
             return '-1 0 0';
     if(race_spawns)
         if(!spot.target || spot.target == "")
             return '-1 0 0';
     if(IS_REAL_CLIENT(this))
     {
         if(spot.restriction == 1)
             return '-1 0 0';
     }
     else
     {
         if(spot.restriction == 2)
             return '-1 0 0';
     }
     float prio = 0;
     float shortest = vlen(world.maxs - world.mins);
     FOREACH_CLIENT(IS_PLAYER(it) && !IS_DEAD(it) && it != this, {
         float thisdist = vlen(it.origin - spot.origin);
         if (thisdist < shortest)
             shortest = thisdist;
     });
     if(shortest > mindist)
         prio += SPAWN_PRIO_GOOD_DISTANCE;
     vector spawn_score = prio * '1 0 0' + shortest * '0 1 0';
     // filter out spots for assault
     if(spot.target && spot.target != "" && targetcheck)
     {
         int found = 0;
         for(entity targ = findchain(targetname, spot.target); targ; targ = targ.chain)
         {
             ++found;
             if(targ.spawn_evalfunc)
             {
                 spawn_score = targ.spawn_evalfunc(targ, this, spot, spawn_score);
                 if(spawn_score.x < 0)
                     return spawn_score;
             }
         }
         if(!found && !g_cts)
         {
             LOG_TRACE("WARNING: spawnpoint at ", vtos(spot.origin), " could not find its target ", spot.target);
             return '-1 0 0';
         }
     }
     MUTATOR_CALLHOOK(Spawn_Score, this, spot, spawn_score);
     spawn_score = M_ARGV(2, vector);
     return spawn_score;
 }
void Spawn_ScoreAll (entity this, entity firstspot, float mindist, float teamcheck, bool targetcheck)
Definition at line 274 of file spawnpoints.qc.
References entity(), and Spawn_Score().
Referenced by Spawn_FilterOutBadSpots().
 {
     entity spot;
     for(spot = firstspot; spot; spot = spot.chain)
         spot.spawnpoint_score = Spawn_Score(this, spot, mindist, teamcheck, targetcheck);
 }
entity Spawn_WeightedPoint (entity firstspot, float lower, float upper, float exponent)
Definition at line 307 of file spawnpoints.qc.
References bound(), entity(), RandomSelection_AddEnt, RandomSelection_chosen_ent, and RandomSelection_Init().
Referenced by SelectSpawnPoint().
 {
     // weight of a point: bound(lower, mindisttoplayer, upper)^exponent
     // multiplied by spot.cnt (useful if you distribute many spawnpoints in a small area)
     entity spot;
     RandomSelection_Init();
     for(spot = firstspot; spot; spot = spot.chain)
         RandomSelection_AddEnt(spot, (bound(lower, spot.spawnpoint_score.y, upper) ** exponent) * spot.cnt, (spot.spawnpoint_score.y >= lower) * 0.5 + spot.spawnpoint_score.x);
     return RandomSelection_chosen_ent;
 }
bool SpawnEvent_Send (entity this, entity to, int sf)
Definition at line 32 of file spawnpoints.qc.
References autocvar_g_spawn_alloweffects, etof(), IS_SPEC, owner, and WriteByte().
Referenced by PutPlayerInServer().
 {
     float send;
     WriteHeader(MSG_ENTITY, ENT_CLIENT_SPAWNEVENT);
     if(autocvar_g_spawn_alloweffects)
     {
         WriteByte(MSG_ENTITY, etof(this.owner));
         WriteVector(MSG_ENTITY, this.owner.origin);
         send = true;
     }
     else if((to == this.owner) || (IS_SPEC(to) && (to.enemy == this.owner)) )
     {
         WriteByte(MSG_ENTITY, 0);
         send = true;
     }
     else { send = false; }
     return send;
 }
spawnfunc (info_player_survivor)
Definition at line 156 of file spawnpoints.qc.
 {
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_start)
Definition at line 161 of file spawnpoints.qc.
 {
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_deathmatch)
Definition at line 166 of file spawnpoints.qc.
References g_spawnpoints, IL_PUSH(), and relocate_spawnpoint().
 {
     IL_PUSH(g_spawnpoints, this);
     relocate_spawnpoint(this);
 }
spawnfunc (info_player_team1)
Definition at line 175 of file spawnpoints.qc.
References NUM_TEAM_1, and team.
 {
     this.team = NUM_TEAM_1; // red
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_team2)
Definition at line 185 of file spawnpoints.qc.
References NUM_TEAM_2, and team.
 {
     this.team = NUM_TEAM_2; // blue
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_team3)
Definition at line 194 of file spawnpoints.qc.
References NUM_TEAM_3, and team.
 {
     this.team = NUM_TEAM_3; // yellow
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_team4)
Definition at line 204 of file spawnpoints.qc.
References NUM_TEAM_4, and team.
 {
     this.team = NUM_TEAM_4; // purple
     spawnfunc_info_player_deathmatch(this);
 }
void spawnpoint_reset (entity this)
Definition at line 77 of file spawnpoints.qc.
Referenced by relocate_spawnpoint().
 {
     this.SendFlags |= 1; // update team since it was restored during reset
 }
bool SpawnPoint_Send (entity this, entity to, int sf)
Definition at line 22 of file spawnpoints.qc.
References origin, team, and WriteByte().
Referenced by link_spawnpoint().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_SPAWNPOINT);
     WriteByte(MSG_ENTITY, this.team);
     WriteVector(MSG_ENTITY, this.origin);
     return true;
 }
void spawnpoint_think (entity this)
Definition at line 55 of file spawnpoints.qc.
References nextthink, origin, spawnpoint_prevorigin, and time.
Referenced by relocate_spawnpoint().
 {
     this.nextthink = time + 0.1;
     if(this.origin != this.spawnpoint_prevorigin)
     {
         this.spawnpoint_prevorigin = this.origin;
         this.SendFlags |= 1;
     }
 }
void spawnpoint_use (entity this, entity actor, entity trigger)
Definition at line 65 of file spawnpoints.qc.
References have_team_spawns, some_spawn_has_been_used, team, and teamplay.
Referenced by relocate_spawnpoint().
 {
     if(teamplay)
     if(have_team_spawns > 0)
     {
         this.team = actor.team;
         some_spawn_has_been_used = true;
         this.SendFlags |= 1; // update team on the client side
     }
     //LOG_INFO("spawnpoint was used!\n");
 }
Variable Documentation
vector spawnpoint_prevorigin
Definition at line 54 of file spawnpoints.qc.
Referenced by spawnpoint_think().
bool testspawn_checked
Definition at line 327 of file spawnpoints.qc.
Referenced by SelectSpawnPoint().
entity testspawn_point
Definition at line 328 of file spawnpoints.qc.
Referenced by SelectSpawnPoint().