Xonotic: menu/xonotic/dialog_hudpanel_vote.qc File Reference
dialog_hudpanel_vote.qc File Reference
#include "dialog_hudpanel_vote.qh"
#include "checkbox.qh"
#include "textlabel.qh"
#include "slider.qh"
Functions
void XonoticHUDVoteDialog_fill (entity me)
Function Documentation
void XonoticHUDVoteDialog_fill (entity me)
Definition at line 7 of file dialog_hudpanel_vote.qc.
References DIALOG_HUDPANEL_COMMON, entity(), makeXonoticSlider(), and makeXonoticTextLabel().
 {
     entity e;
     string panelname = "vote";
     DIALOG_HUDPANEL_COMMON();
     me.TR(me);
         me.TD(me, 1, 1.4, e = makeXonoticTextLabel(0, _("Alpha after voting:")));
         me.TD(me, 1, 2.6, e = makeXonoticSlider(0.1, 1, 0.1, "hud_panel_vote_alreadyvoted_alpha"));
 }