Xonotic: lib/warpzone/mathlib.qc File Reference
mathlib.qc File Reference
#include "mathlib.qh"
Functions
float acosh (float e)
float asinh (float e)
float atanh (float e)
float cbrt (float e)
float copysign (float e, float f)
float cosh (float e)
float erf (float e)
float erfc (float e)
float exp (float e)
float exp2 (float e)
float expm1 (float e)
float fdim (float e, float f)
float fma (float e, float f, float g)
float fmax (float e, float f)
float fmin (float e, float f)
float fmod (float e, float f)
int fpclassify (float e)
vector frexp (float e)
float hypot (float e, float f)
int ilogb (float e)
bool isfinite (float e)
int isgreater (float e, float f)
int isgreaterequal (float e, float f)
bool isinf (float e)
int isless (float e, float f)
int islessequal (float e, float f)
int islessgreater (float e, float f)
bool isnan (float e)
bool isnormal (float e)
int isunordered (float e, float f)
float ldexp (float x, int e)
vector lgamma (float e)
float log10 (float e)
float log1p (float e)
float log2 (float e)
float logb (float e)
float logn (float e, float base)
vector modf (float f)
float nan (string tag)
float nearbyint (float e)
float nextafter (float e, float f)
float nexttoward (float e, float f)
float pymod (float e, float f)
Pythonic mod: TODO: %% operator?
float remainder (float e, float f)
vector remquo (float e, float f)
float scalbn (float e, int n)
bool signbit (float e)
float sinh (float e)
float tanh (float e)
float tgamma (float e)
float trunc (float e)
Function Documentation
float acosh (float e)
Definition at line 48 of file mathlib.qc.
References log(), and sqrt().
 {
     return log(e + sqrt(e*e - 1));
 }
float asinh (float e)
Definition at line 52 of file mathlib.qc.
References log(), and sqrt().
 {
     return log(e + sqrt(e*e + 1));
 }
float atanh (float e)
Definition at line 56 of file mathlib.qc.
References log().
 {
     return 0.5 * log((1+e) / (1-e));
 }
float cbrt (float e)
Definition at line 132 of file mathlib.qc.
References copysign(), fabs(), and pow().
Referenced by solve_cubic_pq().
 {
     return copysign(pow(fabs(e), (1.0/3.0)), e);
 }
float copysign (float e, float f)
Definition at line 225 of file mathlib.qc.
References fabs().
Referenced by AdjustAirAccelQW(), cbrt(), erf(), and lgamma().
 {
     return fabs(e) * ((f>0) ? 1 : -1);
 }
float cosh (float e)
Definition at line 60 of file mathlib.qc.
References exp().
Referenced by tanh().
 {
     return 0.5 * (exp(e) + exp(-e));
 }
float erf (float e)
Definition at line 141 of file mathlib.qc.
References copysign(), exp(), and sqrt().
Referenced by erfc().
 {
     // approximation taken from wikipedia
     float f;
     f = e*e;
     return copysign(sqrt(1 - exp(-f * (1.273239544735163 + 0.14001228868667 * f) / (1 + 0.14001228868667 * f))), e);
 }
float erfc (float e)
Definition at line 148 of file mathlib.qc.
References erf().
 {
     return 1.0 - erf(e);
 }
float exp (float e)
Definition at line 73 of file mathlib.qc.
References M_E, and pow().
Referenced by anticheat_physics(), cosh(), erf(), expm1(), fromDecibelOfSquare(), GenericCommand_rpn(), GetCurrentFov(), ListBox_draw(), sinh(), tgamma(), and toDecibelOfSquare().
 {
     return pow(M_E, e);
 }
float exp2 (float e)
Definition at line 77 of file mathlib.qc.
References pow().
 {
     return pow(2, e);
 }
float expm1 (float e)
Definition at line 81 of file mathlib.qc.
References exp().
 {
     return exp(e) - 1;
 }
float fdim (float e, float f)
Definition at line 260 of file mathlib.qc.
References max().
 {
     return max(e-f, 0);
 }
float fma (float e, float f, float g)
Definition at line 272 of file mathlib.qc.
 {
     return e * f + g;
 }
float fmax (float e, float f)
Definition at line 264 of file mathlib.qc.
References max().
 {
     return max(e, f);
 }
float fmin (float e, float f)
Definition at line 268 of file mathlib.qc.
References min().
 {
     return min(e, f);
 }
float fmod (float e, float f)
Definition at line 208 of file mathlib.qc.
References trunc().
Referenced by CSQCModel_Effects_Apply().
 {
     return e - f * trunc(e / f);
 }
int fpclassify (float e)
Definition at line 7 of file mathlib.qc.
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_ZERO, isinf(), and isnan().
 {
     if(isnan(e))
         return FP_NAN;
     if(isinf(e))
         return FP_INFINITE;
     if(e == 0)
         return FP_ZERO;
     return FP_NORMAL;
 }
vector frexp (float e)
Definition at line 86 of file mathlib.qc.
References ilogb(), pow(), v, and vector().
 {
     vector v;
     v.z = 0;
     v.y = ilogb(e) + 1;
     v.x = e / pow(2, v.y);
     return v;
 }
float hypot (float e, float f)
Definition at line 136 of file mathlib.qc.
References sqrt().
 {
     return sqrt(e*e + f*f);
 }
int ilogb (float e)
Definition at line 94 of file mathlib.qc.
References fabs(), floor(), and log2().
Referenced by frexp().
 {
     return floor(log2(fabs(e)));
 }
bool isfinite (float e)
Definition at line 17 of file mathlib.qc.
References isinf(), and isnan().
Referenced by isnormal(), and lgamma().
 {
     return !(isnan(e) || isinf(e));
 }
int isgreater (float e, float f)
Definition at line 277 of file mathlib.qc.
 {
     return e > f;
 }
int isgreaterequal (float e, float f)
Definition at line 281 of file mathlib.qc.
 {
     return e >= f;
 }
bool isinf (float e)
Definition at line 21 of file mathlib.qc.
Referenced by fpclassify(), and isfinite().
 {
     return (e != 0) && (e + e == e);
 }
int isless (float e, float f)
Definition at line 285 of file mathlib.qc.
 {
     return e < f;
 }
int islessequal (float e, float f)
Definition at line 289 of file mathlib.qc.
 {
     return e <= f;
 }
int islessgreater (float e, float f)
Definition at line 293 of file mathlib.qc.
 {
     return e < f || e > f;
 }
bool isnan (float e)
Definition at line 25 of file mathlib.qc.
References ftos().
Referenced by fpclassify(), is_all_nans(), and isfinite().
 {
     // The sane way to detect NaN is this:
     // float f = e;
     // return (e != f);
     // but darkplaces used to be compiled with -ffinite-math-only which broke it.
     // DP is fixed now but until all clients update (so after 0.8.3) we have to use the following workaround
     // or they'd have issues when connecting to newer servers.
     // Negative NaN ("-nan") is much more common but plain "nan" can be created by negating *some* -nans so we need to check both.
     // DP's QCVM and GMQCC's QCVM behave differently - one needs ftos(-(0.0 / 0.0)), the other ftos(-sqrt(-1)).
     string s = ftos(e);
     return s == "nan" || s == "-nan";
 }
bool isnormal (float e)
Definition at line 39 of file mathlib.qc.
References isfinite().
 {
     return isfinite(e);
 }
int isunordered (float e, float f)
Definition at line 297 of file mathlib.qc.
 {
     return !(e < f || e == f || e > f);
 }
float ldexp (float x, int e)
Definition at line 98 of file mathlib.qc.
References pow().
 {
     return x * pow(2, e);
 }
vector lgamma (float e)
Definition at line 152 of file mathlib.qc.
References copysign(), fabs(), floor(), isfinite(), lgamma(), log(), M_PI, nan(), sin(), v, and vector().
Referenced by lgamma(), and tgamma().
 {
     // TODO improve accuracy
     if(!isfinite(e))
         return fabs(e) * '1 0 0' + copysign(1, e) * '0 1 0';
     if(e < 1 && e == floor(e))
         return nan("gamma") * '1 1 1';
     if(e < 0.1)
     {
         vector v;
         v = lgamma(1.0 - e);
         // reflection formula:
         // gamma(1-z) * gamma(z) = pi / sin(pi*z)
         // lgamma(1-z) + lgamma(z) = log(pi) - log(sin(pi*z))
         // sign of gamma(1-z) = sign of gamma(z) * sign of sin(pi*z)
         v.z = sin(M_PI * e);
         v.x = log(M_PI) - log(fabs(v.z)) - v.x;
         if(v.z < 0)
             v.y = -v.y;
         v.z = 0;
         return v;
     }
     if(e < 1.1)
         return lgamma(e + 1) - log(e) * '1 0 0';
     e -= 1;
     return (0.5 * log(2 * M_PI * e) + e * (log(e) - 1)) * '1 0 0' + '0 1 0';
 }
float log10 (float e)
Definition at line 106 of file mathlib.qc.
References log(), and M_LOG10E.
 {
     return log(e) * M_LOG10E;
 }
float log1p (float e)
Definition at line 110 of file mathlib.qc.
References log().
 {
     return log(e + 1);
 }
float log2 (float e)
Definition at line 114 of file mathlib.qc.
References log(), and M_LOG2E.
Referenced by ilogb(), and logb().
 {
     return log(e) * M_LOG2E;
 }
float logb (float e)
Definition at line 118 of file mathlib.qc.
References fabs(), floor(), and log2().
 {
     return floor(log2(fabs(e)));
 }
float logn (float e, float base)
Definition at line 102 of file mathlib.qc.
References log().
Referenced by buff_Inferno_CalculateTime().
 {
     return log(e) / log(base);
 }
vector modf (float f)
Definition at line 122 of file mathlib.qc.
References trunc().
 {
     return '1 0 0' * (f - trunc(f)) + '0 1 0' * trunc(f);
 }
float nan (string tag)
Definition at line 230 of file mathlib.qc.
References sqrt().
Referenced by lgamma(), and nextafter().
 {
     return sqrt(-1);
 }
float nearbyint (float e)
Definition at line 199 of file mathlib.qc.
References rint().
 {
     return rint(e);
 }
float nextafter (float e, float f)
Definition at line 234 of file mathlib.qc.
References fabs(), max(), nan(), and nextafter().
Referenced by nextafter(), and nexttoward().
 {
     // TODO very crude
     if(e == f)
         return nan("nextafter");
     if(e > f)
         return -nextafter(-e, -f);
     // now we know that e < f
     // so we need the next number > e
     float d, a, b;
     d = max(fabs(e), 0.00000000000000000000001);
     a = e + d;
     do
     {
         d *= 0.5;
         b = a;
         a = e + d;
     }
     while(a != e);
     return b;
 }
float nexttoward (float e, float f)
Definition at line 255 of file mathlib.qc.
References nextafter().
 {
     return nextafter(e, f);
 }
float pymod (float e, float f)
Pythonic mod: TODO: %% operator?
1 % 2 == 1 -1 % 2 == 1 1 % -2 == -1 -1 % -2 == -1
Definition at line 194 of file mathlib.qc.
References floor().
 {
     return e - f * floor(e / f);
 }
float remainder (float e, float f)
Definition at line 212 of file mathlib.qc.
References rint().
Referenced by IsMoveInDirection().
 {
     return e - f * rint(e / f);
 }
vector remquo (float e, float f)
Definition at line 216 of file mathlib.qc.
References rint(), v, and vector().
 {
     vector v;
     v.z = 0;
     v.y = rint(e / f);
     v.x = e - f * v.y;
     return v;
 }
float scalbn (float e, int n)
Definition at line 127 of file mathlib.qc.
References pow().
 {
     return e * pow(2, n);
 }
bool signbit (float e)
Definition at line 43 of file mathlib.qc.
 {
     return (e < 0);
 }
float sinh (float e)
Definition at line 64 of file mathlib.qc.
References exp().
Referenced by tanh().
 {
     return 0.5 * (exp(e) - exp(-e));
 }
float tanh (float e)
Definition at line 68 of file mathlib.qc.
References cosh(), and sinh().
Referenced by ctf_CalculatePassVelocity().
 {
     return sinh(e) / cosh(e);
 }
float tgamma (float e)
Definition at line 179 of file mathlib.qc.
References exp(), lgamma(), v, and vector().
 {
     vector v = lgamma(e);
     return exp(v.x) * v.y;
 }
float trunc (float e)
Definition at line 203 of file mathlib.qc.
References ceil(), and floor().
Referenced by fmod(), and modf().
 {
     return (e>=0) ? floor(e) : ceil(e);
 }