Xonotic: common/state.qh File Reference
state.qh File Reference
Classes
class ClientState
Purpose: common client state, usable on client and server Client: singleton representing the viewed player Server: instance per client.
class PlayerState
Purpose: common player state, usable on client and server Client: singleton representing the viewed player Server: instance per client, clients decoupled from players.
Macros
#define CS_CVAR(this) (this)
#define PS(this) ((this)._ps)
Functions
void ClientState_attach (entity this)
void ClientState_detach (entity this)
ClientState CS (Client this)
void PlayerState_attach (entity this)
void PlayerState_detach (entity this)
Variables
ClientState _cs
PlayerState _ps
Macro Definition Documentation
CS_CVAR
#define CS_CVAR (this) (this)
Definition at line 51 of file state.qh.
Referenced by accuracy_send(), antilag_getlag(), bot_setclientfields(), buff_Touch(), buff_Waypoint_visible_for_player(), ClientCommand_autoswitch(), ClientCommand_physics(), ClientCommand_sentcvar(), ClientDisconnect(), ClientState_detach(), for(), GiveItems(), Handicap_GetVoluntaryHandicap(), IntermissionThink(), Item_GiveTo(), MUTATOR_HOOKFUNCTION(), ObserverOrSpectatorThink(), PlayerPreThink(), PlayerThink(), PutPlayerInServer(), race_checkAndWriteName(), tracebox_antilag(), traceline_antilag(), UpdatePlayerSounds(), W_Model(), W_NextWeapon(), W_NextWeaponOnImpulse(), W_PreviousWeapon(), W_SetupShot_Dir_ProjectileSize_Range(), W_SwitchWeapon(), W_SwitchWeapon_TryOthers(), WarpZone_tracebox_antilag(), and WarpZone_traceline_antilag().
PS
#define PS (this) ((this)._ps)
Definition at line 18 of file state.qh.
Referenced by client_hasweapon(), door_check_keys(), fireBullet_antilag(), PlayerDamage(), PlayerState_attach(), PlayerState_detach(), PutClientInServer(), PutPlayerInServer(), reset_map(), SpectateCopy(), trigger_keylock_touch(), and W_WeaponFrame().
Function Documentation
ClientState_attach()
void ClientState_attach (entity this)
Definition at line 46 of file state.qc.
 {
     this._cs = NEW(ClientState, this);
     // TODO: fold all of these into ClientState
     DecodeLevelParms(this);
     PlayerScore_Attach(this);
     PlayerStats_PlayerBasic_CheckUpdate(this);
     ClientData_Attach(this);
     accuracy_init(this);
     entcs_attach(this);
     anticheat_init(this);
     W_HitPlotOpen(this);
     InventoryStorage_attach(this);
     StatusEffectsStorage_attach(this);
 }
ClientState_detach()
void ClientState_detach (entity this)
Definition at line 73 of file state.qc.
References _cs, accuracy_free(), anticheat_report_to_eventlog(), bot_clientdisconnect(), ClientData_Detach(), CS(), CS_CVAR, entcs_detach(), GetCvars(), InventoryStorage_delete(), NULL, PlayerScore_Detach(), and W_HitPlotClose().
Referenced by ClientDisconnect().
 {
     GetCvars(this, CS_CVAR(this), -1);  // free cvars TODO: is this still needed now that it's stored on the clientstate entity?
     accuracy_free(this); // TODO: needs to be before CS() is deleted!
     PlayerScore_Detach(this); // what ^they^ said
     W_HitPlotClose(this);
     ClientData_Detach(this);
     entcs_detach(this);
     InventoryStorage_delete(this);
     StatusEffectsStorage_delete(this);
     delete(CS(this));
     this._cs = NULL;
     bot_clientdisconnect(this);
     anticheat_report_to_eventlog(this);
 }
CS()
ClientState CS (Client this)
Definition at line 47 of file state.qh.
References _cs, assert, and TC.
Referenced by accuracy_add(), accuracy_free(), accuracy_init(), accuracy_resend(), accuracy_reset(), accuracy_send(), anticheat_fixangle(), anticheat_init(), anticheat_physics(), anticheat_prethink(), anticheat_report_to_eventlog(), anticheat_report_to_playerstats(), anticheat_spectatecopy(), antilag_restore_all(), antilag_takeback_all(), BanCommand_mute(), BanCommand_unmute(), bot_cmd_impulse(), bot_cmd_pause(), bot_lagfunc(), bot_presskeys(), bot_think(), botframe_autowaypoints_fix_from(), ChatBubbleThink(), client_hasweapon(), ClientCommand_clientversion(), ClientCommand_join(), ClientCommand_minigame(), ClientCommand_selectteam(), ClientConnect(), ClientData_Attach(), ClientData_Detach(), ClientData_Send(), ClientData_Touch(), ClientDisconnect(), ClientState_detach(), CommonCommand_timeout(), CommonCommand_who(), crosshair_trace(), ctf_FlagThink(), Damage(), DecodeLevelParms(), Drag(), DumpStats(), EndFrame(), FireRailgunBullet(), FixPlayermodel(), frag_centermessage_override(), GameCommand_nospectators(), GetClientVersionMessage(), GetPlayerScoreString(), GetPressedKeys(), Handicap_GetForcedHandicap(), Handicap_Initialize(), Handicap_SetForcedHandicap(), havocbot_ai(), havocbot_aim(), havocbot_ctf_reset_role(), havocbot_keyboard_movement(), havocbot_movetogoal(), Heal(), ImpulseCommands(), invite_minigame(), IsFlying(), joinAllowed(), lms_RemovePlayer(), MapVote_Tick(), minigame_addplayer(), minigame_find_player(), MinigameImpulse(), MUTATOR_HOOKFUNCTION(), Obituary(), ObserverOrSpectatorThink(), part_minigame(), PingPLReport_Think(), player_clear_minigame(), Player_Physics(), Player_SetTeamIndexChecked(), PlayerDamage(), PlayerPostThink(), PlayerPreThink(), PlayerScore_Add(), PlayerScore_Attach(), PlayerScore_Clear(), PlayerScore_Detach(), PlayerScore_PlayerStats(), PlayerScore_Set(), PlayerScore_Sort(), PlayerTeamScore_Compare(), PlayerThink(), PM_check_specialcommand(), PrintWelcomeMessage(), PutObserverInServer(), PutPlayerInServer(), race_AbandonRaceCheck(), race_GetFractionalLapCount(), race_SendTime(), ReadyRestart_force(), reset_map(), Say(), Score_ClearAll(), Score_NicePrint_Player(), SetChangeParms(), SetPlayerTeam(), SetSpectatee_status(), SetZoomState(), ShowTeamSelection(), SpectateCopy(), STATIC_INIT(), SV_ParseClientCommand_floodcheck(), sys_phys_monitor(), sys_phys_override(), sys_phys_spectator_control(), vehicles_enter(), W_HitPlotAnalysis(), W_HitPlotClose(), W_HitPlotOpen(), W_Nexball_Touch(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_crosshair_trace(), WarpZone_Projectile_Touch(), WinningCondition_Race(), and WinningConditionHelper().
 { TC(Client, this); assert(this._cs); return this._cs; }
PlayerState_attach()
void PlayerState_attach (entity this)
Definition at line 12 of file state.qc.
References _ps, Inventory_new(), NEW, and PS.
Referenced by PutPlayerInServer().
 {
     if (PS(this) && PS(this).m_client == this)
         return;
     this._ps = NEW(PlayerState, this);
     Inventory_new(PS(this));
 }
PlayerState_detach()
void PlayerState_detach (entity this)
Definition at line 22 of file state.qc.
References accuracy_init(), anticheat_init(), bot_clientconnect(), ClientData_Attach(), DecodeLevelParms(), entcs_attach(), entity(), FOREACH_CLIENT, Inventory_clear(), Inventory_delete(), NULL, PlayerScore_Attach(), PS, and W_HitPlotOpen().
Referenced by PutObserverInServer().
 {
     PlayerState ps = PS(this);
     if (!ps) return;  // initial connect
     PS(this) = NULL;
     Inventory_clear(this.inventory_store); // no need to network updates, as there is no inventory attached
     if (ps.m_client != this) return;  // don't own state, spectator
     ps.ps_push(ps, this);
     Inventory_delete(ps);
     FOREACH_CLIENT(PS(it) == ps, { PS(it) = NULL; });
     delete(ps);
 }
Variable Documentation
_cs
ClientState _cs
Definition at line 42 of file state.qh.
Referenced by ClientState_attach(), ClientState_detach(), and CS().
_ps
PlayerState _ps
Definition at line 17 of file state.qh.
Referenced by CopyBody(), and PlayerState_attach().