Xonotic: server/ipban.qh File Reference
ipban.qh File Reference
Functions
void Ban_LoadBans ()
float Ban_MaybeEnforceBan (entity client)
float Ban_MaybeEnforceBanOnce (entity client)
void Ban_SaveBans ()
float BanCommand (string command)
void OnlineBanList_URI_Get_Callback (float id, float status, string data)
Function Documentation
void Ban_LoadBans ()
Definition at line 303 of file ipban.qc.
References argv(), autocvar_g_banned_list, ban_count, Ban_Delete(), ban_expire, ban_ip, ban_loaded, entity(), OnlineBanList_Think(), setthink, stof(), strzone(), time, and tokenize_console.
Referenced by Ban_IsClientBanned(), and spawnfunc().
 {
     float i, n;
     for(i = 0; i < ban_count; ++i)
         Ban_Delete(i);
     ban_count = 0;
     ban_loaded = true;
     n = tokenize_console(autocvar_g_banned_list);
     if(stof(argv(0)) == 1)
     {
         ban_count = (n - 1) / 2;
         for(i = 0; i < ban_count; ++i)
         {
             ban_ip[i] = strzone(argv(2*i+1));
             ban_expire[i] = time + stof(argv(2*i+2));
         }
     }
     entity e = new(bansyncer);
     setthink(e, OnlineBanList_Think);
     e.nextthink = time + 1;
 }
float Ban_MaybeEnforceBan (entity client)
Definition at line 449 of file ipban.qc.
References Ban_IsClientBanned(), and bprint().
Referenced by Ban_MaybeEnforceBanOnce().
 {
     if (Ban_IsClientBanned(client, -1))
     {
         string s = sprintf("^1NOTE:^7 banned client %s just tried to enter\n", client.netaddress);
         dropclient(client);
         bprint(s);
         return true;
     }
     return false;
 }
float Ban_MaybeEnforceBanOnce (entity client)
Definition at line 462 of file ipban.qc.
References Ban_MaybeEnforceBan().
Referenced by ClientConnect(), and SV_ParseClientCommand().
 {
     if (client.ban_checked) return false;
     client.ban_checked = true;
     return Ban_MaybeEnforceBan(client);
 }
void Ban_SaveBans ()
Definition at line 261 of file ipban.qc.
References ban_count, ban_expire, ban_ip, ban_loaded, cvar_set(), ftos(), strcat(), strlen(), and time.
Referenced by Ban_Delete(), Ban_Insert(), and Shutdown().
 {
     string out;
     float i;
     if(!ban_loaded)
         return;
     // version of list
     out = "1";
     for(i = 0; i < ban_count; ++i)
     {
         if(time > ban_expire[i])
             continue;
         out = strcat(out, " ", ban_ip[i]);
         out = strcat(out, " ", ftos(ban_expire[i] - time));
     }
     if(strlen(out) <= 1) // no real entries
         cvar_set("g_banned_list", "");
     else
         cvar_set("g_banned_list", out);
 }
float BanCommand (string command)
Definition at line 315 of file banning.qc.
References BanCommand_macro_command(), and tokenize_console.
Referenced by GameCommand().
 {
     float argc = tokenize_console(command);
     // Guide for working with argc arguments by example:
     // argc:   1    - 2      - 3     - 4
     // argv:   0    - 1      - 2     - 3
     // cmd     vote - master - login - password
     if (BanCommand_macro_command(argc, command)) // continue as usual and scan for normal commands
         return true;                             // handled by one of the above GenericCommand_* functions
     return false;
 }
void OnlineBanList_URI_Get_Callback (float id, float status, string data)
Definition at line 80 of file ipban.qc.
References argv(), autocvar_g_ban_sync_interval, autocvar_g_ban_sync_timeout, autocvar_g_ban_sync_trusted_servers_verify, autocvar_g_ban_sync_uri, Ban_Insert(), ftos(), LABEL, LOG_INFO, LOG_TRACE(), MAX_IPBAN_URIS, min(), OnlineBanList_RequestWaiting, OnlineBanList_Servers, OnlineBanList_Timeout, stof(), strcat(), strlen(), strstrofs, substring(), time, tokenize_console, tokenizebyseparator, and URI_GET_IPBAN.
Referenced by URI_Get_Callback().
 {
     float n, i, j, l;
     string ip;
     float timeleft;
     string reason;
     string serverip;
     float syncinterval;
     string uri;
     id -= URI_GET_IPBAN;
     if(id >= MAX_IPBAN_URIS)
     {
         LOG_INFO("Received ban list for invalid ID\n");
         return;
     }
     tokenize_console(autocvar_g_ban_sync_uri);
     uri = argv(id);
     LOG_INFO("Received ban list from ", uri, ": ");
     if(OnlineBanList_RequestWaiting[id] == 0)
     {
         LOG_INFO("rejected (unexpected)\n");
         return;
     }
     OnlineBanList_RequestWaiting[id] = 0;
     if(time > OnlineBanList_Timeout)
     {
         LOG_INFO("rejected (too late)\n");
         return;
     }
     syncinterval = autocvar_g_ban_sync_interval;
     if(syncinterval == 0)
     {
         LOG_INFO("rejected (syncing disabled)\n");
         return;
     }
     if(syncinterval > 0)
         syncinterval *= 60;
     if(status != 0)
     {
         LOG_INFO("error: status is ", ftos(status), "\n");
         return;
     }
     if(substring(data, 0, 1) == "<")
     {
         LOG_INFO("error: received HTML instead of a ban list\n");
         return;
     }
     if(strstrofs(data, "\r", 0) != -1)
     {
         LOG_INFO("error: received carriage returns\n");
         return;
     }
     if(data == "")
         n = 0;
     else
         n = tokenizebyseparator(data, "\n");
     if((n % 4) != 0)
     {
         LOG_INFO("error: received invalid item count: ", ftos(n), "\n");
         return;
     }
     LOG_INFO("OK, ", ftos(n / 4), " items\n");
     for(i = 0; i < n; i += 4)
     {
         ip = argv(i);
         timeleft = stof(argv(i + 1));
         reason = argv(i + 2);
         serverip = argv(i + 3);
         LOG_TRACE("received ban list item ", ftos(i / 4), ": ip=", ip);
         LOG_TRACE(" timeleft=", ftos(timeleft), " reason=", reason);
         LOG_TRACE(" serverip=", serverip);
         timeleft -= 1.5 * autocvar_g_ban_sync_timeout;
         if(timeleft < 0)
             continue;
         l = strlen(ip);
         if(l != 44) // length 44 is a cryptographic ID
         {
             for(j = 0; j < l; ++j)
                 if(strstrofs("0123456789.", substring(ip, j, 1), 0) == -1)
                 {
                     LOG_INFO("Invalid character ", substring(ip, j, 1), " in IP address ", ip, ". Skipping this ban.\n");
                     goto skip;
                 }
         }
         if(autocvar_g_ban_sync_trusted_servers_verify)
             if((strstrofs(strcat(";", OnlineBanList_Servers, ";"), strcat(";", serverip, ";"), 0) == -1))
                 continue;
         if(syncinterval > 0)
             timeleft = min(syncinterval + (OnlineBanList_Timeout - time) + 5, timeleft);
             // the ban will be prolonged on the next sync
             // or expire 5 seconds after the next timeout
         Ban_Insert(ip, timeleft, strcat("ban synced from ", serverip, " at ", uri), 0);
         LOG_INFO("Ban list syncing: accepted ban of ", ip, " by ", serverip, " at ", uri, ": ");
         LOG_INFO(reason, "\n");
 LABEL(skip)
     }
 }