Xonotic: common/gamemodes/gamemode/keepaway/cl_keepaway.qc File Reference
cl_keepaway.qc File Reference
#include "cl_keepaway.qh"
#include <client/hud/panel/modicons.qh>
Functions
void HUD_Mod_Keepaway (vector pos, vector mySize)
Variables
int kaball_prevstatus
float kaball_statuschange_time
Function Documentation
void HUD_Mod_Keepaway (vector pos, vector mySize)
Definition at line 12 of file cl_keepaway.qc.
References blink(), bound(), DRAWFLAG_NORMAL, drawpic_aspect_skin, drawpic_aspect_skin_expanding(), eX, eY, IT_KEY1, kaball_prevstatus, kaball_statuschange_time, mod_active, panel_fg_alpha, time, vec2, and vector().
Referenced by Keepaway::m_isAlwaysSupported().
 {
     mod_active = 1; // keepaway should always show the mod HUD
     float kaball_alpha = blink(0.85, 0.15, 5);
     int stat_items = STAT(ITEMS);
     int kaball = (stat_items/IT_KEY1) & 1;
     if(kaball != kaball_prevstatus)
     {
         kaball_statuschange_time = time;
         kaball_prevstatus = kaball;
     }
     vector kaball_pos, kaball_size;
     if(mySize.x > mySize.y) {
         kaball_pos = pos + eX * 0.25 * mySize.x;
         kaball_size = vec2(0.5 * mySize.x, mySize.y);
     } else {
         kaball_pos = pos + eY * 0.25 * mySize.y;
         kaball_size = vec2(mySize.x, 0.5 * mySize.y);
     }
     float kaball_statuschange_elapsedtime = time - kaball_statuschange_time;
     float f = bound(0, kaball_statuschange_elapsedtime*2, 1);
     if(kaball_prevstatus && f < 1)
         drawpic_aspect_skin_expanding(kaball_pos, "keepawayball_carrying", kaball_size, '1 1 1', panel_fg_alpha * kaball_alpha, DRAWFLAG_NORMAL, f);
     if(kaball)
         drawpic_aspect_skin(pos, "keepawayball_carrying", vec2(mySize.x, mySize.y), '1 1 1', panel_fg_alpha * kaball_alpha * f, DRAWFLAG_NORMAL);
 }
Variable Documentation
int kaball_prevstatus
Definition at line 6 of file cl_keepaway.qc.
Referenced by HUD_Mod_Keepaway().
float kaball_statuschange_time
Definition at line 7 of file cl_keepaway.qc.
Referenced by HUD_Mod_Keepaway().