Xonotic: client/hud/panel/centerprint.qc File Reference
centerprint.qc File Reference
#include "centerprint.qh"
#include "scoreboard.qh"
#include <common/notifications/all.qh>
#include <client/miscfunctions.qh>
Functions
void centerprint_Add (int new_id, string strMessage, float duration, int countdown_num)
void centerprint_AddStandard (string strMessage)
void centerprint_Kill (int id)
void centerprint_KillAll ()
void HUD_CenterPrint ()
void HUD_CenterPrint_Export (int fh)
Variables
bool centerprint_bold [CENTERPRINT_MAX_MSGS]
int centerprint_countdown_num [CENTERPRINT_MAX_MSGS]
float centerprint_expire_time [CENTERPRINT_MAX_MSGS]
const int CENTERPRINT_MAX_ENTRIES = 50
const int CENTERPRINT_MAX_MSGS = 10
string centerprint_messages [CENTERPRINT_MAX_MSGS]
int centerprint_msgID [CENTERPRINT_MAX_MSGS]
bool centerprint_showing
const float CENTERPRINT_SPACING = 0.7
float centerprint_time [CENTERPRINT_MAX_MSGS]
int cpm_index
float hud_configure_cp_generation_time
Function Documentation
void centerprint_Add (int new_id, string strMessage, float duration, int countdown_num)
Definition at line 46 of file centerprint.qc.
References autocvar_hud_panel_centerprint_fade_out, autocvar_hud_panel_centerprint_time, BOLD_OPERATOR, centerprint_bold, centerprint_countdown_num, centerprint_expire_time, CENTERPRINT_MAX_MSGS, centerprint_messages, centerprint_msgID, centerprint_showing, centerprint_time, cpm_index, max(), min(), strcpy, strlen(), substring(), and TC.
Referenced by centerprint_AddStandard(), centerprint_Kill(), HUD_CenterPrint(), and Local_Notification_sprintf().
 {
     TC(int, new_id); TC(int, countdown_num);
     //LOG_INFOF("centerprint_Add: ^2id: %d ^3dur: %d ^5countdown: %d\n'%s'", new_id, duration, countdown_num, strreplace("\n", "^7\\n^7", strMessage));
     int i, j;
     if(strMessage == "" && new_id == 0)
         return;
     // strip BOLD_OPERATOR
     bool is_bold = (substring(strMessage, 0, 5) == BOLD_OPERATOR);
     if (is_bold)
         strMessage = substring(strMessage, 5, -1);
     // strip trailing newlines
     j = strlen(strMessage) - 1;
     while(substring(strMessage, j, 1) == "\n" && j >= 0)
         --j;
     if (j < strlen(strMessage) - 1)
         strMessage = substring(strMessage, 0, j + 1);
     if(strMessage == "" && new_id == 0)
         return;
     // strip leading newlines
     j = 0;
     while(substring(strMessage, j, 1) == "\n" && j < strlen(strMessage))
         ++j;
     if (j > 0)
         strMessage = substring(strMessage, j, strlen(strMessage) - j);
     if(strMessage == "" && new_id == 0)
         return;
     if (!centerprint_showing)
         centerprint_showing = true;
     for (i=0, j=cpm_index; i<CENTERPRINT_MAX_MSGS; ++i, ++j)
     {
         if (j == CENTERPRINT_MAX_MSGS)
             j = 0;
         if (new_id && new_id == centerprint_msgID[j])
         {
             if (strMessage == "" && centerprint_messages[j] != "" && centerprint_countdown_num[j] == 0)
             {
                 // fade out the current msg (duration and countdown_num are ignored)
                 centerprint_time[j] = min(5, autocvar_hud_panel_centerprint_fade_out);
                 centerprint_expire_time[j] = -1; // don't use the variable time here!
                 return;
             }
             break; // found a msg with the same id, at position j
         }
     }
     if (i == CENTERPRINT_MAX_MSGS)
     {
         // a msg with the same id was not found, add the msg at the next position
         --cpm_index;
         if (cpm_index == -1)
             cpm_index = CENTERPRINT_MAX_MSGS - 1;
         j = cpm_index;
     }
     strcpy(centerprint_messages[j], strMessage);
     centerprint_bold[j] = is_bold;
     centerprint_msgID[j] = new_id;
     if (duration < 0)
     {
         centerprint_time[j] = -1;
         centerprint_expire_time[j] = -1; // don't use the variable time here!
     }
     else
     {
         if(duration == 0)
             duration = max(1, autocvar_hud_panel_centerprint_time);
         centerprint_time[j] = duration;
         centerprint_expire_time[j] = -1; // don't use the variable time here!
     }
     centerprint_countdown_num[j] = countdown_num;
 }
void centerprint_AddStandard (string strMessage)
Definition at line 132 of file centerprint.qc.
References autocvar_hud_panel_centerprint_time, and centerprint_Add().
Referenced by CSQC_Parse_CenterPrint(), HUD_CenterPrint(), and LocalCommand_localprint().
 {
     centerprint_Add(0, strMessage, autocvar_hud_panel_centerprint_time, 0);
 }
void centerprint_Kill (int id)
Definition at line 126 of file centerprint.qc.
References centerprint_Add(), and TC.
Referenced by Announcer_Gamestart(), and Local_Notification_WOVA().
 {
     TC(int, id);
     centerprint_Add(id, "", 0, 0);
 }
void centerprint_KillAll ()
Definition at line 137 of file centerprint.qc.
References centerprint_bold, centerprint_expire_time, CENTERPRINT_MAX_MSGS, centerprint_messages, centerprint_msgID, centerprint_time, and strfree.
Referenced by Destroy_All_Notifications(), HUD_CenterPrint(), and Local_Notification_WOVA().
 {
     for (int i=0; i<CENTERPRINT_MAX_MSGS; ++i)
     {
         centerprint_expire_time[i] = 0;
         centerprint_time[i] = 1;
         centerprint_msgID[i] = 0;
         centerprint_bold[i] = false;
         strfree(centerprint_messages[i]);
     }
 }
void HUD_CenterPrint ()
Definition at line 150 of file centerprint.qc.
References argv(), autocvar__hud_configure, autocvar_hud_panel_centerprint, autocvar_hud_panel_centerprint_align, autocvar_hud_panel_centerprint_dynamichud, autocvar_hud_panel_centerprint_fade_in, autocvar_hud_panel_centerprint_fade_minfontsize, autocvar_hud_panel_centerprint_fade_out, autocvar_hud_panel_centerprint_fade_subsequent, autocvar_hud_panel_centerprint_fade_subsequent_minfontsize, autocvar_hud_panel_centerprint_fade_subsequent_passone, autocvar_hud_panel_centerprint_fade_subsequent_passone_minalpha, autocvar_hud_panel_centerprint_fade_subsequent_passtwo, autocvar_hud_panel_centerprint_fade_subsequent_passtwo_minalpha, autocvar_hud_panel_centerprint_flip, autocvar_hud_panel_centerprint_fontscale, autocvar_hud_panel_centerprint_fontscale_bold, bound(), centerprint_Add(), centerprint_AddStandard(), centerprint_bold, centerprint_countdown_num, centerprint_expire_time, centerprint_KillAll(), CENTERPRINT_MAX_ENTRIES, CENTERPRINT_MAX_MSGS, centerprint_messages, centerprint_msgID, centerprint_showing, CENTERPRINT_SPACING, centerprint_time, count_seconds, cpm_index, draw_beginBoldFont, draw_endBoldFont, drawcolorcodedstring(), DRAWFLAG_NORMAL, drawfontscale, eY, floor(), getWrappedLine(), getWrappedLine_remaining, height, highlightedPanel, hud_configure_cp_generation_time, hud_configure_prev, HUD_PANEL, HUD_Panel_DrawBg, HUD_Panel_LoadCvars(), hud_panel_radar_bottom, HUD_Radar_Clickable(), hud_scale, HUD_Scale_Disable(), HUD_Scale_Enable(), max(), min(), ORDINAL, panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, random(), scoreboard_bottom, scoreboard_fade_alpha, seconds_tostring(), sqrt(), stringwidth, time, tokenizebyseparator, vec2, vector(), vid_conheight, and vid_conwidth.
 {
     if(!autocvar__hud_configure)
     {
         if(!autocvar_hud_panel_centerprint) return;
         if(hud_configure_prev)
             centerprint_KillAll();
     }
     else
     {
         if(!hud_configure_prev)
         {
             centerprint_KillAll();
             hud_configure_cp_generation_time = time; // show a message immediately
         }
         if (time > hud_configure_cp_generation_time)
         {
             if(highlightedPanel == HUD_PANEL(CENTERPRINT))
             {
                 float r;
                 r = random();
                 if (r > 0.8)
                     centerprint_Add(floor(r*1000), sprintf(_("^3Countdown message at time %s, seconds left: ^COUNT"), seconds_tostring(time)), 1, 10);
                 else if (r > 0.55)
                     centerprint_Add(0, sprintf(_("^1Multiline message at time %s that\n^1lasts longer than normal"), seconds_tostring(time)), 20, 0);
                 else
                     centerprint_AddStandard(sprintf(_("Message at time %s"), seconds_tostring(time)));
                 hud_configure_cp_generation_time = time + 1 + random()*4;
             }
             else
             {
                 centerprint_Add(0, _("Generic message"), 10, 0);
                 hud_configure_cp_generation_time = time + 10 - random()*3;
             }
         }
     }
     HUD_Panel_LoadCvars();
     if ( HUD_Radar_Clickable() )
     {
         if (hud_panel_radar_bottom >= 0.96 * vid_conheight)
             return;
         panel_pos.x = 0.5 * (vid_conwidth - panel_size.x);
         panel_pos.y = hud_panel_radar_bottom;
         panel_size.y = min(panel_size.y, vid_conheight - hud_panel_radar_bottom);
     }
     else if(!autocvar__hud_configure && scoreboard_fade_alpha)
     {
         // move the panel below the scoreboard
         if (scoreboard_bottom >= 0.96 * vid_conheight)
             return;
         vector target_pos = vec2(0.5 * (vid_conwidth - panel_size.x), scoreboard_bottom);
         if(target_pos.y > panel_pos.y)
         {
             panel_pos = panel_pos + (target_pos - panel_pos) * sqrt(scoreboard_fade_alpha);
             panel_size.y = min(panel_size.y, vid_conheight - scoreboard_bottom);
         }
     }
     if (autocvar_hud_panel_centerprint_dynamichud)
         HUD_Scale_Enable();
     else
         HUD_Scale_Disable();
     HUD_Panel_DrawBg();
     if (!centerprint_showing)
         return;
     if(panel_bg_padding)
     {
         panel_pos += '1 1 0' * panel_bg_padding;
         panel_size -= '2 2 0' * panel_bg_padding;
     }
     int entries;
     float height;
     vector fontsize;
     int i, j, k, n, g;
     float a, sz, align, current_msg_posY = 0, msg_size;
     vector pos;
     string ts;
     bool all_messages_expired = true;
     pos = panel_pos;
     if (autocvar_hud_panel_centerprint_flip)
         pos.y += panel_size.y;
     align = bound(0, autocvar_hud_panel_centerprint_align, 1);
     for (g=0, i=0, j=cpm_index; i<CENTERPRINT_MAX_MSGS; ++i, ++j)
     {
         bool is_bold = centerprint_bold[j];
         // entries = bound(1, floor(CENTERPRINT_MAX_ENTRIES * 4 * panel_size_y/panel_size_x), CENTERPRINT_MAX_ENTRIES);
         // height = panel_size_y/entries;
         // fontsize = '1 1 0' * height;
         height = (is_bold) ? vid_conheight/50 * autocvar_hud_panel_centerprint_fontscale_bold : vid_conheight/50 * autocvar_hud_panel_centerprint_fontscale;
         fontsize = '1 1 0' * height;
         entries = bound(1, floor(panel_size.y/height), CENTERPRINT_MAX_ENTRIES);
         if (j == CENTERPRINT_MAX_MSGS)
             j = 0;
         if (centerprint_expire_time[j] == -1)
         {
             // here we are sure the time variable is not altered by CSQC_Ent_Update
             centerprint_expire_time[j] = time;
             if (centerprint_time[j] > 0)
                 centerprint_expire_time[j] += centerprint_time[j];
         }
         if (centerprint_expire_time[j] <= time)
         {
             if (centerprint_countdown_num[j] && centerprint_time[j] > 0)
             {
                 centerprint_countdown_num[j] = centerprint_countdown_num[j] - 1;
                 if (centerprint_countdown_num[j] == 0)
                     continue;
                 centerprint_expire_time[j] = centerprint_expire_time[j] + centerprint_time[j];
             }
             else if(centerprint_time[j] != -1)
                 continue;
         }
         all_messages_expired = false;
         // fade
         if(centerprint_time[j] < 0)  // Expired but forced. Expire time is the fade-in time.
             a = (time - centerprint_expire_time[j]) / max(0.0001, autocvar_hud_panel_centerprint_fade_in);
         else if(centerprint_expire_time[j] - autocvar_hud_panel_centerprint_fade_out > time)  // Regularily printed. Not fading out yet.
             a = (time - (centerprint_expire_time[j] - centerprint_time[j])) / max(0.0001, autocvar_hud_panel_centerprint_fade_in);
         else // Expiring soon, so fade it out.
             a = (centerprint_expire_time[j] - time) / max(0.0001, autocvar_hud_panel_centerprint_fade_out);
         if(centerprint_msgID[j] == ORDINAL(CPID_TIMEIN))
             a = 1;
         // while counting down show it anyway in order to hold the current message position
         if (a <= 0.5/255.0 && centerprint_countdown_num[j] == 0)  // Guaranteed invisible - don't show.
             continue;
         if (a > 1)
             a = 1;
         // set the size from fading in/out before subsequent fading
         sz = autocvar_hud_panel_centerprint_fade_minfontsize + a * (1 - autocvar_hud_panel_centerprint_fade_minfontsize);
         // also fade it based on positioning
         if(autocvar_hud_panel_centerprint_fade_subsequent)
         {
             // pass one: all messages after the first have half alpha
             a = a * bound(autocvar_hud_panel_centerprint_fade_subsequent_passone_minalpha, (1 - (g / max(1, autocvar_hud_panel_centerprint_fade_subsequent_passone))), 1);
             // pass two: after that, gradually lower alpha even more for each message
             a = a * bound(autocvar_hud_panel_centerprint_fade_subsequent_passtwo_minalpha, (1 - (g / max(1, autocvar_hud_panel_centerprint_fade_subsequent_passtwo))), 1);
         }
         a *= panel_fg_alpha;
         // finally set the size based on the new alpha from subsequent fading
         sz = sz * (autocvar_hud_panel_centerprint_fade_subsequent_minfontsize + a * (1 - autocvar_hud_panel_centerprint_fade_subsequent_minfontsize));
         drawfontscale = hud_scale * sz;
         if (centerprint_countdown_num[j])
             n = tokenizebyseparator(strreplace("^COUNT", count_seconds(centerprint_countdown_num[j]), centerprint_messages[j]), "\n");
         else
             n = tokenizebyseparator(centerprint_messages[j], "\n");
         if (autocvar_hud_panel_centerprint_flip)
         {
             // check if the message can be entirely shown
             for(k = 0; k < n; ++k)
             {
                 getWrappedLine_remaining = argv(k);
                 while(getWrappedLine_remaining)
                 {
                     ts = getWrappedLine(panel_size.x * hud_scale.x * sz, fontsize, stringwidth_colors);
                     if (ts != "")
                         pos.y -= fontsize.y;
                     else
                         pos.y -= fontsize.y * CENTERPRINT_SPACING/2;
                 }
             }
             current_msg_posY = pos.y; // save starting pos (first line) of the current message
         }
         msg_size = pos.y;
         for(k = 0; k < n; ++k)
         {
             getWrappedLine_remaining = argv(k);
             while(getWrappedLine_remaining)
             {
                 ts = getWrappedLine(panel_size.x * hud_scale.x * sz, fontsize, stringwidth_colors);
                 if (ts != "")
                 {
                     if (align)
                         pos.x = panel_pos.x + (panel_size.x - stringwidth(ts, true, fontsize) * sz) * align;
                     if (a > 0.5/255.0)  // Otherwise guaranteed invisible - don't show. This is checked a second time after some multiplications with other factors were done so temporary changes of these cannot cause flicker.
                         if (is_bold) draw_beginBoldFont();
                         drawcolorcodedstring(pos + eY * 0.5 * (1 - sz * hud_scale.x) * fontsize.y, ts, fontsize, a, DRAWFLAG_NORMAL);
                         if (is_bold) draw_endBoldFont();
                     pos.y += fontsize.y;
                 }
                 else
                     pos.y += fontsize.y * CENTERPRINT_SPACING/2;
             }
         }
         ++g; // move next position number up
         msg_size = pos.y - msg_size;
         if (autocvar_hud_panel_centerprint_flip)
         {
             pos.y = current_msg_posY - CENTERPRINT_SPACING * fontsize.y;
             if (a < 1 && centerprint_msgID[j] == 0) // messages with id can be replaced just after they are faded out, so never move over them the next messages
                 pos.y += (msg_size + CENTERPRINT_SPACING * fontsize.y) * (1 - sqrt(sz));
             if (pos.y < panel_pos.y) // check if the next message can be shown
             {
                 drawfontscale = hud_scale;
                 return;
             }
         }
         else
         {
             pos.y += CENTERPRINT_SPACING * fontsize.y;
             if (a < 1 && centerprint_msgID[j] == 0) // messages with id can be replaced just after they are faded out, so never move over them the next messages
                 pos.y -= (msg_size + CENTERPRINT_SPACING * fontsize.y) * (1 - sqrt(sz));
             if(pos.y > panel_pos.y + panel_size.y - fontsize.y) // check if the next message can be shown
             {
                 drawfontscale = hud_scale;
                 return;
             }
         }
     }
     drawfontscale = hud_scale;
     if (all_messages_expired)
     {
         centerprint_showing = false;
         centerprint_KillAll();
     }
 }
void HUD_CenterPrint_Export (int fh)
Definition at line 9 of file centerprint.qc.
References HUD_Write_Cvar.
 {
     // allow saving cvars that aesthetically change the panel into hud skin files
     HUD_Write_Cvar("hud_panel_centerprint_align");
     HUD_Write_Cvar("hud_panel_centerprint_flip");
     HUD_Write_Cvar("hud_panel_centerprint_fontscale");
     HUD_Write_Cvar("hud_panel_centerprint_fontscale_bold");
     HUD_Write_Cvar("hud_panel_centerprint_time");
     HUD_Write_Cvar("hud_panel_centerprint_fade_in");
     HUD_Write_Cvar("hud_panel_centerprint_fade_out");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passone");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passone_minalpha");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passtwo");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passtwo_minalpha");
     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_minfontsize");
     HUD_Write_Cvar("hud_panel_centerprint_fade_minfontsize");
 }
Variable Documentation
bool centerprint_bold[CENTERPRINT_MAX_MSGS]
Definition at line 40 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
int centerprint_countdown_num[CENTERPRINT_MAX_MSGS]
Definition at line 43 of file centerprint.qc.
Referenced by centerprint_Add(), and HUD_CenterPrint().
float centerprint_expire_time[CENTERPRINT_MAX_MSGS]
Definition at line 42 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
const int CENTERPRINT_MAX_ENTRIES = 50
Definition at line 35 of file centerprint.qc.
Referenced by HUD_CenterPrint().
const int CENTERPRINT_MAX_MSGS = 10
Definition at line 34 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
string centerprint_messages[CENTERPRINT_MAX_MSGS]
Definition at line 38 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
int centerprint_msgID[CENTERPRINT_MAX_MSGS]
Definition at line 39 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
bool centerprint_showing
Definition at line 44 of file centerprint.qc.
Referenced by centerprint_Add(), and HUD_CenterPrint().
const float CENTERPRINT_SPACING = 0.7
Definition at line 36 of file centerprint.qc.
Referenced by HUD_CenterPrint().
float centerprint_time[CENTERPRINT_MAX_MSGS]
Definition at line 41 of file centerprint.qc.
Referenced by centerprint_Add(), centerprint_KillAll(), and HUD_CenterPrint().
int cpm_index
Definition at line 37 of file centerprint.qc.
Referenced by centerprint_Add(), and HUD_CenterPrint().
float hud_configure_cp_generation_time
Definition at line 149 of file centerprint.qc.
Referenced by HUD_CenterPrint().