Xonotic: server/mutators/all.qc File Reference
all.qc File Reference
#include "all.qh"
#include "all.inc"
Macros
#define IMPLEMENTATION
Functions
STATIC_INIT_LATE (Gametype)
Macro Definition Documentation
#define IMPLEMENTATION
Definition at line 85 of file all.qc.
Function Documentation
STATIC_INIT_LATE (Gametype)
Definition at line 75 of file all.qc.
References car(), cdr(), FOREACH, LAMBDA, MapInfo_CurrentGametype(), MapInfo_Type(), Mutator_Add(), and s.
{
     Gametype g = MapInfo_Type(MapInfo_CurrentGametype());
     if (g) {
         for (string _s = g.m_mutators; _s != ""; _s = cdr(_s)) {
             string s = car(_s);
             FOREACH(Mutators, it.m_name == s, LAMBDA(Mutator_Add(it); break));
         }
     }
 }