Xonotic: lib/csqcmodel/sv_model.qc File Reference
lib/csqcmodel/sv_model.qc File Reference
#include "sv_model.qh"
#include "common.qh"
#include <common/animdecide.qh>
#include <common/constants.qh>
#include <common/util.qh>
#include <server/constants.qh>
#include <server/defs.qh>
Defines
#define CSQCMODEL_IF(cond) if(cond) {
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_PROPERTY(flag, t, r, w, f)
#define CSQCMODEL_PROPERTY_SCALED(flag, t, r, w, f, s, mi, ma) CSQCMODEL_PROPERTY(flag,t,r,w,f)
#define CSQCMODEL_IF(cond) if(cond) {
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_PROPERTY(flag, t, r, w, f)
#define CSQCMODEL_PROPERTY_SCALED(flag, t, r, w, f, s, mi, ma)
Functions
bool CSQCModel_Send (entity to, int sf)
void CSQCModel_CheckUpdate (entity e)
void CSQCModel_LinkEntity (entity e)
void CSQCModel_UnlinkEntity (entity e)
Define Documentation
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_IF (cond) if(cond) {
#define CSQCMODEL_IF (cond) if(cond) {
#define CSQCMODEL_PROPERTY (flag, t, r, w, f)
Value:
if(sf & flag) \
    { \
        w(MSG_ENTITY, self.csqcmodel_##f); \
    }
#define CSQCMODEL_PROPERTY (flag, t, r, w, f)
Value:
{ \
        t tmp = e.f; \
        if(tmp != e.csqcmodel_##f) \
        { \
            e.csqcmodel_##f = tmp; \
            e.SendFlags |= flag; \
        } \
    }
#define CSQCMODEL_PROPERTY_SCALED (flag, t, r, w, f, s, mi, ma) CSQCMODEL_PROPERTY(flag,t,r,w,f)
#define CSQCMODEL_PROPERTY_SCALED (flag, t, r, w, f, s, mi, ma)
Value:
{ \
        t tmp = rint(bound(mi, s * e.f, ma) - mi); \
        if(tmp != e.csqcmodel_##f) \
        { \
            e.csqcmodel_##f = tmp; \
            e.SendFlags |= flag; \
        } \
    }
Function Documentation
void CSQCModel_CheckUpdate (entity e)
Definition at line 67 of file sv_model.qc.
References ALLPROPERTIES, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_ORIGIN, CSQCMODEL_PROPERTY_TELEPORTED, CSQCPLAYER_FORCE_UPDATES, EF_RESTARTANIM_BIT, EF_TELEPORT_BIT, IS_CLIENT, random(), time, and unused_float.
Referenced by CSQCModel_LinkEntity().
{
    // some nice flags for CSQCMODEL_IF
    float isplayer = (IS_CLIENT(e));
    float islocalplayer = isplayer; // we set BOTH to 1 here as we need the sendflags
    float isnolocalplayer = isplayer; // we set BOTH to 1 here as we need the sendflags
    unused_float = isplayer;
    unused_float = islocalplayer;
    unused_float = isnolocalplayer;
#if CSQCPLAYER_FORCE_UPDATES
    if(isplayer && time > e.csqcmodel_nextforcedupdate)
    {
        e.SendFlags |= CSQCMODEL_PROPERTY_ORIGIN;
        e.csqcmodel_nextforcedupdate = time + (1 / (CSQCPLAYER_FORCE_UPDATES)) * (0.5 + random()); // ensure about 4 origin sends per sec
    }
#endif
    if(e.effects & EF_RESTARTANIM_BIT)
    {
        e.SendFlags |= CSQCMODEL_PROPERTY_FRAME | CSQCMODEL_PROPERTY_FRAME2; // full anim resend please
        e.effects &= ~EF_RESTARTANIM_BIT;
    }
    if(e.effects & EF_TELEPORT_BIT)
    {
        e.SendFlags |= CSQCMODEL_PROPERTY_TELEPORTED; // no interpolation please
        e.effects &= ~EF_TELEPORT_BIT;
    }
#define CSQCMODEL_IF(cond) if(cond) {
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_PROPERTY(flag,t,r,w,f) \
    { \
        t tmp = e.f; \
        if(tmp != e.csqcmodel_##f) \
        { \
            e.csqcmodel_##f = tmp; \
            e.SendFlags |= flag; \
        } \
    }
#define CSQCMODEL_PROPERTY_SCALED(flag,t,r,w,f,s,mi,ma) \
    { \
        t tmp = rint(bound(mi, s * e.f, ma) - mi); \
        if(tmp != e.csqcmodel_##f) \
        { \
            e.csqcmodel_##f = tmp; \
            e.SendFlags |= flag; \
        } \
    }
    ALLPROPERTIES
#undef CSQCMODEL_PROPERTY_SCALED
#undef CSQCMODEL_PROPERTY
#undef CSQCMODEL_ENDIF
#undef CSQCMODEL_IF
}
void CSQCModel_LinkEntity (entity e)
Definition at line 125 of file sv_model.qc.
References CSQCModel_CheckUpdate(), and CSQCModel_Send().
{
    e.SendEntity = CSQCModel_Send;
    e.SendFlags = 0xFFFFFF;
    CSQCModel_CheckUpdate(e);
}
bool CSQCModel_Send (entity to, int sf)
Definition at line 33 of file sv_model.qc.
References ALLPROPERTIES, IS_CLIENT, unused_float, and WriteInt24_t().
Referenced by CSQCModel_LinkEntity().
{
    // some nice flags for CSQCMODEL_IF
    float isplayer = (IS_CLIENT(self));
    float islocalplayer = (self == to);
    float isnolocalplayer = (isplayer && (self != to));
    unused_float = isplayer;
    unused_float = islocalplayer;
    unused_float = isnolocalplayer;
    WriteHeader(MSG_ENTITY, ENT_CLIENT_MODEL);
    WriteInt24_t(MSG_ENTITY, sf);
#define CSQCMODEL_IF(cond) if(cond) {
#define CSQCMODEL_ENDIF }
#define CSQCMODEL_PROPERTY(flag,t,r,w,f) \
    if(sf & flag) \
    { \
        w(MSG_ENTITY, self.csqcmodel_##f); \
    }
#define CSQCMODEL_PROPERTY_SCALED(flag,t,r,w,f,s,mi,ma) CSQCMODEL_PROPERTY(flag,t,r,w,f)
    ALLPROPERTIES
#undef CSQCMODEL_PROPERTY_SCALED
#undef CSQCMODEL_PROPERTY
#undef CSQCMODEL_ENDIF
#undef CSQCMODEL_IF
    return true;
}
void CSQCModel_UnlinkEntity (entity e)
Definition at line 132 of file sv_model.qc.
References func_null().
Referenced by Monster_Dead(), and vehicles_enter().
{
    e.SendEntity = func_null;
}