Xonotic: menu/xonotic/demolist.qc File Reference
demolist.qc File Reference
#include "demolist.qh"
#include "inputbox.qh"
Functions
void DemoConfirm_ListClick_Check_Gamestatus (entity me)
void DemoList_Filter_Change (entity box, entity me)
void DemoList_Refresh_Click (entity btn, entity me)
void getDemos_for_ext (entity me, string ext, float subdir)
entity makeXonoticDemoList ()
void XonoticDemoList_configureXonoticDemoList (entity me)
string XonoticDemoList_demoName (entity me, float i)
void XonoticDemoList_destroy (entity me)
void XonoticDemoList_doubleClickListBoxItem (entity me, float i, vector where)
void XonoticDemoList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
void XonoticDemoList_getDemos (entity me)
float XonoticDemoList_keyDown (entity me, float scan, float ascii, float shift)
void XonoticDemoList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticDemoList_showNotify (entity me)
void XonoticDemoList_startDemo (entity me)
void XonoticDemoList_timeDemo (entity me)
Function Documentation
void DemoConfirm_ListClick_Check_Gamestatus (entity me)
Definition at line 166 of file demolist.qc.
References boxToGlobal(), boxToGlobalSize(), DialogOpenButton_Click_withCoords(), eX, eY, GAME_CONNECTED, GAME_ISSERVER, gamestatus, and main.
Referenced by XonoticDemoList_doubleClickListBoxItem(), and XonoticDemoList_keyDown().
 {
     if(!(gamestatus & (GAME_CONNECTED | GAME_ISSERVER))) // we're not in a match, lets watch the demo
     {
         me.startDemo(me);
     }
     else // already in a match, player has to confirm
     {
         DialogOpenButton_Click_withCoords(
             me,
             main.demostartconfirmDialog,
             boxToGlobal(eY * (me.selectedItem * me.itemHeight - me.scrollPos), me.origin, me.size),
             boxToGlobalSize(eY * me.itemHeight + eX * (1 - me.controlWidth), me.size)
         );
     }
 }
void DemoList_Filter_Change (entity box, entity me)
Definition at line 130 of file demolist.qc.
References strcat(), string_null, strstrofs, strunzone(), and strzone().
Referenced by XonoticDemoBrowserTab_fill().
 {
     if(me.filterString)
         strunzone(me.filterString);
     if(box.text != "")
     {
         if (strstrofs(box.text, "*", 0) >= 0 || strstrofs(box.text, "?", 0) >= 0)
             me.filterString = strzone(box.text);
         else
             me.filterString = strzone(strcat("*", box.text, "*"));
     }
     else
         me.filterString = string_null;
     me.getDemos(me);
 }
void DemoList_Refresh_Click (entity btn, entity me)
Definition at line 124 of file demolist.qc.
Referenced by XonoticDemoBrowserTab_fill().
 {
     me.getDemos(me);
     me.setSelected(me, 0); //always select the first element after a list update
 }
void getDemos_for_ext (entity me, string ext, float subdir)
Definition at line 31 of file demolist.qc.
References rgb_to_hexcolor(), search_begin(), search_end(), search_getfilename(), search_getsize(), strcat(), strlen(), and substring().
Referenced by XonoticDemoList_getDemos().
 {
     string s;
     if (subdir)
         s="demos/*/";
     else
         s="demos/";
     if(me.filterString)
         s=strcat(s, me.filterString, ext);
     else
         s=strcat(s, "*", ext);
     float list, i, n;
     list = search_begin(s, false, true);
     if(list >= 0)
     {
         n = search_getsize(list);
         for(i = 0; i < n; ++i)
         {
             s = search_getfilename(list, i); // get initial full file name
             s = substring(s, 6, (strlen(s) - 6 - 4)); // remove "demos/" prefix and ".dem" suffix
             s = strdecolorize(s); // remove any pre-existing colors
             if(subdir)
             {
                 s = strreplace("/", "^7/", s); // clear colors at the forward slash
                 s = strcat("/", rgb_to_hexcolor(SKINCOLOR_DEMOLIST_SUBDIR), s); // add a forward slash for sorting, then color
                 bufstr_add(me.listDemo, s, true);
             }
             else { bufstr_add(me.listDemo, s, true); }
         }
         search_end(list);
     }
     if (subdir)
         getDemos_for_ext(me, ext, false);
 }
entity makeXonoticDemoList ()
Definition at line 5 of file demolist.qc.
References entity(), and NEW.
Referenced by XonoticDemoBrowserTab_fill().
 {
     entity me;
     me = NEW(XonoticDemoList);
     me.configureXonoticDemoList(me);
     return me;
 }
void XonoticDemoList_configureXonoticDemoList (entity me)
Definition at line 13 of file demolist.qc.
 {
     me.configureXonoticListBox(me);
     me.nItems = 0;
 }
string XonoticDemoList_demoName (entity me, float i)
Definition at line 19 of file demolist.qc.
References strlen(), and substring().
 {
     string s;
     s = bufstr_get(me.listDemo, i);
     if(substring(s, 0, 1) == "/")
         s = substring(s, 1, strlen(s) - 1);  // remove the first forward slash
     return s;
 }
void XonoticDemoList_destroy (entity me)
Definition at line 84 of file demolist.qc.
 {
     if(me.nItems > 0)
         buf_del(me.listDemo);
 }
void XonoticDemoList_doubleClickListBoxItem (entity me, float i, vector where)
Definition at line 183 of file demolist.qc.
References DemoConfirm_ListClick_Check_Gamestatus().
 {
     DemoConfirm_ListClick_Check_Gamestatus(me);
 }
void XonoticDemoList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 103 of file demolist.qc.
References draw_Fill(), draw_Text(), draw_TextShortenToWidth(), draw_TextWidth(), eX, eY, and getFadedAlpha().
 {
     string s;
     if(isSelected)
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     else if(isFocused)
     {
         me.focusedItemAlpha = getFadedAlpha(me.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, me.focusedItemAlpha);
     }
     s = me.demoName(me,i);
     s = draw_TextShortenToWidth(s, me.columnNameSize, 0, me.realFontSize);
     draw_Text(me.realUpperMargin * eY + (me.columnNameOrigin + 0.00 * (me.columnNameSize - draw_TextWidth(s, 0, me.realFontSize))) * eX, s, me.realFontSize, SKINCOLOR_TEXT, SKINALPHA_TEXT, 1);
 }
void XonoticDemoList_getDemos (entity me)
Definition at line 68 of file demolist.qc.
References buf_create, and getDemos_for_ext().
 {
     if (me.listDemo >= 0)
         buf_del(me.listDemo);
     me.listDemo = buf_create();
     if (me.listDemo < 0)
     {
         me.nItems = 0;
         return;
     }
     getDemos_for_ext(me, ".dem", true);
     me.nItems = buf_getsize(me.listDemo);
     if(me.nItems > 0)
         buf_sort(me.listDemo, 128, false);
 }
float XonoticDemoList_keyDown (entity me, float scan, float ascii, float shift)
Definition at line 188 of file demolist.qc.
References DemoConfirm_ListClick_Check_Gamestatus(), K_ENTER, K_KP_ENTER, and SUPER.
 {
     if(scan == K_ENTER || scan == K_KP_ENTER)
     {
         DemoConfirm_ListClick_Check_Gamestatus(me);
         return 1;
     }
     else
     {
         return SUPER(XonoticDemoList).keyDown(me, scan, ascii, shift);
     }
 }
void XonoticDemoList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 90 of file demolist.qc.
References SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticDemoList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.realFontSize_y = me.fontSize / (me.itemAbsSize_y = (absSize.y * me.itemHeight));
     me.realFontSize_x = me.fontSize / (me.itemAbsSize_x = (absSize.x * (1 - me.controlWidth)));
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
     me.columnNameOrigin = me.realFontSize.x;
     me.columnNameSize = 1 - 2 * me.realFontSize.x;
 }
void XonoticDemoList_showNotify (entity me)
Definition at line 119 of file demolist.qc.
 {
     me.getDemos(me);
 }
void XonoticDemoList_startDemo (entity me)
Definition at line 148 of file demolist.qc.
References localcmd.
 {
     string s;
     s = me.demoName(me, me.selectedItem);
     s = strdecolorize(s);
     localcmd("playdemo \"demos/", s, ".dem\" \nwait \ntogglemenu\n");
 }
void XonoticDemoList_timeDemo (entity me)
Definition at line 157 of file demolist.qc.
References localcmd.
 {
     string s;
     s = me.demoName(me, me.selectedItem);
     s = strdecolorize(s);
     localcmd("timedemo \"demos/", s, ".dem\" \nwait \ntogglemenu\n");
 }