Xonotic: server/world.qh File Reference
world.qh File Reference
Functions
void CheckRules_World ()
void DumpStats (float final)
void ReadyRestart ()
float RedirectionThink ()
void SetWinners (.float field, float value)
STATIC_INIT (g_moveables)
float WinningCondition_Scores (float limit, float leadlimit)
Variables
string cache_lastmutatormsg
string cache_mutatormsg
float checkrules_equality
float checkrules_overtimesadded
float checkrules_suddendeathend
float checkrules_suddendeathwarning
string clientstuff
string cvar_changes
string cvar_purechanges
float cvar_purechanges_count
float default_player_alpha
float default_weapon_alpha
string fog
IntrusiveList g_moveables
string gamemode_name
string matchid
string modname
string redirection_target
bool server_is_dedicated
float ServerProgsDB
float TemporaryDB
float winning
const int WINNING_NEVER = 2
const int WINNING_NO = 0
const int WINNING_STARTSUDDENDEATHOVERTIME = 3
const int WINNING_YES = 1
Function Documentation
void CheckRules_World ()
Definition at line 1438 of file world.qc.
References autocvar_fraglimit, autocvar_timelimit, bprint(), checkrules_overtimesadded, checkrules_suddendeathend, checkrules_suddendeathwarning, CheckRules_World(), ClearWinners(), FOREACH_CLIENT, g_race, g_race_qualifying, GameRules_scoring_add, InitiateOvertime(), InitiateSuddenDeath(), intermission_running, IS_PLAYER, M_ARGV, MapVote_Start(), MapVote_Think(), MUTATOR_CALLHOOK, NextLevel(), NULL, player_count, ReadyRestart(), SetDefaultAlpha(), time, VoteThink(), warmup_stage, WINNING_NEVER, WINNING_STARTSUDDENDEATHOVERTIME, WINNING_YES, WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
Referenced by CheckRules_World(), and StartFrame().
 {
     VoteThink();
     MapVote_Think();
     SetDefaultAlpha();
     if (intermission_running) // someone else quit the game already
     {
         if(player_count == 0) // Nobody there? Then let's go to the next map
             MapVote_Start();
             // this will actually check the player count in the next frame
             // again, but this shouldn't hurt
         return;
     }
     float timelimit = autocvar_timelimit * 60;
     float fraglimit = autocvar_fraglimit;
     float leadlimit = autocvar_leadlimit;
     if (leadlimit < 0) leadlimit = 0;
     if(warmup_stage || time <= game_starttime) // NOTE: this is <= to prevent problems in the very tic where the game starts
     {
         if(timelimit > 0)
             timelimit = 0; // timelimit is not made for warmup
         if(fraglimit > 0)
             fraglimit = 0; // no fraglimit for now
         leadlimit = 0; // no leadlimit for now
     }
     if(timelimit > 0)
     {
         timelimit += game_starttime;
     }
     else if (timelimit < 0)
     {
         // endmatch
         NextLevel();
         return;
     }
     float wantovertime;
     wantovertime = 0;
     if(checkrules_suddendeathend)
     {
         if(!checkrules_suddendeathwarning)
         {
             checkrules_suddendeathwarning = true;
             if(g_race && !g_race_qualifying)
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_RACE_FINISHLAP);
             else
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_OVERTIME_FRAG);
         }
     }
     else
     {
         if (timelimit && time >= timelimit)
         {
             if(g_race && (g_race_qualifying == 2) && timelimit > 0)
             {
                 float totalplayers;
                 float playerswithlaps;
                 float readyplayers;
                 totalplayers = playerswithlaps = readyplayers = 0;
                 FOREACH_CLIENT(IS_PLAYER(it), {
                     ++totalplayers;
                     if(GameRules_scoring_add(it, RACE_FASTEST, 0))
                         ++playerswithlaps;
                     if(it.ready)
                         ++readyplayers;
                 });
                 // at least 2 of the players have completed a lap: start the RACE
                 // otherwise, the players should end the qualifying on their own
                 if(readyplayers || playerswithlaps >= 2)
                 {
                     checkrules_suddendeathend = 0;
                     ReadyRestart(); // go to race
                     return;
                 }
                 else
                     wantovertime |= InitiateSuddenDeath();
             }
             else
                 wantovertime |= InitiateSuddenDeath();
         }
     }
     if (checkrules_suddendeathend && time >= checkrules_suddendeathend)
     {
         NextLevel();
         return;
     }
     int checkrules_status = WinningCondition_RanOutOfSpawns();
     if(checkrules_status == WINNING_YES)
         bprint("Hey! Someone ran out of spawns!\n");
     else if(MUTATOR_CALLHOOK(CheckRules_World, checkrules_status, timelimit, fraglimit))
         checkrules_status = M_ARGV(0, float);
     else
         checkrules_status = WinningCondition_Scores(fraglimit, leadlimit);
     if(checkrules_status == WINNING_STARTSUDDENDEATHOVERTIME)
     {
         checkrules_status = WINNING_NEVER;
         checkrules_overtimesadded = -1;
         wantovertime |= InitiateSuddenDeath();
     }
     if(checkrules_status == WINNING_NEVER)
         // equality cases! Nobody wins if the overtime ends in a draw.
         ClearWinners();
     if(wantovertime)
     {
         if(checkrules_status == WINNING_NEVER)
             InitiateOvertime();
         else
             checkrules_status = WINNING_YES;
     }
     if(checkrules_suddendeathend)
         if(checkrules_status != WINNING_NEVER || time >= checkrules_suddendeathend)
             checkrules_status = WINNING_YES;
     if(checkrules_status == WINNING_YES)
     {
         //print("WINNING\n");
         NextLevel();
     }
 }
void DumpStats (float final)
Definition at line 1030 of file world.qc.
References autocvar_sv_eventlog, autocvar_sv_eventlog_console, autocvar_sv_logscores_bots, autocvar_sv_logscores_console, autocvar_sv_logscores_file, autocvar_sv_logscores_filename, CS(), fclose(), FILE_APPEND, fopen(), FOREACH_CLIENT, fputs(), ftos(), GameLogEcho(), GetGametype(), GetMapname(), GetPlayerScoreString(), GetTeamScoreString(), IS_BOT_CLIENT, IS_PLAYER, IS_REAL_CLIENT, jointime, LOG_INFO, MUTATOR_CALLHOOK, NULL, playername(), rint(), strcat(), teamplay, and time.
Referenced by GameCommand_printstats(), and NextLevel().
 {
     float file;
     string s;
     float to_console;
     float to_eventlog;
     float to_file;
     float i;
     to_console = autocvar_sv_logscores_console;
     to_eventlog = autocvar_sv_eventlog;
     to_file = autocvar_sv_logscores_file;
     if(!final)
     {
         to_console = true; // always print printstats replies
         to_eventlog = false; // but never print them to the event log
     }
     if(to_eventlog)
         if(autocvar_sv_eventlog_console)
             to_console = false; // otherwise we get the output twice
     if(final)
         s = ":scores:";
     else
         s = ":status:";
     s = strcat(s, GetGametype(), "_", GetMapname(), ":", ftos(rint(time)));
     if(to_console)
         LOG_INFO(s);
     if(to_eventlog)
         GameLogEcho(s);
     file = -1;
     if(to_file)
     {
         file = fopen(autocvar_sv_logscores_filename, FILE_APPEND);
         if(file == -1)
             to_file = false;
         else
             fputs(file, strcat(s, "\n"));
     }
     s = strcat(":labels:player:", GetPlayerScoreString(NULL, 0));
     if(to_console)
         LOG_INFO(s);
     if(to_eventlog)
         GameLogEcho(s);
     if(to_file)
         fputs(file, strcat(s, "\n"));
     FOREACH_CLIENT(IS_REAL_CLIENT(it) || (IS_BOT_CLIENT(it) && autocvar_sv_logscores_bots), {
         s = strcat(":player:see-labels:", GetPlayerScoreString(it, 0), ":");
         s = strcat(s, ftos(rint(time - CS(it).jointime)), ":");
         if(IS_PLAYER(it) || MUTATOR_CALLHOOK(GetPlayerStatus, it))
             s = strcat(s, ftos(it.team), ":");
         else
             s = strcat(s, "spectator:");
         if(to_console)
             LOG_INFO(s, playername(it, false));
         if(to_eventlog)
             GameLogEcho(strcat(s, ftos(it.playerid), ":", playername(it, false)));
         if(to_file)
             fputs(file, strcat(s, playername(it, false), "\n"));
     });
     if(teamplay)
     {
         s = strcat(":labels:teamscores:", GetTeamScoreString(0, 0));
         if(to_console)
             LOG_INFO(s);
         if(to_eventlog)
             GameLogEcho(s);
         if(to_file)
             fputs(file, strcat(s, "\n"));
         for(i = 1; i < 16; ++i)
         {
             s = strcat(":teamscores:see-labels:", GetTeamScoreString(i, 0));
             s = strcat(s, ":", ftos(i));
             if(to_console)
                 LOG_INFO(s);
             if(to_eventlog)
                 GameLogEcho(s);
             if(to_file)
                 fputs(file, strcat(s, "\n"));
         }
     }
     if(to_console)
         LOG_INFO(":end");
     if(to_eventlog)
         GameLogEcho(":end");
     if(to_file)
     {
         fputs(file, ":end\n");
         fclose(file);
     }
 }
void ReadyRestart ()
Definition at line 481 of file vote.qc.
References intermission_running, localcmd, MUTATOR_CALLHOOK, race_completing, ReadyRestart_force(), Score_ClearAll(), and sv_ready_restart_after_countdown.
Referenced by CheckRules_World(), GameCommand_allready(), ReadyCount(), and StartFrame().
 {
     if (MUTATOR_CALLHOOK(ReadyRestart_Deny) || intermission_running || race_completing) localcmd("restart\n");
     else localcmd("\nsv_hook_readyrestart\n");
     // Reset ALL scores, but only do that at the beginning of the countdown if sv_ready_restart_after_countdown is off!
     // Otherwise scores could be manipulated during the countdown.
     if (!sv_ready_restart_after_countdown) Score_ClearAll();
     ReadyRestart_force();
 }
float RedirectionThink ()
Definition at line 1690 of file world.qc.
References autocvar_quit_and_redirect_timer, bprint(), cvar_set(), FOREACH_CLIENT, ftos(), IS_REAL_CLIENT, localcmd, LOG_INFO, redirection_nextthink, redirection_target, redirection_timeout, strcat(), stuffcmd, and time.
Referenced by StartFrame().
 {
     float clients_found;
     if(redirection_target == "")
         return false;
     if(!redirection_timeout)
     {
         cvar_set("sv_public", "-2");
         redirection_timeout = time + 0.6; // this will only try twice... should be able to keep more clients
         if(redirection_target == "self")
             bprint("^3SERVER NOTICE:^7 restarting the server\n");
         else
             bprint("^3SERVER NOTICE:^7 redirecting everyone to ", redirection_target, "\n");
     }
     if(time < redirection_nextthink)
         return true;
     redirection_nextthink = time + 1;
     clients_found = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         // TODO add timer
         LOG_INFO("Redirecting: sending connect command to ", it.netname);
         if(redirection_target == "self")
             stuffcmd(it, "\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " reconnect\n");
         else
             stuffcmd(it, strcat("\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " \"connect ", redirection_target, "\"\n"));
         ++clients_found;
     });
     LOG_INFO("Redirecting: ", ftos(clients_found), " clients left.");
     if(time > redirection_timeout || clients_found == 0)
         localcmd("\nwait; wait; wait; quit\n");
     return true;
 }
void SetWinners (.float field, float value)
Definition at line 1252 of file world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), { it.winning = (it.(field) == value); });
 }
STATIC_INIT (g_moveables)
Definition at line 52 of file world.qh.
References IL_NEW.
 { g_moveables = IL_NEW(); }
float WinningCondition_Scores (float limit, float leadlimit)
Definition at line 1273 of file world.qc.
References autocvar_leadlimit_and_fraglimit, checkrules_suddendeathend, ClearWinners(), FLOAT_MAX, fragsleft_last, GetWinningCode(), max(), min(), MUTATOR_CALLHOOK, NULL, SetWinners(), team, Team_GetTeamFromIndex(), Team_IndexToTeam(), Team_SetTeamScore(), teamplay, TeamScore_GetCompareValue(), time, WinningConditionHelper(), WinningConditionHelper_equality, WinningConditionHelper_lowerisbetter, WinningConditionHelper_secondscore, WinningConditionHelper_topscore, WinningConditionHelper_winner, WinningConditionHelper_winnerteam, and WinningConditionHelper_zeroisworst.
Referenced by CheckRules_World(), WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
 {
     // TODO make everything use THIS winning condition (except LMS)
     WinningConditionHelper(NULL);
     if(teamplay)
     {
         for (int i = 1; i < 5; ++i)
         {
             Team_SetTeamScore(Team_GetTeamFromIndex(i),
                 TeamScore_GetCompareValue(Team_IndexToTeam(i)));
         }
     }
     ClearWinners();
     if(WinningConditionHelper_winner)
         WinningConditionHelper_winner.winning = 1;
     if(WinningConditionHelper_winnerteam >= 0)
         SetWinners(team, WinningConditionHelper_winnerteam);
     if(WinningConditionHelper_lowerisbetter)
     {
         WinningConditionHelper_topscore = -WinningConditionHelper_topscore;
         WinningConditionHelper_secondscore = -WinningConditionHelper_secondscore;
         limit = -limit;
     }
     if(WinningConditionHelper_zeroisworst)
         leadlimit = 0; // not supported in this mode
     if(MUTATOR_CALLHOOK(Scores_CountFragsRemaining))
     {
         float fragsleft;
         if (checkrules_suddendeathend && time >= checkrules_suddendeathend)
         {
             fragsleft = 1;
         }
         else
         {
             fragsleft = FLOAT_MAX;
             float leadingfragsleft = FLOAT_MAX;
             if (limit)
                 fragsleft = limit - WinningConditionHelper_topscore;
             if (leadlimit)
                 leadingfragsleft = WinningConditionHelper_secondscore + leadlimit - WinningConditionHelper_topscore;
             if (limit && leadlimit && autocvar_leadlimit_and_fraglimit)
                 fragsleft = max(fragsleft, leadingfragsleft);
             else
                 fragsleft = min(fragsleft, leadingfragsleft);
         }
         if (fragsleft_last != fragsleft) // do not announce same remaining frags multiple times
         {
             if (fragsleft == 1)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_1);
             else if (fragsleft == 2)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_2);
             else if (fragsleft == 3)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_3);
             fragsleft_last = fragsleft;
         }
     }
     bool fraglimit_reached = (limit && WinningConditionHelper_topscore >= limit);
     bool leadlimit_reached = (leadlimit && WinningConditionHelper_topscore - WinningConditionHelper_secondscore >= leadlimit);
     bool limit_reached;
     // only respect leadlimit_and_fraglimit when both limits are set or the game will never end
     if (limit && leadlimit && autocvar_leadlimit_and_fraglimit)
         limit_reached = (fraglimit_reached && leadlimit_reached);
     else
         limit_reached = (fraglimit_reached || leadlimit_reached);
     return GetWinningCode(
         WinningConditionHelper_topscore && limit_reached,
         WinningConditionHelper_equality
     );
 }
Variable Documentation
string cache_lastmutatormsg
Definition at line 28 of file world.qh.
Referenced by getwelcomemessage(), and InitGameplayMode().
string cache_mutatormsg
Definition at line 27 of file world.qh.
Referenced by getwelcomemessage(), and InitGameplayMode().
float checkrules_equality
Definition at line 3 of file world.qh.
Referenced by CampaignPreIntermission(), and WinningCondition_RanOutOfSpawns().
float checkrules_overtimesadded
Definition at line 6 of file world.qh.
Referenced by CheckRules_World(), InitiateOvertime(), InitiateSuddenDeath(), and ReadyRestart_force().
float checkrules_suddendeathend
Definition at line 5 of file world.qh.
Referenced by CheckRules_World(), InitiateSuddenDeath(), ReadyRestart_force(), and WinningCondition_Scores().
float checkrules_suddendeathwarning
Definition at line 4 of file world.qh.
Referenced by CheckRules_World(), and ReadyRestart_force().
string clientstuff
Definition at line 19 of file world.qh.
Referenced by ClientConnect(), InitGameplayMode(), and spawnfunc().
string cvar_changes
Definition at line 11 of file world.qh.
Referenced by CommonCommand_cvar_changes(), and cvar_changes_init().
string cvar_purechanges
Definition at line 12 of file world.qh.
Referenced by CommonCommand_cvar_purechanges(), cvar_changes_init(), and WeaponStats_ready().
float cvar_purechanges_count
Definition at line 13 of file world.qh.
Referenced by cvar_changes_init(), WeaponStats_ready(), and WinningConditionHelper().
float default_player_alpha
Definition at line 30 of file world.qh.
Referenced by CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), PutPlayerInServer(), SetDefaultAlpha(), and vehicles_exit().
float default_weapon_alpha
Definition at line 31 of file world.qh.
Referenced by CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and SetDefaultAlpha().
string fog
Definition at line 23 of file world.qh.
IntrusiveList g_moveables
Definition at line 51 of file world.qh.
Referenced by Physics_Frame().
string gamemode_name
Definition at line 17 of file world.qh.
Referenced by getwelcomemessage(), and InitGameplayMode().
string matchid
Definition at line 21 of file world.qh.
Referenced by spawnfunc(), and W_HitPlotOpen().
string modname
Definition at line 15 of file world.qh.
Referenced by spawnfunc(), WinningConditionHelper(), XonoticServerInfoDialog_loadServerInfo(), and XonoticServerList_drawListBoxItem().
string redirection_target
Definition at line 25 of file world.qh.
Referenced by DoNextMapOverride(), and RedirectionThink().
bool server_is_dedicated
Definition at line 9 of file world.qh.
Referenced by Create_Notification_Entity_InfoCenter(), dedicated_print(), Local_Notification_WOVA(), Maplist_Init(), spawnfunc(), StartFrame(), and SV_PausedTic().
float ServerProgsDB
Definition at line 34 of file world.qh.
Referenced by ctf_CaptureRecord(), ctf_Initialize(), GameCommand_database(), getladder(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), race_writeTime(), RestoreGame(), Shutdown(), spawnfunc(), and uid2name().
float TemporaryDB
Definition at line 35 of file world.qh.
Referenced by getladder(), Shutdown(), and spawnfunc().
float winning
Definition at line 37 of file world.qh.
Referenced by assault_new_round(), spawnfunc(), target_assault_roundend_reset(), target_assault_roundend_use(), target_invasion_roundend_use(), and WinningCondition_LMS().
const int WINNING_NEVER = 2
Definition at line 40 of file world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_LMS(), and WinningCondition_Race().
const int WINNING_NO = 0
Definition at line 38 of file world.qh.
Referenced by GetWinningCode(), WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), and WinningCondition_RanOutOfSpawns().
const int WINNING_STARTSUDDENDEATHOVERTIME = 3
Definition at line 41 of file world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
const int WINNING_YES = 1
Definition at line 39 of file world.qh.
Referenced by CheckRules_World(), GetWinningCode(), WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), WinningCondition_QualifyingThenRace(), WinningCondition_Race(), and WinningCondition_RanOutOfSpawns().