Xonotic: server/command/sv_cmd.qh File Reference
sv_cmd.qh File Reference
Functions
void GameCommand_macro_write_aliases (float fh)
string GotoMap (string m)
void race_deleteTime (string map, float pos)
void shuffleteams ()
Variables
bool shuffleteams_on_reset_map
Function Documentation
void GameCommand_macro_write_aliases (float fh)
Definition at line 1722 of file sv_cmd.qc.
References CMD_Write_Alias, and FOREACH.
Referenced by GENERIC_COMMAND().
 {
     FOREACH(SERVER_COMMANDS, true, { CMD_Write_Alias("qc_cmd_sv", it.m_name, it.m_description); });
 }
string GotoMap (string m)
Definition at line 2048 of file g_world.qc.
References alreadychangedlevel, autocvar_sv_vote_gametype, cvar_set(), DoNextMapOverride(), GameTypeVote_MapInfo_FixName(), MapInfo_CheckMap(), and mapvote_initialized.
Referenced by GameCommand_gotomap().
 {
     m = GameTypeVote_MapInfo_FixName(m);
     if (!m)
         return "The map you suggested is not available on this server.";
     if (!autocvar_sv_vote_gametype)
     if(!MapInfo_CheckMap(m))
         return "The map you suggested does not support the current game mode.";
     cvar_set("nextmap", m);
     cvar_set("timelimit", "-1");
     if(mapvote_initialized || alreadychangedlevel)
     {
         if(DoNextMapOverride(0))
             return "Map switch initiated.";
         else
             return "Hm... no. For some reason I like THIS map more.";
     }
     else
         return "Map switch will happen after scoreboard.";
 }
void race_deleteTime (string map, float pos)
Definition at line 359 of file race.qc.
References CTF_RECORD, CTS_RECORD, db_put(), db_remove, ftos(), g_ctf, g_cts, GetMapname(), getrankings(), MSG_ALL, race_readTime(), race_readUID(), RACE_RECORD, race_send_recordtime(), race_SendRankings(), RANKINGS_CNT, ServerProgsDB, strcat(), and strcpy.
Referenced by GameCommand_delrec().
 {
     string rr = ((g_cts) ? CTS_RECORD : ((g_ctf) ? CTF_RECORD : RACE_RECORD));
     for(int i = pos; i <= RANKINGS_CNT; ++i)
     {
         string therank = ftos(i);
         if (i == RANKINGS_CNT)
         {
             db_remove(ServerProgsDB, strcat(map, rr, "time", therank));
             db_remove(ServerProgsDB, strcat(map, rr, "crypto_idfp", therank));
         }
         else
         {
             db_put(ServerProgsDB, strcat(map, rr, "time", therank), ftos(race_readTime(GetMapname(), i+1)));
             db_put(ServerProgsDB, strcat(map, rr, "crypto_idfp", therank), race_readUID(GetMapname(), i+1));
         }
     }
     race_SendRankings(pos, 0, 1, MSG_ALL);
     if(pos == 1)
         race_send_recordtime(MSG_ALL);
     strcpy(rankings_reply, getrankings());
 }
void shuffleteams ()
Definition at line 1277 of file sv_cmd.qc.
References bprint(), entity(), FOREACH_CLIENT, FOREACH_CLIENT_RANDOM, IS_PLAYER, LOG_INFO, max(), NULL, NUM_TEAMS, TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_IsTeamAllowed(), and teamplay.
Referenced by GameCommand_shuffleteams(), and reset_map().
 {
     if (!teamplay)
     {
         LOG_INFO("Can't shuffle teams when currently not playing a team game.");
         return;
     }
     FOREACH_CLIENT(IS_PLAYER(it) || it.caplayer, {
         if (Player_HasRealForcedTeam(it)) {
             // we could theoretically assign forced players to their teams
             // and shuffle the rest to fill the empty spots but in practise
             // either all players or none are gonna have forced teams
             LOG_INFO("Can't shuffle teams because at least one player has a forced team.");
             return;
         }
     });
     int number_of_teams = 0;
     entity balance = TeamBalance_CheckAllowedTeams(NULL);
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (TeamBalance_IsTeamAllowed(balance, i))
         {
             number_of_teams = max(i, number_of_teams);
         }
     }
     TeamBalance_Destroy(balance);
     int team_index = 0;
     FOREACH_CLIENT_RANDOM(IS_PLAYER(it) || it.caplayer, {
         int target_team_index = team_index + 1;
         if (Entity_GetTeamIndex(it) != target_team_index)
         {
             MoveToTeam(it, target_team_index, 6);
         }
         team_index = (team_index + 1) % number_of_teams;
     });
     bprint("Successfully shuffled the players around randomly.\n");
 }
Variable Documentation
bool shuffleteams_on_reset_map
Definition at line 7 of file sv_cmd.qh.
Referenced by GameCommand_shuffleteams(), MUTATOR_HOOKFUNCTION(), and reset_map().