Xonotic: menu/xonotic/textlabel.qc File Reference
textlabel.qc File Reference
#include "textlabel.qh"
Functions
entity makeXonoticHeaderLabel (string theText)
entity makeXonoticTextLabel (float theAlign, string theText)
void XonoticTextLabel_configureXonoticTextLabel (entity me, float theAlign, string theText)
void XonoticTextLabel_draw (entity me)
Function Documentation
entity makeXonoticHeaderLabel (string theText)
Definition at line 10 of file textlabel.qc.
References entity(), and makeXonoticTextLabel().
Referenced by XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticUserSettingsTab_fill().
 {
     entity me;
     me = makeXonoticTextLabel(0.5, theText);
     me.colorL = SKINCOLOR_HEADER;
     me.alpha = SKINALPHA_HEADER;
     me.isBold = true;
     return me;
 }
entity makeXonoticTextLabel (float theAlign, string theText)
Definition at line 3 of file textlabel.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle(), XonoticDamageTextSettings::fill(), makeXonoticHeaderLabel(), XonoticAudioSettingsTab_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticDemoStartConfirmDialog_fill(), XonoticDemoTimeConfirmDialog_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDConfirmDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDQuickMenuDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDVoteDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticLanguageWarningDialog_fill(), XonoticMapInfoDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticQuitDialog_fill(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticServerCreateTab_fill(), XonoticServerInfoDialog_fill(), XonoticServerListTab_fill(), XonoticSingleplayerDialog_fill(), XonoticUid2NameDialog_fill(), XonoticUserbindEditDialog_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticTextLabel);
     me.configureXonoticTextLabel(me, theAlign, theText);
     return me;
 }
void XonoticTextLabel_configureXonoticTextLabel (entity me, float theAlign, string theText)
Definition at line 19 of file textlabel.qc.
 {
     me.configureLabel(me, theText, me.fontSize, theAlign);
 }
void XonoticTextLabel_draw (entity me)
Definition at line 23 of file textlabel.qc.
References SUPER.
 {
     SUPER(XonoticTextLabel).draw(me);
 }