Xonotic: server/teamplay.qc File Reference
teamplay.qc File Reference
#include "teamplay.qh"
#include "client.qh"
#include "race.qh"
#include "scores.qh"
#include "scores_rules.qh"
#include "bot/api.qh"
#include "command/vote.qh"
#include <server/mutators/_mod.qh>
#include "../common/deathtypes/all.qh"
#include <common/gamemodes/_mod.qh>
#include "../common/teams.qh"
Enumerations
enum { TEAM_BALANCE_UNINITIALIZED, TEAM_BALANCE_TEAMS_CHECKED, TEAM_BALANCE_TEAM_COUNTS_FILLED }
Describes a state of team balance entity.
Functions
entity Entity_GetTeam (entity this)
Returns the team entity of the given entity.
int Entity_GetTeamIndex (entity this)
Returns the team index of the given entity.
bool Entity_HasValidTeam (entity this)
Returns whether the given entity belongs to a valid team.
void KillPlayerForTeamChange (entity player)
Kills player as a result of team change.
void LogTeamChange (float player_id, float team_number, int type)
bool MoveToTeam (entity client, int team_index, int type)
Moves player to the specified team.
void Player_DetermineForcedTeam (entity player)
Determines the forced team of the player using current global config.
int Player_GetForcedTeamIndex (entity player)
Returns the index of the forced team of the given player.
bool Player_HasRealForcedTeam (entity player)
Returns whether player has real forced team.
void Player_SetForcedTeamIndex (entity player, int team_index)
Sets the index of the forced team of the given player.
bool Player_SetTeamIndex (entity player, int index)
Sets the team of the player using its index.
void Player_SetTeamIndexChecked (entity player, int team_index)
Sets the team of the player with all sanity checks.
void setcolor (entity this, int clr)
void SetPlayerColors (entity player, float _color)
bool SetPlayerTeam (entity player, int team_index, int type)
Sets the team of the player.
STATIC_INIT (g_team_entities)
void SV_ChangeTeam (entity player, int new_color)
Called when the player connects or when they change their color with the "color" command.
int Team_GetNumberOfAlivePlayers (entity team_ent)
Returns the number of alive players in a team.
int Team_GetNumberOfAliveTeams ()
Returns the number of alive teams.
int Team_GetNumberOfControlPoints (entity team_ent)
Returns the number of control points owned by a team.
int Team_GetNumberOfTeamsWithControlPoints ()
Returns the number of teams that own control points.
entity Team_GetTeam (int team_num)
Returns the global team entity that corresponds to the given TEAM_NUM value.
entity Team_GetTeamFromIndex (int index)
Returns the global team entity at the given index.
float Team_GetTeamScore (entity team_ent)
Returns the score of the team.
void Team_SetNumberOfAlivePlayers (entity team_ent, int number)
Sets the number of alive players in a team.
void Team_SetNumberOfControlPoints (entity team_ent, int number)
Sets the number of control points owned by a team.
void Team_SetTeamScore (entity team_ent, float score)
Sets the score of the team.
void TeamBalance_AutoBalanceBots ()
Switches a bot from one team to another if teams are not balanced.
void TeamBalance_BanTeamsExcept (entity balance, int index)
Bans team change to all teams except the given one.
entity TeamBalance_CheckAllowedTeams (entity for_whom)
Checks whether the player can join teams according to global configuration and mutator settings.
int TeamBalance_CompareTeams (entity balance, int team_index_a, int team_index_b, entity player, bool use_score)
Compares two teams for the purposes of game balance.
int TeamBalance_CompareTeamsInternal (entity team_a, entity team_b, entity player, bool use_score)
Compares two teams for the purposes of game balance.
void TeamBalance_Destroy (entity balance)
Destroy the team balance entity.
int TeamBalance_FindBestTeam (entity balance, entity player, bool ignore_player)
Finds the team that will make the game most balanced if the player joins it.
int TeamBalance_FindBestTeams (entity balance, entity player, bool use_score)
Returns the bitmask of the teams that will make the game most balanced if the player joins any of them.
int TeamBalance_GetAllowedTeams (entity balance)
Returns the bitmask of allowed teams.
int TeamBalance_GetLargestTeamIndex (entity balance, int teams)
Returns the index of the team with most players that is contained in the given bitmask of teams.
int TeamBalance_GetNumberOfPlayers (entity balance, int index)
Returns the number of players (both humans and bots) in a team.
entity TeamBalance_GetPlayerForTeamSwitch (int source_team_index, int destination_team_index, bool is_bot)
Returns the player who is the most suitable for switching between the given teams.
entity TeamBalance_GetTeam (entity balance, int team_num)
Returns the team entity of the team balance entity that corresponds to the given TEAM_NUM value.
void TeamBalance_GetTeamCounts (entity balance, entity ignore)
Counts the number of players and various other information about each team.
entity TeamBalance_GetTeamFromIndex (entity balance, int index)
Returns the team entity of the team balance entity at the given index.
bool TeamBalance_IsTeamAllowed (entity balance, int index)
Returns whether the team change to the specified team is allowed.
bool TeamBalance_IsTeamAllowedInternal (entity balance, int index)
Returns whether the team change to the specified team is allowed.
void TeamBalance_JoinBestTeam (entity player)
Assigns the given player to a team that will make the game most balanced.
int TeamBalanceTeam_GetNumberOfBots (entity team_ent)
Returns the number of bots in a team.
int TeamBalanceTeam_GetNumberOfPlayers (entity team_ent)
Returns the number of players (both humans and bots) in a team.
bool TeamBalanceTeam_IsAllowed (entity team_ent)
Returns whether the team is allowed.
Variables
string autocvar_g_forced_team_blue
string autocvar_g_forced_team_pink
string autocvar_g_forced_team_red
string autocvar_g_forced_team_yellow
entity g_team_entities [NUM_TEAMS]
Holds global team entities.
int m_num_bots
Number of bots in a team.
int m_num_control_points
Number of control points owned by a team.
int m_num_players
Number of players (both humans and bots) in a team.
int m_num_players_alive
Number of alive players in a team.
int m_team_balance_state
Holds the state of the team balance entity.
entity m_team_balance_team [NUM_TEAMS]
???
float m_team_score
The score of the team.
float team_forced
const int TEAM_NOT_ALLOWED = -1
Indicates that the player is not allowed to join a team.
Enumeration Type Documentation
anonymous enum
Describes a state of team balance entity.
Enumerator
TEAM_BALANCE_UNINITIALIZED
The team balance has not been initialized.
TEAM_BALANCE_TEAMS_CHECKED
TeamBalance_CheckAllowedTeams has been called.
TEAM_BALANCE_TEAM_COUNTS_FILLED
TeamBalance_GetTeamCounts has been called.
Definition at line 19 of file teamplay.qc.
 {
     TEAM_BALANCE_UNINITIALIZED,
     TEAM_BALANCE_TEAMS_CHECKED,
     TEAM_BALANCE_TEAM_COUNTS_FILLED
 };
Function Documentation
entity Entity_GetTeam (entity this)
Returns the team entity of the given entity.
Parameters
[in] this Entity to check.
Returns
Team entity of the given entity or NULL if the entity doesn't belong to any team.
Definition at line 151 of file teamplay.qc.
References Entity_GetTeamIndex(), NULL, Team_GetTeamFromIndex(), and Team_IsValidIndex().
Referenced by CA_count_alive_players(), Domination_count_controlpoints(), freezetag_count_alive_players(), MUTATOR_HOOKFUNCTION(), and Onslaught_count_generators().
 {
     int index = Entity_GetTeamIndex(this);
     if (!Team_IsValidIndex(index))
     {
         return NULL;
     }
     return Team_GetTeamFromIndex(index);
 }
int Entity_GetTeamIndex (entity this)
Returns the team index of the given entity.
Parameters
[in] this Entity to check.
Returns
Team index of the entity.
Definition at line 146 of file teamplay.qc.
References team, and Team_TeamToIndex().
Referenced by Entity_GetTeam(), GameCommand_shuffleteams(), SetPlayerTeam(), and TeamBalance_GetPlayerForTeamSwitch().
 {
     return Team_TeamToIndex(this.team);
 }
bool Entity_HasValidTeam (entity this)
Returns whether the given entity belongs to a valid team.
Parameters
[in] this Entity to check.
Returns
True if entity belongs to a valid team, false otherwise.
Definition at line 141 of file teamplay.qc.
References team, and Team_IsValidTeam().
Referenced by CA_count_alive_players(), Domination_count_controlpoints(), and freezetag_count_alive_players().
 {
     return Team_IsValidTeam(this.team);
 }
void KillPlayerForTeamChange (entity player)
Kills player as a result of team change.
Parameters
[in,out] player Player to kill.
Definition at line 1018 of file teamplay.qc.
References Damage(), DMG_NOWEP, IS_DEAD, and MUTATOR_CALLHOOK.
Referenced by SetPlayerTeam().
 {
     if (IS_DEAD(player))
     {
         return;
     }
     if (MUTATOR_CALLHOOK(Player_ChangeTeamKill, player) == true)
     {
         return;
     }
     Damage(player, player, player, 100000, DEATH_TEAMCHANGE.m_id, DMG_NOWEP,
         player.origin, '0 0 0');
 }
void LogTeamChange (float player_id, float team_number, int type)
Definition at line 1005 of file teamplay.qc.
References autocvar_sv_eventlog, and GameLogEcho().
Referenced by SetPlayerTeam().
 {
     if (!autocvar_sv_eventlog)
     {
         return;
     }
     if (player_id < 1)
     {
         return;
     }
     GameLogEcho(sprintf(":team:%d:%d:%d", player_id, team_number, type));
 }
bool MoveToTeam (entity client, int team_index, int type)
Moves player to the specified team.
Parameters
[in,out] client Client to move.
[in] team_index Index of the team.
[in] type ???
Returns
True on success, false otherwise.
Definition at line 296 of file teamplay.qc.
References lockteams, and SetPlayerTeam().
Referenced by GameCommand_moveplayer(), and GameCommand_shuffleteams().
 {
     //PrintToChatAll(sprintf("MoveToTeam: %s, %f", client.netname, team_index));
     int lockteams_backup = lockteams;  // backup any team lock
     lockteams = 0;  // disable locked teams
     if (!SetPlayerTeam(client, team_index, type))
     {
         lockteams = lockteams_backup;  // restore the team lock
         return false;
     }
     lockteams = lockteams_backup;  // restore the team lock
     return true;
 }
void Player_DetermineForcedTeam (entity player)
Determines the forced team of the player using current global config.
Parameters
[in,out] player Player to adjust.
Definition at line 345 of file teamplay.qc.
References autocvar_g_campaign, autocvar_g_campaign_forceteam, autocvar_g_forced_team_blue, autocvar_g_forced_team_otherwise, autocvar_g_forced_team_pink, autocvar_g_forced_team_red, autocvar_g_forced_team_yellow, IS_REAL_CLIENT, Player_HasRealForcedTeam(), PlayerInList(), TEAM_FORCE_DEFAULT, TEAM_FORCE_SPECTATOR, Team_IsValidIndex(), and teamplay.
Referenced by ClientConnect().
 {
     if (autocvar_g_campaign)
     {
         if (IS_REAL_CLIENT(player)) // only players, not bots
         {
             if (Team_IsValidIndex(autocvar_g_campaign_forceteam))
             {
                 player.team_forced = autocvar_g_campaign_forceteam;
             }
             else
             {
                 player.team_forced = TEAM_FORCE_DEFAULT;
             }
         }
     }
     else if (PlayerInList(player, autocvar_g_forced_team_red))
     {
         player.team_forced = 1;
     }
     else if (PlayerInList(player, autocvar_g_forced_team_blue))
     {
         player.team_forced = 2;
     }
     else if (PlayerInList(player, autocvar_g_forced_team_yellow))
     {
         player.team_forced = 3;
     }
     else if (PlayerInList(player, autocvar_g_forced_team_pink))
     {
         player.team_forced = 4;
     }
     else
     {
         switch (autocvar_g_forced_team_otherwise)
         {
             case "red":
             {
                 player.team_forced = 1;
                 break;
             }
             case "blue":
             {
                 player.team_forced = 2;
                 break;
             }
             case "yellow":
             {
                 player.team_forced = 3;
                 break;
             }
             case "pink":
             {
                 player.team_forced = 4;
                 break;
             }
             case "spectate":
             case "spectator":
             {
                 player.team_forced = TEAM_FORCE_SPECTATOR;
                 break;
             }
             default:
             {
                 player.team_forced = TEAM_FORCE_DEFAULT;
                 break;
             }
         }
     }
     if (!teamplay && Player_HasRealForcedTeam(player))
     {
         player.team_forced = TEAM_FORCE_DEFAULT;
     }
 }
int Player_GetForcedTeamIndex (entity player)
Returns the index of the forced team of the given player.
Parameters
[in] player Player to check.
Returns
Index of the forced team.
Definition at line 315 of file teamplay.qc.
Referenced by ClientCommand_clientversion(), ClientCommand_selectteam(), GameCommand_moveplayer(), and nJoinAllowed().
 {
     return player.team_forced;
 }
bool Player_HasRealForcedTeam (entity player)
Returns whether player has real forced team.
Spectator team is ignored.
Parameters
[in] player Player to check.
Returns
True if player has real forced team, false otherwise.
Definition at line 310 of file teamplay.qc.
References TEAM_FORCE_DEFAULT.
Referenced by GameCommand_shuffleteams(), Player_DetermineForcedTeam(), ShowTeamSelection(), TeamBalance_GetTeamCounts(), and TeamBalance_JoinBestTeam().
 {
     return player.team_forced > TEAM_FORCE_DEFAULT;
 }
void Player_SetForcedTeamIndex (entity player, int team_index)
Sets the index of the forced team of the given player.
Parameters
[in,out] player Player to adjust.
[in] team_index Index of the team to set.
Definition at line 320 of file teamplay.qc.
References LOG_FATAL, TEAM_FORCE_DEFAULT, TEAM_FORCE_SPECTATOR, and Team_IsValidIndex().
Referenced by GameCommand_moveplayer(), minigame_addplayer(), and player_clear_minigame().
 {
     switch (team_index)
     {
         case TEAM_FORCE_SPECTATOR:
         case TEAM_FORCE_DEFAULT:
         {
             player.team_forced = team_index;
             break;
         }
         default:
         {
             if (!Team_IsValidIndex(team_index))
             {
                 LOG_FATAL("Player_SetForcedTeamIndex: Invalid team index.");
             }
             else
             {
                 player.team_forced = team_index;
                 break;
             }
         }
     }
 }
bool Player_SetTeamIndex (entity player, int index)
Sets the team of the player using its index.
Parameters
[in,out] player Player to adjust.
[in] index Index of the team to set.
Returns
True if team switch was successful, false otherwise.
Definition at line 175 of file teamplay.qc.
References MUTATOR_CALLHOOK, SetPlayerColors(), Team_IndexToTeam(), and Team_TeamToIndex().
Referenced by SetPlayerTeam().
 {
     int new_team = Team_IndexToTeam(index);
     if (player.team == new_team)
     {
         if (new_team != -1)
         {
             // This is important when players join the game and one of their
             // color matches the team color while other doesn't. For example
             // [BOT]Lion: color 0 4.
             SetPlayerColors(player, new_team - 1);
         }
         return true;
     }
     int old_index = Team_TeamToIndex(player.team);
     if (MUTATOR_CALLHOOK(Player_ChangeTeam, player, old_index, index) == true)
     {
         // Mutator has blocked team change.
         return false;
     }
     if (new_team == -1)
     {
         player.team = -1;
     }
     else
     {
         SetPlayerColors(player, new_team - 1);
     }
     MUTATOR_CALLHOOK(Player_ChangedTeam, player, old_index, index);
     return true;
 }
void Player_SetTeamIndexChecked (entity player, int team_index)
Sets the team of the player with all sanity checks.
Parameters
[in,out] player Player to adjust.
[in] team_index Index of the team to set.
Definition at line 245 of file teamplay.qc.
References autocvar_g_balance_teams, autocvar_g_balance_teams_prevent_imbalance, autocvar_g_campaign, autocvar_g_changeteam_banned, CS(), entity(), SetPlayerTeam(), TEAM_CHANGE_MANUAL, Team_IndexToBit(), Team_IsValidIndex(), TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_FindBestTeams(), TeamBalance_GetTeamCounts(), TeamBalance_IsTeamAllowedInternal(), teamplay, and wasplayer.
Referenced by ClientKill_Now_TeamChange(), and SV_ChangeTeam().
 {
     if (!teamplay)
     {
         return;
     }
     if (!Team_IsValidIndex(team_index))
     {
         return;
     }
     if ((autocvar_g_campaign) || (autocvar_g_changeteam_banned &&
         CS(player).wasplayer))
     {
         Send_Notification(NOTIF_ONE, player, MSG_INFO,
             INFO_TEAMCHANGE_NOTALLOWED);
         return;
     }
     entity balance = TeamBalance_CheckAllowedTeams(player);
     if (team_index == 1 && !TeamBalance_IsTeamAllowedInternal(balance, 1))
     {
         team_index = 4;
     }
     if (team_index == 4 && !TeamBalance_IsTeamAllowedInternal(balance, 4))
     {
         team_index = 3;
     }
     if (team_index == 3 && !TeamBalance_IsTeamAllowedInternal(balance, 3))
     {
         team_index = 2;
     }
     if (team_index == 2 && !TeamBalance_IsTeamAllowedInternal(balance, 2))
     {
         team_index = 1;
     }
     // autocvar_g_balance_teams_prevent_imbalance only makes sense if autocvar_g_balance_teams is on, as it makes the team selection dialog pointless
     if (autocvar_g_balance_teams && autocvar_g_balance_teams_prevent_imbalance)
     {
         TeamBalance_GetTeamCounts(balance, player);
         if ((Team_IndexToBit(team_index) & TeamBalance_FindBestTeams(balance,
             player, false)) == 0)
         {
             Send_Notification(NOTIF_ONE, player, MSG_INFO,
                 INFO_TEAMCHANGE_LARGERTEAM);
             TeamBalance_Destroy(balance);
             return;
         }
     }
     TeamBalance_Destroy(balance);
     SetPlayerTeam(player, team_index, TEAM_CHANGE_MANUAL);
 }
void setcolor (entity this, int clr)
Definition at line 131 of file teamplay.qc.
References clientcolors, and team.
Referenced by SetPlayerColors().
 {
 #if 0
     this.clientcolors = clr;
     this.team = (clr & 15) + 1;
 #else
     builtin_setcolor(this, clr);
 #endif
 }
void SetPlayerColors (entity player, float _color)
Definition at line 161 of file teamplay.qc.
References setcolor(), and teamplay.
Referenced by Player_SetTeamIndex(), and SV_ChangeTeam().
 {
     float pants = _color & 0x0F;
     float shirt = _color & 0xF0;
     if (teamplay)
     {
         setcolor(player, 16 * pants + pants);
     }
     else
     {
         setcolor(player, shirt + pants);
     }
 }
bool SetPlayerTeam (entity player, int team_index, int type)
Sets the team of the player.
Parameters
[in,out] player Player to adjust.
[in] team_index Index of the team to set.
[in] type Type of the team change. See TEAM_CHANGE constants.
Returns
True if team switch was successful, false otherwise.
Definition at line 207 of file teamplay.qc.
References APP_TEAM_NUM, CS(), Entity_GetTeamIndex(), FRAGS_SPECTATOR, IS_BOT_CLIENT, just_joined, KillPlayerForTeamChange(), LogTeamChange(), NULL, Player_SetTeamIndex(), PlayerScore_Clear(), and TeamBalance_AutoBalanceBots().
Referenced by bot_clientconnect(), MoveToTeam(), Player_SetTeamIndexChecked(), PutObserverInServer(), TeamBalance_AutoBalanceBots(), and TeamBalance_JoinBestTeam().
 {
     int old_team_index = Entity_GetTeamIndex(player);
     if (!Player_SetTeamIndex(player, team_index))
     {
         return false;
     }
     LogTeamChange(player.playerid, player.team, type);
     if (team_index != old_team_index)
     {
         PlayerScore_Clear(player);
         if (team_index != -1)
         {
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(
                 player.team, INFO_JOIN_PLAY_TEAM), player.netname);
         }
         else
         {
             if (!CS(player).just_joined)
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_QUIT_SPECTATE,
                     player.netname);
             }
         }
         KillPlayerForTeamChange(player);
         if (!IS_BOT_CLIENT(player))
         {
             TeamBalance_AutoBalanceBots();
         }
     }
     else if (team_index == -1)
     {
         if (!CS(player).just_joined && player.frags != FRAGS_SPECTATOR)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_QUIT_SPECTATE, player.netname);
     }
     return true;
 }
STATIC_INIT (g_team_entities)
Definition at line 49 of file teamplay.qc.
References g_team_entities, NUM_TEAMS, and spawn().
 {
     for (int i = 0; i < NUM_TEAMS; ++i)
     {
         g_team_entities[i] = spawn();
     }
 }
void SV_ChangeTeam (entity player, int new_color)
Called when the player connects or when they change their color with the "color" command.
Parameters
[in,out] player Player that requested a new color.
[in] new_color Requested color.
Definition at line 1120 of file teamplay.qc.
References IS_CLIENT, NULL, Player_SetTeamIndexChecked(), SetPlayerColors(), Team_TeamToIndex(), and teamplay.
 {
     if (!teamplay)
     {
         SetPlayerColors(player, new_color);
     }
     // TODO: Should we really bother with this?
     if(!IS_CLIENT(player))
     {
         // since this is an engine function, and gamecode doesn't have any calls earlier than this, do the connecting message here
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_CONNECTING,
             player.netname);
         return;
     }
     if (!teamplay)
     {
         return;
     }
     Player_SetTeamIndexChecked(player, Team_TeamToIndex((new_color & 0x0F) +
         1));
 }
int Team_GetNumberOfAlivePlayers (entity team_ent)
Returns the number of alive players in a team.
Parameters
[in] team_ent Team entity.
Returns
Number of alive players in a team.
Definition at line 85 of file teamplay.qc.
Referenced by CA_CheckTeams(), CA_count_alive_players(), CA_GetWinnerTeam(), freezetag_CheckTeams(), freezetag_count_alive_players(), freezetag_getWinnerTeam(), and MUTATOR_HOOKFUNCTION().
 {
     return team_ent.m_num_players_alive;
 }
int Team_GetNumberOfAliveTeams ()
Returns the number of alive teams.
Returns
Number of alive teams.
Definition at line 95 of file teamplay.qc.
References g_team_entities, m_num_players_alive, NUM_TEAMS, and result.
Referenced by CA_CheckTeams(), CA_CheckWinner(), freezetag_CheckTeams(), and freezetag_CheckWinner().
 {
     int result = 0;
     for (int i = 0; i < NUM_TEAMS; ++i)
     {
         if (g_team_entities[i].m_num_players_alive > 0)
         {
             ++result;
         }
     }
     return result;
 }
int Team_GetNumberOfControlPoints (entity team_ent)
Returns the number of control points owned by a team.
Parameters
[in] team_ent Team entity.
Returns
Number of control points owned by a team.
Definition at line 108 of file teamplay.qc.
Referenced by Domination_count_controlpoints(), Domination_GetWinnerTeam(), Onslaught_count_generators(), and Onslaught_GetWinnerTeam().
 {
     return team_ent.m_num_control_points;
 }
int Team_GetNumberOfTeamsWithControlPoints ()
Returns the number of teams that own control points.
Returns
Number of teams that own control points.
Definition at line 118 of file teamplay.qc.
References g_team_entities, m_num_control_points, NUM_TEAMS, and result.
Referenced by Onslaught_CheckWinner().
 {
     int result = 0;
     for (int i = 0; i < NUM_TEAMS; ++i)
     {
         if (g_team_entities[i].m_num_control_points > 0)
         {
             ++result;
         }
     }
     return result;
 }
entity Team_GetTeam (int team_num)
Returns the global team entity that corresponds to the given TEAM_NUM value.
Parameters
[in] team_num Team value. See TEAM_NUM constants.
Returns
Global team entity that corresponds to the given TEAM_NUM value.
Definition at line 66 of file teamplay.qc.
References g_team_entities, LOG_FATALF, Team_IsValidTeam(), and Team_TeamToIndex().
Referenced by WinningCondition_RanOutOfSpawns().
 {
     if (!Team_IsValidTeam(team_num))
     {
         LOG_FATALF("Team_GetTeam: Value is invalid: %f", team_num);
     }
     return g_team_entities[Team_TeamToIndex(team_num) - 1];
 }
entity Team_GetTeamFromIndex (int index)
Returns the global team entity at the given index.
Parameters
[in] index Index of the team.
Returns
Global team entity at the given index.
Definition at line 57 of file teamplay.qc.
References g_team_entities, LOG_FATALF, and Team_IsValidIndex().
Referenced by CA_CheckTeams(), CA_count_alive_players(), CA_GetWinnerTeam(), Domination_count_controlpoints(), Domination_GetWinnerTeam(), Entity_GetTeam(), freezetag_CheckTeams(), freezetag_count_alive_players(), freezetag_getWinnerTeam(), Onslaught_count_generators(), Onslaught_GetWinnerTeam(), WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
 {
     if (!Team_IsValidIndex(index))
     {
         LOG_FATALF("Team_GetTeamFromIndex: Index is invalid: %f", index);
     }
     return g_team_entities[index - 1];
 }
float Team_GetTeamScore (entity team_ent)
Returns the score of the team.
Parameters
[in] team_ent Team entity.
Returns
Score of the team.
Definition at line 75 of file teamplay.qc.
 {
     return team_ent.m_team_score;
 }
void Team_SetNumberOfAlivePlayers (entity team_ent, int number)
Sets the number of alive players in a team.
Parameters
[in,out] team_ent Team entity.
[in] number Number of players to set.
Definition at line 90 of file teamplay.qc.
Referenced by CA_count_alive_players(), and freezetag_count_alive_players().
 {
     team_ent.m_num_players_alive = number;
 }
void Team_SetNumberOfControlPoints (entity team_ent, int number)
Sets the number of control points owned by a team.
Parameters
[in,out] team_ent Team entity.
[in] number Number of control points to set.
Definition at line 113 of file teamplay.qc.
Referenced by Domination_count_controlpoints(), and Onslaught_count_generators().
 {
     team_ent.m_num_control_points = number;
 }
void Team_SetTeamScore (entity team_ent, float score)
Sets the score of the team.
Parameters
[in,out] team_ent Team entity.
[in] score Score to set.
Definition at line 80 of file teamplay.qc.
Referenced by WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
 {
     team_ent.m_team_score = score;
 }
void TeamBalance_AutoBalanceBots ()
Switches a bot from one team to another if teams are not balanced.
Definition at line 866 of file teamplay.qc.
References BITS, entity(), NULL, NUM_TEAMS, SetPlayerTeam(), TEAM_CHANGE_AUTO, Team_IndexToBit(), TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetLargestTeamIndex(), TeamBalance_GetPlayerForTeamSwitch(), TeamBalance_GetTeamCounts(), TeamBalance_GetTeamFromIndex(), TeamBalanceTeam_GetNumberOfPlayers(), TeamBalanceTeam_IsAllowed(), and teams.
Referenced by SetPlayerTeam().
 {
     // checks disabled because we always want auto-balanced bots
     //if (!(autocvar_g_balance_teams && autocvar_g_balance_teams_prevent_imbalance))
     //  return;
     entity balance = TeamBalance_CheckAllowedTeams(NULL);
     TeamBalance_GetTeamCounts(balance, NULL);
     int smallest_team_index = 0;
     int smallest_team_player_count = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         entity team_ = TeamBalance_GetTeamFromIndex(balance, i);
         if (!TeamBalanceTeam_IsAllowed(team_))
         {
             continue;
         }
         int playercount = TeamBalanceTeam_GetNumberOfPlayers(team_);
         if (smallest_team_index == 0)
         {
             smallest_team_index = i;
             smallest_team_player_count = playercount;
         }
         else if (playercount < smallest_team_player_count)
         {
             smallest_team_index = i;
             smallest_team_player_count = playercount;
         }
     }
     //PrintToChatAll(sprintf("Smallest team: %f", smallest_team_index));
     //PrintToChatAll(sprintf("Smallest team players: %f", smallest_team_player_count));
     entity switchable_bot = NULL;
     int teams = BITS(NUM_TEAMS);
     while (teams != 0)
     {
         int largest_team_index = TeamBalance_GetLargestTeamIndex(balance,
             teams);
         if (smallest_team_index == largest_team_index)
         {
             TeamBalance_Destroy(balance);
             return;
         }
         entity largest_team = TeamBalance_GetTeamFromIndex(balance,
             largest_team_index);
         int largest_team_player_count = TeamBalanceTeam_GetNumberOfPlayers(
             largest_team);
         if (largest_team_player_count - smallest_team_player_count < 2)
         {
             TeamBalance_Destroy(balance);
             return;
         }
         //PrintToChatAll(sprintf("Largest team: %f", largest_team_index));
         //PrintToChatAll(sprintf("Largest team players: %f", largest_team_player_count));
         switchable_bot = TeamBalance_GetPlayerForTeamSwitch(largest_team_index,
             smallest_team_index, true);
         if (switchable_bot != NULL)
         {
             break;
         }
         teams &= ~Team_IndexToBit(largest_team_index);
     }
     TeamBalance_Destroy(balance);
     if (switchable_bot == NULL)
     {
         //PrintToChatAll("No bot found after searching through all the teams");
         return;
     }
     SetPlayerTeam(switchable_bot, smallest_team_index, TEAM_CHANGE_AUTO);
 }
void TeamBalance_BanTeamsExcept (entity balance, int index)
Bans team change to all teams except the given one.
Parameters
[in,out] balance Team balance entity.
[in] index Index of the team.
Definition at line 1038 of file teamplay.qc.
References NUM_TEAMS, and TEAM_NOT_ALLOWED.
Referenced by TeamBalance_CheckAllowedTeams().
 {
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (i != index)
         {
             balance.m_team_balance_team[i - 1].m_num_players = TEAM_NOT_ALLOWED;
         }
     }
 }
entity TeamBalance_CheckAllowedTeams (entity for_whom)
Checks whether the player can join teams according to global configuration and mutator settings.
Parameters
[in] for_whom Player to check for. Pass NULL for global rules.
Returns
Team balance entity that holds information about teams. This entity will be automatically destroyed on the next frame but you are encouraged to manually destroy it by calling TeamBalance_Destroy for performance reasons.
Definition at line 456 of file teamplay.qc.
References autocvar_bot_vs_human, AvailableTeams(), BIT, classname, entity(), find(), g_team_entities, IS_BOT_CLIENT, M_ARGV, MUTATOR_CALLHOOK, NULL, NUM_TEAMS, setthink, spawn(), string_null, TEAM_BALANCE_TEAMS_CHECKED, Team_IsValidTeam(), TEAM_NOT_ALLOWED, TeamBalance_BanTeamsExcept(), TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetTeam(), and TeamBalance_IsTeamAllowedInternal().
Referenced by bot_removefromlargestteam(), ClientCommand_selectteam(), ClientConnect(), dom_DelayedInit(), GameCommand_moveplayer(), GameCommand_shuffleteams(), ons_ScoreRules(), Player_SetTeamIndexChecked(), ScoreRules_generic(), TeamBalance_AutoBalanceBots(), TeamBalance_CheckAllowedTeams(), TeamBalance_GetPlayerForTeamSwitch(), and TeamBalance_JoinBestTeam().
 {
     entity balance = spawn();
     for (int i = 0; i < NUM_TEAMS; ++i)
     {
         entity team_ent = balance.m_team_balance_team[i] = spawn();
         team_ent.m_team_score = g_team_entities[i].m_team_score;
         team_ent.m_num_players = TEAM_NOT_ALLOWED;
         team_ent.m_num_bots = 0;
     }
     setthink(balance, TeamBalance_Destroy);
     int teams_mask = 0;
     string teament_name = string_null;
     bool mutator_returnvalue = MUTATOR_CALLHOOK(TeamBalance_CheckAllowedTeams,
         teams_mask, teament_name, for_whom);
     teams_mask = M_ARGV(0, float);
     teament_name = M_ARGV(1, string);
     if (mutator_returnvalue)
     {
         for (int i = 0; i < NUM_TEAMS; ++i)
         {
             if (teams_mask & BIT(i))
             {
                 balance.m_team_balance_team[i].m_num_players = 0;
             }
         }
     }
     if (teament_name)
     {
         entity head = find(NULL, classname, teament_name);
         while (head)
         {
             if (Team_IsValidTeam(head.team))
             {
                 TeamBalance_GetTeam(balance, head.team).m_num_players = 0;
             }
             head = find(head, classname, teament_name);
         }
     }
     // TODO: Balance quantity of bots across > 2 teams when bot_vs_human is set (and remove next line)
     if (AvailableTeams() == 2)
     if (autocvar_bot_vs_human && for_whom)
     {
         if (autocvar_bot_vs_human > 0)
         {
             // find last team available
             if (IS_BOT_CLIENT(for_whom))
             {
                 if (TeamBalance_IsTeamAllowedInternal(balance, 4))
                 {
                     TeamBalance_BanTeamsExcept(balance, 4);
                 }
                 else if (TeamBalance_IsTeamAllowedInternal(balance, 3))
                 {
                     TeamBalance_BanTeamsExcept(balance, 3);
                 }
                 else
                 {
                     TeamBalance_BanTeamsExcept(balance, 2);
                 }
                 // no further cases, we know at least 2 teams exist
             }
             else
             {
                 if (TeamBalance_IsTeamAllowedInternal(balance, 1))
                 {
                     TeamBalance_BanTeamsExcept(balance, 1);
                 }
                 else if (TeamBalance_IsTeamAllowedInternal(balance, 2))
                 {
                     TeamBalance_BanTeamsExcept(balance, 2);
                 }
                 else
                 {
                     TeamBalance_BanTeamsExcept(balance, 3);
                 }
                 // no further cases, bots have one of the teams
             }
         }
         else
         {
             // find first team available
             if (IS_BOT_CLIENT(for_whom))
             {
                 if (TeamBalance_IsTeamAllowedInternal(balance, 1))
                 {
                     TeamBalance_BanTeamsExcept(balance, 1);
                 }
                 else if (TeamBalance_IsTeamAllowedInternal(balance, 2))
                 {
                     TeamBalance_BanTeamsExcept(balance, 2);
                 }
                 else
                 {
                     TeamBalance_BanTeamsExcept(balance, 3);
                 }
                 // no further cases, we know at least 2 teams exist
             }
             else
             {
                 if (TeamBalance_IsTeamAllowedInternal(balance, 4))
                 {
                     TeamBalance_BanTeamsExcept(balance, 4);
                 }
                 else if (TeamBalance_IsTeamAllowedInternal(balance, 3))
                 {
                     TeamBalance_BanTeamsExcept(balance, 3);
                 }
                 else
                 {
                     TeamBalance_BanTeamsExcept(balance, 2);
                 }
                 // no further cases, bots have one of the teams
             }
         }
     }
     if (!for_whom)
     {
         balance.m_team_balance_state = TEAM_BALANCE_TEAMS_CHECKED;
         return balance;
     }
     // if player has a forced team, ONLY allow that one
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (for_whom.team_forced == i &&
             TeamBalance_IsTeamAllowedInternal(balance, i))
         {
             TeamBalance_BanTeamsExcept(balance, i);
             break;
         }
     }
     balance.m_team_balance_state = TEAM_BALANCE_TEAMS_CHECKED;
     return balance;
 }
int TeamBalance_CompareTeams (entity balance, int team_index_a, int team_index_b, entity player, bool use_score)
Compares two teams for the purposes of game balance.
Parameters
[in] balance Team balance entity.
[in] team_index_a Index of the first team.
[in] team_index_b Index of the second team.
[in] player Player to check.
[in] use_score Whether to take into account team scores.
Returns
TEAMS_COMPARE value. See above.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 835 of file teamplay.qc.
References entity(), LOG_FATAL, LOG_FATALF, NULL, TEAM_BALANCE_TEAM_COUNTS_FILLED, Team_IsValidIndex(), TeamBalance_CompareTeamsInternal(), TeamBalance_GetTeamFromIndex(), and TEAMS_COMPARE_EQUAL.
Referenced by TeamBalance_FindBestTeams().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_CompareTeams: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state != TEAM_BALANCE_TEAM_COUNTS_FILLED)
     {
         LOG_FATAL("TeamBalance_CompareTeams: "
             "TeamBalance_GetTeamCounts has not been called.");
     }
     if (!Team_IsValidIndex(team_index_a))
     {
         LOG_FATALF("TeamBalance_CompareTeams: team_index_a is invalid: %f",
             team_index_a);
     }
     if (!Team_IsValidIndex(team_index_b))
     {
         LOG_FATALF("TeamBalance_CompareTeams: team_index_b is invalid: %f",
             team_index_b);
     }
     if (team_index_a == team_index_b)
     {
         return TEAMS_COMPARE_EQUAL;
     }
     entity team_a = TeamBalance_GetTeamFromIndex(balance, team_index_a);
     entity team_b = TeamBalance_GetTeamFromIndex(balance, team_index_b);
     return TeamBalance_CompareTeamsInternal(team_a, team_b, player, use_score);
 }
int TeamBalance_CompareTeamsInternal (entity team_a, entity team_index_b, entity player, bool use_score)
Compares two teams for the purposes of game balance.
Parameters
[in] team_a First team.
[in] team_b Second team.
[in] player Player to check.
[in] use_score Whether to take into account team scores.
Returns
TEAMS_COMPARE value. See above.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 1078 of file teamplay.qc.
References bots_would_leave, IS_REAL_CLIENT, TeamBalanceTeam_IsAllowed(), TEAMS_COMPARE_EQUAL, TEAMS_COMPARE_GREATER, TEAMS_COMPARE_INVALID, and TEAMS_COMPARE_LESS.
Referenced by TeamBalance_CompareTeams().
 {
     if (team_a == team_b)
     {
         return TEAMS_COMPARE_EQUAL;
     }
     if (!TeamBalanceTeam_IsAllowed(team_a) ||
         !TeamBalanceTeam_IsAllowed(team_b))
     {
         return TEAMS_COMPARE_INVALID;
     }
     int num_players_team_a = team_a.m_num_players;
     int num_players_team_b = team_b.m_num_players;
     if (IS_REAL_CLIENT(player) && bots_would_leave)
     {
         num_players_team_a -= team_a.m_num_bots;
         num_players_team_b -= team_b.m_num_bots;
     }
     if (num_players_team_a < num_players_team_b)
     {
         return TEAMS_COMPARE_LESS;
     }
     if (num_players_team_a > num_players_team_b)
     {
         return TEAMS_COMPARE_GREATER;
     }
     if (!use_score)
     {
         return TEAMS_COMPARE_EQUAL;
     }
     if (team_a.m_team_score < team_b.m_team_score)
     {
         return TEAMS_COMPARE_LESS;
     }
     if (team_a.m_team_score > team_b.m_team_score)
     {
         return TEAMS_COMPARE_GREATER;
     }
     return TEAMS_COMPARE_EQUAL;
 }
void TeamBalance_Destroy (entity balance)
Destroy the team balance entity.
Parameters
[in,out] balance Team balance entity to destroy.
Note
Team balance entity is allowed to be NULL.
Definition at line 596 of file teamplay.qc.
References NULL, and NUM_TEAMS.
Referenced by ClientCommand_selectteam(), ClientConnect(), dom_DelayedInit(), GameCommand_moveplayer(), GameCommand_shuffleteams(), ons_ScoreRules(), Player_SetTeamIndexChecked(), ScoreRules_generic(), TeamBalance_AutoBalanceBots(), TeamBalance_CheckAllowedTeams(), TeamBalance_GetPlayerForTeamSwitch(), and TeamBalance_JoinBestTeam().
 {
     if (balance == NULL)
     {
         return;
     }
     for (int i = 0; i < NUM_TEAMS; ++i)
     {
         delete(balance.(m_team_balance_team[i]));
     }
     delete(balance);
 }
int TeamBalance_FindBestTeam (entity balance, entity player, bool ignore_player)
Finds the team that will make the game most balanced if the player joins it.
Parameters
[in] balance Team balance entity.
[in] player Player to check.
[in] ignore_player ???
Returns
Index of the team that will make the game most balanced if the player joins it. If there are several equally good teams available, the function will pick a random one.
Definition at line 752 of file teamplay.qc.
References LOG_FATAL, LOG_FATALF, MapInfo_CurrentGametype(), MapInfo_Type_ToString(), NULL, NUM_TEAMS, RandomSelection_AddFloat, RandomSelection_chosen_float, RandomSelection_Init(), TEAM_BALANCE_UNINITIALIZED, Team_IndexToBit(), TeamBalance_FindBestTeams(), and TeamBalance_GetTeamCounts().
Referenced by GameCommand_moveplayer(), and TeamBalance_JoinBestTeam().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_FindBestTeam: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state == TEAM_BALANCE_UNINITIALIZED)
     {
         LOG_FATAL("TeamBalance_FindBestTeam: "
             "Team balance entity is not initialized.");
     }
     // count how many players are in each team
     if (ignore_player)
     {
         TeamBalance_GetTeamCounts(balance, player);
     }
     else
     {
         TeamBalance_GetTeamCounts(balance, NULL);
     }
     int team_bits = TeamBalance_FindBestTeams(balance, player, true);
     if (team_bits == 0)
     {
         LOG_FATALF("TeamBalance_FindBestTeam: No teams available for %s\n",
             MapInfo_Type_ToString(MapInfo_CurrentGametype()));
     }
     RandomSelection_Init();
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (team_bits & Team_IndexToBit(i))
         {
             RandomSelection_AddFloat(i, 1, 1);
         }
     }
     return RandomSelection_chosen_float;
 }
int TeamBalance_FindBestTeams (entity balance, entity player, bool use_score)
Returns the bitmask of the teams that will make the game most balanced if the player joins any of them.
Parameters
[in] balance Team balance entity.
[in] player Player to check.
[in] use_score Whether to take into account team scores.
Returns
Bitmask of the teams that will make the game most balanced if the player joins any of them.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 789 of file teamplay.qc.
References LOG_FATAL, M_ARGV, MUTATOR_CALLHOOK, NULL, NUM_TEAMS, TEAM_BALANCE_TEAM_COUNTS_FILLED, Team_IndexToBit(), TeamBalance_CompareTeams(), TeamBalance_FindBestTeams(), TeamBalance_IsTeamAllowedInternal(), TEAMS_COMPARE_EQUAL, and TEAMS_COMPARE_LESS.
Referenced by ClientCommand_selectteam(), Player_SetTeamIndexChecked(), TeamBalance_FindBestTeam(), and TeamBalance_FindBestTeams().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_FindBestTeams: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state != TEAM_BALANCE_TEAM_COUNTS_FILLED)
     {
         LOG_FATAL("TeamBalance_FindBestTeams: "
             "TeamBalance_GetTeamCounts has not been called.");
     }
     if (MUTATOR_CALLHOOK(TeamBalance_FindBestTeams, player) == true)
     {
         return M_ARGV(1, float);
     }
     int team_bits = 0;
     int previous_team = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (!TeamBalance_IsTeamAllowedInternal(balance, i))
         {
             continue;
         }
         if (previous_team == 0)
         {
             team_bits = Team_IndexToBit(i);
             previous_team = i;
             continue;
         }
         int compare = TeamBalance_CompareTeams(balance, i, previous_team,
             player, use_score);
         if (compare == TEAMS_COMPARE_LESS)
         {
             team_bits = Team_IndexToBit(i);
             previous_team = i;
             continue;
         }
         if (compare == TEAMS_COMPARE_EQUAL)
         {
             team_bits |= Team_IndexToBit(i);
             previous_team = i;
         }
     }
     return team_bits;
 }
int TeamBalance_GetAllowedTeams (entity balance)
Returns the bitmask of allowed teams.
Parameters
[in] balance Team balance entity.
Returns
Bitmask of allowed teams.
Definition at line 609 of file teamplay.qc.
References LOG_FATAL, NULL, NUM_TEAMS, result, TEAM_BALANCE_UNINITIALIZED, Team_IndexToBit(), and TeamBalance_IsTeamAllowedInternal().
Referenced by ClientConnect(), dom_DelayedInit(), ons_ScoreRules(), and ScoreRules_generic().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_GetAllowedTeams: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state == TEAM_BALANCE_UNINITIALIZED)
     {
         LOG_FATAL("TeamBalance_GetAllowedTeams: "
             "Team balance entity is not initialized.");
     }
     int result = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (TeamBalance_IsTeamAllowedInternal(balance, i))
         {
             result |= Team_IndexToBit(i);
         }
     }
     return result;
 }
int TeamBalance_GetLargestTeamIndex (entity balance, int teams)
Returns the index of the team with most players that is contained in the given bitmask of teams.
Parameters
[in] balance Team balance entity.
[in] teams Bitmask of teams to search in.
Returns
Index of the team with most players.
Definition at line 936 of file teamplay.qc.
References entity(), NUM_TEAMS, Team_IndexToBit(), TeamBalance_GetTeamFromIndex(), TeamBalanceTeam_GetNumberOfPlayers(), and TeamBalanceTeam_IsAllowed().
Referenced by TeamBalance_AutoBalanceBots().
 {
     int largest_team_index = 0;
     int largest_team_player_count = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if (!(Team_IndexToBit(i) & teams))
         {
             continue;
         }
         entity team_ = TeamBalance_GetTeamFromIndex(balance, i);
         if (!TeamBalanceTeam_IsAllowed(team_))
         {
             continue;
         }
         int playercount = TeamBalanceTeam_GetNumberOfPlayers(team_);
         if (largest_team_index == 0)
         {
             largest_team_index = i;
             largest_team_player_count = playercount;
         }
         else if (playercount > largest_team_player_count)
         {
             largest_team_index = i;
             largest_team_player_count = playercount;
         }
     }
     return largest_team_index;
 }
int TeamBalance_GetNumberOfPlayers (entity balance, int index)
Returns the number of players (both humans and bots) in a team.
Parameters
[in] balance Team balance entity.
[in] index Index of the team.
Returns
Number of player (both humans and bots) in a team.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 732 of file teamplay.qc.
References LOG_FATAL, LOG_FATALF, NULL, TEAM_BALANCE_TEAM_COUNTS_FILLED, and Team_IsValidIndex().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_GetNumberOfPlayers: "
             "Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state != TEAM_BALANCE_TEAM_COUNTS_FILLED)
     {
         LOG_FATAL("TeamBalance_GetNumberOfPlayers: "
             "TeamBalance_GetTeamCounts has not been called.");
     }
     if (!Team_IsValidIndex(index))
     {
         LOG_FATALF("TeamBalance_GetNumberOfPlayers: Team index is invalid: %f",
             index);
     }
     return balance.m_team_balance_team[index - 1].m_num_players;
 }
entity TeamBalance_GetPlayerForTeamSwitch (int source_team_index, int destination_team_index, bool is_bot)
Returns the player who is the most suitable for switching between the given teams.
Parameters
[in] source_team_index Index of the team to search in.
[in] destination_team_index Index of the team to switch to.
[in] is_bot True to search for bot, false for human.
Returns
Player who is the most suitable for switching between the given teams or NULL if not found.
Definition at line 966 of file teamplay.qc.
References entity(), Entity_GetTeamIndex(), FLOAT_MAX, FOREACH_CLIENT, IS_BOT_CLIENT, M_ARGV, MUTATOR_CALLHOOK, NULL, PlayerScore_Get, TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetPlayerForTeamSwitch(), and TeamBalance_IsTeamAllowed().
Referenced by TeamBalance_AutoBalanceBots(), and TeamBalance_GetPlayerForTeamSwitch().
 {
     if (MUTATOR_CALLHOOK(TeamBalance_GetPlayerForTeamSwitch, source_team_index,
         destination_team_index, is_bot))
     {
         return M_ARGV(3, entity);
     }
     entity lowest_player = NULL;
     float lowest_score = FLOAT_MAX;
     FOREACH_CLIENT(Entity_GetTeamIndex(it) == source_team_index,
     {
         if (IS_BOT_CLIENT(it) != is_bot)
         {
             continue;
         }
         float temp_score = PlayerScore_Get(it, SP_SCORE);
         if (temp_score >= lowest_score)
         {
             continue;
         }
         //PrintToChatAll(sprintf(
         //  "Found %s with lowest score, checking allowed teams", it.netname));
         entity balance = TeamBalance_CheckAllowedTeams(it);
         if (TeamBalance_IsTeamAllowed(balance, source_team_index))
         {
             //PrintToChatAll("Allowed");
             lowest_player = it;
             lowest_score = temp_score;
         }
         else
         {
             //PrintToChatAll("Not allowed");
         }
         TeamBalance_Destroy(balance);
     });
     return lowest_player;
 }
entity TeamBalance_GetTeam (entity balance, int team_num)
Returns the team entity of the team balance entity that corresponds to the given TEAM_NUM value.
Parameters
[in] balance Team balance entity.
[in] team_num Team value. See TEAM_NUM constants.
Returns
Team entity of the team balance entity that corresponds to the given TEAM_NUM value.
Definition at line 1058 of file teamplay.qc.
References Team_TeamToIndex(), and TeamBalance_GetTeamFromIndex().
Referenced by TeamBalance_CheckAllowedTeams(), and TeamBalance_GetTeamCounts().
 {
     return TeamBalance_GetTeamFromIndex(balance, Team_TeamToIndex(team_num));
 }
void TeamBalance_GetTeamCounts (entity balance, entity ignore)
Counts the number of players and various other information about each team.
Parameters
[in,out] balance Team balance entity.
[in] ignore Player to ignore. This is useful if you plan to switch the player's team. Pass NULL for global information.
Note
This function updates the internal state of the team balance entity.
Definition at line 650 of file teamplay.qc.
References entity(), FOREACH_CLIENT, IS_BOT_CLIENT, IS_CLIENT, LOG_FATAL, M_ARGV, MUTATOR_CALLHOOK, NULL, NUM_TEAMS, Player_HasRealForcedTeam(), TEAM_BALANCE_UNINITIALIZED, Team_IndexToTeam(), Team_IsValidTeam(), TeamBalance_GetTeam(), TeamBalance_GetTeamCounts(), TeamBalance_GetTeamFromIndex(), and TeamBalanceTeam_IsAllowed().
Referenced by bot_removefromlargestteam(), ClientCommand_selectteam(), Player_SetTeamIndexChecked(), TeamBalance_AutoBalanceBots(), TeamBalance_FindBestTeam(), and TeamBalance_GetTeamCounts().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_GetTeamCounts: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state == TEAM_BALANCE_UNINITIALIZED)
     {
         LOG_FATAL("TeamBalance_GetTeamCounts: "
             "Team balance entity is not initialized.");
     }
     if (MUTATOR_CALLHOOK(TeamBalance_GetTeamCounts) == true)
     {
         // Mutator has overriden the configuration.
         for (int i = 1; i <= NUM_TEAMS; ++i)
         {
             entity team_ent = TeamBalance_GetTeamFromIndex(balance, i);
             if (TeamBalanceTeam_IsAllowed(team_ent))
             {
                 MUTATOR_CALLHOOK(TeamBalance_GetTeamCount, i, ignore);
                 team_ent.m_num_players = M_ARGV(2, float);
                 team_ent.m_num_bots = M_ARGV(3, float);
             }
         }
     }
     else
     {
         // Manually count all players.
         FOREACH_CLIENT(true,
         {
             if (it == ignore)
             {
                 continue;
             }
             int team_num;
             // TODO: Reconsider when the player is truly on the team.
             if (IS_CLIENT(it) || (it.caplayer))
             {
                 team_num = it.team;
             }
             else if (Player_HasRealForcedTeam(it))
             {
                 // Do we really need this? Probably not.
                 team_num = Team_IndexToTeam(it.team_forced); // reserve the spot
             }
             else
             {
                 continue;
             }
             if (!Team_IsValidTeam(team_num))
             {
                 continue;
             }
             entity team_ent = TeamBalance_GetTeam(balance, team_num);
             if (!TeamBalanceTeam_IsAllowed(team_ent))
             {
                 continue;
             }
             ++team_ent.m_num_players;
             if (IS_BOT_CLIENT(it))
             {
                 ++team_ent.m_num_bots;
             }
         });
     }
     // if the player who has a forced team has not joined yet, reserve the spot
     if (autocvar_g_campaign)
     {
         if (Team_IsValidIndex(autocvar_g_campaign_forceteam))
         {
             entity team_ent = TeamBalance_GetTeamFromIndex(balance,
                 autocvar_g_campaign_forceteam);
             if (team_ent.m_num_players == team_ent.m_num_bots)
             {
                 ++team_ent.m_num_players;
             }
         }
     }
     balance.m_team_balance_state = TEAM_BALANCE_TEAM_COUNTS_FILLED;
 }
entity TeamBalance_GetTeamFromIndex (entity balance, int index)
Returns the team entity of the team balance entity at the given index.
Parameters
[in] balance Team balance entity.
[in] index Index of the team.
Returns
Team entity of the team balance entity at the given index.
Definition at line 1049 of file teamplay.qc.
References LOG_FATALF, and Team_IsValidIndex().
Referenced by TeamBalance_AutoBalanceBots(), TeamBalance_CompareTeams(), TeamBalance_GetLargestTeamIndex(), TeamBalance_GetTeam(), and TeamBalance_GetTeamCounts().
 {
     if (!Team_IsValidIndex(index))
     {
         LOG_FATALF("TeamBalance_GetTeamFromIndex: Index is invalid: %f", index);
     }
     return balance.m_team_balance_team[index - 1];
 }
bool TeamBalance_IsTeamAllowed (entity balance, int index)
Returns whether the team change to the specified team is allowed.
Parameters
[in] balance Team balance entity.
[in] index Index of the team.
Returns
True if team change to the specified team is allowed, false otherwise.
Definition at line 631 of file teamplay.qc.
References LOG_FATAL, LOG_FATALF, NULL, TEAM_BALANCE_UNINITIALIZED, Team_IsValidIndex(), and TeamBalance_IsTeamAllowedInternal().
Referenced by GameCommand_moveplayer(), GameCommand_shuffleteams(), and TeamBalance_GetPlayerForTeamSwitch().
 {
     if (balance == NULL)
     {
         LOG_FATAL("TeamBalance_IsTeamAllowed: Team balance entity is NULL.");
     }
     if (balance.m_team_balance_state == TEAM_BALANCE_UNINITIALIZED)
     {
         LOG_FATAL("TeamBalance_IsTeamAllowed: "
             "Team balance entity is not initialized.");
     }
     if (!Team_IsValidIndex(index))
     {
         LOG_FATALF("TeamBalance_IsTeamAllowed: Team index is invalid: %f",
             index);
     }
     return TeamBalance_IsTeamAllowedInternal(balance, index);
 }
bool TeamBalance_IsTeamAllowedInternal (entity balance, int index)
Returns whether the team change to the specified team is allowed.
Parameters
[in] balance Team balance entity.
[in] index Index of the team.
Returns
True if team change to the specified team is allowed, false otherwise.
Note
This function bypasses all the sanity checks.
Definition at line 1032 of file teamplay.qc.
References TEAM_NOT_ALLOWED.
Referenced by Player_SetTeamIndexChecked(), TeamBalance_CheckAllowedTeams(), TeamBalance_FindBestTeams(), TeamBalance_GetAllowedTeams(), TeamBalance_IsTeamAllowed(), and TeamBalance_JoinBestTeam().
 {
     return balance.m_team_balance_team[index - 1].m_num_players !=
         TEAM_NOT_ALLOWED;
 }
void TeamBalance_JoinBestTeam (entity player)
Assigns the given player to a team that will make the game most balanced.
Parameters
[in,out] player Player to assign.
Definition at line 420 of file teamplay.qc.
References entity(), Player_HasRealForcedTeam(), SetPlayerTeam(), TEAM_CHANGE_AUTO, TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_FindBestTeam(), TeamBalance_IsTeamAllowedInternal(), and teamplay.
Referenced by bot_clientconnect(), ClientKill_Now_TeamChange(), Join(), and PutPlayerInServer().
 {
     //PrintToChatAll(sprintf("TeamBalance_JoinBestTeam: %s", player.netname));
     if (!teamplay)
     {
         return;
     }
     if (player.bot_forced_team)
     {
         return;
     }
     entity balance = TeamBalance_CheckAllowedTeams(player);
     if (Player_HasRealForcedTeam(player))
     {
         int forced_team_index = player.team_forced;
         bool is_team_allowed = TeamBalance_IsTeamAllowedInternal(balance,
             forced_team_index);
         TeamBalance_Destroy(balance);
         if (!is_team_allowed)
         {
             return;
         }
         if (!SetPlayerTeam(player, forced_team_index, TEAM_CHANGE_AUTO))
         {
             return;
         }
         return;
     }
     int best_team_index = TeamBalance_FindBestTeam(balance, player, true);
     TeamBalance_Destroy(balance);
     if (!SetPlayerTeam(player, best_team_index, TEAM_CHANGE_AUTO))
     {
         return;
     }
 }
int TeamBalanceTeam_GetNumberOfBots (entity team_ent)
Returns the number of bots in a team.
Parameters
[in] team_ent Team entity.
Returns
Number of bots in a team.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 1073 of file teamplay.qc.
 {
     return team_ent.m_num_bots;
 }
int TeamBalanceTeam_GetNumberOfPlayers (entity team_ent)
Returns the number of players (both humans and bots) in a team.
Parameters
[in] team_ent Team entity.
Returns
Number of player (both humans and bots) in a team.
Note
You need to call TeamBalance_GetTeamCounts before calling this function.
Definition at line 1068 of file teamplay.qc.
Referenced by TeamBalance_AutoBalanceBots(), and TeamBalance_GetLargestTeamIndex().
 {
     return team_ent.m_num_players;
 }
bool TeamBalanceTeam_IsAllowed (entity team_ent)
Returns whether the team is allowed.
Parameters
[in] team_ent Team entity.
Returns
True if team is allowed, false otherwise.
Definition at line 1063 of file teamplay.qc.
References TEAM_NOT_ALLOWED.
Referenced by TeamBalance_AutoBalanceBots(), TeamBalance_CompareTeamsInternal(), TeamBalance_GetLargestTeamIndex(), and TeamBalance_GetTeamCounts().
 {
     return team_ent.m_num_players != TEAM_NOT_ALLOWED;
 }
Variable Documentation
string autocvar_g_forced_team_blue
Definition at line 43 of file teamplay.qc.
Referenced by Player_DetermineForcedTeam().
string autocvar_g_forced_team_pink
Definition at line 45 of file teamplay.qc.
Referenced by Player_DetermineForcedTeam().
string autocvar_g_forced_team_red
Definition at line 42 of file teamplay.qc.
Referenced by Player_DetermineForcedTeam().
string autocvar_g_forced_team_yellow
Definition at line 44 of file teamplay.qc.
Referenced by Player_DetermineForcedTeam().
entity g_team_entities[NUM_TEAMS]
Holds global team entities.
Definition at line 47 of file teamplay.qc.
Referenced by STATIC_INIT(), Team_GetNumberOfAliveTeams(), Team_GetNumberOfTeamsWithControlPoints(), Team_GetTeam(), Team_GetTeamFromIndex(), and TeamBalance_CheckAllowedTeams().
int m_num_bots
Number of bots in a team.
Definition at line 38 of file teamplay.qc.
int m_num_control_points
Number of control points owned by a team.
Definition at line 40 of file teamplay.qc.
Referenced by Team_GetNumberOfTeamsWithControlPoints().
int m_num_players
Number of players (both humans and bots) in a team.
Definition at line 37 of file teamplay.qc.
int m_num_players_alive
Number of alive players in a team.
Definition at line 39 of file teamplay.qc.
Referenced by Team_GetNumberOfAliveTeams().
int m_team_balance_state
Holds the state of the team balance entity.
Definition at line 33 of file teamplay.qc.
entity m_team_balance_team[NUM_TEAMS]
???
Definition at line 34 of file teamplay.qc.
float m_team_score
The score of the team.
Definition at line 36 of file teamplay.qc.
float team_forced
Definition at line 31 of file teamplay.qc.
const int TEAM_NOT_ALLOWED = -1
Indicates that the player is not allowed to join a team.
Definition at line 29 of file teamplay.qc.
Referenced by TeamBalance_BanTeamsExcept(), TeamBalance_CheckAllowedTeams(), TeamBalance_IsTeamAllowedInternal(), and TeamBalanceTeam_IsAllowed().