Xonotic: Dialog Class Reference
Dialog Class Reference
Public Member Functions
virtual void _changeFocusXY ()
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
virtual void addItemSimple ()
virtual void close ()
virtual void configureDialog ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void fill ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void gotoRC ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFirstColumn ()
virtual void setFocus ()
virtual void showNotify ()
virtual void TD ()
virtual void TDempty ()
virtual void TDNoMargin ()
virtual void toString ()
virtual void TR ()
Public Attributes
float allowFocusSound = 0
string backgroundImage = string_null
float borderLines = 1
float closable = 1
entity closeButton = NULL
string closeButtonImage = string_null
vector color = '1 0.5 1'
float columns = 2
float columnSpacing = 0
float currentColumn = 0
float currentRow = 0
entity firstChild = NULL
float firstColumn = 0
float focusable = 0
float focused = 0
entity focusedChild = NULL
entity frame = NULL
float intendedHeight = 0
float intendedWidth = 0
float isTabRoot = 1
vector itemOrigin = '0 0 0'
vector itemSize = '0 0 0'
vector itemSpacing = '0 0 0'
entity lastChild = NULL
float marginBottom = 0
float marginLeft = 0
float marginRight = 0
float marginTop = 0
entity mouseFocusedChild = NULL
vector origin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float requiresConnection = 0
float rowHeight = 0
float rows = 3
float rowSpacing = 0
entity savedFocus = NULL
float shown = 0
vector size = '0 0 0'
string title = "Form1"
float titleFontSize = 0
float titleHeight = 0
string tooltip = string_null
float zoomedOutTitleBar = 0
float zoomedOutTitleBarPosition = 0
Detailed Description
Definition at line 19 of file dialog.qh.
Member Function Documentation
virtual void InputContainer::_changeFocusXY () virtual inherited
virtual void Container::addItem () virtual inherited
Reimplemented in ModalController, and Nexposee.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
virtual void Dialog::addItemSimple () virtual
virtual void Dialog::close () virtual
Reimplemented in XonoticRootDialog, XonoticScreenshotViewerDialog, and XonoticMutatorsDialog.
virtual void Dialog::configureDialog () virtual
Reimplemented in XonoticDialog.
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Container::draw () virtual inherited
Reimplemented from Item.
Reimplemented in ModalController, MainWindow, XonoticProfileTab, and Nexposee.
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
virtual void Dialog::fill () virtual
Reimplemented in XonoticGameSettingsTab, XonoticScreenshotViewerDialog, XonoticMutatorsDialog, XonoticUserbindEditDialog, XonoticCreditsDialog, XonoticFirstRunDialog, XonoticHUDAmmoDialog, XonoticHUDCenterprintDialog, XonoticHUDChatDialog, XonoticHUDEngineInfoDialog, XonoticHUDHealthArmorDialog, XonoticHUDInfoMessagesDialog, XonoticHUDItemsTimeDialog, XonoticHUDModIconsDialog, XonoticHUDNotificationDialog, XonoticHUDPhysicsDialog, XonoticHUDPowerupsDialog, XonoticHUDPressedKeysDialog, XonoticHUDQuickMenuDialog, XonoticHUDRaceTimerDialog, XonoticHUDRadarDialog, XonoticHUDScoreDialog, XonoticHUDTimerDialog, XonoticHUDVoteDialog, XonoticHUDWeaponsDialog, XonoticHUDExitDialog, XonoticMonsterToolsDialog, XonoticMultiplayerDialog, XonoticServerCreateTab, XonoticMapInfoDialog, XonoticServerListTab, XonoticServerInfoDialog, XonoticMediaTab, XonoticDemoBrowserTab, XonoticDemoStartConfirmDialog, XonoticDemoTimeConfirmDialog, XonoticMusicPlayerTab, XonoticScreenshotBrowserTab, XonoticProfileTab, XonoticQuitDialog, XonoticSandboxToolsDialog, XonoticSettingsDialog, XonoticAudioSettingsTab, XonoticEffectsSettingsTab, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticHUDConfirmDialog, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticInputSettingsTab, XonoticMiscSettingsTab, XonoticCvarsDialog, XonoticResetDialog, XonoticUserSettingsTab, XonoticLanguageWarningDialog, XonoticVideoSettingsTab, XonoticSingleplayerDialog, XonoticWinnerDialog, XonoticTeamSelectDialog, and XonoticUid2NameDialog.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void InputContainer::focusLeave () virtual inherited
Reimplemented from Container.
virtual void Dialog::gotoRC () virtual
virtual void Container::hideNotify () virtual inherited
Reimplemented from Item.
virtual void Container::itemFromPoint () virtual inherited
virtual void Dialog::keyDown () virtual
Reimplemented from InputContainer.
Reimplemented in XonoticScreenshotViewerDialog.
virtual void Container::keyUp () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual inherited
virtual void InputContainer::mouseDrag () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseMove () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mousePress () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseRelease () virtual inherited
Reimplemented from Container.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void InputContainer::resizeNotify () virtual inherited
Reimplemented from Container.
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Dialog::setFirstColumn () virtual
virtual void Container::setFocus () virtual inherited
virtual void Container::showNotify () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticTab, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
virtual void Dialog::TD () virtual
virtual void Dialog::TDempty () virtual
virtual void Dialog::TDNoMargin () virtual
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void Dialog::TR () virtual
Member Data Documentation
float Item::allowFocusSound = 0 inherited
Definition at line 24 of file item.qh.
string Dialog::backgroundImage = string_null
Definition at line 65 of file dialog.qh.
float Dialog::borderLines = 1
Definition at line 66 of file dialog.qh.
float Dialog::closable = 1
Definition at line 44 of file dialog.qh.
entity Dialog::closeButton = NULL
Definition at line 34 of file dialog.qh.
string Dialog::closeButtonImage = string_null
Definition at line 67 of file dialog.qh.
vector Dialog::color = '1 0.5 1'
Definition at line 46 of file dialog.qh.
float Dialog::columns = 2
Definition at line 49 of file dialog.qh.
float Dialog::columnSpacing = 0
Definition at line 55 of file dialog.qh.
float Dialog::currentColumn = 0
Definition at line 40 of file dialog.qh.
float Dialog::currentRow = 0
Definition at line 39 of file dialog.qh.
entity Container::firstChild = NULL inherited
Definition at line 29 of file container.qh.
float Dialog::firstColumn = 0
Definition at line 41 of file dialog.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
entity Container::focusedChild = NULL inherited
Definition at line 31 of file container.qh.
entity Dialog::frame = NULL
Definition at line 69 of file dialog.qh.
float Dialog::intendedHeight = 0
Definition at line 35 of file dialog.qh.
float Dialog::intendedWidth = 0
Definition at line 47 of file dialog.qh.
float Dialog::isTabRoot = 1
Definition at line 33 of file dialog.qh.
vector Dialog::itemOrigin = '0 0 0'
Definition at line 36 of file dialog.qh.
vector Dialog::itemSize = '0 0 0'
Definition at line 37 of file dialog.qh.
vector Dialog::itemSpacing = '0 0 0'
Definition at line 38 of file dialog.qh.
entity Container::lastChild = NULL inherited
Definition at line 30 of file container.qh.
float Dialog::marginBottom = 0
Definition at line 52 of file dialog.qh.
float Dialog::marginLeft = 0
Definition at line 53 of file dialog.qh.
float Dialog::marginRight = 0
Definition at line 54 of file dialog.qh.
float Dialog::marginTop = 0
Definition at line 51 of file dialog.qh.
entity InputContainer::mouseFocusedChild = NULL inherited
Definition at line 14 of file inputcontainer.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Dialog::requiresConnection = 0
Definition at line 63 of file dialog.qh.
float Dialog::rowHeight = 0
Definition at line 57 of file dialog.qh.
float Dialog::rows = 3
Definition at line 48 of file dialog.qh.
float Dialog::rowSpacing = 0
Definition at line 56 of file dialog.qh.
entity Container::savedFocus = NULL inherited
Definition at line 32 of file container.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
string Dialog::title = "Form1"
Definition at line 45 of file dialog.qh.
float Dialog::titleFontSize = 0
Definition at line 59 of file dialog.qh.
float Dialog::titleHeight = 0
Definition at line 58 of file dialog.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
float Dialog::zoomedOutTitleBar = 0
Definition at line 61 of file dialog.qh.
float Dialog::zoomedOutTitleBarPosition = 0
Definition at line 60 of file dialog.qh.
The documentation for this class was generated from the following file:
menu/item/dialog.qh