Xonotic: server/spawnpoints.qh File Reference
spawnpoints.qh File Reference
Functions
entity SelectSpawnPoint (entity this, bool anypoint)
entity Spawn_FilterOutBadSpots (entity this, entity firstspot, float mindist, float teamcheck)
bool SpawnEvent_Send (entity this, entity to, int sf)
spawnfunc (info_player_deathmatch)
void spawnpoint_use (entity this, entity actor, entity trigger)
Variables
const int SPAWN_PRIO_GOOD_DISTANCE = 10
const int SPAWN_PRIO_NEAR_TEAMMATE_FOUND = 200
const int SPAWN_PRIO_NEAR_TEAMMATE_SAMETEAM = 100
const int SPAWN_PRIO_RACE_PREVIOUS_SPAWN = 50
float spawnpoint_nag
vector spawnpoint_score
Function Documentation
entity SelectSpawnPoint (entity this, bool anypoint)
Definition at line 333 of file spawnpoints.qc.
References autocvar_g_spawn_furthest, autocvar_g_spawn_useallspawns, autocvar_spawn_debug, BIT, classname, entity(), error, find(), g_spawnpoints, GotoNextMap(), have_team_spawns, have_team_spawns_forteams, IL_EACH, IL_FIRST, NULL, prev, random(), some_spawn_has_been_used, Spawn_FilterOutBadSpots(), Spawn_WeightedPoint(), team, testspawn_checked, and testspawn_point.
Referenced by buff_Respawn(), Damage(), ka_RespawnBall(), PutObserverInServer(), and PutPlayerInServer().
 {
     float teamcheck;
     entity spot = NULL;
     if(!testspawn_checked)
     {
         testspawn_point = find(NULL, classname, "testplayerstart");
         testspawn_checked = true;
     }
     if(testspawn_point)
         return testspawn_point;
     if(this.spawnpoint_targ)
         return this.spawnpoint_targ;
     if(anypoint || autocvar_g_spawn_useallspawns)
         teamcheck = -1;
     else if(have_team_spawns > 0)
     {
         if(!(have_team_spawns_forteams & BIT(this.team)))
         {
             // we request a spawn for a team, and we have team
             // spawns, but that team has no spawns?
             if(have_team_spawns_forteams & BIT(0))
                 // try noteam spawns
                 teamcheck = 0;
             else
                 // if not, any spawn has to do
                 teamcheck = -1;
         }
         else
             teamcheck = this.team; // MUST be team
     }
     else if(have_team_spawns == 0 && (have_team_spawns_forteams & BIT(0)))
         teamcheck = 0; // MUST be noteam
     else
         teamcheck = -1;
         // if we get here, we either require team spawns but have none, or we require non-team spawns and have none; use any spawn then
     // get the entire list of spots
     //entity firstspot = findchain(classname, "info_player_deathmatch");
     entity firstspot = IL_FIRST(g_spawnpoints);
     entity prev = NULL;
     IL_EACH(g_spawnpoints, true,
     {
         if(prev)
             prev.chain = it;
         it.chain = NULL;
         prev = it;
     });
     // filter out the bad ones
     // (note this returns the original list if none survived)
     if(anypoint)
     {
         spot = Spawn_WeightedPoint(firstspot, 1, 1, 1);
     }
     else
     {
         firstspot = Spawn_FilterOutBadSpots(this, firstspot, 100, teamcheck);
         // there is 50/50 chance of choosing a random spot or the furthest spot
         // (this means that roughly every other spawn will be furthest, so you
         // usually won't get fragged at spawn twice in a row)
         if (random() > autocvar_g_spawn_furthest)
             spot = Spawn_WeightedPoint(firstspot, 1, 1, 1);
         else
             spot = Spawn_WeightedPoint(firstspot, 1, 5000, 5); // chooses a far far away spawnpoint
     }
     if (!spot)
     {
         if(autocvar_spawn_debug)
             GotoNextMap(0);
         else
         {
             if(some_spawn_has_been_used)
                 return NULL; // team can't spawn any more, because of actions of other team
             else
                 error("Cannot find a spawn point - please fix the map!");
         }
     }
     return spot;
 }
entity Spawn_FilterOutBadSpots (entity this, entity firstspot, float mindist, float teamcheck)
Definition at line 285 of file spawnpoints.qc.
References entity(), NULL, and Spawn_ScoreAll().
Referenced by SelectSpawnPoint(), and trigger_race_checkpoint_verify().
 {
     entity spot, spotlist, spotlistend;
     spotlist = NULL;
     spotlistend = NULL;
     Spawn_ScoreAll(this, firstspot, mindist, teamcheck);
     for(spot = firstspot; spot; spot = spot.chain)
     {
         if(spot.spawnpoint_score.x >= 0) // spawning allowed here
         {
             if(spotlistend)
                 spotlistend.chain = spot;
             spotlistend = spot;
             if(!spotlist)
                 spotlist = spot;
         }
     }
     if(spotlistend)
         spotlistend.chain = NULL;
     return spotlist;
 }
bool SpawnEvent_Send (entity this, entity to, int sf)
Definition at line 28 of file spawnpoints.qc.
References autocvar_g_spawn_alloweffects, etof(), IS_SPEC, owner, and WriteByte().
Referenced by PutPlayerInServer().
 {
     float send;
     WriteHeader(MSG_ENTITY, ENT_CLIENT_SPAWNEVENT);
     if(autocvar_g_spawn_alloweffects)
     {
         WriteByte(MSG_ENTITY, etof(this.owner));
         WriteVector(MSG_ENTITY, this.owner.origin);
         send = true;
     }
     else if((to == this.owner) || (IS_SPEC(to) && (to.enemy == this.owner)) )
     {
         WriteByte(MSG_ENTITY, 0);
         send = true;
     }
     else { send = false; }
     return send;
 }
spawnfunc (info_player_deathmatch)
Definition at line 169 of file spawnpoints.qc.
References classname, g_spawnpoints, IL_PUSH(), and relocate_spawnpoint().
 {
     this.classname = "info_player_deathmatch";
     IL_PUSH(g_spawnpoints, this);
     relocate_spawnpoint(this);
 }
void spawnpoint_use (entity this, entity actor, entity trigger)
Definition at line 61 of file spawnpoints.qc.
References have_team_spawns, some_spawn_has_been_used, team, and teamplay.
Referenced by relocate_spawnpoint().
 {
     if(teamplay)
     if(have_team_spawns > 0)
     {
         this.team = actor.team;
         some_spawn_has_been_used = true;
     }
     //LOG_INFO("spawnpoint was used!\n");
 }
Variable Documentation
const int SPAWN_PRIO_GOOD_DISTANCE = 10
Definition at line 7 of file spawnpoints.qh.
Referenced by Spawn_Score().
const int SPAWN_PRIO_NEAR_TEAMMATE_FOUND = 200
Definition at line 4 of file spawnpoints.qh.
Referenced by MUTATOR_HOOKFUNCTION().
const int SPAWN_PRIO_NEAR_TEAMMATE_SAMETEAM = 100
Definition at line 5 of file spawnpoints.qh.
Referenced by MUTATOR_HOOKFUNCTION().
const int SPAWN_PRIO_RACE_PREVIOUS_SPAWN = 50
Definition at line 6 of file spawnpoints.qh.
Referenced by trigger_race_checkpoint_spawn_evalfunc().
float spawnpoint_nag
Definition at line 10 of file spawnpoints.qh.
Referenced by relocate_spawnpoint().
vector spawnpoint_score
Definition at line 9 of file spawnpoints.qh.