Xonotic: lib/promise.qc File Reference
promise.qc File Reference
#include "promise.qh"
Enumerations
enum { PROMISE_PENDING, PROMISE_RESOLVED, PROMISE_REJECTED }
Functions
void _Promise_done (Promise this, Promise(Promise ret, entity result, entity userdata) onResolve, Promise(Promise ret, entity err, entity userdata) onReject, Promise ret, entity userdata)
void _Promise_finalize (Promise this)
void _Promise_handle (Promise this, PromiseHandler h)
Promise _Promise_onReject_default (Promise ret, entity err, entity userdata)
Promise _Promise_onResolve_default (Promise ret, entity result, entity userdata)
Promise _Promise_then (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onResolve, Promise(Promise ret, entity result, entity userdata) onReject, entity userdata)
classfield (Promise).int _promise_state
classfield (PromiseHandler).Promise _promise_handler_ret
entityclass (PromiseHandler)
Promise Promise_catch_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onReject, entity userdata)
Promise Promise_new_ (Promise this)
void Promise_reject (Promise this)
notify all Promise_catch subscribers that this promise has rejected
void Promise_resolve (Promise this)
notify all Promise_then subscribers that this promise has resolved
Promise Promise_sleep (float n)
Promise Promise_then_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onResolve, entity userdata)
entity REF (entity this)
void ref_init (entity this, int init, void(entity this) finalize)
entity unref (Promise this)
void (entity this) _ref_finalize
Variables
entity entity userdata _promise_handler_reject
entity entity userdata _promise_handler_resolve
int _ref_count
entity err
entity result
Enumeration Type Documentation
anonymous enum
Enumerator
PROMISE_PENDING
PROMISE_RESOLVED
PROMISE_REJECTED
Definition at line 30 of file promise.qc.
      {
     PROMISE_PENDING,
     PROMISE_RESOLVED,
     PROMISE_REJECTED,
 };
Function Documentation
void _Promise_done (Promise this, Promise(Promise ret, entity result, entity userdata) onResolve, Promise(Promise ret, entity err, entity userdata) onReject, Promise ret, entity userdata)
Definition at line 132 of file promise.qc.
References _Promise_handle(), and new_pure.
Referenced by _Promise_then().
 {
     PromiseHandler h = new_pure(PromiseHandler);
     h._promise_handler_ret = ret;
     h._promise_handler_data = userdata;
     h._promise_handler_resolve = onResolve;
     h._promise_handler_reject = onReject;
     _Promise_handle(this, h);
 }
void _Promise_finalize (Promise this)
Definition at line 46 of file promise.qc.
Referenced by Promise_new_().
 {
     delete(this);
 }
void _Promise_handle (Promise this, PromiseHandler h)
Definition at line 106 of file promise.qc.
References _Promise_then(), func_null(), IL_NEW, IL_PUSH(), NULL, p, PROMISE_PENDING, PROMISE_REJECTED, and PROMISE_RESOLVED.
Referenced by _Promise_done(), Promise_reject(), and Promise_resolve().
 {
     switch (this._promise_state) {
         case PROMISE_PENDING:
             if (!this._promise_handlers) {
                 this._promise_handlers = IL_NEW();
             }
             IL_PUSH(this._promise_handlers, h);
             break;
         case PROMISE_RESOLVED: {
             Promise ret = h._promise_handler_ret;
             Promise p = h._promise_handler_resolve(ret, this._promise_result, h._promise_handler_data);
             if (p != ret) _Promise_then(p, ret, func_null, func_null, NULL); // bind p -> ret
             delete(h);
             break;
         }
         case PROMISE_REJECTED: {
             Promise ret = h._promise_handler_ret;
             Promise p = h._promise_handler_reject(ret, this._promise_result, h._promise_handler_data);
             if (p != ret) _Promise_then(p, ret, func_null, func_null, NULL); // bind p -> ret
             delete(h);
             break;
         }
     }
 }
Promise _Promise_onReject_default (Promise ret, entity err, entity userdata)
Definition at line 155 of file promise.qc.
References err, and Promise_reject().
Referenced by _Promise_then().
 {
     ret._promise_result = err;
     Promise_reject(ret);
     return ret;
 }
Promise _Promise_onResolve_default (Promise ret, entity result, entity userdata)
Definition at line 148 of file promise.qc.
References Promise_resolve(), and result.
Referenced by _Promise_then().
 {
     ret._promise_result = result;
     Promise_resolve(ret);
     return ret;
 }
Promise _Promise_then (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onResolve, Promise(Promise ret, entity result, entity userdata) onReject, entity userdata)
Definition at line 162 of file promise.qc.
References _Promise_done(), _Promise_onReject_default(), and _Promise_onResolve_default().
Referenced by _Promise_handle(), Promise_catch_(), and Promise_then_().
 {
     _Promise_done(
             this,
             (onResolve ? onResolve : _Promise_onResolve_default),
             (onReject ? onReject : _Promise_onReject_default),
             ret,
             userdata
     );
     return ret;
 }
classfield (Promise)
classfield (PromiseHandler)
entityclass (PromiseHandler)
Promise Promise_catch_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onReject, entity userdata)
Definition at line 191 of file promise.qc.
References _Promise_then(), func_null(), and unref().
 {
     unref(ret); // ret is a temporary
     return _Promise_then(this, ret, func_null, onReject, userdata);
 }
Promise Promise_new_ (Promise this)
Definition at line 51 of file promise.qc.
References _Promise_finalize(), and ref_init().
 {
     ref_init(this, 2, _Promise_finalize);
     this._promise_result = this; // promises default to being their own result to save on entities
     return this;
 }
void Promise_reject (Promise this)
notify all Promise_catch subscribers that this promise has rejected
Definition at line 79 of file promise.qc.
References _Promise_handle(), IL_DELETE, IL_EACH, LOG_SEVERE, LOG_SEVEREF, PROMISE_PENDING, PROMISE_REJECTED, and unref().
Referenced by _Promise_onReject_default().
 {
     if (!this) {
         LOG_SEVERE("Attempted to reject a null promise");
         return;
     }
     if (this._promise_state != PROMISE_PENDING) {
         LOG_SEVEREF("Rejected non-pending promise %i", this);
         return;
     }
     this._promise_state = PROMISE_REJECTED;
     if (this._promise_handlers) {
         IL_EACH(this._promise_handlers, true, _Promise_handle(this, it));
         IL_DELETE(this._promise_handlers);
     }
     unref(this);
     return;
 }
void Promise_resolve (Promise this)
notify all Promise_then subscribers that this promise has resolved
Definition at line 60 of file promise.qc.
References _Promise_handle(), IL_DELETE, IL_EACH, LOG_SEVERE, LOG_SEVEREF, PROMISE_PENDING, PROMISE_RESOLVED, and unref().
Referenced by _Promise_onResolve_default(), and Promise_sleep().
 {
     if (!this) {
         LOG_SEVERE("Attempted to resolve a null promise");
         return;
     }
     if (this._promise_state != PROMISE_PENDING) {
         LOG_SEVEREF("Resolved non-pending promise %i", this);
         return;
     }
     this._promise_state = PROMISE_RESOLVED;
     if (this._promise_handlers) {
         IL_EACH(this._promise_handlers, true, _Promise_handle(this, it));
         IL_DELETE(this._promise_handlers);
     }
     unref(this);
     return;
 }
Promise Promise_sleep (float n)
Definition at line 206 of file promise.qc.
References p, Promise_new, Promise_resolve(), setthink, time, and unref().
 {
     Promise p = unref(Promise_new());
     setthink(p, Promise_resolve);
     p.nextthink = time + n;
     return p;
 }
Promise Promise_then_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) onResolve, entity userdata)
Definition at line 180 of file promise.qc.
References _Promise_then(), func_null(), and unref().
 {
     unref(ret); // ret is a temporary
     return _Promise_then(this, ret, onResolve, func_null, userdata);
 }
entity REF (entity this)
Definition at line 13 of file promise.qc.
References _ref_count.
 {
     this._ref_count += 1;
     return this;
 }
void ref_init (entity this, int init, void(entity this) finalize)
Definition at line 6 of file promise.qc.
References _ref_count.
Referenced by Promise_new_().
 {
     this._ref_count = init;
     this._ref_finalize = finalize;
 }
entity unref (Promise this)
Definition at line 19 of file promise.qc.
References _ref_count, LOG_DEBUGF, NULL, and sourceLoc.
Referenced by Promise_catch_(), Promise_reject(), Promise_resolve(), Promise_sleep(), and Promise_then_().
 {
     this._ref_count -= 1;
     if (!this._ref_count) {
         LOG_DEBUGF("Finalize entity %i (from %s)", this, this.sourceLoc);
         this._ref_finalize(this);
         return NULL;
     }
     return this;
 }
void (entity this)
Variable Documentation
entity entity userdata _promise_handler_reject
Definition at line 44 of file promise.qc.
entity entity userdata _promise_handler_resolve
Definition at line 43 of file promise.qc.
int _ref_count
Definition at line 3 of file promise.qc.
Referenced by REF(), ref_init(), and unref().
entity err
Definition at line 44 of file promise.qc.
Referenced by _Promise_onReject_default().
entity result
Definition at line 43 of file promise.qc.
Referenced by _Promise_onResolve_default(), MapVote_CheckRules_2(), MapVote_Finished(), PlayerScore_Compare(), Team_GetNumberOfAliveTeams(), Team_GetNumberOfTeamsWithControlPoints(), TeamBalance_GetAllowedTeams(), TeamScore_Compare(), and W_RandomWeapons().