Xonotic: menu/xonotic/hudskinlist.qh File Reference
hudskinlist.qh File Reference
#include "listbox.qh"
Functions
METHOD (XonoticHUDSkinList, configureXonoticHUDSkinList, void(entity))
METHOD (XonoticHUDSkinList, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticHUDSkinList, draw, void(entity))
METHOD (XonoticHUDSkinList, drawListBoxItem, void(entity, int, vector, bool, bool))
METHOD (XonoticHUDSkinList, getHUDSkins, void(entity))
METHOD (XonoticHUDSkinList, setHUDSkin, void(entity))
METHOD (XonoticHUDSkinList, hudskinName, string(entity, float))
METHOD (XonoticHUDSkinList, hudskinPath, string(entity, float))
METHOD (XonoticHUDSkinList, hudskinTitle, string(entity, float))
METHOD (XonoticHUDSkinList, hudskinAuthor, string(entity, float))
METHOD (XonoticHUDSkinList, doubleClickListBoxItem, void(entity, float, vector))
METHOD (XonoticHUDSkinList, keyDown, float(entity, float, float, float))
METHOD (XonoticHUDSkinList, destroy, void(entity))
METHOD (XonoticHUDSkinList, showNotify, void(entity))
entity makeXonoticHUDSkinList ()
void SaveHUDSkin_Click (entity btn, entity me)
void SetHUDSkin_Click (entity btn, entity me)
void HUDSkinList_Filter_Change (entity box, entity me)
void HUDSkinList_Refresh_Click (entity btn, entity me)
void HUDSkinList_SavedName_Change (entity box, entity me)
Variables
entity hudskinlist
Function Documentation
void HUDSkinList_Filter_Change (entity box, entity me)
Definition at line 200 of file hudskinlist.qc.
References strcat(), string_null, strstrofs, strunzone(), and strzone().
Referenced by XonoticHUDExitDialog_fill().
 {
     if(me.filterString)
         strunzone(me.filterString);
     if(box.text != "")
     {
         if (strstrofs(box.text, "*", 0) >= 0 || strstrofs(box.text, "?", 0) >= 0)
             me.filterString = strzone(box.text);
         else
             me.filterString = strzone(strcat("*", box.text, "*"));
     }
     else
         me.filterString = string_null;
     me.getHUDSkins(me);
 }
void HUDSkinList_Refresh_Click (entity btn, entity me)
Definition at line 183 of file hudskinlist.qc.
Referenced by XonoticHUDExitDialog_fill(), and XonoticHUDSkinList_draw().
 {
     me.getHUDSkins(me);
     me.setSelected(me, 0); //always select the first element after a list update
 }
void HUDSkinList_SavedName_Change (entity box, entity me)
Definition at line 189 of file hudskinlist.qc.
References string_null, strunzone(), and strzone().
Referenced by XonoticHUDExitDialog_fill().
 {
     if(me.savedName)
         strunzone(me.savedName);
     if(box.text != "")
         me.savedName = strzone(box.text);
     else
         me.savedName = string_null;
 }
entity makeXonoticHUDSkinList ()
Definition at line 5 of file hudskinlist.qc.
References entity(), me, and NEW.
Referenced by XonoticHUDExitDialog_fill().
 {
     entity me;
     me = NEW(XonoticHUDSkinList);
     me.configureXonoticHUDSkinList(me);
     return me;
 }
METHOD (XonoticHUDSkinList , configureXonoticHUDSkinList , void(entity))
METHOD (XonoticHUDSkinList , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticHUDSkinList , draw , void(entity))
METHOD (XonoticHUDSkinList , drawListBoxItem , void(entity, int, vector, bool, bool))
METHOD (XonoticHUDSkinList , getHUDSkins , void(entity))
METHOD (XonoticHUDSkinList , setHUDSkin , void(entity))
METHOD (XonoticHUDSkinList , hudskinName , string(entity, float))
METHOD (XonoticHUDSkinList , hudskinPath , string(entity, float))
METHOD (XonoticHUDSkinList , hudskinTitle , string(entity, float))
METHOD (XonoticHUDSkinList , hudskinAuthor , string(entity, float))
METHOD (XonoticHUDSkinList , doubleClickListBoxItem , void(entity, float, vector))
METHOD (XonoticHUDSkinList , keyDown , float(entity, float, float, float))
METHOD (XonoticHUDSkinList , destroy , void(entity))
METHOD (XonoticHUDSkinList , showNotify , void(entity))
void SaveHUDSkin_Click (entity btn, entity me)
Definition at line 218 of file hudskinlist.qc.
References localcmd, s, and time.
Referenced by XonoticHUDExitDialog_fill().
 {
     string s = me.savedName;
     if(s == "")
         s = "myconfig";
     localcmd(sprintf("hud save \"%s\"\n", s));
     me.delayedRefreshTime = time + 1;
 }
void SetHUDSkin_Click (entity btn, entity me)
Definition at line 243 of file hudskinlist.qc.
Referenced by XonoticHUDExitDialog_fill().
 {
     me.setHUDSkin(me);
 }
Variable Documentation
entity hudskinlist
Definition at line 33 of file hudskinlist.qh.
Referenced by XonoticHUDExitDialog_fill().