Xonotic: client/draw.qh File Reference
draw.qh File Reference
Macros
#define draw_beginBoldFont() drawfont = FONT_USER + 2
#define draw_endBoldFont() drawfont = FONT_USER + 1
#define drawcharacter(position, character, scale, rgb, alpha, flag) drawcharacter_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
#define drawcolorcodedstring(position, text, scale, alpha, flag) drawcolorcodedstring_builtin(HUD_Shift(position), text, scale, alpha, flag)
#define drawcolorcodedstring2(position, text, scale, rgb, alpha, flag) drawcolorcodedstring2_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
#define drawfill(position, size, rgb, alpha, flag) drawfill_builtin(HUD_Shift(position), HUD_Scale(size), rgb, alpha, flag)
#define drawpic(position, pic, size, rgb, alpha, flag) drawpic_builtin(HUD_Shift(position), pic, HUD_Scale(size), rgb, alpha, flag)
#define drawpic_aspect(pos, pic, mySize, color, theAlpha, drawflag)
#define drawpic_aspect_skin(pos, pic, sz, color, theAlpha, drawflag)
#define drawpic_skin(pos, pic, sz, color, theAlpha, drawflag)
#define drawsetcliparea(xposition, yposition, w, h) drawsetcliparea_builtin(HUD_ShiftX(xposition), HUD_ShiftY(yposition), HUD_ScaleX(w), HUD_ScaleY(h))
#define drawstring(position, text, scale, rgb, alpha, flag) drawstring_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Functions
void drawborderlines (float thickness, vector pos, vector dim, vector color, float theAlpha, float drawflag)
void DrawCircleClippedPic (vector centre, float radi, string pic, float f, vector rgb, float a, float drawflag)
void drawcolorcodedstring_aspect (vector pos, string text, vector sz, float theAlpha, float drawflag)
void drawcolorcodedstring_aspect_expanding (vector pos, string text, vector sz, float theAlpha, float drawflag, float fadelerp)
void drawcolorcodedstring_expanding (vector position, string text, vector theScale, float theAlpha, float flag, float fadelerp)
void drawpic_aspect_skin_expanding (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
void drawpic_aspect_skin_expanding_two (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
void drawpic_tiled (vector pos, string pic, vector sz, vector area, vector color, float theAlpha, float drawflag)
void drawstring_aspect (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag)
void drawstring_aspect_expanding (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag, float fadelerp)
void drawstring_expanding (vector position, string text, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
vector expandingbox_resize_centered_box_offset (float sz, vector boxsize, float boxxsizefactor)
float expandingbox_sizefactor_from_fadelerp (float fadelerp)
void PolyDrawModel (entity e)
float PolyDrawModelSurface (entity e, float i_s)
float stringwidth (string text, float handleColors, vector sz)
Variables
float _drawpic_imgaspect
vector _drawpic_imgsize
float _drawpic_oldsz
string _drawpic_picpath
vector _drawpic_sz
vector drawfontscale
Macro Definition Documentation
#define draw_beginBoldFont () drawfont = FONT_USER + 2
Definition at line 4 of file draw.qh.
Referenced by HUD_Ammo(), HUD_CenterPrint(), HUD_HealthArmor(), HUD_ModIcons(), HUD_Physics(), HUD_Powerups(), HUD_RaceTimer(), HUD_Score(), HUD_StrafeHUD(), HUD_Timer(), Label_draw(), Label_recalcPositionWithText(), MapVote_Draw(), Scoreboard_Draw(), and XonoticPlayerModelSelector_draw().
#define draw_endBoldFont () drawfont = FONT_USER + 1
Definition at line 5 of file draw.qh.
Referenced by CSQC_Init(), draw_reset(), HUD_Ammo(), HUD_CenterPrint(), HUD_HealthArmor(), HUD_ModIcons(), HUD_Physics(), HUD_Powerups(), HUD_RaceTimer(), HUD_Score(), HUD_StrafeHUD(), HUD_Timer(), Label_draw(), Label_recalcPositionWithText(), MapVote_Draw(), Scoreboard_Draw(), and XonoticPlayerModelSelector_draw().
#define drawcharacter (position, character, scale, rgb, alpha, flag) drawcharacter_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 24 of file draw.qh.
#define drawcolorcodedstring (position, text, scale, alpha, flag) drawcolorcodedstring_builtin(HUD_Shift(position), text, scale, alpha, flag)
Definition at line 30 of file draw.qh.
#define drawcolorcodedstring2 (position, text, scale, rgb, alpha, flag) drawcolorcodedstring2_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 33 of file draw.qh.
#define drawfill (position, size, rgb, alpha, flag) drawfill_builtin(HUD_Shift(position), HUD_Scale(size), rgb, alpha, flag)
Definition at line 36 of file draw.qh.
#define drawpic (position, pic, size, rgb, alpha, flag) drawpic_builtin(HUD_Shift(position), pic, HUD_Scale(size), rgb, alpha, flag)
Definition at line 21 of file draw.qh.
#define drawpic_aspect (pos, pic, mySize, color, theAlpha, drawflag)
Value:
MACRO_BEGIN \
        _drawpic_imgsize = draw_getimagesize(pic);\
        if(_drawpic_imgsize != '0 0 0') {\
            _drawpic_imgaspect = _drawpic_imgsize.x/_drawpic_imgsize.y;\
            _drawpic_sz = mySize;\
            if(_drawpic_sz.x/_drawpic_sz.y > _drawpic_imgaspect) {\
                _drawpic_oldsz = _drawpic_sz.x;\
                _drawpic_sz.x = _drawpic_sz.y * _drawpic_imgaspect;\
                if(_drawpic_sz.x)\
                    drawpic(pos + eX * 0.5 * (_drawpic_oldsz - _drawpic_sz.x), pic, _drawpic_sz, color, theAlpha, drawflag);\
            } else {\
                _drawpic_oldsz = _drawpic_sz.y;\
                _drawpic_sz.y = _drawpic_sz.x / _drawpic_imgaspect;\
                if(_drawpic_sz.y)\
                    drawpic(pos + eY * 0.5 * (_drawpic_oldsz - _drawpic_sz.y), pic, _drawpic_sz, color, theAlpha, drawflag);\
            }\
        }\
    MACRO_END
Definition at line 57 of file draw.qh.
#define drawpic_aspect_skin (pos, pic, sz, color, theAlpha, drawflag)
Value:
MACRO_BEGIN \
        _drawpic_picpath = strcat(hud_skin_path, "/", pic);\
        if(precache_pic(_drawpic_picpath) == "") {\
            _drawpic_picpath = strcat("gfx/hud/default/", pic);\
        }\
        drawpic_aspect(pos, _drawpic_picpath, sz, color, theAlpha, drawflag);\
        _drawpic_picpath = string_null;\
    MACRO_END
Definition at line 78 of file draw.qh.
Referenced by DrawAmmoItem(), DrawCAItem(), DrawDomItem(), DrawNumIcon_expanding(), drawpic_aspect_skin_expanding(), HUD_HealthArmor(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_NexBall(), HUD_Mod_Race(), HUD_Notify(), HUD_PressedKeys(), HUD_Weapons(), Item_ItemsTime_Allow(), and Scoreboard_AccuracyStats_Draw().
#define drawpic_skin (pos, pic, sz, color, theAlpha, drawflag)
Value:
MACRO_BEGIN \
        _drawpic_picpath = strcat(hud_skin_path, "/", pic);\
        if(precache_pic(_drawpic_picpath) == "") {\
            _drawpic_picpath = strcat("gfx/hud/default/", pic);\
        }\
        drawpic(pos, _drawpic_picpath, sz, color, theAlpha, drawflag);\
        _drawpic_picpath = string_null;\
    MACRO_END
Definition at line 89 of file draw.qh.
Referenced by drawpic_aspect_skin_expanding_two(), HUD_Vote(), SpecialCommand(), and Vehicles_drawHUD().
#define drawsetcliparea (xposition, yposition, w, h) drawsetcliparea_builtin(HUD_ShiftX(xposition), HUD_ShiftY(yposition), HUD_ScaleX(w), HUD_ScaleY(h))
Definition at line 39 of file draw.qh.
#define drawstring (position, text, scale, rgb, alpha, flag) drawstring_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 27 of file draw.qh.
Function Documentation
void drawborderlines (float thickness, vector pos, vector dim, vector color, float theAlpha, float drawflag)
Definition at line 5 of file draw.qc.
References drawfill(), and vector().
Referenced by GameTypeVote_DrawGameTypeItem(), and MapVote_DrawMapItem().
 {
     vector line_dim = '0 0 0';
     // left and right lines
     pos.x -= thickness;
     line_dim.x = thickness;
     line_dim.y = dim.y;
     drawfill(pos, line_dim, color, theAlpha, drawflag);
     drawfill(pos + (dim.x + thickness) * '1 0 0', line_dim, color, theAlpha, drawflag);
     // upper and lower lines
     pos.y -= thickness;
     line_dim.x = dim.x + thickness * 2; // make upper and lower lines longer
     line_dim.y = thickness;
     drawfill(pos, line_dim, color, theAlpha, drawflag);
     drawfill(pos + (dim.y + thickness) * '0 1 0', line_dim, color, theAlpha, drawflag);
 }
void DrawCircleClippedPic (vector centre, float radi, string pic, float f, vector rgb, float a, float drawflag)
Definition at line 182 of file draw.qc.
References cos(), fabs(), HUD_Scale(), HUD_Shift(), M_PI, sin(), v, and vector().
Referenced by HUD_Crosshair(), and HUD_Draw().
 {
     vector ringsize, v, t;
     ringsize = radi * '1 1 0';
     centre = HUD_Shift(centre);
     ringsize = HUD_Scale(ringsize);
     if(f >= 1)
     {
         // draw full rectangle
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y -= 0.5 * ringsize.y;    t -= '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         return;  // Complete rectangle, nothing more needed.
     }
     float co = cos(f * 2 * M_PI);
     float si = sin(f * 2 * M_PI);
     float q = fabs(co) + fabs(si);
     co /= q;
     si /= q;
     if(f > 0.75)
     {
         // draw upper half in full
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         // draw clipped lower half as a quad
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y -= 0.5 * ringsize.y;    t -= '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
     }
     else if(f > 0.5)
     {
         // draw upper half in full
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         // draw clipped lower half as a triangle
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
     }
     else if(f > 0.25)
     {
         // draw clipped lower half as a quad
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
     }
     else if (f > 0)
     {
         // draw clipped lower half as a triangle
         R_BeginPolygon(pic, drawflag, true);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
     }
     else
     {
         // Nothing to draw.
         return;
     }
     // The last, moving vertex.
         v = centre;         t = '0.5 0.5 0';
         v.x += co * 0.5 * ringsize.x;   t += co * '0.5 0.5 0';
         v.y += si * 0.5 * ringsize.y;   t += si * '0.5 -0.5 0';
         R_PolygonVertex(v, t, rgb, a);
     R_EndPolygon();
 }
void drawcolorcodedstring_aspect (vector pos, string text, vector sz, float theAlpha, float drawflag)
Definition at line 108 of file draw.qc.
References drawcolorcodedstring(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by HUD_Mod_Race(), and HUD_Vote().
{
     SET_POS_AND_SZ_Y_ASPECT(true);
     drawcolorcodedstring(pos, text, '1 1 0' * sz.y, theAlpha, drawflag);
 }
void drawcolorcodedstring_aspect_expanding (vector pos, string text, vector sz, float theAlpha, float drawflag, float fadelerp)
Definition at line 147 of file draw.qc.
References drawcolorcodedstring_expanding(), and SET_POS_AND_SZ_Y_ASPECT.
{
     SET_POS_AND_SZ_Y_ASPECT(true);
     drawcolorcodedstring_expanding(pos, text, '1 1 0' * sz.y, theAlpha, drawflag, fadelerp);
 }
void drawcolorcodedstring_expanding (vector position, string text, vector theScale, float theAlpha, float flag, float fadelerp)
Definition at line 136 of file draw.qc.
References drawcolorcodedstring(), drawfontscale, expandingbox_resize_centered_box_offset(), expandingbox_sizefactor_from_fadelerp(), and hud_scale.
Referenced by drawcolorcodedstring_aspect_expanding().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawfontscale = hud_scale * sz;
     // eventually replace with drawcolorcodedstring
     drawcolorcodedstring(position + expandingbox_resize_centered_box_offset(sz, theScale, stringwidth_builtin(text, true, theScale * (sz / drawfontscale.x)) / (theScale.x * sz)), text, theScale * (sz / drawfontscale.x), theAlpha * (1 - fadelerp), flag);
     drawfontscale = hud_scale;
 }
void drawpic_aspect_skin_expanding (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 61 of file draw.qc.
References drawpic_aspect_skin, expandingbox_resize_centered_box_offset(), and expandingbox_sizefactor_from_fadelerp().
Referenced by DrawNumIcon_expanding(), drawpic_aspect_skin_expanding_two(), HUD_Mod_Keepaway(), and Item_ItemsTime_Allow().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawpic_aspect_skin(position + expandingbox_resize_centered_box_offset(sz, theScale, 1), pic, theScale * sz, rgb, theAlpha * (1 - fadelerp), flag);
 }
void drawpic_aspect_skin_expanding_two (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 69 of file draw.qc.
References drawpic_aspect_skin_expanding(), and drawpic_skin.
 {
     drawpic_aspect_skin_expanding(position, pic, theScale, rgb, theAlpha, flag, fadelerp);
     drawpic_skin(position, pic, theScale, rgb, theAlpha * fadelerp, flag);
 }
void drawpic_tiled (vector pos, string pic, vector sz, vector area, vector color, float theAlpha, float drawflag)
Definition at line 24 of file draw.qc.
References drawsubpic(), HUD_Scale(), HUD_Shift(), min(), and vector().
Referenced by HUD_Panel_HlBorder(), Scoreboard_AccuracyStats_Draw(), Scoreboard_MakeTable(), Scoreboard_MapStats_Draw(), and Scoreboard_Rankings_Draw().
 {
     pos = HUD_Shift(pos);
     sz = HUD_Scale(sz);
     area = HUD_Scale(area);
     vector current_pos = '0 0 0', end_pos, new_size = '0 0 0', ratio = '0 0 0';
     end_pos = pos + area;
     current_pos.y = pos.y;
     while (current_pos.y < end_pos.y)
     {
         current_pos.x = pos.x;
         while (current_pos.x < end_pos.x)
         {
             new_size.x = min(sz.x, end_pos.x - current_pos.x);
             new_size.y = min(sz.y, end_pos.y - current_pos.y);
             ratio.x = new_size.x / sz.x;
             ratio.y = new_size.y / sz.y;
             drawsubpic(current_pos, new_size, pic, '0 0 0', ratio, color, theAlpha, drawflag);
             current_pos.x += sz.x;
         }
         current_pos.y += sz.y;
     }
 }
void drawstring_aspect (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag)
Definition at line 102 of file draw.qc.
References drawstring(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by DrawAmmoItem(), DrawCAItem(), DrawDomItem(), DrawNumIcon_expanding(), HUD_Draw(), HUD_EngineInfo(), HUD_Mod_Race(), HUD_Physics(), HUD_Score(), HUD_Score_Rankings(), HUD_StrafeHUD(), HUD_Timer(), HUD_Vote(), HUD_Weapons(), Item_ItemsTime_Allow(), and race_showTime().
{
     SET_POS_AND_SZ_Y_ASPECT(false);
     drawstring(pos, text, '1 1 0' * sz.y, color, theAlpha, drawflag);
 }
void drawstring_aspect_expanding (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag, float fadelerp)
Definition at line 131 of file draw.qc.
References drawstring_expanding(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by DrawNumIcon_expanding(), and race_showTime().
{
     SET_POS_AND_SZ_Y_ASPECT(false);
     drawstring_expanding(pos, text, '1 1 0' * sz.y, color, theAlpha, drawflag, fadelerp);
 }
void drawstring_expanding (vector position, string text, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 113 of file draw.qc.
References drawfontscale, drawstring(), expandingbox_resize_centered_box_offset(), expandingbox_sizefactor_from_fadelerp(), HUD_Scale(), hud_scale, and vector().
Referenced by drawstring_aspect_expanding(), and HUD_RaceTimer().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawfontscale = hud_scale * sz;
     vector dfs = drawfontscale;
     drawfontscale = sz * '1 1 0';
     float textaspect = stringwidth_builtin(text, false, theScale * (sz / drawfontscale.x)) / (theScale.x * sz);
     drawfontscale = dfs;
     drawstring(position + expandingbox_resize_centered_box_offset(sz, theScale, textaspect), text, HUD_Scale(theScale * (sz / drawfontscale.x)), rgb, theAlpha * (1 - fadelerp), flag);
     // width parameter:
     //    (scale_x * sz / drawfontscale.x) * drawfontscale.x * SIZE1 / (scale_x * sz)
     //    SIZE1
     drawfontscale = hud_scale;
 }
vector expandingbox_resize_centered_box_offset (float sz, vector boxsize, float boxxsizefactor)
Definition at line 55 of file draw.qc.
Referenced by drawcolorcodedstring_expanding(), drawpic_aspect_skin_expanding(), and drawstring_expanding().
 {
     boxsize.x *= boxxsizefactor; // easier interface for text
     return boxsize * (0.5 * (1 - sz));
 }
float expandingbox_sizefactor_from_fadelerp (float fadelerp)
Definition at line 50 of file draw.qc.
Referenced by drawcolorcodedstring_expanding(), drawpic_aspect_skin_expanding(), and drawstring_expanding().
 {
     return 1.2 / (1.2 - fadelerp);
 }
void PolyDrawModel (entity e)
Definition at line 174 of file draw.qc.
References PolyDrawModelSurface().
Referenced by DrawDebugModel().
 {
     float i_s;
     for(i_s = 0; ; ++i_s)
         if(!PolyDrawModelSurface(e, i_s))
             break;
 }
float PolyDrawModelSurface (entity e, float i_s)
Definition at line 153 of file draw.qc.
References SPA_TEXCOORDS0, and vector().
Referenced by PolyDrawModel().
 {
     float i_t;
     float n_t;
     vector tri;
     string tex;
     tex = getsurfacetexture(e, i_s);
     if (!tex)
         return 0; // this is beyond the last one
     n_t = getsurfacenumtriangles(e, i_s);
     for(i_t = 0; i_t < n_t; ++i_t)
     {
         tri = getsurfacetriangle(e, i_s, i_t);
         R_BeginPolygon(tex, 0, false);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.x), getsurfacepointattribute(e, i_s, tri.x, SPA_TEXCOORDS0), '1 1 1', 1);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.y), getsurfacepointattribute(e, i_s, tri.y, SPA_TEXCOORDS0), '1 1 1', 1);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.z), getsurfacepointattribute(e, i_s, tri.z, SPA_TEXCOORDS0), '1 1 1', 1);
         R_EndPolygon();
     }
     return 1;
 }
float stringwidth (string text, float handleColors, vector sz)
Definition at line 75 of file draw.qc.
 {
     vector dfs = drawfontscale;
     drawfontscale = '1 1 0';
     float r = stringwidth_builtin(text, handleColors, sz);
     drawfontscale = dfs;
     return r;
 }
Variable Documentation
float _drawpic_imgaspect
Definition at line 52 of file draw.qh.
vector _drawpic_imgsize
Definition at line 53 of file draw.qh.
float _drawpic_oldsz
Definition at line 55 of file draw.qh.
string _drawpic_picpath
Definition at line 56 of file draw.qh.
vector _drawpic_sz
Definition at line 54 of file draw.qh.
vector drawfontscale
Definition at line 3 of file draw.qh.
Referenced by DamageText::DamageText_draw2d(), Draw_ShowNames(), drawcolorcodedstring_expanding(), drawstring_expanding(), HUD_CenterPrint(), HUD_Scale_Disable(), HUD_Scale_Enable(), and stringwidth().