Xonotic: InputBox Class Reference
InputBox Class Reference
Public Member Functions
ATTRIB (Label, text, string)
ATTRIB (Label, currentText, string)
ATTRIB (InputBox, src, string)
ATTRIB (MenuItem, parent, entity)
ATTRIB (Label, textEntity, entity)
ATTRIB (MenuItem, tooltip, string)
ATTRIB (InputBox, applyButton, entity)
ATTRIB (InputBox, clearButton, entity)
virtual void configureInputBox ()
virtual void configureLabel ()
virtual void destroy ()
virtual void draw ()
virtual void enterText ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void setText ()
virtual void showNotify ()
virtual void toString ()
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = 0.7
vector cb_color = '1 1 1'
vector cb_colorC = '1 1 1'
vector cb_colorF = '1 1 1'
float cb_focused = 0
float cb_pressed = 0
float cb_width = 0
vector color = '1 1 1'
vector colorF = '1 1 1'
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
float cursorPos = 0
float disabled = 0
float disabledAlpha = 0.3
vector dragScrollPos = '0 0 0'
float dragScrollTimer = 0
float editColorCodes = 1
float enableClearButton = 1
float focusable = 1
float focused = 0
float fontSize = 8
string forbiddenCharacters = ""
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
float lastChangeTime = 0
float marginLeft = 0
float marginRight = 0
float maxLength = 255
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
float scrollPos = 0
vector size = '0 0 0'
Detailed Description
Definition at line 4 of file inputbox.qh.
Member Function Documentation
Label::ATTRIB (Label , text , string) inherited
Label::ATTRIB (Label , currentText , string) inherited
InputBox::ATTRIB (InputBox , src , string)
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
Label::ATTRIB (Label , textEntity , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
InputBox::ATTRIB (InputBox , applyButton , entity)
InputBox::ATTRIB (InputBox , clearButton , entity)
virtual void InputBox::configureInputBox () virtual
virtual void Label::configureLabel () virtual inherited
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void InputBox::draw () virtual
Reimplemented from Label.
virtual void InputBox::enterText () virtual
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void MenuItem::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
void MenuItem::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void InputBox::keyDown () virtual
Reimplemented from MenuItem.
Reimplemented in XonoticInputBox.
void MenuItem::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void InputBox::mouseDrag () virtual
Reimplemented from MenuItem.
virtual void InputBox::mouseMove () virtual
Reimplemented from MenuItem.
void InputBox::mousePress () virtual
Reimplemented from MenuItem.
Definition at line 74 of file inputbox.qc.
References InputBox_mouseDrag(), over_ClearButton(), pressed, and time.
     {
         if (this.enableClearButton)
             if (over_ClearButton(this, pos))
             {
                 this.cb_pressed = 1;
                 return true;
             }
         this.dragScrollTimer = time;
         this.pressed = 1;
         return InputBox_mouseDrag(this, pos);
     }
virtual void InputBox::mouseRelease () virtual
Reimplemented from MenuItem.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void InputBox::resizeNotify () virtual
Reimplemented from Label.
virtual void InputBox::setText () virtual
Reimplemented from Label.
Reimplemented in XonoticInputBox.
virtual void InputBox::showNotify () virtual
Reimplemented from MenuItem.
virtual void Label::toString () virtual inherited
Reimplemented from MenuItem.
Reimplemented in Slider, and CheckBox.
Member Data Documentation
float Label::align = 0.5 inherited
Definition at line 15 of file label.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float InputBox::allowFocusSound = 1
Definition at line 23 of file inputbox.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float Label::alpha = 0.7 inherited
Definition at line 24 of file label.qh.
vector InputBox::cb_color = '1 1 1'
Definition at line 41 of file inputbox.qh.
vector InputBox::cb_colorC = '1 1 1'
Definition at line 43 of file inputbox.qh.
vector InputBox::cb_colorF = '1 1 1'
Definition at line 42 of file inputbox.qh.
float InputBox::cb_focused = 0
Definition at line 40 of file inputbox.qh.
float InputBox::cb_pressed = 0
Definition at line 39 of file inputbox.qh.
float InputBox::cb_width = 0
Definition at line 38 of file inputbox.qh.
vector InputBox::color = '1 1 1'
Definition at line 31 of file inputbox.qh.
vector InputBox::colorF = '1 1 1'
Definition at line 32 of file inputbox.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
float InputBox::cursorPos = 0
Definition at line 19 of file inputbox.qh.
float InputBox::disabled = 0
Definition at line 24 of file inputbox.qh.
float Label::disabledAlpha = 0.3 inherited
Definition at line 27 of file label.qh.
vector InputBox::dragScrollPos = '0 0 0'
Definition at line 27 of file inputbox.qh.
float InputBox::dragScrollTimer = 0
Definition at line 26 of file inputbox.qh.
float InputBox::editColorCodes = 1
Definition at line 29 of file inputbox.qh.
float InputBox::enableClearButton = 1
Definition at line 36 of file inputbox.qh.
float InputBox::focusable = 1
Definition at line 22 of file inputbox.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
float Label::fontSize = 8 inherited
Definition at line 14 of file label.qh.
string InputBox::forbiddenCharacters = ""
Definition at line 30 of file inputbox.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
float InputBox::lastChangeTime = 0
Definition at line 25 of file inputbox.qh.
float Label::marginLeft = 0 inherited
Definition at line 20 of file label.qh.
float Label::marginRight = 0 inherited
Definition at line 21 of file label.qh.
float InputBox::maxLength = 255
Definition at line 33 of file inputbox.qh.
vector MenuItem::origin = '0 0 0' inherited
Definition at line 29 of file item.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float InputBox::pressed = 0
Definition at line 28 of file inputbox.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
float InputBox::scrollPos = 0
Definition at line 20 of file inputbox.qh.
vector MenuItem::size = '0 0 0' inherited
Definition at line 30 of file item.qh.
The documentation for this class was generated from the following files:
menu/item/inputbox.qh
menu/item/inputbox.qc