Xonotic: common/mutators/mutator/random_items/sv_random_items.qh File Reference
sv_random_items.qh File Reference
Header file that describes the random items mutator.
Macros
#define EV_RandomItems_GetRandomItemClassName(i, o)
Called when random item classname is requested.
Enumerations
enum {
RANDOM_ITEM_TYPE_HEALTH = BIT(0), RANDOM_ITEM_TYPE_ARMOR = BIT(1), RANDOM_ITEM_TYPE_RESOURCE = BIT(2), RANDOM_ITEM_TYPE_WEAPON = BIT(3),
RANDOM_ITEM_TYPE_POWERUP = BIT(4), RANDOM_ITEM_TYPE_ALL = BITS(5)
}
Functions
MUTATOR_HOOKABLE (RandomItems_GetRandomItemClassName, EV_RandomItems_GetRandomItemClassName)
string RandomItems_GetRandomItemClassName (string prefix)
Returns a random classname of the item.
string RandomItems_GetRandomVanillaItemClassName (string prefix, int types)
Returns a random classname of the vanilla item.
REGISTER_MUTATOR (random_items,(autocvar_g_random_items||autocvar_g_random_loot))
Variables
bool autocvar_g_random_items
Whether to enable random items.
bool autocvar_g_random_loot
Whether to enable random loot.
Detailed Description
Header file that describes the random items mutator.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file sv_random_items.qh.
Macro Definition Documentation
#define EV_RandomItems_GetRandomItemClassName (i, o)
Value:
    i(string, MUTATOR_ARGV_0_string) \ o(string, MUTATOR_ARGV_1_string) \
Called when random item classname is requested.
Definition at line 37 of file sv_random_items.qh.
Enumeration Type Documentation
anonymous enum
Enumerator
RANDOM_ITEM_TYPE_HEALTH
RANDOM_ITEM_TYPE_ARMOR
RANDOM_ITEM_TYPE_RESOURCE
RANDOM_ITEM_TYPE_WEAPON
RANDOM_ITEM_TYPE_POWERUP
RANDOM_ITEM_TYPE_ALL
Definition at line 11 of file sv_random_items.qh.
 {
     RANDOM_ITEM_TYPE_HEALTH = BIT(0),
     RANDOM_ITEM_TYPE_ARMOR = BIT(1),
     RANDOM_ITEM_TYPE_RESOURCE = BIT(2),
     RANDOM_ITEM_TYPE_WEAPON = BIT(3),
     RANDOM_ITEM_TYPE_POWERUP = BIT(4),
     RANDOM_ITEM_TYPE_ALL = BITS(5)
 };
Function Documentation
MUTATOR_HOOKABLE (RandomItems_GetRandomItemClassName , EV_RandomItems_GetRandomItemClassName)
string RandomItems_GetRandomItemClassName (string prefix)
Returns a random classname of the item.
Parameters
[in] prefix Prefix of the cvars that hold probabilities.
Returns
Random classname of the item.
Note
This function will automatically detect gamemode and use cvars from that gamemode.
Definition at line 54 of file sv_random_items.qc.
References M_ARGV, MUTATOR_CALLHOOK, RANDOM_ITEM_TYPE_ALL, RandomItems_GetRandomItemClassName(), and RandomItems_GetRandomVanillaItemClassName().
Referenced by RandomItems_GetRandomItemClassName(), RandomItems_ReplaceMapItem(), and RandomItems_SpawnLootItem().
 {
     if (MUTATOR_CALLHOOK(RandomItems_GetRandomItemClassName, prefix))
     {
         return M_ARGV(1, string);
     }
     return RandomItems_GetRandomVanillaItemClassName(prefix,
         RANDOM_ITEM_TYPE_ALL);
 }
string RandomItems_GetRandomVanillaItemClassName (string prefix, int types)
Returns a random classname of the vanilla item.
Parameters
[in] prefix Prefix of the cvars that hold probabilities.
[in] types Bitmask of the types. See RANDOM_ITEM_TYPE constants.
Returns
Random classname of the vanilla item.
Note
This includes mutator items that don't change gameplay a lot such as jetpack and new toys.
Definition at line 64 of file sv_random_items.qc.
References cvar(), CVAR_TYPEFLAG_EXISTS, FOREACH, LOG_WARNF, RANDOM_ITEM_TYPE_ARMOR, RANDOM_ITEM_TYPE_HEALTH, RANDOM_ITEM_TYPE_POWERUP, RANDOM_ITEM_TYPE_RESOURCE, RANDOM_ITEM_TYPE_WEAPON, RandomItems_GetRandomItemClassNameWithProperty(), RandomSelection_AddFloat, RandomSelection_AddString, RandomSelection_chosen_float, RandomSelection_chosen_string, RandomSelection_Init(), and WEP_FLAG_MUTATORBLOCKED.
Referenced by RandomItems_GetRandomItemClassName().
 {
     if (types == 0)
     {
         return "";
     }
     while (types != 0)
     {
         string cvar_name;
         RandomSelection_Init();
         if (types & RANDOM_ITEM_TYPE_HEALTH)
         {
             cvar_name = sprintf("g_%s_health_probability", prefix);
             if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
             {
                 LOG_WARNF("Random items: cvar %s doesn't exist.", cvar_name);
             }
             else
             {
                 RandomSelection_AddFloat(RANDOM_ITEM_TYPE_HEALTH,
                     cvar(cvar_name), 1);
             }
         }
         if (types & RANDOM_ITEM_TYPE_ARMOR)
         {
             cvar_name = sprintf("g_%s_armor_probability", prefix);
             if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
             {
                 LOG_WARNF("Random items: cvar %s doesn't exist.", cvar_name);
             }
             else
             {
                 RandomSelection_AddFloat(RANDOM_ITEM_TYPE_ARMOR,
                     cvar(cvar_name), 1);
             }
         }
         if (types & RANDOM_ITEM_TYPE_RESOURCE)
         {
             cvar_name = sprintf("g_%s_resource_probability", prefix);
             if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
             {
                 LOG_WARNF("Random items: cvar %s doesn't exist.", cvar_name);
             }
             else
             {
                 RandomSelection_AddFloat(RANDOM_ITEM_TYPE_RESOURCE,
                     cvar(cvar_name), 1);
             }
         }
         if (types & RANDOM_ITEM_TYPE_WEAPON)
         {
             cvar_name = sprintf("g_%s_weapon_probability", prefix);
             if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
             {
                 LOG_WARNF("Random items: cvar %s doesn't exist.", cvar_name);
             }
             else
             {
                 RandomSelection_AddFloat(RANDOM_ITEM_TYPE_WEAPON, cvar(cvar_name), 1);
             }
         }
         if (types & RANDOM_ITEM_TYPE_POWERUP)
         {
             cvar_name = sprintf("g_%s_powerup_probability", prefix);
             if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
             {
                 LOG_WARNF("Random items: cvar %s doesn't exist.", cvar_name);
             }
             else
             {
                 RandomSelection_AddFloat(RANDOM_ITEM_TYPE_POWERUP, cvar(cvar_name), 1);
             }
         }
         int item_type = RandomSelection_chosen_float;
         string class_name = "";
         switch (item_type)
         {
             case RANDOM_ITEM_TYPE_HEALTH:
             {
                 class_name = RandomItems_GetRandomItemClassNameWithProperty(
                     prefix, instanceOfHealth);
                 break;
             }
             case RANDOM_ITEM_TYPE_ARMOR:
             {
                 class_name = RandomItems_GetRandomItemClassNameWithProperty(
                     prefix, instanceOfArmor);
                 break;
             }
             case RANDOM_ITEM_TYPE_RESOURCE:
             {
                 class_name = RandomItems_GetRandomItemClassNameWithProperty(
                     prefix, instanceOfAmmo);
                 break;
             }
             case RANDOM_ITEM_TYPE_WEAPON:
             {
                 RandomSelection_Init();
                 FOREACH(Weapons, it != WEP_Null &&
                     !(it.spawnflags & WEP_FLAG_MUTATORBLOCKED),
                 {
                     cvar_name = sprintf("g_%s_%s_probability", prefix,
                         it.m_canonical_spawnfunc);
                     if (!(cvar_type(cvar_name) & CVAR_TYPEFLAG_EXISTS))
                     {
                         LOG_WARNF("Random items: cvar %s doesn't exist.",
                             cvar_name);
                         continue;
                     }
                     RandomSelection_AddString(it.m_canonical_spawnfunc,
                         cvar(cvar_name), 1);
                 });
                 class_name = RandomSelection_chosen_string;
                 break;
             }
             case RANDOM_ITEM_TYPE_POWERUP:
             {
                 class_name = RandomItems_GetRandomItemClassNameWithProperty(
                     prefix, instanceOfPowerup);
                 break;
             }
         }
         if (class_name != "")
         {
             return class_name;
         }
         types &= ~item_type;
     }
     return "";
 }
REGISTER_MUTATOR (random_items , (autocvar_g_random_items||autocvar_g_random_loot))
Variable Documentation
bool autocvar_g_random_items
Whether to enable random items.
Definition at line 8 of file sv_random_items.qh.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_random_loot
Whether to enable random loot.
Definition at line 9 of file sv_random_items.qh.
Referenced by MUTATOR_HOOKFUNCTION().