Xonotic: server/mutators/mutator/gamemode_domination.qc File Reference
gamemode_domination.qc File Reference
#include "gamemode_domination.qh"
#include <server/teamplay.qh>
Macros
#define DOM_OWNED_CONTROLPOINTS() ((redowned > 0) + (blueowned > 0) + (yellowowned > 0) + (pinkowned > 0))
#define DOM_OWNED_CONTROLPOINTS_OK() (DOM_OWNED_CONTROLPOINTS() < total_controlpoints)
Functions
void AnimateDomPoint (entity this)
void dom_controlpoint_setup (entity this)
void dom_DelayedInit (entity this)
void dom_EventLog (string mode, float team_before, entity actor)
void dom_Initialize ()
void dom_spawnpoint (vector org)
void dom_spawnteam (string teamname, float teamcolor, string pointmodel, float pointskin, Sound capsound, string capnarration, string capmessage)
void dom_spawnteams (int teams)
float Domination_CheckPlayers ()
float Domination_CheckWinner ()
void Domination_count_controlpoints ()
float Domination_GetWinnerTeam ()
void Domination_RoundStart ()
void dompoint_captured (entity this)
void dompointthink (entity this)
void dompointtouch (entity this, entity toucher)
void havocbot_goalrating_controlpoints (entity this, float ratingscale, vector org, float sradius)
void havocbot_role_dom (entity this)
MUTATOR_HOOKFUNCTION (dom, CheckAllowedTeams)
MUTATOR_HOOKFUNCTION (dom, reset_map_players)
MUTATOR_HOOKFUNCTION (dom, PlayerSpawn)
MUTATOR_HOOKFUNCTION (dom, ClientConnect)
MUTATOR_HOOKFUNCTION (dom, HavocBot_ChooseRole)
void ScoreRules_dom (int teams)
void set_dom_state (entity e)
spawnfunc (dom_controlpoint)
spawnfunc (dom_team)
Variables
int autocvar_g_domination_default_teams
bool autocvar_g_domination_disable_frags
int autocvar_g_domination_point_amt
bool autocvar_g_domination_point_fullbright
float autocvar_g_domination_point_rate
float autocvar_g_domination_round_timelimit
int autocvar_g_domination_teams_override
float autocvar_g_domination_warmup
bool g_domination
float total_controlpoints
Macro Definition Documentation
#define DOM_OWNED_CONTROLPOINTS () ((redowned > 0) + (blueowned > 0) + (yellowowned > 0) + (pinkowned > 0))
Definition at line 337 of file gamemode_domination.qc.
#define DOM_OWNED_CONTROLPOINTS_OK () (DOM_OWNED_CONTROLPOINTS() < total_controlpoints)
Definition at line 338 of file gamemode_domination.qc.
Function Documentation
void AnimateDomPoint (entity this)
Definition at line 130 of file gamemode_domination.qc.
References frame, nextthink, pain_finished, t_length, t_width, and time.
Referenced by dompointthink().
 {
     if(this.pain_finished > time)
         return;
     this.pain_finished = time + this.t_width;
     if(this.nextthink > this.pain_finished)
         this.nextthink = this.pain_finished;
     this.frame = this.frame + 1;
     if(this.frame > this.t_length)
         this.frame = 0;
 }
void dom_controlpoint_setup (entity this)
Definition at line 241 of file gamemode_domination.qc.
References autocvar_g_domination_point_amt, autocvar_g_domination_point_rate, classname, cnt, dompointthink(), dompointtouch(), droptofloor, entity(), find(), FL_ITEM, flags, frags, g_items, goalentity, IL_PUSH(), message, nextthink, NULL, objerror(), origin, setthink, skin, solid, SOLID_TRIGGER, sprite, t_length, t_width, time, total_pps, wait, and waypoint_spawnforitem().
Referenced by spawnfunc().
 {
     entity head;
     // find the spawnfunc_dom_team representing unclaimed points
     head = find(NULL, classname, "dom_team");
     while(head && head.netname != "")
         head = find(head, classname, "dom_team");
     if (!head)
         objerror(this, "no spawnfunc_dom_team with netname \"\" found\n");
     // copy important properties from spawnfunc_dom_team entity
     this.goalentity = head;
     _setmodel(this, head.mdl); // precision already set
     this.skin = head.skin;
     this.cnt = -1;
     if(this.message == "")
         this.message = " has captured a control point";
     if(this.frags <= 0)
         this.frags = 1;
     if(this.wait <= 0)
         this.wait = 5;
     float points, waittime;
     if (autocvar_g_domination_point_amt)
         points = autocvar_g_domination_point_amt;
     else
         points = this.frags;
     if (autocvar_g_domination_point_rate)
         waittime = autocvar_g_domination_point_rate;
     else
         waittime = this.wait;
     total_pps += points/waittime;
     if(!this.t_width)
         this.t_width = 0.02; // frame animation rate
     if(!this.t_length)
         this.t_length = 239; // maximum frame
     setthink(this, dompointthink);
     this.nextthink = time;
     settouch(this, dompointtouch);
     this.solid = SOLID_TRIGGER;
     if(!this.flags & FL_ITEM)
         IL_PUSH(g_items, this);
     this.flags = FL_ITEM;
     setsize(this, '-32 -32 -32', '32 32 32');
     setorigin(this, this.origin + '0 0 20');
     droptofloor(this);
     waypoint_spawnforitem(this);
     WaypointSprite_SpawnFixed(WP_DomNeut, this.origin + '0 0 32', this, sprite, RADARICON_DOMPOINT);
 }
void dom_DelayedInit (entity this)
Definition at line 631 of file gamemode_domination.qc.
References autocvar_g_domination_default_teams, autocvar_g_domination_round_timelimit, autocvar_g_domination_roundbased, autocvar_g_domination_teams_override, autocvar_g_domination_warmup, BIT, bound(), c1, c2, c3, c4, CheckAllowedTeams(), classname, dom_spawnteams(), Domination_CheckPlayers(), Domination_CheckWinner(), domination_roundbased, Domination_RoundStart(), domination_teams, find(), LOG_TRACE(), NULL, round_handler_Init(), round_handler_Spawn(), ScoreRules_dom(), and teams.
Referenced by dom_Initialize().
 {
     // if no teams are found, spawn defaults
     if(find(NULL, classname, "dom_team") == NULL || autocvar_g_domination_teams_override >= 2)
     {
         LOG_TRACE("No \"dom_team\" entities found on this map, creating them anyway.");
         domination_teams = autocvar_g_domination_teams_override;
         if (domination_teams < 2)
             domination_teams = autocvar_g_domination_default_teams;
         domination_teams = bound(2, domination_teams, 4);
         dom_spawnteams(domination_teams);
     }
     CheckAllowedTeams(NULL);
     //domination_teams = ((c4>=0) ? 4 : (c3>=0) ? 3 : 2);
     int teams = 0;
     if(c1 >= 0) teams |= BIT(0);
     if(c2 >= 0) teams |= BIT(1);
     if(c3 >= 0) teams |= BIT(2);
     if(c4 >= 0) teams |= BIT(3);
     domination_teams = teams;
     domination_roundbased = autocvar_g_domination_roundbased;
     ScoreRules_dom(domination_teams);
     if(domination_roundbased)
     {
         round_handler_Spawn(Domination_CheckPlayers, Domination_CheckWinner, Domination_RoundStart);
         round_handler_Init(5, autocvar_g_domination_warmup, autocvar_g_domination_round_timelimit);
     }
 }
void dom_EventLog (string mode, float team_before, entity actor)
Definition at line 16 of file gamemode_domination.qc.
References autocvar_sv_eventlog, ftos(), GameLogEcho(), NULL, and strcat().
Referenced by dompoint_captured().
 {
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":dom:", mode, ":", ftos(team_before), ((actor != NULL) ? (strcat(":", ftos(actor.playerid))) : "")));
 }
void dom_Initialize ()
Definition at line 665 of file gamemode_domination.qc.
References dom_DelayedInit(), g_domination, InitializeEntity(), INITPRIO_GAMETYPE, and NULL.
Referenced by REGISTER_MUTATOR().
 {
     g_domination = true;
     InitializeEntity(NULL, dom_DelayedInit, INITPRIO_GAMETYPE);
 }
void dom_spawnpoint (vector org)
Definition at line 608 of file gamemode_domination.qc.
References entity(), setthink, spawn(), and time.
 {
     entity e = spawn();
     e.classname = "dom_controlpoint";
     setthink(e, spawnfunc_dom_controlpoint);
     e.nextthink = time;
     setorigin(e, org);
     spawnfunc_dom_controlpoint(e);
 }
void dom_spawnteam (string teamname, float teamcolor, string pointmodel, float pointskin, Sound capsound, string capnarration, string capmessage)
Definition at line 584 of file gamemode_domination.qc.
References entity(), new_pure, Sound_fixpath, strzone(), and TC.
Referenced by dom_spawnteams().
 {
     TC(Sound, capsound);
     entity e = new_pure(dom_team);
     e.netname = strzone(teamname);
     e.cnt = teamcolor;
     e.model = pointmodel;
     e.skin = pointskin;
     e.noise = strzone(Sound_fixpath(capsound));
     e.noise1 = strzone(capnarration);
     e.message = strzone(capmessage);
     // this code is identical to spawnfunc_dom_team
     _setmodel(e, e.model); // precision not needed
     e.mdl = e.model;
     e.dmg = e.modelindex;
     e.model = "";
     e.modelindex = 0;
     // this would have to be changed if used in quakeworld
     e.team = e.cnt + 1;
     //eprint(e);
 }
void dom_spawnteams (int teams)
Definition at line 619 of file gamemode_domination.qc.
References dom_spawnteam(), NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, TC, and Team_ColoredFullName.
Referenced by dom_DelayedInit().
 {
     TC(int, teams);
     dom_spawnteam(Team_ColoredFullName(NUM_TEAM_1), NUM_TEAM_1-1, "models/domination/dom_red.md3", 0, SND_DOM_CLAIM, "", "Red team has captured a control point");
     dom_spawnteam(Team_ColoredFullName(NUM_TEAM_2), NUM_TEAM_2-1, "models/domination/dom_blue.md3", 0, SND_DOM_CLAIM, "", "Blue team has captured a control point");
     if(teams >= 3)
         dom_spawnteam(Team_ColoredFullName(NUM_TEAM_3), NUM_TEAM_3-1, "models/domination/dom_yellow.md3", 0, SND_DOM_CLAIM, "", "Yellow team has captured a control point");
     if(teams >= 4)
         dom_spawnteam(Team_ColoredFullName(NUM_TEAM_4), NUM_TEAM_4-1, "models/domination/dom_pink.md3", 0, SND_DOM_CLAIM, "", "Pink team has captured a control point");
     dom_spawnteam("", 0, "models/domination/dom_unclaimed.md3", 0, SND_Null, "", "");
 }
float Domination_CheckPlayers ()
Definition at line 376 of file gamemode_domination.qc.
Referenced by dom_DelayedInit().
 {
     return 1;
 }
float Domination_CheckWinner ()
Definition at line 339 of file gamemode_domination.qc.
References APP_TEAM_NUM, autocvar_g_domination_round_timelimit, autocvar_g_domination_warmup, Domination_count_controlpoints(), Domination_GetWinnerTeam(), NULL, round_handler_GetEndTime, round_handler_Init(), ST_DOM_CAPS, TeamScore_AddToTeam(), and time.
Referenced by dom_DelayedInit().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         game_stopped = true;
         round_handler_Init(5, autocvar_g_domination_warmup, autocvar_g_domination_round_timelimit);
         return 1;
     }
     Domination_count_controlpoints();
     float winner_team = Domination_GetWinnerTeam();
     if(winner_team == -1)
         return 0;
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_DOM_CAPS, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     game_stopped = true;
     round_handler_Init(5, autocvar_g_domination_warmup, autocvar_g_domination_round_timelimit);
     return 1;
 }
void Domination_count_controlpoints ()
Definition at line 299 of file gamemode_domination.qc.
References blueowned, g_dompoints, IL_EACH, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, pinkowned, redowned, total_controlpoints, and yellowowned.
Referenced by Domination_CheckWinner().
 {
     total_controlpoints = redowned = blueowned = yellowowned = pinkowned = 0;
     IL_EACH(g_dompoints, true,
     {
         ++total_controlpoints;
         redowned += (it.goalentity.team == NUM_TEAM_1);
         blueowned += (it.goalentity.team == NUM_TEAM_2);
         yellowowned += (it.goalentity.team == NUM_TEAM_3);
         pinkowned += (it.goalentity.team == NUM_TEAM_4);
     });
 }
float Domination_GetWinnerTeam ()
Definition at line 312 of file gamemode_domination.qc.
References blueowned, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, pinkowned, redowned, and yellowowned.
Referenced by Domination_CheckWinner().
 {
     float winner_team = 0;
     if(redowned == total_controlpoints)
         winner_team = NUM_TEAM_1;
     if(blueowned == total_controlpoints)
     {
         if(winner_team) return 0;
         winner_team = NUM_TEAM_2;
     }
     if(yellowowned == total_controlpoints)
     {
         if(winner_team) return 0;
         winner_team = NUM_TEAM_3;
     }
     if(pinkowned == total_controlpoints)
     {
         if(winner_team) return 0;
         winner_team = NUM_TEAM_4;
     }
     if(winner_team)
         return winner_team;
     return -1; // no control points left?
 }
void Domination_RoundStart ()
Definition at line 381 of file gamemode_domination.qc.
References FOREACH_CLIENT, IS_PLAYER, and LAMBDA.
Referenced by dom_DelayedInit().
 {
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(it.player_blocked = false));
 }
void dompoint_captured (entity this)
Definition at line 33 of file gamemode_domination.qc.
References _sound, ATTEN_NORM, autocvar_g_domination_point_amt, autocvar_g_domination_point_rate, bprint(), CH_TRIGGER, cnt, delay, dmg_inflictor, dom_EventLog(), domination_roundbased, enemy, entity(), frags, g_dompoints, goalentity, IL_EACH, model, modelindex, NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, owner, play2all(), PlayerScore_Add(), pps_blue, pps_pink, pps_red, pps_yellow, skin, sprite, SUB_UseTargets(), team, time, total_pps, VOL_BASE, and wait.
Referenced by dompointtouch().
 {
     float old_delay, old_team, real_team;
     // now that the delay has expired, switch to the latest team to lay claim to this point
     entity head = this.owner;
     real_team = this.cnt;
     this.cnt = -1;
     dom_EventLog("taken", this.team, this.dmg_inflictor);
     this.dmg_inflictor = NULL;
     this.goalentity = head;
     this.model = head.mdl;
     this.modelindex = head.dmg;
     this.skin = head.skin;
     float points, wait_time;
     if (autocvar_g_domination_point_amt)
         points = autocvar_g_domination_point_amt;
     else
         points = this.frags;
     if (autocvar_g_domination_point_rate)
         wait_time = autocvar_g_domination_point_rate;
     else
         wait_time = this.wait;
     if(domination_roundbased)
         bprint(sprintf("^3%s^3%s\n", head.netname, this.message));
     else
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_DOMINATION_CAPTURE_TIME, head.netname, this.message, points, wait_time);
     if(this.enemy.playerid == this.enemy_playerid)
         PlayerScore_Add(this.enemy, SP_DOM_TAKES, 1);
     else
         this.enemy = NULL;
     if (head.noise != "")
         if(this.enemy)
             _sound(this.enemy, CH_TRIGGER, head.noise, VOL_BASE, ATTEN_NORM);
         else
             _sound(this, CH_TRIGGER, head.noise, VOL_BASE, ATTEN_NORM);
     if (head.noise1 != "")
         play2all(head.noise1);
     this.delay = time + wait_time;
     // do trigger work
     old_delay = this.delay;
     old_team = this.team;
     this.team = real_team;
     this.delay = 0;
     SUB_UseTargets (this, this, NULL);
     this.delay = old_delay;
     this.team = old_team;
     entity msg = WP_DomNeut;
     switch(this.team)
     {
         case NUM_TEAM_1: msg = WP_DomRed; break;
         case NUM_TEAM_2: msg = WP_DomBlue; break;
         case NUM_TEAM_3: msg = WP_DomYellow; break;
         case NUM_TEAM_4: msg = WP_DomPink; break;
     }
     WaypointSprite_UpdateSprites(this.sprite, msg, WP_Null, WP_Null);
     total_pps = 0, pps_red = 0, pps_blue = 0, pps_yellow = 0, pps_pink = 0;
     IL_EACH(g_dompoints, true,
     {
         if (autocvar_g_domination_point_amt)
             points = autocvar_g_domination_point_amt;
         else
             points = it.frags;
         if (autocvar_g_domination_point_rate)
             wait_time = autocvar_g_domination_point_rate;
         else
             wait_time = it.wait;
         switch(it.goalentity.team)
         {
             case NUM_TEAM_1: pps_red += points/wait_time; break;
             case NUM_TEAM_2: pps_blue += points/wait_time; break;
             case NUM_TEAM_3: pps_yellow += points/wait_time; break;
             case NUM_TEAM_4: pps_pink += points/wait_time; break;
         }
         total_pps += points/wait_time;
     });
     WaypointSprite_UpdateTeamRadar(this.sprite, RADARICON_DOMPOINT, colormapPaletteColor(this.goalentity.team - 1, 0));
     WaypointSprite_Ping(this.sprite);
     this.captime = time;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(set_dom_state(it)));
 }
void dompointthink (entity this)
Definition at line 143 of file gamemode_domination.qc.
References AnimateDomPoint(), autocvar_g_domination_point_amt, autocvar_g_domination_point_rate, delay, domination_roundbased, enemy, frags, game_starttime, goalentity, nextthink, NULL, PlayerScore_Add(), ST_DOM_TICKS, ST_SCORE, TeamScore_AddToTeam(), time, and wait.
Referenced by dom_controlpoint_setup().
 {
     float fragamt;
     this.nextthink = time + 0.1;
     //this.frame = this.frame + 1;
     //if(this.frame > 119)
     //  this.frame = 0;
     AnimateDomPoint(this);
     // give points
     if (game_stopped || this.delay > time || time < game_starttime) // game has ended, don't keep giving points
         return;
     if(autocvar_g_domination_point_rate)
         this.delay = time + autocvar_g_domination_point_rate;
     else
         this.delay = time + this.wait;
     // give credit to the team
     // NOTE: this defaults to 0
     if (!domination_roundbased)
     if (this.goalentity.netname != "")
     {
         if(autocvar_g_domination_point_amt)
             fragamt = autocvar_g_domination_point_amt;
         else
             fragamt = this.frags;
         TeamScore_AddToTeam(this.goalentity.team, ST_SCORE, fragamt);
         TeamScore_AddToTeam(this.goalentity.team, ST_DOM_TICKS, fragamt);
         // give credit to the individual player, if he is still there
         if (this.enemy.playerid == this.enemy_playerid)
         {
             PlayerScore_Add(this.enemy, SP_SCORE, fragamt);
             PlayerScore_Add(this.enemy, SP_DOM_TICKS, fragamt);
         }
         else
             this.enemy = NULL;
     }
 }
void dompointtouch (entity this, entity toucher)
Definition at line 187 of file gamemode_domination.qc.
References captime, classname, cnt, dmg_inflictor, dompoint_captured(), enemy, enemy_playerid, entity(), find(), goalentity, IS_PLAYER, model, modelindex, NULL, owner, round_handler_IsActive, round_handler_IsRoundStarted, skin, sprite, team, and time.
Referenced by dom_controlpoint_setup().
 {
     if (!IS_PLAYER(toucher))
         return;
     if (toucher.health < 1)
         return;
     if(round_handler_IsActive() && !round_handler_IsRoundStarted())
         return;
     if(time < this.captime + 0.3)
         return;
     // only valid teams can claim it
     entity head = find(NULL, classname, "dom_team");
     while (head && head.team != toucher.team)
         head = find(head, classname, "dom_team");
     if (!head || head.netname == "" || head == this.goalentity)
         return;
     // delay capture
     this.team = this.goalentity.team; // this stores the PREVIOUS team!
     this.cnt = toucher.team;
     this.owner = head; // team to switch to after the delay
     this.dmg_inflictor = toucher;
     // this.state = 1;
     // this.delay = time + cvar("g_domination_point_capturetime");
     //this.nextthink = time + cvar("g_domination_point_capturetime");
     //this.think = dompoint_captured;
     // go to neutral team in the mean time
     head = find(NULL, classname, "dom_team");
     while (head && head.netname != "")
         head = find(head, classname, "dom_team");
     if(head == NULL)
         return;
     WaypointSprite_UpdateSprites(this.sprite, WP_DomNeut, WP_Null, WP_Null);
     WaypointSprite_UpdateTeamRadar(this.sprite, RADARICON_DOMPOINT, '0 1 1');
     WaypointSprite_Ping(this.sprite);
     this.goalentity = head;
     this.model = head.mdl;
     this.modelindex = head.dmg;
     this.skin = head.skin;
     this.enemy = toucher; // individual player scoring
     this.enemy_playerid = toucher.playerid;
     dompoint_captured(this);
 }
void havocbot_goalrating_controlpoints (entity this, float ratingscale, vector org, float sradius)
Definition at line 387 of file gamemode_domination.qc.
References g_dompoints, IL_EACH, navigation_routerating(), and vdist.
Referenced by havocbot_role_dom().
 {
     IL_EACH(g_dompoints, vdist((((it.absmin + it.absmax) * 0.5) - org), <, sradius),
     {
         if(it.cnt > -1) // this is just being fought
             navigation_routerating(this, it, ratingscale, 5000);
         else if(it.goalentity.cnt == 0) // unclaimed
             navigation_routerating(this, it, ratingscale * 0.5, 5000);
         else if(it.goalentity.team != this.team) // other team's point
             navigation_routerating(this, it, ratingscale * 0.2, 5000);
     });
 }
void havocbot_role_dom (entity this)
Definition at line 400 of file gamemode_domination.qc.
References autocvar_bot_ai_strategyinterval, bot_strategytime, havocbot_goalrating_controlpoints(), havocbot_goalrating_items(), havocbot_goalrating_waypoints(), IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), origin, and time.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if (this.bot_strategytime < time)
     {
         this.bot_strategytime = time + autocvar_bot_ai_strategyinterval;
         navigation_goalrating_start(this);
         havocbot_goalrating_controlpoints(this, 10000, this.origin, 15000);
         havocbot_goalrating_items(this, 8000, this.origin, 8000);
         //havocbot_goalrating_enemyplayers(this, 3000, this.origin, 2000);
         havocbot_goalrating_waypoints(this, 1, this.origin, 3000);
         navigation_goalrating_end(this);
     }
 }
MUTATOR_HOOKFUNCTION (dom , CheckAllowedTeams)
Definition at line 417 of file gamemode_domination.qc.
References c1, c2, c3, c4, classname, domination_teams, entity(), find(), M_ARGV, NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, and string_null.
 {
     // fallback?
     M_ARGV(0, float) = domination_teams;
     string ret_string = "dom_team";
     entity head = find(NULL, classname, ret_string);
     while(head)
     {
         if(head.netname != "")
         {
             switch(head.team)
             {
                 case NUM_TEAM_1: c1 = 0; break;
                 case NUM_TEAM_2: c2 = 0; break;
                 case NUM_TEAM_3: c3 = 0; break;
                 case NUM_TEAM_4: c4 = 0; break;
             }
         }
         head = find(head, classname, ret_string);
     }
     M_ARGV(1, string) = string_null;
     return true;
 }
MUTATOR_HOOKFUNCTION (dom , reset_map_players)
Definition at line 445 of file gamemode_domination.qc.
References domination_roundbased, FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, pps_blue, pps_pink, pps_red, pps_yellow, PutClientInServer(), set_dom_state(), and total_pps.
 {
     total_pps = 0, pps_red = 0, pps_blue = 0, pps_yellow = 0, pps_pink = 0;
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(
         PutClientInServer(it);
         if(domination_roundbased)
             it.player_blocked = 1;
         if(IS_REAL_CLIENT(it))
             set_dom_state(it);
     ));
     return true;
 }
MUTATOR_HOOKFUNCTION (dom , PlayerSpawn)
Definition at line 458 of file gamemode_domination.qc.
References domination_roundbased, entity(), M_ARGV, and round_handler_IsRoundStarted.
 {
     entity player = M_ARGV(0, entity);
     if(domination_roundbased)
     if(!round_handler_IsRoundStarted())
         player.player_blocked = 1;
     else
         player.player_blocked = 0;
 }
MUTATOR_HOOKFUNCTION (dom , ClientConnect)
Definition at line 469 of file gamemode_domination.qc.
References entity(), M_ARGV, and set_dom_state().
 {
     entity player = M_ARGV(0, entity);
     set_dom_state(player);
 }
MUTATOR_HOOKFUNCTION (dom , HavocBot_ChooseRole)
Definition at line 476 of file gamemode_domination.qc.
References entity(), havocbot_role_dom(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     bot.havocbot_role = havocbot_role_dom;
     return true;
 }
void ScoreRules_dom (int teams)
Definition at line 558 of file gamemode_domination.qc.
References autocvar_g_domination_disable_frags, domination_roundbased, ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_basics(), ScoreRules_basics_end(), SFL_SORT_PRIO_PRIMARY, ST_DOM_CAPS, and ST_DOM_TICKS.
Referenced by dom_DelayedInit().
 {
     if(domination_roundbased)
     {
         ScoreRules_basics(teams, SFL_SORT_PRIO_PRIMARY, 0, true);
         ScoreInfo_SetLabel_TeamScore  (ST_DOM_CAPS, "caps", SFL_SORT_PRIO_PRIMARY);
         ScoreInfo_SetLabel_PlayerScore(SP_DOM_TAKES, "takes", 0);
         ScoreRules_basics_end();
     }
     else
     {
         float sp_domticks, sp_score;
         sp_score = sp_domticks = 0;
         if(autocvar_g_domination_disable_frags)
             sp_domticks = SFL_SORT_PRIO_PRIMARY;
         else
             sp_score = SFL_SORT_PRIO_PRIMARY;
         ScoreRules_basics(teams, sp_score, sp_score, true);
         ScoreInfo_SetLabel_TeamScore  (ST_DOM_TICKS,    "ticks",     sp_domticks);
         ScoreInfo_SetLabel_PlayerScore(SP_DOM_TICKS,    "ticks",     sp_domticks);
         ScoreInfo_SetLabel_PlayerScore(SP_DOM_TAKES,    "takes",     0);
         ScoreRules_basics_end();
     }
 }
void set_dom_state (entity e)
Definition at line 22 of file gamemode_domination.qc.
References domination_teams, pps_blue, pps_pink, pps_red, pps_yellow, and total_pps.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     e.dom_total_pps = total_pps;
     e.dom_pps_red = pps_red;
     e.dom_pps_blue = pps_blue;
     if(domination_teams >= 3)
         e.dom_pps_yellow = pps_yellow;
     if(domination_teams >= 4)
         e.dom_pps_pink = pps_pink;
 }
spawnfunc (dom_controlpoint)
Definition at line 487 of file gamemode_domination.qc.
References autocvar_g_domination_point_fullbright, dom_controlpoint_setup(), EF_FULLBRIGHT, EF_LOWPRECISION, effects, g_domination, g_dompoints, IL_PUSH(), nextthink, scale, setthink, and time.
 {
     if(!g_domination)
     {
         delete(this);
         return;
     }
     setthink(this, dom_controlpoint_setup);
     this.nextthink = time + 0.1;
     this.reset = dom_controlpoint_setup;
     if(!this.scale)
         this.scale = 0.6;
     this.effects = this.effects | EF_LOWPRECISION;
     if (autocvar_g_domination_point_fullbright)
         this.effects |= EF_FULLBRIGHT;
     IL_PUSH(g_dompoints, this);
 }
spawnfunc (dom_team)
Definition at line 534 of file gamemode_domination.qc.
References autocvar_g_domination_teams_override, classname, cnt, dmg, g_domination, mdl, model, modelindex, noise, noise1, precache_sound(), and team.
 {
     if(!g_domination || autocvar_g_domination_teams_override >= 2)
     {
         delete(this);
         return;
     }
     precache_model(this.model);
     if (this.noise != "")
         precache_sound(this.noise);
     if (this.noise1 != "")
         precache_sound(this.noise1);
     this.classname = "dom_team";
     _setmodel(this, this.model); // precision not needed
     this.mdl = this.model;
     this.dmg = this.modelindex;
     this.model = "";
     this.modelindex = 0;
     // this would have to be changed if used in quakeworld
     if(this.cnt)
         this.team = this.cnt + 1; // WHY are these different anyway?
 }
Variable Documentation
int autocvar_g_domination_default_teams
Definition at line 7 of file gamemode_domination.qc.
Referenced by dom_DelayedInit().
bool autocvar_g_domination_disable_frags
Definition at line 8 of file gamemode_domination.qc.
Referenced by ScoreRules_dom().
int autocvar_g_domination_point_amt
Definition at line 9 of file gamemode_domination.qc.
Referenced by dom_controlpoint_setup(), dompoint_captured(), and dompointthink().
bool autocvar_g_domination_point_fullbright
Definition at line 10 of file gamemode_domination.qc.
Referenced by spawnfunc().
float autocvar_g_domination_point_rate
Definition at line 13 of file gamemode_domination.qc.
Referenced by dom_controlpoint_setup(), dompoint_captured(), and dompointthink().
float autocvar_g_domination_round_timelimit
Definition at line 11 of file gamemode_domination.qc.
Referenced by dom_DelayedInit(), and Domination_CheckWinner().
int autocvar_g_domination_teams_override
Definition at line 14 of file gamemode_domination.qc.
Referenced by dom_DelayedInit(), and spawnfunc().
float autocvar_g_domination_warmup
Definition at line 12 of file gamemode_domination.qc.
Referenced by dom_DelayedInit(), and Domination_CheckWinner().
bool g_domination
Definition at line 5 of file gamemode_domination.qc.
Referenced by dom_Initialize(), and spawnfunc().
float total_controlpoints
Definition at line 298 of file gamemode_domination.qc.
Referenced by Domination_count_controlpoints().