Xonotic: common/debug.qh File Reference
debug.qh File Reference
Macros
#define DEBUG_H
Functions
GENERIC_COMMAND (bufstr_get,"Examine a string buffer object")
GENERIC_COMMAND (version,"Print the current version")
Variables
bool debug
int sv_entnum
bool autocvar_debugdraw
Macro Definition Documentation
#define DEBUG_H
Definition at line 2 of file debug.qh.
Function Documentation
GENERIC_COMMAND (bufstr_get , "Examine a string buffer object")
Definition at line 166 of file debug.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetProgramCommandPrefix(), LOG_INFO, LOG_INFOF, s, stof(), and strcat().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             int bufhandle = stof(argv(1));
             int string_index = stof(argv(2));
             string s = bufstr_get(bufhandle, string_index);
             LOG_INFOF("%s\n", s);
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO(strcat("\nUsage:^3 ", GetProgramCommandPrefix(), " bufstr_get bufhandle string_index"));
             return;
         }
     }
 }
GENERIC_COMMAND (version , "Print the current version")
Definition at line 188 of file debug.qh.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetProgramCommandPrefix(), LOG_INFO, and strcat().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             LOG_INFO(WATERMARK "\n");
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO(strcat("\nUsage:^3 ", GetProgramCommandPrefix(), " version"));
             return;
         }
     }
 }
Variable Documentation
bool autocvar_debugdraw
Definition at line 45 of file debug.qh.
bool debug
Definition at line 5 of file debug.qh.
int sv_entnum
Definition at line 6 of file debug.qh.