Xonotic: menu/xonotic/playlist.qh File Reference
playlist.qh File Reference
#include "listbox.qh"
Functions
METHOD (XonoticPlayList, configureXonoticPlayList, void(entity))
METHOD (XonoticPlayList, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticPlayList, draw, void(entity))
METHOD (XonoticPlayList, drawListBoxItem, void(entity, int, vector, bool, bool))
METHOD (XonoticPlayList, stopSound, void(entity))
METHOD (XonoticPlayList, startSound, void(entity, float))
METHOD (XonoticPlayList, resumeSound, void(entity))
METHOD (XonoticPlayList, pauseSound, void(entity))
METHOD (XonoticPlayList, doubleClickListBoxItem, void(entity, float, vector))
METHOD (XonoticPlayList, keyDown, float(entity, float, float, float))
METHOD (XonoticPlayList, mouseDrag, float(entity, vector))
METHOD (XonoticPlayList, addToPlayList, void(entity, string))
METHOD (XonoticPlayList, removeSelectedFromPlayList, void(entity))
entity makeXonoticPlayList ()
void PlayList_Remove (entity btn, entity me)
void PlayList_Remove_All (entity btn, entity me)
void StopSound_Click (entity btn, entity me)
void StartSound_Click (entity btn, entity me)
void PauseSound_Click (entity btn, entity me)
void PrevSound_Click (entity btn, entity me)
void NextSound_Click (entity btn, entity me)
Function Documentation
entity makeXonoticPlayList ()
Definition at line 3 of file playlist.qc.
References entity(), me, and NEW.
Referenced by XonoticMusicPlayerTab_fill().
 {
     entity me;
     me = NEW(XonoticPlayList);
     me.configureXonoticPlayList(me);
     return me;
 }
METHOD (XonoticPlayList , configureXonoticPlayList , void(entity))
METHOD (XonoticPlayList , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticPlayList , draw , void(entity))
METHOD (XonoticPlayList , drawListBoxItem , void(entity, int, vector, bool, bool))
METHOD (XonoticPlayList , stopSound , void(entity))
METHOD (XonoticPlayList , startSound , void(entity, float))
METHOD (XonoticPlayList , resumeSound , void(entity))
METHOD (XonoticPlayList , pauseSound , void(entity))
METHOD (XonoticPlayList , doubleClickListBoxItem , void(entity, float, vector))
METHOD (XonoticPlayList , keyDown , float(entity, float, float, float))
METHOD (XonoticPlayList , mouseDrag , float(entity, vector))
METHOD (XonoticPlayList , addToPlayList , void(entity, string))
METHOD (XonoticPlayList , removeSelectedFromPlayList , void(entity))
void NextSound_Click (entity btn, entity me)
Definition at line 219 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.startSound(me, +1);
 }
void PauseSound_Click (entity btn, entity me)
Definition at line 240 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.pauseSound(me);
 }
void PlayList_Remove (entity btn, entity me)
Definition at line 90 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.removeSelectedFromPlayList(me);
 }
void PlayList_Remove_All (entity btn, entity me)
Definition at line 95 of file playlist.qc.
References cvar_set.
Referenced by XonoticMusicPlayerTab_fill().
 {
     cvar_set("music_playlist_list0", "");
     me.stopSound(me);
     me.selectedItem = 0;
 }
void PrevSound_Click (entity btn, entity me)
Definition at line 214 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.startSound(me, -1);
 }
void StartSound_Click (entity btn, entity me)
Definition at line 209 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.startSound(me, 0);
 }
void StopSound_Click (entity btn, entity me)
Definition at line 171 of file playlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.stopSound(me);
 }