Xonotic: common/gamemodes/gamemode/lms/sv_lms.qc File Reference
sv_lms.qc File Reference
#include "sv_lms.qh"
#include <common/mutators/mutator/instagib/items.qh>
#include <server/campaign.qh>
#include <server/command/_mod.qh>
#include <server/world.qh>
#include <server/items/items.qh>
Functions
void ClearWinners ()
void lms_extralife (entity this)
void lms_Initialize ()
int LMS_NewPlayerLives ()
void lms_RemovePlayer (entity player)
MUTATOR_HOOKFUNCTION (lms, reset_map_global)
MUTATOR_HOOKFUNCTION (lms, reset_map_players)
MUTATOR_HOOKFUNCTION (lms, ReadLevelCvars)
MUTATOR_HOOKFUNCTION (lms, PutClientInServer)
MUTATOR_HOOKFUNCTION (lms, ForbidSpawn)
MUTATOR_HOOKFUNCTION (lms, PlayerDies)
MUTATOR_HOOKFUNCTION (lms, ClientDisconnect)
MUTATOR_HOOKFUNCTION (lms, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (lms, ClientConnect)
MUTATOR_HOOKFUNCTION (lms, AutoJoinOnConnection)
MUTATOR_HOOKFUNCTION (lms, PlayerPreThink)
MUTATOR_HOOKFUNCTION (lms, PlayerRegen)
MUTATOR_HOOKFUNCTION (lms, ForbidThrowCurrentWeapon)
MUTATOR_HOOKFUNCTION (lms, GiveFragsForKill)
MUTATOR_HOOKFUNCTION (lms, SetStartItems)
MUTATOR_HOOKFUNCTION (lms, ForbidPlayerScore_Clear)
MUTATOR_HOOKFUNCTION (lms, FilterItemDefinition)
MUTATOR_HOOKFUNCTION (lms, OnEntityPreSpawn)
MUTATOR_HOOKFUNCTION (lms, ItemTouch)
MUTATOR_HOOKFUNCTION (lms, Bot_FixCount, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (lms, ClientCommand_Spectate)
MUTATOR_HOOKFUNCTION (lms, CheckRules_World)
MUTATOR_HOOKFUNCTION (lms, SetWeaponArena)
MUTATOR_HOOKFUNCTION (lms, GetPlayerStatus)
MUTATOR_HOOKFUNCTION (lms, AddPlayerScore)
int WinningCondition_LMS ()
Variables
int autocvar_g_lms_extra_lives
bool autocvar_g_lms_join_anytime
int autocvar_g_lms_last_join
bool autocvar_g_lms_regenerate
Function Documentation
ClearWinners()
void ClearWinners ()
Definition at line 1404 of file world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by CheckRules_World(), LMS_NewPlayerLives(), WinningCondition_LMS(), WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), { it.winning = 0; });
 }
lms_extralife()
void lms_extralife (entity this)
Definition at line 354 of file sv_lms.qc.
References StartItem().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     StartItem(this, ITEM_ExtraLife);
 }
lms_Initialize()
void lms_Initialize ()
Definition at line 453 of file sv_lms.qc.
References lms_lowest_lives.
Referenced by REGISTER_MUTATOR().
 {
     lms_lowest_lives = 999;
 }
LMS_NewPlayerLives()
int LMS_NewPlayerLives ()
Definition at line 15 of file sv_lms.qc.
References autocvar_g_lms_join_anytime, autocvar_g_lms_last_join, bound(), ClearWinners(), floor(), lms_lowest_lives, and max().
Referenced by MUTATOR_HOOKFUNCTION(), and WinningCondition_LMS().
 {
     int fl = floor(autocvar_fraglimit);
     if(fl == 0 || fl > 999)
         fl = 999;
     // first player has left the game for dying too much? Nobody else can get in.
     if(lms_lowest_lives < 1)
         return 0;
     if(!autocvar_g_lms_join_anytime)
         if(lms_lowest_lives < fl - max(0, floor(autocvar_g_lms_last_join)))
             return 0;
     return bound(1, lms_lowest_lives, fl);
 }
lms_RemovePlayer()
void lms_RemovePlayer (entity player)
Definition at line 187 of file sv_lms.qc.
References CS(), FOREACH_CLIENT, FRAGS_PLAYER_OUT_OF_GAME, FRAGS_SPECTATOR, GameRules_scoring_add, if(), IS_PLAYER, killcount, NULL, TRANSMUTE(), and warmup_stage.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     static int quitters = 0;
     float player_rank = GameRules_scoring_add(player, LMS_RANK, 0);
     if (!player_rank)
     {
         if (player.lms_spectate_warning < 2)
         {
             player.frags = FRAGS_PLAYER_OUT_OF_GAME;
             int pl_cnt = 0;
             FOREACH_CLIENT(IS_PLAYER(it) && it.frags != FRAGS_PLAYER_OUT_OF_GAME, {
                 pl_cnt++;
             });
             GameRules_scoring_add(player, LMS_RANK, pl_cnt + 1);
         }
         else
         {
             FOREACH_CLIENT(true, {
                 if (it.frags == FRAGS_PLAYER_OUT_OF_GAME)
                 {
                     float it_rank = GameRules_scoring_add(it, LMS_RANK, 0);
                     if (it_rank > player_rank && it_rank <= 256)
                         GameRules_scoring_add(it, LMS_RANK, -1);
                 }
                 else if (it.frags != FRAGS_SPECTATOR)
                 {
                     float tl = GameRules_scoring_add(it, LMS_LIVES, 0);
                     if(tl < lms_lowest_lives)
                         lms_lowest_lives = tl;
                 }
             });
             GameRules_scoring_add(player, LMS_RANK, 665 - quitters); // different from 666
             if(!warmup_stage)
             {
                 GameRules_scoring_add(player, LMS_LIVES, -GameRules_scoring_add(player, LMS_LIVES, 0));
                 ++quitters;
             }
             player.frags = FRAGS_PLAYER_OUT_OF_GAME;
             TRANSMUTE(Observer, player);
         }
     }
     if (CS(player).killcount != FRAGS_SPECTATOR && player.lms_spectate_warning < 3)
     {
         if (GameRules_scoring_add(player, LMS_RANK, 0) > 0 && player.lms_spectate_warning < 2)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_LMS_NOLIVES, player.netname);
         else
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_LMS_FORFEIT, player.netname);
     }
 }
MUTATOR_HOOKFUNCTION() [1/25]
MUTATOR_HOOKFUNCTION (lms , reset_map_global)
Definition at line 118 of file sv_lms.qc.
References lms_lowest_lives.
 {
     lms_lowest_lives = 999;
 }
MUTATOR_HOOKFUNCTION() [2/25]
MUTATOR_HOOKFUNCTION (lms , reset_map_players)
Definition at line 123 of file sv_lms.qc.
References FOREACH_CLIENT, FRAGS_PLAYER, GameRules_scoring_add, LMS_NewPlayerLives(), PutClientInServer(), and TRANSMUTE().
 {
     FOREACH_CLIENT(true, {
         TRANSMUTE(Player, it);
         it.frags = FRAGS_PLAYER;
         GameRules_scoring_add(it, LMS_LIVES, LMS_NewPlayerLives());
         PutClientInServer(it);
     });
 }
MUTATOR_HOOKFUNCTION() [3/25]
MUTATOR_HOOKFUNCTION (lms , ReadLevelCvars)
Definition at line 135 of file sv_lms.qc.
References sv_ready_restart_after_countdown.
 {
     // incompatible
     sv_ready_restart_after_countdown = 0;
 }
MUTATOR_HOOKFUNCTION() [4/25]
MUTATOR_HOOKFUNCTION (lms , PutClientInServer)
Definition at line 141 of file sv_lms.qc.
References entity(), FRAGS_SPECTATOR, GameRules_scoring_add, lms_lowest_lives, M_ARGV, TRANSMUTE(), and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(player.frags == FRAGS_SPECTATOR)
         TRANSMUTE(Observer, player);
     else
     {
         float tl = GameRules_scoring_add(player, LMS_LIVES, 0);
         if(tl < lms_lowest_lives)
             lms_lowest_lives = tl;
         if(tl <= 0)
             TRANSMUTE(Observer, player);
         if(warmup_stage)
             GameRules_scoring_add(player, LMS_RANK, -GameRules_scoring_add(player, LMS_RANK, 0));
     }
 }
MUTATOR_HOOKFUNCTION() [5/25]
MUTATOR_HOOKFUNCTION (lms , ForbidSpawn)
Definition at line 159 of file sv_lms.qc.
References entity(), FRAGS_SPECTATOR, GameRules_scoring_add, M_ARGV, and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(warmup_stage)
         return false;
     if(player.frags == FRAGS_SPECTATOR || GameRules_scoring_add(player, LMS_LIVES, 0) <= 0)
     {
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_LMS_NOLIVES);
         return true;
     }
     return false;
 }
MUTATOR_HOOKFUNCTION() [6/25]
MUTATOR_HOOKFUNCTION (lms , PlayerDies)
Definition at line 173 of file sv_lms.qc.
References entity(), GameRules_scoring_add, M_ARGV, RESPAWN_FORCE, RESPAWN_SILENT, and time.
 {
     entity frag_target = M_ARGV(2, entity);
     float tl = GameRules_scoring_add(frag_target, LMS_LIVES, 0);
     if (tl <= 0)
     {
         frag_target.respawn_flags = RESPAWN_SILENT;
         // prevent unwanted sudden rejoin as spectator and movement of spectator camera
         frag_target.respawn_time = time + 2;
     }
     frag_target.respawn_flags |= RESPAWN_FORCE;
 }
MUTATOR_HOOKFUNCTION() [7/25]
MUTATOR_HOOKFUNCTION (lms , ClientDisconnect)
Definition at line 238 of file sv_lms.qc.
References entity(), lms_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // no further message other than the disconnect message
     player.lms_spectate_warning = 3;
     lms_RemovePlayer(player);
 }
MUTATOR_HOOKFUNCTION() [8/25]
MUTATOR_HOOKFUNCTION (lms , MakePlayerObserver)
Definition at line 248 of file sv_lms.qc.
References entity(), IS_PLAYER, lms_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if (!IS_PLAYER(player))
         return true;
     lms_RemovePlayer(player);
     return true;  // prevent team reset
 }
MUTATOR_HOOKFUNCTION() [9/25]
MUTATOR_HOOKFUNCTION (lms , ClientConnect)
Definition at line 259 of file sv_lms.qc.
References entity(), FRAGS_SPECTATOR, GameRules_scoring_add, LMS_NewPlayerLives(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(GameRules_scoring_add(player, LMS_LIVES, LMS_NewPlayerLives()) <= 0)
     {
         GameRules_scoring_add(player, LMS_RANK, 666); // mark as forced spectator for the hud code
         player.frags = FRAGS_SPECTATOR;
     }
 }
MUTATOR_HOOKFUNCTION() [10/25]
MUTATOR_HOOKFUNCTION (lms , AutoJoinOnConnection)
Definition at line 271 of file sv_lms.qc.
References autocvar_g_campaign.
 {
     if(autocvar_g_campaign)
         return false;
     return true;
 }
MUTATOR_HOOKFUNCTION() [11/25]
MUTATOR_HOOKFUNCTION (lms , PlayerPreThink)
Definition at line 278 of file sv_lms.qc.
References DEAD_DYING, DEAD_RESPAWNING, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.deadflag == DEAD_DYING)
         player.deadflag = DEAD_RESPAWNING;
 }
MUTATOR_HOOKFUNCTION() [12/25]
MUTATOR_HOOKFUNCTION (lms , PlayerRegen)
Definition at line 286 of file sv_lms.qc.
References autocvar_g_lms_regenerate.
 {
     if(autocvar_g_lms_regenerate)
         return false;
     return true;
 }
MUTATOR_HOOKFUNCTION() [13/25]
MUTATOR_HOOKFUNCTION (lms , ForbidThrowCurrentWeapon)
Definition at line 293 of file sv_lms.qc.
 {
     // forbode!
     return true;
 }
MUTATOR_HOOKFUNCTION() [14/25]
MUTATOR_HOOKFUNCTION (lms , GiveFragsForKill)
Definition at line 299 of file sv_lms.qc.
References entity(), FOREACH_CLIENT, FRAGS_PLAYER_OUT_OF_GAME, GameRules_scoring_add, IS_PLAYER, lms_lowest_lives, M_ARGV, and warmup_stage.
 {
     entity frag_target = M_ARGV(1, entity);
     if (!warmup_stage)
     {
         // remove a life
         int tl = GameRules_scoring_add(frag_target, LMS_LIVES, -1);
         if(tl < lms_lowest_lives)
             lms_lowest_lives = tl;
         if(tl <= 0)
         {
             int pl_cnt = 0;
             FOREACH_CLIENT(IS_PLAYER(it) && it.frags != FRAGS_PLAYER_OUT_OF_GAME, {
                 pl_cnt++;
             });
             frag_target.frags = FRAGS_PLAYER_OUT_OF_GAME;
             GameRules_scoring_add(frag_target, LMS_RANK, pl_cnt);
         }
     }
     M_ARGV(2, float) = 0; // frag score
     return true;
 }
MUTATOR_HOOKFUNCTION() [15/25]
MUTATOR_HOOKFUNCTION (lms , SetStartItems)
Definition at line 324 of file sv_lms.qc.
References cvar(), start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, and warmup_start_health.
 {
     start_items &= ~(IT_UNLIMITED_AMMO | IT_UNLIMITED_SUPERWEAPONS);
     start_health       = warmup_start_health       = cvar("g_lms_start_health");
     start_armorvalue   = warmup_start_armorvalue   = cvar("g_lms_start_armor");
     start_ammo_shells  = warmup_start_ammo_shells  = cvar("g_lms_start_ammo_shells");
     start_ammo_nails   = warmup_start_ammo_nails   = cvar("g_lms_start_ammo_nails");
     start_ammo_rockets = warmup_start_ammo_rockets = cvar("g_lms_start_ammo_rockets");
     start_ammo_cells   = warmup_start_ammo_cells   = cvar("g_lms_start_ammo_cells");
     start_ammo_plasma  = warmup_start_ammo_plasma  = cvar("g_lms_start_ammo_plasma");
     start_ammo_fuel    = warmup_start_ammo_fuel    = cvar("g_lms_start_ammo_fuel");
 }
MUTATOR_HOOKFUNCTION() [16/25]
MUTATOR_HOOKFUNCTION (lms , ForbidPlayerScore_Clear)
Definition at line 337 of file sv_lms.qc.
 {
     // don't clear player score
     return true;
 }
MUTATOR_HOOKFUNCTION() [17/25]
MUTATOR_HOOKFUNCTION (lms , FilterItemDefinition)
Definition at line 343 of file sv_lms.qc.
References autocvar_g_lms_extra_lives, entity(), and M_ARGV.
 {
     entity definition = M_ARGV(0, entity);
     if (autocvar_g_lms_extra_lives && definition == ITEM_ExtraLife)
     {
         return false;
     }
     return true;
 }
MUTATOR_HOOKFUNCTION() [18/25]
MUTATOR_HOOKFUNCTION (lms , OnEntityPreSpawn)
Definition at line 359 of file sv_lms.qc.
References autocvar_g_lms_extra_lives, autocvar_g_powerups, entity(), lms_extralife(), M_ARGV, MUTATOR_RETURNVALUE, setorigin(), setthink, spawn(), and time.
 {
     if (MUTATOR_RETURNVALUE) return false;
     if (!autocvar_g_powerups) return false;
     if (!autocvar_g_lms_extra_lives) return false;
     entity ent = M_ARGV(0, entity);
     // Can't use .itemdef here
     if (ent.classname != "item_health_mega") return false;
     entity e = spawn();
     setthink(e, lms_extralife);
     e.nextthink = time + 0.1;
     e.spawnflags = ent.spawnflags;
     e.noalign = ent.noalign;
     setorigin(e, ent.origin);
     return true;
 }
MUTATOR_HOOKFUNCTION() [19/25]
MUTATOR_HOOKFUNCTION (lms , ItemTouch)
Definition at line 381 of file sv_lms.qc.
References autocvar_g_lms_extra_lives, entity(), GameRules_scoring_add, M_ARGV, MUT_ITEMTOUCH_CONTINUE, MUT_ITEMTOUCH_PICKUP, and MUTATOR_RETURNVALUE.
 {
     if(MUTATOR_RETURNVALUE) return false;
     entity item = M_ARGV(0, entity);
     entity toucher = M_ARGV(1, entity);
     if(item.itemdef == ITEM_ExtraLife)
     {
         Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_EXTRALIVES, autocvar_g_lms_extra_lives);
         GameRules_scoring_add(toucher, LMS_LIVES, autocvar_g_lms_extra_lives);
         return MUT_ITEMTOUCH_PICKUP;
     }
     return MUT_ITEMTOUCH_CONTINUE;
 }
MUTATOR_HOOKFUNCTION() [20/25]
MUTATOR_HOOKFUNCTION (lms , Bot_FixCount , CBC_ORDER_EXCLUSIVE)
Definition at line 398 of file sv_lms.qc.
References FOREACH_CLIENT, IS_REAL_CLIENT, and M_ARGV.
 {
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         ++M_ARGV(0, int); // activerealplayers
         ++M_ARGV(1, int); // realplayers
     });
     return true;
 }
MUTATOR_HOOKFUNCTION() [21/25]
MUTATOR_HOOKFUNCTION (lms , ClientCommand_Spectate)
Definition at line 408 of file sv_lms.qc.
References entity(), FRAGS_PLAYER_OUT_OF_GAME, FRAGS_SPECTATOR, M_ARGV, MUT_SPECCMD_CONTINUE, MUT_SPECCMD_RETURN, sprint(), and warmup_stage.
 {
     entity player = M_ARGV(0, entity);
     if(warmup_stage || player.lms_spectate_warning)
     {
         // for the forfeit message...
         player.lms_spectate_warning = 2;
     }
     else
     {
         if(player.frags != FRAGS_SPECTATOR && player.frags != FRAGS_PLAYER_OUT_OF_GAME)
         {
             player.lms_spectate_warning = 1;
             sprint(player, "WARNING: you won't be able to enter the game again after spectating in LMS. Use the same command again to spectate anyway.\n");
         }
         return MUT_SPECCMD_RETURN;
     }
     return MUT_SPECCMD_CONTINUE;
 }
MUTATOR_HOOKFUNCTION() [22/25]
MUTATOR_HOOKFUNCTION (lms , CheckRules_World)
Definition at line 429 of file sv_lms.qc.
References M_ARGV, and WinningCondition_LMS().
 {
     M_ARGV(0, float) = WinningCondition_LMS();
     return true;
 }
MUTATOR_HOOKFUNCTION() [23/25]
MUTATOR_HOOKFUNCTION (lms , SetWeaponArena)
Definition at line 435 of file sv_lms.qc.
References autocvar_g_lms_weaponarena, and M_ARGV.
 {
     if(M_ARGV(0, string) == "0" || M_ARGV(0, string) == "")
         M_ARGV(0, string) = autocvar_g_lms_weaponarena;
 }
MUTATOR_HOOKFUNCTION() [24/25]
MUTATOR_HOOKFUNCTION (lms , GetPlayerStatus)
Definition at line 441 of file sv_lms.qc.
 {
     return true;
 }
MUTATOR_HOOKFUNCTION() [25/25]
MUTATOR_HOOKFUNCTION (lms , AddPlayerScore)
Definition at line 446 of file sv_lms.qc.
References entity(), and M_ARGV.
 {
     if(game_stopped)
     if(M_ARGV(0, entity) == SP_LMS_RANK) // score field
         return true; // allow writing to this field in intermission as it is needed for newly joining players
 }
WinningCondition_LMS()
int WinningCondition_LMS ()
Definition at line 37 of file sv_lms.qc.
References autocvar_g_campaign, ClearWinners(), entity(), FOREACH_CLIENT, FRAGS_PLAYER_OUT_OF_GAME, GameRules_scoring_add, IS_PLAYER, IS_REAL_CLIENT, LMS_NewPlayerLives(), LOG_TRACE, NULL, SetWinners(), warmup_stage, winning, WINNING_NEVER, WINNING_NO, WINNING_YES, WinningConditionHelper(), WinningConditionHelper_secondscore, WinningConditionHelper_topscore, and WinningConditionHelper_winner.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity first_player = NULL;
     int totalplayers = 0;
     FOREACH_CLIENT(IS_PLAYER(it) && it.frags != FRAGS_PLAYER_OUT_OF_GAME, {
         if (!totalplayers)
             first_player = it;
         ++totalplayers;
     });
     if (totalplayers)
     {
         if (totalplayers > 1)
         {
             // two or more active players - continue with the game
             if (autocvar_g_campaign)
             {
                 FOREACH_CLIENT(IS_REAL_CLIENT(it), {
                     float pl_lives = GameRules_scoring_add(it, LMS_LIVES, 0);
                     if (!pl_lives)
                         return WINNING_YES; // human player lost, game over
                     break;
                 });
             }
         }
         else
         {
             // exactly one player?
             ClearWinners();
             SetWinners(winning, 0); // NOTE: exactly one player is still "player", so this works out
             if (LMS_NewPlayerLives())
             {
                 // game still running (that is, nobody got removed from the game by a frag yet)? then continue
                 return WINNING_NO;
             }
             else
             {
                 // a winner!
                 // and assign him his first place
                 GameRules_scoring_add(first_player, LMS_RANK, 1);
                 if(warmup_stage)
                     return WINNING_NO;
                 else
                     return WINNING_YES;
             }
         }
     }
     else
     {
         // nobody is playing at all...
         if (LMS_NewPlayerLives())
         {
             // wait for players...
         }
         else
         {
             // SNAFU (maybe a draw game?)
             ClearWinners();
             LOG_TRACE("No players, ending game.");
             return WINNING_YES;
         }
     }
     // When we get here, we have at least two players who are actually LIVING,
     // now check if the top two players have equal score.
     WinningConditionHelper(NULL);
     ClearWinners();
     if(WinningConditionHelper_winner)
         WinningConditionHelper_winner.winning = true;
     if(WinningConditionHelper_topscore == WinningConditionHelper_secondscore)
         return WINNING_NEVER;
     // Top two have different scores? Way to go for our beloved TIMELIMIT!
     return WINNING_NO;
 }
Variable Documentation
autocvar_g_lms_extra_lives
int autocvar_g_lms_extra_lives
Definition at line 9 of file sv_lms.qc.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_lms_join_anytime
bool autocvar_g_lms_join_anytime
Definition at line 10 of file sv_lms.qc.
Referenced by LMS_NewPlayerLives().
autocvar_g_lms_last_join
int autocvar_g_lms_last_join
Definition at line 11 of file sv_lms.qc.
Referenced by LMS_NewPlayerLives().
autocvar_g_lms_regenerate
bool autocvar_g_lms_regenerate
Definition at line 12 of file sv_lms.qc.
Referenced by MUTATOR_HOOKFUNCTION().