Xonotic: common/effects/qc/globalsound.qh File Reference
globalsound.qh File Reference
Macros
#define GLOBALSOUND_H
#define GlobalSounds_from(i) _GlobalSounds_from(i, NULL)
#define PlayerSounds_from(i) _PlayerSounds_from(i, NULL)
#define REGISTER_GLOBALSOUND(id, str)
#define REGISTER_PLAYERSOUND(id)
#define REGISTER_VOICEMSG(id, vt)
Functions
void ClearPlayerSounds (entity this)
string GetPlayerSoundSampleField (string type)
entity GetVoiceMessage (string type)
string GetVoiceMessageSampleField (string type)
float LoadPlayerSounds (entity this, string f, bool strict)
PRECACHE (GlobalSounds)
void PrecacheGlobalSound (string samplestring)
void PrecachePlayerSounds (string f)
STATIC_INIT (PlayerSounds_renumber)
STATIC_INIT (GlobalSounds_renumber)
STATIC_INIT (allvoicesamples)
void UpdatePlayerSounds (entity this)
Variables
string allvoicesamples
bool GetPlayerSoundSampleField_notFound
bool instanceOfVoiceMessage
string m_globalsoundstr
string m_playersoundfld
string m_playersoundstr
int m_playersoundvt
const int VOICETYPE_AUTOTAUNT = 14
const int VOICETYPE_LASTATTACKER = 12
const int VOICETYPE_LASTATTACKER_ONLY = 13
const int VOICETYPE_PLAYERSOUND = 10
const int VOICETYPE_TAUNT = 15
const int VOICETYPE_TEAMRADIO = 11
Macro Definition Documentation
#define GLOBALSOUND_H
Definition at line 2 of file globalsound.qh.
#define GlobalSounds_from (i) _GlobalSounds_from(i, NULL)
Definition at line 88 of file globalsound.qh.
#define PlayerSounds_from (i) _PlayerSounds_from(i, NULL)
Definition at line 15 of file globalsound.qh.
#define REGISTER_GLOBALSOUND (id, str)
Value:
REGISTER(GlobalSounds, GS, id, m_id, new_pure(GlobalSound)) \
    { \
        this.m_globalsoundstr = str; \
    }
Definition at line 89 of file globalsound.qh.
#define REGISTER_PLAYERSOUND (id)
Value:
.string _playersound_##id; \
    REGISTER(PlayerSounds, playersound, id, m_id, new_pure(PlayerSound)) \
    { \
        this.m_playersoundstr = #id; \
        this.m_playersoundfld = _playersound_##id; \
    }
Definition at line 16 of file globalsound.qh.
#define REGISTER_VOICEMSG (id, vt)
Value:
.string _playersound_##id; \
    REGISTER(PlayerSounds, playersound, id, m_id, new_pure(VoiceMessage)) \
    { \
        this.instanceOfVoiceMessage = true; \
        this.m_playersoundstr = #id; \
        this.m_playersoundfld = _playersound_##id; \
        this.m_playersoundvt = vt; \
    }
Definition at line 44 of file globalsound.qh.
Function Documentation
void ClearPlayerSounds (entity this)
string GetPlayerSoundSampleField (string type)
entity GetVoiceMessage (string type)
Referenced by ClientCommand_voice().
string GetVoiceMessageSampleField (string type)
float LoadPlayerSounds (entity this, string f, bool strict)
PRECACHE (GlobalSounds)
Definition at line 102 of file globalsound.qh.
References FOREACH, and PrecacheGlobalSound().
 {
     FOREACH(GlobalSounds, true, PrecacheGlobalSound(it.m_globalsoundstr));
 }
void PrecacheGlobalSound (string samplestring)
Referenced by Monster_Sound_Precache(), and PRECACHE().
void PrecachePlayerSounds (string f)
Referenced by precache(), and precache_playermodel().
STATIC_INIT (PlayerSounds_renumber)
Definition at line 25 of file globalsound.qh.
References FOREACH.
 {
     FOREACH(PlayerSounds, true, it.m_id = i);
 }
STATIC_INIT (GlobalSounds_renumber)
Definition at line 96 of file globalsound.qh.
References FOREACH.
 {
     FOREACH(GlobalSounds, true, it.m_id = i);
 }
STATIC_INIT (allvoicesamples)
Definition at line 146 of file globalsound.qh.
References FOREACH, strcat(), strzone(), and substring().
 {
     FOREACH(PlayerSounds, it.instanceOfVoiceMessage, allvoicesamples = strcat(allvoicesamples, " ", it.m_playersoundstr));
     allvoicesamples = strzone(substring(allvoicesamples, 1, -1));
 }
void UpdatePlayerSounds (entity this)
Referenced by FixPlayermodel(), and setplayermodel().
Variable Documentation
string allvoicesamples
Definition at line 145 of file globalsound.qh.
Referenced by ClientCommand_voice().
bool GetPlayerSoundSampleField_notFound
Definition at line 112 of file globalsound.qh.
bool instanceOfVoiceMessage
Definition at line 42 of file globalsound.qh.
string m_globalsoundstr
Definition at line 86 of file globalsound.qh.
string m_playersoundfld
Definition at line 12 of file globalsound.qh.
string m_playersoundstr
Definition at line 11 of file globalsound.qh.
int m_playersoundvt
Definition at line 43 of file globalsound.qh.
const int VOICETYPE_AUTOTAUNT = 14
Definition at line 58 of file globalsound.qh.
Referenced by PlayerPreThink().
const int VOICETYPE_LASTATTACKER = 12
Definition at line 56 of file globalsound.qh.
const int VOICETYPE_LASTATTACKER_ONLY = 13
Definition at line 57 of file globalsound.qh.
Referenced by PlayerPreThink().
const int VOICETYPE_PLAYERSOUND = 10
Definition at line 54 of file globalsound.qh.
Referenced by DrownPlayer(), Monster_Sound(), PlayerDamage(), PlayerJump(), PM_check_hitground(), and PM_Footsteps().
const int VOICETYPE_TAUNT = 15
Definition at line 59 of file globalsound.qh.
const int VOICETYPE_TEAMRADIO = 11
Definition at line 55 of file globalsound.qh.