Xonotic: common/minigames/minigame/ps.qc File Reference
ps.qc File Reference
#include "ps.qh"
Functions
bool ps_draw (entity minigame)
entity ps_find_piece (entity minig, string tile)
void ps_move (entity minigame, entity player, string thepiece, string pos)
bool ps_move_piece (entity minigame, entity piece, string pos, int leti, int numb)
void ps_setup_pieces (entity minigame)
bool ps_tile_blacklisted (string tile)
bool ps_valid_tile (string tile)
bool ps_winning_piece (entity minigame)
REGISTER_MINIGAME (ps, _("Peg Solitaire"))
Variables
const int PS_LET_CNT = 7
const int PS_NUM_CNT = 7
const int PS_TILE_SIZE = 8
const float PS_TURN_DRAW = 0x0400
const float PS_TURN_MOVE = 0x0100
const float PS_TURN_TYPE = 0x0f00
const float PS_TURN_WIN = 0x0200
Function Documentation
bool ps_draw (entity minigame)
Definition at line 24 of file ps.qc.
References entity(), findentity(), NULL, and owner.
Referenced by ps_move().
 {
     int valid = 0;
     entity e = NULL;
     while( ( e = findentity(e,owner,minigame) ) )
         if( e.classname == "minigame_board_piece" )
         {
             ++valid;
         }
     return ((valid > 0) ? true : false);
 }
entity ps_find_piece (entity minig, string tile)
Definition at line 15 of file ps.qc.
References entity(), findentity(), NULL, and owner.
Referenced by ps_move(), ps_move_piece(), and ps_winning_piece().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile )
             return e;
     return NULL;
 }
void ps_move (entity minigame, entity player, string thepiece, string pos)
Definition at line 157 of file ps.qc.
References active_minigame, argv(), drawfill(), DRAWFLAG_ADDITIVE, DRAWFLAG_NORMAL, drawstring(), entity(), eX, eY, findentity(), FOREACH_MINIGAME_ENTITY, ftos(), hud_fontsize, HUD_Panel_DrawBg, int, K_DOWNARROW, K_ENTER, K_KP_DOWNARROW, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, K_SPACE, K_UPARROW, MINIG_SF_UPDATE, minigame_cmd, minigame_count_players(), minigame_drawcolorcodedstring_trunc(), minigame_drawcolorcodedstring_wrapped(), minigame_drawpic_centered(), minigame_drawstring_wrapped(), minigame_hud_denormalize(), minigame_hud_denormalize_size(), minigame_hud_fitsqare, minigame_hud_normalize(), minigame_hud_simpleboard(), minigame_relative_tile(), minigame_server_sendflags(), minigame_texture(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_name(), minigame_tile_number(), minigame_tile_pos(), mousepos, NULL, owner, panel_fg_alpha, ps_draw(), ps_find_piece(), ps_move_piece(), ps_setup_pieces(), PS_TURN_DRAW, PS_TURN_MOVE, PS_TURN_WIN, ps_valid_tile(), ps_winning_piece(), strcat(), strcpy, strfree, string_null, strzone(), and vector().
 {
     if ( minigame.minigame_flags & PS_TURN_MOVE )
     if ( pos )
     {
         if ( ps_valid_tile(pos) )
         if ( !ps_find_piece(minigame, pos) && ps_find_piece(minigame, thepiece) )
         {
             entity piece = ps_find_piece(minigame, thepiece);
             int number = minigame_tile_number(thepiece);
             int letter = minigame_tile_letter(thepiece);
             bool done = false;
             string try;
             try = minigame_tile_buildname(letter-1,number);
             if(ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter-2,number);
                 if(ps_valid_tile(try) && try == pos)
                     done = ps_move_piece(minigame, piece, pos, letter - 1, number);
             }
             try = minigame_tile_buildname(letter+1,number);
             if(!done && ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter+2,number);
                 if(ps_valid_tile(try) && try == pos)
                     done = ps_move_piece(minigame, piece, pos, letter + 1, number);
             }
             try = minigame_tile_buildname(letter,number-1);
             if(!done && ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter,number-2);
                 if(ps_valid_tile(try) && try == pos)
                     done = ps_move_piece(minigame, piece, pos, letter, number - 1);
             }
             try = minigame_tile_buildname(letter,number+1);
             if(!done && ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter,number+2);
                 if(ps_valid_tile(try) && try == pos)
                     done = ps_move_piece(minigame, piece, pos, letter, number + 1);
             }
             if(!done)
                 return; // didn't make a move
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
             if ( ps_winning_piece(minigame) )
             {
                 if(ps_draw(minigame))
                     minigame.minigame_flags = PS_TURN_DRAW;
                 else
                     minigame.minigame_flags = PS_TURN_WIN;
             }
             else
                 minigame.minigame_flags = PS_TURN_MOVE;
         }
     }
 }
bool ps_move_piece (entity minigame, entity piece, string pos, int leti, int numb)
Definition at line 136 of file ps.qc.
References entity(), MINIG_SF_ALL, minigame_server_sendflags(), minigame_tile_buildname(), ps_find_piece(), strcpy, and strfree.
Referenced by ps_move().
 {
     if(!piece)
         return false;
     if(ps_find_piece(minigame, pos))
         return false;
     entity middle = ps_find_piece(minigame, minigame_tile_buildname(leti,numb));
     if(!middle)
         return false;
     strfree(middle.netname);
     delete(middle);
     strcpy(piece.netname, pos);
     minigame_server_sendflags(piece,MINIG_SF_ALL);
     return true;
 }
void ps_setup_pieces (entity minigame)
Definition at line 116 of file ps.qc.
References entity(), floor(), MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_buildname(), msle_spawn(), PS_LET_CNT, PS_NUM_CNT, ps_valid_tile(), and strzone().
Referenced by ps_move().
 {
     int i, t;
     for(i = 0; i < PS_NUM_CNT; ++i)
     for(t = 0; t < PS_LET_CNT; ++t)
     {
         string try = minigame_tile_buildname(i,t);
         if(!ps_valid_tile(try))
             continue;
         if(i == floor(PS_NUM_CNT * 0.5) && t == floor(PS_LET_CNT * 0.5))
             continue; // middle piece is empty
         entity piece = msle_spawn(minigame,"minigame_board_piece");
         piece.team = 1; // init default team?
         piece.netname = strzone(minigame_tile_buildname(t,i));
         minigame_server_sendflags(piece,MINIG_SF_ALL);
     }
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
 }
bool ps_tile_blacklisted (string tile)
Definition at line 37 of file ps.qc.
References minigame_tile_letter(), and minigame_tile_number().
Referenced by ps_valid_tile().
 {
     int number = minigame_tile_number(tile);
     int letter = minigame_tile_letter(tile);
     if(letter < 2)
     {
         if(number < 2)
             return true;
         else if(number > PS_NUM_CNT - 3)
             return true;
     }
     if(letter > PS_LET_CNT - 3)
     {
         if(number < 2)
             return true;
         else if(number > PS_NUM_CNT - 3)
             return true;
     }
     return false;
 }
bool ps_valid_tile (string tile)
Definition at line 60 of file ps.qc.
References minigame_tile_letter(), minigame_tile_number(), PS_LET_CNT, and ps_tile_blacklisted().
Referenced by ps_move(), ps_setup_pieces(), and ps_winning_piece().
 {
     if ( !tile )
         return false;
     if(ps_tile_blacklisted(tile))
         return false;
     float number = minigame_tile_number(tile);
     float letter = minigame_tile_letter(tile);
     return 0 <= number && number < PS_NUM_CNT && 0 <= letter && letter < PS_LET_CNT;
 }
bool ps_winning_piece (entity minigame)
Definition at line 72 of file ps.qc.
References entity(), findentity(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), NULL, owner, ps_find_piece(), and ps_valid_tile().
Referenced by ps_move().
 {
     //int number = minigame_tile_number(piece.netname);
     //int letter = minigame_tile_letter(piece.netname);
     entity e = NULL;
     while ( ( e = findentity(e,owner,minigame) ) )
         if ( e.classname == "minigame_board_piece" )
         {
             int number = minigame_tile_number(e.netname);
             int letter = minigame_tile_letter(e.netname);
             string try = minigame_tile_buildname(letter - 1, number);
             if(ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter - 2, number);
                 if(ps_valid_tile(try) && !ps_find_piece(minigame,try))
                     return false; // a move is valid, abort!
             }
             try = minigame_tile_buildname(letter + 1, number);
             if(ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter + 2, number);
                 if(ps_valid_tile(try) && !ps_find_piece(minigame,try))
                     return false; // a move is valid, abort!
             }
             try = minigame_tile_buildname(letter, number - 1);
             if(ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter, number - 2);
                 if(ps_valid_tile(try) && !ps_find_piece(minigame,try))
                     return false; // a move is valid, abort!
             }
             try = minigame_tile_buildname(letter, number + 1);
             if(ps_find_piece(minigame,try))
             {
                 try = minigame_tile_buildname(letter, number + 2);
                 if(ps_valid_tile(try) && !ps_find_piece(minigame,try))
                     return false; // a move is valid, abort!
             }
         }
     return true;
 }
REGISTER_MINIGAME (ps , _("Peg Solitaire"))
Variable Documentation
const int PS_LET_CNT = 7
Definition at line 9 of file ps.qc.
Referenced by ps_setup_pieces(), and ps_valid_tile().
const int PS_NUM_CNT = 7
Definition at line 10 of file ps.qc.
Referenced by ps_setup_pieces().
const int PS_TILE_SIZE = 8
Definition at line 12 of file ps.qc.
const float PS_TURN_DRAW = 0x0400
Definition at line 6 of file ps.qc.
Referenced by ps_move().
const float PS_TURN_MOVE = 0x0100
Definition at line 4 of file ps.qc.
Referenced by ps_move().
const float PS_TURN_TYPE = 0x0f00
Definition at line 7 of file ps.qc.
const float PS_TURN_WIN = 0x0200
Definition at line 5 of file ps.qc.
Referenced by ps_move().