Xonotic: common/mapobjects/defs.qh File Reference
defs.qh File Reference
Variables
const int ALL_ENTITIES = BIT(1)
const int CRUSH = BIT(2)
const int INVERT_TEAMS = BIT(2)
const int NOSPLASH = BIT(8)
const int ON_MAPLOAD = BIT(1)
const int ONLY_PLAYERS = BIT(14)
const int SF_TRIGGER_INIT = BIT(0)
const int SF_TRIGGER_RESET = BIT(2)
const int SF_TRIGGER_UPDATE = BIT(1)
const int SPAWNFLAG_NOMESSAGE = BIT(0)
const int SPAWNFLAG_NOTOUCH = BIT(0)
const int START_DISABLED = BIT(0)
const int START_ENABLED = BIT(0)
Variable Documentation
const int ALL_ENTITIES = BIT(1)
Definition at line 8 of file defs.qh.
const int CRUSH = BIT(2)
Definition at line 11 of file defs.qh.
Referenced by plat_crush().
const int INVERT_TEAMS = BIT(2)
Definition at line 10 of file defs.qh.
Referenced by Teleport_Active(), and trigger_push_touch().
const int NOSPLASH = BIT(8)
Definition at line 12 of file defs.qh.
Referenced by door_damage().
const int ON_MAPLOAD = BIT(1)
Definition at line 9 of file defs.qh.
const int ONLY_PLAYERS = BIT(14)
Definition at line 13 of file defs.qh.
const int SF_TRIGGER_INIT = BIT(0)
Definition at line 22 of file defs.qh.
Referenced by conveyor_think(), door_reset(), LinkDoors(), train_next(), and trigger_push_findtarget().
const int SF_TRIGGER_RESET = BIT(2)
Definition at line 24 of file defs.qh.
Referenced by door_reset(), LinkDoors(), plat_reset(), and train_next().
const int SF_TRIGGER_UPDATE = BIT(1)
Definition at line 23 of file defs.qh.
Referenced by conveyor_think(), DelayThink(), door_init_startopen(), door_reset(), and LinkDoors().
const int SPAWNFLAG_NOMESSAGE = BIT(0)
Definition at line 16 of file defs.qh.
const int SPAWNFLAG_NOTOUCH = BIT(0)
Definition at line 17 of file defs.qh.
const int START_DISABLED = BIT(0)
Definition at line 7 of file defs.qh.
const int START_ENABLED = BIT(0)
Definition at line 6 of file defs.qh.
Referenced by DelayThink().