Xonotic: lib/map.qh File Reference
map.qh File Reference
#include "int.qh"
Macros
#define db_remove(db, key) db_put(db, key, "")
#define HM_DELETE(this) db_close(this)
#define HM_gets(this, k) db_get(this, k)
#define HM_NEW(this) (this = db_create())
#define HM_sets(this, key, val) db_put(this, key, val)
Typedefs
using HashMap = int
Functions
void db_close (int db)
int db_create ()
void db_dump (int db, string filename)
string db_get (int db, string key)
int db_load (string filename)
void db_put (int db, string key, string value)
void db_save (int db, string filename)
void db_test ()
Variables
const int DB_BUCKETS = 8192
Macro Definition Documentation
#define db_remove (db, key) db_put(db, key, "")
Definition at line 91 of file map.qh.
Referenced by race_deleteTime(), and uid2name().
#define HM_DELETE (this) db_close(this)
Definition at line 82 of file map.qh.
Referenced by SHUTDOWN().
#define HM_gets (this, k) db_get(this, k)
Definition at line 89 of file map.qh.
Referenced by CTX().
#define HM_NEW (this) (this = db_create())
Definition at line 27 of file map.qh.
Referenced by STATIC_INIT().
#define HM_sets (this, key, val) db_put(this, key, val)
Definition at line 98 of file map.qh.
Referenced by CTX().
Typedef Documentation
using HashMap = int
Definition at line 21 of file map.qh.
Function Documentation
void db_close (int db)
Definition at line 78 of file map.qh.
Referenced by CSQC_UpdateView(), db_test(), GameCommand_database(), GameCommand_effectindexdump(), GenericCommand_rpn(), MapInfo_Cache_Destroy(), and Shutdown().
 {
     buf_del(db);
 }
int db_create ()
Definition at line 23 of file map.qh.
References buf_create.
Referenced by CSQC_Init(), CSQC_UpdateView(), GameCommand_effectindexdump(), GenericCommand_rpn(), MapInfo_Cache_Create(), and spawnfunc().
 {
     return buf_create();
 }
void db_dump (int db, string filename)
Definition at line 64 of file map.qh.
References argv(), fclose(), FILE_WRITE, fopen(), fputs(), LOG_FATALF, strcat(), and tokenizebyseparator.
Referenced by GameCommand_database(), and Shutdown().
 {
     int fh = fopen(filename, FILE_WRITE);
     if (fh < 0) LOG_FATALF("Can't dump DB to %s");
     fputs(fh, "0\n");
     for (int i = 0, n = buf_getsize(db); i < n; ++i)
     {
         int m = tokenizebyseparator(bufstr_get(db, i), "\\");
         for (int j = 2; j < m; j += 2)
             fputs(fh, strcat("\\", argv(j - 1), "\\", argv(j), "\n"));
     }
     fclose(fh);
 }
string db_get (int db, string key)
Definition at line 84 of file map.qh.
References DB_BUCKETS.
Referenced by _getcommandkey(), ctf_CaptureRecord(), ctf_Initialize(), GameCommand_effectindexdump(), GenericCommand_rpn(), getladder(), HUD_Mod_Race(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MUTATOR_HOOKFUNCTION(), race_readName(), race_readTime(), race_readUID(), uid2name(), and XonoticStatsList_getStats().
 {
     int h = crc16(false, key) % DB_BUCKETS;
     return uri_unescape(infoget(bufstr_get(db, h), key));
 }
int db_load (string filename)
Definition at line 31 of file map.qh.
References argv(), buf_create, DB_BUCKETS, db_put(), fclose(), fgets(), FILE_READ, fopen(), stoi, and tokenizebyseparator.
Referenced by CSQC_Init(), db_test(), GameCommand_database(), GenericCommand_rpn(), RestoreGame(), and spawnfunc().
 {
     int db = buf_create();
     if (db < 0) return -1;
     int fh = fopen(filename, FILE_READ);
     if (fh < 0) return db;
     string l = fgets(fh);
     if (stoi(l) == DB_BUCKETS)
     {
         for (int i = 0; (l = fgets(fh)); ++i)
         {
             if (l != "") bufstr_set(db, i, l);
         }
     }
     else
     {
         // different count of buckets, or a dump?
         // need to reorganize the database then (SLOW)
         //
         // note: we also parse the first line (l) in case the DB file is
         // missing the bucket count
         do
         {
             int n = tokenizebyseparator(l, "\\");
             for (int j = 2; j < n; j += 2)
                 db_put(db, argv(j - 1), uri_unescape(argv(j)));
         }
         while ((l = fgets(fh)));
     }
     fclose(fh);
     return db;
 }
void db_put (int db, string key, string value)
Definition at line 93 of file map.qh.
References DB_BUCKETS.
Referenced by _getcommandkey(), ctf_CaptureRecord(), db_load(), db_test(), GameCommand_effectindexdump(), GenericCommand_rpn(), getladder(), HUD_Mod_Race(), MapInfo_Cache_Store(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_writeTime(), and uid2name().
 {
     int h = crc16(false, key) % DB_BUCKETS;
     bufstr_set(db, h, infoadd(bufstr_get(db, h), key, uri_escape(value)));
 }
void db_save (int db, string filename)
Definition at line 7 of file map.qh.
References DB_BUCKETS, fclose(), FILE_WRITE, fopen(), fputs(), ftos(), LOG_WARNF, and strcat().
Referenced by db_test(), GameCommand_database(), GenericCommand_rpn(), and Shutdown().
 {
     int fh = fopen(filename, FILE_WRITE);
     if (fh < 0)
     {
         LOG_WARNF("^1Can't write DB to %s", filename);
         return;
     }
     fputs(fh, strcat(ftos(DB_BUCKETS), "\n"));
     for (int i = 0, n = buf_getsize(db); i < n; ++i)
         fputs(fh, strcat(bufstr_get(db, i), "\n"));
     fclose(fh);
 }
void db_test ()
Definition at line 100 of file map.qh.
References DB_BUCKETS, db_close(), db_load(), db_put(), db_save(), ftos(), LOG_INFO, and random().
 {
     LOG_INFO("LOAD...\n");
     int db = db_load("foo.db");
     LOG_INFO("LOADED. FILL...\n");
     for (int i = 0; i < DB_BUCKETS; ++i)
         db_put(db, ftos(random()), "X");
     LOG_INFO("FILLED. SAVE...\n");
     db_save(db, "foo.db");
     LOG_INFO("SAVED. CLOSE...\n");
     db_close(db);
     LOG_INFO("CLOSED.\n");
 }
Variable Documentation
const int DB_BUCKETS = 8192
Definition at line 6 of file map.qh.
Referenced by db_get(), db_load(), db_put(), db_save(), and db_test().