Xonotic: lib/promise.qh File Reference
promise.qh File Reference
Macros
#define Promise_catch(this, handler, userdata) Promise_catch_(this, Promise_new(), handler, userdata)
#define Promise_new() Promise_new_(new_pure(Promise))
#define Promise_then(this, handler, userdata) Promise_then_(this, Promise_new(), handler, userdata)
Functions
entityclass (Promise)
Promise Promise_catch_ (Promise this, Promise ret, Promise(Promise ret, entity err, entity userdata) handler, entity userdata)
Promise Promise_new_ (Promise this)
void Promise_reject (Promise this)
notify all Promise_catch subscribers that this promise has rejected
void Promise_resolve (Promise this)
notify all Promise_then subscribers that this promise has resolved
Promise Promise_sleep (float n)
Promise Promise_then_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) handler, entity userdata)
Macro Definition Documentation
#define Promise_catch (this, handler, userdata) Promise_catch_(this, Promise_new(), handler, userdata)
Definition at line 21 of file promise.qh.
#define Promise_new () Promise_new_(new_pure(Promise))
Definition at line 5 of file promise.qh.
Referenced by Promise_sleep().
#define Promise_then (this, handler, userdata) Promise_then_(this, Promise_new(), handler, userdata)
Definition at line 13 of file promise.qh.
Function Documentation
entityclass (Promise)
Promise Promise_catch_ (Promise this, Promise ret, Promise(Promise ret, entity err, entity userdata) handler, entity userdata)
Promise Promise_new_ (Promise this)
Definition at line 51 of file promise.qc.
References _Promise_finalize(), _Promise_handle(), and ref_init().
 {
     ref_init(this, 2, _Promise_finalize);
     this._promise_result = this; // promises default to being their own result to save on entities
     return this;
 }
void Promise_reject (Promise this)
notify all Promise_catch subscribers that this promise has rejected
Definition at line 79 of file promise.qc.
References _Promise_handle(), _Promise_then(), entity(), IL_DELETE, IL_EACH, LOG_SEVERE, LOG_SEVEREF, PROMISE_PENDING, PROMISE_REJECTED, and unref().
Referenced by _Promise_onReject_default().
 {
     if (!this) {
         LOG_SEVERE("Attempted to reject a null promise");
         return;
     }
     if (this._promise_state != PROMISE_PENDING) {
         LOG_SEVEREF("Rejected non-pending promise %i", this);
         return;
     }
     this._promise_state = PROMISE_REJECTED;
     if (this._promise_handlers) {
         IL_EACH(this._promise_handlers, true, _Promise_handle(this, it));
         IL_DELETE(this._promise_handlers);
     }
     unref(this);
     return;
 }
void Promise_resolve (Promise this)
notify all Promise_then subscribers that this promise has resolved
Definition at line 60 of file promise.qc.
References _Promise_handle(), IL_DELETE, IL_EACH, LOG_SEVERE, LOG_SEVEREF, PROMISE_PENDING, PROMISE_RESOLVED, and unref().
Referenced by _Promise_onResolve_default(), and Promise_sleep().
 {
     if (!this) {
         LOG_SEVERE("Attempted to resolve a null promise");
         return;
     }
     if (this._promise_state != PROMISE_PENDING) {
         LOG_SEVEREF("Resolved non-pending promise %i", this);
         return;
     }
     this._promise_state = PROMISE_RESOLVED;
     if (this._promise_handlers) {
         IL_EACH(this._promise_handlers, true, _Promise_handle(this, it));
         IL_DELETE(this._promise_handlers);
     }
     unref(this);
     return;
 }
Promise Promise_sleep (float n)
Definition at line 206 of file promise.qc.
References Promise_new, Promise_resolve(), setthink, time, and unref().
 {
     Promise p = unref(Promise_new());
     setthink(p, Promise_resolve);
     p.nextthink = time + n;
     return p;
 }
Promise Promise_then_ (Promise this, Promise ret, Promise(Promise ret, entity result, entity userdata) handler, entity userdata)
Definition at line 180 of file promise.qc.
References _Promise_then(), func_null(), and unref().
 {
     unref(ret); // ret is a temporary
     return _Promise_then(this, ret, onResolve, func_null, userdata);
 }