Xonotic: lib/warpzone/anglestransform.qc File Reference
anglestransform.qc File Reference
#include "anglestransform.qh"
Functions
vector AnglesTransform_Apply (vector transform, vector v)
vector AnglesTransform_ApplyToAngles (vector transform, vector v)
vector AnglesTransform_ApplyToVAngles (vector transform, vector v)
vector AnglesTransform_CancelRoll (vector t)
vector AnglesTransform_FromAngles (vector v)
vector AnglesTransform_FromVAngles (vector v)
vector AnglesTransform_Invert (vector transform)
vector AnglesTransform_LeftDivide (vector from_transform, vector to_transform)
vector AnglesTransform_Multiply (vector t1, vector t2)
vector AnglesTransform_Multiply_GetPostShift (vector t0, vector st0, vector t1, vector st1)
vector AnglesTransform_Normalize (vector t, float minimize_roll)
vector AnglesTransform_PrePostShift_GetPostShift (vector sf, vector t, vector st)
vector AnglesTransform_RightDivide (vector to_transform, vector from_transform)
vector AnglesTransform_ToAngles (vector v)
vector AnglesTransform_ToVAngles (vector v)
vector AnglesTransform_TurnDirectionFR (vector transform)
vector AnglesTransform_TurnDirectionFU (vector transform)
Function Documentation
vector AnglesTransform_Apply (vector transform, vector v)
Definition at line 5 of file anglestransform.qc.
References FIXED_MAKE_VECTORS, and vector().
Referenced by AnglesTransform_Multiply(), AnglesTransform_Multiply_GetPostShift(), AnglesTransform_PrePostShift_GetPostShift(), Portal_ApplyTransformToPlayerAngle(), Portal_TeleportPlayer(), skel_set_boneabs(), WarpZone_TransformOrigin(), WarpZone_TransformVelocity(), WarpZone_UnTransformOrigin(), and WarpZone_UnTransformVelocity().
 {
     vector forward, right, up;
     FIXED_MAKE_VECTORS(transform, forward, right, up);
     return forward * v.x + right * (-v.y) + up * v.z;
 }
vector AnglesTransform_ApplyToAngles (vector transform, vector v)
Definition at line 129 of file anglestransform.qc.
References AnglesTransform_Multiply(), and v.
Referenced by AnglesTransform_ToVAngles(), CheatCommand(), Portal_TeleportPlayer(), WarpZone_TransformAngles(), and WarpZone_UnTransformAngles().
 {
     v.x = -v.x;
     v = AnglesTransform_Multiply(transform, v);
     v.x = -v.x;
     return v;
 }
vector AnglesTransform_ApplyToVAngles (vector transform, vector v)
Definition at line 136 of file anglestransform.qc.
References AnglesTransform_Multiply(), and v.
Referenced by AnglesTransform_ToVAngles(), WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
 {
     v = AnglesTransform_Multiply(transform, v);
     return v;
 }
vector AnglesTransform_CancelRoll (vector t)
Definition at line 96 of file anglestransform.qc.
References fabs().
Referenced by WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
 {
     const float epsilon = 30;
     float f;
     // constraints:
     // forward vector (NOT SO important)
     // right vector, up vector: screen rotation (MORE important)
     // choose best match among all pitch-yaw only rotations
     // FIXME find a better method
     f = fabs(t.x - (-90)) / epsilon;
     if(f < 1)
     {
         //t_x = -90;
         t.y += t.z;
         t.z = 0;
     }
     else
     {
         f = fabs(t.x - 90) / epsilon;
         if(f < 1)
         {
             //t_x = 90;
             t.y -= t.z;
             t.z = 0;
         }
     }
     return t;
 }
vector AnglesTransform_FromAngles (vector v)
Definition at line 141 of file anglestransform.qc.
References v.
Referenced by AnglesTransform_ToVAngles(), attach_sameorigin(), Projectile_Draw(), and vehicle_aimturret().
 {
     v.x = -v.x;
     return v;
 }
vector AnglesTransform_FromVAngles (vector v)
Definition at line 151 of file anglestransform.qc.
References v.
Referenced by AnglesTransform_ToVAngles(), and attach_sameorigin().
 {
     return v;
 }
vector AnglesTransform_Invert (vector transform)
Definition at line 21 of file anglestransform.qc.
References FIXED_MAKE_VECTORS, fixedvectoangles2, and vector().
Referenced by AnglesTransform_LeftDivide(), AnglesTransform_RightDivide(), skel_set_boneabs(), WarpZone_Accumulator_AddInverseTransform(), WarpZone_UnTransformAngles(), WarpZone_UnTransformOrigin(), WarpZone_UnTransformVAngles(), and WarpZone_UnTransformVelocity().
 {
     vector i_forward, i_up;
     vector forward, right, up;
     FIXED_MAKE_VECTORS(transform, forward, right, up);
     // we want angles that turn forward into '1 0 0', right into '0 1 0' and up into '0 0 1'
     // but these are orthogonal unit vectors!
     // so to invert, we can simply fixedvectoangles the TRANSPOSED matrix
     // TODO is this always -transform?
     i_forward.x = forward.x;
     i_forward.y = -right.x;
     i_forward.z = up.x;
     i_up.x = forward.z;
     i_up.y = -right.z;
     i_up.z = up.z;
     return fixedvectoangles2(i_forward, i_up);
 }
vector AnglesTransform_LeftDivide (vector from_transform, vector to_transform)
Definition at line 71 of file anglestransform.qc.
References AnglesTransform_Invert(), and AnglesTransform_Multiply().
Referenced by skel_set_boneabs(), and vehicle_aimturret().
 {
     return AnglesTransform_Multiply(AnglesTransform_Invert(from_transform), to_transform);
 }
vector AnglesTransform_Multiply (vector t1, vector t2)
Definition at line 12 of file anglestransform.qc.
References AnglesTransform_Apply(), FIXED_MAKE_VECTORS, fixedvectoangles2, and vector().
Referenced by AnglesTransform_ApplyToAngles(), AnglesTransform_ApplyToVAngles(), AnglesTransform_LeftDivide(), AnglesTransform_RightDivide(), AnglesTransform_ToVAngles(), Projectile_Draw(), skeleton_from_frames(), WarpZone_Accumulator_AddTransform(), and WarpZone_FindRadius_Recurse().
 {
     vector forward, right, up;
     FIXED_MAKE_VECTORS(t2, forward, right, up);
     forward = AnglesTransform_Apply(t1, forward);
     up = AnglesTransform_Apply(t1, up);
     return fixedvectoangles2(forward, up);
 }
vector AnglesTransform_Multiply_GetPostShift (vector t0, vector st0, vector t1, vector st1)
Definition at line 192 of file anglestransform.qc.
References AnglesTransform_Apply().
Referenced by WarpZone_Accumulator_AddTransform(), and WarpZone_FindRadius_Recurse().
 {
     // we want the result of:
     //   t0 * (t1 * p + st1) + st0
     //   t0 * t1 * p + t0 * st1 + st0
     return st0 + AnglesTransform_Apply(t0, st1);
 }
vector AnglesTransform_Normalize (vector t, float minimize_roll)
Definition at line 76 of file anglestransform.qc.
References rint().
Referenced by vehicle_aimturret(), WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
 {
     float need_flip;
     // first, bring all angles in their range...
     t.x = t.x - 360 * rint(t.x / 360);
     t.y = t.y - 360 * rint(t.y / 360);
     t.z = t.z - 360 * rint(t.z / 360);
     if(minimize_roll)
         need_flip = (t.z > 90 || t.z <= -90);
     else
         need_flip = (t.x > 90 || t.x < -90); // for pitch we prefer to allow exactly -90 degrees for looking straight down
     if(need_flip)
     {
         if(t.x >= 0) t.x = 180 - t.x; else t.x = -180 - t.x;
         if(t.y > 0) t.y -= 180; else t.y += 180;
         if(t.z > 0) t.z -= 180; else t.z += 180;
     }
     return t;
 }
vector AnglesTransform_PrePostShift_GetPostShift (vector sf, vector t, vector st)
Definition at line 199 of file anglestransform.qc.
References AnglesTransform_Apply().
Referenced by WarpZone_Accumulator_AddInverseTransform(), and WarpZone_SetUp().
 {
     return st - AnglesTransform_Apply(t, sf);
 }
vector AnglesTransform_RightDivide (vector to_transform, vector from_transform)
Definition at line 66 of file anglestransform.qc.
References AnglesTransform_Invert(), and AnglesTransform_Multiply().
Referenced by Portal_Connect(), and WarpZone_SetUp().
 {
     return AnglesTransform_Multiply(to_transform, AnglesTransform_Invert(from_transform));
 }
vector AnglesTransform_ToAngles (vector v)
Definition at line 146 of file anglestransform.qc.
References v.
Referenced by AnglesTransform_ToVAngles(), attach_sameorigin(), detach_sameorigin(), Projectile_Draw(), and vehicle_aimturret().
 {
     v.x = -v.x;
     return v;
 }
vector AnglesTransform_ToVAngles (vector v)
Definition at line 155 of file anglestransform.qc.
References AnglesTransform_ApplyToAngles(), AnglesTransform_ApplyToVAngles(), AnglesTransform_FromAngles(), AnglesTransform_FromVAngles(), AnglesTransform_Multiply(), AnglesTransform_ToAngles(), AnglesTransform_ToVAngles(), v, and vector().
Referenced by AnglesTransform_ToVAngles(), attach_sameorigin(), and detach_sameorigin().
 {
     return v;
 }
vector AnglesTransform_TurnDirectionFR (vector transform)
Definition at line 39 of file anglestransform.qc.
Referenced by Portal_Connect(), and WarpZone_SetUp().
 {
     // turn 180 degrees around v_up
     // changes in-direction to out-direction
     //fixedmakevectors(transform);
     //return fixedvectoangles2(-1 * v_forward, 1 * v_up);
     transform.x = -transform.x;
     transform.y = 180 + transform.y;
     transform.z = -transform.z;
     // pitch: -s +c
     // yaw:   -s -c
     // roll:  -s +c
     return transform;
 }
vector AnglesTransform_TurnDirectionFU (vector transform)
Definition at line 54 of file anglestransform.qc.
 {
     // turn 180 degrees around v_up
     // changes in-direction to out-direction
     //fixedmakevectors(transform);
     //return fixedvectoangles2(-1 * v_forward, 1 * v_up);
     transform.x = -transform.x;
     transform.y = 180 + transform.y;
     transform.z = 180 - transform.z;
     return transform;
 }