Xonotic: client/weapons/projectile.qh File Reference
projectile.qh File Reference
#include <common/sounds/sound.qh>
Functions
classfield (Projectile).int traileffect
void Ent_RemoveProjectile (entity this)
entityclass (Projectile)
void loopsound (entity e, int ch, Sound samp, float vol, float attn)
void Projectile_Draw (entity this)
void Projectile_DrawTrail (entity this, vector to)
void Projectile_ResetTrail (entity this, vector to)
void SUB_Stop (entity this, entity toucher)
Variables
fade_rate
const int FL_PROJECTILE = BIT(15)
iorigin2
Function Documentation
classfield (Projectile)
void Ent_RemoveProjectile (entity this)
Definition at line 182 of file projectile.qc.
References count, maxs, mins, MOVE_NORMAL, origin, Projectile_DrawTrail(), trace_endpos, and velocity.
Referenced by NET_HANDLE().
 {
     if (this.count & 0x80)
     {
         tracebox(this.origin, this.mins, this.maxs, this.origin + this.velocity * 0.05, MOVE_NORMAL, this);
         Projectile_DrawTrail(this, trace_endpos);
     }
 }
entityclass (Projectile)
void loopsound (entity e, int ch, Sound samp, float vol, float attn)
Definition at line 172 of file projectile.qc.
References sound, and TC.
Referenced by NET_HANDLE().
 {
     TC(int, ch);
     if (e.silent)
         return;
     sound(e, ch, samp, vol, attn);
     e.snd_looping = ch;
 }
void Projectile_Draw (entity this)
Definition at line 55 of file projectile.qc.
References alpha, angles, AnglesTransform_FromAngles(), AnglesTransform_Multiply(), AnglesTransform_ToAngles(), autocvar_cl_projectiles_sloppy, avelocity, bound(), cnt, count, drawmask, fade_rate, fade_time, FL_ONGROUND, flags, IFLAG_VALID, iflags, InterpolateOrigin_Do(), IS_ONGROUND, MASK_NORMAL, max(), move_movetype, MOVETYPE_FLY, MOVETYPE_NONE, Movetype_Physics_MatchServer(), Movetype_Physics_NoMatchServer(), origin, Projectile_DrawTrail(), PROJECTILE_GRENADE, PROJECTILE_GRENADE_BOUNCING, PROJECTILE_HOOKBOMB, Projectile_ResetTrail(), PROJECTILE_ROCKET, renderflags, time, v_forward, v_right, v_up, vectoangles(), vector(), and velocity.
Referenced by NET_HANDLE().
 {
     vector rot;
     vector trailorigin;
     int f;
     bool drawn;
     float t;
     float a;
     f = this.flags;
     if (this.count & 0x80)
     {
         // UNSET_ONGROUND(this);
         if (this.move_movetype == MOVETYPE_NONE || this.move_movetype == MOVETYPE_FLY)
             Movetype_Physics_NoMatchServer(this);
         // the trivial movetypes do not have to match the
         // server's ticrate as they are ticrate independent
         // NOTE: this assumption is only true if MOVETYPE_FLY
         // projectiles detonate on impact. If they continue
         // moving, we might still be ticrate dependent.
         else
             Movetype_Physics_MatchServer(this, autocvar_cl_projectiles_sloppy);
         if (!IS_ONGROUND(this))
             if (this.velocity != '0 0 0')
                 this.angles = vectoangles(this.velocity);
     }
     else
     {
         InterpolateOrigin_Do(this);
     }
     if (this.count & 0x80)
     {
         drawn = (time >= this.spawntime - 0.02);
         t = max(time, this.spawntime);
     }
     else
     {
         drawn = (this.iflags & IFLAG_VALID);
         t = time;
     }
     if (!(f & FL_ONGROUND))
     {
         rot = '0 0 0';
         switch (this.cnt)
         {
             /*
             case PROJECTILE_GRENADE:
                 rot = '-2000 0 0'; // forward
                 break;
             */
             case PROJECTILE_GRENADE_BOUNCING:
                 rot = '0 -1000 0'; // sideways
                 break;
             case PROJECTILE_HOOKBOMB:
                 rot = '1000 0 0';  // forward
                 break;
             case PROJECTILE_ROCKET:
                 rot = '0 0 720'; // spinning
                 break;
             default:
                 break;
         }
         if (Projectile_isnade(this.cnt))
             rot = this.avelocity;
         this.angles = AnglesTransform_ToAngles(AnglesTransform_Multiply(AnglesTransform_FromAngles(this.angles), rot * (t - this.spawntime)));
     }
     vector ang;
     ang = this.angles;
     ang.x = -ang.x;
     makevectors(ang);
     a = 1 - (time - this.fade_time) * this.fade_rate;
     this.alpha = bound(0, this.alphamod * a, 1);
     if (this.alpha <= 0)
         drawn = 0;
     this.renderflags = 0;
     trailorigin = this.origin;
     switch (this.cnt)
     {
         case PROJECTILE_GRENADE:
         case PROJECTILE_GRENADE_BOUNCING:
             trailorigin += v_right * 1 + v_forward * -10;
             break;
         default:
             break;
     }
     if (Projectile_isnade(this.cnt))
         trailorigin += v_up * 4;
     if (drawn)
         Projectile_DrawTrail(this, trailorigin);
     else
         Projectile_ResetTrail(this, trailorigin);
     this.drawmask = 0;
     if (!drawn)
         return;
     switch (this.cnt)
     {
         // Possibly add dlights here.
         default:
             break;
     }
     this.drawmask = MASK_NORMAL;
 }
void Projectile_DrawTrail (entity this, vector to)
Definition at line 36 of file projectile.qc.
References alpha, cnt, Effects_from, particleeffectnum, particles_alphamax, particles_alphamin, PARTICLES_DRAWASTRAIL, particles_fade, PARTICLES_USEALPHA, PARTICLES_USEFADE, PROJECTILE_FIREMINE, sqrt(), time, to, vector(), and velocity.
Referenced by CSQCModel_Effects_Apply(), Ent_RemoveProjectile(), and Projectile_Draw().
 {
     vector from = this.trail_oldorigin;
     // float t0 = this.trail_oldtime;
     this.trail_oldorigin = to;
     this.trail_oldtime = time;
     // force the effect even for stationary firemine
     if (this.cnt == PROJECTILE_FIREMINE)
         if (from == to)
             from.z += 1;
     if (this.traileffect)
     {
         particles_alphamin = particles_alphamax = particles_fade = sqrt(this.alpha);
         boxparticles(particleeffectnum(Effects_from(this.traileffect)), this, from, to, this.velocity, this.velocity, 1, PARTICLES_USEALPHA | PARTICLES_USEFADE | PARTICLES_DRAWASTRAIL);
     }
 }
void Projectile_ResetTrail (entity this, vector to)
Definition at line 30 of file projectile.qc.
References time, and to.
Referenced by CSQCModel_Effects_Apply(), CSQCModel_Effects_PostUpdate(), and Projectile_Draw().
 {
     this.trail_oldorigin = to;
     this.trail_oldtime = time;
 }
void SUB_Stop (entity this, entity toucher)
Definition at line 24 of file projectile.qc.
References avelocity, MOVETYPE_NONE, set_movetype(), and velocity.
Referenced by NET_HANDLE().
 {
     this.velocity = this.avelocity = '0 0 0';
     set_movetype(this, MOVETYPE_NONE);
 }
Variable Documentation
fade_rate
Definition at line 12 of file projectile.qh.
Referenced by CopyBody(), CSQCProjectile_SendEntity(), DamageText::DamageText(), DamageText::DamageText_draw2d(), NET_HANDLE(), Projectile_Draw(), and SUB_SetFade_Think().
const int FL_PROJECTILE = BIT(15)
Definition at line 33 of file projectile.qh.
Referenced by CreatureFrame_FallDamage(), CreatureFrame_hotliquids(), door_trigger_touch(), FireGrapplingHook(), GrapplingHookThink(), jumppad_push(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), reset_map(), vehicles_projectile(), W_Nexball_Attack2(), and WarpZone_PostTeleportPlayer_Callback().
iorigin2
Definition at line 8 of file projectile.qh.