Xonotic: PlayerState Class Reference
PlayerState Class Reference
Purpose: common player state, usable on client and server Client: singleton representing the viewed player Server: instance per client, clients decoupled from players.
Public Member Functions
PlayerState (entity client)
virtual void describe ()
virtual void display ()
virtual void ps_push ()
Public Attributes
entity m_client = NULL
Weapon m_switchingweapon = Weapons_from(-1)
Weapon m_switchweapon = Weapons_from(-1)
Weapon m_weapon = Weapons_from(-1)
Detailed Description
Purpose: common player state, usable on client and server Client: singleton representing the viewed player Server: instance per client, clients decoupled from players.
Definition at line 8 of file state.qh.
Constructor & Destructor Documentation
PlayerState::PlayerState (entity client) inline
Definition at line 10 of file state.qh.
References CONSTRUCT.
     {
         CONSTRUCT(PlayerState);
         this.m_client = client;
     }
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void PlayerState::ps_push () inline virtual
Definition at line 18 of file state.qh.
References TC.
Referenced by EndFrame(), and PlayerState_detach().
     {
         TC(PlayerState, this);
         STAT(ACTIVEWEAPON, cl) = this.m_weapon.m_id;
         STAT(SWITCHINGWEAPON, cl) = this.m_switchingweapon.m_id;
         STAT(SWITCHWEAPON, cl) = this.m_switchweapon.m_id;
     }
Member Data Documentation
entity PlayerState::m_client = NULL
Definition at line 9 of file state.qh.
Referenced by PlayerState_detach().
Weapon PlayerState::m_switchingweapon = Weapons_from(-1)
Definition at line 15 of file state.qh.
Referenced by PlayerState_detach().
Weapon PlayerState::m_switchweapon = Weapons_from(-1)
Definition at line 16 of file state.qh.
Referenced by PlayerState_detach().
Weapon PlayerState::m_weapon = Weapons_from(-1)
Definition at line 17 of file state.qh.
Referenced by PlayerState_detach().
The documentation for this class was generated from the following file:
common/state.qh