Xonotic: menu/xonotic/tabcontroller.qc File Reference
tabcontroller.qc File Reference
#include "tabcontroller.qh"
#include "button.qh"
Functions
entity makeXonoticTabController (float theRows)
void XonoticTabController_configureXonoticTabController (entity me, float theRows)
entity XonoticTabController_makeTabButton (entity me, string theTitle, entity tab)
entity XonoticTabController_makeTabButton_T (entity me, string theTitle, entity tab, string theTooltip)
Function Documentation
entity makeXonoticTabController (float theRows)
Definition at line 5 of file tabcontroller.qc.
References entity(), and NEW.
Referenced by XonoticMediaTab_fill(), XonoticMultiplayerDialog_fill(), and XonoticSettingsDialog_fill().
 {
     entity me;
     me = NEW(XonoticTabController);
     me.configureXonoticTabController(me, theRows);
     return me;
 }
void XonoticTabController_configureXonoticTabController (entity me, float theRows)
Definition at line 12 of file tabcontroller.qc.
 {
     me.rows = theRows;
 }
entity XonoticTabController_makeTabButton (entity me, string theTitle, entity tab)
Definition at line 26 of file tabcontroller.qc.
References string_null, and XonoticTabController_makeTabButton_T().
 {
     return XonoticTabController_makeTabButton_T(me, theTitle, tab, string_null);
 }
entity XonoticTabController_makeTabButton_T (entity me, string theTitle, entity tab, string theTooltip)
Definition at line 16 of file tabcontroller.qc.
References entity(), error, and makeXonoticButton_T().
Referenced by XonoticTabController_makeTabButton().
 {
     entity b;
     if(me.rows != tab.rows)
         error("Tab dialog height mismatch!");
     b = makeXonoticButton_T(theTitle, '0 0 0', theTooltip);
         me.addTab(me, tab, b);
     // TODO make this real tab buttons (with color parameters, and different gfx)
     return b;
 }