Xonotic: server/elimination.qc File Reference
elimination.qc File Reference
#include "elimination.qh"
#include <common/net_linked.qh>
#include <server/utils.qh>
Functions
void EliminatedPlayers_Init (float(entity) isEliminated_func)
bool EliminatedPlayers_SendEntity (entity this, entity to, float sendflags)
float (entity) isEliminated
Function Documentation
EliminatedPlayers_Init()
void EliminatedPlayers_Init (float(entity) isEliminated_func)
Definition at line 27 of file elimination.qc.
References backtrace, eliminatedPlayers, EliminatedPlayers_SendEntity(), and new_pure.
Referenced by freezetag_Initialize(), and REGISTER_MUTATOR().
 {
     if(eliminatedPlayers)
     {
         backtrace("Can't spawn eliminatedPlayers again!");
         return;
     }
     Net_LinkEntity(eliminatedPlayers = new_pure(eliminatedPlayers), false, 0, EliminatedPlayers_SendEntity);
     eliminatedPlayers.isEliminated = isEliminated_func;
 }
EliminatedPlayers_SendEntity()
bool EliminatedPlayers_SendEntity (entity this, entity to, float sendflags)
Definition at line 7 of file elimination.qc.
References BIT, eliminatedPlayers, entity(), maxclients, nextent(), and serialize.
Referenced by EliminatedPlayers_Init().
 {
     Stream out = MSG_ENTITY;
     WriteHeader(out, ENT_CLIENT_ELIMINATEDPLAYERS);
     serialize(byte, out, sendflags);
     if (sendflags & 1) {
         for (int i = 1; i <= maxclients; i += 8) {
             int f = 0;
             entity e = edict_num(i);
             for (int b = 0; b < 8; ++b, e = nextent(e)) {
                 if (eliminatedPlayers.isEliminated(e)) {
                     f |= BIT(b);
                 }
             }
             serialize(byte, out, f);
         }
     }
     return true;
 }
float()
float (entity)