Xonotic: menu/xonotic/slider_sbfadetime.qc File Reference
slider_sbfadetime.qc File Reference
#include "slider_sbfadetime.qh"
Functions
entity makeXonoticScoreboardFadeTimeSlider ()
void XonoticScoreboardFadeTimeSlider_configureXonoticScoreboardFadeTimeSlider (entity me)
void XonoticScoreboardFadeTimeSlider_loadCvars (entity me)
void XonoticScoreboardFadeTimeSlider_saveCvars (entity me)
Function Documentation
entity makeXonoticScoreboardFadeTimeSlider ()
Definition at line 3 of file slider_sbfadetime.qc.
References entity(), and NEW.
Referenced by XonoticGameHUDSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticScoreboardFadeTimeSlider);
     me.configureXonoticScoreboardFadeTimeSlider(me);
     return me;
 }
void XonoticScoreboardFadeTimeSlider_configureXonoticScoreboardFadeTimeSlider (entity me)
Definition at line 10 of file slider_sbfadetime.qc.
References string_null, and ZCTX.
 {
     me.configureXonoticTextSlider(me, "hud_panel_scoreboard_fadeinspeed", string_null);
     me.addValue(me, ZCTX(_("PART^Slow")),     "5 2.5");
     me.addValue(me, ZCTX(_("PART^Normal")),   "10 5");
     me.addValue(me, ZCTX(_("PART^Fast")),     "15 7.5");
     me.addValue(me, ZCTX(_("PART^Instant")),  "0 0");
     me.configureXonoticTextSliderValues(me);
 }
void XonoticScoreboardFadeTimeSlider_loadCvars (entity me)
Definition at line 19 of file slider_sbfadetime.qc.
References cvar_string().
 {
     me.setValueFromIdentifier_noAnim(me, sprintf("%s %s",
         cvar_string("hud_panel_scoreboard_fadeinspeed"),
         cvar_string("hud_panel_scoreboard_fadeoutspeed")
     ));
 }
void XonoticScoreboardFadeTimeSlider_saveCvars (entity me)
Definition at line 26 of file slider_sbfadetime.qc.
References argv(), cvar_set(), and tokenize_console.
 {
     if(me.value >= 0 || me.value < me.nValues)
     {
         tokenize_console(me.getIdentifier(me));
         cvar_set("hud_panel_scoreboard_fadeinspeed", argv(0));
         cvar_set("hud_panel_scoreboard_fadeoutspeed", argv(1));
     }
 }