Xonotic: Gametype Class Reference
Gametype Class Reference
Public Member Functions
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_configuremenu ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isForcedSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
bool m_hidelimits = false
should this gametype display a score limit in the scoreboard?
int m_id = 0
string m_legacydefaults = ""
DO NOT USE, this is compatibility for legacy maps!
int m_priority = 0
game type priority in random selections
bool m_weaponarena = false
does this gametype enforce its own weapon arena?
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 29 of file mapinfo.qh.
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string)
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string)
game type short name
Gametype::ATTRIB (Gametype , message , string)
human readable name
Gametype::ATTRIB (Gametype , model2 , string)
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string)
game type description
Gametype::ATTRIB (Gametype , m_mutators , string)
virtual void Gametype::describe () inline virtual
Definition at line 89 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual
Definition at line 95 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual
Definition at line 101 of file mapinfo.qh.
References cons(), ENDCLASS, GAMETYPE_FLAG_HIDELIMITS, GAMETYPE_FLAG_PREFERRED, GAMETYPE_FLAG_PRIORITY, GAMETYPE_FLAG_TEAMPLAY, GAMETYPE_FLAG_USEPOINTS, GAMETYPE_FLAG_WEAPONARENA, m_flags, MAPINFO_TYPE_ALL, NULL, REGISTER_REGISTRY, REGISTRY, REGISTRY_CHECK(), REGISTRY_DEFINE_GET, and REGISTRY_SORT().
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = (gflags & GAMETYPE_FLAG_TEAMPLAY);
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = (gflags & GAMETYPE_FLAG_USEPOINTS);
         this.m_priority = ((gflags & GAMETYPE_FLAG_PREFERRED) ? 2 : ((gflags & GAMETYPE_FLAG_PRIORITY) ? 1 : 0));
         this.m_hidelimits = (gflags & GAMETYPE_FLAG_HIDELIMITS);
         this.m_weaponarena = (gflags & GAMETYPE_FLAG_WEAPONARENA);
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void Gametype::m_configuremenu () inline virtual
Reimplemented in TeamDeathmatch, FreezeTag, ClanArena, KeyHunt, Race, Domination, CaptureTheFlag, Invasion, RaceCTS, NexBall, Assault, Onslaught, and LastManStanding.
Definition at line 83 of file mapinfo.qh.
References string_null, and TC.
Referenced by GameType_ConfigureSliders_for_CurrentGametype().
     {
         TC(Gametype, this);
         returns(menu, _("Frag limit:"),      5,  100,  5, "fraglimit_override",        string_null,                    _("The amount of frags needed before the match will end"));
     }
virtual void Gametype::m_generate_mapinfo () inline virtual
Reimplemented in Domination, Race, Invasion, CaptureTheFlag, RaceCTS, NexBall, Assault, and Onslaught.
Definition at line 67 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
virtual void Gametype::m_isAlwaysSupported () inline virtual
Reimplemented in FreezeTag, ClanArena, KeyHunt, TeamDeathmatch, Keepaway, Duel, Deathmatch, and LastManStanding.
Definition at line 75 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_isForcedSupported () inline virtual
Reimplemented in TeamDeathmatch, and Duel.
Definition at line 79 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_isTwoBaseMode () inline virtual
Reimplemented in Race, CaptureTheFlag, NexBall, and Assault.
Definition at line 71 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_parse_mapinfo () inline virtual
Reimplemented in FreezeTag, ClanArena, Domination, KeyHunt, Race, TeamDeathmatch, and Invasion.
Definition at line 63 of file mapinfo.qh.
     {
         return false;
     }
Member Data Documentation
bool Gametype::frags = true
does this gametype use a point limit?
Definition at line 42 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
int Gametype::items = 0
game type ID
Definition at line 32 of file mapinfo.qh.
bool Gametype::m_hidelimits = false
should this gametype display a score limit in the scoreboard?
Definition at line 44 of file mapinfo.qh.
int Gametype::m_id = 0
Definition at line 30 of file mapinfo.qh.
string Gametype::m_legacydefaults = ""
DO NOT USE, this is compatibility for legacy maps!
Definition at line 60 of file mapinfo.qh.
Referenced by _MapInfo_GetDefault().
int Gametype::m_priority = 0
game type priority in random selections
Definition at line 52 of file mapinfo.qh.
bool Gametype::m_weaponarena = false
does this gametype enforce its own weapon arena?
Definition at line 46 of file mapinfo.qh.
bool Gametype::team = false
does this gametype support teamplay?
Definition at line 40 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/mapinfo.qh