Xonotic: common/physics/movetypes/movetypes.qc File Reference
movetypes.qc File Reference
#include "movetypes.qh"
Macros
#define X(v) if (_Movetype_TestEntityPosition(v))
#define X(i)
#define X(s)
Functions
void _Movetype_CheckVelocity (entity this)
bool _Movetype_CheckWater (entity this)
void _Movetype_CheckWaterTransition (entity ent)
vector _Movetype_ClipVelocity (vector vel, vector norm, float f)
int _Movetype_FlyMove (entity this, float dt, bool applygravity, vector stepnormal, float stepheight)
void _Movetype_Impact (entity this, entity oth)
void _Movetype_LinkEdict (entity this, bool touch_triggers)
void _Movetype_LinkEdict_TouchAreaGrid (entity this)
void _Movetype_Physics_ClientFrame (entity this, float movedt)
void _Movetype_Physics_Frame (entity this, float movedt)
float _Movetype_PushEntity (entity this, vector push, bool failonstartsolid)
void _Movetype_PushEntityTrace (entity this, vector push)
bool _Movetype_TestEntityPosition (vector ofs)
bool _Movetype_UnstickEntity (entity this)
void _Movetype_WallFriction (entity this, vector stepnormal)
void Movetype_Physics_MatchServer (entity this, bool sloppy)
void Movetype_Physics_MatchTicrate (entity this, float tr, bool sloppy)
void Movetype_Physics_NoMatchServer (entity this)
void Movetype_Physics_NoMatchTicrate (entity this, float movedt, bool isclient)
void () blocked
Variables
entity _Movetype_TestEntityPosition_ent
float ltime
vector planes [MAX_CLIP_PLANES]
vector tic_angles
vector tic_avelocity
int tic_flags
vector tic_origin
vector tic_saved_angles
vector tic_saved_avelocity
int tic_saved_flags
vector tic_saved_origin
vector tic_saved_velocity
vector tic_velocity
Macro Definition Documentation
#define X (v) if (_Movetype_TestEntityPosition(v))
Referenced by _Movetype_UnstickEntity(), and Movetype_Physics_MatchTicrate().
#define X (i)
Value:
if (_Movetype_TestEntityPosition('0 0 -1' * i)) \
            if (_Movetype_TestEntityPosition('0 0 1' * i))
#define X (s)
Value:
if(this.(s) != this.tic_saved_##s) \
        this.tic_##s = this.(s)
Function Documentation
void _Movetype_CheckVelocity (entity this)
Definition at line 247 of file movetypes.qc.
Referenced by _Movetype_Physics_Step(), _Movetype_Physics_Toss(), and _Movetype_Physics_Walk().
 {
     // if(vlen(this.velocity) < 0.0001)
     // this.velocity = '0 0 0';
 }
bool _Movetype_CheckWater (entity this)
Definition at line 253 of file movetypes.qc.
References CONTENT_EMPTY, DPCONTENTS_LIQUIDSMASK, maxs, mins, origin, vector(), view_ofs, waterlevel, WATERLEVEL_NONE, WATERLEVEL_SUBMERGED, WATERLEVEL_SWIMMING, WATERLEVEL_WETFEET, and watertype.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Walk(), and CSQCPlayer_Physics().
 {
     vector point = this.origin;
     point.z += this.mins.z + 1;
     int nativecontents = pointcontents(point);
     if(this.watertype && this.watertype != nativecontents)
     {
         // dprintf("_Movetype_CheckWater(): Original: '%d', New: '%d'\n", this.watertype, nativecontents);
         if(this.contentstransition)
             this.contentstransition(this.watertype, nativecontents);
     }
     this.waterlevel = WATERLEVEL_NONE;
     this.watertype = CONTENT_EMPTY;
     int supercontents = Mod_Q1BSP_SuperContentsFromNativeContents(nativecontents);
     if(supercontents & DPCONTENTS_LIQUIDSMASK)
     {
         this.watertype = nativecontents;
         this.waterlevel = WATERLEVEL_WETFEET;
         point.z = this.origin.z + (this.mins.z + this.maxs.z) * 0.5;
         if(Mod_Q1BSP_SuperContentsFromNativeContents(pointcontents(point)) & DPCONTENTS_LIQUIDSMASK)
         {
             this.waterlevel = WATERLEVEL_SWIMMING;
             point.z = this.origin.z + this.view_ofs.z;
             if(Mod_Q1BSP_SuperContentsFromNativeContents(pointcontents(point)) & DPCONTENTS_LIQUIDSMASK)
                 this.waterlevel = WATERLEVEL_SUBMERGED;
         }
     }
     return this.waterlevel > 1;
 }
void _Movetype_CheckWaterTransition (entity ent)
Definition at line 287 of file movetypes.qc.
References CONTENT_EMPTY, CONTENT_WATER, and GAMEPLAYFIX_WATERTRANSITION.
Referenced by _Movetype_Physics_Step(), and _Movetype_Physics_Toss().
 {
     int contents = pointcontents(ent.origin);
     if(!ent.watertype)
     {
         // just spawned here
         if(!GAMEPLAYFIX_WATERTRANSITION(ent))
         {
             ent.watertype = contents;
             ent.waterlevel = 1;
             return;
         }
     }
     else if(ent.watertype != contents)
     {
         // dprintf("_Movetype_CheckWaterTransition(): Origin: %s, Direct: '%d', Original: '%d', New: '%d'\n", vtos(ent.origin), pointcontents(ent.origin), ent.watertype, contents);
         if(ent.contentstransition)
             ent.contentstransition(ent.watertype, contents);
     }
     if(contents <= CONTENT_WATER)
     {
         ent.watertype = contents;
         ent.waterlevel = 1;
     }
     else
     {
         ent.watertype = CONTENT_EMPTY;
         ent.waterlevel = (GAMEPLAYFIX_WATERTRANSITION(ent) ? 0 : contents);
     }
 }
vector _Movetype_ClipVelocity (vector vel, vector norm, float f)
Definition at line 440 of file movetypes.qc.
Referenced by _Movetype_FlyMove(), and _Movetype_Physics_Toss().
 {
     vel -= ((vel * norm) * norm) * f;
     if(vel.x > -0.1 && vel.x < 0.1) vel.x = 0;
     if(vel.y > -0.1 && vel.y < 0.1) vel.y = 0;
     if(vel.z > -0.1 && vel.z < 0.1) vel.z = 0;
     return vel;
 }
int _Movetype_FlyMove (entity this, float dt, bool applygravity, vector stepnormal, float stepheight)
Definition at line 37 of file movetypes.qc.
References _Movetype_ClipVelocity(), _Movetype_PushEntity(), cross, fabs(), FL_WATERJUMP, flags, GAMEPLAYFIX_EASIERWATERJUMP, groundentity, IS_ONGROUND, MAX_CLIP_PLANES, move_didgravity, NULL, origin, SET_ONGROUND, sqrt(), trace_allsolid, trace_endpos, trace_ent, trace_fraction, trace_plane_normal, trace_startsolid, vector(), and velocity.
Referenced by _Movetype_Physics_Step(), and _Movetype_Physics_Walk().
 {
     int blocked = 0;
     int i, j, numplanes = 0;
     float time_left = dt, grav = 0;
     vector push;
     vector primal_velocity, original_velocity, restore_velocity;
     for(i = 0; i < MAX_CLIP_PLANES; ++i)
         planes[i] = '0 0 0';
     if(applygravity)
     {
         this.move_didgravity = 1;
         grav = dt * (PHYS_ENTGRAVITY(this) ? PHYS_ENTGRAVITY(this) : 1) * PHYS_GRAVITY(this);
         if(!GAMEPLAYFIX_NOGRAVITYONGROUND || !IS_ONGROUND(this))
         {
             if(GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
                 this.velocity_z -= grav * 0.5;
             else
                 this.velocity_z -= grav;
         }
     }
     original_velocity = primal_velocity = restore_velocity = this.velocity;
     for(int bumpcount = 0;bumpcount < MAX_CLIP_PLANES;bumpcount++)
     {
         if(this.velocity == '0 0 0')
             break;
         push = this.velocity * time_left;
         _Movetype_PushEntity(this, push, true);
         if(trace_startsolid)
         {
             // we got teleported by a touch function
             // let's abort the move
             blocked |= 8;
             break;
         }
         // this code is used by MOVETYPE_WALK and MOVETYPE_STEP and SV_UnstickEntity
         // abort move if we're stuck in the world (and didn't make it out)
         if(trace_startsolid && trace_allsolid)
         {
             this.velocity = restore_velocity;
             return 3;
         }
         if(trace_fraction == 1)
             break;
         float my_trace_fraction = trace_fraction;
         vector my_trace_plane_normal = trace_plane_normal;
         if(trace_plane_normal.z)
         {
             if(trace_plane_normal.z > 0.7)
             {
                 // floor
                 blocked |= 1;
                 if(!trace_ent)
                 {
                     //dprint("_Movetype_FlyMove: !trace_ent\n");
                     trace_ent = NULL;
                 }
                 SET_ONGROUND(this);
                 this.groundentity = trace_ent;
             }
         }
         else if(stepheight)
         {
             // step - handle it immediately
             vector org = this.origin;
             vector steppush = '0 0 1' * stepheight;
             _Movetype_PushEntity(this, steppush, true);
             if(trace_startsolid)
             {
                 blocked |= 8;
                 break;
             }
             _Movetype_PushEntity(this, push, true);
             if(trace_startsolid)
             {
                 blocked |= 8;
                 break;
             }
             float trace2_fraction = trace_fraction;
             steppush = '0 0 1' * (org.z - this.origin_z);
             _Movetype_PushEntity(this, steppush, true);
             if(trace_startsolid)
             {
                 blocked |= 8;
                 break;
             }
             // accept the new position if it made some progress...
             if(fabs(this.origin_x - org.x) >= 0.03125 || fabs(this.origin_y - org.y) >= 0.03125)
             {
                 trace_endpos = this.origin;
                 time_left *= 1 - trace2_fraction;
                 numplanes = 0;
                 continue;
             }
             else
                 this.origin = org;
         }
         else
         {
             // step - return it to caller
             blocked |= 2;
             // save the trace for player extrafriction
             if(stepnormal)
                 stepnormal = trace_plane_normal;
         }
         if(my_trace_fraction >= 0.001)
         {
             // actually covered some distance
             original_velocity = this.velocity;
             numplanes = 0;
         }
         time_left *= 1 - my_trace_fraction;
         // clipped to another plane
         if(numplanes >= MAX_CLIP_PLANES)
         {
             // this shouldn't really happen
             this.velocity = '0 0 0';
             blocked = 3;
             break;
         }
         planes[numplanes] = my_trace_plane_normal;
         numplanes++;
         // modify original_velocity so it parallels all of the clip planes
         vector new_velocity = '0 0 0';
         for (i = 0;i < numplanes;i++)
         {
             new_velocity = _Movetype_ClipVelocity(original_velocity, planes[i], 1);
             for (j = 0;j < numplanes;j++)
             {
                 if(j != i)
                 {
                     // not ok
                     if((new_velocity * planes[j]) < 0)
                         break;
                 }
             }
             if(j == numplanes)
                 break;
         }
         if(i != numplanes)
         {
             // go along this plane
             this.velocity = new_velocity;
         }
         else
         {
             // go along the crease
             if(numplanes != 2)
             {
                 this.velocity = '0 0 0';
                 blocked = 7;
                 break;
             }
             vector dir = cross(planes[0], planes[1]);
             // LordHavoc: thanks to taniwha of QuakeForge for pointing out this fix for slowed falling in corners
             float ilength = sqrt((dir * dir));
             if(ilength)
                 ilength = 1.0 / ilength;
             dir.x *= ilength;
             dir.y *= ilength;
             dir.z *= ilength;
             float d = (dir * this.velocity);
             this.velocity = dir * d;
         }
         // if current velocity is against the original velocity,
         // stop dead to avoid tiny occilations in sloping corners
         if((this.velocity * primal_velocity) <= 0)
         {
             this.velocity = '0 0 0';
             break;
         }
     }
     // LordHavoc: this came from QW and allows you to get out of water more easily
     if(GAMEPLAYFIX_EASIERWATERJUMP(this) && (this.flags & FL_WATERJUMP) && !(blocked & 8))
         this.velocity = primal_velocity;
     if(applygravity)
     {
         if(!GAMEPLAYFIX_NOGRAVITYONGROUND || !IS_ONGROUND(this))
         {
             if(GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
                 this.velocity_z -= grav * 0.5f;
         }
     }
     return blocked;
 }
void _Movetype_Impact (entity this, entity oth)
Definition at line 320 of file movetypes.qc.
Referenced by _Movetype_PushEntity().
 {
     if(gettouch(this))
         gettouch(this)(this, oth);
     if(gettouch(oth))
         gettouch(oth)(oth, this);
 }
void _Movetype_LinkEdict (entity this, bool touch_triggers)
Definition at line 354 of file movetypes.qc.
References _Movetype_LinkEdict_TouchAreaGrid(), absmax, absmin, FL_ITEM, flags, maxs, mins, origin, solid, SOLID_BSP, and vector().
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Follow(), _Movetype_Physics_Frame(), _Movetype_Physics_Step(), _Movetype_Physics_Walk(), and _Movetype_UnstickEntity().
 {
     vector mi, ma;
     if(this.solid == SOLID_BSP)
     {
         // TODO set the absolute bbox
         mi = this.mins;
         ma = this.maxs;
     }
     else
     {
         mi = this.mins;
         ma = this.maxs;
     }
     mi += this.origin;
     ma += this.origin;
     if(this.flags & FL_ITEM)
     {
         mi -= '15 15 1';
         ma += '15 15 1';
     }
     else
     {
         mi -= '1 1 1';
         ma += '1 1 1';
     }
     this.absmin = mi;
     this.absmax = ma;
     if(touch_triggers)
         _Movetype_LinkEdict_TouchAreaGrid(this);
 }
void _Movetype_LinkEdict_TouchAreaGrid (entity this)
Definition at line 329 of file movetypes.qc.
References absmax, absmin, boxesoverlap(), MOVE_NOMONSTERS, MOVE_WORLDONLY, solid, SOLID_NOT, SOLID_TRIGGER, trace_allsolid, trace_endpos, trace_ent, trace_fraction, trace_inopen, trace_inwater, trace_plane_dist, trace_plane_normal, trace_startsolid, and vlen().
Referenced by _Movetype_LinkEdict().
 {
     if(this.solid == SOLID_NOT)
         return;
     FOREACH_ENTITY_RADIUS(0.5 * (this.absmin + this.absmax), 0.5 * vlen(this.absmax - this.absmin), true, {
         if (it.solid == SOLID_TRIGGER && it != this)
         if (it.move_nomonsters != MOVE_NOMONSTERS && it.move_nomonsters != MOVE_WORLDONLY)
         if (gettouch(it) && boxesoverlap(it.absmin, it.absmax, this.absmin, this.absmax))
         {
             trace_allsolid = false;
             trace_startsolid = false;
             trace_fraction = 1;
             trace_inwater = false;
             trace_inopen = true;
             trace_endpos = it.origin;
             trace_plane_normal = '0 0 1';
             trace_plane_dist = 0;
             trace_ent = this;
             gettouch(it)(it, this);
         }
     });
 }
void _Movetype_Physics_ClientFrame (entity this, float movedt)
Definition at line 529 of file movetypes.qc.
References _Movetype_CheckWater(), _Movetype_LinkEdict(), _Movetype_Physics_Follow(), _Movetype_Physics_Step(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), angles, avelocity, LOG_DEBUGF, move_didgravity, move_movetype, MOVETYPE_BOUNCE, MOVETYPE_BOUNCEMISSILE, MOVETYPE_FAKEPUSH, MOVETYPE_FLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_FLYMISSILE, MOVETYPE_FOLLOW, MOVETYPE_NOCLIP, MOVETYPE_NONE, MOVETYPE_PHYSICS, MOVETYPE_PUSH, MOVETYPE_STEP, MOVETYPE_TOSS, MOVETYPE_WALK, origin, and velocity.
Referenced by Movetype_Physics_NoMatchTicrate().
 {
     this.move_didgravity = -1;
     switch (this.move_movetype)
     {
         case MOVETYPE_PUSH:
         case MOVETYPE_FAKEPUSH:
             LOG_DEBUGF("Physics: Lacking QuakeC support for Push movetype, FIX ME by using engine physics!");
             break;
         case MOVETYPE_NONE:
             break;
         case MOVETYPE_FOLLOW:
             _Movetype_Physics_Follow(this);
             break;
         case MOVETYPE_NOCLIP:
             _Movetype_CheckWater(this);
             this.origin = this.origin + movedt * this.velocity;
             this.angles = this.angles + movedt * this.avelocity;
             _Movetype_LinkEdict(this, false);
             break;
         case MOVETYPE_STEP:
             _Movetype_Physics_Step(this, movedt);
             break;
         case MOVETYPE_WALK:
         case MOVETYPE_FLY:
         case MOVETYPE_FLY_WORLDONLY:
             _Movetype_Physics_Walk(this, movedt);
             break;
         case MOVETYPE_TOSS:
         case MOVETYPE_BOUNCE:
         case MOVETYPE_BOUNCEMISSILE:
         case MOVETYPE_FLYMISSILE:
             _Movetype_Physics_Toss(this, movedt);
             break;
         case MOVETYPE_PHYSICS:
             break;
     }
 }
void _Movetype_Physics_Frame (entity this, float movedt)
Definition at line 489 of file movetypes.qc.
References _Movetype_CheckWater(), _Movetype_LinkEdict(), _Movetype_Physics_Follow(), _Movetype_Physics_Step(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), angles, avelocity, LOG_DEBUGF, move_didgravity, move_movetype, MOVETYPE_BOUNCE, MOVETYPE_BOUNCEMISSILE, MOVETYPE_FAKEPUSH, MOVETYPE_FLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_FLYMISSILE, MOVETYPE_FOLLOW, MOVETYPE_NOCLIP, MOVETYPE_NONE, MOVETYPE_PHYSICS, MOVETYPE_PUSH, MOVETYPE_STEP, MOVETYPE_TOSS, MOVETYPE_WALK, origin, and velocity.
Referenced by Movetype_Physics_MatchTicrate(), Movetype_Physics_NoMatchServer(), and Movetype_Physics_NoMatchTicrate().
 {
     this.move_didgravity = -1;
     switch (this.move_movetype)
     {
         case MOVETYPE_PUSH:
         case MOVETYPE_FAKEPUSH:
             LOG_DEBUGF("Physics: Lacking QuakeC support for Push movetype, FIX ME by using engine physics!");
             break;
         case MOVETYPE_NONE:
             break;
         case MOVETYPE_FOLLOW:
             _Movetype_Physics_Follow(this);
             break;
         case MOVETYPE_NOCLIP:
             _Movetype_CheckWater(this);
             this.origin = this.origin + movedt * this.velocity;
             this.angles = this.angles + movedt * this.avelocity;
             _Movetype_LinkEdict(this, false);
             break;
         case MOVETYPE_STEP:
             _Movetype_Physics_Step(this, movedt);
             break;
         case MOVETYPE_WALK:
             _Movetype_Physics_Walk(this, movedt);
             break;
         case MOVETYPE_TOSS:
         case MOVETYPE_BOUNCE:
         case MOVETYPE_BOUNCEMISSILE:
         case MOVETYPE_FLYMISSILE:
         case MOVETYPE_FLY:
         case MOVETYPE_FLY_WORLDONLY:
             _Movetype_Physics_Toss(this, movedt);
             _Movetype_LinkEdict(this, true);
             break;
         case MOVETYPE_PHYSICS:
             break;
     }
 }
float _Movetype_PushEntity (entity this, vector push, bool failonstartsolid)
Definition at line 469 of file movetypes.qc.
References _Movetype_Impact(), _Movetype_PushEntityTrace(), groundentity, IS_ONGROUND, origin, solid, SOLID_TRIGGER, trace_endpos, trace_ent, trace_fraction, and trace_startsolid.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_Toss(), and _Movetype_Physics_Walk().
 {
     _Movetype_PushEntityTrace(this, push);
     if(trace_startsolid && failonstartsolid)
         return trace_fraction;
     this.origin = trace_endpos;
     if(trace_fraction < 1)
         if(this.solid >= SOLID_TRIGGER && (!IS_ONGROUND(this) || (this.groundentity != trace_ent)))
             _Movetype_Impact(this, trace_ent);
     return trace_fraction;
 }
void _Movetype_PushEntityTrace (entity this, vector push)
Definition at line 451 of file movetypes.qc.
References max(), maxs, mins, MOVE_MISSILE, move_movetype, move_nomonsters, MOVE_NOMONSTERS, MOVE_NORMAL, MOVE_WORLDONLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_FLYMISSILE, origin, solid, SOLID_NOT, SOLID_TRIGGER, and vector().
Referenced by _Movetype_PushEntity(), and Movetype_Physics_MatchTicrate().
 {
     vector end = this.origin + push;
     int type;
     if(this.move_nomonsters)
         type = max(0, this.move_nomonsters);
     else if(this.move_movetype == MOVETYPE_FLYMISSILE)
         type = MOVE_MISSILE;
     else if(this.move_movetype == MOVETYPE_FLY_WORLDONLY)
         type = MOVE_WORLDONLY;
     else if(this.solid == SOLID_TRIGGER || this.solid == SOLID_NOT)
         type = MOVE_NOMONSTERS;
     else
         type = MOVE_NORMAL;
     tracebox(this.origin, this.mins, this.maxs, end, type, this);
 }
bool _Movetype_TestEntityPosition (vector ofs)
Definition at line 390 of file movetypes.qc.
References _Movetype_TestEntityPosition_ent, DPCONTENTS_SOLID, dphitcontentsmask, entity(), maxs, mins, move_movetype, MOVE_NOMONSTERS, MOVE_WORLDONLY, MOVETYPE_FLY_WORLDONLY, origin, trace_endpos, trace_startsolid, and vdist.
Referenced by _Movetype_UnstickEntity().
 {
     entity this = _Movetype_TestEntityPosition_ent;
 //  vector org = this.origin + ofs;
     int cont = this.dphitcontentsmask;
     this.dphitcontentsmask = DPCONTENTS_SOLID;
     tracebox(this.origin, this.mins, this.maxs, this.origin, ((this.move_movetype == MOVETYPE_FLY_WORLDONLY) ? MOVE_WORLDONLY : MOVE_NOMONSTERS), this);
     this.dphitcontentsmask = cont;
     if(trace_startsolid)
         return true;
     if(vdist(trace_endpos - this.origin, >, 0.0001))
         this.origin = trace_endpos;
     return false;
 }
bool _Movetype_UnstickEntity (entity this)
Definition at line 408 of file movetypes.qc.
References _Movetype_LinkEdict(), _Movetype_TestEntityPosition(), _Movetype_TestEntityPosition_ent, classname, etof(), LOG_DEBUGF, origin, vtos(), and X.
Referenced by _Movetype_Physics_Toss(), and _Movetype_Physics_Walk().
 {
     _Movetype_TestEntityPosition_ent = this;
     if (!_Movetype_TestEntityPosition(' 0  0  0')) {
         return true;
     }
     #define X(v) if (_Movetype_TestEntityPosition(v))
     X('-1  0  0') X(' 1  0  0')
     X(' 0 -1  0') X(' 0  1  0')
     X('-1 -1  0') X(' 1 -1  0')
     X('-1  1  0') X(' 1  1  0')
     #undef X
     {
         #define X(i) \
             if (_Movetype_TestEntityPosition('0 0 -1' * i)) \
             if (_Movetype_TestEntityPosition('0 0 1' * i))
         X(01) X(02) X(03) X(04) X(05) X(06) X(07) X(08)
         X(09) X(10) X(11) X(12) X(13) X(14) X(15) X(16)
         X(17)
         #undef X
         {
             LOG_DEBUGF("Can't unstick an entity (edict: %d, classname: %s, origin: %s)",
                 etof(this), this.classname, vtos(this.origin));
             return false;
         }
     }
     LOG_DEBUGF("Sucessfully unstuck an entity (edict: %d, classname: %s, origin: %s)",
         etof(this), this.classname, vtos(this.origin));
     _Movetype_LinkEdict(this, true);
     return true;
 }
void _Movetype_WallFriction (entity this, vector stepnormal)
Definition at line 19 of file movetypes.qc.
Referenced by _Movetype_Physics_Walk().
 {
     /*float d, i;
     vector into, side;
     makevectors(this.v_angle);
     d = (stepnormal * v_forward) + 0.5;
     if(d < 0)
     {
         i = (stepnormal * this.velocity);
         into = i * stepnormal;
         side = this.velocity - into;
         this.velocity_x = side.x * (1 * d);
         this.velocity_y = side.y * (1 * d);
     }*/
 }
void Movetype_Physics_MatchServer (entity this, bool sloppy)
Definition at line 594 of file movetypes.qc.
References Movetype_Physics_MatchTicrate().
Referenced by Projectile_Draw().
 {
     Movetype_Physics_MatchTicrate(this, TICRATE, sloppy);
 }
void Movetype_Physics_MatchTicrate (entity this, float tr, bool sloppy)
Definition at line 610 of file movetypes.qc.
References _Movetype_Physics_Frame(), _Movetype_PushEntityTrace(), angles, avelocity, FL_ONGROUND, flags, floor(), gravity, max(), move_didgravity, move_movetype, move_time, MOVETYPE_BOUNCE, MOVETYPE_NOCLIP, MOVETYPE_NONE, Movetype_Physics_NoMatchServer(), MOVETYPE_TOSS, origin, setorigin(), tic_angles, tic_avelocity, tic_flags, tic_origin, tic_saved_angles, tic_saved_avelocity, tic_saved_flags, tic_saved_origin, tic_saved_velocity, tic_velocity, time, trace_endpos, trace_startsolid, vector(), velocity, and X.
Referenced by Movetype_Physics_MatchServer(), and turret_gib_draw().
 {
 #define X(s) \
     if(this.(s) != this.tic_saved_##s) \
         this.tic_##s = this.(s)
     X(origin);
     X(velocity);
     X(flags);
     X(avelocity);
     X(angles);
 #undef X
     if(tr <= 0)
     {
         this.flags = this.tic_flags;
         this.velocity = this.tic_velocity;
         this.origin = this.tic_origin;
         this.avelocity = this.tic_avelocity;
         this.angles = this.tic_angles;
         Movetype_Physics_NoMatchServer(this);
         this.tic_origin = this.origin;
         this.tic_velocity = this.velocity;
         this.tic_avelocity = this.avelocity;
         this.tic_angles = this.angles;
         this.tic_flags = this.flags;
         this.tic_saved_flags = this.flags;
         this.tic_saved_velocity = this.velocity;
         this.tic_saved_origin = this.origin;
         this.tic_saved_avelocity = this.avelocity;
         this.tic_saved_angles = this.angles;
         return;
     }
     float dt = time - this.move_time;
     int n = max(0, floor(dt / tr));
     dt -= n * tr;
     this.move_time += n * tr;
     if(!this.move_didgravity)
         this.move_didgravity = ((this.move_movetype == MOVETYPE_BOUNCE || this.move_movetype == MOVETYPE_TOSS) && !(this.tic_flags & FL_ONGROUND));
     for (int i = 0; i < n; ++i)
     {
         this.flags = this.tic_flags;
         this.velocity = this.tic_velocity;
         setorigin(this, this.tic_origin);
         this.avelocity = this.tic_avelocity;
         this.angles = this.tic_angles;
         _Movetype_Physics_Frame(this, tr);
         this.tic_origin = this.origin;
         this.tic_velocity = this.velocity;
         this.tic_avelocity = this.avelocity;
         this.tic_angles = this.angles;
         this.tic_flags = this.flags;
         if(wasfreed(this))
             return;
     }
     this.avelocity = this.tic_avelocity;
     if(dt > 0 && this.move_movetype != MOVETYPE_NONE && !(this.tic_flags & FL_ONGROUND))
     {
         // now continue the move from move_time to time
         this.velocity = this.tic_velocity;
         if(this.move_didgravity > 0)
         {
             this.velocity_z -= (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE ? 0.5 : 1)
                 * dt
                 * (this.gravity ? this.gravity : 1)
                 * PHYS_GRAVITY(this);
         }
         this.angles = this.tic_angles + dt * this.avelocity;
         if(sloppy || this.move_movetype == MOVETYPE_NOCLIP)
         {
             setorigin(this, this.tic_origin + dt * this.velocity);
         }
         else
         {
             vector oldorg = this.origin;
             this.origin = this.tic_origin;
             _Movetype_PushEntityTrace(this, dt * this.velocity);
             this.origin = oldorg;
             if(!trace_startsolid)
                 setorigin(this, trace_endpos);
         }
         if(this.move_didgravity > 0 && GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
             this.velocity_z -= 0.5 * dt * (this.gravity ? this.gravity : 1) * PHYS_GRAVITY(this);
     }
     else
     {
         this.velocity = this.tic_velocity;
         this.angles = this.tic_angles;
         setorigin(this, this.tic_origin);
     }
     this.tic_saved_flags = this.flags;
     this.tic_saved_velocity = this.velocity;
     this.tic_saved_origin = this.origin;
     this.tic_saved_avelocity = this.avelocity;
     this.tic_saved_angles = this.angles;
 }
void Movetype_Physics_NoMatchServer (entity this)
Definition at line 582 of file movetypes.qc.
References _Movetype_Physics_Frame(), move_time, origin, setorigin(), and time.
Referenced by Movetype_Physics_MatchTicrate(), and Projectile_Draw().
 {
     float movedt = time - this.move_time;
     this.move_time = time;
     _Movetype_Physics_Frame(this, movedt);
     if(wasfreed(this))
         return;
     setorigin(this, this.origin);
 }
void Movetype_Physics_NoMatchTicrate (entity this, float movedt, bool isclient)
Definition at line 568 of file movetypes.qc.
References _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), move_time, origin, setorigin(), and time.
Referenced by CSQCPlayer_Physics(), Physics_Frame(), and Player_Physics().
 {
     this.move_time = time;
     if(isclient)
         _Movetype_Physics_ClientFrame(this, movedt);
     else
         _Movetype_Physics_Frame(this, movedt);
     if(wasfreed(this))
         return;
     setorigin(this, this.origin);
 }
void ()
Variable Documentation
entity _Movetype_TestEntityPosition_ent
Definition at line 389 of file movetypes.qc.
Referenced by _Movetype_TestEntityPosition(), and _Movetype_UnstickEntity().
float ltime
Definition at line 486 of file movetypes.qc.
Referenced by door_go_up(), door_hit_top(), door_rotating_go_up(), door_rotating_hit_top(), plat_hit_top(), SUB_CalcAngleMove(), SUB_CalcMove(), SUB_CalcMove_Bezier(), and train_wait().
vector planes[MAX_CLIP_PLANES]
Definition at line 36 of file movetypes.qc.
vector tic_angles
Definition at line 603 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_avelocity
Definition at line 602 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
int tic_flags
Definition at line 601 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_origin
Definition at line 599 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_saved_angles
Definition at line 609 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_saved_avelocity
Definition at line 608 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
int tic_saved_flags
Definition at line 607 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_saved_origin
Definition at line 605 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_saved_velocity
Definition at line 606 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().
vector tic_velocity
Definition at line 600 of file movetypes.qc.
Referenced by Movetype_Physics_MatchTicrate().