Xonotic: server/mutators/mutator/gamemode_ca.qc File Reference
gamemode_ca.qc File Reference
#include "gamemode_ca.qh"
Macros
#define GAMEMODE_CA_H
Functions
bool CA_CheckTeams ()
bool CA_CheckWinner ()
bool ca_isEliminated (entity e)
void CA_RoundStart ()
REGISTER_MUTATOR (ca, false)
void SetLimits (int fraglimit_override, int leadlimit_override, float timelimit_override, float qualifying_override)
Variables
bool allowed_to_spawn
int autocvar_g_ca_point_leadlimit
int autocvar_g_ca_point_limit
float autocvar_g_ca_round_timelimit
bool autocvar_g_ca_team_spawns
int autocvar_g_ca_teams
int autocvar_g_ca_teams_override
float autocvar_g_ca_warmup
int ca_teams
float caplayer
const int ST_CA_ROUNDS = 1
Macro Definition Documentation
#define GAMEMODE_CA_H
Definition at line 3 of file gamemode_ca.qc.
Function Documentation
bool CA_CheckTeams ()
Referenced by REGISTER_MUTATOR().
bool CA_CheckWinner ()
Referenced by REGISTER_MUTATOR().
bool ca_isEliminated (entity e)
Referenced by REGISTER_MUTATOR().
void CA_RoundStart ()
Referenced by REGISTER_MUTATOR().
REGISTER_MUTATOR (ca , false)
Definition at line 26 of file gamemode_ca.qc.
References ActivateTeamplay(), allowed_to_spawn, autocvar_g_ca_point_leadlimit, autocvar_g_ca_point_limit, autocvar_g_ca_round_timelimit, autocvar_g_ca_team_spawns, autocvar_g_ca_teams, autocvar_g_ca_teams_override, autocvar_g_ca_warmup, bound(), CA_CheckTeams(), CA_CheckWinner(), ca_isEliminated(), CA_RoundStart(), ca_teams, EliminatedPlayers_Init(), error(), have_team_spawns, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, ret_float, round_handler_Init(), round_handler_Spawn(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_basics(), ScoreRules_basics_end(), SetLimits(), SFL_SORT_PRIO_PRIMARY, ST_CA_ROUNDS, and time.
 {
     MUTATOR_ONADD
     {
         // game loads at time 1
         if (time > 1) error("This is a game type and it cannot be added at runtime.");
         allowed_to_spawn = true;
         ca_teams = autocvar_g_ca_teams_override;
         if (ca_teams < 2) ca_teams = autocvar_g_ca_teams;
         ca_teams = bound(2, ca_teams, 4);
         ret_float = ca_teams;
         ScoreRules_basics(ca_teams, SFL_SORT_PRIO_PRIMARY, 0, true);
         ScoreInfo_SetLabel_TeamScore(ST_CA_ROUNDS, "rounds", SFL_SORT_PRIO_PRIMARY);
         ScoreRules_basics_end();
         round_handler_Spawn(CA_CheckTeams, CA_CheckWinner, CA_RoundStart);
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         EliminatedPlayers_Init(ca_isEliminated);
         ActivateTeamplay();
         SetLimits(autocvar_g_ca_point_limit, autocvar_g_ca_point_leadlimit, -1, -1);
         if (autocvar_g_ca_team_spawns)
             have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
void SetLimits (int fraglimit_override, int leadlimit_override, float timelimit_override, float qualifying_override)
Definition at line 566 of file g_world.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and limits_are_set.
Referenced by REGISTER_MUTATOR(), and spawnfunc().
 {
     if(!autocvar_g_campaign)
     {
         if(fraglimit_override >= 0) cvar_set("fraglimit", ftos(fraglimit_override));
         if(timelimit_override >= 0) cvar_set("timelimit", ftos(timelimit_override));
         if(leadlimit_override >= 0) cvar_set("leadlimit", ftos(leadlimit_override));
         if(qualifying_override >= 0) cvar_set("g_race_qualifying_timelimit", ftos(qualifying_override));
     }
     limits_are_set = true;
 }
Variable Documentation
bool allowed_to_spawn
Definition at line 15 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_point_leadlimit
Definition at line 6 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_point_limit
Definition at line 5 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_round_timelimit
Definition at line 7 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
bool autocvar_g_ca_team_spawns
Definition at line 8 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_teams
Definition at line 9 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_teams_override
Definition at line 10 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_warmup
Definition at line 11 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
int ca_teams
Definition at line 14 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().
float caplayer
Definition at line 66 of file gamemode_ca.qc.
Referenced by checkSpectatorBlock(), ClientCommand_join(), and LeaveSpectatorMode().
const int ST_CA_ROUNDS = 1
Definition at line 17 of file gamemode_ca.qc.
Referenced by REGISTER_MUTATOR().