Xonotic: menu/xonotic/screenshotlist.qh File Reference
screenshotlist.qh File Reference
#include "listbox.qh"
Classes
class XonoticScreenshotList
Functions
entity makeXonoticScreenshotList ()
void ScreenshotList_Filter_Change (entity box, entity me)
void ScreenshotList_Filter_Would_Change (entity box, entity me)
void ScreenshotList_Refresh_Click (entity btn, entity me)
void StartScreenshot_Click (entity btn, entity me)
Function Documentation
entity makeXonoticScreenshotList ()
Definition at line 8 of file screenshotlist.qc.
References entity(), and NEW.
Referenced by XonoticScreenshotBrowserTab_fill().
 {
     entity me;
     me = NEW(XonoticScreenshotList);
     me.configureXonoticScreenshotList(me);
     return me;
 }
void ScreenshotList_Filter_Change (entity box, entity me)
Definition at line 156 of file screenshotlist.qc.
References NULL, ScreenshotList_Refresh_Click(), strcat(), strfree, strstrofs, and strzone().
Referenced by XonoticScreenshotList_draw().
 {
     strfree(me.filterString);
     if(box.text != "")
     {
         if (strstrofs(box.text, "*", 0) >= 0 || strstrofs(box.text, "?", 0) >= 0)
             me.filterString = strzone(box.text);
         else
             me.filterString = strzone(strcat("*", box.text, "*"));
     }
     ScreenshotList_Refresh_Click(NULL, me);
 }
void ScreenshotList_Filter_Would_Change (entity box, entity me)
Definition at line 171 of file screenshotlist.qc.
References time.
Referenced by XonoticScreenshotBrowserTab_fill().
 {
     me.filterBox = box;
     me.filterTime = time + 0.5;
 }
void ScreenshotList_Refresh_Click (entity btn, entity me)
Definition at line 150 of file screenshotlist.qc.
Referenced by ScreenshotList_Filter_Change(), and XonoticScreenshotBrowserTab_fill().
 {
     me.getScreenshots(me);
     me.setSelected(me, 0); //always select the first element after a list update
 }
void StartScreenshot_Click (entity btn, entity me)
Definition at line 238 of file screenshotlist.qc.
Referenced by XonoticScreenshotBrowserTab_fill().
 {
     me.startScreenshot(me);
 }