Xonotic: common/command/markup.qh File Reference
common/command/markup.qh File Reference
Defines
#define COMMAND_MARKUP_H
Functions
string GenericCommand_markup (string s2)
Variables
const int NUM_MARKUPS = 41
bool markup_init
string markup_from [NUM_MARKUPS]
string markup_to [NUM_MARKUPS]
Define Documentation
#define COMMAND_MARKUP_H
Definition at line 2 of file markup.qh.
Function Documentation
string GenericCommand_markup (string s2)
Definition at line 59 of file markup.qc.
References GenericCommand_markup_init(), markup_from, markup_to, NUM_MARKUPS, s, strcat(), strlen(), and substring().
Referenced by GenericCommand().
{
    int red, ccase, i, j;
    string s, s3;
    GenericCommand_markup_init();
    s = "";
    red = 0;
    ccase = 0;
    for(i = 0; i < strlen(s2); ++i)
    {
        for(j = 0; j < NUM_MARKUPS; ++j)
        {
            s3 = substring(s2, i, strlen(markup_from[j]));
            if (s3 == markup_from[j])
            {
                s = strcat(s, markup_to[j]);
                i += strlen(markup_from[j]) - 1;
                break;
            }
        }
        if(j == NUM_MARKUPS)
        {
            if(substring(s2, i, 2) == "&&")
            {
                s = strcat(s, strconv(ccase, red, red, "&"));
                ++i;
            }
            else if(substring(s2, i, 2) == "&d")
            {
                red = 2;
                ccase = 0;
                ++i;
            }
            else if(substring(s2, i, 2) == "&a")
            {
                red = 2;
                ccase = 2;
                ++i;
            }
            else if(substring(s2, i, 2) == "&n")
            {
                red = 0;
                ccase = 0;
                ++i;
            }
            else
                s = strcat(s, strconv(ccase, red, red, substring(s2, i, 1)));
        }
    }
    return s;
}
Variable Documentation
string markup_from[NUM_MARKUPS]
Definition at line 11 of file markup.qh.
Referenced by GenericCommand_markup(), and GenericCommand_markup_init().
bool markup_init
Definition at line 10 of file markup.qh.
Referenced by GenericCommand_markup_init().
string markup_to[NUM_MARKUPS]
Definition at line 12 of file markup.qh.
Referenced by GenericCommand_markup(), and GenericCommand_markup_init().
const int NUM_MARKUPS = 41
Definition at line 9 of file markup.qh.
Referenced by GenericCommand_markup().