Xonotic: common/mutators/mutator/breakablehook/sv_breakablehook.qc File Reference
sv_breakablehook.qc File Reference
#include "sv_breakablehook.qh"
#include <common/deathtypes/all.qh>
#include <server/g_hook.qh>
Functions
MUTATOR_HOOKFUNCTION (breakablehook, Damage_Calculate)
REGISTER_MUTATOR (breakablehook, cvar("g_breakablehook"))
Variables
bool autocvar_g_breakablehook
bool autocvar_g_breakablehook_owner
Function Documentation
MUTATOR_HOOKFUNCTION (breakablehook , Damage_Calculate)
Definition at line 11 of file sv_breakablehook.qc.
References Damage(), DIFF_TEAM, DMG_NOWEP, entity(), HITTYPE_SPLASH, M_ARGV, and RemoveHook().
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     if(frag_target.classname == "grapplinghook")
     {
         if((!autocvar_g_breakablehook)
         || (!autocvar_g_breakablehook_owner && frag_attacker == frag_target.realowner)
             ) { M_ARGV(4, float) = 0; }
         // hurt the owner of the hook
         if(DIFF_TEAM(frag_attacker, frag_target.realowner))
         {
             Damage (frag_target.realowner, frag_attacker, frag_attacker, 5, WEP_HOOK.m_id | HITTYPE_SPLASH, DMG_NOWEP, frag_target.realowner.origin, '0 0 0'); // TODO: should get weapon entity from mutator hook
             RemoveHook(frag_target);
             return; // dead
         }
     }
 }
REGISTER_MUTATOR (breakablehook , cvar("g_breakablehook"))
Variable Documentation
bool autocvar_g_breakablehook
Definition at line 8 of file sv_breakablehook.qc.
bool autocvar_g_breakablehook_owner
Definition at line 9 of file sv_breakablehook.qc.