Xonotic: KeyHunt Class Reference
KeyHunt Class Reference
Public Member Functions
KeyHunt ()
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_configuremenu ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isForcedSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
virtual void m_setTeams ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
bool m_hidelimits = false
should this gametype display a score limit in the scoreboard?
int m_id = 0
string m_legacydefaults = "1000 20 3 0"
int m_priority = 0
game type priority in random selections
bool m_weaponarena = false
does this gametype enforce its own weapon arena?
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 8 of file keyhunt.qh.
Constructor & Destructor Documentation
KeyHunt::KeyHunt () inline
Definition at line 9 of file keyhunt.qh.
References GAMETYPE_FLAG_TEAMPLAY, and GAMETYPE_FLAG_USEPOINTS.
     {
         this.gametype_init(this, _("Key Hunt"),"kh","g_keyhunt",GAMETYPE_FLAG_TEAMPLAY | GAMETYPE_FLAG_USEPOINTS,"","timelimit=20 pointlimit=1000 teams=3 leadlimit=0",_("Gather all the keys to win the round"));
     }
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
virtual void Gametype::describe () inline virtual inherited
Definition at line 89 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual inherited
Definition at line 95 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual inherited
Definition at line 101 of file mapinfo.qh.
References cons(), ENDCLASS, GAMETYPE_FLAG_HIDELIMITS, GAMETYPE_FLAG_PREFERRED, GAMETYPE_FLAG_PRIORITY, GAMETYPE_FLAG_TEAMPLAY, GAMETYPE_FLAG_USEPOINTS, GAMETYPE_FLAG_WEAPONARENA, m_flags, MAPINFO_TYPE_ALL, NULL, REGISTER_REGISTRY, REGISTRY, REGISTRY_CHECK(), REGISTRY_DEFINE_GET, and REGISTRY_SORT().
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = (gflags & GAMETYPE_FLAG_TEAMPLAY);
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = (gflags & GAMETYPE_FLAG_USEPOINTS);
         this.m_priority = ((gflags & GAMETYPE_FLAG_PREFERRED) ? 2 : ((gflags & GAMETYPE_FLAG_PRIORITY) ? 1 : 0));
         this.m_hidelimits = (gflags & GAMETYPE_FLAG_HIDELIMITS);
         this.m_weaponarena = (gflags & GAMETYPE_FLAG_WEAPONARENA);
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void KeyHunt::m_configuremenu () inline virtual
Reimplemented from Gametype.
Definition at line 36 of file keyhunt.qh.
References ATTRIB, HUD_Mod_KH(), TC, and vector().
     {
         TC(Gametype, this);
         returns(menu, _("Point limit:"),   200, 1500, 50, "g_keyhunt_point_limit",     "g_keyhunt_teams_override",     _("The amount of points needed before the match will end"));
     }
virtual void Gametype::m_generate_mapinfo () inline virtual inherited
Reimplemented in Domination, Race, Invasion, CaptureTheFlag, RaceCTS, NexBall, Assault, and Onslaught.
Definition at line 67 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
virtual void KeyHunt::m_isAlwaysSupported () inline virtual
Reimplemented from Gametype.
Definition at line 26 of file keyhunt.qh.
     {
         if(spawnpoints >= 12 && diameter > 5120)
             return true;
         return false;
     }
virtual void Gametype::m_isForcedSupported () inline virtual inherited
Reimplemented in TeamDeathmatch, and Duel.
Definition at line 79 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_isTwoBaseMode () inline virtual inherited
Reimplemented in Race, CaptureTheFlag, NexBall, and Assault.
Definition at line 71 of file mapinfo.qh.
     {
         return false;
     }
virtual void KeyHunt::m_parse_mapinfo () inline virtual
Reimplemented from Gametype.
Definition at line 13 of file keyhunt.qh.
References cvar_defstring(), and cvar_set().
     {
         if (!k) {
             cvar_set("g_keyhunt_teams", cvar_defstring("g_keyhunt_teams"));
             return true;
         }
         switch (k) {
             case "teams":
                 cvar_set("g_keyhunt_teams", v);
                 return true;
         }
         return false;
     }
virtual void KeyHunt::m_setTeams () inline virtual
Definition at line 32 of file keyhunt.qh.
References cvar_set().
     {
         cvar_set("g_keyhunt_teams", sa);
     }
Member Data Documentation
bool Gametype::frags = true inherited
does this gametype use a point limit?
Definition at line 42 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
int Gametype::items = 0 inherited
game type ID
Definition at line 32 of file mapinfo.qh.
bool Gametype::m_hidelimits = false inherited
should this gametype display a score limit in the scoreboard?
Definition at line 44 of file mapinfo.qh.
int Gametype::m_id = 0 inherited
Definition at line 30 of file mapinfo.qh.
string KeyHunt::m_legacydefaults = "1000 20 3 0"
Definition at line 44 of file keyhunt.qh.
int Gametype::m_priority = 0 inherited
game type priority in random selections
Definition at line 52 of file mapinfo.qh.
bool Gametype::m_weaponarena = false inherited
does this gametype enforce its own weapon arena?
Definition at line 46 of file mapinfo.qh.
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 40 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/gamemodes/gamemode/keyhunt/keyhunt.qh