Xonotic: menu/xonotic/colorpicker.qh File Reference
colorpicker.qh File Reference
#include "../item/image.qh"
Classes
class XonoticColorpicker
Functions
vector color_hslimage (vector v, vector margin)
vector hslimage_color (vector v, vector margin)
entity makeXonoticColorpicker (entity theTextbox)
Function Documentation
vector color_hslimage (vector v, vector margin)
Definition at line 40 of file colorpicker.qc.
References rgb_to_hsl(), and vector().
Referenced by XonoticColorpickerString_loadCvars().
 {
     vector pos = '0 0 0';
     v = rgb_to_hsl(v);
     if (v.y)
     {
         pos_x = v.x / 6;
         pos_y = v.z * 0.875;
     }
     else // grey scale
     {
         pos_x = v.z;
         pos_y = 0.875 + 0.07;
     }
     pos_x = margin.x + pos.x * (1 - 2 * margin.x);
     pos_y = margin.y + pos.y * (1 - 2 * margin.y);
     return pos;
 }
vector hslimage_color (vector v, vector margin)
Definition at line 26 of file colorpicker.qc.
References eX, eY, eZ, and hsl_to_rgb().
Referenced by XonoticColorpicker_mouseDrag(), and XonoticColorpickerString_saveCvars().
 {
     v_x = (v.x - margin.x) / (1 - 2 * margin.x);
     v_y = (v.y - margin.y) / (1 - 2 * margin.y);
     if(v.x < 0) v_x = 0;
     if(v.y < 0) v_y = 0;
     if(v.x > 1) v_x = 1;
     if(v.y > 1) v_y = 1;
     if(v.y > 0.875) // grey bar
         return hsl_to_rgb(eZ * v.x);
     else
         return hsl_to_rgb(v.x * 6 * eX + eY + v.y / 0.875 * eZ);
 }
entity makeXonoticColorpicker (entity theTextbox)
Definition at line 5 of file colorpicker.qc.
References entity(), and NEW.
Referenced by XonoticFirstRunDialog_fill(), and XonoticProfileTab_fill().
 {
     entity me;
     me = NEW(XonoticColorpicker);
     me.configureXonoticColorpicker(me, theTextbox);
     return me;
 }