Xonotic: server/resources.qc File Reference
resources.qc File Reference
Source file that contains implementation of the resource system.
#include "resources.qh"
#include "autocvars.qh"
#include "miscfunctions.qh"
Functions
float GetResourceAmount (entity e, int resource_type)
Returns the current amount of resource the given entity has.
float GetResourceField (int resource_type)
Converts resource type (a RESOURCE_* constant) to entity field.
float GetResourceLimit (entity e, int resource_type)
Returns the maximum amount of the given resource.
int GetResourceType (.float resource_field)
Converts an entity field to resource type.
void GiveResource (entity receiver, int resource_type, float amount)
Gives an entity some resource.
void GiveResourceWithLimit (entity receiver, int resource_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
void SetResourceAmount (entity e, int resource_type, float amount)
Sets the current amount of resource the given entity will have.
Detailed Description
Source file that contains implementation of the resource system.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file resources.qc.
Function Documentation
float GetResourceAmount (entity e, int resource_type)
Returns the current amount of resource the given entity has.
Parameters
[in] e Entity to check.
[in] resource_type Type of the resource (a RESOURCE_* constant).
Returns
Current amount of resource the given entity has.
Definition at line 71 of file resources.qc.
References GetResourceField().
Referenced by buff_Medic_Heal(), CheatImpulse(), frag_centermessage_override(), GiveResource(), GiveResourceWithLimit(), havocbot_goalrating_item_can_be_left_to_teammate(), instagib_ammocheck(), MUTATOR_HOOKFUNCTION(), Obituary(), W_DecreaseAmmo(), W_Reload(), W_ReloadedAndReady(), and W_ThrowNewWeapon().
 {
     .float resource_field = GetResourceField(resource_type);
     return e.(resource_field);
 }
float GetResourceField (int resource_type)
Converts resource type (a RESOURCE_* constant) to entity field.
Parameters
[in] resource_type Type of the resource.
Returns
Entity field for that resource.
Definition at line 196 of file resources.qc.
References ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, ammo_shells, armorvalue, error, health, RESOURCE_ARMOR, RESOURCE_BULLETS, RESOURCE_CELLS, RESOURCE_FUEL, RESOURCE_HEALTH, RESOURCE_PLASMA, RESOURCE_ROCKETS, and RESOURCE_SHELLS.
Referenced by GetResourceAmount(), and SetResourceAmount().
 {
     switch (resource_type)
     {
         case RESOURCE_HEALTH: { return health; }
         case RESOURCE_ARMOR: { return armorvalue; }
         case RESOURCE_SHELLS: { return ammo_shells; }
         case RESOURCE_BULLETS: { return ammo_nails; }
         case RESOURCE_ROCKETS: { return ammo_rockets; }
         case RESOURCE_CELLS: { return ammo_cells; }
         case RESOURCE_PLASMA: { return ammo_plasma; }
         case RESOURCE_FUEL: { return ammo_fuel; }
     }
     error("GetResourceField: Invalid resource type.");
     return health;
 }
float GetResourceLimit (entity e, int resource_type)
Returns the maximum amount of the given resource.
Parameters
[in] e Entity to check.
[in] resource_type Type of the resource (a RESOURCE_* constant).
Returns
Maximum amount of the given resource.
Definition at line 11 of file resources.qc.
References autocvar_g_balance_armor_limit, autocvar_g_balance_fuel_limit, autocvar_g_balance_health_limit, error, g_pickup_cells_max, g_pickup_nails_max, g_pickup_plasma_max, g_pickup_rockets_max, g_pickup_shells_max, GetResourceLimit(), M_ARGV, MUTATOR_CALLHOOK, RESOURCE_AMOUNT_HARD_LIMIT, RESOURCE_ARMOR, RESOURCE_BULLETS, RESOURCE_CELLS, RESOURCE_FUEL, RESOURCE_HEALTH, RESOURCE_PLASMA, RESOURCE_ROCKETS, and RESOURCE_SHELLS.
Referenced by GetResourceLimit(), player_regen(), and SetResourceAmount().
 {
     float limit;
     switch (resource_type)
     {
         case RESOURCE_HEALTH:
         {
             limit = autocvar_g_balance_health_limit;
             break;
         }
         case RESOURCE_ARMOR:
         {
             limit = autocvar_g_balance_armor_limit;
             break;
         }
         case RESOURCE_SHELLS:
         {
             limit = g_pickup_shells_max;
             break;
         }
         case RESOURCE_BULLETS:
         {
             limit = g_pickup_nails_max;
             break;
         }
         case RESOURCE_ROCKETS:
         {
             limit = g_pickup_rockets_max;
             break;
         }
         case RESOURCE_CELLS:
         {
             limit = g_pickup_cells_max;
             break;
         }
         case RESOURCE_PLASMA:
         {
             limit = g_pickup_plasma_max;
             break;
         }
         case RESOURCE_FUEL:
         {
             limit = autocvar_g_balance_fuel_limit;
             break;
         }
         default:
         {
             error("GetResourceLimit: Invalid resource type.");
             return 0;
         }
     }
     MUTATOR_CALLHOOK(GetResourceLimit, e, resource_type, limit);
     limit = M_ARGV(2, float);
     if (limit > RESOURCE_AMOUNT_HARD_LIMIT)
     {
         limit = RESOURCE_AMOUNT_HARD_LIMIT;
     }
     return limit;
 }
int GetResourceType (.float resource_field)
Converts an entity field to resource type.
Parameters
[in] resource_field Entity field to convert.
Returns
Resource type (a RESOURCE_* constant).
Definition at line 179 of file resources.qc.
References ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, ammo_shells, armorvalue, error, health, RESOURCE_ARMOR, RESOURCE_BULLETS, RESOURCE_CELLS, RESOURCE_FUEL, RESOURCE_HEALTH, RESOURCE_PLASMA, RESOURCE_ROCKETS, and RESOURCE_SHELLS.
 {
     switch (resource_field)
     {
         case health: { return RESOURCE_HEALTH; }
         case armorvalue: { return RESOURCE_ARMOR; }
         case ammo_shells: { return RESOURCE_SHELLS; }
         case ammo_nails: { return RESOURCE_BULLETS; }
         case ammo_rockets: { return RESOURCE_ROCKETS; }
         case ammo_cells: { return RESOURCE_CELLS; }
         case ammo_plasma: { return RESOURCE_PLASMA; }
         case ammo_fuel: { return RESOURCE_FUEL; }
     }
     error("GetResourceType: Invalid field.");
     return 0;
 }
void GiveResource (entity receiver, int resource_type, float amount)
Gives an entity some resource.
Parameters
[in,out] receiver Entity to give resource to.
[in] resource_type Type of the resource (a RESOURCE_* constant).
[in] amount Amount of resource to give.
Returns
No return.
Definition at line 106 of file resources.qc.
References autocvar_g_balance_pause_armor_rot, autocvar_g_balance_pause_fuel_rot, autocvar_g_balance_pause_health_rot, GetResourceAmount(), GiveResource(), M_ARGV, max(), MUTATOR_CALLHOOK, RESOURCE_ARMOR, RESOURCE_FUEL, RESOURCE_HEALTH, SetResourceAmount(), and time.
Referenced by GiveResource(), GiveResourceWithLimit(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), and W_ThrowNewWeapon().
 {
     if (amount == 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResource, receiver, resource_type,
         amount);
     if (forbid)
     {
         return;
     }
     resource_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     if (amount <= 0)
     {
         return;
     }
     SetResourceAmount(receiver, resource_type,
         GetResourceAmount(receiver, resource_type) + amount);
     switch (resource_type)
     {
         case RESOURCE_HEALTH:
         {
             receiver.pauserothealth_finished =
                 max(receiver.pauserothealth_finished, time +
                 autocvar_g_balance_pause_health_rot);
             return;
         }
         case RESOURCE_ARMOR:
         {
             receiver.pauserotarmor_finished =
                 max(receiver.pauserotarmor_finished, time +
                 autocvar_g_balance_pause_armor_rot);
             return;
         }
         case RESOURCE_FUEL:
         {
             receiver.pauserotfuel_finished = max(receiver.pauserotfuel_finished,
                 time + autocvar_g_balance_pause_fuel_rot);
             return;
         }
     }
 }
void GiveResourceWithLimit (entity receiver, int resource_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
Parameters
[in,out] receiver Entity to give resource to.
[in] resource_type Type of the resource (a RESOURCE_* constant).
[in] amount Amount of resource to give.
[in] limit Limit of resources to give.
Returns
No return.
Definition at line 151 of file resources.qc.
References GetResourceAmount(), GiveResource(), GiveResourceWithLimit(), M_ARGV, and MUTATOR_CALLHOOK.
Referenced by GiveResourceWithLimit(), and MUTATOR_HOOKFUNCTION().
 {
     if (amount == 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResourceWithLimit, receiver,
         resource_type, amount, limit);
     if (forbid)
     {
         return;
     }
     resource_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     limit = M_ARGV(3, float);
     if (amount == 0)
     {
         return;
     }
     float current_amount = GetResourceAmount(receiver, resource_type);
     if (current_amount + amount > limit)
     {
         amount = limit - current_amount;
     }
     GiveResource(receiver, resource_type, amount);
 }
void SetResourceAmount (entity e, int resource_type, float amount)
Sets the current amount of resource the given entity will have.
Parameters
[in,out] e Entity to adjust.
[in] resource_type Type of the resource (a RESOURCE_* constant).
[in] amount Amount of resource to set.
Returns
No return.
Definition at line 77 of file resources.qc.
References GetResourceField(), GetResourceLimit(), M_ARGV, MUTATOR_CALLHOOK, and SetResourceAmount().
Referenced by buff_Medic_Heal(), CheatImpulse(), Damage(), Freeze(), GiveResource(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), PutPlayerInServer(), SetResourceAmount(), target_init_use(), Unfreeze(), W_DecreaseAmmo(), W_ReloadedAndReady(), and W_ThrowNewWeapon().
 {
     bool forbid = MUTATOR_CALLHOOK(SetResourceAmount, e, resource_type, amount);
     if (forbid)
     {
         return;
     }
     resource_type = M_ARGV(1, int);
     amount = M_ARGV(2, float);
     float max_amount = GetResourceLimit(e, resource_type);
     float amount_wasted = 0;
     if (amount > max_amount)
     {
         amount_wasted = amount - max_amount;
         amount = max_amount;
     }
     .float resource_field = GetResourceField(resource_type);
     if (e.(resource_field) != amount)
     {
         e.(resource_field) = amount;
         MUTATOR_CALLHOOK(ResourceAmountChanged, e, resource_type, amount);
     }
     if (amount_wasted == 0)
     {
         return;
     }
     MUTATOR_CALLHOOK(ResourceWasted, e, resource_type, amount_wasted);
 }