Xonotic: menu/xonotic/credits.qc File Reference
credits.qc File Reference
#include "credits.qh"
Macros
#define _CREDITS_PERSON(p) CREDITS_PERSON(#p)
#define CREDITS(TITLE, FUNCTION, PERSON, PERSON_, NL)
#define CREDITS_FUNCTION(f) credits_add_line(fh, n, CREDITS_TYPE_FUNCTION, f);
#define CREDITS_NL() credits_add_line(fh, n, CREDITS_TYPE_NL, "");
#define CREDITS_PERSON(p) credits_add_line(fh, n, CREDITS_TYPE_PERSON, p);
#define CREDITS_TITLE(t) credits_add_line(fh, n, CREDITS_TYPE_TITLE, t);
Functions
void credits_add_line (int fh, int n, int type, string line)
void credits_build (int fh, int n)
void credits_export ()
int credits_get ()
entity makeXonoticCreditsList ()
void XonoticCreditsList_configureXonoticCreditsList (entity me)
void XonoticCreditsList_destroy (entity me)
void XonoticCreditsList_draw (entity me)
void XonoticCreditsList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
float XonoticCreditsList_keyDown (entity me, float key, float ascii, float shift)
void XonoticCreditsList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Variables
int CREDITS_TYPE_FUNCTION = 1
int CREDITS_TYPE_NL = -1
int CREDITS_TYPE_PERSON = 0
int CREDITS_TYPE_TITLE = 2
Macro Definition Documentation
_CREDITS_PERSON
#define _CREDITS_PERSON (p) CREDITS_PERSON(#p)
Referenced by credits_build().
CREDITS
#define CREDITS (TITLE, FUNCTION, PERSON, PERSON_, NL)
Definition at line 3 of file credits.qc.
Referenced by credits_build().
CREDITS_FUNCTION
#define CREDITS_FUNCTION (f) credits_add_line(fh, n, CREDITS_TYPE_FUNCTION, f);
Referenced by credits_build().
CREDITS_NL
#define CREDITS_NL () credits_add_line(fh, n, CREDITS_TYPE_NL, "");
Referenced by credits_build().
CREDITS_PERSON
#define CREDITS_PERSON (p) credits_add_line(fh, n, CREDITS_TYPE_PERSON, p);
Referenced by credits_build().
CREDITS_TITLE
#define CREDITS_TITLE (t) credits_add_line(fh, n, CREDITS_TYPE_TITLE, t);
Referenced by credits_build().
Function Documentation
credits_add_line()
void credits_add_line (int fh, int n, int type, string line)
Definition at line 414 of file credits.qc.
References CREDITS_TYPE_FUNCTION, CREDITS_TYPE_TITLE, fputs(), and strcat().
 {
     if (type == CREDITS_TYPE_TITLE)
         line = strcat("**", line);
     else if (type == CREDITS_TYPE_FUNCTION)
         line = strcat("*", line);
     if (fh >= 0)
         fputs(fh, strcat(line, "\n"));
     if (n >= 0)
         bufstr_add(n, line, 0);
 }
credits_build()
void credits_build (int fh, int n)
Definition at line 427 of file credits.qc.
References _CREDITS_PERSON, CREDITS, CREDITS_FUNCTION, CREDITS_NL, CREDITS_PERSON, and CREDITS_TITLE.
Referenced by credits_export(), and credits_get().
 {
     #define CREDITS_TITLE(t) credits_add_line(fh, n, CREDITS_TYPE_TITLE, t);
     #define CREDITS_FUNCTION(f) credits_add_line(fh, n, CREDITS_TYPE_FUNCTION, f);
     #define CREDITS_PERSON(p) credits_add_line(fh, n, CREDITS_TYPE_PERSON, p);
     #define _CREDITS_PERSON(p) CREDITS_PERSON(#p)
     #define CREDITS_NL() credits_add_line(fh, n, CREDITS_TYPE_NL, "");
     CREDITS(CREDITS_TITLE, CREDITS_FUNCTION, _CREDITS_PERSON, CREDITS_PERSON, CREDITS_NL)
     #undef CREDITS_TITLE
     #undef CREDITS_FUNCTION
     #undef CREDITS_PERSON
     #undef _CREDITS_PERSON
     #undef CREDITS_NL
 }
credits_export()
void credits_export ()
Definition at line 449 of file credits.qc.
References credits_build(), FILE_WRITE, and fopen().
Referenced by XonoticCreditsList_configureXonoticCreditsList().
 {
     int fh = fopen("credits.txt", FILE_WRITE);
     if(fh < 0)
         return;
     credits_build(fh, -1);
 }
credits_get()
int credits_get ()
Definition at line 442 of file credits.qc.
References buf_create, and credits_build().
Referenced by XonoticCreditsList_configureXonoticCreditsList().
 {
     int n = buf_create();
     credits_build(-1, n);
     return n;
 }
makeXonoticCreditsList()
entity makeXonoticCreditsList ()
Definition at line 459 of file credits.qc.
References entity(), and NEW.
Referenced by XonoticCreditsDialog_fill().
 {
     entity me;
     me = NEW(XonoticCreditsList);
     me.configureXonoticCreditsList(me);
     return me;
 }
XonoticCreditsList_configureXonoticCreditsList()
void XonoticCreditsList_configureXonoticCreditsList (entity me)
Definition at line 466 of file credits.qc.
References credits_export(), credits_get(), cvar(), and cvar_set().
 {
     me.configureXonoticListBox(me);
     me.bufferIndex = credits_get();
     me.nItems = buf_getsize(me.bufferIndex);
     if (cvar("_menu_credits_export")) // set by the menu_credits_export alias
     {
         credits_export();
         cvar_set("_menu_credits_export", "0");
     }
 }
XonoticCreditsList_destroy()
void XonoticCreditsList_destroy (entity me)
Definition at line 477 of file credits.qc.
 {
     buf_del(me.bufferIndex);
 }
XonoticCreditsList_draw()
void XonoticCreditsList_draw (entity me)
Definition at line 481 of file credits.qc.
References bound(), SUPER, and time.
 {
     if(me.scrolling)
     {
         me.scrollPos = bound(0, (time - me.scrolling) * me.itemHeight, me.nItems * me.itemHeight - 1);
         me.scrollPosTarget = me.scrollPos;
     }
     SUPER(XonoticCreditsList).draw(me);
 }
XonoticCreditsList_drawListBoxItem()
void XonoticCreditsList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 498 of file credits.qc.
References draw_CenterText(), eX, eY, strlen(), substring(), and vector().
 {
     string s;
     float theAlpha;
     vector theColor;
     s = bufstr_get(me.bufferIndex, i);
     if(substring(s, 0, 2) == "**")
     {
         s = substring(s, 2, strlen(s) - 2);
         theColor = SKINCOLOR_CREDITS_TITLE;
         theAlpha = SKINALPHA_CREDITS_TITLE;
     }
     else if(substring(s, 0, 1) == "*")
     {
         s = substring(s, 1, strlen(s) - 1);
         theColor = SKINCOLOR_CREDITS_FUNCTION;
         theAlpha = SKINALPHA_CREDITS_FUNCTION;
     }
     else
     {
         theColor = SKINCOLOR_CREDITS_PERSON;
         theAlpha = SKINALPHA_CREDITS_PERSON;
     }
     draw_CenterText(me.realUpperMargin * eY + 0.5 * eX, s, me.realFontSize, theColor, theAlpha, 0);
 }
XonoticCreditsList_keyDown()
float XonoticCreditsList_keyDown (entity me, float key, float ascii, float shift)
Definition at line 527 of file credits.qc.
References SUPER.
 {
     me.scrolling = 0;
     return SUPER(XonoticCreditsList).keyDown(me, key, ascii, shift);
 }
XonoticCreditsList_resizeNotify()
void XonoticCreditsList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 490 of file credits.qc.
References SUPER.
 {
     SUPER(XonoticCreditsList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.realFontSize_y = me.fontSize / (absSize.y * me.itemHeight);
     me.realFontSize_x = me.fontSize / (absSize.x * (1 - me.controlWidth));
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
 }
Variable Documentation
CREDITS_TYPE_FUNCTION
int CREDITS_TYPE_FUNCTION = 1
Definition at line 411 of file credits.qc.
Referenced by credits_add_line().
CREDITS_TYPE_NL
int CREDITS_TYPE_NL = -1
Definition at line 413 of file credits.qc.
CREDITS_TYPE_PERSON
int CREDITS_TYPE_PERSON = 0
Definition at line 412 of file credits.qc.
CREDITS_TYPE_TITLE
int CREDITS_TYPE_TITLE = 2
Definition at line 410 of file credits.qc.
Referenced by credits_add_line().