Xonotic: common/resources/sv_resources.qh File Reference
sv_resources.qh File Reference
Header file that describes the resource system.
#include <common/resources/resources.qh>
Functions
float GetResource (entity e, Resource res_type)
Returns the current amount of resource the given entity has.
float GetResourceLimit (entity e, Resource res_type)
Returns the maximum amount of the given resource.
void GiveResource (entity receiver, Resource res_type, float amount)
Gives an entity some resource.
void GiveResourceWithLimit (entity receiver, Resource res_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
void SetResource (entity e, Resource res_type, float amount)
Sets the current amount of resource the given entity will have but limited to the max amount allowed for the resource type.
bool SetResourceExplicit (entity e, Resource res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
void TakeResource (entity receiver, Resource res_type, float amount)
Takes an entity some resource.
void TakeResourceWithLimit (entity receiver, Resource res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Variables
int autocvar_g_balance_armor_limit
float autocvar_g_balance_armor_regen
float autocvar_g_balance_armor_regenlinear
int autocvar_g_balance_armor_regenstable
float autocvar_g_balance_armor_rot
float autocvar_g_balance_armor_rotlinear
int autocvar_g_balance_armor_rotstable
float autocvar_g_balance_fuel_limit
float autocvar_g_balance_fuel_regen
float autocvar_g_balance_fuel_regenlinear
int autocvar_g_balance_fuel_regenstable
float autocvar_g_balance_fuel_rot
float autocvar_g_balance_fuel_rotlinear
int autocvar_g_balance_fuel_rotstable
float autocvar_g_balance_health_limit
float autocvar_g_balance_health_regen
float autocvar_g_balance_health_regenlinear
float autocvar_g_balance_health_regenstable
float autocvar_g_balance_health_rot
float autocvar_g_balance_health_rotlinear
float autocvar_g_balance_health_rotstable
float autocvar_g_balance_pause_armor_rot
float autocvar_g_balance_pause_fuel_regen
float autocvar_g_balance_pause_fuel_rot
float autocvar_g_balance_pause_health_regen
float autocvar_g_balance_pause_health_rot
Detailed Description
Header file that describes the resource system.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file sv_resources.qh.
Function Documentation
GetResource()
float GetResource (entity e, Resource res_type)
Returns the current amount of resource the given entity has.
Parameters
[in] e Entity to check.
[in] res_type Type of the resource (a RES_* constant).
Returns
Current amount of resource the given entity has.
Definition at line 10 of file cl_resources.qc.
Referenced by _StartItem(), ammo_pickupevalfunc(), assault_decreaser_sprite_visible(), assault_objective_decrease_use(), assault_wall_think(), basketball_touch(), bot_cmd_eval(), CheatImpulse(), ClientCommand_kill(), CommonCommand_editmob(), CopyBody(), cpicon_draw(), cpicon_send(), ctf_CheckFlagReturn(), ctf_FlagcarrierWaypoints(), ctf_Handle_Drop(), Damage(), destructible_heal(), dompointtouch(), door_damage(), door_reset(), door_trigger_touch(), Draw_ShowNames(), Draw_ShowNames_All(), football_touch(), formatmessage(), frag_centermessage_override(), freezetag_count_alive_players(), freezetag_LastPlayerForTeam(), generator_draw(), generator_send(), GENERIC_COMMAND(), GiveRandomWeapons(), GiveResource(), GiveResourceValue(), GiveResourceWithLimit(), GrapplingHook_Damage(), havocbot_goalrating_ctf_enemyflag(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_ft_freeplayers(), havocbot_goalrating_item_can_be_left_to_teammate(), havocbot_movetogoal(), healtharmor_pickupevalfunc(), instagib_ammocheck(), instagib_countdown(), Invasion_CheckWinner(), Item_GiveAmmoTo(), LinkDoors(), MapVote_Tick(), Monster_Attack_Leap_Check(), Monster_Damage(), Monster_Dead_Damage(), Monster_Frozen_Think(), Monster_Heal(), Monster_Move_Target(), Monster_Spawn_Setup(), Monster_Think(), Monster_ValidTarget(), MUTATOR_HOOKFUNCTION(), navigation_routerating(), NET_HANDLE(), Obituary(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Heal(), ons_ControlPoint_Icon_Spawn(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_UpdateSprite(), ons_GeneratorDamage(), ons_GeneratorHeal(), ons_GeneratorReset(), ons_GeneratorSetup(), Onslaught_count_generators(), plat_center_touch(), plat_outside_touch(), player_regen(), PlayerCorpseDamage(), PlayerDamage(), PlayerHeal(), PlayerHealth(), PlayerPostThink(), PlayerPreThink(), Portal_Damage(), powerups_DropItem_Think(), PutObserverInServer(), readplayerstartcvars(), RotRegen(), spawnfunc(), SpectateCopy(), TakeResource(), TakeResourceWithLimit(), target_objective_spawn_evalfunc(), test_weapons_hurt(), turret_draw(), vehicles_damage(), vehicles_heal(), vehicles_painframe(), vehicles_projectile_damage(), vehicles_regen(), vehicles_regen_resource(), W_DecreaseAmmo(), W_Reload(), W_ReloadedAndReady(), W_ThrowNewWeapon(), W_WeaponFrame(), and weapon_defaultspawnfunc().
 {
     return e.(GetResourceField(res_type));
 }
GetResourceLimit()
float GetResourceLimit (entity e, Resource res_type)
Returns the maximum amount of the given resource.
Parameters
[in] e Entity to check.
[in] res_type Type of the resource (a RES_* constant).
Returns
Maximum amount of the given resource.
Definition at line 12 of file sv_resources.qc.
References autocvar_g_balance_armor_limit, autocvar_g_balance_fuel_limit, autocvar_g_balance_health_limit, error(), g_pickup_cells_max, g_pickup_nails_max, g_pickup_plasma_max, g_pickup_rockets_max, g_pickup_shells_max, GetResourceLimit(), IS_PLAYER, M_ARGV, MUTATOR_CALLHOOK, RES_AMOUNT_HARD_LIMIT, RES_HEALTH, and RES_LIMIT_NONE.
Referenced by GetResourceLimit(), RotRegen(), and SetResource().
 {
     if(!IS_PLAYER(e))
         return RES_LIMIT_NONE; // no limits on non-players
     float limit;
     // TODO: registry handles
     switch (res_type)
     {
         case RES_HEALTH:
         {
             limit = autocvar_g_balance_health_limit;
             break;
         }
         case RES_ARMOR:
         {
             limit = autocvar_g_balance_armor_limit;
             break;
         }
         case RES_SHELLS:
         {
             limit = g_pickup_shells_max;
             break;
         }
         case RES_BULLETS:
         {
             limit = g_pickup_nails_max;
             break;
         }
         case RES_ROCKETS:
         {
             limit = g_pickup_rockets_max;
             break;
         }
         case RES_CELLS:
         {
             limit = g_pickup_cells_max;
             break;
         }
         case RES_PLASMA:
         {
             limit = g_pickup_plasma_max;
             break;
         }
         case RES_FUEL:
         {
             limit = autocvar_g_balance_fuel_limit;
             break;
         }
         default:
         {
             error("GetResourceLimit: Invalid resource type.");
             return 0;
         }
     }
     MUTATOR_CALLHOOK(GetResourceLimit, e, res_type, limit);
     limit = M_ARGV(2, float);
     if (limit > RES_AMOUNT_HARD_LIMIT)
     {
         limit = RES_AMOUNT_HARD_LIMIT;
     }
     return limit;
 }
GiveResource()
void GiveResource (entity receiver, Resource res_type, float amount)
Gives an entity some resource.
Parameters
[in,out] receiver Entity to give resource to.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to give.
Returns
No return.
Definition at line 120 of file sv_resources.qc.
References autocvar_g_balance_pause_armor_rot, autocvar_g_balance_pause_fuel_rot, autocvar_g_balance_pause_health_rot, entity(), GetResource(), GiveResource(), M_ARGV, max(), MUTATOR_CALLHOOK, RES_HEALTH, SetResource(), and time.
Referenced by GiveRandomWeapons(), GiveResource(), GiveResourceWithLimit(), Monster_Miniboss_Check(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), ons_ControlPoint_Icon_BuildThink(), and W_ThrowNewWeapon().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResource, receiver, res_type, amount);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, entity);
     amount = M_ARGV(2, float);
     if (amount <= 0)
     {
         return;
     }
     SetResource(receiver, res_type, GetResource(receiver, res_type) + amount);
     // TODO: registry handles
     switch (res_type)
     {
         case RES_HEALTH:
         {
             receiver.pauserothealth_finished =
                 max(receiver.pauserothealth_finished, time +
                 autocvar_g_balance_pause_health_rot);
             return;
         }
         case RES_ARMOR:
         {
             receiver.pauserotarmor_finished =
                 max(receiver.pauserotarmor_finished, time +
                 autocvar_g_balance_pause_armor_rot);
             return;
         }
         case RES_FUEL:
         {
             receiver.pauserotfuel_finished = max(receiver.pauserotfuel_finished,
                 time + autocvar_g_balance_pause_fuel_rot);
             return;
         }
     }
 }
GiveResourceWithLimit()
void GiveResourceWithLimit (entity receiver, Resource res_type, float amount, float limit)
Gives an entity some resource but not more than a limit.
Parameters
[in,out] receiver Entity to give resource to.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to give.
[in] limit Limit of resources to give.
Returns
No return.
Definition at line 164 of file sv_resources.qc.
References entity(), GetResource(), GiveResource(), GiveResourceWithLimit(), M_ARGV, MUTATOR_CALLHOOK, and RES_LIMIT_NONE.
Referenced by destructible_heal(), GiveResourceWithLimit(), Item_GiveAmmoTo(), Monster_Heal(), ons_ControlPoint_Icon_Heal(), ons_ControlPoint_Icon_Think(), ons_GeneratorHeal(), PlayerHeal(), and vehicles_heal().
 {
     if (amount <= 0)
     {
         return;
     }
     bool forbid = MUTATOR_CALLHOOK(GiveResourceWithLimit, receiver, res_type, amount, limit);
     if (forbid)
     {
         return;
     }
     res_type = M_ARGV(1, entity);
     amount = M_ARGV(2, float);
     limit = M_ARGV(3, float);
     if (amount <= 0)
     {
         return;
     }
     float current_amount = GetResource(receiver, res_type);
     if (current_amount + amount > limit && limit != RES_LIMIT_NONE)
     {
         amount = limit - current_amount;
     }
     GiveResource(receiver, res_type, amount);
 }
SetResource()
void SetResource (entity e, Resource res_type, float amount)
Sets the current amount of resource the given entity will have but limited to the max amount allowed for the resource type.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
No return.
Sets the current amount of resource the given entity will have but limited to the max amount allowed for the resource type.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
No return.
Definition at line 26 of file cl_resources.qc.
References entity(), GetResourceLimit(), M_ARGV, MUTATOR_CALLHOOK, RES_LIMIT_NONE, and SetResourceExplicit().
Referenced by CheatImpulse(), Damage(), Freeze(), GENERIC_COMMAND(), GiveResource(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), RotRegen(), TakeResource(), target_init_use(), Unfreeze(), vehicles_regen_resource(), W_DecreaseAmmo(), W_ReloadedAndReady(), W_ThrowNewWeapon(), and weapon_defaultspawnfunc().
 {
     SetResourceExplicit(e, res_type, amount);
 }
SetResourceExplicit()
bool SetResourceExplicit (entity e, Resource res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
Boolean for whether the ammo amount was changed
Definition at line 15 of file cl_resources.qc.
Referenced by assault_objective_decrease_use(), assault_objective_reset(), assault_objective_use(), CheatCommand(), CopyBody(), ctf_FlagDamage(), ctf_FlagSetup(), ctf_FlagThink(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_RespawnFlag(), Damage(), door_damage(), door_go_down(), Draw_ShowNames_All(), FireGrapplingHook(), FixIntermissionClient(), ft_RemovePlayer(), GiveResourceValue(), LinkDoors(), MapVote_Tick(), Monster_Dead_Fade(), Monster_Frozen_Think(), Monster_Reset(), Monster_Spawn_Setup(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Spawn(), ons_GeneratorReset(), ons_GeneratorSetup(), PlayerPreThink(), Portal_Spawn(), Portal_TeleportPlayer(), powerups_DropItem(), PutObserverInServer(), SetResource(), spawnfunc(), SpectateCopy(), turret_construct(), and vehicles_projectile().
 {
     .float res_field = GetResourceField(res_type);
     if (e.(res_field) != amount)
     {
         e.(res_field) = amount;
         return true;
     }
     return false;
 }
TakeResource()
void TakeResource (entity receiver, Resource res_type, float amount)
Takes an entity some resource.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
Returns
No return.
Definition at line 31 of file cl_resources.qc.
References entity(), GetResource(), M_ARGV, MUTATOR_CALLHOOK, and SetResource().
Referenced by assault_objective_decrease_use(), ctf_FlagDamage(), ctf_FlagThink(), door_damage(), GrapplingHook_Damage(), Monster_Damage(), Monster_Dead_Damage(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Icon_Damage(), ons_GeneratorDamage(), PlayerCorpseDamage(), PlayerDamage(), PM_jetpack(), Portal_Damage(), powerups_DropItem_Think(), TakeResourceWithLimit(), vehicles_damage(), and vehicles_projectile_damage().
 {
     if (amount == 0)
     {
         return;
     }
     SetResource(receiver, res_type, GetResource(receiver, res_type) - amount);
 }
TakeResourceWithLimit()
void TakeResourceWithLimit (entity receiver, Resource res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
[in] limit Limit of resources to take.
Returns
No return.
Definition at line 40 of file cl_resources.qc.
References entity(), GetResource(), M_ARGV, MUTATOR_CALLHOOK, and TakeResource().
Referenced by Item_GiveAmmoTo().
 {
     if (amount == 0)
     {
         return;
     }
     float current_amount = GetResource(receiver, res_type);
     if (current_amount - amount < limit)
     {
         amount = limit + current_amount;
     }
     TakeResource(receiver, res_type, amount);
 }
Variable Documentation
autocvar_g_balance_armor_limit
int autocvar_g_balance_armor_limit
Definition at line 12 of file sv_resources.qh.
Referenced by GetResourceLimit().
autocvar_g_balance_armor_regen
float autocvar_g_balance_armor_regen
Definition at line 14 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_armor_regenlinear
float autocvar_g_balance_armor_regenlinear
Definition at line 15 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_armor_regenstable
int autocvar_g_balance_armor_regenstable
Definition at line 16 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_armor_rot
float autocvar_g_balance_armor_rot
Definition at line 17 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_armor_rotlinear
float autocvar_g_balance_armor_rotlinear
Definition at line 18 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_armor_rotstable
int autocvar_g_balance_armor_rotstable
Definition at line 19 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_limit
float autocvar_g_balance_fuel_limit
Definition at line 13 of file sv_resources.qh.
Referenced by GetResourceLimit().
autocvar_g_balance_fuel_regen
float autocvar_g_balance_fuel_regen
Definition at line 20 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_regenlinear
float autocvar_g_balance_fuel_regenlinear
Definition at line 21 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_regenstable
int autocvar_g_balance_fuel_regenstable
Definition at line 22 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_rot
float autocvar_g_balance_fuel_rot
Definition at line 23 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_rotlinear
float autocvar_g_balance_fuel_rotlinear
Definition at line 24 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_fuel_rotstable
int autocvar_g_balance_fuel_rotstable
Definition at line 25 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_health_limit
float autocvar_g_balance_health_limit
Definition at line 11 of file sv_resources.qh.
Referenced by GetResourceLimit().
autocvar_g_balance_health_regen
float autocvar_g_balance_health_regen
Definition at line 26 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_health_regenlinear
float autocvar_g_balance_health_regenlinear
Definition at line 27 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_health_regenstable
float autocvar_g_balance_health_regenstable
Definition at line 28 of file sv_resources.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and player_regen().
autocvar_g_balance_health_rot
float autocvar_g_balance_health_rot
Definition at line 29 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_health_rotlinear
float autocvar_g_balance_health_rotlinear
Definition at line 30 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_health_rotstable
float autocvar_g_balance_health_rotstable
Definition at line 31 of file sv_resources.qh.
Referenced by player_regen().
autocvar_g_balance_pause_armor_rot
float autocvar_g_balance_pause_armor_rot
Definition at line 32 of file sv_resources.qh.
Referenced by GiveItems(), GiveResource(), and target_init_use().
autocvar_g_balance_pause_fuel_regen
float autocvar_g_balance_pause_fuel_regen
Definition at line 33 of file sv_resources.qh.
Referenced by GiveItems(), and PM_jetpack().
autocvar_g_balance_pause_fuel_rot
float autocvar_g_balance_pause_fuel_rot
Definition at line 34 of file sv_resources.qh.
Referenced by GiveItems(), and GiveResource().
autocvar_g_balance_pause_health_regen
float autocvar_g_balance_pause_health_regen
Definition at line 35 of file sv_resources.qh.
Referenced by GiveItems(), PlayerCorpseDamage(), PlayerDamage(), target_init_use(), and Unfreeze().
autocvar_g_balance_pause_health_rot
float autocvar_g_balance_pause_health_rot
Definition at line 36 of file sv_resources.qh.
Referenced by GiveItems(), GiveResource(), and target_init_use().