Xonotic: menu/xonotic/weaponslist.qh File Reference
weaponslist.qh File Reference
#include "listbox.qh"
Functions
METHOD (XonoticWeaponsList, configureXonoticWeaponsList, void(entity))
METHOD (XonoticWeaponsList, toString, string(entity))
METHOD (XonoticWeaponsList, draw, void(entity))
METHOD (XonoticWeaponsList, drawListBoxItem, void(entity, int, vector, bool, bool))
METHOD (XonoticWeaponsList, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticWeaponsList, keyDown, float(entity, float, float, float))
METHOD (XonoticWeaponsList, mouseDrag, float(entity, vector))
entity makeXonoticWeaponsList ()
void WeaponsList_MoveUp_Click (entity btn, entity me)
void WeaponsList_MoveDown_Click (entity box, entity me)
Function Documentation
entity makeXonoticWeaponsList ()
Definition at line 7 of file weaponslist.qc.
References entity(), me, and NEW.
Referenced by XonoticGameWeaponsSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticWeaponsList);
     me.configureXonoticWeaponsList(me);
     return me;
 }
METHOD (XonoticWeaponsList , configureXonoticWeaponsList , void(entity))
METHOD (XonoticWeaponsList , toString , string(entity))
METHOD (XonoticWeaponsList , draw , void(entity))
METHOD (XonoticWeaponsList , drawListBoxItem , void(entity, int, vector, bool, bool))
METHOD (XonoticWeaponsList , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticWeaponsList , keyDown , float(entity, float, float, float))
METHOD (XonoticWeaponsList , mouseDrag , float(entity, vector))
void WeaponsList_MoveDown_Click (entity box, entity me)
Definition at line 37 of file weaponslist.qc.
References cvar_set, cvar_string(), and swapInPriorityList().
Referenced by XonoticGameWeaponsSettingsTab_fill(), and XonoticWeaponsList_keyDown().
 {
     if(me.selectedItem < me.nItems - 1)
     {
         cvar_set("cl_weaponpriority", swapInPriorityList(cvar_string("cl_weaponpriority"), me.selectedItem, me.selectedItem + 1));
         me.setSelected(me, me.selectedItem + 1);
     }
 }
void WeaponsList_MoveUp_Click (entity btn, entity me)
Definition at line 29 of file weaponslist.qc.
References cvar_set, cvar_string(), and swapInPriorityList().
Referenced by XonoticGameWeaponsSettingsTab_fill(), and XonoticWeaponsList_keyDown().
 {
     if(me.selectedItem > 0)
     {
         cvar_set("cl_weaponpriority", swapInPriorityList(cvar_string("cl_weaponpriority"), me.selectedItem - 1, me.selectedItem));
         me.setSelected(me, me.selectedItem - 1);
     }
 }