Xonotic: common/mutators/mutator/damagetext/sv_damagetext.qc File Reference
sv_damagetext.qc File Reference
#include "sv_damagetext.qh"
Macros
#define SV_DAMAGETEXT_ALL() (autocvar_sv_damagetext >= 3)
#define SV_DAMAGETEXT_DISABLED() (autocvar_sv_damagetext <= 0)
#define SV_DAMAGETEXT_PLAYERS() (autocvar_sv_damagetext >= 2)
#define SV_DAMAGETEXT_SPECTATORS_ONLY() (autocvar_sv_damagetext >= 1)
Functions
AUTOCVAR (sv_damagetext, int, 2, "<= 0: disabled, >= 1: visible to spectators, >= 2: visible to attacker, >= 3: all players see everyone's damage")
MUTATOR_HOOKFUNCTION (damagetext, PlayerDamaged)
REGISTER_MUTATOR (damagetext, true)
bool write_damagetext (entity this, entity client, int sf)
Variables
float dent_net_armor
float dent_net_deathtype
int dent_net_flags
float dent_net_health
float dent_net_potential
Macro Definition Documentation
SV_DAMAGETEXT_ALL
#define SV_DAMAGETEXT_ALL () (autocvar_sv_damagetext >= 3)
Definition at line 10 of file sv_damagetext.qc.
Referenced by write_damagetext().
SV_DAMAGETEXT_DISABLED
#define SV_DAMAGETEXT_DISABLED () (autocvar_sv_damagetext <= 0)
Definition at line 7 of file sv_damagetext.qc.
Referenced by MUTATOR_HOOKFUNCTION().
SV_DAMAGETEXT_PLAYERS
#define SV_DAMAGETEXT_PLAYERS () (autocvar_sv_damagetext >= 2)
Definition at line 9 of file sv_damagetext.qc.
Referenced by write_damagetext().
SV_DAMAGETEXT_SPECTATORS_ONLY
#define SV_DAMAGETEXT_SPECTATORS_ONLY () (autocvar_sv_damagetext >= 1)
Definition at line 8 of file sv_damagetext.qc.
Referenced by write_damagetext().
Function Documentation
AUTOCVAR()
AUTOCVAR (sv_damagetext , int , 2 , "<= 0: disabled, >=1:visible to spectators, >=2:visible to attacker, >=3:all players see everyone 's damage")
MUTATOR_HOOKFUNCTION()
MUTATOR_HOOKFUNCTION (damagetext , PlayerDamaged)
Definition at line 57 of file sv_damagetext.qc.
References almost_equals_eps(), DAMAGETEXT_SHORT_LIMIT, DEATH_WEAPONOF, DTFLAG_BIG_ARMOR, DTFLAG_BIG_HEALTH, DTFLAG_BIG_POTENTIAL, DTFLAG_NO_ARMOR, DTFLAG_NO_POTENTIAL, DTFLAG_SAMETEAM, entity(), flags, health, M_ARGV, new_pure, SAME_TEAM, setthink, SV_DAMAGETEXT_DISABLED, time, and write_damagetext().
{
     if (SV_DAMAGETEXT_DISABLED()) return;
     entity attacker = M_ARGV(0, entity);
     entity hit = M_ARGV(1, entity); if (hit == attacker) return;
     float health = M_ARGV(2, float);
     float armor = M_ARGV(3, float);
     int deathtype = M_ARGV(5, int);
     float potential_damage = M_ARGV(6, float);
     if(DEATH_WEAPONOF(deathtype) == WEP_VAPORIZER) return;
     if(deathtype == DEATH_FIRE.m_id || deathtype == DEATH_BUFF.m_id) return; // TODO: exclude damage over time and thorn effects
     int flags = 0;
     if (SAME_TEAM(hit, attacker)) flags |= DTFLAG_SAMETEAM;
     if (health >= DAMAGETEXT_SHORT_LIMIT) flags |= DTFLAG_BIG_HEALTH;
     if (armor >= DAMAGETEXT_SHORT_LIMIT) flags |= DTFLAG_BIG_ARMOR;
     if (potential_damage >= DAMAGETEXT_SHORT_LIMIT) flags |= DTFLAG_BIG_POTENTIAL;
     if (!armor) flags |= DTFLAG_NO_ARMOR;
     if (almost_equals_eps(armor + health, potential_damage, 5)) flags |= DTFLAG_NO_POTENTIAL;
     entity net_text = new_pure(net_damagetext);
     net_text.realowner = attacker;
     net_text.enemy = hit;
     net_text.dent_net_flags = flags;
     net_text.dent_net_deathtype = deathtype;
     net_text.dent_net_health = health;
     net_text.dent_net_armor = armor;
     net_text.dent_net_potential = potential_damage;
     setthink(net_text, SUB_Remove);
     net_text.nextthink = (time > 10) ? (time + 0.5) : 10; // allow a buffer from start time for clients to load in
     Net_LinkEntity(net_text, false, 0, write_damagetext);
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (damagetext , true)
write_damagetext()
bool write_damagetext (entity this, entity client, int sf)
Definition at line 18 of file sv_damagetext.qc.
References DAMAGETEXT_PRECISION_MULTIPLIER, dent_net_armor, dent_net_deathtype, dent_net_flags, dent_net_health, dent_net_potential, DTFLAG_BIG_ARMOR, DTFLAG_BIG_HEALTH, DTFLAG_BIG_POTENTIAL, DTFLAG_NO_ARMOR, DTFLAG_NO_POTENTIAL, enemy, entity(), etof(), flags, health, IS_OBSERVER, IS_SPEC, realowner, SV_DAMAGETEXT_ALL, SV_DAMAGETEXT_PLAYERS, SV_DAMAGETEXT_SPECTATORS_ONLY, WriteByte(), and WriteShort().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity attacker = this.realowner;
     entity hit = this.enemy;
     int flags = this.dent_net_flags;
     int deathtype = this.dent_net_deathtype;
     float health = this.dent_net_health;
     float armor = this.dent_net_armor;
     float potential_damage = this.dent_net_potential;
     if (!(
         (SV_DAMAGETEXT_ALL()) ||
         (SV_DAMAGETEXT_PLAYERS() && client == attacker) ||
         (SV_DAMAGETEXT_SPECTATORS_ONLY() && IS_SPEC(client) && client.enemy == attacker) ||
         (SV_DAMAGETEXT_SPECTATORS_ONLY() && IS_OBSERVER(client))
     )) return false;
     WriteHeader(MSG_ENTITY, damagetext);
     WriteByte(MSG_ENTITY, etof(hit));
     WriteInt24_t(MSG_ENTITY, deathtype);
     WriteByte(MSG_ENTITY, flags);
     // we need to send a few decimal places to minimize errors when accumulating damage
     // sending them multiplied saves bandwidth compared to using WriteCoord,
     // however if the multiplied damage would be too much for (signed) short, we send an int24
     if (flags & DTFLAG_BIG_HEALTH) WriteInt24_t(MSG_ENTITY, health * DAMAGETEXT_PRECISION_MULTIPLIER);
     else WriteShort(MSG_ENTITY, health * DAMAGETEXT_PRECISION_MULTIPLIER);
     if (!(flags & DTFLAG_NO_ARMOR))
     {
         if (flags & DTFLAG_BIG_ARMOR) WriteInt24_t(MSG_ENTITY, armor * DAMAGETEXT_PRECISION_MULTIPLIER);
         else WriteShort(MSG_ENTITY, armor * DAMAGETEXT_PRECISION_MULTIPLIER);
     }
     if (!(flags & DTFLAG_NO_POTENTIAL))
     {
         if (flags & DTFLAG_BIG_POTENTIAL) WriteInt24_t(MSG_ENTITY, potential_damage * DAMAGETEXT_PRECISION_MULTIPLIER);
         else WriteShort(MSG_ENTITY, potential_damage * DAMAGETEXT_PRECISION_MULTIPLIER);
     }
     return true;
 }
Variable Documentation
dent_net_armor
float dent_net_armor
Definition at line 15 of file sv_damagetext.qc.
Referenced by write_damagetext().
dent_net_deathtype
float dent_net_deathtype
Definition at line 13 of file sv_damagetext.qc.
Referenced by write_damagetext().
dent_net_flags
int dent_net_flags
Definition at line 12 of file sv_damagetext.qc.
Referenced by write_damagetext().
dent_net_health
float dent_net_health
Definition at line 14 of file sv_damagetext.qc.
Referenced by write_damagetext().
dent_net_potential
float dent_net_potential
Definition at line 16 of file sv_damagetext.qc.
Referenced by write_damagetext().