Xonotic: common/effects/effectinfo.qc File Reference
effectinfo.qc File Reference
#include "effectinfo.inc"
Macros
#define EFFECTINFO_PARSER(on, MY)
#define FIELDS(MY)
#define MY(f, type, val) ATTRIB(EffectInfo, effectinfo_##f, type, val)
#define str_bool(it) (it ? "true" : "false")
#define str_float(it) ftos(it)
#define str_vector(it) vtos(it)
#define str_string(it) strcat("\"", it, "\"")
#define p(f, type, default) if (this.effectinfo_##f) { s = strcat(s, "\t", "MY("#f") = ", str_##type(this.effectinfo_##f), ";\n"); }
#define MY(f) this.effectinfo_##f
#define p(k, isset, parse, unparse) if (isset) { s = strcat(s, "\t", #k, unparse, "\n"); }
#define MY(f) info.effectinfo_##f
#define p(k, isset, parse, unparse) case #k: parse break;
#define WRITE(s)
#define EffectInfos_from(i) _EffectInfos_from(i, NULL)
#define EFFECTINFO(name)
#define MY(f) this.effectinfo_##f
#define DEF(name) EFFECTINFO(name)
#define SUB(name)
Functions
CONSTRUCTOR (EffectInfo, string s)
return strcat (s,"}\n")
void effectinfo_read ()
void effectinfo_dump (int fh, bool alsoprint)
GENERIC_COMMAND (dumpeffectinfo,"Dump all effectinfo to effectinfo_dump.txt")
Variables
string s = sprintf("SUB(%s) {\n", this.effectinfo_name)
Macro Definition Documentation
#define DEF (name) EFFECTINFO(name)
Definition at line 335 of file effectinfo.qc.
#define EFFECTINFO (name)
Value:
[[accumulate]] void effectinfo_##name(EffectInfoGroup parent, EffectInfo this) { } \
    REGISTER(EffectInfos, EFFECTINFO, name, m_id, NEW(EffectInfoGroup)) { \
        effectinfo_##name(this, NULL); \
    }
Definition at line 328 of file effectinfo.qc.
#define EFFECTINFO_PARSER (on, MY)
Definition at line 1 of file effectinfo.qc.
Referenced by effectinfo_read().
#define EffectInfos_from (i) _EffectInfos_from(i, NULL)
Definition at line 326 of file effectinfo.qc.
#define FIELDS (MY)
Definition at line 147 of file effectinfo.qc.
#define MY (f, type, val) ATTRIB(EffectInfo, effectinfo_##f, type, val)
Definition at line 334 of file effectinfo.qc.
Referenced by effectinfo_read(), and SUB().
#define MY (f) this.effectinfo_##f
Definition at line 334 of file effectinfo.qc.
#define MY (f) info.effectinfo_##f
Definition at line 334 of file effectinfo.qc.
#define MY (f) this.effectinfo_##f
Definition at line 334 of file effectinfo.qc.
#define p (f, type, default) if (this.effectinfo_##f) { s = strcat(s, "\t", "MY("#f") = ", str_##type(this.effectinfo_##f), ";\n"); }
Definition at line 219 of file effectinfo.qc.
Referenced by _MapInfo_Map_ApplyGametypeEx(), bot_getplace(), c4_winning_piece(), cliptoplane(), compressShortVector(), Container_moveItemAfter(), Container_removeItem(), CTX(), cvar_string_campaignwrapper(), decompressShortVector(), effectinfo_read(), end_minigame(), findperpendicular(), formatmessage(), GameCommand_trace(), getrankings(), HUD_DrawScoreboardRankings(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), HUD_Mod_NexBall(), InputBox_draw(), InputBox_mouseDrag(), InstantAction_LoadMap(), m_keydown(), m_tooltip(), makevectors_matrix(), MapInfo_Get_ByName_NoFallbacks(), minigame_rmplayer(), navigation_markroutes(), navigation_markroutes_inverted(), NET_HANDLE(), PlayerScore_SendEntity(), PlayerScore_Sort(), Porto_Draw(), race_ClearRecords(), Score_NicePrint(), Simple_TeleportPlayer(), skeleton_markbones(), solve_cubic_abcd(), solve_cubic_pq(), steerlib_beamsteer(), TeamScore_SendEntity(), tile_check_cross(), tile_check_plus(), tile_check_plus2(), trigger_race_checkpoint_verify(), UpdateConWidthHeight(), VoteCommand_checkargs(), WarpZone_FindRadius_Recurse(), and XonoticLanguageList_drawListBoxItem().
#define p (k, isset, parse, unparse) if (isset) { s = strcat(s, "\t", #k, unparse, "\n"); }
Definition at line 219 of file effectinfo.qc.
#define p (k, isset, parse, unparse) case #k: parse break;
Definition at line 219 of file effectinfo.qc.
#define str_bool (it) (it ? "true" : "false")
Definition at line 204 of file effectinfo.qc.
#define str_float (it) ftos(it)
Definition at line 205 of file effectinfo.qc.
#define str_string (it) strcat("\"", it, "\"")
Definition at line 207 of file effectinfo.qc.
#define str_vector (it) vtos(it)
Definition at line 206 of file effectinfo.qc.
#define SUB (name)
Value:
[[accumulate]] void effectinfo_##name(EffectInfoGroup parent, EffectInfo this) { parent = EFFECTINFO_##name; parent.children[parent.children_count++] = this = NEW(EffectInfo, #name); } \
    [[accumulate]] void effectinfo_##name(EffectInfoGroup parent, EffectInfo this)
Definition at line 336 of file effectinfo.qc.
#define WRITE (s)
Value:
MACRO_BEGIN { \
        fputs(fh, s); \
        if (alsoprint) LOG_INFO(s); \
    } MACRO_END
Referenced by effectinfo_dump().
Function Documentation
CONSTRUCTOR (EffectInfo , string s)
Definition at line 142 of file effectinfo.qc.
References CONSTRUCT, and s.
{
         CONSTRUCT(EffectInfo);
         this.effectinfo_name = s;
     }
void effectinfo_dump (int fh, bool alsoprint)
Definition at line 263 of file effectinfo.qc.
References findfloat(), NULL, and WRITE.
Referenced by GENERIC_COMMAND().
 {
     #define WRITE(s) MACRO_BEGIN { \
         fputs(fh, s); \
         if (alsoprint) LOG_INFO(s); \
     } MACRO_END
     WRITE("// ********************************************** //\n");
     WRITE("// ** WARNING - DO NOT MANUALLY EDIT THIS FILE ** //\n");
     WRITE("// **                                          ** //\n");
     WRITE("// **  This file is automatically generated by ** //\n");
     WRITE("// **  code with the command 'dumpeffectinfo'. ** //\n");
     WRITE("// **                                          ** //\n");
     WRITE("// **  If you modify an effect, please         ** //\n");
     WRITE("// **  regenerate this file with that command. ** //\n");
     WRITE("// **                                          ** //\n");
     WRITE("// ********************************************** //\n");
     WRITE("\n");
     for (EffectInfo it = NULL; (it = findfloat(it, instanceOfEffectInfo, true)); ) {
         if (it.classname == "vtbl") continue;
         string s = it.dump(it);
         WRITE(s);
     }
     #undef WRITE
 }
void effectinfo_read ()
Definition at line 234 of file effectinfo.qc.
References argv(), demand, EFFECTINFO_PARSER, fclose(), fgets(), FILE_READ, fopen(), LOG_WARNINGF, MY, n, NEW, NULL, p, strzone(), and tokenize_console.
 {
     int fh = fopen("effectinfo.txt", FILE_READ);
     EffectInfo info = NULL;
     for (string line; (line = fgets(fh)); ) {
         int n = tokenize_console(line);
         if (n == 0) continue;
         n--;
         string k = argv(0);
         if (k == "effect") {
             demand(n == 1);
             info = NEW(EffectInfo, strzone(argv(1)));
             continue;
         }
         demand(info != NULL);
         switch (k) {
             #define MY(f) info.effectinfo_##f
             #define p(k, isset, parse, unparse) case #k: parse break;
             EFFECTINFO_PARSER(p, MY)
             #undef p
             #undef MY
             default:
                 LOG_WARNINGF("Unknown property '%s'\n", k);
                 break;
         }
     }
     fclose(fh);
 }
GENERIC_COMMAND (dumpeffectinfo , "Dump all effectinfo to effectinfo_dump.txt")
Definition at line 289 of file effectinfo.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, effectinfo_dump(), fclose(), FILE_WRITE, fopen(), LOG_INFO(), LOG_INFOF(), LOG_WARNINGF, and strcat().
 {
     switch (request) {
         case CMD_REQUEST_COMMAND: {
             string filename = argv(1);
             bool alsoprint = false;
             if (filename == "") {
                 filename = "effectinfo_dump.txt";
                 alsoprint = false;
             } else if (filename == "-") {
                 filename = "effectinfo_dump.txt";
                 alsoprint = true;
             }
             int fh = fopen(filename, FILE_WRITE);
             if (fh >= 0) {
                 effectinfo_dump(fh, alsoprint);
                 LOG_INFOF("Dumping effectinfo... File located at ^2data/data/%s^7.\n", filename);
                 LOG_INFOF("Reload with ^2cl_particles_reloadeffects data/%s^7.\n", filename);
                 fclose(fh);
             } else {
                 LOG_WARNINGF("Could not open file '%s'!\n", filename);
             }
             return;
         }
         default:
         case CMD_REQUEST_USAGE: {
             LOG_INFO(strcat("\nUsage:^3 ", GetProgramCommandPrefix(), " dumpeffectinfo [filename]"));
             LOG_INFO("  Where 'filename' is the file to write (default is effectinfo_dump.txt),\n");
             LOG_INFO("  if supplied with '-' output to console as well as default,\n");
             LOG_INFO("  if left blank, it will only write to default.\n");
             return;
         }
     }
 }
return strcat (s , "}\n")
Referenced by _dumptree_open(), _MapInfo_Generate(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), _Sound_fixpath(), ACCUMULATE_call(), Accuracy_LoadColors(), anticheat_display(), anticheat_report(), AppendItemcodes(), AuditLists(), Ban_Enforce(), Ban_GetClientIP(), Ban_KickBanClient(), Ban_SaveBans(), Ban_View(), bd_load_level(), bd_save_level(), bd_save_piece(), BGMScript_Init(), BGMScript_InitEntity(), bot_cmd_eval(), bot_cmdhelp(), bot_execute_commands_once(), bot_getplace(), bot_list_commands(), bot_relinkplayerlist(), bot_setnameandstuff(), buf_save(), Button_draw(), Campaign_Invalid(), CampaignFile_Load(), CampaignPreInit(), CampaignPreIntermission(), CampaignSaveCvar(), CCR(), CheatCommand(), CheckBox_toString(), checkpoint_passed(), CL_ExteriorWeaponentity_Think(), CL_WeaponEntity_SetModel(), ClientCommand_autoswitch(), ClientCommand_minigame(), ClientCommand_physics(), ClientCommand_sentcvar(), ClientCommand_suggestmap(), ClientCommand_tell(), ClientConnect(), ClientDisconnect(), Cmd_HUD_SetFields(), Cmd_MapVote_MapDownload(), CommonCommand_cvar_changes(), CommonCommand_cvar_purechanges(), CommonCommand_editmob(), CommonCommand_info(), CommonCommand_ladder(), CommonCommand_lsmaps(), CommonCommand_printmaplist(), CommonCommand_rankings(), CommonCommand_records(), CommonCommand_teamstatus(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), cons(), CSQC_Init(), CSQCPlayer_LOD_Apply(), cvar_changes_init(), cvar_set_campaignwrapper(), cvar_string_campaignwrapper(), cvar_string_normal(), CvarList_Revert_Click(), CvarList_Value_Change(), db_dump(), db_save(), DemoList_Filter_Change(), dialog_hudpanel_common_notoggle(), draw_cursor(), draw_teamradar_icon(), draw_UseSkinFor(), drawBackground(), DrawDomItem(), DumpStats(), end_minigame(), FixPlayermodel(), fixPriorityList(), for(), formatmessage(), fstrunzone(), GameCommand(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_bot_cmd(), GameCommand_cointoss(), GameCommand_database(), GameCommand_defer_clear_all(), GameCommand_gettaginfo(), GameCommand_moveplayer(), GameCommand_nospectators(), GameCommand_stuffto(), GameLogEcho(), GameType_GetIcon(), GameTypeVote_AvailabilityStatus(), GameTypeVote_ReadOption(), GameTypeVote_SendOption(), GameTypeVote_Type_FromString(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_addtolist(), GenericCommand_maplist(), GenericCommand_markup(), GenericCommand_nextframe(), GenericCommand_qc_curl(), GenericCommand_removefromlist(), GenericCommand_rpn(), GenericCommand_runtest(), GenericCommand_settemp(), GenericCommand_settemp_restore(), get_model_datafilename(), get_model_parameters(), get_monster_model_datafilename(), getAllHUDSkins(), GetClientErrorString_color(), getcommandkey(), GetCvars_handleFloat(), GetCvars_handleFloatOnce(), GetCvars_handleString(), getDemos_for_ext(), getHUDSkinFiles(), getladder(), getlsmaps(), GetPlayerScoreString(), getrankings(), GetScoreLogLabel(), getScreenshots_for_ext(), GetTeamScoreString(), gettooltip(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), HUD_CenterPrint(), HUD_Chat(), HUD_Crosshair(), HUD_DrawScoreboard(), HUD_GetField(), HUD_InfoMessages(), HUD_Main(), HUD_Minigame_InputEvent(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_Mod_Race(), HUD_mouse_over(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), HUD_Panel_ExportCfg(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), HUD_Radar_InputEvent(), HUD_Score(), HUD_Weapons(), HUDSkinList_Filter_Change(), if(), IMPULSE(), InitializeEntitiesRun(), InputBox_draw(), InputBox_enterText(), InputBox_keyDown(), invite_minigame(), isGametypeInFilter(), item_keys_keylist(), Item_Model(), KeyBinder_Bind_Edit(), language_filename(), ListBox_draw(), LoadMenuSkinValues(), Local_Notification_sprintf(), LocalCommand_create_scrshot_ent(), LocalCommand_handlevote(), LogDeath(), LogTeamchange(), m_init_delayed(), M_Model(), MakeRaceString(), Map_Filename(), Map_MarkAsRecent(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapInfo_LoadMap(), MapList_Add_All(), mapPriorityList(), MapVote_AddVotable(), MapVote_CheckPK3(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_FormatMapItem(), MapVote_InputEvent(), MapVote_ReadOption(), MapVote_SendChoice(), MapVote_SendPicture(), MapVote_Suggest(), markdown(), METHOD(), minigame_addplayer(), minigame_cmd_workaround(), minigame_getWrappedLine(), minigame_rmplayer(), minigame_tile_buildname(), mmsss(), mmssss(), Monster_Sound_Precache(), Monster_Sounds_Load(), Monster_Sounds_Precache(), navigation_goalrating_end(), navigation_poptouchedgoals(), navigation_routerating(), navigation_unstuck(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), Obituary(), OnlineBanList_SendBan(), OnlineBanList_SendUnban(), OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), playerdemo_write(), playerdemo_write_float(), playerdemo_write_modelstring(), playerdemo_write_originvector(), playerdemo_write_sizevector(), playerdemo_write_string(), playerdemo_write_vector(), PlayerJump(), playername(), PlayerPreThink(), PlayerScore_Add(), PlayerScore_PlayerStats(), PlayerScore_TeamStats(), PM_Main(), PM_walk(), prandom(), precache_playermodel(), preMenuDraw(), PreviewExists(), print_to(), Process_Notif_Line(), PutClientInServer(), queue_to_execute_next_frame(), QuickMenu_ActionForNumber(), QuickMenu_Open(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), race_writeTime(), RadarMap_Next(), RadarMap_Think(), readlevelcvars(), readplayerstartcvars(), RedirectionThink(), RestoreGame(), rewrapCampaign(), rgb_to_hexcolor(), Say(), Score_NicePrint_Player(), Score_NicePrint_Spectator(), Score_NicePrint_Team(), ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScoreString(), ScreenshotList_Filter_Change(), ServerList_TypeSort_Click(), Shutdown(), Slider_draw(), spawnfunc(), start_minigame(), STATIC_INIT(), SV_ParseClientCommand(), swapInPriorityList(), swapwords(), target_give_init(), TEST_Run(), textShortenToLength(), textShortenToWidth(), trigger_race_checkpoint_verify(), turret_gibboom(), uid2name(), unescape(), ValidateMap(), Vehicles_drawHUD(), VoteAccept(), VoteCommand(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_checkargs(), VoteCommand_checkinlist(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_no(), VoteCommand_parse(), VoteCommand_status(), VoteCommand_stop(), VoteCommand_yes(), VoteSpam(), VoteStop(), W_FixWeaponOrder_BuildImpulseList(), W_FixWeaponOrder_BuildImpulseList_cmp(), W_HitPlotAnalysis(), W_HitPlotOpen(), W_Model(), W_Reload(), W_Sound(), waypoint_load_links(), waypoint_load_links_hardwired(), waypoint_loadall(), waypoint_save_links(), waypoint_saveall(), WeaponArenaString(), WeaponStats_ready(), WinningConditionHelper(), wordwrap_buffer_put(), wordwrap_buffer_sprint(), wordwrap_sprint(), write_recordmarker(), xencode(), Xonotic_KeyBinds_Read(), XonoticCampaignList_campaignGo(), XonoticCampaignList_drawListBoxItem(), XonoticCampaignList_loadCvars(), XonoticColorpicker_draw(), XonoticColorpickerString_draw(), XonoticColorpickerString_loadCvars(), XonoticColorpickerString_saveCvars(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_configureXonoticCrosshairPreview(), XonoticCrosshairPreview_draw(), XonoticCvarList_updateCvarType(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticHUDSkinList_setHUDSkin(), XonoticHUDWeaponsDialog_fill(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_editUserbind(), XonoticMapInfoDialog_loadMapInfo(), XonoticMapList_drawListBoxItem(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticMutatorsDialog_toString(), XonoticPlayerModelSelector_loadModels(), XonoticPlayList_addToPlayList(), XonoticPlayList_removeSelectedFromPlayList(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_loadCvars(), XonoticScreenshotList_goScreenshot(), XonoticScreenshotList_previewScreenshot(), XonoticScreenshotList_startScreenshot(), XonoticServerList_drawListBoxItem(), XonoticServerList_refreshServerList(), XonoticSkinList_getSkins(), XonoticSoundList_getSounds(), XonoticTextSlider_loadCvars(), XonoticTextSlider_saveCvars(), XonoticWeaponarenaCheckBox_saveCvars(), XonoticWeaponsList_drawListBoxItem(), and XonoticWeaponsList_toString().
Variable Documentation
return s = sprintf("SUB(%s) {\n", this.effectinfo_name)
Definition at line 203 of file effectinfo.qc.
Referenced by _dumptree_open(), _MapInfo_Generate(), _MapInfo_GlobItem(), animdecide_setimplicitstate(), anticheat_display(), AppendItemcodes(), Ban_Enforce(), Ban_GetClientIP(), Ban_IsClientBanned(), Ban_MaybeEnforceBan(), bd_load_piece(), BGMScript_Init(), bot_getplace(), bot_setnameandstuff(), car(), CheckBox_draw(), CLIENT_COMMAND(), ClientCommand_sentcvar(), Cmd_HUD_SetFields(), ColorTranslateRGB(), CONSTRUCTOR(), Container_itemFromPoint(), Container_resizeNotifyLie(), CSQC_ConsoleCommand(), CSQCPlayer_LOD_Apply(), cvar_or(), cvar_set_campaignwrapper(), Dialog_addItemSimple(), draw_SetClipRect(), Draw_ShowNames(), DumpStats(), EndFrame(), FireGrapplingHook(), FixPlayermodel(), fstrunzone(), GameCommand(), GameCommand_bot_cmd(), GameCommand_effectindexdump(), GameCommand_gametype(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_markup(), GenericCommand_rpn(), get_model_parameters(), getAllHUDSkins(), GetAttackDecaySustainAmplitude(), GetCvars(), GetCvars_handleString_Fixup(), getDemos_for_ext(), getHUDSkinFiles(), getladder(), getrankings(), getrecords(), GetReleaseTime(), getScreenshots_for_ext(), gettooltip(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), GrapplingHookThink(), havocbot_movetogoal(), HUD_Configure_DrawGrid(), HUD_DrawScoreboardAccuracyStats(), HUD_InfoMessages(), HUD_Main(), HUD_MinigameMenu_SpawnEntry(), HUD_Mod_Race(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_RaceTimer(), HUD_Score_Rankings(), HUD_Vote(), HUD_Weapons(), InstantAction_LoadMap(), language_filename(), ListBox_draw(), LoadMenuSkinValues(), Local_Notification(), LocalCommand_sendcvar(), LogDeath(), m_init(), m_init_delayed(), m_tooltip(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_Get_ByName_NoFallbacks(), MapList_Add_All(), MapVote_Init(), matchacl(), METHOD(), minigame_getWrappedLine(), mmsss(), mmssss(), Monster_Sound_Precache(), Monster_Sounds_Load(), NET_HANDLE(), pathlib_showsquare(), pathlib_walknode(), player_getspecies(), playerdemo_read_modelstring(), playerdemo_read_string(), PlayerInIDList(), PlayerScore_Add(), PlayerScore_PlayerStats(), Portal_TeleportPlayer(), PutClientInServer(), QuickMenu_Open(), QuickMenu_Page_Load(), QuickMenu_skip_submenu(), race_SendTime(), RandomSelection_Add(), readplayerstartcvars(), rewrapCampaign(), rpn_push(), rpn_set(), saveCvarsMulti(), SaveHUDSkin_Click(), Score_NicePrint_Player(), Score_NicePrint_Team(), setDependent_Check(), shotorg_adjust_values(), skeleton_from_frames(), skeleton_markbones(), spawnfunc(), STATIC_INIT_LATE(), strwords(), SUB_UseTargets(), SV_OnEntityPreSpawnFunction(), swapInPriorityList(), TeamScore_AddToTeam(), TeamScore_GetCompareValue(), Teleport_Touch(), uid2name(), unescape(), UpdateNotification_URI_Get_Callback(), url_fgets(), viewmodel_animate(), W_NameWeaponOrder_MapFunc(), W_NumberWeaponOrder_MapFunc(), W_ThrowNewWeapon(), W_UndeprecateName(), WarpZoneLib_BadEntity(), WarpZoneLib_BoxTouchesBrush(), WarpZoneLib_BoxTouchesBrush_Recurse(), waypoint_load_links(), waypoint_load_links_hardwired(), waypoint_loadall(), waypoint_save_links(), waypoint_saveall(), weapon_defaultspawnfunc(), WeaponArenaString(), WeaponStats_ready(), WinningConditionHelper(), XonoticAudioSettingsTab_fill(), XonoticCampaignList_campaignGo(), XonoticCampaignList_drawListBoxItem(), XonoticCreditsList_drawListBoxItem(), XonoticCrosshairPicker_cellDraw(), XonoticCvarList_drawListBoxItem(), XonoticCvarList_setSelected(), XonoticDemoList_demoName(), XonoticDemoList_drawListBoxItem(), XonoticDemoList_startDemo(), XonoticDemoList_timeDemo(), XonoticEffectsSettingsTab_fill(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticLanguageList_getLanguages(), XonoticLanguageList_loadCvars(), XonoticMapList_drawListBoxItem(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_refilter(), XonoticMutatorsDialog_fill(), XonoticMutatorsDialog_toString(), XonoticPlayerList_drawListBoxItem(), XonoticPlayerList_setPlayerList(), XonoticPlayList_drawListBoxItem(), XonoticPlayList_removeSelectedFromPlayList(), XonoticScreenshotList_drawListBoxItem(), XonoticScreenshotList_screenshotName(), XonoticServerInfoDialog_loadServerInfo(), XonoticSkinList_drawListBoxItem(), XonoticSkinList_getSkins(), XonoticSkinList_loadCvars(), XonoticSoundList_drawListBoxItem(), XonoticSoundList_getSounds(), XonoticSoundList_soundName(), XonoticStatsList_drawListBoxItem(), XonoticTextSlider_loadCvars(), XonoticWeaponsList_draw(), and XonoticWeaponsList_toString().