Xonotic: lib/net.qh File Reference
net.qh File Reference
#include "registry.qh"
#include "sort.qh"
#include "yenc.qh"
Macros
#define NET_HANDLE(id, param) bool Net_Handle_##id(entity this, entity sender, param)
#define REGISTER_NET_TEMP(id)
#define REGISTER_NET_S2C(id) REGISTER_NET_TEMP(id)
#define TempEntities_from(i) _TempEntities_from(i, NULL)
#define REGISTER_NET_LINKED(id)
#define LinkedEntities_from(i) _LinkedEntities_from(i, NULL)
#define REGISTER_NET_C2S(id)
#define C2S_Protocol_from(i) _C2S_Protocol_from(i, NULL)
#define ReadRegistered(r) r##_from(Read_byte())
#define WriteRegistered(r, to, it) Write_byte(to, it.m_id)
#define Read_byte() ReadByte()
#define Write_byte(to, f) WriteByte(to, f)
#define Read_int() ReadInt24_t()
#define Write_int(to, f) WriteInt24_t(to, f)
#define Read_float() ReadFloat()
#define Write_float(to, f) WriteFloat(to, f)
#define Read_string() ReadString()
#define Write_string(to, f) WriteString(to, f)
#define APPROXPASTTIME_MAX (16384 * APPROXPASTTIME_ACCURACY_REQUIREMENT)
#define APPROXPASTTIME_RANGE (64 * APPROXPASTTIME_ACCURACY_REQUIREMENT)
#define WriteFloat(to, f) WriteCoord(to, f)
#define WriteVector(to, v) MACRO_BEGIN { WriteFloat(to, v.x); WriteFloat(to, v.y); WriteFloat(to, v.z); } MACRO_END
#define WriteVector2D(to, v) MACRO_BEGIN { WriteFloat(to, v.x); WriteFloat(to, v.y); } MACRO_END
#define WRITESPECTATABLE_MSG_ONE(to, statement)
Functions
bool (entity this, entity sender, bool isNew) m_read
STATIC_INIT (RegisterTempEntities_renumber)
STATIC_INIT (RegisterLinkedEntities_renumber)
STATIC_INIT (C2S_Protocol_renumber)
void WriteInt24_t (float dst, float val)
void WriteInt48_t (float dst, vector val)
void WriteInt72_t (float dst, vector val)
void WriteApproxPastTime (float dst, float t)
Variables
string netname
int m_id
const float APPROXPASTTIME_ACCURACY_REQUIREMENT = 0.05
Macro Definition Documentation
#define APPROXPASTTIME_MAX (16384 * APPROXPASTTIME_ACCURACY_REQUIREMENT)
Definition at line 252 of file net.qh.
Referenced by WriteApproxPastTime().
#define APPROXPASTTIME_RANGE (64 * APPROXPASTTIME_ACCURACY_REQUIREMENT)
Definition at line 253 of file net.qh.
#define C2S_Protocol_from (i) _C2S_Protocol_from(i, NULL)
Definition at line 89 of file net.qh.
#define LinkedEntities_from (i) _LinkedEntities_from(i, NULL)
Definition at line 63 of file net.qh.
#define NET_HANDLE (id, param) bool Net_Handle_##id(entity this, entity sender, param)
Definition at line 10 of file net.qh.
#define Read_byte () ReadByte()
Definition at line 217 of file net.qh.
#define Read_float () ReadFloat()
Definition at line 244 of file net.qh.
#define Read_int () ReadInt24_t()
Definition at line 241 of file net.qh.
#define Read_string () ReadString()
Definition at line 247 of file net.qh.
#define ReadRegistered (r) r##_from(Read_byte())
Definition at line 214 of file net.qh.
#define REGISTER_NET_C2S (id)
Value:
const bool NET_##id##_istemp = true; \
        REGISTER(C2S_Protocol, NET, id, m_id, new_pure(net_c2s_packet)) \
        { \
            this.netname = #id; \
        }
Definition at line 80 of file net.qh.
#define REGISTER_NET_LINKED (id)
Value:
const bool NET_##id##_istemp = false; \
        REGISTER(LinkedEntities, NET, id, m_id, new_pure(net_linked_packet)) \
        { \
            this.netname = #id; \
        }
Definition at line 54 of file net.qh.
#define REGISTER_NET_S2C (id) REGISTER_NET_TEMP(id)
Definition at line 29 of file net.qh.
#define REGISTER_NET_TEMP (id)
Value:
const bool NET_##id##_istemp = true; \
        REGISTER(TempEntities, NET, id, m_id, new_pure(net_temp_packet)) \
        { \
            this.netname = #id; \
        }
Definition at line 22 of file net.qh.
#define TempEntities_from (i) _TempEntities_from(i, NULL)
Definition at line 32 of file net.qh.
#define Write_byte (to, f) WriteByte(to, f)
Definition at line 218 of file net.qh.
#define Write_float (to, f) WriteFloat(to, f)
Definition at line 245 of file net.qh.
#define Write_int (to, f) WriteInt24_t(to, f)
Definition at line 242 of file net.qh.
#define Write_string (to, f) WriteString(to, f)
Definition at line 248 of file net.qh.
#define WriteFloat (to, f) WriteCoord(to, f)
Definition at line 306 of file net.qh.
#define WriteRegistered (r, to, it) Write_byte(to, it.m_id)
Definition at line 215 of file net.qh.
Referenced by w_whereis().
#define WRITESPECTATABLE_MSG_ONE (to, statement)
Value:
MACRO_BEGIN { \
            entity prev = msg_entity; \
            entity dst = to; \
            FOREACH_CLIENT(IS_REAL_CLIENT(it), { \
                if (it == dst || (it.classname == STR_SPECTATOR && it.enemy == dst)) \
                { \
                    msg_entity = it; \
                    LAMBDA(statement); \
                } \
            }); \
            msg_entity = prev; \
        } MACRO_END
Definition at line 333 of file net.qh.
Referenced by race_ClearTime(), race_ImposePenaltyTime(), race_SendNextCheckpoint(), race_SendStatus(), and race_SendTime().
#define WriteVector (to, v) MACRO_BEGIN { WriteFloat(to, v.x); WriteFloat(to, v.y); WriteFloat(to, v.z); } MACRO_END
Definition at line 307 of file net.qh.
#define WriteVector2D (to, v) MACRO_BEGIN { WriteFloat(to, v.x); WriteFloat(to, v.y); } MACRO_END
Definition at line 308 of file net.qh.
Function Documentation
bool (entity this, entity sender, bool isNew)
STATIC_INIT (RegisterTempEntities_renumber)
Definition at line 36 of file net.qh.
References FOREACH.
 { FOREACH(TempEntities, true, it.m_id = 80 + i); }
STATIC_INIT (RegisterLinkedEntities_renumber)
Definition at line 67 of file net.qh.
References FOREACH.
 { FOREACH(LinkedEntities, true, it.m_id = 1 + i); }
STATIC_INIT (C2S_Protocol_renumber)
Definition at line 93 of file net.qh.
References FOREACH.
 { FOREACH(C2S_Protocol, true, it.m_id = i); }
void WriteApproxPastTime (float dst, float t)
Definition at line 315 of file net.qh.
References APPROXPASTTIME_MAX, bound(), rint(), time, and WriteByte().
         {
             float dt = time - t;
             // warning: this is approximate; do not resend when you don't have to!
             // be careful with sendflags here!
             // we want: 0 -> 0.05, 1 -> 0.1, ..., 255 -> 12.75
             // map to range...
             dt = 256 * (dt / ((APPROXPASTTIME_MAX / 256) + dt));
             // round...
             dt = rint(bound(0, dt, 255));
             WriteByte(dst, dt);
         }
void WriteInt24_t (float dst, float val)
Definition at line 288 of file net.qh.
References floor(), WriteByte(), and WriteShort().
Referenced by accuracy_send(), ClientInit_misc(), CSQCModel_Send(), PlayerScore_SendEntity(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendNextCheckpoint(), race_SendRankings(), race_SendTime(), ScoreInfo_SendEntity(), TeamScore_SendEntity(), WriteInt48_t(), and WriteInt72_t().
         {
             float v;
             WriteShort(dst, (v = floor(val >> 8)));
             WriteByte(dst, val - (v << 8));  // 0..255
         }
void WriteInt48_t (float dst, vector val)
Definition at line 294 of file net.qh.
References WriteInt24_t().
         {
             WriteInt24_t(dst, val.x);
             WriteInt24_t(dst, val.y);
         }
void WriteInt72_t (float dst, vector val)
Definition at line 299 of file net.qh.
References WriteInt24_t().
         {
             WriteInt24_t(dst, val.x);
             WriteInt24_t(dst, val.y);
             WriteInt24_t(dst, val.z);
         }
Variable Documentation
const float APPROXPASTTIME_ACCURACY_REQUIREMENT = 0.05
Definition at line 251 of file net.qh.
int m_id
Definition at line 8 of file net.qh.
string netname
Definition at line 7 of file net.qh.