Xonotic: common/mapinfo.qh File Reference
mapinfo.qh File Reference
#include "util.qh"
Classes
class Assault
class CaptureTheFlag
class ClanArena
class Deathmatch
class Domination
class Duel
class FreezeTag
class Gametype
class Invasion
class Keepaway
class KeyHunt
class LastManStanding
class NexBall
class Onslaught
class Race
class RaceCTS
class TeamDeathmatch
Macros
#define g_assault IS_GAMETYPE(ASSAULT)
#define g_ca IS_GAMETYPE(CA)
#define g_ctf IS_GAMETYPE(CTF)
#define g_cts IS_GAMETYPE(CTS)
#define g_duel IS_GAMETYPE(DUEL)
#define g_freezetag IS_GAMETYPE(FREEZETAG)
#define g_nexball IS_GAMETYPE(NEXBALL)
#define g_race IS_GAMETYPE(RACE)
#define g_tdm IS_GAMETYPE(TEAM_DEATHMATCH)
#define Gametypes_from(i) _Gametypes_from(i, NULL)
#define IS_GAMETYPE(NAME) (MapInfo_LoadedGametype == MAPINFO_TYPE_##NAME)
#define MAPINFO_SETTEMP_ACL_SYSTEM "-g_mapinfo_* -rcon_* -_* -g_ban* -r_water +*"
#define MAPINFO_SETTEMP_ACL_USER cvar_string("g_mapinfo_settemp_acl")
#define REGISTER_GAMETYPE(NAME, inst) REGISTER(Gametypes, MAPINFO_TYPE, NAME, m_id, inst)
Functions
float _MapInfo_FilterGametype (int gametypeFlags, float features, float pFlagsRequired, float pFlagsForbidden, float pAbortOnGenerate)
string _MapInfo_GetDefaultEx (Gametype t)
float _MapInfo_GetTeamPlayBool (Gametype t)
void _MapInfo_Parse_Settemp (string pFilename, string acl, float type, string s, float recurse)
string MapInfo_BSPName_ByID (float i)
void MapInfo_Cache_Create ()
void MapInfo_Cache_Destroy ()
void MapInfo_Cache_Invalidate ()
float MapInfo_CheckMap (string s)
void MapInfo_ClearTemps ()
int MapInfo_CurrentFeatures ()
Gametype MapInfo_CurrentGametype ()
void MapInfo_Enumerate ()
float MapInfo_FilterGametype (Gametype gametypeFlags, float features, float pFlagsRequired, float pFlagsForbidden, float pAbortOnGenerate)
void MapInfo_FilterString (string sf)
float MapInfo_FindName (string s)
string MapInfo_FixName (string s)
int MapInfo_ForbiddenFlags ()
float MapInfo_Get_ByID (float i)
int MapInfo_Get_ByName (string s, float allowGenerate, Gametype gametypeToSet)
string MapInfo_ListAllAllowedMaps (float pFlagsRequired, float pFlagsForbidden)
string MapInfo_ListAllowedMaps (Gametype type, float pFlagsRequired, float pFlagsForbidden)
void MapInfo_LoadMap (string s, float reinit)
void MapInfo_LoadMapSettings (string s)
int MapInfo_RequiredFlags ()
void MapInfo_Shutdown ()
void MapInfo_SwitchGameType (Gametype t)
string MapInfo_Type_Description (Gametype t)
Gametype MapInfo_Type_FromString (string t)
string MapInfo_Type_ToString (Gametype t)
string MapInfo_Type_ToText (Gametype t)
REGISTER_GAMETYPE (DEATHMATCH, NEW(Deathmatch))
REGISTER_GAMETYPE (LMS, NEW(LastManStanding))
REGISTER_GAMETYPE (RACE, NEW(Race))
REGISTER_GAMETYPE (CTS, NEW(RaceCTS))
REGISTER_GAMETYPE (TEAM_DEATHMATCH, NEW(TeamDeathmatch))
REGISTER_GAMETYPE (CTF, NEW(CaptureTheFlag))
REGISTER_GAMETYPE (CA, NEW(ClanArena))
REGISTER_GAMETYPE (DOMINATION, NEW(Domination))
REGISTER_GAMETYPE (KEYHUNT, NEW(KeyHunt))
REGISTER_GAMETYPE (ASSAULT, NEW(Assault))
REGISTER_GAMETYPE (ONSLAUGHT, NEW(Onslaught))
REGISTER_GAMETYPE (NEXBALL, NEW(NexBall))
REGISTER_GAMETYPE (FREEZETAG, NEW(FreezeTag))
REGISTER_GAMETYPE (KEEPAWAY, NEW(Keepaway))
REGISTER_GAMETYPE (INVASION, NEW(Invasion))
REGISTER_GAMETYPE (DUEL, NEW(Duel))
Variables
int m_flags
float MapInfo_count
const int MAPINFO_FEATURE_MONSTERS = 8
const int MAPINFO_FEATURE_TURRETS = 4
const int MAPINFO_FEATURE_VEHICLES = 2
const int MAPINFO_FEATURE_WEAPONS = 1
float MapInfo_FindName_firstResult
string MapInfo_FindName_match
const int MAPINFO_FLAG_FORBIDDEN = 2
const int MAPINFO_FLAG_FRUSTRATING = 4
const int MAPINFO_FLAG_HIDDEN = 1
const int MAPINFO_FLAG_NOAUTOMAPLIST = 8
Gametype MapInfo_LoadedGametype
string MapInfo_Map_author
string MapInfo_Map_bspname
string MapInfo_Map_clientstuff
string MapInfo_Map_description
int MapInfo_Map_flags
string MapInfo_Map_fog
vector MapInfo_Map_maxs
vector MapInfo_Map_mins
int MapInfo_Map_supportedFeatures
int MapInfo_Map_supportedGametypes
string MapInfo_Map_title
string MapInfo_Map_titlestring
float MapInfo_progress
int MAPINFO_TYPE_ALL
Macro Definition Documentation
#define g_assault IS_GAMETYPE(ASSAULT)
Definition at line 446 of file mapinfo.qh.
Referenced by PutPlayerInServer(), spawnfunc(), and waypoint_load_links().
#define g_ca IS_GAMETYPE(CA)
Definition at line 341 of file mapinfo.qh.
#define g_ctf IS_GAMETYPE(CTF)
Definition at line 297 of file mapinfo.qh.
Referenced by DoesQ3ARemoveThisEntity(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), race_writeTime(), and spawnfunc().
#define g_cts IS_GAMETYPE(CTS)
Definition at line 213 of file mapinfo.qh.
Referenced by getladder(), getlsmaps(), getwelcomemessage(), IMPULSE(), MUTATOR_HOOKFUNCTION(), Obituary_SpecialDeath(), player_powerups(), race_deleteTime(), race_readName(), race_readTime(), race_readUID(), race_RetractPlayer(), race_writeTime(), SetSpectatee_status(), Spawn_Score(), spawnfunc(), and TeleportPlayer().
#define g_duel IS_GAMETYPE(DUEL)
Definition at line 608 of file mapinfo.qh.
Referenced by DoesQ3ARemoveThisEntity().
#define g_freezetag IS_GAMETYPE(FREEZETAG)
Definition at line 536 of file mapinfo.qh.
#define g_nexball IS_GAMETYPE(NEXBALL)
Definition at line 495 of file mapinfo.qh.
Referenced by nb_DropBall(), SpawnBall(), spawnfunc(), and SpawnGoal().
#define g_race IS_GAMETYPE(RACE)
Definition at line 183 of file mapinfo.qh.
Referenced by CheckRules_World(), getlsmaps(), IMPULSE(), InitiateSuddenDeath(), PutPlayerInServer(), race_RetractPlayer(), SetSpectatee_status(), spawnfunc(), TeleportPlayer(), and trigger_race_checkpoint_verify().
#define g_tdm IS_GAMETYPE(TEAM_DEATHMATCH)
Definition at line 261 of file mapinfo.qh.
Referenced by DoesQ3ARemoveThisEntity(), and spawnfunc().
#define Gametypes_from (i) _Gametypes_from(i, NULL)
Definition at line 104 of file mapinfo.qh.
Referenced by MapInfo_CurrentGametype(), and ServerList_TypeSort_Click().
#define IS_GAMETYPE (NAME) (MapInfo_LoadedGametype == MAPINFO_TYPE_##NAME)
Definition at line 109 of file mapinfo.qh.
#define MAPINFO_SETTEMP_ACL_SYSTEM "-g_mapinfo_* -rcon_* -_* -g_ban* -r_water +*"
Definition at line 682 of file mapinfo.qh.
Referenced by _MapInfo_Parse_Settemp().
#define MAPINFO_SETTEMP_ACL_USER cvar_string("g_mapinfo_settemp_acl")
Definition at line 681 of file mapinfo.qh.
Referenced by CampaignPreInit(), and MapInfo_Get_ByName_NoFallbacks().
#define REGISTER_GAMETYPE (NAME, inst) REGISTER(Gametypes, MAPINFO_TYPE, NAME, m_id, inst)
Definition at line 107 of file mapinfo.qh.
Referenced by Invasion::m_configuremenu(), Keepaway::m_isAlwaysSupported(), and Duel::m_isForcedSupported().
Function Documentation
float _MapInfo_FilterGametype (int gametypeFlags, float features, float pFlagsRequired, float pFlagsForbidden, float pAbortOnGenerate)
string _MapInfo_GetDefaultEx (Gametype t)
Definition at line 505 of file mapinfo.qc.
Referenced by _MapInfo_Map_ApplyGametypeEx().
 {
     return t ? t.model2 : "";
 }
float _MapInfo_GetTeamPlayBool (Gametype t)
Definition at line 510 of file mapinfo.qc.
References Gametype::team.
Referenced by NET_HANDLE(), and XonoticGametypeList_drawListBoxItem().
 {
     return t ? t.team : false;
 }
void _MapInfo_Parse_Settemp (string pFilename, string acl, float type, string s, float recurse)
Definition at line 629 of file mapinfo.qc.
References _MapInfo_Parse_Settemp(), car(), cdr(), cvar(), cvar_set(), cvar_settemp(), cvar_value_issafe(), fclose(), fgets(), FILE_READ, fopen(), LOG_TRACE(), LOG_WARN, MapInfo_Map_clientstuff, MAPINFO_SETTEMP_ACL_SYSTEM, matchacl(), strcat(), strstrofs, substring(), and WARN_COND.
Referenced by _MapInfo_Parse_Settemp(), CampaignPreInit(), and MapInfo_Get_ByName_NoFallbacks().
 {
     string t;
     float fh, o;
     t = car(s); s = cdr(s);
     // limited support of "" and comments
     //   remove trailing and leading " of t
     if(substring(t, 0, 1) == "\"")
     {
         if(substring(t, -1, 1) == "\"")
             t = substring(t, 1, -2);
     }
     //   remove leading " of s
     if(substring(s, 0, 1) == "\"")
     {
         s = substring(s, 1, -1);
     }
     //   remove trailing " of s, and all that follows (cvar description)
     o = strstrofs(s, "\"", 0);
     if(o >= 0)
         s = substring(s, 0, o);
     //   remove // comments
     o = strstrofs(s, "//", 0);
     if(o >= 0)
         s = substring(s, 0, o);
     //   remove trailing spaces
     while(substring(s, -1, 1) == " ")
         s = substring(s, 0, -2);
     if(t == "#include")
     {
         if(recurse > 0)
         {
             fh = fopen(s, FILE_READ);
             if(fh < 0)
             {
                 if(WARN_COND)
                     LOG_WARN("Map ", pFilename, " references not existing config file ", s);
             }
             else
             {
                 for (;;)
                 {
                     if (!((s = fgets(fh))))
                         break;
                     // catch different sorts of comments
                     if(s == "")                    // empty lines
                         continue;
                     if(substring(s, 0, 1) == "#")  // UNIX style
                         continue;
                     if(substring(s, 0, 2) == "//") // C++ style
                         continue;
                     if(substring(s, 0, 1) == "_")  // q3map style
                         continue;
                     if(substring(s, 0, 4) == "set ")
                         s = substring(s, 4, -1);
                     if(substring(s, 0, 5) == "seta ")
                         s = substring(s, 5, -1);
                     _MapInfo_Parse_Settemp(pFilename, acl, type, s, recurse - 1);
                 }
                 fclose(fh);
             }
         }
         else if(WARN_COND)
             LOG_WARN("Map ", pFilename, " uses too many levels of inclusion");
     }
     else if(t == ""
         || !cvar_value_issafe(t)
         || !cvar_value_issafe(s)
         || matchacl(MAPINFO_SETTEMP_ACL_SYSTEM, t) <= 0)
     {
         if (WARN_COND)
             LOG_WARN("Map ", pFilename, " contains a potentially harmful setting, ignored");
     }
     else if(matchacl(acl, t) <= 0)
     {
         if (WARN_COND)
             LOG_WARN("Map ", pFilename, " contains a denied setting, ignored");
     }
     else
     {
         if(type == 0) // server set
         {
             LOG_TRACE("Applying temporary setting ", t, " := ", s);
         #if 0
             if(cvar("g_campaign"))
                 cvar_set(t, s); // this is a wrapper and is always temporary anyway; no need to backup old values then
             else
         #endif
                 cvar_settemp(t, s);
         }
         else
         {
             LOG_TRACE("Applying temporary client setting ", t, " := ", s);
             MapInfo_Map_clientstuff = strcat(
                     MapInfo_Map_clientstuff, "cl_cmd settemp \"", t, "\" \"", s, "\"\n"
                     );
         }
     }
 }
string MapInfo_BSPName_ByID (float i)
Definition at line 232 of file mapinfo.qc.
References _MapInfo_GlobItem(), and MapInfo_FilterList_Lookup().
Referenced by InstantAction_LoadMap(), MapInfo_Get_ByID(), MapList_Add_All(), MapList_LoadMap(), XonoticMapList_g_maplistCacheToggle(), and XonoticMapList_refilter().
 {
     return _MapInfo_GlobItem(MapInfo_FilterList_Lookup(i));
 }
void MapInfo_Cache_Create ()
Definition at line 35 of file mapinfo.qc.
References _MapInfo_Cache_Active, _MapInfo_Cache_Buf_IndexToMapData, _MapInfo_Cache_DB_NameToIndex, buf_create, db_create(), and MapInfo_Cache_Destroy().
Referenced by MapInfo_Cache_Invalidate(), and preMenuInit().
 {
     MapInfo_Cache_Destroy();
     _MapInfo_Cache_DB_NameToIndex = db_create();
     _MapInfo_Cache_Buf_IndexToMapData = buf_create();
     _MapInfo_Cache_Active = 1;
 }
void MapInfo_Cache_Destroy ()
Definition at line 25 of file mapinfo.qc.
References _MapInfo_Cache_Active, _MapInfo_Cache_Buf_IndexToMapData, _MapInfo_Cache_DB_NameToIndex, and db_close().
Referenced by MapInfo_Cache_Create(), and MapInfo_Shutdown().
 {
     if(!_MapInfo_Cache_Active)
         return;
     db_close(_MapInfo_Cache_DB_NameToIndex);
     buf_del(_MapInfo_Cache_Buf_IndexToMapData);
     _MapInfo_Cache_Active = 0;
 }
void MapInfo_Cache_Invalidate ()
Definition at line 43 of file mapinfo.qc.
References _MapInfo_Cache_Active, and MapInfo_Cache_Create().
Referenced by MapInfo_Enumerate().
 {
     if(!_MapInfo_Cache_Active)
         return;
     MapInfo_Cache_Create();
 }
float MapInfo_CheckMap (string s)
Definition at line 1171 of file mapinfo.qc.
References _MapInfo_CheckMap(), and MapInfo_ClearTemps().
Referenced by DoNextMapOverride(), GenericCommand_maplist(), getmaplist(), GotoMap(), Map_Check(), MapList_LoadMap(), MapVote_AddVotable(), MapVote_Suggest(), and ValidateMap().
 {
     float r;
     r = _MapInfo_CheckMap(s, false);
     MapInfo_ClearTemps();
     return r;
 }
void MapInfo_ClearTemps ()
Definition at line 1283 of file mapinfo.qc.
References MapInfo_Map_author, MapInfo_Map_bspname, MapInfo_Map_clientstuff, MapInfo_Map_description, MapInfo_Map_supportedFeatures, MapInfo_Map_supportedGametypes, MapInfo_Map_title, MapInfo_Map_titlestring, and string_null.
Referenced by _MapInfo_FilterGametype(), getladder(), getlsmaps(), getmaplist(), getrankings(), getrecords(), InitGameplayMode(), MapInfo_CheckMap(), MapInfo_FilterString(), MapInfo_Shutdown(), XonoticMapInfoDialog_loadMapInfo(), and XonoticMapList_drawListBoxItem().
 {
     MapInfo_Map_bspname = string_null;
     MapInfo_Map_title = string_null;
     MapInfo_Map_titlestring = string_null;
     MapInfo_Map_description = string_null;
     MapInfo_Map_author = string_null;
     MapInfo_Map_clientstuff = string_null;
     MapInfo_Map_supportedGametypes = 0;
     MapInfo_Map_supportedFeatures = 0;
 }
int MapInfo_CurrentFeatures ()
Definition at line 1141 of file mapinfo.qc.
References cvar(), and MAPINFO_FEATURE_WEAPONS.
Referenced by _MapInfo_CheckMap(), GameCommand_gametype(), GameTypeVote_SetGametype(), GenericCommand_maplist(), GotoFirstMap(), InstantAction_LoadMap(), make_mapinfo_Think(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapVote_Start(), MapVote_Think(), RestoreGame(), spawnfunc(), and XonoticMapList_refilter().
 {
     int req = 0;
     // TODO: find a better way to check if weapons are required on the map
     if(!(cvar("g_instagib") || cvar("g_overkill") || cvar("g_nix") || cvar("g_weaponarena") || !cvar("g_pickup_items")
         || cvar("g_race") || cvar("g_cts") || cvar("g_nexball") || cvar("g_ca") || cvar("g_freezetag") || cvar("g_lms")))
         req |= MAPINFO_FEATURE_WEAPONS;
     return req;
 }
Gametype MapInfo_CurrentGametype ()
Definition at line 1151 of file mapinfo.qc.
References cvar(), FOREACH, Gametypes_from, and prev.
Referenced by _MapInfo_CheckMap(), Campaign_Invalid(), GameCommand_gametype(), GameType_ConfigureSliders_for_CurrentGametype(), GameTypeVote_SetGametype(), GameTypeVote_Start(), GenericCommand_maplist(), GotoFirstMap(), InstantAction_LoadMap(), make_mapinfo_Think(), MapInfo_ListAllAllowedMaps(), MapInfo_LoadMapSettings(), MapVote_CheckRules_2(), MapVote_Init(), MapVote_SendEntity(), MapVote_Start(), MapVote_Think(), RestoreGame(), spawnfunc(), STATIC_INIT_LATE(), TeamBalance_FindBestTeam(), XonoticGametypeList_loadCvars(), XonoticGametypeList_saveCvars(), and XonoticMapList_refilter().
 {
     Gametype prev = Gametypes_from(cvar("gamecfg"));
     FOREACH(Gametypes, cvar(it.netname) && it != prev, return it);
     return prev ? prev : MAPINFO_TYPE_DEATHMATCH;
 }
void MapInfo_Enumerate ()
Definition at line 116 of file mapinfo.qc.
References _MapInfo_globcount, _MapInfo_globhandle, _MapInfo_globopen, MapInfo_Cache_Invalidate(), search_begin(), search_end(), and search_getsize().
Referenced by GameCommand_make_mapinfo(), GameTypeVote_MapInfo_FixName(), GameTypeVote_SetGametype(), GenericCommand_maplist(), GotoFirstMap(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapVote_Start(), preMenuInit(), RestoreGame(), and spawnfunc().
 {
     if(_MapInfo_globopen)
     {
         search_end(_MapInfo_globhandle);
         _MapInfo_globopen = 0;
     }
     MapInfo_Cache_Invalidate();
     _MapInfo_globhandle = search_begin("maps/*.bsp", true, true);
     if(_MapInfo_globhandle >= 0)
     {
         _MapInfo_globcount = search_getsize(_MapInfo_globhandle);
         _MapInfo_globopen = 1;
     }
     else
         _MapInfo_globcount = 0;
 }
float MapInfo_FilterGametype (Gametype gametypeFlags, float features, float pFlagsRequired, float pFlagsForbidden, float pAbortOnGenerate)
void MapInfo_FilterString (string sf)
Definition at line 195 of file mapinfo.qc.
References _MapInfo_filtered, _MapInfo_FilterList_cmp(), _MapInfo_FilterList_swap(), heapsort(), MapInfo_ClearTemps(), MapInfo_count, MapInfo_Get_ByID(), MapInfo_Map_bspname, MapInfo_Map_title, NULL, and strstrofs.
Referenced by XonoticMapList_refilter().
 {
     // this function further filters _MapInfo_filtered, which is prepared by MapInfo_FilterGametype by string
     float i, j;
     string title;
     for(i = 0, j = -1; i < MapInfo_count; ++i)
     {
         if (MapInfo_Get_ByID(i))
         {
             // prepare for keyword filter
             if (MapInfo_Map_title && strstrofs(MapInfo_Map_title, "<TITLE>", 0) == -1)
                 title = MapInfo_Map_title;
             else
                 title = MapInfo_Map_bspname;
             // keyword filter
             if((strstrofs(strtolower(title), strtolower(sf), 0)) >= 0)
                 bufstr_set(_MapInfo_filtered, ++j, bufstr_get(_MapInfo_filtered, i));
         }
     }
     MapInfo_count = j + 1;
     MapInfo_ClearTemps();
     // sometimes the glob isn't sorted nicely, so fix it here...
     heapsort(MapInfo_count, _MapInfo_FilterList_swap, _MapInfo_FilterList_cmp, NULL);
 }
float MapInfo_FindName (string s)
Definition at line 1087 of file mapinfo.qc.
References _MapInfo_GlobItem(), floor(), MapInfo_count, MapInfo_FilterList_Lookup(), MapInfo_FindName_firstResult, MapInfo_FindName_match, startsWithNocase(), strcasecmp, and string_null.
Referenced by MapInfo_FixName(), XonoticMapList_keyDown(), and XonoticMapList_refilter().
 {
     // if there is exactly one map of prefix s, return it
     // if not, return the null string
     // note that DP sorts glob results... so I can use a binary search
     float l, r, m, cmp;
     l = 0;
     r = MapInfo_count;
     // invariants: r is behind s, l-1 is equal or before
     while(l != r)
     {
         m = floor((l + r) / 2);
         MapInfo_FindName_match = _MapInfo_GlobItem(MapInfo_FilterList_Lookup(m));
         cmp = strcasecmp(MapInfo_FindName_match, s);
         if(cmp == 0)
             return m; // found and good
         if(cmp < 0)
             l = m + 1; // l-1 is before s
         else
             r = m; // behind s
     }
     MapInfo_FindName_match = _MapInfo_GlobItem(MapInfo_FilterList_Lookup(l));
     MapInfo_FindName_firstResult = l;
     // r == l, so: l is behind s, l-1 is before
     // SO: if there is any, l is the one with the right prefix
     //     and l+1 may be one too
     if(l == MapInfo_count)
     {
         MapInfo_FindName_match = string_null;
         MapInfo_FindName_firstResult = -1;
         return -1; // no MapInfo_FindName_match, behind last item
     }
     if(!startsWithNocase(MapInfo_FindName_match, s))
     {
         MapInfo_FindName_match = string_null;
         MapInfo_FindName_firstResult = -1;
         return -1; // wrong prefix
     }
     if(l == MapInfo_count - 1)
         return l; // last one, nothing can follow => unique
     if(startsWithNocase(_MapInfo_GlobItem(MapInfo_FilterList_Lookup(l + 1)), s))
     {
         MapInfo_FindName_match = string_null;
         return -1; // ambigous MapInfo_FindName_match
     }
     return l;
 }
string MapInfo_FixName (string s)
Definition at line 1135 of file mapinfo.qc.
References MapInfo_FindName(), and MapInfo_FindName_match.
Referenced by GameTypeVote_MapInfo_FixName(), and ValidateMap().
 {
     MapInfo_FindName(s);
     return MapInfo_FindName_match;
 }
int MapInfo_ForbiddenFlags ()
Definition at line 1308 of file mapinfo.qc.
References cvar(), MAPINFO_FLAG_FORBIDDEN, MAPINFO_FLAG_FRUSTRATING, and MAPINFO_FLAG_HIDDEN.
Referenced by GameCommand_gametype(), GameTypeVote_MapInfo_FixName(), GameTypeVote_SetGametype(), GenericCommand_maplist(), getlsmaps(), GotoFirstMap(), InstantAction_LoadMap(), make_mapinfo_Think(), MapList_Add_All(), Maplist_Init(), MapVote_Init(), MapVote_Start(), MapVote_Think(), RestoreGame(), spawnfunc(), and XonoticMapList_refilter().
 {
     int f = MAPINFO_FLAG_FORBIDDEN;
 #ifdef GAMEQC
     if (!cvar("g_maplist_allow_hidden"))
 #endif
         f |= MAPINFO_FLAG_HIDDEN;
     if (!cvar("g_maplist_allow_frustrating"))
         f |= MAPINFO_FLAG_FRUSTRATING;
     return f;
 }
float MapInfo_Get_ByID (float i)
Definition at line 257 of file mapinfo.qc.
References MapInfo_BSPName_ByID(), MapInfo_Get_ByName(), and NULL.
Referenced by getladder(), getlsmaps(), MapInfo_FilterString(), MUTATOR_HOOKFUNCTION(), XonoticMapInfoDialog_loadMapInfo(), and XonoticMapList_drawListBoxItem().
 {
     if(MapInfo_Get_ByName(MapInfo_BSPName_ByID(i), 0, NULL))
         return 1;
     return 0;
 }
int MapInfo_Get_ByName (string s, float allowGenerate, Gametype gametypeToSet)
Definition at line 1068 of file mapinfo.qc.
References _MapInfo_Map_ApplyGametypeEx(), error, FOREACH, MapInfo_Get_ByName_NoFallbacks(), and MapInfo_Map_supportedGametypes.
Referenced by _MapInfo_CheckMap(), _MapInfo_FilterGametype(), GameTypeVote_AvailabilityStatus(), MapInfo_Get_ByID(), MapInfo_LoadMapSettings(), and swapInPriorityList().
 {
     int r = MapInfo_Get_ByName_NoFallbacks(pFilename, pAllowGenerate, pGametypeToSet);
     FOREACH(Gametypes, it.m_isForcedSupported(it), _MapInfo_Map_ApplyGametypeEx("", pGametypeToSet, it));
     if(pGametypeToSet)
     {
         if(!(MapInfo_Map_supportedGametypes & pGametypeToSet.m_flags))
         {
             error("Can't select the requested game type. This should never happen as the caller should prevent it!\n");
             //_MapInfo_Map_ApplyGametypeEx("", pGametypeToSet, MAPINFO_TYPE_DEATHMATCH);
             //return;
         }
     }
     return r;
 }
string MapInfo_ListAllAllowedMaps (float pFlagsRequired, float pFlagsForbidden)
Definition at line 1217 of file mapinfo.qc.
References _MapInfo_FilterGametype(), _MapInfo_GlobItem(), MapInfo_count, MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_FilterList_Lookup(), MAPINFO_TYPE_ALL, strcat(), strlen(), and substring().
Referenced by Maplist_Init().
 {
     string out;
     // to make absolutely sure:
     MapInfo_Enumerate();
     _MapInfo_FilterGametype(MAPINFO_TYPE_ALL, 0, pRequiredFlags, pForbiddenFlags, 0);
     out = "";
     for(float i = 0; i < MapInfo_count; ++i)
         out = strcat(out, " ", _MapInfo_GlobItem(MapInfo_FilterList_Lookup(i)));
     MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), pRequiredFlags, pForbiddenFlags, 0);
     return substring(out, 1, strlen(out) - 1);
 }
string MapInfo_ListAllowedMaps (Gametype type, float pFlagsRequired, float pFlagsForbidden)
Definition at line 1203 of file mapinfo.qc.
References _MapInfo_GlobItem(), MapInfo_count, MapInfo_CurrentFeatures(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_FilterList_Lookup(), strcat(), strlen(), and substring().
Referenced by GameTypeVote_SetGametype(), and MapVote_Init().
 {
     string out;
     // to make absolutely sure:
     MapInfo_Enumerate();
     MapInfo_FilterGametype(type, MapInfo_CurrentFeatures(), pRequiredFlags, pForbiddenFlags, 0);
     out = "";
     for(float i = 0; i < MapInfo_count; ++i)
         out = strcat(out, " ", _MapInfo_GlobItem(MapInfo_FilterList_Lookup(i)));
     return substring(out, 1, strlen(out) - 1);
 }
void MapInfo_LoadMap (string s, float reinit)
Definition at line 1184 of file mapinfo.qc.
References cvar_settemp_restore(), localcmd, LOG_INFO, MapInfo_Map_supportedGametypes, and strcat().
Referenced by CampaignSetup(), InstantAction_LoadMap(), Map_Goto(), and MapList_LoadMap().
 {
     MapInfo_Map_supportedGametypes = 0;
     // we shouldn't need this, as LoadMapSettings already fixes the gametype
     //if(!MapInfo_CheckMap(s))
     //{
     //  print("EMERGENCY: can't play the selected map in the given game mode. Falling back to DM.\n");
     //  MapInfo_SwitchGameType(MAPINFO_TYPE_DEATHMATCH.m_flags);
     //}
     LOG_INFO("Switching to map ", s);
     cvar_settemp_restore();
     if(reinit)
         localcmd(strcat("\nmap ", s, "\n"));
     else
         localcmd(strcat("\nchangelevel ", s, "\n"));
 }
void MapInfo_LoadMapSettings (string s)
Definition at line 1241 of file mapinfo.qc.
References _MapInfo_CheckMap(), _MapInfo_Map_ApplyGametypeEx(), cvar(), floor(), FOREACH, LOG_SEVERE, LOG_WARNF, MapInfo_CurrentGametype(), MapInfo_Get_ByName(), MapInfo_LoadMapSettings_SaveGameType(), and MapInfo_Map_supportedGametypes.
Referenced by InitGameplayMode().
 {
     Gametype t = MapInfo_CurrentGametype();
     MapInfo_LoadMapSettings_SaveGameType(t);
     if(!_MapInfo_CheckMap(s, true)) // with underscore, it keeps temps
     {
         if(cvar("g_mapinfo_allow_unsupported_modes_and_let_stuff_break"))
         {
             LOG_SEVERE("can't play the selected map in the given game mode. Working with only the override settings.");
             _MapInfo_Map_ApplyGametypeEx("", t, t);
             return; // do not call Get_ByName!
         }
         if(MapInfo_Map_supportedGametypes == 0)
         {
             LOG_SEVERE("Mapinfo system is not functional at all. Assuming deathmatch.");
             MapInfo_Map_supportedGametypes = MAPINFO_TYPE_DEATHMATCH.m_flags;
             MapInfo_LoadMapSettings_SaveGameType(MAPINFO_TYPE_DEATHMATCH);
             _MapInfo_Map_ApplyGametypeEx("", MAPINFO_TYPE_DEATHMATCH, MAPINFO_TYPE_DEATHMATCH);
             return; // do not call Get_ByName!
         }
         int _t = 1;
         while(!(MapInfo_Map_supportedGametypes & 1))
         {
             _t <<= 1;
             MapInfo_Map_supportedGametypes = floor(MapInfo_Map_supportedGametypes >> 1);
         }
         Gametype t_prev = t;
         FOREACH(Gametypes, it.m_flags == _t, { t = it; break; });
         // t is now a supported mode!
         LOG_WARNF("can't play the selected map in the given game mode (%s). Falling back to a supported mode (%s).", t_prev.mdl, t.mdl);
         MapInfo_LoadMapSettings_SaveGameType(t);
     }
     if(!_MapInfo_CheckMap(s, false)) { // with underscore, it keeps temps
         LOG_WARNF("the selected map lacks features required by current settings; playing anyway.");
     }
     MapInfo_Get_ByName(s, 1, t);
 }
int MapInfo_RequiredFlags ()
Definition at line 1323 of file mapinfo.qc.
References cvar(), and MAPINFO_FLAG_FRUSTRATING.
Referenced by GameCommand_gametype(), GameTypeVote_MapInfo_FixName(), GameTypeVote_SetGametype(), GenericCommand_maplist(), GotoFirstMap(), InstantAction_LoadMap(), make_mapinfo_Think(), Maplist_Init(), MapVote_Init(), MapVote_Start(), MapVote_Think(), RestoreGame(), spawnfunc(), and XonoticMapList_refilter().
 {
     int f = 0;
     if(cvar("g_maplist_allow_frustrating") > 1)
         f |= MAPINFO_FLAG_FRUSTRATING;
     return f;
 }
void MapInfo_Shutdown ()
Definition at line 1295 of file mapinfo.qc.
References _MapInfo_globhandle, _MapInfo_globopen, MapInfo_Cache_Destroy(), MapInfo_ClearTemps(), MapInfo_Filter_Free(), and search_end().
Referenced by __init_dedicated_server_shutdown(), RestoreGame(), Shutdown(), and XonoticMapList_destroy().
 {
     MapInfo_ClearTemps();
     MapInfo_Filter_Free();
     MapInfo_Cache_Destroy();
     if(_MapInfo_globopen)
     {
         search_end(_MapInfo_globhandle);
         _MapInfo_globhandle = -1;
         _MapInfo_globopen = false;
     }
 }
void MapInfo_SwitchGameType (Gametype t)
Definition at line 1179 of file mapinfo.qc.
References cvar_set(), and FOREACH.
Referenced by CampaignPreInit(), GameCommand_gametype(), GameTypeVote_SetGametype(), InstantAction_LoadMap(), MapInfo_LoadMapSettings_SaveGameType(), and XonoticGametypeList_saveCvars().
 {
     FOREACH(Gametypes, true, cvar_set(it.netname, (it == t) ? "1" : "0"));
 }
string MapInfo_Type_Description (Gametype t)
Definition at line 613 of file mapinfo.qc.
Referenced by GameTypeVote_ReadOption(), and XonoticGametypeList_focusedItemChangeNotify().
 {
     return t ? t.gametype_description : "";
 }
Gametype MapInfo_Type_FromString (string t)
Definition at line 592 of file mapinfo.qc.
References FOREACH, LOG_WARNF, MapInfo_Map_bspname, NULL, and WARN_COND.
Referenced by Campaign_Invalid(), CampaignPreInit(), GameCommand_gametype(), GameTypeVote_AvailabilityStatus(), GameTypeVote_ReadOption(), GameTypeVote_Type_FromString(), MapInfo_Get_ByName_NoFallbacks(), and XonoticServerInfoDialog_loadServerInfo().
 {
     string replacement = "";
     switch (gtype)
     {
         case "nexball":   replacement = "nb"; break;
         case "freezetag": replacement = "ft"; break;
         case "keepaway":  replacement = "ka"; break;
         case "invasion":  replacement = "inv"; break;
         case "assault":   replacement = "as"; break;
         case "race":      replacement = "rc"; break;
     }
     if (replacement != "" && WARN_COND)
     {
         LOG_WARNF("MapInfo_Type_FromString (probably %s): using deprecated name '%s'. Should use '%s'.", MapInfo_Map_bspname, gtype, replacement);
         gtype = replacement;
     }
     FOREACH(Gametypes, it.mdl == gtype, return it);
     return NULL;
 }
string MapInfo_Type_ToString (Gametype t)
Definition at line 618 of file mapinfo.qc.
Referenced by _MapInfo_Map_ApplyGametypeEx(), Gamemode_Init(), GameType_GetIcon(), GameTypeVote_SetGametype(), GameTypeVote_Start(), GetGametype(), isGametypeInFilter(), MapVote_CheckRules_2(), ServerList_TypeSort_Click(), and TeamBalance_FindBestTeam().
 {
     return t ? t.mdl : "";
 }
string MapInfo_Type_ToText (Gametype t)
Definition at line 623 of file mapinfo.qc.
Referenced by GameType_GetName(), GameTypeVote_ReadOption(), InitGameplayMode(), MapVote_SendEntity(), Scoreboard_Draw(), XonoticMapInfoDialog_fill(), and XonoticServerInfoDialog_loadServerInfo().
 {
     /* xgettext:no-c-format */
     return t ? t.message : _("@!#%'n Tuba Throwing");
 }
REGISTER_GAMETYPE (DEATHMATCH , NEW(Deathmatch))
REGISTER_GAMETYPE (LMS , NEW(LastManStanding))
REGISTER_GAMETYPE (RACE , NEW(Race))
REGISTER_GAMETYPE (CTS , NEW(RaceCTS))
REGISTER_GAMETYPE (TEAM_DEATHMATCH , NEW(TeamDeathmatch))
REGISTER_GAMETYPE (CTF , NEW(CaptureTheFlag))
REGISTER_GAMETYPE (CA , NEW(ClanArena))
REGISTER_GAMETYPE (DOMINATION , NEW(Domination))
REGISTER_GAMETYPE (KEYHUNT , NEW(KeyHunt))
REGISTER_GAMETYPE (ASSAULT , NEW(Assault))
REGISTER_GAMETYPE (ONSLAUGHT , NEW(Onslaught))
REGISTER_GAMETYPE (NEXBALL , NEW(NexBall))
REGISTER_GAMETYPE (FREEZETAG , NEW(FreezeTag))
REGISTER_GAMETYPE (KEEPAWAY , NEW(Keepaway))
REGISTER_GAMETYPE (INVASION , NEW(Invasion))
REGISTER_GAMETYPE (DUEL , NEW(Duel))
Variable Documentation
int m_flags
Definition at line 20 of file mapinfo.qh.
Referenced by _MapInfo_CheckMap(), Gametype::gametype_init(), Race::m_generate_mapinfo(), RaceCTS::m_generate_mapinfo(), CaptureTheFlag::m_generate_mapinfo(), Domination::m_generate_mapinfo(), Assault::m_generate_mapinfo(), Onslaught::m_generate_mapinfo(), NexBall::m_generate_mapinfo(), Invasion::m_generate_mapinfo(), TeamDeathmatch::m_isForcedSupported(), and Duel::m_isForcedSupported().
float MapInfo_count
Definition at line 620 of file mapinfo.qh.
Referenced by _MapInfo_FilterGametype(), GameCommand_gametype(), GameTypeVote_SetGametype(), getladder(), getlsmaps(), InstantAction_LoadMap(), MapInfo_FilterString(), MapInfo_FindName(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapList_Add_All(), MUTATOR_HOOKFUNCTION(), and XonoticMapList_refilter().
const int MAPINFO_FEATURE_MONSTERS = 8
Definition at line 613 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), and MapInfo_Get_ByName_NoFallbacks().
const int MAPINFO_FEATURE_TURRETS = 4
Definition at line 612 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), and MapInfo_Get_ByName_NoFallbacks().
const int MAPINFO_FEATURE_VEHICLES = 2
Definition at line 611 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), and MapInfo_Get_ByName_NoFallbacks().
const int MAPINFO_FEATURE_WEAPONS = 1
Definition at line 610 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), MapInfo_CurrentFeatures(), and MapInfo_Get_ByName_NoFallbacks().
float MapInfo_FindName_firstResult
Definition at line 645 of file mapinfo.qh.
Referenced by MapInfo_FindName(), and XonoticMapList_keyDown().
string MapInfo_FindName_match
Definition at line 644 of file mapinfo.qh.
Referenced by MapInfo_FindName(), and MapInfo_FixName().
const int MAPINFO_FLAG_FORBIDDEN = 2
Definition at line 616 of file mapinfo.qh.
Referenced by MapInfo_ForbiddenFlags(), and MapInfo_Get_ByName_NoFallbacks().
const int MAPINFO_FLAG_FRUSTRATING = 4
Definition at line 617 of file mapinfo.qh.
Referenced by MapInfo_ForbiddenFlags(), MapInfo_Get_ByName_NoFallbacks(), and MapInfo_RequiredFlags().
const int MAPINFO_FLAG_HIDDEN = 1
Definition at line 615 of file mapinfo.qh.
Referenced by MapInfo_ForbiddenFlags(), and MapInfo_Get_ByName_NoFallbacks().
const int MAPINFO_FLAG_NOAUTOMAPLIST = 8
Definition at line 618 of file mapinfo.qh.
Referenced by MapInfo_Get_ByName_NoFallbacks(), and Maplist_Init().
Gametype MapInfo_LoadedGametype
Definition at line 669 of file mapinfo.qh.
Referenced by GetGametype(), InitGameplayMode(), MapInfo_LoadMapSettings_SaveGameType(), ScoreInfo_SendEntity(), and SV_OnEntityPreSpawnFunction().
string MapInfo_Map_author
Definition at line 10 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), _MapInfo_Map_Reset(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_Get_ByName_NoFallbacks(), XonoticMapInfoDialog_loadMapInfo(), and XonoticMapList_drawListBoxItem().
string MapInfo_Map_bspname
Definition at line 6 of file mapinfo.qh.
Referenced by getladder(), getlsmaps(), LocalCommand_create_scrshot_ent(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_FilterString(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_Type_FromString(), MUTATOR_HOOKFUNCTION(), XonoticMapInfoDialog_loadMapInfo(), and XonoticMapList_drawListBoxItem().
string MapInfo_Map_clientstuff
Definition at line 11 of file mapinfo.qh.
Referenced by _MapInfo_Map_Reset(), _MapInfo_Parse_Settemp(), InitGameplayMode(), MapInfo_ClearTemps(), and MapInfo_Get_ByName_NoFallbacks().
string MapInfo_Map_description
Definition at line 9 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), _MapInfo_Map_Reset(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_Get_ByName_NoFallbacks(), and XonoticMapInfoDialog_loadMapInfo().
int MapInfo_Map_flags
Definition at line 15 of file mapinfo.qh.
Referenced by _MapInfo_FilterGametype(), _MapInfo_Generate(), _MapInfo_Map_Reset(), getlsmaps(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), and MapInfo_Get_ByName_NoFallbacks().
string MapInfo_Map_fog
Definition at line 12 of file mapinfo.qh.
Referenced by _MapInfo_Map_Reset(), InitGameplayMode(), and MapInfo_Get_ByName_NoFallbacks().
vector MapInfo_Map_maxs
Definition at line 17 of file mapinfo.qh.
Referenced by _MapInfo_Map_Reset(), MapInfo_Get_ByName_NoFallbacks(), and swapInPriorityList().
vector MapInfo_Map_mins
Definition at line 16 of file mapinfo.qh.
Referenced by _MapInfo_Map_Reset(), MapInfo_Get_ByName_NoFallbacks(), and swapInPriorityList().
int MapInfo_Map_supportedFeatures
Definition at line 14 of file mapinfo.qh.
Referenced by _MapInfo_CheckMap(), _MapInfo_FilterGametype(), _MapInfo_Generate(), _MapInfo_Map_Reset(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), and MapInfo_Get_ByName_NoFallbacks().
int MapInfo_Map_supportedGametypes
Definition at line 13 of file mapinfo.qh.
Referenced by _MapInfo_CheckMap(), _MapInfo_FilterGametype(), _MapInfo_Generate(), _MapInfo_Map_ApplyGametype(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Map_Reset(), GameTypeVote_AvailabilityStatus(), Race::m_generate_mapinfo(), RaceCTS::m_generate_mapinfo(), CaptureTheFlag::m_generate_mapinfo(), Domination::m_generate_mapinfo(), Assault::m_generate_mapinfo(), Onslaught::m_generate_mapinfo(), NexBall::m_generate_mapinfo(), Invasion::m_generate_mapinfo(), TeamDeathmatch::m_isForcedSupported(), Duel::m_isForcedSupported(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_Get_ByName(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_LoadMap(), MapInfo_LoadMapSettings(), and XonoticMapInfoDialog_loadMapInfo().
string MapInfo_Map_title
Definition at line 7 of file mapinfo.qh.
Referenced by _MapInfo_Generate(), _MapInfo_Map_Reset(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_FilterString(), MapInfo_Get_ByName_NoFallbacks(), and XonoticMapInfoDialog_loadMapInfo().
string MapInfo_Map_titlestring
Definition at line 8 of file mapinfo.qh.
Referenced by _MapInfo_Map_Reset(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_ClearTemps(), MapInfo_Get_ByName_NoFallbacks(), and XonoticMapList_drawListBoxItem().
float MapInfo_progress
Definition at line 627 of file mapinfo.qh.
Referenced by _MapInfo_FilterGametype(), and preMenuInit().
int MAPINFO_TYPE_ALL
Definition at line 19 of file mapinfo.qh.
Referenced by Gametype::gametype_init(), make_mapinfo_Think(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapList_Add_All(), and preMenuInit().