Xonotic: menu/xonotic/dialog_settings_game_hudconfirm.qc File Reference
dialog_settings_game_hudconfirm.qc File Reference
#include "dialog_settings_game_hudconfirm.qh"
#include "textlabel.qh"
#include "button.qh"
Functions
void HUDSetup_Start (entity me, entity btn)
void XonoticHUDConfirmDialog_fill (entity me)
Function Documentation
void HUDSetup_Start (entity me, entity btn)
Definition at line 6 of file dialog_settings_game_hudconfirm.qc.
References GAME_CONNECTED, GAME_ISSERVER, gamestatus, and localcmd.
Referenced by HUDSetup_Check_Gamestatus(), and XonoticHUDConfirmDialog_fill().
 {
     if (!(gamestatus & (GAME_CONNECTED | GAME_ISSERVER)))
         localcmd("map _hudsetup\n");
     else
         localcmd("togglemenu 0\n");
     localcmd("_hud_configure 1\n");
 }
void XonoticHUDConfirmDialog_fill (entity me)
Definition at line 16 of file dialog_settings_game_hudconfirm.qc.
References Dialog_Close(), entity(), HUDSetup_Start(), makeXonoticButton(), and makeXonoticTextLabel().
 {
     entity e;
     me.TR(me);
         me.TD(me, 1, 2, e = makeXonoticTextLabel(0.5, _("In order for the HUD editor to show, you must first be in game.")));
     me.TR(me);
         me.TD(me, 1, 2, e = makeXonoticTextLabel(0.5, _("Do you wish to start a local game to set up the HUD?")));
     me.TR(me);
     me.TR(me);
         me.TD(me, 1, 1, e = makeXonoticButton(_("Yes"), '1 0 0'));
             e.onClick = HUDSetup_Start;
             e.onClickEntity = me;
         me.TD(me, 1, 1, e = makeXonoticButton(_("No"), '0 1 0'));
             e.onClick = Dialog_Close;
             e.onClickEntity = me;
 }