Xonotic: server/damage.qh File Reference
damage.qh File Reference
#include <common/weapons/_all.qh>
Macros
#define DMG_NOWEP (weaponentities[0])
Functions
string AppendItemcodes (string s, entity player)
bool (entity targ, entity inflictor, float amount, float limit) event_heal
void Damage (entity targ, entity inflictor, entity attacker, float damage, int deathtype,.entity weaponentity, vector hitloc, vector force)
void Damage_DamageInfo (vector org, float coredamage, float edgedamage, float rad, vector force, int deathtype, float bloodtype, entity dmgowner)
bool Damage_DamageInfo_SendEntity (entity this, entity to, int sf)
float Fire_AddDamage (entity e, entity o, float d, float t, float dt)
void Fire_ApplyDamage (entity e)
void Freeze (entity targ, float revivespeed, int frozen_type, bool show_waypoint)
void GiveFrags (entity attacker, entity targ, float f, int deathtype,.entity weaponentity)
bool Heal (entity targ, entity inflictor, float amount, float limit)
void Ice_Think (entity this)
float IsFlying (entity a)
void LogDeath (string mode, int deathtype, entity killer, entity killed)
void Obituary (entity attacker, entity inflictor, entity targ, int deathtype,.entity weaponentity)
void Obituary_SpecialDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2, float f3)
float Obituary_WeaponDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2)
float RadiusDamage (entity inflictor, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float forceintensity, int deathtype,.entity weaponentity, entity directhitentity)
float RadiusDamageForSource (entity inflictor, vector inflictororigin, vector inflictorvelocity, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float inflictorselfdamage, float forceintensity, float forcezscale, int deathtype,.entity weaponentity, entity directhitentity)
STATIC_INIT (g_damagedbycontents)
void Unfreeze (entity targ, bool reset_health)
void UpdateFrags (entity player, int f)
void (entity this, entity inflictor, entity attacker, float damage, int deathtype,.entity weaponentity, vector hitloc, vector force) event_damage
void W_SwitchWeapon_Force (Player this, Weapon w,.entity weaponentity)
Variables
float autocvar_g_balance_armor_blockpercent
float autocvar_g_balance_damagepush_speedfactor
int autocvar_g_balance_firetransfer_damage
int autocvar_g_balance_firetransfer_time
float autocvar_g_balance_selfdamagepercent
float autocvar_g_friendlyfire
float autocvar_g_friendlyfire_virtual
float autocvar_g_friendlyfire_virtual_force
bool autocvar_g_frozen_damage_trigger
float autocvar_g_frozen_force
float autocvar_g_frozen_revive_falldamage
int autocvar_g_frozen_revive_falldamage_health
float autocvar_g_maxpushtime
float autocvar_g_mirrordamage
bool autocvar_g_mirrordamage_onlyweapons
bool autocvar_g_mirrordamage_virtual
float autocvar_g_teamdamage_resetspeed
float autocvar_g_teamdamage_threshold
float autocvar_g_throughfloor_damage
float autocvar_g_throughfloor_damage_max_stddev
bool autocvar_g_throughfloor_debug
float autocvar_g_throughfloor_force
float autocvar_g_throughfloor_force_max_stddev
float autocvar_g_throughfloor_max_steps_other
float autocvar_g_throughfloor_max_steps_player
float autocvar_g_throughfloor_min_steps_other
float autocvar_g_throughfloor_min_steps_player
bool canteamdamage
float checkrules_firstblood
float damage_dealt
float damagedbycontents
float damagedbytriggers
float damageextraradius
float damageforcescale
vector death_origin
string deathmessage
float dmg
float dmg_edge
float dmg_force
float dmg_radius
float dmg_team
entity fire_burner
float fire_damagepersec
float fire_deathtype
float fire_hitsound
entity fire_owner
float freeze_time
entity frozen_by
const int FROZEN_NORMAL = 1
const int FROZEN_TEMP_DYING = 3
const int FROZEN_TEMP_REVIVING = 2
IntrusiveList g_damagedbycontents
entity iceblock
int impressive_hits
bool istypefrag
float killsound
const float MAX_DAMAGEEXTRARADIUS = 16
const float MIN_DAMAGEEXTRARADIUS = 2
float pain_finished
entity pusher
float RadiusDamage_running
float revival_time
float revive_speed
float spawnshieldtime
float taunt_soundtime
float teamkill_complain
entity teamkill_soundsource
float teamkill_soundtime
int totalfrags
float typehitsound
float w_deathtype
float yoda
Macro Definition Documentation
DMG_NOWEP
#define DMG_NOWEP (weaponentities[0])
Definition at line 125 of file damage.qh.
Referenced by buff_Vengeance_DelayedDamage(), CheatImpulse(), checkpoint_passed(), ClientKill_Now(), CommonCommand_editmob(), CreatureFrame_FallDamage(), CreatureFrame_hotliquids(), ctf_CaptureShield_Touch(), door_blocked(), door_generic_plat_blocked(), DrownPlayer(), Fire_ApplyDamage(), generic_plat_blocked(), havocbot_role_ctf_carrier(), instagib_countdown(), KillPlayerForTeamChange(), Monster_Attack_Melee(), Monster_Frozen_Think(), Monster_Move(), Monster_Think(), MUTATOR_HOOKFUNCTION(), ons_CaptureShield_Touch(), ons_ControlPoint_Icon_Think(), Onslaught_CheckWinner(), plat_crush(), player_regen(), PlayerPreThink(), PlayerTouchExplode(), vehicles_impact(), vehicles_projectile_explode(), and vehicles_touch().
Function Documentation
AppendItemcodes()
string AppendItemcodes (string s, entity player)
Definition at line 87 of file damage.qc.
References cnt, ftos(), M_ARGV, MAX_WEAPONSLOTS, MUTATOR_CALLHOOK, PHYS_INPUT_BUTTON_CHAT, strcat(), and weaponentities.
Referenced by LogDeath().
 {
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         int w = player.(weaponentity).m_weapon.m_id;
         if(w == 0)
             w = player.(weaponentity).cnt; // previous weapon
         if(w != 0 || slot == 0)
             s = strcat(s, ftos(w));
     }
     if(StatusEffects_active(STATUSEFFECT_Strength, player))
         s = strcat(s, "S");
     if(StatusEffects_active(STATUSEFFECT_Shield, player))
         s = strcat(s, "I");
     if(PHYS_INPUT_BUTTON_CHAT(player))
         s = strcat(s, "T");
     // TODO: include these codes as a flag on the item itself
     MUTATOR_CALLHOOK(LogDeath_AppendItemCodes, player, s);
     s = M_ARGV(1, string);
     return s;
 }
bool()
bool (entity targ, entity inflictor, float amount, float limit)
Damage()
void Damage (entity targ, entity inflictor, entity attacker, float damage, int deathtype, .entity weaponentity, vector hitloc, vector force)
Definition at line 587 of file damage.qc.
References ACTIVE_ACTIVE, autocvar_g_balance_armor_blockpercent, autocvar_g_balance_damagepush_speedfactor, autocvar_g_balance_selfdamagepercent, autocvar_g_friendlyfire, autocvar_g_friendlyfire_virtual, autocvar_g_friendlyfire_virtual_force, autocvar_g_frozen_damage_trigger, autocvar_g_frozen_force, autocvar_g_frozen_revive_falldamage, autocvar_g_frozen_revive_falldamage_health, autocvar_g_mirrordamage, autocvar_g_mirrordamage_onlyweapons, autocvar_g_mirrordamage_virtual, autocvar_g_teamdamage_threshold, autocvar_g_weapondamagefactor, autocvar_g_weaponforcefactor, autocvar_teamplay_mode, CS(), Damage(), DAMAGE_AIM, damage_explosion_calcpush(), DEAD_NO, DEATH_ISSPECIAL, DEATH_ISWEAPON, DEATH_WEAPONOF, DIFF_TEAM, EF_TELEPORT_BIT, entity(), FL_GODMODE, FORCETYPE_FORCEATPOS, FRAGS_SPECTATOR, GetResource(), HITTYPE_SOUND, hook, impressive_hits, IS_CLIENT, IS_DEAD, IS_INDEPENDENT_PLAYER, IS_MONSTER, IS_PLAYER, IS_TURRET, IS_VEHICLE, IsFlying(), ITEM_DAMAGE_NEEDKILL, killcount, M_ARGV, MAX_WEAPONSLOTS, MOVETYPE_NOCLIP, MOVETYPE_PHYSICS, MUTATOR_CALLHOOK, MUTATOR_IS_ENABLED, normalize(), NULL, PHYS_INPUT_BUTTON_CHAT, RemoveHook(), RES_ARMOR, RES_HEALTH, SAME_TEAM, SelectSpawnPoint(), setorigin(), SetResource(), SetResourceExplicit(), setthink, teamkill_complain, time, Unfreeze(), UNSET_ONGROUND, UpdateCSQCProjectile(), v, vector(), vehicles_exit(), vlen(), weaponentities, and yoda.
Referenced by buff_Vengeance_DelayedDamage(), checkpoint_passed(), ClientKill_Now(), CommonCommand_editmob(), CreatureFrame_FallDamage(), CreatureFrame_hotliquids(), ctf_CaptureShield_Touch(), Damage(), door_blocked(), door_generic_plat_blocked(), DrownPlayer(), Fire_ApplyDamage(), fireBullet_antilag(), generic_plat_blocked(), havocbot_role_ctf_carrier(), instagib_countdown(), KillPlayerForTeamChange(), Monster_Attack_Melee(), Monster_Move(), Monster_Think(), MUTATOR_HOOKFUNCTION(), ons_CaptureShield_Touch(), Onslaught_CheckWinner(), plat_crush(), RadiusDamageForSource(), vehicles_impact(), and vehicles_touch().
 {
     float complainteamdamage = 0;
     float mirrordamage = 0;
     float mirrorforce = 0;
     if (game_stopped || (IS_CLIENT(targ) && CS(targ).killcount == FRAGS_SPECTATOR))
         return;
     entity attacker_save = attacker;
     // special rule: gravity bombs and sound-based attacks do not affect team mates (other than for disconnecting the hook)
     if(DEATH_ISWEAPON(deathtype, WEP_HOOK) || (deathtype & HITTYPE_SOUND))
     {
         if(IS_PLAYER(targ) && SAME_TEAM(targ, attacker))
         {
             return;
         }
     }
     if(deathtype == DEATH_KILL.m_id || deathtype == DEATH_TEAMCHANGE.m_id || deathtype == DEATH_AUTOTEAMCHANGE.m_id)
     {
         // exit the vehicle before killing (fixes a crash)
         if(IS_PLAYER(targ) && targ.vehicle)
             vehicles_exit(targ.vehicle, VHEF_RELEASE);
         // These are ALWAYS lethal
         // No damage modification here
         // Instead, prepare the victim for his death...
         if(deathtype == DEATH_TEAMCHANGE.m_id || deathtype == DEATH_AUTOTEAMCHANGE.m_id)
         {
             SetResourceExplicit(targ, RES_ARMOR, 0);
             SetResourceExplicit(targ, RES_HEALTH, 0.9); // this is < 1
         }
         targ.spawnshieldtime = 0;
         targ.flags -= targ.flags & FL_GODMODE;
         damage = 100000;
     }
     else if(deathtype == DEATH_MIRRORDAMAGE.m_id || deathtype == DEATH_NOAMMO.m_id)
     {
         // no processing
     }
     else
     {
         // nullify damage if teamplay is on
         if(deathtype != DEATH_TELEFRAG.m_id)
         if(IS_PLAYER(attacker))
         {
             if(IS_PLAYER(targ) && targ != attacker && (IS_INDEPENDENT_PLAYER(attacker) || IS_INDEPENDENT_PLAYER(targ)))
             {
                 damage = 0;
                 force = '0 0 0';
             }
             else if(!STAT(FROZEN, targ) && SAME_TEAM(attacker, targ))
             {
                 if(autocvar_teamplay_mode == 1)
                     damage = 0;
                 else if(attacker != targ)
                 {
                     if(autocvar_teamplay_mode == 2)
                     {
                         if(IS_PLAYER(targ) && !IS_DEAD(targ))
{
                             attacker.dmg_team = attacker.dmg_team + damage;
                             complainteamdamage = attacker.dmg_team - autocvar_g_teamdamage_threshold;
                         }
                     }
                     else if(autocvar_teamplay_mode == 3)
                         damage = 0;
                     else if(autocvar_teamplay_mode == 4)
                     {
                         if(IS_PLAYER(targ) && !IS_DEAD(targ))
{
                             attacker.dmg_team = attacker.dmg_team + damage;
                             complainteamdamage = attacker.dmg_team - autocvar_g_teamdamage_threshold;
                             if(complainteamdamage > 0)
                                 mirrordamage = autocvar_g_mirrordamage * complainteamdamage;
                             mirrorforce = autocvar_g_mirrordamage * vlen(force);
                             damage = autocvar_g_friendlyfire * damage;
                             // mirrordamage will be used LATER
                             if(autocvar_g_mirrordamage_virtual)
{
                                 vector v  = healtharmor_applydamage(GetResource(attacker, RES_ARMOR), autocvar_g_balance_armor_blockpercent, deathtype, mirrordamage);
                                 attacker.dmg_take += v.x;
                                 attacker.dmg_save += v.y;
                                 attacker.dmg_inflictor = inflictor;
                                 mirrordamage = v.z;
                                 mirrorforce = 0;
                             }
                             if(autocvar_g_friendlyfire_virtual)
{
                                 vector v = healtharmor_applydamage(GetResource(targ, RES_ARMOR), autocvar_g_balance_armor_blockpercent, deathtype, damage);
                                 targ.dmg_take += v.x;
                                 targ.dmg_save += v.y;
                                 targ.dmg_inflictor = inflictor;
                                 damage = 0;
                                 if(!autocvar_g_friendlyfire_virtual_force)
                                     force = '0 0 0';
                             }
                         }
                         else if(!targ.canteamdamage)
                             damage = 0;
                     }
                 }
             }
         }
         if (!DEATH_ISSPECIAL(deathtype))
         {
             damage *= autocvar_g_weapondamagefactor;
             mirrordamage *= autocvar_g_weapondamagefactor;
             complainteamdamage *= autocvar_g_weapondamagefactor;
             force = force * autocvar_g_weaponforcefactor;
             mirrorforce *= autocvar_g_weaponforcefactor;
         }
         // should this be changed at all? If so, in what way?
         MUTATOR_CALLHOOK(Damage_Calculate, inflictor, attacker, targ, deathtype, damage, mirrordamage, force, attacker.(weaponentity));
         damage = M_ARGV(4, float);
         mirrordamage = M_ARGV(5, float);
         force = M_ARGV(6, vector);
         if(IS_PLAYER(targ) && damage > 0 && attacker)
         {
             for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
             {
                 .entity went = weaponentities[slot];
                 if(targ.(went).hook && targ.(went).hook.aiment == attacker)
                     RemoveHook(targ.(went).hook);
             }
         }
         if(STAT(FROZEN, targ) && !ITEM_DAMAGE_NEEDKILL(deathtype)
             && deathtype != DEATH_TEAMCHANGE.m_id && deathtype != DEATH_AUTOTEAMCHANGE.m_id)
         {
             if(autocvar_g_frozen_revive_falldamage > 0 && deathtype == DEATH_FALL.m_id && damage >= autocvar_g_frozen_revive_falldamage)
             {
                 Unfreeze(targ, false);
                 SetResource(targ, RES_HEALTH, autocvar_g_frozen_revive_falldamage_health);
                 Send_Effect(EFFECT_ICEORGLASS, targ.origin, '0 0 0', 3);
                 Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_FREEZETAG_REVIVED_FALL, targ.netname);
                 Send_Notification(NOTIF_ONE, targ, MSG_CENTER, CENTER_FREEZETAG_REVIVE_SELF);
             }
             damage = 0;
             force *= autocvar_g_frozen_force;
         }
         if(IS_PLAYER(targ) && STAT(FROZEN, targ)
             && ITEM_DAMAGE_NEEDKILL(deathtype) && !autocvar_g_frozen_damage_trigger)
         {
             Send_Effect(EFFECT_TELEPORT, targ.origin, '0 0 0', 1);
             entity spot = SelectSpawnPoint(targ, false);
             if(spot)
             {
                 damage = 0;
                 targ.deadflag = DEAD_NO;
                 targ.angles = spot.angles;
                 targ.effects = 0;
                 targ.effects |= EF_TELEPORT_BIT;
                 targ.angles_z = 0; // never spawn tilted even if the spot says to
                 targ.fixangle = true; // turn this way immediately
                 targ.velocity = '0 0 0';
                 targ.avelocity = '0 0 0';
                 targ.punchangle = '0 0 0';
                 targ.punchvector = '0 0 0';
                 targ.oldvelocity = targ.velocity;
                 targ.spawnorigin = spot.origin;
                 setorigin(targ, spot.origin + '0 0 1' * (1 - targ.mins.z - 24));
                 // don't reset back to last position, even if new position is stuck in solid
                 targ.oldorigin = targ.origin;
                 Send_Effect(EFFECT_TELEPORT, targ.origin, '0 0 0', 1);
             }
         }
         if(!MUTATOR_IS_ENABLED(mutator_instagib))
         {
             // apply strength multiplier
             if (attacker.items & ITEM_Strength.m_itemid)
             {
                 if(targ == attacker)
                 {
                     damage = damage * autocvar_g_balance_powerup_strength_selfdamage;
                     force = force * autocvar_g_balance_powerup_strength_selfforce;
                 }
                 else
                 {
                     damage = damage * autocvar_g_balance_powerup_strength_damage;
                     force = force * autocvar_g_balance_powerup_strength_force;
                 }
             }
             // apply invincibility multiplier
             if (targ.items & ITEM_Shield.m_itemid)
             {
                 damage = damage * autocvar_g_balance_powerup_invincible_takedamage;
                 if (targ != attacker)
                 {
                     force = force * autocvar_g_balance_powerup_invincible_takeforce;
                 }
             }
         }
         if (targ == attacker)
             damage = damage * autocvar_g_balance_selfdamagepercent; // Partial damage if the attacker hits himself
         // count the damage
         if(attacker)
         if(!IS_DEAD(targ))
         if(deathtype != DEATH_BUFF.m_id)
         if(targ.takedamage == DAMAGE_AIM)
         if(targ != attacker)
         {
             entity victim;
             if(IS_VEHICLE(targ) && targ.owner)
                 victim = targ.owner;
             else
                 victim = targ;
             if(IS_PLAYER(victim) || (IS_TURRET(victim) && victim.active == ACTIVE_ACTIVE) || IS_MONSTER(victim) || MUTATOR_CALLHOOK(PlayHitsound, victim, attacker))
             {
                 if (DIFF_TEAM(victim, attacker))
                 {
                     if(damage > 0)
                     {
                         if(deathtype != DEATH_FIRE.m_id)
{
                             if(PHYS_INPUT_BUTTON_CHAT(victim))
                                 attacker.typehitsound += 1;
                             else
                                 attacker.damage_dealt += damage;
                         }
                         impressive_hits += 1;
                         if (!DEATH_ISSPECIAL(deathtype))
{
                             if(IS_PLAYER(targ)) // don't do this for vehicles
                             if(IsFlying(victim))
                                 yoda = 1;
                         }
                     }
                 }
                 else if (IS_PLAYER(attacker) && !STAT(FROZEN, victim)) // same team
                 {
                     if (deathtype != DEATH_FIRE.m_id)
                     {
                         attacker.typehitsound += 1;
                     }
                     if(complainteamdamage > 0)
                         if(time > CS(attacker).teamkill_complain)
{
                             CS(attacker).teamkill_complain = time + 5;
                             CS(attacker).teamkill_soundtime = time + 0.4;
                             CS(attacker).teamkill_soundsource = targ;
                         }
                 }
             }
         }
     }
     // apply push
     if (targ.damageforcescale)
     if (force)
     if (!IS_PLAYER(targ) || time >= targ.spawnshieldtime || targ == attacker)
     {
         vector farce = damage_explosion_calcpush(targ.damageforcescale * force, targ.velocity, autocvar_g_balance_damagepush_speedfactor);
         if(targ.move_movetype == MOVETYPE_PHYSICS)
         {
             entity farcent = new(farce);
             farcent.enemy = targ;
             farcent.movedir = farce * 10;
             if(targ.mass)
                 farcent.movedir = farcent.movedir * targ.mass;
             farcent.origin = hitloc;
             farcent.forcetype = FORCETYPE_FORCEATPOS;
             farcent.nextthink = time + 0.1;
             setthink(farcent, SUB_Remove);
         }
         else if(targ.move_movetype != MOVETYPE_NOCLIP)
         {
             targ.velocity = targ.velocity + farce;
         }
         UNSET_ONGROUND(targ);
         UpdateCSQCProjectile(targ);
     }
     // apply damage
     if (damage != 0 || (targ.damageforcescale && force))
     if (targ.event_damage)
         targ.event_damage (targ, inflictor, attacker, damage, deathtype, weaponentity, hitloc, force);
     // apply mirror damage if any
     if(!autocvar_g_mirrordamage_onlyweapons || DEATH_WEAPONOF(deathtype) != WEP_Null)
     if(mirrordamage > 0 || mirrorforce > 0)
     {
         attacker = attacker_save;
         force = normalize(attacker.origin + attacker.view_ofs - hitloc) * mirrorforce;
         Damage(attacker, inflictor, attacker, mirrordamage, DEATH_MIRRORDAMAGE.m_id, weaponentity, attacker.origin, force);
     }
 }
Damage_DamageInfo()
void Damage_DamageInfo (vector org, float coredamage, float edgedamage, float rad, vector force, int deathtype, float bloodtype, entity dmgowner)
Referenced by fireBullet_antilag(), FireRailgunBullet(), and RadiusDamageForSource().
Damage_DamageInfo_SendEntity()
bool Damage_DamageInfo_SendEntity (entity this, entity to, int sf)
Fire_AddDamage()
float Fire_AddDamage (entity e, entity o, float d, float t, float dt)
Definition at line 1109 of file damage.qc.
References accuracy_add(), accuracy_isgooddamage(), DEATH_WEAPONOF, IS_DEAD, IS_PLAYER, max(), min(), and time.
Referenced by CreatureFrame_hotliquids(), and MUTATOR_HOOKFUNCTION().
 {
     float dps;
     float maxtime, mintime, maxdamage, mindamage, maxdps, mindps, totaldamage, totaltime;
     if(IS_PLAYER(e))
     {
         if(IS_DEAD(e))
             return -1;
     }
     t = max(t, 0.1);
     dps = d / t;
     if(StatusEffects_active(STATUSEFFECT_Burning, e))
     {
         float fireendtime = StatusEffects_gettime(STATUSEFFECT_Burning, e);
         mintime = fireendtime - time;
         maxtime = max(mintime, t);
         mindps = e.fire_damagepersec;
         maxdps = max(mindps, dps);
         if(maxtime > mintime || maxdps > mindps)
         {
             // Constraints:
             // damage we have right now
             mindamage = mindps * mintime;
             // damage we want to get
             maxdamage = mindamage + d;
             // but we can't exceed maxtime * maxdps!
             totaldamage = min(maxdamage, maxtime * maxdps);
             // LEMMA:
             // Look at:
             // totaldamage = min(mindamage + d, maxtime * maxdps)
             // We see:
             // totaldamage <= maxtime * maxdps
             // ==> totaldamage / maxdps <= maxtime.
             // We also see:
             // totaldamage / mindps = min(mindamage / mindps + d, maxtime * maxdps / mindps)
             //                     >= min(mintime, maxtime)
             // ==> totaldamage / maxdps >= mintime.
             /*
             // how long do we damage then?
             // at least as long as before
             // but, never exceed maxdps
             totaltime = max(mintime, totaldamage / maxdps); // always <= maxtime due to lemma
             */
             // alternate:
             // at most as long as maximum allowed
             // but, never below mindps
             totaltime = min(maxtime, totaldamage / mindps); // always >= mintime due to lemma
             // assuming t > mintime, dps > mindps:
             // we get d = t * dps = maxtime * maxdps
             // totaldamage = min(maxdamage, maxtime * maxdps) = min(... + d, maxtime * maxdps) = maxtime * maxdps
             // totaldamage / maxdps = maxtime
             // totaldamage / mindps > totaldamage / maxdps = maxtime
             // FROM THIS:
             // a) totaltime = max(mintime, maxtime) = maxtime
             // b) totaltime = min(maxtime, totaldamage / maxdps) = maxtime
             // assuming t <= mintime:
             // we get maxtime = mintime
             // a) totaltime = max(mintime, ...) >= mintime, also totaltime <= maxtime by the lemma, therefore totaltime = mintime = maxtime
             // b) totaltime = min(maxtime, ...) <= maxtime, also totaltime >= mintime by the lemma, therefore totaltime = mintime = maxtime
             // assuming dps <= mindps:
             // we get mindps = maxdps.
             // With this, the lemma says that mintime <= totaldamage / mindps = totaldamage / maxdps <= maxtime.
             // a) totaltime = max(mintime, totaldamage / maxdps) = totaldamage / maxdps
             // b) totaltime = min(maxtime, totaldamage / mindps) = totaldamage / maxdps
             e.fire_damagepersec = totaldamage / totaltime;
             StatusEffects_apply(STATUSEFFECT_Burning, e, time + totaltime, 0);
             if(totaldamage > 1.2 * mindamage)
             {
                 e.fire_deathtype = dt;
                 if(e.fire_owner != o)
                 {
                     e.fire_owner = o;
                     e.fire_hitsound = false;
                 }
             }
             if(accuracy_isgooddamage(o, e))
                 accuracy_add(o, DEATH_WEAPONOF(dt), 0, max(0, totaldamage - mindamage));
             return max(0, totaldamage - mindamage); // can never be negative, but to make sure
         }
         else
             return 0;
     }
     else
     {
         e.fire_damagepersec = dps;
         StatusEffects_apply(STATUSEFFECT_Burning, e, time + t, 0);
         e.fire_deathtype = dt;
         e.fire_owner = o;
         e.fire_hitsound = false;
         if(accuracy_isgooddamage(o, e))
             accuracy_add(o, DEATH_WEAPONOF(dt), 0, d);
         return d;
     }
 }
Fire_ApplyDamage()
void Fire_ApplyDamage (entity e)
Definition at line 1219 of file damage.qc.
References Damage(), DMG_NOWEP, entity(), frametime, g_damagedbycontents, IL_EACH, IS_INDEPENDENT_PLAYER, IS_NOT_A_CLIENT, min(), and time.
 {
     float t, d, hi, ty;
     entity o;
     for(t = 0, o = e.owner; o.owner && t < 16; o = o.owner, ++t);
     if(IS_NOT_A_CLIENT(o))
         o = e.fire_owner;
     float fireendtime = StatusEffects_gettime(STATUSEFFECT_Burning, e);
     t = min(frametime, fireendtime - time);
     d = e.fire_damagepersec * t;
     hi = e.fire_owner.damage_dealt;
     ty = e.fire_owner.typehitsound;
     Damage(e, e, e.fire_owner, d, e.fire_deathtype, DMG_NOWEP, e.origin, '0 0 0');
     if(e.fire_hitsound && e.fire_owner)
     {
         e.fire_owner.damage_dealt = hi;
         e.fire_owner.typehitsound = ty;
     }
     e.fire_hitsound = true;
     if(!IS_INDEPENDENT_PLAYER(e) && !STAT(FROZEN, e))
     {
         IL_EACH(g_damagedbycontents, it.damagedbycontents && it != e,
         {
             if(!IS_DEAD(it) && it.takedamage && !IS_INDEPENDENT_PLAYER(it))
             if(boxesoverlap(e.absmin, e.absmax, it.absmin, it.absmax))
             {
                 t = autocvar_g_balance_firetransfer_time * (fireendtime - time);
                 d = autocvar_g_balance_firetransfer_damage * e.fire_damagepersec * t;
                 Fire_AddDamage(it, o, d, t, DEATH_FIRE.m_id);
             }
         });
     }
 }
Freeze()
void Freeze (entity targ, float revivespeed, int frozen_type, bool show_waypoint)
Definition at line 498 of file damage.qc.
References entity(), floor(), FOREACH_CLIENT, Freeze(), FROZEN_TEMP_DYING, g_bot_targets, Ice_Think(), IL_REMOVE(), IS_MONSTER, IS_PLAYER, MAX_WEAPONSLOTS, MUTATOR_CALLHOOK, NULL, random(), RemoveGrapplingHooks(), RemoveHook(), RES_HEALTH, setmodel, SetResource(), setthink, start_health, Team_ColorRGB(), time, and weaponentities.
Referenced by Freeze(), and freezetag_Freeze().
 {
     if(!IS_PLAYER(targ) && !IS_MONSTER(targ)) // TODO: only specified entities can be freezed
         return;
     if(STAT(FROZEN, targ))
         return;
     float targ_maxhealth = ((IS_MONSTER(targ)) ? targ.max_health : start_health);
     STAT(FROZEN, targ) = frozen_type;
     STAT(REVIVE_PROGRESS, targ) = ((frozen_type == FROZEN_TEMP_DYING) ? 1 : 0);
     SetResource(targ, RES_HEALTH, ((frozen_type == FROZEN_TEMP_DYING) ? targ_maxhealth : 1));
     targ.revive_speed = revivespeed;
     if(targ.bot_attack)
         IL_REMOVE(g_bot_targets, targ);
     targ.bot_attack = false;
     targ.freeze_time = time;
     entity ice = new(ice);
     ice.owner = targ;
     ice.scale = targ.scale;
     // set_movetype(ice, MOVETYPE_FOLLOW) would rotate the ice model with the player
     setthink(ice, Ice_Think);
     ice.nextthink = time;
     ice.frame = floor(random() * 21); // ice model has 20 different looking frames
     setmodel(ice, MDL_ICE);
     ice.alpha = 1;
     ice.colormod = Team_ColorRGB(targ.team);
     ice.glowmod = ice.colormod;
     targ.iceblock = ice;
     targ.revival_time = 0;
     Ice_Think(ice);
     RemoveGrapplingHooks(targ);
     FOREACH_CLIENT(IS_PLAYER(it),
     {
         for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(it.(weaponentity).hook.aiment == targ)
                 RemoveHook(it.(weaponentity).hook);
         }
     });
     // add waypoint
     if(MUTATOR_CALLHOOK(Freeze, targ, revivespeed, frozen_type) || show_waypoint)
         WaypointSprite_Spawn(WP_Frozen, 0, 0, targ, '0 0 64', NULL, targ.team, targ, waypointsprite_attached, true, RADARICON_WAYPOINT);
 }
GiveFrags()
void GiveFrags (entity attacker, entity targ, float f, int deathtype, .entity weaponentity)
Definition at line 49 of file damage.qc.
References GameRules_scoring_add, M_ARGV, MUTATOR_CALLHOOK, UpdateFrags(), and warmup_stage.
Referenced by Obituary().
 {
     // TODO route through PlayerScores instead
     if(game_stopped) return;
     if(f < 0)
     {
         if(targ == attacker)
         {
             // suicide
             GameRules_scoring_add(attacker, SUICIDES, 1);
         }
         else
         {
             // teamkill
             GameRules_scoring_add(attacker, TEAMKILLS, 1);
         }
     }
     else
     {
         // regular frag
         GameRules_scoring_add(attacker, KILLS, 1);
         if(!warmup_stage && targ.playerid)
             PlayerStats_GameReport_Event_Player(attacker, sprintf("kills-%d", targ.playerid), 1);
     }
     GameRules_scoring_add(targ, DEATHS, 1);
     // FIXME fix the mess this is (we have REAL points now!)
     if(MUTATOR_CALLHOOK(GiveFragsForKill, attacker, targ, f, deathtype, attacker.(weaponentity)))
         f = M_ARGV(2, float);
     attacker.totalfrags += f;
     if(f)
         UpdateFrags(attacker, f);
 }
Heal()
bool Heal (entity targ, entity inflictor, float amount, float limit)
Definition at line 1095 of file damage.qc.
References CS(), FRAGS_SPECTATOR, IS_CLIENT, IS_DEAD, and killcount.
 {
     if(game_stopped || (IS_CLIENT(targ) && CS(targ).killcount == FRAGS_SPECTATOR) || STAT(FROZEN, targ) || IS_DEAD(targ))
         return false;
     bool healed = false;
     if(targ.event_heal)
         healed = targ.event_heal(targ, inflictor, amount, limit);
     // TODO: additional handling? what if the healing kills them? should this abort if healing would do so etc
     // TODO: healing fx!
     // TODO: armor healing?
     return healed;
 }
Ice_Think()
void Ice_Think (entity this)
Definition at line 485 of file damage.qc.
References nextthink, origin, owner, setorigin(), time, and vector().
Referenced by Freeze().
 {
     if(!STAT(FROZEN, this.owner) || this.owner.iceblock != this)
     {
         delete(this);
         return;
     }
     vector ice_org = this.owner.origin - '0 0 16';
     if (this.origin != ice_org)
         setorigin(this, ice_org);
     this.nextthink = time;
 }
IsFlying()
float IsFlying (entity a)
Definition at line 798 of file player.qc.
References CS(), CSQC_ClientMovement_PlayerMove_Frame(), csqcmodel_modelflags, entity(), frametime, intermission, IS_DEAD, IS_ONGROUND, IS_REAL_CLIENT, ITEMS_STAT, maxs, MF_ROCKET, mins, MOVE_NORMAL, origin, PM_UpdateButtons(), sys_phys_update(), trace_fraction, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by Damage(), and sys_phys_update().
 {
     if(IS_ONGROUND(this))
         return false;
     if(this.waterlevel >= WATERLEVEL_SWIMMING)
         return false;
     tracebox(this.origin, this.mins, this.maxs, this.origin - '0 0 24', MOVE_NORMAL, this);
     //traceline(this.origin, this.origin - '0 0 48', MOVE_NORMAL, this);
     if(trace_fraction < 1)
         return false;
     return true;
 }
LogDeath()
void LogDeath (string mode, int deathtype, entity killer, entity killed)
Definition at line 110 of file damage.qc.
References AppendItemcodes(), autocvar_sv_eventlog, Deathtype_Name(), ftos(), GameLogEcho(), and strcat().
Referenced by Obituary().
 {
     string s;
     if(!autocvar_sv_eventlog)
         return;
     s = strcat(":kill:", mode);
     s = strcat(s, ":", ftos(killer.playerid));
     s = strcat(s, ":", ftos(killed.playerid));
     s = strcat(s, ":type=", Deathtype_Name(deathtype));
     s = strcat(s, ":items=");
     s = AppendItemcodes(s, killer);
     if(killed != killer)
     {
         s = strcat(s, ":victimitems=");
         s = AppendItemcodes(s, killed);
     }
     GameLogEcho(s);
 }
Obituary()
void Obituary (entity attacker, entity inflictor, entity targ, int deathtype, .entity weaponentity)
Definition at line 233 of file damage.qc.
References APP_TEAM_NUM, backtrace, buff_FirstFromFlags(), checkrules_firstblood, CS(), DEATH_ENT, DEATH_ISSPECIAL, deathmessage, Deathtype_Name(), frag_centermessage_override(), GameRules_scoring_add, GetResource(), GiveFrags(), IS_BOT_CLIENT, IS_PLAYER, KILL_SPREE_LIST, killcount, LogDeath(), M_ARGV, MUTATOR_CALLHOOK, NearestLocation(), NULL, Obituary_SpecialDeath(), Obituary_WeaponDeath(), ping, RES_ARMOR, RES_HEALTH, SAME_TEAM, strcat(), strstrofs, time, and warmup_stage.
Referenced by PlayerDamage().
 {
     // Sanity check
     if (!IS_PLAYER(targ)) { backtrace("Obituary called on non-player?!\n"); return; }
     // Declarations
     float notif_firstblood = false;
     float kill_count_to_attacker, kill_count_to_target;
     bool notif_anonymous = false;
     string attacker_name = attacker.netname;
     // Set final information for the death
     targ.death_origin = targ.origin;
     string deathlocation = (autocvar_notification_server_allows_location ? NearestLocation(targ.death_origin) : "");
     // Abort now if a mutator requests it
     if (MUTATOR_CALLHOOK(ClientObituary, inflictor, attacker, targ, deathtype, attacker.(weaponentity))) { CS(targ).killcount = 0; return; }
     notif_anonymous = M_ARGV(5, bool);
     if(notif_anonymous)
         attacker_name = "Anonymous player";
     #ifdef NOTIFICATIONS_DEBUG
     Debug_Notification(
         sprintf(
             "Obituary(%s, %s, %s, %s = %d);\n",
             attacker_name,
             inflictor.netname,
             targ.netname,
             Deathtype_Name(deathtype),
             deathtype
         )
     );
     #endif
     // =======
     // SUICIDE
     // =======
     if(targ == attacker)
     {
         if(DEATH_ISSPECIAL(deathtype))
         {
             if(deathtype == DEATH_TEAMCHANGE.m_id || deathtype == DEATH_AUTOTEAMCHANGE.m_id)
             {
                 Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", targ.team, 0, 0);
             }
             else
             {
                 switch(DEATH_ENT(deathtype))
                 {
                     case DEATH_MIRRORDAMAGE:
                     {
                         Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", CS(targ).killcount, 0, 0);
                         break;
                     }
                     case DEATH_HURTTRIGGER:
                         Obituary_SpecialDeath(targ, false, deathtype, targ.netname, inflictor.message, deathlocation, CS(targ).killcount, 0, 0);
                         break;
                     default:
                     {
                         Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", CS(targ).killcount, 0, 0);
                         break;
                     }
                 }
             }
         }
         else if (!Obituary_WeaponDeath(targ, false, deathtype, targ.netname, deathlocation, "", CS(targ).killcount, 0))
         {
             backtrace("SUICIDE: what the hell happened here?\n");
             return;
         }
         LogDeath("suicide", deathtype, targ, targ);
         if(deathtype != DEATH_AUTOTEAMCHANGE.m_id) // special case: don't negate frags if auto switched
             GiveFrags(attacker, targ, -1, deathtype, weaponentity);
     }
     // ======
     // MURDER
     // ======
     else if(IS_PLAYER(attacker))
     {
         if(SAME_TEAM(attacker, targ))
         {
             LogDeath("tk", deathtype, attacker, targ);
             GiveFrags(attacker, targ, -1, deathtype, weaponentity);
             CS(attacker).killcount = 0;
             Send_Notification(NOTIF_ONE, attacker, MSG_CENTER, CENTER_DEATH_TEAMKILL_FRAG, targ.netname);
             Send_Notification(NOTIF_ONE, targ, MSG_CENTER, CENTER_DEATH_TEAMKILL_FRAGGED, attacker_name);
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(targ.team, INFO_DEATH_TEAMKILL), targ.netname, attacker_name, deathlocation, CS(targ).killcount);
             // In this case, the death message will ALWAYS be "foo was betrayed by bar"
             // No need for specific death/weapon messages...
         }
         else
         {
             LogDeath("frag", deathtype, attacker, targ);
             GiveFrags(attacker, targ, 1, deathtype, weaponentity);
             CS(attacker).taunt_soundtime = time + 1;
             CS(attacker).killcount = CS(attacker).killcount + 1;
             attacker.killsound += 1;
             // TODO: improve SPREE_ITEM and KILL_SPREE_LIST
             // these 2 macros are spread over multiple files
             #define SPREE_ITEM(counta,countb,center,normal,gentle) \
                 case counta: \
                     Send_Notification(NOTIF_ONE, attacker, MSG_ANNCE, ANNCE_KILLSTREAK_##countb); \
                     if (!warmup_stage) \
                         PlayerStats_GameReport_Event_Player(attacker, PLAYERSTATS_ACHIEVEMENT_KILL_SPREE_##counta, 1); \
                     break;
             switch(CS(attacker).killcount)
             {
                 KILL_SPREE_LIST
                 default: break;
             }
             #undef SPREE_ITEM
             if(!warmup_stage && !checkrules_firstblood)
             {
                 checkrules_firstblood = true;
                 notif_firstblood = true; // modify the current messages so that they too show firstblood information
                 PlayerStats_GameReport_Event_Player(attacker, PLAYERSTATS_ACHIEVEMENT_FIRSTBLOOD, 1);
                 PlayerStats_GameReport_Event_Player(targ, PLAYERSTATS_ACHIEVEMENT_FIRSTVICTIM, 1);
                 // tell spree_inf and spree_cen that this is a first-blood and first-victim event
                 kill_count_to_attacker = -1;
                 kill_count_to_target = -2;
             }
             else
             {
                 kill_count_to_attacker = CS(attacker).killcount;
                 kill_count_to_target = 0;
             }
             if(targ.istypefrag)
             {
                 Send_Notification(
                     NOTIF_ONE,
                     attacker,
                     MSG_CHOICE,
                     CHOICE_TYPEFRAG,
                     targ.netname,
                     kill_count_to_attacker,
                     (IS_BOT_CLIENT(targ) ? -1 : CS(targ).ping)
                 );
                 Send_Notification(
                     NOTIF_ONE,
                     targ,
                     MSG_CHOICE,
                     CHOICE_TYPEFRAGGED,
                     attacker_name,
                     kill_count_to_target,
                     GetResource(attacker, RES_HEALTH),
                     GetResource(attacker, RES_ARMOR),
                     (IS_BOT_CLIENT(attacker) ? -1 : CS(attacker).ping)
                 );
             }
             else if(!frag_centermessage_override(attacker, targ, deathtype, kill_count_to_attacker, kill_count_to_target, attacker_name))
             {
                 Send_Notification(
                     NOTIF_ONE,
                     attacker,
                     MSG_CHOICE,
                     CHOICE_FRAG,
                     targ.netname,
                     kill_count_to_attacker,
                     (IS_BOT_CLIENT(targ) ? -1 : CS(targ).ping)
                 );
                 Send_Notification(
                     NOTIF_ONE,
                     targ,
                     MSG_CHOICE,
                     CHOICE_FRAGGED,
                     attacker_name,
                     kill_count_to_target,
                     GetResource(attacker, RES_HEALTH),
                     GetResource(attacker, RES_ARMOR),
                     (IS_BOT_CLIENT(attacker) ? -1 : CS(attacker).ping)
                 );
             }
             int f3 = 0;
             if(deathtype == DEATH_BUFF.m_id)
                 f3 = buff_FirstFromFlags(attacker).m_id;
             if (!Obituary_WeaponDeath(targ, true, deathtype, targ.netname, attacker_name, deathlocation, CS(targ).killcount, kill_count_to_attacker))
                 Obituary_SpecialDeath(targ, true, deathtype, targ.netname, attacker_name, deathlocation, CS(targ).killcount, kill_count_to_attacker, f3);
         }
     }
     // =============
     // ACCIDENT/TRAP
     // =============
     else
     {
         switch(DEATH_ENT(deathtype))
         {
             // For now, we're just forcing HURTTRIGGER to behave as "DEATH_VOID" and giving it no special options...
             // Later on you will only be able to make custom messages using DEATH_CUSTOM,
             // and there will be a REAL DEATH_VOID implementation which mappers will use.
             case DEATH_HURTTRIGGER:
             {
                 Obituary_SpecialDeath(targ, false, deathtype,
                     targ.netname,
                     inflictor.message,
                     deathlocation,
                     CS(targ).killcount,
                     0,
                     0);
                 break;
             }
             case DEATH_CUSTOM:
             {
                 Obituary_SpecialDeath(targ, false, deathtype,
                     targ.netname,
                     ((strstrofs(deathmessage, "%", 0) < 0) ? strcat("%s ", deathmessage) : deathmessage),
                     deathlocation,
                     CS(targ).killcount,
                     0,
                     0);
                 break;
             }
             default:
             {
                 Obituary_SpecialDeath(targ, false, deathtype, targ.netname, deathlocation, "", CS(targ).killcount, 0, 0);
                 break;
             }
         }
         LogDeath("accident", deathtype, targ, targ);
         GiveFrags(targ, targ, -1, deathtype, weaponentity);
         if(GameRules_scoring_add(targ, SCORE, 0) == -5)
         {
             Send_Notification(NOTIF_ONE, targ, MSG_ANNCE, ANNCE_ACHIEVEMENT_BOTLIKE);
             if (!warmup_stage)
             {
                 PlayerStats_GameReport_Event_Player(attacker, PLAYERSTATS_ACHIEVEMENT_BOTLIKE, 1);
             }
         }
     }
     // reset target kill count
     CS(targ).killcount = 0;
 }
Obituary_SpecialDeath()
void Obituary_SpecialDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2, float f3)
Definition at line 129 of file damage.qc.
References backtrace, DEATH_ISSPECIAL, DT_FIRST, entity(), g_cts, and REGISTRY_GET.
Referenced by Obituary().
 {
     if(!DEATH_ISSPECIAL(deathtype))
     {
         backtrace("Obituary_SpecialDeath called without a special deathtype?\n");
         return;
     }
     entity deathent = REGISTRY_GET(Deathtypes, deathtype - DT_FIRST);
     if (!deathent)
     {
         backtrace("Obituary_SpecialDeath: Could not find deathtype entity!\n");
         return;
     }
     if(g_cts && deathtype == DEATH_KILL.m_id)
         return; // TODO: somehow put this in CTS gamemode file!
     Notification death_message = (murder) ? deathent.death_msgmurder : deathent.death_msgself;
     if(death_message)
     {
         Send_Notification_WOCOVA(
             NOTIF_ONE,
             notif_target,
             MSG_MULTI,
             death_message,
             s1, s2, s3, "",
             f1, f2, f3, 0
         );
         Send_Notification_WOCOVA(
             NOTIF_ALL_EXCEPT,
             notif_target,
             MSG_INFO,
             death_message.nent_msginfo,
             s1, s2, s3, "",
             f1, f2, f3, 0
         );
     }
 }
Obituary_WeaponDeath()
float Obituary_WeaponDeath (entity notif_target, float murder, int deathtype, string s1, string s2, string s3, float f1, float f2)
Definition at line 174 of file damage.qc.
References DEATH_WEAPONOF, LOG_TRACEF, Weapon::netname, and w_deathtype.
Referenced by Obituary().
 {
     Weapon death_weapon = DEATH_WEAPONOF(deathtype);
     if (death_weapon == WEP_Null)
         return false;
     w_deathtype = deathtype;
     Notification death_message = ((murder) ? death_weapon.wr_killmessage(death_weapon) : death_weapon.wr_suicidemessage(death_weapon));
     w_deathtype = false;
     if (death_message)
     {
         Send_Notification_WOCOVA(
             NOTIF_ONE,
             notif_target,
             MSG_MULTI,
             death_message,
             s1, s2, s3, "",
             f1, f2, 0, 0
         );
         // send the info part to everyone
         Send_Notification_WOCOVA(
             NOTIF_ALL_EXCEPT,
             notif_target,
             MSG_INFO,
             death_message.nent_msginfo,
             s1, s2, s3, "",
             f1, f2, 0, 0
         );
     }
     else
     {
         LOG_TRACEF(
             "Obituary_WeaponDeath(): ^1Deathtype ^7(%d)^1 has no notification for weapon %s!\n",
             deathtype,
             death_weapon.netname
         );
     }
     return true;
 }
RadiusDamage()
float RadiusDamage (entity inflictor, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float forceintensity, int deathtype, .entity weaponentity, entity directhitentity)
Definition at line 1089 of file damage.qc.
References RadiusDamageForSource().
Referenced by CheatImpulse(), PlayerTouchExplode(), and vehicles_projectile_explode().
 {
     return RadiusDamageForSource(inflictor, (inflictor.origin + (inflictor.mins + inflictor.maxs) * 0.5), inflictor.velocity, attacker, coredamage, edgedamage, rad,
                                     cantbe, mustbe, false, forceintensity, 1, deathtype, weaponentity, directhitentity);
 }
RadiusDamageForSource()
float RadiusDamageForSource (entity inflictor, vector inflictororigin, vector inflictorvelocity, entity attacker, float coredamage, float edgedamage, float rad, entity cantbe, entity mustbe, float inflictorselfdamage, float forceintensity, float forcezscale, int deathtype, .entity weaponentity, entity directhitentity)
Definition at line 898 of file damage.qc.
References accuracy_add(), accuracy_isgooddamage(), autocvar_g_throughfloor_damage, autocvar_g_throughfloor_damage_max_stddev, autocvar_g_throughfloor_debug, autocvar_g_throughfloor_force, autocvar_g_throughfloor_force_max_stddev, autocvar_g_throughfloor_max_steps_other, autocvar_g_throughfloor_max_steps_player, autocvar_g_throughfloor_min_steps_other, autocvar_g_throughfloor_min_steps_player, backtrace, bound(), ceil(), CENTER_OR_VIEWOFS, Damage(), Damage_DamageInfo(), DEATH_ISSPECIAL, DEATH_WEAPONOF, entity(), HITTYPE_BOUNCE, HITTYPE_SECONDARY, HITTYPE_SOUND, HITTYPE_SPLASH, IS_PLAYER, LOG_INFOF, max(), MAX_DAMAGEEXTRARADIUS, min(), MIN_DAMAGEEXTRARADIUS, MOVE_NOMONSTERS, next, normalize(), RadiusDamage_running, random(), sqrt(), trace_ent, trace_fraction, vector(), vlen(), WarpZone_FindRadius(), WarpZone_TraceLine(), WarpZone_TransformOrigin(), and WarpZone_UnTransformOrigin().
Referenced by RadiusDamage().
 {
     entity  targ;
     vector  force;
     float   total_damage_to_creatures;
     entity  next;
     float   tfloordmg;
     float   tfloorforce;
     float stat_damagedone;
     if(RadiusDamage_running)
     {
         backtrace("RadiusDamage called recursively! Expect stuff to go HORRIBLY wrong.");
         return 0;
     }
     RadiusDamage_running = 1;
     tfloordmg = autocvar_g_throughfloor_damage;
     tfloorforce = autocvar_g_throughfloor_force;
     total_damage_to_creatures = 0;
     if(deathtype != (WEP_HOOK.m_id | HITTYPE_SECONDARY | HITTYPE_BOUNCE)) // only send gravity bomb damage once
         if(!(deathtype & HITTYPE_SOUND)) // do not send radial sound damage (bandwidth hog)
         {
             force = inflictorvelocity;
             if(force == '0 0 0')
                 force = '0 0 -1';
             else
                 force = normalize(force);
             if(forceintensity >= 0)
                 Damage_DamageInfo(inflictororigin, coredamage, edgedamage, rad, forceintensity * force, deathtype, 0, attacker);
             else
                 Damage_DamageInfo(inflictororigin, coredamage, edgedamage, -rad, (-forceintensity) * force, deathtype, 0, attacker);
         }
     stat_damagedone = 0;
     targ = WarpZone_FindRadius (inflictororigin, rad + MAX_DAMAGEEXTRARADIUS, false);
     while (targ)
     {
         next = targ.chain;
         if ((targ != inflictor) || inflictorselfdamage)
         if (((cantbe != targ) && !mustbe) || (mustbe == targ))
         if (targ.takedamage)
         {
             vector nearest;
             vector diff;
             float power;
             // LordHavoc: measure distance to nearest point on target (not origin)
             // (this guarentees 100% damage on a touch impact)
             nearest = targ.WarpZone_findradius_nearest;
             diff = targ.WarpZone_findradius_dist;
             // round up a little on the damage to ensure full damage on impacts
             // and turn the distance into a fraction of the radius
             power = 1 - ((vlen (diff) - bound(MIN_DAMAGEEXTRARADIUS, targ.damageextraradius, MAX_DAMAGEEXTRARADIUS)) / rad);
             //bprint(" ");
             //bprint(ftos(power));
             //if (targ == attacker)
             //  print(ftos(power), "\n");
             if (power > 0)
             {
                 float finaldmg;
                 if (power > 1)
                     power = 1;
                 finaldmg = coredamage * power + edgedamage * (1 - power);
                 if (finaldmg > 0)
                 {
                     float a;
                     float c;
                     vector hitloc;
                     vector myblastorigin;
                     vector center;
                     myblastorigin = WarpZone_TransformOrigin(targ, inflictororigin);
                     // if it's a player, use the view origin as reference
                     center = CENTER_OR_VIEWOFS(targ);
                     force = normalize(center - myblastorigin);
                     force = force * (finaldmg / coredamage) * forceintensity;
                     hitloc = nearest;
                     // apply special scaling along the z axis if set
                     // NOTE: 0 value is not allowed for compatibility, in the case of weapon cvars not being set
                     if(forcezscale)
                         force.z *= forcezscale;
                     if(targ != directhitentity)
                     {
                         float hits;
                         float total;
                         float hitratio;
                         float mininv_f, mininv_d;
                         // test line of sight to multiple positions on box,
                         // and do damage if any of them hit
                         hits = 0;
                         // we know: max stddev of hitratio = 1 / (2 * sqrt(n))
                         // so for a given max stddev:
                         // n = (1 / (2 * max stddev of hitratio))^2
                         mininv_d = (finaldmg * (1-tfloordmg)) / autocvar_g_throughfloor_damage_max_stddev;
                         mininv_f = (vlen(force) * (1-tfloorforce)) / autocvar_g_throughfloor_force_max_stddev;
                         if(autocvar_g_throughfloor_debug)
                             LOG_INFOF("THROUGHFLOOR: D=%f F=%f max(dD)=1/%f max(dF)=1/%f", finaldmg, vlen(force), mininv_d, mininv_f);
                         total = 0.25 * (max(mininv_f, mininv_d) ** 2);
                         if(autocvar_g_throughfloor_debug)
                             LOG_INFOF(" steps=%f", total);
                         if (IS_PLAYER(targ))
                             total = ceil(bound(autocvar_g_throughfloor_min_steps_player, total, autocvar_g_throughfloor_max_steps_player));
                         else
                             total = ceil(bound(autocvar_g_throughfloor_min_steps_other, total, autocvar_g_throughfloor_max_steps_other));
                         if(autocvar_g_throughfloor_debug)
                             LOG_INFOF(" steps=%f dD=%f dF=%f", total, finaldmg * (1-tfloordmg) / (2 * sqrt(total)), vlen(force) * (1-tfloorforce) / (2 * sqrt(total)));
                         for(c = 0; c < total; ++c)
{
                             //traceline(targ.WarpZone_findradius_findorigin, nearest, MOVE_NOMONSTERS, inflictor);
                             WarpZone_TraceLine(inflictororigin, WarpZone_UnTransformOrigin(targ, nearest), MOVE_NOMONSTERS, inflictor);
                             if (trace_fraction == 1 || trace_ent == targ)
{
                                 ++hits;
                                 if (hits > 1)
                                     hitloc = hitloc + nearest;
                                 else
                                     hitloc = nearest;
                             }
                             nearest.x = targ.origin.x + targ.mins.x + random() * targ.size.x;
                             nearest.y = targ.origin.y + targ.mins.y + random() * targ.size.y;
                             nearest.z = targ.origin.z + targ.mins.z + random() * targ.size.z;
                         }
                         nearest = hitloc * (1 / max(1, hits));
                         hitratio = (hits / total);
                         a = bound(0, tfloordmg + (1-tfloordmg) * hitratio, 1);
                         finaldmg = finaldmg * a;
                         a = bound(0, tfloorforce + (1-tfloorforce) * hitratio, 1);
                         force = force * a;
                         if(autocvar_g_throughfloor_debug)
                             LOG_INFOF(" D=%f F=%f", finaldmg, vlen(force));
                     }
                     //if (targ == attacker)
                     //{
                     //  print("hits ", ftos(hits), " / ", ftos(total));
                     //  print(" finaldmg ", ftos(finaldmg), " force ", vtos(force));
                     //  print(" (", ftos(a), ")\n");
                     //}
                     if(finaldmg || force)
                     {
                         if(targ.iscreature)
{
                             total_damage_to_creatures += finaldmg;
                             if(accuracy_isgooddamage(attacker, targ))
                                 stat_damagedone += finaldmg;
                         }
                         if(targ == directhitentity || DEATH_ISSPECIAL(deathtype))
                             Damage(targ, inflictor, attacker, finaldmg, deathtype, weaponentity, nearest, force);
                         else
                             Damage(targ, inflictor, attacker, finaldmg, deathtype | HITTYPE_SPLASH, weaponentity, nearest, force);
                     }
                 }
             }
         }
         targ = next;
     }
     RadiusDamage_running = 0;
     if(!DEATH_ISSPECIAL(deathtype))
         accuracy_add(attacker, DEATH_WEAPONOF(deathtype), 0, min(coredamage, stat_damagedone));
     return total_damage_to_creatures;
 }
STATIC_INIT()
STATIC_INIT (g_damagedbycontents)
Definition at line 156 of file damage.qh.
References IL_NEW.
 { g_damagedbycontents = IL_NEW(); }
Unfreeze()
void Unfreeze (entity targ, bool reset_health)
Definition at line 550 of file damage.qc.
References autocvar_g_balance_pause_health_regen, FOREACH_CLIENT, FROZEN_TEMP_DYING, g_bot_targets, IL_PUSH(), IS_PLAYER, MAX_WEAPONSLOTS, MUTATOR_CALLHOOK, NULL, RemoveHook(), RES_HEALTH, SetResource(), start_health, time, Unfreeze(), and weaponentities.
Referenced by ClientDisconnect(), Damage(), ft_RemovePlayer(), Monster_Dead(), Monster_Frozen_Think(), Monster_Reset(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), PlayerPreThink(), PutObserverInServer(), PutPlayerInServer(), reset_map(), and Unfreeze().
 {
     if(!STAT(FROZEN, targ))
         return;
     if (reset_health && STAT(FROZEN, targ) != FROZEN_TEMP_DYING)
         SetResource(targ, RES_HEALTH, ((IS_PLAYER(targ)) ? start_health : targ.max_health));
     targ.pauseregen_finished = time + autocvar_g_balance_pause_health_regen;
     STAT(FROZEN, targ) = 0;
     STAT(REVIVE_PROGRESS, targ) = 0;
     targ.revival_time = time;
     if(!targ.bot_attack)
         IL_PUSH(g_bot_targets, targ);
     targ.bot_attack = true;
     WaypointSprite_Kill(targ.waypointsprite_attached);
     FOREACH_CLIENT(IS_PLAYER(it),
     {
         for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(it.(weaponentity).hook.aiment == targ)
                 RemoveHook(it.(weaponentity).hook);
         }
     });
     // remove the ice block
     if(targ.iceblock)
         delete(targ.iceblock);
     targ.iceblock = NULL;
     MUTATOR_CALLHOOK(Unfreeze, targ);
 }
UpdateFrags()
void UpdateFrags (entity player, int f)
Definition at line 44 of file damage.qc.
References GameRules_scoring_add_team.
Referenced by GiveFrags(), and kh_Scores_Event().
 {
     GameRules_scoring_add_team(player, SCORE, f);
 }
void()
void (entity this, entity inflictor, entity attacker, float damage, int deathtype, .entity weaponentity, vector hitloc, vector force)
W_SwitchWeapon_Force()
void W_SwitchWeapon_Force (Player this, Weapon w, .entity weaponentity)
Definition at line 243 of file selection.qc.
Referenced by GiveItems(), Item_GiveTo(), MUTATOR_HOOKFUNCTION(), TEST(), W_ThrowWeapon(), and W_WeaponFrame().
 {
     TC(Weapon, wep);
     entity w_ent = this.(weaponentity);
     w_ent.cnt = w_ent.m_switchweapon.m_id;
     w_ent.m_switchweapon = wep;
     w_ent.selectweapon = wep.m_id;
 }
Variable Documentation
autocvar_g_balance_armor_blockpercent
float autocvar_g_balance_armor_blockpercent
Definition at line 21 of file damage.qh.
Referenced by ClientInit_CheckUpdate(), ctf_FlagcarrierWaypoints(), Damage(), MUTATOR_HOOKFUNCTION(), PlayerCorpseDamage(), PlayerDamage(), and PlayerPostThink().
autocvar_g_balance_damagepush_speedfactor
float autocvar_g_balance_damagepush_speedfactor
Definition at line 18 of file damage.qh.
Referenced by ClientInit_CheckUpdate(), Damage(), and MUTATOR_HOOKFUNCTION().
autocvar_g_balance_firetransfer_damage
int autocvar_g_balance_firetransfer_damage
Definition at line 19 of file damage.qh.
autocvar_g_balance_firetransfer_time
int autocvar_g_balance_firetransfer_time
Definition at line 20 of file damage.qh.
autocvar_g_balance_selfdamagepercent
float autocvar_g_balance_selfdamagepercent
Definition at line 24 of file damage.qh.
Referenced by Damage().
autocvar_g_friendlyfire
float autocvar_g_friendlyfire
Definition at line 25 of file damage.qh.
Referenced by Damage(), and MUTATOR_HOOKFUNCTION().
autocvar_g_friendlyfire_virtual
float autocvar_g_friendlyfire_virtual
Definition at line 26 of file damage.qh.
Referenced by Damage().
autocvar_g_friendlyfire_virtual_force
float autocvar_g_friendlyfire_virtual_force
Definition at line 27 of file damage.qh.
Referenced by Damage().
autocvar_g_frozen_damage_trigger
bool autocvar_g_frozen_damage_trigger
Definition at line 30 of file damage.qh.
Referenced by Damage().
autocvar_g_frozen_force
float autocvar_g_frozen_force
Definition at line 31 of file damage.qh.
Referenced by Damage().
autocvar_g_frozen_revive_falldamage
float autocvar_g_frozen_revive_falldamage
Definition at line 28 of file damage.qh.
Referenced by Damage().
autocvar_g_frozen_revive_falldamage_health
int autocvar_g_frozen_revive_falldamage_health
Definition at line 29 of file damage.qh.
Referenced by Damage().
autocvar_g_maxpushtime
float autocvar_g_maxpushtime
Definition at line 17 of file damage.qh.
Referenced by GrapplingHook_Damage(), GrapplingHookThink(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), Portal_TeleportPlayer(), and TeleportPlayer().
autocvar_g_mirrordamage
float autocvar_g_mirrordamage
Definition at line 14 of file damage.qh.
Referenced by Damage().
autocvar_g_mirrordamage_onlyweapons
bool autocvar_g_mirrordamage_onlyweapons
Definition at line 16 of file damage.qh.
Referenced by Damage().
autocvar_g_mirrordamage_virtual
bool autocvar_g_mirrordamage_virtual
Definition at line 15 of file damage.qh.
Referenced by Damage().
autocvar_g_teamdamage_resetspeed
float autocvar_g_teamdamage_resetspeed
Definition at line 22 of file damage.qh.
Referenced by PlayerThink().
autocvar_g_teamdamage_threshold
float autocvar_g_teamdamage_threshold
Definition at line 23 of file damage.qh.
Referenced by Damage().
autocvar_g_throughfloor_damage
float autocvar_g_throughfloor_damage
Definition at line 6 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_damage_max_stddev
float autocvar_g_throughfloor_damage_max_stddev
Definition at line 8 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_debug
bool autocvar_g_throughfloor_debug
Definition at line 5 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_force
float autocvar_g_throughfloor_force
Definition at line 7 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_force_max_stddev
float autocvar_g_throughfloor_force_max_stddev
Definition at line 9 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_max_steps_other
float autocvar_g_throughfloor_max_steps_other
Definition at line 13 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_max_steps_player
float autocvar_g_throughfloor_max_steps_player
Definition at line 11 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_min_steps_other
float autocvar_g_throughfloor_min_steps_other
Definition at line 12 of file damage.qh.
Referenced by RadiusDamageForSource().
autocvar_g_throughfloor_min_steps_player
float autocvar_g_throughfloor_min_steps_player
Definition at line 10 of file damage.qh.
Referenced by RadiusDamageForSource().
canteamdamage
bool canteamdamage
Definition at line 68 of file damage.qh.
checkrules_firstblood
float checkrules_firstblood
Definition at line 46 of file damage.qh.
Referenced by Obituary().
damage_dealt
float damage_dealt
Definition at line 72 of file damage.qh.
damagedbycontents
float damagedbycontents
Definition at line 48 of file damage.qh.
Referenced by CopyBody(), ka_TouchEvent(), Monster_Spawn(), PlayerCorpseDamage(), PutObserverInServer(), PutPlayerInServer(), respawn(), vehicle_initialize(), and vehicles_spawn().
damagedbytriggers
float damagedbytriggers
Definition at line 49 of file damage.qh.
damageextraradius
float damageextraradius
Definition at line 139 of file damage.qh.
damageforcescale
float damageforcescale
Definition at line 136 of file damage.qh.
Referenced by CopyBody(), Monster_Damage(), Monster_Spawn_Setup(), PutObserverInServer(), PutPlayerInServer(), and vehicles_damage().
death_origin
vector death_origin
Definition at line 70 of file damage.qh.
Referenced by formatmessage(), and IMPULSE().
deathmessage
string deathmessage
Definition at line 75 of file damage.qh.
Referenced by Obituary().
dmg
float dmg
Definition at line 37 of file damage.qh.
dmg_edge
float dmg_edge
Definition at line 38 of file damage.qh.
Referenced by STATIC_INIT().
dmg_force
float dmg_force
Definition at line 39 of file damage.qh.
Referenced by STATIC_INIT().
dmg_radius
float dmg_radius
Definition at line 40 of file damage.qh.
Referenced by STATIC_INIT().
dmg_team
float dmg_team
Definition at line 56 of file damage.qh.
Referenced by PlayerThink(), and PutPlayerInServer().
fire_burner
entity fire_burner
Definition at line 149 of file damage.qh.
fire_damagepersec
float fire_damagepersec
Definition at line 145 of file damage.qh.
fire_deathtype
float fire_deathtype
Definition at line 146 of file damage.qh.
fire_hitsound
float fire_hitsound
Definition at line 148 of file damage.qh.
fire_owner
entity fire_owner
Definition at line 147 of file damage.qh.
freeze_time
float freeze_time
Definition at line 114 of file damage.qh.
Referenced by PlayerDamage().
frozen_by
entity frozen_by
Definition at line 116 of file damage.qh.
Referenced by Monster_Frozen_Think(), and PlayerPreThink().
FROZEN_NORMAL
const int FROZEN_NORMAL = 1
Definition at line 108 of file damage.qh.
Referenced by freezetag_count_alive_players(), freezetag_Freeze(), freezetag_isEliminated(), freezetag_LastPlayerForTeam(), ft_RemovePlayer(), havocbot_goalrating_ft_freeplayers(), havocbot_role_ft_offense(), and MUTATOR_HOOKFUNCTION().
FROZEN_TEMP_DYING
const int FROZEN_TEMP_DYING = 3
Definition at line 110 of file damage.qh.
Referenced by Freeze(), Monster_Frozen_Think(), PlayerPreThink(), and Unfreeze().
FROZEN_TEMP_REVIVING
const int FROZEN_TEMP_REVIVING = 2
Definition at line 109 of file damage.qh.
Referenced by Monster_Frozen_Think(), and PlayerPreThink().
g_damagedbycontents
IntrusiveList g_damagedbycontents
Definition at line 155 of file damage.qh.
Referenced by CopyBody(), CreatureFrame_All(), ctf_FlagSetup(), Fire_ApplyDamage(), FireGrapplingHook(), ka_DropEvent(), ka_SpawnBall(), ka_TouchEvent(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), PlayerCorpseDamage(), PutObserverInServer(), PutPlayerInServer(), and vehicle_initialize().
iceblock
entity iceblock
Definition at line 115 of file damage.qh.
Referenced by Monster_Frozen_Think(), Monster_Remove(), and PlayerPreThink().
impressive_hits
int impressive_hits
Definition at line 52 of file damage.qh.
Referenced by Damage().
istypefrag
bool istypefrag
Definition at line 61 of file damage.qh.
killsound
float killsound
Definition at line 72 of file damage.qh.
MAX_DAMAGEEXTRARADIUS
const float MAX_DAMAGEEXTRARADIUS = 16
Definition at line 138 of file damage.qh.
Referenced by RadiusDamageForSource().
MIN_DAMAGEEXTRARADIUS
const float MIN_DAMAGEEXTRARADIUS = 2
Definition at line 137 of file damage.qh.
Referenced by RadiusDamageForSource().
pain_finished
float pain_finished
Definition at line 54 of file damage.qh.
pusher
entity pusher
Definition at line 60 of file damage.qh.
RadiusDamage_running
float RadiusDamage_running
Definition at line 130 of file damage.qh.
Referenced by RadiusDamageForSource().
revival_time
float revival_time
Definition at line 112 of file damage.qh.
Referenced by PutObserverInServer(), and PutPlayerInServer().
revive_speed
float revive_speed
Definition at line 113 of file damage.qh.
Referenced by Monster_Frozen_Think(), and PlayerPreThink().
spawnshieldtime
float spawnshieldtime
Definition at line 64 of file damage.qh.
Referenced by Item_Touch(), Monster_Damage(), Monster_Spawn(), player_powerups(), PlayerDamage(), and PutPlayerInServer().
taunt_soundtime
float taunt_soundtime
Definition at line 62 of file damage.qh.
Referenced by PlayerPreThink().
teamkill_complain
float teamkill_complain
Definition at line 57 of file damage.qh.
Referenced by Damage(), and W_Nexball_Touch().
teamkill_soundsource
entity teamkill_soundsource
Definition at line 59 of file damage.qh.
teamkill_soundtime
float teamkill_soundtime
Definition at line 58 of file damage.qh.
Referenced by PlayerPreThink().
totalfrags
int totalfrags
Definition at line 66 of file damage.qh.
typehitsound
float typehitsound
Definition at line 72 of file damage.qh.
w_deathtype
float w_deathtype
Definition at line 96 of file damage.qh.
Referenced by Obituary_WeaponDeath().
yoda
float yoda
Definition at line 51 of file damage.qh.
Referenced by Damage(), fireBullet_antilag(), and MUTATOR_HOOKFUNCTION().