Xonotic: client/hud/panel/pressedkeys.qc File Reference
pressedkeys.qc File Reference
#include "pressedkeys.qh"
#include <client/autocvars.qh>
#include <client/defs.qh>
#include <client/miscfunctions.qh>
Functions
void HUD_PressedKeys ()
Function Documentation
void HUD_PressedKeys ()
Definition at line 9 of file pressedkeys.qc.
References autocvar__hud_configure, autocvar_hud_panel_pressedkeys, autocvar_hud_panel_pressedkeys_aspect, autocvar_hud_panel_pressedkeys_attack, autocvar_hud_panel_pressedkeys_dynamichud, DRAWFLAG_NORMAL, drawpic_aspect_skin, eX, HUD_Panel_DrawBg, HUD_Panel_LoadCvars(), HUD_Scale_Disable(), HUD_Scale_Enable(), KEY_ATCK, KEY_ATCK2, KEY_BACKWARD, KEY_CROUCH, KEY_FORWARD, KEY_JUMP, KEY_LEFT, KEY_RIGHT, panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, pressedkeys, spectatee_status, vec2, and vector().
 {
     if(!autocvar__hud_configure)
     {
         if(!autocvar_hud_panel_pressedkeys) return;
         if(spectatee_status <= 0 && autocvar_hud_panel_pressedkeys < 2) return;
     }
     HUD_Panel_LoadCvars();
     vector pos, mySize;
     pos = panel_pos;
     mySize = panel_size;
     if (autocvar_hud_panel_pressedkeys_dynamichud)
         HUD_Scale_Enable();
     else
         HUD_Scale_Disable();
     HUD_Panel_DrawBg();
     if(panel_bg_padding)
     {
         pos += '1 1 0' * panel_bg_padding;
         mySize -= '2 2 0' * panel_bg_padding;
     }
     // force custom aspect
     float aspect = autocvar_hud_panel_pressedkeys_aspect;
     if(aspect)
     {
         vector newSize = '0 0 0';
         if(mySize.x/mySize.y > aspect)
         {
             newSize.x = aspect * mySize.y;
             newSize.y = mySize.y;
             pos.x = pos.x + (mySize.x - newSize.x) / 2;
         }
         else
         {
             newSize.y = 1/aspect * mySize.x;
             newSize.x = mySize.x;
             pos.y = pos.y + (mySize.y - newSize.y) / 2;
         }
         mySize = newSize;
     }
     vector keysize = vec2(mySize.x / 3, mySize.y / (3 - !autocvar_hud_panel_pressedkeys_attack));
     int pressedkeys = STAT(PRESSED_KEYS);
     if(autocvar_hud_panel_pressedkeys_attack)
     {
         drawpic_aspect_skin(pos + eX * keysize.x * 0.5, ((pressedkeys & KEY_ATCK) ? "key_atck_inv.tga" : "key_atck.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
         drawpic_aspect_skin(pos + eX * keysize.x * 1.5, ((pressedkeys & KEY_ATCK2) ? "key_atck_inv.tga" : "key_atck.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
         pos.y += keysize.y;
     }
     drawpic_aspect_skin(pos, ((pressedkeys & KEY_CROUCH) ? "key_crouch_inv.tga" : "key_crouch.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     drawpic_aspect_skin(pos + eX * keysize.x, ((pressedkeys & KEY_FORWARD) ? "key_forward_inv.tga" : "key_forward.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     drawpic_aspect_skin(pos + eX * keysize.x * 2, ((pressedkeys & KEY_JUMP) ? "key_jump_inv.tga" : "key_jump.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     pos.y += keysize.y;
     drawpic_aspect_skin(pos, ((pressedkeys & KEY_LEFT) ? "key_left_inv.tga" : "key_left.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     drawpic_aspect_skin(pos + eX * keysize.x, ((pressedkeys & KEY_BACKWARD) ? "key_backward_inv.tga" : "key_backward.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     drawpic_aspect_skin(pos + eX * keysize.x * 2, ((pressedkeys & KEY_RIGHT) ? "key_right_inv.tga" : "key_right.tga"), keysize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
 }