Xonotic: server/miscfunctions.qh File Reference
miscfunctions.qh File Reference
#include <server/defs.qh>
#include <server/g_world.qh>
#include <common/t_items.qh>
#include <server/mutators/_mod.qh>
#include <common/constants.qh>
#include <common/mapinfo.qh>
#include <common/turrets/all.qh>
Macros
#define CENTER_OR_VIEWOFS(ent) (ent.origin + (IS_PLAYER(ent) ? ent.view_ofs : ((ent.mins + ent.maxs) * 0.5)))
#define cvar_normal builtin_cvar
#define cvar_set_normal builtin_cvar_set
#define cvar_string_normal builtin_cvar_string
#define IS_DEAD(s) ((s).deadflag != DEAD_NO)
#define ITEM_DAMAGE_NEEDKILL(dt) (((dt) == DEATH_HURTTRIGGER.m_id) || ((dt) == DEATH_SLIME.m_id) || ((dt) == DEATH_LAVA.m_id) || ((dt) == DEATH_SWAMP.m_id))
#define ITEM_TOUCH_NEEDKILL() (((trace_dpstartcontents | trace_dphitcontents) & DPCONTENTS_NODROP) || (trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY))
#define PROJECTILE_TOUCH(e, t) MACRO_BEGIN if (WarpZone_Projectile_Touch(e,t)) return; MACRO_END
#define WARMUP_START_WEAPONS ((g_warmup_allguns == 1) ? (warmup_start_weapons & (weaponsInMap | start_weapons)) : warmup_start_weapons)
Functions
string AmmoNameFromWeaponentity (Weapon wep)
void attach_sameorigin (entity e, entity to, string tag)
void crosshair_trace (entity pl)
void crosshair_trace_plusvisibletriggers (entity pl)
void crosshair_trace_plusvisibletriggers__is_wz (entity pl, bool is_wz)
void dedicated_print (string input)
print(), but only print if the server is not local
void detach_sameorigin (entity e)
void droptofloor (entity this)
void EliminatedPlayers_Init (float(entity) isEliminated_func)
void follow_sameorigin (entity e, entity to)
string formatmessage (entity this, string msg)
void GameLogClose ()
void GameLogEcho (string s)
void GameLogInit ()
void GetCvars (entity this, entity store, int f)
void GetCvars_handleFloat (entity this, entity store, string thisname, float f,.float field, string name)
void GetCvars_handleString (entity this, entity store, string thisname, float f,.string field, string name)
string GetMapname ()
void InitializeEntitiesRun ()
void InitializeEntity (entity e, void(entity this) func, int order)
float isPushable (entity e)
float LostMovetypeFollow (entity ent)
float MoveToRandomLocationWithinBounds (entity e, vector boundmin, vector boundmax, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
float MoveToRandomMapLocation (entity e, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
string NearestLocation (vector p)
void play2 (entity e, string filename)
void play2all (string samp)
void play2team (float t, string filename)
string playername (entity p, bool team_colorize)
void precache ()
void precache_all_playermodels (string pattern)
void readlevelcvars ()
void readplayerstartcvars ()
void remove_safely (entity e)
void remove_unsafely (entity e)
void SetMovetypeFollow (entity ent, entity e)
bool sound_allowed (int dest, entity e)
void soundat (entity e, vector o, float chan, string samp, float vol, float _atten)
void soundto (float dest, entity e, float chan, string samp, float vol, float atten)
void soundtoat (float _dest, entity e, vector o, float chan, string samp, float vol, float _atten)
float spamsound (entity e, float chan, Sound samp, float vol, float _atten)
STATIC_INIT (g_ctrace_changed)
void stopsound (entity e, float chan)
void stopsoundto (float _dest, entity e, float chan)
string strcat1 (string s)
float tracebox_hits_box (vector start, vector mi, vector ma, vector end, vector thmi, vector thma)
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
string uid2name (string myuid)
void (entity this) initialize_entity
float want_weapon (entity weaponinfo, float allguns)
void WarpZone_crosshair_trace (entity pl)
void WarpZone_crosshair_trace_plusvisibletriggers (entity pl)
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void write_recordmarker (entity pl, float tstart, float dt)
Variables
string autocvar_g_random_start_weapons
Holds a list of possible random start weapons.
vector dropped_origin
entity eliminatedPlayers
IntrusiveList g_ctrace_changed
float g_pickup_cells_max
float g_pickup_fuel_max
float g_pickup_nails_max
float g_pickup_plasma_max
float g_pickup_rockets_max
float g_pickup_shells_max
float g_pickup_weapons_anyway
float g_weapon_stay
float g_weaponarena
string g_weaponarena_list
float g_weaponarena_random
WepSet g_weaponarena_weapons
float g_weapondamagefactor
float g_weaponforcefactor
float g_weaponratefactor
float g_weaponspeedfactor
float g_weaponspreadfactor
entity initialize_entity_first
entity initialize_entity_next
int initialize_entity_order
const int INITPRIO_DROPTOFLOOR = 20
const int INITPRIO_FINDTARGET = 10
const int INITPRIO_FIRST = 0
const int INITPRIO_GAMETYPE = 0
const int INITPRIO_GAMETYPE_FALLBACK = 1
const int INITPRIO_LAST = 99
const int INITPRIO_LINKDOORS = 91
const int INITPRIO_SETLOCATION = 90
float logfile
float logfile_open
entity nearest_entity [NUM_NEAREST_ENTITIES]
float nearest_length [NUM_NEAREST_ENTITIES]
const float NUM_NEAREST_ENTITIES = 4
entity random_start_ammo
Entity that contains amount of ammo to give with random start weapons.
int random_start_weapons_count
Number of random start weapons to give to players.
float start_ammo_cells
float start_ammo_fuel
float start_ammo_nails
float start_ammo_plasma
float start_ammo_rockets
float start_ammo_shells
float start_armorvalue
float start_health
int start_items
WepSet start_weapons
WepSet start_weapons_default
WepSet start_weapons_defaultmask
float sv_autotaunt
float sv_taunt
float warmup_start_ammo_cells
float warmup_start_ammo_fuel
float warmup_start_ammo_nails
float warmup_start_ammo_plasma
float warmup_start_ammo_rockets
float warmup_start_ammo_shells
float warmup_start_armorvalue
float warmup_start_health
WepSet warmup_start_weapons
WepSet warmup_start_weapons_default
WepSet warmup_start_weapons_defaultmask
Macro Definition Documentation
#define CENTER_OR_VIEWOFS (ent) (ent.origin + (IS_PLAYER(ent) ? ent.view_ofs : ((ent.mins + ent.maxs) * 0.5)))
Definition at line 133 of file miscfunctions.qh.
Referenced by buff_Respawn(), buff_Think(), buff_Touch(), CommonCommand_editmob(), havocbot_gettarget(), monster_dropitem(), Monster_FindTarget(), Monster_Move_2D(), MUTATOR_HOOKFUNCTION(), and RadiusDamageForSource().
#define cvar_normal builtin_cvar
Definition at line 16 of file miscfunctions.qh.
Referenced by CampaignBailout(), CampaignPreIntermission(), and spawnfunc().
#define cvar_set_normal builtin_cvar_set
Definition at line 30 of file miscfunctions.qh.
Referenced by CampaignBailout(), CampaignPostInit(), CampaignPreInit(), CampaignSaveCvar(), and spawnfunc().
#define cvar_string_normal builtin_cvar_string
Definition at line 15 of file miscfunctions.qh.
Referenced by CampaignBailout(), and spawnfunc().
#define IS_DEAD (s) ((s).deadflag != DEAD_NO)
Definition at line 125 of file miscfunctions.qh.
#define ITEM_DAMAGE_NEEDKILL (dt) (((dt) == DEATH_HURTTRIGGER.m_id) || ((dt) == DEATH_SLIME.m_id) || ((dt) == DEATH_LAVA.m_id) || ((dt) == DEATH_SWAMP.m_id))
Definition at line 129 of file miscfunctions.qh.
Referenced by ctf_FlagDamage(), kh_Key_Damage(), Monster_Damage(), MUTATOR_HOOKFUNCTION(), and physical_item_damage().
#define ITEM_TOUCH_NEEDKILL () (((trace_dpstartcontents | trace_dphitcontents) & DPCONTENTS_NODROP) || (trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY))
Definition at line 128 of file miscfunctions.qh.
Referenced by buff_Touch(), ctf_FlagThink(), kh_Key_Touch(), and physical_item_touch().
#define PROJECTILE_TOUCH (e, t) MACRO_BEGIN if (WarpZone_Projectile_Touch(e,t)) return; MACRO_END
Definition at line 131 of file miscfunctions.qh.
Referenced by GrapplingHookTouch(), vehicles_projectile_explode(), and W_Nexball_Touch().
#define WARMUP_START_WEAPONS ((g_warmup_allguns == 1) ? (warmup_start_weapons & (weaponsInMap | start_weapons)) : warmup_start_weapons)
Definition at line 209 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and PutPlayerInServer().
Function Documentation
string AmmoNameFromWeaponentity (Weapon wep)
Definition at line 216 of file miscfunctions.qc.
References Weapon::ammo_type, RES_BULLETS, RES_CELLS, RES_FUEL, RES_PLASMA, RES_ROCKETS, and RES_SHELLS.
Referenced by formatmessage().
 {
     string ammoitems = "batteries";
     switch (wep.ammo_type)
     {
         case RES_SHELLS:  ammoitems = ITEM_Shells.m_name;      break;
         case RES_BULLETS: ammoitems = ITEM_Bullets.m_name;     break;
         case RES_ROCKETS: ammoitems = ITEM_Rockets.m_name;     break;
         case RES_CELLS:   ammoitems = ITEM_Cells.m_name;       break;
         case RES_PLASMA:  ammoitems = ITEM_Plasma.m_name;      break;
         case RES_FUEL:    ammoitems = ITEM_JetpackFuel.m_name; break;
     }
     return ammoitems;
 }
void attach_sameorigin (entity e, entity to, string tag)
Definition at line 1413 of file miscfunctions.qc.
References AnglesTransform_FromAngles(), AnglesTransform_FromVAngles(), AnglesTransform_ToAngles(), AnglesTransform_ToVAngles(), fixedmakevectors, fixedvectoangles2, gettagindex, setorigin(), substring(), v_forward, v_right, v_up, vector(), and vlen().
 {
     vector org, t_forward, t_left, t_up, e_forward, e_up;
     float tagscale;
     org = e.origin - gettaginfo(to, gettagindex(to, tag));
     tagscale = (vlen(v_forward) ** -2); // undo a scale on the tag
     t_forward = v_forward * tagscale;
     t_left = v_right * -tagscale;
     t_up = v_up * tagscale;
     e.origin_x = org * t_forward;
     e.origin_y = org * t_left;
     e.origin_z = org * t_up;
     // current forward and up directions
     if (substring(e.model, 0, 1) == "*") // bmodels have their own rules
         e.angles = AnglesTransform_FromVAngles(e.angles);
     else
         e.angles = AnglesTransform_FromAngles(e.angles);
     fixedmakevectors(e.angles);
     // untransform forward, up!
     e_forward.x = v_forward * t_forward;
     e_forward.y = v_forward * t_left;
     e_forward.z = v_forward * t_up;
     e_up.x = v_up * t_forward;
     e_up.y = v_up * t_left;
     e_up.z = v_up * t_up;
     e.angles = fixedvectoangles2(e_forward, e_up);
     if (substring(e.model, 0, 1) == "*") // bmodels have their own rules
         e.angles = AnglesTransform_ToVAngles(e.angles);
     else
         e.angles = AnglesTransform_ToAngles(e.angles);
     setattachment(e, to, tag);
     setorigin(e, e.origin);
 }
void crosshair_trace (entity pl)
Definition at line 39 of file miscfunctions.qc.
References ANTILAG_LATENCY, CS(), cursor_trace_endpos, cursor_trace_start, MOVE_NORMAL, normalize(), and traceline_antilag().
Referenced by CheatCommand(), crosshair_trace_plusvisibletriggers__is_wz(), and MUTATOR_HOOKFUNCTION().
 {
     traceline_antilag(pl, CS(pl).cursor_trace_start, CS(pl).cursor_trace_start + normalize(CS(pl).cursor_trace_endpos - CS(pl).cursor_trace_start) * max_shot_distance, MOVE_NORMAL, pl, ANTILAG_LATENCY(pl));
 }
void crosshair_trace_plusvisibletriggers (entity pl)
Definition at line 44 of file miscfunctions.qc.
References crosshair_trace_plusvisibletriggers__is_wz().
Referenced by Drag(), and sandbox_ObjectEdit_Get().
 {
     crosshair_trace_plusvisibletriggers__is_wz(pl, false);
 }
void crosshair_trace_plusvisibletriggers__is_wz (entity pl, bool is_wz)
Definition at line 54 of file miscfunctions.qc.
References crosshair_trace(), FOREACH_ENTITY_FLOAT, g_ctrace_changed, IL_CLEAR, IL_EACH, solid, SOLID_TRIGGER, and WarpZone_crosshair_trace().
Referenced by crosshair_trace_plusvisibletriggers(), and WarpZone_crosshair_trace_plusvisibletriggers().
 {
     FOREACH_ENTITY_FLOAT(solid, SOLID_TRIGGER,
     {
         if(it.model != "")
         {
             it.solid = SOLID_BSP;
             IL_PUSH(g_ctrace_changed, it);
         }
     });
     if (is_wz)
         WarpZone_crosshair_trace(pl);
     else
         crosshair_trace(pl);
     IL_EACH(g_ctrace_changed, true, { it.solid = SOLID_TRIGGER; });
     IL_CLEAR(g_ctrace_changed);
 }
void dedicated_print (string input)
print(), but only print if the server is not local
Definition at line 80 of file miscfunctions.qc.
References print(), and server_is_dedicated.
Referenced by GameLogEcho(), and Say().
 {
     if (server_is_dedicated) print(input);
 }
void detach_sameorigin (entity e)
Definition at line 1453 of file miscfunctions.qc.
References AnglesTransform_ToAngles(), AnglesTransform_ToVAngles(), fixedvectoangles2, NULL, setorigin(), substring(), v_forward, v_up, and vector().
Referenced by Drag().
 {
     vector org;
     org = gettaginfo(e, 0);
     e.angles = fixedvectoangles2(v_forward, v_up);
     if (substring(e.model, 0, 1) == "*") // bmodels have their own rules
         e.angles = AnglesTransform_ToVAngles(e.angles);
     else
         e.angles = AnglesTransform_ToAngles(e.angles);
     setorigin(e, org);
     setattachment(e, NULL, "");
     setorigin(e, e.origin);
 }
void droptofloor (entity this)
Definition at line 1110 of file miscfunctions.qc.
References DropToFloor_Handler(), InitializeEntity(), and INITPRIO_DROPTOFLOOR.
 {
     InitializeEntity(this, DropToFloor_Handler, INITPRIO_DROPTOFLOOR);
 }
void EliminatedPlayers_Init (float(entity) isEliminated_func)
Definition at line 1082 of file miscfunctions.qc.
References backtrace, eliminatedPlayers, EliminatedPlayers_SendEntity(), and spawn().
Referenced by freezetag_Initialize(), and REGISTER_MUTATOR().
 {
     if(eliminatedPlayers)
     {
         backtrace("Can't spawn eliminatedPlayers again!");
         return;
     }
     Net_LinkEntity(eliminatedPlayers = spawn(), false, 0, EliminatedPlayers_SendEntity);
     eliminatedPlayers.isEliminated = isEliminated_func;
 }
void follow_sameorigin (entity e, entity to)
Definition at line 1467 of file miscfunctions.qc.
References MOVETYPE_FOLLOW, set_movetype(), and to.
 {
     set_movetype(e, MOVETYPE_FOLLOW); // make the hole follow
     e.aiment = to; // make the hole follow bmodel
     e.punchangle = to.angles; // the original angles of bmodel
     e.view_ofs = e.origin - to.origin; // relative origin
     e.v_angle = e.angles - to.angles; // relative angles
 }
string formatmessage (entity this, string msg)
Definition at line 243 of file miscfunctions.qc.
References AmmoNameFromWeaponentity(), autocvar_timelimit, ceil(), cnt, death_origin, entity(), floor(), ftos(), GetResource(), M_ARGV, max(), min(), MUTATOR_CALLHOOK, NearestLocation(), NULL, origin, p, PlayerHealth(), RES_ARMOR, seconds_tostring(), strcat(), strlen(), strstrofs, substring(), time, trace_endpos, trace_ent, vector(), velocity, vlen(), WarpZone_crosshair_trace_plusvisibletriggers(), weaponentities, and Weapons_from.
Referenced by Say().
 {
     float p, p1, p2;
     float n;
     vector cursor = '0 0 0';
     entity cursor_ent = NULL;
     string escape;
     string replacement;
     p = 0;
     n = 7;
     bool traced = false;
     MUTATOR_CALLHOOK(PreFormatMessage, this, msg);
     msg = M_ARGV(1, string);
     while (1) {
         if (n < 1)
             break; // too many replacements
         n = n - 1;
         p1 = strstrofs(msg, "%", p); // NOTE: this destroys msg as it's a tempstring!
         p2 = strstrofs(msg, "\\", p); // NOTE: this destroys msg as it's a tempstring!
         if (p1 < 0)
             p1 = p2;
         if (p2 < 0)
             p2 = p1;
         p = min(p1, p2);
         if (p < 0)
             break;
         if(!traced)
         {
             WarpZone_crosshair_trace_plusvisibletriggers(this);
             cursor = trace_endpos;
             cursor_ent = trace_ent;
             traced = true;
         }
         replacement = substring(msg, p, 2);
         escape = substring(msg, p + 1, 1);
         .entity weaponentity = weaponentities[0]; // TODO: unhardcode
         switch(escape)
         {
             case "%": replacement = "%"; break;
             case "\\":replacement = "\\"; break;
             case "n": replacement = "\n"; break;
             case "a": replacement = ftos(floor(GetResource(this, RES_ARMOR))); break;
             case "h": replacement = PlayerHealth(this); break;
             case "l": replacement = NearestLocation(this.origin); break;
             case "y": replacement = NearestLocation(cursor); break;
             case "d": replacement = NearestLocation(this.death_origin); break;
             case "w": replacement = ((this.(weaponentity).m_weapon == WEP_Null) ? ((this.(weaponentity).m_switchweapon == WEP_Null) ? Weapons_from(this.(weaponentity).cnt) : this.(weaponentity).m_switchweapon) : this.(weaponentity).m_weapon).m_name; break;
             case "W": replacement = AmmoNameFromWeaponentity(this.(weaponentity).m_weapon); break;
             case "x": replacement = ((cursor_ent.netname == "" || !cursor_ent) ? "nothing" : cursor_ent.netname); break;
             case "s": replacement = ftos(vlen(this.velocity - this.velocity_z * '0 0 1')); break;
             case "S": replacement = ftos(vlen(this.velocity)); break;
             case "t": replacement = seconds_tostring(ceil(max(0, autocvar_timelimit * 60 + game_starttime - time))); break;
             case "T": replacement = seconds_tostring(floor(time - game_starttime)); break;
             default:
             {
                 MUTATOR_CALLHOOK(FormatMessage, this, escape, replacement, msg);
                 replacement = M_ARGV(2, string);
                 break;
             }
         }
         msg = strcat(substring(msg, 0, p), replacement, substring(msg, p+2, strlen(msg) - (p+2)));
         p = p + strlen(replacement);
     }
     return msg;
 }
void GameLogClose ()
Definition at line 124 of file miscfunctions.qc.
References fclose(), logfile, and logfile_open.
Referenced by NextLevel().
 {
     if (logfile_open && logfile >= 0)
     {
         fclose(logfile);
         logfile = -1;
     }
 }
void GameLogEcho (string s)
Definition at line 85 of file miscfunctions.qc.
References autocvar_sv_eventlog_console, autocvar_sv_eventlog_files, autocvar_sv_eventlog_files_counter, autocvar_sv_eventlog_files_nameprefix, autocvar_sv_eventlog_files_namesuffix, autocvar_sv_eventlog_files_timestamps, cvar_set(), dedicated_print(), FILE_APPEND, fopen(), fputs(), ftos(), itos, logfile, logfile_open, strcat(), strlen(), and substring().
Referenced by anticheat_report_to_eventlog(), ClientConnect(), ClientDisconnect(), ctf_EventLog(), cts_EventLog(), dom_EventLog(), DumpStats(), end_minigame(), invite_minigame(), ka_EventLog(), kh_Scores_Event(), LogDeath(), LogNB(), LogTeamChange(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_Suggest(), minigame_addplayer(), minigame_rmplayer(), NextLevel(), PlayerInList(), PlayerPreThink(), race_EventLog(), ReadyRestart_force(), Say(), spawnfunc(), start_minigame(), StartFrame(), VoteCommand_call(), VoteCommand_master(), VoteSpam(), VoteStop(), and write_recordmarker().
 {
     string fn;
     int matches;
     if (autocvar_sv_eventlog_files)
     {
         if (!logfile_open)
         {
             logfile_open = true;
             matches = autocvar_sv_eventlog_files_counter + 1;
             cvar_set("sv_eventlog_files_counter", itos(matches));
             fn = ftos(matches);
             if (strlen(fn) < 8)
                 fn = strcat(substring("00000000", 0, 8 - strlen(fn)), fn);
             fn = strcat(autocvar_sv_eventlog_files_nameprefix, fn, autocvar_sv_eventlog_files_namesuffix);
             logfile = fopen(fn, FILE_APPEND);
             fputs(logfile, ":logversion:3\n");
         }
         if (logfile >= 0)
         {
             if (autocvar_sv_eventlog_files_timestamps)
                 fputs(logfile, strcat(":time:", strftime(true, "%Y-%m-%d %H:%M:%S", "\n", s, "\n")));
             else
                 fputs(logfile, strcat(s, "\n"));
         }
     }
     if (autocvar_sv_eventlog_console)
     {
         dedicated_print(strcat(s, "\n"));
     }
 }
void GameLogInit ()
Definition at line 118 of file miscfunctions.qc.
References logfile_open.
Referenced by spawnfunc().
 {
     logfile_open = 0;
     // will be opened later
 }
void GetCvars (entity this, entity store, int f)
Parameters
f -1: cleanup, 0: request, 1: receive
Definition at line 444 of file miscfunctions.qc.
References argv(), cvar_cl_allow_uidtracking, cvar_cl_weaponpriorities, cvar_cl_weaponpriority, get_cvars_f, get_cvars_s, GetCvars(), GetCvars_handleFloat(), GetCvars_handleString_Fixup(), LOG_INFO, MAX_WEAPONSLOTS, MUTATOR_CALLHOOK, strcat1(), string_null, W_FixWeaponOrder_AllowIncomplete(), W_FixWeaponOrder_ForceComplete_AndBuildImpulseList(), w_getbestweapon, and weaponentities.
Referenced by GetCvars().
 {
     string s = string_null;
     if (f == 0)
         LOG_INFO("Warning: requesting cvar values is deprecated. Client should send them automatically using REPLICATE.\n");
     if (f > 0)
         s = strcat1(argv(f));
     get_cvars_f = f;
     get_cvars_s = s;
     MUTATOR_CALLHOOK(GetCvars);
     Notification_GetCvars(this);
     ReplicateVars(this, store, s, f);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriority, "cl_weaponpriority", W_FixWeaponOrder_ForceComplete_AndBuildImpulseList);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[0], "cl_weaponpriority0", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[1], "cl_weaponpriority1", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[2], "cl_weaponpriority2", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[3], "cl_weaponpriority3", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[4], "cl_weaponpriority4", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[5], "cl_weaponpriority5", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[6], "cl_weaponpriority6", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[7], "cl_weaponpriority7", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[8], "cl_weaponpriority8", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(this, store, s, f, cvar_cl_weaponpriorities[9], "cl_weaponpriority9", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleFloat(this, store, s, f, cvar_cl_allow_uidtracking, "cl_allow_uidtracking");
     // fixup of switchweapon (needed for LMS or when spectating is disabled, as PutClientInServer comes too early)
     if (f > 0)
     {
         if (s == "cl_weaponpriority")
         {
             for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
             {
                 .entity weaponentity = weaponentities[slot];
                 if (this.(weaponentity) && (this.(weaponentity).m_weapon != WEP_Null || slot == 0))
                     this.(weaponentity).m_switchweapon = w_getbestweapon(this, weaponentity);
             }
         }
         if (s == "cl_allow_uidtracking")
             PlayerStats_GameReport_AddPlayer(this);
     }
 }
void GetCvars_handleFloat (entity this, entity store, string thisname, float f, .float field, string name)
Definition at line 358 of file miscfunctions.qc.
References argv(), stof(), strcat(), and stuffcmd.
Referenced by GetCvars().
 {
     if (f < 0)
     {
     }
     else if (f > 0)
     {
         if (thisname == name)
             store.(field) = stof(argv(f + 1));
     }
     else
         stuffcmd(this, strcat("cl_cmd sendcvar ", name, "\n"));
 }
void GetCvars_handleString (entity this, entity store, string thisname, float f, .string field, string name)
Definition at line 329 of file miscfunctions.qc.
References argv(), strcat(), strcpy, strfree, and stuffcmd.
Referenced by GetCvars_handleString_Fixup().
 {
     if (f < 0)
     {
         strfree(store.(field));
     }
     else if (f > 0)
     {
         if (thisname == name)
         {
             strcpy(store.(field), argv(f + 1));
         }
     }
     else
         stuffcmd(this, strcat("cl_cmd sendcvar ", name, "\n"));
 }
string GetMapname ()
Definition at line 1009 of file g_world.qc.
References mapname.
Referenced by Campaign_Invalid(), checkpoint_passed(), ctf_CaptureRecord(), ctf_Initialize(), DumpStats(), GameCommand_delrec(), GetMaplistPosition(), getrankings(), IntermissionThink(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_send_recordtime(), race_SendRankings(), race_SendTime(), race_setTime(), sandbox_Database_Load(), sandbox_Database_Save(), spawnfunc(), trigger_race_checkpoint_verify(), and WeaponStats_ready().
 {
     return mapname;
 }
void InitializeEntitiesRun ()
Definition at line 1023 of file miscfunctions.qc.
References backtrace, delete_fn(), entity(), eprint(), func_null(), initialize_entity_first, next, NULL, remove_except_protected(), remove_unsafely(), strcat(), and void.
Referenced by StartFrame().
 {
     entity startoflist = initialize_entity_first;
     initialize_entity_first = NULL;
     delete_fn = remove_except_protected;
     for (entity e = startoflist; e; e = e.initialize_entity_next)
     {
         e.remove_except_protected_forbidden = 1;
     }
     for (entity e = startoflist; e; )
     {
         e.remove_except_protected_forbidden = 0;
         e.initialize_entity_order = 0;
         entity next = e.initialize_entity_next;
         e.initialize_entity_next = NULL;
         var void(entity this) func = e.initialize_entity;
         e.initialize_entity = func_null;
         if (e.classname == "initialize_entity")
         {
             entity wrappee = e.enemy;
             builtin_remove(e);
             e = wrappee;
         }
         //dprint("Delayed initialization: ", e.classname, "\n");
         if (func)
         {
             func(e);
         }
         else
         {
             eprint(e);
             backtrace(strcat("Null function in: ", e.classname, "\n"));
         }
         e = next;
     }
     delete_fn = remove_unsafely;
 }
void InitializeEntity (entity e, void(entity this) func, int order)
Definition at line 990 of file miscfunctions.qc.
References entity(), initialize_entity_first, NULL, and prev.
Referenced by ctf_FlagSetup(), ctf_Initialize(), dom_Initialize(), door_reset(), droptofloor(), InitGameplayMode(), invasion_Initialize(), ka_SpawnBall(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Setup(), ons_GeneratorSetup(), ons_Initialize(), readplayerstartcvars(), REGISTER_MUTATOR(), spawnfunc(), SUB_CalcAngleMoveEnt(), target_give_init(), Teleport_Touch(), train_next(), and trigger_push_findtarget().
 {
     entity prev, cur;
     if (!e || e.initialize_entity)
     {
         // make a proxy initializer entity
         entity e_old = e;
         e = new(initialize_entity);
         e.enemy = e_old;
     }
     e.initialize_entity = func;
     e.initialize_entity_order = order;
     cur = initialize_entity_first;
     prev = NULL;
     for (;;)
     {
         if (!cur || cur.initialize_entity_order > order)
         {
             // insert between prev and cur
             if (prev)
                 prev.initialize_entity_next = e;
             else
                 initialize_entity_first = e;
             e.initialize_entity_next = cur;
             return;
         }
         prev = cur;
         cur = cur.initialize_entity_next;
     }
 }
float isPushable (entity e)
Definition at line 1533 of file miscfunctions.qc.
References IS_VEHICLE, and Item_IsLoot().
Referenced by conveyor_think(), jumppad_push(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), and trigger_impulse_touch_radial().
 {
     if(e.pushable)
         return true;
     if(IS_VEHICLE(e))
         return false;
     if(e.iscreature)
         return true;
     if (Item_IsLoot(e))
     {
         return true;
     }
     switch(e.classname)
     {
         case "body":
             return true;
         case "bullet": // antilagged bullets can't hit this either
             return false;
     }
     if (e.projectiledeathtype)
         return true;
     return false;
 }
float LostMovetypeFollow (entity ent)
Definition at line 1515 of file miscfunctions.qc.
Referenced by GrapplingHookThink().
 {
 /*
     if(ent.move_movetype != MOVETYPE_FOLLOW)
         if(ent.aiment)
             error("???");
 */
     if(ent.aiment)
     {
         if(ent.aiment.classname != ent.aiment_classname)
             return 1;
         if(ent.aiment.deadflag != ent.aiment_deadflag)
             return 1;
     }
     return 0;
 }
float MoveToRandomLocationWithinBounds (entity e, vector boundmin, vector boundmax, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
Definition at line 1272 of file miscfunctions.qc.
References checkpvs(), entity(), ftos(), g_items, g_spawnpoints, IL_EACH, LOG_DEBUG, MOVE_NORMAL, normalize(), NULL, Q3SURFACEFLAG_SKY, random(), setorigin(), trace_dphitcontents, trace_dphitq3surfaceflags, trace_dphittexturename, trace_endpos, trace_fraction, trace_startsolid, tracebox_hits_trigger_hurt(), vectoangles(), vector(), and vlen().
Referenced by MoveToRandomMapLocation().
 {
     float m, i;
     vector start, org, delta, end, enddown, mstart;
     m = e.dphitcontentsmask;
     e.dphitcontentsmask = goodcontents | badcontents;
     org = boundmin;
     delta = boundmax - boundmin;
     start = end = org;
     for (i = 0; i < attempts; ++i)
     {
         start.x = org.x + random() * delta.x;
         start.y = org.y + random() * delta.y;
         start.z = org.z + random() * delta.z;
         // rule 1: start inside world bounds, and outside
         // solid, and don't start from somewhere where you can
         // fall down to evil
         tracebox(start, e.mins, e.maxs, start - '0 0 1' * delta.z, MOVE_NORMAL, e);
         if (trace_fraction >= 1)
             continue;
         if (trace_startsolid)
             continue;
         if (trace_dphitcontents & badcontents)
             continue;
         if (trace_dphitq3surfaceflags & badsurfaceflags)
             continue;
         // rule 2: if we are too high, lower the point
         if (trace_fraction * delta.z > maxaboveground)
             start = trace_endpos + '0 0 1' * maxaboveground;
         enddown = trace_endpos;
         // rule 3: make sure we aren't outside the map. This only works
         // for somewhat well formed maps. A good rule of thumb is that
         // the map should have a convex outside hull.
         // these can be traceLINES as we already verified the starting box
         mstart = start + 0.5 * (e.mins + e.maxs);
         traceline(mstart, mstart + '1 0 0' * delta.x, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart - '1 0 0' * delta.x, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart + '0 1 0' * delta.y, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart - '0 1 0' * delta.y, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart + '0 0 1' * delta.z, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
     // rule 4: we must "see" some spawnpoint or item
     entity sp = NULL;
     IL_EACH(g_spawnpoints, checkpvs(mstart, it),
     {
         if((traceline(mstart, it.origin, MOVE_NORMAL, e), trace_fraction) >= 1)
         {
             sp = it;
             break;
         }
     });
     if(!sp)
     {
         int items_checked = 0;
         IL_EACH(g_items, checkpvs(mstart, it),
         {
             if((traceline(mstart, it.origin + (it.mins + it.maxs) * 0.5, MOVE_NORMAL, e), trace_fraction) >= 1)
             {
                 sp = it;
                 break;
             }
             ++items_checked;
             if(items_checked >= attempts)
                 break; // sanity
         });
         if(!sp)
             continue;
     }
         // find a random vector to "look at"
         end.x = org.x + random() * delta.x;
         end.y = org.y + random() * delta.y;
         end.z = org.z + random() * delta.z;
         end = start + normalize(end - start) * vlen(delta);
         // rule 4: start TO end must not be too short
         tracebox(start, e.mins, e.maxs, end, MOVE_NORMAL, e);
         if (trace_startsolid)
             continue;
         if (trace_fraction < minviewdistance / vlen(delta))
             continue;
         // rule 5: don't want to look at sky
         if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY)
             continue;
         // rule 6: we must not end up in trigger_hurt
         if (tracebox_hits_trigger_hurt(start, e.mins, e.maxs, enddown))
             continue;
         break;
     }
     e.dphitcontentsmask = m;
     if (i < attempts)
     {
         setorigin(e, start);
         e.angles = vectoangles(end - start);
         LOG_DEBUG("Needed ", ftos(i + 1), " attempts");
         return true;
     }
     else
         return false;
 }
float MoveToRandomMapLocation (entity e, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
Definition at line 1397 of file miscfunctions.qc.
References MoveToRandomLocationWithinBounds(), and world.
Referenced by buff_Respawn(), CheatImpulse(), invasion_SpawnChosenMonster(), and ka_RespawnBall().
 {
     return MoveToRandomLocationWithinBounds(e, world.mins, world.maxs, goodcontents, badcontents, badsurfaceflags, attempts, maxaboveground, minviewdistance);
 }
string NearestLocation (vector p)
Definition at line 201 of file miscfunctions.qc.
References entity(), and findnearest().
Referenced by formatmessage(), and Obituary().
 {
     string ret = "somewhere";
     entity loc = findnearest(p, false, '1 1 1');
     if (loc)
         ret = loc.message;
     else
     {
         loc = findnearest(p, true, '1 1 4');
         if (loc)
             ret = loc.netname;
     }
     return ret;
 }
void play2 (entity e, string filename)
Referenced by client_hasweapon(), door_check_keys(), door_touch(), ons_CaptureShield_Touch(), ons_ControlPoint_Icon_Damage(), ons_GeneratorDamage(), SUB_UseTargets_Ex(), trigger_keylock_touch(), vehicles_locktarget(), and W_Reload().
void play2all (string samp)
Referenced by dompoint_captured(), kh_LoserTeam(), kh_WinnerTeam(), and Onslaught_CheckWinner().
void play2team (float t, string filename)
Referenced by ons_ControlPoint_Icon_Damage(), and ons_GeneratorDamage().
string playername (entity p, bool team_colorize)
Definition at line 494 of file miscfunctions.qc.
References intermission_running, IS_PLAYER, strcat(), Team_ColorCode(), and teamplay.
 {
     string t;
     if (team_colorize && teamplay && !intermission_running && IS_PLAYER(p))
     {
         t = Team_ColorCode(p.team);
         return strcat(t, strdecolorize(p.netname));
     }
     else
         return p.netname;
 }
void precache ()
Definition at line 898 of file miscfunctions.qc.
References ATTEN_NONE, autocvar_sv_defaultcharacter, autocvar_sv_defaultplayermodel, autocvar_sv_defaultplayermodel_blue, autocvar_sv_defaultplayermodel_pink, autocvar_sv_defaultplayermodel_red, autocvar_sv_defaultplayermodel_yellow, autocvar_sv_precacheplayermodels, noise, precache_all_playermodels(), precache_playermodels(), precache_sound(), PrecachePlayerSounds(), and VOL_BASE.
Referenced by spawnfunc().
 {
     // gamemode related things
     // Precache all player models if desired
     if (autocvar_sv_precacheplayermodels)
     {
         PrecachePlayerSounds("sound/player/default.sounds");
         precache_all_playermodels("models/player/*.zym");
         precache_all_playermodels("models/player/*.dpm");
         precache_all_playermodels("models/player/*.md3");
         precache_all_playermodels("models/player/*.psk");
         precache_all_playermodels("models/player/*.iqm");
     }
     if (autocvar_sv_defaultcharacter)
     {
         precache_playermodels(autocvar_sv_defaultplayermodel_red);
         precache_playermodels(autocvar_sv_defaultplayermodel_blue);
         precache_playermodels(autocvar_sv_defaultplayermodel_yellow);
         precache_playermodels(autocvar_sv_defaultplayermodel_pink);
         precache_playermodels(autocvar_sv_defaultplayermodel);
     }
 #if 0
     // Disabled this code because it simply does not work (e.g. ignores bgmvolume, overlaps with "cd loop" controlled tracks).
     if (!this.noise && this.music) // quake 3 uses the music field
         this.noise = this.music;
     // plays music for the level if there is any
     if (this.noise)
     {
         precache_sound (this.noise);
         ambientsound ('0 0 0', this.noise, VOL_BASE, ATTEN_NONE);
     }
 #endif
 }
void precache_all_playermodels (string pattern)
Definition at line 880 of file miscfunctions.qc.
References precache_playermodel(), search_begin(), search_end(), search_getfilename(), and search_getsize().
Referenced by precache(), and REGISTER_MUTATOR().
 {
     int globhandle = search_begin(pattern, true, false);
     if (globhandle < 0) return;
     int n = search_getsize(globhandle);
     for (int i = 0; i < n; ++i)
     {
         string s = search_getfilename(globhandle, i);
         precache_playermodel(s);
     }
     search_end(globhandle);
 }
void readlevelcvars ()
Definition at line 226 of file miscfunctions.qh.
References cvar(), FOREACH, g_footsteps, g_jetpack, g_warmup_allguns, g_warmup_allow_timeout, GetGametype(), MUTATOR_CALLHOOK, readplayerstartcvars(), SERVERFLAG_ALLOW_FULLBRIGHT, serverflags, strcat(), sv_clones, sv_foginterval, sv_maxidle, sv_maxidle_slots, sv_maxidle_slots_countbots, sv_maxidle_spectatorsareidle, sv_ready_restart, sv_ready_restart_after_countdown, sv_ready_restart_repeatable, time, and warmup_stage.
Referenced by spawnfunc().
 {
     if(cvar("sv_allow_fullbright"))
         serverflags |= SERVERFLAG_ALLOW_FULLBRIGHT;
     sv_clones = cvar("sv_clones");
     sv_foginterval = cvar("sv_foginterval");
     g_footsteps = cvar("g_footsteps");
     g_jetpack = cvar("g_jetpack");
     sv_maxidle = cvar("sv_maxidle");
     sv_maxidle_spectatorsareidle = cvar("sv_maxidle_spectatorsareidle");
     sv_maxidle_slots = cvar("sv_maxidle_slots");
     sv_maxidle_slots_countbots = cvar("sv_maxidle_slots_countbots");
     sv_autotaunt = cvar("sv_autotaunt");
     sv_taunt = cvar("sv_taunt");
     sv_ready_restart = cvar("sv_ready_restart");
     sv_ready_restart_after_countdown = cvar("sv_ready_restart_after_countdown");
     sv_ready_restart_repeatable = cvar("sv_ready_restart_repeatable");
     warmup_stage = cvar("g_warmup");
     warmup_limit = cvar("g_warmup_limit");
     g_warmup_allguns = cvar("g_warmup_allguns");
     g_warmup_allow_timeout = cvar("g_warmup_allow_timeout");
     if(cvar("g_campaign"))
         warmup_stage = 0; // no warmup during campaign
     g_pickup_respawntime_weapon = cvar("g_pickup_respawntime_weapon");
     g_pickup_respawntime_superweapon = cvar("g_pickup_respawntime_superweapon");
     g_pickup_respawntime_ammo = cvar("g_pickup_respawntime_ammo");
     g_pickup_respawntime_short = cvar("g_pickup_respawntime_short");
     g_pickup_respawntime_medium = cvar("g_pickup_respawntime_medium");
     g_pickup_respawntime_long = cvar("g_pickup_respawntime_long");
     g_pickup_respawntime_powerup = cvar("g_pickup_respawntime_powerup");
     g_pickup_respawntimejitter_weapon = cvar("g_pickup_respawntimejitter_weapon");
     g_pickup_respawntimejitter_superweapon = cvar("g_pickup_respawntimejitter_superweapon");
     g_pickup_respawntimejitter_ammo = cvar("g_pickup_respawntimejitter_ammo");
     g_pickup_respawntimejitter_short = cvar("g_pickup_respawntimejitter_short");
     g_pickup_respawntimejitter_medium = cvar("g_pickup_respawntimejitter_medium");
     g_pickup_respawntimejitter_long = cvar("g_pickup_respawntimejitter_long");
     g_pickup_respawntimejitter_powerup = cvar("g_pickup_respawntimejitter_powerup");
     g_weaponspeedfactor = cvar("g_weaponspeedfactor");
     g_weaponratefactor = cvar("g_weaponratefactor");
     g_weapondamagefactor = cvar("g_weapondamagefactor");
     g_weaponforcefactor = cvar("g_weaponforcefactor");
     g_weaponspreadfactor = cvar("g_weaponspreadfactor");
     g_pickup_shells = cvar("g_pickup_shells");
     g_pickup_shells_max = cvar("g_pickup_shells_max");
     g_pickup_nails = cvar("g_pickup_nails");
     g_pickup_nails_max = cvar("g_pickup_nails_max");
     g_pickup_rockets = cvar("g_pickup_rockets");
     g_pickup_rockets_max = cvar("g_pickup_rockets_max");
     g_pickup_cells = cvar("g_pickup_cells");
     g_pickup_cells_max = cvar("g_pickup_cells_max");
     g_pickup_plasma = cvar("g_pickup_plasma");
     g_pickup_plasma_max = cvar("g_pickup_plasma_max");
     g_pickup_fuel = cvar("g_pickup_fuel");
     g_pickup_fuel_jetpack = cvar("g_pickup_fuel_jetpack");
     g_pickup_fuel_max = cvar("g_pickup_fuel_max");
     g_pickup_armorsmall = cvar("g_pickup_armorsmall");
     g_pickup_armorsmall_max = cvar("g_pickup_armorsmall_max");
     g_pickup_armorsmall_anyway = cvar("g_pickup_armorsmall_anyway");
     g_pickup_armormedium = cvar("g_pickup_armormedium");
     g_pickup_armormedium_max = cvar("g_pickup_armormedium_max");
     g_pickup_armormedium_anyway = cvar("g_pickup_armormedium_anyway");
     g_pickup_armorbig = cvar("g_pickup_armorbig");
     g_pickup_armorbig_max = cvar("g_pickup_armorbig_max");
     g_pickup_armorbig_anyway = cvar("g_pickup_armorbig_anyway");
     g_pickup_armormega = cvar("g_pickup_armormega");
     g_pickup_armormega_max = cvar("g_pickup_armormega_max");
     g_pickup_armormega_anyway = cvar("g_pickup_armormega_anyway");
     g_pickup_healthsmall = cvar("g_pickup_healthsmall");
     g_pickup_healthsmall_max = cvar("g_pickup_healthsmall_max");
     g_pickup_healthsmall_anyway = cvar("g_pickup_healthsmall_anyway");
     g_pickup_healthmedium = cvar("g_pickup_healthmedium");
     g_pickup_healthmedium_max = cvar("g_pickup_healthmedium_max");
     g_pickup_healthmedium_anyway = cvar("g_pickup_healthmedium_anyway");
     g_pickup_healthbig = cvar("g_pickup_healthbig");
     g_pickup_healthbig_max = cvar("g_pickup_healthbig_max");
     g_pickup_healthbig_anyway = cvar("g_pickup_healthbig_anyway");
     g_pickup_healthmega = cvar("g_pickup_healthmega");
     g_pickup_healthmega_max = cvar("g_pickup_healthmega_max");
     g_pickup_healthmega_anyway = cvar("g_pickup_healthmega_anyway");
     g_pickup_ammo_anyway = cvar("g_pickup_ammo_anyway");
     g_pickup_weapons_anyway = cvar("g_pickup_weapons_anyway");
     g_weapon_stay = cvar(strcat("g_", GetGametype(), "_weapon_stay"));
     if(!g_weapon_stay)
         g_weapon_stay = cvar("g_weapon_stay");
     MUTATOR_CALLHOOK(ReadLevelCvars);
     if (!warmup_stage)
         game_starttime = time + cvar("g_start_delay");
     FOREACH(Weapons, it != WEP_Null, { it.wr_init(it); });
     readplayerstartcvars();
 }
void readplayerstartcvars ()
Definition at line 624 of file miscfunctions.qc.
References argv(), cvar(), cvar_string(), FOREACH, g_jetpack, g_warmup_allguns, g_weapon_stay, g_weaponarena, g_weaponarena_list, g_weaponarena_weapons, GetResource(), InitializeEntity(), INITPRIO_FINDTARGET, IT_UNLIMITED_AMMO, IT_UNLIMITED_SUPERWEAPONS, M_ARGV, Weapon::m_name, max(), MUTATOR_CALLHOOK, NULL, random_start_ammo, random_start_weapons_count, RES_BULLETS, RES_CELLS, RES_PLASMA, RES_ROCKETS, RES_SHELLS, SetResource(), spawn(), start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, start_weapons, start_weapons_default, start_weapons_defaultmask, strcat(), strlen(), strzone(), substring(), tokenize_console, want_weapon(), warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, warmup_start_health, warmup_start_weapons, warmup_start_weapons_default, warmup_start_weapons_defaultmask, weaponarena_available_all_update(), weaponarena_available_devall_update(), weaponarena_available_most_update(), weapons_all(), weapons_devall(), Weapons_fromstr(), and weapons_most().
Referenced by readlevelcvars().
 {
     float i, t;
     // initialize starting values for players
     start_weapons = '0 0 0';
     start_weapons_default = '0 0 0';
     start_weapons_defaultmask = '0 0 0';
     start_items = 0;
     start_ammo_shells = 0;
     start_ammo_nails = 0;
     start_ammo_rockets = 0;
     start_ammo_cells = 0;
     start_ammo_plasma = 0;
     if (random_start_ammo == NULL)
     {
         random_start_ammo = spawn();
     }
     start_health = cvar("g_balance_health_start");
     start_armorvalue = cvar("g_balance_armor_start");
     g_weaponarena = 0;
     g_weaponarena_weapons = '0 0 0';
     string s = cvar_string("g_weaponarena");
     MUTATOR_CALLHOOK(SetWeaponArena, s);
     s = M_ARGV(0, string);
     if (s == "0" || s == "")
     {
         // no arena
     }
     else if (s == "off")
     {
         // forcibly turn off weaponarena
     }
     else if (s == "all" || s == "1")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "All Weapons";
         g_weaponarena_weapons = weapons_all();
     }
     else if (s == "devall")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Dev All Weapons";
         g_weaponarena_weapons = weapons_devall();
     }
     else if (s == "most")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Most Weapons";
         g_weaponarena_weapons = weapons_most();
     }
     else if (s == "all_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "All Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_all_update, INITPRIO_FINDTARGET);
     }
     else if (s == "devall_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Dev All Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_devall_update, INITPRIO_FINDTARGET);
     }
     else if (s == "most_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Most Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_most_update, INITPRIO_FINDTARGET);
     }
     else if (s == "none")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "No Weapons";
     }
     else
     {
         g_weaponarena = 1;
         t = tokenize_console(s);
         g_weaponarena_list = "";
         for (i = 0; i < t; ++i)
         {
             s = argv(i);
             Weapon wep = Weapons_fromstr(s);
             if(wep != WEP_Null)
             {
                 g_weaponarena_weapons |= (wep.m_wepset);
                 g_weaponarena_list = strcat(g_weaponarena_list, wep.m_name, " & ");
             }
         }
         g_weaponarena_list = strzone(substring(g_weaponarena_list, 0, strlen(g_weaponarena_list) - 3));
     }
     if (g_weaponarena)
     {
         g_weapon_stay = 0; // incompatible
         start_weapons = g_weaponarena_weapons;
         start_items |= IT_UNLIMITED_AMMO | IT_UNLIMITED_SUPERWEAPONS;
     }
     else
     {
         FOREACH(Weapons, it != WEP_Null, {
             int w = want_weapon(it, false);
             WepSet s = it.m_wepset;
             if(w & 1)
                 start_weapons |= s;
             if(w & 2)
                 start_weapons_default |= s;
             if(w & 4)
                 start_weapons_defaultmask |= s;
         });
     }
     if(cvar("g_balance_superweapons_time") < 0)
         start_items |= IT_UNLIMITED_SUPERWEAPONS;
     if(!cvar("g_use_ammunition"))
         start_items |= IT_UNLIMITED_AMMO;
     if(start_items & IT_UNLIMITED_AMMO)
     {
         start_ammo_shells = 999;
         start_ammo_nails = 999;
         start_ammo_rockets = 999;
         start_ammo_cells = 999;
         start_ammo_plasma = 999;
         start_ammo_fuel = 999;
     }
     else
     {
         start_ammo_shells = cvar("g_start_ammo_shells");
         start_ammo_nails = cvar("g_start_ammo_nails");
         start_ammo_rockets = cvar("g_start_ammo_rockets");
         start_ammo_cells = cvar("g_start_ammo_cells");
         start_ammo_plasma = cvar("g_start_ammo_plasma");
         start_ammo_fuel = cvar("g_start_ammo_fuel");
         random_start_weapons_count = cvar("g_random_start_weapons_count");
         SetResource(random_start_ammo, RES_SHELLS, cvar("g_random_start_shells"));
         SetResource(random_start_ammo, RES_BULLETS, cvar("g_random_start_bullets"));
         SetResource(random_start_ammo, RES_ROCKETS,cvar("g_random_start_rockets"));
         SetResource(random_start_ammo, RES_CELLS, cvar("g_random_start_cells"));
         SetResource(random_start_ammo, RES_PLASMA, cvar("g_random_start_plasma"));
     }
     warmup_start_ammo_shells = start_ammo_shells;
     warmup_start_ammo_nails = start_ammo_nails;
     warmup_start_ammo_rockets = start_ammo_rockets;
     warmup_start_ammo_cells = start_ammo_cells;
     warmup_start_ammo_plasma = start_ammo_plasma;
     warmup_start_ammo_fuel = start_ammo_fuel;
     warmup_start_health = start_health;
     warmup_start_armorvalue = start_armorvalue;
     warmup_start_weapons = start_weapons;
     warmup_start_weapons_default = start_weapons_default;
     warmup_start_weapons_defaultmask = start_weapons_defaultmask;
     if (!g_weaponarena)
     {
         warmup_start_ammo_shells = cvar("g_warmup_start_ammo_shells");
         warmup_start_ammo_nails = cvar("g_warmup_start_ammo_nails");
         warmup_start_ammo_rockets = cvar("g_warmup_start_ammo_rockets");
         warmup_start_ammo_cells = cvar("g_warmup_start_ammo_cells");
         warmup_start_ammo_plasma = cvar("g_warmup_start_ammo_plasma");
         warmup_start_ammo_fuel = cvar("g_warmup_start_ammo_fuel");
         warmup_start_health = cvar("g_warmup_start_health");
         warmup_start_armorvalue = cvar("g_warmup_start_armor");
         warmup_start_weapons = '0 0 0';
         warmup_start_weapons_default = '0 0 0';
         warmup_start_weapons_defaultmask = '0 0 0';
         FOREACH(Weapons, it != WEP_Null, {
             int w = want_weapon(it, g_warmup_allguns);
             WepSet s = it.m_wepset;
             if(w & 1)
                 warmup_start_weapons |= s;
             if(w & 2)
                 warmup_start_weapons_default |= s;
             if(w & 4)
                 warmup_start_weapons_defaultmask |= s;
         });
     }
     if (g_jetpack)
         start_items |= ITEM_Jetpack.m_itemid;
     MUTATOR_CALLHOOK(SetStartItems);
     if (start_items & ITEM_Jetpack.m_itemid)
     {
         start_items |= ITEM_JetpackRegen.m_itemid;
         start_ammo_fuel = max(start_ammo_fuel, cvar("g_balance_fuel_rotstable"));
         warmup_start_ammo_fuel = max(warmup_start_ammo_fuel, cvar("g_balance_fuel_rotstable"));
     }
     start_ammo_shells = max(0, start_ammo_shells);
     start_ammo_nails = max(0, start_ammo_nails);
     start_ammo_rockets = max(0, start_ammo_rockets);
     start_ammo_cells = max(0, start_ammo_cells);
     start_ammo_plasma = max(0, start_ammo_plasma);
     start_ammo_fuel = max(0, start_ammo_fuel);
     SetResource(random_start_ammo, RES_SHELLS,
         max(0, GetResource(random_start_ammo, RES_SHELLS)));
     SetResource(random_start_ammo, RES_BULLETS,
         max(0, GetResource(random_start_ammo, RES_BULLETS)));
     SetResource(random_start_ammo, RES_ROCKETS,
         max(0, GetResource(random_start_ammo, RES_ROCKETS)));
     SetResource(random_start_ammo, RES_CELLS,
         max(0, GetResource(random_start_ammo, RES_CELLS)));
     SetResource(random_start_ammo, RES_PLASMA,
         max(0, GetResource(random_start_ammo, RES_PLASMA)));
     warmup_start_ammo_shells = max(0, warmup_start_ammo_shells);
     warmup_start_ammo_nails = max(0, warmup_start_ammo_nails);
     warmup_start_ammo_rockets = max(0, warmup_start_ammo_rockets);
     warmup_start_ammo_cells = max(0, warmup_start_ammo_cells);
     warmup_start_ammo_plasma = max(0, warmup_start_ammo_plasma);
     warmup_start_ammo_fuel = max(0, warmup_start_ammo_fuel);
 }
void remove_safely (entity e)
Definition at line 984 of file miscfunctions.qc.
References make_safe_for_remove().
Referenced by spawnfunc().
 {
     make_safe_for_remove(e);
     builtin_remove(e);
 }
void remove_unsafely (entity e)
Definition at line 977 of file miscfunctions.qc.
References error.
Referenced by InitializeEntitiesRun(), spawnfunc(), and StartFrame().
 {
     if(e.classname == "spike")
         error("Removing spikes is forbidden (crylink bug), please report");
     builtin_remove(e);
 }
void SetMovetypeFollow (entity ent, entity e)
Definition at line 1497 of file miscfunctions.qc.
References MOVETYPE_FOLLOW, set_movetype(), SOLID_NOT, and strzone().
Referenced by GrapplingHookTouch().
 {
     // FIXME this may not be warpzone aware
     set_movetype(ent, MOVETYPE_FOLLOW); // make the hole follow
     ent.solid = SOLID_NOT; // MOVETYPE_FOLLOW is always non-solid - this means this cannot be teleported by warpzones any more! Instead, we must notice when our owner gets teleported.
     ent.aiment = e; // make the hole follow bmodel
     ent.punchangle = e.angles; // the original angles of bmodel
     ent.view_ofs = ent.origin - e.origin; // relative origin
     ent.v_angle = ent.angles - e.angles; // relative angles
     ent.aiment_classname = strzone(e.classname);
     ent.aiment_deadflag = e.deadflag;
 }
bool sound_allowed (int dest, entity e)
Referenced by CSQCProjectile(), GrapplingHookSend(), Monster_Damage(), PlayerCorpseDamage(), PlayerDamage(), and vehicles_damage().
void soundat (entity e, vector o, float chan, string samp, float vol, float _atten)
void soundto (float dest, entity e, float chan, string samp, float vol, float atten)
Referenced by ons_GeneratorThink(), and UpdatePlayerSounds().
void soundtoat (float _dest, entity e, vector o, float chan, string samp, float vol, float _atten)
Referenced by FireRailgunBullet().
float spamsound (entity e, float chan, Sound samp, float vol, float _atten)
Referenced by Monster_Damage(), and vehicles_damage().
STATIC_INIT (g_ctrace_changed)
Definition at line 353 of file miscfunctions.qh.
References IL_NEW.
 { g_ctrace_changed = IL_NEW(); }
void stopsound (entity e, float chan)
Referenced by PutPlayerInServer().
void stopsoundto (float _dest, entity e, float chan)
Referenced by train_wait().
string strcat1 (string s)
Referenced by Ban_GetClientIP(), Ban_KickBanClient(), GetCvars(), GetCvars_handleString_Fixup(), and race_SendTime().
float tracebox_hits_box (vector start, vector mi, vector ma, vector end, vector thmi, vector thma)
Definition at line 1161 of file miscfunctions.qc.
References trace_hits_box().
 {
     return trace_hits_box(start, end, thmi - ma, thma - mi);
 }
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 203 of file antilag.qc.
References autocvar_g_antilag, CS(), IS_CLIENT, and traceline_antilag_force().
Referenced by crosshair_trace().
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
string uid2name (string myuid)
Definition at line 1251 of file miscfunctions.qc.
References db_get(), db_put(), db_remove, ServerProgsDB, and strcat().
Referenced by getladder(), MUTATOR_HOOKFUNCTION(), race_readName(), and race_setTime().
{
     string s;
     s = db_get(ServerProgsDB, strcat("/uid2name/", myuid));
     // FIXME remove this later after 0.6 release
     // convert old style broken records to correct style
     if(s == "")
     {
         s = db_get(ServerProgsDB, strcat("uid2name", myuid));
         if(s != "")
         {
             db_put(ServerProgsDB, strcat("/uid2name/", myuid), s);
             db_remove(ServerProgsDB, strcat("uid2name", myuid));
         }
     }
     if(s == "")
         s = "^1Unregistered Player";
     return s;
 }
void (entity this)
float want_weapon (entity weaponinfo, float allguns)
Definition at line 506 of file miscfunctions.qc.
References boolean, M_ARGV, MUTATOR_CALLHOOK, WEP_FLAG_HIDDEN, WEP_FLAG_MUTATORBLOCKED, WEP_FLAG_NORMAL, and WEP_FLAG_SPECIALATTACK.
Referenced by readplayerstartcvars(), and weapons_start().
 {
     int d = 0;
     bool allow_mutatorblocked = false;
     if(!weaponinfo.m_id)
         return 0;
     bool mutator_returnvalue = MUTATOR_CALLHOOK(WantWeapon, weaponinfo, d, allguns, allow_mutatorblocked);
     d = M_ARGV(1, float);
     allguns = M_ARGV(2, bool);
     allow_mutatorblocked = M_ARGV(3, bool);
     if(allguns)
         d = boolean((weaponinfo.spawnflags & WEP_FLAG_NORMAL) && !(weaponinfo.spawnflags & (WEP_FLAG_HIDDEN | WEP_FLAG_SPECIALATTACK)));
     else if(!mutator_returnvalue)
         d = !(!weaponinfo.weaponstart);
     if(!allow_mutatorblocked && (weaponinfo.spawnflags & WEP_FLAG_MUTATORBLOCKED)) // never default mutator blocked guns
         d = 0;
     float t = weaponinfo.weaponstartoverride;
     //LOG_INFOF("want_weapon: %s - d: %d t: %d\n", weaponinfo.netname, d, t);
     // bit order in t:
     // 1: want or not
     // 2: is default?
     // 4: is set by default?
     if(t < 0)
         t = 4 | (3 * d);
     else
         t |= (2 * d);
     return t;
 }
void WarpZone_crosshair_trace (entity pl)
Definition at line 75 of file miscfunctions.qc.
References ANTILAG_LATENCY, CS(), cursor_trace_endpos, cursor_trace_start, MOVE_NORMAL, normalize(), and WarpZone_traceline_antilag().
Referenced by crosshair_trace_plusvisibletriggers__is_wz(), crosshair_trace_waypoints(), and IMPULSE().
 {
     WarpZone_traceline_antilag(pl, CS(pl).cursor_trace_start, CS(pl).cursor_trace_start + normalize(CS(pl).cursor_trace_endpos - CS(pl).cursor_trace_start) * max_shot_distance, MOVE_NORMAL, pl, ANTILAG_LATENCY(pl));
 }
void WarpZone_crosshair_trace_plusvisibletriggers (entity pl)
Definition at line 49 of file miscfunctions.qc.
References crosshair_trace_plusvisibletriggers__is_wz().
Referenced by formatmessage(), and IMPULSE().
 {
     crosshair_trace_plusvisibletriggers__is_wz(pl, true);
 }
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 221 of file antilag.qc.
References autocvar_g_antilag, CS(), IS_CLIENT, and WarpZone_traceline_antilag_force().
Referenced by FireRailgunBullet(), W_SetupShot_Dir_ProjectileSize_Range(), and WarpZone_crosshair_trace().
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     WarpZone_traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
void write_recordmarker (entity pl, float tstart, float dt)
Definition at line 1402 of file miscfunctions.qc.
References ftos(), GameLogEcho(), GetGametype(), strcat(), stuffcmd, TIME_ENCODE, and TIME_ENCODED_TOSTRING.
Referenced by ctf_CaptureRecord(), and race_setTime().
 {
     GameLogEcho(strcat(":recordset:", ftos(pl.playerid), ":", ftos(dt)));
     // also write a marker into demo files for demotc-race-record-extractor to find
     stuffcmd(pl,
              strcat(
                  strcat("//", strconv(2, 0, 0, GetGametype()), " RECORD SET ", TIME_ENCODED_TOSTRING(TIME_ENCODE(dt))),
                  " ", ftos(tstart), " ", ftos(dt), "\n"));
 }
Variable Documentation
string autocvar_g_random_start_weapons
Holds a list of possible random start weapons.
Definition at line 200 of file miscfunctions.qh.
Referenced by PutPlayerInServer().
vector dropped_origin
Definition at line 32 of file miscfunctions.qh.
Referenced by DropToFloor_Handler().
entity eliminatedPlayers
Definition at line 34 of file miscfunctions.qh.
Referenced by EliminatedPlayers_Init(), EliminatedPlayers_SendEntity(), freezetag_count_alive_players(), and MUTATOR_HOOKFUNCTION().
IntrusiveList g_ctrace_changed
Definition at line 352 of file miscfunctions.qh.
Referenced by crosshair_trace_plusvisibletriggers__is_wz().
float g_pickup_cells_max
Definition at line 173 of file miscfunctions.qh.
Referenced by GetResourceLimit().
float g_pickup_fuel_max
Definition at line 175 of file miscfunctions.qh.
float g_pickup_nails_max
Definition at line 171 of file miscfunctions.qh.
Referenced by GetResourceLimit().
float g_pickup_plasma_max
Definition at line 174 of file miscfunctions.qh.
Referenced by GetResourceLimit().
float g_pickup_rockets_max
Definition at line 172 of file miscfunctions.qh.
Referenced by GetResourceLimit().
float g_pickup_shells_max
Definition at line 170 of file miscfunctions.qh.
Referenced by GetResourceLimit().
float g_pickup_weapons_anyway
Definition at line 176 of file miscfunctions.qh.
Referenced by weapon_defaultspawnfunc().
float g_weapon_stay
Definition at line 218 of file miscfunctions.qh.
Referenced by getwelcomemessage(), readplayerstartcvars(), and W_ThrowNewWeapon().
float g_weaponarena
Definition at line 177 of file miscfunctions.qh.
Referenced by getwelcomemessage(), MUTATOR_HOOKFUNCTION(), NIX_CanChooseWeapon(), readplayerstartcvars(), and W_IsWeaponThrowable().
string g_weaponarena_list
Definition at line 180 of file miscfunctions.qh.
Referenced by getwelcomemessage(), and readplayerstartcvars().
float g_weaponarena_random
Definition at line 179 of file miscfunctions.qh.
Referenced by getwelcomemessage(), and MUTATOR_HOOKFUNCTION().
WepSet g_weaponarena_weapons
Definition at line 178 of file miscfunctions.qh.
Referenced by ClientConnect(), havocbot_chooseweapon(), NIX_CanChooseWeapon(), readplayerstartcvars(), weaponarena_available_all_update(), weaponarena_available_devall_update(), and weaponarena_available_most_update().
float g_weapondamagefactor
Definition at line 183 of file miscfunctions.qh.
Referenced by Damage().
float g_weaponforcefactor
Definition at line 184 of file miscfunctions.qh.
Referenced by Damage().
float g_weaponratefactor
Definition at line 182 of file miscfunctions.qh.
Referenced by W_WeaponRateFactor(), and weapon_thinkf().
float g_weaponspeedfactor
Definition at line 181 of file miscfunctions.qh.
Referenced by W_WeaponSpeedFactor().
float g_weaponspreadfactor
Definition at line 185 of file miscfunctions.qh.
Referenced by W_SetupProjVelocity_Explicit().
entity initialize_entity_first
Definition at line 343 of file miscfunctions.qh.
Referenced by InitializeEntitiesRun(), InitializeEntity(), and make_safe_for_remove().
entity initialize_entity_next
Definition at line 342 of file miscfunctions.qh.
int initialize_entity_order
Definition at line 341 of file miscfunctions.qh.
const int INITPRIO_DROPTOFLOOR = 20
Definition at line 335 of file miscfunctions.qh.
const int INITPRIO_FINDTARGET = 10
Definition at line 334 of file miscfunctions.qh.
const int INITPRIO_FIRST = 0
Definition at line 331 of file miscfunctions.qh.
const int INITPRIO_GAMETYPE = 0
Definition at line 332 of file miscfunctions.qh.
const int INITPRIO_GAMETYPE_FALLBACK = 1
Definition at line 333 of file miscfunctions.qh.
const int INITPRIO_LAST = 99
Definition at line 338 of file miscfunctions.qh.
const int INITPRIO_LINKDOORS = 91
Definition at line 337 of file miscfunctions.qh.
const int INITPRIO_SETLOCATION = 90
Definition at line 336 of file miscfunctions.qh.
float logfile
Definition at line 139 of file miscfunctions.qh.
Referenced by GameLogClose(), and GameLogEcho().
float logfile_open
Definition at line 138 of file miscfunctions.qh.
Referenced by GameLogClose(), GameLogEcho(), and GameLogInit().
entity nearest_entity[NUM_NEAREST_ENTITIES]
Definition at line 164 of file miscfunctions.qh.
Referenced by findnearest().
float nearest_length[NUM_NEAREST_ENTITIES]
Definition at line 165 of file miscfunctions.qh.
Referenced by findnearest().
const float NUM_NEAREST_ENTITIES = 4
Definition at line 163 of file miscfunctions.qh.
Referenced by findnearest().
entity random_start_ammo
Entity that contains amount of ammo to give with random start weapons.
Definition at line 203 of file miscfunctions.qh.
Referenced by PutPlayerInServer(), and readplayerstartcvars().
int random_start_weapons_count
Number of random start weapons to give to players.
Definition at line 198 of file miscfunctions.qh.
Referenced by PutPlayerInServer(), and readplayerstartcvars().
float start_ammo_cells
Definition at line 194 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_ammo_fuel
Definition at line 196 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_ammo_nails
Definition at line 192 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_ammo_plasma
Definition at line 195 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_ammo_rockets
Definition at line 193 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_ammo_shells
Definition at line 191 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), and target_init_use().
float start_armorvalue
Definition at line 205 of file miscfunctions.qh.
Referenced by ctf_FlagcarrierWaypoints(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), and target_init_use().
float start_health
Definition at line 204 of file miscfunctions.qh.
Referenced by ctf_FlagcarrierWaypoints(), Freeze(), MUTATOR_HOOKFUNCTION(), PlayerPreThink(), PutPlayerInServer(), readplayerstartcvars(), smneg_multiplier(), target_init_use(), and Unfreeze().
int start_items
Definition at line 190 of file miscfunctions.qh.
Referenced by buff_Available(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
WepSet start_weapons
Definition at line 187 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), target_init_use(), weaponarena_available_all_update(), weaponarena_available_devall_update(), and weaponarena_available_most_update().
WepSet start_weapons_default
Definition at line 188 of file miscfunctions.qh.
Referenced by readplayerstartcvars().
WepSet start_weapons_defaultmask
Definition at line 189 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and readplayerstartcvars().
float sv_autotaunt
Definition at line 223 of file miscfunctions.qh.
Referenced by UpdatePlayerSounds().
float sv_taunt
Definition at line 224 of file miscfunctions.qh.
Referenced by UpdatePlayerSounds().
float warmup_start_ammo_cells
Definition at line 213 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_ammo_fuel
Definition at line 215 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_ammo_nails
Definition at line 211 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_ammo_plasma
Definition at line 214 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_ammo_rockets
Definition at line 212 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_ammo_shells
Definition at line 210 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_armorvalue
Definition at line 217 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
float warmup_start_health
Definition at line 216 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), and readplayerstartcvars().
WepSet warmup_start_weapons
Definition at line 206 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), readplayerstartcvars(), weaponarena_available_all_update(), weaponarena_available_devall_update(), and weaponarena_available_most_update().
WepSet warmup_start_weapons_default
Definition at line 207 of file miscfunctions.qh.
Referenced by readplayerstartcvars().
WepSet warmup_start_weapons_defaultmask
Definition at line 208 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and readplayerstartcvars().