Xonotic: menu/command/menu_cmd.qh File Reference
menu/command/menu_cmd.qh File Reference
Defines
#define MENU_CMD_H
Functions
void GameCommand (string command)
Define Documentation
#define MENU_CMD_H
Definition at line 2 of file menu_cmd.qh.
Function Documentation
void GameCommand (string command)
Definition at line 533 of file cl_cmd.qc.
References _dumptree_close(), _dumptree_open(), _dumptree_space, argv(), BanCommand(), BanCommand_macro_help(), BanCommand_macro_usage(), CommonCommand_macro_command(), CommonCommand_macro_help(), CommonCommand_macro_usage(), CSQC_ConsoleCommand(), cvar(), depthfirst(), firstChild, FOREACH_ENTITY_ORDERED, GameCommand_macro_command(), GameCommand_macro_help(), GameCommand_macro_usage(), GenericCommand(), GenericCommand_macro_help(), GenericCommand_macro_usage(), isdemo(), LAMBDA, LocalCommand_macro_command(), LocalCommand_macro_help(), LocalCommand_macro_usage(), LOG_INFO, LOG_INFOF, m_goto(), m_play_click_sound(), m_sync(), main, MENU_SOUND_OPEN, MUTATOR_CALLHOOK, nextSibling, NULL, parent, s, startsWith, strcat(), string_null, strlen(), strtolower(), substring(), tokenize_console, updateConwidths(), and world.
{
    int argc = tokenize_console(command);
    // Guide for working with argc arguments by example:
    // argc:   1    - 2      - 3     - 4
    // argv:   0    - 1      - 2     - 3
    // cmd     vote - master - login - password
    string s = strtolower(argv(0));
    if (s == "help")
    {
        if (argc == 1)
        {
            LOG_INFO("\nClient console commands:\n");
            LocalCommand_macro_help();
            LOG_INFO("\nGeneric commands shared by all programs:\n");
            GenericCommand_macro_help();
            LOG_INFO("\nUsage:^3 cl_cmd COMMAND...^7, where possible commands are listed above.\n");
            LOG_INFO("For help about a specific command, type cl_cmd help COMMAND\n");
            return;
        }
        else if (GenericCommand_macro_usage(argc))  // Instead of trying to call a command, we're going to see detailed information about it
        {
            return;
        }
        else if (LocalCommand_macro_usage(argc))  // now try for normal commands too
        {
            return;
        }
    }
    // continue as usual and scan for normal commands
    if (GenericCommand(command)                                    // handled by common/command/generic.qc
        || LocalCommand_macro_command(argc, command)               // handled by one of the above LocalCommand_* functions
        || MUTATOR_CALLHOOK(CSQC_ConsoleCommand, s, argc, command) // handled by a mutator
       ) return;
    // nothing above caught the command, must be invalid
    LOG_INFO(((command != "") ? strcat("Unknown client command \"", command, "\"") : "No command provided"), ". For a list of supported commands, try cl_cmd help.\n");
}