Xonotic: common/gamemodes/gamemode/race/sv_race.qh File Reference
sv_race.qh File Reference
#include <common/mutators/base.qh>
Functions
void race_Initialize ()
void rc_SetLimits ()
REGISTER_MUTATOR (rc, false)
Function Documentation
race_Initialize()
void race_Initialize ()
Definition at line 398 of file sv_race.qc.
References g_race_qualifying, race_ScoreRules(), and warmup_stage.
Referenced by REGISTER_MUTATOR().
 {
     race_ScoreRules();
     if(g_race_qualifying == 2)
         warmup_stage = 0;
     radar_showenemies = true;
 }
rc_SetLimits()
void rc_SetLimits ()
Definition at line 406 of file sv_race.qc.
References autocvar_g_campaign, autocvar_g_race_laps_limit, autocvar_g_race_qualifying_timelimit, autocvar_g_race_qualifying_timelimit_override, autocvar_g_race_teams, BITS, bound(), g_race_qualifying, GameRules_limit_lead(), GameRules_limit_score(), GameRules_limit_time(), GameRules_limit_time_qualifying(), GameRules_teams(), independent_players, race_fraglimit, race_leadlimit, RACE_RECORD, race_teams, race_timelimit, and record_type.
Referenced by REGISTER_MUTATOR().
 {
     int fraglimit_override, leadlimit_override;
     float timelimit_override, qualifying_override;
     if(autocvar_g_race_teams)
     {
         GameRules_teams(true);
         race_teams = BITS(bound(2, autocvar_g_race_teams, 4));
     }
     else
         race_teams = 0;
     qualifying_override = autocvar_g_race_qualifying_timelimit_override;
     fraglimit_override = autocvar_g_race_laps_limit;
     leadlimit_override = 0; // currently not supported by race
     timelimit_override = autocvar_timelimit_override;
     float want_qualifying = ((qualifying_override >= 0) ? qualifying_override : autocvar_g_race_qualifying_timelimit) > 0;
     record_type = RACE_RECORD;
     if(autocvar_g_campaign)
     {
         g_race_qualifying = 1;
         independent_players = 1;
     }
     else if(want_qualifying)
     {
         g_race_qualifying = 2;
         independent_players = 1;
         race_fraglimit = (fraglimit_override >= 0) ? fraglimit_override : autocvar_fraglimit;
         race_leadlimit = (leadlimit_override >= 0) ? leadlimit_override : autocvar_leadlimit;
         race_timelimit = (timelimit_override >= 0) ? timelimit_override : autocvar_timelimit;
         qualifying_override = (qualifying_override >= 0) ? qualifying_override : autocvar_g_race_qualifying_timelimit;
         fraglimit_override = 0;
         leadlimit_override = 0;
         timelimit_override = qualifying_override;
     }
     else
         g_race_qualifying = 0;
     GameRules_limit_score(fraglimit_override);
     GameRules_limit_lead(leadlimit_override);
     GameRules_limit_time(timelimit_override);
     GameRules_limit_time_qualifying(qualifying_override);
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (rc , false)
Definition at line 7 of file sv_race.qh.
References MUTATOR_ONADD, MUTATOR_STATIC, race_Initialize(), and rc_SetLimits().
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         rc_SetLimits();
         race_Initialize();
     }
     return 0;
 }