Xonotic: common/gamemodes/gamemode/domination/cl_domination.qh File Reference
cl_domination.qh File Reference
Functions
void HUD_Mod_Dom (vector myPos, vector mySize)
void HUD_Mod_Dom_Export (int fh)
Function Documentation
void HUD_Mod_Dom (vector myPos, vector mySize)
Definition at line 64 of file cl_domination.qc.
References autocvar_hud_panel_modicons_dom_layout, ceil(), DrawDomItem(), HUD_GetRowCount(), mod_active, team_count, vec2, and vector().
Referenced by Domination::m_configuremenu().
 {
     mod_active = 1; // required in each mod function that always shows something
     int layout = autocvar_hud_panel_modicons_dom_layout;
     int rows, columns;
     float aspect_ratio;
     aspect_ratio = (layout) ? 3 : 1;
     rows = HUD_GetRowCount(team_count, mySize, aspect_ratio);
     columns = ceil(team_count/rows);
     int i;
     float row = 0, column = 0;
     vector pos, itemSize;
     itemSize = vec2(mySize.x / columns, mySize.y / rows);
     for(i=0; i<team_count; ++i)
     {
         pos = myPos + vec2(column * itemSize.x, row * itemSize.y);
         DrawDomItem(pos, itemSize, aspect_ratio, layout, i);
         ++row;
         if(row >= rows)
         {
             row = 0;
             ++column;
         }
     }
 }
void HUD_Mod_Dom_Export (int fh)
Definition at line 6 of file cl_domination.qc.
References HUD_Write_Cvar.
Referenced by Domination::m_configuremenu().
 {
     HUD_Write_Cvar("hud_panel_modicons_dom_layout");
 }