Xonotic: Keyframe Class Reference
Keyframe Class Reference
Public Member Functions
virtual void addAnim ()
virtual void addEasing ()
ATTRIB (Keyframe, currentChild, entity)
ATTRIB (Keyframe, firstChild, entity)
ATTRIB (Keyframe, lastChild, entity)
ATTRIB (Animation, m_framenames, string)
ATTRIB (Animation, object, entity)
virtual void calcValue ()
virtual void configureAnimation ()
virtual void describe ()
virtual void display ()
virtual void finishAnim ()
virtual void isFinished ()
virtual void isStopped ()
virtual void resumeAnim ()
virtual void setObjectSetter ()
void setterDummy (Animation this, float)
virtual void setTimeStartDuration ()
virtual void setTimeStartEnd ()
virtual void setValueStartDelta ()
virtual void setValueStartEnd ()
virtual void stopAnim ()
virtual void tick ()
virtual void update ()
void (Animation this, float) setter
Public Attributes
float delta = 0
float duration = 0
float finished = false
return
float startTime = 0
float startValue = 0
float stopped = false
float value = 0
Detailed Description
Definition at line 4 of file keyframe.qh.
Member Function Documentation
void Keyframe::addAnim () virtual
Definition at line 52 of file keyframe.qc.
References entity(), error, firstChild, NULL, and other.
     {
         if (other.parent) error("Can't add already added anim!");
         if (other.isFinished(other)) error("Can't add finished anim!");
         other.parent = this;
         entity l = this.lastChild;
         if (l)
         {
             l.nextSibling = other;
         }
         else
         {
             this.currentChild = other;
             this.firstChild = other;
         }
         other.prevSibling = l;
         other.nextSibling = NULL;
         this.lastChild = other;
     }
void Keyframe::addEasing () virtual
Definition at line 24 of file keyframe.qc.
References entity(), getNewChildDuration(), getNewChildStart(), getNewChildValue(), makeEasing(), and other.
     {
         entity other = makeEasing(this.object, this.setter, func, getNewChildStart(this), getNewChildDuration(this, animDurationTime), getNewChildValue(this), animEnd);
         this.addAnim(this, other);
         return other;
     }
Keyframe::ATTRIB (Keyframe , currentChild , entity)
Keyframe::ATTRIB (Keyframe , firstChild , entity)
Keyframe::ATTRIB (Keyframe , lastChild , entity)
Animation::ATTRIB (Animation , m_framenames , string) inherited
Animation::ATTRIB (Animation , object , entity) inherited
void Keyframe::calcValue () virtual
Reimplemented from Animation.
Definition at line 77 of file keyframe.qc.
     {
         if (this.currentChild)
             if (this.currentChild.isFinished(this.currentChild)) this.currentChild = this.currentChild.nextSibling;
         if (this.currentChild)
         {
             this.currentChild.tick(this.currentChild, tickTime);
             return this.currentChild.value;
         }
         return animStartValue + animDelta;
     }
void Animation::configureAnimation () virtual inherited
Definition at line 5 of file animation.qc.
     {
         this.setObjectSetter(this, obj, objSetter);
         this.setTimeStartDuration(this, animStartTime, animDuration);
         this.setValueStartEnd(this, animStartValue, animEndValue);
     }
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
void Animation::finishAnim () virtual inherited
Definition at line 83 of file animation.qc.
     {
         this.value = this.delta + this.startValue;
         this.finished = true;
         this.setter(this.object, this.value);
     }
void Animation::isFinished () virtual inherited
Definition at line 78 of file animation.qc.
     {
         return this.finished;
     }
void Animation::isStopped () virtual inherited
Definition at line 63 of file animation.qc.
     {
         return this.stopped;
     }
void Animation::resumeAnim () virtual inherited
Definition at line 73 of file animation.qc.
     {
         this.stopped = false;
     }
void Animation::setObjectSetter () virtual inherited
Definition at line 42 of file animation.qc.
     {
         this.object = o;
         this.setter = s;
     }
void Animation::setterDummy (Animation this, float) inline inherited
Definition at line 19 of file animation.qh.
 {}
void Animation::setTimeStartDuration () virtual inherited
Definition at line 24 of file animation.qc.
     {
         this.startTime = s;
         this.duration = d;
     }
void Animation::setTimeStartEnd () virtual inherited
Definition at line 18 of file animation.qc.
     {
         this.startTime = s;
         this.duration = e - s;
     }
void Animation::setValueStartDelta () virtual inherited
Definition at line 36 of file animation.qc.
     {
         this.startValue = s;
         this.delta = d;
     }
void Animation::setValueStartEnd () virtual inherited
Definition at line 30 of file animation.qc.
     {
         this.startValue = s;
         this.delta = e - s;
     }
void Animation::stopAnim () virtual inherited
Definition at line 68 of file animation.qc.
     {
         this.stopped = true;
     }
void Animation::tick () virtual inherited
Definition at line 48 of file animation.qc.
     {
         if (this.isStopped(this) || this.isFinished(this) || (tickTime < this.startTime)) return;
         if (tickTime >= (this.startTime + this.duration)) this.finishAnim(this);
         else this.value = this.calcValue(this, (tickTime - this.startTime), this.duration, this.startValue, this.delta);
         this.setter(this.object, this.value);
     }
void Animation::update () virtual inherited
Definition at line 12 of file animation.qc.
References time.
     {
         this.setTimeStartDuration(this, time, animDuration);
         this.setValueStartEnd(this, animStartValue, animEndValue);
     }
Animation::void (Animation this, float) inherited
Member Data Documentation
float Animation::delta = 0 inherited
Definition at line 25 of file animation.qh.
float Animation::duration = 0 inherited
Definition at line 23 of file animation.qh.
float Animation::finished = false inherited
Definition at line 27 of file animation.qh.
Animation::return inherited
Initial value:
{
        FOREACH_WORD(this.m_framenames, true, {
            int f = frameforname(mdlidx, it);
            if (f != -1) return f;
        })
Definition at line 13 of file animdecide.qh.
float Animation::startTime = 0 inherited
Definition at line 22 of file animation.qh.
float Animation::startValue = 0 inherited
Definition at line 24 of file animation.qh.
float Animation::stopped = false inherited
Definition at line 26 of file animation.qh.
float Animation::value = 0 inherited
Definition at line 21 of file animation.qh.
The documentation for this class was generated from the following files:
menu/anim/keyframe.qh
menu/anim/keyframe.qc