Xonotic: menu/xonotic/credits.qh File Reference
credits.qh File Reference
#include "listbox.qh"
Classes
class XonoticCreditsList
Functions
int credits_get ()
entity makeXonoticCreditsList ()
Function Documentation
credits_get()
int credits_get ()
Definition at line 409 of file credits.qc.
References _CREDITS_PERSON, buf_create, CREDITS, CREDITS_FUNCTION, CREDITS_NL, CREDITS_PERSON, and CREDITS_TITLE.
Referenced by XonoticCreditsList_configureXonoticCreditsList().
 {
     int n = buf_create();
     #define CREDITS_TITLE(t) bufstr_add(n, strcat("**", t), 0);
     #define CREDITS_FUNCTION(f) bufstr_add(n, strcat("*", f), 0);
     #define CREDITS_PERSON(p) bufstr_add(n, p, 0);
     #define _CREDITS_PERSON(p) CREDITS_PERSON(#p)
     #define CREDITS_NL() bufstr_add(n, "", 0);
     CREDITS(CREDITS_TITLE, CREDITS_FUNCTION, _CREDITS_PERSON, CREDITS_PERSON, CREDITS_NL)
     #undef CREDITS_TITLE
     #undef CREDITS_FUNCTION
     #undef CREDITS_PERSON
     #undef _CREDITS_PERSON
     #undef CREDITS_NL
     return n;
 }
makeXonoticCreditsList()
entity makeXonoticCreditsList ()
Definition at line 428 of file credits.qc.
References entity(), and NEW.
Referenced by XonoticCreditsDialog_fill().
 {
     entity me;
     me = NEW(XonoticCreditsList);
     me.configureXonoticCreditsList(me);
     return me;
 }