Xonotic: common/effects/effectinfo.inc File Reference
effectinfo.inc File Reference
#include "effectinfo_gentle.inc"
#include "effectinfo_gentle_morphed.inc"
#include "effectinfo_gentle_particlegibs.inc"
#include "effectinfo_onslaught.inc"
#include "effectinfo_gentle_happy.inc"
#include "effectinfo_vehicles.inc"
#include "effectinfo_ctf.inc"
#include "effectinfo_nades.inc"
#include "effectinfo_buffs.inc"
#include "effectinfo_instagib.inc"
Macros
#define flare(name, colormin, colormax)
#define ground_quake(name, colormin, colormax)
#define spawn_event(name, color)
#define spawn_point(name, color)
#define TE_TEI_G3(name, colormin1, colormax1, colormin2, colormax2)
Functions
DEF (TE_WIZSPIKE)
DEF (TE_KNIGHTSPIKE)
DEF (TE_SPIKE)
DEF (TE_SPIKEQUAD)
DEF (TE_SUPERSPIKE)
DEF (TE_SUPERSPIKEQUAD)
DEF (TE_GUNSHOT)
DEF (TE_GUNSHOTQUAD)
DEF (TE_EXPLOSION)
DEF (TE_EXPLOSIONQUAD)
DEF (TE_TAREXPLOSION)
DEF (TE_BLOOD)
DEF (TE_SPARK)
DEF (TE_PLASMABURN)
DEF (TE_SMALLFLASH)
DEF (TE_FLAMEJET)
DEF (TE_LAVASPLASH)
DEF (TE_TELEPORT)
DEF (TE_TEI_G3)
DEF (TE_TEI_SMOKE)
DEF (TE_TEI_BIGEXPLOSION)
DEF (TE_TEI_PLASMAHIT)
DEF (blood)
DEF (teleport)
DEF (TR_BLOOD)
DEF (TR_SLIGHTBLOOD)
DEF (EF_STARDUST)
DEF (item_respawn)
DEF (jumppad_activate)
DEF (laser_muzzleflash)
DEF (laser_impact)
DEF (shotgun_muzzleflash)
DEF (shotgun_impact)
DEF (uzi_muzzleflash)
DEF (machinegun_impact)
DEF (grenadelauncher_muzzleflash)
DEF (TR_GRENADE)
DEF (TR_KNIGHTSPIKE)
DEF (grenade_explode)
DEF (electro_muzzleflash)
DEF (TR_NEXUIZPLASMA)
DEF (electro_impact)
DEF (electro_ballexplode)
DEF (electro_combo)
DEF (crylink_muzzleflash)
DEF (crylink_impact)
DEF (nex_muzzleflash)
DEF (nex_beam)
DEF (nex_impact)
DEF (hagar_muzzleflash)
DEF (hagar_bounce)
DEF (hagar_explode)
DEF (rocketlauncher_muzzleflash)
DEF (TR_ROCKET)
DEF (rocket_explode)
DEF (grapple_muzzleflash)
DEF (grapple_impact)
DEF (nex242_misc_laser_beam)
DEF (nex242_misc_laser_beam_end)
DEF (nex242_misc_laser_beam_fast)
DEF (nex242_misc_laser_beam_fast_end)
DEF (nex242_misc_laser_green_beam)
DEF (nex242_misc_laser_green_beam_end)
DEF (nex242_misc_laser_blue_beam)
DEF (nex242_misc_laser_blue_beam_end)
DEF (nex242_misc_laser_yellow_beam)
DEF (nex242_misc_laser_yellow_beam_end)
DEF (nex242_misc_laser_cyan_beam)
DEF (nex242_misc_laser_cyan_beam_end)
DEF (nex242_misc_laser_magenta_beam)
DEF (nex242_misc_laser_magenta_beam_end)
DEF (nex242_misc_laser_white_beam)
DEF (nex242_misc_laser_white_beam_end)
DEF (nex242_misc_laser_black_beam)
DEF (nex242_misc_laser_black_beam_end)
DEF (nex242_misc_laser_orange_beam)
DEF (nex242_misc_laser_orange_beam_end)
DEF (crylink_impactbig)
DEF (laser_deadly)
DEF (torch_small)
DEF (fountain01)
DEF (hookbomb_explode)
DEF (EF_MGTURRETTRAIL)
DEF (fire_big)
DEF (smoke_ring)
DEF (smoke_large)
DEF (sparks)
DEF (electricity_sparks)
DEF (steam)
DEF (smoking)
DEF (goldendust)
DEF (healing_fx)
DEF (armorrepair_fx)
DEF (ammoregen_fx)
DEF (rage)
DEF (iceorglass)
DEF (poisonfield)
DEF (icefield)
DEF (firefield)
DEF (flamethrower)
DEF (TR_WIZSPIKE)
DEF (TR_VORESPIKE)
DEF (flac_explode)
DEF (tr_bullet)
DEF (smoking_smallemitter)
DEF (TR_CRYLINKPLASMA)
DEF (cherryblossom)
DEF (alien_blood)
DEF (robot_blood)
DEF (alien_TR_BLOOD)
DEF (robot_TR_BLOOD)
DEF (alien_TR_SLIGHTBLOOD)
DEF (robot_TR_SLIGHTBLOOD)
DEF (item_pickup)
DEF (bloodshower)
DEF (alien_bloodshower)
DEF (robot_bloodshower)
DEF (TE_TEI_G3_HIT)
DEF (firemine)
DEF (fireball)
DEF (fireball_laser)
DEF (fireball_explode)
DEF (fireball_muzzleflash)
DEF (fireball_preattack_muzzleflash)
DEF (fireball_bfgdamage)
DEF (EF_FLAME)
DEF (tr_rifle)
DEF (rocket_guide)
DEF (laser_gauntlet)
DEF (laser_gauntletmuzzleflash)
DEF (torchflame)
DEF (electro_lightning)
DEF (gauntlet_lightning)
DEF (crylink_joinexplode)
DEF (kaball_sparks)
DEF (tr_rifle_weak)
DEF (red_smoke)
DEF (pipe_smoke)
DEF (TR_SEEKER)
DEF (explosion_big)
DEF (explosion_medium)
DEF (explosion_small)
DEF (smoke_big)
DEF (smoke_small)
DEF (impact_metal)
DEF (impact_stone)
DEF (impact_wood)
DEF (impact_flesh)
DEF (tr_hagar)
DEF (damage_blaster)
DEF (damage_shotgun)
DEF (alien_damage_shotgun)
DEF (robot_damage_shotgun)
DEF (damage_machinegun)
DEF (alien_damage_machinegun)
DEF (robot_damage_machinegun)
DEF (damage_minelayer)
DEF (damage_mortar)
DEF (damage_arc)
DEF (damage_electro)
DEF (damage_crylink)
DEF (damage_hlac)
DEF (damage_vortex)
DEF (damage_vaporizer)
DEF (damage_rifle)
DEF (damage_rifle_alien)
DEF (damage_rifle_robot)
DEF (damage_seeker)
DEF (damage_hagar)
DEF (damage_fireball)
DEF (damage_devastator)
DEF (fireflies)
DEF (healray_muzzleflash)
DEF (healray_impact)
DEF (bigplasma_muzzleflash)
DEF (bigplasma_impact)
DEF (shockwave_attack)
DEF (arc_lightning)
DEF (arc_beam)
DEF (arc_beam_heal)
DEF (arc_beam_healimpact)
DEF (arc_smoke)
DEF (arc_overheat)
DEF (arc_overheat_fire)
DEF (arc_muzzleflash)
DEF (arc_bolt_explode)
DEF (tr_bullet_weak)
flare (red,"0xff0000","0xdc7171") flare(blue
ground_quake (red,"0x9E6A64","0x91302D") ground_quake(blue
spawn_event (blue,"0x0F0FFF") spawn_event(yellow
spawn_event (pink,"0xFF0FFF") spawn_event(neutral
spawn_point (red,"0xFF0F0F") spawn_point(blue
spawn_point (yellow,"0xFFFF0F") spawn_point(pink
spawn_point (neutral,"0xFFFFFF") spawn_event(red
SUB (TE_WIZSPIKE)
SUB (TE_KNIGHTSPIKE)
SUB (TE_SPIKE)
SUB (TE_SPIKEQUAD)
SUB (TE_SUPERSPIKE)
SUB (TE_SUPERSPIKEQUAD)
SUB (TE_GUNSHOT)
SUB (TE_GUNSHOTQUAD)
SUB (TE_EXPLOSION)
SUB (TE_EXPLOSIONQUAD)
SUB (TE_TAREXPLOSION)
SUB (TE_BLOOD)
SUB (TE_SPARK)
SUB (TE_PLASMABURN)
SUB (TE_SMALLFLASH)
SUB (TE_FLAMEJET)
SUB (TE_LAVASPLASH)
SUB (TE_TELEPORT)
SUB (TE_TEI_G3)
SUB (TE_TEI_SMOKE)
SUB (TE_TEI_BIGEXPLOSION)
SUB (TE_TEI_PLASMAHIT)
SUB (blood)
SUB (teleport)
SUB (TR_BLOOD)
SUB (TR_SLIGHTBLOOD)
SUB (EF_STARDUST)
SUB (item_respawn)
SUB (jumppad_activate)
SUB (laser_muzzleflash)
SUB (laser_impact)
SUB (shotgun_muzzleflash)
SUB (shotgun_impact)
SUB (uzi_muzzleflash)
SUB (machinegun_impact)
SUB (grenadelauncher_muzzleflash)
SUB (TR_GRENADE)
SUB (TR_KNIGHTSPIKE)
SUB (grenade_explode)
SUB (electro_muzzleflash)
SUB (TR_NEXUIZPLASMA)
SUB (electro_impact)
SUB (electro_ballexplode)
SUB (electro_combo)
SUB (crylink_muzzleflash)
SUB (crylink_impact)
SUB (nex_muzzleflash)
SUB (nex_beam)
SUB (nex_impact)
SUB (hagar_muzzleflash)
SUB (hagar_bounce)
SUB (hagar_explode)
SUB (rocketlauncher_muzzleflash)
SUB (TR_ROCKET)
SUB (rocket_explode)
SUB (grapple_muzzleflash)
SUB (grapple_impact)
SUB (nex242_misc_laser_beam)
SUB (nex242_misc_laser_beam_end)
SUB (nex242_misc_laser_beam_fast)
SUB (nex242_misc_laser_beam_fast_end)
SUB (nex242_misc_laser_green_beam)
SUB (nex242_misc_laser_green_beam_end)
SUB (nex242_misc_laser_blue_beam)
SUB (nex242_misc_laser_blue_beam_end)
SUB (nex242_misc_laser_yellow_beam)
SUB (nex242_misc_laser_yellow_beam_end)
SUB (nex242_misc_laser_cyan_beam)
SUB (nex242_misc_laser_cyan_beam_end)
SUB (nex242_misc_laser_magenta_beam)
SUB (nex242_misc_laser_magenta_beam_end)
SUB (nex242_misc_laser_white_beam)
SUB (nex242_misc_laser_white_beam_end)
SUB (nex242_misc_laser_black_beam)
SUB (nex242_misc_laser_black_beam_end)
SUB (nex242_misc_laser_orange_beam)
SUB (nex242_misc_laser_orange_beam_end)
SUB (crylink_impactbig)
SUB (laser_deadly)
SUB (torch_small)
SUB (fountain01)
SUB (hookbomb_explode)
SUB (EF_MGTURRETTRAIL)
SUB (fire_big)
SUB (smoke_ring)
SUB (smoke_large)
SUB (sparks)
SUB (electricity_sparks)
SUB (steam)
SUB (smoking)
SUB (goldendust)
SUB (healing_fx)
SUB (armorrepair_fx)
SUB (ammoregen_fx)
SUB (rage)
SUB (iceorglass)
SUB (poisonfield)
SUB (icefield)
SUB (firefield)
SUB (flamethrower)
SUB (TR_WIZSPIKE)
SUB (TR_VORESPIKE)
SUB (flac_explode)
SUB (tr_bullet)
SUB (smoking_smallemitter)
SUB (TR_CRYLINKPLASMA)
SUB (cherryblossom)
SUB (alien_blood)
SUB (robot_blood)
SUB (alien_TR_BLOOD)
SUB (robot_TR_BLOOD)
SUB (alien_TR_SLIGHTBLOOD)
SUB (robot_TR_SLIGHTBLOOD)
SUB (item_pickup)
SUB (bloodshower)
SUB (alien_bloodshower)
SUB (robot_bloodshower)
SUB (TE_TEI_G3_HIT)
SUB (firemine)
SUB (fireball)
SUB (fireball_laser)
SUB (fireball_explode)
SUB (fireball_muzzleflash)
SUB (fireball_preattack_muzzleflash)
SUB (fireball_bfgdamage)
SUB (EF_FLAME)
SUB (tr_rifle)
SUB (rocket_guide)
SUB (laser_gauntlet)
SUB (laser_gauntletmuzzleflash)
SUB (torchflame)
SUB (electro_lightning)
SUB (gauntlet_lightning)
SUB (crylink_joinexplode)
SUB (kaball_sparks)
SUB (tr_rifle_weak)
SUB (red_smoke)
SUB (pipe_smoke)
SUB (TR_SEEKER)
SUB (explosion_big)
SUB (explosion_medium)
SUB (explosion_small)
SUB (smoke_big)
SUB (smoke_small)
SUB (impact_metal)
SUB (impact_stone)
SUB (impact_wood)
SUB (impact_flesh)
SUB (tr_hagar)
SUB (damage_blaster)
SUB (damage_shotgun)
SUB (alien_damage_shotgun)
SUB (robot_damage_shotgun)
SUB (damage_machinegun)
SUB (alien_damage_machinegun)
SUB (robot_damage_machinegun)
SUB (damage_minelayer)
SUB (damage_mortar)
SUB (damage_arc)
SUB (damage_electro)
SUB (damage_crylink)
SUB (damage_hlac)
SUB (damage_vortex)
SUB (damage_vaporizer)
SUB (damage_rifle)
SUB (damage_rifle_alien)
SUB (damage_rifle_robot)
SUB (damage_seeker)
SUB (damage_hagar)
SUB (damage_fireball)
SUB (damage_devastator)
SUB (fireflies)
SUB (healray_muzzleflash)
SUB (healray_impact)
SUB (bigplasma_muzzleflash)
SUB (bigplasma_impact)
SUB (shockwave_attack)
SUB (arc_lightning)
SUB (arc_beam)
SUB (arc_beam_heal)
SUB (arc_beam_healimpact)
SUB (arc_smoke)
SUB (arc_overheat)
SUB (arc_overheat_fire)
SUB (arc_muzzleflash)
SUB (arc_bolt_explode)
SUB (tr_bullet_weak)
Macro Definition Documentation
#define flare (name, colormin, colormax)
Value:
DEF(name##_flare); \
    SUB(name##_flare) /* smoke */ { \
        MY(alpha_min) = 200; \
        MY(alpha_max) = 256; \
        MY(alpha_fade) = 160; \
        MY(bounce) = 1; \
        MY(color_min) = colormin; \
        MY(color_max) = colormax; \
        MY(count) = 10.500000; \
        MY(gravity) = -0.240000; \
        MY(originjitter) = '2.0 2.0 0.0'; \
        MY(sizeincrease) = 11; \
        MY(size_min) = 1; \
        MY(size_max) = 11; \
        MY(tex_max) = 8; \
        MY(type) = "alphastatic"; \
        MY(velocityjitter) = '15.0 15.0 30.0'; \
    }
Definition at line 3734 of file effectinfo.inc.
#define ground_quake (name, colormin, colormax)
Definition at line 4988 of file effectinfo.inc.
#define spawn_event (name, color)
#define spawn_point (name, color)
Value:
DEF(spawn_point_##name); \
    SUB(spawn_point_##name) { \
        MY(airfriction) = 0.200000; \
        MY(alpha_min) = 64; \
        MY(alpha_max) = 128; \
        MY(alpha_fade) = 128; \
        MY(color_min) = color; \
        MY(color_max) = color; \
        MY(count) = 37.500000; \
        MY(gravity) = -0.100000; \
        MY(liquidfriction) = 0.800000; \
        MY(originjitter) = '16.0 16.0 64.0'; \
        MY(size_min) = 1; \
        MY(size_max) = 2; \
        MY(type) = "static"; \
        MY(velocityjitter) = '32.0 32.0 0.0'; \
    }
Definition at line 8500 of file effectinfo.inc.
Referenced by invasion_SpawnChosenMonster().
#define TE_TEI_G3 (name, colormin1, colormax1, colormin2, colormax2)
Definition at line 5078 of file effectinfo.inc.
Referenced by SUB().
Function Documentation
DEF (TE_WIZSPIKE)
Referenced by SUB().
DEF (TE_KNIGHTSPIKE)
DEF (TE_SPIKE)
DEF (TE_SPIKEQUAD)
DEF (TE_SUPERSPIKE)
DEF (TE_SUPERSPIKEQUAD)
DEF (TE_GUNSHOT)
DEF (TE_GUNSHOTQUAD)
DEF (TE_EXPLOSION)
DEF (TE_EXPLOSIONQUAD)
DEF (TE_TAREXPLOSION)
DEF (TE_BLOOD)
DEF (TE_SPARK)
DEF (TE_PLASMABURN)
DEF (TE_SMALLFLASH)
DEF (TE_FLAMEJET)
DEF (TE_LAVASPLASH)
DEF (TE_TELEPORT)
DEF (TE_TEI_G3)
DEF (TE_TEI_SMOKE)
DEF (TE_TEI_BIGEXPLOSION)
DEF (TE_TEI_PLASMAHIT)
DEF (blood)
DEF (teleport)
DEF (TR_BLOOD)
DEF (TR_SLIGHTBLOOD)
DEF (EF_STARDUST)
DEF (item_respawn)
DEF (jumppad_activate)
DEF (laser_muzzleflash)
DEF (laser_impact)
DEF (shotgun_muzzleflash)
DEF (shotgun_impact)
DEF (uzi_muzzleflash)
DEF (machinegun_impact)
DEF (grenadelauncher_muzzleflash)
DEF (TR_GRENADE)
DEF (TR_KNIGHTSPIKE)
DEF (grenade_explode)
DEF (electro_muzzleflash)
DEF (TR_NEXUIZPLASMA)
DEF (electro_impact)
DEF (electro_ballexplode)
DEF (electro_combo)
DEF (crylink_muzzleflash)
DEF (crylink_impact)
DEF (nex_muzzleflash)
DEF (nex_beam)
DEF (nex_impact)
DEF (hagar_muzzleflash)
DEF (hagar_bounce)
DEF (hagar_explode)
DEF (rocketlauncher_muzzleflash)
DEF (TR_ROCKET)
DEF (rocket_explode)
DEF (grapple_muzzleflash)
DEF (grapple_impact)
DEF (nex242_misc_laser_beam)
DEF (nex242_misc_laser_beam_end)
DEF (nex242_misc_laser_beam_fast)
DEF (nex242_misc_laser_beam_fast_end)
DEF (nex242_misc_laser_green_beam)
DEF (nex242_misc_laser_green_beam_end)
DEF (nex242_misc_laser_blue_beam)
DEF (nex242_misc_laser_blue_beam_end)
DEF (nex242_misc_laser_yellow_beam)
DEF (nex242_misc_laser_yellow_beam_end)
DEF (nex242_misc_laser_cyan_beam)
DEF (nex242_misc_laser_cyan_beam_end)
DEF (nex242_misc_laser_magenta_beam)
DEF (nex242_misc_laser_magenta_beam_end)
DEF (nex242_misc_laser_white_beam)
DEF (nex242_misc_laser_white_beam_end)
DEF (nex242_misc_laser_black_beam)
DEF (nex242_misc_laser_black_beam_end)
DEF (nex242_misc_laser_orange_beam)
DEF (nex242_misc_laser_orange_beam_end)
DEF (crylink_impactbig)
DEF (laser_deadly)
DEF (torch_small)
DEF (fountain01)
DEF (hookbomb_explode)
DEF (EF_MGTURRETTRAIL)
DEF (fire_big)
DEF (smoke_ring)
DEF (smoke_large)
DEF (sparks)
DEF (electricity_sparks)
DEF (steam)
DEF (smoking)
DEF (goldendust)
DEF (healing_fx)
DEF (armorrepair_fx)
DEF (ammoregen_fx)
DEF (rage)
DEF (iceorglass)
DEF (poisonfield)
DEF (icefield)
DEF (firefield)
DEF (flamethrower)
DEF (TR_WIZSPIKE)
DEF (TR_VORESPIKE)
DEF (flac_explode)
DEF (tr_bullet)
DEF (smoking_smallemitter)
DEF (TR_CRYLINKPLASMA)
DEF (cherryblossom)
DEF (alien_blood)
DEF (robot_blood)
DEF (alien_TR_BLOOD)
DEF (robot_TR_BLOOD)
DEF (alien_TR_SLIGHTBLOOD)
DEF (robot_TR_SLIGHTBLOOD)
DEF (item_pickup)
DEF (bloodshower)
DEF (alien_bloodshower)
DEF (robot_bloodshower)
DEF (TE_TEI_G3_HIT)
DEF (firemine)
DEF (fireball)
DEF (fireball_laser)
DEF (fireball_explode)
DEF (fireball_muzzleflash)
DEF (fireball_preattack_muzzleflash)
DEF (fireball_bfgdamage)
DEF (EF_FLAME)
DEF (tr_rifle)
DEF (rocket_guide)
DEF (laser_gauntlet)
DEF (laser_gauntletmuzzleflash)
DEF (torchflame)
DEF (electro_lightning)
DEF (gauntlet_lightning)
DEF (crylink_joinexplode)
DEF (kaball_sparks)
DEF (tr_rifle_weak)
DEF (red_smoke)
DEF (pipe_smoke)
DEF (TR_SEEKER)
DEF (explosion_big)
DEF (explosion_medium)
DEF (explosion_small)
DEF (smoke_big)
DEF (smoke_small)
DEF (impact_metal)
DEF (impact_stone)
DEF (impact_wood)
DEF (impact_flesh)
DEF (tr_hagar)
DEF (damage_blaster)
DEF (damage_shotgun)
DEF (alien_damage_shotgun)
DEF (robot_damage_shotgun)
DEF (damage_machinegun)
DEF (alien_damage_machinegun)
DEF (robot_damage_machinegun)
DEF (damage_minelayer)
DEF (damage_mortar)
DEF (damage_arc)
DEF (damage_electro)
DEF (damage_crylink)
DEF (damage_hlac)
DEF (damage_vortex)
DEF (damage_vaporizer)
DEF (damage_rifle)
DEF (damage_rifle_alien)
DEF (damage_rifle_robot)
DEF (damage_seeker)
DEF (damage_hagar)
DEF (damage_fireball)
DEF (damage_devastator)
DEF (fireflies)
DEF (healray_muzzleflash)
DEF (healray_impact)
DEF (bigplasma_muzzleflash)
DEF (bigplasma_impact)
DEF (shockwave_attack)
DEF (arc_lightning)
DEF (arc_beam)
DEF (arc_beam_heal)
DEF (arc_beam_healimpact)
DEF (arc_smoke)
DEF (arc_overheat)
DEF (arc_overheat_fire)
DEF (arc_muzzleflash)
DEF (arc_bolt_explode)
DEF (tr_bullet_weak)
flare (red , "0xff0000" , "0xdc7171")
ground_quake (red , "0x9E6A64" , "0x91302D")
spawn_event (blue , "0x0F0FFF")
spawn_event (pink , "0xFF0FFF")
spawn_point (red , "0xFF0F0F")
spawn_point (yellow , "0xFFFF0F")
spawn_point (neutral , "0xFFFFFF")
SUB (TE_WIZSPIKE)
Definition at line 13 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, TE_KNIGHTSPIKE, and TE_WIZSPIKE.
Referenced by SUB().
                  {
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 128;
     MY(color_min) = "0x63F2EA";
     MY(color_max) = "0x63f2EA";
     MY(countabsolute) = 1;
     MY(lightcolor) = '0.4 0.9 0.9';
     MY(lightradiusfade) = 200;
     MY(lightradius) = 200;
     MY(size_min) = 20;
     MY(size_max) = 20;
     MY(type) = "static";
 }
SUB (TE_KNIGHTSPIKE)
Definition at line 47 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, SUB(), TE_KNIGHTSPIKE, and TE_SPIKE.
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 0.2 0.2';
     MY(lightradiusfade) = 1000;
     MY(lightradius) = 200;
     MY(originjitter) = '16.0 16.0 16.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (TE_SPIKE)
Definition at line 94 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_SPIKE, and TE_SPIKEQUAD.
               {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (TE_SPIKEQUAD)
Definition at line 153 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, SUB(), TE_SPIKEQUAD, and TE_SUPERSPIKE.
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '2.0 2.5 3.0';
     MY(lightradiusfade) = 200;
     MY(lightradius) = 400;
     MY(originjitter) = '34.0 34.0 34.0';
     MY(size_min) = 64;
     MY(size_max) = 64;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (TE_SUPERSPIKE)
Definition at line 201 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_SUPERSPIKE, and TE_SUPERSPIKEQUAD.
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (TE_SUPERSPIKEQUAD)
Definition at line 260 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_GUNSHOT, and TE_SUPERSPIKEQUAD.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '0.2 0.2 1.5';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 100;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (TE_GUNSHOT)
Definition at line 322 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_GUNSHOT, and TE_GUNSHOTQUAD.
                 {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (TE_GUNSHOTQUAD)
Definition at line 381 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_EXPLOSION, and TE_GUNSHOTQUAD.
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '12.0 12.0 12.0';
     MY(size_min) = 8;
     MY(size_max) = 8;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (TE_EXPLOSION)
Definition at line 426 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_EXPLOSION, and TE_EXPLOSIONQUAD.
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 2.0 0.5';
     MY(lightradiusfade) = 300;
     MY(lightradius) = 150;
     MY(originjitter) = '40.0 40.0 40.0';
     MY(size_min) = 48;
     MY(size_max) = 48;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (TE_EXPLOSIONQUAD)
Definition at line 517 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_EXPLOSIONQUAD, and TE_TAREXPLOSION.
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 2.0 8.0';
     MY(lightradiusfade) = 700;
     MY(lightradius) = 350;
     MY(originjitter) = '40.0 40.0 40.0';
     MY(size_min) = 48;
     MY(size_max) = 48;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (TE_TAREXPLOSION)
Definition at line 587 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, SUB(), TE_BLOOD, and TE_TAREXPLOSION.
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '1.6 0.8 2.0';
     MY(lightradiusfade) = 1200;
     MY(lightradius) = 600;
     MY(originjitter) = '40.0 40.0 40.0';
     MY(size_min) = 48;
     MY(size_max) = 48;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (TE_BLOOD)
Definition at line 656 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), and MY.
               {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(count) = 0.167000;
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 8;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 1;
 }
SUB (TE_SPARK)
Definition at line 679 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
               {
     MY(alpha_min) = 64;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.600000;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 1;
     MY(velocityoffset) = '0.0 0.0 80.0';
 }
SUB (TE_PLASMABURN)
Definition at line 701 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '1.0 1.0 1.0';
     MY(lightradiusfade) = 400;
     MY(lightradius) = 200;
     MY(originjitter) = '16.0 16.0 16.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (TE_SMALLFLASH)
Definition at line 748 of file effectinfo.inc.
References DEF(), and MY.
                    {
     MY(lightcolor) = '2.0 2.0 2.0';
     MY(lightradiusfade) = 1000;
     MY(lightradius) = 200;
 }
SUB (TE_FLAMEJET)
Definition at line 756 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and TE_LAVASPLASH.
                  {
     MY(airfriction) = 1;
     MY(alpha_min) = 64;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 384;
     MY(bounce) = 1.100000;
     MY(color_min) = "0x6f0f00";
     MY(color_max) = "0xe3974f";
     MY(count) = 0.500000;
     MY(gravity) = -1;
     MY(liquidfriction) = 4;
     MY(size_min) = 4;
     MY(size_max) = 4;
     MY(type) = "smoke";
     MY(velocityjitter) = '128.0 128.0 128.0';
     MY(velocitymultiplier) = 1;
 }
SUB (TE_LAVASPLASH)
Definition at line 776 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and TE_TELEPORT.
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x6f0f00";
     MY(color_max) = "0xe3974f";
     MY(count) = 32;
     MY(gravity) = 0.050000;
     MY(originjitter) = '128.0 128.0 32.0';
     MY(originoffset) = '0.0 0.0 32.0';
     MY(size_min) = 12;
     MY(size_max) = 12;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '128.0 128.0 0.0';
     MY(velocityoffset) = '0.0 0.0 256.0';
 }
SUB (TE_TELEPORT)
Definition at line 795 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and TE_TEI_G3.
                  {
     MY(airfriction) = 1;
     MY(alpha_min) = 64;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xA0A0A0";
     MY(color_max) = "0xFFFFFF";
     MY(count) = 56;
     MY(liquidfriction) = 4;
     MY(originjitter) = '16.0 16.0 28.0';
     MY(originoffset) = '0.0 0.0 28.0';
     MY(size_min) = 10;
     MY(size_max) = 10;
     MY(type) = "static";
     MY(velocityjitter) = '0.0 0.0 256.0';
 }
SUB (TE_TEI_G3)
Definition at line 814 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), MY, SUB(), and TE_TEI_G3.
                {
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xFFFFFF";
     MY(color_max) = "0xFFFFFF";
     MY(countabsolute) = 1;
     MY(size_min) = 4;
     MY(size_max) = 4;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (TE_TEI_SMOKE)
Definition at line 843 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and originjitter.
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 0.167000;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 1;
 }
SUB (TE_TEI_BIGEXPLOSION)
Definition at line 862 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 2.0 0.5';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 500;
     MY(originjitter) = '40.0 40.0 40.0';
     MY(size_min) = 72;
     MY(size_max) = 72;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (TE_TEI_PLASMAHIT)
Definition at line 953 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '2.4 4.8 8.0';
     MY(lightradiusfade) = 600;
     MY(lightradius) = 200;
     MY(originjitter) = '20.0 20.0 20.0';
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (blood)
Definition at line 998 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
            {
     MY(airfriction) = 0.400000;
     MY(alpha_min) = 1560;
     MY(alpha_max) = 2560;
     MY(alpha_fade) = 7000;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 0.400000;
     MY(sizeincrease) = 20;
     MY(size_min) = 5;
     MY(size_max) = 11;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 20;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "spark";
     MY(velocityjitter) = '99.0 99.0 55.0';
 }
SUB (teleport)
Definition at line 1043 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
               {
     MY(airfriction) = 2;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 100;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x807aff";
     MY(color_max) = "0x4463d5";
     MY(count) = 500;
     MY(originjitter) = '1.0 1.0 1.0';
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(stretchfactor) = 0.600000;
     MY(tex_min) = 64;
     MY(tex_max) = 64;
     MY(type) = "spark";
     MY(velocityjitter) = '1000.0 1000.0 1500.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (TR_BLOOD)
Definition at line 1078 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
               {
     MY(airfriction) = -2;
     MY(alpha_min) = 384;
     MY(alpha_max) = 984;
     MY(alpha_fade) = 1492;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFF";
     MY(gravity) = 0.400000;
     MY(liquidfriction) = 1;
     MY(sizeincrease) = -5;
     MY(size_min) = 4;
     MY(size_max) = 19;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 7;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 20;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = -0.100000;
 }
SUB (TR_SLIGHTBLOOD)
Definition at line 1124 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), EF_STARDUST, and MY.
                     {
     MY(airfriction) = 1;
     MY(alpha_min) = 384;
     MY(alpha_max) = 384;
     MY(alpha_fade) = 192;
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFF";
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 8;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 64;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (EF_STARDUST)
Definition at line 1149 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                  {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 64;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 128;
     MY(color_min) = "0xfff368";
     MY(color_max) = "0xfff368";
     MY(count) = 37.500000;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '16.0 16.0 64.0';
     MY(size_min) = 1;
     MY(size_max) = 2;
     MY(type) = "static";
     MY(velocityjitter) = '32.0 32.0 0.0';
 }
SUB (item_respawn)
Definition at line 1168 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
                   {
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 128;
     MY(color_min) = "0x63F2EA";
     MY(color_max) = "0x63f2EA";
     MY(countabsolute) = 1;
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(type) = "static";
 }
SUB (jumppad_activate)
Definition at line 1196 of file effectinfo.inc.
References DEF(), and MY.
                       {
     MY(lightcolor) = '2.0 2.0 2.0';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
 }
SUB (laser_muzzleflash)
Definition at line 1204 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 10;
     MY(alpha_min) = 256;
     MY(alpha_max) = 512;
     MY(alpha_fade) = 6280;
     MY(color_min) = "0xcc0000";
     MY(color_max) = "0xff0000";
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.0 0.1 0.1';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(sizeincrease) = -100;
     MY(size_min) = 10;
     MY(size_max) = 15;
     MY(stretchfactor) = 2;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
 }
SUB (laser_impact)
Definition at line 1270 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 0.4 0.4';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 200;
     MY(originjitter) = '14.0 14.0 14.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (shotgun_muzzleflash)
Definition at line 1332 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 1.500000;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = 12;
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.050000;
 }
SUB (shotgun_impact)
Definition at line 1372 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(size_min) = 5;
     MY(size_max) = 8;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (uzi_muzzleflash)
Definition at line 1449 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "static";
     MY(velocityjitter) = '1.0 1.0 1.0';
     MY(velocitymultiplier) = 0.030000;
 }
SUB (machinegun_impact)
Definition at line 1488 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '6.0 3.6 0.6';
     MY(lightradiusfade) = 800;
     MY(lightradius) = 80;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (grenadelauncher_muzzleflash)
Definition at line 1592 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 12;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 1.500000;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '20.0 20.0 20.0';
     MY(velocitymultiplier) = 0.030000;
 }
SUB (TR_GRENADE)
Definition at line 1632 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, originjitter, and SUB().
                 {
     MY(alpha_min) = 300;
     MY(alpha_max) = 400;
     MY(alpha_fade) = 780;
     MY(bounce) = 1;
     MY(color_min) = "0x101010";
     MY(color_max) = "0x000000";
     MY(originjitter) = '1.0 1.0 1.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 3;
     MY(size_max) = 2;
     MY(tex_max) = 8;
     MY(trailspacing) = 4;
     MY(type) = "smoke";
     MY(velocityjitter) = '1.0 1.0 1.0';
     MY(velocitymultiplier) = -0.020000;
 }
SUB (TR_KNIGHTSPIKE)
Definition at line 1691 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 300;
     MY(alpha_max) = 400;
     MY(alpha_fade) = 600;
     MY(bounce) = 1;
     MY(color_min) = "0x303030";
     MY(color_max) = "0x000000";
     MY(gravity) = -0.110000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(sizeincrease) = 11;
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_max) = 8;
     MY(trailspacing) = 6;
     MY(type) = "smoke";
     MY(velocityjitter) = '3.0 3.0 3.0';
     MY(velocitymultiplier) = -0.020000;
 }
SUB (grenade_explode)
Definition at line 1747 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 1.0';
     MY(lightradiusfade) = 400;
     MY(lightradius) = 250;
     MY(originjitter) = '26.0 26.0 26.0';
     MY(size_min) = 48;
     MY(size_max) = 48;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (electro_muzzleflash)
Definition at line 1903 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x283880";
     MY(color_max) = "0x283880";
     MY(countabsolute) = 1;
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = -10;
     MY(size_min) = 15;
     MY(size_max) = 15;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (TR_NEXUIZPLASMA)
Definition at line 1964 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 968;
     MY(color_min) = "0x283880";
     MY(color_max) = "0x283880";
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradius) = 90;
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 38;
     MY(tex_max) = 38;
     MY(trailspacing) = 2;
     MY(type) = "static";
     MY(velocitymultiplier) = -0.100000;
 }
SUB (electro_impact)
Definition at line 2004 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.1 4.4 10.0';
     MY(lightradiusfade) = 250;
     MY(lightradius) = 250;
     MY(originjitter) = '17.0 17.0 17.0';
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (electro_ballexplode)
Definition at line 2092 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.1 4.4 10.0';
     MY(lightradiusfade) = 250;
     MY(lightradius) = 250;
     MY(originjitter) = '17.0 17.0 17.0';
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (electro_combo)
Definition at line 2156 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 5.0 6.0';
     MY(lightradiusfade) = 300;
     MY(lightradius) = 400;
     MY(originjitter) = '17.0 17.0 17.0';
     MY(size_min) = 64;
     MY(size_max) = 64;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (crylink_muzzleflash)
Definition at line 2254 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 2024;
     MY(color_min) = "0xdd9cff";
     MY(color_max) = "0xff0090";
     MY(count) = 0.500000;
     MY(lightcolor) = '1.6 0.2 2.0';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(size_min) = 15;
     MY(size_max) = 20;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
     MY(velocitymultiplier) = 0.010000;
 }
SUB (crylink_impact)
Definition at line 2291 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '12.0 12.0 12.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (nex_muzzleflash)
Definition at line 2360 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                      {
     MY(airfriction) = 9;
     MY(alpha_min) = 328;
     MY(alpha_max) = 328;
     MY(alpha_fade) = 4000;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x0072ff";
     MY(count) = 12;
     MY(lightcolor) = '2.0 2.5 3.0';
     MY(lightradiusfade) = 200;
     MY(lightradius) = 200;
     MY(originjitter) = '4.0 4.0 4.0';
     MY(sizeincrease) = -100;
     MY(size_min) = 16;
     MY(size_max) = 16;
     MY(stretchfactor) = 2;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "spark";
     MY(velocityjitter) = '180.0 180.0 180.0';
     MY(velocitymultiplier) = 1.400000;
 }
SUB (nex_beam)
Definition at line 2401 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
               {
     MY(airfriction) = 5;
     MY(alpha_min) = 64;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x1680A0";
     MY(color_max) = "0x1680A0";
     MY(sizeincrease) = 2;
     MY(size_min) = 4;
     MY(size_max) = 4;
     MY(tex_min) = 32;
     MY(tex_max) = 32;
     MY(trailspacing) = 64;
     MY(type) = "static";
 }
SUB (nex_impact)
Definition at line 2463 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                 {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 6.0 8.0';
     MY(lightradiusfade) = 250;
     MY(lightradius) = 200;
     MY(originjitter) = '14.0 14.0 14.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (hagar_muzzleflash)
Definition at line 2582 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 2;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (hagar_bounce)
Definition at line 2623 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 2;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 300;
     MY(lightradius) = 60;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (hagar_explode)
Definition at line 2662 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 1.0';
     MY(lightradiusfade) = 400;
     MY(lightradius) = 120;
     MY(originjitter) = '14.0 14.0 14.0';
     MY(size_min) = 28;
     MY(size_max) = 38;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (rocketlauncher_muzzleflash)
Definition at line 2780 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 2;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 10;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = 20;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '40.0 40.0 40.0';
     MY(velocitymultiplier) = -0.130000;
 }
SUB (TR_ROCKET)
Definition at line 2823 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, originjitter, and SUB().
                {
     MY(alpha_min) = 200;
     MY(alpha_max) = 300;
     MY(alpha_fade) = 200;
     MY(bounce) = 1;
     MY(color_min) = "0x000000";
     MY(color_max) = "0x666666";
     MY(lightcolor) = '6.0 3.0 1.0';
     MY(lightradius) = 150;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = 11;
     MY(size_min) = 3;
     MY(size_max) = 4;
     MY(tex_max) = 8;
     MY(trailspacing) = 10;
     MY(type) = "smoke";
     MY(velocityjitter) = '3.0 3.0 3.0';
     MY(velocitymultiplier) = -0.020000;
 }
SUB (rocket_explode)
Definition at line 2907 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 1.0';
     MY(lightradiusfade) = 750;
     MY(lightradius) = 400;
     MY(originjitter) = '23.0 23.0 23.0';
     MY(size_min) = 72;
     MY(size_max) = 72;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (grapple_muzzleflash)
Definition at line 3063 of file effectinfo.inc.
References DEF(), and MY.
{
     MY(lightcolor) = '1.0 0.0 0.0';
     MY(lightradiusfade) = 800;
     MY(lightradius) = 160;
 }
SUB (grapple_impact)
Definition at line 3070 of file effectinfo.inc.
References DEF(), and MY.
                     {
     MY(lightcolor) = '1.0 0.0 0.0';
     MY(lightradiusfade) = 800;
     MY(lightradius) = 160;
 }
SUB (nex242_misc_laser_beam)
Definition at line 3077 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xff0000";
     MY(color_max) = "0xff0000";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_beam_end)
Definition at line 3093 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_beam_fast)
Definition at line 3110 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 640;
     MY(color_min) = "0xff0000";
     MY(color_max) = "0xff0000";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 0.100000;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_beam_fast_end)
Definition at line 3126 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_green_beam)
Definition at line 3143 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x00ff00";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_green_beam_end)
Definition at line 3159 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_blue_beam)
Definition at line 3176 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x0000ff";
     MY(color_max) = "0x0000ff";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_blue_beam_end)
Definition at line 3192 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_yellow_beam)
Definition at line 3209 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xffff00";
     MY(color_max) = "0xffff00";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_yellow_beam_end)
Definition at line 3225 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_cyan_beam)
Definition at line 3242 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x00ffff";
     MY(color_max) = "0x00ffff";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_cyan_beam_end)
Definition at line 3258 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_magenta_beam)
Definition at line 3275 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xff00ff";
     MY(color_max) = "0xff00ff";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_magenta_beam_end)
Definition at line 3291 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_white_beam)
Definition at line 3308 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0xffffff";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_white_beam_end)
Definition at line 3324 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_black_beam)
Definition at line 3341 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x000000";
     MY(color_max) = "0x000000";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_black_beam_end)
Definition at line 3357 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (nex242_misc_laser_orange_beam)
Definition at line 3374 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xff6600";
     MY(color_max) = "0xff6600";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 1;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (nex242_misc_laser_orange_beam_end)
Definition at line 3390 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
{
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 768;
     MY(bounce) = -1;
     MY(color_min) = "0x8f4333";
     MY(color_max) = "0xfff31b";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(size_min) = 0.400000;
     MY(size_max) = 0.400000;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 100;
 }
SUB (crylink_impactbig)
Definition at line 3409 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '12.0 12.0 12.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (laser_deadly)
Definition at line 3481 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 56;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (torch_small)
Definition at line 3535 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                  {
     MY(alpha_min) = 200;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 8;
     MY(gravity) = -0.500000;
     MY(originjitter) = '5.0 5.0 5.0';
     MY(sizeincrease) = -1;
     MY(size_min) = 1;
     MY(size_max) = 11;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '1.0 1.0 50.0';
 }
SUB (fountain01)
Definition at line 3571 of file effectinfo.inc.
References alpha_max, count, DEF(), gravity, MY, and originjitter.
                 {
     MY(alpha_max) = 100;
     MY(alpha_fade) = 100;
     MY(bounce) = 1;
     MY(color_min) = "0x7cbaff";
     MY(color_max) = "0xcfd1ff";
     MY(count) = 16;
     MY(gravity) = 0.600000;
     MY(originjitter) = '5.0 5.0 5.0';
     MY(sizeincrease) = 20;
     MY(size_min) = 10;
     MY(size_max) = 15;
     MY(tex_max) = 8;
     MY(type) = "snow";
     MY(velocityjitter) = '81.0 81.0 150.0';
     MY(velocitymultiplier) = 2;
 }
SUB (hookbomb_explode)
Definition at line 3591 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(airfriction) = 10;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 200;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x807aff";
     MY(color_max) = "0x4463d5";
     MY(count) = 25;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(sizeincrease) = -160;
     MY(size_min) = 150;
     MY(size_max) = 200;
     MY(tex_min) = 38;
     MY(tex_max) = 38;
     MY(type) = "static";
     MY(velocityjitter) = '550.0 550.0 550.0';
 }
SUB (EF_MGTURRETTRAIL)
Definition at line 3660 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
                       {
     MY(alpha_min) = 128;
     MY(alpha_max) = 196;
     MY(alpha_fade) = 768;
     MY(color_min) = "0xd0d0a0";
     MY(color_max) = "0xffffff";
     MY(gravity) = -0.010000;
     MY(notunderwater) = true;
     MY(sizeincrease) = -8;
     MY(size_min) = 5;
     MY(size_max) = 4;
     MY(tex_max) = 8;
     MY(trailspacing) = 10;
     MY(type) = "smoke";
 }
SUB (fire_big)
Definition at line 3697 of file effectinfo.inc.
References alpha_max, alpha_min, count, gravity, MY, originjitter, and SUB().
               {
     MY(alpha_min) = 200;
     MY(alpha_max) = 356;
     MY(alpha_fade) = 512;
     MY(bounce) = 2;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 26;
     MY(gravity) = -0.500000;
     MY(originjitter) = '33.0 33.0 33.0';
     MY(sizeincrease) = -3;
     MY(size_min) = 11;
     MY(size_max) = 31;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (smoke_ring)
Definition at line 3760 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
                 {
     MY(airfriction) = 3;
     MY(alpha_min) = 100;
     MY(alpha_max) = 156;
     MY(alpha_fade) = 200;
     MY(bounce) = 1.100000;
     MY(color_min) = "0x111111";
     MY(color_max) = "0x979797";
     MY(count) = 45;
     MY(gravity) = 0.100000;
     MY(notunderwater) = true;
     MY(sizeincrease) = 21;
     MY(size_min) = 1;
     MY(size_max) = 11;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '190.0 190.0 50.0';
 }
SUB (smoke_large)
Definition at line 3781 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
                  {
     MY(airfriction) = 7;
     MY(alpha_min) = 140;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 190;
     MY(bounce) = 1.100000;
     MY(color_min) = "0x9e895f";
     MY(color_max) = "0xffd39b";
     MY(count) = 25;
     MY(gravity) = -0.150000;
     MY(notunderwater) = true;
     MY(sizeincrease) = 21;
     MY(size_min) = 11;
     MY(size_max) = 21;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '390.0 390.0 390.0';
 }
SUB (sparks)
Definition at line 3801 of file effectinfo.inc.
References alpha_max, count, DEF(), gravity, MY, and originjitter.
             {
     MY(airfriction) = 3;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(bounce) = 1.500000;
     MY(color_min) = "0xFFFDD9";
     MY(color_max) = "0xFFFDD9";
     MY(count) = 15;
     MY(gravity) = 1;
     MY(originjitter) = '1.0 1.0 1.0';
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '300.0 300.0 200.0';
     MY(velocitymultiplier) = 1.500000;
 }
SUB (electricity_sparks)
Definition at line 3821 of file effectinfo.inc.
References alpha_max, count, DEF(), gravity, MY, and originjitter.
{
     MY(airfriction) = 3;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 556;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x807aff";
     MY(color_max) = "0x4463d5";
     MY(count) = 35;
     MY(gravity) = 1;
     MY(originjitter) = '1.0 1.0 1.0';
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '300.0 300.0 300.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (steam)
Definition at line 3841 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
            {
     MY(airfriction) = 5;
     MY(alpha_min) = 140;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 190;
     MY(bounce) = 1.100000;
     MY(color_min) = "0xfffbdf";
     MY(color_max) = "0xffffff";
     MY(count) = 1;
     MY(gravity) = -0.250000;
     MY(notunderwater) = true;
     MY(sizeincrease) = 7;
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '19.0 19.0 19.0';
     MY(velocitymultiplier) = 14;
 }
SUB (smoking)
Definition at line 3862 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
              {
     MY(airfriction) = -1;
     MY(alpha_min) = 100;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 100;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x292929";
     MY(color_max) = "0x000000";
     MY(count) = 10;
     MY(gravity) = -0.100000;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(sizeincrease) = 5;
     MY(size_min) = 10;
     MY(size_max) = 40;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '5.0 5.0 20.0';
 }
SUB (goldendust)
Definition at line 3883 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and originjitter.
                 {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 70;
     MY(bounce) = 1.500000;
     MY(color_min) = "0xff9600";
     MY(color_max) = "0xffefb8";
     MY(count) = 25;
     MY(originjitter) = '500.0 500.0 500.0';
     MY(sizeincrease) = -0.300000;
     MY(size_min) = 2;
     MY(size_max) = 3;
     MY(tex_min) = 38;
     MY(tex_max) = 38;
     MY(type) = "snow";
     MY(velocityjitter) = '0.1 0.1 0.1';
 }
SUB (healing_fx)
Definition at line 3902 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                 {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 170;
     MY(bounce) = 1.500000;
     MY(color_min) = "0xff0000";
     MY(color_max) = "0xff0000";
     MY(count) = 25;
     MY(gravity) = -0.100000;
     MY(originjitter) = '5.0 5.0 100.0';
     MY(sizeincrease) = -0.050000;
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '50.0 50.0 0.0';
 }
SUB (armorrepair_fx)
Definition at line 3923 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                     {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 170;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x00ff00";
     MY(count) = 25;
     MY(gravity) = -0.100000;
     MY(originjitter) = '5.0 5.0 50.0';
     MY(sizeincrease) = -0.050000;
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '50.0 50.0 0.0';
 }
SUB (ammoregen_fx)
Definition at line 3944 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                   {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 170;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x0000ff";
     MY(color_max) = "0x0000ff";
     MY(count) = 25;
     MY(gravity) = -0.100000;
     MY(originjitter) = '5.0 5.0 50.0';
     MY(sizeincrease) = -0.050000;
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '50.0 50.0 0.0';
 }
SUB (rage)
Definition at line 3966 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
           {
     MY(airfriction) = 2;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 190;
     MY(color_min) = "0xff0000";
     MY(color_max) = "0xff7800";
     MY(count) = 2.500000;
     MY(gravity) = -0.060000;
     MY(originjitter) = '5.0 5.0 5.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 35;
     MY(tex_max) = 36;
     MY(type) = "smoke";
     MY(velocityjitter) = '25.0 25.0 25.0';
 }
SUB (iceorglass)
Definition at line 3987 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                 {
     MY(airfriction) = 3;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(bounce) = 2;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0xb2d3e6";
     MY(count) = 15;
     MY(gravity) = 1.300000;
     MY(originjitter) = '30.0 30.0 30.0';
     MY(size_min) = 3;
     MY(size_max) = 7;
     MY(tex_min) = 44;
     MY(tex_max) = 44;
     MY(time_min) = 1;
     MY(time_max) = 3;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '100.0 100.0 100.0';
 }
SUB (poisonfield)
Definition at line 4009 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                  {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 50;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x7db843";
     MY(count) = 15;
     MY(gravity) = -0.010000;
     MY(originjitter) = '333.0 333.0 50.0';
     MY(sizeincrease) = 30;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '5.0 5.0 5.0';
 }
SUB (icefield)
Definition at line 4030 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
               {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 50;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x008aff";
     MY(color_max) = "0x75e7ff";
     MY(count) = 10;
     MY(gravity) = -0.010000;
     MY(originjitter) = '333.0 333.0 0.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '5.0 5.0 30.0';
 }
SUB (firefield)
Definition at line 4068 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                {
     MY(airfriction) = 1;
     MY(alpha_min) = 50;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 200;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 100;
     MY(gravity) = -0.060000;
     MY(originjitter) = '180.0 180.0 0.0';
     MY(sizeincrease) = 20;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '5.0 5.0 30.0';
 }
SUB (flamethrower)
Definition at line 4123 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(airfriction) = 1.200000;
     MY(alpha_min) = 50;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 250;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 3;
     MY(gravity) = -0.060000;
     MY(sizeincrease) = 20;
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '40.0 40.0 11.0';
     MY(velocitymultiplier) = 30;
 }
SUB (TR_WIZSPIKE)
Definition at line 4224 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                  {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 968;
     MY(color_min) = "0x404040";
     MY(color_max) = "0x404040";
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradius) = 90;
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 62;
     MY(tex_max) = 62;
     MY(trailspacing) = 4;
     MY(type) = "static";
     MY(velocitymultiplier) = -0.100000;
 }
SUB (TR_VORESPIKE)
Definition at line 4265 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 968;
     MY(color_min) = "0x804000";
     MY(color_max) = "0x804000";
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradius) = 90;
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 62;
     MY(tex_max) = 62;
     MY(trailspacing) = 4;
     MY(type) = "static";
     MY(velocitymultiplier) = -0.100000;
 }
SUB (flac_explode)
Definition at line 4304 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 1.0';
     MY(lightradiusfade) = 400;
     MY(lightradius) = 150;
     MY(originjitter) = '40.0 40.0 40.0';
     MY(size_min) = 18;
     MY(size_max) = 28;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (tr_bullet)
Definition at line 4422 of file effectinfo.inc.
References alpha, alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
                {
     MY(alpha) = '500 600 10000';
     MY(color_min) = "0xf03000";
     MY(color_max) = "0xff6010";
     MY(countabsolute) = 1;
     MY(sizeincrease) = -3;
     MY(size_min) = 0.6;
     MY(size_max) = 0.8;
     my(tex_min) = 200;
     my(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (smoking_smallemitter)
Definition at line 4470 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
{
     MY(airfriction) = -1;
     MY(alpha_min) = 200;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 100;
     MY(color_min) = "0x292929";
     MY(color_max) = "0x000000";
     MY(count) = 10;
     MY(gravity) = -0.100000;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(sizeincrease) = 20;
     MY(size_min) = 6;
     MY(size_max) = 15;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '5.0 5.0 20.0';
 }
SUB (TR_CRYLINKPLASMA)
Definition at line 4491 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), MY, and SUB().
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x5522aa";
     MY(color_max) = "0x6622ff";
     MY(sizeincrease) = 8;
     MY(size_min) = 2;
     MY(size_max) = 2;
     MY(tex_min) = 32;
     MY(tex_max) = 32;
     MY(trailspacing) = 128;
     MY(type) = "static";
     MY(velocityjitter) = '8.0 8.0 8.0';
     MY(velocitymultiplier) = -0.010000;
 }
SUB (cherryblossom)
Definition at line 4526 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                    {
     MY(airfriction) = 1;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 32;
     MY(bounce) = 1.500000;
     MY(color_min) = "0xb123ff";
     MY(color_max) = "0xb183ff";
     MY(count) = 1.500000;
     MY(gravity) = 0.050000;
     MY(liquidfriction) = 1;
     MY(originjitter) = '16.0 16.0 16.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 2;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "static";
     MY(velocityjitter) = '32.0 32.0 0.0';
 }
SUB (alien_blood)
Definition at line 4547 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                  {
     MY(airfriction) = 0.400000;
     MY(alpha_min) = 1560;
     MY(alpha_max) = 2560;
     MY(alpha_fade) = 7000;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xDC9BCD";
     MY(color_max) = "0xDC9BCD";
     MY(count) = 0.400000;
     MY(sizeincrease) = 20;
     MY(size_min) = 5;
     MY(size_max) = 11;
     MY(staincolor_min) = "0xDC9BCD";
     MY(staincolor_max) = "0xDC9BCD";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 25;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "spark";
     MY(velocityjitter) = '99.0 99.0 55.0';
 }
SUB (robot_blood)
Definition at line 4591 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                  {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xff3000";
     MY(color_max) = "0xff7373";
     MY(count) = 0.167000;
     MY(gravity) = 1;
     MY(liquidfriction) = 4;
     MY(size_min) = 1;
     MY(size_max) = 2;
     MY(tex_min) = 70;
     MY(tex_max) = 70;
     MY(type) = "spark";
     MY(velocityjitter) = '264.0 264.0 264.0';
     MY(velocityoffset) = '0.0 0.0 100.0';
 }
SUB (alien_TR_BLOOD)
Definition at line 4646 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
                     {
     MY(airfriction) = -2;
     MY(alpha_min) = 384;
     MY(alpha_max) = 984;
     MY(alpha_fade) = 1492;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xC080B0";
     MY(color_max) = "0xC080B0";
     MY(gravity) = 0.400000;
     MY(liquidfriction) = 1;
     MY(sizeincrease) = -5;
     MY(size_min) = 4;
     MY(size_max) = 19;
     MY(staincolor_min) = "0xC080B0";
     MY(staincolor_max) = "0xC080B0";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 7;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 20;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = -0.100000;
 }
SUB (robot_TR_BLOOD)
Definition at line 4692 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
                     {
     MY(airfriction) = -2;
     MY(alpha_min) = 384;
     MY(alpha_max) = 984;
     MY(alpha_fade) = 1892;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(gravity) = 0.400000;
     MY(liquidfriction) = 1;
     MY(sizeincrease) = -6;
     MY(size_min) = 4;
     MY(size_max) = 13;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 3;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 6;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 16;
     MY(type) = "spark";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = -0.300000;
 }
SUB (alien_TR_SLIGHTBLOOD)
Definition at line 4762 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(airfriction) = 1;
     MY(alpha_min) = 384;
     MY(alpha_max) = 384;
     MY(alpha_fade) = 192;
     MY(bounce) = -1;
     MY(color_min) = "0xC080B0";
     MY(color_max) = "0xC080B0";
     MY(liquidfriction) = 4;
     MY(size_min) = 80;
     MY(size_max) = 80;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 64;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (robot_TR_SLIGHTBLOOD)
Definition at line 4786 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
{
     MY(airfriction) = 1;
     MY(alpha_min) = 384;
     MY(alpha_max) = 384;
     MY(alpha_fade) = 192;
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 8;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(trailspacing) = 64;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (item_pickup)
Definition at line 4811 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
                  {
     MY(alpha_min) = 128;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 64;
     MY(color_min) = "0x63F2EA";
     MY(color_max) = "0xB0C5C4";
     MY(countabsolute) = 1;
     MY(size_min) = 8;
     MY(size_max) = 16;
     MY(type) = "static";
 }
SUB (bloodshower)
Definition at line 4839 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                  {
     MY(alpha_min) = 156;
     MY(alpha_max) = 656;
     MY(alpha_fade) = 1664;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 125;
     MY(gravity) = 1;
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 28;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 3;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "spark";
     MY(velocityjitter) = '764.0 764.0 764.0';
 }
SUB (alien_bloodshower)
Definition at line 4883 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 156;
     MY(alpha_max) = 656;
     MY(alpha_fade) = 1664;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xC080B0";
     MY(color_max) = "0xC080B0";
     MY(count) = 125;
     MY(gravity) = 1;
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 28;
     MY(staincolor_min) = "0xC080B0";
     MY(staincolor_max) = "0xC080B0";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 3;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "spark";
     MY(velocityjitter) = '764.0 764.0 764.0';
 }
SUB (robot_bloodshower)
Definition at line 4927 of file effectinfo.inc.
References alpha_max, alpha_min, count, gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 156;
     MY(alpha_max) = 656;
     MY(alpha_fade) = 1664;
     MY(blend) = "invmod";
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(count) = 100;
     MY(gravity) = 1;
     MY(liquidfriction) = 4;
     MY(size_min) = 8;
     MY(size_max) = 28;
     MY(staincolor_min) = "0xC0D890";
     MY(staincolor_max) = "0xC0D890";
     MY(stainsize_min) = 1;
     MY(stainsize_max) = 2;
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(stretchfactor) = 3;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "spark";
     MY(velocityjitter) = '764.0 764.0 764.0';
 }
SUB (TE_TEI_G3_HIT)
Definition at line 5159 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), MY, and SUB().
                    {
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xFFFFFF";
     MY(color_max) = "0xFFFFFF";
     MY(countabsolute) = 1;
     MY(size_min) = 8;
     MY(size_max) = 8;
     MY(tex_min) = 200;
     MY(tex_max) = 200;
     MY(type) = "beam";
 }
SUB (firemine)
Definition at line 5205 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
               {
     MY(airfriction) = 1.200000;
     MY(alpha_min) = 50;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 250;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 0.500000;
     MY(gravity) = -0.060000;
     MY(sizeincrease) = 5;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(trailspacing) = 2;
     MY(type) = "smoke";
     MY(velocityjitter) = '10.0 10.0 2.0';
 }
SUB (fireball)
Definition at line 5328 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
               {
     MY(airfriction) = 1.200000;
     MY(alpha_min) = 50;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 250;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 0.500000;
     MY(gravity) = -0.060000;
     MY(sizeincrease) = 20;
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(trailspacing) = 2;
     MY(type) = "smoke";
     MY(velocityjitter) = '40.0 40.0 11.0';
 }
SUB (fireball_laser)
Definition at line 5451 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), and MY.
                     {
     MY(alpha_min) = 192;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 2560;
     MY(color_min) = "0x800000";
     MY(color_max) = "0xFF8020";
     MY(count) = 10;
     MY(size_min) = 1;
     MY(size_max) = 1;
     MY(stretchfactor) = 0.700000;
     MY(type) = "spark";
     MY(velocityjitter) = '1.0 1.0 1.0';
     MY(velocitymultiplier) = 10;
 }
SUB (fireball_explode)
Definition at line 5469 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '4.0 2.0 0.5';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 500;
     MY(originjitter) = '56.0 56.0 56.0';
     MY(size_min) = 72;
     MY(size_max) = 72;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (fireball_muzzleflash)
Definition at line 5558 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 2;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (fireball_preattack_muzzleflash)
Definition at line 5594 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 2;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (fireball_bfgdamage)
Definition at line 5630 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), EF_FLAME, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x202020";
     MY(color_max) = "0x404040";
     MY(count) = 2;
     MY(lightcolor) = '2.0 1.5 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (EF_FLAME)
Definition at line 5667 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), EF_FLAME, gravity, MY, originjitter, and SUB().
               {
     MY(alpha_min) = 200;
     MY(alpha_max) = 356;
     MY(alpha_fade) = 512;
     MY(bounce) = 2;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 100;
     MY(gravity) = -0.500000;
     MY(originjitter) = '12.0 12.0 34.0';
     MY(originoffset) = '0.0 0.0 10.0';
     MY(sizeincrease) = -1;
     MY(size_min) = 5;
     MY(size_max) = 21;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (tr_rifle)
Definition at line 5714 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
               {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 2560;
     MY(color_min) = "0x800000";
     MY(color_max) = "0xFF8020";
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(stretchfactor) = 1;
     MY(trailspacing) = 128;
     MY(type) = "spark";
     MY(velocitymultiplier) = 0.700000;
 }
SUB (rocket_guide)
Definition at line 5765 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x404040";
     MY(color_max) = "0x808080";
     MY(count) = 2;
     MY(gravity) = -0.125000;
     MY(liquidfriction) = 0.250000;
     MY(originjitter) = '8.0 8.0 8.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(tex_min) = 62;
     MY(tex_max) = 62;
     MY(type) = "bubble";
     MY(underwater) = true;
     MY(velocityjitter) = '48.0 48.0 48.0';
     MY(velocitymultiplier) = -0.100000;
 }
SUB (laser_gauntlet)
Definition at line 5825 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                     {
     MY(airfriction) = 10;
     MY(alpha_min) = 128;
     MY(alpha_max) = 512;
     MY(alpha_fade) = 6280;
     MY(color_min) = "0xb44215";
     MY(color_max) = "0x880000";
     MY(count) = 3;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = 4000;
     MY(spin_max) = -4000;
     MY(sizeincrease) = -100;
     MY(size_min) = 7;
     MY(size_max) = 10;
     MY(stretchfactor) = 2.300000;
     MY(tex_min) = 43;
     MY(tex_max) = 43;
     MY(type) = "spark";
     MY(velocityjitter) = '150.0 150.0 150.0';
     MY(velocitymultiplier) = 0.200000;
 }
SUB (laser_gauntletmuzzleflash)
Definition at line 5870 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 10;
     MY(alpha_min) = 256;
     MY(alpha_max) = 512;
     MY(alpha_fade) = 6280;
     MY(color_min) = "0x220000";
     MY(color_max) = "0x880000";
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.0 0.1 0.1';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 150;
     MY(sizeincrease) = -100;
     MY(size_min) = 10;
     MY(size_max) = 15;
     MY(stretchfactor) = 2;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
 }
SUB (torchflame)
Definition at line 5937 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                 {
     MY(airfriction) = 1.200000;
     MY(alpha_min) = 50;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 250;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 3;
     MY(gravity) = -0.060000;
     MY(sizeincrease) = 20;
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '40.0 40.0 11.0';
     MY(velocitymultiplier) = 30;
 }
SUB (electro_lightning)
Definition at line 6034 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.1 4.4 10.0';
     MY(lightradiusfade) = 500;
     MY(lightradius) = 50;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(size_min) = 16;
     MY(size_max) = 16;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (gauntlet_lightning)
Definition at line 6104 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x280000";
     MY(color_max) = "0x280000";
     MY(count) = 300;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = 15;
     MY(size_min) = 3;
     MY(size_max) = 3;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "spark";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 2000;
 }
SUB (crylink_joinexplode)
Definition at line 6161 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(originjitter) = '12.0 12.0 12.0';
     MY(size_min) = 24;
     MY(size_max) = 24;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "decal";
 }
SUB (kaball_sparks)
Definition at line 6231 of file effectinfo.inc.
References alpha_max, count, DEF(), gravity, MY, and originjitter.
                    {
     MY(airfriction) = 3;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 556;
     MY(bounce) = 1.500000;
     MY(color_min) = "0xa9cacf";
     MY(color_max) = "0x0054ff";
     MY(count) = 35;
     MY(gravity) = 1;
     MY(originjitter) = '1.0 1.0 1.0';
     MY(size_min) = 1;
     MY(size_max) = 3;
     MY(tex_min) = 40;
     MY(tex_max) = 40;
     MY(type) = "spark";
     MY(velocityjitter) = '300.0 300.0 300.0';
     MY(velocitymultiplier) = 0.500000;
 }
SUB (tr_rifle_weak)
Definition at line 6252 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, and SUB().
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 2560;
     MY(color_min) = "0x800000";
     MY(color_max) = "0xFF8020";
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(stretchfactor) = 1;
     MY(trailspacing) = 128;
     MY(type) = "spark";
     MY(velocitymultiplier) = 0.700000;
 }
SUB (red_smoke)
Definition at line 6302 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
                {
     MY(airfriction) = -1;
     MY(alpha_min) = 32;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 32;
     MY(color_min) = "0xff8866";
     MY(color_max) = "0x331100";
     MY(count) = 2;
     MY(gravity) = -0.007000;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(size_min) = 60;
     MY(size_max) = 120;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocitymultiplier) = 5;
 }
SUB (pipe_smoke)
Definition at line 6323 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
                 {
     MY(airfriction) = -1;
     MY(alpha_min) = 32;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 48;
     MY(color_min) = "0x999999";
     MY(color_max) = "0x555555";
     MY(count) = 2;
     MY(gravity) = -0.015000;
     MY(startangle_max) = 360;
     MY(spin_min) = -180;
     MY(spin_max) = 180;
     MY(sizeincrease) = 35;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '0.0 0.0 5.0';
     MY(velocitymultiplier) = 15;
 }
SUB (TR_SEEKER)
Definition at line 6346 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, originjitter, and SUB().
                {
     MY(alpha_min) = 200;
     MY(alpha_max) = 300;
     MY(alpha_fade) = 200;
     MY(bounce) = 1;
     MY(color_min) = "0x000000";
     MY(color_max) = "0x666666";
     MY(lightcolor) = '6.0 3.0 1.0';
     MY(lightradius) = 100;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = 11;
     MY(size_min) = 2;
     MY(size_max) = 2;
     MY(tex_max) = 8;
     MY(trailspacing) = 10;
     MY(type) = "smoke";
     MY(velocityjitter) = '3.0 3.0 3.0';
     MY(velocitymultiplier) = -0.020000;
 }
SUB (explosion_big)
Definition at line 6433 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 0.0';
     MY(lightradiusfade) = 1750;
     MY(lightradius) = 600;
     MY(originjitter) = '23.0 23.0 23.0';
     MY(size_min) = 172;
     MY(size_max) = 172;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (explosion_medium)
Definition at line 6605 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 56;
     MY(alpha_max) = 56;
     MY(alpha_fade) = 330;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 2400;
     MY(size_min) = 72;
     MY(size_max) = 72;
     MY(tex_min) = 33;
     MY(tex_max) = 33;
     MY(type) = "static";
 }
SUB (explosion_small)
Definition at line 6814 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 56;
     MY(alpha_max) = 56;
     MY(alpha_fade) = 330;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(countabsolute) = 1;
     MY(sizeincrease) = 2400;
     MY(size_min) = 22;
     MY(size_max) = 22;
     MY(tex_min) = 33;
     MY(tex_max) = 33;
     MY(type) = "static";
 }
SUB (smoke_big)
Definition at line 6932 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                {
     MY(airfriction) = 4;
     MY(alpha_min) = 200;
     MY(alpha_max) = 750;
     MY(alpha_fade) = 200;
     MY(color_min) = "0x4F4B46";
     MY(color_max) = "0x000000";
     MY(count) = 3;
     MY(gravity) = -0.500000;
     MY(notunderwater) = true;
     MY(originjitter) = '55.0 55.0 55.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = -20;
     MY(spin_max) = 20;
     MY(sizeincrease) = 15;
     MY(size_min) = 30;
     MY(size_max) = 60;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '140.0 140.0 200.0';
     MY(velocityoffset) = '0.0 0.0 200.0';
 }
SUB (smoke_small)
Definition at line 6958 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and MY.
                  {
     MY(airfriction) = 4;
     MY(alpha_min) = 200;
     MY(alpha_max) = 750;
     MY(alpha_fade) = 200;
     MY(color_min) = "0x4F4B46";
     MY(color_max) = "0x000000";
     MY(count) = 3;
     MY(gravity) = -0.500000;
     MY(notunderwater) = true;
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = -20;
     MY(spin_max) = 20;
     MY(sizeincrease) = -10;
     MY(size_min) = 60;
     MY(size_max) = 100;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
     MY(velocityjitter) = '40.0 40.0 400.0';
     MY(velocityoffset) = '0.0 0.0 200.0';
 }
SUB (impact_metal)
Definition at line 6983 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 25;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 50;
     MY(color_min) = "0x000000";
     MY(color_max) = "0x886666";
     MY(count) = 1;
     MY(gravity) = -0.010000;
     MY(originjitter) = '20.0 20.0 5.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 3;
     MY(size_max) = 6;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
 }
SUB (impact_stone)
Definition at line 7021 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 50;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 75;
     MY(color_min) = "0x000000";
     MY(color_max) = "0xcc9966";
     MY(count) = 1;
     MY(gravity) = -0.010000;
     MY(originjitter) = '20.0 20.0 5.0';
     MY(sizeincrease) = 15;
     MY(size_min) = 3;
     MY(size_max) = 6;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
 }
SUB (impact_wood)
Definition at line 7062 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                  {
     MY(alpha_min) = 50;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 75;
     MY(color_min) = "0x000000";
     MY(color_max) = "0xcc9966";
     MY(count) = 1;
     MY(gravity) = -0.010000;
     MY(originjitter) = '20.0 20.0 5.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 3;
     MY(size_max) = 6;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
 }
SUB (impact_flesh)
Definition at line 7099 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 100;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 400;
     MY(color_min) = "0x000000";
     MY(color_max) = "0x420000";
     MY(count) = 0.500000;
     MY(originjitter) = '11.0 11.0 11.0';
     MY(size_min) = 8;
     MY(size_max) = 12;
     MY(tex_max) = 8;
     MY(type) = "alphastatic";
 }
SUB (tr_hagar)
Definition at line 7139 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), gravity, MY, originjitter, and SUB().
               {
     MY(alpha_min) = 300;
     MY(alpha_max) = 400;
     MY(alpha_fade) = 780;
     MY(bounce) = 1;
     MY(color_min) = "0x101010";
     MY(color_max) = "0x000000";
     MY(originjitter) = '1.0 1.0 1.0';
     MY(sizeincrease) = 10;
     MY(size_min) = 3;
     MY(size_max) = 2;
     MY(tex_max) = 8;
     MY(trailspacing) = 4;
     MY(type) = "smoke";
     MY(velocityjitter) = '1.0 1.0 1.0';
     MY(velocitymultiplier) = -0.020000;
 }
SUB (damage_blaster)
Definition at line 7197 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and originjitter.
                     {
     MY(airfriction) = -0.350000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 16;
     MY(alpha_fade) = 128;
     MY(color_min) = "0x880000";
     MY(color_max) = "0xff4400";
     MY(count) = 3;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_max) = 180;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = 8;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '0.4 0.4 0.6';
 }
SUB (damage_shotgun)
Definition at line 7220 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                     {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 0.600000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 5;
 }
SUB (alien_damage_shotgun)
Definition at line 7259 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xDC9BCD";
     MY(color_max) = "0xDC9BCD";
     MY(count) = 0.600000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 5;
 }
SUB (robot_damage_shotgun)
Definition at line 7298 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(count) = 0.600000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocitymultiplier) = 5;
 }
SUB (damage_machinegun)
Definition at line 7337 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (alien_damage_machinegun)
Definition at line 7375 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xDC9BCD";
     MY(color_max) = "0xDC9BCD";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (robot_damage_machinegun)
Definition at line 7413 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (damage_minelayer)
Definition at line 7451 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 512;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 3;
     MY(gravity) = -0.500000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(sizeincrease) = -15;
     MY(size_min) = 4;
     MY(size_max) = 8;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (damage_mortar)
Definition at line 7490 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 512;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 3;
     MY(gravity) = -0.500000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(sizeincrease) = -15;
     MY(size_min) = 4;
     MY(size_max) = 8;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (damage_arc)
Definition at line 7529 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                 {
     MY(airfriction) = -0.650000;
     MY(alpha_min) = 48;
     MY(alpha_max) = 8;
     MY(alpha_fade) = 48;
     MY(color_min) = "0x66ffff";
     MY(color_max) = "0x2288ff";
     MY(count) = 2;
     MY(gravity) = -0.000100;
     MY(liquidfriction) = 0.600000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_min) = 180;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = -14;
     MY(size_min) = 4;
     MY(size_max) = 8;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "static";
     MY(velocityjitter) = '6.0 6.0 12.0';
 }
SUB (damage_electro)
Definition at line 7596 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 48;
     MY(alpha_max) = 8;
     MY(alpha_fade) = 48;
     MY(color_min) = "0x66ffff";
     MY(color_max) = "0x2288ff";
     MY(count) = 2;
     MY(gravity) = -0.000100;
     MY(liquidfriction) = 0.800000;
     MY(notunderwater) = true;
     MY(originjitter) = '3.0 3.0 3.0';
     MY(startangle_min) = 180;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = -14;
     MY(size_min) = 6;
     MY(size_max) = 10;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "static";
     MY(velocityjitter) = '8.0 8.0 16.0';
 }
SUB (damage_crylink)
Definition at line 7663 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 48;
     MY(alpha_max) = 16;
     MY(alpha_fade) = 48;
     MY(color_min) = "0xff44ff";
     MY(color_max) = "0x9966ff";
     MY(count) = 2;
     MY(gravity) = -0.000100;
     MY(liquidfriction) = 0.800000;
     MY(notunderwater) = true;
     MY(originjitter) = '3.0 3.0 3.0';
     MY(startangle_min) = 180;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = -8;
     MY(size_min) = 0.500000;
     MY(size_max) = 1;
     MY(tex_min) = 38;
     MY(tex_max) = 38;
     MY(type) = "static";
     MY(velocityjitter) = '10.0 10.0 20.0';
 }
SUB (damage_hlac)
Definition at line 7728 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and originjitter.
                  {
     MY(airfriction) = -0.350000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 16;
     MY(alpha_fade) = 128;
     MY(color_min) = "0x880000";
     MY(color_max) = "0xff4400";
     MY(count) = 3;
     MY(notunderwater) = true;
     MY(originjitter) = '4.0 4.0 4.0';
     MY(startangle_max) = 180;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = 10;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '0.4 0.4 0.6';
 }
SUB (damage_vortex)
Definition at line 7751 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 64;
     MY(alpha_max) = 8;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0x88ffff";
     MY(count) = 1;
     MY(gravity) = -0.000100;
     MY(liquidfriction) = 0.600000;
     MY(originjitter) = '4.0 4.0 4.0';
     MY(startangle_min) = 180;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = -14;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "static";
     MY(velocityjitter) = '8.0 8.0 16.0';
 }
SUB (damage_vaporizer)
Definition at line 7817 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(airfriction) = -0.500000;
     MY(alpha_min) = 64;
     MY(alpha_max) = 8;
     MY(alpha_fade) = 64;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0x88ffff";
     MY(count) = 2;
     MY(gravity) = -0.000100;
     MY(liquidfriction) = 0.600000;
     MY(originjitter) = '4.0 4.0 4.0';
     MY(startangle_min) = 180;
     MY(startangle_max) = 360;
     MY(spin_min) = -30;
     MY(spin_max) = 30;
     MY(sizeincrease) = -14;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_min) = 47;
     MY(tex_max) = 47;
     MY(type) = "static";
     MY(velocityjitter) = '8.0 8.0 16.0';
 }
SUB (damage_rifle)
Definition at line 7883 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
                   {
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (damage_rifle_alien)
Definition at line 7921 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xDC9BCD";
     MY(color_max) = "0xDC9BCD";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (damage_rifle_robot)
Definition at line 7959 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and SUB().
{
     MY(airfriction) = 1;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 64;
     MY(bounce) = -1;
     MY(color_min) = "0xC0D890";
     MY(color_max) = "0xC0D890";
     MY(count) = 0.300000;
     MY(liquidfriction) = 4;
     MY(size_min) = 2;
     MY(size_max) = 4;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_min) = 24;
     MY(tex_max) = 32;
     MY(type) = "blood";
     MY(velocityjitter) = '32.0 32.0 32.0';
     MY(velocitymultiplier) = 5;
 }
SUB (damage_seeker)
Definition at line 7997 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 512;
     MY(alpha_max) = 32;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x8f0c00";
     MY(color_max) = "0xff2200";
     MY(count) = 3;
     MY(gravity) = -0.300000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(sizeincrease) = -10;
     MY(size_min) = 4;
     MY(size_max) = 8;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (damage_hagar)
Definition at line 8036 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                   {
     MY(alpha_min) = 512;
     MY(alpha_max) = 32;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x8f0c00";
     MY(color_max) = "0xff3a00";
     MY(count) = 3;
     MY(gravity) = -0.300000;
     MY(notunderwater) = true;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(sizeincrease) = -10;
     MY(size_min) = 4;
     MY(size_max) = 8;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (damage_fireball)
Definition at line 8075 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 16;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x8f0d00";
     MY(color_max) = "0xff5a00";
     MY(count) = 4;
     MY(gravity) = -0.500000;
     MY(notunderwater) = true;
     MY(originjitter) = '8.0 8.0 8.0';
     MY(sizeincrease) = -10;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 50.0';
 }
SUB (damage_devastator)
Definition at line 8114 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
{
     MY(alpha_min) = 512;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 1024;
     MY(color_min) = "0x8f0c00";
     MY(color_max) = "0xff2a00";
     MY(count) = 3;
     MY(gravity) = -0.700000;
     MY(notunderwater) = true;
     MY(originjitter) = '4.0 4.0 4.0';
     MY(sizeincrease) = -10;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_min) = 48;
     MY(tex_max) = 55;
     MY(type) = "smoke";
     MY(velocityjitter) = '22.0 22.0 30.0';
 }
SUB (fireflies)
Definition at line 8153 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, and originjitter.
                {
     MY(airfriction) = 5;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 70;
     MY(bounce) = -1;
     MY(color_min) = "0xff9600";
     MY(color_max) = "0xffefb8";
     MY(count) = 1;
     MY(originjitter) = '32.0 32.0 32.0';
     MY(originoffset) = '8.0 8.0 8.0';
     MY(sizeincrease) = -0.300000;
     MY(size_min) = 2;
     MY(size_max) = 3;
     MY(tex_min) = 38;
     MY(tex_max) = 38;
     MY(time_min) = 1;
     MY(time_max) = 2;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 64.0';
     MY(velocityoffset) = '2.0 2.0 2.0';
 }
SUB (healray_muzzleflash)
Definition at line 8177 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x283880";
     MY(color_max) = "0x283880";
     MY(countabsolute) = 1;
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = -10;
     MY(size_min) = 20;
     MY(size_max) = 20;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (healray_impact)
Definition at line 8235 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                     {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(color_min) = "0xd800ff";
     MY(color_max) = "0xd800ff";
     MY(countabsolute) = 1;
     MY(lightcolor) = '0.0 4.4 0.0';
     MY(lightradiusfade) = 450;
     MY(lightradius) = 125;
     MY(originjitter) = '17.0 17.0 17.0';
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (bigplasma_muzzleflash)
Definition at line 8308 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
{
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 812;
     MY(color_min) = "0x283880";
     MY(color_max) = "0x283880";
     MY(countabsolute) = 1;
     MY(lightcolor) = '1.5 3.0 6.0';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(sizeincrease) = -10;
     MY(size_min) = 50;
     MY(size_max) = 50;
     MY(tex_min) = 65;
     MY(tex_max) = 65;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (bigplasma_impact)
Definition at line 8380 of file effectinfo.inc.
References alpha_max, alpha_min, count, gravity, MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.1 4.4 10.0';
     MY(lightradiusfade) = 450;
     MY(lightradius) = 125;
     MY(originjitter) = '17.0 17.0 17.0';
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 59;
     MY(tex_max) = 59;
     MY(type) = "decal";
 }
SUB (shockwave_attack)
Definition at line 8574 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                       {
     MY(airfriction) = 1;
     MY(alpha_min) = 4096;
     MY(alpha_max) = 4096;
     MY(alpha_fade) = 20000;
     MY(color_min) = "0xb44215";
     MY(color_max) = "0xff0000";
     MY(count) = 1;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(startangle_min) = -180;
     MY(startangle_max) = 180;
     MY(spin_min) = 4000;
     MY(spin_max) = -4000;
     MY(sizeincrease) = 1.500000;
     MY(size_min) = 5;
     MY(size_max) = 7;
     MY(stretchfactor) = 2.300000;
     MY(tex_min) = 43;
     MY(tex_max) = 43;
     MY(type) = "spark";
     MY(velocityjitter) = '10.0 10.0 10.0';
     MY(velocitymultiplier) = 10;
 }
SUB (arc_lightning)
Definition at line 8620 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                    {
     MY(alpha_min) = 32;
     MY(alpha_max) = 32;
     MY(countabsolute) = 1;
     MY(lightcolor) = '3.1 4.4 10.0';
     MY(lightradiusfade) = 200;
     MY(lightradius) = 50;
     MY(originjitter) = '2.0 2.0 2.0';
     MY(size_min) = 16;
     MY(size_max) = 16;
     MY(tex_min) = 16;
     MY(tex_max) = 32;
     MY(type) = "decal";
 }
SUB (arc_beam)
Definition at line 8700 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), MY, originjitter, and SUB().
               {
     MY(airfriction) = -10;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 16384;
     MY(color_min) = "0xfafad2";
     MY(color_max) = "0xffffff";
     MY(originjitter) = '3.0 3.0 3.0';
     MY(relativeoriginoffset) = '10.0 0.0 0.0';
     MY(startangle_max) = 360;
     MY(spin_min) = 360;
     MY(spin_max) = 1000;
     MY(stretchfactor) = 1;
     MY(tex_min) = 71;
     MY(tex_max) = 74;
     MY(time_min) = 0.050000;
     MY(time_max) = 0.050000;
     MY(trailspacing) = 10;
     MY(type) = "spark";
     MY(velocityjitter) = '100.0 100.0 100.0';
     MY(velocitymultiplier) = 200;
 }
SUB (arc_beam_heal)
Definition at line 8749 of file effectinfo.inc.
References alpha_max, alpha_min, DEF(), and MY.
                    {
     MY(airfriction) = -20;
     MY(alpha_min) = 2048;
     MY(alpha_max) = 2048;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x20FF20";
     MY(color_max) = "0x40FF40";
     MY(relativeoriginoffset) = '5.0 0.0 0.0';
     MY(relativevelocityoffset) = '100.0 0.0 0.0';
     MY(sizeincrease) = 20;
     MY(size_min) = 0.100000;
     MY(size_max) = 0.100000;
     MY(tex_min) = 74;
     MY(tex_max) = 74;
     MY(trailspacing) = 1500;
     MY(type) = "smoke";
     MY(velocityjitter) = '3.0 3.0 3.0';
     MY(velocitymultiplier) = 200;
 }
SUB (arc_beam_healimpact)
Definition at line 8771 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and SUB().
{
     MY(alpha_min) = 40;
     MY(alpha_max) = 40;
     MY(alpha_fade) = 350;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x84c52f";
     MY(countabsolute) = 1;
     MY(lightcolor) = '0.0 4.4 0.0';
     MY(lightradiusfade) = 150;
     MY(lightradius) = 20;
     MY(sizeincrease) = -1000;
     MY(size_min) = 32;
     MY(size_max) = 32;
     MY(tex_min) = 33;
     MY(tex_max) = 33;
     MY(type) = "smoke";
     MY(velocitymultiplier) = 44;
 }
SUB (arc_smoke)
Definition at line 8813 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                {
     MY(airfriction) = 1;
     MY(alpha_min) = 32;
     MY(alpha_max) = 64;
     MY(alpha_fade) = 48;
     MY(color_min) = "0x4c453f";
     MY(color_max) = "0x2a241f";
     MY(count) = 2;
     MY(gravity) = -0.125000;
     MY(notunderwater) = true;
     MY(startangle_max) = 360;
     MY(spin_min) = -180;
     MY(spin_max) = 180;
     MY(sizeincrease) = 10;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '0.0 0.0 16.0';
 }
SUB (arc_overheat)
Definition at line 8856 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, and originjitter.
                   {
     MY(airfriction) = 5;
     MY(alpha_min) = 128;
     MY(alpha_max) = 128;
     MY(alpha_fade) = 292;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0x9271fb";
     MY(count) = 24;
     MY(gravity) = -0.400000;
     MY(liquidfriction) = 10;
     MY(originjitter) = '10.0 10.0 10.0';
     MY(sizeincrease) = -24;
     MY(size_min) = 6;
     MY(size_max) = 12;
     MY(tex_min) = 43;
     MY(tex_max) = 43;
     MY(type) = "spark";
     MY(velocityjitter) = '256.0 256.0 256.0';
 }
SUB (arc_overheat_fire)
Definition at line 8878 of file effectinfo.inc.
References alpha_max, count, DEF(), gravity, MY, and originjitter.
{
     MY(alpha_max) = 256;
     MY(alpha_fade) = 640;
     MY(bounce) = 1.500000;
     MY(color_min) = "0x4444ff";
     MY(color_max) = "0xeeeeff";
     MY(count) = 1;
     MY(gravity) = 1;
     MY(liquidfriction) = 5;
     MY(originjitter) = '6.0 6.0 6.0';
     MY(size_min) = 0.400000;
     MY(size_max) = 1;
     MY(type) = "spark";
     MY(velocityjitter) = '92.0 92.0 92.0';
     MY(velocitymultiplier) = 80;
     MY(velocityoffset) = '0.0 0.0 80.0';
 }
SUB (arc_muzzleflash)
Definition at line 8901 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), MY, originjitter, and SUB().
                      {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 512;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x8f4333";
     MY(count) = 2;
     MY(lightcolor) = '0.3 2.0 0.2';
     MY(lightradiusfade) = 2000;
     MY(lightradius) = 200;
     MY(originjitter) = '1.5 1.5 1.5';
     MY(size_min) = 5;
     MY(size_max) = 5;
     MY(tex_max) = 8;
     MY(type) = "smoke";
     MY(velocityjitter) = '6.0 6.0 6.0';
     MY(velocitymultiplier) = 0.010000;
 }
SUB (arc_bolt_explode)
Definition at line 8943 of file effectinfo.inc.
References alpha_max, alpha_min, count, DEF(), gravity, MY, originjitter, and SUB().
                       {
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(countabsolute) = 1;
     MY(lightcolor) = '8.0 4.0 1.0';
     MY(lightradiusfade) = 400;
     MY(lightradius) = 120;
     MY(originjitter) = '14.0 14.0 14.0';
     MY(size_min) = 28;
     MY(size_max) = 38;
     MY(tex_min) = 8;
     MY(tex_max) = 16;
     MY(type) = "decal";
 }
SUB (tr_bullet_weak)
Definition at line 9044 of file effectinfo.inc.
References alpha, alpha_max, alpha_min, gravity, MY, and SUB().
                     {
     MY(alpha) = '75 100 3000';
     MY(color_min) = "0xf03000";
     MY(color_max) = "0xff6010";
     MY(countabsolute) = 1;
     MY(sizeincrease) = -3;
     MY(size_min) = 0.6;
     MY(size_max) = 0.8;
     my(tex_min) = 200;
     my(tex_max) = 200;
     MY(type) = "beam";
 }