Xonotic: common/turrets/all.qh File Reference
all.qh File Reference
#include <common/command/_mod.qh>
#include "config.qh"
#include "turret.qh"
#include "turret/_mod.qh"
Macros
#define _TR_CONFIG(class, fld, T, turname)
#define DEFAULT_FILENAME "turrets_dump.cfg"
#define get_turretinfo(i) REGISTRY_GET(Turrets, i)
#define REGISTER_TURRET(id, inst) REGISTER(Turrets, TUR, id, m_id, inst)
#define TR_CONFIG(class, turname, fld, T) _TR_CONFIG(class, fld, T, turname)
#define TR_CONFIG_BEGIN(class)
#define TR_CONFIG_END()
#define TR_PROPS(L, class, prefix) L(TR_CONFIG_BEGIN, TR_CONFIG, TR_CONFIG_END, class, prefix) \
#define TR_PROPS_COMMON(P, class, prefix)
#define TUR_LAST (REGISTRY_COUNT(Turrets) - 1)
Functions
GENERIC_COMMAND (dumpturrets, "Dump all turrets into " DEFAULT_FILENAME, false)
REGISTER_TURRET (Null, NEW(Turret))
Variables
const int TUR_FIRST = 1
Macro Definition Documentation
_TR_CONFIG
#define _TR_CONFIG (class, fld, T, turname)
Definition at line 55 of file all.qh.
DEFAULT_FILENAME
#define DEFAULT_FILENAME "turrets_dump.cfg"
Definition at line 59 of file all.qh.
Referenced by GENERIC_COMMAND().
get_turretinfo
#define get_turretinfo (i) REGISTRY_GET(Turrets, i)
Definition at line 9 of file all.qh.
Referenced by turret_construct(), turret_die(), and turret_draw2d().
REGISTER_TURRET
#define REGISTER_TURRET (id, inst) REGISTER(Turrets, TUR, id, m_id, inst)
Definition at line 119 of file all.qh.
TR_CONFIG
#define TR_CONFIG (class, turname, fld, T) _TR_CONFIG(class, fld, T, turname)
Definition at line 48 of file all.qh.
TR_CONFIG_BEGIN
#define TR_CONFIG_BEGIN (class)
Definition at line 54 of file all.qh.
TR_CONFIG_END
#define TR_CONFIG_END ()
Definition at line 56 of file all.qh.
TR_PROPS
#define TR_PROPS (L, class, prefix) L(TR_CONFIG_BEGIN, TR_CONFIG, TR_CONFIG_END, class, prefix) \
Definition at line 44 of file all.qh.
TR_PROPS_COMMON
#define TR_PROPS_COMMON (P, class, prefix)
Value:
P(class, prefix, aim_firetolerance_dist, float) \
    P(class, prefix, aim_maxpitch, float) \
    P(class, prefix, aim_maxrot, float) \
    P(class, prefix, aim_speed, float) \
    P(class, prefix, ammo_max, float) \
    P(class, prefix, ammo_recharge, float) \
    P(class, prefix, health, float) \
    P(class, prefix, respawntime, float) \
    P(class, prefix, shot_dmg, float) \
    P(class, prefix, shot_force, float) \
    P(class, prefix, shot_radius, float) \
    P(class, prefix, shot_refire, float) \
    P(class, prefix, shot_speed, float) \
    P(class, prefix, shot_spread, float) \
    P(class, prefix, shot_volly, float) \
    P(class, prefix, shot_volly_refire, float) \
    P(class, prefix, target_range, float) \
    P(class, prefix, target_range_min, float) \
    P(class, prefix, target_range_optimal, float) \
    P(class, prefix, target_select_anglebias, float) \
    P(class, prefix, target_select_missilebias, float) \
    P(class, prefix, target_select_playerbias, float) \
    P(class, prefix, target_select_rangebias, float) \
    P(class, prefix, target_select_samebias, float) \
    P(class, prefix, track_accel_pitch, float) \
    P(class, prefix, track_accel_rot, float) \
    P(class, prefix, track_blendrate, float) \
    P(class, prefix, track_type, float) \
Definition at line 13 of file all.qh.
TUR_LAST
#define TUR_LAST (REGISTRY_COUNT(Turrets) - 1)
Definition at line 117 of file all.qh.
Function Documentation
GENERIC_COMMAND()
GENERIC_COMMAND (dumpturrets , "Dump all turrets into " DEFAULT_FILENAME, false)
Definition at line 61 of file all.qh.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, DEFAULT_FILENAME, fclose(), FILE_WRITE, fopen(), LOG_HELP, LOG_HELPF, LOG_INFO, and LOG_INFOF.
 {
     switch(request)
     {
         case CMD_REQUEST_COMMAND:
         {
             #ifdef SVQC
             tur_config_file = -1;
             tur_config_alsoprint = -1;
             string filename = argv(1);
             if(filename == "")
             {
                 filename = DEFAULT_FILENAME;
                 tur_config_alsoprint = false;
             }
             else if(filename == "-")
             {
                 filename = DEFAULT_FILENAME;
                 tur_config_alsoprint = true;
             }
             tur_config_file = fopen(filename, FILE_WRITE);
             if(tur_config_file >= 0)
             {
                 Dump_Turret_Settings();
                 LOG_INFOF("Dumping turrets... File located in ^2data/data/%s^7.", filename);
                 fclose(tur_config_file);
                 tur_config_file = -1;
                 tur_config_alsoprint = -1;
             }
             else
             {
                 LOG_INFOF("^1Error: ^7Could not open file '%s'!", filename);
             }
             #else
             LOG_INFO("Turrets dump command only works with sv_cmd.");
             #endif
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 ", GetProgramCommandPrefix(), " dumpturrets [<filename>]");
             LOG_HELPF("  Where <filename> is the file to write (default is %s),", DEFAULT_FILENAME);
             LOG_HELP("  if supplied with '-' output to console as well as default,");
             LOG_HELP("  if left blank, it will only write to default.");
             return;
         }
     }
 }
REGISTER_TURRET()
REGISTER_TURRET (Null , NEW(Turret))
Variable Documentation
TUR_FIRST
const int TUR_FIRST = 1
Definition at line 116 of file all.qh.