Xonotic: server/round_handler.qc File Reference
round_handler.qc File Reference
#include "round_handler.qh"
#include "command/vote.qh"
#include "../common/util.qh"
Functions
void round_handler_FirstThink (entity this)
void round_handler_Init (float the_delay, float the_count, float the_round_timelimit)
void round_handler_Remove ()
void round_handler_Reset (float next_think)
void round_handler_Spawn (float() canRoundStart_func, float() canRoundEnd_func, void() roundStart_func)
void round_handler_Think (entity this)
Function Documentation
void round_handler_FirstThink (entity this)
Definition at line 77 of file round_handler.qc.
References count, game_starttime, max(), nextthink, round_handler_Think(), round_starttime, setthink, and time.
Referenced by round_handler_Spawn().
 {
     round_starttime = max(time, game_starttime) + this.count;
     setthink(this, round_handler_Think);
     this.nextthink = max(time, game_starttime);
 }
void round_handler_Init (float the_delay, float the_count, float the_round_timelimit)
Definition at line 66 of file round_handler.qc.
References cnt, count, delay, entity(), fabs(), floor(), round_handler, and round_timelimit.
Referenced by REGISTER_MUTATOR(), and round_handler_Spawn().
 {
     entity this = round_handler;
     this.delay = (the_delay > 0) ? the_delay : 0;
     this.count = fabs(floor(the_count));
     this.cnt = this.count + 1;
     this.round_timelimit = (the_round_timelimit > 0) ? the_round_timelimit : 0;
 }
void round_handler_Remove ()
Definition at line 112 of file round_handler.qc.
References round_handler, and world.
Referenced by round_handler_Think().
 {
     remove(round_handler);
     round_handler = world;
 }
void round_handler_Reset (float next_think)
Definition at line 102 of file round_handler.qc.
References cnt, count, entity(), nextthink, round_handler, round_starttime, and wait.
Referenced by reset_map(), and round_handler_Think().
 {
     entity this = round_handler;
     this.wait = false;
     if (this.count)
         if (this.cnt < this.count + 1) this.cnt = this.count + 1;
     this.nextthink = next_think;
     round_starttime = (next_think) ? (next_think + this.count) : -1;
 }
void round_handler_Spawn (float() canRoundStart_func, float() canRoundEnd_func, void() roundStart_func)
Definition at line 84 of file round_handler.qc.
References backtrace, entity(), nextthink, round_handler, round_handler_FirstThink(), round_handler_Init(), setthink, time, and wait.
Referenced by REGISTER_MUTATOR().
 {
     if (round_handler)
     {
         backtrace("Can't spawn round_handler again!");
         return;
     }
     entity this = round_handler = new(round_handler);
     setthink(this, round_handler_FirstThink);
     this.canRoundStart = canRoundStart_func;
     this.canRoundEnd = canRoundEnd_func;
     this.roundStart = roundStart_func;
     this.wait = false;
     round_handler_Init(5, 5, 180);
     this.nextthink = time;
 }
void round_handler_Think (entity this)
Definition at line 6 of file round_handler.qc.
References cnt, count, delay, game_starttime, gameover, nextthink, reset_map(), round_endtime, round_handler_Remove(), round_handler_Reset(), round_starttime, round_timelimit, time, and wait.
Referenced by round_handler_FirstThink().
 {
     if (time < game_starttime)
     {
         round_handler_Reset(game_starttime);
         return;
     }
     if (gameover)
     {
         round_handler_Reset(0);
         round_handler_Remove();
         return;
     }
     if (this.wait)
     {
         this.wait = false;
         this.cnt = this.count + 1;  // init countdown
         round_starttime = time + this.count;
         reset_map(true);
     }
     if (this.cnt > 0)  // countdown running
     {
         if (this.canRoundStart())
         {
             if (this.cnt == this.count + 1) round_starttime = time + this.count;
             int f = this.cnt - 1;
             if (f == 0)
             {
                 this.cnt = 0;
                 this.round_endtime = (this.round_timelimit) ? time + this.round_timelimit : 0;
                 this.nextthink = time;
                 if (this.roundStart) this.roundStart();
                 return;
             }
             this.cnt = this.cnt - 1;
         }
         else
         {
             round_handler_Reset(0);
         }
         this.nextthink = time + 1;  // canRoundStart every second
     }
     else
     {
         if (this.canRoundEnd())
         {
             // schedule a new round
             this.wait = true;
             this.nextthink = time + this.delay;
         }
         else
         {
             this.nextthink = time;  // canRoundEnd every frame
         }
     }
 }