Xonotic: menu/xonotic/colorpicker_string.qc File Reference
colorpicker_string.qc File Reference
#include "colorpicker_string.qh"
Functions
entity makeXonoticColorpickerString (string theCvar, string theDefaultCvar)
void XonoticColorpickerString_configureXonoticColorpickerString (entity me, string theCvar, string theDefaultCvar)
void XonoticColorpickerString_draw (entity me)
void XonoticColorpickerString_loadCvars (entity me)
float XonoticColorpickerString_mouseDrag (entity me, vector coords)
float XonoticColorpickerString_mousePress (entity me, vector coords)
float XonoticColorpickerString_mouseRelease (entity me, vector coords)
void XonoticColorpickerString_saveCvars (entity me)
Variables
bool disabled
Function Documentation
entity makeXonoticColorpickerString (string theCvar, string theDefaultCvar)
Definition at line 5 of file colorpicker_string.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle(), XonoticGameCrosshairSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDWeaponsDialog_fill(), and XonoticSandboxToolsDialog_fill().
 {
     entity me;
     me = NEW(XonoticColorpickerString);
     me.configureXonoticColorpickerString(me, theCvar, theDefaultCvar);
     return me;
 }
void XonoticColorpickerString_configureXonoticColorpickerString (entity me, string theCvar, string theDefaultCvar)
Definition at line 13 of file colorpicker_string.qc.
References string_null.
 {
     me.configureImage(me, me.image);
     me.cvarName = (theCvar) ? theCvar : string_null;
     me.loadCvars(me);
 }
void XonoticColorpickerString_draw (entity me)
Definition at line 84 of file colorpicker_string.qc.
References draw_alpha, draw_Picture(), draw_PictureSize(), draw_scale, globalToBoxSize(), strcat(), SUPER, and vector().
 {
     float save;
     save = draw_alpha;
     if(me.disabled)
         draw_alpha *= me.disabledAlpha;
     SUPER(XonoticColorpickerString).draw(me);
     vector sz;
     sz = draw_PictureSize(strcat(me.src, "_selected"));
     sz = globalToBoxSize(sz, draw_scale);
     if(!me.disabled)
         draw_Picture(me.imgOrigin + me.prevcoords - 0.5 * sz, strcat(me.src, "_selected"), sz, '1 1 1', 1);
     draw_alpha = save;
 }
void XonoticColorpickerString_loadCvars (entity me)
Definition at line 20 of file colorpicker_string.qc.
References color_hslimage(), cvar(), cvar_string(), eX, eY, eZ, stov(), strcat(), and substring().
 {
     if (!me.cvarName)
         return;
     if(substring(me.cvarName, -1, 1) == "_")
     {
         me.prevcoords = color_hslimage(
             eX * cvar(strcat(me.cvarName, "red")) +
             eY * cvar(strcat(me.cvarName, "green")) +
             eZ * cvar(strcat(me.cvarName, "blue")),
             me.imagemargin);
     }
     else
         me.prevcoords = color_hslimage(stov(cvar_string(me.cvarName)), me.imagemargin);
 }
float XonoticColorpickerString_mouseDrag (entity me, vector coords)
Definition at line 59 of file colorpicker_string.qc.
References vector().
 {
     if(me.disabled)
         return 0;
     vector margin;
     margin = me.imagemargin;
     if(coords.x >= margin.x)
     if(coords.y >= margin.y)
     if(coords.x <= 1 - margin.x)
     if(coords.y <= 1 - margin.y)
     {
         me.prevcoords = coords;
         me.saveCvars(me);
     }
     return 1;
 }
float XonoticColorpickerString_mousePress (entity me, vector coords)
Definition at line 53 of file colorpicker_string.qc.
 {
     me.mouseDrag(me, coords);
     return 1;
 }
float XonoticColorpickerString_mouseRelease (entity me, vector coords)
Definition at line 77 of file colorpicker_string.qc.
References m_play_click_sound(), and MENU_SOUND_SLIDE.
 {
     m_play_click_sound(MENU_SOUND_SLIDE);
     me.mouseDrag(me, coords);
     return 1;
 }
void XonoticColorpickerString_saveCvars (entity me)
Definition at line 37 of file colorpicker_string.qc.
References cvar_set(), ftos(), hslimage_color(), strcat(), substring(), and vector().
 {
     if (!me.cvarName)
         return;
     if(substring(me.cvarName, -1, 1) == "_")
     {
         vector v = hslimage_color(me.prevcoords, me.imagemargin);
         cvar_set(strcat(me.cvarName, "red"), ftos(v.x));
         cvar_set(strcat(me.cvarName, "green"), ftos(v.y));
         cvar_set(strcat(me.cvarName, "blue"), ftos(v.z));
     }
     else
         cvar_set(me.cvarName, sprintf("%v", hslimage_color(me.prevcoords, me.imagemargin)));
 }
Variable Documentation
bool disabled
Definition at line 3 of file colorpicker_string.qc.