Xonotic: server/mutators/mutator/gamemode_assault.qc File Reference
gamemode_assault.qc File Reference
#include "gamemode_assault.qh"
Macros
#define GAMEMODE_ASSAULT_H
Functions
void ActivateTeamplay ()
void assault_ScoreRules ()
REGISTER_MUTATOR (as, false)
void target_objective_decrease_activate (entity this)
void (entity this) havocbot_role
void (entity this, float ratingscale, vector org, float sradius) havocbot_goalrating_items
Variables
entity assault_decreaser
entity assault_sprite
const int HAVOCBOT_AST_ROLE_DEFENSE = 2
const int HAVOCBOT_AST_ROLE_NONE = 0
const int HAVOCBOT_AST_ROLE_OFFENSE = 4
entity havocbot_ast_target
float havocbot_attack_time
int havocbot_role_flags
const float SP_ASSAULT_OBJECTIVES = 4
const float ST_ASSAULT_OBJECTIVES = 1
Macro Definition Documentation
#define GAMEMODE_ASSAULT_H
Definition at line 3 of file gamemode_assault.qc.
Function Documentation
void ActivateTeamplay ()
Definition at line 40 of file teamplay.qc.
Referenced by REGISTER_MUTATOR().
 {
     serverflags |= SERVERFLAG_TEAMPLAY;
     teamplay = 1;
     cvar_set("teamplay", "2");  // DP needs this for sending proper getstatus replies.
 }
void assault_ScoreRules ()
Referenced by REGISTER_MUTATOR().
REGISTER_MUTATOR (as , false)
Definition at line 8 of file gamemode_assault.qc.
References ActivateTeamplay(), assault_ScoreRules(), error(), have_team_spawns, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, and time.
 {
     ActivateTeamplay();
     have_team_spawns = -1; // request team spawns
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         assault_ScoreRules();
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back assault_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
void target_objective_decrease_activate (entity this)
void (entity this)
void (entity this, float ratingscale, vector org, float sradius)
Variable Documentation
entity assault_decreaser
Definition at line 37 of file gamemode_assault.qc.
entity assault_sprite
Definition at line 38 of file gamemode_assault.qc.
const int HAVOCBOT_AST_ROLE_DEFENSE = 2
Definition at line 42 of file gamemode_assault.qc.
const int HAVOCBOT_AST_ROLE_NONE = 0
Definition at line 41 of file gamemode_assault.qc.
const int HAVOCBOT_AST_ROLE_OFFENSE = 4
Definition at line 43 of file gamemode_assault.qc.
entity havocbot_ast_target
Definition at line 53 of file gamemode_assault.qc.
float havocbot_attack_time
Definition at line 46 of file gamemode_assault.qc.
int havocbot_role_flags
Definition at line 45 of file gamemode_assault.qc.
const float SP_ASSAULT_OBJECTIVES = 4
Definition at line 62 of file gamemode_assault.qc.
const float ST_ASSAULT_OBJECTIVES = 1
Definition at line 61 of file gamemode_assault.qc.