Xonotic: server/mutators/mutator/gamemode_lms.qh File Reference
gamemode_lms.qh File Reference
#include "../gamemode.qh"
Macros
#define autocvar_g_lms_lives_override cvar("g_lms_lives_override")
Functions
void lms_Initialize ()
float LMS_NewPlayerLives ()
REGISTER_MUTATOR (lms, false)
Variables
float lms_lowest_lives
float lms_spectate_warning
Macro Definition Documentation
#define autocvar_g_lms_lives_override cvar("g_lms_lives_override")
Definition at line 6 of file gamemode_lms.qh.
Referenced by REGISTER_MUTATOR().
Function Documentation
void lms_Initialize ()
Definition at line 431 of file gamemode_lms.qc.
References lms_lowest_lives, and lms_ScoreRules().
Referenced by REGISTER_MUTATOR().
 {
     lms_lowest_lives = 9999;
     lms_ScoreRules();
 }
float LMS_NewPlayerLives ()
Definition at line 13 of file gamemode_lms.qc.
References autocvar_fraglimit, autocvar_g_lms_join_anytime, autocvar_g_lms_last_join, bound(), and lms_lowest_lives.
Referenced by MUTATOR_HOOKFUNCTION(), and WinningCondition_LMS().
 {
     float fl;
     fl = autocvar_fraglimit;
     if(fl == 0)
         fl = 999;
     // first player has left the game for dying too much? Nobody else can get in.
     if(lms_lowest_lives < 1)
         return 0;
     if(!autocvar_g_lms_join_anytime)
         if(lms_lowest_lives < fl - autocvar_g_lms_last_join)
             return 0;
     return bound(1, lms_lowest_lives, fl);
 }
REGISTER_MUTATOR (lms , false)
Definition at line 9 of file gamemode_lms.qh.
References autocvar_g_lms_lives_override, autocvar_timelimit_override, error, lms_Initialize(), LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, SetLimits(), and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         lms_Initialize();
         SetLimits(((!autocvar_g_lms_lives_override) ? -1 : autocvar_g_lms_lives_override), 0, autocvar_timelimit_override, -1);
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back lms_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
Variable Documentation
float lms_lowest_lives
Definition at line 37 of file gamemode_lms.qh.
Referenced by lms_Initialize(), LMS_NewPlayerLives(), lms_RemovePlayer(), and MUTATOR_HOOKFUNCTION().
float lms_spectate_warning
Definition at line 5 of file gamemode_lms.qh.