Xonotic: XonoticPlayerModelSelector Class Reference
XonoticPlayerModelSelector Class Reference
Public Member Functions
ATTRIB (XonoticPlayerModelSelector, currentModel, string)
ATTRIB (XonoticPlayerModelSelector, currentModelImage, string)
ATTRIB (Image, src, string)
ATTRIB (XonoticPlayerModelSelector, currentModelTitle, string)
ATTRIB (XonoticPlayerModelSelector, currentModelDescription, string)
ATTRIB (MenuItem, parent, entity)
ATTRIB (MenuItem, tooltip, string)
virtual void configureImage ()
virtual void configureXonoticImage ()
virtual void configureXonoticPlayerModelSelector ()
virtual void destroy ()
virtual void drag ()
virtual void drag_setStartPos ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void go ()
virtual void hideNotify ()
virtual void initZoom ()
virtual void keyDown ()
virtual void keyUp ()
virtual void loadCvars ()
virtual void loadModels ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void saveCvars ()
virtual void setZoom ()
virtual void showNotify ()
virtual void toString ()
virtual void updateAspect ()
Public Attributes
float allowFocusSound = 0
float bufModels = -1
vector color = '1 1 1'
float currentSkin = 0
float focusable = 0
float focused = 0
float fontSize = SKINFONTSIZE_NORMAL
float forcedAspect = 0
float idxModels = -1
vector imgOrigin = '0 0 0'
vector imgSize = '0 0 0'
float numModels = -1
vector origin = '0 0 0'
float preferredFocusPriority = 0
vector realFontSize = '0 0 0'
vector size = '0 0 0'
vector start_coords = '0 0 0'
vector start_zoomOffset = '0 0 0'
float titleFontSize = SKINFONTSIZE_TITLE
float zoomBox = 0
float zoomFactor = 1
float zoomLimitedByTheBox = 0
float zoomMax = 0
vector zoomOffset = '0.5 0.5 0'
float zoomSnapToTheBox = 1
float zoomTime = 0
Detailed Description
Definition at line 4 of file playermodel.qh.
Member Function Documentation
XonoticPlayerModelSelector::ATTRIB (XonoticPlayerModelSelector , currentModel , string)
XonoticPlayerModelSelector::ATTRIB (XonoticPlayerModelSelector , currentModelImage , string)
Image::ATTRIB (Image , src , string) inherited
XonoticPlayerModelSelector::ATTRIB (XonoticPlayerModelSelector , currentModelTitle , string)
XonoticPlayerModelSelector::ATTRIB (XonoticPlayerModelSelector , currentModelDescription , string)
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
virtual void Image::configureImage () virtual inherited
virtual void XonoticImage::configureXonoticImage () virtual inherited
virtual void XonoticPlayerModelSelector::configureXonoticPlayerModelSelector () virtual
virtual void XonoticPlayerModelSelector::destroy () virtual
Reimplemented from MenuItem.
virtual void Image::drag () virtual inherited
virtual void Image::drag_setStartPos () virtual inherited
virtual void XonoticPlayerModelSelector::draw () virtual
Reimplemented from Image.
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void MenuItem::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
virtual void XonoticPlayerModelSelector::go () virtual
void MenuItem::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void Image::initZoom () virtual inherited
void MenuItem::keyDown () virtual inherited
Reimplemented in Dialog, XonoticLanguageList, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, XonoticPlayList, XonoticSkinList, XonoticColorpicker, XonoticMapList, XonoticGametypeList, XonoticCampaignList, XonoticKeyBinder, XonoticSoundList, Button, Slider, XonoticServerList, XonoticStatsList, XonoticWeaponsList, XonoticCreditsList, XonoticPicker, InputBox, XonoticCvarList, XonoticScreenshotViewerDialog, Container, ListBox, XonoticCharmap, XonoticInputBox, Nexposee, and InputContainer.
Definition at line 62 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void XonoticPlayerModelSelector::loadCvars () virtual
virtual void XonoticPlayerModelSelector::loadModels () virtual
void MenuItem::mouseDrag () virtual inherited
Reimplemented in XonoticPlayList, Slider, XonoticWeaponsList, Button, InputBox, Container, ListBox, Nexposee, XonoticColorpickerString, XonoticScreenshotImage, InputContainer, XonoticPicker, and XonoticColorpicker.
Definition at line 82 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::mouseMove () virtual inherited
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
void MenuItem::mousePress () virtual inherited
Reimplemented in Slider, Button, InputBox, Container, ListBox, XonoticScreenshotImage, Nexposee, XonoticColorpickerString, InputContainer, XonoticColorpicker, and XonoticPicker.
Definition at line 77 of file item.qc.
     {
         return false;  // unhandled
     }
void MenuItem::mouseRelease () virtual inherited
Reimplemented in XonoticCvarList, Slider, Button, Container, ListBox, InputBox, Nexposee, XonoticColorpickerString, InputContainer, XonoticColorpicker, and XonoticPicker.
Definition at line 87 of file item.qc.
References m_play_focus_sound().
     {
         return 0;  // unhandled
     }
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticPlayerModelSelector::resizeNotify () virtual
Reimplemented from Image.
virtual void XonoticPlayerModelSelector::saveCvars () virtual
virtual void Image::setZoom () virtual inherited
virtual void XonoticPlayerModelSelector::showNotify () virtual
Reimplemented from MenuItem.
virtual void Image::toString () virtual inherited
Reimplemented from MenuItem.
virtual void Image::updateAspect () virtual inherited
Member Data Documentation
float MenuItem::allowFocusSound = 0 inherited
Definition at line 26 of file item.qh.
float XonoticPlayerModelSelector::bufModels = -1
Definition at line 24 of file playermodel.qh.
vector Image::color = '1 1 1' inherited
Definition at line 15 of file image.qh.
float XonoticPlayerModelSelector::currentSkin = 0
Definition at line 13 of file playermodel.qh.
float MenuItem::focusable = 0 inherited
Definition at line 25 of file item.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
float XonoticPlayerModelSelector::fontSize = SKINFONTSIZE_NORMAL
Definition at line 22 of file playermodel.qh.
float Image::forcedAspect = 0 inherited
Definition at line 16 of file image.qh.
float XonoticPlayerModelSelector::idxModels = -1
Definition at line 26 of file playermodel.qh.
vector Image::imgOrigin = '0 0 0' inherited
Definition at line 26 of file image.qh.
vector Image::imgSize = '0 0 0' inherited
Definition at line 27 of file image.qh.
float XonoticPlayerModelSelector::numModels = -1
Definition at line 25 of file playermodel.qh.
vector XonoticPlayerModelSelector::origin = '0 0 0'
Definition at line 19 of file playermodel.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
vector XonoticPlayerModelSelector::realFontSize = '0 0 0'
Definition at line 21 of file playermodel.qh.
vector XonoticPlayerModelSelector::size = '0 0 0'
Definition at line 20 of file playermodel.qh.
vector Image::start_coords = '0 0 0' inherited
Definition at line 25 of file image.qh.
vector Image::start_zoomOffset = '0 0 0' inherited
Definition at line 24 of file image.qh.
float XonoticPlayerModelSelector::titleFontSize = SKINFONTSIZE_TITLE
Definition at line 23 of file playermodel.qh.
float Image::zoomBox = 0 inherited
Definition at line 17 of file image.qh.
float Image::zoomFactor = 1 inherited
Definition at line 18 of file image.qh.
float Image::zoomLimitedByTheBox = 0 inherited
Definition at line 22 of file image.qh.
float Image::zoomMax = 0 inherited
Definition at line 23 of file image.qh.
vector Image::zoomOffset = '0.5 0.5 0' inherited
Definition at line 19 of file image.qh.
float Image::zoomSnapToTheBox = 1 inherited
Definition at line 20 of file image.qh.
float Image::zoomTime = 0 inherited
Definition at line 21 of file image.qh.
The documentation for this class was generated from the following file:
menu/xonotic/playermodel.qh