Xonotic: menu/xonotic/button.qh File Reference
button.qh File Reference
#include "../item/button.qh"
Classes
class XonoticButton
Functions
entity makeXonoticButton (string theText, vector theColor)
entity makeXonoticButton_T (string theText, vector theColor, string theTooltip)
Function Documentation
entity makeXonoticButton (string theText, vector theColor)
Definition at line 10 of file button.qc.
References makeXonoticButton_T(), and string_null.
Referenced by XonoticCreditsDialog_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticDemoStartConfirmDialog_fill(), XonoticDemoTimeConfirmDialog_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDConfirmDialog_fill(), XonoticHUDExitDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMapInfoDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticScreenshotViewerDialog_fill(), XonoticServerCreateTab_fill(), XonoticServerInfoDialog_fill(), XonoticServerListTab_fill(), XonoticSingleplayerDialog_fill(), XonoticUserbindEditDialog_fill(), XonoticUserSettingsTab_fill(), and XonoticWinnerDialog_fill().
 {
     return makeXonoticButton_T(theText, theColor, string_null);
 }
entity makeXonoticButton_T (string theText, vector theColor, string theTooltip)
Definition at line 3 of file button.qc.
References entity(), and NEW.
Referenced by makeXonoticButton(), XonoticDemoBrowserTab_fill(), XonoticHUDExitDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticQuitDialog_fill(), XonoticServerCreateTab_fill(), XonoticServerListTab_fill(), and XonoticTabController_makeTabButton_T().
 {
     entity me;
     me = NEW(XonoticButton);
     me.configureXonoticButton(me, theText, theColor, theTooltip);
     return me;
 }