Xonotic: menu/xonotic/cvarlist.qh File Reference
cvarlist.qh File Reference
#include "listbox.qh"
Classes
class XonoticCvarList
Functions
void CvarList_End_Editing (entity box, entity me)
void CvarList_Filter_Change (entity box, entity me)
void CvarList_Filter_ModifiedCvars (entity box, entity me)
void CvarList_Revert_Click (entity btn, entity me)
void CvarList_Value_Change (entity box, entity me)
entity makeXonoticCvarList ()
Variables
float autocvar_menu_cvarlist_onlymodified
Function Documentation
void CvarList_End_Editing (entity box, entity me)
Definition at line 251 of file cvarlist.qc.
Referenced by XonoticCvarsDialog_fill().
 {
     box.parent.setFocus(box.parent, me);
 }
void CvarList_Filter_Change (entity box, entity me)
Definition at line 126 of file cvarlist.qc.
References CvarList_Load().
Referenced by XonoticCvarsDialog_fill().
 {
     CvarList_Load(me, box.text);
     me.setSelected(me, 0);
 }
void CvarList_Filter_ModifiedCvars (entity box, entity me)
Definition at line 131 of file cvarlist.qc.
References autocvar_menu_cvarlist_onlymodified, cvar_set(), CvarList_Load(), and ftos().
Referenced by XonoticCvarsDialog_fill().
 {
     cvar_set("menu_cvarlist_onlymodified", ftos(!autocvar_menu_cvarlist_onlymodified));
     box.setChecked(box, autocvar_menu_cvarlist_onlymodified);
     CvarList_Load(me, me.controlledTextbox.text);
     me.setSelected(me, 0);
 }
void CvarList_Revert_Click (entity btn, entity me)
Definition at line 236 of file cvarlist.qc.
References autocvar_menu_forced_saved_cvars, autocvar_menu_reverted_nonsaved_cvars, cvar_set(), strcat(), strhasword, strlen(), and substring().
Referenced by XonoticCvarList_keyDown(), and XonoticCvarsDialog_fill().
 {
     me.cvarValueBox.setText(me.cvarValueBox, me.cvarDefault);
     me.cvarValueBox.cursorPos = strlen(me.cvarDefault);
     if(strhasword(autocvar_menu_forced_saved_cvars, me.cvarName))
     {
         cvar_set("menu_forced_saved_cvars", substring(strreplace(strcat(" ", me.cvarName, " "), " ", strcat(" ", autocvar_menu_forced_saved_cvars, " ")), 1, -2));
         if (autocvar_menu_reverted_nonsaved_cvars == "")
             cvar_set("menu_reverted_nonsaved_cvars", me.cvarName);
         else
             cvar_set("menu_reverted_nonsaved_cvars", strcat(autocvar_menu_reverted_nonsaved_cvars, " ", me.cvarName));
     }
     me.cvarNeedsForcing = me.updateCvarType(me);
 }
void CvarList_Value_Change (entity box, entity me)
Definition at line 220 of file cvarlist.qc.
References autocvar_menu_forced_saved_cvars, autocvar_menu_reverted_nonsaved_cvars, cvar_set(), localcmd, strcat(), and substring().
Referenced by XonoticCvarsDialog_fill().
 {
     cvar_set(me.cvarNameBox.text, box.text);
     if(me.cvarNeedsForcing)
     {
         localcmd(sprintf("\nseta %1$s \"$%1$s\"\n", me.cvarName));
         cvar_set("menu_reverted_nonsaved_cvars", substring(strreplace(strcat(" ", me.cvarName, " "), " ", strcat(" ", autocvar_menu_reverted_nonsaved_cvars, " ")), 1, -2));
         if (autocvar_menu_forced_saved_cvars == "")
             cvar_set("menu_forced_saved_cvars", me.cvarName);
         else
             cvar_set("menu_forced_saved_cvars", strcat(autocvar_menu_forced_saved_cvars, " ", me.cvarName));
         me.cvarNeedsForcing = 0;
         me.updateCvarType(me);
     }
 }
entity makeXonoticCvarList ()
Definition at line 8 of file cvarlist.qc.
References entity(), and NEW.
Referenced by XonoticCvarsDialog_fill().
 {
     entity me;
     me = NEW(XonoticCvarList);
     me.configureXonoticCvarList(me);
     return me;
 }
Variable Documentation
float autocvar_menu_cvarlist_onlymodified
Definition at line 47 of file cvarlist.qh.
Referenced by CvarList_Filter_ModifiedCvars(), and CvarList_Load().