Xonotic: XonoticTextSlider Class Reference
XonoticTextSlider Class Reference
Public Member Functions
virtual void addValue ()
ATTRIB (Label, text, string)
ATTRIB (Label, currentText, string)
ATTRIB (XonoticTextSlider, cvarName, string)
ATTRIB (Slider, src, string)
ATTRIB (MenuItem, parent, entity)
ATTRIB (Label, textEntity, entity)
ATTRIB (Slider, sliderAnim, entity)
ATTRIB (MenuItem, tooltip, string)
virtual void clearValues ()
virtual void configureLabel ()
virtual void configureSliderValues ()
virtual void configureSliderVisuals ()
virtual void configureTextSliderValues ()
virtual void configureXonoticTextSlider ()
virtual void configureXonoticTextSliderValues ()
virtual void destroy ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void getIdentifier ()
virtual void hideNotify ()
virtual void insertValue ()
virtual void keyDown ()
virtual void keyUp ()
virtual void loadCvars ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void saveCvars ()
virtual void setSliderValue ()
virtual void setText ()
virtual void setValue ()
virtual void setValue_allowAnim ()
virtual void setValue_noAnim ()
virtual void setValueFromIdentifier ()
virtual void setValueFromIdentifier_allowAnim ()
virtual void setValueFromIdentifier_noAnim ()
virtual void showNotify ()
virtual void toString ()
virtual void valueToIdentifier ()
virtual void valueToText ()
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = SKINALPHA_TEXT
float animated = 1
vector color = SKINCOLOR_SLIDER_N
vector color2 = SKINCOLOR_SLIDER_S
vector colorC = SKINCOLOR_SLIDER_C
vector colorD = SKINCOLOR_SLIDER_D
vector colorF = SKINCOLOR_SLIDER_F
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
float controlWidth = 0
float disabled = 0
float disabledAlpha = SKINALPHA_DISABLED
float focusable = 1
float focused = 0
float fontSize = SKINFONTSIZE_NORMAL
string image = SKINGFX_SLIDER
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
float marginLeft = 0
float marginRight = 0
int nValues = 0
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
float sendCvars = 0
vector size = '0 0 0'
float sliderValue = 0
float textSpace = 0
vector tolerance = '0.2 2 0'
float value = 0
float valueDigits = 0
float valueDisplayMultiplier = 1.0
string valueIdentifiers [256]
float valueKeyStep = 0
float valueMax = 0
float valueMin = 0
float valuePageStep = 0
float valueSpace = SKINWIDTH_SLIDERTEXT
float valueStep = 0
string valueStrings [256]
Detailed Description
Definition at line 4 of file textslider.qh.
Member Function Documentation
virtual void TextSlider::addValue () virtual inherited
Label::ATTRIB (Label , text , string) inherited
Label::ATTRIB (Label , currentText , string) inherited
XonoticTextSlider::ATTRIB (XonoticTextSlider , cvarName , string)
Slider::ATTRIB (Slider , src , string) inherited
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
Label::ATTRIB (Label , textEntity , entity) inherited
Slider::ATTRIB (Slider , sliderAnim , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
virtual void TextSlider::clearValues () virtual inherited
virtual void Label::configureLabel () virtual inherited
virtual void Slider::configureSliderValues () virtual inherited
virtual void Slider::configureSliderVisuals () virtual inherited
virtual void TextSlider::configureTextSliderValues () virtual inherited
virtual void XonoticTextSlider::configureXonoticTextSlider () virtual
virtual void XonoticTextSlider::configureXonoticTextSliderValues () virtual
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Slider::draw () virtual inherited
Reimplemented from Label.
Reimplemented in XonoticResolutionSlider, and XonoticPicmipSlider.
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void MenuItem::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
virtual void TextSlider::getIdentifier () virtual inherited
void MenuItem::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void TextSlider::insertValue () virtual inherited
virtual void Slider::keyDown () virtual inherited
Reimplemented from MenuItem.
virtual void Slider::keyUp () virtual inherited
Reimplemented from MenuItem.
virtual void XonoticTextSlider::loadCvars () virtual
Reimplemented in XonoticResolutionSlider, XonoticParticlesSlider, and XonoticScoreboardFadeTimeSlider.
virtual void Slider::mouseDrag () virtual inherited
Reimplemented from MenuItem.
void MenuItem::mouseMove () virtual inherited
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
void Slider::mousePress () virtual inherited
Reimplemented from MenuItem.
Definition at line 175 of file slider.qc.
References almost_in_bounds(), applyButton, ceil(), disabled, fabs(), floor(), max(), median(), min(), and pressed.
     {
         float controlCenter;
         if (this.disabled) return false;
         if (pos.x < 0) return false;
         if (pos.y < 0) return false;
         if (pos.x >= 1 - this.textSpace) return false;
         if (pos.y >= 1) return false;
         controlCenter = (this.value - this.valueMin) / (this.valueMax - this.valueMin) * (1 - this.textSpace - this.controlWidth) + 0.5 * this.controlWidth;
         if (fabs(pos.x - controlCenter) <= 0.5 * this.controlWidth)
         {
             this.pressed = 1;
             this.pressOffset = pos.x - controlCenter;
             this.previousValue = this.value;
             // this.mouseDrag(this, pos);
         }
         else
         {
             float clickValue, pageValue, inRange;
             clickValue = median(0, (pos.x - this.pressOffset - 0.5 * this.controlWidth) / (1 - this.textSpace - this.controlWidth), 1) * (this.valueMax - this.valueMin) + this.valueMin;
             inRange = (almost_in_bounds(this.valueMin, this.value, this.valueMax));
             if (pos.x < controlCenter)
             {
                 pageValue = this.value - this.valuePageStep;
                 if (this.valueStep) clickValue = floor(clickValue / this.valueStep) * this.valueStep;
                 pageValue = max(pageValue, clickValue);
             }
             else
             {
                 pageValue = this.value + this.valuePageStep;
                 if (this.valueStep) clickValue = ceil(clickValue / this.valueStep) * this.valueStep;
                 pageValue = min(pageValue, clickValue);
             }
             if (inRange) this.setValue(this, median(this.valueMin, pageValue, this.valueMax));
             else this.setValue(this, this.valueMax);
             if(this.applyButton)
                 this.applyButton.disabled = false;
             if (pageValue == clickValue)
             {
                 controlCenter = (this.value - this.valueMin) / (this.valueMax - this.valueMin) * (1 - this.textSpace - this.controlWidth) + 0.5 * this.controlWidth;
                 this.pressed = 1;
                 this.pressOffset = pos.x - controlCenter;
                 this.previousValue = this.value;
                 // this.mouseDrag(this, pos);
             }
         }
         return true;
     }
virtual void Slider::mouseRelease () virtual inherited
Reimplemented from MenuItem.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Slider::resizeNotify () virtual inherited
Reimplemented from Label.
virtual void XonoticTextSlider::saveCvars () virtual
Reimplemented in XonoticResolutionSlider, XonoticParticlesSlider, and XonoticScoreboardFadeTimeSlider.
virtual void Slider::setSliderValue () virtual inherited
virtual void Label::setText () virtual inherited
Reimplemented in InputBox, and XonoticInputBox.
virtual void XonoticTextSlider::setValue () virtual
Reimplemented from Slider.
virtual void Slider::setValue_allowAnim () virtual inherited
virtual void XonoticTextSlider::setValue_noAnim () virtual
Reimplemented from Slider.
virtual void TextSlider::setValueFromIdentifier () virtual inherited
virtual void TextSlider::setValueFromIdentifier_allowAnim () virtual inherited
virtual void TextSlider::setValueFromIdentifier_noAnim () virtual inherited
virtual void Slider::showNotify () virtual inherited
Reimplemented from MenuItem.
virtual void Slider::toString () virtual inherited
Reimplemented from Label.
virtual void TextSlider::valueToIdentifier () virtual inherited
virtual void TextSlider::valueToText () virtual inherited
Reimplemented from Slider.
Member Data Documentation
float XonoticTextSlider::align = 0.5
Definition at line 13 of file textslider.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float Slider::allowFocusSound = 1 inherited
Definition at line 25 of file slider.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float XonoticTextSlider::alpha = SKINALPHA_TEXT
Definition at line 25 of file textslider.qh.
float Slider::animated = 1 inherited
Definition at line 27 of file slider.qh.
vector XonoticTextSlider::color = SKINCOLOR_SLIDER_N
Definition at line 14 of file textslider.qh.
vector XonoticTextSlider::color2 = SKINCOLOR_SLIDER_S
Definition at line 18 of file textslider.qh.
vector XonoticTextSlider::colorC = SKINCOLOR_SLIDER_C
Definition at line 15 of file textslider.qh.
vector XonoticTextSlider::colorD = SKINCOLOR_SLIDER_D
Definition at line 17 of file textslider.qh.
vector XonoticTextSlider::colorF = SKINCOLOR_SLIDER_F
Definition at line 16 of file textslider.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
float Slider::controlWidth = 0 inherited
Definition at line 38 of file slider.qh.
float Slider::disabled = 0 inherited
Definition at line 43 of file slider.qh.
float XonoticTextSlider::disabledAlpha = SKINALPHA_DISABLED
Definition at line 26 of file textslider.qh.
float Slider::focusable = 1 inherited
Definition at line 24 of file slider.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
float XonoticTextSlider::fontSize = SKINFONTSIZE_NORMAL
Definition at line 9 of file textslider.qh.
string XonoticTextSlider::image = SKINGFX_SLIDER
Definition at line 11 of file textslider.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
float Label::marginLeft = 0 inherited
Definition at line 20 of file label.qh.
float Label::marginRight = 0 inherited
Definition at line 21 of file label.qh.
int TextSlider::nValues = 0 inherited
Definition at line 19 of file textslider.qh.
vector MenuItem::origin = '0 0 0' inherited
Definition at line 29 of file item.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float Slider::pressed = 0 inherited
Definition at line 39 of file slider.qh.
float Slider::pressOffset = 0 inherited
Definition at line 40 of file slider.qh.
float Slider::previousValue = 0 inherited
Definition at line 41 of file slider.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
float XonoticTextSlider::sendCvars = 0
Definition at line 23 of file textslider.qh.
vector MenuItem::size = '0 0 0' inherited
Definition at line 30 of file item.qh.
float Slider::sliderValue = 0 inherited
Definition at line 28 of file slider.qh.
float Slider::textSpace = 0 inherited
Definition at line 37 of file slider.qh.
vector XonoticTextSlider::tolerance = '0.2 2 0'
Definition at line 12 of file textslider.qh.
float Slider::value = 0 inherited
Definition at line 26 of file slider.qh.
float Slider::valueDigits = 0 inherited
Definition at line 33 of file slider.qh.
float Slider::valueDisplayMultiplier = 1.0 inherited
Definition at line 36 of file slider.qh.
string TextSlider::valueIdentifiers[256] inherited
Definition at line 18 of file textslider.qh.
float Slider::valueKeyStep = 0 inherited
Definition at line 34 of file slider.qh.
float Slider::valueMax = 0 inherited
Definition at line 31 of file slider.qh.
float Slider::valueMin = 0 inherited
Definition at line 30 of file slider.qh.
float Slider::valuePageStep = 0 inherited
Definition at line 35 of file slider.qh.
float XonoticTextSlider::valueSpace = SKINWIDTH_SLIDERTEXT
Definition at line 10 of file textslider.qh.
float Slider::valueStep = 0 inherited
Definition at line 32 of file slider.qh.
string TextSlider::valueStrings[256] inherited
Definition at line 17 of file textslider.qh.
The documentation for this class was generated from the following file:
menu/xonotic/textslider.qh