Xonotic: common/triggers/trigger/impulse.qc File Reference
impulse.qc File Reference
#include "impulse.qh"
Functions
void trigger_impulse_touch1 (entity this, entity toucher)
void trigger_impulse_touch2 (entity this, entity toucher)
void trigger_impulse_touch3 (entity this, entity toucher)
Function Documentation
void trigger_impulse_touch1 (entity this, entity toucher)
Definition at line 3 of file impulse.qc.
References active, ACTIVE_ACTIVE, entity(), EXACTTRIGGER_TOUCH, falloff, find(), isPushable(), min(), normalize(), NULL, objerror(), origin, radius, spawnflags, strength, target, targetname, time, UNSET_ONGROUND, UpdateCSQCProjectile(), and vlen().
 {
     entity targ;
     float pushdeltatime;
     float str;
     if (this.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(toucher))
         return;
     EXACTTRIGGER_TOUCH(this, toucher);
     targ = find(NULL, targetname, this.target);
     if(!targ)
     {
         objerror(this, "trigger_force without a (valid) .target!\n");
         delete(this);
         return;
     }
     str = min(this.radius, vlen(this.origin - toucher.origin));
     if(this.falloff == 1)
         str = (str / this.radius) * this.strength;
     else if(this.falloff == 2)
         str = (1 - (str / this.radius)) * this.strength;
     else
         str = this.strength;
     pushdeltatime = time - toucher.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     toucher.lastpushtime = time;
     if(!pushdeltatime) return;
     if(this.spawnflags & 64)
     {
         float addspeed = str - toucher.velocity * normalize(targ.origin - this.origin);
         if (addspeed > 0)
         {
             float accelspeed = min(8 * pushdeltatime * str, addspeed);
             toucher.velocity += accelspeed * normalize(targ.origin - this.origin);
         }
     }
     else
         toucher.velocity = toucher.velocity + normalize(targ.origin - this.origin) * str * pushdeltatime;
     UNSET_ONGROUND(toucher);
 #ifdef SVQC
     UpdateCSQCProjectile(toucher);
 #endif
 }
void trigger_impulse_touch2 (entity this, entity toucher)
Definition at line 59 of file impulse.qc.
References active, ACTIVE_ACTIVE, EXACTTRIGGER_TOUCH, isPushable(), pow(), strength, time, and UpdateCSQCProjectile().
 {
     float pushdeltatime;
     if (this.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(toucher))
         return;
     EXACTTRIGGER_TOUCH(this, toucher);
     pushdeltatime = time - toucher.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     toucher.lastpushtime = time;
     if(!pushdeltatime) return;
     // div0: ticrate independent, 1 = identity (not 20)
     toucher.velocity = toucher.velocity * pow(this.strength, pushdeltatime);
 #ifdef SVQC
     UpdateCSQCProjectile(toucher);
 #endif
 }
void trigger_impulse_touch3 (entity this, entity toucher)
Definition at line 85 of file impulse.qc.
References active, ACTIVE_ACTIVE, EXACTTRIGGER_TOUCH, falloff, isPushable(), min(), normalize(), origin, radius, strength, time, UpdateCSQCProjectile(), and vlen().
 {
     float pushdeltatime;
     float str;
     if (this.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(toucher))
         return;
     EXACTTRIGGER_TOUCH(this, toucher);
     pushdeltatime = time - toucher.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     toucher.lastpushtime = time;
     if(!pushdeltatime) return;
     setsize(this, '-1 -1 -1' * this.radius,'1 1 1' * this.radius);
     str = min(this.radius, vlen(this.origin - toucher.origin));
     if(this.falloff == 1)
         str = (1 - str / this.radius) * this.strength; // 1 in the inside
     else if(this.falloff == 2)
         str = (str / this.radius) * this.strength; // 0 in the inside
     else
         str = this.strength;
     toucher.velocity = toucher.velocity + normalize(toucher.origin - this.origin) * str * pushdeltatime;
 #ifdef SVQC
     UpdateCSQCProjectile(toucher);
 #endif
 }