Xonotic: menu/xonotic/commandbutton.qc File Reference
commandbutton.qc File Reference
#include "commandbutton.qh"
Functions
entity makeXonoticCommandButton (string theText, vector theColor, string theCommand, float theFlags)
entity makeXonoticCommandButton_T (string theText, vector theColor, string theCommand, float theFlags, string theTooltip)
void XonoticCommandButton_Click (entity me, entity other)
void XonoticCommandButton_configureXonoticCommandButton (entity me, string theText, vector theColor, string theCommand, float theFlags, string theTooltip)
Function Documentation
entity makeXonoticCommandButton (string theText, vector theColor, string theCommand, float theFlags)
Definition at line 10 of file commandbutton.qc.
References makeXonoticCommandButton_T(), and string_null.
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticLanguageWarningDialog_fill(), XonoticMonsterToolsDialog_fill(), XonoticProfileTab_fill(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticTeamSelectDialog_fill(), XonoticUid2NameDialog_fill(), XonoticUserSettingsTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticCommandButton_T(theText, theColor, theCommand, theFlags, string_null);
 }
entity makeXonoticCommandButton_T (string theText, vector theColor, string theCommand, float theFlags, string theTooltip)
Definition at line 3 of file commandbutton.qc.
References entity(), and NEW.
Referenced by makeXonoticCommandButton(), XonoticQuitDialog_fill(), and XonoticServerListTab_fill().
 {
     entity me;
     me = NEW(XonoticCommandButton);
     me.configureXonoticCommandButton(me, theText, theColor, theCommand, theFlags, theTooltip);
     return me;
 }
void XonoticCommandButton_Click (entity me, entity other)
Definition at line 15 of file commandbutton.qc.
References cmd(), COMMANDBUTTON_CLOSE, m_goto(), and string_null.
Referenced by XonoticCommandButton_configureXonoticCommandButton().
 {
     //if(me.flags & COMMANDBUTTON_APPLY)
     //  saveAllCvars(me.parent);
     cmd("\n", me.onClickCommand, "\n");
     //if(me.flags & COMMANDBUTTON_REVERT)
     //  loadAllCvars(me.parent);
     if(me.flags & COMMANDBUTTON_CLOSE)
         m_goto(string_null);
 }
void XonoticCommandButton_configureXonoticCommandButton (entity me, string theText, vector theColor, string theCommand, float theFlags, string theTooltip)
Definition at line 26 of file commandbutton.qc.
References XonoticCommandButton_Click().
 {
     me.configureXonoticButton(me, theText, theColor, theTooltip);
     me.onClickCommand = theCommand;
     me.flags = theFlags;
     me.onClick = XonoticCommandButton_Click;
     me.onClickEntity = me;
 }