Xonotic: common/effects/effectinfo_gentle_particlegibs.inc File Reference
effectinfo_gentle_particlegibs.inc File Reference
Functions
DEF (particlegibs_damage_hit)
DEF (particlegibs_damage_dissolve)
SUB (particlegibs_damage_hit)
SUB (particlegibs_damage_dissolve)
Function Documentation
DEF (particlegibs_damage_hit)
Referenced by SUB().
DEF (particlegibs_damage_dissolve)
SUB (particlegibs_damage_hit)
Definition at line 4 of file effectinfo_gentle_particlegibs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
Referenced by SUB().
{
     MY(airfriction) = 3;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 428;
     MY(bounce) = -1;
     MY(color_min) = "0xA8FFFF";
     MY(color_max) = "0xA8FFFFF";
     MY(count) = 0.500000;
     MY(gravity) = 1;
     MY(liquidfriction) = 6;
     MY(size_min) = 5;
     MY(size_max) = 10;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_max) = 8;
     MY(type) = "blood";
     MY(velocityjitter) = '156.0 156.0 212.0';
 }
SUB (particlegibs_damage_dissolve)
Definition at line 80 of file effectinfo_gentle_particlegibs.inc.
References alpha_max, alpha_min, count, gravity, originjitter, and SUB().
{
     MY(airfriction) = 3;
     MY(alpha_min) = 256;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 328;
     MY(color_min) = "0x00ffff";
     MY(color_max) = "0x82ffff";
     MY(count) = 32;
     MY(gravity) = 1;
     MY(liquidfriction) = 6;
     MY(originjitter) = '10.0 10.0 25.0';
     MY(size_min) = 15;
     MY(size_max) = 20;
     MY(staincolor_min) = "0x808080";
     MY(staincolor_max) = "0x808080";
     MY(staintex_min) = 16;
     MY(staintex_max) = 24;
     MY(tex_max) = 8;
     MY(type) = "blood";
     MY(velocityjitter) = '256.0 256.0 312.0';
 }