Xonotic: server/antilag.qh File Reference
antilag.qh File Reference
Macros
#define ANTILAG_LATENCY(e) min(0.4, CS(e).ping * 0.001)
Functions
void antilag_clear (entity e, entity store)
void antilag_record (entity e, entity store, float t)
void antilag_restore (entity e, entity store)
void antilag_restore_all (entity ignore)
void antilag_takeback (entity e, entity store, float t)
void antilag_takeback_all (entity ignore, float lag)
vector antilag_takebackorigin (entity e, entity store, float t)
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Variables
float antilag_debug
Macro Definition Documentation
#define ANTILAG_LATENCY (e) min(0.4, CS(e).ping * 0.001)
Definition at line 14 of file antilag.qh.
Referenced by anticheat_fixangle(), crosshair_trace(), fireBullet(), FireRailgunBullet(), W_HitPlotAnalysis(), W_SetupShot_Dir_ProjectileSize_Range(), and WarpZone_crosshair_trace().
Function Documentation
void antilag_clear (entity e, entity store)
Definition at line 114 of file antilag.qc.
References ANTILAG_MAX_ORIGINS, and antilag_restore().
Referenced by PutPlayerInServer(), vehicles_damage(), and vehicles_enter().
 {
     antilag_restore(e, store);
     for (int i = 0; i < ANTILAG_MAX_ORIGINS; ++i) {
         store.antilag_times[i] = -2342;
         store.antilag_origins[i] = e.origin;
     }
     store.antilag_index = ANTILAG_MAX_ORIGINS - 1; // next one is 0
 }
void antilag_record (entity e, entity store, float t)
Definition at line 21 of file antilag.qc.
References ANTILAG_MAX_ORIGINS, antilag_record(), antilag_takebackorigin(), time, and VHF_PLAYERSLOT.
Referenced by antilag_record(), and EndFrame().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_record(e.vehicle, e.vehicle, t);
     }
     if (time < store.antilag_times[store.antilag_index]) return;
     store.antilag_index += 1;
     if (store.antilag_index >= ANTILAG_MAX_ORIGINS)
         store.antilag_index = 0;
     store.antilag_times[store.antilag_index] = t;
     store.antilag_origins[store.antilag_index] = e.origin;
     if (store.antilag_debug)
         te_spark(antilag_takebackorigin(e, store, t - store.antilag_debug), '0 0 0', 32);
 }
void antilag_restore (entity e, entity store)
Definition at line 101 of file antilag.qc.
References antilag_restore(), setorigin(), and VHF_PLAYERSLOT.
Referenced by antilag_clear(), antilag_restore(), antilag_restore_all(), and W_HitPlotAnalysis().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_restore(e.vehicle, e.vehicle);
     }
     if (!store.antilag_takenback) return;
     setorigin(e, store.antilag_saved_origin);
     store.antilag_takenback = false;
 }
void antilag_restore_all (entity ignore)
Definition at line 138 of file antilag.qc.
References antilag_restore(), CS(), FOREACH_CLIENT, g_monsters, g_projectiles, IL_EACH, and IS_PLAYER.
Referenced by fireBullet(), and tracebox_antilag_force_wz().
 {
     FOREACH_CLIENT(IS_PLAYER(it) && it != ignore, antilag_restore(it, CS(it)));
     IL_EACH(g_monsters, it != ignore,
     {
         antilag_restore(it, it);
     });
     IL_EACH(g_projectiles, it != ignore && it.classname == "nade",
     {
         antilag_restore(it, it);
     });
 }
void antilag_takeback (entity e, entity store, float t)
Definition at line 86 of file antilag.qc.
References antilag_takeback(), antilag_takebackorigin(), setorigin(), vector(), and VHF_PLAYERSLOT.
Referenced by antilag_takeback(), antilag_takeback_all(), and W_HitPlotAnalysis().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_takeback(e.vehicle, e.vehicle, t);
     }
     if (!store.antilag_takenback)
         store.antilag_saved_origin = e.origin;
     vector org = antilag_takebackorigin(e, store, t);
     setorigin(e, org);
     store.antilag_takenback = true;
 }
void antilag_takeback_all (entity ignore, float lag)
Definition at line 125 of file antilag.qc.
References antilag_takeback(), CS(), FOREACH_CLIENT, g_monsters, g_projectiles, IL_EACH, IS_PLAYER, and time.
Referenced by fireBullet(), and tracebox_antilag_force_wz().
 {
     FOREACH_CLIENT(IS_PLAYER(it) && it != ignore, antilag_takeback(it, CS(it), time - lag));
     IL_EACH(g_monsters, it != ignore,
     {
         antilag_takeback(it, it, time - lag);
     });
     IL_EACH(g_projectiles, it != ignore && it.classname == "nade",
     {
         antilag_takeback(it, it, time - lag);
     });
 }
vector antilag_takebackorigin (entity e, entity store, float t)
Definition at line 60 of file antilag.qc.
References antilag_find(), ANTILAG_MAX_ORIGINS, and lerpv().
Referenced by antilag_record(), antilag_takeback(), and antilag_takebackavgvelocity().
 {
     int i0 = antilag_find(e, store, t);
     if (i0 < 0)
     {
         // IN THE PRESENT
         if(store.antilag_takenback)
             return store.antilag_saved_origin;
         else
             return e.origin;
     }
     int i1 = i0 + 1;
     if (i1 >= ANTILAG_MAX_ORIGINS)
         i1 = 0;
     return lerpv(store.antilag_times[i0], store.antilag_origins[i0], store.antilag_times[i1], store.antilag_origins[i1], t);
 }
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 200 of file antilag.qc.
References autocvar_g_antilag, CS(), IS_CLIENT, and tracebox_antilag_force_wz().
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, false);
 }
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
Definition at line 159 of file antilag.qc.
References antilag_restore_all(), antilag_takeback_all(), DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, IS_REAL_CLIENT, and WarpZone_TraceBox().
Referenced by tracebox_antilag(), traceline_antilag_force(), WarpZone_tracebox_antilag(), and WarpZone_traceline_antilag_force().
 {
     // check whether antilagged traces are enabled
     if (lag < 0.001)
         lag = 0;
     if (!IS_REAL_CLIENT(forent))
         lag = 0; // only antilag for clients
     // change shooter to SOLID_BBOX so the shot can hit corpses
     int oldsolid = source.dphitcontentsmask;
     if(source)
         source.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
     if (lag)
         antilag_takeback_all(forent, lag);
     // do the trace
     if(wz)
         WarpZone_TraceBox (v1, mi, ma, v2, nomonst, forent);
     else
         tracebox (v1, mi, ma, v2, nomonst, forent);
     // restore players to current positions
     if (lag)
         antilag_restore_all(forent);
     // restore shooter solid type
     if(source)
         source.dphitcontentsmask = oldsolid;
 }
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 193 of file antilag.qc.
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 189 of file antilag.qc.
References tracebox_antilag_force_wz().
Referenced by traceline_antilag(), W_HitPlotAnalysis(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, false);
 }
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 218 of file antilag.qc.
References autocvar_g_antilag, CS(), IS_CLIENT, and tracebox_antilag_force_wz().
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, true);
 }
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 211 of file antilag.qc.
 {
     bool noantilag = ((IS_CLIENT(source)) ? CS(source).cvar_cl_noantilag : false);
     if (autocvar_g_antilag != 2 || noantilag)
         lag = 0;
     WarpZone_traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 207 of file antilag.qc.
References tracebox_antilag_force_wz().
Referenced by WarpZone_traceline_antilag().
 {
     tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, true);
 }
Variable Documentation
float antilag_debug
Definition at line 12 of file antilag.qh.