Xonotic: common/mutators/mutator/bloodloss/sv_bloodloss.qc File Reference
sv_bloodloss.qc File Reference
#include "sv_bloodloss.qh"
Functions
MUTATOR_HOOKFUNCTION (bloodloss, PlayerPreThink)
MUTATOR_HOOKFUNCTION (bloodloss, PlayerJump)
MUTATOR_HOOKFUNCTION (bloodloss, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (bloodloss, BuildMutatorsPrettyString)
REGISTER_MUTATOR (bloodloss, cvar("g_bloodloss"))
Variables
float bloodloss_timer
Function Documentation
MUTATOR_HOOKFUNCTION (bloodloss , PlayerPreThink)
Definition at line 7 of file sv_bloodloss.qc.
References autocvar_g_bloodloss, entity(), IS_DEAD, IS_PLAYER, M_ARGV, PHYS_INPUT_BUTTON_CROUCH, random(), time, and vehicles_exit().
 {
     entity player = M_ARGV(0, entity);
     if(IS_PLAYER(player))
     if(player.health <= autocvar_g_bloodloss && !IS_DEAD(player))
     {
         PHYS_INPUT_BUTTON_CROUCH(player) = true;
         if(time >= player.bloodloss_timer)
         {
             if(player.vehicle)
                 vehicles_exit(player.vehicle, VHEF_RELEASE);
             if(player.event_damage)
                 player.event_damage(player, player, player, 1, DEATH_ROT.m_id, player.origin, '0 0 0');
             player.bloodloss_timer = time + 0.5 + random() * 0.5;
         }
     }
 }
MUTATOR_HOOKFUNCTION (bloodloss , PlayerJump)
Definition at line 27 of file sv_bloodloss.qc.
References autocvar_g_bloodloss, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.health <= autocvar_g_bloodloss)
         return true;
 }
MUTATOR_HOOKFUNCTION (bloodloss , BuildMutatorsString)
Definition at line 35 of file sv_bloodloss.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":bloodloss");
 }
MUTATOR_HOOKFUNCTION (bloodloss , BuildMutatorsPrettyString)
Definition at line 40 of file sv_bloodloss.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Blood loss");
 }
REGISTER_MUTATOR (bloodloss , cvar("g_bloodloss"))
Variable Documentation
float bloodloss_timer
Definition at line 5 of file sv_bloodloss.qc.