Xonotic: lib/csqcmodel/sv_model.qh File Reference
sv_model.qh File Reference
#include "common.qh"
Macros
#define CSQCMODEL_ENDIF
#define CSQCMODEL_IF(cond)
#define CSQCMODEL_PROPERTY(flag, t, r, w, f)
#define CSQCMODEL_PROPERTY_SCALED(flag, t, r, w, f, s, mi, ma)
Functions
void CSQCModel_CheckUpdate (entity e)
void CSQCModel_LinkEntity (entity e)
void CSQCModel_UnlinkEntity (entity e)
Macro Definition Documentation
#define CSQCMODEL_ENDIF
Definition at line 33 of file sv_model.qh.
#define CSQCMODEL_IF (cond)
Definition at line 32 of file sv_model.qh.
#define CSQCMODEL_PROPERTY (flag, t, r, w, f)
Value:
.t f; \
    .t csqcmodel_##f;
Definition at line 34 of file sv_model.qh.
#define CSQCMODEL_PROPERTY_SCALED (flag, t, r, w, f, s, mi, ma)
Value:
.t f; \
    .t csqcmodel_##f;
Definition at line 37 of file sv_model.qh.
Function Documentation
void CSQCModel_CheckUpdate (entity e)
Definition at line 68 of file sv_model.qc.
References ALLPROPERTIES, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_ORIGIN, CSQCMODEL_PROPERTY_TELEPORTED, CSQCPLAYER_FORCE_UPDATES, EF_RESTARTANIM_BIT, EF_TELEPORT_BIT, IS_CLIENT, random(), and time.
Referenced by CSQCModel_LinkEntity().
 {
     // some nice flags for CSQCMODEL_IF
     noref float isplayer = IS_CLIENT(e);
     noref float islocalplayer = isplayer; // we set BOTH to 1 here as we need the sendflags
     noref float isnolocalplayer = isplayer; // we set BOTH to 1 here as we need the sendflags
 #if CSQCPLAYER_FORCE_UPDATES
     if(isplayer && time > e.csqcmodel_nextforcedupdate)
     {
         e.SendFlags |= CSQCMODEL_PROPERTY_ORIGIN;
         e.csqcmodel_nextforcedupdate = time + (1 / (CSQCPLAYER_FORCE_UPDATES)) * (0.5 + random()); // ensure about 4 origin sends per sec
     }
 #endif
     if(e.effects & EF_RESTARTANIM_BIT)
     {
         e.SendFlags |= CSQCMODEL_PROPERTY_FRAME | CSQCMODEL_PROPERTY_FRAME2; // full anim resend please
         e.effects &= ~EF_RESTARTANIM_BIT;
     }
     if(e.effects & EF_TELEPORT_BIT)
     {
         e.SendFlags |= CSQCMODEL_PROPERTY_TELEPORTED; // no interpolation please
         e.effects &= ~EF_TELEPORT_BIT;
     }
 #define CSQCMODEL_IF(cond) if(cond) {
 #define CSQCMODEL_ENDIF }
 #define CSQCMODEL_PROPERTY(flag,t,r,w,f) \
     { \
         t tmp = e.f; \
         if(tmp != e.csqcmodel_##f) \
         { \
             e.csqcmodel_##f = tmp; \
             e.SendFlags |= flag; \
         } \
     }
 #define CSQCMODEL_PROPERTY_SCALED(flag,t,r,w,f,s,mi,ma) \
     { \
         t tmp = rint(bound(mi, s * e.f, ma) - mi); \
         if(tmp != e.csqcmodel_##f) \
         { \
             e.csqcmodel_##f = tmp; \
             e.SendFlags |= flag; \
         } \
     }
     ALLPROPERTIES
 #undef CSQCMODEL_PROPERTY_SCALED
 #undef CSQCMODEL_PROPERTY
 #undef CSQCMODEL_ENDIF
 #undef CSQCMODEL_IF
 }
void CSQCModel_LinkEntity (entity e)
Definition at line 122 of file sv_model.qc.
References CSQCModel_CheckUpdate(), CSQCModel_Send(), and setSendEntity.
 {
     setSendEntity(e, CSQCModel_Send);
     e.SendFlags = 0xFFFFFF;
     CSQCModel_CheckUpdate(e);
 }
void CSQCModel_UnlinkEntity (entity e)
Definition at line 129 of file sv_model.qc.
References func_null(), and setSendEntity.
Referenced by Monster_Dead(), and vehicles_enter().
 {
     setSendEntity(e, func_null);
 }