Xonotic: common/triggers/trigger/swamp.qc File Reference
swamp.qc File Reference
#include "swamp.qh"
Functions
void swamp_touch (entity this, entity toucher)
void swampslug_think (entity this)
Variables
float swamp_interval
float swamp_slowdown
entity swampslug
Function Documentation
void swamp_touch (entity this, entity toucher)
Definition at line 64 of file swamp.qc.
References dmg, EXACTTRIGGER_TOUCH, IS_DEAD, IS_PLAYER, setthink, spawn(), swamp_interval, swamp_slowdown, swampslug_think(), and time.
 {
     // If whatever thats touching the swamp is not a player
     // or if its a dead player, just dont care abt it.
     if(!IS_PLAYER(toucher) || IS_DEAD(toucher))
         return;
     EXACTTRIGGER_TOUCH(this, toucher);
     // Chech if player alredy got a swampslug.
     if(toucher.in_swamp != 1)
     {
         // If not attach one.
         //centerprint(toucher,"Entering swamp!\n");
         toucher.swampslug = spawn();
         toucher.swampslug.health = 2;
         setthink(toucher.swampslug, swampslug_think);
         toucher.swampslug.nextthink = time;
         toucher.swampslug.owner = toucher;
         toucher.swampslug.dmg = this.dmg;
         toucher.swampslug.swamp_interval = this.swamp_interval;
         toucher.swamp_slowdown = this.swamp_slowdown;
         toucher.in_swamp = 1;
         return;
     }
     //toucher.in_swamp = 1;
     //Revitalize players swampslug
     toucher.swampslug.health = 2;
 }
void swampslug_think (entity this)
Definition at line 40 of file swamp.qc.
References Damage(), dmg, health, nextthink, owner, swamp_interval, and time.
Referenced by swamp_touch().
 {
     //Slowly kill the slug
     this.health = this.health - 1;
     //Slug dead? then remove curses.
     if(this.health <= 0)
     {
         this.owner.in_swamp = 0;
         delete(this);
         //centerprint(this.owner,"Killing slug...\n");
         return;
     }
     // Slug still alive, so we are still in the swamp
     // Or we have exited it very recently.
     // Do the damage and renew the timer.
 #ifdef SVQC
     Damage (this.owner, this, this, this.dmg, DEATH_SWAMP.m_id, this.owner.origin, '0 0 0');
 #endif
     this.nextthink = time + this.swamp_interval;
 }
Variable Documentation
float swamp_interval
Definition at line 19 of file swamp.qc.
Referenced by swamp_touch(), and swampslug_think().
float swamp_slowdown
Definition at line 20 of file swamp.qc.
Referenced by swamp_touch().
entity swampslug
Definition at line 21 of file swamp.qc.