Xonotic: lib/matrix/matrix.qc File Reference
matrix.qc File Reference
#include "matrix.qh"
Functions
void MX_Forget (string room)
void MX_JLF_ (entity fh, entity pass, int status)
void MX_Join (string room)
void MX_Leave (string room)
void MX_Messages (string from)
void MX_Messages_ (entity fh, entity pass, int status)
void MX_Nick (string name)
void MX_Nick_ (entity fh, entity pass, int status)
void MX_Say (string body)
void MX_Say_ (entity fh, entity pass, int status)
void MX_Sync (string since)
void MX_Sync_ (entity fh, entity pass, int status)
void MX_Typing (bool state)
void MX_Typing_ (entity fh, entity pass, int status)
Variables
string message
Function Documentation
void MX_Forget (string room)
Definition at line 135 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/forget?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_JLF_ (entity fh, entity pass, int status)
Definition at line 145 of file matrix.qc.
References entity(), MX_Typing_(), pass, url_fclose(), url_fputs(), and URL_READY_CANWRITE.
Referenced by MX_Forget(), MX_Join(), MX_Leave(), and MX_Sync_().
 {
     switch (status) {
         case URL_READY_CANWRITE: {
             fh.url_content_type = "application/json";
             url_fputs(fh, sprintf("{}", pass.message));
             url_fclose(fh);
             break;
         }
     }
 }
void MX_Join (string room)
Definition at line 115 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/join?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_Leave (string room)
Definition at line 125 of file matrix.qc.
References autocvar_matrix_server, FILE_WRITE, matrix_access_token, matrix_room, MX_JLF_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/leave?access_token=%s", autocvar_matrix_server, matrix_room, matrix_access_token),
         FILE_WRITE,
         MX_JLF_,
         NULL
     );
 }
void MX_Messages (string from)
Definition at line 34 of file matrix.qc.
References autocvar_matrix_server, FILE_READ, matrix_access_token, matrix_room, MX_Messages_(), NULL, and url_single_fopen().
Referenced by GENERIC_COMMAND(), and MX_Messages_().
 {
     if (!matrix_access_token) return;
     string s = sprintf("%s/_matrix/client/r0/events?room_id=%s&limit=50&timeout=30000&from=%s&access_token=%s", autocvar_matrix_server, matrix_room, from, matrix_access_token);
     url_single_fopen(
         s,
         FILE_READ,
         MX_Messages_,
         NULL
     );
 }
void MX_Messages_ (entity fh, entity pass, int status)
Definition at line 45 of file matrix.qc.
References _json_parse_object(), entity(), EXPECT_NE, json_get(), json_parse(), LOG_WARNF, MX_Handle(), MX_Messages(), MX_Sync_(), pass, stof(), strcat(), url_fclose(), url_fgets(), URL_READY_CANREAD, and URL_READY_CLOSED.
Referenced by MX_Messages(), and MX_Nick_().
 {
     switch (status) {
         default: {
             LOG_WARNF("status: %d", status);
             break;
         }
         case URL_READY_CLOSED: break;
         case URL_READY_CANREAD: {
             string json = "";
             for (string s; (s = url_fgets(fh)); ) { json = strcat(json, s, "\n"); }
             url_fclose(fh);
             int buf = json_parse(json, _json_parse_object);
             EXPECT_NE(-1, buf);
             for (int i = 0, n = stof(json_get(buf, "chunk.length")); i < n; ++i) {
                 MX_Handle(buf, sprintf("chunk.%d", i));
             }
             MX_Messages(json_get(buf, "end"));
             break;
         }
     }
 }
void MX_Nick (string name)
Definition at line 6 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_user, MX_Nick_(), name, new_pure, pass, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     entity pass = new_pure(mx);
     pass.message = name;
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/profile/%s/displayname?access_token=%s", autocvar_matrix_server, matrix_user, matrix_access_token),
         FILE_WRITE,
         MX_Nick_,
         pass
     );
 }
void MX_Nick_ (entity fh, entity pass, int status)
Definition at line 18 of file matrix.qc.
References entity(), MX_Messages_(), pass, url_fclose(), url_fputs(), and URL_READY_CANWRITE.
Referenced by MX_Nick().
 {
     switch (status) {
         case URL_READY_CANWRITE: {
             fh.url_verb = "PUT";
             fh.url_content_type = "application/json";
             url_fputs(fh, sprintf("{\"displayname\": \"%s\"}", pass.message));
             delete(pass);
             url_fclose(fh);
             break;
         }
     }
 }
void MX_Say (string body)
Definition at line 187 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_room, MX_Say_(), new_pure, pass, strzone(), and url_single_fopen().
Referenced by GENERIC_COMMAND(), and Say().
 {
     if (!matrix_access_token) return;
     static int txnid;
     entity pass = new_pure(mx);
     pass.message = strzone(body);
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/send/m.room.message/%d?access_token=%s", autocvar_matrix_server, matrix_room, ++txnid, matrix_access_token),
         FILE_WRITE,
         MX_Say_,
         pass
     );
 }
void MX_Say_ (entity fh, entity pass, int status)
Definition at line 200 of file matrix.qc.
References pass, strfree, url_fclose(), url_fputs(), and URL_READY_CANWRITE.
Referenced by MX_Say(), and MX_Typing_().
 {
     switch (status) {
         case URL_READY_CANWRITE: {
             fh.url_verb = "PUT";
             fh.url_content_type = "application/json";
             url_fputs(fh, sprintf("{\"msgtype\": \"m.text\", \"body\": \"%s\"}", pass.message));
             strfree(pass.message);
             delete(pass);
             url_fclose(fh);
             break;
         }
     }
 }
void MX_Sync (string since)
Definition at line 70 of file matrix.qc.
References autocvar_matrix_server, FILE_READ, matrix_access_token, matrix_room, MX_Sync_(), NULL, strcat(), and url_single_fopen().
Referenced by GENERIC_COMMAND(), and MX_Sync_().
 {
     if (!matrix_access_token) return;
     string s = strcat(autocvar_matrix_server, "/_matrix/client/r0/sync?");
     if (since) {
         s = strcat(s,
             "since=", since, "&",
             "timeout=30000&",
             sprintf("filter={\"account_data\":{\"types\":[]},\"presence\":{\"types\":[]},\"room\":{\"rooms\":[\"%s\"]}}&", matrix_room)
         );
     } else {
         s = strcat(s,
             "timeout=0&",
             "filter={\"account_data\":{\"types\":[]},\"presence\":{\"types\":[]},\"room\":{\"rooms\":[]}}&"
         );
     }
     s = strcat(s, "access_token=", matrix_access_token);
     url_single_fopen(s, FILE_READ, MX_Sync_, NULL);
 }
void MX_Sync_ (entity fh, entity pass, int status)
Definition at line 89 of file matrix.qc.
References _json_parse_object(), entity(), EXPECT_NE, json_get(), json_parse(), LOG_WARNF, matrix_room, MX_Handle(), MX_JLF_(), MX_Sync(), pass, stof(), strcat(), url_fclose(), url_fgets(), URL_READY_CANREAD, and URL_READY_CLOSED.
Referenced by MX_Messages_(), and MX_Sync().
 {
     switch (status) {
         default: {
             LOG_WARNF("status: %d", status);
             break;
         }
         case URL_READY_CLOSED: break;
         case URL_READY_CANREAD: {
             string json = "";
             for (string s; (s = url_fgets(fh)); ) { json = strcat(json, s, "\n"); }
             url_fclose(fh);
             int buf = json_parse(json, _json_parse_object);
             EXPECT_NE(-1, buf);
             string arr = sprintf("rooms.join.%s.timeline.events", matrix_room);
             for (int i = 0, n = stof(json_get(buf, sprintf("%s.length", arr))); i < n; ++i) {
                 MX_Handle(buf, sprintf("%s.%d", arr, i));
             }
             MX_Sync(json_get(buf, "next_batch"));
             break;
         }
     }
 }
void MX_Typing (bool state)
Definition at line 159 of file matrix.qc.
References autocvar_matrix_server, entity(), FILE_WRITE, matrix_access_token, matrix_room, matrix_user, MX_Typing_(), new_pure, pass, and url_single_fopen().
Referenced by GENERIC_COMMAND().
 {
     if (!matrix_access_token) return;
     entity pass = new_pure(mx);
     pass.message = state ? "true" : "false";
     url_single_fopen(
         sprintf("%s/_matrix/client/r0/rooms/%s/typing/%s?access_token=%s", autocvar_matrix_server, matrix_room, matrix_user, matrix_access_token),
         FILE_WRITE,
         MX_Typing_,
         pass
     );
 }
void MX_Typing_ (entity fh, entity pass, int status)
Definition at line 171 of file matrix.qc.
References entity(), MX_Say_(), pass, url_fclose(), url_fputs(), and URL_READY_CANWRITE.
Referenced by MX_JLF_(), and MX_Typing().
 {
     switch (status) {
         case URL_READY_CANWRITE: {
             fh.url_verb = "PUT";
             fh.url_content_type = "application/json";
             url_fputs(fh, sprintf("{\"typing\": %s, \"timeout\": 30000}", pass.message));
             delete(pass);
             url_fclose(fh);
             break;
         }
     }
 }
Variable Documentation
string message
Definition at line 3 of file matrix.qc.