Xonotic: server/pathlib/utility.qh File Reference
server/pathlib/utility.qh File Reference
Defines
#define PATHLIB_UTILITY
Functions
float fsnap (float val, float fsize)
entity pathlib_nodeatpoint (vector where)
float tile_check_plus2 (vector where)
Define Documentation
#define PATHLIB_UTILITY
Definition at line 2 of file utility.qh.
Function Documentation
float fsnap (float val, float fsize)
Definition at line 51 of file math.qh.
References rint().
Referenced by pathlib_astar(), pathlib_flynode(), pathlib_nodeatpoint(), pathlib_swimnode(), pathlib_walknode(), and pathlib_wateroutnode().
{
    return rint(val / fsize) * fsize;
}
entity pathlib_nodeatpoint (vector where)
Definition at line 53 of file utility.qc.
References entity(), fsnap(), pathlib_gridsize, pathlib_searched_cnt, and world.
Referenced by pathlib_expandnode_starf(), pathlib_makenode_adaptive(), and pathlib_mknode().
{
    entity node;
    ++pathlib_searched_cnt;
    where.x = fsnap(where.x,pathlib_gridsize);
    where.y = fsnap(where.y,pathlib_gridsize);
    node = findradius(where,pathlib_gridsize * 0.5);
    while(node)
    {
        if(node.is_path_node == true)
            return node;
        node = node.chain;
    }
    return world;
}
float tile_check_plus2 (vector where)
Definition at line 144 of file utility.qc.
References location_isok(), MOVE_WORLDONLY, p, pathlib_gridsize, pathlib_node_edgeflag_back, pathlib_node_edgeflag_backleft, pathlib_node_edgeflag_backright, pathlib_node_edgeflag_forward, pathlib_node_edgeflag_forwardleft, pathlib_node_edgeflag_forwardright, pathlib_node_edgeflag_left, pathlib_node_edgeflag_none, pathlib_node_edgeflag_right, PLIB_FORWARD, PLIB_RIGHT, SELFPARAM, tile_check_down, tile_check_up, trace_endpos, and vector().
Referenced by pathlib_expandnode_star().
{SELFPARAM();
    vector p,f,r;
    float i = 0, e = 0;
    f = PLIB_FORWARD * pathlib_gridsize;
    r = PLIB_RIGHT   * pathlib_gridsize;
//#define pathlib_node_edgeflag_left    2
//#define pathlib_node_edgeflag_right   4
//#define pathlib_node_edgeflag_forward 8
//#define pathlib_node_edgeflag_back    16
    // forward
    p = where + f;
    traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,self);
    if (location_isok(trace_endpos,1,0))
    {
       ++i;
       e |= pathlib_node_edgeflag_forward;
    }
    //left
    p = where - r;
    traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,self);
    if (location_isok(trace_endpos,1,0))
    {
       ++i;
       e |= pathlib_node_edgeflag_left;
    }
    // Right
    p = where + r;
    traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,self);
    if (location_isok(trace_endpos,1,0))
    {
       ++i;
       e |= pathlib_node_edgeflag_right;
    }
    //Back
    p = where - f;
    traceline(p+tile_check_up,p-tile_check_down,MOVE_WORLDONLY,self);
    if (location_isok(trace_endpos,1,0))
    {
       ++i;
       e |= pathlib_node_edgeflag_back;
    }
    // forward-right
    p = where + f + r;
    traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, self);
    if (location_isok(trace_endpos, 1, 0))
    {
       ++i;
       e |= pathlib_node_edgeflag_forwardright;
    }
    // Forward-left
    p = where + f - r;
    traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, self);
    if (location_isok(trace_endpos, 1, 0))
    {
       ++i;
       e |= pathlib_node_edgeflag_forwardleft;
    }
    // Back-right
    p = where - f + r;
    traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, self);
    if (location_isok(trace_endpos, 1 ,0))
    {
       ++i;
       e |= pathlib_node_edgeflag_backright;
    }
    //Back-left
    p = where - f - r;
    traceline(p + tile_check_up, p - tile_check_down, MOVE_WORLDONLY, self);
    if (location_isok(trace_endpos, 1, 0))
    {
       ++i;
       e |= pathlib_node_edgeflag_backleft;
    }
    if(i == 0)
        e = pathlib_node_edgeflag_none;
    return e;
}