Xonotic: common/triggers/func/door.qc File Reference
door.qc File Reference
Functions
void door_blocked ()
bool door_check_keys (entity door, entity player)
void door_damage (entity this, entity inflictor, entity attacker, float damage, int deathtype, vector hitloc, vector force)
void door_fire ()
void door_generic_plat_blocked ()
void door_go_down ()
void door_go_up ()
void door_hit_bottom ()
void door_hit_top ()
void door_init_startopen ()
void door_reset (entity this)
void door_rotating_go_down ()
void door_rotating_go_up ()
void door_rotating_hit_bottom ()
void door_rotating_hit_top ()
void door_spawnfield (vector fmins, vector fmaxs)
void door_touch ()
void door_trigger_touch ()
void door_use ()
void LinkDoors ()
bool LinkDoors_isconnected (entity e1, entity e2, entity pass)
entity LinkDoors_nextent (entity cur, entity near, entity pass)
void () door_go_down
Variables
float door_finished
Function Documentation
void door_blocked ()
Definition at line 28 of file door.qc.
References classname, Damage(), DAMAGE_NO, DAMAGE_YES, dmg, door_go_down(), door_go_up(), door_rotating_go_down(), door_rotating_go_up(), IS_DEAD, other, SELFPARAM, spawnflags, state, STATE_DOWN, and wait.
 {SELFPARAM();
     if((self.spawnflags & 8)
 #ifdef SVQC
         && (other.takedamage != DAMAGE_NO)
 #elif defined(CSQC)
         && !IS_DEAD(other)
 #endif
     )
     { // KIll Kill Kill!!
 #ifdef SVQC
         Damage (other, self, self, 10000, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
 #endif
     }
     else
     {
 #ifdef SVQC
         if((self.dmg) && (other.takedamage == DAMAGE_YES))    // Shall we bite?
             Damage (other, self, self, self.dmg, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
 #endif
          // don't change direction for dead or dying stuff
         if(IS_DEAD(other)
 #ifdef SVQC
             && (other.takedamage == DAMAGE_NO)
 #endif
         )
         {
             if (self.wait >= 0)
             {
                 if (self.state == STATE_DOWN)
             if (self.classname == "door")
             {
                 door_go_up ();
             } else
             {
                 door_rotating_go_up ();
             }
                 else
             if (self.classname == "door")
             {
                 door_go_down ();
             } else
             {
                 door_rotating_go_down ();
             }
             }
         }
 #ifdef SVQC
         else
         {
             //gib dying stuff just to make sure
             if((self.dmg) && (other.takedamage != DAMAGE_NO))    // Shall we bite?
                 Damage (other, self, self, 10000, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
         }
 #endif
     }
 }
bool door_check_keys (entity door, entity player)
Definition at line 157 of file door.qc.
References IS_PLAYER, item_keys_keylist(), play2(), SND, and time.
Referenced by door_trigger_touch().
 {
     if(door.owner)
         door = door.owner;
     // no key needed
     if(!door.itemkeys)
         return true;
     // this door require a key
     // only a player can have a key
     if(!IS_PLAYER(player))
         return false;
     int valid = (door.itemkeys & player.itemkeys);
     door.itemkeys &= ~valid; // only some of the needed keys were given
     if(!door.itemkeys)
     {
 #ifdef SVQC
         play2(player, SND(TALK));
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_DOOR_UNLOCKED);
 #endif
         return true;
     }
     if(!valid)
     {
 #ifdef SVQC
         if(player.key_door_messagetime <= time)
         {
             play2(player, door.noise3);
             Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_DOOR_LOCKED_NEED, item_keys_keylist(door.itemkeys));
             player.key_door_messagetime = time + 2;
         }
 #endif
         return false;
     }
     // door needs keys the player doesn't have
 #ifdef SVQC
     if(player.key_door_messagetime <= time)
     {
         play2(player, door.noise3);
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_DOOR_LOCKED_ALSONEED, item_keys_keylist(door.itemkeys));
         player.key_door_messagetime = time + 2;
     }
 #endif
     return false;
 }
void door_damage (entity this, entity inflictor, entity attacker, float damage, int deathtype, vector hitloc, vector force)
Definition at line 275 of file door.qc.
References DAMAGE_NO, DEATH_ISSPECIAL, DOOR_NOSPLASH, door_use(), health, HITTYPE_SPLASH, itemkeys, owner, spawnflags, and WITHSELF.
 {
     if(this.spawnflags & DOOR_NOSPLASH)
         if(!(DEATH_ISSPECIAL(deathtype)) && (deathtype & HITTYPE_SPLASH))
             return;
     this.health = this.health - damage;
     if (this.itemkeys)
     {
         // don't allow opening doors through damage if keys are required
         return;
     }
     if (this.health <= 0)
     {
         this.owner.health = this.owner.max_health;
         this.owner.takedamage = DAMAGE_NO;  // wil be reset upon return
         WITHSELF(this.owner, door_use());
     }
 }
void door_fire ()
Definition at line 209 of file door.qc.
References classname, door_go_down(), door_go_up(), door_rotating_go_down(), door_rotating_go_up(), DOOR_TOGGLE, enemy, entity(), lip, objerror, other, owner, SELFPARAM, setself, spawnflags, state, STATE_BOTTOM, STATE_DOWN, STATE_TOP, STATE_UP, and world.
Referenced by door_use().
 {SELFPARAM();
     entity  starte;
     if (self.owner != self)
         objerror ("door_fire: self.owner != self");
     if (self.spawnflags & DOOR_TOGGLE)
     {
         if (self.state == STATE_UP || self.state == STATE_TOP)
         {
             starte = self;
             do
             {
                 if (self.classname == "door")
                 {
                     door_go_down ();
                 }
                 else
                 {
                     door_rotating_go_down ();
                 }
                 setself(self.enemy);
             } while ( (self != starte) && (self != world) );
             setself(this);
             return;
         }
     }
 // trigger all paired doors
     starte = self;
     do
     {
         if (self.classname == "door")
         {
             door_go_up ();
         } else
         {
             // if the BIDIR spawnflag (==2) is set and the trigger has set trigger_reverse, reverse the opening direction
             if ((self.spawnflags & 2) && other.trigger_reverse!=0 && self.lip!=666 && self.state == STATE_BOTTOM)
             {
                 self.lip = 666; // self.lip is used to remember reverse opening direction for door_rotating
                 self.pos2 = '0 0 0' - self.pos2;
             }
             // if BIDIR_IN_DOWN (==8) is set, prevent the door from reoping during closing if it is triggered from the wrong side
             if (!((self.spawnflags & 2) &&  (self.spawnflags & 8) && self.state == STATE_DOWN
                 && (((self.lip==666) && (other.trigger_reverse==0)) || ((self.lip!=666) && (other.trigger_reverse!=0)))))
             {
                 door_rotating_go_up ();
             }
         }
         setself(self.enemy);
     } while ( (self != starte) && (self != world) );
     setself(this);
 }
void door_generic_plat_blocked ()
Definition at line 325 of file door.qc.
References Damage(), DAMAGE_NO, DAMAGE_YES, dmg, door_rotating_go_down(), door_rotating_go_up(), IS_DEAD, other, SELFPARAM, spawnflags, state, STATE_DOWN, and wait.
 {SELFPARAM();
     if((self.spawnflags & 8) && (other.takedamage != DAMAGE_NO)) { // KIll Kill Kill!!
 #ifdef SVQC
         Damage (other, self, self, 10000, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
 #endif
     }
     else
     {
 #ifdef SVQC
         if((self.dmg) && (other.takedamage == DAMAGE_YES))    // Shall we bite?
             Damage (other, self, self, self.dmg, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
 #endif
          //Dont chamge direction for dead or dying stuff
         if(IS_DEAD(other) && (other.takedamage == DAMAGE_NO))
         {
             if (self.wait >= 0)
             {
                 if (self.state == STATE_DOWN)
                     door_rotating_go_up ();
                 else
                     door_rotating_go_down ();
             }
         }
 #ifdef SVQC
         else
         {
             //gib dying stuff just to make sure
             if((self.dmg) && (other.takedamage != DAMAGE_NO))    // Shall we bite?
                 Damage (other, self, self, 10000, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
         }
 #endif
     }
 }
void door_go_down ()
Definition at line 111 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, DAMAGE_YES, door_hit_bottom(), max_health, noise2, pos1, SELFPARAM, speed, STATE_DOWN, SUB_CalcMove(), TSPEED_LINEAR, and VOL_BASE.
Referenced by door_blocked(), door_fire(), and door_hit_top().
 {SELFPARAM();
     if (self.noise2 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise2, VOL_BASE, ATTEN_NORM);
     if (self.max_health)
     {
         self.takedamage = DAMAGE_YES;
         self.health = self.max_health;
     }
     self.state = STATE_DOWN;
     SUB_CalcMove (self.pos1, TSPEED_LINEAR, self.speed, door_hit_bottom);
 }
void door_go_up ()
Definition at line 125 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, door_hit_top(), noise2, pos2, SELFPARAM, speed, state, STATE_TOP, STATE_UP, SUB_CalcMove(), SUB_UseTargets(), TSPEED_LINEAR, and VOL_BASE.
Referenced by door_blocked(), and door_fire().
 {SELFPARAM();
     if (self.state == STATE_UP)
         return;     // already going up
     if (self.state == STATE_TOP)
     {   // reset top wait time
         self.SUB_NEXTTHINK = self.SUB_LTIME + self.wait;
         return;
     }
     if (self.noise2 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise2, VOL_BASE, ATTEN_NORM);
     self.state = STATE_UP;
     SUB_CalcMove (self.pos2, TSPEED_LINEAR, self.speed, door_hit_top);
     string oldmessage;
     oldmessage = self.message;
     self.message = "";
     SUB_UseTargets();
     self.message = oldmessage;
 }
void door_hit_bottom ()
Definition at line 104 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, noise1, SELFPARAM, STATE_BOTTOM, and VOL_BASE.
Referenced by door_go_down().
 {SELFPARAM();
     if (self.noise1 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise1, VOL_BASE, ATTEN_NORM);
     self.state = STATE_BOTTOM;
 }
void door_hit_top ()
Definition at line 87 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, classname, door_go_down(), door_rotating_go_down(), DOOR_TOGGLE, noise1, SELFPARAM, spawnflags, STATE_TOP, and VOL_BASE.
Referenced by door_go_up().
 {SELFPARAM();
     if (self.noise1 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise1, VOL_BASE, ATTEN_NORM);
     self.state = STATE_TOP;
     if (self.spawnflags & DOOR_TOGGLE)
         return;     // don't come down automatically
     if (self.classname == "door")
     {
         self.SUB_THINK = door_go_down;
     } else
     {
         self.SUB_THINK = door_rotating_go_down;
     }
     self.SUB_NEXTTHINK = self.SUB_LTIME + self.wait;
 }
void door_init_startopen ()
Definition at line 696 of file door.qc.
References pos2, SELFPARAM, and SF_TRIGGER_UPDATE.
 {SELFPARAM();
     SUB_SETORIGIN(self, self.pos2);
     self.pos2 = self.pos1;
     self.pos1 = self.origin;
 #ifdef SVQC
     self.SendFlags |= SF_TRIGGER_UPDATE;
 #endif
 }
void door_reset (entity this)
Definition at line 707 of file door.qc.
References func_null(), pos1, SF_TRIGGER_RESET, state, and STATE_BOTTOM.
 {
     SUB_SETORIGIN(this, this.pos1);
     this.SUB_VELOCITY = '0 0 0';
     this.state = STATE_BOTTOM;
     this.SUB_THINK = func_null;
     this.SUB_NEXTTHINK = 0;
 #ifdef SVQC
     this.SendFlags |= SF_TRIGGER_RESET;
 #endif
 }
void door_rotating_go_down ()
Definition at line 386 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, DAMAGE_YES, door_rotating_hit_bottom(), max_health, noise2, pos1, SELFPARAM, speed, STATE_DOWN, SUB_CalcAngleMove(), TSPEED_LINEAR, and VOL_BASE.
Referenced by door_blocked(), door_fire(), door_generic_plat_blocked(), door_hit_top(), and door_rotating_hit_top().
 {SELFPARAM();
     if (self.noise2 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise2, VOL_BASE, ATTEN_NORM);
     if (self.max_health)
     {
         self.takedamage = DAMAGE_YES;
         self.health = self.max_health;
     }
     self.state = STATE_DOWN;
     SUB_CalcAngleMove (self.pos1, TSPEED_LINEAR, self.speed, door_rotating_hit_bottom);
 }
void door_rotating_go_up ()
Definition at line 400 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, door_rotating_hit_top(), noise2, pos2, SELFPARAM, speed, state, STATE_TOP, STATE_UP, SUB_CalcAngleMove(), SUB_UseTargets(), TSPEED_LINEAR, and VOL_BASE.
Referenced by door_blocked(), door_fire(), and door_generic_plat_blocked().
 {SELFPARAM();
     if (self.state == STATE_UP)
         return;     // already going up
     if (self.state == STATE_TOP)
     {   // reset top wait time
         self.SUB_NEXTTHINK = self.SUB_LTIME + self.wait;
         return;
     }
     if (self.noise2 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise2, VOL_BASE, ATTEN_NORM);
     self.state = STATE_UP;
     SUB_CalcAngleMove (self.pos2, TSPEED_LINEAR, self.speed, door_rotating_hit_top);
     string oldmessage;
     oldmessage = self.message;
     self.message = "";
     SUB_UseTargets();
     self.message = oldmessage;
 }
void door_rotating_hit_bottom ()
Definition at line 374 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, lip, noise1, SELFPARAM, STATE_BOTTOM, and VOL_BASE.
Referenced by door_rotating_go_down().
 {SELFPARAM();
     if (self.noise1 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise1, VOL_BASE, ATTEN_NORM);
     if (self.lip==666) // self.lip is used to remember reverse opening direction for door_rotating
     {
         self.pos2 = '0 0 0' - self.pos2;
         self.lip = 0;
     }
     self.state = STATE_BOTTOM;
 }
void door_rotating_hit_top ()
Definition at line 363 of file door.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, door_rotating_go_down(), DOOR_TOGGLE, noise1, SELFPARAM, spawnflags, STATE_TOP, and VOL_BASE.
Referenced by door_rotating_go_up().
 {SELFPARAM();
     if (self.noise1 != "")
         _sound (self, CH_TRIGGER_SINGLE, self.noise1, VOL_BASE, ATTEN_NORM);
     self.state = STATE_TOP;
     if (self.spawnflags & DOOR_TOGGLE)
         return;     // don't come down automatically
     self.SUB_THINK = door_rotating_go_down;
     self.SUB_NEXTTHINK = self.SUB_LTIME + self.wait;
 }
void door_spawnfield (vector fmins, vector fmaxs)
Definition at line 456 of file door.qc.
References door_trigger_touch(), entity(), MASK_NORMAL, MOVETYPE_NONE, SELFPARAM, SOLID_TRIGGER, and vector().
Referenced by LinkDoors().
 {SELFPARAM();
     entity  trigger;
     vector  t1 = fmins, t2 = fmaxs;
     trigger = new(doortriggerfield);
     trigger.movetype = MOVETYPE_NONE;
     trigger.solid = SOLID_TRIGGER;
     trigger.owner = self;
 #ifdef SVQC
     trigger.touch = door_trigger_touch;
 #elif defined(CSQC)
     trigger.trigger_touch = door_trigger_touch;
     trigger.draw = trigger_draw_generic;
     trigger.drawmask = MASK_NORMAL;
 #endif
     setsize (trigger, t1 - '60 60 8', t2 + '60 60 8');
 }
void door_touch ()
Definition at line 306 of file door.qc.
References centerprint(), IS_CLIENT, IS_PLAYER, other, owner, play2(), SELFPARAM, and time.
 {SELFPARAM();
     if (!IS_PLAYER(other))
         return;
     if (self.owner.door_finished > time)
         return;
     self.owner.door_finished = time + 2;
 #ifdef SVQC
     if (!(self.owner.dmg) && (self.owner.message != ""))
     {
         if (IS_CLIENT(other))
             centerprint(other, self.owner.message);
         play2(other, self.owner.noise);
     }
 #endif
 }
void door_trigger_touch ()
Definition at line 431 of file door.qc.
References activator, door_check_keys(), door_finished, door_use(), FL_PROJECTILE, IS_CLIENT, IS_DEAD, other, owner, SELFPARAM, setself, and time.
Referenced by door_spawnfield().
 {SELFPARAM();
     if (other.health < 1)
 #ifdef SVQC
         if (!((other.iscreature || (other.flags & FL_PROJECTILE)) && !IS_DEAD(other)))
 #elif defined(CSQC)
         if(!((IS_CLIENT(other) || other.classname == "csqcprojectile") && !IS_DEAD(other)))
 #endif
             return;
     if (time < self.door_finished)
         return;
     // check if door is locked
     if (!door_check_keys(self, other))
         return;
     self.door_finished = time + 1;
     activator = other;
     setself(self.owner);
     door_use ();
 }
void door_use ()
Definition at line 265 of file door.qc.
References door_fire(), owner, SELFPARAM, and WITHSELF.
Referenced by door_damage(), and door_trigger_touch().
 {SELFPARAM();
     //dprint("door_use (model: ");dprint(self.model);dprint(")\n");
     if (self.owner)
     {
         WITHSELF(self.owner, door_fire());
     }
 }
void LinkDoors ()
Definition at line 509 of file door.qc.
References absmax, absmin, door_spawnfield(), enemy, entity(), etos(), FindConnectedComponent(), health, IFTARGETED, items, LinkDoors_isconnected(), LinkDoors_nextent(), LOG_TRACE(), SELFPARAM, spawnflags, vector(), and world.
 {SELFPARAM();
     entity  t;
     vector  cmins, cmaxs;
 #ifdef SVQC
     door_link();
 #endif
     if (self.enemy)
         return;     // already linked by another door
     if (self.spawnflags & 4)
     {
         self.owner = self.enemy = self;
         if (self.health)
             return;
         IFTARGETED
             return;
         if (self.items)
             return;
         door_spawnfield(self.absmin, self.absmax);
         return;     // don't want to link this door
     }
     FindConnectedComponent(self, enemy, LinkDoors_nextent, LinkDoors_isconnected, world);
     // set owner, and make a loop of the chain
     LOG_TRACE("LinkDoors: linking doors:");
     for(t = self; ; t = t.enemy)
     {
         LOG_TRACE(" ", etos(t));
         t.owner = self;
         if(t.enemy == world)
         {
             t.enemy = self;
             break;
         }
     }
     LOG_TRACE("\n");
     // collect health, targetname, message, size
     cmins = self.absmin;
     cmaxs = self.absmax;
     for(t = self; ; t = t.enemy)
     {
         if(t.health && !self.health)
             self.health = t.health;
         if((t.targetname != "") && (self.targetname == ""))
             self.targetname = t.targetname;
         if((t.message != "") && (self.message == ""))
             self.message = t.message;
         if (t.absmin_x < cmins_x)
             cmins_x = t.absmin_x;
         if (t.absmin_y < cmins_y)
             cmins_y = t.absmin_y;
         if (t.absmin_z < cmins_z)
             cmins_z = t.absmin_z;
         if (t.absmax_x > cmaxs_x)
             cmaxs_x = t.absmax_x;
         if (t.absmax_y > cmaxs_y)
             cmaxs_y = t.absmax_y;
         if (t.absmax_z > cmaxs_z)
             cmaxs_z = t.absmax_z;
         if(t.enemy == self)
             break;
     }
     // distribute health, targetname, message
     for(t = self; t; t = t.enemy)
     {
         t.health = self.health;
         t.targetname = self.targetname;
         t.message = self.message;
         if(t.enemy == self)
             break;
     }
     // shootable, or triggered doors just needed the owner/enemy links,
     // they don't spawn a field
     if (self.health)
         return;
     IFTARGETED
         return;
     if (self.items)
         return;
     door_spawnfield(cmins, cmaxs);
 }
bool LinkDoors_isconnected (entity e1, entity e2, entity pass)
Definition at line 493 of file door.qc.
Referenced by LinkDoors().
 {
     float DELTA = 4;
     if((e1.absmin_x > e2.absmax_x + DELTA)
     || (e1.absmin_y > e2.absmax_y + DELTA)
     || (e1.absmin_z > e2.absmax_z + DELTA)
     || (e2.absmin_x > e1.absmax_x + DELTA)
     || (e2.absmin_y > e1.absmax_y + DELTA)
     || (e2.absmin_z > e1.absmax_z + DELTA)
     ) { return false; }
     return true;
 }
entity LinkDoors_nextent (entity cur, entity near, entity pass)
Definition at line 485 of file door.qc.
References classname, find(), and SELFPARAM.
Referenced by LinkDoors().
 {SELFPARAM();
     while((cur = find(cur, classname, self.classname)) && ((cur.spawnflags & 4) || cur.enemy))
     {
     }
     return cur;
 }
void ()
Variable Documentation
float door_finished
Definition at line 296 of file door.qc.
Referenced by door_trigger_touch().