Xonotic: menu/xonotic/radiobutton.qc File Reference
radiobutton.qc File Reference
#include "radiobutton.qh"
Functions
entity makeXonoticRadioButton (float theGroup, string theCvar, string theValue, string theText)
entity makeXonoticRadioButton_T (float theGroup, string theCvar, string theValue, string theText, string theTooltip)
void XonoticRadioButton_configureXonoticRadioButton (entity me, float theGroup, string theCvar, string theValue, string theText, string theTooltip)
void XonoticRadioButton_draw (entity me)
void XonoticRadioButton_loadCvars (entity me)
void XonoticRadioButton_saveCvars (entity me)
void XonoticRadioButton_setChecked (entity me, float val)
Function Documentation
entity makeXonoticRadioButton (float theGroup, string theCvar, string theValue, string theText)
Definition at line 10 of file radiobutton.qc.
References makeXonoticRadioButton_T(), and string_null.
Referenced by XonoticFirstRunDialog_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDQuickMenuDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticMonsterToolsDialog_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticSandboxToolsDialog_fill(), XonoticSingleplayerDialog_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticRadioButton_T(theGroup, theCvar, theValue, theText, string_null);
 }
entity makeXonoticRadioButton_T (float theGroup, string theCvar, string theValue, string theText, string theTooltip)
Definition at line 3 of file radiobutton.qc.
References entity(), and NEW.
Referenced by makeXonoticRadioButton(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticMutatorsDialog_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticRadioButton);
     me.configureXonoticRadioButton(me, theGroup, theCvar, theValue, theText, theTooltip);
     return me;
 }
void XonoticRadioButton_configureXonoticRadioButton (entity me, float theGroup, string theCvar, string theValue, string theText, string theTooltip)
Definition at line 14 of file radiobutton.qc.
References setZonedTooltip(), and string_null.
 {
     me.cvarName = (theCvar) ? theCvar : string_null;
     me.cvarValue = theValue;
     me.loadCvars(me);
     setZonedTooltip(me, theTooltip, theCvar);
     me.configureRadioButton(me, theText, me.fontSize, me.image, theGroup, 0);
 }
void XonoticRadioButton_draw (entity me)
Definition at line 58 of file radiobutton.qc.
References entity(), and SUPER.
 {
     if (!me.cvarValue)
         if (!me.cvarName)
         {
             // this is the "other" option
             // always select this if none other is
             entity e;
             float found;
             found = 0;
             for(e = me.parent.firstChild; e; e = e.nextSibling)
                 if(e.group == me.group)
                     if(e.checked)
                         found = 1;
             if(!found)
                 me.setChecked(me, 1);
         }
     SUPER(XonoticRadioButton).draw(me);
 }
void XonoticRadioButton_loadCvars (entity me)
Definition at line 30 of file radiobutton.qc.
References boolean, cvar(), and cvar_string().
 {
     if(me.cvarValue)
     {
         if(me.cvarName)
         {
             if(me.cvarValueIsAnotherCvar)
                 me.checked = (cvar_string(me.cvarName) == cvar_string(me.cvarValue));
             else
                 me.checked = (cvar_string(me.cvarName) == me.cvarValue);
         }
     }
     else
     {
         if(me.cvarName)
         {
             me.checked = boolean(cvar(me.cvarName));
         }
         else
         {
             // this is difficult
             // this is the "generic" selection... but at this time, not
             // everything is constructed yet.
             // we need to set this later in draw()
             me.checked = 0;
         }
     }
 }
void XonoticRadioButton_saveCvars (entity me)
Definition at line 77 of file radiobutton.qc.
References cvar_set(), cvar_string(), and ftos().
 {
     if(me.cvarValue)
     {
         if(me.cvarName)
         {
             if(me.checked)
             {
                 if(me.cvarValueIsAnotherCvar)
                     cvar_set(me.cvarName, cvar_string(me.cvarValue));
                 else
                     cvar_set(me.cvarName, me.cvarValue);
             }
             else if(me.cvarOffValue)
                 cvar_set(me.cvarName, me.cvarOffValue);
         }
     }
     else
     {
         if(me.cvarName)
         {
             cvar_set(me.cvarName, ftos(me.checked));
         }
     }
 }
void XonoticRadioButton_setChecked (entity me, float val)
Definition at line 22 of file radiobutton.qc.
 {
     if(val != me.checked)
     {
         me.checked = val;
         me.saveCvars(me);
     }
 }