Xonotic: menu/xonotic/util.qh File Reference
util.qh File Reference
Functions
void CheckSendCvars (entity me, string cvarnamestring)
void clearTooltip (entity e)
void dialog_hudpanel_main_checkbox (entity me, string panelname)
void dialog_hudpanel_main_settings (entity me, string panelname)
void forAllDescendants (entity root, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
int GameType_GetCount ()
string GameType_GetIcon (int cnt)
entity GameType_GetID (int cnt)
string GameType_GetName (int cnt)
int GameType_GetTotalCount ()
string getCvarsMulti (entity me)
float getFadedAlpha (float currentAlpha, float startAlpha, float targetAlpha)
float GL_CheckExtension (string ext)
float GL_Have_TextureCompression ()
void loadAllCvars (entity root)
void makeCallback (entity me, entity cbent, void(entity, entity) cbfunc)
void makeMulti (entity me, string otherCvars)
string resolvemod (string m)
void saveAllCvars (entity root)
void setDependent (entity e, string theCvarName, float theCvarMin, float theCvarMax)
void setDependentAND (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
void setDependentAND3 (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max, string theCvar3Name, float theCvar3Min, float theCvar3Max)
void setDependentOR (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
void setDependentStringNotEqual (entity e, string theCvarName, string theCvarValue)
void setDependentWeird (entity e, float(entity) func)
void setZonedTooltip (entity e, string theTooltip, string theCvar)
float updateCompression ()
void UpdateNotification_URI_Get_Callback (float id, float status, string data)
Variables
string _Nex_ExtResponseSystem_BannedServers
float _Nex_ExtResponseSystem_BannedServersNeedsRefresh
string _Nex_ExtResponseSystem_PromotedServers
float _Nex_ExtResponseSystem_PromotedServersNeedsRefresh
string _Nex_ExtResponseSystem_RecommendedServers
float _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh
Function Documentation
void CheckSendCvars (entity me, string cvarnamestring)
Definition at line 829 of file util.qc.
References cmd(), cvar_string(), GAME_CONNECTED, GAME_ISSERVER, gamestatus, and LOG_INFOF.
Referenced by saveCvarsMulti(), XonoticCheckBox_saveCvars(), XonoticCheckBoxString_saveCvars(), XonoticInputBox_saveCvars(), XonoticSlider_saveCvars(), and XonoticTextSlider_saveCvars().
 {
     if(me.sendCvars)
     {
         LOG_INFOF("Sending cvar: %s -> %s", cvarnamestring, cvar_string(cvarnamestring));
         if(gamestatus & (GAME_CONNECTED | GAME_ISSERVER))
         {
             cmd(sprintf("\nsendcvar %s\n", cvarnamestring));
         }
     }
 }
void clearTooltip (entity e)
Definition at line 277 of file util.qc.
References setZonedTooltip(), and string_null.
Referenced by XonoticRegisteredSettingsList::focusedItemChangeNotify(), XonoticGametypeList_focusedItemChangeNotify(), XonoticServerList_focusedItemChangeNotify(), and XonoticServerList_mouseMove().
 {
     setZonedTooltip(e, string_null, string_null);
 }
void dialog_hudpanel_main_checkbox (entity me, string panelname)
Definition at line 752 of file util.qc.
References entity(), makeXonoticCheckBox(), strcat(), and strzone().
Referenced by XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDModIconsDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDRaceTimerDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDVoteDialog_fill(), and XonoticHUDWeaponsDialog_fill().
 {
     entity e;
     me.TR(me);
         me.TDempty(me, 1.5);
         me.TD(me, 1, 2.5, e = makeXonoticCheckBox(0, strzone(strcat("hud_panel_", panelname)), _("Enable")));
 }
void dialog_hudpanel_main_settings (entity me, string panelname)
Definition at line 761 of file util.qc.
References entity(), ftos(), ftos_decimals(), makeXonoticCheckBox(), makeXonoticCheckBoxString(), makeXonoticColorpickerString(), makeXonoticTextLabel(), makeXonoticTextSlider(), setDependentStringNotEqual(), strcat(), and strzone().
Referenced by XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDModIconsDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDQuickMenuDialog_fill(), XonoticHUDRaceTimerDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDVoteDialog_fill(), and XonoticHUDWeaponsDialog_fill().
 {
     float i;
     entity e;
     me.gotoRC(me, me.currentRow + 1.5, 0);
         me.TD(me, 1, 1.4, e = makeXonoticTextLabel(0, _("Background:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 e.addValue(e, strzone(strcat("border_", panelname)), strzone(strcat("border_", panelname)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Color:")));
         me.TD(me, 2, 2.6, e = makeXonoticColorpickerString(strzone(strcat("hud_panel_", panelname, "_bg_color")), "hud_panel_bg_color"));
             setDependentStringNotEqual(e, strzone(strcat("hud_panel_", panelname, "_bg_color")), "");
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.0, e = makeXonoticCheckBoxString("", "1 1 1", strzone(strcat("hud_panel_", panelname, "_bg_color")), _("Use default")));
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Border size:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_border"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i * 2, 0)), strzone(ftos(i * 2)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Alpha:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_alpha"))));
                 e.addValue(e, _("Default"), "");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i/10, 1)), strzone(ftos(i/10)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Team Color:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_color_team"))));
                 e.addValue(e, _("Default"), "");
                 e.addValue(e, _("Disable"), "0");
                 for(i = 1; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i/10, 1)), strzone(ftos(i/10)));
                 e.configureXonoticTextSliderValues(e);
     me.TR(me);
         me.TDempty(me, 0.4);
         me.TD(me, 1, 3.6, e = makeXonoticCheckBox(0, "hud_configure_teamcolorforced", _("Test team color in configure mode")));
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Padding:")));
             me.TD(me, 1, 2.6, e = makeXonoticTextSlider(strzone(strcat("hud_panel_", panelname, "_bg_padding"))));
                 e.addValue(e, _("Default"), "");
                 for(i = 0; i <= 10; ++i)
                     e.addValue(e, strzone(ftos_decimals(i - 5, 0)), strzone(ftos(i - 5)));
                 e.configureXonoticTextSliderValues(e);
 }
void forAllDescendants (entity root, void(entity, entity) funcPre, void(entity, entity) funcPost, entity pass)
Definition at line 24 of file util.qc.
References depthfirst(), firstChild, nextSibling, and parent.
Referenced by loadAllCvars(), and saveAllCvars().
 {
     depthfirst(root, parent, firstChild, nextSibling, funcPre, funcPost, pass);
 }
int GameType_GetCount ()
Definition at line 704 of file util.qc.
References cvar(), GAMETYPES, and HIDDEN_GAMETYPES.
Referenced by XonoticGametypeList_configureXonoticGametypeList(), XonoticGametypeList_draw(), and XonoticGametypeList_loadCvars().
 {
     int i = 0;
     int dev = cvar("developer");
     #define GAMETYPE(id) ++i;
     GAMETYPES
     #undef GAMETYPE
     #define GAMETYPE(it) { if (dev > 0) ++i; }
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return i;
 }
string GameType_GetIcon (int cnt)
Definition at line 733 of file util.qc.
References entity(), GameType_GetID(), makeXonoticCheckBox(), makeXonoticCheckBoxString(), makeXonoticColorpickerString(), makeXonoticTextLabel(), makeXonoticTextSlider(), MapInfo_Type_ToString(), and strcat().
Referenced by XonoticGametypeList_configureXonoticGametypeList(), and XonoticGametypeList_drawListBoxItem().
 {
     Gametype i = GameType_GetID(cnt);
     return i ? strcat("gametype_", MapInfo_Type_ToString(i)) : "";
 }
entity GameType_GetID (int cnt)
Definition at line 694 of file util.qc.
References GAMETYPES, HIDDEN_GAMETYPES, and NULL.
Referenced by GameType_GetIcon(), GameType_GetName(), XonoticGametypeList_drawListBoxItem(), XonoticGametypeList_focusedItemChangeNotify(), XonoticGametypeList_loadCvars(), XonoticGametypeList_saveCvars(), XonoticMapInfoDialog_fill(), and XonoticMapInfoDialog_loadMapInfo().
 {
     int i = 0;
     #define GAMETYPE(it) { if (i++ == cnt) return it; }
     GAMETYPES
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return NULL;
 }
string GameType_GetName (int cnt)
Definition at line 727 of file util.qc.
References GameType_GetID(), and MapInfo_Type_ToText().
Referenced by XonoticGametypeList_drawListBoxItem().
 {
     Gametype i = GameType_GetID(cnt);
     return i ? MapInfo_Type_ToText(i) : "";
 }
int GameType_GetTotalCount ()
Definition at line 717 of file util.qc.
References GAMETYPES, and HIDDEN_GAMETYPES.
Referenced by XonoticGametypeList_configureXonoticGametypeList(), XonoticMapInfoDialog_fill(), and XonoticMapInfoDialog_loadMapInfo().
 {
     int i = 0;
     #define GAMETYPE(id) ++i;
     GAMETYPES
     HIDDEN_GAMETYPES
     #undef GAMETYPE
     return i;
 }
string getCvarsMulti (entity me)
Definition at line 58 of file util.qc.
References string_null.
Referenced by gettooltip().
 {
     if (me.cvarNames_Multi)
         return me.cvarNames_Multi;
     return string_null;
 }
float getFadedAlpha (float currentAlpha, float startAlpha, float targetAlpha)
Definition at line 820 of file util.qc.
References frametime, max(), and min().
Referenced by XonoticRegisteredSettingsList::drawListBoxItem(), XonoticCampaignList_drawListBoxItem(), XonoticCvarList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPicker_draw(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), XonoticSoundList_drawListBoxItem(), XonoticStatsList_drawListBoxItem(), and XonoticWeaponsList_drawListBoxItem().
 {
     if(startAlpha < targetAlpha)
         currentAlpha = min(currentAlpha + frametime * 0.5, targetAlpha);
     else
         currentAlpha = max(currentAlpha - frametime * 0.5, targetAlpha);
     return currentAlpha;
 }
float GL_CheckExtension (string ext)
Definition at line 13 of file util.qc.
References cvar_string(), and strhasword.
Referenced by GL_Have_TextureCompression().
 {
     return strhasword(cvar_string("gl_info_extensions"), ext);
 }
float GL_Have_TextureCompression ()
Definition at line 18 of file util.qc.
References GL_CheckExtension().
Referenced by updateCompression(), and XonoticPicmipSlider_configureXonoticPicmipSlider().
 {
     return (GL_CheckExtension("GL_EXT_texture_compression_s3tc") && GL_CheckExtension("GL_ARB_texture_compression"));
 }
void loadAllCvars (entity root)
Definition at line 51 of file util.qc.
References forAllDescendants(), loadCvarsOf(), NULL, and SUB_Null_ee().
Referenced by m_sync(), XonoticDamageTextSettings::showNotify(), XonoticCvarsDialog_showNotify(), XonoticGameCrosshairSettingsTab_showNotify(), XonoticGameHUDSettingsTab_showNotify(), XonoticGameMessageSettingsTab_showNotify(), XonoticGameModelSettingsTab_showNotify(), XonoticGameViewSettingsTab_showNotify(), XonoticGameWeaponsSettingsTab_showNotify(), XonoticMutatorsDialog_showNotify(), and XonoticTab_showNotify().
 {
     forAllDescendants(root, loadCvarsOf, SUB_Null_ee, NULL);
 }
void makeCallback (entity me, entity cbent, void(entity, entity) cbfunc)
Definition at line 105 of file util.qc.
References entity(), and saveCvarsCallback().
Referenced by XonoticServerCreateTab_fill().
 {
     e.saveCvars_Callback = e.saveCvars;
     e.saveCvars = saveCvarsCallback;
     e.saveCvars_Callback_ent = cbent;
     e.saveCvars_Callback_func = cbfunc;
 }
void makeMulti (entity me, string otherCvars)
Definition at line 90 of file util.qc.
References entity(), and saveCvarsMulti().
Referenced by XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), and XonoticMutatorsDialog_fill().
 {
     e.cvarNames_Multi = otherCvars;
     e.saveCvars_Multi = e.saveCvars;
     e.saveCvars = saveCvarsMulti;
 }
string resolvemod (string m)
Definition at line 608 of file util.qc.
References getcurrentmod().
Referenced by XonoticServerList_refreshServerList().
 {
     if(m == "=")
         return getcurrentmod();
     else
         return m;
 }
void saveAllCvars (entity root)
Definition at line 47 of file util.qc.
References forAllDescendants(), NULL, saveCvarsOf(), and SUB_Null_ee().
 {
     forAllDescendants(root, saveCvarsOf, SUB_Null_ee, NULL);
 }
void setDependent (entity e, string theCvarName, float theCvarMin, float theCvarMax)
Definition at line 178 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticDamageTextSettings::fill(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = string_null;
     e.cvar3_setDependent = string_null;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentAND (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
Definition at line 202 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), and XonoticGameViewSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = string_null;
     e.op_setDependent = 0;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentAND3 (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max, string theCvar3Name, float theCvar3Min, float theCvar3Max)
Definition at line 232 of file util.qc.
References func_null(), setDependent_Check(), and setDependent_Draw().
Referenced by XonoticEffectsSettingsTab_fill(), and XonoticGameCrosshairSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = theCvar3Name;
     e.cvar3Min_setDependent = theCvar3Min;
     e.cvar3Max_setDependent = theCvar3Max;
     e.op_setDependent = 0;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentOR (entity e, string theCvarName, float theCvarMin, float theCvarMax, string theCvar2Name, float theCvar2Min, float theCvar2Max)
Definition at line 217 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by XonoticEffectsSettingsTab_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvar_setDependent = theCvarName;
     e.cvarMin_setDependent = theCvarMin;
     e.cvarMax_setDependent = theCvarMax;
     e.cvar2_setDependent = theCvar2Name;
     e.cvar2Min_setDependent = theCvar2Min;
     e.cvar2Max_setDependent = theCvar2Max;
     e.cvar3_setDependent = string_null;
     e.op_setDependent = 1;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentStringNotEqual (entity e, string theCvarName, string theCvarValue)
Definition at line 190 of file util.qc.
References func_null(), setDependent_Check(), setDependent_Draw(), and string_null.
Referenced by dialog_hudpanel_main_settings(), XonoticAudioSettingsTab_fill(), and XonoticHUDWeaponsDialog_fill().
 {
     e.draw_setDependent = e.draw;
     e.cvarString_setDependent = theCvarName;
     e.cvarValue_setDependent = theCvarValue;
     e.cvar_setDependent = string_null;
     e.cvar2_setDependent = string_null;
     e.cvar3_setDependent = string_null;
     e.func_setDependent = func_null;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setDependentWeird (entity e, float(entity) func)
Definition at line 249 of file util.qc.
References setDependent_Check(), and setDependent_Draw().
Referenced by XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), and XonoticMutatorsDialog_fill().
 {
     e.draw_setDependent = e.draw;
     e.func_setDependent = func;
     e.draw = setDependent_Draw;
     setDependent_Check(e);
 }
void setZonedTooltip (entity e, string theTooltip, string theCvar)
Definition at line 257 of file util.qc.
References prvm_language, strfree, string_null, and strzone().
Referenced by clearTooltip(), XonoticRegisteredSettingsList::focusedItemChangeNotify(), ServerList_Update_favoriteButton(), XonoticButton_configureXonoticButton(), XonoticCheckBox_configureXonoticCheckBox(), XonoticGametypeList_focusedItemChangeNotify(), XonoticInputBox_configureXonoticInputBox(), XonoticRadioButton_configureXonoticRadioButton(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), XonoticSlider_configureXonoticSlider(), and XonoticTextSlider_configureXonoticTextSlider().
 {
     if(theTooltip == "") // no tooltip, use cvar description then
     {
         if(theCvar != "" && prvm_language == "en")
         {
             string t = cvar_description(theCvar);
             if(t != "" && t != "custom cvar")
                 theTooltip = t;
         }
     }
     else if(theTooltip == "-") // no cvar description as tooltip
     {
         theTooltip = string_null;
     }
     strfree(e.tooltip);
     e.tooltip = (theTooltip != "") ? strzone(theTooltip) : string_null;
 }
float updateCompression ()
Definition at line 616 of file util.qc.
References cvar_set(), cvar_string(), fexists(), GL_Have_TextureCompression(), and LOG_INFO.
Referenced by m_init(), m_sync(), and XonoticEffectsSettingsTab_fill().
 {
     float have_dds, have_jpg, have_tga;
     float can_dds;
     have_dds = (fexists("dds/particles/particlefont.dds"));
     have_jpg = (fexists("particles/particlefont.jpg"));
     have_tga = (fexists("particles/particlefont.tga"));
     can_dds = GL_Have_TextureCompression();
     if(have_dds && (have_jpg || have_tga))
     {
         // both? Let's only use good quality precompressed files
         // but ONLY if we actually support it!
         if(can_dds)
         {
             // these builds are meant to have GOOD quality, so let's not compress non-skinframes
             cvar_set("gl_texturecompression", "0");
             return 1;
             //cvar_set("gl_texturecompression", cvar_string("r_texture_dds_load"));
             //return 2;
         }
         else
         {
             cvar_set("gl_texturecompression", "0");
             cvar_set("r_texture_dds_load", "0");
             return 0;
         }
     }
     else if(have_dds)
     {
         // DDS only? We probably always want texture compression
         cvar_set("gl_texturecompression", "1");
         cvar_set("r_texture_dds_load", "1");
         if(!can_dds)
             LOG_INFO(_("^1ERROR: Texture compression is required but not supported.\n^1Expect visual problems."));
         return 0;
     }
     else
     {
         // TGA only? Allow runtime compression
         if(can_dds)
         {
             cvar_set("gl_texturecompression", cvar_string("r_texture_dds_load"));
             return 2;
         }
         else
         {
             cvar_set("gl_texturecompression", "0");
             cvar_set("r_texture_dds_load", "0");
             return 0;
         }
     }
 }
void UpdateNotification_URI_Get_Callback (float id, float status, string data)
Definition at line 321 of file util.qc.
References _Nex_ExtResponseSystem_BannedServers, _Nex_ExtResponseSystem_BannedServersNeedsRefresh, _Nex_ExtResponseSystem_PromotedServers, _Nex_ExtResponseSystem_PromotedServersNeedsRefresh, _Nex_ExtResponseSystem_RecommendedServers, _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh, APPEND_TO_STRING, argv(), cvar(), cvar_string(), DisableServerBackwardsCompatibility(), LOG_INFO, LOG_TRACE(), LOG_TRACEF, strcmp, strstrofs, strzone(), substring(), tokenizebyseparator, and vercmp().
Referenced by URI_Get_Callback().
 {
     float n;
     if(_Nex_ExtResponseSystem_UpdateTo)
     {
         LOG_TRACE("error: UpdateNotification_URI_Get_Callback has been called before");
         return;
     }
     if(status != 0)
     {
         LOG_TRACEF("error receiving update notification: status is %d", status);
         return;
     }
     if(substring(data, 0, 1) == "<")
     {
         LOG_TRACE("error: received HTML instead of an update notification");
         return;
     }
     if(strstrofs(data, "\r", 0) != -1)
     {
         LOG_TRACE("error: received carriage returns from update notification server");
         return;
     }
     if(data == "")
         n = 0;
     else
         n = tokenizebyseparator(data, "\n");
     float i;
     string s;
     string un_version = "";
     string un_download = "";
     string un_url = "";
     string un_bannedservers = "";
     string un_emergency_pk3s = "";
     string un_promoted = "";
     string un_recommended = "";
     string un_compatexpire = "";
     for(i = 0; i < n; ++i)
     {
         s = substring(argv(i), 2, -1);
         if(s == "") { continue; } // ignore empty lines
         switch(substring(argv(i), 0, 1))
         {
             case "V":
             {
                 un_version = s;
                 break;
             }
             case "C":
             {
                 un_compatexpire = s;
                 break;
             }
             case "D":
             {
                 un_download = s;
                 break;
             }
             case "U":
             {
                 un_url = s;
                 break;
             }
             case "B":
             {
                 APPEND_TO_STRING(un_bannedservers, " ", s);
                 break;
             }
             case "E":
             {
                 if(cvar("menu_updatecheck_getpacks"))
                     APPEND_TO_STRING(un_emergency_pk3s, " ", s);
                 break;
             }
             case "P":
             {
                 APPEND_TO_STRING(un_promoted, " ", s);
                 break;
             }
             case "R":
             {
                 APPEND_TO_STRING(un_recommended, " ", s);
                 break;
             }
         }
     }
     if(un_version != "")
     {
         if(vercmp(cvar_string("g_xonoticversion"), un_version) < 0)
         {
             // update needed
             _Nex_ExtResponseSystem_UpdateTo = strzone(un_version);
             if(un_download) { LOG_INFO(_("Update can be downloaded at:"), "\n", un_download); }
             if(un_url) { _Nex_ExtResponseSystem_UpdateToURL = strzone(un_url); }
             DisableServerBackwardsCompatibility();
         }
         else if(cvar_string("g_xonoticversion") == un_version)
         {
             if(un_compatexpire != "")
             {
                 string curdate = strftime(false, "%Y%m%d%H%M%S");
                 if (strcmp(curdate, un_compatexpire) >= 0)
                     DisableServerBackwardsCompatibility();
             }
         }
     }
     if(un_bannedservers != "")
     {
         _Nex_ExtResponseSystem_BannedServers = strzone(un_bannedservers);
         _Nex_ExtResponseSystem_BannedServersNeedsRefresh = 1;
     }
     if(un_emergency_pk3s != "")
     {
         _Nex_ExtResponseSystem_Packs = strzone(un_emergency_pk3s);
         _Nex_ExtResponseSystem_PacksStep = 1;
     }
     if(un_promoted != "")
     {
         _Nex_ExtResponseSystem_PromotedServers = strzone(un_promoted);
         _Nex_ExtResponseSystem_PromotedServersNeedsRefresh = 1;
     }
     if(un_recommended != "")
     {
         _Nex_ExtResponseSystem_RecommendedServers = strzone(un_recommended);
         _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh = 1;
     }
 }
Variable Documentation
string _Nex_ExtResponseSystem_BannedServers
Definition at line 44 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback(), and XonoticServerList_refreshServerList().
float _Nex_ExtResponseSystem_BannedServersNeedsRefresh
Definition at line 45 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback(), and XonoticServerList_draw().
string _Nex_ExtResponseSystem_PromotedServers
Definition at line 46 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback().
float _Nex_ExtResponseSystem_PromotedServersNeedsRefresh
Definition at line 47 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback(), and XonoticServerList_draw().
string _Nex_ExtResponseSystem_RecommendedServers
Definition at line 48 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback().
float _Nex_ExtResponseSystem_RecommendedServersNeedsRefresh
Definition at line 49 of file util.qh.
Referenced by UpdateNotification_URI_Get_Callback(), and XonoticServerList_draw().