Xonotic: client/commands/cl_cmd.qh File Reference
cl_cmd.qh File Reference
Macros
#define CLIENT_COMMAND(id, description)
#define CLIENT_COMMANDS_from(i) _CLIENT_COMMANDS_from(i, NULL)
Functions
void Cmd_Scoreboard_Help ()
void Cmd_Scoreboard_SetFields (int)
void LocalCommand_macro_write_aliases (int fh)
STATIC_INIT (CLIENT_COMMANDS_aliases)
Macro Definition Documentation
#define CLIENT_COMMAND (id, description)
Value:
CLASS(clientcommand_##id, Command) \
        ATTRIB(clientcommand_##id, m_name, string, #id); \
        ATTRIB(clientcommand_##id, m_description, string, description); \
    ENDCLASS(clientcommand_##id) \
    REGISTER(CLIENT_COMMANDS, CMD_CL, id, m_id, NEW(clientcommand_##id)); \
    METHOD(clientcommand_##id, m_invokecmd, void(clientcommand_##id this, int request, entity caller, int arguments, string command))
Definition at line 14 of file cl_cmd.qh.
#define CLIENT_COMMANDS_from (i) _CLIENT_COMMANDS_from(i, NULL)
Definition at line 10 of file cl_cmd.qh.
Function Documentation
void Cmd_Scoreboard_Help ()
Definition at line 292 of file scoreboard.qc.
References LOG_INFO.
Referenced by LocalCommand_hud().
 {
     LOG_INFO(_("You can modify the scoreboard using the ^2scoreboard_columns_set command.\n"));
     LOG_INFO(_("^3|---------------------------------------------------------------|\n"));
     LOG_INFO(_("Usage:\n"));
     LOG_INFO(_("^2scoreboard_columns_set default\n"));
     LOG_INFO(_("^2scoreboard_columns_set ^7field1 field2 ...\n"));
     LOG_INFO(_("The following field names are recognized (case insensitive):\n"));
     LOG_INFO(_("You can use a ^3|^7 to start the right-aligned fields.\n"));
     LOG_INFO("\n");
     LOG_INFO(_("^3name^7 or ^3nick^7             Name of a player\n"));
     LOG_INFO(_("^3ping^7                     Ping time\n"));
     LOG_INFO(_("^3pl^7                       Packet loss\n"));
     LOG_INFO(_("^3elo^7                      Player ELO\n"));
     LOG_INFO(_("^3kills^7                    Number of kills\n"));
     LOG_INFO(_("^3deaths^7                   Number of deaths\n"));
     LOG_INFO(_("^3suicides^7                 Number of suicides\n"));
     LOG_INFO(_("^3frags^7                    kills - suicides\n"));
     LOG_INFO(_("^3kd^7                       The kill-death ratio\n"));
     LOG_INFO(_("^3dmg^7                      The total damage done\n"));
     LOG_INFO(_("^3dmgtaken^7                 The total damage taken\n"));
     LOG_INFO(_("^3sum^7                      frags - deaths\n"));
     LOG_INFO(_("^3caps^7                     How often a flag (CTF) or a key (KeyHunt) was captured\n"));
     LOG_INFO(_("^3pickups^7                  How often a flag (CTF) or a key (KeyHunt) or a ball (Keepaway) was picked up\n"));
     LOG_INFO(_("^3captime^7                  Time of fastest cap (CTF)\n"));
     LOG_INFO(_("^3fckills^7                  Number of flag carrier kills\n"));
     LOG_INFO(_("^3returns^7                  Number of flag returns\n"));
     LOG_INFO(_("^3drops^7                    Number of flag drops\n"));
     LOG_INFO(_("^3lives^7                    Number of lives (LMS)\n"));
     LOG_INFO(_("^3rank^7                     Player rank\n"));
     LOG_INFO(_("^3pushes^7                   Number of players pushed into void\n"));
     LOG_INFO(_("^3destroyed^7                Number of keys destroyed by pushing them into void\n"));
     LOG_INFO(_("^3kckills^7                  Number of keys carrier kills\n"));
     LOG_INFO(_("^3losses^7                   Number of times a key was lost\n"));
     LOG_INFO(_("^3laps^7                     Number of laps finished (race/cts)\n"));
     LOG_INFO(_("^3time^7                     Total time raced (race/cts)\n"));
     LOG_INFO(_("^3fastest^7                  Time of fastest lap (race/cts)\n"));
     LOG_INFO(_("^3ticks^7                    Number of ticks (DOM)\n"));
     LOG_INFO(_("^3takes^7                    Number of domination points taken (DOM)\n"));
     LOG_INFO(_("^3bckills^7                  Number of ball carrier kills\n"));
     LOG_INFO(_("^3bctime^7                   Total amount of time holding the ball in Keepaway\n"));
     LOG_INFO(_("^3score^7                    Total score\n"));
     LOG_INFO("\n");
     LOG_INFO(_("Before a field you can put a + or - sign, then a comma separated list\n"
             "of game types, then a slash, to make the field show up only in these\n"
             "or in all but these game types. You can also specify 'all' as a\n"
             "field to show all fields available for the current game mode.\n\n"));
     LOG_INFO(_("The special game type names 'teams' and 'noteams' can be used to\n"
             "include/exclude ALL teams/noteams game modes.\n\n"));
     LOG_INFO(_("Example: scoreboard_columns_set name ping pl | +ctf/field3 -dm/field4\n"));
     LOG_INFO(_("will display name, ping and pl aligned to the left, and the fields\n"
             "right of the vertical bar aligned to the right.\n"));
     LOG_INFO(_("'field3' will only be shown in CTF, and 'field4' will be shown in all\n"
             "other gamemodes except DM.\n"));
 }
void Cmd_Scoreboard_SetFields (int)
Definition at line 371 of file scoreboard.qc.
References argv(), autocvar_scoreboard_columns, FOREACH, gametype, hud_fontsize, HUD_GetFontsize(), isGametypeInFilter(), LABEL, LOG_INFO, LOG_INFOF, MAX_SBT_FIELDS, ps_primary, ps_secondary, sbt_field, sbt_field_size, sbt_field_title, sbt_num_fields, SCOREBOARD_DEFAULT_COLUMNS, SFL_ALLOW_HIDE, strcat(), stringwidth(), strlen(), strstrofs, strunzone(), strzone(), substring(), TC, teamplay, tokenizebyseparator, and TranslateScoresLabel().
Referenced by LocalCommand_hud(), and Scoreboard_InitScores().
 {
     TC(int, argc);
     int i, slash;
     string str, pattern;
     bool have_name = false, have_primary = false, have_secondary = false, have_separator = false;
     int missing;
     if(!gametype)
         return; // do nothing, we don't know gametype and scores yet
     // sbt_fields uses strunzone on the titles!
     if(!sbt_field_title[0])
         for(i = 0; i < MAX_SBT_FIELDS; ++i)
             sbt_field_title[i] = strzone("(null)");
     // TODO: re enable with gametype dependant cvars?
     if(argc < 3) // no arguments provided
         argc = tokenizebyseparator(strcat("0 1 ", autocvar_scoreboard_columns), " ");
     if(argc < 3)
         argc = tokenizebyseparator(strcat("0 1 ", SCOREBOARD_DEFAULT_COLUMNS), " ");
     if(argc == 3)
     {
         if(argv(2) == "default")
             argc = tokenizebyseparator(strcat("0 1 ", SCOREBOARD_DEFAULT_COLUMNS), " ");
         else if(argv(2) == "all")
         {
             string s;
             s = "ping pl name |";
             FOREACH(Scores, true, {
                 if(it != ps_primary)
                 if(it != ps_secondary)
                 if(scores_label(it) != "")
                     s = strcat(s, " ", scores_label(it));
             });
             if(ps_secondary != ps_primary)
                 s = strcat(s, " ", scores_label(ps_secondary));
             s = strcat(s, " ", scores_label(ps_primary));
             argc = tokenizebyseparator(strcat("0 1 ", s), " ");
         }
     }
     sbt_num_fields = 0;
     hud_fontsize = HUD_GetFontsize("hud_fontsize");
     for(i = 1; i < argc - 1; ++i)
     {
         float nocomplain;
         str = argv(i+1);
         nocomplain = false;
         if(substring(str, 0, 1) == "?")
         {
             nocomplain = true;
             str = substring(str, 1, strlen(str) - 1);
         }
         slash = strstrofs(str, "/", 0);
         if(slash >= 0)
         {
             pattern = substring(str, 0, slash);
             str = substring(str, slash + 1, strlen(str) - (slash + 1));
             if (!isGametypeInFilter(gametype, teamplay, false, pattern))
                 continue;
         }
         strunzone(sbt_field_title[sbt_num_fields]);
         sbt_field_title[sbt_num_fields] = strzone(TranslateScoresLabel(str));
         sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
         str = strtolower(str);
         PlayerScoreField j;
         switch(str)
         {
             case "ping": sbt_field[sbt_num_fields] = SP_PING; break;
             case "pl": sbt_field[sbt_num_fields] = SP_PL; break;
             case "kd": case "kdr": case "kdratio": sbt_field[sbt_num_fields] = SP_KDRATIO; break;
             case "sum": case "diff": case "k-d": sbt_field[sbt_num_fields] = SP_SUM; break;
             case "name": case "nick": sbt_field[sbt_num_fields] = SP_NAME; have_name = true; break;
             case "|": sbt_field[sbt_num_fields] = SP_SEPARATOR; have_separator = true; break;
             case "elo": sbt_field[sbt_num_fields] = SP_ELO; break;
             case "dmg": case "damage": sbt_field[sbt_num_fields] = SP_DMG; break;
             case "dmgtaken": case "damagetaken": sbt_field[sbt_num_fields] = SP_DMGTAKEN; break;
             default:
             {
                 FOREACH(Scores, true, {
                     if (str == strtolower(scores_label(it))) {
                         j = it;
                         goto found; // sorry, but otherwise fteqcc -O3 miscompiles this and warns about "unreachable code"
                     }
                 });
 LABEL(notfound)
                 if(str == "frags")
                     j = SP_FRAGS;
                 else
                 {
                     if(!nocomplain)
                         LOG_INFOF("^1Error:^7 Unknown score field: '%s'\n", str);
                     continue;
                 }
 LABEL(found)
                 sbt_field[sbt_num_fields] = j;
                 if(j == ps_primary)
                     have_primary = true;
                 if(j == ps_secondary)
                     have_secondary = true;
             }
         }
         ++sbt_num_fields;
         if(sbt_num_fields >= MAX_SBT_FIELDS)
             break;
     }
     if(scores_flags(ps_primary) & SFL_ALLOW_HIDE)
         have_primary = true;
     if(scores_flags(ps_secondary) & SFL_ALLOW_HIDE)
         have_secondary = true;
     if(ps_primary == ps_secondary)
         have_secondary = true;
     missing = (!have_primary) + (!have_secondary) + (!have_separator) + (!have_name);
     if(sbt_num_fields + missing < MAX_SBT_FIELDS)
     {
         if(!have_name)
         {
             strunzone(sbt_field_title[sbt_num_fields]);
             for(i = sbt_num_fields; i > 0; --i)
             {
                 sbt_field_title[i] = sbt_field_title[i-1];
                 sbt_field_size[i] = sbt_field_size[i-1];
                 sbt_field[i] = sbt_field[i-1];
             }
             sbt_field_title[0] = strzone(TranslateScoresLabel("name"));
             sbt_field[0] = SP_NAME;
             ++sbt_num_fields;
             LOG_INFO("fixed missing field 'name'\n");
             if(!have_separator)
             {
                 strunzone(sbt_field_title[sbt_num_fields]);
                 for(i = sbt_num_fields; i > 1; --i)
                 {
                     sbt_field_title[i] = sbt_field_title[i-1];
                     sbt_field_size[i] = sbt_field_size[i-1];
                     sbt_field[i] = sbt_field[i-1];
                 }
                 sbt_field_title[1] = strzone("|");
                 sbt_field[1] = SP_SEPARATOR;
                 sbt_field_size[1] = stringwidth("|", false, hud_fontsize);
                 ++sbt_num_fields;
                 LOG_INFO("fixed missing field '|'\n");
             }
         }
         else if(!have_separator)
         {
             strunzone(sbt_field_title[sbt_num_fields]);
             sbt_field_title[sbt_num_fields] = strzone("|");
             sbt_field_size[sbt_num_fields] = stringwidth("|", false, hud_fontsize);
             sbt_field[sbt_num_fields] = SP_SEPARATOR;
             ++sbt_num_fields;
             LOG_INFO("fixed missing field '|'\n");
         }
         if(!have_secondary)
         {
             strunzone(sbt_field_title[sbt_num_fields]);
             sbt_field_title[sbt_num_fields] = strzone(TranslateScoresLabel(scores_label(ps_secondary)));
             sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
             sbt_field[sbt_num_fields] = ps_secondary;
             ++sbt_num_fields;
             LOG_INFOF("fixed missing field '%s'\n", scores_label(ps_secondary));
         }
         if(!have_primary)
         {
             strunzone(sbt_field_title[sbt_num_fields]);
             sbt_field_title[sbt_num_fields] = strzone(TranslateScoresLabel(scores_label(ps_primary)));
             sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
             sbt_field[sbt_num_fields] = ps_primary;
             ++sbt_num_fields;
             LOG_INFOF("fixed missing field '%s'\n", scores_label(ps_primary));
         }
     }
     sbt_field[sbt_num_fields] = SP_END;
 }
void LocalCommand_macro_write_aliases (int fh)
Definition at line 507 of file cl_cmd.qc.
References CLIENT_COMMANDS, CMD_Write_Alias, and FOREACH.
Referenced by GENERIC_COMMAND().
 {
     FOREACH(CLIENT_COMMANDS, true, CMD_Write_Alias("qc_cmd_cl", it.m_name, it.m_description));
 }
STATIC_INIT (CLIENT_COMMANDS_aliases)
Definition at line 22 of file cl_cmd.qh.
References CLIENT_COMMANDS, FOREACH, and localcmd.
{
     FOREACH(CLIENT_COMMANDS, true, localcmd(sprintf("alias %1$s \"%2$s %1$s ${* ?}\"\n", it.m_name, "qc_cmd_cl")));
 }