Xonotic: common/triggers/func/train.qh File Reference
train.qh File Reference
Variables
const int TRAIN_CURVE = BIT(0)
const int TRAIN_NEEDACTIVATION = BIT(2)
const int TRAIN_TURN = BIT(1)
Variable Documentation
const int TRAIN_CURVE = BIT(0)
Definition at line 4 of file train.qh.
Referenced by train_next(), and train_wait().
const int TRAIN_NEEDACTIVATION = BIT(2)
Definition at line 6 of file train.qh.
Referenced by train_wait().
const int TRAIN_TURN = BIT(1)
Definition at line 5 of file train.qh.