Xonotic: Spider Class Reference
Spider Class Reference
Public Member Functions
virtual void describe ()
virtual void display ()
virtual void mr_anim ()
(BOTH?) sets animations for monster
virtual void mr_death ()
(SERVER) called when monster dies
virtual void mr_pain ()
(SERVER) called when monster is damaged
virtual void mr_precache ()
(BOTH) precaches models/sounds used by this monster
virtual void mr_setup ()
(SERVER) setup monster data
virtual void mr_think ()
(SERVER) logic to run every frame
Public Attributes
Model m_model = MDL_MON_SPIDER
vector maxs = '18 18 30'
vector mins = '-18 -18 -25'
string monster_name = _("Spider")
int monsterid = 0
string netname = "spider"
int spawnflags = MON_FLAG_MELEE | MON_FLAG_RANGED | MON_FLAG_RIDE
Detailed Description
Definition at line 8 of file spider.qc.
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Monster::mr_anim () inline virtual inherited
(BOTH?) sets animations for monster
Definition at line 74 of file monster.qh.
References TC.
Referenced by Monster_UpdateModel().
 { TC(Monster, this); return false; }
virtual void Monster::mr_death () inline virtual inherited
(SERVER) called when monster dies
Definition at line 68 of file monster.qh.
References TC.
Referenced by Monster_Dead().
 { TC(Monster, this); return false; }
virtual void Monster::mr_pain () inline virtual inherited
(SERVER) called when monster is damaged
Definition at line 72 of file monster.qh.
References TC.
Referenced by Monster_Damage().
 { TC(Monster, this); return false; }
virtual void Monster::mr_precache () inline virtual inherited
(BOTH) precaches models/sounds used by this monster
Definition at line 70 of file monster.qh.
References TC.
 { TC(Monster, this); return false; }
virtual void Monster::mr_setup () inline virtual inherited
(SERVER) setup monster data
Definition at line 64 of file monster.qh.
References TC.
Referenced by Monster_Spawn_Setup().
 { TC(Monster, this); return false; }
virtual void Monster::mr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 66 of file monster.qh.
References TC.
Referenced by Monster_Think().
 { TC(Monster, this); return false; }
Member Data Documentation
Model Spider::m_model = MDL_MON_SPIDER
Definition at line 13 of file spider.qc.
vector Spider::maxs = '18 18 30'
Definition at line 11 of file spider.qc.
vector Spider::mins = '-18 -18 -25'
Definition at line 10 of file spider.qc.
string Spider::monster_name = _("Spider")
Definition at line 16 of file spider.qc.
int Monster::monsterid = 0 inherited
Definition at line 49 of file monster.qh.
string Spider::netname = "spider"
Definition at line 15 of file spider.qc.
int Spider::spawnflags = MON_FLAG_MELEE | MON_FLAG_RANGED | MON_FLAG_RIDE
Definition at line 9 of file spider.qc.
The documentation for this class was generated from the following file:
common/monsters/monster/spider.qc