Xonotic: common/items/all.qh File Reference
all.qh File Reference
#include <common/command/_mod.qh>
#include "item.qh"
Macros
#define REGISTER_ITEM(id, class) REGISTER(Items, ITEM, id, m_id, NEW(class))
Functions
void Dump_Items ()
GENERIC_COMMAND (dumpitems, "Dump all items to the console", false)
STATIC_INIT (Items)
Macro Definition Documentation
REGISTER_ITEM
#define REGISTER_ITEM (id, class) REGISTER(Items, ITEM, id, m_id, NEW(class))
Definition at line 13 of file all.qh.
Function Documentation
Dump_Items()
void Dump_Items ()
Definition at line 3 of file all.qc.
References FOREACH, and ITEM_HANDLE.
Referenced by GENERIC_COMMAND(), and STATIC_INIT().
 {
     FOREACH(Items, true, ITEM_HANDLE(Show, it));
 }
GENERIC_COMMAND()
GENERIC_COMMAND (dumpitems , "Dump all items to the console" , false)
Definition at line 36 of file all.qh.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, Dump_Items(), Item_Model(), and LOG_HELP.
{
     switch (request) {
         case CMD_REQUEST_COMMAND: {
             Dump_Items();
             return;
         }
         default:
         case CMD_REQUEST_USAGE: {
             LOG_HELP("Usage:^3 ", GetProgramCommandPrefix(), " dumpitems");
             return;
         }
     }
 }
STATIC_INIT()
STATIC_INIT (Items)
Definition at line 32 of file all.qh.
References Dump_Items(), and FOREACH.
 { FOREACH(Items, true, it.m_id = i); }