Xonotic: Shambler Class Reference
Shambler Class Reference
Public Member Functions
virtual void describe ()
virtual void display ()
virtual void mr_anim ()
(BOTH?) sets animations for monster
virtual void mr_death ()
(SERVER) called when monster dies
virtual void mr_pain ()
(SERVER) called when monster is damaged
virtual void mr_precache ()
(BOTH) precaches models/sounds used by this monster
virtual void mr_setup ()
(SERVER) setup monster data
virtual void mr_think ()
(SERVER) logic to run every frame
Public Attributes
Model m_model = MDL_MON_SHAMBLER
vector maxs = '41 41 65'
vector mins = '-41 -41 -31'
string monster_name = _("Shambler")
int monsterid = 0
string netname = "shambler"
int spawnflags = MONSTER_SIZE_BROKEN | MON_FLAG_SUPERMONSTER | MON_FLAG_MELEE | MON_FLAG_RANGED
Detailed Description
Definition at line 8 of file shambler.qc.
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 276 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 290 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Monster::mr_anim () inline virtual inherited
(BOTH?) sets animations for monster
Definition at line 74 of file monster.qh.
References TC.
Referenced by Monster_UpdateModel(), and monsters_animoverride().
 { TC(Monster, this); return false; }
virtual void Monster::mr_death () inline virtual inherited
(SERVER) called when monster dies
Definition at line 68 of file monster.qh.
References TC.
Referenced by Monster_Dead().
 { TC(Monster, this); return false; }
virtual void Monster::mr_pain () inline virtual inherited
(SERVER) called when monster is damaged
Definition at line 72 of file monster.qh.
References TC.
Referenced by Monster_Damage().
 { TC(Monster, this); return damage_take; }
virtual void Monster::mr_precache () inline virtual inherited
(BOTH) precaches models/sounds used by this monster
Definition at line 70 of file monster.qh.
References TC.
 { TC(Monster, this); return false; }
virtual void Monster::mr_setup () inline virtual inherited
(SERVER) setup monster data
Definition at line 64 of file monster.qh.
References TC.
Referenced by Monster_Spawn_Setup().
 { TC(Monster, this); return false; }
virtual void Monster::mr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 66 of file monster.qh.
References TC.
Referenced by Monster_Think().
 { TC(Monster, this); return false; }
Member Data Documentation
Model Shambler::m_model = MDL_MON_SHAMBLER
Definition at line 13 of file shambler.qc.
vector Shambler::maxs = '41 41 65'
Definition at line 11 of file shambler.qc.
vector Shambler::mins = '-41 -41 -31'
Definition at line 10 of file shambler.qc.
string Shambler::monster_name = _("Shambler")
Definition at line 16 of file shambler.qc.
int Monster::monsterid = 0 inherited
Definition at line 49 of file monster.qh.
string Shambler::netname = "shambler"
Definition at line 15 of file shambler.qc.
int Shambler::spawnflags = MONSTER_SIZE_BROKEN | MON_FLAG_SUPERMONSTER | MON_FLAG_MELEE | MON_FLAG_RANGED
Definition at line 9 of file shambler.qc.
The documentation for this class was generated from the following file:
common/monsters/monster/shambler.qc