Xonotic: menu/xonotic/dialog_hudpanel_score.qc File Reference
dialog_hudpanel_score.qc File Reference
#include "dialog_hudpanel_score.qh"
#include "checkbox.qh"
#include "textlabel.qh"
#include "radiobutton.qh"
Functions
void XonoticHUDScoreDialog_fill (entity me)
Function Documentation
XonoticHUDScoreDialog_fill()
void XonoticHUDScoreDialog_fill (entity me)
Definition at line 7 of file dialog_hudpanel_score.qc.
References dialog_hudpanel_main_checkbox(), dialog_hudpanel_main_settings(), entity(), and makeXonoticTextLabel().
 {
     entity e;
     string panelname = "score";
     dialog_hudpanel_main_checkbox(me, panelname);
     dialog_hudpanel_main_settings(me, panelname);
     me.TR(me);
         me.TD(me, 1, 4, e = makeXonoticTextLabel(0, _("Score:")));
     me.TR(me);
         me.TDempty(me, 0.2);
         me.TD(me, 1, 1.2, e = makeXonoticTextLabel(0, _("Rankings:")));
         me.TD(me, 1, 2.6/3, e = makeXonoticRadioButton(1, "hud_panel_score_rankings", "0", _("Off")));
         me.TD(me, 1, 2.6/3, e = makeXonoticRadioButton(1, "hud_panel_score_rankings", "1", _("And me")));
         me.TD(me, 1, 2.6/3, e = makeXonoticRadioButton(1, "hud_panel_score_rankings", "2", _("Pure")));
 }