Xonotic: menu/xonotic/dialog_multiplayer.qc File Reference
dialog_multiplayer.qc File Reference
#include "dialog_multiplayer.qh"
#include "tabcontroller.qh"
#include "dialog_multiplayer_join.qh"
#include "dialog_multiplayer_create.qh"
#include "dialog_multiplayer_media.qh"
#include "dialog_multiplayer_profile.qh"
Functions
void XonoticMultiplayerDialog_fill (entity me)
Function Documentation
void XonoticMultiplayerDialog_fill (entity me)
Definition at line 9 of file dialog_multiplayer.qc.
References entity(), makeXonoticMediaTab(), makeXonoticProfileTab(), makeXonoticServerCreateTab(), makeXonoticServerListTab(), and makeXonoticTabController().
 {
     entity mc, e;
     mc = makeXonoticTabController(me.rows - 1);
     me.TR(me);
         me.TD(me, 1, 1, e = mc.makeTabButton_T(mc, _("Servers"), makeXonoticServerListTab(),
             _("Find servers to play on")));
         me.TD(me, 1, 1, e = mc.makeTabButton_T(mc, _("Create"), makeXonoticServerCreateTab(),
             _("Host your own game")));
         me.TD(me, 1, 1, e = mc.makeTabButton(mc, _("Media"), makeXonoticMediaTab()));
         me.TD(me, 1, 1, e = mc.makeTabButton(mc, _("Profile"), makeXonoticProfileTab()));
     me.TR(me);
         me.TD(me, me.rows - 1, me.columns, mc);
 }