Xonotic: common/items/all.qh File Reference
all.qh File Reference
#include "../command/all.qh"
#include "item.qh"
Macros
#define ITEMS_ALL_H
#define Items_from(i) _Items_from(i, NULL)
#define REGISTER_ITEM(id, class) REGISTER(Items, ITEM, id, m_id, NEW(class))
If you register a new item, make sure to add it to all.inc.
Functions
STATIC_INIT (Items)
void Dump_Items ()
GENERIC_COMMAND (dumpitems,"Dump all items to the console")
string Item_Model (string item_mdl)
Macro Definition Documentation
#define ITEMS_ALL_H
Definition at line 2 of file all.qh.
#define Items_from (i) _Items_from(i, NULL)
Definition at line 9 of file all.qh.
#define REGISTER_ITEM (id, class) REGISTER(Items, ITEM, id, m_id, NEW(class))
If you register a new item, make sure to add it to all.inc.
Definition at line 12 of file all.qh.
Function Documentation
void Dump_Items ()
Definition at line 7 of file all.qc.
References FOREACH, ITEM_HANDLE(), and LAMBDA.
Referenced by GENERIC_COMMAND().
 {
     FOREACH(Items, true, LAMBDA(
         ITEM_HANDLE(Show, it);
     ));
 }
GENERIC_COMMAND (dumpitems , "Dump all items to the console")
Definition at line 20 of file all.qh.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, Dump_Items(), GetProgramCommandPrefix(), and LOG_INFOF.
{
     switch (request) {
         case CMD_REQUEST_COMMAND: {
             Dump_Items();
             return;
         }
         default:
         case CMD_REQUEST_USAGE: {
             LOG_INFOF("\nUsage:^3 %s dumpitems", GetProgramCommandPrefix());
             return;
         }
     }
 }
string Item_Model (string item_mdl)
Definition at line 14 of file all.qc.
References item_model_output, MUTATOR_CALLHOOK, and strcat().
 {
     string output = strcat("models/items/", item_mdl);
 #ifdef SVQC
     MUTATOR_CALLHOOK(ItemModel, item_mdl, output);
     output = item_model_output;
 #endif
     return output;
 }
STATIC_INIT (Items)
Definition at line 16 of file all.qh.
References FOREACH, and LAMBDA.
 { FOREACH(Items, true, LAMBDA(it.m_id = i)); }