Xonotic: menu/anim/easing.qc File Reference
easing.qc File Reference
#include "easing.qh"
#include "../menu.qh"
#include "keyframe.qh"
Functions
float easingLinear (float tickTime, float animDuration, float animStart, float animDelta)
float easingQuadIn (float tickTime, float animDuration, float animStart, float animDelta)
float easingQuadInOut (float tickTime, float animDuration, float animStart, float animDelta)
float easingQuadOut (float tickTime, float animDuration, float animStart, float animDelta)
entity makeEasing (entity obj, void(entity, float) objSetter, float(float, float, float, float) func, float animStartTime, float animDuration, float animStartValue, float animEnd)
entity makeHostedEasing (entity obj, void(entity, float) objSetter, float(float, float, float, float) func, float animDuration, float animStartValue, float animEnd)
Function Documentation
float easingLinear (float tickTime, float animDuration, float animStart, float animDelta)
Definition at line 31 of file easing.qc.
     {
         return (animDelta * (tickTime / animDuration)) + animStart;
     }
float easingQuadIn (float tickTime, float animDuration, float animStart, float animDelta)
Definition at line 36 of file easing.qc.
Referenced by easingQuadInOut().
     {
         float frac = tickTime / animDuration;
         return (animDelta * frac * frac) + animStart;
     }
float easingQuadInOut (float tickTime, float animDuration, float animStart, float animDelta)
Definition at line 48 of file easing.qc.
References easingQuadIn(), and easingQuadOut().
     {
         if (tickTime < (animDuration / 2)) return easingQuadIn(tickTime, (animDuration / 2), animStart, (animDelta / 2));
         else return easingQuadOut((tickTime - (animDuration / 2)), (animDuration / 2), (animStart + (animDelta / 2)), (animDelta / 2));
     }
float easingQuadOut (float tickTime, float animDuration, float animStart, float animDelta)
Definition at line 42 of file easing.qc.
Referenced by easingQuadInOut(), and Slider_setValue_allowAnim().
     {
         float frac = tickTime / animDuration;
         return (-animDelta * frac * (frac - 2)) + animStart;
     }
entity makeEasing (entity obj, void(entity, float) objSetter, float(float, float, float, float) func, float animStartTime, float animDuration, float animStartValue, float animEnd)
Definition at line 13 of file easing.qc.
References entity(), and NEW.
Referenced by Keyframe::addEasing(), and makeHostedEasing().
     {
         entity this = NEW(Easing);
         this.configureAnimation(this, obj, objSetter, animStartTime, animDuration, animStartValue, animEnd);
         this.setMath(this, func);
         return this;
     }
entity makeHostedEasing (entity obj, void(entity, float) objSetter, float(float, float, float, float) func, float animDuration, float animStartValue, float animEnd)
Definition at line 6 of file easing.qc.
References anim, entity(), makeEasing(), and time.
Referenced by Slider_setValue_allowAnim().
     {
         entity this = makeEasing(obj, objSetter, func, time, animDuration, animStartValue, animEnd);
         anim.addAnim(anim, this);
         return this;
     }