Xonotic: server/mapvoting.qc File Reference
mapvoting.qc File Reference
#include "mapvoting.qh"
#include "g_world.qh"
#include "command/cmd.qh"
#include "command/getreplies.qh"
#include "../common/constants.qh"
#include <common/net_linked.qh>
#include "../common/mapinfo.qh"
#include "../common/playerstats.qh"
#include "../common/util.qh"
Functions
bool GameTypeVote_AddVotable (string nextMode)
int GameTypeVote_AvailabilityStatus (string type_name)
bool GameTypeVote_Finished (int pos)
int GameTypeVote_GetMask ()
string GameTypeVote_MapInfo_FixName (string m)
void GameTypeVote_SendOption (int i)
bool GameTypeVote_SetGametype (Gametype type)
bool GameTypeVote_Start ()
Gametype GameTypeVote_Type_FromString (string type_name)
Returns the gamtype ID from its name, if type_name isn't a real gametype it checks for sv_vote_gametype_(type_name)_type.
void MapVote_AddVotable (string nextMap, bool isSuggestion)
void MapVote_CheckRules_1 ()
bool MapVote_CheckRules_2 ()
void MapVote_ClearAllVotes ()
bool MapVote_Finished (int mappos)
void MapVote_Init ()
bool MapVote_SendEntity (entity this, entity to, int sf)
void MapVote_SendOption (int i)
void MapVote_SendPicture (entity to, int id)
void MapVote_Spawn ()
void MapVote_Start ()
string MapVote_Suggest (entity this, string m)
void MapVote_Think ()
void MapVote_Tick ()
void MapVote_TouchMask ()
void MapVote_TouchVotes (entity voter)
void MapVote_UnzoneStrings ()
void MapVote_WriteMask ()
Variables
bool gametypevote_finished
int mapvote
bool mapvote_abstain
int mapvote_count
int mapvote_count_real
bool mapvote_detail
entity mapvote_ent
float mapvote_keeptwotime
string mapvote_maps [MAPVOTE_COUNT]
int mapvote_maps_flags [MAPVOTE_COUNT]
string mapvote_maps_pakfile [MAPVOTE_COUNT]
int mapvote_maps_screenshot_dir [MAPVOTE_COUNT]
bool mapvote_maps_suggested [MAPVOTE_COUNT]
float mapvote_nextthink
bool mapvote_run
string mapvote_screenshot_dirs [MAPVOTE_SCREENSHOT_DIRS_COUNT]
const int MAPVOTE_SCREENSHOT_DIRS_COUNT = 4
int mapvote_screenshot_dirs_count
int mapvote_selections [MAPVOTE_COUNT]
int mapvote_suggestion_ptr
string mapvote_suggestions [MAPVOTE_COUNT]
float mapvote_timeout
int mapvote_voters
Function Documentation
bool GameTypeVote_AddVotable (string nextMode)
Definition at line 747 of file mapvoting.qc.
References GameTypeVote_AvailabilityStatus(), GameTypeVote_Type_FromString(), mapvote_count, mapvote_maps, mapvote_maps_flags, mapvote_maps_pakfile, mapvote_maps_screenshot_dir, mapvote_maps_suggested, NULL, and strzone().
Referenced by GameTypeVote_Start().
 {
     if ( nextMode == "" || GameTypeVote_Type_FromString(nextMode) == NULL )
         return false;
     for(int j = 0; j < mapvote_count; ++j)
         if(mapvote_maps[j] == nextMode)
             return false;
     mapvote_maps[mapvote_count] = strzone(nextMode);
     mapvote_maps_suggested[mapvote_count] = false;
     mapvote_maps_screenshot_dir[mapvote_count] = 0;
     mapvote_maps_pakfile[mapvote_count] = strzone("");
     mapvote_maps_flags[mapvote_count] = GameTypeVote_AvailabilityStatus(nextMode);
     mapvote_count += 1;
     return true;
 }
int GameTypeVote_AvailabilityStatus (string type_name)
Definition at line 53 of file mapvoting.qc.
References autocvar_nextmap, cvar_string(), GTV_AVAILABLE, GTV_CUSTOM, GTV_FORBIDDEN, MapInfo_Get_ByName(), MapInfo_Map_supportedGametypes, MapInfo_Type_FromString(), NULL, and strcat().
Referenced by GameTypeVote_AddVotable().
 {
     int flag = GTV_FORBIDDEN;
     Gametype type = MapInfo_Type_FromString(type_name);
     if ( type == NULL )
     {
         type = MapInfo_Type_FromString(cvar_string(
             strcat("sv_vote_gametype_",type_name,"_type")));
         flag |= GTV_CUSTOM;
     }
     if( type == NULL )
         return flag;
     if ( autocvar_nextmap != "" )
     {
         if ( !MapInfo_Get_ByName(autocvar_nextmap, false, NULL) )
             return flag;
         if (!(MapInfo_Map_supportedGametypes & type.m_flags))
             return flag;
     }
     return flag | GTV_AVAILABLE;
 }
bool GameTypeVote_Finished (int pos)
Definition at line 729 of file mapvoting.qc.
References gametypevote, GameTypeVote_SetGametype(), GameTypeVote_Type_FromString(), localcmd, LOG_TRACE(), and mapvote_maps.
Referenced by MapVote_Finished().
 {
     if(!gametypevote || gametypevote_finished)
         return false;
     if ( !GameTypeVote_SetGametype(GameTypeVote_Type_FromString(mapvote_maps[pos])) )
     {
         LOG_TRACE("Selected gametype is not supported by any map");
     }
     localcmd("sv_vote_gametype_hook_all\n");
     localcmd("sv_vote_gametype_hook_", mapvote_maps[pos], "\n");
     gametypevote_finished = true;
     return true;
 }
int GameTypeVote_GetMask ()
Definition at line 79 of file mapvoting.qc.
References argv(), autocvar_sv_vote_gametype_options, GameTypeVote_Type_FromString(), MAPVOTE_COUNT, min(), and tokenizebyseparator.
Referenced by GameTypeVote_MapInfo_FixName().
 {
     int n, j, gametype_mask;
     n = tokenizebyseparator(autocvar_sv_vote_gametype_options, " ");
     n = min(MAPVOTE_COUNT, n);
     gametype_mask = 0;
     for(j = 0; j < n; ++j)
         gametype_mask |= GameTypeVote_Type_FromString(argv(j)).m_flags;
     return gametype_mask;
 }
string GameTypeVote_MapInfo_FixName (string m)
Definition at line 90 of file mapvoting.qc.
References _MapInfo_FilterGametype(), autocvar_sv_vote_gametype, GameTypeVote_GetMask(), MapInfo_Enumerate(), MapInfo_FixName(), MapInfo_ForbiddenFlags(), and MapInfo_RequiredFlags().
Referenced by GotoMap(), and MapVote_Suggest().
 {
     if ( autocvar_sv_vote_gametype )
     {
         MapInfo_Enumerate();
         _MapInfo_FilterGametype(GameTypeVote_GetMask(), 0, MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
     }
     return MapInfo_FixName(m);
 }
void GameTypeVote_SendOption (int i)
Definition at line 318 of file mapvoting.qc.
References cvar_string(), GTV_AVAILABLE, GTV_CUSTOM, mapvote_abstain, mapvote_count, mapvote_maps, mapvote_maps_flags, strcat(), WriteByte(), and WriteString().
Referenced by MapVote_SendEntity().
 {
     // abstain
     if(mapvote_abstain && i == mapvote_count - 1)
     {
         WriteString(MSG_ENTITY, ""); // abstain needs no text
         WriteByte(MSG_ENTITY, GTV_AVAILABLE);
     }
     else
     {
         string type_name = mapvote_maps[i];
         WriteString(MSG_ENTITY, type_name);
         WriteByte(MSG_ENTITY, mapvote_maps_flags[i]);
         if ( mapvote_maps_flags[i] & GTV_CUSTOM )
         {
             WriteString(MSG_ENTITY, cvar_string(
                 strcat("sv_vote_gametype_",type_name,"_name")));
             WriteString(MSG_ENTITY, cvar_string(
                 strcat("sv_vote_gametype_",type_name,"_description")));
             WriteString(MSG_ENTITY, cvar_string(
                 strcat("sv_vote_gametype_",type_name,"_type")));
         }
     }
 }
bool GameTypeVote_SetGametype (Gametype type)
Definition at line 693 of file mapvoting.qc.
References autocvar_g_maplist_shuffle, bprint(), cvar_set(), getlsmaps(), MapInfo_count, MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_ListAllowedMaps(), MapInfo_RequiredFlags(), MapInfo_SwitchGameType(), MapInfo_Type_ToString(), ShuffleMaplist(), strunzone(), and strzone().
Referenced by GameTypeVote_Finished().
 {
     if (MapInfo_CurrentGametype() == type)
         return true;
     Gametype tsave = MapInfo_CurrentGametype();
     MapInfo_SwitchGameType(type);
     MapInfo_Enumerate();
     MapInfo_FilterGametype(type, MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
     if(MapInfo_count > 0)
     {
         // update lsmaps in case the gametype changed, this way people can easily list maps for it
         if(lsmaps_reply != "") { strunzone(lsmaps_reply); }
         lsmaps_reply = strzone(getlsmaps());
         bprint("Game type successfully switched to ", MapInfo_Type_ToString(type), "\n");
     }
     else
     {
         bprint("Cannot use this game type: no map for it found\n");
         MapInfo_SwitchGameType(tsave);
         MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
         return false;
     }
     //localcmd("gametype ", MapInfo_Type_ToString(type), "\n");
     cvar_set("g_maplist", MapInfo_ListAllowedMaps(type, MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags()) );
     if(autocvar_g_maplist_shuffle)
         ShuffleMaplist();
     return true;
 }
bool GameTypeVote_Start ()
Definition at line 769 of file mapvoting.qc.
References argv(), autocvar_g_maplist_votable_nodetail, autocvar_sv_vote_gametype_keeptwotime, autocvar_sv_vote_gametype_options, autocvar_sv_vote_gametype_timeout, gametypevote, GameTypeVote_AddVotable(), GTV_AVAILABLE, MapInfo_CurrentGametype(), MapInfo_Type_ToString(), mapvote_abstain, MapVote_ClearAllVotes(), mapvote_count, MAPVOTE_COUNT, mapvote_count_real, mapvote_detail, MapVote_Finished(), mapvote_keeptwotime, mapvote_maps, mapvote_maps_flags, MapVote_Spawn(), mapvote_timeout, MapVote_UnzoneStrings(), min(), strunzone(), strzone(), time, and tokenizebyseparator.
Referenced by MapVote_Think().
 {
     MapVote_ClearAllVotes();
     MapVote_UnzoneStrings();
     mapvote_count = 0;
     mapvote_timeout = time + autocvar_sv_vote_gametype_timeout;
     mapvote_abstain = false;
     mapvote_detail = !autocvar_g_maplist_votable_nodetail;
     int n = tokenizebyseparator(autocvar_sv_vote_gametype_options, " ");
     n = min(MAPVOTE_COUNT, n);
     int really_available, which_available;
     really_available = 0;
     which_available = -1;
     for(int j = 0; j < n; ++j)
     {
         if ( GameTypeVote_AddVotable(argv(j)) )
         if ( mapvote_maps_flags[j] & GTV_AVAILABLE )
         {
             really_available++;
             which_available = j;
         }
     }
     mapvote_count_real = mapvote_count;
     gametypevote = 1;
     if ( really_available == 0 )
     {
         if ( mapvote_count > 0 )
             strunzone(mapvote_maps[0]);
         mapvote_maps[0] = strzone(MapInfo_Type_ToString(MapInfo_CurrentGametype()));
         //GameTypeVote_Finished(0);
         MapVote_Finished(0);
         return false;
     }
     if ( really_available == 1 )
     {
         //GameTypeVote_Finished(which_available);
         MapVote_Finished(which_available);
         return false;
     }
     mapvote_count_real = mapvote_count;
     mapvote_keeptwotime = time + autocvar_sv_vote_gametype_keeptwotime;
     if(mapvote_count_real < 3 || mapvote_keeptwotime <= time)
         mapvote_keeptwotime = 0;
     MapVote_Spawn();
     return true;
 }
Gametype GameTypeVote_Type_FromString (string type_name)
Returns the gamtype ID from its name, if type_name isn't a real gametype it checks for sv_vote_gametype_(type_name)_type.
Definition at line 44 of file mapvoting.qc.
References cvar_string(), MapInfo_Type_FromString(), NULL, and strcat().
Referenced by GameTypeVote_AddVotable(), GameTypeVote_Finished(), and GameTypeVote_GetMask().
 {
     Gametype type = MapInfo_Type_FromString(type_name);
     if (type == NULL)
         type = MapInfo_Type_FromString(cvar_string(
             strcat("sv_vote_gametype_",type_name,"_type")));
     return type;
 }
void MapVote_AddVotable (string nextMap, bool isSuggestion)
Definition at line 162 of file mapvoting.qc.
References GTV_AVAILABLE, MapInfo_CheckMap(), mapvote_count, mapvote_maps, mapvote_maps_flags, mapvote_maps_pakfile, mapvote_maps_screenshot_dir, mapvote_maps_suggested, mapvote_screenshot_dirs, mapvote_screenshot_dirs_count, strcat(), string_null, strstrofs, strzone(), and substring().
Referenced by MapVote_Init().
 {
     int j, i, o;
     string pakfile, mapfile;
     if(nextMap == "")
         return;
     for(j = 0; j < mapvote_count; ++j)
         if(mapvote_maps[j] == nextMap)
             return;
     // suggestions might be no longer valid/allowed after gametype switch!
     if(isSuggestion)
         if(!MapInfo_CheckMap(nextMap))
             return;
     mapvote_maps[mapvote_count] = strzone(nextMap);
     mapvote_maps_suggested[mapvote_count] = isSuggestion;
     pakfile = string_null;
     for(i = 0; i < mapvote_screenshot_dirs_count; ++i)
     {
         mapfile = strcat(mapvote_screenshot_dirs[i], "/", nextMap);
         pakfile = whichpack(strcat(mapfile, ".tga"));
         if(pakfile == "")
             pakfile = whichpack(strcat(mapfile, ".jpg"));
         if(pakfile == "")
             pakfile = whichpack(strcat(mapfile, ".png"));
         if(pakfile != "")
             break;
     }
     if(i >= mapvote_screenshot_dirs_count)
         i = 0; // FIXME maybe network this error case, as that means there is no mapshot on the server?
     for(o = strstrofs(pakfile, "/", 0)+1; o > 0; o = strstrofs(pakfile, "/", 0)+1)
         pakfile = substring(pakfile, o, -1);
     mapvote_maps_screenshot_dir[mapvote_count] = i;
     mapvote_maps_pakfile[mapvote_count] = strzone(pakfile);
     mapvote_maps_flags[mapvote_count] = GTV_AVAILABLE;
     mapvote_count += 1;
 }
void MapVote_CheckRules_1 ()
Definition at line 483 of file mapvoting.qc.
References FOREACH_CLIENT, GTV_AVAILABLE, IS_REAL_CLIENT, mapvote_count, mapvote_maps_flags, mapvote_selections, and mapvote_voters.
Referenced by MapVote_Tick().
 {
     for (int i = 0; i < mapvote_count; ++i)
         if (mapvote_maps_flags[i] & GTV_AVAILABLE)
         {
             //dprint("Map ", ftos(i), ": "); dprint(mapvote_maps[i], "\n");
             mapvote_selections[i] = 0;
         }
     mapvote_voters = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         ++mapvote_voters;
         if (it.mapvote)
         {
             int idx = it.mapvote - 1;
             //dprint("Player ", it.netname, " vote = ", ftos(idx), "\n");
             ++mapvote_selections[idx];
         }
     });
 }
bool MapVote_CheckRules_2 ()
Definition at line 504 of file mapvoting.qc.
References autocvar_sv_eventlog, autocvar_sv_vote_gametype_default_current, error, ftos(), GameLogEcho(), gametypevote, GTV_AVAILABLE, MapInfo_CurrentGametype(), MapInfo_Type_ToString(), mapvote_abstain, mapvote_count, mapvote_count_real, MapVote_Finished(), mapvote_keeptwotime, mapvote_maps, mapvote_maps_flags, mapvote_selections, mapvote_timeout, MapVote_TouchMask(), mapvote_voters, RandomSelection_AddFloat, RandomSelection_best_priority, RandomSelection_chosen_float, RandomSelection_Init(), strcat(), and time.
Referenced by MapVote_Tick().
 {
     int i;
     int firstPlace, secondPlace, currentPlace;
     int firstPlaceVotes, secondPlaceVotes, currentVotes;
     int mapvote_voters_real;
     string result;
     if(mapvote_count_real == 1)
         return MapVote_Finished(0);
     mapvote_voters_real = mapvote_voters;
     if(mapvote_abstain)
         mapvote_voters_real -= mapvote_selections[mapvote_count - 1];
     RandomSelection_Init();
     currentPlace = 0;
     currentVotes = -1;
     for(i = 0; i < mapvote_count_real; ++i)
         if ( mapvote_maps_flags[i] & GTV_AVAILABLE )
         {
             RandomSelection_AddFloat(i, 1, mapvote_selections[i]);
             if ( gametypevote &&  mapvote_maps[i] == MapInfo_Type_ToString(MapInfo_CurrentGametype()) )
             {
                 currentVotes = mapvote_selections[i];
                 currentPlace = i;
             }
         }
     firstPlaceVotes = RandomSelection_best_priority;
     if ( autocvar_sv_vote_gametype_default_current && currentVotes == firstPlaceVotes )
         firstPlace = currentPlace;
     else
         firstPlace = RandomSelection_chosen_float;
     //dprint("First place: ", ftos(firstPlace), "\n");
     //dprint("First place votes: ", ftos(firstPlaceVotes), "\n");
     RandomSelection_Init();
     for(i = 0; i < mapvote_count_real; ++i)
         if(i != firstPlace)
         if ( mapvote_maps_flags[i] & GTV_AVAILABLE )
             RandomSelection_AddFloat(i, 1, mapvote_selections[i]);
     secondPlace = RandomSelection_chosen_float;
     secondPlaceVotes = RandomSelection_best_priority;
     //dprint("Second place: ", ftos(secondPlace), "\n");
     //dprint("Second place votes: ", ftos(secondPlaceVotes), "\n");
     if(firstPlace == -1)
         error("No first place in map vote... WTF?");
     if(secondPlace == -1 || time > mapvote_timeout || (mapvote_voters_real - firstPlaceVotes) < firstPlaceVotes)
         return MapVote_Finished(firstPlace);
     if(mapvote_keeptwotime)
         if(time > mapvote_keeptwotime || (mapvote_voters_real - firstPlaceVotes - secondPlaceVotes) < secondPlaceVotes)
         {
             MapVote_TouchMask();
             mapvote_keeptwotime = 0;
             result = strcat(":vote:keeptwo:", mapvote_maps[firstPlace]);
             result = strcat(result, ":", ftos(firstPlaceVotes));
             result = strcat(result, ":", mapvote_maps[secondPlace]);
             result = strcat(result, ":", ftos(secondPlaceVotes), "::");
             int didntvote = mapvote_voters;
             for(i = 0; i < mapvote_count; ++i)
             {
                 didntvote -= mapvote_selections[i];
                 if(i != firstPlace)
                     if(i != secondPlace)
                     {
                         result = strcat(result, ":", mapvote_maps[i]);
                         result = strcat(result, ":", ftos(mapvote_selections[i]));
                         if(i < mapvote_count_real)
{
                             mapvote_maps_flags[i] &= ~GTV_AVAILABLE;
                         }
                     }
             }
             result = strcat(result, ":didn't vote:", ftos(didntvote));
             if(autocvar_sv_eventlog)
                 GameLogEcho(result);
         }
     return false;
 }
void MapVote_ClearAllVotes ()
Definition at line 100 of file mapvoting.qc.
References FOREACH_CLIENT, and LAMBDA.
Referenced by GameTypeVote_Start(), and MapVote_Init().
 {
     FOREACH_CLIENT(true, LAMBDA(it.mapvote = 0));
 }
bool MapVote_Finished (int mappos)
Definition at line 425 of file mapvoting.qc.
References alreadychangedlevel, autocvar_nextmap, autocvar_sv_eventlog, FixClientCvars(), FOREACH_CLIENT, ftos(), GameLogEcho(), gametypevote, GameTypeVote_Finished(), GTV_AVAILABLE, IS_REAL_CLIENT, LAMBDA, Map_Goto(), Map_Goto_SetStr(), mapvote_count, MapVote_Init(), mapvote_maps, mapvote_maps_flags, mapvote_maps_suggested, mapvote_selections, mapvote_voters, and strcat().
Referenced by GameTypeVote_Start(), and MapVote_CheckRules_2().
 {
     if(alreadychangedlevel)
         return false;
     string result;
     int i;
     int didntvote;
     if(autocvar_sv_eventlog)
     {
         result = strcat(":vote:finished:", mapvote_maps[mappos]);
         result = strcat(result, ":", ftos(mapvote_selections[mappos]), "::");
         didntvote = mapvote_voters;
         for(i = 0; i < mapvote_count; ++i)
             if(mapvote_maps_flags[i] & GTV_AVAILABLE )
             {
                 didntvote -= mapvote_selections[i];
                 if(i != mappos)
                 {
                     result = strcat(result, ":", mapvote_maps[i]);
                     result = strcat(result, ":", ftos(mapvote_selections[i]));
                 }
             }
         result = strcat(result, ":didn't vote:", ftos(didntvote));
         GameLogEcho(result);
         if(mapvote_maps_suggested[mappos])
             GameLogEcho(strcat(":vote:suggestion_accepted:", mapvote_maps[mappos]));
     }
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(FixClientCvars(it)));
     if(gametypevote)
     {
         if ( GameTypeVote_Finished(mappos) )
         {
             gametypevote = false;
             if(autocvar_nextmap != "")
             {
                 Map_Goto_SetStr(autocvar_nextmap);
                 Map_Goto(0);
                 alreadychangedlevel = true;
                 return true;
             }
             else
                 MapVote_Init();
         }
         return false;
     }
     Map_Goto_SetStr(mapvote_maps[mappos]);
     Map_Goto(0);
     alreadychangedlevel = true;
     return true;
 }
void MapVote_Init ()
Definition at line 203 of file mapvoting.qc.
References argv(), autocvar_g_maplist_shuffle, autocvar_g_maplist_votable, autocvar_g_maplist_votable_abstain, autocvar_g_maplist_votable_keeptwotime, autocvar_g_maplist_votable_nodetail, autocvar_g_maplist_votable_screenshot_dir, autocvar_g_maplist_votable_suggestions, autocvar_g_maplist_votable_timeout, boolean, bprint(), cvar_set(), floor(), GetNextMap(), localcmd, MapInfo_CurrentGametype(), MapInfo_ForbiddenFlags(), MapInfo_ListAllowedMaps(), MapInfo_RequiredFlags(), mapvote_abstain, MapVote_AddVotable(), MapVote_ClearAllVotes(), mapvote_count, MAPVOTE_COUNT, mapvote_count_real, mapvote_detail, mapvote_keeptwotime, mapvote_screenshot_dirs, MAPVOTE_SCREENSHOT_DIRS_COUNT, mapvote_screenshot_dirs_count, MapVote_Spawn(), mapvote_suggestion_ptr, mapvote_suggestions, mapvote_timeout, MapVote_UnzoneStrings(), min(), random(), ShuffleMaplist(), strzone(), time, and tokenize_console.
 {
     int i;
     int nmax, smax;
     MapVote_ClearAllVotes();
     MapVote_UnzoneStrings();
     mapvote_count = 0;
     mapvote_detail = !autocvar_g_maplist_votable_nodetail;
     mapvote_abstain = boolean(autocvar_g_maplist_votable_abstain);
     if(mapvote_abstain)
         nmax = min(MAPVOTE_COUNT - 1, autocvar_g_maplist_votable);
     else
         nmax = min(MAPVOTE_COUNT, autocvar_g_maplist_votable);
     smax = min3(nmax, autocvar_g_maplist_votable_suggestions, mapvote_suggestion_ptr);
     // we need this for AddVotable, as that cycles through the screenshot dirs
     mapvote_screenshot_dirs_count = tokenize_console(autocvar_g_maplist_votable_screenshot_dir);
     if(mapvote_screenshot_dirs_count == 0)
         mapvote_screenshot_dirs_count = tokenize_console("maps levelshots");
     mapvote_screenshot_dirs_count = min(mapvote_screenshot_dirs_count, MAPVOTE_SCREENSHOT_DIRS_COUNT);
     for(i = 0; i < mapvote_screenshot_dirs_count; ++i)
         mapvote_screenshot_dirs[i] = strzone(argv(i));
     if(mapvote_suggestion_ptr)
         for(i = 0; i < 100 && mapvote_count < smax; ++i)
             MapVote_AddVotable(mapvote_suggestions[floor(random() * mapvote_suggestion_ptr)], true);
     for(i = 0; i < 100 && mapvote_count < nmax; ++i)
         MapVote_AddVotable(GetNextMap(), false);
     if(mapvote_count == 0)
     {
         bprint( "Maplist contains no single playable map!  Resetting it to default map list.\n" );
         cvar_set("g_maplist", MapInfo_ListAllowedMaps(MapInfo_CurrentGametype(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags()));
         if(autocvar_g_maplist_shuffle)
             ShuffleMaplist();
         localcmd("\nmenu_cmd sync\n");
         for(i = 0; i < 100 && mapvote_count < nmax; ++i)
             MapVote_AddVotable(GetNextMap(), false);
     }
     mapvote_count_real = mapvote_count;
     if(mapvote_abstain)
         MapVote_AddVotable("don't care", false);
     //dprint("mapvote count is ", ftos(mapvote_count), "\n");
     mapvote_keeptwotime = time + autocvar_g_maplist_votable_keeptwotime;
     mapvote_timeout = time + autocvar_g_maplist_votable_timeout;
     if(mapvote_count_real < 3 || mapvote_keeptwotime <= time)
         mapvote_keeptwotime = 0;
     MapVote_Spawn();
 }
bool MapVote_SendEntity (entity this, entity to, int sf)
Definition at line 343 of file mapvoting.qc.
References autocvar_nextmap, autocvar_sv_vote_gametype, gametypevote, GameTypeVote_SendOption(), GTV_AVAILABLE, MapInfo_CurrentGametype(), MapInfo_Type_ToText(), mapvote_abstain, mapvote_count, mapvote_detail, mapvote_maps_flags, mapvote_screenshot_dirs, mapvote_screenshot_dirs_count, mapvote_selections, MapVote_SendOption(), mapvote_timeout, MapVote_WriteMask(), WriteByte(), WriteCoord(), and WriteString().
Referenced by MapVote_Spawn().
 {
     int i;
     if(sf & 1)
         sf &= ~2; // if we send 1, we don't need to also send 2
     WriteHeader(MSG_ENTITY, ENT_CLIENT_MAPVOTE);
     WriteByte(MSG_ENTITY, sf);
     if(sf & 1)
     {
         // flag 1 == initialization
         for(i = 0; i < mapvote_screenshot_dirs_count; ++i)
             WriteString(MSG_ENTITY, mapvote_screenshot_dirs[i]);
         WriteString(MSG_ENTITY, "");
         WriteByte(MSG_ENTITY, mapvote_count);
         WriteByte(MSG_ENTITY, mapvote_abstain);
         WriteByte(MSG_ENTITY, mapvote_detail);
         WriteCoord(MSG_ENTITY, mapvote_timeout);
         if ( gametypevote )
         {
             // gametype vote
             WriteByte(MSG_ENTITY, 1);
             WriteString(MSG_ENTITY, autocvar_nextmap);
         }
         else if ( autocvar_sv_vote_gametype )
         {
             // map vote but gametype has been chosen via voting screen
             WriteByte(MSG_ENTITY, 2);
             WriteString(MSG_ENTITY, MapInfo_Type_ToText(MapInfo_CurrentGametype()));
         }
         else
             WriteByte(MSG_ENTITY, 0); // map vote
         MapVote_WriteMask();
         // Send data for the vote options
         for(i = 0; i < mapvote_count; ++i)
         {
             if(gametypevote)
                 GameTypeVote_SendOption(i);
             else
                 MapVote_SendOption(i);
         }
     }
     if(sf & 2)
     {
         // flag 2 == update of mask
         MapVote_WriteMask();
     }
     if(sf & 4)
     {
         if(mapvote_detail)
             for(i = 0; i < mapvote_count; ++i)
                 if ( mapvote_maps_flags[i] & GTV_AVAILABLE )
                     WriteByte(MSG_ENTITY, mapvote_selections[i]);
         WriteByte(MSG_ENTITY, to.mapvote);
     }
     return true;
 }
void MapVote_SendOption (int i)
Definition at line 298 of file mapvoting.qc.
References mapvote_abstain, mapvote_count, mapvote_maps, mapvote_maps_pakfile, mapvote_maps_screenshot_dir, WriteByte(), and WriteString().
Referenced by MapVote_SendEntity().
 {
     // abstain
     if(mapvote_abstain && i == mapvote_count - 1)
     {
         WriteString(MSG_ENTITY, ""); // abstain needs no text
         WriteString(MSG_ENTITY, ""); // abstain needs no pack
         WriteByte(MSG_ENTITY, 0); // abstain needs no screenshot dir
     }
     else
     {
         WriteString(MSG_ENTITY, mapvote_maps[i]);
         WriteString(MSG_ENTITY, mapvote_maps_pakfile[i]);
         WriteByte(MSG_ENTITY, mapvote_maps_screenshot_dir[i]);
     }
 }
void MapVote_SendPicture (entity to, int id)
Definition at line 261 of file mapvoting.qc.
References mapvote_maps, mapvote_maps_screenshot_dir, mapvote_screenshot_dirs, msg_entity, MSG_ONE, strcat(), to, and WriteByte().
Referenced by ClientCommand_mv_getpicture().
 {
     msg_entity = to;
     WriteHeader(MSG_ONE, TE_CSQC_PICTURE);
     WriteByte(MSG_ONE, id);
     WritePicture(MSG_ONE, strcat(mapvote_screenshot_dirs[mapvote_maps_screenshot_dir[id]], "/", mapvote_maps[id]), 3072);
 }
void MapVote_Spawn ()
Definition at line 410 of file mapvoting.qc.
References mapvote_ent, MapVote_SendEntity(), and spawn().
Referenced by GameTypeVote_Start(), and MapVote_Init().
 {
     Net_LinkEntity(mapvote_ent = spawn(), false, 0, MapVote_SendEntity);
 }
void MapVote_Start ()
Definition at line 628 of file mapvoting.qc.
References MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), and mapvote_run.
Referenced by CheckRules_World(), and IntermissionThink().
 {
     // if mapvote is already running, don't do this initialization again
     if(mapvote_run) { return; }
     // don't start mapvote until after playerstats gamereport is sent
     if(PlayerStats_GameReport_DelayMapVote) { return; }
     MapInfo_Enumerate();
     if(MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1))
         mapvote_run = true;
 }
string MapVote_Suggest (entity this, string m)
Definition at line 122 of file mapvoting.qc.
References autocvar_g_maplist_votable_suggestions, autocvar_g_maplist_votable_suggestions_override_mostrecent, autocvar_sv_eventlog, autocvar_sv_vote_gametype, floor(), ftos(), GameLogEcho(), gametypevote, GameTypeVote_MapInfo_FixName(), Map_IsRecent(), MapInfo_CheckMap(), MAPVOTE_COUNT, mapvote_initialized, mapvote_suggestion_ptr, mapvote_suggestions, playerid, random(), strcat(), strunzone(), and strzone().
Referenced by ClientCommand_suggestmap().
 {
     int i;
     if(m == "")
         return "That's not how to use this command.";
     if(!autocvar_g_maplist_votable_suggestions)
         return "Suggestions are not accepted on this server.";
     if(mapvote_initialized)
     if(!gametypevote)
         return "Can't suggest - voting is already in progress!";
     m = GameTypeVote_MapInfo_FixName(m);
     if (!m)
         return "The map you suggested is not available on this server.";
     if(!autocvar_g_maplist_votable_suggestions_override_mostrecent)
         if(Map_IsRecent(m))
             return "This server does not allow for recent maps to be played again. Please be patient for some rounds.";
     if (!autocvar_sv_vote_gametype)
     if(!MapInfo_CheckMap(m))
         return "The map you suggested does not support the current game mode.";
     for(i = 0; i < mapvote_suggestion_ptr; ++i)
         if(mapvote_suggestions[i] == m)
             return "This map was already suggested.";
     if(mapvote_suggestion_ptr >= MAPVOTE_COUNT)
     {
         i = floor(random() * mapvote_suggestion_ptr);
     }
     else
     {
         i = mapvote_suggestion_ptr;
         mapvote_suggestion_ptr += 1;
     }
     if(mapvote_suggestions[i] != "")
         strunzone(mapvote_suggestions[i]);
     mapvote_suggestions[i] = strzone(m);
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":vote:suggested:", m, ":", ftos(this.playerid)));
     return strcat("Suggestion of ", m, " accepted.");
 }
void MapVote_Think ()
Definition at line 641 of file mapvoting.qc.
References alreadychangedlevel, autocvar_g_maplist_votable, autocvar_nextmap, autocvar_rescan_pending, autocvar_sv_vote_gametype, cvar_set(), DoNextMapOverride(), GameTypeVote_Start(), GotoNextMap(), localcmd, MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), MapVote_Init(), mapvote_initialized, mapvote_nextthink, mapvote_run, MapVote_Tick(), player_count, and time.
Referenced by CheckRules_World().
 {
     if(!mapvote_run)
         return;
     if(alreadychangedlevel)
         return;
     if(time < mapvote_nextthink)
         return;
     //dprint("tick\n");
     mapvote_nextthink = time + 0.5;
     if(!mapvote_initialized)
     {
         if(autocvar_rescan_pending == 1)
         {
             cvar_set("rescan_pending", "2");
             localcmd("fs_rescan\nrescan_pending 3\n");
             return;
         }
         else if(autocvar_rescan_pending == 2)
         {
             return;
         }
         else if(autocvar_rescan_pending == 3)
         {
             // now build missing mapinfo files
             if(!MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1))
                 return;
             // we're done, start the timer
             cvar_set("rescan_pending", "0");
         }
         mapvote_initialized = true;
         if(DoNextMapOverride(0))
             return;
         if(!autocvar_g_maplist_votable || player_count <= 0)
         {
             GotoNextMap(0);
             return;
         }
         if(autocvar_sv_vote_gametype) { GameTypeVote_Start(); }
         else if(autocvar_nextmap == "") { MapVote_Init(); }
     }
     MapVote_Tick();
 }
void MapVote_Tick ()
Definition at line 589 of file mapvoting.qc.
References FOREACH_CLIENT, IS_REAL_CLIENT, LAMBDA, MapVote_CheckRules_1(), MapVote_CheckRules_2(), msg_entity, MSG_ONE, SVC_FINALE, WriteByte(), and WriteString().
Referenced by MapVote_Think().
 {
     MapVote_CheckRules_1(); // count
     if(MapVote_CheckRules_2()) // decide
         return;
     int totalvotes = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(
         // hide scoreboard again
         if(it.health != 2342)
         {
             it.health = 2342;
             it.impulse = 0;
             msg_entity = it;
             WriteByte(MSG_ONE, SVC_FINALE);
             WriteString(MSG_ONE, "");
         }
         // clear possibly invalid votes
         if ( !(mapvote_maps_flags[it.mapvote-1] & GTV_AVAILABLE) )
             it.mapvote = 0;
         // use impulses as new vote
         if(it.impulse >= 1 && it.impulse <= mapvote_count)
             if( mapvote_maps_flags[it.impulse - 1] & GTV_AVAILABLE )
             {
                 it.mapvote = it.impulse;
                 MapVote_TouchVotes(it);
             }
         it.impulse = 0;
         if(it.mapvote)
             ++totalvotes;
     ));
     MapVote_CheckRules_1(); // just count
 }
void MapVote_TouchMask ()
Definition at line 415 of file mapvoting.qc.
References mapvote_ent.
Referenced by MapVote_CheckRules_2().
 {
     mapvote_ent.SendFlags |= 2;
 }
void MapVote_TouchVotes (entity voter)
Definition at line 420 of file mapvoting.qc.
References mapvote_ent.
 {
     mapvote_ent.SendFlags |= 4;
 }
void MapVote_UnzoneStrings ()
Definition at line 105 of file mapvoting.qc.
References mapvote_count, mapvote_maps, mapvote_maps_pakfile, string_null, and strunzone().
Referenced by GameTypeVote_Start(), and MapVote_Init().
 {
     for(int j = 0; j < mapvote_count; ++j)
     {
         if ( mapvote_maps[j] )
         {
             strunzone(mapvote_maps[j]);
             mapvote_maps[j] = string_null;
         }
         if ( mapvote_maps_pakfile[j] )
         {
             strunzone(mapvote_maps_pakfile[j]);
             mapvote_maps_pakfile[j] = string_null;
         }
     }
 }
void MapVote_WriteMask ()
Definition at line 270 of file mapvoting.qc.
References BIT, GTV_AVAILABLE, mapvote_count, mapvote_maps_flags, WriteByte(), WriteLong(), and WriteShort().
Referenced by MapVote_SendEntity().
 {
     if ( mapvote_count < 24 )
     {
         int mask = 0;
         for(int j = 0; j < mapvote_count; ++j)
         {
             if(mapvote_maps_flags[j] & GTV_AVAILABLE)
                 mask |= BIT(j);
         }
         if(mapvote_count < 8)
             WriteByte(MSG_ENTITY, mask);
         else if (mapvote_count < 16)
             WriteShort(MSG_ENTITY,mask);
         else
             WriteLong(MSG_ENTITY, mask);
     }
     else
     {
         for (int j = 0; j < mapvote_count; ++j)
             WriteByte(MSG_ENTITY, mapvote_maps_flags[j]);
     }
 }
Variable Documentation
bool gametypevote_finished
Definition at line 728 of file mapvoting.qc.
int mapvote
Definition at line 36 of file mapvoting.qc.
bool mapvote_abstain
Definition at line 35 of file mapvoting.qc.
Referenced by GameTypeVote_SendOption(), GameTypeVote_Start(), MapVote_CheckRules_2(), MapVote_Init(), MapVote_SendEntity(), and MapVote_SendOption().
int mapvote_count
Definition at line 22 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), GameTypeVote_SendOption(), GameTypeVote_Start(), MapVote_AddVotable(), MapVote_CheckRules_1(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_Init(), MapVote_SendEntity(), MapVote_SendOption(), MapVote_UnzoneStrings(), and MapVote_WriteMask().
int mapvote_count_real
Definition at line 23 of file mapvoting.qc.
Referenced by GameTypeVote_Start(), MapVote_CheckRules_2(), and MapVote_Init().
bool mapvote_detail
Definition at line 34 of file mapvoting.qc.
Referenced by GameTypeVote_Start(), MapVote_Init(), and MapVote_SendEntity().
entity mapvote_ent
Definition at line 38 of file mapvoting.qc.
Referenced by MapVote_Spawn(), MapVote_TouchMask(), and MapVote_TouchVotes().
float mapvote_keeptwotime
Definition at line 16 of file mapvoting.qc.
Referenced by GameTypeVote_Start(), MapVote_CheckRules_2(), and MapVote_Init().
string mapvote_maps[MAPVOTE_COUNT]
Definition at line 24 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), GameTypeVote_Finished(), GameTypeVote_SendOption(), GameTypeVote_Start(), MapVote_AddVotable(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_SendOption(), MapVote_SendPicture(), and MapVote_UnzoneStrings().
int mapvote_maps_flags[MAPVOTE_COUNT]
Definition at line 32 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), GameTypeVote_SendOption(), GameTypeVote_Start(), MapVote_AddVotable(), MapVote_CheckRules_1(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_SendEntity(), and MapVote_WriteMask().
string mapvote_maps_pakfile[MAPVOTE_COUNT]
Definition at line 26 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), MapVote_AddVotable(), MapVote_SendOption(), and MapVote_UnzoneStrings().
int mapvote_maps_screenshot_dir[MAPVOTE_COUNT]
Definition at line 25 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), MapVote_AddVotable(), MapVote_SendOption(), and MapVote_SendPicture().
bool mapvote_maps_suggested[MAPVOTE_COUNT]
Definition at line 27 of file mapvoting.qc.
Referenced by GameTypeVote_AddVotable(), MapVote_AddVotable(), and MapVote_Finished().
float mapvote_nextthink
Definition at line 15 of file mapvoting.qc.
Referenced by MapVote_Think().
bool mapvote_run
Definition at line 33 of file mapvoting.qc.
Referenced by MapVote_Start(), and MapVote_Think().
string mapvote_screenshot_dirs[MAPVOTE_SCREENSHOT_DIRS_COUNT]
Definition at line 19 of file mapvoting.qc.
Referenced by MapVote_AddVotable(), MapVote_Init(), MapVote_SendEntity(), and MapVote_SendPicture().
const int MAPVOTE_SCREENSHOT_DIRS_COUNT = 4
Definition at line 18 of file mapvoting.qc.
Referenced by MapVote_Init().
int mapvote_screenshot_dirs_count
Definition at line 20 of file mapvoting.qc.
Referenced by MapVote_AddVotable(), MapVote_Init(), and MapVote_SendEntity().
int mapvote_selections[MAPVOTE_COUNT]
Definition at line 31 of file mapvoting.qc.
Referenced by MapVote_CheckRules_1(), MapVote_CheckRules_2(), MapVote_Finished(), and MapVote_SendEntity().
int mapvote_suggestion_ptr
Definition at line 29 of file mapvoting.qc.
Referenced by MapVote_Init(), and MapVote_Suggest().
string mapvote_suggestions[MAPVOTE_COUNT]
Definition at line 28 of file mapvoting.qc.
Referenced by MapVote_Init(), and MapVote_Suggest().
float mapvote_timeout
Definition at line 17 of file mapvoting.qc.
Referenced by GameTypeVote_Start(), MapVote_CheckRules_2(), MapVote_Init(), and MapVote_SendEntity().
int mapvote_voters
Definition at line 30 of file mapvoting.qc.
Referenced by MapVote_CheckRules_1(), MapVote_CheckRules_2(), and MapVote_Finished().