Xonotic: MainWindow Class Reference
MainWindow Class Reference
Public Member Functions
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
virtual void addTab ()
ATTRIB (MainWindow, firstRunDialog, entity)
ATTRIB (MainWindow, advancedDialog, entity)
ATTRIB (MainWindow, mutatorsDialog, entity)
ATTRIB (MainWindow, mapInfoDialog, entity)
ATTRIB (MainWindow, userbindEditDialog, entity)
ATTRIB (MainWindow, winnerDialog, entity)
ATTRIB (MainWindow, serverInfoDialog, entity)
ATTRIB (MainWindow, cvarsDialog, entity)
ATTRIB (MainWindow, screenshotViewerDialog, entity)
ATTRIB (MainWindow, viewDialog, entity)
ATTRIB (MainWindow, hudconfirmDialog, entity)
ATTRIB (MainWindow, languageWarningDialog, entity)
ATTRIB (MainWindow, mainNexposee, entity)
ATTRIB (MainWindow, dialogToShow, entity)
ATTRIB (MainWindow, demostartconfirmDialog, entity)
ATTRIB (MainWindow, demotimeconfirmDialog, entity)
ATTRIB (Item, parent, entity)
ATTRIB (MainWindow, resetDialog, entity)
ATTRIB (Item, tooltip, string)
ATTRIB (Container, firstChild, entity)
ATTRIB (Container, lastChild, entity)
ATTRIB (Container, focusedChild, entity)
ATTRIB (Container, savedFocus, entity)
ATTRIB (ModalController, previousButton, entity)
virtual void configureMainWindow ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideAll ()
virtual void hideChild ()
virtual void hideNotify ()
virtual void initializeDialog ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFocus ()
virtual void showChild ()
virtual void showNotify ()
virtual void switchState ()
virtual void toString ()
Public Attributes
float allowFocusSound = 0
float fadedAlpha = SKINALPHA_BEHIND
float focusable = 0
float focused = 0
vector origin = '0 0 0'
float preferredFocusPriority = 0
float shown = 0
vector size = '0 0 0'
Detailed Description
Definition at line 5 of file mainwindow.qh.
Member Function Documentation
virtual void ModalController::addItem () virtual inherited
Reimplemented from Container.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
virtual void ModalController::addTab () virtual inherited
MainWindow::ATTRIB (MainWindow , firstRunDialog , entity)
MainWindow::ATTRIB (MainWindow , advancedDialog , entity)
MainWindow::ATTRIB (MainWindow , mutatorsDialog , entity)
MainWindow::ATTRIB (MainWindow , mapInfoDialog , entity)
MainWindow::ATTRIB (MainWindow , userbindEditDialog , entity)
MainWindow::ATTRIB (MainWindow , winnerDialog , entity)
MainWindow::ATTRIB (MainWindow , serverInfoDialog , entity)
MainWindow::ATTRIB (MainWindow , cvarsDialog , entity)
MainWindow::ATTRIB (MainWindow , screenshotViewerDialog , entity)
MainWindow::ATTRIB (MainWindow , viewDialog , entity)
MainWindow::ATTRIB (MainWindow , hudconfirmDialog , entity)
MainWindow::ATTRIB (MainWindow , languageWarningDialog , entity)
MainWindow::ATTRIB (MainWindow , mainNexposee , entity)
MainWindow::ATTRIB (MainWindow , dialogToShow , entity)
MainWindow::ATTRIB (MainWindow , demostartconfirmDialog , entity)
MainWindow::ATTRIB (MainWindow , demotimeconfirmDialog , entity)
Item::ATTRIB (Item , parent , entity) inherited
MainWindow::ATTRIB (MainWindow , resetDialog , entity)
Item::ATTRIB (Item , tooltip , string) inherited
Container::ATTRIB (Container , firstChild , entity) inherited
Container::ATTRIB (Container , lastChild , entity) inherited
Container::ATTRIB (Container , focusedChild , entity) inherited
Container::ATTRIB (Container , savedFocus , entity) inherited
ModalController::ATTRIB (ModalController , previousButton , entity) inherited
virtual void MainWindow::configureMainWindow () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void MainWindow::draw () virtual
Reimplemented from ModalController.
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void Container::focusLeave () virtual inherited
Reimplemented from Item.
Reimplemented in InputContainer.
virtual void ModalController::hideAll () virtual inherited
virtual void ModalController::hideChild () virtual inherited
virtual void Container::hideNotify () virtual inherited
Reimplemented from Item.
virtual void ModalController::initializeDialog () virtual inherited
virtual void Container::itemFromPoint () virtual inherited
virtual void Container::keyDown () virtual inherited
Reimplemented from Item.
Reimplemented in Dialog, XonoticScreenshotViewerDialog, Nexposee, and InputContainer.
virtual void Container::keyUp () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual inherited
virtual void Container::mouseDrag () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::mouseMove () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::mousePress () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::mouseRelease () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee, and InputContainer.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void ModalController::resizeNotify () virtual inherited
Reimplemented from Container.
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Container::setFocus () virtual inherited
virtual void ModalController::showChild () virtual inherited
virtual void Container::showNotify () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticDamageTextSettings, XonoticTab, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
virtual void ModalController::switchState () virtual inherited
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
Member Data Documentation
float Item::allowFocusSound = 0 inherited
Definition at line 24 of file item.qh.
float MainWindow::fadedAlpha = SKINALPHA_BEHIND
Definition at line 21 of file mainwindow.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
vector ModalController::origin = '0 0 0' inherited
Definition at line 37 of file modalcontroller.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector ModalController::size = '0 0 0' inherited
Definition at line 38 of file modalcontroller.qh.
The documentation for this class was generated from the following file:
menu/xonotic/mainwindow.qh