Xonotic: common/gamemodes/gamemode/freezetag/sv_freezetag.qh File Reference
sv_freezetag.qh File Reference
#include <common/mutators/base.qh>
#include <server/command/sv_cmd.qh>
Functions
void freezetag_Initialize ()
REGISTER_MUTATOR (ft, false)
Variables
int autocvar_g_freezetag_point_leadlimit
int autocvar_g_freezetag_point_limit
bool autocvar_g_freezetag_revive_auto = 1
int autocvar_g_freezetag_revive_auto_progress = 1
int autocvar_g_freezetag_revive_auto_reducible
float autocvar_g_freezetag_revive_auto_reducible_forcefactor = 0.01
float autocvar_g_freezetag_revive_auto_reducible_maxforce
float autocvar_g_freezetag_revive_extra_size
bool autocvar_g_freezetag_revive_nade
float autocvar_g_freezetag_revive_nade_health
float autocvar_g_freezetag_revive_spawnshield = 1
float autocvar_g_freezetag_revive_speed
float autocvar_g_freezetag_revive_speed_t2s = 0.25
float autocvar_g_freezetag_revive_time_to_score = 1.5
bool autocvar_g_freezetag_team_spawns
string autocvar_g_freezetag_weaponarena = "most_available"
float freezetag_frozen_force
float freezetag_frozen_time
float freezetag_frozen_timeout
float freezetag_revive_time
float freezetag_teams
const float ICE_MAX_ALPHA = 1
const float ICE_MIN_ALPHA = 0.1
const int ST_FT_ROUNDS = 1
Function Documentation
freezetag_Initialize()
void freezetag_Initialize ()
Definition at line 771 of file sv_freezetag.qc.
References autocvar_g_freezetag_round_timelimit, autocvar_g_freezetag_teams_override, autocvar_g_freezetag_warmup, BITS, bound(), cvar(), EliminatedPlayers_Init(), freezetag_CheckTeams(), freezetag_CheckWinner(), freezetag_isEliminated(), freezetag_teams, func_null(), GameRules_scoring, round_handler_Init(), round_handler_Spawn(), SFL_SORT_PRIO_PRIMARY, and ST_FT_ROUNDS.
Referenced by REGISTER_MUTATOR().
 {
     freezetag_teams = autocvar_g_freezetag_teams_override;
     if(freezetag_teams < 2)
         freezetag_teams = cvar("g_freezetag_teams"); // read the cvar directly as it gets written earlier in the same frame
     freezetag_teams = BITS(bound(2, freezetag_teams, 4));
     GameRules_scoring(freezetag_teams, SFL_SORT_PRIO_PRIMARY, 0, {
         field_team(ST_FT_ROUNDS, "rounds", SFL_SORT_PRIO_PRIMARY);
         field(SP_FREEZETAG_REVIVALS, "revivals", 0);
     });
     round_handler_Spawn(freezetag_CheckTeams, freezetag_CheckWinner, func_null);
     round_handler_Init(5, autocvar_g_freezetag_warmup, autocvar_g_freezetag_round_timelimit);
     EliminatedPlayers_Init(freezetag_isEliminated);
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (ft , false)
Definition at line 15 of file sv_freezetag.qh.
References autocvar_g_freezetag_point_leadlimit, autocvar_g_freezetag_point_limit, autocvar_g_freezetag_team_spawns, freezetag_Initialize(), GameRules_limit_lead(), GameRules_limit_score(), GameRules_spawning_teams(), GameRules_teams(), MUTATOR_ONADD, and MUTATOR_STATIC.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_teams(true);
         GameRules_spawning_teams(autocvar_g_freezetag_team_spawns);
         GameRules_limit_score(autocvar_g_freezetag_point_limit);
         GameRules_limit_lead(autocvar_g_freezetag_point_leadlimit);
         freezetag_Initialize();
     }
     return 0;
 }
Variable Documentation
autocvar_g_freezetag_point_leadlimit
int autocvar_g_freezetag_point_leadlimit
Definition at line 7 of file sv_freezetag.qh.
Referenced by REGISTER_MUTATOR().
autocvar_g_freezetag_point_limit
int autocvar_g_freezetag_point_limit
Definition at line 6 of file sv_freezetag.qh.
Referenced by REGISTER_MUTATOR().
autocvar_g_freezetag_revive_auto
bool autocvar_g_freezetag_revive_auto = 1
Definition at line 38 of file sv_freezetag.qh.
Referenced by freezetag_Freeze(), and MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_auto_progress
int autocvar_g_freezetag_revive_auto_progress = 1
Definition at line 39 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_auto_reducible
int autocvar_g_freezetag_revive_auto_reducible
Definition at line 40 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_auto_reducible_forcefactor
float autocvar_g_freezetag_revive_auto_reducible_forcefactor = 0.01
Definition at line 41 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_auto_reducible_maxforce
float autocvar_g_freezetag_revive_auto_reducible_maxforce
Definition at line 42 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_extra_size
float autocvar_g_freezetag_revive_extra_size
Definition at line 43 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_nade
bool autocvar_g_freezetag_revive_nade
Definition at line 47 of file sv_freezetag.qh.
autocvar_g_freezetag_revive_nade_health
float autocvar_g_freezetag_revive_nade_health
Definition at line 48 of file sv_freezetag.qh.
autocvar_g_freezetag_revive_spawnshield
float autocvar_g_freezetag_revive_spawnshield = 1
Definition at line 49 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_speed
float autocvar_g_freezetag_revive_speed
Definition at line 44 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_speed_t2s
float autocvar_g_freezetag_revive_speed_t2s = 0.25
Definition at line 45 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_revive_time_to_score
float autocvar_g_freezetag_revive_time_to_score = 1.5
Definition at line 46 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
autocvar_g_freezetag_team_spawns
bool autocvar_g_freezetag_team_spawns
Definition at line 8 of file sv_freezetag.qh.
Referenced by REGISTER_MUTATOR().
autocvar_g_freezetag_weaponarena
string autocvar_g_freezetag_weaponarena = "most_available"
Definition at line 9 of file sv_freezetag.qh.
Referenced by MUTATOR_HOOKFUNCTION().
freezetag_frozen_force
float freezetag_frozen_force
Definition at line 33 of file sv_freezetag.qh.
freezetag_frozen_time
float freezetag_frozen_time
Definition at line 31 of file sv_freezetag.qh.
freezetag_frozen_timeout
float freezetag_frozen_timeout
Definition at line 32 of file sv_freezetag.qh.
freezetag_revive_time
float freezetag_revive_time
Definition at line 30 of file sv_freezetag.qh.
freezetag_teams
float freezetag_teams
Definition at line 36 of file sv_freezetag.qh.
Referenced by freezetag_CheckTeams(), freezetag_Initialize(), and MUTATOR_HOOKFUNCTION().
ICE_MAX_ALPHA
const float ICE_MAX_ALPHA = 1
Definition at line 34 of file sv_freezetag.qh.
ICE_MIN_ALPHA
const float ICE_MIN_ALPHA = 0.1
Definition at line 35 of file sv_freezetag.qh.
ST_FT_ROUNDS
const int ST_FT_ROUNDS = 1
Definition at line 11 of file sv_freezetag.qh.
Referenced by freezetag_CheckWinner(), and freezetag_Initialize().