Xonotic: lib/random.qh File Reference
random.qh File Reference
Macros
#define prandom_debug()
#define RandomSelection_AddEnt(e, weight, priority) RandomSelection_Add(e, 0, string_null, '0 0 0', weight, priority)
#define RandomSelection_AddFloat(f, weight, priority) RandomSelection_Add(NULL, f, string_null, '0 0 0', weight, priority)
#define RandomSelection_AddString(s, weight, priority) RandomSelection_Add(NULL, 0, s, '0 0 0', weight, priority)
#define RandomSelection_AddVec(v, weight, priority) RandomSelection_Add(NULL, 0, string_null, v, weight, priority)
#define USE_PRANDOM
Functions
float prandom ()
vector prandomvec ()
void psrandom (float seed)
ERASEABLE void RandomSelection_Add (entity e, float f, string s, vector v, float weight, float priority)
ERASEABLE void RandomSelection_Init ()
Variables
float RandomSelection_best_priority
entity RandomSelection_chosen_ent
float RandomSelection_chosen_float
string RandomSelection_chosen_string
vector RandomSelection_chosen_vec
float RandomSelection_totalweight
Macro Definition Documentation
#define prandom_debug ()
Definition at line 31 of file random.qh.
Referenced by NET_HANDLE(), and psrandom().
#define RandomSelection_AddEnt (e, weight, priority) RandomSelection_Add(e, 0, string_null, '0 0 0', weight, priority)
Definition at line 14 of file random.qh.
Referenced by buff_NewType(), CheatCommand(), CheatImpulse(), invasion_PickMonster(), invasion_PickSpawn(), jumppad_push(), MUTATOR_HOOKFUNCTION(), Simple_TeleportPlayer(), Spawn_WeightedPoint(), SUB_UseTargets_Ex(), train_next_find(), and W_RandomWeapons().
#define RandomSelection_AddFloat (f, weight, priority) RandomSelection_Add(NULL, f, string_null, '0 0 0', weight, priority)
Definition at line 15 of file random.qh.
Referenced by invasion_SpawnChosenMonster(), MapVote_CheckRules_2(), NIX_ChooseNextWeapon(), RandomItems_GetRandomVanillaItemClassName(), TeamBalance_FindBestTeam(), and ttt_next_match().
#define RandomSelection_AddString (s, weight, priority) RandomSelection_Add(NULL, 0, s, '0 0 0', weight, priority)
Definition at line 16 of file random.qh.
Referenced by bot_setnameandstuff(), FixIntermissionClient(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), and RandomItems_GetRandomVanillaItemClassName().
#define RandomSelection_AddVec (v, weight, priority) RandomSelection_Add(NULL, 0, string_null, v, weight, priority)
Definition at line 17 of file random.qh.
#define USE_PRANDOM
Definition at line 21 of file random.qh.
Function Documentation
float prandom ()
Definition at line 100 of file random.qc.
References ftos(), LOG_TRACE(), M_PI, prandom_seed, and strcat().
Referenced by prandomvec(), SND_GIB_SPLAT_RANDOM(), and turret_gibtoss().
     {
         float c;
         c = crc16(false, strcat(ftos(prandom_seed), ftos(prandom_seed + M_PI)));
         prandom_seed = c;
     #ifdef USE_PRANDOM_DEBUG
             LOG_TRACE("RANDOM -> ", ftos(c));
     #endif
         return c / 65536;  // in [0..1[
     }
vector prandomvec ()
Definition at line 113 of file random.qc.
References prandom(), v, and vector().
Referenced by turret_gibtoss().
     {
         vector v;
         do
         {
             v.x = prandom();
             v.y = prandom();
             v.z = prandom();
         }
         while (v * v > 1);
         return v;
     }
void psrandom (float seed)
Definition at line 128 of file random.qc.
References ftos(), LOG_TRACE(), prandom_debug, and prandom_seed.
Referenced by NET_HANDLE().
     {
         prandom_seed = seed;
     #ifdef USE_PRANDOM_DEBUG
             LOG_TRACE("SRANDOM ", ftos(seed));
     #endif
     }
ERASEABLE void RandomSelection_Add (entity e, float f, string s, vector v, float weight, float priority)
Definition at line 14 of file random.qc.
References random(), RandomSelection_best_priority, RandomSelection_chosen_ent, RandomSelection_chosen_float, RandomSelection_chosen_string, RandomSelection_chosen_vec, RandomSelection_totalweight, and v.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if (priority > RandomSelection_best_priority)
     {
         RandomSelection_best_priority = priority;
         RandomSelection_chosen_ent = e;
         RandomSelection_chosen_float = f;
         RandomSelection_chosen_string = s;
         RandomSelection_chosen_vec = v;
         RandomSelection_totalweight = weight;
     }
     else if (priority == RandomSelection_best_priority)
     {
         RandomSelection_totalweight += weight;
         if (random() * RandomSelection_totalweight <= weight)
         {
             RandomSelection_chosen_ent = e;
             RandomSelection_chosen_float = f;
             RandomSelection_chosen_string = s;
             RandomSelection_chosen_vec = v;
         }
     }
 }
ERASEABLE void RandomSelection_Init ()
Definition at line 4 of file random.qc.
References ERASEABLE, NULL, RandomSelection_best_priority, RandomSelection_chosen_ent, RandomSelection_chosen_float, RandomSelection_chosen_string, RandomSelection_totalweight, and string_null.
Referenced by bot_setnameandstuff(), buff_NewType(), CheatCommand(), CheatImpulse(), FixIntermissionClient(), invasion_PickMonster(), invasion_PickSpawn(), invasion_SpawnChosenMonster(), jumppad_push(), MapVote_CheckRules_2(), MUTATOR_HOOKFUNCTION(), NIX_ChooseNextWeapon(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), RandomItems_GetRandomVanillaItemClassName(), Simple_TeleportPlayer(), Spawn_WeightedPoint(), spawnmonster(), SUB_UseTargets_Ex(), TeamBalance_FindBestTeam(), TeleportPlayer(), train_next_find(), ttt_next_match(), and W_RandomWeapons().
 {
     RandomSelection_totalweight = 0;
     RandomSelection_chosen_ent = NULL;
     RandomSelection_chosen_float = 0;
     RandomSelection_chosen_string = string_null;
     RandomSelection_best_priority = -1;
 }
Variable Documentation
float RandomSelection_best_priority
Definition at line 4 of file random.qh.
Referenced by MapVote_CheckRules_2(), RandomSelection_Add(), and RandomSelection_Init().
entity RandomSelection_chosen_ent
Definition at line 5 of file random.qh.
Referenced by buff_NewType(), CheatCommand(), CheatImpulse(), invasion_PickMonster(), invasion_PickSpawn(), jumppad_push(), MUTATOR_HOOKFUNCTION(), RandomSelection_Add(), RandomSelection_Init(), Simple_TeleportPlayer(), Spawn_WeightedPoint(), spawnmonster(), SUB_UseTargets_Ex(), train_next_find(), and W_RandomWeapons().
float RandomSelection_chosen_float
Definition at line 6 of file random.qh.
Referenced by invasion_SpawnChosenMonster(), MapVote_CheckRules_2(), NIX_ChooseNextWeapon(), RandomItems_GetRandomVanillaItemClassName(), RandomSelection_Add(), RandomSelection_Init(), TeamBalance_FindBestTeam(), and ttt_next_match().
string RandomSelection_chosen_string
Definition at line 7 of file random.qh.
Referenced by bot_setnameandstuff(), FixIntermissionClient(), invasion_SpawnChosenMonster(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), RandomItems_GetRandomVanillaItemClassName(), RandomSelection_Add(), RandomSelection_Init(), and TeleportPlayer().
vector RandomSelection_chosen_vec
Definition at line 8 of file random.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and RandomSelection_Add().
float RandomSelection_totalweight
Definition at line 3 of file random.qh.
Referenced by RandomSelection_Add(), and RandomSelection_Init().