Xonotic: common/gamemodes/sv_rules.qh File Reference
sv_rules.qh File Reference
Macros
#define GameRules_scoring(teams, spprio, stprio, fields)
#define GameRules_scoring_add(client, fld, value) _GameRules_scoring_add(client, SP_##fld, value)
#define GameRules_scoring_add_team(client, fld, value) _GameRules_scoring_add_team(client, SP_##fld, ST_##fld, value)
Functions
float _GameRules_scoring_add (entity client, entity sp, float value)
float _GameRules_scoring_add_team (entity client, entity sp, int st, float value)
void _GameRules_scoring_begin (int teams, float spprio, float stprio)
void _GameRules_scoring_end ()
void _GameRules_scoring_field (entity i, string label, int scoreflags)
void _GameRules_scoring_field_team (float i, string label, int scoreflags)
void GameRules_limit_fallbacks ()
Set any unspecified rules to their defaults.
void GameRules_limit_lead (int limit)
void GameRules_limit_score (int limit)
void GameRules_limit_time (int limit)
void GameRules_limit_time_qualifying (int limit)
void GameRules_score_enabled (bool value)
Disabling score disables the "score" column on the scoreboard.
bool GameRules_scoring_is_vip (entity player)
void GameRules_scoring_vip (entity player, bool value)
Mark a player as being 'important' (flag carrier, ball carrier, etc)
void GameRules_spawning_teams (bool value)
Used to disable team spawns in team modes.
void GameRules_teams (bool value)
Variables
int autocvar_leadlimit_and_fraglimit
int autocvar_leadlimit_override
int total_players
Macro Definition Documentation
GameRules_scoring
#define GameRules_scoring (teams, spprio, stprio, fields)
Value:
MACRO_BEGIN \
    _GameRules_scoring_begin((teams), (spprio), (stprio)); \
    noref void(entity, string, float) field = _GameRules_scoring_field; \
    /* todo: just have the one `field` function */ \
    noref void(int, string, float) field_team = _GameRules_scoring_field_team; \
    LAMBDA(fields); \
    _GameRules_scoring_end(); \
MACRO_END
Parameters
teams a bitmask of active teams
spprio player score priority (if frags aren't enabled)
stprio team score priority (if frags aren't enabled)
Definition at line 38 of file sv_rules.qh.
Referenced by ctf_ScoreRules(), cts_ScoreRules(), freezetag_Initialize(), invasion_ScoreRules(), kh_ScoreRules(), nb_ScoreRules(), ons_ScoreRules(), race_ScoreRules(), REGISTER_MUTATOR(), ScoreRules_dom(), and ScoreRules_generic().
GameRules_scoring_add
#define GameRules_scoring_add (client, fld, value) _GameRules_scoring_add(client, SP_##fld, value)
Definition at line 60 of file sv_rules.qh.
Referenced by CheckRules_World(), ctf_CaptureShield_CheckStatus(), ctf_Handle_Capture(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_Handle_Return(), dompoint_captured(), dompointthink(), freezetag_Add_Score(), GiveFrags(), GoalTouch(), Invasion_CheckWinner(), ka_TimeScoring(), ka_TouchEvent(), kh_HandleFrags(), kh_Key_Collect(), kh_Key_DropAll(), kh_Key_DropOne(), kh_LoserTeam(), lms_AddPlayer(), lms_RemovePlayer(), Monster_Dead(), MUTATOR_HOOKFUNCTION(), Obituary(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_GeneratorDamage(), PlayerDamage(), race_GetFractionalLapCount(), race_SendTime(), and WinningCondition_LMS().
GameRules_scoring_add_team
#define GameRules_scoring_add_team (client, fld, value) _GameRules_scoring_add_team(client, SP_##fld, ST_##fld, value)
Definition at line 62 of file sv_rules.qh.
Referenced by assault_objective_decrease_use(), ctf_Handle_Capture(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_Handle_Return(), kh_WinnerTeam(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Icon_BuildThink(), race_SendTime(), and UpdateFrags().
Function Documentation
_GameRules_scoring_add()
float _GameRules_scoring_add (entity client, entity sp, float value)
Definition at line 107 of file sv_rules.qc.
References PlayerScore_Add().
 {
     return PlayerScore_Add(client, sp, value);
 }
_GameRules_scoring_add_team()
float _GameRules_scoring_add_team (entity client, entity sp, int st, float value)
Definition at line 111 of file sv_rules.qc.
References PlayerTeamScore_Add().
 {
     return PlayerTeamScore_Add(client, sp, st, value);
 }
_GameRules_scoring_begin()
void _GameRules_scoring_begin (int teams, float spprio, float stprio)
Definition at line 80 of file sv_rules.qc.
References _GameRules_score_enabled, and ScoreRules_basics().
 {
     ScoreRules_basics(teams, spprio, stprio, _GameRules_score_enabled);
 }
_GameRules_scoring_end()
void _GameRules_scoring_end ()
Definition at line 92 of file sv_rules.qc.
References ScoreRules_basics_end().
 {
     ScoreRules_basics_end();
 }
_GameRules_scoring_field()
void _GameRules_scoring_field (entity i, string label, int scoreflags)
Definition at line 84 of file sv_rules.qc.
References ScoreInfo_SetLabel_PlayerScore().
 {
     ScoreInfo_SetLabel_PlayerScore(i, label, scoreflags);
 }
_GameRules_scoring_field_team()
void _GameRules_scoring_field_team (float i, string label, int scoreflags)
Definition at line 88 of file sv_rules.qc.
References ScoreInfo_SetLabel_TeamScore().
 {
     ScoreInfo_SetLabel_TeamScore(i, label, scoreflags);
 }
GameRules_limit_fallbacks()
void GameRules_limit_fallbacks ()
Set any unspecified rules to their defaults.
Definition at line 73 of file sv_rules.qc.
References autocvar_leadlimit_override, GameRules_limit_lead(), GameRules_limit_score(), and GameRules_limit_time().
Referenced by spawnfunc().
 {
     GameRules_limit_score(autocvar_fraglimit_override);
     GameRules_limit_lead(autocvar_leadlimit_override);
     GameRules_limit_time(autocvar_timelimit_override);
 }
GameRules_limit_lead()
void GameRules_limit_lead (int limit)
Definition at line 44 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_lead_initialized.
Referenced by GameRules_limit_fallbacks(), nb_Initialize(), rc_SetLimits(), REGISTER_MUTATOR(), and tdm_Initialize().
 {
     if (GameRules_limit_lead_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("leadlimit", ftos(limit));
     GameRules_limit_lead_initialized = true;
 }
GameRules_limit_score()
void GameRules_limit_score (int limit)
Definition at line 34 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_score_initialized.
Referenced by GameRules_limit_fallbacks(), nb_Initialize(), rc_SetLimits(), REGISTER_MUTATOR(), and tdm_Initialize().
 {
     if (GameRules_limit_score_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("fraglimit", ftos(limit));
     GameRules_limit_score_initialized = true;
 }
GameRules_limit_time()
void GameRules_limit_time (int limit)
Definition at line 54 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_time_initialized.
Referenced by GameRules_limit_fallbacks(), and rc_SetLimits().
 {
     if (GameRules_limit_time_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("timelimit", ftos(limit));
     GameRules_limit_time_initialized = true;
 }
GameRules_limit_time_qualifying()
void GameRules_limit_time_qualifying (int limit)
Definition at line 64 of file sv_rules.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and GameRules_limit_time_qualifying_initialized.
Referenced by rc_SetLimits().
 {
     if (GameRules_limit_time_qualifying_initialized) return;
     if (autocvar_g_campaign) return;
     if (limit < 0) return;
     cvar_set("g_race_qualifying_timelimit", ftos(limit));
     GameRules_limit_time_qualifying_initialized = true;
 }
GameRules_score_enabled()
void GameRules_score_enabled (bool value)
Disabling score disables the "score" column on the scoreboard.
Definition at line 28 of file sv_rules.qc.
References _GameRules_score_enabled.
Referenced by cts_ScoreRules(), invasion_ScoreRules(), race_ScoreRules(), and REGISTER_MUTATOR().
 {
     _GameRules_score_enabled = value;
 }
GameRules_scoring_is_vip()
bool GameRules_scoring_is_vip (entity player)
Definition at line 102 of file sv_rules.qc.
 {
     return player.m_GameRules_scoring_vip;
 }
GameRules_scoring_vip()
void GameRules_scoring_vip (entity player, bool value)
Mark a player as being 'important' (flag carrier, ball carrier, etc)
Parameters
player the entity to mark
value VIP status
Definition at line 98 of file sv_rules.qc.
Referenced by ctf_Handle_Pickup(), ctf_Handle_Retrieve(), ctf_Handle_Throw(), ctf_RespawnFlag(), DropBall(), GiveBall(), ka_PlayerReset(), and ka_TouchEvent().
 {
     player.m_GameRules_scoring_vip = value;
 }
GameRules_spawning_teams()
void GameRules_spawning_teams (bool value)
Used to disable team spawns in team modes.
Definition at line 22 of file sv_rules.qc.
References have_team_spawns.
Referenced by GameRules_teams(), REGISTER_MUTATOR(), and tdm_Initialize().
 {
     have_team_spawns = value ? -1 : 0;
 }
GameRules_teams()
void GameRules_teams (bool value)
Definition at line 6 of file sv_rules.qc.
References cvar_set(), GameRules_spawning_teams(), SERVERFLAG_TEAMPLAY, serverflags, Team_InitTeams(), and teamplay.
Referenced by InitGameplayMode(), nb_Initialize(), rc_SetLimits(), REGISTER_MUTATOR(), and tdm_Initialize().
 {
     if (value) {
         serverflags |= SERVERFLAG_TEAMPLAY;
         teamplay = 1;
         cvar_set("teamplay", "2");  // DP needs this for sending proper getstatus replies.
         Team_InitTeams();
         GameRules_spawning_teams(true);
     } else {
         serverflags &= ~SERVERFLAG_TEAMPLAY;
         teamplay = 0;
         cvar_set("teamplay", "0");  // DP needs this for sending proper getstatus replies.
         GameRules_spawning_teams(false);
     }
 }
Variable Documentation
autocvar_leadlimit_and_fraglimit
int autocvar_leadlimit_and_fraglimit
Definition at line 4 of file sv_rules.qh.
Referenced by WinningCondition_Scores().
autocvar_leadlimit_override
int autocvar_leadlimit_override
Definition at line 5 of file sv_rules.qh.
Referenced by GameRules_limit_fallbacks().
total_players
int total_players
Definition at line 8 of file sv_rules.qh.
Referenced by CA_CheckTeams(), CA_count_alive_players(), freezetag_CheckTeams(), and freezetag_count_alive_players().