Xonotic: common/gamemodes/gamemode/freezetag/sv_freezetag.qc File Reference
sv_freezetag.qc File Reference
#include "sv_freezetag.qh"
#include <server/resources.qh>
Macros
#define IS_REVIVING(player, it, revive_extra_size)
Functions
void freezetag_Add_Score (entity targ, entity attacker)
bool freezetag_CheckTeams ()
bool freezetag_CheckWinner ()
void freezetag_count_alive_players ()
void freezetag_Freeze (entity targ, entity attacker)
int freezetag_getWinnerTeam ()
void freezetag_Initialize ()
bool freezetag_isEliminated (entity e)
entity freezetag_LastPlayerForTeam (entity this)
void freezetag_LastPlayerForTeam_Notify (entity this)
void ft_RemovePlayer (entity this)
void havocbot_goalrating_ft_freeplayers (entity this, float ratingscale, vector org, float sradius)
void havocbot_role_ft_freeing (entity this)
void havocbot_role_ft_offense (entity this)
MUTATOR_HOOKFUNCTION (ft, ClientDisconnect)
MUTATOR_HOOKFUNCTION (ft, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (ft, PlayerDies)
MUTATOR_HOOKFUNCTION (ft, PlayerSpawn)
MUTATOR_HOOKFUNCTION (ft, reset_map_players)
MUTATOR_HOOKFUNCTION (ft, GiveFragsForKill, CBC_ORDER_FIRST)
MUTATOR_HOOKFUNCTION (ft, Unfreeze)
MUTATOR_HOOKFUNCTION (ft, PlayerPreThink, CBC_ORDER_FIRST)
MUTATOR_HOOKFUNCTION (ft, SetStartItems)
MUTATOR_HOOKFUNCTION (ft, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (ft, TeamBalance_CheckAllowedTeams, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (ft, SetWeaponArena)
MUTATOR_HOOKFUNCTION (ft, FragCenterMessage)
MUTATOR_HOOKFUNCTION (ft, SV_ParseServerCommand)
void nades_Clear (entity)
void nades_GiveBonus (entity player, float score)
void (entity this) havocbot_role_ft_freeing
Variables
float autocvar_g_freezetag_frozen_maxtime
float autocvar_g_freezetag_revive_clearspeed
float autocvar_g_freezetag_round_timelimit
int autocvar_g_freezetag_teams_override
float autocvar_g_freezetag_warmup
Macro Definition Documentation
#define IS_REVIVING (player, it, revive_extra_size)
Value:
(it != player && !STAT(FROZEN, it) && !IS_DEAD(it) && SAME_TEAM(it, player) \
    && boxesoverlap(player.absmin - revive_extra_size, player.absmax + revive_extra_size, it.absmin, it.absmax))
Definition at line 462 of file sv_freezetag.qc.
Referenced by MUTATOR_HOOKFUNCTION().
Function Documentation
void freezetag_Add_Score (entity targ, entity attacker)
Definition at line 177 of file sv_freezetag.qc.
References GameRules_scoring_add, and IS_PLAYER.
Referenced by freezetag_Freeze(), and MUTATOR_HOOKFUNCTION().
 {
     if(attacker == targ)
     {
         // you froze your own dumb targ
         // counted as "suicide" already
         GameRules_scoring_add(targ, SCORE, -1);
     }
     else if(IS_PLAYER(attacker))
     {
         // got frozen by an enemy
         // counted as "kill" and "death" already
         GameRules_scoring_add(targ, SCORE, -1);
         GameRules_scoring_add(attacker, SCORE, +1);
     }
     // else nothing - got frozen by the game type rules themselves
 }
bool freezetag_CheckTeams ()
Definition at line 46 of file sv_freezetag.qc.
References freezetag_teams, NULL, NUM_TEAMS, NumTeams(), Team_GetNumberOfAlivePlayers(), Team_GetNumberOfAliveTeams(), Team_GetTeamFromIndex(), Team_IndexToBit(), and total_players.
Referenced by freezetag_Initialize().
 {
     static float prev_missing_teams_mask;
     if (Team_GetNumberOfAliveTeams() == NumTeams(freezetag_teams))
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return true;
     }
     if(total_players == 0)
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return false;
     }
     int missing_teams_mask = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if ((freezetag_teams & Team_IndexToBit(i)) &&
             (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(i)) == 0))
         {
             missing_teams_mask |= Team_IndexToBit(i);
         }
     }
     if(prev_missing_teams_mask != missing_teams_mask)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_MISSING_TEAMS, missing_teams_mask);
         prev_missing_teams_mask = missing_teams_mask;
     }
     return false;
 }
bool freezetag_CheckWinner ()
Definition at line 108 of file sv_freezetag.qc.
References APP_TEAM_NUM, autocvar_g_freezetag_round_timelimit, autocvar_g_freezetag_warmup, FOREACH_CLIENT, freezetag_getWinnerTeam(), IS_PLAYER, nades_Clear(), NULL, round_handler_GetEndTime, round_handler_Init(), ST_SCORE, Team_GetNumberOfAliveTeams(), TeamScore_AddToTeam(), and time.
Referenced by freezetag_Initialize().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         FOREACH_CLIENT(IS_PLAYER(it), {
             it.freezetag_frozen_timeout = 0;
             nades_Clear(it);
         });
         game_stopped = true;
         round_handler_Init(5, autocvar_g_freezetag_warmup, autocvar_g_freezetag_round_timelimit);
         return true;
     }
     if (Team_GetNumberOfAliveTeams() > 1)
     {
         return false;
     }
     int winner_team = freezetag_getWinnerTeam();
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_SCORE, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     FOREACH_CLIENT(IS_PLAYER(it), {
         it.freezetag_frozen_timeout = 0;
         nades_Clear(it);
     });
     game_stopped = true;
     round_handler_Init(5, autocvar_g_freezetag_warmup, autocvar_g_freezetag_round_timelimit);
     return true;
 }
void freezetag_count_alive_players ()
Definition at line 12 of file sv_freezetag.qc.
References eliminatedPlayers, entity(), Entity_GetTeam(), Entity_HasValidTeam(), FOREACH_CLIENT, FROZEN_NORMAL, GetResource(), IS_PLAYER, IS_REAL_CLIENT, NUM_TEAMS, RES_HEALTH, Team_GetNumberOfAlivePlayers(), Team_GetTeamFromIndex(), Team_SetNumberOfAlivePlayers(), and total_players.
Referenced by freezetag_Freeze(), ft_RemovePlayer(), and MUTATOR_HOOKFUNCTION().
 {
     total_players = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         Team_SetNumberOfAlivePlayers(Team_GetTeamFromIndex(i), 0);
     }
     FOREACH_CLIENT(IS_PLAYER(it) && Entity_HasValidTeam(it),
     {
         ++total_players;
         if (GetResource(it, RES_HEALTH) < 1 || STAT(FROZEN, it) == FROZEN_NORMAL)
         {
             continue;
         }
         entity team_ = Entity_GetTeam(it);
         int num_alive = Team_GetNumberOfAlivePlayers(team_);
         ++num_alive;
         Team_SetNumberOfAlivePlayers(team_, num_alive);
     });
     FOREACH_CLIENT(IS_REAL_CLIENT(it),
     {
         STAT(REDALIVE, it) = Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(
             1));
         STAT(BLUEALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(2));
         STAT(YELLOWALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(3));
         STAT(PINKALIVE, it) = Team_GetNumberOfAlivePlayers(
             Team_GetTeamFromIndex(4));
     });
     eliminatedPlayers.SendFlags |= 1;
 }
void freezetag_Freeze (entity targ, entity attacker)
Definition at line 196 of file sv_freezetag.qc.
References autocvar_g_freezetag_frozen_maxtime, Freeze(), freezetag_Add_Score(), freezetag_count_alive_players(), FROZEN_NORMAL, and time.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(STAT(FROZEN, targ))
         return;
     if(autocvar_g_freezetag_frozen_maxtime > 0)
         targ.freezetag_frozen_timeout = time + autocvar_g_freezetag_frozen_maxtime;
     Freeze(targ, 0, FROZEN_NORMAL, true);
     freezetag_count_alive_players();
     freezetag_Add_Score(targ, attacker);
 }
int freezetag_getWinnerTeam ()
Definition at line 80 of file sv_freezetag.qc.
References entity(), nades_Clear(), nades_GiveBonus(), NUM_TEAM_1, NUM_TEAMS, Team_GetNumberOfAlivePlayers(), Team_GetTeamFromIndex(), and Team_IndexToTeam().
Referenced by freezetag_CheckWinner().
 {
     int winner_team = 0;
     if (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(1)) >= 1)
     {
         winner_team = NUM_TEAM_1;
     }
     for (int i = 2; i <= NUM_TEAMS; ++i)
     {
         if (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(i)) >= 1)
         {
             if (winner_team != 0)
             {
                 return 0;
             }
             winner_team = Team_IndexToTeam(i);
         }
     }
     if (winner_team)
     {
         return winner_team;
     }
     return -1; // no player left
 }
void freezetag_Initialize ()
Definition at line 620 of file sv_freezetag.qc.
References autocvar_g_freezetag_round_timelimit, autocvar_g_freezetag_teams_override, autocvar_g_freezetag_warmup, BITS, bound(), cvar(), EliminatedPlayers_Init(), freezetag_CheckTeams(), freezetag_CheckWinner(), freezetag_isEliminated(), freezetag_teams, func_null(), GameRules_scoring, round_handler_Init(), round_handler_Spawn(), and SFL_SORT_PRIO_PRIMARY.
Referenced by REGISTER_MUTATOR().
 {
     freezetag_teams = autocvar_g_freezetag_teams_override;
     if(freezetag_teams < 2)
         freezetag_teams = cvar("g_freezetag_teams"); // read the cvar directly as it gets written earlier in the same frame
     freezetag_teams = BITS(bound(2, freezetag_teams, 4));
     GameRules_scoring(freezetag_teams, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_PRIMARY, {
         field(SP_FREEZETAG_REVIVALS, "revivals", 0);
     });
     round_handler_Spawn(freezetag_CheckTeams, freezetag_CheckWinner, func_null);
     round_handler_Init(5, autocvar_g_freezetag_warmup, autocvar_g_freezetag_round_timelimit);
     EliminatedPlayers_Init(freezetag_isEliminated);
 }
bool freezetag_isEliminated (entity e)
Definition at line 211 of file sv_freezetag.qc.
References entity(), FROZEN_NORMAL, havocbot_role_ft_freeing(), havocbot_role_ft_offense(), IS_DEAD, IS_PLAYER, and void().
Referenced by freezetag_Initialize().
 {
     if(IS_PLAYER(e) && (STAT(FROZEN, e) == FROZEN_NORMAL || IS_DEAD(e)))
         return true;
     return false;
 }
entity freezetag_LastPlayerForTeam (entity this)
Definition at line 151 of file sv_freezetag.qc.
References entity(), FOREACH_CLIENT, FROZEN_NORMAL, GetResource(), IS_PLAYER, NULL, RES_HEALTH, and SAME_TEAM.
Referenced by freezetag_LastPlayerForTeam_Notify().
 {
     entity last_pl = NULL;
     FOREACH_CLIENT(IS_PLAYER(it) && it != this && SAME_TEAM(it, this), {
         if (STAT(FROZEN, it) != FROZEN_NORMAL && GetResource(it, RES_HEALTH) >= 1)
         {
             if (!last_pl)
                 last_pl = it;
             else
                 return NULL;
         }
     });
     return last_pl;
 }
void freezetag_LastPlayerForTeam_Notify (entity this)
Definition at line 166 of file sv_freezetag.qc.
References entity(), freezetag_LastPlayerForTeam(), round_handler_IsActive, and round_handler_IsRoundStarted.
Referenced by ft_RemovePlayer(), and MUTATOR_HOOKFUNCTION().
 {
     if(round_handler_IsActive())
     if(round_handler_IsRoundStarted())
     {
         entity pl = freezetag_LastPlayerForTeam(this);
         if(pl)
             Send_Notification(NOTIF_ONE, pl, MSG_CENTER, CENTER_ALONE);
     }
 }
void ft_RemovePlayer (entity this)
Definition at line 327 of file sv_freezetag.qc.
References freezetag_count_alive_players(), freezetag_LastPlayerForTeam_Notify(), FROZEN_NORMAL, RES_HEALTH, SetResourceExplicit(), and Unfreeze().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if (STAT(FROZEN, this) != FROZEN_NORMAL)
         freezetag_LastPlayerForTeam_Notify(this);
     Unfreeze(this, false);
     SetResourceExplicit(this, RES_HEALTH, 0); // neccessary to correctly count alive players
     freezetag_count_alive_players();
 }
void havocbot_goalrating_ft_freeplayers (entity this, float ratingscale, vector org, float sradius)
Definition at line 226 of file sv_freezetag.qc.
References entity(), FLOAT_MAX, FOREACH_CLIENT, FROZEN_NORMAL, GetResource(), IS_PLAYER, navigation_routerating(), NULL, RES_HEALTH, SAME_TEAM, vdist, and vlen2.
Referenced by havocbot_role_ft_freeing(), and havocbot_role_ft_offense().
 {
     entity best_pl = NULL;
     float best_dist2 = FLOAT_MAX;
     FOREACH_CLIENT(IS_PLAYER(it) && it != this && SAME_TEAM(it, this), {
         if (STAT(FROZEN, it) == FROZEN_NORMAL)
         {
             if(vdist(it.origin - org, >, sradius))
                 continue;
             navigation_routerating(this, it, ratingscale, 2000);
         }
         else if (best_dist2
             && GetResource(it, RES_HEALTH) < GetResource(this, RES_HEALTH) + 30
             && vlen2(it.origin - org) < best_dist2)
         {
             // If teamate is not frozen still seek them out as fight better
             // in a group.
             best_dist2 = vlen2(it.origin - org);
             if (best_dist2 < 700 ** 2)
             {
                 best_pl = NULL;
                 best_dist2 = 0; // already close to a teammate
             }
             else
                 best_pl = it;
         }
     });
     if (best_pl)
         navigation_routerating(this, best_pl, ratingscale / 2, 2000);
 }
void havocbot_role_ft_freeing (entity this)
Definition at line 293 of file sv_freezetag.qc.
References havocbot_goalrating_enemyplayers(), havocbot_goalrating_ft_freeplayers(), havocbot_goalrating_items(), havocbot_goalrating_waypoints(), havocbot_role_ft_offense(), havocbot_role_timeout, IS_DEAD, LOG_TRACE(), navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), origin, random(), and time.
Referenced by freezetag_isEliminated(), havocbot_role_ft_offense(), and MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + random() * 10 + 20;
     if (time > this.havocbot_role_timeout)
     {
         LOG_TRACE("changing role to offense");
         this.havocbot_role = havocbot_role_ft_offense;
         this.havocbot_role_timeout = 0;
         return;
     }
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_items(this, 10000, this.origin, 10000);
         havocbot_goalrating_enemyplayers(this, 5000, this.origin, 10000);
         havocbot_goalrating_ft_freeplayers(this, 20000, this.origin, 10000);
         havocbot_goalrating_waypoints(this, 1, this.origin, 3000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
void havocbot_role_ft_offense (entity this)
Definition at line 257 of file sv_freezetag.qc.
References FOREACH_CLIENT, FROZEN_NORMAL, havocbot_goalrating_enemyplayers(), havocbot_goalrating_ft_freeplayers(), havocbot_goalrating_items(), havocbot_goalrating_waypoints(), havocbot_role_ft_freeing(), havocbot_role_timeout, IS_DEAD, IS_PLAYER, LOG_TRACE(), navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), origin, random(), SAME_TEAM, and time.
Referenced by freezetag_isEliminated(), havocbot_role_ft_freeing(), and MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + random() * 10 + 20;
     // Count how many players on team are unfrozen.
     int unfrozen = 0;
     FOREACH_CLIENT(IS_PLAYER(it) && SAME_TEAM(it, this) && STAT(FROZEN, it) != FROZEN_NORMAL, {
         unfrozen++;
     });
     // If only one left on team or if role has timed out then start trying to free players.
     if ((!unfrozen && STAT(FROZEN, this) != FROZEN_NORMAL) || time > this.havocbot_role_timeout)
     {
         LOG_TRACE("changing role to freeing");
         this.havocbot_role = havocbot_role_ft_freeing;
         this.havocbot_role_timeout = 0;
         return;
     }
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_items(this, 12000, this.origin, 10000);
         havocbot_goalrating_enemyplayers(this, 10000, this.origin, 10000);
         havocbot_goalrating_ft_freeplayers(this, 9000, this.origin, 10000);
         havocbot_goalrating_waypoints(this, 1, this.origin, 3000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
MUTATOR_HOOKFUNCTION (ft , ClientDisconnect)
Definition at line 337 of file sv_freezetag.qc.
References entity(), ft_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     ft_RemovePlayer(player);
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , MakePlayerObserver)
Definition at line 345 of file sv_freezetag.qc.
References entity(), ft_RemovePlayer(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     ft_RemovePlayer(player);
 }
MUTATOR_HOOKFUNCTION (ft , PlayerDies)
Definition at line 352 of file sv_freezetag.qc.
References entity(), freezetag_Add_Score(), freezetag_count_alive_players(), freezetag_Freeze(), freezetag_LastPlayerForTeam_Notify(), FROZEN_NORMAL, IS_PLAYER, ITEM_DAMAGE_NEEDKILL, M_ARGV, NULL, RESPAWN_FORCE, round_handler_CountdownRunning, round_handler_IsActive, time, and Unfreeze().
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float frag_deathtype = M_ARGV(3, float);
     if(round_handler_IsActive())
     if(round_handler_CountdownRunning())
     {
         if (STAT(FROZEN, frag_target) == FROZEN_NORMAL)
             Unfreeze(frag_target, true);
         freezetag_count_alive_players();
         frag_target.respawn_time = time;
         frag_target.respawn_flags |= RESPAWN_FORCE;
         return true;
     }
     // Cases DEATH_TEAMCHANGE and DEATH_AUTOTEAMCHANGE are needed to fix a bug whe
     // you succeed changing team through the menu: you both really die (gibbing) and get frozen
     if(ITEM_DAMAGE_NEEDKILL(frag_deathtype)
         || frag_deathtype == DEATH_TEAMCHANGE.m_id || frag_deathtype == DEATH_AUTOTEAMCHANGE.m_id)
     {
         // let the player die, he will be automatically frozen when he respawns
         if (STAT(FROZEN, frag_target) != FROZEN_NORMAL)
         {
             freezetag_Add_Score(frag_target, frag_attacker);
             freezetag_count_alive_players();
             freezetag_LastPlayerForTeam_Notify(frag_target);
         }
         else
             Unfreeze(frag_target, false); // remove ice
         frag_target.freezetag_frozen_timeout = -2; // freeze on respawn
         return true;
     }
     if (STAT(FROZEN, frag_target) == FROZEN_NORMAL)
         return true;
     freezetag_Freeze(frag_target, frag_attacker);
     freezetag_LastPlayerForTeam_Notify(frag_target);
     if(frag_attacker == frag_target || frag_attacker == NULL)
     {
         if(IS_PLAYER(frag_target))
             Send_Notification(NOTIF_ONE, frag_target, MSG_CENTER, CENTER_FREEZETAG_SELF);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_FREEZETAG_SELF, frag_target.netname);
     }
     else
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_FREEZETAG_FREEZE, frag_target.netname, frag_attacker.netname);
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , PlayerSpawn)
Definition at line 407 of file sv_freezetag.qc.
References entity(), freezetag_count_alive_players(), freezetag_Freeze(), M_ARGV, NULL, round_handler_IsActive, and round_handler_IsRoundStarted.
 {
     entity player = M_ARGV(0, entity);
     if(player.freezetag_frozen_timeout == -1) // if PlayerSpawn is called by reset_map_players
         return true; // do nothing, round is starting right now
     if(player.freezetag_frozen_timeout == -2) // player was dead
     {
         freezetag_Freeze(player, NULL);
         return true;
     }
     freezetag_count_alive_players();
     if(round_handler_IsActive())
     if(round_handler_IsRoundStarted())
     {
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_FREEZETAG_SPAWN_LATE);
         freezetag_Freeze(player, NULL);
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , reset_map_players)
Definition at line 432 of file sv_freezetag.qc.
References CS(), FOREACH_CLIENT, freezetag_count_alive_players(), IS_PLAYER, and PutClientInServer().
 {
     FOREACH_CLIENT(IS_PLAYER(it), {
         CS(it).killcount = 0;
         it.freezetag_frozen_timeout = -1;
         PutClientInServer(it);
         it.freezetag_frozen_timeout = 0;
     });
     freezetag_count_alive_players();
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , GiveFragsForKill , CBC_ORDER_FIRST)
Definition at line 444 of file sv_freezetag.qc.
References M_ARGV.
 {
     M_ARGV(2, float) = 0; // no frags counted in Freeze Tag
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , Unfreeze)
Definition at line 450 of file sv_freezetag.qc.
References entity(), and M_ARGV.
 {
     entity targ = M_ARGV(0, entity);
     targ.freezetag_frozen_time = 0;
     targ.freezetag_frozen_timeout = 0;
 }
MUTATOR_HOOKFUNCTION (ft , PlayerPreThink , CBC_ORDER_FIRST)
Definition at line 466 of file sv_freezetag.qc.
References autocvar_g_freezetag_frozen_maxtime, autocvar_g_freezetag_revive_clearspeed, autocvar_g_freezetag_revive_extra_size, autocvar_g_freezetag_revive_speed, autocvar_g_nades_bonus_score_low, bound(), entity(), FOREACH_CLIENT, frametime, freezetag_count_alive_players(), FROZEN_NORMAL, GameRules_scoring_add, IS_PLAYER, IS_REVIVING, M_ARGV, max(), nades_GiveBonus(), NULL, RES_HEALTH, round_handler_IsActive, round_handler_IsRoundStarted, SetResourceExplicit(), start_health, time, Unfreeze(), vector(), warmup_stage, and warmup_start_health.
 {
     if(game_stopped)
         return true;
     if(round_handler_IsActive())
     if(!round_handler_IsRoundStarted())
         return true;
     int n;
     entity player = M_ARGV(0, entity);
     //if (STAT(FROZEN, player) == FROZEN_NORMAL)
     //if(player.freezetag_frozen_timeout > 0 && time < player.freezetag_frozen_timeout)
         //player.iceblock.alpha = ICE_MIN_ALPHA + (ICE_MAX_ALPHA - ICE_MIN_ALPHA) * (player.freezetag_frozen_timeout - time) / (player.freezetag_frozen_timeout - player.freezetag_frozen_time);
     entity reviving_players_last = NULL;
     entity reviving_players_first = NULL;
     if(player.freezetag_frozen_timeout > 0 && time >= player.freezetag_frozen_timeout)
         n = -1;
     else
     {
         n = 0;
         vector revive_extra_size = '1 1 1' * autocvar_g_freezetag_revive_extra_size;
         FOREACH_CLIENT(IS_PLAYER(it) && IS_REVIVING(player, it, revive_extra_size), {
             if (reviving_players_last)
                 reviving_players_last.chain = it;
             reviving_players_last = it;
             if (!reviving_players_first)
                 reviving_players_first = it;
             ++n;
         });
         if (reviving_players_last)
             reviving_players_last.chain = NULL;
     }
     if (!n) // no teammate nearby
     {
         if (STAT(FROZEN, player) == FROZEN_NORMAL)
         {
             STAT(REVIVE_PROGRESS, player) = bound(0, STAT(REVIVE_PROGRESS, player) - frametime * autocvar_g_freezetag_revive_clearspeed, 1);
             SetResourceExplicit(player, RES_HEALTH, max(1, STAT(REVIVE_PROGRESS, player) * ((warmup_stage) ? warmup_start_health : start_health)));
         }
         else if (!STAT(FROZEN, player))
             STAT(REVIVE_PROGRESS, player) = 0; // thawing nobody
     }
     else if (STAT(FROZEN, player) == FROZEN_NORMAL) // OK, there is at least one teammate reviving us
     {
         STAT(REVIVE_PROGRESS, player) = bound(0, STAT(REVIVE_PROGRESS, player) + frametime * max(1/60, autocvar_g_freezetag_revive_speed), 1);
         SetResourceExplicit(player, RES_HEALTH, max(1, STAT(REVIVE_PROGRESS, player) * ((warmup_stage) ? warmup_start_health : start_health)));
         if(STAT(REVIVE_PROGRESS, player) >= 1)
         {
             Unfreeze(player, false);
             freezetag_count_alive_players();
             if(n == -1)
             {
                 Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_FREEZETAG_AUTO_REVIVED, autocvar_g_freezetag_frozen_maxtime);
                 Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_FREEZETAG_AUTO_REVIVED, player.netname, autocvar_g_freezetag_frozen_maxtime);
                 return true;
             }
             // EVERY team mate nearby gets a point (even if multiple!)
             for(entity it = reviving_players_first; it; it = it.chain)
             {
                 GameRules_scoring_add(it, FREEZETAG_REVIVALS, +1);
                 GameRules_scoring_add(it, SCORE, +1);
                 nades_GiveBonus(it, autocvar_g_nades_bonus_score_low);
             }
             entity first = reviving_players_first;
             Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_FREEZETAG_REVIVED, first.netname);
             Send_Notification(NOTIF_ONE, first, MSG_CENTER, CENTER_FREEZETAG_REVIVE, player.netname);
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_FREEZETAG_REVIVED, player.netname, first.netname);
         }
         for(entity it = reviving_players_first; it; it = it.chain)
             STAT(REVIVE_PROGRESS, it) = STAT(REVIVE_PROGRESS, player);
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , SetStartItems)
Definition at line 550 of file sv_freezetag.qc.
References cvar(), IT_UNLIMITED_AMMO, IT_UNLIMITED_SUPERWEAPONS, start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_items, warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, and warmup_start_ammo_shells.
 {
     start_items &= ~(IT_UNLIMITED_AMMO | IT_UNLIMITED_SUPERWEAPONS);
     //start_health       = warmup_start_health       = cvar("g_lms_start_health");
     //start_armorvalue   = warmup_start_armorvalue   = cvar("g_lms_start_armor");
     start_ammo_shells  = warmup_start_ammo_shells  = cvar("g_lms_start_ammo_shells");
     start_ammo_nails   = warmup_start_ammo_nails   = cvar("g_lms_start_ammo_nails");
     start_ammo_rockets = warmup_start_ammo_rockets = cvar("g_lms_start_ammo_rockets");
     start_ammo_cells   = warmup_start_ammo_cells   = cvar("g_lms_start_ammo_cells");
     start_ammo_plasma  = warmup_start_ammo_plasma  = cvar("g_lms_start_ammo_plasma");
     start_ammo_fuel    = warmup_start_ammo_fuel    = cvar("g_lms_start_ammo_fuel");
 }
MUTATOR_HOOKFUNCTION (ft , HavocBot_ChooseRole)
Definition at line 563 of file sv_freezetag.qc.
References CS(), entity(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), IS_DEAD, jointime, M_ARGV, random(), and time.
 {
     entity bot = M_ARGV(0, entity);
     if (!IS_DEAD(bot))
     {
         if (random() < 0.5)
             bot.havocbot_role = havocbot_role_ft_freeing;
         else
             bot.havocbot_role = havocbot_role_ft_offense;
     }
     // if bots spawn all at once assign them a more appropriated role after a while
     if (time < CS(bot).jointime + 1)
         bot.havocbot_role_timeout = time + 10 + random() * 10;
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , TeamBalance_CheckAllowedTeams , CBC_ORDER_EXCLUSIVE)
Definition at line 582 of file sv_freezetag.qc.
References freezetag_teams, and M_ARGV.
 {
     M_ARGV(0, float) = freezetag_teams;
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , SetWeaponArena)
Definition at line 588 of file sv_freezetag.qc.
References autocvar_g_freezetag_weaponarena, and M_ARGV.
 {
     if(M_ARGV(0, string) == "0" || M_ARGV(0, string) == "")
         M_ARGV(0, string) = autocvar_g_freezetag_weaponarena;
 }
MUTATOR_HOOKFUNCTION (ft , FragCenterMessage)
Definition at line 594 of file sv_freezetag.qc.
References CS(), entity(), FROZEN_NORMAL, GetResource(), IS_BOT_CLIENT, M_ARGV, ping, RES_ARMOR, and RES_HEALTH.
 {
     entity frag_attacker = M_ARGV(0, entity);
     entity frag_target = M_ARGV(1, entity);
     //float frag_deathtype = M_ARGV(2, float);
     int kill_count_to_attacker = M_ARGV(3, int);
     int kill_count_to_target = M_ARGV(4, int);
     if(STAT(FROZEN, frag_target) == FROZEN_NORMAL)
         return; // target was already frozen, so this is just pushing them off the cliff
     Send_Notification(NOTIF_ONE, frag_attacker, MSG_CHOICE, CHOICE_FRAG_FREEZE, frag_target.netname, kill_count_to_attacker, (IS_BOT_CLIENT(frag_target) ? -1 : CS(frag_target).ping));
     Send_Notification(NOTIF_ONE, frag_target, MSG_CHOICE, CHOICE_FRAGGED_FREEZE, frag_attacker.netname, kill_count_to_target,
         GetResource(frag_attacker, RES_HEALTH), GetResource(frag_attacker, RES_ARMOR), (IS_BOT_CLIENT(frag_attacker) ? -1 : CS(frag_attacker).ping));
     return true;
 }
MUTATOR_HOOKFUNCTION (ft , SV_ParseServerCommand)
Definition at line 612 of file sv_freezetag.qc.
References cmd_name, M_ARGV, round_handler_IsActive, round_handler_IsRoundStarted, and shuffleteams_on_reset_map.
 {
     string cmd_name = M_ARGV(0, string);
     if (cmd_name == "shuffleteams")
         shuffleteams_on_reset_map = !(round_handler_IsActive() && !round_handler_IsRoundStarted());
     return false;
 }
void nades_Clear (entity)
Referenced by freezetag_CheckWinner(), and freezetag_getWinnerTeam().
void nades_GiveBonus (entity player, float score)
Referenced by freezetag_getWinnerTeam(), and MUTATOR_HOOKFUNCTION().
void (entity this)
Referenced by freezetag_isEliminated().
Variable Documentation
float autocvar_g_freezetag_frozen_maxtime
Definition at line 5 of file sv_freezetag.qc.
Referenced by freezetag_Freeze(), and MUTATOR_HOOKFUNCTION().
float autocvar_g_freezetag_revive_clearspeed
Definition at line 6 of file sv_freezetag.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_freezetag_round_timelimit
Definition at line 7 of file sv_freezetag.qc.
Referenced by freezetag_CheckWinner(), and freezetag_Initialize().
int autocvar_g_freezetag_teams_override
Definition at line 9 of file sv_freezetag.qc.
Referenced by freezetag_Initialize().
float autocvar_g_freezetag_warmup
Definition at line 10 of file sv_freezetag.qc.
Referenced by freezetag_CheckWinner(), and freezetag_Initialize().