Xonotic: common/mutators/mutator/itemstime/itemstime.qc File Reference
itemstime.qc File Reference
#include "itemstime.qh"
Macros
#define hud_panel_itemstime_hidebig false
Functions
bool Item_ItemsTime_Allow (GameItem it)
bool Item_ItemsTime_SpectatorOnly (GameItem it)
REGISTER_MUTATOR (itemstime, true)
Macro Definition Documentation
hud_panel_itemstime_hidebig
#define hud_panel_itemstime_hidebig false
Definition at line 53 of file itemstime.qc.
Referenced by Item_ItemsTime_SpectatorOnly().
Function Documentation
Item_ItemsTime_Allow()
bool Item_ItemsTime_Allow (GameItem it)
Definition at line 64 of file itemstime.qc.
References autocvar__hud_configure, autocvar_hud_progressbar_alpha, blink(), bound(), CBC_ORDER_LAST, ceil(), ClientConnect(), color, count, DRAWFLAG_NORMAL, drawpic_aspect_skin, drawpic_aspect_skin_expanding(), drawstring_aspect(), entity(), eX, floor(), FOREACH, FOREACH_CLIENT, ftos(), g_items, hud_configure_menu_open, HUD_GetRowCount(), HUD_ItemsTime(), HUD_Panel_DrawBg, HUD_Panel_DrawProgressBar(), HUD_Panel_LoadCvars(), HUD_Scale_Enable(), HUD_Write_Cvar, if(), IL_EACH, IS_PLAYER, IS_REAL_CLIENT, Item_ItemsTime_Allow(), Item_ItemsTime_SetTime(), Item_ItemsTime_SetTimesForAllPlayers(), Item_ItemsTime_SpectatorOnly(), Item_ItemsTime_UpdateTime(), M_ARGV, GameItem::m_id, max(), MUTATOR_HOOKFUNCTION, panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, precache_pic(), REGISTRY_MAX, spectatee_status, STATIC_INIT, time, vec2, vector(), warmup_stage, and WEPSET_SUPERWEAPONS.
Referenced by Item_ItemsTime_Allow(), Item_Respawn(), Item_ScheduleRespawnIn(), and Item_Think().
 {
     return (false
     || it.instanceOfPowerup
     || Item_ItemsTime_SpectatorOnly(it)
     );
 }
Item_ItemsTime_SpectatorOnly()
bool Item_ItemsTime_SpectatorOnly (GameItem it)
Definition at line 56 of file itemstime.qc.
References hud_panel_itemstime_hidebig.
Referenced by Item_ItemsTime_Allow(), Item_RespawnCountdown(), and Item_Think().
 {
     return (false
     || it == ITEM_ArmorMega     || (it == ITEM_ArmorBig && !hud_panel_itemstime_hidebig)
     || it == ITEM_HealthMega    || (it == ITEM_HealthBig && !hud_panel_itemstime_hidebig)
     );
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (itemstime , true)