Xonotic: menu/xonotic/dialog_settings_misc_reset.qc File Reference
dialog_settings_misc_reset.qc File Reference
#include "dialog_settings_misc_reset.qh"
#include "textlabel.qh"
#include "commandbutton.qh"
#include "button.qh"
Functions
void XonoticResetDialog_fill (entity me)
Function Documentation
void XonoticResetDialog_fill (entity me)
Definition at line 7 of file dialog_settings_misc_reset.qc.
References Dialog_Close(), entity(), makeXonoticButton(), makeXonoticCommandButton(), and makeXonoticTextLabel().
 {
     entity e;
     me.TR(me);
         me.TD(me, 1, 2, makeXonoticTextLabel(0.5, _("Are you sure you want to reset all settings?")));
     me.TR(me);
         me.TD(me, 1, 2, makeXonoticTextLabel(0.5, _("This will create a backup config in your data directory")));
     me.TR(me);
     me.TR(me);
         me.TD(me, 1, 1, e = makeXonoticCommandButton(_("Yes"), '1 0 0', "saveconfig backup.cfg\n;\n exec default.cfg\n", 0));
         me.TD(me, 1, 1, e = makeXonoticButton(_("No"), '0 1 0'));
             e.onClick = Dialog_Close;
             e.onClickEntity = me;
 }