Xonotic: XonoticListBox Class Reference
XonoticListBox Class Reference
Public Member Functions
ATTRIB (MenuItem, parent, entity)
ATTRIB (MenuItem, tooltip, string)
ATTRIB (ListBox, src, string)
virtual void clickListBoxItem ()
virtual void configureListBox ()
virtual void configureXonoticListBox ()
virtual void destroy ()
virtual void doubleClickListBoxItem ()
virtual void draw ()
virtual void drawListBoxItem ()
virtual void focusedItemChangeNotify ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void getFirstFullyVisibleItemAtScrollPos ()
virtual void getItemAtPos ()
virtual void getItemHeight ()
virtual void getItemStart ()
virtual void getLastFullyVisibleItemAtScrollPos ()
virtual void getTotalHeight ()
virtual void hideNotify ()
virtual void isScrolling ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void scrollToItem ()
virtual void setFocusedItem ()
virtual void setSelected ()
virtual void showNotify ()
virtual void toString ()
virtual void updateControlTopBottom ()
Public Attributes
float allowFocusSound = 1
float alphaBG = SKINALPHA_LISTBOX_BACKGROUND
vector color = SKINCOLOR_SCROLLBAR_N
vector color2 = SKINCOLOR_SCROLLBAR_S
vector colorBG = SKINCOLOR_LISTBOX_BACKGROUND
vector colorC = SKINCOLOR_SCROLLBAR_C
vector colorF = SKINCOLOR_SCROLLBAR_F
float controlBottom = 0
float controlTop = 0
float controlWidth = 0
vector dragScrollPos = '0 0 0'
float focusable = 1
float focused = 0
int focusedItem = -1
float focusedItemAlpha = 0.3
float fontSize = SKINFONTSIZE_NORMAL
vector itemAbsSize = '0 0 0'
float itemHeight = 0
float lastClickedItem = -1
float lastClickedTime = 0
float mouseMoveOffset = -1
float needScrollToItem = -1
float nItems = 42
vector origin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
float rowsPerItem = 1
float scrollbarWidth = SKINWIDTH_SCROLLBAR
float scrollPos = 0
float scrollPosTarget = 0
int selectedItem = 0
bool selectionDoesntMatter = false
vector size = '0 0 0'
string src = SKINGFX_SCROLLBAR
vector tolerance = '2 0.2 0'
Detailed Description
Definition at line 4 of file listbox.qh.
Member Function Documentation
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
ListBox::ATTRIB (ListBox , src , string) inherited
virtual void ListBox::clickListBoxItem () virtual inherited
Reimplemented in XonoticGametypeList, and XonoticMapList.
virtual void ListBox::configureListBox () virtual inherited
virtual void XonoticListBox::configureXonoticListBox () virtual
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void ListBox::doubleClickListBoxItem () virtual inherited
Reimplemented in XonoticLanguageList, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, XonoticPlayList, XonoticSkinList, XonoticSoundList, XonoticMapList, XonoticStatsList, XonoticCampaignList, XonoticServerList, and XonoticKeyBinder.
virtual void ListBox::draw () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticScreenshotList, XonoticHUDSkinList, XonoticPlayList, XonoticWeaponsList, XonoticCampaignList, XonoticCreditsList, XonoticGametypeList, XonoticMapList, and XonoticServerList.
virtual void ListBox::drawListBoxItem () virtual inherited
Reimplemented in XonoticRegisteredSettingsList, XonoticScrollPanel, XonoticScreenshotList, XonoticDemoList, XonoticHUDSkinList, XonoticPlayList, XonoticWeaponsList, XonoticCampaignList, XonoticCreditsList, XonoticGametypeList, XonoticMapList, XonoticServerList, XonoticSkinList, XonoticSoundList, XonoticStatsList, XonoticCvarList, XonoticKeyBinder, XonoticLanguageList, and XonoticPlayerList.
virtual void ListBox::focusedItemChangeNotify () virtual inherited
Reimplemented in XonoticRegisteredSettingsList, XonoticRegisteredSettingsList, XonoticServerList, and XonoticGametypeList.
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void ListBox::focusLeave () virtual inherited
Reimplemented from MenuItem.
virtual void ListBox::getFirstFullyVisibleItemAtScrollPos () virtual inherited
virtual void ListBox::getItemAtPos () virtual inherited
Reimplemented in XonoticServerList, and XonoticScrollPanel.
virtual void ListBox::getItemHeight () virtual inherited
Reimplemented in XonoticServerList, and XonoticScrollPanel.
virtual void ListBox::getItemStart () virtual inherited
Reimplemented in XonoticServerList, and XonoticScrollPanel.
virtual void ListBox::getLastFullyVisibleItemAtScrollPos () virtual inherited
virtual void ListBox::getTotalHeight () virtual inherited
Reimplemented in XonoticServerList, and XonoticScrollPanel.
void MenuItem::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void ListBox::isScrolling () virtual inherited
virtual void ListBox::keyDown () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticLanguageList, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, XonoticPlayList, XonoticSkinList, XonoticMapList, XonoticGametypeList, XonoticCampaignList, XonoticKeyBinder, XonoticSoundList, XonoticServerList, XonoticStatsList, XonoticWeaponsList, XonoticCreditsList, and XonoticCvarList.
void MenuItem::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void ListBox::mouseDrag () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticPlayList, and XonoticWeaponsList.
virtual void ListBox::mouseMove () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticServerList.
void ListBox::mousePress () virtual inherited
Reimplemented from MenuItem.
Definition at line 211 of file listbox.qc.
References max(), min(), and pressed.
     {
         if (pos.x < 0) return false;
         if (pos.y < 0) return false;
         if (pos.x >= 1) return false;
         if (pos.y >= 1) return false;
         this.dragScrollPos = pos;
         this.updateControlTopBottom(this);
         if (pos.x >= 1 - this.controlWidth)
         {
             // if hit, set this.pressed, otherwise scroll by one page
             if (pos.y < this.controlTop)
             {
                 // page up
                 this.scrollPosTarget = max(this.scrollPosTarget - 1, 0);
             }
             else if (pos.y > this.controlBottom)
             {
                 // page down
                 this.scrollPosTarget = min(this.scrollPosTarget + 1, this.getTotalHeight(this) - 1);
             }
             else
             {
                 this.pressed = 1;
                 this.pressOffset = pos.y;
                 this.previousValue = this.scrollPos;
             }
         }
         else
         {
             // continue doing that while dragging (even when dragging outside). When releasing, forward the click to the then selected item.
             this.pressed = 2;
             // an item has been clicked. Select it, ...
             this.setSelected(this, this.getItemAtPos(this, this.scrollPos + pos.y));
             this.setFocusedItem(this, this.selectedItem);
         }
         return true;
     }
virtual void ListBox::mouseRelease () virtual inherited
Reimplemented from MenuItem.
Reimplemented in XonoticCvarList.
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticListBox::resizeNotify () virtual
Reimplemented from ListBox.
Reimplemented in XonoticRegisteredSettingsList, XonoticScrollPanel, XonoticMapList, XonoticCampaignList, XonoticServerList, XonoticWeaponsList, XonoticCreditsList, XonoticGametypeList, XonoticKeyBinder, XonoticCvarList, XonoticDemoList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayList, XonoticScreenshotList, XonoticSkinList, XonoticSoundList, XonoticStatsList, and XonoticPlayerList.
virtual void ListBox::scrollToItem () virtual inherited
virtual void ListBox::setFocusedItem () virtual inherited
virtual void ListBox::setSelected () virtual inherited
Reimplemented in XonoticServerList, XonoticRegisteredSettingsList, XonoticCvarList, XonoticScrollPanel, XonoticCampaignList, XonoticKeyBinder, XonoticGametypeList, XonoticLanguageList, and XonoticScreenshotList.
void MenuItem::showNotify () virtual inherited
Reimplemented in Container, Slider, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, InputBox, XonoticSoundList, XonoticDamageTextSettings, XonoticStatsList, XonoticPlayerModelSelector, XonoticTab, XonoticCvarList, XonoticKeyBinder, Button, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
Definition at line 56 of file item.qc.
     {}
void MenuItem::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void ListBox::updateControlTopBottom () virtual inherited
Member Data Documentation
float ListBox::allowFocusSound = 1 inherited
Definition at line 19 of file listbox.qh.
float XonoticListBox::alphaBG = SKINALPHA_LISTBOX_BACKGROUND
Definition at line 17 of file listbox.qh.
vector XonoticListBox::color = SKINCOLOR_SCROLLBAR_N
Definition at line 12 of file listbox.qh.
vector XonoticListBox::color2 = SKINCOLOR_SCROLLBAR_S
Definition at line 14 of file listbox.qh.
vector XonoticListBox::colorBG = SKINCOLOR_LISTBOX_BACKGROUND
Definition at line 16 of file listbox.qh.
vector XonoticListBox::colorC = SKINCOLOR_SCROLLBAR_C
Definition at line 15 of file listbox.qh.
vector XonoticListBox::colorF = SKINCOLOR_SCROLLBAR_F
Definition at line 13 of file listbox.qh.
float ListBox::controlBottom = 0 inherited
Definition at line 34 of file listbox.qh.
float ListBox::controlTop = 0 inherited
Definition at line 33 of file listbox.qh.
float ListBox::controlWidth = 0 inherited
Definition at line 35 of file listbox.qh.
vector ListBox::dragScrollPos = '0 0 0' inherited
Definition at line 36 of file listbox.qh.
float ListBox::focusable = 1 inherited
Definition at line 14 of file listbox.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
int ListBox::focusedItem = -1 inherited
Definition at line 15 of file listbox.qh.
float ListBox::focusedItemAlpha = 0.3 inherited
Definition at line 16 of file listbox.qh.
float XonoticListBox::fontSize = SKINFONTSIZE_NORMAL
Definition at line 6 of file listbox.qh.
vector ListBox::itemAbsSize = '0 0 0' inherited
Definition at line 48 of file listbox.qh.
float ListBox::itemHeight = 0 inherited
Definition at line 47 of file listbox.qh.
float ListBox::lastClickedItem = -1 inherited
Definition at line 52 of file listbox.qh.
float ListBox::lastClickedTime = 0 inherited
Definition at line 53 of file listbox.qh.
float ListBox::mouseMoveOffset = -1 inherited
Definition at line 18 of file listbox.qh.
float ListBox::needScrollToItem = -1 inherited
Definition at line 26 of file listbox.qh.
float ListBox::nItems = 42 inherited
Definition at line 46 of file listbox.qh.
vector ListBox::origin = '0 0 0' inherited
Definition at line 22 of file listbox.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float ListBox::pressed = 0 inherited
Definition at line 29 of file listbox.qh.
float ListBox::pressOffset = 0 inherited
Definition at line 30 of file listbox.qh.
float ListBox::previousValue = 0 inherited
Definition at line 28 of file listbox.qh.
float XonoticListBox::rowsPerItem = 1
Definition at line 10 of file listbox.qh.
float XonoticListBox::scrollbarWidth = SKINWIDTH_SCROLLBAR
Definition at line 7 of file listbox.qh.
float ListBox::scrollPos = 0 inherited
Definition at line 23 of file listbox.qh.
float ListBox::scrollPosTarget = 0 inherited
Definition at line 24 of file listbox.qh.
int ListBox::selectedItem = 0 inherited
Definition at line 20 of file listbox.qh.
bool ListBox::selectionDoesntMatter = false inherited
Definition at line 37 of file listbox.qh.
vector ListBox::size = '0 0 0' inherited
Definition at line 21 of file listbox.qh.
string XonoticListBox::src = SKINGFX_SCROLLBAR
Definition at line 8 of file listbox.qh.
vector XonoticListBox::tolerance = '2 0.2 0'
Definition at line 9 of file listbox.qh.
The documentation for this class was generated from the following file:
menu/xonotic/listbox.qh