Xonotic: server/weapons/accuracy.qc File Reference
accuracy.qc File Reference
#include "accuracy.qh"
#include <server/mutators/_mod.qh>
#include <common/constants.qh>
#include <common/net_linked.qh>
#include <common/teams.qh>
#include <common/util.qh>
#include <common/weapons/_all.qh>
Functions
void accuracy_add (entity this, Weapon w, int fired, int hit)
int accuracy_byte (float n, float d)
bool accuracy_canbegooddamage (entity attacker)
void accuracy_free (entity e)
void accuracy_init (entity e)
bool accuracy_isgooddamage (entity attacker, entity targ)
void accuracy_resend (entity e)
bool accuracy_send (entity this, entity to, int sf)
Variables
float fired_time
Function Documentation
void accuracy_add (entity this, Weapon w, int fired, int hit)
Definition at line 64 of file accuracy.qc.
References accuracy, accuracy_byte(), CS(), entity(), FOREACH_CLIENT, IS_INDEPENDENT_PLAYER, IS_SPEC, Weapon::m_id, time, and WEP_FIRST.
Referenced by Fire_AddDamage(), fireBullet(), RadiusDamageForSource(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     if (IS_INDEPENDENT_PLAYER(this)) return;
     entity a = CS(this).accuracy;
     if (!a) return;
     if (!hit && !fired) return;
     if (w == WEP_Null) return;
     int wepid = w.m_id;
     wepid -= WEP_FIRST;
     int b = accuracy_byte(a.accuracy_hit[wepid], a.accuracy_fired[wepid]);
     if (hit)    a.accuracy_hit  [wepid] += hit;
     if (fired)  a.accuracy_fired[wepid] += fired;
     if (hit && STAT(HIT_TIME, a) != time) { // only run this once per frame
         a.accuracy_cnt_hit[wepid] += 1;
         STAT(HIT_TIME, a) = time;
     }
     if (fired && a.fired_time != time) { // only run this once per frame
         a.accuracy_cnt_fired[wepid] += 1;
         a.fired_time = time;
     }
     if (b == accuracy_byte(a.accuracy_hit[wepid], a.accuracy_fired[wepid])) return; // no change
     int sf = 1 << (wepid % 24);
     a.SendFlags |= sf;
     FOREACH_CLIENT(IS_SPEC(it) && it.enemy == this, { CS(it).accuracy.SendFlags |= sf; });
 }
int accuracy_byte (float n, float d)
Definition at line 10 of file accuracy.qc.
References rint().
Referenced by accuracy_add(), and accuracy_send().
 {
     if (n <= 0) return 0;
     if (n > d) return 255;
     return 1 + rint(n * 100.0 / d);
 }
bool accuracy_canbegooddamage (entity attacker)
Definition at line 114 of file accuracy.qc.
References warmup_stage.
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     return !warmup_stage;
 }
void accuracy_free (entity e)
Definition at line 49 of file accuracy.qc.
References CS().
Referenced by ClientState_detach().
 {
     delete(CS(e).accuracy);
 }
void accuracy_init (entity e)
Definition at line 41 of file accuracy.qc.
References accuracy, accuracy_send(), CS(), entity(), and new_pure.
Referenced by ClientState_attach().
 {
     entity a = CS(e).accuracy = new_pure(accuracy);
     a.owner = e;
     a.drawonlytoclient = e;
     Net_LinkEntity(a, false, 0, accuracy_send);
 }
bool accuracy_isgooddamage (entity attacker, entity targ)
Definition at line 93 of file accuracy.qc.
References IS_CLIENT, IS_DEAD, MUT_ACCADD_INVALID, MUT_ACCADD_VALID, MUTATOR_CALLHOOK, SAME_TEAM, time, and warmup_stage.
Referenced by Fire_AddDamage(), fireBullet(), PlayerDamage(), and RadiusDamageForSource().
 {
     int mutator_check = MUTATOR_CALLHOOK(AccuracyTargetValid, attacker, targ);
     if (warmup_stage) return false;
     if (game_stopped) return false;
     // damage to dead/frozen players is good only if it happens in the frame they get killed / frozen
     // so that stats for weapons that shoot multiple projectiles per shot are properly counted
     if (IS_DEAD(targ) && time > targ.death_time) return false;
     if (STAT(FROZEN, targ) && time > targ.freeze_time) return false;
     if (SAME_TEAM(attacker, targ)) return false;
     if (mutator_check == MUT_ACCADD_INVALID) return true;
     if (mutator_check != MUT_ACCADD_VALID) return false;
     if (!IS_CLIENT(targ)) return false;
     return true;
 }
void accuracy_resend (entity e)
Definition at line 55 of file accuracy.qc.
References CS().
Referenced by PutObserverInServer(), PutPlayerInServer(), and SpectateSet().
 {
     CS(e).accuracy.SendFlags = 0xFFFFFF;
 }
bool accuracy_send (entity this, entity to, int sf)
Definition at line 17 of file accuracy.qc.
References accuracy_byte(), autocvar_sv_accuracy_data_share, CS(), entity(), IS_SPEC, owner, WEP_FIRST, WEP_LAST, and WriteByte().
Referenced by accuracy_init().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_ACCURACY);
     entity a = this.owner;
     if (IS_SPEC(a)) a = a.enemy;
     a = CS(a).accuracy;
     if (to != a.owner)
         if (!autocvar_sv_accuracy_data_share && !CS(a.owner).cvar_cl_accuracy_data_share)
             sf = 0;
     // note: zero sendflags can never be sent... so we can use that to say that we send no accuracy!
     WriteInt24_t(MSG_ENTITY, sf);
     if (sf == 0) return true;
     // note: we know that client and server agree about SendFlags...
     int f = 1;
     for (int w = 0; w <= WEP_LAST - WEP_FIRST; ++w) {
         if (sf & f) WriteByte(MSG_ENTITY, accuracy_byte(a.accuracy_hit[w], a.accuracy_fired[w]));
         f = (f == 0x800000) ? 1 : f * 2;
     }
     return true;
 }
Variable Documentation
float fired_time
Definition at line 62 of file accuracy.qc.