Xonotic: ClanArena Class Reference
ClanArena Class Reference
Public Member Functions
ClanArena ()
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_configuremenu ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isForcedSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
virtual void m_setTeams ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
int m_id = 0
string m_legacydefaults = "10 20 0"
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 302 of file mapinfo.qh.
Constructor & Destructor Documentation
ClanArena::ClanArena () inline
Definition at line 303 of file mapinfo.qh.
     {
         this.gametype_init(this, _("Clan Arena"),"ca","g_ca",true,true,"","timelimit=20 pointlimit=10 teams=2 leadlimit=6",_("Kill all enemy teammates to win the round"));
     }
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
virtual void Gametype::describe () inline virtual inherited
Definition at line 75 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual inherited
Definition at line 81 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual inherited
Definition at line 87 of file mapinfo.qh.
References cons(), ENDCLASS, m_flags, MAPINFO_TYPE_ALL, and REGISTRY.
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = gteamplay;
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = gusepoints;
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void ClanArena::m_configuremenu () inline virtual
Reimplemented from Gametype.
Definition at line 330 of file mapinfo.qh.
References ATTRIB, HUD_Mod_CA(), TC, and vector().
     {
         TC(Gametype, this);
         returns(menu, _("Frag limit:"),      5,  100,  5, "fraglimit_override",        "g_ca_teams_override",          _("The amount of frags needed before the match will end"));
     }
virtual void Gametype::m_generate_mapinfo () inline virtual inherited
Reimplemented in Invasion, NexBall, Onslaught, Assault, Domination, CaptureTheFlag, RaceCTS, and Race.
Definition at line 53 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
virtual void ClanArena::m_isAlwaysSupported () inline virtual
Reimplemented from Gametype.
Definition at line 320 of file mapinfo.qh.
     {
         if(spawnpoints >= 8 && diameter > 4096)
             return true;
         return false;
     }
virtual void Gametype::m_isForcedSupported () inline virtual inherited
Reimplemented in Duel, and TeamDeathmatch.
Definition at line 65 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_isTwoBaseMode () inline virtual inherited
Reimplemented in NexBall, Assault, CaptureTheFlag, and Race.
Definition at line 57 of file mapinfo.qh.
     {
         return false;
     }
virtual void ClanArena::m_parse_mapinfo () inline virtual
Reimplemented from Gametype.
Definition at line 307 of file mapinfo.qh.
References cvar_defstring(), and cvar_set().
     {
         if (!k) {
             cvar_set("g_ca_teams", cvar_defstring("g_ca_teams"));
             return true;
         }
         switch (k) {
             case "teams":
                 cvar_set("g_ca_teams", v);
                 return true;
         }
         return false;
     }
virtual void ClanArena::m_setTeams () inline virtual
Definition at line 326 of file mapinfo.qh.
References cvar_set().
     {
         cvar_set("g_ca_teams", sa);
     }
Member Data Documentation
bool Gametype::frags = true inherited
does this gametype use a point limit?
Definition at line 35 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
int Gametype::items = 0 inherited
game type ID
Definition at line 25 of file mapinfo.qh.
int Gametype::m_id = 0 inherited
Definition at line 23 of file mapinfo.qh.
Referenced by MapInfo_LoadMapSettings_SaveGameType().
string ClanArena::m_legacydefaults = "10 20 0"
Definition at line 338 of file mapinfo.qh.
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 33 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/mapinfo.qh