Xonotic: common/mutators/mutator/dodging/sv_dodging.qc File Reference
sv_dodging.qc File Reference
#include "sv_dodging.qh"
Macros
#define PHYS_DODGING g_dodging
#define PHYS_DODGING_AIR autocvar_sv_dodging_air_dodging
#define PHYS_DODGING_AIR_MAXSPEED autocvar_sv_dodging_air_maxspeed
#define PHYS_DODGING_DELAY autocvar_sv_dodging_delay
#define PHYS_DODGING_DISTANCE_THRESHOLD autocvar_sv_dodging_wall_distance_threshold
#define PHYS_DODGING_FROZEN_DOUBLETAP autocvar_sv_dodging_frozen_doubletap
#define PHYS_DODGING_HEIGHT_THRESHOLD autocvar_sv_dodging_height_threshold
#define PHYS_DODGING_HORIZ_FORCE_FASTEST autocvar_sv_dodging_horiz_force_fastest
#define PHYS_DODGING_HORIZ_FORCE_FROZEN autocvar_sv_dodging_horiz_force_frozen
#define PHYS_DODGING_HORIZ_FORCE_SLOWEST autocvar_sv_dodging_horiz_force_slowest
#define PHYS_DODGING_HORIZ_SPEED_MAX autocvar_sv_dodging_horiz_speed_max
#define PHYS_DODGING_HORIZ_SPEED_MIN autocvar_sv_dodging_horiz_speed_min
#define PHYS_DODGING_MAXSPEED autocvar_sv_dodging_maxspeed
#define PHYS_DODGING_RAMP_TIME autocvar_sv_dodging_ramp_time
#define PHYS_DODGING_UP_SPEED autocvar_sv_dodging_up_speed
#define PHYS_DODGING_WALL autocvar_sv_dodging_wall_dodging
#define X(dir)
#define X(COND, BTN, RESULT)
Functions
float determine_force (entity player)
bool is_close_to_ground (entity this, float threshold)
bool is_close_to_wall (entity this, float threshold)
MUTATOR_HOOKFUNCTION (dodging, PlayerPhysics)
void PM_dodging (entity this)
bool PM_dodging_checkpressedkeys (entity this)
Variables
float dodging_action
vector dodging_direction
float dodging_force_remaining
float dodging_force_total
float dodging_single_action
float last_BACKWARD_KEY_time
float last_dodging_time
float last_FORWARD_KEY_time
float last_LEFT_KEY_time
float last_RIGHT_KEY_time
Macro Definition Documentation
#define PHYS_DODGING g_dodging
Definition at line 5 of file sv_dodging.qc.
#define PHYS_DODGING_AIR autocvar_sv_dodging_air_dodging
Definition at line 18 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
#define PHYS_DODGING_AIR_MAXSPEED autocvar_sv_dodging_air_maxspeed
Definition at line 20 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_DELAY autocvar_sv_dodging_delay
Definition at line 6 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_DISTANCE_THRESHOLD autocvar_sv_dodging_wall_distance_threshold
Definition at line 7 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_FROZEN_DOUBLETAP autocvar_sv_dodging_frozen_doubletap
Definition at line 8 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_HEIGHT_THRESHOLD autocvar_sv_dodging_height_threshold
Definition at line 9 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_HORIZ_FORCE_FASTEST autocvar_sv_dodging_horiz_force_fastest
Definition at line 13 of file sv_dodging.qc.
Referenced by determine_force().
#define PHYS_DODGING_HORIZ_FORCE_FROZEN autocvar_sv_dodging_horiz_force_frozen
Definition at line 14 of file sv_dodging.qc.
Referenced by determine_force().
#define PHYS_DODGING_HORIZ_FORCE_SLOWEST autocvar_sv_dodging_horiz_force_slowest
Definition at line 12 of file sv_dodging.qc.
Referenced by determine_force().
#define PHYS_DODGING_HORIZ_SPEED_MAX autocvar_sv_dodging_horiz_speed_max
Definition at line 11 of file sv_dodging.qc.
Referenced by determine_force().
#define PHYS_DODGING_HORIZ_SPEED_MIN autocvar_sv_dodging_horiz_speed_min
Definition at line 10 of file sv_dodging.qc.
Referenced by determine_force().
#define PHYS_DODGING_MAXSPEED autocvar_sv_dodging_maxspeed
Definition at line 19 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define PHYS_DODGING_RAMP_TIME autocvar_sv_dodging_ramp_time
Definition at line 15 of file sv_dodging.qc.
Referenced by PM_dodging().
#define PHYS_DODGING_UP_SPEED autocvar_sv_dodging_up_speed
Definition at line 16 of file sv_dodging.qc.
Referenced by PM_dodging().
#define PHYS_DODGING_WALL autocvar_sv_dodging_wall_dodging
Definition at line 17 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
#define X (dir)
Value:
tracebox(this.origin, this.mins, this.maxs, this.origin + threshold * dir, true, this); \
    if (trace_fraction < 1 && !(trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY)) \
        return true;
Definition at line 110 of file sv_dodging.qc.
Referenced by is_close_to_ground(), is_close_to_wall(), and PM_dodging_checkpressedkeys().
#define X (COND, BTN, RESULT)
Value:
if (mymovement_##COND) {                                                                                \
        /* is this a state change? */                                                                       \
        if(!(PHYS_DODGING_PRESSED_KEYS(this) & KEY_##BTN) || frozen_no_doubletap) {                         \
            tap_direction_##RESULT;                                                                         \
            if ((time - this.last_##BTN##_KEY_time) < PHYS_DODGING_TIMEOUT(this) || frozen_no_doubletap) {  \
                dodge_detected = true;                                                                      \
            } else if(PHYS_INPUT_BUTTON_DODGE(this)) {                                                      \
                dodge_detected = true;                                                                      \
            }                                                                                               \
            this.last_##BTN##_KEY_time = time;                                                               \
        }                                                                                                   \
    }
Definition at line 110 of file sv_dodging.qc.
Function Documentation
float determine_force (entity player)
Definition at line 136 of file sv_dodging.qc.
References map_bound_ranges(), PHYS_DODGING_HORIZ_FORCE_FASTEST, PHYS_DODGING_HORIZ_FORCE_FROZEN, PHYS_DODGING_HORIZ_FORCE_SLOWEST, PHYS_DODGING_HORIZ_SPEED_MAX, PHYS_DODGING_HORIZ_SPEED_MIN, PHYS_FROZEN, vec2, and vlen().
Referenced by PM_dodging_checkpressedkeys().
{
     if (PHYS_FROZEN(player)) return PHYS_DODGING_HORIZ_FORCE_FROZEN;
     float horiz_vel = vlen(vec2(player.velocity));
     return map_bound_ranges(horiz_vel,
                             PHYS_DODGING_HORIZ_SPEED_MIN, PHYS_DODGING_HORIZ_SPEED_MAX,
                             PHYS_DODGING_HORIZ_FORCE_SLOWEST, PHYS_DODGING_HORIZ_FORCE_FASTEST);
 }
bool is_close_to_ground (entity this, float threshold)
Definition at line 126 of file sv_dodging.qc.
References IS_ONGROUND, v_up, and X.
Referenced by PM_dodging_checkpressedkeys().
 {
     if (IS_ONGROUND(this)) return true;
     X(-v_up); // necessary for dodging down a slope using doubletap (using `+dodge` works anyway)
     return false;
 }
bool is_close_to_wall (entity this, float threshold)
Definition at line 116 of file sv_dodging.qc.
References v_forward, v_right, and X.
Referenced by PM_dodging_checkpressedkeys().
 {
     X(v_right);
     X(-v_right);
     X(v_forward);
     X(-v_forward);
     return false;
 }
MUTATOR_HOOKFUNCTION (dodging , PlayerPhysics)
Definition at line 288 of file sv_dodging.qc.
References entity(), M_ARGV, and PM_dodging().
 {
     entity player = M_ARGV(0, entity);
 #ifdef CSQC
     PM_dodging_GetPressedKeys(player);
 #endif
     PM_dodging(player);
 }
void PM_dodging (entity this)
Definition at line 210 of file sv_dodging.qc.
References angles, ANIMACTION_JUMP, animdecide_setaction(), CH_PLAYER, dodging_action, dodging_direction, dodging_force_remaining, dodging_force_total, dodging_single_action, IS_DEAD, min(), PHYS_DODGING_AIR, PHYS_DODGING_RAMP_TIME, PHYS_DODGING_UP_SPEED, UNSET_ONGROUND, v_angle, v_forward, v_right, v_up, velocity, VOICETYPE_PLAYERSOUND, VOL_BASE, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     // can't use return value from PM_dodging_checkpressedkeys because they're called from different hooks
     if (!this.dodging_action) return;
     // when swimming or dead, no dodging allowed..
     if (this.waterlevel >= WATERLEVEL_SWIMMING || IS_DEAD(this))
     {
         this.dodging_action = 0;
         this.dodging_direction.x = 0;
         this.dodging_direction.y = 0;
         return;
     }
     // make sure v_up, v_right and v_forward are sane
     if(PHYS_DODGING_AIR)
         makevectors(this.v_angle);
     else
         makevectors(this.angles);
     // fraction of the force to apply each frame
     // if we have e.g. 0.5 sec ramptime and a frametime of 0.25, then the ramp code
     // will be called ramp_time/frametime times = 2 times. so, we need to
     // add 0.5 * the total speed each frame until the dodge action is done..
     float common_factor = PHYS_DODGING_FRAMETIME / PHYS_DODGING_RAMP_TIME;
     // NOTE: depending on cl_netfps the client may (and probably will) send more input frames during each server frame
     // but common_factor uses server frame rate so players with higher cl_netfps will ramp slightly faster
     float velocity_increase = min(common_factor * this.dodging_force_total, this.dodging_force_remaining);
     this.dodging_force_remaining -= velocity_increase;
     this.velocity += this.dodging_direction.x * velocity_increase * v_forward
                    + this.dodging_direction.y * velocity_increase * v_right;
     // the up part of the dodge is a single shot action
     if (this.dodging_single_action == 1)
     {
         UNSET_ONGROUND(this);
         this.velocity += PHYS_DODGING_UP_SPEED * v_up;
 #ifdef SVQC
         if (autocvar_sv_dodging_sound)
             PlayerSound(this, playersound_jump, CH_PLAYER, VOL_BASE, VOICETYPE_PLAYERSOUND);
         animdecide_setaction(this, ANIMACTION_JUMP, true);
 #endif
         this.dodging_single_action = 0;
     }
     if(this.dodging_force_remaining <= 0)
     {
         // reset state so next dodge can be done correctly
         this.dodging_action = 0;
         this.dodging_direction.x = 0;
         this.dodging_direction.y = 0;
     }
 }
bool PM_dodging_checkpressedkeys (entity this)
Definition at line 145 of file sv_dodging.qc.
References angles, determine_force(), dodging_action, dodging_direction, dodging_force_remaining, dodging_force_total, dodging_single_action, is_close_to_ground(), is_close_to_wall(), last_dodging_time, PHYS_DODGING_AIR, PHYS_DODGING_AIR_MAXSPEED, PHYS_DODGING_DELAY, PHYS_DODGING_DISTANCE_THRESHOLD, PHYS_DODGING_FROZEN, PHYS_DODGING_FROZEN_DOUBLETAP, PHYS_DODGING_HEIGHT_THRESHOLD, PHYS_DODGING_MAXSPEED, PHYS_DODGING_WALL, PHYS_FROZEN, sqrt(), time, vdist, vector(), velocity, and X.
 {
     bool frozen_dodging = (PHYS_FROZEN(this) && PHYS_DODGING_FROZEN(this));
     bool frozen_no_doubletap = (frozen_dodging && !PHYS_DODGING_FROZEN_DOUBLETAP);
     float tap_direction_x = 0;
     float tap_direction_y = 0;
     bool dodge_detected = false;
     vector mymovement = PHYS_CS(this).movement;
     #define X(COND,BTN,RESULT)                                                                              \
     if (mymovement_##COND) {                                                                                \
         /* is this a state change? */                                                                       \
         if(!(PHYS_DODGING_PRESSED_KEYS(this) & KEY_##BTN) || frozen_no_doubletap) {                         \
             tap_direction_##RESULT;                                                                         \
             if ((time - this.last_##BTN##_KEY_time) < PHYS_DODGING_TIMEOUT(this) || frozen_no_doubletap) {  \
                 dodge_detected = true;                                                                      \
             } else if(PHYS_INPUT_BUTTON_DODGE(this)) {                                                      \
                 dodge_detected = true;                                                                      \
             }                                                                                               \
             this.last_##BTN##_KEY_time = time;                                                              \
         }                                                                                                   \
     }
     X(x < 0, BACKWARD,  x--);
     X(x > 0, FORWARD,   x++);
     X(y < 0, LEFT,      y--);
     X(y > 0, RIGHT,     y++);
     #undef X
     if (!dodge_detected) return false;
     // this check has to be after checking keys:
     // the first key press of the double tap is allowed to be before dodging delay,
     // only the second has to be after, otherwise +dodge gives an advantage because typical repress time is 0.1 s
     // or higher which means players using +dodge would be able to do it more often
     if ((time - this.last_dodging_time) < PHYS_DODGING_DELAY)
         return false;
     makevectors(this.angles);
     bool can_dodge = (is_close_to_ground(this, PHYS_DODGING_HEIGHT_THRESHOLD) && (PHYS_DODGING_MAXSPEED == 0 || vdist(this.velocity, <, PHYS_DODGING_MAXSPEED)));
     bool can_wall_dodge = (PHYS_DODGING_WALL && is_close_to_wall(this, PHYS_DODGING_DISTANCE_THRESHOLD));
     bool can_air_dodge = (PHYS_DODGING_AIR && (PHYS_DODGING_AIR_MAXSPEED == 0 || vdist(this.velocity, <, PHYS_DODGING_AIR_MAXSPEED)));
     if (!can_dodge && !can_wall_dodge && !can_air_dodge) return false;
     this.last_dodging_time = time;
     this.dodging_action = 1;
     this.dodging_single_action = 1;
     this.dodging_force_total = determine_force(this);
     this.dodging_force_remaining = this.dodging_force_total;
     this.dodging_direction.x = tap_direction_x;
     this.dodging_direction.y = tap_direction_y;
     // normalize the dodging_direction vector.. (unlike UT99) XD
     float length = sqrt(this.dodging_direction.x ** 2 + this.dodging_direction.y ** 2);
     this.dodging_direction.x = this.dodging_direction.x / length;
     this.dodging_direction.y = this.dodging_direction.y / length;
     return true;
 }
Variable Documentation
float dodging_action
Definition at line 83 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
vector dodging_direction
Definition at line 95 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
float dodging_force_remaining
Definition at line 104 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
float dodging_force_total
Definition at line 102 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
float dodging_single_action
Definition at line 86 of file sv_dodging.qc.
Referenced by PM_dodging(), and PM_dodging_checkpressedkeys().
float last_BACKWARD_KEY_time
Definition at line 90 of file sv_dodging.qc.
float last_dodging_time
Definition at line 99 of file sv_dodging.qc.
Referenced by PM_dodging_checkpressedkeys().
float last_FORWARD_KEY_time
Definition at line 89 of file sv_dodging.qc.
float last_LEFT_KEY_time
Definition at line 91 of file sv_dodging.qc.
float last_RIGHT_KEY_time
Definition at line 92 of file sv_dodging.qc.