Xonotic: DamageText Class Reference
DamageText Class Reference
Public Member Functions
DamageText (int _group, vector _origin, bool _screen_coords, int _health, int _armor, int _potential_damage, int _deathtype, bool _friendlyfire)
~DamageText ()
void DamageText_draw2d (DamageText this)
void DamageText_update (DamageText this, vector _origin, int _health, int _armor, int _potential_damage, int _deathtype)
void (DamageText) draw2d
Public Attributes
float alpha = autocvar_cl_damagetext_alpha_start
float fade_rate = 0
float hit_time = 0
int m_armordamage = 0
vector m_color = autocvar_cl_damagetext_color
vector m_color_friendlyfire = autocvar_cl_damagetext_friendlyfire_color
int m_deathtype = 0
bool m_friendlyfire = false
int m_group = 0
int m_healthdamage = 0
int m_potential_damage = 0
bool m_screen_coords = false
float m_shrink_rate = 0
float m_size = autocvar_cl_damagetext_size_min
string text = string_null
Static Public Attributes
static int screen_count = 0
static DamageText screen_first = NULL
Detailed Description
Definition at line 43 of file cl_damagetext.qc.
Constructor & Destructor Documentation
DamageText::DamageText (int _group, vector _origin, bool _screen_coords, int _health, int _armor, int _potential_damage, int _deathtype, bool _friendlyfire) inline
Definition at line 176 of file cl_damagetext.qc.
References CONSTRUCT, fade_rate, g_drawables_2d, and IL_PUSH().
{
         CONSTRUCT(DamageText);
         this.m_group = _group;
         this.m_friendlyfire = _friendlyfire;
         this.m_screen_coords = _screen_coords;
         if (_screen_coords) {
             this.fade_rate = 1 / autocvar_cl_damagetext_2d_alpha_lifetime;
             this.m_shrink_rate = 1 / autocvar_cl_damagetext_2d_size_lifetime;
         } else {
             this.fade_rate = 1 / autocvar_cl_damagetext_alpha_lifetime;
             this.m_shrink_rate = 0;
         }
         DamageText_update(this, _origin, _health, _armor, _potential_damage, _deathtype);
         IL_PUSH(g_drawables_2d, this);
     }
DamageText::~DamageText () inline
Definition at line 192 of file cl_damagetext.qc.
References ENDCLASS, NULL, and strfree.
{
         strfree(this.text);
         if (this == DamageText_screen_first) {
             // start from 0 offset again, hopefully, others (if any) will have faded away by now
             DamageText_screen_first = NULL;
             DamageText_screen_count = 0;
         }
     }
Member Function Documentation
void DamageText::DamageText_draw2d (DamageText this) inline
Definition at line 63 of file cl_damagetext.qc.
References ATTRIB, DEATH_WEAPONOF, DRAWFLAG_NORMAL, drawfontscale, fade_rate, origin, project_3d_to_2d(), size, time, view_angles, and Weapon::wpcolor.
{
         float since_hit = time - this.hit_time;
         // can't use `dt = hit_time - prev_update_time` because shrinking wouldn't be linear
         float size = this.m_size - since_hit * this.m_shrink_rate * this.m_size;
         float alpha_ = this.alpha - since_hit * this.fade_rate;
         if (alpha_ <= 0 || size <= 0) {
             delete(this);
             return;
         }
         vector screen_pos;
         if (this.m_screen_coords) {
             screen_pos = this.origin + since_hit * autocvar_cl_damagetext_2d_velocity;
         } else {
             vector forward, right, up;
             MAKE_VECTORS(view_angles, forward, right, up);
             vector world_offset = since_hit * autocvar_cl_damagetext_velocity_world + autocvar_cl_damagetext_offset_world;
             vector world_pos = this.origin + world_offset.x * forward + world_offset.y * right + world_offset.z * up;
             screen_pos = project_3d_to_2d(world_pos) + since_hit * autocvar_cl_damagetext_velocity_screen + autocvar_cl_damagetext_offset_screen;
         }
         screen_pos.y += size / 2;
         if (screen_pos.z >= 0) {
             screen_pos.z = 0;
             vector rgb;
             if (this.m_friendlyfire) {
                 rgb = this.m_color_friendlyfire;
             } else {
                 rgb = this.m_color;
             }
             if (autocvar_cl_damagetext_color_per_weapon) {
                 Weapon w = DEATH_WEAPONOF(this.m_deathtype);
                 if (w != WEP_Null) rgb = w.wpcolor;
             }
             vector drawfontscale_save = drawfontscale;
             drawfontscale = (size / autocvar_cl_damagetext_size_max) * '1 1 0';
             screen_pos.y -= drawfontscale.x * size / 2;
             drawcolorcodedstring2_builtin(screen_pos, this.text, autocvar_cl_damagetext_size_max * '1 1 0', rgb, alpha_, DRAWFLAG_NORMAL);
             drawfontscale = drawfontscale_save;
         }
     }
void DamageText::DamageText_update (DamageText this, vector _origin, int _health, int _armor, int _potential_damage, int _deathtype) inline
Definition at line 107 of file cl_damagetext.qc.
References almost_equals_eps(), alpha, DAMAGETEXT_PRECISION_MULTIPLIER, health, map_bound_ranges(), rint(), setorigin(), strcat(), strcpy, strlen(), strstrofs, substring(), substring_range(), and time.
{
         this.m_healthdamage = _health;
         this.m_armordamage = _armor;
         this.m_potential_damage = _potential_damage;
         this.m_deathtype = _deathtype;
         setorigin(this, _origin);
         if (this.m_screen_coords) {
             this.alpha = autocvar_cl_damagetext_2d_alpha_start;
         } else {
             this.alpha = autocvar_cl_damagetext_alpha_start;
         }
         this.hit_time = time;
         int health = rint(this.m_healthdamage / DAMAGETEXT_PRECISION_MULTIPLIER);
         int armor = rint(this.m_armordamage / DAMAGETEXT_PRECISION_MULTIPLIER);
         int total = rint((this.m_healthdamage + this.m_armordamage) / DAMAGETEXT_PRECISION_MULTIPLIER);
         int potential = rint(this.m_potential_damage / DAMAGETEXT_PRECISION_MULTIPLIER);
         int potential_health = rint((this.m_potential_damage - this.m_armordamage) / DAMAGETEXT_PRECISION_MULTIPLIER);
         bool redundant = almost_equals_eps(this.m_healthdamage + this.m_armordamage, this.m_potential_damage, 5);
         string s = autocvar_cl_damagetext_format;
         s = strreplace("{armor}", (
             (this.m_armordamage == 0 && autocvar_cl_damagetext_format_hide_redundant)
                 ? ""
                 : sprintf("%d", armor)
             ), s);
         s = strreplace("{potential}", (
             (redundant && autocvar_cl_damagetext_format_hide_redundant)
                 ? ""
                 : sprintf("%d", potential)
             ), s);
         s = strreplace("{potential_health}", (
             (redundant && autocvar_cl_damagetext_format_hide_redundant)
                 ? ""
                 : sprintf("%d", potential_health)
             ), s);
         s = strreplace("{health}", (
             (health == potential_health || !autocvar_cl_damagetext_format_verbose)
                 ? sprintf("%d",      health)
                 : sprintf("%d (%d)", health, potential_health)
             ), s);
         s = strreplace("{total}", (
             (total == potential || !autocvar_cl_damagetext_format_verbose)
                 ? sprintf("%d",      total)
                 : sprintf("%d (%d)", total, potential)
             ), s);
         // futureproofing: remove any remaining (unknown) format strings in case we add new ones in the future
         // so players can use them on new servers and still have working damagetext on old ones
         while (true) {
             int opening_pos = strstrofs(s, "{", 0);
             if (opening_pos == -1) break;
             int closing_pos = strstrofs(s, "}", opening_pos);
             if (closing_pos == -1 || closing_pos <= opening_pos) break;
             s = strcat(
                 substring(s, 0, opening_pos),
                 substring_range(s, closing_pos + 1, strlen(s))
             );
         }
         strcpy(this.text, s);
         this.m_size = map_bound_ranges(potential,
             autocvar_cl_damagetext_size_min_damage, autocvar_cl_damagetext_size_max_damage,
             autocvar_cl_damagetext_size_min, autocvar_cl_damagetext_size_max);
     }
DamageText::void (DamageText)
Member Data Documentation
float DamageText::alpha = autocvar_cl_damagetext_alpha_start
Definition at line 47 of file cl_damagetext.qc.
float DamageText::fade_rate = 0
Definition at line 48 of file cl_damagetext.qc.
float DamageText::hit_time = 0
Definition at line 56 of file cl_damagetext.qc.
int DamageText::m_armordamage = 0
Definition at line 53 of file cl_damagetext.qc.
vector DamageText::m_color = autocvar_cl_damagetext_color
Definition at line 44 of file cl_damagetext.qc.
vector DamageText::m_color_friendlyfire = autocvar_cl_damagetext_friendlyfire_color
Definition at line 45 of file cl_damagetext.qc.
int DamageText::m_deathtype = 0
Definition at line 55 of file cl_damagetext.qc.
bool DamageText::m_friendlyfire = false
Definition at line 51 of file cl_damagetext.qc.
int DamageText::m_group = 0
Definition at line 50 of file cl_damagetext.qc.
int DamageText::m_healthdamage = 0
Definition at line 52 of file cl_damagetext.qc.
int DamageText::m_potential_damage = 0
Definition at line 54 of file cl_damagetext.qc.
bool DamageText::m_screen_coords = false
Definition at line 58 of file cl_damagetext.qc.
float DamageText::m_shrink_rate = 0
Definition at line 49 of file cl_damagetext.qc.
float DamageText::m_size = autocvar_cl_damagetext_size_min
Definition at line 46 of file cl_damagetext.qc.
int DamageText::screen_count = 0 static
Definition at line 61 of file cl_damagetext.qc.
DamageText DamageText::screen_first = NULL static
Definition at line 60 of file cl_damagetext.qc.
string DamageText::text = string_null
Definition at line 57 of file cl_damagetext.qc.
The documentation for this class was generated from the following file:
common/mutators/mutator/damagetext/cl_damagetext.qc