Xonotic: menu/xonotic/textslider.qc File Reference
textslider.qc File Reference
#include "textslider.qh"
Functions
entity makeXonoticTextSlider (string theCvar)
entity makeXonoticTextSlider_T (string theCvar, string theTooltip)
void XonoticTextSlider_configureXonoticTextSlider (entity me, string theCvar, string theTooltip)
void XonoticTextSlider_configureXonoticTextSliderValues (entity me)
void XonoticTextSlider_loadCvars (entity me)
void XonoticTextSlider_saveCvars (entity me)
void XonoticTextSlider_setValue (entity me, float val)
void XonoticTextSlider_setValue_noAnim (entity me, float val)
Function Documentation
entity makeXonoticTextSlider (string theCvar)
Definition at line 10 of file textslider.qc.
References makeXonoticTextSlider_T(), and string_null.
Referenced by dialog_hudpanel_common_notoggle(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticHUDExitDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     return makeXonoticTextSlider_T(theCvar, string_null);
 }
entity makeXonoticTextSlider_T (string theCvar, string theTooltip)
Definition at line 3 of file textslider.qc.
References entity(), and NEW.
Referenced by makeXonoticTextSlider(), XonoticAudioSettingsTab_fill(), XonoticEffectsSettingsTab_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameViewSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticServerCreateTab_fill(), and XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticTextSlider);
     me.configureXonoticTextSlider(me, theCvar, theTooltip);
     return me;
 }
void XonoticTextSlider_configureXonoticTextSlider (entity me, string theCvar, string theTooltip)
Definition at line 14 of file textslider.qc.
References setZonedTooltip(), and string_null.
 {
     me.configureSliderVisuals(me, me.fontSize, me.align, me.valueSpace, me.image);
     me.cvarName = (theCvar) ? theCvar : string_null;
     // me.loadCvars(me); // don't load it yet
     setZonedTooltip(me, theTooltip, theCvar);
 }
void XonoticTextSlider_configureXonoticTextSliderValues (entity me)
Definition at line 98 of file textslider.qc.
References string_null.
 {
     me.configureTextSliderValues(me, string_null);
     me.loadCvars(me);
 }
void XonoticTextSlider_loadCvars (entity me)
Definition at line 37 of file textslider.qc.
References argv(), cvar_string(), strcat(), and tokenize_console.
 {
     if (!me.cvarName)
         return;
     float n = tokenize_console(me.cvarName);
     string s = cvar_string(argv(0));
     float i;
     for(i = 1; i < n; ++i)
         s = strcat(s, " ", cvar_string(argv(i)));
     me.setValueFromIdentifier_noAnim(me, s);
     if(me.value < 0 && n > 1)
     {
         // if it failed: check if all cvars have the same value
         // if yes, try its value as 1-word identifier
         for(i = 1; i < n; ++i)
             if(cvar_string(argv(i)) != cvar_string(argv(i-1)))
                 break;
         if(i >= n)
             me.setValueFromIdentifier_noAnim(me, cvar_string(argv(0)));
     }
 }
void XonoticTextSlider_saveCvars (entity me)
Definition at line 59 of file textslider.qc.
References argv(), CheckSendCvars(), cvar_set(), error, strcat(), and tokenize_console.
 {
     if (!me.cvarName)
         return;
     if(me.value >= 0 && me.value < me.nValues)
     {
         float n = tokenize_console(me.cvarName);
         if(n == 1)
         {
             // this is a special case to allow spaces in the identifiers
             cvar_set(argv(0), me.getIdentifier(me));
             CheckSendCvars(me, argv(0));
         }
         else
         {
             float i;
             float m = tokenize_console(strcat(me.cvarName, " ", me.getIdentifier(me)));
             if(m == n + 1)
             {
                 for(i = 0; i < n; ++i)
                 {
                     cvar_set(argv(i), argv(n));
                     CheckSendCvars(me, argv(i));
                 }
             }
             else if(m == n * 2)
             {
                 for(i = 0; i < n; ++i)
                 {
                     cvar_set(argv(i), argv(i + n));
                     CheckSendCvars(me, argv(i));
                 }
             }
             else
                 error("XonoticTextSlider: invalid identifier ", me.getIdentifier(me), " does not match cvar list ", me.cvarName);
         }
     }
 }
void XonoticTextSlider_setValue (entity me, float val)
Definition at line 21 of file textslider.qc.
References SUPER.
 {
     if(val != me.value)
     {
         SUPER(XonoticTextSlider).setValue( me, val );
         me.saveCvars(me);
     }
 }
void XonoticTextSlider_setValue_noAnim (entity me, float val)
Definition at line 29 of file textslider.qc.
References SUPER.
 {
     if(val != me.value)
     {
         SUPER(XonoticTextSlider).setValue_noAnim(me, val);
         me.saveCvars(me);
     }
 }