Xonotic: common/weapons/all.qc File Reference
all.qc File Reference
#include "all.qh"
#include "calculations.qc"
#include "all.inc"
Macros
#define IMPLEMENTATION
#define shotorg_adjust shotorg_adjust_values
#define WEAPONS_ALL_C
Functions
WepSet _WepSet_FromWeapon (int a)
void CL_WeaponEntity_SetModel (entity this, string name, bool _anim)
supported formats:
CLIENT_COMMAND (weapon_find,"Show spawn locations of a weapon")
string GetAmmoPicture (.int ammotype)
vector shotorg_adjust_values (vector vecs, bool y_is_right, bool visual, int algn)
vector shotorg_adjustfromclient (vector vecs, float y_is_right, float algn)
string W_FixWeaponOrder (string order, float complete)
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
string W_FixWeaponOrder_BuildImpulseList (string o)
float W_FixWeaponOrder_BuildImpulseList_cmp (int i, int j, entity pass)
void W_FixWeaponOrder_BuildImpulseList_swap (int i, int j, entity pass)
string W_FixWeaponOrder_ForceComplete (string order)
string W_Model (string w_mdl)
string W_NameWeaponOrder (string order)
string W_NameWeaponOrder_MapFunc (string s)
string W_NumberWeaponOrder (string order)
string W_NumberWeaponOrder_MapFunc (string s)
void W_RandomWeapons (entity e, float n)
string W_Sound (string w_snd)
string W_UndeprecateName (string s)
void w_whereis (Weapon this)
Variables
float W_FixWeaponOrder_BuildImpulseList_buf [Weapons_MAX]
string W_FixWeaponOrder_BuildImpulseList_order
Macro Definition Documentation
#define IMPLEMENTATION
Definition at line 53 of file all.qc.
#define shotorg_adjust shotorg_adjust_values
Definition at line 337 of file all.qc.
Referenced by CL_WeaponEntity_SetModel().
#define WEAPONS_ALL_C
Definition at line 2 of file all.qc.
Function Documentation
WepSet _WepSet_FromWeapon (int a)
Definition at line 59 of file all.qc.
References power2of(), and WEP_FIRST.
Referenced by STATIC_INIT().
 {
     a -= WEP_FIRST;
     if (Weapons_MAX > 24)
         if (a >= 24)
         {
             a -= 24;
             if (Weapons_MAX > 48)
                 if (a >= 24)
                 {
                     a -= 24;
                     return '0 0 1' * power2of(a);
                 }
             return '0 1 0' * power2of(a);
         }
     return '1 0 0' * power2of(a);
 }
void CL_WeaponEntity_SetModel (entity this, string name, bool _anim)
supported formats:
simple animated model, muzzle flash handling on h_ model: h_tuba.dpm, h_tuba.dpm.framegroups - invisible model controlling the animation tags: shot = muzzle end (shot origin, also used for muzzle flashes) shell = casings ejection point (must be on the right hand side of the gun) weapon = attachment for v_tuba.md3 v_tuba.md3 - first and third person model g_tuba.md3 - pickup model
simple animated model, muzzle flash handling on v_ model: h_tuba.dpm, h_tuba.dpm.framegroups - invisible model controlling the animation tags: weapon = attachment for v_tuba.md3 v_tuba.md3 - first and third person model tags: shot = muzzle end (shot origin, also used for muzzle flashes) shell = casings ejection point (must be on the right hand side of the gun) g_tuba.md3 - pickup model
fully animated model, muzzle flash handling on h_ model: h_tuba.dpm, h_tuba.dpm.framegroups - animated first person model tags: shot = muzzle end (shot origin, also used for muzzle flashes) shell = casings ejection point (must be on the right hand side of the gun) handle = corresponding to the origin of v_tuba.md3 (used for muzzle flashes) v_tuba.md3 - third person model g_tuba.md3 - pickup model
fully animated model, muzzle flash handling on v_ model: h_tuba.dpm, h_tuba.dpm.framegroups - animated first person model tags: shot = muzzle end (shot origin) shell = casings ejection point (must be on the right hand side of the gun) v_tuba.md3 - third person model tags: shot = muzzle end (for muzzle flashes) g_tuba.md3 - pickup model
writes: this.origin, this.angles this.weaponchild this.movedir, this.view_ofs attachment stuff anim stuff to free: call again with "" remove the ent
Definition at line 390 of file all.qc.
References angles, anim_fire1, anim_fire2, anim_idle, anim_reload, animfixfps(), compressShotOrigin(), decompressShotOrigin(), frame, gettagindex, LOG_WARNINGF, MASK_NORMAL, model, movedir, NULL, oldorigin, owner, renderflags, RF_VIEWMODEL, setanim, shotorg_adjust, spawnorigin, strcat(), vector, view_ofs, viewmodelforclient, W_Model(), weaponchild, and wframe.
Referenced by CL_Weapon_GetShotOrg(), CL_Weaponentity_Think(), and viewmodel_draw().
 {
     if (name == "")
     {
         this.model = "";
         if (this.weaponchild) remove(this.weaponchild);
         this.weaponchild = NULL;
         this.movedir = '0 0 0';
         this.spawnorigin = '0 0 0';
         this.oldorigin = '0 0 0';
         this.anim_fire1  = '0 1 0.01';
         this.anim_fire2  = '0 1 0.01';
         this.anim_idle   = '0 1 0.01';
         this.anim_reload = '0 1 0.01';
     }
     else
     {
         // if there is a child entity, hide it until we're sure we use it
         if (this.weaponchild) this.weaponchild.model = "";
         _setmodel(this, W_Model(strcat("v_", name, ".md3")));
         int v_shot_idx;  // used later
         (v_shot_idx = gettagindex(this, "shot")) || (v_shot_idx = gettagindex(this, "tag_shot"));
         _setmodel(this, W_Model(strcat("h_", name, ".iqm")));
         // preset some defaults that work great for renamed zym files (which don't need an animinfo)
         this.anim_fire1  = animfixfps(this, '0 1 0.01', '0 0 0');
         this.anim_fire2  = animfixfps(this, '1 1 0.01', '0 0 0');
         this.anim_idle   = animfixfps(this, '2 1 0.01', '0 0 0');
         this.anim_reload = animfixfps(this, '3 1 0.01', '0 0 0');
         // if we have a "weapon" tag, let's attach the v_ model to it ("invisible hand" style model)
         // if we don't, this is a "real" animated model
         string t;
         if ((t = "weapon", gettagindex(this, t)) || (t = "tag_weapon", gettagindex(this, t)))
         {
             if (!this.weaponchild)
             {
                 this.weaponchild = new(weaponchild);
 #ifdef CSQC
                 this.weaponchild.drawmask = MASK_NORMAL;
                 this.weaponchild.renderflags |= RF_VIEWMODEL;
 #endif
             }
             _setmodel(this.weaponchild, W_Model(strcat("v_", name, ".md3")));
             setsize(this.weaponchild, '0 0 0', '0 0 0');
             setattachment(this.weaponchild, this, t);
         }
         else
         {
             if (this.weaponchild) remove(this.weaponchild);
             this.weaponchild = NULL;
         }
         setsize(this, '0 0 0', '0 0 0');
         setorigin(this, '0 0 0');
         this.angles = '0 0 0';
         this.frame = 0;
 #ifdef SVQC
         this.viewmodelforclient = NULL;
 #else
         this.renderflags &= ~RF_VIEWMODEL;
 #endif
         if (v_shot_idx)  // v_ model attached to invisible h_ model
         {
             this.movedir = gettaginfo(this.weaponchild, v_shot_idx);
         }
         else
         {
             int idx;
             if ((idx = gettagindex(this, "shot")) || (idx = gettagindex(this, "tag_shot")))
             {
                 this.movedir = gettaginfo(this, idx);
             }
             else
             {
                 LOG_WARNINGF("weapon model %s does not support the 'shot' tag, will display shots TOTALLY wrong\n",
                     this.model);
                 this.movedir = '0 0 0';
             }
         }
         {
             int idx = 0;
             // v_ model attached to invisible h_ model
             if (this.weaponchild
                 && ((idx = gettagindex(this.weaponchild, "shell")) || (idx = gettagindex(this.weaponchild, "tag_shell"))))
             {
                 this.spawnorigin = gettaginfo(this.weaponchild, idx);
             }
             else if ((idx = gettagindex(this, "shell")) || (idx = gettagindex(this, "tag_shell")))
             {
                 this.spawnorigin = gettaginfo(this, idx);
             }
             else
             {
                 LOG_WARNINGF("weapon model %s does not support the 'shell' tag, will display casings wrong\n",
                     this.model);
                 this.spawnorigin = this.movedir;
             }
         }
         if (v_shot_idx)
         {
             this.oldorigin = '0 0 0';  // use regular attachment
         }
         else
         {
             int idx;
             if (this.weaponchild)
                 (idx = gettagindex(this, "weapon")) || (idx = gettagindex(this, "tag_weapon"));
             else
                 (idx = gettagindex(this, "handle")) || (idx = gettagindex(this, "tag_handle"));
             if (idx)
             {
                 this.oldorigin = this.movedir - gettaginfo(this, idx);
             }
             else
             {
                 LOG_WARNINGF(
                     "weapon model %s does not support the 'handle' tag "
                     "and neither does the v_ model support the 'shot' tag, "
                     "will display muzzle flashes TOTALLY wrong\n",
                     this.model);
                 this.oldorigin = '0 0 0';  // there is no way to recover from this
             }
         }
 #ifdef SVQC
         this.viewmodelforclient = this.owner;
 #else
         this.renderflags |= RF_VIEWMODEL;
 #endif
     }
     this.view_ofs = '0 0 0';
     if (this.movedir.x >= 0)
     {
         int algn = STAT(GUNALIGN, this.owner);
         vector v = this.movedir;
         this.movedir = shotorg_adjust(v, false, false, algn);
         this.view_ofs = shotorg_adjust(v, false, true, algn) - v;
     }
     int compressed_shotorg = compressShotOrigin(this.movedir);
     // make them match perfectly
 #ifdef SVQC
     this.movedir = decompressShotOrigin(this.owner.stat_shotorg = compressed_shotorg);
 #else
     this.movedir = decompressShotOrigin(compressed_shotorg);
 #endif
     this.spawnorigin += this.view_ofs;  // offset the casings origin by the same amount
     // check if an instant weapon switch occurred
     setorigin(this, this.view_ofs);
     if (!_anim) return;
     // reset animstate now
     this.wframe = WFRAME_IDLE;
     setanim(this, this.anim_idle, true, false, true);
 }
CLIENT_COMMAND (weapon_find , "Show spawn locations of a weapon")
Definition at line 614 of file all.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, FOREACH, LOG_INFO, LOG_INFOF, and w_whereis().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             string s = argv(1);
             if (s == "all")
             {
                 FOREACH(Weapons, it != WEP_Null, w_whereis(it));
                 return;
             }
             if (s == "unowned")
             {
                 FOREACH(Weapons, it != WEP_Null && !(STAT(WEAPONS) & it.m_wepset), w_whereis(it));
                 return;
             }
             FOREACH(Weapons, it != WEP_Null && it.netname == s,
             {
                 w_whereis(it);
                 return;
             });
         }
         default:
         {
             LOG_INFOF("Incorrect parameters for ^2%s^7\n", "weapon_find");
         }
         case CMD_REQUEST_USAGE:
         {
             LOG_INFO("\nUsage:^3 cl_cmd weapon_find weapon\n");
             LOG_INFO("  Where 'weapon' is the lowercase weapon name, 'all' or 'unowned'.\n");
             return;
         }
     }
 }
string GetAmmoPicture (.int ammotype)
Definition at line 216 of file all.qc.
References ammo_cells, ammo_fuel, ammo_nails, ammo_plasma, ammo_rockets, and ammo_shells.
Referenced by DrawAmmoItem(), and W_DecreaseAmmo().
 {
     switch (ammotype)
     {
         case ammo_shells:  return ITEM_Shells.m_icon;
         case ammo_nails:   return ITEM_Bullets.m_icon;
         case ammo_rockets: return ITEM_Rockets.m_icon;
         case ammo_cells:   return ITEM_Cells.m_icon;
         case ammo_plasma:  return ITEM_Plasma.m_icon;
         case ammo_fuel:    return ITEM_JetpackFuel.m_icon;
         default: return "";  // wtf, no ammo type?
     }
 }
vector shotorg_adjust_values (vector vecs, bool y_is_right, bool visual, int algn)
Definition at line 301 of file all.qc.
References autocvar_g_shootfromcenter, autocvar_g_shootfromeye, autocvar_g_shootfromfixedorigin, shotorg_adjustfromclient(), stov(), and vector.
Referenced by GrappleHookInit().
 {
 #ifdef SVQC
     string s;
 #endif
     if (visual)
     {
         vecs = shotorg_adjustfromclient(vecs, y_is_right, algn);
     }
 #ifdef SVQC
     else if (autocvar_g_shootfromeye)
     {
         vecs.y = vecs.z = 0;
     }
     else if (autocvar_g_shootfromcenter)
     {
         vecs.y = 0;
         vecs.z -= 2;
     }
     else if ((s = autocvar_g_shootfromfixedorigin) != "")
     {
         vector v = stov(s);
         if (y_is_right) v.y = -v.y;
         if (v.x != 0) vecs.x = v.x;
         vecs.y = v.y;
         vecs.z = v.z;
     }
 #endif
     else  // just do the same as top
     {
         vecs = shotorg_adjustfromclient(vecs, y_is_right, algn);
     }
     return vecs;
 }
vector shotorg_adjustfromclient (vector vecs, float y_is_right, float algn)
Definition at line 279 of file all.qc.
Referenced by shotorg_adjust_values().
 {
     switch (algn)
     {
         default:
         case 3:
             // right alignment
             break;
         case 4:
             // left
             vecs.y = -vecs.y;
             break;
         case 1:
         case 2:
             // center
             vecs.y = 0;
             vecs.z -= 2;
             break;
     }
     return vecs;
 }
string W_FixWeaponOrder (string order, float complete)
Definition at line 101 of file all.qc.
References fixPriorityList(), WEP_FIRST, WEP_IMPULSE_BEGIN, and WEP_LAST.
Referenced by LocalCommand_sendcvar(), W_FixWeaponOrder_AllowIncomplete(), W_FixWeaponOrder_ForceComplete(), and XonoticWeaponsList_draw().
 {
     return fixPriorityList(order, WEP_FIRST, WEP_LAST, WEP_IMPULSE_BEGIN - WEP_FIRST, complete);
 }
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
Definition at line 184 of file all.qc.
References W_FixWeaponOrder().
Referenced by GetCvars().
 {
     return W_FixWeaponOrder(order, 0);
 }
string W_FixWeaponOrder_BuildImpulseList (string o)
Definition at line 169 of file all.qc.
References ftos(), heapsort(), NULL, strcat(), string_null, substring(), W_FixWeaponOrder_BuildImpulseList_cmp(), W_FixWeaponOrder_BuildImpulseList_swap(), WEP_FIRST, and WEP_LAST.
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     int i;
     W_FixWeaponOrder_BuildImpulseList_order = o;
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST] = i;
     heapsort(WEP_LAST - WEP_FIRST + 1, W_FixWeaponOrder_BuildImpulseList_swap, W_FixWeaponOrder_BuildImpulseList_cmp,
         NULL);
     o = "";
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         o = strcat(o, " ", ftos(W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST]));
     W_FixWeaponOrder_BuildImpulseList_order = string_null;
     return substring(o, 1, -1);
 }
float W_FixWeaponOrder_BuildImpulseList_cmp (int i, int j, entity pass)
Definition at line 154 of file all.qc.
References Weapon::impulse, strcat(), strstrofs, and Weapons_from.
Referenced by W_FixWeaponOrder_BuildImpulseList().
 {
     int si = W_FixWeaponOrder_BuildImpulseList_buf[i];
     Weapon e1 = Weapons_from(si);
     int sj = W_FixWeaponOrder_BuildImpulseList_buf[j];
     Weapon e2 = Weapons_from(sj);
     int d = (e1.impulse + 9) % 10 - (e2.impulse + 9) % 10;
     if (d != 0) return -d;  // high impulse first!
     return strstrofs(strcat(" ", W_FixWeaponOrder_BuildImpulseList_order, " "),
         sprintf(" %d ", si), 0)
            -
            strstrofs(strcat(" ", W_FixWeaponOrder_BuildImpulseList_order, " "),
         sprintf(" %d ", sj), 0)
     ;  // low char index first!
 }
void W_FixWeaponOrder_BuildImpulseList_swap (int i, int j, entity pass)
Definition at line 147 of file all.qc.
Referenced by W_FixWeaponOrder_BuildImpulseList().
 {
     float h;
     h = W_FixWeaponOrder_BuildImpulseList_buf[i];
     W_FixWeaponOrder_BuildImpulseList_buf[i] = W_FixWeaponOrder_BuildImpulseList_buf[j];
     W_FixWeaponOrder_BuildImpulseList_buf[j] = h;
 }
string W_FixWeaponOrder_ForceComplete (string order)
Definition at line 189 of file all.qc.
References cvar_defstring(), W_FixWeaponOrder(), and W_NumberWeaponOrder().
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     if (order == "") order = W_NumberWeaponOrder(cvar_defstring("cl_weaponpriority"));
     return W_FixWeaponOrder(order, 1);
 }
string W_Model (string w_mdl)
Definition at line 271 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
Referenced by CL_ExteriorWeaponentity_Think(), and CL_WeaponEntity_SetModel().
 {
     string output = strcat("models/weapons/", w_mdl);
     MUTATOR_CALLHOOK(WeaponModel, w_mdl, output);
     return M_ARGV(1, string);
 }
string W_NameWeaponOrder (string order)
Definition at line 129 of file all.qc.
References mapPriorityList(), and W_NameWeaponOrder_MapFunc().
Referenced by XonoticWeaponsList_draw().
 {
     return mapPriorityList(order, W_NameWeaponOrder_MapFunc);
 }
string W_NameWeaponOrder_MapFunc (string s)
Definition at line 105 of file all.qc.
References entity(), stof(), and Weapons_from.
Referenced by W_NameWeaponOrder().
 {
     int i = stof(s);
     if (s == "0" || i)
     {
         entity wi = Weapons_from(i);
         if (wi != WEP_Null) return wi.netname;
     }
     return s;
 }
string W_NumberWeaponOrder (string order)
Definition at line 140 of file all.qc.
References mapPriorityList(), and W_NumberWeaponOrder_MapFunc().
Referenced by bot_custom_weapon_priority_setup(), HUD_Weapons(), LocalCommand_sendcvar(), W_FixWeaponOrder_ForceComplete(), XonoticWeaponsList_draw(), and XonoticWeaponsList_toString().
 {
     return mapPriorityList(order, W_NumberWeaponOrder_MapFunc);
 }
string W_NumberWeaponOrder_MapFunc (string s)
Definition at line 133 of file all.qc.
References FOREACH, ftos(), stof(), and W_UndeprecateName().
Referenced by W_NumberWeaponOrder().
 {
     if (s == "0" || stof(s)) return s;
     s = W_UndeprecateName(s);
     FOREACH(Weapons, it != WEP_Null && it.netname == s, return ftos(i));
     return s;
 }
void W_RandomWeapons (entity e, float n)
Definition at line 195 of file all.qc.
References FOREACH, RandomSelection_Add(), RandomSelection_chosen_ent, RandomSelection_Init(), string_null, and WepSet_FromWeapon.
Referenced by GiveFrags().
 {
     int i;
     WepSet remaining;
     WepSet result;
     remaining = e.weapons;
     result = '0 0 0';
     for (i = 0; i < n; ++i)
     {
         RandomSelection_Init();
         FOREACH(Weapons, it != WEP_Null, {
             if (remaining & (it.m_wepset))
                 RandomSelection_Add(it, 0, string_null, 1, 1);
         });
         Weapon w = RandomSelection_chosen_ent;
         result |= WepSet_FromWeapon(w);
         remaining &= ~WepSet_FromWeapon(w);
     }
     e.weapons = result;
 }
string W_Sound (string w_snd)
Definition at line 260 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
 {
     string output = strcat("weapons/", w_snd);
 #ifdef SVQC
         MUTATOR_CALLHOOK(WeaponSound, w_snd, output);
         return M_ARGV(1, string);
 #else
         return output;
 #endif
 }
string W_UndeprecateName (string s)
Definition at line 116 of file all.qc.
Referenced by W_NumberWeaponOrder_MapFunc().
 {
     switch (s)
     {
         case "nex": return "vortex";
         case "rocketlauncher": return "devastator";
         case "laser": return "blaster";
         case "minstanex": return "vaporizer";
         case "grenadelauncher": return "mortar";
         case "uzi": return "machinegun";
         default: return s;
     }
 }
void w_whereis (Weapon this)
Definition at line 608 of file all.qc.
References WriteRegistered.
Referenced by CLIENT_COMMAND().
 {
     int channel = MSG_C2S;
     WriteHeader(channel, w_whereis);
     WriteRegistered(Weapons, channel, this);
 }
Variable Documentation
float W_FixWeaponOrder_BuildImpulseList_buf[Weapons_MAX]
Definition at line 145 of file all.qc.
string W_FixWeaponOrder_BuildImpulseList_order
Definition at line 146 of file all.qc.