Xonotic: server/main.qh File Reference
main.qh File Reference
Functions
void dedicated_print (string input)
print(), but only print if the server is not local
bool expr_evaluate (string s)
Evaluate an expression of the form: [+ | -]? [var[op]val | [op]var | val | var] ...
void main ()
void remove_except_protected (entity e)
void remove_safely (entity e)
void remove_unsafely (entity e)
Variables
float contents_damagetime
bool iscreature
vector oldvelocity
float remove_except_protected_forbidden
float serverframetime
float serverprevtime
float servertime
float species
float watersound_finished
Function Documentation
void dedicated_print (string input)
print(), but only print if the server is not local
Definition at line 176 of file main.qc.
References print(), and server_is_dedicated.
Referenced by GameLogEcho(), and Say().
 {
     if (server_is_dedicated) print(input);
 }
bool expr_evaluate (string s)
Evaluate an expression of the form: [+ | -]? [var[op]val | [op]var | val | var] ...
+: all must match. this is the default -: one must NOT match
var>x var<x var>="">=x var<=x var==x var!=x var===x var!==x
Definition at line 48 of file cvar.qh.
References argv(), BINOP, cvar(), cvar_string(), ERASEABLE, ftos(), stof(), str2chr, substring(), tokenize_console, v, and X.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     bool ret = false;
     if (str2chr(s, 0) == '+') {
         s = substring(s, 1, -1);
     } else if (str2chr(s, 0) == '-') {
         ret = true;
         s = substring(s, 1, -1);
     }
     bool expr_fail = false;
     for (int i = 0, n = tokenize_console(s); i < n; ++i) {
         int o;
         string k, v;
         s = argv(i);
         #define X(expr) \
             if (expr) \
                 continue; \
             expr_fail = true; \
             break;
         #define BINOP(op, len, expr) \
             if ((o = strstrofs(s, op, 0)) >= 0) { \
                 k = substring(s, 0, o); \
                 v = substring(s, o + len, -1); \
                 X(expr); \
             }
         BINOP(">=", 2, cvar(k) >= stof(v));
         BINOP("<=", 2, cvar(k) <= stof(v));
         BINOP(">",  1, cvar(k) >  stof(v));
         BINOP("<",  1, cvar(k) <  stof(v));
         BINOP("==", 2, cvar(k) == stof(v));
         BINOP("!=", 2, cvar(k) != stof(v));
         BINOP("===", 3, cvar_string(k) == v);
         BINOP("!==", 3, cvar_string(k) != v);
         {
             k = s;
             bool b = true;
             if (str2chr(k, 0) == '!') {
                 k = substring(s, 1, -1);
                 b = false;
             }
             float f = stof(k);
             bool isnum = ftos(f) == k;
             X(boolean(isnum ? f : cvar(k)) == b);
         }
         #undef BINOP
         #undef X
     }
     if (!expr_fail) {
         ret = !ret;
     }
     // now ret is true if we want to keep the item, and false if we want to get rid of it
     return ret;
 }
void main ()
Definition at line 390 of file main.qc.
 {
 }
void remove_except_protected (entity e)
Definition at line 212 of file main.qc.
References error().
Referenced by InitializeEntitiesRun().
 {
     if(e.remove_except_protected_forbidden)
         error("not allowed to remove this at this point");
     builtin_remove(e);
 }
void remove_safely (entity e)
Definition at line 226 of file main.qc.
References make_safe_for_remove().
Referenced by spawnfunc().
 {
     make_safe_for_remove(e);
     builtin_remove(e);
 }
void remove_unsafely (entity e)
Definition at line 219 of file main.qc.
References error().
Referenced by InitializeEntitiesRun(), spawnfunc(), and StartFrame().
 {
     if(e.classname == "spike")
         error("Removing spikes is forbidden (crylink bug), please report");
     builtin_remove(e);
 }
Variable Documentation
float contents_damagetime
Definition at line 29 of file main.qh.
Referenced by CreatureFrame_hotliquids(), and CreatureFrame_Liquids().
bool iscreature
Definition at line 26 of file main.qh.
Referenced by CopyBody(), Monster_Spawn(), PutObserverInServer(), PutPlayerInServer(), vehicle_initialize(), and vehicles_spawn().
vector oldvelocity
Definition at line 22 of file main.qh.
Referenced by CheatImpulse(), CreatureFrame_FallDamage(), PutObserverInServer(), PutPlayerInServer(), and vehicles_impact().
float remove_except_protected_forbidden
Definition at line 6 of file main.qh.
float serverframetime
Definition at line 20 of file main.qh.
Referenced by Drag_Update(), and StartFrame().
float serverprevtime
Definition at line 20 of file main.qh.
float servertime
Definition at line 20 of file main.qh.
Referenced by anticheat_fixangle(), anticheat_init(), anticheat_physics(), anticheat_report_to_eventlog(), anticheat_report_to_playerstats(), CSQC_Ent_Update(), Drag_Update(), NET_HANDLE(), and StartFrame().
float species
Definition at line 27 of file main.qh.
Referenced by CopyBody().
float watersound_finished
Definition at line 24 of file main.qh.
Referenced by CreatureFrame_hotliquids().