Xonotic: XonoticGameSettingsTab Class Reference
XonoticGameSettingsTab Class Reference
Public Member Functions
XonoticGameSettingsTab ()
virtual void _changeFocusXY ()
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
virtual void addItemSimple ()
ATTRIB (Tab, title, string)
ATTRIB (InputContainer, mouseFocusedChild, entity)
ATTRIB (XonoticTab, backgroundImage, string)
ATTRIB (Tab, backgroundImage, string)
ATTRIB (XonoticTab, titleTooltip, string)
ATTRIB (MenuItem, parent, entity)
ATTRIB (Container, firstChild, entity)
ATTRIB (Container, lastChild, entity)
ATTRIB (Container, focusedChild, entity)
ATTRIB (MenuItem, tooltip, string)
ATTRIB (Container, savedFocus, entity)
ATTRIB (Dialog, closeButton, entity)
ATTRIB (XonoticGameSettingsTab, currentItem, entity)
ATTRIB (Dialog, backgroundImage, string)
ATTRIB (Dialog, closeButtonImage, string)
ATTRIB (Dialog, frame, entity)
virtual void close ()
virtual void configureDialog ()
virtual void destroy ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void fill ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void gotoRC ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFirstColumn ()
virtual void setFocus ()
virtual void showNotify ()
virtual void TD ()
virtual void TDempty ()
virtual void TDNoMargin ()
virtual void topicChangeNotify ()
virtual void toString ()
virtual void TR ()
Public Attributes
float allowFocusSound = 0
float borderLines = 1
float closable = 0
vector color = '1 0.5 1'
float columns = 6.5
float columnSpacing = SKINMARGIN_COLUMNS
float currentColumn = 0
entity currentPanel = NEW(XonoticTab)
float currentRow = 0
float firstColumn = 0
float focusable = 0
float focused = 0
bool hideMenuOnClose = false
float intendedHeight = 0
float intendedWidth = 0.9
float isTabRoot = 0
vector itemOrigin = '0 0 0'
vector itemSize = '0 0 0'
vector itemSpacing = '0 0 0'
float marginBottom = 0
float marginLeft = 0
float marginRight = 0
float marginTop = 0
string name = ""
vector origin = '0 0 0'
float preferredFocusPriority = 0
float requiresConnection = 0
float rootDialog = 0
float rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL
float rows = 15.5
float rowSpacing = SKINMARGIN_ROWS
float shown = 0
vector size = '0 0 0'
DataSource source = NEW(SettingSource)
string title = "Form1"
float titleFontSize = 0
float titleHeight = 0
entity topicList = NEW(XonoticRegisteredSettingsList, this.source)
float zoomedOutTitleBar = 0
float zoomedOutTitleBarPosition = 0
Detailed Description
Definition at line 36 of file dialog_settings_game.qh.
Constructor & Destructor Documentation
XonoticGameSettingsTab::XonoticGameSettingsTab () inline
Definition at line 49 of file dialog_settings_game.qh.
References ENDCLASS.
     {
         this.configureDialog(this);
     }
Member Function Documentation
virtual void InputContainer::_changeFocusXY () virtual inherited
virtual void Container::addItem () virtual inherited
Reimplemented in ModalController, and Nexposee.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
virtual void Dialog::addItemSimple () virtual inherited
Tab::ATTRIB (Tab , title , string) inherited
InputContainer::ATTRIB (InputContainer , mouseFocusedChild , entity) inherited
XonoticTab::ATTRIB (XonoticTab , backgroundImage , string) inherited
Tab::ATTRIB (Tab , backgroundImage , string) inherited
XonoticTab::ATTRIB (XonoticTab , titleTooltip , string) inherited
MenuItem::ATTRIB (MenuItem , parent , entity) inherited
Container::ATTRIB (Container , firstChild , entity) inherited
Container::ATTRIB (Container , lastChild , entity) inherited
Container::ATTRIB (Container , focusedChild , entity) inherited
MenuItem::ATTRIB (MenuItem , tooltip , string) inherited
Container::ATTRIB (Container , savedFocus , entity) inherited
Dialog::ATTRIB (Dialog , closeButton , entity) inherited
XonoticGameSettingsTab::ATTRIB (XonoticGameSettingsTab , currentItem , entity)
Dialog::ATTRIB (Dialog , backgroundImage , string) inherited
Dialog::ATTRIB (Dialog , closeButtonImage , string) inherited
Dialog::ATTRIB (Dialog , frame , entity) inherited
virtual void Dialog::close () virtual inherited
Reimplemented in XonoticRootDialog, XonoticScreenshotViewerDialog, and XonoticMutatorsDialog.
virtual void Dialog::configureDialog () virtual inherited
Reimplemented in XonoticDialog.
void MenuItem::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Container::draw () virtual inherited
Reimplemented from MenuItem.
Reimplemented in ModalController, MainWindow, XonoticProfileTab, and Nexposee.
Referenced by XonoticScrollPanel::drawListBoxItem().
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
void XonoticGameSettingsTab::fill () virtual
Reimplemented from Dialog.
Definition at line 122 of file dialog_settings_game.qc.
References entity().
 {
     entity topics = this.topicList;
         topics.onChange = this.topicChangeNotify;
         topics.onChangeEntity = this;
     int
     col = 0, width = 1;
     this.gotoRC(this, 0, col);
         this.TD(this, this.rows, width, topics);
     col += width, width = this.columns - col;
     this.gotoRC(this, 0, col); this.setFirstColumn(this, this.currentColumn);
         this.TD(this, this.rows, width, this.currentPanel);
     this.topicChangeNotify(topics, this);
 }
void MenuItem::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void InputContainer::focusLeave () virtual inherited
Reimplemented from Container.
virtual void Dialog::gotoRC () virtual inherited
virtual void Container::hideNotify () virtual inherited
Reimplemented from MenuItem.
virtual void Container::itemFromPoint () virtual inherited
virtual void Dialog::keyDown () virtual inherited
Reimplemented from InputContainer.
Reimplemented in XonoticScreenshotViewerDialog.
virtual void Container::keyUp () virtual inherited
Reimplemented from MenuItem.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual inherited
virtual void InputContainer::mouseDrag () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseMove () virtual inherited
Reimplemented from Container.
void InputContainer::mousePress () virtual inherited
Reimplemented from Container.
Definition at line 119 of file inputcontainer.qc.
References NULL, and SUPER.
     {
         this.mouseFocusedChild = NULL;  // force focusing
         if (this._changeFocusXY(this, pos))
             if (SUPER(InputContainer).mousePress(this, pos)) return true;
         if (pos.x >= 0 && pos.y >= 0 && pos.x < 1 && pos.y < 1) return true;
         return false;
     }
virtual void InputContainer::mouseRelease () virtual inherited
Reimplemented from Container.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
void MenuItem::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void InputContainer::resizeNotify () virtual inherited
Reimplemented from Container.
Referenced by XonoticScrollPanel::resizeNotify().
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Dialog::setFirstColumn () virtual inherited
virtual void Container::setFocus () virtual inherited
virtual void XonoticTab::showNotify () virtual inherited
Reimplemented from Container.
Reimplemented in XonoticDamageTextSettings, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, and XonoticGameWeaponsSettingsTab.
virtual void Dialog::TD () virtual inherited
virtual void Dialog::TDempty () virtual inherited
virtual void Dialog::TDNoMargin () virtual inherited
void XonoticGameSettingsTab::topicChangeNotify () virtual
Definition at line 95 of file dialog_settings_game.qc.
References entity(), func_null(), DataSource::getEntry(), and NULL.
 {
     entity s = NULL;
     entity c = this.currentPanel;
     if (c.classname == "XonoticScrollPanel")
     {
         s = this.currentPanel;
         s.viewportHeight = 15.5;
         c = s.currentPanel;
     }
     entity removing = this.currentItem;
     DataSource data = this.topicList.source;
     entity adding = data.getEntry(data, this.topicList.selectedItem, func_null);
     if (removing == adding) return;
     if (removing) {
         this.currentItem = NULL;
         c.removeItem(c, removing);
     }
     if (adding) {
         this.currentItem = adding;
         adding.resizeNotify(adding, '0 0 0', c.size, '0 0 0', c.size);
         c.addItem(c, adding, '0 0 0', '1 1 0', 1);
         if (s)
             s.resizeNotify(s, '0 0 0', s.size, '0 0 0', s.size);
     }
 }
void MenuItem::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void Dialog::TR () virtual inherited
Member Data Documentation
float MenuItem::allowFocusSound = 0 inherited
Definition at line 26 of file item.qh.
float Dialog::borderLines = 1 inherited
Definition at line 67 of file dialog.qh.
float Tab::closable = 0 inherited
Definition at line 6 of file tab.qh.
vector Dialog::color = '1 0.5 1' inherited
Definition at line 47 of file dialog.qh.
float XonoticGameSettingsTab::columns = 6.5
Definition at line 39 of file dialog_settings_game.qh.
float XonoticTab::columnSpacing = SKINMARGIN_COLUMNS inherited
Definition at line 17 of file tab.qh.
float Dialog::currentColumn = 0 inherited
Definition at line 40 of file dialog.qh.
entity XonoticGameSettingsTab::currentPanel = NEW(XonoticTab)
Definition at line 45 of file dialog_settings_game.qh.
float Dialog::currentRow = 0 inherited
Definition at line 39 of file dialog.qh.
float Dialog::firstColumn = 0 inherited
Definition at line 41 of file dialog.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float MenuItem::focused = 0 inherited
Definition at line 24 of file item.qh.
bool Dialog::hideMenuOnClose = false inherited
Definition at line 70 of file dialog.qh.
float Dialog::intendedHeight = 0 inherited
Definition at line 35 of file dialog.qh.
float XonoticGameSettingsTab::intendedWidth = 0.9
Definition at line 37 of file dialog_settings_game.qh.
float Tab::isTabRoot = 0 inherited
Definition at line 5 of file tab.qh.
vector Dialog::itemOrigin = '0 0 0' inherited
Definition at line 36 of file dialog.qh.
vector Dialog::itemSize = '0 0 0' inherited
Definition at line 37 of file dialog.qh.
vector Dialog::itemSpacing = '0 0 0' inherited
Definition at line 38 of file dialog.qh.
float XonoticTab::marginBottom = 0 inherited
Definition at line 14 of file tab.qh.
float XonoticTab::marginLeft = 0 inherited
Definition at line 15 of file tab.qh.
float XonoticTab::marginRight = 0 inherited
Definition at line 16 of file tab.qh.
float XonoticTab::marginTop = 0 inherited
Definition at line 13 of file tab.qh.
string Dialog::name = "" inherited
Definition at line 46 of file dialog.qh.
vector MenuItem::origin = '0 0 0' inherited
Definition at line 29 of file item.qh.
float MenuItem::preferredFocusPriority = 0 inherited
Definition at line 28 of file item.qh.
float Dialog::requiresConnection = 0 inherited
Definition at line 64 of file dialog.qh.
float Tab::rootDialog = 0 inherited
Definition at line 7 of file tab.qh.
float XonoticTab::rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL inherited
Definition at line 19 of file tab.qh.
float XonoticGameSettingsTab::rows = 15.5
Definition at line 38 of file dialog_settings_game.qh.
float XonoticTab::rowSpacing = SKINMARGIN_ROWS inherited
Definition at line 18 of file tab.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector MenuItem::size = '0 0 0' inherited
Definition at line 30 of file item.qh.
DataSource XonoticGameSettingsTab::source = NEW(SettingSource)
Definition at line 40 of file dialog_settings_game.qh.
string Dialog::title = "Form1" inherited
Definition at line 45 of file dialog.qh.
float Tab::titleFontSize = 0 inherited
Definition at line 9 of file tab.qh.
float Tab::titleHeight = 0 inherited
Definition at line 23 of file tab.qh.
entity XonoticGameSettingsTab::topicList = NEW(XonoticRegisteredSettingsList, this.source)
Definition at line 41 of file dialog_settings_game.qh.
float Dialog::zoomedOutTitleBar = 0 inherited
Definition at line 62 of file dialog.qh.
float Dialog::zoomedOutTitleBarPosition = 0 inherited
Definition at line 61 of file dialog.qh.
The documentation for this class was generated from the following files:
menu/xonotic/dialog_settings_game.qh
menu/xonotic/dialog_settings_game.qc