Xonotic: server/weapons/selection.qc File Reference
selection.qc File Reference
#include "selection.qh"
#include "weaponsystem.qh"
#include <common/t_items.qh>
#include <common/constants.qh>
#include <common/net_linked.qh>
#include <common/util.qh>
#include <common/items/item.qh>
#include <common/weapons/_all.qh>
#include <common/state.qh>
#include <common/mutators/mutator/waypoints/waypointsprites.qh>
#include <common/wepent.qh>
Functions
bool client_hasweapon (entity this, Weapon wpn,.entity weaponentity, float andammo, bool complain)
void Send_WeaponComplain (entity e, float wpn, float type)
void W_CycleWeapon (entity this, string weaponorder, float dir,.entity weaponentity)
float W_GetCycleWeapon (entity this, string weaponorder, float dir, float imp, float complain, float skipmissing,.entity weaponentity)
void W_LastWeapon (entity this,.entity weaponentity)
void W_NextWeapon (entity this, int list,.entity weaponentity)
void W_NextWeaponOnImpulse (entity this, float imp,.entity weaponentity)
void W_PreviousWeapon (entity this, float list,.entity weaponentity)
void W_SwitchToOtherWeapon (entity this,.entity weaponentity)
void W_SwitchWeapon (entity this, Weapon w,.entity weaponentity)
void W_SwitchWeapon_Force (Player this, Weapon wep,.entity weaponentity)
void Weapon_whereis (Weapon this, entity cl)
Function Documentation
bool client_hasweapon (entity this, Weapon wpn, .entity weaponentity, float andammo, bool complain)
Definition at line 43 of file selection.qc.
References autocvar_g_weaponswitch_debug, g_mines, hasweapon_complain_spam, IL_EACH, IS_REAL_CLIENT, IT_UNLIMITED_WEAPON_AMMO, items, Weapon::m_id, OFFHAND_HOOK, play2(), Send_WeaponComplain(), SND, Weapon::spawnflags, sprint(), time, weapons, weaponsInMap, weaponslot(), WEP_FLAG_DUALWIELD, WepSet_FromWeapon, Weapon::wr_checkammo1(), and Weapon::wr_checkammo2().
Referenced by bot_cmd_select_weapon(), havocbot_chooseweapon(), NIX_GiveCurrentWeapon(), REGISTER_MUTATOR(), W_GetCycleWeapon(), W_LastWeapon(), and W_SwitchWeapon().
 {
     float f = 0;
     if (time < this.hasweapon_complain_spam)
         complain = 0;
     // ignore hook button when using other offhand equipment
     if (this.offhand != OFFHAND_HOOK)
     if (wpn == WEP_HOOK && !((this.weapons | weaponsInMap) & WepSet_FromWeapon(wpn)))
         complain = 0;
     if (complain)
         this.hasweapon_complain_spam = time + 0.2;
     if (wpn == WEP_Null)
     {
         if (complain)
             sprint(this, "Invalid weapon\n");
         return false;
     }
     if (autocvar_g_weaponswitch_debug == 2 && weaponslot(weaponentity) > 0 && !(wpn.spawnflags & WEP_FLAG_DUALWIELD))
         return false; // no complaints needed
     if (this.weapons & WepSet_FromWeapon(wpn))
     {
         if (andammo)
         {
             if(this.items & IT_UNLIMITED_WEAPON_AMMO)
             {
                 f = 1;
             }
             else
             {
                 f = wpn.wr_checkammo1(wpn, this, weaponentity) + wpn.wr_checkammo2(wpn, this, weaponentity);
                 // always allow selecting the Mine Layer if we placed mines, so that we can detonate them
                 if(wpn == WEP_MINE_LAYER)
                     IL_EACH(g_mines, it.owner == this && it.weaponentity_fld == weaponentity,
                     {
                         f = 1;
                         break; // no need to continue
                     });
             }
             if (!f)
             {
                 if (complain)
                 if(IS_REAL_CLIENT(this))
                 {
                     play2(this, SND(UNAVAILABLE));
                     Send_WeaponComplain (this, wpn.m_id, 0);
                 }
                 return false;
             }
         }
         return true;
     }
     if (complain)
     {
         // DRESK - 3/16/07
         // Report Proper Weapon Status / Modified Weapon Ownership Message
         if (weaponsInMap & WepSet_FromWeapon(wpn))
         {
             Send_WeaponComplain(this, wpn.m_id, 1);
             if(autocvar_g_showweaponspawns < 3)
                 Weapon_whereis(wpn, this);
             else
             {
                 FOREACH(Weapons, it.impulse == wpn.impulse,
                 {
                     Weapon_whereis(it, this);
                 });
             }
         }
         else
         {
             Send_WeaponComplain (this, wpn.m_id, 2);
         }
         play2(this, SND(UNAVAILABLE));
     }
     return false;
 }
void Send_WeaponComplain (entity e, float wpn, float type)
Definition at line 15 of file selection.qc.
References msg_entity, MSG_ONE, and WriteByte().
Referenced by client_hasweapon().
 {
     msg_entity = e;
     WriteHeader(MSG_ONE, TE_CSQC_WEAPONCOMPLAIN);
     WriteByte(MSG_ONE, wpn);
     WriteByte(MSG_ONE, type);
 }
void W_CycleWeapon (entity this, string weaponorder, float dir, .entity weaponentity)
Definition at line 282 of file selection.qc.
References W_GetCycleWeapon(), W_SwitchWeapon(), and Weapons_from.
Referenced by W_NextWeapon(), and W_PreviousWeapon().
 {
     float w;
     w = W_GetCycleWeapon(this, weaponorder, dir, -1, 1, true, weaponentity);
     if(w > 0)
         W_SwitchWeapon(this, Weapons_from(w), weaponentity);
 }
float W_GetCycleWeapon (entity this, string weaponorder, float dir, float imp, float complain, float skipmissing, .entity weaponentity)
Definition at line 126 of file selection.qc.
References car(), cdr(), client_hasweapon(), entity(), FOREACH, selectweapon, stof(), weaponcomplainindex, weaponorder, weapons, Weapons_from, weaponsInMap, and WEP_FLAG_MUTATORBLOCKED.
Referenced by W_CycleWeapon(), and W_NextWeaponOnImpulse().
 {
     // We cannot tokenize in this function, as GiveItems calls this
     // function. Thus we must use car/cdr.
     float weaponwant, first_valid, prev_valid, switchtonext, switchtolast;
     WepSet wepset = '0 0 0';
     switchtonext = switchtolast = 0;
     first_valid = prev_valid = 0;
     float weaponcur;
     entity wep;
     if(skipmissing || this.(weaponentity).selectweapon == 0)
         weaponcur = this.(weaponentity).m_switchweapon.m_id;
     else
         weaponcur = this.(weaponentity).selectweapon;
     if(dir == 0)
         switchtonext = 1;
     int c = 0;
     string rest = weaponorder;
     while(rest != "")
     {
         weaponwant = stof(car(rest)); rest = cdr(rest);
         wep = Weapons_from(weaponwant);
         wepset = wep.m_wepset;
         if(imp >= 0)
         if(wep.impulse != imp)
             continue;
         bool have_other = false;
         FOREACH(Weapons, it != WEP_Null, {
             if(i != weaponwant)
             if(it.impulse == imp || imp < 0)
             if((this.weapons & (it.m_wepset)) || (weaponsInMap & (it.m_wepset)))
                 have_other = true;
         });
         // skip weapons we don't own that aren't normal and aren't in the map
         if(!(this.weapons & wepset))
         if(!(weaponsInMap & wepset))
         if((wep.spawnflags & WEP_FLAG_MUTATORBLOCKED) || have_other)
             continue;
         ++c;
         if(!skipmissing || client_hasweapon(this, wep, weaponentity, true, false))
         {
             if(switchtonext)
                 return weaponwant;
             if(!first_valid)
                 first_valid = weaponwant;
             if(weaponwant == weaponcur)
             {
                 if(dir >= 0)
                     switchtonext = 1;
                 else if(prev_valid)
                     return prev_valid;
                 else
                     switchtolast = 1;
             }
             prev_valid = weaponwant;
         }
     }
     if(first_valid)
     {
         if(switchtolast)
             return prev_valid;
         else
             return first_valid;
     }
     // complain (but only for one weapon on the button that has been pressed)
     if(complain)
     {
         this.weaponcomplainindex += 1;
         c = (this.weaponcomplainindex % c) + 1;
         rest = weaponorder;
         while(rest != "")
         {
             weaponwant = stof(car(rest)); rest = cdr(rest);
             wep = Weapons_from(weaponwant);
             wepset = wep.m_wepset;
             if(imp >= 0)
                 if(wep.impulse != imp)
                     continue;
             bool have_other = false;
             FOREACH(Weapons, it != WEP_Null, {
                 if(i != weaponwant)
                 if(it.impulse == imp || imp < 0)
                 if((this.weapons & (it.m_wepset)) || (weaponsInMap & (it.m_wepset)))
                     have_other = true;
             });
             // skip weapons we don't own that aren't normal and aren't in the map
             if(!(this.weapons & wepset))
             if(!(weaponsInMap & wepset))
             if((wep.spawnflags & WEP_FLAG_MUTATORBLOCKED) || have_other)
                 continue;
             --c;
             if(c == 0)
             {
                 client_hasweapon(this, wep, weaponentity, true, true);
                 break;
             }
         }
     }
     return 0;
 }
void W_LastWeapon (entity this, .entity weaponentity)
Definition at line 321 of file selection.qc.
References client_hasweapon(), cnt, W_SwitchToOtherWeapon(), W_SwitchWeapon(), and Weapons_from.
Referenced by IMPULSE().
 {
     Weapon wep = Weapons_from(this.(weaponentity).cnt);
     if (client_hasweapon(this, wep, weaponentity, true, false))
         W_SwitchWeapon(this, wep, weaponentity);
     else
         W_SwitchToOtherWeapon(this, weaponentity);
 }
void W_NextWeapon (entity this, int list, .entity weaponentity)
Definition at line 299 of file selection.qc.
References cvar_cl_weaponpriority, W_CycleWeapon(), weaponorder_byid, and weaponorder_byimpulse.
Referenced by IMPULSE(), and X().
 {
     if(list == 0)
         W_CycleWeapon(this, weaponorder_byid, -1, weaponentity);
     else if(list == 1)
         W_CycleWeapon(this, this.weaponorder_byimpulse, -1, weaponentity);
     else if(list == 2)
         W_CycleWeapon(this, this.cvar_cl_weaponpriority, -1, weaponentity);
 }
void W_NextWeaponOnImpulse (entity this, float imp, .entity weaponentity)
Definition at line 290 of file selection.qc.
References cvar_cl_weaponimpulsemode, cvar_cl_weaponpriority, W_GetCycleWeapon(), W_SwitchWeapon(), and Weapons_from.
 {
     float w;
     w = W_GetCycleWeapon(this, this.cvar_cl_weaponpriority, +1, imp, 1, (this.cvar_cl_weaponimpulsemode == 0), weaponentity);
     if(w > 0)
         W_SwitchWeapon(this, Weapons_from(w), weaponentity);
 }
void W_PreviousWeapon (entity this, float list, .entity weaponentity)
Definition at line 310 of file selection.qc.
References cvar_cl_weaponpriority, W_CycleWeapon(), weaponorder_byid, and weaponorder_byimpulse.
Referenced by IMPULSE().
 {
     if(list == 0)
         W_CycleWeapon(this, weaponorder_byid, +1, weaponentity);
     else if(list == 1)
         W_CycleWeapon(this, this.weaponorder_byimpulse, +1, weaponentity);
     else if(list == 2)
         W_CycleWeapon(this, this.cvar_cl_weaponpriority, +1, weaponentity);
 }
void W_SwitchToOtherWeapon (entity this, .entity weaponentity)
Definition at line 247 of file selection.qc.
References w_getbestweapon, W_SwitchWeapon_Force(), weapons, and WepSet_FromWeapon.
Referenced by W_LastWeapon(), and W_Reload().
 {
     // hack to ensure it switches to an OTHER weapon (in case the other fire mode still has ammo, we want that anyway)
     Weapon ww;
     WepSet set = WepSet_FromWeapon(this.(weaponentity).m_weapon);
     if (this.weapons & set)
     {
         this.weapons &= ~set;
         ww = w_getbestweapon(this, weaponentity);
         this.weapons |= set;
     }
     else
     {
         ww = w_getbestweapon(this, weaponentity);
     }
     if (ww == WEP_Null) return;
     W_SwitchWeapon_Force(this, ww, weaponentity);
 }
void W_SwitchWeapon (entity this, Weapon w, .entity weaponentity)
Definition at line 266 of file selection.qc.
References client_hasweapon(), entity(), forbidWeaponUse(), Weapon::m_id, selectweapon, W_SwitchWeapon_Force(), and Weapon::wr_reload().
Referenced by IMPULSE(), NIX_GiveCurrentWeapon(), W_CycleWeapon(), W_LastWeapon(), W_NextWeaponOnImpulse(), and W_WeaponFrame().
 {
     if(this.(weaponentity).m_switchweapon != w)
     {
         if(client_hasweapon(this, w, weaponentity, true, true))
             W_SwitchWeapon_Force(this, w, weaponentity);
         else
             this.(weaponentity).selectweapon = w.m_id; // update selectweapon anyway
     }
     else if(!forbidWeaponUse(this))
     {
         entity actor = this;
         w.wr_reload(w, actor, weaponentity);
     }
 }
void W_SwitchWeapon_Force (Player this, Weapon wep, .entity weaponentity)
Definition at line 238 of file selection.qc.
References cnt, Weapon::m_id, selectweapon, and TC.
Referenced by GiveFrags(), TEST(), W_SwitchToOtherWeapon(), W_SwitchWeapon(), W_ThrowWeapon(), and W_WeaponFrame().
 {
     TC(Weapon, wep);
     this.(weaponentity).cnt = this.(weaponentity).m_switchweapon.m_id;
     this.(weaponentity).m_switchweapon = wep;
     this.(weaponentity).selectweapon = wep.m_id;
 }
void Weapon_whereis (Weapon this, entity cl)
Definition at line 23 of file selection.qc.
References autocvar_g_showweaponspawns, enemy, entity(), g_items, IL_EACH, ITS_AVAILABLE, and NULL.
 {
     if (!autocvar_g_showweaponspawns) return;
     IL_EACH(g_items, it.weapon == this.m_id && (!it.team || (it.ItemStatus & ITS_AVAILABLE)),
     {
         if (it.classname == "droppedweapon" && autocvar_g_showweaponspawns < 2)
             continue;
         entity wp = WaypointSprite_Spawn(
             WP_Weapon,
             -2, 0,
             NULL, it.origin + ('0 0 1' * it.maxs.z) * 1.2,
             cl, 0,
             NULL, enemy,
             0,
             RADARICON_NONE
         );
         wp.wp_extra = this.m_id;
     });
 }