Xonotic: IntrusiveList Class Reference
IntrusiveList Class Reference
limitations: NULL cannot be present elements can only be present once a maximum of IL_MAX lists can exist at one time freed entities must be removed from the list
Public Member Functions
IntrusiveList ()
~IntrusiveList ()
ATTRIB (IntrusiveList, il_head, entity)
ATTRIB (IntrusiveList, il_tail, entity)
virtual void describe ()
virtual void display ()
Public Attributes
entity il_nextfld = nil
entity il_prevfld = nil
Detailed Description
limitations: NULL cannot be present elements can only be present once a maximum of IL_MAX lists can exist at one time freed entities must be removed from the list
Definition at line 18 of file intrusivelist.qh.
Constructor & Destructor Documentation
IntrusiveList::IntrusiveList () inline
Definition at line 23 of file intrusivelist.qh.
References IL_INIT().
 { IL_INIT(this); }
IntrusiveList::~IntrusiveList () inline
Definition at line 24 of file intrusivelist.qh.
References IL_DTOR().
 { IL_DTOR(this); }
Member Function Documentation
IntrusiveList::ATTRIB (IntrusiveList , il_head , entity)
IntrusiveList::ATTRIB (IntrusiveList , il_tail , entity)
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
Member Data Documentation
entity IntrusiveList::il_nextfld = nil
Definition at line 21 of file intrusivelist.qh.
Referenced by IL_ENDFRAME().
entity IntrusiveList::il_prevfld = nil
Definition at line 22 of file intrusivelist.qh.
The documentation for this class was generated from the following file:
lib/intrusivelist.qh