Xonotic: lib/i18n.qh File Reference
i18n.qh File Reference
#include "log.qh"
#include "map.qh"
#include "unsafe.qh"
Macros
#define CTX_CACHE 1
#define ZCTX(s) strzone(CTX(s))
Functions
ERASEABLE string CTX (string s)
ERASEABLE string language_filename (string s)
SHUTDOWN (CTX_cache)
STATIC_INIT (CTX_cache)
Variables
HashMap CTX_cache
string prvm_language
Macro Definition Documentation
CTX_CACHE
#define CTX_CACHE 1
Definition at line 29 of file i18n.qh.
ZCTX
#define ZCTX (s) strzone(CTX(s))
Definition at line 68 of file i18n.qh.
Referenced by ServerList_Update_favoriteButton(), XonoticScoreboardFadeTimeSlider_configureXonoticScoreboardFadeTimeSlider(), and XonoticServerListTab_fill().
Function Documentation
CTX()
ERASEABLE string CTX (string s)
Definition at line 45 of file i18n.qh.
References CTX_cache, HM_gets, HM_sets, LOG_DEBUGF, strstrofs, and substring().
Referenced by count_fill(), Label_getInfo(), and XonoticDecibelsSlider_valueToText().
 {
 #if CTX_CACHE
     string c = HM_gets(CTX_cache, s);
     if (c != "") return c;
 #endif
     int caret_ofs = strstrofs(s, "^", 0);
     string ret = s;
     // empty (caret_ofs == 0) and one char (caret_ofs == 1) prefixes are invalid
     if (caret_ofs > 1)
     {
         int space_ofs = strstrofs(substring(s, 0, caret_ofs), " ", 0);
         // prefixes containing a space are invalid (likely the caret is part of a color code)
         if (space_ofs < 0 || space_ofs > caret_ofs)
             ret = substring(s, caret_ofs + 1, -1);
     }
 #if CTX_CACHE
     LOG_DEBUGF("CTX(\"%s\")", s);
     HM_sets(CTX_cache, s, ret);
 #endif
     return ret;
 }
language_filename()
ERASEABLE string language_filename (string s)
Deprecated:
prefer _("translatable text") - GMQCC's -ftranslatable-strings feature
Definition at line 14 of file i18n.qh.
References fclose(), FILE_READ, fopen(), prvm_language, and strcat().
Referenced by CampaignFile_Load().
 {
     string fn = prvm_language;
     if (fn == "" || fn == "dump") return s;
     fn = strcat(s, ".", fn);
     int fh = fopen(fn, FILE_READ);
     if (fh >= 0)
     {
         fclose(fh);
         return fn;
     }
     return s;
 }
SHUTDOWN()
SHUTDOWN (CTX_cache)
Definition at line 38 of file i18n.qh.
References CTX_cache, ERASEABLE, and HM_DELETE.
     {
         HM_DELETE(CTX_cache);
     }
STATIC_INIT()
STATIC_INIT (CTX_cache)
Definition at line 34 of file i18n.qh.
References CTX_cache, and HM_NEW.
     {
         HM_NEW(CTX_cache);
     }
Variable Documentation
CTX_cache
HashMap CTX_cache
Definition at line 33 of file i18n.qh.
Referenced by CTX(), SHUTDOWN(), and STATIC_INIT().
prvm_language
string prvm_language
Definition at line 8 of file i18n.qh.
Referenced by CheckFirstRunButton(), CSQC_Init(), firstRun_setLanguage(), language_filename(), m_init(), setZonedTooltip(), translate_key(), and XonoticLanguageList_setLanguage().