Xonotic: server/matrix.qc File Reference
matrix.qc File Reference
#include "matrix.qh"
#include "client.qh"
Functions
var void MX_Handle (int buf, string ancestor)
Function Documentation
var void MX_Handle (int buf, string ancestor)
Definition at line 5 of file matrix.qc.
References json_get(), matrix_user, NULL, Say(), and strcat().
 {
     string type = json_get(buf, strcat(ancestor, ".type"));
     switch (type) {
         case "m.room.message": {
             string msgtype = json_get(buf, strcat(ancestor, ".content.msgtype"));
             switch (msgtype) {
                 case "m.text": {
                     string sender = json_get(buf, strcat(ancestor, ".sender"));
                     string body = json_get(buf, strcat(ancestor, ".content.body"));
                     if (sender != matrix_user && body) Say(NULL, false, NULL, body, false);
                     break;
                 }
             }
             break;
         }
     }
 }