Xonotic: server/bot/aim.qh File Reference
server/bot/aim.qh File Reference
Defines
#define AIM_H
Functions
float lag_additem (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4)
void lag_update ()
void bot_lagfunc (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4)
float bot_shouldattack (entity e)
float bot_aimdir (vector v, float maxfiredeviation)
float bot_aim (float shotspeed, float shotspeedupward, float maxshottime, float applygravity)
float findtrajectorywithleading (vector org, vector m1, vector m2, entity targ, float shotspeed, float shotspeedupward, float maxtime, float shotdelay, entity ignore)
vector bot_shotlead (vector targorigin, vector targvelocity, float shotspeed, float shotdelay)
void (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4) lag_func
Variables
entity tracetossent
entity tracetossfaketarget
vector findtrajectory_velocity
vector shotorg
vector shotdir
float lag1_time
float lag1_float1
float lag1_float2
entity lag1_entity1
vector lag1_vec1
vector lag1_vec2
vector lag1_vec3
vector lag1_vec4
float lag2_time
float lag2_float1
float lag2_float2
entity lag2_entity1
vector lag2_vec1
vector lag2_vec2
vector lag2_vec3
vector lag2_vec4
float lag3_time
float lag3_float1
float lag3_float2
entity lag3_entity1
vector lag3_vec1
vector lag3_vec2
vector lag3_vec3
vector lag3_vec4
float lag4_time
float lag4_float1
float lag4_float2
entity lag4_entity1
vector lag4_vec1
vector lag4_vec2
vector lag4_vec3
vector lag4_vec4
float lag5_time
float lag5_float1
float lag5_float2
entity lag5_entity1
vector lag5_vec1
vector lag5_vec2
vector lag5_vec3
vector lag5_vec4
float bot_badaimtime
float bot_aimthinktime
float bot_prevaimtime
float bot_firetimer
float bot_aimlatency
vector bot_mouseaim
vector bot_badaimoffset
vector bot_1st_order_aimfilter
vector bot_2nd_order_aimfilter
vector bot_3th_order_aimfilter
vector bot_4th_order_aimfilter
vector bot_5th_order_aimfilter
vector bot_olddesiredang
vector bot_aimselforigin
vector bot_aimselfvelocity
vector bot_aimtargorigin
vector bot_aimtargvelocity
entity bot_aimtarg
Define Documentation
#define AIM_H
Definition at line 2 of file aim.qh.
Function Documentation
float bot_aim (float shotspeed, float shotspeedupward, float maxshottime, float applygravity)
Definition at line 321 of file aim.qc.
References autocvar_bot_ai_aimskill_firetolerance_distdegrees, autocvar_bot_ai_aimskill_firetolerance_maxdegrees, autocvar_bot_ai_aimskill_firetolerance_mindegrees, bot_aimdir(), bot_aimlatency, bot_aimtarg, bot_aimtargorigin, bot_aimtargvelocity, bot_shotlead(), bot_shouldattack(), bound(), DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, enemy, findtrajectory_velocity, findtrajectorywithleading(), LOG_TRACE(), PS(), SELFPARAM, shotdir, shotorg, skill, sqrt(), trace_ent, trace_fraction, v_angle, v_forward, vector(), vlen(), and W_WeaponSpeedFactor().
{SELFPARAM();
    float f, r, hf, distanceratio;
    vector v;
    /*
    eprint(self);
    dprint("bot_aim(", ftos(shotspeed));
    dprint(", ", ftos(shotspeedupward));
    dprint(", ", ftos(maxshottime));
    dprint(", ", ftos(applygravity));
    dprint(");\n");
    */
    hf = self.dphitcontentsmask;
    self.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
    shotspeed *= W_WeaponSpeedFactor();
    shotspeedupward *= W_WeaponSpeedFactor();
    if (!shotspeed)
    {
        LOG_TRACE("bot_aim: WARNING: weapon ", PS(self).m_weapon.m_name, " shotspeed is zero!\n");
        shotspeed = 1000000;
    }
    if (!maxshottime)
    {
        LOG_TRACE("bot_aim: WARNING: weapon ", PS(self).m_weapon.m_name, " maxshottime is zero!\n");
        maxshottime = 1;
    }
    makevectors(self.v_angle);
    shotorg = self.origin + self.view_ofs;
    shotdir = v_forward;
    v = bot_shotlead(self.bot_aimtargorigin, self.bot_aimtargvelocity, shotspeed, self.bot_aimlatency);
    distanceratio = sqrt(bound(0,skill,10000))*0.3*(vlen(v-shotorg)-100)/autocvar_bot_ai_aimskill_firetolerance_distdegrees;
    distanceratio = bound(0,distanceratio,1);
    r =  (autocvar_bot_ai_aimskill_firetolerance_maxdegrees-autocvar_bot_ai_aimskill_firetolerance_mindegrees)
        * (1-distanceratio) + autocvar_bot_ai_aimskill_firetolerance_mindegrees;
    if (applygravity && self.bot_aimtarg)
    {
        if (!findtrajectorywithleading(shotorg, '0 0 0', '0 0 0', self.bot_aimtarg, shotspeed, shotspeedupward, maxshottime, 0, self))
        {
            self.dphitcontentsmask = hf;
            return false;
        }
        f = bot_aimdir(findtrajectory_velocity - shotspeedupward * '0 0 1', r);
    }
    else
    {
        f = bot_aimdir(v - shotorg, r);
        //dprint("AIM: ");dprint(vtos(self.bot_aimtargorigin));dprint(" + ");dprint(vtos(self.bot_aimtargvelocity));dprint(" * ");dprint(ftos(self.bot_aimlatency + vlen(self.bot_aimtargorigin - shotorg) / shotspeed));dprint(" = ");dprint(vtos(v));dprint(" : aimdir = ");dprint(vtos(normalize(v - shotorg)));dprint(" : ");dprint(vtos(shotdir));dprint("\n");
        //traceline(shotorg, shotorg + shotdir * 10000, false, self);
        //if (trace_ent.takedamage)
        //if (trace_fraction < 1)
        //if (!bot_shouldattack(trace_ent))
        //  return false;
        traceline(shotorg, self.bot_aimtargorigin, false, self);
        if (trace_fraction < 1)
        if (trace_ent != self.enemy)
        if (!bot_shouldattack(trace_ent))
        {
            self.dphitcontentsmask = hf;
            return false;
        }
    }
    //if (r > maxshottime * shotspeed)
    //  return false;
    self.dphitcontentsmask = hf;
    return true;
}
float bot_aimdir (vector v, float maxfiredeviation)
Definition at line 170 of file aim.qc.
References autocvar_bot_ai_aimskill_blendrate, autocvar_bot_ai_aimskill_fixedrate, autocvar_bot_ai_aimskill_mouse, autocvar_bot_ai_aimskill_offset, autocvar_bot_ai_aimskill_order_filter_1st, autocvar_bot_ai_aimskill_order_filter_2nd, autocvar_bot_ai_aimskill_order_filter_3th, autocvar_bot_ai_aimskill_order_filter_4th, autocvar_bot_ai_aimskill_order_filter_5th, autocvar_bot_ai_aimskill_order_mix_1st, autocvar_bot_ai_aimskill_order_mix_2nd, autocvar_bot_ai_aimskill_order_mix_3th, autocvar_bot_ai_aimskill_order_mix_4th, autocvar_bot_ai_aimskill_order_mix_5th, autocvar_bot_ai_aimskill_think, bot_1st_order_aimfilter, bot_aggresskill, bot_aimskill, bot_aimthinktime, bot_badaimtime, bot_mouseskill, bot_offsetskill, bot_thinkskill, bound(), cos(), floor(), max(), normalize(), pow(), random(), randomvec(), SELFPARAM, shotdir, shotorg, skill, time, trace_endpos, v_angle, v_forward, vdist, vectoangles(), vector(), and vlen().
Referenced by bot_aim(), havocbot_ai(), and havocbot_moveto().
{SELFPARAM();
    float dist, delta_t, blend;
    vector desiredang, diffang;
    //dprint("aim ", self.netname, ": old:", vtos(self.v_angle));
    // make sure v_angle is sane first
    self.v_angle_y = self.v_angle.y - floor(self.v_angle.y / 360) * 360;
    self.v_angle_z = 0;
    // get the desired angles to aim at
    //dprint(" at:", vtos(v));
    v = normalize(v);
    //te_lightning2(world, self.origin + self.view_ofs, self.origin + self.view_ofs + v * 200);
    if (time >= self.bot_badaimtime)
    {
        self.bot_badaimtime = max(self.bot_badaimtime + 0.3, time);
        self.bot_badaimoffset = randomvec() * bound(0, 5 - 0.5 * (skill+self.bot_offsetskill), 5) * autocvar_bot_ai_aimskill_offset;
    }
    desiredang = vectoangles(v) + self.bot_badaimoffset;
    //dprint(" desired:", vtos(desiredang));
    if (desiredang.x >= 180)
        desiredang.x = desiredang.x - 360;
    desiredang.x = bound(-90, 0 - desiredang.x, 90);
    desiredang.z = self.v_angle.z;
    //dprint(" / ", vtos(desiredang));
    //if (self.bot_painintensity)
    //{
    //  // shake from pain
    //  desiredang = desiredang + randomvec() * self.bot_painintensity * 0.2;
    //}
    // calculate turn angles
    diffang = (desiredang - self.bot_olddesiredang);
    // wrap yaw turn
    diffang.y = diffang.y - floor(diffang.y / 360) * 360;
    if (diffang.y >= 180)
        diffang.y = diffang.y - 360;
    self.bot_olddesiredang = desiredang;
    //dprint(" diff:", vtos(diffang));
    delta_t = time-self.bot_prevaimtime;
    self.bot_prevaimtime = time;
    // Here we will try to anticipate the comming aiming direction
    self.bot_1st_order_aimfilter= self.bot_1st_order_aimfilter
        + (diffang * (1 / delta_t)    - self.bot_1st_order_aimfilter) * bound(0, autocvar_bot_ai_aimskill_order_filter_1st,1);
    self.bot_2nd_order_aimfilter= self.bot_2nd_order_aimfilter
        + (self.bot_1st_order_aimfilter - self.bot_2nd_order_aimfilter) * bound(0, autocvar_bot_ai_aimskill_order_filter_2nd,1);
    self.bot_3th_order_aimfilter= self.bot_3th_order_aimfilter
        + (self.bot_2nd_order_aimfilter - self.bot_3th_order_aimfilter) * bound(0, autocvar_bot_ai_aimskill_order_filter_3th,1);
    self.bot_4th_order_aimfilter= self.bot_4th_order_aimfilter
        + (self.bot_3th_order_aimfilter - self.bot_4th_order_aimfilter) * bound(0, autocvar_bot_ai_aimskill_order_filter_4th,1);
    self.bot_5th_order_aimfilter= self.bot_5th_order_aimfilter
        + (self.bot_4th_order_aimfilter - self.bot_5th_order_aimfilter) * bound(0, autocvar_bot_ai_aimskill_order_filter_5th,1);
    //blend = (bound(0,skill,10)*0.1)*pow(1-bound(0,skill,10)*0.05,2.5)*5.656854249; //Plot formule before changing !
    blend = bound(0,skill+self.bot_aimskill,10)*0.1;
    desiredang = desiredang + blend *
    (
          self.bot_1st_order_aimfilter * autocvar_bot_ai_aimskill_order_mix_1st
        + self.bot_2nd_order_aimfilter * autocvar_bot_ai_aimskill_order_mix_2nd
        + self.bot_3th_order_aimfilter * autocvar_bot_ai_aimskill_order_mix_3th
        + self.bot_4th_order_aimfilter * autocvar_bot_ai_aimskill_order_mix_4th
        + self.bot_5th_order_aimfilter * autocvar_bot_ai_aimskill_order_mix_5th
    );
    // calculate turn angles
    diffang = desiredang - self.bot_mouseaim;
    // wrap yaw turn
    diffang.y = diffang.y - floor(diffang.y / 360) * 360;
    if (diffang.y >= 180)
        diffang.y = diffang.y - 360;
    //dprint(" diff:", vtos(diffang));
    if (time >= self.bot_aimthinktime)
    {
        self.bot_aimthinktime = max(self.bot_aimthinktime + 0.5 - 0.05*(skill+self.bot_thinkskill), time);
        self.bot_mouseaim = self.bot_mouseaim + diffang * (1-random()*0.1*bound(1,10-(skill+self.bot_thinkskill),10));
    }
    //self.v_angle = self.v_angle + diffang * bound(0, r * frametime * (skill * 0.5 + 2), 1);
    diffang = self.bot_mouseaim - desiredang;
    // wrap yaw turn
    diffang.y = diffang.y - floor(diffang.y / 360) * 360;
    if (diffang.y >= 180)
        diffang.y = diffang.y - 360;
    desiredang = desiredang + diffang * bound(0,autocvar_bot_ai_aimskill_think,1);
    // calculate turn angles
    diffang = desiredang - self.v_angle;
    // wrap yaw turn
    diffang.y = diffang.y - floor(diffang.y / 360) * 360;
    if (diffang.y >= 180)
        diffang.y = diffang.y - 360;
    //dprint(" diff:", vtos(diffang));
    // jitter tracking
    dist = vlen(diffang);
    //diffang = diffang + randomvec() * (dist * 0.05 * (3.5 - bound(0, skill, 3)));
    // turn
    float r, fixedrate, blendrate;
    fixedrate = autocvar_bot_ai_aimskill_fixedrate / bound(1,dist,1000);
    blendrate = autocvar_bot_ai_aimskill_blendrate;
    r = max(fixedrate, blendrate);
    //self.v_angle = self.v_angle + diffang * bound(frametime, r * frametime * (2+skill*skill*0.05-random()*0.05*(10-skill)), 1);
    self.v_angle = self.v_angle + diffang * bound(delta_t, r * delta_t * (2+pow(skill+self.bot_mouseskill,3)*0.005-random()), 1);
    self.v_angle = self.v_angle * bound(0,autocvar_bot_ai_aimskill_mouse,1) + desiredang * bound(0,(1-autocvar_bot_ai_aimskill_mouse),1);
    //self.v_angle = self.v_angle + diffang * bound(0, r * frametime * (skill * 0.5 + 2), 1);
    //self.v_angle = self.v_angle + diffang * (1/ blendrate);
    self.v_angle_z = 0;
    self.v_angle_y = self.v_angle.y - floor(self.v_angle.y / 360) * 360;
    //dprint(" turn:", vtos(self.v_angle));
    makevectors(self.v_angle);
    shotorg = self.origin + self.view_ofs;
    shotdir = v_forward;
    //dprint(" dir:", vtos(v_forward));
    //te_lightning2(world, shotorg, shotorg + shotdir * 100);
    // calculate turn angles again
    //diffang = desiredang - self.v_angle;
    //diffang_y = diffang_y - floor(diffang_y / 360) * 360;
    //if (diffang_y >= 180)
    //  diffang_y = diffang_y - 360;
    //dprint("e ", vtos(diffang), " < ", ftos(maxfiredeviation), "\n");
    // decide whether to fire this time
    // note the maxfiredeviation is in degrees so this has to convert to radians first
    //if ((normalize(v) * shotdir) >= cos(maxfiredeviation * (3.14159265358979323846 / 180)))
    if ((normalize(v) * shotdir) >= cos(maxfiredeviation * (3.14159265358979323846 / 180)))
    if(vdist(trace_endpos-shotorg, <, 500 + 500 * bound(0, skill + self.bot_aggresskill, 10)) || random()*random()>bound(0,(skill+self.bot_aggresskill)*0.05,1))
        self.bot_firetimer = time + bound(0.1, 0.5-(skill+self.bot_aggresskill)*0.05, 0.5);
    //traceline(shotorg,shotorg+shotdir*1000,false,world);
    //dprint(ftos(maxfiredeviation),"\n");
    //dprint(" diff:", vtos(diffang), "\n");
    return self.bot_canfire && (time < self.bot_firetimer);
}
void bot_lagfunc (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4)
Definition at line 147 of file aim.qc.
References FL_INWATER, flags, random(), SELFPARAM, skill, and world.
Referenced by bot_clientconnect().
{SELFPARAM();
    if(self.flags & FL_INWATER)
    {
        self.bot_aimtarg = world;
        return;
    }
    self.bot_aimtarg = e1;
    self.bot_aimlatency = self.ping; // FIXME?  Shouldn't this be in the lag item?
    self.bot_aimselforigin = v1;
    self.bot_aimselfvelocity = v2;
    self.bot_aimtargorigin = v3;
    self.bot_aimtargvelocity = v4;
    if(skill <= 0)
        self.bot_canfire = (random() < 0.8);
    else if(skill <= 1)
        self.bot_canfire = (random() < 0.9);
    else if(skill <= 2)
        self.bot_canfire = (random() < 0.95);
    else
        self.bot_canfire = 1;
}
vector bot_shotlead (vector targorigin, vector targvelocity, float shotspeed, float shotdelay)
Definition at line 315 of file aim.qc.
References shotorg, and vlen().
Referenced by bot_aim().
{
    // Try to add code here that predicts gravity effect here, no clue HOW to though ... well not yet atleast...
    return targorigin + targvelocity * (shotdelay + vlen(targorigin - shotorg) / shotspeed);
}
float bot_shouldattack (entity e)
Definition at line 109 of file aim.qc.
References bot_ignore_bots, FL_NOTARGET, IS_BOT_CLIENT, IS_DEAD, MUTATOR_CALLHOOK, SELFPARAM, and teamplay.
Referenced by bot_aim(), havocbot_chooseenemy(), and havocbot_goalrating_enemyplayers().
{SELFPARAM();
    if (e.team == self.team)
    {
        if (e == self)
            return false;
        if (teamplay)
        if (e.team != 0)
            return false;
    }
    if(STAT(FROZEN, e))
        return false;
    if(teamplay)
    {
        if(e.team==0)
            return false;
    }
    else if(bot_ignore_bots)
        if(IS_BOT_CLIENT(e))
            return false;
    if (!e.takedamage)
        return false;
    if (IS_DEAD(e))
        return false;
    if (e.BUTTON_CHAT)
        return false;
    if(e.flags & FL_NOTARGET)
        return false;
    if(MUTATOR_CALLHOOK(BotShouldAttack, e))
        return false;
    return true;
}
float findtrajectorywithleading (vector org, vector m1, vector m2, entity targ, float shotspeed, float shotspeedupward, float maxtime, float shotdelay, entity ignore)
Definition at line 13 of file aim.qc.
References findtrajectory_velocity, MOVETYPE_NONE, normalize(), SOLID_BBOX, SOLID_NOT, trace_endpos, trace_ent, tracetossent, tracetossfaketarget, vector(), and vlen().
Referenced by bot_aim().
{
    float c, savesolid, shottime;
    vector dir, end, v, o;
    if (shotspeed < 1)
        return false; // could cause division by zero if calculated
    if (targ.solid < SOLID_BBOX) // SOLID_NOT and SOLID_TRIGGER
        return false; // could never hit it
    if (!tracetossent)
        tracetossent = new(tracetossent);
    tracetossent.owner = ignore;
    setsize(tracetossent, m1, m2);
    savesolid = targ.solid;
    targ.solid = SOLID_NOT;
    o = (targ.absmin + targ.absmax) * 0.5;
    shottime = ((vlen(o - org) / shotspeed) + shotdelay);
    v = targ.velocity * shottime + o;
    tracebox(o, targ.mins, targ.maxs, v, false, targ);
    v = trace_endpos;
    end = v + (targ.mins + targ.maxs) * 0.5;
    if ((vlen(end - org) / shotspeed + 0.2) > maxtime)
    {
        // out of range
        targ.solid = savesolid;
        return false;
    }
    if (!tracetossfaketarget)
        tracetossfaketarget = new(tracetossfaketarget);
    tracetossfaketarget.solid = savesolid;
    tracetossfaketarget.movetype = targ.movetype;
    _setmodel(tracetossfaketarget, targ.model); // no low precision
    tracetossfaketarget.model = targ.model;
    tracetossfaketarget.modelindex = targ.modelindex;
    setsize(tracetossfaketarget, targ.mins, targ.maxs);
    setorigin(tracetossfaketarget, v);
    c = 0;
    dir = normalize(end - org);
    while (c < 10) // 10 traces
    {
        setorigin(tracetossent, org); // reset
        tracetossent.velocity = findtrajectory_velocity = normalize(dir) * shotspeed + shotspeedupward * '0 0 1';
        tracetoss(tracetossent, ignore); // love builtin functions...
        if (trace_ent == tracetossfaketarget) // done
        {
            targ.solid = savesolid;
            // make it disappear
            tracetossfaketarget.solid = SOLID_NOT;
            tracetossfaketarget.movetype = MOVETYPE_NONE;
            tracetossfaketarget.model = "";
            tracetossfaketarget.modelindex = 0;
            // relink to remove it from physics considerations
            setorigin(tracetossfaketarget, v);
            return true;
        }
        dir.z = dir.z + 0.1; // aim up a little more
        c = c + 1;
    }
    targ.solid = savesolid;
    // make it disappear
    tracetossfaketarget.solid = SOLID_NOT;
    tracetossfaketarget.movetype = MOVETYPE_NONE;
    tracetossfaketarget.model = "";
    tracetossfaketarget.modelindex = 0;
    // relink to remove it from physics considerations
    setorigin(tracetossfaketarget, v);
    // leave a valid one even if it won't reach
    findtrajectory_velocity = normalize(end - org) * shotspeed + shotspeedupward * '0 0 1';
    return false;
}
float lag_additem (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4)
Definition at line 98 of file aim.qc.
References f1, f2, lag1_time, lag2_time, lag3_time, lag4_time, lag5_time, and SELFPARAM.
Referenced by havocbot_aim().
{SELFPARAM();
    if (self.lag1_time == 0) {self.lag1_time = t;self.lag1_float1 = f1;self.lag1_float2 = f2;self.lag1_entity1 = e1;self.lag1_vec1 = v1;self.lag1_vec2 = v2;self.lag1_vec3 = v3;self.lag1_vec4 = v4;return true;}
    if (self.lag2_time == 0) {self.lag2_time = t;self.lag2_float1 = f1;self.lag2_float2 = f2;self.lag2_entity1 = e1;self.lag2_vec1 = v1;self.lag2_vec2 = v2;self.lag2_vec3 = v3;self.lag2_vec4 = v4;return true;}
    if (self.lag3_time == 0) {self.lag3_time = t;self.lag3_float1 = f1;self.lag3_float2 = f2;self.lag3_entity1 = e1;self.lag3_vec1 = v1;self.lag3_vec2 = v2;self.lag3_vec3 = v3;self.lag3_vec4 = v4;return true;}
    if (self.lag4_time == 0) {self.lag4_time = t;self.lag4_float1 = f1;self.lag4_float2 = f2;self.lag4_entity1 = e1;self.lag4_vec1 = v1;self.lag4_vec2 = v2;self.lag4_vec3 = v3;self.lag4_vec4 = v4;return true;}
    if (self.lag5_time == 0) {self.lag5_time = t;self.lag5_float1 = f1;self.lag5_float2 = f2;self.lag5_entity1 = e1;self.lag5_vec1 = v1;self.lag5_vec2 = v2;self.lag5_vec3 = v3;self.lag5_vec4 = v4;return true;}
    // no room for it (what is the best thing to do here??)
    return false;
}
void lag_update ()
Definition at line 89 of file aim.qc.
References lag1_entity1, lag1_float1, lag1_float2, lag1_time, lag1_vec1, lag1_vec2, lag1_vec3, lag1_vec4, lag2_entity1, lag2_float1, lag2_float2, lag2_time, lag2_vec1, lag2_vec2, lag2_vec3, lag2_vec4, lag3_entity1, lag3_float1, lag3_float2, lag3_time, lag3_vec1, lag3_vec2, lag3_vec3, lag3_vec4, lag4_entity1, lag4_float1, lag4_float2, lag4_time, lag4_vec1, lag4_vec2, lag4_vec3, lag4_vec4, lag5_entity1, lag5_float1, lag5_float2, lag5_time, lag5_vec1, lag5_vec2, lag5_vec3, lag5_vec4, SELFPARAM, and time.
Referenced by havocbot_ai().
{SELFPARAM();
    if (self.lag1_time) if (time > self.lag1_time) {self.lag_func(self.lag1_time, self.lag1_float1, self.lag1_float2, self.lag1_entity1, self.lag1_vec1, self.lag1_vec2, self.lag1_vec3, self.lag1_vec4);self.lag1_time = 0;}
    if (self.lag2_time) if (time > self.lag2_time) {self.lag_func(self.lag2_time, self.lag2_float1, self.lag2_float2, self.lag2_entity1, self.lag2_vec1, self.lag2_vec2, self.lag2_vec3, self.lag2_vec4);self.lag2_time = 0;}
    if (self.lag3_time) if (time > self.lag3_time) {self.lag_func(self.lag3_time, self.lag3_float1, self.lag3_float2, self.lag3_entity1, self.lag3_vec1, self.lag3_vec2, self.lag3_vec3, self.lag3_vec4);self.lag3_time = 0;}
    if (self.lag4_time) if (time > self.lag4_time) {self.lag_func(self.lag4_time, self.lag4_float1, self.lag4_float2, self.lag4_entity1, self.lag4_vec1, self.lag4_vec2, self.lag4_vec3, self.lag4_vec4);self.lag4_time = 0;}
    if (self.lag5_time) if (time > self.lag5_time) {self.lag_func(self.lag5_time, self.lag5_float1, self.lag5_float2, self.lag5_entity1, self.lag5_vec1, self.lag5_vec2, self.lag5_vec3, self.lag5_vec4);self.lag5_time = 0;}
}
void (float t, float f1, float f2, entity e1, vector v1, vector v2, vector v3, vector v4)
Variable Documentation
vector bot_1st_order_aimfilter
Definition at line 71 of file aim.qh.
Referenced by bot_aimdir().
vector bot_2nd_order_aimfilter
Definition at line 72 of file aim.qh.
vector bot_3th_order_aimfilter
Definition at line 73 of file aim.qh.
vector bot_4th_order_aimfilter
Definition at line 74 of file aim.qh.
vector bot_5th_order_aimfilter
Definition at line 75 of file aim.qh.
float bot_aimlatency
Definition at line 67 of file aim.qh.
Referenced by bot_aim().
vector bot_aimselforigin
Definition at line 78 of file aim.qh.
vector bot_aimselfvelocity
Definition at line 79 of file aim.qh.
entity bot_aimtarg
Definition at line 83 of file aim.qh.
Referenced by bot_aim(), and havocbot_ai().
vector bot_aimtargorigin
Definition at line 80 of file aim.qh.
Referenced by bot_aim().
vector bot_aimtargvelocity
Definition at line 81 of file aim.qh.
Referenced by bot_aim().
float bot_aimthinktime
Definition at line 64 of file aim.qh.
Referenced by bot_aimdir().
vector bot_badaimoffset
Definition at line 70 of file aim.qh.
float bot_badaimtime
Definition at line 63 of file aim.qh.
Referenced by bot_aimdir().
float bot_firetimer
Definition at line 66 of file aim.qh.
vector bot_mouseaim
Definition at line 69 of file aim.qh.
vector bot_olddesiredang
Definition at line 76 of file aim.qh.
float bot_prevaimtime
Definition at line 65 of file aim.qh.
vector findtrajectory_velocity
Definition at line 9 of file aim.qh.
Referenced by bot_aim(), and findtrajectorywithleading().
entity lag1_entity1
Definition at line 21 of file aim.qh.
Referenced by lag_update().
float lag1_float1
Definition at line 19 of file aim.qh.
Referenced by lag_update().
float lag1_float2
Definition at line 20 of file aim.qh.
Referenced by lag_update().
float lag1_time
Definition at line 18 of file aim.qh.
Referenced by lag_additem(), and lag_update().
vector lag1_vec1
Definition at line 22 of file aim.qh.
Referenced by lag_update().
vector lag1_vec2
Definition at line 23 of file aim.qh.
Referenced by lag_update().
vector lag1_vec3
Definition at line 24 of file aim.qh.
Referenced by lag_update().
vector lag1_vec4
Definition at line 25 of file aim.qh.
Referenced by lag_update().
entity lag2_entity1
Definition at line 30 of file aim.qh.
Referenced by lag_update().
float lag2_float1
Definition at line 28 of file aim.qh.
Referenced by lag_update().
float lag2_float2
Definition at line 29 of file aim.qh.
Referenced by lag_update().
float lag2_time
Definition at line 27 of file aim.qh.
Referenced by lag_additem(), and lag_update().
vector lag2_vec1
Definition at line 31 of file aim.qh.
Referenced by lag_update().
vector lag2_vec2
Definition at line 32 of file aim.qh.
Referenced by lag_update().
vector lag2_vec3
Definition at line 33 of file aim.qh.
Referenced by lag_update().
vector lag2_vec4
Definition at line 34 of file aim.qh.
Referenced by lag_update().
entity lag3_entity1
Definition at line 39 of file aim.qh.
Referenced by lag_update().
float lag3_float1
Definition at line 37 of file aim.qh.
Referenced by lag_update().
float lag3_float2
Definition at line 38 of file aim.qh.
Referenced by lag_update().
float lag3_time
Definition at line 36 of file aim.qh.
Referenced by lag_additem(), and lag_update().
vector lag3_vec1
Definition at line 40 of file aim.qh.
Referenced by lag_update().
vector lag3_vec2
Definition at line 41 of file aim.qh.
Referenced by lag_update().
vector lag3_vec3
Definition at line 42 of file aim.qh.
Referenced by lag_update().
vector lag3_vec4
Definition at line 43 of file aim.qh.
Referenced by lag_update().
entity lag4_entity1
Definition at line 48 of file aim.qh.
Referenced by lag_update().
float lag4_float1
Definition at line 46 of file aim.qh.
Referenced by lag_update().
float lag4_float2
Definition at line 47 of file aim.qh.
Referenced by lag_update().
float lag4_time
Definition at line 45 of file aim.qh.
Referenced by lag_additem(), and lag_update().
vector lag4_vec1
Definition at line 49 of file aim.qh.
Referenced by lag_update().
vector lag4_vec2
Definition at line 50 of file aim.qh.
Referenced by lag_update().
vector lag4_vec3
Definition at line 51 of file aim.qh.
Referenced by lag_update().
vector lag4_vec4
Definition at line 52 of file aim.qh.
Referenced by lag_update().
entity lag5_entity1
Definition at line 57 of file aim.qh.
Referenced by lag_update().
float lag5_float1
Definition at line 55 of file aim.qh.
Referenced by lag_update().
float lag5_float2
Definition at line 56 of file aim.qh.
Referenced by lag_update().
float lag5_time
Definition at line 54 of file aim.qh.
Referenced by lag_additem(), and lag_update().
vector lag5_vec1
Definition at line 58 of file aim.qh.
Referenced by lag_update().
vector lag5_vec2
Definition at line 59 of file aim.qh.
Referenced by lag_update().
vector lag5_vec3
Definition at line 60 of file aim.qh.
Referenced by lag_update().
vector lag5_vec4
Definition at line 61 of file aim.qh.
Referenced by lag_update().
vector shotdir
Definition at line 14 of file aim.qh.
Referenced by bot_aim(), and bot_aimdir().
vector shotorg
Definition at line 13 of file aim.qh.
Referenced by bot_aim(), bot_aimdir(), and bot_shotlead().
entity tracetossent
Definition at line 7 of file aim.qh.
Referenced by findtrajectorywithleading().
entity tracetossfaketarget
Definition at line 8 of file aim.qh.
Referenced by findtrajectorywithleading().