Xonotic: common/mapobjects/platforms.qh File Reference
platforms.qh File Reference
Functions
void plat_center_touch (entity this, entity toucher)
void plat_crush (entity this, entity blocker)
void plat_go_down (entity this)
void plat_go_up (entity this)
void plat_outside_touch (entity this, entity toucher)
void plat_trigger_use (entity this, entity actor, entity trigger)
Variables
float dmg
float dmgtime2
const int PLAT_LOW_TRIGGER = BIT(0)
Function Documentation
void plat_center_touch (entity this, entity toucher)
Definition at line 90 of file platforms.qc.
References enemy, GetResource(), IS_DEAD, IS_PLAYER, plat_go_up(), RES_HEALTH, STATE_BOTTOM, and STATE_TOP.
Referenced by plat_spawn_inside_trigger().
 {
 #ifdef SVQC
     if (!toucher.iscreature)
         return;
     if (GetResource(toucher, RES_HEALTH) <= 0)
         return;
 #elif defined(CSQC)
     if (!IS_PLAYER(toucher))
         return;
     if(IS_DEAD(toucher))
         return;
 #endif
     if (this.enemy.state == STATE_BOTTOM) {
         plat_go_up(this.enemy);
     } else if (this.enemy.state == STATE_TOP)
         this.enemy.nextthink = this.enemy.ltime + 1;
 }
void plat_crush (entity this, entity blocker)
Definition at line 138 of file platforms.qc.
References CRUSH, Damage(), DAMAGE_NO, dmg, DMG_NOWEP, IS_DEAD, plat_go_down(), plat_go_up(), spawnflags, state, STATE_DOWN, and STATE_UP.
 {
     if((this.spawnflags & CRUSH) && (blocker.takedamage != DAMAGE_NO))
     { // KIll Kill Kill!!
 #ifdef SVQC
         Damage (blocker, this, this, 10000, DEATH_HURTTRIGGER.m_id, DMG_NOWEP, blocker.origin, '0 0 0');
 #endif
     }
     else
     {
 #ifdef SVQC
         if((this.dmg) && (blocker.takedamage != DAMAGE_NO))
         {   // Shall we bite?
             Damage (blocker, this, this, this.dmg, DEATH_HURTTRIGGER.m_id, DMG_NOWEP, blocker.origin, '0 0 0');
             // Gib dead/dying stuff
             if(IS_DEAD(blocker))
                 Damage (blocker, this, this, 10000, DEATH_HURTTRIGGER.m_id, DMG_NOWEP, blocker.origin, '0 0 0');
         }
 #endif
         if (this.state == STATE_UP)
             plat_go_down (this);
         else if (this.state == STATE_DOWN)
             plat_go_up (this);
     // when in other states, then the plat_crush event came delayed after
     // plat state already had changed
     // this isn't a bug per se!
     }
 }
void plat_go_down (entity this)
Definition at line 76 of file platforms.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, noise, plat_hit_bottom(), pos2, speed, state, STATE_DOWN, SUB_CalcMove(), TSPEED_LINEAR, and VOL_BASE.
Referenced by plat_crush(), plat_hit_top(), plat_outside_touch(), plat_trigger_use(), and plat_use().
 {
     _sound (this, CH_TRIGGER_SINGLE, this.noise, VOL_BASE, ATTEN_NORM);
     this.state = STATE_DOWN;
     SUB_CalcMove (this, this.pos2, TSPEED_LINEAR, this.speed, plat_hit_bottom);
 }
void plat_go_up (entity this)
Definition at line 83 of file platforms.qc.
References _sound, ATTEN_NORM, CH_TRIGGER_SINGLE, noise, plat_hit_top(), pos1, speed, state, STATE_UP, SUB_CalcMove(), TSPEED_LINEAR, and VOL_BASE.
Referenced by plat_center_touch(), and plat_crush().
 {
     _sound (this, CH_TRIGGER_SINGLE, this.noise, VOL_BASE, ATTEN_NORM);
     this.state = STATE_UP;
     SUB_CalcMove (this, this.pos1, TSPEED_LINEAR, this.speed, plat_hit_top);
 }
void plat_outside_touch (entity this, entity toucher)
Definition at line 111 of file platforms.qc.
References enemy, entity(), GetResource(), IS_PLAYER, plat_go_down(), RES_HEALTH, and STATE_TOP.
 {
 #ifdef SVQC
     if (!toucher.iscreature)
         return;
     if (GetResource(toucher, RES_HEALTH) <= 0)
         return;
 #elif defined(CSQC)
     if (!IS_PLAYER(toucher))
         return;
 #endif
     if (this.enemy.state == STATE_TOP) {
         entity e = this.enemy;
         plat_go_down(e);
     }
 }
void plat_trigger_use (entity this, entity actor, entity trigger)
Definition at line 130 of file platforms.qc.
References getthink, and plat_go_down().
Referenced by plat_reset().
 {
     if (getthink(this))
         return;     // already activated
     plat_go_down(this);
 }
Variable Documentation
float dmg
Definition at line 15 of file platforms.qh.
Referenced by assault_objective_decrease_use(), buff_Vengeance_DelayedDamage(), CL_ExteriorWeaponentity_Think(), door_blocked(), door_generic_plat_blocked(), door_reset(), generic_plat_blocked(), plat_crush(), spawnfunc(), STATIC_INIT(), swamp_touch(), swampslug_think(), and train_next().
float dmgtime2
Definition at line 6 of file platforms.qh.
Referenced by generic_plat_blocked(), and train_next().
const int PLAT_LOW_TRIGGER = BIT(0)
Definition at line 4 of file platforms.qh.
Referenced by plat_spawn_inside_trigger().