Xonotic: common/gamemodes/gamemode/race/sv_race.qc File Reference
sv_race.qc File Reference
#include "sv_race.qh"
#include <server/client.qh>
#include <server/world.qh>
#include <server/gamelog.qh>
#include <server/intermission.qh>
#include <server/race.qh>
#include <common/ent_cs.qh>
#include <common/mapobjects/triggers.qh>
Macros
#define autocvar_g_race_laps_limit cvar("g_race_laps_limit")
Functions
void havocbot_role_race (entity this)
MUTATOR_HOOKFUNCTION (rc, ClientKill)
MUTATOR_HOOKFUNCTION (rc, AbortSpeedrun)
MUTATOR_HOOKFUNCTION (rc, PlayerPhysics)
MUTATOR_HOOKFUNCTION (rc, reset_map_global)
MUTATOR_HOOKFUNCTION (rc, ClientConnect)
MUTATOR_HOOKFUNCTION (rc, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (rc, PlayerSpawn)
MUTATOR_HOOKFUNCTION (rc, PutClientInServer)
MUTATOR_HOOKFUNCTION (rc, PlayerDies)
MUTATOR_HOOKFUNCTION (rc, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (rc, GetPressedKeys)
MUTATOR_HOOKFUNCTION (rc, ForbidPlayerScore_Clear)
MUTATOR_HOOKFUNCTION (rc, TeamBalance_CheckAllowedTeams, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (rc, Scores_CountFragsRemaining)
MUTATOR_HOOKFUNCTION (rc, GetRecords)
MUTATOR_HOOKFUNCTION (rc, HideTeamNagger)
MUTATOR_HOOKFUNCTION (rc, FixClientCvars)
MUTATOR_HOOKFUNCTION (rc, CheckRules_World)
MUTATOR_HOOKFUNCTION (rc, ReadLevelCvars)
void race_EventLog (string mode, entity actor)
void race_Initialize ()
void race_ScoreRules ()
void rc_SetLimits ()
float WinningCondition_QualifyingThenRace (float limit)
float WinningCondition_Race (float fraglimit)
Variables
float autocvar_g_race_qualifying_timelimit
float autocvar_g_race_qualifying_timelimit_override
int autocvar_g_race_teams
float race_checkpoint
Macro Definition Documentation
#define autocvar_g_race_laps_limit cvar("g_race_laps_limit")
Definition at line 11 of file sv_race.qc.
Referenced by rc_SetLimits().
Function Documentation
void havocbot_role_race (entity this)
Definition at line 18 of file sv_race.qc.
References g_racecheckpoints, IL_EACH, IS_DEAD, LABEL, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), navigation_routerating(), and race_checkpoint.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         bool raw_touch_check = true;
         int cp = this.race_checkpoint;
         LABEL(search_racecheckpoints)
         IL_EACH(g_racecheckpoints, true,
         {
             if(it.cnt == cp || cp == -1)
             {
                 // redirect bot to next goal if it touched the waypoint of an untouchable checkpoint
                 // e.g. checkpoint in front of Stormkeep's warpzone
                 // the same workaround is applied in CTS game mode
                 if (raw_touch_check && vdist(this.origin - it.nearestwaypoint.origin, <, 30))
                 {
                     cp = race_NextCheckpoint(cp);
                     raw_touch_check = false;
                     goto search_racecheckpoints;
                 }
                 navigation_routerating(this, it, 1000000, 5000);
             }
         });
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
MUTATOR_HOOKFUNCTION (rc , ClientKill)
Definition at line 117 of file sv_race.qc.
References g_race_qualifying, and M_ARGV.
 {
     if(g_race_qualifying)
         M_ARGV(1, float) = 0; // killtime
 }
MUTATOR_HOOKFUNCTION (rc , AbortSpeedrun)
Definition at line 123 of file sv_race.qc.
References autocvar_g_allow_checkpoints, entity(), M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     if(autocvar_g_allow_checkpoints)
         race_PreparePlayer(player); // nice try
 }
MUTATOR_HOOKFUNCTION (rc , PlayerPhysics)
Definition at line 131 of file sv_race.qc.
References CS(), entity(), fabs(), floor(), IS_PLAYER, M_ARGV, M_SQRT1_2, movement, MOVETYPE_NONE, set_movetype(), time, vector(), and vlen().
 {
     entity player = M_ARGV(0, entity);
     float dt = M_ARGV(1, float);
     player.race_movetime_frac += dt;
     float f = floor(player.race_movetime_frac);
     player.race_movetime_frac -= f;
     player.race_movetime_count += f;
     player.race_movetime = player.race_movetime_frac + player.race_movetime_count;
 #ifdef SVQC
     if(IS_PLAYER(player))
     {
         if (player.race_penalty)
             if (time > player.race_penalty)
                 player.race_penalty = 0;
         if(player.race_penalty)
         {
             player.velocity = '0 0 0';
             set_movetype(player, MOVETYPE_NONE);
             player.disableclientprediction = 2;
         }
     }
 #endif
     // force kbd movement for fairness
     float wishspeed;
     vector wishvel;
     // if record times matter
     // ensure nothing EVIL is being done (i.e. div0_evade)
     // this hinders joystick users though
     // but it still gives SOME analog control
     wishvel.x = fabs(CS(player).movement.x);
     wishvel.y = fabs(CS(player).movement.y);
     if(wishvel.x != 0 && wishvel.y != 0 && wishvel.x != wishvel.y)
     {
         wishvel.z = 0;
         wishspeed = vlen(wishvel);
         if(wishvel.x >= 2 * wishvel.y)
         {
             // pure X motion
             if(CS(player).movement.x > 0)
                 CS(player).movement_x = wishspeed;
             else
                 CS(player).movement_x = -wishspeed;
             CS(player).movement_y = 0;
         }
         else if(wishvel.y >= 2 * wishvel.x)
         {
             // pure Y motion
             CS(player).movement_x = 0;
             if(CS(player).movement.y > 0)
                 CS(player).movement_y = wishspeed;
             else
                 CS(player).movement_y = -wishspeed;
         }
         else
         {
             // diagonal
             if(CS(player).movement.x > 0)
                 CS(player).movement_x = M_SQRT1_2 * wishspeed;
             else
                 CS(player).movement_x = -M_SQRT1_2 * wishspeed;
             if(CS(player).movement.y > 0)
                 CS(player).movement_y = M_SQRT1_2 * wishspeed;
             else
                 CS(player).movement_y = -M_SQRT1_2 * wishspeed;
         }
     }
 }
MUTATOR_HOOKFUNCTION (rc , reset_map_global)
Definition at line 204 of file sv_race.qc.
References cvar_set(), FOREACH_CLIENT, ftos(), g_race_qualifying, independent_players, NULL, PlayerScore_Sort(), race_ClearRecords(), race_EventLog(), race_fraglimit, race_leadlimit, race_place, race_ScoreRules(), race_timelimit, and Score_NicePrint().
 {
     float s;
     Score_NicePrint(NULL);
     race_ClearRecords();
     PlayerScore_Sort(race_place, 0, 1, 0);
     FOREACH_CLIENT(true, {
         if(it.race_place)
         {
             s = GameRules_scoring_add(it, RACE_FASTEST, 0);
             if(!s)
                 it.race_place = 0;
         }
         race_EventLog(ftos(it.race_place), it);
     });
     if(g_race_qualifying == 2)
     {
         g_race_qualifying = 0;
         independent_players = 0;
         cvar_set("fraglimit", ftos(race_fraglimit));
         cvar_set("leadlimit", ftos(race_leadlimit));
         cvar_set("timelimit", ftos(race_timelimit));
         race_ScoreRules();
     }
 }
MUTATOR_HOOKFUNCTION (rc , ClientConnect)
Definition at line 234 of file sv_race.qc.
References autocvar_g_cts_send_rankings_cnt, db_get(), entity(), GetMapname(), IS_REAL_CLIENT, M_ARGV, min(), msg_entity, MSG_ONE, race_PreparePlayer(), RACE_RECORD, race_send_rankings_cnt(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendRankings(), ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, stof(), strcat(), and uid2name().
 {
     entity player = M_ARGV(0, entity);
     race_PreparePlayer(player);
     player.race_checkpoint = -1;
     string rr = RACE_RECORD;
     if(IS_REAL_CLIENT(player))
     {
         msg_entity = player;
         race_send_recordtime(MSG_ONE);
         race_send_speedaward(MSG_ONE);
         speedaward_alltimebest = stof(db_get(ServerProgsDB, strcat(GetMapname(), rr, "speed/speed")));
         speedaward_alltimebest_holder = uid2name(db_get(ServerProgsDB, strcat(GetMapname(), rr, "speed/crypto_idfp")));
         race_send_speedaward_alltimebest(MSG_ONE);
         float i;
         int m = min(RANKINGS_CNT, autocvar_g_cts_send_rankings_cnt);
         race_send_rankings_cnt(MSG_ONE);
         for (i = 1; i <= m; ++i)
         {
             race_SendRankings(i, 0, 0, MSG_ONE);
         }
     }
 }
MUTATOR_HOOKFUNCTION (rc , MakePlayerObserver)
Definition at line 263 of file sv_race.qc.
References entity(), FRAGS_PLAYER_OUT_OF_GAME, FRAGS_SPECTATOR, g_race_qualifying, GameRules_scoring_add, M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     if(g_race_qualifying)
     {
         if(GameRules_scoring_add(player, RACE_FASTEST, 0))
             player.frags = FRAGS_PLAYER_OUT_OF_GAME;
         else
             player.frags = FRAGS_SPECTATOR;
     }
     race_PreparePlayer(player);
     player.race_checkpoint = -1;
 }
MUTATOR_HOOKFUNCTION (rc , PlayerSpawn)
Definition at line 279 of file sv_race.qc.
References entity(), M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     entity spawn_spot = M_ARGV(1, entity);
     if(spawn_spot.target == "")
         // Emergency: this wasn't a real spawnpoint. Can this ever happen?
         race_PreparePlayer(player);
     // if we need to respawn, do it right
     player.race_respawn_checkpoint = player.race_checkpoint;
     player.race_respawn_spotref = spawn_spot;
     player.race_place = 0;
 }
MUTATOR_HOOKFUNCTION (rc , PutClientInServer)
Definition at line 295 of file sv_race.qc.
References CS(), entity(), FRAGS_SPECTATOR, g_race_qualifying, IS_PLAYER, killcount, M_ARGV, race_AbandonRaceCheck(), race_PreparePlayer(), and race_RetractPlayer().
 {
     entity player = M_ARGV(0, entity);
     if(IS_PLAYER(player))
     if(!game_stopped)
     {
         if(CS(player).killcount == FRAGS_SPECTATOR /* initial spawn */ || g_race_qualifying) // spawn
             race_PreparePlayer(player);
         else // respawn
             race_RetractPlayer(player);
         race_AbandonRaceCheck(player);
     }
 }
MUTATOR_HOOKFUNCTION (rc , PlayerDies)
Definition at line 311 of file sv_race.qc.
References entity(), M_ARGV, race_AbandonRaceCheck(), and RESPAWN_FORCE.
 {
     entity frag_target = M_ARGV(2, entity);
     frag_target.respawn_flags |= RESPAWN_FORCE;
     race_AbandonRaceCheck(frag_target);
 }
MUTATOR_HOOKFUNCTION (rc , HavocBot_ChooseRole)
Definition at line 319 of file sv_race.qc.
References entity(), havocbot_role_race(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     bot.havocbot_role = havocbot_role_race;
     return true;
 }
MUTATOR_HOOKFUNCTION (rc , GetPressedKeys)
Definition at line 327 of file sv_race.qc.
References CS(), db_put(), entity(), ftos(), GetMapname(), IS_OBSERVER, M_ARGV, MSG_ALL, RACE_RECORD, race_send_speedaward(), race_send_speedaward_alltimebest(), ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, speedaward_alltimebest_uid, speedaward_holder, speedaward_lastsent, speedaward_lastupdate, speedaward_speed, speedaward_uid, strcat(), strcpy, strzone(), time, uid2name(), vdist, and vlen().
 {
     entity player = M_ARGV(0, entity);
     if(CS(player).cvar_cl_allow_uidtracking == 1 && CS(player).cvar_cl_allow_uid2name == 1)
     {
         if (!player.stored_netname)
             player.stored_netname = strzone(uid2name(player.crypto_idfp));
         if(player.stored_netname != player.netname)
         {
             db_put(ServerProgsDB, strcat("/uid2name/", player.crypto_idfp), player.netname);
             strcpy(player.stored_netname, player.netname);
         }
     }
     if (!IS_OBSERVER(player))
     {
         if(vdist(player.velocity - player.velocity_z * '0 0 1', >, speedaward_speed))
         {
             speedaward_speed = vlen(player.velocity - player.velocity_z * '0 0 1');
             speedaward_holder = player.netname;
             speedaward_uid = player.crypto_idfp;
             speedaward_lastupdate = time;
         }
         if (speedaward_speed > speedaward_lastsent && time - speedaward_lastupdate > 1)
         {
             string rr = RACE_RECORD;
             race_send_speedaward(MSG_ALL);
             speedaward_lastsent = speedaward_speed;
             if (speedaward_speed > speedaward_alltimebest && speedaward_uid != "")
             {
                 speedaward_alltimebest = speedaward_speed;
                 speedaward_alltimebest_holder = speedaward_holder;
                 speedaward_alltimebest_uid = speedaward_uid;
                 db_put(ServerProgsDB, strcat(GetMapname(), rr, "speed/speed"), ftos(speedaward_alltimebest));
                 db_put(ServerProgsDB, strcat(GetMapname(), rr, "speed/crypto_idfp"), speedaward_alltimebest_uid);
                 race_send_speedaward_alltimebest(MSG_ALL);
             }
         }
     }
 }
MUTATOR_HOOKFUNCTION (rc , ForbidPlayerScore_Clear)
Definition at line 369 of file sv_race.qc.
References g_race_qualifying.
 {
     if(g_race_qualifying)
         return true; // in qualifying, you don't lose score by observing
 }
MUTATOR_HOOKFUNCTION (rc , TeamBalance_CheckAllowedTeams , CBC_ORDER_EXCLUSIVE)
Definition at line 375 of file sv_race.qc.
References M_ARGV, and race_teams.
 {
     M_ARGV(0, float) = race_teams;
     return true;
 }
MUTATOR_HOOKFUNCTION (rc , Scores_CountFragsRemaining)
Definition at line 381 of file sv_race.qc.
References g_race_qualifying.
 {
     // announce remaining frags if not in qualifying mode
     if(!g_race_qualifying)
         return true;
 }
MUTATOR_HOOKFUNCTION (rc , GetRecords)
Definition at line 388 of file sv_race.qc.
References M_ARGV, MapInfo_count, MapInfo_Get_ByID(), MapInfo_Map_bspname, race_readName(), race_readTime(), strcat(), and TIME_ENCODED_TOSTRING.
 {
     int record_page = M_ARGV(0, int);
     string ret_string = M_ARGV(1, string);
     for(int i = record_page * 200; i < MapInfo_count && i < record_page * 200 + 200; ++i)
     {
         if(MapInfo_Get_ByID(i))
         {
             float r = race_readTime(MapInfo_Map_bspname, 1);
             if(!r)
                 continue;
             string h = race_readName(MapInfo_Map_bspname, 1);
             ret_string = strcat(ret_string, strpad(32, MapInfo_Map_bspname), " ", strpad(-8, TIME_ENCODED_TOSTRING(r)), " ", h, "\n");
         }
     }
     M_ARGV(1, string) = ret_string;
 }
MUTATOR_HOOKFUNCTION (rc , HideTeamNagger)
Definition at line 410 of file sv_race.qc.
 {
     return true; // doesn't work so well
 }
MUTATOR_HOOKFUNCTION (rc , FixClientCvars)
Definition at line 415 of file sv_race.qc.
References entity(), M_ARGV, and stuffcmd.
 {
     entity player = M_ARGV(0, entity);
     stuffcmd(player, "cl_cmd settemp cl_movecliptokeyboard 2\n");
 }
MUTATOR_HOOKFUNCTION (rc , CheckRules_World)
Definition at line 422 of file sv_race.qc.
References g_race_qualifying, M_ARGV, WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
 {
     float checkrules_timelimit = M_ARGV(1, float);
     float checkrules_fraglimit = M_ARGV(2, float);
     if(checkrules_timelimit >= 0)
     {
         if(!g_race_qualifying)
         {
             M_ARGV(0, float) = WinningCondition_Race(checkrules_fraglimit);
             return true;
         }
         else if(g_race_qualifying == 2)
         {
             M_ARGV(0, float) = WinningCondition_QualifyingThenRace(checkrules_fraglimit);
             return true;
         }
     }
 }
MUTATOR_HOOKFUNCTION (rc , ReadLevelCvars)
Definition at line 442 of file sv_race.qc.
References g_race_qualifying, and warmup_stage.
 {
     if(g_race_qualifying == 2)
         warmup_stage = 0;
 }
void race_EventLog (string mode, entity actor)
Definition at line 73 of file sv_race.qc.
References autocvar_sv_eventlog, ftos(), GameLogEcho(), NULL, and strcat().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":race:", mode, ":", ((actor != NULL) ? (strcat(":", ftos(actor.playerid))) : "")));
 }
void race_Initialize ()
Definition at line 448 of file sv_race.qc.
References g_race_qualifying, race_ScoreRules(), and warmup_stage.
Referenced by REGISTER_MUTATOR().
 {
     race_ScoreRules();
     if(g_race_qualifying == 2)
         warmup_stage = 0;
     radar_showenemies = true;
 }
void race_ScoreRules ()
Definition at line 54 of file sv_race.qc.
References g_race_qualifying, GameRules_score_enabled(), GameRules_scoring, race_teams, SFL_LOWER_IS_BETTER, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_SECONDARY, SFL_TIME, and ST_RACE_LAPS.
Referenced by MUTATOR_HOOKFUNCTION(), and race_Initialize().
 {
     GameRules_score_enabled(false);
     GameRules_scoring(race_teams, 0, 0, {
         if (race_teams) {
             field_team(ST_RACE_LAPS, "laps", SFL_SORT_PRIO_PRIMARY);
             field(SP_RACE_LAPS, "laps", SFL_SORT_PRIO_PRIMARY);
             field(SP_RACE_TIME, "time", SFL_SORT_PRIO_SECONDARY | SFL_LOWER_IS_BETTER | SFL_TIME);
             field(SP_RACE_FASTEST, "fastest", SFL_LOWER_IS_BETTER | SFL_TIME);
         } else if (g_race_qualifying) {
             field(SP_RACE_FASTEST, "fastest", SFL_SORT_PRIO_PRIMARY | SFL_LOWER_IS_BETTER | SFL_TIME);
         } else {
             field(SP_RACE_LAPS, "laps", SFL_SORT_PRIO_PRIMARY);
             field(SP_RACE_TIME, "time", SFL_SORT_PRIO_SECONDARY | SFL_LOWER_IS_BETTER | SFL_TIME);
             field(SP_RACE_FASTEST, "fastest", SFL_LOWER_IS_BETTER | SFL_TIME);
         }
     });
 }
void rc_SetLimits ()
Definition at line 456 of file sv_race.qc.
References autocvar_fraglimit, autocvar_g_campaign, autocvar_g_race_laps_limit, autocvar_g_race_qualifying_timelimit, autocvar_g_race_qualifying_timelimit_override, autocvar_g_race_teams, autocvar_timelimit, autocvar_timelimit_override, BITS, bound(), g_race_qualifying, GameRules_limit_lead(), GameRules_limit_score(), GameRules_limit_time(), GameRules_limit_time_qualifying(), GameRules_teams(), independent_players, race_fraglimit, race_leadlimit, race_teams, and race_timelimit.
Referenced by REGISTER_MUTATOR().
 {
     int fraglimit_override, leadlimit_override;
     float timelimit_override, qualifying_override;
     if(autocvar_g_race_teams)
     {
         GameRules_teams(true);
         race_teams = BITS(bound(2, autocvar_g_race_teams, 4));
     }
     else
         race_teams = 0;
     qualifying_override = autocvar_g_race_qualifying_timelimit_override;
     fraglimit_override = autocvar_g_race_laps_limit;
     leadlimit_override = 0; // currently not supported by race
     timelimit_override = autocvar_timelimit_override;
     float want_qualifying = ((qualifying_override >= 0) ? qualifying_override : autocvar_g_race_qualifying_timelimit) > 0;
     if(autocvar_g_campaign)
     {
         g_race_qualifying = 1;
         independent_players = 1;
     }
     else if(want_qualifying)
     {
         g_race_qualifying = 2;
         independent_players = 1;
         race_fraglimit = (fraglimit_override >= 0) ? fraglimit_override : autocvar_fraglimit;
         race_leadlimit = (leadlimit_override >= 0) ? leadlimit_override : autocvar_leadlimit;
         race_timelimit = (timelimit_override >= 0) ? timelimit_override : autocvar_timelimit;
         qualifying_override = (qualifying_override >= 0) ? qualifying_override : autocvar_g_race_qualifying_timelimit;
         fraglimit_override = 0;
         leadlimit_override = 0;
         timelimit_override = qualifying_override;
     }
     else
         g_race_qualifying = 0;
     GameRules_limit_score(fraglimit_override);
     GameRules_limit_lead(leadlimit_override);
     GameRules_limit_time(timelimit_override);
     GameRules_limit_time_qualifying(qualifying_override);
 }
float WinningCondition_QualifyingThenRace (float limit)
Definition at line 103 of file sv_race.qc.
References WINNING_STARTSUDDENDEATHOVERTIME, WINNING_YES, and WinningCondition_Scores().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     float wc;
     wc = WinningCondition_Scores(limit, 0);
     // NEVER initiate overtime
     if(wc == WINNING_YES || wc == WINNING_STARTSUDDENDEATHOVERTIME)
     {
         return WINNING_YES;
     }
     return wc;
 }
float WinningCondition_Race (float fraglimit)
Definition at line 79 of file sv_race.qc.
References CS(), FOREACH_CLIENT, IS_PLAYER, race_completed, WINNING_NEVER, WINNING_STARTSUDDENDEATHOVERTIME, WINNING_YES, and WinningCondition_Scores().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     float wc;
     float n, c;
     n = 0;
     c = 0;
     FOREACH_CLIENT(IS_PLAYER(it), {
         ++n;
         if(CS(it).race_completed)
             ++c;
     });
     if(n && (n == c))
         return WINNING_YES;
     wc = WinningCondition_Scores(fraglimit, 0);
     // ALWAYS initiate overtime, unless EVERYONE has finished the race!
     if(wc == WINNING_YES || wc == WINNING_STARTSUDDENDEATHOVERTIME)
     // do NOT support equality when the laps are all raced!
         return WINNING_STARTSUDDENDEATHOVERTIME;
     else
         return WINNING_NEVER;
 }
Variable Documentation
float autocvar_g_race_qualifying_timelimit
Definition at line 12 of file sv_race.qc.
Referenced by rc_SetLimits().
float autocvar_g_race_qualifying_timelimit_override
Definition at line 13 of file sv_race.qc.
Referenced by rc_SetLimits().
int autocvar_g_race_teams
Definition at line 14 of file sv_race.qc.
Referenced by rc_SetLimits().
float race_checkpoint
Definition at line 17 of file sv_race.qc.
Referenced by havocbot_role_race().