Xonotic: common/triggers/trigger/impulse.qc File Reference
impulse.qc File Reference
Functions
void trigger_impulse_touch1 ()
void trigger_impulse_touch2 ()
void trigger_impulse_touch3 ()
Function Documentation
void trigger_impulse_touch1 ()
Definition at line 2 of file impulse.qc.
References active, ACTIVE_ACTIVE, entity(), EXACTTRIGGER_TOUCH, falloff, find(), FL_ONGROUND, isPushable(), min(), normalize(), objerror, origin, other, radius, SELFPARAM, spawnflags, strength, target, targetname, time, UNSET_ONGROUND, UpdateCSQCProjectile(), vlen(), and world.
 {SELFPARAM();
     entity targ;
     float pushdeltatime;
     float str;
     if (self.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(other))
         return;
     EXACTTRIGGER_TOUCH;
     targ = find(world, targetname, self.target);
     if(!targ)
     {
         objerror("trigger_force without a (valid) .target!\n");
         remove(self);
         return;
     }
 #ifdef SVQC
     str = min(self.radius, vlen(self.origin - other.origin));
 #elif defined(CSQC)
     str = min(self.radius, vlen(self.origin - other.move_origin));
 #endif
     if(self.falloff == 1)
         str = (str / self.radius) * self.strength;
     else if(self.falloff == 2)
         str = (1 - (str / self.radius)) * self.strength;
     else
         str = self.strength;
     pushdeltatime = time - other.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     other.lastpushtime = time;
     if(!pushdeltatime) return;
     if(self.spawnflags & 64)
     {
 #ifdef SVQC
         float addspeed = str - other.velocity * normalize(targ.origin - self.origin);
         if (addspeed > 0)
         {
             float accelspeed = min(8 * pushdeltatime * str, addspeed);
             other.velocity += accelspeed * normalize(targ.origin - self.origin);
         }
 #elif defined(CSQC)
         float addspeed = str - other.move_velocity * normalize(targ.origin - self.origin);
         if (addspeed > 0)
         {
             float accelspeed = min(8 * pushdeltatime * str, addspeed);
             other.move_velocity += accelspeed * normalize(targ.origin - self.origin);
         }
 #endif
     }
     else
 #ifdef SVQC
         other.velocity = other.velocity + normalize(targ.origin - self.origin) * str * pushdeltatime;
 #elif defined(CSQC)
         other.move_velocity = other.move_velocity + normalize(targ.origin - self.origin) * str * pushdeltatime;
 #endif
 #ifdef SVQC
     UNSET_ONGROUND(other);
     UpdateCSQCProjectile(other);
 #elif defined(CSQC)
     other.move_flags &= ~FL_ONGROUND;
 #endif
 }
void trigger_impulse_touch2 ()
Definition at line 77 of file impulse.qc.
References active, ACTIVE_ACTIVE, EXACTTRIGGER_TOUCH, isPushable(), other, pow(), SELFPARAM, strength, time, and UpdateCSQCProjectile().
 {SELFPARAM();
     float pushdeltatime;
     if (self.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(other))
         return;
     EXACTTRIGGER_TOUCH;
     pushdeltatime = time - other.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     other.lastpushtime = time;
     if(!pushdeltatime) return;
     // div0: ticrate independent, 1 = identity (not 20)
 #ifdef SVQC
     other.velocity = other.velocity * pow(self.strength, pushdeltatime);
     UpdateCSQCProjectile(other);
 #elif defined(CSQC)
     other.move_velocity = other.move_velocity * pow(self.strength, pushdeltatime);
 #endif
 }
void trigger_impulse_touch3 ()
Definition at line 105 of file impulse.qc.
References active, ACTIVE_ACTIVE, EXACTTRIGGER_TOUCH, falloff, isPushable(), min(), normalize(), origin, other, radius, SELFPARAM, strength, time, UpdateCSQCProjectile(), and vlen().
 {SELFPARAM();
     float pushdeltatime;
     float str;
     if (self.active != ACTIVE_ACTIVE)
         return;
     if (!isPushable(other))
         return;
     EXACTTRIGGER_TOUCH;
     pushdeltatime = time - other.lastpushtime;
     if (pushdeltatime > 0.15) pushdeltatime = 0;
     other.lastpushtime = time;
     if(!pushdeltatime) return;
     setsize(self, '-1 -1 -1' * self.radius,'1 1 1' * self.radius);
 #ifdef SVQC
     str = min(self.radius, vlen(self.origin - other.origin));
 #elif defined(CSQC)
     str = min(self.radius, vlen(self.origin - other.move_origin));
 #endif
     if(self.falloff == 1)
         str = (1 - str / self.radius) * self.strength; // 1 in the inside
     else if(self.falloff == 2)
         str = (str / self.radius) * self.strength; // 0 in the inside
     else
         str = self.strength;
 #ifdef SVQC
     other.velocity = other.velocity + normalize(other.origin - self.origin) * str * pushdeltatime;
     UpdateCSQCProjectile(other);
 #elif defined(CSQC)
     other.move_velocity = other.move_velocity + normalize(other.move_origin - self.origin) * str * pushdeltatime;
 #endif
 }