Xonotic: menu/xonotic/playerlist.qc File Reference
playerlist.qc File Reference
#include "playerlist.qh"
Functions
entity makeXonoticPlayerList ()
void XonoticPlayerList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
string XonoticPlayerList_getPlayerList (entity me, float i, float key)
void XonoticPlayerList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticPlayerList_setPlayerList (entity me, string plist)
Variables
const float PLAYERPARM_COUNT = 4
const float PLAYERPARM_NAME = 3
const float PLAYERPARM_PING = 1
const float PLAYERPARM_SCORE = 0
const float PLAYERPARM_TEAM = 2
float realUpperMargin2
Function Documentation
entity makeXonoticPlayerList ()
Definition at line 11 of file playerlist.qc.
References entity(), and NEW.
Referenced by XonoticServerInfoDialog_fill().
 {
     entity me;
     me = NEW(XonoticPlayerList);
     me.configureXonoticListBox(me);
     return me;
 }
void XonoticPlayerList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 78 of file playerlist.qc.
References colormapPaletteColor, draw_Text(), draw_TextShortenToWidth(), draw_TextWidth(), eX, eY, FRAGS_SPECTATOR, PLAYERPARM_NAME, PLAYERPARM_SCORE, PLAYERPARM_TEAM, stof(), strlen(), strstrofs, substring(), and vector().
 {
     string s;
     string score;
     float t;
     vector rgb;
     t = stof(me.getPlayerList(me, i, PLAYERPARM_TEAM));
     if(t == 1)
         rgb = colormapPaletteColor(4, 0);
     else if(t == 2)
         rgb = colormapPaletteColor(13, 0);
     else if(t == 3)
         rgb = colormapPaletteColor(12, 0);
     else if(t == 4)
         rgb = colormapPaletteColor(9, 0);
     else
         rgb = SKINCOLOR_TEXT;
     s = me.getPlayerList(me, i, PLAYERPARM_NAME);
     score = me.getPlayerList(me, i, PLAYERPARM_SCORE);
     if(substring(score, strlen(score) - 10, 10) == ":spectator")
     {
         score = _("spectator");
     }
     else
     {
         if((t = strstrofs(score, ":", 0)) >= 0)
             score = substring(score, 0, t);
         if((t = strstrofs(score, ",", 0)) >= 0)
             score = substring(score, 0, t);
         if(stof(score) == FRAGS_SPECTATOR)
             score = _("spectator");
     }
     s = draw_TextShortenToWidth(s, me.columnNameSize, 1, me.realFontSize);
     draw_Text(me.realUpperMargin2 * eY + (me.columnNameOrigin + 0.00 * (me.columnNameSize - draw_TextWidth(s, 1, me.realFontSize))) * eX, s, me.realFontSize, '1 1 1', 1, 1);
     score = draw_TextShortenToWidth(score, me.columnScoreSize, 0, me.realFontSize);
     draw_Text(me.realUpperMargin2 * eY + (me.columnScoreOrigin + 1.00 * (me.columnScoreSize - draw_TextWidth(score, 1, me.realFontSize))) * eX, score, me.realFontSize, rgb, 1, 0);
 }
string XonoticPlayerList_getPlayerList (entity me, float i, float key)
Definition at line 54 of file playerlist.qc.
References PLAYERPARM_COUNT.
 {
     return bufstr_get(me.playerList, i * PLAYERPARM_COUNT + key);
 }
void XonoticPlayerList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 59 of file playerlist.qc.
References SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticPlayerList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.itemAbsSize.y = absSize.y * me.itemHeight;
     me.itemAbsSize.x = absSize.x * (1 - me.controlWidth);
     me.realFontSize.y = me.fontSize / me.itemAbsSize.y;
     me.realFontSize.x = me.fontSize / me.itemAbsSize.x;
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
     // this list does 1 char left and right margin
     me.columnScoreSize = 5 * me.realFontSize.x;
     me.columnNameSize = 1 - 3 * me.realFontSize.x - me.columnScoreSize;
     me.columnNameOrigin = me.realFontSize.x;
     me.columnScoreOrigin = me.columnNameOrigin + me.columnNameSize + me.realFontSize.x;
 }
void XonoticPlayerList_setPlayerList (entity me, string plist)
Definition at line 19 of file playerlist.qc.
References argv(), buf_create, PLAYERPARM_COUNT, PLAYERPARM_NAME, PLAYERPARM_PING, PLAYERPARM_SCORE, PLAYERPARM_TEAM, tokenize_console, and tokenizebyseparator.
 {
     int buf,i,n;
     string s;
     buf = buf_create();
     me.nItems = tokenizebyseparator(plist, "\n");
     for(i = 0; i < me.nItems; ++i)
     {
         bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_NAME, argv(i)); // -666 100 "^4Nex ^2Player"
     }
     for(i = 0; i < me.nItems; ++i)
     {
         s = bufstr_get(buf, i * PLAYERPARM_COUNT + PLAYERPARM_NAME);
         n = tokenize_console(s);
         if(n == 4)
         {
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_SCORE, argv(0)); // -666
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_PING,  argv(1)); // 100
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_TEAM,  argv(2)); // 0 for spec, else 1, 2, 3, 4
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_NAME,  argv(3)); // ^4Nex ^2Player
         }
         else
         {
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_SCORE, argv(0)); // -666
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_PING,  argv(1)); // 100
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_TEAM,  "-1");
             bufstr_set(buf, i * PLAYERPARM_COUNT + PLAYERPARM_NAME,  argv(2)); // ^4Nex ^2Player
         }
     }
     me.playerList = buf;
 }
Variable Documentation
const float PLAYERPARM_COUNT = 4
Definition at line 9 of file playerlist.qc.
Referenced by XonoticPlayerList_getPlayerList(), and XonoticPlayerList_setPlayerList().
const float PLAYERPARM_NAME = 3
Definition at line 8 of file playerlist.qc.
Referenced by XonoticPlayerList_drawListBoxItem(), and XonoticPlayerList_setPlayerList().
const float PLAYERPARM_PING = 1
Definition at line 6 of file playerlist.qc.
Referenced by XonoticPlayerList_setPlayerList().
const float PLAYERPARM_SCORE = 0
Definition at line 5 of file playerlist.qc.
Referenced by XonoticPlayerList_drawListBoxItem(), and XonoticPlayerList_setPlayerList().
const float PLAYERPARM_TEAM = 2
Definition at line 7 of file playerlist.qc.
Referenced by XonoticPlayerList_drawListBoxItem(), and XonoticPlayerList_setPlayerList().
float realUpperMargin2
Definition at line 3 of file playerlist.qc.