Xonotic: menu/xonotic/maplist.qh File Reference
maplist.qh File Reference
#include "listbox.qh"
Classes
class XonoticMapList
Functions
entity makeXonoticMapList ()
void MapList_Add_All (entity btn, entity me)
void MapList_Add_Shown (entity btn, entity me)
void MapList_LoadMap (entity btn, entity me)
void MapList_Remove_All (entity btn, entity me)
void MapList_Remove_Shown (entity btn, entity me)
void MapList_StringFilterBox_Change (entity box, entity me)
float MapList_StringFilterBox_keyDown (entity me, float key, float ascii, float shift)
Function Documentation
makeXonoticMapList()
entity makeXonoticMapList ()
Definition at line 15 of file maplist.qc.
References entity(), and NEW.
 {
     entity me;
     me = NEW(XonoticMapList);
     me.configureXonoticMapList(me);
     return me;
 }
MapList_Add_All()
void MapList_Add_All (entity btn, entity me)
Definition at line 251 of file maplist.qc.
References _MapInfo_FilterGametype(), cvar_set(), MapInfo_BSPName_ByID(), MapInfo_count, MapInfo_ForbiddenFlags(), MAPINFO_TYPE_ALL, strcat(), strlen(), and substring().
 {
     float i;
     string s;
     _MapInfo_FilterGametype(MAPINFO_TYPE_ALL, 0, 0, MapInfo_ForbiddenFlags(), 0); // all
     s = "";
     for(i = 0; i < MapInfo_count; ++i)
         s = strcat(s, " ", MapInfo_BSPName_ByID(i));
     cvar_set("g_maplist", substring(s, 1, strlen(s) - 1));
     me.refilter(me);
 }
MapList_Add_Shown()
void MapList_Add_Shown (entity btn, entity me)
Definition at line 227 of file maplist.qc.
References strlen().
 {
     float i, n;
     n = strlen(me.g_maplistCache);
     for (i = 0 ; i < n; i++)
     {
         if (!me.g_maplistCacheQuery(me, i))
             me.g_maplistCacheToggle(me, i);
     }
     me.refilter(me);
 }
MapList_LoadMap()
void MapList_LoadMap (entity btn, entity me)
Definition at line 269 of file maplist.qc.
References Dialog_Close(), LOG_INFO, and MapInfo_BSPName_ByID().
 {
     string m;
     float i;
     i = me.selectedItem;
     if(btn.parent.instanceOfXonoticMapInfoDialog)
     {
         i = btn.parent.currentMapIndex;
         Dialog_Close(btn, btn.parent);
     }
     if(i >= me.nItems || i < 0)
         return;
     m = MapInfo_BSPName_ByID(i);
     if (!m)
     {
         LOG_INFO(_("Huh? Can't play this (m is NULL). Refiltering so this won't happen again."));
         me.refilter(me);
         return;
     }
     if(MapInfo_CheckMap(m))
     {
         localcmd("\nmenu_loadmap_prepare\n");
         if(cvar("menu_use_default_hostname"))
             localcmd("hostname \"", sprintf(_("%s's Xonotic Server"), strdecolorize(cvar_string("_cl_name"))), "\"\n");
         MapInfo_LoadMap(m, 1);
     }
     else
     {
         LOG_INFO(_("Huh? Can't play this (invalid game type). Refiltering so this won't happen again."));
         me.refilter(me);
         return;
     }
 }
MapList_Remove_All()
void MapList_Remove_All (entity btn, entity me)
Definition at line 263 of file maplist.qc.
References cvar_set().
 {
     cvar_set("g_maplist", "");
     me.refilter(me);
 }
MapList_Remove_Shown()
void MapList_Remove_Shown (entity btn, entity me)
Definition at line 239 of file maplist.qc.
References strlen().
 {
     float i, n;
     n = strlen(me.g_maplistCache);
     for (i = 0 ; i < n; i++)
     {
         if (me.g_maplistCacheQuery(me, i))
             me.g_maplistCacheToggle(me, i);
     }
     me.refilter(me);
 }
MapList_StringFilterBox_Change()
void MapList_StringFilterBox_Change (entity box, entity me)
Definition at line 218 of file maplist.qc.
References strfree, and strzone().
Referenced by XonoticMapList_keyDown().
 {
     strfree(me.stringFilter);
     if(box.text != "")
         me.stringFilter = strzone(box.text);
     me.refilter(me);
 }
MapList_StringFilterBox_keyDown()
float MapList_StringFilterBox_keyDown (entity me, float key, float ascii, float shift)
Definition at line 382 of file maplist.qc.
References K_DOWNARROW, K_ENTER, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_UPARROW, and SUPER.
 {
     // in this section, note that onChangeEntity has the ref to mapListBox
     // we make use of that, instead of extending a class to add one more attrib
     switch(scan)
     {
         case K_KP_ENTER:
         case K_ENTER:
             // move the focus to the mapListBox
             me.onChangeEntity.parent.setFocus(me.onChangeEntity.parent, me.onChangeEntity);
             return 1;
         case K_KP_UPARROW:
         case K_UPARROW:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             // pass the event to the mapListBox (to scroll up and down)
             return me.onChangeEntity.keyDown(me.onChangeEntity, scan, ascii, shift);
     }
     return SUPER(XonoticInputBox).keyDown(me, scan, ascii, shift);
 }