Xonotic: menu/xonotic/datasource.qc File Reference
datasource.qc File Reference
#include "datasource.qh"
Functions
CONSTRUCTOR (StringSource, string str, string sep)
METHOD (StringSource, getEntry, entity(entity this, int i, void(string name, string icon) returns))
CONSTRUCTOR (CvarStringSource, string cv, string sep)
METHOD (CvarStringSource, getEntry, entity(entity this, int i, void(string name, string icon) returns))
return SUPER (CvarStringSource).reload(this
Variables
this StringSource_str = s ? cvar_string(s) : string_null
return filter
Function Documentation
CONSTRUCTOR (StringSource , string str, string sep)
Definition at line 3 of file datasource.qc.
References CONSTRUCT, and StringSource_str.
     {
         CONSTRUCT(StringSource);
         this.StringSource_str = str;
         this.StringSource_sep = sep;
     }
CONSTRUCTOR (CvarStringSource , string cv, string sep)
Definition at line 22 of file datasource.qc.
References CONSTRUCT.
     {
         CONSTRUCT(CvarStringSource);
         this.CvarStringSource_cvar = cv;
         this.StringSource_sep = sep;
     }
METHOD (StringSource , getEntry , entity(entity this, int i, void(string name, string icon) returns))
Definition at line 9 of file datasource.qc.
References argv(), DataSource_false, DataSource_true, n, s, string_null, StringSource_str, and tokenizebyseparator.
     {
         int n = tokenizebyseparator(this.StringSource_str, this.StringSource_sep);
         if (i < 0 || i >= n) return DataSource_false;
         string s = argv(i);
         if (returns) returns(s, string_null);
         return DataSource_true;
     }
METHOD (CvarStringSource , getEntry , entity(entity this, int i, void(string name, string icon) returns))
Definition at line 28 of file datasource.qc.
References cvar_string(), s, string_null, StringSource_str, and SUPER().
     {
         string s = this.CvarStringSource_cvar;
         this.StringSource_str = s ? cvar_string(s) : string_null;
         return SUPER(CvarStringSource).getEntry(this, i, returns);
     }
return SUPER (CvarStringSource)
Referenced by BorderImage_draw(), BorderImage_recalcPositionWithText(), BorderImage_resizeNotify(), Button_configureButton(), Button_draw(), Button_resizeNotify(), CheckBox_draw(), CheckBox_toString(), Container_draw(), Container_resizeNotifyLie(), Dialog_keyDown(), Image_draw(), Image_resizeNotify(), InputBox_configureInputBox(), InputBox_resizeNotify(), InputBox_setText(), InputContainer_focusLeave(), InputContainer_keyDown(), InputContainer_mouseDrag(), InputContainer_mouseMove(), InputContainer_mousePress(), InputContainer_mouseRelease(), InputContainer_resizeNotify(), Label_draw(), Label_resizeNotify(), ListBox_draw(), ListBox_resizeNotify(), MainWindow_draw(), MapList_StringFilterBox_keyDown(), METHOD(), ModalController_addItem(), ModalController_draw(), Nexposee_addItem(), Nexposee_draw(), Nexposee_focusEnter(), Nexposee_keyDown(), Nexposee_keyUp(), Nexposee_mouseDrag(), Nexposee_mouseMove(), Nexposee_mousePress(), Nexposee_mouseRelease(), Slider_configureSliderVisuals(), Slider_draw(), Slider_resizeNotify(), TextSlider_setValueFromIdentifier_allowAnim(), XonoticCampaignList_draw(), XonoticCampaignList_keyDown(), XonoticCampaignList_resizeNotify(), XonoticCampaignList_setSelected(), XonoticCharmap_keyDown(), XonoticCharmap_resizeNotify(), XonoticColorButton_draw(), XonoticColorpicker_draw(), XonoticColorpickerString_draw(), XonoticCreditsList_draw(), XonoticCreditsList_keyDown(), XonoticCreditsList_resizeNotify(), XonoticCrosshairPicker_cellSelect(), XonoticCrosshairPicker_configureXonoticCrosshairPicker(), XonoticCrosshairPreview_draw(), XonoticCvarList_keyDown(), XonoticCvarList_mouseRelease(), XonoticCvarList_resizeNotify(), XonoticCvarList_setSelected(), XonoticCvarsDialog_showNotify(), XonoticDemoList_keyDown(), XonoticDemoList_resizeNotify(), XonoticDialog_configureDialog(), XonoticGametypeList_keyDown(), XonoticGametypeList_resizeNotify(), XonoticGametypeList_setSelected(), XonoticHUDSkinList_draw(), XonoticHUDSkinList_keyDown(), XonoticHUDSkinList_resizeNotify(), XonoticInputBox_keyDown(), XonoticInputBox_loadCvars(), XonoticInputBox_setText(), XonoticKeyBinder_keyDown(), XonoticKeyBinder_resizeNotify(), XonoticKeyBinder_setSelected(), XonoticLanguageList_keyDown(), XonoticLanguageList_loadCvars(), XonoticLanguageList_resizeNotify(), XonoticLanguageList_setSelected(), XonoticListBox_resizeNotify(), XonoticMapList_draw(), XonoticMapList_keyDown(), XonoticMapList_resizeNotify(), XonoticMutatorsDialog_close(), XonoticMutatorsDialog_showNotify(), XonoticPicker_draw(), XonoticPicmipSlider_draw(), XonoticPlayerList_resizeNotify(), XonoticPlayerModelSelector_draw(), XonoticPlayerModelSelector_resizeNotify(), XonoticPlayList_draw(), XonoticPlayList_keyDown(), XonoticPlayList_mouseDrag(), XonoticPlayList_resizeNotify(), XonoticProfileTab_draw(), XonoticRadioButton_draw(), XonoticResolutionSlider_draw(), XonoticScreenshotImage_draw(), XonoticScreenshotImage_resizeNotify(), XonoticScreenshotList_draw(), XonoticScreenshotList_keyDown(), XonoticScreenshotList_resizeNotify(), XonoticScreenshotList_setSelected(), XonoticScreenshotViewerDialog_close(), XonoticScreenshotViewerDialog_keyDown(), XonoticServerList_draw(), XonoticServerList_focusEnter(), XonoticServerList_keyDown(), XonoticServerList_mouseMove(), XonoticServerList_resizeNotify(), XonoticServerList_setSelected(), XonoticSkinList_keyDown(), XonoticSkinList_resizeNotify(), XonoticSlider_setValue(), XonoticSlider_setValue_noAnim(), XonoticSliderCheckBox_draw(), XonoticSoundList_keyDown(), XonoticSoundList_resizeNotify(), XonoticStatsList_keyDown(), XonoticStatsList_resizeNotify(), XonoticTab_showNotify(), XonoticTeamSelectDialog_showNotify(), XonoticTextLabel_draw(), XonoticTextSlider_setValue(), XonoticTextSlider_setValue_noAnim(), XonoticWeaponsList_draw(), XonoticWeaponsList_keyDown(), XonoticWeaponsList_mouseDrag(), and XonoticWeaponsList_resizeNotify().
Variable Documentation
return filter
Definition at line 38 of file datasource.qc.
Referenced by GameCommand().
this StringSource_str = s ? cvar_string(s) : string_null
Definition at line 37 of file datasource.qc.
Referenced by CONSTRUCTOR(), and METHOD().