Xonotic: menu/xonotic/dialog_settings.qc File Reference
dialog_settings.qc File Reference
#include "dialog_settings.qh"
#include "dialog_settings_video.qh"
#include "dialog_settings_effects.qh"
#include "dialog_settings_audio.qh"
#include "dialog_settings_game.qh"
#include "dialog_settings_input.qh"
#include "dialog_settings_user.qh"
#include "dialog_settings_misc.qh"
#include "tabcontroller.qh"
Functions
void XonoticSettingsDialog_fill (entity me)
Function Documentation
void XonoticSettingsDialog_fill (entity me)
Definition at line 13 of file dialog_settings.qc.
References entity(), makeXonoticAudioSettingsTab(), makeXonoticEffectsSettingsTab(), makeXonoticInputSettingsTab(), makeXonoticMiscSettingsTab(), makeXonoticTabController(), makeXonoticUserSettingsTab(), makeXonoticVideoSettingsTab(), and NEW.
 {
     entity mc;
     mc = makeXonoticTabController(me.rows - 2.5);
     me.TR(me);
         me.TD(me, 1, 2, mc.makeTabButton(mc, _("Video"),   makeXonoticVideoSettingsTab()));
         me.TD(me, 1, 2, mc.makeTabButton(mc, _("Effects"), makeXonoticEffectsSettingsTab()));
         me.TD(me, 1, 2, mc.makeTabButton(mc, _("Audio"),   makeXonoticAudioSettingsTab()));
     me.TR(me);
         me.TD(me, 1, 1.5, mc.makeTabButton(mc, _("Game"),    NEW(XonoticGameSettingsTab)));
         me.TD(me, 1, 1.5, mc.makeTabButton(mc, _("Input"),   makeXonoticInputSettingsTab()));
         me.TD(me, 1, 1.5, mc.makeTabButton(mc, _("User"),    makeXonoticUserSettingsTab()));
         me.TD(me, 1, 1.5, mc.makeTabButton(mc, _("Misc"),    makeXonoticMiscSettingsTab()));
     me.gotoRC(me, 2.5, 0);
         me.TD(me, me.rows - 2.5, me.columns, mc);
 }