Xonotic: server/compat/quake3.qh File Reference
quake3.qh File Reference
Macros
#define Q3COMPAT_ARENA BIT(0)
#define Q3COMPAT_DEFI BIT(1)
#define SPAWNFUNC_Q3(weapon_classname, ammo_classname, xonwep)
#define SPAWNFUNC_Q3_COND(weapon_classname, ammo_classname, cond, xonwep1, xonwep0)
#define SPAWNFUNC_Q3AMMO(ammo_classname, xonwep)
#define SPAWNFUNC_Q3AMMO_COND(ammo_classname, cond, xonwep1, xonwep0) SPAWNFUNC_Q3AMMO(ammo_classname, (cond ? xonwep1 : xonwep0))
Functions
bool DoesQ3ARemoveThisEntity (entity this)
int GetAmmoConsumptionQ3 (string netname)
Variables
bool autocvar_sv_q3compat_changehitbox
int fragsfilter_cnt
int q3compat = 0
Macro Definition Documentation
Q3COMPAT_ARENA
#define Q3COMPAT_ARENA BIT(0)
Definition at line 4 of file quake3.qh.
Referenced by spawnfunc().
Q3COMPAT_DEFI
#define Q3COMPAT_DEFI BIT(1)
Definition at line 5 of file quake3.qh.
Referenced by spawnfunc().
SPAWNFUNC_Q3
#define SPAWNFUNC_Q3 (weapon_classname, ammo_classname, xonwep)
Value:
SPAWNFUNC_WEAPON(weapon_classname, xonwep) \
    SPAWNFUNC_Q3AMMO(ammo_classname, xonwep)
Definition at line 32 of file quake3.qh.
SPAWNFUNC_Q3_COND
#define SPAWNFUNC_Q3_COND (weapon_classname, ammo_classname, cond, xonwep1, xonwep0)
Value:
SPAWNFUNC_WEAPON_COND(weapon_classname, cond, xonwep1, xonwep0) \
    SPAWNFUNC_Q3AMMO_COND(ammo_classname, cond, xonwep1, xonwep0)
Definition at line 37 of file quake3.qh.
SPAWNFUNC_Q3AMMO
#define SPAWNFUNC_Q3AMMO (ammo_classname, xonwep)
Value:
spawnfunc(ammo_classname) \
    { \
        if(this.count && xonwep.ammo_type) \
            SetResource(this, xonwep.ammo_type, this.count * GetAmmoConsumptionQ3(xonwep.netname)); \
    SPAWNFUNC_BODY(GetAmmoItem(xonwep.ammo_type)) \
    }
Definition at line 19 of file quake3.qh.
SPAWNFUNC_Q3AMMO_COND
#define SPAWNFUNC_Q3AMMO_COND (ammo_classname, cond, xonwep1, xonwep0) SPAWNFUNC_Q3AMMO(ammo_classname, (cond ? xonwep1 : xonwep0))
Definition at line 28 of file quake3.qh.
Function Documentation
DoesQ3ARemoveThisEntity()
bool DoesQ3ARemoveThisEntity (entity this)
Definition at line 282 of file quake3.qc.
References ctf_oneflag, cvar_string(), g_ctf, g_duel, gametype, maxclients, notcpm, notfree, notsingle, notta, notteam, notvq3, strstrofs, and teamplay.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     // Q3 style filters (DO NOT USE, THIS IS COMPAT ONLY)
     // DeFRaG mappers use "notcpm" or "notvq3" to disable an entity in CPM or VQ3 physics
     // Xonotic is usually played with a CPM-based physics so we default to CPM mode
     if(cvar_string("g_mod_physics") == "Q3")
     {
         if(this.notvq3)
             return true;
     }
     else if(this.notcpm)
         return true;
     // Q3 mappers use "notq3a" or "notta" to disable an entity in Q3A or Q3TA
     // Xonotic has ~equivalent features to Team Arena
     if(this.notta)
         return true;
     // FIXME: singleplayer does not use maxclients 1 as that would prevent bots
     if(this.notsingle)
         if(maxclients == 1)
             return true;
     if(this.notteam)
         if(teamplay)
             return true;
     if(this.notfree)
         if(!teamplay)
             return true;
     if(this.gametype)
     {
         string gametypename;
         // From ioq3 g_spawn.c: static char *gametypeNames[] = {"ffa", "tournament", "single", "team", "ctf", "oneflag", "obelisk", "harvester"};
         gametypename = "ffa";
         if(teamplay)
             gametypename = "team";
         if(g_ctf)
             gametypename = "ctf";
         if(g_ctf && ctf_oneflag)
             gametypename = "oneflag";
         if(g_duel)
             gametypename = "tournament";
         if(maxclients == 1)
             gametypename = "single";
         // we do not have the other types (obelisk, harvester)
         if(strstrofs(this.gametype, gametypename, 0) < 0)
             return true;
     }
     return false;
 }
GetAmmoConsumptionQ3()
int GetAmmoConsumptionQ3 (string netname)
Definition at line 337 of file quake3.qc.
References cvar(), and strcat().
Referenced by weapon_defaultspawnfunc().
 {
     switch (netname)
     {
         case "arc":    return autocvar_g_balance_arc_beam_ammo;
         case "devastator": return autocvar_g_balance_devastator_ammo;
         case "machinegun": return autocvar_g_balance_machinegun_sustained_ammo;
         case "minelayer":  return autocvar_g_balance_minelayer_ammo;
         case "seeker":     return autocvar_g_balance_seeker_tag_ammo;
         default:       return cvar(strcat("g_balance_", netname, "_primary_ammo"));
     }
 }
Variable Documentation
autocvar_sv_q3compat_changehitbox
bool autocvar_sv_q3compat_changehitbox
Definition at line 7 of file quake3.qh.
Referenced by PutPlayerInServer().
fragsfilter_cnt
int fragsfilter_cnt
Definition at line 12 of file quake3.qh.
Referenced by PutPlayerInServer().
q3compat
int q3compat = 0
Definition at line 3 of file quake3.qh.
Referenced by door_reset(), PutPlayerInServer(), spawnfunc(), SV_OnEntityPreSpawnFunction(), and weapon_defaultspawnfunc().