Xonotic: lib/spawnfunc.qh File Reference
spawnfunc.qh File Reference
Macros
#define __spawnfunc_spawn_all()
#define _spawnfunc_check(fld) if (s == #fld) continue;
#define _spawnfunc_checktypes(fld)
#define EVAL_spawnfunc(...) __VA_ARGS__
#define FIELD_SCALAR(fld, n) fld(n)
#define FIELD_VEC(fld, n)
#define FIELDS_ALL(fld) if (false)
#define FIELDS_COMMON(fld)
#define FIELDS_NONE(fld)
#define FIELDS_UNION(fld)
#define spawnfunc(...) EVAL_spawnfunc(OVERLOAD(spawnfunc, __VA_ARGS__))
#define spawnfunc_1(id) spawnfunc_2(id, FIELDS_UNION)
#define spawnfunc_2(id, whitelist)
#define SPAWNFUNC_INTERNAL_FIELDS(X)
#define X(T, fld, def) .T fld, __spawnfunc_##fld;
#define X(T, fld, def) { prototype.__spawnfunc_##fld = prototype.fld; prototype.fld = def; }
#define X(T, fld, def) { e.fld = e.__spawnfunc_##fld; e.__spawnfunc_##fld = def; }
Functions
void __spawnfunc_defer (entity prototype, void(entity) constructor)
void __spawnfunc_spawn (entity prototype)
void (entity) __spawnfunc_constructor
Variables
noref entity __spawnfunc_expect
noref int __spawnfunc_expecting
noref bool __spawnfunc_first
noref bool __spawnfunc_unreachable_workaround = true
noref IntrusiveList g_map_entities
noref IntrusiveList g_spawn_queue
noref bool require_spawnfunc_prefix
If this global exists, only functions with spawnfunc_ name prefix qualify as spawn functions.
bool spawnfunc_checked
Macro Definition Documentation
#define __spawnfunc_spawn_all ()
Value:
MACRO_BEGIN \
        g_map_entities = IL_NEW(); \
        IL_EACH(g_spawn_queue, true, __spawnfunc_spawn(it)); \
    MACRO_END
Definition at line 60 of file spawnfunc.qh.
Referenced by spawnfunc().
#define _spawnfunc_check (fld) if (s == #fld) continue;
Definition at line 27 of file spawnfunc.qh.
#define _spawnfunc_checktypes (fld)
Definition at line 25 of file spawnfunc.qh.
#define EVAL_spawnfunc (...) __VA_ARGS__
Definition at line 277 of file spawnfunc.qh.
#define FIELD_SCALAR (fld, n) fld(n)
Definition at line 136 of file spawnfunc.qh.
#define FIELD_VEC (fld, n)
Value:
fld(n) \
        fld(n##_x) \
        fld(n##_y) \
        fld(n##_z)
Definition at line 138 of file spawnfunc.qh.
#define FIELDS_ALL (fld) if (false)
Definition at line 145 of file spawnfunc.qh.
#define FIELDS_COMMON (fld)
Value:
FIELD_SCALAR(fld, classname) \
        FIELD_SCALAR(fld, sourceLoc) \
        FIELD_SCALAR(fld, spawnfunc_checked) \
        FIELD_VEC(fld, origin) \
Definition at line 147 of file spawnfunc.qh.
#define FIELDS_NONE (fld)
Definition at line 144 of file spawnfunc.qh.
#define FIELDS_UNION (fld)
Definition at line 154 of file spawnfunc.qh.
#define spawnfunc (...) EVAL_spawnfunc(OVERLOAD(spawnfunc, __VA_ARGS__))
Definition at line 276 of file spawnfunc.qh.
#define spawnfunc_1 (id) spawnfunc_2(id, FIELDS_UNION)
Definition at line 86 of file spawnfunc.qh.
#define spawnfunc_2 (id, whitelist)
Definition at line 87 of file spawnfunc.qh.
#define SPAWNFUNC_INTERNAL_FIELDS (X)
Value:
X(string, classname, "spawnfunc") \
        X(string, target, string_null) \
        X(string, target2, string_null) \
        X(string, target3, string_null) \
        X(string, target4, string_null) \
        X(string, targetname, string_null) \
Definition at line 37 of file spawnfunc.qh.
Referenced by __spawnfunc_defer(), and __spawnfunc_spawn().
#define X (T, fld, def) .T fld, __spawnfunc_##fld;
Definition at line 46 of file spawnfunc.qh.
Referenced by __spawnfunc_defer(), and __spawnfunc_spawn().
#define X (T, fld, def) { prototype.__spawnfunc_##fld = prototype.fld; prototype.fld = def; }
Definition at line 46 of file spawnfunc.qh.
#define X (T, fld, def) { e.fld = e.__spawnfunc_##fld; e.__spawnfunc_##fld = def; }
Definition at line 46 of file spawnfunc.qh.
Function Documentation
void __spawnfunc_defer (entity prototype, void(entity) constructor)
Definition at line 50 of file spawnfunc.qh.
References IL_PUSH(), SPAWNFUNC_INTERNAL_FIELDS, and X.
     {
         IL_PUSH(g_spawn_queue, prototype);
         #define X(T, fld, def) { prototype.__spawnfunc_##fld = prototype.fld; prototype.fld = def; }
         SPAWNFUNC_INTERNAL_FIELDS(X);
         #undef X
         prototype.__spawnfunc_constructor = constructor;
     }
void __spawnfunc_spawn (entity prototype)
Definition at line 67 of file spawnfunc.qh.
References copyentity(), entity(), IL_PUSH(), SPAWNFUNC_INTERNAL_FIELDS, and X.
     {
         entity e = new(clone);
         copyentity(prototype, e);
         IL_PUSH(g_map_entities, e);
         #define X(T, fld, def) { e.fld = e.__spawnfunc_##fld; e.__spawnfunc_##fld = def; }
         SPAWNFUNC_INTERNAL_FIELDS(X);
         #undef X
 #ifdef SVQC
         _SV_OnEntityPreSpawnFunction(e);
         if (wasfreed(e)) {
             return;
         }
 #endif
         e.__spawnfunc_constructor(e);
     }
void (entity) const
Variable Documentation
noref entity __spawnfunc_expect
Definition at line 31 of file spawnfunc.qh.
noref int __spawnfunc_expecting
Definition at line 30 of file spawnfunc.qh.
noref bool __spawnfunc_first
Definition at line 84 of file spawnfunc.qh.
noref bool __spawnfunc_unreachable_workaround = true
Definition at line 32 of file spawnfunc.qh.
noref IntrusiveList g_map_entities
Definition at line 59 of file spawnfunc.qh.
noref IntrusiveList g_spawn_queue
Definition at line 35 of file spawnfunc.qh.
noref bool require_spawnfunc_prefix
If this global exists, only functions with spawnfunc_ name prefix qualify as spawn functions.
Definition at line 4 of file spawnfunc.qh.
bool spawnfunc_checked
Definition at line 5 of file spawnfunc.qh.
Referenced by ctf_SpawnTeam(), and tdm_SpawnTeam().