Xonotic: common/gamemodes/gamemode/clanarena/sv_clanarena.qh File Reference
sv_clanarena.qh File Reference
#include <common/mutators/base.qh>
#include <server/round_handler.qh>
#include <server/miscfunctions.qh>
#include <server/command/sv_cmd.qh>
Functions
bool CA_CheckTeams ()
bool CA_CheckWinner ()
bool ca_isEliminated (entity e)
void CA_RoundStart ()
REGISTER_MUTATOR (ca, false)
Variables
bool allowed_to_spawn
int autocvar_g_ca_point_leadlimit
int autocvar_g_ca_point_limit
float autocvar_g_ca_round_timelimit
bool autocvar_g_ca_team_spawns
int autocvar_g_ca_teams_override
float autocvar_g_ca_warmup
string autocvar_g_ca_weaponarena = "most"
int ca_teams
float caplayer
const int ST_CA_ROUNDS = 1
Function Documentation
bool CA_CheckTeams ()
Definition at line 112 of file sv_clanarena.qc.
References allowed_to_spawn, CA_count_alive_players(), ca_teams, NULL, NUM_TEAMS, NumTeams(), Team_GetNumberOfAlivePlayers(), Team_GetNumberOfAliveTeams(), Team_GetTeamFromIndex(), Team_IndexToBit(), and total_players.
Referenced by REGISTER_MUTATOR().
 {
     static int prev_missing_teams_mask;
     allowed_to_spawn = true;
     CA_count_alive_players();
     if (Team_GetNumberOfAliveTeams() == NumTeams(ca_teams))
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return true;
     }
     if(total_players == 0)
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return false;
     }
     int missing_teams_mask = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         if ((ca_teams & Team_IndexToBit(i)) &&
             (Team_GetNumberOfAlivePlayers(Team_GetTeamFromIndex(i)) == 0))
         {
             missing_teams_mask |= Team_IndexToBit(i);
         }
     }
     if(prev_missing_teams_mask != missing_teams_mask)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_MISSING_TEAMS, missing_teams_mask);
         prev_missing_teams_mask = missing_teams_mask;
     }
     return false;
 }
bool CA_CheckWinner ()
Definition at line 65 of file sv_clanarena.qc.
References allowed_to_spawn, APP_TEAM_NUM, autocvar_g_ca_round_timelimit, autocvar_g_ca_warmup, CA_count_alive_players(), CA_GetWinnerTeam(), FOREACH_CLIENT, IS_PLAYER, nades_Clear(), NULL, round_handler_GetEndTime, round_handler_Init(), ST_CA_ROUNDS, Team_GetNumberOfAliveTeams(), TeamScore_AddToTeam(), and time.
Referenced by REGISTER_MUTATOR().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         FOREACH_CLIENT(IS_PLAYER(it), { nades_Clear(it); });
         allowed_to_spawn = false;
         game_stopped = true;
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         return 1;
     }
     CA_count_alive_players();
     if (Team_GetNumberOfAliveTeams() > 1)
     {
         return 0;
     }
     int winner_team = CA_GetWinnerTeam();
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_CA_ROUNDS, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     allowed_to_spawn = false;
     game_stopped = true;
     round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
     FOREACH_CLIENT(IS_PLAYER(it), { nades_Clear(it); });
     return 1;
 }
bool ca_isEliminated (entity e)
Definition at line 148 of file sv_clanarena.qc.
References FRAGS_PLAYER_OUT_OF_GAME, and IS_DEAD.
Referenced by REGISTER_MUTATOR().
 {
     if(e.caplayer == 1 && (IS_DEAD(e) || e.frags == FRAGS_PLAYER_OUT_OF_GAME))
         return true;
     if(e.caplayer == 0.5)
         return true;
     return false;
 }
void CA_RoundStart ()
Definition at line 107 of file sv_clanarena.qc.
References allowed_to_spawn, boolean, and warmup_stage.
Referenced by REGISTER_MUTATOR().
 {
     allowed_to_spawn = boolean(warmup_stage);
 }
REGISTER_MUTATOR (ca , false)
Definition at line 28 of file sv_clanarena.qh.
References allowed_to_spawn, autocvar_g_ca_point_leadlimit, autocvar_g_ca_point_limit, autocvar_g_ca_round_timelimit, autocvar_g_ca_team_spawns, autocvar_g_ca_teams_override, autocvar_g_ca_warmup, BITS, bound(), CA_CheckTeams(), CA_CheckWinner(), ca_isEliminated(), CA_RoundStart(), ca_teams, cvar(), EliminatedPlayers_Init(), GameRules_limit_lead(), GameRules_limit_score(), GameRules_scoring, GameRules_spawning_teams(), GameRules_teams(), MUTATOR_ONADD, MUTATOR_STATIC, round_handler_Init(), round_handler_Spawn(), SFL_SORT_PRIO_PRIMARY, and ST_CA_ROUNDS.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         GameRules_teams(true);
         GameRules_spawning_teams(autocvar_g_ca_team_spawns);
         GameRules_limit_score(autocvar_g_ca_point_limit);
         GameRules_limit_lead(autocvar_g_ca_point_leadlimit);
         ca_teams = autocvar_g_ca_teams_override;
         if (ca_teams < 2)
             ca_teams = cvar("g_ca_teams"); // read the cvar directly as it gets written earlier in the same frame
         ca_teams = BITS(bound(2, ca_teams, 4));
         GameRules_scoring(ca_teams, SFL_SORT_PRIO_PRIMARY, 0, {
             field_team(ST_CA_ROUNDS, "rounds", SFL_SORT_PRIO_PRIMARY);
         });
         allowed_to_spawn = true;
         round_handler_Spawn(CA_CheckTeams, CA_CheckWinner, CA_RoundStart);
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         EliminatedPlayers_Init(ca_isEliminated);
     }
     return 0;
 }
Variable Documentation
bool allowed_to_spawn
Definition at line 19 of file sv_clanarena.qh.
Referenced by CA_CheckTeams(), CA_CheckWinner(), CA_RoundStart(), MUTATOR_HOOKFUNCTION(), and REGISTER_MUTATOR().
int autocvar_g_ca_point_leadlimit
Definition at line 9 of file sv_clanarena.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_point_limit
Definition at line 8 of file sv_clanarena.qh.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_round_timelimit
Definition at line 10 of file sv_clanarena.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().
bool autocvar_g_ca_team_spawns
Definition at line 11 of file sv_clanarena.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_teams_override
Definition at line 13 of file sv_clanarena.qh.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_warmup
Definition at line 14 of file sv_clanarena.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().
string autocvar_g_ca_weaponarena = "most"
Definition at line 15 of file sv_clanarena.qh.
Referenced by MUTATOR_HOOKFUNCTION().
int ca_teams
Definition at line 18 of file sv_clanarena.qh.
Referenced by CA_CheckTeams(), MUTATOR_HOOKFUNCTION(), and REGISTER_MUTATOR().
float caplayer
Definition at line 56 of file sv_clanarena.qh.
Referenced by checkSpectatorBlock(), and nJoinAllowed().
const int ST_CA_ROUNDS = 1
Definition at line 21 of file sv_clanarena.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().