Xonotic: menu/xonotic/inputbox.qc File Reference
inputbox.qc File Reference
#include "inputbox.qh"
Functions
entity makeXonoticInputBox (float doEditColorCodes, string theCvar)
entity makeXonoticInputBox_T (float doEditColorCodes, string theCvar, string theTooltip)
void XonoticInputBox_configureXonoticInputBox (entity me, float doEditColorCodes, string theCvar, string theTooltip)
void XonoticInputBox_focusLeave (entity me)
float XonoticInputBox_keyDown (entity me, float key, float ascii, float shift)
void XonoticInputBox_loadCvars (entity me)
void XonoticInputBox_saveCvars (entity me)
void XonoticInputBox_setText (entity me, string val)
Function Documentation
entity makeXonoticInputBox (float doEditColorCodes, string theCvar)
Definition at line 10 of file inputbox.qc.
References makeXonoticInputBox_T(), and string_null.
Referenced by XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticHUDExitDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticServerListTab_fill(), and XonoticUserbindEditDialog_fill().
 {
     return makeXonoticInputBox_T(doEditColorCodes, theCvar, string_null);
 }
entity makeXonoticInputBox_T (float doEditColorCodes, string theCvar, string theTooltip)
Definition at line 3 of file inputbox.qc.
References entity(), and NEW.
Referenced by makeXonoticInputBox(), XonoticFirstRunDialog_fill(), XonoticMiscSettingsTab_fill(), XonoticProfileTab_fill(), and XonoticServerCreateTab_fill().
 {
     entity me;
     me = NEW(XonoticInputBox);
     me.configureXonoticInputBox(me, doEditColorCodes, theCvar, theTooltip);
     return me;
 }
void XonoticInputBox_configureXonoticInputBox (entity me, float doEditColorCodes, string theCvar, string theTooltip)
Definition at line 14 of file inputbox.qc.
References setZonedTooltip(), string_null, and strlen().
 {
     me.configureInputBox(me, "", 0, me.fontSize, me.image);
     me.editColorCodes = doEditColorCodes;
     me.cvarName = (theCvar) ? theCvar : string_null;
     me.loadCvars(me);
     setZonedTooltip(me, theTooltip, theCvar);
     me.cursorPos = strlen(me.text);
 }
void XonoticInputBox_focusLeave (entity me)
Definition at line 23 of file inputbox.qc.
 {
     me.saveCvars(me);
 }
float XonoticInputBox_keyDown (entity me, float key, float ascii, float shift)
Definition at line 53 of file inputbox.qc.
References K_ENTER, K_KP_ENTER, and SUPER.
 {
     float r;
     r = 0;
     if(key == K_ENTER || key == K_KP_ENTER)
     {
         if(me.cvarName)
         {
             me.saveCvars(me);
             r = 1;
         }
         if(me.onEnter)
             me.onEnter(me, me.onEnterEntity);
     }
     if(SUPER(XonoticInputBox).keyDown(me, key, ascii, shift))
         r = 1;
     return r;
 }
void XonoticInputBox_loadCvars (entity me)
Definition at line 40 of file inputbox.qc.
References cvar_string(), and SUPER.
 {
     if (!me.cvarName)
         return;
     SUPER(XonoticInputBox).setText(me, cvar_string(me.cvarName));
 }
void XonoticInputBox_saveCvars (entity me)
Definition at line 46 of file inputbox.qc.
References CheckSendCvars(), and cvar_set().
 {
     if (!me.cvarName)
         return;
     cvar_set(me.cvarName, me.text);
     CheckSendCvars(me, me.cvarName);
 }
void XonoticInputBox_setText (entity me, string val)
Definition at line 27 of file inputbox.qc.
References SUPER.
 {
     if(me.text != val)
     {
         SUPER(XonoticInputBox).setText(me, val);
         if(me.onChange)
             me.onChange(me, me.onChangeEntity);
         if(me.saveImmediately)
             me.saveCvars(me);
     }
     else
         SUPER(XonoticInputBox).setText(me, val);
 }