Xonotic: common/mutators/mutator/random_gravity/sv_random_gravity.qc File Reference
sv_random_gravity.qc File Reference
#include "sv_random_gravity.qh"
Functions
MUTATOR_HOOKFUNCTION (random_gravity, SV_StartFrame)
MUTATOR_HOOKFUNCTION (random_gravity, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (random_gravity, BuildMutatorsPrettyString)
Variables
float autocvar_g_random_gravity_delay
float autocvar_g_random_gravity_max
float autocvar_g_random_gravity_min
float autocvar_g_random_gravity_negative
float autocvar_g_random_gravity_negative_chance
float autocvar_g_random_gravity_positive
Function Documentation
MUTATOR_HOOKFUNCTION (random_gravity , SV_StartFrame)
Definition at line 25 of file sv_random_gravity.qc.
References autocvar_g_random_gravity_delay, autocvar_g_random_gravity_max, autocvar_g_random_gravity_min, autocvar_g_random_gravity_negative, autocvar_g_random_gravity_negative_chance, autocvar_g_random_gravity_positive, autocvar_sv_gravity, bound(), cvar(), cvar_set(), ftos(), LOG_TRACE(), random(), round_handler_IsActive, round_handler_IsRoundStarted, and time.
 {
     if(game_stopped || !cvar("g_random_gravity")) return false;
     if(time < gravity_delay) return false;
     if(time < game_starttime) return false;
     if(round_handler_IsActive() && !round_handler_IsRoundStarted()) return false;
     if(random() >= autocvar_g_random_gravity_negative_chance)
         cvar_set("sv_gravity", ftos(bound(autocvar_g_random_gravity_min, random() - random() * -autocvar_g_random_gravity_negative, autocvar_g_random_gravity_max)));
     else
         cvar_set("sv_gravity", ftos(bound(autocvar_g_random_gravity_min, random() * autocvar_g_random_gravity_positive, autocvar_g_random_gravity_max)));
     gravity_delay = time + autocvar_g_random_gravity_delay;
     LOG_TRACE("Gravity is now: ", ftos(autocvar_sv_gravity));
 }
MUTATOR_HOOKFUNCTION (random_gravity , BuildMutatorsString)
Definition at line 42 of file sv_random_gravity.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":RandomGravity");
 }
MUTATOR_HOOKFUNCTION (random_gravity , BuildMutatorsPrettyString)
Definition at line 47 of file sv_random_gravity.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Random gravity");
 }
Variable Documentation
float autocvar_g_random_gravity_delay
Definition at line 13 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_random_gravity_max
Definition at line 10 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_random_gravity_min
Definition at line 9 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_random_gravity_negative
Definition at line 12 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_random_gravity_negative_chance
Definition at line 8 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_random_gravity_positive
Definition at line 11 of file sv_random_gravity.qc.
Referenced by MUTATOR_HOOKFUNCTION().