Xonotic: client/hud/panel/strafehud.qh File Reference
strafehud.qh File Reference
#include "../panel.qh"
Functions
string GetLengthUnit (int)
float GetLengthUnitFactor (int)
void HUD_Panel_DrawStrafeHUD (float, float, vector, float, int, int)
void StrafeHUD_drawGradient (vector, vector, vector, float, float, float, float, int)
vector StrafeHUD_mixColors (vector, vector, float)
Function Documentation
string GetLengthUnit (int)
Definition at line 902 of file strafehud.qc.
References strcat().
Referenced by HUD_StrafeHUD().
 {
     switch(length_unit)
     {
         // translator-friendly strings without the initial space
         default:
         case 1: return strcat(" ", _("qu"));
         case 2: return strcat(" ", _("m"));
         case 3: return strcat(" ", _("km"));
         case 4: return strcat(" ", _("mi"));
         case 5: return strcat(" ", _("nmi"));
     }
 }
float GetLengthUnitFactor (int)
Definition at line 889 of file strafehud.qc.
Referenced by HUD_StrafeHUD().
 {
     switch(length_unit)
     {
         default:
         case 1: return 1.0;
         case 2: return 0.0254;
         case 3: return 0.0254 * 0.001;
         case 4: return 0.0254 * 0.001 * 0.6213711922;
         case 5: return 0.0254 * 0.001 * 0.5399568035;
     }
 }
void HUD_Panel_DrawStrafeHUD (float , float , vector , float , int , int)
Definition at line 778 of file strafehud.qc.
References autocvar_hud_panel_strafehud_bar_neutral_color, direction, drawfill(), DRAWFLAG_NORMAL, eX, fabs(), hidden_width, HUD_Panel_DrawProgressBar(), max(), min(), panel_pos, panel_size, size, StrafeHUD_drawGradient(), and vector().
Referenced by HUD_StrafeHUD().
 {
     float mirror_offset, mirror_width;
     vector size = panel_size;
     vector mirror_size = panel_size;
     float original_width = width;
     float hiddencolor_width;
     if(alpha <= 0 && type != 2 || width <= 0) return;
     if(type == 2 && gradientType == 0) type = 0;
     if(offset < 0)
     {
         mirror_width = min(fabs(offset), width);
         mirror_offset = panel_size.x + hidden_width - fabs(offset);
         width += offset;
         offset = 0;
     }
     else
     {
         mirror_width = min(offset + width - panel_size.x - hidden_width, width);
         mirror_offset = max(offset - panel_size.x - hidden_width, 0);
     }
     if((offset + width) > panel_size.x)
     {
         width = panel_size.x - offset;
     }
     if(mirror_offset < 0)
     {
         mirror_width += mirror_offset;
         mirror_offset = 0;
     }
     if((mirror_offset + mirror_width) > panel_size.x)
     {
         mirror_width = panel_size.x - mirror_offset;
     }
     if(width < 0) width = 0;
     if(mirror_width < 0) mirror_width = 0;
     hiddencolor_width = original_width - width - mirror_width;
     if(direction < 0) // swap mirror and non-mirror values if direction points left
     {
         offset += mirror_offset;
         mirror_offset = offset - mirror_offset;
         offset -= mirror_offset;
         width += mirror_width;
         mirror_width = width - mirror_width;
         width -= mirror_width;
     }
     size.x = width;
     mirror_size.x = mirror_width;
     switch(type)
     {
         default:
         case 0: // no styling (drawfill)
             if(mirror_size.x > 0 && mirror_size.y > 0) drawfill(panel_pos + eX * mirror_offset, mirror_size, color, alpha, DRAWFLAG_NORMAL);
             if(size.x > 0 && size.y > 0) drawfill(panel_pos + eX * offset, size, color, alpha, DRAWFLAG_NORMAL);
             break;
         case 1: // progress bar style
             if(mirror_size.x > 0 && mirror_size.y > 0) HUD_Panel_DrawProgressBar(panel_pos + eX * mirror_offset, mirror_size, "progressbar", 1, 0, 0, color, alpha, DRAWFLAG_NORMAL);
             if(size.x > 0 && size.y > 0) HUD_Panel_DrawProgressBar(panel_pos + eX * offset, size, "progressbar", 1, 0, 0, color, alpha, DRAWFLAG_NORMAL);
             break;
         case 2: // gradient style (types: 1 = left, 2 = right, 3 = both)
             StrafeHUD_drawGradient(color, autocvar_hud_panel_strafehud_bar_neutral_color, mirror_size, original_width, mirror_offset, alpha, width + (mirror_offset == 0 ? hiddencolor_width : 0), gradientType);
             StrafeHUD_drawGradient(color, autocvar_hud_panel_strafehud_bar_neutral_color, size, original_width, offset, alpha, (offset == 0 ? hiddencolor_width : 0), gradientType);
     }
 }
void StrafeHUD_drawGradient (vector , vector , vector , float , float , float , float , int)
Definition at line 865 of file strafehud.qc.
References autocvar_hud_panel_strafehud_bar_neutral_alpha, bound(), drawfill(), DRAWFLAG_NORMAL, eX, panel_pos, size, StrafeHUD_mixColors(), and vector().
Referenced by HUD_Panel_DrawStrafeHUD().
 {
     float color_ratio, alpha1, alpha2;
     vector gradient_size = size;
     alpha1 = bound(0, alpha, 1);
     alpha2 = bound(0, autocvar_hud_panel_strafehud_bar_neutral_alpha, 1);
     if((alpha1+alpha2) == 0) return;
     color_ratio = alpha1/(alpha1+alpha2);
     for(int i = 0; i < size.x; ++i)
     {
         float ratio, alpha_ratio, combine_ratio1, combine_ratio2;
         gradient_size.x = size.x - i < 1 ? size.x - i : 1;
         ratio = (i + gradientOffset) / original_width * (gradientType == 3 ? 2 : 1);
         if(ratio > 1) ratio = 2 - ratio;
         if(gradientType != 2) ratio = 1 - ratio;
         alpha_ratio = alpha1 - (alpha1 - alpha2) * ratio;
         combine_ratio1 = ratio*(1-color_ratio);
         combine_ratio2 = (1-ratio)*color_ratio;
         ratio = (combine_ratio1 + combine_ratio2) == 0 ? 1 : combine_ratio1/(combine_ratio1 + combine_ratio2);
         if(alpha_ratio > 0) drawfill(panel_pos + eX * (offset + i), gradient_size, StrafeHUD_mixColors(color1, color2, ratio), alpha_ratio, DRAWFLAG_NORMAL);
     }
 }
vector StrafeHUD_mixColors (vector , vector , float)
Definition at line 854 of file strafehud.qc.
References vector().
Referenced by HUD_StrafeHUD(), and StrafeHUD_drawGradient().
 {
     vector mixedColor;
     if(ratio <= 0) return color1;
     if(ratio >= 1) return color2;
     mixedColor.x = color1.x + (color2.x - color1.x) * ratio;
     mixedColor.y = color1.y + (color2.y - color1.y) * ratio;
     mixedColor.z = color1.z + (color2.z - color1.z) * ratio;
     return mixedColor;
 }