Xonotic: client/resources.qc File Reference
resources.qc File Reference
Source file that contains implementation of the resource system.
#include "resources.qh"
#include <common/items/item/ammo.qh>
Functions
float GetResource (entity e, int res_type)
Returns the current amount of resource the given entity has.
float GetResourceField (int res_type)
Converts resource type (a RES_* constant) to entity field.
int GetResourceType (.float res_field)
Converts an entity field to resource type.
void SetResource (entity e, int res_type, float amount)
Sets the current amount of resource the given entity will have.
bool SetResourceExplicit (entity e, int res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
void TakeResource (entity receiver, int res_type, float amount)
Takes an entity some resource.
void TakeResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Detailed Description
Source file that contains implementation of the resource system.
Copyright
GNU GPLv2 or any later version.
Definition in file resources.qc.
Function Documentation
float GetResource (entity e, int res_type)
Returns the current amount of resource the given entity has.
Parameters
[in] e Entity to check.
[in] res_type Type of the resource (a RES_* constant).
Returns
Current amount of resource the given entity has.
Definition at line 8 of file resources.qc.
Referenced by assault_decreaser_sprite_visible(), assault_objective_decrease_use(), assault_wall_think(), basketball_touch(), bot_cmd_eval(), buff_Medic_Heal(), CheatImpulse(), ClientCommand_kill(), CommonCommand_editmob(), CopyBody(), cpicon_draw(), cpicon_send(), ctf_CheckFlagReturn(), ctf_FlagcarrierWaypoints(), ctf_Handle_Drop(), Damage(), destructible_heal(), dompointtouch(), door_damage(), door_reset(), door_trigger_touch(), Draw_ShowNames(), Draw_ShowNames_All(), football_touch(), formatmessage(), frag_centermessage_override(), freezetag_count_alive_players(), freezetag_LastPlayerForTeam(), generator_draw(), generator_send(), GENERIC_COMMAND(), GiveResource(), GiveResourceWithLimit(), GrapplingHook_Damage(), havocbot_goalrating_ctf_enemyflag(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_ft_freeplayers(), havocbot_goalrating_item_can_be_left_to_teammate(), havocbot_movetogoal(), instagib_ammocheck(), Invasion_CheckWinner(), LinkDoors(), MapVote_Tick(), Monster_Attack_Leap_Check(), Monster_Damage(), Monster_Dead_Damage(), Monster_Frozen_Think(), Monster_Heal(), Monster_Move_Target(), Monster_Spawn_Setup(), Monster_Think(), Monster_ValidTarget(), MUTATOR_HOOKFUNCTION(), navigation_routerating(), NET_HANDLE(), Obituary(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Heal(), ons_ControlPoint_Icon_Spawn(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_UpdateSprite(), ons_GeneratorDamage(), ons_GeneratorHeal(), ons_GeneratorReset(), ons_GeneratorSetup(), Onslaught_count_generators(), plat_center_touch(), plat_outside_touch(), player_regen(), PlayerCorpseDamage(), PlayerDamage(), PlayerHeal(), PlayerHealth(), PlayerPostThink(), PlayerPreThink(), Portal_Damage(), PutObserverInServer(), readplayerstartcvars(), REGISTER_ITEM(), RotRegen(), SpectateCopy(), TakeResource(), TakeResourceWithLimit(), target_objective_spawn_evalfunc(), test_weapons_hurt(), turret_draw(), turret_draw2d(), vehicles_damage(), vehicles_heal(), vehicles_painframe(), vehicles_projectile_damage(), vehicles_regen(), vehicles_regen_resource(), W_DecreaseAmmo(), W_Reload(), W_ReloadedAndReady(), W_ThrowNewWeapon(), W_WeaponFrame(), and weapon_defaultspawnfunc().
 {
     return e.(GetResourceField(res_type));
 }
float GetResourceField (int res_type)
Converts resource type (a RES_* constant) to entity field.
Parameters
[in] res_type Type of the resource.
Returns
Entity field for that resource.
Definition at line 69 of file resources.qc.
Referenced by SetResourceExplicit().
 {
     switch (res_type)
     {
         case RES_HEALTH: { return health; }
         case RES_ARMOR: { return armorvalue; }
         case RES_SHELLS: { return ammo_shells; }
         case RES_BULLETS: { return ammo_nails; }
         case RES_ROCKETS: { return ammo_rockets; }
         case RES_CELLS: { return ammo_cells; }
         case RES_PLASMA: { return ammo_plasma; }
         case RES_FUEL: { return ammo_fuel; }
     }
     error("GetResourceField: Invalid resource type.");
     return health;
 }
int GetResourceType (.float res_field)
Converts an entity field to resource type.
Parameters
[in] res_field Entity field to convert.
Returns
Resource type (a RES_* constant).
Definition at line 52 of file resources.qc.
 {
     switch (res_field)
     {
         case health: { return RES_HEALTH; }
         case armorvalue: { return RES_ARMOR; }
         case ammo_shells: { return RES_SHELLS; }
         case ammo_nails: { return RES_BULLETS; }
         case ammo_rockets: { return RES_ROCKETS; }
         case ammo_cells: { return RES_CELLS; }
         case ammo_plasma: { return RES_PLASMA; }
         case ammo_fuel: { return RES_FUEL; }
     }
     error("GetResourceType: Invalid field.");
     return 0;
 }
void SetResource (entity e, int res_type, float amount)
Sets the current amount of resource the given entity will have.
Sets the current amount of resource the given entity will have but limited to the max amount allowed for the resource type.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
No return.
Definition at line 24 of file resources.qc.
Referenced by buff_Medic_Heal(), CheatImpulse(), Damage(), Freeze(), GENERIC_COMMAND(), GiveResource(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), PutPlayerInServer(), readplayerstartcvars(), REGISTER_MUTATOR(), RotRegen(), SetResource(), TakeResource(), target_init_use(), Unfreeze(), vehicles_regen_resource(), W_DecreaseAmmo(), W_ReloadedAndReady(), W_ThrowNewWeapon(), and weapon_defaultspawnfunc().
 {
     SetResourceExplicit(e, res_type, amount);
 }
bool SetResourceExplicit (entity e, int res_type, float amount)
Sets the resource amount of an entity without calling any hooks.
Parameters
[in,out] e Entity to adjust.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to set.
Returns
Boolean for whether the ammo amount was changed
Definition at line 13 of file resources.qc.
Referenced by assault_objective_decrease_use(), assault_objective_reset(), assault_objective_use(), CheatCommand(), CopyBody(), ctf_FlagDamage(), ctf_FlagSetup(), ctf_FlagThink(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_RespawnFlag(), Damage(), door_damage(), door_go_down(), Draw_ShowNames_All(), FireGrapplingHook(), FixIntermissionClient(), ft_RemovePlayer(), LinkDoors(), MapVote_Tick(), Monster_Dead_Fade(), Monster_Frozen_Think(), Monster_Reset(), Monster_Spawn_Setup(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Spawn(), ons_GeneratorReset(), ons_GeneratorSetup(), PlayerPreThink(), Portal_Spawn(), Portal_TeleportPlayer(), PutObserverInServer(), REGISTER_ITEM(), SetResource(), spawnfunc(), SpectateCopy(), target_give_init(), turret_construct(), and vehicles_projectile().
 {
     .float res_field = GetResourceField(res_type);
     if (e.(res_field) != amount)
     {
         e.(res_field) = amount;
         return true;
     }
     return false;
 }
void TakeResource (entity receiver, int res_type, float amount)
Takes an entity some resource.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
Returns
No return.
Definition at line 29 of file resources.qc.
Referenced by assault_objective_decrease_use(), ctf_FlagDamage(), ctf_FlagThink(), door_damage(), GrapplingHook_Damage(), Monster_Damage(), Monster_Dead_Damage(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Icon_Damage(), ons_GeneratorDamage(), PlayerCorpseDamage(), PlayerDamage(), PM_jetpack(), Portal_Damage(), TakeResource(), TakeResourceWithLimit(), vehicles_damage(), and vehicles_projectile_damage().
 {
     if (amount == 0)
     {
         return;
     }
     SetResource(receiver, res_type, GetResource(receiver, res_type) - amount);
 }
void TakeResourceWithLimit (entity receiver, int res_type, float amount, float limit)
Takes an entity some resource but not less than a limit.
Parameters
[in,out] receiver Entity to take resource from.
[in] res_type Type of the resource (a RES_* constant).
[in] amount Amount of resource to take.
[in] limit Limit of resources to take.
Returns
No return.
Definition at line 38 of file resources.qc.
Referenced by TakeResourceWithLimit().
 {
     if (amount == 0)
     {
         return;
     }
     float current_amount = GetResource(receiver, res_type);
     if (current_amount - amount < limit)
     {
         amount = limit + current_amount;
     }
     TakeResource(receiver, res_type, amount);
 }