Xonotic: common/minigames/minigame/nmm.qc File Reference
nmm.qc File Reference
#include "nmm.qh"
Functions
entity nmm_find_tile (entity minig, string id)
bool nmm_in_mill (entity tile)
bool nmm_in_mill_string (entity tile, string s)
void nmm_init_tiles (entity minig)
void nmm_kill_tiles (entity minig)
void nmm_spawn_tile (string id, entity minig, int distance)
void nmm_spawn_tile_square (entity minig, int offset, int skip)
bool nmm_tile_adjacent (entity tile1, entity tile2)
string nmm_tile_build_hmill (entity tile)
string nmm_tile_build_vmill (entity tile)
bool nmm_tile_canmove (entity tile)
REGISTER_MINIGAME (nmm, _("Nine Men's Morris"))
Variables
const int NMM_PIECE_BOARD = 0x2
const int NMM_PIECE_DEAD = 0x0
const int NMM_PIECE_HOME = 0x1
int nmm_tile_distance
string nmm_tile_hmill
entity nmm_tile_piece
string nmm_tile_vmill
const int NMM_TURN_FLY = 0x0400
const int NMM_TURN_MOVE = 0x0200
const int NMM_TURN_PLACE = 0x0100
const int NMM_TURN_TAKE = 0x0800
const int NMM_TURN_TAKEANY =0x1000
const int NMM_TURN_TEAM = 0x00ff
const int NMM_TURN_TEAM1 = 0x0001
const int NMM_TURN_TEAM2 = 0x0002
const int NMM_TURN_TYPE = 0xff00
const int NMM_TURN_WIN = 0x2000
Function Documentation
entity nmm_find_tile (entity minig, string id)
Definition at line 143 of file nmm.qc.
References entity(), findentity(), NULL, and owner.
Referenced by nmm_in_mill(), and nmm_in_mill_string().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_nmm_tile" && e.netname == id )
             return e;
     return NULL;
 }
bool nmm_in_mill (entity tile)
Definition at line 190 of file nmm.qc.
References active_minigame, argv(), drawfill(), DRAWFLAG_ADDITIVE, DRAWFLAG_NORMAL, drawpic(), entity(), eX, eY, findentity(), FOREACH_MINIGAME_ENTITY, ftos(), hud_fontsize, HUD_Panel_DrawBg, int, K_DOWNARROW, K_ENTER, K_KP_DOWNARROW, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, K_SPACE, K_UPARROW, LOG_TRACE(), MINIG_SF_UPDATE, minigame_cmd, minigame_drawcolorcodedstring_trunc(), minigame_drawcolorcodedstring_wrapped(), minigame_drawpic_centered(), minigame_drawstring_wrapped(), minigame_hud_denormalize(), minigame_hud_denormalize_size(), minigame_hud_fitsqare, minigame_hud_mouse_in(), minigame_hud_simpleboard(), minigame_prompt(), minigame_relative_tile(), minigame_self, minigame_texture(), minigame_tile_name(), msle_spawn(), nmm_find_tile(), nmm_in_mill_string(), nmm_init_tiles(), nmm_kill_tiles(), NMM_PIECE_BOARD, NMM_PIECE_DEAD, NMM_PIECE_HOME, nmm_tile_adjacent(), nmm_tile_canmove(), NMM_TURN_TAKEANY, NMM_TURN_TEAM, NMM_TURN_TEAM1, NULL, owner, panel_fg_alpha, strcat(), strcpy, strfree, and vector().
 {
     return tile.nmm_tile_piece &&  (
         nmm_in_mill_string(tile,tile.nmm_tile_hmill) ||
         nmm_in_mill_string(tile,tile.nmm_tile_vmill) );
 }
bool nmm_in_mill_string (entity tile, string s)
Definition at line 177 of file nmm.qc.
References argv(), entity(), nmm_find_tile(), and tokenize().
Referenced by nmm_in_mill().
 {
     int argc = tokenize(s);
     for ( int i = 0; i < argc; i++ )
     {
         entity e = nmm_find_tile(tile.owner,argv(i));
         if ( !e || !e.nmm_tile_piece || e.nmm_tile_piece.team != tile.nmm_tile_piece.team )
             return false;
     }
     return true;
 }
void nmm_init_tiles (entity minig)
Definition at line 137 of file nmm.qc.
References nmm_spawn_tile_square().
Referenced by nmm_in_mill().
 {
     nmm_spawn_tile_square(minig,0,2);
 }
void nmm_kill_tiles (entity minig)
Definition at line 123 of file nmm.qc.
References entity(), findentity(), NULL, owner, and strfree.
Referenced by nmm_in_mill().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_nmm_tile" )
         {
             strfree(e.netname);
             strfree(e.nmm_tile_hmill);
             strfree(e.nmm_tile_vmill);
             delete(e);
         }
 }
void nmm_spawn_tile (string id, entity minig, int distance)
Definition at line 85 of file nmm.qc.
References entity(), minigame_tile_pos(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), and strzone().
Referenced by nmm_spawn_tile_square().
 {
     // TODO global variable + list_next for simpler tile loops
     entity e = new(minigame_nmm_tile);
     e.origin = minigame_tile_pos(id,7,7);
     e.netname = id;
     e.owner = minig;
     e.team = 0;
     e.nmm_tile_distance = distance;
     e.nmm_tile_hmill = strzone(nmm_tile_build_hmill(e));
     e.nmm_tile_vmill = strzone(nmm_tile_build_vmill(e));
 }
void nmm_spawn_tile_square (entity minig, int offset, int skip)
Definition at line 102 of file nmm.qc.
References minigame_tile_buildname(), nmm_spawn_tile(), and strzone().
Referenced by nmm_init_tiles().
 {
     int letter = offset;
     int number = offset;
     for ( int i = 0; i < 3; i++ )
     {
         number = offset;
         for ( int j = 0; j < 3; j++ )
         {
             if ( i != 1 || j != 1 )
                 nmm_spawn_tile(strzone(minigame_tile_buildname(letter,number)),minig, skip+1);
             number += skip+1;
         }
         letter += skip+1;
     }
     if ( skip > 0 )
         nmm_spawn_tile_square(minig,offset+1,skip-1);
 }
bool nmm_tile_adjacent (entity tile1, entity tile2)
Definition at line 153 of file nmm.qc.
References fabs(), minigame_tile_letter(), and minigame_tile_number().
Referenced by nmm_in_mill(), and nmm_tile_canmove().
 {
     int dnumber = fabs ( minigame_tile_number(tile1.netname) - minigame_tile_number(tile2.netname) );
     int dletter = fabs ( minigame_tile_letter(tile1.netname) - minigame_tile_letter(tile2.netname) );
     return ( dnumber == 0 && ( dletter == 1 || dletter == tile1.nmm_tile_distance ) ) ||
         ( dletter == 0 && ( dnumber == 1 || dnumber == tile1.nmm_tile_distance ) );
 }
string nmm_tile_build_hmill (entity tile)
Definition at line 30 of file nmm.qc.
References minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), and strcat().
Referenced by nmm_spawn_tile().
 {
     int number = minigame_tile_number(tile.netname);
     int letter = minigame_tile_letter(tile.netname);
     if ( number == letter || number+letter == 6 )
     {
         int add = letter < 3 ? 1 : -1;
         return strcat(tile.netname," ",
             minigame_tile_buildname(letter+add*tile.nmm_tile_distance,number)," ",
             minigame_tile_buildname(letter+add*2*tile.nmm_tile_distance,number) );
     }
     else if ( letter == 3 )
         return strcat(minigame_tile_buildname(letter-tile.nmm_tile_distance,number)," ",
             tile.netname," ",
             minigame_tile_buildname(letter+tile.nmm_tile_distance,number) );
     else if ( letter < 3 )
         return strcat(minigame_tile_buildname(0,number)," ",
             minigame_tile_buildname(1,number)," ",
             minigame_tile_buildname(2,number) );
     else
         return strcat(minigame_tile_buildname(4,number)," ",
             minigame_tile_buildname(5,number)," ",
             minigame_tile_buildname(6,number) );
 }
string nmm_tile_build_vmill (entity tile)
Definition at line 56 of file nmm.qc.
References minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), and strcat().
Referenced by nmm_spawn_tile().
 {
     int letter = minigame_tile_letter(tile.netname);
     int number = minigame_tile_number(tile.netname);
     if ( letter == number || letter+number == 6 )
     {
         int add = number < 3 ? 1 : -1;
         return strcat(tile.netname," ",
             minigame_tile_buildname(letter,number+add*tile.nmm_tile_distance)," ",
             minigame_tile_buildname(letter,number+add*2*tile.nmm_tile_distance) );
     }
     else if ( number == 3 )
         return strcat(minigame_tile_buildname(letter,number-tile.nmm_tile_distance)," ",
             tile.netname," ",
             minigame_tile_buildname(letter,number+tile.nmm_tile_distance) );
     else if ( number < 3 )
         return strcat(minigame_tile_buildname(letter,0)," ",
             minigame_tile_buildname(letter,1)," ",
             minigame_tile_buildname(letter,2) );
     else
         return strcat(minigame_tile_buildname(letter,4)," ",
             minigame_tile_buildname(letter,5)," ",
             minigame_tile_buildname(letter,6) );
 }
bool nmm_tile_canmove (entity tile)
Definition at line 164 of file nmm.qc.
References entity(), findentity(), nmm_tile_adjacent(), NULL, and owner.
Referenced by nmm_in_mill().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,tile.owner) ) )
         if ( e.classname == "minigame_nmm_tile" && !e.nmm_tile_piece
                 && nmm_tile_adjacent(e,tile) )
         {
             return true;
         }
     return false;
 }
REGISTER_MINIGAME (nmm , _("Nine Men's Morris"))
Variable Documentation
const int NMM_PIECE_BOARD = 0x2
Definition at line 22 of file nmm.qc.
Referenced by nmm_in_mill().
const int NMM_PIECE_DEAD = 0x0
Definition at line 20 of file nmm.qc.
Referenced by nmm_in_mill().
const int NMM_PIECE_HOME = 0x1
Definition at line 21 of file nmm.qc.
Referenced by nmm_in_mill().
int nmm_tile_distance
Definition at line 24 of file nmm.qc.
string nmm_tile_hmill
Definition at line 26 of file nmm.qc.
entity nmm_tile_piece
Definition at line 25 of file nmm.qc.
string nmm_tile_vmill
Definition at line 27 of file nmm.qc.
const int NMM_TURN_FLY = 0x0400
Definition at line 11 of file nmm.qc.
const int NMM_TURN_MOVE = 0x0200
Definition at line 10 of file nmm.qc.
const int NMM_TURN_PLACE = 0x0100
Definition at line 9 of file nmm.qc.
const int NMM_TURN_TAKE = 0x0800
Definition at line 12 of file nmm.qc.
const int NMM_TURN_TAKEANY =0x1000
Definition at line 13 of file nmm.qc.
Referenced by nmm_in_mill().
const int NMM_TURN_TEAM = 0x00ff
Definition at line 18 of file nmm.qc.
Referenced by nmm_in_mill().
const int NMM_TURN_TEAM1 = 0x0001
Definition at line 16 of file nmm.qc.
Referenced by nmm_in_mill().
const int NMM_TURN_TEAM2 = 0x0002
Definition at line 17 of file nmm.qc.
const int NMM_TURN_TYPE = 0xff00
Definition at line 15 of file nmm.qc.
const int NMM_TURN_WIN = 0x2000
Definition at line 14 of file nmm.qc.