Xonotic: menu/xonotic/demolist.qh File Reference
demolist.qh File Reference
#include "mainwindow.qh"
#include "listbox.qh"
Functions
METHOD (XonoticDemoList, configureXonoticDemoList, void(entity))
METHOD (XonoticDemoList, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticDemoList, drawListBoxItem, void(entity, int, vector, bool, bool))
METHOD (XonoticDemoList, getDemos, void(entity))
METHOD (XonoticDemoList, startDemo, void(entity))
METHOD (XonoticDemoList, timeDemo, void(entity))
METHOD (XonoticDemoList, demoName, string(entity, float))
METHOD (XonoticDemoList, doubleClickListBoxItem, void(entity, float, vector))
METHOD (XonoticDemoList, keyDown, float(entity, float, float, float))
METHOD (XonoticDemoList, destroy, void(entity))
METHOD (XonoticDemoList, showNotify, void(entity))
entity makeXonoticDemoList ()
void DemoList_Refresh_Click (entity btn, entity me)
void DemoList_Filter_Change (entity box, entity me)
Variables
entity demolist
Function Documentation
void DemoList_Filter_Change (entity box, entity me)
Definition at line 130 of file demolist.qc.
References strcat(), string_null, strstrofs, strunzone(), and strzone().
Referenced by XonoticDemoBrowserTab_fill().
 {
     if(me.filterString)
         strunzone(me.filterString);
     if(box.text != "")
     {
         if (strstrofs(box.text, "*", 0) >= 0 || strstrofs(box.text, "?", 0) >= 0)
             me.filterString = strzone(box.text);
         else
             me.filterString = strzone(strcat("*", box.text, "*"));
     }
     else
         me.filterString = string_null;
     me.getDemos(me);
 }
void DemoList_Refresh_Click (entity btn, entity me)
Definition at line 124 of file demolist.qc.
Referenced by XonoticDemoBrowserTab_fill().
 {
     me.getDemos(me);
     me.setSelected(me, 0); //always select the first element after a list update
 }
entity makeXonoticDemoList ()
Definition at line 5 of file demolist.qc.
References entity(), me, and NEW.
Referenced by XonoticDemoBrowserTab_fill().
 {
     entity me;
     me = NEW(XonoticDemoList);
     me.configureXonoticDemoList(me);
     return me;
 }
METHOD (XonoticDemoList , configureXonoticDemoList , void(entity))
METHOD (XonoticDemoList , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticDemoList , drawListBoxItem , void(entity, int, vector, bool, bool))
METHOD (XonoticDemoList , getDemos , void(entity))
METHOD (XonoticDemoList , startDemo , void(entity))
METHOD (XonoticDemoList , timeDemo , void(entity))
METHOD (XonoticDemoList , demoName , string(entity, float))
METHOD (XonoticDemoList , doubleClickListBoxItem , void(entity, float, vector))
METHOD (XonoticDemoList , keyDown , float(entity, float, float, float))
METHOD (XonoticDemoList , destroy , void(entity))
METHOD (XonoticDemoList , showNotify , void(entity))
Variable Documentation
entity demolist
Definition at line 30 of file demolist.qh.
Referenced by DemoConfirm_Check_Gamestatus(), Handle_StartDemo_Click(), Handle_TimeDemo_Click(), XonoticDemoBrowserTab_fill(), XonoticDemoStartConfirmDialog_fill(), and XonoticDemoTimeConfirmDialog_fill().