Xonotic: Player Class Reference
Player Class Reference
Public Member Functions
Player ()
~Player ()
virtual void describe ()
virtual void display ()
virtual void m_unwind ()
STATIC_METHOD (Client, Add, void(Client this, int _team))
STATIC_METHOD (Client, Remove, void(Client this))
Public Attributes
int clientcolors = this.clientcolors
int colormap = this.colormap
string crypto_encryptmethod = this.crypto_encryptmethod
the string "AES128" if encrypting, and string_null if plaintext
string crypto_idfp = this.crypto_idfp
fingerprint of ID used by the player entity, or string_null if not identified
bool crypto_idfp_signed = this.crypto_idfp_signed
set if the player's ID has been signed
string crypto_keyfp = this.crypto_keyfp
fingerprint of CA key the player used to authenticate
string crypto_mykeyfp = this.crypto_mykeyfp
fingerprint of CA key the server used to authenticate to the player
string crypto_signmethod = this.crypto_signmethod
the string "HMAC-SHA256" if signing, and string_null if plaintext
string netaddress = this.netaddress
Client IP.
string netname = this.netname
Client name.
int playerid = this.playerid
string playermodel = this.playermodel
int playerskin = this.playerskin
int team = this.team
Detailed Description
Definition at line 74 of file client.qh.
Constructor & Destructor Documentation
Player::Player () inline
Definition at line 75 of file client.qh.
References classname, IL_PUSH(), and STR_PLAYER.
                  {
         this.classname = STR_PLAYER;
         IL_PUSH(g_players, this);
     }
Player::~Player () inline
Definition at line 79 of file client.qh.
References IL_REMOVE().
{
         IL_REMOVE(g_players, this);
     }
Member Function Documentation
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
void Client::m_unwind () virtual inherited
Definition at line 84 of file client.qh.
References classname, TC, and UNWIND.
 {
     TC(Client, this);
     #define UNWIND(class) MACRO_BEGIN if (this.instanceOf##class) { METHOD_REFERENCE(class, dtorimpl)(this); } MACRO_END
     switch (this.classname) {
         case "Observer":
             UNWIND(Spectator);
             UNWIND(Player);
             return true;
         case "Spectator":
             UNWIND(Observer);
             UNWIND(Player);
             return true;
         case "Player":
             UNWIND(Observer);
             UNWIND(Spectator);
             return true;
     }
     #undef UNWIND
     return false;
 }
Client::STATIC_METHOD (Client , Add , void(Client this, int _team)) inherited
Client::STATIC_METHOD (Client , Remove , void(Client this)) inherited
Member Data Documentation
int Client::clientcolors = this.clientcolors inherited
Definition at line 13 of file client.qh.
int Client::colormap = this.colormap inherited
Definition at line 11 of file client.qh.
string Client::crypto_encryptmethod = this.crypto_encryptmethod inherited
the string "AES128" if encrypting, and string_null if plaintext
Definition at line 28 of file client.qh.
string Client::crypto_idfp = this.crypto_idfp inherited
fingerprint of ID used by the player entity, or string_null if not identified
Definition at line 24 of file client.qh.
bool Client::crypto_idfp_signed = this.crypto_idfp_signed inherited
set if the player's ID has been signed
Definition at line 26 of file client.qh.
string Client::crypto_keyfp = this.crypto_keyfp inherited
fingerprint of CA key the player used to authenticate
Definition at line 20 of file client.qh.
string Client::crypto_mykeyfp = this.crypto_mykeyfp inherited
fingerprint of CA key the server used to authenticate to the player
Definition at line 22 of file client.qh.
string Client::crypto_signmethod = this.crypto_signmethod inherited
the string "HMAC-SHA256" if signing, and string_null if plaintext
Definition at line 30 of file client.qh.
string Client::netaddress = this.netaddress inherited
Client IP.
Definition at line 15 of file client.qh.
string Client::netname = this.netname inherited
Client name.
Definition at line 10 of file client.qh.
Referenced by W_WeaponFrame().
int Client::playerid = this.playerid inherited
Definition at line 34 of file client.qh.
string Client::playermodel = this.playermodel inherited
Definition at line 16 of file client.qh.
int Client::playerskin = this.playerskin inherited
Definition at line 17 of file client.qh.
int Client::team = this.team inherited
Definition at line 12 of file client.qh.
The documentation for this class was generated from the following file:
server/client.qh