Xonotic: lib/warpzone/common.qc File Reference
common.qc File Reference
#include "common.qh"
Functions
void WarpZone_Accumulator_Add (entity acc, entity wz)
void WarpZone_Accumulator_AddInverse (entity acc, entity wz)
void WarpZone_Accumulator_AddInverseTransform (entity acc, vector t, vector s)
void WarpZone_Accumulator_AddTransform (entity acc, vector t, vector s)
void WarpZone_Accumulator_Clear (entity acc)
vector WarpZone_Camera_camera_transform (entity this, vector org, vector ang)
void WarpZone_Camera_SetUp (entity e, vector my_org, vector my_ang)
vector WarpZone_camera_transform (entity this, vector org, vector ang)
entity WarpZone_Find (vector mi, vector ma)
entity WarpZone_FindRadius (vector org, float rad, bool needlineofsight)
void WarpZone_FindRadius_Recurse (vector org, float rad, vector org0, vector transform, vector shift, bool needlineofsight)
void WarpZone_MakeAllOther ()
void WarpZone_MakeAllSolid ()
float WarpZone_PlaneDist (entity wz, vector v)
void WarpZone_RefSys_Add (entity me, entity wz)
void WarpZone_RefSys_AddIncrementally (entity me, entity ref)
void WarpZone_RefSys_AddInverse (entity me, entity wz)
void WarpZone_RefSys_AddInverseTransform (entity me, vector t, vector s)
void WarpZone_RefSys_AddTransform (entity me, vector t, vector s)
void WarpZone_RefSys_BeginAddingIncrementally (entity me, entity ref)
void WarpZone_RefSys_CheckCreate (entity me)
void WarpZone_RefSys_Clear (entity me)
void WarpZone_RefSys_Copy (entity me, entity from)
void WarpZone_RefSys_GC (entity this)
entity WarpZone_RefSys_SpawnSameRefSys (entity me)
vector WarpZone_RefSys_TransformAngles (entity from, entity to, vector ang)
vector WarpZone_RefSys_TransformOrigin (entity from, entity to, vector org)
vector WarpZone_RefSys_TransformVAngles (entity from, entity to, vector ang)
vector WarpZone_RefSys_TransformVelocity (entity from, entity to, vector vel)
void WarpZone_SetUp (entity e, vector my_org, vector my_ang, vector other_org, vector other_ang)
float WarpZone_TargetPlaneDist (entity wz, vector v)
void WarpZone_Trace_AddTransform (entity wz)
void WarpZone_Trace_InitTransform ()
void WarpZone_TraceBox (vector org, vector mi, vector ma, vector end, float nomonsters, entity forent)
void WarpZone_TraceBox_ThroughZone (vector org, vector mi, vector ma, vector end, float nomonsters, entity forent, entity zone, WarpZone_trace_callback_t cb)
void WarpZone_TraceLine (vector org, vector end, float nomonsters, entity forent)
void WarpZone_TraceToss (entity e, entity forent)
void WarpZone_TraceToss_ThroughZone (entity e, entity forent, entity zone, WarpZone_trace_callback_t cb)
void WarpZone_TrailParticles (entity own, float eff, vector org, vector end)
void WarpZone_TrailParticles_trace_callback (vector from, vector endpos, vector to)
vector WarpZone_TransformAngles (entity wz, vector v)
vector WarpZone_TransformOrigin (entity wz, vector v)
vector WarpZone_TransformVAngles (entity wz, vector ang)
vector WarpZone_TransformVelocity (entity wz, vector v)
vector WarpZone_UnTransformAngles (entity wz, vector v)
vector WarpZone_UnTransformOrigin (entity wz, vector v)
vector WarpZone_UnTransformVAngles (entity wz, vector ang)
vector WarpZone_UnTransformVelocity (entity wz, vector v)
bool WarpZoneLib_BadEntity (entity e)
float WarpZoneLib_BoxTouchesBrush (vector mi, vector ma, entity e, entity ig)
float WarpZoneLib_BoxTouchesBrush_Recurse ()
bool WarpZoneLib_ExactTrigger_Touch (entity this, entity toucher)
bool WarpZoneLib_MoveOutOfSolid (entity e)
void WarpZoneLib_MoveOutOfSolid_Expand (entity e, vector by)
vector WarpZoneLib_NearestPointOnBox (vector mi, vector ma, vector org)
Variables
float autocvar_cl_warpzone_usetrace = 1
entity enemy
float WarpZone_findradius_hit
entity WarpZone_findradius_next
entity WarpZone_refsys
vector WarpZone_refsys_incremental_shift
vector WarpZone_refsys_incremental_transform
float WarpZone_TrailParticles_trace_callback_eff
entity WarpZone_TrailParticles_trace_callback_own
entity WarpZoneLib_BoxTouchesBrush_ent
entity WarpZoneLib_BoxTouchesBrush_ignore
vector WarpZoneLib_BoxTouchesBrush_maxs
vector WarpZoneLib_BoxTouchesBrush_mins
Function Documentation
void WarpZone_Accumulator_Add (entity acc, entity wz)
Definition at line 23 of file common.qc.
References WarpZone_Accumulator_AddTransform().
Referenced by WarpZone_RefSys_AddIncrementally(), and WarpZone_Trace_AddTransform().
 {
     WarpZone_Accumulator_AddTransform(acc, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_Accumulator_AddInverse (entity acc, entity wz)
Definition at line 35 of file common.qc.
References WarpZone_Accumulator_AddInverseTransform().
 {
     WarpZone_Accumulator_AddInverseTransform(acc, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_Accumulator_AddInverseTransform (entity acc, vector t, vector s)
Definition at line 27 of file common.qc.
References AnglesTransform_Invert(), AnglesTransform_PrePostShift_GetPostShift(), vector(), and WarpZone_Accumulator_AddTransform().
Referenced by WarpZone_Accumulator_AddInverse(), WarpZone_RefSys_AddIncrementally(), and WarpZone_RefSys_AddInverseTransform().
 {
     vector tt, ss;
     tt = AnglesTransform_Invert(t);
     ss = AnglesTransform_PrePostShift_GetPostShift(s, tt, '0 0 0');
     WarpZone_Accumulator_AddTransform(acc, tt, ss);
     // yes, this probably can be done simpler... but this way is "obvious" :)
 }
void WarpZone_Accumulator_AddTransform (entity acc, vector t, vector s)
Definition at line 15 of file common.qc.
References AnglesTransform_Multiply(), AnglesTransform_Multiply_GetPostShift(), and vector().
Referenced by WarpZone_Accumulator_Add(), WarpZone_Accumulator_AddInverseTransform(), and WarpZone_RefSys_AddTransform().
 {
     vector tr, st;
     tr = AnglesTransform_Multiply(t, acc.warpzone_transform);
     st = AnglesTransform_Multiply_GetPostShift(t, s, acc.warpzone_transform, acc.warpzone_shift);
     acc.warpzone_transform = tr;
     acc.warpzone_shift = st;
 }
void WarpZone_Accumulator_Clear (entity acc)
Definition at line 10 of file common.qc.
Referenced by WarpZone_RefSys_CheckCreate(), and WarpZone_Trace_InitTransform().
 {
     acc.warpzone_transform = '0 0 0';
     acc.warpzone_shift = '0 0 0';
 }
vector WarpZone_Camera_camera_transform (entity this, vector org, vector ang)
Definition at line 79 of file common.qc.
References maxs, mins, origin, trace_endpos, vdist, warpzone_angles, warpzone_fadeend, warpzone_fadestart, and warpzone_origin.
Referenced by WarpZone_Camera_SetUp().
 {
     // a fixed camera view
     if(this.warpzone_fadestart)
         if(vdist(org - this.origin - 0.5 * (this.mins + this.maxs), >, this.warpzone_fadeend + 400))
             return org;
             // don't transform if zone faded out (plus 400qu safety margin for typical speeds and latencies)
             // unneeded on client, on server this helps a lot
     trace_endpos = this.warpzone_origin;
     makevectors(this.warpzone_angles);
     return this.warpzone_origin;
 }
void WarpZone_Camera_SetUp (entity e, vector my_org, vector my_ang)
Definition at line 92 of file common.qc.
References setcamera_transform, and WarpZone_Camera_camera_transform().
Referenced by NET_HANDLE().
 {
     e.warpzone_origin = my_org;
     e.warpzone_angles = my_ang;
     setcamera_transform(e, WarpZone_Camera_camera_transform);
 }
vector WarpZone_camera_transform (entity this, vector org, vector ang)
Definition at line 41 of file common.qc.
References autocvar_cl_warpzone_usetrace, maxs, mins, MOVE_NOMONSTERS, NULL, origin, trace_endpos, v_forward, v_right, v_up, vdist, vector(), warpzone_fadeend, warpzone_fadestart, warpzone_targetorigin, WarpZone_TransformOrigin(), and WarpZone_TransformVelocity().
Referenced by WarpZone_SetUp().
 {
     vector vf, vr, vu;
     if(this.warpzone_fadestart)
         if(vdist(org - this.origin - 0.5 * (this.mins + this.maxs), >, this.warpzone_fadeend + 400))
             return org;
             // don't transform if zone faded out (plus 400qu safety margin for typical speeds and latencies)
             // unneeded on client, on server this helps a lot
     vf = v_forward;
     vr = v_right;
     vu = v_up;
     org = WarpZone_TransformOrigin(this, org);
     vf = WarpZone_TransformVelocity(this, vf);
     vr = WarpZone_TransformVelocity(this, vr);
     vu = WarpZone_TransformVelocity(this, vu);
     if(autocvar_cl_warpzone_usetrace)
         traceline(this.warpzone_targetorigin, org, MOVE_NOMONSTERS, NULL);
     else
         trace_endpos = this.warpzone_targetorigin;
     v_forward = vf;
     v_right = vr;
     v_up = vu;
     return org;
 }
entity WarpZone_Find (vector mi, vector ma)
Definition at line 154 of file common.qc.
References g_warpzones, IL_EACH, NULL, warpzone_warpzones_exist, and WarpZoneLib_BoxTouchesBrush().
Referenced by WarpZone_FixNearClip(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     // if we are near any warpzone planes - MOVE AWAY (work around nearclip)
     if(!warpzone_warpzones_exist)
         return NULL;
     IL_EACH(g_warpzones, WarpZoneLib_BoxTouchesBrush(mi, ma, it, NULL),
     {
         return it;
     });
     return NULL;
 }
entity WarpZone_FindRadius (vector org, float rad, bool needlineofsight)
Definition at line 657 of file common.qc.
References chain, entity(), findchainfloat(), FOREACH_LIST, WarpZone_findradius_hit, and WarpZone_FindRadius_Recurse().
Referenced by MUTATOR_HOOKFUNCTION(), PlayerUseKey(), and RadiusDamageForSource().
 {
     // FIXME: why can't we do this? (sometimes finds nothing, breaking explosions)
     // if (!warpzone_warpzones_exist && !needlineofsight) return findradius(org, rad);
     WarpZone_FindRadius_Recurse(org, rad, org, '0 0 0', '0 0 0', needlineofsight);
     entity list_first = findchainfloat(WarpZone_findradius_hit, 1);
     FOREACH_LIST(list, chain, true, it.WarpZone_findradius_hit = 0);
     return list_first;
 }
void WarpZone_FindRadius_Recurse (vector org, float rad, vector org0, vector transform, vector shift, bool needlineofsight)
Parameters
org blast origin of current search
org0 original blast origin
transform how to untransform (victim to blast system)
Definition at line 591 of file common.qc.
References AnglesTransform_Multiply(), AnglesTransform_Multiply_GetPostShift(), bound(), entity(), MOVE_NOMONSTERS, NULL, p, trace_endpos, trace_fraction, vector(), vlen(), vlen2, WarpZone_TransformOrigin(), WarpZoneLib_BadEntity(), and WarpZoneLib_NearestPointOnBox().
Referenced by WarpZone_FindRadius().
 {
     if (rad <= 0) return;
     entity wz = NULL;
     FOREACH_ENTITY_RADIUS(org, rad, !WarpZoneLib_BadEntity(it), {
         vector p = WarpZoneLib_NearestPointOnBox(it.origin + it.mins, it.origin + it.maxs, org0);
         if (needlineofsight)
         {
             traceline(org, p, MOVE_NOMONSTERS, it);
             if (trace_fraction < 1) continue;
         }
         if (!it.WarpZone_findradius_hit || vlen2(it.WarpZone_findradius_dist) > vlen2(org0 - p))
         {
             it.WarpZone_findradius_nearest = p;
             it.WarpZone_findradius_dist = org0 - p;
             it.WarpZone_findradius_findorigin = org;
             it.WarpZone_findradius_findradius = rad;
             if (it.classname == "warpzone_refsys")
             {
                 // ignore, especially: do not overwrite the refsys parameters
             }
             else if (it.classname == "trigger_warpzone")
             {
                 it.WarpZone_findradius_next = wz;
                 wz = it;
                 it.WarpZone_findradius_hit = 1;
                 it.enemy.WarpZone_findradius_dist = '0 0 0'; // we don't want to go through this zone ever again
                 it.enemy.WarpZone_findradius_hit = 1;
             }
             else
             {
                 it.warpzone_transform = transform;
                 it.warpzone_shift = shift;
                 it.WarpZone_findradius_hit = 1;
             }
         }
     });
     for(entity e = wz; e; e = e.WarpZone_findradius_next)
     {
         if (WarpZoneLib_BadEntity(e)) continue;
         vector org0_new = WarpZone_TransformOrigin(e, org);
         traceline(e.warpzone_targetorigin, org0_new, MOVE_NOMONSTERS, e);
         vector org_new = trace_endpos;
         vector transform_new = AnglesTransform_Multiply(e.warpzone_transform, transform);
         vector shift_new = AnglesTransform_Multiply_GetPostShift(e.warpzone_transform, e.warpzone_shift, transform, shift);
         WarpZone_FindRadius_Recurse(
             org_new,
             bound(0, rad - vlen(org_new - org0_new), rad - 8),
             org0_new,
             transform_new, shift_new,
             needlineofsight);
         e.WarpZone_findradius_hit = 0;
         e.enemy.WarpZone_findradius_hit = 0;
     }
 }
void WarpZone_MakeAllOther ()
Definition at line 176 of file common.qc.
References g_warpzones, IL_EACH, SOLID_TRIGGER, and warpzone_warpzones_exist.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     if(!warpzone_warpzones_exist)
         return;
     IL_EACH(g_warpzones, true,
     {
         it.solid = SOLID_TRIGGER;
     });
 }
void WarpZone_MakeAllSolid ()
Definition at line 166 of file common.qc.
References g_warpzones, IL_EACH, SOLID_BSP, and warpzone_warpzones_exist.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     if(!warpzone_warpzones_exist)
         return;
     IL_EACH(g_warpzones, true,
     {
         it.solid = SOLID_BSP;
     });
 }
float WarpZone_PlaneDist (entity wz, vector v)
Definition at line 489 of file common.qc.
Referenced by WarpZone_FixNearClip(), and WarpZone_Touch().
 {
     return (v - wz.warpzone_origin) * wz.warpzone_forward;
 }
void WarpZone_RefSys_Add (entity me, entity wz)
Definition at line 702 of file common.qc.
References WarpZone_RefSys_AddTransform().
Referenced by WarpZone_Teleport().
 {
     WarpZone_RefSys_AddTransform(me, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_RefSys_AddIncrementally (entity me, entity ref)
Definition at line 720 of file common.qc.
References WarpZone_Accumulator_Add(), and WarpZone_Accumulator_AddInverseTransform().
Referenced by GrapplingHookThink().
 {
     //vector t, s;
     if(me.WarpZone_refsys_incremental_transform == ref.WarpZone_refsys.warpzone_transform)
     if(me.WarpZone_refsys_incremental_shift == ref.WarpZone_refsys.warpzone_shift)
         return;
     WarpZone_Accumulator_AddInverseTransform(me.WarpZone_refsys, me.WarpZone_refsys_incremental_transform, me.WarpZone_refsys_incremental_shift);
     WarpZone_Accumulator_Add(me.WarpZone_refsys, ref.WarpZone_refsys);
     me.WarpZone_refsys_incremental_shift = ref.WarpZone_refsys.warpzone_shift;
     me.WarpZone_refsys_incremental_transform = ref.WarpZone_refsys.warpzone_transform;
 }
void WarpZone_RefSys_AddInverse (entity me, entity wz)
Definition at line 714 of file common.qc.
References WarpZone_RefSys_AddInverseTransform().
Referenced by ctf_Handle_Throw(), and Monster_Enemy_Check().
 {
     WarpZone_RefSys_AddInverseTransform(me, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_RefSys_AddInverseTransform (entity me, vector t, vector s)
Definition at line 706 of file common.qc.
References WarpZone_Accumulator_AddInverseTransform(), and WarpZone_RefSys_CheckCreate().
Referenced by WarpZone_RefSys_AddInverse().
 {
     if(t != '0 0 0' || s != '0 0 0')
     {
         WarpZone_RefSys_CheckCreate(me);
         WarpZone_Accumulator_AddInverseTransform(me.WarpZone_refsys, t, s);
     }
 }
void WarpZone_RefSys_AddTransform (entity me, vector t, vector s)
Definition at line 694 of file common.qc.
References WarpZone_Accumulator_AddTransform(), and WarpZone_RefSys_CheckCreate().
Referenced by WarpZone_RefSys_Add().
 {
     if(t != '0 0 0' || s != '0 0 0')
     {
         WarpZone_RefSys_CheckCreate(me);
         WarpZone_Accumulator_AddTransform(me.WarpZone_refsys, t, s);
     }
 }
void WarpZone_RefSys_BeginAddingIncrementally (entity me, entity ref)
Definition at line 731 of file common.qc.
Referenced by GrapplingHookTouch().
 {
     me.WarpZone_refsys_incremental_shift = ref.WarpZone_refsys.warpzone_shift;
     me.WarpZone_refsys_incremental_transform = ref.WarpZone_refsys.warpzone_transform;
 }
void WarpZone_RefSys_CheckCreate (entity me)
Definition at line 675 of file common.qc.
References setthink, time, WarpZone_Accumulator_Clear(), and WarpZone_RefSys_GC().
Referenced by WarpZone_RefSys_AddInverseTransform(), WarpZone_RefSys_AddTransform(), and WarpZone_RefSys_Copy().
 {
     if(me.WarpZone_refsys.owner != me)
     {
         me.WarpZone_refsys = new(warpzone_refsys);
         me.WarpZone_refsys.owner = me;
         setthink(me.WarpZone_refsys, WarpZone_RefSys_GC);
         me.WarpZone_refsys.nextthink = time + 1;
         WarpZone_Accumulator_Clear(me.WarpZone_refsys);
     }
 }
void WarpZone_RefSys_Clear (entity me)
Definition at line 686 of file common.qc.
References NULL.
Referenced by WarpZone_RefSys_Copy().
 {
     if(me.WarpZone_refsys)
     {
         delete(me.WarpZone_refsys);
         me.WarpZone_refsys = NULL;
     }
 }
void WarpZone_RefSys_Copy (entity me, entity from)
Definition at line 768 of file common.qc.
References WarpZone_RefSys_CheckCreate(), and WarpZone_RefSys_Clear().
Referenced by ctf_Handle_Throw(), Monster_Enemy_Check(), and WarpZone_RefSys_SpawnSameRefSys().
 {
     if(from.WarpZone_refsys)
     {
         WarpZone_RefSys_CheckCreate(me);
         me.WarpZone_refsys.warpzone_shift = from.WarpZone_refsys.warpzone_shift;
         me.WarpZone_refsys.warpzone_transform = from.WarpZone_refsys.warpzone_transform;
     }
     else
         WarpZone_RefSys_Clear(me);
 }
void WarpZone_RefSys_GC (entity this)
Definition at line 668 of file common.qc.
References nextthink, owner, and time.
Referenced by WarpZone_RefSys_CheckCreate().
 {
     // garbage collect unused reference systems
     this.nextthink = time + 1;
     if(this.owner.WarpZone_refsys != this)
         delete(this);
 }
entity WarpZone_RefSys_SpawnSameRefSys (entity me)
Definition at line 779 of file common.qc.
References entity(), spawn(), and WarpZone_RefSys_Copy().
Referenced by FireGrapplingHook().
 {
     entity e;
     e = spawn();
     WarpZone_RefSys_Copy(e, me);
     return e;
 }
vector WarpZone_RefSys_TransformAngles (entity from, entity to, vector ang)
Definition at line 752 of file common.qc.
References WarpZone_TransformAngles(), and WarpZone_UnTransformAngles().
 {
     if(from.WarpZone_refsys)
         ang = WarpZone_UnTransformAngles(from.WarpZone_refsys, ang);
     if(to.WarpZone_refsys)
         ang = WarpZone_TransformAngles(to.WarpZone_refsys, ang);
     return ang;
 }
vector WarpZone_RefSys_TransformOrigin (entity from, entity to, vector org)
Definition at line 736 of file common.qc.
References WarpZone_TransformOrigin(), and WarpZone_UnTransformOrigin().
Referenced by ctf_FlagThink(), ctf_Handle_Throw(), GrapplingHookThink(), Monster_Enemy_Check(), and Monster_Move_Target().
 {
     if(from.WarpZone_refsys)
         org = WarpZone_UnTransformOrigin(from.WarpZone_refsys, org);
     if(to.WarpZone_refsys)
         org = WarpZone_TransformOrigin(to.WarpZone_refsys, org);
     return org;
 }
vector WarpZone_RefSys_TransformVAngles (entity from, entity to, vector ang)
Definition at line 760 of file common.qc.
References WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
 {
     if(from.WarpZone_refsys)
         ang = WarpZone_UnTransformVAngles(from.WarpZone_refsys, ang);
     if(to.WarpZone_refsys)
         ang = WarpZone_TransformVAngles(to.WarpZone_refsys, ang);
     return ang;
 }
vector WarpZone_RefSys_TransformVelocity (entity from, entity to, vector vel)
Definition at line 744 of file common.qc.
References WarpZone_TransformVelocity(), and WarpZone_UnTransformVelocity().
Referenced by GrapplingHookThink().
 {
     if(from.WarpZone_refsys)
         vel = WarpZone_UnTransformVelocity(from.WarpZone_refsys, vel);
     if(to.WarpZone_refsys)
         vel = WarpZone_TransformVelocity(to.WarpZone_refsys, vel);
     return vel;
 }
void WarpZone_SetUp (entity e, vector my_org, vector my_ang, vector other_org, vector other_ang)
Definition at line 66 of file common.qc.
References AnglesTransform_PrePostShift_GetPostShift(), AnglesTransform_RightDivide(), AnglesTransform_TurnDirectionFR(), fixedmakevectors, setcamera_transform, v_forward, and WarpZone_camera_transform().
Referenced by NET_HANDLE().
 {
     e.warpzone_transform = AnglesTransform_RightDivide(other_ang, AnglesTransform_TurnDirectionFR(my_ang));
     e.warpzone_shift = AnglesTransform_PrePostShift_GetPostShift(my_org, e.warpzone_transform, other_org);
     e.warpzone_origin = my_org;
     e.warpzone_targetorigin = other_org;
     e.warpzone_angles = my_ang;
     e.warpzone_targetangles = other_ang;
     fixedmakevectors(my_ang); e.warpzone_forward = v_forward;
     fixedmakevectors(other_ang); e.warpzone_targetforward = v_forward;
     setcamera_transform(e, WarpZone_camera_transform);
 }
float WarpZone_TargetPlaneDist (entity wz, vector v)
Definition at line 494 of file common.qc.
Referenced by WarpZone_Teleport().
 {
     return (v - wz.warpzone_targetorigin) * wz.warpzone_targetforward;
 }
void WarpZone_Trace_AddTransform (entity wz)
Definition at line 194 of file common.qc.
References WarpZone_Accumulator_Add(), and WarpZone_trace_transform.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     WarpZone_Accumulator_Add(WarpZone_trace_transform, wz);
 }
void WarpZone_Trace_InitTransform ()
Definition at line 186 of file common.qc.
References new_pure, WarpZone_Accumulator_Clear(), and WarpZone_trace_transform.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     if(!WarpZone_trace_transform)
     {
         WarpZone_trace_transform = new_pure(warpzone_trace_transform);
     }
     WarpZone_Accumulator_Clear(WarpZone_trace_transform);
 }
void WarpZone_TraceBox (vector org, vector mi, vector ma, vector end, float nomonsters, entity forent)
Definition at line 333 of file common.qc.
References NULL, WarpZone_trace_callback_t_null, and WarpZone_TraceBox_ThroughZone().
Referenced by CommonCommand_editmob(), CSQC_UpdateView(), tracebox_antilag_force_wz(), and WarpZone_TraceLine().
 {
     WarpZone_TraceBox_ThroughZone(org, mi, ma, end, nomonsters, forent, NULL, WarpZone_trace_callback_t_null);
 }
void WarpZone_TraceBox_ThroughZone (vector org, vector mi, vector ma, vector end, float nomonsters, entity forent, entity zone, WarpZone_trace_callback_t cb)
Definition at line 199 of file common.qc.
References BITCLR_ASSIGN, BITSET_ASSIGN, DPCONTENTS_SOLID, entity(), LABEL, LOG_TRACE(), MOVE_NOMONSTERS, MOVE_NOTHING, MOVE_WORLDONLY, normalize(), NULL, trace_dphitcontents, trace_endpos, trace_ent, trace_fraction, trace_startsolid, v_forward, v_right, v_up, vector(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_Trace_AddTransform(), WarpZone_trace_firstzone, WarpZone_trace_forent, WarpZone_Trace_InitTransform(), WarpZone_trace_lastzone, WarpZone_TransformOrigin(), and warpzone_warpzones_exist.
Referenced by fireBullet(), WarpZone_TraceBox(), and WarpZone_TrailParticles().
 {
     float nomonsters_adjusted;
     float frac, sol, i;
     float contentshack;
     vector o0, e0;
     entity wz;
     vector vf, vr, vu;
     WarpZone_trace_forent = forent;
     WarpZone_trace_firstzone = NULL;
     WarpZone_trace_lastzone = NULL;
     WarpZone_Trace_InitTransform();
     if(!warpzone_warpzones_exist)
     {
         if(nomonsters == MOVE_NOTHING)
         {
             trace_endpos = end;
             trace_fraction = 1;
             if(cb)
                 cb(org, trace_endpos, end);
             return;
         }
         else
         {
             tracebox(org, mi, ma, end, nomonsters, WarpZone_trace_forent);
             if(cb)
                 cb(org, trace_endpos, end);
             return;
         }
     }
     vf = v_forward;
     vr = v_right;
     vu = v_up;
     o0 = org;
     e0 = end;
     switch(nomonsters)
     {
         case MOVE_WORLDONLY:
         case MOVE_NOTHING:
             nomonsters_adjusted = MOVE_NOMONSTERS;
             break;
         default:
             nomonsters_adjusted = nomonsters;
             break;
     }
     if((contentshack = (WarpZone_trace_forent.dphitcontentsmask && !(WarpZone_trace_forent.dphitcontentsmask & DPCONTENTS_SOLID))))
         BITSET_ASSIGN(WarpZone_trace_forent.dphitcontentsmask, DPCONTENTS_SOLID);
     // if starting in warpzone, first transform
     wz = WarpZone_Find(org + mi, org + ma);
     if(wz)
     {
         WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
         {
             // we are in ANOTHER warpzone. This is bad. Make a zero length trace and return.
             sol = 1;
             trace_fraction = 0;
             trace_endpos = org;
             goto fail;
         }
         WarpZone_Trace_AddTransform(wz);
         org = WarpZone_TransformOrigin(wz, org);
         end = WarpZone_TransformOrigin(wz, end);
     }
     WarpZone_MakeAllSolid();
     sol = -1;
     frac = 0;
     i = 16;
     for (;;)
     {
         if(--i < 1)
         {
             LOG_TRACE("Too many warpzones in sequence, aborting trace.");
             trace_ent = NULL;
             break;
         }
         tracebox(org, mi, ma, end, nomonsters_adjusted, WarpZone_trace_forent);
         if(cb)
             cb(org, trace_endpos, end);
         if(sol < 0)
             sol = trace_startsolid;
         frac = trace_fraction = frac + (1 - frac) * trace_fraction;
         if(trace_fraction >= 1)
             break;
         if(trace_ent.classname != "trigger_warpzone")
         {
             if((nomonsters == MOVE_NOTHING) || ((nomonsters == MOVE_WORLDONLY) && trace_ent) || (contentshack && (trace_dphitcontents & WarpZone_trace_forent.dphitcontentsmask) == DPCONTENTS_SOLID))
             {
                 // continue the trace, ignoring this hit (we only care for warpzones)
                 org = trace_endpos + normalize(end - org);
                 continue;
                 // we cannot do an inverted trace here, as we do care for further warpzones inside that "solid" to be found
                 // otherwise, players could block entrances that way
             }
             break;
         }
         /*if(trace_ent == wz)
         {
             // FIXME can this check be removed? Do we really need it?
             LOG_TRACE("I transformed into the same zone again, wtf, aborting the trace");
             trace_ent = NULL;
             break;
         }*/
         wz = trace_ent;
         if(!WarpZone_trace_firstzone)
             WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
             break;
         WarpZone_Trace_AddTransform(wz);
         // we hit a warpzone... so, let's perform the trace after the warp again
         org = WarpZone_TransformOrigin(wz, trace_endpos);
         end = WarpZone_TransformOrigin(wz, end);
         // we got warped, so let's step back a bit
         tracebox(org, mi, ma, org + normalize(org - end) * 32, nomonsters_adjusted, WarpZone_trace_forent);
         org = trace_endpos;
     }
     WarpZone_MakeAllOther();
 LABEL(fail)
     if(contentshack)
         BITCLR_ASSIGN(WarpZone_trace_forent.dphitcontentsmask, DPCONTENTS_SOLID);
     trace_startsolid = sol;
     v_forward = vf;
     v_right = vr;
     v_up = vu;
 }
void WarpZone_TraceLine (vector org, vector end, float nomonsters, entity forent)
Definition at line 338 of file common.qc.
References WarpZone_TraceBox().
Referenced by CommonCommand_editmob(), CSQC_UpdateView(), ctf_CalculatePassVelocity(), ctf_FlagThink(), Monster_CalculateVelocity(), Monster_Move_Target(), RadiusDamageForSource(), sandbox_ObjectSpawn(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     WarpZone_TraceBox(org, '0 0 0', '0 0 0', end, nomonsters, forent);
 }
void WarpZone_TraceToss (entity e, entity forent)
Definition at line 452 of file common.qc.
References NULL, WarpZone_trace_callback_t_null, and WarpZone_TraceToss_ThroughZone().
 {
     WarpZone_TraceToss_ThroughZone(e, forent, NULL, WarpZone_trace_callback_t_null);
 }
void WarpZone_TraceToss_ThroughZone (entity e, entity forent, entity zone, WarpZone_trace_callback_t cb)
Definition at line 343 of file common.qc.
References cvar(), entity(), LABEL, LOG_TRACE(), NULL, setorigin(), trace_endpos, trace_ent, trace_fraction, v_forward, v_right, v_up, vector(), vlen(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_Trace_AddTransform(), WarpZone_trace_firstzone, WarpZone_trace_forent, WarpZone_Trace_InitTransform(), WarpZone_trace_lastzone, WarpZone_tracetoss_time, WarpZone_tracetoss_velocity, WarpZone_TransformOrigin(), WarpZone_TransformVelocity(), and warpzone_warpzones_exist.
Referenced by WarpZone_TraceToss().
 {
     float g, dt, i;
     vector vf, vr, vu, v0, o0;
     entity wz;
     o0 = e.origin;
     v0 = e.velocity;
     g = cvar("sv_gravity") * e.gravity;
     WarpZone_trace_forent = forent;
     WarpZone_trace_firstzone = NULL;
     WarpZone_trace_lastzone = NULL;
     WarpZone_Trace_InitTransform();
     WarpZone_tracetoss_time = 0;
     if(!warpzone_warpzones_exist)
     {
         tracetoss(e, WarpZone_trace_forent);
         if(cb)
             cb(e.origin, trace_endpos, trace_endpos);
         dt = vlen(e.origin - o0) / vlen(e.velocity);
         WarpZone_tracetoss_time += dt;
         e.velocity_z -= dt * g;
         WarpZone_tracetoss_velocity = e.velocity;
         e.velocity = v0;
         return;
     }
     vf = v_forward;
     vr = v_right;
     vu = v_up;
     // if starting in warpzone, first transform
     wz = WarpZone_Find(e.origin + e.mins, e.origin + e.maxs);
     if(wz)
     {
         WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
         {
             // we are in ANOTHER warpzone. This is bad. Make a zero length trace and return.
             WarpZone_tracetoss_time = 0;
             trace_endpos = o0;
             goto fail;
         }
         WarpZone_Trace_AddTransform(wz);
         vector org = WarpZone_TransformOrigin(wz, e.origin);
         setorigin(e, org);
         e.velocity = WarpZone_TransformVelocity(wz, e.velocity);
     }
     WarpZone_MakeAllSolid();
     i = 16;
     for (;;)
     {
         if(--i < 1)
         {
             LOG_TRACE("Too many warpzones in sequence, aborting trace.");
             trace_ent = NULL;
             break;
         }
         tracetoss(e, WarpZone_trace_forent);
         if(cb)
             cb(e.origin, trace_endpos, trace_endpos);
         dt = vlen(trace_endpos - e.origin) / vlen(e.velocity);
         WarpZone_tracetoss_time += dt;
         e.origin = trace_endpos;
         e.velocity_z -= dt * g;
         if(trace_fraction >= 1)
             break;
         if(trace_ent.classname != "trigger_warpzone")
             break;
         if(trace_ent == wz)
         {
             // FIXME can this check be removed? Do we really need it?
             LOG_TRACE("I transformed into the same zone again, wtf, aborting the trace");
             trace_ent = NULL;
             break;
         }
         wz = trace_ent;
         if(!WarpZone_trace_firstzone)
             WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
             break;
         WarpZone_Trace_AddTransform(wz);
         // we hit a warpzone... so, let's perform the trace after the warp again
         e.origin = WarpZone_TransformOrigin(wz, e.origin);
         e.velocity = WarpZone_TransformVelocity(wz, e.velocity);
         // we got warped, so let's step back a bit
         e.velocity = -e.velocity;
         tracetoss(e, WarpZone_trace_forent);
         dt = vlen(trace_endpos - e.origin) / vlen(e.velocity);
         WarpZone_tracetoss_time -= dt;
         e.origin = trace_endpos;
         e.velocity = -e.velocity;
     }
     WarpZone_MakeAllOther();
 LABEL(fail)
     WarpZone_tracetoss_velocity = e.velocity;
     v_forward = vf;
     v_right = vr;
     v_up = vu;
     // restore old entity data (caller just uses trace_endpos, WarpZone_tracetoss_velocity and the transform)
     e.velocity = v0;
     e.origin = o0;
 }
void WarpZone_TrailParticles (entity own, float eff, vector org, vector end)
Definition at line 464 of file common.qc.
References MOVE_NOMONSTERS, NULL, WarpZone_TraceBox_ThroughZone(), WarpZone_TrailParticles_trace_callback(), WarpZone_TrailParticles_trace_callback_eff, and WarpZone_TrailParticles_trace_callback_own.
Referenced by ctf_Handle_Throw().
 {
     WarpZone_TrailParticles_trace_callback_own = own;
     WarpZone_TrailParticles_trace_callback_eff = eff;
     WarpZone_TraceBox_ThroughZone(org, '0 0 0', '0 0 0', end, MOVE_NOMONSTERS, NULL, NULL, WarpZone_TrailParticles_trace_callback);
 }
void WarpZone_TrailParticles_trace_callback (vector from, vector endpos, vector to)
Definition at line 459 of file common.qc.
References WarpZone_TrailParticles_trace_callback_eff, and WarpZone_TrailParticles_trace_callback_own.
Referenced by WarpZone_TrailParticles().
 {
     __trailparticles(WarpZone_TrailParticles_trace_callback_own, WarpZone_TrailParticles_trace_callback_eff, from, endpos);
 }
vector WarpZone_TransformAngles (entity wz, vector v)
Definition at line 509 of file common.qc.
References AnglesTransform_ApplyToAngles().
Referenced by WarpZone_RefSys_TransformAngles(), and WarpZone_Teleport().
 {
     return AnglesTransform_ApplyToAngles(wz.warpzone_transform, v);
 }
vector WarpZone_TransformOrigin (entity wz, vector v)
Definition at line 499 of file common.qc.
References AnglesTransform_Apply().
Referenced by fireBullet(), RadiusDamageForSource(), WarpZone_camera_transform(), WarpZone_FindRadius_Recurse(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_RefSys_TransformOrigin(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     return wz.warpzone_shift + AnglesTransform_Apply(wz.warpzone_transform, v);
 }
vector WarpZone_TransformVAngles (entity wz, vector ang)
Definition at line 514 of file common.qc.
References AnglesTransform_ApplyToVAngles(), AnglesTransform_CancelRoll(), and AnglesTransform_Normalize().
Referenced by CSQC_UpdateView(), NET_HANDLE(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_RefSys_TransformVAngles(), and WarpZone_Teleport().
 {
 #ifdef KEEP_ROLL
     float roll;
     roll = ang.z;
     ang.z = 0;
 #endif
     ang = AnglesTransform_ApplyToVAngles(wz.warpzone_transform, ang);
 #ifdef KEEP_ROLL
     ang = AnglesTransform_Normalize(ang, true);
     ang = AnglesTransform_CancelRoll(ang);
     ang.z = roll;
 #else
     ang = AnglesTransform_Normalize(ang, false);
 #endif
     return ang;
 }
vector WarpZone_TransformVelocity (entity wz, vector v)
Definition at line 504 of file common.qc.
References AnglesTransform_Apply().
Referenced by fireBullet(), FireRailgunBullet(), WarpZone_camera_transform(), WarpZone_RefSys_TransformVelocity(), WarpZone_Teleport(), and WarpZone_TraceToss_ThroughZone().
 {
     return AnglesTransform_Apply(wz.warpzone_transform, v);
 }
vector WarpZone_UnTransformAngles (entity wz, vector v)
Definition at line 545 of file common.qc.
References AnglesTransform_ApplyToAngles(), and AnglesTransform_Invert().
Referenced by WarpZone_RefSys_TransformAngles().
 {
     return AnglesTransform_ApplyToAngles(AnglesTransform_Invert(wz.warpzone_transform), v);
 }
vector WarpZone_UnTransformOrigin (entity wz, vector v)
Definition at line 535 of file common.qc.
References AnglesTransform_Apply(), and AnglesTransform_Invert().
Referenced by FireRailgunBullet(), MUTATOR_HOOKFUNCTION(), RadiusDamageForSource(), W_SetupShot_Dir_ProjectileSize_Range(), and WarpZone_RefSys_TransformOrigin().
 {
     return AnglesTransform_Apply(AnglesTransform_Invert(wz.warpzone_transform), v - wz.warpzone_shift);
 }
vector WarpZone_UnTransformVAngles (entity wz, vector ang)
Definition at line 550 of file common.qc.
References AnglesTransform_ApplyToVAngles(), AnglesTransform_CancelRoll(), AnglesTransform_Invert(), and AnglesTransform_Normalize().
Referenced by WarpZone_RefSys_TransformVAngles().
 {
     float roll;
     roll = ang.z;
     ang.z = 0;
     ang = AnglesTransform_ApplyToVAngles(AnglesTransform_Invert(wz.warpzone_transform), ang);
     ang = AnglesTransform_Normalize(ang, true);
     ang = AnglesTransform_CancelRoll(ang);
     ang.z = roll;
     return ang;
 }
vector WarpZone_UnTransformVelocity (entity wz, vector v)
Definition at line 540 of file common.qc.
References AnglesTransform_Apply(), and AnglesTransform_Invert().
Referenced by WarpZone_RefSys_TransformVelocity().
 {
     return AnglesTransform_Apply(AnglesTransform_Invert(wz.warpzone_transform), v);
 }
bool WarpZoneLib_BadEntity (entity e)
Definition at line 574 of file common.qc.
References is_pure, and startsWith.
Referenced by WarpZone_FindRadius_Recurse().
 {
     if (is_pure(e)) return true;
     string s = e.classname;
     //if (s == "net_linked") return true; // actually some real entities are linked without classname, fail
     if (s == "") return true;
     if (startsWith(s, "target_")) return true;
     if (startsWith(s, "info_")) return true;
     return false;
 }
float WarpZoneLib_BoxTouchesBrush (vector mi, vector ma, entity e, entity ig)
Definition at line 135 of file common.qc.
References SOLID_BSP, WarpZoneLib_BoxTouchesBrush_ent, WarpZoneLib_BoxTouchesBrush_ignore, WarpZoneLib_BoxTouchesBrush_maxs, WarpZoneLib_BoxTouchesBrush_mins, and WarpZoneLib_BoxTouchesBrush_Recurse().
Referenced by havocbot_moveto(), Teleport_Find(), WarpZone_Find(), and WarpZoneLib_ExactTrigger_Touch().
 {
     float f, s;
     if(!e.modelindex || e.warpzone_isboxy)
         return 1;
     s = e.solid;
     e.solid = SOLID_BSP;
     WarpZoneLib_BoxTouchesBrush_mins = mi;
     WarpZoneLib_BoxTouchesBrush_maxs = ma;
     WarpZoneLib_BoxTouchesBrush_ent = e;
     WarpZoneLib_BoxTouchesBrush_ignore = ig;
     f = WarpZoneLib_BoxTouchesBrush_Recurse();
     e.solid = s;
     return f;
 }
float WarpZoneLib_BoxTouchesBrush_Recurse ()
Definition at line 105 of file common.qc.
References entity(), LOG_TRACE(), MOVE_NOMONSTERS, SOLID_NOT, trace_ent, trace_networkentity, WarpZoneLib_BoxTouchesBrush_ent, WarpZoneLib_BoxTouchesBrush_ignore, WarpZoneLib_BoxTouchesBrush_maxs, and WarpZoneLib_BoxTouchesBrush_mins.
Referenced by WarpZoneLib_BoxTouchesBrush().
 {
     float s;
     entity se;
     float f;
     tracebox('0 0 0', WarpZoneLib_BoxTouchesBrush_mins, WarpZoneLib_BoxTouchesBrush_maxs, '0 0 0', MOVE_NOMONSTERS, WarpZoneLib_BoxTouchesBrush_ignore);
 #ifdef CSQC
     if (trace_networkentity)
     {
         LOG_TRACE("hit a network ent, cannot continue WarpZoneLib_BoxTouchesBrush");
         // we cannot continue, as a player blocks us...
         // so, abort
         return 0;
     }
 #endif
     if (!trace_ent)
         return 0;
     if (trace_ent == WarpZoneLib_BoxTouchesBrush_ent)
         return 1;
     se = trace_ent;
     s = se.solid;
     se.solid = SOLID_NOT;
     f = WarpZoneLib_BoxTouchesBrush_Recurse();
     se.solid = s;
     return f;
 }
bool WarpZoneLib_ExactTrigger_Touch (entity this, entity toucher)
Definition at line 787 of file common.qc.
References WarpZoneLib_BoxTouchesBrush().
Referenced by WarpZone_Touch().
 {
     return !WarpZoneLib_BoxTouchesBrush(toucher.absmin, toucher.absmax, this, toucher);
 }
bool WarpZoneLib_MoveOutOfSolid (entity e)
Definition at line 807 of file common.qc.
References eX, eY, eZ, MOVE_WORLDONLY, setorigin(), trace_startsolid, vector(), and WarpZoneLib_MoveOutOfSolid_Expand().
Referenced by WarpZone_Teleport().
 {
     vector o = e.origin;
     traceline(o, o, MOVE_WORLDONLY, e);
     if (trace_startsolid)
         return false;
     tracebox(o, e.mins, e.maxs, o, MOVE_WORLDONLY, e);
     if (!trace_startsolid)
         return true;
     vector m0 = e.mins;
     vector m1 = e.maxs;
     e.mins = '0 0 0';
     e.maxs = '0 0 0';
     WarpZoneLib_MoveOutOfSolid_Expand(e, eX * m0.x); e.mins_x = m0.x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eX * m1.x); e.maxs_x = m1.x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eY * m0.y); e.mins_y = m0.y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eY * m1.y); e.maxs_y = m1.y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eZ * m0.z); e.mins_z = m0.z;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eZ * m1.z); e.maxs_z = m1.z;
     setorigin(e, e.origin);
     tracebox(e.origin, e.mins, e.maxs, e.origin, MOVE_WORLDONLY, e);
     if (trace_startsolid)
     {
         setorigin(e, o);
         return false;
     }
     return true;
 }
void WarpZoneLib_MoveOutOfSolid_Expand (entity e, vector by)
Definition at line 793 of file common.qc.
References MOVE_WORLDONLY, setorigin(), trace_fraction, and trace_startsolid.
Referenced by WarpZoneLib_MoveOutOfSolid().
 {
     float eps = 0.0625;
     tracebox(e.origin, e.mins - '1 1 1' * eps, e.maxs + '1 1 1' * eps, e.origin + by, MOVE_WORLDONLY, e);
     if (trace_startsolid)
         return;
     if (trace_fraction < 1)
     {
         // hit something
         // adjust origin in the other direction...
         setorigin(e, e.origin - by * (1 - trace_fraction));
     }
 }
vector WarpZoneLib_NearestPointOnBox (vector mi, vector ma, vector org)
Definition at line 565 of file common.qc.
References bound(), and vector().
Referenced by WarpZone_FindRadius_Recurse().
 {
     vector nearest;
     nearest.x = bound(mi.x, org.x, ma.x);
     nearest.y = bound(mi.y, org.y, ma.y);
     nearest.z = bound(mi.z, org.z, ma.z);
     return nearest;
 }
Variable Documentation
float autocvar_cl_warpzone_usetrace = 1
Definition at line 40 of file common.qc.
Referenced by WarpZone_camera_transform().
entity enemy
Definition at line 99 of file common.qc.
float WarpZone_findradius_hit
Definition at line 589 of file common.qc.
Referenced by WarpZone_FindRadius().
entity WarpZone_findradius_next
Definition at line 590 of file common.qc.
entity WarpZone_refsys
Definition at line 667 of file common.qc.
vector WarpZone_refsys_incremental_shift
Definition at line 718 of file common.qc.
vector WarpZone_refsys_incremental_transform
Definition at line 719 of file common.qc.
float WarpZone_TrailParticles_trace_callback_eff
Definition at line 458 of file common.qc.
Referenced by WarpZone_TrailParticles(), and WarpZone_TrailParticles_trace_callback().
entity WarpZone_TrailParticles_trace_callback_own
Definition at line 457 of file common.qc.
Referenced by WarpZone_TrailParticles(), and WarpZone_TrailParticles_trace_callback().
entity WarpZoneLib_BoxTouchesBrush_ent
Definition at line 103 of file common.qc.
Referenced by WarpZoneLib_BoxTouchesBrush(), and WarpZoneLib_BoxTouchesBrush_Recurse().
entity WarpZoneLib_BoxTouchesBrush_ignore
Definition at line 104 of file common.qc.
Referenced by WarpZoneLib_BoxTouchesBrush(), and WarpZoneLib_BoxTouchesBrush_Recurse().
vector WarpZoneLib_BoxTouchesBrush_maxs
Definition at line 102 of file common.qc.
Referenced by WarpZoneLib_BoxTouchesBrush(), and WarpZoneLib_BoxTouchesBrush_Recurse().
vector WarpZoneLib_BoxTouchesBrush_mins
Definition at line 101 of file common.qc.
Referenced by WarpZoneLib_BoxTouchesBrush(), and WarpZoneLib_BoxTouchesBrush_Recurse().