Xonotic: common/gamemodes/gamemode/nexball/sv_nexball.qh File Reference
sv_nexball.qh File Reference
#include "weapon.qh"
Functions
void DropBall (entity ball, vector org, vector vel)
void nb_Initialize ()
REGISTER_MUTATOR (nb, false)
Variables
float autocvar_g_nexball_basketball_delay_hold
float autocvar_g_nexball_basketball_delay_hold_forteam
float autocvar_g_nexball_basketball_effects_default
float autocvar_g_nexball_basketball_teamsteal
float autocvar_g_nexball_delay_idle
float autocvar_g_nexball_football_boost_forward
float autocvar_g_nexball_football_boost_up
float autocvar_g_nexball_football_physics
float autocvar_g_nexball_meter_period
const vector BALL_ATTACHORG = '3 0 16'
const float BALL_BASKET = 2
const float BALL_EFFECTMASK = 1229
const float BALL_FOOT = 1
const vector BALL_MAXS = '16 16 16'
const vector BALL_MINS = '-16 -16 -16'
float ball_scale
float balls
float g_nexball_meter_period
const float GOAL_FAULT = -1
const float GOAL_OUT = -2
const float GOAL_TOUCHPLAYER = 1
entity nb_dropper
float nb_droptime
float nb_teams
float teamtime
Function Documentation
void DropBall (entity ball, vector org, vector vel)
Definition at line 202 of file sv_nexball.qc.
References autocvar_g_nexball_basketball_effects_default, autocvar_g_nexball_delay_idle, ball_scale, basketball_touch(), EF_NOSHADOW, entity(), GameRules_scoring_vip(), min(), MOVETYPE_BOUNCE, NULL, ResetBall(), set_movetype(), setorigin(), setthink, SPRITERULE_DEFAULT, state, time, UNSET_ONGROUND, and WS_READY.
Referenced by ball_restart(), DropOwner(), GoalTouch(), MUTATOR_HOOKFUNCTION(), nb_DropBall(), nexball_setstatus(), W_Nexball_Attack(), and W_Nexball_Attack2().
 {
     ball.effects |= autocvar_g_nexball_basketball_effects_default;
     ball.effects &= ~EF_NOSHADOW;
     ball.owner.effects &= ~autocvar_g_nexball_basketball_effects_default;
     setattachment(ball, NULL, "");
     setorigin(ball, org);
     set_movetype(ball, MOVETYPE_BOUNCE);
     UNSET_ONGROUND(ball);
     ball.scale = ball_scale;
     ball.velocity = vel;
     ball.nb_droptime = time;
     settouch(ball, basketball_touch);
     setthink(ball, ResetBall);
     ball.nextthink = min(time + autocvar_g_nexball_delay_idle, ball.teamtime);
     if(STAT(NB_METERSTART, ball.owner))
     {
         STAT(NB_METERSTART, ball.owner) = 0;
         .entity weaponentity = ball.weaponentity_fld;
         ball.owner.(weaponentity).state = WS_READY;
     }
     WaypointSprite_Kill(ball.owner.waypointsprite_attachedforcarrier);
     WaypointSprite_Spawn(WP_NbBall, 0, 0, ball, '0 0 64', NULL, ball.team, ball, waypointsprite_attachedforcarrier, false, RADARICON_FLAGCARRIER); // no health bar please
     WaypointSprite_UpdateRule(ball.waypointsprite_attachedforcarrier, 0, SPRITERULE_DEFAULT);
     entity e = ball.owner; ball.owner = NULL;
     e.ballcarried = NULL;
     GameRules_scoring_vip(e, false);
 }
void nb_Initialize ()
Definition at line 943 of file sv_nexball.qc.
References autocvar_g_nexball_goalleadlimit, autocvar_g_nexball_goallimit, autocvar_g_nexball_meter_period, autocvar_g_nexball_radar_showallplayers, g_nexball_meter_period, GameRules_limit_lead(), GameRules_limit_score(), GameRules_teams(), InitializeEntity(), nb_delayedinit(), NULL, and rint().
Referenced by REGISTER_MUTATOR().
 {
     g_nexball_meter_period = autocvar_g_nexball_meter_period;
     if(g_nexball_meter_period <= 0)
         g_nexball_meter_period = 2; // avoid division by zero etc. due to silly users
     g_nexball_meter_period = rint(g_nexball_meter_period * 32) / 32; //Round to 1/32ths to send as a byte multiplied by 32
     // General settings
     /*
     CVTOV(g_nexball_football_boost_forward);   //100
     CVTOV(g_nexball_football_boost_up);     //200
     CVTOV(g_nexball_delay_idle);               //10
     CVTOV(g_nexball_football_physics);       //0
     */
     radar_showenemies = autocvar_g_nexball_radar_showallplayers;
     GameRules_teams(true);
     GameRules_limit_score(autocvar_g_nexball_goallimit);
     GameRules_limit_lead(autocvar_g_nexball_goalleadlimit);
     InitializeEntity(NULL, nb_delayedinit, INITPRIO_GAMETYPE);
 }
REGISTER_MUTATOR (nb , false)
Definition at line 7 of file sv_nexball.qh.
References MUTATOR_ONADD, MUTATOR_ONROLLBACK_OR_REMOVE, MUTATOR_STATIC, nb_Initialize(), and WEP_FLAG_MUTATORBLOCKED.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         nb_Initialize();
         WEP_NEXBALL.spawnflags &= ~WEP_FLAG_MUTATORBLOCKED;
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         WEP_NEXBALL.spawnflags |= WEP_FLAG_MUTATORBLOCKED;
     }
     return 0;
 }
Variable Documentation
float autocvar_g_nexball_basketball_delay_hold
Definition at line 41 of file sv_nexball.qh.
Referenced by GiveBall().
float autocvar_g_nexball_basketball_delay_hold_forteam
Definition at line 42 of file sv_nexball.qh.
Referenced by GiveBall().
float autocvar_g_nexball_basketball_effects_default
Definition at line 43 of file sv_nexball.qh.
Referenced by DropBall(), GiveBall(), and spawnfunc().
float autocvar_g_nexball_basketball_teamsteal
Definition at line 44 of file sv_nexball.qh.
Referenced by W_Nexball_Touch().
float autocvar_g_nexball_delay_idle
Definition at line 40 of file sv_nexball.qh.
Referenced by basketball_touch(), DropBall(), football_touch(), and InitBall().
float autocvar_g_nexball_football_boost_forward
Definition at line 37 of file sv_nexball.qh.
Referenced by football_touch().
float autocvar_g_nexball_football_boost_up
Definition at line 38 of file sv_nexball.qh.
Referenced by football_touch().
float autocvar_g_nexball_football_physics
Definition at line 39 of file sv_nexball.qh.
Referenced by football_touch().
float autocvar_g_nexball_meter_period
Definition at line 45 of file sv_nexball.qh.
Referenced by nb_Initialize().
const vector BALL_ATTACHORG = '3 0 16'
Definition at line 27 of file sv_nexball.qh.
const float BALL_BASKET = 2
Definition at line 29 of file sv_nexball.qh.
Referenced by spawnfunc().
const float BALL_EFFECTMASK = 1229
Definition at line 24 of file sv_nexball.qh.
Referenced by spawnfunc().
const float BALL_FOOT = 1
Definition at line 28 of file sv_nexball.qh.
Referenced by spawnfunc().
const vector BALL_MAXS = '16 16 16'
Definition at line 26 of file sv_nexball.qh.
Referenced by relocate_nexball(), SpawnBall(), and W_Nexball_Attack().
const vector BALL_MINS = '-16 -16 -16'
Definition at line 25 of file sv_nexball.qh.
Referenced by relocate_nexball(), SpawnBall(), and W_Nexball_Attack().
float ball_scale
Definition at line 48 of file sv_nexball.qh.
Referenced by DropBall(), and SpawnBall().
float balls
Definition at line 47 of file sv_nexball.qh.
Referenced by spawnfunc().
float g_nexball_meter_period
Definition at line 56 of file sv_nexball.qh.
Referenced by ClientInit_misc(), nb_Initialize(), and W_Nexball_Attack().
const float GOAL_FAULT = -1
Definition at line 33 of file sv_nexball.qh.
Referenced by GoalTouch(), and spawnfunc().
const float GOAL_OUT = -2
Definition at line 34 of file sv_nexball.qh.
Referenced by GoalTouch(), spawnfunc(), and SpawnGoal().
const float GOAL_TOUCHPLAYER = 1
Definition at line 31 of file sv_nexball.qh.
Referenced by GoalTouch().
entity nb_dropper
Definition at line 51 of file sv_nexball.qh.
Referenced by basketball_touch().
float nb_droptime
Definition at line 52 of file sv_nexball.qh.
Referenced by basketball_touch().
float nb_teams
Definition at line 49 of file sv_nexball.qh.
Referenced by GoalTouch(), nb_delayedinit(), and nb_spawnteams().
float teamtime
Definition at line 54 of file sv_nexball.qh.
Referenced by basketball_touch(), InitBall(), and ResetBall().