Xonotic: XonoticServerList Class Reference
XonoticServerList Class Reference
Public Member Functions
virtual void clickListBoxItem ()
virtual void configureListBox ()
virtual void configureXonoticListBox ()
virtual void configureXonoticServerList ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void doubleClickListBoxItem ()
virtual void draw ()
virtual void drawListBoxItem ()
virtual void focusedItemChangeNotify ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void getFirstFullyVisibleItemAtScrollPos ()
virtual void getItemAtPos ()
virtual void getItemHeight ()
virtual void getItemStart ()
virtual void getLastFullyVisibleItemAtScrollPos ()
virtual void getTotalHeight ()
virtual void hideNotify ()
virtual void isScrolling ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void positionSortButton ()
virtual void refreshServerList ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void scrollToItem ()
virtual void setFocusedItem ()
virtual void setSelected ()
virtual void setSortOrder ()
virtual void showNotify ()
virtual void toggleFavorite ()
virtual void toString ()
virtual void updateControlTopBottom ()
Public Attributes
float allowFocusSound = 1
float alphaBG = SKINALPHA_LISTBOX_BACKGROUND
float categoriesHeight = 1.25
vector color = SKINCOLOR_SCROLLBAR_N
vector color2 = SKINCOLOR_SCROLLBAR_S
vector colorBG = SKINCOLOR_LISTBOX_BACKGROUND
vector colorC = SKINCOLOR_SCROLLBAR_C
vector colorF = SKINCOLOR_SCROLLBAR_F
float columnIconsOrigin = 0
float columnIconsSize = 0
float columnMapOrigin = 0
float columnMapSize = 0
float columnNameOrigin = 0
float columnNameSize = 0
float columnPingOrigin = 0
float columnPingSize = 0
float columnPlayersOrigin = 0
float columnPlayersSize = 0
float columnTypeOrigin = 0
float columnTypeSize = 0
entity connectButton = NULL
float controlBottom = 0
entity controlledTextbox = NULL
float controlTop = 0
float controlWidth = 0
float currentSortField = -1
float currentSortOrder = 0
vector dragScrollPos = '0 0 0'
entity favoriteButton = NULL
float filterShowEmpty = 1
float filterShowFull = 1
string filterString = string_null
float focusable = 1
float focused = 0
int focusedItem = -1
float focusedItemAlpha = 0.3
float fontSize = SKINFONTSIZE_NORMAL
float iconsSizeFactor = 0.85
entity infoButton = NULL
entity ipAddressBox = NULL
float ipAddressBoxFocused = -1
vector itemAbsSize = '0 0 0'
float itemHeight = 0
float lastClickedItem = -1
float lastClickedTime = 0
bool lockedSelectedItem = true
float mouseMoveOffset = -1
bool mouseOverIcons = false
float needScrollToItem = -1
float needsRefresh = 1
float nextRefreshTime = 0
float nItems = 42
vector origin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
vector realFontSize = '0 0 0'
float realUpperMargin = 0
float rowsPerItem = 1
float scrollbarWidth = SKINWIDTH_SCROLLBAR
float scrollPos = 0
float scrollPosTarget = 0
float seenIPv4 = 0
float seenIPv6 = 0
int selectedItem = 0
string selectedServer = string_null
bool selectionDoesntMatter = false
vector size = '0 0 0'
entity sortButton1 = NULL
entity sortButton2 = NULL
entity sortButton3 = NULL
entity sortButton4 = NULL
entity sortButton5 = NULL
string src = SKINGFX_SCROLLBAR
vector tolerance = SKINTOLERANCE_SLIDER
string tooltip = string_null
Detailed Description
Definition at line 4 of file serverlist.qh.
Member Function Documentation
virtual void ListBox::clickListBoxItem () virtual inherited
Reimplemented in XonoticGametypeList, and XonoticMapList.
virtual void ListBox::configureListBox () virtual inherited
virtual void XonoticListBox::configureXonoticListBox () virtual inherited
virtual void XonoticServerList::configureXonoticServerList () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 276 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 290 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void XonoticServerList::doubleClickListBoxItem () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::draw () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::drawListBoxItem () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::focusedItemChangeNotify () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::focusEnter () virtual
Reimplemented from Item.
virtual void ListBox::focusLeave () virtual inherited
Reimplemented from Item.
virtual void ListBox::getFirstFullyVisibleItemAtScrollPos () virtual inherited
virtual void XonoticServerList::getItemAtPos () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::getItemHeight () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::getItemStart () virtual
Reimplemented from ListBox.
virtual void ListBox::getLastFullyVisibleItemAtScrollPos () virtual inherited
virtual void XonoticServerList::getTotalHeight () virtual
Reimplemented from ListBox.
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void ListBox::isScrolling () virtual inherited
virtual void XonoticServerList::keyDown () virtual
Reimplemented from ListBox.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void ListBox::mouseDrag () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticPlayList, and XonoticWeaponsList.
virtual void XonoticServerList::mouseMove () virtual
Reimplemented from ListBox.
virtual void ListBox::mousePress () virtual inherited
Reimplemented from Item.
virtual void ListBox::mouseRelease () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticCvarList.
virtual void XonoticServerList::positionSortButton () virtual
virtual void XonoticServerList::refreshServerList () virtual
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticServerList::resizeNotify () virtual
Reimplemented from XonoticListBox.
virtual void ListBox::scrollToItem () virtual inherited
virtual void ListBox::setFocusedItem () virtual inherited
virtual void XonoticServerList::setSelected () virtual
Reimplemented from ListBox.
virtual void XonoticServerList::setSortOrder () virtual
void Item::showNotify () virtual inherited
Reimplemented in Container, Slider, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, InputBox, XonoticSoundList, XonoticStatsList, XonoticPlayerModelSelector, XonoticTab, XonoticCvarList, XonoticKeyBinder, Button, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
Definition at line 56 of file item.qc.
     {}
void XonoticServerList::toggleFavorite () virtual
Definition at line 223 of file serverlist.qc.
References argv(), argv_end_index, argv_start_index, cvar_set(), cvar_string(), p, REFRESHSERVERLIST_RESORT, strcat(), strlen(), strstrofs, substring(), and tokenize_console.
 {
     bool adding = true;
     string srv_resolved = netaddress_resolve(srv, 26000);
     string p = crypto_getidfp(srv_resolved);
     string s = cvar_string("net_slist_favorites");
     string ret = s;
     for (int i = 0, n = tokenize_console(s); i < n; ++i)
     {
         bool match;
         if (substring(argv(i), 0, 1) != "[" && strlen(argv(i)) == 44 && strstrofs(argv(i), ".", 0) < 0)
         {
             // it's a pubkey hash
             match = (p && p == argv(i));
         }
         else
         {
             // it's an ip
             match = (srv_resolved == netaddress_resolve(argv(i), 26000));
         }
         if (!match) continue;
         // on match: remove
         adding = false;
         string before = (i > 0) ? substring(s, 0, argv_end_index(i - 1)) : "";
         string after = (i < n - 1) ? substring(s, argv_start_index(i + 1), -1) : "";
         s = strcat(before, (before != "" && after != "" ? " " : ""), after);
         ret = s;
         // keep searching
         // TODO: why not break here?
         n = tokenize_console(s);
         --i; // offset the increment that is about to happen
     }
     if (adding)
     {
         ret = strcat(s, (s != "" ? " " : ""), p ? p : srv);
     }
     cvar_set("net_slist_favorites", ret);
     this.refreshServerList(this, REFRESHSERVERLIST_RESORT);
 }
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void ListBox::updateControlTopBottom () virtual inherited
Member Data Documentation
float ListBox::allowFocusSound = 1 inherited
Definition at line 19 of file listbox.qh.
float XonoticListBox::alphaBG = SKINALPHA_LISTBOX_BACKGROUND inherited
Definition at line 17 of file listbox.qh.
float XonoticServerList::categoriesHeight = 1.25
Definition at line 63 of file serverlist.qh.
vector XonoticListBox::color = SKINCOLOR_SCROLLBAR_N inherited
Definition at line 12 of file listbox.qh.
vector XonoticListBox::color2 = SKINCOLOR_SCROLLBAR_S inherited
Definition at line 14 of file listbox.qh.
vector XonoticListBox::colorBG = SKINCOLOR_LISTBOX_BACKGROUND inherited
Definition at line 16 of file listbox.qh.
vector XonoticListBox::colorC = SKINCOLOR_SCROLLBAR_C inherited
Definition at line 15 of file listbox.qh.
vector XonoticListBox::colorF = SKINCOLOR_SCROLLBAR_F inherited
Definition at line 13 of file listbox.qh.
float XonoticServerList::columnIconsOrigin = 0
Definition at line 21 of file serverlist.qh.
float XonoticServerList::columnIconsSize = 0
Definition at line 22 of file serverlist.qh.
float XonoticServerList::columnMapOrigin = 0
Definition at line 27 of file serverlist.qh.
float XonoticServerList::columnMapSize = 0
Definition at line 28 of file serverlist.qh.
float XonoticServerList::columnNameOrigin = 0
Definition at line 25 of file serverlist.qh.
float XonoticServerList::columnNameSize = 0
Definition at line 26 of file serverlist.qh.
float XonoticServerList::columnPingOrigin = 0
Definition at line 23 of file serverlist.qh.
float XonoticServerList::columnPingSize = 0
Definition at line 24 of file serverlist.qh.
float XonoticServerList::columnPlayersOrigin = 0
Definition at line 31 of file serverlist.qh.
float XonoticServerList::columnPlayersSize = 0
Definition at line 32 of file serverlist.qh.
float XonoticServerList::columnTypeOrigin = 0
Definition at line 29 of file serverlist.qh.
float XonoticServerList::columnTypeSize = 0
Definition at line 30 of file serverlist.qh.
entity XonoticServerList::connectButton = NULL
Definition at line 54 of file serverlist.qh.
float ListBox::controlBottom = 0 inherited
Definition at line 34 of file listbox.qh.
entity XonoticServerList::controlledTextbox = NULL
Definition at line 41 of file serverlist.qh.
float ListBox::controlTop = 0 inherited
Definition at line 33 of file listbox.qh.
float ListBox::controlWidth = 0 inherited
Definition at line 35 of file listbox.qh.
float XonoticServerList::currentSortField = -1
Definition at line 57 of file serverlist.qh.
float XonoticServerList::currentSortOrder = 0
Definition at line 56 of file serverlist.qh.
vector ListBox::dragScrollPos = '0 0 0' inherited
Definition at line 36 of file listbox.qh.
entity XonoticServerList::favoriteButton = NULL
Definition at line 43 of file serverlist.qh.
float XonoticServerList::filterShowEmpty = 1
Definition at line 38 of file serverlist.qh.
float XonoticServerList::filterShowFull = 1
Definition at line 39 of file serverlist.qh.
string XonoticServerList::filterString = string_null
Definition at line 40 of file serverlist.qh.
float ListBox::focusable = 1 inherited
Definition at line 14 of file listbox.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
int ListBox::focusedItem = -1 inherited
Definition at line 15 of file listbox.qh.
float ListBox::focusedItemAlpha = 0.3 inherited
Definition at line 16 of file listbox.qh.
float XonoticListBox::fontSize = SKINFONTSIZE_NORMAL inherited
Definition at line 6 of file listbox.qh.
float XonoticServerList::iconsSizeFactor = 0.85
Definition at line 14 of file serverlist.qh.
entity XonoticServerList::infoButton = NULL
Definition at line 55 of file serverlist.qh.
entity XonoticServerList::ipAddressBox = NULL
Definition at line 42 of file serverlist.qh.
float XonoticServerList::ipAddressBoxFocused = -1
Definition at line 59 of file serverlist.qh.
vector ListBox::itemAbsSize = '0 0 0' inherited
Definition at line 48 of file listbox.qh.
float ListBox::itemHeight = 0 inherited
Definition at line 47 of file listbox.qh.
float ListBox::lastClickedItem = -1 inherited
Definition at line 52 of file listbox.qh.
float ListBox::lastClickedTime = 0 inherited
Definition at line 53 of file listbox.qh.
bool XonoticServerList::lockedSelectedItem = true
Definition at line 33 of file serverlist.qh.
float ListBox::mouseMoveOffset = -1 inherited
Definition at line 18 of file listbox.qh.
bool XonoticServerList::mouseOverIcons = false
Definition at line 16 of file serverlist.qh.
float ListBox::needScrollToItem = -1 inherited
Definition at line 26 of file listbox.qh.
float XonoticServerList::needsRefresh = 1
Definition at line 46 of file serverlist.qh.
float XonoticServerList::nextRefreshTime = 0
Definition at line 44 of file serverlist.qh.
float ListBox::nItems = 42 inherited
Definition at line 46 of file listbox.qh.
vector ListBox::origin = '0 0 0' inherited
Definition at line 22 of file listbox.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float ListBox::pressed = 0 inherited
Definition at line 29 of file listbox.qh.
float ListBox::pressOffset = 0 inherited
Definition at line 30 of file listbox.qh.
float ListBox::previousValue = 0 inherited
Definition at line 28 of file listbox.qh.
vector XonoticServerList::realFontSize = '0 0 0'
Definition at line 19 of file serverlist.qh.
float XonoticServerList::realUpperMargin = 0
Definition at line 20 of file serverlist.qh.
float XonoticServerList::rowsPerItem = 1
Definition at line 6 of file serverlist.qh.
float XonoticListBox::scrollbarWidth = SKINWIDTH_SCROLLBAR inherited
Definition at line 7 of file listbox.qh.
float ListBox::scrollPos = 0 inherited
Definition at line 23 of file listbox.qh.
float ListBox::scrollPosTarget = 0 inherited
Definition at line 24 of file listbox.qh.
float XonoticServerList::seenIPv4 = 0
Definition at line 61 of file serverlist.qh.
float XonoticServerList::seenIPv6 = 0
Definition at line 62 of file serverlist.qh.
int ListBox::selectedItem = 0 inherited
Definition at line 20 of file listbox.qh.
string XonoticServerList::selectedServer = string_null
Definition at line 35 of file serverlist.qh.
bool ListBox::selectionDoesntMatter = false inherited
Definition at line 37 of file listbox.qh.
vector ListBox::size = '0 0 0' inherited
Definition at line 21 of file listbox.qh.
entity XonoticServerList::sortButton1 = NULL
Definition at line 49 of file serverlist.qh.
entity XonoticServerList::sortButton2 = NULL
Definition at line 50 of file serverlist.qh.
entity XonoticServerList::sortButton3 = NULL
Definition at line 51 of file serverlist.qh.
entity XonoticServerList::sortButton4 = NULL
Definition at line 52 of file serverlist.qh.
entity XonoticServerList::sortButton5 = NULL
Definition at line 53 of file serverlist.qh.
string XonoticListBox::src = SKINGFX_SCROLLBAR inherited
Definition at line 8 of file listbox.qh.
vector XonoticListBox::tolerance = SKINTOLERANCE_SLIDER inherited
Definition at line 9 of file listbox.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
The documentation for this class was generated from the following files:
menu/xonotic/serverlist.qh
menu/xonotic/serverlist.qc