Xonotic: menu/xonotic/slider_decibels.qc File Reference
slider_decibels.qc File Reference
#include "slider_decibels.qh"
Functions
float fromDecibelOfSquare (float f, float mi)
entity makeXonoticDecibelsSlider (float theValueMin, float theValueMax, float theValueStep, string theCvar)
entity makeXonoticDecibelsSlider_T (float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
TEST (XonoticDecibelsSlider, SoundTest)
float toDecibelOfSquare (float f, float mi)
void XonoticDecibelsSlider_loadCvars (entity me)
void XonoticDecibelsSlider_saveCvars (entity me)
string XonoticDecibelsSlider_valueToText (entity me, float v)
Variables
float autocvar_menu_snd_sliderscale
bool autocvar_test_XonoticDecibelsSlider = false
Function Documentation
float fromDecibelOfSquare (float f, float mi)
Definition at line 17 of file slider_decibels.qc.
References exp(), and log().
Referenced by TEST(), XonoticDecibelsSlider_loadCvars(), XonoticDecibelsSlider_saveCvars(), and XonoticDecibelsSlider_valueToText().
 {
     float A = log(10) / 20; // note: about 0.115; inverse: about 8.686
     if(mi != 0)
     {
         // linear scale part
         float t = 1 / A + mi;
         float u = exp(1 + A * mi);
         if(f <= t)
             return u * ((f - mi) / (t - mi));
     }
     return exp(A * f);
 }
entity makeXonoticDecibelsSlider (float theValueMin, float theValueMax, float theValueStep, string theCvar)
Definition at line 38 of file slider_decibels.qc.
References makeXonoticDecibelsSlider_T(), and string_null.
 {
     return makeXonoticDecibelsSlider_T(theValueMin, theValueMax, theValueStep, theCvar, string_null);
 }
entity makeXonoticDecibelsSlider_T (float theValueMin, float theValueMax, float theValueStep, string theCvar, string theTooltip)
Definition at line 31 of file slider_decibels.qc.
References entity(), and NEW.
Referenced by makeXonoticDecibelsSlider(), and XonoticAudioSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticDecibelsSlider);
     me.configureXonoticSlider(me, theValueMin, theValueMax, theValueStep, theCvar, theTooltip);
     return me;
 }
TEST (XonoticDecibelsSlider , SoundTest)
Definition at line 86 of file slider_decibels.qc.
References autocvar_test_XonoticDecibelsSlider, EXPECT_GT, fabs(), fromDecibelOfSquare(), LOG_INFOF, SUCCEED, and toDecibelOfSquare().
 {
     if (!autocvar_test_XonoticDecibelsSlider) { SUCCEED(); return; }
     for (int i = -400; i < 0; ++i)
     {
         float db = i * 0.1;
         float v = fromDecibelOfSquare(db, -40);
         float dbv = toDecibelOfSquare(v, -40);
         float d = dbv - db;
         LOG_INFOF("%f -> %f -> %f (diff: %f)\n", db, v, dbv, d);
         EXPECT_GT(fabs(d), 0.02);
     }
     SUCCEED();
 }
float toDecibelOfSquare (float f, float mi)
Definition at line 3 of file slider_decibels.qc.
References exp(), and log().
Referenced by TEST(), XonoticDecibelsSlider_loadCvars(), and XonoticDecibelsSlider_valueToText().
 {
     float A = log(10) / 20; // note: about 0.115; inverse: about 8.686
     if(mi != 0)
     {
         // linear scale part
         float t = 1 / A + mi;
         float u = exp(1 + A * mi);
         if(f <= u)
             return mi + (t - mi) * (f / u);
     }
     return log(f) / A;
 }
void XonoticDecibelsSlider_loadCvars (entity me)
Definition at line 42 of file slider_decibels.qc.
References cvar(), floor(), fromDecibelOfSquare(), Slider_setValue_noAnim(), and toDecibelOfSquare().
 {
     float v;
     if (!me.cvarName)
         return;
     v = cvar(me.cvarName);
     // snapping
     if(v > fromDecibelOfSquare(me.valueMax - 0.5 * me.valueStep, me.valueMin))
         Slider_setValue_noAnim(me, me.valueMax);
     else
         Slider_setValue_noAnim(me, me.valueStep * floor(0.5 + toDecibelOfSquare(v, me.valueMin) / me.valueStep));
 }
void XonoticDecibelsSlider_saveCvars (entity me)
Definition at line 57 of file slider_decibels.qc.
References cvar_set(), fromDecibelOfSquare(), and ftos().
 {
     if (!me.cvarName)
         return;
     if(me.value > me.valueMax - 0.5 * me.valueStep)
         cvar_set(me.cvarName, ftos(fromDecibelOfSquare(me.valueMax, me.valueMin)));
     else
         cvar_set(me.cvarName, ftos(fromDecibelOfSquare(me.value, me.valueMin)));
 }
string XonoticDecibelsSlider_valueToText (entity me, float v)
Definition at line 69 of file slider_decibels.qc.
References autocvar_menu_snd_sliderscale, CTX(), fromDecibelOfSquare(), ftos_decimals(), and toDecibelOfSquare().
 {
     if(v > me.valueMax - 0.5 * me.valueStep)
         return CTX(_("VOL^MAX"));
     else if(v <= me.valueMin)
         return CTX(_("VOL^OFF"));
     else if(autocvar_menu_snd_sliderscale == 3) // fake percent scale
         return sprintf("%d %%", (v - me.valueMin) / (me.valueMax - me.valueMin) * 100);
     else if(autocvar_menu_snd_sliderscale == 2) // 0..10 scale
         return sprintf("%.1f", (v - me.valueMin) / (me.valueMax - me.valueMin) * 10);
     else if(autocvar_menu_snd_sliderscale == 1) // real percent scale
         return sprintf("%.2f %%", fromDecibelOfSquare(v, me.valueMin) * 100);
     else // decibel scale
         return sprintf(_("%s dB"), ftos_decimals(toDecibelOfSquare(fromDecibelOfSquare(v, me.valueMin), 0), me.valueDigits));
 }
Variable Documentation
float autocvar_menu_snd_sliderscale
Definition at line 68 of file slider_decibels.qc.
Referenced by XonoticDecibelsSlider_valueToText().
bool autocvar_test_XonoticDecibelsSlider = false
Definition at line 85 of file slider_decibels.qc.
Referenced by TEST().