Xonotic: lib/warpzone/common.qh File Reference
common.qh File Reference
Macros
#define BITCLR(a, b) ((a) - ((a) & (b)))
#define BITCLR_ASSIGN(a, b) ((a) = (a) - ((a) & (b)))
#define BITSET(a, b) ((a) | (b))
#define BITSET_ASSIGN(a, b) ((a) |= (b))
#define BITXOR(a, b) (((a) | (b)) - ((a) & (b)))
#define BITXOR_ASSIGN(a, b) ((a) = ((a) | (b)) - ((a) & (b)))
#define EXACTTRIGGER_INIT WarpZoneLib_ExactTrigger_Init(this)
#define EXACTTRIGGER_TOUCH(e, t) if(WarpZoneLib_ExactTrigger_Touch((e), (t))) return
#define MOVE_NOTHING -1
#define move_out_of_solid(e) WarpZoneLib_MoveOutOfSolid(e)
Typedefs
using WarpZone_trace_callback_t = void(vector start, vector hit, vector end)
Functions
STATIC_INIT (g_warpzones)
void WarpZone_Camera_SetUp (entity e, vector my_org, vector my_ang)
entity WarpZone_Find (vector mi, vector ma)
entity WarpZone_FindRadius (vector org, float radius, float needlineofsight)
void WarpZone_MakeAllOther ()
void WarpZone_MakeAllSolid ()
float WarpZone_PlaneDist (entity wz, vector v)
void WarpZone_RefSys_Add (entity me, entity wz)
void WarpZone_RefSys_AddIncrementally (entity me, entity ref)
void WarpZone_RefSys_AddInverse (entity me, entity wz)
void WarpZone_RefSys_AddInverseTransform (entity me, vector t, vector s)
void WarpZone_RefSys_AddTransform (entity me, vector t, vector s)
void WarpZone_RefSys_BeginAddingIncrementally (entity me, entity ref)
void WarpZone_RefSys_Clear (entity me)
void WarpZone_RefSys_Copy (entity me, entity from)
entity WarpZone_RefSys_SpawnSameRefSys (entity me)
vector WarpZone_RefSys_TransformAngles (entity from, entity to, vector ang)
vector WarpZone_RefSys_TransformOrigin (entity from, entity to, vector org)
vector WarpZone_RefSys_TransformVAngles (entity from, entity to, vector ang)
vector WarpZone_RefSys_TransformVelocity (entity from, entity to, vector vel)
void WarpZone_SetUp (entity e, vector my_org, vector my_ang, vector other_org, vector other_ang)
float WarpZone_TargetPlaneDist (entity wz, vector v)
void WarpZone_TraceBox (vector org, vector min, vector max, vector end, float nomonsters, entity forent)
void WarpZone_TraceBox_ThroughZone (vector org, vector min, vector max, vector end, float nomonsters, entity forent, entity zone, WarpZone_trace_callback_t cb)
void WarpZone_TraceLine (vector org, vector end, float nomonsters, entity forent)
void WarpZone_TraceToss (entity e, entity forent)
void WarpZone_TraceToss_ThroughZone (entity e, entity forent, entity zone, WarpZone_trace_callback_t cb)
void WarpZone_TrailParticles (entity own, float eff, vector org, vector end)
vector WarpZone_TransformAngles (entity wz, vector v)
vector WarpZone_TransformOrigin (entity wz, vector v)
vector WarpZone_TransformVAngles (entity wz, vector v)
vector WarpZone_TransformVelocity (entity wz, vector v)
vector WarpZone_UnTransformAngles (entity wz, vector v)
vector WarpZone_UnTransformOrigin (entity wz, vector v)
vector WarpZone_UnTransformVAngles (entity wz, vector v)
vector WarpZone_UnTransformVelocity (entity wz, vector v)
float WarpZoneLib_BoxTouchesBrush (vector mi, vector ma, entity e, entity ig)
void WarpZoneLib_ExactTrigger_Init (entity this)
bool WarpZoneLib_ExactTrigger_Touch (entity this, entity toucher)
bool WarpZoneLib_MoveOutOfSolid (entity e)
vector WarpZoneLib_NearestPointOnBox (vector mi, vector ma, vector org)
Variables
IntrusiveList g_warpzones
vector warpzone_angles
float warpzone_cameras_exist
float warpzone_fadeend
float warpzone_fadestart
vector WarpZone_findradius_dist
vector WarpZone_findradius_findorigin
float WarpZone_findradius_findradius
vector WarpZone_findradius_nearest
vector warpzone_forward
float warpzone_isboxy
vector warpzone_origin
vector warpzone_shift
vector warpzone_targetangles
vector warpzone_targetforward
vector warpzone_targetorigin
var WarpZone_trace_callback_t WarpZone_trace_callback_t_null
entity WarpZone_trace_firstzone
entity WarpZone_trace_forent
entity WarpZone_trace_lastzone
entity WarpZone_trace_transform
float WarpZone_tracetoss_time
vector WarpZone_tracetoss_velocity
vector warpzone_transform
float warpzone_warpzones_exist
Macro Definition Documentation
#define BITCLR (a, b) ((a) - ((a) & (b)))
Definition at line 92 of file common.qh.
#define BITCLR_ASSIGN (a, b) ((a) = (a) - ((a) & (b)))
Definition at line 101 of file common.qh.
Referenced by WarpZone_TeleportPlayer(), and WarpZone_TraceBox_ThroughZone().
#define BITSET (a, b) ((a) | (b))
Definition at line 95 of file common.qh.
#define BITSET_ASSIGN (a, b) ((a) |= (b))
Definition at line 104 of file common.qh.
Referenced by ctf_DelayedInit(), DelayThink(), trigger_push_findtarget(), WarpZone_Projectile_Touch(), WarpZone_Touch(), and WarpZone_TraceBox_ThroughZone().
#define BITXOR (a, b) (((a) | (b)) - ((a) & (b)))
Definition at line 98 of file common.qh.
#define BITXOR_ASSIGN (a, b) ((a) = ((a) | (b)) - ((a) & (b)))
Definition at line 107 of file common.qh.
Referenced by anim_set(), animdecide_setframes(), CheatCommand(), TeleportPlayer(), and WarpZone_TeleportPlayer().
#define EXACTTRIGGER_INIT WarpZoneLib_ExactTrigger_Init(this)
Definition at line 117 of file common.qh.
Referenced by conveyor_think(), DelayThink(), spawnfunc(), SpawnGoal(), Teleport_Touch(), and trigger_keylock_touch().
#define EXACTTRIGGER_TOUCH (e, t) if(WarpZoneLib_ExactTrigger_Touch((e), (t))) return
Definition at line 116 of file common.qh.
Referenced by checkpoint_touch(), func_ladder_touch(), GoalTouch(), penalty_touch(), Teleport_Touch(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), and trigger_push_touch().
#define MOVE_NOTHING -1
Definition at line 33 of file common.qh.
Referenced by WarpZone_TraceBox_ThroughZone().
#define move_out_of_solid (e) WarpZoneLib_MoveOutOfSolid(e)
Definition at line 110 of file common.qh.
Referenced by CheatCommand(), Portal_FindSafeOrigin(), relocate_nexball(), relocate_spawnpoint(), and waypoint_spawn().
Typedef Documentation
using WarpZone_trace_callback_t = void(vector start, vector hit, vector end)
Definition at line 35 of file common.qh.
Function Documentation
STATIC_INIT (g_warpzones)
Definition at line 7 of file common.qh.
References IL_NEW.
 { g_warpzones = IL_NEW(); }
void WarpZone_Camera_SetUp (entity e, vector my_org, vector my_ang)
Definition at line 95 of file common.qc.
References setcamera_transform, and WarpZone_Camera_camera_transform().
Referenced by NET_HANDLE(), and WarpZone_Projectile_Touch().
 {
     e.warpzone_origin = my_org;
     e.warpzone_angles = my_ang;
     setcamera_transform(e, WarpZone_Camera_camera_transform);
 }
entity WarpZone_Find (vector mi, vector ma)
Definition at line 157 of file common.qc.
References g_warpzones, IL_EACH, NULL, warpzone_warpzones_exist, and WarpZoneLib_BoxTouchesBrush().
Referenced by WarpZone_FixNearClip(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_Projectile_Touch(), WarpZone_Touch(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     // if we are near any warpzone planes - MOVE AWAY (work around nearclip)
     if(!warpzone_warpzones_exist)
         return NULL;
     IL_EACH(g_warpzones, WarpZoneLib_BoxTouchesBrush(mi, ma, it, NULL),
     {
         return it;
     });
     return NULL;
 }
entity WarpZone_FindRadius (vector org, float radius, float needlineofsight)
void WarpZone_MakeAllOther ()
Definition at line 179 of file common.qc.
References g_warpzones, IL_EACH, SOLID_TRIGGER, and warpzone_warpzones_exist.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     if(!warpzone_warpzones_exist)
         return;
     IL_EACH(g_warpzones, true,
     {
         it.solid = SOLID_TRIGGER;
     });
 }
void WarpZone_MakeAllSolid ()
Definition at line 169 of file common.qc.
References g_warpzones, IL_EACH, SOLID_BSP, and warpzone_warpzones_exist.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     if(!warpzone_warpzones_exist)
         return;
     IL_EACH(g_warpzones, true,
     {
         it.solid = SOLID_BSP;
     });
 }
float WarpZone_PlaneDist (entity wz, vector v)
Definition at line 489 of file common.qc.
Referenced by WarpZone_FixNearClip(), WarpZone_Projectile_Touch(), and WarpZone_Touch().
 {
     return (v - wz.warpzone_origin) * wz.warpzone_forward;
 }
void WarpZone_RefSys_Add (entity me, entity wz)
Definition at line 702 of file common.qc.
References WarpZone_RefSys_AddTransform().
Referenced by WarpZone_Teleport().
 {
     WarpZone_RefSys_AddTransform(me, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_RefSys_AddIncrementally (entity me, entity ref)
Definition at line 720 of file common.qc.
References WarpZone_Accumulator_Add(), and WarpZone_Accumulator_AddInverseTransform().
Referenced by GrapplingHookThink().
 {
     //vector t, s;
     if(me.WarpZone_refsys_incremental_transform == ref.WarpZone_refsys.warpzone_transform)
     if(me.WarpZone_refsys_incremental_shift == ref.WarpZone_refsys.warpzone_shift)
         return;
     WarpZone_Accumulator_AddInverseTransform(me.WarpZone_refsys, me.WarpZone_refsys_incremental_transform, me.WarpZone_refsys_incremental_shift);
     WarpZone_Accumulator_Add(me.WarpZone_refsys, ref.WarpZone_refsys);
     me.WarpZone_refsys_incremental_shift = ref.WarpZone_refsys.warpzone_shift;
     me.WarpZone_refsys_incremental_transform = ref.WarpZone_refsys.warpzone_transform;
 }
void WarpZone_RefSys_AddInverse (entity me, entity wz)
Definition at line 714 of file common.qc.
References WarpZone_RefSys_AddInverseTransform().
Referenced by ctf_Handle_Throw(), and Monster_Enemy_Check().
 {
     WarpZone_RefSys_AddInverseTransform(me, wz.warpzone_transform, wz.warpzone_shift);
 }
void WarpZone_RefSys_AddInverseTransform (entity me, vector t, vector s)
Definition at line 706 of file common.qc.
References WarpZone_Accumulator_AddInverseTransform(), and WarpZone_RefSys_CheckCreate().
Referenced by WarpZone_RefSys_AddInverse().
 {
     if(t != '0 0 0' || s != '0 0 0')
     {
         WarpZone_RefSys_CheckCreate(me);
         WarpZone_Accumulator_AddInverseTransform(me.WarpZone_refsys, t, s);
     }
 }
void WarpZone_RefSys_AddTransform (entity me, vector t, vector s)
Definition at line 694 of file common.qc.
References WarpZone_Accumulator_AddTransform(), and WarpZone_RefSys_CheckCreate().
Referenced by WarpZone_RefSys_Add().
 {
     if(t != '0 0 0' || s != '0 0 0')
     {
         WarpZone_RefSys_CheckCreate(me);
         WarpZone_Accumulator_AddTransform(me.WarpZone_refsys, t, s);
     }
 }
void WarpZone_RefSys_BeginAddingIncrementally (entity me, entity ref)
Definition at line 731 of file common.qc.
Referenced by GrapplingHookTouch().
 {
     me.WarpZone_refsys_incremental_shift = ref.WarpZone_refsys.warpzone_shift;
     me.WarpZone_refsys_incremental_transform = ref.WarpZone_refsys.warpzone_transform;
 }
void WarpZone_RefSys_Clear (entity me)
Definition at line 686 of file common.qc.
References NULL.
Referenced by WarpZone_RefSys_Copy().
 {
     if(me.WarpZone_refsys)
     {
         delete(me.WarpZone_refsys);
         me.WarpZone_refsys = NULL;
     }
 }
void WarpZone_RefSys_Copy (entity me, entity from)
Definition at line 768 of file common.qc.
References WarpZone_RefSys_CheckCreate(), and WarpZone_RefSys_Clear().
Referenced by ctf_Handle_Throw(), Monster_Enemy_Check(), and WarpZone_RefSys_SpawnSameRefSys().
 {
     if(from.WarpZone_refsys)
     {
         WarpZone_RefSys_CheckCreate(me);
         me.WarpZone_refsys.warpzone_shift = from.WarpZone_refsys.warpzone_shift;
         me.WarpZone_refsys.warpzone_transform = from.WarpZone_refsys.warpzone_transform;
     }
     else
         WarpZone_RefSys_Clear(me);
 }
entity WarpZone_RefSys_SpawnSameRefSys (entity me)
Definition at line 779 of file common.qc.
References entity(), spawn(), and WarpZone_RefSys_Copy().
Referenced by FireGrapplingHook().
 {
     entity e;
     e = spawn();
     WarpZone_RefSys_Copy(e, me);
     return e;
 }
vector WarpZone_RefSys_TransformAngles (entity from, entity to, vector ang)
Definition at line 752 of file common.qc.
References WarpZone_TransformAngles(), and WarpZone_UnTransformAngles().
 {
     if(from.WarpZone_refsys)
         ang = WarpZone_UnTransformAngles(from.WarpZone_refsys, ang);
     if(to.WarpZone_refsys)
         ang = WarpZone_TransformAngles(to.WarpZone_refsys, ang);
     return ang;
 }
vector WarpZone_RefSys_TransformOrigin (entity from, entity to, vector org)
Definition at line 736 of file common.qc.
References WarpZone_TransformOrigin(), and WarpZone_UnTransformOrigin().
Referenced by ctf_FlagThink(), ctf_Handle_Throw(), GrapplingHookThink(), Monster_Enemy_Check(), and Monster_Move_Target().
 {
     if(from.WarpZone_refsys)
         org = WarpZone_UnTransformOrigin(from.WarpZone_refsys, org);
     if(to.WarpZone_refsys)
         org = WarpZone_TransformOrigin(to.WarpZone_refsys, org);
     return org;
 }
vector WarpZone_RefSys_TransformVAngles (entity from, entity to, vector ang)
Definition at line 760 of file common.qc.
References WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
 {
     if(from.WarpZone_refsys)
         ang = WarpZone_UnTransformVAngles(from.WarpZone_refsys, ang);
     if(to.WarpZone_refsys)
         ang = WarpZone_TransformVAngles(to.WarpZone_refsys, ang);
     return ang;
 }
vector WarpZone_RefSys_TransformVelocity (entity from, entity to, vector vel)
Definition at line 744 of file common.qc.
References WarpZone_TransformVelocity(), and WarpZone_UnTransformVelocity().
Referenced by GrapplingHookThink().
 {
     if(from.WarpZone_refsys)
         vel = WarpZone_UnTransformVelocity(from.WarpZone_refsys, vel);
     if(to.WarpZone_refsys)
         vel = WarpZone_TransformVelocity(to.WarpZone_refsys, vel);
     return vel;
 }
void WarpZone_SetUp (entity e, vector my_org, vector my_ang, vector other_org, vector other_ang)
Definition at line 66 of file common.qc.
References AnglesTransform_PrePostShift_GetPostShift(), AnglesTransform_RightDivide(), AnglesTransform_TurnDirectionFR(), FIXED_MAKE_VECTORS, setcamera_transform, vector(), and WarpZone_camera_transform().
Referenced by NET_HANDLE(), and WarpZone_Projectile_Touch().
 {
     e.warpzone_transform = AnglesTransform_RightDivide(other_ang, AnglesTransform_TurnDirectionFR(my_ang));
     e.warpzone_shift = AnglesTransform_PrePostShift_GetPostShift(my_org, e.warpzone_transform, other_org);
     e.warpzone_origin = my_org;
     e.warpzone_targetorigin = other_org;
     e.warpzone_angles = my_ang;
     e.warpzone_targetangles = other_ang;
     vector forward, right, up;
     FIXED_MAKE_VECTORS(my_ang, forward, right, up);
     e.warpzone_forward = forward;
     FIXED_MAKE_VECTORS(other_ang, forward, right, up);
     e.warpzone_targetforward = forward;
     setcamera_transform(e, WarpZone_camera_transform);
 }
float WarpZone_TargetPlaneDist (entity wz, vector v)
Definition at line 494 of file common.qc.
Referenced by WarpZone_Teleport().
 {
     return (v - wz.warpzone_targetorigin) * wz.warpzone_targetforward;
 }
void WarpZone_TraceBox (vector org, vector min, vector max, vector end, float nomonsters, entity forent)
Definition at line 333 of file common.qc.
References NULL, WarpZone_trace_callback_t_null, and WarpZone_TraceBox_ThroughZone().
Referenced by CommonCommand_editmob(), tracebox_antilag_force_wz(), View_EventChase(), and WarpZone_TraceLine().
 {
     WarpZone_TraceBox_ThroughZone(org, mi, ma, end, nomonsters, forent, NULL, WarpZone_trace_callback_t_null);
 }
void WarpZone_TraceBox_ThroughZone (vector org, vector min, vector max, vector end, float nomonsters, entity forent, entity zone, WarpZone_trace_callback_t cb)
Definition at line 202 of file common.qc.
References BITCLR_ASSIGN, BITSET_ASSIGN, DPCONTENTS_SOLID, entity(), LABEL, LOG_TRACE(), MOVE_NOMONSTERS, MOVE_NOTHING, MOVE_WORLDONLY, normalize(), NULL, trace_dphitcontents, trace_endpos, trace_ent, trace_fraction, trace_startsolid, v_forward, v_right, v_up, vector(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_Trace_AddTransform(), WarpZone_trace_firstzone, WarpZone_trace_forent, WarpZone_Trace_InitTransform(), WarpZone_trace_lastzone, WarpZone_TransformOrigin(), and warpzone_warpzones_exist.
Referenced by fireBullet_antilag(), WarpZone_TraceBox(), and WarpZone_TrailParticles().
 {
     float nomonsters_adjusted;
     float frac, sol, i;
     float contentshack;
     entity wz;
     vector vf, vr, vu;
     WarpZone_trace_forent = forent;
     WarpZone_trace_firstzone = NULL;
     WarpZone_trace_lastzone = NULL;
     WarpZone_Trace_InitTransform();
     if(!warpzone_warpzones_exist)
     {
         if(nomonsters == MOVE_NOTHING)
         {
             trace_endpos = end;
             trace_fraction = 1;
             if(cb)
                 cb(org, trace_endpos, end);
             return;
         }
         else
         {
             tracebox(org, mi, ma, end, nomonsters, WarpZone_trace_forent);
             if(cb)
                 cb(org, trace_endpos, end);
             return;
         }
     }
     vf = v_forward;
     vr = v_right;
     vu = v_up;
     switch(nomonsters)
     {
         case MOVE_WORLDONLY:
         case MOVE_NOTHING:
             nomonsters_adjusted = MOVE_NOMONSTERS;
             break;
         default:
             nomonsters_adjusted = nomonsters;
             break;
     }
     if((contentshack = (WarpZone_trace_forent.dphitcontentsmask && !(WarpZone_trace_forent.dphitcontentsmask & DPCONTENTS_SOLID))))
         BITSET_ASSIGN(WarpZone_trace_forent.dphitcontentsmask, DPCONTENTS_SOLID);
     // if starting in warpzone, first transform
     wz = WarpZone_Find(org + mi, org + ma);
     if(wz)
     {
         WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
         {
             // we are in ANOTHER warpzone. This is bad. Make a zero length trace and return.
             sol = 1;
             trace_fraction = 0;
             trace_endpos = org;
             goto fail;
         }
         WarpZone_Trace_AddTransform(wz);
         org = WarpZone_TransformOrigin(wz, org);
         end = WarpZone_TransformOrigin(wz, end);
     }
     WarpZone_MakeAllSolid();
     sol = -1;
     frac = 0;
     i = 16;
     for (;;)
     {
         if(--i < 1)
         {
             LOG_TRACE("Too many warpzones in sequence, aborting trace.");
             trace_ent = NULL;
             break;
         }
         tracebox(org, mi, ma, end, nomonsters_adjusted, WarpZone_trace_forent);
         if(cb)
             cb(org, trace_endpos, end);
         if(sol < 0)
             sol = trace_startsolid;
         frac = trace_fraction = frac + (1 - frac) * trace_fraction;
         if(trace_fraction >= 1)
             break;
         if(trace_ent.classname != "trigger_warpzone")
         {
             if((nomonsters == MOVE_NOTHING) || ((nomonsters == MOVE_WORLDONLY) && trace_ent) || (contentshack && (trace_dphitcontents & WarpZone_trace_forent.dphitcontentsmask) == DPCONTENTS_SOLID))
             {
                 // continue the trace, ignoring this hit (we only care for warpzones)
                 org = trace_endpos + normalize(end - org);
                 continue;
                 // we cannot do an inverted trace here, as we do care for further warpzones inside that "solid" to be found
                 // otherwise, players could block entrances that way
             }
             break;
         }
         /*if(trace_ent == wz)
         {
             // FIXME can this check be removed? Do we really need it?
             LOG_TRACE("I transformed into the same zone again, wtf, aborting the trace");
             trace_ent = NULL;
             break;
         }*/
         wz = trace_ent;
         if(!WarpZone_trace_firstzone)
             WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
             break;
         WarpZone_Trace_AddTransform(wz);
         // we hit a warpzone... so, let's perform the trace after the warp again
         org = WarpZone_TransformOrigin(wz, trace_endpos);
         end = WarpZone_TransformOrigin(wz, end);
         // we got warped, so let's step back a bit
         tracebox(org, mi, ma, org + normalize(org - end) * 32, nomonsters_adjusted, WarpZone_trace_forent);
         org = trace_endpos;
     }
     WarpZone_MakeAllOther();
 LABEL(fail)
     if(contentshack)
         BITCLR_ASSIGN(WarpZone_trace_forent.dphitcontentsmask, DPCONTENTS_SOLID);
     trace_startsolid = sol;
     v_forward = vf;
     v_right = vr;
     v_up = vu;
 }
void WarpZone_TraceLine (vector org, vector end, float nomonsters, entity forent)
Definition at line 338 of file common.qc.
References WarpZone_TraceBox().
Referenced by CommonCommand_editmob(), ctf_CalculatePassVelocity(), ctf_FlagThink(), Monster_CalculateVelocity(), Monster_Move_Target(), RadiusDamageForSource(), sandbox_ObjectSpawn(), View_EventChase(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     WarpZone_TraceBox(org, '0 0 0', '0 0 0', end, nomonsters, forent);
 }
void WarpZone_TraceToss (entity e, entity forent)
Definition at line 452 of file common.qc.
References NULL, WarpZone_trace_callback_t_null, and WarpZone_TraceToss_ThroughZone().
 {
     WarpZone_TraceToss_ThroughZone(e, forent, NULL, WarpZone_trace_callback_t_null);
 }
void WarpZone_TraceToss_ThroughZone (entity e, entity forent, entity zone, WarpZone_trace_callback_t cb)
Definition at line 343 of file common.qc.
References cvar(), entity(), LABEL, LOG_TRACE(), NULL, setorigin(), trace_endpos, trace_ent, trace_fraction, v_forward, v_right, v_up, vector(), vlen(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_Trace_AddTransform(), WarpZone_trace_firstzone, WarpZone_trace_forent, WarpZone_Trace_InitTransform(), WarpZone_trace_lastzone, WarpZone_tracetoss_time, WarpZone_tracetoss_velocity, WarpZone_TransformOrigin(), WarpZone_TransformVelocity(), and warpzone_warpzones_exist.
Referenced by WarpZone_TraceToss().
 {
     float g, dt, i;
     vector vf, vr, vu, v0, o0;
     entity wz;
     o0 = e.origin;
     v0 = e.velocity;
     g = cvar("sv_gravity") * e.gravity;
     WarpZone_trace_forent = forent;
     WarpZone_trace_firstzone = NULL;
     WarpZone_trace_lastzone = NULL;
     WarpZone_Trace_InitTransform();
     WarpZone_tracetoss_time = 0;
     if(!warpzone_warpzones_exist)
     {
         tracetoss(e, WarpZone_trace_forent);
         if(cb)
             cb(e.origin, trace_endpos, trace_endpos);
         dt = vlen(e.origin - o0) / vlen(e.velocity);
         WarpZone_tracetoss_time += dt;
         e.velocity_z -= dt * g;
         WarpZone_tracetoss_velocity = e.velocity;
         e.velocity = v0;
         return;
     }
     vf = v_forward;
     vr = v_right;
     vu = v_up;
     // if starting in warpzone, first transform
     wz = WarpZone_Find(e.origin + e.mins, e.origin + e.maxs);
     if(wz)
     {
         WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
         {
             // we are in ANOTHER warpzone. This is bad. Make a zero length trace and return.
             WarpZone_tracetoss_time = 0;
             trace_endpos = o0;
             goto fail;
         }
         WarpZone_Trace_AddTransform(wz);
         vector org = WarpZone_TransformOrigin(wz, e.origin);
         setorigin(e, org);
         e.velocity = WarpZone_TransformVelocity(wz, e.velocity);
     }
     WarpZone_MakeAllSolid();
     i = 16;
     for (;;)
     {
         if(--i < 1)
         {
             LOG_TRACE("Too many warpzones in sequence, aborting trace.");
             trace_ent = NULL;
             break;
         }
         tracetoss(e, WarpZone_trace_forent);
         if(cb)
             cb(e.origin, trace_endpos, trace_endpos);
         dt = vlen(trace_endpos - e.origin) / vlen(e.velocity);
         WarpZone_tracetoss_time += dt;
         e.origin = trace_endpos;
         e.velocity_z -= dt * g;
         if(trace_fraction >= 1)
             break;
         if(trace_ent.classname != "trigger_warpzone")
             break;
         if(trace_ent == wz)
         {
             // FIXME can this check be removed? Do we really need it?
             LOG_TRACE("I transformed into the same zone again, wtf, aborting the trace");
             trace_ent = NULL;
             break;
         }
         wz = trace_ent;
         if(!WarpZone_trace_firstzone)
             WarpZone_trace_firstzone = wz;
         WarpZone_trace_lastzone = wz;
         if(zone && wz != zone)
             break;
         WarpZone_Trace_AddTransform(wz);
         // we hit a warpzone... so, let's perform the trace after the warp again
         e.origin = WarpZone_TransformOrigin(wz, e.origin);
         e.velocity = WarpZone_TransformVelocity(wz, e.velocity);
         // we got warped, so let's step back a bit
         e.velocity = -e.velocity;
         tracetoss(e, WarpZone_trace_forent);
         dt = vlen(trace_endpos - e.origin) / vlen(e.velocity);
         WarpZone_tracetoss_time -= dt;
         e.origin = trace_endpos;
         e.velocity = -e.velocity;
     }
     WarpZone_MakeAllOther();
 LABEL(fail)
     WarpZone_tracetoss_velocity = e.velocity;
     v_forward = vf;
     v_right = vr;
     v_up = vu;
     // restore old entity data (caller just uses trace_endpos, WarpZone_tracetoss_velocity and the transform)
     e.velocity = v0;
     e.origin = o0;
 }
void WarpZone_TrailParticles (entity own, float eff, vector org, vector end)
Definition at line 464 of file common.qc.
References entity(), MOVE_NOMONSTERS, NULL, PARTICLES_DRAWASTRAIL, to, vector(), WarpZone_TraceBox_ThroughZone(), WarpZone_TrailParticles_trace_callback(), WarpZone_TrailParticles_trace_callback_eff, and WarpZone_TrailParticles_trace_callback_own.
Referenced by ctf_Handle_Throw().
 {
     WarpZone_TrailParticles_trace_callback_own = own;
     WarpZone_TrailParticles_trace_callback_eff = eff;
     WarpZone_TraceBox_ThroughZone(org, '0 0 0', '0 0 0', end, MOVE_NOMONSTERS, NULL, NULL, WarpZone_TrailParticles_trace_callback);
 }
vector WarpZone_TransformAngles (entity wz, vector v)
Definition at line 509 of file common.qc.
References AnglesTransform_ApplyToAngles().
Referenced by WarpZone_RefSys_TransformAngles(), and WarpZone_Teleport().
 {
     return AnglesTransform_ApplyToAngles(wz.warpzone_transform, v);
 }
vector WarpZone_TransformOrigin (entity wz, vector v)
Definition at line 499 of file common.qc.
References AnglesTransform_Apply().
Referenced by fireBullet_antilag(), RadiusDamageForSource(), WarpZone_camera_transform(), WarpZone_FindRadius_Recurse(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_RefSys_TransformOrigin(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
 {
     return wz.warpzone_shift + AnglesTransform_Apply(wz.warpzone_transform, v);
 }
vector WarpZone_TransformVAngles (entity wz, vector v)
Definition at line 514 of file common.qc.
References AnglesTransform_ApplyToVAngles(), AnglesTransform_CancelRoll(), and AnglesTransform_Normalize().
Referenced by NET_HANDLE(), View_EventChase(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_Projectile_Touch(), WarpZone_RefSys_TransformVAngles(), and WarpZone_Teleport().
 {
 #ifdef KEEP_ROLL
     float roll;
     roll = ang.z;
     ang.z = 0;
 #endif
     ang = AnglesTransform_ApplyToVAngles(wz.warpzone_transform, ang);
 #ifdef KEEP_ROLL
     ang = AnglesTransform_Normalize(ang, true);
     ang = AnglesTransform_CancelRoll(ang);
     ang.z = roll;
 #else
     ang = AnglesTransform_Normalize(ang, false);
 #endif
     return ang;
 }
vector WarpZone_TransformVelocity (entity wz, vector v)
Definition at line 504 of file common.qc.
References AnglesTransform_Apply().
Referenced by fireBullet_antilag(), FireRailgunBullet(), WarpZone_camera_transform(), WarpZone_RefSys_TransformVelocity(), WarpZone_Teleport(), and WarpZone_TraceToss_ThroughZone().
 {
     return AnglesTransform_Apply(wz.warpzone_transform, v);
 }
vector WarpZone_UnTransformAngles (entity wz, vector v)
Definition at line 545 of file common.qc.
References AnglesTransform_ApplyToAngles(), and AnglesTransform_Invert().
Referenced by WarpZone_RefSys_TransformAngles().
 {
     return AnglesTransform_ApplyToAngles(AnglesTransform_Invert(wz.warpzone_transform), v);
 }
vector WarpZone_UnTransformOrigin (entity wz, vector v)
Definition at line 535 of file common.qc.
References AnglesTransform_Apply(), and AnglesTransform_Invert().
Referenced by FireRailgunBullet(), MUTATOR_HOOKFUNCTION(), RadiusDamageForSource(), W_SetupShot_Dir_ProjectileSize_Range(), and WarpZone_RefSys_TransformOrigin().
 {
     return AnglesTransform_Apply(AnglesTransform_Invert(wz.warpzone_transform), v - wz.warpzone_shift);
 }
vector WarpZone_UnTransformVAngles (entity wz, vector v)
Definition at line 550 of file common.qc.
References AnglesTransform_ApplyToVAngles(), AnglesTransform_CancelRoll(), AnglesTransform_Invert(), and AnglesTransform_Normalize().
Referenced by WarpZone_RefSys_TransformVAngles().
 {
     float roll;
     roll = ang.z;
     ang.z = 0;
     ang = AnglesTransform_ApplyToVAngles(AnglesTransform_Invert(wz.warpzone_transform), ang);
     ang = AnglesTransform_Normalize(ang, true);
     ang = AnglesTransform_CancelRoll(ang);
     ang.z = roll;
     return ang;
 }
vector WarpZone_UnTransformVelocity (entity wz, vector v)
Definition at line 540 of file common.qc.
References AnglesTransform_Apply(), and AnglesTransform_Invert().
Referenced by WarpZone_RefSys_TransformVelocity().
 {
     return AnglesTransform_Apply(AnglesTransform_Invert(wz.warpzone_transform), v);
 }
float WarpZoneLib_BoxTouchesBrush (vector mi, vector ma, entity e, entity ig)
Definition at line 138 of file common.qc.
References SOLID_BSP, WarpZoneLib_BoxTouchesBrush_ent, WarpZoneLib_BoxTouchesBrush_ignore, WarpZoneLib_BoxTouchesBrush_maxs, WarpZoneLib_BoxTouchesBrush_mins, and WarpZoneLib_BoxTouchesBrush_Recurse().
Referenced by conveyor_think(), havocbot_moveto(), Teleport_Find(), WarpZone_Find(), and WarpZoneLib_ExactTrigger_Touch().
 {
     float f, s;
     if(!e.modelindex || e.warpzone_isboxy)
         return 1;
     s = e.solid;
     e.solid = SOLID_BSP;
     WarpZoneLib_BoxTouchesBrush_mins = mi;
     WarpZoneLib_BoxTouchesBrush_maxs = ma;
     WarpZoneLib_BoxTouchesBrush_ent = e;
     WarpZoneLib_BoxTouchesBrush_ignore = ig;
     f = WarpZoneLib_BoxTouchesBrush_Recurse();
     e.solid = s;
     return f;
 }
void WarpZoneLib_ExactTrigger_Init (entity this)
Definition at line 12 of file util_server.qc.
References angles, maxs, mins, model, movedir, MOVETYPE_NONE, origin, scale, set_movetype(), setorigin(), solid, SOLID_TRIGGER, vector(), and warpzone_isboxy.
Referenced by WarpZone_Projectile_Touch().
 {
     vector mi, ma;
     if (this.movedir == '0 0 0')
     if (this.angles != '0 0 0')
     {
         vector forward, _r, _u;
         MAKE_VECTORS(this.angles, forward, _r, _u);
         this.movedir = forward;
     }
     if(this.model == "")
     {
         // It's a box! No need to match with exacttriggers.
         this.warpzone_isboxy = 1;
     }
     else
     {
         mi = this.mins;
         ma = this.maxs;
         precache_model(this.model);
         _setmodel(this, this.model);
         // let mapper-set mins/maxs override the model's bounds if set
         if(mi != '0 0 0' || ma != '0 0 0')
         {
             // It's a box! No need to match with exacttriggers.
             this.mins = mi;
             this.maxs = ma;
             this.warpzone_isboxy = 1;
         }
     }
     setorigin(this, this.origin);
     if(this.scale)
         setsize(this, this.mins * this.scale, this.maxs * this.scale);
     else
         setsize(this, this.mins, this.maxs);
     set_movetype(this, MOVETYPE_NONE);
     this.solid = SOLID_TRIGGER;
     this.model = "";
 }
bool WarpZoneLib_ExactTrigger_Touch (entity this, entity toucher)
Definition at line 787 of file common.qc.
 {
     return !WarpZoneLib_BoxTouchesBrush(toucher.absmin, toucher.absmax, this, toucher);
 }
bool WarpZoneLib_MoveOutOfSolid (entity e)
Definition at line 807 of file common.qc.
 {
     vector o = e.origin;
     traceline(o, o, MOVE_WORLDONLY, e);
     if (trace_startsolid)
         return false;
     tracebox(o, e.mins, e.maxs, o, MOVE_WORLDONLY, e);
     if (!trace_startsolid)
         return true;
     vector m0 = e.mins;
     vector m1 = e.maxs;
     e.mins = '0 0 0';
     e.maxs = '0 0 0';
     WarpZoneLib_MoveOutOfSolid_Expand(e, eX * m0.x); e.mins_x = m0.x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eX * m1.x); e.maxs_x = m1.x;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eY * m0.y); e.mins_y = m0.y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eY * m1.y); e.maxs_y = m1.y;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eZ * m0.z); e.mins_z = m0.z;
     WarpZoneLib_MoveOutOfSolid_Expand(e, eZ * m1.z); e.maxs_z = m1.z;
     setorigin(e, e.origin);
     tracebox(e.origin, e.mins, e.maxs, e.origin, MOVE_WORLDONLY, e);
     if (trace_startsolid)
     {
         setorigin(e, o);
         return false;
     }
     return true;
 }
vector WarpZoneLib_NearestPointOnBox (vector mi, vector ma, vector org)
Definition at line 565 of file common.qc.
References bound(), and vector().
Referenced by WarpZone_FindRadius_Recurse().
 {
     vector nearest;
     nearest.x = bound(mi.x, org.x, ma.x);
     nearest.y = bound(mi.y, org.y, ma.y);
     nearest.z = bound(mi.z, org.z, ma.z);
     return nearest;
 }
Variable Documentation
IntrusiveList g_warpzones
Definition at line 6 of file common.qh.
Referenced by NET_HANDLE(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), and WarpZone_Projectile_Touch().
vector warpzone_angles
Definition at line 15 of file common.qh.
Referenced by WarpZone_Camera_camera_transform(), WarpZone_Projectile_Touch(), and WarpZone_Touch().
float warpzone_cameras_exist
Definition at line 10 of file common.qh.
Referenced by NET_HANDLE(), and WarpZone_Projectile_Touch().
float warpzone_fadeend
Definition at line 22 of file common.qh.
Referenced by NET_HANDLE(), WarpZone_Camera_camera_transform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), and WarpZone_Touch().
float warpzone_fadestart
Definition at line 21 of file common.qh.
Referenced by NET_HANDLE(), WarpZone_Camera_camera_transform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), and WarpZone_Touch().
vector WarpZone_findradius_dist
Definition at line 52 of file common.qh.
vector WarpZone_findradius_findorigin
Definition at line 55 of file common.qh.
float WarpZone_findradius_findradius
Definition at line 56 of file common.qh.
vector WarpZone_findradius_nearest
Definition at line 53 of file common.qh.
vector warpzone_forward
Definition at line 16 of file common.qh.
float warpzone_isboxy
Definition at line 12 of file common.qh.
Referenced by conveyor_think(), DelayThink(), NET_HANDLE(), WarpZone_Touch(), and WarpZoneLib_ExactTrigger_Init().
vector warpzone_origin
Definition at line 14 of file common.qh.
Referenced by WarpZone_Camera_camera_transform(), WarpZone_Projectile_Touch(), and WarpZone_Touch().
vector warpzone_shift
Definition at line 13 of file common.qh.
vector warpzone_targetangles
Definition at line 18 of file common.qh.
Referenced by WarpZone_Touch().
vector warpzone_targetforward
Definition at line 19 of file common.qh.
vector warpzone_targetorigin
Definition at line 17 of file common.qh.
Referenced by WarpZone_camera_transform(), and WarpZone_Touch().
var WarpZone_trace_callback_t WarpZone_trace_callback_t_null
Definition at line 36 of file common.qh.
Referenced by WarpZone_TraceBox(), and WarpZone_TraceToss().
entity WarpZone_trace_firstzone
Definition at line 38 of file common.qh.
Referenced by FireRailgunBullet(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
entity WarpZone_trace_forent
Definition at line 34 of file common.qh.
Referenced by fireBullet_antilag(), fireBullet_trace_callback(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
entity WarpZone_trace_lastzone
Definition at line 39 of file common.qh.
Referenced by WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().
entity WarpZone_trace_transform
Definition at line 37 of file common.qh.
Referenced by fireBullet_antilag(), FireRailgunBullet(), View_EventChase(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_Trace_AddTransform(), and WarpZone_Trace_InitTransform().
float WarpZone_tracetoss_time
Definition at line 41 of file common.qh.
Referenced by WarpZone_TraceToss_ThroughZone().
vector WarpZone_tracetoss_velocity
Definition at line 40 of file common.qh.
Referenced by WarpZone_TraceToss_ThroughZone().
vector warpzone_transform
Definition at line 20 of file common.qh.
Referenced by NET_HANDLE().
float warpzone_warpzones_exist
Definition at line 9 of file common.qh.
Referenced by NET_HANDLE(), WarpZone_Find(), WarpZone_MakeAllOther(), WarpZone_MakeAllSolid(), WarpZone_Projectile_Touch(), WarpZone_TraceBox_ThroughZone(), and WarpZone_TraceToss_ThroughZone().