Xonotic: lib/warpzone/client.qh File Reference
client.qh File Reference
Functions
void WarpZone_FixPMove ()
void WarpZone_FixView ()
void WarpZone_Shutdown ()
Variables
vector warpzone_save_view_angles
vector warpzone_save_view_origin
Function Documentation
void WarpZone_FixPMove ()
Definition at line 207 of file client.qc.
References entity(), input_angles, pmove_org, WarpZone_Find(), WarpZone_TransformOrigin(), and WarpZone_TransformVAngles().
 {
     entity e = WarpZone_Find(pmove_org, pmove_org);
     if(e)
     {
         pmove_org = WarpZone_TransformOrigin(e, pmove_org);
         input_angles = WarpZone_TransformVAngles(e, input_angles);
     }
 }
void WarpZone_FixView ()
Definition at line 220 of file client.qc.
References autocvar_cl_rollkillspeed, cvar(), entity(), frametime, max(), min(), vector(), VF_ANGLES, VF_CL_VIEWANGLES_Z, VF_ORIGIN, WarpZone_Find(), WarpZone_FixNearClip(), warpzone_save_view_angles, warpzone_save_view_origin, WarpZone_TransformOrigin(), WarpZone_TransformVAngles(), WarpZone_View_Inside(), and WarpZone_View_Outside().
Referenced by CSQC_UpdateView().
 {
     entity e;
     vector org, ang, nearclip, corner0, corner1, corner2, corner3, o;
     warpzone_save_view_origin = org = getpropertyvec(VF_ORIGIN);
     warpzone_save_view_angles = ang = getpropertyvec(VF_ANGLES);
     e = WarpZone_Find(org, org);
     if(e)
     {
         org = WarpZone_TransformOrigin(e, org);
         ang = WarpZone_TransformVAngles(e, ang);
         WarpZone_View_Inside();
     }
     else
         WarpZone_View_Outside();
 #ifndef KEEP_ROLL
     float rick;
     float f;
     static float rollkill;
     if (STAT(HEALTH) > 0 || STAT(HEALTH) == -666 || STAT(HEALTH) == -2342)
     {
         f = 0;
         // reset roll when passing through a warpzone that change player's roll angle
         if(autocvar_cl_rollkillspeed)
             f = max(0, (1 - frametime * autocvar_cl_rollkillspeed));
         if(rollkill)
             rollkill = 0;
     }
     else
     {
         f = 1;
         // roll the view when killed (v_deathtilt)
         if(autocvar_cl_rollkillspeed)
         {
             rollkill += frametime * autocvar_cl_rollkillspeed;
             f = min(1, rollkill);
         }
         else if(rollkill)
             rollkill = 0;
     }
     rick = getproperty(VF_CL_VIEWANGLES_Z);
     rick *= f;
     setproperty(VF_CL_VIEWANGLES_Z, rick);
     ang.z *= f;
 #endif
     setproperty(VF_ORIGIN, org);
     setproperty(VF_ANGLES, ang);
     nearclip = '0 0 1' * (cvar("r_nearclip") * 1.125);
     corner0 = cs_unproject('0 0 0' + nearclip);
     corner1 = cs_unproject('1 0 0' * cvar("vid_conwidth") + nearclip);
     corner2 = cs_unproject('0 1 0' * cvar("vid_conheight") + nearclip);
     corner3 = cs_unproject('1 0 0' * cvar("vid_conwidth") + '0 1 0' * cvar("vid_conheight") + nearclip);
     o = WarpZone_FixNearClip(org, corner0, corner1, corner2, corner3);
     if(o != '0 0 0')
         setproperty(VF_ORIGIN, org + o);
 }
void WarpZone_Shutdown ()
Definition at line 283 of file client.qc.
References WarpZone_View_Outside().
Referenced by Shutdown().
 {
     WarpZone_View_Outside();
 }
Variable Documentation
vector warpzone_save_view_angles
Definition at line 9 of file client.qh.
Referenced by WarpZone_FixView().
vector warpzone_save_view_origin
Definition at line 8 of file client.qh.
Referenced by WarpZone_FixView().