Xonotic: server/compat/quake3.qc File Reference
quake3.qc File Reference
#include "quake3.qh"
#include <common/gamemodes/_mod.qh>
#include <common/gamemodes/gamemode/ctf/sv_ctf.qh>
#include <common/mapobjects/trigger/counter.qh>
#include <common/mapobjects/triggers.qh>
#include <common/mutators/mutator/buffs/buffs.qh>
#include <common/mutators/mutator/buffs/sv_buffs.qh>
#include <common/mutators/mutator/powerups/_mod.qh>
#include <common/mutators/mutator/status_effects/_mod.qh>
#include <common/notifications/all.qh>
#include <common/stats.qh>
#include <common/weapons/_all.qh>
#include <server/client.qh>
#include <server/items/items.qh>
#include <server/items/spawning.qh>
#include <server/resources.qh>
#include <server/world.qh>
Functions
bool DoesQ3ARemoveThisEntity (entity this)
void fragsfilter_use (entity this, entity actor, entity trigger)
int GetAmmoConsumptionQ3 (string netname)
void score_use (entity this, entity actor, entity trigger)
spawnfunc (target_init)
spawnfunc (target_give)
spawnfunc (target_score)
spawnfunc (target_fragsFilter)
SPAWNFUNC_ITEM (item_armor_green, ITEM_ArmorMedium) .float wait
void target_give_init (entity this)
void target_init_use (entity this, entity actor, entity trigger)
void target_init_verify (entity this)
Variables
float delay
string gametype
bool notcpm
bool notfree
bool notsingle
bool notta
bool notteam
bool notvq3
Function Documentation
DoesQ3ARemoveThisEntity()
bool DoesQ3ARemoveThisEntity (entity this)
Definition at line 282 of file quake3.qc.
References ctf_oneflag, cvar_string(), g_ctf, g_duel, gametype, maxclients, notcpm, notfree, notsingle, notta, notteam, notvq3, strstrofs, and teamplay.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     // Q3 style filters (DO NOT USE, THIS IS COMPAT ONLY)
     // DeFRaG mappers use "notcpm" or "notvq3" to disable an entity in CPM or VQ3 physics
     // Xonotic is usually played with a CPM-based physics so we default to CPM mode
     if(cvar_string("g_mod_physics") == "Q3")
     {
         if(this.notvq3)
             return true;
     }
     else if(this.notcpm)
         return true;
     // Q3 mappers use "notq3a" or "notta" to disable an entity in Q3A or Q3TA
     // Xonotic has ~equivalent features to Team Arena
     if(this.notta)
         return true;
     // FIXME: singleplayer does not use maxclients 1 as that would prevent bots
     if(this.notsingle)
         if(maxclients == 1)
             return true;
     if(this.notteam)
         if(teamplay)
             return true;
     if(this.notfree)
         if(!teamplay)
             return true;
     if(this.gametype)
     {
         string gametypename;
         // From ioq3 g_spawn.c: static char *gametypeNames[] = {"ffa", "tournament", "single", "team", "ctf", "oneflag", "obelisk", "harvester"};
         gametypename = "ffa";
         if(teamplay)
             gametypename = "team";
         if(g_ctf)
             gametypename = "ctf";
         if(g_ctf && ctf_oneflag)
             gametypename = "oneflag";
         if(g_duel)
             gametypename = "tournament";
         if(maxclients == 1)
             gametypename = "single";
         // we do not have the other types (obelisk, harvester)
         if(strstrofs(this.gametype, gametypename, 0) < 0)
             return true;
     }
     return false;
 }
fragsfilter_use()
void fragsfilter_use (entity this, entity actor, entity trigger)
Definition at line 259 of file quake3.qc.
References IS_PLAYER, and SUB_UseTargets().
Referenced by spawnfunc().
 {
     if(!IS_PLAYER(actor))
         return;
     if(actor.fragsfilter_cnt >= this.frags)
         SUB_UseTargets(this, actor, trigger);
 }
GetAmmoConsumptionQ3()
int GetAmmoConsumptionQ3 (string netname)
Definition at line 337 of file quake3.qc.
References cvar(), and strcat().
Referenced by weapon_defaultspawnfunc().
 {
     switch (netname)
     {
         case "arc":    return autocvar_g_balance_arc_beam_ammo;
         case "devastator": return autocvar_g_balance_devastator_ammo;
         case "machinegun": return autocvar_g_balance_machinegun_sustained_ammo;
         case "minelayer":  return autocvar_g_balance_minelayer_ammo;
         case "seeker":     return autocvar_g_balance_seeker_tag_ammo;
         default:       return cvar(strcat("g_balance_", netname, "_primary_ammo"));
     }
 }
score_use()
void score_use (entity this, entity actor, entity trigger)
Definition at line 244 of file quake3.qc.
References count, and IS_PLAYER.
Referenced by spawnfunc().
 {
     if(!IS_PLAYER(actor))
         return;
     actor.fragsfilter_cnt += this.count;
 }
spawnfunc() [1/4]
spawnfunc (target_init)
Definition at line 197 of file quake3.qc.
References InitializeEntity(), target_init_use(), target_init_verify(), and use.
 {
     this.use = target_init_use;
     InitializeEntity(this, target_init_verify, INITPRIO_FINDTARGET);
 }
spawnfunc() [2/4]
spawnfunc (target_give)
Definition at line 239 of file quake3.qc.
References InitializeEntity(), and target_give_init().
 {
     InitializeEntity(this, target_give_init, INITPRIO_FINDTARGET);
 }
spawnfunc() [3/4]
spawnfunc (target_score)
Definition at line 250 of file quake3.qc.
References count, g_cts, score_use(), and use.
 {
     if(!g_cts) { delete(this); return; }
     if(!this.count)
         this.count = 1;
     this.use = score_use;
 }
spawnfunc() [4/4]
spawnfunc (target_fragsFilter)
Definition at line 266 of file quake3.qc.
References frags, fragsfilter_use(), g_cts, and use.
 {
     if(!g_cts) { delete(this); return; }
     if(!this.frags)
         this.frags = 1;
     this.use = fragsfilter_use;
 }
SPAWNFUNC_ITEM()
SPAWNFUNC_ITEM (item_armor_green , ITEM_ArmorMedium)
Referenced by Item_SetExpiring(), and spawnfunc().
target_give_init()
void target_give_init (entity this)
Definition at line 204 of file quake3.qc.
References g_items, IL_EACH, InitializeEntity(), setthink, spawnflags, target_init_verify(), and time.
Referenced by spawnfunc().
 {
     IL_EACH(g_items, it.targetname == this.target,
     {
         if (it.classname == "item_buff")
         {
             this.netname = cons(this.netname, it.buffdef.netname);
             this.buffs_finished += it.buffs_finished;
         }
         else
         {
             this.ammo_rockets          += it.ammo_rockets;
             this.ammo_cells            += it.ammo_cells;
             this.ammo_shells           += it.ammo_shells;
             this.ammo_nails            += it.ammo_nails;
             this.invincible_finished   += it.invincible_finished;
             this.strength_finished     += it.strength_finished;
             this.speed_finished        += it.speed_finished;
             this.invisibility_finished += it.invisibility_finished;
             this.health                += it.health;
             this.armorvalue            += it.armorvalue;
             this.netname = cons(this.netname, (it.itemdef.m_weapon) ? it.itemdef.m_weapon.netname : it.itemdef.netname);
         }
         //remove(it); // removing ents in init functions causes havoc, workaround:
         setthink(it, SUB_Remove);
         it.nextthink = time;
     });
     this.spawnflags = 2;
     this.spawnfunc_checked = true;
     spawnfunc_target_items(this);
     InitializeEntity(this, target_init_verify, INITPRIO_FINDTARGET);
 }
target_init_use()
void target_init_use (entity this, entity actor, entity trigger)
Definition at line 130 of file quake3.qc.
References ATTN_NORM, autocvar_g_balance_pause_armor_rot, autocvar_g_balance_pause_health_regen, autocvar_g_balance_pause_health_rot, buff_FirstFromFlags(), buff_RemoveAll(), CH_TRIGGER, entity(), FOREACH, IS_INDEPENDENT_PLAYER, RES_ARMOR, RES_BULLETS, RES_CELLS, RES_FUEL, RES_HEALTH, RES_PLASMA, RES_ROCKETS, RES_SHELLS, SetResource(), sound, spawnflags, start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_weapons, STATUSEFFECT_REMOVE_NORMAL, SUB_UseTargets(), time, VOL_BASE, and WEPSET.
Referenced by spawnfunc().
 {
     if (!(this.spawnflags & 1))
     {
         SetResource(actor, RES_ARMOR, start_armorvalue);
         actor.pauserotarmor_finished = time + autocvar_g_balance_pause_armor_rot;
     }
     if (!(this.spawnflags & 2))
     {
         SetResource(actor, RES_HEALTH, start_health);
         actor.pauserothealth_finished = time + autocvar_g_balance_pause_health_rot;
         actor.pauseregen_finished = time + autocvar_g_balance_pause_health_regen;
     }
     if (!(this.spawnflags & 4))
     {
         if(this.spawnflags & 32) // spawn with only melee
         {
             SetResource(actor, RES_SHELLS, 0);
             SetResource(actor, RES_BULLETS, 0);
             SetResource(actor, RES_ROCKETS, 0);
             SetResource(actor, RES_CELLS, 0);
             SetResource(actor, RES_PLASMA, 0);
             SetResource(actor, RES_FUEL, 0);
             STAT(WEAPONS, actor) = WEPSET(SHOTGUN);
         }
         else
         {
             SetResource(actor, RES_SHELLS, start_ammo_shells);
             SetResource(actor, RES_BULLETS, start_ammo_nails);
             SetResource(actor, RES_ROCKETS, start_ammo_rockets);
             SetResource(actor, RES_CELLS, start_ammo_cells);
             SetResource(actor, RES_PLASMA, start_ammo_plasma);
             SetResource(actor, RES_FUEL, start_ammo_fuel);
             STAT(WEAPONS, actor) = start_weapons;
         }
     }
     if (!(this.spawnflags & 8))
     {
         FOREACH(StatusEffect, it.instanceOfPowerups,
         {
             it.m_remove(it, actor, STATUSEFFECT_REMOVE_NORMAL);
         });
         entity heldbuff = buff_FirstFromFlags(actor);
         if(heldbuff) // TODO: make a dropbuffs function to handle this
         {
             int buffid = heldbuff.m_id;
             Send_Notification(NOTIF_ONE, actor, MSG_MULTI, ITEM_BUFF_DROP, buffid);
             sound(actor, CH_TRIGGER, SND_BUFF_LOST, VOL_BASE, ATTN_NORM);
             if(!IS_INDEPENDENT_PLAYER(actor))
                 Send_Notification(NOTIF_ALL_EXCEPT, actor, MSG_INFO, INFO_ITEM_BUFF_LOST, actor.netname, buffid);
             buff_RemoveAll(actor, STATUSEFFECT_REMOVE_NORMAL);
         }
     }
     if (!(this.spawnflags & 16))
     {
         // We don't have holdables.
     }
     SUB_UseTargets(this, actor, trigger);
 }
target_init_verify()
void target_init_verify (entity this)
Definition at line 112 of file quake3.qc.
References classname, entity(), find(), NULL, and targetname.
Referenced by spawnfunc(), and target_give_init().
 {
     entity trigger, targ;
     for(trigger = NULL; (trigger = find(trigger, classname, "trigger_multiple")); )
         for(targ = NULL; (targ = find(targ, targetname, trigger.target)); )
             if (targ.classname == "target_init" || targ.classname == "target_give" || targ.classname == "target_items")
             {
                 trigger.wait = 0;
                 trigger.delay = 0;
                 targ.wait = 0;
                 targ.delay = 0;
                 //setsize(targ, trigger.mins, trigger.maxs);
                 //setorigin(targ, trigger.origin);
                 //remove(trigger);
             }
 }
Variable Documentation
delay
float delay
Definition at line 109 of file quake3.qc.
gametype
string gametype
Definition at line 281 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notcpm
bool notcpm
Definition at line 280 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notfree
bool notfree
Definition at line 277 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notsingle
bool notsingle
Definition at line 276 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notta
bool notta
Definition at line 278 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notteam
bool notteam
Definition at line 275 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
notvq3
bool notvq3
Definition at line 279 of file quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().