Xonotic: server/antilag.qc File Reference
antilag.qc File Reference
#include "antilag.qh"
Functions
void antilag_clear (entity e, entity store)
float antilag_find (entity e, entity store, float t)
void antilag_record (entity e, entity store, float t)
void antilag_restore (entity e, entity store)
void antilag_takeback (entity e, entity store, float t)
vector antilag_takebackavgvelocity (entity e, entity store, float t0, float t1)
vector antilag_takebackorigin (entity e, entity store, float t)
Variables
float antilag_debug
int antilag_index
const int ANTILAG_MAX_ORIGINS = 64
vector antilag_origins [ANTILAG_MAX_ORIGINS]
vector antilag_saved_origin
float antilag_takenback
float antilag_times [ANTILAG_MAX_ORIGINS]
Function Documentation
void antilag_clear (entity e, entity store)
Definition at line 112 of file antilag.qc.
References ANTILAG_MAX_ORIGINS, and antilag_restore().
Referenced by PutClientInServer(), vehicles_damage(), and vehicles_enter().
 {
     antilag_restore(e, store);
     for (int i = 0; i < ANTILAG_MAX_ORIGINS; ++i) {
         store.antilag_times[i] = -2342;
         store.antilag_origins[i] = e.origin;
     }
     store.antilag_index = ANTILAG_MAX_ORIGINS - 1; // next one is 0
 }
float antilag_find (entity e, entity store, float t)
Definition at line 38 of file antilag.qc.
References ANTILAG_MAX_ORIGINS.
Referenced by antilag_takebackorigin().
 {
     for(int i = store.antilag_index; i > 0; --i)
         if(store.antilag_times[i] >= t)
             if(store.antilag_times[i - 1] < t)
                 return i - 1;
     if(store.antilag_times[0] >= t)
         if(store.antilag_times[ANTILAG_MAX_ORIGINS - 1] < t)
             return ANTILAG_MAX_ORIGINS - 1;
     for(int i = ANTILAG_MAX_ORIGINS - 1; i > store.antilag_index + 1; --i)
         if(store.antilag_times[i] >= t)
             if(store.antilag_times[i - 1] < t)
                 return i - 1;
     // if we get here, t is sandwiched nowhere, so let's assume it's in the present
     return -1;
 }
void antilag_record (entity e, entity store, float t)
Definition at line 19 of file antilag.qc.
References ANTILAG_MAX_ORIGINS, antilag_record(), antilag_takebackorigin(), time, and VHF_PLAYERSLOT.
Referenced by antilag_record(), and EndFrame().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_record(e.vehicle, e.vehicle, t);
     }
     if (time < store.antilag_times[store.antilag_index]) return;
     store.antilag_index += 1;
     if (store.antilag_index >= ANTILAG_MAX_ORIGINS)
         store.antilag_index = 0;
     store.antilag_times[store.antilag_index] = t;
     store.antilag_origins[store.antilag_index] = e.origin;
     if (store.antilag_debug)
         te_spark(antilag_takebackorigin(e, store, t - store.antilag_debug), '0 0 0', 32);
 }
void antilag_restore (entity e, entity store)
Definition at line 99 of file antilag.qc.
References antilag_restore(), and VHF_PLAYERSLOT.
Referenced by antilag_clear(), antilag_restore(), fireBullet(), tracebox_antilag_force_wz(), and W_HitPlotAnalysis().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_restore(e.vehicle, e.vehicle);
     }
     if (!store.antilag_takenback) return;
     setorigin(e, store.antilag_saved_origin);
     store.antilag_takenback = false;
 }
void antilag_takeback (entity e, entity store, float t)
Definition at line 84 of file antilag.qc.
References antilag_takeback(), antilag_takebackorigin(), vector(), and VHF_PLAYERSLOT.
Referenced by antilag_takeback(), fireBullet(), tracebox_antilag_force_wz(), and W_HitPlotAnalysis().
 {
     if (e.vehicle) {
         if (e.vehicle.vehicle_flags == VHF_PLAYERSLOT) return;
         antilag_takeback(e.vehicle, e.vehicle, t);
     }
     if (!store.antilag_takenback)
         store.antilag_saved_origin = e.origin;
     vector org = antilag_takebackorigin(e, store, t);
     setorigin(e, org);
     store.antilag_takenback = true;
 }
vector antilag_takebackavgvelocity (entity e, entity store, float t0, float t1)
Definition at line 76 of file antilag.qc.
References antilag_takebackorigin(), and vector().
 {
     if (t0 >= t1) return '0 0 0';
     vector o0 = antilag_takebackorigin(e, store, t0);
     vector o1 = antilag_takebackorigin(e, store, t1);
     return (o1 - o0) * (1 / (t1 - t0));
 }
vector antilag_takebackorigin (entity e, entity store, float t)
Definition at line 58 of file antilag.qc.
References antilag_find(), ANTILAG_MAX_ORIGINS, and lerpv().
Referenced by antilag_record(), antilag_takeback(), and antilag_takebackavgvelocity().
 {
     int i0 = antilag_find(e, store, t);
     if (i0 < 0)
     {
         // IN THE PRESENT
         if(store.antilag_takenback)
             return store.antilag_saved_origin;
         else
             return e.origin;
     }
     int i1 = i0 + 1;
     if (i1 >= ANTILAG_MAX_ORIGINS)
         i1 = 0;
     return lerpv(store.antilag_times[i0], store.antilag_origins[i0], store.antilag_times[i1], store.antilag_origins[i1], t);
 }
Variable Documentation
float antilag_debug
Definition at line 17 of file antilag.qc.
Referenced by FireRailgunBullet().
int antilag_index
Definition at line 13 of file antilag.qc.
const int ANTILAG_MAX_ORIGINS = 64
Definition at line 10 of file antilag.qc.
Referenced by antilag_clear(), antilag_find(), antilag_record(), and antilag_takebackorigin().
vector antilag_origins[ANTILAG_MAX_ORIGINS]
Definition at line 11 of file antilag.qc.
vector antilag_saved_origin
Definition at line 14 of file antilag.qc.
float antilag_takenback
Definition at line 15 of file antilag.qc.
float antilag_times[ANTILAG_MAX_ORIGINS]
Definition at line 12 of file antilag.qc.