Xonotic: lib/p2mathlib.qc File Reference
p2mathlib.qc File Reference
Functions
ERASEABLE vector aim_vec (vector org, vector targ)
ERASEABLE float angle_snap_f (float f, float increment)
ERASEABLE vector angle_snap_vec (vector v, float increment)
ERASEABLE vector vec_bias (vector v, float f)
ERASEABLE vector vec_bounds_in (vector point, vector a, vector b)
ERASEABLE vector vec_bounds_out (vector point, vector a, vector b)
ERASEABLE vector vec_to_max (vector a, vector b)
ERASEABLE vector vec_to_min (vector a, vector b)
Function Documentation
ERASEABLE vector aim_vec (vector org, vector targ)
Definition at line 95 of file p2mathlib.qc.
References normalize(), v, vectoangles(), and vector().
 {
     vector v;
     // we float around x and y, but rotate around z
     v.x = targ.x - org.x;
     v.y = targ.y - org.y;
     v.z = org.z - targ.z;
     // get the angles actual
     return vectoangles(normalize(v));
 }
ERASEABLE float angle_snap_f (float f, float increment)
Definition at line 73 of file p2mathlib.qc.
Referenced by angle_snap_vec().
 {
     for (int j = 0; j <= 360; )
     {
         if (f <= j - increment) return j - increment;
         j = j + increment;
     }
     return 0;
 }
ERASEABLE vector angle_snap_vec (vector v, float increment)
Definition at line 85 of file p2mathlib.qc.
References angle_snap_f(), and vector().
 {
     vector c;
     c.x = angle_snap_f(v.x, increment);
     c.y = angle_snap_f(v.y, increment);
     c.z = angle_snap_f(v.z, increment);
     return c;
 }
ERASEABLE vector vec_bias (vector v, float f)
Definition at line 21 of file p2mathlib.qc.
References vector().
 {
     vector c;
     c.x = v.x + f;
     c.y = v.y + f;
     c.z = v.z + f;
     return c;
 }
ERASEABLE vector vec_bounds_in (vector point, vector a, vector b)
Definition at line 51 of file p2mathlib.qc.
References vec_to_max(), vec_to_min(), and vector().
 {
     vector d = vec_to_min(a, b);
     vector e = vec_to_max(a, b);
     vector c = vec_to_min(vec_to_max(point, d), e);
     return c;
 }
ERASEABLE vector vec_bounds_out (vector point, vector a, vector b)
Definition at line 62 of file p2mathlib.qc.
References vec_to_max(), vec_to_min(), and vector().
 {
     vector d = vec_to_max(a, b);
     vector e = vec_to_min(a, b);
     vector c = vec_to_min(vec_to_max(point, d), e);
     return c;
 }
ERASEABLE vector vec_to_max (vector a, vector b)
Definition at line 40 of file p2mathlib.qc.
References max(), and vector().
Referenced by vec_bounds_in(), and vec_bounds_out().
 {
     vector c;
     c.x = max(a.x, b.x);
     c.y = max(a.y, b.y);
     c.z = max(a.z, b.z);
     return c;
 }
ERASEABLE vector vec_to_min (vector a, vector b)
Definition at line 30 of file p2mathlib.qc.
References min(), and vector().
Referenced by vec_bounds_in(), and vec_bounds_out().
 {
     vector c;
     c.x = min(a.x, b.x);
     c.y = min(a.y, b.y);
     c.z = min(a.z, b.z);
     return c;
 }