Xonotic: menu/xonotic/screenshotimage.qc File Reference
screenshotimage.qc File Reference
#include "screenshotimage.qh"
Functions
entity makeXonoticScreenshotImage ()
void XonoticScreenshotImage_configureXonoticScreenshotImage (entity me)
void XonoticScreenshotImage_draw (entity me)
void XonoticScreenshotImage_load (entity me, string theImage)
float XonoticScreenshotImage_mouseDrag (entity me, vector coords)
float XonoticScreenshotImage_mouseMove (entity me, vector coords)
void XonoticScreenshotImage_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Function Documentation
makeXonoticScreenshotImage()
entity makeXonoticScreenshotImage ()
Definition at line 3 of file screenshotimage.qc.
References entity(), and NEW.
Referenced by XonoticScreenshotViewerDialog_fill().
 {
     entity me;
     me = NEW(XonoticScreenshotImage);
     me.configureXonoticScreenshotImage(me);
     return me;
 }
XonoticScreenshotImage_configureXonoticScreenshotImage()
void XonoticScreenshotImage_configureXonoticScreenshotImage (entity me)
Definition at line 11 of file screenshotimage.qc.
References string_null.
 {
     me.configureXonoticImage(me, string_null, -2);
     me.zoomLimitedByTheBox = false; // enable this to forbid enlarging the image more than the containing box (if making use of draw_SetClip is a too bad thing)
     me.zoomSnapToTheBox = false; // disabled: it's cooler
 }
XonoticScreenshotImage_draw()
void XonoticScreenshotImage_draw (entity me)
Definition at line 43 of file screenshotimage.qc.
References draw_CenterText(), draw_Text(), floor(), SUPER, and time.
 {
     if (me.src != "")
     {
         float theAlpha;
         SUPER(XonoticScreenshotImage).draw(me);
         if (me.showTitle && time < me.screenshotTime + 4) // 3 seconds at full alpha, 1 second fading out
         {
             theAlpha = (4 - (time - me.screenshotTime));
             draw_CenterText('0.5 0 0', me.screenshotTitle, me.realFontSize, '1 1 1', theAlpha, false);
         }
         if (time < me.zoomTime + 2) // 1 seconds at full alpha, 1 second fading out
         {
             string zoomString;
             float myzoom = me.zoomFactor * 100;
             if (myzoom - floor(myzoom) == 0)
                 zoomString = sprintf("%d%%", myzoom);
             else
                 zoomString = sprintf("%.2f%%", myzoom);
             theAlpha = (2 - (time - me.zoomTime));
             draw_Text('0.05 0.95 0', zoomString, me.realFontSize, '1 1 1', theAlpha, false);
         }
     }
 }
XonoticScreenshotImage_load()
void XonoticScreenshotImage_load (entity me, string theImage)
Definition at line 18 of file screenshotimage.qc.
References METHOD, strcpy, strlen(), substring(), time, and vector().
 {
     me.screenshotTime = time;
     me.src = theImage;
     strcpy(me.screenshotTitle, substring(me.src, 13, strlen(theImage) - 13)); //strip "/screenshots/"
     me.initZoom(me); // this image may have a different size
     me.setZoom(me, 0, 0);
 }
XonoticScreenshotImage_mouseDrag()
float XonoticScreenshotImage_mouseDrag (entity me, vector coords)
Definition at line 33 of file screenshotimage.qc.
 {
     return me.drag(me, coords);
 }
XonoticScreenshotImage_mouseMove()
float XonoticScreenshotImage_mouseMove (entity me, vector coords)
Definition at line 38 of file screenshotimage.qc.
 {
     return me.drag_setStartPos(me, coords);
 }
XonoticScreenshotImage_resizeNotify()
void XonoticScreenshotImage_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 68 of file screenshotimage.qc.
References SUPER.
 {
     SUPER(XonoticScreenshotImage).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.realFontSize_y = me.fontSize / absSize.y;
     me.realFontSize_x = me.fontSize / absSize.x;
 }