Xonotic: server/cl_impulse.qc File Reference
cl_impulse.qc File Reference
#include "cl_impulse.qh"
#include "round_handler.qh"
#include "bot/waypoints.qh"
#include "weapons/throwing.qh"
#include "command/common.qh"
#include "cheats.qh"
#include "bot/navigation.qh"
#include "weapons/selection.qh"
#include "weapons/tracing.qh"
#include "weapons/weaponsystem.qh"
#include <common/state.qh>
#include "../common/minigames/sv_minigames.qh"
#include "../common/weapons/all.qh"
#include "../common/vehicles/sv_vehicles.qh"
#include "../common/mutators/mutator/waypoints/waypointsprites.qh"
Macros
#define IMPULSE(id) _IMPULSE(IMP_##id)
#define _IMPULSE(id)
#define X(slot)
Impulse map:
#define X(slot, dir)
Impulse map:
#define X(i)
Impulse map:
#define X(id) case IMP_##id.impulse:
Impulse map:
Functions
X (1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) X(0) X(0
prev X (1, prev) X(2
prev prev X (3, prev) X(4
prev prev prev X (5, prev) X(6
prev prev prev prev X (7, prev) X(8
prev prev prev prev prev X (9, prev) X(0
prev prev prev prev prev best X (1, best) X(2
prev prev prev prev prev best best X (3, best) X(4
prev prev prev prev prev best
best best X (5, best) X(6
prev prev prev prev prev best
best best best X (7, best) X(8
prev prev prev prev prev best
best best best best X (9, best) X(0
prev prev prev prev prev best
best best best best next X (1, next) X(2
prev prev prev prev prev best
best best best best next next X (3, next) X(4
prev prev prev prev prev best
best best best best next next
next X (5, next) X(6
prev prev prev prev prev best
best best best best next next
next next X (7, next) X(8
prev prev prev prev prev best
best best best best next next
next next next X (9, next) X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15) X(16) X(17) X(18) X(19) X(20) X(21) X(22) X(23) IMPULSE(weapon_next_byid)
IMPULSE (weapon_prev_byid)
IMPULSE (weapon_next_bygroup)
IMPULSE (weapon_prev_bygroup)
IMPULSE (weapon_next_bypriority)
IMPULSE (weapon_prev_bypriority)
IMPULSE (weapon_last)
IMPULSE (weapon_best)
IMPULSE (weapon_drop)
IMPULSE (weapon_reload)
void ImpulseCommands (entity this)
IMPULSE (use)
IMPULSE (waypoint_personal_here)
IMPULSE (waypoint_personal_crosshair)
IMPULSE (waypoint_personal_death)
IMPULSE (waypoint_here_follow)
IMPULSE (waypoint_here_here)
IMPULSE (waypoint_here_crosshair)
IMPULSE (waypoint_here_death)
IMPULSE (waypoint_danger_here)
IMPULSE (waypoint_danger_crosshair)
IMPULSE (waypoint_danger_death)
IMPULSE (waypoint_clear_personal)
IMPULSE (waypoint_clear)
IMPULSE (navwaypoint_spawn)
IMPULSE (navwaypoint_remove)
IMPULSE (navwaypoint_relink)
IMPULSE (navwaypoint_save)
IMPULSE (navwaypoint_unreachable)
Variables
entity vehicle
Macro Definition Documentation
#define _IMPULSE (id)
Value:
void id##_handle(entity this); \
    STATIC_INIT_LATE(id) \
    { \
        id.impulse_handle = id##_handle; \
    } \
    void id##_handle(entity this)
Definition at line 26 of file cl_impulse.qc.
#define IMPULSE (id) _IMPULSE(IMP_##id)
Definition at line 25 of file cl_impulse.qc.
#define X (slot)
Value:
IMPULSE(weapon_group_##slot) \
    { \
        if (IS_DEAD(this)) \
        { \
            this.impulse = IMP_weapon_group_##slot.impulse; \
            return; \
        } \
        W_NextWeaponOnImpulse(slot); \
    }
Impulse map:
0 reserved (no input)
99: loaded
140: moving clone 141: ctf speedrun 142: fixed clone 143: emergency teleport 148: unfairly eliminate
TODO: 200 to 209: prev weapon shortcuts 210 to 219: best weapon shortcuts 220 to 229: next weapon shortcuts 230 to 253: individual weapons (up to 24)
Definition at line 56 of file cl_impulse.qc.
Referenced by ImpulseCommands().
#define X (slot, dir)
Value:
IMPULSE(weapon_priority_##slot##_##dir) \
    { \
        if (this.vehicle) return; \
        if (IS_DEAD(this)) \
        { \
            this.impulse = IMP_weapon_priority_##slot##_##dir.impulse; \
            return; \
        } \
        noref int prev = -1; \
        noref int best =  0; \
        noref int next = +1; \
        W_CycleWeapon(this.cvar_cl_weaponpriorities[slot], dir); \
    }
Impulse map:
0 reserved (no input)
99: loaded
140: moving clone 141: ctf speedrun 142: fixed clone 143: emergency teleport 148: unfairly eliminate
TODO: 200 to 209: prev weapon shortcuts 210 to 219: best weapon shortcuts 220 to 229: next weapon shortcuts 230 to 253: individual weapons (up to 24)
Definition at line 56 of file cl_impulse.qc.
#define X (i)
Value:
IMPULSE(weapon_byid_##i) \
    { \
        if (this.vehicle) return; \
        if (IS_DEAD(this)) \
        { \
            this.impulse = IMP_weapon_byid_##i.impulse; \
            return; \
        } \
        W_SwitchWeapon(Weapons_from(WEP_FIRST + i)); \
    }
Impulse map:
0 reserved (no input)
99: loaded
140: moving clone 141: ctf speedrun 142: fixed clone 143: emergency teleport 148: unfairly eliminate
TODO: 200 to 209: prev weapon shortcuts 210 to 219: best weapon shortcuts 220 to 229: next weapon shortcuts 230 to 253: individual weapons (up to 24)
Definition at line 56 of file cl_impulse.qc.
#define X (id) case IMP_##id.impulse:
Impulse map:
0 reserved (no input)
99: loaded
140: moving clone 141: ctf speedrun 142: fixed clone 143: emergency teleport 148: unfairly eliminate
TODO: 200 to 209: prev weapon shortcuts 210 to 219: best weapon shortcuts 220 to 229: next weapon shortcuts 230 to 253: individual weapons (up to 24)
Definition at line 56 of file cl_impulse.qc.
Function Documentation
IMPULSE (weapon_prev_byid)
Definition at line 178 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_PreviousWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_byid.impulse;
         return;
     }
     W_PreviousWeapon(0);
 }
IMPULSE (weapon_next_bygroup)
Definition at line 189 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_NextWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_bygroup.impulse;
         return;
     }
     W_NextWeapon(1);
 }
IMPULSE (weapon_prev_bygroup)
Definition at line 200 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_PreviousWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_bygroup.impulse;
         return;
     }
     W_PreviousWeapon(1);
 }
IMPULSE (weapon_next_bypriority)
Definition at line 211 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_NextWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_bypriority.impulse;
         return;
     }
     W_NextWeapon(2);
 }
IMPULSE (weapon_prev_bypriority)
Definition at line 222 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_PreviousWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_prev_bypriority.impulse;
         return;
     }
     W_PreviousWeapon(2);
 }
IMPULSE (weapon_last)
Definition at line 233 of file cl_impulse.qc.
References IS_DEAD, vehicle, and W_LastWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     W_LastWeapon(this);
 }
IMPULSE (weapon_best)
Definition at line 240 of file cl_impulse.qc.
References IS_DEAD, vehicle, w_getbestweapon, and W_SwitchWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     W_SwitchWeapon(w_getbestweapon(this));
 }
IMPULSE (weapon_drop)
Definition at line 247 of file cl_impulse.qc.
References IS_DEAD, v_forward, vehicle, velocity, W_CalculateProjectileVelocity(), and W_ThrowWeapon().
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     W_ThrowWeapon(W_CalculateProjectileVelocity(this.velocity, v_forward * 750, false), '0 0 0', true);
 }
IMPULSE (weapon_reload)
Definition at line 254 of file cl_impulse.qc.
References entity(), forbidWeaponUse(), IS_DEAD, PS(), vehicle, and weaponentities.
 {
     if (this.vehicle) return;
     if (IS_DEAD(this)) return;
     if (forbidWeaponUse(this)) return;
     Weapon w = PS(this).m_weapon;
     entity actor = this;
     .entity weaponentity = weaponentities[0]; // TODO: unhardcode
     w.wr_reload(w, actor, weaponentity);
 }
IMPULSE (use)
Definition at line 374 of file cl_impulse.qc.
References PlayerUseKey().
 {
     PlayerUseKey();
 }
IMPULSE (waypoint_personal_here)
Definition at line 379 of file cl_impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, this.origin, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at location\n");
 }
IMPULSE (waypoint_personal_crosshair)
Definition at line 386 of file cl_impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace().
 {
     WarpZone_crosshair_trace(this);
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, trace_endpos, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at crosshair\n");
 }
IMPULSE (waypoint_personal_death)
Definition at line 394 of file cl_impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployPersonal(WP_Waypoint, this.death_origin, RADARICON_WAYPOINT);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "personal waypoint spawned at death location\n");
 }
IMPULSE (waypoint_here_follow)
Definition at line 402 of file cl_impulse.qc.
References entity(), IS_DEAD, MUTATOR_CALLHOOK, sprint(), and teamplay.
 {
     if (!teamplay) return;
     if (IS_DEAD(this)) return;
     if (!MUTATOR_CALLHOOK(HelpMePing, this))
     {
         entity wp = WaypointSprite_Attach(WP_Helpme, true, RADARICON_HELPME);
         if (!wp) WaypointSprite_HelpMePing(this.waypointsprite_attachedforcarrier);
         else WaypointSprite_Ping(wp);
     }
     sprint(this, "HELP ME attached\n");
 }
IMPULSE (waypoint_here_here)
Definition at line 415 of file cl_impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, this.origin, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at location\n");
 }
IMPULSE (waypoint_here_crosshair)
Definition at line 422 of file cl_impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace().
 {
     WarpZone_crosshair_trace(this);
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, trace_endpos, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at crosshair\n");
 }
IMPULSE (waypoint_here_death)
Definition at line 430 of file cl_impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployFixed(WP_Here, false, this.death_origin, RADARICON_HERE);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "HERE spawned at death location\n");
 }
IMPULSE (waypoint_danger_here)
Definition at line 438 of file cl_impulse.qc.
References entity(), origin, and sprint().
 {
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, this.origin, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at location\n");
 }
IMPULSE (waypoint_danger_crosshair)
Definition at line 445 of file cl_impulse.qc.
References entity(), sprint(), trace_endpos, and WarpZone_crosshair_trace().
 {
     WarpZone_crosshair_trace(this);
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, trace_endpos, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at crosshair\n");
 }
IMPULSE (waypoint_danger_death)
Definition at line 453 of file cl_impulse.qc.
References death_origin, entity(), and sprint().
 {
     if (!this.death_origin) return;
     entity wp = WaypointSprite_DeployFixed(WP_Danger, false, this.death_origin, RADARICON_DANGER);
     if (wp) WaypointSprite_Ping(wp);
     sprint(this, "DANGER spawned at death location\n");
 }
IMPULSE (waypoint_clear_personal)
Definition at line 461 of file cl_impulse.qc.
References NULL, personal, and sprint().
 {
     WaypointSprite_ClearPersonal();
     if (this.personal)
     {
         remove(this.personal);
         this.personal = NULL;
     }
     sprint(this, "personal waypoint cleared\n");
 }
IMPULSE (waypoint_clear)
Definition at line 472 of file cl_impulse.qc.
References NULL, personal, and sprint().
 {
     WaypointSprite_ClearOwned();
     if (this.personal)
     {
         remove(this.personal);
         this.personal = NULL;
     }
     sprint(this, "all waypoints cleared\n");
 }
IMPULSE (navwaypoint_spawn)
Definition at line 483 of file cl_impulse.qc.
References autocvar_g_waypointeditor, bprint(), origin, strcat(), vtos(), waypoint_schedulerelink(), and waypoint_spawn().
 {
     if (!autocvar_g_waypointeditor) return;
     waypoint_schedulerelink(waypoint_spawn(this.origin, this.origin, 0));
     bprint(strcat("Waypoint spawned at ", vtos(this.origin), "\n"));
 }
IMPULSE (navwaypoint_remove)
Definition at line 490 of file cl_impulse.qc.
References autocvar_g_waypointeditor, bprint(), entity(), navigation_findnearestwaypoint(), strcat(), vtos(), waypoint_remove(), and WAYPOINTFLAG_GENERATED.
 {
     if (!autocvar_g_waypointeditor) return;
     entity e = navigation_findnearestwaypoint(this, false);
     if (!e) return;
     if (e.wpflags & WAYPOINTFLAG_GENERATED) return;
     bprint(strcat("Waypoint removed at ", vtos(e.origin), "\n"));
     waypoint_remove(e);
 }
IMPULSE (navwaypoint_relink)
Definition at line 500 of file cl_impulse.qc.
References autocvar_g_waypointeditor, and waypoint_schedulerelinkall().
 {
     if (!autocvar_g_waypointeditor) return;
     waypoint_schedulerelinkall();
 }
IMPULSE (navwaypoint_save)
Definition at line 506 of file cl_impulse.qc.
References autocvar_g_waypointeditor, and waypoint_saveall().
 {
     if (!autocvar_g_waypointeditor) return;
     waypoint_saveall();
 }
IMPULSE (navwaypoint_unreachable)
Definition at line 512 of file cl_impulse.qc.
References autocvar_g_waypointeditor, classname, EF_BLUE, EF_NODEPTHTEST, EF_RED, entity(), etos(), findchainflags(), FL_ITEM, flags, frame, LOG_INFO, LOG_INFOF, model, MOVE_NOMONSTERS, navigation_findnearestwaypoint(), navigation_markroutes(), navigation_markroutes_inverted(), NULL, skin, STAT(), trace_endpos, vector(), vtos(), and world.
 {
     if (!autocvar_g_waypointeditor) return;
     for (entity e = findchain(classname, "waypoint"); e; e = e.chain)
     {
         e.colormod = '0.5 0.5 0.5';
         e.effects &= ~(EF_NODEPTHTEST | EF_RED | EF_BLUE);
     }
     entity e2 = navigation_findnearestwaypoint(this, false);
     navigation_markroutes(e2);
     int i, m;
     i = 0;
     m = 0;
     for (entity e = findchain(classname, "waypoint"); e; e = e.chain)
     {
         if (e.wpcost < 10000000) continue;
         LOG_INFO("unreachable: ", etos(e), " ", vtos(e.origin), "\n");
         e.colormod_z = 8;
         e.effects |= EF_NODEPTHTEST | EF_BLUE;
         ++i;
         ++m;
     }
     if (i) LOG_INFOF("%d waypoints cannot be reached from here in any way (marked with blue light)\n", i);
     navigation_markroutes_inverted(e2);
     i = 0;
     for (entity e = findchain(classname, "waypoint"); e; e = e.chain)
     {
         if (e.wpcost < 10000000) continue;
         LOG_INFO("cannot reach me: ", etos(e), " ", vtos(e.origin), "\n");
         e.colormod_x = 8;
         if (!(e.effects & EF_NODEPTHTEST))  // not already reported before
             ++m;
         e.effects |= EF_NODEPTHTEST | EF_RED;
         ++i;
     }
     if (i) LOG_INFOF("%d waypoints cannot walk to here in any way (marked with red light)\n", i);
     if (m) LOG_INFOF("%d waypoints have been marked total\n", m);
     i = 0;
     for (entity e = findchain(classname, "info_player_deathmatch"); e; e = e.chain)
     {
         vector org = e.origin;
         tracebox(e.origin, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL), e.origin - '0 0 512', MOVE_NOMONSTERS, world);
         setorigin(e, trace_endpos);
         if (navigation_findnearestwaypoint(e, false))
         {
             setorigin(e, org);
             e.effects &= ~EF_NODEPTHTEST;
             e.model = "";
         }
         else
         {
             setorigin(e, org);
             LOG_INFO("spawn without waypoint: ", etos(e), " ", vtos(e.origin), "\n");
             e.effects |= EF_NODEPTHTEST;
             _setmodel(e, this.model);
             e.frame = this.frame;
             e.skin = this.skin;
             e.colormod = '8 0.5 8';
             setsize(e, '0 0 0', '0 0 0');
             ++i;
         }
     }
     if (i) LOG_INFOF("%d spawnpoints have no nearest waypoint (marked by player model)\n", i);
     i = 0;
     entity start = findchainflags(flags, FL_ITEM);
     for (entity e = start; e; e = e.chain)
     {
         e.effects &= ~(EF_NODEPTHTEST | EF_RED | EF_BLUE);
         e.colormod = '0.5 0.5 0.5';
     }
     for (entity e = start; e; e = e.chain)
     {
         if (navigation_findnearestwaypoint(e, false)) continue;
         LOG_INFO("item without waypoint: ", etos(e), " ", vtos(e.origin), "\n");
         e.effects |= EF_NODEPTHTEST | EF_RED;
         e.colormod_x = 8;
         ++i;
     }
     if (i) LOG_INFOF("%d items have no nearest waypoint and cannot be walked away from (marked with red light)\n", i);
     i = 0;
     for (entity e = start; e; e = e.chain)
     {
         if (navigation_findnearestwaypoint(e, true)) continue;
         LOG_INFO("item without waypoint: ", etos(e), " ", vtos(e.origin), "\n");
         e.effects |= EF_NODEPTHTEST | EF_BLUE;
         e.colormod_z = 8;
         ++i;
     }
     if (i) LOG_INFOF("%d items have no nearest waypoint and cannot be walked to (marked with blue light)\n", i);
 }
void ImpulseCommands (entity this)
Definition at line 265 of file cl_impulse.qc.
References CheatImpulse(), entity(), FOREACH, gameover, if(), impulse, MinigameImpulse(), round_handler_IsActive, round_handler_IsRoundStarted, TIMEOUT_ACTIVE, timeout_status, vehicle_impulse(), and X.
Referenced by PlayerPostThink().
 {
     if (gameover) return;
     int imp = this.impulse;
     if (!imp) return;
     this.impulse = 0;
     if (MinigameImpulse(this, imp)) return;
     if (timeout_status == TIMEOUT_ACTIVE) return;  // don't allow any impulses while the game is paused
     // allow only weapon change impulses when not in round time
     if (round_handler_IsActive() && !round_handler_IsRoundStarted())
     {
         #define X(id) case IMP_##id.impulse:
         switch (imp)
         {
             X(weapon_group_0)
             X(weapon_group_1)
             X(weapon_group_2)
             X(weapon_group_3)
             X(weapon_group_4)
             X(weapon_group_5)
             X(weapon_group_6)
             X(weapon_group_7)
             X(weapon_group_8)
             X(weapon_group_9)
             X(weapon_next_byid)
             X(weapon_prev_byid)
             X(weapon_next_bygroup)
             X(weapon_prev_bygroup)
             X(weapon_next_bypriority)
             X(weapon_prev_bypriority)
             X(weapon_last)
             X(weapon_best)
             X(weapon_reload)
             X(weapon_priority_0_prev)
             X(weapon_priority_1_prev)
             X(weapon_priority_2_prev)
             X(weapon_priority_3_prev)
             X(weapon_priority_4_prev)
             X(weapon_priority_5_prev)
             X(weapon_priority_6_prev)
             X(weapon_priority_7_prev)
             X(weapon_priority_8_prev)
             X(weapon_priority_9_prev)
             X(weapon_priority_0_next)
             X(weapon_priority_1_next)
             X(weapon_priority_2_next)
             X(weapon_priority_3_next)
             X(weapon_priority_4_next)
             X(weapon_priority_5_next)
             X(weapon_priority_6_next)
             X(weapon_priority_7_next)
             X(weapon_priority_8_next)
             X(weapon_priority_9_next)
             X(weapon_priority_0_best)
             X(weapon_priority_1_best)
             X(weapon_priority_2_best)
             X(weapon_priority_3_best)
             X(weapon_priority_4_best)
             X(weapon_priority_5_best)
             X(weapon_priority_6_best)
             X(weapon_priority_7_best)
             X(weapon_priority_8_best)
             X(weapon_priority_9_best)
             X(weapon_byid_0)
             X(weapon_byid_1)
             X(weapon_byid_2)
             X(weapon_byid_3)
             X(weapon_byid_4)
             X(weapon_byid_5)
             X(weapon_byid_6)
             X(weapon_byid_7)
             X(weapon_byid_8)
             X(weapon_byid_9)
             X(weapon_byid_10)
             X(weapon_byid_11)
             X(weapon_byid_12)
             X(weapon_byid_13)
             X(weapon_byid_14)
             X(weapon_byid_15)
             X(weapon_byid_16)
             X(weapon_byid_17)
             X(weapon_byid_18)
             X(weapon_byid_19)
             X(weapon_byid_20)
             X(weapon_byid_21)
             X(weapon_byid_22)
             X(weapon_byid_23)
             break;
             default: return;
         }
 #undef X
     }
     if (vehicle_impulse(this, imp)) return;
     if (CheatImpulse(imp)) return;
     FOREACH(IMPULSES, it.impulse == imp, {
         void(entity) f = it.impulse_handle;
         if (!f) continue;
         f(this);
         return;
     });
 }
X (1)
prev X (1 , prev)
prev prev X (3 , prev)
prev prev prev X (5 , prev)
prev prev prev prev X (7 , prev)
prev prev prev prev prev X (9 , prev)
prev prev prev prev prev best X (1 , best)
prev prev prev prev prev best best X (3 , best)
prev prev prev prev prev best best best X (5 , best)
prev prev prev prev prev best best best best X (7 , best)
prev prev prev prev prev best best best best best X (9 , best)
prev prev prev prev prev best best best best best next X (1 , next)
prev prev prev prev prev best best best best best next next X (3 , next)
prev prev prev prev prev best best best best best next next next X (5 , next)
prev prev prev prev prev best best best best best next next next next X (7 , next)
prev prev prev prev prev best best best best best next next next next next X (9 , next)
Definition at line 125 of file cl_impulse.qc.
References impulse, IS_DEAD, vehicle, and W_NextWeapon().
     { \
         if (this.vehicle) return; \
         if (IS_DEAD(this)) \
         { \
             this.impulse = IMP_weapon_byid_##i.impulse; \
             return; \
         } \
         W_SwitchWeapon(Weapons_from(WEP_FIRST + i)); \
     }
 X(0)
 X(1)
 X(2)
 X(3)
 X(4)
 X(5)
 X(6)
 X(7)
 X(8)
 X(9)
 X(10)
 X(11)
 X(12)
 X(13)
 X(14)
 X(15)
 X(16)
 X(17)
 X(18)
 X(19)
 X(20)
 X(21)
 X(22)
 X(23)
 #undef X
 IMPULSE(weapon_next_byid)
 {
     if (this.vehicle) return;
     if (IS_DEAD(this))
     {
         this.impulse = IMP_weapon_next_byid.impulse;
         return;
     }
     W_NextWeapon(0);
 }
Variable Documentation
entity vehicle
Definition at line 23 of file cl_impulse.qc.
Referenced by ClientDisconnect(), ClientKill_Now(), FireGrapplingHook(), IMPULSE(), player_regen(), PlayerPreThink(), PlayerUseKey(), PutObserverInServer(), vehicle_impulse(), and X().