Xonotic: client/csqcmodel_hooks.qc File Reference
client/csqcmodel_hooks.qc File Reference
#include "mutators/events.qh"
#include "player_skeleton.qh"
#include "weapons/projectile.qh"
#include <common/animdecide.qh>
#include <common/physics/movetypes/movetypes.qh>
#include <common/viewloc.qh>
#include <lib/csqcmodel/cl_model.qh>
#include <lib/csqcmodel/cl_player.qh>
#include <lib/csqcmodel/interpolate.qh>
Defines
#define IS_DEAD_FRAME(f) ((f) == 0 || (f) == 1)
#define FIX_FRAMETIME(f, ft)
Functions
void CSQCModel_Hook_PreDraw (entity this, bool isplayer)
void CSQCPlayer_LOD_Apply (entity this)
void CSQCPlayer_ModelAppearance_PreUpdate (entity this)
void CSQCPlayer_ModelAppearance_PostUpdate (entity this)
void CSQCPlayer_ModelAppearance_Apply (entity this, bool islocalplayer)
void CSQCPlayer_FallbackFrame_PreUpdate (entity this)
void CSQCPlayer_FallbackFrame_PostUpdate (entity this, bool isnew)
void CSQCPlayer_AnimDecide_PostUpdate (entity this, bool isnew)
int CSQCPlayer_FallbackFrame (entity this, int f)
void CSQCPlayer_FallbackFrame_Apply (entity this)
void CSQCModel_AutoTagIndex_Apply (entity this)
void CSQCModel_Effects_PreUpdate (entity this)
void Reset_ArcBeam ()
void CSQCModel_Effects_PostUpdate (entity this)
void CSQCModel_Effects_Apply (entity this)
void CSQCModel_Hook_PreUpdate (entity this, bool isnew, bool isplayer, bool islocalplayer)
void CSQCModel_Hook_PostUpdate (entity this, bool isnew, bool isplayer, bool islocalplayer)
Variables
float death_time
int modelflags
bool isplayermodel
int lodmodelindex0
int lodmodelindex1
int lodmodelindex2
string forceplayermodels_model
bool forceplayermodels_modelisgoodmodel
int forceplayermodels_modelindex
int forceplayermodels_skin
string forceplayermodels_mymodel
bool forceplayermodels_myisgoodmodel
int forceplayermodels_mymodelindex
bool forceplayermodels_attempted
string forceplayermodels_savemodel
int forceplayermodels_savemodelindex
int forceplayermodels_saveskin
int forceplayermodels_savecolormap
string forceplayermodels_isgoodmodel_mdl
bool forceplayermodels_isgoodmodel
string forceplayermodels_goodmodel
int forceplayermodels_goodmodelindex
vector glowmod
vector old_glowmod
int csqcmodel_saveframe
int csqcmodel_saveframe2
int csqcmodel_framecount
entity tag_entity
int tag_entity_lastmodelindex
int tag_index
const int EF_BRIGHTFIELD = BIT(0)
const int EF_BRIGHTLIGHT = BIT(2)
const int EF_DIMLIGHT = BIT(3)
const int EF_DOUBLESIDED = BIT(15)
const int EF_NOSELFSHADOW = BIT(16)
const int EF_DYNAMICMODELLIGHT = BIT(17)
const int EF_RESTARTANIM_BIT = BIT(20)
const int EF_TELEPORT_BIT = BIT(21)
const int MF_ROCKET = BIT(0)
const int MF_GRENADE = BIT(1)
const int MF_GIB = BIT(2)
const int MF_ROTATE = BIT(3)
const int MF_TRACER = BIT(4)
const int MF_ZOMGIB = BIT(5)
const int MF_TRACER2 = BIT(6)
const int MF_TRACER3 = BIT(7)
int csqcmodel_effects
int csqcmodel_modelflags
int csqcmodel_traileffect
int snd_looping
int csqcmodel_predraw_run
int anim_frame
int anim_frame1time
int anim_frame2
int anim_frame2time
int anim_saveframe
int anim_saveframe1time
int anim_saveframe2
int anim_saveframe2time
int anim_prev_pmove_flags
Define Documentation
#define FIX_FRAMETIME (f, ft)
Value:
MACRO_BEGIN {                                                                           \
        if(IS_DEAD_FRAME(this.f) && this.ft != 0 && this.death_time != 0)                                           \
            this.ft = this.death_time;                                                                              \
} MACRO_END
Referenced by CSQCPlayer_FallbackFrame_PostUpdate().
#define IS_DEAD_FRAME (f) ((f) == 0 || (f) == 1)
Definition at line 313 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_FallbackFrame_PostUpdate().
Function Documentation
void CSQCModel_AutoTagIndex_Apply (entity this)
Definition at line 387 of file csqcmodel_hooks.qc.
References CSQCModel_Hook_PreDraw(), drawmask, entnum, findfloat(), gettagindex, LOG_TRACE(), maxclients, model, MUTATOR_CALLHOOK, skeleton_loadinfo(), substring(), tag_entity, tag_entity_lastmodelindex, tag_index, and world.
Referenced by CSQCModel_Hook_PreDraw().
{
    if(this.tag_entity && wasfreed(this.tag_entity))
        this.tag_entity = world;
    viewloc_SetTags(this);
    MUTATOR_CALLHOOK(TagIndex_Update, this);
    if(this.tag_networkentity)
    {
        // we are ATTACHED!
        bool changed = 0;
        if(this.tag_entity.entnum != this.tag_networkentity)
        {
            this.tag_entity = findfloat(world, entnum, this.tag_networkentity);
            changed = 1;
        }
        // recursive predraw call to fix issues with forcemodels and LOD if bone indexes mismatch
        if(this.tag_entity.classname == "csqcmodel")
        {
            CSQCModel_Hook_PreDraw(this.tag_entity, (this.entnum >= 1 && this.entnum <= maxclients));
        }
        if(this.tag_entity.modelindex != this.tag_entity_lastmodelindex)
        {
            this.tag_entity_lastmodelindex = this.tag_entity.modelindex;
            changed = 1;
        }
        if(changed)
        {
            if(this.tag_entity)
            {
                // the best part is: IT EXISTS
                if(substring(this.model, 0, 14) == "models/weapons")
                {
                    if(substring(this.tag_entity.model, 0, 14) == "models/weapons")
                    {
                        this.tag_index = gettagindex(this.tag_entity, "weapon");
                        if(!this.tag_index)
                            this.tag_index = gettagindex(this.tag_entity, "tag_weapon");
                        if(!this.tag_index)
{
                            // we need to prevent this from 'appening
                            this.tag_entity = world;
                            this.drawmask = 0;
                            LOG_TRACE("h_ model lacks weapon attachment, but v_ model is attached to it\n");
                        }
                    }
                    else if(this.tag_entity.isplayermodel)
                    {
                        skeleton_loadinfo(this.tag_entity);
                        this.tag_index = this.tag_entity.bone_weapon;
                    }
                }
                if(substring(this.tag_entity.model, 0, 14) == "models/weapons")
                {
                    this.tag_index = gettagindex(this.tag_entity, "shot");
                    if(!this.tag_index)
                        this.tag_index = gettagindex(this.tag_entity, "tag_shot");
                }
                MUTATOR_CALLHOOK(TagIndex_Apply, this);
            }
            else
            {
                // damn, see you next frame
                this.drawmask = 0;
            }
        }
    }
}
void CSQCModel_Effects_Apply (entity this)
Definition at line 505 of file csqcmodel_hooks.qc.
References alpha, angles, autocvar_g_jetpack_attenuation, bound(), CH_TRIGGER_SINGLE, CSQCMODEL_EF_RESPAWNGHOST, csqcmodel_effects, csqcmodel_modelflags, csqcmodel_traileffect, drawmask, EF_ADDITIVE, EF_BLUE, EF_BRIGHTFIELD, EF_BRIGHTLIGHT, EF_DIMLIGHT, EF_DOUBLESIDED, EF_DYNAMICMODELLIGHT, EF_FLAME, EF_FULLBRIGHT, EF_NODEPTHTEST, EF_NODRAW, EF_NOSELFSHADOW, EF_NOSHADOW, EF_RED, EF_STARDUST, effects, fmod(), frametime, MF_GIB, MF_GRENADE, MF_ROCKET, MF_ROTATE, MF_TRACER, MF_TRACER2, MF_TRACER3, MF_ZOMGIB, origin, pointparticles, Projectile_DrawTrail(), Projectile_ResetTrail(), renderflags, RF_ADDITIVE, RF_DEPTHHACK, RF_DYNAMICMODELLIGHT, RF_FULLBRIGHT, RF_NOSHADOW, RF_USEAXIS, snd_looping, sound, time, and VOL_BASE.
Referenced by CSQCModel_Hook_PreDraw(), and viewmodel_draw().
{
    int eff = this.csqcmodel_effects & ~CSQCMODEL_EF_RESPAWNGHOST;
    int tref = this.csqcmodel_traileffect;
    this.renderflags &= ~(RF_DEPTHHACK | RF_ADDITIVE | RF_FULLBRIGHT | EF_NOSHADOW | RF_USEAXIS);
    this.effects = 0;
    this.traileffect = 0;
    if(eff & EF_BRIGHTFIELD)
        tref = EFFECT_TR_NEXUIZPLASMA.m_id;
    // ignoring EF_MUZZLEFLASH
    if(eff & EF_BRIGHTLIGHT)
        adddynamiclight(this.origin, 400, '3 3 3');
    if(eff & EF_DIMLIGHT)
        adddynamiclight(this.origin, 200, '1.5 1.5 1.5');
    if((eff & EF_NODRAW) || (this.alpha < 0))
        this.drawmask = 0;
    if(eff & EF_ADDITIVE)
        this.renderflags |= RF_ADDITIVE;
    if(eff & EF_BLUE)
        adddynamiclight(this.origin, 200, '0.15 0.15 1.5');
    if(eff & EF_RED)
        adddynamiclight(this.origin, 200, '1.5 0.15 0.15');
    // ignoring EF_NOGUNBOB
    if(eff & EF_FULLBRIGHT)
        this.renderflags |= RF_FULLBRIGHT;
    if(eff & EF_FLAME)
        pointparticles(EFFECT_EF_FLAME, this.origin, '0 0 0', bound(0, frametime, 0.1));
    if(eff & EF_STARDUST)
        pointparticles(EFFECT_EF_STARDUST, this.origin, '0 0 0', bound(0, frametime, 0.1));
    if(eff & EF_NOSHADOW)
        this.renderflags |= RF_NOSHADOW;
    if(eff & EF_NODEPTHTEST)
        this.renderflags |= RF_DEPTHHACK;
    // ignoring EF_SELECTABLE
    if(eff & EF_DOUBLESIDED)
        this.effects |= EF_DOUBLESIDED;
    if(eff & EF_NOSELFSHADOW)
        this.effects |= EF_NOSELFSHADOW;
    if(eff & EF_DYNAMICMODELLIGHT)
        this.renderflags |= RF_DYNAMICMODELLIGHT;
    // ignoring EF_UNUSED18, EF_UNUSED19, EF_RESTARTANIM_BIT, EF_TELEPORT_BIT, EF_LOWPRECISION
    if(this.csqcmodel_modelflags & MF_ROCKET)
        tref = EFFECT_TR_ROCKET.m_id;
    if(this.csqcmodel_modelflags & MF_GRENADE)
        tref = EFFECT_TR_GRENADE.m_id;
    if(this.csqcmodel_modelflags & MF_GIB)
        tref = EFFECT_TR_BLOOD.m_id;
    if(this.csqcmodel_modelflags & MF_ROTATE)
    {
        this.renderflags |= RF_USEAXIS;
        makevectors(this.angles + '0 100 0' * fmod(time, 3.6));
    }
    if(this.csqcmodel_modelflags & MF_TRACER)
        tref = EFFECT_TR_WIZSPIKE.m_id;
    if(this.csqcmodel_modelflags & MF_ZOMGIB)
        tref = EFFECT_TR_SLIGHTBLOOD.m_id;
    if(this.csqcmodel_modelflags & MF_TRACER2)
        tref = EFFECT_TR_KNIGHTSPIKE.m_id;
    if(this.csqcmodel_modelflags & MF_TRACER3)
        tref = EFFECT_TR_VORESPIKE.m_id;
    this.traileffect = tref;
    if(this.drawmask)
        Projectile_DrawTrail(this, this.origin);
    else
        Projectile_ResetTrail(this, this.origin);
    if(this.csqcmodel_effects & CSQCMODEL_EF_RESPAWNGHOST)
        this.renderflags |= RF_ADDITIVE;
        // also special in CSQCPlayer_GlowMod_Apply
    if(this.csqcmodel_modelflags & MF_ROCKET)
    {
        if(!this.snd_looping)
        {
            sound(this, CH_TRIGGER_SINGLE, SND_JETPACK_FLY, VOL_BASE, autocvar_g_jetpack_attenuation);
            this.snd_looping = CH_TRIGGER_SINGLE;
        }
    }
    else
    {
        if(this.snd_looping)
        {
            sound(this, this.snd_looping, SND_Null, VOL_BASE, autocvar_g_jetpack_attenuation);
            this.snd_looping = 0;
        }
    }
}
void CSQCModel_Effects_PostUpdate (entity this)
Definition at line 489 of file csqcmodel_hooks.qc.
References csqcmodel_effects, csqcmodel_modelflags, csqcmodel_teleported, csqcmodel_traileffect, csqcplayer, effects, modelflags, origin, Projectile_ResetTrail(), and Reset_ArcBeam().
Referenced by CSQCModel_Hook_PostUpdate().
{
    if (this == csqcplayer) {
        if (this.csqcmodel_teleported) {
            Reset_ArcBeam();
        }
    }
    this.csqcmodel_effects = this.effects;
    this.csqcmodel_modelflags = this.modelflags;
    this.csqcmodel_traileffect = this.traileffect;
    this.effects = 0;
    this.modelflags = 0;
    if(this.csqcmodel_teleported)
        Projectile_ResetTrail(this, this.origin);
}
void CSQCModel_Effects_PreUpdate (entity this)
Definition at line 482 of file csqcmodel_hooks.qc.
References csqcmodel_effects, csqcmodel_modelflags, csqcmodel_traileffect, effects, and modelflags.
Referenced by CSQCModel_Hook_PreUpdate().
{
    this.effects = this.csqcmodel_effects;
    this.modelflags = this.csqcmodel_modelflags;
    this.traileffect = this.csqcmodel_traileffect;
}
void CSQCModel_Hook_PostUpdate (entity this, bool isnew, bool isplayer, bool islocalplayer)
Definition at line 721 of file csqcmodel_hooks.qc.
References CSQCModel_Effects_PostUpdate(), CSQCPlayer_AnimDecide_PostUpdate(), CSQCPlayer_FallbackFrame_PostUpdate(), CSQCPlayer_ModelAppearance_PostUpdate(), entnum, isplayermodel, maxclients, model, and substring().
{
    // is it a player model? (shared state)
    this.isplayermodel = (substring(this.model, 0, 14) == "models/player/" || substring(this.model, 0, 17) == "models/ok_player/" || (substring(this.model, 0, 16) == "models/monsters/" && (this.entnum >= 1 && this.entnum <= maxclients)));
    // save values set by server
    if(this.isplayermodel)
    {
        CSQCPlayer_ModelAppearance_PostUpdate(this);
        if(isplayer)
            CSQCPlayer_AnimDecide_PostUpdate(this, isnew);
        else
            CSQCPlayer_FallbackFrame_PostUpdate(this, isnew);
    }
    CSQCModel_Effects_PostUpdate(this);
}
void CSQCModel_Hook_PreDraw (entity this, bool isplayer)
Definition at line 608 of file csqcmodel_hooks.qc.
References anim_frame, anim_frame1time, anim_frame2, anim_frame2time, anim_prev_pmove_flags, anim_saveframe, anim_saveframe1time, anim_saveframe2, anim_saveframe2time, anim_state, animdecide_load_if_needed(), animdecide_setframes(), animdecide_setimplicitstate(), animdecide_setstate(), ANIMSTATE_DUCK, CSQCModel_AutoTagIndex_Apply(), CSQCModel_Effects_Apply(), CSQCModel_InterpolateAnimation_2To4_Do(), CSQCModel_InterpolateAnimation_2To4_Note(), CSQCModel_InterpolateAnimation_2To4_PreNote(), csqcmodel_isdead, csqcmodel_predraw_run, CSQCMODEL_PROPERTY_FRAME, CSQCMODEL_PROPERTY_FRAME2, CSQCMODEL_PROPERTY_LERPFRAC, csqcplayer, CSQCPlayer_FallbackFrame_Apply(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), drawmask, entnum, FL_DUCKED, flags, frame, frame1time, frame2, frame2time, framecount, free_skeleton_from_frames(), IS_ONGROUND, isplayermodel, lerpfrac, lerpfrac4, MASK_NORMAL, maxs, mins, model, modelindex, MOVE_NORMAL, origin, player_localnum, skeleton_from_frames(), skeleton_loadinfo(), trace_fraction, and trace_startsolid.
Referenced by CSQCModel_AutoTagIndex_Apply().
{
    if(this.csqcmodel_predraw_run == framecount)
        return;
    this.csqcmodel_predraw_run = framecount;
    if(!this.modelindex || this.model == "null")
    {
        this.drawmask = 0;
        return;
    }
    else
        this.drawmask = MASK_NORMAL;
    if(this.isplayermodel) // this checks if it's a player MODEL!
    {
        CSQCPlayer_ModelAppearance_Apply(this, this.entnum == player_localnum + 1);
        CSQCPlayer_LOD_Apply(this);
        if(!isplayer)
        {
            skeleton_loadinfo(this);
            bool doblend = (this.bone_upperbody >= 0);
            CSQCPlayer_FallbackFrame_Apply(this);
            if(doblend)
            {
                skeleton_from_frames(this, this.csqcmodel_isdead);
            }
            else
            {
                free_skeleton_from_frames(this);
                // just in case, clear these (we're animating in frame and frame3)
                this.lerpfrac = 0;
                this.lerpfrac4 = 0;
            }
        }
        else
        {
            // we know that frame3 and frame4 fields, used by InterpolateAnimation, are left alone - but that is all we know!
            skeleton_loadinfo(this);
            bool doblend = (this.bone_upperbody >= 0);
            bool onground = 0;
            if(this == csqcplayer)
            {
                if(IS_ONGROUND(this))
                    onground = 1;
                this.anim_prev_pmove_flags = this.flags;
                if(this.flags & FL_DUCKED)
                    animdecide_setstate(this, this.anim_state | ANIMSTATE_DUCK, false);
                else if(this.anim_state & ANIMSTATE_DUCK)
                    animdecide_setstate(this, this.anim_state - ANIMSTATE_DUCK, false);
            }
            else
            {
                tracebox(this.origin + '0 0 1', this.mins, this.maxs, this.origin - '0 0 4', MOVE_NORMAL, this);
                if(trace_startsolid || trace_fraction < 1)
                    onground = 1;
            }
            animdecide_load_if_needed(this);
            animdecide_setimplicitstate(this, onground);
            animdecide_setframes(this, doblend, anim_frame, anim_frame1time, anim_frame2, anim_frame2time);
            int sf = 0;
            if(this.anim_saveframe != this.anim_frame || this.anim_saveframe1time != this.anim_frame1time)
                sf |= CSQCMODEL_PROPERTY_FRAME;
            if(this.anim_saveframe2 != this.anim_frame2 || this.anim_saveframe2time != this.anim_frame2time)
                sf |= CSQCMODEL_PROPERTY_FRAME2;
            this.anim_saveframe = this.anim_frame;
            this.anim_saveframe1time = this.anim_frame1time;
            this.anim_saveframe2 = this.anim_frame2;
            this.anim_saveframe2time = this.anim_frame2time;
            // Note: we always consider lerpfrac "changed", as it uses fixed values every time anyway.
            // This ensures that .frame etc. are always written.
            CSQCModel_InterpolateAnimation_2To4_PreNote(this, sf | CSQCMODEL_PROPERTY_LERPFRAC);
            this.lerpfrac = (doblend ? 0.5 : 0);
            this.frame = this.anim_frame;
            this.frame1time = this.anim_frame1time;
            this.frame2 = this.anim_frame2;
            this.frame2time = this.anim_frame2time;
            CSQCModel_InterpolateAnimation_2To4_Note(this, sf | CSQCMODEL_PROPERTY_LERPFRAC, false);
            CSQCModel_InterpolateAnimation_2To4_Do(this);
            if(doblend)
            {
                skeleton_from_frames(this, this.csqcmodel_isdead);
            }
            else
            {
                free_skeleton_from_frames(this);
                // just in case, clear these (we're animating in frame and frame3)
                this.lerpfrac = 0;
                this.lerpfrac4 = 0;
            }
        }
    }
    CSQCModel_AutoTagIndex_Apply(this);
    CSQCModel_Effects_Apply(this);
}
void CSQCModel_Hook_PreUpdate (entity this, bool isnew, bool isplayer, bool islocalplayer)
Definition at line 707 of file csqcmodel_hooks.qc.
References CSQCModel_Effects_PreUpdate(), CSQCPlayer_FallbackFrame_PreUpdate(), CSQCPlayer_ModelAppearance_PreUpdate(), IFLAG_V_ANGLE_X, iflags, and isplayermodel.
{
    // interpolate v_angle
    this.iflags |= IFLAG_V_ANGLE_X;
    // revert to values from server
    CSQCModel_Effects_PreUpdate(this);
    if(this.isplayermodel)
    {
        if(!isplayer)
            CSQCPlayer_FallbackFrame_PreUpdate(this);
        CSQCPlayer_ModelAppearance_PreUpdate(this);
    }
}
void CSQCPlayer_AnimDecide_PostUpdate (entity this, bool isnew)
Definition at line 349 of file csqcmodel_hooks.qc.
References anim_state, ANIMSTATE_DEAD1, ANIMSTATE_DEAD2, boolean, and csqcmodel_isdead.
Referenced by CSQCModel_Hook_PostUpdate().
{
    this.csqcmodel_isdead = boolean(this.anim_state & (ANIMSTATE_DEAD1 | ANIMSTATE_DEAD2));
}
int CSQCPlayer_FallbackFrame (entity this, int f)
Definition at line 353 of file csqcmodel_hooks.qc.
References LOG_INFOF, model, and modelindex.
Referenced by CSQCPlayer_FallbackFrame_Apply().
{
    if(frameduration(this.modelindex, f) > 0)
        return f; // goooooood
    if(frameduration(this.modelindex, 1) <= 0)
        return f; // this is a static model. We can't fix it if we wanted to
    switch(f)
    {
        case 23: return 11; // anim_melee -> anim_shoot
        case 24: return 4; // anim_duckwalkbackwards -> anim_duckwalk
        case 25: return 4; // anim_duckwalkstrafeleft -> anim_duckwalk
        case 26: return 4; // anim_duckwalkstraferight -> anim_duckwalk
        case 27: return 4; // anim_duckwalkforwardright -> anim_duckwalk
        case 28: return 4; // anim_duckwalkforwardleft -> anim_duckwalk
        case 29: return 4; // anim_duckwalkbackright -> anim_duckwalk
        case 30: return 4; // anim_duckwalkbackleft -> anim_duckwalk
    }
    LOG_INFOF("Frame %d missing in model %s, and we have no fallback - FAIL!\n", f, this.model);
    return f;
}
void CSQCPlayer_FallbackFrame_Apply (entity this)
Definition at line 373 of file csqcmodel_hooks.qc.
References CSQCPlayer_FallbackFrame(), frame, frame2, frame3, and frame4.
Referenced by CSQCModel_Hook_PreDraw().
{
    this.frame = CSQCPlayer_FallbackFrame(this, this.frame);
    this.frame2 = CSQCPlayer_FallbackFrame(this, this.frame2);
#ifdef CSQCMODEL_HAVE_TWO_FRAMES
    this.frame3 = CSQCPlayer_FallbackFrame(this, this.frame3);
    this.frame4 = CSQCPlayer_FallbackFrame(this, this.frame4);
#endif
}
void CSQCPlayer_FallbackFrame_PostUpdate (entity this, bool isnew)
Definition at line 323 of file csqcmodel_hooks.qc.
References csqcmodel_isdead, csqcmodel_saveframe, csqcmodel_saveframe2, FIX_FRAMETIME, frame, frame1time, frame2, frame2time, frame3, frame3time, frame4, frame4time, and IS_DEAD_FRAME.
Referenced by CSQCModel_Hook_PostUpdate().
{
    this.csqcmodel_saveframe = this.frame;
    this.csqcmodel_saveframe2 = this.frame2;
#ifdef CSQCMODEL_HAVE_TWO_FRAMES
    this.csqcmodel_saveframe3 = this.frame3;
    this.csqcmodel_saveframe4 = this.frame4;
#endif
    // hack for death animations: set their frametime to zero in case a
    // player "pops in"
    if(isnew)
    {
#define FIX_FRAMETIME(f,ft) MACRO_BEGIN {                                                                           \
        if(IS_DEAD_FRAME(this.f) && this.ft != 0 && this.death_time != 0)                                           \
            this.ft = this.death_time;                                                                              \
} MACRO_END
        FIX_FRAMETIME(frame, frame1time);
        FIX_FRAMETIME(frame2, frame2time);
#ifdef CSQCMODEL_HAVE_TWO_FRAMES
        FIX_FRAMETIME(frame3, frame3time);
        FIX_FRAMETIME(frame4, frame4time);
#endif
    }
    this.csqcmodel_isdead = IS_DEAD_FRAME(this.frame);
}
void CSQCPlayer_FallbackFrame_PreUpdate (entity this)
Definition at line 314 of file csqcmodel_hooks.qc.
References csqcmodel_saveframe, csqcmodel_saveframe2, frame, frame2, frame3, and frame4.
Referenced by CSQCModel_Hook_PreUpdate().
{
    this.frame = this.csqcmodel_saveframe;
    this.frame2 = this.csqcmodel_saveframe2;
#ifdef CSQCMODEL_HAVE_TWO_FRAMES
    this.frame3 = this.csqcmodel_saveframe3;
    this.frame4 = this.csqcmodel_saveframe4;
#endif
}
void CSQCPlayer_LOD_Apply (entity this)
Definition at line 22 of file csqcmodel_hooks.qc.
References autocvar_cl_loddistance1, autocvar_cl_loddistance2, autocvar_cl_playerdetailreduction, bound(), current_viewzoom, fexists(), lodmodelindex0, lodmodelindex1, lodmodelindex2, maxs, mins, model, modelindex, origin, s, strcat(), strlen(), substring(), vector(), view_origin, view_quality, and vlen().
Referenced by CSQCModel_Hook_PreDraw().
{
    // LOD model loading
    if(this.lodmodelindex0 != this.modelindex)
    {
        string modelname = this.model;
        string s;
        vector mi = this.mins;
        vector ma = this.maxs;
        // set modelindex
        this.lodmodelindex0 = this.modelindex;
        this.lodmodelindex1 = this.modelindex;
        this.lodmodelindex2 = this.modelindex;
        // FIXME: this only supports 3-letter extensions
        s = strcat(substring(modelname, 0, strlen(modelname)-4), "_lod1", substring(modelname, -4, 4));
        if(fexists(s))
        {
            precache_model(s);
            _setmodel(this, s);
            if(this.modelindex)
                this.lodmodelindex1 = this.modelindex;
        }
        s = strcat(substring(modelname, 0, strlen(modelname)-4), "_lod2", substring(modelname, -4, 4));
        if(fexists(s))
        {
            precache_model(s);
            _setmodel(this, s);
            if(this.modelindex)
                this.lodmodelindex2 = this.modelindex;
        }
        _setmodel(this, modelname); // make everything normal again
        setsize(this, mi, ma);
    }
    // apply LOD
    if(autocvar_cl_playerdetailreduction <= 0)
    {
        if(autocvar_cl_playerdetailreduction <= -2)
            this.modelindex = this.lodmodelindex2;
        else if(autocvar_cl_playerdetailreduction <= -1)
            this.modelindex = this.lodmodelindex1;
        else
            this.modelindex = this.lodmodelindex0;
    }
    else
    {
        float distance = vlen(this.origin - view_origin);
        float f = (distance * current_viewzoom + 100.0) * autocvar_cl_playerdetailreduction;
        f *= 1.0 / bound(0.01, view_quality, 1);
        if(f > autocvar_cl_loddistance2)
            this.modelindex = this.lodmodelindex2;
        else if(f > autocvar_cl_loddistance1)
            this.modelindex = this.lodmodelindex1;
        else
            this.modelindex = this.lodmodelindex0;
    }
}
void CSQCPlayer_ModelAppearance_Apply (entity this, bool islocalplayer)
Definition at line 133 of file csqcmodel_hooks.qc.
References autocvar__cl_color, autocvar__cl_playermodel, autocvar__cl_playerskin, autocvar_cl_deathglow, autocvar_cl_forcemyplayercolors, autocvar_cl_forcemyplayermodel, autocvar_cl_forcemyplayerskin, autocvar_cl_forceplayercolors, autocvar_cl_forceplayermodels, bound(), colormap, colormapPaletteColor, csqcmodel_isdead, cvar_defstring(), death_time, entity(), fexists(), forceplayermodels_attempted, forceplayermodels_goodmodel, forceplayermodels_goodmodelindex, forceplayermodels_isgoodmodel, forceplayermodels_model, forceplayermodels_modelindex, forceplayermodels_modelisgoodmodel, forceplayermodels_myisgoodmodel, forceplayermodels_mymodel, forceplayermodels_mymodelindex, forceplayermodels_savecolormap, forceplayermodels_savemodel, forceplayermodels_savemodelindex, forceplayermodels_saveskin, forceplayermodels_skin, glowmod, isdemo(), max(), model, modelindex, old_glowmod, player_localnum, skin, spawn(), stof(), team_count, teamplay, teams, and time.
Referenced by CSQCModel_Hook_PreDraw().
{
    // FORCEMODEL
    // which one is ALWAYS good?
    if (!forceplayermodels_goodmodel)
    {
        entity e = spawn();
        precache_model(cvar_defstring("_cl_playermodel"));
        _setmodel(e, cvar_defstring("_cl_playermodel"));
        forceplayermodels_goodmodel = e.model;
        forceplayermodels_goodmodelindex = e.modelindex;
        remove(e);
    }
    // first, try finding it from the server
    if(this.forceplayermodels_savemodelindex && this.forceplayermodels_savemodel != "null")
    {
        if(islocalplayer)
        {
            if(!isdemo()) // this is mainly cheat protection; not needed for demos
            {
                // trust server's idea of "own player model"
                forceplayermodels_modelisgoodmodel = this.forceplayermodels_isgoodmodel;
                forceplayermodels_model = this.forceplayermodels_savemodel;
                forceplayermodels_modelindex = this.forceplayermodels_savemodelindex;
                forceplayermodels_skin = this.forceplayermodels_saveskin;
                forceplayermodels_attempted = 1;
            }
        }
    }
    // forcemodel finding
    if(!forceplayermodels_attempted)
    {
        forceplayermodels_attempted = 1;
        // only if this failed, find it out on our own
        entity e = spawn();
        precache_model(autocvar__cl_playermodel);
        _setmodel(e, autocvar__cl_playermodel); // this is harmless, see below
        forceplayermodels_modelisgoodmodel = fexists(e.model);
        forceplayermodels_model = e.model;
        forceplayermodels_modelindex = e.modelindex;
        forceplayermodels_skin = autocvar__cl_playerskin;
        remove(e);
    }
    if(autocvar_cl_forcemyplayermodel != "" && autocvar_cl_forcemyplayermodel != forceplayermodels_mymodel)
    {
        entity e = spawn();
        _setmodel(e, autocvar_cl_forcemyplayermodel); // this is harmless, see below
        forceplayermodels_myisgoodmodel = fexists(e.model);
        forceplayermodels_mymodel = e.model;
        forceplayermodels_mymodelindex = e.modelindex;
        remove(e);
    }
    // apply it
    bool isfriend;
    int cm;
    cm = this.forceplayermodels_savecolormap;
    cm = (cm >= 1024) ? cm : (stof(getplayerkeyvalue(cm - 1, "colors")) + 1024);
    if(teamplay)
        isfriend = (cm == 1024 + 17 * myteam);
    else
        isfriend = islocalplayer;
    if(autocvar_cl_forcemyplayermodel != "" && forceplayermodels_myisgoodmodel && isfriend)
    {
        this.model = forceplayermodels_mymodel;
        this.modelindex = forceplayermodels_mymodelindex;
        this.skin = autocvar_cl_forcemyplayerskin;
    }
    else if(autocvar_cl_forceplayermodels && forceplayermodels_modelisgoodmodel)
    {
        this.model = forceplayermodels_model;
        this.modelindex = forceplayermodels_modelindex;
        this.skin = forceplayermodels_skin;
    }
    else if(this.forceplayermodels_isgoodmodel)
    {
        this.model = this.forceplayermodels_savemodel;
        this.modelindex = this.forceplayermodels_savemodelindex;
        this.skin = this.forceplayermodels_saveskin;
    }
    else
    {
        this.model = forceplayermodels_goodmodel;
        this.modelindex = forceplayermodels_goodmodelindex;
        this.skin = this.forceplayermodels_saveskin;
    }
    // forceplayercolors too
    if(teamplay)
    {
        // own team's color is never forced
        int forcecolor_friend = 0;
        int forcecolor_enemy = 0;
        entity tm;
        if(autocvar_cl_forcemyplayercolors)
            forcecolor_friend = 1024 + autocvar_cl_forcemyplayercolors;
        if(autocvar_cl_forceplayercolors == 2 && team_count == 2)
            forcecolor_enemy = 1024 + autocvar__cl_color;
        if(forcecolor_enemy && !forcecolor_friend)
        {
            // only enemy color is forced?
            // verify it is not equal to the friend color
            if(forcecolor_enemy == 1024 + 17 * myteam)
                forcecolor_enemy = 0;
        }
        if(forcecolor_friend && !forcecolor_enemy)
        {
            // only friend color is forced?
            // verify it is not equal to the enemy color
            for(tm = teams.sort_next; tm; tm = tm.sort_next)
                // note: we even compare against our own team.
                // if we rejected because we matched our OWN team color,
                // this is not bad; we then simply keep our color as is
                // anyway.
                if(forcecolor_friend == 1024 + 17 * tm.team)
                    forcecolor_friend = 0;
        }
        if(cm == 1024 + 17 * myteam)
        {
            if(forcecolor_friend)
                this.colormap = forcecolor_friend;
        }
        else
        {
            if(forcecolor_enemy)
                this.colormap = forcecolor_enemy;
        }
    }
    else
    {
        if(autocvar_cl_forcemyplayercolors && islocalplayer)
            this.colormap = 1024 + autocvar_cl_forcemyplayercolors;
        else if(autocvar_cl_forceplayercolors)
            this.colormap = player_localnum + 1;
    }
    // GLOWMOD AND DEATH FADING
    if(this.colormap > 0)
        this.glowmod = colormapPaletteColor(((this.colormap >= 1024) ? this.colormap : stof(getplayerkeyvalue(this.colormap - 1, "colors"))) & 0x0F, true) * 2;
    else
        this.glowmod = '1 1 1';
    if(autocvar_cl_deathglow > 0)
    {
        if(this.csqcmodel_isdead)
        {
            // Fade out to black now...
            if(this.old_glowmod == '0 0 0') { this.old_glowmod = this.glowmod; }
            this.colormap = 0;
            this.glowmod = this.old_glowmod * bound(0, 1 - (time - this.death_time) / autocvar_cl_deathglow, 1);
            this.glowmod_x = max(this.glowmod.x, 0.0001);
            this.glowmod_y = max(this.glowmod.y, 0.0001);
            this.glowmod_z = max(this.glowmod.z, 0.0001);
        }
        else if(this.old_glowmod != '0 0 0') { this.old_glowmod = '0 0 0'; }
    }
    //printf("CSQCPlayer_ModelAppearance_Apply(): state = %s, colormap = %f, glowmod = %s\n", (this.csqcmodel_isdead ? "DEAD" : "ALIVE"), this.colormap, vtos(this.glowmod));
}
void CSQCPlayer_ModelAppearance_PostUpdate (entity this)
Definition at line 118 of file csqcmodel_hooks.qc.
References colormap, fexists(), forceplayermodels_isgoodmodel, forceplayermodels_isgoodmodel_mdl, forceplayermodels_savecolormap, forceplayermodels_savemodel, forceplayermodels_savemodelindex, forceplayermodels_saveskin, LOG_INFOF, model, modelindex, and skin.
Referenced by CSQCModel_Hook_PostUpdate().
{
    this.forceplayermodels_savemodel = this.model;
    this.forceplayermodels_savemodelindex = this.modelindex;
    this.forceplayermodels_saveskin = this.skin;
    this.forceplayermodels_savecolormap = this.colormap;
    if(this.forceplayermodels_savemodel != this.forceplayermodels_isgoodmodel_mdl)
    {
        this.forceplayermodels_isgoodmodel = fexists(this.forceplayermodels_savemodel);
        this.forceplayermodels_isgoodmodel_mdl = this.forceplayermodels_savemodel;
        if(!this.forceplayermodels_isgoodmodel)
            LOG_INFOF("Warning: missing model %s has been used\n", this.forceplayermodels_savemodel);
    }
}
void CSQCPlayer_ModelAppearance_PreUpdate (entity this)
Definition at line 111 of file csqcmodel_hooks.qc.
References colormap, forceplayermodels_savecolormap, forceplayermodels_savemodel, forceplayermodels_savemodelindex, forceplayermodels_saveskin, model, modelindex, and skin.
Referenced by CSQCModel_Hook_PreUpdate().
{
    this.model = this.forceplayermodels_savemodel;
    this.modelindex = this.forceplayermodels_savemodelindex;
    this.skin = this.forceplayermodels_saveskin;
    this.colormap = this.forceplayermodels_savecolormap;
}
void Reset_ArcBeam ()
Referenced by CSQCModel_Effects_PostUpdate(), and WarpZone_PostTeleportPlayer_Callback().
Variable Documentation
int anim_frame
Definition at line 599 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_frame1time
Definition at line 600 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_frame2
Definition at line 601 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_frame2time
Definition at line 602 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_prev_pmove_flags
Definition at line 607 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_saveframe
Definition at line 603 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_saveframe1time
Definition at line 604 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_saveframe2
Definition at line 605 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int anim_saveframe2time
Definition at line 606 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int csqcmodel_effects
Definition at line 479 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), CSQCModel_Effects_PostUpdate(), and CSQCModel_Effects_PreUpdate().
int csqcmodel_framecount
Definition at line 311 of file csqcmodel_hooks.qc.
int csqcmodel_modelflags
Definition at line 480 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), CSQCModel_Effects_PostUpdate(), and CSQCModel_Effects_PreUpdate().
int csqcmodel_predraw_run
Definition at line 598 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PreDraw().
int csqcmodel_saveframe
Definition at line 305 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_FallbackFrame_PostUpdate(), and CSQCPlayer_FallbackFrame_PreUpdate().
int csqcmodel_saveframe2
Definition at line 306 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_FallbackFrame_PostUpdate(), and CSQCPlayer_FallbackFrame_PreUpdate().
int csqcmodel_traileffect
Definition at line 481 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), CSQCModel_Effects_PostUpdate(), and CSQCModel_Effects_PreUpdate().
float death_time
Definition at line 11 of file csqcmodel_hooks.qc.
Referenced by CopyBody(), CSQCPlayer_ModelAppearance_Apply(), PlayerDamage(), and PutClientInServer().
const int EF_BRIGHTFIELD = BIT(0)
Definition at line 463 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int EF_BRIGHTLIGHT = BIT(2)
Definition at line 464 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int EF_DIMLIGHT = BIT(3)
Definition at line 465 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), and Monster_Spawn_Setup().
const int EF_DOUBLESIDED = BIT(15)
Definition at line 466 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), vehicle_addplayerslot(), and vehicles_reset_colors().
const int EF_DYNAMICMODELLIGHT = BIT(17)
Definition at line 468 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int EF_NOSELFSHADOW = BIT(16)
Definition at line 467 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int EF_RESTARTANIM_BIT = BIT(20)
Definition at line 469 of file csqcmodel_hooks.qc.
Referenced by anim_set(), animdecide_setframes(), CSQCModel_CheckUpdate(), and PutClientInServer().
const int EF_TELEPORT_BIT = BIT(21)
Definition at line 470 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_CheckUpdate(), Damage(), PutClientInServer(), vehicle_addplayerslot(), vehicles_reset_colors(), and WarpZone_TeleportPlayer().
bool forceplayermodels_attempted
Definition at line 95 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
string forceplayermodels_goodmodel
Definition at line 105 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
int forceplayermodels_goodmodelindex
Definition at line 106 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
bool forceplayermodels_isgoodmodel
Definition at line 103 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply(), and CSQCPlayer_ModelAppearance_PostUpdate().
string forceplayermodels_isgoodmodel_mdl
Definition at line 102 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_PostUpdate().
string forceplayermodels_model
Definition at line 86 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
int forceplayermodels_modelindex
Definition at line 88 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
bool forceplayermodels_modelisgoodmodel
Definition at line 87 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
bool forceplayermodels_myisgoodmodel
Definition at line 92 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
string forceplayermodels_mymodel
Definition at line 91 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
int forceplayermodels_mymodelindex
Definition at line 93 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
int forceplayermodels_savecolormap
Definition at line 100 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), and CSQCPlayer_ModelAppearance_PreUpdate().
string forceplayermodels_savemodel
Definition at line 97 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), and CSQCPlayer_ModelAppearance_PreUpdate().
int forceplayermodels_savemodelindex
Definition at line 98 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), and CSQCPlayer_ModelAppearance_PreUpdate().
int forceplayermodels_saveskin
Definition at line 99 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), and CSQCPlayer_ModelAppearance_PreUpdate().
int forceplayermodels_skin
Definition at line 89 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
vector glowmod
Definition at line 108 of file csqcmodel_hooks.qc.
Referenced by CL_ExteriorWeaponentity_Think(), CopyBody(), cpicon_changeteam(), and CSQCPlayer_ModelAppearance_Apply().
bool isplayermodel
Definition at line 16 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Hook_PostUpdate(), CSQCModel_Hook_PreDraw(), CSQCModel_Hook_PreUpdate(), and CSQCPlayer_SetMinsMaxs().
int lodmodelindex0
Definition at line 19 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_LOD_Apply(), Ent_Wall_Draw(), g_clientmodel_genericsendentity(), and NET_HANDLE().
int lodmodelindex1
Definition at line 20 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_LOD_Apply(), Ent_Wall_Draw(), g_clientmodel_genericsendentity(), LODmodel_attach(), and NET_HANDLE().
int lodmodelindex2
Definition at line 21 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_LOD_Apply(), Ent_Wall_Draw(), g_clientmodel_genericsendentity(), LOD_customize(), and NET_HANDLE().
const int MF_GIB = BIT(2)
Definition at line 473 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int MF_GRENADE = BIT(1)
Definition at line 472 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int MF_ROCKET = BIT(0)
Definition at line 471 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), and player_powerups().
const int MF_ROTATE = BIT(3)
Definition at line 474 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), and spawn_item_key().
const int MF_TRACER = BIT(4)
Definition at line 475 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int MF_TRACER2 = BIT(6)
Definition at line 477 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int MF_TRACER3 = BIT(7)
Definition at line 478 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
const int MF_ZOMGIB = BIT(5)
Definition at line 476 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply().
int modelflags
Definition at line 12 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_PostUpdate(), and CSQCModel_Effects_PreUpdate().
vector old_glowmod
Definition at line 109 of file csqcmodel_hooks.qc.
Referenced by CSQCPlayer_ModelAppearance_Apply().
int snd_looping
Definition at line 504 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_Effects_Apply(), and Ent_Remove().
entity tag_entity
Definition at line 384 of file csqcmodel_hooks.qc.
Referenced by CL_ExteriorWeaponentity_Think(), CSQCModel_AutoTagIndex_Apply(), and vehicles_reset_colors().
int tag_entity_lastmodelindex
Definition at line 385 of file csqcmodel_hooks.qc.
Referenced by CSQCModel_AutoTagIndex_Apply().
int tag_index
Definition at line 386 of file csqcmodel_hooks.qc.
Referenced by CL_ExteriorWeaponentity_Think(), and CSQCModel_AutoTagIndex_Apply().