Xonotic: common/viewloc.qh File Reference
viewloc.qh File Reference
Functions
void viewloc_PlayerPhysics (entity this)
Variables
entity viewloc
Function Documentation
viewloc_PlayerPhysics()
void viewloc_PlayerPhysics (entity this)
Definition at line 13 of file viewloc.qc.
References aim_vec(), angle_snap_f(), angle_snap_vec(), autocvar_vid_conheight, autocvar_vid_conwidth, BIT, CSQCModel_server2csqc(), entity(), entnum, findfloat(), flags, freeze_ang, freeze_org, input_buttons, input_movevalues, LOG_TRACE, max(), min(), MOVE_NOMONSTERS, normalize(), NULL, PHYS_INPUT_BUTTON_CROUCH, player_localentnum, spectatee_status, STATIC_INIT_LATE, trace_endpos, vec2, vec3, vec_bounds_in(), vec_to_max(), vec_to_min(), vectoangles(), vector(), VF_ANGLES, VF_CL_VIEWANGLES, VF_ORIGIN, viewloc, VIEWLOC_CAM_NOANGLE, VIEWLOC_CAM_SNAP_CLOSE, VIEWLOC_CAM_SNAP_HARD, VIEWLOC_CAM_SNAP_UNLOCK, VIEWLOC_CAM_TRACK, VIEWLOC_FREEAIM, VIEWLOC_FREEMOVE, viewloc_mousepos, and vtos().
Referenced by sys_phys_update().
 {
     if(this.viewloc)
     {
         if(this.viewloc.goalentity == this.viewloc.enemy)
             return; // we can't side-scroll in this case
         vector old_movement = PHYS_CS(this).movement;
         PHYS_CS(this).movement_x = old_movement_y;
         if((this.viewloc.spawnflags & VIEWLOC_FREEMOVE) && !this.ladder_entity)
             PHYS_CS(this).movement_y = old_movement_x;
         else
             PHYS_CS(this).movement_y = 0;
         vector level_start, level_end;
         level_start = this.viewloc.enemy.origin;
         level_end = this.viewloc.goalentity.origin;
         vector forward = vectoangles(normalize(level_end - level_start));
         vector backward = vectoangles(normalize(level_start - level_end));
         if((this.viewloc.spawnflags & VIEWLOC_FREEMOVE) && this.angles_y < 0 && !this.ladder_entity)
             PHYS_CS(this).movement_y = -PHYS_CS(this).movement_y;
         if(this.viewloc.spawnflags & VIEWLOC_FREEAIM)
         {
             if(this.angles_y > 0)
                 PHYS_CS(this).movement_x = -PHYS_CS(this).movement_x;
         }
         else
         {
             if(PHYS_CS(this).movement_x < 0)
                 PHYS_CS(this).movement_x = -PHYS_CS(this).movement_x;
             if(PHYS_CS(this).movement_x < 0) // left
                 this.angles_y = backward.y;
             if(PHYS_CS(this).movement_x > 0) // right
                 this.angles_y = forward.y;
         }
     #if 0
         //if(!PHYS_INPUT_BUTTON_CROUCH(this) && !IS_DUCKED(this))
         if(!(this.viewloc.spawnflags & VIEWLOC_FREEMOVE))
         {
 #ifdef SVQC
             //PHYS_INPUT_BUTTON_CROUCH(this) = (old_movement_x < 0);
             if (old_movement.x < 0)
                 PHYS_INPUT_BUTTON_CROUCH(this) = true;
 #elif defined(CSQC)
             if (old_movement.x < 0)
             {
                 input_buttons |= BIT(4);
                 this.flags |= FL_DUCKED;
             }
             //else { input_buttons &= ~16; this.flags &= ~FL_DUCKED; }
 #endif
         }
     #endif
     }
 }
Variable Documentation
viewloc
entity viewloc
Definition at line 5 of file viewloc.qh.