Xonotic: menu/xonotic/soundlist.qh File Reference
soundlist.qh File Reference
#include "listbox.qh"
Classes
class XonoticSoundList
Functions
entity makeXonoticSoundList ()
void SoundList_Add (entity box, entity me)
void SoundList_Add_All (entity box, entity me)
void SoundList_Filter_Change (entity box, entity me)
void SoundList_Menu_Track_Change (entity box, entity me)
void SoundList_Menu_Track_Reset (entity box, entity me)
Function Documentation
entity makeXonoticSoundList ()
Definition at line 6 of file soundlist.qc.
References entity(), and NEW.
Referenced by XonoticMusicPlayerTab_fill().
 {
     entity me;
     me = NEW(XonoticSoundList);
     me.configureXonoticSoundList(me);
     return me;
 }
void SoundList_Add (entity box, entity me)
Definition at line 117 of file soundlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     me.playlist.addToPlayList(me.playlist, me.soundName(me, me.selectedItem));
 }
void SoundList_Add_All (entity box, entity me)
Definition at line 122 of file soundlist.qc.
Referenced by XonoticMusicPlayerTab_fill().
 {
     int i;
     for(i = 0; i < me.nItems; ++i)
         me.playlist.addToPlayList(me.playlist, me.soundName(me, i));
 }
void SoundList_Filter_Change (entity box, entity me)
Definition at line 107 of file soundlist.qc.
References strfree, and strzone().
Referenced by XonoticMusicPlayerTab_fill().
 {
     strfree(me.filterString);
     if(box.text != "")
         me.filterString = strzone(box.text);
     me.getSounds(me);
 }
void SoundList_Menu_Track_Change (entity box, entity me)
Definition at line 97 of file soundlist.qc.
References cvar_set().
Referenced by XonoticMusicPlayerTab_fill().
 {
     cvar_set("menu_cdtrack", me.soundName(me, me.selectedItem));
 }
void SoundList_Menu_Track_Reset (entity box, entity me)
Definition at line 102 of file soundlist.qc.
References cvar_defstring(), and cvar_set().
Referenced by XonoticMusicPlayerTab_fill().
 {
     cvar_set("menu_cdtrack", cvar_defstring("menu_cdtrack"));
 }