Xonotic: client/announcer.qh File Reference
client/announcer.qh File Reference
Defines
#define CLIENT_ANNOUNCER_H
Functions
void Announcer ()
string AnnouncerOption ()
Define Documentation
#define CLIENT_ANNOUNCER_H
Definition at line 2 of file announcer.qh.
Function Documentation
void Announcer ()
Definition at line 161 of file announcer.qc.
References Announcer_Gamestart(), and Announcer_Time().
Referenced by CSQC_UpdateView().
{
    Announcer_Gamestart();
    Announcer_Time();
}
string AnnouncerOption ()
Definition at line 10 of file announcer.qc.
References AnnouncerOption(), autocvar_cl_announcer, MUTATOR_CALLHOOK, and ret_string.
Referenced by AnnouncerOption(), and Create_Notification_Entity().
{
    string ret = autocvar_cl_announcer;
    MUTATOR_CALLHOOK(AnnouncerOption, ret);
    ret = ret_string;
    return ret;
}