Xonotic: server/t_quake3.qc File Reference
t_quake3.qc File Reference
#include "t_quake3.qh"
#include "../common/weapons/all.qh"
Functions
bool DoesQ3ARemoveThisEntity (entity this)
spawnfunc (weapon_crylink)
spawnfunc (weapon_electro)
spawnfunc (weapon_hagar)
spawnfunc (weapon_machinegun)
spawnfunc (weapon_vortex)
spawnfunc (target_items)
spawnfunc (item_bullets)
spawnfunc (item_cells)
spawnfunc (item_rockets)
spawnfunc (item_shells)
spawnfunc (item_jetpack)
spawnfunc (item_armor_big)
spawnfunc (item_armor_large)
spawnfunc (item_armor_small)
spawnfunc (item_health_medium)
spawnfunc (item_health_mega)
spawnfunc (ammo_shells)
spawnfunc (ammo_bullets)
spawnfunc (ammo_grenades)
spawnfunc (weapon_lightning)
spawnfunc (ammo_lightning)
spawnfunc (weapon_plasmagun)
spawnfunc (ammo_cells)
spawnfunc (weapon_railgun)
spawnfunc (ammo_slugs)
spawnfunc (weapon_bfg)
spawnfunc (ammo_bfg)
spawnfunc (ammo_rockets)
spawnfunc (item_armor_body)
spawnfunc (item_armor_combat)
spawnfunc (item_armor_shard)
spawnfunc (item_enviro)
spawnfunc (target_init)
spawnfunc (target_give)
spawnfunc (item_flight)
void target_give_init (entity this)
void target_init_verify (entity this)
Variables
float delay
string gametype
float notfree
float notq3a
float notsingle
float notta
float notteam
float wait
Function Documentation
bool DoesQ3ARemoveThisEntity (entity this)
Definition at line 167 of file t_quake3.qc.
References g_ctf, g_tdm, gametype, maxclients, notfree, notq3a, notsingle, notta, notteam, strstrofs, and teamplay.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     // Q3 style filters (DO NOT USE, THIS IS COMPAT ONLY)
     if(this.notq3a)
         if(!teamplay || g_tdm || g_ctf)
             return true;
     if(this.notta)
         if (!(!teamplay || g_tdm || g_ctf))
             return true;
     if(this.notsingle)
         if(maxclients == 1)
             return true;
     if(this.notteam)
         if(teamplay)
             return true;
     if(this.notfree)
         if(!teamplay)
             return true;
     if(this.gametype)
     {
         string gametypename;
         // static char *gametypeNames[] = {"ffa", "tournament", "single", "team", "ctf", "oneflag", "obelisk", "harvester", "teamtournament"}
         gametypename = "ffa";
         if(teamplay)
             gametypename = "team";
         if(g_ctf)
             gametypename = "ctf";
         if(maxclients == 1)
             gametypename = "single";
         // we do not have the other types (oneflag, obelisk, harvester, teamtournament)
         if(strstrofs(this.gametype, gametypename, 0) < 0)
             return true;
     }
     return false;
 }
spawnfunc (weapon_crylink)
spawnfunc (weapon_electro)
spawnfunc (weapon_hagar)
spawnfunc (weapon_machinegun)
spawnfunc (weapon_vortex)
spawnfunc (target_items)
spawnfunc (item_bullets)
spawnfunc (item_cells)
spawnfunc (item_rockets)
spawnfunc (item_shells)
spawnfunc (item_jetpack)
spawnfunc (item_armor_big)
spawnfunc (item_armor_large)
spawnfunc (item_armor_small)
spawnfunc (item_health_medium)
spawnfunc (item_health_mega)
spawnfunc (ammo_shells)
Definition at line 34 of file t_quake3.qc.
 { spawnfunc_item_shells(this);         }
spawnfunc (ammo_bullets)
Definition at line 37 of file t_quake3.qc.
 { spawnfunc_item_bullets(this);        }
spawnfunc (ammo_grenades)
Definition at line 40 of file t_quake3.qc.
 { spawnfunc_item_rockets(this);        }
spawnfunc (weapon_lightning)
Definition at line 43 of file t_quake3.qc.
 { spawnfunc_weapon_electro(this);      }
spawnfunc (ammo_lightning)
Definition at line 44 of file t_quake3.qc.
 { spawnfunc_item_cells(this);          }
spawnfunc (weapon_plasmagun)
Definition at line 47 of file t_quake3.qc.
 { spawnfunc_weapon_hagar(this);        }
spawnfunc (ammo_cells)
Definition at line 48 of file t_quake3.qc.
 { spawnfunc_item_rockets(this);        }
spawnfunc (weapon_railgun)
Definition at line 51 of file t_quake3.qc.
 { spawnfunc_weapon_vortex(this);          }
spawnfunc (ammo_slugs)
Definition at line 52 of file t_quake3.qc.
 { spawnfunc_item_cells(this);          }
spawnfunc (weapon_bfg)
Definition at line 55 of file t_quake3.qc.
 { spawnfunc_weapon_crylink(this);      }
spawnfunc (ammo_bfg)
Definition at line 56 of file t_quake3.qc.
 { spawnfunc_item_cells(this);          }
spawnfunc (ammo_rockets)
Definition at line 59 of file t_quake3.qc.
 { spawnfunc_item_rockets(this);        }
spawnfunc (item_armor_body)
Definition at line 62 of file t_quake3.qc.
 { spawnfunc_item_armor_large(this);    }
spawnfunc (item_armor_combat)
Definition at line 63 of file t_quake3.qc.
 { spawnfunc_item_armor_big(this);      }
spawnfunc (item_armor_shard)
Definition at line 64 of file t_quake3.qc.
 { spawnfunc_item_armor_small(this);    }
spawnfunc (item_enviro)
Definition at line 65 of file t_quake3.qc.
 { spawnfunc_item_invincible(this);     }
spawnfunc (target_init)
Definition at line 89 of file t_quake3.qc.
References InitializeEntity(), INITPRIO_FINDTARGET, netname, spawnflags, and target_init_verify().
 {
     this.spawnflags = 0; // remove all weapons except the ones listed below
     this.netname = "shotgun"; // keep these weapons through the remove trigger
     spawnfunc_target_items(this);
     InitializeEntity(this, target_init_verify, INITPRIO_FINDTARGET);
 }
spawnfunc (target_give)
Definition at line 140 of file t_quake3.qc.
References InitializeEntity(), INITPRIO_FINDTARGET, and target_give_init().
 {
     InitializeEntity(this, target_give_init, INITPRIO_FINDTARGET);
 }
spawnfunc (item_flight)
Definition at line 156 of file t_quake3.qc.
 {
     spawnfunc_item_jetpack(this);
 }
void target_give_init (entity this)
Definition at line 98 of file t_quake3.qc.
References ammo, ammo_cells, ammo_rockets, armorvalue, entity(), find(), health, InitializeEntity(), INITPRIO_FINDTARGET, netname, NULL, setthink, spawnflags, strcat(), SUB_Remove(), target, target_init_verify(), targetname, time, WEP_CVAR, and WEP_CVAR_PRI.
Referenced by spawnfunc().
 {
     entity targ;
     for (targ = NULL; (targ = find(targ, targetname, this.target)); ) {
         if (targ.classname == "weapon_rocketlauncher" || targ.classname == "weapon_devastator") {
             this.ammo_rockets += targ.count * WEP_CVAR(devastator, ammo);
             this.netname = "devastator";
         }
         else if (targ.classname == "weapon_plasmagun") {
             this.ammo_rockets += targ.count * WEP_CVAR_PRI(hagar, ammo); // WEAPONTODO
             if(this.netname == "")
                 this.netname = "hagar";
             else
                 this.netname = strcat(this.netname, " hagar");
         }
         else if (targ.classname == "weapon_bfg") {
             this.ammo_cells += targ.count * WEP_CVAR_PRI(crylink, ammo);
             if(this.netname == "")
                 this.netname = "crylink";
             else
                 this.netname = strcat(this.netname, " crylink");
         }
         else if (targ.classname == "weapon_grenadelauncher" || targ.classname == "weapon_mortar") {
             this.ammo_rockets += targ.count * WEP_CVAR_PRI(mortar, ammo); // WEAPONTODO
             if(this.netname == "")
                 this.netname = "mortar";
             else
                 this.netname = strcat(this.netname, " mortar");
         }
         else if (targ.classname == "item_armor_body")
             this.armorvalue = 100;
         else if (targ.classname == "item_health_mega")
             this.health = 200;
         //remove(targ); // removing ents in init functions causes havoc, workaround:
         setthink(targ, SUB_Remove);
         targ.nextthink = time;
     }
     this.spawnflags = 2;
     spawnfunc_target_items(this);
     InitializeEntity(this, target_init_verify, INITPRIO_FINDTARGET);
 }
void target_init_verify (entity this)
Definition at line 71 of file t_quake3.qc.
References classname, entity(), find(), NULL, and targetname.
Referenced by spawnfunc(), and target_give_init().
 {
     entity trigger, targ;
     for(trigger = NULL; (trigger = find(trigger, classname, "trigger_multiple")); )
         for(targ = NULL; (targ = find(targ, targetname, trigger.target)); )
             if (targ.classname == "target_init" || targ.classname == "target_give" || targ.classname == "target_items")
             {
                 trigger.wait = 0;
                 trigger.delay = 0;
                 targ.wait = 0;
                 targ.delay = 0;
                 //setsize(targ, trigger.mins, trigger.maxs);
                 //setorigin(targ, trigger.origin);
                 //remove(trigger);
             }
 }
Variable Documentation
float delay
Definition at line 68 of file t_quake3.qc.
string gametype
Definition at line 166 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float notfree
Definition at line 163 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float notq3a
Definition at line 164 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float notsingle
Definition at line 162 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float notta
Definition at line 165 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float notteam
Definition at line 161 of file t_quake3.qc.
Referenced by DoesQ3ARemoveThisEntity().
float wait
Definition at line 67 of file t_quake3.qc.