Xonotic: server/bot/scripting.qc File Reference
scripting.qc File Reference
#include "scripting.qh"
#include <common/state.qh>
#include <common/physics/player.qh>
#include "bot.qh"
Functions
void bot_clearqueue (entity bot)
float bot_cmd_aim (entity this)
float bot_cmd_aimtarget (entity this)
float bot_cmd_barrier (entity this)
float bot_cmd_cc (entity this)
float bot_cmd_continue (entity this)
float bot_cmd_debug_assert_canfire (entity this)
float bot_cmd_else (entity this)
float bot_cmd_eval (entity this, string expr)
float bot_cmd_fi (entity this)
float bot_cmd_if (entity this)
float bot_cmd_impulse (entity this)
float bot_cmd_keypress_handler (entity this, string key, float enabled)
float bot_cmd_moveto (entity this)
float bot_cmd_movetotarget (entity this)
float bot_cmd_pause (entity this)
float bot_cmd_presskey (entity this)
float bot_cmd_releasekey (entity this)
float bot_cmd_resetaim (entity this)
float bot_cmd_resetgoal (entity this)
float bot_cmd_select_weapon (entity this)
float bot_cmd_sound (entity this)
float bot_cmd_turn (entity this)
float bot_cmd_wait (entity this)
float bot_cmd_wait_until (entity this)
void bot_cmdhelp (string scmd)
void bot_command_executed (entity this, bool rm)
void bot_commands_init ()
float bot_decodecommand (string cmdstring)
void bot_dequeuecommand (entity bot, float idx)
int bot_execute_commands (entity this)
float bot_execute_commands_once (entity this)
entity bot_getplace (entity this, string placename)
bool bot_havecommand (entity this, int idx)
void bot_list_commands ()
bool bot_presskeys (entity this)
void bot_queuecommand (entity bot, string cmdstring)
string bot_readcommand (entity bot, float idx)
void bot_resetqueues ()
void bot_setcurrentcommand (entity this)
entity find_bot_by_name (string name)
entity find_bot_by_number (float number)
void SV_ParseClientCommand (string s)
Variables
vector bot_cmd_aim_begin
float bot_cmd_aim_begintime
vector bot_cmd_aim_end
float bot_cmd_aim_endtime
int bot_cmd_condition_status
const int BOT_CMD_KEY_ATTACK1 = BIT(5)
const int BOT_CMD_KEY_ATTACK2 = BIT(6)
const int BOT_CMD_KEY_BACKWARD = BIT(1)
const int BOT_CMD_KEY_CHAT = BIT(10)
const int BOT_CMD_KEY_CROUCH = BIT(9)
const int BOT_CMD_KEY_FORWARD = BIT(0)
const int BOT_CMD_KEY_HOOK = BIT(8)
const int BOT_CMD_KEY_JUMP = BIT(4)
const int BOT_CMD_KEY_LEFT = BIT(3)
const int BOT_CMD_KEY_NONE = 0
const int BOT_CMD_KEY_RIGHT = BIT(2)
const int BOT_CMD_KEY_USE = BIT(7)
int bot_cmd_keys
float bot_cmd_wait_time
float bot_cmdqueuebuf
float bot_cmdqueuebuf_allocated
float bot_cmdqueuebuf_end
float bot_cmdqueuebuf_start
int bot_exec_status
string bot_placenames [MAX_BOT_PLACES]
entity bot_places [MAX_BOT_PLACES]
float bot_places_count
const int CMD_CONDITION_false = 2
const int CMD_CONDITION_false_BLOCK = 8
const int CMD_CONDITION_NONE = 0
const int CMD_CONDITION_true = 1
const int CMD_CONDITION_true_BLOCK = 4
const int MAX_BOT_PLACES = 4
int state
entity tuba_note
Function Documentation
void bot_clearqueue (entity bot)
Definition at line 15 of file scripting.qc.
References LOG_TRACE().
Referenced by bot_clientdisconnect(), bot_cmd_if(), bot_dequeuecommand(), and bot_resetqueues().
 {
     if(!bot.bot_cmdqueuebuf_allocated)
         return;
     buf_del(bot.bot_cmdqueuebuf);
     bot.bot_cmdqueuebuf_allocated = false;
     LOG_TRACE("bot ", bot.netname, " queue cleared\n");
 }
float bot_cmd_aim (entity this)
Definition at line 717 of file scripting.qc.
References argv(), bot_cmd, bot_cmd_aim_begin, bot_cmd_aim_begintime, bot_cmd_aim_end, bot_cmd_aim_endtime, CMD_STATUS_ERROR, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, min(), stof(), time, tokenizebyseparator, and v_angle.
Referenced by bot_cmd_aimtarget(), and bot_execute_commands_once().
 {
     // Current direction
     if(this.bot_cmd_aim_endtime)
     {
         float progress;
         progress = min(1 - (this.bot_cmd_aim_endtime - time) / (this.bot_cmd_aim_endtime - this.bot_cmd_aim_begintime),1);
         this.v_angle = this.bot_cmd_aim_begin + ((this.bot_cmd_aim_end - this.bot_cmd_aim_begin) * progress);
         if(time>=this.bot_cmd_aim_endtime)
         {
             this.bot_cmd_aim_endtime = 0;
             return CMD_STATUS_FINISHED;
         }
         else
             return CMD_STATUS_EXECUTING;
     }
     // New aiming direction
     string parms;
     float tokens, step;
     parms = bot_cmd.bot_cmd_parm_string;
     tokens = tokenizebyseparator(parms, " ");
     if(tokens<2||tokens>3)
         return CMD_STATUS_ERROR;
     step = (tokens == 3) ? stof(argv(2)) : 0;
     if(step == 0)
     {
         this.v_angle_x -= stof(argv(1));
         this.v_angle_y += stof(argv(0));
         return CMD_STATUS_FINISHED;
     }
     this.bot_cmd_aim_begin = this.v_angle;
     this.bot_cmd_aim_end_x = this.v_angle.x - stof(argv(1));
     this.bot_cmd_aim_end_y = this.v_angle.y + stof(argv(0));
     this.bot_cmd_aim_end_z = 0;
     this.bot_cmd_aim_begintime = time;
     this.bot_cmd_aim_endtime = time + step;
     return CMD_STATUS_EXECUTING;
 }
float bot_cmd_aimtarget (entity this)
Definition at line 768 of file scripting.qc.
References argv(), bot_cmd, bot_cmd_aim(), bot_cmd_aim_begin, bot_cmd_aim_begintime, bot_cmd_aim_end, bot_cmd_aim_endtime, bot_getplace(), CMD_STATUS_ERROR, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, entity(), origin, stof(), time, tokenizebyseparator, v_angle, vectoangles(), vector, and view_ofs.
Referenced by bot_execute_commands_once().
 {
     if(this.bot_cmd_aim_endtime)
     {
         return bot_cmd_aim(this);
     }
     entity e;
     string parms;
     vector v;
     float tokens, step;
     parms = bot_cmd.bot_cmd_parm_string;
     tokens = tokenizebyseparator(parms, " ");
     e = bot_getplace(this, argv(0));
     if(!e)
         return CMD_STATUS_ERROR;
     v = e.origin + (e.mins + e.maxs) * 0.5;
     if(tokens==1)
     {
         this.v_angle = vectoangles(v - (this.origin + this.view_ofs));
         this.v_angle_x = -this.v_angle.x;
         return CMD_STATUS_FINISHED;
     }
     if(tokens<1||tokens>2)
         return CMD_STATUS_ERROR;
     step = stof(argv(1));
     this.bot_cmd_aim_begin = this.v_angle;
     this.bot_cmd_aim_end = vectoangles(v - (this.origin + this.view_ofs));
     this.bot_cmd_aim_end_x = -this.bot_cmd_aim_end.x;
     this.bot_cmd_aim_begintime = time;
     this.bot_cmd_aim_endtime = time + step;
     return CMD_STATUS_EXECUTING;
 }
float bot_cmd_barrier (entity this)
Definition at line 528 of file scripting.qc.
References bot_barrier, bot_barriertime, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, FOREACH_CLIENT, LAMBDA, and time.
Referenced by bot_execute_commands_once().
 {
     // 0 = no barrier, 1 = waiting, 2 = waiting finished
     if(this.bot_barrier == 0) // initialization
     {
         this.bot_barrier = 1;
         //this.colormod = '4 4 0';
     }
     if(this.bot_barrier == 1) // find other bots
     {
         FOREACH_CLIENT(it.isbot, LAMBDA(
             if(it.bot_cmdqueuebuf_allocated)
             if(it.bot_barrier != 1)
                 return CMD_STATUS_EXECUTING; // not all are at the barrier yet
         ));
         // all bots hit the barrier!
         // acknowledge barrier
         FOREACH_CLIENT(it.isbot, LAMBDA(it.bot_barrier = 2));
         bot_barriertime = time;
     }
     // if we get here, the barrier is finished
     // so end it...
     this.bot_barrier = 0;
     //this.colormod = '0 0 0';
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_cc (entity this)
Definition at line 480 of file scripting.qc.
References bot_cmd, CMD_STATUS_FINISHED, SV_ParseClientCommand(), and WITHSELF.
Referenced by bot_execute_commands_once().
 {
     WITHSELF(this, SV_ParseClientCommand(bot_cmd.bot_cmd_parm_string));
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_continue (entity this)
Definition at line 492 of file scripting.qc.
References bot_exec_status, BOT_EXEC_STATUS_PAUSED, and CMD_STATUS_FINISHED.
Referenced by bot_execute_commands_once().
 {
     this.bot_exec_status &= ~BOT_EXEC_STATUS_PAUSED;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_debug_assert_canfire (entity this)
Definition at line 1056 of file scripting.qc.
References ATTACK_FINISHED, bot_cmd, CMD_STATUS_FINISHED, colormod, ftos(), LOG_INFO, netname, state, time, tuba_note, weaponentities, weaponname, and WS_READY.
Referenced by bot_execute_commands_once().
 {
     float f = bot_cmd.bot_cmd_parm_float;
     int slot = 0;
     .entity weaponentity = weaponentities[slot];
     if(this.(weaponentity).state != WS_READY)
     {
         if(f)
         {
             this.colormod = '0 8 8';
             LOG_INFO("Bot ", this.netname, " using ", this.weaponname, " wants to fire, inhibited by weaponentity state\n");
         }
     }
     else if(ATTACK_FINISHED(this, slot) > time)
     {
         if(f)
         {
             this.colormod = '8 0 8';
             LOG_INFO("Bot ", this.netname, " using ", this.weaponname, " wants to fire, inhibited by ATTACK_FINISHED (", ftos(ATTACK_FINISHED(this, slot) - time), " seconds left)\n");
         }
     }
     else if(this.tuba_note)
     {
         if(f)
         {
             this.colormod = '8 0 0';
             LOG_INFO("Bot ", this.netname, " using ", this.weaponname, " wants to fire, bot still has an active tuba note\n");
         }
     }
     else
     {
         if(!f)
         {
             this.colormod = '8 8 0';
             LOG_INFO("Bot ", this.netname, " using ", this.weaponname, " thinks it has fired, but apparently did not; ATTACK_FINISHED says ", ftos(ATTACK_FINISHED(this, slot) - time), " seconds left\n");
         }
     }
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_else (entity this)
Definition at line 693 of file scripting.qc.
References bot_cmd_condition_status, CMD_CONDITION_false_BLOCK, CMD_CONDITION_true_BLOCK, and CMD_STATUS_FINISHED.
Referenced by bot_execute_commands_once().
 {
     this.bot_cmd_condition_status &= ~CMD_CONDITION_true_BLOCK;
     this.bot_cmd_condition_status |= CMD_CONDITION_false_BLOCK;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_eval (entity this, string expr)
Definition at line 593 of file scripting.qc.
References cvar(), flagcarried, health, LOG_INFO, NULL, stof(), strcat(), strlen(), strstrofs, substring(), velocity, and vlen().
Referenced by bot_cmd_if().
 {
     // Search for numbers
     if(strstrofs("0123456789", substring(expr, 0, 1), 0) >= 0)
     {
         return stof(expr);
     }
     // Search for cvars
     if(substring(expr, 0, 5)=="cvar.")
     {
         return cvar(substring(expr, 5, strlen(expr)));
     }
     // Search for fields
     switch(expr)
     {
         case "health":
             return this.health;
         case "speed":
             return vlen(this.velocity);
         case "flagcarrier":
             return ((this.flagcarried!=NULL));
     }
     LOG_INFO(strcat("ERROR: Unable to convert the expression '",expr,"' into a numeric value\n"));
     return 0;
 }
float bot_cmd_fi (entity this)
Definition at line 700 of file scripting.qc.
References bot_cmd_condition_status, CMD_CONDITION_NONE, and CMD_STATUS_FINISHED.
Referenced by bot_execute_commands_once().
 {
     this.bot_cmd_condition_status = CMD_CONDITION_NONE;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_if (entity this)
Definition at line 622 of file scripting.qc.
References bot_clearqueue(), bot_cmd, bot_cmd_condition_status, bot_cmd_eval(), CMD_CONDITION_false, CMD_CONDITION_NONE, CMD_CONDITION_true, CMD_CONDITION_true_BLOCK, CMD_STATUS_ERROR, CMD_STATUS_FINISHED, LOG_INFO, strlen(), strstrofs, and substring().
Referenced by bot_execute_commands_once().
 {
     string expr, val_a, val_b;
     float cmpofs;
     if(this.bot_cmd_condition_status != CMD_CONDITION_NONE)
     {
         // Only one "if" block is allowed at time
         LOG_INFO("ERROR: Only one conditional block can be processed at time");
         bot_clearqueue(this);
         return CMD_STATUS_ERROR;
     }
     this.bot_cmd_condition_status |= CMD_CONDITION_true_BLOCK;
     // search for operators
     expr = bot_cmd.bot_cmd_parm_string;
     cmpofs = strstrofs(expr,"=",0);
     if(cmpofs>0)
     {
         val_a = substring(expr,0,cmpofs);
         val_b = substring(expr,cmpofs+1,strlen(expr));
         if(bot_cmd_eval(this, val_a)==bot_cmd_eval(this, val_b))
             this.bot_cmd_condition_status |= CMD_CONDITION_true;
         else
             this.bot_cmd_condition_status |= CMD_CONDITION_false;
         return CMD_STATUS_FINISHED;
     }
     cmpofs = strstrofs(expr,">",0);
     if(cmpofs>0)
     {
         val_a = substring(expr,0,cmpofs);
         val_b = substring(expr,cmpofs+1,strlen(expr));
         if(bot_cmd_eval(this, val_a)>bot_cmd_eval(this, val_b))
             this.bot_cmd_condition_status |= CMD_CONDITION_true;
         else
             this.bot_cmd_condition_status |= CMD_CONDITION_false;
         return CMD_STATUS_FINISHED;
     }
     cmpofs = strstrofs(expr,"<",0);
     if(cmpofs>0)
     {
         val_a = substring(expr,0,cmpofs);
         val_b = substring(expr,cmpofs+1,strlen(expr));
         if(bot_cmd_eval(this, val_a)<bot_cmd_eval(this, val_b))
             this.bot_cmd_condition_status |= CMD_CONDITION_true;
         else
             this.bot_cmd_condition_status |= CMD_CONDITION_false;
         return CMD_STATUS_FINISHED;
     }
     if(bot_cmd_eval(this, expr))
         this.bot_cmd_condition_status |= CMD_CONDITION_true;
     else
         this.bot_cmd_condition_status |= CMD_CONDITION_false;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_impulse (entity this)
Definition at line 486 of file scripting.qc.
References bot_cmd, CMD_STATUS_FINISHED, and impulse.
Referenced by bot_execute_commands_once().
 {
     this.impulse = bot_cmd.bot_cmd_parm_float;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_keypress_handler (entity this, string key, float enabled)
Definition at line 876 of file scripting.qc.
References BOT_CMD_KEY_ATTACK1, BOT_CMD_KEY_ATTACK2, BOT_CMD_KEY_BACKWARD, BOT_CMD_KEY_CHAT, BOT_CMD_KEY_CROUCH, BOT_CMD_KEY_FORWARD, BOT_CMD_KEY_HOOK, BOT_CMD_KEY_JUMP, BOT_CMD_KEY_LEFT, BOT_CMD_KEY_NONE, BOT_CMD_KEY_RIGHT, BOT_CMD_KEY_USE, bot_cmd_keys, CMD_STATUS_FINISHED, and power2of().
Referenced by bot_cmd_presskey(), and bot_cmd_releasekey().
 {
     switch(key)
     {
         case "all":
             if(enabled)
                 this.bot_cmd_keys = power2of(20) - 1; // >:)
             else
                 this.bot_cmd_keys = BOT_CMD_KEY_NONE;
         case "forward":
             if(enabled)
             {
                 this.bot_cmd_keys |= BOT_CMD_KEY_FORWARD;
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_BACKWARD;
             }
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_FORWARD;
             break;
         case "backward":
             if(enabled)
             {
                 this.bot_cmd_keys |= BOT_CMD_KEY_BACKWARD;
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_FORWARD;
             }
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_BACKWARD;
             break;
         case "left":
             if(enabled)
             {
                 this.bot_cmd_keys |= BOT_CMD_KEY_LEFT;
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_RIGHT;
             }
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_LEFT;
             break;
         case "right":
             if(enabled)
             {
                 this.bot_cmd_keys |= BOT_CMD_KEY_RIGHT;
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_LEFT;
             }
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_RIGHT;
             break;
         case "jump":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_JUMP;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_JUMP;
             break;
         case "crouch":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_CROUCH;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_CROUCH;
             break;
         case "attack1":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_ATTACK1;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_ATTACK1;
             break;
         case "attack2":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_ATTACK2;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_ATTACK2;
             break;
         case "use":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_USE;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_USE;
             break;
         case "hook":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_HOOK;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_HOOK;
             break;
         case "chat":
             if(enabled)
                 this.bot_cmd_keys |= BOT_CMD_KEY_CHAT;
             else
                 this.bot_cmd_keys &= ~BOT_CMD_KEY_CHAT;
             break;
         default:
             break;
     }
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_moveto (entity this)
Definition at line 1008 of file scripting.qc.
References bot_cmd.
Referenced by bot_execute_commands_once().
 {
     return this.cmd_moveto(this, bot_cmd.bot_cmd_parm_vector);
 }
float bot_cmd_movetotarget (entity this)
Definition at line 1013 of file scripting.qc.
References bot_cmd, bot_getplace(), CMD_STATUS_ERROR, and entity().
Referenced by bot_execute_commands_once().
 {
     entity e;
     e = bot_getplace(this, bot_cmd.bot_cmd_parm_string);
     if(!e)
         return CMD_STATUS_ERROR;
     return this.cmd_moveto(this, e.origin + (e.mins + e.maxs) * 0.5);
 }
float bot_cmd_pause (entity this)
Definition at line 990 of file scripting.qc.
References BOT_CMD_KEY_NONE, bot_cmd_keys, bot_exec_status, BOT_EXEC_STATUS_PAUSED, CMD_STATUS_FINISHED, movement, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_CHAT, PHYS_INPUT_BUTTON_CROUCH, PHYS_INPUT_BUTTON_DRAG, PHYS_INPUT_BUTTON_HOOK, PHYS_INPUT_BUTTON_JUMP, and PHYS_INPUT_BUTTON_USE.
Referenced by bot_execute_commands_once().
 {
     PHYS_INPUT_BUTTON_DRAG(this) = false;
     PHYS_INPUT_BUTTON_USE(this) = false;
     PHYS_INPUT_BUTTON_ATCK(this) = false;
     PHYS_INPUT_BUTTON_JUMP(this) = false;
     PHYS_INPUT_BUTTON_HOOK(this) = false;
     PHYS_INPUT_BUTTON_CHAT(this) = false;
     PHYS_INPUT_BUTTON_ATCK2(this) = false;
     PHYS_INPUT_BUTTON_CROUCH(this) = false;
     this.movement = '0 0 0';
     this.bot_cmd_keys = BOT_CMD_KEY_NONE;
     this.bot_exec_status |= BOT_EXEC_STATUS_PAUSED;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_presskey (entity this)
Definition at line 970 of file scripting.qc.
References bot_cmd, bot_cmd_keypress_handler(), and CMD_STATUS_FINISHED.
Referenced by bot_execute_commands_once().
 {
     string key;
     key = bot_cmd.bot_cmd_parm_string;
     bot_cmd_keypress_handler(this, key,true);
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_releasekey (entity this)
Definition at line 981 of file scripting.qc.
References bot_cmd, and bot_cmd_keypress_handler().
Referenced by bot_execute_commands_once().
 {
     string key;
     key = bot_cmd.bot_cmd_parm_string;
     return bot_cmd_keypress_handler(this, key,false);
 }
float bot_cmd_resetaim (entity this)
Definition at line 706 of file scripting.qc.
References CMD_STATUS_FINISHED, and v_angle.
Referenced by bot_execute_commands_once().
 {
     this.v_angle = '0 0 0';
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_resetgoal (entity this)
Definition at line 1022 of file scripting.qc.
Referenced by bot_execute_commands_once().
 {
     return this.cmd_resetgoal(this);
 }
float bot_cmd_select_weapon (entity this)
Definition at line 570 of file scripting.qc.
References bot_cmd, client_hasweapon(), CMD_STATUS_ERROR, CMD_STATUS_FINISHED, PS, Weapons_from, and WEP_LAST.
Referenced by bot_execute_commands_once().
 {
     float id = bot_cmd.bot_cmd_parm_float;
     if(id < WEP_FIRST || id > WEP_LAST)
         return CMD_STATUS_ERROR;
     if(client_hasweapon(this, Weapons_from(id), true, false))
         PS(this).m_switchweapon = Weapons_from(id);
     else
         return CMD_STATUS_ERROR;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_sound (entity this)
Definition at line 1028 of file scripting.qc.
References _sound, argv(), atten, ATTEN_MIN, bot_cmd, CH_WEAPON_B, CMD_STATUS_FINISHED, precache_sound(), stof(), tokenizebyseparator, and VOL_BASE.
Referenced by bot_execute_commands_once().
 {
     string f;
     f = bot_cmd.bot_cmd_parm_string;
     float n = tokenizebyseparator(f, " ");
     string sample = f;
     float chan = CH_WEAPON_B;
     float vol = VOL_BASE;
     float atten = ATTEN_MIN;
     if(n >= 1)
         sample = argv(n - 1);
     if(n >= 2)
         chan = stof(argv(0));
     if(n >= 3)
         vol = stof(argv(1));
     if(n >= 4)
         atten = stof(argv(2));
     precache_sound(f);
     _sound(this, chan, sample, vol, atten);
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_turn (entity this)
Definition at line 563 of file scripting.qc.
References bot_cmd, CMD_STATUS_FINISHED, floor(), and v_angle.
Referenced by bot_execute_commands_once().
 {
     this.v_angle_y = this.v_angle.y + bot_cmd.bot_cmd_parm_float;
     this.v_angle_y = this.v_angle.y - floor(this.v_angle.y / 360) * 360;
     return CMD_STATUS_FINISHED;
 }
float bot_cmd_wait (entity this)
Definition at line 499 of file scripting.qc.
References bot_cmd, bot_cmd_wait_time, bot_exec_status, BOT_EXEC_STATUS_WAITING, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, and time.
Referenced by bot_execute_commands_once().
 {
     if(this.bot_exec_status & BOT_EXEC_STATUS_WAITING)
     {
         if(time>=this.bot_cmd_wait_time)
         {
             this.bot_exec_status &= ~BOT_EXEC_STATUS_WAITING;
             return CMD_STATUS_FINISHED;
         }
         else
             return CMD_STATUS_EXECUTING;
     }
     this.bot_cmd_wait_time = time + bot_cmd.bot_cmd_parm_float;
     this.bot_exec_status |= BOT_EXEC_STATUS_WAITING;
     return CMD_STATUS_EXECUTING;
 }
float bot_cmd_wait_until (entity this)
Definition at line 517 of file scripting.qc.
References bot_barriertime, bot_cmd, bot_exec_status, BOT_EXEC_STATUS_WAITING, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, and time.
Referenced by bot_execute_commands_once().
 {
     if(time < bot_cmd.bot_cmd_parm_float + bot_barriertime)
     {
         this.bot_exec_status |= BOT_EXEC_STATUS_WAITING;
         return CMD_STATUS_EXECUTING;
     }
     this.bot_exec_status &= ~BOT_EXEC_STATUS_WAITING;
     return CMD_STATUS_FINISHED;
 }
void bot_cmdhelp (string scmd)
Definition at line 329 of file scripting.qc.
References BOT_CMD_AIM, BOT_CMD_AIMTARGET, BOT_CMD_BARRIER, BOT_CMD_CC, BOT_CMD_CONTINUE, BOT_CMD_COUNTER, BOT_CMD_DEBUG_ASSERT_CANFIRE, BOT_CMD_IF, BOT_CMD_MOVETO, BOT_CMD_MOVETOTARGET, BOT_CMD_PARAMETER_FLOAT, BOT_CMD_PARAMETER_STRING, BOT_CMD_PARAMETER_VECTOR, bot_cmd_parm_type, BOT_CMD_PAUSE, BOT_CMD_PRESSKEY, BOT_CMD_RELEASEKEY, BOT_CMD_RESETAIM, BOT_CMD_RESETGOAL, BOT_CMD_SOUND, bot_cmd_string, BOT_CMD_TURN, BOT_CMD_WAIT, BOT_CMD_WAIT_UNTIL, bot_cmds_initialized, bot_commands_init(), LOG_INFO, and strcat().
Referenced by GameCommand_bot_cmd().
 {
     int i, ntype;
     string stype;
     if(!bot_cmds_initialized)
         bot_commands_init();
     for(i=1;i<BOT_CMD_COUNTER;++i)
     {
         if(bot_cmd_string[i]!=scmd)
             continue;
         ntype = bot_cmd_parm_type[i];
         switch(ntype)
         {
             case BOT_CMD_PARAMETER_FLOAT:
                 stype = "float number";
                 break;
             case BOT_CMD_PARAMETER_STRING:
                 stype = "string";
                 break;
             case BOT_CMD_PARAMETER_VECTOR:
                 stype = "vector";
                 break;
             default:
                 stype = "none";
                 break;
         }
         LOG_INFO(strcat("Command: ",bot_cmd_string[i],"\nParameter: <",stype,"> \n"));
         LOG_INFO("Description: ");
         switch(i)
         {
             case BOT_CMD_PAUSE:
                 LOG_INFO("Stops the bot completely. Any command other than 'continue' will be ignored.");
                 break;
             case BOT_CMD_CONTINUE:
                 LOG_INFO("Disable paused status");
                 break;
             case BOT_CMD_WAIT:
                 LOG_INFO("Pause command parsing and bot ai for N seconds. Pressed key will remain pressed");
                 break;
             case BOT_CMD_WAIT_UNTIL:
                 LOG_INFO("Pause command parsing and bot ai until time is N from the last barrier. Pressed key will remain pressed");
                 break;
             case BOT_CMD_BARRIER:
                 LOG_INFO("Waits till all bots that have a command queue reach this command. Pressed key will remain pressed");
                 break;
             case BOT_CMD_TURN:
                 LOG_INFO("Look to the right or left N degrees. For turning to the left use positive numbers.");
                 break;
             case BOT_CMD_MOVETO:
                 LOG_INFO("Walk to an specific coordinate on the map. Usage: moveto \"x y z\"");
                 break;
             case BOT_CMD_MOVETOTARGET:
                 LOG_INFO("Walk to the specific target on the map");
                 break;
             case BOT_CMD_RESETGOAL:
                 LOG_INFO("Resets the goal stack");
                 break;
             case BOT_CMD_CC:
                 LOG_INFO("Execute client command. Examples: cc \"say something\"; cc god; cc \"name newnickname\"; cc kill;");
                 break;
             case BOT_CMD_IF:
                 LOG_INFO("Perform simple conditional execution.\n");
                 LOG_INFO("Syntax: \n");
                 LOG_INFO("        sv_cmd .. if \"condition\"\n");
                 LOG_INFO("        sv_cmd ..     <instruction if true>\n");
                 LOG_INFO("        sv_cmd ..     <instruction if true>\n");
                 LOG_INFO("        sv_cmd .. else\n");
                 LOG_INFO("        sv_cmd ..     <instruction if false>\n");
                 LOG_INFO("        sv_cmd ..     <instruction if false>\n");
                 LOG_INFO("        sv_cmd .. fi\n");
                 LOG_INFO("Conditions: a=b, a>b, a<b, a\t\t(spaces not allowed)\n");
                 LOG_INFO("            Values in conditions can be numbers, cvars in the form cvar.cvar_string or special fields\n");
                 LOG_INFO("Fields: health, speed, flagcarrier\n");
                 LOG_INFO("Examples: if health>50; if health>cvar.g_balance_laser_primary_damage; if flagcarrier;");
                 break;
             case BOT_CMD_RESETAIM:
                 LOG_INFO("Points the aim to the coordinates x,y 0,0");
                 break;
             case BOT_CMD_AIM:
                 LOG_INFO("Move the aim x/y (horizontal/vertical) degrees relatives to the bot\n");
                 LOG_INFO("There is a 3rd optional parameter telling in how many seconds the aim has to reach the new position\n");
                 LOG_INFO("Examples: aim \"90 0\"    // Turn 90 degrees inmediately (positive numbers move to the left/up)\n");
                 LOG_INFO("          aim \"0 90 2\"  // Will gradually look to the sky in the next two seconds");
                 break;
             case BOT_CMD_AIMTARGET:
                 LOG_INFO("Points the aim to given target");
                 break;
             case BOT_CMD_PRESSKEY:
                 LOG_INFO("Press one of the following keys: forward, backward, left, right, jump, crouch, attack1, attack2, use\n");
                 LOG_INFO("Multiple keys can be pressed at time (with many presskey calls) and it will remain pressed until the command \"releasekey\" is called");
                 LOG_INFO("Note: The script will not return the control to the bot ai until all keys are released");
                 break;
             case BOT_CMD_RELEASEKEY:
                 LOG_INFO("Release previoulsy used keys. Use the parameter \"all\" to release all keys");
                 break;
             case BOT_CMD_SOUND:
                 LOG_INFO("play sound file at bot location");
                 break;
             case BOT_CMD_DEBUG_ASSERT_CANFIRE:
                 LOG_INFO("verify the state of the weapon entity");
                 break;
             default:
                 LOG_INFO("This command has no description yet.");
                 break;
         }
         LOG_INFO("\n");
     }
 }
void bot_command_executed (entity this, bool rm)
Definition at line 1100 of file scripting.qc.
References bot_cmd, bot_cmd_execution_index, bot_dequeuecommand(), cmd(), and entity().
Referenced by bot_execute_commands_once().
 {
     entity cmd;
     cmd = bot_cmd;
     if(rm)
         bot_dequeuecommand(this, this.bot_cmd_execution_index);
     this.bot_cmd_execution_index++;
 }
void bot_commands_init ()
Definition at line 151 of file scripting.qc.
References BOT_CMD_AIM, BOT_CMD_AIMTARGET, BOT_CMD_BARRIER, BOT_CMD_CC, BOT_CMD_CONSOLE, BOT_CMD_CONTINUE, BOT_CMD_DEBUG_ASSERT_CANFIRE, BOT_CMD_ELSE, BOT_CMD_FI, BOT_CMD_IF, BOT_CMD_IMPULSE, BOT_CMD_MOVETO, BOT_CMD_MOVETOTARGET, BOT_CMD_NULL, BOT_CMD_PARAMETER_FLOAT, BOT_CMD_PARAMETER_NONE, BOT_CMD_PARAMETER_STRING, BOT_CMD_PARAMETER_VECTOR, bot_cmd_parm_type, BOT_CMD_PAUSE, BOT_CMD_PRESSKEY, BOT_CMD_RELEASEKEY, BOT_CMD_RESETAIM, BOT_CMD_RESETGOAL, BOT_CMD_SELECTWEAPON, BOT_CMD_SOUND, bot_cmd_string, BOT_CMD_TURN, BOT_CMD_WAIT, BOT_CMD_WAIT_UNTIL, and bot_cmds_initialized.
Referenced by bot_cmdhelp(), bot_decodecommand(), and bot_list_commands().
 {
     bot_cmd_string[BOT_CMD_NULL] = "";
     bot_cmd_parm_type[BOT_CMD_NULL] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_PAUSE] = "pause";
     bot_cmd_parm_type[BOT_CMD_PAUSE] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_CONTINUE] = "continue";
     bot_cmd_parm_type[BOT_CMD_CONTINUE] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_WAIT] = "wait";
     bot_cmd_parm_type[BOT_CMD_WAIT] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmd_string[BOT_CMD_TURN] = "turn";
     bot_cmd_parm_type[BOT_CMD_TURN] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmd_string[BOT_CMD_MOVETO] = "moveto";
     bot_cmd_parm_type[BOT_CMD_MOVETO] = BOT_CMD_PARAMETER_VECTOR;
     bot_cmd_string[BOT_CMD_MOVETOTARGET] = "movetotarget";
     bot_cmd_parm_type[BOT_CMD_MOVETOTARGET] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_RESETGOAL] = "resetgoal";
     bot_cmd_parm_type[BOT_CMD_RESETGOAL] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_CC] = "cc";
     bot_cmd_parm_type[BOT_CMD_CC] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_IF] = "if";
     bot_cmd_parm_type[BOT_CMD_IF] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_ELSE] = "else";
     bot_cmd_parm_type[BOT_CMD_ELSE] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_FI] = "fi";
     bot_cmd_parm_type[BOT_CMD_FI] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_RESETAIM] = "resetaim";
     bot_cmd_parm_type[BOT_CMD_RESETAIM] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_AIM] = "aim";
     bot_cmd_parm_type[BOT_CMD_AIM] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_AIMTARGET] = "aimtarget";
     bot_cmd_parm_type[BOT_CMD_AIMTARGET] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_PRESSKEY] = "presskey";
     bot_cmd_parm_type[BOT_CMD_PRESSKEY] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_RELEASEKEY] = "releasekey";
     bot_cmd_parm_type[BOT_CMD_RELEASEKEY] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_SELECTWEAPON] = "selectweapon";
     bot_cmd_parm_type[BOT_CMD_SELECTWEAPON] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmd_string[BOT_CMD_IMPULSE] = "impulse";
     bot_cmd_parm_type[BOT_CMD_IMPULSE] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmd_string[BOT_CMD_WAIT_UNTIL] = "wait_until";
     bot_cmd_parm_type[BOT_CMD_WAIT_UNTIL] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmd_string[BOT_CMD_BARRIER] = "barrier";
     bot_cmd_parm_type[BOT_CMD_BARRIER] = BOT_CMD_PARAMETER_NONE;
     bot_cmd_string[BOT_CMD_CONSOLE] = "console";
     bot_cmd_parm_type[BOT_CMD_CONSOLE] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_SOUND] = "sound";
     bot_cmd_parm_type[BOT_CMD_SOUND] = BOT_CMD_PARAMETER_STRING;
     bot_cmd_string[BOT_CMD_DEBUG_ASSERT_CANFIRE] = "debug_assert_canfire";
     bot_cmd_parm_type[BOT_CMD_DEBUG_ASSERT_CANFIRE] = BOT_CMD_PARAMETER_FLOAT;
     bot_cmds_initialized = true;
 }
float bot_decodecommand (string cmdstring)
Definition at line 269 of file scripting.qc.
References bot_cmd, BOT_CMD_COUNTER, BOT_CMD_PARAMETER_FLOAT, BOT_CMD_PARAMETER_NONE, BOT_CMD_PARAMETER_STRING, BOT_CMD_PARAMETER_VECTOR, bot_cmd_parm_type, bot_cmd_string, bot_cmds_initialized, bot_commands_init(), LOG_INFO, stof(), stov(), strstrofs, strunzone(), strzone(), and substring().
Referenced by bot_setcurrentcommand().
 {
     float cmd_parm_type;
     float sp;
     string parm;
     sp = strstrofs(cmdstring, " ", 0);
     if(sp < 0)
     {
         parm = "";
     }
     else
     {
         parm = substring(cmdstring, sp + 1, -1);
         cmdstring = substring(cmdstring, 0, sp);
     }
     if(!bot_cmds_initialized)
         bot_commands_init();
     int i;
     for(i=1;i<BOT_CMD_COUNTER;++i)
     {
         if(bot_cmd_string[i]!=cmdstring)
             continue;
         cmd_parm_type = bot_cmd_parm_type[i];
         if(cmd_parm_type!=BOT_CMD_PARAMETER_NONE&&parm=="")
         {
             LOG_INFO("ERROR: A parameter is required for this command\n");
             return 0;
         }
         // Load command into queue
         bot_cmd.bot_cmd_type = i;
         // Attach parameter
         switch(cmd_parm_type)
         {
             case BOT_CMD_PARAMETER_FLOAT:
                 bot_cmd.bot_cmd_parm_float = stof(parm);
                 break;
             case BOT_CMD_PARAMETER_STRING:
                 if(bot_cmd.bot_cmd_parm_string)
                     strunzone(bot_cmd.bot_cmd_parm_string);
                 bot_cmd.bot_cmd_parm_string = strzone(parm);
                 break;
             case BOT_CMD_PARAMETER_VECTOR:
                 bot_cmd.bot_cmd_parm_vector = stov(parm);
                 break;
             default:
                 break;
         }
         return 1;
     }
     LOG_INFO("ERROR: No such command '", cmdstring, "'\n");
     return 0;
 }
void bot_dequeuecommand (entity bot, float idx)
Definition at line 66 of file scripting.qc.
References bot_clearqueue(), and error.
Referenced by bot_command_executed(), and bot_setcurrentcommand().
 {
     if(!bot.bot_cmdqueuebuf_allocated)
         error("dequeuecommand but no queue allocated");
     if(idx < bot.bot_cmdqueuebuf_start)
         error("dequeueing a command in the past");
     if(idx >= bot.bot_cmdqueuebuf_end)
         error("dequeueing a command in the future");
     bufstr_set(bot.bot_cmdqueuebuf, idx, "");
     if(idx == bot.bot_cmdqueuebuf_start)
         bot.bot_cmdqueuebuf_start += 1;
     if(bot.bot_cmdqueuebuf_start >= bot.bot_cmdqueuebuf_end)
         bot_clearqueue(bot);
 }
int bot_execute_commands (entity this)
Definition at line 1332 of file scripting.qc.
References bot_execute_commands_once().
Referenced by havocbot_ai().
 {
     int f;
     do
     {
         f = bot_execute_commands_once(this);
     }
     while(f < 0);
     return f;
 }
float bot_execute_commands_once (entity this)
Definition at line 1167 of file scripting.qc.
References autocvar_g_debug_bot_commands, boolean, bot_cmd, BOT_CMD_AIM, bot_cmd_aim(), BOT_CMD_AIMTARGET, bot_cmd_aimtarget(), BOT_CMD_BARRIER, bot_cmd_barrier(), BOT_CMD_CC, bot_cmd_cc(), bot_cmd_condition_status, BOT_CMD_CONSOLE, BOT_CMD_CONTINUE, bot_cmd_continue(), BOT_CMD_DEBUG_ASSERT_CANFIRE, bot_cmd_debug_assert_canfire(), BOT_CMD_ELSE, bot_cmd_else(), BOT_CMD_FI, bot_cmd_fi(), BOT_CMD_IF, bot_cmd_if(), BOT_CMD_IMPULSE, bot_cmd_impulse(), BOT_CMD_MOVETO, bot_cmd_moveto(), BOT_CMD_MOVETOTARGET, bot_cmd_movetotarget(), BOT_CMD_NULL, BOT_CMD_PARAMETER_FLOAT, BOT_CMD_PARAMETER_STRING, BOT_CMD_PARAMETER_VECTOR, bot_cmd_parm_type, BOT_CMD_PAUSE, bot_cmd_pause(), BOT_CMD_PRESSKEY, bot_cmd_presskey(), BOT_CMD_RELEASEKEY, bot_cmd_releasekey(), BOT_CMD_RESETAIM, bot_cmd_resetaim(), BOT_CMD_RESETGOAL, bot_cmd_resetgoal(), bot_cmd_select_weapon(), BOT_CMD_SELECTWEAPON, BOT_CMD_SOUND, bot_cmd_sound(), bot_cmd_string, BOT_CMD_TURN, bot_cmd_turn(), BOT_CMD_WAIT, bot_cmd_wait(), BOT_CMD_WAIT_UNTIL, bot_cmd_wait_until(), bot_command_executed(), bot_exec_status, BOT_EXEC_STATUS_PAUSED, bot_presskeys(), bot_setcurrentcommand(), clientcommand(), CMD_CONDITION_false, CMD_CONDITION_false_BLOCK, CMD_CONDITION_true, CMD_CONDITION_true_BLOCK, CMD_STATUS_ERROR, CMD_STATUS_EXECUTING, CMD_STATUS_FINISHED, ftos(), localcmd, LOG_INFO, NULL, strcat(), and vtos().
Referenced by bot_execute_commands().
 {
     float status, ispressingkey;
     // Find command
     bot_setcurrentcommand(this);
     // if we have no bot command, better return
     // old logic kept pressing previously pressed keys, but that has problems
     // (namely, it means you cannot make a bot "normal" ever again)
     // to keep a bot walking for a while, use the "wait" bot command
     if(bot_cmd == NULL)
         return false;
     // Ignore all commands except continue when the bot is paused
     if(this.bot_exec_status & BOT_EXEC_STATUS_PAUSED)
     if(bot_cmd.bot_cmd_type!=BOT_CMD_CONTINUE)
     {
         if(bot_cmd.bot_cmd_type!=BOT_CMD_NULL)
         {
             bot_command_executed(this, true);
             LOG_INFO( "WARNING: Commands are ignored while the bot is paused. Use the command 'continue' instead.\n");
         }
         return 1;
     }
     // Keep pressing keys raised by the "presskey" command
     ispressingkey = boolean(bot_presskeys(this));
     // Handle conditions
     if (!(bot_cmd.bot_cmd_type==BOT_CMD_FI||bot_cmd.bot_cmd_type==BOT_CMD_ELSE))
     if(this.bot_cmd_condition_status & CMD_CONDITION_true && this.bot_cmd_condition_status & CMD_CONDITION_false_BLOCK)
     {
         bot_command_executed(this, true);
         return -1;
     }
     else if(this.bot_cmd_condition_status & CMD_CONDITION_false && this.bot_cmd_condition_status & CMD_CONDITION_true_BLOCK)
     {
         bot_command_executed(this, true);
         return -1;
     }
     // Map commands to functions
     switch(bot_cmd.bot_cmd_type)
     {
         case BOT_CMD_NULL:
             return ispressingkey;
             //break;
         case BOT_CMD_PAUSE:
             status = bot_cmd_pause(this);
             break;
         case BOT_CMD_CONTINUE:
             status = bot_cmd_continue(this);
             break;
         case BOT_CMD_WAIT:
             status = bot_cmd_wait(this);
             break;
         case BOT_CMD_WAIT_UNTIL:
             status = bot_cmd_wait_until(this);
             break;
         case BOT_CMD_TURN:
             status = bot_cmd_turn(this);
             break;
         case BOT_CMD_MOVETO:
             status = bot_cmd_moveto(this);
             break;
         case BOT_CMD_MOVETOTARGET:
             status = bot_cmd_movetotarget(this);
             break;
         case BOT_CMD_RESETGOAL:
             status = bot_cmd_resetgoal(this);
             break;
         case BOT_CMD_CC:
             status = bot_cmd_cc(this);
             break;
         case BOT_CMD_IF:
             status = bot_cmd_if(this);
             break;
         case BOT_CMD_ELSE:
             status = bot_cmd_else(this);
             break;
         case BOT_CMD_FI:
             status = bot_cmd_fi(this);
             break;
         case BOT_CMD_RESETAIM:
             status = bot_cmd_resetaim(this);
             break;
         case BOT_CMD_AIM:
             status = bot_cmd_aim(this);
             break;
         case BOT_CMD_AIMTARGET:
             status = bot_cmd_aimtarget(this);
             break;
         case BOT_CMD_PRESSKEY:
             status = bot_cmd_presskey(this);
             break;
         case BOT_CMD_RELEASEKEY:
             status = bot_cmd_releasekey(this);
             break;
         case BOT_CMD_SELECTWEAPON:
             status = bot_cmd_select_weapon(this);
             break;
         case BOT_CMD_IMPULSE:
             status = bot_cmd_impulse(this);
             break;
         case BOT_CMD_BARRIER:
             status = bot_cmd_barrier(this);
             break;
         case BOT_CMD_CONSOLE:
             localcmd(strcat(bot_cmd.bot_cmd_parm_string, "\n"));
             status = CMD_STATUS_FINISHED;
             break;
         case BOT_CMD_SOUND:
             status = bot_cmd_sound(this);
             break;
         case BOT_CMD_DEBUG_ASSERT_CANFIRE:
             status = bot_cmd_debug_assert_canfire(this);
             break;
         default:
             LOG_INFO(strcat("ERROR: Invalid command on queue with id '",ftos(bot_cmd.bot_cmd_type),"'\n"));
             return 0;
     }
     if (status==CMD_STATUS_ERROR)
         LOG_INFO(strcat("ERROR: The command '",bot_cmd_string[bot_cmd.bot_cmd_type],"' returned an error status\n"));
     // Move execution pointer
     if(status==CMD_STATUS_EXECUTING)
     {
         return 1;
     }
     else
     {
         if(autocvar_g_debug_bot_commands)
         {
             string parms;
             switch(bot_cmd_parm_type[bot_cmd.bot_cmd_type])
             {
                 case BOT_CMD_PARAMETER_FLOAT:
                     parms = ftos(bot_cmd.bot_cmd_parm_float);
                     break;
                 case BOT_CMD_PARAMETER_STRING:
                     parms = bot_cmd.bot_cmd_parm_string;
                     break;
                 case BOT_CMD_PARAMETER_VECTOR:
                     parms = vtos(bot_cmd.bot_cmd_parm_vector);
                     break;
                 default:
                     parms = "";
                     break;
             }
             clientcommand(this,strcat("say ^7", bot_cmd_string[bot_cmd.bot_cmd_type]," ",parms,"\n"));
         }
         bot_command_executed(this, true);
     }
     if(status == CMD_STATUS_FINISHED)
         return -1;
     return CMD_STATUS_ERROR;
 }
entity bot_getplace (entity this, string placename)
Definition at line 107 of file scripting.qc.
References bot_placenames, bot_places, bot_places_count, cvar_set(), cvar_string(), entity(), find(), LOG_INFO, MAX_BOT_PLACES, NULL, p, s2, strcat(), strstrofs, strzone(), substring(), and targetname.
Referenced by bot_cmd_aimtarget(), and bot_cmd_movetotarget().
 {
     entity e;
     if(substring(placename, 0, 1) == "@")
     {
         int i, p;
         placename = substring(placename, 1, -1);
         string s, s2;
         for(i = 0; i < this.bot_places_count; ++i)
             if(this.(bot_placenames[i]) == placename)
                 return this.(bot_places[i]);
         // now: i == this.bot_places_count
         s = s2 = cvar_string(placename);
         p = strstrofs(s2, " ", 0);
         if(p >= 0)
         {
             s = substring(s2, 0, p);
             //print("places: ", placename, " -> ", cvar_string(placename), "\n");
             cvar_set(placename, strcat(substring(s2, p+1, -1), " ", s));
             //print("places: ", placename, " := ", cvar_string(placename), "\n");
         }
         e = find(NULL, targetname, s);
         if(!e)
             LOG_INFO("invalid place ", s, "\n");
         if(i < MAX_BOT_PLACES)
         {
             this.(bot_placenames[i]) = strzone(placename);
             this.(bot_places[i]) = e;
             this.bot_places_count += 1;
         }
         return e;
     }
     else
     {
         e = find(NULL, targetname, placename);
         if(!e)
             LOG_INFO("invalid place ", placename, "\n");
         return e;
     }
 }
bool bot_havecommand (entity this, int idx)
Definition at line 92 of file scripting.qc.
References bot_cmdqueuebuf_allocated, bot_cmdqueuebuf_end, and bot_cmdqueuebuf_start.
Referenced by bot_setcurrentcommand().
 {
     if(!this.bot_cmdqueuebuf_allocated)
         return false;
     if(idx < this.bot_cmdqueuebuf_start)
         return false;
     if(idx >= this.bot_cmdqueuebuf_end)
         return false;
     return true;
 }
void bot_list_commands ()
Definition at line 444 of file scripting.qc.
References BOT_CMD_COUNTER, BOT_CMD_PARAMETER_FLOAT, BOT_CMD_PARAMETER_STRING, BOT_CMD_PARAMETER_VECTOR, bot_cmd_parm_type, bot_cmd_string, bot_cmds_initialized, bot_commands_init(), LOG_INFO, and strcat().
Referenced by GameCommand_bot_cmd().
 {
     int i;
     string ptype;
     if(!bot_cmds_initialized)
         bot_commands_init();
     LOG_INFO("List of all available commands:\n");
     LOG_INFO("  Command - Parameter Type\n");
     for(i=1;i<BOT_CMD_COUNTER;++i)
     {
         switch(bot_cmd_parm_type[i])
         {
             case BOT_CMD_PARAMETER_FLOAT:
                 ptype = "float number";
                 break;
             case BOT_CMD_PARAMETER_STRING:
                 ptype = "string";
                 break;
             case BOT_CMD_PARAMETER_VECTOR:
                 ptype = "vector";
                 break;
             default:
                 ptype = "none";
                 break;
         }
         LOG_INFO(strcat("  ",bot_cmd_string[i]," - <",ptype,"> \n"));
     }
 }
bool bot_presskeys (entity this)
Definition at line 827 of file scripting.qc.
References autocvar_sv_maxspeed, BOT_CMD_KEY_ATTACK1, BOT_CMD_KEY_ATTACK2, BOT_CMD_KEY_BACKWARD, BOT_CMD_KEY_CHAT, BOT_CMD_KEY_CROUCH, BOT_CMD_KEY_FORWARD, BOT_CMD_KEY_HOOK, BOT_CMD_KEY_JUMP, BOT_CMD_KEY_LEFT, BOT_CMD_KEY_NONE, BOT_CMD_KEY_RIGHT, BOT_CMD_KEY_USE, bot_cmd_keys, movement, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_CHAT, PHYS_INPUT_BUTTON_CROUCH, PHYS_INPUT_BUTTON_HOOK, PHYS_INPUT_BUTTON_JUMP, and PHYS_INPUT_BUTTON_USE.
Referenced by bot_execute_commands_once().
 {
     this.movement = '0 0 0';
     PHYS_INPUT_BUTTON_JUMP(this) = false;
     PHYS_INPUT_BUTTON_CROUCH(this) = false;
     PHYS_INPUT_BUTTON_ATCK(this) = false;
     PHYS_INPUT_BUTTON_ATCK2(this) = false;
     PHYS_INPUT_BUTTON_USE(this) = false;
     PHYS_INPUT_BUTTON_HOOK(this) = false;
     PHYS_INPUT_BUTTON_CHAT(this) = false;
     if(this.bot_cmd_keys == BOT_CMD_KEY_NONE)
         return false;
     if(this.bot_cmd_keys & BOT_CMD_KEY_FORWARD)
         this.movement_x = autocvar_sv_maxspeed;
     else if(this.bot_cmd_keys & BOT_CMD_KEY_BACKWARD)
         this.movement_x = -autocvar_sv_maxspeed;
     if(this.bot_cmd_keys & BOT_CMD_KEY_RIGHT)
         this.movement_y = autocvar_sv_maxspeed;
     else if(this.bot_cmd_keys & BOT_CMD_KEY_LEFT)
         this.movement_y = -autocvar_sv_maxspeed;
     if(this.bot_cmd_keys & BOT_CMD_KEY_JUMP)
         PHYS_INPUT_BUTTON_JUMP(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_CROUCH)
         PHYS_INPUT_BUTTON_CROUCH(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_ATTACK1)
         PHYS_INPUT_BUTTON_ATCK(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_ATTACK2)
         PHYS_INPUT_BUTTON_ATCK2(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_USE)
         PHYS_INPUT_BUTTON_USE(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_HOOK)
         PHYS_INPUT_BUTTON_HOOK(this) = true;
     if(this.bot_cmd_keys & BOT_CMD_KEY_CHAT)
         PHYS_INPUT_BUTTON_CHAT(this) = true;
     return true;
 }
void bot_queuecommand (entity bot, string cmdstring)
Definition at line 24 of file scripting.qc.
References buf_create, precache_sound(), strstrofs, and substring().
Referenced by GameCommand_bot_cmd().
 {
     if(!bot.bot_cmdqueuebuf_allocated)
     {
         bot.bot_cmdqueuebuf = buf_create();
         bot.bot_cmdqueuebuf_allocated = true;
         bot.bot_cmdqueuebuf_start = 0;
         bot.bot_cmdqueuebuf_end = 0;
     }
     bufstr_set(bot.bot_cmdqueuebuf, bot.bot_cmdqueuebuf_end, cmdstring);
     // if the command was a "sound" command, precache the sound NOW
     // this prevents lagging!
     {
         float sp;
         string parm;
         string cmdstr;
         sp = strstrofs(cmdstring, " ", 0);
         if(sp >= 0)
         {
             parm = substring(cmdstring, sp + 1, -1);
             cmdstr = substring(cmdstring, 0, sp);
             if(cmdstr == "sound")
             {
                 // find the LAST word
                 for (;;)
                 {
                     sp = strstrofs(parm, " ", 0);
                     if(sp < 0)
                         break;
                     parm = substring(parm, sp + 1, -1);
                 }
                 precache_sound(parm);
             }
         }
     }
     bot.bot_cmdqueuebuf_end += 1;
 }
string bot_readcommand (entity bot, float idx)
Definition at line 81 of file scripting.qc.
References error.
Referenced by bot_setcurrentcommand().
 {
     if(!bot.bot_cmdqueuebuf_allocated)
         error("readcommand but no queue allocated");
     if(idx < bot.bot_cmdqueuebuf_start)
         error("reading a command in the past");
     if(idx >= bot.bot_cmdqueuebuf_end)
         error("reading a command in the future");
     return bufstr_get(bot.bot_cmdqueuebuf, idx);
 }
void bot_resetqueues ()
Definition at line 1147 of file scripting.qc.
References bot_barriertime, bot_clearqueue(), FOREACH_CLIENT, LAMBDA, string_null, strunzone(), and time.
Referenced by GameCommand_bot_cmd().
 {
     FOREACH_CLIENT(it.isbot, LAMBDA(
         it.bot_cmd_execution_index = 0;
         bot_clearqueue(it);
         // also, cancel all barriers
         it.bot_barrier = 0;
         for(int i = 0; i < it.bot_places_count; ++i)
         {
             strunzone(it.(bot_placenames[i]));
             it.(bot_placenames[i]) = string_null;
         }
         it.bot_places_count = 0;
     ));
     bot_barriertime = time;
 }
void bot_setcurrentcommand (entity this)
Definition at line 1112 of file scripting.qc.
References bot_cmd, bot_cmd_current, bot_cmd_execution_index, bot_decodecommand(), bot_dequeuecommand(), bot_havecommand(), bot_readcommand(), new_pure, and NULL.
Referenced by bot_execute_commands_once().
 {
     bot_cmd = NULL;
     if(!this.bot_cmd_current)
     {
         this.bot_cmd_current = new_pure(bot_cmd);
         this.bot_cmd_current.is_bot_cmd = true;
     }
     bot_cmd = this.bot_cmd_current;
     if(bot_cmd.bot_cmd_index != this.bot_cmd_execution_index || this.bot_cmd_execution_index == 0)
     {
         if(bot_havecommand(this, this.bot_cmd_execution_index))
         {
             string cmdstring;
             cmdstring = bot_readcommand(this, this.bot_cmd_execution_index);
             if(bot_decodecommand(cmdstring))
             {
                 bot_cmd.owner = this;
                 bot_cmd.bot_cmd_index = this.bot_cmd_execution_index;
             }
             else
             {
                 // Invalid command, remove from queue
                 bot_cmd = NULL;
                 bot_dequeuecommand(this, this.bot_cmd_execution_index);
                 this.bot_cmd_execution_index++;
             }
         }
         else
             bot_cmd = NULL;
     }
 }
entity find_bot_by_name (string name)
Definition at line 229 of file scripting.qc.
References entity(), findchainflags(), FL_CLIENT, flags, IS_BOT_CLIENT, and NULL.
Referenced by GameCommand_bot_cmd().
 {
     entity bot;
     bot = findchainflags(flags, FL_CLIENT);
     while (bot)
     {
         if(IS_BOT_CLIENT(bot))
         if(bot.netname==name)
             return bot;
         bot = bot.chain;
     }
     return NULL;
 }
entity find_bot_by_number (float number)
Definition at line 247 of file scripting.qc.
References entity(), findchainflags(), FL_CLIENT, flags, IS_BOT_CLIENT, and NULL.
Referenced by GameCommand_bot_cmd().
 {
     entity bot;
     float c = 0;
     if(!number)
         return NULL;
     bot = findchainflags(flags, FL_CLIENT);
     while (bot)
     {
         if(IS_BOT_CLIENT(bot))
         {
             if(++c==number)
                 return bot;
         }
         bot = bot.chain;
     }
     return NULL;
 }
void SV_ParseClientCommand (string s)
Definition at line 707 of file cmd.qc.
References argv(), Ban_MaybeEnforceBanOnce(), CheatCommand(), chr2str, clientcommand(), ClientCommand_macro_command(), ClientCommand_macro_help(), ClientCommand_macro_usage(), CommonCommand_macro_command(), CommonCommand_macro_help(), CommonCommand_macro_usage(), ENGINE_EVENT, MUTATOR_CALLHOOK, sprint(), str2chr, strcat(), strlen(), strtolower(), SV_ParseClientCommand_floodcheck(), and tokenize_console.
Referenced by bot_cmd_cc().
 {ENGINE_EVENT();
     // If invalid UTF-8, don't even parse it
     string command2 = "";
     float len = strlen(command);
     float i;
     for (i = 0; i < len; ++i)
         command2 = strcat(command2, chr2str(str2chr(command, i)));
     if (command != command2) return;
     // if we're banned, don't even parse the command
     if (Ban_MaybeEnforceBanOnce(this)) return;
     float argc = tokenize_console(command);
     // Guide for working with argc arguments by example:
     // argc:   1    - 2      - 3     - 4
     // argv:   0    - 1      - 2     - 3
     // cmd     vote - master - login - password
     // for floodcheck
     switch (strtolower(argv(0)))
     {
         // exempt commands which are not subject to floodcheck
         case "begin": break;                               // handled by engine in host_cmd.c
         case "download": break;                            // handled by engine in cl_parse.c
         case "mv_getpicture": break;                       // handled by server in this file
         case "pause": break;                               // handled by engine in host_cmd.c
         case "prespawn": break;                            // handled by engine in host_cmd.c
         case "sentcvar": break;                            // handled by server in this file
         case "spawn": break;                               // handled by engine in host_cmd.c
         case "c2s": Net_ClientCommand(this, command); return; // handled by net.qh
         default:
             if (SV_ParseClientCommand_floodcheck(this)) break; // "true": continue, as we're not flooding yet
             else return;                                   // "false": not allowed to continue, halt // print("^1ERROR: ^7ANTISPAM CAUGHT: ", command, ".\n");
     }
     /* NOTE: should this be disabled? It can be spammy perhaps, but hopefully it's okay for now */
     if (argv(0) == "help")
     {
         if (argc == 1)
         {
             sprint(this, "\nClient networked commands:\n");
             ClientCommand_macro_help(this);
             sprint(this, "\nCommon networked commands:\n");
             CommonCommand_macro_help(this);
             sprint(this, "\nUsage:^3 cmd COMMAND...^7, where possible commands are listed above.\n");
             sprint(this, "For help about a specific command, type cmd help COMMAND\n");
             return;
         }
         else if (CommonCommand_macro_usage(argc, this))  // Instead of trying to call a command, we're going to see detailed information about it
         {
             return;
         }
         else if (ClientCommand_macro_usage(argc, this))  // same, but for normal commands now
         {
             return;
         }
     }
     else if (MUTATOR_CALLHOOK(SV_ParseClientCommand, this, strtolower(argv(0)), argc, command))
     {
         return;  // handled by a mutator
     }
     else if (CheatCommand(this, argc))
     {
         return;  // handled by server/cheats.qc
     }
     else if (CommonCommand_macro_command(argc, this, command))
     {
         return;                                          // handled by server/command/common.qc
     }
     else if (ClientCommand_macro_command(argc, this, command)) // continue as usual and scan for normal commands
     {
         return;                                          // handled by one of the above ClientCommand_* functions
     }
     else
     {
         clientcommand(this, command);
     }
 }
Variable Documentation
vector bot_cmd_aim_begin
Definition at line 714 of file scripting.qc.
Referenced by bot_cmd_aim(), and bot_cmd_aimtarget().
float bot_cmd_aim_begintime
Definition at line 712 of file scripting.qc.
Referenced by bot_cmd_aim(), and bot_cmd_aimtarget().
vector bot_cmd_aim_end
Definition at line 715 of file scripting.qc.
Referenced by bot_cmd_aim(), and bot_cmd_aimtarget().
float bot_cmd_aim_endtime
Definition at line 713 of file scripting.qc.
Referenced by bot_cmd_aim(), and bot_cmd_aimtarget().
int bot_cmd_condition_status
Definition at line 585 of file scripting.qc.
Referenced by bot_cmd_else(), bot_cmd_fi(), bot_cmd_if(), and bot_execute_commands_once().
const int BOT_CMD_KEY_ATTACK1 = BIT(5)
Definition at line 820 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_ATTACK2 = BIT(6)
Definition at line 821 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_BACKWARD = BIT(1)
Definition at line 816 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_CHAT = BIT(10)
Definition at line 825 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_CROUCH = BIT(9)
Definition at line 824 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_FORWARD = BIT(0)
Definition at line 815 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_HOOK = BIT(8)
Definition at line 823 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_JUMP = BIT(4)
Definition at line 819 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_LEFT = BIT(3)
Definition at line 818 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_NONE = 0
Definition at line 814 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), bot_cmd_pause(), and bot_presskeys().
const int BOT_CMD_KEY_RIGHT = BIT(2)
Definition at line 817 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
const int BOT_CMD_KEY_USE = BIT(7)
Definition at line 822 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), and bot_presskeys().
int bot_cmd_keys
Definition at line 812 of file scripting.qc.
Referenced by bot_cmd_keypress_handler(), bot_cmd_pause(), and bot_presskeys().
float bot_cmd_wait_time
Definition at line 498 of file scripting.qc.
Referenced by bot_cmd_wait().
float bot_cmdqueuebuf
Definition at line 11 of file scripting.qc.
float bot_cmdqueuebuf_allocated
Definition at line 10 of file scripting.qc.
Referenced by bot_havecommand().
float bot_cmdqueuebuf_end
Definition at line 13 of file scripting.qc.
Referenced by bot_havecommand().
float bot_cmdqueuebuf_start
Definition at line 12 of file scripting.qc.
Referenced by bot_havecommand().
int bot_exec_status
Definition at line 477 of file scripting.qc.
Referenced by bot_cmd_continue(), bot_cmd_pause(), bot_cmd_wait(), bot_cmd_wait_until(), and bot_execute_commands_once().
string bot_placenames[MAX_BOT_PLACES]
Definition at line 106 of file scripting.qc.
Referenced by bot_getplace().
entity bot_places[MAX_BOT_PLACES]
Definition at line 105 of file scripting.qc.
Referenced by bot_getplace().
float bot_places_count
Definition at line 104 of file scripting.qc.
Referenced by bot_getplace().
const int CMD_CONDITION_false = 2
Definition at line 589 of file scripting.qc.
Referenced by bot_cmd_if(), and bot_execute_commands_once().
const int CMD_CONDITION_false_BLOCK = 8
Definition at line 591 of file scripting.qc.
Referenced by bot_cmd_else(), and bot_execute_commands_once().
const int CMD_CONDITION_NONE = 0
Definition at line 587 of file scripting.qc.
Referenced by bot_cmd_fi(), and bot_cmd_if().
const int CMD_CONDITION_true = 1
Definition at line 588 of file scripting.qc.
Referenced by bot_cmd_if(), and bot_execute_commands_once().
const int CMD_CONDITION_true_BLOCK = 4
Definition at line 590 of file scripting.qc.
Referenced by bot_cmd_else(), bot_cmd_if(), and bot_execute_commands_once().
const int MAX_BOT_PLACES = 4
Definition at line 103 of file scripting.qc.
Referenced by bot_getplace().
int state
Definition at line 8 of file scripting.qc.
Referenced by bot_cmd_debug_assert_canfire().
entity tuba_note
Definition at line 1055 of file scripting.qc.
Referenced by bot_cmd_debug_assert_canfire().