Xonotic: menu/xonotic/image.qc File Reference
image.qc File Reference
#include "image.qh"
Functions
entity makeXonoticImage (string theImage, float theAspect)
void XonoticImage_configureXonoticImage (entity me, string theImage, float theAspect)
Function Documentation
makeXonoticImage()
entity makeXonoticImage (string theImage, float theAspect)
Definition at line 3 of file image.qc.
References entity(), and NEW.
Referenced by XonoticMapInfoDialog_fill(), and XonoticWinnerDialog_fill().
 {
     entity me;
     me = NEW(XonoticImage);
     me.configureXonoticImage(me, theImage, theAspect);
     return me;
 }
XonoticImage_configureXonoticImage()
void XonoticImage_configureXonoticImage (entity me, string theImage, float theAspect)
Definition at line 10 of file image.qc.
 {
     me.configureImage(me, theImage);
     me.forcedAspect = theAspect;
 }