Xonotic: common/gamemodes/gamemode/onslaught/onslaught.qc File Reference
onslaught.qc File Reference
Macros
#define GAMEMODE_ONSLAUGHT_H
Functions
void ons_Initialize ()
REGISTER_MUTATOR (ons, false)
Variables
float autocvar_g_onslaught_point_limit
Macro Definition Documentation
#define GAMEMODE_ONSLAUGHT_H
Definition at line 2 of file onslaught.qc.
Function Documentation
void ons_Initialize ()
Referenced by REGISTER_MUTATOR().
REGISTER_MUTATOR (ons , false)
Definition at line 7 of file onslaught.qc.
References ActivateTeamplay(), autocvar_g_onslaught_point_limit, autocvar_leadlimit_override, autocvar_timelimit_override, error, have_team_spawns, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, ons_Initialize(), SetLimits(), and time.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         ons_Initialize();
         ActivateTeamplay();
         SetLimits(autocvar_g_onslaught_point_limit, autocvar_leadlimit_override, autocvar_timelimit_override, -1);
         have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back ons_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return false;
 }
Variable Documentation
float autocvar_g_onslaught_point_limit
Definition at line 4 of file onslaught.qc.
Referenced by REGISTER_MUTATOR().