Xonotic: Sound Class Reference
Sound Class Reference
Public Member Functions
Sound (string() path)
string _Sound_fixpath (string base)
ATTRIB (Sound, sound_str, string())
virtual void describe ()
virtual void display ()
virtual void sound_precache ()
Public Attributes
int m_id = 0
Detailed Description
Definition at line 95 of file sound.qh.
Constructor & Destructor Documentation
Sound::Sound (string() path) inline
Definition at line 98 of file sound.qh.
References CONSTRUCT.
     {
         CONSTRUCT(Sound);
         this.sound_str = path;
     }
Member Function Documentation
string Sound::_Sound_fixpath (string base) inline
Definition at line 104 of file sound.qh.
References extensions, LOG_WARNF, strcat(), string_null, and tryext.
     {
         if (base == "") return string_null;
 #ifdef SVQC
         return strcat(base, ".wav");  // let the client engine decide
 #else
         #define extensions(x) \
             x(wav) \
             x(ogg) \
             x(flac) \
         #define tryext(ext) { string s = strcat(base, "." #ext); if (fexists(strcat("sound/", s))) return s; }
         extensions(tryext);
         LOG_WARNF("Missing sound: \"%s\"", strcat("sound/", base));
         #undef tryext
         #undef extensions
         return string_null;
 #endif
     }
Sound::ATTRIB (Sound , sound_str , string())
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Sound::sound_precache () inline virtual
Definition at line 123 of file sound.qh.
References precache_sound(), profile(), Sound_fixpath, and TC.
     {
         TC(Sound, this);
         string s = Sound_fixpath(this);
         if (!s) return;
         profile(sprintf("precache_sound(\"%s\")", s));
         precache_sound(s);
     }
Member Data Documentation
int Sound::m_id = 0
Definition at line 96 of file sound.qh.
The documentation for this class was generated from the following file:
common/sounds/sound.qh