Xonotic: server/command/vote.qc File Reference
vote.qc File Reference
#include "vote.qh"
#include <common/command/_mod.qh>
#include "common.qh"
#include "../g_damage.qh"
#include "../g_world.qh"
#include "../race.qh"
#include "../round_handler.qh"
#include "../scores.qh"
#include "../mutators/_mod.qh"
#include <common/constants.qh>
#include <common/net_linked.qh>
#include <common/mapinfo.qh>
#include <common/notifications/all.qh>
#include <common/playerstats.qh>
#include <common/util.qh>
Macros
#define spectators_allowed (!autocvar_sv_vote_nospectators || (autocvar_sv_vote_nospectators == 1 && (warmup_stage || intermission_running)))
#define VOTE_COMMAND(name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { print_to(caller, strcat(" ^2", name, "^7: ", description)); } }
#define VOTE_COMMAND(name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(2))) { function; return; } } }
#define VOTE_COMMAND(name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(1))) { function; return true; } } }
#define VOTE_COMMANDS(request, caller, arguments, command)
Functions
void Nagger_Init ()
void Nagger_ReadyCounted ()
bool Nagger_SendEntity (entity this, entity to, float sendflags)
void Nagger_VoteChanged ()
void Nagger_VoteCountChanged ()
string OriginalCallerName ()
void ReadyCount ()
void ReadyRestart ()
void ReadyRestart_force ()
void ReadyRestart_think (entity this)
void reset_map (bool dorespawn)
string ValidateMap (string validated_map, entity caller)
void VoteAccept ()
void VoteCommand (float request, entity caller, float argc, string vote_command)
void VoteCommand_abstain (float request, entity caller)
void VoteCommand_call (float request, entity caller, float argc, string vote_command)
float Votecommand_check_assignment (entity caller, float assignment)
float VoteCommand_checkargs (float startpos, float argc)
float VoteCommand_checkinlist (string vote_command, string list)
float VoteCommand_checknasty (string vote_command)
string VoteCommand_extractcommand (string input, float startpos, float argc)
float VoteCommand_macro_command (entity caller, float argc, string vote_command)
void VoteCommand_macro_help (entity caller, float argc)
void VoteCommand_master (float request, entity caller, float argc, string vote_command)
void VoteCommand_no (float request, entity caller)
float VoteCommand_parse (entity caller, string vote_command, string vote_list, float startpos, float argc)
void VoteCommand_status (float request, entity caller)
void VoteCommand_stop (float request, entity caller)
void VoteCommand_yes (float request, entity caller)
void VoteCount (float first_count)
void VoteReject ()
void VoteReset ()
void VoteSpam (float notvoters, float mincount, string result)
void VoteStop (entity stopper)
void VoteThink ()
void VoteTimeout ()
Macro Definition Documentation
#define spectators_allowed (!autocvar_sv_vote_nospectators || (autocvar_sv_vote_nospectators == 1 && (warmup_stage || intermission_running)))
Definition at line 201 of file vote.qc.
Referenced by VoteCommand_call(), and VoteCommand_master().
#define VOTE_COMMAND (name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { print_to(caller, strcat(" ^2", name, "^7: ", description)); } }
#define VOTE_COMMAND (name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(2))) { function; return; } } }
#define VOTE_COMMAND (name, function, description, assignment) { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(1))) { function; return true; } } }
#define VOTE_COMMANDS (request, caller, arguments, command)
Value:
VOTE_COMMAND("abstain", VoteCommand_abstain(request, caller), "Abstain your vote in current vote", VC_ASGNMNT_CLIENTONLY) \
    VOTE_COMMAND("call", VoteCommand_call(request, caller, arguments, command), "Create a new vote for players to decide on", VC_ASGNMNT_BOTH) \
    VOTE_COMMAND("help", VoteCommand_macro_help(caller, arguments), "Shows this information", VC_ASGNMNT_BOTH) \
    VOTE_COMMAND("master", VoteCommand_master(request, caller, arguments, command), "Full control over all voting and vote commands", VC_ASGNMNT_CLIENTONLY) \
    VOTE_COMMAND("no", VoteCommand_no(request, caller), "Select no in current vote", VC_ASGNMNT_CLIENTONLY) \
    VOTE_COMMAND("status", VoteCommand_status(request, caller), "Prints information about current vote", VC_ASGNMNT_BOTH) \
    VOTE_COMMAND("stop", VoteCommand_stop(request, caller), "Immediately end a vote", VC_ASGNMNT_BOTH) \
    VOTE_COMMAND("yes", VoteCommand_yes(request, caller), "Select yes in current vote", VC_ASGNMNT_CLIENTONLY) \
    /* nothing */
Definition at line 1083 of file vote.qc.
Referenced by VoteCommand_macro_command(), and VoteCommand_macro_help().
Function Documentation
void Nagger_Init ()
Definition at line 89 of file vote.qc.
References nagger, Nagger_SendEntity(), and new_pure.
Referenced by spawnfunc().
 {
     Net_LinkEntity(nagger = new_pure(nagger), false, 0, Nagger_SendEntity);
 }
void Nagger_ReadyCounted ()
Definition at line 104 of file vote.qc.
References BIT, and nagger.
Referenced by ReadyCount(), and ReadyRestart_force().
 {
     if (nagger) nagger.SendFlags |= BIT(0);
 }
bool Nagger_SendEntity (entity this, entity to, float sendflags)
Definition at line 28 of file vote.qc.
References BIT, entity(), IS_REAL_CLIENT, maxclients, nextent(), readycount, vote_accept_count, vote_called, vote_called_display, vote_needed_overall, vote_reject_count, warmup_stage, WriteByte(), WriteChar(), and WriteString().
Referenced by Nagger_Init().
 {
     int nags, i, f, b;
     entity e;
     WriteHeader(MSG_ENTITY, ENT_CLIENT_NAGGER);
     // bits:
     //   1 = ready
     //   2 = player needs to ready up
     //   4 = vote
     //   8 = player needs to vote
     //  16 = warmup
     // sendflags:
     //  64 = vote counts
     // 128 = vote string
     nags = 0;
     if (readycount)
     {
         nags |= BIT(0);
         if (to.ready == 0) nags |= BIT(1);
     }
     if (vote_called)
     {
         nags |= BIT(2);
         if (to.vote_selection == 0) nags |= BIT(3);
     }
     if (warmup_stage) nags |= BIT(4);
     if (sendflags & BIT(6)) nags |= BIT(6);
     if (sendflags & BIT(7)) nags |= BIT(7);
     if (!(nags & 4))  // no vote called? send no string
         nags &= ~(BIT(6) | BIT(7));
     WriteByte(MSG_ENTITY, nags);
     if (nags & BIT(6))
     {
         WriteByte(MSG_ENTITY, vote_accept_count);
         WriteByte(MSG_ENTITY, vote_reject_count);
         WriteByte(MSG_ENTITY, vote_needed_overall);
         WriteChar(MSG_ENTITY, to.vote_selection);
     }
     if (nags & BIT(7)) WriteString(MSG_ENTITY, vote_called_display);
     if (nags & 1)
     {
         for (i = 1; i <= maxclients; i += 8)
         {
             for (f = 0, e = edict_num(i), b = 1; b < 256; b *= 2, e = nextent(e))
                 if (!IS_REAL_CLIENT(e) || e.ready) f |= b;
             WriteByte(MSG_ENTITY, f);
         }
     }
     return true;
 }
void Nagger_VoteChanged ()
Definition at line 94 of file vote.qc.
References BIT, and nagger.
Referenced by VoteCommand_call(), VoteCommand_master(), and VoteReset().
 {
     if (nagger) nagger.SendFlags |= BIT(7);
 }
void Nagger_VoteCountChanged ()
Definition at line 99 of file vote.qc.
References BIT, and nagger.
Referenced by VoteCount().
 {
     if (nagger) nagger.SendFlags |= BIT(6);
 }
string OriginalCallerName ()
Definition at line 110 of file vote.qc.
References IS_REAL_CLIENT, playername(), vote_caller, and vote_caller_name.
Referenced by VoteAccept(), VoteCommand_call(), VoteCommand_master(), VoteCommand_status(), VoteReject(), VoteStop(), and VoteTimeout().
 {
     if (IS_REAL_CLIENT(vote_caller)) return playername(vote_caller, false);
     return vote_caller_name;
 }
void ReadyCount ()
Definition at line 475 of file vote.qc.
References bound(), cvar(), floor(), FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, Nagger_ReadyCounted(), readycount, and ReadyRestart().
Referenced by ClientCommand_ready(), and ClientDisconnect().
 {
     float ready_needed_factor, ready_needed_count;
     float t_ready = 0, t_players = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it) && (IS_PLAYER(it) || it.caplayer == 1), LAMBDA(
         ++t_players;
         if (it.ready) ++t_ready;
     ));
     readycount = t_ready;
     Nagger_ReadyCounted();
     ready_needed_factor = bound(0.5, cvar("g_warmup_majority_factor"), 0.999);
     ready_needed_count = floor(t_players * ready_needed_factor) + 1;
     if (readycount >= ready_needed_count) ReadyRestart();
 }
void ReadyRestart ()
Definition at line 463 of file vote.qc.
References autocvar_sv_ready_restart_after_countdown, localcmd, MUTATOR_CALLHOOK, race_completing, ReadyRestart_force(), and Score_ClearAll().
Referenced by CheckRules_World(), GameCommand_allready(), ReadyCount(), and StartFrame().
 {
     if (MUTATOR_CALLHOOK(ReadyRestart_Deny) || game_stopped || race_completing) localcmd("restart\n");
     else localcmd("\nsv_hook_gamerestart\n");
     // Reset ALL scores, but only do that at the beginning of the countdown if sv_ready_restart_after_countdown is off!
     // Otherwise scores could be manipulated during the countdown.
     if (!autocvar_sv_ready_restart_after_countdown) Score_ClearAll();
     ReadyRestart_force();
 }
void ReadyRestart_force ()
Definition at line 404 of file vote.qc.
References autocvar_sv_eventlog, autocvar_sv_ready_restart_after_countdown, autocvar_sv_timeout, autocvar_sv_timeout_number, autocvar_teamplay_lockonrestart, autocvar_timelimit, autocvar_timelimit_overtime, bprint(), checkrules_overtimesadded, checkrules_suddendeathend, checkrules_suddendeathwarning, cvar_set(), entity(), FOREACH_CLIENT, ftos(), g_race_qualifying, game_starttime, GameLogEcho(), IS_PLAYER, IS_REAL_CLIENT, LAMBDA, lockteams, Nagger_ReadyCounted(), new_pure, readycount, readyrestart_happened, ReadyRestart_think(), reset_map(), RESTART_COUNTDOWN, restart_mapalreadyrestarted, setthink, teamplay, time, VoteReset(), and warmup_stage.
Referenced by assault_new_round(), and ReadyRestart().
 {
     if (time <= game_starttime && game_stopped)
         return;
     bprint("^1Server is restarting...\n");
     VoteReset();
     // clear overtime, we have to decrease timelimit to its original value again.
     if (checkrules_overtimesadded > 0 && g_race_qualifying != 2)
         cvar_set("timelimit", ftos(autocvar_timelimit - (checkrules_overtimesadded * autocvar_timelimit_overtime)));
     checkrules_suddendeathend = checkrules_overtimesadded = checkrules_suddendeathwarning = 0;
     readyrestart_happened = true;
     game_starttime = time + RESTART_COUNTDOWN;
     // clear player attributes
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(
         it.alivetime = 0;
         it.killcount = 0;
         PS_GR_P_ADDVAL(it, PLAYERSTATS_ALIVETIME, -PS_GR_P_ADDVAL(it, PLAYERSTATS_ALIVETIME, 0));
     ));
     restart_mapalreadyrestarted = false; // reset this var, needed when cvar sv_ready_restart_repeatable is in use
     // disable the warmup global for the server
     warmup_stage = 0;                // once the game is restarted the game is in match stage
     // reset the .ready status of all players (also spectators)
     FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(it.ready = false));
     readycount = 0;
     Nagger_ReadyCounted();  // NOTE: this causes a resend of that entity, and will also turn off warmup state on the client
     // lock teams with lockonrestart
     if (autocvar_teamplay_lockonrestart && teamplay)
     {
         lockteams = true;
         bprint("^1The teams are now locked.\n");
     }
     // initiate the restart-countdown-announcer entity
     if (autocvar_sv_ready_restart_after_countdown)
     {
         entity restart_timer = new_pure(restart_timer);
         setthink(restart_timer, ReadyRestart_think);
         restart_timer.nextthink = game_starttime;
     }
     // after a restart every players number of allowed timeouts gets reset, too
     if (autocvar_sv_timeout)
     {
         FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), LAMBDA(it.allowed_timeouts = autocvar_sv_timeout_number));
     }
     // reset map immediately if this cvar is not set
     if (!autocvar_sv_ready_restart_after_countdown) reset_map(true);
     if (autocvar_sv_eventlog) GameLogEcho(":restart");
 }
void ReadyRestart_think (entity this)
Definition at line 395 of file vote.qc.
References reset_map(), restart_mapalreadyrestarted, and Score_ClearAll().
Referenced by ReadyRestart_force().
 {
     restart_mapalreadyrestarted = true;
     reset_map(true);
     Score_ClearAll();
     delete(this);
 }
void reset_map (bool dorespawn)
Definition at line 335 of file vote.qc.
References FL_PROJECTILE, FOREACH_ENTITY_ORDERED, game_starttime, IS_NOT_A_CLIENT, MUTATOR_CALLHOOK, round_handler_IsActive, round_handler_Reset(), and time.
Referenced by ReadyRestart_force(), ReadyRestart_think(), and round_handler_Think().
 {
     if (time <= game_starttime)
     {
         if (game_stopped)
             return;
         if (round_handler_IsActive())
             round_handler_Reset(game_starttime);
     }
     MUTATOR_CALLHOOK(reset_map_global);
     FOREACH_ENTITY_ORDERED(IS_NOT_A_CLIENT(it), {
         if (it.reset)
         {
             it.reset(it);
             continue;
         }
         if (it.team_saved) it.team = it.team_saved;
         if (it.flags & FL_PROJECTILE) delete(it);  // remove any projectiles left
     });
     // Waypoints and assault start come LAST
     FOREACH_ENTITY_ORDERED(IS_NOT_A_CLIENT(it), {
         if (it.reset2) it.reset2(it);
     });
     FOREACH_CLIENT(IS_PLAYER(it) && STAT(FROZEN, it), LAMBDA(Unfreeze(it)));
     // Moving the player reset code here since the player-reset depends
     // on spawnpoint entities which have to be reset first --blub
     if (dorespawn)
     {
         if (!MUTATOR_CALLHOOK(reset_map_players))
         {
             if (restart_mapalreadyrestarted || (time < game_starttime))
             {
                 FOREACH_CLIENT(IS_PLAYER(it),
                 {
                     /*
                     only reset players if a restart countdown is active
                     this can either be due to cvar sv_ready_restart_after_countdown having set
                     restart_mapalreadyrestarted to 1 after the countdown ended or when
                     sv_ready_restart_after_countdown is not used and countdown is still running
                     */
                     // NEW: changed behaviour so that it prevents that previous spectators/observers suddenly spawn as players
                     // PlayerScore_Clear(it);
                     it.killcount = 0;
                     // stop the player from moving so that he stands still once he gets respawned
                     it.velocity = '0 0 0';
                     it.avelocity = '0 0 0';
                     it.movement = '0 0 0';
                     PutClientInServer(it);
                 });
             }
         }
     }
 }
string ValidateMap (string validated_map, entity caller)
Definition at line 540 of file vote.qc.
References autocvar_sv_vote_override_mostrecent, Map_IsRecent(), MapInfo_CheckMap(), MapInfo_FixName(), print_to(), strcat(), and string_null.
Referenced by VoteCommand_parse().
 {
     validated_map = MapInfo_FixName(validated_map);
     if (!validated_map)
     {
         print_to(caller, "This map is not available on this server.");
         return string_null;
     }
     if (!autocvar_sv_vote_override_mostrecent && caller)
     {
         if (Map_IsRecent(validated_map))
         {
             print_to(caller, "This server does not allow for recent maps to be played again. Please be patient for some rounds.");
             return string_null;
         }
     }
     if (!MapInfo_CheckMap(validated_map))
     {
         print_to(caller, strcat("^1Invalid mapname, \"^3", validated_map, "^1\" does not support the current game mode."));
         return string_null;
     }
     return validated_map;
 }
void VoteAccept ()
Definition at line 154 of file vote.qc.
References bprint(), localcmd, NULL, OriginalCallerName(), strcat(), vote_called, vote_called_command, vote_called_display, vote_caller, VOTE_MASTER, and VoteReset().
 {
     bprint("\{1}^2* ^3", OriginalCallerName(), "^2's vote for ^1", vote_called_display, "^2 was accepted\n");
     if ((vote_called == VOTE_MASTER) && vote_caller) vote_caller.vote_master = 1;
     else localcmd(strcat(vote_called_command, "\n"));
     if (vote_caller)   vote_caller.vote_waittime = 0;  // people like your votes, you don't need to wait to vote again
     VoteReset();
     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_VOTE_ACCEPT);
 }
void VoteCommand (float request, entity caller, float argc, string vote_command)
Definition at line 1137 of file vote.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), strcat(), VoteCommand_macro_command(), and VoteCommand_macro_help().
Referenced by COMMON_COMMAND().
 {
     // Guide for working with argc arguments by example:
     // argc:   1    - 2      - 3     - 4
     // argv:   0    - 1      - 2     - 3
     // cmd     vote - master - login - password
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (VoteCommand_macro_command(caller, argc, vote_command)) return;
         }
         default:
             print_to(caller, strcat(((argv(1) != "") ? strcat("Unknown vote command \"", argv(1), "\"") : "No command provided"), ". For a list of supported commands, try ", GetCommandPrefix(caller), " vote help.\n"));
         case CMD_REQUEST_USAGE:
         {
             VoteCommand_macro_help(caller, argc);
             return;
         }
     }
 }
void VoteCommand_abstain (float request, entity caller)
Definition at line 716 of file vote.qc.
References autocvar_sv_vote_change, autocvar_sv_vote_singlecount, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), msg_entity, print_to(), strcat(), vote_called, VOTE_SELECT_ABSTAIN, VOTE_SELECT_NULL, and VoteCount().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!vote_called) { print_to(caller, "^1No vote called."); }
             else if (caller.vote_selection != VOTE_SELECT_NULL && !autocvar_sv_vote_change)
             {
                 print_to(caller, "^1You have already voted.");
             }
             else  // everything went okay, continue changing vote
             {
                 print_to(caller, "^1You abstained from your vote.");
                 caller.vote_selection = VOTE_SELECT_ABSTAIN;
                 msg_entity = caller;
                 if (!autocvar_sv_vote_singlecount)   VoteCount(false); }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote abstain"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void VoteCommand_call (float request, entity caller, float argc, string vote_command)
Definition at line 748 of file vote.qc.
References autocvar_sv_eventlog, autocvar_sv_vote_call, autocvar_sv_vote_commands, autocvar_sv_vote_gamestart, autocvar_sv_vote_timeout, autocvar_sv_vote_wait, bprint(), ceil(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, FOREACH_CLIENT, ftos(), game_starttime, GameLogEcho(), GetCallerName(), GetCommandPrefix(), IS_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, msg_entity, Nagger_VoteChanged(), NULL, OriginalCallerName(), print_to(), spectators_allowed, strcat(), strzone(), time, timeout_status, vote_called, vote_called_command, vote_called_display, vote_caller, vote_caller_name, vote_endtime, VOTE_NORMAL, vote_parsed_command, vote_parsed_display, VOTE_SELECT_ACCEPT, VoteCommand_checknasty(), VoteCommand_extractcommand(), VoteCommand_parse(), and VoteCount().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             float tmp_playercount = 0;
             vote_command = VoteCommand_extractcommand(vote_command, 2, argc);
             if (!autocvar_sv_vote_call && caller) { print_to(caller, "^1Vote calling is not allowed."); }
             else if (!autocvar_sv_vote_gamestart && time < game_starttime)
             {
                 print_to(caller, "^1Vote calling is not allowed before the match has started.");
             }
             else if (vote_called)
             {
                 print_to(caller, "^1There is already a vote called.");
             }
             else if (!spectators_allowed && (caller && !IS_PLAYER(caller)))
             {
                 print_to(caller, "^1Only players can call a vote.");
             }
             else if (caller && !IS_CLIENT(caller))
             {
                 print_to(caller, "^1Only connected clients can vote.");
             }
             else if (timeout_status)
             {
                 print_to(caller, "^1You can not call a vote while a timeout is active.");
             }
             else if (caller && (time < caller.vote_waittime))
             {
                 print_to(caller, strcat("^1You have to wait ^2", ftos(ceil(caller.vote_waittime - time)), "^1 seconds before you can again call a vote."));
             }
             else if (!VoteCommand_checknasty(vote_command))
             {
                 print_to(caller, "^1Syntax error in command, see 'vhelp' for more info.");
             }
             else if (!VoteCommand_parse(caller, vote_command, autocvar_sv_vote_commands, 2, argc))
             {
                 print_to(caller, "^1This command is not acceptable, see 'vhelp' for more info.");
             }
             else  // everything went okay, continue with calling the vote
             {
                 vote_caller = caller;  // remember who called the vote
                 vote_caller_name = strzone(GetCallerName(vote_caller));
                 vote_called = VOTE_NORMAL;
                 vote_called_command = strzone(vote_parsed_command);
                 vote_called_display = strzone(vote_parsed_display);
                 vote_endtime = time + autocvar_sv_vote_timeout;
                 if (caller)
                 {
                     caller.vote_selection = VOTE_SELECT_ACCEPT;
                     caller.vote_waittime = time + autocvar_sv_vote_wait;
                     msg_entity = caller;
                 }
                 FOREACH_CLIENT(IS_REAL_CLIENT(it), LAMBDA(++tmp_playercount));
                 if (tmp_playercount > 1)   Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_VOTE_CALL);  // don't announce a "vote now" sound if player is alone
                 bprint("\{1}^2* ^3", OriginalCallerName(), "^2 calls a vote for ", vote_called_display, "\n");
                 if (autocvar_sv_eventlog)   GameLogEcho(strcat(":vote:vcall:", ftos(vote_caller.playerid), ":", vote_called_display));
                 Nagger_VoteChanged();
                 VoteCount(true);  // needed if you are the only one
             }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote call command"));
             print_to(caller, "  Where 'command' is the command to request a vote upon.");
             print_to(caller, strcat("Examples: ", GetCommandPrefix(caller), " vote call gotomap dance"));
             print_to(caller, strcat("          ", GetCommandPrefix(caller), " vote call endmatch"));
             return;
         }
     }
 }
float Votecommand_check_assignment (entity caller, float assignment)
Definition at line 500 of file vote.qc.
References VC_ASGNMNT_BOTH, VC_ASGNMNT_CLIENTONLY, and VC_ASGNMNT_SERVERONLY.
 {
     float from_server = (!caller);
     if ((assignment == VC_ASGNMNT_BOTH)
         || ((!from_server && assignment == VC_ASGNMNT_CLIENTONLY)
         || (from_server && assignment == VC_ASGNMNT_SERVERONLY))) return true;
     return false;
 }
float VoteCommand_checkargs (float startpos, float argc)
Definition at line 568 of file vote.qc.
References argv(), cvar_string(), CVAR_TYPEFLAG_EXISTS, LOG_INFO, p, stof(), strcat(), strlen(), strstrofs, and substring().
Referenced by VoteCommand_parse().
 {
     float p, q, check, minargs;
     string cvarname = strcat("sv_vote_command_restriction_", argv(startpos));
     string cmdrestriction = "";  // No we don't.
     string charlist, arg;
     float checkmate;
     if(cvar_type(cvarname) & CVAR_TYPEFLAG_EXISTS)
         cmdrestriction = cvar_string(cvarname);
     else
         LOG_INFO("NOTE: ", cvarname, " does not exist, no restrictions will be applied.\n");
     if (cmdrestriction == "") return true;
     ++startpos;  // skip command name
     // check minimum arg count
     // 0 args: argc == startpos
     // 1 args: argc == startpos + 1
     // ...
     minargs = stof(cmdrestriction);
     if (argc - startpos < minargs) return false;
     p = strstrofs(cmdrestriction, ";", 0);  // find first semicolon
     for ( ; ; )
     {
         // we know that at any time, startpos <= argc - minargs
         // so this means: argc-minargs >= startpos >= argc, thus
         // argc-minargs >= argc, thus minargs <= 0, thus all minargs
         // have been seen already
         if (startpos >= argc) // all args checked? GOOD
             break;
         if (p < 0)            // no more args? FAIL
         {
             // exception: exactly minargs left, this one included
             if (argc - startpos == minargs) break;
             // otherwise fail
             return false;
         }
         // cut to next semicolon
         q = strstrofs(cmdrestriction, ";", p + 1);  // find next semicolon
         if (q < 0) charlist = substring(cmdrestriction, p + 1, -1);
         else charlist = substring(cmdrestriction, p + 1, q - (p + 1));
         // in case we ever want to allow semicolons in VoteCommand_checknasty
         // charlist = strreplace("^^", ";", charlist);
         if (charlist != "")
         {
             // verify the arg only contains allowed chars
             arg = argv(startpos);
             checkmate = strlen(arg);
             for (check = 0; check < checkmate; ++check)
                 if (strstrofs(charlist, substring(arg, check, 1), 0) < 0) return false;
             // not allowed character
             // all characters are allowed. FINE.
         }
         ++startpos;
         --minargs;
         p = q;
     }
     return true;
 }
float VoteCommand_checkinlist (string vote_command, string list)
Definition at line 531 of file vote.qc.
References strcat(), and strstrofs.
Referenced by VoteCommand_parse().
 {
     string l = strcat(" ", list, " ");
     if (strstrofs(l, strcat(" ", vote_command, " "), 0) >= 0) return true;
     return false;
 }
float VoteCommand_checknasty (string vote_command)
Definition at line 521 of file vote.qc.
References strstrofs.
Referenced by VoteCommand_call(), and VoteCommand_master().
 {
     if ((strstrofs(vote_command, ";", 0) >= 0)
         || (strstrofs(vote_command, "\n", 0) >= 0)
         || (strstrofs(vote_command, "\r", 0) >= 0)
         || (strstrofs(vote_command, "$", 0) >= 0)) return false;
     return true;
 }
string VoteCommand_extractcommand (string input, float startpos, float argc)
Definition at line 511 of file vote.qc.
References argv_end_index, argv_start_index, and substring().
Referenced by VoteCommand_call(), and VoteCommand_master().
 {
     string output;
     if ((argc - 1) < startpos) output = "";
     else output = substring(input, argv_start_index(startpos), argv_end_index(-1) - argv_start_index(startpos));
     return output;
 }
float VoteCommand_macro_command (entity caller, float argc, string vote_command)
Definition at line 1121 of file vote.qc.
References CMD_REQUEST_COMMAND, and VOTE_COMMANDS.
Referenced by VoteCommand().
 {
     #define VOTE_COMMAND(name, function, description, assignment) \
         { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(1))) { function; return true; } } }
     VOTE_COMMANDS(CMD_REQUEST_COMMAND, caller, argc, vote_command);
 #undef VOTE_COMMAND
     return false;
 }
void VoteCommand_macro_help (entity caller, float argc)
Definition at line 1094 of file vote.qc.
References argv(), autocvar_sv_vote_commands, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), strcat(), and VOTE_COMMANDS.
Referenced by VoteCommand().
 {
     string command_origin = GetCommandPrefix(caller);
     if (argc == 2 || argv(2) == "help")  // help display listing all commands
     {
         print_to(caller, "\nVoting commands:\n");
         #define VOTE_COMMAND(name, function, description, assignment) \
             { if (Votecommand_check_assignment(caller, assignment)) { print_to(caller, strcat("  ^2", name, "^7: ", description)); } }
         VOTE_COMMANDS(0, caller, 0, "");
 #undef VOTE_COMMAND
         print_to(caller, strcat("\nUsage:^3 ", command_origin, " vote COMMAND...^7, where possible commands are listed above.\n"));
         print_to(caller, strcat("For help about a specific command, type ", command_origin, " vote help COMMAND"));
         print_to(caller, strcat("\n^7You can call a vote for or execute these commands: ^3", autocvar_sv_vote_commands, "^7 and maybe further ^3arguments^7"));
     }
     else  // usage for individual command
     {
         #define VOTE_COMMAND(name, function, description, assignment) \
             { if (Votecommand_check_assignment(caller, assignment)) { if (name == strtolower(argv(2))) { function; return; } } }
         VOTE_COMMANDS(CMD_REQUEST_USAGE, caller, argc, "");
 #undef VOTE_COMMAND
     }
 }
void VoteCommand_master (float request, entity caller, float argc, string vote_command)
Definition at line 832 of file vote.qc.
References argv(), autocvar_sv_eventlog, autocvar_sv_vote_commands, autocvar_sv_vote_master, autocvar_sv_vote_master_callable, autocvar_sv_vote_master_commands, autocvar_sv_vote_master_password, autocvar_sv_vote_timeout, autocvar_sv_vote_wait, bprint(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, ftos(), GameLogEcho(), GetCallerName(), GetCommandPrefix(), IS_PLAYER, localcmd, Nagger_VoteChanged(), OriginalCallerName(), print_to(), spectators_allowed, strcat(), strzone(), time, timeout_status, vote_called, vote_called_command, vote_called_display, vote_caller, vote_caller_name, vote_endtime, VOTE_MASTER, vote_parsed_command, vote_parsed_display, VOTE_SELECT_ACCEPT, VoteCommand_checknasty(), VoteCommand_extractcommand(), VoteCommand_parse(), and VoteCount().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (autocvar_sv_vote_master)
             {
                 switch (strtolower(argv(2)))
                 {
                     case "do":
                     {
                         vote_command = VoteCommand_extractcommand(vote_command, 3, argc);
                         if (!caller.vote_master) { print_to(caller, "^1You do not have vote master privelages."); }
                         else if (!VoteCommand_checknasty(vote_command))
{
                             print_to(caller, "^1Syntax error in command, see 'vhelp' for more info.");
                         }
                         else if (!VoteCommand_parse(caller, vote_command, strcat(autocvar_sv_vote_commands, " ", autocvar_sv_vote_master_commands), 3, argc))
{
                             print_to(caller, "^1This command is not acceptable, see 'vhelp' for more info.");
                         }
                         else  // everything went okay, proceed with command
{
                             localcmd(strcat(vote_parsed_command, "\n"));
                             print_to(caller, strcat("Executing command '", vote_parsed_display, "' on server."));
                             bprint("\{1}^2* ^3", GetCallerName(caller), "^2 used their ^3master^2 status to do \"^2", vote_parsed_display, "^2\".\n");
                             if (autocvar_sv_eventlog)   GameLogEcho(strcat(":vote:vdo:", ftos(caller.playerid), ":", vote_parsed_display)); }
                         return;
                     }
                     case "login":
                     {
                         if (autocvar_sv_vote_master_password == "") { print_to(caller, "^1Login to vote master is not allowed."); }
                         else if (caller.vote_master)
{
                             print_to(caller, "^1You are already logged in as vote master.");
                         }
                         else if (autocvar_sv_vote_master_password != argv(3))
{
                             print_to(caller, strcat("Rejected vote master login from ", GetCallerName(caller)));
                         }
                         else  // everything went okay, proceed with giving this player master privilages
{
                             caller.vote_master = true;
                             print_to(caller, strcat("Accepted vote master login from ", GetCallerName(caller)));
                             bprint("\{1}^2* ^3", GetCallerName(caller), "^2 logged in as ^3master^2\n");
                             if (autocvar_sv_eventlog)   GameLogEcho(strcat(":vote:vlogin:", ftos(caller.playerid))); }
                         return;
                     }
                     default:  // calling a vote for master
                     {
                         if (!autocvar_sv_vote_master_callable) { print_to(caller, "^1Vote to become vote master is not allowed."); }
                         else if (vote_called)
{
                             print_to(caller, "^1There is already a vote called.");
                         }
                         else if (!spectators_allowed && (caller && !IS_PLAYER(caller)))
{
                             print_to(caller, "^1Only players can call a vote.");
                         }
                         else if (timeout_status)
{
                             print_to(caller, "^1You can not call a vote while a timeout is active.");
                         }
                         else  // everything went okay, continue with creating vote
{
                             vote_caller = caller;
                             vote_caller_name = strzone(GetCallerName(vote_caller));
                             vote_called = VOTE_MASTER;
                             vote_called_command = strzone("XXX");
                             vote_called_display = strzone("^3master");
                             vote_endtime = time + autocvar_sv_vote_timeout;
                             caller.vote_selection = VOTE_SELECT_ACCEPT;
                             caller.vote_waittime = time + autocvar_sv_vote_wait;
                             bprint("\{1}^2* ^3", OriginalCallerName(), "^2 calls a vote to become ^3master^2.\n");
                             if (autocvar_sv_eventlog)   GameLogEcho(strcat(":vote:vcall:", ftos(vote_caller.playerid), ":", vote_called_display));
                             Nagger_VoteChanged();
                             VoteCount(true);  // needed if you are the only one
                         }
                         return;
                     }
                 }
             }
             else { print_to(caller, "^1Master control of voting is not allowed."); }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote master [action [command | password]]"));
             print_to(caller, "  If action is left blank, it calls a vote for you to become master.");
             print_to(caller, "  Otherwise the actions are either 'do' a command or 'login' as master.");
             return;
         }
     }
 }
void VoteCommand_no (float request, entity caller)
Definition at line 942 of file vote.qc.
References autocvar_sv_vote_change, autocvar_sv_vote_no_stops_vote, autocvar_sv_vote_singlecount, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), msg_entity, print_to(), strcat(), vote_called, vote_caller, VOTE_SELECT_NULL, VOTE_SELECT_REJECT, VoteCount(), and VoteStop().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!vote_called) { print_to(caller, "^1No vote called."); }
             else if (caller.vote_selection != VOTE_SELECT_NULL && !autocvar_sv_vote_change)
             {
                 print_to(caller, "^1You have already voted.");
             }
             else if (((caller == vote_caller) || caller.vote_master) && autocvar_sv_vote_no_stops_vote)
             {
                 VoteStop(caller);
             }
             else  // everything went okay, continue changing vote
             {
                 print_to(caller, "^1You rejected the vote.");
                 caller.vote_selection = VOTE_SELECT_REJECT;
                 msg_entity = caller;
                 if (!autocvar_sv_vote_singlecount)   VoteCount(false); }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote no"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
float VoteCommand_parse (entity caller, string vote_command, string vote_list, float startpos, float argc)
Definition at line 642 of file vote.qc.
References argv(), argv_start_index, autocvar_g_ban_default_bantime, autocvar_g_ban_default_masksize, autocvar_sv_vote_limit, entity(), etof(), ftos(), GetClientErrorString, GetIndexedEntity(), next_token, print_to(), strcat(), strlen(), strzone(), substring(), ValidateMap(), VerifyClientEntity(), vote_parsed_command, vote_parsed_display, VoteCommand_checkargs(), and VoteCommand_checkinlist().
Referenced by VoteCommand_call(), and VoteCommand_master().
 {
     string first_command;
     first_command = argv(startpos);
     /*printf("VoteCommand_parse(): Command: '%s', Length: %f.\n",
         substring(vote_command, argv_start_index(startpos), strlen(vote_command) - argv_start_index(startpos)),
         strlen(substring(vote_command, argv_start_index(startpos), strlen(vote_command) - argv_start_index(startpos)))
     );*/
     if (
         (autocvar_sv_vote_limit > 0)
         &&
         (strlen(substring(vote_command, argv_start_index(startpos), strlen(vote_command) - argv_start_index(startpos))) > autocvar_sv_vote_limit)
        )   return false;
     if (!VoteCommand_checkinlist(first_command, vote_list)) return false;
     if (!VoteCommand_checkargs(startpos, argc)) return false;
     switch (first_command) // now go through and parse the proper commands to adjust as needed.
     {
         case "kick":
         case "kickban":    // catch all kick/kickban commands
         {
             entity victim = GetIndexedEntity(argc, (startpos + 1));
             float accepted = VerifyClientEntity(victim, true, false);
             if (accepted > 0)
             {
                 string reason = ((argc > next_token) ? substring(vote_command, argv_start_index(next_token), strlen(vote_command) - argv_start_index(next_token)) : "No reason provided");
                 string command_arguments;
                 if (first_command == "kickban") command_arguments = strcat(ftos(autocvar_g_ban_default_bantime), " ", ftos(autocvar_g_ban_default_masksize), " ~");
                 else command_arguments = reason;
                 vote_parsed_command = strcat(first_command, " # ", ftos(etof(victim)), " ", command_arguments);
                 vote_parsed_display = strcat("^1", vote_command, " (^7", victim.netname, "^1): ", reason);
             }
             else { print_to(caller, strcat("vcall: ", GetClientErrorString(accepted, argv(startpos + 1)), ".\n")); return false; }
             break;
         }
         case "map":
         case "chmap":
         case "gotomap":  // re-direct all map selection commands to gotomap
         {
             vote_command = ValidateMap(argv(startpos + 1), caller);
             if (!vote_command)   return false;
             vote_parsed_command = strcat("gotomap ", vote_command);
             vote_parsed_display = strzone(strcat("^1", vote_parsed_command));
             break;
         }
         default:
         {
             vote_parsed_command = vote_command;
             vote_parsed_display = strzone(strcat("^1", vote_command));
             break;
         }
     }
     return true;
 }
void VoteCommand_status (float request, entity caller)
Definition at line 978 of file vote.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), OriginalCallerName(), print_to(), strcat(), vote_called, and vote_called_display.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (vote_called) print_to(caller, strcat("^7Vote for ", vote_called_display, "^7 called by ^7", OriginalCallerName(), "^7."));
             else print_to(caller, "^1No vote called.");
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote status"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void VoteCommand_stop (float request, entity caller)
Definition at line 1000 of file vote.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), strcat(), vote_called, vote_caller, and VoteStop().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!vote_called)   print_to(caller, "^1No vote called.");
             else if ((caller == vote_caller) || !caller || caller.vote_master)   VoteStop(caller);
             else   print_to(caller, "^1You are not allowed to stop that vote.");
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote stop"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void VoteCommand_yes (float request, entity caller)
Definition at line 1022 of file vote.qc.
References autocvar_sv_vote_change, autocvar_sv_vote_singlecount, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), msg_entity, print_to(), strcat(), vote_called, VOTE_SELECT_ACCEPT, VOTE_SELECT_NULL, and VoteCount().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!vote_called) { print_to(caller, "^1No vote called."); }
             else if (caller.vote_selection != VOTE_SELECT_NULL && !autocvar_sv_vote_change)
             {
                 print_to(caller, "^1You have already voted.");
             }
             else  // everything went okay, continue changing vote
             {
                 print_to(caller, "^1You accepted the vote.");
                 caller.vote_selection = VOTE_SELECT_ACCEPT;
                 msg_entity = caller;
                 if (!autocvar_sv_vote_singlecount)   VoteCount(false); }
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " vote yes"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void VoteCount (float first_count)
Definition at line 203 of file vote.qc.
References FOREACH_CLIENT, IS_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, Nagger_VoteCountChanged(), vote_abstain_count, vote_accept_count, vote_reject_count, and VOTE_SELECT_REJECT.
Referenced by ClientDisconnect(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_master(), VoteCommand_no(), VoteCommand_yes(), and VoteThink().
 {
     // declarations
     vote_accept_count = vote_reject_count = vote_abstain_count = 0;
     float vote_player_count = 0, notvoters = 0;
     float vote_real_player_count = 0, vote_real_accept_count = 0;
     float vote_real_reject_count = 0, vote_real_abstain_count = 0;
     float vote_needed_of_voted, final_needed_votes;
     float vote_factor_overall, vote_factor_of_voted;
     Nagger_VoteCountChanged();
     // add up all the votes from each connected client
     FOREACH_CLIENT(IS_REAL_CLIENT(it) && IS_CLIENT(it), LAMBDA(
         ++vote_player_count;
         if (IS_PLAYER(it))   ++vote_real_player_count;
         switch (it.vote_selection)
         {
             case VOTE_SELECT_REJECT:
             { ++vote_reject_count;
               { if (IS_PLAYER(it)) ++vote_real_reject_count; } break;
             }
             case VOTE_SELECT_ACCEPT:
             { ++vote_accept_count;
               { if (IS_PLAYER(it)) ++vote_real_accept_count; } break;
             }
             case VOTE_SELECT_ABSTAIN:
             { ++vote_abstain_count;
               { if (IS_PLAYER(it)) ++vote_real_abstain_count; } break;
             }
             default: break;
         }
     ));
     // Check to see if there are enough players on the server to allow master voting... otherwise, vote master could be used for evil.
     if ((vote_called == VOTE_MASTER) && autocvar_sv_vote_master_playerlimit > vote_player_count)
     {
         if (vote_caller)   vote_caller.vote_waittime = 0;
         print_to(vote_caller, "^1There are not enough players on this server to allow you to become vote master.");
         VoteReset();
         return;
     }
     // if spectators aren't allowed to vote and there are players in a match, then only count the players in the vote and ignore spectators.
     if (!spectators_allowed && (vote_real_player_count > 0))
     {
         vote_accept_count = vote_real_accept_count;
         vote_reject_count = vote_real_reject_count;
         vote_abstain_count = vote_real_abstain_count;
         vote_player_count = vote_real_player_count;
     }
     // people who have no opinion in any way :D
     notvoters = (vote_player_count - vote_accept_count - vote_reject_count - vote_abstain_count);
     // determine the goal for the vote to be passed or rejected normally
     vote_factor_overall = bound(0.5, autocvar_sv_vote_majority_factor, 0.999);
     vote_needed_overall = floor((vote_player_count - vote_abstain_count) * vote_factor_overall) + 1;
     // if the vote times out, determine the amount of votes needed of the people who actually already voted
     vote_factor_of_voted = bound(0.5, autocvar_sv_vote_majority_factor_of_voted, 0.999);
     vote_needed_of_voted = floor((vote_accept_count + vote_reject_count) * vote_factor_of_voted) + 1;
     // are there any players at all on the server? it could be an admin vote
     if (vote_player_count == 0 && first_count)
     {
         VoteSpam(0, -1, "yes");  // no players at all, just accept it
         VoteAccept();
         return;
     }
     // since there ARE players, finally calculate the result of the vote
     if (vote_accept_count >= vote_needed_overall)
     {
         VoteSpam(notvoters, -1, "yes");  // there is enough acceptions to pass the vote
         VoteAccept();
         return;
     }
     if (vote_reject_count > vote_player_count - vote_abstain_count - vote_needed_overall)
     {
         VoteSpam(notvoters, -1, "no");  // there is enough rejections to deny the vote
         VoteReject();
         return;
     }
     // there is not enough votes in either direction, now lets just calculate what the voters have said
     if (time > vote_endtime)
     {
         final_needed_votes = vote_needed_overall;
         if (autocvar_sv_vote_majority_factor_of_voted)
         {
             if (vote_accept_count >= vote_needed_of_voted)
             {
                 VoteSpam(notvoters, min(vote_needed_overall, vote_needed_of_voted), "yes");
                 VoteAccept();
                 return;
             }
             if (vote_accept_count + vote_reject_count > 0)
             {
                 VoteSpam(notvoters, min(vote_needed_overall, vote_needed_of_voted), "no");
                 VoteReject();
                 return;
             }
             final_needed_votes = min(vote_needed_overall, vote_needed_of_voted);
         }
         // it didn't pass or fail, so not enough votes to even make a decision.
         VoteSpam(notvoters, final_needed_votes, "timeout");
         VoteTimeout();
     }
 }
void VoteReject ()
Definition at line 167 of file vote.qc.
References bprint(), NULL, OriginalCallerName(), vote_called_display, and VoteReset().
 {
     bprint("\{1}^2* ^3", OriginalCallerName(), "^2's vote for ", vote_called_display, "^2 was rejected\n");
     VoteReset();
     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_VOTE_FAIL);
 }
void VoteReset ()
Definition at line 120 of file vote.qc.
References FOREACH_CLIENT, LAMBDA, Nagger_VoteChanged(), NULL, string_null, strunzone(), vote_called, vote_called_command, vote_called_display, vote_caller, vote_caller_name, vote_endtime, VOTE_NULL, vote_parsed_command, and vote_parsed_display.
Referenced by InitGameplayMode(), NextLevel(), ReadyRestart_force(), VoteAccept(), VoteReject(), VoteStop(), and VoteTimeout().
 {
     FOREACH_CLIENT(true, LAMBDA(it.vote_selection = 0));
     if (vote_called)
     {
         strunzone(vote_called_command);
         strunzone(vote_called_display);
         strunzone(vote_caller_name);
     }
     vote_called = VOTE_NULL;
     vote_caller = NULL;
     vote_caller_name = string_null;
     vote_endtime = 0;
     vote_called_command = string_null;
     vote_called_display = string_null;
     vote_parsed_command = string_null;
     vote_parsed_display = string_null;
     Nagger_VoteChanged();
 }
void VoteSpam (float notvoters, float mincount, string result)
Definition at line 181 of file vote.qc.
References autocvar_sv_eventlog, bprint(), ftos(), GameLogEcho(), strcat(), vote_abstain_count, vote_accept_count, and vote_reject_count.
 {
     bprint(strcat(
         strcat("\{1}^2* vote results: ^1", ftos(vote_accept_count)),
         strcat("^2:^1", ftos(vote_reject_count)),
         ((mincount >= 0) ? strcat("^2 (^1", ftos(mincount), "^2 needed)") : "^2"),
         strcat(", ^1", ftos(vote_abstain_count), "^2 didn't care"),
         strcat(", ^1", ftos(notvoters), strcat("^2 didn't ", ((mincount >= 0) ? "" : "have to "), "vote\n"))));
     if (autocvar_sv_eventlog)
     {
         GameLogEcho(strcat(
             strcat(":vote:v", result, ":", ftos(vote_accept_count)),
             strcat(":", ftos(vote_reject_count)),
             strcat(":", ftos(vote_abstain_count)),
             strcat(":", ftos(notvoters)),
             strcat(":", ftos(mincount))));
     }
 }
void VoteStop (entity stopper)
Definition at line 145 of file vote.qc.
References autocvar_sv_eventlog, autocvar_sv_vote_stop, bprint(), ftos(), GameLogEcho(), GetCallerName(), OriginalCallerName(), strcat(), time, vote_caller, and VoteReset().
Referenced by VoteCommand_no(), and VoteCommand_stop().
 {
     bprint("\{1}^2* ^3", GetCallerName(stopper), "^2 stopped ^3", OriginalCallerName(), "^2's vote\n");
     if (autocvar_sv_eventlog)   GameLogEcho(strcat(":vote:vstop:", ftos(stopper.playerid)));
     // Don't force them to wait for next vote, this way they can e.g. correct their vote.
     if ((vote_caller) && (stopper == vote_caller))   vote_caller.vote_waittime = time + autocvar_sv_vote_stop;
     VoteReset();
 }
void VoteThink ()
Definition at line 320 of file vote.qc.
References time, vote_endtime, and VoteCount().
Referenced by CheckRules_World().
 {
     if (vote_endtime > 0)        // a vote was called
     {
         if (time > vote_endtime) // time is up
             VoteCount(false);
     }
 }
void VoteTimeout ()
Definition at line 174 of file vote.qc.
References bprint(), NULL, OriginalCallerName(), vote_called_display, and VoteReset().
 {
     bprint("\{1}^2* ^3", OriginalCallerName(), "^2's vote for ", vote_called_display, "^2 timed out\n");
     VoteReset();
     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_VOTE_FAIL);
 }