Xonotic: common/mapobjects/trigger/viewloc.qh File Reference
viewloc.qh File Reference
Variables
entity viewloc
const int VIEWLOC_CAM_NOANGLE = BIT(4)
const int VIEWLOC_CAM_SNAP_CLOSE = BIT(7)
const int VIEWLOC_CAM_SNAP_HARD = BIT(5)
const int VIEWLOC_CAM_SNAP_UNLOCK = BIT(6)
const int VIEWLOC_CAM_TRACK = BIT(3)
const int VIEWLOC_FREEAIM = BIT(1)
const int VIEWLOC_FREEMOVE = BIT(2)
const int VIEWLOC_NOSIDESCROLL = BIT(0)
Variable Documentation
entity viewloc
Definition at line 13 of file viewloc.qh.
Referenced by DrawReticle(), PlayerJump(), PM_ClientMovement_UpdateStatus(), PutObserverInServer(), PutPlayerInServer(), SpectateCopy(), sys_phys_simulate(), View_EventChase(), viewloc_PlayerPhysics(), and WantEventchase().
const int VIEWLOC_CAM_NOANGLE = BIT(4)
Definition at line 8 of file viewloc.qh.
Referenced by viewloc_PlayerPhysics().
const int VIEWLOC_CAM_SNAP_CLOSE = BIT(7)
Definition at line 11 of file viewloc.qh.
Referenced by viewloc_PlayerPhysics().
const int VIEWLOC_CAM_SNAP_HARD = BIT(5)
Definition at line 9 of file viewloc.qh.
Referenced by viewloc_PlayerPhysics().
const int VIEWLOC_CAM_SNAP_UNLOCK = BIT(6)
Definition at line 10 of file viewloc.qh.
Referenced by viewloc_PlayerPhysics().
const int VIEWLOC_CAM_TRACK = BIT(3)
Definition at line 7 of file viewloc.qh.
Referenced by viewloc_PlayerPhysics().
const int VIEWLOC_FREEAIM = BIT(1)
Definition at line 5 of file viewloc.qh.
Referenced by HUD_Crosshair(), HUD_Mouse(), and viewloc_PlayerPhysics().
const int VIEWLOC_FREEMOVE = BIT(2)
Definition at line 6 of file viewloc.qh.
Referenced by PM_ClientMovement_UpdateStatus(), and viewloc_PlayerPhysics().
const int VIEWLOC_NOSIDESCROLL = BIT(0)
Definition at line 4 of file viewloc.qh.