Xonotic: menu/xonotic/keybinder.qh File Reference
keybinder.qh File Reference
#include "listbox.qh"
Classes
class XonoticKeyBinder
Functions
void KeyBinder_Bind_Change (entity btn, entity me)
void KeyBinder_Bind_Clear (entity btn, entity me)
void KeyBinder_Bind_Edit (entity btn, entity me)
void KeyBinder_Bind_Reset_All (entity btn, entity me)
entity makeXonoticKeyBinder ()
Function Documentation
void KeyBinder_Bind_Change (entity btn, entity me)
Definition at line 184 of file keybinder.qc.
References keyGrabber, and Xonotic_KeyBinds_Functions.
Referenced by XonoticInputSettingsTab_fill(), XonoticKeyBinder_doubleClickListBoxItem(), XonoticKeyBinder_keyDown(), and XonoticKeyBinder_keyGrabbed().
 {
     string func;
     func = Xonotic_KeyBinds_Functions[me.selectedItem];
     if(func == "")
         return;
     me.keyGrabButton.forcePressed = 1;
     me.clearButton.disabled = 1;
     keyGrabber = me;
 }
void KeyBinder_Bind_Clear (entity btn, entity me)
Definition at line 300 of file keybinder.qc.
References argv(), cvar_set(), KEY_NOT_BOUND_CMD, keynumtostring(), localcmd, m_play_click_sound(), MENU_SOUND_CLEAR, stof(), tokenize(), and Xonotic_KeyBinds_Functions.
Referenced by XonoticInputSettingsTab_fill(), and XonoticKeyBinder_keyDown().
 {
     float n, j, k;
     string func;
     func = Xonotic_KeyBinds_Functions[me.selectedItem];
     if(func == "")
         return;
     n = tokenize(findkeysforcommand(func, 0)); // uses '...' strings
     for(j = 0; j < n; ++j)
     {
         k = stof(argv(j));
         if(k != -1)
             //localcmd("\nunbind \"", keynumtostring(k), "\"\n");
             localcmd("\nbind \"", keynumtostring(k), "\" \"", KEY_NOT_BOUND_CMD, "\"\n");
     }
     m_play_click_sound(MENU_SOUND_CLEAR);
     localcmd("-zoom\n"); // to make sure we aren't in togglezoom'd state
     cvar_set("_hud_showbinds_reload", "1");
 }
void KeyBinder_Bind_Edit (entity btn, entity me)
Definition at line 279 of file keybinder.qc.
References cvar_string(), DialogOpenButton_Click(), strcat(), strlen(), substring(), Xonotic_KeyBinds_Descriptions, and Xonotic_KeyBinds_Functions.
Referenced by XonoticInputSettingsTab_fill().
 {
     string func, descr;
     if(!me.userbindEditDialog)
         return;
     func = Xonotic_KeyBinds_Functions[me.selectedItem];
     if(func == "")
         return;
     descr = Xonotic_KeyBinds_Descriptions[me.selectedItem];
     if(substring(descr, 0, 1) != "$")
         return;
     descr = substring(descr, 1, strlen(descr) - 1);
     // Hooray! It IS a user bind!
     me.userbindEditDialog.loadUserBind(me.userbindEditDialog, cvar_string(strcat(descr, "_description")), cvar_string(strcat(descr, "_press")), cvar_string(strcat(descr, "_release")));
     DialogOpenButton_Click(btn, me.userbindEditDialog);
 }
void KeyBinder_Bind_Reset_All (entity btn, entity me)
Definition at line 321 of file keybinder.qc.
References cvar_set(), and localcmd.
Referenced by XonoticInputSettingsTab_fill().
 {
     localcmd("unbindall\n");
     localcmd("exec binds-xonotic.cfg\n");
     localcmd("-zoom\n"); // to make sure we aren't in togglezoom'd state
     cvar_set("_hud_showbinds_reload", "1");
 }
entity makeXonoticKeyBinder ()
Definition at line 118 of file keybinder.qc.
References entity(), and NEW.
Referenced by XonoticInputSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticKeyBinder);
     me.configureXonoticKeyBinder(me);
     return me;
 }