Xonotic: server/race.qh File Reference
race.qh File Reference
Functions
void race_AbandonRaceCheck (entity p)
void race_checkAndWriteName (entity player)
void race_ClearRecords ()
float race_GetFractionalLapCount (entity e)
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
void race_InitSpectator ()
float race_NextCheckpoint (float f)
void race_PreparePlayer (entity this)
float race_PreviousCheckpoint (float f)
string race_readName (string map, float pos)
float race_readTime (string map, float pos)
string race_readUID (string map, float pos)
void race_RetractPlayer (entity this)
void race_send_rankings_cnt (float msg)
void race_send_recordtime (float msg)
void race_send_speedaward (float msg)
void race_send_speedaward_alltimebest (float msg)
void race_SendAll (entity player, bool only_rankings)
void race_SendNextCheckpoint (entity e, float spec)
void race_SendRanking (float pos, float prevpos, float del, float msg)
void race_setTime (string map, float t, string myuid, string mynetname, entity e, bool showmessage)
void race_SpeedAwardFrame (entity player)
void race_StartCompleting ()
spawnfunc (target_checkpoint)
string uid2name (string myuid)
void write_recordmarker (entity pl, float tstart, float dt)
Variables
bool autocvar_g_allow_checkpoints
int autocvar_g_cts_send_rankings_cnt = 15
bool g_race_qualifying
float race_completed
float race_completing
float race_fraglimit
float race_highest_place_spawn
float race_laptime
float race_leadlimit
float race_lowest_place_spawn
float race_movetime
float race_movetime_count
float race_movetime_frac
float race_place
float race_respawn_checkpoint
entity race_respawn_spotref
float race_spawns
float race_started
float race_teams
float race_timelimit
float speedaward_alltimebest
string speedaward_alltimebest_holder
string speedaward_alltimebest_uid
string speedaward_holder
float speedaward_lastsent
float speedaward_lastupdate
float speedaward_speed
string speedaward_uid
const float ST_RACE_LAPS = 1
Function Documentation
race_AbandonRaceCheck()
void race_AbandonRaceCheck (entity p)
Definition at line 1161 of file race.qc.
References ClientData_Touch(), CS(), MAKE_INDEPENDENT_PLAYER, NULL, race_completed, and race_completing.
Referenced by MUTATOR_HOOKFUNCTION(), and race_StartCompleting().
 {
     if(race_completing && !CS(p).race_completed)
     {
         CS(p).race_completed = 1;
         MAKE_INDEPENDENT_PLAYER(p);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_ABANDONED, p.netname);
         ClientData_Touch(p);
     }
 }
race_checkAndWriteName()
void race_checkAndWriteName (entity player)
Definition at line 142 of file race.qc.
References CS_CVAR, db_put(), ServerProgsDB, strcat(), strcpy, strzone(), and uid2name().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(CS_CVAR(player).cvar_cl_allow_uidtracking == 1 && CS_CVAR(player).cvar_cl_allow_uid2name == 1)
     {
         if (!player.stored_netname)
             player.stored_netname = strzone(uid2name(player.crypto_idfp));
         if(player.stored_netname != player.netname)
         {
             db_put(ServerProgsDB, strcat("/uid2name/", player.crypto_idfp), player.netname);
             strcpy(player.stored_netname, player.netname);
         }
     }
 }
race_ClearRecords()
void race_ClearRecords ()
Definition at line 1208 of file race.qc.
References FOREACH_CLIENT, MAX_CHECKPOINTS, race_checkpoint_recordholders, race_checkpoint_records, race_PreparePlayer(), and strfree.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     for(int j = 0; j < MAX_CHECKPOINTS; ++j)
     {
         race_checkpoint_records[j] = 0;
         strfree(race_checkpoint_recordholders[j]);
     }
     FOREACH_CLIENT(true, {
         float p = it.race_place;
         race_PreparePlayer(it);
         it.race_place = p;
     });
 }
race_GetFractionalLapCount()
float race_GetFractionalLapCount (entity e)
Definition at line 1287 of file race.qc.
References bound(), CS(), entity(), GameRules_scoring_add, IL_EACH, max(), race_completed, race_highest_checkpoint, race_timed_checkpoint, vector(), and vlen().
 {
     // interesting metrics (idea by KrimZon) to maybe sort players in the
     // scoreboard, immediately updates when overtaking
     //
     // requires the track to be built so you never get farther away from the
     // next checkpoint, though, and current Xonotic race maps are not built that
     // way
     //
     // also, this code is slow and would need optimization (i.e. "next CP"
     // links on CP entities)
     float l;
     l = GameRules_scoring_add(e, RACE_LAPS, 0);
     if(CS(e).race_completed)
         return l; // not fractional
     vector o0, o1;
     float bestfraction, fraction;
     entity lastcp;
     float nextcpindex, lastcpindex;
     nextcpindex = max(e.race_checkpoint, 0);
     lastcpindex = e.race_respawn_checkpoint;
     lastcp = e.race_respawn_spotref;
     if(nextcpindex == lastcpindex)
         return l; // finish
     bestfraction = 1;
     IL_EACH(g_racecheckpoints, true,
     {
         if(it.race_checkpoint != lastcpindex)
             continue;
         if(lastcp)
             if(it != lastcp)
                 continue;
         o0 = (it.absmin + it.absmax) * 0.5;
         IL_EACH(g_racecheckpoints, true,
         {
             if(it.race_checkpoint != nextcpindex)
                 continue;
             o1 = (it.absmin + it.absmax) * 0.5;
             if(o0 == o1)
                 continue;
             fraction = bound(0.0001, vlen(e.origin - o1) / vlen(o0 - o1), 1);
             if(fraction < bestfraction)
                 bestfraction = fraction;
         });
     });
     // we are at CP "nextcpindex - bestfraction"
     // race_timed_checkpoint == 4: then nextcp==4 means 0.9999x, nextcp==0 means 0.0000x
     // race_timed_checkpoint == 0: then nextcp==0 means 0.9999x
     float c, nc;
     nc = race_highest_checkpoint + 1;
     c = ((nextcpindex - race_timed_checkpoint + nc + nc - 1) % nc) + 1 - bestfraction;
     return l + c / nc;
 }
race_ImposePenaltyTime()
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
Definition at line 1223 of file race.qc.
References g_race_qualifying, IS_REAL_CLIENT, msg_entity, MSG_ONE, RACE_NET_PENALTY_QUALIFYING, RACE_NET_PENALTY_RACE, time, TIME_ENCODE, WriteByte(), WriteShort(), and WriteString().
Referenced by CheatCommand(), checkpoint_passed(), penalty_touch(), and penalty_use().
 {
     if(g_race_qualifying)
     {
         pl.race_penalty_accumulator += penalty;
         if(IS_REAL_CLIENT(pl))
         {
             msg_entity = pl;
             WRITESPECTATABLE_MSG_ONE(msg_entity, {
                 WriteHeader(MSG_ONE, TE_CSQC_RACE);
                 WriteByte(MSG_ONE, RACE_NET_PENALTY_QUALIFYING);
                 WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                 WriteString(MSG_ONE, reason);
             });
         }
     }
     else
     {
         pl.race_penalty = time + penalty;
         if(IS_REAL_CLIENT(pl))
         {
             msg_entity = pl;
             WRITESPECTATABLE_MSG_ONE(msg_entity, {
                 WriteHeader(MSG_ONE, TE_CSQC_RACE);
                 WriteByte(MSG_ONE, RACE_NET_PENALTY_RACE);
                 WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                 WriteString(MSG_ONE, reason);
             });
         }
     }
 }
race_InitSpectator()
void race_InitSpectator ()
Definition at line 70 of file race.qc.
References g_race_qualifying, msg_entity, and race_SendNextCheckpoint().
Referenced by SetSpectatee_status().
 {
     if(g_race_qualifying)
         if(msg_entity.enemy.race_laptime)
             race_SendNextCheckpoint(msg_entity.enemy, 1);
 }
race_NextCheckpoint()
float race_NextCheckpoint (float f)
Definition at line 181 of file race.qc.
References race_highest_checkpoint.
Referenced by checkpoint_passed(), and trigger_race_checkpoint_verify().
 {
     if(f >= race_highest_checkpoint)
         return 0;
     else
         return f + 1;
 }
race_PreparePlayer()
void race_PreparePlayer (entity this)
Definition at line 1178 of file race.qc.
References NULL, race_ClearTime(), race_place, race_respawn_checkpoint, race_respawn_spotref, and race_started.
Referenced by MUTATOR_HOOKFUNCTION(), and race_ClearRecords().
 {
     race_ClearTime(this);
     this.race_place = 0;
     this.race_started = 0;
     this.race_respawn_checkpoint = 0;
     this.race_respawn_spotref = NULL;
 }
race_PreviousCheckpoint()
float race_PreviousCheckpoint (float f)
Definition at line 189 of file race.qc.
References race_highest_checkpoint.
 {
     if(f == -1)
         return 0;
     else if(f == 0)
         return race_highest_checkpoint;
     else
         return f - 1;
 }
race_readName()
string race_readName (string map, float pos)
Definition at line 137 of file race.qc.
References db_get(), ftos(), record_type, ServerProgsDB, strcat(), and uid2name().
Referenced by getrankings(), MUTATOR_HOOKFUNCTION(), race_SendRanking(), and race_setTime().
 {
     return uid2name(db_get(ServerProgsDB, strcat(map, record_type, "crypto_idfp", ftos(pos))));
 }
race_readTime()
float race_readTime (string map, float pos)
Definition at line 77 of file race.qc.
References db_get(), ftos(), record_type, ServerProgsDB, stof(), and strcat().
Referenced by getladder(), getlsmaps(), getrankings(), MUTATOR_HOOKFUNCTION(), race_deleteTime(), race_readPos(), race_send_recordtime(), race_SendRanking(), race_setTime(), and race_writeTime().
 {
     return stof(db_get(ServerProgsDB, strcat(map, record_type, "time", ftos(pos))));
 }
race_readUID()
string race_readUID (string map, float pos)
Definition at line 82 of file race.qc.
References db_get(), ftos(), record_type, ServerProgsDB, and strcat().
Referenced by getladder(), race_deleteTime(), race_setTime(), and race_writeTime().
 {
     return db_get(ServerProgsDB, strcat(map, record_type, "crypto_idfp", ftos(pos)));
 }
race_RetractPlayer()
void race_RetractPlayer (entity this)
Definition at line 1187 of file race.qc.
References g_cts, g_race, race_checkpoint, race_ClearTime(), race_respawn_checkpoint, and race_timed_checkpoint.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(!g_race && !g_cts)
         return;
     if(this.race_respawn_checkpoint == 0 || this.race_respawn_checkpoint == race_timed_checkpoint)
         race_ClearTime(this);
     this.race_checkpoint = this.race_respawn_checkpoint;
 }
race_send_rankings_cnt()
void race_send_rankings_cnt (float msg)
Definition at line 276 of file race.qc.
References autocvar_g_cts_send_rankings_cnt, min(), RACE_NET_RANKINGS_CNT, and WriteByte().
Referenced by race_SendAll().
 {
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_RANKINGS_CNT);
     int m = min(RANKINGS_CNT, autocvar_g_cts_send_rankings_cnt);
     WriteByte(msg, m);
 }
race_send_recordtime()
void race_send_recordtime (float msg)
Definition at line 250 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RECORD, race_readTime(), and WriteByte().
Referenced by race_deleteTime(), race_SendAll(), and race_setTime().
 {
     // send the server best time
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SERVER_RECORD);
     WriteInt24_t(msg, race_readTime(GetMapname(), 1));
 }
race_send_speedaward()
void race_send_speedaward (float msg)
Definition at line 258 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD, speedaward_holder, speedaward_speed, WriteByte(), and WriteString().
Referenced by race_SendAll(), and race_SpeedAwardFrame().
 {
     // send the best speed of the round
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SPEED_AWARD);
     WriteInt24_t(msg, floor(speedaward_speed+0.5));
     WriteString(msg, speedaward_holder);
 }
race_send_speedaward_alltimebest()
void race_send_speedaward_alltimebest (float msg)
Definition at line 267 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD_BEST, speedaward_alltimebest, speedaward_alltimebest_holder, WriteByte(), and WriteString().
Referenced by race_SendAll(), and race_SpeedAwardFrame().
 {
     // send the best speed
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SPEED_AWARD_BEST);
     WriteInt24_t(msg, floor(speedaward_alltimebest+0.5));
     WriteString(msg, speedaward_alltimebest_holder);
 }
race_SendAll()
void race_SendAll (entity player, bool only_rankings)
Definition at line 323 of file race.qc.
References autocvar_g_cts_send_rankings_cnt, db_get(), GetMapname(), IS_REAL_CLIENT, min(), msg_entity, MSG_ONE, race_send_rankings_cnt(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendRanking(), record_type, ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, stof(), strcat(), and uid2name().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(!IS_REAL_CLIENT(player))
         return;
     msg_entity = player;
     if (!only_rankings)
     {
         race_send_recordtime(MSG_ONE);
         race_send_speedaward(MSG_ONE);
         speedaward_alltimebest = stof(db_get(ServerProgsDB, strcat(GetMapname(), record_type, "speed/speed")));
         speedaward_alltimebest_holder = uid2name(db_get(ServerProgsDB, strcat(GetMapname(), record_type, "speed/crypto_idfp")));
         race_send_speedaward_alltimebest(MSG_ONE);
     }
     int m = min(RANKINGS_CNT, autocvar_g_cts_send_rankings_cnt);
     race_send_rankings_cnt(MSG_ONE);
     for (int i = 1; i <= m; ++i)
         race_SendRanking(i, 0, 0, MSG_ONE);
 }
race_SendNextCheckpoint()
void race_SendNextCheckpoint (entity e, float spec)
Definition at line 215 of file race.qc.
References IS_REAL_CLIENT, msg_entity, MSG_ONE, race_checkpoint_recordholders, race_checkpoint_records, race_CheckpointNetworkID(), RACE_NET_CHECKPOINT_NEXT_QUALIFYING, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING, time, WriteByte(), WriteCoord(), and WriteString().
Referenced by checkpoint_passed(), and race_InitSpectator().
 {
     if(!e.race_laptime)
         return;
     int cp = e.race_checkpoint;
     float recordtime = race_checkpoint_records[cp];
     float myrecordtime = e.race_checkpoint_record[cp];
     string recordholder = race_checkpoint_recordholders[cp];
     if(recordholder == e.netname)
         recordholder = "";
     if(!IS_REAL_CLIENT(e))
         return;
     if(!spec)
         msg_entity = e;
     WRITESPECTATABLE_MSG_ONE(msg_entity, {
         WriteHeader(MSG_ONE, TE_CSQC_RACE);
         if(spec)
         {
             WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING);
             //WriteCoord(MSG_ONE, e.race_laptime - e.race_penalty_accumulator);
             WriteCoord(MSG_ONE, time - e.race_movetime - e.race_penalty_accumulator);
         }
         else
             WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_QUALIFYING);
         WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player will be at next
         WriteInt24_t(MSG_ONE, recordtime);
         if(!spec)
             WriteInt24_t(MSG_ONE, myrecordtime);
         WriteString(MSG_ONE, recordholder);
     });
 }
race_SendRanking()
void race_SendRanking (float pos, float prevpos, float del, float msg)
Definition at line 284 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RANKINGS, race_readName(), race_readTime(), WriteByte(), WriteShort(), and WriteString().
Referenced by race_deleteTime(), race_SendAll(), and race_setTime().
 {
     WriteHeader(msg, TE_CSQC_RACE);
     WriteByte(msg, RACE_NET_SERVER_RANKINGS);
     WriteShort(msg, pos);
     WriteShort(msg, prevpos);
     WriteShort(msg, del);
     WriteString(msg, race_readName(GetMapname(), pos));
     WriteInt24_t(msg, race_readTime(GetMapname(), pos));
 }
race_setTime()
void race_setTime (string map, float t, string myuid, string mynetname, entity e, bool showmessage)
Definition at line 364 of file race.qc.
References GetMapname(), getrankings(), MSG_ALL, NULL, race_readName(), race_readPos(), race_readTime(), race_readUID(), race_send_recordtime(), race_SendRanking(), race_SendStatus(), race_writeTime(), strcpy, time, TIME_DECODE, uid2name(), and write_recordmarker().
Referenced by ctf_CaptureRecord(), and race_SendTime().
 {
     // netname only used TEMPORARILY for printing
     int newpos = race_readPos(map, t);
     int player_prevpos = 0;
     for(int i = 1; i <= RANKINGS_CNT; ++i)
     {
         if(race_readUID(map, i) == myuid)
             player_prevpos = i;
     }
     float oldrec;
     string oldrec_holder;
     if (player_prevpos && (player_prevpos < newpos || !newpos))
     {
         oldrec = race_readTime(GetMapname(), player_prevpos);
         race_SendStatus(0, e); // "fail"
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_FAIL_RANKED, mynetname, player_prevpos, t, oldrec);
         return;
     }
     else if (!newpos)
     {
         // no ranking, time worse than the worst ranked
         oldrec = race_readTime(GetMapname(), RANKINGS_CNT);
         race_SendStatus(0, e); // "fail"
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_FAIL_UNRANKED, mynetname, RANKINGS_CNT, t, oldrec);
         return;
     }
     // if we didn't hit a return yet, we have a new record!
     // if the player does not have a UID we can unfortunately not store the record, as the rankings system relies on UIDs
     if(myuid == "")
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_MISSING_UID, mynetname, t);
         return;
     }
     if(uid2name(myuid) == "^1Unregistered Player")
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_MISSING_NAME, mynetname, t);
         return;
     }
     oldrec = race_readTime(GetMapname(), newpos);
     oldrec_holder = race_readName(GetMapname(), newpos);
     // store new ranking
     race_writeTime(GetMapname(), t, myuid);
     if (newpos == 1 && showmessage)
     {
         write_recordmarker(e, time - TIME_DECODE(t), TIME_DECODE(t));
         race_send_recordtime(MSG_ALL);
     }
     race_SendRanking(newpos, player_prevpos, 0, MSG_ALL);
     strcpy(rankings_reply, getrankings());
     if(newpos == player_prevpos)
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_IMPROVED, mynetname, newpos, t, oldrec);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(1, e); } // "new time"
     }
     else if(oldrec == 0)
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_SET, mynetname, newpos, t);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(2, e); } // "new rank"
     }
     else
     {
         if(showmessage)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_RACE_NEW_BROKEN, mynetname, oldrec_holder, newpos, t, oldrec);
         if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
         else { race_SendStatus(2, e); } // "new rank"
     }
 }
race_SpeedAwardFrame()
void race_SpeedAwardFrame (entity player)
Definition at line 295 of file race.qc.
References db_put(), ftos(), GetMapname(), intermission_running, IS_OBSERVER, MSG_ALL, race_send_speedaward(), race_send_speedaward_alltimebest(), record_type, ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, speedaward_alltimebest_uid, speedaward_holder, speedaward_lastsent, speedaward_lastupdate, speedaward_speed, speedaward_uid, strcat(), time, vdist, and vlen().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if (IS_OBSERVER(player))
         return;
     if(vdist(player.velocity - player.velocity_z * '0 0 1', >, speedaward_speed))
     {
         speedaward_speed = vlen(player.velocity - player.velocity_z * '0 0 1');
         speedaward_holder = player.netname;
         speedaward_uid = player.crypto_idfp;
         speedaward_lastupdate = time;
     }
     if (speedaward_speed > speedaward_lastsent && (time - speedaward_lastupdate > 1 || intermission_running))
     {
         race_send_speedaward(MSG_ALL);
         speedaward_lastsent = speedaward_speed;
         if (speedaward_speed > speedaward_alltimebest && speedaward_uid != "")
         {
             speedaward_alltimebest = speedaward_speed;
             speedaward_alltimebest_holder = speedaward_holder;
             speedaward_alltimebest_uid = speedaward_uid;
             db_put(ServerProgsDB, strcat(GetMapname(), record_type, "speed/speed"), ftos(speedaward_alltimebest));
             db_put(ServerProgsDB, strcat(GetMapname(), record_type, "speed/crypto_idfp"), speedaward_alltimebest_uid);
             race_send_speedaward_alltimebest(MSG_ALL);
         }
     }
 }
race_StartCompleting()
void race_StartCompleting ()
Definition at line 1172 of file race.qc.
References FOREACH_CLIENT, IS_DEAD, IS_PLAYER, race_AbandonRaceCheck(), and race_completing.
Referenced by InitiateSuddenDeath(), and race_SendTime().
 {
     race_completing = 1;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_DEAD(it), { race_AbandonRaceCheck(it); });
 }
spawnfunc()
spawnfunc (target_checkpoint)
Definition at line 1151 of file race.qc.
References target_checkpoint_setup().
 {
     // xonotic defrag entity
     target_checkpoint_setup(this);
 }
uid2name()
string uid2name (string myuid)
Definition at line 35 of file race.qc.
References db_get(), db_put(), db_remove, ServerProgsDB, and strcat().
Referenced by getladder(), race_checkAndWriteName(), race_readName(), race_SendAll(), and race_setTime().
 {
     string s = db_get(ServerProgsDB, strcat("/uid2name/", myuid));
     // FIXME remove this later after 0.6 release
     // convert old style broken records to correct style
     if(s == "")
     {
         s = db_get(ServerProgsDB, strcat("uid2name", myuid));
         if(s != "")
         {
             db_put(ServerProgsDB, strcat("/uid2name/", myuid), s);
             db_remove(ServerProgsDB, strcat("uid2name", myuid));
         }
     }
     if(s == "")
         s = "^1Unregistered Player";
     return s;
 }
write_recordmarker()
void write_recordmarker (entity pl, float tstart, float dt)
Definition at line 56 of file race.qc.
References ftos(), GameLogEcho(), GetGametype(), strcat(), stuffcmd, TIME_ENCODE, and TIME_ENCODED_TOSTRING.
Referenced by ctf_CaptureRecord(), and race_setTime().
 {
     GameLogEcho(strcat(":recordset:", ftos(pl.playerid), ":", ftos(dt)));
     // also write a marker into demo files for demotc-race-record-extractor to find
     stuffcmd(pl,
              strcat(
                  strcat("//", strconv(2, 0, 0, GetGametype()), " RECORD SET ", TIME_ENCODED_TOSTRING(TIME_ENCODE(dt))),
                  " ", ftos(tstart), " ", ftos(dt), "\n"));
 }
Variable Documentation
autocvar_g_allow_checkpoints
bool autocvar_g_allow_checkpoints
Definition at line 3 of file race.qh.
Referenced by CheatImpulse(), checkpoint_passed(), IMPULSE(), and MUTATOR_HOOKFUNCTION().
autocvar_g_cts_send_rankings_cnt
int autocvar_g_cts_send_rankings_cnt = 15
Definition at line 10 of file race.qh.
Referenced by race_send_rankings_cnt(), and race_SendAll().
g_race_qualifying
bool g_race_qualifying
Definition at line 12 of file race.qh.
Referenced by checkpoint_passed(), CheckRules_World(), ClientCommand_ready(), cts_ScoreRules(), InitiateSuddenDeath(), MUTATOR_HOOKFUNCTION(), PlayerThink(), race_ImposePenaltyTime(), race_Initialize(), race_InitSpectator(), race_ScoreRules(), race_SendTime(), rc_SetLimits(), ReadyRestart_force(), REGISTER_MUTATOR(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
race_completed
float race_completed
Definition at line 25 of file race.qh.
Referenced by ClientData_Send(), race_AbandonRaceCheck(), race_GetFractionalLapCount(), race_SendTime(), and WinningCondition_Race().
race_completing
float race_completing
Definition at line 27 of file race.qh.
Referenced by race_AbandonRaceCheck(), race_SendTime(), race_StartCompleting(), and ReadyRestart().
race_fraglimit
float race_fraglimit
Definition at line 20 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and rc_SetLimits().
race_highest_place_spawn
float race_highest_place_spawn
Definition at line 18 of file race.qh.
Referenced by spawnfunc(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
race_laptime
float race_laptime
Definition at line 26 of file race.qh.
race_leadlimit
float race_leadlimit
Definition at line 21 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and rc_SetLimits().
race_lowest_place_spawn
float race_lowest_place_spawn
Definition at line 19 of file race.qh.
Referenced by spawnfunc(), trigger_race_checkpoint_spawn_evalfunc(), and trigger_race_checkpoint_verify().
race_movetime
float race_movetime
Definition at line 29 of file race.qh.
race_movetime_count
float race_movetime_count
Definition at line 31 of file race.qh.
race_movetime_frac
float race_movetime_frac
Definition at line 30 of file race.qh.
race_place
float race_place
Definition at line 23 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), race_PreparePlayer(), and spawnfunc().
race_respawn_checkpoint
float race_respawn_checkpoint
Definition at line 33 of file race.qh.
Referenced by race_PreparePlayer(), and race_RetractPlayer().
race_respawn_spotref
entity race_respawn_spotref
Definition at line 34 of file race.qh.
Referenced by race_PreparePlayer().
race_spawns
float race_spawns
Definition at line 17 of file race.qh.
Referenced by Spawn_Score(), and spawnfunc().
race_started
float race_started
Definition at line 24 of file race.qh.
Referenced by race_PreparePlayer().
race_teams
float race_teams
Definition at line 5 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), race_ScoreRules(), and rc_SetLimits().
race_timelimit
float race_timelimit
Definition at line 22 of file race.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and rc_SetLimits().
speedaward_alltimebest
float speedaward_alltimebest
Definition at line 61 of file race.qh.
Referenced by race_send_speedaward_alltimebest(), race_SendAll(), and race_SpeedAwardFrame().
speedaward_alltimebest_holder
string speedaward_alltimebest_holder
Definition at line 62 of file race.qh.
Referenced by race_send_speedaward_alltimebest(), race_SendAll(), and race_SpeedAwardFrame().
speedaward_alltimebest_uid
string speedaward_alltimebest_uid
Definition at line 63 of file race.qh.
Referenced by race_SpeedAwardFrame().
speedaward_holder
string speedaward_holder
Definition at line 58 of file race.qh.
Referenced by race_send_speedaward(), and race_SpeedAwardFrame().
speedaward_lastsent
float speedaward_lastsent
Definition at line 14 of file race.qh.
Referenced by race_SpeedAwardFrame().
speedaward_lastupdate
float speedaward_lastupdate
Definition at line 15 of file race.qh.
Referenced by race_SpeedAwardFrame().
speedaward_speed
float speedaward_speed
Definition at line 57 of file race.qh.
Referenced by race_send_speedaward(), and race_SpeedAwardFrame().
speedaward_uid
string speedaward_uid
Definition at line 59 of file race.qh.
Referenced by race_SpeedAwardFrame().
ST_RACE_LAPS
const float ST_RACE_LAPS = 1
Definition at line 8 of file race.qh.
Referenced by race_ScoreRules().