Xonotic: server/race.qc File Reference
server/race.qc File Reference
#include "race.qh"
#include "cl_client.qh"
#include "portals.qh"
#include "scores.qh"
#include "spawnpoints.qh"
#include "bot/waypoints.qh"
#include "bot/navigation.qh"
#include "command/getreplies.qh"
#include "../common/deathtypes/all.qh"
#include "../common/notifications.qh"
#include "../common/mapinfo.qh"
#include "../common/triggers/subs.qh"
#include "../lib/warpzone/util_server.qh"
#include "../lib/warpzone/common.qh"
#include "../common/mutators/mutator/waypoints/waypointsprites.qh"
Functions
void race_InitSpectator ()
void W_Porto_Fail (float failhard)
float race_readTime (string map, float pos)
string race_readUID (string map, float pos)
float race_readPos (string map, float t)
void race_writeTime (string map, float t, string myuid)
string race_readName (string map, float pos)
spawnfunc (target_checkpoint)
float race_NextCheckpoint (float f)
float race_PreviousCheckpoint (float f)
float race_CheckpointNetworkID (float f)
void race_SendNextCheckpoint (entity e, float spec)
void race_send_recordtime (float msg)
void race_send_speedaward (float msg)
void race_send_speedaward_alltimebest (float msg)
void race_SendRankings (float pos, float prevpos, float del, float msg)
void race_SendStatus (float id, entity e)
void race_setTime (string map, float t, string myuid, string mynetname, entity e)
void race_deleteTime (string map, float pos)
void race_SendTime (entity e, float cp, float t, float tvalid)
void race_ClearTime (entity e)
void dumpsurface (entity e)
void checkpoint_passed ()
void checkpoint_touch ()
void checkpoint_use ()
float race_waypointsprite_visible_for_player (entity e)
void trigger_race_checkpoint_verify ()
vector trigger_race_checkpoint_spawn_evalfunc (entity player, entity spot, vector current)
spawnfunc (trigger_race_checkpoint)
spawnfunc (target_startTimer)
spawnfunc (target_stopTimer)
void race_AbandonRaceCheck (entity p)
void race_StartCompleting ()
void race_PreparePlayer ()
void race_RetractPlayer ()
spawnfunc (info_player_race)
void race_ClearRecords ()
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
void penalty_touch ()
void penalty_use ()
spawnfunc (trigger_race_penalty)
float race_GetFractionalLapCount (entity e)
Variables
const float MAX_CHECKPOINTS = 255
float race_penalty
float race_penalty_accumulator
string race_penalty_reason
float race_checkpoint
entity race_lastpenalty
entity sprite
float race_checkpoint_records [MAX_CHECKPOINTS]
string race_checkpoint_recordholders [MAX_CHECKPOINTS]
float race_checkpoint_lasttimes [MAX_CHECKPOINTS]
float race_checkpoint_lastlaps [MAX_CHECKPOINTS]
entity race_checkpoint_lastplayers [MAX_CHECKPOINTS]
float race_highest_checkpoint
float race_timed_checkpoint
float defrag_ents
float defragcpexists
float have_verified
Function Documentation
void checkpoint_passed ()
Definition at line 564 of file race.qc.
References activator, classname, Damage(), defrag_ents, defragcpexists, entity(), fclose(), FILE_WRITE, find(), fopen(), fputs(), ftos(), g_race_qualifying, GetMapname(), IS_PLAYER, normalize(), other, Portal_ClearAll(), race_checkpoint, race_highest_checkpoint, race_ImposePenaltyTime(), race_NextCheckpoint(), race_penalty, race_penalty_reason, race_SendNextCheckpoint(), race_SendTime(), race_timed_checkpoint, SELFPARAM, setself, spawnflags, strcat(), SUB_UseTargets(), time, trace_plane_normal, W_Porto_Fail(), and world.
Referenced by checkpoint_touch(), and checkpoint_use().
{SELFPARAM();
    string oldmsg;
    entity cp;
    if(other.classname == "porto")
    {
        // do not allow portalling through checkpoints
        trace_plane_normal = normalize(-1 * other.velocity);
        setself(other);
        W_Porto_Fail(0);
        return;
    }
    /*
     * Trigger targets
     */
    if (!((self.spawnflags & 2) && (IS_PLAYER(other))))
    {
        activator = other;
        oldmsg = self.message;
        self.message = "";
        SUB_UseTargets();
        self.message = oldmsg;
    }
    if (!IS_PLAYER(other))
        return;
    /*
     * Remove unauthorized equipment
     */
    Portal_ClearAll(other);
    other.porto_forbidden = 2; // decreased by 1 each StartFrame
    if(defrag_ents)
    {
        if(self.race_checkpoint == -2)
        {
            self.race_checkpoint = other.race_checkpoint;
        }
        float largest_cp_id = 0;
        float cp_amount = 0;
        for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
        {
            cp_amount += 1;
            if(cp.race_checkpoint > largest_cp_id) // update the finish id if someone hit a new checkpoint
            {
                largest_cp_id = cp.race_checkpoint;
                for(cp = world; (cp = find(cp, classname, "target_stopTimer"));)
                    cp.race_checkpoint = largest_cp_id + 1; // finish line
                race_highest_checkpoint = largest_cp_id + 1;
                race_timed_checkpoint = largest_cp_id + 1;
                for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
                {
                    if(cp.race_checkpoint == -2) // set defragcpexists to -1 so that the cp id file will be rewritten when someone finishes
                        defragcpexists = -1;
                }
            }
        }
        if(cp_amount == 0)
        {
            for(cp = world; (cp = find(cp, classname, "target_stopTimer"));)
                cp.race_checkpoint = 1;
            race_highest_checkpoint = 1;
            race_timed_checkpoint = 1;
        }
    }
    if((other.race_checkpoint == -1 && self.race_checkpoint == 0) || (other.race_checkpoint == self.race_checkpoint))
    {
        if(self.race_penalty)
        {
            if(other.race_lastpenalty != self)
            {
                other.race_lastpenalty = self;
                race_ImposePenaltyTime(other, self.race_penalty, self.race_penalty_reason);
            }
        }
        if(other.race_penalty)
            return;
        /*
         * Trigger targets
         */
        if(self.spawnflags & 2)
        {
            activator = other;
            oldmsg = self.message;
            self.message = "";
            SUB_UseTargets();
            self.message = oldmsg;
        }
        if(other.race_respawn_checkpoint != self.race_checkpoint || !other.race_started)
            other.race_respawn_spotref = self; // this is not a spot but a CP, but spawnpoint selection will deal with that
        other.race_respawn_checkpoint = self.race_checkpoint;
        other.race_checkpoint = race_NextCheckpoint(self.race_checkpoint);
        other.race_started = 1;
        race_SendTime(other, self.race_checkpoint, other.race_movetime, boolean(other.race_laptime));
        if(!self.race_checkpoint) // start line
        {
            other.race_laptime = time;
            other.race_movetime = other.race_movetime_frac = other.race_movetime_count = 0;
            other.race_penalty_accumulator = 0;
            other.race_lastpenalty = world;
        }
        if(g_race_qualifying)
            race_SendNextCheckpoint(other, 0);
        if(defrag_ents && defragcpexists < 0 && self.classname == "target_stopTimer")
        {
            float fh;
            defragcpexists = fh = fopen(strcat("maps/", GetMapname(), ".defragcp"), FILE_WRITE);
            if(fh >= 0)
            {
                for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
                fputs(fh, strcat(cp.targetname, " ", ftos(cp.race_checkpoint), "\n"));
            }
            fclose(fh);
        }
    }
    else if(other.race_checkpoint == race_NextCheckpoint(self.race_checkpoint))
    {
        // ignored
    }
    else
    {
        if(self.spawnflags & 4)
            Damage (other, self, self, 10000, DEATH_HURTTRIGGER.m_id, other.origin, '0 0 0');
    }
}
void checkpoint_touch ()
Definition at line 704 of file race.qc.
References checkpoint_passed(), and EXACTTRIGGER_TOUCH.
Referenced by spawnfunc().
{
    EXACTTRIGGER_TOUCH;
    checkpoint_passed();
}
void checkpoint_use ()
Definition at line 710 of file race.qc.
References activator, checkpoint_passed(), and other.
Referenced by spawnfunc().
{
    if(other.classname == "info_player_deathmatch") // a spawn, a spawn
        return;
    other = activator;
    checkpoint_passed();
}
void dumpsurface (entity e)
Definition at line 540 of file race.qc.
References etos(), ftos(), LOG_INFO, n, vector(), and vtos().
{
    float n, si, ni;
    vector norm, vec;
    LOG_INFO("Surfaces of ", etos(e), ":\n");
    LOG_INFO("TEST = ", ftos(getsurfacenearpoint(e, '0 0 0')), "\n");
    for(si = 0; ; ++si)
    {
        n = getsurfacenumpoints(e, si);
        if(n <= 0)
            break;
        LOG_INFO("  Surface ", ftos(si), ":\n");
        norm = getsurfacenormal(e, si);
        LOG_INFO("    Normal = ", vtos(norm), "\n");
        for(ni = 0; ni < n; ++ni)
        {
            vec = getsurfacepoint(e, si, ni);
            LOG_INFO("    Point ", ftos(ni), " = ", vtos(vec), " (", ftos(norm * vec), ")\n");
        }
    }
}
void penalty_touch ()
Definition at line 1115 of file race.qc.
References EXACTTRIGGER_TOUCH, other, race_ImposePenaltyTime(), race_penalty, race_penalty_reason, and SELFPARAM.
Referenced by spawnfunc().
{SELFPARAM();
    EXACTTRIGGER_TOUCH;
    if(other.race_lastpenalty != self)
    {
        other.race_lastpenalty = self;
        race_ImposePenaltyTime(other, self.race_penalty, self.race_penalty_reason);
    }
}
void penalty_use ()
Definition at line 1125 of file race.qc.
References activator, race_ImposePenaltyTime(), race_penalty, race_penalty_reason, and SELFPARAM.
Referenced by spawnfunc().
{SELFPARAM();
    race_ImposePenaltyTime(activator, self.race_penalty, self.race_penalty_reason);
}
void race_AbandonRaceCheck (entity p)
Definition at line 1017 of file race.qc.
References ClientData_Touch(), INFO_RACE_ABANDONED, MAKE_INDEPENDENT_PLAYER, MSG_INFO, race_completing, and world.
Referenced by race_StartCompleting().
{
    if(race_completing && !p.race_completed)
    {
        p.race_completed = 1;
        MAKE_INDEPENDENT_PLAYER(p);
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_ABANDONED, p.netname);
        ClientData_Touch(p);
    }
}
float race_CheckpointNetworkID (float f)
Definition at line 142 of file race.qc.
References race_timed_checkpoint.
Referenced by race_SendNextCheckpoint(), and race_SendTime().
{
    if(race_timed_checkpoint)
    {
        if(f == 0)
            return 254; // start
        else if(f == race_timed_checkpoint)
            return 255; // finish
    }
    return f;
}
void race_ClearRecords ()
Definition at line 1064 of file race.qc.
References entity(), FOREACH_CLIENT, LAMBDA, MAX_CHECKPOINTS, p, race_checkpoint_recordholders, race_checkpoint_records, race_PreparePlayer(), SELFPARAM, string_null, strunzone(), and WITH.
{SELFPARAM();
    float i;
    for(i = 0; i < MAX_CHECKPOINTS; ++i)
    {
        race_checkpoint_records[i] = 0;
        if(race_checkpoint_recordholders[i])
            strunzone(race_checkpoint_recordholders[i]);
        race_checkpoint_recordholders[i] = string_null;
    }
    FOREACH_CLIENT(true, LAMBDA(
        float p = it.race_place;
        WITH(entity, self, it, race_PreparePlayer());
        it.race_place = p;
    ));
}
void race_ClearTime (entity e)
Definition at line 522 of file race.qc.
References IS_REAL_CLIENT, msg_entity, MSG_ONE, RACE_NET_CHECKPOINT_CLEAR, world, WriteByte(), and WRITESPECTATABLE_MSG_ONE.
Referenced by race_PreparePlayer(), and race_RetractPlayer().
{
    e.race_checkpoint = 0;
    e.race_laptime = 0;
    e.race_movetime = e.race_movetime_frac = e.race_movetime_count = 0;
    e.race_penalty_accumulator = 0;
    e.race_lastpenalty = world;
    if(!IS_REAL_CLIENT(e))
        return;
    msg_entity = e;
    WRITESPECTATABLE_MSG_ONE(msg_entity, {
        WriteHeader(MSG_ONE, TE_CSQC_RACE);
        WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_CLEAR); // next
    });
}
void race_deleteTime (string map, float pos)
Definition at line 325 of file race.qc.
References CTS_RECORD, db_put(), db_remove, ftos(), g_cts, GetMapname(), getrankings(), MSG_ALL, race_readTime(), race_readUID(), RACE_RECORD, race_send_recordtime(), race_SendRankings(), RANKINGS_CNT, ServerProgsDB, strcat(), strunzone(), and strzone().
Referenced by GameCommand_delrec().
{
    string rr;
    if(g_cts)
        rr = CTS_RECORD;
    else
        rr = RACE_RECORD;
    float i;
    for (i = pos; i <= RANKINGS_CNT; ++i)
    {
        if (i == RANKINGS_CNT)
        {
            db_remove(ServerProgsDB, strcat(map, rr, "time", ftos(i)));
            db_remove(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(i)));
        }
        else
        {
            db_put(ServerProgsDB, strcat(map, rr, "time", ftos(i)), ftos(race_readTime(GetMapname(), i+1)));
            db_put(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(i)), race_readUID(GetMapname(), i+1));
        }
    }
    race_SendRankings(pos, 0, 1, MSG_ALL);
    if(pos == 1)
        race_send_recordtime(MSG_ALL);
    if(rankings_reply)
        strunzone(rankings_reply);
    rankings_reply = strzone(getrankings());
}
float race_GetFractionalLapCount (entity e)
Definition at line 1147 of file race.qc.
References bound(), classname, entity(), find(), max(), PlayerScore_Add(), race_highest_checkpoint, race_timed_checkpoint, SP_RACE_LAPS, vector(), vlen(), and world.
{
    // interesting metrics (idea by KrimZon) to maybe sort players in the
    // scoreboard, immediately updates when overtaking
    //
    // requires the track to be built so you never get farther away from the
    // next checkpoint, though, and current Xonotic race maps are not built that
    // way
    //
    // also, this code is slow and would need optimization (i.e. "next CP"
    // links on CP entities)
    float l;
    l = PlayerScore_Add(e, SP_RACE_LAPS, 0);
    if(e.race_completed)
        return l; // not fractional
    vector o0, o1;
    float bestfraction, fraction;
    entity lastcp, cp0, cp1;
    float nextcpindex, lastcpindex;
    nextcpindex = max(e.race_checkpoint, 0);
    lastcpindex = e.race_respawn_checkpoint;
    lastcp = e.race_respawn_spotref;
    if(nextcpindex == lastcpindex)
        return l; // finish
    bestfraction = 1;
    for(cp0 = world; (cp0 = find(cp0, classname, "trigger_race_checkpoint")); )
    {
        if(cp0.race_checkpoint != lastcpindex)
            continue;
        if(lastcp)
            if(cp0 != lastcp)
                continue;
        o0 = (cp0.absmin + cp0.absmax) * 0.5;
        for(cp1 = world; (cp1 = find(cp1, classname, "trigger_race_checkpoint")); )
        {
            if(cp1.race_checkpoint != nextcpindex)
                continue;
            o1 = (cp1.absmin + cp1.absmax) * 0.5;
            if(o0 == o1)
                continue;
            fraction = bound(0.0001, vlen(e.origin - o1) / vlen(o0 - o1), 1);
            if(fraction < bestfraction)
                bestfraction = fraction;
        }
    }
    // we are at CP "nextcpindex - bestfraction"
    // race_timed_checkpoint == 4: then nextcp==4 means 0.9999x, nextcp==0 means 0.0000x
    // race_timed_checkpoint == 0: then nextcp==0 means 0.9999x
    float c, nc;
    nc = race_highest_checkpoint + 1;
    c = ((nextcpindex - race_timed_checkpoint + nc + nc - 1) % nc) + 1 - bestfraction;
    return l + c / nc;
}
void race_ImposePenaltyTime (entity pl, float penalty, string reason)
Definition at line 1083 of file race.qc.
References g_race_qualifying, IS_REAL_CLIENT, msg_entity, MSG_ONE, RACE_NET_PENALTY_QUALIFYING, RACE_NET_PENALTY_RACE, time, TIME_ENCODE, WriteByte(), WriteShort(), WRITESPECTATABLE_MSG_ONE, and WriteString().
Referenced by CheatCommand(), checkpoint_passed(), penalty_touch(), and penalty_use().
{
    if(g_race_qualifying)
    {
        pl.race_penalty_accumulator += penalty;
        if(IS_REAL_CLIENT(pl))
        {
            msg_entity = pl;
            WRITESPECTATABLE_MSG_ONE(msg_entity, {
                WriteHeader(MSG_ONE, TE_CSQC_RACE);
                WriteByte(MSG_ONE, RACE_NET_PENALTY_QUALIFYING);
                WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                WriteString(MSG_ONE, reason);
            });
        }
    }
    else
    {
        pl.race_penalty = time + penalty;
        if(IS_REAL_CLIENT(pl))
        {
            msg_entity = pl;
            WRITESPECTATABLE_MSG_ONE(msg_entity, {
                WriteHeader(MSG_ONE, TE_CSQC_RACE);
                WriteByte(MSG_ONE, RACE_NET_PENALTY_RACE);
                WriteShort(MSG_ONE, TIME_ENCODE(penalty));
                WriteString(MSG_ONE, reason);
            });
        }
    }
}
void race_InitSpectator ()
Definition at line 18 of file race.qc.
References g_race_qualifying, msg_entity, and race_SendNextCheckpoint().
Referenced by PlayerPreThink().
{
    if(g_race_qualifying)
        if(msg_entity.enemy.race_laptime)
            race_SendNextCheckpoint(msg_entity.enemy, 1);
}
float race_NextCheckpoint (float f)
Definition at line 120 of file race.qc.
References race_highest_checkpoint.
Referenced by checkpoint_passed(), and trigger_race_checkpoint_verify().
{
    if(f >= race_highest_checkpoint)
        return 0;
    else
        return f + 1;
}
void race_PreparePlayer ()
Definition at line 1034 of file race.qc.
References race_ClearTime(), SELFPARAM, and world.
Referenced by race_ClearRecords().
{SELFPARAM();
    race_ClearTime(self);
    self.race_place = 0;
    self.race_started = 0;
    self.race_respawn_checkpoint = 0;
    self.race_respawn_spotref = world;
}
float race_PreviousCheckpoint (float f)
Definition at line 128 of file race.qc.
References race_highest_checkpoint.
{
    if(f == -1)
        return 0;
    else if(f == 0)
        return race_highest_checkpoint;
    else
        return f - 1;
}
string race_readName (string map, float pos)
Definition at line 88 of file race.qc.
References CTS_RECORD, db_get(), ftos(), g_cts, RACE_RECORD, ServerProgsDB, strcat(), and uid2name().
Referenced by getrankings(), race_SendRankings(), and race_setTime().
{
    string rr = (g_cts) ? CTS_RECORD : RACE_RECORD;
    return uid2name(db_get(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(pos))));
}
float race_readPos (string map, float t)
Definition at line 41 of file race.qc.
References race_readTime(), and RANKINGS_CNT.
Referenced by race_setTime(), and race_writeTime().
{
    float i;
    for (i = 1; i <= RANKINGS_CNT; ++i)
    if (race_readTime(map, i) == 0 || race_readTime(map, i) > t)
        return i;
    return 0; // pos is zero if unranked
}
float race_readTime (string map, float pos)
Definition at line 27 of file race.qc.
References CTS_RECORD, db_get(), ftos(), g_cts, RACE_RECORD, ServerProgsDB, stof(), and strcat().
Referenced by getladder(), getrankings(), race_deleteTime(), race_readPos(), race_send_recordtime(), race_SendRankings(), race_setTime(), and race_writeTime().
{
    string rr = (g_cts) ? CTS_RECORD : RACE_RECORD;
    return stof(db_get(ServerProgsDB, strcat(map, rr, "time", ftos(pos))));
}
string race_readUID (string map, float pos)
Definition at line 34 of file race.qc.
References CTS_RECORD, db_get(), ftos(), g_cts, RACE_RECORD, ServerProgsDB, and strcat().
Referenced by getladder(), race_deleteTime(), race_setTime(), and race_writeTime().
{
    string rr = (g_cts) ? CTS_RECORD : RACE_RECORD;
    return db_get(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(pos)));
}
void race_RetractPlayer ()
Definition at line 1043 of file race.qc.
References g_cts, g_race, race_ClearTime(), race_respawn_checkpoint, race_timed_checkpoint, and SELFPARAM.
{SELFPARAM();
    if(!g_race && !g_cts)
        return;
    if(self.race_respawn_checkpoint == 0 || self.race_respawn_checkpoint == race_timed_checkpoint)
        race_ClearTime(self);
    self.race_checkpoint = self.race_respawn_checkpoint;
}
void race_send_recordtime (float msg)
Definition at line 190 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RECORD, race_readTime(), WriteByte(), and WriteInt24_t().
Referenced by race_deleteTime(), and race_setTime().
{
    // send the server best time
    WriteHeader(msg, TE_CSQC_RACE);
    WriteByte(msg, RACE_NET_SERVER_RECORD);
    WriteInt24_t(msg, race_readTime(GetMapname(), 1));
}
void race_send_speedaward (float msg)
Definition at line 199 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD, speedaward_holder, speedaward_speed, WriteByte(), WriteInt24_t(), and WriteString().
{
    // send the best speed of the round
    WriteHeader(msg, TE_CSQC_RACE);
    WriteByte(msg, RACE_NET_SPEED_AWARD);
    WriteInt24_t(msg, floor(speedaward_speed+0.5));
    WriteString(msg, speedaward_holder);
}
void race_send_speedaward_alltimebest (float msg)
Definition at line 208 of file race.qc.
References floor(), RACE_NET_SPEED_AWARD_BEST, speedaward_alltimebest, speedaward_alltimebest_holder, WriteByte(), WriteInt24_t(), and WriteString().
{
    // send the best speed
    WriteHeader(msg, TE_CSQC_RACE);
    WriteByte(msg, RACE_NET_SPEED_AWARD_BEST);
    WriteInt24_t(msg, floor(speedaward_alltimebest+0.5));
    WriteString(msg, speedaward_alltimebest_holder);
}
void race_SendNextCheckpoint (entity e, float spec)
Definition at line 154 of file race.qc.
References IS_REAL_CLIENT, msg_entity, MSG_ONE, race_checkpoint_recordholders, race_checkpoint_records, race_CheckpointNetworkID(), RACE_NET_CHECKPOINT_NEXT_QUALIFYING, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING, time, WriteByte(), WriteCoord(), WriteInt24_t(), WRITESPECTATABLE_MSG_ONE, and WriteString().
Referenced by checkpoint_passed(), race_InitSpectator(), and race_SendTime().
{
    float recordtime;
    string recordholder;
    float cp;
    if(!e.race_laptime)
        return;
    cp = e.race_checkpoint;
    recordtime = race_checkpoint_records[cp];
    recordholder = race_checkpoint_recordholders[cp];
    if(recordholder == e.netname)
        recordholder = "";
    if(!IS_REAL_CLIENT(e))
        return;
    if(!spec)
        msg_entity = e;
    WRITESPECTATABLE_MSG_ONE(msg_entity, {
        WriteHeader(MSG_ONE, TE_CSQC_RACE);
        if(spec)
        {
            WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_SPEC_QUALIFYING);
            //WriteCoord(MSG_ONE, e.race_laptime - e.race_penalty_accumulator);
            WriteCoord(MSG_ONE, time - e.race_movetime - e.race_penalty_accumulator);
        }
        else
            WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_NEXT_QUALIFYING);
        WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player will be at next
        WriteInt24_t(MSG_ONE, recordtime);
        WriteString(MSG_ONE, recordholder);
    });
}
void race_SendRankings (float pos, float prevpos, float del, float msg)
Definition at line 217 of file race.qc.
References GetMapname(), RACE_NET_SERVER_RANKINGS, race_readName(), race_readTime(), WriteByte(), WriteInt24_t(), WriteShort(), and WriteString().
Referenced by race_deleteTime(), and race_setTime().
{
    WriteHeader(msg, TE_CSQC_RACE);
    WriteByte(msg, RACE_NET_SERVER_RANKINGS);
    WriteShort(msg, pos);
    WriteShort(msg, prevpos);
    WriteShort(msg, del);
    WriteString(msg, race_readName(GetMapname(), pos));
    WriteInt24_t(msg, race_readTime(GetMapname(), pos));
}
void race_SendStatus (float id, entity e)
Definition at line 228 of file race.qc.
References IS_REAL_CLIENT, MSG_ALL, msg_entity, MSG_ONE, RACE_NET_SERVER_STATUS, WriteByte(), WriteShort(), WRITESPECTATABLE_MSG_ONE, and WriteString().
Referenced by race_setTime().
{
    if(!IS_REAL_CLIENT(e))
        return;
    float msg;
    if (id == 0)
        msg = MSG_ONE;
    else
        msg = MSG_ALL;
    msg_entity = e;
    WRITESPECTATABLE_MSG_ONE(msg_entity, {
        WriteHeader(msg, TE_CSQC_RACE);
        WriteByte(msg, RACE_NET_SERVER_STATUS);
        WriteShort(msg, id);
        WriteString(msg, e.netname);
    });
}
void race_SendTime (entity e, float cp, float t, float tvalid)
Definition at line 357 of file race.qc.
References autocvar_fraglimit, ClientData_Touch(), entity(), FOREACH_CLIENT, g_race_qualifying, game_starttime, GetMapname(), IS_PLAYER, IS_REAL_CLIENT, LAMBDA, MAKE_INDEPENDENT_PLAYER, msg_entity, MSG_INFO, MSG_ONE, MUTATOR_CALLHOOK, PlayerScore_Add(), PlayerTeamScore_Add(), race_checkpoint_lastlaps, race_checkpoint_lastplayers, race_checkpoint_lasttimes, race_checkpoint_recordholders, race_checkpoint_records, race_CheckpointNetworkID(), race_completing, RACE_NET_CHECKPOINT_HIT_QUALIFYING, RACE_NET_CHECKPOINT_HIT_RACE, RACE_NET_CHECKPOINT_HIT_RACE_BY_OPPONENT, race_SendNextCheckpoint(), race_setTime(), race_StartCompleting(), race_timed_checkpoint, s, SP_RACE_FASTEST, SP_RACE_LAPS, SP_RACE_TIME, ST_RACE_LAPS, strcat1(), strunzone(), strzone(), time, TIME_ENCODE, world, WriteByte(), WriteInt24_t(), WRITESPECTATABLE_MSG_ONE, and WriteString().
Referenced by checkpoint_passed().
{
    float snew, l;
    if(g_race_qualifying)
        t += e.race_penalty_accumulator;
    t = TIME_ENCODE(t); // make integer
    // adding just 0.4 so it rounds down in the .5 case (matching the timer display)
    if(tvalid)
    if(cp == race_timed_checkpoint) // finish line
    if (!e.race_completed)
    {
        float s;
        if(g_race_qualifying)
        {
            s = PlayerScore_Add(e, SP_RACE_FASTEST, 0);
            if(!s || t < s)
                PlayerScore_Add(e, SP_RACE_FASTEST, t - s);
        }
        else
        {
            s = PlayerScore_Add(e, SP_RACE_FASTEST, 0);
            if(!s || t < s)
                PlayerScore_Add(e, SP_RACE_FASTEST, t - s);
            s = PlayerScore_Add(e, SP_RACE_TIME, 0);
            snew = TIME_ENCODE(time - game_starttime);
            PlayerScore_Add(e, SP_RACE_TIME, snew - s);
            l = PlayerTeamScore_Add(e, SP_RACE_LAPS, ST_RACE_LAPS, 1);
            if(autocvar_fraglimit)
                if(l >= autocvar_fraglimit)
                    race_StartCompleting();
            if(race_completing)
            {
                e.race_completed = 1;
                MAKE_INDEPENDENT_PLAYER(e);
                Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_FINISHED, e.netname);
                ClientData_Touch(e);
            }
        }
    }
    float recordtime;
    string recordholder;
    if(g_race_qualifying)
    {
        if(tvalid)
        {
            recordtime = race_checkpoint_records[cp];
            recordholder = strcat1(race_checkpoint_recordholders[cp]); // make a tempstring copy, as we'll possibly strunzone it!
            if(recordholder == e.netname)
                recordholder = "";
            if(t != 0)
            {
                if(cp == race_timed_checkpoint)
                {
                    race_setTime(GetMapname(), t, e.crypto_idfp, e.netname, e);
                    MUTATOR_CALLHOOK(Race_FinalCheckpoint, e);
                }
                if(t < recordtime || recordtime == 0)
                {
                    race_checkpoint_records[cp] = t;
                    if(race_checkpoint_recordholders[cp])
                        strunzone(race_checkpoint_recordholders[cp]);
                    race_checkpoint_recordholders[cp] = strzone(e.netname);
                    if(g_race_qualifying)
                    {
                        FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it) && it.race_checkpoint == cp, LAMBDA(race_SendNextCheckpoint(it, 0)));
                    }
                }
            }
        }
        else
        {
            // dummies
            t = 0;
            recordtime = 0;
            recordholder = "";
        }
        if(IS_REAL_CLIENT(e))
        {
            msg_entity = e;
            if(g_race_qualifying)
            {
                WRITESPECTATABLE_MSG_ONE(msg_entity, {
                    WriteHeader(MSG_ONE, TE_CSQC_RACE);
                    WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_HIT_QUALIFYING);
                    WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player now is at
                    WriteInt24_t(MSG_ONE, t); // time to that intermediate
                    WriteInt24_t(MSG_ONE, recordtime); // previously best time
                    WriteString(MSG_ONE, recordholder); // record holder
                });
            }
        }
    }
    else // RACE! Not Qualifying
    {
        float lself, lother, othtime;
        entity oth;
        oth = race_checkpoint_lastplayers[cp];
        if(oth)
        {
            lself = PlayerScore_Add(e, SP_RACE_LAPS, 0);
            lother = race_checkpoint_lastlaps[cp];
            othtime = race_checkpoint_lasttimes[cp];
        }
        else
            lself = lother = othtime = 0;
        if(IS_REAL_CLIENT(e))
        {
            msg_entity = e;
            WRITESPECTATABLE_MSG_ONE(msg_entity, {
                WriteHeader(MSG_ONE, TE_CSQC_RACE);
                WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_HIT_RACE);
                WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player now is at
                if(e == oth)
                {
                    WriteInt24_t(MSG_ONE, 0);
                    WriteByte(MSG_ONE, 0);
                    WriteString(MSG_ONE, "");
                }
                else
                {
                    WriteInt24_t(MSG_ONE, TIME_ENCODE(time - race_checkpoint_lasttimes[cp]));
                    WriteByte(MSG_ONE, lself - lother);
                    WriteString(MSG_ONE, oth.netname); // record holder
                }
            });
        }
        race_checkpoint_lastplayers[cp] = e;
        race_checkpoint_lasttimes[cp] = time;
        race_checkpoint_lastlaps[cp] = lself;
        if(IS_REAL_CLIENT(oth))
        {
            msg_entity = oth;
            WRITESPECTATABLE_MSG_ONE(msg_entity, {
                WriteHeader(MSG_ONE, TE_CSQC_RACE);
                WriteByte(MSG_ONE, RACE_NET_CHECKPOINT_HIT_RACE_BY_OPPONENT);
                WriteByte(MSG_ONE, race_CheckpointNetworkID(cp)); // checkpoint the player now is at
                if(e == oth)
                {
                    WriteInt24_t(MSG_ONE, 0);
                    WriteByte(MSG_ONE, 0);
                    WriteString(MSG_ONE, "");
                }
                else
                {
                    WriteInt24_t(MSG_ONE, TIME_ENCODE(time - othtime));
                    WriteByte(MSG_ONE, lother - lself);
                    WriteString(MSG_ONE, e.netname); // record holder
                }
            });
        }
    }
}
void race_setTime (string map, float t, string myuid, string mynetname, entity e)
Definition at line 247 of file race.qc.
References GetMapname(), getrankings(), INFO_RACE_FAIL_UNRANKED, INFO_RACE_NEW_BROKEN, INFO_RACE_NEW_MISSING_UID, MSG_ALL, MSG_INFO, race_readName(), race_readPos(), race_readTime(), race_readUID(), race_send_recordtime(), race_SendRankings(), race_SendStatus(), race_writeTime(), RANKINGS_CNT, strunzone(), strzone(), time, TIME_DECODE, world, and write_recordmarker().
Referenced by race_SendTime().
{
    // netname only used TEMPORARILY for printing
    float newpos, player_prevpos;
    newpos = race_readPos(map, t);
    float i;
    player_prevpos = 0;
    for(i = 1; i <= RANKINGS_CNT; ++i)
    {
        if(race_readUID(map, i) == myuid)
            player_prevpos = i;
    }
    float oldrec;
    string oldrec_holder;
    if (player_prevpos && (player_prevpos < newpos || !newpos))
    {
        oldrec = race_readTime(GetMapname(), player_prevpos);
        race_SendStatus(0, e); // "fail"
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_FAIL_RANKED, mynetname, player_prevpos, t, oldrec);
        return;
    }
    else if (!newpos)
    {
        // no ranking, time worse than the worst ranked
        oldrec = race_readTime(GetMapname(), RANKINGS_CNT);
        race_SendStatus(0, e); // "fail"
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_FAIL_UNRANKED, mynetname, RANKINGS_CNT, t, oldrec);
        return;
    }
    // if we didn't hit a return yet, we have a new record!
    // if the player does not have a UID we can unfortunately not store the record, as the rankings system relies on UIDs
    if(myuid == "")
    {
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_NEW_MISSING_UID, mynetname, t);
        return;
    }
    oldrec = race_readTime(GetMapname(), newpos);
    oldrec_holder = race_readName(GetMapname(), newpos);
    // store new ranking
    race_writeTime(GetMapname(), t, myuid);
    if (newpos == 1)
    {
        write_recordmarker(e, time - TIME_DECODE(t), TIME_DECODE(t));
        race_send_recordtime(MSG_ALL);
    }
    race_SendRankings(newpos, player_prevpos, 0, MSG_ALL);
    if(rankings_reply)
        strunzone(rankings_reply);
    rankings_reply = strzone(getrankings());
    if(newpos == player_prevpos)
    {
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_NEW_IMPROVED, mynetname, newpos, t, oldrec);
        if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
        else { race_SendStatus(1, e); } // "new time"
    }
    else if(oldrec == 0)
    {
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_NEW_SET, mynetname, newpos, t);
        if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
        else { race_SendStatus(2, e); } // "new rank"
    }
    else
    {
        Send_Notification(NOTIF_ALL, world, MSG_INFO, INFO_RACE_NEW_BROKEN, mynetname, oldrec_holder, newpos, t, oldrec);
        if(newpos == 1) { race_SendStatus(3, e); } // "new server record"
        else { race_SendStatus(2, e); } // "new rank"
    }
}
void race_StartCompleting ()
Definition at line 1028 of file race.qc.
References FOREACH_CLIENT, IS_DEAD, IS_PLAYER, LAMBDA, race_AbandonRaceCheck(), and race_completing.
Referenced by InitiateSuddenDeath(), and race_SendTime().
{
    race_completing = 1;
    FOREACH_CLIENT(IS_PLAYER(it) && IS_DEAD(it), LAMBDA(race_AbandonRaceCheck(it)));
}
float race_waypointsprite_visible_for_player (entity e)
Definition at line 719 of file race.qc.
References SELFPARAM.
Referenced by spawnfunc().
{SELFPARAM();
    if(e.race_checkpoint == -1 || self.owner.race_checkpoint == -2)
        return true;
    else if(e.race_checkpoint == self.owner.race_checkpoint)
        return true;
    else
        return false;
}
void race_writeTime (string map, float t, string myuid)
Definition at line 51 of file race.qc.
References CTS_RECORD, db_put(), ftos(), g_cts, race_readPos(), race_readTime(), race_readUID(), RACE_RECORD, RANKINGS_CNT, ServerProgsDB, and strcat().
Referenced by race_setTime().
{
    string rr = (g_cts) ? CTS_RECORD : RACE_RECORD;
    float newpos;
    newpos = race_readPos(map, t);
    float i, prevpos = 0;
    for(i = 1; i <= RANKINGS_CNT; ++i)
    {
        if(race_readUID(map, i) == myuid)
            prevpos = i;
    }
    if (prevpos)
    {
        // player improved his existing record, only have to iterate on ranks between new and old recs
        for (i = prevpos; i > newpos; --i)
        {
            db_put(ServerProgsDB, strcat(map, rr, "time", ftos(i)), ftos(race_readTime(map, i - 1)));
            db_put(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(i)), race_readUID(map, i - 1));
        }
    }
    else
    {
        // player has no ranked record yet
        for (i = RANKINGS_CNT; i > newpos; --i)
        {
            db_put(ServerProgsDB, strcat(map, rr, "time", ftos(i)), ftos(race_readTime(map, i - 1)));
            db_put(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(i)), race_readUID(map, i - 1));
        }
    }
    // store new time itself
    db_put(ServerProgsDB, strcat(map, rr, "time", ftos(newpos)), ftos(t));
    db_put(ServerProgsDB, strcat(map, rr, "crypto_idfp", ftos(newpos)), myuid);
}
spawnfunc (target_checkpoint)
Definition at line 973 of file race.qc.
References checkpoint_touch(), checkpoint_use(), classname, defrag_ents, EXACTTRIGGER_INIT, g_cts, g_race, InitializeEntity(), INITPRIO_FINDTARGET, message, message2, MOVE_NORMAL, NULL, race_checkpoint, race_penalty_reason, race_timed_checkpoint, race_waypointsprite_visible_for_player(), spawnflags, sprite, time, trace_endpos, trigger_race_checkpoint_verify(), vector(), and waypoint_spawnforitem_force().
{
    vector o;
    if(!g_race && !g_cts) { remove(self); return; }
    defrag_ents = 1;
    EXACTTRIGGER_INIT;
    self.use = checkpoint_use;
    if (!(self.spawnflags & 1))
        self.touch = checkpoint_touch;
    o = (self.absmin + self.absmax) * 0.5;
    tracebox(o, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL), o - '0 0 1' * (o.z - self.absmin.z), MOVE_NORMAL, self);
    waypoint_spawnforitem_force(self, trace_endpos);
    self.nearestwaypointtimeout = time + 1000000000;
    if(self.message == "")
        self.message = "went backwards";
    if (self.message2 == "")
        self.message2 = "was pushed backwards by";
    if (self.race_penalty_reason == "")
        self.race_penalty_reason = "missing a checkpoint";
    if(self.classname == "target_startTimer")
        self.race_checkpoint = 0;
    else
        self.race_checkpoint = -2;
    race_timed_checkpoint = 1;
    if(self.race_checkpoint == 0)
        WaypointSprite_SpawnFixed(WP_RaceStart, o, self, sprite, RADARICON_NONE);
    else
        WaypointSprite_SpawnFixed(WP_RaceCheckpoint, o, self, sprite, RADARICON_NONE);
    self.sprite.waypointsprite_visible_for_player = race_waypointsprite_visible_for_player;
    InitializeEntity(self, trigger_race_checkpoint_verify, INITPRIO_FINDTARGET);
}
spawnfunc (trigger_race_checkpoint)
Definition at line 925 of file race.qc.
References checkpoint_touch(), checkpoint_use(), EXACTTRIGGER_INIT, g_cts, g_race, InitializeEntity(), INITPRIO_FINDTARGET, message, message2, MOVE_NORMAL, NULL, race_checkpoint, race_highest_checkpoint, race_penalty, race_penalty_reason, race_timed_checkpoint, race_waypointsprite_visible_for_player(), spawnflags, sprite, time, trace_endpos, trigger_race_checkpoint_spawn_evalfunc(), trigger_race_checkpoint_verify(), vector(), and waypoint_spawnforitem_force().
{
    vector o;
    if(!g_race && !g_cts) { remove(self); return; }
    EXACTTRIGGER_INIT;
    self.use = checkpoint_use;
    if (!(self.spawnflags & 1))
        self.touch = checkpoint_touch;
    o = (self.absmin + self.absmax) * 0.5;
    tracebox(o, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL), o - '0 0 1' * (o.z - self.absmin.z), MOVE_NORMAL, self);
    waypoint_spawnforitem_force(self, trace_endpos);
    self.nearestwaypointtimeout = time + 1000000000;
    if(self.message == "")
        self.message = "went backwards";
    if (self.message2 == "")
        self.message2 = "was pushed backwards by";
    if (self.race_penalty_reason == "")
        self.race_penalty_reason = "missing a checkpoint";
    self.race_checkpoint = self.cnt;
    if(self.race_checkpoint > race_highest_checkpoint)
    {
        race_highest_checkpoint = self.race_checkpoint;
        if(self.spawnflags & 8)
            race_timed_checkpoint = self.race_checkpoint;
        else
            race_timed_checkpoint = 0;
    }
    if(!self.race_penalty)
    {
        if(self.race_checkpoint)
            WaypointSprite_SpawnFixed(WP_RaceCheckpoint, o, self, sprite, RADARICON_NONE);
        else
            WaypointSprite_SpawnFixed(WP_RaceStartFinish, o, self, sprite, RADARICON_NONE);
    }
    self.sprite.waypointsprite_visible_for_player = race_waypointsprite_visible_for_player;
    self.spawn_evalfunc = trigger_race_checkpoint_spawn_evalfunc;
    InitializeEntity(self, trigger_race_checkpoint_verify, INITPRIO_FINDTARGET);
}
spawnfunc (target_startTimer)
Definition at line 1014 of file race.qc.
{ spawnfunc_target_checkpoint(this); }
spawnfunc (target_stopTimer)
Definition at line 1015 of file race.qc.
{ spawnfunc_target_checkpoint(this); }
spawnfunc (info_player_race)
Definition at line 1052 of file race.qc.
References g_cts, g_race, race_highest_place_spawn, race_lowest_place_spawn, race_place, and race_spawns.
{
    if(!g_race && !g_cts) { remove(self); return; }
    ++race_spawns;
    spawnfunc_info_player_deathmatch(this);
    if(self.race_place > race_highest_place_spawn)
        race_highest_place_spawn = self.race_place;
    if(self.race_place < race_lowest_place_spawn)
        race_lowest_place_spawn = self.race_place;
}
spawnfunc (trigger_race_penalty)
Definition at line 1130 of file race.qc.
References EXACTTRIGGER_INIT, penalty_touch(), penalty_use(), race_penalty, race_penalty_reason, and spawnflags.
{
    // TODO: find out why this wasnt done:
    //if(!g_cts && !g_race) { remove(self); return; }
    EXACTTRIGGER_INIT;
    self.use = penalty_use;
    if (!(self.spawnflags & 1))
        self.touch = penalty_touch;
    if (self.race_penalty_reason == "")
        self.race_penalty_reason = "missing a checkpoint";
    if (!self.race_penalty)
        self.race_penalty = 5;
}
vector trigger_race_checkpoint_spawn_evalfunc (entity player, entity spot, vector current)
Definition at line 893 of file race.qc.
References g_race_qualifying, race_checkpoint, race_highest_place_spawn, race_lowest_place_spawn, SELFPARAM, and SPAWN_PRIO_RACE_PREVIOUS_SPAWN.
Referenced by spawnfunc().
{SELFPARAM();
    if(g_race_qualifying)
    {
        // spawn at first
        if(self.race_checkpoint != 0)
            return '-1 0 0';
        if(spot.race_place != race_lowest_place_spawn)
            return '-1 0 0';
    }
    else
    {
        if(self.race_checkpoint != player.race_respawn_checkpoint)
            return '-1 0 0';
        // try reusing the previous spawn
        if(self == player.race_respawn_spotref || spot == player.race_respawn_spotref)
            current.x += SPAWN_PRIO_RACE_PREVIOUS_SPAWN;
        if(self.race_checkpoint == 0)
        {
            float pl;
            pl = player.race_place;
            if(pl > race_highest_place_spawn)
                pl = 0;
            if(pl == 0 && !player.race_started)
                pl = race_highest_place_spawn; // use last place if he has not even touched finish yet
            if(spot.race_place != pl)
                return '-1 0 0';
        }
    }
    return current;
}
void trigger_race_checkpoint_verify ()
Definition at line 730 of file race.qc.
References argv(), classname, defrag_ents, defragcpexists, entity(), error(), fclose(), fgets(), FILE_READ, find(), fopen(), ftos(), g_race, g_race_qualifying, GetMapname(), have_verified, p, race_highest_checkpoint, race_highest_place_spawn, race_lowest_place_spawn, race_NextCheckpoint(), race_place, race_timed_checkpoint, SELFPARAM, setself, spawn(), Spawn_FilterOutBadSpots(), stof(), STR_PLAYER, strcat(), targetname, tokenize_console, and world.
Referenced by spawnfunc().
{SELFPARAM();
    entity cp;
    float i, p;
    float qual;
    if(have_verified)
        return;
    have_verified = 1;
    qual = g_race_qualifying;
    setself(spawn());
    self.classname = STR_PLAYER;
    if(g_race)
    {
        for(i = 0; i <= race_highest_checkpoint; ++i)
        {
            self.race_checkpoint = race_NextCheckpoint(i);
            // race only (middle of the race)
            g_race_qualifying = 0;
            self.race_place = 0;
            if(!Spawn_FilterOutBadSpots(findchain(classname, "info_player_deathmatch"), 0, false))
                error(strcat("Checkpoint ", ftos(i), " misses a spawnpoint with race_place==", ftos(self.race_place), " (used for respawning in race) - bailing out"));
            if(i == 0)
            {
                // qualifying only
                g_race_qualifying = 1;
                self.race_place = race_lowest_place_spawn;
                if(!Spawn_FilterOutBadSpots(findchain(classname, "info_player_deathmatch"), 0, false))
                    error(strcat("Checkpoint ", ftos(i), " misses a spawnpoint with race_place==", ftos(self.race_place), " (used for qualifying) - bailing out"));
                // race only (initial spawn)
                g_race_qualifying = 0;
                for(p = 1; p <= race_highest_place_spawn; ++p)
                {
                    self.race_place = p;
                    if(!Spawn_FilterOutBadSpots(findchain(classname, "info_player_deathmatch"), 0, false))
                        error(strcat("Checkpoint ", ftos(i), " misses a spawnpoint with race_place==", ftos(self.race_place), " (used for initially spawning in race) - bailing out"));
                }
            }
        }
    }
    else if(!defrag_ents)
    {
        // qualifying only
        self.race_checkpoint = race_NextCheckpoint(0);
        g_race_qualifying = 1;
        self.race_place = race_lowest_place_spawn;
        if(!Spawn_FilterOutBadSpots(findchain(classname, "info_player_deathmatch"), 0, false))
            error(strcat("Checkpoint 0 misses a spawnpoint with race_place==", ftos(self.race_place), " (used for qualifying) - bailing out"));
    }
    else
    {
        self.race_checkpoint = race_NextCheckpoint(0);
        g_race_qualifying = 1;
        self.race_place = 0; // there's only one spawn on defrag maps
        // check if a defragcp file already exists, then read it and apply the checkpoint order
        float fh;
        float len;
        string l;
        defragcpexists = fh = fopen(strcat("maps/", GetMapname(), ".defragcp"), FILE_READ);
        if(fh >= 0)
        {
            while((l = fgets(fh)))
            {
                len = tokenize_console(l);
                if(len != 2)
                {
                    defragcpexists = -1; // something's wrong in the defrag cp file, set defragcpexists to -1 so that it will be rewritten when someone finishes
                    continue;
                }
                for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
                    if(argv(0) == cp.targetname)
                        cp.race_checkpoint = stof(argv(1));
            }
            fclose(fh);
        }
    }
    g_race_qualifying = qual;
    if(race_timed_checkpoint)
    {
        if(defrag_ents)
        {
            for(cp = world; (cp = find(cp, classname, "target_startTimer"));)
                WaypointSprite_UpdateSprites(cp.sprite, WP_RaceStart, WP_Null, WP_Null);
            for(cp = world; (cp = find(cp, classname, "target_stopTimer"));)
                WaypointSprite_UpdateSprites(cp.sprite, WP_RaceFinish, WP_Null, WP_Null);
            for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
            {
                if(cp.race_checkpoint == -2) // something's wrong with the defrag cp file or it has not been written yet, set defragcpexists to -1 so that it will be rewritten when someone finishes
                    defragcpexists = -1;
            }
            if(defragcpexists != -1)
            {
                float largest_cp_id = 0;
                for(cp = world; (cp = find(cp, classname, "target_checkpoint"));)
                    if(cp.race_checkpoint > largest_cp_id)
                        largest_cp_id = cp.race_checkpoint;
                for(cp = world; (cp = find(cp, classname, "target_stopTimer"));)
                    cp.race_checkpoint = largest_cp_id + 1; // finish line
                race_highest_checkpoint = largest_cp_id + 1;
                race_timed_checkpoint = largest_cp_id + 1;
            }
            else
            {
                for(cp = world; (cp = find(cp, classname, "target_stopTimer"));)
                    cp.race_checkpoint = 255; // finish line
                race_highest_checkpoint = 255;
                race_timed_checkpoint = 255;
            }
        }
        else
        {
            for(cp = world; (cp = find(cp, classname, "trigger_race_checkpoint")); )
                if(cp.sprite)
                {
                    if(cp.race_checkpoint == 0)
                        WaypointSprite_UpdateSprites(cp.sprite, WP_RaceStart, WP_Null, WP_Null);
                    else if(cp.race_checkpoint == race_timed_checkpoint)
                        WaypointSprite_UpdateSprites(cp.sprite, WP_RaceFinish, WP_Null, WP_Null);
                }
        }
    }
    if(defrag_ents)
    {
        entity trigger, targ;
        for(trigger = world; (trigger = find(trigger, classname, "trigger_multiple")); )
            for(targ = world; (targ = find(targ, targetname, trigger.target)); )
                if (targ.classname == "target_checkpoint" || targ.classname == "target_startTimer" || targ.classname == "target_stopTimer")
                {
                    trigger.wait = 0;
                    trigger.delay = 0;
                    targ.wait = 0;
                    targ.delay = 0;
                    // These just make the game crash on some maps with oddly shaped triggers.
                    // (on the other hand they used to fix the case when two players ran through a checkpoint at once,
                    // and often one of them just passed through without being registered. Hope it's fixed  in a better way now.
                    // (happened on item triggers too)
                    //
                    //targ.wait = -2;
                    //targ.delay = 0;
                    //setsize(targ, trigger.mins, trigger.maxs);
                    //setorigin(targ, trigger.origin);
                    //remove(trigger);
                }
    }
    remove(self);
    setself(this);
}
void W_Porto_Fail (float failhard)
Referenced by checkpoint_passed().
Variable Documentation
float defrag_ents
Definition at line 117 of file race.qc.
Referenced by checkpoint_passed(), spawnfunc(), and trigger_race_checkpoint_verify().
float defragcpexists
Definition at line 118 of file race.qc.
Referenced by checkpoint_passed(), and trigger_race_checkpoint_verify().
float have_verified
Definition at line 729 of file race.qc.
Referenced by trigger_race_checkpoint_verify().
const float MAX_CHECKPOINTS = 255
Definition at line 96 of file race.qc.
Referenced by race_ClearRecords().
float race_checkpoint
Definition at line 103 of file race.qc.
float race_checkpoint_lastlaps[MAX_CHECKPOINTS]
Definition at line 111 of file race.qc.
Referenced by race_SendTime().
entity race_checkpoint_lastplayers[MAX_CHECKPOINTS]
Definition at line 112 of file race.qc.
Referenced by race_SendTime().
float race_checkpoint_lasttimes[MAX_CHECKPOINTS]
Definition at line 110 of file race.qc.
Referenced by race_SendTime().
string race_checkpoint_recordholders[MAX_CHECKPOINTS]
Definition at line 109 of file race.qc.
Referenced by race_ClearRecords(), race_SendNextCheckpoint(), and race_SendTime().
float race_checkpoint_records[MAX_CHECKPOINTS]
Definition at line 108 of file race.qc.
Referenced by race_ClearRecords(), race_SendNextCheckpoint(), and race_SendTime().
float race_highest_checkpoint
Definition at line 114 of file race.qc.
Referenced by checkpoint_passed(), race_GetFractionalLapCount(), race_NextCheckpoint(), race_PreviousCheckpoint(), spawnfunc(), and trigger_race_checkpoint_verify().
entity race_lastpenalty
Definition at line 104 of file race.qc.
float race_penalty
Definition at line 100 of file race.qc.
float race_penalty_accumulator
Definition at line 101 of file race.qc.
string race_penalty_reason
Definition at line 102 of file race.qc.
Referenced by checkpoint_passed(), penalty_touch(), penalty_use(), and spawnfunc().
float race_timed_checkpoint
Definition at line 115 of file race.qc.
Referenced by checkpoint_passed(), race_CheckpointNetworkID(), race_GetFractionalLapCount(), race_RetractPlayer(), race_SendTime(), spawnfunc(), and trigger_race_checkpoint_verify().
entity sprite
Definition at line 106 of file race.qc.