Xonotic: dpdefs/upstream/csprogsdefs.qc File Reference
csprogsdefs.qc File Reference
Macros
#define SPA_LIGHTMAP0_TEXCOORDS 5
#define SPA_LIGHTMAP_COLOR 6
#define SPA_POSITION 0
#define SPA_R_AXIS 3
#define SPA_S_AXIS 1
#define SPA_T_AXIS 2
#define SPA_TEXCOORDS0 4
Functions
float checkpvs (vector viewpos, entity viewee)
void coverage ()
vector drawgetimagesize (string pic)
float drawsubpic (vector position, vector size, string pic, vector srcPosition, vector srcSize, vector rgb, float alpha, float flag)
entity () spawn = #17
entity (entity start,.string fld, string match) find
entity (vector org, float rad) findradius
entity (entity e) nextent
entity (entity start,.float fld, float match) findfloat = #449
entity (entity start,.entity fld, entity match) findentity
entity (.string fld, string match) findchain
entity (.float fld, float match) findchainfloat = #450
entity (float num) entitybyindex
float findfont (string s)
float (float f, float t, float n) CSQC_InputEvent = #32
float (string s) CSQC_ConsoleCommand = #45
float () random = #34
float (vector v) vlen = #13
float (vector v1, vector v2, float tryents, entity ignoreentity) traceline
float (float v) rint = #37
float (entity e) checkbottom
float (string name, string value) registercvar = #228
float (float a,...) min = #95
float (float f, float f) pow
float (string filename, float mode) fopen
float (string str, string sub, float startpos) strstrofs
float (vector position, float character, vector scale, vector rgb, float alpha, float flag) drawcharacter_builtin
float (vector position, string text, vector scale, vector rgb, float alpha, float flag) drawstring_builtin = #322
float (vector position, vector size, vector rgb, float alpha, float flag) drawfill_builtin
float (vector position, string text, vector scale, float alpha, float flag) drawcolorcodedstring_builtin
float (entity e, float s) getsurfacenumpoints
float (entity e, vector p) getsurfacenearpoint
float (string pattern, float caseinsensitive, float quiet) search_begin
float (entity ent, string tagname) gettagindex
float (float bufhandle, string str, float order) bufstr_add = #630
float (vector org, vector vel) spawnparticle
float (vector org, vector vel, float theme) quickparticle
float (vector org, vector vel, float delay, float collisiondelay) delayedparticle
float (vector org, vector vel, float delay, float collisiondelay, float theme) quickdelayedparticle
float (string url, float id, string content_type, string delim, float buf, float keyid) crypto_uri_postbuf
float (string s, string separator1,...) tokenizebyseparator
float (float caseinsensitive, string s,...) crc16
float (float skel, entity ent, float modlindex, float retainfrac, float firstbone, float lastbone) skel_build
float (float skel, string tagname) skel_find_bone
float (float skel, float bonenum, string g1, string g2, string g3, string g4, string g5, string g6) example_skel_findbonegroup
float (float fieldnum, entity ent, string s) putentityfieldstring
float loadfont (string fontname, string fontmaps, string sizes, float slot, float fix_scale, float fix_voffset)
float log (float f)
string (float f) ftos = #112
string (vector v) vtos
string (entity ent) etos
string (string s) precache_file = #75
string (...) strcat
string (string s, float start, float length) substring
string (float c,...) chr2str
string (float ccase, float calpha, float cnum, string s,...) strconv
string (float chars, string s,...) strpad = #478
string (string info, string key, string value,...) infoadd
string (string info, string key) infoget
string (string name,...) precache_pic = #627
string (float playernum, string keyname) getplayerkeyvalue = #465
string () ReadString
string (entity e, float s) getsurfacetexture
string (float handle, float num) search_getfilename = #466
string (string search, string replace, string subject) strreplace = #485
string (string command, float bindmap) findkeysforcommand = #625
string (string digest, string data,...) digest_hex = #115
string (float fieldnum, entity ent) getentityfieldstring
float stringwidth_builtin (string text, float allowColorCodes, vector size)
float stringwidth_menu (string text, float allowColorCodes, vector size)
vector (vector v) normalize = #51
vector (vector v, vector w) vectoangles2
vector () randomvec = #344
vector (vector org, float lpflags) getlight2
vector (string) stov = #318
vector (float property) getpropertyvec
vector (vector position, string text, vector scale, vector rgb, float alpha, float flag) drawcolorcodedstring2_builtin
vector (entity e, float s, float n) getsurfacepoint = #629
vector (entity e, float s) getsurfacenormal = #452
vector (entity e, float s, vector p) getsurfaceclippedpoint
vector (entity e, float s, float n, float a) getsurfacepointattribute
vector (float entitynum, float fldnum) getentityvec = #269
void () CSQC_Init
void (float w, float h) CSQC_UpdateView
void (vector ang) makevectors
void (entity e, vector o) setorigin
void (entity e, string m) setmodel
void (entity e, vector min, vector max) setsize
void (entity e, float chan, string samp) sound
void (string e) error
void (entity e) remove
void (string s,...) dprint
void (float style, string value) lightstyle
void (vector o, vector d, float color, float count) particle
void (entity e, entity ignore) tracetoss
void (string var, string val) cvar_set
void (vector pos, string samp, float vol, float atten) ambientsound
void (vector v1, vector min, vector max, vector v2, float nomonsters, entity forent) tracebox
void (float fhandle) fclose
void (vector org, float radius, vector lightcolours) adddynamiclight
void (vector org, float radius, vector lightcolours, float style, string cubemapname, float pflags) adddynamiclight2
void (string texturename, float flag,...) R_BeginPolygon
void (vector org, vector texcoords, vector rgb, float alpha) R_PolygonVertex
void (float width, vector pos1, vector pos2, float flag) drawline
void (float x, float y, float width, float height) drawsetcliparea_builtin
void (entity e, float mdlindex) setmodelindex
void (entity ent, float effectnum, vector start, vector end) trailparticles
void (...) runstandardplayerphysics
void (vector origin, vector forward, vector right, vector up) SetListener
void (vector org, string modelname, float startframe, float endframe, float framerate) effect
void (vector org, vector velocity, float howmany) te_blood
void (vector org, vector color) te_explosionrgb
void (vector mincorner, vector maxcorner, vector vel, float howmany, float color, float gravityflag, float randomveljitter) te_particlecube
void (vector mincorner, vector maxcorner, vector vel, float howmany, float color) te_particlerain
void (vector org, float radius, float lifetime, vector color) te_customflash
void (vector org, float colorstart, float colorlength) te_explosion2
void (entity e, entity tagentity, string tagname) setattachment
void (float bufhandle, float sortpower, float backward) buf_sort
void (float bufhandle, float string_index, string str) bufstr_set
void (entity e, float chan, string samp, float vol, float atten, float speed, float flags) sound7
void (float skel, float bonenum, vector org) skel_set_bone
void (float skel, float startbone, float endbone, vector org) skel_mul_bones
void (float animmodelindex, float framegroup, float framegroupstarttime, float blendalpha, string groupbonename, string excludegroupname1, string excludegroupname2) example_skel_player_update_applyoverride
void (vector eyetarget, string bonename) example_skel_player_update_eyetarget
void (float fh, entity e) writetofile
void (float effectindex, entity own, vector org_from, vector org_to, vector dir_from, vector dir_to, float countmultiplier, float flags) boxparticles
Variables
vector absmax
vector absmin
vector angles
const float ATTN_IDLE = 2
const float ATTN_NONE = 0
const float ATTN_NORM = 1
const float ATTN_STATIC = 3
vector avelocity
entity chain
const float CHAN_AUTO = 0
const float CHAN_BODY = 4
const float CHAN_ITEM = 3
const float CHAN_VOICE = 2
const float CHAN_WEAPON = 1
string classname
float clientcommandframe
float colormap
const float CONTENT_EMPTY = -1
const float CONTENT_LAVA = -5
const float CONTENT_SKY = -6
const float CONTENT_SLIME = -4
const float CONTENT_SOLID = -2
const float CONTENT_WATER = -3
float CVAR_TYPEFLAG_ENGINE = 8
float CVAR_TYPEFLAG_EXISTS = 1
float CVAR_TYPEFLAG_HASDESCRIPTION = 16
float CVAR_TYPEFLAG_PRIVATE = 4
float CVAR_TYPEFLAG_READONLY = 32
float CVAR_TYPEFLAG_SAVED = 2
float DEG2RAD = 0.0174532925199432957692369076848861271344287188854172545609719144
float DPCONTENTS_BODY = 32
float DPCONTENTS_BOTCLIP = 2048
float DPCONTENTS_CORPSE = 64
float DPCONTENTS_DONOTENTER = 1024
float DPCONTENTS_LAVA = 8
float DPCONTENTS_LIQUIDSMASK = 14
float DPCONTENTS_MONSTERCLIP = 512
float DPCONTENTS_NODROP = 128
float DPCONTENTS_OPAQUE = 4096
float DPCONTENTS_PLAYERCLIP = 256
float DPCONTENTS_SKY = 16
float DPCONTENTS_SLIME = 4
float DPCONTENTS_SOLID = 1
float DPCONTENTS_WATER = 2
float dphitcontentsmask
const float DRAWFLAG_2XMODULATE = 3
const float DRAWFLAG_ADDITIVE = 1
const float DRAWFLAG_MIPMAP = 0x100
const float DRAWFLAG_MODULATE = 2
const float DRAWFLAG_NORMAL = 0
const float DRAWFLAG_SCREEN = 4
float drawfont
float drawmask
float E_ABSMAX = 15
float E_ABSMIN = 14
float E_ACTIVE = 0
float E_ALPHA = 7
float E_COLORMOD = 8
float E_FORWARD = 2
float E_LIGHT = 16
float E_MAXS = 13
float E_MINS = 12
float E_ORIGIN = 1
float E_ORIGINANDVECTORS = 6
float E_PANTSCOLOR = 9
float E_RIGHT = 3
float E_SCALE = 5
float E_SHIRTCOLOR = 10
float E_SKIN = 11
float E_UP = 4
const float EF_ADDITIVE = 32
const float EF_BLUE = 64
const float EF_FLAME = 1024
const float EF_FULLBRIGHT = 512
const float EF_NODEPTHTEST = 8192
const float EF_NODRAW = 16
const float EF_NOSHADOW = 4096
const float EF_RED = 128
const float EF_SELECTABLE = 16384
const float EF_STARDUST = 2048
float effects
void end_sys_fields
void end_sys_globals
entity enemy
float entnum
const float EXTRA_HIGH = 99999999
const float EXTRA_LOW = -99999999
const float false = 0
const float FALSE = 0
float FIELD_ENTITY = 4
float FIELD_FLOAT = 2
float FIELD_FUNCTION = 6
float FIELD_STRING = 1
float FIELD_VECTOR = 3
const float FILE_APPEND = 1
const float FILE_READ = 0
const float FILE_WRITE = 2
float flags
float FONT_CENTERPRINT = 5
float FONT_CHAT = 4
float FONT_CONSOLE = 1
float FONT_DEFAULT = 0
float FONT_INFOBAR = 6
float FONT_MENU = 7
float FONT_NOTIFY = 3
float FONT_SBAR = 2
float FONT_USER0 = 8
float FONT_USER1 = 9
float FONT_USER2 = 10
float FONT_USER3 = 11
float FONT_USER4 = 12
float FONT_USER5 = 13
float FONT_USER6 = 14
float FONT_USER7 = 15
float frame
float frame1time
float frame2
float frame2time
float frame3
float frame3time
float frame4
float frame4time
float frametime
vector getlight_ambient
vector getlight_diffuse
vector getlight_dir
vector gettaginfo_forward
string gettaginfo_name
vector gettaginfo_offset
float gettaginfo_parent
vector gettaginfo_right
vector gettaginfo_up
float GETTIME_CDTRACK = 4
float GETTIME_FRAMESTART = 0
float GETTIME_HIRES = 2
float GETTIME_REALTIME = 1
float GETTIME_UPTIME = 3
vector input_angles
float input_buttons
vector input_movevalues
float input_timelength
float intermission
float lerpfrac
float lerpfrac3
float lerpfrac4
const float LP_COMPLETE = 7
const float LP_DYNLIGHT = 4
const float LP_LIGHTMAP = 1
const float LP_RTWORLD = 2
const float M_PI = 3.14159265358979323846
string mapname
const float MASK_ENGINE = 1
const float MASK_ENGINEVIEWMODELS = 2
const float MASK_NORMAL = 4
float maxclients
vector maxs
vector mins
string model
float modelindex
vector modellight_ambient
vector modellight_diffuse
vector modellight_dir
const float MOVE_MISSILE = 2
const float MOVE_NOMONSTERS = 1
const float MOVE_NORMAL = 0
float MOVE_WORLDONLY = 3
float movetype
float movevar_accelerate
float movevar_airaccelerate
float movevar_entgravity
float movevar_friction
float movevar_gravity
float movevar_maxspeed
float movevar_spectatormaxspeed
float movevar_stopspeed
float movevar_wateraccelerate
float movevar_waterfriction
string netname
float nextthink
vector oldorigin
vector origin
entity other
entity owner
float particle_airfriction
float particle_alpha
float particle_alphafade
float particle_angle
float PARTICLE_BEAM = 3
float PARTICLE_BILLBOARD = 0
float particle_blendmode
float particle_bounce
vector particle_color1
vector particle_color2
float particle_delaycollision
float particle_delayspawn
float particle_gravity
float particle_liquidfriction
float particle_orientation
float PARTICLE_ORIENTED_DOUBLESIDED = 2
float particle_originjitter
float particle_qualityreduction
float particle_size
float particle_sizeincrease
float PARTICLE_SPARK = 1
float particle_spin
float particle_stainalpha
vector particle_staincolor1
vector particle_staincolor2
float particle_stainsize
float particle_staintex
float particle_stretch
float particle_tex
float particle_time
float particle_type
float particle_velocityjitter
float particles_alphamax
float particles_alphamin
vector particles_colormax
vector particles_colormin
float PARTICLES_DRAWASTRAIL = 128
float particles_fade
float PARTICLES_USEALPHA = 1
float PARTICLES_USECOLOR = 2
float PARTICLES_USEFADE = 4
float PBLEND_ADD = 1
float PBLEND_ALPHA = 0
float PBLEND_INVMOD = 2
const float PFL_CROUCH = 2
const float PFL_DEAD = 4
const float PFL_GIBBED = 8
const float PFL_ONGROUND = 1
const float PFLAGS_CORONA = 2
const float PFLAGS_FULLDYNAMIC = 128
const float PFLAGS_NOSHADOW = 1
float PI = 3.1415926535897932384626433832795028841971693993751058209749445923
float player_localentnum
float player_localnum
float PMF_DUCKED = 4
float PMF_ONGROUND = 8
vector pmove_maxs
vector pmove_mins
vector pmove_org
vector pmove_vel
float PRECACHE_PIC_FROMWAD = 1
float PRECACHE_PIC_MIPMAP = 8
float PRECACHE_PIC_NOTPERSISTENT = 2
float PT_ALPHASTATIC = 1
float PT_BEAM = 4
float PT_BLOOD = 9
float PT_BUBBLE = 8
float PT_DECAL = 11
float PT_ENTITYPARTICLE = 12
float PT_RAIN = 5
float PT_RAINDECAL = 6
float PT_SMOKE = 10
float PT_SNOW = 7
float PT_SPARK = 3
float PT_STATIC = 2
float Q3SURFACEFLAG_FLESH = 64
float Q3SURFACEFLAG_LADDER = 8
float Q3SURFACEFLAG_METALSTEPS = 4096
float Q3SURFACEFLAG_NODAMAGE = 1
float Q3SURFACEFLAG_NODRAW = 128
float Q3SURFACEFLAG_NOIMPACT = 16
float Q3SURFACEFLAG_NOMARKS = 32
float Q3SURFACEFLAG_NONSOLID = 16384
float Q3SURFACEFLAG_NOSTEPS = 8192
float Q3SURFACEFLAG_SKY = 4
float Q3SURFACEFLAG_SLICK = 2
float RAD2DEG = 57.2957795130823208767981548141051703324054724665643215491602438612
float REFDEFFLAG_DEAD = 4
float REFDEFFLAG_INTERMISSION = 8
float REFDEFFLAG_JUMPING = 2
float REFDEFFLAG_TELEPORTED = 1
const float RF_ADDITIVE = 8
const float RF_DEPTHHACK = 4
float RF_DYNAMICMODELLIGHT = 8192
const float RF_EXTERNALMODEL = 2
const float RF_FULLBRIGHT = 256
const float RF_MODELLIGHT = 4096
const float RF_NOSHADOW = 512
const float RF_USEAXIS = 16
const float RF_VIEWMODEL = 1
const float RF_WORLDOBJECT = 128
entity self
float servercommandframe
vector size
float skeletonindex
float skin
float solid
const float SOLID_BBOX = 2
const float SOLID_BSP = 4
const float SOLID_CORPSE = 5
const float SOLID_NOT = 0
const float SOLID_SLIDEBOX = 3
const float SOLID_TRIGGER = 1
float SOUNDFLAG_RELIABLE = 1
const float STAT_ACTIVEWEAPON = 10
const float STAT_AMMO = 3
const float STAT_ARMOR = 4
const float STAT_CELLS = 9
const float STAT_FRAGLIMIT = 235
const float STAT_HEALTH = 0
const float STAT_ITEMS = 15
const float STAT_MONSTERS = 14
const float STAT_MOVEVARS_GRAVITY = 242
const float STAT_MOVEVARS_TICRATE = 240
const float STAT_MOVEVARS_TIMESCALE = 241
const float STAT_NAILS = 7
const float STAT_ROCKETS = 8
const float STAT_SECRETS = 13
const float STAT_SHELLS = 6
const float STAT_TIMELIMIT = 236
const float STAT_TOTALMONSTERS = 12
const float STAT_TOTALSECRETS = 11
const float STAT_VIEWHEIGHT = 16
const float STAT_WEAPONFRAME = 5
const float STAT_WEAPONMODEL = 2
const float TE_EXPLOSION = 3
const float TE_EXPLOSION2 = 12
const float TE_EXPLOSIONQUAD = 70
const float TE_EXPLOSIONRGB = 53
const float TE_GUNSHOT = 2
const float TE_GUNSHOTQUAD = 57
const float TE_KNIGHTSPIKE = 8
const float TE_LAVASPLASH = 10
const float TE_LIGHTNING1 = 5
const float TE_LIGHTNING2 = 6
const float TE_LIGHTNING3 = 9
const float TE_SPIKE = 0
const float TE_SPIKEQUAD = 58
const float TE_SUPERSPIKE = 1
const float TE_SUPERSPIKEQUAD = 59
const float TE_TAREXPLOSION = 4
const float TE_TELEPORT = 11
const float TE_WIZSPIKE = 7
float time
float trace_allsolid
float trace_dphitcontents
float trace_dphitq3surfaceflags
string trace_dphittexturename
float trace_dpstartcontents
vector trace_endpos
entity trace_ent
float trace_fraction
float trace_inopen
float trace_inwater
float trace_networkentity
float trace_plane_dist
vector trace_plane_normal
float trace_startsolid
float transparent_offset
const float true = 1
const float TRUE = 1
vector v_forward
vector v_right
vector v_up
const vector VEC_0 = '0 0 0'
const vector VEC_1 = '1 1 1'
vector VEC_HULL_MAX = '16 16 32'
vector VEC_HULL_MIN = '-16 -16 -24'
const vector VEC_M1 = '-1 -1 -1'
vector velocity
const float VF_ANGLES = 15
const float VF_ANGLES_X = 16
const float VF_ANGLES_Y = 17
const float VF_ANGLES_Z = 18
const float VF_CL_VIEWANGLES = 33
const float VF_CL_VIEWANGLES_X = 34
const float VF_CL_VIEWANGLES_Y = 35
const float VF_CL_VIEWANGLES_Z = 36
const float VF_DRAWCROSSHAIR = 21
const float VF_DRAWENGINESBAR = 20
const float VF_DRAWWORLD = 19
const float VF_FOV = 8
const float VF_FOVX = 9
const float VF_FOVY = 10
const float VF_MAINVIEW = 400
const float VF_MIN = 1
const float VF_MIN_X = 2
const float VF_MIN_Y = 3
const float VF_MINFPS_QUALITY = 401
const float VF_ORIGIN = 11
const float VF_ORIGIN_X = 12
const float VF_ORIGIN_Y = 13
const float VF_ORIGIN_Z = 14
const float VF_PERSPECTIVE = 200
const float VF_SIZE = 4
const float VF_SIZE_X = 6
const float VF_SIZE_Y = 5
const float VF_VIEWPORT = 7
vector view_angles
vector view_punchangle
vector view_punchvector
entity world
Macro Definition Documentation
#define SPA_LIGHTMAP0_TEXCOORDS 5
Definition at line 945 of file csprogsdefs.qc.
#define SPA_LIGHTMAP_COLOR 6
Definition at line 946 of file csprogsdefs.qc.
#define SPA_POSITION 0
Definition at line 940 of file csprogsdefs.qc.
#define SPA_R_AXIS 3
Definition at line 943 of file csprogsdefs.qc.
#define SPA_S_AXIS 1
Definition at line 941 of file csprogsdefs.qc.
#define SPA_T_AXIS 2
Definition at line 942 of file csprogsdefs.qc.
#define SPA_TEXCOORDS0 4
Definition at line 944 of file csprogsdefs.qc.
Function Documentation
float checkpvs (vector viewpos, entity viewee)
Referenced by havocbot_bunnyhop(), havocbot_goalrating_ons_controlpoints_attack(), havocbot_goalrating_ons_generator_attack(), havocbot_movetogoal(), havocbot_role_ctf_defense(), Monster_ValidTarget(), MoveToRandomLocationWithinBounds(), MUTATOR_HOOKFUNCTION(), navigation_shortenpath(), WarpZone_Fade_PreDraw(), and waypoint_think().
void coverage ()
vector drawgetimagesize (string pic)
Referenced by draw_PictureSize(), MapVote_DrawMapItem(), and turret_draw2d().
float drawsubpic (vector position, vector size, string pic, vector srcPosition, vector srcSize, vector rgb, float alpha, float flag)
Referenced by draw_BorderPicture(), draw_ButtonPicture(), draw_VertButtonPicture(), drawpic_tiled(), HUD_Panel_DrawHighlight(), and HUD_Panel_DrawProgressBar().
entity () = #17
Referenced by __spawn(), __spawnfunc_spawn(), _GetPlayerSoundSampleField(), _Movetype_Physics_Follow(), _Movetype_Physics_Walk(), _Movetype_TestEntityPosition(), accuracy_add(), accuracy_init(), accuracy_send(), AnimHost::addAnim(), Keyframe::addAnim(), Keyframe::addEasing(), addPowerupItem(), AuditLists(), AuxiliaryXhair_customize(), Ban_LoadBans(), BanCommand_kickban(), BanCommand_mute(), BanCommand_unmute(), bd_check_winner(), bd_close_editor(), bd_do_fill(), bd_editor_place(), bd_find_controller(), bd_find_dozer(), bd_find_piece(), bd_load_piece(), bd_move(), bd_move_dozer(), bd_reset_moves(), bd_save_level(), bd_setup_pieces(), bd_unfill_recurse(), bot_cmd_aimtarget(), bot_cmd_movetotarget(), bot_command_executed(), bot_endgame(), bot_getplace(), bot_relinkplayerlist(), bot_remove_from_bot_list(), bot_removefromlargestteam(), bot_removenewest(), bot_spawn(), botframe_autowaypoints_fix_from(), botframe_showwaypointlinks(), botframe_updatedangerousobjects(), buff_Customize(), buff_Init(), buff_NewType(), buff_Respawn(), buff_Think(), buff_Touch(), buff_Waypoint_Spawn(), buffs_BuffModel_Customize(), buffs_DelayedInit(), c4_find_piece(), c4_move(), c4_winning_piece(), CA_count_alive_players(), ca_LastPlayerForTeam(), ca_LastPlayerForTeam_Notify(), CA_SpectateNext(), CallbackChain::CallbackChain_Add(), CheatCommand(), CheatImpulse(), CheckCategoryOverride(), CL_ExteriorWeaponentity_Think(), CL_SpawnWeaponentity(), CL_Weapon_GetShotOrg(), ClientCommand_minigame(), ClientCommand_selectteam(), ClientCommand_spectate(), ClientCommand_tell(), ClientCommand_voice(), ClientConnect(), ClientData_Send(), ClientData_Touch(), ClientInit_Spawn(), Cmd_MapVote_MapDownload(), CommonCommand_editmob(), Container_addItem(), Container_draw(), Container_hideNotify(), Container_itemFromPoint(), Container_keyDown(), Container_keyUp(), Container_mouseDrag(), Container_mouseMove(), Container_mouseRelease(), Container_moveItemAfter(), Container_preferredFocusedGrandChild(), Container_removeItem(), Container_resizeNotifyLie(), Container_showNotify(), CopyBody(), Create_Effect_Entity(), CSQC_UpdateView(), CSQCModel_Draw(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_SetCamera(), CSQCVehicleSetup(), ctf_CaptureShield_Spawn(), ctf_CheckStalemate(), ctf_DelayedFlagSetup(), ctf_DelayedInit(), ctf_FlagBase_Customize(), ctf_FlagcarrierWaypoints(), ctf_FlagThink(), ctf_Handle_Capture(), ctf_Handle_Drop(), ctf_Handle_Retrieve(), ctf_Handle_Throw(), ctf_RemovePlayer(), ctf_SpawnTeam(), ctf_Stalemate_Customize(), Damage(), deactivate_minigame(), Deathtype_Name(), debuggoalstack(), depthfirst(), Dialog_configureDialog(), dialog_hudpanel_main_checkbox(), dialog_hudpanel_main_settings(), dom_controlpoint_setup(), dom_DelayedInit(), dom_spawnpoint(), dom_spawnteam(), Domination_count_controlpoints(), dompoint_captured(), dompointtouch(), door_check_keys(), door_fire(), door_spawnfield(), Drag(), Drag_Finish(), Drag_Update(), draw_ClearClip(), Draw_ShowNames(), Draw_ShowNames_All(), EFFECT_ROCKETMINSTA_LASER(), EliminatedPlayers_SendEntity(), end_minigame(), EndFrame(), XonoticDamageTextSettings::fill(), XonoticGameSettingsTab::fill(), find_bot_by_number(), FindConnectedComponent(), AnimHost::finishAllAnim(), AnimHost::finishObjAnim(), Fire_ApplyDamage(), fireBullet(), FireGrapplingHook(), FireRailgunBullet(), formatmessage(), Freeze(), freezetag_count_alive_players(), freezetag_LastPlayerForTeam(), freezetag_LastPlayerForTeam_Notify(), GameCommand_adminmsg(), GameCommand_animbench(), GameCommand_anticheat(), GameCommand_bot_cmd(), GameCommand_defer_clear(), GameCommand_gettaginfo(), GameCommand_make_mapinfo(), GameCommand_moveplayer(), GameCommand_shuffleteams(), GameCommand_stuffto(), GameCommand_trace(), GameType_ConfigureSliders(), GameTypeVote_DrawGameTypeItem(), GetCurrentFov(), SettingSource::getEntry(), SettingSource::getEntryTooltip(), GetFilteredEntity(), GetFilteredNumber(), GetIndexedEntity(), GetPlayerScoreString(), GetTeam(), GetTeamScoreString(), GrapplingHookThink(), havocbot_ai(), havocbot_chooseenemy(), havocbot_ctf_calculate_middlepoint(), havocbot_ctf_find_enemy_flag(), havocbot_ctf_find_flag(), havocbot_ctf_is_basewaypoint(), havocbot_ctf_reset_role(), havocbot_dodge(), havocbot_gettarget(), havocbot_goalrating_ast_targets(), havocbot_goalrating_ball(), havocbot_goalrating_ctf_droppedflags(), havocbot_goalrating_ctf_enemybase(), havocbot_goalrating_ctf_enemyflag(), havocbot_goalrating_ctf_ourbase(), havocbot_goalrating_ctf_ourstolenflag(), havocbot_goalrating_ft_freeplayers(), havocbot_goalrating_kh(), havocbot_goalrating_ons_controlpoints_attack(), havocbot_goalrating_ons_generator_attack(), havocbot_moveto(), havocbot_moveto_refresh_route(), havocbot_movetogoal(), havocbot_role_ctf_carrier(), havocbot_role_ctf_defense(), havocbot_role_ctf_escort(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), havocbot_select_an_item_of_group(), HitSound(), HUD_Ammo(), HUD_Crosshair(), Hud_Dynamic_Frame(), HUD_InfoMessages(), HUD_MinigameBoard(), HUD_MinigameMenu(), HUD_MinigameMenu_Click_ExpandCollapse(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameMenu_CustomEntry(), HUD_MinigameMenu_MouseInput(), HUD_MinigameMenu_SpawnEntry(), HUD_MinigameMenu_SpawnSubEntry(), HUD_MinigameStatus(), HUD_Mod_Race(), HUD_Panel_InputEvent(), HUD_Powerups(), HUD_Quickmenu_PlayerListEntries(), HUD_Score(), HUD_Score_Rankings(), HUD_Weapons(), IL_ENDFRAME(), IL_POP(), IL_PUSH(), IL_REMOVE(), IL_SHIFT(), IL_UNSHIFT(), IMPULSE(), ImpulseCommands(), info_autoscreenshot_findtarget(), InitializeEntitiesRun(), InitializeEntity(), InputContainer__changeFocusXY(), InputContainer_keyDown(), invasion_SpawnChosenMonster(), Item_Create(), Item_CreateLoot(), Item_IsAllowed(), join_minigame(), jumppad_push(), ka_DropEvent(), ka_RemoveBall(), ka_RespawnBall(), ka_SpawnBall(), kh_FinishRound(), kh_HandleFrags(), kh_Key_AllOwnedByWhichTeam(), kh_Key_AssignTo(), kh_Key_Attach(), kh_Key_Detach(), kh_Key_DropAll(), kh_Key_DropOne(), kh_Key_Remove(), kh_Key_Spawn(), kh_Key_Think(), kh_LoserTeam(), kh_StartRound(), kh_update_state(), kh_WinnerTeam(), LinkDoors(), Local_Notification(), LocalCommand_boxparticles(), LocalCommand_debugmodel(), m_activate_window(), m_findtooltipitem(), m_goto(), m_keydown(), m_setpointerfocus(), m_tooltip(), MainWindow_configureMainWindow(), make_safe_for_remove(), makeEasing(), makeHostedEasing(), makeHostedKeyframe(), makeKeyframe(), makeTeamButton_T(), makeXonoticAudioSettingsTab(), makeXonoticBigButton(), makeXonoticBigCommandButton_T(), makeXonoticButton_T(), makeXonoticCampaignList(), makeXonoticCharmap(), makeXonoticCheckBoxEx_T(), makeXonoticCheckBoxString(), makeXonoticColorButton(), makeXonoticColorpicker(), makeXonoticColorpickerString(), makeXonoticCommandButton_T(), makeXonoticCreditsList(), makeXonoticCrosshairPicker(), makeXonoticCrosshairPreview(), makeXonoticCvarList(), makeXonoticDecibelsSlider_T(), makeXonoticDemoBrowserTab(), makeXonoticDemoList(), makeXonoticEffectsSettingsTab(), makeXonoticGameCrosshairSettingsTab(), makeXonoticGameHUDSettingsTab(), makeXonoticGameMessageSettingsTab(), makeXonoticGameModelSettingsTab(), makeXonoticGametypeList(), makeXonoticGameViewSettingsTab(), makeXonoticGameWeaponsSettingsTab(), makeXonoticHeaderLabel(), makeXonoticHUDSkinList(), makeXonoticImage(), makeXonoticInputBox_T(), makeXonoticInputSettingsTab(), makeXonoticKeyBinder(), makeXonoticLanguageList(), makeXonoticListBox(), makeXonoticMapList(), makeXonoticMediaTab(), makeXonoticMiscSettingsTab(), makeXonoticMusicPlayerTab(), makeXonoticNexposee(), makeXonoticParticlesSlider(), makeXonoticPicker(), makeXonoticPicmipSlider(), makeXonoticPlayerList(), makeXonoticPlayerModelSelector(), makeXonoticPlayList(), makeXonoticProfileTab(), makeXonoticRadioButton_T(), makeXonoticResolutionSlider(), makeXonoticScoreboardFadeTimeSlider(), makeXonoticScreenshotBrowserTab(), makeXonoticScreenshotImage(), makeXonoticScreenshotList(), makeXonoticServerCreateTab(), makeXonoticServerList(), makeXonoticServerListTab(), makeXonoticSkinList(), makeXonoticSlider_T(), makeXonoticSliderCheckBox(), makeXonoticSoundList(), makeXonoticStatsList(), makeXonoticTabController(), makeXonoticTextLabel(), makeXonoticTextSlider_T(), makeXonoticUserSettingsTab(), makeXonoticVideoSettingsTab(), makeXonoticWeaponarenaCheckBox(), makeXonoticWeaponsList(), MapVote_CheckPK3(), minigame_addplayer(), minigame_CheckSend(), minigame_count_players(), minigame_find_player(), minigame_resend(), minigame_rmplayer(), minigame_SendEntity(), MinigameImpulse(), ModalController_draw(), ModalController_hideAll(), Monster_Delay(), monster_dropitem(), Monster_FindTarget(), Monster_Move(), Monster_Spawn(), Monster_Spawn_Setup(), Container::mousePress(), MoveToLast(), MoveToRandomLocationWithinBounds(), msle_spawn(), MUTATOR_HOOKFUNCTION(), MX_Nick(), MX_Say(), MX_Typing(), Nagger_SendEntity(), navigation_findnearestwaypoint(), navigation_get_really_close_waypoint(), navigation_goalrating_start(), navigation_markroutes(), navigation_markroutes_inverted(), navigation_poptouchedgoals(), navigation_routerating(), navigation_routetogoal(), navigation_shortenpath(), NearestLocation(), NET_HANDLE(), Nexposee_calc(), Nexposee_Calc_Scale(), Nexposee_draw(), Nexposee_mouseMove(), NIX_CanChooseWeapon(), NIX_GiveCurrentWeapon(), nmm_find_tile(), nmm_in_mill_string(), nmm_kill_tiles(), nmm_spawn_tile(), nmm_tile_canmove(), Obituary_SpecialDeath(), ok_DropItem(), ons_CaptureShield_Customize(), ons_CaptureShield_Spawn(), ons_ControlPoint_Icon_Spawn(), ons_ControlPoint_UpdateSprite(), ons_Count_SelfControlPoints(), ons_generator_ray_spawn(), ons_Generator_UpdateSprite(), ons_MonsterSpawn_Delayed(), ons_Nearest_ControlPoint(), ons_Nearest_ControlPoint_2D(), ons_ScoreRules(), ons_TurretSpawn_Delayed(), Onslaught_CheckWinner(), Onslaught_count_generators(), Onslaught_RoundStart(), onslaught_updatelinks(), part_minigame(), path_build(), pathlib_astar(), pathlib_expandnode_starf(), pathlib_getbestopen(), pathlib_makenode_adaptive(), pathlib_mknode(), pathlib_nodeatpoint(), pathlib_walknode(), pathlib_waypointpath_autostep(), pathlib_waypointpath_step(), pathlib_wpp_bestopen(), PingPLReport_Think(), plat_outside_touch(), plat_spawn_inside_trigger(), Player_SetTeamIndexChecked(), Playerchecker_Think(), PlayerScore_Add(), PlayerScore_Attach(), PlayerScore_Clear(), PlayerScore_PlayerStats(), PlayerScore_Set(), PlayerScore_Sort(), PlayerScore_TeamStats(), PlayerTeamScore_Compare(), PlayerTouchExplode(), PlayerUseKey(), PM_check_hitground(), PM_ClientMovement_UpdateStatus(), PM_Footsteps(), Portal_Remove(), Portal_Spawn(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_Think(), Porto_Draw(), PostInit(), pp_find_piece(), pp_move(), pp_next_match(), pp_setup_pieces(), pp_valid_move(), ps_draw(), ps_find_piece(), ps_move(), ps_move_piece(), ps_setup_pieces(), ps_winning_piece(), PutObserverInServer(), PutPlayerInServer(), race_GetFractionalLapCount(), race_waypointsprite_visible_for_player(), RadioButton_Click(), RadiusDamageForSource(), RandomItems_ReplaceMapItem(), RandomItems_SpawnLootItem(), ReadyRestart_force(), RegisterPlayer(), RegisterSLCategories(), RegisterTeam(), Item::relinquishFocus(), relocate_spawnpoint(), AnimHost::removeAllAnim(), AnimHost::removeAnim(), RemoveHook(), AnimHost::removeObjAnim(), RemovePlayer(), RemoveTeam(), replace_with_insta_cells(), resetPowerupItems(), AnimHost::resumeAllAnim(), AnimHost::resumeObjAnim(), round_handler_Init(), round_handler_Reset(), round_handler_Spawn(), sandbox_Database_Load(), sandbox_ObjectPort_Load(), sandbox_ObjectSpawn(), Score_ClearAll(), Score_NicePrint(), Score_NicePrint_Player(), Score_NicePrint_Team(), Scoreboard_Draw(), Scoreboard_MakeTable(), Scoreboard_UpdatePlayerPos(), Scoreboard_UpdatePlayerTeams(), Scoreboard_UpdateTeamPos(), ScoreRules_generic(), SelectSpawnPoint(), ServerList_Update_favoriteButton(), SetSpectatee(), SetTeam(), Simple_TeleportPlayer(), Sort_Spawn(), Spawn_FilterOutBadSpots(), Spawn_Score(), Spawn_ScoreAll(), Spawn_WeightedPoint(), spawnfunc(), SpecialCommand(), Spectate(), SpectateNext(), SpectatePrev(), start_minigame(), STATIC_INIT(), STATIC_INIT_EARLY(), steerlib_flock(), steerlib_flock2d(), steerlib_swarm(), AnimHost::stopAllAnim(), AnimHost::stopObjAnim(), SUB_CalcMove_Bezier(), SUB_CalcMove_controller_think(), SUB_UseTargets_Ex(), SV_ParseClientCommand_floodcheck(), sys_phys_simulate_simple(), target_init_verify(), target_objective_decrease_activate(), tdm_SpawnTeam(), TeamBalance_AutoBalanceBots(), TeamBalance_CheckAllowedTeams(), TeamBalance_CompareTeams(), TeamBalance_GetLargestTeamIndex(), TeamBalance_GetPlayerForTeamSwitch(), TeamBalance_GetTeamCounts(), TeamBalance_JoinBestTeam(), TeamScore_AddToTeam(), TeamScore_GetCompareValue(), TeamScore_Spawn(), teleport_findtarget(), Teleport_Touch(), TeleportPlayer(), TEST(), AnimHost::tickAll(), XonoticGameSettingsTab::topicChangeNotify(), train_next(), train_next_find(), train_wait(), trigger_impulse_touch_directional(), trigger_keylock_kill(), trigger_keylock_touch(), trigger_keylock_trigger(), trigger_push_test(), trigger_race_checkpoint_verify(), TrueAimCheck(), ttt_find_piece(), ttt_move(), ttt_next_match(), turret_construct(), turret_die(), turret_gibtoss(), UpdateAuxiliaryXhair(), url_multi_fopen(), url_single_fopen(), url_URI_Get_Callback(), vehicle_impulse(), vehicle_tossgib(), vehicles_enter(), vehicles_exit(), vehicles_projectile(), vehicles_setreturn(), vehicles_showwp(), viewmodel_animate(), viewmodel_draw(), VoteCommand_parse(), W_AttachToShotorg(), w_clear(), W_DecreaseAmmo(), W_GetCycleWeapon(), W_HitPlotAnalysis(), W_NameWeaponOrder_MapFunc(), W_Nexball_Attack(), W_Nexball_Attack2(), W_Nexball_Touch(), W_PlayStrengthSound(), w_ready(), W_Reload(), W_ReloadedAndReady(), W_SetupShot_Dir_ProjectileSize_Range(), W_SwitchWeapon(), W_ThrowNewWeapon(), W_WeaponFrame(), WarpZone_FindRadius(), WarpZone_FindRadius_Recurse(), WarpZone_FixNearClip(), WarpZone_FixPMove(), WarpZone_FixView(), WarpZone_PostInitialize_Callback(), WarpZone_Projectile_Touch(), WarpZone_RefSys_SpawnSameRefSys(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_BoxTouchesBrush_Recurse(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_remove_fromeditor(), waypoint_save_links(), waypoint_spawn_fromeditor(), waypoint_spawnforteleporter_boxes(), waypoint_spawnpersonal(), waypoint_unreachable(), weapon_defaultspawnfunc(), weapon_prepareattack_check(), weapon_prepareattack_do(), weapon_thinkf(), Weapon_whereis(), weaponorder_swap(), WinningCondition_Assault(), WinningCondition_LMS(), WinningConditionHelper(), XonoticAudioSettingsTab_fill(), XonoticCreditsDialog_fill(), XonoticCvarsDialog_fill(), XonoticDemoBrowserTab_fill(), XonoticDemoStartConfirmDialog_fill(), XonoticDemoTimeConfirmDialog_fill(), XonoticEffectsSettingsTab_fill(), XonoticFirstRunDialog_fill(), XonoticGameCrosshairSettingsTab_fill(), XonoticGameHUDSettingsTab_fill(), XonoticGameMessageSettingsTab_fill(), XonoticGameModelSettingsTab_fill(), XonoticGametypeList_saveCvars(), XonoticGameViewSettingsTab_fill(), XonoticGameWeaponsSettingsTab_fill(), XonoticHUDAmmoDialog_fill(), XonoticHUDCenterprintDialog_fill(), XonoticHUDChatDialog_fill(), XonoticHUDConfirmDialog_fill(), XonoticHUDEngineInfoDialog_fill(), XonoticHUDExitDialog_fill(), XonoticHUDHealthArmorDialog_fill(), XonoticHUDInfoMessagesDialog_fill(), XonoticHUDItemsTimeDialog_fill(), XonoticHUDNotificationDialog_fill(), XonoticHUDPhysicsDialog_fill(), XonoticHUDPowerupsDialog_fill(), XonoticHUDPressedKeysDialog_fill(), XonoticHUDQuickMenuDialog_fill(), XonoticHUDRadarDialog_fill(), XonoticHUDScoreDialog_fill(), XonoticHUDTimerDialog_fill(), XonoticHUDVoteDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticInputSettingsTab_fill(), XonoticLanguageWarningDialog_fill(), XonoticMapInfoDialog_fill(), XonoticMapInfoDialog_loadMapInfo(), XonoticMediaTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMonsterToolsDialog_fill(), XonoticMultiplayerDialog_fill(), XonoticMusicPlayerTab_fill(), XonoticMutatorsDialog_fill(), XonoticProfileTab_fill(), XonoticQuitDialog_fill(), XonoticRadioButton_draw(), XonoticResetDialog_fill(), XonoticSandboxToolsDialog_fill(), XonoticScreenshotBrowserTab_fill(), XonoticScreenshotViewerDialog_fill(), XonoticServerCreateTab_fill(), XonoticServerInfoDialog_fill(), XonoticServerList_drawListBoxItem(), XonoticServerListTab_fill(), XonoticSettingsDialog_fill(), XonoticSingleplayerDialog_fill(), XonoticTabController_makeTabButton_T(), XonoticTeamSelectDialog_fill(), XonoticUid2NameDialog_fill(), XonoticUserbindEditDialog_fill(), XonoticUserSettingsTab_fill(), XonoticVideoSettingsTab_fill(), XonoticWeaponsList_drawListBoxItem(), XonoticWeaponsList_toString(), and XonoticWinnerDialog_fill().
entity (entity start, .string fld, string match)
entity (vector org, float rad)
entity (entity e)
entity (entity start, .float fld, float match) = #449
entity (entity start, .entity fld, entity match)
entity (.string fld, string match)
entity (.float fld, float match) = #450
entity (float num)
float findfont (string s)
float (float f, float t, float n) = #32
float (string s) = #45
float () = #34
float (vector v) = #13
float (vector v1, vector v2, float tryents, entity ignoreentity)
float (float v) = #37
float (entity e)
float (string name, string value) = #228
float (float a, ...) = #95
float (float f, float f)
float (string filename, float mode)
float (string str, string sub, float startpos)
float (vector position, float character, vector scale, vector rgb, float alpha, float flag)
float (vector position, string text, vector scale, vector rgb, float alpha, float flag) = #322
float (vector position, vector size, vector rgb, float alpha, float flag)
float (vector position, string text, vector scale, float alpha, float flag)
float (entity e, float s)
float (entity e, vector p)
float (string pattern, float caseinsensitive, float quiet)
float (entity ent, string tagname)
float (float bufhandle, string str, float order) = #630
float (vector org, vector vel)
float (vector org, vector vel, float theme)
float (vector org, vector vel, float delay, float collisiondelay)
float (vector org, vector vel, float delay, float collisiondelay, float theme)
float (string url, float id, string content_type, string delim, float buf, float keyid)
float (string s, string separator1, ...)
float (float caseinsensitive, string s, ...)
float (float skel, entity ent, float modlindex, float retainfrac, float firstbone, float lastbone)
float (float skel, string tagname)
float (float skel, float bonenum, string g1, string g2, string g3, string g4, string g5, string g6)
float (float fieldnum, entity ent, string s)
float loadfont (string fontname, string fontmaps, string sizes, float slot, float fix_scale, float fix_voffset)
float log (float f)
Referenced by acosh(), asinh(), atanh(), fromDecibelOfSquare(), gsl_ran_gaussian(), lgamma(), log10(), log1p(), log2(), logn(), and toDecibelOfSquare().
string (float f) = #112
string (vector v)
string (entity ent)
string (string s) = #75
string (...)
string (string s, float start, float length)
string (float c, ...)
string (float ccase, float calpha, float cnum, string s, ...)
string (float chars, string s, ...) = #478
string (string info, string key, string value, ...)
string (string info, string key)
string (string name, ...) = #627
string (float playernum, string keyname) = #465
string ()
string (entity e, float s)
string (float handle, float num) = #466
string (string search, string replace, string subject) = #485
string (string command, float bindmap) = #625
string (string digest, string data, ...) = #115
string (float fieldnum, entity ent)
float stringwidth_builtin (string text, float allowColorCodes, vector size)
Referenced by drawcolorcodedstring_expanding(), drawstring_expanding(), and stringwidth().
float stringwidth_menu (string text, float allowColorCodes, vector size)
vector (vector v) = #51
Referenced by _MapInfo_Generate(), _Movetype_CheckWater(), _Movetype_FlyMove(), _Movetype_LinkEdict(), _Movetype_Physics_Follow(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), _Movetype_PushEntityTrace(), Accuracy_GetColor(), aim_vec(), angle_snap_vec(), angleofs3(), AnglesTransform_Invert(), AnglesTransform_Multiply(), anim_vec(), animdecide_getloweranim(), animdecide_getupperanim(), animdecide_load_if_needed(), animdecide_setframes(), animdecide_setimplicitstate(), antilag_takeback(), antilag_takebackavgvelocity(), attach_sameorigin(), AuxiliaryXhair_Draw2D(), bd_move_dozer(), beamsweep(), bobmodel_ofs(), BorderImage_draw(), BorderImage_recalcPositionWithText(), bot_aim(), bot_aimdir(), bot_cmd_aimtarget(), botframe_autowaypoints_fix_from(), botframe_updatedangerousobjects(), buff_Respawn(), buildpath_nodefilter_directional(), Button_draw(), calc_followmodel_ofs(), CheatCommand(), CheckWaterJump(), CL_Weapon_GetShotOrg(), color_hslimage(), compressShortVector(), Container_itemFromPoint(), Container_resizeNotifyLie(), crosshair_getcolor(), CSQC_Demo_Camera(), CSQC_UpdateView(), CSQCPlayer_LOD_Apply(), CSQCPlayer_Physics(), CSQCPlayer_SetCamera(), ctf_CalculatePassVelocity(), ctf_CaptureShield_Touch(), ctf_CheckPassDirection(), ctf_FlagThink(), ctf_Handle_Throw(), Damage(), damage_explosion_calcpush(), debuggoalstack(), debugnodestatus(), decompressShortVector(), decompressShotOrigin(), detach_sameorigin(), Dialog_addItemSimple(), door_spawnfield(), Drag_Update(), Item::draw(), draw_BorderPicture(), draw_ButtonPicture(), draw_Picture_Aligned(), Draw_ShowNames(), draw_teamradar_background(), draw_teamradar_icon(), draw_teamradar_link(), draw_teamradar_player(), draw_TextWidth(), draw_VertButtonPicture(), DrawAmmoItem(), drawBackground(), drawborderlines(), DrawCAItem(), DrawCircleClippedPic(), DrawDomItem(), DrawNumIcon_expanding(), drawpic_tiled(), drawstring_expanding(), findnearest(), findtrajectorywithleading(), fireBullet(), FireRailgunBullet(), FixPlayermodel(), formatmessage(), frexp(), GameCommand_bbox(), GameCommand_gettaginfo(), GameCommand_trace(), GameTypeVote_DrawGameTypeItem(), generator_draw(), GENERIC_COMMAND(), GenericCommand(), get_closer_dest(), get_shotvelocity(), GetCurrentFov(), GrapplingHookThink(), havocbot_aim(), havocbot_bunnyhop(), havocbot_chooseenemy(), havocbot_ctf_calculate_middlepoint(), havocbot_dodge(), havocbot_gettarget(), havocbot_goalrating_items(), havocbot_keyboard_movement(), havocbot_moveto(), havocbot_movetogoal(), havocbot_role_ctf_carrier(), havocbot_role_ctf_defense(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), HUD_Ammo(), HUD_CenterPrint(), HUD_Chat(), HUD_Configure_DrawGrid(), HUD_Crosshair(), HUD_Draw(), Hud_Dynamic_Frame(), HUD_EngineInfo(), HUD_Get_Num_Color(), HUD_GetFontsize(), HUD_HealthArmor(), HUD_InfoMessages(), HUD_Main(), HUD_MinigameBoard(), HUD_MinigameHelp(), HUD_MinigameMenu(), HUD_MinigameMenu_MouseInput(), HUD_MinigameMenu_SpawnSubEntry(), HUD_MinigameStatus(), HUD_Mod_CA(), HUD_Mod_CTF(), HUD_Mod_Dom(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_Race(), HUD_mouse_over(), HUD_Notify(), HUD_Panel_Arrow_Action(), HUD_Panel_CheckMove(), HUD_Panel_CheckResize(), HUD_Panel_DrawProgressBar(), HUD_Panel_HlBorder(), HUD_Panel_InputEvent(), HUD_Panel_Mouse(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Powerups(), HUD_PressedKeys(), HUD_QuickMenu(), HUD_Quickmenu_DrawEntry(), HUD_RaceTimer(), HUD_Radar(), HUD_Radar_Mouse(), HUD_Score(), HUD_Score_Rankings(), HUD_Timer(), HUD_Vote(), HUD_Weapons(), hue_mi_ma_to_rgb(), Image_updateAspect(), info_autoscreenshot_findtarget(), InitGameplayMode(), InputBox_draw(), InterpolateOrigin_Do(), jumppad_push(), ka_RespawnBall(), kh_Key_Think(), kh_WinnerTeam(), Label_draw(), Label_recalcPositionWithText(), leanmodel_ofs(), lgamma(), LinkDoors(), ListBox_draw(), ListBox_mouseRelease(), LocalCommand_boxparticles(), m_allocatetooltipbox(), m_draw(), m_keydown(), m_tooltip(), MapVote_Draw(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), minigame_drawcolorcodedstring_wrapped(), minigame_drawstring_wrapped(), ModalController_draw(), Monster_Attack_Leap_Check(), Monster_CalculateVelocity(), Monster_Damage(), monster_dropitem(), Monster_FindTarget(), monster_makevectors(), Monster_Move(), Monster_Move_2D(), Monster_Move_Target(), Monster_ValidTarget(), monsters_animoverride(), movelib_groundalign4point(), MoveToRandomLocationWithinBounds(), Movetype_Physics_MatchTicrate(), MUTATOR_HOOKFUNCTION(), navigation_checkladders(), navigation_findnearestwaypoint_withdist_except(), navigation_goalrating_timeout_can_be_anticipated(), navigation_markroutes(), navigation_markroutes_checkwaypoint(), navigation_markroutes_inverted(), navigation_markroutes_nearestwaypoints(), navigation_poptouchedgoals(), navigation_shortenpath(), NET_HANDLE(), Nexposee_calc(), Nexposee_draw(), ons_camSetup(), ons_CaptureShield_Touch(), ons_Nearest_ControlPoint_2D(), ons_Teleport(), pathlib_close_node(), pathlib_expandnode_box(), pathlib_expandnode_octagon(), pathlib_expandnode_star(), pathlib_expandnode_starf(), pathlib_h_diagonal2sdp(), pathlib_makenode_adaptive(), pathlib_walknode(), pathlib_wateroutnode(), plat_spawn_inside_trigger(), PlayerCorpseDamage(), PlayerDamage(), PlayerEdgeDistance(), PlayerPostThink(), PlayerScore_Compare(), PlayerTouchExplode(), PM_Accelerate(), PM_AirAccelerate(), PM_check_frozen(), PM_dodging_checkpressedkeys(), PM_jetpack(), PolyDrawModelSurface(), Portal_ApplyTransformToPlayerAngle(), Portal_FindSafeOrigin(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_TeleportPlayer(), Portal_Think(), Portal_Touch(), Portal_WillHitPlane(), Porto_Draw(), prandomvec(), preMenuDraw(), preMenuInit(), Projectile_Draw(), Projectile_DrawTrail(), QuickMenu_Mouse(), race_GetFractionalLapCount(), RadiusDamageForSource(), RandomItems_SpawnLootItem(), randompos(), relocate_spawnpoint(), remquo(), rgb_to_hsl(), rgb_to_hsv(), sandbox_ObjectAttach_Remove(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), Scoreboard_FixColumnWidth(), Scoreboard_MakeTable(), Scoreboard_MapStats_Draw(), Scoreboard_Rankings_Draw(), ServerList_Info_Click(), set_tracewalk_dest(), set_tracewalk_dest_2(), shortangle_v(), shortangle_vxy(), Simple_TeleportPlayer(), skel_set_boneabs(), skeleton_from_frames(), solve_cubic_abcd(), solve_quadratic(), solve_shotdirection(), Spawn_PreDraw(), Spawn_Score(), spawnfunc(), SpecialCommand(), steerlib_arrive(), steerlib_attract(), steerlib_attract2(), steerlib_beamsteer(), steerlib_flock(), steerlib_flock2d(), steerlib_repell(), steerlib_standoff(), steerlib_swarm(), steerlib_traceavoid(), steerlib_traceavoid_flat(), steerlib_wander(), stringwidth(), SUB_CalcAngleMove(), SUB_CalcMove(), SUB_CalcMove_controller_think(), SUB_NoImpactCheck(), sys_phys_simulate(), sys_phys_simulate_simple(), sys_phys_update(), teamradar_2dcoord_to_texcoord(), teamradar_3dcoord_to_texcoord(), teamradar_texcoord_to_2dcoord(), teamradar_texcoord_to_3dcoord(), TeamScore_Compare(), TeleportPlayer(), tgamma(), tile_check_cross(), tile_check_plus(), tile_check_plus2(), tracewalk(), train_next(), train_wait(), trigger_push_calculatevelocity(), trigger_push_test(), trigger_race_checkpoint_verify(), TrueAimCheck(), turret_draw2d(), updateConwidths(), vec_bias(), vec_bounds_in(), vec_bounds_out(), vec_to_max(), vec_to_min(), vehicle_aimturret(), vehicle_tossgib(), Vehicles_drawCrosshair(), Vehicles_drawHUD(), vehicles_findgoodexit(), vehicles_reset_colors(), vehicles_showwp(), viewloc_PlayerPhysics(), viewmodel_draw(), vsnap(), W_CalculateProjectileVelocity(), W_CalculateSpread(), W_HitPlotAnalysis(), W_HitPlotNormalizedUntransform(), W_HitPlotUnnormalizedUntransform(), W_Nexball_Think(), W_SetupShot_Dir_ProjectileSize_Range(), W_WeaponFrame(), WarpZone_Accumulator_AddInverseTransform(), WarpZone_Accumulator_AddTransform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), WarpZone_FindRadius_Recurse(), WarpZone_FixNearClip(), WarpZone_FixView(), WarpZone_PostInitialize_Callback(), WarpZone_Projectile_Touch(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_ExactTrigger_Init(), WarpZoneLib_MoveOutOfSolid(), WarpZoneLib_NearestPointOnBox(), waypoint_getlinkcost(), waypoint_getSymmetricalPoint(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_remove_fromeditor(), waypoint_setupmodel(), waypoint_spawn(), waypoint_spawn_fromeditor(), waypoint_think(), weapon_thinkf(), WeaponStats_ready(), XonoticCampaignList_drawListBoxItem(), XonoticColorpicker_mouseDrag(), XonoticColorpickerString_draw(), XonoticColorpickerString_mouseDrag(), XonoticColorpickerString_saveCvars(), XonoticCreditsList_drawListBoxItem(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_draw(), XonoticCvarList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticPicker_draw(), XonoticPicker_mouseMove(), XonoticPlayerList_drawListBoxItem(), XonoticPlayerModelSelector_draw(), XonoticResolutionSlider_loadResolutions(), XonoticResolutionSlider_saveCvars(), XonoticServerList_drawListBoxItem(), XonoticServerList_keyDown(), XonoticServerList_positionSortButton(), and XonoticWeaponsList_drawListBoxItem().
vector (vector v, vector w)
vector () = #344
vector (vector org, float lpflags)
vector (string) = #318
vector (float property)
vector (vector position, string text, vector scale, vector rgb, float alpha, float flag)
vector (entity e, float s, float n) = #629
vector (entity e, float s) = #452
vector (entity e, float s, vector p)
vector (entity e, float s, float n, float a)
vector (float entitynum, float fldnum) = #269
void ()
void (float w, float h)
void (vector ang)
void (entity e, vector o)
void (entity e, string m)
void (entity e, vector min, vector max)
void (entity e, float chan, string samp)
void (string e)
void (entity e)
void (string s, ...)
void (float style, string value)
void (vector o, vector d, float color, float count)
void (entity e, entity ignore)
void (string var, string val)
void (vector pos, string samp, float vol, float atten)
void (vector v1, vector min, vector max, vector v2, float nomonsters, entity forent)
void (float fhandle)
void (vector org, float radius, vector lightcolours)
void (vector org, float radius, vector lightcolours, float style, string cubemapname, float pflags)
void (string texturename, float flag, ...)
void (vector org, vector texcoords, vector rgb, float alpha)
void (float width, vector pos1, vector pos2, float flag)
void (float x, float y, float width, float height)
void (entity e, float mdlindex)
void (entity ent, float effectnum, vector start, vector end)
void (...)
void (vector origin, vector forward, vector right, vector up)
void (vector org, string modelname, float startframe, float endframe, float framerate)
void (vector org, vector velocity, float howmany)
void (vector org, vector color)
void (vector mincorner, vector maxcorner, vector vel, float howmany, float color, float gravityflag, float randomveljitter)
void (vector mincorner, vector maxcorner, vector vel, float howmany, float color)
void (vector org, float radius, float lifetime, vector color)
void (vector org, float colorstart, float colorlength)
void (entity e, entity tagentity, string tagname)
void (float bufhandle, float sortpower, float backward)
void (float bufhandle, float string_index, string str)
void (entity e, float chan, string samp, float vol, float atten, float speed, float flags)
void (float skel, float bonenum, vector org)
void (float skel, float startbone, float endbone, vector org)
void (float animmodelindex, float framegroup, float framegroupstarttime, float blendalpha, string groupbonename, string excludegroupname1, string excludegroupname2)
void (vector eyetarget, string bonename)
void (float fh, entity e)
void (float effectindex, entity own, vector org_from, vector org_to, vector dir_from, vector dir_to, float countmultiplier, float flags)
Variable Documentation
vector absmax
Definition at line 92 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict(), _Movetype_LinkEdict_TouchAreaGrid(), ctf_CaptureShield_Touch(), ctf_FlagThink(), LinkDoors(), movelib_groundalign4point(), navigation_poptouchedgoals(), ons_CaptureShield_Touch(), plat_spawn_inside_trigger(), PM_check_frozen(), spawnfunc(), sys_phys_simulate_simple(), sys_phys_update(), trigger_push_test(), vehicles_findgoodexit(), and waypoint_think().
vector absmin
Definition at line 92 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict(), _Movetype_LinkEdict_TouchAreaGrid(), ctf_CaptureShield_Touch(), ctf_FlagThink(), LinkDoors(), movelib_groundalign4point(), navigation_poptouchedgoals(), ons_CaptureShield_Touch(), plat_spawn_inside_trigger(), PM_check_frozen(), spawnfunc(), sys_phys_simulate_simple(), sys_phys_update(), trigger_push_test(), vehicles_findgoodexit(), and waypoint_think().
vector angles
Definition at line 104 of file csprogsdefs.qc.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Follow(), _Movetype_Physics_Frame(), _Movetype_Physics_Toss(), anticheat_spectatecopy(), bot_think(), buff_Respawn(), CheatImpulse(), CopyBody(), CSQCModel_Effects_Apply(), CSQCPlayer_Physics(), ctf_FlagThink(), GrapplingHookThink(), InterpolateOrigin_Do(), InterpolateOrigin_Note(), InterpolateOrigin_Undo(), ka_RespawnBall(), Monster_Dead_Fade(), Monster_Move(), Monster_Move_2D(), Monster_Move_Target(), Monster_Reset(), Monster_Spawn(), Monster_ValidTarget(), movelib_groundalign4point(), Movetype_Physics_MatchTicrate(), physical_item_damage(), physical_item_think(), physical_item_touch(), PlayerDamage(), PlayerThink(), PM_dodging(), PM_dodging_checkpressedkeys(), Projectile_Draw(), PutObserverInServer(), PutPlayerInServer(), relocate_spawnpoint(), SpectateCopy(), SUB_CalcAngleMove(), SUB_CalcAngleMoveDone(), SV_OnEntityPreSpawnFunction(), sys_phys_simulate_simple(), sys_phys_update(), turret_construct(), vehicle_initialize(), vehicles_damage(), vehicles_painframe(), vehicles_spawn(), viewmodel_animate(), viewmodel_draw(), and WarpZoneLib_ExactTrigger_Init().
const float ATTN_IDLE = 2
Definition at line 227 of file csprogsdefs.qc.
const float ATTN_NONE = 0
Definition at line 225 of file csprogsdefs.qc.
Referenced by HitSound().
const float ATTN_NORM = 1
Definition at line 226 of file csprogsdefs.qc.
Referenced by buff_Think(), buff_Touch(), MUTATOR_HOOKFUNCTION(), W_SetupShot_Dir_ProjectileSize_Range(), and W_WeaponFrame().
const float ATTN_STATIC = 3
Definition at line 228 of file csprogsdefs.qc.
vector avelocity
Definition at line 105 of file csprogsdefs.qc.
Referenced by _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Toss(), CopyBody(), Movetype_Physics_MatchTicrate(), NET_HANDLE(), PlayerDamage(), Projectile_Draw(), PutObserverInServer(), PutPlayerInServer(), respawn(), SUB_CalcAngleMove(), SUB_CalcAngleMoveDone(), SUB_Stop(), sys_phys_simulate_simple(), vehicles_reset_colors(), and vehicles_spawn().
entity chain
Definition at line 123 of file csprogsdefs.qc.
Referenced by WarpZone_FindRadius().
const float CHAN_AUTO = 0
Definition at line 219 of file csprogsdefs.qc.
Referenced by ons_GeneratorThink().
const float CHAN_BODY = 4
Definition at line 223 of file csprogsdefs.qc.
const float CHAN_ITEM = 3
Definition at line 222 of file csprogsdefs.qc.
const float CHAN_VOICE = 2
Definition at line 221 of file csprogsdefs.qc.
const float CHAN_WEAPON = 1
Definition at line 220 of file csprogsdefs.qc.
string classname
Definition at line 107 of file csprogsdefs.qc.
Referenced by _Movetype_UnstickEntity(), buff_Init(), buffs_DelayedInit(), CA_SpectateNext(), CheatCommand(), CheatImpulse(), Client::Client(), CSQC_Ent_Update(), ctf_DelayedInit(), dom_controlpoint_setup(), dom_DelayedInit(), dompointtouch(), door_blocked(), door_hit_top(), Ent_Remove(), generator_construct(), HUD_MinigameMenu_ClickJoin(), LinkDoors_nextent(), Client::m_unwind(), minigame_SendEntity(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), Observer::Observer(), Player::Player(), PlayerDamage(), SelectSpawnPoint(), spawnfunc(), SpectateNext(), SpectatePrev(), Spectator::Spectator(), SUB_NoImpactCheck(), sys_phys_postupdate(), target_init_verify(), tdm_DelayedInit(), TeamBalance_CheckAllowedTeams(), trigger_race_checkpoint_verify(), vehicles_spawn(), WarpZone_PostInitialize_Callback(), WarpZone_Projectile_Touch_ImpactFilter_Callback(), weapon_defaultspawnfunc(), and WinningCondition_Assault().
float clientcommandframe
Definition at line 23 of file csprogsdefs.qc.
Referenced by CSQCPlayer_PredictTo(), and CSQCPlayer_SetCamera().
float colormap
Definition at line 131 of file csprogsdefs.qc.
Referenced by CL_ExteriorWeaponentity_Think(), CopyBody(), cpicon_changeteam(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), CSQCPlayer_ModelAppearance_PreUpdate(), generator_changeteam(), monster_setupcolors(), NET_HANDLE(), ons_CaptureShield_Reset(), ons_ControlPoint_Reset(), physical_item_think(), turret_changeteam(), and vehicles_reset_colors().
const float CONTENT_EMPTY = -1
Definition at line 236 of file csprogsdefs.qc.
const float CONTENT_LAVA = -5
Definition at line 240 of file csprogsdefs.qc.
const float CONTENT_SKY = -6
Definition at line 241 of file csprogsdefs.qc.
const float CONTENT_SLIME = -4
Definition at line 239 of file csprogsdefs.qc.
const float CONTENT_SOLID = -2
Definition at line 237 of file csprogsdefs.qc.
const float CONTENT_WATER = -3
Definition at line 238 of file csprogsdefs.qc.
float CVAR_TYPEFLAG_ENGINE = 8
Definition at line 1174 of file csprogsdefs.qc.
Referenced by XonoticCvarList_updateCvarType(), XonoticInputSettingsTab_fill(), and XonoticMiscSettingsTab_fill().
float CVAR_TYPEFLAG_EXISTS = 1
Definition at line 1171 of file csprogsdefs.qc.
Referenced by cvar_string_normal(), RandomItems_GetItemReplacementClassNames(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), RandomItems_GetRandomVanillaItemClassName(), VoteCommand_checkargs(), and VoteCommand_macro_help().
float CVAR_TYPEFLAG_HASDESCRIPTION = 16
Definition at line 1175 of file csprogsdefs.qc.
float CVAR_TYPEFLAG_PRIVATE = 4
Definition at line 1173 of file csprogsdefs.qc.
Referenced by XonoticCvarList_updateCvarType().
float CVAR_TYPEFLAG_READONLY = 32
Definition at line 1176 of file csprogsdefs.qc.
Referenced by XonoticCvarList_updateCvarType().
float CVAR_TYPEFLAG_SAVED = 2
Definition at line 1172 of file csprogsdefs.qc.
Referenced by XonoticCvarList_drawListBoxItem(), and XonoticCvarList_updateCvarType().
float DEG2RAD = 0.0174532925199432957692369076848861271344287188854172545609719144
Definition at line 961 of file csprogsdefs.qc.
Referenced by bot_aimdir(), CSQC_Demo_Camera(), HUD_Radar(), ons_camSetup(), teamradar_2dcoord_to_texcoord(), teamradar_texcoord_to_2dcoord(), and waypoint_getSymmetricalPoint().
float DPCONTENTS_BODY = 32
Definition at line 1129 of file csprogsdefs.qc.
Referenced by bot_aim(), buff_Init(), buff_Respawn(), CheatImpulse(), fireBullet(), GameCommand_trace(), havocbot_chooseenemy(), ka_RespawnBall(), kh_Key_Spawn(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), STATIC_INIT(), teleport_findtarget(), tracebox_antilag_force_wz(), trigger_push_test(), TrueAim_Init(), vehicle_initialize(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_PostInitialize_Callback(), and waypoint_think().
float DPCONTENTS_BOTCLIP = 2048
Definition at line 1136 of file csprogsdefs.qc.
Referenced by GameCommand_trace(), kh_Key_Spawn(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), teleport_findtarget(), trigger_push_test(), WarpZone_PostInitialize_Callback(), and waypoint_think().
float DPCONTENTS_CORPSE = 64
Definition at line 1130 of file csprogsdefs.qc.
Referenced by bot_aim(), buff_Respawn(), CheatImpulse(), fireBullet(), havocbot_chooseenemy(), ka_RespawnBall(), tracebox_antilag_force_wz(), TrueAim_Init(), and W_SetupShot_Dir_ProjectileSize_Range().
float DPCONTENTS_DONOTENTER = 1024
Definition at line 1134 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), and ka_RespawnBall().
float DPCONTENTS_LAVA = 8
Definition at line 1127 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), and ka_RespawnBall().
float DPCONTENTS_LIQUIDSMASK = 14
Definition at line 1135 of file csprogsdefs.qc.
Referenced by _Movetype_CheckWater().
float DPCONTENTS_MONSTERCLIP = 512
Definition at line 1133 of file csprogsdefs.qc.
Referenced by Monster_Spawn(), and MUTATOR_HOOKFUNCTION().
float DPCONTENTS_NODROP = 128
Definition at line 1131 of file csprogsdefs.qc.
float DPCONTENTS_OPAQUE = 4096
Definition at line 1137 of file csprogsdefs.qc.
Referenced by fireBullet().
float DPCONTENTS_PLAYERCLIP = 256
Definition at line 1132 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), ctf_FlagSetup(), GameCommand_trace(), ka_RespawnBall(), kh_Key_Spawn(), Monster_Spawn(), Porto_Draw(), PutObserverInServer(), PutPlayerInServer(), STATIC_INIT(), teleport_findtarget(), trigger_push_test(), vehicle_initialize(), WarpZone_PostInitialize_Callback(), and waypoint_think().
float DPCONTENTS_SKY = 16
Definition at line 1128 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), and ka_RespawnBall().
float DPCONTENTS_SLIME = 4
Definition at line 1126 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), and ka_RespawnBall().
float DPCONTENTS_SOLID = 1
Definition at line 1124 of file csprogsdefs.qc.
Referenced by _Movetype_TestEntityPosition(), bot_aim(), buff_Init(), buff_Respawn(), CheatImpulse(), ctf_FlagSetup(), fireBullet(), GameCommand_trace(), havocbot_chooseenemy(), ka_RespawnBall(), kh_Key_Spawn(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), PutObserverInServer(), PutPlayerInServer(), STATIC_INIT(), teleport_findtarget(), tracebox_antilag_force_wz(), trigger_push_test(), TrueAim_Init(), vehicle_initialize(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_PostInitialize_Callback(), WarpZone_TraceBox_ThroughZone(), and waypoint_think().
float DPCONTENTS_WATER = 2
Definition at line 1125 of file csprogsdefs.qc.
float dphitcontentsmask
Definition at line 1118 of file csprogsdefs.qc.
Referenced by _Movetype_TestEntityPosition(), bot_aim(), buff_Init(), CopyBody(), fireBullet(), havocbot_chooseenemy(), Monster_Spawn(), PutObserverInServer(), PutPlayerInServer(), TrueAim_Init(), vehicle_initialize(), and waypoint_think().
const float DRAWFLAG_2XMODULATE = 3
Definition at line 320 of file csprogsdefs.qc.
const float DRAWFLAG_ADDITIVE = 1
Definition at line 318 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView(), draw_teamradar_icon(), HUD_Crosshair(), HUD_Draw(), HUD_MinigameMenu(), HUD_Quickmenu_DrawEntry(), NET_HANDLE(), and SpecialCommand().
const float DRAWFLAG_MIPMAP = 0x100
Definition at line 322 of file csprogsdefs.qc.
Referenced by draw_teamradar_background().
const float DRAWFLAG_MODULATE = 2
Definition at line 319 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView().
const float DRAWFLAG_NORMAL = 0
Definition at line 317 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView(), DamageText::DamageText_draw2d(), draw_cursor(), Draw_ShowNames(), DrawAmmoItem(), DrawCAItem(), DrawDomItem(), DrawNadeProgressBar(), DrawNumIcon_expanding(), GameTypeVote_DrawGameTypeItem(), HUD_CenterPrint(), HUD_Chat(), HUD_Configure_DrawGrid(), HUD_Configure_PostDraw(), HUD_Draw(), HUD_EngineInfo(), HUD_HealthArmor(), HUD_Main(), HUD_MinigameHelp(), HUD_MinigameMenu(), HUD_MinigameMenu_DrawColoredEntry(), HUD_MinigameMenu_DrawEntry(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_NexBall(), HUD_Mod_Race(), HUD_Notify(), HUD_Panel_HlBorder(), HUD_Panel_Mouse(), HUD_Physics(), HUD_Powerups(), HUD_PressedKeys(), HUD_QuickMenu(), HUD_RaceTimer(), HUD_Score(), HUD_Score_Rankings(), HUD_Timer(), HUD_Vote(), InfoMessages_drawstring(), MapStats_DrawKeyValue(), MapVote_Draw(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), minigame_hud_simpleboard(), NET_HANDLE(), Porto_Draw(), QuickMenu_Mouse(), race_showTime(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), Scoreboard_MakeTable(), Scoreboard_MapStats_Draw(), Scoreboard_Rankings_Draw(), SpecialCommand(), turret_draw2d(), Vehicles_drawCrosshair(), and Vehicles_drawHUD().
const float DRAWFLAG_SCREEN = 4
Definition at line 321 of file csprogsdefs.qc.
Referenced by draw_teamradar_background().
float drawfont
Definition at line 820 of file csprogsdefs.qc.
float drawmask
Definition at line 95 of file csprogsdefs.qc.
Referenced by cpicon_construct(), CSQCModel_AutoTagIndex_Apply(), CSQCModel_Effects_Apply(), CSQCModel_Hook_PreDraw(), DrawDebugModel(), generator_construct(), NET_HANDLE(), Projectile_Draw(), Spawn_PreDraw(), turret_construct(), turret_gib_draw(), turret_head_draw(), and WarpZone_Fade_PreDraw().
float E_ABSMAX = 15
Definition at line 795 of file csprogsdefs.qc.
float E_ABSMIN = 14
Definition at line 794 of file csprogsdefs.qc.
float E_ACTIVE = 0
Definition at line 780 of file csprogsdefs.qc.
float E_ALPHA = 7
Definition at line 787 of file csprogsdefs.qc.
float E_COLORMOD = 8
Definition at line 788 of file csprogsdefs.qc.
float E_FORWARD = 2
Definition at line 782 of file csprogsdefs.qc.
float E_LIGHT = 16
Definition at line 796 of file csprogsdefs.qc.
float E_MAXS = 13
Definition at line 793 of file csprogsdefs.qc.
float E_MINS = 12
Definition at line 792 of file csprogsdefs.qc.
float E_ORIGIN = 1
Definition at line 781 of file csprogsdefs.qc.
float E_ORIGINANDVECTORS = 6
Definition at line 786 of file csprogsdefs.qc.
float E_PANTSCOLOR = 9
Definition at line 789 of file csprogsdefs.qc.
float E_RIGHT = 3
Definition at line 783 of file csprogsdefs.qc.
float E_SCALE = 5
Definition at line 785 of file csprogsdefs.qc.
float E_SHIRTCOLOR = 10
Definition at line 790 of file csprogsdefs.qc.
float E_SKIN = 11
Definition at line 791 of file csprogsdefs.qc.
float E_UP = 4
Definition at line 784 of file csprogsdefs.qc.
const float EF_ADDITIVE = 32
Definition at line 300 of file csprogsdefs.qc.
const float EF_BLUE = 64
Definition at line 301 of file csprogsdefs.qc.
const float EF_FLAME = 1024
Definition at line 302 of file csprogsdefs.qc.
const float EF_FULLBRIGHT = 512
Definition at line 303 of file csprogsdefs.qc.
const float EF_NODEPTHTEST = 8192
Definition at line 304 of file csprogsdefs.qc.
const float EF_NODRAW = 16
Definition at line 305 of file csprogsdefs.qc.
const float EF_NOSHADOW = 4096
Definition at line 306 of file csprogsdefs.qc.
const float EF_RED = 128
Definition at line 307 of file csprogsdefs.qc.
const float EF_SELECTABLE = 16384
Definition at line 309 of file csprogsdefs.qc.
Referenced by vehicle_addplayerslot(), and vehicles_reset_colors().
const float EF_STARDUST = 2048
Definition at line 308 of file csprogsdefs.qc.
float effects
Definition at line 111 of file csprogsdefs.qc.
Referenced by buff_Customize(), buff_Init(), buffs_BuffModel_Customize(), CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), CopyBody(), CSQCModel_Effects_Apply(), CSQCModel_Effects_PostUpdate(), CSQCModel_Effects_PreUpdate(), FixIntermissionClient(), ka_RespawnBall(), ka_TouchEvent(), Monster_Dead(), Monster_Miniboss_Check(), Monster_Spawn(), Monster_Spawn_Setup(), player_powerups(), PutObserverInServer(), PutPlayerInServer(), respawn(), shieldhit_think(), spawnfunc(), SpectateCopy(), vehicle_initialize(), vehicle_use(), vehicles_reset_colors(), and w_clear().
void end_sys_fields
Definition at line 136 of file csprogsdefs.qc.
void end_sys_globals
Definition at line 76 of file csprogsdefs.qc.
entity enemy
Definition at line 127 of file csprogsdefs.qc.
float entnum
Definition at line 94 of file csprogsdefs.qc.
Referenced by CSQC_Ent_Remove(), CSQC_Ent_Update(), CSQCModel_AutoTagIndex_Apply(), CSQCModel_Draw(), CSQCModel_Hook_PostUpdate(), CSQCModel_Hook_PreDraw(), CSQCModel_remove(), CSQCModel_server2csqc(), CSQCPlayer_PostUpdate(), LocalCommand_boxparticles(), and NET_HANDLE().
const float EXTRA_HIGH = 99999999
Definition at line 263 of file csprogsdefs.qc.
const float EXTRA_LOW = -99999999
Definition at line 262 of file csprogsdefs.qc.
const float false = 0
Definition at line 258 of file csprogsdefs.qc.
const float FALSE = 0
Definition at line 260 of file csprogsdefs.qc.
float FIELD_ENTITY = 4
Definition at line 1416 of file csprogsdefs.qc.
float FIELD_FLOAT = 2
Definition at line 1414 of file csprogsdefs.qc.
float FIELD_FUNCTION = 6
Definition at line 1417 of file csprogsdefs.qc.
float FIELD_STRING = 1
Definition at line 1413 of file csprogsdefs.qc.
float FIELD_VECTOR = 3
Definition at line 1415 of file csprogsdefs.qc.
const float FILE_APPEND = 1
Definition at line 232 of file csprogsdefs.qc.
const float FILE_READ = 0
Definition at line 231 of file csprogsdefs.qc.
const float FILE_WRITE = 2
Definition at line 233 of file csprogsdefs.qc.
float flags
Definition at line 129 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict(), _Movetype_Physics_Walk(), bot_think(), buff_FirstFromFlags(), buff_Init(), CheatCommand(), CheckWaterJump(), ClientConnect(), ClientDisconnect(), CreatureFrame_FallDamage(), CreatureFrame_hotliquids(), CreatureFrame_Liquids(), CSQCModel_Hook_PreDraw(), CSQCPlayer_SavePrediction(), CSQCPlayer_Unpredict(), dom_controlpoint_setup(), find_bot_by_number(), HUD_MinigameMenu_Click_ExpandCollapse(), instagib_ammocheck(), LocalCommand_boxparticles(), Monster_Appear_Check(), Monster_Dead(), Monster_Move(), Monster_Move_Target(), Monster_Spawn(), Movetype_Physics_MatchTicrate(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ObserverThink(), PlayerDamage(), PlayerPreThink(), Projectile_Draw(), PutObserverInServer(), PutPlayerInServer(), SpectatorThink(), sys_phys_postupdate(), sys_phys_update(), vehicles_spawn(), and viewloc_PlayerPhysics().
float FONT_CENTERPRINT = 5
Definition at line 826 of file csprogsdefs.qc.
float FONT_CHAT = 4
Definition at line 825 of file csprogsdefs.qc.
float FONT_CONSOLE = 1
Definition at line 822 of file csprogsdefs.qc.
float FONT_DEFAULT = 0
Definition at line 821 of file csprogsdefs.qc.
float FONT_INFOBAR = 6
Definition at line 827 of file csprogsdefs.qc.
float FONT_MENU = 7
Definition at line 828 of file csprogsdefs.qc.
float FONT_NOTIFY = 3
Definition at line 824 of file csprogsdefs.qc.
float FONT_SBAR = 2
Definition at line 823 of file csprogsdefs.qc.
float FONT_USER0 = 8
Definition at line 829 of file csprogsdefs.qc.
float FONT_USER1 = 9
Definition at line 830 of file csprogsdefs.qc.
float FONT_USER2 = 10
Definition at line 831 of file csprogsdefs.qc.
float FONT_USER3 = 11
Definition at line 832 of file csprogsdefs.qc.
float FONT_USER4 = 12
Definition at line 833 of file csprogsdefs.qc.
float FONT_USER5 = 13
Definition at line 834 of file csprogsdefs.qc.
float FONT_USER6 = 14
Definition at line 835 of file csprogsdefs.qc.
float FONT_USER7 = 15
Definition at line 836 of file csprogsdefs.qc.
float frame
Definition at line 109 of file csprogsdefs.qc.
float frame1time
Definition at line 1247 of file csprogsdefs.qc.
float frame2
Definition at line 1241 of file csprogsdefs.qc.
float frame2time
Definition at line 1248 of file csprogsdefs.qc.
float frame3
Definition at line 1242 of file csprogsdefs.qc.
float frame3time
Definition at line 1249 of file csprogsdefs.qc.
float frame4
Definition at line 1243 of file csprogsdefs.qc.
float frame4time
Definition at line 1250 of file csprogsdefs.qc.
float frametime
Definition at line 17 of file csprogsdefs.qc.
Referenced by anim_set(), anticheat_endframe(), anticheat_physics(), anticheat_startframe(), bobmodel_ofs(), buff_Think(), Button_draw(), cpicon_draw(), CSQC_UpdateView(), CSQCModel_Effects_Apply(), Drag(), Drag_Update(), Draw_ShowNames(), EndFrame(), Fire_ApplyDamage(), getFadedAlpha(), GrapplingHookThink(), HUD_Crosshair(), HUD_ModIcons(), img_select(), ListBox_draw(), m_draw(), m_tooltip(), ModalController_draw(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), Nexposee_draw(), Physics_Frame(), play_countdown(), Player_Physics(), player_regen(), PlayerPostThink(), PlayerPreThink(), PlayerThink(), Portal_Think(), Portal_Think_TryTeleportPlayer(), Portal_Touch(), RunThink(), Scoreboard_Draw(), Spawn_Draw(), SpecialCommand(), StartFrame(), SUB_Friction(), SUB_SetFade_Think(), sys_phys_update_single(), W_WeaponFrame(), WarpZone_FixView(), WarpZone_Teleport(), and WarpZone_Touch().
vector getlight_ambient
Definition at line 411 of file csprogsdefs.qc.
vector getlight_diffuse
Definition at line 412 of file csprogsdefs.qc.
vector getlight_dir
Definition at line 410 of file csprogsdefs.qc.
vector gettaginfo_forward
Definition at line 1464 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo().
string gettaginfo_name
Definition at line 1462 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo(), and MUTATOR_HOOKFUNCTION().
vector gettaginfo_offset
Definition at line 1463 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo().
float gettaginfo_parent
Definition at line 1461 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo().
vector gettaginfo_right
Definition at line 1465 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo().
vector gettaginfo_up
Definition at line 1466 of file csprogsdefs.qc.
Referenced by GameCommand_gettaginfo().
float GETTIME_CDTRACK = 4
Definition at line 1019 of file csprogsdefs.qc.
float GETTIME_FRAMESTART = 0
Definition at line 1006 of file csprogsdefs.qc.
Referenced by CommonCommand_time().
float GETTIME_HIRES = 2
Definition at line 1008 of file csprogsdefs.qc.
Referenced by CommonCommand_time(), GameCommand_animbench(), and W_SetupProjVelocity_Explicit().
float GETTIME_REALTIME = 1
Definition at line 1007 of file csprogsdefs.qc.
float GETTIME_UPTIME = 3
Definition at line 1009 of file csprogsdefs.qc.
Referenced by CommonCommand_time().
vector input_angles
Definition at line 60 of file csprogsdefs.qc.
Referenced by CSQCPlayer_Physics(), CSQCPlayer_PredictTo(), CSQCPlayer_SetCamera(), skeleton_from_frames(), and WarpZone_FixPMove().
float input_buttons
Definition at line 62 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera(), and viewloc_PlayerPhysics().
vector input_movevalues
Definition at line 61 of file csprogsdefs.qc.
float input_timelength
Definition at line 59 of file csprogsdefs.qc.
float intermission
Definition at line 148 of file csprogsdefs.qc.
Referenced by Announcer_Gamestart(), Announcer_Time(), CSQC_UpdateView(), CSQCPlayer_SetCamera(), GetCurrentFov(), HUD_Chat(), HUD_Configure_Frame(), HUD_Crosshair(), HUD_Draw(), Hud_Dynamic_Frame(), HUD_Main(), HUD_Panel_Draw(), HUD_Radar_Mouse(), HUD_Vehicle(), Porto_Draw(), Scoreboard_Draw(), Scoreboard_WouldDraw(), viewmodel_draw(), and WantEventchase().
float lerpfrac
Definition at line 1244 of file csprogsdefs.qc.
float lerpfrac3
Definition at line 1245 of file csprogsdefs.qc.
float lerpfrac4
Definition at line 1246 of file csprogsdefs.qc.
const float LP_COMPLETE = 7
Definition at line 416 of file csprogsdefs.qc.
const float LP_DYNLIGHT = 4
Definition at line 415 of file csprogsdefs.qc.
const float LP_LIGHTMAP = 1
Definition at line 413 of file csprogsdefs.qc.
const float LP_RTWORLD = 2
Definition at line 414 of file csprogsdefs.qc.
const float M_PI = 3.14159265358979323846
Definition at line 269 of file csprogsdefs.qc.
Referenced by anticheat_physics(), colormapPaletteColor_(), CSQC_UpdateView(), DrawCircleClippedPic(), GameCommand_trace(), GetCurrentFov(), GetOrthoviewFOV(), GetViewLocationFOV(), gsl_ran_gaussian(), HUD_Get_Num_Color(), HUD_Mod_KH(), lgamma(), movement_oddity(), ons_Teleport(), prandom(), smneg_multiplier(), solve_cubic_pq(), turret_draw2d(), and W_CalculateSpread().
string mapname
Definition at line 26 of file csprogsdefs.qc.
Referenced by GetMapname(), InitGameplayMode(), spawnfunc(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_remove_fromeditor(), waypoint_save_links(), and waypoint_saveall().
const float MASK_ENGINE = 1
Definition at line 162 of file csprogsdefs.qc.
const float MASK_ENGINEVIEWMODELS = 2
Definition at line 163 of file csprogsdefs.qc.
const float MASK_NORMAL = 4
Definition at line 164 of file csprogsdefs.qc.
float maxclients
Definition at line 21 of file csprogsdefs.qc.
Referenced by bot_fixcount(), CommonCommand_who(), CopyBody(), CSQC_Init(), CSQC_UpdateView(), CSQCModel_AutoTagIndex_Apply(), CSQCModel_Draw(), CSQCModel_Hook_PostUpdate(), CSQCModel_server2csqc(), DoesQ3ARemoveThisEntity(), EliminatedPlayers_SendEntity(), EnemyHitCheck(), HUD_MinigameMenu_ClickInvite(), Nagger_SendEntity(), NET_HANDLE(), nJoinAllowed(), PingPLReport_Think(), Playerchecker_Think(), PlayerPostThink(), STATIC_INIT(), STATIC_INIT_EARLY(), VerifyClientNumber(), and viewmodel_draw().
vector maxs
Definition at line 113 of file csprogsdefs.qc.
Referenced by _Movetype_CheckWater(), _Movetype_LinkEdict(), _Movetype_Physics_Walk(), _Movetype_PushEntityTrace(), _Movetype_TestEntityPosition(), buff_Respawn(), CopyBody(), CSQCModel_Hook_PreDraw(), CSQCPlayer_LOD_Apply(), CSQCPlayer_SetMinsMaxs(), ctf_FlagThink(), DragBox_Think(), Ent_RemoveProjectile(), generator_draw(), IsFlying(), Monster_Spawn(), Monster_Spawn_Setup(), movelib_groundalign4point(), navigation_markroutes_nearestwaypoints(), navigation_shortenpath(), NET_HANDLE(), pathlib_astar(), PlayerDamage(), PlayerJump(), PlayerPostThink(), PM_check_hitground(), PM_check_slick(), PM_Footsteps(), relocate_spawnpoint(), Spawn_PreDraw(), steerlib_beamsteer(), SUB_NoImpactCheck(), sys_phys_simulate(), sys_phys_simulate_simple(), vehicle_altitude(), vehicles_damage(), vehicles_findgoodexit(), WarpZone_Camera_camera_transform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), and WarpZoneLib_ExactTrigger_Init().
vector mins
Definition at line 113 of file csprogsdefs.qc.
Referenced by _Movetype_CheckWater(), _Movetype_LinkEdict(), _Movetype_Physics_Walk(), _Movetype_PushEntityTrace(), _Movetype_TestEntityPosition(), buff_Respawn(), CopyBody(), CSQCModel_Hook_PreDraw(), CSQCPlayer_LOD_Apply(), CSQCPlayer_SetMinsMaxs(), ctf_FlagThink(), DragBox_Think(), Ent_RemoveProjectile(), generator_draw(), IsFlying(), Monster_Spawn(), navigation_markroutes_nearestwaypoints(), navigation_shortenpath(), NET_HANDLE(), pathlib_astar(), PlayerDamage(), PlayerJump(), PlayerPostThink(), PM_check_hitground(), PM_check_slick(), PM_Footsteps(), relocate_spawnpoint(), Spawn_PreDraw(), steerlib_beamsteer(), SUB_NoImpactCheck(), sys_phys_simulate(), sys_phys_simulate_simple(), vehicle_altitude(), vehicles_damage(), vehicles_findgoodexit(), WarpZone_Camera_camera_transform(), WarpZone_camera_transform(), WarpZone_Fade_PreDraw(), and WarpZoneLib_ExactTrigger_Init().
string model
Definition at line 108 of file csprogsdefs.qc.
Referenced by assault_wall_think(), ChatBubbleThink(), CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), CopyBody(), CSQCModel_AutoTagIndex_Apply(), CSQCModel_Hook_PostUpdate(), CSQCModel_Hook_PreDraw(), CSQCPlayer_FallbackFrame(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), CSQCPlayer_ModelAppearance_PreUpdate(), dompoint_captured(), dompointtouch(), GameCommand_animbench(), GameCommand_gettaginfo(), Monster_Sounds_Update(), monsters_animoverride(), player_getspecies(), PutObserverInServer(), PutPlayerInServer(), spawnfunc(), turret_die(), UpdatePlayerSounds(), and WarpZoneLib_ExactTrigger_Init().
float modelindex
Definition at line 91 of file csprogsdefs.qc.
Referenced by CL_Weaponentity_Think(), CopyBody(), CSQCModel_Hook_PreDraw(), CSQCPlayer_FallbackFrame(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_ModelAppearance_PostUpdate(), CSQCPlayer_ModelAppearance_PreUpdate(), dompoint_captured(), dompointtouch(), NET_HANDLE(), Portal_Customize(), spawnfunc(), and weapon_defaultspawnfunc().
vector modellight_ambient
Definition at line 762 of file csprogsdefs.qc.
vector modellight_diffuse
Definition at line 763 of file csprogsdefs.qc.
vector modellight_dir
Definition at line 764 of file csprogsdefs.qc.
const float MOVE_MISSILE = 2
Definition at line 254 of file csprogsdefs.qc.
const float MOVE_NOMONSTERS = 1
Definition at line 253 of file csprogsdefs.qc.
const float MOVE_NORMAL = 0
Definition at line 252 of file csprogsdefs.qc.
float MOVE_WORLDONLY = 3
Definition at line 1089 of file csprogsdefs.qc.
float movetype
Definition at line 98 of file csprogsdefs.qc.
Referenced by SV_OnEntityPreSpawnFunction().
float movevar_accelerate
Definition at line 68 of file csprogsdefs.qc.
float movevar_airaccelerate
Definition at line 69 of file csprogsdefs.qc.
float movevar_entgravity
Definition at line 73 of file csprogsdefs.qc.
float movevar_friction
Definition at line 71 of file csprogsdefs.qc.
float movevar_gravity
Definition at line 64 of file csprogsdefs.qc.
float movevar_maxspeed
Definition at line 66 of file csprogsdefs.qc.
float movevar_spectatormaxspeed
Definition at line 67 of file csprogsdefs.qc.
float movevar_stopspeed
Definition at line 65 of file csprogsdefs.qc.
float movevar_wateraccelerate
Definition at line 70 of file csprogsdefs.qc.
float movevar_waterfriction
Definition at line 72 of file csprogsdefs.qc.
string netname
Definition at line 125 of file csprogsdefs.qc.
float nextthink
Definition at line 121 of file csprogsdefs.qc.
Referenced by a_think(), AnimateDomPoint(), Announcer_Countdown(), assault_wall_think(), buff_Init(), buff_Think(), ChatBubbleThink(), CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), ClientInit_CheckUpdate(), CopyBody(), CopyBody_Think(), ctf_FlagThink(), dom_controlpoint_setup(), dompointthink(), door_go_up(), door_hit_top(), door_reset(), DragBox_Think(), fireburner_think(), GotoFirstMap(), GrapplingHook_Stop(), GrapplingHookThink(), Ice_Think(), ka_Handler_CheckBall(), ka_RespawnBall(), ka_TimeScoring(), ka_TouchEvent(), kh_Controller_Think(), kh_Key_Think(), KillIndicator_Think(), make_mapinfo_Think(), Monster_Appear_Check(), Monster_Damage(), Monster_Dead(), Monster_Dead_Damage(), Monster_Dead_Fade(), Monster_Dead_Think(), Monster_Delay_Action(), Monster_Spawn_Setup(), Monster_Think(), OnlineBanList_Think(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_Reset(), ons_ControlPoint_Think(), ons_DelayedLinkSetup(), ons_GeneratorDamage(), ons_GeneratorReset(), ons_GeneratorThink(), ons_Link_CheckUpdate(), physical_item_think(), PingPLReport_Think(), plas_think(), plat_hit_top(), Playerchecker_Think(), PlayerDamage(), Portal_Think(), PutObserverInServer(), PutPlayerInServer(), RandomSeed_Think(), relocate_spawnpoint(), round_handler_FirstThink(), round_handler_Reset(), round_handler_Spawn(), round_handler_Think(), RunThink(), shieldhit_think(), spawnfunc(), spawnpoint_think(), SUB_CalcAngleMove(), SUB_CalcAngleMoveDone(), SUB_CalcMove(), SUB_CalcMove_Bezier(), SUB_CalcMove_controller_think(), SUB_CalcMoveDone(), SUB_Friction(), SUB_SetFade_Think(), swampslug_think(), thrown_wep_think(), timeout_handler_think(), train_wait(), trigger_push_touch(), turret_gib_draw(), vehicle_initialize(), vehicle_use(), vehicles_gib_think(), vehicles_projectile_damage(), vehicles_spawn(), vehicles_think(), W_Nexball_Think(), W_PrepareExplosionByDamage(), and WarpZone_RefSys_GC().
vector oldorigin
Definition at line 102 of file csprogsdefs.qc.
Referenced by NET_HANDLE(), PutPlayerInServer(), and thrown_wep_think().
vector origin
Definition at line 101 of file csprogsdefs.qc.
entity other
Definition at line 14 of file csprogsdefs.qc.
Referenced by AnimHost::addAnim(), Keyframe::addAnim(), Keyframe::addEasing(), Container_addItem(), Container_moveItemAfter(), Container_setFocus(), ModalController_addTab(), and AnimHost::removeAnim().
entity owner
Definition at line 133 of file csprogsdefs.qc.
float particle_airfriction
Definition at line 671 of file csprogsdefs.qc.
float particle_alpha
Definition at line 666 of file csprogsdefs.qc.
float particle_alphafade
Definition at line 667 of file csprogsdefs.qc.
float particle_angle
Definition at line 684 of file csprogsdefs.qc.
float PARTICLE_BEAM = 3
Definition at line 656 of file csprogsdefs.qc.
float PARTICLE_BILLBOARD = 0
Definition at line 653 of file csprogsdefs.qc.
float particle_blendmode
Definition at line 659 of file csprogsdefs.qc.
float particle_bounce
Definition at line 670 of file csprogsdefs.qc.
vector particle_color1
Definition at line 661 of file csprogsdefs.qc.
vector particle_color2
Definition at line 662 of file csprogsdefs.qc.
float particle_delaycollision
Definition at line 683 of file csprogsdefs.qc.
float particle_delayspawn
Definition at line 682 of file csprogsdefs.qc.
float particle_gravity
Definition at line 669 of file csprogsdefs.qc.
float particle_liquidfriction
Definition at line 672 of file csprogsdefs.qc.
float particle_orientation
Definition at line 660 of file csprogsdefs.qc.
float PARTICLE_ORIENTED_DOUBLESIDED = 2
Definition at line 655 of file csprogsdefs.qc.
float particle_originjitter
Definition at line 673 of file csprogsdefs.qc.
float particle_qualityreduction
Definition at line 675 of file csprogsdefs.qc.
float particle_size
Definition at line 664 of file csprogsdefs.qc.
float particle_sizeincrease
Definition at line 665 of file csprogsdefs.qc.
float PARTICLE_SPARK = 1
Definition at line 654 of file csprogsdefs.qc.
float particle_spin
Definition at line 685 of file csprogsdefs.qc.
float particle_stainalpha
Definition at line 680 of file csprogsdefs.qc.
vector particle_staincolor1
Definition at line 677 of file csprogsdefs.qc.
vector particle_staincolor2
Definition at line 678 of file csprogsdefs.qc.
float particle_stainsize
Definition at line 681 of file csprogsdefs.qc.
float particle_staintex
Definition at line 679 of file csprogsdefs.qc.
float particle_stretch
Definition at line 676 of file csprogsdefs.qc.
float particle_tex
Definition at line 663 of file csprogsdefs.qc.
float particle_time
Definition at line 668 of file csprogsdefs.qc.
float particle_type
Definition at line 658 of file csprogsdefs.qc.
float particle_velocityjitter
Definition at line 674 of file csprogsdefs.qc.
float particles_alphamax
Definition at line 1449 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
float particles_alphamin
Definition at line 1449 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
vector particles_colormax
Definition at line 1451 of file csprogsdefs.qc.
vector particles_colormin
Definition at line 1451 of file csprogsdefs.qc.
float PARTICLES_DRAWASTRAIL = 128
Definition at line 1454 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
float particles_fade
Definition at line 1453 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
float PARTICLES_USEALPHA = 1
Definition at line 1448 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
float PARTICLES_USECOLOR = 2
Definition at line 1450 of file csprogsdefs.qc.
float PARTICLES_USEFADE = 4
Definition at line 1452 of file csprogsdefs.qc.
Referenced by Projectile_DrawTrail().
float PBLEND_ADD = 1
Definition at line 650 of file csprogsdefs.qc.
float PBLEND_ALPHA = 0
Definition at line 649 of file csprogsdefs.qc.
float PBLEND_INVMOD = 2
Definition at line 651 of file csprogsdefs.qc.
const float PFL_CROUCH = 2
Definition at line 312 of file csprogsdefs.qc.
const float PFL_DEAD = 4
Definition at line 313 of file csprogsdefs.qc.
const float PFL_GIBBED = 8
Definition at line 314 of file csprogsdefs.qc.
const float PFL_ONGROUND = 1
Definition at line 311 of file csprogsdefs.qc.
const float PFLAGS_CORONA = 2
Definition at line 297 of file csprogsdefs.qc.
const float PFLAGS_FULLDYNAMIC = 128
Definition at line 298 of file csprogsdefs.qc.
Referenced by buff_Customize(), buff_Init(), and buffs_BuffModel_Spawn().
const float PFLAGS_NOSHADOW = 1
Definition at line 296 of file csprogsdefs.qc.
float PI = 3.1415926535897932384626433832795028841971693993751058209749445923
Definition at line 963 of file csprogsdefs.qc.
Referenced by cpicon_draw(), and HUD_Physics().
float player_localentnum
Definition at line 19 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView(), CSQCModel_Draw(), CSQCPlayer_SetCamera(), Draw_ShowNames(), Hud_Dynamic_Frame(), minigame_player_entremove(), NET_HANDLE(), TrueAimCheck(), viewmodel_animate(), and viewmodel_draw().
float player_localnum
Definition at line 20 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView(), CSQCModel_Draw(), CSQCModel_Hook_PreDraw(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_PostUpdate(), HUD_InfoMessages(), HUD_MinigameMenu_ClickInvite(), HUD_Mod_Race(), HUD_Quickmenu_PlayerListEntries(), HUD_Score_Rankings(), NET_HANDLE(), Scoreboard_Draw(), Scoreboard_Rankings_Draw(), and turret_draw2d().
float PMF_DUCKED = 4
Definition at line 921 of file csprogsdefs.qc.
Referenced by CSQCPlayer_Physics().
float PMF_ONGROUND = 8
Definition at line 922 of file csprogsdefs.qc.
Referenced by CSQCPlayer_Physics().
vector pmove_maxs
Definition at line 57 of file csprogsdefs.qc.
vector pmove_mins
Definition at line 56 of file csprogsdefs.qc.
vector pmove_org
Definition at line 54 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView(), and WarpZone_FixPMove().
vector pmove_vel
Definition at line 55 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera(), GetCurrentFov(), and HUD_Physics().
float PRECACHE_PIC_FROMWAD = 1
Definition at line 1080 of file csprogsdefs.qc.
float PRECACHE_PIC_MIPMAP = 8
Definition at line 1082 of file csprogsdefs.qc.
Referenced by XonoticGametypeList_configureXonoticGametypeList().
float PRECACHE_PIC_NOTPERSISTENT = 2
Definition at line 1081 of file csprogsdefs.qc.
float PT_ALPHASTATIC = 1
Definition at line 636 of file csprogsdefs.qc.
float PT_BEAM = 4
Definition at line 639 of file csprogsdefs.qc.
float PT_BLOOD = 9
Definition at line 644 of file csprogsdefs.qc.
float PT_BUBBLE = 8
Definition at line 643 of file csprogsdefs.qc.
float PT_DECAL = 11
Definition at line 646 of file csprogsdefs.qc.
float PT_ENTITYPARTICLE = 12
Definition at line 647 of file csprogsdefs.qc.
float PT_RAIN = 5
Definition at line 640 of file csprogsdefs.qc.
float PT_RAINDECAL = 6
Definition at line 641 of file csprogsdefs.qc.
float PT_SMOKE = 10
Definition at line 645 of file csprogsdefs.qc.
float PT_SNOW = 7
Definition at line 642 of file csprogsdefs.qc.
float PT_SPARK = 3
Definition at line 638 of file csprogsdefs.qc.
float PT_STATIC = 2
Definition at line 637 of file csprogsdefs.qc.
float Q3SURFACEFLAG_FLESH = 64
Definition at line 1144 of file csprogsdefs.qc.
float Q3SURFACEFLAG_LADDER = 8
Definition at line 1141 of file csprogsdefs.qc.
float Q3SURFACEFLAG_METALSTEPS = 4096
Definition at line 1150 of file csprogsdefs.qc.
Referenced by PM_check_hitground(), and PM_Footsteps().
float Q3SURFACEFLAG_NODAMAGE = 1
Definition at line 1138 of file csprogsdefs.qc.
float Q3SURFACEFLAG_NODRAW = 128
Definition at line 1145 of file csprogsdefs.qc.
Referenced by fireBullet().
float Q3SURFACEFLAG_NOIMPACT = 16
Definition at line 1142 of file csprogsdefs.qc.
Referenced by CheatCommand(), ka_TouchEvent(), Porto_Draw(), SUB_NoImpactCheck(), and vehicles_impact().
float Q3SURFACEFLAG_NOMARKS = 32
Definition at line 1143 of file csprogsdefs.qc.
float Q3SURFACEFLAG_NONSOLID = 16384
Definition at line 1152 of file csprogsdefs.qc.
Referenced by fireBullet().
float Q3SURFACEFLAG_NOSTEPS = 8192
Definition at line 1151 of file csprogsdefs.qc.
Referenced by PM_check_hitground(), and PM_Footsteps().
float Q3SURFACEFLAG_SKY = 4
Definition at line 1140 of file csprogsdefs.qc.
Referenced by buff_Respawn(), CheatImpulse(), fireBullet(), ka_RespawnBall(), and location_isok().
float Q3SURFACEFLAG_SLICK = 2
Definition at line 1139 of file csprogsdefs.qc.
Referenced by PM_check_slick(), Porto_Draw(), and sys_phys_simulate().
float RAD2DEG = 57.2957795130823208767981548141051703324054724665643215491602438612
Definition at line 962 of file csprogsdefs.qc.
Referenced by ctf_CheckPassDirection(), IsMoveInDirection(), MUTATOR_HOOKFUNCTION(), and ons_Teleport().
float REFDEFFLAG_DEAD = 4
Definition at line 925 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera().
float REFDEFFLAG_INTERMISSION = 8
Definition at line 926 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera().
float REFDEFFLAG_JUMPING = 2
Definition at line 924 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera().
float REFDEFFLAG_TELEPORTED = 1
Definition at line 923 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SetCamera().
const float RF_ADDITIVE = 8
Definition at line 169 of file csprogsdefs.qc.
const float RF_DEPTHHACK = 4
Definition at line 168 of file csprogsdefs.qc.
float RF_DYNAMICMODELLIGHT = 8192
Definition at line 1459 of file csprogsdefs.qc.
Referenced by CSQCModel_Effects_Apply().
const float RF_EXTERNALMODEL = 2
Definition at line 167 of file csprogsdefs.qc.
const float RF_FULLBRIGHT = 256
Definition at line 1457 of file csprogsdefs.qc.
Referenced by CSQCModel_Effects_Apply().
const float RF_MODELLIGHT = 4096
Definition at line 761 of file csprogsdefs.qc.
const float RF_NOSHADOW = 512
Definition at line 1458 of file csprogsdefs.qc.
Referenced by CSQCModel_Effects_Apply().
const float RF_USEAXIS = 16
Definition at line 170 of file csprogsdefs.qc.
const float RF_VIEWMODEL = 1
Definition at line 166 of file csprogsdefs.qc.
const float RF_WORLDOBJECT = 128
Definition at line 754 of file csprogsdefs.qc.
entity self
Definition at line 13 of file csprogsdefs.qc.
float servercommandframe
Definition at line 24 of file csprogsdefs.qc.
Referenced by CSQCPlayer_SavePrediction(), and CSQCPlayer_SetCamera().
vector size
Definition at line 114 of file csprogsdefs.qc.
Referenced by AuxiliaryXhair_Draw2D(), DamageText::DamageText_draw2d(), HUD_Notify(), HUD_Powerups(), Item::resizeNotify(), and SUB_NoImpactCheck().
float skeletonindex
Definition at line 1239 of file csprogsdefs.qc.
Referenced by Ent_Remove().
float skin
Definition at line 110 of file csprogsdefs.qc.
float solid
Definition at line 99 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Walk(), _Movetype_PushEntity(), _Movetype_PushEntityTrace(), assault_wall_think(), buff_Init(), CopyBody(), cpicon_construct(), crosshair_trace_plusvisibletriggers__is_wz(), dom_controlpoint_setup(), generator_construct(), Monster_Dead(), Monster_Spawn(), NET_HANDLE(), ons_ControlPoint_Icon_BuildThink(), physical_item_think(), PlayerCorpseDamage(), PlayerDamage(), PlayerPostThink(), Portal_Think(), Portal_Touch(), PutObserverInServer(), PutPlayerInServer(), respawn(), spawnfunc(), sys_phys_simulate_simple(), teleport_findtarget(), turret_construct(), vehicles_spawn(), and WarpZoneLib_ExactTrigger_Init().
const float SOLID_BBOX = 2
Definition at line 246 of file csprogsdefs.qc.
const float SOLID_BSP = 4
Definition at line 248 of file csprogsdefs.qc.
const float SOLID_CORPSE = 5
Definition at line 249 of file csprogsdefs.qc.
const float SOLID_NOT = 0
Definition at line 244 of file csprogsdefs.qc.
const float SOLID_SLIDEBOX = 3
Definition at line 247 of file csprogsdefs.qc.
const float SOLID_TRIGGER = 1
Definition at line 245 of file csprogsdefs.qc.
float SOUNDFLAG_RELIABLE = 1
Definition at line 1053 of file csprogsdefs.qc.
const float STAT_ACTIVEWEAPON = 10
Definition at line 210 of file csprogsdefs.qc.
const float STAT_AMMO = 3
Definition at line 203 of file csprogsdefs.qc.
const float STAT_ARMOR = 4
Definition at line 204 of file csprogsdefs.qc.
const float STAT_CELLS = 9
Definition at line 209 of file csprogsdefs.qc.
const float STAT_FRAGLIMIT = 235
Definition at line 1444 of file csprogsdefs.qc.
const float STAT_HEALTH = 0
Definition at line 201 of file csprogsdefs.qc.
const float STAT_ITEMS = 15
Definition at line 215 of file csprogsdefs.qc.
const float STAT_MONSTERS = 14
Definition at line 214 of file csprogsdefs.qc.
const float STAT_MOVEVARS_GRAVITY = 242
Definition at line 1446 of file csprogsdefs.qc.
const float STAT_MOVEVARS_TICRATE = 240
Definition at line 1442 of file csprogsdefs.qc.
const float STAT_MOVEVARS_TIMESCALE = 241
Definition at line 1443 of file csprogsdefs.qc.
const float STAT_NAILS = 7
Definition at line 207 of file csprogsdefs.qc.
const float STAT_ROCKETS = 8
Definition at line 208 of file csprogsdefs.qc.
const float STAT_SECRETS = 13
Definition at line 213 of file csprogsdefs.qc.
const float STAT_SHELLS = 6
Definition at line 206 of file csprogsdefs.qc.
const float STAT_TIMELIMIT = 236
Definition at line 1445 of file csprogsdefs.qc.
const float STAT_TOTALMONSTERS = 12
Definition at line 212 of file csprogsdefs.qc.
const float STAT_TOTALSECRETS = 11
Definition at line 211 of file csprogsdefs.qc.
const float STAT_VIEWHEIGHT = 16
Definition at line 216 of file csprogsdefs.qc.
const float STAT_WEAPONFRAME = 5
Definition at line 205 of file csprogsdefs.qc.
const float STAT_WEAPONMODEL = 2
Definition at line 202 of file csprogsdefs.qc.
const float TE_EXPLOSION = 3
Definition at line 278 of file csprogsdefs.qc.
const float TE_EXPLOSION2 = 12
Definition at line 287 of file csprogsdefs.qc.
const float TE_EXPLOSIONQUAD = 70
Definition at line 291 of file csprogsdefs.qc.
const float TE_EXPLOSIONRGB = 53
Definition at line 289 of file csprogsdefs.qc.
const float TE_GUNSHOT = 2
Definition at line 277 of file csprogsdefs.qc.
const float TE_GUNSHOTQUAD = 57
Definition at line 290 of file csprogsdefs.qc.
const float TE_KNIGHTSPIKE = 8
Definition at line 283 of file csprogsdefs.qc.
const float TE_LAVASPLASH = 10
Definition at line 285 of file csprogsdefs.qc.
const float TE_LIGHTNING1 = 5
Definition at line 280 of file csprogsdefs.qc.
const float TE_LIGHTNING2 = 6
Definition at line 281 of file csprogsdefs.qc.
const float TE_LIGHTNING3 = 9
Definition at line 284 of file csprogsdefs.qc.
const float TE_SPIKE = 0
Definition at line 275 of file csprogsdefs.qc.
const float TE_SPIKEQUAD = 58
Definition at line 292 of file csprogsdefs.qc.
const float TE_SUPERSPIKE = 1
Definition at line 276 of file csprogsdefs.qc.
const float TE_SUPERSPIKEQUAD = 59
Definition at line 293 of file csprogsdefs.qc.
const float TE_TAREXPLOSION = 4
Definition at line 279 of file csprogsdefs.qc.
const float TE_TELEPORT = 11
Definition at line 286 of file csprogsdefs.qc.
const float TE_WIZSPIKE = 7
Definition at line 282 of file csprogsdefs.qc.
float time
Definition at line 16 of file csprogsdefs.qc.
Referenced by a_think(), accuracy_add(), accuracy_isgooddamage(), Accuracy_LoadColors(), anim_set(), anim_update(), AnimateDomPoint(), animdecide_getloweranim(), animdecide_getupperanim(), animdecide_setaction(), animdecide_setimplicitstate(), animdecide_setstate(), Announcer_Countdown(), Announcer_Gamestart(), Announcer_Time(), anticheat_physics(), antilag_record(), antilag_takeback_all(), AppendItemcodes(), assault_new_round(), assault_wall_think(), AuxiliaryXhair_Draw2D(), Ban_Insert(), Ban_IsClientBanned(), Ban_LoadBans(), Ban_SaveBans(), Ban_View(), bobmodel_ofs(), bot_aimdir(), bot_clientconnect(), bot_cmd_aim(), bot_cmd_aimtarget(), bot_cmd_debug_assert_canfire(), bot_cmd_wait(), bot_cmd_wait_until(), bot_fixcount(), bot_serverframe(), bot_think(), botframe_showwaypointlinks(), buff_Customize(), buff_Effect(), buff_Init(), buff_Respawn(), buff_SetCooldown(), buff_Think(), buff_Touch(), CA_CheckWinner(), calc_followmodel_ofs(), calculate_player_respawn_time(), CampaignPreIntermission(), changematchtime(), ChatBubbleThink(), CheatCommand(), CheatImpulse(), CheckRules_World(), checkSpectatorBlock(), CheckWaterJump(), CL_ExteriorWeaponentity_Think(), CL_SpawnWeaponentity(), CL_Weaponentity_Think(), client_hasweapon(), ClientCommand_ready(), ClientConnect(), ClientInit_CheckUpdate(), ClientKill_Silent(), ClientKill_TeamChange(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), conveyor_think(), CopyBody(), CopyBody_Think(), cpicon_construct(), cpicon_damage(), cpicon_draw(), CreatureFrame_All(), CreatureFrame_hotliquids(), CreatureFrame_Liquids(), crosshair_getcolor(), CSQC_Ent_Update(), CSQC_UpdateView(), CSQCModel_CheckUpdate(), CSQCModel_Effects_Apply(), CSQCModel_InterpolateAnimation_1To2_Do(), CSQCModel_InterpolateAnimation_1To2_Note(), CSQCModel_InterpolateAnimation_2To4_Do(), CSQCModel_InterpolateAnimation_2To4_Note(), CSQCPlayer_GetPredictionErrorO(), CSQCPlayer_GetPredictionErrorV(), CSQCPlayer_ModelAppearance_Apply(), CSQCPlayer_SetPredictionError(), CSQCProjectile_SendEntity(), ctf_CaptureRecord(), ctf_CheckFlagReturn(), ctf_CheckStalemate(), ctf_FlagSetup(), ctf_FlagThink(), ctf_Handle_Capture(), ctf_Handle_Drop(), ctf_Handle_Pickup(), ctf_Handle_Retrieve(), ctf_Handle_Return(), ctf_Handle_Throw(), ctf_RespawnFlag(), Damage(), DamageText::DamageText_draw2d(), DamageText::DamageText_update(), DecodeLevelParms(), dom_controlpoint_setup(), dom_spawnpoint(), Domination_CheckWinner(), dompoint_captured(), dompointthink(), dompointtouch(), door_check_keys(), door_touch(), door_trigger_touch(), DragBox_Think(), Draw_ShowNames(), draw_teamradar_icon(), DrawDebugModel(), DrownPlayer(), dumpnode(), DumpStats(), EndFrame(), Fire_AddDamage(), Fire_ApplyDamage(), Fire_IsBurning(), fireburner_think(), FireGrapplingHook(), FixIntermissionClient(), forbidWeaponUse(), formatmessage(), Freeze(), freezetag_CheckWinner(), freezetag_Freeze(), func_ladder_touch(), GameCommand_make_mapinfo(), GameCommand_nospectators(), GameTypeVote_Start(), generator_construct(), generator_draw(), generic_plat_blocked(), GenericCommand_rpn(), GiveResource(), GotoFirstMap(), GrapplingHook_Damage(), GrapplingHook_Stop(), GrapplingHookThink(), havocbot_aim(), havocbot_bunnyhop(), havocbot_checkgoaldistance(), havocbot_chooseenemy(), havocbot_chooseweapon(), havocbot_ctf_reset_role(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_keyboard_movement(), havocbot_moveto(), havocbot_movetogoal(), havocbot_role_ast_defense(), havocbot_role_ast_offense(), havocbot_role_ctf_carrier(), havocbot_role_ctf_defense(), havocbot_role_ctf_escort(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), havocbot_role_ctf_setrole(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_kh_defense(), havocbot_role_kh_freelancer(), havocbot_role_kh_offense(), havocbot_role_ons_offense(), HitSound(), HUD_Ammo(), HUD_CenterPrint(), HUD_Chat(), HUD_Configure_Frame(), HUD_Crosshair(), Hud_Dynamic_Frame(), HUD_Get_Num_Color(), HUD_HealthArmor(), HUD_InfoMessages(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_NexBall(), HUD_Mod_Race(), HUD_Notify(), HUD_Notify_Push(), HUD_Panel_Arrow_Action(), HUD_Panel_InputEvent(), HUD_Panel_LoadCvars(), HUD_Panel_Mouse(), HUD_Physics(), HUD_Powerups(), HUD_QuickMenu(), HUD_RaceTimer(), HUD_Radar(), Hud_Shake_Update(), HUD_Timer(), HUD_Vote(), HUD_Weapons(), Ice_Think(), Image_setZoom(), img_select(), InitiateSuddenDeath(), InputBox_draw(), InputBox_keyDown(), InputBox_mouseDrag(), instagib_ammocheck(), IntermissionThink(), InterpolateOrigin_Do(), InterpolateOrigin_Note(), Invasion_CheckWinner(), invasion_PickSpawn(), Item_InitializeLoot(), joinAllowed(), jumppad_push(), ka_DropEvent(), ka_Handler_CheckBall(), ka_Initialize(), ka_RespawnBall(), ka_TimeScoring(), ka_TouchEvent(), kh_Controller_SetThink(), kh_Controller_Think(), kh_Key_AssignTo(), kh_Key_Attach(), kh_Key_Damage(), kh_Key_Detach(), kh_Key_DropAll(), kh_Key_DropOne(), kh_Key_Spawn(), kh_Key_Think(), kh_Key_Touch(), kh_StartRound(), kh_WaitForPlayers(), KillIndicator_Think(), lag_update(), ListBox_mouseRelease(), LocalCommand_blurtest(), m_draw(), m_play_focus_sound(), make_mapinfo_Think(), makeHostedEasing(), makeKeyframe(), MapVote_CheckRules_2(), MapVote_Draw(), MapVote_Init(), MapVote_Think(), MapVote_UpdateMask(), Monster_Attack_Check(), Monster_Attack_Leap(), Monster_Attack_Leap_Check(), Monster_Attack_Melee(), Monster_Damage(), Monster_Dead(), Monster_Dead_Damage(), Monster_Dead_Fade(), Monster_Dead_Think(), Monster_Delay(), Monster_Delay_Action(), monster_dropitem(), Monster_Move(), Monster_Move_2D(), Monster_Move_Target(), Monster_Sound(), Monster_Spawn(), Monster_Spawn_Setup(), Monster_Think(), Monster_ValidTarget(), InputBox::mousePress(), Movetype_Physics_MatchTicrate(), Movetype_Physics_NoMatchServer(), Movetype_Physics_NoMatchTicrate(), MUTATOR_HOOKFUNCTION(), navigation_dynamicgoal_init(), navigation_dynamicgoal_set(), navigation_goalrating_timeout(), navigation_goalrating_timeout_can_be_anticipated(), navigation_goalrating_timeout_expire(), navigation_goalrating_timeout_set(), navigation_poptouchedgoals(), navigation_shortenpath(), NET_HANDLE(), NextLevel(), NIX_GiveCurrentWeapon(), nJoinAllowed(), Obituary(), OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Heal(), ons_ControlPoint_Icon_Spawn(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_Reset(), ons_ControlPoint_Setup(), ons_ControlPoint_Think(), ons_ControlPoint_Touch(), ons_DelayedLinkSetup(), ons_generator_ray_draw(), ons_generator_ray_spawn(), ons_GeneratorDamage(), ons_GeneratorReset(), ons_GeneratorSetup(), ons_GeneratorThink(), ons_Link_CheckUpdate(), ons_Teleport(), Onslaught_CheckWinner(), onslaught_controlpoint_icon_link(), pathlib_deletepath(), pathlib_mknode(), pathlib_walknode(), pathlib_waypointpath_autostep(), physical_item_think(), Physics_Frame(), PingPLReport_Spawn(), PingPLReport_Think(), plas_think(), play_countdown(), player_powerups(), player_regen(), Playerchecker_Think(), PlayerCorpseDamage(), PlayerDamage(), PlayerJump(), PlayerPostThink(), PlayerPreThink(), PlayerThink(), PM_check_hitground(), PM_check_nickspam(), PM_dodging_checkpressedkeys(), PM_Footsteps(), PM_jetpack(), Portal_Connect(), Portal_MakeInPortal(), Portal_Remove(), Portal_RemoveLater(), Portal_Spawn(), Portal_TeleportPlayer(), Portal_Think(), Portal_Touch(), PostInit(), preMenuDraw(), PrintWelcomeMessage(), Projectile_Draw(), Projectile_DrawTrail(), Projectile_ResetTrail(), Promise_sleep(), PutObserverInServer(), PutPlayerInServer(), QuickMenu_ActionForNumber(), QuickMenu_Open(), QuickMenu_Page_ActiveEntry(), QuickMenu_Page_Load(), race_ImposePenaltyTime(), race_SendNextCheckpoint(), race_SendTime(), race_setTime(), RandomSeed_Think(), readlevelcvars(), ReadyRestart_force(), RedirectionThink(), REGISTER_MUTATOR(), relocate_spawnpoint(), reset_map(), respawn(), round_handler_FirstThink(), round_handler_Spawn(), round_handler_Think(), RunThink(), sandbox_ObjectFunction_Touch(), sandbox_ObjectSpawn(), SaveHUDSkin_Click(), Say(), Scoreboard_Draw(), ScreenshotList_Filter_Would_Change(), SetChangeParms(), shieldhit_think(), ShowRespawnCountdown(), spawnfunc(), spawnpoint_think(), SpecialCommand(), StartFrame(), SUB_CalcMove_Bezier(), SUB_CalcMove_controller_think(), SUB_Friction(), SUB_SetFade_Think(), SUB_UseTargets_Ex(), SV_ParseClientCommand_floodcheck(), swamp_touch(), swampslug_think(), sys_phys_monitor(), sys_phys_override(), sys_phys_postupdate(), sys_phys_pregame_hold(), sys_phys_simulate(), sys_phys_update(), systems_update(), target_init_use(), TeleportPlayer(), TEST(), thrown_wep_think(), AnimHost::tickAll(), timeout_handler_think(), train_wait(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), trigger_keylock_touch(), trigger_push_touch(), turret_draw(), turret_draw2d(), turret_gib_draw(), turret_gibtoss(), Unfreeze(), Animation::update(), UpdateChatBubble(), vehicle_initialize(), vehicle_tossgib(), vehicle_use(), vehicles_clearreturn(), vehicles_crushable(), vehicles_damage(), Vehicles_drawHUD(), vehicles_enter(), vehicles_exit(), vehicles_gib_think(), vehicles_impact(), vehicles_locktarget(), vehicles_painframe(), vehicles_projectile(), vehicles_projectile_damage(), vehicles_regen(), vehicles_regen_resource(), vehicles_return(), vehicles_setreturn(), vehicles_showwp(), vehicles_spawn(), vehicles_think(), vehicles_touch(), viewloc_PlayerPhysics(), viewmodel_draw(), VoteCommand_call(), VoteCommand_master(), VoteStop(), VoteThink(), W_HitPlotAnalysis(), W_Nexball_Attack2(), W_Nexball_Think(), W_Nexball_Touch(), W_PlayStrengthSound(), W_PrepareExplosionByDamage(), W_Reload(), W_ThrowNewWeapon(), W_WeaponFrame(), WarpZone_Projectile_Touch(), WarpZone_RefSys_CheckCreate(), WarpZone_RefSys_GC(), WarpZone_Teleport(), WarpZone_TeleportPlayer(), WarpZone_Touch(), waypoint_schedulerelink(), weapon_prepareattack_check(), weapon_prepareattack_do(), weapon_thinkf(), WinningCondition_Assault(), XonoticCreditsDialog_focusEnter(), XonoticCreditsList_draw(), XonoticHUDSkinList_draw(), XonoticMapList_keyDown(), XonoticPlayList_drawListBoxItem(), XonoticProfileTab_draw(), XonoticScreenshotImage_draw(), XonoticScreenshotImage_load(), XonoticScreenshotList_draw(), XonoticScreenshotList_setSelected(), XonoticScreenshotList_startSlideShow(), XonoticServerList_focusEnter(), and XonoticStatsList_getStats().
float trace_allsolid
Definition at line 34 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), sys_phys_simulate_simple(), vehicles_findgoodexit(), and WarpZone_Projectile_Touch().
float trace_dphitcontents
Definition at line 1120 of file csprogsdefs.qc.
Referenced by fireBullet(), MoveToRandomLocationWithinBounds(), Porto_Draw(), SUB_NoImpactCheck(), sys_phys_simulate_simple(), WarpZone_Projectile_Touch(), and WarpZone_TraceBox_ThroughZone().
float trace_dphitq3surfaceflags
Definition at line 1121 of file csprogsdefs.qc.
Referenced by CheatCommand(), fireBullet(), FireRailgunBullet(), ka_TouchEvent(), location_isok(), MoveToRandomLocationWithinBounds(), PM_check_hitground(), PM_check_slick(), PM_Footsteps(), Porto_Draw(), SUB_NoImpactCheck(), sys_phys_simulate(), sys_phys_simulate_simple(), vehicles_impact(), and WarpZone_Projectile_Touch().
string trace_dphittexturename
Definition at line 1122 of file csprogsdefs.qc.
Referenced by MoveToRandomLocationWithinBounds(), sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
float trace_dpstartcontents
Definition at line 1119 of file csprogsdefs.qc.
Referenced by sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
vector trace_endpos
Definition at line 37 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_PushEntity(), _Movetype_TestEntityPosition(), beamsweep(), bot_aimdir(), botframe_autowaypoints_fix(), botframe_autowaypoints_fix_from(), buff_Respawn(), CheatCommand(), CommonCommand_editmob(), CSQC_UpdateView(), ctf_CalculatePassVelocity(), Drag(), EnemyHitCheck(), Ent_RemoveProjectile(), findtrajectorywithleading(), fireBullet(), FireRailgunBullet(), formatmessage(), GameCommand_bbox(), GameCommand_trace(), IMPULSE(), Monster_CalculateVelocity(), Monster_Spawn(), movelib_groundalign4point(), MoveToRandomLocationWithinBounds(), Movetype_Physics_MatchTicrate(), navigation_routerating(), pathlib_walknode(), pathlib_wateroutnode(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_TeleportPlayer(), Porto_Draw(), sandbox_ObjectSpawn(), set_tracewalk_dest(), spawnfunc(), sys_phys_simulate_simple(), tile_check_cross(), tile_check_plus(), tile_check_plus2(), tracewalk(), trigger_push_test(), TrueAimCheck(), vehicle_altitude(), vehicle_initialize(), W_HitPlotAnalysis(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_Camera_camera_transform(), WarpZone_camera_transform(), WarpZone_FindRadius_Recurse(), WarpZone_Projectile_Touch(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), and waypoint_fixorigin_down_dir().
entity trace_ent
Definition at line 40 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Toss(), _Movetype_PushEntity(), bot_aim(), CommonCommand_editmob(), ctf_FlagThink(), Drag(), Draw_ShowNames(), EnemyHitCheck(), findtrajectorywithleading(), fireBullet(), FireRailgunBullet(), formatmessage(), havocbot_chooseenemy(), havocbot_gettarget(), havocbot_goalrating_kh(), Monster_Attack_Leap_Check(), Monster_Attack_Melee(), Monster_Move_2D(), Monster_Move_Target(), Monster_ValidTarget(), navigation_routetogoal(), navigation_shortenpath(), Portal_Think_TryTeleportPlayer(), RadiusDamageForSource(), sandbox_ObjectEdit_Get(), sys_phys_simulate_simple(), tracewalk(), trigger_push_test(), vehicles_locktarget(), W_HitPlotAnalysis(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_Projectile_Touch(), WarpZone_Projectile_Touch_ImpactFilter_Callback(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), and WarpZoneLib_BoxTouchesBrush_Recurse().
float trace_fraction
Definition at line 36 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Toss(), _Movetype_PushEntity(), beamsweep(), bot_aim(), botframe_autowaypoints_fixdown(), botframe_updatedangerousobjects(), CheatCommand(), CheckWaterJump(), CSQC_UpdateView(), CSQCModel_Hook_PreDraw(), ctf_CalculatePassVelocity(), ctf_FlagThink(), Draw_ShowNames(), fireBullet(), FireRailgunBullet(), GameCommand_trace(), havocbot_ai(), havocbot_chooseenemy(), havocbot_gettarget(), havocbot_goalrating_kh(), havocbot_movetogoal(), IsFlying(), Monster_CalculateVelocity(), Monster_Move_2D(), Monster_Move_Target(), Monster_ValidTarget(), movelib_groundalign4point(), MoveToRandomLocationWithinBounds(), MUTATOR_HOOKFUNCTION(), navigation_checkladders(), navigation_poptouchedgoals(), navigation_waypoint_will_link(), ons_camSetup(), ons_Teleport(), pathlib_flynode(), pathlib_swimnode(), pathlib_walknode(), pathlib_wateroutnode(), PlayerJump(), Portal_Touch(), RadiusDamageForSource(), steerlib_beamsteer(), steerlib_traceavoid(), steerlib_traceavoid_flat(), SUB_NoImpactCheck(), sys_phys_simulate_simple(), tracewalk(), vehicles_findgoodexit(), vehicles_force_fromtag_hover(), vehicles_force_fromtag_maglev(), WarpZone_FindRadius_Recurse(), WarpZone_Projectile_Touch(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_MoveOutOfSolid_Expand(), and waypoint_fixorigin_down_dir().
float trace_inopen
Definition at line 41 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
float trace_inwater
Definition at line 42 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
float trace_networkentity
Definition at line 1456 of file csprogsdefs.qc.
Referenced by Draw_ShowNames(), EnemyHitCheck(), and WarpZoneLib_BoxTouchesBrush_Recurse().
float trace_plane_dist
Definition at line 39 of file csprogsdefs.qc.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
vector trace_plane_normal
Definition at line 38 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Toss(), CheatCommand(), checkpoint_passed(), CheckWaterJump(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Porto_Draw(), sys_phys_simulate_simple(), and WarpZone_Projectile_Touch().
float trace_startsolid
Definition at line 35 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), _Movetype_PushEntity(), _Movetype_TestEntityPosition(), CheatCommand(), CheatImpulse(), CSQC_UpdateView(), CSQCModel_Hook_PreDraw(), ctf_FlagThink(), GameCommand_bbox(), GameCommand_trace(), MoveToRandomLocationWithinBounds(), Movetype_Physics_MatchTicrate(), MUTATOR_HOOKFUNCTION(), ons_Teleport(), PM_ClientMovement_UpdateStatus(), Portal_TeleportPlayer(), relocate_spawnpoint(), set_tracewalk_dest(), sys_phys_simulate(), sys_phys_simulate_simple(), tracewalk(), turret_gibtoss(), vehicles_findgoodexit(), W_Nexball_Attack(), WarpZone_Projectile_Touch(), WarpZone_Teleport(), WarpZone_TraceBox_ThroughZone(), WarpZoneLib_MoveOutOfSolid(), WarpZoneLib_MoveOutOfSolid_Expand(), and waypoint_fixorigin_down_dir().
float transparent_offset
Definition at line 746 of file csprogsdefs.qc.
const float true = 1
Definition at line 257 of file csprogsdefs.qc.
const float TRUE = 1
Definition at line 259 of file csprogsdefs.qc.
vector v_forward
Definition at line 31 of file csprogsdefs.qc.
Referenced by AnglesTransform_Apply(), AnglesTransform_Invert(), AnglesTransform_Multiply(), animdecide_setimplicitstate(), anticheat_physics(), attach_sameorigin(), bot_aim(), bot_aimdir(), CheatCommand(), CheatImpulse(), CheckWaterJump(), CommonCommand_editmob(), CSQC_UpdateView(), ctf_CheckPassDirection(), ctf_Handle_Throw(), detach_sameorigin(), Drag_Begin(), Drag_Update(), draw_teamradar_player(), GetCurrentFov(), GrapplingHookThink(), havocbot_movetogoal(), IMPULSE(), InterpolateOrigin_Note(), is_close_to_wall(), kh_AttachedOrigin(), kh_Key_DropAll(), kh_Key_DropOne(), kh_Key_Think(), Monster_Attack_Melee(), Monster_Move_2D(), Monster_Move_Target(), Monster_ValidTarget(), movelib_groundalign4point(), ons_Teleport(), PM_dodging(), PM_jetpack(), Portal_ApplyTransformToPlayerAngle(), Portal_FindSafeOrigin(), Portal_Remove(), Portal_Spawn(), Portal_TeleportPlayer(), Portal_Think_TryTeleportPlayer(), Portal_Touch(), Porto_Draw(), Projectile_Draw(), relocate_spawnpoint(), sandbox_ObjectSpawn(), skel_set_boneabs(), skeleton_from_frames(), steerlib_beamsteer(), steerlib_traceavoid(), steerlib_traceavoid_flat(), steerlib_wander(), sys_phys_simulate(), TeleportPlayer(), vehicles_force_fromtag_hover(), vehicles_force_fromtag_maglev(), W_SetupShot_Dir_ProjectileSize_Range(), W_WeaponFrame(), WarpZone_camera_transform(), WarpZone_PostInitialize_Callback(), WarpZone_PostTeleportPlayer_Callback(), WarpZone_SetUp(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), WarpZoneLib_ExactTrigger_Init(), and weapon_thinkf().
vector v_right
Definition at line 31 of file csprogsdefs.qc.
Referenced by AnglesTransform_Apply(), AnglesTransform_Invert(), animdecide_setimplicitstate(), attach_sameorigin(), CSQC_UpdateView(), Drag_Begin(), Drag_Update(), draw_teamradar_player(), GrapplingHookThink(), havocbot_movetogoal(), is_close_to_wall(), kh_AttachedOrigin(), movelib_groundalign4point(), PlayerDamage(), PM_dodging(), PM_jetpack(), Portal_Spawn(), Portal_TeleportPlayer(), Porto_Draw(), Projectile_Draw(), steerlib_beamsteer(), steerlib_traceavoid(), steerlib_traceavoid_flat(), sys_phys_simulate(), W_SetupShot_Dir_ProjectileSize_Range(), W_WeaponFrame(), WarpZone_camera_transform(), WarpZone_PostInitialize_Callback(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), and weapon_thinkf().
vector v_up
Definition at line 31 of file csprogsdefs.qc.
Referenced by AnglesTransform_Apply(), AnglesTransform_Invert(), AnglesTransform_Multiply(), attach_sameorigin(), CSQC_UpdateView(), detach_sameorigin(), Drag_Begin(), Drag_Update(), draw_teamradar_player(), FireGrapplingHook(), GrapplingHookThink(), InterpolateOrigin_Note(), is_close_to_ground(), kh_AttachedOrigin(), movelib_groundalign4point(), PM_dodging(), Portal_ApplyTransformToPlayerAngle(), Portal_Spawn(), Portal_TeleportPlayer(), Porto_Draw(), Projectile_Draw(), skel_set_boneabs(), skeleton_from_frames(), steerlib_traceavoid(), W_SetupShot_Dir_ProjectileSize_Range(), W_WeaponFrame(), WarpZone_camera_transform(), WarpZone_PostInitialize_Callback(), WarpZone_TraceBox_ThroughZone(), WarpZone_TraceToss_ThroughZone(), and weapon_thinkf().
const vector VEC_0 = '0 0 0'
Definition at line 266 of file csprogsdefs.qc.
const vector VEC_1 = '1 1 1'
Definition at line 265 of file csprogsdefs.qc.
vector VEC_HULL_MAX = '16 16 32'
Definition at line 272 of file csprogsdefs.qc.
vector VEC_HULL_MIN = '-16 -16 -24'
Definition at line 271 of file csprogsdefs.qc.
const vector VEC_M1 = '-1 -1 -1'
Definition at line 267 of file csprogsdefs.qc.
vector velocity
Definition at line 103 of file csprogsdefs.qc.
Referenced by _Movetype_FlyMove(), _Movetype_Physics_ClientFrame(), _Movetype_Physics_Frame(), _Movetype_Physics_Toss(), _Movetype_Physics_Walk(), bot_cmd_eval(), buff_Respawn(), CheatImpulse(), CopyBody(), CPM_PM_Aircontrol(), CreatureFrame_FallDamage(), CSQCPlayer_PredictTo(), CSQCPlayer_SavePrediction(), CSQCPlayer_Unpredict(), CSQCProjectile_SendEntity(), ctf_FlagThink(), door_reset(), Ent_RemoveProjectile(), formatmessage(), GrapplingHook_Stop(), havocbot_aim(), havocbot_bunnyhop(), havocbot_movetogoal(), IMPULSE(), InterpolateOrigin_Do(), InterpolateOrigin_Note(), InterpolateOrigin_Undo(), ka_RespawnBall(), ka_TouchEvent(), Monster_Attack_Leap(), Monster_Attack_Leap_Check(), Monster_CalculateVelocity(), Monster_Damage(), Monster_Dead(), Monster_Move(), Monster_Move_2D(), Monster_Reset(), Monster_Spawn(), Movetype_Physics_MatchTicrate(), navigation_poptouchedgoals(), NET_HANDLE(), PlayerJump(), PM_Accelerate(), PM_AirAccelerate(), PM_check_frozen(), PM_ClientMovement_UpdateStatus(), PM_dodging(), PM_dodging_checkpressedkeys(), PM_Footsteps(), PM_jetpack(), Projectile_Draw(), Projectile_DrawTrail(), PutObserverInServer(), PutPlayerInServer(), respawn(), sandbox_ObjectFunction_Touch(), SpectateCopy(), SUB_CalcMove(), SUB_CalcMove_Bezier(), SUB_CalcMoveDone(), SUB_Friction(), SUB_NoImpactCheck(), SUB_Stop(), sys_phys_land(), sys_phys_postupdate(), sys_phys_pregame_hold(), sys_phys_simulate(), sys_phys_simulate_simple(), sys_phys_update(), turret_die(), turret_gibboom(), vehicles_damage(), vehicles_impact(), vehicles_painframe(), vehicles_projectile_damage(), vehicles_reset_colors(), vehicles_spawn(), vehicles_touch(), W_Nexball_Think(), W_Nexball_Touch(), and WantEventchase().
const float VF_ANGLES = 15
Definition at line 186 of file csprogsdefs.qc.
const float VF_ANGLES_X = 16
Definition at line 187 of file csprogsdefs.qc.
const float VF_ANGLES_Y = 17
Definition at line 188 of file csprogsdefs.qc.
const float VF_ANGLES_Z = 18
Definition at line 189 of file csprogsdefs.qc.
const float VF_CL_VIEWANGLES = 33
Definition at line 194 of file csprogsdefs.qc.
const float VF_CL_VIEWANGLES_X = 34
Definition at line 195 of file csprogsdefs.qc.
const float VF_CL_VIEWANGLES_Y = 35
Definition at line 196 of file csprogsdefs.qc.
const float VF_CL_VIEWANGLES_Z = 36
Definition at line 197 of file csprogsdefs.qc.
const float VF_DRAWCROSSHAIR = 21
Definition at line 192 of file csprogsdefs.qc.
const float VF_DRAWENGINESBAR = 20
Definition at line 191 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView().
const float VF_DRAWWORLD = 19
Definition at line 190 of file csprogsdefs.qc.
const float VF_FOV = 8
Definition at line 179 of file csprogsdefs.qc.
const float VF_FOVX = 9
Definition at line 180 of file csprogsdefs.qc.
const float VF_FOVY = 10
Definition at line 181 of file csprogsdefs.qc.
const float VF_MAINVIEW = 400
Definition at line 899 of file csprogsdefs.qc.
const float VF_MIN = 1
Definition at line 172 of file csprogsdefs.qc.
const float VF_MIN_X = 2
Definition at line 173 of file csprogsdefs.qc.
const float VF_MIN_Y = 3
Definition at line 174 of file csprogsdefs.qc.
const float VF_MINFPS_QUALITY = 401
Definition at line 910 of file csprogsdefs.qc.
Referenced by CSQC_UpdateView().
const float VF_ORIGIN = 11
Definition at line 182 of file csprogsdefs.qc.
const float VF_ORIGIN_X = 12
Definition at line 183 of file csprogsdefs.qc.
const float VF_ORIGIN_Y = 13
Definition at line 184 of file csprogsdefs.qc.
const float VF_ORIGIN_Z = 14
Definition at line 185 of file csprogsdefs.qc.
const float VF_PERSPECTIVE = 200
Definition at line 199 of file csprogsdefs.qc.
const float VF_SIZE = 4
Definition at line 175 of file csprogsdefs.qc.
const float VF_SIZE_X = 6
Definition at line 177 of file csprogsdefs.qc.
const float VF_SIZE_Y = 5
Definition at line 176 of file csprogsdefs.qc.
const float VF_VIEWPORT = 7
Definition at line 178 of file csprogsdefs.qc.
vector view_angles
Definition at line 150 of file csprogsdefs.qc.
Referenced by calc_followmodel_ofs(), CSQC_UpdateView(), CSQCPlayer_Physics(), CSQCPlayer_PredictTo(), GetCurrentFov(), HUD_Radar(), leanmodel_ofs(), LocalCommand_create_scrshot_ent(), LocalCommand_debugmodel(), and Porto_Draw().
vector view_punchangle
Definition at line 151 of file csprogsdefs.qc.
vector view_punchvector
Definition at line 152 of file csprogsdefs.qc.
entity world
Definition at line 15 of file csprogsdefs.qc.
Referenced by __spawn(), bot_execute_commands_once(), ClientConnect(), ClientInit_misc(), fireBullet(), GameCommand_bbox(), GameCommand_trace(), InitGameplayMode(), MoveToRandomMapLocation(), and Spawn_Score().