Xonotic: common/mutators/mutator/buffs/buffs.qc File Reference
buffs.qc File Reference
#include "buffs.qh"
Functions
entity buff_FirstFromFlags (int _buffs)
string BUFF_NAME (int i)
Function Documentation
buff_FirstFromFlags()
entity buff_FirstFromFlags (int _buffs)
Definition at line 9 of file buffs.qc.
References flags, and FOREACH.
Referenced by buff_Init(), buff_Think(), buff_Touch(), buff_Waypoint_Spawn(), MUTATOR_HOOKFUNCTION(), Obituary(), and target_init_use().
 {
     if (flags)
     {
         FOREACH(Buffs, it.m_itemid & _buffs, { return it; });
     }
     return BUFF_Null;
 }
BUFF_NAME()
string BUFF_NAME (int i)
Definition at line 3 of file buffs.qc.
References Buff::m_color, Buff::m_name, REGISTRY_GET, rgb_to_hexcolor(), and strcat().
 {
     Buff b = REGISTRY_GET(Buffs, i);
     return strcat(rgb_to_hexcolor(b.m_color), b.m_name);
 }