Xonotic: JumpBuff Class Reference
JumpBuff Class Reference
Public Member Functions
ATTRIB (StatusEffects, m_name, string)
ATTRIB (StatusEffects, m_icon, string)
virtual void Buff ::display ()
virtual void StatusEffects ::display ()
Public Attributes
vector m_color = '0.24 0.78 1'
bool m_hidden = false
Whether the effect is displayed in the HUD.
string m_icon = "buff_jump"
int m_id = 0
float m_lifetime = 60
string m_name = _("Jump")
int m_skin = 10
string m_sprite = ""
string netname = "jump"
Detailed Description
Definition at line 110 of file all.inc.
Member Function Documentation
ATTRIB() [1/2]
StatusEffects::ATTRIB (StatusEffects , m_name , string) inherited
ATTRIB() [2/2]
StatusEffects::ATTRIB (StatusEffects , m_icon , string) inherited
Buff ::display()
virtual void Buff::Buff ::display () inline virtual inherited
Definition at line 31 of file buffs.qh.
References cvar(), cvar_string(), ENDCLASS, m_name, METHOD, netname, and strcat().
{
         returns(this.m_name, sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.m_icon));
     }
StatusEffects ::display()
virtual void StatusEffects::StatusEffects ::display () inline virtual inherited
Definition at line 54 of file all.qh.
References cvar_string(), ENDCLASS, string_null, and TC.
     {
         TC(StatusEffects, this);
         returns(this.m_name, this.m_icon ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.m_icon) : string_null);
     }
Member Data Documentation
m_color
vector JumpBuff::m_color = '0.24 0.78 1'
Definition at line 115 of file all.inc.
m_hidden
bool StatusEffects::m_hidden = false inherited
Whether the effect is displayed in the HUD.
Definition at line 36 of file all.qh.
m_icon
string JumpBuff::m_icon = "buff_jump"
Definition at line 113 of file all.inc.
m_id
int StatusEffects::m_id = 0 inherited
Definition at line 31 of file all.qh.
m_lifetime
float Buff::m_lifetime = 60 inherited
Definition at line 29 of file buffs.qh.
m_name
string JumpBuff::m_name = _("Jump")
Definition at line 111 of file all.inc.
m_skin
int JumpBuff::m_skin = 10
Definition at line 114 of file all.inc.
m_sprite
string Buff::m_sprite = "" inherited
Definition at line 30 of file buffs.qh.
netname
string JumpBuff::netname = "jump"
Definition at line 112 of file all.inc.
The documentation for this class was generated from the following file:
common/mutators/mutator/buffs/all.inc