Xonotic: ecs/systems/physics.qh File Reference
physics.qh File Reference
Functions
void sys_phys_ai (entity this)
void sys_phys_fix (entity this, float dt)
void sys_phys_fixspeed (entity this, float maxspeed_mod)
void sys_phys_monitor (entity this, float dt)
bool sys_phys_override (entity this, float dt)
void sys_phys_pregame_hold (entity this)
void sys_phys_spectator_control (entity this)
SYSTEM (phys, 30, 10)
Function Documentation
void sys_phys_ai (entity this)
Definition at line 21 of file cl_physics.qc.
References bot_think(), and IS_BOT_CLIENT.
Referenced by sys_phys_update().
 {}
void sys_phys_fix (entity this, float dt)
Definition at line 3 of file cl_physics.qc.
References items, movement, PHYS_INPUT_BUTTON_JUMP, PM_ClientMovement_UpdateStatus(), team, and UNSET_JUMP_HELD.
Referenced by sys_phys_update().
 {
     this.team = myteam + 1; // is this correct?
     this.movement = PHYS_INPUT_MOVEVALUES(this);
     this.items = STAT(ITEMS, this);
     if (!(PHYS_INPUT_BUTTON_JUMP(this))) // !jump
         UNSET_JUMP_HELD(this);           // canjump = true
     PM_ClientMovement_UpdateStatus(this);
 }
void sys_phys_fixspeed (entity this, float maxspeed_mod)
Definition at line 27 of file cl_physics.qc.
References autocvar_sv_jumpspeedcap_max, autocvar_sv_jumpspeedcap_min, ftos(), max(), PHYS_MAXAIRSPEED, PHYS_MAXSPEED, speed, strcat(), and stuffcmd.
Referenced by sys_phys_update().
 {}
void sys_phys_monitor (entity this, float dt)
Definition at line 19 of file cl_physics.qc.
References anticheat_physics(), buttons_old, CS(), movement, movement_old, PHYS_INPUT_BUTTON_MASK, PM_check_nickspam(), PM_check_punch(), sv_maxidle, time, v_angle, and v_angle_old.
Referenced by sys_phys_update().
 {}
bool sys_phys_override (entity this, float dt)
Definition at line 13 of file cl_physics.qc.
References CS(), hud, HUD_NORMAL, PHYS_INPUT_BUTTON_MASK, PM_check_specialcommand(), and time.
Referenced by sys_phys_update().
 {
     // no vehicle prediction
     return hud != HUD_NORMAL;
 }
void sys_phys_pregame_hold (entity this)
Definition at line 23 of file cl_physics.qc.
References disableclientprediction, IS_PLAYER, move_movetype, MOVETYPE_NONE, MOVETYPE_WALK, set_movetype(), time, and velocity.
Referenced by sys_phys_update().
 {}
void sys_phys_spectator_control (entity this)
Definition at line 25 of file cl_physics.qc.
References autocvar_sv_spectator_speed_multiplier, autocvar_sv_spectator_speed_multiplier_max, autocvar_sv_spectator_speed_multiplier_min, bound(), CS(), impulse, lastclassname, and STR_PLAYER.
Referenced by sys_phys_update().
 {}
SYSTEM (phys , 30 , 10)