Xonotic: common/minigames/sv_minigames.qc File Reference
common/minigames/sv_minigames.qc File Reference
#include "minigames.qh"
Defines
#define FIELD(Flags, Type, Name) if (sf & (Flags)) Write##Type(MSG_ENTITY, self.Name);
#define MSLE(Name, Fields)
Functions
void player_clear_minigame (entity player)
void minigame_rmplayer (entity minigame_session, entity player)
bool minigame_SendEntity (entity this, entity to, int sf)
void minigame_resend (entity minigame)
bool minigame_CheckSend ()
int minigame_addplayer (entity minigame_session, entity player)
entity start_minigame (entity player, string minigame)
Create a new minigame session.
entity join_minigame (entity player, string game_id)
Join an existing minigame session.
void part_minigame (entity player)
void end_minigame (entity minigame_session)
void end_minigames ()
string invite_minigame (entity inviter, entity player)
Invite a player to join in a minigame.
entity minigame_find_player (entity client)
bool MinigameImpulse (entity this, int imp)
void ClientCommand_minigame (int request, int argc, string command)
Define Documentation
#define FIELD (Flags, Type, Name) if (sf & (Flags)) Write##Type(MSG_ENTITY, self.Name);
Definition at line 53 of file sv_minigames.qc.
#define MSLE (Name, Fields)
Value:
else if (self.classname == #Name) { \
        if ( sf & MINIG_SF_CREATE ) WriteString(MSG_ENTITY,self.owner.netname); \
        Fields }
Definition at line 54 of file sv_minigames.qc.
Function Documentation
void ClientCommand_minigame (int request, int argc, string command)
Definition at line 306 of file sv_minigames.qc.
References active_minigame, argv(), argv_end_index, autocvar_sv_minigames, CMD_REQUEST_COMMAND, entity(), error(), FOREACH, GetIndexedEntity(), invite_minigame(), join_minigame(), LAMBDA, minigame_find_player(), minigame_sessions, MSG_CENTER, part_minigame(), SELFPARAM, sprint(), start_minigame(), strcat(), substring(), tokenize_console, and world.
{SELFPARAM();
    if ( !autocvar_sv_minigames )
    {
        sprint(self,"Minigames are not enabled!\n");
        return;
    }
    if (request == CMD_REQUEST_COMMAND )
    {
        string minig_cmd = argv(1);
        if ( minig_cmd == "create" && argc > 2 )
        {
            entity minig = start_minigame(self, argv(2));
            if ( minig )
                sprint(self,"Created minigame session: ",minig.netname,"\n");
            else
                sprint(self,"Cannot start minigame session!\n");
            return;
        }
        else if ( minig_cmd == "join" && argc > 2 )
        {
            entity minig = join_minigame(self, argv(2));
            if ( minig )
                sprint(self,"Joined: ",minig.netname,"\n");
            else
            {
                Send_Notification(NOTIF_ONE, self, MSG_CENTER, CENTER_JOIN_PREVENT_MINIGAME);
                sprint(self,"Cannot join given minigame session!\n");
            }
            return;
        }
        else if ( minig_cmd == "list" )
        {
            FOREACH(Minigames, true, LAMBDA(
            {
                sprint(self,it.netname," (",it.message,") ","\n");
            }));
            return;
        }
        else if ( minig_cmd == "list-sessions" )
        {
            entity e;
            for ( e = minigame_sessions; e != world; e = e.list_next )
                sprint(self,e.netname,"\n");
            return;
        }
        else if ( minig_cmd == "end" || minig_cmd == "part" )
        {
            if ( self.active_minigame )
            {
                part_minigame(self);
                sprint(self,"Left minigame session\n");
            }
            else
                sprint(self,"You aren't playing any minigame...\n");
            return;
        }
        else if ( minig_cmd == "invite" && argc > 2 )
        {
            if ( self.active_minigame )
            {
                entity client = GetIndexedEntity(argc, 2);
                string error = invite_minigame(self,client);
                if ( error == "" )
                {
                    sprint(self,"You have invited ",client.netname,
                        " to join your game of ", self.active_minigame.descriptor.message, "\n");
                }
                else
                    sprint(self,"Could not invite: ", error, ".\n");
            }
            else
                sprint(self,"You aren't playing any minigame...\n");
            return;
        }
        else if ( self.active_minigame )
        {
            entity e = minigame_find_player(self);
            string subcommand = substring(command,argv_end_index(0),-1);
            int arg_c = tokenize_console(subcommand);
            if ( self.active_minigame.minigame_event(self.active_minigame,"cmd",e,arg_c,subcommand) )
                return;
        }
        else sprint(self,strcat("Wrong command:^1 ",command,"\n"));
    }
    sprint(self, "\nUsage:^3 cmd minigame create <minigame>\n");
    sprint(self, "  Start a new minigame session\n");
    sprint(self, "Usage:^3 cmd minigame join <session>\n");
    sprint(self, "  Join an exising minigame session\n");
    sprint(self, "Usage:^3 cmd minigame list\n");
    sprint(self, "  List available minigames\n");
    sprint(self, "Usage:^3 cmd minigame list-sessions\n");
    sprint(self, "  List available minigames sessions\n");
    sprint(self, "Usage:^3 cmd minigame part|end\n");
    sprint(self, "  Leave the current minigame\n");
    sprint(self, "Usage:^3 cmd minigame invite <player>\n");
    sprint(self, "  Invite the given player to join you in a minigame\n");
}
void end_minigame (entity minigame_session)
Definition at line 223 of file sv_minigames.qc.
References entity(), etof(), findentity(), ftos(), GameLogEcho(), LOG_TRACE(), minigame_sessions, owner, p, player_clear_minigame(), strcat(), strunzone(), and world.
Referenced by end_minigames(), minigame_rmplayer(), and start_minigame().
{
    if ( minigame_session.owner )
        minigame_session.owner.list_next = minigame_session.list_next;
    else
        minigame_sessions = minigame_session.list_next;
    minigame_session.minigame_event(minigame_session,"end");
    GameLogEcho(strcat(":minigame:end:",minigame_session.netname));
    entity e = world;
    while( (e = findentity(e, owner, minigame_session)) )
        if ( e.minigame_autoclean )
        {
            LOG_TRACE("SV Auto-cleaned: ",ftos(etof(e)), " (",e.classname,")\n");
            remove(e);
        }
    entity p;
    for ( e = minigame_session.minigame_players; e != world; e = p )
    {
        p = e.list_next;
        player_clear_minigame(e.minigame_players);
        remove(e);
    }
    strunzone(minigame_session.netname);
    remove(minigame_session);
}
void end_minigames ()
Definition at line 254 of file sv_minigames.qc.
References end_minigame(), and minigame_sessions.
{
    while ( minigame_sessions )
    {
        end_minigame(minigame_sessions);
    }
}
string invite_minigame (entity inviter, entity player)
Invite a player to join in a minigame.
Returns:
Error string
Definition at line 262 of file sv_minigames.qc.
References etof(), ftos(), GameLogEcho(), INFO_MINIGAME_INVITE, MSG_INFO, strcat(), and VerifyClientEntity().
Referenced by ClientCommand_minigame().
{
    if ( !inviter || !inviter.active_minigame )
        return "Invalid minigame";
    if ( !VerifyClientEntity(player, true, false) )
        return "Invalid player";
    if ( inviter == player )
        return "You can't invite yourself";
    if ( player.active_minigame == inviter.active_minigame )
        return strcat(player.netname," is already playing");
    Send_Notification(NOTIF_ONE, player, MSG_INFO, INFO_MINIGAME_INVITE,
        inviter.active_minigame.netname, inviter.netname );
    GameLogEcho(strcat(":minigame:invite:",inviter.active_minigame.netname,":",
        ftos(etof(player)),":",player.netname));
    return "";
}
entity join_minigame (entity player, string game_id)
Join an existing minigame session.
Returns:
minigame session entity
Definition at line 199 of file sv_minigames.qc.
References autocvar_sv_minigames, entity(), IS_REAL_CLIENT, minigame_addplayer(), minigame_sessions, and world.
Referenced by ClientCommand_minigame().
{
    if ( !autocvar_sv_minigames || !IS_REAL_CLIENT(player) )
        return world;
    entity minig;
    for ( minig = minigame_sessions; minig != world; minig = minig.list_next )
    {
        if ( minig.netname == game_id )
        if ( minigame_addplayer(minig,player) )
            return minig;
    }
    return world;
}
int minigame_addplayer (entity minigame_session, entity player)
Definition at line 124 of file sv_minigames.qc.
References autocvar_sv_minigames_observer, entity(), etof(), ftos(), GameLogEcho(), IS_OBSERVER, minigame_CheckSend(), minigame_resend(), minigame_rmplayer(), minigame_SendEntity(), PutObserverInServer(), SELFPARAM, strcat(), and WITH.
Referenced by join_minigame(), and start_minigame().
{SELFPARAM();
    if ( player.active_minigame )
    {
        if ( player.active_minigame == minigame_session )
            return 0;
        minigame_rmplayer(player.active_minigame,player);
    }
    entity player_pointer = new(minigame_player);
    int mgteam = minigame_session.minigame_event(minigame_session,"join",player,player_pointer);
    if ( mgteam )
    {
        player_pointer.owner = minigame_session;
        player_pointer.minigame_players = player;
        player_pointer.team = mgteam;
        player_pointer.list_next = minigame_session.minigame_players;
        minigame_session.minigame_players = player_pointer;
        player.active_minigame = minigame_session;
        player.minigame_players = player_pointer;
        player_pointer.customizeentityforclient = minigame_CheckSend;
        Net_LinkEntity(player_pointer, false, 0, minigame_SendEntity);
        if ( !IS_OBSERVER(player) && autocvar_sv_minigames_observer )
        {
            WITH(entity, self, player, PutObserverInServer());
        }
        if ( autocvar_sv_minigames_observer == 2 )
            player.team_forced = -1;
        minigame_resend(minigame_session);
    }
    else { remove(player_pointer); }
    GameLogEcho(strcat(":minigame:join",(mgteam?"":"fail"),":",minigame_session.netname,":",
        ftos(etof(player)),":",player.netname));
    return mgteam;
}
bool minigame_CheckSend ()
Definition at line 115 of file sv_minigames.qc.
References entity(), other, owner, SELFPARAM, and world.
Referenced by minigame_addplayer(), and msle_spawn().
{SELFPARAM();
    entity e;
    for ( e = self.owner.minigame_players; e != world; e = e.list_next )
        if ( e.minigame_players == other )
            return true;
    return false;
}
entity minigame_find_player (entity client)
Definition at line 282 of file sv_minigames.qc.
References entity(), and world.
Referenced by ClientCommand_minigame(), and MinigameImpulse().
{
    if ( ! client.active_minigame )
        return world;
    entity e;
    for ( e = client.active_minigame.minigame_players; e; e = e.list_next )
        if ( e.minigame_players == client )
            return e;
    return world;
}
void minigame_resend (entity minigame)
Definition at line 105 of file sv_minigames.qc.
References entity(), findentity(), MINIG_SF_ALL, owner, and world.
Referenced by minigame_addplayer().
{
    minigame.SendFlags = MINIG_SF_ALL;
    entity e = world;
    while (( e = findentity(e,owner,minigame) ))
    {
        e.SendFlags = MINIG_SF_ALL;
    }
}
void minigame_rmplayer (entity minigame_session, entity player)
Definition at line 14 of file sv_minigames.qc.
References end_minigame(), entity(), etof(), ftos(), GameLogEcho(), p, player_clear_minigame(), strcat(), and world.
Referenced by minigame_addplayer(), and part_minigame().
{
    entity e;
    entity p = minigame_session.minigame_players;
    if ( p.minigame_players == player )
    {
        if ( p.list_next == world )
        {
            end_minigame(minigame_session);
            return;
        }
        minigame_session.minigame_event(minigame_session,"part",player);
        GameLogEcho(strcat(":minigame:part:",minigame_session.netname,":",
            ftos(etof(player)),":",player.netname));
        minigame_session.minigame_players = p.list_next;
        remove ( p );
        player_clear_minigame(player);
    }
    else
    {
        for ( e = p.list_next; e != world; e = e.list_next )
        {
            if ( e.minigame_players == player )
            {
                minigame_session.minigame_event(minigame_session,"part",player);
                GameLogEcho(strcat(":minigame:part:",minigame_session.netname,":",
                    ftos(etof(player)),":",player.netname));
                p.list_next = e.list_next;
                remove(e);
                player_clear_minigame(player);
                return;
            }
            p = e;
        }
    }
}
bool minigame_SendEntity (entity this, entity to, int sf)
Definition at line 61 of file sv_minigames.qc.
References classname, descriptor, entity(), etof(), MINIG_SF_CREATE, MINIG_SF_UPDATE, minigame_flags, minigame_players, MINIGAME_SIMPLELINKED_ENTITIES, msle_id(), netname, owner, team, WriteByte(), WriteLong(), WriteShort(), and WriteString().
Referenced by minigame_addplayer(), msle_spawn(), and start_minigame().
{
    WriteHeader(MSG_ENTITY, ENT_CLIENT_MINIGAME);
    WriteByte(MSG_ENTITY, sf);
    if ( sf & MINIG_SF_CREATE )
    {
        WriteShort(MSG_ENTITY,msle_id(self.classname));
        WriteString(MSG_ENTITY,self.netname);
    }
    entity minigame_ent = self.owner;
    if ( self.classname == "minigame" )
    {
        minigame_ent = self;
        if ( sf & MINIG_SF_CREATE )
            WriteString(MSG_ENTITY,self.descriptor.netname);
        if ( sf & MINIG_SF_UPDATE )
            WriteLong(MSG_ENTITY,self.minigame_flags);
    }
    else if ( self.classname == "minigame_player" )
    {
        if ( sf & MINIG_SF_CREATE )
        {
            WriteString(MSG_ENTITY,self.owner.netname);
            WriteLong(MSG_ENTITY,etof(self.minigame_players));
        }
        if ( sf & MINIG_SF_UPDATE )
            WriteByte(MSG_ENTITY,self.team);
    }
    MINIGAME_SIMPLELINKED_ENTITIES
    minigame_ent.minigame_event(minigame_ent,"network_send",self,sf);
    return true;
}
bool MinigameImpulse (entity this, int imp)
Definition at line 293 of file sv_minigames.qc.
References active_minigame, entity(), and minigame_find_player().
Referenced by ImpulseCommands(), ObserverThink(), and SpectatorThink().
{
    if (!this.active_minigame) return false;
    entity e = minigame_find_player(this);
    if ( imp && this.active_minigame && e )
    {
        return this.active_minigame.minigame_event(this.active_minigame,"impulse",e,imp);
    }
    return false;
}
void part_minigame (entity player)
Definition at line 215 of file sv_minigames.qc.
References entity(), and minigame_rmplayer().
Referenced by ClientCommand_minigame(), and ClientDisconnect().
{
    entity minig = player.active_minigame;
    if ( minig && minig.classname == "minigame" )
        minigame_rmplayer(minig,player);
}
void player_clear_minigame (entity player)
Definition at line 3 of file sv_minigames.qc.
References IS_PLAYER, MOVETYPE_FLY_WORLDONLY, MOVETYPE_WALK, and world.
Referenced by end_minigame(), and minigame_rmplayer().
{
    player.active_minigame = world;
    player.minigame_players = world;
    if ( IS_PLAYER(player) )
        player.movetype = MOVETYPE_WALK;
    else
        player.movetype = MOVETYPE_FLY_WORLDONLY;
    player.team_forced = 0;
}
entity start_minigame (entity player, string minigame)
Create a new minigame session.
Returns:
minigame session entity
Definition at line 163 of file sv_minigames.qc.
References autocvar_sv_minigames, end_minigame(), entity(), etof(), ftos(), GameLogEcho(), IS_REAL_CLIENT, LOG_TRACE(), minigame_addplayer(), minigame_get_descriptor(), minigame_SendEntity(), minigame_sessions, strcat(), strzone(), and world.
Referenced by ClientCommand_minigame().
{
    if ( !autocvar_sv_minigames || !IS_REAL_CLIENT(player) )
        return world;
    entity e = minigame_get_descriptor(minigame);
    if ( e )
    {
        entity minig = new(minigame);
        minig.netname = strzone(strcat(e.netname,"_",ftos(etof(minig))));
        minig.descriptor = e;
        minig.minigame_event = e.minigame_event;
        minig.minigame_event(minig,"start");
        GameLogEcho(strcat(":minigame:start:",minig.netname));
        if ( ! minigame_addplayer(minig,player) )
        {
            LOG_TRACE("Minigame ",minig.netname," rejected the first player join!\n");
            end_minigame(minig);
            return world;
        }
        Net_LinkEntity(minig, false, 0, minigame_SendEntity);
        if ( !minigame_sessions )
            minigame_sessions = minig;
        else
        {
            minigame_sessions.owner = minig;
            minig.list_next = minigame_sessions;
            minigame_sessions = minig;
        }
        return minig;
    }
    return world;
}