Xonotic: menu/xonotic/dialog_multiplayer_profile.qc File Reference
dialog_multiplayer_profile.qc File Reference
#include "dialog_multiplayer_profile.qh"
#include "playermodel.qh"
#include "statslist.qh"
#include "languagelist.qh"
#include "textlabel.qh"
#include "commandbutton.qh"
#include "inputbox.qh"
#include "colorpicker.qh"
#include "charmap.qh"
#include "colorbutton.qh"
#include "checkbox.qh"
#include "radiobutton.qh"
Macros
#define GENDERWIDTH_ITEM (GENDERWIDTH_LENGTH / 3)
#define GENDERWIDTH_LENGTH 2.5
#define GENDERWIDTH_OFFSET 0.25
Functions
entity makeXonoticProfileTab ()
void XonoticProfileTab_draw (entity me)
void XonoticProfileTab_fill (entity me)
Macro Definition Documentation
#define GENDERWIDTH_ITEM (GENDERWIDTH_LENGTH / 3)
Referenced by XonoticProfileTab_fill().
#define GENDERWIDTH_LENGTH 2.5
#define GENDERWIDTH_OFFSET 0.25
Referenced by XonoticProfileTab_fill().
Function Documentation
entity makeXonoticProfileTab ()
Definition at line 15 of file dialog_multiplayer_profile.qc.
References entity(), and NEW.
Referenced by XonoticMultiplayerDialog_fill().
 {
     entity me;
     me = NEW(XonoticProfileTab);
     me.configureDialog(me);
     return me;
 }
void XonoticProfileTab_draw (entity me)
Definition at line 22 of file dialog_multiplayer_profile.qc.
References cvar_string(), mod(), SUPER, and time.
 {
     if(cvar_string("_cl_name") == "Player")
         me.playerNameLabel.alpha = ((mod(time * 2, 2) < 1) ? 1 : 0);
     else
         me.playerNameLabel.alpha = me.playerNameLabelAlpha;
     SUPER(XonoticProfileTab).draw(me);
 }
void XonoticProfileTab_fill (entity me)
Definition at line 30 of file dialog_multiplayer_profile.qc.
References COMMANDBUTTON_APPLY, entity(), GENDERWIDTH_ITEM, GENDERWIDTH_OFFSET, makeXonoticButton(), makeXonoticCharmap(), makeXonoticCheckBox(), makeXonoticColorButton(), makeXonoticColorpicker(), makeXonoticCommandButton(), makeXonoticHeaderLabel(), makeXonoticInputBox_T(), makeXonoticLanguageList(), makeXonoticPlayerModelSelector(), makeXonoticRadioButton(), makeXonoticStatsList(), makeXonoticTextLabel(), makeXonoticTextSlider(), mod(), PlayerModelSelector_Next_Click(), PlayerModelSelector_Prev_Click(), setDependent(), statslist, and string_null.
 {
     entity e, pms, label, box;
     float i;
     entity profileApplyButton = makeXonoticCommandButton(_("Apply immediately"), '0 0 0',
         "color -1 -1;"
         "name \"$_cl_name\";"
         "playermodel $_cl_playermodel;"
         "playerskin $_cl_playerskin;"
         "sendcvar cl_allow_uidtracking;"
         "sendcvar cl_allow_uid2name;"
         , COMMANDBUTTON_APPLY);
     profileApplyButton.disableOnClick = true;
     // ==============
     //  NAME SECTION
     // ==============
     me.gotoRC(me, 0.5, 0);
         me.TD(me, 1, 3, me.playerNameLabel = makeXonoticHeaderLabel(_("Name")));
     me.gotoRC(me, 1.5, 0);
         me.TD(me, 1, 3, label = makeXonoticTextLabel(0.5, string_null));
             label.allowCut = 1;
             label.allowColors = 1;
             label.alpha = 1;
             label.isBold = true;
             label.fontSize = SKINFONTSIZE_TITLE;
     me.gotoRC(me, 2.5, 0);
         me.TD(me, 1, 3.0, box = makeXonoticInputBox_T(1, "_cl_name",
             _("Name under which you will appear in the game")));
             box.forbiddenCharacters = "\r\n\\\"$"; // don't care, isn't getting saved
             box.maxLength = -127; // negative means encoded length in bytes
             box.saveImmediately = 0;  // Sorry, can't do this, it spams "name" commands.
             box.enableClearButton = 0;
             box.applyButton = profileApplyButton;
             label.textEntity = box;
     me.TR(me);
         me.TD(me, 5, 1, e = makeXonoticColorpicker(box));
         me.TD(me, 5, 2, e = makeXonoticCharmap(box));
     // ===============
     //  MODEL SECTION
     // ===============
     //me.gotoRC(me, 0.5, 3.1); me.setFirstColumn(me, me.currentColumn); // TOP RIGHT
     //me.gotoRC(me, 9, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM RIGHT
     me.gotoRC(me, 9, 0); me.setFirstColumn(me, me.currentColumn); // BOTTOM LEFT
         me.TD(me, 1, 3, e = makeXonoticHeaderLabel(_("Model")));
     me.TR(me);
         //me.TDempty(me, 0); // MODEL LEFT, COLOR RIGHT
         me.TDempty(me, 1); // MODEL RIGHT, COLOR LEFT
         pms = makeXonoticPlayerModelSelector();
         me.TD(me, 1, 0.3, e = makeXonoticButton("<<", '0 0 0'));
             e.onClick = PlayerModelSelector_Prev_Click;
             e.onClickEntity = pms;
             e.applyButton = profileApplyButton;
         me.TD(me, 11.5, 1.4, pms);
         me.TD(me, 1, 0.3, e = makeXonoticButton(">>", '0 0 0'));
             e.onClick = PlayerModelSelector_Next_Click;
             e.onClickEntity = pms;
             e.applyButton = profileApplyButton;
     //me.setFirstColumn(me, me.currentColumn + 2); // MODEL LEFT, COLOR RIGHT
     me.gotoRC(me, me.currentRow, 0); me.setFirstColumn(me, me.currentColumn); // MODEL RIGHT, COLOR LEFT
     me.TR(me);
         me.TD(me, 1, 1, e = makeXonoticHeaderLabel(_("Glowing color")));
         for(i = 0; i < 15; ++i)
         {
             if(mod(i, 5) == 0)
                 me.TR(me);
             me.TDNoMargin(me, 1, 0.2, e = makeXonoticColorButton(1, 0, i), '0 1 0');
                 e.applyButton = profileApplyButton;
         }
     me.TR(me);
     me.TR(me);
         me.TD(me, 1, 1, e = makeXonoticHeaderLabel(_("Detail color")));
         for(i = 0; i < 15; ++i)
         {
             if(mod(i, 5) == 0)
                 me.TR(me);
             me.TDNoMargin(me, 1, 0.2, e = makeXonoticColorButton(2, 1, i), '0 1 0');
                 e.applyButton = profileApplyButton;
         }
     // ====================
     //  STATISTICS SECTION
     // ====================
     me.gotoRC(me, 0.5, 3.1); me.setFirstColumn(me, me.currentColumn); // TOP RIGHT
     //me.gotoRC(me, 9, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM RIGHT
     //me.gotoRC(me, 9, 0); me.setFirstColumn(me, me.currentColumn); // BOTTOM LEFT
         me.TD(me, 1, 3, e = makeXonoticHeaderLabel(_("Statistics")));
     me.TR(me);
         me.TDempty(me, 0.25);
         me.TD(me, 1, 2.5, e = makeXonoticCheckBox(0, "cl_allow_uidtracking", _("Allow player statistics to track your client")));
             e.applyButton = profileApplyButton;
     me.TR(me);
         me.TDempty(me, 0.25);
         me.TD(me, 1, 2.5, e = makeXonoticCheckBox(0, "cl_allow_uid2name", _("Allow player statistics to use your nickname")));
             e.applyButton = profileApplyButton;
             setDependent(e, "cl_allow_uidtracking", 1, 1);
     me.gotoRC(me, 4, 3.1); // TOP RIGHT
     //me.gotoRC(me, 12.5, 3.1); // BOTTOM RIGHT
     //me.gotoRC(me, 12.5, 0); // BOTTOM LEFT
         me.TDempty(me, 0.25);
         me.TD(me, 9, 2.5, statslist = makeXonoticStatsList());
         //setDependent(statslist, "cl_allow_uidtracking", 1, 1);
     // =================
     //  COUNTRY SECTION
     // =================
     me.gotoRC(me, 16, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM SECTION, TOP POS
     //me.gotoRC(me, 13.5, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM SECTION, TOP POS
     //me.gotoRC(me, 0.5, 3.1); me.setFirstColumn(me, me.currentColumn); // TOP SECTION, TOP POS
         me.TD(me, 1, 3, e = makeXonoticHeaderLabel(_("Country")));
     me.TR(me);
         me.TDempty(me, 0.5);
         me.TD(me, 4.5, 2, e = makeXonoticLanguageList()); // todo: cl_country: create proper country list
     // ================
     //  GENDER SECTION
     // ================
     me.gotoRC(me, 13.5, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM SECTION, TOP POS
     //me.gotoRC(me, 19.5, 3.1); me.setFirstColumn(me, me.currentColumn); // BOTTOM SECTION, BOTTOM POS
     //me.gotoRC(me, 6.5, 3.1); me.setFirstColumn(me, me.currentColumn); // TOP SECTION, BOTTOM POS
     #if 0
         me.TD(me, 1, 1, e = makeXonoticTextLabel(0, _("Gender:")));
         me.TD(me, 1, 2, e = makeXonoticTextSlider("_cl_gender"));
             e.addValue(e, _("Undisclosed"), "0");
             e.addValue(e, _("Female"), "1");
             e.addValue(e, _("Male"), "2");
             e.configureXonoticTextSliderValues(e);
     #else
             me.TD(me, 1, 3, e = makeXonoticHeaderLabel(_("Gender")));
         me.TR(me);
             #define GENDERWIDTH_OFFSET 0.25
             #define GENDERWIDTH_LENGTH 2.5
             #define GENDERWIDTH_ITEM (GENDERWIDTH_LENGTH / 3)
             me.TDempty(me, GENDERWIDTH_OFFSET);
             me.TD(me, 1, GENDERWIDTH_ITEM, e = makeXonoticRadioButton(3, "_cl_gender", "2", _("Female")));
             me.TD(me, 1, GENDERWIDTH_ITEM, e = makeXonoticRadioButton(3, "_cl_gender", "1", _("Male")));
             me.TD(me, 1, GENDERWIDTH_ITEM, e = makeXonoticRadioButton(3, "_cl_gender", "0", _("Undisclosed")));
     #endif
     me.gotoRC(me, me.rows - 1, 0);
         me.TD(me, 1, me.columns, profileApplyButton);
 }