Xonotic: common/gamemodes/gamemode/assault/sv_assault.qc File Reference
sv_assault.qc File Reference
#include "sv_assault.qh"
#include <server/command/vote.qh>
#include <common/mapobjects/func/breakable.qh>
#include <common/mapobjects/triggers.qh>
#include <common/turrets/sv_turrets.qh>
#include <server/damage.qh>
#include <server/world.qh>
#include <server/spawnpoints.qh>
Macros
#define AS_ROUND_DELAY 5
Functions
void as_round_think ()
bool assault_decreaser_sprite_visible (entity this, entity player, entity view)
void assault_new_round (entity this)
void assault_objective_decrease_use (entity this, entity actor, entity trigger)
void assault_objective_reset (entity this)
void assault_objective_use (entity this, entity actor, entity trigger)
void assault_roundstart_use (entity this, entity actor, entity trigger)
void assault_roundstart_use_this (entity this)
void assault_setenemytoobjective (entity this)
void assault_wall_think (entity this)
bool destructible_heal (entity targ, entity inflictor, float amount, float limit)
void havocbot_ast_reset_role (entity this)
void havocbot_goalrating_ast_targets (entity this, float ratingscale)
void havocbot_role_ast_defense (entity this)
void havocbot_role_ast_offense (entity this)
void havocbot_role_ast_setrole (entity this, float role)
MUTATOR_HOOKFUNCTION (as, PlayerSpawn)
MUTATOR_HOOKFUNCTION (as, TurretSpawn)
MUTATOR_HOOKFUNCTION (as, VehicleInit)
MUTATOR_HOOKFUNCTION (as, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (as, PlayHitsound)
MUTATOR_HOOKFUNCTION (as, TeamBalance_CheckAllowedTeams)
MUTATOR_HOOKFUNCTION (as, CheckRules_World)
MUTATOR_HOOKFUNCTION (as, ReadLevelCvars)
MUTATOR_HOOKFUNCTION (as, OnEntityPreSpawn)
MUTATOR_HOOKFUNCTION (as, ReadyRestart_Deny)
spawnfunc (info_player_attacker)
spawnfunc (info_player_defender)
spawnfunc (target_objective)
spawnfunc (target_objective_decrease)
spawnfunc (func_assault_destructible)
spawnfunc (func_assault_wall)
spawnfunc (target_assault_roundend)
spawnfunc (target_assault_roundstart)
STATIC_INIT (g_assault)
void target_assault_roundend_reset (entity this)
void target_assault_roundend_use (entity this, entity actor, entity trigger)
void target_objective_decrease_activate (entity this)
void target_objective_decrease_findtarget (entity this)
vector target_objective_spawn_evalfunc (entity this, entity player, entity spot, vector current)
int WinningCondition_Assault ()
Variables
entity as_round
entity ent_winning
IntrusiveList g_assault_destructibles
IntrusiveList g_assault_objectivedecreasers
IntrusiveList g_assault_objectives
entity sprite
Macro Definition Documentation
#define AS_ROUND_DELAY 5
Definition at line 12 of file sv_assault.qc.
Referenced by assault_new_round(), and WinningCondition_Assault().
Function Documentation
void as_round_think ()
Definition at line 231 of file sv_assault.qc.
References as_round, assault_new_round(), and NULL.
Referenced by WinningCondition_Assault().
 {
     game_stopped = false;
     assault_new_round(as_round.ent_winning);
     delete(as_round);
     as_round = NULL;
 }
bool assault_decreaser_sprite_visible (entity this, entity player, entity view)
Definition at line 108 of file sv_assault.qc.
References assault_decreaser, ASSAULT_VALUE_INACTIVE, GetResource(), and RES_HEALTH.
Referenced by target_objective_decrease_activate().
 {
     if(GetResource(this.assault_decreaser.enemy, RES_HEALTH) >= ASSAULT_VALUE_INACTIVE)
         return false;
     return true;
 }
void assault_new_round (entity this)
Definition at line 203 of file sv_assault.qc.
References AS_ROUND_DELAY, assault_attacker_team, ceil(), cvar_set(), ftos(), g_saved_team, IL_EACH, IS_CLIENT, NUM_TEAM_1, NUM_TEAM_2, ReadyRestart_force(), time, and winning.
Referenced by as_round_think().
 {
     //bprint("ASSAULT: new round\n");
     // up round counter
     this.winning = this.winning + 1;
     // swap attacker/defender roles
     if(assault_attacker_team == NUM_TEAM_1)
         assault_attacker_team = NUM_TEAM_2;
     else
         assault_attacker_team = NUM_TEAM_1;
     IL_EACH(g_saved_team, !IS_CLIENT(it),
     {
         if(it.team_saved == NUM_TEAM_1)
             it.team_saved = NUM_TEAM_2;
         else if(it.team_saved == NUM_TEAM_2)
             it.team_saved = NUM_TEAM_1;
     });
     // reset the level with a countdown
     cvar_set("timelimit", ftos(ceil(time - AS_ROUND_DELAY - game_starttime) / 60));
     ReadyRestart_force(); // sets game_starttime
 }
void assault_objective_decrease_use (entity this, entity actor, entity trigger)
Definition at line 54 of file sv_assault.qc.
References assault_attacker_team, ASSAULT_VALUE_INACTIVE, centerprint(), dmg, enemy, FOREACH_CLIENT, GameRules_scoring_add_team, GetResource(), IS_PLAYER, NULL, RES_HEALTH, SetResourceExplicit(), SUB_UseTargets(), and TakeResource().
Referenced by spawnfunc().
 {
     if(actor.team != assault_attacker_team)
     {
         // wrong team triggered decrease
         return;
     }
     if(trigger.assault_sprite)
     {
         WaypointSprite_Disown(trigger.assault_sprite, waypointsprite_deadlifetime);
         if(trigger.classname == "func_assault_destructible")
             trigger.sprite = NULL; // TODO: just unsetting it?!
     }
     else
         return; // already activated! cannot activate again!
     float hlth = GetResource(this.enemy, RES_HEALTH);
     if (hlth < ASSAULT_VALUE_INACTIVE)
     {
         if (hlth - this.dmg > 0.5)
         {
             GameRules_scoring_add_team(actor, SCORE, this.dmg);
             TakeResource(this.enemy, RES_HEALTH, this.dmg);
         }
         else
         {
             GameRules_scoring_add_team(actor, SCORE, hlth);
             GameRules_scoring_add_team(actor, ASSAULT_OBJECTIVES, 1);
             SetResourceExplicit(this.enemy, RES_HEALTH, -1);
             if(this.enemy.message)
                 FOREACH_CLIENT(IS_PLAYER(it), { centerprint(it, this.enemy.message); });
             SUB_UseTargets(this.enemy, this, trigger);
         }
     }
 }
void assault_objective_reset (entity this)
Definition at line 48 of file sv_assault.qc.
References ASSAULT_VALUE_INACTIVE, RES_HEALTH, and SetResourceExplicit().
Referenced by spawnfunc().
 {
     SetResourceExplicit(this, RES_HEALTH, ASSAULT_VALUE_INACTIVE);
 }
void assault_objective_use (entity this, entity actor, entity trigger)
Definition at line 25 of file sv_assault.qc.
References IL_EACH, RES_HEALTH, and SetResourceExplicit().
Referenced by spawnfunc().
 {
     // activate objective
     SetResourceExplicit(this, RES_HEALTH, 100);
     //print("^2Activated objective ", this.targetname, "=", etos(this), "\n");
     //print("Activator is ", actor.classname, "\n");
     IL_EACH(g_assault_objectivedecreasers, it.target == this.targetname,
     {
         target_objective_decrease_activate(it);
     });
 }
void assault_roundstart_use (entity this, entity actor, entity trigger)
Definition at line 163 of file sv_assault.qc.
References g_turrets, IL_EACH, NUM_TEAM_1, NUM_TEAM_2, SUB_UseTargets(), and turret_respawn().
Referenced by assault_roundstart_use_this(), and spawnfunc().
 {
     SUB_UseTargets(this, this, trigger);
     //(Re)spawn all turrets
     IL_EACH(g_turrets, true,
     {
         // Swap turret teams
         if(it.team == NUM_TEAM_1)
             it.team = NUM_TEAM_2;
         else
             it.team = NUM_TEAM_1;
         // Doubles as teamchange
         turret_respawn(it);
     });
 }
void assault_roundstart_use_this (entity this)
Definition at line 180 of file sv_assault.qc.
References assault_roundstart_use(), and NULL.
Referenced by spawnfunc().
 {
     assault_roundstart_use(this, NULL, NULL);
 }
void assault_setenemytoobjective (entity this)
Definition at line 93 of file sv_assault.qc.
References enemy, IL_EACH, NULL, and objerror().
Referenced by spawnfunc(), and target_objective_decrease_findtarget().
 {
     IL_EACH(g_assault_objectives, it.targetname == this.target,
     {
         if(this.enemy == NULL)
             this.enemy = it;
         else
             objerror(this, "more than one objective as target - fix the map!");
         break;
     });
     if(this.enemy == NULL)
         objerror(this, "no objective as target - fix the map!");
 }
void assault_wall_think (entity this)
Definition at line 185 of file sv_assault.qc.
References enemy, GetResource(), model, nextthink, RES_HEALTH, solid, SOLID_BSP, SOLID_NOT, and time.
Referenced by spawnfunc().
 {
     if(GetResource(this.enemy, RES_HEALTH) < 0)
     {
         this.model = "";
         this.solid = SOLID_NOT;
     }
     else
     {
         this.model = this.mdl;
         this.solid = SOLID_BSP;
     }
     this.nextthink = time + 0.2;
 }
bool destructible_heal (entity targ, entity inflictor, float amount, float limit)
Definition at line 340 of file sv_assault.qc.
References GetResource(), GiveResourceWithLimit(), RES_HEALTH, and RES_LIMIT_NONE.
Referenced by spawnfunc().
 {
     float true_limit = ((limit != RES_LIMIT_NONE) ? limit : targ.max_health);
     float hlth = GetResource(targ, RES_HEALTH);
     if (hlth <= 0 || hlth >= true_limit)
         return false;
     GiveResourceWithLimit(targ, RES_HEALTH, amount, true_limit);
     if(targ.sprite)
     {
         WaypointSprite_UpdateHealth(targ.sprite, GetResource(targ, RES_HEALTH));
     }
     func_breakable_colormod(targ);
     return true;
 }
void havocbot_ast_reset_role (entity this)
Definition at line 556 of file sv_assault.qc.
References assault_attacker_team, HAVOCBOT_AST_ROLE_DEFENSE, HAVOCBOT_AST_ROLE_OFFENSE, havocbot_role_ast_setrole(), IS_DEAD, and team.
Referenced by havocbot_role_ast_defense(), havocbot_role_ast_offense(), and MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if(this.team == assault_attacker_team)
         havocbot_role_ast_setrole(this, HAVOCBOT_AST_ROLE_OFFENSE);
     else
         havocbot_role_ast_setrole(this, HAVOCBOT_AST_ROLE_DEFENSE);
 }
void havocbot_goalrating_ast_targets (entity this, float ratingscale)
dprint("waypoints around target were found\n");
Definition at line 405 of file sv_assault.qc.
References best, checkpvs(), entity(), FLOAT_MAX, havocbot_attack_time, IL_EACH, navigation_routerating(), NULL, origin, radius, time, vector(), view_ofs, and WAYPOINTFLAG_GENERATED.
Referenced by havocbot_role_ast_defense(), and havocbot_role_ast_offense().
 {
     IL_EACH(g_assault_destructibles, it.bot_attack,
     {
         if (it.target == "")
             continue;
         bool found = false;
         entity destr = it;
         IL_EACH(g_assault_objectivedecreasers, it.targetname == destr.target,
         {
             float hlth = GetResource(it.enemy, RES_HEALTH);
             if (hlth > 0 && hlth < ASSAULT_VALUE_INACTIVE)
             {
                 found = true;
                 break;
             }
         });
         if(!found)
             continue;
         vector p = 0.5 * (it.absmin + it.absmax);
         // Find and rate waypoints around it
         found = false;
         entity best = NULL;
         float bestvalue = FLOAT_MAX;
         entity des = it;
         for (float radius = 500; radius <= 1500 && !found; radius += 500)
         {
             FOREACH_ENTITY_RADIUS(p, radius, it.classname == "waypoint" && !(it.wpflags & WAYPOINTFLAG_GENERATED),
             {
                 if(checkpvs(it.origin, des))
                 {
                     found = true;
                     if(it.cnt < bestvalue)
                     {
                         best = it;
                         bestvalue = it.cnt;
                     }
                 }
             });
         }
         if(best)
         {
         //  te_lightning2(NULL, '0 0 0', best.origin);
         //  te_knightspike(best.origin);
             navigation_routerating(this, best, ratingscale, 4000);
             best.cnt += 1;
             this.havocbot_attack_time = 0;
             if(checkpvs(this.origin + this.view_ofs, it))
             if(checkpvs(this.origin + this.view_ofs, best))
             {
             //  dprint("increasing attack time for this target\n");
                 this.havocbot_attack_time = time + 2;
             }
         }
     });
 }
void havocbot_role_ast_defense (entity this)
Definition at line 506 of file sv_assault.qc.
References havocbot_ast_reset_role(), havocbot_attack_time, havocbot_goalrating_ast_targets(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_role_timeout, IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), origin, and time.
Referenced by havocbot_role_ast_setrole().
 {
     if(IS_DEAD(this))
     {
         this.havocbot_attack_time = 0;
         havocbot_ast_reset_role(this);
         return;
     }
     // Set the role timeout if necessary
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + 120;
     if (time > this.havocbot_role_timeout)
     {
         havocbot_ast_reset_role(this);
         return;
     }
     if(this.havocbot_attack_time>time)
         return;
     if (navigation_goalrating_timeout(this))
     {
         // role: defense
         navigation_goalrating_start(this);
         havocbot_goalrating_enemyplayers(this, 10000, this.origin, 3000);
         havocbot_goalrating_ast_targets(this, 20000);
         havocbot_goalrating_items(this, 30000, this.origin, 10000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
void havocbot_role_ast_offense (entity this)
Definition at line 471 of file sv_assault.qc.
References havocbot_ast_reset_role(), havocbot_attack_time, havocbot_goalrating_ast_targets(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_role_timeout, IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), origin, and time.
Referenced by havocbot_role_ast_setrole().
 {
     if(IS_DEAD(this))
     {
         this.havocbot_attack_time = 0;
         havocbot_ast_reset_role(this);
         return;
     }
     // Set the role timeout if necessary
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + 120;
     if (time > this.havocbot_role_timeout)
     {
         havocbot_ast_reset_role(this);
         return;
     }
     if(this.havocbot_attack_time>time)
         return;
     if (navigation_goalrating_timeout(this))
     {
         // role: offense
         navigation_goalrating_start(this);
         havocbot_goalrating_enemyplayers(this, 10000, this.origin, 650);
         havocbot_goalrating_ast_targets(this, 20000);
         havocbot_goalrating_items(this, 30000, this.origin, 10000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
void havocbot_role_ast_setrole (entity this, float role)
Definition at line 541 of file sv_assault.qc.
References HAVOCBOT_AST_ROLE_DEFENSE, HAVOCBOT_AST_ROLE_OFFENSE, havocbot_role_ast_defense(), havocbot_role_ast_offense(), and havocbot_role_timeout.
Referenced by havocbot_ast_reset_role().
 {
     switch(role)
     {
         case HAVOCBOT_AST_ROLE_DEFENSE:
             this.havocbot_role = havocbot_role_ast_defense;
             this.havocbot_role_timeout = 0;
             break;
         case HAVOCBOT_AST_ROLE_OFFENSE:
             this.havocbot_role = havocbot_role_ast_offense;
             this.havocbot_role_timeout = 0;
             break;
     }
 }
MUTATOR_HOOKFUNCTION (as , PlayerSpawn)
Definition at line 568 of file sv_assault.qc.
References assault_attacker_team, entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.team == assault_attacker_team)
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_ASSAULT_ATTACKING);
     else
         Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_ASSAULT_DEFENDING);
 }
MUTATOR_HOOKFUNCTION (as , TurretSpawn)
Definition at line 578 of file sv_assault.qc.
References assault_attacker_team, entity(), FLOAT_MAX, and M_ARGV.
 {
     entity turret = M_ARGV(0, entity);
     if(!turret.team || turret.team == FLOAT_MAX)
         turret.team = assault_attacker_team; // this gets reversed when match starts (assault_roundstart_use)
 }
MUTATOR_HOOKFUNCTION (as , VehicleInit)
Definition at line 586 of file sv_assault.qc.
References entity(), M_ARGV, and time.
 {
     entity veh = M_ARGV(0, entity);
     veh.nextthink = time + 0.5;
 }
MUTATOR_HOOKFUNCTION (as , HavocBot_ChooseRole)
Definition at line 593 of file sv_assault.qc.
References entity(), havocbot_ast_reset_role(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     havocbot_ast_reset_role(bot);
     return true;
 }
MUTATOR_HOOKFUNCTION (as , PlayHitsound)
Definition at line 601 of file sv_assault.qc.
References entity(), and M_ARGV.
 {
     entity frag_victim = M_ARGV(0, entity);
     return (frag_victim.classname == "func_assault_destructible");
 }
MUTATOR_HOOKFUNCTION (as , TeamBalance_CheckAllowedTeams)
Definition at line 608 of file sv_assault.qc.
References BIT, and M_ARGV.
 {
     // assault always has 2 teams
     M_ARGV(0, float) = BIT(0) | BIT(1);
     return true;
 }
MUTATOR_HOOKFUNCTION (as , CheckRules_World)
Definition at line 615 of file sv_assault.qc.
References M_ARGV, and WinningCondition_Assault().
 {
     M_ARGV(0, float) = WinningCondition_Assault();
     return true;
 }
MUTATOR_HOOKFUNCTION (as , ReadLevelCvars)
Definition at line 621 of file sv_assault.qc.
References sv_ready_restart_after_countdown, and warmup_stage.
 {
     // incompatible
     warmup_stage = 0;
     sv_ready_restart_after_countdown = 0;
 }
MUTATOR_HOOKFUNCTION (as , OnEntityPreSpawn)
Definition at line 628 of file sv_assault.qc.
References entity(), and M_ARGV.
 {
     entity ent = M_ARGV(0, entity);
     switch(ent.classname)
     {
         case "info_player_team1":
         case "info_player_team2":
         case "info_player_team3":
         case "info_player_team4":
             return true;
     }
 }
MUTATOR_HOOKFUNCTION (as , ReadyRestart_Deny)
Definition at line 642 of file sv_assault.qc.
 {
     // readyrestart not supported (yet)
     return true;
 }
spawnfunc (info_player_attacker)
Definition at line 295 of file sv_assault.qc.
References g_assault, NUM_TEAM_1, and team.
Referenced by conveyor_think(), door_reset(), func_ladder_think(), SUB_NullThink(), Teleport_Touch(), train_next(), trigger_impulse_touch_radial(), trigger_keylock_touch(), trigger_push_findtarget(), and WarpZone_Projectile_Touch().
 {
     if (!g_assault) { delete(this); return; }
     this.team = NUM_TEAM_1; // red, gets swapped every round
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (info_player_defender)
Definition at line 303 of file sv_assault.qc.
References g_assault, NUM_TEAM_2, and team.
 {
     if (!g_assault) { delete(this); return; }
     this.team = NUM_TEAM_2; // blue, gets swapped every round
     spawnfunc_info_player_deathmatch(this);
 }
spawnfunc (target_objective)
Definition at line 311 of file sv_assault.qc.
References assault_objective_reset(), assault_objective_use(), g_assault, IL_PUSH(), spawn_evalfunc, target_objective_spawn_evalfunc(), and use.
 {
     if (!g_assault) { delete(this); return; }
     IL_PUSH(g_assault_objectives, this);
     this.use = assault_objective_use;
     this.reset = assault_objective_reset;
     this.reset(this);
     this.spawn_evalfunc = target_objective_spawn_evalfunc;
 }
spawnfunc (target_objective_decrease)
Definition at line 322 of file sv_assault.qc.
References assault_objective_decrease_use(), ASSAULT_VALUE_INACTIVE, dmg, enemy, g_assault, IL_PUSH(), InitializeEntity(), max_health, NULL, RES_HEALTH, SetResourceExplicit(), target_objective_decrease_findtarget(), and use.
 {
     if (!g_assault) { delete(this); return; }
     IL_PUSH(g_assault_objectivedecreasers, this);
     if(!this.dmg)
         this.dmg = 101;
     this.use = assault_objective_decrease_use;
     SetResourceExplicit(this, RES_HEALTH, ASSAULT_VALUE_INACTIVE);
     this.max_health = ASSAULT_VALUE_INACTIVE;
     this.enemy = NULL;
     InitializeEntity(this, target_objective_decrease_findtarget, INITPRIO_FINDTARGET);
 }
spawnfunc (func_assault_destructible)
Definition at line 356 of file sv_assault.qc.
References assault_attacker_team, destructible_heal(), g_assault, IL_PUSH(), NUM_TEAM_1, NUM_TEAM_2, spawnflags, and team.
 {
     if (!g_assault) { delete(this); return; }
     this.spawnflags = 3;
     this.event_heal = destructible_heal;
     IL_PUSH(g_assault_destructibles, this);
     if(assault_attacker_team == NUM_TEAM_1)
         this.team = NUM_TEAM_2;
     else
         this.team = NUM_TEAM_1;
     spawnfunc_func_breakable(this);
 }
spawnfunc (func_assault_wall)
Definition at line 372 of file sv_assault.qc.
References assault_setenemytoobjective(), assault_wall_think(), g_assault, InitializeEntity(), model, nextthink, setthink, solid, SOLID_BSP, and time.
 {
     if (!g_assault) { delete(this); return; }
     this.mdl = this.model;
     _setmodel(this, this.mdl);
     this.solid = SOLID_BSP;
     setthink(this, assault_wall_think);
     this.nextthink = time;
     InitializeEntity(this, assault_setenemytoobjective, INITPRIO_FINDTARGET);
 }
spawnfunc (target_assault_roundend)
Definition at line 384 of file sv_assault.qc.
References cnt, g_assault, target_assault_roundend_reset(), target_assault_roundend_use(), use, and winning.
 {
     if (!g_assault) { delete(this); return; }
     this.winning = 0; // round not yet won by attackers
     this.use = target_assault_roundend_use;
     this.cnt = 0; // first round
     this.reset = target_assault_roundend_reset;
 }
spawnfunc (target_assault_roundstart)
Definition at line 394 of file sv_assault.qc.
References assault_attacker_team, assault_roundstart_use(), assault_roundstart_use_this(), g_assault, InitializeEntity(), NUM_TEAM_1, and use.
 {
     if (!g_assault) { delete(this); return; }
     assault_attacker_team = NUM_TEAM_1;
     this.use = assault_roundstart_use;
     this.reset2 = assault_roundstart_use_this;
     InitializeEntity(this, assault_roundstart_use_this, INITPRIO_FINDTARGET);
 }
STATIC_INIT (g_assault)
Definition at line 17 of file sv_assault.qc.
References IL_NEW.
 {
     g_assault_destructibles = IL_NEW();
     g_assault_objectivedecreasers = IL_NEW();
     g_assault_objectives = IL_NEW();
 }
void target_assault_roundend_reset (entity this)
Definition at line 151 of file sv_assault.qc.
References cnt, and winning.
Referenced by spawnfunc().
 {
     //print("round end reset\n");
     ++this.cnt; // up round counter
     this.winning = false; // up round
 }
void target_assault_roundend_use (entity this, entity actor, entity trigger)
Definition at line 158 of file sv_assault.qc.
References winning.
Referenced by spawnfunc().
 {
     this.winning = 1; // round has been won by attackers
 }
void target_objective_decrease_activate (entity this)
Definition at line 116 of file sv_assault.qc.
References assault_attacker_team, assault_decreaser_sprite_visible(), assault_sprite, entity(), FOREACH_ENTITY_STRING, NULL, owner, SPRITERULE_TEAMPLAY, target, and targetname.
 {
     entity spr;
     this.owner = NULL;
     FOREACH_ENTITY_STRING(target, this.targetname,
     {
         if(it.assault_sprite != NULL)
         {
             WaypointSprite_Disown(it.assault_sprite, waypointsprite_deadlifetime);
             if(it.classname == "func_assault_destructible")
                 it.sprite = NULL; // TODO: just unsetting it?!
         }
         spr = WaypointSprite_SpawnFixed(WP_AssaultDefend, 0.5 * (it.absmin + it.absmax), it, assault_sprite, RADARICON_OBJECTIVE);
         spr.assault_decreaser = this;
         spr.waypointsprite_visible_for_player = assault_decreaser_sprite_visible;
         spr.classname = "sprite_waypoint";
         WaypointSprite_UpdateRule(spr, assault_attacker_team, SPRITERULE_TEAMPLAY);
         if(it.classname == "func_assault_destructible")
         {
             WaypointSprite_UpdateSprites(spr, WP_AssaultDefend, WP_AssaultDestroy, WP_AssaultDestroy);
             WaypointSprite_UpdateMaxHealth(spr, it.max_health);
             WaypointSprite_UpdateHealth(spr, GetResource(it, RES_HEALTH));
             it.sprite = spr;
         }
         else
             WaypointSprite_UpdateSprites(spr, WP_AssaultDefend, WP_AssaultPush, WP_AssaultPush);
     });
 }
void target_objective_decrease_findtarget (entity this)
Definition at line 146 of file sv_assault.qc.
References assault_setenemytoobjective().
Referenced by spawnfunc().
 {
     assault_setenemytoobjective(this);
 }
vector target_objective_spawn_evalfunc (entity this, entity player, entity spot, vector current)
Definition at line 38 of file sv_assault.qc.
References ASSAULT_VALUE_INACTIVE, GetResource(), and RES_HEALTH.
Referenced by spawnfunc().
 {
     float hlth = GetResource(this, RES_HEALTH);
     if (hlth < 0 || hlth >= ASSAULT_VALUE_INACTIVE)
         return '-1 0 0';
     return current;
 }
int WinningCondition_Assault ()
Definition at line 241 of file sv_assault.qc.
References as_round, AS_ROUND_DELAY, as_round_think(), assault_attacker_team, autocvar_g_campaign, bprint(), ceil(), classname, cvar_set(), entity(), find(), ftos(), NULL, NUM_TEAM_1, NUM_TEAM_2, SetWinners(), ST_ASSAULT_OBJECTIVES, team, TeamScore_AddToTeam(), time, WINNING_NO, WINNING_YES, and WinningConditionHelper().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(as_round)
         return WINNING_NO;
     WinningConditionHelper(NULL); // set worldstatus
     int status = WINNING_NO;
     // as the timelimit has not yet passed just assume the defending team will win
     if(assault_attacker_team == NUM_TEAM_1)
     {
         SetWinners(team, NUM_TEAM_2);
     }
     else
     {
         SetWinners(team, NUM_TEAM_1);
     }
     entity ent;
     ent = find(NULL, classname, "target_assault_roundend");
     if(ent)
     {
         if(ent.winning) // round end has been triggered by attacking team
         {
             bprint("Assault: round completed.\n");
             SetWinners(team, assault_attacker_team);
             TeamScore_AddToTeam(assault_attacker_team, ST_ASSAULT_OBJECTIVES, 666 - TeamScore_AddToTeam(assault_attacker_team, ST_ASSAULT_OBJECTIVES, 0));
             if(ent.cnt == 1 || autocvar_g_campaign) // this was the second round
             {
                 status = WINNING_YES;
             }
             else
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ASSAULT_OBJ_DESTROYED, ceil(time - game_starttime));
                 as_round = new(as_round);
                 as_round.think = as_round_think;
                 as_round.ent_winning = ent;
                 as_round.nextthink = time + AS_ROUND_DELAY;
                 game_stopped = true;
                 // make sure timelimit isn't hit while the game is blocked
                 if(autocvar_timelimit > 0)
                 if(time + AS_ROUND_DELAY >= game_starttime + autocvar_timelimit * 60)
                     cvar_set("timelimit", ftos(autocvar_timelimit + AS_ROUND_DELAY / 60));
             }
         }
     }
     return status;
 }
Variable Documentation
entity as_round
Definition at line 229 of file sv_assault.qc.
Referenced by as_round_think(), and WinningCondition_Assault().
entity ent_winning
Definition at line 230 of file sv_assault.qc.
IntrusiveList g_assault_destructibles
Definition at line 14 of file sv_assault.qc.
IntrusiveList g_assault_objectivedecreasers
Definition at line 15 of file sv_assault.qc.
IntrusiveList g_assault_objectives
Definition at line 16 of file sv_assault.qc.
entity sprite
Definition at line 11 of file sv_assault.qc.
Referenced by dom_controlpoint_setup(), dompoint_captured(), dompointtouch(), monster_changeteam(), Monster_Damage(), Monster_Frozen_Think(), Monster_Remove(), Monster_Spawn_Setup(), ons_ControlPoint_Reset(), ons_ControlPoint_Setup(), ons_GeneratorDamage(), ons_GeneratorReset(), ons_GeneratorSetup(), and SpawnGoal().