Xonotic: common/turrets/util.qc File Reference
common/turrets/util.qc File Reference
Functions
float turret_tag_fire_update ()
void FireImoBeam (vector start, vector end, vector smin, vector smax, float bforce, float f_dmg, float f_velfactor, int deathtype)
Function Documentation
void FireImoBeam (vector start, vector end, vector smin, vector smax, float bforce, float f_dmg, float f_velfactor, int deathtype)
Definition at line 23 of file util.qc.
References Damage(), entity(), findfloat(), normalize(), railgunhit, SELFPARAM, SOLID_BSP, SOLID_NOT, trace_endpos, trace_ent, trace_fraction, vector(), and world.
{SELFPARAM();
    vector hitloc, force, endpoint, dir;
    entity ent;
    dir = normalize(end - start);
    force = dir * bforce;
    // go a little bit into the wall because we need to hit this wall later
    end = end + dir;
    // trace multiple times until we hit a wall, each obstacle will be made unsolid.
    // note down which entities were hit so we can damage them later
    while (1)
    {
        tracebox(start, smin, smax, end, false, self);
        // if it is world we can't hurt it so stop now
        if (trace_ent == world || trace_fraction == 1)
            break;
        if (trace_ent.solid == SOLID_BSP)
            break;
        // make the entity non-solid so we can hit the next one
        trace_ent.railgunhit = true;
        trace_ent.railgunhitloc = end;
        trace_ent.railgunhitsolidbackup = trace_ent.solid;
        // stop if this is a wall
        // make the entity non-solid
        trace_ent.solid = SOLID_NOT;
    }
    endpoint = trace_endpos;
    // find all the entities the railgun hit and restore their solid state
    ent = findfloat(world, railgunhit, true);
    while (ent)
    {
        // restore their solid type
        ent.solid = ent.railgunhitsolidbackup;
        ent = findfloat(ent, railgunhit, true);
    }
    // find all the entities the railgun hit and hurt them
    ent = findfloat(world, railgunhit, true);
    while (ent)
    {
        // get the details we need to call the damage function
        hitloc = ent.railgunhitloc;
        ent.railgunhitloc = '0 0 0';
        ent.railgunhitsolidbackup = SOLID_NOT;
        ent.railgunhit = false;
        // apply the damage
        if (ent.takedamage)
        {
            Damage (ent, self, self, f_dmg, deathtype, hitloc, force);
            ent.velocity = ent.velocity * f_velfactor;
            //ent.alpha = 0.25 + random() * 0.75;
        }
        // advance to the next entity
        ent = findfloat(ent, railgunhit, true);
    }
    trace_endpos = endpoint;
}
float turret_tag_fire_update ()
Definition at line 5 of file util.qc.
References error(), gettagindex, normalize(), SELFPARAM, tur_head, and v_forward.
{SELFPARAM();
    if(!self.tur_head)
    {
        error("Call to turret_tag_fire_update with self.tur_head missing!\n");
        self.tur_shotorg = '0 0 0';
        return false;
    }
    self.tur_shotorg = gettaginfo(self.tur_head, gettagindex(self.tur_head, "tag_fire"));
    v_forward = normalize(v_forward);
    return true;
}