Xonotic: common/mutators/mutator/instagib/sv_instagib.qh File Reference
sv_instagib.qh File Reference
#include "items.qh"
#include <common/gamemodes/_mod.qh>
Functions
void instagib_extralife (entity this)
void instagib_invisibility (entity this)
void instagib_speed (entity this)
REGISTER_MUTATOR (mutator_instagib, autocvar_g_instagib &&!MapInfo_LoadedGametype.m_weaponarena)
Variables
bool autocvar_g_instagib
int autocvar_g_instagib_extralives
float autocvar_g_instagib_invis_alpha
float autocvar_g_rm
float autocvar_g_rm_damage
float autocvar_g_rm_edgedamage
float autocvar_g_rm_force
float autocvar_g_rm_laser
float autocvar_g_rm_laser_count
float autocvar_g_rm_laser_damage
float autocvar_g_rm_laser_force
float autocvar_g_rm_laser_lifetime
float autocvar_g_rm_laser_radius
float autocvar_g_rm_laser_rapid
float autocvar_g_rm_laser_rapid_delay
float autocvar_g_rm_laser_rapid_refire
float autocvar_g_rm_laser_refire
float autocvar_g_rm_laser_speed
float autocvar_g_rm_laser_spread
float autocvar_g_rm_laser_spread_random
float autocvar_g_rm_radius
Function Documentation
void instagib_extralife (entity this)
Definition at line 35 of file sv_instagib.qc.
References StartItem().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     StartItem(this, ITEM_ExtraLife);
 }
void instagib_invisibility (entity this)
Definition at line 29 of file sv_instagib.qc.
References autocvar_g_instagib_invisibility_time, and StartItem().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     this.strength_finished = autocvar_g_instagib_invisibility_time;
     StartItem(this, ITEM_Invisibility);
 }
void instagib_speed (entity this)
Definition at line 40 of file sv_instagib.qc.
References autocvar_g_instagib_speed_time, and StartItem().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     this.invincible_finished = autocvar_g_instagib_speed_time;
     StartItem(this, ITEM_Speed);
 }
REGISTER_MUTATOR (mutator_instagib , autocvar_g_instagib &&!MapInfo_LoadedGametype. m_weaponarena)
Definition at line 34 of file sv_instagib.qh.
References ITEM_FLAG_MUTATORBLOCKED, MUTATOR_ONADD, and MUTATOR_ONROLLBACK_OR_REMOVE.
 {
     MUTATOR_ONADD
     {
         ITEM_VaporizerCells.spawnflags &= ~ITEM_FLAG_MUTATORBLOCKED;
         ITEM_Invisibility.spawnflags &= ~ITEM_FLAG_MUTATORBLOCKED;
         ITEM_Speed.spawnflags &= ~ITEM_FLAG_MUTATORBLOCKED;
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         ITEM_VaporizerCells.spawnflags |= ITEM_FLAG_MUTATORBLOCKED;
         ITEM_Invisibility.spawnflags |= ITEM_FLAG_MUTATORBLOCKED;
         ITEM_Speed.spawnflags |= ITEM_FLAG_MUTATORBLOCKED;
     }
 }
Variable Documentation
bool autocvar_g_instagib
Definition at line 26 of file sv_instagib.qh.
int autocvar_g_instagib_extralives
Definition at line 28 of file sv_instagib.qh.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_instagib_invis_alpha
Definition at line 27 of file sv_instagib.qh.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_rm
Definition at line 7 of file sv_instagib.qh.
Referenced by instagib_ammocheck(), and MUTATOR_HOOKFUNCTION().
float autocvar_g_rm_damage
Definition at line 8 of file sv_instagib.qh.
float autocvar_g_rm_edgedamage
Definition at line 9 of file sv_instagib.qh.
float autocvar_g_rm_force
Definition at line 10 of file sv_instagib.qh.
float autocvar_g_rm_laser
Definition at line 12 of file sv_instagib.qh.
Referenced by instagib_ammocheck(), and MUTATOR_HOOKFUNCTION().
float autocvar_g_rm_laser_count
Definition at line 13 of file sv_instagib.qh.
float autocvar_g_rm_laser_damage
Definition at line 18 of file sv_instagib.qh.
float autocvar_g_rm_laser_force
Definition at line 24 of file sv_instagib.qh.
float autocvar_g_rm_laser_lifetime
Definition at line 17 of file sv_instagib.qh.
float autocvar_g_rm_laser_radius
Definition at line 23 of file sv_instagib.qh.
float autocvar_g_rm_laser_rapid
Definition at line 20 of file sv_instagib.qh.
float autocvar_g_rm_laser_rapid_delay
Definition at line 22 of file sv_instagib.qh.
float autocvar_g_rm_laser_rapid_refire
Definition at line 21 of file sv_instagib.qh.
float autocvar_g_rm_laser_refire
Definition at line 19 of file sv_instagib.qh.
float autocvar_g_rm_laser_speed
Definition at line 14 of file sv_instagib.qh.
float autocvar_g_rm_laser_spread
Definition at line 15 of file sv_instagib.qh.
float autocvar_g_rm_laser_spread_random
Definition at line 16 of file sv_instagib.qh.
float autocvar_g_rm_radius
Definition at line 11 of file sv_instagib.qh.