Xonotic: common/mutators/mutator/dynamic_handicap/sv_dynamic_handicap.qc File Reference
sv_dynamic_handicap.qc File Reference
Source file that contains implementation of the Dynamic handicap mutator.
#include "sv_dynamic_handicap.qh"
Functions
float DynamicHandicap_ClampHandicap (float handicap)
Clamps the value of the handicap.
float DynamicHandicap_GetBaseValue (entity player)
Returns the base value of the handicap.
float DynamicHandicap_ScaleHandicap (float handicap)
Scales the base value of the handicap.
void DynamicHandicap_UpdateHandicap (entity player)
Updates the handicap of a given player.
MUTATOR_HOOKFUNCTION (dynamic_handicap, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (dynamic_handicap, BuildMutatorsPrettyString)
MUTATOR_HOOKFUNCTION (dynamic_handicap, ClientConnect)
Hook that is called when player connects to the server.
MUTATOR_HOOKFUNCTION (dynamic_handicap, PlayerDies)
Hook that is called when player dies.
REGISTER_MUTATOR (dynamic_handicap, autocvar_g_dynamic_handicap)
Variables
int autocvar_g_dynamic_handicap
Whether to enable dynamic handicap.
float autocvar_g_dynamic_handicap_max
The maximum value of the handicap.
float autocvar_g_dynamic_handicap_min
The minimum value of the handicap.
float autocvar_g_dynamic_handicap_scale
The scale of the handicap.
Detailed Description
Source file that contains implementation of the Dynamic handicap mutator.
Author
Lyberta
Copyright
GNU GPLv2 or any later version.
Definition in file sv_dynamic_handicap.qc.
Function Documentation
float DynamicHandicap_ClampHandicap (float handicap)
Clamps the value of the handicap.
Parameters
[in] handicap Value to clamp.
Returns
Clamped value.
Definition at line 93 of file sv_dynamic_handicap.qc.
References autocvar_g_dynamic_handicap_max, and autocvar_g_dynamic_handicap_min.
Referenced by DynamicHandicap_UpdateHandicap().
 {
     if ((autocvar_g_dynamic_handicap_min >= 0) && (handicap <
         autocvar_g_dynamic_handicap_min))
     {
         handicap = autocvar_g_dynamic_handicap_min;
     }
     if ((autocvar_g_dynamic_handicap_max > 0) && (handicap >
         autocvar_g_dynamic_handicap_max))
     {
         handicap = autocvar_g_dynamic_handicap_max;
     }
     return handicap;
 }
float DynamicHandicap_GetBaseValue (entity player)
Returns the base value of the handicap.
Parameters
[in] player Player to evaluate.
Returns
Base handicap value.
Definition at line 47 of file sv_dynamic_handicap.qc.
References PlayerScore_Get.
Referenced by DynamicHandicap_UpdateHandicap().
 {
     int kills = PlayerScore_Get(player, SP_KILLS);
     int deaths = PlayerScore_Get(player, SP_DEATHS);
     if (kills == deaths)
     {
         return 1;
     }
     if (deaths == 0)
     {
         return kills;
     }
     if (kills == 0)
     {
         return 1 / deaths;
     }
     return kills / deaths;
 }
float DynamicHandicap_ScaleHandicap (float handicap)
Scales the base value of the handicap.
Parameters
[in] handicap Value to scale.
Returns
Scaled value.
Definition at line 66 of file sv_dynamic_handicap.qc.
References autocvar_g_dynamic_handicap_scale.
Referenced by DynamicHandicap_UpdateHandicap().
 {
     if (handicap == 1)
     {
         return 1;
     }
     if (autocvar_g_dynamic_handicap_scale == 1)
     {
         return handicap;
     }
     if (handicap > 1)
     {
         handicap -= 1;
         handicap *= autocvar_g_dynamic_handicap_scale;
         return handicap + 1;
     }
     if (handicap < 1)
     {
         handicap = 1 / handicap;
         handicap -= 1;
         handicap *= autocvar_g_dynamic_handicap_scale;
         handicap += 1;
         return 1 / handicap;
     }
     return 1;
 }
void DynamicHandicap_UpdateHandicap (entity player)
Updates the handicap of a given player.
Parameters
[in,out] player Player to update.
Returns
No return.
Definition at line 39 of file sv_dynamic_handicap.qc.
References DynamicHandicap_ClampHandicap(), DynamicHandicap_GetBaseValue(), DynamicHandicap_ScaleHandicap(), and Handicap_SetForcedHandicap().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     float handicap = DynamicHandicap_GetBaseValue(player);
     handicap = DynamicHandicap_ScaleHandicap(handicap);
     handicap = DynamicHandicap_ClampHandicap(handicap);
     Handicap_SetForcedHandicap(player, handicap);
 }
MUTATOR_HOOKFUNCTION (dynamic_handicap , BuildMutatorsString)
Definition at line 112 of file sv_dynamic_handicap.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":handicap");
 }
MUTATOR_HOOKFUNCTION (dynamic_handicap , BuildMutatorsPrettyString)
Definition at line 117 of file sv_dynamic_handicap.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Dynamic handicap");
 }
MUTATOR_HOOKFUNCTION (dynamic_handicap , ClientConnect)
Hook that is called when player connects to the server.
Definition at line 123 of file sv_dynamic_handicap.qc.
References DynamicHandicap_UpdateHandicap(), entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     DynamicHandicap_UpdateHandicap(player);
 }
MUTATOR_HOOKFUNCTION (dynamic_handicap , PlayerDies)
Hook that is called when player dies.
Definition at line 130 of file sv_dynamic_handicap.qc.
References DynamicHandicap_UpdateHandicap(), entity(), IS_CLIENT, and M_ARGV.
 {
     entity attacker = M_ARGV(1, entity);
     entity victim = M_ARGV(2, entity);
     DynamicHandicap_UpdateHandicap(victim);
     if (!IS_CLIENT(attacker))
     {
         return;
     }
     DynamicHandicap_UpdateHandicap(attacker);
 }
REGISTER_MUTATOR (dynamic_handicap , autocvar_g_dynamic_handicap)
Variable Documentation
int autocvar_g_dynamic_handicap
Whether to enable dynamic handicap.
Definition at line 10 of file sv_dynamic_handicap.qc.
float autocvar_g_dynamic_handicap_max
The maximum value of the handicap.
Definition at line 15 of file sv_dynamic_handicap.qc.
Referenced by DynamicHandicap_ClampHandicap().
float autocvar_g_dynamic_handicap_min
The minimum value of the handicap.
Definition at line 14 of file sv_dynamic_handicap.qc.
Referenced by DynamicHandicap_ClampHandicap().
float autocvar_g_dynamic_handicap_scale
The scale of the handicap.
Larget values mean more penalties for strong players and more buffs for weak players.
Definition at line 13 of file sv_dynamic_handicap.qc.
Referenced by DynamicHandicap_ScaleHandicap().