Xonotic: server/mutators/mutator/gamemode_invasion.qc File Reference
gamemode_invasion.qc File Reference
#include "gamemode_invasion.qh"
#include <common/monsters/sv_spawn.qh>
#include <common/monsters/sv_monsters.qh>
#include <server/teamplay.qh>
Functions
bool Invasion_CheckPlayers ()
bool Invasion_CheckWinner ()
void invasion_DelayedInit (entity this)
entity invasion_GetWaveEntity (int wavenum)
void invasion_Initialize ()
Monster invasion_PickMonster (int supermonster_count)
entity invasion_PickSpawn ()
void Invasion_RoundStart ()
void invasion_ScoreRules (int inv_teams)
void invasion_SpawnChosenMonster (Monster mon)
void invasion_SpawnMonsters (int supermonster_count)
MUTATOR_HOOKFUNCTION (inv, MonsterDies)
MUTATOR_HOOKFUNCTION (inv, MonsterSpawn)
MUTATOR_HOOKFUNCTION (inv, OnEntityPreSpawn)
MUTATOR_HOOKFUNCTION (inv, SV_StartFrame)
MUTATOR_HOOKFUNCTION (inv, PlayerRegen)
MUTATOR_HOOKFUNCTION (inv, PlayerSpawn)
MUTATOR_HOOKFUNCTION (inv, Damage_Calculate)
MUTATOR_HOOKFUNCTION (inv, SV_ParseClientCommand)
MUTATOR_HOOKFUNCTION (inv, BotShouldAttack)
MUTATOR_HOOKFUNCTION (inv, SetStartItems)
MUTATOR_HOOKFUNCTION (inv, AccuracyTargetValid)
MUTATOR_HOOKFUNCTION (inv, AllowMobSpawning)
MUTATOR_HOOKFUNCTION (inv, CheckAllowedTeams, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (inv, AllowMobButcher)
spawnfunc (invasion_wave)
spawnfunc (invasion_spawnpoint)
STATIC_INIT (g_invasion_waves)
STATIC_INIT (g_invasion_spawns)
Variables
int autocvar_g_invasion_monster_count
float autocvar_g_invasion_round_timelimit
float autocvar_g_invasion_spawn_delay
float autocvar_g_invasion_spawnpoint_spawn_delay
float autocvar_g_invasion_warmup
bool autocvar_g_invasion_zombies_only
IntrusiveList g_invasion_spawns
IntrusiveList g_invasion_waves
string spawnmob
Function Documentation
bool Invasion_CheckPlayers ()
Definition at line 282 of file gamemode_invasion.qc.
Referenced by invasion_DelayedInit().
 {
     return true;
 }
bool Invasion_CheckWinner ()
Definition at line 172 of file gamemode_invasion.qc.
References autocvar_g_invasion_round_timelimit, autocvar_g_invasion_warmup, g_monsters, get_monsterinfo, IL_CLEAR, IL_EACH, MON_FLAG_SUPERMONSTER, Monster_Remove(), NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, round_handler_GetEndTime, round_handler_Init(), teamplay, and time.
Referenced by invasion_DelayedInit().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         IL_EACH(g_monsters, true,
         {
             Monster_Remove(it);
         });
         IL_CLEAR(g_monsters);
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         round_handler_Init(5, autocvar_g_invasion_warmup, autocvar_g_invasion_round_timelimit);
         return 1;
     }
     float total_alive_monsters = 0, supermonster_count = 0, red_alive = 0, blue_alive = 0, yellow_alive = 0, pink_alive = 0;
     IL_EACH(g_monsters, it.health > 0,
     {
         if((get_monsterinfo(it.monsterid)).spawnflags & MON_FLAG_SUPERMONSTER)
             ++supermonster_count;
         ++total_alive_monsters;
         if(teamplay)
         switch(it.team)
         {
             case NUM_TEAM_1: ++red_alive; break;
             case NUM_TEAM_2: ++blue_alive; break;
             case NUM_TEAM_3: ++yellow_alive; break;
             case NUM_TEAM_4: ++pink_alive; break;
         }
     });
     if((total_alive_monsters + inv_numkilled) < inv_maxspawned && inv_maxcurrent < inv_maxspawned)
     {
         if(time >= inv_lastcheck)
         {
             invasion_SpawnMonsters(supermonster_count);
             inv_lastcheck = time + autocvar_g_invasion_spawn_delay;
         }
         return 0;
     }
     if(inv_numspawned < 1)
         return 0; // nothing has spawned yet
     if(teamplay)
     {
         if(((red_alive > 0) + (blue_alive > 0) + (yellow_alive > 0) + (pink_alive > 0)) > 1)
             return 0;
     }
     else if(inv_numkilled < inv_maxspawned)
         return 0;
     entity winner = NULL;
     float winning_score = 0, winner_team = 0;
     if(teamplay)
     {
         if(red_alive > 0) { winner_team = NUM_TEAM_1; }
         if(blue_alive > 0)
         if(winner_team) { winner_team = 0; }
         else { winner_team = NUM_TEAM_2; }
         if(yellow_alive > 0)
         if(winner_team) { winner_team = 0; }
         else { winner_team = NUM_TEAM_3; }
         if(pink_alive > 0)
         if(winner_team) { winner_team = 0; }
         else { winner_team = NUM_TEAM_4; }
     }
     else
     {
         FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(
             float cs = PlayerScore_Add(it, SP_KILLS, 0);
             if(cs > winning_score)
             {
                 winning_score = cs;
                 winner = it;
             }
         ));
     }
     IL_EACH(g_monsters, true,
     {
         Monster_Remove(it);
     });
     IL_CLEAR(g_monsters);
     if(teamplay)
     {
         if(winner_team)
         {
             Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         }
     }
     else if(winner)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_PLAYER_WIN, winner.netname);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_PLAYER_WIN, winner.netname);
     }
     round_handler_Init(5, autocvar_g_invasion_warmup, autocvar_g_invasion_round_timelimit);
     return 1;
 }
void invasion_DelayedInit (entity this)
Definition at line 480 of file gamemode_invasion.qc.
References autocvar_g_invasion_round_timelimit, autocvar_g_invasion_teams, autocvar_g_invasion_warmup, BIT, bound(), independent_players, inv_maxrounds, inv_roundcnt, Invasion_CheckPlayers(), Invasion_CheckWinner(), Invasion_RoundStart(), invasion_ScoreRules(), invasion_teams, round_handler_Init(), round_handler_Spawn(), and teams.
Referenced by invasion_Initialize().
 {
     if(autocvar_g_invasion_teams)
     {
         invasion_teams = bound(2, autocvar_g_invasion_teams, 4);
         int teams = 0;
         if(invasion_teams >= 1) teams |= BIT(0);
         if(invasion_teams >= 2) teams |= BIT(1);
         if(invasion_teams >= 3) teams |= BIT(2);
         if(invasion_teams >= 4) teams |= BIT(3);
         invasion_teams = teams; // now set it?
     }
     else
         invasion_teams = 0;
     independent_players = 1; // to disable extra useless scores
     invasion_ScoreRules(invasion_teams);
     independent_players = 0;
     round_handler_Spawn(Invasion_CheckPlayers, Invasion_CheckWinner, Invasion_RoundStart);
     round_handler_Init(5, autocvar_g_invasion_warmup, autocvar_g_invasion_round_timelimit);
     inv_roundcnt = 0;
     inv_maxrounds = 15; // 15?
 }
entity invasion_GetWaveEntity (int wavenum)
Definition at line 68 of file gamemode_invasion.qc.
References IL_EACH.
Referenced by invasion_SpawnChosenMonster().
 {
     IL_EACH(g_invasion_waves, it.cnt == wavenum,
     {
         return it; // found one
     });
     // if no specific one is found, find the last existing wave ent
     entity best = NULL;
     IL_EACH(g_invasion_waves, it.cnt <= wavenum,
     {
         if(!best || it.cnt > best.cnt)
             best = it;
     });
     return best;
 }
void invasion_Initialize ()
Definition at line 509 of file gamemode_invasion.qc.
References InitializeEntity(), INITPRIO_GAMETYPE, invasion_DelayedInit(), and NULL.
Referenced by REGISTER_MUTATOR().
 {
     InitializeEntity(NULL, invasion_DelayedInit, INITPRIO_GAMETYPE);
 }
Monster invasion_PickMonster (int supermonster_count)
Definition at line 38 of file gamemode_invasion.qc.
References autocvar_g_invasion_zombies_only, FOREACH, MON_FLAG_HIDDEN, MON_FLAG_SUPERMONSTER, MONSTER_SIZE_QUAKE, MONSTER_TYPE_FLY, MONSTER_TYPE_PASSIVE, MONSTER_TYPE_SWIM, MONSTER_TYPE_UNDEAD, RandomSelection_AddEnt, RandomSelection_chosen_ent, and RandomSelection_Init().
Referenced by invasion_SpawnMonsters().
 {
     RandomSelection_Init();
     FOREACH(Monsters, it != MON_Null,
     {
         if((it.spawnflags & MON_FLAG_HIDDEN) || (it.spawnflags & MONSTER_TYPE_PASSIVE) || (it.spawnflags & MONSTER_TYPE_FLY) || (it.spawnflags & MONSTER_TYPE_SWIM) ||
             (it.spawnflags & MONSTER_SIZE_QUAKE) || ((it.spawnflags & MON_FLAG_SUPERMONSTER) && supermonster_count >= 1))
             continue;
         if(autocvar_g_invasion_zombies_only && !(it.spawnflags & MONSTER_TYPE_UNDEAD))
             continue;
         RandomSelection_AddEnt(it, 1, 1);
     });
     return RandomSelection_chosen_ent;
 }
entity invasion_PickSpawn ()
Definition at line 55 of file gamemode_invasion.qc.
References autocvar_g_invasion_spawnpoint_spawn_delay, IL_EACH, RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), and time.
Referenced by invasion_SpawnChosenMonster().
 {
     RandomSelection_Init();
     IL_EACH(g_invasion_spawns, true,
     {
         RandomSelection_AddEnt(it, 1, ((time < it.spawnshieldtime) ? 0.2 : 1)); // give recently used spawnpoints a very low rating
         it.spawnshieldtime = time + autocvar_g_invasion_spawnpoint_spawn_delay;
     });
     return RandomSelection_chosen_ent;
 }
void Invasion_RoundStart ()
Definition at line 287 of file gamemode_invasion.qc.
References autocvar_g_invasion_monster_count, DistributeEvenly_Get(), DistributeEvenly_Init(), FOREACH_CLIENT, inv_maxcurrent, inv_maxrounds, inv_maxspawned, inv_monsters_perteam, inv_monsterskill, inv_numkilled, inv_numspawned, inv_roundcnt, invasion_teams, IS_PLAYER, LAMBDA, max(), NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, rint(), and teamplay.
Referenced by invasion_DelayedInit().
 {
     int numplayers = 0;
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(
         it.player_blocked = false;
         ++numplayers;
     ));
     if(inv_roundcnt < inv_maxrounds)
         inv_roundcnt += 1; // a limiter to stop crazy counts
     inv_monsterskill = inv_roundcnt + max(1, numplayers * 0.3);
     inv_maxcurrent = 0;
     inv_numspawned = 0;
     inv_numkilled = 0;
     inv_maxspawned = rint(max(autocvar_g_invasion_monster_count, autocvar_g_invasion_monster_count * (inv_roundcnt * 0.5)));
     if(teamplay)
     {
         DistributeEvenly_Init(inv_maxspawned, invasion_teams);
         inv_monsters_perteam[NUM_TEAM_1] = DistributeEvenly_Get(1);
         inv_monsters_perteam[NUM_TEAM_2] = DistributeEvenly_Get(1);
         if(invasion_teams >= 3) inv_monsters_perteam[NUM_TEAM_3] = DistributeEvenly_Get(1);
         if(invasion_teams >= 4) inv_monsters_perteam[NUM_TEAM_4] = DistributeEvenly_Get(1);
     }
 }
void invasion_ScoreRules (int inv_teams)
Definition at line 471 of file gamemode_invasion.qc.
References CheckAllowedTeams(), NULL, ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_basics(), ScoreRules_basics_end(), SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_SECONDARY, and ST_INV_KILLS.
Referenced by invasion_DelayedInit().
 {
     if(inv_teams) { CheckAllowedTeams(NULL); }
     ScoreRules_basics(inv_teams, 0, 0, false);
     if(inv_teams) ScoreInfo_SetLabel_TeamScore(ST_INV_KILLS, "frags", SFL_SORT_PRIO_PRIMARY);
     ScoreInfo_SetLabel_PlayerScore(SP_KILLS, "frags", ((inv_teams) ? SFL_SORT_PRIO_SECONDARY : SFL_SORT_PRIO_PRIMARY));
     ScoreRules_basics_end();
 }
void invasion_SpawnChosenMonster (Monster mon)
Definition at line 86 of file gamemode_invasion.qc.
References entity(), FOREACH_WORD, inv_roundcnt, invasion_GetWaveEntity(), invasion_PickSpawn(), RandomSelection_AddString, RandomSelection_chosen_string, RandomSelection_Init(), and spawn_point.
Referenced by invasion_SpawnMonsters().
 {
     entity monster;
     entity spawn_point = invasion_PickSpawn();
     entity wave_ent = invasion_GetWaveEntity(inv_roundcnt);
     string tospawn = "";
     if(wave_ent && wave_ent.spawnmob && wave_ent.spawnmob != "")
     {
         RandomSelection_Init();
         FOREACH_WORD(wave_ent.spawnmob, true,
         {
             RandomSelection_AddString(it, 1, 1);
         });
         tospawn = RandomSelection_chosen_string;
     }
     if(spawn_point == NULL)
     {
         LOG_TRACE("Warning: couldn't find any invasion_spawnpoint spawnpoints, attempting to spawn monsters in random locations");
         entity e = spawn();
         setsize(e, mon.m_mins, mon.m_maxs);
         if(MoveToRandomMapLocation(e, DPCONTENTS_SOLID | DPCONTENTS_CORPSE | DPCONTENTS_PLAYERCLIP, DPCONTENTS_SLIME | DPCONTENTS_LAVA | DPCONTENTS_SKY | DPCONTENTS_BODY | DPCONTENTS_DONOTENTER, Q3SURFACEFLAG_SKY, 10, 1024, 256))
             monster = spawnmonster(e, tospawn, mon.monsterid, NULL, NULL, e.origin, false, false, 2);
         else
         {
             delete(e);
             return;
         }
     }
     else // if spawnmob field falls through (unset), fallback to mon (relying on spawnmonster for that behaviour)
         monster = spawnmonster(spawn(), ((spawn_point.spawnmob && spawn_point.spawnmob != "") ? spawn_point.spawnmob : tospawn), mon.monsterid, spawn_point, spawn_point, spawn_point.origin, false, false, 2);
     if(!monster)
         return;
     monster.spawnshieldtime = time;
     if(spawn_point)
     {
         if(spawn_point.target_range)
             monster.target_range = spawn_point.target_range;
         monster.target2 = spawn_point.target2;
     }
     if(teamplay)
     {
         if(spawn_point && spawn_point.team && inv_monsters_perteam[spawn_point.team] > 0)
             monster.team = spawn_point.team;
         else
         {
             RandomSelection_Init();
             if(inv_monsters_perteam[NUM_TEAM_1] > 0) RandomSelection_AddFloat(NUM_TEAM_1, 1, 1);
             if(inv_monsters_perteam[NUM_TEAM_2] > 0) RandomSelection_AddFloat(NUM_TEAM_2, 1, 1);
             if(invasion_teams >= 3) if(inv_monsters_perteam[NUM_TEAM_3] > 0) { RandomSelection_AddFloat(NUM_TEAM_3, 1, 1); }
             if(invasion_teams >= 4) if(inv_monsters_perteam[NUM_TEAM_4] > 0) { RandomSelection_AddFloat(NUM_TEAM_4, 1, 1); }
             monster.team = RandomSelection_chosen_float;
         }
         monster_setupcolors(monster);
         if(monster.sprite)
         {
             WaypointSprite_UpdateTeamRadar(monster.sprite, RADARICON_DANGER, ((monster.team) ? Team_ColorRGB(monster.team) : '1 0 0'));
             monster.sprite.team = 0;
             monster.sprite.SendFlags |= 1;
         }
     }
     monster.monster_attack = false; // it's the player's job to kill all the monsters
     if(inv_roundcnt >= inv_maxrounds)
         monster.spawnflags |= MONSTERFLAG_MINIBOSS; // last round spawns minibosses
 }
void invasion_SpawnMonsters (int supermonster_count)
Definition at line 165 of file gamemode_invasion.qc.
References invasion_PickMonster(), and invasion_SpawnChosenMonster().
 {
     Monster chosen_monster = invasion_PickMonster(supermonster_count);
     invasion_SpawnChosenMonster(chosen_monster);
 }
MUTATOR_HOOKFUNCTION (inv , MonsterDies)
Definition at line 316 of file gamemode_invasion.qc.
References entity(), inv_maxcurrent, inv_monsters_perteam, inv_numkilled, IS_PLAYER, M_ARGV, MONSTERFLAG_RESPAWNED, PlayerScore_Add(), SAME_TEAM, ST_INV_KILLS, teamplay, and TeamScore_AddToTeam().
 {
     entity frag_target = M_ARGV(0, entity);
     entity frag_attacker = M_ARGV(1, entity);
     if(!(frag_target.spawnflags & MONSTERFLAG_RESPAWNED))
     {
         inv_numkilled += 1;
         inv_maxcurrent -= 1;
         if(teamplay) { inv_monsters_perteam[frag_target.team] -= 1; }
         if(IS_PLAYER(frag_attacker))
         if(SAME_TEAM(frag_attacker, frag_target)) // in non-teamplay modes, same team = same player, so this works
             PlayerScore_Add(frag_attacker, SP_KILLS, -1);
         else
         {
             PlayerScore_Add(frag_attacker, SP_KILLS, +1);
             if(teamplay)
                 TeamScore_AddToTeam(frag_attacker.team, ST_INV_KILLS, +1);
         }
     }
 }
MUTATOR_HOOKFUNCTION (inv , MonsterSpawn)
Definition at line 339 of file gamemode_invasion.qc.
References DPCONTENTS_BODY, DPCONTENTS_BOTCLIP, DPCONTENTS_MONSTERCLIP, DPCONTENTS_SOLID, entity(), get_monsterinfo, inv_maxcurrent, inv_monsterskill, inv_numspawned, M_ARGV, MON_FLAG_SUPERMONSTER, MONSTERFLAG_RESPAWNED, MONSTERFLAG_SPAWNED, and NULL.
 {
     entity mon = M_ARGV(0, entity);
     if(!(mon.spawnflags & MONSTERFLAG_SPAWNED))
         return true;
     if(!(mon.spawnflags & MONSTERFLAG_RESPAWNED))
     {
         inv_numspawned += 1;
         inv_maxcurrent += 1;
     }
     mon.monster_skill = inv_monsterskill;
     if((get_monsterinfo(mon.monsterid)).spawnflags & MON_FLAG_SUPERMONSTER)
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_INVASION_SUPERMONSTER, mon.monster_name);
     mon.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_BOTCLIP | DPCONTENTS_MONSTERCLIP;
 }
MUTATOR_HOOKFUNCTION (inv , OnEntityPreSpawn)
Definition at line 360 of file gamemode_invasion.qc.
References entity(), M_ARGV, MONSTERFLAG_SPAWNED, and startsWith.
 {
     entity ent = M_ARGV(0, entity);
     // TODO: allow these as "rogues" or something
     if(startsWith(ent.classname, "monster_"))
     if(!(ent.spawnflags & MONSTERFLAG_SPAWNED))
         return true;
 }
MUTATOR_HOOKFUNCTION (inv , SV_StartFrame)
Definition at line 370 of file gamemode_invasion.qc.
References inv_maxspawned, inv_numkilled, monsters_killed, and monsters_total.
 {
     monsters_total = inv_maxspawned; // TODO: make sure numspawned never exceeds maxspawned
     monsters_killed = inv_numkilled;
 }
MUTATOR_HOOKFUNCTION (inv , PlayerRegen)
Definition at line 376 of file gamemode_invasion.qc.
 {
     // no regeneration in invasion
     return true;
 }
MUTATOR_HOOKFUNCTION (inv , PlayerSpawn)
Definition at line 382 of file gamemode_invasion.qc.
References entity(), g_bot_targets, IL_REMOVE(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     if(player.bot_attack)
         IL_REMOVE(g_bot_targets, player);
     player.bot_attack = false;
 }
MUTATOR_HOOKFUNCTION (inv , Damage_Calculate)
Definition at line 391 of file gamemode_invasion.qc.
References entity(), IS_PLAYER, M_ARGV, and vector().
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float frag_damage = M_ARGV(4, float);
     vector frag_force = M_ARGV(6, vector);
     if(IS_PLAYER(frag_attacker) && IS_PLAYER(frag_target) && frag_attacker != frag_target)
     {
         frag_damage = 0;
         frag_force = '0 0 0';
         M_ARGV(4, float) = frag_damage;
         M_ARGV(6, vector) = frag_force;
     }
 }
MUTATOR_HOOKFUNCTION (inv , SV_ParseClientCommand)
Definition at line 408 of file gamemode_invasion.qc.
References cmd_name, entity(), ftos(), inv_maxspawned, inv_monsterskill, inv_numkilled, inv_numspawned, inv_roundcnt, M_ARGV, monsters_killed, monsters_total, MUTATOR_RETURNVALUE, sprint(), and strcat().
 {
     if(MUTATOR_RETURNVALUE) // command was already handled?
         return;
     entity player = M_ARGV(0, entity);
     string cmd_name = M_ARGV(1, string);
     if(cmd_name == "debuginvasion")
     {
         sprint(player, strcat("inv_maxspawned = ", ftos(inv_maxspawned), "\n"));
         sprint(player, strcat("inv_numspawned = ", ftos(inv_numspawned), "\n"));
         sprint(player, strcat("inv_numkilled = ", ftos(inv_numkilled), "\n"));
         sprint(player, strcat("inv_roundcnt = ", ftos(inv_roundcnt), "\n"));
         sprint(player, strcat("monsters_total = ", ftos(monsters_total), "\n"));
         sprint(player, strcat("monsters_killed = ", ftos(monsters_killed), "\n"));
         sprint(player, strcat("inv_monsterskill = ", ftos(inv_monsterskill), "\n"));
         return true;
     }
 }
MUTATOR_HOOKFUNCTION (inv , BotShouldAttack)
Definition at line 430 of file gamemode_invasion.qc.
References entity(), IS_MONSTER, and M_ARGV.
 {
     entity targ = M_ARGV(1, entity);
     if(!IS_MONSTER(targ))
         return true;
 }
MUTATOR_HOOKFUNCTION (inv , SetStartItems)
Definition at line 438 of file gamemode_invasion.qc.
References start_armorvalue, and start_health.
 {
     start_health = 200;
     start_armorvalue = 200;
 }
MUTATOR_HOOKFUNCTION (inv , AccuracyTargetValid)
Definition at line 444 of file gamemode_invasion.qc.
References entity(), IS_MONSTER, M_ARGV, MUT_ACCADD_INDIFFERENT, and MUT_ACCADD_INVALID.
 {
     entity frag_target = M_ARGV(1, entity);
     if(IS_MONSTER(frag_target))
         return MUT_ACCADD_INVALID;
     return MUT_ACCADD_INDIFFERENT;
 }
MUTATOR_HOOKFUNCTION (inv , AllowMobSpawning)
Definition at line 453 of file gamemode_invasion.qc.
References M_ARGV.
 {
     // monster spawning disabled during an invasion
     M_ARGV(1, string) = "You cannot spawn monsters during an invasion!";
     return true;
 }
MUTATOR_HOOKFUNCTION (inv , CheckAllowedTeams , CBC_ORDER_EXCLUSIVE)
Definition at line 460 of file gamemode_invasion.qc.
References invasion_teams, and M_ARGV.
 {
     M_ARGV(0, float) = invasion_teams;
 }
MUTATOR_HOOKFUNCTION (inv , AllowMobButcher)
Definition at line 465 of file gamemode_invasion.qc.
References M_ARGV.
 {
     M_ARGV(0, string) = "This command does not work during an invasion!";
     return true;
 }
spawnfunc (invasion_wave)
Definition at line 23 of file gamemode_invasion.qc.
References g_invasion, and IL_PUSH().
 {
     if(!g_invasion) { delete(this); return; }
     IL_PUSH(g_invasion_waves, this);
 }
spawnfunc (invasion_spawnpoint)
Definition at line 30 of file gamemode_invasion.qc.
References classname, g_invasion, and IL_PUSH().
 {
     if(!g_invasion) { delete(this); return; }
     this.classname = "invasion_spawnpoint";
     IL_PUSH(g_invasion_spawns, this);
 }
STATIC_INIT (g_invasion_waves)
Definition at line 9 of file gamemode_invasion.qc.
References IL_NEW.
 { g_invasion_waves = IL_NEW(); }
STATIC_INIT (g_invasion_spawns)
Definition at line 12 of file gamemode_invasion.qc.
References IL_NEW.
 { g_invasion_spawns = IL_NEW(); }
Variable Documentation
int autocvar_g_invasion_monster_count
Definition at line 17 of file gamemode_invasion.qc.
Referenced by Invasion_RoundStart().
float autocvar_g_invasion_round_timelimit
Definition at line 14 of file gamemode_invasion.qc.
Referenced by Invasion_CheckWinner(), and invasion_DelayedInit().
float autocvar_g_invasion_spawn_delay
Definition at line 19 of file gamemode_invasion.qc.
float autocvar_g_invasion_spawnpoint_spawn_delay
Definition at line 15 of file gamemode_invasion.qc.
Referenced by invasion_PickSpawn().
float autocvar_g_invasion_warmup
Definition at line 16 of file gamemode_invasion.qc.
Referenced by Invasion_CheckWinner(), and invasion_DelayedInit().
bool autocvar_g_invasion_zombies_only
Definition at line 18 of file gamemode_invasion.qc.
Referenced by invasion_PickMonster().
IntrusiveList g_invasion_spawns
Definition at line 11 of file gamemode_invasion.qc.
IntrusiveList g_invasion_waves
Definition at line 8 of file gamemode_invasion.qc.
string spawnmob
Definition at line 21 of file gamemode_invasion.qc.
Referenced by spawnfunc().