Xonotic: server/mutators/mutator/gamemode_tdm.qc File Reference
gamemode_tdm.qc File Reference
#include "gamemode_tdm.qh"
Macros
#define GAMEMODE_TDM_H
Functions
REGISTER_MUTATOR (tdm, false)
void tdm_DelayedInit (entity this)
Variables
int autocvar_g_tdm_point_leadlimit
int autocvar_g_tdm_point_limit
bool autocvar_g_tdm_team_spawns
Macro Definition Documentation
#define GAMEMODE_TDM_H
Definition at line 3 of file gamemode_tdm.qc.
Function Documentation
REGISTER_MUTATOR (tdm , false)
Definition at line 10 of file gamemode_tdm.qc.
References ActivateTeamplay(), autocvar_g_tdm_point_leadlimit, autocvar_g_tdm_point_limit, autocvar_g_tdm_team_spawns, error(), have_team_spawns, InitializeEntity(), INITPRIO_GAMETYPE, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, SetLimits(), tdm_DelayedInit(), time, and world.
 {
     MUTATOR_ONADD
     {
         if (time > 1) // game loads at time 1
             error("This is a game type and it cannot be added at runtime.");
         InitializeEntity(world, tdm_DelayedInit, INITPRIO_GAMETYPE);
         ActivateTeamplay();
         SetLimits(autocvar_g_tdm_point_limit, autocvar_g_tdm_point_leadlimit, -1, -1);
         if (autocvar_g_tdm_team_spawns)
             have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         // we actually cannot roll back tdm_Initialize here
         // BUT: we don't need to! If this gets called, adding always
         // succeeds.
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
void tdm_DelayedInit (entity this)
Referenced by REGISTER_MUTATOR().
Variable Documentation
int autocvar_g_tdm_point_leadlimit
Definition at line 6 of file gamemode_tdm.qc.
Referenced by REGISTER_MUTATOR().
int autocvar_g_tdm_point_limit
Definition at line 5 of file gamemode_tdm.qc.
Referenced by REGISTER_MUTATOR().
bool autocvar_g_tdm_team_spawns
Definition at line 7 of file gamemode_tdm.qc.
Referenced by REGISTER_MUTATOR().