Xonotic: common/weapons/config.qc File Reference
config.qc File Reference
#include "config.qh"
Functions
void Dump_Weapon_Settings ()
float W_Config_Queue_Compare (int root, int child, entity pass)
void W_Config_Queue_Swap (int root, int child, entity pass)
Function Documentation
void Dump_Weapon_Settings ()
Definition at line 25 of file config.qc.
References FOREACH, heapsort(), LOG_INFO, NULL, string_null, W_Config_Queue_Compare(), W_Config_Queue_Swap(), and WEP_FLAG_MUTATORBLOCKED.
Referenced by GENERIC_COMMAND().
 {
     int totalweapons = 0, totalsettings = 0;
     FOREACH(Weapons, it != WEP_Null, {
         // step 1: clear the queue
         WEP_CONFIG_COUNT = 0;
         for (int x = 0; x <= MAX_WEP_CONFIG; ++x)
             { wep_config_queue[x] = string_null; }
         // step 2: build new queue
         it.wr_config(it);
         // step 3: sort queue
         heapsort(WEP_CONFIG_COUNT, W_Config_Queue_Swap, W_Config_Queue_Compare, NULL);
         // step 4: write queue
         WEP_CONFIG_WRITETOFILE(sprintf(
             "// {{{ #%d: %s%s\n",
             i,
             it.m_name,
             ((it.spawnflags & WEP_FLAG_MUTATORBLOCKED) ? " (MUTATOR WEAPON)" : "")
         ));
         for (int x = 0; x <= WEP_CONFIG_COUNT; ++x) { WEP_CONFIG_WRITETOFILE(wep_config_queue[x]); }
         WEP_CONFIG_WRITETOFILE("// }}}\n");
         // step 5: debug info
         LOG_INFO(sprintf("#%d: %s: %d settings...\n", i, it.m_name, WEP_CONFIG_COUNT));
         totalweapons += 1;
         totalsettings += WEP_CONFIG_COUNT;
     });
     // clear queue now that we're finished
     WEP_CONFIG_COUNT = 0;
     for(int x = 0; x <= MAX_WEP_CONFIG; ++x)
         { wep_config_queue[x] = string_null; }
     // extra information
     LOG_INFO(sprintf("Totals: %d weapons, %d settings\n", totalweapons, totalsettings));
 }
float W_Config_Queue_Compare (int root, int child, entity pass)
Definition at line 20 of file config.qc.
References strcmp.
Referenced by Dump_Weapon_Settings().
 {
     return strcmp(wep_config_queue[root], wep_config_queue[child]);
 }
void W_Config_Queue_Swap (int root, int child, entity pass)
Definition at line 13 of file config.qc.
Referenced by Dump_Weapon_Settings().
 {
     string oldroot = wep_config_queue[root];
     wep_config_queue[root] = wep_config_queue[child];
     wep_config_queue[child] = oldroot;
 }