Xonotic: CvarStringSource Class Reference
CvarStringSource Class Reference
Public Member Functions
CvarStringSource (string cv, string sep)
ATTRIB (StringSource, StringSource_str, string)
ATTRIB (StringSource, StringSource_sep, string)
ATTRIB (CvarStringSource, CvarStringSource_cvar, string)
virtual void describe ()
virtual void destroy ()
cleanup on shutdown.
virtual void display ()
virtual void getEntry ()
get entry i passing name and icon through returns if it is not null returns DataSource_false if out of bounds otherwise returns an entity or DataSource_true
virtual void indexOf ()
return the index of the first match for find.
virtual void reload ()
reload all entries matching filter returning how many matches were found
Static Public Attributes
static entity false = NULL
static entity true = NEW(Object)
Detailed Description
Definition at line 29 of file datasource.qh.
Constructor & Destructor Documentation
CvarStringSource::CvarStringSource (string cv, string sep)
Definition at line 22 of file datasource.qc.
References CONSTRUCT.
     {
         CONSTRUCT(CvarStringSource);
         this.CvarStringSource_cvar = cv;
         this.StringSource_sep = sep;
     }
Member Function Documentation
StringSource::ATTRIB (StringSource , StringSource_str , string) inherited
StringSource::ATTRIB (StringSource , StringSource_sep , string) inherited
CvarStringSource::ATTRIB (CvarStringSource , CvarStringSource_cvar , string)
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 295 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void DataSource::destroy () inline virtual inherited
cleanup on shutdown.
optional
Definition at line 17 of file datasource.qh.
 { }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 309 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
void CvarStringSource::getEntry () virtual
get entry i passing name and icon through returns if it is not null returns DataSource_false if out of bounds otherwise returns an entity or DataSource_true
Reimplemented from StringSource.
Definition at line 28 of file datasource.qc.
References cvar_string(), string_null, and SUPER.
     {
         string s = this.CvarStringSource_cvar;
         this.StringSource_str = s ? cvar_string(s) : string_null;
         return SUPER(CvarStringSource).getEntry(this, i, returns);
     }
virtual void DataSource::indexOf () inline virtual inherited
return the index of the first match for find.
optional
Definition at line 13 of file datasource.qh.
 { return -1; }
void CvarStringSource::reload () virtual
reload all entries matching filter returning how many matches were found
Reimplemented from StringSource.
Definition at line 34 of file datasource.qc.
References cvar_string(), string_null, and SUPER.
     {
         string s = this.CvarStringSource_cvar;
         this.StringSource_str = s ? cvar_string(s) : string_null;
         return SUPER(CvarStringSource).reload(this, filter);
     }
Member Data Documentation
entity DataSource::false = NULL static inherited
Definition at line 5 of file datasource.qh.
entity DataSource::true = NEW(Object) static inherited
Definition at line 4 of file datasource.qh.
The documentation for this class was generated from the following files:
menu/xonotic/datasource.qh
menu/xonotic/datasource.qc