Xonotic: menu/xonotic/dialog_multiplayer_join_termsofservice.qc File Reference
dialog_multiplayer_join_termsofservice.qc File Reference
#include "dialog_multiplayer_join_termsofservice.qh"
#include "textbox.qh"
#include <lib/urllib.qh>
Functions
void AdditionalServerInfo_OnGet (entity fh, entity me, int status)
entity makeXonoticServerToSTab ()
void XonoticServerToSTab_fill (entity me)
void XonoticServerToSTab_loadToS (entity me, string downloadurl)
Function Documentation
AdditionalServerInfo_OnGet()
void AdditionalServerInfo_OnGet (entity fh, entity me, int status)
Definition at line 28 of file dialog_multiplayer_join_termsofservice.qc.
References strcat(), strfree, strzone(), url_fclose(), url_fgets(), URL_READY_CANREAD, URL_READY_CLOSED, and URL_READY_ERROR.
Referenced by XonoticServerToSTab_loadToS().
 {
     switch (status) {
         case URL_READY_CLOSED:
         {
             break;
         }
         case URL_READY_ERROR:
         {
             me.text = strzone("Error reading ToS");
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         case URL_READY_CANREAD:
         {
             strfree(me.text);
             string temp = "";
             for (string s; (s = url_fgets(fh)); )
             {
                 if (temp != "")
                     temp = strcat(temp, "\n", s);
                 else
                     temp = s;
             }
             url_fclose(fh);
             me.text = strzone(temp);
             me.textBox.setText(me.textBox, me.text);
             break;
         }
         default:
         {
             break;
         }
     }
 }
makeXonoticServerToSTab()
entity makeXonoticServerToSTab ()
Definition at line 7 of file dialog_multiplayer_join_termsofservice.qc.
References entity(), and NEW.
 {
     entity me;
     me = NEW(XonoticServerToSTab);
     me.configureDialog(me);
     return me;
 }
XonoticServerToSTab_fill()
void XonoticServerToSTab_fill (entity me)
Definition at line 20 of file dialog_multiplayer_join_termsofservice.qc.
References entity(), and makeXonoticTextBox().
 {
     entity e;
     me.TR(me);
     me.TD(me, me.rows, me.columns, e = makeXonoticTextBox());
     me.textBox = e;
 }
XonoticServerToSTab_loadToS()
void XonoticServerToSTab_loadToS (entity me, string downloadurl)
Definition at line 15 of file dialog_multiplayer_join_termsofservice.qc.
References AdditionalServerInfo_OnGet(), FILE_READ, and url_single_fopen().
 {
     url_single_fopen(downloadurl, FILE_READ, AdditionalServerInfo_OnGet, me);
 }