Xonotic: server/weapons/selection.qh File Reference
selection.qh File Reference
#include <common/weapons/_all.qh>
#include <common/stats.qh>
Macros
#define w_getbestweapon(ent, wepent) REGISTRY_GET(Weapons, W_GetCycleWeapon(ent, CS_CVAR(ent).cvar_cl_weaponpriority, 0, -1, false, true, wepent))
Functions
bool client_hasweapon (entity this, Weapon wpn,.entity weaponentity, float andammo, bool complain)
void Send_WeaponComplain (entity e, float wpn, float type)
void W_CycleWeapon (entity this, string weaponorder, float dir,.entity weaponentity)
float W_GetCycleWeapon (entity this, string weaponorder, float dir, float imp, float complain, float skipmissing,.entity weaponentity)
void W_LastWeapon (entity this,.entity weaponentity)
void W_NextWeapon (entity this, float list,.entity weaponentity)
void W_NextWeaponOnImpulse (entity this, float imp,.entity weaponentity)
void W_PreviousWeapon (entity this, float list,.entity weaponentity)
void W_SwitchToOtherWeapon (entity this,.entity weaponentity)
bool W_SwitchWeapon (entity this, Weapon imp,.entity weaponentity)
void W_SwitchWeapon_Force (Player this, Weapon w,.entity weaponentity)
void W_SwitchWeapon_TryOthers (entity this, Weapon imp,.entity weaponentity)
Variables
int autocvar_g_showweaponspawns
bool autocvar_g_weaponswitch_debug
bool autocvar_g_weaponswitch_debug_alternate
WepSet dual_weapons
float hasweapon_complain_spam
int selectweapon
int weaponcomplainindex
Macro Definition Documentation
w_getbestweapon
#define w_getbestweapon (ent, wepent) REGISTRY_GET(Weapons, W_GetCycleWeapon(ent, CS_CVAR(ent).cvar_cl_weaponpriority, 0, -1, false, true, wepent))
Definition at line 23 of file selection.qh.
Referenced by GetCvars(), GiveItems(), IMPULSE(), Item_GiveTo(), MUTATOR_HOOKFUNCTION(), PutPlayerInServer(), REGISTER_MUTATOR(), W_SwitchToOtherWeapon(), W_ThrowWeapon(), and W_WeaponFrame().
Function Documentation
client_hasweapon()
bool client_hasweapon (entity this, Weapon wpn, .entity weaponentity, float andammo, bool complain)
Definition at line 48 of file selection.qc.
References autocvar_g_showweaponspawns, autocvar_g_weaponswitch_debug, CS(), dual_weapons, FOREACH, hasweapon_complain_spam, IL_EACH, Weapon::impulse, IS_REAL_CLIENT, items, Weapon::m_id, OFFHAND_HOOK, PS, Send_WeaponComplain(), SND, Weapon::spawnflags, sprint(), time, Weapon_whereis(), weaponslot(), WEP_FLAG_DUALWIELD, and WepSet_FromWeapon.
Referenced by bot_cmd_select_weapon(), havocbot_chooseweapon(), havocbot_movetogoal(), NIX_GiveCurrentWeapon(), REGISTER_MUTATOR(), W_GetCycleWeapon(), W_LastWeapon(), and W_SwitchWeapon().
 {
     float f = 0;
     if (time < CS(this).hasweapon_complain_spam)
         complain = 0;
     // ignore hook button when using other offhand equipment
     if (this.offhand != OFFHAND_HOOK)
     if (wpn == WEP_HOOK && !((STAT(WEAPONS, this) | weaponsInMap) & WepSet_FromWeapon(wpn)))
         complain = 0;
     if (complain)
         CS(this).hasweapon_complain_spam = time + 0.2;
     if (wpn == WEP_Null)
     {
         if (complain)
             sprint(this, "Invalid weapon\n");
         return false;
     }
     if (autocvar_g_weaponswitch_debug == 2 && weaponslot(weaponentity) > 0 && !(wpn.spawnflags & WEP_FLAG_DUALWIELD) && !(PS(this).dual_weapons & wpn.m_wepset))
         return false; // no complaints needed
     if (STAT(WEAPONS, this) & WepSet_FromWeapon(wpn))
     {
         if (andammo)
         {
             if(this.items & IT_UNLIMITED_AMMO)
             {
                 f = 1;
             }
             else
             {
                 f = wpn.wr_checkammo1(wpn, this, weaponentity) + wpn.wr_checkammo2(wpn, this, weaponentity);
                 // always allow selecting the Mine Layer if we placed mines, so that we can detonate them
                 if(wpn == WEP_MINE_LAYER)
                     IL_EACH(g_mines, it.owner == this && it.weaponentity_fld == weaponentity,
                     {
                         f = 1;
                         break; // no need to continue
                     });
             }
             if (!f)
             {
                 if (complain)
                 if(IS_REAL_CLIENT(this))
                 {
                     play2(this, SND(UNAVAILABLE));
                     Send_WeaponComplain (this, wpn.m_id, 0);
                 }
                 return false;
             }
         }
         return true;
     }
     if (complain)
     {
         // DRESK - 3/16/07
         // Report Proper Weapon Status / Modified Weapon Ownership Message
         if (weaponsInMap & WepSet_FromWeapon(wpn))
         {
             Send_WeaponComplain(this, wpn.m_id, 1);
             if(autocvar_g_showweaponspawns < 3)
                 Weapon_whereis(wpn, this);
             else
             {
                 FOREACH(Weapons, it.impulse == wpn.impulse,
                 {
                     Weapon_whereis(it, this);
                 });
             }
         }
         else
         {
             Send_WeaponComplain (this, wpn.m_id, 2);
         }
         play2(this, SND(UNAVAILABLE));
     }
     return false;
 }
Send_WeaponComplain()
void Send_WeaponComplain (entity e, float wpn, float type)
Definition at line 18 of file selection.qc.
References msg_entity, MSG_ONE, and WriteByte().
Referenced by client_hasweapon().
 {
     msg_entity = e;
     WriteHeader(MSG_ONE, TE_CSQC_WEAPONCOMPLAIN);
     WriteByte(MSG_ONE, wpn);
     WriteByte(MSG_ONE, type);
 }
W_CycleWeapon()
void W_CycleWeapon (entity this, string weaponorder, float dir, .entity weaponentity)
Definition at line 302 of file selection.qc.
References REGISTRY_GET, W_GetCycleWeapon(), and W_SwitchWeapon().
Referenced by for(), W_NextWeapon(), and W_PreviousWeapon().
 {
     float w;
     w = W_GetCycleWeapon(this, weaponorder, dir, -1, 1, true, weaponentity);
     if(w > 0)
         W_SwitchWeapon(this, REGISTRY_GET(Weapons, w), weaponentity);
 }
W_GetCycleWeapon()
float W_GetCycleWeapon (entity this, string weaponorder, float dir, float imp, float complain, float skipmissing, .entity weaponentity)
Definition at line 131 of file selection.qc.
References car(), cdr(), client_hasweapon(), entity(), FOREACH, REGISTRY_GET, selectweapon, stof(), weaponcomplainindex, weaponorder, and WEP_FLAG_MUTATORBLOCKED.
Referenced by W_CycleWeapon(), and W_NextWeaponOnImpulse().
 {
     // We cannot tokenize in this function, as GiveItems calls this
     // function. Thus we must use car/cdr.
     float weaponwant, first_valid, prev_valid, switchtonext, switchtolast;
     WepSet wepset = '0 0 0';
     switchtonext = switchtolast = 0;
     first_valid = prev_valid = 0;
     float weaponcur;
     entity wep;
     if(skipmissing || this.(weaponentity).selectweapon == 0)
         weaponcur = this.(weaponentity).m_switchweapon.m_id;
     else
         weaponcur = this.(weaponentity).selectweapon;
     if(dir == 0)
         switchtonext = 1;
     int c = 0;
     string rest = weaponorder;
     while(rest != "")
     {
         weaponwant = stof(car(rest)); rest = cdr(rest);
         wep = REGISTRY_GET(Weapons, weaponwant);
         wepset = wep.m_wepset;
         if(imp >= 0)
         if(wep.impulse != imp)
             continue;
         bool have_other = false;
         FOREACH(Weapons, it != WEP_Null, {
             if(i != weaponwant)
             if(it.impulse == imp || imp < 0)
             if((STAT(WEAPONS, this) & (it.m_wepset)) || (weaponsInMap & (it.m_wepset)))
                 have_other = true;
         });
         // skip weapons we don't own that aren't normal and aren't in the map
         if(!(STAT(WEAPONS, this) & wepset))
         if(!(weaponsInMap & wepset))
         if((wep.spawnflags & WEP_FLAG_MUTATORBLOCKED) || have_other)
             continue;
         ++c;
         if(!skipmissing || client_hasweapon(this, wep, weaponentity, true, false))
         {
             if(switchtonext)
                 return weaponwant;
             if(!first_valid)
                 first_valid = weaponwant;
             if(weaponwant == weaponcur)
             {
                 if(dir >= 0)
                     switchtonext = 1;
                 else if(prev_valid)
                     return prev_valid;
                 else
                     switchtolast = 1;
             }
             prev_valid = weaponwant;
         }
     }
     if(first_valid)
     {
         if(switchtolast)
             return prev_valid;
         else
             return first_valid;
     }
     // complain (but only for one weapon on the button that has been pressed)
     if(complain)
     {
         this.weaponcomplainindex += 1;
         c = (this.weaponcomplainindex % c) + 1;
         rest = weaponorder;
         while(rest != "")
         {
             weaponwant = stof(car(rest)); rest = cdr(rest);
             wep = REGISTRY_GET(Weapons, weaponwant);
             wepset = wep.m_wepset;
             if(imp >= 0)
                 if(wep.impulse != imp)
                     continue;
             bool have_other = false;
             FOREACH(Weapons, it != WEP_Null, {
                 if(i != weaponwant)
                 if(it.impulse == imp || imp < 0)
                 if((STAT(WEAPONS, this) & (it.m_wepset)) || (weaponsInMap & (it.m_wepset)))
                     have_other = true;
             });
             // skip weapons we don't own that aren't normal and aren't in the map
             if(!(STAT(WEAPONS, this) & wepset))
             if(!(weaponsInMap & wepset))
             if((wep.spawnflags & WEP_FLAG_MUTATORBLOCKED) || have_other)
                 continue;
             --c;
             if(c == 0)
             {
                 client_hasweapon(this, wep, weaponentity, true, true);
                 break;
             }
         }
     }
     return 0;
 }
W_LastWeapon()
void W_LastWeapon (entity this, .entity weaponentity)
Definition at line 341 of file selection.qc.
References client_hasweapon(), cnt, REGISTRY_GET, W_SwitchToOtherWeapon(), and W_SwitchWeapon().
Referenced by IMPULSE().
 {
     Weapon wep = REGISTRY_GET(Weapons, this.(weaponentity).cnt);
     if (client_hasweapon(this, wep, weaponentity, true, false))
         W_SwitchWeapon(this, wep, weaponentity);
     else
         W_SwitchToOtherWeapon(this, weaponentity);
 }
W_NextWeapon()
void W_NextWeapon (entity this, float list, .entity weaponentity)
W_NextWeaponOnImpulse()
void W_NextWeaponOnImpulse (entity this, float imp, .entity weaponentity)
Definition at line 310 of file selection.qc.
References CS_CVAR, REGISTRY_GET, W_GetCycleWeapon(), and W_SwitchWeapon().
Referenced by W_SwitchWeapon_TryOthers(), and weapon_group_handle().
 {
     float w;
     w = W_GetCycleWeapon(this, CS_CVAR(this).cvar_cl_weaponpriority, +1, imp, 1, (CS_CVAR(this).cvar_cl_weaponimpulsemode == 0), weaponentity);
     if(w > 0)
         W_SwitchWeapon(this, REGISTRY_GET(Weapons, w), weaponentity);
 }
W_PreviousWeapon()
void W_PreviousWeapon (entity this, float list, .entity weaponentity)
Definition at line 330 of file selection.qc.
References CS_CVAR, W_CycleWeapon(), weaponorder_byid, and weaponorder_byimpulse.
Referenced by IMPULSE().
 {
     if(list == 0)
         W_CycleWeapon(this, weaponorder_byid, +1, weaponentity);
     else if(list == 1)
         W_CycleWeapon(this, CS_CVAR(this).weaponorder_byimpulse, +1, weaponentity);
     else if(list == 2)
         W_CycleWeapon(this, CS_CVAR(this).cvar_cl_weaponpriority, +1, weaponentity);
 }
W_SwitchToOtherWeapon()
void W_SwitchToOtherWeapon (entity this, .entity weaponentity)
Definition at line 253 of file selection.qc.
References w_getbestweapon, W_SwitchWeapon_Force(), and WepSet_FromWeapon.
Referenced by W_LastWeapon(), W_Reload(), and weapon_prepareattack_checkammo().
 {
     // hack to ensure it switches to an OTHER weapon (in case the other fire mode still has ammo, we want that anyway)
     Weapon ww;
     WepSet set = WepSet_FromWeapon(this.(weaponentity).m_weapon);
     if (STAT(WEAPONS, this) & set)
     {
         STAT(WEAPONS, this) &= ~set;
         ww = w_getbestweapon(this, weaponentity);
         STAT(WEAPONS, this) |= set;
     }
     else
     {
         ww = w_getbestweapon(this, weaponentity);
     }
     if (ww == WEP_Null) return;
     W_SwitchWeapon_Force(this, ww, weaponentity);
 }
W_SwitchWeapon()
bool W_SwitchWeapon (entity this, Weapon imp, .entity weaponentity)
Definition at line 272 of file selection.qc.
References client_hasweapon(), CS_CVAR, entity(), Weapon::m_id, selectweapon, W_SwitchWeapon_Force(), and weaponLocked().
Referenced by GiveBall(), IMPULSE(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), W_CycleWeapon(), W_LastWeapon(), W_NextWeaponOnImpulse(), W_SwitchWeapon_TryOthers(), and W_WeaponFrame().
 {
     if(this.(weaponentity).m_switchweapon != w)
     {
         if(client_hasweapon(this, w, weaponentity, true, true))
         {
             W_SwitchWeapon_Force(this, w, weaponentity);
             return true;
         }
         else
         {
             this.(weaponentity).selectweapon = w.m_id; // update selectweapon anyway
             return false;
         }
     }
     else if(!weaponLocked(this) && CS_CVAR(this).cvar_cl_weapon_switch_reload)
     {
         entity actor = this;
         w.wr_reload(w, actor, weaponentity);
     }
     return true; // player already has the weapon out or needs to reload
 }
W_SwitchWeapon_Force()
void W_SwitchWeapon_Force (Player this, Weapon w, .entity weaponentity)
Definition at line 243 of file selection.qc.
References entity(), Weapon::m_id, and TC.
Referenced by W_SwitchToOtherWeapon(), and W_SwitchWeapon().
 {
     TC(Weapon, wep);
     entity w_ent = this.(weaponentity);
     w_ent.cnt = w_ent.m_switchweapon.m_id;
     w_ent.m_switchweapon = wep;
     w_ent.selectweapon = wep.m_id;
 }
W_SwitchWeapon_TryOthers()
void W_SwitchWeapon_TryOthers (entity this, Weapon imp, .entity weaponentity)
Definition at line 296 of file selection.qc.
References CS_CVAR, Weapon::impulse, W_NextWeaponOnImpulse(), and W_SwitchWeapon().
Referenced by weapon_byid_handle().
 {
     if(!W_SwitchWeapon(this, w, weaponentity) && CS_CVAR(this).cvar_cl_weapon_switch_fallback_to_impulse)
         W_NextWeaponOnImpulse(this, w.impulse, weaponentity);
 }
Variable Documentation
autocvar_g_showweaponspawns
int autocvar_g_showweaponspawns
Definition at line 6 of file selection.qh.
Referenced by client_hasweapon(), and Weapon_whereis().
autocvar_g_weaponswitch_debug
bool autocvar_g_weaponswitch_debug
Definition at line 7 of file selection.qh.
Referenced by client_hasweapon(), for(), IMPULSE(), PutPlayerInServer(), W_Reload(), W_WeaponFrame(), weapon_byid_handle(), weapon_group_handle(), and X().
autocvar_g_weaponswitch_debug_alternate
bool autocvar_g_weaponswitch_debug_alternate
Definition at line 8 of file selection.qh.
Referenced by weapon_prepareattack_do().
dual_weapons
WepSet dual_weapons
Definition at line 12 of file selection.qh.
Referenced by client_hasweapon().
hasweapon_complain_spam
float hasweapon_complain_spam
Definition at line 17 of file selection.qh.
Referenced by client_hasweapon().
selectweapon
int selectweapon
Definition at line 10 of file selection.qh.
Referenced by W_GetCycleWeapon(), and W_SwitchWeapon().
weaponcomplainindex
int weaponcomplainindex
Definition at line 20 of file selection.qh.
Referenced by W_GetCycleWeapon().