Xonotic: common/effects/qc/globalsound.qc File Reference
globalsound.qc File Reference
#include "globalsound.qh"
#include <common/ent_cs.qh>
#include <common/animdecide.qh>
Functions
string _GetPlayerSoundSampleField (string type, bool voice)
void ClearPlayerSounds (entity this)
entity GetPlayerSound (string type)
string GetPlayerSoundSampleField (string type)
entity GetVoiceMessage (string type)
string GetVoiceMessageSampleField (string type)
float GlobalSound_pitch (float _pitch)
string GlobalSound_sample (string pair, float r)
bool LoadPlayerSounds (entity this, string f, bool strict)
void PrecacheGlobalSound (string sample)
void PrecachePlayerSounds (string f)
void UpdatePlayerSounds (entity this)
Variables
bool autocvar_g_debug_defaultsounds
string model_for_playersound
int skin_for_playersound
Function Documentation
string _GetPlayerSoundSampleField (string type, bool voice)
Definition at line 202 of file globalsound.qc.
References entity(), GetPlayerSound(), GetPlayerSoundSampleField_notFound, and GetVoiceMessage().
Referenced by GetPlayerSoundSampleField(), and GetVoiceMessageSampleField().
     {
         GetPlayerSoundSampleField_notFound = false;
         entity e = voice ? GetVoiceMessage(type) : GetPlayerSound(type);
         if (e) return e.m_playersoundfld;
         GetPlayerSoundSampleField_notFound = true;
         return playersound_taunt.m_playersoundfld;
     }
void ClearPlayerSounds (entity this)
Definition at line 246 of file globalsound.qc.
References FOREACH, and strfree.
Referenced by UpdatePlayerSounds().
         {
             FOREACH(PlayerSounds, true, {
                 .string fld = it.m_playersoundfld;
                 if (this.(fld))
                 {
                     strfree(this.(fld));
                 }
             });
         }
entity GetPlayerSound (string type)
Definition at line 196 of file globalsound.qc.
References FOREACH, and NULL.
Referenced by _GetPlayerSoundSampleField().
     {
         FOREACH(PlayerSounds, it.m_playersoundstr == type && it.instanceOfVoiceMessage == false, return it);
         return NULL;
     }
string GetPlayerSoundSampleField (string type)
Definition at line 241 of file globalsound.qc.
References _GetPlayerSoundSampleField().
Referenced by LoadPlayerSounds().
         {
             return _GetPlayerSoundSampleField(type, false);
         }
entity GetVoiceMessage (string type)
Definition at line 190 of file globalsound.qc.
References FOREACH, and NULL.
Referenced by _GetPlayerSoundSampleField(), and ClientCommand_voice().
     {
         FOREACH(PlayerSounds, it.m_playersoundstr == type && it.instanceOfVoiceMessage == true, return it);
         return NULL;
     }
string GetVoiceMessageSampleField (string type)
Definition at line 211 of file globalsound.qc.
References _GetPlayerSoundSampleField().
Referenced by LoadPlayerSounds().
     {
         return _GetPlayerSoundSampleField(type, true);
     }
float GlobalSound_pitch (float _pitch)
Definition at line 158 of file globalsound.qc.
Referenced by UpdatePlayerSounds().
     {
         // customizable gradient function that crosses (0,a), (c,1) and asymptotically approaches b
         float a = 1.5; // max pitch
         float b = 0.75; // min pitch
         float c = 100; // standard pitch (scale * 100)
         float d = _pitch;
         float pitch_shift = (b*d*(a-1) + a*c*(1-b)) / (d*(a-1) + c*(1-b));
         return pitch_shift * 100;
     }
string GlobalSound_sample (string pair, float r)
Definition at line 144 of file globalsound.qc.
References car(), cdr(), floor(), and stof().
Referenced by Monster_Sound(), and UpdatePlayerSounds().
     {
         int n;
         {
             string s = cdr(pair);
             if (s) n = stof(s);
             else n = 0;
         }
         string sample = car(pair);
         if (n > 0) sample = sprintf("%s%d.wav", sample, floor(r * n + 1));  // randomization
         else sample = sprintf("%s.wav", sample);
         return sample;
     }
bool LoadPlayerSounds (entity this, string f, bool strict)
Definition at line 257 of file globalsound.qc.
References argv(), fclose(), fgets(), FILE_READ, fopen(), GetPlayerSoundSampleField(), GetPlayerSoundSampleField_notFound, GetVoiceMessageSampleField(), LOG_TRACEF, LOG_WARNF, strcat(), strcpy, and tokenize_console.
Referenced by UpdatePlayerSounds().
         {
             int fh = fopen(f, FILE_READ);
             if (fh < 0)
             {
                 if (strict) LOG_WARNF("Player sound file not found: %s", f);
                 return false;
             }
             for (string s; (s = fgets(fh)); )
             {
                 int n = tokenize_console(s);
                 if (n != 3)
                 {
                     if (n != 0) LOG_WARNF("Invalid sound info line: %s", s);
                     continue;
                 }
                 string key = argv(0);
                 var.string field = GetPlayerSoundSampleField(key);
                 if (GetPlayerSoundSampleField_notFound) field = GetVoiceMessageSampleField(key);
                 if (GetPlayerSoundSampleField_notFound)
                 {
                     LOG_TRACEF("Invalid sound info field in player sound file '%s': %s", f, key);
                     continue;
                 }
                 string file = argv(1);
                 string variants = argv(2);
                 strcpy(this.(field), strcat(file, " ", variants));
             }
             fclose(fh);
             return true;
         }
void PrecacheGlobalSound (string sample)
Definition at line 170 of file globalsound.qc.
References car(), cdr(), precache_sound(), and stof().
Referenced by Monster_Sound_Precache(), PRECACHE(), PrecachePlayerSounds(), and STATIC_INIT().
     {
         int n;
         {
             string s = cdr(sample);
             if (s) n = stof(s);
             else n = 0;
         }
         sample = car(sample);
         if (n > 0)
         {
             for (int i = 1; i <= n; ++i)
                 precache_sound(sprintf("%s%d.wav", sample, i));
         }
         else
         {
             precache_sound(sprintf("%s.wav", sample));
         }
     }
void PrecachePlayerSounds (string f)
Definition at line 216 of file globalsound.qc.
References argv(), fclose(), fgets(), FILE_READ, fopen(), LOG_WARNF, PrecacheGlobalSound(), strcat(), and tokenize_console.
Referenced by PRECACHE(), and precache_playermodel().
     {
         int fh = fopen(f, FILE_READ);
         if (fh < 0)
         {
             LOG_WARNF("Player sound file not found: %s", f);
             return;
         }
         for (string s; (s = fgets(fh)); )
         {
             int n = tokenize_console(s);
             if (n != 3)
             {
                 if (n != 0) LOG_WARNF("Invalid sound info line: %s", s);
                 continue;
             }
             string file = argv(1);
             string variants = argv(2);
             PrecacheGlobalSound(strcat(file, " ", variants));
         }
         fclose(fh);
     }
void UpdatePlayerSounds (entity this)
Definition at line 294 of file globalsound.qc.
References ANIMACTION_TAUNT, animdecide_setaction(), ATTEN_MIN, ATTEN_NONE, ATTEN_NORM, backtrace, classname, ClearPlayerSounds(), CS(), entity(), FOREACH_CLIENT, get_model_datafilename(), GlobalSound_pitch(), GlobalSound_sample(), IS_DEAD, IS_PLAYER, IS_REAL_CLIENT, LoadPlayerSounds(), model, model_for_playersound, MSG_ALL, MSG_BROADCAST, msg_entity, MSG_ONE, NULL, pusher, random(), SAME_TEAM, scale, skin, skin_for_playersound, strcpy, VOICETYPE_AUTOTAUNT, VOICETYPE_LASTATTACKER, VOICETYPE_LASTATTACKER_ONLY, VOICETYPE_PLAYERSOUND, VOICETYPE_TAUNT, VOICETYPE_TEAMRADIO, VOL_BASE, and X.
Referenced by FixPlayermodel(), and setplayermodel().
         {
             if (this.model == this.model_for_playersound && this.skin == this.skin_for_playersound) return;
             strcpy(this.model_for_playersound, this.model);
             this.skin_for_playersound = this.skin;
             ClearPlayerSounds(this);
             LoadPlayerSounds(this, "sound/player/default.sounds", true);
             if (this.model == "null"
             #ifdef SVQC
                 && autocvar_g_debug_globalsounds
             #endif
             ) return;
             if (autocvar_g_debug_defaultsounds) return;
             if (LoadPlayerSounds(this, get_model_datafilename(this.model, this.skin, "sounds"), false)) return;
             LoadPlayerSounds(this, get_model_datafilename(this.model, 0, "sounds"), true);
         }
Variable Documentation
bool autocvar_g_debug_defaultsounds
Definition at line 292 of file globalsound.qc.
string model_for_playersound
Definition at line 289 of file globalsound.qc.
Referenced by UpdatePlayerSounds().
int skin_for_playersound
Definition at line 290 of file globalsound.qc.
Referenced by UpdatePlayerSounds().