Xonotic: menu/item/modalcontroller.qh File Reference
modalcontroller.qh File Reference
#include "container.qh"
Classes
class ModalController
Functions
void DialogCloseButton_Click (entity button, entity tab)
void DialogOpenButton_Click (entity button, entity tab)
void DialogOpenButton_Click_withCoords (entity button, entity tab, vector theOrigin, vector theSize)
void TabButton_Click (entity button, entity tab)
Variables
float ModalController_state
vector origin
vector size
entity tabSelectingButton
Function Documentation
void DialogCloseButton_Click (entity button, entity tab)
Definition at line 44 of file modalcontroller.qc.
Referenced by Dialog_close().
     {
         tab.parent.hideChild(tab.parent, tab, 0);
     }
void DialogOpenButton_Click (entity button, entity tab)
Definition at line 30 of file modalcontroller.qc.
References DialogOpenButton_Click_withCoords().
Referenced by Button_playClickSound(), DemoButton_Click(), DemoConfirm_Check_Gamestatus(), HUDSetup_Check_Gamestatus(), KeyBinder_Bind_Edit(), XonoticLanguageList_setLanguage(), XonoticMiscSettingsTab_fill(), and XonoticServerCreateTab_fill().
     {
         DialogOpenButton_Click_withCoords(button, tab, button.origin, button.size);
     }
void DialogOpenButton_Click_withCoords (entity button, entity tab, vector theOrigin, vector theSize)
Definition at line 35 of file modalcontroller.qc.
     {
         if (tab.ModalController_state) return;
         if (button) button.forcePressed = 1;
         if (tab.parent.focusedChild) tab.parent.focusedChild.saveFocus(tab.parent.focusedChild);
         tab.ModalController_controllingButton = button;
         tab.parent.showChild(tab.parent, tab, theOrigin, theSize, 0);
     }
void TabButton_Click (entity button, entity tab)
Definition at line 21 of file modalcontroller.qc.
Referenced by m_activate_window(), and ModalController_addTab().
     {
         if (tab.ModalController_state == 1) return;
         tab.parent.hideAll(tab.parent, 0);
         button.forcePressed = 1;
         tab.ModalController_controllingButton = button;
         tab.parent.showChild(tab.parent, tab, button.origin, button.size, 0);
     }
Variable Documentation
float ModalController_state
Definition at line 43 of file modalcontroller.qh.
vector origin
Definition at line 45 of file modalcontroller.qh.
vector size
Definition at line 46 of file modalcontroller.qh.
entity tabSelectingButton
Definition at line 44 of file modalcontroller.qh.