Xonotic: server/command/cmd.qh File Reference
cmd.qh File Reference
Functions
void ClientCommand_macro_write_aliases (float fh)
string MapVote_Suggest (entity this, string m)
Variables
int autocvar_sv_clientcommand_antispam_count
float autocvar_sv_clientcommand_antispam_time
bool autocvar_sv_ready_restart
bool autocvar_sv_ready_restart_repeatable
float cmd_floodcount
float cmd_floodtime
Function Documentation
void ClientCommand_macro_write_aliases (float fh)
Definition at line 882 of file cmd.qc.
References CLIENT_COMMANDS, and NULL.
Referenced by GENERIC_COMMAND().
 {
     #define CLIENT_COMMAND(name, function, description) \
         { CMD_Write_Alias("qc_cmd_cmd", name, description); }
     CLIENT_COMMANDS(NULL, 0, 0, "");
 #undef CLIENT_COMMAND
 }
string MapVote_Suggest (entity this, string m)
Definition at line 119 of file mapvoting.qc.
References autocvar_g_maplist_votable_suggestions, autocvar_g_maplist_votable_suggestions_override_mostrecent, autocvar_sv_eventlog, autocvar_sv_vote_gametype, floor(), ftos(), GameLogEcho(), gametypevote, GameTypeVote_MapInfo_FixName(), Map_IsRecent(), MapInfo_CheckMap(), mapvote_initialized, mapvote_suggestion_ptr, mapvote_suggestions, playerid, random(), strcat(), strunzone(), and strzone().
Referenced by ClientCommand_suggestmap().
 {
     int i;
     if(m == "")
         return "That's not how to use this command.";
     if(!autocvar_g_maplist_votable_suggestions)
         return "Suggestions are not accepted on this server.";
     if(mapvote_initialized)
     if(!gametypevote)
         return "Can't suggest - voting is already in progress!";
     m = GameTypeVote_MapInfo_FixName(m);
     if (!m)
         return "The map you suggested is not available on this server.";
     if(!autocvar_g_maplist_votable_suggestions_override_mostrecent)
         if(Map_IsRecent(m))
             return "This server does not allow for recent maps to be played again. Please be patient for some rounds.";
     if (!autocvar_sv_vote_gametype)
     if(!MapInfo_CheckMap(m))
         return "The map you suggested does not support the current game mode.";
     for(i = 0; i < mapvote_suggestion_ptr; ++i)
         if(mapvote_suggestions[i] == m)
             return "This map was already suggested.";
     if(mapvote_suggestion_ptr >= MAPVOTE_COUNT)
     {
         i = floor(random() * mapvote_suggestion_ptr);
     }
     else
     {
         i = mapvote_suggestion_ptr;
         mapvote_suggestion_ptr += 1;
     }
     if(mapvote_suggestions[i] != "")
         strunzone(mapvote_suggestions[i]);
     mapvote_suggestions[i] = strzone(m);
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":vote:suggested:", m, ":", ftos(this.playerid)));
     return strcat("Suggestion of ", m, " accepted.");
 }
Variable Documentation
int autocvar_sv_clientcommand_antispam_count
Definition at line 4 of file cmd.qh.
Referenced by SV_ParseClientCommand_floodcheck().
float autocvar_sv_clientcommand_antispam_time
Definition at line 3 of file cmd.qh.
Referenced by SV_ParseClientCommand_floodcheck().
bool autocvar_sv_ready_restart
Definition at line 5 of file cmd.qh.
Referenced by ClientCommand_ready().
bool autocvar_sv_ready_restart_repeatable
Definition at line 6 of file cmd.qh.
Referenced by ClientCommand_ready().
float cmd_floodcount
Definition at line 9 of file cmd.qh.
float cmd_floodtime
Definition at line 8 of file cmd.qh.