Xonotic: menu/xonotic/dialog_settings_game_hud.qh File Reference
dialog_settings_game_hud.qh File Reference
#include "tab.qh"
#include "../gamesettings.qh"
Classes
class XonoticGameHUDSettingsTab
Functions
void HUDSetup_Start (entity me, entity btn)
entity makeXonoticGameHUDSettingsTab ()
REGISTER_SETTINGS (HUD, makeXonoticGameHUDSettingsTab())
Function Documentation
void HUDSetup_Start (entity me, entity btn)
Definition at line 6 of file dialog_settings_game_hudconfirm.qc.
References GAME_CONNECTED, GAME_ISSERVER, gamestatus, and localcmd.
Referenced by HUDSetup_Check_Gamestatus(), and XonoticHUDConfirmDialog_fill().
 {
     if (!(gamestatus & (GAME_CONNECTED | GAME_ISSERVER)))
         localcmd("map _hudsetup\n");
     else
         localcmd("togglemenu 0\n");
     localcmd("_hud_configure 1\n");
 }
entity makeXonoticGameHUDSettingsTab ()
Definition at line 26 of file dialog_settings_game_hud.qc.
References entity(), and NEW.
 {
     entity me;
     me = NEW(XonoticGameHUDSettingsTab);
     me.configureDialog(me);
     return me;
 }
REGISTER_SETTINGS (HUD , makeXonoticGameHUDSettingsTab())