Xonotic: Racer Class Reference
Racer Class Reference
Public Member Functions
ATTRIB (Vehicle, m_icon, string)
hud icon
ATTRIB (Vehicle, tag_head, string)
tur_head model tag
ATTRIB (Vehicle, tag_hud, string)
hud model tag
ATTRIB (Vehicle, tag_view, string)
cockpit model tag
ATTRIB (Vehicle, PlayerPhysplug, bool(entity, float))
player physics mod
virtual void describe ()
virtual void display ()
virtual void vr_crosshair ()
(CLIENT) logic to run every frame
virtual void vr_death ()
(SERVER) called when vehicle dies
virtual void vr_enter ()
(SERVER) called when a player enters this vehicle
virtual void vr_gunner_enter ()
(SERVER) called when a player enters this vehicle while occupied
virtual void vr_hud ()
(CLIENT) logic to run every frame
virtual void vr_impact ()
(SERVER) called when a vehicle hits something
virtual void vr_precache ()
(BOTH) precaches models/sounds used by this vehicle
virtual void vr_setup ()
(BOTH) setup vehicle data
virtual void vr_spawn ()
(SERVER) called when the vehicle re-spawns
virtual void vr_think ()
(SERVER) logic to run every frame
Public Attributes
string head_model = "null"
float height = 200
string hud_model = "models/vehicles/wakizashi_cockpit.dpm"
string m_icon = "vehicle_racer"
vector maxs = '120 120 40' * 0.5
string mdl = "models/vehicles/wakizashi.dpm"
vector mins = '-120 -120 -40' * 0.5
string model = "models/vehicles/wakizashi.dpm"
string netname = "racer"
int spawnflags = VHF_DMGSHAKE | VHF_DMGROLL
string tag_head = ""
string tag_hud = ""
string tag_view = "tag_viewport"
string vehicle_name = _("Racer")
int vehicleid = 0
vector view_ofs = '0 0 50'
Detailed Description
Definition at line 5 of file racer.qh.
Member Function Documentation
Vehicle::ATTRIB (Vehicle , m_icon , string) inherited
hud icon
Vehicle::ATTRIB (Vehicle , tag_head , string) inherited
tur_head model tag
Vehicle::ATTRIB (Vehicle , tag_hud , string) inherited
hud model tag
Vehicle::ATTRIB (Vehicle , tag_view , string) inherited
cockpit model tag
Vehicle::ATTRIB (Vehicle , PlayerPhysplug , bool(entity, float)) inherited
player physics mod
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Vehicle::vr_crosshair () inline virtual inherited
(CLIENT) logic to run every frame
Definition at line 57 of file vehicle.qh.
Referenced by HUD_Crosshair_Vehicle().
 { }
virtual void Vehicle::vr_death () inline virtual inherited
(SERVER) called when vehicle dies
Definition at line 43 of file vehicle.qh.
Referenced by vehicles_damage().
 { }
virtual void Vehicle::vr_enter () inline virtual inherited
(SERVER) called when a player enters this vehicle
Definition at line 47 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_gunner_enter () inline virtual inherited
(SERVER) called when a player enters this vehicle while occupied
Definition at line 49 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_hud () inline virtual inherited
(CLIENT) logic to run every frame
Definition at line 55 of file vehicle.qh.
Referenced by HUD_Vehicle().
 { }
virtual void Vehicle::vr_impact () inline virtual inherited
(SERVER) called when a vehicle hits something
Definition at line 53 of file vehicle.qh.
Referenced by vehicles_touch().
 { }
virtual void Vehicle::vr_precache () inline virtual inherited
(BOTH) precaches models/sounds used by this vehicle
Definition at line 45 of file vehicle.qh.
Referenced by vehicle_initialize().
 { }
virtual void Vehicle::vr_setup () inline virtual inherited
(BOTH) setup vehicle data
Definition at line 39 of file vehicle.qh.
Referenced by NET_HANDLE(), and vehicle_initialize().
 { }
virtual void Vehicle::vr_spawn () inline virtual inherited
(SERVER) called when the vehicle re-spawns
Definition at line 51 of file vehicle.qh.
Referenced by vehicles_spawn().
 { }
virtual void Vehicle::vr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 41 of file vehicle.qh.
Referenced by vehicles_think().
 { }
Member Data Documentation
string Racer::head_model = "null"
Definition at line 13 of file racer.qh.
float Racer::height = 200
Definition at line 10 of file racer.qh.
string Racer::hud_model = "models/vehicles/wakizashi_cockpit.dpm"
Definition at line 14 of file racer.qh.
string Racer::m_icon = "vehicle_racer"
Definition at line 20 of file racer.qh.
vector Racer::maxs = '120 120 40' * 0.5
Definition at line 8 of file racer.qh.
string Racer::mdl = "models/vehicles/wakizashi.dpm"
Definition at line 11 of file racer.qh.
vector Racer::mins = '-120 -120 -40' * 0.5
Definition at line 7 of file racer.qh.
string Racer::model = "models/vehicles/wakizashi.dpm"
Definition at line 12 of file racer.qh.
string Racer::netname = "racer"
Definition at line 18 of file racer.qh.
int Racer::spawnflags = VHF_DMGSHAKE | VHF_DMGROLL
Definition at line 6 of file racer.qh.
string Racer::tag_head = ""
Definition at line 15 of file racer.qh.
string Racer::tag_hud = ""
Definition at line 16 of file racer.qh.
string Racer::tag_view = "tag_viewport"
Definition at line 17 of file racer.qh.
string Racer::vehicle_name = _("Racer")
Definition at line 19 of file racer.qh.
int Vehicle::vehicleid = 0 inherited
Definition at line 4 of file vehicle.qh.
Referenced by vehicle_initialize().
vector Racer::view_ofs = '0 0 50'
Definition at line 9 of file racer.qh.
The documentation for this class was generated from the following file:
common/vehicles/vehicle/racer.qh