Xonotic: common/gamemodes/gamemode/cts/sv_cts.qc File Reference
sv_cts.qc File Reference
#include "sv_cts.qh"
#include <server/race.qh>
#include <server/items.qh>
Functions
void cts_EventLog (string mode, entity actor)
void cts_Initialize ()
void cts_ScoreRules ()
void havocbot_role_cts (entity this)
MUTATOR_HOOKFUNCTION (cts, PlayerPhysics)
MUTATOR_HOOKFUNCTION (cts, reset_map_global)
MUTATOR_HOOKFUNCTION (cts, ClientConnect)
MUTATOR_HOOKFUNCTION (cts, AbortSpeedrun)
MUTATOR_HOOKFUNCTION (cts, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (cts, PlayerSpawn)
MUTATOR_HOOKFUNCTION (cts, PutClientInServer)
MUTATOR_HOOKFUNCTION (cts, PlayerDies)
MUTATOR_HOOKFUNCTION (cts, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (cts, GetPressedKeys)
MUTATOR_HOOKFUNCTION (cts, ForbidThrowCurrentWeapon)
MUTATOR_HOOKFUNCTION (cts, FilterItem)
MUTATOR_HOOKFUNCTION (cts, Damage_Calculate)
MUTATOR_HOOKFUNCTION (cts, ForbidPlayerScore_Clear)
MUTATOR_HOOKFUNCTION (cts, GetRecords)
MUTATOR_HOOKFUNCTION (cts, ClientKill)
MUTATOR_HOOKFUNCTION (cts, Race_FinalCheckpoint)
MUTATOR_HOOKFUNCTION (cts, HideTeamNagger)
MUTATOR_HOOKFUNCTION (cts, FixClientCvars)
MUTATOR_HOOKFUNCTION (cts, WantWeapon)
MUTATOR_HOOKFUNCTION (cts, ForbidDropCurrentWeapon)
Variables
float autocvar_g_cts_finish_kill_delay
bool autocvar_g_cts_removeprojectiles
bool autocvar_g_cts_selfdamage
float race_checkpoint
Function Documentation
void cts_EventLog (string mode, entity actor)
Definition at line 62 of file sv_cts.qc.
References autocvar_sv_eventlog, ftos(), GameLogEcho(), NULL, and strcat().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(autocvar_sv_eventlog)
         GameLogEcho(strcat(":cts:", mode, ":", ((actor != NULL) ? (strcat(":", ftos(actor.playerid))) : "")));
 }
void cts_Initialize ()
Definition at line 413 of file sv_cts.qc.
References cts_ScoreRules().
Referenced by REGISTER_MUTATOR().
 {
     cts_ScoreRules();
 }
void cts_ScoreRules ()
Definition at line 48 of file sv_cts.qc.
References g_race_qualifying, GameRules_score_enabled(), GameRules_scoring, SFL_LOWER_IS_BETTER, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_SECONDARY, and SFL_TIME.
Referenced by cts_Initialize().
 {
     GameRules_score_enabled(false);
     GameRules_scoring(0, 0, 0, {
         if (g_race_qualifying) {
             field(SP_RACE_FASTEST, "fastest", SFL_SORT_PRIO_PRIMARY | SFL_LOWER_IS_BETTER | SFL_TIME);
         } else {
             field(SP_RACE_LAPS, "laps", SFL_SORT_PRIO_PRIMARY);
             field(SP_RACE_TIME, "time", SFL_SORT_PRIO_SECONDARY | SFL_LOWER_IS_BETTER | SFL_TIME);
             field(SP_RACE_FASTEST, "fastest", SFL_LOWER_IS_BETTER | SFL_TIME);
         }
     });
 }
void havocbot_role_cts (entity this)
Definition at line 12 of file sv_cts.qc.
References g_racecheckpoints, IL_EACH, IS_DEAD, LABEL, navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_routerating(), origin, race_checkpoint, race_NextCheckpoint(), and vdist.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         bool raw_touch_check = true;
         int cp = this.race_checkpoint;
         LABEL(search_racecheckpoints)
         IL_EACH(g_racecheckpoints, true,
         {
             if(it.cnt == cp || cp == -1)
             {
                 // redirect bot to next goal if it touched the waypoint of an untouchable checkpoint
                 // e.g. checkpoint in front of Stormkeep's warpzone
                 // the same workaround is applied in Race game mode
                 if (raw_touch_check && vdist(this.origin - it.nearestwaypoint.origin, <, 30))
                 {
                     cp = race_NextCheckpoint(cp);
                     raw_touch_check = false;
                     goto search_racecheckpoints;
                 }
                 navigation_routerating(this, it, 1000000, 5000);
             }
         });
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
MUTATOR_HOOKFUNCTION (cts , PlayerPhysics)
Definition at line 68 of file sv_cts.qc.
References CS(), entity(), fabs(), floor(), IS_PLAYER, M_ARGV, M_SQRT1_2, movement, MOVETYPE_NONE, set_movetype(), time, vector(), and vlen().
 {
     entity player = M_ARGV(0, entity);
     float dt = M_ARGV(1, float);
     player.race_movetime_frac += dt;
     float f = floor(player.race_movetime_frac);
     player.race_movetime_frac -= f;
     player.race_movetime_count += f;
     player.race_movetime = player.race_movetime_frac + player.race_movetime_count;
     if(IS_PLAYER(player))
     {
         if (player.race_penalty)
             if (time > player.race_penalty)
                 player.race_penalty = 0;
         if(player.race_penalty)
         {
             player.velocity = '0 0 0';
             set_movetype(player, MOVETYPE_NONE);
             player.disableclientprediction = 2;
         }
     }
     // force kbd movement for fairness
     float wishspeed;
     vector wishvel;
     // if record times matter
     // ensure nothing EVIL is being done (i.e. div0_evade)
     // this hinders joystick users though
     // but it still gives SOME analog control
     wishvel.x = fabs(CS(player).movement.x);
     wishvel.y = fabs(CS(player).movement.y);
     if(wishvel.x != 0 && wishvel.y != 0 && wishvel.x != wishvel.y)
     {
         wishvel.z = 0;
         wishspeed = vlen(wishvel);
         if(wishvel.x >= 2 * wishvel.y)
         {
             // pure X motion
             if(CS(player).movement.x > 0)
                 CS(player).movement_x = wishspeed;
             else
                 CS(player).movement_x = -wishspeed;
             CS(player).movement_y = 0;
         }
         else if(wishvel.y >= 2 * wishvel.x)
         {
             // pure Y motion
             CS(player).movement_x = 0;
             if(CS(player).movement.y > 0)
                 CS(player).movement_y = wishspeed;
             else
                 CS(player).movement_y = -wishspeed;
         }
         else
         {
             // diagonal
             if(CS(player).movement.x > 0)
                 CS(player).movement_x = M_SQRT1_2 * wishspeed;
             else
                 CS(player).movement_x = -M_SQRT1_2 * wishspeed;
             if(CS(player).movement.y > 0)
                 CS(player).movement_y = M_SQRT1_2 * wishspeed;
             else
                 CS(player).movement_y = -M_SQRT1_2 * wishspeed;
         }
     }
 }
MUTATOR_HOOKFUNCTION (cts , reset_map_global)
Definition at line 139 of file sv_cts.qc.
References cts_EventLog(), FOREACH_CLIENT, ftos(), GameRules_scoring_add, NULL, PlayerScore_Sort(), race_ClearRecords(), race_place, and Score_NicePrint().
 {
     float s;
     Score_NicePrint(NULL);
     race_ClearRecords();
     PlayerScore_Sort(race_place, 0, 1, 0);
     FOREACH_CLIENT(true, {
         if(it.race_place)
         {
             s = GameRules_scoring_add(it, RACE_FASTEST, 0);
             if(!s)
                 it.race_place = 0;
         }
         cts_EventLog(ftos(it.race_place), it);
     });
     if(g_race_qualifying == 2)
     {
         g_race_qualifying = 0;
         independent_players = 0;
         cvar_set("fraglimit", ftos(race_fraglimit));
         cvar_set("leadlimit", ftos(race_leadlimit));
         cvar_set("timelimit", ftos(race_timelimit));
         cts_ScoreRules();
     }
 }
MUTATOR_HOOKFUNCTION (cts , ClientConnect)
Definition at line 169 of file sv_cts.qc.
References autocvar_g_cts_send_rankings_cnt, CTS_RECORD, db_get(), entity(), GetMapname(), IS_REAL_CLIENT, M_ARGV, min(), msg_entity, MSG_ONE, race_PreparePlayer(), race_send_rankings_cnt(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendRankings(), RANKINGS_CNT, ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, stof(), strcat(), and uid2name().
 {
     entity player = M_ARGV(0, entity);
     race_PreparePlayer(player);
     player.race_checkpoint = -1;
     if(IS_REAL_CLIENT(player))
     {
         string rr = CTS_RECORD;
         msg_entity = player;
         race_send_recordtime(MSG_ONE);
         race_send_speedaward(MSG_ONE);
         speedaward_alltimebest = stof(db_get(ServerProgsDB, strcat(GetMapname(), rr, "speed/speed")));
         speedaward_alltimebest_holder = uid2name(db_get(ServerProgsDB, strcat(GetMapname(), rr, "speed/crypto_idfp")));
         race_send_speedaward_alltimebest(MSG_ONE);
         float i;
         int m = min(RANKINGS_CNT, autocvar_g_cts_send_rankings_cnt);
         race_send_rankings_cnt(MSG_ONE);
         for (i = 1; i <= m; ++i)
         {
             race_SendRankings(i, 0, 0, MSG_ONE);
         }
     }
 }
MUTATOR_HOOKFUNCTION (cts , AbortSpeedrun)
Definition at line 198 of file sv_cts.qc.
References autocvar_g_allow_checkpoints, entity(), M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     if(autocvar_g_allow_checkpoints)
         race_PreparePlayer(player); // nice try
 }
MUTATOR_HOOKFUNCTION (cts , MakePlayerObserver)
Definition at line 206 of file sv_cts.qc.
References entity(), FRAGS_PLAYER_OUT_OF_GAME, FRAGS_SPECTATOR, GameRules_scoring_add, M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     if(GameRules_scoring_add(player, RACE_FASTEST, 0))
         player.frags = FRAGS_PLAYER_OUT_OF_GAME;
     else
         player.frags = FRAGS_SPECTATOR;
     race_PreparePlayer(player);
     player.race_checkpoint = -1;
 }
MUTATOR_HOOKFUNCTION (cts , PlayerSpawn)
Definition at line 219 of file sv_cts.qc.
References entity(), M_ARGV, and race_PreparePlayer().
 {
     entity player = M_ARGV(0, entity);
     entity spawn_spot = M_ARGV(1, entity);
     if(spawn_spot.target == "")
         // Emergency: this wasn't a real spawnpoint. Can this ever happen?
         race_PreparePlayer(player);
     // if we need to respawn, do it right
     player.race_respawn_checkpoint = player.race_checkpoint;
     player.race_respawn_spotref = spawn_spot;
     player.race_place = 0;
 }
MUTATOR_HOOKFUNCTION (cts , PutClientInServer)
Definition at line 235 of file sv_cts.qc.
References CS(), entity(), FRAGS_SPECTATOR, g_race_qualifying, IS_PLAYER, killcount, M_ARGV, race_AbandonRaceCheck(), race_PreparePlayer(), and race_RetractPlayer().
 {
     entity player = M_ARGV(0, entity);
     if(IS_PLAYER(player))
     if(!game_stopped)
     {
         if(CS(player).killcount == FRAGS_SPECTATOR /* initial spawn */ || g_race_qualifying) // spawn
             race_PreparePlayer(player);
         else // respawn
             race_RetractPlayer(player);
         race_AbandonRaceCheck(player);
     }
 }
MUTATOR_HOOKFUNCTION (cts , PlayerDies)
Definition at line 251 of file sv_cts.qc.
References autocvar_g_cts_removeprojectiles, entity(), FL_PROJECTILE, g_projectiles, IL_EACH, M_ARGV, race_AbandonRaceCheck(), and RESPAWN_FORCE.
 {
     entity frag_target = M_ARGV(2, entity);
     frag_target.respawn_flags |= RESPAWN_FORCE;
     race_AbandonRaceCheck(frag_target);
     if(autocvar_g_cts_removeprojectiles)
     {
         IL_EACH(g_projectiles, it.owner == frag_target && (it.flags & FL_PROJECTILE),
         {
             delete(it);
         });
     }
 }
MUTATOR_HOOKFUNCTION (cts , HavocBot_ChooseRole)
Definition at line 267 of file sv_cts.qc.
References entity(), havocbot_role_cts(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     bot.havocbot_role = havocbot_role_cts;
     return true;
 }
MUTATOR_HOOKFUNCTION (cts , GetPressedKeys)
Definition at line 275 of file sv_cts.qc.
References CS(), CTS_RECORD, cvar_cl_allow_uid2name, cvar_cl_allow_uidtracking, db_put(), entity(), ftos(), GetMapname(), IS_OBSERVER, M_ARGV, MSG_ALL, race_send_speedaward(), race_send_speedaward_alltimebest(), ServerProgsDB, speedaward_alltimebest, speedaward_alltimebest_holder, speedaward_alltimebest_uid, speedaward_holder, speedaward_lastsent, speedaward_lastupdate, speedaward_speed, speedaward_uid, strcat(), strcpy, strzone(), time, uid2name(), vdist, and vlen().
 {
     entity player = M_ARGV(0, entity);
     if(CS(player).cvar_cl_allow_uidtracking == 1 && CS(player).cvar_cl_allow_uid2name == 1)
     {
         if (!player.stored_netname)
             player.stored_netname = strzone(uid2name(player.crypto_idfp));
         if(player.stored_netname != player.netname)
         {
             db_put(ServerProgsDB, strcat("/uid2name/", player.crypto_idfp), player.netname);
             strcpy(player.stored_netname, player.netname);
         }
     }
     if (!IS_OBSERVER(player))
     {
         if(vdist(player.velocity - player.velocity_z * '0 0 1', >, speedaward_speed))
         {
             speedaward_speed = vlen(player.velocity - player.velocity_z * '0 0 1');
             speedaward_holder = player.netname;
             speedaward_uid = player.crypto_idfp;
             speedaward_lastupdate = time;
         }
         if (speedaward_speed > speedaward_lastsent && time - speedaward_lastupdate > 1)
         {
             string rr = CTS_RECORD;
             race_send_speedaward(MSG_ALL);
             speedaward_lastsent = speedaward_speed;
             if (speedaward_speed > speedaward_alltimebest && speedaward_uid != "")
             {
                 speedaward_alltimebest = speedaward_speed;
                 speedaward_alltimebest_holder = speedaward_holder;
                 speedaward_alltimebest_uid = speedaward_uid;
                 db_put(ServerProgsDB, strcat(GetMapname(), rr, "speed/speed"), ftos(speedaward_alltimebest));
                 db_put(ServerProgsDB, strcat(GetMapname(), rr, "speed/crypto_idfp"), speedaward_alltimebest_uid);
                 race_send_speedaward_alltimebest(MSG_ALL);
             }
         }
     }
 }
MUTATOR_HOOKFUNCTION (cts , ForbidThrowCurrentWeapon)
Definition at line 317 of file sv_cts.qc.
 {
     // no weapon dropping in CTS
     return true;
 }
MUTATOR_HOOKFUNCTION (cts , FilterItem)
Definition at line 323 of file sv_cts.qc.
References entity(), Item_IsLoot(), and M_ARGV.
 {
     entity item = M_ARGV(0, entity);
     if (Item_IsLoot(item))
     {
         return true;
     }
 }
MUTATOR_HOOKFUNCTION (cts , Damage_Calculate)
Definition at line 333 of file sv_cts.qc.
References autocvar_g_cts_selfdamage, entity(), and M_ARGV.
 {
     entity frag_attacker = M_ARGV(1, entity);
     entity frag_target = M_ARGV(2, entity);
     float frag_deathtype = M_ARGV(3, float);
     float frag_damage = M_ARGV(4, float);
     if(frag_target == frag_attacker || frag_deathtype == DEATH_FALL.m_id)
     if(!autocvar_g_cts_selfdamage)
     {
         frag_damage = 0;
         M_ARGV(4, float) = frag_damage;
     }
 }
MUTATOR_HOOKFUNCTION (cts , ForbidPlayerScore_Clear)
Definition at line 348 of file sv_cts.qc.
 {
     return true; // in CTS, you don't lose score by observing
 }
MUTATOR_HOOKFUNCTION (cts , GetRecords)
Definition at line 353 of file sv_cts.qc.
References M_ARGV, MapInfo_count, MapInfo_Get_ByID(), MapInfo_Map_bspname, race_readName(), race_readTime(), strcat(), and TIME_ENCODED_TOSTRING.
 {
     int record_page = M_ARGV(0, int);
     string ret_string = M_ARGV(1, string);
     for(int i = record_page * 200; i < MapInfo_count && i < record_page * 200 + 200; ++i)
     {
         if(MapInfo_Get_ByID(i))
         {
             float r = race_readTime(MapInfo_Map_bspname, 1);
             if(!r)
                 continue;
             string h = race_readName(MapInfo_Map_bspname, 1);
             ret_string = strcat(ret_string, strpad(32, MapInfo_Map_bspname), " ", strpad(-8, TIME_ENCODED_TOSTRING(r)), " ", h, "\n");
         }
     }
     M_ARGV(1, string) = ret_string;
 }
MUTATOR_HOOKFUNCTION (cts , ClientKill)
Definition at line 375 of file sv_cts.qc.
References M_ARGV.
 {
     M_ARGV(1, float) = 0; // kill delay
 }
MUTATOR_HOOKFUNCTION (cts , Race_FinalCheckpoint)
Definition at line 380 of file sv_cts.qc.
References autocvar_g_cts_finish_kill_delay, ClientKill_Silent(), entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // useful to prevent cheating by running back to the start line and starting out with more speed
     if(autocvar_g_cts_finish_kill_delay)
         ClientKill_Silent(player, autocvar_g_cts_finish_kill_delay);
 }
MUTATOR_HOOKFUNCTION (cts , HideTeamNagger)
Definition at line 389 of file sv_cts.qc.
 {
     return true; // doesn't work so well (but isn't cts a teamless mode?)
 }
MUTATOR_HOOKFUNCTION (cts , FixClientCvars)
Definition at line 394 of file sv_cts.qc.
References entity(), M_ARGV, and stuffcmd.
 {
     entity player = M_ARGV(0, entity);
     stuffcmd(player, "cl_cmd settemp cl_movecliptokeyboard 2\n");
 }
MUTATOR_HOOKFUNCTION (cts , WantWeapon)
Definition at line 401 of file sv_cts.qc.
References entity(), and M_ARGV.
 {
     M_ARGV(1, float) = (M_ARGV(0, entity) == WEP_SHOTGUN); // want weapon = weapon info
     M_ARGV(3, bool) = true; // want mutator blocked
     return true;
 }
MUTATOR_HOOKFUNCTION (cts , ForbidDropCurrentWeapon)
Definition at line 408 of file sv_cts.qc.
 {
     return true;
 }
Variable Documentation
float autocvar_g_cts_finish_kill_delay
Definition at line 6 of file sv_cts.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_cts_removeprojectiles
Definition at line 8 of file sv_cts.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_cts_selfdamage
Definition at line 7 of file sv_cts.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float race_checkpoint
Definition at line 11 of file sv_cts.qc.
Referenced by havocbot_role_cts().