Xonotic: server/pathlib/debug.qc File Reference
debug.qc File Reference
#include "debug.qh"
#include "pathlib.qh"
Functions
void __showpath2_think ()
MODEL (SQUARE,"models/pathlib/square.md3")
MODEL (SQUARE_GOOD,"models/pathlib/goodsquare.md3")
MODEL (SQUARE_BAD,"models/pathlib/badsquare.md3")
MODEL (EDGE,"models/pathlib/edge.md3")
void path_dbg_think ()
void pathlib_showedge (vector where, float _lifetime, float rot)
void pathlib_showpath (entity start)
void pathlib_showpath2 (entity path)
void pathlib_showsquare (vector where, float goodsquare, float _lifetime)
void pathlib_showsquare2 (entity node, vector ncolor, float align)
Function Documentation
void __showpath2_think ()
Definition at line 32 of file debug.qc.
References origin, path_next, SELFPARAM, and time.
Referenced by pathlib_showpath2().
 {SELFPARAM();
     #ifdef TURRET_DEBUG
     mark_info(self.origin,1);
     #endif
     if(self.path_next)
     {
         self.path_next.think     = __showpath2_think;
         self.path_next.nextthink = time + 0.15;
     }
     else
     {
         self.owner.think     = __showpath2_think;
         self.owner.nextthink = time + 0.15;
     }
 }
MODEL (SQUARE , "models/pathlib/square.md3")
MODEL (SQUARE_GOOD , "models/pathlib/goodsquare.md3")
MODEL (SQUARE_BAD , "models/pathlib/badsquare.md3")
MODEL (EDGE , "models/pathlib/edge.md3")
void path_dbg_think ()
Definition at line 26 of file debug.qc.
References pathlib_showpath(), SELFPARAM, and time.
 {SELFPARAM();
     pathlib_showpath(self);
     self.nextthink = time + 1;
 }
void pathlib_showedge (vector where, float _lifetime, float rot)
Definition at line 99 of file debug.qc.
References entity(), pathlib_gridsize, setmodel, SOLID_NOT, spawn(), SUB_Remove_self(), and time.
 {
     entity e;
     if(!_lifetime)
         _lifetime = time + 30;
     else
         _lifetime += time;
     e           = spawn();
     e.alpha     = 0.25;
     e.think     = SUB_Remove_self;
     e.nextthink = _lifetime;
     e.scale     = pathlib_gridsize / 512;
     e.solid     = SOLID_NOT;
     setorigin(e,where);
     setmodel(e, MDL_EDGE);
     //traceline(where + '0 0 32',where - '0 0 128',MOVE_WORLDONLY,e);
     //e.angles = vectoangles(trace_plane_normal);
     e.angles_y = rot;
     //e.angles_x += 90;
 }
void pathlib_showpath (entity start)
Definition at line 15 of file debug.qc.
References entity().
Referenced by path_dbg_think().
 {
     entity e;
     e = start;
     while(e.path_next)
     {
         te_lightning1(e,e.origin,e.path_next.origin);
         e = e.path_next;
     }
 }
void pathlib_showpath2 (entity path)
Definition at line 49 of file debug.qc.
References __showpath2_think(), and time.
Referenced by pathlib_astar().
 {
     path.think     = __showpath2_think;
     path.nextthink = time;
 }
void pathlib_showsquare (vector where, float goodsquare, float _lifetime)
Definition at line 74 of file debug.qc.
References entity(), MOVE_WORLDONLY, pathlib_gridsize, setmodel, SOLID_NOT, spawn(), SUB_Remove_self(), time, trace_plane_normal, and vectoangles().
Referenced by pathlib_makenode_adaptive(), and pathlib_mknode().
 {
     entity s;
     if(!_lifetime)
         _lifetime = time + 30;
     else
         _lifetime += time;
     s           = spawn();
     s.alpha     = 0.25;
     s.think     = SUB_Remove_self;
     s.nextthink = _lifetime;
     s.scale     = pathlib_gridsize / 512.001;
     s.solid     = SOLID_NOT;
     setmodel(s, goodsquare ? MDL_SQUARE_GOOD : MDL_SQUARE_BAD);
     traceline(where + '0 0 32',where - '0 0 128',MOVE_WORLDONLY,s);
     s.angles = vectoangles(trace_plane_normal);
     s.angles_x -= 90;
     setorigin(s,where);
 }
void pathlib_showsquare2 (entity node, vector ncolor, float align)
Definition at line 55 of file debug.qc.
References MOVE_WORLDONLY, pathlib_gridsize, setmodel, SOLID_NOT, trace_plane_normal, and vectoangles().
 {
     node.alpha     = 0.25;
     node.scale     = pathlib_gridsize / 512.001;
     node.solid     = SOLID_NOT;
     setmodel(node, MDL_SQUARE);
     setorigin(node,node.origin);
     node.colormod = ncolor;
     if(align)
     {
         traceline(node.origin + '0 0 32', node.origin - '0 0 128', MOVE_WORLDONLY, node);
         node.angles = vectoangles(trace_plane_normal);
         node.angles_x -= 90;
     }
 }