Xonotic: common/mapobjects/trigger/teleport.qc File Reference
teleport.qc File Reference
#include "teleport.qh"
Functions
bool Teleport_Active (entity this, entity player)
void Teleport_Touch (entity this, entity toucher)
Function Documentation
bool Teleport_Active (entity this, entity player)
Definition at line 15 of file teleport.qc.
References active, ACTIVE_ACTIVE, DIFF_TEAM, INVERT_TEAMS, IS_DEAD, IS_PLAYER, IS_TURRET, spawnflags, and team.
Referenced by Teleport_Touch().
 {
     if (this.active != ACTIVE_ACTIVE)
         return false;
 #ifdef SVQC
     if (!player.teleportable)
         return false;
     if(player.vehicle)
     if(!player.vehicle.teleportable)
         return false;
     if(IS_TURRET(player))
         return false;
 #elif defined(CSQC)
     if(!IS_PLAYER(player))
         return false;
 #endif
     if(IS_DEAD(player))
         return false;
     if(this.team)
         if(((this.spawnflags & INVERT_TEAMS) == 0) == (DIFF_TEAM(this, player)))
             return false;
     return true;
 }
void Teleport_Touch (entity this, entity toucher)
Definition at line 45 of file teleport.qc.
References active, ACTIVE_ACTIVE, angles, classname, entity(), EXACTTRIGGER_INIT, EXACTTRIGGER_TOUCH, FOREACH_WORD, g_teleporters, IL_PUSH(), InitializeEntity(), INITPRIO_FINDTARGET, IS_PLAYER, move_time, NET_HANDLE, noise, objerror(), precache_sound(), RemoveGrapplingHooks(), Simple_TeleportPlayer(), solid, SOLID_TRIGGER, spawnflags, spawnfunc(), speed, string_null, SUB_UseTargets(), target, team, Teleport_Active(), teleport_findtarget(), time, to, use, WriteByte(), and WriteCoord().
Referenced by teleport_findtarget().
 {
     entity player = toucher;
     if(!Teleport_Active(this, player))
         return;
     EXACTTRIGGER_TOUCH(this, player);
 #ifdef SVQC
     if(IS_PLAYER(player))
         RemoveGrapplingHooks(player);
 #endif
     entity e;
     e = Simple_TeleportPlayer(this, player);
 #ifdef SVQC
     string s = this.target; this.target = string_null;
     SUB_UseTargets(this, player, player); // TODO: should we be using toucher for trigger too?
     if (!this.target) this.target = s;
     SUB_UseTargets(e, player, player);
 #endif
 }