Xonotic: lib/color.qh File Reference
color.qh File Reference
#include "string.qh"
Macros
#define colormapPaletteColor(c, isPants) colormapPaletteColor_(c, isPants, time)
Functions
ERASEABLE vector colormapPaletteColor_ (int c, bool isPants, float t)
ERASEABLE vector hsl_to_rgb (vector hsl)
ERASEABLE vector hsv_to_rgb (vector hsv)
ERASEABLE vector hue_mi_ma_to_rgb (float hue, float mi, float ma)
ERASEABLE float rgb_mi_ma_to_hue (vector rgb, float mi, float ma)
ERASEABLE string rgb_to_hexcolor (vector rgb)
ERASEABLE vector rgb_to_hsl (vector rgb)
ERASEABLE vector rgb_to_hsv (vector rgb)
Macro Definition Documentation
#define colormapPaletteColor (c, isPants) colormapPaletteColor_(c, isPants, time)
Definition at line 5 of file color.qh.
Referenced by CSQC_UpdateView(), CSQCPlayer_ModelAppearance_Apply(), ctf_DelayedFlagSetup(), draw_teamradar_link(), HUD_Main(), kh_Key_AssignTo(), NET_HANDLE(), ons_ControlPoint_UpdateSprite(), ons_Generator_UpdateSprite(), Scoreboard_GetName(), XonoticColorButton_draw(), and XonoticPlayerList_drawListBoxItem().
Function Documentation
ERASEABLE vector colormapPaletteColor_ (int c, bool isPants, float t)
Definition at line 7 of file color.qh.
References M_E, M_PI, and sin().
 {
     switch (c)
     {
         case  0: return '1.000000 1.000000 1.000000';
         case  1: return '1.000000 0.333333 0.000000';
         case  2: return '0.000000 1.000000 0.501961';
         case  3: return '0.000000 1.000000 0.000000';
         case  4: return '1.000000 0.000000 0.000000';
         case  5: return '0.000000 0.666667 1.000000';
         case  6: return '0.000000 1.000000 1.000000';
         case  7: return '0.501961 1.000000 0.000000';
         case  8: return '0.501961 0.000000 1.000000';
         case  9: return '1.000000 0.000000 1.000000';
         case 10: return '1.000000 0.000000 0.501961';
         case 11: return '0.000000 0.000000 1.000000';
         case 12: return '1.000000 1.000000 0.000000';
         case 13: return '0.000000 0.333333 1.000000';
         case 14: return '1.000000 0.666667 0.000000';
         case 15:
             if (isPants)
                 return '1 0 0' * (0.502 + 0.498 * sin(t / M_E + 0))
                     + '0 1 0' * (0.502 + 0.498 * sin(t / M_E + M_PI * 2 / 3))
                     + '0 0 1' * (0.502 + 0.498 * sin(t / M_E + M_PI * 4 / 3));
             else
                 return '1 0 0' * (0.502 + 0.498 * sin(t / M_PI + M_PI * 5 / 3))
                     + '0 1 0' * (0.502 + 0.498 * sin(t / M_PI + M_PI))
                     + '0 0 1' * (0.502 + 0.498 * sin(t / M_PI + M_PI * 1 / 3));
         default: return '0.000 0.000 0.000';
     }
 }
ERASEABLE vector hsl_to_rgb (vector hsl)
Definition at line 161 of file color.qh.
References hue_mi_ma_to_rgb().
Referenced by GenericCommand(), and hslimage_color().
 {
     float mi, ma, maminusmi;
     if (hsl.z <= 0.5) maminusmi = hsl.y * 2 * hsl.z;
     else maminusmi = hsl.y * (2 - 2 * hsl.z);
     // hsl_z     = 0.5 * mi + 0.5 * ma
     // maminusmi =     - mi +       ma
     mi = hsl.z - 0.5 * maminusmi;
     ma = hsl.z + 0.5 * maminusmi;
     return hue_mi_ma_to_rgb(hsl.x, mi, ma);
 }
ERASEABLE vector hsv_to_rgb (vector hsv)
Definition at line 135 of file color.qh.
References hue_mi_ma_to_rgb().
 {
     return hue_mi_ma_to_rgb(hsv.x, hsv.z * (1 - hsv.y), hsv.z);
 }
ERASEABLE vector hue_mi_ma_to_rgb (float hue, float mi, float ma)
Definition at line 62 of file color.qh.
References floor(), and vector().
Referenced by hsl_to_rgb(), and hsv_to_rgb().
 {
     vector rgb;
     hue -= 6 * floor(hue / 6);
     // else if(ma == rgb_x)
     //  hue = 60 * (rgb_y - rgb_z) / (ma - mi);
     if (hue <= 1)
     {
         rgb.x = ma;
         rgb.y = hue * (ma - mi) + mi;
         rgb.z = mi;
     }
     // else if(ma == rgb_y)
     //  hue = 60 * (rgb_z - rgb_x) / (ma - mi) + 120;
     else if (hue <= 2)
     {
         rgb.x = (2 - hue) * (ma - mi) + mi;
         rgb.y = ma;
         rgb.z = mi;
     }
     else if (hue <= 3)
     {
         rgb.x = mi;
         rgb.y = ma;
         rgb.z = (hue - 2) * (ma - mi) + mi;
     }
     // else // if(ma == rgb_z)
     //  hue = 60 * (rgb_x - rgb_y) / (ma - mi) + 240;
     else if (hue <= 4)
     {
         rgb.x = mi;
         rgb.y = (4 - hue) * (ma - mi) + mi;
         rgb.z = ma;
     }
     else if (hue <= 5)
     {
         rgb.x = (hue - 4) * (ma - mi) + mi;
         rgb.y = mi;
         rgb.z = ma;
     }
     // else if(ma == rgb_x)
     //  hue = 60 * (rgb_y - rgb_z) / (ma - mi);
     else  // if(hue <= 6)
     {
         rgb.x = ma;
         rgb.y = mi;
         rgb.z = (6 - hue) * (ma - mi) + mi;
     }
     return rgb;
 }
ERASEABLE float rgb_mi_ma_to_hue (vector rgb, float mi, float ma)
Definition at line 40 of file color.qh.
Referenced by rgb_to_hsl(), and rgb_to_hsv().
 {
     if (mi == ma)
     {
         return 0;
     }
     else if (ma == rgb.x)
     {
         if (rgb.y >= rgb.z) return (rgb.y - rgb.z) / (ma - mi);
         else return (rgb.y - rgb.z) / (ma - mi) + 6;
     }
     else if (ma == rgb.y)
     {
         return (rgb.z - rgb.x) / (ma - mi) + 2;
     }
     else  // if(ma == rgb_z)
     {
         return (rgb.x - rgb.y) / (ma - mi) + 4;
     }
 }
ERASEABLE string rgb_to_hexcolor (vector rgb)
Definition at line 177 of file color.qh.
References DEC_TO_HEXDIGIT, floor(), and strcat().
Referenced by BUFF_NAME(), GenericCommand(), getDemos_for_ext(), getScreenshots_for_ext(), and XonoticColorpicker_mouseDrag().
 {
     return strcat(
         "^x",
         DEC_TO_HEXDIGIT(floor(rgb.x * 15 + 0.5)),
         DEC_TO_HEXDIGIT(floor(rgb.y * 15 + 0.5)),
         DEC_TO_HEXDIGIT(floor(rgb.z * 15 + 0.5))
                  );
 }
ERASEABLE vector rgb_to_hsl (vector rgb)
Definition at line 141 of file color.qh.
References max(), min(), rgb_mi_ma_to_hue(), and vector().
Referenced by color_hslimage().
 {
     float mi, ma;
     vector hsl;
     mi = min(rgb.x, rgb.y, rgb.z);
     ma = max(rgb.x, rgb.y, rgb.z);
     hsl.x = rgb_mi_ma_to_hue(rgb, mi, ma);
     hsl.z = 0.5 * (mi + ma);
     if (mi == ma) hsl.y = 0;
     else if (hsl.z <= 0.5) hsl.y = (ma - mi) / (2 * hsl.z);
     else  // if(hsl_z > 0.5)
         hsl.y = (ma - mi) / (2 - 2 * hsl.z);
     return hsl;
 }
ERASEABLE vector rgb_to_hsv (vector rgb)
Definition at line 117 of file color.qh.
References max(), min(), rgb_mi_ma_to_hue(), and vector().
 {
     float mi, ma;
     vector hsv;
     mi = min(rgb.x, rgb.y, rgb.z);
     ma = max(rgb.x, rgb.y, rgb.z);
     hsv.x = rgb_mi_ma_to_hue(rgb, mi, ma);
     hsv.z = ma;
     if (ma == 0) hsv.y = 0;
     else hsv.y = 1 - mi / ma;
     return hsv;
 }