Xonotic: common/mutators/mutator/new_toys/sv_new_toys.qc File Reference
sv_new_toys.qc File Reference
#include "sv_new_toys.qh"
#include "../random_items/sv_random_items.qh"
Functions
MUTATOR_HOOKFUNCTION (nt, SetStartItems)
MUTATOR_HOOKFUNCTION (nt, SetWeaponreplace)
MUTATOR_HOOKFUNCTION (nt, FilterItem)
string nt_GetFullReplacement (string w)
string nt_GetReplacement (string w, float m)
bool nt_IsNewToy (int w)
REGISTER_MUTATOR (nt, expr_evaluate(cvar_string("g_new_toys"))&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok))
Variables
float autocvar_g_new_toys_autoreplace
bool autocvar_g_new_toys_use_pickupsound = false
string new_toys
const float NT_AUTOREPLACE_ALWAYS = 1
const float NT_AUTOREPLACE_NEVER = 0
const float NT_AUTOREPLACE_RANDOM = 2
Function Documentation
MUTATOR_HOOKFUNCTION (nt , SetStartItems)
Definition at line 156 of file sv_new_toys.qc.
References argv(), FOREACH, nt_GetReplacement(), start_weapons, start_weapons_defaultmask, tokenize_console, warmup_start_weapons, and warmup_start_weapons_defaultmask.
 {
     // rearrange start_weapon_default
     // apply those bits that are set by start_weapon_defaultmask
     // same for warmup
     float j, n;
     WepSet newdefault;
     WepSet warmup_newdefault;
     newdefault = '0 0 0';
     warmup_newdefault = '0 0 0';
     WepSet seti = '0 0 0';
     FOREACH(Weapons, it != WEP_Null, {
         seti = it.m_wepset;
         n = tokenize_console(nt_GetReplacement(it.netname, autocvar_g_new_toys_autoreplace));
         for(j = 0; j < n; ++j)
             FOREACH(Weapons, it != WEP_Null, {
                 if(it.netname == argv(j))
                 {
                     WepSet setk = it.m_wepset;
                     if(start_weapons & seti) newdefault |= setk;
                     if(warmup_start_weapons & seti) warmup_newdefault |= setk;
                 }
             });
     });
     newdefault &= start_weapons_defaultmask;
     start_weapons &= ~start_weapons_defaultmask;
     start_weapons |= newdefault;
     warmup_newdefault &= warmup_start_weapons_defaultmask;
     warmup_start_weapons &= ~warmup_start_weapons_defaultmask;
     warmup_start_weapons |= warmup_newdefault;
 }
MUTATOR_HOOKFUNCTION (nt , SetWeaponreplace)
Definition at line 196 of file sv_new_toys.qc.
References entity(), M_ARGV, MUTATOR_IS_ENABLED, nt_GetReplacement(), and W_Apply_Weaponreplace().
 {
     if (MUTATOR_IS_ENABLED(random_items))
     {
         // Do not replace weapons when random items are enabled.
         return;
     }
     entity wep = M_ARGV(0, entity);
     entity wepinfo = M_ARGV(1, entity);
     string ret_string = M_ARGV(2, string);
     // otherwise, we do replace
     if(wep.new_toys)
     {
         // map defined replacement:
         ret_string = wep.new_toys;
     }
     else
     {
         // auto replacement:
         ret_string = nt_GetReplacement(wepinfo.netname, autocvar_g_new_toys_autoreplace);
     }
     // apply regular weaponreplace
     ret_string = W_Apply_Weaponreplace(ret_string);
     M_ARGV(2, string) = ret_string;
 }
MUTATOR_HOOKFUNCTION (nt , FilterItem)
Definition at line 225 of file sv_new_toys.qc.
References entity(), M_ARGV, nt_IsNewToy(), and string_null.
 {
     entity item = M_ARGV(0, entity);
     if(nt_IsNewToy(item.weapon) && autocvar_g_new_toys_use_pickupsound) {
         item.item_pickupsound = string_null;
         item.item_pickupsound_ent = SND_WEAPONPICKUP_NEW_TOYS;
     }
 }
string nt_GetFullReplacement (string w)
Definition at line 131 of file sv_new_toys.qc.
References string_null.
Referenced by nt_GetReplacement().
 {
     switch(w)
     {
         case "hagar": return "seeker";
         case "devastator": return "minelayer";
         case "machinegun": return "hlac";
         case "vortex": return "rifle";
         //case "shotgun": return "shockwave";
         default: return string_null;
     }
 }
string nt_GetReplacement (string w, float m)
Definition at line 144 of file sv_new_toys.qc.
References nt_GetFullReplacement(), and strcat().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if(m == NT_AUTOREPLACE_NEVER)
         return w;
     string s = nt_GetFullReplacement(w);
     if (!s)
         return w;
     if(m == NT_AUTOREPLACE_RANDOM)
         s = strcat(w, " ", s);
     return s;
 }
bool nt_IsNewToy (int w)
Definition at line 116 of file sv_new_toys.qc.
Referenced by MUTATOR_HOOKFUNCTION(), and REGISTER_MUTATOR().
 {
     switch(w)
     {
         case WEP_SEEKER.m_id:
         case WEP_MINE_LAYER.m_id:
         case WEP_HLAC.m_id:
         case WEP_RIFLE.m_id:
         case WEP_SHOCKWAVE.m_id:
             return true;
         default:
             return false;
     }
 }
REGISTER_MUTATOR (nt , expr_evaluate(cvar_string("g_new_toys"))&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok))
Definition at line 77 of file sv_new_toys.qc.
References error, FOREACH, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, MUTATOR_ONROLLBACK_OR_REMOVE, nt_IsNewToy(), time, and WEP_FLAG_MUTATORBLOCKED.
 {
     MUTATOR_ONADD
     {
         if(time > 1) // game loads at time 1
             error("This cannot be added at runtime\n");
         // mark the guns as ok to use by e.g. impulse 99
         FOREACH(Weapons, it != WEP_Null, {
             if(nt_IsNewToy(it.m_id))
                 it.spawnflags &= ~WEP_FLAG_MUTATORBLOCKED;
         });
     }
     MUTATOR_ONROLLBACK_OR_REMOVE
     {
         FOREACH(Weapons, it != WEP_Null, {
             if(nt_IsNewToy(it.m_id))
                 it.spawnflags |= WEP_FLAG_MUTATORBLOCKED;
         });
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This cannot be removed at runtime");
         return -1;
     }
     return 0;
 }
Variable Documentation
float autocvar_g_new_toys_autoreplace
Definition at line 110 of file sv_new_toys.qc.
bool autocvar_g_new_toys_use_pickupsound = false
Definition at line 111 of file sv_new_toys.qc.
string new_toys
Definition at line 108 of file sv_new_toys.qc.
const float NT_AUTOREPLACE_ALWAYS = 1
Definition at line 113 of file sv_new_toys.qc.
const float NT_AUTOREPLACE_NEVER = 0
Definition at line 112 of file sv_new_toys.qc.
const float NT_AUTOREPLACE_RANDOM = 2
Definition at line 114 of file sv_new_toys.qc.