Xonotic: server/weapons/hitplot.qh File Reference
hitplot.qh File Reference
Functions
void W_HitPlotAnalysis (entity player, entity wep, vector screenforward, vector screenright, vector screenup)
void W_HitPlotClose (entity player)
void W_HitPlotOpen (entity player)
Variables
bool autocvar_g_hitplots
string autocvar_g_hitplots_individuals
float hitplotfh
Function Documentation
W_HitPlotAnalysis()
void W_HitPlotAnalysis (entity player, entity wep, vector screenforward, vector screenright, vector screenup)
Definition at line 58 of file hitplot.qc.
References ANTILAG_LATENCY, antilag_restore(), antilag_takeback(), CS(), entity(), fputs(), ftos(), hitplotfh, IS_CLIENT, IS_MONSTER, IS_REAL_CLIENT, MOVE_NORMAL, strcat(), time, trace_endpos, trace_ent, traceline_antilag_force(), vector(), and W_HitPlotNormalizedUntransform().
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     if(CS(player).hitplotfh >= 0)
     {
         float lag = ANTILAG_LATENCY(player);
         if(lag < 0.001)
             lag = 0;
         if(!IS_REAL_CLIENT(player))
             lag = 0; // only antilag for clients
         vector org = player.origin + player.view_ofs;
         traceline_antilag_force(player, org, org + screenforward * max_shot_distance, MOVE_NORMAL, player, lag);
         if(IS_CLIENT(trace_ent) || IS_MONSTER(trace_ent))
         {
             entity store = IS_CLIENT(trace_ent) ? CS(trace_ent) : trace_ent;
             antilag_takeback(trace_ent, store, time - lag);
             vector hitplot = W_HitPlotNormalizedUntransform(org, trace_ent, screenforward, screenright, screenup, trace_endpos);
             antilag_restore(trace_ent, store);
             fputs(CS(player).hitplotfh, strcat(ftos(hitplot.x), " ", ftos(hitplot.y), " ", ftos(hitplot.z), " ", ftos(wep.m_id), "\n"));
             //print(strcat(ftos(hitplot_x), " ", ftos(hitplot_y), " ", ftos(hitplot_z), "\n"));
         }
     }
 }
W_HitPlotClose()
void W_HitPlotClose (entity player)
Definition at line 92 of file hitplot.qc.
References CS(), fclose(), and hitplotfh.
 {
     if(CS(player).hitplotfh >= 0)
     {
         fclose(CS(player).hitplotfh);
         CS(player).hitplotfh = -1;
     }
 }
W_HitPlotOpen()
void W_HitPlotOpen (entity player)
Definition at line 82 of file hitplot.qc.
References autocvar_g_hitplots, autocvar_g_hitplots_individuals, CS(), FILE_WRITE, fopen(), fputs(), ftos(), hitplotfh, matchid, strcat(), and strhasword.
 {
     if(autocvar_g_hitplots || strhasword(autocvar_g_hitplots_individuals, player.netaddress))
     {
         CS(player).hitplotfh = fopen(strcat("hits-", matchid, "-", player.netaddress, "-", ftos(player.playerid), ".plot"), FILE_WRITE);
         fputs(CS(player).hitplotfh, strcat("#name ", playername(player.netname, player.team, false), "\n"));
     }
     else { CS(player).hitplotfh = -1; }
 }
Variable Documentation
autocvar_g_hitplots
bool autocvar_g_hitplots
Definition at line 3 of file hitplot.qh.
Referenced by W_HitPlotOpen().
autocvar_g_hitplots_individuals
string autocvar_g_hitplots_individuals
Definition at line 4 of file hitplot.qh.
Referenced by W_HitPlotOpen().
hitplotfh
float hitplotfh
Definition at line 6 of file hitplot.qh.
Referenced by W_HitPlotAnalysis(), W_HitPlotClose(), and W_HitPlotOpen().