Xonotic: lib/noise.qh File Reference
noise.qh File Reference
Functions
classfield (Noise).float noise_baccum
entityclass (Noise)
ERASEABLE float Noise_Brown (entity e, float dt)
ERASEABLE float Noise_Burst (entity e, float dt, float p)
+1 or -1
ERASEABLE float Noise_Pink (entity e, float dt)
ERASEABLE float Noise_White (entity e, float dt)
Function Documentation
classfield (Noise)
entityclass (Noise)
ERASEABLE float Noise_Brown (entity e, float dt)
Definition at line 12 of file noise.qh.
References ERASEABLE, random(), and sqrt().
 {
     e.noise_baccum += random() * sqrt(dt);  // same stddev for all dt
     return e.noise_baccum;
 }
ERASEABLE float Noise_Burst (entity e, float dt, float p)
+1 or -1
Definition at line 35 of file noise.qh.
References random().
 {
     if (random() > (p ** dt)) e.noise_bstate = !e.noise_bstate;
     return 2 * e.noise_bstate - 1;
 }
ERASEABLE float Noise_Pink (entity e, float dt)
Definition at line 18 of file noise.qh.
References ERASEABLE, and random().
Referenced by View_NightVision().
 {
     float f;
     f = dt * 60;
     // http://home.earthlink.net/~ltrammell/tech/pinkalg.htm
     if (random() > (0.3190 ** f)) e.noise_paccum = 0.34848 * (2 * random() - 1);
     if (random() > (0.7756 ** f)) e.noise_paccum2 = 0.28768 * (2 * random() - 1);
     if (random() > (0.9613 ** f)) e.noise_paccum3 = 0.43488 * (2 * random() - 1);
     return e.noise_paccum + e.noise_paccum2 + e.noise_paccum3;
 }
ERASEABLE float Noise_White (entity e, float dt)
Definition at line 29 of file noise.qh.
References ERASEABLE, and random().
Referenced by View_NightVision().
 {
     return random() * 2 - 1;
 }