Xonotic: menu/draw.qc File Reference
draw.qc File Reference
#include "draw.qh"
#include "../common/util.qh"
#include "../common/constants.qh"
Classes
class ClipFrame
Functions
void _draw_SetClip (vector o, vector s)
vector boxToGlobal (vector v, vector theOrigin, vector theScale)
vector boxToGlobalSize (vector v, vector theScale)
void draw_BorderPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha, vector theBorderSize)
void draw_ButtonPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
void draw_CenterText (vector theOrigin, string theText, vector theSize, vector theColor, float theAlpha, float ICanHasKallerz)
void draw_ClearClip ()
float draw_CondensedFontFactor (string theText, float ICanHasKallerz, vector SizeThxBye, float maxWidth)
void draw_drawMousePointer (vector where)
void draw_Fill (vector theOrigin, vector theSize, vector theColor, float theAlpha)
void draw_Picture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
vector draw_PictureSize (string pic)
string draw_PreloadPicture (string pic)
string draw_PreloadPictureWithFlags (string pic, float f)
void draw_reset (float cw, float ch, float ox, float oy)
void draw_SetClip ()
void draw_SetClipRect (vector theOrigin, vector theScale)
void draw_setMousePointer (string pic, vector theSize, vector theOffset)
void draw_Text (vector theOrigin, string theText, vector theSize, vector theColor, float theAlpha, float ICanHasKallerz)
float draw_TextLengthUpToWidth (string theText, float maxWidth, float allowColorCodes, vector theFontSize)
string draw_TextShortenToWidth (string theText, float maxWidth, float ICanHasKallerz, vector SizeThxBye)
float draw_TextWidth (string theText, float ICanHasKallerz, vector SizeThxBye)
float draw_TextWidth_WithColors (string s, vector theFontSize)
float draw_TextWidth_WithoutColors (string s, vector theFontSize)
void draw_VertButtonPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
vector globalToBox (vector v, vector theOrigin, vector theScale)
vector globalToBoxSize (vector v, vector theScale)
STATIC_INIT (draw_clip)
Variables
IntrusiveList draw_clip
string draw_mousepointer
vector draw_mousepointer_offset
vector draw_mousepointer_size
Function Documentation
void _draw_SetClip (vector o, vector s)
Definition at line 322 of file draw.qc.
References bound(), ClipFrame::clip_scale, ClipFrame::clip_shift, drawsetcliparea(), IL_PEEK, IL_PUSH(), NEW, and prev.
Referenced by draw_SetClip(), and draw_SetClipRect().
 {
     ClipFrame prev = IL_PEEK(draw_clip);
     if (prev) {
         o.x = bound(prev.clip_shift.x, o.x, prev.clip_shift.x + prev.clip_scale.x);
         o.y = bound(prev.clip_shift.y, o.y, prev.clip_shift.y + prev.clip_scale.y);
         s.x = bound(0, s.x, prev.clip_scale.x - (o.x - prev.clip_shift.x));
         s.y = bound(0, s.y, prev.clip_scale.y - (o.y - prev.clip_shift.y));
     }
     ClipFrame e = NEW(ClipFrame);
     e.clip_shift = o;
     e.clip_scale = s;
     IL_PUSH(draw_clip, e);
     drawsetcliparea(o.x, o.y, s.x, s.y);
 }
vector boxToGlobal (vector v, vector theOrigin, vector theScale)
Definition at line 45 of file draw.qc.
References v.
Referenced by BorderImage_recalcPositionWithText(), Container_enterLieSubitem(), Container_resizeNotifyLie(), DemoConfirm_ListClick_Check_Gamestatus(), draw_BorderPicture(), draw_ButtonPicture(), draw_drawMousePointer(), draw_Fill(), draw_Picture(), draw_SetClipRect(), draw_Text(), draw_VertButtonPicture(), ListBox_draw(), ServerList_Info_Click(), XonoticServerList_keyDown(), and XonoticServerList_positionSortButton().
 {
     v.x *= theScale.x;
     v.y *= theScale.y;
     v += theOrigin;
     return v;
 }
vector boxToGlobalSize (vector v, vector theScale)
Definition at line 53 of file draw.qc.
References v.
Referenced by BorderImage_draw(), BorderImage_recalcPositionWithText(), Container_enterLieSubitem(), Container_resizeNotifyLie(), DemoConfirm_ListClick_Check_Gamestatus(), draw_BorderPicture(), draw_ButtonPicture(), draw_Fill(), draw_Picture(), draw_SetClipRect(), draw_Text(), draw_TextWidth(), draw_VertButtonPicture(), ListBox_draw(), ServerList_Info_Click(), XonoticServerList_keyDown(), and XonoticServerList_positionSortButton().
 {
     v.x *= theScale.x;
     v.y *= theScale.y;
     return v;
 }
void draw_BorderPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha, vector theBorderSize)
Definition at line 169 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_scale, draw_shift, draw_UseSkinFor(), drawsubpic(), eX, eY, height, and vector().
Referenced by BorderImage_draw(), m_tooltip(), and minigame_hud_simpleboard().
 {
     vector dX, dY;
     vector width, height;
     vector bW, bH;
     pic = draw_UseSkinFor(pic);
     theOrigin = boxToGlobal(theOrigin, draw_shift, draw_scale);
     theSize = boxToGlobalSize(theSize, draw_scale);
     theBorderSize = boxToGlobalSize(theBorderSize, draw_scale);
     theAlpha *= draw_alpha;
     width = eX * theSize.x;
     height = eY * theSize.y;
     // zero size? bail out, we cannot handle this
     if(theSize.x <= 0 || theSize.y <= 0)
         return;
     if(theBorderSize.x <= 0) // no x border
     {
         if(theBorderSize.y <= 0)
         {
             drawsubpic(theOrigin,                            width          + height,          pic, '0.25 0.25 0', '0.5  0.5  0', theColor, theAlpha, 0);
         }
         else if(theSize.y <= theBorderSize.y * 2)
         {
             // not high enough... draw just top and bottom then
             bH = eY * (0.25 * theSize.y / (theBorderSize.y * 2));
             drawsubpic(theOrigin,                             width          + height * 0.5, pic, '0.25 0 0',           '0.5  0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin              + height * 0.5, width          + height * 0.5, pic, '0.25 0 0' + eY - bH, '0.5  0 0' + bH, theColor, theAlpha, 0);
         }
         else
         {
             dY = theBorderSize.y * eY;
             drawsubpic(theOrigin,                            width                   +     dY, pic, '0.25 0    0', '0.5  0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin          + dY,              width          + height - 2 * dY, pic, '0.25 0.25 0', '0.5  0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin + height - dY,              width                   +     dY, pic, '0.25 0.75 0', '0.5  0.25 0', theColor, theAlpha, 0);
         }
     }
     else if(theSize.x <= theBorderSize.x * 2)
     {
         // not wide enough... draw just left and right then
         bW = eX * (0.25 * theSize.x / (theBorderSize.x * 2));
         if(theBorderSize.y <= 0)
         {
             drawsubpic(theOrigin,                             width * 0.5 + height,          pic, '0 0.25 0',           '0 0.5  0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width * 0.5,               width * 0.5 + height,          pic, '0 0.25 0' + eX - bW, '0 0.5  0' + bW, theColor, theAlpha, 0);
         }
         else if(theSize.y <= theBorderSize.y * 2)
         {
             // not high enough... draw just corners
             bH = eY * (0.25 * theSize.y / (theBorderSize.y * 2));
             drawsubpic(theOrigin,                 width * 0.5 + height * 0.5, pic, '0 0 0',           bW + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width   * 0.5, width * 0.5 + height * 0.5, pic, eX - bW,           bW + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + height  * 0.5, width * 0.5 + height * 0.5, pic, eY - bH,           bW + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + theSize * 0.5, width * 0.5 + height * 0.5, pic, eX + eY - bW - bH, bW + bH, theColor, theAlpha, 0);
         }
         else
         {
             dY = theBorderSize.y * eY;
             drawsubpic(theOrigin,                             width * 0.5          +     dY, pic, '0 0    0',           '0 0.25 0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width * 0.5,               width * 0.5          +     dY, pic, '0 0    0' + eX - bW, '0 0.25 0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin                        + dY, width * 0.5 + height - 2 * dY, pic, '0 0.25 0',           '0 0.5  0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width * 0.5          + dY, width * 0.5 + height - 2 * dY, pic, '0 0.25 0' + eX - bW, '0 0.5  0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin               + height - dY, width * 0.5          +     dY, pic, '0 0.75 0',           '0 0.25 0' + bW, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width * 0.5 + height - dY, width * 0.5          +     dY, pic, '0 0.75 0' + eX - bW, '0 0.25 0' + bW, theColor, theAlpha, 0);
         }
     }
     else
     {
         if(theBorderSize.y <= 0)
         {
             dX = theBorderSize.x * eX;
             drawsubpic(theOrigin,                                        dX + height,          pic, '0    0.25 0', '0.25 0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin                       + dX, width - 2 * dX + height,          pic, '0.25 0.25 0', '0.5  0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin               + width - dX,             dX + height,          pic, '0.75 0.25 0', '0.25 0.5  0', theColor, theAlpha, 0);
         }
         else if(theSize.y <= theBorderSize.y * 2)
         {
             // not high enough... draw just top and bottom then
             bH = eY * (0.25 * theSize.y / (theBorderSize.y * 2));
             dX = theBorderSize.x * eX;
             drawsubpic(theOrigin,                                         dX + height * 0.5, pic, '0    0 0',           '0.25 0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + dX,                        width - 2 * dX + height * 0.5, pic, '0.25 0 0',           '0.5  0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width - dX,                            dX + height * 0.5, pic, '0.75 0 0',           '0.25 0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin              + height * 0.5,             dX + height * 0.5, pic, '0    0 0' + eY - bH, '0.25 0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + dX         + height * 0.5, width - 2 * dX + height * 0.5, pic, '0.25 0 0' + eY - bH, '0.5  0 0' + bH, theColor, theAlpha, 0);
             drawsubpic(theOrigin + width - dX + height * 0.5,             dX + height * 0.5, pic, '0.75 0 0' + eY - bH, '0.25 0 0' + bH, theColor, theAlpha, 0);
         }
         else
         {
             dX = theBorderSize.x * eX;
             dY = theBorderSize.y * eY;
             drawsubpic(theOrigin,                                        dX          +     dY, pic, '0    0    0', '0.25 0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin                  + dX,      width - 2 * dX          +     dY, pic, '0.25 0    0', '0.5  0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin          + width - dX,                  dX          +     dY, pic, '0.75 0    0', '0.25 0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin          + dY,                          dX + height - 2 * dY, pic, '0    0.25 0', '0.25 0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin          + dY         + dX, width - 2 * dX + height - 2 * dY, pic, '0.25 0.25 0', '0.5  0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin          + dY + width - dX,             dX + height - 2 * dY, pic, '0.75 0.25 0', '0.25 0.5  0', theColor, theAlpha, 0);
             drawsubpic(theOrigin + height - dY,                          dX          +     dY, pic, '0    0.75 0', '0.25 0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin + height - dY         + dX, width - 2 * dX          +     dY, pic, '0.25 0.75 0', '0.5  0.25 0', theColor, theAlpha, 0);
             drawsubpic(theOrigin + height - dY + width - dX,             dX          +     dY, pic, '0.75 0.75 0', '0.25 0.25 0', theColor, theAlpha, 0);
         }
     }
 }
void draw_ButtonPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
Definition at line 97 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_scale, draw_shift, draw_UseSkinFor(), drawsubpic(), eX, eY, height, and vector().
Referenced by Button_draw(), InputBox_draw(), and Slider_draw().
 {
     vector square;
     vector width, height;
     vector bW;
     pic = draw_UseSkinFor(pic);
     theOrigin = boxToGlobal(theOrigin, draw_shift, draw_scale);
     theSize = boxToGlobalSize(theSize, draw_scale);
     theAlpha *= draw_alpha;
     width = eX * theSize.x;
     height = eY * theSize.y;
     if(theSize.x <= theSize.y * 2)
     {
         // button not wide enough
         // draw just left and right part then
         square = eX * theSize.x * 0.5;
         bW = eX * (0.25 * theSize.x / (theSize.y * 2));
         drawsubpic(theOrigin,          square + height, pic, '0 0 0', eY + bW, theColor, theAlpha, 0);
         drawsubpic(theOrigin + square, square + height, pic, eX - bW, eY + bW, theColor, theAlpha, 0);
     }
     else
     {
         square = eX * theSize.y;
         drawsubpic(theOrigin,                  height  +     square, pic, '0    0 0', '0.25 1 0', theColor, theAlpha, 0);
         drawsubpic(theOrigin +         square, theSize - 2 * square, pic, '0.25 0 0', '0.5  1 0', theColor, theAlpha, 0);
         drawsubpic(theOrigin + width - square, height  +     square, pic, '0.75 0 0', '0.25 1 0', theColor, theAlpha, 0);
     }
 }
void draw_CenterText (vector theOrigin, string theText, vector theSize, vector theColor, float theAlpha, float ICanHasKallerz)
Definition at line 287 of file draw.qc.
References draw_Text(), draw_TextWidth(), and eX.
Referenced by postMenuDraw(), preMenuDraw(), preMenuInit(), XonoticCharmap_cellDraw(), XonoticCreditsList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticPlayerModelSelector_draw(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotImage_draw(), and XonoticSoundList_drawListBoxItem().
 {
     //dprint(strcat("orig = ", vtos(theOrigin) ," tx = ", ftos(draw_TextWidth(theText, ICanHasKallerz, theSize)), "\n"));
     draw_Text(theOrigin - eX * 0.5 * draw_TextWidth(theText, ICanHasKallerz, theSize), theText, theSize, theColor, theAlpha, ICanHasKallerz);
 }
void draw_ClearClip ()
Definition at line 351 of file draw.qc.
References ClipFrame::clip_scale, ClipFrame::clip_shift, drawresetcliparea(), drawsetcliparea(), entity(), IL_EMPTY, IL_PEEK, IL_REMOVE(), and LOG_FATAL.
Referenced by Image_draw(), InputBox_draw(), and ListBox_draw().
 {
     if (IL_EMPTY(draw_clip)) {
         LOG_FATAL("Not clipping, can't clear it then");
     }
     entity currentSettings = IL_PEEK(draw_clip);
     IL_REMOVE(draw_clip, currentSettings);
     delete(currentSettings);
     drawresetcliparea();
     ClipFrame e = IL_PEEK(draw_clip);
     if (e) {
         drawsetcliparea(e.clip_shift.x, e.clip_shift.y, e.clip_scale.x, e.clip_scale.y);
     }
 }
float draw_CondensedFontFactor (string theText, float ICanHasKallerz, vector SizeThxBye, float maxWidth)
Definition at line 305 of file draw.qc.
References draw_TextWidth().
Referenced by XonoticGametypeList_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), and XonoticWeaponsList_drawListBoxItem().
 {
     float w = draw_TextWidth(theText, ICanHasKallerz, SizeThxBye);
     if (w > maxWidth) {
         //dprintf("NOTE: label text %s too wide for label, condensed by factor %f\n", theText, maxWidth / w);
         return maxWidth / w;
     }
     return 1.0;
 }
void draw_drawMousePointer (vector where)
Definition at line 16 of file draw.qc.
References boxToGlobal(), draw_alpha, draw_mousepointer, draw_mousepointer_offset, draw_mousepointer_size, draw_scale, draw_shift, and drawpic().
Referenced by m_draw().
 {
     drawpic(boxToGlobal(where, draw_shift, draw_scale) - draw_mousepointer_offset, draw_mousepointer, draw_mousepointer_size, '1 1 1', draw_alpha, 0);
 }
void draw_Fill (vector theOrigin, vector theSize, vector theColor, float theAlpha)
Definition at line 86 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_scale, draw_shift, and drawfill().
Referenced by MenuItem::draw(), XonoticRegisteredSettingsList::drawListBoxItem(), InputBox_draw(), ListBox_draw(), m_draw(), preMenuDraw(), preMenuInit(), XonoticCampaignList_drawListBoxItem(), XonoticCvarList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPicker_draw(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), XonoticSoundList_drawListBoxItem(), XonoticStatsList_drawListBoxItem(), and XonoticWeaponsList_drawListBoxItem().
 {
     drawfill(boxToGlobal(theOrigin, draw_shift, draw_scale), boxToGlobalSize(theSize, draw_scale), theColor, theAlpha * draw_alpha, 0);
 }
void draw_Picture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
Definition at line 72 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_scale, draw_shift, draw_UseSkinFor(), and drawpic().
Referenced by Button_draw(), draw_Picture_Aligned(), Image_draw(), InputBox_draw(), Slider_draw(), XonoticCampaignList_drawListBoxItem(), XonoticColorpicker_draw(), XonoticColorpickerString_draw(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_draw(), XonoticGametypeList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), and XonoticSkinList_drawListBoxItem().
 {
     if(theSize.x == 0 || theSize.y <= 0) // no default sizing please
         return;
     pic = draw_UseSkinFor(pic);
     drawpic(boxToGlobal(theOrigin, draw_shift, draw_scale), pic, boxToGlobalSize(theSize, draw_scale), theColor, theAlpha * draw_alpha, 0);
 }
vector draw_PictureSize (string pic)
Definition at line 80 of file draw.qc.
References draw_UseSkinFor(), and drawgetimagesize().
Referenced by draw_Picture_Aligned(), Image_updateAspect(), XonoticCampaignList_drawListBoxItem(), XonoticColorpickerString_draw(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_draw(), XonoticMapInfoDialog_loadMapInfo(), XonoticMapList_drawListBoxItem(), XonoticPlayerModelSelector_go(), XonoticServerList_drawListBoxItem(), and XonoticSkinList_getSkins().
 {
     pic = draw_UseSkinFor(pic);
     return drawgetimagesize(pic);
 }
string draw_PreloadPicture (string pic)
Definition at line 60 of file draw.qc.
References draw_UseSkinFor(), and precache_pic().
Referenced by XonoticMapList_refilter().
 {
     pic = draw_UseSkinFor(pic);
     return precache_pic(pic);
 }
string draw_PreloadPictureWithFlags (string pic, float f)
Definition at line 66 of file draw.qc.
References draw_UseSkinFor(), and precache_pic().
Referenced by XonoticGametypeList_configureXonoticGametypeList().
 {
     pic = draw_UseSkinFor(pic);
     return precache_pic(pic, f);
 }
void draw_reset (float cw, float ch, float ox, float oy)
Definition at line 21 of file draw.qc.
References draw_alpha, draw_endBoldFont, draw_fontscale, draw_scale, and draw_shift.
Referenced by draw_reset_cropped(), and draw_reset_full().
 {
     draw_shift = '1 0 0' * ox + '0 1 0' * oy;
     draw_scale = '1 0 0' * cw + '0 1 0' * ch;
     draw_alpha = 1;
     draw_fontscale = '1 1 0';
     draw_endBoldFont();
 }
void draw_SetClip ()
Definition at line 338 of file draw.qc.
References _draw_SetClip(), draw_scale, and draw_shift.
Referenced by Image_draw(), and ListBox_draw().
 {
     _draw_SetClip(draw_shift, draw_scale);
 }
void draw_SetClipRect (vector theOrigin, vector theScale)
Definition at line 343 of file draw.qc.
References _draw_SetClip(), boxToGlobal(), boxToGlobalSize(), draw_scale, and draw_shift.
Referenced by InputBox_draw().
 {
     _draw_SetClip(
         boxToGlobal(theOrigin, draw_shift, draw_scale),
         boxToGlobalSize(theScale, draw_scale)
     );
 }
void draw_setMousePointer (string pic, vector theSize, vector theOffset)
Definition at line 9 of file draw.qc.
References draw_mousepointer, draw_mousepointer_offset, draw_mousepointer_size, draw_UseSkinFor(), eX, eY, and strzone().
Referenced by m_init_delayed().
 {
     draw_mousepointer = strzone(draw_UseSkinFor(pic));
     draw_mousepointer_size = theSize;
     draw_mousepointer_offset = eX * (theOffset.x * theSize.x) + eY * (theOffset.y * theSize.y);
 }
void draw_Text (vector theOrigin, string theText, vector theSize, vector theColor, float theAlpha, float ICanHasKallerz)
Definition at line 271 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_fontscale, draw_scale, draw_shift, drawcolorcodedstring(), drawstring(), globalToBoxSize(), and LOG_TRACE().
Referenced by draw_CenterText(), XonoticRegisteredSettingsList::drawListBoxItem(), InputBox_draw(), Label_draw(), ListBox_drawListBoxItem(), m_tooltip(), XonoticCampaignList_drawListBoxItem(), XonoticCvarList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPlayerList_drawListBoxItem(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotImage_draw(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), XonoticSoundList_drawListBoxItem(), XonoticStatsList_drawListBoxItem(), and XonoticWeaponsList_drawListBoxItem().
 {
     if(theSize.x <= 0 || theSize.y <= 0) {
         LOG_TRACE("Drawing zero size text?");
         return;
     }
     //float wi;
     //wi = draw_TextWidth(theText, ICanHasKallerz, theSize);
     //draw_Fill(theOrigin, '1 0 0' * wi + '0 1 0' * theSize_y, '1 0 0', 0.3);
     if(ICanHasKallerz)
         drawcolorcodedstring(boxToGlobal(theOrigin, draw_shift, draw_scale), theText, globalToBoxSize(boxToGlobalSize(theSize, draw_scale), draw_fontscale), theAlpha * draw_alpha, 0);
     else
         drawstring(boxToGlobal(theOrigin, draw_shift, draw_scale), theText, globalToBoxSize(boxToGlobalSize(theSize, draw_scale), draw_fontscale), theColor, theAlpha * draw_alpha, 0);
 }
float draw_TextLengthUpToWidth (string theText, float maxWidth, float allowColorCodes, vector theFontSize)
Definition at line 390 of file draw.qc.
References draw_TextWidth_WithColors(), draw_TextWidth_WithoutColors(), and textLengthUpToWidth().
Referenced by InputBox_mouseDrag().
 {
     if(allowColorCodes)
         return textLengthUpToWidth(theText, maxWidth, theFontSize, draw_TextWidth_WithColors);
     else
         return textLengthUpToWidth(theText, maxWidth, theFontSize, draw_TextWidth_WithoutColors);
 }
string draw_TextShortenToWidth (string theText, float maxWidth, float ICanHasKallerz, vector SizeThxBye)
Definition at line 366 of file draw.qc.
References draw_TextWidth_WithColors(), draw_TextWidth_WithoutColors(), and textShortenToWidth().
Referenced by XonoticRegisteredSettingsList::drawListBoxItem(), Label_draw(), XonoticCampaignList_drawListBoxItem(), XonoticCvarList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPlayerList_drawListBoxItem(), XonoticPlayList_drawListBoxItem(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), XonoticSoundList_drawListBoxItem(), and XonoticStatsList_drawListBoxItem().
 {
     /*
     if(draw_TextWidth(theText, ICanHasKallerz, SizeThxBye) <= maxWidth)
         return theText;
     else
         return strcat(substring(theText, 0, draw_TextLengthUpToWidth(theText, maxWidth - draw_TextWidth("...", ICanHasKallerz, SizeThxBye), ICanHasKallerz, SizeThxBye)), "...");
     */
     if(ICanHasKallerz)
         return textShortenToWidth(theText, maxWidth, SizeThxBye, draw_TextWidth_WithColors);
     else
         return textShortenToWidth(theText, maxWidth, SizeThxBye, draw_TextWidth_WithoutColors);
 }
float draw_TextWidth (string theText, float ICanHasKallerz, vector SizeThxBye)
Definition at line 293 of file draw.qc.
References boxToGlobalSize(), draw_fontscale, draw_scale, globalToBoxSize(), stringwidth(), v, and vector().
Referenced by draw_CenterText(), draw_CondensedFontFactor(), draw_TextWidth_WithColors(), draw_TextWidth_WithoutColors(), InputBox_draw(), Label_recalcPositionWithText(), m_tooltip(), preMenuDraw(), XonoticCampaignList_drawListBoxItem(), XonoticDemoList_drawListBoxItem(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticLanguageList_drawListBoxItem(), XonoticMapList_drawListBoxItem(), XonoticPlayerList_drawListBoxItem(), XonoticScreenshotList_drawListBoxItem(), XonoticServerList_drawListBoxItem(), XonoticSkinList_drawListBoxItem(), and XonoticStatsList_drawListBoxItem().
 {
     //return strlen(theText);
     //dprint("draw_TextWidth \"", theText, "\"\n");
     vector v;
     v = '0 0 0';
     //float r;
     v.x = stringwidth(theText, ICanHasKallerz, globalToBoxSize(boxToGlobalSize(SizeThxBye, draw_scale), draw_fontscale));
     v = globalToBoxSize(v, draw_scale);
     return v.x;
 }
float draw_TextWidth_WithColors (string s, vector theFontSize)
Definition at line 380 of file draw.qc.
References draw_TextWidth().
Referenced by draw_TextLengthUpToWidth(), draw_TextShortenToWidth(), Label_draw(), and Label_recalcPositionWithText().
 {
     return draw_TextWidth(s, true, theFontSize);
 }
float draw_TextWidth_WithoutColors (string s, vector theFontSize)
Definition at line 385 of file draw.qc.
References draw_TextWidth().
Referenced by draw_TextLengthUpToWidth(), draw_TextShortenToWidth(), Label_draw(), Label_recalcPositionWithText(), m_tooltip(), and rewrapCampaign().
 {
     return draw_TextWidth(s, false, theFontSize);
 }
void draw_VertButtonPicture (vector theOrigin, string pic, vector theSize, vector theColor, float theAlpha)
Definition at line 132 of file draw.qc.
References boxToGlobal(), boxToGlobalSize(), draw_alpha, draw_scale, draw_shift, draw_UseSkinFor(), drawsubpic(), eX, eY, height, and vector().
Referenced by ListBox_draw().
 {
     vector square;
     vector width, height;
     vector bH;
     pic = draw_UseSkinFor(pic);
     theOrigin = boxToGlobal(theOrigin, draw_shift, draw_scale);
     theSize = boxToGlobalSize(theSize, draw_scale);
     theAlpha *= draw_alpha;
     width = eX * theSize.x;
     height = eY * theSize.y;
     if(theSize.y <= theSize.x * 2)
     {
         // button not high enough
         // draw just upper and lower part then
         square = eY * theSize.y * 0.5;
         bH = eY * (0.25 * theSize.y / (theSize.x * 2));
         drawsubpic(theOrigin,          square + width, pic, '0 0 0', eX + bH, theColor, theAlpha, 0);
         drawsubpic(theOrigin + square, square + width, pic, eY - bH, eX + bH, theColor, theAlpha, 0);
     }
     else
     {
         square = eY * theSize.x;
         drawsubpic(theOrigin,                   width   +     square, pic, '0 0    0', '1 0.25 0', theColor, theAlpha, 0);
         drawsubpic(theOrigin +          square, theSize - 2 * square, pic, '0 0.25 0', '1 0.5  0', theColor, theAlpha, 0);
         drawsubpic(theOrigin + height - square, width   +     square, pic, '0 0.75 0', '1 0.25 0', theColor, theAlpha, 0);
     }
 }
vector globalToBox (vector v, vector theOrigin, vector theScale)
Definition at line 30 of file draw.qc.
References v.
Referenced by Container_mouseDrag(), Container_mouseMove(), Container_mouseRelease(), InputContainer__changeFocusXY(), ListBox_mouseRelease(), m_draw(), m_findtooltipitem(), ModalController_showChild(), and Container::mousePress().
 {
     v -= theOrigin;
     v.x /= theScale.x;
     v.y /= theScale.y;
     return v;
 }
vector globalToBoxSize (vector v, vector theScale)
Definition at line 38 of file draw.qc.
References v.
Referenced by BorderImage_draw(), draw_Text(), draw_TextWidth(), m_draw(), ModalController_draw(), ModalController_showChild(), Nexposee_draw(), postMenuDraw(), XonoticColorpickerString_draw(), XonoticCrosshairPicker_cellDraw(), and XonoticCrosshairPreview_draw().
 {
     v.x /= theScale.x;
     v.y /= theScale.y;
     return v;
 }
STATIC_INIT (draw_clip)
Definition at line 316 of file draw.qc.
References IL_NEW.
 { draw_clip = IL_NEW(); }
Variable Documentation
IntrusiveList draw_clip
Definition at line 315 of file draw.qc.
string draw_mousepointer
Definition at line 5 of file draw.qc.
Referenced by draw_drawMousePointer(), and draw_setMousePointer().
vector draw_mousepointer_offset
Definition at line 6 of file draw.qc.
Referenced by draw_drawMousePointer(), and draw_setMousePointer().
vector draw_mousepointer_size
Definition at line 7 of file draw.qc.
Referenced by draw_drawMousePointer(), and draw_setMousePointer().