Xonotic: server/playerdemo.qc File Reference
playerdemo.qc File Reference
#include "playerdemo.qh"
Macros
#define PLAYERDEMO_FIELD(ent, func, t, f) func##t(ent,f,#f);
#define PLAYERDEMO_FIELDS(ent, func)
Functions
void playerdemo_init (entity this)
void playerdemo_open_read (entity this, string f)
void playerdemo_open_write (entity this, string f)
float playerdemo_read (entity this)
void playerdemo_read_float (entity this,.float f, string name)
void playerdemo_read_modelstring (entity this,.string f, string name)
void playerdemo_read_originvector (entity this,.vector f, string name)
void playerdemo_read_sizevector (entity this,.vector f, string name)
void playerdemo_read_string (entity this,.string f, string name)
void playerdemo_read_vector (entity this,.vector f, string name)
void playerdemo_shutdown (entity this)
void playerdemo_write (entity this)
void playerdemo_write_float (entity this,.float f, string name)
void playerdemo_write_modelstring (entity this,.string f, string name)
void playerdemo_write_originvector (entity this,.vector f, string name)
void playerdemo_write_sizevector (entity this,.vector f, string name)
void playerdemo_write_string (entity this,.string f, string name)
void playerdemo_write_vector (entity this,.vector f, string name)
Variables
float playerdemo_fh
float playerdemo_mode
const float PLAYERDEMO_MODE_OFF = 0
const float PLAYERDEMO_MODE_READING = 1
const float PLAYERDEMO_MODE_WRITING = 2
float playerdemo_starttime
float playerdemo_time
Macro Definition Documentation
#define PLAYERDEMO_FIELD (ent, func, t, f) func##t(ent,f,#f);
Definition at line 50 of file playerdemo.qc.
#define PLAYERDEMO_FIELDS (ent, func)
Value:
PLAYERDEMO_FIELD(ent,func,originvector,origin) \
    PLAYERDEMO_FIELD(ent,func,vector,angles) \
    PLAYERDEMO_FIELD(ent,func,sizevector,mins) \
    PLAYERDEMO_FIELD(ent,func,sizevector,maxs) \
    PLAYERDEMO_FIELD(ent,func,vector,v_angle) \
    PLAYERDEMO_FIELD(ent,func,modelstring,model) \
    PLAYERDEMO_FIELD(ent,func,string,playermodel) \
    PLAYERDEMO_FIELD(ent,func,float,skin) \
    PLAYERDEMO_FIELD(ent,func,string,playerskin) \
    PLAYERDEMO_FIELD(ent,func,float,frame) \
    PLAYERDEMO_FIELD(ent,func,float,effects) \
    /* PLAYERDEMO_FIELD(ent,func,float,switchweapon) */ \
    PLAYERDEMO_FIELD(CS(ent),func,float,button0) /* TODO: PHYS_INPUT_BUTTON_ATCK */ \
    PLAYERDEMO_FIELD(CS(ent),func,float,button3) /* TODO: PHYS_INPUT_BUTTON_ATCK2 */ \
    PLAYERDEMO_FIELD(CS(ent),func,float,button5) /* TODO: PHYS_INPUT_BUTTON_CROUCH */ \
    PLAYERDEMO_FIELD(CS(ent),func,float,button6) /* TODO: PHYS_INPUT_BUTTON_HOOK */ \
    PLAYERDEMO_FIELD(CS(ent),func,float,buttonuse) /* TODO: PHYS_INPUT_BUTTON_USE */ \
    PLAYERDEMO_FIELD(ent,func,float,flags) \
Definition at line 51 of file playerdemo.qc.
Referenced by playerdemo_read(), and playerdemo_write().
Function Documentation
void playerdemo_init (entity this)
Definition at line 17 of file playerdemo.qc.
References playerdemo_mode, and PLAYERDEMO_MODE_OFF.
Referenced by ClientState_attach().
 {
     this.playerdemo_mode = PLAYERDEMO_MODE_OFF;
 }
void playerdemo_open_read (entity this, string f)
Definition at line 30 of file playerdemo.qc.
References fgets(), FILE_READ, fopen(), LOG_INFO, MOVETYPE_NONE, netname, playerdemo_fh, playerdemo_mode, PLAYERDEMO_MODE_READING, playerdemo_shutdown(), playerdemo_starttime, playerdemo_time, set_movetype(), stof(), and time.
Referenced by GameCommand_playerdemo().
 {
     playerdemo_shutdown(this);
     this.playerdemo_mode = PLAYERDEMO_MODE_READING;
     this.playerdemo_fh = fopen(f, FILE_READ);
     this.playerdemo_starttime = time - 1;
     this.playerdemo_time = stof(fgets(this.playerdemo_fh));
     this.playerdemo_time += this.playerdemo_starttime;
     set_movetype(this, MOVETYPE_NONE);
     LOG_INFO("playerdemo: ", this.netname, " reading from ", f);
 }
void playerdemo_open_write (entity this, string f)
Definition at line 41 of file playerdemo.qc.
References FILE_WRITE, fopen(), LOG_INFO, netname, playerdemo_fh, playerdemo_mode, PLAYERDEMO_MODE_WRITING, playerdemo_shutdown(), playerdemo_starttime, and time.
Referenced by GameCommand_playerdemo().
 {
     playerdemo_shutdown(this);
     this.playerdemo_mode = PLAYERDEMO_MODE_WRITING;
     this.playerdemo_fh = fopen(f, FILE_WRITE);
     this.playerdemo_starttime = time - 1;
     LOG_INFO("playerdemo: ", this.netname, " writing to ", f);
     LOG_INFO("WARNING: playerdemo file format is incomplete and not stable yet. DO NOT RELY ON IT!");
 }
float playerdemo_read (entity this)
Definition at line 138 of file playerdemo.qc.
References CS(), dmg_inflictor, dmg_save, dmg_take, fgets(), NULL, playerdemo_fh, PLAYERDEMO_FIELDS, playerdemo_mode, PLAYERDEMO_MODE_READING, playerdemo_starttime, playerdemo_time, PlayerPostThink(), PlayerPreThink(), stof(), time, and velocity.
Referenced by sys_phys_ai().
 {
     if(this.playerdemo_mode != PLAYERDEMO_MODE_READING)
         return 0;
     if(this.playerdemo_time < 0)
         return 1;
     float t;
     t = time;
     while(time >= this.playerdemo_time)
     {
         PLAYERDEMO_FIELDS(this, playerdemo_read_)
         {
             time = this.playerdemo_time;
             PlayerPreThink(this);
             // not running physics though... this is just so we can run weapon stuff
             PlayerPostThink(this);
         }
         this.playerdemo_time = stof(fgets(this.playerdemo_fh));
         if(this.playerdemo_time == 0)
         {
             this.playerdemo_time = -1;
             return 1;
         }
         this.playerdemo_time += this.playerdemo_starttime;
     }
     this.velocity = '0 0 0';
     CS(this).movement = '0 0 0';
     this.dmg_take = 0; // so screen doesn't stay blurry
     this.dmg_save = 0;
     this.dmg_inflictor = NULL;
     time = t;
     return 1;
 }
void playerdemo_read_float (entity this, .float f, string name)
Definition at line 134 of file playerdemo.qc.
References fgets(), playerdemo_fh, and stof().
 {
     this.(f) = stof(fgets(this.playerdemo_fh));
 }
void playerdemo_read_modelstring (entity this, .string f, string name)
Definition at line 128 of file playerdemo.qc.
References fgets(), and playerdemo_fh.
 {
     string s = fgets(this.playerdemo_fh);
     if (s != this.(f))
         _setmodel(this, s);
 }
void playerdemo_read_originvector (entity this, .vector f, string name)
Definition at line 103 of file playerdemo.qc.
References fgets(), playerdemo_fh, setorigin(), and stov().
 {
     setorigin(this, stov(fgets(this.playerdemo_fh)));
 }
void playerdemo_read_sizevector (entity this, .vector f, string name)
Definition at line 107 of file playerdemo.qc.
References fgets(), maxs, mins, playerdemo_fh, and stov().
 {
     this.(f) = stov(fgets(this.playerdemo_fh));
     setsize(this, this.mins, this.maxs);
 }
void playerdemo_read_string (entity this, .string f, string name)
Definition at line 116 of file playerdemo.qc.
References fgets(), playerdemo_fh, and strzone().
 {
     string s = fgets(this.playerdemo_fh);
     if (s != this.(f))
     {
         /*
         if(this.f)
             strunzone(this.f);
         */
         this.(f) = strzone(s);
     }
 }
void playerdemo_read_vector (entity this, .vector f, string name)
Definition at line 112 of file playerdemo.qc.
References fgets(), playerdemo_fh, and stov().
 {
     this.(f) = stov(fgets(this.playerdemo_fh));
 }
void playerdemo_shutdown (entity this)
Definition at line 21 of file playerdemo.qc.
References fclose(), LOG_INFO, netname, playerdemo_fh, playerdemo_mode, and PLAYERDEMO_MODE_OFF.
Referenced by ClientState_detach(), playerdemo_open_read(), and playerdemo_open_write().
 {
     if(this.playerdemo_mode != PLAYERDEMO_MODE_OFF)
     {
         LOG_INFO("playerdemo: ", this.netname, " closed");
         fclose(this.playerdemo_fh);
     }
     this.playerdemo_mode = 0;
 }
void playerdemo_write (entity this)
Definition at line 96 of file playerdemo.qc.
References fputs(), ftos(), playerdemo_fh, PLAYERDEMO_FIELDS, playerdemo_mode, PLAYERDEMO_MODE_WRITING, playerdemo_starttime, strcat(), and time.
Referenced by PlayerPostThink().
 {
     if(this.playerdemo_mode != PLAYERDEMO_MODE_WRITING)
         return;
     fputs(this.playerdemo_fh, strcat(ftos(time - this.playerdemo_starttime), "\n"));
     PLAYERDEMO_FIELDS(this, playerdemo_write_)
 }
void playerdemo_write_float (entity this, .float f, string name)
Definition at line 92 of file playerdemo.qc.
References fputs(), ftos(), playerdemo_fh, and strcat().
 {
     fputs(this.playerdemo_fh, strcat(ftos(this.(f)), "\n"));
 }
void playerdemo_write_modelstring (entity this, .string f, string name)
Definition at line 88 of file playerdemo.qc.
References fputs(), playerdemo_fh, and strcat().
 {
     fputs(this.playerdemo_fh, strcat(this.(f), "\n"));
 }
void playerdemo_write_originvector (entity this, .vector f, string name)
Definition at line 72 of file playerdemo.qc.
References fputs(), playerdemo_fh, strcat(), and vtos().
 {
     fputs(this.playerdemo_fh, strcat(vtos(this.(f)), "\n"));
 }
void playerdemo_write_sizevector (entity this, .vector f, string name)
Definition at line 76 of file playerdemo.qc.
References fputs(), playerdemo_fh, strcat(), and vtos().
 {
     fputs(this.playerdemo_fh, strcat(vtos(this.(f)), "\n"));
 }
void playerdemo_write_string (entity this, .string f, string name)
Definition at line 84 of file playerdemo.qc.
References fputs(), playerdemo_fh, and strcat().
 {
     fputs(this.playerdemo_fh, strcat(this.(f), "\n"));
 }
void playerdemo_write_vector (entity this, .vector f, string name)
Definition at line 80 of file playerdemo.qc.
References fputs(), playerdemo_fh, strcat(), and vtos().
 {
     fputs(this.playerdemo_fh, strcat(vtos(this.(f)), "\n"));
 }
Variable Documentation
float playerdemo_fh
Definition at line 10 of file playerdemo.qc.
Referenced by playerdemo_open_read(), playerdemo_open_write(), playerdemo_read(), playerdemo_read_float(), playerdemo_read_modelstring(), playerdemo_read_originvector(), playerdemo_read_sizevector(), playerdemo_read_string(), playerdemo_read_vector(), playerdemo_shutdown(), playerdemo_write(), playerdemo_write_float(), playerdemo_write_modelstring(), playerdemo_write_originvector(), playerdemo_write_sizevector(), playerdemo_write_string(), and playerdemo_write_vector().
float playerdemo_mode
Definition at line 11 of file playerdemo.qc.
Referenced by playerdemo_init(), playerdemo_open_read(), playerdemo_open_write(), playerdemo_read(), playerdemo_shutdown(), and playerdemo_write().
const float PLAYERDEMO_MODE_OFF = 0
Definition at line 14 of file playerdemo.qc.
Referenced by playerdemo_init(), and playerdemo_shutdown().
const float PLAYERDEMO_MODE_READING = 1
Definition at line 15 of file playerdemo.qc.
Referenced by playerdemo_open_read(), and playerdemo_read().
const float PLAYERDEMO_MODE_WRITING = 2
Definition at line 16 of file playerdemo.qc.
Referenced by playerdemo_open_write(), and playerdemo_write().
float playerdemo_starttime
Definition at line 12 of file playerdemo.qc.
Referenced by playerdemo_open_read(), playerdemo_open_write(), playerdemo_read(), and playerdemo_write().
float playerdemo_time
Definition at line 13 of file playerdemo.qc.
Referenced by playerdemo_open_read(), and playerdemo_read().