Xonotic: lib/angle.qc File Reference
angle.qc File Reference
Macros
#define angleofs(from, to) angleofs3(from.origin, from.angles, to.origin)
Functions
ERASEABLE float anglemods (float v)
ERASEABLE vector angleofs3 (vector from, vector ang, vector to)
ERASEABLE float shortangle_f (float ang1, float ang2)
ERASEABLE vector shortangle_v (vector ang1, vector ang2)
ERASEABLE vector shortangle_vxy (vector ang1, vector ang2)
Variables
vector angles
vector origin
Macro Definition Documentation
#define angleofs (from, to) angleofs3(from.origin, from.angles, to.origin)
Definition at line 90 of file angle.qc.
Function Documentation
ERASEABLE float anglemods (float v)
Definition at line 13 of file angle.qc.
References floor(), and v.
Referenced by Monster_Move_2D().
 {
     v = v - 360 * floor(v / 360);
     if(v >= 180)
         return v - 360;
     else if(v <= -180)
         return v + 360;
     else
         return v;
 }
ERASEABLE vector angleofs3 (vector from, vector ang, vector to)
Definition at line 73 of file angle.qc.
References normalize(), vectoangles(), and vector().
 {
     vector v_res;
     v_res = normalize(to - from);
     v_res = vectoangles(v_res);
     v_res = v_res - ang;
     if (v_res_x < 0)    v_res_x += 360;
     if (v_res_x > 180)  v_res_x -= 360;
     if (v_res_y < 0)    v_res_y += 360;
     if (v_res_y > 180)  v_res_y -= 360;
     return v_res;
 }
ERASEABLE float shortangle_f (float ang1, float ang2)
Definition at line 29 of file angle.qc.
Referenced by Monster_Move(), shortangle_v(), and shortangle_vxy().
 {
     if(ang1 > ang2)
     {
         if(ang1 > 180)
             return ang1 - 360;
     }
     else
     {
         if(ang1 < -180)
             return ang1 + 360;
     }
     return ang1;
 }
ERASEABLE vector shortangle_v (vector ang1, vector ang2)
Definition at line 46 of file angle.qc.
References shortangle_f(), and vector().
 {
     vector vtmp;
     vtmp_x = shortangle_f(ang1_x,ang2_x);
     vtmp_y = shortangle_f(ang1_y,ang2_y);
     vtmp_z = shortangle_f(ang1_z,ang2_z);
     return vtmp;
 }
ERASEABLE vector shortangle_vxy (vector ang1, vector ang2)
Definition at line 58 of file angle.qc.
References shortangle_f(), and vector().
 {
     vector vtmp = '0 0 0';
     vtmp_x = shortangle_f(ang1_x,ang2_x);
     vtmp_y = shortangle_f(ang1_y,ang2_y);
     return vtmp;
 }
Variable Documentation
vector angles
Definition at line 7 of file angle.qc.
vector origin
Definition at line 1 of file angle.qc.