Xonotic: common/mutators/mutator/pinata/sv_pinata.qc File Reference
sv_pinata.qc File Reference
#include "sv_pinata.qh"
Functions
MUTATOR_HOOKFUNCTION (pinata, PlayerDies)
MUTATOR_HOOKFUNCTION (pinata, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (pinata, BuildMutatorsPrettyString)
REGISTER_MUTATOR (pinata, expr_evaluate(autocvar_g_pinata)&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok))
Variables
string autocvar_g_pinata
Function Documentation
MUTATOR_HOOKFUNCTION (pinata , PlayerDies)
Definition at line 6 of file sv_pinata.qc.
References CENTER_OR_VIEWOFS, entity(), FOREACH, M_ARGV, MAX_WEAPONSLOTS, randomvec(), W_IsWeaponThrowable(), W_ThrowNewWeapon(), weaponentities, and WepSet_FromWeapon.
 {
     entity frag_target = M_ARGV(2, entity);
     for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         .entity weaponentity = weaponentities[slot];
         if(frag_target.(weaponentity).m_weapon == WEP_Null)
             continue;
         FOREACH(Weapons, it != WEP_Null, {
             if(STAT(WEAPONS, frag_target) & WepSet_FromWeapon(it))
             if(frag_target.(weaponentity).m_weapon != it)
             if(W_IsWeaponThrowable(frag_target, it.m_id))
                 W_ThrowNewWeapon(frag_target, it.m_id, false, CENTER_OR_VIEWOFS(frag_target), randomvec() * 175 + '0 0 325', weaponentity);
         });
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (pinata , BuildMutatorsString)
Definition at line 28 of file sv_pinata.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":Pinata");
 }
MUTATOR_HOOKFUNCTION (pinata , BuildMutatorsPrettyString)
Definition at line 33 of file sv_pinata.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Piñata");
 }
REGISTER_MUTATOR (pinata , expr_evaluate(autocvar_g_pinata)&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok))
Variable Documentation
string autocvar_g_pinata
Definition at line 3 of file sv_pinata.qc.