Xonotic: common/minigames/minigames.qh File Reference
minigames.qh File Reference
#include "minigame/all.qh"
Functions
int (entity, string,...) minigame_event
For minigame sessions/descriptors: execute the given event Client events: mouse_moved(vector mouse_pos) return 1 to handle input, 0 to discard mouse_pressed/released(int K_Keycode) return 1 to handle input, 0 to discard note: see dpdefs/keycodes.qc for values key_pressed/released(int K_Keycode) return 1 to handle input, 0 to discard note: see dpdefs/keycodes.qc for values activate() executed when the minigame is activated for the current client deactivate() executed when the minigame is deactivated for the current client network_receive(entity received,int flags) executed each time a networked entity is received note: when this is called self == ...(0,entity) You can use the MINIG_SF_ constants to check the send flags IMPORTANT: always read in client everything you send from the server! menu_show(entity parent_menu_item) executed when the Current Game menu is shown, used to add custom entries Call HUD_MinigameMenu_CustomEntry to do so (pass ...(0,entity) as first argument) menu_click(string arg) executed when a custom menu entry is clicked Server events: start() executed when the minigame session is starting end() executed when the minigame session is shutting down join(entity player) executed when a player wants to join the session return the player team number to accept the new player, 0 to discard part(entity player) executed when a player is going to leave the session network_send(entity sent,int flags) executed each time a networked entity is sent note: when this is called self == ...(0,entity) You can use the MINIG_SF_ constants to check the send flags IMPORTANT: always read in client everything you send from the server! cmd(entity minigame_player, int argc, string command) self = client entity triggering this argv(n) = console token argc: number of console tokens command: full command string triggered when a player does "cmd minigame ..." with some unrecognized command return 1 if the minigame has handled the command impulse(entity minigame_player,int impulse) self = client entity triggering this triggered when a player does "impulse ..." return 1 if the minigame has handled the impulse.
int minigame_count_players (entity minigame)
entity minigame_get_descriptor (string id)
int minigame_next_team (int curr_team, int n_teams)
int minigame_prev_team (int curr_team, int n_teams)
string minigame_relative_tile (string start_id, int dx, int dy, int rows, int columns)
void minigame_server_sendflags (entity ent, int mgflags)
string minigame_tile_buildname (int letter, int number)
int minigame_tile_letter (string id)
string minigame_tile_name (vector pos, int rows, int columns)
int minigame_tile_number (string id)
vector minigame_tile_pos (string id, int rows, int columns)
string msle_classname (int id)
int msle_id (string class_name)
entity msle_spawn (entity minigame_session, string class_name)
Variables
entity descriptor
For minigame sessions: minigame descriptor object.
entity list_next
entity list_prev
const int MINIG_SF_ALL = 0xff
const int MINIG_SF_CREATE = 0x01
const int MINIG_SF_CUSTOM = 0x10
const int MINIG_SF_MAX = 0x80
const int MINIG_SF_UPDATE = 0x02
bool minigame_autoclean
int minigame_flags
Function Documentation
int (entity , string , ...)
For minigame sessions/descriptors: execute the given event Client events: mouse_moved(vector mouse_pos) return 1 to handle input, 0 to discard mouse_pressed/released(int K_Keycode) return 1 to handle input, 0 to discard note: see dpdefs/keycodes.qc for values key_pressed/released(int K_Keycode) return 1 to handle input, 0 to discard note: see dpdefs/keycodes.qc for values activate() executed when the minigame is activated for the current client deactivate() executed when the minigame is deactivated for the current client network_receive(entity received,int flags) executed each time a networked entity is received note: when this is called self == ...(0,entity) You can use the MINIG_SF_ constants to check the send flags IMPORTANT: always read in client everything you send from the server! menu_show(entity parent_menu_item) executed when the Current Game menu is shown, used to add custom entries Call HUD_MinigameMenu_CustomEntry to do so (pass ...(0,entity) as first argument) menu_click(string arg) executed when a custom menu entry is clicked Server events: start() executed when the minigame session is starting end() executed when the minigame session is shutting down join(entity player) executed when a player wants to join the session return the player team number to accept the new player, 0 to discard part(entity player) executed when a player is going to leave the session network_send(entity sent,int flags) executed each time a networked entity is sent note: when this is called self == ...(0,entity) You can use the MINIG_SF_ constants to check the send flags IMPORTANT: always read in client everything you send from the server! cmd(entity minigame_player, int argc, string command) self = client entity triggering this argv(n) = console token argc: number of console tokens command: full command string triggered when a player does "cmd minigame ..." with some unrecognized command return 1 if the minigame has handled the command impulse(entity minigame_player,int impulse) self = client entity triggering this triggered when a player does "impulse ..." return 1 if the minigame has handled the impulse.
int minigame_count_players (entity minigame)
Definition at line 123 of file minigames.qc.
References entity(), findentity(), NULL, and owner.
 {
     int pl_num = 0;
     entity e;
 #ifdef SVQC
     for(e = minigame.minigame_players; e; e = e.list_next)
 #elif defined(CSQC)
     e = NULL;
     while( (e = findentity(e,owner,minigame)) )
         if ( e.classname == "minigame_player" )
 #endif
         pl_num++;
     return pl_num;
 }
entity minigame_get_descriptor (string id)
Definition at line 5 of file minigames.qc.
References FOREACH, and NULL.
Referenced by HUD_MinigameBoard(), HUD_MinigameStatus(), NET_HANDLE(), and start_minigame().
 {
     FOREACH(Minigames, it.netname == id, return it);
     return NULL;
 }
int minigame_next_team (int curr_team, int n_teams)
Definition at line 65 of file minigames.qc.
Referenced by c4_move(), pp_move(), and ttt_move().
 {
     return curr_team % n_teams + 1;
 }
int minigame_prev_team (int curr_team, int n_teams)
Definition at line 71 of file minigames.qc.
 {
     return curr_team % n_teams - 1;
 }
string minigame_relative_tile (string start_id, int dx, int dy, int rows, int columns)
Definition at line 40 of file minigames.qc.
References minigame_tile_buildname(), minigame_tile_letter(), and minigame_tile_number().
Referenced by snake_move_head().
 {
     int letter = minigame_tile_letter(start_id);
     int number = minigame_tile_number(start_id);
     letter = (letter+dx) % columns;
     number = (number+dy) % rows;
     if ( letter < 0 )
         letter = columns + letter;
     if ( number < 0 )
         number = rows + number;
     return minigame_tile_buildname(letter, number);
 }
void minigame_server_sendflags (entity ent, int mgflags)
Definition at line 78 of file minigames.qc.
Referenced by bd_activate_editor(), bd_check_winner(), bd_close_editor(), bd_do_next_match(), bd_editor_place(), bd_load_piece(), bd_move(), bd_move_dozer(), bd_reset_moves(), bd_restart_match(), c4_move(), minigame_setup_snake(), pp_move(), pp_next_match(), pp_setup_pieces(), ps_move(), ps_move_piece(), ps_setup_pieces(), snake_check_winner(), snake_move(), snake_move_body(), snake_move_head(), snake_new_mouse(), snake_setup_pieces(), ttt_move(), and ttt_next_match().
 {
     #ifdef SVQC
         ent.SendFlags |= mgflags;
     #endif
 }
string minigame_tile_buildname (int letter, int number)
Definition at line 34 of file minigames.qc.
References chr2str, ftos(), and strcat().
Referenced by bd_fill_recurse(), bd_move_dozer(), bd_unfill_recurse(), c4_get_lowest_tile(), c4_winning_piece(), minigame_relative_tile(), minigame_setup_snake(), minigame_tile_name(), nmm_spawn_tile_square(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), pp_setup_pieces(), pp_valid_move(), pp_winning_piece(), ps_move(), ps_move_piece(), ps_setup_pieces(), ps_winning_piece(), snake_move(), snake_move_head(), snake_new_mouse(), and ttt_winning_piece().
 {
     return strcat(chr2str('a'+letter),ftos(number+1));
 }
int minigame_tile_letter (string id)
Definition at line 12 of file minigames.qc.
References str2chr, and substring().
Referenced by bd_do_fill(), bd_move_dozer(), bd_valid_tile(), c4_get_lowest_tile(), c4_valid_tile(), c4_winning_piece(), minigame_relative_tile(), minigame_tile_pos(), nmm_tile_adjacent(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), pp_valid_move(), pp_valid_tile(), pp_winning_piece(), ps_move(), ps_tile_blacklisted(), ps_valid_tile(), ps_winning_piece(), snake_move(), snake_move_head(), snake_valid_tile(), ttt_valid_tile(), and ttt_winning_piece().
 {
     return str2chr(substring(id,0,1),0)-'a';
 }
string minigame_tile_name (vector pos, int rows, int columns)
Definition at line 54 of file minigames.qc.
References floor(), and minigame_tile_buildname().
 {
     if ( pos_x < 0 || pos_x > 1 || pos_y < 0 || pos_y > 1 )
         return ""; // no tile
     int letter = floor(pos_x * columns);
     int number = floor((1-pos_y) * rows);
     return minigame_tile_buildname(letter, number);
 }
int minigame_tile_number (string id)
Definition at line 21 of file minigames.qc.
References stof(), and substring().
Referenced by bd_do_fill(), bd_move_dozer(), bd_valid_tile(), c4_valid_tile(), c4_winning_piece(), minigame_relative_tile(), minigame_tile_pos(), nmm_tile_adjacent(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), pp_valid_move(), pp_valid_tile(), pp_winning_piece(), ps_move(), ps_tile_blacklisted(), ps_valid_tile(), ps_winning_piece(), snake_move(), snake_move_head(), snake_valid_tile(), ttt_valid_tile(), and ttt_winning_piece().
 {
     return stof(substring(id,1,-1)) -1 ;
 }
vector minigame_tile_pos (string id, int rows, int columns)
Definition at line 27 of file minigames.qc.
References eX, eY, minigame_tile_letter(), and minigame_tile_number().
Referenced by nmm_spawn_tile().
 {
     return eX*(minigame_tile_letter(id)+0.5)/columns +
            eY - eY*(minigame_tile_number(id)+0.5)/rows;
 }
string msle_classname (int id)
Definition at line 112 of file minigames.qc.
References MINIGAME_SIMPLELINKED_ENTITIES, and msle_base_id.
Referenced by NET_HANDLE().
 {
     if ( id == 1 ) return "minigame";
     if ( id == 2 ) return "minigame_player";
     int i = msle_base_id;
 #define MSLE(Name, Fields) i++; if ( id == i ) return #Name;
     MINIGAME_SIMPLELINKED_ENTITIES
 #undef MSLE
     return "";
 }
int msle_id (string class_name)
Definition at line 101 of file minigames.qc.
References MINIGAME_SIMPLELINKED_ENTITIES, and msle_base_id.
Referenced by minigame_SendEntity().
 {
     if ( class_name == "minigame" ) return 1;
     if ( class_name == "minigame_player" ) return 2;
     int i = msle_base_id;
 #define MSLE(Name, Fields) i++; if ( class_name == #Name ) return i;
     MINIGAME_SIMPLELINKED_ENTITIES
 #undef MSLE
     return 0;
 }
entity msle_spawn (entity minigame_session, string class_name)
Definition at line 87 of file minigames.qc.
References entity(), minigame_CheckSend(), minigame_SendEntity(), and spawn().
Referenced by bd_editor_place(), bd_load_piece(), c4_move(), minigame_setup_snake(), pp_move(), pp_setup_pieces(), ps_setup_pieces(), snake_move_body(), snake_new_mouse(), and ttt_move().
 {
     entity e = spawn();
     e.classname = class_name;
     e.owner = minigame_session;
     e.minigame_autoclean = 1;
     #ifdef SVQC
         setcefc(e, minigame_CheckSend);
         Net_LinkEntity(e, false, 0, minigame_SendEntity);
     #endif
     return e;
 }
Variable Documentation
entity descriptor
For minigame sessions: minigame descriptor object.
Definition at line 45 of file minigames.qh.
Referenced by minigame_SendEntity(), and NET_HANDLE().
entity list_next
Definition at line 6 of file minigames.qh.
Referenced by HUD_MinigameMenu_Click_ExpandCollapse().
entity list_prev
Definition at line 4 of file minigames.qh.
const int MINIG_SF_ALL = 0xff
Definition at line 112 of file minigames.qh.
Referenced by bd_load_piece(), c4_move(), minigame_resend(), minigame_setup_snake(), pp_move(), pp_setup_pieces(), ps_move_piece(), ps_setup_pieces(), snake_new_mouse(), and ttt_move().
const int MINIG_SF_CREATE = 0x01
Definition at line 108 of file minigames.qh.
Referenced by minigame_SendEntity(), and NET_HANDLE().
const int MINIG_SF_CUSTOM = 0x10
Definition at line 110 of file minigames.qh.
const int MINIG_SF_MAX = 0x80
Definition at line 111 of file minigames.qh.
const int MINIG_SF_UPDATE = 0x02
Definition at line 109 of file minigames.qh.
Referenced by bd_activate_editor(), bd_check_winner(), bd_close_editor(), bd_do_next_match(), bd_editor_place(), bd_move(), bd_move_dozer(), bd_restart_match(), c4_move(), minigame_SendEntity(), NET_HANDLE(), pp_move(), pp_next_match(), pp_setup_pieces(), ps_move(), ps_setup_pieces(), snake_check_winner(), snake_move(), snake_move_body(), snake_move_head(), snake_new_mouse(), snake_setup_pieces(), ttt_move(), and ttt_next_match().
bool minigame_autoclean
Definition at line 100 of file minigames.qh.
int minigame_flags
Definition at line 103 of file minigames.qh.
Referenced by minigame_SendEntity(), and NET_HANDLE().