Xonotic: XonoticBigCommandButton Class Reference
XonoticBigCommandButton Class Reference
Public Member Functions
virtual void configureButton ()
virtual void configureLabel ()
virtual void configureXonoticBigCommandButton ()
virtual void configureXonoticButton ()
virtual void configureXonoticCommandButton ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void playClickSound ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void setText ()
virtual void showNotify ()
virtual void toString ()
void (entity, entity) onClick
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = SKINALPHA_TEXT
float alpha2 = 1
entity applyButton = NULL
float buttonLeftOfText = 0
float clickTime = 0
vector color = SKINCOLOR_BUTTON_N
vector color2 = '1 1 1'
vector colorC = SKINCOLOR_BUTTON_C
vector colorD = SKINCOLOR_BUTTON_D
vector colorF = SKINCOLOR_BUTTON_F
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
string currentText = string_null
float disabled = 0
float disabledAlpha = SKINALPHA_DISABLED
bool disableOnClick = false
float flags = 0
float focusable = 1
float focused = 0
float fontSize = SKINFONTSIZE_NORMAL
float forcePressed = 0
string grayImage = SKINGFX_BUTTON_BIG_GRAY
string image = SKINGFX_BUTTON_BIG
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
float marginLeft = SKINMARGIN_BUTTON
float marginRight = SKINMARGIN_BUTTON
string onClickCommand = string_null
entity onClickEntity = NULL
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float pressed = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
vector size = '0 0 0'
string src = string_null
string src2 = string_null
float src2scale = 1
float srcMulti = 1
string srcSuffix = string_null
string text = string_null
entity textEntity = NULL
string tooltip = string_null
Detailed Description
Definition at line 4 of file bigcommandbutton.qh.
Member Function Documentation
virtual void Button::configureButton () virtual inherited
virtual void Label::configureLabel () virtual inherited
virtual void XonoticBigCommandButton::configureXonoticBigCommandButton () virtual
virtual void XonoticButton::configureXonoticButton () virtual inherited
virtual void XonoticCommandButton::configureXonoticCommandButton () virtual inherited
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Button::draw () virtual inherited
Reimplemented from Label.
Reimplemented in XonoticSliderCheckBox, XonoticColorButton, CheckBox, and XonoticRadioButton.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
void Item::focusLeave () virtual inherited
Reimplemented in Container, ListBox, XonoticColorpicker, InputContainer, XonoticCharmap, and XonoticInputBox.
Definition at line 99 of file item.qc.
     {}
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void Button::keyDown () virtual inherited
Reimplemented from Item.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void Button::mouseDrag () virtual inherited
Reimplemented from Item.
void Item::mouseMove () virtual inherited
Reimplemented in XonoticServerList, XonoticScreenshotImage, InputBox, Container, ListBox, Nexposee, XonoticPicker, and InputContainer.
Definition at line 72 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void Button::mousePress () virtual inherited
Reimplemented from Item.
virtual void Button::mouseRelease () virtual inherited
Reimplemented from Item.
virtual void Button::playClickSound () virtual inherited
Reimplemented in CheckBox.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Button::resizeNotify () virtual inherited
Reimplemented from Label.
virtual void Label::setText () virtual inherited
Reimplemented in InputBox, and XonoticInputBox.
virtual void Button::showNotify () virtual inherited
Reimplemented from Item.
virtual void Label::toString () virtual inherited
Reimplemented from Item.
Reimplemented in Slider, and CheckBox.
Button::void (entity , entity) inherited
Member Data Documentation
float Label::align = 0.5 inherited
Definition at line 15 of file label.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float Button::allowFocusSound = 1 inherited
Definition at line 25 of file button.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float XonoticButton::alpha = SKINALPHA_TEXT inherited
Definition at line 13 of file button.qh.
float Button::alpha2 = 1 inherited
Definition at line 38 of file button.qh.
entity Button::applyButton = NULL inherited
Definition at line 28 of file button.qh.
float Button::buttonLeftOfText = 0 inherited
Definition at line 23 of file button.qh.
float Button::clickTime = 0 inherited
Definition at line 27 of file button.qh.
vector XonoticButton::color = SKINCOLOR_BUTTON_N inherited
Definition at line 9 of file button.qh.
vector Button::color2 = '1 1 1' inherited
Definition at line 37 of file button.qh.
vector XonoticButton::colorC = SKINCOLOR_BUTTON_C inherited
Definition at line 10 of file button.qh.
vector XonoticButton::colorD = SKINCOLOR_BUTTON_D inherited
Definition at line 12 of file button.qh.
vector XonoticButton::colorF = SKINCOLOR_BUTTON_F inherited
Definition at line 11 of file button.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
string Label::currentText = string_null inherited
Definition at line 13 of file label.qh.
float Button::disabled = 0 inherited
Definition at line 30 of file button.qh.
float XonoticButton::disabledAlpha = SKINALPHA_DISABLED inherited
Definition at line 14 of file button.qh.
bool Button::disableOnClick = false inherited
Definition at line 29 of file button.qh.
float XonoticCommandButton::flags = 0 inherited
Definition at line 7 of file commandbutton.qh.
float Button::focusable = 1 inherited
Definition at line 24 of file button.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
float XonoticButton::fontSize = SKINFONTSIZE_NORMAL inherited
Definition at line 6 of file button.qh.
float Button::forcePressed = 0 inherited
Definition at line 32 of file button.qh.
string XonoticBigCommandButton::grayImage = SKINGFX_BUTTON_BIG_GRAY
Definition at line 7 of file bigcommandbutton.qh.
string XonoticBigCommandButton::image = SKINGFX_BUTTON_BIG
Definition at line 6 of file bigcommandbutton.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
float XonoticButton::marginLeft = SKINMARGIN_BUTTON inherited
Definition at line 15 of file button.qh.
float XonoticButton::marginRight = SKINMARGIN_BUTTON inherited
Definition at line 16 of file button.qh.
string XonoticCommandButton::onClickCommand = string_null inherited
Definition at line 6 of file commandbutton.qh.
entity Button::onClickEntity = NULL inherited
Definition at line 17 of file button.qh.
vector Button::origin = '0 0 0' inherited
Definition at line 40 of file button.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float Button::pressed = 0 inherited
Definition at line 26 of file button.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
vector Button::size = '0 0 0' inherited
Definition at line 41 of file button.qh.
string Button::src = string_null inherited
Definition at line 18 of file button.qh.
string Button::src2 = string_null inherited
Definition at line 20 of file button.qh.
float Button::src2scale = 1 inherited
Definition at line 21 of file button.qh.
float Button::srcMulti = 1 inherited
Definition at line 22 of file button.qh.
string Button::srcSuffix = string_null inherited
Definition at line 19 of file button.qh.
string Label::text = string_null inherited
Definition at line 12 of file label.qh.
entity Label::textEntity = NULL inherited
Definition at line 28 of file label.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
The documentation for this class was generated from the following file:
menu/xonotic/bigcommandbutton.qh