Xonotic: server/sv_main.qh File Reference
sv_main.qh File Reference
Functions
bool expr_evaluate (string s)
Evaluate an expression of the form: [+ | -]? [var[op]val | [op]var | val | var] ...
void main ()
Function Documentation
bool expr_evaluate (string s)
Evaluate an expression of the form: [+ | -]? [var[op]val | [op]var | val | var] ...
+: all must match. this is the default -: one must NOT match
var>x var<x var>="">=x var<=x var==x var!=x var===x var!==x
Definition at line 266 of file sv_main.qc.
References argv(), BINOP, cvar(), cvar_string(), ftos(), stof(), str2chr, substring(), tokenize_console, v, and X.
Referenced by SV_OnEntityPreSpawnFunction().
 {
     bool ret = false;
     if (str2chr(s, 0) == '+') {
         s = substring(s, 1, -1);
     } else if (str2chr(s, 0) == '-') {
         ret = true;
         s = substring(s, 1, -1);
     }
     bool expr_fail = false;
     for (int i = 0, n = tokenize_console(s); i < n; ++i) {
         int o;
         string k, v;
         s = argv(i);
         #define X(expr) \
             if (expr) { \
                 continue; \
             } else { \
                 expr_fail = true; \
                 break; \
             }
         #define BINOP(op, len, expr) \
             if ((o = strstrofs(s, op, 0)) >= 0) { \
                 k = substring(s, 0, o); \
                 v = substring(s, o + len, -1); \
                 X(expr); \
             }
         BINOP(">=", 2, cvar(k) >= stof(v));
         BINOP("<=", 2, cvar(k) <= stof(v));
         BINOP(">",  1, cvar(k) >  stof(v));
         BINOP("<",  1, cvar(k) <  stof(v));
         BINOP("==", 2, cvar(k) == stof(v));
         BINOP("!=", 2, cvar(k) != stof(v));
         BINOP("===", 3, cvar_string(k) == v);
         BINOP("!==", 3, cvar_string(k) != v);
         {
             k = s;
             bool b = true;
             if (str2chr(k, 0) == '!') {
                 k = substring(s, 1, -1);
                 b = false;
             }
             float f = stof(k);
             bool isnum = ftos(f) == k;
             X(boolean(isnum ? f : cvar(k)) == b);
         }
         #undef BINOP
         #undef X
     }
     if (!expr_fail) {
         ret = !ret;
     }
     // now ret is true if we want to keep the item, and false if we want to get rid of it
     return ret;
 }
void main ()
Definition at line 395 of file sv_main.qc.
 {
 }