Xonotic: Bumblebee Class Reference
Bumblebee Class Reference
Public Member Functions
ATTRIB (Vehicle, m_icon, string)
hud icon
ATTRIB (Vehicle, tag_head, string)
tur_head model tag
ATTRIB (Vehicle, tag_hud, string)
hud model tag
ATTRIB (Vehicle, tag_view, string)
cockpit model tag
ATTRIB (Vehicle, PlayerPhysplug, bool(entity, float))
player physics mod
virtual void vr_crosshair ()
(CLIENT) logic to run every frame
virtual void vr_death ()
(SERVER) called when vehicle dies
virtual void vr_enter ()
(SERVER) called when a player enters this vehicle
virtual void vr_gunner_enter ()
(SERVER) called when a player enters this vehicle while occupied
virtual void vr_hud ()
(CLIENT) logic to run every frame
virtual void vr_impact ()
(SERVER) called when a vehicle hits something
virtual void vr_precache ()
(BOTH) precaches models/sounds used by this vehicle
virtual void vr_setcolors ()
(SERVER) called when a vehicle's colors are being reset, so modules can be updated
virtual void vr_setup ()
(BOTH) setup vehicle data
virtual void vr_spawn ()
(SERVER) called when the vehicle re-spawns
virtual void vr_think ()
(SERVER) logic to run every frame
Public Attributes
string head_model = ""
float height = 450
string hud_model = "models/vehicles/spiderbot_cockpit.dpm"
string m_icon = "vehicle_bumble"
vector m_maxs = '230 130 130'
vector m_mins = '-245 -130 -130'
string mdl = "models/vehicles/bumblebee_body.dpm"
string model = "models/vehicles/bumblebee_body.dpm"
string netname = "bumblebee"
int spawnflags = VHF_DMGSHAKE
string tag_head = ""
string tag_hud = ""
string tag_view = "tag_viewport"
string vehicle_name = _("Bumblebee")
int vehicleid = 0
vector view_ofs = '0 0 300'
Detailed Description
Definition at line 5 of file bumblebee.qh.
Member Function Documentation
Vehicle::ATTRIB (Vehicle , m_icon , string) inherited
hud icon
Vehicle::ATTRIB (Vehicle , tag_head , string) inherited
tur_head model tag
Vehicle::ATTRIB (Vehicle , tag_hud , string) inherited
hud model tag
Vehicle::ATTRIB (Vehicle , tag_view , string) inherited
cockpit model tag
Vehicle::ATTRIB (Vehicle , PlayerPhysplug , bool(entity, float)) inherited
player physics mod
virtual void Vehicle::vr_crosshair () inline virtual inherited
(CLIENT) logic to run every frame
Definition at line 59 of file vehicle.qh.
References ENDCLASS.
Referenced by HUD_Crosshair_Vehicle().
 { }
virtual void Vehicle::vr_death () inline virtual inherited
(SERVER) called when vehicle dies
Definition at line 43 of file vehicle.qh.
Referenced by vehicles_damage().
 { }
virtual void Vehicle::vr_enter () inline virtual inherited
(SERVER) called when a player enters this vehicle
Definition at line 47 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_gunner_enter () inline virtual inherited
(SERVER) called when a player enters this vehicle while occupied
Definition at line 49 of file vehicle.qh.
Referenced by vehicles_enter().
 { }
virtual void Vehicle::vr_hud () inline virtual inherited
(CLIENT) logic to run every frame
Definition at line 57 of file vehicle.qh.
Referenced by HUD_Vehicle().
 { }
virtual void Vehicle::vr_impact () inline virtual inherited
(SERVER) called when a vehicle hits something
Definition at line 53 of file vehicle.qh.
Referenced by vehicles_touch().
 { }
virtual void Vehicle::vr_precache () inline virtual inherited
(BOTH) precaches models/sounds used by this vehicle
Definition at line 45 of file vehicle.qh.
Referenced by vehicle_initialize().
 { }
virtual void Vehicle::vr_setcolors () inline virtual inherited
(SERVER) called when a vehicle's colors are being reset, so modules can be updated
Definition at line 55 of file vehicle.qh.
Referenced by vehicles_reset_colors().
 { }
virtual void Vehicle::vr_setup () inline virtual inherited
(BOTH) setup vehicle data
Definition at line 39 of file vehicle.qh.
Referenced by NET_HANDLE(), and vehicle_initialize().
 { }
virtual void Vehicle::vr_spawn () inline virtual inherited
(SERVER) called when the vehicle re-spawns
Definition at line 51 of file vehicle.qh.
 { }
virtual void Vehicle::vr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 41 of file vehicle.qh.
Referenced by vehicles_think().
 { }
Member Data Documentation
string Bumblebee::head_model = ""
Definition at line 13 of file bumblebee.qh.
float Bumblebee::height = 450
Definition at line 10 of file bumblebee.qh.
string Bumblebee::hud_model = "models/vehicles/spiderbot_cockpit.dpm"
Definition at line 14 of file bumblebee.qh.
string Bumblebee::m_icon = "vehicle_bumble"
Definition at line 20 of file bumblebee.qh.
vector Bumblebee::m_maxs = '230 130 130'
Definition at line 8 of file bumblebee.qh.
vector Bumblebee::m_mins = '-245 -130 -130'
Definition at line 7 of file bumblebee.qh.
string Bumblebee::mdl = "models/vehicles/bumblebee_body.dpm"
Definition at line 11 of file bumblebee.qh.
string Bumblebee::model = "models/vehicles/bumblebee_body.dpm"
Definition at line 12 of file bumblebee.qh.
string Bumblebee::netname = "bumblebee"
Definition at line 18 of file bumblebee.qh.
int Bumblebee::spawnflags = VHF_DMGSHAKE
Definition at line 6 of file bumblebee.qh.
string Bumblebee::tag_head = ""
Definition at line 15 of file bumblebee.qh.
string Bumblebee::tag_hud = ""
Definition at line 16 of file bumblebee.qh.
string Bumblebee::tag_view = "tag_viewport"
Definition at line 17 of file bumblebee.qh.
string Bumblebee::vehicle_name = _("Bumblebee")
Definition at line 19 of file bumblebee.qh.
int Vehicle::vehicleid = 0 inherited
Definition at line 4 of file vehicle.qh.
Referenced by vehicle_initialize().
vector Bumblebee::view_ofs = '0 0 300'
Definition at line 9 of file bumblebee.qh.
The documentation for this class was generated from the following file:
common/vehicles/vehicle/bumblebee.qh