Xonotic: common/gamemodes/gamemode/clanarena/cl_clanarena.qh File Reference
cl_clanarena.qh File Reference
Functions
void HUD_Mod_CA (vector myPos, vector mySize)
void HUD_Mod_CA_Draw (vector myPos, vector mySize, int layout)
void HUD_Mod_CA_Export (int fh)
Function Documentation
void HUD_Mod_CA (vector myPos, vector mySize)
Definition at line 74 of file cl_clanarena.qc.
References autocvar_hud_panel_modicons_ca_layout, HUD_Mod_CA_Draw(), and mod_active.
Referenced by ClanArena::m_configuremenu().
 {
     mod_active = 1; // required in each mod function that always shows something
     HUD_Mod_CA_Draw(myPos, mySize, autocvar_hud_panel_modicons_ca_layout);
 }
void HUD_Mod_CA_Draw (vector myPos, vector mySize, int layout)
Definition at line 45 of file cl_clanarena.qc.
References ceil(), DrawCAItem(), HUD_GetRowCount(), team_count, vec2, and vector().
Referenced by HUD_Mod_CA(), and HUD_Mod_FreezeTag().
 {
     int rows, columns;
     float aspect_ratio;
     aspect_ratio = (layout) ? 2 : 1;
     rows = HUD_GetRowCount(team_count, mySize, aspect_ratio);
     columns = ceil(team_count/rows);
     int i;
     float row = 0, column = 0;
     vector pos = '0 0 0', itemSize;
     itemSize = vec2(mySize.x / columns, mySize.y / rows);
     for(i=0; i<team_count; ++i)
     {
         pos.x = myPos.x + column * itemSize.x;
         pos.y = myPos.y + row * itemSize.y;
         DrawCAItem(pos, itemSize, aspect_ratio, layout, i);
         ++row;
         if(row >= rows)
         {
             row = 0;
             ++column;
         }
     }
 }
void HUD_Mod_CA_Export (int fh)
Definition at line 3 of file cl_clanarena.qc.
References HUD_Write_Cvar.
Referenced by ClanArena::m_configuremenu().
 {
     HUD_Write_Cvar("hud_panel_modicons_ca_layout");
 }