Xonotic: server/command/banning.qc File Reference
banning.qc File Reference
#include "banning.qh"
#include <common/command/_mod.qh>
#include <common/state.qh>
#include <common/stats.qh>
#include <common/util.qh>
#include <common/weapons/_all.qh>
#include <server/command/common.qh>
#include <server/ipban.qh>
#include <server/player.qh>
Macros
#define BAN_COMMAND(name, function, description) { if (strtolower(description) != "") { LOG_INFO(" ^2", name, "^7: ", description); } }
#define BAN_COMMAND(name, function, description) { if (name == strtolower(argv(0))) { function; return true; } }
#define BAN_COMMAND(name, function, description) { if (name == strtolower(argv(1))) { function; return true; } }
#define BAN_COMMAND(name, function, description) { if (strtolower(description) != "") { CMD_Write_Alias("qc_cmd_sv", name, description); } }
#define BAN_COMMANDS(request, arguments, command)
Functions
float BanCommand (string command)
void BanCommand_ban (int request, int argc, string command)
void BanCommand_banlist (int request)
void BanCommand_kickban (int request, int argc, string command)
float BanCommand_macro_command (int argc, string command)
void BanCommand_macro_help ()
float BanCommand_macro_usage (int argc)
void BanCommand_macro_write_aliases (float fh)
void BanCommand_mute (int request, int argc, string command)
void BanCommand_unban (int request, int argc)
void BanCommand_unmute (int request, int argc)
Macro Definition Documentation
#define BAN_COMMAND (name, function, description) { if (strtolower(description) != "") { LOG_INFO(" ^2", name, "^7: ", description); } }
#define BAN_COMMAND (name, function, description) { if (name == strtolower(argv(0))) { function; return true; } }
#define BAN_COMMAND (name, function, description) { if (name == strtolower(argv(1))) { function; return true; } }
#define BAN_COMMAND (name, function, description) { if (strtolower(description) != "") { CMD_Write_Alias("qc_cmd_sv", name, description); } }
#define BAN_COMMANDS (request, arguments, command)
Value:
BAN_COMMAND("ban", BanCommand_ban(request, arguments, command), "Ban an IP address or a range of addresses (like 1.2.3)") \
    BAN_COMMAND("banlist", BanCommand_banlist(request), "List all existing bans") \
    BAN_COMMAND("kickban", BanCommand_kickban(request, arguments, command), "Disconnect a client and ban it at the same time") \
    BAN_COMMAND("mute", BanCommand_mute(request, arguments, command), "Disallow a client from talking by muting them") \
    BAN_COMMAND("unban", BanCommand_unban(request, arguments), "Remove an existing ban") \
    BAN_COMMAND("unmute", BanCommand_unmute(request, arguments), "Unmute a client") \
    /* nothing */
Definition at line 267 of file banning.qc.
Referenced by BanCommand_macro_command(), BanCommand_macro_help(), BanCommand_macro_usage(), and BanCommand_macro_write_aliases().
Function Documentation
float BanCommand (string command)
Definition at line 316 of file banning.qc.
References BanCommand_macro_command(), and tokenize_console.
Referenced by GameCommand().
 {
     int argc = tokenize_console(command);
     // Guide for working with argc arguments by example:
     // argc:   1    - 2      - 3     - 4
     // argv:   0    - 1      - 2     - 3
     // cmd     vote - master - login - password
     if (BanCommand_macro_command(argc, command)) // continue as usual and scan for normal commands
         return true;                             // handled by one of the above GenericCommand_* functions
     return false;
 }
void BanCommand_ban (int request, int argc, string command)
Definition at line 18 of file banning.qc.
References argv(), autocvar_g_ban_default_bantime, Ban_Insert(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GET_BAN_ARG, GET_BAN_REASON, LOG_HELP, and LOG_INFOF.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argc >= 2)
             {
                 string ip = argv(1);
                 float reason_arg, bantime;
                 string reason;
                 reason_arg = 2;
                 GET_BAN_ARG(bantime, autocvar_g_ban_default_bantime);
                 GET_BAN_REASON(reason, "No reason provided");
                 Ban_Insert(ip, bantime, reason, 1);
                 return;
             }
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd ban address [bantime] [reason]");
             LOG_HELP("  'address' is the IP address or range of the player to ban,");
             LOG_HELP("  'bantime' is the amount of time that the ban is active (default if not provided),");
             LOG_HELP("  and 'reason' is the string to label the ban with as reason for banning.");
             LOG_HELP("See also: ^2banlist, kickban, unban^7");
             return;
         }
     }
 }
void BanCommand_banlist (int request)
Definition at line 54 of file banning.qc.
References Ban_View(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, and LOG_HELP.
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             Ban_View();
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd banlist");
             LOG_HELP("  No arguments required.");
             LOG_HELP("See also: ^2ban, kickban, unban^7");
             return;
         }
     }
 }
void BanCommand_kickban (int request, int argc, string command)
Definition at line 75 of file banning.qc.
References argv(), autocvar_g_ban_default_bantime, autocvar_g_ban_default_masksize, Ban_KickBanClient(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, entity(), GET_BAN_ARG, GET_BAN_REASON, GetClientErrorString, GetIndexedEntity(), LOG_HELP, LOG_INFO, LOG_INFOF, next_token, and VerifyKickableEntity().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argc >= 2)
             {
                 entity client = GetIndexedEntity(argc, 1);
                 float accepted = VerifyKickableEntity(client);
                 float reason_arg, bantime, masksize;
                 string reason;
                 if (accepted > 0)
                 {
                     reason_arg = next_token;
                     GET_BAN_ARG(bantime, autocvar_g_ban_default_bantime);
                     GET_BAN_ARG(masksize, autocvar_g_ban_default_masksize);
                     GET_BAN_REASON(reason, "No reason provided");
                     Ban_KickBanClient(client, bantime, masksize, reason);
                     return;
                 }
                 else
                 {
                     LOG_INFO("kickban: ", GetClientErrorString(accepted, argv(1)), ".");
                 }
             }
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd kickban client [bantime] [masksize] [reason]");
             LOG_HELP("  'client' is the entity number or name of the player to ban,");
             LOG_HELP("  'bantime' is the amount of time that the ban is active (default if not provided),");
             LOG_HELP("  'masksize' is the range of the IP address (1-thru-4, default if not provided),");
             LOG_HELP("  and 'reason' is the string to label the ban with as reason for banning.");
             LOG_HELP("See also: ^2ban, banlist, unban^7");
             return;
         }
     }
 }
float BanCommand_macro_command (int argc, string command)
Definition at line 285 of file banning.qc.
References BAN_COMMANDS, and CMD_REQUEST_COMMAND.
Referenced by BanCommand().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (name == strtolower(argv(0))) { function; return true; } }
     BAN_COMMANDS(CMD_REQUEST_COMMAND, argc, command);
 #undef BAN_COMMAND
     return false;
 }
void BanCommand_macro_help ()
Definition at line 276 of file banning.qc.
References BAN_COMMANDS.
Referenced by GameCommand().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (strtolower(description) != "") { LOG_INFO("  ^2", name, "^7: ", description); } }
     BAN_COMMANDS(0, 0, "");
 #undef BAN_COMMAND
 }
float BanCommand_macro_usage (int argc)
Definition at line 296 of file banning.qc.
References BAN_COMMANDS, and CMD_REQUEST_USAGE.
Referenced by GameCommand().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (name == strtolower(argv(1))) { function; return true; } }
     BAN_COMMANDS(CMD_REQUEST_USAGE, argc, "");
 #undef BAN_COMMAND
     return false;
 }
void BanCommand_macro_write_aliases (float fh)
Definition at line 307 of file banning.qc.
References BAN_COMMANDS.
Referenced by GENERIC_COMMAND().
 {
     #define BAN_COMMAND(name, function, description) \
         { if (strtolower(description) != "") { CMD_Write_Alias("qc_cmd_sv", name, description); } }
     BAN_COMMANDS(0, 0, "");
 #undef BAN_COMMAND
 }
void BanCommand_mute (int request, int argc, string command)
Definition at line 122 of file banning.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, CS(), entity(), GetClientErrorString, GetFilteredEntity(), LOG_HELP, LOG_INFO, LOG_INFOF, and VerifyClientEntity().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argc >= 2)
             {
                 entity client = GetFilteredEntity(argv(1));
                 float accepted = VerifyClientEntity(client, true, false);
                 if (accepted > 0)
                 {
                     CS(client).muted = true;
                     return;
                 }
                 else
                 {
                     LOG_INFO("mute: ", GetClientErrorString(accepted, argv(1)), ".");
                 }
             }
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd mute client");
             LOG_HELP("  'client' is the entity number or name of the player to mute.");
             LOG_HELP("See also: ^2unmute^7");
             return;
         }
     }
 }
void BanCommand_unban (int request, int argc)
Definition at line 157 of file banning.qc.
References argv(), Ban_Delete(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, LOG_HELP, stof(), and substring().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argv(1))
             {
                 float tmp_number = -1;
                 string tmp_string;
                 if (substring(argv(1), 0, 1) == "#")
                 {
                     tmp_string = substring(argv(1), 1, -1);
                     if (tmp_string != "") // is it all one token? like #1
                         tmp_number = stof(tmp_string);
                     else if (argc > 2)    // no, it's two tokens? # 1
                         tmp_number = stof(argv(2));
                     else tmp_number = -1;
                 }
                 else  // maybe it's ONLY a number?
                 {
                     tmp_number = stof(argv(1));
                     if ((tmp_number == 0) && (argv(1) != "0")) tmp_number = -1; }
                 if (tmp_number >= 0)
                 {
                     Ban_Delete(tmp_number);
                     return;
                 }
             }
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd unban banid");
             LOG_HELP("  Where 'banid' is the ID of the ban of which to remove.");
             LOG_HELP("See also: ^2ban, banlist, kickban^7");
             return;
         }
     }
 }
void BanCommand_unmute (int request, int argc)
Definition at line 203 of file banning.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, CS(), entity(), GetClientErrorString, GetFilteredEntity(), LOG_HELP, LOG_INFO, LOG_INFOF, and VerifyClientEntity().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (argc >= 2)
             {
                 entity client = GetFilteredEntity(argv(1));
                 float accepted = VerifyClientEntity(client, true, false);
                 if (accepted > 0)
                 {
                     CS(client).muted = false;
                     return;
                 }
                 else
                 {
                     LOG_INFO("unmute: ", GetClientErrorString(accepted, argv(1)), ".");
                 }
             }
         }
         default:
             LOG_INFOF("Incorrect parameters for ^2%s^7", argv(0));
         case CMD_REQUEST_USAGE:
         {
             LOG_HELP("Usage:^3 sv_cmd unmute client");
             LOG_HELP("  'client' is the entity number or name of the player to unmute.");
             LOG_HELP("See also: ^2mute^7");
             return;
         }
     }
 }