Xonotic: client/hud/panel/engineinfo.qc File Reference
engineinfo.qc File Reference
#include "engineinfo.qh"
#include <client/autocvars.qh>
#include <client/miscfunctions.qh>
Functions
void HUD_EngineInfo ()
Variables
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_instantupdate_change_threshold
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_new_weight
int framecounter
float frametimeavg
float frametimeavg1
float frametimeavg2
float prevfps
float prevfps_time
Function Documentation
void HUD_EngineInfo ()
Definition at line 18 of file engineinfo.qc.
References autocvar__hud_configure, autocvar_hud_panel_engineinfo, autocvar_hud_panel_engineinfo_dynamichud, autocvar_hud_panel_engineinfo_framecounter_decimals, autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage, autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_instantupdate_change_threshold, autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_new_weight, autocvar_hud_panel_engineinfo_framecounter_time, color, DRAWFLAG_NORMAL, drawstring_aspect(), fabs(), framecounter, frametimeavg, frametimeavg1, frametimeavg2, gettime(), GETTIME_REALTIME, HUD_Get_Num_Color(), HUD_Panel_DrawBg, HUD_Panel_LoadCvars(), HUD_Scale_Disable(), HUD_Scale_Enable(), panel_bg_padding, panel_fg_alpha, panel_pos, panel_size, prevfps, prevfps_time, and vector().
 {
     if(!autocvar__hud_configure)
     {
         if(!autocvar_hud_panel_engineinfo) return;
     }
     HUD_Panel_LoadCvars();
     vector pos, mySize;
     pos = panel_pos;
     mySize = panel_size;
     if (autocvar_hud_panel_engineinfo_dynamichud)
         HUD_Scale_Enable();
     else
         HUD_Scale_Disable();
     HUD_Panel_DrawBg();
     if(panel_bg_padding)
     {
         pos += '1 1 0' * panel_bg_padding;
         mySize -= '2 2 0' * panel_bg_padding;
     }
     float currentTime = gettime(GETTIME_REALTIME);
     if(autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage)
     {
         float currentframetime = currentTime - prevfps_time;
         frametimeavg = (frametimeavg + frametimeavg1 + frametimeavg2 + currentframetime)/4; // average three frametimes into framecounter for slightly more stable fps readings :P
         frametimeavg2 = frametimeavg1;
         frametimeavg1 = frametimeavg;
         float weight;
         weight = autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_new_weight;
         if(currentframetime > 0.0001) // filter out insane values which sometimes seem to occur and throw off the average? If you are getting 10,000 fps or more, then you don't need a framerate counter.
         {
             if(fabs(prevfps - (1/frametimeavg)) > prevfps * autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_instantupdate_change_threshold) // if there was a big jump in fps, just force prevfps at current (1/currentframetime) to make big updates instant
                 prevfps = (1/currentframetime);
             prevfps = (1 - weight) * prevfps + weight * (1/frametimeavg); // framecounter just used so there's no need for a new variable, think of it as "frametime average"
         }
         prevfps_time = currentTime;
     }
     else
     {
         framecounter += 1;
         if(currentTime - prevfps_time > autocvar_hud_panel_engineinfo_framecounter_time)
         {
             prevfps = framecounter/(currentTime - prevfps_time);
             framecounter = 0;
             prevfps_time = currentTime;
         }
     }
     vector color;
     color = HUD_Get_Num_Color (prevfps, 100);
     drawstring_aspect(pos, sprintf(_("FPS: %.*f"), autocvar_hud_panel_engineinfo_framecounter_decimals, prevfps), mySize, color, panel_fg_alpha, DRAWFLAG_NORMAL);
 }
Variable Documentation
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage
Definition at line 15 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_instantupdate_change_threshold
Definition at line 17 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float autocvar_hud_panel_engineinfo_framecounter_exponentialmovingaverage_new_weight
Definition at line 16 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
int framecounter
Definition at line 10 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float frametimeavg
Definition at line 12 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float frametimeavg1
Definition at line 13 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float frametimeavg2
Definition at line 14 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float prevfps
Definition at line 8 of file engineinfo.qc.
Referenced by HUD_EngineInfo().
float prevfps_time
Definition at line 9 of file engineinfo.qc.
Referenced by HUD_EngineInfo().