Xonotic: common/physics/movetypes/step.qc File Reference
step.qc File Reference
Functions
void _Movetype_Physics_Step (entity this, float dt)
Function Documentation
void _Movetype_Physics_Step (entity this, float dt)
Definition at line 1 of file step.qc.
References _Movetype_CheckVelocity(), _Movetype_CheckWaterTransition(), _Movetype_FlyMove(), _Movetype_LinkEdict(), FL_ONGROUND, move_flags, and UPWARD_VELOCITY_CLEARS_ONGROUND.
Referenced by _Movetype_Physics_ClientFrame(), and _Movetype_Physics_Frame().
 {
     if(this.move_flags & FL_ONGROUND)
     {
         if(this.velocity_z >= (1.0 / 32.0) && UPWARD_VELOCITY_CLEARS_ONGROUND(this))
         {
             this.move_flags &= ~FL_ONGROUND;
             _Movetype_CheckVelocity(this);
             _Movetype_FlyMove(this, dt, true, '0 0 0', 0);
             _Movetype_LinkEdict(this, true);
         }
     }
     else
     {
         _Movetype_CheckVelocity(this);
         _Movetype_FlyMove(this, dt, true, '0 0 0', 0);
         _Movetype_LinkEdict(this, true);
         // TODO? movetypesteplandevent
     }
     _Movetype_CheckWaterTransition(this);
 }