Xonotic: common/triggers/trigger/keylock.qc File Reference
common/triggers/trigger/keylock.qc File Reference
Functions
void trigger_keylock_trigger (string s)
trigger given targets
void trigger_keylock_kill (string s)
kill killtarget of trigger keylock.
void trigger_keylock_touch ()
Function Documentation
void trigger_keylock_kill (string s)
kill killtarget of trigger keylock.
Definition at line 27 of file keylock.qc.
References entity(), find(), targetname, and world.
Referenced by trigger_keylock_touch().
{
    entity t;
    for(t = world; (t = find(t, targetname, s)); )
        remove(t);
}
void trigger_keylock_touch ()
Definition at line 34 of file keylock.qc.
References activator, CENTER_DOOR_LOCKED_ALSONEED, centerprint(), delay, IS_PLAYER, item_keys_keylist(), item_keys_usekey(), itemkeys, killtarget, message, MSG_CENTER, noise, noise1, noise2, other, play2(), SELFPARAM, target, target2, time, trigger_keylock_kill(), and trigger_keylock_trigger().
{SELFPARAM();
    bool key_used = false;
    bool started_delay = false;
    // only player may trigger the lock
    if(!IS_PLAYER(other))
        return;
    // check silver key
    if(self.itemkeys)
        key_used = item_keys_usekey(self, other);
    activator = other;
    if(self.itemkeys)
    {
#ifdef SVQC
        // at least one of the keys is missing
        if(key_used)
        {
            // one or more keys were given, but others are still missing!
            play2(other, self.noise1);
            Send_Notification(NOTIF_ONE, other, MSG_CENTER, CENTER_DOOR_LOCKED_ALSONEED, item_keys_keylist(self.itemkeys));
            other.key_door_messagetime = time + 2;
        }
        else if(other.key_door_messagetime <= time)
        {
            // no keys were given
            play2(other, self.noise2);
            Send_Notification(NOTIF_ONE, other, MSG_CENTER, CENTER_DOOR_LOCKED_NEED, item_keys_keylist(self.itemkeys));
            other.key_door_messagetime = time + 2;
        }
#endif
        // trigger target2
        if(self.delay <= time || started_delay == true)
        if(self.target2)
        {
            trigger_keylock_trigger(self.target2);
            started_delay = true;
            self.delay = time + self.wait;
        }
    }
    else
    {
#ifdef SVQC
        // all keys were given!
        play2(other, self.noise);
        centerprint(other, self.message);
#endif
        if(self.target)
            trigger_keylock_trigger(self.target);
        if(self.killtarget)
            trigger_keylock_kill(self.killtarget);
        remove(self);
    }
}
void trigger_keylock_trigger (string s)
trigger given targets
Definition at line 4 of file keylock.qc.
References activator, entity(), find(), other, SELFPARAM, setself, targetname, and world.
Referenced by trigger_keylock_touch().
{SELFPARAM();
    entity otemp = other;
    entity atemp = activator;
    entity t;
    for(t = world; (t = find(t, targetname, s)); )
        if(t.use)
        {
            setself(t);
            other = this;
            activator = atemp;
            self.use();
        }
    setself(this);
    other = otemp;
    activator = atemp;
}