Xonotic: server/campaign.qh File Reference
campaign.qh File Reference
Macros
#define CAMPAIGN_MAX_ENTRIES 2
Functions
int Campaign_GetLevelNum ()
string Campaign_GetMessage ()
void CampaignLevelWarp (float n)
void CampaignPostInit ()
void CampaignPostIntermission ()
void CampaignPreInit ()
void CampaignPreIntermission ()
Variables
bool campaign_bots_may_start
campaign mode: bots shall spawn but wait for the player to spawn before they do anything in other game modes, this is ignored
bool campaign_forcewin
Macro Definition Documentation
#define CAMPAIGN_MAX_ENTRIES 2
Definition at line 4 of file campaign.qh.
Function Documentation
int Campaign_GetLevelNum ()
Definition at line 78 of file campaign.qc.
References campaign_level.
Referenced by PrintWelcomeMessage().
 {
     return campaign_level + 1;
 }
string Campaign_GetMessage ()
Definition at line 83 of file campaign.qc.
References campaign_longdesc, campaign_shortdesc, and strcat().
Referenced by PrintWelcomeMessage().
 {
     return strcat(campaign_shortdesc[0], "\n^3\n", campaign_longdesc[0]);
 }
void CampaignLevelWarp (float n)
Definition at line 323 of file campaign.qc.
References campaign_entries, campaign_level, CampaignFile_Load(), CampaignFile_Unload(), CampaignSetup(), and error.
Referenced by GameCommand_warp().
 {
     if(n < 0)
         n = campaign_level + 1;
     CampaignFile_Unload();
     CampaignFile_Load(n, 1);
     if(campaign_entries)
         CampaignSetup(0);
     else
         error("Sorry, cheater. You are NOT WELCOME.");
     CampaignFile_Unload();
 }
void CampaignPostInit ()
Definition at line 156 of file campaign.qc.
References argv(), autocvar__campaign_testrun, campaign_fraglimit, Campaign_Invalid(), campaign_timelimit, cvar_set(), cvar_set_normal, and tokenizebyseparator.
Referenced by spawnfunc().
 {
     // now some sanity checks
     if(Campaign_Invalid())
         return;
     if(autocvar__campaign_testrun)
     {
         cvar_set("fraglimit", "0");
         cvar_set("leadlimit", "0");
         cvar_set("timelimit", "0.01");
         cvar_set_normal("fraglimit", "0");
         cvar_set_normal("leadlimit", "0");
         cvar_set_normal("timelimit", "0.01");
     }
     else
     {
         // "default" uses implicit values, "" or "0" means no limit
         tokenizebyseparator(campaign_fraglimit[0], "+");
         if(argv(0) != "default") {
             cvar_set("fraglimit", argv(0));
             cvar_set_normal("fraglimit", argv(0));
         }
         if(argv(1) != "default") {
             cvar_set("leadlimit", argv(1));
             cvar_set_normal("leadlimit", argv(1));
         }
         if(campaign_timelimit[0] != "default") {
             cvar_set("timelimit", campaign_timelimit[0]);
             cvar_set_normal("timelimit", campaign_timelimit[0]);
         }
     }
 }
void CampaignPostIntermission ()
Definition at line 301 of file campaign.qc.
References campaign_entries, campaign_index_var, campaign_name, campaign_won, CampaignFile_Unload(), CampaignSetup(), localcmd, LOG_DEBUG, and strunzone().
Referenced by DoNextMapOverride().
 {
     // NOTE: campaign_won is 0 or 1, that is, points to the next level
     if(campaign_won && campaign_entries < 2)
     {
         // last map won!
         LOG_DEBUG("^2test run: campaign looks GOOD");
         localcmd("togglemenu 1\n");
         CampaignFile_Unload();
         return;
     }
     CampaignSetup(campaign_won);
     CampaignFile_Unload();
     strunzone(campaign_index_var);
     strunzone(campaign_name);
     campaign_name = "";
 }
void CampaignPreInit ()
Definition at line 88 of file campaign.qc.
References _MapInfo_Parse_Settemp(), argv(), autocvar__campaign_index, autocvar__campaign_name, autocvar_g_campaign_skill, autocvar_sv_cheats, autocvar_sv_gravity, campaign_bots, campaign_botskill, campaign_entries, campaign_forcewin, campaign_gametype, campaign_index_var, Campaign_Invalid(), campaign_level, campaign_mutators, campaign_name, CampaignBailout(), CampaignFile_Load(), CampaignFile_Unload(), cvar(), cvar_set(), cvar_set_normal, cvar_settemp(), cvar_string(), ftos(), MAPINFO_SETTEMP_ACL_USER, MapInfo_SwitchGameType(), MapInfo_Type_FromString(), mapname, max(), strcat(), strzone(), and tokenizebyseparator.
Referenced by spawnfunc().
 {
     float baseskill;
     campaign_level = autocvar__campaign_index;
     campaign_name = strzone(autocvar__campaign_name);
     campaign_index_var = strzone(strcat("g_campaign", campaign_name, "_index"));
     CampaignFile_Load(campaign_level, 2);
     if(campaign_entries < 1)
     {
         CampaignBailout("unknown map");
         return;
     }
     if(autocvar_sv_cheats)
     {
         MapInfo_SwitchGameType(MapInfo_Type_FromString(campaign_gametype[0]));
         CampaignFile_Unload();
         CampaignBailout("JOLLY CHEATS AHAHAHAHAHAHAH))");
         return;
     }
     baseskill = max(0, autocvar_g_campaign_skill + campaign_botskill[0]);
     campaign_forcewin = false;
     cvar_set("sv_public", "0");
     cvar_set("pausable", "1");
 #if 0
     cvar_campaignwrapper_list = strzone(strcat("; ", campaign_mutators[0], "; "));
 #else
     string cvar_campaignwrapper_list = strcat("; ", campaign_mutators[0], "; ");
     int argc = tokenizebyseparator(cvar_campaignwrapper_list, "; ");
     if(argc > 0)
     {
         for(int j = 0; j < argc; ++j)
         {
             string arg = argv(j);
             if(arg == "") continue;
             _MapInfo_Parse_Settemp(mapname, MAPINFO_SETTEMP_ACL_USER, 0, arg, 0); // no recursion!
         }
     }
 #endif
 #if 0
     cvar = cvar_campaignwrapper;
     cvar_string = cvar_string_campaignwrapper;
     cvar_set = cvar_set_campaignwrapper;
     cvar_set("g_campaign", "1");
     cvar_set("g_dm", "0");
     cvar_set("skill", ftos(baseskill));
     cvar_set("bot_number", ftos(campaign_bots[0]));
 #else
     cvar_settemp("g_campaign", "1");
     cvar_settemp("g_dm", "0");
     cvar_settemp("skill", ftos(baseskill));
     cvar_settemp("bot_number", ftos(campaign_bots[0]));
 #endif
     MapInfo_SwitchGameType(MapInfo_Type_FromString(campaign_gametype[0]));
     // copy sv_gravity cvar, as the engine needs it too (sorry, this will mess
     // with the menu a little still...)
     cvar_set_normal("sv_gravity", ftos(autocvar_sv_gravity));
     if(Campaign_Invalid())
         return;
 }
void CampaignPreIntermission ()
Definition at line 229 of file campaign.qc.
References autocvar__campaign_testrun, autocvar_fraglimit, autocvar_timelimit, bprint(), campaign_entries, campaign_forcewin, campaign_index_var, campaign_level, campaign_name, campaign_won, CampaignSaveCvar(), cheatcount_total, checkrules_equality, cvar_normal, FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, strcat(), and time.
Referenced by NextLevel().
 {
     int won = 0;
     int lost = 0;
     string savevar;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), {
         if(it.winning)
             won += 1;
         else
             lost += 1;
     });
     if(autocvar__campaign_testrun)
     {
         campaign_won = 1;
         bprint("Campaign test run, advancing level.\n");
     }
     else if(campaign_forcewin)
     {
         campaign_won = 1;
         bprint("The current level has been WON.\n");
     }
     else if(won == 1 && lost == 0 && checkrules_equality == 0)
     {
         if(autocvar_timelimit != 0 && autocvar_fraglimit != 0 && time > autocvar_timelimit * 60) // checks if the timelimit has expired.
         {
             campaign_won = 0;
             bprint("Time's up! The current level has been LOST.\n");
             // sound!
         }
         else
         {
             campaign_won = 1;
             bprint("The current level has been WON.\n");
             // sound!
         }
     }
     else if(autocvar_timelimit != 0 && time > autocvar_timelimit * 60)
     {
         campaign_won = 0;
         bprint("Time's up! The current level has been LOST.\n");
         // sound!
     }
     else
     {
         campaign_won = 0;
         bprint("The current level has been LOST.\n");
         // sound!
     }
     if(campaign_won && cheatcount_total == 0 && !autocvar__campaign_testrun)
     {
         if(campaign_level == cvar_normal(campaign_index_var))
         {
             if(campaign_entries < 2)
             {
                 // I have won
                 savevar = strcat("g_campaign", campaign_name, "_won");
                 CampaignSaveCvar(savevar, 1);
                 // advance level (for menu to show it right)
                 CampaignSaveCvar(campaign_index_var, campaign_level + 1);
             }
             else
             {
                 // advance level
                 CampaignSaveCvar(campaign_index_var, campaign_level + 1);
             }
         }
     }
 }
Variable Documentation
bool campaign_bots_may_start
campaign mode: bots shall spawn but wait for the player to spawn before they do anything in other game modes, this is ignored
Definition at line 20 of file campaign.qh.
Referenced by bot_think(), Join(), Monster_Move(), Monster_Move_2D(), MUTATOR_HOOKFUNCTION(), PlayerPreThink(), and round_handler_Think().
bool campaign_forcewin
Definition at line 22 of file campaign.qh.
Referenced by CampaignPreInit(), and CampaignPreIntermission().