Xonotic: common/minigames/cl_minigames_hud.qh File Reference
cl_minigames_hud.qh File Reference
Functions
float HUD_Minigame_InputEvent (float bInputType, float nPrimary, float nSecondary)
void HUD_Minigame_Mouse ()
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
void HUD_MinigameMenu_CustomEntry (entity parent, string message, string event_arg)
float HUD_MinigameMenu_IsOpened ()
Function Documentation
float HUD_Minigame_InputEvent (float bInputType, float nPrimary, float nSecondary)
TODO: bInputType == 2?
Definition at line 592 of file cl_minigames_hud.qc.
References active_minigame, argv(), autocvar__hud_configure, HUD_MinigameMenu_activeitem, HUD_MinigameMenu_Click(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, HUD_mouse_over(), HUD_PANEL, hudShiftState, K_ALT, K_CTRL, K_DOWNARROW, K_END, K_ENTER, K_ESCAPE, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_ENTER, K_KP_HOME, K_KP_UPARROW, K_MOUSE1, K_MOUSE16, K_MOUSE2, K_SHIFT, K_SPACE, K_UPARROW, mouseClicked, mousepos, NULL, S_ALT, S_CTRL, S_MOUSE1, S_MOUSE2, S_SHIFT, stof(), strcat(), and tokenize().
Referenced by CSQC_InputEvent().
 {
     if( !HUD_MinigameMenu_IsOpened() || autocvar__hud_configure )
         return false;
     if(bInputType == 3)
     {
         mousepos_x = nPrimary;
         mousepos_y = nSecondary;
         if ( active_minigame && HUD_mouse_over(HUD_PANEL(MINIGAMEBOARD)) )
             active_minigame.minigame_event(active_minigame,"mouse_moved",mousepos);
         return true;
     }
     else
     {
         if(bInputType == 0) {
             if(nPrimary == K_ALT) hudShiftState |= S_ALT;
             if(nPrimary == K_CTRL) hudShiftState |= S_CTRL;
             if(nPrimary == K_SHIFT) hudShiftState |= S_SHIFT;
             if(nPrimary == K_MOUSE1) mouseClicked |= S_MOUSE1;
             if(nPrimary == K_MOUSE2) mouseClicked |= S_MOUSE2;
         }
         else if(bInputType == 1) {
             if(nPrimary == K_ALT) hudShiftState -= (hudShiftState & S_ALT);
             if(nPrimary == K_CTRL) hudShiftState -= (hudShiftState & S_CTRL);
             if(nPrimary == K_SHIFT) hudShiftState -= (hudShiftState & S_SHIFT);
             if(nPrimary == K_MOUSE1) mouseClicked -= (mouseClicked & S_MOUSE1);
             if(nPrimary == K_MOUSE2) mouseClicked -= (mouseClicked & S_MOUSE2);
         }
         // allow some binds
         string con_keys = findkeysforcommand("toggleconsole", 0);
         int keys = tokenize(con_keys); // findkeysforcommand returns data for this
         int i;
         for (i = 0; i < keys; ++i)
         {
             if(nPrimary == stof(argv(i)))
                 return false;
         }
         if ( active_minigame && ( bInputType == 0 || bInputType == 1 ) )
         {
             string device = "";
             string action = bInputType == 0 ? "pressed" : "released";
             if ( nPrimary >= K_MOUSE1 && nPrimary <= K_MOUSE16 )
             {
                 if ( HUD_mouse_over(HUD_PANEL(MINIGAMEBOARD)) )
                     device = "mouse";
             }
             else
                 device = "key";
             if ( device && active_minigame.minigame_event(
                     active_minigame,strcat(device,"_",action),nPrimary) )
                 return true;
         }
         if ( bInputType == 0 )
         {
             if ( nPrimary == K_MOUSE1 && HUD_MinigameMenu_activeitem &&
                 HUD_mouse_over(HUD_PANEL(MINIGAMEMENU)) )
             {
                 HUD_MinigameMenu_Click(HUD_MinigameMenu_activeitem);
                 return true;
             }
             if ( nPrimary == K_UPARROW || nPrimary == K_KP_UPARROW )
             {
                 if ( HUD_MinigameMenu_activeitem && HUD_MinigameMenu_activeitem.list_prev )
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_activeitem.list_prev;
                 else
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_last_entry;
                 return true;
             }
             else if ( nPrimary == K_DOWNARROW || nPrimary == K_KP_DOWNARROW )
             {
                 if ( HUD_MinigameMenu_activeitem && HUD_MinigameMenu_activeitem.list_next )
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_activeitem.list_next;
                 else
                     HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_HOME || nPrimary == K_KP_HOME )
             {
                 HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_END || nPrimary == K_KP_END )
             {
                 HUD_MinigameMenu_activeitem = HUD_MinigameMenu_entries;
                 return true;
             }
             else if ( nPrimary == K_KP_ENTER || nPrimary == K_ENTER || nPrimary == K_SPACE )
             {
                 HUD_MinigameMenu_Click(HUD_MinigameMenu_activeitem);
                 return true;
             }
             else if ( nPrimary == K_ESCAPE )
             {
                 HUD_MinigameMenu_Close(NULL, NULL, NULL);
                 return true;
             }
         }
     }
     return false;
 }
void HUD_Minigame_Mouse ()
Definition at line 704 of file cl_minigames_hud.qc.
References autocvar__hud_configure, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_MouseInput(), HUD_mouse_over(), HUD_PANEL, and mv_active.
Referenced by HUD_Mouse().
 {
     if( !HUD_MinigameMenu_IsOpened() || autocvar__hud_configure || mv_active )
         return;
     if ( HUD_MinigameMenu_IsOpened() && HUD_mouse_over(HUD_PANEL(MINIGAMEMENU)) )
         HUD_MinigameMenu_MouseInput();
 }
void HUD_MinigameMenu_Close (entity this, entity actor, entity trigger)
Definition at line 361 of file cl_minigames_hud.qc.
References entity(), HUD_MinigameMenu_activeitem, HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, NULL, and p.
Referenced by deactivate_minigame(), HUD_Minigame_InputEvent(), HUD_MinigameMenu(), HUD_MinigameMenu_CurrentButton(), MUTATOR_HOOKFUNCTION(), and Shutdown().
 {
     if ( HUD_MinigameMenu_IsOpened() )
     {
         entity e, p;
         for ( e = HUD_MinigameMenu_entries; e != NULL; e = p )
         {
             p = e.list_next;
             delete(e);
         }
         HUD_MinigameMenu_entries = NULL;
         HUD_MinigameMenu_last_entry = NULL;
         HUD_MinigameMenu_activeitem = NULL;
     }
 }
void HUD_MinigameMenu_CustomEntry (entity parent, string message, string event_arg)
Definition at line 331 of file cl_minigames_hud.qc.
References entity(), HUD_MinigameMenu_ClickCustomEntry(), HUD_MinigameMenu_InsertEntry(), and HUD_MinigameMenu_SpawnSubEntry().
Referenced by bd_close_editor(), pp_next_match(), and ttt_next_match().
 {
     entity e = HUD_MinigameMenu_SpawnSubEntry(
         menumessage, HUD_MinigameMenu_ClickCustomEntry, parent );
     e.netname = event_arg;
     HUD_MinigameMenu_InsertEntry(e, parent);
     //dprint("CustomEntry ",ftos(num_for_edict(parent))," ",menumessage," ",event_arg,"\n");
 }
float HUD_MinigameMenu_IsOpened ()
Definition at line 355 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_entries, and NULL.
Referenced by activate_minigame(), HUD_Crosshair(), HUD_Minigame_InputEvent(), HUD_Minigame_Mouse(), HUD_MinigameBoard(), HUD_MinigameHelp(), HUD_MinigameMenu(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_Open(), HUD_MinigameStatus(), HUD_Mouse(), HUD_Panel_Draw(), HUD_QuickMenu_Forbidden(), HUD_WouldShowCursor(), minigame_prompt(), MUTATOR_HOOKFUNCTION(), Scoreboard_WouldDraw(), and View_CheckButtonStatus().
 {
     return HUD_MinigameMenu_entries != NULL;
 }