Xonotic: menu/xonotic/hudskinlist.qc File Reference
hudskinlist.qc File Reference
#include "hudskinlist.qh"
#include "inputbox.qh"
Functions
void getAllHUDSkins (entity me, int sortbuf)
void getHUDSkinFiles (entity me, int sortbuf, string subdir)
void HUDSkinList_Filter_Change (entity box, entity me)
void HUDSkinList_Refresh_Click (entity btn, entity me)
void HUDSkinList_SavedName_Change (entity box, entity me)
entity makeXonoticHUDSkinList ()
void SaveHUDSkin_Click (entity btn, entity me)
void SetHUDSkin_Click (entity btn, entity me)
void XonoticHUDSkinList_configureXonoticHUDSkinList (entity me)
void XonoticHUDSkinList_destroy (entity me)
void XonoticHUDSkinList_doubleClickListBoxItem (entity me, float i, vector where)
void XonoticHUDSkinList_draw (entity me)
void XonoticHUDSkinList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
void XonoticHUDSkinList_getHUDSkins (entity me)
string XonoticHUDSkinList_hudskinAuthor (entity me, float i)
string XonoticHUDSkinList_hudskinName (entity me, float i)
string XonoticHUDSkinList_hudskinPath (entity me, float i)
string XonoticHUDSkinList_hudskinTitle (entity me, float i)
float XonoticHUDSkinList_keyDown (entity me, float scan, float ascii, float shift)
void XonoticHUDSkinList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticHUDSkinList_setHUDSkin (entity me)
void XonoticHUDSkinList_showNotify (entity me)
Variables
const float HUDSKINPARM_AUTHOR = 3
const float HUDSKINPARM_COUNT = 4
const float HUDSKINPARM_NAME = 0
const float HUDSKINPARM_PATH = 1
const float HUDSKINPARM_TITLE = 2
Function Documentation
void getAllHUDSkins (entity me, int sortbuf)
Definition at line 83 of file hudskinlist.qc.
References argv(), fclose(), fgets(), FILE_READ, fopen(), HUDSKINPARM_AUTHOR, HUDSKINPARM_COUNT, HUDSKINPARM_NAME, HUDSKINPARM_PATH, HUDSKINPARM_TITLE, strcat(), strlen(), strstrofs, substring(), and tokenize_console.
Referenced by XonoticHUDSkinList_getHUDSkins().
 {
     int n = buf_getsize(sortbuf);
     for(int i = 0; i < n; ++i)
     {
         string entry = bufstr_get(sortbuf, i);
         int ofs = strstrofs(entry, "/", 0);
         string s = "";
         string filename = entry;
         if(ofs >= 0)
         {
             s = substring(entry, ofs + 1, -1); // skip initial "/"
             s = strcat(s, "/");
             bufstr_set(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_PATH, s);
             filename = strcat(s, substring(entry, 0, ofs));
         }
         else
             ofs = strlen(entry);
         s = substring(entry, 4, ofs - 4 - 4); // remove "hud_" prefix and ".cfg" suffix
         bufstr_set(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_NAME, s);
         int fh = fopen(filename, FILE_READ);
         if(fh < 0)
             continue;
         while((s = fgets(fh)) && substring(s, 0, 2) == "//")
         {
             tokenize_console(substring(s, 2, -1));
             if(argv(0) == "title")
                 bufstr_set(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_TITLE, argv(1));
             else if(argv(0) == "author")
                 bufstr_set(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_AUTHOR, argv(1));
         }
         fclose(fh);
     }
 }
void getHUDSkinFiles (entity me, int sortbuf, string subdir)
Definition at line 42 of file hudskinlist.qc.
References search_begin(), search_end(), search_getfilename(), search_getsize(), strcat(), strstrofs, and substring().
Referenced by XonoticHUDSkinList_getHUDSkins().
 {
     string s;
     if(me.filterString)
         s = me.filterString;
     else
         s = "*";
     s = strcat(subdir, "hud_", s, ".cfg");
     int list = search_begin(s, false, true);
     if(list >= 0)
     {
         int n = search_getsize(list);
         for(int i = 0; i < n; ++i)
         {
             string s = search_getfilename(list, i);
             int subdir_ofs = strstrofs(s, "/", 0);
             if(subdir_ofs >= 0)
             {
                 int ofs = subdir_ofs;
                 while(ofs != -1)
                 {
                     subdir_ofs = ofs;
                     ofs = strstrofs(s, "/", subdir_ofs + 1);
                 }
             }
             if(subdir_ofs == -1)
                 bufstr_add(sortbuf, s, true);
             else
             {
                 subdir = substring(s, 0, subdir_ofs);
                 string filename = substring(s, subdir_ofs + 1, -1);
                 // invert path and filename position so we can sort sortbuf by filename
                 bufstr_add(sortbuf, strcat(filename, "/", subdir), true);
             }
         }
         search_end(list);
     }
 }
void HUDSkinList_Filter_Change (entity box, entity me)
Definition at line 200 of file hudskinlist.qc.
References strcat(), string_null, strstrofs, strunzone(), and strzone().
Referenced by XonoticHUDExitDialog_fill().
 {
     if(me.filterString)
         strunzone(me.filterString);
     if(box.text != "")
     {
         if (strstrofs(box.text, "*", 0) >= 0 || strstrofs(box.text, "?", 0) >= 0)
             me.filterString = strzone(box.text);
         else
             me.filterString = strzone(strcat("*", box.text, "*"));
     }
     else
         me.filterString = string_null;
     me.getHUDSkins(me);
 }
void HUDSkinList_Refresh_Click (entity btn, entity me)
Definition at line 183 of file hudskinlist.qc.
Referenced by XonoticHUDExitDialog_fill(), and XonoticHUDSkinList_draw().
 {
     me.getHUDSkins(me);
     me.setSelected(me, 0); //always select the first element after a list update
 }
void HUDSkinList_SavedName_Change (entity box, entity me)
Definition at line 189 of file hudskinlist.qc.
References string_null, strunzone(), and strzone().
Referenced by XonoticHUDExitDialog_fill().
 {
     if(me.savedName)
         strunzone(me.savedName);
     if(box.text != "")
         me.savedName = strzone(box.text);
     else
         me.savedName = string_null;
 }
entity makeXonoticHUDSkinList ()
Definition at line 5 of file hudskinlist.qc.
References entity(), and NEW.
Referenced by XonoticHUDExitDialog_fill().
 {
     entity me;
     me = NEW(XonoticHUDSkinList);
     me.configureXonoticHUDSkinList(me);
     return me;
 }
void SaveHUDSkin_Click (entity btn, entity me)
Definition at line 218 of file hudskinlist.qc.
References localcmd, and time.
Referenced by XonoticHUDExitDialog_fill().
 {
     string s = me.savedName;
     if(s == "")
         s = "myconfig";
     localcmd(sprintf("hud save \"%s\"\n", s));
     me.delayedRefreshTime = time + 1;
 }
void SetHUDSkin_Click (entity btn, entity me)
Definition at line 243 of file hudskinlist.qc.
Referenced by XonoticHUDExitDialog_fill().
 {
     me.setHUDSkin(me);
 }
void XonoticHUDSkinList_configureXonoticHUDSkinList (entity me)
Definition at line 13 of file hudskinlist.qc.
 {
     me.configureXonoticListBox(me);
     me.nItems = 0;
 }
void XonoticHUDSkinList_destroy (entity me)
Definition at line 138 of file hudskinlist.qc.
 {
     if(me.nItems > 0)
         buf_del(me.listHUDSkin);
 }
void XonoticHUDSkinList_doubleClickListBoxItem (entity me, float i, vector where)
Definition at line 248 of file hudskinlist.qc.
References m_play_click_sound(), and MENU_SOUND_EXECUTE.
 {
     m_play_click_sound(MENU_SOUND_EXECUTE);
     me.setHUDSkin(me);
 }
void XonoticHUDSkinList_draw (entity me)
Definition at line 227 of file hudskinlist.qc.
References HUDSkinList_Refresh_Click(), NULL, SUPER, and time.
 {
     if(me.delayedRefreshTime > 0 && me.delayedRefreshTime < time)
     {
         HUDSkinList_Refresh_Click(NULL, me);
         me.delayedRefreshTime = 0;
     }
     SUPER(XonoticHUDSkinList).draw(me);
 }
void XonoticHUDSkinList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 157 of file hudskinlist.qc.
References draw_Fill(), draw_Text(), draw_TextShortenToWidth(), draw_TextWidth(), eX, eY, getFadedAlpha(), s2, and strcat().
 {
     string s, s2;
     if(isSelected)
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     else if(isFocused)
     {
         me.focusedItemAlpha = getFadedAlpha(me.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, me.focusedItemAlpha);
     }
     s = me.hudskinTitle(me, i);
     if(s == "")
         s = me.hudskinName(me, i);
     s2 = me.hudskinAuthor(me, i);
     if(s2 != "")
         s = strcat(s, " (", s2, ")");
     s = draw_TextShortenToWidth(s, me.columnNameSize, 0, me.realFontSize);
     draw_Text(me.realUpperMargin * eY + (me.columnNameOrigin + 0.00 * (me.columnNameSize - draw_TextWidth(s, 0, me.realFontSize))) * eX, s, me.realFontSize, SKINCOLOR_TEXT, SKINALPHA_TEXT, 1);
 }
void XonoticHUDSkinList_getHUDSkins (entity me)
Definition at line 119 of file hudskinlist.qc.
References buf_create, getAllHUDSkins(), getHUDSkinFiles(), and HUDSKINPARM_COUNT.
 {
     if (me.listHUDSkin >= 0)
         buf_del(me.listHUDSkin);
     me.listHUDSkin = buf_create();
     if (me.listHUDSkin < 0)
     {
         me.nItems = 0;
         return;
     }
     int sortbuf = buf_create();
     getHUDSkinFiles(me, sortbuf, "");
     getHUDSkinFiles(me, sortbuf, "data/");
     buf_sort(sortbuf, 128, 0);
     getAllHUDSkins(me, sortbuf);
     buf_del(sortbuf);
     me.nItems = buf_getsize(me.listHUDSkin) / HUDSKINPARM_COUNT;
 }
string XonoticHUDSkinList_hudskinAuthor (entity me, float i)
Definition at line 36 of file hudskinlist.qc.
References HUDSKINPARM_AUTHOR, and HUDSKINPARM_COUNT.
 {
     return bufstr_get(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_AUTHOR);
 }
string XonoticHUDSkinList_hudskinName (entity me, float i)
Definition at line 24 of file hudskinlist.qc.
References HUDSKINPARM_COUNT, and HUDSKINPARM_NAME.
 {
     return bufstr_get(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_NAME);
 }
string XonoticHUDSkinList_hudskinPath (entity me, float i)
Definition at line 28 of file hudskinlist.qc.
References HUDSKINPARM_COUNT, and HUDSKINPARM_PATH.
 {
     return bufstr_get(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_PATH);
 }
string XonoticHUDSkinList_hudskinTitle (entity me, float i)
Definition at line 32 of file hudskinlist.qc.
References HUDSKINPARM_COUNT, and HUDSKINPARM_TITLE.
 {
     return bufstr_get(me.listHUDSkin, i * HUDSKINPARM_COUNT + HUDSKINPARM_TITLE);
 }
float XonoticHUDSkinList_keyDown (entity me, float scan, float ascii, float shift)
Definition at line 254 of file hudskinlist.qc.
References K_ENTER, K_KP_ENTER, and SUPER.
 {
     if(scan == K_ENTER || scan == K_KP_ENTER)
     {
         me.setHUDSkin(me);
         return 1;
     }
     else
     {
         return SUPER(XonoticHUDSkinList).keyDown(me, scan, ascii, shift);
     }
 }
void XonoticHUDSkinList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 144 of file hudskinlist.qc.
References SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticHUDSkinList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.realFontSize_y = me.fontSize / (me.itemAbsSize_y = (absSize.y * me.itemHeight));
     me.realFontSize_x = me.fontSize / (me.itemAbsSize_x = (absSize.x * (1 - me.controlWidth)));
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
     me.columnNameOrigin = me.realFontSize.x;
     me.columnNameSize = 1 - 2 * me.realFontSize.x;
 }
void XonoticHUDSkinList_setHUDSkin (entity me)
Definition at line 237 of file hudskinlist.qc.
References localcmd, and strcat().
 {
     string cfg = strcat(me.hudskinPath(me, me.selectedItem), "hud_", me.hudskinName(me, me.selectedItem), ".cfg");
     localcmd("exec \"", cfg, "\"\n");
 }
void XonoticHUDSkinList_showNotify (entity me)
Definition at line 178 of file hudskinlist.qc.
 {
     me.getHUDSkins(me);
 }
Variable Documentation
const float HUDSKINPARM_AUTHOR = 3
Definition at line 22 of file hudskinlist.qc.
Referenced by getAllHUDSkins(), and XonoticHUDSkinList_hudskinAuthor().
const float HUDSKINPARM_COUNT = 4
Definition at line 23 of file hudskinlist.qc.
Referenced by getAllHUDSkins(), XonoticHUDSkinList_getHUDSkins(), XonoticHUDSkinList_hudskinAuthor(), XonoticHUDSkinList_hudskinName(), XonoticHUDSkinList_hudskinPath(), and XonoticHUDSkinList_hudskinTitle().
const float HUDSKINPARM_NAME = 0
Definition at line 19 of file hudskinlist.qc.
Referenced by getAllHUDSkins(), and XonoticHUDSkinList_hudskinName().
const float HUDSKINPARM_PATH = 1
Definition at line 20 of file hudskinlist.qc.
Referenced by getAllHUDSkins(), and XonoticHUDSkinList_hudskinPath().
const float HUDSKINPARM_TITLE = 2
Definition at line 21 of file hudskinlist.qc.
Referenced by getAllHUDSkins(), and XonoticHUDSkinList_hudskinTitle().