Xonotic: client/hud/hud_config.qh File Reference
hud_config.qh File Reference
Functions
void HUD_Configure_Frame ()
void HUD_Configure_PostDraw ()
void HUD_Panel_ExportCfg (string cfgname)
float HUD_Panel_InputEvent (float bInputType, float nPrimary, float nSecondary)
void HUD_Panel_Mouse ()
Variables
float hud_configure_checkcollisions
vector hud_configure_gridSize
float hud_configure_menu_open
float hud_configure_prev
vector hud_configure_realGridSize
int mouseClicked
int prevMouseClicked
vector prevMouseClickedPos
float prevMouseClickedTime
const int S_MOUSE1 = 1
const int S_MOUSE2 = 2
const int S_MOUSE3 = 4
Function Documentation
void HUD_Configure_Frame ()
Definition at line 1252 of file hud_config.qc.
References _menu_alpha_prev, autocvar__hud_configure, autocvar__menu_alpha, autocvar_hud_cursormode, HUD_Configure_DrawGrid(), HUD_Configure_Exit_Force(), hud_configure_menu_open, hud_configure_prev, hud_dynamic_shake_factor, hud_panels_from, hudShiftState, intermission, isdemo(), panel_order, scoreboard_active, and time.
Referenced by HUD_Main().
 {
     int i;
     if(autocvar__hud_configure)
     {
         if(isdemo() || intermission == 2 || scoreboard_active)
         {
             HUD_Configure_Exit_Force();
             return;
         }
         if(!hud_configure_prev)
         {
             if(autocvar_hud_cursormode)
                 setcursormode(1);
             hudShiftState = 0;
             for(i = hud_panels_COUNT - 1; i >= 0; --i)
                 hud_panels_from(panel_order[i]).update_time = time;
         }
         // NOTE this check is necessary because _menu_alpha isn't updated the frame the menu gets enabled
         if(autocvar__menu_alpha != _menu_alpha_prev)
         {
             if(autocvar__menu_alpha == 0)
                 hud_configure_menu_open = 0;
             _menu_alpha_prev = autocvar__menu_alpha;
         }
         HUD_Configure_DrawGrid();
     }
     else if(hud_configure_prev)
     {
         if(hud_configure_menu_open)
             hud_configure_menu_open = 0;
         if(autocvar_hud_cursormode)
             setcursormode(0);
         hud_dynamic_shake_factor = -1;
     }
 }
void HUD_Configure_PostDraw ()
Definition at line 1306 of file hud_config.qc.
References autocvar__hud_configure, autocvar__menu_alpha, drawfill(), DRAWFLAG_NORMAL, highlightedPanel, hlBorderSize, HUD_Panel_HlBorder(), HUD_Panel_UpdatePosSize, panel, panel_bg_border, panel_pos, panel_size, and tab_panel.
Referenced by HUD_Main().
 {
     if(autocvar__hud_configure)
     {
         if(tab_panel)
         {
             panel = tab_panel;
             HUD_Panel_UpdatePosSize();
             drawfill(panel_pos - '1 1 0' * panel_bg_border, panel_size + '2 2 0' * panel_bg_border, '1 1 1', .2, DRAWFLAG_NORMAL);
         }
         if(highlightedPanel)
         {
             panel = highlightedPanel;
             HUD_Panel_UpdatePosSize();
             HUD_Panel_HlBorder(panel_bg_border * hlBorderSize, '0 0.5 1', 0.4 * (1 - autocvar__menu_alpha));
         }
     }
 }
void HUD_Panel_ExportCfg (string cfgname)
Definition at line 13 of file hud_config.qc.
References autocvar_hud_skin, fclose(), FILE_WRITE, fopen(), hud_panels_from, HUD_Write, HUD_Write_Cvar, HUD_Write_PanelCvar, LOG_INFOF, MUTATOR_CALLHOOK, panel, and strcat().
Referenced by LocalCommand_hud().
 {
     float fh;
     string filename = strcat("hud_", autocvar_hud_skin, "_", cfgname, ".cfg");
     string str = "";
     fh = fopen(filename, FILE_WRITE);
     if(fh >= 0)
     {
         HUD_Write("//title \n");
         HUD_Write("//author \n");
         HUD_Write("\n");
         HUD_Write_Cvar("hud_skin");
         HUD_Write_Cvar("hud_panel_bg");
         HUD_Write_Cvar("hud_panel_bg_color");
         HUD_Write_Cvar("hud_panel_bg_color_team");
         HUD_Write_Cvar("hud_panel_bg_alpha");
         HUD_Write_Cvar("hud_panel_bg_border");
         HUD_Write_Cvar("hud_panel_bg_padding");
         HUD_Write_Cvar("hud_panel_fg_alpha");
         HUD_Write("\n");
         HUD_Write_Cvar("hud_dock");
         HUD_Write_Cvar("hud_dock_color");
         HUD_Write_Cvar("hud_dock_color_team");
         HUD_Write_Cvar("hud_dock_alpha");
         HUD_Write("\n");
         HUD_Write_Cvar("hud_progressbar_alpha");
         HUD_Write_Cvar("hud_progressbar_strength_color");
         HUD_Write_Cvar("hud_progressbar_superweapons_color");
         HUD_Write_Cvar("hud_progressbar_shield_color");
         HUD_Write_Cvar("hud_progressbar_health_color");
         HUD_Write_Cvar("hud_progressbar_armor_color");
         HUD_Write_Cvar("hud_progressbar_fuel_color");
         HUD_Write_Cvar("hud_progressbar_nexball_color");
         HUD_Write_Cvar("hud_progressbar_speed_color");
         HUD_Write_Cvar("hud_progressbar_acceleration_color");
         HUD_Write_Cvar("hud_progressbar_acceleration_neg_color");
         HUD_Write_Cvar("hud_progressbar_vehicles_ammo1_color");
         HUD_Write_Cvar("hud_progressbar_vehicles_ammo2_color");
         HUD_Write("\n");
         HUD_Write_Cvar("_hud_panelorder");
         HUD_Write("\n");
         HUD_Write_Cvar("hud_configure_grid");
         HUD_Write_Cvar("hud_configure_grid_xsize");
         HUD_Write_Cvar("hud_configure_grid_ysize");
         HUD_Write("\n");
         // common cvars for all panels
         for (int i = 0; i < hud_panels_COUNT; ++i)
         {
             panel = hud_panels_from(i);
             HUD_Write_PanelCvar("_pos");
             HUD_Write_PanelCvar("_size");
             HUD_Write_PanelCvar("_bg");
             HUD_Write_PanelCvar("_bg_color");
             HUD_Write_PanelCvar("_bg_color_team");
             HUD_Write_PanelCvar("_bg_alpha");
             HUD_Write_PanelCvar("_bg_border");
             HUD_Write_PanelCvar("_bg_padding");
             switch(panel) {
                 case HUD_PANEL_WEAPONS:
                     HUD_Write_Cvar("hud_panel_weapons_accuracy");
                     HUD_Write_Cvar("hud_panel_weapons_label");
                     HUD_Write_Cvar("hud_panel_weapons_label_scale");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_padding");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_time");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_fadetime");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_color_outofammo");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_color_donthave");
                     HUD_Write_Cvar("hud_panel_weapons_complainbubble_color_unavailable");
                     HUD_Write_Cvar("hud_panel_weapons_ammo");
                     HUD_Write_Cvar("hud_panel_weapons_ammo_color");
                     HUD_Write_Cvar("hud_panel_weapons_ammo_alpha");
                     HUD_Write_Cvar("hud_panel_weapons_aspect");
                     HUD_Write_Cvar("hud_panel_weapons_timeout");
                     HUD_Write_Cvar("hud_panel_weapons_timeout_effect");
                     HUD_Write_Cvar("hud_panel_weapons_timeout_fadebgmin");
                     HUD_Write_Cvar("hud_panel_weapons_timeout_fadefgmin");
                     HUD_Write_Cvar("hud_panel_weapons_timeout_speed_in");
                     HUD_Write_Cvar("hud_panel_weapons_timeout_speed_out");
                     HUD_Write_Cvar("hud_panel_weapons_onlyowned");
                     HUD_Write_Cvar("hud_panel_weapons_noncurrent_alpha");
                     HUD_Write_Cvar("hud_panel_weapons_noncurrent_scale");
                     HUD_Write_Cvar("hud_panel_weapons_selection_radius");
                     HUD_Write_Cvar("hud_panel_weapons_selection_speed");
                     break;
                 case HUD_PANEL_AMMO:
                     HUD_Write_Cvar("hud_panel_ammo_onlycurrent");
                     HUD_Write_Cvar("hud_panel_ammo_noncurrent_alpha");
                     HUD_Write_Cvar("hud_panel_ammo_noncurrent_scale");
                     HUD_Write_Cvar("hud_panel_ammo_iconalign");
                     HUD_Write_Cvar("hud_panel_ammo_progressbar");
                     HUD_Write_Cvar("hud_panel_ammo_progressbar_name");
                     HUD_Write_Cvar("hud_panel_ammo_progressbar_xoffset");
                     HUD_Write_Cvar("hud_panel_ammo_text");
                     break;
                 case HUD_PANEL_POWERUPS:
                     HUD_Write_Cvar("hud_panel_powerups_iconalign");
                     HUD_Write_Cvar("hud_panel_powerups_baralign");
                     HUD_Write_Cvar("hud_panel_powerups_progressbar");
                     HUD_Write_Cvar("hud_panel_powerups_text");
                     break;
                 case HUD_PANEL_HEALTHARMOR:
                     HUD_Write_Cvar("hud_panel_healtharmor_combined");
                     HUD_Write_Cvar("hud_panel_healtharmor_flip");
                     HUD_Write_Cvar("hud_panel_healtharmor_iconalign");
                     HUD_Write_Cvar("hud_panel_healtharmor_baralign");
                     HUD_Write_Cvar("hud_panel_healtharmor_progressbar");
                     HUD_Write_Cvar("hud_panel_healtharmor_progressbar_health");
                     HUD_Write_Cvar("hud_panel_healtharmor_progressbar_armor");
                     HUD_Write_Cvar("hud_panel_healtharmor_progressbar_gfx");
                     HUD_Write_Cvar("hud_panel_healtharmor_progressbar_gfx_smooth");
                     HUD_Write_Cvar("hud_panel_healtharmor_text");
                     break;
                 case HUD_PANEL_NOTIFY:
                     HUD_Write_Cvar("hud_panel_notify_flip");
                     HUD_Write_Cvar("hud_panel_notify_fontsize");
                     HUD_Write_Cvar("hud_panel_notify_time");
                     HUD_Write_Cvar("hud_panel_notify_fadetime");
                     HUD_Write_Cvar("hud_panel_notify_icon_aspect");
                     break;
                 case HUD_PANEL_TIMER:
                     break;
                 case HUD_PANEL_RADAR:
                     HUD_Write_Cvar("hud_panel_radar_foreground_alpha");
                     HUD_Write_Cvar("hud_panel_radar_rotation");
                     HUD_Write_Cvar("hud_panel_radar_zoommode");
                     HUD_Write_Cvar("hud_panel_radar_scale");
                     HUD_Write_Cvar("hud_panel_radar_maximized_scale");
                     HUD_Write_Cvar("hud_panel_radar_maximized_size");
                     HUD_Write_Cvar("hud_panel_radar_maximized_rotation");
                     HUD_Write_Cvar("hud_panel_radar_maximized_zoommode");
                     break;
                 case HUD_PANEL_SCORE:
                     HUD_Write_Cvar("hud_panel_score_rankings");
                     break;
                 case HUD_PANEL_VOTE:
                     HUD_Write_Cvar("hud_panel_vote_alreadyvoted_alpha");
                     break;
                 case HUD_PANEL_MODICONS:
                     HUD_Write_Cvar("hud_panel_modicons_ca_layout");
                     HUD_Write_Cvar("hud_panel_modicons_dom_layout");
                     HUD_Write_Cvar("hud_panel_modicons_freezetag_layout");
                     break;
                 case HUD_PANEL_PRESSEDKEYS:
                     HUD_Write_Cvar("hud_panel_pressedkeys_aspect");
                     HUD_Write_Cvar("hud_panel_pressedkeys_attack");
                     break;
                 case HUD_PANEL_ENGINEINFO:
                     HUD_Write_Cvar("hud_panel_engineinfo_framecounter_time");
                     HUD_Write_Cvar("hud_panel_engineinfo_framecounter_decimals");
                     break;
                 case HUD_PANEL_INFOMESSAGES:
                     HUD_Write_Cvar("hud_panel_infomessages_flip");
                     break;
                 case HUD_PANEL_PHYSICS:
                     HUD_Write_Cvar("hud_panel_physics_speed_unit_show");
                     HUD_Write_Cvar("hud_panel_physics_speed_max");
                     HUD_Write_Cvar("hud_panel_physics_speed_vertical");
                     HUD_Write_Cvar("hud_panel_physics_topspeed");
                     HUD_Write_Cvar("hud_panel_physics_topspeed_time");
                     HUD_Write_Cvar("hud_panel_physics_acceleration_max");
                     HUD_Write_Cvar("hud_panel_physics_acceleration_vertical");
                     HUD_Write_Cvar("hud_panel_physics_flip");
                     HUD_Write_Cvar("hud_panel_physics_baralign");
                     HUD_Write_Cvar("hud_panel_physics_progressbar");
                     HUD_Write_Cvar("hud_panel_physics_acceleration_progressbar_mode");
                     HUD_Write_Cvar("hud_panel_physics_acceleration_progressbar_scale");
                     HUD_Write_Cvar("hud_panel_physics_acceleration_progressbar_nonlinear");
                     HUD_Write_Cvar("hud_panel_physics_text");
                     HUD_Write_Cvar("hud_panel_physics_text_scale");
                     break;
                 case HUD_PANEL_CENTERPRINT:
                     HUD_Write_Cvar("hud_panel_centerprint_align");
                     HUD_Write_Cvar("hud_panel_centerprint_flip");
                     HUD_Write_Cvar("hud_panel_centerprint_fontscale");
                     HUD_Write_Cvar("hud_panel_centerprint_time");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_in");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_out");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passone");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passone_minalpha");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passtwo");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_passtwo_minalpha");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_subsequent_minfontsize");
                     HUD_Write_Cvar("hud_panel_centerprint_fade_minfontsize");
                     break;
                 case HUD_PANEL_ITEMSTIME:
                     HUD_Write_Cvar("hud_panel_itemstime_iconalign");
                     HUD_Write_Cvar("hud_panel_itemstime_progressbar");
                     HUD_Write_Cvar("hud_panel_itemstime_progressbar_name");
                     HUD_Write_Cvar("hud_panel_itemstime_progressbar_reduced");
                     HUD_Write_Cvar("hud_panel_itemstime_text");
                     HUD_Write_Cvar("hud_panel_itemstime_ratio");
                     HUD_Write_Cvar("hud_panel_itemstime_dynamicsize");
                     break;
                 case HUD_PANEL_MAPVOTE:
                     HUD_Write_Cvar("hud_panel_mapvote_highlight_border");
                     break;
                 case HUD_PANEL_QUICKMENU:
                     HUD_Write_Cvar("hud_panel_quickmenu_align");
                     break;
                 case HUD_PANEL_SCOREBOARD:
                     HUD_Write_Cvar("hud_panel_scoreboard_fadeinspeed");
                     HUD_Write_Cvar("hud_panel_scoreboard_fadeoutspeed");
                     HUD_Write_Cvar("hud_panel_scoreboard_respawntime_decimals");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_bg_alpha");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_bg_scale");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_fg_alpha");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_fg_alpha_self");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_highlight");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_highlight_alpha");
                     HUD_Write_Cvar("hud_panel_scoreboard_table_highlight_alpha_self");
                     HUD_Write_Cvar("hud_panel_scoreboard_bg_teams_color_team");
                     HUD_Write_Cvar("hud_panel_scoreboard_accuracy_doublerows");
                     HUD_Write_Cvar("hud_panel_scoreboard_accuracy_nocolors");
                     break;
             }
             HUD_Write("\n");
         }
         MUTATOR_CALLHOOK(HUD_WriteCvars, fh);
         HUD_Write("menu_sync\n"); // force the menu to reread the cvars, so that the dialogs are updated
         LOG_INFOF(_("^2Successfully exported to %s! (Note: It's saved in data/data/)"), filename);
         fclose(fh);
     }
     else
         LOG_INFOF(_("^1Couldn't write to %s"), filename);
 }
float HUD_Panel_InputEvent (float bInputType, float nPrimary, float nSecondary)
Definition at line 674 of file hud_config.qc.
References argv(), autocvar__hud_configure, autocvar__menu_alpha, autocvar_hud_dock, cvar(), cvar_set(), entity(), floor(), ftos(), highlightedAction, highlightedPanel, highlightedPanel_backup, hud_configure_menu_open, HUD_Panel_Arrow_Action(), HUD_Panel_EnableMenu(), HUD_Panel_FirstInDrawQ(), HUD_Panel_UpdatePosSize, hud_panels_from, hudShiftState, K_ALT, K_BACKSPACE, K_CTRL, K_DOWNARROW, K_ENTER, K_ESCAPE, K_KP_ENTER, K_LEFTARROW, K_MOUSE1, K_MOUSE2, K_PAUSE, K_RIGHTARROW, K_SHIFT, K_SPACE, K_TAB, K_UPARROW, LABEL, localcmd, mouseClicked, mousepos, NULL, panel, PANEL_CONFIG_CANBEOFF, PANEL_CONFIG_MAIN, panel_pos, panel_pos_backup, panel_size, panel_size_backup, panel_size_copied, pressed_key_time, reset_tab_panels(), S_ALT, S_CTRL, S_MOUSE1, S_MOUSE2, S_SHIFT, stof(), strcat(), tab_backward, tab_panel, tab_panel_pos, tab_panels, time, tokenize(), vector(), and vid_conheight.
Referenced by CSQC_InputEvent().
 {
     string s;
     if(bInputType == 2)
         return false;
     if(!autocvar__hud_configure)
         return false;
     if(bInputType == 3)
     {
         mousepos.x = nPrimary;
         mousepos.y = nSecondary;
         return true;
     }
     // block any input while a menu dialog is fading
     // don't block mousepos read as it leads to cursor jumps in the interaction with the menu
     if(autocvar__menu_alpha)
     {
         hudShiftState = 0;
         mouseClicked = 0;
         return true;
     }
     // allow console bind to work
     string con_keys = findkeysforcommand("toggleconsole", 0);
     int keys = tokenize(con_keys); // findkeysforcommand returns data for this
     bool hit_con_bind = false;
     int i;
     for (i = 0; i < keys; ++i)
     {
         if(nPrimary == stof(argv(i)))
             hit_con_bind = true;
     }
     if(bInputType == 0) {
         if(nPrimary == K_ALT) hudShiftState |= S_ALT;
         if(nPrimary == K_CTRL) hudShiftState |= S_CTRL;
         if(nPrimary == K_SHIFT) hudShiftState |= S_SHIFT;
     }
     else if(bInputType == 1) {
         if(nPrimary == K_ALT) hudShiftState -= (hudShiftState & S_ALT);
         if(nPrimary == K_CTRL) hudShiftState -= (hudShiftState & S_CTRL);
         if(nPrimary == K_SHIFT) hudShiftState -= (hudShiftState & S_SHIFT);
     }
     if(nPrimary == K_CTRL)
     {
         if (bInputType == 1) //ctrl has been released
         {
             if (tab_panel)
             {
                 //switch to selected panel
                 highlightedPanel = tab_panel;
                 highlightedAction = 0;
                 HUD_Panel_FirstInDrawQ(highlightedPanel.panel_id);
             }
             tab_panel = NULL;
             reset_tab_panels();
         }
     }
     if(nPrimary == K_MOUSE1)
     {
         if(bInputType == 0) // key pressed
             mouseClicked |= S_MOUSE1;
         else if(bInputType == 1) // key released
             mouseClicked -= (mouseClicked & S_MOUSE1);
     }
     else if(nPrimary == K_MOUSE2)
     {
         if(bInputType == 0) // key pressed
             mouseClicked |= S_MOUSE2;
         else if(bInputType == 1) // key released
             mouseClicked -= (mouseClicked & S_MOUSE2);
     }
     else if(nPrimary == K_ESCAPE)
     {
         if (bInputType == 1)
             return true;
         hud_configure_menu_open = 1;
         localcmd("menu_showhudexit\n");
     }
     else if(nPrimary == K_BACKSPACE && hudShiftState & S_CTRL)
     {
         if (bInputType == 1)
             return true;
         if (!hud_configure_menu_open)
             cvar_set("_hud_configure", "0");
     }
     else if(nPrimary == K_TAB && hudShiftState & S_CTRL) // switch panel
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         // FIXME minor bug: if a panel is highlighted, has the same pos_x and
         // lays in the same level of another panel then the next consecutive
         // CTRL TAB presses will reselect once more the highlighted panel
         entity starting_panel;
         entity old_tab_panel = tab_panel;
         if (!tab_panel) //first press of TAB
         {
             if (highlightedPanel)
             {
                 panel = highlightedPanel;
                 HUD_Panel_UpdatePosSize();
             }
             else
                 panel_pos = '0 0 0';
             starting_panel = highlightedPanel;
             tab_panel_pos = panel_pos; //to compute level
         }
         else
         {
             if ( ((!tab_backward) && (hudShiftState & S_SHIFT)) || (tab_backward && !(hudShiftState & S_SHIFT)) ) //tab direction changed?
                 reset_tab_panels();
             starting_panel = tab_panel;
         }
         tab_backward = (hudShiftState & S_SHIFT);
         float k, level = 0, start_posX;
         vector candidate_pos = '0 0 0';
         const float LEVELS_NUM = 4;
         float level_height = vid_conheight / LEVELS_NUM;
 LABEL(find_tab_panel)
         level = floor(tab_panel_pos.y / level_height) * level_height; //starting level
         candidate_pos.x = (!tab_backward) ? vid_conwidth : 0;
         start_posX = tab_panel_pos.x;
         tab_panel = NULL;
         k=0;
         while(++k)
         {
             for(i = 0; i < hud_panels_COUNT; ++i)
             {
                 panel = hud_panels_from(i);
                 if(!(panel.panel_configflags & PANEL_CONFIG_MAIN))
                     continue;
                 if (panel == tab_panels[i] || panel == starting_panel)
                     continue;
                 HUD_Panel_UpdatePosSize();
                 if (panel_pos.y >= level && (panel_pos.y - level) < level_height)
                 if (  ( !tab_backward && panel_pos.x >= start_posX && (panel_pos.x < candidate_pos.x || (panel_pos.x == candidate_pos.x && panel_pos.y <= candidate_pos.y)) )
                     || ( tab_backward && panel_pos.x <= start_posX && (panel_pos.x > candidate_pos.x || (panel_pos.x == candidate_pos.x && panel_pos.y >= candidate_pos.y)) )  )
                 {
                     tab_panel = panel;
                     tab_panel_pos = candidate_pos = panel_pos;
                 }
             }
             if (tab_panel)
                 break;
             if (k == LEVELS_NUM) //tab_panel not found
             {
                 reset_tab_panels();
                 if (!old_tab_panel)
                 {
                     tab_panel = NULL;
                     return true;
                 }
                 starting_panel = old_tab_panel;
                 old_tab_panel = NULL;
                 goto find_tab_panel; //u must find tab_panel!
             }
             if (!tab_backward)
             {
                 level = (level + level_height) % vid_conheight;
                 start_posX = 0;
                 candidate_pos.x = vid_conwidth;
             }
             else
             {
                 level = (level - level_height) % vid_conheight;
                 start_posX = vid_conwidth;
                 candidate_pos.x = 0;
             }
         }
         tab_panels[tab_panel.panel_id] = tab_panel;
     }
     else if(nPrimary == K_SPACE && hudShiftState & S_CTRL) // enable/disable highlighted panel or dock
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         if (highlightedPanel)
         {
             if(panel.panel_configflags & PANEL_CONFIG_CANBEOFF)
                 cvar_set(strcat("hud_panel_", highlightedPanel.panel_name), ftos(!cvar(strcat("hud_panel_", highlightedPanel.panel_name))));
         }
         else
             cvar_set(strcat("hud_dock"), (autocvar_hud_dock == "") ? "dock" : "");
     }
     else if(nPrimary == 'c' && hudShiftState & S_CTRL) // copy highlighted panel size
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         if (highlightedPanel)
         {
             panel = highlightedPanel;
             HUD_Panel_UpdatePosSize();
             panel_size_copied = panel_size;
         }
     }
     else if(nPrimary == 'v' && hudShiftState & S_CTRL) // past copied size on the highlighted panel
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         if (panel_size_copied == '0 0 0' || !highlightedPanel)
             return true;
         panel = highlightedPanel;
         HUD_Panel_UpdatePosSize();
         // reduce size if it'd go beyond screen boundaries
         vector tmp_size = panel_size_copied;
         if (panel_pos.x + panel_size_copied.x > vid_conwidth)
             tmp_size.x = vid_conwidth - panel_pos.x;
         if (panel_pos.y + panel_size_copied.y > vid_conheight)
             tmp_size.y = vid_conheight - panel_pos.y;
         if (panel_size == tmp_size)
             return true;
         // backup first!
         panel_pos_backup = panel_pos;
         panel_size_backup = panel_size;
         highlightedPanel_backup = highlightedPanel;
         s = strcat(ftos(tmp_size.x/vid_conwidth), " ", ftos(tmp_size.y/vid_conheight));
         cvar_set(strcat("hud_panel_", highlightedPanel.panel_name, "_size"), s);
     }
     else if(nPrimary == 'z' && hudShiftState & S_CTRL) // undo last action
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         //restore previous values
         if (highlightedPanel_backup)
         {
             s = strcat(ftos(panel_pos_backup.x/vid_conwidth), " ", ftos(panel_pos_backup.y/vid_conheight));
             cvar_set(strcat("hud_panel_", highlightedPanel_backup.panel_name, "_pos"), s);
             s = strcat(ftos(panel_size_backup.x/vid_conwidth), " ", ftos(panel_size_backup.y/vid_conheight));
             cvar_set(strcat("hud_panel_", highlightedPanel_backup.panel_name, "_size"), s);
             highlightedPanel_backup = NULL;
         }
     }
     else if(nPrimary == 's' && hudShiftState & S_CTRL) // save config
     {
         if (bInputType == 1 || mouseClicked)
             return true;
         localcmd("hud save myconfig\n");
     }
     else if(nPrimary == K_UPARROW || nPrimary == K_DOWNARROW || nPrimary == K_LEFTARROW || nPrimary == K_RIGHTARROW)
     {
         if (bInputType == 1)
         {
             pressed_key_time = 0;
             return true;
         }
         else if (pressed_key_time == 0)
             pressed_key_time = time;
         if (!mouseClicked)
             HUD_Panel_Arrow_Action(nPrimary); //move or resize panel
     }
     else if(nPrimary == K_ENTER || nPrimary == K_SPACE || nPrimary == K_KP_ENTER)
     {
         if (bInputType == 1)
             return true;
         if (highlightedPanel)
             HUD_Panel_EnableMenu();
     }
     else if(hit_con_bind || nPrimary == K_PAUSE)
         return false;
     return true;
 }
void HUD_Panel_Mouse ()
Definition at line 1119 of file hud_config.qc.
References autocvar__menu_alpha, autocvar_hud_configure_checkcollisions, autocvar_hud_cursormode, draw_cursor(), draw_cursor_normal(), drawfill(), DRAWFLAG_NORMAL, highlightedAction, highlightedPanel, highlightedPanel_backup, highlightedPanel_initial_pos, highlightedPanel_initial_size, hud_configure_checkcollisions, hud_configure_menu_open, HUD_Panel_Check_Mouse_Pos(), HUD_Panel_EnableMenu(), HUD_Panel_Highlight(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Panel_UpdatePosSize, hudShiftState, mouse_over_panel, mouseClicked, mousepos, NULL, panel, panel_bg_border, panel_click_distance, panel_click_resizeorigin, panel_pos, panel_pos_backup, panel_size, panel_size_backup, prevMouseClicked, prevMouseClickedPos, prevMouseClickedTime, reset_tab_panels(), resizeCorner, S_CTRL, S_MOUSE1, tab_panel, time, update_mousepos(), and vector().
Referenced by CSQC_UpdateView().
 {
     if(autocvar__menu_alpha == 1)
         return;
     if (!autocvar_hud_cursormode)
         update_mousepos();
     if(mouseClicked)
     {
         if(prevMouseClicked == 0)
         {
             if (tab_panel)
             {
                 //stop ctrl-tab selection
                 tab_panel = NULL;
                 reset_tab_panels();
             }
             HUD_Panel_Highlight(mouseClicked & S_MOUSE1); // sets highlightedPanel, highlightedAction, panel_click_distance, panel_click_resizeorigin
                                     // and calls HUD_Panel_UpdatePosSize() for the highlighted panel
             if (highlightedPanel)
             {
                 highlightedPanel_initial_pos = panel_pos;
                 highlightedPanel_initial_size = panel_size;
             }
             // doubleclick check
             if ((mouseClicked & S_MOUSE1) && time - prevMouseClickedTime < 0.4 && highlightedPanel && prevMouseClickedPos == mousepos)
             {
                 mouseClicked = 0; // to prevent spam, I guess.
                 HUD_Panel_EnableMenu();
             }
             else
             {
                 if (mouseClicked & S_MOUSE1)
                 {
                     prevMouseClickedTime = time;
                     prevMouseClickedPos = mousepos;
                 }
                 mouse_over_panel = HUD_Panel_Check_Mouse_Pos(mouseClicked & S_MOUSE1);
             }
         }
         else
         {
             panel = highlightedPanel;
             HUD_Panel_UpdatePosSize();
         }
         if (highlightedPanel)
         {
             drawfill(panel_pos - '1 1 0' * panel_bg_border, panel_size + '2 2 0' * panel_bg_border, '1 1 1', .1, DRAWFLAG_NORMAL);
             if (highlightedPanel_initial_pos != panel_pos || highlightedPanel_initial_size != panel_size)
             {
                 hud_configure_checkcollisions = (!(hudShiftState & S_CTRL) && autocvar_hud_configure_checkcollisions);
                 // backup!
                 panel_pos_backup = highlightedPanel_initial_pos;
                 panel_size_backup = highlightedPanel_initial_size;
                 highlightedPanel_backup = highlightedPanel;
             }
             else
                 // in case the clicked panel is inside another panel and we aren't
                 // moving it, avoid the immediate "fix" of its position/size
                 // (often unwanted and hateful) by disabling collisions check
                 hud_configure_checkcollisions = false;
         }
         if(highlightedAction == 1)
             HUD_Panel_SetPos(mousepos - panel_click_distance);
         else if(highlightedAction == 2)
         {
             vector mySize = '0 0 0';
             if(resizeCorner == 1) {
                 mySize.x = panel_click_resizeorigin.x - (mousepos.x - panel_click_distance.x);
                 mySize.y = panel_click_resizeorigin.y - (mousepos.y - panel_click_distance.y);
             } else if(resizeCorner == 2) {
                 mySize.x = mousepos.x + panel_click_distance.x - panel_click_resizeorigin.x;
                 mySize.y = panel_click_distance.y + panel_click_resizeorigin.y - mousepos.y;
             } else if(resizeCorner == 3) {
                 mySize.x = panel_click_resizeorigin.x + panel_click_distance.x - mousepos.x;
                 mySize.y = mousepos.y + panel_click_distance.y - panel_click_resizeorigin.y;
             } else { // resizeCorner == 4
                 mySize.x = mousepos.x - (panel_click_resizeorigin.x - panel_click_distance.x);
                 mySize.y = mousepos.y - (panel_click_resizeorigin.y - panel_click_distance.y);
             }
             HUD_Panel_SetPosSize(mySize);
         }
     }
     else
     {
         if(prevMouseClicked)
             highlightedAction = 0;
         if(hud_configure_menu_open == 2)
             mouse_over_panel = 0;
         else
             mouse_over_panel = HUD_Panel_Check_Mouse_Pos(true);
         if (mouse_over_panel && !tab_panel)
             drawfill(panel_pos - '1 1 0' * panel_bg_border, panel_size + '2 2 0' * panel_bg_border, '1 1 1', .1, DRAWFLAG_NORMAL);
     }
     // draw cursor after performing move/resize to have the panel pos/size updated before mouse_over_panel
     float cursor_alpha = 1 - autocvar__menu_alpha;
     if(!mouse_over_panel)
         draw_cursor_normal(mousepos, '1 1 1', cursor_alpha);
     else if(mouse_over_panel == 1)
         draw_cursor(mousepos, '0.5 0.5 0', "/cursor_move", '1 1 1', cursor_alpha);
     else if(mouse_over_panel == 2)
         draw_cursor(mousepos, '0.5 0.5 0', "/cursor_resize", '1 1 1', cursor_alpha);
     else
         draw_cursor(mousepos, '0.5 0.5 0', "/cursor_resize2", '1 1 1', cursor_alpha);
     prevMouseClicked = mouseClicked;
 }
Variable Documentation
float hud_configure_checkcollisions
Definition at line 12 of file hud_config.qh.
Referenced by HUD_Panel_Arrow_Action(), HUD_Panel_Mouse(), HUD_Panel_SetPos(), and HUD_Panel_SetPosSize().
vector hud_configure_gridSize
Definition at line 13 of file hud_config.qh.
Referenced by HUD_Configure_DrawGrid(), HUD_Panel_SetPos(), and HUD_Panel_SetPosSize().
float hud_configure_menu_open
Definition at line 15 of file hud_config.qh.
Referenced by HUD_Configure_Exit_Force(), HUD_Configure_Frame(), HUD_Main(), HUD_Panel_EnableMenu(), HUD_Panel_InputEvent(), HUD_Panel_LoadCvars(), HUD_Panel_Mouse(), and Scoreboard_Draw().
float hud_configure_prev
Definition at line 11 of file hud_config.qh.
Referenced by HUD_CenterPrint(), HUD_Configure_Frame(), HUD_Main(), and HUD_QuickMenu().
vector hud_configure_realGridSize
Definition at line 14 of file hud_config.qh.
Referenced by HUD_Configure_DrawGrid(), HUD_Panel_Arrow_Action(), HUD_Panel_SetPos(), and HUD_Panel_SetPosSize().
int mouseClicked
Definition at line 6 of file hud_config.qh.
Referenced by HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_Panel_Mouse(), HUD_Radar_InputEvent(), HUD_Radar_Mouse(), HUD_Radar_Show_Maximized(), QuickMenu_Close(), QuickMenu_InputEvent(), and QuickMenu_Mouse().
int prevMouseClicked
Definition at line 7 of file hud_config.qh.
Referenced by HUD_Panel_Mouse(), QuickMenu_Close(), and QuickMenu_Mouse().
vector prevMouseClickedPos
Definition at line 9 of file hud_config.qh.
Referenced by HUD_Panel_Mouse().
float prevMouseClickedTime
Definition at line 8 of file hud_config.qh.
Referenced by HUD_Panel_Mouse().
const int S_MOUSE1 = 1
Definition at line 3 of file hud_config.qh.
Referenced by HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_Panel_Mouse(), HUD_Radar_InputEvent(), HUD_Radar_Mouse(), QuickMenu_InputEvent(), and QuickMenu_Mouse().
const int S_MOUSE2 = 2
Definition at line 4 of file hud_config.qh.
Referenced by HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_Radar_InputEvent(), HUD_Radar_Mouse(), QuickMenu_InputEvent(), and QuickMenu_Mouse().
const int S_MOUSE3 = 4
Definition at line 5 of file hud_config.qh.