Xonotic: menu/xonotic/slider_resolution.qh File Reference
slider_resolution.qh File Reference
#include "textslider.qh"
Classes
class XonoticResolutionSlider
Functions
entity makeXonoticResolutionSlider ()
float updateConwidths (float width, float height, float pixelheight)
Function Documentation
entity makeXonoticResolutionSlider ()
Definition at line 67 of file slider_resolution.qc.
References entity(), and NEW.
Referenced by XonoticVideoSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticResolutionSlider);
     me.configureXonoticResolutionSlider(me);
     return me;
 }
float updateConwidths (float width, float height, float pixelheight)
Definition at line 6 of file slider_resolution.qc.
References cvar(), cvar_set(), cvar_string(), ftos(), height, LOG_TRACE(), max(), min(), rint(), vector(), and XonoticResolutionSlider_DataHasChanged.
 {
     vector r, c;
     float minfactor, maxfactor;
     float sz, f;
     sz = cvar("menu_vid_scale");
     if (sz < -1)
         return 0;  // No recalculation.
     // Save off current settings.
     cvar_set("_menu_vid_width", ftos(width));
     cvar_set("_menu_vid_height", ftos(height));
     cvar_set("_menu_vid_pixelheight", ftos(pixelheight));
     cvar_set("_menu_vid_desktopfullscreen", cvar_string("vid_desktopfullscreen"));
     r_x = width;
     r_y = height;
     r_z = pixelheight;
     // calculate the base resolution
     c_z = 0;
     c_x = 800;
     c_y = c.x * r.y * r.z / r.x;
     if(c.y < 600)
     {
         c_y = 600;
         c_x = c.y * r.x / (r.y * r.z);
     }
     f = min(r.x / c.x, r.y / c.y);
     if(f < 1)
         c = c * f; // ensures that c_x <= r_x and c_y <= r_y
     minfactor = min(1, 640 / c.x);            // can be > 1 only if c_x is <640
     maxfactor = max(1, r.x / c.x, r.y / c.y); // can be < 1 only if r_x < c_x and r_y < c_y
     LOG_TRACE("min factor: ", ftos(minfactor));
     LOG_TRACE("max factor: ", ftos(maxfactor));
     if(sz < 0)
         f = 1 - (maxfactor - 1) * sz;
     else if(sz > 0)
         f = 1 + (minfactor - 1) * sz;
     else
         f = 1;
     c = c * f; // fteqcc fail
     c_x = rint(c.x);
     c_y = rint(c.y);
     // Please reload resolutions list and such stuff.
     XonoticResolutionSlider_DataHasChanged = true;
     if (c.x != cvar("vid_conwidth") || c.y != cvar("vid_conheight"))
     {
         cvar_set("vid_conwidth", ftos(c.x));
         cvar_set("vid_conheight", ftos(c.y));
         return 1;
     }
     return 0;
 }