Xonotic: common/gamemodes/gamemode/onslaught/sv_onslaught.qc File Reference
sv_onslaught.qc File Reference
#include "sv_onslaught.qh"
#include "sv_controlpoint.qh"
#include "sv_generator.qh"
Functions
bool clientcamera_send (entity this, entity to, int sf)
void havocbot_goalrating_ons_controlpoints_attack (entity this, float ratingscale)
bool havocbot_goalrating_ons_generator_attack (entity this, float ratingscale)
void havocbot_ons_reset_role (entity this)
void havocbot_role_ons_assistant (entity this)
void havocbot_role_ons_defense (entity this)
void havocbot_role_ons_offense (entity this)
void havocbot_role_ons_setrole (entity this, int role)
MUTATOR_HOOKFUNCTION (ons, reset_map_global)
MUTATOR_HOOKFUNCTION (ons, ClientDisconnect)
MUTATOR_HOOKFUNCTION (ons, MakePlayerObserver)
MUTATOR_HOOKFUNCTION (ons, PlayerSpawn)
MUTATOR_HOOKFUNCTION (ons, PlayerDies)
MUTATOR_HOOKFUNCTION (ons, MonsterMove)
MUTATOR_HOOKFUNCTION (ons, MonsterSpawn)
MUTATOR_HOOKFUNCTION (ons, TurretSpawn)
MUTATOR_HOOKFUNCTION (ons, HavocBot_ChooseRole)
MUTATOR_HOOKFUNCTION (ons, TeamBalance_CheckAllowedTeams)
MUTATOR_HOOKFUNCTION (ons, SpectateCopy)
MUTATOR_HOOKFUNCTION (ons, SV_ParseClientCommand)
MUTATOR_HOOKFUNCTION (ons, PlayerUseKey)
MUTATOR_HOOKFUNCTION (ons, PlayHitsound)
MUTATOR_HOOKFUNCTION (ons, SendWaypoint)
MUTATOR_HOOKFUNCTION (ons, TurretValidateTarget)
MUTATOR_HOOKFUNCTION (ons, TurretThink)
void nades_Clear (entity e)
void ons_camSetup (entity this)
bool ons_CaptureShield_Customize (entity this, entity client)
void ons_CaptureShield_Reset (entity this)
void ons_CaptureShield_Spawn (entity generator, bool is_generator)
void ons_CaptureShield_Touch (entity this, entity toucher)
int ons_ControlPoint_Attackable (entity cp, int teamnum)
int ons_ControlPoint_CanBeLinked (entity cp, int teamnum)
void ons_ControlPoint_Icon_BuildThink (entity this)
void ons_ControlPoint_Icon_Damage (entity this, entity inflictor, entity attacker, float damage, int deathtype,.entity weaponentity, vector hitloc, vector force)
bool ons_ControlPoint_Icon_Heal (entity targ, entity inflictor, float amount, float limit)
void ons_ControlPoint_Icon_Spawn (entity cp, entity player)
void ons_ControlPoint_Icon_Think (entity this)
void ons_ControlPoint_Reset (entity this)
void ons_ControlPoint_Setup (entity cp)
void ons_ControlPoint_Think (entity this)
void ons_ControlPoint_Touch (entity this, entity toucher)
void ons_ControlPoint_UpdateSprite (entity e)
entity ons_ControlPoint_Waypoint (entity e)
int ons_Count_SelfControlPoints (entity this)
find the number of control points and generators in the same team as this
void ons_DelayedControlPoint_Setup (entity this)
void ons_DelayedGeneratorSetup (entity this)
void ons_DelayedInit (entity this)
void ons_DelayedLinkSetup (entity this)
void ons_Generator_UpdateSprite (entity e)
entity ons_Generator_Waypoint (entity e)
void ons_GeneratorDamage (entity this, entity inflictor, entity attacker, float damage, int deathtype,.entity weaponentity, vector hitloc, vector force)
bool ons_GeneratorHeal (entity targ, entity inflictor, float amount, float limit)
void ons_GeneratorReset (entity this)
void ons_GeneratorSetup (entity gen)
void ons_GeneratorThink (entity this)
void ons_Initialize ()
void ons_Link_CheckUpdate (entity this)
bool ons_Link_Send (entity this, entity to, int sendflags)
void ons_MonsterSpawn_Delayed (entity this)
entity ons_Nearest_ControlPoint (entity this, vector pos, float max_dist)
entity ons_Nearest_ControlPoint_2D (entity this, vector pos, float max_dist)
void ons_ScoreRules ()
bool ons_Teleport (entity player, entity tele_target, float range, bool tele_effects)
Teleport player to a random position near tele_target if tele_effects is true, teleport sound+particles are created return false on failure.
void ons_TurretSpawn_Delayed (entity this)
bool Onslaught_CheckPlayers ()
bool Onslaught_CheckWinner ()
void onslaught_controlpoint_icon_link (entity e, void(entity this) spawnproc)
void Onslaught_count_generators ()
void onslaught_generator_touch (entity this, entity toucher)
int Onslaught_GetWinnerTeam ()
void Onslaught_RoundStart ()
void onslaught_updatelinks ()
spawnfunc (onslaught_link)
spawnfunc (onslaught_controlpoint)
spawnfunc (onslaught_generator)
Variables
float autocvar_g_onslaught_allow_vehicle_touch
float autocvar_g_onslaught_click_radius
float autocvar_g_onslaught_cp_buildhealth
float autocvar_g_onslaught_cp_buildtime
float autocvar_g_onslaught_cp_health
float autocvar_g_onslaught_cp_proxydecap
float autocvar_g_onslaught_cp_proxydecap_distance = 512
float autocvar_g_onslaught_cp_proxydecap_dps = 100
float autocvar_g_onslaught_cp_regen
float autocvar_g_onslaught_gen_health
float autocvar_g_onslaught_round_timelimit
float autocvar_g_onslaught_shield_force = 100
bool autocvar_g_onslaught_spawn_at_controlpoints
float autocvar_g_onslaught_spawn_at_controlpoints_chance = 0.5
float autocvar_g_onslaught_spawn_at_controlpoints_random
bool autocvar_g_onslaught_spawn_at_generator
float autocvar_g_onslaught_spawn_at_generator_chance
float autocvar_g_onslaught_spawn_at_generator_random
float autocvar_g_onslaught_spawn_choose
float autocvar_g_onslaught_teleport_radius
float autocvar_g_onslaught_teleport_wait
float autocvar_g_onslaught_warmup
entity cam
bool g_onslaught
int total_generators
Function Documentation
bool clientcamera_send (entity this, entity to, int sf)
Definition at line 36 of file sv_onslaught.qc.
References origin, and WriteAngle().
Referenced by ons_camSetup().
 {
     WriteHeader(MSG_ENTITY, ENT_ONSCAMERA);
     WriteVector(MSG_ENTITY, this.origin);
     WriteAngle(MSG_ENTITY, this.angles_x);
     WriteAngle(MSG_ENTITY, this.angles_y);
     WriteAngle(MSG_ENTITY, this.angles_z);
     return true;
 }
void havocbot_goalrating_ons_controlpoints_attack (entity this, float ratingscale)
Definition at line 1293 of file sv_onslaught.qc.
References best, BIT, checkpvs(), entity(), FLOAT_MAX, FOREACH_CLIENT, ftos(), g_waypoints, havocbot_attack_time, havocbot_ons_target, havocbot_role_ons_offense(), IL_EACH, IS_PLAYER, LOG_DEBUG, navigation_routerating(), netname, NULL, ons_worldcplist, origin, radius, SAME_TEAM, team, time, vdist, view_ofs, and vtos().
Referenced by havocbot_role_ons_offense().
 {
     entity cp, cp1, cp2, best, wp;
     float radius, bestvalue;
     int c;
     bool found;
     // Filter control points
     for(cp2 = ons_worldcplist; cp2; cp2 = cp2.ons_worldcpnext)
     {
         cp2.wpcost = c = 0;
         cp2.wpconsidered = false;
         if(cp2.isshielded)
             continue;
         // Ignore owned controlpoints
         if(!((cp2.aregensneighbor & BIT(this.team)) || (cp2.arecpsneighbor & BIT(this.team))))
             continue;
         // Count team mates interested in this control point
         // (easier and cleaner than keeping counters per cp and teams)
         FOREACH_CLIENT(it != this && IS_PLAYER(it), {
             if(SAME_TEAM(it, this))
             if(it.havocbot_role == havocbot_role_ons_offense)
             if(it.havocbot_ons_target == cp2)
                 ++c;
         });
         // NOTE: probably decrease the cost of attackable control points
         cp2.wpcost = c;
         cp2.wpconsidered = true;
     }
     // We'll consider only the best case
     bestvalue = FLOAT_MAX;
     cp = NULL;
     for(cp1 = ons_worldcplist; cp1; cp1 = cp1.ons_worldcpnext)
     {
         if (!cp1.wpconsidered)
             continue;
         if(cp1.wpcost<bestvalue)
         {
             bestvalue = cp1.wpcost;
             cp = cp1;
             this.havocbot_ons_target = cp1;
         }
     }
     if (!cp)
         return;
     LOG_DEBUG(this.netname, " chose cp ranked ", ftos(bestvalue));
     if(cp.goalentity)
     {
         // Should be attacked
         // Rate waypoints near it
         found = false;
         best = NULL;
         bestvalue = FLOAT_MAX;
         for (radius = 500; radius <= 1000 && !found; radius += 500)
         {
             IL_EACH(g_waypoints, vdist(cp.origin - it.origin, <, radius),
             {
                 if (!(it.wpflags & WAYPOINTFLAG_GENERATED) && checkpvs(it.origin, cp))
                 {
                     found = true;
                     if (it.cnt < bestvalue)
                     {
                         best = it;
                         bestvalue = it.cnt;
                     }
                 }
             });
         }
         if(best)
         {
             navigation_routerating(this, best, ratingscale, 10000);
             best.cnt += 1;
             this.havocbot_attack_time = 0;
             if(checkpvs(this.origin + this.view_ofs, cp))
             if(checkpvs(this.origin + this.view_ofs, best))
                 this.havocbot_attack_time = time + 2;
         }
         else
         {
             navigation_routerating(this, cp, ratingscale, 10000);
         }
         LOG_DEBUG(this.netname, " found an attackable controlpoint at ", vtos(cp.origin));
     }
     else
     {
         // Should be touched
         LOG_DEBUG(this.netname, " found a touchable controlpoint at ", vtos(cp.origin));
         navigation_routerating(this, cp, ratingscale * 2, 10000);
     }
 }
bool havocbot_goalrating_ons_generator_attack (entity this, float ratingscale)
Definition at line 1395 of file sv_onslaught.qc.
References checkpvs(), entity(), FLOAT_MAX, g_waypoints, havocbot_attack_time, IL_EACH, LOG_DEBUG, navigation_routerating(), NULL, ons_worldgeneratorlist, origin, SAME_TEAM, time, vdist, and view_ofs.
Referenced by havocbot_role_ons_offense().
 {
     entity g, wp, bestwp;
     bool found;
     int bestvalue;
     for(g = ons_worldgeneratorlist; g; g = g.ons_worldgeneratornext)
     {
         if(SAME_TEAM(g, this) || g.isshielded)
             continue;
         // Should be attacked
         // Rate waypoints near it
         found = false;
         bestwp = NULL;
         bestvalue = FLOAT_MAX;
         IL_EACH(g_waypoints, vdist(g.origin - it.origin, <, 400),
         {
             if (checkpvs(it.origin, g))
             {
                 found = true;
                 if (it.cnt < bestvalue)
                 {
                     bestwp = it;
                     bestvalue = it.cnt;
                 }
             }
         });
         if(bestwp)
         {
             LOG_DEBUG("waypoints found around generator");
             navigation_routerating(this, bestwp, ratingscale, 10000);
             bestwp.cnt += 1;
             this.havocbot_attack_time = 0;
             if(checkpvs(this.origin + this.view_ofs, g))
             if(checkpvs(this.origin + this.view_ofs, bestwp))
                 this.havocbot_attack_time = time + 5;
             return true;
         }
         else
         {
             LOG_DEBUG("generator found without waypoints around");
             // if there aren't waypoints near the generator go straight to it
             navigation_routerating(this, g, ratingscale, 10000);
             this.havocbot_attack_time = 0;
             return true;
         }
     }
     return false;
 }
void havocbot_ons_reset_role (entity this)
Definition at line 1495 of file sv_onslaught.qc.
References HAVOCBOT_ONS_ROLE_OFFENSE, havocbot_ons_target, havocbot_role_ons_setrole(), IS_DEAD, and NULL.
Referenced by havocbot_role_ons_assistant(), havocbot_role_ons_defense(), havocbot_role_ons_offense(), and MUTATOR_HOOKFUNCTION().
 {
     if(IS_DEAD(this))
         return;
     this.havocbot_ons_target = NULL;
     // TODO: Defend control points or generator if necessary
     havocbot_role_ons_setrole(this, HAVOCBOT_ONS_ROLE_OFFENSE);
 }
void havocbot_role_ons_assistant (entity this)
Definition at line 1485 of file sv_onslaught.qc.
References havocbot_ons_reset_role().
Referenced by havocbot_role_ons_setrole().
 {
     havocbot_ons_reset_role(this);
 }
void havocbot_role_ons_defense (entity this)
Definition at line 1490 of file sv_onslaught.qc.
References havocbot_ons_reset_role().
Referenced by havocbot_role_ons_setrole().
 {
     havocbot_ons_reset_role(this);
 }
void havocbot_role_ons_offense (entity this)
Definition at line 1450 of file sv_onslaught.qc.
References havocbot_attack_time, havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_goalrating_ons_controlpoints_attack(), havocbot_goalrating_ons_generator_attack(), havocbot_ons_reset_role(), havocbot_role_timeout, IS_DEAD, navigation_goalrating_end(), navigation_goalrating_start(), navigation_goalrating_timeout(), navigation_goalrating_timeout_set(), origin, and time.
Referenced by havocbot_goalrating_ons_controlpoints_attack(), and havocbot_role_ons_setrole().
 {
     if(IS_DEAD(this))
     {
         this.havocbot_attack_time = 0;
         havocbot_ons_reset_role(this);
         return;
     }
     // Set the role timeout if necessary
     if (!this.havocbot_role_timeout)
         this.havocbot_role_timeout = time + 120;
     if (time > this.havocbot_role_timeout)
     {
         havocbot_ons_reset_role(this);
         return;
     }
     if(this.havocbot_attack_time>time)
         return;
     if (navigation_goalrating_timeout(this))
     {
         navigation_goalrating_start(this);
         havocbot_goalrating_enemyplayers(this, 20000, this.origin, 650);
         if(!havocbot_goalrating_ons_generator_attack(this, 10000))
             havocbot_goalrating_ons_controlpoints_attack(this, 10000);
         havocbot_goalrating_items(this, 25000, this.origin, 10000);
         navigation_goalrating_end(this);
         navigation_goalrating_timeout_set(this);
     }
 }
void havocbot_role_ons_setrole (entity this, int role)
Definition at line 1271 of file sv_onslaught.qc.
References HAVOCBOT_ONS_ROLE_ASSISTANT, HAVOCBOT_ONS_ROLE_DEFENSE, HAVOCBOT_ONS_ROLE_OFFENSE, havocbot_role_ons_assistant(), havocbot_role_ons_defense(), havocbot_role_ons_offense(), havocbot_role_timeout, LOG_DEBUG, and netname.
Referenced by havocbot_ons_reset_role().
 {
     switch(role)
     {
         case HAVOCBOT_ONS_ROLE_DEFENSE:
             LOG_DEBUG(this.netname, " switched to defense");
             this.havocbot_role = havocbot_role_ons_defense;
             this.havocbot_role_timeout = 0;
             break;
         case HAVOCBOT_ONS_ROLE_ASSISTANT:
             LOG_DEBUG(this.netname, " switched to assistant");
             this.havocbot_role = havocbot_role_ons_assistant;
             this.havocbot_role_timeout = 0;
             break;
         case HAVOCBOT_ONS_ROLE_OFFENSE:
             LOG_DEBUG(this.netname, " switched to offense");
             this.havocbot_role = havocbot_role_ons_offense;
             this.havocbot_role_timeout = 0;
             break;
     }
 }
MUTATOR_HOOKFUNCTION (ons , reset_map_global)
Definition at line 1660 of file sv_onslaught.qc.
References FOREACH_CLIENT, IS_PLAYER, and PutClientInServer().
 {
     FOREACH_CLIENT(IS_PLAYER(it), {
         STAT(ROUNDLOST, it) = false;
         it.ons_deathloc = '0 0 0';
         PutClientInServer(it);
         it.clientcamera = it;
     });
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , ClientDisconnect)
Definition at line 1671 of file sv_onslaught.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     player.ons_deathloc = '0 0 0';
 }
MUTATOR_HOOKFUNCTION (ons , MakePlayerObserver)
Definition at line 1678 of file sv_onslaught.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     player.ons_deathloc = '0 0 0';
 }
MUTATOR_HOOKFUNCTION (ons , PlayerSpawn)
Definition at line 1685 of file sv_onslaught.qc.
References autocvar_g_onslaught_spawn_at_controlpoints, autocvar_g_onslaught_spawn_at_controlpoints_chance, autocvar_g_onslaught_spawn_at_controlpoints_random, autocvar_g_onslaught_spawn_at_generator, autocvar_g_onslaught_spawn_at_generator_chance, autocvar_g_onslaught_spawn_at_generator_random, autocvar_g_onslaught_spawn_choose, autocvar_g_onslaught_teleport_radius, entity(), M_ARGV, MOVE_NOMONSTERS, MOVE_NORMAL, normalize(), NULL, ons_stalemate, ons_Teleport(), ons_worldcplist, ons_worldgeneratorlist, RAD2DEG, random(), RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), round_handler_IsRoundStarted, SAME_TEAM, setorigin(), trace_fraction, trace_startsolid, vector(), and vlen2.
 {
     entity player = M_ARGV(0, entity);
     if(!round_handler_IsRoundStarted())
     {
         player.player_blocked = true;
         return false;
     }
     entity l;
     for(l = ons_worldgeneratorlist; l; l = l.ons_worldgeneratornext)
     {
         l.sprite.SendFlags |= 16;
     }
     for(l = ons_worldcplist; l; l = l.ons_worldcpnext)
     {
         l.sprite.SendFlags |= 16;
     }
     if(ons_stalemate) { Send_Notification(NOTIF_ONE, player, MSG_CENTER, CENTER_OVERTIME_CONTROLPOINT); }
     if ( autocvar_g_onslaught_spawn_choose )
     if ( player.ons_spawn_by )
     if ( ons_Teleport(player,player.ons_spawn_by,autocvar_g_onslaught_teleport_radius,false) )
     {
         player.ons_spawn_by = NULL;
         return false;
     }
     if(autocvar_g_onslaught_spawn_at_controlpoints)
     if(random() <= autocvar_g_onslaught_spawn_at_controlpoints_chance)
     {
         float random_target = autocvar_g_onslaught_spawn_at_controlpoints_random;
         entity tmp_entity, closest_target = NULL;
         vector spawn_loc = player.ons_deathloc;
         // new joining player or round reset, don't bother checking
         if(spawn_loc == '0 0 0') { return false; }
         if(random_target) { RandomSelection_Init(); }
         for(tmp_entity = ons_worldcplist; tmp_entity; tmp_entity = tmp_entity.ons_worldcpnext)
         {
             if(SAME_TEAM(tmp_entity, player))
             {
                 if(random_target)
                     RandomSelection_AddEnt(tmp_entity, 1, 1);
                 else if(vlen2(tmp_entity.origin - spawn_loc) <= vlen2(closest_target.origin - spawn_loc) || closest_target == NULL)
                     closest_target = tmp_entity;
             }
         }
         if(random_target) { closest_target = RandomSelection_chosen_ent; }
         if(closest_target)
         {
             float i;
             vector loc;
             float iteration_scale = 1;
             for(i = 0; i < 10; ++i)
             {
                 iteration_scale -= i / 10;
                 loc = closest_target.origin + '0 0 96' * iteration_scale;
                 loc += ('0 1 0' * random()) * 128 * iteration_scale;
                 tracebox(loc, STAT(PL_MIN, player), STAT(PL_MAX, player), loc, MOVE_NORMAL, player);
                 if(trace_fraction == 1.0 && !trace_startsolid)
                 {
                     traceline(closest_target.origin, loc, MOVE_NOMONSTERS, closest_target); // double check to make sure we're not spawning outside the NULL
                     if(trace_fraction == 1.0 && !trace_startsolid)
                     {
                         setorigin(player, loc);
                         player.angles = normalize(loc - closest_target.origin) * RAD2DEG;
                         return false;
                     }
                 }
             }
         }
     }
     if(autocvar_g_onslaught_spawn_at_generator)
     if(random() <= autocvar_g_onslaught_spawn_at_generator_chance)
     {
         float random_target = autocvar_g_onslaught_spawn_at_generator_random;
         entity tmp_entity, closest_target = NULL;
         vector spawn_loc = player.ons_deathloc;
         // new joining player or round reset, don't bother checking
         if(spawn_loc == '0 0 0') { return false; }
         if(random_target) { RandomSelection_Init(); }
         for(tmp_entity = ons_worldgeneratorlist; tmp_entity; tmp_entity = tmp_entity.ons_worldgeneratornext)
         {
             if(random_target)
                 RandomSelection_AddEnt(tmp_entity, 1, 1);
             else
             {
                 if(SAME_TEAM(tmp_entity, player))
                 if(vlen2(tmp_entity.origin - spawn_loc) <= vlen2(closest_target.origin - spawn_loc) || closest_target == NULL)
                     closest_target = tmp_entity;
             }
         }
         if(random_target) { closest_target = RandomSelection_chosen_ent; }
         if(closest_target)
         {
             float i;
             vector loc;
             float iteration_scale = 1;
             for(i = 0; i < 10; ++i)
             {
                 iteration_scale -= i / 10;
                 loc = closest_target.origin + '0 0 128' * iteration_scale;
                 loc += ('0 1 0' * random()) * 256 * iteration_scale;
                 tracebox(loc, STAT(PL_MIN, player), STAT(PL_MAX, player), loc, MOVE_NORMAL, player);
                 if(trace_fraction == 1.0 && !trace_startsolid)
                 {
                     traceline(closest_target.origin, loc, MOVE_NOMONSTERS, closest_target); // double check to make sure we're not spawning outside the NULL
                     if(trace_fraction == 1.0 && !trace_startsolid)
                     {
                         setorigin(player, loc);
                         player.angles = normalize(loc - closest_target.origin) * RAD2DEG;
                         return false;
                     }
                 }
             }
         }
     }
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , PlayerDies)
Definition at line 1819 of file sv_onslaught.qc.
References autocvar_g_onslaught_spawn_choose, entity(), M_ARGV, ons_Count_SelfControlPoints(), ons_worldcplist, ons_worldgeneratorlist, and stuffcmd.
 {
     entity frag_target = M_ARGV(2, entity);
     frag_target.ons_deathloc = frag_target.origin;
     entity l;
     for(l = ons_worldgeneratorlist; l; l = l.ons_worldgeneratornext)
     {
         l.sprite.SendFlags |= 16;
     }
     for(l = ons_worldcplist; l; l = l.ons_worldcpnext)
     {
         l.sprite.SendFlags |= 16;
     }
     if ( autocvar_g_onslaught_spawn_choose )
     if ( ons_Count_SelfControlPoints(frag_target) > 1 )
         stuffcmd(frag_target, "qc_cmd_cl hud clickradar\n");
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , MonsterMove)
Definition at line 1841 of file sv_onslaught.qc.
References entity(), find(), M_ARGV, NULL, and targetname.
 {
     entity mon = M_ARGV(0, entity);
     entity e = find(NULL, targetname, mon.target);
     if (e != NULL)
         mon.team = e.team;
 }
MUTATOR_HOOKFUNCTION (ons , MonsterSpawn)
Definition at line 1870 of file sv_onslaught.qc.
References entity(), InitializeEntity(), INITPRIO_FINDTARGET, M_ARGV, ons_MonsterSpawn_Delayed(), and spawn().
 {
     entity mon = M_ARGV(0, entity);
     entity e = spawn();
     e.owner = mon;
     InitializeEntity(e, ons_MonsterSpawn_Delayed, INITPRIO_FINDTARGET);
 }
MUTATOR_HOOKFUNCTION (ons , TurretSpawn)
Definition at line 1900 of file sv_onslaught.qc.
References entity(), InitializeEntity(), INITPRIO_FINDTARGET, M_ARGV, ons_TurretSpawn_Delayed(), and spawn().
 {
     entity turret = M_ARGV(0, entity);
     entity e = spawn();
     e.owner = turret;
     InitializeEntity(e, ons_TurretSpawn_Delayed, INITPRIO_FINDTARGET);
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , HavocBot_ChooseRole)
Definition at line 1911 of file sv_onslaught.qc.
References entity(), havocbot_ons_reset_role(), and M_ARGV.
 {
     entity bot = M_ARGV(0, entity);
     havocbot_ons_reset_role(bot);
     return true;
 }
MUTATOR_HOOKFUNCTION (ons , TeamBalance_CheckAllowedTeams)
Definition at line 1919 of file sv_onslaught.qc.
References entity(), M_ARGV, ons_worldgeneratorlist, Team_IsValidTeam(), and Team_TeamToBit().
 {
     // onslaught is special
     for(entity tmp_entity = ons_worldgeneratorlist; tmp_entity; tmp_entity = tmp_entity.ons_worldgeneratornext)
     {
         if (Team_IsValidTeam(tmp_entity.team))
         {
             M_ARGV(0, float) |= Team_TeamToBit(tmp_entity.team);
         }
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (ons , SpectateCopy)
Definition at line 1933 of file sv_onslaught.qc.
References entity(), and M_ARGV.
 {
     entity spectatee = M_ARGV(0, entity);
     entity client = M_ARGV(1, entity);
     STAT(ROUNDLOST, client) = STAT(ROUNDLOST, spectatee); // make spectators see it too
 }
MUTATOR_HOOKFUNCTION (ons , SV_ParseClientCommand)
Definition at line 1941 of file sv_onslaught.qc.
References argv(), autocvar_g_onslaught_click_radius, autocvar_g_onslaught_teleport_radius, cmd_argc, cmd_name, entity(), GetResource(), IS_PLAYER, M_ARGV, MUTATOR_RETURNVALUE, NULL, ons_Nearest_ControlPoint(), ons_Nearest_ControlPoint_2D(), ons_Teleport(), RES_HEALTH, RESPAWN_FORCE, sprint(), stof(), and vector().
 {
     if(MUTATOR_RETURNVALUE) // command was already handled?
         return false;
     entity player = M_ARGV(0, entity);
     string cmd_name = M_ARGV(1, string);
     int cmd_argc = M_ARGV(2, int);
     if ( cmd_name == "ons_spawn" )
     {
         vector pos = player.origin;
         if(cmd_argc > 1)
             pos_x = stof(argv(1));
         if(cmd_argc > 2)
             pos_y = stof(argv(2));
         if(cmd_argc > 3)
             pos_z = stof(argv(3));
         if ( IS_PLAYER(player) )
         {
             if ( !STAT(FROZEN, player) )
             {
                 entity source_point = ons_Nearest_ControlPoint(player, player.origin, autocvar_g_onslaught_teleport_radius);
                 if ( !source_point && GetResource(player, RES_HEALTH) > 0 )
                 {
                     sprint(player, "\nYou need to be next to a control point\n");
                     return true;
                 }
                 entity closest_target = ons_Nearest_ControlPoint_2D(player, pos, autocvar_g_onslaught_click_radius);
                 if ( closest_target == NULL )
                 {
                     sprint(player, "\nNo control point found\n");
                     return true;
                 }
                 if ( GetResource(player, RES_HEALTH) <= 0 )
                 {
                     player.ons_spawn_by = closest_target;
                     player.respawn_flags = player.respawn_flags | RESPAWN_FORCE;
                 }
                 else
                 {
                     if ( source_point == closest_target )
                     {
                         sprint(player, "\nTeleporting to the same point\n");
                         return true;
                     }
                     if ( !ons_Teleport(player,closest_target,autocvar_g_onslaught_teleport_radius,true) )
                         sprint(player, "\nUnable to teleport there\n");
                 }
                 return true;
             }
             sprint(player, "\nNo teleportation for you\n");
         }
         return true;
     }
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , PlayerUseKey)
Definition at line 2009 of file sv_onslaught.qc.
References autocvar_g_onslaught_teleport_radius, entity(), IS_DEAD, M_ARGV, MUTATOR_RETURNVALUE, ons_Nearest_ControlPoint(), stuffcmd, and time.
 {
     if(MUTATOR_RETURNVALUE || game_stopped) return false;
     entity player = M_ARGV(0, entity);
     if((time > player.teleport_antispam) && (!IS_DEAD(player)) && !player.vehicle)
     {
         entity source_point = ons_Nearest_ControlPoint(player, player.origin, autocvar_g_onslaught_teleport_radius);
         if ( source_point )
         {
             stuffcmd(player, "qc_cmd_cl hud clickradar\n");
             return true;
         }
     }
 }
MUTATOR_HOOKFUNCTION (ons , PlayHitsound)
Definition at line 2026 of file sv_onslaught.qc.
References entity(), and M_ARGV.
 {
     entity frag_victim = M_ARGV(0, entity);
     return (frag_victim.classname == "onslaught_generator" && !frag_victim.isshielded)
         || (frag_victim.classname == "onslaught_controlpoint_icon" && !frag_victim.owner.isshielded);
 }
MUTATOR_HOOKFUNCTION (ons , SendWaypoint)
Definition at line 2034 of file sv_onslaught.qc.
References entity(), GetResource(), M_ARGV, ons_ControlPoint_Attackable(), RES_HEALTH, SAME_TEAM, and to.
 {
     entity wp = M_ARGV(0, entity);
     entity to = M_ARGV(1, entity);
     int sf = M_ARGV(2, int);
     int wp_flag = M_ARGV(3, int);
     if(sf & 16)
     {
         if(wp.owner.classname == "onslaught_controlpoint")
         {
             entity wp_owner = wp.owner;
             entity e = WaypointSprite_getviewentity(to);
             if(SAME_TEAM(e, wp_owner) && GetResource(wp_owner.goalentity, RES_HEALTH) >= wp_owner.goalentity.max_health) { wp_flag |= 2; }
             if(!ons_ControlPoint_Attackable(wp_owner, e.team)) { wp_flag |= 2; }
         }
         if(wp.owner.classname == "onslaught_generator")
         {
             entity wp_owner = wp.owner;
             if(wp_owner.isshielded && GetResource(wp_owner, RES_HEALTH) >= wp_owner.max_health) { wp_flag |= 2; }
             if(GetResource(wp_owner, RES_HEALTH) <= 0) { wp_flag |= 2; }
         }
     }
     M_ARGV(3, int) = wp_flag;
 }
MUTATOR_HOOKFUNCTION (ons , TurretValidateTarget)
Definition at line 2061 of file sv_onslaught.qc.
References entity(), M_ARGV, and substring().
 {
     entity turret_target = M_ARGV(1, entity);
     if(substring(turret_target.classname, 0, 10) == "onslaught_") // don't attack onslaught targets, that's the player's job!
     {
         M_ARGV(3, float) = -3;
         return true;
     }
     return false;
 }
MUTATOR_HOOKFUNCTION (ons , TurretThink)
Definition at line 2074 of file sv_onslaught.qc.
References entity(), find(), M_ARGV, NULL, targetname, and turret_respawn().
 {
     entity turret = M_ARGV(0, entity);
     // ONS uses somewhat backwards linking.
     if(turret.target)
     {
         entity e = find(NULL, targetname, turret.target);
         if (e != NULL)
             turret.team = e.team;
     }
     if(turret.team != turret.tur_head.team)
         turret_respawn(turret);
 }
void nades_Clear (entity e)
Referenced by Onslaught_CheckWinner(), and Onslaught_GetWinnerTeam().
void ons_camSetup (entity this)
Definition at line 850 of file sv_onslaught.qc.
References cam, clientcamera_send(), cos(), DEG2RAD, FOREACH_CLIENT, MOVE_WORLDONLY, MSG_ALL, origin, setorigin(), sin(), trace_fraction, vec2, vector(), WriteAngle(), and WriteByte().
Referenced by ons_GeneratorDamage().
 {
     vector dir;
     vector ang = '0 0 0';
     vector best_ang = '0 0 0';
     float best_trace_fraction = 0;
     while(ang.y < 360)
     {
         dir = vec2(cos(ang.y * DEG2RAD), sin(ang.y * DEG2RAD));
         dir *= 500;
         traceline(this.origin, this.origin - dir, MOVE_WORLDONLY, this);
         if(trace_fraction > best_trace_fraction)
         {
             best_trace_fraction = trace_fraction;
             best_ang = ang;
             if(trace_fraction == 1)
                 break;
         }
         ang.y += 90;
         if(ang.y == 360)
             ang.y = 45;
     }
     cam.origin = this.origin;
     setorigin(cam, cam.origin);
     cam.angles = best_ang;
     Net_LinkEntity(cam, false, 0, clientcamera_send);
     FOREACH_CLIENT(true, it.clientcamera = cam;);
     WriteByte(MSG_ALL, SVC_SETVIEWANGLES);
     WriteAngle(MSG_ALL, cam.angles_x);
     WriteAngle(MSG_ALL, cam.angles_y);
     WriteAngle(MSG_ALL, cam.angles_z);
 }
bool ons_CaptureShield_Customize (entity this, entity client)
Definition at line 49 of file sv_onslaught.qc.
References enemy, entity(), ons_ControlPoint_Attackable(), and SAME_TEAM.
Referenced by ons_CaptureShield_Spawn().
 {
     entity e = WaypointSprite_getviewentity(client);
     if(!this.enemy.isshielded && (ons_ControlPoint_Attackable(this.enemy, e.team) > 0 || this.enemy.classname != "onslaught_controlpoint")) { return false; }
     if(SAME_TEAM(this, e)) { return false; }
     return true;
 }
void ons_CaptureShield_Reset (entity this)
Definition at line 81 of file sv_onslaught.qc.
References colormap, enemy, and team.
Referenced by ons_CaptureShield_Spawn().
 {
     this.colormap = this.enemy.colormap;
     this.team = this.enemy.team;
 }
void ons_CaptureShield_Spawn (entity generator, bool is_generator)
Definition at line 87 of file sv_onslaught.qc.
References EF_ADDITIVE, entity(), IL_PUSH(), MOVETYPE_NOCLIP, ons_CaptureShield_Customize(), ons_CaptureShield_Reset(), ons_CaptureShield_Touch(), set_movetype(), setorigin(), and SOLID_TRIGGER.
Referenced by ons_DelayedControlPoint_Setup(), and ons_DelayedGeneratorSetup().
 {
     entity shield = new(ons_captureshield);
     IL_PUSH(g_onsshields, shield);
     shield.enemy = generator;
     shield.team = generator.team;
     shield.colormap = generator.colormap;
     shield.reset = ons_CaptureShield_Reset;
     settouch(shield, ons_CaptureShield_Touch);
     setcefc(shield, ons_CaptureShield_Customize);
     shield.effects = EF_ADDITIVE;
     set_movetype(shield, MOVETYPE_NOCLIP);
     shield.solid = SOLID_TRIGGER;
     shield.avelocity = '7 0 11';
     shield.scale = 1;
     shield.model = ((is_generator) ? "models/onslaught/generator_shield.md3" : "models/onslaught/controlpoint_shield.md3");
     precache_model(shield.model);
     setorigin(shield, generator.origin);
     _setmodel(shield, shield.model);
     setsize(shield, shield.scale * shield.mins, shield.scale * shield.maxs);
 }
void ons_CaptureShield_Touch (entity this, entity toucher)
Definition at line 59 of file sv_onslaught.qc.
References absmax, absmin, Damage(), DMG_NOWEP, enemy, IS_PLAYER, IS_REAL_CLIENT, normalize(), ons_captureshield_force, ons_ControlPoint_Attackable(), play2(), SAME_TEAM, SND, and vector().
Referenced by ons_CaptureShield_Spawn().
 {
     if(!this.enemy.isshielded && (ons_ControlPoint_Attackable(this.enemy, toucher.team) > 0 || this.enemy.classname != "onslaught_controlpoint")) { return; }
     if(!IS_PLAYER(toucher)) { return; }
     if(SAME_TEAM(toucher, this)) { return; }
     vector mymid = (this.absmin + this.absmax) * 0.5;
     vector theirmid = (toucher.absmin + toucher.absmax) * 0.5;
     Damage(toucher, this, this, 0, DEATH_HURTTRIGGER.m_id, DMG_NOWEP, mymid, normalize(theirmid - mymid) * ons_captureshield_force);
     if(IS_REAL_CLIENT(toucher))
     {
         play2(toucher, SND(ONS_DAMAGEBLOCKEDBYSHIELD));
         if(this.enemy.classname == "onslaught_generator")
             Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_ONS_GENERATOR_SHIELDED);
         else
             Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_ONS_CONTROLPOINT_SHIELDED);
     }
 }
int ons_ControlPoint_Attackable (entity cp, int teamnum)
Definition at line 324 of file sv_onslaught.qc.
References ons_ControlPoint_CanBeLinked().
Referenced by MUTATOR_HOOKFUNCTION(), ons_CaptureShield_Customize(), ons_CaptureShield_Touch(), ons_ControlPoint_Touch(), and ons_ControlPoint_Waypoint().
 {
     int a;
     if(cp.isshielded)
     {
         return 0;
     }
     else if(cp.goalentity)
     {
         // if there's already an icon built, nothing happens
         if(cp.team == teamnum)
         {
             a = ons_ControlPoint_CanBeLinked(cp, teamnum);
             if(a) // attackable by enemy?
                 return -2; // EMERGENCY!
             return -1;
         }
         // we know it can be linked, so no need to check
         // but...
         a = ons_ControlPoint_CanBeLinked(cp, teamnum);
         if(a == 2) // near our generator?
             return 3; // EMERGENCY!
         return 1;
     }
     else
     {
         // free point
         if(ons_ControlPoint_CanBeLinked(cp, teamnum))
         {
             a = ons_ControlPoint_CanBeLinked(cp, teamnum); // why was this here NUM_TEAM_1 + NUM_TEAM_2 - t
             if(a == 2)
                 return 4; // GET THIS ONE NOW!
             else
                 return 2; // TOUCH ME
         }
     }
     return 0;
 }
int ons_ControlPoint_CanBeLinked (entity cp, int teamnum)
Definition at line 316 of file sv_onslaught.qc.
References BIT.
Referenced by ons_ControlPoint_Attackable(), ons_ControlPoint_Icon_BuildThink(), and ons_ControlPoint_UpdateSprite().
 {
     if(cp.aregensneighbor & BIT(teamnum)) return 2;
     if(cp.arecpsneighbor & BIT(teamnum)) return 1;
     return 0;
 }
void ons_ControlPoint_Icon_BuildThink (entity this)
Definition at line 529 of file sv_onslaught.qc.
References APP_TEAM_NUM, ATTEN_NORM, autocvar_g_onslaught_cp_regen, CH_TRIGGER, count, CPSF_SETUP, CPSF_STATUS, EFFECT_CAP(), entity(), GameRules_scoring_add, GameRules_scoring_add_team, GetResource(), GiveResource(), IS_PLAYER, max_health, nextthink, NULL, ons_ControlPoint_CanBeLinked(), ons_ControlPoint_Icon_Think(), ONS_CP_THINKRATE, onslaught_controlpoint_icon_link(), onslaught_updatelinks(), origin, owner, random(), randomvec(), RES_HEALTH, setmodel, SetResourceExplicit(), setthink, solid, SOLID_BBOX, sound, SUB_UseTargets(), time, and VOL_BASE.
Referenced by ons_ControlPoint_Icon_Spawn().
 {
     int a;
     this.nextthink = time + ONS_CP_THINKRATE;
     // only do this if there is power
     a = ons_ControlPoint_CanBeLinked(this.owner, this.owner.team);
     if(!a)
         return;
     GiveResource(this, RES_HEALTH, this.count);
     this.SendFlags |= CPSF_STATUS;
     if (GetResource(this, RES_HEALTH) >= this.max_health)
     {
         SetResourceExplicit(this, RES_HEALTH, this.max_health);
         this.count = autocvar_g_onslaught_cp_regen * ONS_CP_THINKRATE; // slow repair rate from now on
         setthink(this, ons_ControlPoint_Icon_Think);
         sound(this, CH_TRIGGER, SND_ONS_CONTROLPOINT_BUILT, VOL_BASE, ATTEN_NORM);
         this.owner.iscaptured = true;
         this.solid = SOLID_BBOX;
         Send_Effect(EFFECT_CAP(this.owner.team), this.owner.origin, '0 0 0', 1);
         WaypointSprite_UpdateMaxHealth(this.owner.sprite, this.max_health);
         WaypointSprite_UpdateHealth(this.owner.sprite, GetResource(this, RES_HEALTH));
         if(IS_PLAYER(this.owner.ons_toucher))
         {
             if(this.owner.message != "")
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ONSLAUGHT_CAPTURE, this.owner.ons_toucher.netname, this.owner.message);
                 Send_Notification(NOTIF_ALL_EXCEPT, this.owner.ons_toucher, MSG_CENTER, APP_TEAM_NUM(this.owner.ons_toucher.team, CENTER_ONS_CAPTURE_TEAM), this.owner.message);
                 Send_Notification(NOTIF_ONE, this.owner.ons_toucher, MSG_CENTER, CENTER_ONS_CAPTURE, this.owner.message);
             }
             else
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ONSLAUGHT_CAPTURE_NONAME, this.owner.ons_toucher.netname);
                 Send_Notification(NOTIF_ALL_EXCEPT, this.owner.ons_toucher, MSG_CENTER, APP_TEAM_NUM(this.owner.ons_toucher.team, CENTER_ONS_CAPTURE_TEAM_NONAME));
                 Send_Notification(NOTIF_ONE, this.owner.ons_toucher, MSG_CENTER, CENTER_ONS_CAPTURE_NONAME);
             }
             GameRules_scoring_add(this.owner.ons_toucher, ONS_CAPS, 1);
             GameRules_scoring_add_team(this.owner.ons_toucher, SCORE, 10);
         }
         this.owner.ons_toucher = NULL;
         onslaught_updatelinks();
         // Use targets now (somebody make sure this is in the right place..)
         SUB_UseTargets(this.owner, this, NULL);
         this.SendFlags |= CPSF_SETUP;
     }
     if(this.owner.model != MDL_ONS_CP_PAD2.model_str())
         setmodel(this.owner, MDL_ONS_CP_PAD2);
     if(random() < 0.9 - GetResource(this, RES_HEALTH) / this.max_health)
         Send_Effect(EFFECT_RAGE, this.origin + 10 * randomvec(), '0 0 -1', 1);
 }
void ons_ControlPoint_Icon_Damage (entity this, entity inflictor, entity attacker, float damage, int deathtype, .entity weaponentity, vector hitloc, vector force)
Definition at line 371 of file sv_onslaught.qc.
References APP_TEAM_NUM, ATTEN_NORM, CH_TRIGGER, count, CPSF_STATUS, GameRules_scoring_add, GetResource(), IS_PLAYER, NULL, ONS_CP_THINKRATE, ons_notification_time, onslaught_updatelinks(), origin, owner, pain_finished, play2(), play2team(), pointparticles, random(), RES_HEALTH, setmodel, SND, sound, SUB_UseTargets(), TakeResource(), team, time, and VOL_BASE.
Referenced by ons_ControlPoint_Icon_Spawn(), and ons_ControlPoint_Icon_Think().
 {
     if(damage <= 0) { return; }
     if (this.owner.isshielded)
     {
         // this is protected by a shield, so ignore the damage
         if (time > this.pain_finished)
             if (IS_PLAYER(attacker))
             {
                 play2(attacker, SND(ONS_DAMAGEBLOCKEDBYSHIELD));
                 this.pain_finished = time + 1;
                 attacker.typehitsound += 1; // play both sounds (shield is way too quiet)
             }
         return;
     }
     if(IS_PLAYER(attacker))
     if(time - ons_notification_time[this.team] > 10)
     {
         play2team(this.team, SND(ONS_CONTROLPOINT_UNDERATTACK));
         ons_notification_time[this.team] = time;
     }
     TakeResource(this, RES_HEALTH, damage);
     if(this.owner.iscaptured)
         WaypointSprite_UpdateHealth(this.owner.sprite, GetResource(this, RES_HEALTH));
     else
         WaypointSprite_UpdateBuildFinished(this.owner.sprite, time + (this.max_health - GetResource(this, RES_HEALTH)) / (this.count / ONS_CP_THINKRATE));
     this.pain_finished = time + 1;
     // particles on every hit
     pointparticles(EFFECT_SPARKS, hitloc, force*-1, 1);
     //sound on every hit
     if (random() < 0.5)
         sound(this, CH_TRIGGER, SND_ONS_HIT1, VOL_BASE+0.3, ATTEN_NORM);
     else
         sound(this, CH_TRIGGER, SND_ONS_HIT2, VOL_BASE+0.3, ATTEN_NORM);
     if (GetResource(this, RES_HEALTH) < 0)
     {
         sound(this, CH_TRIGGER, SND_GRENADE_IMPACT, VOL_BASE, ATTEN_NORM);
         pointparticles(EFFECT_ROCKET_EXPLODE, this.origin, '0 0 0', 1);
         if (this.owner.message != "")
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(this.team, INFO_ONSLAUGHT_CPDESTROYED), this.owner.message, attacker.netname);
         else
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(this.team, INFO_ONSLAUGHT_CPDESTROYED_NONAME), attacker.netname);
         GameRules_scoring_add(attacker, ONS_TAKES, 1);
         GameRules_scoring_add(attacker, SCORE, 10);
         this.owner.goalentity = NULL;
         this.owner.islinked = false;
         this.owner.iscaptured = false;
         this.owner.team = 0;
         this.owner.colormap = 1024;
         WaypointSprite_UpdateMaxHealth(this.owner.sprite, 0);
         onslaught_updatelinks();
         // Use targets now (somebody make sure this is in the right place..)
         SUB_UseTargets(this.owner, this, NULL);
         this.owner.waslinked = this.owner.islinked;
         if(this.owner.model != "models/onslaught/controlpoint_pad.md3")
             setmodel(this.owner, MDL_ONS_CP_PAD1);
         //setsize(this, '-32 -32 0', '32 32 8');
         delete(this);
     }
     this.SendFlags |= CPSF_STATUS;
 }
bool ons_ControlPoint_Icon_Heal (entity targ, entity inflictor, float amount, float limit)
Definition at line 446 of file sv_onslaught.qc.
References CPSF_STATUS, GetResource(), GiveResourceWithLimit(), ONS_CP_THINKRATE, RES_HEALTH, RES_LIMIT_NONE, and time.
Referenced by ons_ControlPoint_Icon_Spawn().
 {
     float hlth = GetResource(targ, RES_HEALTH);
     float true_limit = ((limit != RES_LIMIT_NONE) ? limit : targ.max_health);
     if (hlth <= 0 || hlth >= true_limit)
         return false;
     GiveResourceWithLimit(targ, RES_HEALTH, amount, true_limit);
     hlth = GetResource(targ, RES_HEALTH);
     if(targ.owner.iscaptured)
         WaypointSprite_UpdateHealth(targ.owner.sprite, hlth);
     else
         WaypointSprite_UpdateBuildFinished(targ.owner.sprite, time + (targ.max_health - hlth) / (targ.count / ONS_CP_THINKRATE));
     targ.SendFlags |= CPSF_STATUS;
     return true;
 }
void ons_ControlPoint_Icon_Spawn (entity cp, entity player)
Definition at line 594 of file sv_onslaught.qc.
References ATTEN_NORM, autocvar_g_onslaught_cp_buildhealth, autocvar_g_onslaught_cp_buildtime, autocvar_g_onslaught_cp_health, CH_TRIGGER, CPICON_MAX, CPICON_MIN, CPICON_OFFSET, DAMAGE_AIM, EFFECT_FLAG_TOUCH(), entity(), g_bot_targets, GetResource(), IL_PUSH(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Icon_Heal(), ONS_CP_THINKRATE, onslaught_controlpoint_icon_link(), RES_HEALTH, setorigin(), SetResourceExplicit(), SOLID_NOT, sound, SPRITERULE_TEAMPLAY, time, and VOL_BASE.
Referenced by ons_ControlPoint_Touch().
 {
     entity e = new(onslaught_controlpoint_icon);
     setsize(e, CPICON_MIN, CPICON_MAX);
     setorigin(e, cp.origin + CPICON_OFFSET);
     e.owner = cp;
     e.max_health = autocvar_g_onslaught_cp_health;
     SetResourceExplicit(e, RES_HEALTH, autocvar_g_onslaught_cp_buildhealth);
     e.solid = SOLID_NOT;
     e.takedamage = DAMAGE_AIM;
     e.bot_attack = true;
     IL_PUSH(g_bot_targets, e);
     e.event_damage = ons_ControlPoint_Icon_Damage;
     e.event_heal = ons_ControlPoint_Icon_Heal;
     e.team = player.team;
     e.colormap = 1024 + (e.team - 1) * 17;
     e.count = (e.max_health - GetResource(e, RES_HEALTH)) * ONS_CP_THINKRATE / autocvar_g_onslaught_cp_buildtime; // how long it takes to build
     sound(e, CH_TRIGGER, SND_ONS_CONTROLPOINT_BUILD, VOL_BASE, ATTEN_NORM);
     cp.goalentity = e;
     cp.team = e.team;
     cp.colormap = e.colormap;
     Send_Effect(EFFECT_FLAG_TOUCH(player.team), e.origin, '0 0 0', 1);
     WaypointSprite_UpdateBuildFinished(cp.sprite, time + (e.max_health - GetResource(e, RES_HEALTH)) / (e.count / ONS_CP_THINKRATE));
     WaypointSprite_UpdateRule(cp.sprite,cp.team,SPRITERULE_TEAMPLAY);
     cp.sprite.SendFlags |= 16;
     onslaught_controlpoint_icon_link(e, ons_ControlPoint_Icon_BuildThink);
 }
void ons_ControlPoint_Icon_Think (entity this)
Definition at line 463 of file sv_onslaught.qc.
References ATTEN_NORM, autocvar_g_onslaught_cp_proxydecap, autocvar_g_onslaught_cp_proxydecap_distance, autocvar_g_onslaught_cp_proxydecap_dps, CH_PAIN, count, CPSF_STATUS, DMG_NOWEP, FOREACH_CLIENT, GetResource(), GiveResourceWithLimit(), IS_DEAD, IS_PLAYER, max_health, nextthink, NULL, ons_ControlPoint_Icon_Damage(), ONS_CP_THINKRATE, origin, owner, pain_finished, random(), randompos(), RES_HEALTH, sound, SUB_UseTargets(), time, vdist, and VOL_BASE.
Referenced by ons_ControlPoint_Icon_BuildThink().
 {
     this.nextthink = time + ONS_CP_THINKRATE;
     if(autocvar_g_onslaught_cp_proxydecap)
     {
         int _enemy_count = 0;
         int _friendly_count = 0;
         FOREACH_CLIENT(IS_PLAYER(it) && !IS_DEAD(it), {
             if(vdist(it.origin - this.origin, <, autocvar_g_onslaught_cp_proxydecap_distance))
             {
                 if(SAME_TEAM(it, this))
                     ++_friendly_count;
                 else
                     ++_enemy_count;
             }
         });
         _friendly_count = _friendly_count * (autocvar_g_onslaught_cp_proxydecap_dps * ONS_CP_THINKRATE);
         _enemy_count = _enemy_count * (autocvar_g_onslaught_cp_proxydecap_dps * ONS_CP_THINKRATE);
         GiveResourceWithLimit(this, RES_HEALTH, (_friendly_count - _enemy_count), this.max_health);
         this.SendFlags |= CPSF_STATUS;
         if(GetResource(this, RES_HEALTH) <= 0)
         {
             ons_ControlPoint_Icon_Damage(this, this, this, 1, 0, DMG_NOWEP, this.origin, '0 0 0');
             return;
         }
     }
     if (time > this.pain_finished + 5)
     {
         if(GetResource(this, RES_HEALTH) < this.max_health)
         {
             GiveResourceWithLimit(this, RES_HEALTH, this.count, this.max_health);
             WaypointSprite_UpdateHealth(this.owner.sprite, GetResource(this, RES_HEALTH));
         }
     }
     if(this.owner.islinked != this.owner.waslinked)
     {
         // unteam the spawnpoint if needed
         int t = this.owner.team;
         if(!this.owner.islinked)
             this.owner.team = 0;
         SUB_UseTargets(this.owner, this, NULL);
         this.owner.team = t;
         this.owner.waslinked = this.owner.islinked;
     }
     // damaged fx
     if(random() < 0.6 - GetResource(this, RES_HEALTH) / this.max_health)
     {
         Send_Effect(EFFECT_ELECTRIC_SPARKS, this.origin + randompos('-10 -10 -20', '10 10 20'), '0 0 0', 1);
         if(random() > 0.8)
             sound(this, CH_PAIN, SND_ONS_SPARK1, VOL_BASE, ATTEN_NORM);
         else if (random() > 0.5)
             sound(this, CH_PAIN, SND_ONS_SPARK2, VOL_BASE, ATTEN_NORM);
     }
 }
void ons_ControlPoint_Reset (entity this)
Definition at line 732 of file sv_onslaught.qc.
References colormap, goalentity, iscaptured, islinked, isshielded, nextthink, NULL, ons_ControlPoint_Think(), ONS_CP_THINKRATE, ons_toucher, onslaught_updatelinks(), setmodel, setthink, sprite, SPRITERULE_TEAMPLAY, SUB_UseTargets(), team, and time.
Referenced by ons_ControlPoint_Setup().
 {
     if(this.goalentity)
         delete(this.goalentity);
     this.goalentity = NULL;
     this.team = 0;
     this.colormap = 1024;
     this.iscaptured = false;
     this.islinked = false;
     this.isshielded = true;
     setthink(this, ons_ControlPoint_Think);
     this.ons_toucher = NULL;
     this.nextthink = time + ONS_CP_THINKRATE;
     setmodel(this, MDL_ONS_CP_PAD1);
     WaypointSprite_UpdateMaxHealth(this.sprite, 0);
     WaypointSprite_UpdateRule(this.sprite,this.team,SPRITERULE_TEAMPLAY);
     onslaught_updatelinks();
     SUB_UseTargets(this, this, NULL); // to reset the structures, playerspawns etc.
     CSQCMODEL_AUTOUPDATE(this);
 }
void ons_ControlPoint_Setup (entity cp)
Definition at line 768 of file sv_onslaught.qc.
References CPGEN_WAYPOINT_OFFSET, droptofloor, InitializeEntity(), INITPRIO_SETLOCATION, MOVETYPE_NONE, MOVETYPE_TOSS, ons_ControlPoint_Reset(), ons_ControlPoint_Think(), ons_ControlPoint_Touch(), ONS_CP_THINKRATE, ons_DelayedControlPoint_Setup(), ons_worldcplist, set_movetype(), setmodel, setorigin(), setthink, SOLID_BBOX, sprite, SPRITERULE_TEAMPLAY, and time.
Referenced by spawnfunc().
 {
     // main setup
     cp.ons_worldcpnext = ons_worldcplist; // link control point into ons_worldcplist
     ons_worldcplist = cp;
     cp.netname = "Control point";
     cp.team = 0;
     cp.solid = SOLID_BBOX;
     set_movetype(cp, MOVETYPE_NONE);
     settouch(cp, ons_ControlPoint_Touch);
     setthink(cp, ons_ControlPoint_Think);
     cp.nextthink = time + ONS_CP_THINKRATE;
     cp.reset = ons_ControlPoint_Reset;
     cp.colormap = 1024;
     cp.iscaptured = false;
     cp.islinked = false;
     cp.isshielded = true;
     // appearence
     setmodel(cp, MDL_ONS_CP_PAD1);
     // control point placement
     if((cp.spawnflags & 1) || cp.noalign) // don't drop to floor, just stay at fixed location
     {
         cp.noalign = true;
         set_movetype(cp, MOVETYPE_NONE);
     }
     else // drop to floor, automatically find a platform and set that as spawn origin
     {
         setorigin(cp, cp.origin + '0 0 20');
         cp.noalign = false;
         droptofloor(cp);
         set_movetype(cp, MOVETYPE_TOSS);
     }
     // waypointsprites
     WaypointSprite_SpawnFixed(WP_Null, cp.origin + CPGEN_WAYPOINT_OFFSET, cp, sprite, RADARICON_NONE);
     WaypointSprite_UpdateRule(cp.sprite, cp.team, SPRITERULE_TEAMPLAY);
     InitializeEntity(cp, ons_DelayedControlPoint_Setup, INITPRIO_SETLOCATION);
 }
void ons_ControlPoint_Think (entity this)
Definition at line 726 of file sv_onslaught.qc.
References nextthink, ONS_CP_THINKRATE, and time.
Referenced by ons_ControlPoint_Reset(), and ons_ControlPoint_Setup().
 {
     this.nextthink = time + ONS_CP_THINKRATE;
     CSQCMODEL_AUTOUPDATE(this);
 }
void ons_ControlPoint_Touch (entity this, entity toucher)
Definition at line 689 of file sv_onslaught.qc.
References autocvar_g_onslaught_allow_vehicle_touch, IS_DEAD, IS_PLAYER, IS_VEHICLE, iscaptured, ons_ControlPoint_Attackable(), ons_ControlPoint_Icon_Spawn(), ons_toucher, onslaught_updatelinks(), rint(), SAME_TEAM, and time.
Referenced by ons_ControlPoint_Setup().
 {
     int attackable;
     if(IS_VEHICLE(toucher) && toucher.owner)
     {
         if (!autocvar_g_onslaught_allow_vehicle_touch)
             return;
         toucher = toucher.owner;
     }
     if(!IS_PLAYER(toucher)) { return; }
     if(STAT(FROZEN, toucher)) { return; }
     if(IS_DEAD(toucher)) { return; }
     if ( SAME_TEAM(this,toucher) )
     if ( this.iscaptured )
     {
         if(time <= toucher.teleport_antispam)
             Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_ONS_TELEPORT_ANTISPAM, rint(toucher.teleport_antispam - time));
         else
             Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_ONS_TELEPORT);
     }
     attackable = ons_ControlPoint_Attackable(this, toucher.team);
     if(attackable != 2 && attackable != 4)
         return;
     // we've verified that this player has a legitimate claim to this point,
     // so start building the captured point icon (which only captures this
     // point if it successfully builds without being destroyed first)
     ons_ControlPoint_Icon_Spawn(this, toucher);
     this.ons_toucher = toucher;
     onslaught_updatelinks();
 }
void ons_ControlPoint_UpdateSprite (entity e)
Definition at line 645 of file sv_onslaught.qc.
References colormapPaletteColor, entity(), GetResource(), NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, ons_ControlPoint_CanBeLinked(), ons_ControlPoint_Waypoint(), RES_HEALTH, and s1.
Referenced by onslaught_updatelinks().
 {
     entity s1 = ons_ControlPoint_Waypoint(e);
     WaypointSprite_UpdateSprites(e.sprite, s1, s1, s1);
     bool sh;
     sh = !(ons_ControlPoint_CanBeLinked(e, NUM_TEAM_1) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_2) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_3) || ons_ControlPoint_CanBeLinked(e, NUM_TEAM_4));
     if(e.lastteam != e.team + 2 || e.lastshielded != sh || e.iscaptured != e.lastcaptured)
     {
         if(e.iscaptured) // don't mess up build bars!
         {
             if(sh)
             {
                 WaypointSprite_UpdateMaxHealth(e.sprite, 0);
             }
             else
             {
                 WaypointSprite_UpdateMaxHealth(e.sprite, e.goalentity.max_health);
                 WaypointSprite_UpdateHealth(e.sprite, GetResource(e.goalentity, RES_HEALTH));
             }
         }
         if(e.lastshielded)
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, 0.5 * colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, '0.5 0.5 0.5');
         }
         else
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_CONTROLPOINT, '0.75 0.75 0.75');
         }
         WaypointSprite_Ping(e.sprite);
         e.lastteam = e.team + 2;
         e.lastshielded = sh;
         e.lastcaptured = e.iscaptured;
     }
 }
entity ons_ControlPoint_Waypoint (entity e)
Definition at line 629 of file sv_onslaught.qc.
References ons_ControlPoint_Attackable().
Referenced by ons_ControlPoint_UpdateSprite().
 {
     if(e.team)
     {
         int a = ons_ControlPoint_Attackable(e, e.team);
         if(a == -2) { return WP_OnsCPDefend; } // defend now
         if(a == -1 || a == 1 || a == 2) { return WP_OnsCP; } // touch
         if(a == 3 || a == 4) { return WP_OnsCPAttack; } // attack
     }
     else
         return WP_OnsCP;
     return WP_Null;
 }
int ons_Count_SelfControlPoints (entity this)
find the number of control points and generators in the same team as this
Definition at line 1580 of file sv_onslaught.qc.
References entity(), ons_worldcplist, ons_worldgeneratorlist, and SAME_TEAM.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     int n = 0;
     for(entity cp = ons_worldcplist; cp; cp = cp.ons_worldcpnext)
     {
         if(SAME_TEAM(cp, this))
         if(cp.iscaptured)
             n++;
     }
     for(entity gen = ons_worldgeneratorlist; gen; gen = gen.ons_worldgeneratornext)
     {
         if(SAME_TEAM(gen, this))
             n++;
     }
     return n;
 }
void ons_DelayedControlPoint_Setup (entity this)
Definition at line 758 of file sv_onslaught.qc.
References ons_CaptureShield_Spawn(), and onslaught_updatelinks().
Referenced by ons_ControlPoint_Setup().
 {
     onslaught_updatelinks();
     // captureshield setup
     ons_CaptureShield_Spawn(this, false);
     CSQCMODEL_AUTOINIT(this);
 }
void ons_DelayedGeneratorSetup (entity this)
Definition at line 1037 of file sv_onslaught.qc.
References bot_basewaypoint, generator_send(), nearestwaypoint, nearestwaypointtimeout, ons_CaptureShield_Spawn(), onslaught_updatelinks(), origin, and waypoint_spawnforitem_force().
Referenced by ons_GeneratorSetup().
 {
     // bot waypoints
     waypoint_spawnforitem_force(this, this.origin);
     this.nearestwaypointtimeout = 0; // activate waypointing again
     this.bot_basewaypoint = this.nearestwaypoint;
     // captureshield setup
     ons_CaptureShield_Spawn(this, true);
     onslaught_updatelinks();
     Net_LinkEntity(this, false, 0, generator_send);
 }
void ons_DelayedInit (entity this)
Definition at line 2166 of file sv_onslaught.qc.
References autocvar_g_onslaught_round_timelimit, autocvar_g_onslaught_warmup, ons_ScoreRules(), Onslaught_CheckPlayers(), Onslaught_CheckWinner(), Onslaught_RoundStart(), round_handler_Init(), and round_handler_Spawn().
Referenced by ons_Initialize().
 {
     ons_ScoreRules();
     round_handler_Spawn(Onslaught_CheckPlayers, Onslaught_CheckWinner, Onslaught_RoundStart);
     round_handler_Init(5, autocvar_g_onslaught_warmup, autocvar_g_onslaught_round_timelimit);
 }
void ons_DelayedLinkSetup (entity this)
Definition at line 298 of file sv_onslaught.qc.
References enemy, etos(), find(), goalentity, LOG_DEBUG, nextthink, NULL, objerror(), ons_Link_CheckUpdate(), setthink, target, target2, targetname, and time.
Referenced by spawnfunc().
 {
     this.goalentity = find(NULL, targetname, this.target);
     this.enemy = find(NULL, targetname, this.target2);
     if(!this.goalentity) { objerror(this, "can not find target\n"); }
     if(!this.enemy) { objerror(this, "can not find target2\n"); }
     LOG_DEBUG(etos(this.goalentity), " linked with ", etos(this.enemy));
     this.SendFlags |= 3;
     setthink(this, ons_Link_CheckUpdate);
     this.nextthink = time;
 }
void ons_Generator_UpdateSprite (entity e)
Definition at line 823 of file sv_onslaught.qc.
References colormapPaletteColor, entity(), ons_Generator_Waypoint(), and s1.
Referenced by onslaught_updatelinks().
 {
     entity s1 = ons_Generator_Waypoint(e);
     WaypointSprite_UpdateSprites(e.sprite, s1, s1, s1);
     if(e.lastteam != e.team + 2 || e.lastshielded != e.isshielded)
     {
         e.lastteam = e.team + 2;
         e.lastshielded = e.isshielded;
         if(e.lastshielded)
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, 0.5 * colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, '0.5 0.5 0.5');
         }
         else
         {
             if(e.team)
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, colormapPaletteColor(e.team - 1, false));
             else
                 WaypointSprite_UpdateTeamRadar(e.sprite, RADARICON_GENERATOR, '0.75 0.75 0.75');
         }
         WaypointSprite_Ping(e.sprite);
     }
 }
entity ons_Generator_Waypoint (entity e)
Definition at line 816 of file sv_onslaught.qc.
Referenced by ons_Generator_UpdateSprite().
 {
     if (e.isshielded)
         return WP_OnsGenShielded;
     return WP_OnsGen;
 }
void ons_GeneratorDamage (entity this, entity inflictor, entity attacker, float damage, int deathtype, .entity weaponentity, vector hitloc, vector force)
Definition at line 885 of file sv_onslaught.qc.
References APP_TEAM_NUM, ATTEN_NORM, bound(), CH_TRIGGER, count, DAMAGE_NO, FOREACH_CLIENT, frame, func_null(), GameRules_scoring_add, GetResource(), GSF_STATUS, IS_PLAYER, IS_REAL_CLIENT, iscaptured, islinked, isshielded, lasthealth, max_health, nextthink, NULL, ons_camSetup(), onslaught_updatelinks(), pain_finished, play2(), play2team(), random(), RES_HEALTH, round_handler_IsRoundStarted, SAME_TEAM, setthink, SND, sound, sprite, takedamage, TakeResource(), team, time, VOL_BASE, and warmup_stage.
Referenced by ons_GeneratorReset(), and ons_GeneratorSetup().
 {
     if(damage <= 0) return;
     if(warmup_stage || game_stopped) return;
     if(!round_handler_IsRoundStarted()) return;
     if (attacker != this)
     {
         if (this.isshielded)
         {
             // generator is protected by a shield, so ignore the damage
             if (time > this.pain_finished)
                 if (IS_PLAYER(attacker))
                 {
                     play2(attacker, SND(ONS_DAMAGEBLOCKEDBYSHIELD));
                     attacker.typehitsound += 1;
                     this.pain_finished = time + 1;
                 }
             return;
         }
         if (time > this.pain_finished)
         {
             this.pain_finished = time + 10;
             FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it) && SAME_TEAM(it, this), Send_Notification(NOTIF_ONE, it, MSG_CENTER, CENTER_GENERATOR_UNDERATTACK));
             play2team(this.team, SND(ONS_GENERATOR_UNDERATTACK));
         }
     }
     TakeResource(this, RES_HEALTH, damage);
     float hlth = GetResource(this, RES_HEALTH);
     WaypointSprite_UpdateHealth(this.sprite, hlth);
     // choose an animation frame based on health
     this.frame = 10 * bound(0, (1 - hlth / this.max_health), 1);
     // see if the generator is still functional, or dying
     if (hlth > 0)
     {
         this.lasthealth = hlth;
     }
     else
     {
         if (attacker == this)
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(this.team, INFO_ONSLAUGHT_GENDESTROYED_OVERTIME));
         else
         {
             Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(this.team, INFO_ONSLAUGHT_GENDESTROYED));
             GameRules_scoring_add(attacker, SCORE, 100);
         }
         this.iscaptured = false;
         this.islinked = false;
         this.isshielded = false;
         this.takedamage = DAMAGE_NO; // can't be hurt anymore
         this.event_damage = func_null; // won't do anything if hurt
         this.event_heal = func_null;
         this.count = 0; // reset counter
         setthink(this, func_null);
         this.nextthink = 0;
         //this.think(); // do the first explosion now
         WaypointSprite_UpdateMaxHealth(this.sprite, 0);
         WaypointSprite_Ping(this.sprite);
         //WaypointSprite_Kill(this.sprite); // can't do this yet, code too poor
         onslaught_updatelinks();
         ons_camSetup(this);
     }
     // Throw some flaming gibs on damage, more damage = more chance for gib
     if(random() < damage/220)
     {
         sound(this, CH_TRIGGER, SND_ROCKET_IMPACT, VOL_BASE, ATTEN_NORM);
     }
     else
     {
         // particles on every hit
         Send_Effect(EFFECT_SPARKS, hitloc, force * -1, 1);
         //sound on every hit
         if (random() < 0.5)
             sound(this, CH_TRIGGER, SND_ONS_HIT1, VOL_BASE, ATTEN_NORM);
         else
             sound(this, CH_TRIGGER, SND_ONS_HIT2, VOL_BASE, ATTEN_NORM);
     }
     this.SendFlags |= GSF_STATUS;
 }
bool ons_GeneratorHeal (entity targ, entity inflictor, float amount, float limit)
Definition at line 971 of file sv_onslaught.qc.
References bound(), GetResource(), GiveResourceWithLimit(), GSF_STATUS, RES_HEALTH, and RES_LIMIT_NONE.
Referenced by ons_GeneratorReset(), and ons_GeneratorSetup().
 {
     float true_limit = ((limit != RES_LIMIT_NONE) ? limit : targ.max_health);
     float hlth = GetResource(targ, RES_HEALTH);
     if (hlth <= 0 || hlth >= true_limit)
         return false;
     GiveResourceWithLimit(targ, RES_HEALTH, amount, true_limit);
     hlth = GetResource(targ, RES_HEALTH);
     WaypointSprite_UpdateHealth(targ.sprite, hlth);
     targ.frame = 10 * bound(0, (1 - hlth / targ.max_health), 1);
     targ.lasthealth = hlth;
     targ.SendFlags |= GSF_STATUS;
     return true;
 }
void ons_GeneratorReset (entity this)
Definition at line 1008 of file sv_onslaught.qc.
References autocvar_g_onslaught_gen_health, bot_attack, DAMAGE_AIM, g_bot_targets, GEN_THINKRATE, generator_send(), GetResource(), GSF_SETUP, GSF_STATUS, IL_CONTAINS(), IL_PUSH(), iscaptured, islinked, isshielded, lasthealth, max_health, nextthink, ons_GeneratorDamage(), ons_GeneratorHeal(), ons_GeneratorThink(), onslaught_updatelinks(), RES_HEALTH, SetResourceExplicit(), setthink, sprite, SPRITERULE_TEAMPLAY, takedamage, team, team_saved, and time.
Referenced by ons_GeneratorSetup().
 {
     this.team = this.team_saved;
     SetResourceExplicit(this, RES_HEALTH, autocvar_g_onslaught_gen_health);
     this.lasthealth = this.max_health = autocvar_g_onslaught_gen_health;
     this.takedamage = DAMAGE_AIM;
     this.bot_attack = true;
     if(!IL_CONTAINS(g_bot_targets, this))
         IL_PUSH(g_bot_targets, this);
     this.iscaptured = true;
     this.islinked = true;
     this.isshielded = true;
     this.event_damage = ons_GeneratorDamage;
     this.event_heal = ons_GeneratorHeal;
     setthink(this, ons_GeneratorThink);
     this.nextthink = time + GEN_THINKRATE;
     Net_LinkEntity(this, false, 0, generator_send);
     this.SendFlags = GSF_SETUP; // just incase
     this.SendFlags |= GSF_STATUS;
     WaypointSprite_UpdateMaxHealth(this.sprite, this.max_health);
     WaypointSprite_UpdateHealth(this.sprite, GetResource(this, RES_HEALTH));
     WaypointSprite_UpdateRule(this.sprite,this.team,SPRITERULE_TEAMPLAY);
     onslaught_updatelinks();
 }
void ons_GeneratorSetup (entity gen)
Definition at line 1063 of file sv_onslaught.qc.
References autocvar_g_onslaught_gen_health, CPGEN_SPAWN_OFFSET, CPGEN_WAYPOINT_OFFSET, DAMAGE_AIM, droptofloor, g_bot_targets, g_saved_team, GEN_THINKRATE, GENERATOR_MAX, GENERATOR_MIN, GetResource(), IL_PUSH(), InitializeEntity(), INITPRIO_SETLOCATION, MOVETYPE_NONE, ons_DelayedGeneratorSetup(), ons_GeneratorDamage(), ons_GeneratorHeal(), ons_GeneratorReset(), ons_GeneratorThink(), ons_worldgeneratorlist, onslaught_generator_touch(), RES_HEALTH, set_movetype(), setorigin(), SetResourceExplicit(), setthink, SOLID_BBOX, sprite, SPRITERULE_TEAMPLAY, Team_ColoredFullName, and time.
Referenced by spawnfunc().
 {
     // declarations
     int teamnum = gen.team;
     // main setup
     gen.ons_worldgeneratornext = ons_worldgeneratorlist; // link generator into ons_worldgeneratorlist
     ons_worldgeneratorlist = gen;
     gen.netname = sprintf("%s generator", Team_ColoredFullName(teamnum));
     gen.classname = "onslaught_generator";
     gen.solid = SOLID_BBOX;
     gen.team_saved = teamnum;
     IL_PUSH(g_saved_team, gen);
     set_movetype(gen, MOVETYPE_NONE);
     gen.lasthealth = gen.max_health = autocvar_g_onslaught_gen_health;
     SetResourceExplicit(gen, RES_HEALTH, autocvar_g_onslaught_gen_health);
     gen.takedamage = DAMAGE_AIM;
     gen.bot_attack = true;
     IL_PUSH(g_bot_targets, gen);
     gen.event_damage = ons_GeneratorDamage;
     gen.event_heal = ons_GeneratorHeal;
     gen.reset = ons_GeneratorReset;
     setthink(gen, ons_GeneratorThink);
     gen.nextthink = time + GEN_THINKRATE;
     gen.iscaptured = true;
     gen.islinked = true;
     gen.isshielded = true;
     settouch(gen, onslaught_generator_touch);
     // appearence
     // model handled by CSQC
     setsize(gen, GENERATOR_MIN, GENERATOR_MAX);
     setorigin(gen, (gen.origin + CPGEN_SPAWN_OFFSET));
     gen.colormap = 1024 + (teamnum - 1) * 17;
     // generator placement
     droptofloor(gen);
     // waypointsprites
     WaypointSprite_SpawnFixed(WP_Null, gen.origin + CPGEN_WAYPOINT_OFFSET, gen, sprite, RADARICON_NONE);
     WaypointSprite_UpdateRule(gen.sprite, gen.team, SPRITERULE_TEAMPLAY);
     WaypointSprite_UpdateMaxHealth(gen.sprite, gen.max_health);
     WaypointSprite_UpdateHealth(gen.sprite, GetResource(gen, RES_HEALTH));
     InitializeEntity(gen, ons_DelayedGeneratorSetup, INITPRIO_SETLOCATION);
 }
void ons_GeneratorThink (entity this)
Definition at line 987 of file sv_onslaught.qc.
References APP_TEAM_NUM, ATTEN_NONE, CHAN_AUTO, FOREACH_CLIENT, GEN_THINKRATE, IS_PLAYER, IS_REAL_CLIENT, isshielded, msg_entity, MSG_ONE, nextthink, SAME_TEAM, SND, soundto(), team, time, VOL_BASE, and wait.
Referenced by ons_GeneratorReset(), and ons_GeneratorSetup().
 {
     this.nextthink = time + GEN_THINKRATE;
     if (game_stopped || this.isshielded || time < this.wait)
         return;
     this.wait = time + 5;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it),
     {
         if (SAME_TEAM(it, this))
         {
             Send_Notification(NOTIF_ONE, it, MSG_CENTER, CENTER_ONS_NOTSHIELDED_TEAM);
             msg_entity = it;
             soundto(MSG_ONE, this, CHAN_AUTO, SND(ONS_GENERATOR_ALARM), VOL_BASE, ATTEN_NONE, 0);
         }
         else
             Send_Notification(NOTIF_ONE, it, MSG_CENTER, APP_TEAM_NUM(this.team, CENTER_ONS_NOTSHIELDED));
     });
 }
void ons_Initialize ()
Definition at line 2174 of file sv_onslaught.qc.
References autocvar_g_onslaught_shield_force, cam, g_onslaught, InitializeEntity(), INITPRIO_GAMETYPE, NULL, ons_captureshield_force, and ons_DelayedInit().
Referenced by REGISTER_MUTATOR().
 {
     g_onslaught = true;
     ons_captureshield_force = autocvar_g_onslaught_shield_force;
     cam = new(objective_camera);
     InitializeEntity(NULL, ons_DelayedInit, INITPRIO_GAMETYPE);
 }
void ons_Link_CheckUpdate (entity this)
Definition at line 279 of file sv_onslaught.qc.
References clientcolors, enemy, goalentity, nextthink, and time.
Referenced by ons_DelayedLinkSetup().
 {
     // TODO check if the two sides have moved (currently they won't move anyway)
     float cc = 0, cc1 = 0, cc2 = 0;
     if(this.goalentity.islinked || this.goalentity.iscaptured) { cc1 = (this.goalentity.team - 1) * 0x01; }
     if(this.enemy.islinked || this.enemy.iscaptured) { cc2 = (this.enemy.team - 1) * 0x10; }
     cc = cc1 + cc2;
     if(cc != this.clientcolors)
     {
         this.clientcolors = cc;
         this.SendFlags |= 4;
     }
     this.nextthink = time;
 }
bool ons_Link_Send (entity this, entity to, int sendflags)
Definition at line 260 of file sv_onslaught.qc.
References clientcolors, enemy, goalentity, and WriteByte().
Referenced by spawnfunc().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_RADARLINK);
     WriteByte(MSG_ENTITY, sendflags);
     if(sendflags & 1)
     {
         WriteVector(MSG_ENTITY, this.goalentity.origin);
     }
     if(sendflags & 2)
     {
         WriteVector(MSG_ENTITY, this.enemy.origin);
     }
     if(sendflags & 4)
     {
         WriteByte(MSG_ENTITY, this.clientcolors); // which is goalentity's color + enemy's color * 16
     }
     return true;
 }
void ons_MonsterSpawn_Delayed (entity this)
Definition at line 1850 of file sv_onslaught.qc.
References entity(), find(), NULL, owner, and target.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity own = this.owner;
     if(!own) { delete(this); return; }
     if(own.targetname)
     {
         entity e = find(NULL, target, own.targetname);
         if(e != NULL)
         {
             own.team = e.team;
             own.use(own, e, NULL);
         }
     }
     delete(this);
 }
entity ons_Nearest_ControlPoint (entity this, vector pos, float max_dist)
Definition at line 1512 of file sv_onslaught.qc.
References entity(), NULL, ons_worldcplist, ons_worldgeneratorlist, SAME_TEAM, vdist, and vlen2.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity closest_target = NULL;
     for(entity cp = ons_worldcplist; cp; cp = cp.ons_worldcpnext)
     {
         if(SAME_TEAM(cp, this))
         if(cp.iscaptured)
         if(max_dist <= 0 || vdist(cp.origin - pos, <=, max_dist))
         if(vlen2(cp.origin - pos) <= vlen2(closest_target.origin - pos) || closest_target == NULL)
             closest_target = cp;
     }
     for(entity gen = ons_worldgeneratorlist; gen; gen = gen.ons_worldgeneratornext)
     {
         if(SAME_TEAM(gen, this))
         if(max_dist <= 0 || vdist(gen.origin - pos, <, max_dist))
         if(vlen2(gen.origin - pos) <= vlen2(closest_target.origin - pos) || closest_target == NULL)
             closest_target = gen;
     }
     return closest_target;
 }
entity ons_Nearest_ControlPoint_2D (entity this, vector pos, float max_dist)
Definition at line 1539 of file sv_onslaught.qc.
References entity(), NULL, ons_worldcplist, ons_worldgeneratorlist, SAME_TEAM, vector(), and vlen().
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity closest_target = NULL;
     vector delta;
     float smallest_distance = 0, distance;
     for(entity cp = ons_worldcplist; cp; cp = cp.ons_worldcpnext)
     {
         delta = cp.origin - pos;
         delta_z = 0;
         distance = vlen(delta);
         if(SAME_TEAM(cp, this))
         if(cp.iscaptured)
         if(max_dist <= 0 || distance <= max_dist)
         if(closest_target == NULL || distance <= smallest_distance )
         {
             closest_target = cp;
             smallest_distance = distance;
         }
     }
     for(entity gen = ons_worldgeneratorlist; gen; gen = gen.ons_worldgeneratornext)
     {
         delta = gen.origin - pos;
         delta_z = 0;
         distance = vlen(delta);
         if(SAME_TEAM(gen, this))
         if(max_dist <= 0 || distance <= max_dist)
         if(closest_target == NULL || distance <= smallest_distance )
         {
             closest_target = gen;
             smallest_distance = distance;
         }
     }
     return closest_target;
 }
void ons_ScoreRules ()
Definition at line 2154 of file sv_onslaught.qc.
References entity(), GameRules_scoring, NULL, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_SECONDARY, ST_ONS_CAPS, TeamBalance_CheckAllowedTeams(), TeamBalance_Destroy(), TeamBalance_GetAllowedTeams(), and teams.
Referenced by ons_DelayedInit().
 {
     entity balance = TeamBalance_CheckAllowedTeams(NULL);
     int teams = TeamBalance_GetAllowedTeams(balance);
     TeamBalance_Destroy(balance);
     GameRules_scoring(teams, SFL_SORT_PRIO_PRIMARY, 0, {
         field_team(ST_ONS_CAPS, "destroyed", SFL_SORT_PRIO_PRIMARY);
         field(SP_ONS_CAPS, "caps", SFL_SORT_PRIO_SECONDARY);
         field(SP_ONS_TAKES, "takes", 0);
     });
 }
bool ons_Teleport (entity player, entity tele_target, float range, bool tele_effects)
Teleport player to a random position near tele_target if tele_effects is true, teleport sound+particles are created return false on failure.
Definition at line 1602 of file sv_onslaught.qc.
References ATTEN_NORM, autocvar_g_onslaught_teleport_wait, bot_aim_reset(), CH_TRIGGER, cos(), IS_BOT_CLIENT, M_PI, makevectors, MOVE_NOMONSTERS, MOVE_NORMAL, RAD2DEG, random(), setorigin(), sin(), sound, time, trace_fraction, trace_startsolid, v_forward, vector(), and VOL_BASE.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     if ( !tele_target )
         return false;
     int i;
     vector loc;
     float theta;
     // narrow the range for each iteration to increase chances that a spawnpoint
     // can be found even if there's little room around the control point
     float iteration_scale = 1;
     for(i = 0; i < 16; ++i)
     {
         iteration_scale -= i / 16;
         theta = random() * 2 * M_PI;
         loc_y = sin(theta);
         loc_x = cos(theta);
         loc_z = 0;
         loc *= random() * range * iteration_scale;
         loc += tele_target.origin + '0 0 128' * iteration_scale;
         tracebox(loc, STAT(PL_MIN, player), STAT(PL_MAX, player), loc, MOVE_NORMAL, player);
         if(trace_fraction == 1.0 && !trace_startsolid)
         {
             traceline(tele_target.origin, loc, MOVE_NOMONSTERS, tele_target); // double check to make sure we're not spawning outside the NULL
             if(trace_fraction == 1.0 && !trace_startsolid)
             {
                 if ( tele_effects )
                 {
                     Send_Effect(EFFECT_TELEPORT, player.origin, '0 0 0', 1);
                     sound (player, CH_TRIGGER, SND_TELEPORT, VOL_BASE, ATTEN_NORM);
                 }
                 setorigin(player, loc);
                 player.angles = '0 1 0' * ( theta * RAD2DEG + 180 );
                 makevectors(player.angles);
                 player.fixangle = true;
                 if (IS_BOT_CLIENT(player))
                 {
                     player.v_angle = player.angles;
                     bot_aim_reset(player);
                 }
                 player.teleport_antispam = time + autocvar_g_onslaught_teleport_wait;
                 if ( tele_effects )
                     Send_Effect(EFFECT_TELEPORT, player.origin + v_forward * 32, '0 0 0', 1);
                 return true;
             }
         }
     }
     return false;
 }
void ons_TurretSpawn_Delayed (entity this)
Definition at line 1879 of file sv_onslaught.qc.
References ACTIVE_NOT, entity(), find(), NULL, owner, and target.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     entity own = this.owner;
     if(!own) { delete(this); return; }
     if(own.targetname)
     {
         entity e = find(NULL, target, own.targetname);
         if(e != NULL)
         {
             own.team = e.team;
             own.active = ACTIVE_NOT;
             own.use(own, e, NULL);
         }
     }
     delete(this);
 }
bool Onslaught_CheckPlayers ()
Definition at line 1247 of file sv_onslaught.qc.
Referenced by ons_DelayedInit().
 {
     return 1;
 }
bool Onslaught_CheckWinner ()
Definition at line 1166 of file sv_onslaught.qc.
References APP_TEAM_NUM, ATTEN_NONE, autocvar__campaign_testrun, autocvar_g_campaign, autocvar_g_onslaught_round_timelimit, autocvar_g_onslaught_warmup, autocvar_timelimit, autocvar_timelimit_suddendeath, CH_INFO, Damage(), DIFF_TEAM, DMG_NOWEP, entity(), FOREACH_CLIENT, IS_PLAYER, max(), nades_Clear(), NULL, ons_stalemate, ons_worldcplist, ons_worldgeneratorlist, Onslaught_count_generators(), Onslaught_GetWinnerTeam(), play2all(), round_handler_GetEndTime, round_handler_Init(), SND, sound, ST_ONS_CAPS, Team_GetNumberOfTeamsWithControlPoints(), TeamScore_AddToTeam(), time, VOL_BASE, and wpforenemy_announced.
Referenced by ons_DelayedInit().
 {
     if ((autocvar_timelimit && time > game_starttime + autocvar_timelimit * 60) || (round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0))
     {
         ons_stalemate = true;
         if (!wpforenemy_announced)
         {
             Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_OVERTIME_CONTROLPOINT);
             sound(NULL, CH_INFO, SND_ONS_GENERATOR_DECAY, VOL_BASE, ATTEN_NONE);
             wpforenemy_announced = true;
         }
         entity tmp_entity; // temporary entity
         float d;
         for(tmp_entity = ons_worldgeneratorlist; tmp_entity; tmp_entity = tmp_entity.ons_worldgeneratornext) if(time >= tmp_entity.ons_overtime_damagedelay)
         {
             // tmp_entity.max_health / 300 gives 5 minutes of overtime.
             // control points reduce the overtime duration.
             d = 1;
             entity e;
             for(e = ons_worldcplist; e; e = e.ons_worldcpnext)
             {
                 if(DIFF_TEAM(e, tmp_entity))
                 if(e.islinked)
                     d = d + 1;
             }
             if(autocvar_g_campaign && autocvar__campaign_testrun)
                 d = d * tmp_entity.max_health;
             else
                 d = d * tmp_entity.max_health / max(30, 60 * autocvar_timelimit_suddendeath);
             Damage(tmp_entity, tmp_entity, tmp_entity, d, DEATH_HURTTRIGGER.m_id, DMG_NOWEP, tmp_entity.origin, '0 0 0');
             tmp_entity.sprite.SendFlags |= 16;
             tmp_entity.ons_overtime_damagedelay = time + 1;
         }
     }
     else { wpforenemy_announced = false; ons_stalemate = false; }
     Onslaught_count_generators();
     if (Team_GetNumberOfTeamsWithControlPoints() > 1)
     {
         return 0;
     }
     int winner_team = Onslaught_GetWinnerTeam();
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_ONS_CAPS, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     ons_stalemate = false;
     play2all(SND(CTF_CAPTURE(winner_team)));
     round_handler_Init(7, autocvar_g_onslaught_warmup, autocvar_g_onslaught_round_timelimit);
     FOREACH_CLIENT(IS_PLAYER(it), {
         STAT(ROUNDLOST, it) = true;
         it.player_blocked = true;
         nades_Clear(it);
     });
     game_stopped = true;
     return 1;
 }
void onslaught_controlpoint_icon_link (entity e, void(entity this) spawnproc)
Definition at line 35 of file sv_controlpoint.qc.
References cpicon_send(), setthink, sys_frametime, and time.
Referenced by ons_ControlPoint_Icon_BuildThink(), and ons_ControlPoint_Icon_Spawn().
 {
     Net_LinkEntity(e, true, 0, cpicon_send);
     setthink(e, spawnproc);
     e.nextthink = time + sys_frametime;
 }
void Onslaught_count_generators ()
Definition at line 1117 of file sv_onslaught.qc.
References entity(), Entity_GetTeam(), GetResource(), NUM_TEAMS, ons_worldgeneratorlist, RES_HEALTH, Team_GetNumberOfControlPoints(), Team_GetTeamFromIndex(), Team_SetNumberOfControlPoints(), and total_generators.
Referenced by Onslaught_CheckWinner().
 {
     entity e;
     total_generators = 0;
     for (int i = 1; i <= NUM_TEAMS; ++i)
     {
         Team_SetNumberOfControlPoints(Team_GetTeamFromIndex(i), 0);
     }
     for(e = ons_worldgeneratorlist; e; e = e.ons_worldgeneratornext)
     {
         ++total_generators;
         if (GetResource(e, RES_HEALTH) < 1)
         {
             continue;
         }
         entity team_ = Entity_GetTeam(e);
         int num_control_points = Team_GetNumberOfControlPoints(team_);
         ++num_control_points;
         Team_SetNumberOfControlPoints(team_, num_control_points);
     }
 }
void onslaught_generator_touch (entity this, entity toucher)
Definition at line 1053 of file sv_onslaught.qc.
References IS_PLAYER, iscaptured, and SAME_TEAM.
Referenced by ons_GeneratorSetup().
 {
     if ( IS_PLAYER(toucher) )
     if ( SAME_TEAM(this,toucher) )
     if ( this.iscaptured )
     {
         Send_Notification(NOTIF_ONE, toucher, MSG_CENTER, CENTER_ONS_TELEPORT);
     }
 }
int Onslaught_GetWinnerTeam ()
Definition at line 1139 of file sv_onslaught.qc.
References entity(), nades_Clear(), NUM_TEAM_1, NUM_TEAMS, Team_GetNumberOfControlPoints(), Team_GetTeamFromIndex(), and Team_IndexToTeam().
Referenced by Onslaught_CheckWinner().
 {
     int winner_team = 0;
     if (Team_GetNumberOfControlPoints(Team_GetTeamFromIndex(1)) >= 1)
     {
         winner_team = NUM_TEAM_1;
     }
     for (int i = 2; i <= NUM_TEAMS; ++i)
     {
         if (Team_GetNumberOfControlPoints(Team_GetTeamFromIndex(i)) >= 1)
         {
             if (winner_team != 0)
             {
                 return 0;
             }
             winner_team = Team_IndexToTeam(i);
         }
     }
     if (winner_team)
     {
         return winner_team;
     }
     return -1; // no generators left?
 }
void Onslaught_RoundStart ()
Definition at line 1252 of file sv_onslaught.qc.
References entity(), FOREACH_CLIENT, IS_PLAYER, ons_worldcplist, and ons_worldgeneratorlist.
Referenced by ons_DelayedInit().
 {
     entity tmp_entity;
     FOREACH_CLIENT(IS_PLAYER(it), it.player_blocked = false);
     for(tmp_entity = ons_worldcplist; tmp_entity; tmp_entity = tmp_entity.ons_worldcpnext)
         tmp_entity.sprite.SendFlags |= 16;
     for(tmp_entity = ons_worldgeneratorlist; tmp_entity; tmp_entity = tmp_entity.ons_worldgeneratornext)
         tmp_entity.sprite.SendFlags |= 16;
 }
void onslaught_updatelinks ()
Definition at line 116 of file sv_onslaught.qc.
References BIT, DAMAGE_AIM, DAMAGE_NO, DIFF_TEAM, entity(), etos(), ftos(), g_bot_targets, IL_EACH, IL_PUSH(), IL_REMOVE(), LOG_DEBUG, ons_ControlPoint_UpdateSprite(), ons_Generator_UpdateSprite(), ons_worldcplist, ons_worldgeneratorlist, ons_worldlinklist, and SAME_TEAM.
Referenced by ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_ControlPoint_Reset(), ons_ControlPoint_Touch(), ons_DelayedControlPoint_Setup(), ons_DelayedGeneratorSetup(), ons_GeneratorDamage(), and ons_GeneratorReset().
 {
     entity l;
     // first check if the game has ended
     LOG_DEBUG("--- updatelinks ---");
     // mark generators as being shielded and networked
     for(l = ons_worldgeneratorlist; l; l = l.ons_worldgeneratornext)
     {
         if (l.iscaptured)
             LOG_DEBUG(etos(l), " (generator) belongs to team ", ftos(l.team));
         else
             LOG_DEBUG(etos(l), " (generator) is destroyed");
         l.islinked = l.iscaptured;
         l.isshielded = l.iscaptured;
         l.sprite.SendFlags |= 16;
     }
     // mark points as shielded and not networked
     for(l = ons_worldcplist; l; l = l.ons_worldcpnext)
     {
         l.islinked = false;
         l.isshielded = true;
         l.aregensneighbor = 0;
         l.arecpsneighbor = 0;
         LOG_DEBUG(etos(l), " (point) belongs to team ", ftos(l.team));
         l.sprite.SendFlags |= 16;
     }
     // flow power outward from the generators through the network
     bool stop = false;
     while (!stop)
     {
         stop = true;
         for(l = ons_worldlinklist; l; l = l.ons_worldlinknext)
         {
             // if both points are captured by the same team, and only one of
             // them is powered, mark the other one as powered as well
             if (l.enemy.iscaptured && l.goalentity.iscaptured)
                 if (l.enemy.islinked != l.goalentity.islinked)
                     if(SAME_TEAM(l.enemy, l.goalentity))
                     {
                         if (!l.goalentity.islinked)
{
                             stop = false;
                             l.goalentity.islinked = true;
                             LOG_DEBUG(etos(l), " (link) is marking ", etos(l.goalentity), " (point) because its team matches ", etos(l.enemy), " (point)");
                         }
                         else if (!l.enemy.islinked)
{
                             stop = false;
                             l.enemy.islinked = true;
                             LOG_DEBUG(etos(l), " (link) is marking ", etos(l.enemy), " (point) because its team matches ", etos(l.goalentity), " (point)");
                         }
                     }
         }
     }
     // now that we know which points are powered we can mark their neighbors
     // as unshielded if team differs
     for(l = ons_worldlinklist; l; l = l.ons_worldlinknext)
     {
         if (l.goalentity.islinked)
         {
             if(DIFF_TEAM(l.goalentity, l.enemy))
             {
                 LOG_DEBUG(etos(l), " (link) is unshielding ", etos(l.enemy), " (point) because its team does not match ", etos(l.goalentity), " (point)");
                 l.enemy.isshielded = false;
             }
             if(l.goalentity.classname == "onslaught_generator")
                 l.enemy.aregensneighbor |= BIT(l.goalentity.team);
             else
                 l.enemy.arecpsneighbor |= BIT(l.goalentity.team);
         }
         if (l.enemy.islinked)
         {
             if(DIFF_TEAM(l.goalentity, l.enemy))
             {
                 LOG_DEBUG(etos(l), " (link) is unshielding ", etos(l.goalentity), " (point) because its team does not match ", etos(l.enemy), " (point)");
                 l.goalentity.isshielded = false;
             }
             if(l.enemy.classname == "onslaught_generator")
                 l.goalentity.aregensneighbor |= BIT(l.enemy.team);
             else
                 l.goalentity.arecpsneighbor |= BIT(l.enemy.team);
         }
     }
     // now update the generators
     for(l = ons_worldgeneratorlist; l; l = l.ons_worldgeneratornext)
     {
         if (l.isshielded)
         {
             LOG_DEBUG(etos(l), " (generator) is shielded");
             l.takedamage = DAMAGE_NO;
             if(l.bot_attack)
                 IL_REMOVE(g_bot_targets, l);
             l.bot_attack = false;
         }
         else
         {
             LOG_DEBUG(etos(l), " (generator) is not shielded");
             l.takedamage = DAMAGE_AIM;
             if(!l.bot_attack)
                 IL_PUSH(g_bot_targets, l);
             l.bot_attack = true;
         }
         ons_Generator_UpdateSprite(l);
     }
     // now update the takedamage and alpha variables on control point icons
     for(l = ons_worldcplist; l; l = l.ons_worldcpnext)
     {
         if (l.isshielded)
         {
             LOG_DEBUG(etos(l), " (point) is shielded");
             if (l.goalentity)
             {
                 l.goalentity.takedamage = DAMAGE_NO;
                 if(l.goalentity.bot_attack)
                     IL_REMOVE(g_bot_targets, l.goalentity);
                 l.goalentity.bot_attack = false;
             }
         }
         else
         {
             LOG_DEBUG(etos(l), " (point) is not shielded");
             if (l.goalentity)
             {
                 l.goalentity.takedamage = DAMAGE_AIM;
                 if(!l.goalentity.bot_attack)
                     IL_PUSH(g_bot_targets, l.goalentity);
                 l.goalentity.bot_attack = true;
             }
         }
         ons_ControlPoint_UpdateSprite(l);
     }
     IL_EACH(g_onsshields, true,
     {
         it.team = it.enemy.team;
         it.colormap = it.enemy.colormap;
     });
 }
spawnfunc (onslaught_link)
Definition at line 2104 of file sv_onslaught.qc.
References g_onslaught, InitializeEntity(), INITPRIO_FINDTARGET, objerror(), ons_DelayedLinkSetup(), ons_Link_Send(), ons_worldlinklist, ons_worldlinknext, target, and target2.
 {
     if(!g_onslaught) { delete(this); return; }
     if (this.target == "" || this.target2 == "")
         objerror(this, "target and target2 must be set\n");
     this.ons_worldlinknext = ons_worldlinklist; // link into ons_worldlinklist
     ons_worldlinklist = this;
     InitializeEntity(this, ons_DelayedLinkSetup, INITPRIO_FINDTARGET);
     Net_LinkEntity(this, false, 0, ons_Link_Send);
 }
spawnfunc (onslaught_controlpoint)
Definition at line 2129 of file sv_onslaught.qc.
References g_onslaught, and ons_ControlPoint_Setup().
 {
     if(!g_onslaught) { delete(this); return; }
     ons_ControlPoint_Setup(this);
 }
spawnfunc (onslaught_generator)
Definition at line 2145 of file sv_onslaught.qc.
References g_onslaught, objerror(), ons_GeneratorSetup(), and team.
 {
     if(!g_onslaught) { delete(this); return; }
     if(!this.team) { objerror(this, "team must be set"); }
     ons_GeneratorSetup(this);
 }
Variable Documentation
float autocvar_g_onslaught_allow_vehicle_touch
Definition at line 23 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Touch().
float autocvar_g_onslaught_click_radius
Definition at line 28 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_cp_buildhealth
Definition at line 17 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Spawn().
float autocvar_g_onslaught_cp_buildtime
Definition at line 18 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Spawn().
float autocvar_g_onslaught_cp_health
Definition at line 19 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Spawn().
float autocvar_g_onslaught_cp_proxydecap
Definition at line 10 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Think().
float autocvar_g_onslaught_cp_proxydecap_distance = 512
Definition at line 11 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Think().
float autocvar_g_onslaught_cp_proxydecap_dps = 100
Definition at line 12 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_Think().
float autocvar_g_onslaught_cp_regen
Definition at line 20 of file sv_onslaught.qc.
Referenced by ons_ControlPoint_Icon_BuildThink().
float autocvar_g_onslaught_gen_health
Definition at line 21 of file sv_onslaught.qc.
Referenced by ons_GeneratorReset(), and ons_GeneratorSetup().
float autocvar_g_onslaught_round_timelimit
Definition at line 24 of file sv_onslaught.qc.
Referenced by ons_DelayedInit(), and Onslaught_CheckWinner().
float autocvar_g_onslaught_shield_force = 100
Definition at line 22 of file sv_onslaught.qc.
Referenced by ons_Initialize().
bool autocvar_g_onslaught_spawn_at_controlpoints
Definition at line 8 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_spawn_at_controlpoints_chance = 0.5
Definition at line 13 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_spawn_at_controlpoints_random
Definition at line 14 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
bool autocvar_g_onslaught_spawn_at_generator
Definition at line 9 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_spawn_at_generator_chance
Definition at line 15 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_spawn_at_generator_random
Definition at line 16 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_spawn_choose
Definition at line 27 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_teleport_radius
Definition at line 26 of file sv_onslaught.qc.
Referenced by MUTATOR_HOOKFUNCTION().
float autocvar_g_onslaught_teleport_wait
Definition at line 7 of file sv_onslaught.qc.
Referenced by ons_Teleport().
float autocvar_g_onslaught_warmup
Definition at line 25 of file sv_onslaught.qc.
Referenced by ons_DelayedInit(), and Onslaught_CheckWinner().
entity cam
Definition at line 30 of file sv_onslaught.qc.
Referenced by ons_camSetup(), and ons_Initialize().
bool g_onslaught
Definition at line 5 of file sv_onslaught.qc.
Referenced by ons_Initialize(), and spawnfunc().
int total_generators
Definition at line 1116 of file sv_onslaught.qc.
Referenced by Onslaught_count_generators().