Xonotic: server/weapons/accuracy.qh File Reference
accuracy.qh File Reference
#include <common/weapons/_all.qh>
#include <common/stats.qh>
Functions
void accuracy_add (entity e, Weapon w, float fired, float hit)
bool accuracy_canbegooddamage (entity attacker)
void accuracy_free (entity e)
void accuracy_init (entity e)
bool accuracy_isgooddamage (entity attacker, entity targ)
void accuracy_resend (entity e)
void accuracy_reset (entity e)
REPLICATE (cvar_cl_accuracy_data_share, bool, "cl_accuracy_data_share")
REPLICATE (cvar_cl_accuracy_data_receive, bool, "cl_accuracy_data_receive")
Variables
entity accuracy
float accuracy_cnt_fired [REGISTRY_MAX(Weapons)]
float accuracy_cnt_hit [REGISTRY_MAX(Weapons)]
float accuracy_fired [REGISTRY_MAX(Weapons)]
float accuracy_frags [REGISTRY_MAX(Weapons)]
float accuracy_hit [REGISTRY_MAX(Weapons)]
float autocvar_sv_accuracy_data_share = 1
Weapon Accuracy stats.
bool cvar_cl_accuracy_data_receive
bool cvar_cl_accuracy_data_share
Function Documentation
accuracy_add()
void accuracy_add (entity e, Weapon w, float fired, float hit)
Definition at line 83 of file accuracy.qc.
References accuracy_byte(), CS(), entity(), FOREACH_CLIENT, IS_INDEPENDENT_PLAYER, IS_SPEC, Weapon::m_id, time, and WEP_FIRST.
Referenced by Fire_AddDamage(), fireBullet_antilag(), FireRailgunBullet(), RadiusDamageForSource(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     if (IS_INDEPENDENT_PLAYER(this)) return;
     entity a = CS(this).accuracy;
     if (!a) return;
     if (!hit && !fired) return;
     if (w == WEP_Null) return;
     int wepid = w.m_id;
     wepid -= WEP_FIRST;
     int b = accuracy_byte(a.accuracy_hit[wepid], a.accuracy_fired[wepid]);
     if (hit)    a.accuracy_hit  [wepid] += hit;
     if (fired)  a.accuracy_fired[wepid] += fired;
     if (hit && STAT(HIT_TIME, a) != time) { // only run this once per frame
         a.accuracy_cnt_hit[wepid] += 1;
         STAT(HIT_TIME, a) = time;
     }
     if (fired && a.fired_time != time) { // only run this once per frame
         a.accuracy_cnt_fired[wepid] += 1;
         a.fired_time = time;
     }
     if (b == accuracy_byte(a.accuracy_hit[wepid], a.accuracy_fired[wepid])) return; // no change
     int sf = 1 << (wepid % 24);
     a.SendFlags |= sf;
     FOREACH_CLIENT(IS_SPEC(it) && it.enemy == this, { CS(it).accuracy.SendFlags |= sf; });
 }
accuracy_canbegooddamage()
bool accuracy_canbegooddamage (entity attacker)
Definition at line 132 of file accuracy.qc.
References IS_CLIENT, and warmup_stage.
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     return !warmup_stage && IS_CLIENT(attacker);
 }
accuracy_free()
void accuracy_free (entity e)
Definition at line 53 of file accuracy.qc.
References CS().
 {
     delete(CS(e).accuracy);
 }
accuracy_init()
void accuracy_init (entity e)
Definition at line 45 of file accuracy.qc.
References accuracy, accuracy_send(), CS(), entity(), and new_pure.
 {
     entity a = CS(e).accuracy = new_pure(accuracy);
     a.owner = e;
     a.drawonlytoclient = e;
     Net_LinkEntity(a, false, 0, accuracy_send);
 }
accuracy_isgooddamage()
bool accuracy_isgooddamage (entity attacker, entity targ)
Definition at line 112 of file accuracy.qc.
References IS_CLIENT, IS_DEAD, MUT_ACCADD_INVALID, MUT_ACCADD_VALID, MUTATOR_CALLHOOK, SAME_TEAM, time, and warmup_stage.
Referenced by Fire_AddDamage(), fireBullet_antilag(), PlayerDamage(), and RadiusDamageForSource().
 {
     int mutator_check = MUTATOR_CALLHOOK(AccuracyTargetValid, attacker, targ);
     if (warmup_stage || game_stopped) return false;
     // damage to dead/frozen players is good only if it happens in the frame they get killed / frozen
     // so that stats for weapons that shoot multiple projectiles per shot are properly counted
     if (IS_DEAD(targ) && time > targ.death_time) return false;
     if (STAT(FROZEN, targ) && time > targ.freeze_time) return false;
     if (SAME_TEAM(attacker, targ)) return false;
     if (mutator_check == MUT_ACCADD_INVALID) return true;
     if (mutator_check != MUT_ACCADD_VALID) return false;
     if (!IS_CLIENT(targ) || !IS_CLIENT(attacker)) return false;
     return true;
 }
accuracy_resend()
void accuracy_resend (entity e)
Definition at line 74 of file accuracy.qc.
References CS().
Referenced by PutObserverInServer(), PutPlayerInServer(), and SpectateSet().
 {
     CS(e).accuracy.SendFlags = 0xFFFFFF;
 }
accuracy_reset()
void accuracy_reset (entity e)
Definition at line 58 of file accuracy.qc.
References CS(), entity(), and REGISTRY_MAX.
Referenced by reset_map().
 {
     entity a = CS(e).accuracy;
     if (!a) return;
     for (int i = 0; i < REGISTRY_MAX(Weapons); i++)
     {
         a.accuracy_frags[i] = 0;
         a.accuracy_hit[i] = 0;
         a.accuracy_fired[i] = 0;
         a.accuracy_cnt_hit[i] = 0;
         a.accuracy_cnt_fired[i] = 0;
     }
 }
REPLICATE() [1/2]
REPLICATE (cvar_cl_accuracy_data_share , bool , "cl_accuracy_data_share")
REPLICATE() [2/2]
REPLICATE (cvar_cl_accuracy_data_receive , bool , "cl_accuracy_data_receive")
Variable Documentation
accuracy
entity accuracy
Definition at line 28 of file accuracy.qh.
Referenced by accuracy_init().
accuracy_cnt_fired
float accuracy_cnt_fired[REGISTRY_MAX(Weapons)]
Definition at line 34 of file accuracy.qh.
accuracy_cnt_hit
float accuracy_cnt_hit[REGISTRY_MAX(Weapons)]
Definition at line 33 of file accuracy.qh.
accuracy_fired
float accuracy_fired[REGISTRY_MAX(Weapons)]
Definition at line 32 of file accuracy.qh.
accuracy_frags
float accuracy_frags[REGISTRY_MAX(Weapons)]
Definition at line 29 of file accuracy.qh.
accuracy_hit
float accuracy_hit[REGISTRY_MAX(Weapons)]
Definition at line 31 of file accuracy.qh.
autocvar_sv_accuracy_data_share
float autocvar_sv_accuracy_data_share = 1
Weapon Accuracy stats.
These stats are sent to all the clients to be displayed on the scoreboard and also to Xonstats.
Note that weapon damage is counted differently from player damage:
it isn't limited by target's health in case you kill them
it ignores handicap, shield, strength and similar powerups / buffs
it doesn't count more than a single full hit if you hit multiple targets with a single shot in order to never assign more than 100% accuracy per hit
obviously damage caused by fall, lava, trigger_hurt and telefrags isn't counted as weapon damage in any way
Definition at line 21 of file accuracy.qh.
Referenced by accuracy_send().
cvar_cl_accuracy_data_receive
bool cvar_cl_accuracy_data_receive
Definition at line 25 of file accuracy.qh.
Referenced by STATIC_INIT().
cvar_cl_accuracy_data_share
bool cvar_cl_accuracy_data_share
Definition at line 23 of file accuracy.qh.
Referenced by STATIC_INIT().