Xonotic: lib/accumulate.qh File Reference
lib/accumulate.qh File Reference
Defines
#define ACCUMULATE_FUNCTION(func, otherfunc) .float _ACCUMULATE_##func##__##otherfunc;
#define CALL_ACCUMULATED_FUNCTION(func) ACCUMULATE_call(#func)
#define SET_FIRST_OR_LAST(input, first, count) if (!input) { input = (first + count); }
#define SET_FIELD_COUNT(field, first, count) if (!field) { field = (first + count); ++count; }
#define CHECK_MAX_COUNT(name, max, count, type) if (count > max) { error(strcat("Maximum ", type, " hit: ", #name, ": ", ftos(count), ".\n")); }
Functions
void ACCUMULATE_call (string func)
Define Documentation
#define ACCUMULATE_FUNCTION (func, otherfunc) .float _ACCUMULATE_##func##__##otherfunc;
Definition at line 32 of file accumulate.qh.
#define CALL_ACCUMULATED_FUNCTION (func) ACCUMULATE_call(#func)
Definition at line 46 of file accumulate.qh.
Referenced by GenericCommand_restartnotifs(), and STATIC_INIT().
#define CHECK_MAX_COUNT (name, max, count, type) if (count > max) { error(strcat("Maximum ", type, " hit: ", #name, ": ", ftos(count), ".\n")); }
Definition at line 56 of file accumulate.qh.
#define SET_FIELD_COUNT (field, first, count) if (!field) { field = (first + count); ++count; }
Definition at line 54 of file accumulate.qh.
#define SET_FIRST_OR_LAST (input, first, count) if (!input) { input = (first + count); }
Definition at line 52 of file accumulate.qh.
Function Documentation
void ACCUMULATE_call (string func)
Definition at line 34 of file accumulate.qh.
References callfunction(), n, name, strcat(), strlen(), and substring().
        {
            float i;
            float n = numentityfields();
            string funcprefix = strcat("_ACCUMULATE_", func, "__");
            float funcprefixlen = strlen(funcprefix);
            for (i = 0; i < n; ++i)
            {
                string name = entityfieldname(i);
                if (substring(name, 0, funcprefixlen) == funcprefix) callfunction(substring(name, funcprefixlen, -1));
            }
        }