Xonotic: LastManStanding Class Reference
LastManStanding Class Reference
Public Member Functions
LastManStanding ()
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_configuremenu ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isForcedSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
Public Attributes
bool frags = true
does this gametype use a point limit?
int items = 0
game type ID
bool m_hidelimits = false
should this gametype display a score limit in the scoreboard?
int m_id = 0
string m_legacydefaults = "9 20 0"
int m_priority = 0
game type priority in random selections
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 5 of file lms.qh.
Constructor & Destructor Documentation
LastManStanding::LastManStanding () inline
Definition at line 6 of file lms.qh.
References GAMETYPE_FLAG_HIDELIMITS, and GAMETYPE_FLAG_USEPOINTS.
     {
         this.gametype_init(this, _("Last Man Standing"),"lms","g_lms",GAMETYPE_FLAG_USEPOINTS | GAMETYPE_FLAG_HIDELIMITS,"","timelimit=20 lives=5 leadlimit=0",_("Survive and kill until the enemies have no lives left"));
     }
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
virtual void Gametype::describe () inline virtual inherited
Definition at line 86 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual inherited
Definition at line 92 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual inherited
Definition at line 98 of file mapinfo.qh.
References cons(), ENDCLASS, GAMETYPE_FLAG_HIDELIMITS, GAMETYPE_FLAG_PREFERRED, GAMETYPE_FLAG_PRIORITY, GAMETYPE_FLAG_TEAMPLAY, GAMETYPE_FLAG_USEPOINTS, m_flags, MAPINFO_TYPE_ALL, NULL, REGISTER_REGISTRY, REGISTRY, REGISTRY_CHECK(), REGISTRY_DEFINE_GET, and REGISTRY_SORT().
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = (gflags & GAMETYPE_FLAG_TEAMPLAY);
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         this.frags = (gflags & GAMETYPE_FLAG_USEPOINTS);
         this.m_priority = ((gflags & GAMETYPE_FLAG_PREFERRED) ? 2 : ((gflags & GAMETYPE_FLAG_PRIORITY) ? 1 : 0));
         this.m_hidelimits = (gflags & GAMETYPE_FLAG_HIDELIMITS);
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void LastManStanding::m_configuremenu () inline virtual
Reimplemented from Gametype.
Definition at line 14 of file lms.qh.
References string_null, and TC.
     {
         TC(Gametype, this);
         returns(menu, _("Lives:"),           3,   50,  1, "g_lms_lives_override",      string_null,                    string_null);
     }
virtual void Gametype::m_generate_mapinfo () inline virtual inherited
Reimplemented in Domination, Race, Invasion, CaptureTheFlag, RaceCTS, NexBall, Assault, and Onslaught.
Definition at line 64 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
     }
virtual void LastManStanding::m_isAlwaysSupported () inline virtual
Reimplemented from Gametype.
Definition at line 10 of file lms.qh.
     {
         return true;
     }
virtual void Gametype::m_isForcedSupported () inline virtual inherited
Reimplemented in TeamDeathmatch, and Duel.
Definition at line 76 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_isTwoBaseMode () inline virtual inherited
Reimplemented in Race, CaptureTheFlag, NexBall, and Assault.
Definition at line 68 of file mapinfo.qh.
     {
         return false;
     }
virtual void Gametype::m_parse_mapinfo () inline virtual inherited
Reimplemented in FreezeTag, ClanArena, Domination, KeyHunt, Race, TeamDeathmatch, and Invasion.
Definition at line 60 of file mapinfo.qh.
     {
         return false;
     }
Member Data Documentation
bool Gametype::frags = true inherited
does this gametype use a point limit?
Definition at line 41 of file mapinfo.qh.
Referenced by _MapInfo_Map_ApplyGametype().
int Gametype::items = 0 inherited
game type ID
Definition at line 31 of file mapinfo.qh.
bool Gametype::m_hidelimits = false inherited
should this gametype display a score limit in the scoreboard?
Definition at line 43 of file mapinfo.qh.
int Gametype::m_id = 0 inherited
Definition at line 29 of file mapinfo.qh.
string LastManStanding::m_legacydefaults = "9 20 0"
Definition at line 19 of file lms.qh.
int Gametype::m_priority = 0 inherited
game type priority in random selections
Definition at line 49 of file mapinfo.qh.
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 39 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/gamemodes/gamemode/lms/lms.qh