Xonotic: common/mutators/mutator/powerups/sv_powerups.qc File Reference
sv_powerups.qc File Reference
#include "sv_powerups.qh"
Functions
MUTATOR_HOOKFUNCTION (powerups, W_PlayStrengthSound)
MUTATOR_HOOKFUNCTION (powerups, LogDeath_AppendItemCodes)
MUTATOR_HOOKFUNCTION (powerups, Damage_Calculate)
MUTATOR_HOOKFUNCTION (powerups, CustomizeWaypoint)
MUTATOR_HOOKFUNCTION (powerups, MonsterValidTarget)
MUTATOR_HOOKFUNCTION (powerups, ItemTouched)
MUTATOR_HOOKFUNCTION (powerups, PlayerDies)
MUTATOR_HOOKFUNCTION (powerups, PlayerPhysics_UpdateStats)
MUTATOR_HOOKFUNCTION (powerups, WeaponRateFactor)
MUTATOR_HOOKFUNCTION (powerups, BuildMutatorsPrettyString)
MUTATOR_HOOKFUNCTION (powerups, BotShouldAttack)
MUTATOR_HOOKFUNCTION (powerups, BuildMutatorsString)
void powerups_DropItem (entity this, StatusEffects effect)
void powerups_DropItem_Think (entity this)
Function Documentation
MUTATOR_HOOKFUNCTION() [1/12]
MUTATOR_HOOKFUNCTION (powerups , W_PlayStrengthSound)
Definition at line 3 of file sv_powerups.qc.
References ATTEN_NORM, autocvar_sv_strengthsound_antispam_refire_threshold, autocvar_sv_strengthsound_antispam_time, CH_TRIGGER, entity(), M_ARGV, sound, time, and VOL_BASE.
 {
     entity player = M_ARGV(0, entity);
     if(StatusEffects_active(STATUSEFFECT_Strength, player)
         && ((time > player.prevstrengthsound + autocvar_sv_strengthsound_antispam_time) // prevent insane sound spam
         || (time > player.prevstrengthsoundattempt + autocvar_sv_strengthsound_antispam_refire_threshold)))
         {
             sound(player, CH_TRIGGER, SND_STRENGTH_FIRE, VOL_BASE, ATTEN_NORM);
             player.prevstrengthsound = time;
         }
     player.prevstrengthsoundattempt = time;
 }
MUTATOR_HOOKFUNCTION() [2/12]
MUTATOR_HOOKFUNCTION (powerups , LogDeath_AppendItemCodes)
Definition at line 17 of file sv_powerups.qc.
References entity(), M_ARGV, and strcat().
 {
     entity player = M_ARGV(0, entity);
     if(StatusEffects_active(STATUSEFFECT_Strength, player))
         M_ARGV(1, string) = strcat(M_ARGV(1, string), "S");
     if(StatusEffects_active(STATUSEFFECT_Shield, player))
         M_ARGV(1, string) = strcat(M_ARGV(1, string), "I");
     // TODO: item codes for other powerups?
 }
MUTATOR_HOOKFUNCTION() [3/12]
MUTATOR_HOOKFUNCTION (powerups , Damage_Calculate)
Definition at line 30 of file sv_powerups.qc.
References entity(), M_ARGV, and vector().
 {
     entity attacker = M_ARGV(1, entity);
     entity targ = M_ARGV(2, entity);
     // apply strength multiplier
     if(StatusEffects_active(STATUSEFFECT_Strength, attacker))
     {
         if(targ == attacker)
         {
             M_ARGV(4, float) = M_ARGV(4, float) * autocvar_g_balance_powerup_strength_selfdamage;
             M_ARGV(6, vector) = M_ARGV(6, vector) * autocvar_g_balance_powerup_strength_selfforce;
         }
         else
         {
             M_ARGV(4, float) = M_ARGV(4, float) * autocvar_g_balance_powerup_strength_damage;
             M_ARGV(6, vector) = M_ARGV(6, vector) * autocvar_g_balance_powerup_strength_force;
         }
     }
     // apply shield multiplier
     if(StatusEffects_active(STATUSEFFECT_Shield, targ))
     {
         M_ARGV(4, float) = M_ARGV(4, float) * autocvar_g_balance_powerup_invincible_takedamage;
         if (targ != attacker)
         {
             M_ARGV(6, vector) = M_ARGV(6, vector) * autocvar_g_balance_powerup_invincible_takeforce;
         }
     }
 }
MUTATOR_HOOKFUNCTION() [4/12]
MUTATOR_HOOKFUNCTION (powerups , CustomizeWaypoint)
Definition at line 61 of file sv_powerups.qc.
References DIFF_TEAM, entity(), IS_CLIENT, and M_ARGV.
 {
     entity wp = M_ARGV(0, entity);
     entity player = M_ARGV(1, entity);
     entity e = WaypointSprite_getviewentity(player);
     // if you have the invisibility powerup, sprites ALWAYS are restricted to your team
     // but only apply this to real players, not to spectators
     if(IS_CLIENT(wp.owner) && (e == player) && DIFF_TEAM(wp.owner, e) && StatusEffects_active(STATUSEFFECT_Invisibility, wp.owner))
         return true;
 }
MUTATOR_HOOKFUNCTION() [5/12]
MUTATOR_HOOKFUNCTION (powerups , MonsterValidTarget)
Definition at line 74 of file sv_powerups.qc.
References entity(), and M_ARGV.
 {
     entity targ = M_ARGV(1, entity);
     return StatusEffects_active(STATUSEFFECT_Invisibility, targ);
 }
MUTATOR_HOOKFUNCTION() [6/12]
MUTATOR_HOOKFUNCTION (powerups , ItemTouched)
Definition at line 144 of file sv_powerups.qc.
References entity(), and M_ARGV.
 {
     entity e = M_ARGV(0, entity);
     if(e.waypointsprite_attached)
         WaypointSprite_Kill(e.waypointsprite_attached);
 }
MUTATOR_HOOKFUNCTION() [7/12]
MUTATOR_HOOKFUNCTION (powerups , PlayerDies)
Definition at line 151 of file sv_powerups.qc.
References autocvar_g_powerups_drop_ondeath, entity(), FOREACH, and M_ARGV.
 {
     if(!autocvar_g_powerups_drop_ondeath)
         return;
     entity frag_target = M_ARGV(2, entity);
     FOREACH(StatusEffect, it.instanceOfPowerups,
     {
         if(StatusEffects_active(it, frag_target))
             powerups_DropItem(frag_target, it);
     });
 }
MUTATOR_HOOKFUNCTION() [8/12]
MUTATOR_HOOKFUNCTION (powerups , PlayerPhysics_UpdateStats)
Definition at line 165 of file sv_powerups.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(0, entity);
     // these automatically reset, no need to worry
     if(StatusEffects_active(STATUSEFFECT_Speed, player))
         STAT(MOVEVARS_HIGHSPEED, player) *= autocvar_g_balance_powerup_speed_highspeed;
 }
MUTATOR_HOOKFUNCTION() [9/12]
MUTATOR_HOOKFUNCTION (powerups , WeaponRateFactor)
Definition at line 174 of file sv_powerups.qc.
References entity(), and M_ARGV.
 {
     entity player = M_ARGV(1, entity);
     if(StatusEffects_active(STATUSEFFECT_Speed, player))
         M_ARGV(0, float) *= autocvar_g_balance_powerup_speed_attackrate;
 }
MUTATOR_HOOKFUNCTION() [10/12]
MUTATOR_HOOKFUNCTION (powerups , BuildMutatorsPrettyString)
Definition at line 182 of file sv_powerups.qc.
References autocvar_g_powerups, M_ARGV, and strcat().
 {
     if(autocvar_g_powerups == 0)
         M_ARGV(0, string) = strcat(M_ARGV(0, string), ", No powerups");
     if(autocvar_g_powerups > 0)
         M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Powerups");
 }
MUTATOR_HOOKFUNCTION() [11/12]
MUTATOR_HOOKFUNCTION (powerups , BotShouldAttack)
Definition at line 190 of file sv_powerups.qc.
References entity(), and M_ARGV.
 {
     entity targ = M_ARGV(1, entity);
     if(StatusEffects_active(STATUSEFFECT_Invisibility, targ))
         return true;
 }
MUTATOR_HOOKFUNCTION() [12/12]
MUTATOR_HOOKFUNCTION (powerups , BuildMutatorsString)
Definition at line 198 of file sv_powerups.qc.
References autocvar_g_powerups, M_ARGV, and strcat().
 {
     if(autocvar_g_powerups == 0)
         M_ARGV(0, string) = strcat(M_ARGV(0, string), ":no_powerups");
     if(autocvar_g_powerups > 0)
         M_ARGV(0, string) = strcat(M_ARGV(0, string), ":powerups");
 }
powerups_DropItem()
void powerups_DropItem (entity this, StatusEffects effect)
Definition at line 97 of file sv_powerups.qc.
References autocvar_g_items_dropped_lifetime, autocvar_g_powerups_drop_ondeath, entity(), Item_DefinitionFromInternalName(), Item_InitializeLoot(), Item_SetExpiring(), NULL, powerups_DropItem_Think(), randomvec(), RES_HEALTH, SetResourceExplicit(), setthink, spawn(), and time.
 {
     entity item = Item_DefinitionFromInternalName(effect.netname);
     float t = StatusEffects_gettime(effect, this);
     float timeleft = t - time;
     float maxtime = 0;
     if(timeleft <= 1 || !item)
         return;
     entity e = spawn();
     // If we want the timer to keep running, we enable expiring then use the exact time the powerup will finish at.
     // If we want the timer to freeze, we disable expiring and we just use the time left of the powerup.
     // See Item_SetExpiring() below.
     float finished = (autocvar_g_powerups_drop_ondeath == 2 ? timeleft : t);
     // If the timer is frozen, the item will stay on the floor for 20 secs (same as weapons),
     // otherwise it'll disappear after the timer runs out.
     float time_to_live = (autocvar_g_powerups_drop_ondeath == 2 ? autocvar_g_items_dropped_lifetime : timeleft);
     // TODO: items cannot hold their "item field" yet, so we need to list all the powerups here!
     switch(item)
     {
         case ITEM_Strength: e.strength_finished = finished; maxtime = autocvar_g_balance_powerup_strength_time; break;
         case ITEM_Shield: e.invincible_finished = finished; maxtime = autocvar_g_balance_powerup_invincible_time; break;
         case ITEM_Invisibility: e.invisibility_finished = finished; maxtime = autocvar_g_balance_powerup_invincible_time; break;
         case ITEM_Speed: e.speed_finished = finished; maxtime = autocvar_g_balance_powerup_speed_time; break;
     }
     Item_InitializeLoot(e, item.m_canonical_spawnfunc, this.origin + '0 0 32', randomvec() * 175 + '0 0 175', time_to_live);
     if(autocvar_g_powerups_drop_ondeath != 2)
         Item_SetExpiring(e, true);
     // Use health as time left to live
     SetResourceExplicit(e, RES_HEALTH, time_to_live);
     // Create waypoint displaying time left of the powerup
     entity wp = WaypointSprite_Spawn(WP_Item, 0, 0, e, '0 0 1' * e.maxs.z, NULL, 0, e, waypointsprite_attached, true, RADARICON_Item);
     wp.wp_extra = item.m_id;
     WaypointSprite_UpdateMaxHealth(e.waypointsprite_attached, maxtime);
     WaypointSprite_UpdateHealth(e.waypointsprite_attached, timeleft);
     // Start dropping its time to live
     setthink(e, powerups_DropItem_Think);
     e.nextthink = time + 1;
 }
powerups_DropItem_Think()
void powerups_DropItem_Think (entity this)
Definition at line 80 of file sv_powerups.qc.
References autocvar_g_powerups_drop_ondeath, GetResource(), nextthink, RES_HEALTH, TakeResource(), and time.
Referenced by powerups_DropItem().
 {
     TakeResource(this, RES_HEALTH, 1);
     if(GetResource(this, RES_HEALTH) < 1) {
         WaypointSprite_Kill(this.waypointsprite_attached);
         delete(this);
         return;
     }
     // Only needed to update if the timer of the powerup is running
     if(autocvar_g_powerups_drop_ondeath == 1)
         WaypointSprite_UpdateHealth(this.waypointsprite_attached, GetResource(this, RES_HEALTH));
     this.nextthink = time + 1;
 }