Xonotic: server/command/common.qh File Reference
common.qh File Reference
#include <common/command/_mod.qh>
#include "vote.qh"
#include <common/monsters/sv_spawn.qh>
Macros
#define COMMON_COMMAND(id, description)
#define COMMON_COMMANDS_from(i) _COMMON_COMMANDS_from(i, NULL)
#define GetClientErrorString(clienterror, original_input) GetClientErrorString_color(clienterror, original_input, "^7")
Functions
COMMON_COMMAND (cvar_changes,"Prints a list of all changed server cvars")
COMMON_COMMAND (cvar_purechanges,"Prints a list of all changed gameplay cvars")
COMMON_COMMAND (editmob,"Modifies a monster or all monsters")
COMMON_COMMAND (info,"Request for unique server information set up by admin")
COMMON_COMMAND (ladder,"Get information about top players if supported")
COMMON_COMMAND (lsmaps,"List maps which can be used with the current game mode")
COMMON_COMMAND (printmaplist,"Display full server maplist reply")
COMMON_COMMAND (rankings,"Print information about rankings")
COMMON_COMMAND (records,"List top 10 records for the current map")
COMMON_COMMAND (teamstatus,"Show information about player and team scores")
COMMON_COMMAND (time,"Print different formats/readouts of time")
COMMON_COMMAND (timein,"Resume the game from being paused with a timeout")
COMMON_COMMAND (timeout,"Call a timeout which pauses the game for certain amount of time unless unpaused")
COMMON_COMMAND (vote,"Request an action to be voted upon by players")
COMMON_COMMAND (who,"Display detailed client information about all players")
void CommonCommand_cvar_changes (int request, entity caller)
void CommonCommand_cvar_purechanges (int request, entity caller)
void CommonCommand_editmob (int request, entity caller, int argc)
void CommonCommand_info (int request, entity caller, int argc)
void CommonCommand_ladder (int request, entity caller)
void CommonCommand_lsmaps (int request, entity caller)
float CommonCommand_macro_command (int argc, entity caller, string command)
void CommonCommand_macro_help (entity caller)
float CommonCommand_macro_usage (int argc, entity caller)
void CommonCommand_macro_write_aliases (float fh)
void CommonCommand_printmaplist (int request, entity caller)
void CommonCommand_rankings (int request, entity caller)
void CommonCommand_records (int request, entity caller)
void CommonCommand_teamstatus (int request, entity caller)
void CommonCommand_time (int request, entity caller)
void CommonCommand_timein (int request, entity caller)
void CommonCommand_timeout (int request, entity caller)
void CommonCommand_who (int request, entity caller, int argc)
string GetCallerName (entity caller)
string GetClientErrorString_color (float clienterror, string original_input, string col)
string GetCommandPrefix (entity caller)
entity GetFilteredEntity (string input)
float GetFilteredNumber (string input)
entity GetIndexedEntity (int argc, float start_index)
void print_to (entity to, string input)
STATIC_INIT (COMMON_COMMANDS_aliases)
void timeout_handler_reset (entity this)
void timeout_handler_think (entity this)
float VerifyClientEntity (entity client, float must_be_real, float must_be_bots)
float VerifyClientNumber (float tmp_number)
float VerifyKickableEntity (entity client)
Variables
float allowed_timeouts
const float CLIENT_ACCEPTABLE = 1
const float CLIENT_DOESNT_EXIST = -1
const float CLIENT_NOT_BOT = -3
const float CLIENT_NOT_REAL = -2
vector lastV_angle
float next_token
float orig_slowmo
float sys_frametime
const float TIMEOUT_ACTIVE = 2
entity timeout_caller
entity timeout_handler
const float TIMEOUT_INACTIVE = 0
const float TIMEOUT_LEADTIME = 1
float timeout_leadtime
const float TIMEOUT_SLOWMO_VALUE = 0.0001
float timeout_status
float timeout_time
Macro Definition Documentation
#define COMMON_COMMAND (id, description)
Value:
CLASS(commoncommand_##id, Command) \
        ATTRIB(commoncommand_##id, m_name, string, #id); \
        ATTRIB(commoncommand_##id, m_description, string, description); \
    ENDCLASS(commoncommand_##id) \
    REGISTER(COMMON_COMMANDS, CMD_SV, id, m_id, NEW(commoncommand_##id)); \
    METHOD(commoncommand_##id, m_invokecmd, void(commoncommand_##id this, int request, entity caller, int arguments, string command))
Definition at line 9 of file common.qh.
#define COMMON_COMMANDS_from (i) _COMMON_COMMANDS_from(i, NULL)
Definition at line 5 of file common.qh.
#define GetClientErrorString (clienterror, original_input) GetClientErrorString_color(clienterror, original_input, "^7")
Definition at line 79 of file common.qh.
Referenced by BanCommand_kickban(), BanCommand_mute(), BanCommand_unmute(), ClientCommand_tell(), GameCommand_adminmsg(), GameCommand_anticheat(), GameCommand_defer_clear(), GameCommand_moveplayer(), GameCommand_stuffto(), and VoteCommand_parse().
Function Documentation
COMMON_COMMAND (cvar_changes , "Prints a list of all changed server cvars")
Definition at line 142 of file common.qh.
References CommonCommand_cvar_changes().
 { CommonCommand_cvar_changes(request, caller); }
COMMON_COMMAND (cvar_purechanges , "Prints a list of all changed gameplay cvars")
Definition at line 143 of file common.qh.
References CommonCommand_cvar_purechanges().
 { CommonCommand_cvar_purechanges(request, caller); }
COMMON_COMMAND (editmob , "Modifies a monster or all monsters")
Definition at line 144 of file common.qh.
References CommonCommand_editmob().
 { CommonCommand_editmob(request, caller, arguments); }
COMMON_COMMAND (info , "Request for unique server information set up by admin")
Definition at line 145 of file common.qh.
References CommonCommand_info().
 { CommonCommand_info(request, caller, arguments); }
COMMON_COMMAND (ladder , "Get information about top players if supported")
Definition at line 146 of file common.qh.
References CommonCommand_ladder().
 { CommonCommand_ladder(request, caller); }
COMMON_COMMAND (lsmaps , "List maps which can be used with the current game mode")
Definition at line 147 of file common.qh.
References CommonCommand_lsmaps().
 { CommonCommand_lsmaps(request, caller); }
COMMON_COMMAND (printmaplist , "Display full server maplist reply")
Definition at line 148 of file common.qh.
References CommonCommand_printmaplist().
 { CommonCommand_printmaplist(request, caller); }
COMMON_COMMAND (rankings , "Print information about rankings")
Definition at line 149 of file common.qh.
References CommonCommand_rankings().
 { CommonCommand_rankings(request, caller); }
COMMON_COMMAND (records , "List top 10 records for the current map")
Definition at line 150 of file common.qh.
References CommonCommand_records().
 { CommonCommand_records(request, caller); }
COMMON_COMMAND (teamstatus , "Show information about player and team scores")
Definition at line 151 of file common.qh.
References CommonCommand_teamstatus().
 { CommonCommand_teamstatus(request, caller); }
COMMON_COMMAND (time , "Print different formats/readouts of time")
Definition at line 152 of file common.qh.
References CommonCommand_time().
 { CommonCommand_time(request, caller); }
COMMON_COMMAND (timein , "Resume the game from being paused with a timeout")
Definition at line 153 of file common.qh.
References CommonCommand_timein().
 { CommonCommand_timein(request, caller); }
COMMON_COMMAND (timeout , "Call a timeout which pauses the game for certain amount of time unless unpaused")
Definition at line 154 of file common.qh.
References CommonCommand_timeout().
 { CommonCommand_timeout(request, caller); }
COMMON_COMMAND (vote , "Request an action to be voted upon by players")
Definition at line 155 of file common.qh.
References VoteCommand().
 { VoteCommand(request, caller, arguments, command); }
COMMON_COMMAND (who , "Display detailed client information about all players")
Definition at line 156 of file common.qh.
References CommonCommand_who().
 { CommonCommand_who(request, caller, arguments);}
void CommonCommand_cvar_changes (int request, entity caller)
Definition at line 283 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, cvar_changes, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, cvar_changes);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " cvar_changes"));
             print_to(caller, "  No arguments required.");
             print_to(caller, "See also: ^2cvar_purechanges^7");
             return;
         }
     }
 }
void CommonCommand_cvar_purechanges (int request, entity caller)
Definition at line 304 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, cvar_purechanges, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, cvar_purechanges);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " cvar_purechanges"));
             print_to(caller, "  No arguments required.");
             print_to(caller, "See also: ^2cvar_changes^7");
             return;
         }
     }
 }
void CommonCommand_editmob (int request, entity caller, int argc)
Definition at line 325 of file common.qc.
References argv(), autocvar_g_campaign, autocvar_g_monsters, autocvar_g_monsters_edit, autocvar_g_monsters_max, autocvar_g_monsters_max_perplayer, CENTER_OR_VIEWOFS, CMD_REQUEST_COMMAND, Damage(), DMG_NOWEP, entity(), FOREACH, ftos(), g_monsters, GetResource(), IL_CLEAR, IL_EACH, IS_DEAD, IS_MONSTER, IS_PLAYER, LOG_INFO, M_ARGV, Monster_Remove(), monsters_killed, monsters_total, MOVE_NORMAL, MUTATOR_CALLHOOK, NULL, print_to(), RES_HEALTH, spawn(), spawnmonster(), stof(), strcat(), totalspawned, trace_endpos, trace_ent, v_forward, WarpZone_TraceBox(), and WarpZone_TraceLine().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (autocvar_g_campaign) { print_to(caller, "Monster editing is disabled in singleplayer"); return; }
             // no checks for g_monsters here, as it may be toggled mid match which existing monsters
             if (caller)
             {
                 makevectors(caller.v_angle);
                 WarpZone_TraceLine(caller.origin + caller.view_ofs, caller.origin + caller.view_ofs + v_forward * 100, MOVE_NORMAL, caller);
             }
             entity mon = trace_ent;
             bool is_visible = IS_MONSTER(mon);
             string argument = argv(2);
             switch (argv(1))
             {
                 case "name":
                 {
                     if (!caller) { print_to(caller, "Only players can edit monsters"); return; }
                     if (!argument)   break;  // escape to usage
                     if (!autocvar_g_monsters_edit) { print_to(caller, "Monster editing is disabled"); return; }
                     if (mon.realowner != caller && autocvar_g_monsters_edit < 2) { print_to(caller, "This monster does not belong to you"); return; }
                     if (!is_visible) { print_to(caller, "You must look at your monster to edit it"); return; }
                     string mon_oldname = mon.monster_name;
                     mon.monster_name = argument;
                     if (mon.sprite)   WaypointSprite_UpdateSprites(mon.sprite, WP_Monster, WP_Null, WP_Null);
                     print_to(caller, sprintf("Your pet '%s' is now known as '%s'", mon_oldname, mon.monster_name));
                     return;
                 }
                 case "spawn":
                 {
                     if (!caller) { print_to(caller, "Only players can spawn monsters"); return; }
                     if (!argv(2))   break;  // escape to usage
                     int moveflag, tmp_moncount = 0;
                     string arg_lower = strtolower(argument);
                     moveflag = (argv(3)) ? stof(argv(3)) : 1;  // follow owner if not defined
                     if (arg_lower == "list") { print_to(caller, monsterlist_reply); return; }
                     IL_EACH(g_monsters, it.realowner == caller,
                     {
                         ++tmp_moncount;
                     });
                     if (!autocvar_g_monsters) { print_to(caller, "Monsters are disabled"); return; }
                     if (autocvar_g_monsters_max <= 0 || autocvar_g_monsters_max_perplayer <= 0) { print_to(caller, "Monster spawning is disabled"); return; }
                     if (!IS_PLAYER(caller)) { print_to(caller, "You must be playing to spawn a monster"); return; }
                     if (MUTATOR_CALLHOOK(AllowMobSpawning, caller)) { print_to(caller, M_ARGV(1, string)); return; }
                     if (caller.vehicle) { print_to(caller, "You can't spawn monsters while driving a vehicle"); return; }
                     if (STAT(FROZEN, caller)) { print_to(caller, "You can't spawn monsters while frozen"); return; }
                     if (IS_DEAD(caller)) { print_to(caller, "You can't spawn monsters while dead"); return; }
                     if (tmp_moncount >= autocvar_g_monsters_max) { print_to(caller, "The maximum monster count has been reached"); return; }
                     if (tmp_moncount >= autocvar_g_monsters_max_perplayer) { print_to(caller, "You can't spawn any more monsters"); return; }
                     bool found = false;
                     FOREACH(Monsters, it != MON_Null && it.netname == arg_lower,
                     {
                         found = true;
                         break;
                     });
                     if (!found && arg_lower != "random" && arg_lower != "anyrandom") { print_to(caller, "Invalid monster"); return; }
                     totalspawned += 1;
                     WarpZone_TraceBox(CENTER_OR_VIEWOFS(caller), caller.mins, caller.maxs, CENTER_OR_VIEWOFS(caller) + v_forward * 150, true, caller);
                     mon = spawnmonster(spawn(), arg_lower, 0, caller, caller, trace_endpos, false, false, moveflag);
                     print_to(caller, strcat("Spawned ", mon.monster_name));
                     return;
                 }
                 case "kill":
                 {
                     if (!caller) { print_to(caller, "Only players can kill monsters"); return; }
                     if (mon.realowner != caller && autocvar_g_monsters_edit < 2) { print_to(caller, "This monster does not belong to you"); return; }
                     if (!is_visible) { print_to(caller, "You must look at your monster to edit it"); return; }
                     Damage(mon, NULL, NULL, GetResource(mon, RES_HEALTH) + mon.max_health + 200, DEATH_KILL.m_id, DMG_NOWEP, mon.origin, '0 0 0');
                     print_to(caller, strcat("Your pet '", mon.monster_name, "' has been brutally mutilated"));
                     return;
                 }
                 case "skin":
                 {
                     if (!caller) { print_to(caller, "Only players can edit monsters"); return; }
                     if (!argument)   break;  // escape to usage
                     if (!autocvar_g_monsters_edit) { print_to(caller, "Monster editing is disabled"); return; }
                     if (!is_visible) { print_to(caller, "You must look at your monster to edit it"); return; }
                     if (mon.realowner != caller && autocvar_g_monsters_edit < 2) { print_to(caller, "This monster does not belong to you"); return; }
                     if (mon.monsterid == MON_MAGE.monsterid) { print_to(caller, "Mage skins can't be changed"); return; }  // TODO
                     mon.skin = stof(argument);
                     print_to(caller, strcat("Monster skin successfully changed to ", ftos(mon.skin)));
                     return;
                 }
                 case "movetarget":
                 {
                     if (!caller) { print_to(caller, "Only players can edit monsters"); return; }
                     if (!argument)   break;  // escape to usage
                     if (!autocvar_g_monsters_edit) { print_to(caller, "Monster editing is disabled"); return; }
                     if (!is_visible) { print_to(caller, "You must look at your monster to edit it"); return; }
                     if (mon.realowner != caller && autocvar_g_monsters_edit < 2) { print_to(caller, "This monster does not belong to you"); return; }
                     mon.monster_moveflags = stof(argument);
                     print_to(caller, strcat("Monster move target successfully changed to ", ftos(mon.monster_moveflags)));
                     return;
                 }
                 case "butcher":
                 {
                     if (caller) { print_to(caller, "This command is not available to players"); return; }
                     if (MUTATOR_CALLHOOK(AllowMobButcher)) { LOG_INFO(M_ARGV(0, string)); return; }
                     int tmp_remcount = 0;
                     IL_EACH(g_monsters, true,
                     {
                         Monster_Remove(it);
                         ++tmp_remcount;
                     });
                     IL_CLEAR(g_monsters);
                     monsters_total = monsters_killed = totalspawned = 0;
                     print_to(caller, (tmp_remcount) ? sprintf("Killed %d monster%s", tmp_remcount, (tmp_remcount == 1) ? "" : "s") : "No monsters to kill");
                     return;
                 }
             }
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " editmob command [arguments]"));
             print_to(caller, "  Where 'command' can be butcher spawn skin movetarget kill name");
             print_to(caller, "  spawn, skin, movetarget and name require 'arguments'");
             print_to(caller, "  spawn also takes arguments list and random");
             print_to(caller, "  Monster will follow owner if third argument of spawn command is not defined");
             return;
         }
     }
 }
void CommonCommand_info (int request, entity caller, int argc)
Definition at line 472 of file common.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             string command = builtin_cvar_string(strcat("sv_info_", argv(1)));
             if (command) wordwrap_sprint(caller, command, 1000);
             else print_to(caller, "ERROR: unsupported info command");
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " info request"));
             print_to(caller, "  Where 'request' is the suffixed string appended onto the request for cvar.");
             return;
         }
     }
 }
void CommonCommand_ladder (int request, entity caller)
Definition at line 496 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, ladder_reply);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " ladder"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_lsmaps (int request, entity caller)
Definition at line 516 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, lsmaps_reply);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " lsmaps"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
float CommonCommand_macro_command (int argc, entity caller, string command)
Definition at line 163 of file common.qh.
References argv(), CMD_REQUEST_COMMAND, and FOREACH.
Referenced by GameCommand(), and SV_ParseClientCommand().
 {
     string c = strtolower(argv(0));
     FOREACH(COMMON_COMMANDS, it.m_name == c, {
         it.m_invokecmd(it, CMD_REQUEST_COMMAND, caller, argc, command);
         return true;
     });
     return false;
 }
void CommonCommand_macro_help (entity caller)
Definition at line 158 of file common.qh.
References FOREACH, and print_to().
Referenced by GameCommand(), and SV_ParseClientCommand().
 {
     FOREACH(COMMON_COMMANDS, true, { print_to(caller, sprintf("  ^2%s^7: %s", it.m_name, it.m_description)); });
 }
float CommonCommand_macro_usage (int argc, entity caller)
Definition at line 173 of file common.qh.
References argv(), CMD_REQUEST_USAGE, and FOREACH.
Referenced by GameCommand(), and SV_ParseClientCommand().
 {
     string c = strtolower(argv(1));
     FOREACH(COMMON_COMMANDS, it.m_name == c, {
         it.m_invokecmd(it, CMD_REQUEST_USAGE, caller, argc, "");
         return true;
     });
     return false;
 }
void CommonCommand_macro_write_aliases (float fh)
Definition at line 183 of file common.qh.
References CMD_Write_Alias, and FOREACH.
Referenced by GENERIC_COMMAND().
 {
     FOREACH(COMMON_COMMANDS, true, { CMD_Write_Alias("qc_cmd_svcmd", it.m_name, it.m_description); });
 }
void CommonCommand_printmaplist (int request, entity caller)
Definition at line 536 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, maplist_reply);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " printmaplist"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_rankings (int request, entity caller)
Definition at line 556 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, rankings_reply);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " rankings"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_records (int request, entity caller)
Definition at line 576 of file common.qc.
References argv(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), stoi, and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             int num = stoi(argv(1));
             if(num > 0 && num <= 10 && records_reply[num - 1] != "")
                 print_to(caller, records_reply[num - 1]);
             else
             {
                 for (int i = 0; i < 10; ++i)
                     if (records_reply[i] != "") print_to(caller, records_reply[i]);
             }
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " records"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_teamstatus (int request, entity caller)
Definition at line 604 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCommandPrefix(), print_to(), Score_NicePrint(), and strcat().
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             Score_NicePrint(caller);
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " teamstatus"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_time (int request, entity caller)
Definition at line 624 of file common.qc.
References CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, ftos(), GetCommandPrefix(), gettime(), GETTIME_FRAMESTART, GETTIME_HIRES, GETTIME_REALTIME, GETTIME_UPTIME, print_to(), strcat(), and time.
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             print_to(caller, strcat("time = ", ftos(time)));
             print_to(caller, strcat("frame start = ", ftos(gettime(GETTIME_FRAMESTART))));
             print_to(caller, strcat("realtime = ", ftos(gettime(GETTIME_REALTIME))));
             print_to(caller, strcat("hires = ", ftos(gettime(GETTIME_HIRES))));
             print_to(caller, strcat("uptime = ", ftos(gettime(GETTIME_UPTIME))));
             print_to(caller, strcat("localtime = ", strftime(true, "%a %b %d %H:%M:%S %Z %Y")));
             print_to(caller, strcat("gmtime = ", strftime(false, "%a %b %d %H:%M:%S %Z %Y")));
             return;
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " time"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_timein (int request, entity caller)
Definition at line 650 of file common.qc.
References autocvar_sv_timeout, autocvar_sv_timeout_resumetime, bprint(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, GetCallerName(), GetCommandPrefix(), LOG_TRACE(), print_to(), strcat(), time, TIMEOUT_ACTIVE, timeout_caller, timeout_handler, TIMEOUT_INACTIVE, TIMEOUT_LEADTIME, timeout_status, and timeout_time.
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!caller || autocvar_sv_timeout)
             {
                 if (!timeout_status) { print_to(caller, "^7Error: There is no active timeout called."); }
                 else if (caller && (caller != timeout_caller))
                 {
                     print_to(caller, "^7Error: You are not allowed to stop the active timeout.");
                 }
                 else  // everything should be okay, continue aborting timeout
                 {
                     switch (timeout_status)
                     {
                         case TIMEOUT_LEADTIME:
{
                             timeout_status = TIMEOUT_INACTIVE;
                             timeout_time = 0;
                             timeout_handler.nextthink = time;  // timeout_handler has to take care of it immediately
                             bprint(strcat("^7The timeout was aborted by ", GetCallerName(caller), " !\n"));
                             return;
                         }
                         case TIMEOUT_ACTIVE:
{
                             timeout_time = autocvar_sv_timeout_resumetime;
                             timeout_handler.nextthink = time;  // timeout_handler has to take care of it immediately
                             bprint(strcat("^1Attention: ^7", GetCallerName(caller), " resumed the game! Prepare for battle!\n"));
                             return;
                         }
                         default: LOG_TRACE("timeout status was inactive, but this code was executed anyway?");
                             return;
                     }
                 }
             }
             else { print_to(caller, "^1Timeins are not allowed to be called, enable them with sv_timeout 1.\n"); }
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " timein"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_timeout (int request, entity caller)
Definition at line 705 of file common.qc.
References allowed_timeouts, autocvar_sv_timeout, autocvar_sv_timeout_leadtime, autocvar_sv_timeout_length, autocvar_timelimit, bprint(), CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, CS(), ftos(), g_warmup_allow_timeout, GetCallerName(), GetCommandPrefix(), IS_PLAYER, NULL, print_to(), setthink, spawn(), strcat(), time, timeout_caller, timeout_handler, timeout_handler_think(), TIMEOUT_LEADTIME, timeout_leadtime, timeout_status, timeout_time, vote_called, and warmup_stage.
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             if (!caller || autocvar_sv_timeout)
             {
                 float last_possible_timeout = ((autocvar_timelimit * 60) - autocvar_sv_timeout_leadtime - 1);
                 if (timeout_status) { print_to(caller, "^7Error: A timeout is already active."); }
                 else if (vote_called)
                 {
                     print_to(caller, "^7Error: You can not call a timeout while a vote is active.");
                 }
                 else if (warmup_stage && !g_warmup_allow_timeout)
                 {
                     print_to(caller, "^7Error: You can not call a timeout in warmup-stage.");
                 }
                 else if (time < game_starttime)
                 {
                     print_to(caller, "^7Error: You can not call a timeout while the map is being restarted.");
                 }
                 else if (caller && (CS(caller).allowed_timeouts < 1))
                 {
                     print_to(caller, "^7Error: You already used all your timeout calls for this map.");
                 }
                 else if (caller && !IS_PLAYER(caller))
                 {
                     print_to(caller, "^7Error: You must be a player to call a timeout.");
                 }
                 else if ((autocvar_timelimit) && (last_possible_timeout < time - game_starttime))
                 {
                     print_to(caller, "^7Error: It is too late to call a timeout now!");
                 }
                 else  // everything should be okay, proceed with starting the timeout
                 {
                     if (caller)   CS(caller).allowed_timeouts -= 1;
                     // write a bprint who started the timeout (and how many they have left)
                     bprint(GetCallerName(caller), " ^7called a timeout", (caller ? strcat(" (", ftos(CS(caller).allowed_timeouts), " timeout(s) left)") : ""), "!\n");
                     timeout_status = TIMEOUT_LEADTIME;
                     timeout_caller = caller;
                     timeout_time = autocvar_sv_timeout_length;
                     timeout_leadtime = autocvar_sv_timeout_leadtime;
                     timeout_handler = spawn();
                     setthink(timeout_handler, timeout_handler_think);
                     timeout_handler.nextthink = time;  // always let the entity think asap
                     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_TIMEOUT);
                 }
             }
             else { print_to(caller, "^1Timeouts are not allowed to be called, enable them with sv_timeout 1.\n"); }
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " timeout"));
             print_to(caller, "  No arguments required.");
             return;
         }
     }
 }
void CommonCommand_who (int request, entity caller, int argc)
Definition at line 774 of file common.qc.
References argv(), autocvar_sv_status_privacy, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, CS(), etof(), FOREACH_CLIENT, ftos(), GetCommandPrefix(), IS_BOT_CLIENT, jointime, maxclients, ping, ping_packetloss, print_to(), process_time(), strcat(), and time.
Referenced by COMMON_COMMAND().
 {
     switch (request)
     {
         case CMD_REQUEST_COMMAND:
         {
             float total_listed_players, is_bot;
             float privacy = (caller && autocvar_sv_status_privacy);
             string separator = strreplace("%", " ", strcat((argv(1) ? argv(1) : " "), "^7"));
             string tmp_netaddress, tmp_crypto_idfp;
             print_to(caller, strcat("List of client information", (privacy ? " (some data is hidden for privacy)" : ""), ":"));
             print_to(caller, sprintf(strreplace(" ", separator, " %-4s %-20s %-5s %-3s %-9s %-16s %s "),
                 "ent", "nickname", "ping", "pl", "time", "ip", "crypto_id"));
             total_listed_players = 0;
             FOREACH_CLIENT(true, {
                 is_bot = (IS_BOT_CLIENT(it));
                 if (is_bot)
                 {
                     tmp_netaddress = "null/botclient";
                     tmp_crypto_idfp = "null/botclient";
                 }
                 else if (privacy)
                 {
                     tmp_netaddress = "hidden";
                     tmp_crypto_idfp = "hidden";
                 }
                 else
                 {
                     tmp_netaddress = it.netaddress;
                     tmp_crypto_idfp = it.crypto_idfp;
                 }
                 print_to(caller, sprintf(strreplace(" ", separator, " #%-3d %-20.20s %-5d %-3d %-9s %-16s %s "),
                     etof(it),
                     it.netname,
                     CS(it).ping,
                     CS(it).ping_packetloss,
                     process_time(1, time - CS(it).jointime),
                     tmp_netaddress,
                     tmp_crypto_idfp));
                 ++total_listed_players;
             });
             print_to(caller, strcat("Finished listing ", ftos(total_listed_players), " client(s) out of ", ftos(maxclients), " slots."));
             return;  // never fall through to usage
         }
         default:
         case CMD_REQUEST_USAGE:
         {
             print_to(caller, strcat("\nUsage:^3 ", GetCommandPrefix(caller), " who [separator]"));
             print_to(caller, "  Where 'separator' is the optional string to separate the values with, default is a space.");
             return;
         }
     }
 }
string GetCallerName (entity caller)
Definition at line 29 of file common.qc.
References autocvar_sv_adminnick, and playername().
Referenced by CommonCommand_timein(), CommonCommand_timeout(), GameCommand_adminmsg(), GameCommand_stuffto(), VoteCommand_call(), VoteCommand_master(), and VoteStop().
 {
     if (caller) return playername(caller, false);
     else return ((autocvar_sv_adminnick != "") ? autocvar_sv_adminnick : "SERVER ADMIN"); // autocvar_hostname
 }
string GetClientErrorString_color (float clienterror, string original_input, string col)
Definition at line 53 of file common.qc.
References CLIENT_DOESNT_EXIST, CLIENT_NOT_BOT, CLIENT_NOT_REAL, and strcat().
 {
     switch (clienterror)
     {
         case CLIENT_DOESNT_EXIST:
         { return strcat(col, "Client '", original_input, col, "' doesn't exist");
         }
         case CLIENT_NOT_REAL:
         { return strcat(col, "Client '", original_input, col, "' is not real");
         }
         case CLIENT_NOT_BOT:
         { return strcat(col, "Client '", original_input, col, "' is not a bot");
         }
         default:
         { return "Incorrect usage of GetClientErrorString";
         }
     }
 }
string GetCommandPrefix (entity caller)
Definition at line 22 of file common.qc.
Referenced by CommonCommand_cvar_changes(), CommonCommand_cvar_purechanges(), CommonCommand_info(), CommonCommand_ladder(), CommonCommand_lsmaps(), CommonCommand_printmaplist(), CommonCommand_rankings(), CommonCommand_records(), CommonCommand_teamstatus(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), VoteCommand(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_no(), VoteCommand_status(), VoteCommand_stop(), and VoteCommand_yes().
 {
     if (caller) return "cmd";
     else return "sv_cmd";
 }
entity GetFilteredEntity (string input)
Definition at line 140 of file common.qc.
References entity(), FOREACH_CLIENT, NULL, stof(), substring(), and VerifyClientNumber().
Referenced by BanCommand_mute(), BanCommand_unmute(), ClientCommand_spectate(), GameCommand_adminmsg(), GameCommand_moveplayer(), and GetFilteredNumber().
 {
     entity selection;
     float tmp_number;
     if (substring(input, 0, 1) == "#") tmp_number = stof(substring(input, 1, -1));
     else tmp_number = stof(input);
     if (VerifyClientNumber(tmp_number))
     {
         selection = edict_num(tmp_number);
     }
     else
     {
         selection = NULL;
         FOREACH_CLIENT(true, {
             if(strdecolorize(it.netname) == strdecolorize(input))
             {
                 selection = it;
                 break; // no reason to keep looking
             }
         });
     }
     return selection;
 }
float GetFilteredNumber (string input)
Definition at line 168 of file common.qc.
References entity(), etof(), and GetFilteredEntity().
Referenced by GameCommand_moveplayer().
 {
     entity selection = GetFilteredEntity(input);
     float output;
     output = etof(selection);
     return output;
 }
entity GetIndexedEntity (int argc, float start_index)
Definition at line 79 of file common.qc.
References argv(), entity(), FOREACH_CLIENT, next_token, NULL, stof(), substring(), and VerifyClientNumber().
Referenced by BanCommand_kickban(), ClientCommand_minigame(), ClientCommand_tell(), GameCommand_anticheat(), GameCommand_defer_clear(), GameCommand_stuffto(), and VoteCommand_parse().
 {
     entity selection;
     float tmp_number, index;
     string tmp_string;
     next_token = -1;
     index = start_index;
     selection = NULL;
     if (argc > start_index)
     {
         if (substring(argv(index), 0, 1) == "#")
         {
             tmp_string = substring(argv(index), 1, -1);
             ++index;
             if (tmp_string != "")  // is it all one token? like #1
             {
                 tmp_number = stof(tmp_string);
             }
             else if (argc > index)  // no, it's two tokens? # 1
             {
                 tmp_number = stof(argv(index));
                 ++index;
             }
             else
             {
                 tmp_number = 0;
             }
         }
         else  // maybe it's ONLY a number?
         {
             tmp_number = stof(argv(index));
             ++index;
         }
         if (VerifyClientNumber(tmp_number))
         {
             selection = edict_num(tmp_number);  // yes, it was a number
         }
         else  // no, maybe it's a name?
         {
             FOREACH_CLIENT(true, {
                 if(strdecolorize(it.netname) == strdecolorize(argv(start_index)))
                 {
                     selection = it;
                     break; // no reason to keep looking
                 }
             });
             index = (start_index + 1);
         }
     }
     next_token = index;
     // print(strcat("start_index: ", ftos(start_index), ", next_token: ", ftos(next_token), ", edict: ", ftos(num_for_edict(selection)), ".\n"));
     return selection;
 }
void print_to (entity to, string input)
Definition at line 179 of file common.qc.
References print(), sprint(), and strcat().
Referenced by ClientCommand_tell(), CommonCommand_cvar_changes(), CommonCommand_cvar_purechanges(), CommonCommand_editmob(), CommonCommand_info(), CommonCommand_ladder(), CommonCommand_lsmaps(), CommonCommand_macro_help(), CommonCommand_printmaplist(), CommonCommand_rankings(), CommonCommand_records(), CommonCommand_teamstatus(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), MUTATOR_HOOKFUNCTION(), sandbox_ObjectSpawn(), Score_NicePrint_Player(), Score_NicePrint_Spectator(), Score_NicePrint_Spectators(), Score_NicePrint_Team(), ValidateMap(), VoteCommand(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_no(), VoteCommand_parse(), VoteCommand_status(), VoteCommand_stop(), and VoteCommand_yes().
 {
     if (to) sprint(to, strcat(input, "\n"));
     else print(input, "\n");
 }
STATIC_INIT (COMMON_COMMANDS_aliases)
Definition at line 17 of file common.qh.
References FOREACH, and localcmd.
{
     FOREACH(COMMON_COMMANDS, true, { localcmd(sprintf("alias %1$s \"%2$s %1$s ${* ?}\"\n", it.m_name, "qc_cmd_svcmd")); });
 }
void timeout_handler_reset (entity this)
Definition at line 190 of file common.qc.
References NULL, timeout_caller, timeout_leadtime, and timeout_time.
Referenced by timeout_handler_think().
 {
     timeout_caller = NULL;
     timeout_time = 0;
     timeout_leadtime = 0;
     delete(this);
 }
void timeout_handler_think (entity this)
Definition at line 199 of file common.qc.
References autocvar_sv_timeout_resumetime, cvar_set(), FOREACH_CLIENT, ftos(), IS_PLAYER, IS_REAL_CLIENT, nextthink, NULL, orig_slowmo, time, TIMEOUT_ACTIVE, timeout_handler_reset(), TIMEOUT_INACTIVE, TIMEOUT_LEADTIME, timeout_leadtime, TIMEOUT_SLOWMO_VALUE, timeout_status, and timeout_time.
Referenced by CommonCommand_timeout().
 {
     switch (timeout_status)
     {
         case TIMEOUT_ACTIVE:
         {
             if (timeout_time > 0)  // countdown is still going
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_TIMEOUT_ENDING, timeout_time);
                 if (timeout_time == autocvar_sv_timeout_resumetime) // play a warning sound when only <sv_timeout_resumetime> seconds are left
                     Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_PREPARE);
                 this.nextthink = time + TIMEOUT_SLOWMO_VALUE;       // think again in one second
                 timeout_time -= 1;                                  // decrease the time counter
             }
             else  // time to end the timeout
             {
                 Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_TIMEIN);
                 timeout_status = TIMEOUT_INACTIVE;
                 // reset the slowmo value back to normal
                 cvar_set("slowmo", ftos(orig_slowmo));
                 // unlock the view for players so they can move around again
                 FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), {
                     it.fixangle = false;
                 });
                 timeout_handler_reset(this);
             }
             return;
         }
         case TIMEOUT_LEADTIME:
         {
             if (timeout_leadtime > 0)  // countdown is still going
             {
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_TIMEOUT_BEGINNING, timeout_leadtime);
                 this.nextthink = time + 1; // think again in one second
                 timeout_leadtime -= 1;     // decrease the time counter
             }
             else  // time to begin the timeout
             {
                 timeout_status = TIMEOUT_ACTIVE;
                 // set the slowmo value to the timeout default slowmo value
                 cvar_set("slowmo", ftos(TIMEOUT_SLOWMO_VALUE));
                 // reset all the flood variables
                 FOREACH_CLIENT(true, {
                     it.nickspamcount = it.nickspamtime = it.floodcontrol_chat =
                         it.floodcontrol_chatteam = it.floodcontrol_chattell =
                             it.floodcontrol_voice = it.floodcontrol_voiceteam = 0;
                 });
                 // copy .v_angle to .lastV_angle for every player in order to fix their view during pause (see PlayerPreThink)
                 FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), {
                     it.lastV_angle = it.v_angle;
                 });
                 this.nextthink = time;  // think again next frame to handle it under TIMEOUT_ACTIVE code
             }
             return;
         }
         case TIMEOUT_INACTIVE:
         default:
         {
             timeout_handler_reset(this);
             return;
         }
     }
 }
float VerifyClientEntity (entity client, float must_be_real, float must_be_bots)
Definition at line 43 of file common.qc.
References CLIENT_ACCEPTABLE, CLIENT_DOESNT_EXIST, CLIENT_NOT_BOT, CLIENT_NOT_REAL, IS_BOT_CLIENT, IS_CLIENT, and IS_REAL_CLIENT.
Referenced by BanCommand_mute(), BanCommand_unmute(), ClientCommand_spectate(), ClientCommand_tell(), GameCommand_adminmsg(), GameCommand_anticheat(), GameCommand_defer_clear(), GameCommand_moveplayer(), GameCommand_stuffto(), invite_minigame(), and VoteCommand_parse().
 {
     if (!IS_CLIENT(client)) return CLIENT_DOESNT_EXIST;
     else if (must_be_real && !IS_REAL_CLIENT(client)) return CLIENT_NOT_REAL;
     else if (must_be_bots && !IS_BOT_CLIENT(client)) return CLIENT_NOT_BOT;
     return CLIENT_ACCEPTABLE;
 }
float VerifyClientNumber (float tmp_number)
Definition at line 73 of file common.qc.
References maxclients.
Referenced by GetFilteredEntity(), and GetIndexedEntity().
 {
     if ((tmp_number < 1) || (tmp_number > maxclients)) return false;
     else return true;
 }
float VerifyKickableEntity (entity client)
Definition at line 36 of file common.qc.
References CLIENT_ACCEPTABLE, CLIENT_NOT_REAL, and IS_REAL_CLIENT.
Referenced by BanCommand_kickban().
 {
     if (!IS_REAL_CLIENT(client)) return CLIENT_NOT_REAL;
     return CLIENT_ACCEPTABLE;
 }
Variable Documentation
float allowed_timeouts
Definition at line 53 of file common.qh.
Referenced by CommonCommand_timeout().
const float CLIENT_ACCEPTABLE = 1
Definition at line 32 of file common.qh.
Referenced by VerifyClientEntity(), and VerifyKickableEntity().
const float CLIENT_DOESNT_EXIST = -1
Definition at line 33 of file common.qh.
Referenced by GetClientErrorString_color(), and VerifyClientEntity().
const float CLIENT_NOT_BOT = -3
Definition at line 35 of file common.qh.
Referenced by GetClientErrorString_color(), and VerifyClientEntity().
const float CLIENT_NOT_REAL = -2
Definition at line 34 of file common.qh.
Referenced by GetClientErrorString_color(), VerifyClientEntity(), and VerifyKickableEntity().
vector lastV_angle
Definition at line 54 of file common.qh.
Referenced by PlayerThink().
float next_token
Definition at line 63 of file common.qh.
Referenced by BanCommand_kickban(), ClientCommand_tell(), GameCommand_stuffto(), GetIndexedEntity(), and VoteCommand_parse().
float orig_slowmo
Definition at line 49 of file common.qh.
Referenced by StartFrame(), and timeout_handler_think().
float sys_frametime
Definition at line 48 of file common.qh.
Referenced by anticheat_physics(), CSQCProjectile_SendEntity(), Monster_Spawn(), onslaught_controlpoint_icon_link(), pathlib_astar(), PingPLReport_Think(), StartFrame(), and SUB_NoImpactCheck().
const float TIMEOUT_ACTIVE = 2
Definition at line 40 of file common.qh.
Referenced by CommonCommand_timein(), ImpulseCommands(), PlayerThink(), Say(), timeout_handler_think(), and weapon_prepareattack_check().
entity timeout_caller
Definition at line 46 of file common.qh.
Referenced by CommonCommand_timein(), CommonCommand_timeout(), and timeout_handler_reset().
entity timeout_handler
Definition at line 47 of file common.qh.
Referenced by CommonCommand_timein(), and CommonCommand_timeout().
const float TIMEOUT_INACTIVE = 0
Definition at line 38 of file common.qh.
Referenced by CommonCommand_timein(), and timeout_handler_think().
const float TIMEOUT_LEADTIME = 1
Definition at line 39 of file common.qh.
Referenced by CommonCommand_timein(), CommonCommand_timeout(), StartFrame(), and timeout_handler_think().
float timeout_leadtime
Definition at line 51 of file common.qh.
Referenced by CommonCommand_timeout(), timeout_handler_reset(), and timeout_handler_think().
const float TIMEOUT_SLOWMO_VALUE = 0.0001
Definition at line 43 of file common.qh.
Referenced by timeout_handler_think().
float timeout_status
Definition at line 52 of file common.qh.
Referenced by ClientCommand_ready(), CommonCommand_timein(), CommonCommand_timeout(), ImpulseCommands(), PlayerThink(), Say(), StartFrame(), SV_ParseClientCommand_floodcheck(), timeout_handler_think(), VoteCommand_call(), VoteCommand_master(), and weapon_prepareattack_check().
float timeout_time
Definition at line 50 of file common.qh.
Referenced by CommonCommand_timein(), CommonCommand_timeout(), timeout_handler_reset(), and timeout_handler_think().