Xonotic: server/campaign.qh File Reference
server/campaign.qh File Reference
Defines
#define CAMPAIGN_H
#define CAMPAIGN_MAX_ENTRIES 2
Functions
void CampaignPreInit ()
void CampaignPostInit ()
void CampaignPreIntermission ()
void CampaignPostIntermission ()
void CampaignLevelWarp (float n)
Variables
string campaign_message
float campaign_bots_may_start
Define Documentation
#define CAMPAIGN_H
Definition at line 2 of file campaign.qh.
#define CAMPAIGN_MAX_ENTRIES 2
Definition at line 5 of file campaign.qh.
Function Documentation
void CampaignLevelWarp (float n)
Definition at line 275 of file campaign.qc.
References campaign_entries, campaign_level, CampaignFile_Load(), CampaignFile_Unload(), CampaignSetup(), and error().
Referenced by GameCommand_warp().
{
    if(n < 0)
        n = campaign_level + 1;
    CampaignFile_Unload();
    CampaignFile_Load(n, 1);
    if(campaign_entries)
        CampaignSetup(0);
    else
        error("Sorry, cheater. You are NOT WELCOME.");
    CampaignFile_Unload();
}
void CampaignPostInit ()
Definition at line 124 of file campaign.qc.
References autocvar__campaign_testrun, campaign_fraglimit, Campaign_Invalid(), campaign_timelimit, cvar_set(), cvar_set_normal, and ftos().
Referenced by spawnfunc().
{
    // now some sanity checks
    if(Campaign_Invalid())
        return;
    if(autocvar__campaign_testrun)
    {
        cvar_set("fraglimit", "0");
        cvar_set("timelimit", "0.01");
        cvar_set_normal("fraglimit", "0");
        cvar_set_normal("timelimit", "0.01");
    }
    else
    {
        cvar_set("fraglimit", ftos(campaign_fraglimit[0]));
        cvar_set("timelimit", ftos(campaign_timelimit[0]));
        cvar_set_normal("fraglimit", ftos(campaign_fraglimit[0]));
        cvar_set_normal("timelimit", ftos(campaign_timelimit[0]));
    }
}
void CampaignPostIntermission ()
Definition at line 252 of file campaign.qc.
References campaign_entries, campaign_index_var, campaign_message, campaign_name, campaign_won, CampaignFile_Unload(), CampaignSetup(), localcmd, LOG_DEBUG, and strunzone().
{
    // NOTE: campaign_won is 0 or 1, that is, points to the next level
    if(campaign_won && campaign_entries < 2)
    {
        // last map won!
        LOG_DEBUG("^2test run: campaign looks GOOD\n");
        localcmd("togglemenu 1\n");
        CampaignFile_Unload();
        return;
    }
    CampaignSetup(campaign_won);
    CampaignFile_Unload();
    strunzone(campaign_message);
    strunzone(campaign_index_var);
    strunzone(campaign_name);
    campaign_name = "";
}
void CampaignPreInit ()
Definition at line 72 of file campaign.qc.
References autocvar__campaign_index, autocvar__campaign_name, autocvar_g_campaign_skill, autocvar_sv_cheats, autocvar_sv_gravity, campaign_bots, campaign_botskill, campaign_entries, campaign_gametype, campaign_index_var, Campaign_Invalid(), campaign_level, campaign_longdesc, campaign_message, campaign_mutators, campaign_name, campaign_shortdesc, CampaignBailout(), CampaignFile_Load(), cvar(), cvar_campaignwrapper(), cvar_campaignwrapper_list, cvar_set(), cvar_set_campaignwrapper(), cvar_set_normal, cvar_string(), cvar_string_campaignwrapper(), ftos(), MapInfo_SwitchGameType(), MapInfo_Type_FromString(), strcat(), strunzone(), and strzone().
Referenced by spawnfunc().
{
    float baseskill;
    string title;
    if(autocvar_sv_cheats)
    {
        CampaignBailout("JOLLY CHEATS AHAHAHAHAHAHAH))");
        return;
    }
    campaign_level = autocvar__campaign_index;
    campaign_name = strzone(autocvar__campaign_name);
    campaign_index_var = strzone(strcat("g_campaign", campaign_name, "_index"));
    CampaignFile_Load(campaign_level, 2);
    if(campaign_entries < 1)
    {
        CampaignBailout("unknown map");
        return;
    }
    baseskill = autocvar_g_campaign_skill;
    baseskill = baseskill + campaign_botskill[0];
    if(baseskill < 0)
        baseskill = 0;
    cvar_set("sv_public", "0");
    cvar_set("pausable", "1");
    cvar_campaignwrapper_list = strzone(strcat("; ", campaign_mutators[0], "; "));
    cvar = cvar_campaignwrapper;
    cvar_string = cvar_string_campaignwrapper;
    cvar_set = cvar_set_campaignwrapper;
    cvar_set("g_campaign", "1");
    cvar_set("g_dm", "0");
    cvar_set("skill", ftos(baseskill));
    cvar_set("bot_number", ftos(campaign_bots[0]));
    MapInfo_SwitchGameType(MapInfo_Type_FromString(campaign_gametype[0]));
    // copy sv_gravity cvar, as the engine needs it too (sorry, this will mess
    // with the menu a little still...)
    cvar_set_normal("sv_gravity", ftos(autocvar_sv_gravity));
    if(Campaign_Invalid())
        return;
    title = campaign_shortdesc[0];
    title = strzone(strcat("Level ", ftos(campaign_level + 1), ": ", title));
    campaign_message = strzone(strcat(title, "\n^3\n", campaign_longdesc[0], "\n\n^1press jump to enter the game"));
    strunzone(title);
}
void CampaignPreIntermission ()
Definition at line 185 of file campaign.qc.
References autocvar__campaign_testrun, autocvar_fraglimit, autocvar_timelimit, bprint(), campaign_entries, campaign_index_var, campaign_level, campaign_name, campaign_won, CampaignSaveCvar(), cheatcount_total, checkrules_equality, cvar_normal(), FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, strcat(), and time.
Referenced by NextLevel().
{
    int won = 0;
    int lost = 0;
    string savevar;
    FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), LAMBDA(
        if(it.winning)
            won += 1;
        else
            lost += 1;
    ));
    if(autocvar__campaign_testrun)
    {
        campaign_won = 1;
        bprint("Campaign test run, advancing level.\n");
    }
    else if(won == 1 && lost == 0 && checkrules_equality == 0)
    {
        if(autocvar_timelimit != 0 && autocvar_fraglimit != 0 && time > autocvar_timelimit * 60) // checks if the timelimit has expired.
        {
            campaign_won = 0;
            bprint("Time's up! The current level has been LOST.\n");
            // sound!
        }
        else
        {
            campaign_won = 1;
            bprint("The current level has been WON.\n");
            // sound!
        }
    }
    else if(autocvar_timelimit != 0 && time > autocvar_timelimit * 60)
    {
        campaign_won = 0;
        bprint("Time's up! The current level has been LOST.\n");
        // sound!
    }
    else
    {
        campaign_won = 0;
        bprint("The current level has been LOST.\n");
        // sound!
    }
    if(campaign_won && cheatcount_total == 0 && !autocvar__campaign_testrun)
    {
        if(campaign_level == cvar_normal(campaign_index_var))
        {
            if(campaign_entries < 2)
            {
                // I have won
                savevar = strcat("g_campaign", campaign_name, "_won");
                CampaignSaveCvar(savevar, 1);
                // advance level (for menu to show it right)
                CampaignSaveCvar(campaign_index_var, campaign_level + 1);
            }
            else
            {
                // advance level
                CampaignSaveCvar(campaign_index_var, campaign_level + 1);
            }
        }
    }
}
Variable Documentation
float campaign_bots_may_start
Definition at line 16 of file campaign.qh.
Referenced by bot_think(), ClientCommand_join(), ClientConnect(), LeaveSpectatorMode(), Monster_Move(), and Monster_Move_2D().
string campaign_message
Definition at line 7 of file campaign.qh.
Referenced by CampaignPostIntermission(), CampaignPreInit(), and PrintWelcomeMessage().