Xonotic: lib/warpzone/client.qc File Reference
client.qc File Reference
#include "client.qh"
#include "common.qh"
Functions
void CL_RotateMoves (vector ang)
NET_HANDLE (ENT_CLIENT_WARPZONE, bool isnew)
NET_HANDLE (ENT_CLIENT_WARPZONE_CAMERA, bool isnew)
NET_HANDLE (ENT_CLIENT_WARPZONE_TELEPORTED, bool isnew)
void WarpZone_Fade_PreDraw (entity this)
vector WarpZone_FixNearClip (vector o, vector c0, vector c1, vector c2, vector c3)
void WarpZone_FixPMove ()
void WarpZone_FixView ()
void WarpZone_Shutdown ()
void WarpZone_Touch (entity this, entity toucher)
void WarpZone_View_Inside ()
void WarpZone_View_Outside ()
Variables
float autocvar_cl_rollkillspeed = 10
float warpzone_fixingview
float warpzone_fixingview_drawexteriormodel
Function Documentation
void CL_RotateMoves (vector ang)
Referenced by NET_HANDLE().
NET_HANDLE (ENT_CLIENT_WARPZONE , bool isnew)
Definition at line 29 of file client.qc.
References classname, enemy, max(), maxs, mins, modelindex, origin, scale, setpredraw, WarpZone_Fade_PreDraw(), warpzone_fadeend, warpzone_fadestart, warpzone_isboxy, WarpZone_SetUp(), and warpzone_warpzones_exist.
 {
     warpzone_warpzones_exist = 1;
     if (!this.enemy)
     {
         this.enemy = new(warpzone_from);
     }
     this.classname = "trigger_warpzone";
     int f = ReadByte();
     this.warpzone_isboxy = (f & 1);
     if(f & 4)
     {
         this.origin_x = ReadCoord();
         this.origin_y = ReadCoord();
         this.origin_z = ReadCoord();
     }
     else
         this.origin = '0 0 0';
     this.modelindex = ReadShort();
     this.mins_x = ReadCoord();
     this.mins_y = ReadCoord();
     this.mins_z = ReadCoord();
     this.maxs_x = ReadCoord();
     this.maxs_y = ReadCoord();
     this.maxs_z = ReadCoord();
     this.scale = ReadByte() / 16;
     this.enemy.oldorigin_x = ReadCoord();
     this.enemy.oldorigin_y = ReadCoord();
     this.enemy.oldorigin_z = ReadCoord();
     this.enemy.avelocity_x = ReadCoord();
     this.enemy.avelocity_y = ReadCoord();
     this.enemy.avelocity_z = ReadCoord();
     this.oldorigin_x = ReadCoord();
     this.oldorigin_y = ReadCoord();
     this.oldorigin_z = ReadCoord();
     this.avelocity_x = ReadCoord();
     this.avelocity_y = ReadCoord();
     this.avelocity_z = ReadCoord();
     if(f & 2)
     {
         this.warpzone_fadestart = ReadShort();
         this.warpzone_fadeend = max(this.warpzone_fadestart + 1, ReadShort());
     }
     else
     {
         this.warpzone_fadestart = 0;
         this.warpzone_fadeend = 0;
     }
     // common stuff
     WarpZone_SetUp(this, this.enemy.oldorigin, this.enemy.avelocity, this.oldorigin, this.avelocity);
     // link me
     //setmodel(this, this.model);
     setorigin(this, this.origin);
     setsize(this, this.mins, this.maxs);
     // how to draw
     // engine currently wants this
     setpredraw(this, WarpZone_Fade_PreDraw);
     //settouch(this, WarpZone_Touch);
     return true;
 }
NET_HANDLE (ENT_CLIENT_WARPZONE_CAMERA , bool isnew)
Definition at line 96 of file client.qc.
References avelocity, classname, drawmask, MASK_NORMAL, max(), maxs, mins, modelindex, oldorigin, origin, scale, setpredraw, WarpZone_Camera_SetUp(), warpzone_cameras_exist, WarpZone_Fade_PreDraw(), warpzone_fadeend, and warpzone_fadestart.
 {
     warpzone_cameras_exist = 1;
     this.classname = "func_warpzone_camera";
     int f = ReadByte();
     if(f & 4)
     {
         this.origin_x = ReadCoord();
         this.origin_y = ReadCoord();
         this.origin_z = ReadCoord();
     }
     else
         this.origin = '0 0 0';
     this.modelindex = ReadShort();
     this.mins_x = ReadCoord();
     this.mins_y = ReadCoord();
     this.mins_z = ReadCoord();
     this.maxs_x = ReadCoord();
     this.maxs_y = ReadCoord();
     this.maxs_z = ReadCoord();
     this.scale = ReadByte() / 16;
     this.oldorigin_x = ReadCoord();
     this.oldorigin_y = ReadCoord();
     this.oldorigin_z = ReadCoord();
     this.avelocity_x = ReadCoord();
     this.avelocity_y = ReadCoord();
     this.avelocity_z = ReadCoord();
     if(f & 2)
     {
         this.warpzone_fadestart = ReadShort();
         this.warpzone_fadeend = max(this.warpzone_fadestart + 1, ReadShort());
     }
     else
     {
         this.warpzone_fadestart = 0;
         this.warpzone_fadeend = 0;
     }
     // common stuff
     WarpZone_Camera_SetUp(this, this.oldorigin, this.avelocity);
     // engine currently wants this
     this.drawmask = MASK_NORMAL;
     // link me
     //setmodel(this, this.model);
     setorigin(this, this.origin);
     setsize(this, this.mins, this.maxs);
     // how to draw
     // engine currently wants this
     setpredraw(this, WarpZone_Fade_PreDraw);
     return true;
 }
NET_HANDLE (ENT_CLIENT_WARPZONE_TELEPORTED , bool isnew)
Definition at line 154 of file client.qc.
References checkextension(), CL_RotateMoves(), classname, vector(), VF_CL_VIEWANGLES, warpzone_transform, and WarpZone_TransformVAngles().
 {
     this.classname = "warpzone_teleported";
     vector v;
     v.x = ReadCoord();
     v.y = ReadCoord();
     v.z = ReadCoord();
     return = true;
     if (!isnew) return;
     this.warpzone_transform = v;
     setproperty(VF_CL_VIEWANGLES, WarpZone_TransformVAngles(this, getpropertyvec(VF_CL_VIEWANGLES)));
     if(checkextension("DP_CSQC_ROTATEMOVES"))
         CL_RotateMoves(v);
         //CL_RotateMoves('0 90 0');
 }
void WarpZone_Fade_PreDraw (entity this)
Definition at line 11 of file client.qc.
References alpha, bound(), checkpvs(), drawmask, MASK_NORMAL, maxs, mins, origin, vector(), VF_ORIGIN, vlen(), warpzone_fadeend, and warpzone_fadestart.
Referenced by NET_HANDLE().
 {
     vector org;
     org = getpropertyvec(VF_ORIGIN);
     if(!checkpvs(org, this)) // this makes sense as long as we don't support recursive warpzones
         this.alpha = 0;
     else if(this.warpzone_fadestart)
         this.alpha = bound(0, (this.warpzone_fadeend - vlen(org - this.origin - 0.5 * (this.mins + this.maxs))) / (this.warpzone_fadeend - this.warpzone_fadestart), 1);
     else
         this.alpha = 1;
     //printf("%v <-> %v\n", view_origin, this.origin + 0.5 * (this.mins + this.maxs));
     if(this.alpha <= 0)
         this.drawmask = 0;
     else
         this.drawmask = MASK_NORMAL;
 }
vector WarpZone_FixNearClip (vector o, vector c0, vector c1, vector c2, vector c3)
Definition at line 195 of file client.qc.
References entity(), max(), min(), vector(), WarpZone_Find(), and WarpZone_PlaneDist().
Referenced by WarpZone_FixView().
 {
     vector mi, ma;
     entity e;
     float pd;
     mi.x = min(o.x, c0_x, c1_x, c2_x, c3_x);
     ma.x = max(o.x, c0_x, c1_x, c2_x, c3_x);
     mi.y = min(o.y, c0_y, c1_y, c2_y, c3_y);
     ma.y = max(o.y, c0_y, c1_y, c2_y, c3_y);
     mi.z = min(o.z, c0_z, c1_z, c2_z, c3_z);
     ma.z = max(o.z, c0_z, c1_z, c2_z, c3_z);
     e = WarpZone_Find(mi, ma);
     if(e)
     {
         if(WarpZone_PlaneDist(e, o) < 0)
             return '0 0 0';
             // can't really be, though, but if it is, this is not my warpzone, but a random different one in the same mins/maxs
         pd = min(
                 WarpZone_PlaneDist(e, c0),
                 WarpZone_PlaneDist(e, c1),
                 WarpZone_PlaneDist(e, c2),
                 WarpZone_PlaneDist(e, c3)
             );
         if(pd < 0)
             return e.warpzone_forward * -pd;
     }
     return '0 0 0';
 }
void WarpZone_FixPMove ()
Definition at line 227 of file client.qc.
References entity(), input_angles, pmove_org, WarpZone_Find(), WarpZone_TransformOrigin(), and WarpZone_TransformVAngles().
 {
     entity e = WarpZone_Find(pmove_org, pmove_org);
     if(e)
     {
         pmove_org = WarpZone_TransformOrigin(e, pmove_org);
         input_angles = WarpZone_TransformVAngles(e, input_angles);
     }
 }
void WarpZone_FixView ()
Definition at line 240 of file client.qc.
References autocvar_cl_rollkillspeed, cvar(), entity(), frametime, max(), min(), vector(), VF_ANGLES, VF_CL_VIEWANGLES_Z, VF_ORIGIN, WarpZone_Find(), WarpZone_FixNearClip(), warpzone_save_view_angles, warpzone_save_view_origin, WarpZone_TransformOrigin(), WarpZone_TransformVAngles(), WarpZone_View_Inside(), and WarpZone_View_Outside().
Referenced by CSQC_UpdateView().
 {
     entity e;
     vector org, ang, nearclip, corner0, corner1, corner2, corner3, o;
     warpzone_save_view_origin = org = getpropertyvec(VF_ORIGIN);
     warpzone_save_view_angles = ang = getpropertyvec(VF_ANGLES);
     e = WarpZone_Find(org, org);
     if(e)
     {
         org = WarpZone_TransformOrigin(e, org);
         ang = WarpZone_TransformVAngles(e, ang);
         WarpZone_View_Inside();
     }
     else
         WarpZone_View_Outside();
 #ifndef KEEP_ROLL
     float rick;
     float f;
     static float rollkill;
     if (STAT(HEALTH) > 0 || STAT(HEALTH) == -666 || STAT(HEALTH) == -2342)
     {
         f = 0;
         // reset roll when passing through a warpzone that change player's roll angle
         if(autocvar_cl_rollkillspeed)
             f = max(0, (1 - frametime * autocvar_cl_rollkillspeed));
         if(rollkill)
             rollkill = 0;
     }
     else
     {
         f = 1;
         // roll the view when killed (v_deathtilt)
         if(autocvar_cl_rollkillspeed)
         {
             rollkill += frametime * autocvar_cl_rollkillspeed;
             f = min(1, rollkill);
         }
         else if(rollkill)
             rollkill = 0;
     }
     rick = getproperty(VF_CL_VIEWANGLES_Z);
     rick *= f;
     setproperty(VF_CL_VIEWANGLES_Z, rick);
     ang.z *= f;
 #endif
     setproperty(VF_ORIGIN, org);
     setproperty(VF_ANGLES, ang);
     nearclip = '0 0 1' * (cvar("r_nearclip") * 1.125);
     corner0 = cs_unproject('0 0 0' + nearclip);
     corner1 = cs_unproject('1 0 0' * cvar("vid_conwidth") + nearclip);
     corner2 = cs_unproject('0 1 0' * cvar("vid_conheight") + nearclip);
     corner3 = cs_unproject('1 0 0' * cvar("vid_conwidth") + '0 1 0' * cvar("vid_conheight") + nearclip);
     o = WarpZone_FixNearClip(org, corner0, corner1, corner2, corner3);
     if(o != '0 0 0')
         setproperty(VF_ORIGIN, org + o);
 }
void WarpZone_Shutdown ()
Definition at line 303 of file client.qc.
References WarpZone_View_Outside().
Referenced by Shutdown().
 {
     WarpZone_View_Outside();
 }
void WarpZone_Touch (entity this, entity toucher)
Definition at line 169 of file server.qc.
References bound(), enemy, frametime, IS_NOT_A_CLIENT, LOG_TRACE(), max(), MOVETYPE_FOLLOW, MOVETYPE_NONE, string_null, SUB_UseTargets(), target, target2, target3, time, vlen(), WarpZone_PlaneDist(), WarpZone_Teleport(), and WarpZoneLib_ExactTrigger_Touch().
 {
     if(toucher.classname == "trigger_warpzone")
         return;
     if(time <= toucher.warpzone_teleport_finishtime) // already teleported this frame
         return;
     // FIXME needs a better check to know what is safe to teleport and what not
     if((toucher.move_movetype == MOVETYPE_NONE && toucher.move_movetype == MOVETYPE_NONE) || toucher.move_movetype == MOVETYPE_FOLLOW || toucher.move_movetype == MOVETYPE_FOLLOW || toucher.tag_entity
 #ifdef CSQC
     || tag_networkentity
 #endif
     )
         return;
     if(WarpZoneLib_ExactTrigger_Touch(this, toucher))
         return;
     if(WarpZone_PlaneDist(this, toucher.origin + toucher.view_ofs) >= 0) // wrong side of the trigger_warpzone (don't teleport yet)
         return;
     float f;
     // number of frames we need to go back:
     //   dist = 16*sqrt(2) qu
     //   dist ~ 24 qu
     //   24 qu = v*t
     //   24 qu = v*frametime*n
     //       n = 24 qu/(v*frametime)
     // for clients go only one frame though, may be too irritating otherwise
     // but max 0.25 sec = 0.25/frametime frames
     //       24/(0.25/frametime)
     //       96*frametime
     float d;
     d = 24 + max(vlen(toucher.mins), vlen(toucher.maxs));
     if(IS_NOT_A_CLIENT(toucher))
         f = -d / bound(frametime * d * 1, frametime * vlen(toucher.velocity), d);
     else
         f = -1;
     if(WarpZone_Teleport(this, toucher, f, 0))
     {
 #ifdef SVQC
         string save1, save2;
         save1 = this.target; this.target = string_null;
         save2 = this.target3; this.target3 = string_null;
         SUB_UseTargets(this, toucher, toucher); // use toucher too?
         if (!this.target) this.target = save1;
         if (!this.target3) this.target3 = save2;
         save1 = this.target; this.target = string_null;
         save2 = this.target2; this.target2 = string_null;
         SUB_UseTargets(this.enemy, toucher, toucher); // use toucher too?
         if (!this.target) this.target = save1;
         if (!this.target2) this.target2 = save2;
 #endif
     }
     else
     {
         LOG_TRACE("WARPZONE FAIL AHAHAHAHAH))");
     }
 }
void WarpZone_View_Inside ()
Definition at line 181 of file client.qc.
References autocvar_chase_active, cvar(), cvar_set(), warpzone_fixingview, warpzone_fixingview_drawexteriormodel, and WarpZone_View_Outside().
Referenced by WarpZone_FixView().
 {
     if(autocvar_chase_active)
     {
         WarpZone_View_Outside();
         return;
     }
     if(warpzone_fixingview)
         return;
     warpzone_fixingview = 1;
     warpzone_fixingview_drawexteriormodel = cvar("r_drawexteriormodel");
     cvar_set("r_drawexteriormodel", "0");
 }
void WarpZone_View_Outside ()
Definition at line 173 of file client.qc.
References cvar_set(), ftos(), warpzone_fixingview, and warpzone_fixingview_drawexteriormodel.
Referenced by WarpZone_FixView(), WarpZone_Shutdown(), and WarpZone_View_Inside().
 {
     if(!warpzone_fixingview)
         return;
     warpzone_fixingview = 0;
     cvar_set("r_drawexteriormodel", ftos(warpzone_fixingview_drawexteriormodel));
 }
Variable Documentation
float autocvar_cl_rollkillspeed = 10
Definition at line 238 of file client.qc.
Referenced by WarpZone_FixView().
float warpzone_fixingview
Definition at line 170 of file client.qc.
Referenced by WarpZone_View_Inside(), and WarpZone_View_Outside().
float warpzone_fixingview_drawexteriormodel
Definition at line 171 of file client.qc.
Referenced by WarpZone_View_Inside(), and WarpZone_View_Outside().