Xonotic: server/portals.qh File Reference
portals.qh File Reference
Functions
vector Portal_ApplyTransformToPlayerAngle (vector transform, vector vangle)
void Portal_ClearAll (entity own)
void Portal_ClearAll_PortalsOnly (entity own)
void Portal_ClearAllLater (entity own)
void Portal_ClearWithID (entity own, float id)
float Portal_SpawnInPortalAtTrace (entity own, vector dir, float id)
float Portal_SpawnOutPortalAtTrace (entity own, vector dir, float id)
void Portal_Think (entity this)
Variables
float portal_id
entity portal_in
entity portal_out
Function Documentation
vector Portal_ApplyTransformToPlayerAngle (vector transform, vector vangle)
Definition at line 42 of file portals.qc.
References AnglesTransform_Apply(), fixedmakevectors, fixedvectoangles, v_forward, v_up, vector(), and vectoyaw().
Referenced by Portal_TeleportPlayer().
 {
     vector old_forward, old_up;
     vector old_yawforward;
     vector new_forward, new_up;
     vector new_yawforward;
     vector ang;
     ang = vangle;
     /*
        ang_x = bound(-89, mod(-ang_x + 180, 360) - 180, 89);
        ang = AnglesTransform_ApplyToVAngles(transform, ang);
      */
     // PLAYERS use different math
 #if !(POSITIVE_PITCH_IS_DOWN)
     ang.x = -ang.x;
 #endif
     //print("reference: ", vtos(AnglesTransform_ApplyToVAngles(transform, ang)), "\n");
     fixedmakevectors(ang);
     old_forward = v_forward;
     old_up = v_up;
     fixedmakevectors(ang.y * '0 1 0');
     old_yawforward = v_forward;
     // their aiming directions are portalled...
     new_forward = AnglesTransform_Apply(transform, old_forward);
     new_up = AnglesTransform_Apply(transform, old_up);
     new_yawforward = AnglesTransform_Apply(transform, old_yawforward);
     // but now find a new sense of direction
     // this is NOT easy!
     // assume new_forward points straight up.
     // What is our yaw?
     //
     // new_up could now point forward OR backward... which direction to choose?
     if(new_forward.z > 0.7 || new_forward.z < -0.7) // far up; in this case, the "up" vector points backwards
     {
         // new_yawforward and new_yawup define the new aiming half-circle
         // we "just" need to find out whether new_up or -new_up is in that half circle
         ang = fixedvectoangles(new_forward); // this still gets us a nice pitch value...
         if(new_up * new_yawforward < 0)
             new_up = -1 * new_up;
         ang.y = vectoyaw(new_up); // this vector is the yaw we want
         //print("UP/DOWN path: ", vtos(ang), "\n");
     }
     else
     {
         // good angles; here, "forward" suffices
         ang = fixedvectoangles(new_forward);
         //print("GOOD path: ", vtos(ang), "\n");
     }
 #if !(POSITIVE_PITCH_IS_DOWN)
     ang.x = -ang.x;
 #endif
     ang.z = vangle.z;
     return ang;
 }
void Portal_ClearAll (entity own)
Definition at line 576 of file portals.qc.
References Portal_ClearAll_PortalsOnly(), and W_Porto_Remove().
Referenced by checkpoint_passed(), ClientDisconnect(), and PutObserverInServer().
 {
     Portal_ClearAll_PortalsOnly(own);
     W_Porto_Remove(own);
 }
void Portal_ClearAll_PortalsOnly (entity own)
Definition at line 569 of file portals.qc.
References Portal_Remove().
Referenced by Portal_ClearAll().
 {
     if(own.portal_in)
         Portal_Remove(own.portal_in, 0);
     if(own.portal_out)
         Portal_Remove(own.portal_out, 0);
 }
void Portal_ClearAllLater (entity own)
Definition at line 599 of file portals.qc.
References Portal_ClearAllLater_PortalsOnly(), and W_Porto_Remove().
Referenced by PlayerDamage().
 {
     Portal_ClearAllLater_PortalsOnly(own);
     W_Porto_Remove(own);
 }
void Portal_ClearWithID (entity own, float id)
Definition at line 604 of file portals.qc.
References Portal_Disconnect(), and Portal_Remove().
 {
     if(own.portal_in)
         if(own.portal_in.portal_id == id)
         {
             if(own.portal_out)
                 Portal_Disconnect(own.portal_in, own.portal_out);
             Portal_Remove(own.portal_in, 0);
         }
     if(own.portal_out)
         if(own.portal_out.portal_id == id)
         {
             if(own.portal_in)
                 Portal_Disconnect(own.portal_in, own.portal_out);
             Portal_Remove(own.portal_out, 0);
         }
 }
float Portal_SpawnInPortalAtTrace (entity own, vector dir, float id)
Definition at line 659 of file portals.qc.
References entity(), fixedmakevectors, fixedvectoangles2, Portal_SetInPortal(), Portal_Spawn(), trace_endpos, trace_plane_normal, and vector().
 {
     entity portal;
     vector ang;
     vector org;
     org = trace_endpos;
     ang = fixedvectoangles2(trace_plane_normal, dir);
     fixedmakevectors(ang);
     portal = Portal_Spawn(own, org, ang);
     if(!portal)
         return 0;
     portal.portal_id = portal_id_val;
     Portal_SetInPortal(own, portal);
     return 1;
 }
float Portal_SpawnOutPortalAtTrace (entity own, vector dir, float id)
Definition at line 679 of file portals.qc.
References entity(), fixedmakevectors, fixedvectoangles2, Portal_SetOutPortal(), Portal_Spawn(), trace_endpos, trace_plane_normal, and vector().
 {
     entity portal;
     vector ang;
     vector org;
     org = trace_endpos;
     ang = fixedvectoangles2(trace_plane_normal, dir);
     fixedmakevectors(ang);
     portal = Portal_Spawn(own, org, ang);
     if(!portal)
         return 0;
     portal.portal_id = portal_id_val;
     Portal_SetOutPortal(own, portal);
     return 1;
 }
void Portal_Think (entity this)
Definition at line 455 of file portals.qc.
References aiment, autocvar_sv_gravity, enemy, entity(), error, fade_time, fixedmakevectors, FOREACH_CLIENT, frametime, IS_INDEPENDENT_PLAYER, IS_PLAYER, mangle, MAX_WEAPONSLOTS, nextthink, NULL, portal_activatetime, Portal_Remove(), Portal_Think_TryTeleportPlayer(), solid, SOLID_BBOX, SOLID_TRIGGER, time, vector(), and weaponentities.
Referenced by Portal_MakeInPortal(), and Portal_Spawn().
 {
     entity o;
     vector g;
 #ifdef PORTALS_ARE_NOT_SOLID
     // portal is being removed?
     if(this.solid != SOLID_TRIGGER)
         return; // possibly engine bug
     if(!this.enemy)
         error("Portal_Think called for a broken portal\n");
     o = this.aiment;
     this.solid = SOLID_BBOX;
     this.aiment = NULL;
     g = frametime * '0 0 -1' * autocvar_sv_gravity;
     fixedmakevectors(this.mangle);
     FOREACH_CLIENT(IS_PLAYER(it), {
         if(it != o)
             if(IS_INDEPENDENT_PLAYER(it) || IS_INDEPENDENT_PLAYER(o))
                 continue; // cannot go through someone else's portal
         if(it != o || time >= this.portal_activatetime)
             Portal_Think_TryTeleportPlayer(this, it, g);
         for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(it.(weaponentity).hook)
                 Portal_Think_TryTeleportPlayer(this, it.(weaponentity).hook, g);
         }
     });
     this.solid = SOLID_TRIGGER;
     this.aiment = o;
 #endif
     this.nextthink = time;
     if(this.fade_time && time > this.fade_time)
         Portal_Remove(this, 0);
 }
Variable Documentation
float portal_id
Definition at line 3 of file portals.qh.
entity portal_in
Definition at line 4 of file portals.qh.
entity portal_out
Definition at line 4 of file portals.qh.