Xonotic: common/gamemodes/gamemode/onslaught/sv_controlpoint.qc File Reference
sv_controlpoint.qc File Reference
#include "sv_controlpoint.qh"
Functions
bool cpicon_send (entity this, entity to, int sf)
void onslaught_controlpoint_icon_link (entity e, void(entity this) spawnproc)
Variables
bool iscaptured
Function Documentation
bool cpicon_send (entity this, entity to, int sf)
Definition at line 5 of file sv_controlpoint.qc.
References ceil(), count, CPSF_SETUP, CPSF_STATUS, health, max_health, owner, team, WriteByte(), and WriteCoord().
Referenced by onslaught_controlpoint_icon_link().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_CONTROLPOINT_ICON);
     if(sf & CPSF_SETUP)
         sf &= ~CPSF_STATUS;
     WriteByte(MSG_ENTITY, sf);
     if(sf & CPSF_SETUP)
     {
         WriteCoord(MSG_ENTITY, this.origin_x);
         WriteCoord(MSG_ENTITY, this.origin_y);
         WriteCoord(MSG_ENTITY, this.origin_z);
         WriteByte(MSG_ENTITY, this.health);
         WriteByte(MSG_ENTITY, this.max_health);
         WriteByte(MSG_ENTITY, this.count);
         WriteByte(MSG_ENTITY, this.team);
         WriteByte(MSG_ENTITY, this.owner.iscaptured);
     }
     if(sf & CPSF_STATUS)
     {
         WriteByte(MSG_ENTITY, this.team);
         if(this.health <= 0)
             WriteByte(MSG_ENTITY, 0);
         else
             WriteByte(MSG_ENTITY, ceil((this.health / this.max_health) * 255));
     }
     return true;
 }
void onslaught_controlpoint_icon_link (entity e, void(entity this) spawnproc)
Definition at line 37 of file sv_controlpoint.qc.
References cpicon_send(), setthink, sys_frametime, and time.
Referenced by ons_ControlPoint_Icon_Spawn().
 {
     Net_LinkEntity(e, true, 0, cpicon_send);
     setthink(e, spawnproc);
     e.nextthink = time * sys_frametime;
 }
Variable Documentation
bool iscaptured
Definition at line 3 of file sv_controlpoint.qc.