Xonotic: common/weapons/calculations.qh File Reference
calculations.qh File Reference
Functions
vector damage_explosion_calcpush (vector explosion_f, vector target_v, float speedfactor)
float explosion_calcpush_getmultiplier (vector explosion_v, vector target_v)
vector W_CalculateSpread (vector forward, float spread, float spreadfactor, float spreadstyle)
int W_GunAlign (entity this, int preferred_align)
Function Documentation
vector damage_explosion_calcpush (vector explosion_f, vector target_v, float speedfactor)
Definition at line 45 of file calculations.qc.
References explosion_calcpush_getmultiplier(), LOG_INFOF, v, and vector().
Referenced by Damage(), and MUTATOR_HOOKFUNCTION().
 {
     // if below 1, the formulas make no sense (and would cause superjumps)
     if(speedfactor < 1)
         return explosion_f;
 #if 0
     float m;
     // find m so that
     //   speedfactor * (1 + e) * m / (1 + m) == 1
     m = 1 / ((1 + 0) * speedfactor - 1);
     vector v;
     v = explosion_calcpush(explosion_f * speedfactor, m, target_v, 1, 0);
     // the factor we then get is:
     //   1
     LOG_INFOF("MASS: %f\nv: %v -> %v\nENERGY BEFORE == %f + %f = %f\nENERGY AFTER >= %f",
         m,
         target_v, target_v + v,
         target_v * target_v, m * explosion_f * speedfactor * explosion_f * speedfactor, target_v * target_v + m * explosion_f * speedfactor * explosion_f * speedfactor,
         (target_v + v) * (target_v + v));
     return v;
 #endif
     return explosion_f * explosion_calcpush_getmultiplier(explosion_f * speedfactor, target_v);
 }
float explosion_calcpush_getmultiplier (vector explosion_v, vector target_v)
Definition at line 7 of file calculations.qc.
References explosion_calcpush_getmultiplier(), and vector().
Referenced by damage_explosion_calcpush(), and explosion_calcpush_getmultiplier().
 {
     float a;
     a  = explosion_v * (explosion_v - target_v);
     if(a <= 0)
         // target is too fast to be hittable by this
         return 0;
     a /= (explosion_v * explosion_v);
         // we know we can divide by this, or above a would be == 0
     return a;
 }
vector W_CalculateSpread (vector forward, float spread, float spreadfactor, float spreadstyle)
Definition at line 187 of file calculations.qc.
References cliptoplane(), cos(), cross, error, findperpendicular(), gsl_ran_gaussian(), M_PI, normalize(), random(), randomvec(), sin(), solve_cubic_abcd(), sqrt(), and vector().
Referenced by W_SetupProjVelocity_Explicit().
 {
     float sigma;
     vector v1 = '0 0 0', v2;
     float dx, dy, r;
     spread *= spreadfactor; //g_weaponspreadfactor;
     if(spread <= 0)
         return forward;
     switch(spreadstyle)
     {
         case 0:
         {
             // this is the baseline for the spread value!
             // standard deviation: sqrt(2/5)
             // density function: sqrt(1-r^2)
             return forward + randomvec() * spread;
         }
         case 1:
         {
             // same thing, basically
             return normalize(forward + cliptoplane(randomvec() * spread, forward));
         }
         case 2:
         {
             // circle spread... has at sigma=1 a standard deviation of sqrt(1/2)
             sigma = spread * 0.89442719099991587855; // match baseline stddev
             v1 = findperpendicular(forward);
             v2 = cross(forward, v1);
             // random point on unit circle
             dx = random() * 2 * M_PI;
             dy = sin(dx);
             dx = cos(dx);
             // radius in our dist function
             r = random();
             r = sqrt(r);
             return normalize(forward + (v1 * dx + v2 * dy) * r * sigma);
         }
         case 3: // gauss 3d
         {
             sigma = spread * 0.44721359549996; // match baseline stddev
             // note: 2D gaussian has sqrt(2) times the stddev of 1D, so this factor is right
             v1 = forward;
             v1_x += gsl_ran_gaussian(sigma);
             v1_y += gsl_ran_gaussian(sigma);
             v1_z += gsl_ran_gaussian(sigma);
             return v1;
         }
         case 4: // gauss 2d
         {
             sigma = spread * 0.44721359549996; // match baseline stddev
             // note: 2D gaussian has sqrt(2) times the stddev of 1D, so this factor is right
             v1_x = gsl_ran_gaussian(sigma);
             v1_y = gsl_ran_gaussian(sigma);
             v1_z = gsl_ran_gaussian(sigma);
             return normalize(forward + cliptoplane(v1, forward));
         }
         case 5: // 1-r
         {
             sigma = spread * 1.154700538379252; // match baseline stddev
             v1 = findperpendicular(forward);
             v2 = cross(forward, v1);
             // random point on unit circle
             dx = random() * 2 * M_PI;
             dy = sin(dx);
             dx = cos(dx);
             // radius in our dist function
             r = random();
             r = solve_cubic_abcd(-2, 3, 0, -r) * '0 1 0';
             return normalize(forward + (v1 * dx + v2 * dy) * r * sigma);
         }
         case 6: // 1-r^2
         {
             sigma = spread * 1.095445115010332; // match baseline stddev
             v1 = findperpendicular(forward);
             v2 = cross(forward, v1);
             // random point on unit circle
             dx = random() * 2 * M_PI;
             dy = sin(dx);
             dx = cos(dx);
             // radius in our dist function
             r = random();
             r = sqrt(1 - r);
             r = sqrt(1 - r);
             return normalize(forward + (v1 * dx + v2 * dy) * r * sigma);
         }
         case 7: // (1-r) (2-r)
         {
             sigma = spread * 1.224744871391589; // match baseline stddev
             v1 = findperpendicular(forward);
             v2 = cross(forward, v1);
             // random point on unit circle
             dx = random() * 2 * M_PI;
             dy = sin(dx);
             dx = cos(dx);
             // radius in our dist function
             r = random();
             r = 1 - sqrt(r);
             r = 1 - sqrt(r);
             return normalize(forward + (v1 * dx + v2 * dy) * r * sigma);
         }
         default:
             error("g_projectiles_spread_style must be 0 (sphere), 1 (flattened sphere), 2 (circle), 3 (gauss 3D), 4 (gauss plane), 5 (linear falloff), 6 (quadratic falloff), 7 (stronger falloff)!");
     }
     return '0 0 0';
     /*
      * how to derive falloff functions:
      * rho(r) := (2-r) * (1-r);
      * a : 0;
      * b : 1;
      * rhor(r) := r * rho(r);
      * cr(t) := integrate(rhor(r), r, a, t);
      * scr(t) := integrate(rhor(r) * r^2, r, a, t);
      * variance : scr(b) / cr(b);
      * solve(cr(r) = rand * cr(b), r), programmmode:false;
      * sqrt(0.4 / variance), numer;
      */
 }
int W_GunAlign (entity this, int preferred_align)
Definition at line 169 of file calculations.qc.
References entity().
Referenced by findperpendicular(), FireGrapplingHook(), GrapplingHookThink(), W_Model(), and W_ResetGunAlign().
     {
         return this.m_gunalign > 0 ? this.m_gunalign : preferred_align;
     }