Xonotic: menu/xonotic/slider_decibels.qh File Reference
slider_decibels.qh File Reference
#include "slider.qh"
Classes
class XonoticDecibelsSlider
Functions
entity makeXonoticDecibelsSlider (float, float, float, string)
entity makeXonoticDecibelsSlider_T (float, float, float, string, string)
Function Documentation
entity makeXonoticDecibelsSlider (float , float , float , string)
Definition at line 38 of file slider_decibels.qc.
References makeXonoticDecibelsSlider_T(), and string_null.
 {
     return makeXonoticDecibelsSlider_T(theValueMin, theValueMax, theValueStep, theCvar, string_null);
 }
entity makeXonoticDecibelsSlider_T (float , float , float , string , string)
Definition at line 31 of file slider_decibels.qc.
References entity(), and NEW.
Referenced by makeXonoticDecibelsSlider(), and XonoticAudioSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticDecibelsSlider);
     me.configureXonoticSlider(me, theValueMin, theValueMax, theValueStep, theCvar, theTooltip);
     return me;
 }