Xonotic: client/miscfunctions.qh File Reference
miscfunctions.qh File Reference
Macros
#define draw_beginBoldFont() drawfont = FONT_USER + 2
#define draw_endBoldFont() drawfont = FONT_USER + 1
#define drawcharacter(position, character, scale, rgb, alpha, flag) drawcharacter_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
#define drawcolorcodedstring(position, text, scale, alpha, flag) drawcolorcodedstring_builtin(HUD_Shift(position), text, scale, alpha, flag)
#define drawcolorcodedstring2(position, text, scale, rgb, alpha, flag) drawcolorcodedstring2_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
#define drawfill(position, size, rgb, alpha, flag) drawfill_builtin(HUD_Shift(position), HUD_Scale(size), rgb, alpha, flag)
#define drawpic(position, pic, size, rgb, alpha, flag) drawpic_builtin(HUD_Shift(position), pic, HUD_Scale(size), rgb, alpha, flag)
#define drawpic_aspect(pos, pic, mySize, color, theAlpha, drawflag)
#define drawpic_aspect_skin(pos, pic, sz, color, theAlpha, drawflag)
#define drawpic_skin(pos, pic, sz, color, theAlpha, drawflag)
#define drawsetcliparea(xposition, yposition, w, h) drawsetcliparea_builtin(HUD_ShiftX(xposition), HUD_ShiftY(yposition), HUD_ScaleX(w), HUD_ScaleY(h))
#define drawstring(position, text, scale, rgb, alpha, flag) drawstring_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
#define HUD_ScaleX(f) (f * hud_scale.x)
#define HUD_ScaleY(f) (f * hud_scale.y)
#define HUD_ShiftX(f) (f + hud_shift.x + hud_shift.z * (f - hud_scale_center.x))
#define HUD_ShiftY(f) (f + hud_shift.y + hud_shift.z * (f - hud_scale_center.y))
#define IS_DEAD(s) (((s).classname == "csqcmodel") ? (s).csqcmodel_isdead : ((s).health <= 0))
#define SET_POS_AND_SZ_Y_ASPECT(allow_colors)
Functions
vector Accuracy_GetColor (float accuracy)
void Accuracy_LoadColors ()
void Accuracy_LoadLevels ()
void AuditLists ()
float cvar_or (string cv, float v)
void drawborderlines (float thickness, vector pos, vector dim, vector color, float theAlpha, float drawflag)
void DrawCircleClippedPic (vector centre, float radi, string pic, float f, vector rgb, float a, float drawflag)
void drawcolorcodedstring_aspect (vector pos, string text, vector sz, float theAlpha, float drawflag)
void drawcolorcodedstring_aspect_expanding (vector pos, string text, vector sz, float theAlpha, float drawflag, float fadelerp)
void drawcolorcodedstring_expanding (vector position, string text, vector theScale, float theAlpha, float flag, float fadelerp)
void drawpic_aspect_skin_expanding (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
void drawpic_aspect_skin_expanding_two (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
void drawpic_tiled (vector pos, string pic, vector sz, vector area, vector color, float theAlpha, float drawflag)
void drawstring_aspect (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag)
void drawstring_aspect_expanding (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag, float fadelerp)
void drawstring_expanding (vector position, string text, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
vector expandingbox_resize_centered_box_offset (float sz, vector boxsize, float boxxsizefactor)
float expandingbox_sizefactor_from_fadelerp (float fadelerp)
entity GetTeam (int Team, bool add)
vector HUD_GetFontsize (string cvarname)
vector HUD_Scale (vector v)
void HUD_Scale_Disable ()
void HUD_Scale_Enable ()
vector HUD_Shift (vector v)
void MoveToLast (entity e)
string playername (string thename, float teamid)
void PolyDrawModel (entity e)
float PolyDrawModelSurface (entity e, float i_s)
float PreviewExists (string name)
vector project_3d_to_2d (vector vec)
float RegisterPlayer (entity player)
float RegisterTeam (entity Team)
void RemovePlayer (entity player)
void RemoveTeam (entity Team)
vector Rotate (vector v, float a)
float stringwidth (string text, float handleColors, vector sz)
void update_mousepos ()
Variables
float _drawpic_imgaspect
vector _drawpic_imgsize
float _drawpic_oldsz
string _drawpic_picpath
vector _drawpic_sz
vector acc_col [MAX_ACCURACY_LEVELS]
float acc_col_loadtime
string acc_color_levels
float acc_lev [MAX_ACCURACY_LEVELS]
int acc_levels
vector drawfontscale
const int INITPRIO_DROPTOFLOOR = 20
const int INITPRIO_FINDTARGET = 10
const int INITPRIO_FIRST = 0
const int INITPRIO_GAMETYPE = 0
const int INITPRIO_GAMETYPE_FALLBACK = 1
const int INITPRIO_LAST = 99
const int INITPRIO_LINKDOORS = 91
const int INITPRIO_SETLOCATION = 90
const int MAX_ACCURACY_LEVELS = 10
entity players
float team_count
entity teams
Macro Definition Documentation
#define draw_beginBoldFont () drawfont = FONT_USER + 2
Definition at line 48 of file miscfunctions.qh.
Referenced by HUD_Ammo(), HUD_HealthArmor(), HUD_ModIcons(), HUD_Physics(), HUD_Powerups(), HUD_RaceTimer(), HUD_Score(), HUD_Timer(), Label_draw(), Label_recalcPositionWithText(), MapVote_Draw(), Scoreboard_Draw(), and XonoticPlayerModelSelector_draw().
#define draw_endBoldFont () drawfont = FONT_USER + 1
Definition at line 49 of file miscfunctions.qh.
Referenced by CSQC_Init(), draw_reset(), HUD_Ammo(), HUD_HealthArmor(), HUD_ModIcons(), HUD_Physics(), HUD_Powerups(), HUD_RaceTimer(), HUD_Score(), HUD_Timer(), Label_draw(), Label_recalcPositionWithText(), MapVote_Draw(), Scoreboard_Draw(), and XonoticPlayerModelSelector_draw().
#define drawcharacter (position, character, scale, rgb, alpha, flag) drawcharacter_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 79 of file miscfunctions.qh.
#define drawcolorcodedstring (position, text, scale, alpha, flag) drawcolorcodedstring_builtin(HUD_Shift(position), text, scale, alpha, flag)
Definition at line 85 of file miscfunctions.qh.
#define drawcolorcodedstring2 (position, text, scale, rgb, alpha, flag) drawcolorcodedstring2_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 88 of file miscfunctions.qh.
#define drawfill (position, size, rgb, alpha, flag) drawfill_builtin(HUD_Shift(position), HUD_Scale(size), rgb, alpha, flag)
Definition at line 91 of file miscfunctions.qh.
#define drawpic (position, pic, size, rgb, alpha, flag) drawpic_builtin(HUD_Shift(position), pic, HUD_Scale(size), rgb, alpha, flag)
Definition at line 76 of file miscfunctions.qh.
#define drawpic_aspect (pos, pic, mySize, color, theAlpha, drawflag)
Value:
MACRO_BEGIN {\
        _drawpic_imgsize = draw_getimagesize(pic);\
        if(_drawpic_imgsize != '0 0 0') {\
            _drawpic_imgaspect = _drawpic_imgsize.x/_drawpic_imgsize.y;\
            _drawpic_sz = mySize;\
            if(_drawpic_sz.x/_drawpic_sz.y > _drawpic_imgaspect) {\
                _drawpic_oldsz = _drawpic_sz.x;\
                _drawpic_sz.x = _drawpic_sz.y * _drawpic_imgaspect;\
                if(_drawpic_sz.x)\
                    drawpic(pos + eX * 0.5 * (_drawpic_oldsz - _drawpic_sz.x), pic, _drawpic_sz, color, theAlpha, drawflag);\
            } else {\
                _drawpic_oldsz = _drawpic_sz.y;\
                _drawpic_sz.y = _drawpic_sz.x / _drawpic_imgaspect;\
                if(_drawpic_sz.y)\
                    drawpic(pos + eY * 0.5 * (_drawpic_oldsz - _drawpic_sz.y), pic, _drawpic_sz, color, theAlpha, drawflag);\
            }\
        }\
    } MACRO_END
Definition at line 112 of file miscfunctions.qh.
#define drawpic_aspect_skin (pos, pic, sz, color, theAlpha, drawflag)
Value:
MACRO_BEGIN {\
        _drawpic_picpath = strcat(hud_skin_path, "/", pic);\
        if(precache_pic(_drawpic_picpath) == "") {\
            _drawpic_picpath = strcat("gfx/hud/default/", pic);\
        }\
        drawpic_aspect(pos, _drawpic_picpath, sz, color, theAlpha, drawflag);\
        _drawpic_picpath = string_null;\
    } MACRO_END
Definition at line 133 of file miscfunctions.qh.
Referenced by DrawAmmoItem(), DrawCAItem(), DrawDomItem(), DrawNumIcon_expanding(), drawpic_aspect_skin_expanding(), HUD_HealthArmor(), HUD_Mod_Keepaway(), HUD_Mod_KH(), HUD_Mod_NexBall(), HUD_Mod_Race(), HUD_Notify(), HUD_PressedKeys(), and Scoreboard_AccuracyStats_Draw().
#define drawpic_skin (pos, pic, sz, color, theAlpha, drawflag)
Value:
MACRO_BEGIN {\
        _drawpic_picpath = strcat(hud_skin_path, "/", pic);\
        if(precache_pic(_drawpic_picpath) == "") {\
            _drawpic_picpath = strcat("gfx/hud/default/", pic);\
        }\
        drawpic(pos, _drawpic_picpath, sz, color, theAlpha, drawflag);\
        _drawpic_picpath = string_null;\
    } MACRO_END
Definition at line 144 of file miscfunctions.qh.
Referenced by drawpic_aspect_skin_expanding_two(), HUD_Vote(), and Vehicles_drawHUD().
#define drawsetcliparea (xposition, yposition, w, h) drawsetcliparea_builtin(HUD_ShiftX(xposition), HUD_ShiftY(yposition), HUD_ScaleX(w), HUD_ScaleY(h))
Definition at line 94 of file miscfunctions.qh.
#define drawstring (position, text, scale, rgb, alpha, flag) drawstring_builtin(HUD_Shift(position), text, scale, rgb, alpha, flag)
Definition at line 82 of file miscfunctions.qh.
#define HUD_ScaleX (f) (f * hud_scale.x)
Definition at line 62 of file miscfunctions.qh.
Referenced by HUD_Scale().
#define HUD_ScaleY (f) (f * hud_scale.y)
Definition at line 63 of file miscfunctions.qh.
Referenced by HUD_Scale().
#define HUD_ShiftX (f) (f + hud_shift.x + hud_shift.z * (f - hud_scale_center.x))
Definition at line 64 of file miscfunctions.qh.
Referenced by HUD_Shift().
#define HUD_ShiftY (f) (f + hud_shift.y + hud_shift.z * (f - hud_scale_center.y))
Definition at line 65 of file miscfunctions.qh.
Referenced by HUD_Shift().
#define IS_DEAD (s) (((s).classname == "csqcmodel") ? (s).csqcmodel_isdead : ((s).health <= 0))
Definition at line 37 of file miscfunctions.qh.
Referenced by accuracy_isgooddamage(), bot_shouldattack(), bot_think(), botframe_autowaypoints(), buff_Think(), CA_count_alive_players(), ca_isEliminated(), ca_LastPlayerForTeam(), ChatBubbleThink(), CheatImpulse(), CheatsAllowed(), CheckRules_Player(), CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), ClientCommand_selectteam(), ClientKill_TeamChange(), CommonCommand_editmob(), CreatureFrame_FallDamage(), ctf_FlagThink(), Damage(), door_blocked(), door_generic_plat_blocked(), door_trigger_touch(), Drag_CanDrag(), DrownPlayer(), Fire_AddDamage(), Fire_ApplyDamage(), freezetag_isEliminated(), generic_plat_blocked(), havocbot_ai(), havocbot_ast_reset_role(), havocbot_ctf_reset_role(), havocbot_ctf_teamcount(), havocbot_ons_reset_role(), havocbot_role_ast_defense(), havocbot_role_ast_offense(), havocbot_role_ctf_carrier(), havocbot_role_ctf_defense(), havocbot_role_ctf_escort(), havocbot_role_ctf_middle(), havocbot_role_ctf_offense(), havocbot_role_ctf_retriever(), havocbot_role_cts(), havocbot_role_dom(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_generic(), havocbot_role_ka_carrier(), havocbot_role_ka_collector(), havocbot_role_kh_carrier(), havocbot_role_kh_defense(), havocbot_role_kh_freelancer(), havocbot_role_kh_offense(), havocbot_role_ons_offense(), havocbot_role_race(), IMPULSE(), instagib_ammocheck(), JoinBestTeam(), jumppad_push(), ka_TouchEvent(), kh_GetMissingTeams(), kh_Key_Touch(), kh_StartRound(), Monster_Anim(), Monster_Attack_Leap_Check(), Monster_Move_Target(), Monster_ValidTarget(), MUTATOR_HOOKFUNCTION(), ons_ControlPoint_Icon_Think(), ons_ControlPoint_Touch(), plat_center_touch(), plat_crush(), player_anim(), player_powerups(), PlayerPreThink(), PlayerUseKey(), PM_dodging(), race_StartCompleting(), REGISTER_MUTATOR(), ShowRespawnCountdown(), SV_ChangeTeam(), swamp_touch(), sys_phys_update(), Teleport_Touch(), vehicle_impulse(), vehicle_use(), vehicles_enter(), vehicles_exit(), vehicles_locktarget(), vehicles_setreturn(), WinningCondition_RanOutOfSpawns(), and X().
#define SET_POS_AND_SZ_Y_ASPECT (allow_colors)
Value:
MACRO_BEGIN {                                                           \
    float textaspect, oldsz;                                                                                       \
    vector dfs = drawfontscale; \
    drawfontscale = '1 1 0'; \
    textaspect = stringwidth(text, allow_colors, '1 1 1' * sz.y) / sz.y;                                            \
    drawfontscale = dfs; \
    if(sz.x/sz.y > textaspect) {                                                                                    \
        oldsz = sz.x;                                                                                               \
        sz.x = sz.y * textaspect;                                                                                   \
        pos.x += (oldsz - sz.x) * 0.5;                                                                              \
    } else {                                                                                                        \
        oldsz = sz.y;                                                                                               \
        sz.y = sz.x / textaspect;                                                                                   \
        pos.y += (oldsz - sz.y) * 0.5;                                                                              \
    }                                                                                                               \
} MACRO_END
Definition at line 158 of file miscfunctions.qh.
Referenced by drawcolorcodedstring_aspect(), drawcolorcodedstring_aspect_expanding(), drawstring_aspect(), and drawstring_aspect_expanding().
Function Documentation
vector Accuracy_GetColor (float accuracy)
Definition at line 605 of file miscfunctions.qc.
References acc_col, acc_lev, acc_levels, color, and vector().
Referenced by Scoreboard_AccuracyStats_Draw().
 {
     float factor;
     vector color;
     if(acc_levels < 2)
         return '0 0 0'; // return black, can't determine the right color
     // find the max level lower than acc
     int j = acc_levels-1;
     while(j && accuracy < acc_lev[j])
         --j;
     // inject color j+1 in color j, how much depending on how much accuracy is higher than level j
     factor = (accuracy - acc_lev[j]) / (acc_lev[j+1] - acc_lev[j]);
     color = acc_col[j];
     color = color + factor * (acc_col[j+1] - color);
     return color;
 }
void Accuracy_LoadColors ()
Definition at line 593 of file miscfunctions.qc.
References acc_col, acc_col_loadtime, acc_levels, cvar_string(), ftos(), stov(), strcat(), and time.
Referenced by Scoreboard_AccuracyStats_Draw().
 {
     if(time > acc_col_loadtime)
     if(acc_levels >= 2)
     {
         int i;
         for(i = 0; i < acc_levels; ++i)
             acc_col[i] = stov(cvar_string(strcat("accuracy_color", ftos(i))));
         acc_col_loadtime = time + 2;
     }
 }
void Accuracy_LoadLevels ()
Definition at line 574 of file miscfunctions.qc.
References acc_color_levels, acc_lev, acc_levels, argv(), autocvar_accuracy_color_levels, LOG_INFO, MAX_ACCURACY_LEVELS, stof(), strunzone(), strzone(), and tokenize_console.
Referenced by HUD_Draw().
 {
     if(autocvar_accuracy_color_levels != acc_color_levels)
     {
         if(acc_color_levels)
             strunzone(acc_color_levels);
         acc_color_levels = strzone(autocvar_accuracy_color_levels);
         acc_levels = tokenize_console(acc_color_levels);
         if(acc_levels > MAX_ACCURACY_LEVELS)
             acc_levels = MAX_ACCURACY_LEVELS;
         if(acc_levels < 2)
             LOG_INFO("Warning: accuracy_color_levels must contain at least 2 values\n");
         int i;
         for(i = 0; i < acc_levels; ++i)
             acc_lev[i] = stof(argv(i)) / 100.0;
     }
 }
void AuditLists ()
Definition at line 12 of file miscfunctions.qc.
References entity(), error, players, prev, strcat(), and teams.
Referenced by MoveToLast(), RegisterPlayer(), RegisterTeam(), RemovePlayer(), and RemoveTeam().
 {
     entity e;
     entity prev;
     prev = players;
     for(e = prev.sort_next; e; prev = e, e = e.sort_next)
     {
         if(prev != e.sort_prev)
             error(strcat("sort list chain error\nplease submit the output of 'prvm_edicts client' to the developers"));
     }
     prev = teams;
     for(e = prev.sort_next; e; prev = e, e = e.sort_next)
     {
         if(prev != e.sort_prev)
             error(strcat("sort list chain error\nplease submit the output of 'prvm_edicts client' to the developers"));
     }
 }
float cvar_or (string cv, float v)
Definition at line 174 of file miscfunctions.qc.
References cvar_string(), stof(), and v.
 {
     string s;
     s = cvar_string(cv);
     if(s == "")
         return v;
     else
         return stof(s);
 }
void drawborderlines (float thickness, vector pos, vector dim, vector color, float theAlpha, float drawflag)
Definition at line 215 of file miscfunctions.qc.
References drawfill(), and vector().
Referenced by GameTypeVote_DrawGameTypeItem(), and MapVote_DrawMapItem().
 {
     vector line_dim = '0 0 0';
     // left and right lines
     pos.x -= thickness;
     line_dim.x = thickness;
     line_dim.y = dim.y;
     drawfill(pos, line_dim, color, theAlpha, drawflag);
     drawfill(pos + (dim.x + thickness) * '1 0 0', line_dim, color, theAlpha, drawflag);
     // upper and lower lines
     pos.y -= thickness;
     line_dim.x = dim.x + thickness * 2; // make upper and lower lines longer
     line_dim.y = thickness;
     drawfill(pos, line_dim, color, theAlpha, drawflag);
     drawfill(pos + (dim.y + thickness) * '0 1 0', line_dim, color, theAlpha, drawflag);
 }
void DrawCircleClippedPic (vector centre, float radi, string pic, float f, vector rgb, float a, float drawflag)
Definition at line 399 of file miscfunctions.qc.
References cos(), fabs(), HUD_Scale(), HUD_Shift(), M_PI, sin(), v, and vector().
Referenced by HUD_Crosshair(), and HUD_Draw().
 {
     float d;
     vector ringsize, v, t;
     ringsize = radi * '1 1 0';
     centre = HUD_Shift(centre);
     ringsize = HUD_Scale(ringsize);
     float co = cos(f * 2 * M_PI);
     float si = sin(f * 2 * M_PI);
     float q = fabs(co) + fabs(si);
     co /= q;
     si /= q;
     if(f >= 1)
     {
         // draw full rectangle
         R_BeginPolygon(pic, drawflag);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y -= 0.5 * ringsize.y;    t -= '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         d = q - 1;
         if(d > 0)
         {
             R_BeginPolygon(pic, drawflag);
                 v = centre;         t = '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
                 v = centre;         t = '0.5 0.5 0';
                 v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
         }
     }
     else if(f > 0.75)
     {
         // draw upper and first triangle
         R_BeginPolygon(pic, drawflag);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         R_BeginPolygon(pic, drawflag);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y -= 0.5 * ringsize.y;    t -= '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         d = q - 0.75;
         if(d <= 0)
             R_EndPolygon();
     }
     else if(f > 0.5)
     {
         // draw upper triangle
         R_BeginPolygon(pic, drawflag);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
         d = q - 0.5;
         if(d > 0)
         {
             R_BeginPolygon(pic, drawflag);
                 v = centre;         t = '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
                 v = centre;         t = '0.5 0.5 0';
                 v.x -= 0.5 * ringsize.x;    t -= '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
         }
     }
     else if(f > 0.25)
     {
         // draw first triangle
         R_BeginPolygon(pic, drawflag);
             v = centre;         t = '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
             R_PolygonVertex(v, t, rgb, a);
             v = centre;         t = '0.5 0.5 0';
             v.y += 0.5 * ringsize.y;    t += '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         d = q - 0.25;
         if(d <= 0)
             R_EndPolygon();
     }
     else
     {
         d = q;
         if(d > 0)
         {
             R_BeginPolygon(pic, drawflag);
                 v = centre;         t = '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
                 v = centre;         t = '0.5 0.5 0';
                 v.x += 0.5 * ringsize.x;    t += '0.5 0.5 0';
                 R_PolygonVertex(v, t, rgb, a);
         }
     }
     if(d > 0)
     {
             v = centre;         t = '0.5 0.5 0';
             v.x += co * 0.5 * ringsize.x;   t += co * '0.5 0.5 0';
             v.y += si * 0.5 * ringsize.y;   t += si * '0.5 -0.5 0';
             R_PolygonVertex(v, t, rgb, a);
         R_EndPolygon();
     }
 }
void drawcolorcodedstring_aspect (vector pos, string text, vector sz, float theAlpha, float drawflag)
Definition at line 318 of file miscfunctions.qc.
References drawcolorcodedstring(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by HUD_Mod_Race(), and HUD_Vote().
{
     SET_POS_AND_SZ_Y_ASPECT(true);
     drawcolorcodedstring(pos, text, '1 1 0' * sz.y, theAlpha, drawflag);
 }
void drawcolorcodedstring_aspect_expanding (vector pos, string text, vector sz, float theAlpha, float drawflag, float fadelerp)
Definition at line 357 of file miscfunctions.qc.
References drawcolorcodedstring_expanding(), and SET_POS_AND_SZ_Y_ASPECT.
{
     SET_POS_AND_SZ_Y_ASPECT(true);
     drawcolorcodedstring_expanding(pos, text, '1 1 0' * sz.y, theAlpha, drawflag, fadelerp);
 }
void drawcolorcodedstring_expanding (vector position, string text, vector theScale, float theAlpha, float flag, float fadelerp)
Definition at line 346 of file miscfunctions.qc.
References drawcolorcodedstring(), drawfontscale, expandingbox_resize_centered_box_offset(), expandingbox_sizefactor_from_fadelerp(), hud_scale, and stringwidth_builtin().
Referenced by drawcolorcodedstring_aspect_expanding().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawfontscale = hud_scale * sz;
     // eventually replace with drawcolorcodedstring
     drawcolorcodedstring(position + expandingbox_resize_centered_box_offset(sz, theScale, stringwidth_builtin(text, true, theScale * (sz / drawfontscale.x)) / (theScale.x * sz)), text, theScale * (sz / drawfontscale.x), theAlpha * (1 - fadelerp), flag);
     drawfontscale = hud_scale;
 }
void drawpic_aspect_skin_expanding (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 260 of file miscfunctions.qc.
References drawpic_aspect_skin, expandingbox_resize_centered_box_offset(), and expandingbox_sizefactor_from_fadelerp().
Referenced by DrawNumIcon_expanding(), drawpic_aspect_skin_expanding_two(), and HUD_Mod_Keepaway().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawpic_aspect_skin(position + expandingbox_resize_centered_box_offset(sz, theScale, 1), pic, theScale * sz, rgb, theAlpha * (1 - fadelerp), flag);
 }
void drawpic_aspect_skin_expanding_two (vector position, string pic, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 268 of file miscfunctions.qc.
References drawpic_aspect_skin_expanding(), and drawpic_skin.
 {
     drawpic_aspect_skin_expanding(position, pic, theScale, rgb, theAlpha, flag, fadelerp);
     drawpic_skin(position, pic, theScale, rgb, theAlpha * fadelerp, flag);
 }
void drawpic_tiled (vector pos, string pic, vector sz, vector area, vector color, float theAlpha, float drawflag)
Definition at line 234 of file miscfunctions.qc.
References drawsubpic(), HUD_Scale(), HUD_Shift(), min(), and vector().
Referenced by HUD_Panel_HlBorder(), Scoreboard_AccuracyStats_Draw(), Scoreboard_MakeTable(), Scoreboard_MapStats_Draw(), and Scoreboard_Rankings_Draw().
 {
     pos = HUD_Shift(pos);
     sz = HUD_Scale(sz);
     area = HUD_Scale(area);
     vector current_pos = '0 0 0', end_pos, new_size = '0 0 0', ratio = '0 0 0';
     end_pos = pos + area;
     current_pos.y = pos.y;
     while (current_pos.y < end_pos.y)
     {
         current_pos.x = pos.x;
         while (current_pos.x < end_pos.x)
         {
             new_size.x = min(sz.x, end_pos.x - current_pos.x);
             new_size.y = min(sz.y, end_pos.y - current_pos.y);
             ratio.x = new_size.x / sz.x;
             ratio.y = new_size.y / sz.y;
             drawsubpic(current_pos, new_size, pic, '0 0 0', ratio, color, theAlpha, drawflag);
             current_pos.x += sz.x;
         }
         current_pos.y += sz.y;
     }
 }
void drawstring_aspect (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag)
Definition at line 312 of file miscfunctions.qc.
References drawstring(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by DrawAmmoItem(), DrawCAItem(), DrawDomItem(), DrawNumIcon_expanding(), HUD_Draw(), HUD_EngineInfo(), HUD_Mod_Race(), HUD_Physics(), HUD_Score(), HUD_Score_Rankings(), HUD_Timer(), HUD_Vote(), and race_showTime().
{
     SET_POS_AND_SZ_Y_ASPECT(false);
     drawstring(pos, text, '1 1 0' * sz.y, color, theAlpha, drawflag);
 }
void drawstring_aspect_expanding (vector pos, string text, vector sz, vector color, float theAlpha, float drawflag, float fadelerp)
Definition at line 341 of file miscfunctions.qc.
References drawstring_expanding(), and SET_POS_AND_SZ_Y_ASPECT.
Referenced by DrawNumIcon_expanding(), and race_showTime().
{
     SET_POS_AND_SZ_Y_ASPECT(false);
     drawstring_expanding(pos, text, '1 1 0' * sz.y, color, theAlpha, drawflag, fadelerp);
 }
void drawstring_expanding (vector position, string text, vector theScale, vector rgb, float theAlpha, float flag, float fadelerp)
Definition at line 323 of file miscfunctions.qc.
References drawfontscale, drawstring(), expandingbox_resize_centered_box_offset(), expandingbox_sizefactor_from_fadelerp(), hud_scale, HUD_Scale(), stringwidth_builtin(), and vector().
Referenced by drawstring_aspect_expanding(), and HUD_RaceTimer().
 {
     float sz;
     sz = expandingbox_sizefactor_from_fadelerp(fadelerp);
     drawfontscale = hud_scale * sz;
     vector dfs = drawfontscale;
     drawfontscale = sz * '1 1 0';
     float textaspect = stringwidth_builtin(text, false, theScale * (sz / drawfontscale.x)) / (theScale.x * sz);
     drawfontscale = dfs;
     drawstring(position + expandingbox_resize_centered_box_offset(sz, theScale, textaspect), text, HUD_Scale(theScale * (sz / drawfontscale.x)), rgb, theAlpha * (1 - fadelerp), flag);
     // width parameter:
     //    (scale_x * sz / drawfontscale.x) * drawfontscale.x * SIZE1 / (scale_x * sz)
     //    SIZE1
     drawfontscale = hud_scale;
 }
vector expandingbox_resize_centered_box_offset (float sz, vector boxsize, float boxxsizefactor)
Definition at line 209 of file miscfunctions.qc.
Referenced by drawcolorcodedstring_expanding(), drawpic_aspect_skin_expanding(), and drawstring_expanding().
 {
     boxsize.x *= boxxsizefactor; // easier interface for text
     return boxsize * (0.5 * (1 - sz));
 }
float expandingbox_sizefactor_from_fadelerp (float fadelerp)
Definition at line 204 of file miscfunctions.qc.
Referenced by drawcolorcodedstring_expanding(), drawpic_aspect_skin_expanding(), and drawstring_expanding().
 {
     return 1.2 / (1.2 - fadelerp);
 }
entity GetTeam (int Team, bool add)
Definition at line 120 of file miscfunctions.qc.
References entity(), new_pure, NULL, NUM_SPECTATOR, RegisterTeam(), TC, team, and teamslots.
Referenced by CSQC_Init(), HUD_InfoMessages(), NET_HANDLE(), and SetTeam().
 {
     TC(int, Team); TC(bool, add);
     int num = (Team == NUM_SPECTATOR) ? 16 : Team;
     if(teamslots[num])
         return teamslots[num];
     if (!add)
         return NULL;
     entity tm = new_pure(team);
     tm.team = Team;
     teamslots[num] = tm;
     RegisterTeam(tm);
     return tm;
 }
vector HUD_GetFontsize (string cvarname)
Definition at line 135 of file miscfunctions.qc.
References cvar_string(), stov(), v, and vector().
Referenced by Cmd_Scoreboard_SetFields(), MapVote_Draw(), and Scoreboard_Draw().
 {
     vector v;
     v = stov(cvar_string(cvarname));
     if(v.x == 0)
         v = '8 8 0';
     if(v.y == 0)
         v.y = v.x;
     v.z = 0;
     return v;
 }
vector HUD_Scale (vector v)
Definition at line 288 of file miscfunctions.qc.
References HUD_ScaleX, HUD_ScaleY, and v.
Referenced by DrawCircleClippedPic(), drawpic_tiled(), drawstring_expanding(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), and HUD_Radar().
 {
     v.x = HUD_ScaleX(v.x);
     v.y = HUD_ScaleY(v.y);
     return v;
 }
void HUD_Scale_Disable ()
Definition at line 274 of file miscfunctions.qc.
References drawfontscale, hud_scale, and hud_shift.
Referenced by CSQC_UpdateView(), HUD_Ammo(), HUD_CenterPrint(), HUD_Chat(), HUD_Draw(), Hud_Dynamic_Frame(), HUD_EngineInfo(), HUD_HealthArmor(), HUD_InfoMessages(), HUD_MinigameMenu(), HUD_MinigameStatus(), HUD_ModIcons(), HUD_Notify(), HUD_Physics(), HUD_Powerups(), HUD_PressedKeys(), HUD_QuickMenu(), HUD_RaceTimer(), HUD_Radar(), HUD_Score(), HUD_Timer(), HUD_Vote(), MapVote_Draw(), and Scoreboard_Draw().
 {
     hud_scale = '1 1 0';
     hud_shift = '0 0 0';
     drawfontscale = hud_scale;
 }
void HUD_Scale_Enable ()
Definition at line 281 of file miscfunctions.qc.
References drawfontscale, hud_scale, hud_scale_current, hud_shift, and hud_shift_current.
Referenced by HUD_Ammo(), HUD_CenterPrint(), HUD_Draw(), HUD_EngineInfo(), HUD_HealthArmor(), HUD_InfoMessages(), HUD_ModIcons(), HUD_Notify(), HUD_Physics(), HUD_Powerups(), HUD_PressedKeys(), HUD_RaceTimer(), HUD_Radar(), HUD_Score(), HUD_Timer(), HUD_Vote(), and Scoreboard_Draw().
 {
     hud_scale = hud_scale_current;
     hud_shift = hud_shift_current;
     drawfontscale = hud_scale;
 }
vector HUD_Shift (vector v)
Definition at line 295 of file miscfunctions.qc.
References HUD_ShiftX, HUD_ShiftY, and v.
Referenced by DrawCircleClippedPic(), drawpic_tiled(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), and HUD_Radar().
 {
     v.x = HUD_ShiftX(v.x);
     v.y = HUD_ShiftY(v.y);
     return v;
 }
void MoveToLast (entity e)
Definition at line 68 of file miscfunctions.qc.
References AuditLists(), entity(), and SORT_SWAP.
 {
     AuditLists();
     entity ent = e.sort_next;
     while(ent)
     {
         SORT_SWAP(ent, e);
         ent = e.sort_next;
     }
     AuditLists();
 }
string playername (string thename, float teamid)
Definition at line 161 of file miscfunctions.qc.
References strcat(), TC, Team_ColorCode(), and teamplay.
Referenced by CheatsAllowed(), ClientCommand_ready(), ClientConnect(), Draw_ShowNames(), DumpStats(), GameCommand_adminmsg(), GameCommand_defer_clear(), GameCommand_moveplayer(), GetCallerName(), NextLevel(), OriginalCallerName(), PlayerPreThink(), Say(), Score_NicePrint_Player(), Score_NicePrint_Spectator(), SetPlayerTeam(), and W_HitPlotOpen().
 {
     TC(int, teamid);
     string t;
     if (teamplay)
     {
         t = Team_ColorCode(teamid);
         return strcat(t, strdecolorize(thename));
     }
     else
         return strdecolorize(thename);
 }
void PolyDrawModel (entity e)
Definition at line 391 of file miscfunctions.qc.
References PolyDrawModelSurface().
Referenced by DrawDebugModel().
 {
     float i_s;
     for(i_s = 0; ; ++i_s)
         if(!PolyDrawModelSurface(e, i_s))
             break;
 }
float PolyDrawModelSurface (entity e, float i_s)
Definition at line 370 of file miscfunctions.qc.
References SPA_TEXCOORDS0, and vector().
Referenced by PolyDrawModel().
 {
     float i_t;
     float n_t;
     vector tri;
     string tex;
     tex = getsurfacetexture(e, i_s);
     if (!tex)
         return 0; // this is beyond the last one
     n_t = getsurfacenumtriangles(e, i_s);
     for(i_t = 0; i_t < n_t; ++i_t)
     {
         tri = getsurfacetriangle(e, i_s, i_t);
         R_BeginPolygon(tex, 0);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.x), getsurfacepointattribute(e, i_s, tri.x, SPA_TEXCOORDS0), '1 1 1', 1);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.y), getsurfacepointattribute(e, i_s, tri.y, SPA_TEXCOORDS0), '1 1 1', 1);
         R_PolygonVertex(getsurfacepoint(e, i_s, tri.z), getsurfacepointattribute(e, i_s, tri.z, SPA_TEXCOORDS0), '1 1 1', 1);
         R_EndPolygon();
     }
     return 1;
 }
float PreviewExists (string name)
Definition at line 147 of file miscfunctions.qc.
References autocvar_cl_readpicture_force, fexists(), and strcat().
Referenced by Cmd_MapVote_MapDownload(), GameTypeVote_ReadOption(), and MapVote_CheckPic().
 {
     if(autocvar_cl_readpicture_force)
         return false;
     if (fexists(strcat(name, ".tga"))) return true;
     if (fexists(strcat(name, ".png"))) return true;
     if (fexists(strcat(name, ".jpg"))) return true;
     if (fexists(strcat(name, ".pcx"))) return true;
     return false;
 }
vector project_3d_to_2d (vector vec)
Definition at line 184 of file miscfunctions.qc.
References cs_project_is_b0rked, vid_conheight, vid_height, and vid_width.
Referenced by AuxiliaryXhair_Draw2D(), DamageText::DamageText_draw2d(), Draw_ShowNames(), EnemyHitCheck(), HUD_Crosshair(), NET_HANDLE(), and turret_draw2d().
 {
     vec = cs_project(vec);
     if(cs_project_is_b0rked > 0)
     {
         vec.x *= vid_conwidth / vid_width;
         vec.y *= vid_conheight / vid_height;
     }
     return vec;
 }
float RegisterPlayer (entity player)
Definition at line 33 of file miscfunctions.qc.
References AuditLists(), entity(), error, and players.
Referenced by Playerchecker_Think().
 {
     entity pl;
     AuditLists();
     for(pl = players.sort_next; pl; pl = pl.sort_next)
         if(pl == player)
             error("Player already registered!");
     player.sort_next = players.sort_next;
     player.sort_prev = players;
     if(players.sort_next)
         players.sort_next.sort_prev = player;
     players.sort_next = player;
     AuditLists();
     return true;
 }
float RegisterTeam (entity Team)
Definition at line 80 of file miscfunctions.qc.
References assert_once, AuditLists(), entity(), eprint(), error, NUM_SPECTATOR, team_count, and teams.
Referenced by GetTeam().
 {
     assert_once(Team.team, eprint(Team));
     entity tm;
     AuditLists();
     for(tm = teams.sort_next; tm; tm = tm.sort_next)
         if(tm == Team)
             error("Team already registered!");
     Team.sort_next = teams.sort_next;
     Team.sort_prev = teams;
     if(teams.sort_next)
         teams.sort_next.sort_prev = Team;
     teams.sort_next = Team;
     if(Team.team && Team.team != NUM_SPECTATOR)
         ++team_count;
     AuditLists();
     return true;
 }
void RemovePlayer (entity player)
Definition at line 49 of file miscfunctions.qc.
References AuditLists(), entity(), error, parent, and players.
Referenced by Playerchecker_Think().
 {
     entity pl, parent;
     AuditLists();
     parent = players;
     for(pl = players.sort_next; pl && pl != player; pl = pl.sort_next)
         parent = pl;
     if(!pl)
     {
         error("Trying to remove a player which is not in the playerlist!");
         return;
     }
     parent.sort_next = player.sort_next;
     if(player.sort_next)
         player.sort_next.sort_prev = parent;
     AuditLists();
 }
void RemoveTeam (entity Team)
Definition at line 99 of file miscfunctions.qc.
References AuditLists(), entity(), LOG_INFO, NUM_SPECTATOR, parent, team_count, and teams.
 {
     entity tm, parent;
     AuditLists();
     parent = teams;
     for(tm = teams.sort_next; tm && tm != Team; tm = tm.sort_next)
         parent = tm;
     if(!tm)
     {
         LOG_INFO(_("Trying to remove a team which is not in the teamlist!"));
         return;
     }
     parent.sort_next = Team.sort_next;
     if(Team.sort_next)
         Team.sort_next.sort_prev = parent;
     if(Team.team && Team.team != NUM_SPECTATOR)
         --team_count;
     AuditLists();
 }
vector Rotate (vector v, float a)
Definition at line 116 of file vector.qh.
References cos(), sin(), and vec2.
Referenced by HUD_Radar(), teamradar_2dcoord_to_texcoord(), teamradar_texcoord_to_2dcoord(), and waypoint_getSymmetricalOrigin().
 {
     float a_sin = sin(a), a_cos = cos(a);
     return vec2(v.x * a_cos + v.y * a_sin, -v.x * a_sin + v.y * a_cos);
 }
float stringwidth (string text, float handleColors, vector sz)
Definition at line 302 of file miscfunctions.qc.
 {
     vector dfs = drawfontscale;
     drawfontscale = '1 1 0';
     float r = stringwidth_builtin(text, handleColors, sz);
     drawfontscale = dfs;
     return r;
 }
void update_mousepos ()
Definition at line 362 of file miscfunctions.qc.
References autocvar_menu_mouse_speed, bound(), getmousepos(), mousepos, and vid_conheight.
Referenced by HUD_Minigame_Mouse(), HUD_Panel_Mouse(), HUD_Radar_Mouse(), MapVote_Draw(), and QuickMenu_Mouse().
 {
     mousepos += getmousepos() * autocvar_menu_mouse_speed;
     mousepos.x = bound(0, mousepos.x, vid_conwidth);
     mousepos.y = bound(0, mousepos.y, vid_conheight);
 }
Variable Documentation
float _drawpic_imgaspect
Definition at line 107 of file miscfunctions.qh.
vector _drawpic_imgsize
Definition at line 108 of file miscfunctions.qh.
float _drawpic_oldsz
Definition at line 110 of file miscfunctions.qh.
string _drawpic_picpath
Definition at line 111 of file miscfunctions.qh.
vector _drawpic_sz
Definition at line 109 of file miscfunctions.qh.
vector acc_col[MAX_ACCURACY_LEVELS]
Definition at line 200 of file miscfunctions.qh.
Referenced by Accuracy_GetColor(), and Accuracy_LoadColors().
float acc_col_loadtime
Definition at line 201 of file miscfunctions.qh.
Referenced by Accuracy_LoadColors().
string acc_color_levels
Definition at line 203 of file miscfunctions.qh.
Referenced by Accuracy_LoadLevels().
float acc_lev[MAX_ACCURACY_LEVELS]
Definition at line 199 of file miscfunctions.qh.
Referenced by Accuracy_GetColor(), and Accuracy_LoadLevels().
int acc_levels
Definition at line 202 of file miscfunctions.qh.
Referenced by Accuracy_GetColor(), Accuracy_LoadColors(), and Accuracy_LoadLevels().
vector drawfontscale
Definition at line 47 of file miscfunctions.qh.
Referenced by DamageText::DamageText_draw2d(), Draw_ShowNames(), drawcolorcodedstring_expanding(), drawstring_expanding(), HUD_CenterPrint(), HUD_Scale_Disable(), HUD_Scale_Enable(), and stringwidth().
const int INITPRIO_DROPTOFLOOR = 20
Definition at line 11 of file miscfunctions.qh.
Referenced by droptofloor().
const int INITPRIO_FINDTARGET = 10
Definition at line 10 of file miscfunctions.qh.
Referenced by MUTATOR_HOOKFUNCTION(), REGISTER_MUTATOR(), SetBrushEntityModel(), and spawnfunc().
const int INITPRIO_FIRST = 0
Definition at line 7 of file miscfunctions.qh.
const int INITPRIO_GAMETYPE = 0
Definition at line 8 of file miscfunctions.qh.
Referenced by ctf_Initialize(), dom_Initialize(), invasion_Initialize(), ons_Initialize(), and REGISTER_MUTATOR().
const int INITPRIO_GAMETYPE_FALLBACK = 1
Definition at line 9 of file miscfunctions.qh.
Referenced by InitGameplayMode().
const int INITPRIO_LAST = 99
Definition at line 14 of file miscfunctions.qh.
const int INITPRIO_LINKDOORS = 91
Definition at line 13 of file miscfunctions.qh.
const int INITPRIO_SETLOCATION = 90
Definition at line 12 of file miscfunctions.qh.
Referenced by ctf_FlagSetup(), ka_SpawnBall(), ons_ControlPoint_Setup(), and ons_GeneratorSetup().
const int MAX_ACCURACY_LEVELS = 10
Definition at line 198 of file miscfunctions.qh.
Referenced by Accuracy_LoadLevels().
entity players
Definition at line 3 of file miscfunctions.qh.
Referenced by AuditLists(), CSQC_Init(), HUD_Quickmenu_PlayerListEntries(), HUD_Score(), HUD_Score_Rankings(), kh_GetMissingTeams(), kh_LoserTeam(), kh_StartRound(), RegisterPlayer(), RemovePlayer(), Scoreboard_Draw(), Scoreboard_MakeTable(), Scoreboard_UpdatePlayerPos(), Scoreboard_UpdatePlayerTeams(), and Shutdown().
float team_count
Definition at line 5 of file miscfunctions.qh.
Referenced by CSQCPlayer_ModelAppearance_Apply(), HUD_Mod_CA(), HUD_Mod_Dom(), HUD_Quickmenu_PlayerListEntries(), HUD_Score(), HUD_Score_Rankings(), RegisterTeam(), RemoveTeam(), and Scoreboard_MakeTable().
entity teams
Definition at line 4 of file miscfunctions.qh.
Referenced by assault_ScoreRules(), AuditLists(), CSQC_Init(), CSQCPlayer_ModelAppearance_Apply(), dom_DelayedInit(), freezetag_Initialize(), HUD_InfoMessages(), HUD_Score(), HUD_Score_Rankings(), invasion_DelayedInit(), kh_Initialize(), ons_ScoreRules(), rc_SetLimits(), REGISTER_MUTATOR(), RegisterTeam(), RemoveTeam(), Scoreboard_Draw(), Scoreboard_UpdateTeamPos(), ScoreRules_basics(), ScoreRules_generic(), Shutdown(), tdm_DelayedInit(), and XonoticTeamSelectDialog_showNotify().