Xonotic: menu/xonotic/dialog_settings_game.qc File Reference
dialog_settings_game.qc File Reference
#include "dialog_settings_game.qh"
#include "../gamesettings.qh"
Functions
METHOD (SettingSource, getEntry, entity(entity this, int i, void(string name, string icon) returns))
METHOD (SettingSource, getEntryTooltip, entity(entity this, int i, void(string theTooltip) returns))
METHOD (SettingSource, reload, int(entity this, string filter))
void XonoticRegisteredSettingsList_getNameIcon_cb (string _name, string _icon)
void XonoticRegisteredSettingsList_getTooltip_cb (string _tooltip)
if (!this.source.getEntry(this.source, i, XonoticRegisteredSettingsList_getNameIcon_cb)) return
if (isSelected)
else if (isFocused)
draw_Text (this.realUpperMargin *eY+(0.5 *this.realFontSize.x)*eX, s, this.realFontSize, '1 1 1', SKINALPHA_TEXT, 0)
if (theTooltip!="") setZonedTooltip(this
else clearTooltip (this)
this onChange (this, this.onChangeEntity)
CONSTRUCTOR (XonoticRegisteredSettingsList, DataSource _source)
if (removing==adding) return
if (adding)
this gotoRC (this, 0, col)
this TD (this, this.rows, width, topics)
this setFirstColumn (this, this.currentColumn)
this TD (this, this.rows, width, this.currentPanel)
this topicChangeNotify (topics, this)
Variables
string XonoticRegisteredSettingsList_cb_name
string XonoticRegisteredSettingsList_cb_tooltip
string name = XonoticRegisteredSettingsList_cb_name
string s = draw_TextShortenToWidth(strdecolorize(name), 1, 0, this.realFontSize)
theTooltip
string_null
this itemAbsSize = '0 0 0'
this realFontSize_y = this.fontSize / (this.itemAbsSize_y = (absSize.y * this.itemHeight))
this realFontSize_x = this.fontSize / (this.itemAbsSize_x = (absSize.x * (1 - this.controlWidth)))
this realUpperMargin = 0.5 * (1 - this.realFontSize.y)
entity removing = this.currentItem
DataSource data = this.topicList.source
entity adding = data.getEntry(data, this.topicList.selectedItem, func_null)
topics onChange = this.topicChangeNotify
topics onChangeEntity = this
int col = 0
int width = 1
Function Documentation
else clearTooltip (this)
Referenced by ServerList_Update_favoriteButton(), XonoticGametypeList_focusedItemChangeNotify(), XonoticServerList_focusedItemChangeNotify(), and XonoticServerList_mouseMove().
CONSTRUCTOR (XonoticRegisteredSettingsList , DataSource _source)
Definition at line 88 of file dialog_settings_game.qc.
References CONSTRUCT.
{
     CONSTRUCT(XonoticRegisteredSettingsList);
     this.source = _source;
     this.configureXonoticListBox(this);
     this.refilter(this);
 }
draw_Text (this.realUpperMargin *eY+(0.5 *this.realFontSize.x)* eX, s , this. realFontSize, '1 1 1' , SKINALPHA_TEXT , 0)
this gotoRC (this , 0 , col)
if (!this.source. getEntrythis.source, i, XonoticRegisteredSettingsList_getNameIcon_cb)
if (isSelected)
Definition at line 37 of file dialog_settings_game.qc.
References draw_Fill().
                     {
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     } else if (isFocused) {
else if (isFocused)
Definition at line 39 of file dialog_settings_game.qc.
{
         this.focusedItemAlpha = getFadedAlpha(this.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, this.focusedItemAlpha);
     }
if (theTooltip! = "")
if (removing = = adding)
Definition at line 102 of file dialog_settings_game.qc.
References NULL.
                   {
         this.currentItem = NULL;
         c.removeItem(c, removing);
     }
if (adding)
Definition at line 106 of file dialog_settings_game.qc.
References adding.
                 {
         this.currentItem = adding;
         adding.resizeNotify(adding, '0 0 0', c.size, '0 0 0', c.size);
         c.addItem(c, adding, '0 0 0', '1 1 0', 1);
     }
METHOD (SettingSource , getEntry , entity(entity this, int i, void(string name, string icon) returns))
Definition at line 5 of file dialog_settings_game.qc.
References entity(), l, and string_null.
 {
     Lazy l = Settings_from(i);
     entity it = l.m_get();
     if (returns) returns(it.title, string_null);
     return it;
 }
METHOD (SettingSource , getEntryTooltip , entity(entity this, int i, void(string theTooltip) returns))
Definition at line 12 of file dialog_settings_game.qc.
References entity(), and l.
 {
     Lazy l = Settings_from(i);
     entity it = l.m_get();
     if (returns) returns(it.tooltip);
     return it;
 }
METHOD (SettingSource , reload , int(entity this, string filter))
Definition at line 19 of file dialog_settings_game.qc.
 { return Settings_COUNT; }
this onChange (this , this. onChangeEntity)
this setFirstColumn (this , this. currentColumn)
this TD (this , this. rows, width , topics)
this TD (this , this. rows, width , this. currentPanel)
this topicChangeNotify (topics , this)
void XonoticRegisteredSettingsList_getNameIcon_cb (string _name, string _icon)
Definition at line 23 of file dialog_settings_game.qc.
 {
     XonoticRegisteredSettingsList_cb_name = _name;
 }
void XonoticRegisteredSettingsList_getTooltip_cb (string _tooltip)
Definition at line 27 of file dialog_settings_game.qc.
 {
     XonoticRegisteredSettingsList_cb_tooltip = _tooltip;
 }
Variable Documentation
entity adding = data.getEntry(data, this.topicList.selectedItem, func_null)
Definition at line 100 of file dialog_settings_game.qc.
Referenced by cvar_changes_init(), and if().
col = 0
Definition at line 119 of file dialog_settings_game.qc.
Referenced by Dialog_gotoRC(), Dialog_setFirstColumn(), getlsmaps(), getmaplist(), getmonsterlist(), and MakeRaceString().
DataSource data = this.topicList.source
Definition at line 99 of file dialog_settings_game.qc.
Referenced by XonoticStatsList_drawListBoxItem(), and XonoticStatsList_getStats().
this itemAbsSize = '0 0 0'
Definition at line 78 of file dialog_settings_game.qc.
string name = XonoticRegisteredSettingsList_cb_name
Definition at line 36 of file dialog_settings_game.qc.
topics onChange = this.topicChangeNotify
Definition at line 115 of file dialog_settings_game.qc.
topics onChangeEntity = this
Definition at line 116 of file dialog_settings_game.qc.
this realFontSize_x = this.fontSize / (this.itemAbsSize_x = (absSize.x * (1 - this.controlWidth)))
Definition at line 80 of file dialog_settings_game.qc.
this realFontSize_y = this.fontSize / (this.itemAbsSize_y = (absSize.y * this.itemHeight))
Definition at line 79 of file dialog_settings_game.qc.
this realUpperMargin = 0.5 * (1 - this.realFontSize.y)
Definition at line 81 of file dialog_settings_game.qc.
entity removing = this.currentItem
Definition at line 98 of file dialog_settings_game.qc.
string s = draw_TextShortenToWidth(strdecolorize(name), 1, 0, this.realFontSize)
Definition at line 43 of file dialog_settings_game.qc.
string_null
Definition at line 61 of file dialog_settings_game.qc.
Referenced by METHOD().
theTooltip
Definition at line 61 of file dialog_settings_game.qc.
width = 1
Definition at line 119 of file dialog_settings_game.qc.
Referenced by draw_BorderPicture(), draw_ButtonPicture(), Draw_ShowNames(), draw_VertButtonPicture(), GetOrthoviewFOV(), HUD_Panel_DrawProgressBar(), and updateConwidths().
string XonoticRegisteredSettingsList_cb_name
Definition at line 21 of file dialog_settings_game.qc.
string XonoticRegisteredSettingsList_cb_tooltip
Definition at line 22 of file dialog_settings_game.qc.