Xonotic: CaptureTheFlag Class Reference
CaptureTheFlag Class Reference
Public Member Functions
CaptureTheFlag ()
ATTRIB (Gametype, netname, string)
game type name as in cvar (with g_ prefix)
ATTRIB (Gametype, mdl, string)
game type short name
ATTRIB (Gametype, message, string)
human readable name
ATTRIB (Gametype, model2, string)
game type defaults
ATTRIB (Gametype, gametype_description, string)
game type description
ATTRIB (Gametype, m_mutators, string)
virtual void describe ()
virtual void display ()
virtual void gametype_init ()
virtual void m_generate_mapinfo ()
virtual void m_isAlwaysSupported ()
virtual void m_isTwoBaseMode ()
virtual void m_parse_mapinfo ()
virtual void m_setTeams ()
Public Attributes
int items = 0
game type ID
int m_id = 0
bool team = false
does this gametype support teamplay?
Detailed Description
Definition at line 217 of file mapinfo.qh.
Constructor & Destructor Documentation
CaptureTheFlag::CaptureTheFlag () inline
Definition at line 218 of file mapinfo.qh.
     {
         this.gametype_init(this, _("Capture the Flag"),"ctf","g_ctf",true,"","timelimit=20 caplimit=10 leadlimit=6",_("Find and bring the enemy flag to your base to capture it, defend your base from the other team"));
     }
Member Function Documentation
Gametype::ATTRIB (Gametype , netname , string) inherited
game type name as in cvar (with g_ prefix)
Gametype::ATTRIB (Gametype , mdl , string) inherited
game type short name
Gametype::ATTRIB (Gametype , message , string) inherited
human readable name
Gametype::ATTRIB (Gametype , model2 , string) inherited
game type defaults
Gametype::ATTRIB (Gametype , gametype_description , string) inherited
game type description
Gametype::ATTRIB (Gametype , m_mutators , string) inherited
virtual void Gametype::describe () inline virtual inherited
Definition at line 61 of file mapinfo.qh.
References TC.
     {
         TC(Gametype, this);
         return this.gametype_description;
     }
virtual void Gametype::display () inline virtual inherited
Definition at line 67 of file mapinfo.qh.
References strcat(), and TC.
     {
         TC(Gametype, this);
         returns(this.message, strcat("gametype_", this.mdl));
     }
virtual void Gametype::gametype_init () inline virtual inherited
Definition at line 73 of file mapinfo.qh.
References cons(), m_flags, and MAPINFO_TYPE_ALL.
     {
         this.netname = g_name;
         this.mdl = sname;
         this.message = hname;
         this.team = gteamplay;
         this.m_mutators = cons(sname, mutators);
         this.model2 = defaults;
         this.gametype_description = gdescription;
         // same as `1 << m_id`
         MAPINFO_TYPE_ALL |= this.items = this.m_flags = (MAPINFO_TYPE_ALL + 1);
     }
virtual void CaptureTheFlag::m_generate_mapinfo () inline virtual
Reimplemented from Gametype.
Definition at line 222 of file mapinfo.qh.
References m_flags, and MapInfo_Map_supportedGametypes.
     {
         if(v == "item_flag_team2" || v == "team_CTF_blueflag")
             MapInfo_Map_supportedGametypes |= this.m_flags;
     }
virtual void Gametype::m_isAlwaysSupported () inline virtual inherited
Reimplemented in Keepaway, FreezeTag, KeyHunt, ClanArena, TeamDeathmatch, LastManStanding, and Deathmatch.
Definition at line 56 of file mapinfo.qh.
     {
         return false;
     }
virtual void CaptureTheFlag::m_isTwoBaseMode () inline virtual
Reimplemented from Gametype.
Definition at line 227 of file mapinfo.qh.
     {
         return true;
     }
virtual void Gametype::m_parse_mapinfo () inline virtual inherited
Reimplemented in Invasion, FreezeTag, KeyHunt, Domination, ClanArena, TeamDeathmatch, and Race.
Definition at line 44 of file mapinfo.qh.
     {
         return false;
     }
virtual void CaptureTheFlag::m_setTeams () inline virtual
Definition at line 231 of file mapinfo.qh.
References cvar_set().
     {
         cvar_set("fraglimit", sa);
     }
Member Data Documentation
int Gametype::items = 0 inherited
game type ID
Definition at line 25 of file mapinfo.qh.
int Gametype::m_id = 0 inherited
Definition at line 23 of file mapinfo.qh.
Referenced by MapInfo_LoadMapSettings_SaveGameType().
bool Gametype::team = false inherited
does this gametype support teamplay?
Definition at line 33 of file mapinfo.qh.
Referenced by _MapInfo_GetTeamPlayBool().
The documentation for this class was generated from the following file:
common/mapinfo.qh