Xonotic: server/weapons/weaponsystem.qh File Reference
weaponsystem.qh File Reference
#include <server/defs.qh>
#include <server/miscfunctions.qh>
Functions
void CL_SpawnWeaponentity (entity e,.entity weaponentity)
vector CL_Weapon_GetShotOrg (float wpn)
void W_AttachToShotorg (entity actor,.entity weaponentity, entity flash, vector offset)
void W_DecreaseAmmo (Weapon wep, entity actor, float ammo_use,.entity weaponentity)
void W_DropEvent (.void(Weapon, entity actor,.entity) event, entity player, float weapon_type, entity weapon_item,.entity weaponentity)
void W_Reload (entity actor,.entity weaponentity, float sent_ammo_min, Sound sent_sound)
void W_WeaponFrame (Player actor,.entity weaponentity)
float W_WeaponRateFactor (entity this)
float W_WeaponSpeedFactor (entity this)
bool weapon_prepareattack (Weapon thiswep, entity actor,.entity weaponentity, bool secondary, float attacktime)
bool weapon_prepareattack_check (Weapon thiswep, entity actor,.entity weaponentity, float secondary, float attacktime)
void weapon_prepareattack_do (entity actor,.entity weaponentity, float secondary, float attacktime)
void weapon_thinkf (entity actor,.entity weaponentity, WFRAME fr, float t, void(Weapon thiswep, entity actor,.entity weaponentity, int fire) func)
bool weaponLocked (entity player)
bool weaponUseForbidden (entity player)
Variables
float internalteam
entity weapon_dropevent_item
entity weaponentity_fld
Function Documentation
void CL_SpawnWeaponentity (entity e, .entity weaponentity)
Definition at line 171 of file weaponsystem.qc.
References CL_ExteriorWeaponentity_Think(), CL_Weaponentity_CustomizeEntityForClient(), CL_Weaponentity_Think(), drag_undraggable(), entity(), setmodel, setorigin(), setthink, SOLID_NOT, time, and weaponentities.
Referenced by PutPlayerInServer().
 {
     entity view = actor.(weaponentity) = new(weaponentity);
     view.solid = SOLID_NOT;
     view.owner = actor;
     setmodel(view, MDL_Null);  // precision set when changed
     setorigin(view, '0 0 0');
     view.weaponentity_fld = weaponentity;
     setthink(view, CL_Weaponentity_Think);
     view.nextthink = time;
     view.viewmodelforclient = actor;
     view.draggable = drag_undraggable;
     setcefc(view, CL_Weaponentity_CustomizeEntityForClient);
     wepent_link(view);
     if (weaponentity == weaponentities[0]) // only one exterior model, thank you very much
     {
         entity exterior = actor.exteriorweaponentity = new(exteriorweaponentity);
         exterior.solid = SOLID_NOT;
         exterior.owner = actor;
         exterior.draggable = drag_undraggable;
         exterior.weaponentity_fld = weaponentity;
         setorigin(exterior, '0 0 0');
         setthink(exterior, CL_ExteriorWeaponentity_Think);
         exterior.nextthink = time;
         CSQCMODEL_AUTOINIT(exterior);
     }
 }
vector CL_Weapon_GetShotOrg (float wpn)
void W_AttachToShotorg (entity actor, .entity weaponentity, entity flash, vector offset)
Definition at line 657 of file weaponsystem.qc.
References copyentity(), entity(), gettagindex, random(), setorigin(), and spawn().
 {
     flash.owner = actor;
     flash.angles_z = random() * 360;
     entity view = actor.(weaponentity);
     entity exterior = actor.exteriorweaponentity;
     if (gettagindex(view, "shot")) setattachment(flash, view, "shot");
     else setattachment(flash, view, "tag_shot");
     setorigin(flash, offset);
     entity xflash = spawn();
     copyentity(flash, xflash);
     flash.viewmodelforclient = actor;
     if (view.oldorigin.x > 0)
     {
         setattachment(xflash, exterior, "");
         setorigin(xflash, view.oldorigin + offset);
     }
     else
     {
         if (gettagindex(exterior, "shot")) setattachment(xflash, exterior, "shot");
         else setattachment(xflash, exterior, "tag_shot");
         setorigin(xflash, offset);
     }
 }
void W_DecreaseAmmo (Weapon wep, entity actor, float ammo_use, .entity weaponentity)
Definition at line 687 of file weaponsystem.qc.
References ammo, Weapon::ammo_type, backtrace, entity(), GetAmmoPicture(), GetResource(), IT_UNLIMITED_WEAPON_AMMO, M_ARGV, MUTATOR_CALLHOOK, Weapon::netname, RES_NONE, SetResource(), and W_DecreaseAmmo().
Referenced by W_DecreaseAmmo().
 {
     if (MUTATOR_CALLHOOK(W_DecreaseAmmo, actor, actor.(weaponentity), ammo_use)) return;
     if ((actor.items & IT_UNLIMITED_WEAPON_AMMO) && !wep.reloading_ammo) return;
     ammo_use = M_ARGV(2, float);
     entity w_ent = actor.(weaponentity);
     // if this weapon is reloadable, decrease its load. Else decrease the player's ammo
     if (wep.reloading_ammo)
     {
         w_ent.clip_load -= ammo_use;
         w_ent.(weapon_load[w_ent.m_weapon.m_id]) = w_ent.clip_load;
     }
     else if (wep.ammo_type != RES_NONE)
     {
         float ammo = GetResource(actor, wep.ammo_type);
         if (ammo < ammo_use)
         {
             backtrace(sprintf(
                 "W_DecreaseAmmo(%.2f): '%s' subtracted too much %s from '%s', resulting with '%.2f' left... "
                 "Please notify the developers immediately with a copy of this backtrace!\n",
                 ammo_use,
                 wep.netname,
                 GetAmmoPicture(wep.ammo_type),
                 actor.netname,
                 ammo
                              ));
         }
         SetResource(actor, wep.ammo_type, ammo - ammo_use);
     }
 }
void W_DropEvent (.void(Weapon, entity actor,.entity) event, entity player, float weapon_type, entity weapon_item, .entity weaponentity)
Definition at line 837 of file weaponsystem.qc.
References weapon_dropevent_item, and Weapons_from.
Referenced by W_ThrowNewWeapon().
 {
     Weapon w = Weapons_from(weapon_type);
     weapon_dropevent_item = weapon_item;
     w.event(w, player, weaponentity);
 }
void W_Reload (entity actor, .entity weaponentity, float sent_ammo_min, Sound sent_sound)
Definition at line 760 of file weaponsystem.qc.
References _sound, ATTEN_NORM, CH_WEAPON_SINGLE, clip_load, entity(), GetResource(), IS_REAL_CLIENT, IT_UNLIMITED_WEAPON_AMMO, LOG_TRACE(), MUTATOR_CALLHOOK, old_clip_load, play2(), reload_ammo_amount, RES_NONE, SND, Sound_fixpath, sprint(), state, strcat(), strcpy, TC, time, VOL_BASE, W_Reload(), W_ReloadedAndReady(), W_SwitchToOtherWeapon(), weapon_load, weapon_thinkf(), WEP_FLAG_RELOADABLE, and WS_READY.
Referenced by W_Reload().
 {
     TC(Sound, sent_sound);
     // set global values to work with
     entity this = actor.(weaponentity);
     Weapon e = this.m_weapon;
     if (MUTATOR_CALLHOOK(W_Reload, actor)) return;
     this.reload_ammo_min = sent_ammo_min;
     this.reload_ammo_amount = e.reloading_ammo;
     this.reload_time = e.reloading_time;
     strcpy(actor.reload_sound, Sound_fixpath(sent_sound));
     // don't reload weapons that don't have the RELOADABLE flag
     if (!(e.spawnflags & WEP_FLAG_RELOADABLE))
     {
         LOG_TRACE(
             "Warning: Attempted to reload a weapon that does not have the WEP_FLAG_RELOADABLE flag. Fix your code!\n");
         return;
     }
     // return if reloading is disabled for this weapon
     if (!this.reload_ammo_amount) return;
     // our weapon is fully loaded, no need to reload
     if (this.clip_load >= this.reload_ammo_amount) return;
     // no ammo, so nothing to load
     if (e.ammo_type != RES_NONE)
     {
         if (!GetResource(actor, e.ammo_type) && this.reload_ammo_min)
         {
             if (!(actor.items & IT_UNLIMITED_WEAPON_AMMO))
             {
                 if (IS_REAL_CLIENT(actor) && actor.reload_complain < time)
                 {
                     play2(actor, SND(UNAVAILABLE));
                     sprint(actor, strcat("You don't have enough ammo to reload the ^2", this.m_weapon.m_name, "\n"));
                     actor.reload_complain = time + 1;
                 }
                 // switch away if the amount of ammo is not enough to keep using this weapon
                 if (!(e.wr_checkammo1(e, actor, weaponentity) + e.wr_checkammo2(e, actor, weaponentity)))
                 {
                     this.clip_load = -1;  // reload later
                     W_SwitchToOtherWeapon(actor, weaponentity);
                 }
                 return;
             }
         }
     }
     if (this)
     {
         if (this.wframe == WFRAME_RELOAD) return;
         // allow switching away while reloading, but this will cause a new reload!
         this.state = WS_READY;
     }
     // now begin the reloading process
     _sound(actor, CH_WEAPON_SINGLE, actor.reload_sound, VOL_BASE, ATTEN_NORM);
     // do not set ATTACK_FINISHED in reload code any more. This causes annoying delays if eg: You start reloading a weapon,
     // then quickly switch to another weapon and back. Reloading is canceled, but the reload delay is still there,
     // so your weapon is disabled for a few seconds without reason
     // ATTACK_FINISHED(actor, weaponentity) = max(time, ATTACK_FINISHED(actor, weaponentity)) + this.reload_time + 1;
     weapon_thinkf(actor, weaponentity, WFRAME_RELOAD, this.reload_time, W_ReloadedAndReady);
     if (this.clip_load < 0) this.clip_load = 0;
     this.old_clip_load = this.clip_load;
     this.clip_load = this.(weapon_load[this.m_weapon.m_id]) = -1;
 }
void W_WeaponFrame (Player actor, .entity weaponentity)
Definition at line 457 of file weaponsystem.qc.
References ATTACK_FINISHED, ATTN_NORM, autocvar_g_weaponswitch_debug, bprint(), bulletcounter, CH_WEAPON_SINGLE, clip_load, clip_size, entity(), frametime, GetResource(), INDEPENDENT_ATTACK_FINISHED, IS_PLAYER, LOG_WARNF, Weapon::mdl, Client::netname, OFFHAND_HOOK, PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_HOOK, PS, RES_HEALTH, sound, Weapon::spawnflags, state, TC, time, Client::v_angle, v_forward, v_right, v_up, vector(), VOL_BASE, w_clear(), w_getbestweapon, w_ready(), W_SwitchWeapon(), W_SwitchWeapon_Force(), W_TICSPERFRAME, weapon_frametime, weapon_load, weapon_nextthink, weapon_thinkf(), weaponentities, weaponLocked(), weaponslot(), weaponUseForbidden(), WEP_FLAG_DUALWIELD, WEP_FLAG_RELOADABLE, WEPSET, WepSet_FromWeapon, Weapon::wr_gonethink(), Weapon::wr_setup(), Weapon::wr_think(), WS_CLEAR, WS_DROP, WS_INUSE, WS_RAISE, and WS_READY.
Referenced by PlayerThink(), and PutPlayerInServer().
 {
     TC(Player, actor);
     TC(PlayerState, PS(actor));
     entity this = actor.(weaponentity);
     if (frametime) this.weapon_frametime = frametime;
     if (!this || GetResource(actor, RES_HEALTH) < 1) return;  // Dead player can't use weapons and injure impulse commands
     int button_atck = PHYS_INPUT_BUTTON_ATCK(actor);
     int button_atck2 = PHYS_INPUT_BUTTON_ATCK2(actor);
     if (weaponUseForbidden(actor))
         button_atck = button_atck2 = 0; // forbid primary and secondary fire, switching is allowed
     if (weaponLocked(actor))
     {
         if (this.state != WS_CLEAR)
         {
             Weapon wpn = this.m_weapon;
             w_ready(wpn, actor, weaponentity, button_atck | (button_atck2 << 1));
             return;
         }
     }
     if(autocvar_g_weaponswitch_debug == 2 && weaponslot(weaponentity) > 0)
     {
         .entity wepe1 = weaponentities[0];
         entity wep1 = actor.(wepe1);
         this.m_switchweapon = wep1.m_switchweapon;
         entity store = IS_PLAYER(actor) ? PS(actor) : actor;
         if(!(this.m_switchweapon.spawnflags & WEP_FLAG_DUALWIELD) && !(store.dual_weapons & wep1.m_switchweapon.m_wepset))
         {
             this.m_weapon = WEP_Null;
             this.m_switchingweapon = WEP_Null;
             this.m_switchweapon = WEP_Null;
             this.state = WS_CLEAR;
             this.weaponname = "";
             return;
         }
     }
     if (this.m_switchweapon == WEP_Null)
     {
         if (this.state != WS_CLEAR)
             w_ready(this.m_weapon, actor, weaponentity, button_atck | (button_atck2 << 1));
         this.m_weapon = WEP_Null;
         this.m_switchingweapon = WEP_Null;
         this.state = WS_CLEAR;
         this.weaponname = "";
         return;
     }
     makevectors(actor.v_angle);
     vector fo = v_forward;  // save them in case the weapon think functions change it
     vector ri = v_right;
     vector up = v_up;
     // Change weapon
     if (this.m_weapon != this.m_switchweapon)
     {
         switch (this.state)
         {
             default:
                 LOG_WARNF("unhandled weaponentity (%i) state for player (%i): %d", this, actor, this.state);
                 break;
             case WS_INUSE:
             case WS_RAISE:
                 break;
             case WS_CLEAR:
             {
                 // end switching!
                 Weapon newwep = this.m_switchweapon;
                 this.m_switchingweapon = newwep;
                 // the two weapon entities will notice this has changed and update their models
                 this.m_weapon = newwep;
                 this.weaponname = newwep.mdl;
                 this.bulletcounter = 0;
                 newwep.wr_setup(newwep, actor, weaponentity);
                 this.state = WS_RAISE;
                 // set our clip load to the load of the weapon we switched to, if it's reloadable
                 if ((newwep.spawnflags & WEP_FLAG_RELOADABLE) && newwep.reloading_ammo)  // prevent accessing undefined cvars
                 {
                     this.clip_load = this.(weapon_load[this.m_switchweapon.m_id]);
                     this.clip_size = newwep.reloading_ammo;
                 }
                 else
                 {
                     this.clip_load = this.clip_size = 0;
                 }
                 weapon_thinkf(actor, weaponentity, WFRAME_DONTCHANGE, newwep.switchdelay_raise, w_ready);
                 break;
             }
             case WS_DROP:
             {
                 // in dropping phase we can switch at any time
                 this.m_switchingweapon = this.m_switchweapon;
                 break;
             }
             case WS_READY:
             {
                 // start switching!
                 this.m_switchingweapon = this.m_switchweapon;
                 entity oldwep = this.m_weapon;
                 // set up weapon switch think in the future, and start drop anim
                 if (INDEPENDENT_ATTACK_FINISHED || ATTACK_FINISHED(actor, weaponentity) <= time + this.weapon_frametime * 0.5)
                 {
                     sound(actor, CH_WEAPON_SINGLE, SND_WEAPON_SWITCH, VOL_BASE, ATTN_NORM);
                     this.state = WS_DROP;
                     weapon_thinkf(actor, weaponentity, WFRAME_DONTCHANGE, oldwep.switchdelay_drop, w_clear);
                 }
                 break;
             }
         }
     }
     // LordHavoc: network timing test code
     // if (actor.button0)
     //  print(ftos(frametime), " ", ftos(time), " >= ", ftos(ATTACK_FINISHED(actor, weaponentity)), " >= ", ftos(this.weapon_nextthink), "\n");
     Weapon w = this.m_weapon;
     // call the think code which may fire the weapon
     // and do so multiple times to resolve framerate dependency issues if the
     // server framerate is very low and the weapon fire rate very high
     for (int c = 0; c < W_TICSPERFRAME; ++c)
     {
         if (w != WEP_Null && !(STAT(WEAPONS, actor) & WepSet_FromWeapon(w)))
         {
             if (this.m_weapon == this.m_switchweapon) W_SwitchWeapon_Force(actor, w_getbestweapon(actor, weaponentity), weaponentity);
             w = WEP_Null;
         }
         v_forward = fo;
         v_right = ri;
         v_up = up;
         bool block_weapon = false;
         {
             bool key_pressed = PHYS_INPUT_BUTTON_HOOK(actor) && !actor.vehicle;
             if (weaponUseForbidden(actor))
                 key_pressed = false;
             Weapon off = actor.offhand;
             if (off && (!(STAT(WEAPONS, actor) & WEPSET(HOOK)) || off != OFFHAND_HOOK))
             {
                 if (off.offhand_think) off.offhand_think(off, actor, key_pressed);
             }
             else
             {
                 if (key_pressed && this.m_switchweapon != WEP_HOOK && !actor.hook_switchweapon)
                     W_SwitchWeapon(actor, WEP_HOOK, weaponentity);
                 actor.hook_switchweapon = key_pressed;
                 Weapon h = WEP_HOOK;
                 block_weapon = (this.m_weapon == h && (button_atck || key_pressed));
                 h.wr_think(h, actor, weaponentity, block_weapon ? 1 : 0);
             }
         }
         v_forward = fo;
         v_right = ri;
         v_up = up;
         if (!block_weapon)
         {
             Weapon e = this.m_weapon;
             TC(Weapon, e);
             if (w != WEP_Null)
             {
                 e.wr_think(e, actor, weaponentity, button_atck | (button_atck2 << 1));
             }
             else if (e)
             {
                 e.wr_gonethink(e, actor, weaponentity);
             }
         }
         if (time + this.weapon_frametime * 0.5 >= this.weapon_nextthink)
         {
             if (this.weapon_think)
             {
                 v_forward = fo;
                 v_right = ri;
                 v_up = up;
                 Weapon wpn = this.m_weapon;
                 this.weapon_think(wpn, actor, weaponentity,
                     button_atck | (button_atck2 << 1));
             }
             else
             {
                 bprint("\{1}^1ERROR: undefined weapon think function for ", actor.netname, "\n");
             }
         }
     }
 }
float W_WeaponRateFactor (entity this)
Definition at line 26 of file weaponsystem.qc.
References g_weaponratefactor, M_ARGV, and MUTATOR_CALLHOOK.
Referenced by weapon_prepareattack_do(), and weapon_thinkf().
 {
     float t = 1;
     if(g_weaponratefactor > 0)
         t = 1.0 / g_weaponratefactor;
     MUTATOR_CALLHOOK(WeaponRateFactor, t, this);
     t = M_ARGV(0, float);
     return t;
 }
float W_WeaponSpeedFactor (entity this)
Definition at line 38 of file weaponsystem.qc.
References g_weaponspeedfactor, M_ARGV, and MUTATOR_CALLHOOK.
Referenced by bot_aim(), and W_CalculateProjectileVelocity().
 {
     float t = 1.0 * g_weaponspeedfactor;
     MUTATOR_CALLHOOK(WeaponSpeedFactor, t, this);
     t = M_ARGV(0, float);
     return t;
 }
bool weapon_prepareattack (Weapon thiswep, entity actor, .entity weaponentity, bool secondary, float attacktime)
Definition at line 346 of file weaponsystem.qc.
References weapon_prepareattack_check(), and weapon_prepareattack_do().
 {
     if (weapon_prepareattack_check(thiswep, actor, weaponentity, secondary, attacktime))
     {
         weapon_prepareattack_do(actor, weaponentity, secondary, attacktime);
         return true;
     }
     return false;
 }
bool weapon_prepareattack_check (Weapon thiswep, entity actor, .entity weaponentity, float secondary, float attacktime)
void weapon_prepareattack_do (entity actor, .entity weaponentity, float secondary, float attacktime)
void weapon_thinkf (entity actor, .entity weaponentity, WFRAME fr, float t, void(Weapon thiswep, entity actor,.entity weaponentity, int fire) func)
Parameters
t defer thinking until time + t
func next think function
Definition at line 360 of file weaponsystem.qc.
References ANIMACTION_MELEE, ANIMACTION_SHOOT, animdecide_setaction(), backtrace, boolean, entity(), FOREACH_CLIENT, g_weaponratefactor, IS_SPEC, NULL, state, time, v_forward, v_right, v_up, vector(), w_ready(), W_WeaponRateFactor(), weapon_frametime, weapon_nextthink, WEP_TYPE_MELEE_PRI, WEP_TYPE_MELEE_SEC, and WS_RAISE.
Referenced by w_ready(), W_Reload(), and W_WeaponFrame().
 {
     entity this = actor.(weaponentity);
     if (this == NULL) return;
     bool restartanim;
     if (fr == WFRAME_DONTCHANGE)
     {
         fr = this.wframe;
         restartanim = false;
     }
     else
     {
         restartanim = fr != WFRAME_IDLE;
     }
     vector of = v_forward;
     vector or = v_right;
     vector ou = v_up;
     vector a = '0 0 0';
     this.wframe = fr;
     if (fr == WFRAME_IDLE) a = this.anim_idle;
     else if (fr == WFRAME_FIRE1) a = this.anim_fire1;
     else if (fr == WFRAME_FIRE2) a = this.anim_fire2;
     else  // if (fr == WFRAME_RELOAD)
         a = this.anim_reload;
     a.z *= g_weaponratefactor;
     v_forward = of;
     v_right = or;
     v_up = ou;
     if (this.weapon_think == w_ready && func != w_ready && this.state == WS_RAISE) backtrace(
             "Tried to override initial weapon think function - should this really happen?");
     t *= W_WeaponRateFactor(actor);
     // VorteX: haste can be added here
     if (this.weapon_think == w_ready)
     {
         this.weapon_nextthink = time;
         // dprint("started firing at ", ftos(time), "\n");
     }
     if (this.weapon_nextthink < time - this.weapon_frametime * 1.5
         || this.weapon_nextthink > time + this.weapon_frametime * 1.5)
     {
         this.weapon_nextthink = time;
         // dprint("reset weapon animation timer at ", ftos(time), "\n");
     }
     this.weapon_nextthink += t;
     this.weapon_think = func;
     // dprint("next ", ftos(this.weapon_nextthink), "\n");
     if (this)
     {
         FOREACH_CLIENT(true, {
             if(it == actor || (IS_SPEC(it) && it.enemy == actor))
                 wframe_send(it, this, a, restartanim);
         });
     }
     if ((fr == WFRAME_FIRE1 || fr == WFRAME_FIRE2) && t)
     {
         bool primary_melee = boolean(fr == WFRAME_FIRE1 && (this.m_weapon.spawnflags & WEP_TYPE_MELEE_PRI));
         bool secondary_melee = boolean(fr == WFRAME_FIRE2 && (this.m_weapon.spawnflags & WEP_TYPE_MELEE_SEC));
         int act = (primary_melee || secondary_melee)
             ? ANIMACTION_MELEE
             : ANIMACTION_SHOOT
             ;
         animdecide_setaction(actor, act, restartanim);
     }
     else if (actor.anim_upper_action == ANIMACTION_SHOOT || actor.anim_upper_action == ANIMACTION_MELEE)
     {
         actor.anim_upper_action = 0;
     }
 }
bool weaponLocked (entity player)
Definition at line 445 of file weaponsystem.qc.
References MUTATOR_CALLHOOK, sv_ready_restart_after_countdown, and time.
Referenced by FireGrapplingHook(), IMPULSE(), MUTATOR_HOOKFUNCTION(), vehicles_touch(), W_SwitchWeapon(), and W_WeaponFrame().
 {
     if (time < game_starttime && !sv_ready_restart_after_countdown) return true;
     if (player.player_blocked) return true;
     if (game_stopped) return true;
     if (STAT(FROZEN, player)) return true;
     if (MUTATOR_CALLHOOK(LockWeapon, player)) return true;
     return false;
 }
bool weaponUseForbidden (entity player)
Definition at line 438 of file weaponsystem.qc.
References MUTATOR_CALLHOOK, round_handler_IsActive, and round_handler_IsRoundStarted.
Referenced by W_WeaponFrame().
 {
     if (round_handler_IsActive() && !round_handler_IsRoundStarted()) return true;
     if (MUTATOR_CALLHOOK(ForbidWeaponUse, player)) return true;
     return false;
 }
Variable Documentation
float internalteam
Definition at line 6 of file weaponsystem.qh.
Referenced by weapon_defaultspawnfunc().
entity weapon_dropevent_item
Definition at line 7 of file weaponsystem.qh.
Referenced by W_DropEvent().
entity weaponentity_fld
Definition at line 9 of file weaponsystem.qh.
Referenced by CL_ExteriorWeaponentity_Think(), CL_Weaponentity_Think(), GrapplingHookSend(), GrapplingHookThink(), and RemoveHook().