Xonotic: menu/xonotic/playermodel.qh File Reference
playermodel.qh File Reference
#include "image.qh"
Functions
METHOD (XonoticPlayerModelSelector, configureXonoticPlayerModelSelector, void(entity))
METHOD (XonoticPlayerModelSelector, loadModels, void(entity))
METHOD (XonoticPlayerModelSelector, loadCvars, void(entity))
METHOD (XonoticPlayerModelSelector, saveCvars, void(entity))
METHOD (XonoticPlayerModelSelector, draw, void(entity))
METHOD (XonoticPlayerModelSelector, resizeNotify, void(entity, vector, vector, vector, vector))
METHOD (XonoticPlayerModelSelector, showNotify, void(entity))
METHOD (XonoticPlayerModelSelector, go, void(entity, float))
METHOD (XonoticPlayerModelSelector, destroy, void(entity))
entity makeXonoticPlayerModelSelector ()
void PlayerModelSelector_Next_Click (entity btn, entity me)
void PlayerModelSelector_Prev_Click (entity btn, entity me)
Function Documentation
entity makeXonoticPlayerModelSelector ()
Definition at line 3 of file playermodel.qc.
References entity(), me, and NEW.
Referenced by XonoticProfileTab_fill().
 {
     entity me;
     me = NEW(XonoticPlayerModelSelector);
     me.configureXonoticPlayerModelSelector(me);
     return me;
 }
METHOD (XonoticPlayerModelSelector , configureXonoticPlayerModelSelector , void(entity))
METHOD (XonoticPlayerModelSelector , loadModels , void(entity))
METHOD (XonoticPlayerModelSelector , loadCvars , void(entity))
METHOD (XonoticPlayerModelSelector , saveCvars , void(entity))
METHOD (XonoticPlayerModelSelector , draw , void(entity))
METHOD (XonoticPlayerModelSelector , resizeNotify , void(entity, vector, vector, vector, vector))
METHOD (XonoticPlayerModelSelector , showNotify , void(entity))
METHOD (XonoticPlayerModelSelector , go , void(entity, float))
METHOD (XonoticPlayerModelSelector , destroy , void(entity))
void PlayerModelSelector_Next_Click (entity btn, entity me)
Definition at line 136 of file playermodel.qc.
Referenced by XonoticProfileTab_fill().
 {
     if (me.numModels <= 0)
         return;
     me.go(me, +1);
     me.saveCvars(me);
 }
void PlayerModelSelector_Prev_Click (entity btn, entity me)
Definition at line 144 of file playermodel.qc.
Referenced by XonoticProfileTab_fill().
 {
     if (me.numModels <= 0)
         return;
     me.go(me, -1);
     me.saveCvars(me);
 }