Xonotic: server/constants.qh File Reference
server/constants.qh File Reference
Defines
#define SERVER_CONSTANTS_H
#define EFMASK_CHEAP (EF_ADDITIVE | EF_DOUBLESIDED | EF_FULLBRIGHT | EF_NODEPTHTEST | EF_NODRAW | EF_NOGUNBOB | EF_NOSHADOW | EF_LOWPRECISION | EF_SELECTABLE | EF_TELEPORT_BIT)
Variables
const int FL_WEAPON = BIT(13)
const int FL_POWERUP = BIT(14)
const int FL_PROJECTILE = BIT(15)
const int FL_TOSSED = BIT(16)
const int FL_NO_WEAPON_STAY = BIT(17)
const int FL_SPAWNING = BIT(18)
const int FL_PICKUPITEMS = BIT(19)
const int SVC_SETVIEW = 5
const int RESPAWN_FORCE = 1
const int RESPAWN_SILENT = 2
const int NUM_PLAYERSKINS_TEAMPLAY = 3
const int ASSAULT_VALUE_INACTIVE = 1000
Define Documentation
#define EFMASK_CHEAP (EF_ADDITIVE | EF_DOUBLESIDED | EF_FULLBRIGHT | EF_NODEPTHTEST | EF_NODRAW | EF_NOGUNBOB | EF_NOSHADOW | EF_LOWPRECISION | EF_SELECTABLE | EF_TELEPORT_BIT)
Definition at line 17 of file constants.qh.
#define SERVER_CONSTANTS_H
Definition at line 2 of file constants.qh.
Variable Documentation
const int ASSAULT_VALUE_INACTIVE = 1000
Definition at line 21 of file constants.qh.
const int FL_NO_WEAPON_STAY = BIT(17)
Definition at line 8 of file constants.qh.
const int FL_PICKUPITEMS = BIT(19)
Definition at line 10 of file constants.qh.
Referenced by PutClientInServer().
const int FL_POWERUP = BIT(14)
Definition at line 5 of file constants.qh.
Referenced by REGISTER_ITEM().
const int FL_PROJECTILE = BIT(15)
Definition at line 6 of file constants.qh.
const int FL_SPAWNING = BIT(18)
Definition at line 9 of file constants.qh.
Referenced by ObserverThink(), and SpectatorThink().
const int FL_TOSSED = BIT(16)
Definition at line 7 of file constants.qh.
Referenced by W_ThrowNewWeapon().
const int FL_WEAPON = BIT(13)
Definition at line 4 of file constants.qh.
Referenced by navigation_routerating().
const int NUM_PLAYERSKINS_TEAMPLAY = 3
Definition at line 19 of file constants.qh.
const int RESPAWN_FORCE = 1
Definition at line 14 of file constants.qh.
Referenced by calculate_player_respawn_time(), and PlayerPreThink().
const int RESPAWN_SILENT = 2
Definition at line 15 of file constants.qh.
Referenced by PlayerPreThink().
const int SVC_SETVIEW = 5
Definition at line 12 of file constants.qh.
Referenced by PutClientInServer(), PutObserverInServer(), and SpectateSet().