Xonotic: client/hud/panel/weapons.qh File Reference
weapons.qh File Reference
#include "../panel.qh"
Functions
vector Accuracy_GetColor (float accuracy)
void Accuracy_LoadColors ()
void Accuracy_LoadLevels ()
Variables
vector acc_col [MAX_ACCURACY_LEVELS]
float acc_col_loadtime
string acc_color_levels
float acc_lev [MAX_ACCURACY_LEVELS]
int acc_levels
const int MAX_ACCURACY_LEVELS = 10
Function Documentation
vector Accuracy_GetColor (float accuracy)
Definition at line 68 of file weapons.qc.
References acc_col, acc_lev, acc_levels, color, and vector().
Referenced by HUD_Weapons(), and Scoreboard_AccuracyStats_Draw().
 {
     float factor;
     vector color;
     if(acc_levels < 2)
         return '0 0 0'; // return black, can't determine the right color
     // find the max level lower than acc
     int j = acc_levels-1;
     while(j && accuracy < acc_lev[j])
         --j;
     // inject color j+1 in color j, how much depending on how much accuracy is higher than level j
     factor = (accuracy - acc_lev[j]) / (acc_lev[j+1] - acc_lev[j]);
     color = acc_col[j];
     color = color + factor * (acc_col[j+1] - color);
     return color;
 }
void Accuracy_LoadColors ()
Definition at line 56 of file weapons.qc.
References acc_col, acc_col_loadtime, acc_levels, cvar_string(), ftos(), stov(), strcat(), and time.
Referenced by HUD_Weapons(), and Scoreboard_AccuracyStats_Draw().
 {
     if(time > acc_col_loadtime)
     if(acc_levels >= 2)
     {
         int i;
         for(i = 0; i < acc_levels; ++i)
             acc_col[i] = stov(cvar_string(strcat("accuracy_color", ftos(i))));
         acc_col_loadtime = time + 2;
     }
 }
void Accuracy_LoadLevels ()
Definition at line 39 of file weapons.qc.
References acc_color_levels, acc_lev, acc_levels, argv(), autocvar_accuracy_color_levels, LOG_INFO, MAX_ACCURACY_LEVELS, stof(), strcpy, and tokenize_console.
Referenced by HUD_Draw().
 {
     if(autocvar_accuracy_color_levels != acc_color_levels)
     {
         strcpy(acc_color_levels, autocvar_accuracy_color_levels);
         acc_levels = tokenize_console(acc_color_levels);
         if(acc_levels > MAX_ACCURACY_LEVELS)
             acc_levels = MAX_ACCURACY_LEVELS;
         if(acc_levels < 2)
             LOG_INFO("Warning: accuracy_color_levels must contain at least 2 values");
         int i;
         for(i = 0; i < acc_levels; ++i)
             acc_lev[i] = stof(argv(i)) / 100.0;
     }
 }
Variable Documentation
vector acc_col[MAX_ACCURACY_LEVELS]
Definition at line 6 of file weapons.qh.
Referenced by Accuracy_GetColor(), and Accuracy_LoadColors().
float acc_col_loadtime
Definition at line 7 of file weapons.qh.
Referenced by Accuracy_LoadColors().
string acc_color_levels
Definition at line 9 of file weapons.qh.
Referenced by Accuracy_LoadLevels().
float acc_lev[MAX_ACCURACY_LEVELS]
Definition at line 5 of file weapons.qh.
Referenced by Accuracy_GetColor(), and Accuracy_LoadLevels().
int acc_levels
Definition at line 8 of file weapons.qh.
Referenced by Accuracy_GetColor(), Accuracy_LoadColors(), and Accuracy_LoadLevels().
const int MAX_ACCURACY_LEVELS = 10
Definition at line 4 of file weapons.qh.
Referenced by Accuracy_LoadLevels().