Xonotic: lib/random.qc File Reference
random.qc File Reference
#include "random.qh"
Functions
float DistributeEvenly_Get (float weight)
float DistributeEvenly_GetRandomized (float weight)
void DistributeEvenly_Init (float amount, float totalweight)
float gsl_ran_gaussian (float sigma)
float prandom ()
vector prandomvec ()
void psrandom (float seed)
void RandomSelection_Add (entity e, float f, string s, vector v, float weight, float priority)
void RandomSelection_Init ()
Variables
float DistributeEvenly_amount
float DistributeEvenly_totalweight
float gsl_ran_gaussian_lastvalue
float gsl_ran_gaussian_lastvalue_set
float prandom_seed
Function Documentation
float DistributeEvenly_Get (float weight)
Definition at line 50 of file random.qc.
References DistributeEvenly_amount, DistributeEvenly_totalweight, and floor().
Referenced by Invasion_RoundStart(), kh_LoserTeam(), and kh_WinnerTeam().
 {
     float f;
     if (weight <= 0) return 0;
     f = floor(0.5 + DistributeEvenly_amount * weight / DistributeEvenly_totalweight);
     DistributeEvenly_totalweight -= weight;
     DistributeEvenly_amount -= f;
     return f;
 }
float DistributeEvenly_GetRandomized (float weight)
Definition at line 60 of file random.qc.
References DistributeEvenly_amount, DistributeEvenly_totalweight, floor(), and random().
 {
     float f;
     if (weight <= 0) return 0;
     f = floor(random() + DistributeEvenly_amount * weight / DistributeEvenly_totalweight);
     DistributeEvenly_totalweight -= weight;
     DistributeEvenly_amount -= f;
     return f;
 }
void DistributeEvenly_Init (float amount, float totalweight)
Definition at line 39 of file random.qc.
References DistributeEvenly_amount, DistributeEvenly_totalweight, ftos(), and LOG_TRACE().
Referenced by Invasion_RoundStart(), kh_LoserTeam(), and kh_WinnerTeam().
 {
     if (DistributeEvenly_amount)
     {
         LOG_TRACE("DistributeEvenly_Init: UNFINISHED DISTRIBUTION (", ftos(DistributeEvenly_amount), " for ", ftos(DistributeEvenly_totalweight), " left!)");
     }
     if (totalweight == 0) DistributeEvenly_amount = 0;
     else DistributeEvenly_amount = amount;
     DistributeEvenly_totalweight = totalweight;
 }
float gsl_ran_gaussian (float sigma)
Definition at line 73 of file random.qc.
References cos(), gsl_ran_gaussian_lastvalue, gsl_ran_gaussian_lastvalue_set, log(), M_PI, random(), sin(), and sqrt().
Referenced by W_CalculateSpread().
 {
     if (gsl_ran_gaussian_lastvalue_set)
     {
         gsl_ran_gaussian_lastvalue_set = 0;
         return sigma * gsl_ran_gaussian_lastvalue;
     }
     else
     {
         float a = random() * 2 * M_PI;
         float b = sqrt(-2 * log(random()));
         gsl_ran_gaussian_lastvalue = cos(a) * b;
         gsl_ran_gaussian_lastvalue_set = 1;
         return sigma * sin(a) * b;
     }
 }
float prandom ()
Definition at line 94 of file random.qc.
References ftos(), LOG_TRACE(), M_PI, prandom_seed, and strcat().
Referenced by prandomvec(), SND_GIB_SPLAT_RANDOM(), and turret_gibtoss().
     {
         float c;
         c = crc16(false, strcat(ftos(prandom_seed), ftos(prandom_seed + M_PI)));
         prandom_seed = c;
     #ifdef USE_PRANDOM_DEBUG
             LOG_TRACE("RANDOM -> ", ftos(c));
     #endif
         return c / 65536;  // in [0..1[
     }
vector prandomvec ()
Definition at line 107 of file random.qc.
References prandom(), v, and vector().
Referenced by turret_gibtoss().
     {
         vector v;
         do
         {
             v.x = prandom();
             v.y = prandom();
             v.z = prandom();
         }
         while (v * v > 1);
         return v;
     }
void psrandom (float seed)
Definition at line 122 of file random.qc.
References ftos(), LOG_TRACE(), and prandom_seed.
Referenced by NET_HANDLE().
     {
         prandom_seed = seed;
     #ifdef USE_PRANDOM_DEBUG
             LOG_TRACE("SRANDOM ", ftos(seed));
     #endif
     }
void RandomSelection_Add (entity e, float f, string s, vector v, float weight, float priority)
Definition at line 12 of file random.qc.
References random(), RandomSelection_best_priority, RandomSelection_chosen_ent, RandomSelection_chosen_float, RandomSelection_chosen_string, RandomSelection_chosen_vec, RandomSelection_totalweight, and v.
 {
     if (priority > RandomSelection_best_priority)
     {
         RandomSelection_best_priority = priority;
         RandomSelection_chosen_ent = e;
         RandomSelection_chosen_float = f;
         RandomSelection_chosen_string = s;
         RandomSelection_chosen_vec = v;
         RandomSelection_totalweight = weight;
     }
     else if (priority == RandomSelection_best_priority)
     {
         RandomSelection_totalweight += weight;
         if (random() * RandomSelection_totalweight <= weight)
         {
             RandomSelection_chosen_ent = e;
             RandomSelection_chosen_float = f;
             RandomSelection_chosen_string = s;
             RandomSelection_chosen_vec = v;
         }
     }
 }
void RandomSelection_Init ()
Definition at line 3 of file random.qc.
References NULL, RandomSelection_best_priority, RandomSelection_chosen_ent, RandomSelection_chosen_float, RandomSelection_chosen_string, RandomSelection_totalweight, and string_null.
Referenced by bot_setnameandstuff(), buff_NewType(), CheatCommand(), CheatImpulse(), FindSmallestTeam(), FixIntermissionClient(), invasion_PickMonster(), invasion_PickSpawn(), invasion_SpawnChosenMonster(), jumppad_push(), MapVote_CheckRules_2(), MUTATOR_HOOKFUNCTION(), NIX_ChooseNextWeapon(), Simple_TeleportPlayer(), Spawn_WeightedPoint(), spawnmonster(), SUB_UseTargets_Ex(), TeleportPlayer(), train_next_find(), and W_RandomWeapons().
 {
     RandomSelection_totalweight = 0;
     RandomSelection_chosen_ent = NULL;
     RandomSelection_chosen_float = 0;
     RandomSelection_chosen_string = string_null;
     RandomSelection_best_priority = -1;
 }
Variable Documentation
float DistributeEvenly_amount
Definition at line 36 of file random.qc.
Referenced by DistributeEvenly_Get(), DistributeEvenly_GetRandomized(), and DistributeEvenly_Init().
float DistributeEvenly_totalweight
Definition at line 37 of file random.qc.
Referenced by DistributeEvenly_Get(), DistributeEvenly_GetRandomized(), and DistributeEvenly_Init().
float gsl_ran_gaussian_lastvalue
Definition at line 71 of file random.qc.
Referenced by gsl_ran_gaussian().
float gsl_ran_gaussian_lastvalue_set
Definition at line 72 of file random.qc.
Referenced by gsl_ran_gaussian().
float prandom_seed
Definition at line 93 of file random.qc.
Referenced by prandom(), and psrandom().