Xonotic: common/physics/player.qc File Reference
common/physics/player.qc File Reference
#include "player.qh"
#include "../triggers/include.qh"
#include "../viewloc.qh"
Defines
#define unstick_offsets(X)
#define X(unstick_offset)
Functions
float IsMoveInDirection (vector mv, float ang)
float GeomLerp (float a, float lerp, float b)
void PM_ClientMovement_Unstick (entity this)
void PM_ClientMovement_UpdateStatus (entity this, bool ground)
void PM_ClientMovement_Move (entity this)
void CPM_PM_Aircontrol (entity this, vector wishdir, float wishspeed)
float AdjustAirAccelQW (float accelqw, float factor)
void PM_Accelerate (entity this, vector wishdir, float wishspeed, float wishspeed0, float accel, float accelqw, float stretchfactor, float sidefric, float speedlimit)
void PM_AirAccelerate (entity this, vector wishdir, float wishspeed)
bool PlayerJump (entity this)
void CheckWaterJump (entity this)
void CheckPlayerJump (entity this)
float racecar_angle (float forward, float down)
void SpecialCommand ()
float PM_check_specialcommand (entity this, float buttons)
void PM_check_nickspam (entity this)
void PM_check_punch (entity this)
void PM_check_frozen (entity this)
void PM_check_hitground (entity this)
void PM_Footsteps (entity this)
void PM_check_blocked (entity this)
void PM_fly (entity this, float maxspd_mod)
void PM_swim (entity this, float maxspd_mod)
void PM_ladder (entity this, float maxspd_mod)
void PM_jetpack (entity this, float maxspd_mod)
void PM_walk (entity this, float maxspd_mod)
void PM_air (entity this, float buttons_prev, float maxspd_mod)
bool IsFlying (entity this)
void PM_Main (entity this)
Variables
float jetpack_stopped
string specialcommand = "xwxwxsxsxaxdxaxdx1x "
float specialcommand_pos
vector oldmovement
Define Documentation
#define unstick_offsets (X)
Value:
/* 1 no nudge (just return the original if this test passes) */ \
    X(' 0.000  0.000  0.000') \
/* 6 simple nudges */ \
    X(' 0.000  0.000  0.125') X('0.000  0.000 -0.125') \
    X('-0.125  0.000  0.000') X('0.125  0.000  0.000') \
    X(' 0.000 -0.125  0.000') X('0.000  0.125  0.000') \
/* 4 diagonal flat nudges */ \
    X('-0.125 -0.125  0.000') X('0.125 -0.125  0.000') \
    X('-0.125  0.125  0.000') X('0.125  0.125  0.000') \
/* 8 diagonal upward nudges */ \
    X('-0.125  0.000  0.125') X('0.125  0.000  0.125') \
    X(' 0.000 -0.125  0.125') X('0.000  0.125  0.125') \
    X('-0.125 -0.125  0.125') X('0.125 -0.125  0.125') \
    X('-0.125  0.125  0.125') X('0.125  0.125  0.125') \
/* 8 diagonal downward nudges */ \
    X('-0.125  0.000 -0.125') X('0.125  0.000 -0.125') \
    X(' 0.000 -0.125 -0.125') X('0.000  0.125 -0.125') \
    X('-0.125 -0.125 -0.125') X('0.125 -0.125 -0.125') \
    X('-0.125  0.125 -0.125') X('0.125  0.125 -0.125') \
Definition at line 83 of file player.qc.
Referenced by PM_ClientMovement_Unstick().
#define X (unstick_offset)
Value:
{ \
        vector neworigin = unstick_offset + this.origin; \
        tracebox(neworigin, STAT(PL_CROUCH_MIN, NULL), STAT(PL_CROUCH_MAX, NULL), neworigin, MOVE_NORMAL, this); \
        if (!trace_startsolid) \
        { \
            setorigin(this, neworigin); \
            return; \
        } \
    }
Function Documentation
float AdjustAirAccelQW (float accelqw, float factor)
Definition at line 315 of file player.qc.
References bound(), copysign(), and fabs().
Referenced by PM_Accelerate().
{
    return copysign(bound(0.000001, 1 - (1 - fabs(accelqw)) * factor, 1), accelqw);
}
void CheckPlayerJump (entity this)
Definition at line 577 of file player.qc.
References CheckWaterJump(), INFO_JETPACK_NOFUEL, IT_UNLIMITED_WEAPON_AMMO, IT_USING_JETPACK, ITEMS_STAT, jetpack_stopped, MSG_INFO, PHYS_AMMO_FUEL, PHYS_FROZEN, PHYS_INPUT_BUTTON_JETPACK, PHYS_INPUT_BUTTON_JUMP, PHYS_JETPACK_FUEL, player_multijump, PlayerJump(), UNSET_JUMP_HELD, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by PM_Main().
{
#ifdef SVQC
    float was_flying = ITEMS_STAT(this) & IT_USING_JETPACK;
#endif
    if (JETPACK_JUMP(this) < 2)
        ITEMS_STAT(this) &= ~IT_USING_JETPACK;
    if(PHYS_INPUT_BUTTON_JUMP(this) || PHYS_INPUT_BUTTON_JETPACK(this))
    {
        float air_jump = !PlayerJump(this) || player_multijump; // PlayerJump() has important side effects
        float activate = JETPACK_JUMP(this) && air_jump && PHYS_INPUT_BUTTON_JUMP(this) || PHYS_INPUT_BUTTON_JETPACK(this);
        float has_fuel = !PHYS_JETPACK_FUEL(this) || PHYS_AMMO_FUEL(this) || ITEMS_STAT(this) & IT_UNLIMITED_WEAPON_AMMO;
        if (!(ITEMS_STAT(this) & ITEM_Jetpack.m_itemid)) { }
        else if (this.jetpack_stopped) { }
        else if (!has_fuel)
        {
#ifdef SVQC
            if (was_flying) // TODO: ran out of fuel message
                Send_Notification(NOTIF_ONE, this, MSG_INFO, INFO_JETPACK_NOFUEL);
            else if (activate)
                Send_Notification(NOTIF_ONE, this, MSG_INFO, INFO_JETPACK_NOFUEL);
#endif
            this.jetpack_stopped = true;
            ITEMS_STAT(this) &= ~IT_USING_JETPACK;
        }
        else if (activate && !PHYS_FROZEN(this))
            ITEMS_STAT(this) |= IT_USING_JETPACK;
    }
    else
    {
        this.jetpack_stopped = false;
        ITEMS_STAT(this) &= ~IT_USING_JETPACK;
    }
    if (!PHYS_INPUT_BUTTON_JUMP(this))
        UNSET_JUMP_HELD(this);
    if (this.waterlevel == WATERLEVEL_SWIMMING)
        CheckWaterJump(this);
}
void CheckWaterJump (entity this)
Definition at line 539 of file player.qc.
References FL_WATERJUMP, flags, movedir, normalize(), origin, SET_JUMP_HELD, time, trace_fraction, trace_plane_normal, v_angle, v_forward, and vector().
Referenced by CheckPlayerJump().
{
// check for a jump-out-of-water
    makevectors(this.v_angle);
    vector start = this.origin;
    start_z += 8;
    v_forward_z = 0;
    normalize(v_forward);
    vector end = start + v_forward*24;
    traceline (start, end, true, this);
    if (trace_fraction < 1)
    {   // solid at waist
        start_z = start_z + this.maxs_z - 8;
        end = start + v_forward*24;
        this.movedir = trace_plane_normal * -50;
        traceline(start, end, true, this);
        if (trace_fraction == 1)
        {   // open at eye level
            this.velocity_z = 225;
            this.flags |= FL_WATERJUMP;
            SET_JUMP_HELD(this);
        #ifdef SVQC
            PHYS_TELEPORT_TIME(this) = time + 2;    // safety net
        #elif defined(CSQC)
            pmove_waterjumptime = time + 2;
        #endif
        }
    }
}
void CPM_PM_Aircontrol (entity this, vector wishdir, float wishspeed)
Definition at line 288 of file player.qc.
References bound(), IsMoveInDirection(), max(), movement, normalize(), PHYS_AIRCONTROL, PHYS_AIRCONTROL_PENALTY, PHYS_AIRCONTROL_POWER, PHYS_MAXAIRSPEED, pow(), sqrt(), velocity, and vlen().
Referenced by PM_air().
{
    float k = 32 * (2 * IsMoveInDirection(this.movement, 0) - 1);
    if (k <= 0)
        return;
    k *= bound(0, wishspeed / PHYS_MAXAIRSPEED(this), 1);
    float zspeed = this.velocity_z;
    this.velocity_z = 0;
    float xyspeed = vlen(this.velocity);
    this.velocity = normalize(this.velocity);
    float dot = this.velocity * wishdir;
    if (dot > 0) // we can't change direction while slowing down
    {
        k *= pow(dot, PHYS_AIRCONTROL_POWER(this)) * PHYS_INPUT_TIMELENGTH;
        xyspeed = max(0, xyspeed - PHYS_AIRCONTROL_PENALTY(this) * sqrt(max(0, 1 - dot*dot)) * k/32);
        k *= PHYS_AIRCONTROL(this);
        this.velocity = normalize(this.velocity * xyspeed + wishdir * k);
    }
    this.velocity = this.velocity * xyspeed;
    this.velocity_z = zspeed;
}
float GeomLerp (float a, float lerp, float b)
Definition at line 76 of file player.qc.
References fabs(), and pow().
Referenced by PM_air().
{
    return a == 0 ? (lerp < 1 ? 0 : b)
        : b == 0 ? (lerp > 0 ? 0 : a)
        : a * pow(fabs(b / a), lerp);
}
bool IsFlying (entity this)
Definition at line 1274 of file player.qc.
References IS_ONGROUND, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by Damage(), and PM_Main().
{
    if(IS_ONGROUND(this))
        return false;
    if(this.waterlevel >= WATERLEVEL_SWIMMING)
        return false;
    //traceline(this.origin, this.origin - '0 0 48', MOVE_NORMAL, this);
    //if(trace_fraction < 1)
        //return false;
    return true;
}
float IsMoveInDirection (vector mv, float ang)
Definition at line 67 of file player.qc.
References fabs(), RAD2DEG, and remainder().
Referenced by CPM_PM_Aircontrol(), and PM_air().
{
    if (mv_x == 0 && mv_y == 0)
        return 0; // avoid division by zero
    ang -= RAD2DEG * atan2(mv_y, mv_x);
    ang = remainder(ang, 360) / 45;
    return ang > 1 ? 0 : ang < -1 ? 0 : 1 - fabs(ang);
}
bool PlayerJump (entity this)
Definition at line 432 of file player.qc.
References ANIMACTION_JUMP, animdecide_setaction(), autocvar_g_jump_grunt, autocvar_speedmeter, CH_PLAYER, ftos(), IS_JUMP_HELD, IS_ONGROUND, jumppadcount, lastground, LOG_TRACE(), maxs, mins, MOVE_NORMAL, MUTATOR_CALLHOOK, origin, PHYS_FRICTION_ONLAND, PHYS_FROZEN, PHYS_JUMPSPEEDCAP_DISABLE_ONRAMPS, PHYS_JUMPVELOCITY, PHYS_MAXSPEED, PHYS_TRACK_CANJUMP, player_blocked, player_jumpheight, player_multijump, SET_JUMP_HELD, stof(), strcat(), time, trace_fraction, UNSET_ONGROUND, velocity, viewloc, vlen(), VOICETYPE_PLAYERSOUND, vtos(), WAS_ONGROUND, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by CheckPlayerJump().
{
    if (PHYS_FROZEN(this))
        return true; // no jumping in freezetag when frozen
#ifdef SVQC
    if (this.player_blocked)
        return true; // no jumping while blocked
#endif
    bool doublejump = false;
    float mjumpheight = PHYS_JUMPVELOCITY(this);
    if (MUTATOR_CALLHOOK(PlayerJump, this, doublejump, mjumpheight))
        return true;
    doublejump = player_multijump;
    mjumpheight = player_jumpheight;
    if (this.waterlevel >= WATERLEVEL_SWIMMING)
    {
        if(this.viewloc)
        {
            doublejump = true;
            mjumpheight *= 0.7;
        }
        else
        {
            this.velocity_z = PHYS_MAXSPEED(this) * 0.7;
            return true;
        }
    }
    if (!doublejump)
        if (!IS_ONGROUND(this))
            return IS_JUMP_HELD(this);
    bool track_jump = PHYS_CL_TRACK_CANJUMP(this);
    if(PHYS_TRACK_CANJUMP(this))
        track_jump = true;
    if (track_jump)
        if (IS_JUMP_HELD(this))
            return true;
    // sv_jumpspeedcap_min/sv_jumpspeedcap_max act as baseline
    // velocity bounds.  Final velocity is bound between (jumpheight *
    // min + jumpheight) and (jumpheight * max + jumpheight);
    if(PHYS_JUMPSPEEDCAP_MIN != "")
    {
        float minjumpspeed = mjumpheight * stof(PHYS_JUMPSPEEDCAP_MIN);
        if (this.velocity_z < minjumpspeed)
            mjumpheight += minjumpspeed - this.velocity_z;
    }
    if(PHYS_JUMPSPEEDCAP_MAX != "")
    {
        // don't do jump speedcaps on ramps to preserve old xonotic ramjump style
        tracebox(this.origin + '0 0 0.01', this.mins, this.maxs, this.origin - '0 0 0.01', MOVE_NORMAL, this);
        if (!(trace_fraction < 1 && trace_plane_normal_z < 0.98 && PHYS_JUMPSPEEDCAP_DISABLE_ONRAMPS(this)))
        {
            float maxjumpspeed = mjumpheight * stof(PHYS_JUMPSPEEDCAP_MAX);
            if (this.velocity_z > maxjumpspeed)
                mjumpheight -= this.velocity_z - maxjumpspeed;
        }
    }
    if (!WAS_ONGROUND(this))
    {
#ifdef SVQC
        if(autocvar_speedmeter)
            LOG_TRACE(strcat("landing velocity: ", vtos(this.velocity), " (abs: ", ftos(vlen(this.velocity)), ")\n"));
#endif
        if(this.lastground < time - 0.3)
        {
            float f = (1 - PHYS_FRICTION_ONLAND(this));
            this.velocity_x *= f;
            this.velocity_y *= f;
        }
#ifdef SVQC
        if(this.jumppadcount > 1)
            LOG_TRACE(strcat(ftos(this.jumppadcount), "x jumppad combo\n"));
        this.jumppadcount = 0;
#endif
    }
    this.velocity_z += mjumpheight;
    UNSET_ONGROUND(this);
    SET_JUMP_HELD(this);
#ifdef SVQC
    this.oldvelocity_z = this.velocity_z;
    animdecide_setaction(this, ANIMACTION_JUMP, true);
    if (autocvar_g_jump_grunt)
        PlayerSound(this, playersound_jump, CH_PLAYER, VOICETYPE_PLAYERSOUND);
#endif
    return true;
}
void PM_Accelerate (entity this, vector wishdir, float wishspeed, float wishspeed0, float accel, float accelqw, float stretchfactor, float sidefric, float speedlimit)
Definition at line 325 of file player.qc.
References AdjustAirAccelQW(), bound(), fabs(), max(), sqrt(), vec2, vector(), velocity, and vlen().
Referenced by PM_air(), PM_fly(), PM_ladder(), and PM_swim().
{
    float speedclamp = stretchfactor > 0 ? stretchfactor
    : accelqw < 0 ? 1 // full clamping, no stretch
    : -1; // no clamping
    accelqw = fabs(accelqw);
    if (GAMEPLAYFIX_Q2AIRACCELERATE)
        wishspeed0 = wishspeed; // don't need to emulate this Q1 bug
    float vel_straight = this.velocity * wishdir;
    float vel_z = this.velocity_z;
    vector vel_xy = vec2(this.velocity);
    vector vel_perpend = vel_xy - vel_straight * wishdir;
    float step = accel * PHYS_INPUT_TIMELENGTH * wishspeed0;
    float vel_xy_current  = vlen(vel_xy);
    if (speedlimit)
        accelqw = AdjustAirAccelQW(accelqw, (speedlimit - bound(wishspeed, vel_xy_current, speedlimit)) / max(1, speedlimit - wishspeed));
    float vel_xy_forward =  vel_xy_current  + bound(0, wishspeed - vel_xy_current, step) * accelqw + step * (1 - accelqw);
    float vel_xy_backward = vel_xy_current  - bound(0, wishspeed + vel_xy_current, step) * accelqw - step * (1 - accelqw);
    vel_xy_backward = max(0, vel_xy_backward); // not that it REALLY occurs that this would cause wrong behaviour afterwards
    vel_straight =          vel_straight    + bound(0, wishspeed - vel_straight,   step) * accelqw + step * (1 - accelqw);
    if (sidefric < 0 && (vel_perpend*vel_perpend))
        // negative: only apply so much sideways friction to stay below the speed you could get by "braking"
    {
        float f = max(0, 1 + PHYS_INPUT_TIMELENGTH * wishspeed * sidefric);
        float themin = (vel_xy_backward * vel_xy_backward - vel_straight * vel_straight) / (vel_perpend * vel_perpend);
        // assume: themin > 1
        // vel_xy_backward*vel_xy_backward - vel_straight*vel_straight > vel_perpend*vel_perpend
        // vel_xy_backward*vel_xy_backward > vel_straight*vel_straight + vel_perpend*vel_perpend
        // vel_xy_backward*vel_xy_backward > vel_xy * vel_xy
        // obviously, this cannot be
        if (themin <= 0)
            vel_perpend *= f;
        else
        {
            themin = sqrt(themin);
            vel_perpend *= max(themin, f);
        }
    }
    else
        vel_perpend *= max(0, 1 - PHYS_INPUT_TIMELENGTH * wishspeed * sidefric);
    vel_xy = vel_straight * wishdir + vel_perpend;
    if (speedclamp >= 0)
    {
        float vel_xy_preclamp;
        vel_xy_preclamp = vlen(vel_xy);
        if (vel_xy_preclamp > 0) // prevent division by zero
        {
            vel_xy_current += (vel_xy_forward - vel_xy_current) * speedclamp;
            if (vel_xy_current < vel_xy_preclamp)
                vel_xy *= (vel_xy_current / vel_xy_preclamp);
        }
    }
    this.velocity = vel_xy + vel_z * '0 0 1';
}
void PM_air (entity this, float buttons_prev, float maxspd_mod)
Definition at line 1194 of file player.qc.
References autocvar_cl_movement, CPM_PM_Aircontrol(), fabs(), GeomLerp(), IS_ONGROUND, IsMoveInDirection(), max(), min(), movement, normalize(), PHYS_AIRACCEL_QW, PHYS_AIRACCEL_QW_STRETCHFACTOR, PHYS_AIRACCEL_SIDEWAYS_FRICTION, PHYS_AIRACCELERATE, PHYS_AIRCONTROL, PHYS_AIRSPEEDLIMIT_NONQW, PHYS_AIRSTOPACCELERATE, PHYS_AIRSTRAFEACCEL_QW, PHYS_AIRSTRAFEACCELERATE, PHYS_MAXAIRSPEED, PHYS_MAXAIRSTRAFESPEED, PHYS_WARSOWBUNNY_TURNACCEL, PM_Accelerate(), PM_AirAccelerate(), PM_ClientMovement_Move(), time, v_angle, v_forward, v_right, vec2, vector(), velocity, and vlen().
Referenced by PM_Main().
{
    makevectors(this.v_angle.y * '0 1 0');
    vector wishvel = v_forward * this.movement.x
                    + v_right * this.movement.y;
    // acceleration
    vector wishdir = normalize(wishvel);
    float wishspeed = vlen(wishvel);
#ifdef SVQC
    if(time >= PHYS_TELEPORT_TIME(this))
#elif defined(CSQC)
    if(pmove_waterjumptime <= 0)
#endif
    {
        float maxairspd = PHYS_MAXAIRSPEED(this) * min(maxspd_mod, 1);
        // apply air speed limit
        float airaccelqw = PHYS_AIRACCEL_QW(this);
        float wishspeed0 = wishspeed;
        wishspeed = min(wishspeed, maxairspd);
        if (IS_DUCKED(this))
            wishspeed *= 0.5;
        float airaccel = PHYS_AIRACCELERATE(this) * min(maxspd_mod, 1);
        float accelerating = (this.velocity * wishdir > 0);
        float wishspeed2 = wishspeed;
        // CPM: air control
        if (PHYS_AIRSTOPACCELERATE(this))
        {
            vector curdir = normalize(vec2(this.velocity));
            airaccel += (PHYS_AIRSTOPACCELERATE(this)*maxspd_mod - airaccel) * max(0, -(curdir * wishdir));
        }
        // note that for straight forward jumping:
        // step = accel * PHYS_INPUT_TIMELENGTH * wishspeed0;
        // accel  = bound(0, wishspeed - vel_xy_current, step) * accelqw + step * (1 - accelqw);
        // -->
        // dv/dt = accel * maxspeed (when slow)
        // dv/dt = accel * maxspeed * (1 - accelqw) (when fast)
        // log dv/dt = logaccel + logmaxspeed (when slow)
        // log dv/dt = logaccel + logmaxspeed + log(1 - accelqw) (when fast)
        float strafity = IsMoveInDirection(this.movement, -90) + IsMoveInDirection(this.movement, +90); // if one is nonzero, other is always zero
        if (PHYS_MAXAIRSTRAFESPEED(this))
            wishspeed = min(wishspeed, GeomLerp(PHYS_MAXAIRSPEED(this)*maxspd_mod, strafity, PHYS_MAXAIRSTRAFESPEED(this)*maxspd_mod));
        if (PHYS_AIRSTRAFEACCELERATE(this))
            airaccel = GeomLerp(airaccel, strafity, PHYS_AIRSTRAFEACCELERATE(this)*maxspd_mod);
        if (PHYS_AIRSTRAFEACCEL_QW(this))
            airaccelqw =
                (((strafity > 0.5 ? PHYS_AIRSTRAFEACCEL_QW(this) : PHYS_AIRACCEL_QW(this)) >= 0) ? +1 : -1)
                *
                (1 - GeomLerp(1 - fabs(PHYS_AIRACCEL_QW(this)), strafity, 1 - fabs(PHYS_AIRSTRAFEACCEL_QW(this))));
        // !CPM
        if (PHYS_WARSOWBUNNY_TURNACCEL(this) && accelerating && this.movement.y == 0 && this.movement.x != 0)
            PM_AirAccelerate(this, wishdir, wishspeed2);
        else
            PM_Accelerate(this, wishdir, wishspeed, wishspeed0, airaccel, airaccelqw, PHYS_AIRACCEL_QW_STRETCHFACTOR(this), PHYS_AIRACCEL_SIDEWAYS_FRICTION(this) / maxairspd, PHYS_AIRSPEEDLIMIT_NONQW(this));
        if (PHYS_AIRCONTROL(this))
            CPM_PM_Aircontrol(this, wishdir, wishspeed2);
    }
#ifdef CSQC
    float g = PHYS_GRAVITY(this) * PHYS_ENTGRAVITY(this) * PHYS_INPUT_TIMELENGTH;
    if(autocvar_cl_movement == 3)
    if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
        this.velocity_z -= g * 0.5;
    else
        this.velocity_z -= g;
#endif
    PM_ClientMovement_Move(this);
#ifdef CSQC
    if(autocvar_cl_movement == 3)
    if (!IS_ONGROUND(this) || !(GAMEPLAYFIX_NOGRAVITYONGROUND))
        if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
            this.velocity_z -= g * 0.5;
#endif
}
void PM_AirAccelerate (entity this, vector wishdir, float wishspeed)
Definition at line 389 of file player.qc.
References max(), min(), normalize(), PHYS_MAXSPEED, PHYS_WARSOWBUNNY_ACCEL, PHYS_WARSOWBUNNY_AIRFORWARDACCEL, PHYS_WARSOWBUNNY_BACKTOSIDERATIO, PHYS_WARSOWBUNNY_TOPSPEED, PHYS_WARSOWBUNNY_TURNACCEL, vector(), velocity, and vlen().
Referenced by PM_air().
{
    if (wishspeed == 0)
        return;
    vector curvel = this.velocity;
    curvel_z = 0;
    float curspeed = vlen(curvel);
    if (wishspeed > curspeed * 1.01)
        wishspeed = min(wishspeed, curspeed + PHYS_WARSOWBUNNY_AIRFORWARDACCEL(this) * PHYS_MAXSPEED(this) * PHYS_INPUT_TIMELENGTH);
    else
    {
        float f = max(0, (PHYS_WARSOWBUNNY_TOPSPEED(this) - curspeed) / (PHYS_WARSOWBUNNY_TOPSPEED(this) - PHYS_MAXSPEED(this)));
        wishspeed = max(curspeed, PHYS_MAXSPEED(this)) + PHYS_WARSOWBUNNY_ACCEL(this) * f * PHYS_MAXSPEED(this) * PHYS_INPUT_TIMELENGTH;
    }
    vector wishvel = wishdir * wishspeed;
    vector acceldir = wishvel - curvel;
    float addspeed = vlen(acceldir);
    acceldir = normalize(acceldir);
    float accelspeed = min(addspeed, PHYS_WARSOWBUNNY_TURNACCEL(this) * PHYS_MAXSPEED(this) * PHYS_INPUT_TIMELENGTH);
    if (PHYS_WARSOWBUNNY_BACKTOSIDERATIO(this) < 1)
    {
        vector curdir = normalize(curvel);
        float dot = acceldir * curdir;
        if (dot < 0)
            acceldir -= (1 - PHYS_WARSOWBUNNY_BACKTOSIDERATIO(this)) * dot * curdir;
    }
    this.velocity += accelspeed * acceldir;
}
void PM_check_blocked (entity this)
Definition at line 797 of file player.qc.
References disableclientprediction, movement, and player_blocked.
Referenced by PM_Main().
{
#ifdef SVQC
    if (!this.player_blocked)
        return;
    this.movement = '0 0 0';
    this.disableclientprediction = 1;
#endif
}
void PM_check_frozen (entity this)
Definition at line 730 of file player.qc.
References absmax, absmin, bound(), CONTENT_WATER, IS_REAL_CLIENT, movement, PHYS_DODGING_FROZEN, PHYS_FROZEN, vector(), and velocity.
Referenced by PM_Main().
{
    if (!PHYS_FROZEN(this))
        return;
    if (PHYS_DODGING_FROZEN(this)
#ifdef SVQC
    && IS_REAL_CLIENT(this)
#endif
    )
    {
        this.movement_x = bound(-5, this.movement.x, 5);
        this.movement_y = bound(-5, this.movement.y, 5);
        this.movement_z = bound(-5, this.movement.z, 5);
    }
    else
        this.movement = '0 0 0';
    vector midpoint = ((this.absmin + this.absmax) * 0.5);
    if (pointcontents(midpoint) == CONTENT_WATER)
    {
        this.velocity = this.velocity * 0.5;
        if (pointcontents(midpoint + '0 0 16') == CONTENT_WATER)
            this.velocity_z = 200;
    }
}
void PM_check_hitground (entity this)
Definition at line 757 of file player.qc.
References CH_PLAYER, entity(), hook, ladder_time, maxs, mins, MOVE_NOMONSTERS, nextstep, origin, Q3SURFACEFLAG_METALSTEPS, Q3SURFACEFLAG_NOSTEPS, random(), time, trace_dphitq3surfaceflags, VOICETYPE_PLAYERSOUND, wasFlying, waterlevel, and WATERLEVEL_SWIMMING.
Referenced by PM_Main().
{
#ifdef SVQC
    if (!this.wasFlying) return;
    this.wasFlying = false;
    if (this.waterlevel >= WATERLEVEL_SWIMMING) return;
    if (time < this.ladder_time) return;
    if (this.hook) return;
    this.nextstep = time + 0.3 + random() * 0.1;
    trace_dphitq3surfaceflags = 0;
    tracebox(this.origin, this.mins, this.maxs, this.origin - '0 0 1', MOVE_NOMONSTERS, this);
    if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOSTEPS) return;
    entity gs = (trace_dphitq3surfaceflags & Q3SURFACEFLAG_METALSTEPS)
        ? GS_FALL_METAL
        : GS_FALL;
    GlobalSound(this, gs, CH_PLAYER, VOICETYPE_PLAYERSOUND);
#endif
}
void PM_check_nickspam (entity this)
Definition at line 684 of file player.qc.
References autocvar_g_nick_flood_penalty_red, autocvar_g_nick_flood_penalty_yellow, BUTTON_ATCK, BUTTON_ATCK2, BUTTON_CROUCH, BUTTON_HOOK, BUTTON_JUMP, BUTTON_USE, BUTTON_ZOOM, fixangle, movement, nickspamcount, nickspamtime, random(), and time.
Referenced by PM_Main().
{
#ifdef SVQC
    if (time >= this.nickspamtime)
        return;
    if (this.nickspamcount >= autocvar_g_nick_flood_penalty_yellow)
    {
        // slight annoyance for nick change scripts
        this.movement = -1 * this.movement;
        this.BUTTON_ATCK = this.BUTTON_JUMP = this.BUTTON_ATCK2 = this.BUTTON_ZOOM = this.BUTTON_CROUCH = this.BUTTON_HOOK = this.BUTTON_USE = 0;
        if (this.nickspamcount >= autocvar_g_nick_flood_penalty_red) // if you are persistent and the slight annoyance above does not stop you, I'll show you!
        {
            this.v_angle_x = random() * 360;
            this.v_angle_y = random() * 360;
            // at least I'm not forcing retardedview by also assigning to angles_z
            this.fixangle = true;
        }
    }
#endif
}
void PM_check_punch (entity this)
Definition at line 706 of file player.qc.
References normalize(), punchangle, punchvector, and vlen().
Referenced by PM_Main().
{
#ifdef SVQC
    if (this.punchangle != '0 0 0')
    {
        float f = vlen(this.punchangle) - 10 * PHYS_INPUT_TIMELENGTH;
        if (f > 0)
            this.punchangle = normalize(this.punchangle) * f;
        else
            this.punchangle = '0 0 0';
    }
    if (this.punchvector != '0 0 0')
    {
        float f = vlen(this.punchvector) - 30 * PHYS_INPUT_TIMELENGTH;
        if (f > 0)
            this.punchvector = normalize(this.punchvector) * f;
        else
            this.punchvector = '0 0 0';
    }
#endif
}
float PM_check_specialcommand (entity this, float buttons)
Definition at line 647 of file player.qc.
References SpecialCommand(), specialcommand_pos, strlen(), and substring().
Referenced by PM_Main().
{
#ifdef SVQC
    string c;
    if (!buttons)
        c = "x";
    else if (buttons == 1)
        c = "1";
    else if (buttons == 2)
        c = " ";
    else if (buttons == 128)
        c = "s";
    else if (buttons == 256)
        c = "w";
    else if (buttons == 512)
        c = "a";
    else if (buttons == 1024)
        c = "d";
    else
        c = "?";
    if (c == substring(specialcommand, this.specialcommand_pos, 1))
    {
        this.specialcommand_pos += 1;
        if (this.specialcommand_pos >= strlen(specialcommand))
        {
            this.specialcommand_pos = 0;
            SpecialCommand();
            return true;
        }
    }
    else if (this.specialcommand_pos && (c != substring(specialcommand, this.specialcommand_pos - 1, 1)))
        this.specialcommand_pos = 0;
#endif
    return false;
}
void PM_ClientMovement_Move (entity this)
Definition at line 196 of file player.qc.
References autocvar_cl_movement, fabs(), maxs, mins, MOVE_NORMAL, origin, PHYS_STEPHEIGHT, PM_ClientMovement_UpdateStatus(), SET_ONGROUND, trace_endpos, trace_fraction, trace_plane_normal, trace_startsolid, vector(), and velocity.
Referenced by PM_air(), PM_fly(), PM_jetpack(), PM_ladder(), PM_swim(), and PM_walk().
{
#ifdef CSQC
    PM_ClientMovement_UpdateStatus(this, false);
    if(autocvar_cl_movement == 1)
        return;
    int bump;
    float t;
    float f;
    vector neworigin;
    vector currentorigin2;
    vector neworigin2;
    vector primalvelocity;
    vector trace1_endpos = '0 0 0';
    vector trace2_endpos = '0 0 0';
    vector trace3_endpos = '0 0 0';
    float trace1_fraction = 0;
    float trace2_fraction = 0;
    float trace3_fraction = 0;
    vector trace1_plane_normal = '0 0 0';
    vector trace2_plane_normal = '0 0 0';
    vector trace3_plane_normal = '0 0 0';
    primalvelocity = this.velocity;
    for(bump = 0, t = PHYS_INPUT_TIMELENGTH; bump < 8 && (this.velocity * this.velocity) > 0; bump++)
    {
        neworigin = this.origin + t * this.velocity;
        tracebox(this.origin, this.mins, this.maxs, neworigin, MOVE_NORMAL, this);
        trace1_endpos = trace_endpos;
        trace1_fraction = trace_fraction;
        trace1_plane_normal = trace_plane_normal;
        if(trace1_fraction < 1 && trace1_plane_normal_z == 0)
        {
            // may be a step or wall, try stepping up
            // first move forward at a higher level
            currentorigin2 = this.origin;
            currentorigin2_z += PHYS_STEPHEIGHT(this);
            neworigin2 = neworigin;
            neworigin2_z += PHYS_STEPHEIGHT(this);
            tracebox(currentorigin2, this.mins, this.maxs, neworigin2, MOVE_NORMAL, this);
            trace2_endpos = trace_endpos;
            trace2_fraction = trace_fraction;
            trace2_plane_normal = trace_plane_normal;
            if(!trace_startsolid)
            {
                // then move down from there
                currentorigin2 = trace2_endpos;
                neworigin2 = trace2_endpos;
                neworigin2_z = this.origin_z;
                tracebox(currentorigin2, this.mins, this.maxs, neworigin2, MOVE_NORMAL, this);
                trace3_endpos = trace_endpos;
                trace3_fraction = trace_fraction;
                trace3_plane_normal = trace_plane_normal;
                // accept the new trace if it made some progress
                if(fabs(trace3_endpos_x - trace1_endpos_x) >= 0.03125 || fabs(trace3_endpos_y - trace1_endpos_y) >= 0.03125)
                {
                    trace1_endpos = trace2_endpos;
                    trace1_fraction = trace2_fraction;
                    trace1_plane_normal = trace2_plane_normal;
                    trace1_endpos = trace3_endpos;
                }
            }
        }
        // check if it moved at all
        if(trace1_fraction >= 0.001)
            setorigin(this, trace1_endpos);
        // check if it moved all the way
        if(trace1_fraction == 1)
            break;
        // this is only really needed for nogravityonground combined with gravityunaffectedbyticrate
        // <LordHavoc> I'm pretty sure I commented it out solely because it seemed redundant
        // this got commented out in a change that supposedly makes the code match QW better
        // so if this is broken, maybe put it in an if(cls.protocol != PROTOCOL_QUAKEWORLD) block
        if(trace1_plane_normal_z > 0.7)
            SET_ONGROUND(this);
        t -= t * trace1_fraction;
        f = (this.velocity * trace1_plane_normal);
        this.velocity = this.velocity + -f * trace1_plane_normal;
    }
    if(PHYS_TELEPORT_TIME(this) > 0)
        this.velocity = primalvelocity;
#endif
}
void PM_ClientMovement_Unstick (entity this)
Definition at line 105 of file player.qc.
References unstick_offsets, and X.
Referenced by PM_ClientMovement_UpdateStatus().
{
    #define X(unstick_offset) \
    { \
        vector neworigin = unstick_offset + this.origin; \
        tracebox(neworigin, STAT(PL_CROUCH_MIN, NULL), STAT(PL_CROUCH_MAX, NULL), neworigin, MOVE_NORMAL, this); \
        if (!trace_startsolid) \
        { \
            setorigin(this, neworigin); \
            return; \
        } \
    }
    unstick_offsets(X);
    #undef X
}
void PM_ClientMovement_UpdateStatus (entity this, bool ground)
Definition at line 121 of file player.qc.
References autocvar_cl_movement, CONTENT_LAVA, CONTENT_SLIME, CONTENT_WATER, IS_ONGROUND, IS_PLAYER, maxs, mins, MOVE_NORMAL, NULL, origin, PHYS_INPUT_BUTTON_CROUCH, PM_ClientMovement_Unstick(), SET_ONGROUND, trace_plane_normal, trace_startsolid, UNSET_ONGROUND, vector(), velocity, waterlevel, WATERLEVEL_NONE, WATERLEVEL_SUBMERGED, WATERLEVEL_SWIMMING, WATERLEVEL_WETFEET, and watertype.
Referenced by PM_ClientMovement_Move(), and PM_Main().
{
#ifdef CSQC
    if(!IS_PLAYER(this))
        return;
    // make sure player is not stuck
    if(autocvar_cl_movement == 3)
        PM_ClientMovement_Unstick(this);
    // set crouched
    if (PHYS_INPUT_BUTTON_CROUCH(this))
    {
        // wants to crouch, this always works
        if (!IS_DUCKED(this)) SET_DUCKED(this);
    }
    else
    {
        // wants to stand, if currently crouching we need to check for a low ceiling first
        if (IS_DUCKED(this))
        {
            tracebox(this.origin, STAT(PL_MIN, NULL), STAT(PL_MAX, NULL), this.origin, MOVE_NORMAL, this);
            if (!trace_startsolid) UNSET_DUCKED(this);
        }
    }
    // set onground
    vector origin1 = this.origin + '0 0 1';
    vector origin2 = this.origin - '0 0 1';
    if (ground && autocvar_cl_movement == 3)
    {
        tracebox(origin1, this.mins, this.maxs, origin2, MOVE_NORMAL, this);
        if (trace_fraction < 1.0 && trace_plane_normal.z > 0.7)
        {
            SET_ONGROUND(this);
            // this code actually "predicts" an impact; so let's clip velocity first
            this.velocity -= this.velocity * trace_plane_normal * trace_plane_normal;
        }
        else
            UNSET_ONGROUND(this);
    }
    if(autocvar_cl_movement == 3)
    {
        // set watertype/waterlevel
        origin1 = this.origin;
        origin1.z += this.mins_z + 1;
        this.waterlevel = WATERLEVEL_NONE;
        int thepoint = pointcontents(origin1);
        this.watertype = (thepoint == CONTENT_WATER || thepoint == CONTENT_LAVA || thepoint == CONTENT_SLIME);
        if (this.watertype)
        {
            this.waterlevel = WATERLEVEL_WETFEET;
            origin1.z = this.origin.z + (this.mins.z + this.maxs.z) * 0.5;
            thepoint = pointcontents(origin1);
            if (thepoint == CONTENT_WATER || thepoint == CONTENT_LAVA || thepoint == CONTENT_SLIME)
            {
                this.waterlevel = WATERLEVEL_SWIMMING;
                origin1.z = this.origin.z + 22;
                thepoint = pointcontents(origin1);
                if (thepoint == CONTENT_WATER || thepoint == CONTENT_LAVA || thepoint == CONTENT_SLIME)
                    this.waterlevel = WATERLEVEL_SUBMERGED;
            }
        }
    }
    if (IS_ONGROUND(this) || this.velocity.z <= 0 || pmove_waterjumptime <= 0)
        pmove_waterjumptime = 0;
#endif
}
void PM_fly (entity this, float maxspd_mod)
Definition at line 807 of file player.qc.
References min(), movement, normalize(), PHYS_ACCELERATE, PHYS_FRICTION, PHYS_MAXSPEED, PM_Accelerate(), PM_ClientMovement_Move(), time, UNSET_ONGROUND, v_angle, v_forward, v_right, vector(), velocity, and vlen().
Referenced by PM_Main().
{
    // noclipping or flying
    UNSET_ONGROUND(this);
    this.velocity = this.velocity * (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this));
    makevectors(this.v_angle);
    //wishvel = v_forward * this.movement.x + v_right * this.movement.y + v_up * this.movement.z;
    vector wishvel = v_forward * this.movement.x
                    + v_right * this.movement.y
                    + '0 0 1' * this.movement.z;
    // acceleration
    vector wishdir = normalize(wishvel);
    float wishspeed = min(vlen(wishvel), PHYS_MAXSPEED(this) * maxspd_mod);
#ifdef SVQC
    if(time >= PHYS_TELEPORT_TIME(this))
#endif
        PM_Accelerate(this, wishdir, wishspeed, wishspeed, PHYS_ACCELERATE(this) * maxspd_mod, 1, 0, 0, 0);
    PM_ClientMovement_Move(this);
}
void PM_Footsteps (entity this)
Definition at line 776 of file player.qc.
References autocvar_sv_maxspeed, CH_PLAYER, entity(), g_footsteps, lastground, maxs, mins, MOVE_NOMONSTERS, nextstep, origin, Q3SURFACEFLAG_METALSTEPS, Q3SURFACEFLAG_NOSTEPS, random(), time, trace_dphitq3surfaceflags, vdist, velocity, and VOICETYPE_PLAYERSOUND.
Referenced by PM_Main().
{
#ifdef SVQC
    if (!g_footsteps) return;
    if (IS_DUCKED(this)) return;
    if (time >= this.lastground + 0.2) return;
    if (vdist(this.velocity, <=, autocvar_sv_maxspeed * 0.6)) return;
    if ((time > this.nextstep) || (time < (this.nextstep - 10.0)))
    {
        this.nextstep = time + 0.3 + random() * 0.1;
        trace_dphitq3surfaceflags = 0;
        tracebox(this.origin, this.mins, this.maxs, this.origin - '0 0 1', MOVE_NOMONSTERS, this);
        if (trace_dphitq3surfaceflags & Q3SURFACEFLAG_NOSTEPS) return;
        entity gs = (trace_dphitq3surfaceflags & Q3SURFACEFLAG_METALSTEPS)
            ? GS_STEP_METAL
            : GS_STEP;
        GlobalSound(this, gs, CH_PLAYER, VOICETYPE_PLAYERSOUND);
    }
#endif
}
void PM_jetpack (entity this, float maxspd_mod)
Definition at line 982 of file player.qc.
References ammo_fuel, autocvar_cl_movement, autocvar_g_balance_pause_fuel_regen, bound(), IS_ONGROUND, IT_UNLIMITED_WEAPON_AMMO, IT_USING_JETPACK, ITEMS_STAT, max(), min(), normalize(), pauseregen_finished, PHYS_AMMO_FUEL, PHYS_JETPACK_ACCEL_SIDE, PHYS_JETPACK_ACCEL_UP, PHYS_JETPACK_ANTIGRAVITY, PHYS_JETPACK_FUEL, PHYS_JETPACK_MAXSPEED_SIDE, PHYS_JETPACK_MAXSPEED_UP, PHYS_MAXAIRSPEED, PM_ClientMovement_Move(), sqrt(), time, UNSET_ONGROUND, v_angle, v_forward, v_right, vector(), velocity, and vlen().
Referenced by PM_Main().
{
    //makevectors(this.v_angle.y * '0 1 0');
    makevectors(this.v_angle);
    vector wishvel = v_forward * this.movement_x
                    + v_right * this.movement_y;
    // add remaining speed as Z component
    float maxairspd = PHYS_MAXAIRSPEED(this) * max(1, maxspd_mod);
    // fix speedhacks :P
    wishvel = normalize(wishvel) * min(1, vlen(wishvel) / maxairspd);
    // add the unused velocity as up component
    wishvel_z = 0;
    // if (this.BUTTON_JUMP)
        wishvel_z = sqrt(max(0, 1 - wishvel * wishvel));
    // it is now normalized, so...
    float a_side = PHYS_JETPACK_ACCEL_SIDE(this);
    float a_up = PHYS_JETPACK_ACCEL_UP(this);
    float a_add = PHYS_JETPACK_ANTIGRAVITY(this) * PHYS_GRAVITY(this);
    wishvel_x *= a_side;
    wishvel_y *= a_side;
    wishvel_z *= a_up;
    wishvel_z += a_add;
    float best = 0;
    // finding the maximum over all vectors of above form
    // with wishvel having an absolute value of 1
    // we're finding the maximum over
    //   f(a_side, a_up, a_add, z) := a_side * (1 - z^2) + (a_add + a_up * z)^2;
    // for z in the range from -1 to 1
    // maximum is EITHER attained at the single extreme point:
    float a_diff = a_side * a_side - a_up * a_up;
    float f;
    if (a_diff != 0)
    {
        f = a_add * a_up / a_diff; // this is the zero of diff(f(a_side, a_up, a_add, z), z)
        if (f > -1 && f < 1) // can it be attained?
        {
            best = (a_diff + a_add * a_add) * (a_diff + a_up * a_up) / a_diff;
            //print("middle\n");
        }
    }
    // OR attained at z = 1:
    f = (a_up + a_add) * (a_up + a_add);
    if (f > best)
    {
        best = f;
        //print("top\n");
    }
    // OR attained at z = -1:
    f = (a_up - a_add) * (a_up - a_add);
    if (f > best)
    {
        best = f;
        //print("bottom\n");
    }
    best = sqrt(best);
    //print("best possible acceleration: ", ftos(best), "\n");
    float fxy, fz;
    fxy = bound(0, 1 - (this.velocity * normalize(wishvel_x * '1 0 0' + wishvel_y * '0 1 0')) / PHYS_JETPACK_MAXSPEED_SIDE(this), 1);
    if (wishvel_z - PHYS_GRAVITY(this) > 0)
        fz = bound(0, 1 - this.velocity_z / PHYS_JETPACK_MAXSPEED_UP(this), 1);
    else
        fz = bound(0, 1 + this.velocity_z / PHYS_JETPACK_MAXSPEED_UP(this), 1);
    float fvel;
    fvel = vlen(wishvel);
    wishvel_x *= fxy;
    wishvel_y *= fxy;
    wishvel_z = (wishvel_z - PHYS_GRAVITY(this)) * fz + PHYS_GRAVITY(this);
    fvel = min(1, vlen(wishvel) / best);
    if (PHYS_JETPACK_FUEL(this) && !(ITEMS_STAT(this) & IT_UNLIMITED_WEAPON_AMMO))
        f = min(1, PHYS_AMMO_FUEL(this) / (PHYS_JETPACK_FUEL(this) * PHYS_INPUT_TIMELENGTH * fvel));
    else
        f = 1;
    //print("this acceleration: ", ftos(vlen(wishvel) * f), "\n");
    if (f > 0 && wishvel != '0 0 0')
    {
        this.velocity = this.velocity + wishvel * f * PHYS_INPUT_TIMELENGTH;
        UNSET_ONGROUND(this);
#ifdef SVQC
        if (!(ITEMS_STAT(this) & IT_UNLIMITED_WEAPON_AMMO))
            this.ammo_fuel -= PHYS_JETPACK_FUEL(this) * PHYS_INPUT_TIMELENGTH * fvel * f;
        ITEMS_STAT(this) |= IT_USING_JETPACK;
        // jetpack also inhibits health regeneration, but only for 1 second
        this.pauseregen_finished = max(this.pauseregen_finished, time + autocvar_g_balance_pause_fuel_regen);
#endif
    }
#ifdef CSQC
    float g = PHYS_GRAVITY(this) * PHYS_ENTGRAVITY(this) * PHYS_INPUT_TIMELENGTH;
    if(autocvar_cl_movement == 3)
    {
        if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
            this.velocity_z -= g * 0.5;
        else
            this.velocity_z -= g;
    }
    PM_ClientMovement_Move(this);
    if(autocvar_cl_movement == 3)
    {
        if (!IS_ONGROUND(this) || !(GAMEPLAYFIX_NOGRAVITYONGROUND))
            if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
                this.velocity_z -= g * 0.5;
    }
#endif
}
void PM_ladder (entity this, float maxspd_mod)
Definition at line 929 of file player.qc.
References CONTENT_EMPTY, ladder_entity, min(), normalize(), oldmovement, PHYS_ACCELERATE, PHYS_FRICTION, PHYS_MAXSPEED, PM_Accelerate(), PM_ClientMovement_Move(), time, UNSET_ONGROUND, v_angle, v_forward, v_right, vector(), velocity, viewloc, vlen(), waterlevel, WATERLEVEL_NONE, WATERLEVEL_SUBMERGED, WATERLEVEL_SWIMMING, WATERLEVEL_WETFEET, and watertype.
Referenced by PM_Main().
{
    // on a spawnfunc_func_ladder or swimming in spawnfunc_func_water
    UNSET_ONGROUND(this);
    float g;
    g = PHYS_GRAVITY(this) * PHYS_INPUT_TIMELENGTH;
    if (PHYS_ENTGRAVITY(this))
        g *= PHYS_ENTGRAVITY(this);
    if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
    {
        g *= 0.5;
        this.velocity_z += g;
    }
    this.velocity = this.velocity * (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this));
    makevectors(this.v_angle);
    //wishvel = v_forward * this.movement.x + v_right * this.movement.y + v_up * this.movement.z;
    vector wishvel = v_forward * this.movement_x
                    + v_right * this.movement_y
                    + '0 0 1' * this.movement_z;
    if(this.viewloc)
        wishvel.z = this.oldmovement.x;
    this.velocity_z += g;
    if (this.ladder_entity.classname == "func_water")
    {
        float f = vlen(wishvel);
        if (f > this.ladder_entity.speed)
            wishvel *= (this.ladder_entity.speed / f);
        this.watertype = this.ladder_entity.skin;
        f = this.ladder_entity.origin_z + this.ladder_entity.maxs_z;
        if ((this.origin_z + this.view_ofs_z) < f)
            this.waterlevel = WATERLEVEL_SUBMERGED;
        else if ((this.origin_z + (this.mins_z + this.maxs_z) * 0.5) < f)
            this.waterlevel = WATERLEVEL_SWIMMING;
        else if ((this.origin_z + this.mins_z + 1) < f)
            this.waterlevel = WATERLEVEL_WETFEET;
        else
        {
            this.waterlevel = WATERLEVEL_NONE;
            this.watertype = CONTENT_EMPTY;
        }
    }
    // acceleration
    vector wishdir = normalize(wishvel);
    float wishspeed = min(vlen(wishvel), PHYS_MAXSPEED(this) * maxspd_mod);
    if(time >= PHYS_TELEPORT_TIME(this))
        // water acceleration
        PM_Accelerate(this, wishdir, wishspeed, wishspeed, PHYS_ACCELERATE(this)*maxspd_mod, 1, 0, 0, 0);
    PM_ClientMovement_Move(this);
}
void PM_Main (entity this)
Definition at line 1286 of file player.qc.
References absmax, absmin, angles, anticheat_physics(), autocvar_sv_jumpspeedcap_max, autocvar_sv_jumpspeedcap_min, autocvar_sv_spectator_speed_multiplier, bot_think(), bound(), buttons_old, CheckPlayerJump(), classname, CONTENT_WATER, conveyor, disableclientprediction, entity(), fixangle, FL_WATERJUMP, flags, ftos(), game_starttime, impulse, in_swamp, IS_BOT_CLIENT, IS_DEAD, IS_ONGROUND, IS_PLAYER, IsFlying(), IT_USING_JETPACK, items, ITEMS_STAT, ladder_time, lastclassname, lastflags, lastground, max(), move_movetype, movedir, movement, movement_old, movetype, MOVETYPE_FLY, MOVETYPE_FLY_WORLDONLY, MOVETYPE_NOCLIP, MOVETYPE_NONE, MOVETYPE_WALK, MUTATOR_CALLHOOK, oldmovement, parm_idlesince, PHYS_HIGHSPEED, PHYS_INPUT_BUTTON_JUMP, PHYS_INPUT_BUTTON_MASK, PHYS_MAXAIRSPEED, PHYS_MAXSPEED, playerdemo_read(), PM_air(), PM_check_blocked(), PM_check_frozen(), PM_check_hitground(), PM_check_nickspam(), PM_check_punch(), PM_check_specialcommand(), PM_ClientMovement_UpdateStatus(), PM_fly(), PM_Footsteps(), PM_jetpack(), PM_ladder(), PM_swim(), PM_walk(), speed, STR_PLAYER, strcat(), sv_maxidle, swamp_slowdown, team, time, UNSET_JUMP_HELD, v_angle, v_angle_old, vector(), velocity, viewloc_PlayerPhysics(), wasFlying, waterlevel, WATERLEVEL_NONE, WATERLEVEL_SWIMMING, and WITH.
{
    int buttons = PHYS_INPUT_BUTTON_MASK(this);
#ifdef CSQC
    this.items = STAT(ITEMS);
    this.movement = PHYS_INPUT_MOVEVALUES(this);
    this.spectatorspeed = STAT(SPECTATORSPEED);
    vector oldv_angle = this.v_angle;
    vector oldangles = this.angles; // we need to save these, as they're abused by other code
    this.v_angle = PHYS_INPUT_ANGLES(this);
    this.angles = PHYS_WORLD_ANGLES(this);
    this.team = myteam + 1; // is this correct?
    if (!(PHYS_INPUT_BUTTON_JUMP(this))) // !jump
        UNSET_JUMP_HELD(this); // canjump = true
    pmove_waterjumptime -= PHYS_INPUT_TIMELENGTH;
    PM_ClientMovement_UpdateStatus(this, true);
#endif
    this.oldmovement = this.movement;
#ifdef SVQC
    WarpZone_PlayerPhysics_FixVAngle();
#endif
    float maxspeed_mod = 1;
    maxspeed_mod *= PHYS_HIGHSPEED(this);
#ifdef SVQC
    Physics_UpdateStats(this, maxspeed_mod);
    if (this.PlayerPhysplug)
        if (this.PlayerPhysplug())
            return;
#endif
#ifdef SVQC
    anticheat_physics(this);
#endif
    if (PM_check_specialcommand(this, buttons))
        return;
#ifdef SVQC
    if (sv_maxidle > 0)
    {
        if (buttons != this.buttons_old || this.movement != this.movement_old || this.v_angle != this.v_angle_old)
            this.parm_idlesince = time;
    }
#endif
    int buttons_prev = this.buttons_old;
    this.buttons_old = buttons;
    this.movement_old = this.movement;
    this.v_angle_old = this.v_angle;
    PM_check_nickspam(this);
    PM_check_punch(this);
#ifdef SVQC
    if (IS_BOT_CLIENT(this))
    {
        if (playerdemo_read(this))
            return;
        WITH(entity, self, this, bot_think());
    }
#endif
#ifdef SVQC
    if (IS_PLAYER(this))
    {
        const bool allowed_to_move = (time >= game_starttime);
        if (!allowed_to_move)
        {
            this.velocity = '0 0 0';
            this.movetype = MOVETYPE_NONE;
            this.disableclientprediction = 2;
        }
        else if (this.disableclientprediction == 2)
        {
            if (this.movetype == MOVETYPE_NONE)
                this.movetype = MOVETYPE_WALK;
            this.disableclientprediction = 0;
        }
    }
#endif
#ifdef SVQC
    if (this.movetype == MOVETYPE_NONE)
        return;
    // when we get here, disableclientprediction cannot be 2
    this.disableclientprediction = 0;
#endif
    viewloc_PlayerPhysics(this);
    PM_check_frozen(this);
    PM_check_blocked(this);
    maxspeed_mod = 1;
    if (this.in_swamp)
        maxspeed_mod *= this.swamp_slowdown; //cvar("g_balance_swamp_moverate");
    // conveyors: first fix velocity
    if (this.conveyor.state)
        this.velocity -= this.conveyor.movedir;
    MUTATOR_CALLHOOK(PlayerPhysics, this);
    if (!IS_PLAYER(this))
    {
#ifdef SVQC
        maxspeed_mod = autocvar_sv_spectator_speed_multiplier;
        if (!this.spectatorspeed)
            this.spectatorspeed = maxspeed_mod;
        if (this.impulse && this.impulse <= 19 || (this.impulse >= 200 && this.impulse <= 209) || (this.impulse >= 220 && this.impulse <= 229))
        {
            if (this.lastclassname != STR_PLAYER)
            {
                if (this.impulse == 10 || this.impulse == 15 || this.impulse == 18 || (this.impulse >= 200 && this.impulse <= 209))
                    this.spectatorspeed = bound(1, this.spectatorspeed + 0.5, 5);
                else if (this.impulse == 11)
                    this.spectatorspeed = maxspeed_mod;
                else if (this.impulse == 12 || this.impulse == 16  || this.impulse == 19 || (this.impulse >= 220 && this.impulse <= 229))
                    this.spectatorspeed = bound(1, this.spectatorspeed - 0.5, 5);
                else if (this.impulse >= 1 && this.impulse <= 9)
                    this.spectatorspeed = 1 + 0.5 * (this.impulse - 1);
            } // otherwise just clear
            this.impulse = 0;
        }
#endif
        maxspeed_mod = this.spectatorspeed;
    }
#ifdef SVQC
    float spd = max(PHYS_MAXSPEED(this), PHYS_MAXAIRSPEED(this)) * maxspeed_mod;
    if(this.speed != spd)
    {
        this.speed = spd;
        string temps = ftos(spd);
        stuffcmd(this, strcat("cl_forwardspeed ", temps, "\n"));
        stuffcmd(this, strcat("cl_backspeed ", temps, "\n"));
        stuffcmd(this, strcat("cl_sidespeed ", temps, "\n"));
        stuffcmd(this, strcat("cl_upspeed ", temps, "\n"));
    }
    if(this.jumpspeedcap_min != autocvar_sv_jumpspeedcap_min)
    {
        this.jumpspeedcap_min = autocvar_sv_jumpspeedcap_min;
        stuffcmd(this, sprintf("\ncl_jumpspeedcap_min \"%s\"\n", autocvar_sv_jumpspeedcap_min));
    }
    if(this.jumpspeedcap_max != autocvar_sv_jumpspeedcap_max)
    {
        this.jumpspeedcap_max = autocvar_sv_jumpspeedcap_max;
        stuffcmd(this, sprintf("\ncl_jumpspeedcap_max \"%s\"\n", autocvar_sv_jumpspeedcap_max));
    }
#endif
    if(IS_DEAD(this))
    {
        // handle water here
        vector midpoint = ((this.absmin + this.absmax) * 0.5);
        if(pointcontents(midpoint) == CONTENT_WATER)
        {
            this.velocity = this.velocity * 0.5;
            // do we want this?
            //if(pointcontents(midpoint + '0 0 2') == CONTENT_WATER)
                //{ this.velocity_z = 70; }
        }
        goto end;
    }
#ifdef SVQC
    if (!this.fixangle)
        this.angles = '0 1 0' * this.v_angle.y;
#endif
    if (IS_PLAYER(this) && IS_ONGROUND(this))
    {
        PM_check_hitground(this);
        PM_Footsteps(this);
    }
    if(IsFlying(this))
        this.wasFlying = 1;
    if (IS_PLAYER(this))
        CheckPlayerJump(this);
    if (this.flags & FL_WATERJUMP)
    {
        this.velocity_x = this.movedir.x;
        this.velocity_y = this.movedir.y;
        if (time > PHYS_TELEPORT_TIME(this) || this.waterlevel == WATERLEVEL_NONE)
        {
            this.flags &= ~FL_WATERJUMP;
            PHYS_TELEPORT_TIME(this) = 0;
        }
    }
    else if (MUTATOR_CALLHOOK(PM_Physics, this, maxspeed_mod))
        { }
#ifdef SVQC
    else if (this.movetype == MOVETYPE_NOCLIP || this.movetype == MOVETYPE_FLY || this.movetype == MOVETYPE_FLY_WORLDONLY || MUTATOR_CALLHOOK(IsFlying, this))
#elif defined(CSQC)
    else if (this.move_movetype == MOVETYPE_NOCLIP || this.move_movetype == MOVETYPE_FLY || this.move_movetype == MOVETYPE_FLY_WORLDONLY || MUTATOR_CALLHOOK(IsFlying, this))
#endif
        PM_fly(this, maxspeed_mod);
    else if (this.waterlevel >= WATERLEVEL_SWIMMING)
        PM_swim(this, maxspeed_mod);
    else if (time < this.ladder_time)
        PM_ladder(this, maxspeed_mod);
    else if (ITEMS_STAT(this) & IT_USING_JETPACK)
        PM_jetpack(this, maxspeed_mod);
    else if (IS_ONGROUND(this))
        PM_walk(this, maxspeed_mod);
    else
        PM_air(this, buttons_prev, maxspeed_mod);
:end
    if (IS_ONGROUND(this))
        this.lastground = time;
    // conveyors: then break velocity again
    if(this.conveyor.state)
        this.velocity += this.conveyor.movedir;
    this.lastflags = this.flags;
    this.lastclassname = this.classname;
#ifdef CSQC
    this.v_angle = oldv_angle;
    this.angles = oldangles;
#endif
}
void PM_swim (entity this, float maxspd_mod)
Definition at line 828 of file player.qc.
References CONTENT_LAVA, CONTENT_SLIME, max(), min(), MOVE_NOMONSTERS, movement, normalize(), origin, PHYS_ACCELERATE, PHYS_FRICTION, PHYS_INPUT_BUTTON_JUMP, PHYS_MAXSPEED, PM_Accelerate(), PM_ClientMovement_Move(), SET_JUMP_HELD, trace_startsolid, UNSET_ONGROUND, v_angle, v_forward, v_right, vector(), velocity, viewloc, vlen(), waterlevel, WATERLEVEL_SWIMMING, and watertype.
Referenced by PM_Main().
{
    // swimming
    UNSET_ONGROUND(this);
    float jump = PHYS_INPUT_BUTTON_JUMP(this);
    // water jump only in certain situations
    // this mimics quakeworld code
    if (jump && this.waterlevel == WATERLEVEL_SWIMMING && this.velocity_z >= -180 && !this.viewloc)
    {
        vector yawangles = '0 1 0' * this.v_angle.y;
        makevectors(yawangles);
        vector forward = v_forward;
        vector spot = this.origin + 24 * forward;
        spot_z += 8;
        traceline(spot, spot, MOVE_NOMONSTERS, this);
        if (trace_startsolid)
        {
            spot_z += 24;
            traceline(spot, spot, MOVE_NOMONSTERS, this);
            if (!trace_startsolid)
            {
                this.velocity = forward * 50;
                this.velocity_z = 310;
            #ifdef CSQC
                pmove_waterjumptime = 2;
            #endif
                UNSET_ONGROUND(this);
                SET_JUMP_HELD(this);
            }
        }
    }
    makevectors(this.v_angle);
    //wishvel = v_forward * this.movement.x + v_right * this.movement.y + v_up * this.movement.z;
    vector wishvel = v_forward * this.movement.x
                    + v_right * this.movement.y
                    + '0 0 1' * this.movement.z;
    if(this.viewloc)
        wishvel.z = -160; // drift anyway
    else if (wishvel == '0 0 0')
        wishvel = '0 0 -60'; // drift towards bottom
    vector wishdir = normalize(wishvel);
    float wishspeed = min(vlen(wishvel), PHYS_MAXSPEED(this) * maxspd_mod) * 0.7;
    if (IS_DUCKED(this))
        wishspeed *= 0.5;
//  if (pmove_waterjumptime <= 0) // TODO: use
    {
        // water friction
        float f = 1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this);
        f = min(max(0, f), 1);
        this.velocity *= f;
        f = wishspeed - this.velocity * wishdir;
        if (f > 0)
        {
            float accelspeed = min(PHYS_ACCELERATE(this) * PHYS_INPUT_TIMELENGTH * wishspeed, f);
            this.velocity += accelspeed * wishdir;
        }
        // holding jump button swims upward slowly
        if (jump && !this.viewloc)
        {
#if 0
            if (this.watertype & CONTENT_LAVA)
                this.velocity_z =  50;
            else if (this.watertype & CONTENT_SLIME)
                this.velocity_z =  80;
            else
            {
                if (IS_NEXUIZ_DERIVED(gamemode))
#endif
                    this.velocity_z = 200;
#if 0
                else
                    this.velocity_z = 100;
            }
#endif
        }
    }
    if(this.viewloc)
    {
        const float addspeed = wishspeed - this.velocity * wishdir;
        if (addspeed > 0)
        {
            const float accelspeed = min(PHYS_ACCELERATE(this) * PHYS_INPUT_TIMELENGTH * wishspeed, addspeed);
            this.velocity += accelspeed * wishdir;
        }
    }
    else
    {
        // water acceleration
        PM_Accelerate(this, wishdir, wishspeed, wishspeed, PHYS_ACCELERATE(this) * maxspd_mod, 1, 0, 0, 0);
        PM_ClientMovement_Move(this);
    }
}
void PM_walk (entity this, float maxspd_mod)
Definition at line 1104 of file player.qc.
References autocvar_cl_movement, autocvar_speedmeter, f2, ftos(), IS_ONGROUND, jumppadcount, lastground, LOG_TRACE(), max(), maxs, min(), mins, MOVE_NOMONSTERS, movement, normalize(), origin, PHYS_ACCELERATE, PHYS_FRICTION, PHYS_FRICTION_ONLAND, PHYS_FRICTION_SLICK, PHYS_MAXSPEED, PHYS_STOPSPEED, PM_ClientMovement_Move(), Q3SURFACEFLAG_SLICK, sqrt(), strcat(), time, trace_dphitq3surfaceflags, v_angle, v_forward, v_right, vdist, vec2, vector(), velocity, vlen(), vlen2, vtos(), and WAS_ONGROUND.
Referenced by PM_Main().
{
    if (!WAS_ONGROUND(this))
    {
#ifdef SVQC
        if (autocvar_speedmeter)
            LOG_TRACE(strcat("landing velocity: ", vtos(this.velocity), " (abs: ", ftos(vlen(this.velocity)), ")\n"));
#endif
        if (this.lastground < time - 0.3)
            this.velocity *= (1 - PHYS_FRICTION_ONLAND(this));
#ifdef SVQC
        if (this.jumppadcount > 1)
            LOG_TRACE(strcat(ftos(this.jumppadcount), "x jumppad combo\n"));
        this.jumppadcount = 0;
#endif
    }
    // walking
    makevectors(this.v_angle.y * '0 1 0');
    const vector wishvel = v_forward * this.movement.x
                        + v_right * this.movement.y;
    // acceleration
    const vector wishdir = normalize(wishvel);
    float wishspeed = vlen(wishvel);
    wishspeed = min(wishspeed, PHYS_MAXSPEED(this) * maxspd_mod);
    if (IS_DUCKED(this)) wishspeed *= 0.5;
    // apply edge friction
    const float f2 = vlen2(vec2(this.velocity));
    if (f2 > 0)
    {
        trace_dphitq3surfaceflags = 0;
        tracebox(this.origin, this.mins, this.maxs, this.origin - '0 0 1', MOVE_NOMONSTERS, this);
        // TODO: apply edge friction
        // apply ground friction
        const int realfriction = (trace_dphitq3surfaceflags & Q3SURFACEFLAG_SLICK)
            ? PHYS_FRICTION_SLICK(this)
            : PHYS_FRICTION(this);
        float f = sqrt(f2);
        f = 1 - PHYS_INPUT_TIMELENGTH * realfriction * ((f < PHYS_STOPSPEED(this)) ? (PHYS_STOPSPEED(this) / f) : 1);
        f = max(0, f);
        this.velocity *= f;
        /*
           Mathematical analysis time!
           Our goal is to invert this mess.
           For the two cases we get:
            v = v0 * (1 - PHYS_INPUT_TIMELENGTH * (PHYS_STOPSPEED(this) / v0) * PHYS_FRICTION(this))
              = v0 - PHYS_INPUT_TIMELENGTH * PHYS_STOPSPEED(this) * PHYS_FRICTION(this)
            v0 = v + PHYS_INPUT_TIMELENGTH * PHYS_STOPSPEED(this) * PHYS_FRICTION(this)
           and
            v = v0 * (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this))
            v0 = v / (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this))
           These cases would be chosen ONLY if:
            v0 < PHYS_STOPSPEED(this)
            v + PHYS_INPUT_TIMELENGTH * PHYS_STOPSPEED(this) * PHYS_FRICTION(this) < PHYS_STOPSPEED(this)
            v < PHYS_STOPSPEED(this) * (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this))
           and, respectively:
            v0 >= PHYS_STOPSPEED(this)
            v / (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this)) >= PHYS_STOPSPEED(this)
            v >= PHYS_STOPSPEED(this) * (1 - PHYS_INPUT_TIMELENGTH * PHYS_FRICTION(this))
         */
    }
    const float addspeed = wishspeed - this.velocity * wishdir;
    if (addspeed > 0)
    {
        const float accelspeed = min(PHYS_ACCELERATE(this) * PHYS_INPUT_TIMELENGTH * wishspeed, addspeed);
        this.velocity += accelspeed * wishdir;
    }
#ifdef CSQC
    float g = PHYS_GRAVITY(this) * PHYS_ENTGRAVITY(this) * PHYS_INPUT_TIMELENGTH;
    if(autocvar_cl_movement == 3)
    {
        if (!(GAMEPLAYFIX_NOGRAVITYONGROUND))
            this.velocity_z -= g * (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE ? 0.5 : 1);
    }
    if (vdist(this.velocity, >, 0))
        PM_ClientMovement_Move(this);
    if(autocvar_cl_movement == 3)
    {
        if (GAMEPLAYFIX_GRAVITYUNAFFECTEDBYTICRATE)
            if (!IS_ONGROUND(this) || !GAMEPLAYFIX_NOGRAVITYONGROUND)
                this.velocity_z -= g * 0.5;
    }
#endif
}
float racecar_angle (float forward, float down)
Definition at line 619 of file player.qc.
References vectoyaw().
{
    if (forward < 0)
    {
        forward = -forward;
        down = -down;
    }
    float ret = vectoyaw('0 1 0' * down + '1 0 0' * forward);
    float angle_mult = forward / (800 + forward);
    if (ret > 180)
        return ret * angle_mult + 360 * (1 - angle_mult);
    else
        return ret * angle_mult;
}
void SpecialCommand ()
Definition at line 639 of file player.qc.
References CheatImpulse(), and LOG_INFO.
Referenced by PM_check_specialcommand().
{
#ifdef SVQC
    if (!CheatImpulse(CHIMPULSE_GIVE_ALL.impulse))
        LOG_INFO("A hollow voice says \"Plugh\".\n");
#endif
}
Variable Documentation
float jetpack_stopped
Definition at line 576 of file player.qc.
Referenced by CheckPlayerJump().
vector oldmovement
Definition at line 928 of file player.qc.
Referenced by PM_ladder(), and PM_Main().
string specialcommand = "xwxwxsxsxaxdxaxdx1x "
Definition at line 637 of file player.qc.
float specialcommand_pos
Definition at line 638 of file player.qc.
Referenced by PM_check_specialcommand().