Xonotic: lib/warpzone/server.qc File Reference
server.qc File Reference
#include "server.qh"
#include "common.qh"
Macros
#define WarpZone_StoreProjectileData(e_)
Functions
float WarpZone_Projectile_Touch (entity this, entity toucher)
float WarpZone_Teleport (entity wz, entity player, float f0, float f1)
void WarpZone_TeleportPlayer (entity teleporter, entity player, vector to, vector to_angles, vector to_velocity)
void WarpZone_Touch (entity this, entity toucher)
Variables
vector warpzone_oldangles
vector warpzone_oldorigin
vector warpzone_oldvelocity
vector warpzone_save_angles
vector warpzone_save_eangles
vector warpzone_save_eorigin
vector warpzone_save_origin
float warpzone_teleport_finishtime
float warpzone_teleport_time
entity warpzone_teleport_zone
Macro Definition Documentation
#define WarpZone_StoreProjectileData (e_)
Value:
MACRO_BEGIN \
    entity e = e_; \
    e.warpzone_oldorigin = e.origin; \
    e.warpzone_oldvelocity = e.velocity; \
    e.warpzone_oldangles = e.angles; \
    MACRO_END
Definition at line 38 of file server.qc.
Referenced by WarpZone_Projectile_Touch(), and WarpZone_Teleport().
Function Documentation
float WarpZone_Projectile_Touch (entity this, entity toucher)
Definition at line 382 of file server.qc.
References aiment, angles, BITSET_ASSIGN, checkpvs(), cross, CS(), EF_NODEPTHTEST, effects, enemy, entity(), error(), find(), FOREACH_CLIENT, g_projectiles, g_warpzones, IL_EACH, IL_PUSH(), IS_CLIENT, IS_OBSERVER, IS_PLAYER, IS_REAL_CLIENT, killtarget, LOG_INFO, maxs, mins, model, modelscale, nextthink, normalize(), NULL, origin, ping, random(), scale, setorigin(), setSendEntity, setthink, Simple_TeleportPlayer(), solid, SOLID_BSP, SOLID_NOT, spawnflags, spawnfunc(), string_null, target, targetname, Teleport_Find(), time, trace_allsolid, trace_dphitcontents, trace_dphitq3surfaceflags, trace_dphittexturename, trace_dpstartcontents, trace_endpos, trace_ent, trace_fraction, trace_inopen, trace_inwater, trace_plane_dist, trace_plane_normal, trace_startsolid, use, v_angle, vdist, vectoangles(), vector(), vlen(), vtos(), warpzone_angles, WarpZone_Camera_SetUp(), warpzone_cameras_exist, WarpZone_Find(), warpzone_origin, WarpZone_PlaneDist(), WarpZone_PostInitialize_Callback(), WarpZone_Projectile_Touch_ImpactFilter_Callback(), warpzone_save_angles, warpzone_save_eangles, warpzone_save_eorigin, warpzone_save_origin, WarpZone_SetUp(), WarpZone_StoreProjectileData, WarpZone_Teleport(), warpzone_teleport_time, warpzone_teleport_zone, WarpZone_Touch(), WarpZone_TransformVAngles(), warpzone_warpzones_exist, WarpZoneLib_ExactTrigger_Init(), and WarpZoneLib_ExactTrigger_Touch().
 {
     if(toucher.classname == "trigger_warpzone")
         return true;
     // no further impacts if we teleported this frame!
     // this is because even if we did teleport, the engine still may raise
     // touch events for the previous location
     // engine now aborts moves on teleport, so this SHOULD not happen any more
     // but if this is called from TouchAreaGrid of the projectile moving,
     // then this won't do
     if(time == this.warpzone_teleport_time)
         return true;
 #ifdef SVQC
 #ifdef WARPZONELIB_KEEPDEBUG
     // this SEEMS to not happen at the moment, but if it did, it would be more reliable
     {
         float save_dpstartcontents;
         float save_dphitcontents;
         float save_dphitq3surfaceflags;
         string save_dphittexturename;
         float save_allsolid;
         float save_startsolid;
         float save_fraction;
         vector save_endpos;
         vector save_plane_normal;
         float save_plane_dist;
         entity save_ent;
         float save_inopen;
         float save_inwater;
         save_dpstartcontents = trace_dpstartcontents;
         save_dphitcontents = trace_dphitcontents;
         save_dphitq3surfaceflags = trace_dphitq3surfaceflags;
         save_dphittexturename = trace_dphittexturename;
         save_allsolid = trace_allsolid;
         save_startsolid = trace_startsolid;
         save_fraction = trace_fraction;
         save_endpos = trace_endpos;
         save_plane_normal = trace_plane_normal;
         save_plane_dist = trace_plane_dist;
         save_ent = trace_ent;
         save_inopen = trace_inopen;
         save_inwater = trace_inwater;
         float f = WarpZone_CheckProjectileImpact(this);
         if (f) return (f > 0);
         trace_dpstartcontents = save_dpstartcontents;
         trace_dphitcontents = save_dphitcontents;
         trace_dphitq3surfaceflags = save_dphitq3surfaceflags;
         trace_dphittexturename = save_dphittexturename;
         trace_allsolid = save_allsolid;
         trace_startsolid = save_startsolid;
         trace_fraction = save_fraction;
         trace_endpos = save_endpos;
         trace_plane_normal = save_plane_normal;
         trace_plane_dist = save_plane_dist;
         trace_ent = save_ent;
         trace_inopen = save_inopen;
         trace_inwater = save_inwater;
     }
 #endif
     if(WarpZone_Projectile_Touch_ImpactFilter_Callback(this, toucher))
         return true;
 #endif
     return false;
 }
float WarpZone_Teleport (entity wz, entity player, float f0, float f1)
Definition at line 82 of file server.qc.
References EF_NODEPTHTEST, entity(), frametime, IS_NOT_A_CLIENT, IS_PLAYER, IS_VEHICLE, LOG_INFO, max(), MOVE_NOMONSTERS, MOVE_NORMAL, MOVE_WORLDONLY, NULL, setmodel, setorigin(), setSendEntity, setthink, time, trace_endpos, trace_startsolid, vector(), VF_CL_VIEWANGLES, vlen(), WarpZone_RefSys_Add(), WarpZone_StoreProjectileData, WarpZone_TargetPlaneDist(), WarpZone_TeleportPlayer(), WarpZone_TransformAngles(), WarpZone_TransformOrigin(), WarpZone_TransformVAngles(), WarpZone_TransformVelocity(), and WarpZoneLib_MoveOutOfSolid().
Referenced by WarpZone_Projectile_Touch(), and WarpZone_Touch().
 {
     vector o0, a0, v0, o1, a1, v1, o10;
     o0 = player.origin + player.view_ofs;
     v0 = player.velocity;
     a0 = player.angles;
     o10 = o1 = WarpZone_TransformOrigin(wz, o0);
     v1 = WarpZone_TransformVelocity(wz, v0);
     if (!IS_NOT_A_CLIENT(player))
         a1 = WarpZone_TransformVAngles(wz, PHYS_INPUT_ANGLES(player));
     else
         a1 = WarpZone_TransformAngles(wz, a0);
     if(f0 != 0 || f1 != 0)
     {
         // retry last move but behind the warpzone!
         // we must first go back as far as we can, then forward again, to not cause double touch events!
         tracebox(o1 - player.view_ofs + v1 * frametime * f1, player.mins, player.maxs, o1 - player.view_ofs + v1 * frametime * f0, MOVE_WORLDONLY, player);
         {
             entity own;
             own = player.owner;
             player.owner = NULL;
             tracebox(trace_endpos, player.mins, player.maxs, o1 - player.view_ofs + v1 * frametime * f1, MOVE_NORMAL, player); // this should get us through the warpzone
             player.owner = own;
         }
         o1 = trace_endpos + player.view_ofs;
         float d, dv, md;
         md = max(vlen(player.mins), vlen(player.maxs));
         d = WarpZone_TargetPlaneDist(wz, o1);
         dv = WarpZone_TargetPlaneDist(wz, v1);
         if(d < 0)
             o1 = o1 - v1 * (d / dv);
     }
     // put him out of solid
     tracebox(o1 - player.view_ofs, player.mins, player.maxs, o1 - player.view_ofs, MOVE_NOMONSTERS, player);
     if(trace_startsolid)
     {
         setorigin(player, o1 - player.view_ofs);
         if(WarpZoneLib_MoveOutOfSolid(player))
         {
             o1 = player.origin + player.view_ofs;
             setorigin(player, o0 - player.view_ofs);
         }
         else
         {
             LOG_INFO("would have to put player in solid, won't do that");
             setorigin(player, o0 - player.view_ofs);
             return 0;
         }
     }
     // do the teleport
     WarpZone_RefSys_Add(player, wz);
     WarpZone_TeleportPlayer(wz, player, o1 - player.view_ofs, a1, v1);
     WarpZone_StoreProjectileData(player);
     player.warpzone_teleport_time = time;
     player.warpzone_teleport_finishtime = time;
     player.warpzone_teleport_zone = wz;
 #ifdef SVQC
     // prevent further teleports back
     float dt = (o1 - o10) * v1 * (1 / (v1 * v1));
     if(dt < PHYS_INPUT_FRAMETIME)
         player.warpzone_teleport_finishtime += PHYS_INPUT_FRAMETIME - dt;
 #endif
 #ifndef WARPZONE_USE_FIXANGLE
     #ifdef SVQC
     if(IS_VEHICLE(player) && player.owner)
         player = player.owner; // hax
     if(IS_PLAYER(player))
     {
         // instead of fixangle, send the transform to the client for smoother operation
         player.fixangle = false;
         entity ts = new(warpzone_teleported);
         setmodel(ts, MDL_Null);
         setSendEntity(ts, WarpZone_Teleported_Send);
         ts.SendFlags = 0xFFFFFF;
         ts.drawonlytoclient = player;
         setthink(ts, SUB_Remove);
         ts.nextthink = time + 1;
         ts.owner = player;
         ts.enemy = wz;
         ts.effects = EF_NODEPTHTEST;
         ts.angles = wz.warpzone_transform;
     }
     #elif defined(CSQC)
     setproperty(VF_CL_VIEWANGLES, WarpZone_TransformVAngles(wz, getpropertyvec(VF_CL_VIEWANGLES)));
     //if(checkextension("DP_CSQC_ROTATEMOVES"))
         //CL_RotateMoves(wz.warpzone_transform);
     #endif
 #endif
     return 1;
 }
void WarpZone_TeleportPlayer (entity teleporter, entity player, vector to, vector to_angles, vector to_velocity)
Definition at line 45 of file server.qc.
References angles, BITCLR_ASSIGN, BITXOR_ASSIGN, bot_aim_reset(), EF_TELEPORT_BIT, entity(), FL_ONGROUND, IS_BOT_CLIENT, IS_PLAYER, setorigin(), time, to, and WarpZone_PostTeleportPlayer_Callback().
Referenced by WarpZone_Teleport().
 {
 #ifdef SVQC
     player.lastteleport_origin = player.origin;
     player.lastteleporttime = time;
 #endif
     setorigin(player, to); // NOTE: this also aborts the move, when this is called by touch
     player.angles = to_angles;
 #ifdef SVQC
     player.oldorigin = to; // for DP's unsticking
     player.fixangle = true;
     if (IS_BOT_CLIENT(player))
     {
         // FIXME find a way to smooth view's angles change for bots too
         player.v_angle = player.angles;
         bot_aim_reset(player);
     }
 #endif
     player.velocity = to_velocity;
     BITXOR_ASSIGN(player.effects, EF_TELEPORT_BIT);
     if(IS_PLAYER(player))
         BITCLR_ASSIGN(player.flags, FL_ONGROUND);
     WarpZone_PostTeleportPlayer_Callback(player);
 }
void WarpZone_Touch (entity this, entity toucher)
Definition at line 184 of file server.qc.
References BIT, BITSET_ASSIGN, bound(), enemy, entity(), frametime, IS_NOT_A_CLIENT, LOG_INFO, LOG_TRACE, max(), maxs, mins, modelindex, MOVETYPE_FOLLOW, MOVETYPE_NONE, origin, scale, sendflags, setorigin(), SUB_UseTargets_SkipTargets(), time, to, vector(), vlen(), vtos(), warpzone_angles, warpzone_fadeend, warpzone_fadestart, WarpZone_Find(), warpzone_isboxy, warpzone_origin, WarpZone_PlaneDist(), warpzone_targetangles, warpzone_targetorigin, WarpZone_Teleport(), WarpZoneLib_ExactTrigger_Touch(), WriteByte(), WriteCoord(), and WriteShort().
Referenced by WarpZone_Fade_PreDraw(), and WarpZone_Projectile_Touch().
 {
     if(toucher.classname == "trigger_warpzone")
         return;
     if(time <= toucher.warpzone_teleport_finishtime) // already teleported this frame
         return;
     // FIXME needs a better check to know what is safe to teleport and what not
     if(toucher.move_movetype == MOVETYPE_NONE || toucher.move_movetype == MOVETYPE_FOLLOW || toucher.tag_entity)
         return;
     if(WarpZoneLib_ExactTrigger_Touch(this, toucher))
         return;
     if(WarpZone_PlaneDist(this, toucher.origin + toucher.view_ofs) >= 0) // wrong side of the trigger_warpzone (don't teleport yet)
         return;
     float f;
     // number of frames we need to go back:
     //   dist = 16*sqrt(2) qu
     //   dist ~ 24 qu
     //   24 qu = v*t
     //   24 qu = v*frametime*n
     //       n = 24 qu/(v*frametime)
     // for clients go only one frame though, may be too irritating otherwise
     // but max 0.25 sec = 0.25/frametime frames
     //       24/(0.25/frametime)
     //       96*frametime
     float d;
     d = 24 + max(vlen(toucher.mins), vlen(toucher.maxs));
     if(IS_NOT_A_CLIENT(toucher))
         f = -d / bound(frametime * d * 1, frametime * vlen(toucher.velocity), d);
     else
         f = -1;
     if(WarpZone_Teleport(this, toucher, f, 0))
     {
 #ifdef SVQC
         SUB_UseTargets_SkipTargets(this, toucher, toucher, BIT(1) | BIT(3)); // use toucher too?
         SUB_UseTargets_SkipTargets(this.enemy, toucher, toucher, BIT(1) | BIT(2)); // use toucher too?
 #endif
     }
     else
     {
         LOG_TRACE("WARPZONE FAIL AHAHAHAHAH))");
     }
 }
Variable Documentation
vector warpzone_oldangles
Definition at line 33 of file server.qc.
vector warpzone_oldorigin
Definition at line 33 of file server.qc.
vector warpzone_oldvelocity
Definition at line 33 of file server.qc.
vector warpzone_save_angles
Definition at line 28 of file server.qc.
Referenced by WarpZone_Projectile_Touch().
vector warpzone_save_eangles
Definition at line 30 of file server.qc.
Referenced by WarpZone_Projectile_Touch().
vector warpzone_save_eorigin
Definition at line 29 of file server.qc.
Referenced by WarpZone_Projectile_Touch().
vector warpzone_save_origin
Definition at line 27 of file server.qc.
Referenced by WarpZone_Projectile_Touch().
float warpzone_teleport_finishtime
Definition at line 35 of file server.qc.
float warpzone_teleport_time
Definition at line 34 of file server.qc.
Referenced by WarpZone_Projectile_Touch().
entity warpzone_teleport_zone
Definition at line 36 of file server.qc.
Referenced by WarpZone_Projectile_Touch().