Xonotic: XonoticInputBox Class Reference
XonoticInputBox Class Reference
Public Member Functions
virtual void configureInputBox ()
virtual void configureLabel ()
virtual void configureXonoticInputBox ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void enterText ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void loadCvars ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void recalcPositionWithText ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void saveCvars ()
virtual void setText ()
virtual void showNotify ()
virtual void toString ()
void (entity, entity) onChange
void (entity, entity) onEnter
Public Attributes
float align = 0.5
float allowColors = 0
float allowCut = 0
float allowFocusSound = 1
float allowWrap = 0
float alpha = SKINALPHA_TEXT
entity applyButton = NULL
vector cb_color = SKINCOLOR_CLEARBUTTON_N
vector cb_colorC = SKINCOLOR_CLEARBUTTON_C
vector cb_colorF = SKINCOLOR_CLEARBUTTON_F
float cb_focused = 0
float cb_offset = SKINOFFSET_CLEARBUTTON
float cb_pressed = 0
string cb_src = SKINGFX_CLEARBUTTON
float cb_width = 0
entity clearButton = NULL
vector color = SKINCOLOR_INPUTBOX_N
vector colorF = SKINCOLOR_INPUTBOX_F
vector colorL = SKINCOLOR_TEXT
float condenseFactor = 1
string currentText = string_null
float cursorPos = 0
string cvarName = string_null
float disabled = 0
float disabledAlpha = 0.3
vector dragScrollPos = '0 0 0'
float dragScrollTimer = 0
float editColorCodes = 1
float enableClearButton = 1
float focusable = 1
float focused = 0
float fontSize = SKINFONTSIZE_NORMAL
string forbiddenCharacters = ""
string image = SKINGFX_INPUTBOX
float isBold = 0
float keepspaceLeft = 0
float keepspaceRight = 0
float lastChangeTime = 0
float marginLeft = SKINMARGIN_INPUTBOX_CHARS
float marginRight = SKINMARGIN_INPUTBOX_CHARS
float maxLength = 255
entity onChangeEntity = NULL
entity onEnterEntity = NULL
vector origin = '0 0 0'
float overrideCondenseFactor = 0
vector overrideRealOrigin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float pressed = 0
vector realFontSize = '0 0 0'
vector realOrigin = '0 0 0'
float recalcPos = 0
float saveImmediately = 0
float scrollPos = 0
float sendCvars = 0
vector size = '0 0 0'
string src = string_null
string text = string_null
entity textEntity = NULL
string tooltip = string_null
Detailed Description
Definition at line 4 of file inputbox.qh.
Member Function Documentation
virtual void InputBox::configureInputBox () virtual inherited
virtual void Label::configureLabel () virtual inherited
virtual void XonoticInputBox::configureXonoticInputBox () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void InputBox::draw () virtual inherited
Reimplemented from Label.
virtual void InputBox::enterText () virtual inherited
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void XonoticInputBox::focusLeave () virtual
Reimplemented from Item.
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void XonoticInputBox::keyDown () virtual
Reimplemented from InputBox.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void XonoticInputBox::loadCvars () virtual
virtual void InputBox::mouseDrag () virtual inherited
Reimplemented from Item.
virtual void InputBox::mouseMove () virtual inherited
Reimplemented from Item.
virtual void InputBox::mousePress () virtual inherited
Reimplemented from Item.
virtual void InputBox::mouseRelease () virtual inherited
Reimplemented from Item.
virtual void Label::recalcPositionWithText () virtual inherited
Reimplemented in BorderImage.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void InputBox::resizeNotify () virtual inherited
Reimplemented from Label.
virtual void XonoticInputBox::saveCvars () virtual
virtual void XonoticInputBox::setText () virtual
Reimplemented from InputBox.
virtual void InputBox::showNotify () virtual inherited
Reimplemented from Item.
virtual void Label::toString () virtual inherited
Reimplemented from Item.
Reimplemented in Slider, and CheckBox.
XonoticInputBox::void (entity , entity)
XonoticInputBox::void (entity , entity)
Member Data Documentation
float Label::align = 0.5 inherited
Definition at line 15 of file label.qh.
float Label::allowColors = 0 inherited
Definition at line 17 of file label.qh.
float Label::allowCut = 0 inherited
Definition at line 16 of file label.qh.
float InputBox::allowFocusSound = 1 inherited
Definition at line 23 of file inputbox.qh.
float Label::allowWrap = 0 inherited
Definition at line 29 of file label.qh.
float XonoticInputBox::alpha = SKINALPHA_TEXT
Definition at line 20 of file inputbox.qh.
entity InputBox::applyButton = NULL inherited
Definition at line 34 of file inputbox.qh.
vector XonoticInputBox::cb_color = SKINCOLOR_CLEARBUTTON_N
Definition at line 25 of file inputbox.qh.
vector XonoticInputBox::cb_colorC = SKINCOLOR_CLEARBUTTON_C
Definition at line 27 of file inputbox.qh.
vector XonoticInputBox::cb_colorF = SKINCOLOR_CLEARBUTTON_F
Definition at line 26 of file inputbox.qh.
float InputBox::cb_focused = 0 inherited
Definition at line 40 of file inputbox.qh.
float XonoticInputBox::cb_offset = SKINOFFSET_CLEARBUTTON
Definition at line 23 of file inputbox.qh.
float InputBox::cb_pressed = 0 inherited
Definition at line 39 of file inputbox.qh.
string XonoticInputBox::cb_src = SKINGFX_CLEARBUTTON
Definition at line 24 of file inputbox.qh.
float InputBox::cb_width = 0 inherited
Definition at line 38 of file inputbox.qh.
entity InputBox::clearButton = NULL inherited
Definition at line 37 of file inputbox.qh.
vector XonoticInputBox::color = SKINCOLOR_INPUTBOX_N
Definition at line 17 of file inputbox.qh.
vector XonoticInputBox::colorF = SKINCOLOR_INPUTBOX_F
Definition at line 18 of file inputbox.qh.
vector Label::colorL = SKINCOLOR_TEXT inherited
Definition at line 25 of file label.qh.
float Label::condenseFactor = 1 inherited
Definition at line 31 of file label.qh.
string Label::currentText = string_null inherited
Definition at line 13 of file label.qh.
float InputBox::cursorPos = 0 inherited
Definition at line 19 of file inputbox.qh.
string XonoticInputBox::cvarName = string_null
Definition at line 29 of file inputbox.qh.
float InputBox::disabled = 0 inherited
Definition at line 24 of file inputbox.qh.
float Label::disabledAlpha = 0.3 inherited
Definition at line 27 of file label.qh.
vector InputBox::dragScrollPos = '0 0 0' inherited
Definition at line 27 of file inputbox.qh.
float InputBox::dragScrollTimer = 0 inherited
Definition at line 26 of file inputbox.qh.
float InputBox::editColorCodes = 1 inherited
Definition at line 29 of file inputbox.qh.
float InputBox::enableClearButton = 1 inherited
Definition at line 36 of file inputbox.qh.
float InputBox::focusable = 1 inherited
Definition at line 22 of file inputbox.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
float XonoticInputBox::fontSize = SKINFONTSIZE_NORMAL
Definition at line 9 of file inputbox.qh.
string InputBox::forbiddenCharacters = "" inherited
Definition at line 30 of file inputbox.qh.
string XonoticInputBox::image = SKINGFX_INPUTBOX
Definition at line 10 of file inputbox.qh.
float Label::isBold = 0 inherited
Definition at line 11 of file label.qh.
float Label::keepspaceLeft = 0 inherited
Definition at line 18 of file label.qh.
float Label::keepspaceRight = 0 inherited
Definition at line 19 of file label.qh.
float InputBox::lastChangeTime = 0 inherited
Definition at line 25 of file inputbox.qh.
float XonoticInputBox::marginLeft = SKINMARGIN_INPUTBOX_CHARS
Definition at line 15 of file inputbox.qh.
float XonoticInputBox::marginRight = SKINMARGIN_INPUTBOX_CHARS
Definition at line 16 of file inputbox.qh.
float InputBox::maxLength = 255 inherited
Definition at line 33 of file inputbox.qh.
entity XonoticInputBox::onChangeEntity = NULL
Definition at line 12 of file inputbox.qh.
entity XonoticInputBox::onEnterEntity = NULL
Definition at line 14 of file inputbox.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
float Label::overrideCondenseFactor = 0 inherited
Definition at line 33 of file label.qh.
vector Label::overrideRealOrigin = '0 0 0' inherited
Definition at line 32 of file label.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float InputBox::pressed = 0 inherited
Definition at line 28 of file inputbox.qh.
vector Label::realFontSize = '0 0 0' inherited
Definition at line 22 of file label.qh.
vector Label::realOrigin = '0 0 0' inherited
Definition at line 23 of file label.qh.
float Label::recalcPos = 0 inherited
Definition at line 30 of file label.qh.
float XonoticInputBox::saveImmediately = 0
Definition at line 34 of file inputbox.qh.
float InputBox::scrollPos = 0 inherited
Definition at line 20 of file inputbox.qh.
float XonoticInputBox::sendCvars = 0
Definition at line 32 of file inputbox.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
string InputBox::src = string_null inherited
Definition at line 17 of file inputbox.qh.
string Label::text = string_null inherited
Definition at line 12 of file label.qh.
entity Label::textEntity = NULL inherited
Definition at line 28 of file label.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
The documentation for this class was generated from the following file:
menu/xonotic/inputbox.qh