Xonotic: client/hud/panel/centerprint.qh File Reference
centerprint.qh File Reference
#include "../panel.qh"
Functions
void centerprint_Add (int new_id, string strMessage, float duration, int countdown_num)
void centerprint_AddStandard (string strMessage)
void centerprint_Kill (int id)
void centerprint_KillAll ()
Variables
bool autocvar_hud_panel_centerprint
float autocvar_hud_panel_centerprint_align
bool autocvar_hud_panel_centerprint_dynamichud = true
float autocvar_hud_panel_centerprint_fade_in = 0.2
float autocvar_hud_panel_centerprint_fade_minfontsize = 0
float autocvar_hud_panel_centerprint_fade_out = 0.5
float autocvar_hud_panel_centerprint_fade_subsequent = 1
float autocvar_hud_panel_centerprint_fade_subsequent_minfontsize = 0.75
float autocvar_hud_panel_centerprint_fade_subsequent_passone = 3
float autocvar_hud_panel_centerprint_fade_subsequent_passone_minalpha = 0.5
float autocvar_hud_panel_centerprint_fade_subsequent_passtwo = 10
float autocvar_hud_panel_centerprint_fade_subsequent_passtwo_minalpha = 0.5
bool autocvar_hud_panel_centerprint_flip
float autocvar_hud_panel_centerprint_fontscale
float autocvar_hud_panel_centerprint_fontscale_bold = 1.4
float autocvar_hud_panel_centerprint_time
Function Documentation
void centerprint_Add (int new_id, string strMessage, float duration, int countdown_num)
Definition at line 46 of file centerprint.qc.
References autocvar_hud_panel_centerprint_fade_out, autocvar_hud_panel_centerprint_time, BOLD_OPERATOR, centerprint_bold, centerprint_countdown_num, centerprint_expire_time, CENTERPRINT_MAX_MSGS, centerprint_messages, centerprint_msgID, centerprint_showing, centerprint_time, cpm_index, max(), min(), strcpy, strlen(), substring(), and TC.
Referenced by centerprint_AddStandard(), centerprint_Kill(), HUD_CenterPrint(), and Local_Notification_sprintf().
 {
     TC(int, new_id); TC(int, countdown_num);
     //LOG_INFOF("centerprint_Add: ^2id: %d ^3dur: %d ^5countdown: %d\n'%s'", new_id, duration, countdown_num, strreplace("\n", "^7\\n^7", strMessage));
     int i, j;
     if(strMessage == "" && new_id == 0)
         return;
     // strip BOLD_OPERATOR
     bool is_bold = (substring(strMessage, 0, 5) == BOLD_OPERATOR);
     if (is_bold)
         strMessage = substring(strMessage, 5, -1);
     // strip trailing newlines
     j = strlen(strMessage) - 1;
     while(substring(strMessage, j, 1) == "\n" && j >= 0)
         --j;
     if (j < strlen(strMessage) - 1)
         strMessage = substring(strMessage, 0, j + 1);
     if(strMessage == "" && new_id == 0)
         return;
     // strip leading newlines
     j = 0;
     while(substring(strMessage, j, 1) == "\n" && j < strlen(strMessage))
         ++j;
     if (j > 0)
         strMessage = substring(strMessage, j, strlen(strMessage) - j);
     if(strMessage == "" && new_id == 0)
         return;
     if (!centerprint_showing)
         centerprint_showing = true;
     for (i=0, j=cpm_index; i<CENTERPRINT_MAX_MSGS; ++i, ++j)
     {
         if (j == CENTERPRINT_MAX_MSGS)
             j = 0;
         if (new_id && new_id == centerprint_msgID[j])
         {
             if (strMessage == "" && centerprint_messages[j] != "" && centerprint_countdown_num[j] == 0)
             {
                 // fade out the current msg (duration and countdown_num are ignored)
                 centerprint_time[j] = min(5, autocvar_hud_panel_centerprint_fade_out);
                 centerprint_expire_time[j] = -1; // don't use the variable time here!
                 return;
             }
             break; // found a msg with the same id, at position j
         }
     }
     if (i == CENTERPRINT_MAX_MSGS)
     {
         // a msg with the same id was not found, add the msg at the next position
         --cpm_index;
         if (cpm_index == -1)
             cpm_index = CENTERPRINT_MAX_MSGS - 1;
         j = cpm_index;
     }
     strcpy(centerprint_messages[j], strMessage);
     centerprint_bold[j] = is_bold;
     centerprint_msgID[j] = new_id;
     if (duration < 0)
     {
         centerprint_time[j] = -1;
         centerprint_expire_time[j] = -1; // don't use the variable time here!
     }
     else
     {
         if(duration == 0)
             duration = max(1, autocvar_hud_panel_centerprint_time);
         centerprint_time[j] = duration;
         centerprint_expire_time[j] = -1; // don't use the variable time here!
     }
     centerprint_countdown_num[j] = countdown_num;
 }
void centerprint_AddStandard (string strMessage)
Definition at line 132 of file centerprint.qc.
References autocvar_hud_panel_centerprint_time, and centerprint_Add().
Referenced by CSQC_Parse_CenterPrint(), HUD_CenterPrint(), and LocalCommand_localprint().
 {
     centerprint_Add(0, strMessage, autocvar_hud_panel_centerprint_time, 0);
 }
void centerprint_Kill (int id)
Definition at line 126 of file centerprint.qc.
References centerprint_Add(), and TC.
Referenced by Announcer_Gamestart(), and Local_Notification_WOVA().
 {
     TC(int, id);
     centerprint_Add(id, "", 0, 0);
 }
void centerprint_KillAll ()
Definition at line 137 of file centerprint.qc.
References centerprint_bold, centerprint_expire_time, CENTERPRINT_MAX_MSGS, centerprint_messages, centerprint_msgID, centerprint_time, and strfree.
Referenced by Destroy_All_Notifications(), HUD_CenterPrint(), and Local_Notification_WOVA().
 {
     for (int i=0; i<CENTERPRINT_MAX_MSGS; ++i)
     {
         centerprint_expire_time[i] = 0;
         centerprint_time[i] = 1;
         centerprint_msgID[i] = 0;
         centerprint_bold[i] = false;
         strfree(centerprint_messages[i]);
     }
 }
Variable Documentation
bool autocvar_hud_panel_centerprint
Definition at line 4 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_align
Definition at line 5 of file centerprint.qh.
Referenced by HUD_CenterPrint().
bool autocvar_hud_panel_centerprint_dynamichud = true
Definition at line 18 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_in = 0.2
Definition at line 6 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_minfontsize = 0
Definition at line 14 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_out = 0.5
Definition at line 7 of file centerprint.qh.
Referenced by centerprint_Add(), and HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent = 1
Definition at line 8 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent_minfontsize = 0.75
Definition at line 13 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent_passone = 3
Definition at line 9 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent_passone_minalpha = 0.5
Definition at line 10 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent_passtwo = 10
Definition at line 11 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fade_subsequent_passtwo_minalpha = 0.5
Definition at line 12 of file centerprint.qh.
Referenced by HUD_CenterPrint().
bool autocvar_hud_panel_centerprint_flip
Definition at line 15 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fontscale
Definition at line 16 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_fontscale_bold = 1.4
Definition at line 17 of file centerprint.qh.
Referenced by HUD_CenterPrint().
float autocvar_hud_panel_centerprint_time
Definition at line 19 of file centerprint.qh.
Referenced by centerprint_Add(), and centerprint_AddStandard().