Xonotic: client/hud/panel/timer.qh File Reference
timer.qh File Reference
#include "../panel.qh"
Functions
vector HUD_Timer_Color (float timeleft)
float HUD_Timer_TimeElapsed (float curtime, float starttime)
float HUD_Timer_TimeLeft (float curtime, float starttime, float timelimit)
Variables
bool autocvar_hud_panel_timer
bool autocvar_hud_panel_timer_dynamichud = true
bool autocvar_hud_panel_timer_increment
int autocvar_hud_panel_timer_secondary = 1
bool autocvar_hud_panel_timer_unbound
Function Documentation
HUD_Timer_Color()
vector HUD_Timer_Color (float timeleft)
Definition at line 13 of file timer.qc.
Referenced by HUD_Timer().
 {
     if(timeleft <= 60)
         return '1 0 0'; // red
     else if(timeleft <= 300)
         return '1 1 0'; // yellow
     else
         return '1 1 1'; // white
 }
HUD_Timer_TimeElapsed()
float HUD_Timer_TimeElapsed (float curtime, float starttime)
Definition at line 23 of file timer.qc.
References autocvar_hud_panel_timer_unbound, floor(), max(), and starttime.
Referenced by HUD_Timer().
 {
     float time_elapsed = curtime - starttime;
     if (!autocvar_hud_panel_timer_unbound)
         time_elapsed = max(0, time_elapsed);
     return floor(time_elapsed);
 }
HUD_Timer_TimeLeft()
float HUD_Timer_TimeLeft (float curtime, float starttime, float timelimit)
Definition at line 31 of file timer.qc.
References autocvar_hud_panel_timer_unbound, bound(), and ceil().
Referenced by HUD_Timer().
 {
     float timeleft = timelimit + starttime - curtime;
     if (!autocvar_hud_panel_timer_unbound)
         timeleft = bound(0, timeleft, timelimit);
     return ceil(timeleft);
 }
Variable Documentation
autocvar_hud_panel_timer
bool autocvar_hud_panel_timer
Definition at line 4 of file timer.qh.
Referenced by HUD_Timer().
autocvar_hud_panel_timer_dynamichud
bool autocvar_hud_panel_timer_dynamichud = true
Definition at line 5 of file timer.qh.
Referenced by HUD_Timer().
autocvar_hud_panel_timer_increment
bool autocvar_hud_panel_timer_increment
Definition at line 6 of file timer.qh.
Referenced by HUD_Timer().
autocvar_hud_panel_timer_secondary
int autocvar_hud_panel_timer_secondary = 1
Definition at line 7 of file timer.qh.
Referenced by HUD_Timer().
autocvar_hud_panel_timer_unbound
bool autocvar_hud_panel_timer_unbound
Definition at line 8 of file timer.qh.
Referenced by HUD_Timer_TimeElapsed(), and HUD_Timer_TimeLeft().