Xonotic: server/world.qc File Reference
world.qc File Reference
#include "world.qh"
#include <common/constants.qh>
#include <common/deathtypes/all.qh>
#include <common/gamemodes/_mod.qh>
#include <common/gamemodes/sv_rules.qh>
#include <common/items/_mod.qh>
#include <common/mapinfo.qh>
#include <common/mapobjects/target/music.qh>
#include <common/mapobjects/trigger/hurt.qh>
#include <common/mapobjects/trigger/secret.qh>
#include <common/mapobjects/triggers.qh>
#include <common/monsters/_mod.qh>
#include <common/monsters/sv_monsters.qh>
#include <common/net_linked.qh>
#include <common/notifications/all.qh>
#include <common/physics/player.qh>
#include <common/playerstats.qh>
#include <common/state.qh>
#include <common/stats.qh>
#include <common/teams.qh>
#include <common/util.qh>
#include <common/vehicles/all.qh>
#include <common/weapons/_all.qh>
#include <server/anticheat.qh>
#include <server/antilag.qh>
#include <server/bot/api.qh>
#include <server/campaign.qh>
#include <server/cheats.qh>
#include <server/client.qh>
#include <server/command/common.qh>
#include <server/command/getreplies.qh>
#include <server/command/sv_cmd.qh>
#include <server/command/vote.qh>
#include <server/damage.qh>
#include <server/gamelog.qh>
#include <server/hook.qh>
#include <server/intermission.qh>
#include <server/ipban.qh>
#include <server/items/items.qh>
#include <server/main.qh>
#include <server/mapvoting.qh>
#include <server/mutators/_mod.qh>
#include <server/race.qh>
#include <server/scores.qh>
#include <server/scores_rules.qh>
#include <server/spawnpoints.qh>
#include <server/teamplay.qh>
#include <server/weapons/common.qh>
#include <server/weapons/weaponstats.qh>
Macros
#define BADCVAR(p) if(k == p) continue
#define BADPREFIX(p) if(substring(k, 0, strlen(p)) == p) continue
#define BADPRESUFFIX(p, s) if(substring(k, 0, strlen(p)) == p && substring(k, -strlen(s), -1) == s) continue
#define BADVALUE(p, val) if (k == p && v == val) continue
#define X(match)
Functions
void __init_dedicated_server_shutdown ()
void AddWinners (.float field, float value)
void CheckRules_World ()
void ClearWinners ()
void cvar_changes_init ()
void droptofloor (entity this)
void DropToFloor_Handler (entity this)
void DumpStats (float final)
void EndFrame ()
void GameplayMode_DelayedInit (entity this)
float GetWinningCode (float fraglimitreached, float equality)
void GotoFirstMap (entity this)
void InitGameplayMode ()
void InitializeEntitiesRun ()
void InitializeEntity (entity e, void(entity this) func, int order)
void InitiateOvertime ()
float InitiateSuddenDeath ()
bool MoveToRandomLocationWithinBounds (entity e, vector boundmin, vector boundmax, float goodcontents, float badcontents, float badsurfaceflags, int attempts, float maxaboveground, float minviewdistance)
float MoveToRandomMapLocation (entity e, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
void NextLevel ()
void Physics_Frame ()
void PingPLReport_Spawn ()
void PingPLReport_Think (entity this)
bool RandomSeed_Send (entity this, entity to, int sf)
void RandomSeed_Spawn ()
void RandomSeed_Think (entity this)
void readlevelcvars ()
void readplayerstartcvars ()
float RedirectionThink ()
void RestoreGame ()
void RunThink (entity this)
void SetDefaultAlpha ()
void SetWinners (.float field, float value)
void Shutdown ()
spawnfunc (__init_dedicated_server)
spawnfunc (worldspawn)
spawnfunc (light)
STATIC_INIT_EARLY (maxclients)
void systems_update ()
float want_weapon (entity weaponinfo, float allguns)
void weaponarena_available_all_update (entity this)
void weaponarena_available_devall_update (entity this)
void weaponarena_available_most_update (entity this)
WepSet weapons_all ()
WepSet weapons_devall ()
WepSet weapons_most ()
WepSet weapons_start ()
Weapons the player normally starts with outside weapon arena.
float WinningCondition_RanOutOfSpawns ()
float WinningCondition_Scores (float limit, float leadlimit)
Variables
bool autocvar_sv_freezenonclients
bool autocvar_sv_gameplayfix_multiplethinksperframe = true
int fragsleft_last
float latency_cnt
float latency_sum
const float LATENCY_THINKRATE = 10
float latency_time
entity pingplreport
entity randomseed
float redirection_nextthink
float redirection_timeout
const float SPAWNFLAG_NO_WAYPOINTS_FOR_ITEMS = 1
bool world_already_spawned
Macro Definition Documentation
BADCVAR
#define BADCVAR (p) if(k == p) continue
Referenced by cvar_changes_init().
BADPREFIX
#define BADPREFIX (p) if(substring(k, 0, strlen(p)) == p) continue
Referenced by cvar_changes_init().
BADPRESUFFIX
#define BADPRESUFFIX (p, s) if(substring(k, 0, strlen(p)) == p && substring(k, -strlen(s), -1) == s) continue
Referenced by cvar_changes_init().
BADVALUE
#define BADVALUE (p, val) if (k == p && v == val) continue
Referenced by cvar_changes_init().
X
#define X (match)
Value:
MACRO_BEGIN \
            int fd = search_begin(match, true, false); \
            if (fd >= 0) \
            { \
                for (int i = 0, j = search_getsize(fd); i < j; ++i) \
                { \
                    s = cons(s, search_getfilename(fd, i)); \
                } \
                search_end(fd); \
            } \
        MACRO_END
Referenced by spawnfunc().
Function Documentation
__init_dedicated_server_shutdown()
void __init_dedicated_server_shutdown ()
Definition at line 619 of file world.qc.
References MapInfo_Shutdown().
Referenced by Shutdown().
{
     MapInfo_Shutdown();
 }
AddWinners()
void AddWinners (.float field, float value)
Definition at line 1391 of file world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by WinningCondition_RanOutOfSpawns().
 {
     FOREACH_CLIENT(IS_PLAYER(it), {
         if(it.(field) == value)
             it.winning = 1;
     });
 }
CheckRules_World()
void CheckRules_World ()
Definition at line 1571 of file world.qc.
References bprint(), checkrules_overtimesadded, checkrules_suddendeathend, checkrules_suddendeathwarning, CheckRules_World(), ClearWinners(), FOREACH_CLIENT, g_race, g_race_qualifying, GameRules_scoring_add, InitiateOvertime(), InitiateSuddenDeath(), intermission_running, IS_PLAYER, M_ARGV, MapVote_Start(), MapVote_Think(), MUTATOR_CALLHOOK, NextLevel(), NULL, player_count, ReadyRestart(), SetDefaultAlpha(), time, VoteThink(), warmup_stage, WINNING_NEVER, WINNING_STARTSUDDENDEATHOVERTIME, WINNING_YES, WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
Referenced by CheckRules_World(), and StartFrame().
 {
     VoteThink();
     MapVote_Think();
     SetDefaultAlpha();
     if (intermission_running) // someone else quit the game already
     {
         if(player_count == 0) // Nobody there? Then let's go to the next map
             MapVote_Start();
             // this will actually check the player count in the next frame
             // again, but this shouldn't hurt
         return;
     }
     float timelimit = autocvar_timelimit * 60;
     float fraglimit = autocvar_fraglimit;
     float leadlimit = autocvar_leadlimit;
     if (leadlimit < 0) leadlimit = 0;
     if(warmup_stage || time <= game_starttime) // NOTE: this is <= to prevent problems in the very tic where the game starts
     {
         if(timelimit > 0)
             timelimit = 0; // timelimit is not made for warmup
         if(fraglimit > 0)
             fraglimit = 0; // no fraglimit for now
         leadlimit = 0; // no leadlimit for now
     }
     if(timelimit > 0)
     {
         timelimit += game_starttime;
     }
     else if (timelimit < 0)
     {
         // endmatch
         NextLevel();
         return;
     }
     float wantovertime;
     wantovertime = 0;
     if(checkrules_suddendeathend)
     {
         if(!checkrules_suddendeathwarning)
         {
             checkrules_suddendeathwarning = true;
             if(g_race && !g_race_qualifying)
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_RACE_FINISHLAP);
             else
                 Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_OVERTIME_FRAG);
         }
     }
     else
     {
         if (timelimit && time >= timelimit)
         {
             if(g_race && (g_race_qualifying == 2) && timelimit > 0)
             {
                 float totalplayers;
                 float playerswithlaps;
                 float readyplayers;
                 totalplayers = playerswithlaps = readyplayers = 0;
                 FOREACH_CLIENT(IS_PLAYER(it), {
                     ++totalplayers;
                     if(GameRules_scoring_add(it, RACE_FASTEST, 0))
                         ++playerswithlaps;
                     if(it.ready)
                         ++readyplayers;
                 });
                 // at least 2 of the players have completed a lap: start the RACE
                 // otherwise, the players should end the qualifying on their own
                 if(readyplayers || playerswithlaps >= 2)
                 {
                     checkrules_suddendeathend = 0;
                     ReadyRestart(); // go to race
                     return;
                 }
                 else
                     wantovertime |= InitiateSuddenDeath();
             }
             else
                 wantovertime |= InitiateSuddenDeath();
         }
     }
     if (checkrules_suddendeathend && time >= checkrules_suddendeathend)
     {
         NextLevel();
         return;
     }
     int checkrules_status = WinningCondition_RanOutOfSpawns();
     if(checkrules_status == WINNING_YES)
         bprint("Hey! Someone ran out of spawns!\n");
     else if(MUTATOR_CALLHOOK(CheckRules_World, checkrules_status, timelimit, fraglimit))
         checkrules_status = M_ARGV(0, float);
     else
         checkrules_status = WinningCondition_Scores(fraglimit, leadlimit);
     if(checkrules_status == WINNING_STARTSUDDENDEATHOVERTIME)
     {
         checkrules_status = WINNING_NEVER;
         checkrules_overtimesadded = -1;
         wantovertime |= InitiateSuddenDeath();
     }
     if(checkrules_status == WINNING_NEVER)
         // equality cases! Nobody wins if the overtime ends in a draw.
         ClearWinners();
     if(wantovertime)
     {
         if(checkrules_status == WINNING_NEVER)
             InitiateOvertime();
         else
             checkrules_status = WINNING_YES;
     }
     if(checkrules_suddendeathend)
         if(checkrules_status != WINNING_NEVER || time >= checkrules_suddendeathend)
             checkrules_status = WINNING_YES;
     if(checkrules_status == WINNING_YES)
     {
         //print("WINNING\n");
         NextLevel();
     }
 }
ClearWinners()
void ClearWinners ()
Definition at line 1400 of file world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by CheckRules_World(), LMS_NewPlayerLives(), spawnfunc(), WinningCondition_Invasion(), WinningCondition_LMS(), WinningCondition_RanOutOfSpawns(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), { it.winning = 0; });
 }
cvar_changes_init()
void cvar_changes_init ()
Definition at line 149 of file world.qc.
References BADCVAR, BADPREFIX, BADPRESUFFIX, BADVALUE, buf_create, cvar_changes, cvar_defstring(), cvar_purechanges, cvar_purechanges_count, cvar_string(), strcat(), strfree, strlen(), strzone(), and v.
Referenced by spawnfunc().
 {
     float h;
     string k, v, d;
     float n, i, adding, pureadding;
     strfree(cvar_changes);
     strfree(cvar_purechanges);
     cvar_purechanges_count = 0;
     h = buf_create();
     buf_cvarlist(h, "", "_"); // exclude all _ cvars as they are temporary
     n = buf_getsize(h);
     adding = true;
     pureadding = true;
     for(i = 0; i < n; ++i)
     {
         k = bufstr_get(h, i);
 #define BADPREFIX(p) if(substring(k, 0, strlen(p)) == p) continue
 #define BADPRESUFFIX(p,s) if(substring(k, 0, strlen(p)) == p && substring(k, -strlen(s), -1) == s) continue
 #define BADCVAR(p) if(k == p) continue
 #define BADVALUE(p, val) if (k == p && v == val) continue
         // general excludes and namespaces for server admin used cvars
         BADPREFIX("help_"); // PN's server has this listed as changed, let's not rat him out for THAT
         // internal
         BADPREFIX("csqc_");
         BADPREFIX("cvar_check_");
         BADCVAR("gamecfg");
         BADCVAR("g_configversion");
         BADCVAR("halflifebsp");
         BADCVAR("sv_mapformat_is_quake2");
         BADCVAR("sv_mapformat_is_quake3");
         BADPREFIX("sv_world");
         // client
         BADPREFIX("chase_");
         BADPREFIX("cl_");
         BADPREFIX("con_");
         BADPREFIX("scoreboard_");
         BADPREFIX("g_campaign");
         BADPREFIX("g_waypointsprite_");
         BADPREFIX("gl_");
         BADPREFIX("joy");
         BADPREFIX("hud_");
         BADPREFIX("m_");
         BADPREFIX("menu_");
         BADPREFIX("net_slist_");
         BADPREFIX("r_");
         BADPREFIX("sbar_");
         BADPREFIX("scr_");
         BADPREFIX("snd_");
         BADPREFIX("show");
         BADPREFIX("sensitivity");
         BADPREFIX("userbind");
         BADPREFIX("v_");
         BADPREFIX("vid_");
         BADPREFIX("crosshair");
         BADCVAR("mod_q3bsp_lightmapmergepower");
         BADCVAR("mod_q3bsp_nolightmaps");
         BADCVAR("fov");
         BADCVAR("mastervolume");
         BADCVAR("volume");
         BADCVAR("bgmvolume");
         BADCVAR("in_pitch_min");
         BADCVAR("in_pitch_max");
         // private
         BADCVAR("developer");
         BADCVAR("log_dest_udp");
         BADCVAR("net_address");
         BADCVAR("net_address_ipv6");
         BADCVAR("port");
         BADCVAR("savedgamecfg");
         BADCVAR("serverconfig");
         BADCVAR("sv_autoscreenshot");
         BADCVAR("sv_heartbeatperiod");
         BADCVAR("sv_vote_master_password");
         BADCVAR("sys_colortranslation");
         BADCVAR("sys_specialcharactertranslation");
         BADCVAR("timeformat");
         BADCVAR("timestamps");
         BADCVAR("g_require_stats");
         BADPREFIX("developer_");
         BADPREFIX("g_ban_");
         BADPREFIX("g_banned_list");
         BADPREFIX("g_require_stats_");
         BADPREFIX("g_chat_flood_");
         BADPREFIX("g_ghost_items");
         BADPREFIX("g_playerstats_");
         BADPREFIX("g_voice_flood_");
         BADPREFIX("log_file");
         BADPREFIX("quit_");
         BADPREFIX("rcon_");
         BADPREFIX("sv_allowdownloads");
         BADPREFIX("sv_autodemo");
         BADPREFIX("sv_curl_");
         BADPREFIX("sv_eventlog");
         BADPREFIX("sv_logscores_");
         BADPREFIX("sv_master");
         BADPREFIX("sv_weaponstats_");
         BADPREFIX("sv_waypointsprite_");
         BADCVAR("rescan_pending");
         // these can contain player IDs, so better hide
         BADPREFIX("g_forced_team_");
         BADCVAR("sv_muteban_list");
         BADCVAR("sv_voteban_list");
         BADCVAR("sv_allow_customplayermodels_idlist");
         BADCVAR("sv_allow_customplayermodels_speciallist");
         // mapinfo
         BADCVAR("fraglimit");
         BADCVAR("g_arena");
         BADCVAR("g_assault");
         BADCVAR("g_ca");
         BADCVAR("g_ca_teams");
         BADCVAR("g_conquest");
         BADCVAR("g_conquest_teams");
         BADCVAR("g_ctf");
         BADCVAR("g_cts");
         BADCVAR("g_dotc");
         BADCVAR("g_dm");
         BADCVAR("g_domination");
         BADCVAR("g_domination_default_teams");
         BADCVAR("g_duel");
         BADCVAR("g_duel_not_dm_maps");
         BADCVAR("g_freezetag");
         BADCVAR("g_freezetag_teams");
         BADCVAR("g_invasion_teams");
         BADCVAR("g_invasion_type");
         BADCVAR("g_jailbreak");
         BADCVAR("g_jailbreak_teams");
         BADCVAR("g_keepaway");
         BADCVAR("g_keyhunt");
         BADCVAR("g_keyhunt_teams");
         BADCVAR("g_lms");
         BADCVAR("g_nexball");
         BADCVAR("g_onslaught");
         BADCVAR("g_race");
         BADCVAR("g_race_laps_limit");
         BADCVAR("g_race_qualifying_timelimit");
         BADCVAR("g_race_qualifying_timelimit_override");
         BADCVAR("g_runematch");
         BADCVAR("g_shootfromeye");
         BADCVAR("g_snafu");
         BADCVAR("g_survival");
         BADCVAR("g_survival_not_dm_maps");
         BADCVAR("g_tdm");
         BADCVAR("g_tdm_on_dm_maps");
         BADCVAR("g_tdm_teams");
         BADCVAR("g_vip");
         BADCVAR("leadlimit");
         BADCVAR("nextmap");
         BADCVAR("teamplay");
         BADCVAR("timelimit");
         BADCVAR("g_mapinfo_settemp_acl");
         BADCVAR("g_mapinfo_ignore_warnings");
         BADCVAR("g_maplist_ignore_sizes");
         BADCVAR("g_maplist_sizes_count_bots");
         // long
         BADCVAR("hostname");
         BADCVAR("g_maplist");
         BADCVAR("g_maplist_mostrecent");
         BADCVAR("sv_motd");
         v = cvar_string(k);
         d = cvar_defstring(k);
         if(v == d)
             continue;
         if(adding)
         {
             cvar_changes = strcat(cvar_changes, k, " \"", v, "\" // \"", d, "\"\n");
             if(strlen(cvar_changes) > 16384)
             {
                 cvar_changes = "// too many settings have been changed to show them here\n";
                 adding = 0;
             }
         }
         // now check if the changes are actually gameplay relevant
         // does nothing gameplay relevant
         BADCVAR("captureleadlimit_override");
         BADCVAR("condump_stripcolors");
         BADCVAR("gameversion");
         BADCVAR("fs_gamedir");
         BADCVAR("g_allow_oldvortexbeam");
         BADCVAR("g_balance_kill_delay");
         BADCVAR("g_buffs_pickup_anyway");
         BADCVAR("g_buffs_randomize");
         BADCVAR("g_buffs_randomize_teamplay");
         BADCVAR("g_campcheck_distance");
         BADCVAR("g_chatsounds");
         BADCVAR("g_ca_point_leadlimit");
         BADCVAR("g_ca_point_limit");
         BADCVAR("g_ctf_captimerecord_always");
         BADCVAR("g_ctf_flag_glowtrails");
         BADCVAR("g_ctf_dynamiclights");
         BADCVAR("g_ctf_flag_pickup_verbosename");
         BADPRESUFFIX("g_ctf_flag_", "_model");
         BADPRESUFFIX("g_ctf_flag_", "_skin");
         BADCVAR("g_domination_point_leadlimit");
         BADCVAR("g_forced_respawn");
         BADCVAR("g_freezetag_point_leadlimit");
         BADCVAR("g_freezetag_point_limit");
         BADCVAR("g_glowtrails");
         BADCVAR("g_hats");
         BADCVAR("g_casings");
         BADCVAR("g_invasion_point_limit");
         BADCVAR("g_jump_grunt");
         BADCVAR("g_keepaway_ballcarrier_effects");
         BADCVAR("g_keepawayball_effects");
         BADCVAR("g_keyhunt_point_leadlimit");
         BADCVAR("g_nexball_goalleadlimit");
         BADCVAR("g_new_toys_autoreplace");
         BADCVAR("g_new_toys_use_pickupsound");
         BADCVAR("g_physics_predictall");
         BADCVAR("g_piggyback");
         BADCVAR("g_playerclip_collisions");
         BADCVAR("g_spawn_alloweffects");
         BADCVAR("g_tdm_point_leadlimit");
         BADCVAR("g_tdm_point_limit");
         BADCVAR("leadlimit_and_fraglimit");
         BADCVAR("leadlimit_override");
         BADCVAR("pausable");
         BADCVAR("sv_announcer");
         BADCVAR("sv_checkforpacketsduringsleep");
         BADCVAR("sv_damagetext");
         BADCVAR("sv_db_saveasdump");
         BADCVAR("sv_intermission_cdtrack");
         BADCVAR("sv_mapchange_delay");
         BADCVAR("sv_minigames");
         BADCVAR("sv_namechangetimer");
         BADCVAR("sv_precacheplayermodels");
         BADCVAR("sv_radio");
         BADCVAR("sv_stepheight");
         BADCVAR("sv_timeout");
         BADCVAR("sv_weapons_modeloverride");
         BADCVAR("w_prop_interval");
         BADPREFIX("chat_");
         BADPREFIX("crypto_");
         BADPREFIX("gameversion_");
         BADPREFIX("g_chat_");
         BADPREFIX("g_ctf_captimerecord_");
         BADPREFIX("g_hats_");
         BADPREFIX("g_maplist_");
         BADPREFIX("g_mod_");
         BADPREFIX("g_respawn_");
         BADPREFIX("net_");
         BADPREFIX("notification_");
         BADPREFIX("prvm_");
         BADPREFIX("skill_");
         BADPREFIX("sv_allow_");
         BADPREFIX("sv_cullentities_");
         BADPREFIX("sv_maxidle_");
         BADPREFIX("sv_minigames_");
         BADPREFIX("sv_radio_");
         BADPREFIX("sv_timeout_");
         BADPREFIX("sv_vote_");
         BADPREFIX("timelimit_");
         // allowed changes to server admins (please sync this to server.cfg)
         // vi commands:
         //   :/"impure"/,$d
         //   :g!,^\/\/[^ /],d
         //   :%s,//\([^ ]*\).*,BADCVAR("\1");,
         //   :%!sort
         // yes, this does contain some redundant stuff, don't really care
         BADPREFIX("bot_ai_");
         BADCVAR("bot_config_file");
         BADCVAR("bot_number");
         BADCVAR("bot_prefix");
         BADCVAR("bot_suffix");
         BADCVAR("capturelimit_override");
         BADCVAR("fraglimit_override");
         BADCVAR("gametype");
         BADCVAR("g_antilag");
         BADCVAR("g_balance_teams");
         BADCVAR("g_balance_teams_prevent_imbalance");
         BADCVAR("g_balance_teams_scorefactor");
         BADCVAR("g_ban_sync_trusted_servers");
         BADCVAR("g_ban_sync_uri");
         BADCVAR("g_buffs");
         BADCVAR("g_ca_teams_override");
         BADCVAR("g_ctf_fullbrightflags");
         BADCVAR("g_ctf_ignore_frags");
         BADCVAR("g_ctf_leaderboard");
         BADCVAR("g_domination_point_limit");
         BADCVAR("g_domination_teams_override");
         BADCVAR("g_freezetag_teams_override");
         BADCVAR("g_friendlyfire");
         BADCVAR("g_fullbrightitems");
         BADCVAR("g_fullbrightplayers");
         BADCVAR("g_keyhunt_point_limit");
         BADCVAR("g_keyhunt_teams_override");
         BADCVAR("g_lms_lives_override");
         BADCVAR("g_maplist");
         BADCVAR("g_maxplayers");
         BADCVAR("g_mirrordamage");
         BADCVAR("g_nexball_goallimit");
         BADCVAR("g_norecoil");
         BADCVAR("g_physics_clientselect");
         BADCVAR("g_pinata");
         BADCVAR("g_powerups");
         BADCVAR("g_player_brightness");
         BADCVAR("g_rocket_flying");
         BADCVAR("g_rocket_flying_disabledelays");
         BADCVAR("g_spawnshieldtime");
         BADCVAR("g_start_delay");
         BADCVAR("g_superspectate");
         BADCVAR("g_tdm_teams_override");
         BADCVAR("g_warmup");
         BADCVAR("g_weapon_stay"); BADPRESUFFIX("g_", "_weapon_stay");
         BADCVAR("hostname");
         BADCVAR("log_file");
         BADCVAR("maxplayers");
         BADCVAR("minplayers");
         BADCVAR("minplayers_per_team");
         BADCVAR("net_address");
         BADCVAR("port");
         BADCVAR("rcon_password");
         BADCVAR("rcon_restricted_commands");
         BADCVAR("rcon_restricted_password");
         BADCVAR("skill");
         BADCVAR("sv_adminnick");
         BADCVAR("sv_autoscreenshot");
         BADCVAR("sv_autotaunt");
         BADCVAR("sv_curl_defaulturl");
         BADCVAR("sv_defaultcharacter");
         BADCVAR("sv_defaultcharacterskin");
         BADCVAR("sv_defaultplayercolors");
         BADCVAR("sv_defaultplayermodel");
         BADCVAR("sv_defaultplayerskin");
         BADCVAR("sv_maxidle");
         BADCVAR("sv_maxrate");
         BADCVAR("sv_motd");
         BADCVAR("sv_public");
         BADCVAR("sv_ready_restart");
         BADCVAR("sv_showfps");
         BADCVAR("sv_status_privacy");
         BADCVAR("sv_taunt");
         BADCVAR("sv_vote_call");
         BADCVAR("sv_vote_commands");
         BADCVAR("sv_vote_majority_factor");
         BADCVAR("sv_vote_master");
         BADCVAR("sv_vote_master_commands");
         BADCVAR("sv_vote_master_password");
         BADCVAR("sv_vote_simple_majority_factor");
         BADVALUE("sys_ticrate", "0.0166667");
         BADVALUE("sys_ticrate", "0.0333333");
         BADCVAR("teamplay_mode");
         BADCVAR("timelimit_override");
         BADPREFIX("g_warmup_");
         BADPREFIX("sv_info_");
         BADPREFIX("sv_ready_restart_");
         // mutators that announce themselves properly to the server browser
         BADCVAR("g_instagib");
         BADCVAR("g_new_toys");
         BADCVAR("g_nix");
         BADCVAR("g_grappling_hook");
         BADCVAR("g_jetpack");
         // temporary for testing
         // TODO remove before 0.8.3 release
         BADCVAR("g_ca_weaponarena");
         BADCVAR("g_freezetag_weaponarena");
         BADCVAR("g_lms_weaponarena");
         BADCVAR("g_ctf_stalemate_time");
 #undef BADPRESUFFIX
 #undef BADPREFIX
 #undef BADCVAR
 #undef BADVALUE
         if(pureadding)
         {
             cvar_purechanges = strcat(cvar_purechanges, k, " \"", v, "\" // \"", d, "\"\n");
             if(strlen(cvar_purechanges) > 16384)
             {
                 cvar_purechanges = "// too many settings have been changed to show them here\n";
                 pureadding = 0;
             }
         }
         ++cvar_purechanges_count;
         // WARNING: this variable is used for the server list
         // NEVER dare to skip this code!
         // Hacks to intentionally appearing as "pure server" even though you DO have
         // modified settings may be punished by removal from the server list.
         // You can do to the variables cvar_changes and cvar_purechanges all you want,
         // though.
     }
     buf_del(h);
     if(cvar_changes == "")
         cvar_changes = "// this server runs at default server settings\n";
     else
         cvar_changes = strcat("// this server runs at modified server settings:\n", cvar_changes);
     cvar_changes = strzone(cvar_changes);
     if(cvar_purechanges == "")
         cvar_purechanges = "// this server runs at default gameplay settings\n";
     else
         cvar_purechanges = strcat("// this server runs at modified gameplay settings:\n", cvar_purechanges);
     cvar_purechanges = strzone(cvar_purechanges);
 }
droptofloor()
void droptofloor (entity this)
Definition at line 2203 of file world.qc.
References DropToFloor_Handler(), and InitializeEntity().
 {
     InitializeEntity(this, DropToFloor_Handler, INITPRIO_DROPTOFLOOR);
 }
DropToFloor_Handler()
void DropToFloor_Handler (entity this)
Definition at line 2197 of file world.qc.
References dropped_origin, origin, and WITHSELF.
Referenced by droptofloor().
 {
     WITHSELF(this, builtin_droptofloor());
     this.dropped_origin = this.origin;
 }
DumpStats()
void DumpStats (float final)
Definition at line 1163 of file world.qc.
References autocvar_sv_eventlog, autocvar_sv_eventlog_console, autocvar_sv_logscores_bots, autocvar_sv_logscores_console, autocvar_sv_logscores_file, autocvar_sv_logscores_filename, CS(), fclose(), FILE_APPEND, fopen(), FOREACH_CLIENT, fputs(), ftos(), GameLogEcho(), GetGametype(), GetMapname(), GetPlayerScoreString(), GetTeamScoreString(), IS_BOT_CLIENT, IS_PLAYER, IS_REAL_CLIENT, jointime, LOG_HELP, MUTATOR_CALLHOOK, NULL, rint(), strcat(), teamplay, and time.
Referenced by GameCommand_printstats(), and NextLevel().
 {
     float file;
     string s;
     float to_console;
     float to_eventlog;
     float to_file;
     float i;
     to_console = autocvar_sv_logscores_console;
     to_eventlog = autocvar_sv_eventlog;
     to_file = autocvar_sv_logscores_file;
     if(!final)
     {
         to_console = true; // always print printstats replies
         to_eventlog = false; // but never print them to the event log
     }
     if(to_eventlog)
         if(autocvar_sv_eventlog_console)
             to_console = false; // otherwise we get the output twice
     if(final)
         s = ":scores:";
     else
         s = ":status:";
     s = strcat(s, GetGametype(), "_", GetMapname(), ":", ftos(rint(time)));
     if(to_console)
         LOG_HELP(s);
     if(to_eventlog)
         GameLogEcho(s);
     file = -1;
     if(to_file)
     {
         file = fopen(autocvar_sv_logscores_filename, FILE_APPEND);
         if(file == -1)
             to_file = false;
         else
             fputs(file, strcat(s, "\n"));
     }
     s = strcat(":labels:player:", GetPlayerScoreString(NULL, 0));
     if(to_console)
         LOG_HELP(s);
     if(to_eventlog)
         GameLogEcho(s);
     if(to_file)
         fputs(file, strcat(s, "\n"));
     FOREACH_CLIENT(IS_REAL_CLIENT(it) || (IS_BOT_CLIENT(it) && autocvar_sv_logscores_bots), {
         s = strcat(":player:see-labels:", GetPlayerScoreString(it, 0), ":");
         s = strcat(s, ftos(rint(time - CS(it).jointime)), ":");
         if(IS_PLAYER(it) || MUTATOR_CALLHOOK(GetPlayerStatus, it))
             s = strcat(s, ftos(it.team), ":");
         else
             s = strcat(s, "spectator:");
         if(to_console)
             LOG_HELP(s, playername(it.netname, it.team, false));
         if(to_eventlog)
             GameLogEcho(strcat(s, ftos(it.playerid), ":", playername(it.netname, it.team, false)));
         if(to_file)
             fputs(file, strcat(s, playername(it.netname, it.team, false), "\n"));
     });
     if(teamplay)
     {
         s = strcat(":labels:teamscores:", GetTeamScoreString(0, 0));
         if(to_console)
             LOG_HELP(s);
         if(to_eventlog)
             GameLogEcho(s);
         if(to_file)
             fputs(file, strcat(s, "\n"));
         for(i = 1; i < 16; ++i)
         {
             s = strcat(":teamscores:see-labels:", GetTeamScoreString(i, 0));
             s = strcat(s, ":", ftos(i));
             if(to_console)
                 LOG_HELP(s);
             if(to_eventlog)
                 GameLogEcho(s);
             if(to_file)
                 fputs(file, strcat(s, "\n"));
         }
     }
     if(to_console)
         LOG_HELP(":end");
     if(to_eventlog)
         GameLogEcho(":end");
     if(to_file)
     {
         fputs(file, ":end\n");
         fclose(file);
     }
 }
EndFrame()
void EndFrame ()
Definition at line 2279 of file world.qc.
References anticheat_endframe(), antilag_record(), autocvar_g_antilag_nudge, ceil(), CS(), entity(), FOREACH_CLIENT, frametime, g_monsters, g_projectiles, IL_EACH, IL_ENDFRAME(), IS_REAL_CLIENT, IS_SPEC, Physics_Frame(), systems_update(), and time.
 {
     anticheat_endframe();
     Physics_Frame();
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         entity e = IS_SPEC(it) ? it.enemy : it;
         if (e.typehitsound) {
             STAT(TYPEHIT_TIME, it) = time;
         } else if (e.killsound) {
             STAT(KILL_TIME, it) = time;
         } else if (e.damage_dealt) {
             STAT(HIT_TIME, it) = time;
             STAT(DAMAGE_DEALT_TOTAL, it) += ceil(e.damage_dealt);
         }
     });
     // add 1 frametime because after this, engine SV_Physics
     // increases time by a frametime and then networks the frame
     // add another frametime because client shows everything with
     // 1 frame of lag (cl_nolerp 0). The last +1 however should not be
     // needed!
     float altime = time + frametime * (1 + autocvar_g_antilag_nudge);
     FOREACH_CLIENT(true, {
         it.typehitsound = false;
         it.damage_dealt = 0;
         it.killsound = false;
         antilag_record(it, CS(it), altime);
     });
     IL_EACH(g_monsters, true,
     {
         antilag_record(it, it, altime);
     });
     IL_EACH(g_projectiles, it.classname == "nade",
     {
         antilag_record(it, it, altime);
     });
     systems_update();
     IL_ENDFRAME();
 }
GameplayMode_DelayedInit()
void GameplayMode_DelayedInit (entity this)
Definition at line 631 of file world.qc.
References ScoreRules_generic(), and scores_initialized.
Referenced by InitGameplayMode().
 {
     if(!scores_initialized)
         ScoreRules_generic();
 }
GetWinningCode()
float GetWinningCode (float fraglimitreached, float equality)
Definition at line 1356 of file world.qc.
References autocvar_g_campaign, WINNING_NEVER, WINNING_NO, WINNING_STARTSUDDENDEATHOVERTIME, and WINNING_YES.
Referenced by WinningCondition_Scores().
 {
     if(autocvar_g_campaign == 1)
     {
         if(fraglimitreached)
             return WINNING_YES;
         else
             return WINNING_NO;
     }
     else
     {
         if(equality)
         {
             if(fraglimitreached)
                 return WINNING_STARTSUDDENDEATHOVERTIME;
             else
                 return WINNING_NEVER;
         }
         else
         {
             if(fraglimitreached)
                 return WINNING_YES;
             else
                 return WINNING_NO;
         }
     }
 }
GotoFirstMap()
void GotoFirstMap (entity this)
Definition at line 115 of file world.qc.
References autocvar__sv_init, autocvar_g_maplist, autocvar_g_maplist_shuffle, cvar_set(), DoNextMapOverride(), ftos(), GotoNextMap(), LOG_INFO, MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), nextthink, ShuffleMaplist(), time, and tokenizebyseparator.
Referenced by spawnfunc().
 {
     float n;
     if(autocvar__sv_init)
     {
         // cvar_set("_sv_init", "0");
         // we do NOT set this to 0 any more, so someone "accidentally" changing
         // to this "init" map on a dedicated server will cause no permanent
         // harm
         if(autocvar_g_maplist_shuffle)
             ShuffleMaplist();
         n = tokenizebyseparator(autocvar_g_maplist, " ");
         cvar_set("g_maplist_index", ftos(n - 1)); // jump to map 0 in GotoNextMap
         MapInfo_Enumerate();
         MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
         if(!DoNextMapOverride(1))
             GotoNextMap(1);
         return;
     }
     if(time < 5)
     {
         this.nextthink = time;
     }
     else
     {
         this.nextthink = time + 1;
         LOG_INFO("Waiting for _sv_init being set to 1 by initialization scripts...");
     }
 }
InitGameplayMode()
void InitGameplayMode ()
Definition at line 637 of file world.qc.
References cache_lastmutatormsg, cache_mutatormsg, clientstuff, cvar_value_issafe(), gamemode_name, GameplayMode_DelayedInit(), GameRules_teams(), InitializeEntity(), LOG_INFO, MapInfo_ClearTemps(), MapInfo_LoadedGametype, MapInfo_LoadMapSettings(), MapInfo_Map_clientstuff, MapInfo_Map_fog, MapInfo_Type_ToText(), mapname, min(), NULL, string_null, strzone(), v, vector(), vlen(), VoteReset(), and world.
Referenced by spawnfunc().
 {
     VoteReset();
     // find out good world mins/maxs bounds, either the static bounds found by looking for solid, or the mapinfo specified bounds
     get_mi_min_max(1);
     // assign reflectively to avoid "assignment to world" warning
     int done = 0; for (int i = 0, n = numentityfields(); i < n; ++i) {
         string k = entityfieldname(i); vector v = (k == "mins") ? mi_min : (k == "maxs") ? mi_max : '0 0 0';
         if (v) {
             putentityfieldstring(i, world, sprintf("%v", v));
             if (++done == 2) break;
         }
     }
     // currently, NetRadiant's limit is 131072 qu for each side
     // distance from one corner of a 131072qu cube to the opposite corner is approx. 227023 qu
     // set the distance according to map size but don't go over the limit to avoid issues with float precision
     // in case somebody makes extremely large maps
     max_shot_distance = min(230000, vlen(world.maxs - world.mins));
     MapInfo_LoadMapSettings(mapname);
     GameRules_teams(false);
     if (!cvar_value_issafe(world.fog))
     {
         LOG_INFO("The current map contains a potentially harmful fog setting, ignored");
         world.fog = string_null;
     }
     if(MapInfo_Map_fog != "")
     {
         if(MapInfo_Map_fog == "none")
             world.fog = string_null;
         else
             world.fog = strzone(MapInfo_Map_fog);
     }
     clientstuff = strzone(MapInfo_Map_clientstuff);
     MapInfo_ClearTemps();
     gamemode_name = MapInfo_Type_ToText(MapInfo_LoadedGametype);
     cache_mutatormsg = strzone("");
     cache_lastmutatormsg = strzone("");
     InitializeEntity(NULL, GameplayMode_DelayedInit, INITPRIO_GAMETYPE_FALLBACK);
 }
InitializeEntitiesRun()
void InitializeEntitiesRun ()
Definition at line 2158 of file world.qc.
References backtrace, delete_fn(), entity(), eprint(), func_null(), initialize_entity_first, next, NULL, remove_except_protected(), remove_unsafely(), strcat(), and void.
Referenced by StartFrame().
 {
     entity startoflist = initialize_entity_first;
     initialize_entity_first = NULL;
     delete_fn = remove_except_protected;
     for (entity e = startoflist; e; e = e.initialize_entity_next)
     {
         e.remove_except_protected_forbidden = 1;
     }
     for (entity e = startoflist; e; )
     {
         e.remove_except_protected_forbidden = 0;
         e.initialize_entity_order = 0;
         entity next = e.initialize_entity_next;
         e.initialize_entity_next = NULL;
         var void(entity this) func = e.initialize_entity;
         e.initialize_entity = func_null;
         if (e.classname == "initialize_entity")
         {
             entity wrappee = e.enemy;
             builtin_remove(e);
             e = wrappee;
         }
         //dprint("Delayed initialization: ", e.classname, "\n");
         if (func)
         {
             func(e);
         }
         else
         {
             eprint(e);
             backtrace(strcat("Null function in: ", e.classname, "\n"));
         }
         e = next;
     }
     delete_fn = remove_unsafely;
 }
InitializeEntity()
void InitializeEntity (entity e, void(entity this) func, int order)
Definition at line 2125 of file world.qc.
References entity(), initialize_entity_first, NULL, and prev.
Referenced by _StartItem(), buffs_Initialize(), ctf_FlagSetup(), ctf_Initialize(), dom_Initialize(), door_reset(), droptofloor(), InitGameplayMode(), invasion_Initialize(), ka_SpawnBall(), MUTATOR_HOOKFUNCTION(), nb_Initialize(), ons_ControlPoint_Setup(), ons_GeneratorSetup(), ons_Initialize(), readplayerstartcvars(), relocate_spawnpoint(), spawnfunc(), SUB_CalcAngleMoveEnt(), target_checkpoint_setup(), target_give_init(), tdm_Initialize(), Teleport_Touch(), train_next(), and trigger_push_findtarget().
 {
     entity prev, cur;
     if (!e || e.initialize_entity)
     {
         // make a proxy initializer entity
         entity e_old = e;
         e = new(initialize_entity);
         e.enemy = e_old;
     }
     e.initialize_entity = func;
     e.initialize_entity_order = order;
     cur = initialize_entity_first;
     prev = NULL;
     for (;;)
     {
         if (!cur || cur.initialize_entity_order > order)
         {
             // insert between prev and cur
             if (prev)
                 prev.initialize_entity_next = e;
             else
                 initialize_entity_first = e;
             e.initialize_entity_next = cur;
             return;
         }
         prev = cur;
         cur = cur.initialize_entity_next;
     }
 }
InitiateOvertime()
void InitiateOvertime ()
Definition at line 1348 of file world.qc.
References autocvar_timelimit_overtime, checkrules_overtimesadded, cvar_set(), ftos(), and NULL.
Referenced by CheckRules_World().
 {
     ++checkrules_overtimesadded;
     //add one more overtime by simply extending the timelimit
     cvar_set("timelimit", ftos(autocvar_timelimit + autocvar_timelimit_overtime));
     Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_OVERTIME_TIME, autocvar_timelimit_overtime * 60);
 }
InitiateSuddenDeath()
float InitiateSuddenDeath ()
Definition at line 1321 of file world.qc.
References autocvar_g_campaign, autocvar_timelimit_overtime, autocvar_timelimit_overtimes, autocvar_timelimit_suddendeath, checkrules_overtimesadded, checkrules_suddendeathend, g_race, g_race_qualifying, race_StartCompleting(), and time.
Referenced by CheckRules_World().
 {
     // Check first whether normal overtimes could be added before initiating suddendeath mode
     // - for this timelimit_overtime needs to be >0 of course
     // - also check the winning condition calculated in the previous frame and only add normal overtime
     //   again, if at the point at which timelimit would be extended again, still no winner was found
     if (!autocvar_g_campaign && checkrules_overtimesadded >= 0
         && (checkrules_overtimesadded < autocvar_timelimit_overtimes || autocvar_timelimit_overtimes < 0)
         && autocvar_timelimit_overtime && !(g_race && !g_race_qualifying))
     {
         return 1; // need to call InitiateOvertime later
     }
     else
     {
         if(!checkrules_suddendeathend)
         {
             if(autocvar_g_campaign)
                 checkrules_suddendeathend = time; // no suddendeath in campaign
             else
                 checkrules_suddendeathend = time + 60 * autocvar_timelimit_suddendeath;
             if(g_race && !g_race_qualifying)
                 race_StartCompleting();
         }
         return 0;
     }
 }
MoveToRandomLocationWithinBounds()
bool MoveToRandomLocationWithinBounds (entity e, vector boundmin, vector boundmax, float goodcontents, float badcontents, float badsurfaceflags, int attempts, float maxaboveground, float minviewdistance)
Definition at line 1028 of file world.qc.
References checkpvs(), entity(), ftos(), g_items, g_spawnpoints, IL_EACH, LOG_DEBUG, MOVE_NORMAL, normalize(), NULL, Q3SURFACEFLAG_SKY, random(), setorigin(), trace_dphitcontents, trace_dphitq3surfaceflags, trace_dphittexturename, trace_endpos, trace_fraction, trace_startsolid, vectoangles(), vector(), and vlen().
Referenced by MoveToRandomMapLocation().
 {
     float m = e.dphitcontentsmask;
     e.dphitcontentsmask = goodcontents | badcontents;
     vector org = boundmin;
     vector delta = boundmax - boundmin;
     vector start, end;
     start = end = org;
     int j; // used after the loop
     for(j = 0; j < attempts; ++j)
     {
         start.x = org.x + random() * delta.x;
         start.y = org.y + random() * delta.y;
         start.z = org.z + random() * delta.z;
         // rule 1: start inside world bounds, and outside
         // solid, and don't start from somewhere where you can
         // fall down to evil
         tracebox(start, e.mins, e.maxs, start - '0 0 1' * delta.z, MOVE_NORMAL, e);
         if (trace_fraction >= 1)
             continue;
         if (trace_startsolid)
             continue;
         if (trace_dphitcontents & badcontents)
             continue;
         if (trace_dphitq3surfaceflags & badsurfaceflags)
             continue;
         // rule 2: if we are too high, lower the point
         if (trace_fraction * delta.z > maxaboveground)
             start = trace_endpos + '0 0 1' * maxaboveground;
         vector enddown = trace_endpos;
         // rule 3: make sure we aren't outside the map. This only works
         // for somewhat well formed maps. A good rule of thumb is that
         // the map should have a convex outside hull.
         // these can be traceLINES as we already verified the starting box
         vector mstart = start + 0.5 * (e.mins + e.maxs);
         traceline(mstart, mstart + '1 0 0' * delta.x, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart - '1 0 0' * delta.x, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart + '0 1 0' * delta.y, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart - '0 1 0' * delta.y, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         traceline(mstart, mstart + '0 0 1' * delta.z, MOVE_NORMAL, e);
         if (trace_fraction >= 1 || trace_dphittexturename == "common/caulk")
             continue;
         // rule 4: we must "see" some spawnpoint or item
         entity sp = NULL;
         IL_EACH(g_spawnpoints, checkpvs(mstart, it),
         {
             if((traceline(mstart, it.origin, MOVE_NORMAL, e), trace_fraction) >= 1)
             {
                 sp = it;
                 break;
             }
         });
         if(!sp)
         {
             int items_checked = 0;
             IL_EACH(g_items, checkpvs(mstart, it),
             {
                 if((traceline(mstart, it.origin + (it.mins + it.maxs) * 0.5, MOVE_NORMAL, e), trace_fraction) >= 1)
                 {
                     sp = it;
                     break;
                 }
                 ++items_checked;
                 if(items_checked >= attempts)
                     break; // sanity
             });
             if(!sp)
                 continue;
         }
         // find a random vector to "look at"
         end.x = org.x + random() * delta.x;
         end.y = org.y + random() * delta.y;
         end.z = org.z + random() * delta.z;
         end = start + normalize(end - start) * vlen(delta);
         // rule 4: start TO end must not be too short
         tracebox(start, e.mins, e.maxs, end, MOVE_NORMAL, e);
         if(trace_startsolid)
             continue;
         if(trace_fraction < minviewdistance / vlen(delta))
             continue;
         // rule 5: don't want to look at sky
         if(trace_dphitq3surfaceflags & Q3SURFACEFLAG_SKY)
             continue;
         // rule 6: we must not end up in trigger_hurt
         if(tracebox_hits_trigger_hurt(start, e.mins, e.maxs, enddown))
             continue;
         break;
     }
     e.dphitcontentsmask = m;
     if(j < attempts)
     {
         setorigin(e, start);
         e.angles = vectoangles(end - start);
         LOG_DEBUG("Needed ", ftos(j + 1), " attempts");
         return true;
     }
     return false;
 }
MoveToRandomMapLocation()
float MoveToRandomMapLocation (entity e, float goodcontents, float badcontents, float badsurfaceflags, float attempts, float maxaboveground, float minviewdistance)
Definition at line 1150 of file world.qc.
References MoveToRandomLocationWithinBounds(), and world.
Referenced by buff_Respawn(), CheatImpulse(), invasion_SpawnChosenMonster(), and ka_RespawnBall().
 {
     return MoveToRandomLocationWithinBounds(e, world.mins, world.maxs, goodcontents, badcontents, badsurfaceflags, attempts, maxaboveground, minviewdistance);
 }
NextLevel()
void NextLevel ()
Definition at line 1269 of file world.qc.
References autocvar_g_campaign, autocvar_sv_eventlog, autocvar_sv_mapchange_delay, bprint(), CampaignPreIntermission(), CPID_Null, DumpStats(), FixIntermissionClient(), FOREACH_CLIENT, GameLogClose(), GameLogEcho(), intermission_exittime, intermission_running, IS_PLAYER, localcmd, MUTATOR_CALLHOOK, NULL, player_count, time, VoteReset(), and WeaponStats_Shutdown().
Referenced by CheckRules_World().
 {
     game_stopped = true;
     intermission_running = true; // game over
     // enforce a wait time before allowing changelevel
     if(player_count > 0)
         intermission_exittime = time + autocvar_sv_mapchange_delay;
     else
         intermission_exittime = -1;
     /*
     WriteByte (MSG_ALL, SVC_CDTRACK);
     WriteByte (MSG_ALL, 3);
     WriteByte (MSG_ALL, 3);
     // done in FixIntermission
     */
     //pos = FindIntermission ();
     VoteReset();
     DumpStats(true);
     // send statistics
     PlayerStats_GameReport(true);
     WeaponStats_Shutdown();
     Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_Null); // kill all centerprints now
     if(autocvar_sv_eventlog)
         GameLogEcho(":gameover");
     GameLogClose();
     FOREACH_CLIENT(IS_PLAYER(it), {
         FixIntermissionClient(it);
         if(it.winning)
             bprint(playername(it.netname, it.team, false), " ^7wins.\n");
     });
     target_music_kill();
     if(autocvar_g_campaign)
         CampaignPreIntermission();
     MUTATOR_CALLHOOK(MatchEnd);
     localcmd("\nsv_hook_gameend\n");
 }
Physics_Frame()
void Physics_Frame ()
Definition at line 2237 of file world.qc.
References g_moveables, IL_EACH, IS_CLIENT, MOVETYPE_NONE, MOVETYPE_PHYSICS, Movetype_Physics_NoMatchTicrate(), MOVETYPE_QCENTITY, MOVETYPE_USER_FIRST, MOVETYPE_USER_LAST, and systems_update().
Referenced by EndFrame().
 {
     if(autocvar_sv_freezenonclients)
         return;
     IL_EACH(g_moveables, true,
     {
         if(IS_CLIENT(it) || it.move_movetype == MOVETYPE_PHYSICS)
             continue;
         //set_movetype(it, it.move_movetype);
         // inline the set_movetype function, since this is called a lot
         it.movetype = (it.move_qcphysics) ? MOVETYPE_QCENTITY : it.move_movetype;
         if(it.move_qcphysics && it.move_movetype != MOVETYPE_NONE)
             Movetype_Physics_NoMatchTicrate(it, PHYS_INPUT_TIMELENGTH, false);
         if(it.movetype >= MOVETYPE_USER_FIRST && it.movetype <= MOVETYPE_USER_LAST) // these cases have no think handling
         {
             if(it.move_movetype == MOVETYPE_PUSH || it.move_movetype == MOVETYPE_FAKEPUSH)
                 continue; // these movetypes have no regular think function
             // handle thinking here
             if (getthink(it) && it.nextthink > 0 && it.nextthink <= time + frametime)
                 RunThink(it);
         }
     });
     if(autocvar_sv_gameplayfix_delayprojectiles >= 0)
         return;
     // make a second pass to see if any ents spawned this frame and make
     // sure they run their move/think. this is verified by checking .move_time, which will never be 0 if the entity has moved
     // MOVETYPE_NONE is also checked as .move_time WILL be 0 with that movetype
     IL_EACH(g_moveables, it.move_qcphysics,
     {
         if(IS_CLIENT(it) || it.move_time || it.move_movetype == MOVETYPE_NONE || it.move_movetype == MOVETYPE_PHYSICS)
             continue;
         Movetype_Physics_NoMatchTicrate(it, PHYS_INPUT_TIMELENGTH, false);
     });
 }
PingPLReport_Spawn()
void PingPLReport_Spawn ()
Definition at line 95 of file world.qc.
References new_pure, pingplreport, PingPLReport_Think(), setthink, and time.
Referenced by spawnfunc().
 {
     pingplreport = new_pure(pingplreport);
     setthink(pingplreport, PingPLReport_Think);
     pingplreport.nextthink = time;
 }
PingPLReport_Think()
void PingPLReport_Think (entity this)
Definition at line 57 of file world.qc.
References bound(), ceil(), cnt, CS(), entity(), IS_CLIENT, IS_REAL_CLIENT, LATENCY_THINKRATE, latency_time, maxclients, min(), MSG_BROADCAST, nextthink, ping, ping_movementloss, ping_packetloss, sys_frametime, time, WriteByte(), and WriteShort().
Referenced by PingPLReport_Spawn().
 {
     float delta;
     entity e;
     delta = 3 / maxclients;
     if(delta < sys_frametime)
         delta = 0;
     this.nextthink = time + delta;
     e = edict_num(this.cnt + 1);
     if(IS_CLIENT(e) && IS_REAL_CLIENT(e))
     {
         WriteHeader(MSG_BROADCAST, TE_CSQC_PINGPLREPORT);
         WriteByte(MSG_BROADCAST, this.cnt);
         WriteShort(MSG_BROADCAST, bound(1, CS(e).ping, 32767));
         WriteByte(MSG_BROADCAST, min(ceil(CS(e).ping_packetloss * 255), 255));
         WriteByte(MSG_BROADCAST, min(ceil(CS(e).ping_movementloss * 255), 255));
         // record latency times for clients throughout the match so we can report it to playerstats
         if(time > (CS(e).latency_time + LATENCY_THINKRATE))
         {
             CS(e).latency_sum += CS(e).ping;
             CS(e).latency_cnt += 1;
             CS(e).latency_time = time;
             //print("sum: ", ftos(CS(e).latency_sum), ", cnt: ", ftos(CS(e).latency_cnt), ", avg: ", ftos(CS(e).latency_sum / CS(e).latency_cnt), ".\n");
         }
     }
     else
     {
         WriteHeader(MSG_BROADCAST, TE_CSQC_PINGPLREPORT);
         WriteByte(MSG_BROADCAST, this.cnt);
         WriteShort(MSG_BROADCAST, 0);
         WriteByte(MSG_BROADCAST, 0);
         WriteByte(MSG_BROADCAST, 0);
     }
     this.cnt = (this.cnt + 1) % maxclients;
 }
RandomSeed_Send()
bool RandomSeed_Send (entity this, entity to, int sf)
Definition at line 562 of file world.qc.
References cnt, and WriteShort().
Referenced by RandomSeed_Spawn().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_RANDOMSEED);
     WriteShort(MSG_ENTITY, this.cnt);
     return true;
 }
RandomSeed_Spawn()
void RandomSeed_Spawn ()
Definition at line 575 of file world.qc.
References getthink, new_pure, randomseed, RandomSeed_Send(), RandomSeed_Think(), and setthink.
Referenced by spawnfunc().
 {
     randomseed = new_pure(randomseed);
     setthink(randomseed, RandomSeed_Think);
     Net_LinkEntity(randomseed, false, 0, RandomSeed_Send);
     getthink(randomseed)(randomseed); // sets random seed and nextthink
 }
RandomSeed_Think()
void RandomSeed_Think (entity this)
Definition at line 568 of file world.qc.
References bound(), cnt, floor(), nextthink, random(), and time.
Referenced by RandomSeed_Spawn().
 {
     this.cnt = bound(0, floor(random() * 65536), 65535);
     this.nextthink = time + 5;
     this.SendFlags |= 1;
 }
readlevelcvars()
void readlevelcvars ()
Definition at line 2042 of file world.qc.
References cvar(), FOREACH, g_pickup_cells_max, g_pickup_fuel_max, g_pickup_nails_max, g_pickup_plasma_max, g_pickup_rockets_max, g_pickup_shells_max, g_pickup_weapons_anyway, g_weapon_stay, GetGametype(), MUTATOR_CALLHOOK, readplayerstartcvars(), SERVERFLAG_ALLOW_FULLBRIGHT, serverflags, strcat(), sv_ready_restart_after_countdown, time, and warmup_stage.
Referenced by spawnfunc().
 {
     if(cvar("sv_allow_fullbright"))
         serverflags |= SERVERFLAG_ALLOW_FULLBRIGHT;
     sv_ready_restart_after_countdown = cvar("sv_ready_restart_after_countdown");
     warmup_stage = cvar("g_warmup");
     warmup_limit = cvar("g_warmup_limit");
     if(cvar("g_campaign"))
         warmup_stage = 0; // no warmup during campaign
     g_pickup_respawntime_weapon = cvar("g_pickup_respawntime_weapon");
     g_pickup_respawntime_superweapon = cvar("g_pickup_respawntime_superweapon");
     g_pickup_respawntime_ammo = cvar("g_pickup_respawntime_ammo");
     g_pickup_respawntime_short = cvar("g_pickup_respawntime_short");
     g_pickup_respawntime_medium = cvar("g_pickup_respawntime_medium");
     g_pickup_respawntime_long = cvar("g_pickup_respawntime_long");
     g_pickup_respawntime_powerup = cvar("g_pickup_respawntime_powerup");
     g_pickup_respawntimejitter_weapon = cvar("g_pickup_respawntimejitter_weapon");
     g_pickup_respawntimejitter_superweapon = cvar("g_pickup_respawntimejitter_superweapon");
     g_pickup_respawntimejitter_ammo = cvar("g_pickup_respawntimejitter_ammo");
     g_pickup_respawntimejitter_short = cvar("g_pickup_respawntimejitter_short");
     g_pickup_respawntimejitter_medium = cvar("g_pickup_respawntimejitter_medium");
     g_pickup_respawntimejitter_long = cvar("g_pickup_respawntimejitter_long");
     g_pickup_respawntimejitter_powerup = cvar("g_pickup_respawntimejitter_powerup");
     g_pickup_shells = cvar("g_pickup_shells");
     g_pickup_shells_max = cvar("g_pickup_shells_max");
     g_pickup_nails = cvar("g_pickup_nails");
     g_pickup_nails_max = cvar("g_pickup_nails_max");
     g_pickup_rockets = cvar("g_pickup_rockets");
     g_pickup_rockets_max = cvar("g_pickup_rockets_max");
     g_pickup_cells = cvar("g_pickup_cells");
     g_pickup_cells_max = cvar("g_pickup_cells_max");
     g_pickup_plasma = cvar("g_pickup_plasma");
     g_pickup_plasma_max = cvar("g_pickup_plasma_max");
     g_pickup_fuel = cvar("g_pickup_fuel");
     g_pickup_fuel_jetpack = cvar("g_pickup_fuel_jetpack");
     g_pickup_fuel_max = cvar("g_pickup_fuel_max");
     g_pickup_armorsmall = cvar("g_pickup_armorsmall");
     g_pickup_armorsmall_max = cvar("g_pickup_armorsmall_max");
     g_pickup_armorsmall_anyway = cvar("g_pickup_armorsmall_anyway");
     g_pickup_armormedium = cvar("g_pickup_armormedium");
     g_pickup_armormedium_max = cvar("g_pickup_armormedium_max");
     g_pickup_armormedium_anyway = cvar("g_pickup_armormedium_anyway");
     g_pickup_armorbig = cvar("g_pickup_armorbig");
     g_pickup_armorbig_max = cvar("g_pickup_armorbig_max");
     g_pickup_armorbig_anyway = cvar("g_pickup_armorbig_anyway");
     g_pickup_armormega = cvar("g_pickup_armormega");
     g_pickup_armormega_max = cvar("g_pickup_armormega_max");
     g_pickup_armormega_anyway = cvar("g_pickup_armormega_anyway");
     g_pickup_healthsmall = cvar("g_pickup_healthsmall");
     g_pickup_healthsmall_max = cvar("g_pickup_healthsmall_max");
     g_pickup_healthsmall_anyway = cvar("g_pickup_healthsmall_anyway");
     g_pickup_healthmedium = cvar("g_pickup_healthmedium");
     g_pickup_healthmedium_max = cvar("g_pickup_healthmedium_max");
     g_pickup_healthmedium_anyway = cvar("g_pickup_healthmedium_anyway");
     g_pickup_healthbig = cvar("g_pickup_healthbig");
     g_pickup_healthbig_max = cvar("g_pickup_healthbig_max");
     g_pickup_healthbig_anyway = cvar("g_pickup_healthbig_anyway");
     g_pickup_healthmega = cvar("g_pickup_healthmega");
     g_pickup_healthmega_max = cvar("g_pickup_healthmega_max");
     g_pickup_healthmega_anyway = cvar("g_pickup_healthmega_anyway");
     g_pickup_ammo_anyway = cvar("g_pickup_ammo_anyway");
     g_pickup_weapons_anyway = cvar("g_pickup_weapons_anyway");
     g_weapon_stay = cvar(strcat("g_", GetGametype(), "_weapon_stay"));
     if(!g_weapon_stay)
         g_weapon_stay = cvar("g_weapon_stay");
     MUTATOR_CALLHOOK(ReadLevelCvars);
     if (!warmup_stage)
         game_starttime = time + cvar("g_start_delay");
     FOREACH(Weapons, it != WEP_Null, { it.wr_init(it); });
     readplayerstartcvars();
 }
readplayerstartcvars()
void readplayerstartcvars ()
Definition at line 1822 of file world.qc.
References argv(), autocvar_g_jetpack, autocvar_g_warmup_allguns, cvar(), cvar_string(), FOREACH, g_weapon_stay, g_weaponarena, g_weaponarena_list, g_weaponarena_weapons, GetResource(), InitializeEntity(), M_ARGV, Weapon::m_name, max(), MUTATOR_CALLHOOK, new_pure, NULL, random_start_ammo, random_start_weapons_count, RES_BULLETS, RES_CELLS, RES_PLASMA, RES_ROCKETS, RES_SHELLS, SetResource(), start_ammo_cells, start_ammo_fuel, start_ammo_nails, start_ammo_plasma, start_ammo_rockets, start_ammo_shells, start_armorvalue, start_health, start_items, start_weapons, start_weapons_default, start_weapons_defaultmask, strcat(), strlen(), strzone(), substring(), tokenize_console, want_weapon(), warmup_start_ammo_cells, warmup_start_ammo_fuel, warmup_start_ammo_nails, warmup_start_ammo_plasma, warmup_start_ammo_rockets, warmup_start_ammo_shells, warmup_start_armorvalue, warmup_start_health, warmup_start_weapons, warmup_start_weapons_default, warmup_start_weapons_defaultmask, Weapon_from_name(), weaponarena_available_all_update(), weaponarena_available_devall_update(), weaponarena_available_most_update(), weapons_all(), weapons_devall(), and weapons_most().
Referenced by readlevelcvars().
 {
     // initialize starting values for players
     start_weapons = '0 0 0';
     start_weapons_default = '0 0 0';
     start_weapons_defaultmask = '0 0 0';
     start_items = 0;
     start_ammo_shells = 0;
     start_ammo_nails = 0;
     start_ammo_rockets = 0;
     start_ammo_cells = 0;
     start_ammo_plasma = 0;
     if (random_start_ammo == NULL)
     {
         random_start_ammo = new_pure(random_start_ammo);
     }
     start_health = cvar("g_balance_health_start");
     start_armorvalue = cvar("g_balance_armor_start");
     g_weaponarena = 0;
     g_weaponarena_weapons = '0 0 0';
     string s = cvar_string("g_weaponarena");
     MUTATOR_CALLHOOK(SetWeaponArena, s);
     s = M_ARGV(0, string);
     if (s == "0" || s == "")
     {
         // no arena
     }
     else if (s == "off")
     {
         // forcibly turn off weaponarena
     }
     else if (s == "all" || s == "1")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "All Weapons";
         g_weaponarena_weapons = weapons_all();
     }
     else if (s == "devall")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Dev All Weapons";
         g_weaponarena_weapons = weapons_devall();
     }
     else if (s == "most")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Most Weapons";
         g_weaponarena_weapons = weapons_most();
     }
     else if (s == "all_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "All Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_all_update, INITPRIO_FINDTARGET);
     }
     else if (s == "devall_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Dev All Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_devall_update, INITPRIO_FINDTARGET);
     }
     else if (s == "most_available")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "Most Available Weapons";
         // this needs to run after weaponsInMapAll is initialized
         InitializeEntity(NULL, weaponarena_available_most_update, INITPRIO_FINDTARGET);
     }
     else if (s == "none")
     {
         g_weaponarena = 1;
         g_weaponarena_list = "No Weapons";
     }
     else
     {
         g_weaponarena = 1;
         float t = tokenize_console(s);
         g_weaponarena_list = "";
         for (int j = 0; j < t; ++j)
         {
             s = argv(j);
             Weapon wep = Weapon_from_name(s);
             if(wep != WEP_Null)
             {
                 g_weaponarena_weapons |= (wep.m_wepset);
                 g_weaponarena_list = strcat(g_weaponarena_list, wep.m_name, " & ");
             }
         }
         g_weaponarena_list = strzone(substring(g_weaponarena_list, 0, strlen(g_weaponarena_list) - 3));
     }
     if (g_weaponarena)
     {
         g_weapon_stay = 0; // incompatible
         start_weapons = g_weaponarena_weapons;
         start_items |= IT_UNLIMITED_AMMO | IT_UNLIMITED_SUPERWEAPONS;
     }
     else
     {
         FOREACH(Weapons, it != WEP_Null, {
             int w = want_weapon(it, false);
             WepSet s = it.m_wepset;
             if(w & 1)
                 start_weapons |= s;
             if(w & 2)
                 start_weapons_default |= s;
             if(w & 4)
                 start_weapons_defaultmask |= s;
         });
     }
     if(cvar("g_balance_superweapons_time") < 0)
         start_items |= IT_UNLIMITED_SUPERWEAPONS;
     if(!cvar("g_use_ammunition"))
         start_items |= IT_UNLIMITED_AMMO;
     if(start_items & IT_UNLIMITED_AMMO)
     {
         start_ammo_shells = 999;
         start_ammo_nails = 999;
         start_ammo_rockets = 999;
         start_ammo_cells = 999;
         start_ammo_plasma = 999;
         start_ammo_fuel = 999;
     }
     else
     {
         start_ammo_shells = cvar("g_start_ammo_shells");
         start_ammo_nails = cvar("g_start_ammo_nails");
         start_ammo_rockets = cvar("g_start_ammo_rockets");
         start_ammo_cells = cvar("g_start_ammo_cells");
         start_ammo_plasma = cvar("g_start_ammo_plasma");
         start_ammo_fuel = cvar("g_start_ammo_fuel");
         random_start_weapons_count = cvar("g_random_start_weapons_count");
         SetResource(random_start_ammo, RES_SHELLS, cvar("g_random_start_shells"));
         SetResource(random_start_ammo, RES_BULLETS, cvar("g_random_start_bullets"));
         SetResource(random_start_ammo, RES_ROCKETS, cvar("g_random_start_rockets"));
         SetResource(random_start_ammo, RES_CELLS, cvar("g_random_start_cells"));
         SetResource(random_start_ammo, RES_PLASMA, cvar("g_random_start_plasma"));
     }
     warmup_start_ammo_shells = start_ammo_shells;
     warmup_start_ammo_nails = start_ammo_nails;
     warmup_start_ammo_rockets = start_ammo_rockets;
     warmup_start_ammo_cells = start_ammo_cells;
     warmup_start_ammo_plasma = start_ammo_plasma;
     warmup_start_ammo_fuel = start_ammo_fuel;
     warmup_start_health = start_health;
     warmup_start_armorvalue = start_armorvalue;
     warmup_start_weapons = start_weapons;
     warmup_start_weapons_default = start_weapons_default;
     warmup_start_weapons_defaultmask = start_weapons_defaultmask;
     if (!g_weaponarena)
     {
         warmup_start_ammo_shells = cvar("g_warmup_start_ammo_shells");
         warmup_start_ammo_nails = cvar("g_warmup_start_ammo_nails");
         warmup_start_ammo_rockets = cvar("g_warmup_start_ammo_rockets");
         warmup_start_ammo_cells = cvar("g_warmup_start_ammo_cells");
         warmup_start_ammo_plasma = cvar("g_warmup_start_ammo_plasma");
         warmup_start_ammo_fuel = cvar("g_warmup_start_ammo_fuel");
         warmup_start_health = cvar("g_warmup_start_health");
         warmup_start_armorvalue = cvar("g_warmup_start_armor");
         warmup_start_weapons = '0 0 0';
         warmup_start_weapons_default = '0 0 0';
         warmup_start_weapons_defaultmask = '0 0 0';
         FOREACH(Weapons, it != WEP_Null, {
             int w = want_weapon(it, autocvar_g_warmup_allguns);
             WepSet s = it.m_wepset;
             if(w & 1)
                 warmup_start_weapons |= s;
             if(w & 2)
                 warmup_start_weapons_default |= s;
             if(w & 4)
                 warmup_start_weapons_defaultmask |= s;
         });
     }
     if (autocvar_g_jetpack)
         start_items |= ITEM_Jetpack.m_itemid;
     MUTATOR_CALLHOOK(SetStartItems);
     if (start_items & ITEM_Jetpack.m_itemid)
     {
         start_items |= ITEM_JetpackRegen.m_itemid;
         start_ammo_fuel = max(start_ammo_fuel, cvar("g_balance_fuel_rotstable"));
         warmup_start_ammo_fuel = max(warmup_start_ammo_fuel, cvar("g_balance_fuel_rotstable"));
     }
     start_ammo_shells = max(0, start_ammo_shells);
     start_ammo_nails = max(0, start_ammo_nails);
     start_ammo_rockets = max(0, start_ammo_rockets);
     start_ammo_cells = max(0, start_ammo_cells);
     start_ammo_plasma = max(0, start_ammo_plasma);
     start_ammo_fuel = max(0, start_ammo_fuel);
     SetResource(random_start_ammo, RES_SHELLS, max(0, GetResource(random_start_ammo, RES_SHELLS)));
     SetResource(random_start_ammo, RES_BULLETS, max(0, GetResource(random_start_ammo, RES_BULLETS)));
     SetResource(random_start_ammo, RES_ROCKETS, max(0, GetResource(random_start_ammo, RES_ROCKETS)));
     SetResource(random_start_ammo, RES_CELLS, max(0, GetResource(random_start_ammo, RES_CELLS)));
     SetResource(random_start_ammo, RES_PLASMA, max(0, GetResource(random_start_ammo, RES_PLASMA)));
     warmup_start_ammo_shells = max(0, warmup_start_ammo_shells);
     warmup_start_ammo_nails = max(0, warmup_start_ammo_nails);
     warmup_start_ammo_rockets = max(0, warmup_start_ammo_rockets);
     warmup_start_ammo_cells = max(0, warmup_start_ammo_cells);
     warmup_start_ammo_plasma = max(0, warmup_start_ammo_plasma);
     warmup_start_ammo_fuel = max(0, warmup_start_ammo_fuel);
 }
RedirectionThink()
float RedirectionThink ()
Definition at line 2327 of file world.qc.
References autocvar_quit_and_redirect_timer, bprint(), cvar_set(), FOREACH_CLIENT, ftos(), IS_REAL_CLIENT, localcmd, LOG_INFO, redirection_target, strcat(), stuffcmd, and time.
Referenced by StartFrame().
 {
     float clients_found;
     if(redirection_target == "")
         return false;
     if(!redirection_timeout)
     {
         cvar_set("sv_public", "-2");
         redirection_timeout = time + 0.6; // this will only try twice... should be able to keep more clients
         if(redirection_target == "self")
             bprint("^3SERVER NOTICE:^7 restarting the server\n");
         else
             bprint("^3SERVER NOTICE:^7 redirecting everyone to ", redirection_target, "\n");
     }
     if(time < redirection_nextthink)
         return true;
     redirection_nextthink = time + 1;
     clients_found = 0;
     FOREACH_CLIENT(IS_REAL_CLIENT(it), {
         // TODO add timer
         LOG_INFO("Redirecting: sending connect command to ", it.netname);
         if(redirection_target == "self")
             stuffcmd(it, "\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " reconnect\n");
         else
             stuffcmd(it, strcat("\ndisconnect; defer ", ftos(autocvar_quit_and_redirect_timer), " \"connect ", redirection_target, "\"\n"));
         ++clients_found;
     });
     LOG_INFO("Redirecting: ", ftos(clients_found), " clients left.");
     if(time > redirection_timeout || clients_found == 0)
         localcmd("\nwait; wait; wait; quit\n");
     return true;
 }
RestoreGame()
void RestoreGame ()
Definition at line 2368 of file world.qc.
References autocvar_sessionid, db_load(), MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), MapInfo_Shutdown(), ServerProgsDB, strcat(), and WeaponStats_Init().
 {
     // Loaded from a save game
     // some things then break, so let's work around them...
     // Progs DB (capture records)
     ServerProgsDB = db_load(strcat("server.db", autocvar_sessionid));
     // Mapinfo
     MapInfo_Shutdown();
     MapInfo_Enumerate();
     MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1);
     WeaponStats_Init();
     TargetMusic_RestoreGame();
 }
RunThink()
void RunThink (entity this)
Definition at line 2209 of file world.qc.
References frametime, getthink, max(), nextthink, and time.
 {
     // don't let things stay in the past.
     // it is possible to start that way by a trigger with a local time.
     if(this.nextthink <= 0 || this.nextthink > time + frametime)
         return;
     float oldtime = time; // do we need to save this?
     for (int iterations = 0; iterations < 128 && !wasfreed(this); iterations++)
     {
         time = max(oldtime, this.nextthink);
         this.nextthink = 0;
         if(getthink(this))
             getthink(this)(this);
         // mods often set nextthink to time to cause a think every frame,
         // we don't want to loop in that case, so exit if the new nextthink is
         // <= the time the qc was told, also exit if it is past the end of the
         // frame
         if(this.nextthink <= time || this.nextthink > oldtime + frametime || !autocvar_sv_gameplayfix_multiplethinksperframe)
             break;
     }
     time = oldtime;
 }
SetDefaultAlpha()
void SetDefaultAlpha ()
Definition at line 104 of file world.qc.
References autocvar_g_player_alpha, default_player_alpha, default_weapon_alpha, and MUTATOR_CALLHOOK.
Referenced by CheckRules_World(), and spawnfunc().
 {
     if (!MUTATOR_CALLHOOK(SetDefaultAlpha))
     {
         default_player_alpha = autocvar_g_player_alpha;
         if(default_player_alpha == 0)
             default_player_alpha = 1;
         default_weapon_alpha = default_player_alpha;
     }
 }
SetWinners()
void SetWinners (.float field, float value)
Definition at line 1385 of file world.qc.
References FOREACH_CLIENT, and IS_PLAYER.
Referenced by WinningCondition_Assault(), WinningCondition_Invasion(), WinningCondition_LMS(), and WinningCondition_Scores().
 {
     FOREACH_CLIENT(IS_PLAYER(it), { it.winning = (it.(field) == value); });
 }
Shutdown()
void Shutdown ()
Definition at line 2385 of file world.qc.
References __init_dedicated_server_shutdown(), autocvar_chase_active, autocvar_cl_db_saveasdump, autocvar_developer, autocvar_r_drawviewmodel, autocvar_sessionid, autocvar_sv_db_saveasdump, Ban_SaveBans(), binddb, bot_endgame(), calledhooks, camera_active, chase_active_backup, cheatcount_total, CheatShutdown(), ClientProgsDB, cvar_defstring(), cvar_set(), db_close(), db_dump(), db_save(), deactivate_minigame(), ftos(), HOOK_END, HOOK_START, HUD_MinigameMenu_Close(), isdemo(), localcmd, LOG_INFO, LOG_TRACE, MapInfo_Shutdown(), NULL, orig_slowmo, players, ServerProgsDB, strcat(), teams, tempdb, TemporaryDB, TIMEOUT_ACTIVE, timeout_status, WarpZone_Shutdown(), WeaponStats_Shutdown(), and world_initialized.
 {
     game_stopped = 2;
     if(world_initialized > 0)
     {
         world_initialized = 0;
         // if a timeout is active, reset the slowmo value to normal
         if(timeout_status == TIMEOUT_ACTIVE)
             cvar_set("slowmo", ftos(orig_slowmo));
         LOG_TRACE("Saving persistent data...");
         Ban_SaveBans();
         // playerstats with unfinished match
         PlayerStats_GameReport(false);
         if(!cheatcount_total)
         {
             if(autocvar_sv_db_saveasdump)
                 db_dump(ServerProgsDB, strcat("server.db", autocvar_sessionid));
             else
                 db_save(ServerProgsDB, strcat("server.db", autocvar_sessionid));
         }
         if(autocvar_developer > 0)
         {
             if(autocvar_sv_db_saveasdump)
                 db_dump(TemporaryDB, "server-temp.db");
             else
                 db_save(TemporaryDB, "server-temp.db");
         }
         CheatShutdown(); // must be after cheatcount check
         db_close(ServerProgsDB);
         db_close(TemporaryDB);
         LOG_TRACE("Saving persistent data... done!");
         // tell the bot system the game is ending now
         bot_endgame();
         WeaponStats_Shutdown();
         MapInfo_Shutdown();
     }
     else if(world_initialized == 0)
     {
         LOG_INFO("NOTE: crashed before even initializing the world, not saving persistent data");
     }
     else
     {
         __init_dedicated_server_shutdown();
     }
 }
spawnfunc() [1/3]
spawnfunc (__init_dedicated_server)
Definition at line 584 of file world.qc.
References delete_fn(), entity(), g_spawnpoints, GotoFirstMap(), IL_PUSH(), MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), remove_unsafely(), setthink, static_init, static_init_late, static_init_precache, time, and world_initialized.
 {
     // handler for _init/_init map (only for dedicated server initialization)
     world_initialized = -1; // don't complain
     delete_fn = remove_unsafely;
     entity e = new(GotoFirstMap);
     setthink(e, GotoFirstMap);
     e.nextthink = time; // this is usually 1 at this point
     e = new(info_player_deathmatch);  // safeguard against player joining
     // assign reflectively to avoid "assignment to world" warning
     for (int i = 0, n = numentityfields(); i < n; ++i) {
         string k = entityfieldname(i);
         if (k == "classname") {
             // safeguard against various stuff ;)
             putentityfieldstring(i, this, "worldspawn");
             break;
         }
     }
     // needs to be done so early because of the constants they create
     static_init();
     static_init_late();
     static_init_precache();
     IL_PUSH(g_spawnpoints, e); // just incase
     MapInfo_Enumerate();
     MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 0);
 }
spawnfunc() [2/3]
spawnfunc (worldspawn)
Definition at line 685 of file world.qc.
References argv(), autocvar_g_campaign, autocvar_g_norecoil, autocvar_g_pickup_items, autocvar_g_powerups, autocvar_g_use_ammunition, autocvar_g_waypoints_for_items, autocvar_g_weaponarena, autocvar_sessionid, autocvar_sv_curl_serverpackages_auto, autocvar_sv_eventlog, autocvar_sv_eventlog_files_counter, Ban_LoadBans(), boolean, bot_waypoints_for_items, CampaignPostInit(), CampaignPreInit(), changelevel(), CheatInit(), ClientInit_Spawn(), clientstuff, cons(), cvar_changes_init(), cvar_defstring(), cvar_set(), cvar_settemp(), cvar_string(), cvar_value_issafe(), db_create(), db_load(), delete_fn(), endsWith, error(), fclose(), fexists(), fgets(), FILE_READ, floor(), fopen(), ftos(), GameLogEcho(), GameLogInit(), GameRules_limit_fallbacks(), GetGametype(), getladder(), getlsmaps(), getmaplist(), GetMapname(), getmonsterlist(), getrankings(), getrecords(), InitGameplayMode(), itos, localcmd, LOG_INFO, LOG_INFOF, M_ARGV, Map_MarkAsRecent(), MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_Enumerate(), MapInfo_FilterGametype(), MapInfo_ForbiddenFlags(), MapInfo_RequiredFlags(), mapname, matchid, modname, MUTATOR_CALLHOOK, Nagger_Init(), PingPLReport_Spawn(), player_count, random(), RandomSeed_Spawn(), readlevelcvars(), remove_safely(), server_is_dedicated, ServerProgsDB, SetDefaultAlpha(), SPAWNFLAG_NO_WAYPOINTS_FOR_ITEMS, spawnflags, startsWith, static_init, static_init_late, static_init_precache, stof(), strcat(), strcpy, strzone(), TemporaryDB, tokenize_console, WeaponStats_Init(), WinningConditionHelper(), world_already_spawned, world_initialized, and X.
 {
     server_is_dedicated = boolean(stof(cvar_defstring("is_dedicated")));
     bool wantrestart = false;
     {
         if (!server_is_dedicated)
         {
             // force unloading of server pk3 files when starting a listen server
             // localcmd("\nfs_rescan\n"); // FIXME: does more harm than good, has unintended side effects. What we really want is to unload temporary pk3s only
             // restore csqc_progname too
             string expect = "csprogs.dat";
             wantrestart = cvar_string("csqc_progname") != expect;
             cvar_set("csqc_progname", expect);
         }
         else
         {
             // Try to use versioned csprogs from pk3
             // Only ever use versioned csprogs.dat files on dedicated servers;
             // we need to reset csqc_progname on clients ourselves, and it's easier if the client's release name is constant
             string pk3csprogs = "csprogs-" WATERMARK ".dat";
             // This always works; fall back to it if a versioned csprogs.dat is suddenly missing
             string select = "csprogs.dat";
             if (fexists(pk3csprogs)) select = pk3csprogs;
             if (cvar_string("csqc_progname") != select)
             {
                 cvar_set("csqc_progname", select);
                 wantrestart = true;
             }
             // Check for updates on startup
             // We do it this way for atomicity so that connecting clients still match the server progs and don't disconnect
             int sentinel = fopen("progs.txt", FILE_READ);
             if (sentinel >= 0)
             {
                 string switchversion = fgets(sentinel);
                 fclose(sentinel);
                 if (switchversion != "" && switchversion != WATERMARK)
                 {
                     LOG_INFOF("Switching progs: " WATERMARK " -> %s", switchversion);
                     // if it doesn't exist, assume either:
                     //   a) the current program was overwritten
                     //   b) this is a client only update
                     string newprogs = sprintf("progs-%s.dat", switchversion);
                     if (fexists(newprogs))
                     {
                         cvar_set("sv_progs", newprogs);
                         wantrestart = true;
                     }
                     string newcsprogs = sprintf("csprogs-%s.dat", switchversion);
                     if (fexists(newcsprogs))
                     {
                         cvar_set("csqc_progname", newcsprogs);
                         wantrestart = true;
                     }
                 }
             }
         }
         if (wantrestart)
         {
             LOG_INFO("Restart requested");
             changelevel(mapname);
             // let initialization continue, shutdown depends on it
         }
     }
     if(world_already_spawned)
         error("world already spawned - you may have EXACTLY ONE worldspawn!");
     world_already_spawned = true;
     delete_fn = remove_safely; // during spawning, watch what you remove!
     cvar_changes_init(); // do this very early now so it REALLY matches the server config
     // needs to be done so early because of the constants they create
     static_init();
     ServerProgsDB = db_load(strcat("server.db", autocvar_sessionid));
     TemporaryDB = db_create();
     // 0 normal
     lightstyle(0, "m");
     // 1 FLICKER (first variety)
     lightstyle(1, "mmnmmommommnonmmonqnmmo");
     // 2 SLOW STRONG PULSE
     lightstyle(2, "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba");
     // 3 CANDLE (first variety)
     lightstyle(3, "mmmmmaaaaammmmmaaaaaabcdefgabcdefg");
     // 4 FAST STROBE
     lightstyle(4, "mamamamamama");
     // 5 GENTLE PULSE 1
     lightstyle(5,"jklmnopqrstuvwxyzyxwvutsrqponmlkj");
     // 6 FLICKER (second variety)
     lightstyle(6, "nmonqnmomnmomomno");
     // 7 CANDLE (second variety)
     lightstyle(7, "mmmaaaabcdefgmmmmaaaammmaamm");
     // 8 CANDLE (third variety)
     lightstyle(8, "mmmaaammmaaammmabcdefaaaammmmabcdefmmmaaaa");
     // 9 SLOW STROBE (fourth variety)
     lightstyle(9, "aaaaaaaazzzzzzzz");
     // 10 FLUORESCENT FLICKER
     lightstyle(10, "mmamammmmammamamaaamammma");
     // 11 SLOW PULSE NOT FADE TO BLACK
     lightstyle(11, "abcdefghijklmnopqrrqponmlkjihgfedcba");
     // styles 32-62 are assigned by the spawnfunc_light program for switchable lights
     // 63 testing
     lightstyle(63, "a");
     if(autocvar_g_campaign)
         CampaignPreInit();
     Map_MarkAsRecent(mapname);
     PlayerStats_GameReport_Init(); // we need this to be initiated before InitGameplayMode
     InitGameplayMode();
     static_init_late();
     static_init_precache();
     readlevelcvars();
     GameRules_limit_fallbacks();
     if(warmup_limit == 0)
         warmup_limit = (autocvar_timelimit > 0) ? autocvar_timelimit * 60 : autocvar_timelimit;
     player_count = 0;
     bot_waypoints_for_items = autocvar_g_waypoints_for_items;
     if(bot_waypoints_for_items == 1)
         if(this.spawnflags & SPAWNFLAG_NO_WAYPOINTS_FOR_ITEMS)
             bot_waypoints_for_items = 0;
     WaypointSprite_Init();
     GameLogInit(); // prepare everything
     // NOTE for matchid:
     // changing the logic generating it is okay. But:
     // it HAS to stay <= 64 chars
     // character set: ASCII 33-126 without the following characters: : ; ' " \ $
     if(autocvar_sv_eventlog)
     {
         string s = sprintf("%s.%s.%06d", itos(autocvar_sv_eventlog_files_counter), strftime(false, "%s"), floor(random() * 1000000));
         matchid = strzone(s);
         GameLogEcho(strcat(":gamestart:", GetGametype(), "_", GetMapname(), ":", s));
         s = ":gameinfo:mutators:LIST";
         MUTATOR_CALLHOOK(BuildMutatorsString, s);
         s = M_ARGV(0, string);
         // initialiation stuff, not good in the mutator system
         if(!autocvar_g_use_ammunition)
             s = strcat(s, ":no_use_ammunition");
         // initialiation stuff, not good in the mutator system
         if(autocvar_g_pickup_items == 0)
             s = strcat(s, ":no_pickup_items");
         if(autocvar_g_pickup_items > 0)
             s = strcat(s, ":pickup_items");
         // initialiation stuff, not good in the mutator system
         if(autocvar_g_weaponarena != "0")
             s = strcat(s, ":", autocvar_g_weaponarena, " arena");
         // TODO to mutator system
         if(autocvar_g_norecoil)
             s = strcat(s, ":norecoil");
         // TODO to mutator system
         if(autocvar_g_powerups == 0)
             s = strcat(s, ":no_powerups");
         if(autocvar_g_powerups > 0)
             s = strcat(s, ":powerups");
         GameLogEcho(s);
         GameLogEcho(":gameinfo:end");
     }
     else
         matchid = strzone(ftos(random()));
     cvar_set("nextmap", "");
     SetDefaultAlpha();
     if(autocvar_g_campaign)
         CampaignPostInit();
     Ban_LoadBans();
     MapInfo_Enumerate();
     MapInfo_FilterGametype(MapInfo_CurrentGametype(), MapInfo_CurrentFeatures(), MapInfo_RequiredFlags(), MapInfo_ForbiddenFlags(), 1);
     if(fexists(strcat("scripts/", mapname, ".arena")))
         cvar_settemp("sv_q3acompat_machineshotgunswap", "1");
     if(fexists(strcat("scripts/", mapname, ".defi")))
         cvar_settemp("sv_q3defragcompat", "1");
     if(whichpack(strcat("maps/", mapname, ".cfg")) != "")
     {
         int fd = fopen(strcat("maps/", mapname, ".cfg"), FILE_READ);
         if(fd != -1)
         {
             string s;
             while((s = fgets(fd)))
             {
                 int l = tokenize_console(s);
                 if(l < 2)
                     continue;
                 if(argv(0) == "cd")
                 {
                     string trackname = argv(2);
                     LOG_INFO("Found ^1UNSUPPORTED^7 cd loop command in .cfg file; put this line in mapinfo instead:");
                     LOG_INFO("  cdtrack ", trackname);
                     if (cvar_value_issafe(trackname))
                     {
                         string newstuff = strcat(clientstuff, "cd loop \"", trackname, "\"\n");
                         strcpy(clientstuff, newstuff);
                     }
                 }
                 else if(argv(0) == "fog")
                 {
                     LOG_INFO("Found ^1UNSUPPORTED^7 fog command in .cfg file; put this line in worldspawn in the .map/.bsp/.ent file instead:");
                     LOG_INFO("  \"fog\" \"", s, "\"");
                 }
                 else if(argv(0) == "set")
                 {
                     LOG_INFO("Found ^1UNSUPPORTED^7 set command in .cfg file; put this line in mapinfo instead:");
                     LOG_INFO("  clientsettemp_for_type all ", argv(1), " ", argv(2));
                 }
                 else if(argv(0) != "//")
                 {
                     LOG_INFO("Found ^1UNSUPPORTED^7 set command in .cfg file; put this line in mapinfo instead:");
                     LOG_INFO("  clientsettemp_for_type all ", argv(0), " ", argv(1));
                 }
             }
             fclose(fd);
         }
     }
     WeaponStats_Init();
     Nagger_Init();
     // set up information replies for clients and server to use
     maplist_reply = strzone(getmaplist());
     lsmaps_reply = strzone(getlsmaps());
     monsterlist_reply = strzone(getmonsterlist());
     bool records_available = false;
     for(int i = 0; i < 10; ++i)
     {
         string s = getrecords(i);
         if (s != "")
         {
             records_reply[i] = strzone(s);
             records_available = true;
         }
     }
     if (!records_available)
         records_reply[0] = "No records available for the current game mode.\n";
     ladder_reply = strzone(getladder());
     rankings_reply = strzone(getrankings());
     // begin other init
     ClientInit_Spawn();
     RandomSeed_Spawn();
     PingPLReport_Spawn();
     CheatInit();
     if (!wantrestart) localcmd("\n_sv_hook_gamestart ", GetGametype(), "\n");
     // fill sv_curl_serverpackages from .serverpackage files
     if (autocvar_sv_curl_serverpackages_auto)
     {
         string s = "csprogs-" WATERMARK ".dat";
         // remove automatically managed files from the list to prevent duplicates
         for (int i = 0, n = tokenize_console(cvar_string("sv_curl_serverpackages")); i < n; ++i)
         {
             string pkg = argv(i);
             if (startsWith(pkg, "csprogs-")) continue;
             if (endsWith(pkg, "-serverpackage.txt")) continue;
             if (endsWith(pkg, ".serverpackage")) continue;  // OLD legacy
             s = cons(s, pkg);
         }
         // add automatically managed files to the list
         #define X(match) MACRO_BEGIN \
             int fd = search_begin(match, true, false); \
             if (fd >= 0) \
             { \
                 for (int i = 0, j = search_getsize(fd); i < j; ++i) \
                 { \
                     s = cons(s, search_getfilename(fd, i)); \
                 } \
                 search_end(fd); \
             } \
         MACRO_END
         X("*-serverpackage.txt");
         X("*.serverpackage");
         #undef X
         cvar_set("sv_curl_serverpackages", s);
     }
     // MOD AUTHORS: change this, and possibly remove a few of the blocks below to ignore certain changes
     modname = "Xonotic";
     // physics/balance/config changes that count as mod
     if(cvar_string("g_mod_physics") != cvar_defstring("g_mod_physics"))
         modname = cvar_string("g_mod_physics");
     if(cvar_string("g_mod_balance") != cvar_defstring("g_mod_balance") && cvar_string("g_mod_balance") != "Testing")
         modname = cvar_string("g_mod_balance");
     if(cvar_string("g_mod_config") != cvar_defstring("g_mod_config"))
         modname = cvar_string("g_mod_config");
     // extra mutators that deserve to count as mod
     MUTATOR_CALLHOOK(SetModname, modname);
     modname = M_ARGV(0, string);
     // save it for later
     modname = strzone(modname);
     WinningConditionHelper(this); // set worldstatus
     world_initialized = 1;
     __spawnfunc_spawn_all();
 }
spawnfunc() [3/3]
spawnfunc (light)
Definition at line 1022 of file world.qc.
 {
     //makestatic (this); // Who the f___ did that?
     delete(this);
 }
STATIC_INIT_EARLY()
STATIC_INIT_EARLY (maxclients)
Definition at line 623 of file world.qc.
References entity(), maxclients, nextent(), and NULL.
 {
     maxclients = 0;
     for (entity head = nextent(NULL); head; head = nextent(head)) {
         ++maxclients;
     }
 }
systems_update()
void systems_update ()
Definition at line 7 of file main.qc.
References SYSTEM_UPDATE, and time.
Referenced by EndFrame(), and Physics_Frame().
 {
     float realtime = time;
     SYSTEM_UPDATE(phys);
     time = realtime;
 }
want_weapon()
float want_weapon (entity weaponinfo, float allguns)
Definition at line 1704 of file world.qc.
References boolean, M_ARGV, MUTATOR_CALLHOOK, WEP_FLAG_HIDDEN, WEP_FLAG_MUTATORBLOCKED, WEP_FLAG_NORMAL, and WEP_FLAG_SPECIALATTACK.
Referenced by readplayerstartcvars(), and weapons_start().
 {
     int d = 0;
     bool allow_mutatorblocked = false;
     if(!weaponinfo.m_id)
         return 0;
     bool mutator_returnvalue = MUTATOR_CALLHOOK(WantWeapon, weaponinfo, d, allguns, allow_mutatorblocked);
     d = M_ARGV(1, float);
     allguns = M_ARGV(2, bool);
     allow_mutatorblocked = M_ARGV(3, bool);
     if(allguns)
         d = boolean((weaponinfo.spawnflags & WEP_FLAG_NORMAL) && !(weaponinfo.spawnflags & (WEP_FLAG_HIDDEN | WEP_FLAG_SPECIALATTACK)));
     else if(!mutator_returnvalue)
         d = !(!weaponinfo.weaponstart);
     if(!allow_mutatorblocked && (weaponinfo.spawnflags & WEP_FLAG_MUTATORBLOCKED)) // never default mutator blocked guns
         d = 0;
     float t = weaponinfo.weaponstartoverride;
     //LOG_INFOF("want_weapon: %s - d: %d t: %d\n", weaponinfo.netname, d, t);
     // bit order in t:
     // 1: want or not
     // 2: is default?
     // 4: is set by default?
     if(t < 0)
         t = 4 | (3 * d);
     else
         t |= (2 * d);
     return t;
 }
weaponarena_available_all_update()
void weaponarena_available_all_update (entity this)
Definition at line 1783 of file world.qc.
References g_weaponarena_weapons, start_weapons, warmup_start_weapons, weapons_all(), and weapons_start().
Referenced by readplayerstartcvars().
 {
     if (weaponsInMapAll)
     {
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_start() | (weaponsInMapAll & weapons_all());
     }
     else
     {
         // if no weapons are available on the map, just fall back to all weapons arena
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_all();
     }
 }
weaponarena_available_devall_update()
void weaponarena_available_devall_update (entity this)
Definition at line 1796 of file world.qc.
References g_weaponarena_weapons, start_weapons, warmup_start_weapons, weapons_devall(), and weapons_start().
Referenced by readplayerstartcvars().
 {
     if (weaponsInMapAll)
     {
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_start() | weaponsInMapAll;
     }
     else
     {
         // if no weapons are available on the map, just fall back to devall weapons arena
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_devall();
     }
 }
weaponarena_available_most_update()
void weaponarena_available_most_update (entity this)
Definition at line 1809 of file world.qc.
References g_weaponarena_weapons, start_weapons, warmup_start_weapons, weapons_most(), and weapons_start().
Referenced by readplayerstartcvars().
 {
     if (weaponsInMapAll)
     {
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_start() | (weaponsInMapAll & weapons_most());
     }
     else
     {
         // if no weapons are available on the map, just fall back to most weapons arena
         start_weapons = warmup_start_weapons = g_weaponarena_weapons = weapons_most();
     }
 }
weapons_all()
WepSet weapons_all ()
Definition at line 1753 of file world.qc.
References FOREACH, WEP_FLAG_MUTATORBLOCKED, and WEP_FLAG_SPECIALATTACK.
Referenced by readplayerstartcvars(), and weaponarena_available_all_update().
 {
     WepSet ret = '0 0 0';
     FOREACH(Weapons, it != WEP_Null, {
         if (!(it.spawnflags & (WEP_FLAG_MUTATORBLOCKED | WEP_FLAG_SPECIALATTACK)))
             ret |= it.m_wepset;
     });
     return ret;
 }
weapons_devall()
WepSet weapons_devall ()
Definition at line 1763 of file world.qc.
References FOREACH.
Referenced by readplayerstartcvars(), and weaponarena_available_devall_update().
 {
     WepSet ret = '0 0 0';
     FOREACH(Weapons, it != WEP_Null,
     {
         ret |= it.m_wepset;
     });
     return ret;
 }
weapons_most()
WepSet weapons_most ()
Definition at line 1773 of file world.qc.
References FOREACH, WEP_FLAG_HIDDEN, WEP_FLAG_MUTATORBLOCKED, WEP_FLAG_NORMAL, and WEP_FLAG_SPECIALATTACK.
Referenced by readplayerstartcvars(), and weaponarena_available_most_update().
 {
     WepSet ret = '0 0 0';
     FOREACH(Weapons, it != WEP_Null, {
         if ((it.spawnflags & WEP_FLAG_NORMAL) && !(it.spawnflags & (WEP_FLAG_MUTATORBLOCKED | WEP_FLAG_HIDDEN | WEP_FLAG_SPECIALATTACK)))
             ret |= it.m_wepset;
     });
     return ret;
 }
weapons_start()
WepSet weapons_start ()
Weapons the player normally starts with outside weapon arena.
Definition at line 1742 of file world.qc.
References FOREACH, and want_weapon().
Referenced by weaponarena_available_all_update(), weaponarena_available_devall_update(), and weaponarena_available_most_update().
 {
     WepSet ret = '0 0 0';
     FOREACH(Weapons, it != WEP_Null, {
         int w = want_weapon(it, false);
         if (w & 1)
             ret |= it.m_wepset;
     });
     return ret;
 }
WinningCondition_RanOutOfSpawns()
float WinningCondition_RanOutOfSpawns ()
Definition at line 1487 of file world.qc.
References AddWinners(), autocvar_g_spawn_useallspawns, checkrules_equality, ClearWinners(), entity(), FOREACH_CLIENT, g_spawnpoints, have_team_spawns, IL_EACH, IS_DEAD, IS_PLAYER, MAX_TEAMSCORE, NULL, NUM_TEAMS, some_spawn_has_been_used, team, Team_GetTeamFromIndex(), Team_GetTeamScore(), Team_IndexToTeam(), Team_IsValidTeam(), Team_SetTeamScore(), TeamBalance_CheckAllowedTeams(), TeamBalance_IsTeamAllowed(), TeamScore_AddToTeam(), WINNING_NO, and WINNING_YES.
Referenced by CheckRules_World().
 {
     if(have_team_spawns <= 0)
         return WINNING_NO;
     if(!autocvar_g_spawn_useallspawns)
         return WINNING_NO;
     if(!some_spawn_has_been_used)
         return WINNING_NO;
     for (int i = 1; i < 5; ++i)
     {
         Team_SetTeamScore(Team_GetTeamFromIndex(i), 0);
     }
     FOREACH_CLIENT(IS_PLAYER(it) && !IS_DEAD(it),
     {
         if (Team_IsValidTeam(it.team))
         {
             Team_SetTeamScore(Team_GetTeam(it.team), 1);
         }
     });
     IL_EACH(g_spawnpoints, true,
     {
         if (Team_IsValidTeam(it.team))
         {
             Team_SetTeamScore(Team_GetTeam(it.team), 1);
         }
     });
     ClearWinners();
     float team1_score = Team_GetTeamScore(Team_GetTeamFromIndex(1));
     float team2_score = Team_GetTeamScore(Team_GetTeamFromIndex(2));
     float team3_score = Team_GetTeamScore(Team_GetTeamFromIndex(3));
     float team4_score = Team_GetTeamScore(Team_GetTeamFromIndex(4));
     if(team1_score + team2_score + team3_score + team4_score == 0)
     {
         checkrules_equality = true;
         return WINNING_YES;
     }
     else if(team1_score + team2_score + team3_score + team4_score == 1)
     {
         float t, i;
         if(team1_score)
             t = 1;
         else if(team2_score)
             t = 2;
         else if(team3_score)
             t = 3;
         else // if(team4_score)
             t = 4;
         entity balance = TeamBalance_CheckAllowedTeams(NULL);
         for(i = 0; i < MAX_TEAMSCORE; ++i)
         {
             for (int j = 1; j <= NUM_TEAMS; ++j)
             {
                 if (t == j)
                 {
                     continue;
                 }
                 if (!TeamBalance_IsTeamAllowed(balance, j))
                 {
                     continue;
                 }
                 TeamScore_AddToTeam(Team_IndexToTeam(j), i, -1000);
             }
         }
         AddWinners(team, t);
         return WINNING_YES;
     }
     else
         return WINNING_NO;
 }
WinningCondition_Scores()
float WinningCondition_Scores (float limit, float leadlimit)
Definition at line 1406 of file world.qc.
References autocvar_leadlimit_and_fraglimit, checkrules_suddendeathend, ClearWinners(), FLOAT_MAX, fragsleft_last, GetWinningCode(), max(), min(), MUTATOR_CALLHOOK, NULL, SetWinners(), team, Team_GetTeamFromIndex(), Team_IndexToTeam(), Team_SetTeamScore(), teamplay, TeamScore_GetCompareValue(), time, WinningConditionHelper(), WinningConditionHelper_equality, WinningConditionHelper_lowerisbetter, WinningConditionHelper_secondscore, WinningConditionHelper_topscore, WinningConditionHelper_winner, WinningConditionHelper_winnerteam, and WinningConditionHelper_zeroisworst.
Referenced by CheckRules_World(), WinningCondition_QualifyingThenRace(), and WinningCondition_Race().
 {
     // TODO make everything use THIS winning condition (except LMS)
     WinningConditionHelper(NULL);
     if(teamplay)
     {
         for (int i = 1; i < 5; ++i)
         {
             Team_SetTeamScore(Team_GetTeamFromIndex(i),
                 TeamScore_GetCompareValue(Team_IndexToTeam(i)));
         }
     }
     ClearWinners();
     if(WinningConditionHelper_winner)
         WinningConditionHelper_winner.winning = 1;
     if(WinningConditionHelper_winnerteam >= 0)
         SetWinners(team, WinningConditionHelper_winnerteam);
     if(WinningConditionHelper_lowerisbetter)
     {
         WinningConditionHelper_topscore = -WinningConditionHelper_topscore;
         WinningConditionHelper_secondscore = -WinningConditionHelper_secondscore;
         limit = -limit;
     }
     if(WinningConditionHelper_zeroisworst)
         leadlimit = 0; // not supported in this mode
     if(MUTATOR_CALLHOOK(Scores_CountFragsRemaining))
     {
         float fragsleft;
         if (checkrules_suddendeathend && time >= checkrules_suddendeathend)
         {
             fragsleft = 1;
         }
         else
         {
             fragsleft = FLOAT_MAX;
             float leadingfragsleft = FLOAT_MAX;
             if (limit)
                 fragsleft = limit - WinningConditionHelper_topscore;
             if (leadlimit)
                 leadingfragsleft = WinningConditionHelper_secondscore + leadlimit - WinningConditionHelper_topscore;
             if (limit && leadlimit && autocvar_leadlimit_and_fraglimit)
                 fragsleft = max(fragsleft, leadingfragsleft);
             else
                 fragsleft = min(fragsleft, leadingfragsleft);
         }
         if (fragsleft_last != fragsleft) // do not announce same remaining frags multiple times
         {
             if (fragsleft == 1)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_1);
             else if (fragsleft == 2)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_2);
             else if (fragsleft == 3)
                 Send_Notification(NOTIF_ALL, NULL, MSG_ANNCE, ANNCE_REMAINING_FRAG_3);
             fragsleft_last = fragsleft;
         }
     }
     bool fraglimit_reached = (limit && WinningConditionHelper_topscore >= limit);
     bool leadlimit_reached = (leadlimit && WinningConditionHelper_topscore - WinningConditionHelper_secondscore >= leadlimit);
     bool limit_reached;
     // only respect leadlimit_and_fraglimit when both limits are set or the game will never end
     if (limit && leadlimit && autocvar_leadlimit_and_fraglimit)
         limit_reached = (fraglimit_reached && leadlimit_reached);
     else
         limit_reached = (fraglimit_reached || leadlimit_reached);
     return GetWinningCode(
         WinningConditionHelper_topscore && limit_reached,
         WinningConditionHelper_equality
     );
 }
Variable Documentation
autocvar_sv_freezenonclients
bool autocvar_sv_freezenonclients
Definition at line 2236 of file world.qc.
autocvar_sv_gameplayfix_multiplethinksperframe
bool autocvar_sv_gameplayfix_multiplethinksperframe = true
Definition at line 2208 of file world.qc.
fragsleft_last
int fragsleft_last
Definition at line 1405 of file world.qc.
Referenced by WinningCondition_Scores().
latency_cnt
float latency_cnt
Definition at line 54 of file world.qc.
latency_sum
float latency_sum
Definition at line 53 of file world.qc.
LATENCY_THINKRATE
const float LATENCY_THINKRATE = 10
Definition at line 52 of file world.qc.
Referenced by PingPLReport_Think().
latency_time
float latency_time
Definition at line 55 of file world.qc.
Referenced by PingPLReport_Think().
pingplreport
entity pingplreport
Definition at line 56 of file world.qc.
Referenced by PingPLReport_Spawn().
randomseed
entity randomseed
Definition at line 561 of file world.qc.
Referenced by RandomSeed_Spawn().
redirection_nextthink
float redirection_nextthink
Definition at line 2326 of file world.qc.
redirection_timeout
float redirection_timeout
Definition at line 2325 of file world.qc.
SPAWNFLAG_NO_WAYPOINTS_FOR_ITEMS
const float SPAWNFLAG_NO_WAYPOINTS_FOR_ITEMS = 1
Definition at line 102 of file world.qc.
Referenced by spawnfunc().
world_already_spawned
bool world_already_spawned
Definition at line 684 of file world.qc.
Referenced by spawnfunc().