Xonotic: client/hud/panel/scoreboard.qh File Reference
scoreboard.qh File Reference
#include "../panel.qh"
Functions
void Cmd_Scoreboard_SetFields (int argc)
void Scoreboard_Draw ()
void Scoreboard_InitScores ()
void Scoreboard_UpdatePlayerPos (entity pl)
void Scoreboard_UpdatePlayerTeams ()
void Scoreboard_UpdateTeamPos (entity Team)
bool Scoreboard_WouldDraw ()
Variables
float scoreboard_acc_fade_alpha
bool scoreboard_active
float scoreboard_fade_alpha
Function Documentation
void Cmd_Scoreboard_SetFields (int argc)
Definition at line 364 of file scoreboard.qc.
References argv(), autocvar_scoreboard_columns, cvar_set(), FOREACH, gametype, hud_fontsize, HUD_GetFontsize(), isGametypeInFilter(), LABEL, LOG_INFO, LOG_INFOF, MAX_SBT_FIELDS, ps_primary, ps_secondary, sbt_field, sbt_field_size, sbt_field_title, sbt_num_fields, SCOREBOARD_DEFAULT_COLUMNS, scores_flags, scores_label, SFL_ALLOW_HIDE, strcat(), strcpy, stringwidth(), strlen(), strstrofs, strunzone(), strzone(), substring(), TC, teamplay, tokenizebyseparator, and TranslateScoresLabel().
Referenced by Scoreboard_InitScores().
 {
     TC(int, argc);
     int i, slash;
     string str, pattern;
     bool have_name = false, have_primary = false, have_secondary = false, have_separator = false;
     int missing;
     if(!gametype)
         return; // do nothing, we don't know gametype and scores yet
     // sbt_fields uses strunzone on the titles!
     if(!sbt_field_title[0])
         for(i = 0; i < MAX_SBT_FIELDS; ++i)
             sbt_field_title[i] = strzone("(null)");
     // TODO: re enable with gametype dependant cvars?
     if(argc < 3) // no arguments provided
         argc = tokenizebyseparator(strcat("0 1 ", autocvar_scoreboard_columns), " ");
     if(argc < 3)
         argc = tokenizebyseparator(strcat("0 1 ", SCOREBOARD_DEFAULT_COLUMNS), " ");
     if(argc == 3)
     {
         if(argv(2) == "default" || argv(2) == "expand_default")
         {
             if(argv(2) == "expand_default")
                 cvar_set("scoreboard_columns", SCOREBOARD_DEFAULT_COLUMNS);
             argc = tokenizebyseparator(strcat("0 1 ", SCOREBOARD_DEFAULT_COLUMNS), " ");
         }
         else if(argv(2) == "all")
         {
             string s = "ping pl name |"; // scores without a label
             FOREACH(Scores, true, {
                 if(it != ps_primary)
                 if(it != ps_secondary)
                 if(scores_label(it) != "")
                     s = strcat(s, " ", scores_label(it));
             });
             if(ps_secondary != ps_primary)
                 s = strcat(s, " ", scores_label(ps_secondary));
             s = strcat(s, " ", scores_label(ps_primary));
             argc = tokenizebyseparator(strcat("0 1 ", s), " ");
         }
     }
     sbt_num_fields = 0;
     hud_fontsize = HUD_GetFontsize("hud_fontsize");
     for(i = 1; i < argc - 1; ++i)
     {
         str = argv(i+1);
         bool nocomplain = false;
         if(substring(str, 0, 1) == "?")
         {
             nocomplain = true;
             str = substring(str, 1, strlen(str) - 1);
         }
         slash = strstrofs(str, "/", 0);
         if(slash >= 0)
         {
             pattern = substring(str, 0, slash);
             str = substring(str, slash + 1, strlen(str) - (slash + 1));
             if (!isGametypeInFilter(gametype, teamplay, false, pattern))
                 continue;
         }
         strcpy(sbt_field_title[sbt_num_fields], TranslateScoresLabel(str));
         sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
         str = strtolower(str);
         PlayerScoreField j;
         switch(str)
         {
             case "ping": sbt_field[sbt_num_fields] = SP_PING; break;
             case "pl": sbt_field[sbt_num_fields] = SP_PL; break;
             case "kd": case "kdr": case "kdratio": sbt_field[sbt_num_fields] = SP_KDRATIO; break;
             case "sum": case "diff": case "k-d": sbt_field[sbt_num_fields] = SP_SUM; break;
             case "name": case "nick": sbt_field[sbt_num_fields] = SP_NAME; have_name = true; break;
             case "|": sbt_field[sbt_num_fields] = SP_SEPARATOR; have_separator = true; break;
             case "elo": sbt_field[sbt_num_fields] = SP_ELO; break;
             case "dmg": case "damage": sbt_field[sbt_num_fields] = SP_DMG; break;
             case "dmgtaken": case "damagetaken": sbt_field[sbt_num_fields] = SP_DMGTAKEN; break;
             case "fps": sbt_field[sbt_num_fields] = SP_FPS; break;
             default:
             {
                 FOREACH(Scores, true, {
                     if (str == strtolower(scores_label(it))) {
                         j = it;
                         goto found; // sorry, but otherwise fteqcc -O3 miscompiles this and warns about "unreachable code"
                     }
                 });
 LABEL(notfound)
                 if(str == "frags")
                     j = SP_FRAGS;
                 else
                 {
                     if(!nocomplain)
                         LOG_INFOF("^1Error:^7 Unknown score field: '%s'", str);
                     continue;
                 }
 LABEL(found)
                 sbt_field[sbt_num_fields] = j;
                 if(j == ps_primary)
                     have_primary = true;
                 if(j == ps_secondary)
                     have_secondary = true;
             }
         }
         ++sbt_num_fields;
         if(sbt_num_fields >= MAX_SBT_FIELDS)
             break;
     }
     if(scores_flags(ps_primary) & SFL_ALLOW_HIDE)
         have_primary = true;
     if(scores_flags(ps_secondary) & SFL_ALLOW_HIDE)
         have_secondary = true;
     if(ps_primary == ps_secondary)
         have_secondary = true;
     missing = (!have_primary) + (!have_secondary) + (!have_separator) + (!have_name);
     if(sbt_num_fields + missing < MAX_SBT_FIELDS)
     {
         if(!have_name)
         {
             strunzone(sbt_field_title[sbt_num_fields]);
             for(i = sbt_num_fields; i > 0; --i)
             {
                 sbt_field_title[i] = sbt_field_title[i-1];
                 sbt_field_size[i] = sbt_field_size[i-1];
                 sbt_field[i] = sbt_field[i-1];
             }
             sbt_field_title[0] = strzone(TranslateScoresLabel("name"));
             sbt_field[0] = SP_NAME;
             ++sbt_num_fields;
             LOG_INFO("fixed missing field 'name'");
             if(!have_separator)
             {
                 strunzone(sbt_field_title[sbt_num_fields]);
                 for(i = sbt_num_fields; i > 1; --i)
                 {
                     sbt_field_title[i] = sbt_field_title[i-1];
                     sbt_field_size[i] = sbt_field_size[i-1];
                     sbt_field[i] = sbt_field[i-1];
                 }
                 sbt_field_title[1] = strzone("|");
                 sbt_field[1] = SP_SEPARATOR;
                 sbt_field_size[1] = stringwidth("|", false, hud_fontsize);
                 ++sbt_num_fields;
                 LOG_INFO("fixed missing field '|'");
             }
         }
         else if(!have_separator)
         {
             strcpy(sbt_field_title[sbt_num_fields], "|");
             sbt_field_size[sbt_num_fields] = stringwidth("|", false, hud_fontsize);
             sbt_field[sbt_num_fields] = SP_SEPARATOR;
             ++sbt_num_fields;
             LOG_INFO("fixed missing field '|'");
         }
         if(!have_secondary)
         {
             strcpy(sbt_field_title[sbt_num_fields], TranslateScoresLabel(scores_label(ps_secondary)));
             sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
             sbt_field[sbt_num_fields] = ps_secondary;
             ++sbt_num_fields;
             LOG_INFOF("fixed missing field '%s'", scores_label(ps_secondary));
         }
         if(!have_primary)
         {
             strcpy(sbt_field_title[sbt_num_fields], TranslateScoresLabel(scores_label(ps_primary)));
             sbt_field_size[sbt_num_fields] = stringwidth(sbt_field_title[sbt_num_fields], false, hud_fontsize);
             sbt_field[sbt_num_fields] = ps_primary;
             ++sbt_num_fields;
             LOG_INFOF("fixed missing field '%s'", scores_label(ps_primary));
         }
     }
     sbt_field[sbt_num_fields] = SP_END;
 }
void Scoreboard_Draw ()
Definition at line 1511 of file scoreboard.qc.
References autocvar__hud_configure, autocvar_con_notify, autocvar_con_notifysize, autocvar_hud_fontsize, autocvar_hud_panel_scoreboard_bg_teams_color_team, autocvar_hud_panel_scoreboard_ctf_leaderboard, autocvar_hud_panel_scoreboard_dynamichud, autocvar_hud_panel_scoreboard_fadeinspeed, autocvar_hud_panel_scoreboard_fadeoutspeed, autocvar_hud_panel_scoreboard_minwidth, autocvar_hud_panel_scoreboard_namesize, autocvar_hud_panel_scoreboard_respawntime_decimals, autocvar_hud_panel_scoreboard_table_bg_alpha, autocvar_hud_panel_scoreboard_table_bg_scale, autocvar_hud_panel_scoreboard_table_fg_alpha, autocvar_hud_panel_scoreboard_table_fg_alpha_self, autocvar_hud_panel_scoreboard_table_highlight, autocvar_hud_panel_scoreboard_table_highlight_alpha, autocvar_hud_panel_scoreboard_table_highlight_alpha_self, bound(), ceil(), ColorTranslateRGB(), count_seconds, count_seconds_decs, CTX(), draw_beginBoldFont, draw_endBoldFont, drawcolorcodedstring(), DRAWFLAG_NORMAL, drawstring(), entity(), eX, eY, frametime, ftos(), gametype, getcommandkey, hud_configure_menu_open, hud_draw_maximized, hud_fontsize, hud_fontsize_str, HUD_GetFontsize(), HUD_Panel_LoadCvars(), HUD_Scale_Disable(), HUD_Scale_Enable(), intermission, ISGAMETYPE, MapInfo_Type_ToText(), max(), max_namesize, min(), NULL, NUM_SPECTATOR, panel, panel_bg_border, panel_bg_color, panel_bg_color_team, panel_fg_alpha, panel_pos, panel_size, player_localnum, players, playerslots, ps_primary, race_speedaward, race_speedaward_alltimebest, race_speedaward_alltimebest_holder, race_speedaward_alltimebest_unit, race_speedaward_holder, race_speedaward_unit, respawn_time, sbt_bg_alpha, sbt_fg_alpha, sbt_fg_alpha_self, sbt_highlight, sbt_highlight_alpha, sbt_highlight_alpha_self, scale, scoreboard_acc_fade_alpha, Scoreboard_AccuracyStats_Draw(), Scoreboard_AccuracyStats_WouldDraw(), scoreboard_active, scoreboard_bottom, Scoreboard_DrawOthers(), scoreboard_fade_alpha, Scoreboard_initFieldSizes(), Scoreboard_MakeTable(), Scoreboard_MapStats_Draw(), Scoreboard_Rankings_Draw(), Scoreboard_UpdatePlayerTeams(), scores_flags, scores_label, shortmapname, strcat(), strcpy, stringwidth(), Team_ColorRGB(), teamplay, teams, teamscores_flags, teamscores_label, time, TranslateScoresLabel(), ts_primary, ts_secondary, vec2, and vector().
 {
     if(!autocvar__hud_configure)
     {
         if(!hud_draw_maximized) return;
         // frametime checks allow to toggle the scoreboard even when the game is paused
         if(scoreboard_active) {
             if (scoreboard_fade_alpha < 1)
                 scoreboard_time = time;
             if(hud_configure_menu_open == 1)
                 scoreboard_fade_alpha = 1;
             float scoreboard_fadeinspeed = autocvar_hud_panel_scoreboard_fadeinspeed;
             if (scoreboard_fadeinspeed && frametime)
                 scoreboard_fade_alpha = min(1, scoreboard_fade_alpha + frametime * scoreboard_fadeinspeed);
             else
                 scoreboard_fade_alpha = 1;
             if(hud_fontsize_str != autocvar_hud_fontsize)
             {
                 hud_fontsize = HUD_GetFontsize("hud_fontsize");
                 Scoreboard_initFieldSizes();
                 strcpy(hud_fontsize_str, autocvar_hud_fontsize);
             }
         }
         else {
             float scoreboard_fadeoutspeed = autocvar_hud_panel_scoreboard_fadeoutspeed;
             if (scoreboard_fadeoutspeed && frametime)
                 scoreboard_fade_alpha = max(0, scoreboard_fade_alpha - frametime * scoreboard_fadeoutspeed);
             else
                 scoreboard_fade_alpha = 0;
         }
         if (!scoreboard_fade_alpha)
         {
             scoreboard_acc_fade_alpha = 0;
             return;
         }
     }
     else
         scoreboard_fade_alpha = 0;
     if (autocvar_hud_panel_scoreboard_dynamichud)
         HUD_Scale_Enable();
     else
         HUD_Scale_Disable();
     if(scoreboard_fade_alpha <= 0)
         return;
     panel_fade_alpha *= scoreboard_fade_alpha;
     HUD_Panel_LoadCvars();
     sbt_bg_alpha = autocvar_hud_panel_scoreboard_table_bg_alpha * panel_fg_alpha;
     sbt_highlight = autocvar_hud_panel_scoreboard_table_highlight;
     sbt_highlight_alpha = autocvar_hud_panel_scoreboard_table_highlight_alpha * panel_fg_alpha;
     sbt_highlight_alpha_self = autocvar_hud_panel_scoreboard_table_highlight_alpha_self * panel_fg_alpha;
     sbt_fg_alpha = autocvar_hud_panel_scoreboard_table_fg_alpha * panel_fg_alpha;
     sbt_fg_alpha_self = autocvar_hud_panel_scoreboard_table_fg_alpha_self * panel_fg_alpha;
     // don't overlap with con_notify
     if(!autocvar__hud_configure)
         panel_pos.y = max((autocvar_con_notify * autocvar_con_notifysize), panel_pos.y);
     float excess = max(0, max_namesize - autocvar_hud_panel_scoreboard_namesize * hud_fontsize.x);
     float fixed_scoreboard_width = bound(vid_conwidth * autocvar_hud_panel_scoreboard_minwidth, vid_conwidth - excess, vid_conwidth * 0.93);
     panel_pos.x = 0.5 * (vid_conwidth - fixed_scoreboard_width);
     panel_size.x = fixed_scoreboard_width;
     Scoreboard_UpdatePlayerTeams();
     vector pos = panel_pos;
     entity pl, tm;
     string str;
     vector str_pos;
     // Heading
     vector sb_heading_fontsize;
     sb_heading_fontsize = hud_fontsize * 2;
     draw_beginBoldFont();
     drawstring(pos + eX * panel_bg_padding, _("Scoreboard"), sb_heading_fontsize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
     draw_endBoldFont();
     pos.y += sb_heading_fontsize.y;
     if(panel.current_panel_bg != "0")
         pos.y += panel_bg_border;
     // Draw the scoreboard
     float scale = autocvar_hud_panel_scoreboard_table_bg_scale;
     if(scale <= 0)
         scale = 0.25;
     vector bg_size = draw_getimagesize("gfx/scoreboard/scoreboard_bg") * scale;
     if(teamplay)
     {
         vector panel_bg_color_save = panel_bg_color;
         vector team_score_baseoffset = eY * hud_fontsize.y - eX * hud_fontsize.x * 0.5;
         if(panel.current_panel_bg != "0")
             team_score_baseoffset.x -= panel_bg_border;
         for(tm = teams.sort_next; tm; tm = tm.sort_next)
         {
             if(tm.team == NUM_SPECTATOR)
                 continue;
             if(!tm.team)
                 continue;
             draw_beginBoldFont();
             vector rgb = Team_ColorRGB(tm.team);
             str = ftos(tm.(teamscores(ts_primary)));
             str_pos = pos + team_score_baseoffset - eX * stringwidth(str, false, hud_fontsize * 1.5);
             drawstring(str_pos, str, hud_fontsize * 1.5, rgb, panel_fg_alpha, DRAWFLAG_NORMAL);
             if(ts_primary != ts_secondary)
             {
                 str = ftos(tm.(teamscores(ts_secondary)));
                 str_pos = pos + team_score_baseoffset - vec2(stringwidth(str, false, hud_fontsize), hud_fontsize.y * 1.5);
                 drawstring(str_pos, str, hud_fontsize, rgb, panel_fg_alpha, DRAWFLAG_NORMAL);
             }
             draw_endBoldFont();
             if(autocvar_hud_panel_scoreboard_bg_teams_color_team > 0)
                 panel_bg_color = rgb * autocvar_hud_panel_scoreboard_bg_teams_color_team;
             else if(panel_bg_color_team > 0)
                 panel_bg_color = rgb * panel_bg_color_team;
             else
                 panel_bg_color = rgb;
             pos = Scoreboard_MakeTable(pos, tm, panel_bg_color, bg_size);
         }
         panel_bg_color = panel_bg_color_save;
     }
     else
     {
         for(tm = teams.sort_next; tm; tm = tm.sort_next)
             if(tm.team != NUM_SPECTATOR)
                 break;
         // display it anyway
         pos = Scoreboard_MakeTable(pos, tm, panel_bg_color, bg_size);
     }
     if (Scoreboard_AccuracyStats_WouldDraw(pos.y))
         pos = Scoreboard_AccuracyStats_Draw(pos, panel_bg_color, bg_size);
     if(ISGAMETYPE(CTS) || ISGAMETYPE(RACE) || (autocvar_hud_panel_scoreboard_ctf_leaderboard && ISGAMETYPE(CTF) && STAT(CTF_SHOWLEADERBOARD))) {
         if(race_speedaward) {
             drawcolorcodedstring(pos, sprintf(_("Speed award: %d%s ^7(%s^7)"), race_speedaward, race_speedaward_unit, ColorTranslateRGB(race_speedaward_holder)), hud_fontsize, panel_fg_alpha, DRAWFLAG_NORMAL);
             pos.y += 1.25 * hud_fontsize.y;
         }
         if(race_speedaward_alltimebest) {
             drawcolorcodedstring(pos, sprintf(_("All-time fastest: %d%s ^7(%s^7)"), race_speedaward_alltimebest, race_speedaward_alltimebest_unit, ColorTranslateRGB(race_speedaward_alltimebest_holder)), hud_fontsize, panel_fg_alpha, DRAWFLAG_NORMAL);
             pos.y += 1.25 * hud_fontsize.y;
         }
         pos = Scoreboard_Rankings_Draw(pos, playerslots[player_localnum], panel_bg_color, bg_size);
     }
     pos = Scoreboard_MapStats_Draw(pos, panel_bg_color, bg_size);
     // List spectators
     for(pl = players.sort_next; pl; pl = pl.sort_next)
     {
         if(pl.team == NUM_SPECTATOR)
         {
             for(tm = teams.sort_next; tm; tm = tm.sort_next)
                 if(tm.team == NUM_SPECTATOR)
                     break;
             str = sprintf("%s (%d)", _("Spectators"), tm.team_size);
             draw_beginBoldFont();
             drawstring(pos, str, hud_fontsize, '1 1 1', panel_fg_alpha, DRAWFLAG_NORMAL);
             draw_endBoldFont();
             pos.y += 1.25 * hud_fontsize.y;
             pos = Scoreboard_DrawOthers(pos, '0 0 0', pl.team, NULL, pl, 0);
             pos.y += 1.25 * hud_fontsize.y;
             break;
         }
     }
     // Print info string
     float tl, fl, ll;
     str = sprintf(_("playing ^3%s^7 on ^2%s^7"), MapInfo_Type_ToText(gametype), shortmapname);
     tl = STAT(TIMELIMIT);
     fl = STAT(FRAGLIMIT);
     ll = STAT(LEADLIMIT);
     if(ISGAMETYPE(LMS))
     {
         if(tl > 0)
             str = strcat(str, sprintf(_(" for up to ^1%1.0f minutes^7"), tl));
     }
     else
     {
         if(tl > 0)
             str = strcat(str, sprintf(_(" for up to ^1%1.0f minutes^7"), tl));
         if(fl > 0)
         {
             if(tl > 0)
                 str = strcat(str, _(" or"));
             if(teamplay)
             {
                 str = strcat(str, sprintf(_(" until ^3%s %s^7"), ScoreString(teamscores_flags(ts_primary), fl),
                     (teamscores_label(ts_primary) == "score")   ? CTX(_("SCO^points")) :
                     (teamscores_label(ts_primary) == "fastest") ? CTX(_("SCO^is beaten")) :
                     TranslateScoresLabel(teamscores_label(ts_primary))));
             }
             else
             {
                 str = strcat(str, sprintf(_(" until ^3%s %s^7"), ScoreString(scores_flags(ps_primary), fl),
                     (scores_label(ps_primary) == "score")   ? CTX(_("SCO^points")) :
                     (scores_label(ps_primary) == "fastest") ? CTX(_("SCO^is beaten")) :
                     TranslateScoresLabel(scores_label(ps_primary))));
             }
         }
         if(ll > 0)
         {
             if(tl > 0 || fl > 0)
                 str = strcat(str, _(" or"));
             if(teamplay)
             {
                 str = strcat(str, sprintf(_(" until a lead of ^3%s %s^7"), ScoreString(teamscores_flags(ts_primary), ll),
                     (teamscores_label(ts_primary) == "score")   ? CTX(_("SCO^points")) :
                     (teamscores_label(ts_primary) == "fastest") ? CTX(_("SCO^is beaten")) :
                     TranslateScoresLabel(teamscores_label(ts_primary))));
             }
             else
             {
                 str = strcat(str, sprintf(_(" until a lead of ^3%s %s^7"), ScoreString(scores_flags(ps_primary), ll),
                     (scores_label(ps_primary) == "score")   ? CTX(_("SCO^points")) :
                     (scores_label(ps_primary) == "fastest") ? CTX(_("SCO^is beaten")) :
                     TranslateScoresLabel(scores_label(ps_primary))));
             }
         }
     }
     pos.y += 1.2 * hud_fontsize.y;
     drawcolorcodedstring(pos + '0.5 0 0' * (panel_size.x - stringwidth(str, true, hud_fontsize)), str, hud_fontsize, panel_fg_alpha, DRAWFLAG_NORMAL);
     // print information about respawn status
     float respawn_time = STAT(RESPAWN_TIME);
     if(!intermission)
     if(respawn_time)
     {
         if(respawn_time < 0)
         {
             // a negative number means we are awaiting respawn, time value is still the same
             respawn_time *= -1; // remove mark now that we checked it
             if(respawn_time < time) // it happens for a few frames when server is respawning the player
                 str = ""; // draw an empty string to not change suddenly scoreboard_bottom
             else
                 str = sprintf(_("^1Respawning in ^3%s^1..."),
                     (autocvar_hud_panel_scoreboard_respawntime_decimals ?
                         count_seconds_decs(respawn_time - time, autocvar_hud_panel_scoreboard_respawntime_decimals)
                         :
                         count_seconds(ceil(respawn_time - time))
                     )
                 );
         }
         else if(time < respawn_time)
         {
             str = sprintf(_("You are dead, wait ^3%s^7 before respawning"),
                 (autocvar_hud_panel_scoreboard_respawntime_decimals ?
                     count_seconds_decs(respawn_time - time, autocvar_hud_panel_scoreboard_respawntime_decimals)
                     :
                     count_seconds(ceil(respawn_time - time))
                 )
             );
         }
         else if(time >= respawn_time)
             str = sprintf(_("You are dead, press ^2%s^7 to respawn"), getcommandkey("jump", "+jump"));
         pos.y += 1.2 * hud_fontsize.y;
         drawcolorcodedstring(pos + '0.5 0 0' * (panel_size.x - stringwidth(str, true, hud_fontsize)), str, hud_fontsize, panel_fg_alpha, DRAWFLAG_NORMAL);
     }
     scoreboard_bottom = pos.y + 2 * hud_fontsize.y;
 }
void Scoreboard_InitScores ()
Definition at line 136 of file scoreboard.qc.
References Cmd_Scoreboard_SetFields(), FOREACH, MAX_TEAMSCORE, NULL, ps_primary, ps_secondary, scores_flags, SFL_SORT_PRIO_MASK, SFL_SORT_PRIO_PRIMARY, SFL_SORT_PRIO_SECONDARY, teamscores_flags, ts_primary, and ts_secondary.
Referenced by NET_HANDLE().
 {
     int i, f;
     ps_primary = ps_secondary = NULL;
     ts_primary = ts_secondary = -1;
     FOREACH(Scores, true, {
         f = (scores_flags(it) & SFL_SORT_PRIO_MASK);
         if(f == SFL_SORT_PRIO_PRIMARY)
             ps_primary = it;
         if(f == SFL_SORT_PRIO_SECONDARY)
             ps_secondary = it;
     });
     if(ps_secondary == NULL)
         ps_secondary = ps_primary;
     for(i = 0; i < MAX_TEAMSCORE; ++i)
     {
         f = (teamscores_flags(i) & SFL_SORT_PRIO_MASK);
         if(f == SFL_SORT_PRIO_PRIMARY)
             ts_primary = i;
         if(f == SFL_SORT_PRIO_SECONDARY)
             ts_secondary = i;
     }
     if(ts_secondary == -1)
         ts_secondary = ts_primary;
     Cmd_Scoreboard_SetFields(0);
 }
void Scoreboard_UpdatePlayerPos (entity pl)
Definition at line 253 of file scoreboard.qc.
References entity(), players, Scoreboard_ComparePlayerScores(), and SORT_SWAP.
Referenced by NET_HANDLE(), Playerchecker_Think(), and Scoreboard_UpdatePlayerTeams().
 {
     entity ent;
     for(ent = player.sort_next; ent && Scoreboard_ComparePlayerScores(player, ent); ent = player.sort_next)
     {
         SORT_SWAP(player, ent);
     }
     for(ent = player.sort_prev; ent != players && Scoreboard_ComparePlayerScores(ent, player); ent = player.sort_prev)
     {
         SORT_SWAP(ent, player);
     }
 }
void Scoreboard_UpdatePlayerTeams ()
Definition at line 167 of file scoreboard.qc.
References entity(), players, Scoreboard_UpdatePlayerPos(), and SetTeam().
Referenced by HUD_Score_Rankings(), and Scoreboard_Draw().
 {
     entity pl, tmp;
     //int num = 0;
     for(pl = players.sort_next; pl; pl = pl.sort_next)
     {
         //num += 1;
         int Team = entcs_GetScoreTeam(pl.sv_entnum);
         if(SetTeam(pl, Team))
         {
             tmp = pl.sort_prev;
             Scoreboard_UpdatePlayerPos(pl);
             if(tmp)
                 pl = tmp;
             else
                 pl = players.sort_next;
         }
     }
     /*
     if(num != lastpnum)
         print(strcat("PNUM: ", ftos(num), "\n"));
     lastpnum = num;
     */
 }
void Scoreboard_UpdateTeamPos (entity Team)
Definition at line 296 of file scoreboard.qc.
References entity(), Scoreboard_CompareTeamScores(), SORT_SWAP, and teams.
Referenced by NET_HANDLE().
 {
     entity ent;
     for(ent = Team.sort_next; ent && Scoreboard_CompareTeamScores(Team, ent); ent = Team.sort_next)
     {
         SORT_SWAP(Team, ent);
     }
     for(ent = Team.sort_prev; ent != teams && Scoreboard_CompareTeamScores(ent, Team); ent = Team.sort_prev)
     {
         SORT_SWAP(ent, Team);
     }
 }
bool Scoreboard_WouldDraw ()
Definition at line 1113 of file scoreboard.qc.
References active_minigame, autocvar_cl_deathscoreboard, HUD_Radar_Clickable(), intermission, ISGAMETYPE, MUTATOR_CALLHOOK, QuickMenu_IsOpened(), scoreboard_showscores, scoreboard_showscores_force, and spectatee_status.
Referenced by CSQC_UpdateView().
 {
     if (MUTATOR_CALLHOOK(DrawScoreboard))
         return false;
     else if (QuickMenu_IsOpened())
         return false;
     else if (HUD_Radar_Clickable())
         return false;
     else if (scoreboard_showscores)
         return true;
     else if (intermission == 1)
         return true;
     else if (intermission == 2)
         return false;
     else if (spectatee_status != -1 && STAT(HEALTH) <= 0 && autocvar_cl_deathscoreboard && !ISGAMETYPE(CTS) && !active_minigame)
         return true;
     else if (scoreboard_showscores_force)
         return true;
     return false;
 }
Variable Documentation
float scoreboard_acc_fade_alpha
Definition at line 6 of file scoreboard.qh.
Referenced by Scoreboard_AccuracyStats_Draw(), and Scoreboard_Draw().
bool scoreboard_active
Definition at line 4 of file scoreboard.qh.
Referenced by AuxiliaryXhair_Draw2D(), CSQC_UpdateView(), HUD_Configure_Frame(), HUD_Crosshair(), and Scoreboard_Draw().
float scoreboard_fade_alpha
Definition at line 5 of file scoreboard.qh.
Referenced by HUD_CenterPrint(), HUD_Main(), HUD_Panel_Draw(), HUD_Score_Rankings(), Scoreboard_AccuracyStats_Draw(), and Scoreboard_Draw().