Xonotic: server/mutators/loader.qc File Reference
loader.qc File Reference
#include "loader.qh"
#include <server/defs.qh>
#include <server/miscfunctions.qh>
Functions
STATIC_INIT_LATE (Gametype)
Function Documentation
STATIC_INIT_LATE (Gametype)
Definition at line 6 of file loader.qc.
References car(), cdr(), FOREACH, MapInfo_CurrentGametype(), and Mutator_Add().
{
     Gametype g = MapInfo_CurrentGametype();
     if (g) {
         for (string _s = g.m_mutators; _s != ""; _s = cdr(_s)) {
             string s = car(_s);
             FOREACH(Mutators, it.m_name == s, { Mutator_Add(it); break; });
         }
     }
 }