Xonotic: common/gamemodes/gamemode/cts/sv_cts.qh File Reference
sv_cts.qh File Reference
#include <common/mutators/base.qh>
#include <server/race.qh>
Functions
void cts_Initialize ()
REGISTER_MUTATOR (cts, false)
Variables
const float ST_CTS_LAPS = 1
Function Documentation
cts_Initialize()
void cts_Initialize ()
Definition at line 373 of file sv_cts.qc.
References CTS_RECORD, cts_ScoreRules(), and record_type.
Referenced by REGISTER_MUTATOR().
 {
     record_type = CTS_RECORD;
     cts_ScoreRules();
 }
REGISTER_MUTATOR()
REGISTER_MUTATOR (cts , false)
Definition at line 8 of file sv_cts.qh.
References cts_Initialize(), g_race_qualifying, GameRules_limit_lead(), GameRules_limit_score(), independent_players, MUTATOR_ONADD, and MUTATOR_STATIC.
 {
     MUTATOR_STATIC();
     MUTATOR_ONADD
     {
         g_race_qualifying = true;
         independent_players = 1;
         GameRules_limit_score(0);
         GameRules_limit_lead(0);
         cts_Initialize();
     }
     return 0;
 }
Variable Documentation
ST_CTS_LAPS
const float ST_CTS_LAPS = 1
Definition at line 24 of file sv_cts.qh.