Xonotic: server/anticheat.qc File Reference
anticheat.qc File Reference
#include "anticheat.qh"
#include "antilag.qh"
#include "autocvars.qh"
#include "defs.qh"
#include "miscfunctions.qh"
#include "command/common.qh"
Functions
MEAN_DECLARE (anticheat_div0_evade, 5)
MEAN_DECLARE (anticheat_div0_strafebot_old, 5)
MEAN_DECLARE (anticheat_div0_strafebot_new, 5)
MEAN_DECLARE (anticheat_idle_snapaim_signal, 5)
MEAN_DECLARE (anticheat_idle_snapaim_noise, 1)
MEAN_DECLARE (anticheat_idle_snapaim_m2, 2)
MEAN_DECLARE (anticheat_idle_snapaim_m3, 3)
MEAN_DECLARE (anticheat_idle_snapaim_m4, 4)
MEAN_DECLARE (anticheat_idle_snapaim_m7, 7)
MEAN_DECLARE (anticheat_idle_snapaim_m10, 10)
MEAN_DECLARE (anticheat_speedhack, 5)
MEAN_DECLARE (anticheat_speedhack_m1, 1)
MEAN_DECLARE (anticheat_speedhack_m2, 2)
MEAN_DECLARE (anticheat_speedhack_m3, 3)
MEAN_DECLARE (anticheat_speedhack_m4, 4)
MEAN_DECLARE (anticheat_speedhack_m5, 5)
float movement_oddity (vector m0, vector m1)
void anticheat_physics (entity this)
void anticheat_spectatecopy (entity spectatee)
void anticheat_prethink ()
string anticheat_display (float f, float tmin, float mi, float ma)
void anticheat_report ()
float anticheat_getvalue (string id)
void anticheat_startframe ()
void anticheat_fixangle ()
void anticheat_endframe ()
void anticheat_init (entity this)
void anticheat_shutdown ()
Variables
float anticheat_jointime
float anticheat_fixangle_endtime
float anticheat_div0_evade_evasion_delta
float anticheat_div0_evade_offset
vector anticheat_div0_evade_v_angle
vector anticheat_div0_evade_forward_initial
vector anticheat_div0_strafebot_movement_prev
vector anticheat_div0_strafebot_forward_prev
float anticheat_speedhack_offset
float anticheat_speedhack_movetime
float anticheat_speedhack_movetime_count
float anticheat_speedhack_movetime_frac
float anticheat_speedhack_accu
float anticheat_speedhack_lasttime
Function Documentation
string anticheat_display (float f, float tmin, float mi, float ma)
Definition at line 162 of file anticheat.qc.
References ftos(), s, and strcat().
Referenced by anticheat_report().
 {
     string s;
     s = ftos(f);
     if(f <= mi)
         return strcat(s, ":N");
     if(f >= ma)
         return strcat(s, ":Y");
     return strcat(s, ":-");
 }
void anticheat_endframe ()
Definition at line 233 of file anticheat.qc.
References anticheat_div0_evade_evasion_delta, anticheat_fixangle(), entity(), FOREACH_CLIENT, frametime, LAMBDA, random(), SELFPARAM, and WITH.
Referenced by EndFrame().
 {SELFPARAM();
     FOREACH_CLIENT(true, LAMBDA(
         if(it.fixangle)
             WITH(entity, self, it, anticheat_fixangle());
     ));
     anticheat_div0_evade_evasion_delta += frametime * (0.5 + random());
 }
void anticheat_fixangle ()
Definition at line 228 of file anticheat.qc.
References ANTILAG_LATENCY, SELFPARAM, and servertime.
Referenced by anticheat_endframe(), and WarpZone_PostTeleportPlayer_Callback().
 {SELFPARAM();
     self.anticheat_fixangle_endtime = servertime + ANTILAG_LATENCY(self) + 0.2;
 }
float anticheat_getvalue (string id)
Definition at line 198 of file anticheat.qc.
References MEAN_EVALUATE, SELFPARAM, and servertime.
 {SELFPARAM();
     switch(id) {
         case "_time": return servertime - self.anticheat_jointime;
         case "speedhack": return MEAN_EVALUATE(self, anticheat_speedhack);
         case "speedhack_m1": return MEAN_EVALUATE(self, anticheat_speedhack_m1);
         case "speedhack_m2": return MEAN_EVALUATE(self, anticheat_speedhack_m2);
         case "speedhack_m3": return MEAN_EVALUATE(self, anticheat_speedhack_m3);
         case "speedhack_m4": return MEAN_EVALUATE(self, anticheat_speedhack_m4);
         case "speedhack_m5": return MEAN_EVALUATE(self, anticheat_speedhack_m5);
         case "div0_strafebot_old": return MEAN_EVALUATE(self, anticheat_div0_strafebot_old);
         case "div0_strafebot_new": return MEAN_EVALUATE(self, anticheat_div0_strafebot_new);
         case "div0_evade": return MEAN_EVALUATE(self, anticheat_div0_evade);
         case "idle_snapaim": return MEAN_EVALUATE(self, anticheat_idle_snapaim_signal) - MEAN_EVALUATE(self, anticheat_idle_snapaim_noise);
         case "idle_snapaim_signal": return MEAN_EVALUATE(self, anticheat_idle_snapaim_signal);
         case "idle_snapaim_noise": return MEAN_EVALUATE(self, anticheat_idle_snapaim_noise);
         case "idle_snapaim_m2": return MEAN_EVALUATE(self, anticheat_idle_snapaim_m2);
         case "idle_snapaim_m3": return MEAN_EVALUATE(self, anticheat_idle_snapaim_m3);
         case "idle_snapaim_m4": return MEAN_EVALUATE(self, anticheat_idle_snapaim_m4);
         case "idle_snapaim_m7": return MEAN_EVALUATE(self, anticheat_idle_snapaim_m7);
         case "idle_snapaim_m10": return MEAN_EVALUATE(self, anticheat_idle_snapaim_m10);
     }
     return -1;
 }
void anticheat_init (entity this)
Definition at line 242 of file anticheat.qc.
References anticheat_jointime, anticheat_speedhack_offset, and servertime.
Referenced by ClientConnect().
 {
     this.anticheat_speedhack_offset = 0;
     this.anticheat_jointime = servertime;
 }
void anticheat_physics (entity this)
Definition at line 63 of file anticheat.qc.
References anticheat_div0_evade_evasion_delta, anticheat_div0_evade_forward_initial, anticheat_div0_evade_offset, anticheat_div0_evade_v_angle, anticheat_div0_strafebot_forward_prev, anticheat_div0_strafebot_movement_prev, anticheat_fixangle_endtime, anticheat_speedhack_accu, anticheat_speedhack_lasttime, anticheat_speedhack_movetime, anticheat_speedhack_movetime_count, anticheat_speedhack_movetime_frac, anticheat_speedhack_offset, autocvar_slowmo, exp(), fabs(), falloff, floor(), frametime, M_PI, max(), MEAN_ACCUMULATE, movement, movement_oddity(), servertime, sys_frametime, time, v_angle, and v_forward.
Referenced by PM_Main().
 {
     float f;
     // div0_evade -> SPECTATORS
     makevectors(this.v_angle);
     if(this.anticheat_div0_evade_offset == 0)
     {
         f = fabs(anticheat_div0_evade_evasion_delta - floor(anticheat_div0_evade_evasion_delta) - 0.5) * 2; // triangle function
         this.anticheat_div0_evade_offset = servertime + sys_frametime * (3 * f - 1);
         this.anticheat_div0_evade_v_angle = this.v_angle;
         this.anticheat_div0_evade_forward_initial = v_forward;
         MEAN_ACCUMULATE(this, anticheat_div0_evade, 0, 1);
     }
     else
     {
         if(time < this.anticheat_div0_evade_offset)
             this.anticheat_div0_evade_v_angle = this.v_angle;
         MEAN_ACCUMULATE(this, anticheat_div0_evade, 0.5 - 0.5 * (this.anticheat_div0_evade_forward_initial * v_forward), 1);
     }
     MEAN_ACCUMULATE(this, anticheat_div0_strafebot_old, movement_oddity(this.movement, this.anticheat_div0_strafebot_movement_prev), 1);
     this.anticheat_div0_strafebot_movement_prev = this.movement;
     // Note: this actually tries to detect snap-aim.
     if(this.anticheat_div0_strafebot_forward_prev && time > this.anticheat_fixangle_endtime) {
         float cosangle = this.anticheat_div0_strafebot_forward_prev * v_forward;
         float angle = cosangle < -1 ? M_PI : cosangle > 1 ? 0 : acos(cosangle);
         /*
         if (angle >= 10 * M_PI / 180)
             printf("SNAP %s: %f for %f, %f since fixangle\n", this.netname, angle * 180 / M_PI, cosangle, time - this.anticheat_fixangle_endtime);
         */
         MEAN_ACCUMULATE(this, anticheat_div0_strafebot_new, angle / M_PI, 1);
         if (autocvar_slowmo > 0) {
             // Technically this is a NOP, as the engine should be ensuring
             // this in the first place. Let's guard against dividing by
             // zero anyway.
             float dt = max(0.001, frametime) / autocvar_slowmo;
             float anglespeed = angle / dt;
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_signal, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_noise, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_m2, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_m3, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_m4, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_m7, anglespeed, dt);
             MEAN_ACCUMULATE(this, anticheat_idle_snapaim_m10, anglespeed, dt);
         }
     }
     this.anticheat_div0_strafebot_forward_prev = v_forward;
     // generic speedhack detection: correlate anticheat_speedhack_movetime (UPDATED BEFORE THIS) and server time
     this.anticheat_speedhack_movetime_frac += frametime;
     f = floor(this.anticheat_speedhack_movetime_frac);
     this.anticheat_speedhack_movetime_frac -= f;
     this.anticheat_speedhack_movetime_count += f;
     this.anticheat_speedhack_movetime = this.anticheat_speedhack_movetime_frac + this.anticheat_speedhack_movetime_count;
     f = this.anticheat_speedhack_movetime - servertime;
     if(this.anticheat_speedhack_offset == 0)
         this.anticheat_speedhack_offset = f;
     else
     {
         MEAN_ACCUMULATE(this, anticheat_speedhack, max(0, f - this.anticheat_speedhack_offset), 1);
         this.anticheat_speedhack_offset += (f - this.anticheat_speedhack_offset) * frametime * 0.1;
     }
     // new generic speedhack detection
     if (this.anticheat_speedhack_lasttime > 0) {
         float dt = servertime - this.anticheat_speedhack_lasttime;
         const float falloff = 0.2;
         this.anticheat_speedhack_accu *= exp(-dt * falloff);
         this.anticheat_speedhack_accu += frametime * falloff;
         // NOTE: at cl_netfps x, this actually averages not to 1, but to 1/x * falloff / (1 - exp(-1/x * falloff))
         // For 15 netfps (absolute minimum bearable), and 0.2 falloff, this is: 1.0067
         this.anticheat_speedhack_lasttime = servertime;
         MEAN_ACCUMULATE(this, anticheat_speedhack_m1, this.anticheat_speedhack_accu, frametime);
         MEAN_ACCUMULATE(this, anticheat_speedhack_m2, this.anticheat_speedhack_accu, frametime);
         MEAN_ACCUMULATE(this, anticheat_speedhack_m3, this.anticheat_speedhack_accu, frametime);
         MEAN_ACCUMULATE(this, anticheat_speedhack_m4, this.anticheat_speedhack_accu, frametime);
         MEAN_ACCUMULATE(this, anticheat_speedhack_m5, this.anticheat_speedhack_accu, frametime);
     } else {
         this.anticheat_speedhack_accu = 1;
         this.anticheat_speedhack_lasttime = servertime;
     }
 }
void anticheat_prethink ()
Definition at line 156 of file anticheat.qc.
References SELFPARAM.
Referenced by PlayerPreThink().
 {SELFPARAM();
     // div0_evade -> SPECTATORS
     self.anticheat_div0_evade_offset = 0;
 }
void anticheat_report ()
Definition at line 173 of file anticheat.qc.
References anticheat_display(), anticheat_jointime, autocvar_sv_eventlog, ftos(), GameLogEcho(), MEAN_EVALUATE, playerid, SELFPARAM, servertime, and strcat().
Referenced by ClientDisconnect(), and GameCommand_anticheat().
 {SELFPARAM();
     if(!autocvar_sv_eventlog)
         return;
     // TODO(divVerent): Use xonstat to acquire good thresholds.
     GameLogEcho(strcat(":anticheat:_time:", ftos(self.playerid), ":", ftos(servertime - self.anticheat_jointime)));
     GameLogEcho(strcat(":anticheat:speedhack:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack), 240, 0, 9999))); // Actually this one seems broken.
     GameLogEcho(strcat(":anticheat:speedhack_m1:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack_m1), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m2:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack_m2), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m3:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack_m3), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m4:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack_m4), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m5:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_speedhack_m5), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:div0_strafebot_old:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_div0_strafebot_old), 120, 0.15, 0.4)));
     GameLogEcho(strcat(":anticheat:div0_strafebot_new:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_div0_strafebot_new), 120, 0.25, 0.8)));
     GameLogEcho(strcat(":anticheat:div0_evade:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_div0_evade), 120, 0.2, 0.5)));
     GameLogEcho(strcat(":anticheat:idle_snapaim:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_signal) - MEAN_EVALUATE(self, anticheat_idle_snapaim_noise), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_signal:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_signal), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_noise:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_noise), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m2:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_m2), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m3:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_m3), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m4:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_m4), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m7:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_m7), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m10:", ftos(self.playerid), ":", anticheat_display(MEAN_EVALUATE(self, anticheat_idle_snapaim_m10), 120, 0, 9999)));
 }
void anticheat_shutdown ()
Definition at line 248 of file anticheat.qc.
Referenced by ClientDisconnect().
 {
 }
void anticheat_spectatecopy (entity spectatee)
Definition at line 150 of file anticheat.qc.
References SELFPARAM.
Referenced by SpectateCopy().
 {SELFPARAM();
     // div0_evade -> SPECTATORS
     self.angles = spectatee.anticheat_div0_evade_v_angle;
 }
void anticheat_startframe ()
Definition at line 223 of file anticheat.qc.
References anticheat_div0_evade_evasion_delta, frametime, and random().
Referenced by StartFrame().
 {
     anticheat_div0_evade_evasion_delta += frametime * (0.5 + random());
 }
MEAN_DECLARE (anticheat_div0_evade , 5)
MEAN_DECLARE (anticheat_div0_strafebot_old , 5)
MEAN_DECLARE (anticheat_div0_strafebot_new , 5)
MEAN_DECLARE (anticheat_idle_snapaim_signal , 5)
MEAN_DECLARE (anticheat_idle_snapaim_noise , 1)
MEAN_DECLARE (anticheat_idle_snapaim_m2 , 2)
MEAN_DECLARE (anticheat_idle_snapaim_m3 , 3)
MEAN_DECLARE (anticheat_idle_snapaim_m4 , 4)
MEAN_DECLARE (anticheat_idle_snapaim_m7 , 7)
MEAN_DECLARE (anticheat_idle_snapaim_m10 , 10)
MEAN_DECLARE (anticheat_speedhack , 5)
MEAN_DECLARE (anticheat_speedhack_m1 , 1)
MEAN_DECLARE (anticheat_speedhack_m2 , 2)
MEAN_DECLARE (anticheat_speedhack_m3 , 3)
MEAN_DECLARE (anticheat_speedhack_m4 , 4)
MEAN_DECLARE (anticheat_speedhack_m5 , 5)
float movement_oddity (vector m0, vector m1)
Definition at line 54 of file anticheat.qc.
References cos(), M_PI, and normalize().
Referenced by anticheat_physics().
 {
     float cosangle = normalize(m0) * normalize(m1);
     if(cosangle >= 0)
         return 0;
     return 0.5 - 0.5 * cos(cosangle * cosangle * 4 * M_PI);
         // returns 0 for: -1, -sqrt(0.5), 0 (angles that commonly happen with kbd)
 }
Variable Documentation
float anticheat_div0_evade_evasion_delta
Definition at line 16 of file anticheat.qc.
Referenced by anticheat_endframe(), anticheat_physics(), and anticheat_startframe().
vector anticheat_div0_evade_forward_initial
Definition at line 19 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_div0_evade_offset
Definition at line 17 of file anticheat.qc.
Referenced by anticheat_physics().
vector anticheat_div0_evade_v_angle
Definition at line 18 of file anticheat.qc.
Referenced by anticheat_physics().
vector anticheat_div0_strafebot_forward_prev
Definition at line 25 of file anticheat.qc.
Referenced by anticheat_physics().
vector anticheat_div0_strafebot_movement_prev
Definition at line 22 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_fixangle_endtime
Definition at line 14 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_jointime
Definition at line 12 of file anticheat.qc.
Referenced by anticheat_init(), and anticheat_report().
float anticheat_speedhack_accu
Definition at line 46 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_speedhack_lasttime
Definition at line 47 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_speedhack_movetime
Definition at line 43 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_speedhack_movetime_count
Definition at line 43 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_speedhack_movetime_frac
Definition at line 43 of file anticheat.qc.
Referenced by anticheat_physics().
float anticheat_speedhack_offset
Definition at line 42 of file anticheat.qc.
Referenced by anticheat_init(), and anticheat_physics().