Xonotic: menu/item/textslider.qc File Reference
textslider.qc File Reference
#include "textslider.qh"
Functions
void TextSlider_addValue (entity me, string theString, string theIdentifier)
void TextSlider_clearValues (entity me)
void TextSlider_configureTextSliderValues (entity me, string theDefault)
string TextSlider_getIdentifier (entity me)
void TextSlider_insertValue (entity me, int pos, string theString, string theIdentifier)
void TextSlider_setValueFromIdentifier (entity me, string id)
void TextSlider_setValueFromIdentifier_allowAnim (entity me, string id, bool allowAnim)
void TextSlider_setValueFromIdentifier_noAnim (entity me, string id)
string TextSlider_valueToIdentifier (entity me, int val)
string TextSlider_valueToText (entity me, int val)
Function Documentation
void TextSlider_addValue (entity me, string theString, string theIdentifier)
Definition at line 42 of file textslider.qc.
     {
         me.(valueStrings[me.nValues]) = theString;
         me.(valueIdentifiers[me.nValues]) = theIdentifier;
         me.nValues += 1;
     }
void TextSlider_clearValues (entity me)
Definition at line 38 of file textslider.qc.
     {
         me.nValues = 0;
     }
void TextSlider_configureTextSliderValues (entity me, string theDefault)
Definition at line 60 of file textslider.qc.
     {
         me.configureSliderValues(me, 0, 0, me.nValues - 1, 1, 1, 1);
         me.setValueFromIdentifier_noAnim(me, theDefault);
     }
string TextSlider_getIdentifier (entity me)
Definition at line 34 of file textslider.qc.
     {
         return me.valueToIdentifier(me, me.value);
     }
void TextSlider_insertValue (entity me, int pos, string theString, string theIdentifier)
Definition at line 48 of file textslider.qc.
     {
         int i;
         for (i = me.nValues; i > pos; --i)
         {
             me.(valueStrings[i]) = me.(valueStrings[i - 1]);
             me.(valueIdentifiers[i]) = me.(valueIdentifiers[i - 1]);
         }
         me.(valueStrings[pos]) = theString;
         me.(valueIdentifiers[pos]) = theIdentifier;
         me.nValues += 1;
     }
void TextSlider_setValueFromIdentifier (entity me, string id)
Definition at line 30 of file textslider.qc.
References TextSlider_setValueFromIdentifier_allowAnim().
     {
         TextSlider_setValueFromIdentifier_allowAnim(me, id, true);
     }
void TextSlider_setValueFromIdentifier_allowAnim (entity me, string id, bool allowAnim)
Definition at line 15 of file textslider.qc.
References SUPER.
Referenced by TextSlider_setValueFromIdentifier(), and TextSlider_setValueFromIdentifier_noAnim().
     {
         int i;
         for (i = 0; i < me.nValues; ++i)
             if (me.valueToIdentifier(me, i) == id)
             {
                 SUPER(TextSlider).setValue_allowAnim(me, i, allowAnim);
                 return;
             }
         SUPER(TextSlider).setValue_allowAnim(me, -1, allowAnim);
     }
void TextSlider_setValueFromIdentifier_noAnim (entity me, string id)
Definition at line 26 of file textslider.qc.
References TextSlider_setValueFromIdentifier_allowAnim().
     {
         TextSlider_setValueFromIdentifier_allowAnim(me, id, false);
     }
string TextSlider_valueToIdentifier (entity me, int val)
Definition at line 3 of file textslider.qc.
     {
         if (val >= me.nValues) return "custom";
         if (val < 0) return "custom";
         return me.(valueIdentifiers[val]);
     }
string TextSlider_valueToText (entity me, int val)
Definition at line 9 of file textslider.qc.
     {
         if (val >= me.nValues) return _("Custom");
         if (val < 0) return _("Custom");
         return me.(valueStrings[val]);
     }