Xonotic: common/models/all.inc File Reference
all.inc File Reference
Functions
Model MDL_GIB_ROBO_RANDOM ()
Model MDL_NUM (int i)
MODEL (CTF_SHIELD, "models/ctf/shield.md3")
MODEL (CTF_CAPTURE, "models/ctf/shockwavetransring.md3")
MODEL (CTF_FLAG, "models/ctf/flags.md3")
MODEL (DOM_NEUTRAL, "models/domination/dom_unclaimed.md3")
MODEL (DOM_RED, "models/domination/dom_red.md3")
MODEL (DOM_BLUE, "models/domination/dom_blue.md3")
MODEL (DOM_YELLOW, "models/domination/dom_yellow.md3")
MODEL (DOM_PINK, "models/domination/dom_pink.md3")
MODEL (ICE, "models/ice/ice.md3")
MODEL (KH_KEY, "models/keyhunt/key.md3")
MODEL (OK_HMG, W_Model("g_ok_hmg.md3"))
MODEL (OK_RPC, W_Model("g_ok_rl.md3"))
MODEL (OK_MG_VIEW, W_Model("h_ok_mg.iqm"))
MODEL (OK_MG_WORLD, W_Model("v_ok_mg.md3"))
MODEL (OK_MG_ITEM, W_Model("g_ok_mg.md3"))
MODEL (OK_SHOTGUN_VIEW, W_Model("h_ok_shotgun.iqm"))
MODEL (OK_SHOTGUN_WORLD, W_Model("v_ok_shotgun.md3"))
MODEL (OK_SHOTGUN_ITEM, W_Model("g_ok_shotgun.md3"))
MODEL (OK_SNIPER_VIEW, W_Model("h_ok_sniper.iqm"))
MODEL (OK_SNIPER_WORLD, W_Model("v_ok_sniper.md3"))
MODEL (OK_SNIPER_ITEM, W_Model("g_ok_sniper.md3"))
MODEL (ONS_CP, "models/onslaught/controlpoint_icon.md3")
MODEL (ONS_CP_SHIELD, "models/onslaught/controlpoint_shield.md3")
MODEL (ONS_CP_PAD1, "models/onslaught/controlpoint_pad.md3")
MODEL (ONS_CP_PAD2, "models/onslaught/controlpoint_pad2.md3")
MODEL (ONS_CP1, "models/onslaught/controlpoint_icon_dmg1.md3")
MODEL (ONS_CP1_GIB, "models/onslaught/controlpoint_icon_gib1.md3")
MODEL (ONS_CP2, "models/onslaught/controlpoint_icon_dmg2.md3")
MODEL (ONS_CP2_GIB, "models/onslaught/controlpoint_icon_gib2.md3")
MODEL (ONS_CP3, "models/onslaught/controlpoint_icon_dmg3.md3")
MODEL (ONS_CP3_GIB, "models/onslaught/controlpoint_icon_gib4.md3")
MODEL (ONS_RAY, "models/onslaught/ons_ray.md3")
MODEL (ONS_GEN, "models/onslaught/generator.md3")
MODEL (ONS_GEN_SHIELD, "models/onslaught/generator_shield.md3")
MODEL (ONS_GEN_GIB1, "models/onslaught/gen_gib1.md3")
MODEL (ONS_GEN_GIB2, "models/onslaught/gen_gib2.md3")
MODEL (ONS_GEN_GIB3, "models/onslaught/gen_gib3.md3")
MODEL (ONS_GEN1, "models/onslaught/generator_dmg1.md3")
MODEL (ONS_GEN2, "models/onslaught/generator_dmg2.md3")
MODEL (ONS_GEN3, "models/onslaught/generator_dmg3.md3")
MODEL (ONS_GEN4, "models/onslaught/generator_dmg4.md3")
MODEL (ONS_GEN5, "models/onslaught/generator_dmg5.md3")
MODEL (ONS_GEN6, "models/onslaught/generator_dmg6.md3")
MODEL (ONS_GEN7, "models/onslaught/generator_dmg7.md3")
MODEL (ONS_GEN8, "models/onslaught/generator_dmg8.md3")
MODEL (ONS_GEN9, "models/onslaught/generator_dmg9.md3")
MODEL (ONS_GEN_DEAD, "models/onslaught/generator_dead.md3")
MODEL (PROJECTILE_ELECTRO, "models/ebomb.mdl")
MODEL (PROJECTILE_ELECTRO_BEAM, "models/elaser.mdl")
MODEL (PROJECTILE_ROCKET, "models/rocket.md3")
MODEL (PROJECTILE_CRYLINK, "models/plasmatrail.mdl")
MODEL (PROJECTILE_CRYLINK_BOUNCING, "models/plasmatrail.mdl")
MODEL (PROJECTILE_GRENADE, "models/grenademodel.md3")
MODEL (PROJECTILE_GRENADE_BOUNCING, "models/grenademodel.md3")
MODEL (PROJECTILE_MINE, "models/mine.md3")
MODEL (PROJECTILE_BLASTER, "models/laser.mdl")
MODEL (PROJECTILE_HLAC, "models/hlac_bullet.md3")
MODEL (PROJECTILE_PORTO_RED, "models/grenademodel.md3")
MODEL (PROJECTILE_PORTO_BLUE, "models/grenademodel.md3")
MODEL (PROJECTILE_HOOKBOMB, "models/grenademodel.md3")
MODEL (PROJECTILE_HAGAR, "models/hagarmissile.mdl")
MODEL (PROJECTILE_HAGAR_BOUNCING, "models/hagarmissile.mdl")
MODEL (PROJECTILE_ARC_BOLT, "models/ebomb.mdl")
MODEL (PROJECTILE_NAPALM_FOUNTAIN, "null")
MODEL (PROJECTILE_FIREBALL, "null")
MODEL (PROJECTILE_FIREMINE, "null")
MODEL (PROJECTILE_TAG, "models/laser.mdl")
MODEL (PROJECTILE_FLAC, "models/hagarmissile.mdl")
MODEL (PROJECTILE_SEEKER, "models/tagrocket.md3")
MODEL (PROJECTILE_MAGE_SPIKE, "models/ebomb.mdl")
MODEL (PROJECTILE_SHAMBLER_LIGHTNING, "models/ebomb.mdl")
MODEL (PROJECTILE_RAPTORBOMB, "models/vehicles/clusterbomb.md3")
MODEL (PROJECTILE_RAPTORBOMBLET, "models/vehicles/bomblet.md3")
MODEL (PROJECTILE_RAPTORCANNON, "models/plasmatrail.mdl")
MODEL (PROJECTILE_SPIDERROCKET, "models/vehicles/rocket02.md3")
MODEL (PROJECTILE_WAKIROCKET, "models/vehicles/rocket01.md3")
MODEL (PROJECTILE_WAKICANNON, "models/laser.mdl")
MODEL (PROJECTILE_BUMBLE_GUN, "models/elaser.mdl")
MODEL (PROJECTILE_BUMBLE_BEAM, "models/elaser.mdl")
MODEL (PROJECTILE_RPC, W_Model("ok_rocket.md3"))
MODEL (PROJECTILE_ROCKETMINSTA_LASER, "models/elaser.mdl")
MODEL (PROJECTILE_NADE, W_Model("v_ok_grenade.md3"))
MODEL (NADE_VIEW, W_Model("h_ok_grenade.iqm"))
MODEL (NADE_TIMER, "models/ok_nade_counter/ok_nade_counter.md3")
MODEL (NADE_ORB, "models/ctf/shield.md3")
MODEL (GIB_CHUNK, "models/gibs/chunk.mdl")
MODEL (GIB_LEG1, "models/gibs/leg1.md3")
MODEL (GIB_LEG2, "models/gibs/leg2.md3")
MODEL (GIB_CHEST, "models/gibs/chest.md3")
MODEL (GIB_SMALLCHEST, "models/gibs/smallchest.md3")
MODEL (GIB_ARM, "models/gibs/arm.md3")
MODEL (GIB_BLOODYSKULL, "models/gibs/bloodyskull.md3")
MODEL (GIB_EYE, "models/gibs/eye.md3")
MODEL (GIB_ROBO, "models/gibs/robo.md3")
MODEL (GIB_ROBO_1, "models/gibs/robo1.md3")
MODEL (GIB_ROBO_2, "models/gibs/robo2.md3")
MODEL (GIB_ROBO_3, "models/gibs/robo3.md3")
MODEL (GIB_ROBO_4, "models/gibs/robo4.md3")
MODEL (GIB_ROBO_5, "models/gibs/robo5.md3")
MODEL (GIB_ROBO_6, "models/gibs/robo6.md3")
MODEL (GIB_ROBO_7, "models/gibs/robo7.md3")
MODEL (GIB_ROBO_8, "models/gibs/robo8.md3")
MODEL (CASING_SHELL, "models/casing_shell.mdl")
MODEL (CASING_BULLET, "models/casing_bronze.iqm")
MODEL (BUFF, "models/relics/relic.md3")
MODEL (BLASTER_VIEW, W_Model("h_laser.iqm"))
MODEL (BLASTER_WORLD, W_Model("v_laser.md3"))
MODEL (BLASTER_ITEM, W_Model("g_laser.md3"))
MODEL (SHOTGUN_MUZZLEFLASH, "models/uziflash.md3")
MODEL (SHOTGUN_VIEW, W_Model("h_shotgun.iqm"))
MODEL (SHOTGUN_WORLD, W_Model("v_shotgun.md3"))
MODEL (SHOTGUN_ITEM, W_Model("g_shotgun.md3"))
MODEL (MACHINEGUN_MUZZLEFLASH, "models/uziflash.md3")
MODEL (MACHINEGUN_VIEW, W_Model("h_uzi.iqm"))
MODEL (MACHINEGUN_WORLD, W_Model("v_uzi.md3"))
MODEL (MACHINEGUN_ITEM, W_Model("g_uzi.md3"))
MODEL (MORTAR_VIEW, W_Model("h_gl.iqm"))
MODEL (MORTAR_WORLD, W_Model("v_gl.md3"))
MODEL (MORTAR_ITEM, W_Model("g_gl.md3"))
MODEL (MINELAYER_MUZZLEFLASH, "models/flash.md3")
MODEL (MINELAYER_MINE, "models/mine.md3")
MODEL (MINELAYER_VIEW, W_Model("h_minelayer.iqm"))
MODEL (MINELAYER_WORLD, W_Model("v_minelayer.md3"))
MODEL (MINELAYER_ITEM, W_Model("g_minelayer.md3"))
MODEL (ELECTRO_VIEW, W_Model("h_electro.iqm"))
MODEL (ELECTRO_WORLD, W_Model("v_electro.md3"))
MODEL (ELECTRO_ITEM, W_Model("g_electro.md3"))
MODEL (CRYLINK_VIEW, W_Model("h_crylink.iqm"))
MODEL (CRYLINK_WORLD, W_Model("v_crylink.md3"))
MODEL (CRYLINK_ITEM, W_Model("g_crylink.md3"))
MODEL (VORTEX_MUZZLEFLASH, "models/nexflash.md3")
MODEL (VORTEX_VIEW, W_Model("h_nex.iqm"))
MODEL (VORTEX_WORLD, W_Model("v_nex.md3"))
MODEL (VORTEX_ITEM, W_Model("g_nex.md3"))
MODEL (HAGAR_VIEW, W_Model("h_hagar.iqm"))
MODEL (HAGAR_WORLD, W_Model("v_hagar.md3"))
MODEL (HAGAR_ITEM, W_Model("g_hagar.md3"))
MODEL (DEVASTATOR_MUZZLEFLASH, "models/flash.md3")
MODEL (DEVASTATOR_VIEW, W_Model("h_rl.iqm"))
MODEL (DEVASTATOR_WORLD, W_Model("v_rl.md3"))
MODEL (DEVASTATOR_ITEM, W_Model("g_rl.md3"))
MODEL (PORTAL, "models/portal.md3")
MODEL (PORTO_VIEW, W_Model("h_porto.iqm"))
MODEL (PORTO_WORLD, W_Model("v_porto.md3"))
MODEL (PORTO_ITEM, W_Model("g_porto.md3"))
MODEL (VAPORIZER_MUZZLEFLASH, "models/nexflash.md3")
MODEL (VAPORIZER_VIEW, W_Model("h_minstanex.iqm"))
MODEL (VAPORIZER_WORLD, W_Model("v_minstanex.md3"))
MODEL (VAPORIZER_ITEM, W_Model("g_minstanex.md3"))
MODEL (HOOK, "models/hook.md3")
MODEL (HOOK_VIEW, W_Model("h_hookgun.iqm"))
MODEL (HOOK_WORLD, W_Model("v_hookgun.md3"))
MODEL (HOOK_ITEM, W_Model("g_hookgun.md3"))
MODEL (HLAC_VIEW, W_Model("h_hlac.iqm"))
MODEL (HLAC_WORLD, W_Model("v_hlac.md3"))
MODEL (HLAC_ITEM, W_Model("g_hlac.md3"))
MODEL (TUBA_VIEW, W_Model("h_tuba.iqm"))
MODEL (TUBA_WORLD, W_Model("v_tuba.md3"))
MODEL (TUBA_ITEM, W_Model("g_tuba.md3"))
MODEL (ACCORDION_VIEW, W_Model("h_akordeon.iqm"))
MODEL (ACCORDION_WORLD, W_Model("v_akordeon.md3"))
MODEL (KLEINBOTTLE_VIEW, W_Model("h_kleinbottle.iqm"))
MODEL (KLEINBOTTLE_WORLD, W_Model("v_kleinbottle.md3"))
MODEL (RIFLE_VIEW, W_Model("h_campingrifle.iqm"))
MODEL (RIFLE_WORLD, W_Model("v_campingrifle.md3"))
MODEL (RIFLE_ITEM, W_Model("g_campingrifle.md3"))
MODEL (FIREBALL_SPHERE, "models/sphere/sphere.md3")
MODEL (FIREBALL_VIEW, W_Model("h_fireball.iqm"))
MODEL (FIREBALL_WORLD, W_Model("v_fireball.md3"))
MODEL (FIREBALL_ITEM, W_Model("g_fireball.md3"))
MODEL (SEEKER_VIEW, W_Model("h_seeker.iqm"))
MODEL (SEEKER_WORLD, W_Model("v_seeker.md3"))
MODEL (SEEKER_ITEM, W_Model("g_seeker.md3"))
MODEL (SHOCKWAVE_MUZZLEFLASH, "models/uziflash.md3")
MODEL (SHOCKWAVE_VIEW, W_Model("h_shotgun.iqm"))
MODEL (SHOCKWAVE_WORLD, W_Model("v_shotgun.md3"))
MODEL (SHOCKWAVE_ITEM, W_Model("g_shotgun.md3"))
MODEL (ARC_MUZZLEFLASH, "models/flash.md3")
MODEL (ARC_VIEW, W_Model("h_arc.iqm"))
MODEL (ARC_WORLD, W_Model("v_arc.md3"))
MODEL (ARC_ITEM, W_Model("g_arc.md3"))
MODEL (HMG_MUZZLEFLASH, "models/uziflash.md3")
MODEL (HMG_VIEW, W_Model("h_ok_hmg.iqm"))
MODEL (HMG_WORLD, W_Model("v_ok_hmg.md3"))
MODEL (HMG_ITEM, W_Model("g_ok_hmg.md3"))
MODEL (RPC_MUZZLEFLASH, "models/flash.md3")
MODEL (RPC_VIEW, W_Model("h_ok_rl.iqm"))
MODEL (RPC_WORLD, W_Model("v_ok_rl.md3"))
MODEL (RPC_ITEM, W_Model("g_ok_rl.md3"))
MODEL (TUR_GIB_BASE1, "models/turrets/base-gib1.md3")
MODEL (TUR_GIB_BASE2, "models/turrets/base-gib2.md3")
MODEL (TUR_GIB_BASE3, "models/turrets/base-gib3.md3")
MODEL (TUR_GIB_BASE4, "models/turrets/base-gib4.md3")
MODEL (TUR_GIB_HEAD1, "models/turrets/head-gib1.md3")
MODEL (TUR_GIB_HEAD2, "models/turrets/head-gib2.md3")
MODEL (TUR_GIB_HEAD3, "models/turrets/head-gib3.md3")
MODEL (TUR_GIB_HEAD4, "models/turrets/head-gib4.md3")
MODEL (TUR_BASE, "models/turrets/base.md3")
MODEL (TUR_EWHEEL_BASE, "models/turrets/ewheel-base2.md3")
MODEL (TUR_EWHEEL_HEAD, "models/turrets/ewheel-gun1.md3")
MODEL (TUR_FLAC_BASE, "models/turrets/base.md3")
MODEL (TUR_FLAC_HEAD, "models/turrets/flac.md3")
MODEL (TUR_FUSIONREACTOR_BASE, "models/turrets/base.md3")
MODEL (TUR_FUSIONREACTOR_HEAD, "models/turrets/reactor.md3")
MODEL (TUR_HELLION_BASE, "models/turrets/base.md3")
MODEL (TUR_HELLION_HEAD, "models/turrets/hellion.md3")
MODEL (TUR_HK_BASE, "models/turrets/base.md3")
MODEL (TUR_HK_HEAD, "models/turrets/hk.md3")
MODEL (TUR_MACHINEGUN_BASE, "models/turrets/base.md3")
MODEL (TUR_MACHINEGUN_HEAD, "models/turrets/machinegun.md3")
MODEL (TUR_MIRS_BASE, "models/turrets/base.md3")
MODEL (TUR_MIRS_HEAD, "models/turrets/mlrs.md3")
MODEL (TUR_PHASER_BASE, "models/turrets/base.md3")
MODEL (TUR_PHASER_BEAM, "models/turrets/phaser_beam.md3")
MODEL (TUR_PHASER_HEAD, "models/turrets/phaser.md3")
MODEL (TUR_PLASMA_BASE, "models/turrets/base.md3")
MODEL (TUR_PLASMA_HEAD, "models/turrets/plasma.md3")
MODEL (TUR_PLASMA_DUAL_BASE, "models/turrets/base.md3")
MODEL (TUR_PLASMA_DUAL_HEAD, "models/turrets/plasmad.md3")
MODEL (TUR_TESLA_BASE, "models/turrets/tesla_base.md3")
MODEL (TUR_TESLA_HEAD, "models/turrets/tesla_head.md3")
MODEL (TUR_WALKER_BASE, "models/turrets/walker_body.md3")
MODEL (TUR_WALKER_HEAD, "models/turrets/walker_head_minigun.md3")
MODEL (VEH_SHIELD, "models/vhshield.md3")
MODEL (VEH_BUMBLEBEE_BODY, "models/vehicles/bumblebee_body.dpm")
MODEL (VEH_BUMBLEBEE_CANNON_CENTER, "models/vehicles/bumblebee_ray.dpm")
MODEL (VEH_BUMBLEBEE_CANNON_LEFT, "models/vehicles/bumblebee_plasma_left.dpm")
MODEL (VEH_BUMBLEBEE_CANNON_RIGHT, "models/vehicles/bumblebee_plasma_right.dpm")
MODEL (VEH_BUMBLEBEE_SHIELD, "models/vhshield.md3")
MODEL (VEH_RACER_BODY, "models/vehicles/wakizashi.dpm")
MODEL (VEH_RACER_VIEW, "models/vehicles/wakizashi_cockpit.dpm")
MODEL (VEH_RAPTOR_BODY, "models/vehicles/raptor.dpm")
MODEL (VEH_RAPTOR_CB_FOLDED, "models/vehicles/clusterbomb_folded.md3")
MODEL (VEH_RAPTOR_CB_FRAGMENT, "models/vehicles/clusterbomb_fragment.md3")
MODEL (VEH_RAPTOR_FLARE, "models/runematch/rune.mdl")
MODEL (VEH_RAPTOR_GUN, "models/vehicles/raptor_gun.dpm")
MODEL (VEH_RAPTOR_PROP, "models/vehicles/spinner.dpm")
MODEL (VEH_RAPTOR_TAIL, "models/vehicles/raptor_body.dpm")
MODEL (VEH_RAPTOR_VIEW, "models/vehicles/raptor_cockpit.dpm")
MODEL (VEH_SPIDERBOT_BODY, "models/vehicles/spiderbot.dpm")
MODEL (VEH_SPIDERBOT_GUN, "models/vehicles/spiderbot_barrels.dpm")
MODEL (VEH_SPIDERBOT_MUZZLEFLASH, "models/uziflash.md3")
MODEL (VEH_SPIDERBOT_TOP, "models/vehicles/spiderbot_top.dpm")
MODEL (VEH_SPIDERBOT_VIEW, "models/vehicles/spiderbot_cockpit.dpm")
MODEL (CHAT, "models/misc/chatbubble.spr")
MODEL (CHAT_MINIGAME, "models/sprites/minigame_busy.iqm")
MODEL (0, "models/sprites/0.spr32")
MODEL (1, "models/sprites/1.spr32")
MODEL (2, "models/sprites/2.spr32")
MODEL (3, "models/sprites/3.spr32")
MODEL (4, "models/sprites/4.spr32")
MODEL (5, "models/sprites/5.spr32")
MODEL (6, "models/sprites/6.spr32")
MODEL (7, "models/sprites/7.spr32")
MODEL (8, "models/sprites/8.spr32")
MODEL (9, "models/sprites/9.spr32")
MODEL (10, "models/sprites/10.spr32")
MODEL (WAYPOINT, "models/runematch/rune.mdl")
MODEL (MARKER, "models/marker.md3")
string W_Model (string w_mdl)
Function Documentation
MDL_GIB_ROBO_RANDOM()
Model MDL_GIB_ROBO_RANDOM ()
Definition at line 148 of file all.inc.
References floor(), MODEL(), random(), REGISTRY_GET, and W_Model().
{
     int i = floor(random() * 8);
     return REGISTRY_GET(Models, MDL_GIB_ROBO_1.m_id + i);
 }
MDL_NUM()
Model MDL_NUM (int i)
Definition at line 351 of file all.inc.
References MODEL(), and REGISTRY_GET.
Referenced by DragBox_Think(), and KillIndicator_Think().
                      {
     if ((i >= 0 && i <= 10))
         return REGISTRY_GET(Models, MDL_0.m_id + i);
     return MDL_Null;
 }
MODEL() [1/259]
MODEL (CTF_SHIELD , "models/ctf/shield.md3")
Referenced by MDL_GIB_ROBO_RANDOM(), and MDL_NUM().
MODEL() [2/259]
MODEL (CTF_CAPTURE , "models/ctf/shockwavetransring.md3")
MODEL() [3/259]
MODEL (CTF_FLAG , "models/ctf/flags.md3")
MODEL() [4/259]
MODEL (DOM_NEUTRAL , "models/domination/dom_unclaimed.md3")
MODEL() [5/259]
MODEL (DOM_RED , "models/domination/dom_red.md3")
MODEL() [6/259]
MODEL (DOM_BLUE , "models/domination/dom_blue.md3")
MODEL() [7/259]
MODEL (DOM_YELLOW , "models/domination/dom_yellow.md3")
MODEL() [8/259]
MODEL (DOM_PINK , "models/domination/dom_pink.md3")
MODEL() [9/259]
MODEL (ICE , "models/ice/ice.md3")
MODEL() [10/259]
MODEL (KH_KEY , "models/keyhunt/key.md3")
MODEL() [11/259]
MODEL (OK_HMG , W_Model("g_ok_hmg.md3"))
MODEL() [12/259]
MODEL (OK_RPC , W_Model("g_ok_rl.md3"))
MODEL() [13/259]
MODEL (OK_MG_VIEW , W_Model("h_ok_mg.iqm"))
MODEL() [14/259]
MODEL (OK_MG_WORLD , W_Model("v_ok_mg.md3"))
MODEL() [15/259]
MODEL (OK_MG_ITEM , W_Model("g_ok_mg.md3"))
MODEL() [16/259]
MODEL (OK_SHOTGUN_VIEW , W_Model("h_ok_shotgun.iqm"))
MODEL() [17/259]
MODEL (OK_SHOTGUN_WORLD , W_Model("v_ok_shotgun.md3"))
MODEL() [18/259]
MODEL (OK_SHOTGUN_ITEM , W_Model("g_ok_shotgun.md3"))
MODEL() [19/259]
MODEL (OK_SNIPER_VIEW , W_Model("h_ok_sniper.iqm"))
MODEL() [20/259]
MODEL (OK_SNIPER_WORLD , W_Model("v_ok_sniper.md3"))
MODEL() [21/259]
MODEL (OK_SNIPER_ITEM , W_Model("g_ok_sniper.md3"))
MODEL() [22/259]
MODEL (ONS_CP , "models/onslaught/controlpoint_icon.md3")
MODEL() [23/259]
MODEL (ONS_CP_SHIELD , "models/onslaught/controlpoint_shield.md3")
MODEL() [24/259]
MODEL (ONS_CP_PAD1 , "models/onslaught/controlpoint_pad.md3")
MODEL() [25/259]
MODEL (ONS_CP_PAD2 , "models/onslaught/controlpoint_pad2.md3")
MODEL() [26/259]
MODEL (ONS_CP1 , "models/onslaught/controlpoint_icon_dmg1.md3")
MODEL() [27/259]
MODEL (ONS_CP1_GIB , "models/onslaught/controlpoint_icon_gib1.md3")
MODEL() [28/259]
MODEL (ONS_CP2 , "models/onslaught/controlpoint_icon_dmg2.md3")
MODEL() [29/259]
MODEL (ONS_CP2_GIB , "models/onslaught/controlpoint_icon_gib2.md3")
MODEL() [30/259]
MODEL (ONS_CP3 , "models/onslaught/controlpoint_icon_dmg3.md3")
MODEL() [31/259]
MODEL (ONS_CP3_GIB , "models/onslaught/controlpoint_icon_gib4.md3")
MODEL() [32/259]
MODEL (ONS_RAY , "models/onslaught/ons_ray.md3")
MODEL() [33/259]
MODEL (ONS_GEN , "models/onslaught/generator.md3")
MODEL() [34/259]
MODEL (ONS_GEN_SHIELD , "models/onslaught/generator_shield.md3")
MODEL() [35/259]
MODEL (ONS_GEN_GIB1 , "models/onslaught/gen_gib1.md3")
MODEL() [36/259]
MODEL (ONS_GEN_GIB2 , "models/onslaught/gen_gib2.md3")
MODEL() [37/259]
MODEL (ONS_GEN_GIB3 , "models/onslaught/gen_gib3.md3")
MODEL() [38/259]
MODEL (ONS_GEN1 , "models/onslaught/generator_dmg1.md3")
MODEL() [39/259]
MODEL (ONS_GEN2 , "models/onslaught/generator_dmg2.md3")
MODEL() [40/259]
MODEL (ONS_GEN3 , "models/onslaught/generator_dmg3.md3")
MODEL() [41/259]
MODEL (ONS_GEN4 , "models/onslaught/generator_dmg4.md3")
MODEL() [42/259]
MODEL (ONS_GEN5 , "models/onslaught/generator_dmg5.md3")
MODEL() [43/259]
MODEL (ONS_GEN6 , "models/onslaught/generator_dmg6.md3")
MODEL() [44/259]
MODEL (ONS_GEN7 , "models/onslaught/generator_dmg7.md3")
MODEL() [45/259]
MODEL (ONS_GEN8 , "models/onslaught/generator_dmg8.md3")
MODEL() [46/259]
MODEL (ONS_GEN9 , "models/onslaught/generator_dmg9.md3")
MODEL() [47/259]
MODEL (ONS_GEN_DEAD , "models/onslaught/generator_dead.md3")
MODEL() [48/259]
MODEL (PROJECTILE_ELECTRO , "models/ebomb.mdl")
MODEL() [49/259]
MODEL (PROJECTILE_ELECTRO_BEAM , "models/elaser.mdl")
MODEL() [50/259]
MODEL (PROJECTILE_ROCKET , "models/rocket.md3")
MODEL() [51/259]
MODEL (PROJECTILE_CRYLINK , "models/plasmatrail.mdl")
MODEL() [52/259]
MODEL (PROJECTILE_CRYLINK_BOUNCING , "models/plasmatrail.mdl")
MODEL() [53/259]
MODEL (PROJECTILE_GRENADE , "models/grenademodel.md3")
MODEL() [54/259]
MODEL (PROJECTILE_GRENADE_BOUNCING , "models/grenademodel.md3")
MODEL() [55/259]
MODEL (PROJECTILE_MINE , "models/mine.md3")
MODEL() [56/259]
MODEL (PROJECTILE_BLASTER , "models/laser.mdl")
MODEL() [57/259]
MODEL (PROJECTILE_HLAC , "models/hlac_bullet.md3")
MODEL() [58/259]
MODEL (PROJECTILE_PORTO_RED , "models/grenademodel.md3")
MODEL() [59/259]
MODEL (PROJECTILE_PORTO_BLUE , "models/grenademodel.md3")
MODEL() [60/259]
MODEL (PROJECTILE_HOOKBOMB , "models/grenademodel.md3")
MODEL() [61/259]
MODEL (PROJECTILE_HAGAR , "models/hagarmissile.mdl")
MODEL() [62/259]
MODEL (PROJECTILE_HAGAR_BOUNCING , "models/hagarmissile.mdl")
MODEL() [63/259]
MODEL (PROJECTILE_ARC_BOLT , "models/ebomb.mdl")
MODEL() [64/259]
MODEL (PROJECTILE_NAPALM_FOUNTAIN , "null")
MODEL() [65/259]
MODEL (PROJECTILE_FIREBALL , "null")
MODEL() [66/259]
MODEL (PROJECTILE_FIREMINE , "null")
MODEL() [67/259]
MODEL (PROJECTILE_TAG , "models/laser.mdl")
MODEL() [68/259]
MODEL (PROJECTILE_FLAC , "models/hagarmissile.mdl")
MODEL() [69/259]
MODEL (PROJECTILE_SEEKER , "models/tagrocket.md3")
MODEL() [70/259]
MODEL (PROJECTILE_MAGE_SPIKE , "models/ebomb.mdl")
MODEL() [71/259]
MODEL (PROJECTILE_SHAMBLER_LIGHTNING , "models/ebomb.mdl")
MODEL() [72/259]
MODEL (PROJECTILE_RAPTORBOMB , "models/vehicles/clusterbomb.md3")
MODEL() [73/259]
MODEL (PROJECTILE_RAPTORBOMBLET , "models/vehicles/bomblet.md3")
MODEL() [74/259]
MODEL (PROJECTILE_RAPTORCANNON , "models/plasmatrail.mdl")
MODEL() [75/259]
MODEL (PROJECTILE_SPIDERROCKET , "models/vehicles/rocket02.md3")
MODEL() [76/259]
MODEL (PROJECTILE_WAKIROCKET , "models/vehicles/rocket01.md3")
MODEL() [77/259]
MODEL (PROJECTILE_WAKICANNON , "models/laser.mdl")
MODEL() [78/259]
MODEL (PROJECTILE_BUMBLE_GUN , "models/elaser.mdl")
MODEL() [79/259]
MODEL (PROJECTILE_BUMBLE_BEAM , "models/elaser.mdl")
MODEL() [80/259]
MODEL (PROJECTILE_RPC , W_Model("ok_rocket.md3"))
MODEL() [81/259]
MODEL (PROJECTILE_ROCKETMINSTA_LASER , "models/elaser.mdl")
MODEL() [82/259]
MODEL (PROJECTILE_NADE , W_Model("v_ok_grenade.md3"))
MODEL() [83/259]
MODEL (NADE_VIEW , W_Model("h_ok_grenade.iqm"))
MODEL() [84/259]
MODEL (NADE_TIMER , "models/ok_nade_counter/ok_nade_counter.md3")
MODEL() [85/259]
MODEL (NADE_ORB , "models/ctf/shield.md3")
MODEL() [86/259]
MODEL (GIB_CHUNK , "models/gibs/chunk.mdl")
MODEL() [87/259]
MODEL (GIB_LEG1 , "models/gibs/leg1.md3")
MODEL() [88/259]
MODEL (GIB_LEG2 , "models/gibs/leg2.md3")
MODEL() [89/259]
MODEL (GIB_CHEST , "models/gibs/chest.md3")
MODEL() [90/259]
MODEL (GIB_SMALLCHEST , "models/gibs/smallchest.md3")
MODEL() [91/259]
MODEL (GIB_ARM , "models/gibs/arm.md3")
MODEL() [92/259]
MODEL (GIB_BLOODYSKULL , "models/gibs/bloodyskull.md3")
MODEL() [93/259]
MODEL (GIB_EYE , "models/gibs/eye.md3")
MODEL() [94/259]
MODEL (GIB_ROBO , "models/gibs/robo.md3")
MODEL() [95/259]
MODEL (GIB_ROBO_1 , "models/gibs/robo1.md3")
MODEL() [96/259]
MODEL (GIB_ROBO_2 , "models/gibs/robo2.md3")
MODEL() [97/259]
MODEL (GIB_ROBO_3 , "models/gibs/robo3.md3")
MODEL() [98/259]
MODEL (GIB_ROBO_4 , "models/gibs/robo4.md3")
MODEL() [99/259]
MODEL (GIB_ROBO_5 , "models/gibs/robo5.md3")
MODEL() [100/259]
MODEL (GIB_ROBO_6 , "models/gibs/robo6.md3")
MODEL() [101/259]
MODEL (GIB_ROBO_7 , "models/gibs/robo7.md3")
MODEL() [102/259]
MODEL (GIB_ROBO_8 , "models/gibs/robo8.md3")
MODEL() [103/259]
MODEL (CASING_SHELL , "models/casing_shell.mdl")
MODEL() [104/259]
MODEL (CASING_BULLET , "models/casing_bronze.iqm")
MODEL() [105/259]
MODEL (BUFF , "models/relics/relic.md3")
MODEL() [106/259]
MODEL (BLASTER_VIEW , W_Model("h_laser.iqm"))
MODEL() [107/259]
MODEL (BLASTER_WORLD , W_Model("v_laser.md3"))
MODEL() [108/259]
MODEL (BLASTER_ITEM , W_Model("g_laser.md3"))
MODEL() [109/259]
MODEL (SHOTGUN_MUZZLEFLASH , "models/uziflash.md3")
MODEL() [110/259]
MODEL (SHOTGUN_VIEW , W_Model("h_shotgun.iqm"))
MODEL() [111/259]
MODEL (SHOTGUN_WORLD , W_Model("v_shotgun.md3"))
MODEL() [112/259]
MODEL (SHOTGUN_ITEM , W_Model("g_shotgun.md3"))
MODEL() [113/259]
MODEL (MACHINEGUN_MUZZLEFLASH , "models/uziflash.md3")
MODEL() [114/259]
MODEL (MACHINEGUN_VIEW , W_Model("h_uzi.iqm"))
MODEL() [115/259]
MODEL (MACHINEGUN_WORLD , W_Model("v_uzi.md3"))
MODEL() [116/259]
MODEL (MACHINEGUN_ITEM , W_Model("g_uzi.md3"))
MODEL() [117/259]
MODEL (MORTAR_VIEW , W_Model("h_gl.iqm"))
MODEL() [118/259]
MODEL (MORTAR_WORLD , W_Model("v_gl.md3"))
MODEL() [119/259]
MODEL (MORTAR_ITEM , W_Model("g_gl.md3"))
MODEL() [120/259]
MODEL (MINELAYER_MUZZLEFLASH , "models/flash.md3")
MODEL() [121/259]
MODEL (MINELAYER_MINE , "models/mine.md3")
MODEL() [122/259]
MODEL (MINELAYER_VIEW , W_Model("h_minelayer.iqm"))
MODEL() [123/259]
MODEL (MINELAYER_WORLD , W_Model("v_minelayer.md3"))
MODEL() [124/259]
MODEL (MINELAYER_ITEM , W_Model("g_minelayer.md3"))
MODEL() [125/259]
MODEL (ELECTRO_VIEW , W_Model("h_electro.iqm"))
MODEL() [126/259]
MODEL (ELECTRO_WORLD , W_Model("v_electro.md3"))
MODEL() [127/259]
MODEL (ELECTRO_ITEM , W_Model("g_electro.md3"))
MODEL() [128/259]
MODEL (CRYLINK_VIEW , W_Model("h_crylink.iqm"))
MODEL() [129/259]
MODEL (CRYLINK_WORLD , W_Model("v_crylink.md3"))
MODEL() [130/259]
MODEL (CRYLINK_ITEM , W_Model("g_crylink.md3"))
MODEL() [131/259]
MODEL (VORTEX_MUZZLEFLASH , "models/nexflash.md3")
MODEL() [132/259]
MODEL (VORTEX_VIEW , W_Model("h_nex.iqm"))
MODEL() [133/259]
MODEL (VORTEX_WORLD , W_Model("v_nex.md3"))
MODEL() [134/259]
MODEL (VORTEX_ITEM , W_Model("g_nex.md3"))
MODEL() [135/259]
MODEL (HAGAR_VIEW , W_Model("h_hagar.iqm"))
MODEL() [136/259]
MODEL (HAGAR_WORLD , W_Model("v_hagar.md3"))
MODEL() [137/259]
MODEL (HAGAR_ITEM , W_Model("g_hagar.md3"))
MODEL() [138/259]
MODEL (DEVASTATOR_MUZZLEFLASH , "models/flash.md3")
MODEL() [139/259]
MODEL (DEVASTATOR_VIEW , W_Model("h_rl.iqm"))
MODEL() [140/259]
MODEL (DEVASTATOR_WORLD , W_Model("v_rl.md3"))
MODEL() [141/259]
MODEL (DEVASTATOR_ITEM , W_Model("g_rl.md3"))
MODEL() [142/259]
MODEL (PORTAL , "models/portal.md3")
MODEL() [143/259]
MODEL (PORTO_VIEW , W_Model("h_porto.iqm"))
MODEL() [144/259]
MODEL (PORTO_WORLD , W_Model("v_porto.md3"))
MODEL() [145/259]
MODEL (PORTO_ITEM , W_Model("g_porto.md3"))
MODEL() [146/259]
MODEL (VAPORIZER_MUZZLEFLASH , "models/nexflash.md3")
MODEL() [147/259]
MODEL (VAPORIZER_VIEW , W_Model("h_minstanex.iqm"))
MODEL() [148/259]
MODEL (VAPORIZER_WORLD , W_Model("v_minstanex.md3"))
MODEL() [149/259]
MODEL (VAPORIZER_ITEM , W_Model("g_minstanex.md3"))
MODEL() [150/259]
MODEL (HOOK , "models/hook.md3")
MODEL() [151/259]
MODEL (HOOK_VIEW , W_Model("h_hookgun.iqm"))
MODEL() [152/259]
MODEL (HOOK_WORLD , W_Model("v_hookgun.md3"))
MODEL() [153/259]
MODEL (HOOK_ITEM , W_Model("g_hookgun.md3"))
MODEL() [154/259]
MODEL (HLAC_VIEW , W_Model("h_hlac.iqm"))
MODEL() [155/259]
MODEL (HLAC_WORLD , W_Model("v_hlac.md3"))
MODEL() [156/259]
MODEL (HLAC_ITEM , W_Model("g_hlac.md3"))
MODEL() [157/259]
MODEL (TUBA_VIEW , W_Model("h_tuba.iqm"))
MODEL() [158/259]
MODEL (TUBA_WORLD , W_Model("v_tuba.md3"))
MODEL() [159/259]
MODEL (TUBA_ITEM , W_Model("g_tuba.md3"))
MODEL() [160/259]
MODEL (ACCORDION_VIEW , W_Model("h_akordeon.iqm"))
MODEL() [161/259]
MODEL (ACCORDION_WORLD , W_Model("v_akordeon.md3"))
MODEL() [162/259]
MODEL (KLEINBOTTLE_VIEW , W_Model("h_kleinbottle.iqm"))
MODEL() [163/259]
MODEL (KLEINBOTTLE_WORLD , W_Model("v_kleinbottle.md3"))
MODEL() [164/259]
MODEL (RIFLE_VIEW , W_Model("h_campingrifle.iqm"))
MODEL() [165/259]
MODEL (RIFLE_WORLD , W_Model("v_campingrifle.md3"))
MODEL() [166/259]
MODEL (RIFLE_ITEM , W_Model("g_campingrifle.md3"))
MODEL() [167/259]
MODEL (FIREBALL_SPHERE , "models/sphere/sphere.md3")
MODEL() [168/259]
MODEL (FIREBALL_VIEW , W_Model("h_fireball.iqm"))
MODEL() [169/259]
MODEL (FIREBALL_WORLD , W_Model("v_fireball.md3"))
MODEL() [170/259]
MODEL (FIREBALL_ITEM , W_Model("g_fireball.md3"))
MODEL() [171/259]
MODEL (SEEKER_VIEW , W_Model("h_seeker.iqm"))
MODEL() [172/259]
MODEL (SEEKER_WORLD , W_Model("v_seeker.md3"))
MODEL() [173/259]
MODEL (SEEKER_ITEM , W_Model("g_seeker.md3"))
MODEL() [174/259]
MODEL (SHOCKWAVE_MUZZLEFLASH , "models/uziflash.md3")
MODEL() [175/259]
MODEL (SHOCKWAVE_VIEW , W_Model("h_shotgun.iqm"))
MODEL() [176/259]
MODEL (SHOCKWAVE_WORLD , W_Model("v_shotgun.md3"))
MODEL() [177/259]
MODEL (SHOCKWAVE_ITEM , W_Model("g_shotgun.md3"))
MODEL() [178/259]
MODEL (ARC_MUZZLEFLASH , "models/flash.md3")
MODEL() [179/259]
MODEL (ARC_VIEW , W_Model("h_arc.iqm"))
MODEL() [180/259]
MODEL (ARC_WORLD , W_Model("v_arc.md3"))
MODEL() [181/259]
MODEL (ARC_ITEM , W_Model("g_arc.md3"))
MODEL() [182/259]
MODEL (HMG_MUZZLEFLASH , "models/uziflash.md3")
MODEL() [183/259]
MODEL (HMG_VIEW , W_Model("h_ok_hmg.iqm"))
MODEL() [184/259]
MODEL (HMG_WORLD , W_Model("v_ok_hmg.md3"))
MODEL() [185/259]
MODEL (HMG_ITEM , W_Model("g_ok_hmg.md3"))
MODEL() [186/259]
MODEL (RPC_MUZZLEFLASH , "models/flash.md3")
MODEL() [187/259]
MODEL (RPC_VIEW , W_Model("h_ok_rl.iqm"))
MODEL() [188/259]
MODEL (RPC_WORLD , W_Model("v_ok_rl.md3"))
MODEL() [189/259]
MODEL (RPC_ITEM , W_Model("g_ok_rl.md3"))
MODEL() [190/259]
MODEL (TUR_GIB_BASE1 , "models/turrets/base-gib1.md3")
MODEL() [191/259]
MODEL (TUR_GIB_BASE2 , "models/turrets/base-gib2.md3")
MODEL() [192/259]
MODEL (TUR_GIB_BASE3 , "models/turrets/base-gib3.md3")
MODEL() [193/259]
MODEL (TUR_GIB_BASE4 , "models/turrets/base-gib4.md3")
MODEL() [194/259]
MODEL (TUR_GIB_HEAD1 , "models/turrets/head-gib1.md3")
MODEL() [195/259]
MODEL (TUR_GIB_HEAD2 , "models/turrets/head-gib2.md3")
MODEL() [196/259]
MODEL (TUR_GIB_HEAD3 , "models/turrets/head-gib3.md3")
MODEL() [197/259]
MODEL (TUR_GIB_HEAD4 , "models/turrets/head-gib4.md3")
MODEL() [198/259]
MODEL (TUR_BASE , "models/turrets/base.md3")
MODEL() [199/259]
MODEL (TUR_EWHEEL_BASE , "models/turrets/ewheel-base2.md3")
MODEL() [200/259]
MODEL (TUR_EWHEEL_HEAD , "models/turrets/ewheel-gun1.md3")
MODEL() [201/259]
MODEL (TUR_FLAC_BASE , "models/turrets/base.md3")
MODEL() [202/259]
MODEL (TUR_FLAC_HEAD , "models/turrets/flac.md3")
MODEL() [203/259]
MODEL (TUR_FUSIONREACTOR_BASE , "models/turrets/base.md3")
MODEL() [204/259]
MODEL (TUR_FUSIONREACTOR_HEAD , "models/turrets/reactor.md3")
MODEL() [205/259]
MODEL (TUR_HELLION_BASE , "models/turrets/base.md3")
MODEL() [206/259]
MODEL (TUR_HELLION_HEAD , "models/turrets/hellion.md3")
MODEL() [207/259]
MODEL (TUR_HK_BASE , "models/turrets/base.md3")
MODEL() [208/259]
MODEL (TUR_HK_HEAD , "models/turrets/hk.md3")
MODEL() [209/259]
MODEL (TUR_MACHINEGUN_BASE , "models/turrets/base.md3")
MODEL() [210/259]
MODEL (TUR_MACHINEGUN_HEAD , "models/turrets/machinegun.md3")
MODEL() [211/259]
MODEL (TUR_MIRS_BASE , "models/turrets/base.md3")
MODEL() [212/259]
MODEL (TUR_MIRS_HEAD , "models/turrets/mlrs.md3")
MODEL() [213/259]
MODEL (TUR_PHASER_BASE , "models/turrets/base.md3")
MODEL() [214/259]
MODEL (TUR_PHASER_BEAM , "models/turrets/phaser_beam.md3")
MODEL() [215/259]
MODEL (TUR_PHASER_HEAD , "models/turrets/phaser.md3")
MODEL() [216/259]
MODEL (TUR_PLASMA_BASE , "models/turrets/base.md3")
MODEL() [217/259]
MODEL (TUR_PLASMA_HEAD , "models/turrets/plasma.md3")
MODEL() [218/259]
MODEL (TUR_PLASMA_DUAL_BASE , "models/turrets/base.md3")
MODEL() [219/259]
MODEL (TUR_PLASMA_DUAL_HEAD , "models/turrets/plasmad.md3")
MODEL() [220/259]
MODEL (TUR_TESLA_BASE , "models/turrets/tesla_base.md3")
MODEL() [221/259]
MODEL (TUR_TESLA_HEAD , "models/turrets/tesla_head.md3")
MODEL() [222/259]
MODEL (TUR_WALKER_BASE , "models/turrets/walker_body.md3")
MODEL() [223/259]
MODEL (TUR_WALKER_HEAD , "models/turrets/walker_head_minigun.md3")
MODEL() [224/259]
MODEL (VEH_SHIELD , "models/vhshield.md3")
MODEL() [225/259]
MODEL (VEH_BUMBLEBEE_BODY , "models/vehicles/bumblebee_body.dpm")
MODEL() [226/259]
MODEL (VEH_BUMBLEBEE_CANNON_CENTER , "models/vehicles/bumblebee_ray.dpm")
MODEL() [227/259]
MODEL (VEH_BUMBLEBEE_CANNON_LEFT , "models/vehicles/bumblebee_plasma_left.dpm")
MODEL() [228/259]
MODEL (VEH_BUMBLEBEE_CANNON_RIGHT , "models/vehicles/bumblebee_plasma_right.dpm")
MODEL() [229/259]
MODEL (VEH_BUMBLEBEE_SHIELD , "models/vhshield.md3")
MODEL() [230/259]
MODEL (VEH_RACER_BODY , "models/vehicles/wakizashi.dpm")
MODEL() [231/259]
MODEL (VEH_RACER_VIEW , "models/vehicles/wakizashi_cockpit.dpm")
MODEL() [232/259]
MODEL (VEH_RAPTOR_BODY , "models/vehicles/raptor.dpm")
MODEL() [233/259]
MODEL (VEH_RAPTOR_CB_FOLDED , "models/vehicles/clusterbomb_folded.md3")
MODEL() [234/259]
MODEL (VEH_RAPTOR_CB_FRAGMENT , "models/vehicles/clusterbomb_fragment.md3")
MODEL() [235/259]
MODEL (VEH_RAPTOR_FLARE , "models/runematch/rune.mdl")
MODEL() [236/259]
MODEL (VEH_RAPTOR_GUN , "models/vehicles/raptor_gun.dpm")
MODEL() [237/259]
MODEL (VEH_RAPTOR_PROP , "models/vehicles/spinner.dpm")
MODEL() [238/259]
MODEL (VEH_RAPTOR_TAIL , "models/vehicles/raptor_body.dpm")
MODEL() [239/259]
MODEL (VEH_RAPTOR_VIEW , "models/vehicles/raptor_cockpit.dpm")
MODEL() [240/259]
MODEL (VEH_SPIDERBOT_BODY , "models/vehicles/spiderbot.dpm")
MODEL() [241/259]
MODEL (VEH_SPIDERBOT_GUN , "models/vehicles/spiderbot_barrels.dpm")
MODEL() [242/259]
MODEL (VEH_SPIDERBOT_MUZZLEFLASH , "models/uziflash.md3")
MODEL() [243/259]
MODEL (VEH_SPIDERBOT_TOP , "models/vehicles/spiderbot_top.dpm")
MODEL() [244/259]
MODEL (VEH_SPIDERBOT_VIEW , "models/vehicles/spiderbot_cockpit.dpm")
MODEL() [245/259]
MODEL (CHAT , "models/misc/chatbubble.spr")
MODEL() [246/259]
MODEL (CHAT_MINIGAME , "models/sprites/minigame_busy.iqm")
MODEL() [247/259]
MODEL (0 , "models/sprites/0.spr32")
MODEL() [248/259]
MODEL (1 , "models/sprites/1.spr32")
MODEL() [249/259]
MODEL (2 , "models/sprites/2.spr32")
MODEL() [250/259]
MODEL (3 , "models/sprites/3.spr32")
MODEL() [251/259]
MODEL (4 , "models/sprites/4.spr32")
MODEL() [252/259]
MODEL (5 , "models/sprites/5.spr32")
MODEL() [253/259]
MODEL (6 , "models/sprites/6.spr32")
MODEL() [254/259]
MODEL (7 , "models/sprites/7.spr32")
MODEL() [255/259]
MODEL (8 , "models/sprites/8.spr32")
MODEL() [256/259]
MODEL (9 , "models/sprites/9.spr32")
MODEL() [257/259]
MODEL (10 , "models/sprites/10.spr32")
MODEL() [258/259]
MODEL (WAYPOINT , "models/runematch/rune.mdl")
MODEL() [259/259]
MODEL (MARKER , "models/marker.md3")
W_Model()
string W_Model (string w_mdl)
Definition at line 270 of file all.qc.
Referenced by CL_ExteriorWeaponentity_Think(), and MDL_GIB_ROBO_RANDOM().
 {
     string output = strcat("models/weapons/", w_mdl);
     MUTATOR_CALLHOOK(WeaponModel, w_mdl, output);
     return M_ARGV(1, string);
 }