Xonotic: common/mutators/mutator/melee_only/sv_melee_only.qc File Reference
sv_melee_only.qc File Reference
#include "sv_melee_only.qh"
#include "../overkill/sv_overkill.qh"
Functions
MUTATOR_HOOKFUNCTION (melee_only, SetStartItems, CBC_ORDER_LAST)
MUTATOR_HOOKFUNCTION (melee_only, SetWeaponArena)
MUTATOR_HOOKFUNCTION (melee_only, ForbidRandomStartWeapons)
MUTATOR_HOOKFUNCTION (melee_only, ForbidThrowCurrentWeapon)
MUTATOR_HOOKFUNCTION (melee_only, FilterItemDefinition)
MUTATOR_HOOKFUNCTION (melee_only, BuildMutatorsString)
MUTATOR_HOOKFUNCTION (melee_only, BuildMutatorsPrettyString)
REGISTER_MUTATOR (melee_only, expr_evaluate(autocvar_g_melee_only)&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok)&&!g_nexball)
Variables
string autocvar_g_melee_only
Function Documentation
MUTATOR_HOOKFUNCTION (melee_only , SetStartItems , CBC_ORDER_LAST)
Definition at line 8 of file sv_melee_only.qc.
References start_ammo_shells, start_weapons, warmup_start_ammo_shells, warmup_start_weapons, and WEPSET.
 {
     start_ammo_shells = warmup_start_ammo_shells = 0;
     start_weapons = warmup_start_weapons = WEPSET(SHOTGUN);
 }
MUTATOR_HOOKFUNCTION (melee_only , SetWeaponArena)
Definition at line 14 of file sv_melee_only.qc.
References M_ARGV.
 {
     // turn weapon arena off
     M_ARGV(0, string) = "off";
 }
MUTATOR_HOOKFUNCTION (melee_only , ForbidRandomStartWeapons)
Definition at line 20 of file sv_melee_only.qc.
 {
     return true;
 }
MUTATOR_HOOKFUNCTION (melee_only , ForbidThrowCurrentWeapon)
Definition at line 25 of file sv_melee_only.qc.
 {
     return true;
 }
MUTATOR_HOOKFUNCTION (melee_only , FilterItemDefinition)
Definition at line 30 of file sv_melee_only.qc.
References entity(), and M_ARGV.
 {
     entity definition = M_ARGV(0, entity);
     switch (definition)
     {
         case ITEM_HealthSmall:
         case ITEM_ArmorSmall:
             return false;
     }
     return true;
 }
MUTATOR_HOOKFUNCTION (melee_only , BuildMutatorsString)
Definition at line 44 of file sv_melee_only.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ":MeleeOnly");
 }
MUTATOR_HOOKFUNCTION (melee_only , BuildMutatorsPrettyString)
Definition at line 49 of file sv_melee_only.qc.
References M_ARGV, and strcat().
 {
     M_ARGV(0, string) = strcat(M_ARGV(0, string), ", Melee Only Arena");
 }
REGISTER_MUTATOR (melee_only , expr_evaluate(autocvar_g_melee_only)&&!MUTATOR_IS_ENABLED(mutator_instagib)&&!MUTATOR_IS_ENABLED(ok)&&! g_nexball)
Variable Documentation
string autocvar_g_melee_only
Definition at line 5 of file sv_melee_only.qc.