Xonotic: server/g_lights.qc File Reference
g_lights.qc File Reference
#include "g_lights.qh"
Functions
void dynlight_find_aiment (entity this)
void dynlight_find_path (entity this)
void dynlight_find_target (entity this)
void dynlight_think (entity this)
void dynlight_use (entity this, entity actor, entity trigger)
spawnfunc (dynlight)
void train_next (entity this)
Variables
vector color
const float DFOLLOW = 4
const float DNOSHADOW = 2
string dtagname
float lefty
float light_lev
const float LOOP = 1
float speed
Function Documentation
void dynlight_find_aiment (entity this)
Definition at line 44 of file g_lights.qc.
References aiment, angles, dynlight_think(), entity(), find(), MOVETYPE_FOLLOW, nextthink, NULL, objerror(), origin, owner, punchangle, set_movetype(), setthink, target, targetname, time, v_angle, and view_ofs.
Referenced by spawnfunc().
 {
     entity targ;
     if (!this.target)
         objerror (this, "dynlight: no target to follow");
     targ = find(NULL, targetname, this.target);
     set_movetype(this, MOVETYPE_FOLLOW);
     this.aiment = targ;
     this.owner = targ;
     this.punchangle = targ.angles;
     this.view_ofs = this.origin - targ.origin;
     this.v_angle = this.angles - targ.angles;
     setthink(this, dynlight_think);
     this.nextthink = time + 0.1;
 }
void dynlight_find_path (entity this)
Definition at line 60 of file g_lights.qc.
References entity(), find(), nextthink, NULL, objerror(), setthink, target, targetname, time, and train_next().
Referenced by spawnfunc().
 {
     entity targ;
     if (!this.target)
         objerror (this, "dynlight: no target to follow");
     targ = find(NULL, targetname, this.target);
     this.target = targ.target;
     setorigin(this, targ.origin);
     setthink(this, train_next);
     this.nextthink = time + 0.1;
 }
void dynlight_find_target (entity this)
Definition at line 72 of file g_lights.qc.
References dtagname, dynlight_think(), entity(), find(), nextthink, NULL, objerror(), owner, setthink, target, targetname, and time.
Referenced by spawnfunc().
 {
     entity targ;
     if (!this.target)
         objerror (this, "dynlight: no target to follow");
     targ = find(NULL, targetname, this.target);
     setattachment(this, targ, this.dtagname);
     this.owner = targ;
     setthink(this, dynlight_think);
     this.nextthink = time + 0.1;
 }
void dynlight_think (entity this)
Definition at line 37 of file g_lights.qc.
References nextthink, owner, and time.
Referenced by dynlight_find_aiment(), and dynlight_find_target().
 {
     if(!this.owner)
         delete(this);
     this.nextthink = time + 0.1;
 }
void dynlight_use (entity this, entity actor, entity trigger)
Definition at line 84 of file g_lights.qc.
References lefty, and light_lev.
Referenced by spawnfunc().
 {
     if (this.light_lev == 0)
         this.light_lev = this.lefty;
     else
         this.light_lev = 0;
 }
spawnfunc (dynlight)
Definition at line 91 of file g_lights.qc.
References color, DFOLLOW, dtagname, dynlight_find_aiment(), dynlight_find_path(), dynlight_find_target(), dynlight_use(), InitializeEntity(), INITPRIO_FINDTARGET, lefty, light_lev, MOVETYPE_NOCLIP, origin, set_movetype(), solid, SOLID_NOT, spawnflags, speed, target, and use.
 {
     if (!this.light_lev)
         this.light_lev = 200;
     if (!this.color)
         this.color = '1 1 1';
     this.lefty = this.light_lev;
     this.use = dynlight_use;
     setsize (this, '0 0 0', '0 0 0');
     setorigin(this, this.origin);
     //this.pflags = PFLAGS_FULLDYNAMIC;
     this.solid = SOLID_NOT;
     //this.blocked = func_null;
     //if (this.spawnflags & DNOSHADOW)
     //  this.pflags = this.pflags + PFLAGS_NOSHADOW;
     //if (this.spawnflags & START_OFF)
     //  this.light_lev = 0;
 //tag attaching
     if (this.dtagname)
     {
         InitializeEntity(this, dynlight_find_target, INITPRIO_FINDTARGET);
         return;
     }
 // entity following
     if (this.spawnflags & DFOLLOW)
     {
         InitializeEntity(this, dynlight_find_aiment, INITPRIO_FINDTARGET);
         return;
     }
 // path following
     if (this.target)
 //  if (!(this.spawnflags & DFOLLOW))
     {
         set_movetype(this, MOVETYPE_NOCLIP);
         if (!this.speed)
             this.speed = 100;
         InitializeEntity(this, dynlight_find_path, INITPRIO_FINDTARGET);
         return;
     }
 }
void train_next (entity this)
Definition at line 83 of file train.qc.
References _sound, ATTEN_IDLE, CH_TRIGGER_SINGLE, entity(), find(), future_target, noise, NULL, objerror(), platmovetype_end, platmovetype_end_default, platmovetype_start, platmovetype_start_default, spawnflags, SUB_CalcMove(), SUB_CalcMove_Bezier(), target, target_random, targetname, train_next_find(), train_wait(), TSPEED_LINEAR, vector(), view_ofs, VOL_BASE, and wait.
Referenced by dynlight_find_path(), and train_wait().
 {
     entity targ = NULL, cp = NULL;
     vector cp_org = '0 0 0';
     targ = this.future_target;
     this.target = targ.target;
     this.target_random = targ.target_random;
     this.future_target = train_next_find(targ);
     if (this.spawnflags & 1)
     {
         if(targ.curvetarget)
         {
             cp = find(NULL, targetname, targ.curvetarget); // get its second target (the control point)
             cp_org = cp.origin - this.view_ofs; // no control point found, assume a straight line to the destination
         }
     }
     if (this.target == "")
         objerror(this, "train_next: no next target");
     this.wait = targ.wait;
     if (!this.wait)
         this.wait = 0.1;
     if(targ.platmovetype)
     {
         // this path_corner contains a movetype overrider, apply it
         this.platmovetype_start = targ.platmovetype_start;
         this.platmovetype_end = targ.platmovetype_end;
     }
     else
     {
         // this path_corner doesn't contain a movetype overrider, use the train's defaults
         this.platmovetype_start = this.platmovetype_start_default;
         this.platmovetype_end = this.platmovetype_end_default;
     }
     if (targ.speed)
     {
         if (cp)
             SUB_CalcMove_Bezier(this, cp_org, targ.origin - this.view_ofs, TSPEED_LINEAR, targ.speed, train_wait);
         else
             SUB_CalcMove(this, targ.origin - this.view_ofs, TSPEED_LINEAR, targ.speed, train_wait);
     }
     else
     {
         if (cp)
             SUB_CalcMove_Bezier(this, cp_org, targ.origin - this.view_ofs, TSPEED_LINEAR, this.speed, train_wait);
         else
             SUB_CalcMove(this, targ.origin - this.view_ofs, TSPEED_LINEAR, this.speed, train_wait);
     }
     if(this.noise != "")
         _sound(this, CH_TRIGGER_SINGLE, this.noise, VOL_BASE, ATTEN_IDLE);
 }
Variable Documentation
vector color
Definition at line 13 of file g_lights.qc.
Referenced by spawnfunc().
const float DFOLLOW = 4
Definition at line 10 of file g_lights.qc.
Referenced by spawnfunc().
const float DNOSHADOW = 2
Definition at line 9 of file g_lights.qc.
string dtagname
Definition at line 14 of file g_lights.qc.
Referenced by dynlight_find_target(), and spawnfunc().
float lefty
Definition at line 12 of file g_lights.qc.
Referenced by dynlight_use(), and spawnfunc().
float light_lev
Definition at line 11 of file g_lights.qc.
Referenced by dynlight_use(), and spawnfunc().
const float LOOP = 1
Definition at line 5 of file g_lights.qc.
float speed
Definition at line 7 of file g_lights.qc.
Referenced by spawnfunc().