Xonotic: common/notifications/all.qc File Reference
all.qc File Reference
#include "all.qh"
Macros
#define AnnouncerFilename(snd) sprintf("announcer/%s/%s.wav", AnnouncerOption(), snd)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE(prog, selected, result) ARG_CASE_##prog(selected, result)
#define ARG_CASE_ARG_CS(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_CS(selected, result)
#define ARG_CASE_ARG_CS_SV(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV(selected, result)
#define ARG_CASE_ARG_CS_SV(selected, result)
#define ARG_CASE_ARG_CS_SV(selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_DC(selected, result)
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_HA(selected, result)
#define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE_ARG_DC(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_DC(selected, result)
#define ARG_CASE_ARG_SV(selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_SV(selected, result)
#define ARG_CASE_ARG_SV(selected, result)
#define ARG_CASE_ARG_SV(selected, result) case selected: arg_slot[sel_num++] = result; break;
#define NOTIF_WRITE(str) write_String_To_File(fh, str, alsoprint)
#define NOTIF_WRITE_ENTITY(e, description)
#define NOTIF_WRITE_ENTITY_CHOICE(e, descriptiona, descriptionb)
#define NOTIF_WRITE_HARDCODED(cvar, default, description) NOTIF_WRITE("seta notification_" cvar " \"" default "\" \"" description "\"\n")
#define SET_NOTIF_STRING(string, stringname)
#define VARITEM(stringc, floatc, args)
Functions
void Create_Notification_Entity (entity notif, float var_default, float var_cvar, MSG typeId, string namestring, int teamnum)
void Create_Notification_Entity_Annce (entity notif, float var_cvar, string namestring, float channel, string snd, float vol, float position)
void Create_Notification_Entity_Choice (entity notif, float var_cvar, string namestring, float challow_def, float challow_var, MSG chtype, Notification optiona, Notification optionb)
void Create_Notification_Entity_InfoCenter (entity notif, float var_cvar, string namestring, int strnum, int flnum, string args, string hudargs, string icon, CPID cpid, string durcnt, string normal, string gentle)
void Create_Notification_Entity_Multi (entity notif, float var_cvar, string namestring, Notification anncename, Notification infoname, Notification centername)
void Destroy_All_Notifications ()
void Destroy_Notification_Entity (entity notif)
void Dump_Notifications (int fh, bool alsoprint)
used to output notifications.cfg file
void Local_Notification (MSG net_type, Notification net_name,...count)
string Local_Notification_sprintf (string input, string args, string s1, string s2, string s3, string s4, int f1, float f2, float f3, float f4)
void Local_Notification_WOVA (MSG net_type, Notification net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
glue for networking, forwards to Local_Notification
string Process_Notif_Args (float arg_type, string args, string notiftype, string notifname)
string Process_Notif_Line (MSG typeId, bool chat, string input, string notiftype, string notifname, string stringtype)
Macro Definition Documentation
#define AnnouncerFilename (snd) sprintf("announcer/%s/%s.wav", AnnouncerOption(), snd)
Definition at line 441 of file all.qc.
Referenced by Create_Notification_Entity_Annce().
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected,result)
#define ARG_CASE (prog, selected, result) ARG_CASE_##prog(selected, result)
#define ARG_CASE_ARG_CS (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result)
#define ARG_CASE_ARG_CS_SV (selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_DC (selected, result)
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_DC (selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_CS_SV_HA (selected, result)
#define ARG_CASE_ARG_CS_SV_HA (selected, result) case selected: arg_slot[sel_num++] = result; break;
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_DC (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_DC (selected, result)
#define ARG_CASE_ARG_SV (selected, result) case selected: ++sel_num; break;
#define ARG_CASE_ARG_SV (selected, result)
#define ARG_CASE_ARG_SV (selected, result)
#define ARG_CASE_ARG_SV (selected, result) case selected: arg_slot[sel_num++] = result; break;
#define NOTIF_WRITE (str) write_String_To_File(fh, str, alsoprint)
Referenced by Dump_Notifications().
#define NOTIF_WRITE_ENTITY (e, description)
Value:
NOTIF_WRITE(sprintf(\
            "seta notification_%s \"%d\" \"%s\"\n", \
            Get_Notif_CvarName(e), e.nent_default, description \
        ))
#define NOTIF_WRITE_ENTITY_CHOICE (e, descriptiona, descriptionb)
Value:
NOTIF_WRITE(sprintf(\
            "seta notification_%s \"%d\" \"%s\"\n" \
            "seta notification_%s_ALLOWED \"%d\" \"%s\"\n", \
            Get_Notif_CvarName(e), e.nent_default, descriptiona, \
            Get_Notif_CvarName(e), e.nent_challow_def, descriptionb \
        ))
#define NOTIF_WRITE_HARDCODED (cvar, default, description) NOTIF_WRITE("seta notification_" cvar " \"" default "\" \"" description "\"\n")
#define SET_NOTIF_STRING (string, stringname)
Value:
MACRO_BEGIN \
                    notif.nent_string = strzone(CCR( \
                        Process_Notif_Line( \
                            typeId, \
                            (var_cvar > 1), \
                            string, \
                            typestring, \
                            namestring, \
                            stringname \
                        )) \
                    ); \
                MACRO_END
Referenced by Create_Notification_Entity_InfoCenter().
#define VARITEM (stringc, floatc, args)
Value:
if ((stringcount == stringc) && (floatcount == floatc)) \
        { Local_Notification(net_type, net_name, args); return; }
Function Documentation
void Create_Notification_Entity (entity notif, float var_default, float var_cvar, MSG typeId, string namestring, int teamnum)
Definition at line 393 of file all.qc.
References LOG_INFOF, notif_error, notif_global_error, and strzone().
 {
     // =====================
     //  Global Entity Setup
     // =====================
     notif.nent_default = var_default;
     notif.nent_enabled = (var_cvar >= 1);
     notif.nent_type = typeId;
     notif.nent_name = strzone(namestring);
     notif.nent_teamnum = teamnum;
     // Other pre-notif-setup requisites
     notif_error = false;
     switch (typeId)
     {
         case MSG_ANNCE:
         case MSG_INFO:
         case MSG_CENTER:
         case MSG_MULTI:
         case MSG_CHOICE:
             break;
         default:
             LOG_INFOF(
                 (
                     "^1NOTIFICATION WITH IMPROPER TYPE: "
                     "^7net_type = %d, net_name = %s."
                 ),
                 typeId,
                 namestring
             );
             notif_error = true;
             break;
     }
     // now check to see if any errors happened
     if (notif_error)
     {
         notif.nent_enabled = false; // disable the notification so it can't cause trouble
         notif_global_error = true; // throw the red flag that an error happened on init
     }
 }
void Create_Notification_Entity_Annce (entity notif, float var_cvar, string namestring, float channel, string snd, float vol, float position)
Definition at line 443 of file all.qc.
References AnnouncerFilename, Get_Notif_TypeName(), LOG_INFOF, notif_error, precache_sound(), and strzone().
         {
             // Set MSG_ANNCE information and handle precaching
             #ifdef CSQC
             MSG typeId = MSG_ANNCE;
             if (!(GENTLE && (var_cvar == 1)))
             {
                 if(snd != "")
                 {
                     if(notif.nent_enabled)
                     {
                         precache_sound(AnnouncerFilename(snd));
                         notif.nent_channel = channel;
                         notif.nent_snd = strzone(snd);
                         notif.nent_vol = vol;
                         notif.nent_position = position;
                     }
                 }
                 else
                 {
                     string typestring = Get_Notif_TypeName(typeId);
                     LOG_INFOF(
                         (
                             "^1NOTIFICATION WITH NO SOUND: "
                             "^7net_type = %s, net_name = %s."
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
             }
             else { notif.nent_enabled = false; }
             #else
             notif.nent_enabled = false;
             #endif
         }
void Create_Notification_Entity_Choice (entity notif, float var_cvar, string namestring, float challow_def, float challow_var, MSG chtype, Notification optiona, Notification optionb)
Definition at line 699 of file all.qc.
References Get_Notif_TypeName(), LOG_INFOF, max(), and notif_error.
         {
             MSG typeId = MSG_CHOICE;
             if (chtype == MSG_Null || !optiona || !optionb)
             {
                 string typestring = Get_Notif_TypeName(typeId);
                 LOG_INFOF(
                     (
                         "^1NOTIFICATION IS MISSING CHOICE PARAMS: "
                         "^7net_type = %s, net_name = %s."
                     ),
                     typestring,
                     namestring
                 );
                 notif_error = true;
             }
             else
             {
                 notif.nent_optiona = optiona;
                 notif.nent_optionb = optionb;
                 notif.nent_challow_def = challow_def; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                 notif.nent_challow_var = challow_var; // 0: never allowed, 1: allowed in warmup, 2: always allowed
                 notif.nent_stringcount = max(notif.nent_optiona.nent_stringcount, notif.nent_optionb.nent_stringcount);
                 notif.nent_floatcount = max(notif.nent_optiona.nent_floatcount, notif.nent_optionb.nent_floatcount);
                 /*#ifdef NOTIFICATIONS_DEBUG
                 Debug_Notification(sprintf(
                     "Create_Notification_Entity(...): MSG_CHOICE: %s\n%s\n%s\n",
                     notif.nent_name,
                     sprintf(
                         "^ optiona: %s %s : %d %d",
                         Get_Notif_TypeName(notif.nent_optiona.nent_type),
                         notif.nent_optiona.nent_name,
                         notif.nent_optiona.nent_stringcount,
                         notif.nent_optiona.nent_floatcount
                     ),
                     sprintf(
                         "^ optionb: %s %s : %d %d",
                         Get_Notif_TypeName(notif.nent_optionb.nent_type),
                         notif.nent_optionb.nent_name,
                         notif.nent_optionb.nent_stringcount,
                         notif.nent_optionb.nent_floatcount
                     )
                 ));
                 #endif*/
             }
         }
void Create_Notification_Entity_InfoCenter (entity notif, float var_cvar, string namestring, int strnum, int flnum, string args, string hudargs, string icon, CPID cpid, string durcnt, string normal, string gentle)
Definition at line 489 of file all.qc.
References CPID_Null, Get_Notif_TypeName(), LOG_INFOF, LOG_WARNF, notif_error, Process_Notif_Args(), server_is_dedicated, SET_NOTIF_STRING, and strzone().
         {
             MSG typeId = notif.nent_type;
             // Set MSG_INFO and MSG_CENTER string/float counts
             notif.nent_stringcount = strnum;
             notif.nent_floatcount = flnum;
             // Only initialize arguments if we're either a client or on a dedicated server
             #ifdef SVQC
             float should_process_args = server_is_dedicated;
             #else
             float should_process_args = true;
             #endif
             string typestring = Get_Notif_TypeName(typeId);
             if(should_process_args)
             {
                 // ========================
                 //  Process Main Arguments
                 // ========================
                 if(strnum + flnum)
                 {
                     if(args != "")
                     {
                         notif.nent_args = strzone(
                             Process_Notif_Args(1, args, typestring, namestring));
                     }
                     else if((hudargs == "") && (durcnt ==""))
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION HAS ARG COUNTS BUT NO ARGS OR HUDARGS OR DURCNT: "
                                 "^7net_type = %s, net_name = %s, strnum = %d, flnum = %d"
                             ),
                             typestring,
                             namestring,
                             strnum,
                             flnum
                         );
                         notif_error = true;
                     }
                 }
                 else if(args != "")
                 {
                     notif.nent_args = strzone(
                         Process_Notif_Args(1, args, typestring, namestring));
                 }
                 // =======================================
                 //  Process HUD and Centerprint Arguments
                 //    Only processed on CSQC, as these
                 //    args are only for HUD features.
                 // =======================================
                 #ifdef CSQC
                 if(hudargs != "")
                 {
                     notif.nent_hudargs = strzone(
                         Process_Notif_Args(2, hudargs, typestring, namestring));
                     if(icon != "") { notif.nent_icon = strzone(icon); }
                     else
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION HAS HUDARGS BUT NO ICON: "
                                 "^7net_type = %s, net_name = %s."
                             ),
                             typestring,
                             namestring
                         );
                         notif_error = true;
                     }
                 }
                 else if(icon != "")
                 {
                     LOG_WARNF(
                         (
                             "^1NOTIFICATION HAS ICON BUT NO HUDARGS: "
                             "^7net_type = %s, net_name = %s.\n"
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
                 if (durcnt != "")
                 {
                     notif.nent_durcnt = strzone(Process_Notif_Args(3, durcnt, typestring, namestring));
                     if (cpid == CPID_Null && durcnt != "0 0")
                     {
                         LOG_WARNF(
                             (
                                 "Notification has durcnt but no cpid: "
                                 "net_type = %s, net_name = %s."
                             ),
                             typestring,
                             namestring
                         );
                         notif_error = true;
                     }
                 }
                 notif.nent_cpid = cpid;
                 #endif
                 // ======================
                 //  Process Notif String
                 // ======================
                 #define SET_NOTIF_STRING(string,stringname) MACRO_BEGIN \
                     notif.nent_string = strzone(CCR( \
                         Process_Notif_Line( \
                             typeId, \
                             (var_cvar > 1), \
                             string, \
                             typestring, \
                             namestring, \
                             stringname \
                         )) \
                     ); \
                 MACRO_END
                 if(GENTLE)
                 {
                     if(gentle != "") { SET_NOTIF_STRING(gentle, "GENTLE"); }
                     else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                 }
                 else if(normal != "") { SET_NOTIF_STRING(normal, "NORMAL"); }
                 #undef SET_NOTIF_STRING
                 // Check to make sure a string was chosen
                 if(notif.nent_string == "")
                 {
                     LOG_INFOF(
                         (
                             "^1EMPTY NOTIFICATION: "
                             "^7net_type = %s, net_name = %s."
                         ),
                         typestring,
                         namestring
                     );
                     notif_error = true;
                 }
             }
         }
void Create_Notification_Entity_Multi (entity notif, float var_cvar, string namestring, Notification anncename, Notification infoname, Notification centername)
Definition at line 648 of file all.qc.
References Get_Notif_TypeName(), LOG_INFOF, max(), and notif_error.
         {
             MSG typeId = MSG_MULTI;
             // Set MSG_MULTI string/float counts
             if (!anncename && !infoname && !centername)
             {
                 string typestring = Get_Notif_TypeName(typeId);
                 LOG_INFOF(
                     (
                         "^1NOTIFICATION WITH NO SUBCALLS: "
                         "^7net_type = %s, net_name = %s."
                     ),
                     typestring,
                     namestring
                 );
                 notif_error = true;
             }
             else
             {
                 // announcements don't actually need any arguments, so lets not even count them.
                 if (anncename) { notif.nent_msgannce = anncename; }
                 float infoname_stringcount = 0, infoname_floatcount = 0;
                 float centername_stringcount = 0, centername_floatcount = 0;
                 if (infoname)
                 {
                     notif.nent_msginfo = infoname;
                     infoname_stringcount = notif.nent_msginfo.nent_stringcount;
                     infoname_floatcount = notif.nent_msginfo.nent_floatcount;
                 }
                 if (centername)
                 {
                     notif.nent_msgcenter = centername;
                     centername_stringcount = notif.nent_msgcenter.nent_stringcount;
                     centername_floatcount = notif.nent_msgcenter.nent_floatcount;
                 }
                 // set the requirements of THIS notification to the totals of its subcalls
                 notif.nent_stringcount = max(infoname_stringcount, centername_stringcount);
                 notif.nent_floatcount = max(infoname_floatcount, centername_floatcount);
             }
         }
void Destroy_All_Notifications ()
Definition at line 156 of file all.qc.
References CPID_Null, Destroy_Notification_Entity(), FOREACH, NULL, and reset_centerprint_messages().
Referenced by GenericCommand_restartnotifs().
 {
     // kill all networked notifications and centerprints
     #ifdef SVQC
     Kill_Notification(NOTIF_ALL, NULL, MSG_Null, CPID_Null);
     #else
     reset_centerprint_messages();
     #endif
     // kill all real notification entities
     FOREACH(Notifications, true, { Destroy_Notification_Entity(it); });
 }
void Destroy_Notification_Entity (entity notif)
Definition at line 144 of file all.qc.
References strunzone().
Referenced by Destroy_All_Notifications().
 {
     if (notif.nent_name != "") strunzone(notif.nent_name);
     if (notif.nent_snd != "") strunzone(notif.nent_snd);
     if (notif.nent_args != "") strunzone(notif.nent_args);
     if (notif.nent_hudargs != "") strunzone(notif.nent_hudargs);
     if (notif.nent_icon != "") strunzone(notif.nent_icon);
     if (notif.nent_durcnt != "") strunzone(notif.nent_durcnt);
     if (notif.nent_string != "") strunzone(notif.nent_string);
     delete(notif);
 }
void Dump_Notifications (int fh, bool alsoprint)
used to output notifications.cfg file
Definition at line 778 of file all.qc.
References FOREACH, and NOTIF_WRITE.
Referenced by GENERIC_COMMAND().
 {
     #define NOTIF_WRITE(str) write_String_To_File(fh, str, alsoprint)
     #define NOTIF_WRITE_ENTITY(e, description) \
         NOTIF_WRITE(sprintf( \
             "seta notification_%s \"%d\" \"%s\"\n", \
             Get_Notif_CvarName(e), e.nent_default, description \
         ))
     #define NOTIF_WRITE_ENTITY_CHOICE(e, descriptiona, descriptionb) \
         NOTIF_WRITE(sprintf( \
             "seta notification_%s \"%d\" \"%s\"\n" \
             "seta notification_%s_ALLOWED \"%d\" \"%s\"\n", \
             Get_Notif_CvarName(e), e.nent_default, descriptiona, \
             Get_Notif_CvarName(e), e.nent_challow_def, descriptionb \
         ))
     #define NOTIF_WRITE_HARDCODED(cvar, default, description) \
         NOTIF_WRITE("seta notification_" cvar " \"" default "\" \"" description "\"\n")
     // Note: This warning only applies to the notifications.cfg file that is output...
     // You ARE supposed to manually edit this function to add i.e. hard coded
     // notification variables for mutators or game modes or such and then
     // regenerate the notifications.cfg file from the new code.
     NOTIF_WRITE(
         "// ********************************************** //\n"
         "// ** WARNING - DO NOT MANUALLY EDIT THIS FILE ** //\n"
         "// **                                          ** //\n"
         "// **  This file is automatically generated    ** //\n"
         "// **  by code with the command 'dumpnotifs'.  ** //\n"
         "// **                                          ** //\n"
         "// **  If you add a new notification, please   ** //\n"
         "// **  regenerate this file with that command  ** //\n"
         "// **  making sure that the output matches     ** //\n"
         "// **  with the lists and defaults in code.    ** //\n"
         "// **                                          ** //\n"
         "// ********************************************** //\n");
     // These notifications will also append their string as a comment...
     // This is not necessary, and does not matter if they vary between config versions,
     // it is just a semi-helpful tool for those who want to manually change their user settings.
     int NOTIF_ANNCE_COUNT = 0;
     int NOTIF_INFO_COUNT = 0;
     int NOTIF_CENTER_COUNT = 0;
     int NOTIF_MULTI_COUNT = 0;
     int NOTIF_CHOICE_COUNT = 0;
     FOREACH(Notifications, true, {
         switch (it.nent_type)
         {
             case MSG_ANNCE: ++NOTIF_ANNCE_COUNT; break;
             case MSG_INFO: ++NOTIF_INFO_COUNT; break;
             case MSG_CENTER: ++NOTIF_CENTER_COUNT; break;
             case MSG_MULTI: ++NOTIF_MULTI_COUNT; break;
             case MSG_CHOICE: ++NOTIF_CHOICE_COUNT; break;
         }
     });
     NOTIF_WRITE(sprintf("\n// MSG_ANNCE notifications (count = %d):\n", NOTIF_ANNCE_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_ANNCE && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = disabled, 1 = enabled if gentle mode is off, 2 = always enabled"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_INFO notifications (count = %d):\n", NOTIF_INFO_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_INFO && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = off, 1 = print to console, "
             "2 = print to console and chatbox (if notification_allow_chatboxprint is enabled)"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_CENTER notifications (count = %d):\n", NOTIF_CENTER_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_CENTER && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "0 = off, 1 = centerprint"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_MULTI notifications (count = %d):\n", NOTIF_MULTI_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_MULTI && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY(it,
             "Enable this multiple notification"
         );
     });
     NOTIF_WRITE(sprintf("\n// MSG_CHOICE notifications (count = %d):\n", NOTIF_CHOICE_COUNT));
     FOREACH(Notifications, it.nent_type == MSG_CHOICE && (!it.nent_teamnum || it.nent_teamnum == NUM_TEAM_1), {
         NOTIF_WRITE_ENTITY_CHOICE(it,
             "Choice for this notification 0 = off, 1 = default message, 2 = verbose message",
             "Allow choice for this notification 0 = off, 1 = only in warmup mode, 2 = always"
         );
     });
     // edit these to match whichever cvars are used for specific notification options
     NOTIF_WRITE("\n// HARD CODED notification variables:\n");
     NOTIF_WRITE_HARDCODED(
         "allow_chatboxprint", "1",
         "Allow INFO notifications to be printed to chat box "
         "0 = do not allow, "
         "1 = allow only if allowed by individual notification_INFO* cvars, "
         "2 = force all INFO notifications to be printed to the chatbox"
     );
     NOTIF_WRITE_HARDCODED(
         "debug", "0",
         "Print extra debug information on all notification function calls "
         "(Requires -DNOTIFICATIONS_DEBUG flag to be enabled on QCSRC compilation)... "
         "0 = disabled, 1 = dprint, 2 = print"
     );
     NOTIF_WRITE_HARDCODED(
         "errors_are_fatal", "1",
         "If a notification fails upon initialization, cause a Host_Error to stop the program"
     );
     NOTIF_WRITE_HARDCODED(
         "item_centerprinttime", "1.5",
         "How long to show item information centerprint messages (like 'You got the Electro' or such)"
     );
     NOTIF_WRITE_HARDCODED(
         "lifetime_mapload", "10",
         "Amount of time that notification entities last immediately at mapload (in seconds) "
         "to help prevent notifications from being lost on early init (like gamestart countdown)"
     );
     NOTIF_WRITE_HARDCODED(
         "lifetime_runtime", "0.5",
         "Amount of time that notification entities last on the server during runtime (In seconds)"
     );
     NOTIF_WRITE_HARDCODED(
         "server_allows_location", "1",
         "Server side cvar for allowing death messages to show location information too"
     );
     NOTIF_WRITE_HARDCODED(
         "show_location", "0",
         "Append location information to MSG_INFO death/kill messages"
     );
     NOTIF_WRITE_HARDCODED(
         "show_location_string", "",
         "Replacement string piped into sprintf, "
         "so you can do different messages like this: ' at the %s' or ' (near %s)'"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees", "1",
         "Print information about sprees in death/kill messages"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_center", "1",
         "Show spree information in MSG_CENTER messages... "
         "0 = off, 1 = target (but only for first victim) and attacker"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_center_specialonly", "1",
         "Don't show spree information in MSG_CENTER messages if it isn't an achievement"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info", "3",
         "Show spree information in MSG_INFO messages... "
         "0 = off, 1 = target only, 2 = attacker only, 3 = target and attacker"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info_newline", "1",
         "Show attacker spree information for MSG_INFO messages on a separate line than the death notification itself"
     );
     NOTIF_WRITE_HARDCODED(
         "show_sprees_info_specialonly", "1",
         "Don't show attacker spree information in MSG_INFO messages if it isn't an achievement"
     );
     NOTIF_WRITE(sprintf(
         (
             "\n// Notification counts (total = %d): "
             "MSG_ANNCE = %d, MSG_INFO = %d, MSG_CENTER = %d, MSG_MULTI = %d, MSG_CHOICE = %d\n"
         ),
         (
             NOTIF_ANNCE_COUNT +
             NOTIF_INFO_COUNT +
             NOTIF_CENTER_COUNT +
             NOTIF_MULTI_COUNT +
             NOTIF_CHOICE_COUNT
         ),
         NOTIF_ANNCE_COUNT,
         NOTIF_INFO_COUNT,
         NOTIF_CENTER_COUNT,
         NOTIF_MULTI_COUNT,
         NOTIF_CHOICE_COUNT
     ));
     #undef NOTIF_WRITE_HARDCODED
     #undef NOTIF_WRITE_ENTITY
     #undef NOTIF_WRITE
 }
void Local_Notification (MSG net_type, Notification net_name, count)
Definition at line 1182 of file all.qc.
References backtrace, count, cvar(), entity(), float(), Get_Notif_CvarName(), Get_Notif_TypeName(), Local_Notification_sprintf(), Local_Notification_WOVA(), LOG_WARNF, MakeConsoleSafe(), print(), strzone(), substring(), and warmup_stage.
Referenced by Announcer_Countdown(), Announcer_Gamestart(), Local_Notification_WOVA(), and NET_HANDLE().
 {
     // retreive entity of this notification
     entity notif = net_name;
     if (!notif)
     {
         #ifdef NOTIFICATIONS_DEBUG
         Debug_Notification(sprintf(
             "Local_Notification(%s, NULL, ...);\n",
             Get_Notif_TypeName(net_type)
         ));
         #endif
         LOG_WARNF("Incorrect usage of Local_Notification: %s", "Null notification");
         return;
     }
     // check if the notification is enabled
     if (!notif.nent_enabled)
     {
         #ifdef NOTIFICATIONS_DEBUG
         Debug_Notification(sprintf(
             "Local_Notification(%s, %s, ...): Entity was disabled...\n",
             Get_Notif_TypeName(net_type),
             notif.nent_name
         ));
         #endif
         return;
     }
     string s1 = CCR((notif.nent_stringcount > 0) ? ...(0, string) : "");
     string s2 = CCR((notif.nent_stringcount > 1) ? ...(1, string) : "");
     string s3 = CCR((notif.nent_stringcount > 2) ? ...(2, string) : "");
     string s4 = CCR((notif.nent_stringcount > 3) ? ...(3, string) : "");
     float f1 =  ((notif.nent_floatcount  > 0) ? ...((notif.nent_stringcount + 0), float) : 0);
     float f2 =  ((notif.nent_floatcount  > 1) ? ...((notif.nent_stringcount + 1), float) : 0);
     float f3 =  ((notif.nent_floatcount  > 2) ? ...((notif.nent_stringcount + 2), float) : 0);
     float f4 =  ((notif.nent_floatcount  > 3) ? ...((notif.nent_stringcount + 3), float) : 0);
     #ifdef NOTIFICATIONS_DEBUG
     Debug_Notification(sprintf(
         "Local_Notification(%s, %s, %s, %s);\n",
         Get_Notif_TypeName(net_type),
         notif.nent_name,
         MakeConsoleSafe(sprintf("'%s^7', '%s^7', '%s^7', '%s^7'", s1, s2, s3, s4)),
         sprintf("%d, %d, %d, %d", f1, f2, f3, f4)
     ));
     #endif
     if ((notif.nent_stringcount + notif.nent_floatcount) != count)
     {
         backtrace(sprintf(
             (
                 "Arguments mismatch for Local_Notification(%s, %s, ...)! "
                 "stringcount(%d) + floatcount(%d) != count(%d)\n"
                 "Check the definition and function call for accuracy...?\n"
             ),
             Get_Notif_TypeName(net_type),
             notif.nent_name,
             notif.nent_stringcount,
             notif.nent_floatcount,
             count
         ));
         return;
     }
     switch (net_type)
     {
         case MSG_ANNCE:
         {
             #ifdef CSQC
             Local_Notification_sound(notif.nent_channel, notif.nent_snd, notif.nent_vol, notif.nent_position);
             #else
             backtrace("MSG_ANNCE on server?... Please notify Samual immediately!\n");
             #endif
             break;
         }
         case MSG_INFO:
         {
             print(
                 Local_Notification_sprintf(
                     notif.nent_string,
                     notif.nent_args,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4)
             );
             #ifdef CSQC
             if (notif.nent_icon != "")
             {
                 if (notif.nent_iconargs != "")
                 {
                     string s = Local_Notification_sprintf(
                         notif.nent_icon,notif.nent_iconargs,
                         s1, s2, s3, s4, f1, f2, f3, f4);
                     // remove the trailing newline
                     notif.nent_icon = strzone(substring(s, 0, -1));
                 }
                 Local_Notification_HUD_Notify_Push(
                     notif.nent_icon,
                     notif.nent_hudargs,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #endif
             break;
         }
         #ifdef CSQC
         case MSG_CENTER:
         {
             Local_Notification_centerprint_generic(
                 Local_Notification_sprintf(
                     notif.nent_string,
                     notif.nent_args,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4),
                 notif.nent_durcnt,
                 notif.nent_cpid,
                 f1, f2);
             break;
         }
         #endif
         case MSG_MULTI:
         {
             if (notif.nent_msginfo && notif.nent_msginfo.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_INFO,
                     notif.nent_msginfo,
                     notif.nent_msginfo.nent_stringcount,
                     notif.nent_msginfo.nent_floatcount,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #ifdef CSQC
             if (notif.nent_msgannce && notif.nent_msgannce.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_ANNCE,
                     notif.nent_msgannce,
                     0, 0,
                     "", "", "", "",
                     0, 0, 0, 0);
             }
             if (notif.nent_msgcenter && notif.nent_msgcenter.nent_enabled)
             {
                 Local_Notification_WOVA(
                     MSG_CENTER,
                     notif.nent_msgcenter,
                     notif.nent_msgcenter.nent_stringcount,
                     notif.nent_msgcenter.nent_floatcount,
                     s1, s2, s3, s4,
                     f1, f2, f3, f4);
             }
             #endif
             break;
         }
         case MSG_CHOICE:
         {
             entity found_choice = notif.nent_optiona;
             if (notif.nent_challow_var && (warmup_stage || (notif.nent_challow_var == 2))) {
                 switch (cvar(sprintf("notification_%s", Get_Notif_CvarName(notif))))
                 {
                     case 1: break;
                     case 2: found_choice = notif.nent_optionb; break;
                     default: return; // not enabled anyway
                 }
             }
             Local_Notification_WOVA(
                 found_choice.nent_type,
                 found_choice,
                 found_choice.nent_stringcount,
                 found_choice.nent_floatcount,
                 s1, s2, s3, s4,
                 f1, f2, f3, f4);
         }
     }
 }
string Local_Notification_sprintf (string input, string args, string s1, string s2, string s3, string s4, int f1, float f2, float f3, float f4)
Definition at line 990 of file all.qc.
References arg_slot, car(), cdr(), MakeConsoleSafe(), NOTIF_ARGUMENT_LIST, NOTIF_HIT_MAX, NOTIF_HIT_UNKNOWN, NOTIF_MAX_ARGS, and strcat().
Referenced by Local_Notification().
 {
     #ifdef NOTIFICATIONS_DEBUG
     Debug_Notification(sprintf(
         "Local_Notification_sprintf('%s^7', '%s', %s, %s);\n",
         MakeConsoleSafe(input),
         args,
         MakeConsoleSafe(sprintf("'%s^7', '%s^7', '%s^7', '%s^7'", s1, s2, s3, s4)),
         sprintf("%d, %d, %d, %d", f1, f2, f3, f4)
     ));
     #endif
     for (int sel_num = 0; sel_num < NOTIF_MAX_ARGS; ++sel_num) { arg_slot[sel_num] = ""; }
     for (int sel_num = 0; (args != ""); )
     {
         string selected = car(args); args = cdr(args);
         NOTIF_HIT_MAX(NOTIF_MAX_ARGS, "Local_Notification_sprintf");
         string tmp_s; // used by NOTIF_ARGUMENT_LIST
         switch (strtolower(selected))
         {
             #define ARG_CASE_ARG_CS_SV_HA(selected, result) case selected: arg_slot[sel_num++] = result; break;
             #define ARG_CASE_ARG_CS_SV_DC(selected, result) case selected: arg_slot[sel_num++] = result; break;
             #define ARG_CASE_ARG_CS_SV(selected, result)    case selected: arg_slot[sel_num++] = result; break;
 #ifdef CSQC
             #define ARG_CASE_ARG_CS(selected, result)       case selected: arg_slot[sel_num++] = result; break;
             #define ARG_CASE_ARG_SV(selected, result)
 #else
             #define ARG_CASE_ARG_CS(selected, result)
             #define ARG_CASE_ARG_SV(selected, result)       case selected: arg_slot[sel_num++] = result; break;
 #endif
             #define ARG_CASE_ARG_DC(selected, result)
             #define ARG_CASE(prog, selected, result)        ARG_CASE_##prog(selected, result)
             NOTIF_ARGUMENT_LIST
             #undef ARG_CASE
             #undef ARG_CASE_ARG_DC
             #undef ARG_CASE_ARG_SV
             #undef ARG_CASE_ARG_CS
             #undef ARG_CASE_ARG_CS_SV
             #undef ARG_CASE_ARG_CS_SV_DC
             #undef ARG_CASE_ARG_CS_SV_HA
             default: NOTIF_HIT_UNKNOWN(NOTIF_MAX_ARGS, "Local_Notification_sprintf")
         }
     }
     return sprintf(
         strcat(input, "\n"),
         arg_slot[0],
         arg_slot[1],
         arg_slot[2],
         arg_slot[3],
         arg_slot[4],
         arg_slot[5],
         arg_slot[6]
     );
 }
void Local_Notification_WOVA (MSG net_type, Notification net_name, float stringcount, float floatcount, string s1, string s2, string s3, string s4, float f1, float f2, float f3, float f4)
glue for networking, forwards to Local_Notification
Definition at line 1365 of file all.qc.
References EIGHT_VARS_TO_VARARGS_VARLIST, and Local_Notification().
Referenced by Local_Notification().
 {
     #define VARITEM(stringc, floatc, args) \
         if ((stringcount == stringc) && (floatcount == floatc)) \
         { Local_Notification(net_type, net_name, args); return; }
     EIGHT_VARS_TO_VARARGS_VARLIST
     #undef VARITEM
     Local_Notification(net_type, net_name); // some notifications don't have any arguments at all
 }
string Process_Notif_Args (float arg_type, string args, string notiftype, string notifname)
Definition at line 216 of file all.qc.
References car(), cdr(), ftos(), LOG_INFOF, NOTIF_ARGUMENT_LIST, notif_error, NOTIF_MAX_ARGS, NOTIF_MAX_DURCNT, NOTIF_MAX_HUDARGS, and stof().
Referenced by Create_Notification_Entity_InfoCenter().
 {
     string selected, remaining = args;
     float sel_num = 0;
     for (;(remaining != "");)
     {
         selected = car(remaining); remaining = cdr(remaining);
         switch(arg_type)
         {
             case 1: // normal args
             {
                 if(sel_num == NOTIF_MAX_ARGS)
                 {
                     LOG_INFOF(
                         (
                             "^1NOTIFICATION HAS TOO MANY ARGUMENTS: "
                             "^7net_type = %s, net_name = %s, max args = %d."
                         ),
                         notiftype,
                         notifname,
                         NOTIF_MAX_ARGS
                     );
                     notif_error = true;
                     break;
                 }
                 switch(strtolower(selected))
                 {
                     #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_CS_SV(selected,result)    case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_CS(selected,result)       case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_SV(selected,result)       case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_DC(selected,result)
                     #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                     NOTIF_ARGUMENT_LIST
                     #undef ARG_CASE
                     #undef ARG_CASE_ARG_DC
                     #undef ARG_CASE_ARG_SV
                     #undef ARG_CASE_ARG_CS
                     #undef ARG_CASE_ARG_CS_SV
                     #undef ARG_CASE_ARG_CS_SV_DC
                     #undef ARG_CASE_ARG_CS_SV_HA
                     default:
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: "
                                 "^7net_type = %s, net_name = %s, args arg = '%s'."
                             ),
                             notiftype,
                             notifname,
                             selected
                         );
                         notif_error = true;
                         break;
                     }
                 }
                 break;
             }
             case 2: // hudargs
             {
                 if(sel_num == NOTIF_MAX_HUDARGS)
                 {
                     LOG_INFOF(
                         (
                             "^1NOTIFICATION HAS TOO MANY ARGUMENTS: "
                             "^7net_type = %s, net_name = %s, max hudargs = %d."
                         ),
                         notiftype,
                         notifname,
                         NOTIF_MAX_HUDARGS
                     );
                     notif_error = true;
                     break;
                 }
                 switch(strtolower(selected))
                 {
                     #define ARG_CASE_ARG_CS_SV_HA(selected,result) case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_CS_SV_DC(selected,result)
                     #define ARG_CASE_ARG_CS_SV(selected,result)
                     #define ARG_CASE_ARG_CS(selected,result)
                     #define ARG_CASE_ARG_SV(selected,result)
                     #define ARG_CASE_ARG_DC(selected,result)
                     #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                     NOTIF_ARGUMENT_LIST
                     #undef ARG_CASE
                     #undef ARG_CASE_ARG_DC
                     #undef ARG_CASE_ARG_SV
                     #undef ARG_CASE_ARG_CS
                     #undef ARG_CASE_ARG_CS_SV
                     #undef ARG_CASE_ARG_CS_SV_DC
                     #undef ARG_CASE_ARG_CS_SV_HA
                     default:
                     {
                         LOG_INFOF(
                             (
                                 "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: "
                                 "^7net_type = %s, net_name = %s, hudargs arg = '%s'."
                             ),
                             notiftype,
                             notifname,
                             selected
                         );
                         notif_error = true;
                         break;
                     }
                 }
                 break;
             }
             case 3: // durcnt
             {
                 if(sel_num == NOTIF_MAX_DURCNT)
                 {
                     LOG_INFOF(
                         (
                             "^1NOTIFICATION HAS TOO MANY ARGUMENTS: "
                             "^7net_type = %s, net_name = %s, max durcnt = %d."
                         ),
                         notiftype,
                         notifname,
                         NOTIF_MAX_DURCNT
                     );
                     notif_error = true;
                     break;
                 }
                 switch(strtolower(selected))
                 {
                     #define ARG_CASE_ARG_CS_SV_HA(selected,result)
                     #define ARG_CASE_ARG_CS_SV_DC(selected,result) case selected: ++sel_num; break;
                     #define ARG_CASE_ARG_CS_SV(selected,result)
                     #define ARG_CASE_ARG_CS(selected,result)
                     #define ARG_CASE_ARG_SV(selected,result)
                     #define ARG_CASE_ARG_DC(selected,result)       case selected: ++sel_num; break;
                     #define ARG_CASE(prog,selected,result)         ARG_CASE_##prog(selected,result)
                     NOTIF_ARGUMENT_LIST
                     #undef ARG_CASE
                     #undef ARG_CASE_ARG_DC
                     #undef ARG_CASE_ARG_SV
                     #undef ARG_CASE_ARG_CS
                     #undef ARG_CASE_ARG_CS_SV
                     #undef ARG_CASE_ARG_CS_SV_DC
                     #undef ARG_CASE_ARG_CS_SV_HA
                     default:
                     {
                         if(ftos(stof(selected)) != "") { ++sel_num; }
                         else
{
                             LOG_INFOF(
                                 (
                                     "^1NOTIFICATION WITH UNKNOWN TOKEN IN ARGUMENT STRING: "
                                     "^7net_type = %s, net_name = %s, durcnt arg = '%s'."
                                 ),
                                 notiftype,
                                 notifname,
                                 selected
                             );
                             notif_error = true;
                         }
                         break;
                     }
                 }
                 break;
             }
         }
     }
     return args;
 }
string Process_Notif_Line (MSG typeId, bool chat, string input, string notiftype, string notifname, string stringtype)
Definition at line 169 of file all.qc.
References autocvar_notification_allow_chatboxprint, LOG_INFOF, notif_error, strcat(), strlen(), and substring().
 {
     #ifdef CSQC
     if(typeId == MSG_INFO)
     {
         if((chat && autocvar_notification_allow_chatboxprint)
             || (autocvar_notification_allow_chatboxprint == 2))
         {
             // pass 1: add ETX char at beginning of line
             input = strcat("\{3}", input);
             // pass 2: add ETX char at end of each new line (so that
             // messages with multiple lines are put through chatbox too)
             input = strreplace("\n", "\n\{3}", input);
             // pass 3: strip trailing ETX char
             if(substring(input, (strlen(input) - 1), 1) == "\{3}")
                 { input = substring(input, 0, (strlen(input) - 1)); }
         }
     }
     #endif
     // done to both MSG_INFO and MSG_CENTER
     if(substring(input, (strlen(input) - 1), 1) == "\n")
     {
         LOG_INFOF(
             (
                 "^1TRAILING NEW LINE AT END OF NOTIFICATION: "
                 "^7net_type = %s, net_name = %s, string = %s."
             ),
             notiftype,
             notifname,
             stringtype
         );
         notif_error = true;
         input = substring(input, 1, (strlen(input) - 1));
     }
     return input;
 }