Xonotic: common/gamemodes/gamemode/onslaught/sv_generator.qc File Reference
sv_generator.qc File Reference
#include "sv_generator.qh"
Functions
bool generator_send (entity this, entity to, int sf)
Function Documentation
bool generator_send (entity this, entity to, int sf)
Definition at line 3 of file sv_generator.qc.
References ceil(), count, GetResourceAmount(), GSF_SETUP, GSF_STATUS, max_health, origin, RESOURCE_HEALTH, team, and WriteByte().
Referenced by ons_DelayedGeneratorSetup(), and ons_GeneratorReset().
 {
     WriteHeader(MSG_ENTITY, ENT_CLIENT_GENERATOR);
     WriteByte(MSG_ENTITY, sf);
     if(sf & GSF_SETUP)
     {
         WriteVector(MSG_ENTITY, this.origin);
         WriteByte(MSG_ENTITY, GetResourceAmount(this, RESOURCE_HEALTH));
         WriteByte(MSG_ENTITY, this.max_health);
         WriteByte(MSG_ENTITY, this.count);
         WriteByte(MSG_ENTITY, this.team);
     }
     if(sf & GSF_STATUS)
     {
         WriteByte(MSG_ENTITY, this.team);
         if(GetResourceAmount(this, RESOURCE_HEALTH) <= 0)
             WriteByte(MSG_ENTITY, 0);
         else
             WriteByte(MSG_ENTITY, ceil((GetResourceAmount(this, RESOURCE_HEALTH) / this.max_health) * 255));
     }
     return true;
 }