Xonotic: common/minigames/minigame/snake.qc File Reference
snake.qc File Reference
Functions
void minigame_setup_snake (entity minigame, int pteam)
REGISTER_MINIGAME (snake,"Snake")
void snake_add_score (entity minigame, int pteam, int thescore)
bool snake_alone (entity minig)
void snake_check_winner (entity minigame)
void snake_eat_team (entity minigame, int pteam)
entity snake_find_cnt (entity minig, int steam, int tile)
entity snake_find_head (entity minig, int steam)
entity snake_find_piece (entity minig, string tile)
entity snake_get_player (entity minigame, int pteam)
void snake_head_think (entity this)
void snake_move (entity minigame, entity player, string dxs, string dys)
void snake_move_body (entity minigame, entity head, bool ate_mouse)
void snake_move_head (entity minigame, entity head)
void snake_new_mouse (entity minigame)
void snake_setup_pieces (entity minigame)
bool snake_valid_tile (string tile)
int snake_winning_team (entity minigame)
Variables
float autocvar_sv_minigames_snake_delay_initial = 0.7
float autocvar_sv_minigames_snake_delay_min = 0.1
float autocvar_sv_minigames_snake_delay_multiplier = 50
int autocvar_sv_minigames_snake_lives = 3
bool autocvar_sv_minigames_snake_wrap = false
float snake_delay
vector snake_dir
entity snake_last
const int SNAKE_LET_CNT = 15
int snake_lives [SNAKE_TEAMS+1]
int snake_lost_teams
entity snake_next
const int SNAKE_NUM_CNT = 15
entity snake_prev
int snake_score
const int SNAKE_SF_PLAYERSCORE = MINIG_SF_CUSTOM
bool snake_tail
const int SNAKE_TEAMS = 6
const int SNAKE_TILE_SIZE = 15
const float SNAKE_TURN_LOSS = 0x0400
const float SNAKE_TURN_MOVE = 0x0100
const int SNAKE_TURN_TEAM = 0x000f
const float SNAKE_TURN_TYPE = 0x0f00
const float SNAKE_TURN_WIN = 0x0200
Function Documentation
void minigame_setup_snake (entity minigame, int pteam)
Definition at line 168 of file snake.qc.
References autocvar_sv_minigames_snake_delay_initial, entity(), MINIG_SF_ALL, minigame_server_sendflags(), minigame_tile_buildname(), msle_spawn(), NULL, RandomSelection_Add(), RandomSelection_chosen_string, RandomSelection_Init(), setthink, snake_find_piece(), snake_head_think(), SNAKE_LET_CNT, SNAKE_NUM_CNT, strzone(), and time.
Referenced by snake_eat_team().
 {
     RandomSelection_Init();
     int i, j;
     for(i = 1; i < SNAKE_LET_CNT - 1; ++i)
     for(j = 1; j < SNAKE_NUM_CNT - 1; ++j)
     {
         string pos = minigame_tile_buildname(i, j);
         if(!snake_find_piece(minigame, pos))
             RandomSelection_Add(NULL, 0, pos, 1, 1);
     }
     entity piece = msle_spawn(minigame,"minigame_board_piece");
     piece.team = pteam;
     piece.netname = strzone(RandomSelection_chosen_string);
     piece.cnt = 1;
     piece.snake_next = NULL;
     piece.snake_prev = NULL;
     piece.snake_last = piece;
     setthink(piece, snake_head_think);
     piece.snake_delay = autocvar_sv_minigames_snake_delay_initial;
     piece.nextthink = time + 0.1;
     minigame_server_sendflags(piece,MINIG_SF_ALL);
 }
REGISTER_MINIGAME (snake , "Snake")
void snake_add_score (entity minigame, int pteam, int thescore)
Definition at line 215 of file snake.qc.
References entity(), snake_get_player(), and SNAKE_SF_PLAYERSCORE.
Referenced by snake_move_body(), and snake_move_head().
 {
 #ifdef SVQC
     if(!minigame)
         return;
     entity pl = snake_get_player(minigame, pteam);
     if(pl)
     {
         pl.snake_score += thescore;
         pl.SendFlags |= SNAKE_SF_PLAYERSCORE;
     }
 #endif
 }
bool snake_alone (entity minig)
Definition at line 38 of file snake.qc.
References entity(), findentity(), NULL, and owner.
Referenced by snake_check_winner(), and snake_move_head().
 {
     int headcount = 0;
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.cnt == 1 )
             ++headcount;
     return headcount <= 1;
 }
void snake_check_winner (entity minigame)
Definition at line 126 of file snake.qc.
References entity(), MINIG_SF_UPDATE, minigame_server_sendflags(), snake_alone(), snake_get_player(), SNAKE_TEAMS, SNAKE_TURN_LOSS, SNAKE_TURN_WIN, and snake_winning_team().
Referenced by snake_head_think().
 {
     if(snake_alone(minigame) && !minigame.snake_lost_teams)
         return;
     int winner = snake_winning_team(minigame);
     int alivecnt = 0;
     for(int i = 1; i <= SNAKE_TEAMS; ++i)
     {
         entity pl = snake_get_player(minigame, i);
         if(pl && minigame.snake_lives[i] > 0)
             ++alivecnt;
     }
     if(!alivecnt)
     {
         minigame.minigame_flags = SNAKE_TURN_LOSS;
         minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         return;
     }
     if(winner)
     {
         minigame.minigame_flags = SNAKE_TURN_WIN | winner;
         minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     }
 }
void snake_eat_team (entity minigame, int pteam)
Definition at line 271 of file snake.qc.
References BIT, entity(), findentity(), minigame_setup_snake(), NULL, owner, snake_find_head(), snake_get_player(), SNAKE_SF_PLAYERSCORE, strunzone(), and time.
Referenced by snake_move_head().
 {
     entity head = snake_find_head(minigame, pteam);
     if(!head) { return; }
     minigame.snake_lives[pteam] -= 1;
     entity pl = snake_get_player(minigame, pteam);
 #ifdef SVQC
     pl.SendFlags |= SNAKE_SF_PLAYERSCORE;
 #endif
     head.nextthink = time + 1; // make sure they don't to eat us somehow
     entity e = NULL;
     while ( ( e = findentity(e,owner,minigame) ) )
         if ( e.classname == "minigame_board_piece" && e.cnt && e.team == pteam )
         {
             if(e.netname) { strunzone(e.netname); }
             remove(e);
         }
     if(minigame.snake_lives[pteam] <= 0)
         minigame.snake_lost_teams |= BIT(pteam);
     if(pl && minigame.snake_lives[pteam] > 0)
         minigame_setup_snake(minigame, pteam);
 }
entity snake_find_cnt (entity minig, int steam, int tile)
Definition at line 60 of file snake.qc.
References entity(), findentity(), NULL, and owner.
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.cnt == tile && e.team == steam )
             return e;
     return NULL;
 }
entity snake_find_head (entity minig, int steam)
Definition at line 79 of file snake.qc.
References entity(), findentity(), NULL, and owner.
Referenced by snake_eat_team(), and snake_move().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.cnt == 1 && e.team == steam )
             return e;
     return NULL;
 }
entity snake_find_piece (entity minig, string tile)
Definition at line 50 of file snake.qc.
References entity(), findentity(), NULL, and owner.
Referenced by minigame_setup_snake(), snake_move(), snake_move_head(), and snake_new_mouse().
 {
     entity e = NULL;
     while ( ( e = findentity(e,owner,minig) ) )
         if ( e.classname == "minigame_board_piece" && e.netname == tile )
             return e;
     return NULL;
 }
entity snake_get_player (entity minigame, int pteam)
Definition at line 200 of file snake.qc.
References entity(), findentity(), NULL, and owner.
Referenced by snake_add_score(), snake_check_winner(), snake_eat_team(), and snake_winning_team().
 {
     entity e;
 #ifdef SVQC
     for(e = minigame.minigame_players; e; e = e.list_next)
 #elif defined(CSQC)
     e = NULL;
     while( (e = findentity(e,owner,minigame)) )
         if ( e.classname == "minigame_player" )
 #endif
     if(e.team == pteam)
         return e;
     return NULL;
 }
void snake_head_think (entity this)
Definition at line 156 of file snake.qc.
References entity(), nextthink, owner, snake_check_winner(), snake_delay, snake_move_head(), SNAKE_TURN_MOVE, and time.
Referenced by minigame_setup_snake().
 {
     entity minigame = this.owner;
     if(minigame.minigame_flags & SNAKE_TURN_MOVE)
         snake_move_head(minigame, this);
     snake_check_winner(minigame);
     this.nextthink = time + this.snake_delay;
 }
void snake_move (entity minigame, entity player, string dxs, string dys)
Definition at line 364 of file snake.qc.
References bound(), entity(), MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), snake_find_head(), snake_find_piece(), SNAKE_TURN_MOVE, stof(), and time.
 {
     if ( minigame.minigame_flags & SNAKE_TURN_MOVE )
     if ( dxs || dys )
     {
         //if ( snake_valid_tile(pos) )
         //if ( snake_find_piece(minigame, pos) )
         {
             entity head = snake_find_head(minigame, player.team);
             if(!head)
                 return; // their head is already dead
             int dx = ((dxs) ? bound(-1, stof(dxs), 1) : 0);
             int dy = ((dys) ? bound(-1, stof(dys), 1) : 0);
             int myl = minigame_tile_letter(head.netname);
             int myn = minigame_tile_number(head.netname);
             entity check_piece = snake_find_piece(minigame, minigame_tile_buildname(myl + dx, myn + dy));
             if(check_piece && check_piece.cnt == 2)
                 return; // nope!
             if(head.snake_dir == '0 0 0')
                 head.nextthink = time; // TODO: make sure this can't be exploited!
             head.snake_dir_x = dx;
             head.snake_dir_y = dy;
             head.snake_dir_z = 0;
             minigame_server_sendflags(head,MINIG_SF_UPDATE);
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         }
     }
 }
void snake_move_body (entity minigame, entity head, bool ate_mouse)
Definition at line 229 of file snake.qc.
References autocvar_sv_minigames_snake_delay_initial, autocvar_sv_minigames_snake_delay_min, autocvar_sv_minigames_snake_delay_multiplier, entity(), max(), MINIG_SF_UPDATE, minigame_server_sendflags(), msle_spawn(), NULL, snake_add_score(), strunzone(), and strzone().
Referenced by snake_move_head().
 {
     for(entity e = head.snake_last; e; e = e.snake_prev)
     {
         if(!e || e == head) { break; }
         entity nextpiece = e.snake_prev; // can be head
         if(e.netname) { strunzone(e.netname); }
         e.netname = strzone(nextpiece.netname);
         e.snake_dir = nextpiece.snake_dir;
         minigame_server_sendflags(e, MINIG_SF_UPDATE);
     }
     if(ate_mouse)
     {
         entity tail = head.snake_last;
         tail.snake_tail = false;
         int newcnt = tail.cnt + 1;
         head.snake_delay = max(autocvar_sv_minigames_snake_delay_min, autocvar_sv_minigames_snake_delay_initial - (newcnt / autocvar_sv_minigames_snake_delay_multiplier));
         snake_add_score(minigame, head.team, 1);
         entity piece = msle_spawn(minigame,"minigame_board_piece");
         piece.cnt = newcnt;
         piece.team = head.team;
         piece.snake_prev = tail;
         piece.snake_dir = tail.snake_dir;
         piece.snake_next = NULL;
         piece.snake_tail = true;
         piece.netname = strzone(tail.netname);
         tail.snake_next = piece;
         head.snake_last = piece;
         minigame_server_sendflags(piece,MINIG_SF_UPDATE);
         //minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
     }
 }
void snake_move_head (entity minigame, entity head)
Definition at line 300 of file snake.qc.
References autocvar_sv_minigames_snake_wrap, entity(), MINIG_SF_UPDATE, minigame_relative_tile(), minigame_server_sendflags(), minigame_tile_buildname(), minigame_tile_letter(), minigame_tile_number(), snake_add_score(), snake_alone(), snake_eat_team(), snake_find_piece(), SNAKE_LET_CNT, snake_move_body(), snake_new_mouse(), SNAKE_NUM_CNT, SNAKE_TURN_LOSS, snake_valid_tile(), strunzone(), and strzone().
Referenced by snake_head_think().
 {
     if(!head.snake_dir_x && !head.snake_dir_y)
         return; // nope!
     string newpos;
     if(autocvar_sv_minigames_snake_wrap)
         newpos = minigame_relative_tile(head.netname, head.snake_dir_x, head.snake_dir_y, SNAKE_NUM_CNT, SNAKE_LET_CNT);
     else
     {
         int myx = minigame_tile_letter(head.netname);
         int myy = minigame_tile_number(head.netname);
         myx += head.snake_dir_x;
         myy += head.snake_dir_y;
         newpos = minigame_tile_buildname(myx, myy);
     }
     entity hit = snake_find_piece(minigame, newpos);
     if(!snake_valid_tile(newpos) || (hit && hit.cnt && hit.team == head.team))
     {
         if(snake_alone(minigame))
         {
             minigame.minigame_flags = SNAKE_TURN_LOSS;
             minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
         }
         else
         {
             snake_add_score(minigame, head.team, -1);
             snake_eat_team(minigame, head.team);
         }
         return;
     }
     bool ate_mouse = (hit && !hit.cnt);
     // move the body first, then set the new head position?
     snake_move_body(minigame, head, ate_mouse);
     if(head.netname) { strunzone(head.netname); }
     head.netname = strzone(newpos);
     minigame_server_sendflags(head,MINIG_SF_UPDATE);
     // above check makes sure it's not our team
     if(hit.cnt)
     {
         snake_eat_team(minigame, hit.team);
         snake_add_score(minigame, head.team, 1);
     }
     if(ate_mouse)
     {
         if(hit.netname) { strunzone(hit.netname); }
         remove(hit);
         snake_new_mouse(minigame);
     }
 }
void snake_new_mouse (entity minigame)
Definition at line 88 of file snake.qc.
References entity(), MINIG_SF_ALL, MINIG_SF_UPDATE, minigame_server_sendflags(), minigame_tile_buildname(), msle_spawn(), NULL, RandomSelection_Add(), RandomSelection_chosen_string, RandomSelection_Init(), snake_find_piece(), SNAKE_LET_CNT, SNAKE_NUM_CNT, and strzone().
Referenced by snake_move_head(), and snake_setup_pieces().
 {
     RandomSelection_Init();
     int i, j;
     for(i = 0; i < SNAKE_LET_CNT; ++i)
     for(j = 0; j < SNAKE_NUM_CNT; ++j)
     {
         string pos = minigame_tile_buildname(i, j);
         if(!snake_find_piece(minigame, pos))
             RandomSelection_Add(NULL, 0, pos, 1, 1);
     }
     entity piece = msle_spawn(minigame,"minigame_board_piece");
     piece.team = 0;
     piece.netname = strzone(RandomSelection_chosen_string);
     minigame_server_sendflags(piece,MINIG_SF_ALL);
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
 }
void snake_setup_pieces (entity minigame)
Definition at line 193 of file snake.qc.
References MINIG_SF_UPDATE, minigame_server_sendflags(), and snake_new_mouse().
 {
     snake_new_mouse(minigame);
     minigame_server_sendflags(minigame,MINIG_SF_UPDATE);
 }
bool snake_valid_tile (string tile)
Definition at line 70 of file snake.qc.
References minigame_tile_letter(), minigame_tile_number(), SNAKE_LET_CNT, and SNAKE_NUM_CNT.
Referenced by snake_move_head().
 {
     if ( !tile )
         return false;
     int number = minigame_tile_number(tile);
     int letter = minigame_tile_letter(tile);
     return 0 <= number && number < SNAKE_NUM_CNT && 0 <= letter && letter < SNAKE_LET_CNT;
 }
int snake_winning_team (entity minigame)
Definition at line 109 of file snake.qc.
References entity(), snake_get_player(), and SNAKE_TEAMS.
Referenced by snake_check_winner().
 {
     int winning_team = 0;
     for(int i = 1; i <= SNAKE_TEAMS; ++i)
     {
         entity pl = snake_get_player(minigame, i);
         if(pl && minigame.snake_lives[i] > 0)
         {
             if(winning_team)
                 return 0;
             winning_team = i;
         }
     }
     return winning_team;
 }
Variable Documentation
float autocvar_sv_minigames_snake_delay_initial = 0.7
Definition at line 20 of file snake.qc.
Referenced by minigame_setup_snake(), and snake_move_body().
float autocvar_sv_minigames_snake_delay_min = 0.1
Definition at line 22 of file snake.qc.
Referenced by snake_move_body().
float autocvar_sv_minigames_snake_delay_multiplier = 50
Definition at line 21 of file snake.qc.
Referenced by snake_move_body().
int autocvar_sv_minigames_snake_lives = 3
Definition at line 23 of file snake.qc.
bool autocvar_sv_minigames_snake_wrap = false
Definition at line 19 of file snake.qc.
Referenced by snake_move_head().
float snake_delay
Definition at line 27 of file snake.qc.
Referenced by snake_head_think().
vector snake_dir
Definition at line 28 of file snake.qc.
entity snake_last
Definition at line 30 of file snake.qc.
const int SNAKE_LET_CNT = 15
Definition at line 12 of file snake.qc.
Referenced by minigame_setup_snake(), snake_move_head(), snake_new_mouse(), and snake_valid_tile().
int snake_lives[SNAKE_TEAMS+1]
Definition at line 34 of file snake.qc.
int snake_lost_teams
Definition at line 36 of file snake.qc.
entity snake_next
Definition at line 30 of file snake.qc.
const int SNAKE_NUM_CNT = 15
Definition at line 13 of file snake.qc.
Referenced by minigame_setup_snake(), snake_move_head(), snake_new_mouse(), and snake_valid_tile().
entity snake_prev
Definition at line 30 of file snake.qc.
int snake_score
Definition at line 25 of file snake.qc.
const int SNAKE_SF_PLAYERSCORE = MINIG_SF_CUSTOM
Definition at line 10 of file snake.qc.
Referenced by snake_add_score(), and snake_eat_team().
bool snake_tail
Definition at line 32 of file snake.qc.
const int SNAKE_TEAMS = 6
Definition at line 17 of file snake.qc.
Referenced by snake_check_winner(), and snake_winning_team().
const int SNAKE_TILE_SIZE = 15
Definition at line 15 of file snake.qc.
const float SNAKE_TURN_LOSS = 0x0400
Definition at line 5 of file snake.qc.
Referenced by snake_check_winner(), and snake_move_head().
const float SNAKE_TURN_MOVE = 0x0100
Definition at line 3 of file snake.qc.
Referenced by snake_head_think(), and snake_move().
const int SNAKE_TURN_TEAM = 0x000f
Definition at line 8 of file snake.qc.
const float SNAKE_TURN_TYPE = 0x0f00
Definition at line 6 of file snake.qc.
const float SNAKE_TURN_WIN = 0x0200
Definition at line 4 of file snake.qc.
Referenced by snake_check_winner().