Xonotic: server/intermission.qh File Reference
intermission.qh File Reference
Functions
float DoNextMapOverride (float reinit)
void FixIntermissionClient (entity e)
string GetGametype ()
string GetMapname ()
string GetNextMap ()
string GotoMap (string m)
void GotoNextMap (float reinit)
void IntermissionThink (entity this)
void Map_Goto (float reinit)
void Map_Goto_SetStr (string nextmapname)
bool Map_IsRecent (string m)
void Map_MarkAsRecent (string m)
void ShuffleMaplist ()
Variables
bool alreadychangedlevel
bool autocvar_lastlevel
string autocvar_nextmap
bool autocvar_samelevel
bool autocvar_sv_autoscreenshot
string autocvar_sv_intermission_cdtrack
float intermission_exittime
bool intermission_running
Function Documentation
DoNextMapOverride()
float DoNextMapOverride (float reinit)
Definition at line 312 of file intermission.qc.
References alreadychangedlevel, autocvar_g_campaign, autocvar_lastlevel, autocvar_nextmap, autocvar_quit_and_redirect, autocvar_quit_when_empty, autocvar_samelevel, autocvar_sv_vote_gametype, CampaignPostIntermission(), currentbots, cvar_set(), cvar_settemp_restore(), gametypevote, GameTypeVote_MapInfo_FixName(), localcmd, Map_Goto(), Map_Goto_SetStr(), MapInfo_CheckMap(), player_count, redirection_target, and strzone().
Referenced by GotoFirstMap(), GotoMap(), and MapVote_Think().
 {
     if(autocvar_g_campaign)
     {
         CampaignPostIntermission();
         alreadychangedlevel = true;
         return true;
     }
     if(autocvar_quit_when_empty)
     {
         if(player_count <= currentbots)
         {
             localcmd("quit\n");
             alreadychangedlevel = true;
             return true;
         }
     }
     if(autocvar_quit_and_redirect != "")
     {
         redirection_target = strzone(autocvar_quit_and_redirect);
         alreadychangedlevel = true;
         return true;
     }
     if (!reinit && autocvar_samelevel) // if samelevel is set, stay on same level
     {
         localcmd("restart\n");
         alreadychangedlevel = true;
         return true;
     }
     if(autocvar_nextmap != "")
     {
         string m;
         m = GameTypeVote_MapInfo_FixName(autocvar_nextmap);
         cvar_set("nextmap",m);
         if(!m || gametypevote)
             return false;
         if(autocvar_sv_vote_gametype)
         {
             Map_Goto_SetStr(m);
             return false;
         }
         if(MapInfo_CheckMap(m))
         {
             Map_Goto_SetStr(m);
             Map_Goto(reinit);
             alreadychangedlevel = true;
             return true;
         }
     }
     if(!reinit && autocvar_lastlevel)
     {
         cvar_settemp_restore();
         localcmd("set lastlevel 0\ntogglemenu 1\n");
         alreadychangedlevel = true;
         return true;
     }
     return false;
 }
FixIntermissionClient()
void FixIntermissionClient (entity e)
Definition at line 453 of file intermission.qc.
References autocvar_sv_intermission_cdtrack, EF_NODRAW, effects, FOREACH_WORD, IS_REAL_CLIENT, MAX_WEAPONSLOTS, msg_entity, MSG_ONE, RandomSelection_AddString, RandomSelection_chosen_string, RandomSelection_Init(), RES_HEALTH, SetResourceExplicit(), stuffcmd, SVC_INTERMISSION, time, weaponentities, and WriteByte().
Referenced by IntermissionThink(), and NextLevel().
 {
     if(!e.autoscreenshot) // initial call
     {
         e.autoscreenshot = time + 0.8;  // used for autoscreenshot
         SetResourceExplicit(e, RES_HEALTH, -2342); // health in the first intermission phase
         for (int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(e.(weaponentity))
             {
                 e.(weaponentity).effects = EF_NODRAW;
                 if (e.(weaponentity).weaponchild)
                     e.(weaponentity).weaponchild.effects = EF_NODRAW;
             }
         }
         if(IS_REAL_CLIENT(e))
         {
             stuffcmd(e, "\nscr_printspeed 1000000\n");
             RandomSelection_Init();
             FOREACH_WORD(autocvar_sv_intermission_cdtrack, true, {
                 RandomSelection_AddString(it, 1, 1);
             });
             if (RandomSelection_chosen_string != "")
             {
                 stuffcmd(e, sprintf("\ncd loop %s\n", RandomSelection_chosen_string));
             }
             msg_entity = e;
             WriteByte(MSG_ONE, SVC_INTERMISSION);
         }
     }
 }
GetGametype()
string GetGametype ()
Definition at line 13 of file intermission.qc.
References MapInfo_LoadedGametype, and MapInfo_Type_ToString().
Referenced by DumpStats(), readlevelcvars(), spawnfunc(), WeaponStats_ready(), WinningConditionHelper(), and write_recordmarker().
 {
     return MapInfo_Type_ToString(MapInfo_LoadedGametype);
 }
GetMapname()
string GetMapname ()
Definition at line 18 of file intermission.qc.
References mapname.
Referenced by Campaign_Invalid(), checkpoint_passed(), ctf_CaptureRecord(), ctf_Initialize(), DumpStats(), GameCommand_delrec(), GetMaplistPosition(), getrankings(), IntermissionThink(), race_deleteTime(), race_send_recordtime(), race_SendAll(), race_SendRanking(), race_SendTime(), race_setTime(), race_SpeedAwardFrame(), sandbox_Database_Load(), sandbox_Database_Save(), spawnfunc(), trigger_race_checkpoint_verify(), and WeaponStats_ready().
 {
     return mapname;
 }
GetNextMap()
string GetNextMap ()
Definition at line 284 of file intermission.qc.
References autocvar_g_maplist_selectrandom, autocvar_g_maplist_shuffle, getmapname_stored, Map_Goto_SetFloat(), Maplist_Init(), MaplistMethod_Iterate(), MaplistMethod_Random(), MaplistMethod_Repeat(), and MaplistMethod_Shuffle().
Referenced by GotoNextMap(), and MapVote_Init().
 {
     Maplist_Init();
     float nextMap = -1;
     if(nextMap == -1)
         if(autocvar_g_maplist_shuffle > 0)
             nextMap = MaplistMethod_Shuffle(autocvar_g_maplist_shuffle + 1);
     if(nextMap == -1)
         if(autocvar_g_maplist_selectrandom)
             nextMap = MaplistMethod_Random();
     if(nextMap == -1)
         nextMap = MaplistMethod_Iterate();
     if(nextMap == -1)
         nextMap = MaplistMethod_Repeat();
     if(nextMap >= 0)
     {
         Map_Goto_SetFloat(nextMap);
         return getmapname_stored;
     }
     return "";
 }
GotoMap()
string GotoMap (string m)
Definition at line 393 of file intermission.qc.
References alreadychangedlevel, autocvar_sv_vote_gametype, cvar_set(), DoNextMapOverride(), GameTypeVote_MapInfo_FixName(), MapInfo_CheckMap(), and mapvote_initialized.
Referenced by GameCommand_gotomap().
 {
     m = GameTypeVote_MapInfo_FixName(m);
     if (!m)
         return "The map you suggested is not available on this server.";
     if (!autocvar_sv_vote_gametype)
     if(!MapInfo_CheckMap(m))
         return "The map you suggested does not support the current game mode.";
     cvar_set("nextmap", m);
     cvar_set("timelimit", "-1");
     if(mapvote_initialized || alreadychangedlevel)
     {
         if(DoNextMapOverride(0))
             return "Map switch initiated.";
         else
             return "Hm... no. For some reason I like THIS map more.";
     }
     else
         return "Map switch will happen after scoreboard.";
 }
GotoNextMap()
void GotoNextMap (float reinit)
Definition at line 373 of file intermission.qc.
References alreadychangedlevel, error(), GetNextMap(), and Map_Goto().
Referenced by GotoFirstMap(), MapVote_Think(), and SelectSpawnPoint().
 {
     //string nextmap;
     //float n, nummaps;
     //string s;
     if (alreadychangedlevel)
         return;
     alreadychangedlevel = true;
     string nextMap = GetNextMap();
     if(nextMap == "")
         error("Everything is broken - cannot find a next map. Please report this to the developers.");
     Map_Goto(reinit);
 }
IntermissionThink()
void IntermissionThink (entity this)
Definition at line 423 of file intermission.qc.
References autocvar_sv_autoscreenshot, autoscreenshot, CS_CVAR, FixIntermissionClient(), GetMapname(), intermission_exittime, IS_REAL_CLIENT, mapvote_initialized, MapVote_Start(), PHYS_INPUT_BUTTON_ATCK, PHYS_INPUT_BUTTON_ATCK2, PHYS_INPUT_BUTTON_HOOK, PHYS_INPUT_BUTTON_JUMP, PHYS_INPUT_BUTTON_USE, strftime_s(), stuffcmd, and time.
Referenced by PlayerPreThink(), and PlayerThink().
 {
     FixIntermissionClient(this);
     float server_screenshot = (autocvar_sv_autoscreenshot && CS_CVAR(this).cvar_cl_autoscreenshot);
     float client_screenshot = (CS_CVAR(this).cvar_cl_autoscreenshot == 2);
     if( (server_screenshot || client_screenshot)
         && ((this.autoscreenshot > 0) && (time > this.autoscreenshot)) )
     {
         this.autoscreenshot = -1;
         if(IS_REAL_CLIENT(this))
         {
             string num = strftime_s(); // strftime(false, "%s") isn't reliable, see strftime_s description
             stuffcmd(this, sprintf("\nscreenshot screenshots/autoscreenshot/%s-%s.jpg; "
                 "echo \"^5A screenshot has been taken at request of the server.\"\n", GetMapname(), num));
         }
         return;
     }
     if (time < intermission_exittime)
         return;
     if(!mapvote_initialized)
         if (time < intermission_exittime + 10 && !(PHYS_INPUT_BUTTON_ATCK(this) || PHYS_INPUT_BUTTON_JUMP(this) || PHYS_INPUT_BUTTON_ATCK2(this) || PHYS_INPUT_BUTTON_HOOK(this) || PHYS_INPUT_BUTTON_USE(this)))
             return;
     MapVote_Start();
 }
Map_Goto()
void Map_Goto (float reinit)
Definition at line 159 of file intermission.qc.
References getmapname_stored, and MapInfo_LoadMap().
Referenced by DoNextMapOverride(), GotoNextMap(), and MapVote_Finished().
 {
     MapInfo_LoadMap(getmapname_stored, reinit);
 }
Map_Goto_SetStr()
void Map_Goto_SetStr (string nextmapname)
Definition at line 143 of file intermission.qc.
References getmapname_stored, strunzone(), and strzone().
Referenced by DoNextMapOverride(), Map_Goto_SetFloat(), and MapVote_Finished().
 {
     if(getmapname_stored != "")
         strunzone(getmapname_stored);
     if(nextmapname == "")
         getmapname_stored = "";
     else
         getmapname_stored = strzone(nextmapname);
 }
Map_IsRecent()
bool Map_IsRecent (string m)
Definition at line 113 of file intermission.qc.
References autocvar_g_maplist_mostrecent, and strhasword.
Referenced by Map_Check(), MapVote_Suggest(), and ValidateMap().
 {
     return strhasword(autocvar_g_maplist_mostrecent, m);
 }
Map_MarkAsRecent()
void Map_MarkAsRecent (string m)
Definition at line 108 of file intermission.qc.
References autocvar_g_maplist_mostrecent, autocvar_g_maplist_mostrecent_count, cons(), cvar_set(), max(), and strwords().
Referenced by spawnfunc().
 {
     cvar_set("g_maplist_mostrecent", strwords(cons(m, autocvar_g_maplist_mostrecent), max(0, autocvar_g_maplist_mostrecent_count)));
 }
ShuffleMaplist()
void ShuffleMaplist ()
Definition at line 388 of file intermission.qc.
References autocvar_g_maplist, cvar_set(), and shufflewords().
Referenced by GameTypeVote_SetGametype(), GotoFirstMap(), Maplist_Init(), and MapVote_Init().
 {
     cvar_set("g_maplist", shufflewords(autocvar_g_maplist));
 }
Variable Documentation
alreadychangedlevel
bool alreadychangedlevel
Definition at line 11 of file intermission.qh.
Referenced by DoNextMapOverride(), GotoMap(), GotoNextMap(), MapVote_Finished(), and MapVote_Think().
autocvar_lastlevel
bool autocvar_lastlevel
Definition at line 3 of file intermission.qh.
Referenced by DoNextMapOverride().
autocvar_nextmap
string autocvar_nextmap
Definition at line 4 of file intermission.qh.
Referenced by DoNextMapOverride(), GameTypeVote_AvailabilityStatus(), MapVote_Finished(), MapVote_SendEntity(), and MapVote_Think().
autocvar_samelevel
bool autocvar_samelevel
Definition at line 5 of file intermission.qh.
Referenced by DoNextMapOverride().
autocvar_sv_autoscreenshot
bool autocvar_sv_autoscreenshot
Definition at line 6 of file intermission.qh.
Referenced by IntermissionThink().
autocvar_sv_intermission_cdtrack
string autocvar_sv_intermission_cdtrack
Definition at line 7 of file intermission.qh.
Referenced by FixIntermissionClient().
intermission_exittime
float intermission_exittime
Definition at line 10 of file intermission.qh.
Referenced by IntermissionThink(), and NextLevel().
intermission_running
bool intermission_running
Definition at line 9 of file intermission.qh.
Referenced by bot_serverframe(), CheckRules_World(), ClientCommand_mv_getpicture(), ClientCommand_spectate(), FindConnectedComponent(), NextLevel(), PlayerPostThink(), PlayerPreThink(), PlayerThink(), race_SpeedAwardFrame(), ReadyRestart(), and round_handler_Think().