Xonotic: XonoticSandboxToolsDialog Class Reference
XonoticSandboxToolsDialog Class Reference
Public Member Functions
virtual void _changeFocusXY ()
virtual void addItem ()
virtual void addItemCentered ()
virtual void addItemRightCentered ()
virtual void addItemSimple ()
virtual void close ()
virtual void configureDialog ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void enterLieSubitem ()
virtual void enterSubitem ()
virtual void fill ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void gotoRC ()
virtual void hideNotify ()
virtual void itemFromPoint ()
virtual void keyDown ()
virtual void keyUp ()
virtual void leaveSubitem ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveItemAfter ()
virtual void preferredFocusedGrandChild ()
virtual void relinquishFocus ()
virtual void removeItem ()
virtual void resizeNotify ()
virtual void resizeNotifyLie ()
virtual void saveFocus ()
virtual void setAlphaOf ()
virtual void setFirstColumn ()
virtual void setFocus ()
virtual void showNotify ()
virtual void TD ()
virtual void TDempty ()
virtual void TDNoMargin ()
virtual void toString ()
virtual void TR ()
Public Attributes
float allowFocusSound = 0
float alpha = SKINALPHA_TEXT
string backgroundImage = SKINGFX_DIALOGBORDER
float borderLines = SKINHEIGHT_DIALOGBORDER
float closable = 1
entity closeButton = NULL
string closeButtonImage = SKINGFX_CLOSEBUTTON
vector color = SKINCOLOR_DIALOG_SANDBOXTOOLS
float columns = 4
float columnSpacing = SKINMARGIN_COLUMNS
float currentColumn = 0
float currentRow = 0
entity firstChild = NULL
float firstColumn = 0
float focusable = 0
float focused = 0
entity focusedChild = NULL
entity frame = NULL
float intendedHeight = 0
float intendedWidth = 0.8
float isTabRoot = 1
vector itemOrigin = '0 0 0'
vector itemSize = '0 0 0'
vector itemSpacing = '0 0 0'
entity lastChild = NULL
float marginBottom = SKINMARGIN_BOTTOM
float marginLeft = SKINMARGIN_LEFT
float marginRight = SKINMARGIN_RIGHT
float marginTop = SKINMARGIN_TOP
entity mouseFocusedChild = NULL
string name = "SandboxTools"
vector origin = '0 0 0'
entity parent = NULL
float preferredFocusPriority = 0
float requiresConnection = true
float rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL
float rows = 16
float rowSpacing = SKINMARGIN_ROWS
entity savedFocus = NULL
float shown = 0
vector size = '0 0 0'
string title = _("Sandbox Tools")
float titleFontSize = SKINFONTSIZE_TITLE
float titleHeight = SKINFONTSIZE_TITLE * SKINHEIGHT_TITLE
string tooltip = string_null
float zoomedOutTitleBar = SKINHEIGHT_ZOOMEDTITLE != 0
float zoomedOutTitleBarPosition = SKINHEIGHT_ZOOMEDTITLE * 0.5 - 0.5
Detailed Description
Definition at line 4 of file dialog_sandboxtools.qh.
Member Function Documentation
virtual void InputContainer::_changeFocusXY () virtual inherited
virtual void Container::addItem () virtual inherited
Reimplemented in ModalController, and Nexposee.
virtual void Container::addItemCentered () virtual inherited
virtual void Container::addItemRightCentered () virtual inherited
virtual void Dialog::addItemSimple () virtual inherited
virtual void XonoticRootDialog::close () virtual inherited
Reimplemented from Dialog.
virtual void XonoticDialog::configureDialog () virtual inherited
Reimplemented from Dialog.
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 283 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, GameItem, Gametype, Nade, Buff, and Turret.
Definition at line 297 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void Container::draw () virtual inherited
Reimplemented from Item.
Reimplemented in ModalController, MainWindow, XonoticProfileTab, and Nexposee.
virtual void Container::enterLieSubitem () virtual inherited
virtual void Container::enterSubitem () virtual inherited
virtual void XonoticSandboxToolsDialog::fill () virtual
Reimplemented from Dialog.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void InputContainer::focusLeave () virtual inherited
Reimplemented from Container.
virtual void Dialog::gotoRC () virtual inherited
virtual void Container::hideNotify () virtual inherited
Reimplemented from Item.
virtual void Container::itemFromPoint () virtual inherited
virtual void Dialog::keyDown () virtual inherited
Reimplemented from InputContainer.
Reimplemented in XonoticScreenshotViewerDialog.
virtual void Container::keyUp () virtual inherited
Reimplemented from Item.
Reimplemented in Nexposee.
virtual void Container::leaveSubitem () virtual inherited
virtual void InputContainer::mouseDrag () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseMove () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mousePress () virtual inherited
Reimplemented from Container.
virtual void InputContainer::mouseRelease () virtual inherited
Reimplemented from Container.
virtual void Container::moveItemAfter () virtual inherited
virtual void Container::preferredFocusedGrandChild () virtual inherited
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void Container::removeItem () virtual inherited
virtual void InputContainer::resizeNotify () virtual inherited
Reimplemented from Container.
virtual void Container::resizeNotifyLie () virtual inherited
virtual void Container::saveFocus () virtual inherited
virtual void Container::setAlphaOf () virtual inherited
virtual void Dialog::setFirstColumn () virtual inherited
virtual void Container::setFocus () virtual inherited
virtual void Container::showNotify () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticTab, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
virtual void Dialog::TD () virtual inherited
virtual void Dialog::TDempty () virtual inherited
virtual void Dialog::TDNoMargin () virtual inherited
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void Dialog::TR () virtual inherited
Member Data Documentation
float Item::allowFocusSound = 0 inherited
Definition at line 24 of file item.qh.
float XonoticDialog::alpha = SKINALPHA_TEXT inherited
Definition at line 30 of file dialog.qh.
string XonoticDialog::backgroundImage = SKINGFX_DIALOGBORDER inherited
Definition at line 24 of file dialog.qh.
float XonoticDialog::borderLines = SKINHEIGHT_DIALOGBORDER inherited
Definition at line 25 of file dialog.qh.
float Dialog::closable = 1 inherited
Definition at line 44 of file dialog.qh.
entity Dialog::closeButton = NULL inherited
Definition at line 34 of file dialog.qh.
string XonoticDialog::closeButtonImage = SKINGFX_CLOSEBUTTON inherited
Definition at line 26 of file dialog.qh.
vector XonoticSandboxToolsDialog::color = SKINCOLOR_DIALOG_SANDBOXTOOLS
Definition at line 7 of file dialog_sandboxtools.qh.
float XonoticSandboxToolsDialog::columns = 4
Definition at line 10 of file dialog_sandboxtools.qh.
float XonoticDialog::columnSpacing = SKINMARGIN_COLUMNS inherited
Definition at line 18 of file dialog.qh.
float Dialog::currentColumn = 0 inherited
Definition at line 40 of file dialog.qh.
float Dialog::currentRow = 0 inherited
Definition at line 39 of file dialog.qh.
entity Container::firstChild = NULL inherited
Definition at line 29 of file container.qh.
float Dialog::firstColumn = 0 inherited
Definition at line 41 of file dialog.qh.
float Container::focusable = 0 inherited
Definition at line 28 of file container.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
entity Container::focusedChild = NULL inherited
Definition at line 31 of file container.qh.
entity Dialog::frame = NULL inherited
Definition at line 69 of file dialog.qh.
float Dialog::intendedHeight = 0 inherited
Definition at line 35 of file dialog.qh.
float XonoticSandboxToolsDialog::intendedWidth = 0.8
Definition at line 8 of file dialog_sandboxtools.qh.
float Dialog::isTabRoot = 1 inherited
Definition at line 33 of file dialog.qh.
vector Dialog::itemOrigin = '0 0 0' inherited
Definition at line 36 of file dialog.qh.
vector Dialog::itemSize = '0 0 0' inherited
Definition at line 37 of file dialog.qh.
vector Dialog::itemSpacing = '0 0 0' inherited
Definition at line 38 of file dialog.qh.
entity Container::lastChild = NULL inherited
Definition at line 30 of file container.qh.
float XonoticDialog::marginBottom = SKINMARGIN_BOTTOM inherited
Definition at line 15 of file dialog.qh.
float XonoticDialog::marginLeft = SKINMARGIN_LEFT inherited
Definition at line 16 of file dialog.qh.
float XonoticDialog::marginRight = SKINMARGIN_RIGHT inherited
Definition at line 17 of file dialog.qh.
float XonoticDialog::marginTop = SKINMARGIN_TOP inherited
Definition at line 14 of file dialog.qh.
entity InputContainer::mouseFocusedChild = NULL inherited
Definition at line 14 of file inputcontainer.qh.
string XonoticSandboxToolsDialog::name = "SandboxTools"
Definition at line 11 of file dialog_sandboxtools.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
entity Item::parent = NULL inherited
Definition at line 25 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float XonoticSandboxToolsDialog::requiresConnection = true
Definition at line 12 of file dialog_sandboxtools.qh.
float XonoticDialog::rowHeight = SKINFONTSIZE_NORMAL * SKINHEIGHT_NORMAL inherited
Definition at line 20 of file dialog.qh.
float XonoticSandboxToolsDialog::rows = 16
Definition at line 9 of file dialog_sandboxtools.qh.
float XonoticDialog::rowSpacing = SKINMARGIN_ROWS inherited
Definition at line 19 of file dialog.qh.
entity Container::savedFocus = NULL inherited
Definition at line 32 of file container.qh.
float Container::shown = 0 inherited
Definition at line 33 of file container.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
string XonoticSandboxToolsDialog::title = _("Sandbox Tools")
Definition at line 6 of file dialog_sandboxtools.qh.
float XonoticDialog::titleFontSize = SKINFONTSIZE_TITLE inherited
Definition at line 22 of file dialog.qh.
float XonoticDialog::titleHeight = SKINFONTSIZE_TITLE * SKINHEIGHT_TITLE inherited
Definition at line 21 of file dialog.qh.
string Item::tooltip = string_null inherited
Definition at line 29 of file item.qh.
float XonoticDialog::zoomedOutTitleBar = SKINHEIGHT_ZOOMEDTITLE != 0 inherited
Definition at line 28 of file dialog.qh.
float XonoticDialog::zoomedOutTitleBarPosition = SKINHEIGHT_ZOOMEDTITLE * 0.5 - 0.5 inherited
Definition at line 27 of file dialog.qh.
The documentation for this class was generated from the following file:
menu/xonotic/dialog_sandboxtools.qh