Xonotic: menu/xonotic/textbox.qc File Reference
textbox.qc File Reference
#include "textbox.qh"
#include "../item/label.qh"
Functions
entity makeXonoticTextBox ()
void XonoticTextBox_destroy (entity me)
void XonoticTextBox_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
string XonoticTextBox_getTextBoxLine (entity me, int i)
void XonoticTextBox_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticTextBox_setText (entity me, string text)
Function Documentation
makeXonoticTextBox()
entity makeXonoticTextBox ()
Definition at line 4 of file textbox.qc.
References entity(), and NEW.
Referenced by XonoticServerToSTab_fill().
 {
     entity me;
     me = NEW(XonoticTextBox);
     me.configureXonoticListBox(me);
     return me;
 }
XonoticTextBox_destroy()
void XonoticTextBox_destroy (entity me)
Definition at line 12 of file textbox.qc.
 {
     if (me.stringList >= 0)
     {
         buf_del(me.stringList);
         me.stringList = -1;
     }
 }
XonoticTextBox_drawListBoxItem()
void XonoticTextBox_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 86 of file textbox.qc.
References draw_Text(), and vec2.
 {
     string s = me.getTextBoxLine(me, i);
     draw_Text(vec2(0, 0), s, me.realFontSize, me.colorL, me.alpha, true);
 }
XonoticTextBox_getTextBoxLine()
string XonoticTextBox_getTextBoxLine (entity me, int i)
Definition at line 51 of file textbox.qc.
References string_null.
 {
     if (me.stringList >= 0)
     {
         return bufstr_get(me.stringList, i);
     }
     return string_null;
 }
XonoticTextBox_resizeNotify()
void XonoticTextBox_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 62 of file textbox.qc.
References strcat(), string_null, and SUPER.
 {
     me.itemAbsSize = '0 0 0';
     SUPER(XonoticTextBox).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.itemAbsSize.y = absSize.y * me.itemHeight;
     me.itemAbsSize.x = absSize.x * (1 - me.controlWidth);
     me.realFontSize.y = me.fontSize / me.itemAbsSize.y;
     me.realFontSize.x = me.fontSize / me.itemAbsSize.x;
     string temp = string_null;
     for (int i = 0; i < me.nItems; ++i)
     {
         if (!temp)
         {
             temp = me.getTextBoxLine(me, i);
         }
         else
         {
             temp = strcat(temp, "\n", me.getTextBoxLine(me, i));
         }
     }
     me.setText(me, temp);
 }
XonoticTextBox_setText()
void XonoticTextBox_setText (entity me, string text)
Definition at line 21 of file textbox.qc.
References argv(), buf_create, draw_TextWidth_WithColors(), getWrappedLine(), getWrappedLine_remaining, substring(), and tokenizebyseparator.
 {
     if (me.stringList >= 0)
     {
         buf_del(me.stringList);
         me.stringList = -1;
     }
     int buf;
     int line = 0;
     string t;
     buf = buf_create();
     for (int i = 0, n = tokenizebyseparator(text, "\n"); i < n; ++i)
     {
         t = substring(argv(i), 0, -1);
         getWrappedLine_remaining = t;
         while (getWrappedLine_remaining)
         {
             t = getWrappedLine(1, me.realFontSize, draw_TextWidth_WithColors);
             bufstr_set(buf, line, t);
             line++;
         }
     }
     me.stringList = buf;
     me.nItems = line+1;
 }