Xonotic: common/turrets/util.qh File Reference
common/turrets/util.qh File Reference
Defines
#define TURRETS_UTIL_H
Functions
float shortangle_f (float ang1, float ang2)
float anglemods (float v)
float turret_tag_fire_update ()
vector shortangle_vxy (vector ang1, vector ang2)
vector angleofs (entity from, entity to)
vector angleofs3 (vector from, vector from_a, entity to)
void FireImoBeam (vector start, vector end, vector smin, vector smax, float bforce, float f_dmg, float f_velfactor, float deathtype)
Define Documentation
#define TURRETS_UTIL_H
Definition at line 2 of file util.qh.
Function Documentation
float anglemods (float v)
Definition at line 7 of file angle.qc.
References floor().
Referenced by Monster_Move_2D().
{
    v = v - 360 * floor(v / 360);
    if(v >= 180)
        return v - 360;
    else if(v <= -180)
        return v + 360;
    else
        return v;
}
vector angleofs (entity from, entity to)
Definition at line 62 of file angle.qc.
References normalize(), vectoangles(), and vector().
{
    vector v_res;
    v_res = normalize(to.origin - from.origin);
    v_res = vectoangles(v_res);
    v_res = v_res - from.angles;
    if (v_res_x < 0)    v_res_x += 360;
    if (v_res_x > 180)  v_res_x -= 360;
    if (v_res_y < 0)    v_res_y += 360;
    if (v_res_y > 180)  v_res_y -= 360;
    return v_res;
}
vector angleofs3 (vector from, vector from_a, entity to)
Definition at line 79 of file angle.qc.
References normalize(), vectoangles(), and vector().
{
    vector v_res;
    v_res = normalize(to.origin - from);
    v_res = vectoangles(v_res);
    v_res = v_res - from_a;
    if (v_res_x < 0)    v_res_x += 360;
    if (v_res_x > 180)  v_res_x -= 360;
    if (v_res_y < 0)    v_res_y += 360;
    if (v_res_y > 180)  v_res_y -= 360;
    return v_res;
}
void FireImoBeam (vector start, vector end, vector smin, vector smax, float bforce, float f_dmg, float f_velfactor, float deathtype)
float shortangle_f (float ang1, float ang2)
Definition at line 22 of file angle.qc.
Referenced by Monster_Move(), shortangle_v(), and shortangle_vxy().
{
    if(ang1 > ang2)
    {
        if(ang1 > 180)
            return ang1 - 360;
    }
    else
    {
        if(ang1 < -180)
            return ang1 + 360;
    }
    return ang1;
}
vector shortangle_vxy (vector ang1, vector ang2)
Definition at line 49 of file angle.qc.
References shortangle_f(), and vector().
{
    vector vtmp = '0 0 0';
    vtmp_x = shortangle_f(ang1_x,ang2_x);
    vtmp_y = shortangle_f(ang1_y,ang2_y);
    return vtmp;
}
float turret_tag_fire_update ()
Definition at line 5 of file util.qc.
References error(), gettagindex, normalize(), SELFPARAM, tur_head, and v_forward.
{SELFPARAM();
    if(!self.tur_head)
    {
        error("Call to turret_tag_fire_update with self.tur_head missing!\n");
        self.tur_shotorg = '0 0 0';
        return false;
    }
    self.tur_shotorg = gettaginfo(self.tur_head, gettagindex(self.tur_head, "tag_fire"));
    v_forward = normalize(v_forward);
    return true;
}