Xonotic: dpdefs/upstream/menudefs.qc File Reference
menudefs.qc File Reference
Macros
#define GETGAMEDIRINFO_DESCRIPTION 1
#define GETGAMEDIRINFO_NAME 0
Functions
void addwantedhostcachekey (string key)
float altstr_count (string str)
string altstr_get (string str, float num)
string altstr_ins (string str, float num, string set)
string altstr_prepare (string str)
string altstr_set (string str, float num, string set)
string argv (float n)
float bound (float min, float value, float max)
void bprint (string text,...)
void callfunction (...)
float ceil (float f)
void centerprint (string text,...)
void changelevel (string map)
void checkextension (string ext)
string chr (float ascii)
void clientcommand (float client, string s)
float clientcount (void)
float clientstate (void)
void cmd (string command,...)
void copyentity (entity src, entity dst)
void coredump (void)
float cos (float f)
void coverage ()
void crash (void)
float cvar (string name)
const string cvar_defstring (string name)
void cvar_set (string name, string value)
const string cvar_string (string name)
void dprint (string text,...)
float drawcharacter (vector position, float character, vector scale, vector rgb, float alpha, float flag)
float drawcolorcodedstring (vector position, string text, vector scale, float alpha, float flag)
vector drawcolorcodedstring2 (vector position, string text, vector scale, vector rgb, float alpha, float flag)
float drawfill (vector position, vector size, vector rgb, float alpha, float flag)
vector drawgetimagesize (string pic)
float drawpic (vector position, string pic, vector size, vector rgb, float alpha, float flag)
void drawresetcliparea (void)
void drawsetcliparea (float x, float y, float width, float height)
float drawstring (vector position, string text, vector scale, vector rgb, float alpha, float flag)
float drawsubpic (vector position, vector size, string pic, vector srcPosition, vector srcSize, vector rgb, float alpha, float flag)
void eprint (entity e)
void error (string err,...)
float etof (entity ent)
string etos (entity e)
float fabs (float f)
void fclose (float fhandle)
string fgets (float fhandle)
entity find (entity start,.string field, string match)
entity findchainentity (.entity field, entity match)
entity findchainflags (.float field, float match)
entity findchainfloat (.float field, float match)
entity findchainstring (.string field, string match)
entity findentity (entity start,.entity field, entity match)
entity findflags (entity start,.float field, float match)
entity findfloat (entity start,.float field, float match)
float (float key, string bind, float bindmap) setkeybind_bindmap
float (vector bm) setbindmaps
float (string key) stringtokeynum
float (float i) crypto_getmyidstatus
float (string url, float id, string content_type, string delim, float buf, float keyid) crypto_uri_postbuf
float (string str, string sub, float startpos) strstrofs
float (string str, float ofs) str2chr
float (string s1, string s2) strcmp
float (float caseinsensitive, string s,...) crc16
float () buf_create
float (string url, float id, string content_type, string data) uri_post
float (string url, float id, string content_type, string delim, float buf) uri_postbuf
float (float fieldnum, entity ent, string s) putentityfieldstring
float (string s, string separator1,...) tokenizebyseparator
float floor (float f)
float fopen (string filename, float mode)
void fputs (float fhandle, string s)
void freepic (string name)
entity ftoe (float num)
string ftos (float f)
float gecko_create (string name)
void gecko_destroy (string name)
vector gecko_get_texture_extent (string name)
float gecko_keyevent (string name, float key, float eventtype)
void gecko_mousemove (string name, float x, float y)
void gecko_navigate (string name, string URI)
void gecko_resize (string name, float w, float h)
string getextresponse (void)
float gethostcacheindexforkey (string key)
float gethostcachenumber (float fld, float hostnr)
string gethostcachestring (float type, float hostnr)
float gethostcachevalue (float type)
float getkeydest (void)
vector getmousepos (void)
float getmousetarget (void)
vector getresolution (float number)
float gettime (void)
float iscachedpic (string name)
float isdemo ()
float isfunction (string function_name)
float isserver (void)
string keynumtostring (float keynum)
void loadfromdata (string data)
void loadfromfile (string file)
void localsound (string sample)
float log (float f)
float max (float f,...)
float min (float f,...)
float mod (float val, float m)
entity nextent (entity e)
vector normalize (vector v)
void objerror (string err,...)
void parseentitydata (entity ent, string data)
float pow (float a, float b)
string precache_file (string file)
string precache_pic (string name,...)
string precache_sound (string sample)
void print (string text,...)
float random (void)
vector randomvec (void)
void refreshhostcache (...)
float registercvar (string name, string value, float flags)
void remove (entity e)
void resethostcachemasks (void)
void resorthostcache (void)
float rint (float f)
float search_begin (string pattern, float caseinsensitive, float quiet)
void search_end (float handle)
string search_getfilename (float handle, float num)
float search_getsize (float handle)
void sethostcachemasknumber (float mask, float fld, float num, float op)
void sethostcachemaskstring (float mask, float fld, string str, float op)
void sethostcachesort (float fld, float slsf)
void setkeydest (float dest)
void setmousetarget (float trg)
float sin (float f)
entity spawn (void)
void sprint (float clientnum, string text,...)
float sqrt (float f)
void stackdump (void)
float stof (string val,...)
vector stov (string s)
const string str_cvar (string name)
string strcat (string s1, string s2,...)
string (float key, float bindmap) getkeybind_bindmap
string (string command, float bindmap) findkeysforcommand
string (string serveraddress) crypto_getkeyfp
string (float i) crypto_getmykeyfp
string (float c,...) chr2str
string (float ccase, float calpha, float cnum, string s,...) strconv
string (float chars, string s,...) strpad
string (string info, string key, string value,...) infoadd
string (string info, string key) infoget
string (float bufhandle, string glue) buf_implode
string (string digest, string data,...) digest_hex
string (float fieldnum, entity ent) getentityfieldstring
string (string search, string replace, string subject) strreplace
string (string format,...) sprintf
float stringwidth (string text, float handleColors, vector size)
float strlen (string s)
void strunzone (string s)
string strzone (string s)
string substring (string s, float start, float length)
float tokenize (string s)
void traceoff (void)
void traceon (void)
float validstring (string str)
vector vectoangles (vector v)
vector (void) getbindmaps
float vectoyaw (vector v)
float vlen (vector v)
void () m_init
void (float keynr, float ascii) m_keydown
void (float mode) m_toggle
void (float bufhandle, float sortpower, float backward) buf_sort
void (float bufhandle, float string_index, string str) bufstr_set
void (float bufhandle, string pattern, string antipattern) buf_cvarlist
string vtos (vector v)
void WriteAngle (float data, float dest, float desto)
void WriteByte (float data, float dest, float desto)
void WriteChar (float data, float dest, float desto)
void WriteCoord (float data, float dest, float desto)
void WriteEntity (entity data, float dest, float desto)
void WriteLong (float data, float dest, float desto)
void WriteShort (float data, float dest, float desto)
void WriteString (string data, float dest, float desto)
void writetofile (float fhandle, entity ent)
Variables
float CRYPTO_IDSTATUS_EMPTY = 0
float CRYPTO_IDSTATUS_OUTOFRANGE = -1
float CRYPTO_IDSTATUS_SIGNED = 2
float CRYPTO_IDSTATUS_UNSIGNED = 1
float CS_CONNECTED = 2
float CS_DEDICATED = 0
float CS_DISCONNECTED = 1
float CVAR_TYPEFLAG_ENGINE = 8
float CVAR_TYPEFLAG_EXISTS = 1
float CVAR_TYPEFLAG_HASDESCRIPTION = 16
float CVAR_TYPEFLAG_PRIVATE = 4
float CVAR_TYPEFLAG_READONLY = 32
float CVAR_TYPEFLAG_SAVED = 2
float DRAWFLAG_2XMODULATE = 3
float DRAWFLAG_ADDITIVE = 1
float DRAWFLAG_MODULATE = 2
float DRAWFLAG_NORMAL = 0
float drawfont
void end_sys_fields
void end_sys_globals
float ERR_BADDRAWFLAG = -2
float ERR_BADFILENAME = -4
float ERR_BADSCALE = -3
float ERR_BADSIZE = -3
float ERR_CANNOTOPEN = -1
float ERR_INVALIDMODE = -3
float ERR_NOTCACHED = -4
float ERR_NOTENOUGHFILEHANDLES = -2
float ERR_NULLSTRING = -1
float FALSE = 0
float false = 0
float FIELD_ENTITY = 4
float FIELD_FLOAT = 2
float FIELD_FUNCTION = 6
float FIELD_STRING = 1
float FIELD_VECTOR = 3
float FILE_APPEND = 1
float FILE_READ = 0
float FILE_WRITE = 2
float FONT_CENTERPRINT = 5
float FONT_CHAT = 4
float FONT_CONSOLE = 1
float FONT_DEFAULT = 0
float FONT_INFOBAR = 6
float FONT_MENU = 7
float FONT_NOTIFY = 3
float FONT_SBAR = 2
float FONT_USER = 8
float GECKO_BUTTON_DOUBLECLICK = 3
float GECKO_BUTTON_DOWN = 0
float GECKO_BUTTON_PRESS = 2
float GECKO_BUTTON_UP = 1
float KEY_GAME = 0
float KEY_MENU = 2
float KEY_MENU_GRABBED = 3
float KEY_UNKNOWN = -1
float MSG_ALL = 2
float MSG_BROADCAST = 0
float MSG_INIT = 3
float MSG_ONE = 1
float MT_CLIENT = 2
float MT_MENU = 1
entity null_entity
float PRECACHE_PIC_FROMWAD = 1
float PRECACHE_PIC_MIPMAP = 8
float PRECACHE_PIC_NOTPERSISTENT = 2
entity self
float SLIST_HOSTCACHETOTALCOUNT = 1
float SLIST_HOSTCACHEVIEWCOUNT = 0
float SLIST_LEGACY_LINE1 = 1024
float SLIST_LEGACY_LINE2 = 1025
float SLIST_MASK_AND = 0
float SLIST_MASK_OR = 512
float SLIST_MASTERQUERYCOUNT = 2
float SLIST_MASTERREPLYCOUNT = 3
float SLIST_SERVERQUERYCOUNT = 4
float SLIST_SERVERREPLYCOUNT = 5
float SLIST_SORTDESCENDING = 7
float SLIST_SORTFIELD = 6
float SLIST_TEST_CONTAINS = 0
float SLIST_TEST_EQUAL = 4
float SLIST_TEST_GREATER = 5
float SLIST_TEST_GREATEREQUAL = 6
float SLIST_TEST_LESS = 3
float SLIST_TEST_LESSEQUAL = 2
float SLIST_TEST_NOTCONTAIN = 1
float SLIST_TEST_NOTEQUAL = 7
float SLIST_TEST_NOTSTARTSWITH = 9
float SLIST_TEST_STARTSWITH = 8
float SLSF_CATEGORIES = 4
float SLSF_DESCENDING = 1
float SLSF_FAVORITES = 2
float TRUE = 1
float true = 1
Macro Definition Documentation
#define GETGAMEDIRINFO_DESCRIPTION 1
Definition at line 550 of file menudefs.qc.
Referenced by m_init().
#define GETGAMEDIRINFO_NAME 0
Definition at line 549 of file menudefs.qc.
Referenced by m_init().
Function Documentation
void addwantedhostcachekey (string key)
float altstr_count (string str)
string altstr_get (string str, float num)
string altstr_ins (string str, float num, string set)
string altstr_prepare (string str)
string altstr_set (string str, float num, string set)
string argv (float n)
Referenced by _getcommandkey(), Accuracy_LoadLevels(), Ban_LoadBans(), BanCommand_ban(), BanCommand_kickban(), BanCommand_mute(), BanCommand_unban(), BanCommand_unmute(), bd_load_piece(), bd_set_nextlevel(), bot_cmd_aim(), bot_cmd_aimtarget(), bot_cmd_sound(), bot_custom_weapon_priority_setup(), bot_setnameandstuff(), CampaignSaveCvar(), CheatCommand(), CheatsAllowed(), CheckCategoryForEntry(), ClientCommand_autoswitch(), ClientCommand_clientversion(), ClientCommand_minigame(), ClientCommand_mv_getpicture(), ClientCommand_physics(), ClientCommand_selectteam(), ClientCommand_selfstuff(), ClientCommand_sentcvar(), ClientCommand_spectate(), ClientCommand_suggestmap(), ClientCommand_tell(), ClientCommand_voice(), ClientCommand_wpeditor(), Cmd_MapVote_MapDownload(), Cmd_Scoreboard_SetFields(), CommonCommand_editmob(), CommonCommand_info(), CommonCommand_macro_command(), CommonCommand_macro_usage(), CommonCommand_records(), CommonCommand_who(), CSQC_ConsoleCommand(), db_dump(), db_load(), doBGMScript(), effectinfo_read(), expr_evaluate(), FixPlayermodel(), fixPriorityList(), GameCommand(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_animbench(), GameCommand_anticheat(), GameCommand_bot_cmd(), GameCommand_cointoss(), GameCommand_database(), GameCommand_defer_clear(), GameCommand_delrec(), GameCommand_effectindexdump(), GameCommand_gametype(), GameCommand_gettaginfo(), GameCommand_gotomap(), GameCommand_macro_command(), GameCommand_macro_usage(), GameCommand_moveplayer(), GameCommand_setbots(), GameCommand_stuffto(), GameCommand_trace(), GameCommand_warp(), GameTypeVote_DrawGameTypeItem(), GameTypeVote_GetMask(), GameTypeVote_Start(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_addtolist(), GenericCommand_macro_command(), GenericCommand_macro_usage(), GenericCommand_maplist(), GenericCommand_qc_curl(), GenericCommand_removefromlist(), GenericCommand_rpn(), GenericCommand_runtest(), GenericCommand_settemp(), getAllHUDSkins(), getcurrentmod(), GetCvars(), GetCvars_handleFloat(), GetCvars_handleFloatOnce(), GetCvars_handleString(), StringSource::getEntry(), GetIndexedEntity(), getladder(), getmaplist(), GetMaplistPosition(), HUD_CenterPrint(), HUD_Main(), HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_QuickMenu(), HUD_Radar_InputEvent(), IsServerInList(), KeyBinder_Bind_Clear(), LoadMenuSkinValues(), LoadPlayerSounds(), LocalCommand_blurtest(), LocalCommand_boxparticles(), LocalCommand_create_scrshot_ent(), LocalCommand_debugmodel(), LocalCommand_handlevote(), LocalCommand_hud(), LocalCommand_localprint(), LocalCommand_macro_command(), LocalCommand_macro_usage(), LocalCommand_mv_download(), LocalCommand_sendcvar(), m_init_delayed(), Map_Check(), Map_Filename(), Map_Goto_SetFloat(), MapInfo_Get_ByName_NoFallbacks(), Maplist_Init(), MaplistMethod_Shuffle(), mapPriorityList(), MapVote_Init(), Monster_Sound_Precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), nmm_in_mill_string(), OnlineBanList_SendBan(), OnlineBanList_SendUnban(), OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), PrecachePlayerSounds(), QuickMenu_InputEvent(), QuickMenu_Open(), QuickMenu_Page_Load(), RandomItems_ReplaceMapItem(), readplayerstartcvars(), replace_bind(), rewrapCampaign(), sandbox_ObjectPort_Load(), saveCvarsMulti(), set_platmovetype(), spawnfunc(), superspec_filteritem(), SV_ParseClientCommand(), swapInPriorityList(), XonoticServerList::toggleFavorite(), trigger_race_checkpoint_verify(), updateCheck(), UpdateNotification_URI_Get_Callback(), url_multi_fopen(), url_multi_ready(), url_URI_Get_Callback(), VoteCommand(), VoteCommand_checkargs(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_parse(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), weapon_defaultspawnfunc(), WeaponArenaString(), WeaponStats_ready(), XonoticCampaignList_drawListBoxItem(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_keyGrabbed(), XonoticLanguageList_getLanguages(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_refilter(), XonoticParticlesSlider_saveCvars(), XonoticPlayerList_setPlayerList(), XonoticPlayerModelSelector_draw(), XonoticPlayList_addToPlayList(), XonoticPlayList_drawListBoxItem(), XonoticPlayList_removeSelectedFromPlayList(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_saveCvars(), XonoticScoreboardFadeTimeSlider_saveCvars(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), XonoticServerList_refreshServerList(), XonoticTextSlider_loadCvars(), XonoticTextSlider_saveCvars(), XonoticWeaponarenaCheckBox_loadCvars(), XonoticWeaponsList_drawListBoxItem(), and XonoticWeaponsList_toString().
float bound (float min, float value, float max)
Referenced by _draw_SetClip(), AdjustAirAccelQW(), anim_update(), bobmodel_ofs(), bot_aim(), bot_aimdir(), bot_think(), botframe_updatedangerousobjects(), buff_Medic_Heal(), calc_followmodel_ofs(), ClientKill_TeamChange(), compressShotOrigin(), Container_addItem(), cpicon_draw(), CPM_PM_Aircontrol(), CSQC_UpdateView(), CSQCModel_Effects_Apply(), CSQCModel_InterpolateAnimation_1To2_Do(), CSQCModel_InterpolateAnimation_2To4_Do(), CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), ctf_Handle_Pickup(), ctf_Handle_Throw(), dom_DelayedInit(), DrawAmmoItem(), ExponentialFalloff(), fpscounter_update(), freezetag_Initialize(), GenericCommand_rpn(), get_closer_dest(), get_shotvelocity(), GetCurrentFov(), GrapplingHookThink(), Handicap_GetVoluntaryHandicap(), havocbot_chooseweapon(), havocbot_goalrating_ctf_enemyflag(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_keyboard_movement(), HUD_Ammo(), HUD_CenterPrint(), HUD_Configure_DrawGrid(), HUD_Crosshair(), Hud_Dynamic_Frame(), HUD_GetRowCount(), HUD_Mod_Keepaway(), HUD_Mod_Race(), HUD_Notify(), HUD_Panel_SetPos(), HUD_Physics(), HUD_Powerups(), HUD_RaceTimer(), HUD_Radar(), HUD_Radar_Mouse(), HUD_Score_Rankings(), Hud_Shake_Update(), HUD_Vote(), Image_setZoom(), Image_updateAspect(), InputBox_draw(), InputBox_resizeNotify(), InterpolateOrigin_Do(), invasion_DelayedInit(), kh_Initialize(), kh_Key_Damage(), kh_Key_Touch(), ListBox_scrollToItem(), ListBox_setSelected(), LMS_NewPlayerLives(), m_draw(), m_tooltip(), Maplist_Init(), MapVote_ReadOption(), median(), ModalController_switchState(), Monster_Damage(), Monster_Dead_Damage(), Monster_Frozen_Think(), Monster_Move(), Monster_Spawn(), Monster_Spawn_Setup(), MUTATOR_HOOKFUNCTION(), navigation_markroutes_checkwaypoint(), NET_HANDLE(), ons_GeneratorDamage(), ons_GeneratorHeal(), PingPLReport_Think(), PlayerCorpseDamage(), PlayerDamage(), PlayerPreThink(), PlayerThink(), PM_Accelerate(), PM_check_frozen(), PM_jetpack(), Portal_TeleportPlayer(), preMenuDraw(), Projectile_Draw(), race_GetFractionalLapCount(), RadiusDamageForSource(), RandomSeed_Think(), rc_SetLimits(), REGISTER_MUTATOR(), sandbox_ObjectEdit_Scale(), sandbox_ObjectFunction_Touch(), Score_NicePrint(), Scoreboard_Draw(), Scoreboard_GetField(), Scoreboard_MakeTable(), set_tracewalk_dest(), set_tracewalk_dest_2(), skeleton_from_frames(), Spawn_Draw(), Spawn_PreDraw(), Spawn_WeightedPoint(), SpecialCommand(), steerlib_arrive(), steerlib_attract(), steerlib_attract2(), steerlib_repell(), steerlib_wander(), sys_phys_spectator_control(), tdm_DelayedInit(), tracewalk(), turret_draw2d(), turret_gib_draw(), update_mousepos(), UpdateAuxiliaryXhair(), vehicle_aimturret(), ViewLocation_Mouse(), viewmodel_draw(), WarpZone_Fade_PreDraw(), WarpZone_FindRadius_Recurse(), WarpZone_Touch(), WarpZoneLib_NearestPointOnBox(), waypoint_getlinkcost(), WinningCondition_Scores(), XonoticCampaignList_loadCvars(), XonoticColorpicker_draw(), XonoticCreditsList_draw(), XonoticKeyBinder_setSelected(), and XonoticPlayList_startSound().
void bprint (string text, ...)
Referenced by autoskill(), Ban_Enforce(), Ban_MaybeEnforceBan(), bot_fixcount(), CampaignPreIntermission(), CheckRules_World(), ClientCommand_ready(), CommonCommand_timein(), CommonCommand_timeout(), dompoint_captured(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_gametype(), GameCommand_lockteams(), GameCommand_moveplayer(), GameCommand_nospectators(), GameCommand_shuffleteams(), GameCommand_unlockteams(), GameTypeVote_SetGametype(), Maplist_Init(), MapVote_Init(), NextLevel(), PrintToChatAll(), ReadyRestart_force(), RedirectionThink(), VoteAccept(), VoteCommand_call(), VoteCommand_master(), VoteReject(), VoteSpam(), VoteStop(), VoteTimeout(), W_WeaponFrame(), waypoint_spawn_fromeditor(), WinningCondition_Assault(), and WinningCondition_Invasion().
void callfunction (...)
Referenced by ACCUMULATE_call(), and TEST_Run().
float ceil (float f)
Referenced by assault_new_round(), bot_fixcount(), calculate_player_respawn_time(), ClientKill_Silent(), ClientKill_TeamChange(), cpicon_send(), EndFrame(), formatmessage(), generator_send(), GenericCommand_rpn(), HUD_Ammo(), HUD_GetTableSize_BestItemAR(), HUD_InfoMessages(), HUD_Mod_CA(), HUD_Mod_Dom(), HUD_Powerups(), HUD_Score(), HUD_Score_Rankings(), HUD_Timer(), InstantAction_LoadMap(), kh_Controller_SetThink(), MaplistMethod_Shuffle(), MapVote_Draw(), Slider::mousePress(), NIX_GiveCurrentWeapon(), pathlib_astar(), PingPLReport_Think(), PlayerPostThink(), RadiusDamageForSource(), sandbox_ObjectFunction_Touch(), Scoreboard_Draw(), Scoreboard_GetField(), Scoreboard_Rankings_Draw(), ShowRespawnCountdown(), target_invasion_roundend_use(), trunc(), VoteCommand_call(), vsnap(), WinningCondition_Assault(), and XonoticMapInfoDialog_fill().
void centerprint (string text, ...)
Referenced by assault_objective_decrease_use(), door_touch(), GameCommand_adminmsg(), jumppad_push(), Say(), SUB_UseTargets_Ex(), superspec_msg(), and trigger_keylock_touch().
void changelevel (string map)
Referenced by spawnfunc().
void checkextension (string ext)
Referenced by CSQC_UpdateView(), NET_HANDLE(), and REGISTER_MUTATOR().
string chr (float ascii)
Referenced by InputBox_keyDown(), and XonoticMapList_keyDown().
void clientcommand (float client, string s)
Referenced by bot_execute_commands_once(), and SV_ParseClientCommand().
float clientcount (void)
float clientstate (void)
Referenced by m_draw(), and m_gamestatus().
void cmd (string command, ...)
Referenced by bot_command_executed(), CheatCommand(), CheckBox_Click_Redisplay(), CheckSendCvars(), minigame_cmd_workaround(), QuickMenu_Page_Load(), and XonoticCommandButton_Click().
void copyentity (entity src, entity dst)
Referenced by __spawnfunc_spawn(), clearentity(), W_AttachToShotorg(), and weapon_defaultspawnfunc().
void coredump (void)
float cos (float f)
Referenced by bobmodel_ofs(), bot_aimdir(), Cosine_Interpolate(), cpicon_draw(), CSQC_Demo_Camera(), CSQC_UpdateView(), decompressShortVector(), DrawCircleClippedPic(), GenericCommand_rpn(), gsl_ran_gaussian(), HUD_HealthArmor(), HUD_Mod_Keepaway(), HUD_Physics(), movement_oddity(), ons_camSetup(), ons_Teleport(), preMenuDraw(), Rotate(), solve_cubic_pq(), and W_CalculateSpread().
void coverage ()
void crash (void)
float cvar (string name)
Referenced by _getcommandkey(), _MapInfo_Map_ApplyGametype(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), bot_cmd_eval(), buff_Available(), buff_Init(), CampaignBailout(), CampaignPreInit(), checkCompatibility_newtoys(), checkCompatibility_pinata(), checkCompatibility_weaponarena_weapon(), CSQC_UpdateView(), ctf_FlagSetup(), DisableServerBackwardsCompatibility(), expr_evaluate(), freezetag_Initialize(), GameCommand(), getwelcomemessage(), havocbot_bunnyhop(), HUD_Configure_DrawGrid(), HUD_Panel_InputEvent(), HUD_QuickMenu(), isInvisibleString(), kh_Initialize(), Local_Notification(), m_draw(), m_gamestatus(), m_init(), TeamDeathmatch::m_isForcedSupported(), m_play_click_sound(), m_play_focus_sound(), m_tooltip(), MapInfo_CurrentFeatures(), MapInfo_CurrentGametype(), MapInfo_ForbiddenFlags(), MapInfo_LoadMapSettings(), MapInfo_RequiredFlags(), MapList_LoadMap(), Monster_Spawn(), MUTATOR_HOOKFUNCTION(), preMenuDraw(), RandomItems_GetRandomInstagibItemClassName(), RandomItems_GetRandomItemClassNameWithProperty(), RandomItems_GetRandomOverkillItemClassName(), RandomItems_GetRandomVanillaItemClassName(), readlevelcvars(), readplayerstartcvars(), REGISTER_MUTATOR(), setDependent_Check(), someShadowCvarIsEnabled(), spawnfunc(), STATIC_INIT(), texmemsize(), updateCheck(), UpdateConWidthHeight(), updateConwidths(), UpdateNotification_URI_Get_Callback(), WarpZone_FixView(), WarpZone_TraceToss_ThroughZone(), WarpZone_View_Inside(), weapon_defaultspawnfunc(), XonoticAudioSettingsTab_fill(), XonoticCampaignList_draw(), XonoticCampaignList_loadCvars(), XonoticCheckBox_loadCvars(), XonoticColorButton_loadCvars(), XonoticColorButton_saveCvars(), XonoticColorpicker_draw(), XonoticColorpickerString_loadCvars(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_draw(), XonoticDecibelsSlider_loadCvars(), XonoticEffectsSettingsTab_fill(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_toString(), XonoticParticlesSlider_configureXonoticParticlesSlider(), XonoticPicmipSlider_autofix(), XonoticPlayList_draw(), XonoticPlayList_drawListBoxItem(), XonoticPlayList_mouseDrag(), XonoticPlayList_pauseSound(), XonoticPlayList_removeSelectedFromPlayList(), XonoticPlayList_resumeSound(), XonoticPlayList_startSound(), XonoticPlayList_stopSound(), XonoticRadioButton_loadCvars(), XonoticResolutionSlider_configureXonoticResolutionSlider(), XonoticResolutionSlider_draw(), XonoticScreenshotViewerDialog_close(), XonoticScreenshotViewerDialog_loadScreenshot(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), XonoticSlider_loadCvars(), XonoticTeamSelectDialog_showNotify(), and XonoticVideoSettingsTab_fill().
const string cvar_defstring (string name)
Referenced by _MapInfo_Map_ApplyGametypeEx(), CheckFirstRunButton(), CheckPlayerModel(), Client::Client(), ClientCommand_sentcvar(), CSQCPlayer_ModelAppearance_Apply(), cvar_changes_init(), cvar_string_campaignwrapper(), CvarList_Load(), GENERIC_COMMAND(), getwelcomemessage(), LoadMenuSkinValues(), m_init_delayed(), Race::m_parse_mapinfo(), TeamDeathmatch::m_parse_mapinfo(), ClanArena::m_parse_mapinfo(), Domination::m_parse_mapinfo(), KeyHunt::m_parse_mapinfo(), FreezeTag::m_parse_mapinfo(), MainWindow_configureMainWindow(), Shutdown(), SoundList_Menu_Track_Reset(), spawnfunc(), W_FixWeaponOrder_ForceComplete(), XonoticCampaignList_campaignGo(), XonoticColorButton_loadCvars(), XonoticCvarList_drawListBoxItem(), XonoticCvarList_setSelected(), XonoticMutatorsDialog_toString(), XonoticSkinList_getSkins(), and XonoticSoundList_drawListBoxItem().
void cvar_set (string name, string value)
Referenced by _MapInfo_Map_ApplyGametype(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), assault_new_round(), autoskill(), Ban_SaveBans(), bot_getplace(), CampaignBailout(), CampaignPostInit(), CampaignPreInit(), changematchtime(), ClientCommand_tell(), Cmd_Scoreboard_SetFields(), CSQC_Demo_Camera(), CSQC_Init(), CSQC_UpdateView(), Curl_URI_Get_Callback(), cvar_settemp_restore(), CvarList_Filter_ModifiedCvars(), CvarList_Revert_Click(), CvarList_Value_Change(), DisableServerBackwardsCompatibility(), DoNextMapOverride(), GameLogEcho(), GameRules_limit_lead(), GameRules_limit_score(), GameRules_limit_time(), GameRules_limit_time_qualifying(), GameRules_teams(), GameTypeVote_SetGametype(), GenericCommand_addtolist(), GenericCommand_maplist(), GenericCommand_removefromlist(), GenericCommand_rpn(), GotoFirstMap(), GotoMap(), HUD_Chat(), HUD_Configure_Exit_Force(), HUD_Main(), HUD_Mod_Race(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Vote(), InitiateOvertime(), InstantAction_LoadMap(), invasion_DelayedInit(), KeyBinder_Bind_Clear(), KeyBinder_Bind_Reset_All(), LoadMenuSkinValues(), LocalCommand_hud(), m_draw(), m_init(), m_init_delayed(), Race::m_parse_mapinfo(), TeamDeathmatch::m_parse_mapinfo(), ClanArena::m_parse_mapinfo(), Domination::m_parse_mapinfo(), KeyHunt::m_parse_mapinfo(), FreezeTag::m_parse_mapinfo(), Invasion::m_parse_mapinfo(), TeamDeathmatch::m_setTeams(), CaptureTheFlag::m_setTeams(), ClanArena::m_setTeams(), KeyHunt::m_setTeams(), FreezeTag::m_setTeams(), Map_Goto_SetFloat(), Map_MarkAsRecent(), MapInfo_LoadMapSettings_SaveGameType(), MapInfo_SwitchGameType(), MapList_Add_All(), Maplist_Init(), MapList_Remove_All(), MaplistMethod_Shuffle(), MapVote_Init(), MapVote_Think(), MUTATOR_HOOKFUNCTION(), PlayList_Remove_All(), ReadyRestart_force(), RedirectionThink(), replace_bind(), saveCvarsMulti(), ShuffleMaplist(), Shutdown(), SoundList_Menu_Track_Change(), SoundList_Menu_Track_Reset(), spawnfunc(), timeout_handler_think(), XonoticServerList::toggleFavorite(), updateCheck(), updateCompression(), updateConwidths(), url_fclose(), url_single_fopen(), WarpZone_View_Inside(), WarpZone_View_Outside(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_loadall(), WeaponsList_MoveDown_Click(), WeaponsList_MoveUp_Click(), WinningCondition_Assault(), XonoticCampaignList_campaignGo(), XonoticCampaignList_loadCvars(), XonoticCheckBox_saveCvars(), XonoticCheckBoxString_saveCvars(), XonoticColorButton_loadCvars(), XonoticColorButton_saveCvars(), XonoticColorpickerString_saveCvars(), XonoticCrosshairPicker_cellSelect(), XonoticDecibelsSlider_saveCvars(), XonoticInputBox_saveCvars(), XonoticKeyBinder_editUserbind(), XonoticKeyBinder_keyGrabbed(), XonoticLanguageList_saveCvars(), XonoticMapList_g_maplistCacheToggle(), XonoticParticlesSlider_saveCvars(), XonoticPlayerModelSelector_saveCvars(), XonoticPlayList_addToPlayList(), XonoticPlayList_mouseDrag(), XonoticPlayList_removeSelectedFromPlayList(), XonoticPlayList_startSound(), XonoticPlayList_stopSound(), XonoticRadioButton_saveCvars(), XonoticResolutionSlider_saveCvars(), XonoticScoreboardFadeTimeSlider_saveCvars(), XonoticScreenshotViewerDialog_close(), XonoticScreenshotViewerDialog_loadScreenshot(), XonoticSkinList_saveCvars(), XonoticSlider_saveCvars(), XonoticTextSlider_saveCvars(), XonoticWeaponsList_draw(), and XonoticWeaponsList_mouseDrag().
const string cvar_string (string name)
Referenced by _MapInfo_Map_ApplyGametype(), Accuracy_LoadColors(), bot_getplace(), CampaignBailout(), CampaignPreInit(), checkCompatibility_newtoys(), checkCompatibility_pinata(), checkCompatibility_weaponarena_weapon(), CheckFirstRunButton(), CheckSendCvars(), ClientCommand_tell(), CSQC_Init(), CSQC_UpdateView(), ctf_FlagSetup(), cvar_changes_init(), cvar_or(), CvarList_Load(), Buff::display(), Nade::display(), GameItem::display(), Weapon::display(), expr_evaluate(), firstRun_setLanguage(), GameTypeVote_AvailabilityStatus(), GameTypeVote_SendOption(), GameTypeVote_Type_FromString(), GENERIC_COMMAND(), GenericCommand_addtolist(), GenericCommand_maplist(), GenericCommand_removefromlist(), GenericCommand_rpn(), getcurrentmod(), CvarStringSource::getEntry(), GL_CheckExtension(), HUD_GetFontsize(), HUD_mouse_over(), HUD_Panel_LoadCvars(), KeyBinder_Bind_Edit(), LoadMenuSkinValues(), LocalCommand_sendcvar(), m_init(), m_init_delayed(), MainWindow_configureMainWindow(), MapInfo_Get_ByName_NoFallbacks(), MapList_LoadMap(), RandomItems_GetItemReplacementClassNames(), readplayerstartcvars(), CvarStringSource::reload(), saveCvarsMulti(), setDependent_Check(), spawnfunc(), XonoticServerList::toggleFavorite(), updateCheck(), updateCompression(), UpdateConWidthHeight(), updateConwidths(), UpdateNotification_URI_Get_Callback(), VoteCommand_checkargs(), VoteCommand_macro_help(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_loadall(), WeaponArenaString(), WeaponsList_MoveDown_Click(), WeaponsList_MoveUp_Click(), XonoticCampaignList_draw(), XonoticCampaignList_loadCvars(), XonoticCheckBoxString_loadCvars(), XonoticColorButton_loadCvars(), XonoticColorpickerString_loadCvars(), XonoticCrosshairPicker_configureXonoticCrosshairPicker(), XonoticCrosshairPreview_configureXonoticCrosshairPreview(), XonoticCrosshairPreview_draw(), XonoticCvarList_drawListBoxItem(), XonoticCvarList_setSelected(), XonoticInputBox_loadCvars(), XonoticKeyBinder_drawListBoxItem(), XonoticLanguageList_loadCvars(), XonoticLanguageList_setLanguage(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_refilter(), XonoticMutatorsDialog_toString(), XonoticParticlesSlider_loadCvars(), XonoticPlayerModelSelector_loadCvars(), XonoticPlayList_addToPlayList(), XonoticPlayList_configureXonoticPlayList(), XonoticPlayList_draw(), XonoticPlayList_mouseDrag(), XonoticPlayList_removeSelectedFromPlayList(), XonoticPlayList_startSound(), XonoticProfileTab_draw(), XonoticRadioButton_loadCvars(), XonoticRadioButton_saveCvars(), XonoticResolutionSlider_loadCvars(), XonoticScoreboardFadeTimeSlider_loadCvars(), XonoticServerList_refreshServerList(), XonoticSkinList_loadCvars(), XonoticSoundList_drawListBoxItem(), XonoticTextSlider_loadCvars(), XonoticWeaponarenaCheckBox_loadCvars(), XonoticWeaponsList_draw(), XonoticWeaponsList_mouseDrag(), and XonoticWeaponsList_toString().
void dprint (string text, ...)
float drawcharacter (vector position, float character, vector scale, vector rgb, float alpha, float flag)
float drawcolorcodedstring (vector position, string text, vector scale, float alpha, float flag)
Referenced by Draw_ShowNames(), draw_Text(), drawcolorcodedstring_aspect(), drawcolorcodedstring_expanding(), HUD_CenterPrint(), HUD_Chat(), HUD_Notify(), HUD_Quickmenu_DrawEntry(), HUD_RaceTimer(), HUD_Score_Rankings(), InfoMessages_drawstring(), minigame_drawcolorcodedstring_trunc(), minigame_drawcolorcodedstring_wrapped(), Scoreboard_Draw(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), and Scoreboard_Rankings_Draw().
vector drawcolorcodedstring2 (vector position, string text, vector scale, vector rgb, float alpha, float flag)
float drawfill (vector position, vector size, vector rgb, float alpha, float flag)
Referenced by CSQC_UpdateView(), draw_Fill(), drawborderlines(), GameTypeVote_DrawGameTypeItem(), HUD_Configure_DrawGrid(), HUD_Configure_PostDraw(), HUD_Draw(), HUD_MinigameMenu(), HUD_Panel_HlBorder(), HUD_Panel_Mouse(), HUD_Physics(), HUD_QuickMenu(), HUD_Score_Rankings(), MapVote_DrawMapItem(), QuickMenu_Mouse(), Scoreboard_DrawHeader(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), Scoreboard_Rankings_Draw(), and SpecialCommand().
vector drawgetimagesize (string pic)
float drawpic (vector position, string pic, vector size, vector rgb, float alpha, float flag)
Referenced by AuxiliaryXhair_Draw2D(), CSQC_UpdateView(), draw_cursor(), draw_drawMousePointer(), draw_Picture(), GameTypeVote_DrawGameTypeItem(), HUD_Main(), HUD_MinigameMenu(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), MapVote_DrawMapItem(), minigame_drawpic_centered(), minigame_hud_simpleboard(), Scoreboard_DrawItem(), Scoreboard_MakeTable(), SpecialCommand(), turret_draw2d(), Vehicles_drawCrosshair(), and Vehicles_drawHUD().
void drawresetcliparea (void)
Referenced by draw_ClearClip(), DrawDomItem(), HUD_Vote(), and Vehicles_drawHUD().
void drawsetcliparea (float x, float y, float width, float height)
Referenced by _draw_SetClip(), draw_ClearClip(), DrawDomItem(), HUD_Radar(), HUD_Vote(), and Vehicles_drawHUD().
float drawstring (vector position, string text, vector scale, vector rgb, float alpha, float flag)
Referenced by CSQC_UpdateView(), draw_Text(), drawstring_aspect(), drawstring_expanding(), GameTypeVote_DrawGameTypeItem(), HUD_RaceTimer(), HUD_Score_Rankings(), MapStats_DrawKeyValue(), MapVote_Draw(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), minigame_drawstring_trunc(), minigame_drawstring_wrapped(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawItem(), Scoreboard_DrawOthers(), Scoreboard_MapStats_Draw(), Scoreboard_Rankings_Draw(), and Vehicles_drawHUD().
float drawsubpic (vector position, vector size, string pic, vector srcPosition, vector srcSize, vector rgb, float alpha, float flag)
void eprint (entity e)
Referenced by Draw_ShowNames_All(), InitializeEntitiesRun(), RegisterTeam(), and TeamScore_SendEntity().
void error (string err, ...)
float etof (entity ent)
Referenced by _Movetype_UnstickEntity(), botframe_showwaypointlinks(), CheatCommand(), ClientConnect(), CommonCommand_who(), CSQC_Ent_Update(), end_minigame(), GameCommand_defer_clear_all(), GetFilteredNumber(), GrapplingHookSend(), invite_minigame(), minigame_addplayer(), minigame_autoclean_entity(), minigame_rmplayer(), minigame_SendEntity(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), PlayerScore_SendEntity(), PutObserverInServer(), SetSpectatee(), SpawnEvent_Send(), start_minigame(), and VoteCommand_parse().
string etos (entity e)
Referenced by _dumptree_open(), LinkDoors(), ons_DelayedLinkSetup(), onslaught_updatelinks(), Pickup::show(), and waypoint_unreachable().
float fabs (float f)
Referenced by _Movetype_FlyMove(), _Movetype_Physics_Walk(), AdjustAirAccelQW(), almost_equals_eps(), AnglesTransform_CancelRoll(), animdecide_setimplicitstate(), anticheat_physics(), bot_fixcount(), cbrt(), copysign(), CSQC_UpdateView(), DragBox_Think(), MenuItem::draw(), DrawCircleClippedPic(), DynamicHandicap_UpdateHandicap(), float2range11(), GenericCommand_rpn(), GeomLerp(), havocbot_bunnyhop(), havocbot_checkgoaldistance(), HUD_Crosshair(), Hud_Dynamic_Frame(), HUD_EngineInfo(), HUD_HealthArmor(), HUD_Powerups(), HUD_Score(), ilogb(), IsMoveInDirection(), lgamma(), ListBox_draw(), logb(), Slider::mousePress(), MUTATOR_HOOKFUNCTION(), navigation_shortenpath(), nextafter(), nmm_tile_adjacent(), pathlib_h_diagonal(), pathlib_h_diagonal2(), pathlib_h_diagonal2sdp(), pathlib_h_diagonal3(), pathlib_h_manhattan(), pathlib_wateroutnode(), PM_Accelerate(), round_handler_Init(), Slider_configureSliderValues(), sys_phys_simulate(), TEST(), trigger_push_calculatevelocity(), trigger_push_test(), url_URI_Get_Callback(), vehicles_damage(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_getSymmetricalPoint(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_saveCvars(), and XonoticSlider_configureXonoticSlider().
void fclose (float fhandle)
Referenced by _MapInfo_Generate(), _MapInfo_Parse_Settemp(), bd_load_level(), bd_save_level(), BGMScript_Init(), bot_setnameandstuff(), buf_load(), buf_save(), CampaignFile_Load(), CampaignSaveCvar(), CheatCommand(), db_dump(), db_load(), db_save(), DumpStats(), effectinfo_read(), fexists(), GameCommand_bot_cmd(), GameLogClose(), GENERIC_COMMAND(), get_model_parameters(), getAllHUDSkins(), HUD_Panel_ExportCfg(), language_filename(), LoadMenuSkinValues(), LoadPlayerSounds(), LocalCommand_create_scrshot_ent(), m_init_delayed(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), Monster_Sound_Precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), PrecachePlayerSounds(), QuickMenu_Open(), sandbox_Database_Load(), spawnfunc(), STATIC_INIT_LATE(), superspec_save_client_conf(), trigger_race_checkpoint_verify(), url_fclose(), W_HitPlotClose(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_save_links(), waypoint_saveall(), XonoticLanguageList_getLanguages(), and XonoticSkinList_getSkins().
string fgets (float fhandle)
Referenced by _MapInfo_Generate(), _MapInfo_Parse_Settemp(), bd_load_level(), BGMScript_Init(), bot_setnameandstuff(), buf_load(), CampaignFile_Load(), CampaignSaveCvar(), db_load(), effectinfo_read(), GameCommand_bot_cmd(), GameCommand_effectindexdump(), get_model_parameters(), getAllHUDSkins(), LoadMenuSkinValues(), LoadPlayerSounds(), m_init_delayed(), MapHasRightSize(), Monster_Sound_Precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), PrecachePlayerSounds(), QuickMenu_Open(), sandbox_Database_Load(), spawnfunc(), trigger_race_checkpoint_verify(), url_fgets(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), XonoticLanguageList_getLanguages(), and XonoticSkinList_getSkins().
entity find (entity start, .string field, string match)
Referenced by bot_getplace(), buffs_DelayedInit(), CA_SpectateNext(), CheatCommand(), CheatImpulse(), ctf_DelayedInit(), dom_controlpoint_setup(), dom_DelayedInit(), dompointtouch(), HUD_MinigameMenu_ClickJoin(), info_autoscreenshot_findtarget(), jumppad_push(), LinkDoors_nextent(), m_goto(), minigame_read_owner(), Monster_Move(), MUTATOR_HOOKFUNCTION(), ons_DelayedLinkSetup(), ons_MonsterSpawn_Delayed(), ons_TurretSpawn_Delayed(), SelectSpawnPoint(), SpectateNext(), SUB_UseTargets_Ex(), target_init_verify(), tdm_DelayedInit(), TeamBalance_CheckAllowedTeams(), teleport_findtarget(), train_next(), train_next_find(), train_wait(), trigger_impulse_touch_directional(), trigger_keylock_kill(), trigger_keylock_trigger(), trigger_push_test(), trigger_race_checkpoint_verify(), vehicle_initialize(), WarpZone_PostInitialize_Callback(), and WinningCondition_Assault().
entity findchainentity (.entity field, entity match)
entity findchainflags (.float field, float match)
Referenced by find_bot_by_number().
entity findchainfloat (.float field, float match)
Referenced by havocbot_dodge(), and WarpZone_FindRadius().
entity findchainstring (.string field, string match)
entity findentity (entity start, .entity field, entity match)
Referenced by bd_check_winner(), bd_find_controller(), bd_find_dozer(), bd_find_piece(), bd_move(), bd_reset_moves(), bd_save_level(), bd_setup_pieces(), c4_find_piece(), deactivate_minigame(), end_minigame(), minigame_count_players(), minigame_resend(), nmm_find_tile(), nmm_kill_tiles(), nmm_tile_canmove(), pp_find_piece(), pp_next_match(), ps_draw(), ps_find_piece(), ps_winning_piece(), ttt_find_piece(), and ttt_next_match().
entity findflags (entity start, .float field, float match)
entity findfloat (entity start, .float field, float match)
Referenced by CSQCModel_AutoTagIndex_Apply(), CSQCModel_server2csqc(), effectinfo_dump(), HUD_MinigameMenu_ClickInvite(), and LocalCommand_boxparticles().
float (float key, string bind, float bindmap)
float (vector bm)
float (string key)
float (float i)
float (string url, float id, string content_type, string delim, float buf, float keyid)
float (string str, string sub, float startpos)
float (string str, float ofs)
float (string s1, string s2)
float (float caseinsensitive, string s, ...)
float ()
float (string url, float id, string content_type, string data)
float (string url, float id, string content_type, string delim, float buf)
float (float fieldnum, entity ent, string s)
float (string s, string separator1, ...)
float floor (float f)
Referenced by anglemods(), Announcer_Countdown(), Announcer_Gamestart(), anticheat_physics(), bot_aimdir(), bot_cmd_turn(), bot_fixcount(), compressShortVector(), count_fill(), count_ordinal(), crosshair_getcolor(), crosshairpicker_crosshairToCell(), ctf_Handle_Capture(), ctf_Handle_Pickup(), DisableServerBackwardsCompatibility(), DistributeEvenly_Get(), DistributeEvenly_GetRandomized(), DragBox_Think(), DrawDebugModel(), DrawDomItem(), FixPlayermodel(), fixPriorityList(), format_time(), formatmessage(), Freeze(), GenericCommand(), GenericCommand_rpn(), getladder(), GlobalSound_sample(), HUD_CenterPrint(), HUD_Chat(), HUD_GetRowCount(), HUD_HealthArmor(), HUD_Main(), HUD_Notify(), HUD_Panel_InputEvent(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Powerups(), HUD_Score_Rankings(), Hud_Shake_Update(), HUD_Timer(), hue_mi_ma_to_rgb(), ilogb(), img_select(), InputBox_draw(), InstantAction_LoadMap(), invertLengthLog(), is_int(), leanmodel_ofs(), lgamma(), ListBox_getItemAtPos(), logb(), MapInfo_FindName(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_LoadMapSettings(), MaplistMethod_Random(), MapVote_Init(), MapVote_MoveUp(), MapVote_Suggest(), MDL_GIB_ROBO_RANDOM(), minigame_tile_name(), mmsss(), mmssss(), Slider::mousePress(), Movetype_Physics_MatchTicrate(), MUTATOR_HOOKFUNCTION(), play_countdown(), process_time(), ps_setup_pieces(), pymod(), QuickMenu_Mouse(), race_send_speedaward(), race_send_speedaward_alltimebest(), RandomItems_ReplaceMapItem(), RandomSeed_Think(), rgb_to_hexcolor(), round_handler_Init(), Score_NicePrint(), Scoreboard_GetName(), Scoreboard_MakeTable(), Scoreboard_Rankings_Draw(), seconds_tostring(), shuffle(), Slider_configureSliderValues(), Slider_mouseDrag(), SND_GIB_SPLAT_RANDOM(), spawnfunc(), SpecialCommand(), SUB_CalcAngleMove(), SUB_CalcMove_controller_think(), textLengthUpToLength(), textLengthUpToWidth(), trunc(), turret_draw2d(), updateCheck(), waypoint_loadall(), xencode(), XonoticColorButton_loadCvars(), XonoticDecibelsSlider_loadCvars(), XonoticKeyBinder_setSelected(), XonoticPicker_mouseMove(), XonoticScreenshotImage_draw(), XonoticServerList_draw(), and XonoticServerList_getItemAtPos().
float fopen (string filename, float mode)
Referenced by _MapInfo_Generate(), _MapInfo_Parse_Settemp(), bd_load_level(), bd_save_level(), BGMScript_Init(), bot_setnameandstuff(), buf_load(), buf_save(), CampaignFile_Load(), CampaignSaveCvar(), CheatCommand(), db_dump(), db_load(), db_save(), DumpStats(), effectinfo_read(), fexists(), GameCommand_bot_cmd(), GameCommand_effectindexdump(), GameLogEcho(), GENERIC_COMMAND(), get_model_parameters(), getAllHUDSkins(), HUD_Panel_ExportCfg(), language_filename(), LoadMenuSkinValues(), LoadPlayerSounds(), LocalCommand_create_scrshot_ent(), m_init_delayed(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), Monster_Sound_Precache(), Monster_Sounds_Load(), MUTATOR_HOOKFUNCTION(), PrecachePlayerSounds(), QuickMenu_Open(), sandbox_Database_Load(), sandbox_Database_Save(), spawnfunc(), STATIC_INIT_LATE(), superspec_save_client_conf(), trigger_race_checkpoint_verify(), url_single_fopen(), W_HitPlotOpen(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_save_links(), waypoint_saveall(), XonoticLanguageList_getLanguages(), and XonoticSkinList_getSkins().
void fputs (float fhandle, string s)
Referenced by bd_save_level(), buf_save(), CampaignSaveCvar(), CheatCommand(), db_dump(), db_save(), DumpStats(), GameLogEcho(), LocalCommand_create_scrshot_ent(), MapInfo_Get_ByName_NoFallbacks(), RegisterCvars_Save(), sandbox_Database_Save(), superspec_save_client_conf(), url_fputs(), W_HitPlotAnalysis(), W_HitPlotOpen(), waypoint_save_links(), and waypoint_saveall().
void freepic (string name)
entity ftoe (float num)
string ftos (float f)
Referenced by _json_parse_array(), _json_parse_int(), _MapInfo_FilterGametype(), _MapInfo_Generate(), Accuracy_LoadColors(), anticheat_display(), anticheat_report_to_eventlog(), AppendItemcodes(), assault_new_round(), autoskill(), Ban_Insert(), Ban_SaveBans(), Ban_View(), bd_save_controller_piece(), bd_save_piece(), bot_cmd_debug_assert_canfire(), bot_execute_commands_once(), bot_relinkplayerlist(), CampaignPostInit(), CampaignPreInit(), CampaignSaveCvar(), CampaignSetup(), changematchtime(), CheatCommand(), ClientConnect(), ClientDisconnect(), Cmd_MapVote_MapDownload(), CommonCommand_editmob(), CommonCommand_time(), CommonCommand_timeout(), CommonCommand_who(), crosshairpicker_cellToCrosshair(), CSQC_UpdateView(), ctf_CaptureRecord(), ctf_EventLog(), ctf_Handle_Pickup(), cts_EventLog(), CvarList_Filter_ModifiedCvars(), db_save(), Deathtype_Name(), dialog_hudpanel_main_settings(), DisableServerBackwardsCompatibility(), DistributeEvenly_Init(), dom_EventLog(), draw_teamradar_icon(), DrawAmmoItem(), drawBackground(), DrawCAItem(), DrawDomItem(), DrawNumIcon_expanding(), DumpStats(), end_minigame(), expr_evaluate(), fixPriorityList(), formatmessage(), GameCommand_allspec(), GameCommand_animbench(), GameCommand_bot_cmd(), GameCommand_defer_clear_all(), GameCommand_effectindexdump(), GameCommand_gettaginfo(), GameCommand_moveplayer(), GameCommand_nospectators(), GameCommand_trace(), GameLogEcho(), GameRules_limit_lead(), GameRules_limit_score(), GameRules_limit_time(), GameRules_limit_time_qualifying(), GameType_ConfigureSliders(), GenericCommand_rpn(), GenericCommand_settemp_restore(), get_model_datafilename(), get_model_parameters(), get_monster_model_datafilename(), getladder(), GetPlayerScoreString(), GetTeamScoreString(), getwelcomemessage(), GotoFirstMap(), havocbot_goalrating_ons_controlpoints_attack(), havocbot_moveto(), HitSound(), HUD_Chat(), HUD_Main(), HUD_MinigameMenu_ClickInvite(), HUD_Mod_Race(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Score(), HUD_Score_Rankings(), InitiateOvertime(), InstantAction_LoadMap(), invite_minigame(), isnt_bool(), isnt_int(), ka_EventLog(), kh_Scores_Event(), LocalCommand_create_scrshot_ent(), LocalCommand_handlevote(), LocalCommand_hud(), LogDeath(), m_draw(), Map_Goto_SetFloat(), MapInfo_Cache_Store(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_LoadMapSettings_SaveGameType(), MaplistMethod_Shuffle(), MapVote_CheckPK3(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_InputEvent(), MapVote_SendChoice(), MapVote_Suggest(), minigame_addplayer(), minigame_autoclean_entity(), minigame_rmplayer(), minigame_tile_buildname(), mmsss(), mmssss(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), OnlineBanList_SendBan(), OnlineBanList_URI_Get_Callback(), onslaught_updatelinks(), pathlib_astar(), pathlib_makenode_adaptive(), pathlib_waypointpath(), pathlib_waypointpath_step(), PlayerJump(), PlayerPreThink(), prandom(), Process_Notif_Args(), psrandom(), QuickMenu_Open(), race_deleteTime(), race_EventLog(), race_readName(), race_readTime(), race_readUID(), race_writeTime(), ReadyRestart_force(), RedirectionThink(), sandbox_Database_Load(), sandbox_Database_Save(), sandbox_ObjectFunction_Touch(), Say(), Scoreboard_Draw(), Scoreboard_GetField(), Shutdown(), spawnfunc(), start_minigame(), StartFrame(), STATIC_INIT(), superspec_save_client_conf(), sys_phys_fixspeed(), timeout_handler_think(), trigger_race_checkpoint_verify(), turret_gibboom(), updateCheck(), updateConwidths(), UpdateDamage(), URI_Get_Callback(), url_fclose(), url_single_fopen(), VoteCommand_call(), VoteCommand_master(), VoteCommand_parse(), VoteSpam(), VoteStop(), W_FixWeaponOrder_BuildImpulseList(), W_HitPlotAnalysis(), W_HitPlotOpen(), W_NumberWeaponOrder_MapFunc(), W_SetupProjVelocity_Explicit(), WarpZone_View_Outside(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_saveall(), WeaponStats_ready(), WinningCondition_Assault(), WinningConditionHelper(), write_recordmarker(), XonoticCampaignList_loadCvars(), XonoticColorButton_loadCvars(), XonoticColorButton_saveCvars(), XonoticColorpickerString_saveCvars(), XonoticDecibelsSlider_saveCvars(), XonoticHUDExitDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticPlayerModelSelector_loadModels(), XonoticPlayerModelSelector_saveCvars(), XonoticPlayList_drawListBoxItem(), XonoticPlayList_mouseDrag(), XonoticPlayList_removeSelectedFromPlayList(), XonoticPlayList_startSound(), XonoticRadioButton_saveCvars(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_loadResolutions(), XonoticScreenshotViewerDialog_close(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), and XonoticStatsList_getStats().
float gecko_create (string name)
void gecko_destroy (string name)
vector gecko_get_texture_extent (string name)
float gecko_keyevent (string name, float key, float eventtype)
void gecko_mousemove (string name, float x, float y)
void gecko_navigate (string name, string URI)
void gecko_resize (string name, float w, float h)
string getextresponse (void)
float gethostcacheindexforkey (string key)
float gethostcachenumber (float fld, float hostnr)
Referenced by CheckCategoryForEntry(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_draw(), and XonoticServerList_drawListBoxItem().
string gethostcachestring (float type, float hostnr)
Referenced by CheckCategoryForEntry(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_draw(), XonoticServerList_drawListBoxItem(), and XonoticServerList_setSelected().
float gethostcachevalue (float type)
Referenced by XonoticServerList_draw(), and XonoticServerList_setSelected().
float getkeydest (void)
Referenced by m_draw().
vector getmousepos (void)
Referenced by CSQC_Demo_Camera(), m_draw(), m_keydown(), update_mousepos(), and ViewLocation_Mouse().
float getmousetarget (void)
Referenced by m_draw().
vector getresolution (float number)
Referenced by XonoticResolutionSlider_loadResolutions(), and XonoticResolutionSlider_saveCvars().
float gettime (void)
Referenced by CommonCommand_time(), fpscounter_update(), GameCommand_animbench(), HUD_EngineInfo(), m_draw(), pathlib_astar(), pathlib_waypointpath(), STATIC_INIT(), and W_SetupProjVelocity_Explicit().
float iscachedpic (string name)
float isdemo ()
Referenced by ConsoleCommand_macro_init(), CSQC_UpdateView(), CSQCPlayer_ModelAppearance_Apply(), GameCommand(), Gamemode_Init(), GetCurrentFov(), HUD_Configure_Frame(), LocalCommand_hud(), m_gamestatus(), and Shutdown().
float isfunction (string function_name)
Referenced by TEST_Run().
float isserver (void)
Referenced by m_gamestatus().
string keynumtostring (float keynum)
Referenced by _getcommandkey(), KeyBinder_Bind_Clear(), replace_bind(), XonoticKeyBinder_drawListBoxItem(), and XonoticKeyBinder_keyGrabbed().
void loadfromdata (string data)
void loadfromfile (string file)
void localsound (string sample)
Referenced by m_play_click_sound(), and m_play_focus_sound().
float log (float f)
float max (float f, ...)
Referenced by _MapInfo_Generate(), _Movetype_PushEntityTrace(), almost_equals(), almost_equals_eps(), almost_in_bounds(), animdecide_getloweranim(), animdecide_getupperanim(), Announcer_Time(), anticheat_physics(), autoskill(), Ban_Insert(), bobmodel_ofs(), bot_aimdir(), bot_fixcount(), bot_think(), buff_Init(), buff_NewType(), buff_SetCooldown(), buff_Think(), CalcRot(), CalcRotRegen(), centerprint_generic(), changematchtime(), CheatCommand(), CheatImpulse(), ClientKill_TeamChange(), CPM_PM_Aircontrol(), Create_Notification_Entity_Choice(), Create_Notification_Entity_Multi(), CSQC_Demo_Camera(), CSQC_UpdateView(), CSQCPlayer_ModelAppearance_Apply(), ctf_Handle_Capture(), DecodeLevelParms(), Drag_MoveBackward(), Drag_Update(), Draw_ShowNames(), fdim(), Fire_AddDamage(), fireBullet(), fmax(), formatmessage(), GameCommand_shuffleteams(), GameTypeVote_DrawGameTypeItem(), GenericCommand(), GenericCommand_rpn(), GetCurrentFov(), getFadedAlpha(), GetReleaseAmplitude(), GetReleaseTime(), GiveResource(), GiveValue(), GrapplingHookThink(), havocbot_checkgoaldistance(), havocbot_goalrating_enemyplayers(), havocbot_goalrating_items(), havocbot_goalrating_waypoints(), havocbot_keyboard_movement(), HUD_CenterPrint(), HUD_Chat(), Hud_Dynamic_Frame(), HUD_InfoMessages(), HUD_Mod_Race(), HUD_ModIcons(), HUD_Notify(), HUD_Panel_Check_Mouse_Pos(), HUD_Panel_Highlight(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), HUD_Score_Rankings(), HUD_Timer(), HUD_Weapons(), Image_setZoom(), img_select(), InputBox_draw(), Invasion_RoundStart(), ListBox_keyDown(), ListBox_mouseDrag(), ListBox_updateControlTopBottom(), m_draw(), Map_MarkAsRecent(), MapVote_Draw(), MapVote_DrawMapItem(), Monster_Frozen_Think(), ListBox::mousePress(), Slider::mousePress(), Movetype_Physics_MatchTicrate(), MUTATOR_HOOKFUNCTION(), navigation_markroutes_nearestwaypoints(), navigation_shortenpath(), NET_HANDLE(), nextafter(), OnlineBanList_Think(), Onslaught_CheckWinner(), pathlib_h_diagonal(), PlayerCorpseDamage(), PlayerDamage(), PlayerPreThink(), PlayerThink(), PM_Accelerate(), PM_AirAccelerate(), PM_jetpack(), Porto_Draw(), preMenuDraw(), Projectile_Draw(), race_GetFractionalLapCount(), RadiusDamageForSource(), readplayerstartcvars(), rgb_to_hsl(), rgb_to_hsv(), round_handler_FirstThink(), RunThink(), Say(), Score_NicePrint_Team(), Scoreboard_Draw(), Scoreboard_DrawOthers(), Scoreboard_GetField(), Scoreboard_Rankings_Draw(), smneg_multiplier(), SpecialCommand(), steerlib_dodge(), sys_phys_fixspeed(), sys_phys_simulate(), texmemsize(), trace_hits_box_1d(), updateConwidths(), vec_to_max(), vehicles_locktarget(), vehicles_painframe(), viewmodel_draw(), vlen_maxnorm2d(), vlen_minnorm2d(), W_Nexball_Attack(), WarpZone_FixNearClip(), WarpZone_FixView(), WarpZone_Teleport(), WarpZone_Touch(), WinningCondition_Scores(), and XonoticStatsList_getStats().
float min (float f, ...)
Referenced by _MapInfo_Generate(), _Movetype_Physics_Toss(), bobmodel_ofs(), bot_cmd_aim(), bot_fixcount(), bot_think(), Button_resizeNotify(), CalcRegen(), CalcRotRegen(), centerprint_generic(), changematchtime(), CreatureFrame_FallDamage(), ctf_CalculatePassVelocity(), ctf_CheckPassDirection(), Drag_Update(), Draw_ShowNames(), drawpic_tiled(), Fire_AddDamage(), Fire_ApplyDamage(), fireBullet(), fmin(), formatmessage(), GameTypeVote_GetMask(), GameTypeVote_Start(), GenericCommand_rpn(), GetCurrentFov(), getFadedAlpha(), getladder(), GiveValue(), havocbot_role_ctf_carrier(), havocbot_role_ctf_retriever(), HUD_CenterPrint(), HUD_Chat(), HUD_InfoMessages(), HUD_Mod_Race(), HUD_ModIcons(), HUD_Notify(), HUD_Panel_CheckResize(), HUD_Panel_DrawHighlight(), HUD_Physics(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), Image_setZoom(), img_select(), InitGameplayMode(), InputBox_draw(), ListBox_keyDown(), ListBox_mouseDrag(), ListBox_updateControlTopBottom(), m_draw(), MapVote_Draw(), MapVote_DrawMapItem(), MapVote_Init(), MapVote_InputEvent(), ModalController_draw(), ListBox::mousePress(), Slider::mousePress(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), Nexposee_draw(), nJoinAllowed(), OnlineBanList_URI_Get_Callback(), pathlib_h_diagonal2(), PingPLReport_Think(), PlayerPostThink(), PM_AirAccelerate(), PM_dodging(), PM_jetpack(), Portal_WillHitPlane(), QuickMenu_Mouse(), race_send_rankings_cnt(), RadiusDamageForSource(), rgb_to_hsl(), rgb_to_hsv(), Scoreboard_AccuracyStats_Draw(), Scoreboard_Draw(), Scoreboard_GetField(), Scoreboard_Rankings_Draw(), sys_phys_simulate(), sys_phys_simulate_simple(), sys_phys_update(), target_invasion_roundend_use(), trace_hits_box_1d(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), trigger_push_test(), turret_draw2d(), updateConwidths(), vec_to_min(), vehicles_impact(), vehicles_locktarget(), vehicles_regen(), vehicles_regen_resource(), vehicles_setreturn(), vlen_minnorm2d(), W_ReloadedAndReady(), W_ThrowNewWeapon(), WantEventchase(), WarpZone_FixNearClip(), WarpZone_FixView(), weapon_prepareattack_do(), XonoticCampaignList_loadCvars(), and XonoticCampaignList_setSelected().
float mod (float val, float m)
Referenced by crosshairpicker_crosshairToCell(), XonoticCampaignList_campaignGo(), XonoticMapInfoDialog_fill(), XonoticPicker_draw(), XonoticPicker_moveFocus(), XonoticPlayerModelSelector_go(), XonoticProfileTab_draw(), and XonoticProfileTab_fill().
entity nextent (entity e)
Referenced by EliminatedPlayers_SendEntity(), GameCommand_animbench(), GameCommand_gettaginfo(), GameCommand_trace(), Nagger_SendEntity(), and STATIC_INIT_EARLY().
vector normalize (vector v)
Referenced by aim_vec(), angleofs3(), bot_aimdir(), buildpath_nodefilter_directional(), CheatCommand(), checkpoint_passed(), CheckWaterJump(), CPM_PM_Aircontrol(), crosshair_trace(), CSQC_Demo_Camera(), ctf_CalculatePassVelocity(), ctf_CaptureShield_Touch(), ctf_CheckPassDirection(), Damage(), dist_point_line(), draw_teamradar_link(), draw_teamradar_player(), findperpendicular(), findtrajectorywithleading(), fireBullet(), FireRailgunBullet(), GameCommand_trace(), GrapplingHookThink(), havocbot_dodge(), havocbot_movetogoal(), Monster_Attack_Melee(), Monster_CalculateVelocity(), Monster_ValidTarget(), movement_oddity(), MUTATOR_HOOKFUNCTION(), ok_DropItem(), ons_CaptureShield_Touch(), pathlib_h_diagonal2sdp(), pathlib_walknode(), PM_AirAccelerate(), PM_check_punch(), PM_jetpack(), Portal_TeleportPlayer(), RadiusDamageForSource(), solve_shotdirection(), steerlib_arrive(), steerlib_attract(), steerlib_attract2(), steerlib_beamsteer(), steerlib_repell(), steerlib_standoff(), steerlib_traceavoid_flat(), steerlib_wander(), SUB_NoImpactCheck(), sys_phys_simulate(), tracewalk(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), trigger_push_calculatevelocity(), trigger_push_test(), vehicle_aimturret(), vehicles_damage(), vehicles_findgoodexit(), vehicles_force_fromtag_hover(), vehicles_force_fromtag_maglev(), vehicles_touch(), viewloc_PlayerPhysics(), W_CalculateProjectileVelocity(), W_CalculateSpread(), W_Nexball_Think(), W_Nexball_Touch(), W_SetupProjVelocity_Explicit(), W_SetupShot_Dir_ProjectileSize_Range(), WarpZone_crosshair_trace(), and WarpZone_TraceBox_ThroughZone().
void objerror (string err, ...)
Referenced by assault_setenemytoobjective(), dom_controlpoint_setup(), door_fire(), info_autoscreenshot_findtarget(), ons_DelayedLinkSetup(), plat_spawn_inside_trigger(), plat_use(), relocate_spawnpoint(), set_platmovetype(), spawnfunc(), SUB_CalcAngleMove(), SUB_CalcMove(), SUB_CalcMove_Bezier(), teleport_findtarget(), train_next(), trigger_impulse_touch_directional(), and trigger_push_test().
void parseentitydata (entity ent, string data)
float pow (float a, float b)
Referenced by cbrt(), exp(), exp2(), frexp(), ldexp(), and scalbn().
string precache_file (string file)
string precache_pic (string name, ...)
Referenced by CSQC_Init(), draw_PreloadPicture(), draw_PreloadPictureWithFlags(), GameTypeVote_ReadOption(), HUD_Chat(), HUD_Main(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), m_init_delayed(), minigame_texture(), SpecialCommand(), and Vehicles_drawHUD().
string precache_sound (string sample)
Referenced by bot_cmd_sound(), bot_queuecommand(), Create_Notification_Entity_Annce(), MUTATOR_HOOKFUNCTION(), precache(), PrecacheGlobalSound(), sandbox_Database_Load(), Sound::sound_precache(), and spawnfunc().
void print (string text, ...)
Referenced by _dumptree_close(), _dumptree_open(), CSQC_Parse_Print(), dedicated_print(), isnt_bool(), isnt_int(), json_dump(), Local_Notification(), MX_Handle(), print_to(), TEST(), and url_fputs().
float random (void)
Referenced by anticheat_endframe(), anticheat_startframe(), bot_aimdir(), bot_clientconnect(), bot_lagfunc(), bot_think(), ClientConnect(), cpicon_damage(), CSQCModel_CheckUpdate(), DistributeEvenly_GetRandomized(), MenuItem::draw(), drawBackground(), Freeze(), GameCommand_cointoss(), GameCommand_trace(), generator_draw(), GenericCommand(), GenericCommand_rpn(), gsl_ran_gaussian(), havocbot_ctf_reset_role(), havocbot_goalrating_waypoints(), havocbot_keyboard_movement(), havocbot_movetogoal(), havocbot_role_ctf_defense(), havocbot_role_ctf_escort(), havocbot_role_ft_freeing(), havocbot_role_ft_offense(), havocbot_role_kh_defense(), havocbot_role_kh_freelancer(), havocbot_role_kh_offense(), HUD_CenterPrint(), InstantAction_LoadMap(), kh_Key_DropAll(), kh_Key_Spawn(), kh_StartRound(), MapInfo_Get_ByName_NoFallbacks(), MaplistMethod_Random(), MaplistMethod_Shuffle(), MapVote_Init(), MapVote_Suggest(), MDL_GIB_ROBO_RANDOM(), Monster_Anim(), Monster_Miniboss_Check(), Monster_Move(), Monster_Move_Target(), Monster_Sound(), Monster_Spawn_Setup(), MoveToRandomLocationWithinBounds(), MUTATOR_HOOKFUNCTION(), navigation_poptouchedgoals(), Noise_Brown(), Noise_Burst(), Noise_Pink(), Noise_White(), ons_ControlPoint_Icon_BuildThink(), ons_ControlPoint_Icon_Damage(), ons_generator_ray_spawn(), ons_GeneratorDamage(), ons_Teleport(), player_anim(), PlayerDamage(), PM_check_hitground(), PM_check_nickspam(), PM_Footsteps(), preMenuInit(), RadiusDamageForSource(), randombit(), RandomItems_ReplaceMapItem(), randompos(), RandomSeed_Think(), RandomSelection_Add(), relocate_spawnpoint(), respawn(), sandbox_ObjectFunction_Touch(), SelectSpawnPoint(), shuffle(), SND_GRENADE_BOUNCE_RANDOM(), SND_HAGEXP_RANDOM(), SND_NEXWHOOSH_RANDOM(), SND_RIC_RANDOM(), spawnfunc(), SpecialCommand(), turret_die(), turret_draw(), updateCheck(), vehicle_initialize(), vehicle_tossgib(), vehicles_painframe(), W_AttachToShotorg(), W_CalculateSpread(), and XonoticColorButton_loadCvars().
vector randomvec (void)
Referenced by bot_aimdir(), buff_Respawn(), buffs_DelayedInit(), cpicon_damage(), crosshair_getcolor(), CSQC_UpdateView(), fireBullet(), GameCommand_trace(), Monster_Dead(), monster_dropitem(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ons_ControlPoint_Icon_BuildThink(), ons_generator_ray_spawn(), RandomItems_SpawnLootItem(), respawn(), SpawnThrownWeapon(), SpecialCommand(), steerlib_wander(), turret_die(), turret_draw(), turret_gibboom(), vehicles_findgoodexit(), vehicles_gib_explode(), vehicles_painframe(), and W_CalculateSpread().
void refreshhostcache (...)
Referenced by XonoticServerList_refreshServerList().
float registercvar (string name, string value, float flags)
Referenced by CampaignSaveCvar(), CSQC_Init(), GenericCommand_rpn(), and XonoticCampaignList_loadCvars().
void remove (entity e)
void resethostcachemasks (void)
Referenced by XonoticServerList_refreshServerList().
void resorthostcache (void)
Referenced by XonoticServerList_refreshServerList().
float rint (float f)
Referenced by accuracy_byte(), AnglesTransform_Normalize(), compressShotOrigin(), DamageText::DamageText_update(), DumpStats(), fpscounter_update(), fsnap(), GameCommand_trace(), Invasion_RoundStart(), Monster_Move_Target(), Monster_Spawn_Setup(), MUTATOR_HOOKFUNCTION(), nearbyint(), ons_ControlPoint_Touch(), pathlib_walknode(), remainder(), remquo(), SendAuxiliaryXhair(), SND_GRENADE_BOUNCE_RANDOM(), SND_HAGEXP_RANDOM(), SND_NEXWHOOSH_RANDOM(), SND_RIC_RANDOM(), updateConwidths(), vsnap(), and XonoticResolutionSlider_addResolution().
float search_begin (string pattern, float caseinsensitive, float quiet)
Referenced by getDemos_for_ext(), getHUDSkinFiles(), getScreenshots_for_ext(), m_init_delayed(), MapInfo_Enumerate(), Monster_Sounds_Precache(), precache_all_playermodels(), precache_playermodel(), XonoticCampaignList_configureXonoticCampaignList(), XonoticPlayerModelSelector_loadModels(), XonoticSkinList_getSkins(), and XonoticSoundList_getSounds().
void search_end (float handle)
Referenced by getDemos_for_ext(), getHUDSkinFiles(), getScreenshots_for_ext(), m_init_delayed(), MapInfo_Enumerate(), MapInfo_Shutdown(), Monster_Sounds_Precache(), precache_all_playermodels(), precache_playermodel(), XonoticCampaignList_destroy(), XonoticPlayerModelSelector_loadModels(), XonoticSkinList_getSkins(), XonoticSoundList_destroy(), and XonoticSoundList_getSounds().
string search_getfilename (float handle, float num)
Referenced by _MapInfo_GlobItem(), getDemos_for_ext(), getHUDSkinFiles(), getScreenshots_for_ext(), m_init_delayed(), Monster_Sounds_Precache(), precache_all_playermodels(), precache_playermodel(), XonoticCampaignList_campaignGo(), XonoticPlayerModelSelector_loadModels(), XonoticSkinList_getSkins(), and XonoticSoundList_soundName().
float search_getsize (float handle)
Referenced by getDemos_for_ext(), getHUDSkinFiles(), getScreenshots_for_ext(), m_init_delayed(), MapInfo_Enumerate(), Monster_Sounds_Precache(), precache_all_playermodels(), precache_playermodel(), XonoticCampaignList_campaignGo(), XonoticPlayerModelSelector_loadModels(), XonoticSkinList_getSkins(), and XonoticSoundList_getSounds().
void sethostcachemasknumber (float mask, float fld, float num, float op)
Referenced by XonoticServerList_refreshServerList().
void sethostcachemaskstring (float mask, float fld, string str, float op)
Referenced by XonoticServerList_refreshServerList().
void sethostcachesort (float fld, float slsf)
Referenced by XonoticServerList_refreshServerList().
void setkeydest (float dest)
Referenced by m_display(), m_draw(), and m_hide().
void setmousetarget (float trg)
Referenced by m_display(), and m_hide().
float sin (float f)
Referenced by bobmodel_ofs(), buff_Customize(), colormapPaletteColor_(), CSQC_Demo_Camera(), CSQC_UpdateView(), decompressShortVector(), DrawCircleClippedPic(), GenericCommand_rpn(), gsl_ran_gaussian(), HUD_Crosshair(), HUD_Get_Num_Color(), HUD_Mod_KH(), lgamma(), ons_camSetup(), ons_Teleport(), preMenuDraw(), Rotate(), Vehicles_drawHUD(), and W_CalculateSpread().
entity spawn (void)
Referenced by addPowerupItem(), buffs_BuffModel_Spawn(), buffs_DelayedInit(), CheatCommand(), CheatImpulse(), CL_Weapon_GetShotOrg(), ClientKill_Silent(), ClientKill_TeamChange(), CommonCommand_editmob(), CommonCommand_timeout(), cpicon_construct(), CSQCPlayer_ModelAppearance_Apply(), dom_spawnpoint(), EliminatedPlayers_Init(), GameCommand_animbench(), GameCommand_gettaginfo(), GameTypeVote_DrawGameTypeItem(), gettaginfo_relative(), HUD_MinigameMenu_SpawnEntry(), Item_Create(), Item_CreateLoot(), kh_Initialize(), kh_Key_Spawn(), MapVote_CheckPK3(), MapVote_Spawn(), Monster_Delay(), monster_dropitem(), msle_spawn(), MUTATOR_HOOKFUNCTION(), NET_HANDLE(), ok_DropItem(), path_build(), pathlib_astar(), pathlib_mknode(), pathlib_walknode(), pathlib_waypointpath(), pathlib_waypointpath_autostep(), plat_spawn_inside_trigger(), PlayerTouchExplode(), RandomItems_ReplaceMapItem(), RandomItems_SpawnLootItem(), readplayerstartcvars(), spawnfunc(), STATIC_INIT(), swamp_touch(), TeamBalance_CheckAllowedTeams(), teleport_findtarget(), trigger_push_test(), turret_construct(), vehicle_addplayerslot(), vehicle_tossgib(), vehicles_damage(), vehicles_projectile(), vehicles_showwp(), W_AttachToShotorg(), W_ThrowNewWeapon(), WarpZone_PostInitialize_Callback(), WarpZone_RefSys_SpawnSameRefSys(), and weapon_defaultspawnfunc().
void sprint (float clientnum, string text, ...)
Referenced by Ban_KickBanClient(), Ban_MaybeEnforceBan(), bd_activate_editor(), bd_close_editor(), bd_do_fill(), CheatCommand(), CheatImpulse(), client_hasweapon(), ClientCommand_autoswitch(), ClientCommand_clientversion(), ClientCommand_join(), ClientCommand_kill(), ClientCommand_minigame(), ClientCommand_mv_getpicture(), ClientCommand_physics(), ClientCommand_ready(), ClientCommand_say(), ClientCommand_say_team(), ClientCommand_selectteam(), ClientCommand_selfstuff(), ClientCommand_sentcvar(), ClientCommand_spectate(), ClientCommand_suggestmap(), ClientCommand_tell(), ClientCommand_voice(), ClientCommand_wpeditor(), GameCommand_adminmsg(), IMPULSE(), MUTATOR_HOOKFUNCTION(), print_to(), PrintToChat(), PrintToChatTeam(), PutPlayerInServer(), Say(), superspec_msg(), SV_ParseClientCommand(), W_Reload(), waypoint_getSymmetricalAxis_cmd(), and waypoint_getSymmetricalOrigin_cmd().
float sqrt (float f)
Referenced by _Movetype_FlyMove(), acosh(), asinh(), bot_aim(), CPM_PM_Aircontrol(), CSQC_Demo_Camera(), erf(), gsl_ran_gaussian(), HUD_CenterPrint(), HUD_GetRowCount(), HUD_GetTableSize_BestItemAR(), HUD_Physics(), hypot(), MUTATOR_HOOKFUNCTION(), nan(), Noise_Brown(), PM_Accelerate(), PM_dodging_checkpressedkeys(), PM_jetpack(), Projectile_DrawTrail(), RadiusDamageForSource(), solve_cubic_pq(), solve_quadratic(), sys_phys_simulate(), trigger_push_calculatevelocity(), turret_draw2d(), W_CalculateSpread(), and waypoint_gettravelcost().
void stackdump (void)
float stof (string val, ...)
Referenced by _getcommandkey(), _json_parse_int(), _MapInfo_FilterList_cmp(), _MapInfo_Generate(), Accuracy_LoadLevels(), Ban_LoadBans(), BanCommand_unban(), bd_do_fill(), bd_do_move(), bot_cmd_aim(), bot_cmd_aimtarget(), bot_cmd_eval(), bot_cmd_sound(), bot_custom_weapon_priority_setup(), bot_decodecommand(), CampaignFile_Load(), CheatCommand(), CheckCategoryForEntry(), ClientCommand_clientversion(), ClientCommand_mv_getpicture(), Cmd_MapVote_MapDownload(), CommonCommand_editmob(), crosshairpicker_crosshairToCell(), ctf_Initialize(), cvar_campaignwrapper(), cvar_normal(), cvar_or(), doBGMScript(), expr_evaluate(), FixPlayermodel(), fixPriorityList(), GameCommand_adminmsg(), GameCommand_animbench(), GameCommand_bot_cmd(), GameCommand_delrec(), GameCommand_gettaginfo(), GameCommand_trace(), GameCommand_warp(), GENERIC_COMMAND(), GenericCommand_qc_curl(), GenericCommand_rpn(), get_model_parameters(), GetCvars_handleFloat(), GetCvars_handleFloatOnce(), GetFilteredEntity(), GetIndexedEntity(), getladder(), getwelcomemessage(), GlobalSound_sample(), HUD_Main(), HUD_Minigame_InputEvent(), HUD_Mod_Race(), HUD_Panel_InputEvent(), HUD_QuickMenu(), HUD_Radar_InputEvent(), InputBox_draw(), InterpretBoolean(), KeyBinder_Bind_Clear(), LocalCommand_blurtest(), MapInfo_Cache_Retrieve(), MapInfo_Cache_Store(), MapInfo_FilterList_Lookup(), minigame_tile_number(), MUTATOR_HOOKFUNCTION(), MX_Handle(), MX_Messages_(), MX_Sync_(), OnlineBanList_URI_Get_Callback(), PlayerJump(), PrecacheGlobalSound(), Process_Notif_Args(), QuickMenu_InputEvent(), QuickMenu_Page_Load(), race_readTime(), replace_bind(), rpn_getf(), rpn_popf(), sandbox_ObjectPort_Load(), set_platmovetype(), spawnfunc(), trigger_race_checkpoint_verify(), vercmp_recursive(), VoteCommand_checkargs(), W_GetCycleWeapon(), W_NameWeaponOrder_MapFunc(), W_NumberWeaponOrder_MapFunc(), waypoint_load_links(), waypoint_loadall(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_keyGrabbed(), XonoticMapList_g_maplistCacheQuery(), XonoticMutatorsDialog_toString(), XonoticPlayerList_drawListBoxItem(), XonoticPlayerModelSelector_go(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_saveCvars(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), XonoticStatsList_convertDate(), XonoticStatsList_getStats(), XonoticWeaponsList_drawListBoxItem(), and XonoticWeaponsList_toString().
vector stov (string s)
Referenced by _MapInfo_Generate(), Accuracy_LoadColors(), bot_decodecommand(), CheatCommand(), crosshair_getcolor(), CSQC_UpdateView(), GameCommand_trace(), GENERIC_COMMAND(), HUD_Crosshair(), HUD_GetFontsize(), HUD_Main(), HUD_mouse_over(), HUD_Panel_LoadCvars(), LoadMenuSkinValues(), LocalCommand_boxparticles(), MUTATOR_HOOKFUNCTION(), sandbox_ObjectPort_Load(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), WeaponStats_LogItem(), WeaponStats_ready(), XonoticColorpickerString_loadCvars(), and XonoticCrosshairPreview_draw().
const string str_cvar (string name)
string strcat (string s1, string s2, ...)
Referenced by _dumptree_open(), _getcommandkey(), _json_parse_array(), _json_parse_float(), _json_parse_int(), _json_parse_pair(), _json_parse_string(), _MapInfo_Generate(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), _Sound_fixpath(), ACCUMULATE_call(), Accuracy_LoadColors(), anticheat_display(), anticheat_register_to_playerstats(), anticheat_report_to_eventlog(), anticheat_report_to_playerstats(), AppendItemcodes(), AuditLists(), Ban_Enforce(), Ban_GetClientIP(), Ban_KickBanClient(), Ban_SaveBans(), Ban_View(), bd_load_level(), bd_save_controller_piece(), bd_save_level(), bd_save_piece(), BGMScript_Init(), BGMScript_InitEntity(), bot_cmdhelp(), bot_execute_commands_once(), bot_getplace(), botframe_showwaypointlinks(), buf_save(), buff_Available(), BUFF_NAME(), Button_draw(), Campaign_Invalid(), CampaignFile_Load(), CampaignPreInit(), CampaignPreIntermission(), CampaignSaveCvar(), CheatCommand(), CheckBox_toString(), CL_ExteriorWeaponentity_Think(), ClientCommand_autoswitch(), ClientCommand_minigame(), ClientCommand_physics(), ClientCommand_sentcvar(), ClientCommand_suggestmap(), ClientCommand_tell(), ClientConnect(), ClientDisconnect(), Cmd_MapVote_MapDownload(), Cmd_Scoreboard_SetFields(), CommonCommand_cvar_changes(), CommonCommand_cvar_purechanges(), CommonCommand_editmob(), CommonCommand_info(), CommonCommand_ladder(), CommonCommand_lsmaps(), CommonCommand_printmaplist(), CommonCommand_rankings(), CommonCommand_records(), CommonCommand_teamstatus(), CommonCommand_time(), CommonCommand_timein(), CommonCommand_timeout(), CommonCommand_who(), cons(), cons_mid(), CSQC_Init(), CSQC_UpdateView(), CSQCPlayer_LOD_Apply(), ctf_CaptureRecord(), ctf_Initialize(), cts_EventLog(), cvar_changes_init(), cvar_set_campaignwrapper(), cvar_string_campaignwrapper(), cvar_string_normal(), CvarList_Revert_Click(), CvarList_Value_Change(), DamageText::DamageText_update(), db_dump(), db_save(), DemoList_Filter_Change(), EffectInfo::describe(), dialog_hudpanel_main_checkbox(), dialog_hudpanel_main_settings(), Gametype::display(), dom_EventLog(), draw_cursor(), draw_teamradar_icon(), draw_UseSkinFor(), drawBackground(), DrawDomItem(), DumpStats(), end_minigame(), FixPlayermodel(), fixPriorityList(), formatmessage(), fstrunzone(), GameCommand(), GameCommand_adminmsg(), GameCommand_allspec(), GameCommand_bot_cmd(), GameCommand_cointoss(), GameCommand_defer_clear_all(), GameCommand_gettaginfo(), GameCommand_moveplayer(), GameCommand_nospectators(), GameCommand_stuffto(), GameLogEcho(), GameType_GetIcon(), GameTypeVote_AvailabilityStatus(), GameTypeVote_ReadOption(), GameTypeVote_SendOption(), GameTypeVote_Type_FromString(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_maplist(), GenericCommand_markup(), GenericCommand_rpn(), get_model_datafilename(), get_model_parameters(), get_monster_model_datafilename(), getAllHUDSkins(), GetClientErrorString_color(), GetClientVersionMessage(), GetCvars_handleFloat(), GetCvars_handleFloatOnce(), GetCvars_handleString(), getDemos_for_ext(), getHUDSkinFiles(), getladder(), GetPlayerScoreString(), getrankings(), GetScoreLogLabel(), getScreenshots_for_ext(), GetTeamScoreString(), gettooltip(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), HUD_CenterPrint(), HUD_Chat(), HUD_Crosshair(), HUD_InfoMessages(), HUD_Main(), HUD_Minigame_InputEvent(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_Mod_Race(), HUD_mouse_over(), HUD_Panel_DrawHighlight(), HUD_Panel_DrawProgressBar(), HUD_Panel_ExportCfg(), HUD_Panel_FirstInDrawQ(), HUD_Panel_InputEvent(), HUD_Panel_LoadCvars(), HUD_Panel_SetPos(), HUD_Panel_SetPosSize(), HUD_Physics(), HUD_Quickmenu_DrawEntry(), HUD_Radar(), HUD_Radar_InputEvent(), HUD_Score(), HUD_Weapons(), HUDSkinList_Filter_Change(), InitializeEntitiesRun(), InputBox_draw(), InputBox_enterText(), InputBox_keyDown(), invite_minigame(), isGametypeInFilter(), Item_Model(), Item_Sound(), json_parse(), ka_EventLog(), KeyBinder_Bind_Edit(), kh_Scores_Event(), kh_WinnerTeam(), Label_getInfo(), language_filename(), ListBox_draw(), LoadMenuSkinValues(), LoadPlayerSounds(), Local_Notification_sprintf(), LocalCommand_create_scrshot_ent(), LocalCommand_handlevote(), LogDeath(), m_init_delayed(), M_Model(), MakeRaceString(), Map_Filename(), Map_MarkAsRecent(), MapHasRightSize(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapInfo_LoadMap(), MapList_Add_All(), MaplistMethod_Shuffle(), mapPriorityList(), MapVote_AddVotable(), MapVote_CheckPK3(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_FormatMapItem(), MapVote_InputEvent(), MapVote_ReadOption(), MapVote_SendChoice(), MapVote_SendPicture(), MapVote_Suggest(), markdown(), minigame_addplayer(), minigame_cmd_workaround(), minigame_getWrappedLine(), minigame_rmplayer(), minigame_tile_buildname(), mmsss(), mmssss(), Monster_Sound_Precache(), Monster_Sounds_Load(), Monster_Sounds_Precache(), MUTATOR_HOOKFUNCTION(), MX_Handle(), MX_Messages_(), MX_Sync(), MX_Sync_(), nmm_tile_build_hmill(), nmm_tile_build_vmill(), nt_GetReplacement(), Obituary(), OnlineBanList_SendBan(), OnlineBanList_SendUnban(), OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), playername(), PlayerPreThink(), PlayerScore_Add(), PlayerScore_PlayerStats(), PlayerScore_TeamStats(), prandom(), precache_playermodel(), PrecachePlayerSounds(), preMenuDraw(), PreviewExists(), print_to(), PrintToChat(), PrintToChatAll(), PrintToChatTeam(), Process_Notif_Line(), process_time(), PutPlayerInServer(), queue_to_execute_next_frame(), QuickMenu_ActionForNumber(), QuickMenu_Open(), race_deleteTime(), race_EventLog(), race_readName(), race_readTime(), race_readUID(), race_writeTime(), readlevelcvars(), readplayerstartcvars(), RedirectionThink(), RestoreGame(), rewrapCampaign(), rgb_to_hexcolor(), sandbox_Database_Load(), sandbox_Database_Save(), sandbox_ObjectFunction_Touch(), Say(), Score_NicePrint_Player(), Score_NicePrint_Spectator(), Score_NicePrint_Team(), Scoreboard_Draw(), Scoreboard_GetField(), ScoreInfo_SetLabel_PlayerScore(), ScoreInfo_SetLabel_TeamScore(), ScreenshotList_Filter_Change(), ServerList_TypeSort_Click(), Shutdown(), Slider_draw(), spawnfunc(), start_minigame(), STATIC_INIT(), superspec_msg(), SV_ParseClientCommand(), swapInPriorityList(), swapwords(), sys_phys_fixspeed(), TEST_Run(), textShortenToLength(), textShortenToWidth(), XonoticServerList::toggleFavorite(), trigger_race_checkpoint_verify(), turret_gibboom(), uid2name(), unescape(), ValidateMap(), Vehicles_drawHUD(), VoteAccept(), VoteCommand(), VoteCommand_abstain(), VoteCommand_call(), VoteCommand_checkargs(), VoteCommand_checkinlist(), VoteCommand_macro_help(), VoteCommand_master(), VoteCommand_no(), VoteCommand_parse(), VoteCommand_status(), VoteCommand_stop(), VoteCommand_yes(), VoteSpam(), VoteStop(), W_FixWeaponOrder_BuildImpulseList(), W_FixWeaponOrder_BuildImpulseList_cmp(), W_HitPlotAnalysis(), W_HitPlotOpen(), W_Model(), W_Reload(), W_Sound(), waypoint_getSymmetricalAxis_cmd(), waypoint_getSymmetricalOrigin_cmd(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), waypoint_save_links(), waypoint_saveall(), waypoint_spawn_fromeditor(), weapon_defaultspawnfunc(), WeaponStats_ready(), WinningConditionHelper(), wordwrap_buffer_put(), write_recordmarker(), xencode(), Xonotic_KeyBinds_Read(), XonoticCampaignList_campaignGo(), XonoticCampaignList_drawListBoxItem(), XonoticCampaignList_loadCvars(), XonoticColorpicker_draw(), XonoticColorpickerString_draw(), XonoticColorpickerString_loadCvars(), XonoticColorpickerString_saveCvars(), XonoticCrosshairPicker_cellDraw(), XonoticCrosshairPreview_configureXonoticCrosshairPreview(), XonoticCrosshairPreview_draw(), XonoticCvarList_updateCvarType(), XonoticGametypeList_drawListBoxItem(), XonoticHUDSkinList_drawListBoxItem(), XonoticHUDSkinList_setHUDSkin(), XonoticHUDWeaponsDialog_fill(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_editUserbind(), XonoticMapInfoDialog_loadMapInfo(), XonoticMapList_drawListBoxItem(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticPlayerModelSelector_loadModels(), XonoticPlayList_addToPlayList(), XonoticPlayList_removeSelectedFromPlayList(), XonoticResolutionSlider_addResolution(), XonoticResolutionSlider_loadCvars(), XonoticScreenshotList_goScreenshot(), XonoticScreenshotList_previewScreenshot(), XonoticScreenshotList_startScreenshot(), XonoticServerList_drawListBoxItem(), XonoticServerList_refreshServerList(), XonoticSkinList_getSkins(), XonoticSoundList_getSounds(), XonoticStatsList_getStats(), XonoticTextSlider_loadCvars(), XonoticTextSlider_saveCvars(), XonoticWeaponarenaCheckBox_saveCvars(), XonoticWeaponsList_drawListBoxItem(), and XonoticWeaponsList_toString().
string (float key, float bindmap)
string (string command, float bindmap)
string (string serveraddress)
string (float i)
string (float c, ...)
string (float ccase, float calpha, float cnum, string s, ...)
string (float chars, string s, ...)
string (string info, string key, string value, ...)
string (string info, string key)
string (float bufhandle, string glue)
string (string digest, string data, ...)
string (float fieldnum, entity ent)
string (string search, string replace, string subject)
string (string format, ...)
float stringwidth (string text, float handleColors, vector size)
Definition at line 304 of file miscfunctions.qc.
References drawfontscale, stringwidth_builtin(), and vector().
Referenced by Cmd_Scoreboard_SetFields(), Draw_ShowNames(), draw_TextWidth(), HUD_CenterPrint(), HUD_Notify(), HUD_RaceTimer(), HUD_Score_Rankings(), MapStats_DrawKeyValue(), MapVote_Draw(), MapVote_DrawAbstain(), MapVote_DrawMapItem(), MapVote_FormatMapItem(), Scoreboard_Draw(), Scoreboard_DrawHeader(), Scoreboard_DrawOthers(), Scoreboard_FixColumnWidth(), Scoreboard_initFieldSizes(), and Scoreboard_Rankings_Draw().
 {
     vector dfs = drawfontscale;
     drawfontscale = '1 1 0';
     float r = stringwidth_builtin(text, handleColors, sz);
     drawfontscale = dfs;
     return r;
 }
float strlen (string s)
Referenced by _dumptree_close(), _MapInfo_Generate(), _MapInfo_GlobItem(), ACCUMULATE_call(), Ban_SaveBans(), BGMScript_InitEntity(), bot_cmd_eval(), bot_cmd_if(), CampaignFile_Load(), cdr(), centerprint_generic(), Cmd_Scoreboard_SetFields(), CSQCPlayer_LOD_Apply(), cvar_changes_init(), cvar_string_campaignwrapper(), CvarList_Revert_Click(), DamageText::DamageText_update(), draw_UseSkinFor(), drawBackground(), find_last_color_code(), findinlist_abbrev(), FixPlayermodel(), fixPriorityList(), formatmessage(), GameCommand(), GameLogEcho(), GameTypeVote_ReadOption(), GenericCommand(), GenericCommand_maplist(), GenericCommand_markup(), GenericCommand_rpn(), Get_Notif_CvarName(), getAllHUDSkins(), getDemos_for_ext(), GetPlayerScoreString(), getScreenshots_for_ext(), GetTeamScoreString(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), InputBox_draw(), InputBox_enterText(), InputBox_keyDown(), isGametypeInFilter(), isInvisibleString(), IsServerInList(), KeyBinder_Bind_Edit(), LocalCommand_sendcvar(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapList_Add_All(), MapList_Add_Shown(), MapList_Remove_Shown(), MaplistMethod_Shuffle(), mapPriorityList(), matchacl(), minigame_getWrappedLine(), OnlineBanList_URI_Get_Callback(), PM_check_specialcommand(), Process_Notif_Line(), readplayerstartcvars(), rewrapCampaign(), saveCvarsMulti(), Say(), Score_NicePrint_Player(), ServerList_TypeSort_Click(), startsWithNocase(), SV_ParseClientCommand(), swapInPriorityList(), textLengthUpToLength(), textLengthUpToWidth(), XonoticServerList::toggleFavorite(), unescape(), unquote(), VoteCommand_checkargs(), VoteCommand_parse(), wordwrap_cb(), xdecode(), XonoticCampaignList_campaignGo(), XonoticCreditsList_drawListBoxItem(), XonoticCvarList_setSelected(), XonoticCvarList_updateCvarType(), XonoticDemoList_demoName(), XonoticInputBox_configureXonoticInputBox(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_editUserbind(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticPlayerList_drawListBoxItem(), XonoticPlayList_removeSelectedFromPlayList(), XonoticScreenshotImage_load(), XonoticScreenshotList_screenshotName(), XonoticServerList_draw(), XonoticServerList_refreshServerList(), XonoticServerList_setSelected(), XonoticSkinList_getSkins(), XonoticSoundList_soundName(), XonoticStatsList_convertDate(), XonoticStatsList_drawListBoxItem(), XonoticStatsList_getStats(), and XonoticWeaponsList_toString().
void strunzone (string s)
Referenced by Ban_Delete(), CampaignPostIntermission(), CampaignPreInit(), Cmd_Scoreboard_SetFields(), Curl_URI_Get_Callback(), cvar_set_campaignwrapper(), cvar_settemp_restore(), Destroy_Notification_Entity(), fstrunzone(), GameCommand_gametype(), GameTypeVote_SetGametype(), GameTypeVote_Start(), GENERIC_COMMAND(), HUD_Crosshair(), HUD_Notify_Push(), Map_Goto_SetStr(), MapVote_Suggest(), MUTATOR_HOOKFUNCTION(), QuickMenu_Page_Load(), unescape(), wordwrap_cb(), XonoticMapList_g_maplistCacheToggle(), and XonoticResolutionSlider_loadResolutions().
string strzone (string s)
Referenced by Ban_Insert(), Ban_LoadBans(), bd_editor_place(), bd_load_piece(), bot_getplace(), c4_move(), CampaignFile_Load(), CampaignPreInit(), CheatCommand(), CheckPlayerModel(), Cmd_Scoreboard_SetFields(), Create_Notification_Entity(), Create_Notification_Entity_Annce(), Create_Notification_Entity_InfoCenter(), CSQC_Init(), ctf_FlagSetup(), cvar_changes_init(), cvar_set_campaignwrapper(), DemoList_Filter_Change(), dialog_hudpanel_main_checkbox(), dialog_hudpanel_main_settings(), dom_spawnteam(), DoNextMapOverride(), draw_setMousePointer(), effectinfo_read(), GameCommand_gametype(), GameType_ConfigureSliders(), GameTypeVote_AddVotable(), GameTypeVote_ReadOption(), GameTypeVote_SetGametype(), GameTypeVote_Start(), GENERIC_COMMAND(), GenericCommand_qc_curl(), HUD_Crosshair(), HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickInvite(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_Notify_Push(), HUDSkinList_Filter_Change(), HUDSkinList_SavedName_Change(), InitGameplayMode(), InputBox_setText(), LoadMenuSkinValues(), Local_Notification(), m_init(), m_init_delayed(), Map_Goto_SetStr(), MapList_StringFilterBox_Change(), MapVote_AddVotable(), MapVote_Init(), MapVote_ReadOption(), MapVote_Suggest(), MUTATOR_HOOKFUNCTION(), MX_Say(), Net_MapVote_Picture(), nmm_spawn_tile(), nmm_spawn_tile_square(), PlayerPreThink(), pp_move(), pp_setup_pieces(), preMenuDraw(), ps_setup_pieces(), QuickMenu_Page_Load(), race_CheckName(), RandomItems_ReplaceMapItem(), readplayerstartcvars(), ReadString_Zoned(), rewrapCampaign(), sandbox_ObjectPort_Load(), sandbox_ObjectSpawn(), Scoreboard_Rankings_Draw(), ScreenshotList_Filter_Change(), ServerList_Filter_Change(), SetMovetypeFollow(), setZonedTooltip(), SoundList_Filter_Change(), spawnfunc(), start_minigame(), STATIC_INIT(), ttt_move(), unescape(), UpdateNotification_URI_Get_Callback(), url_multi_fopen(), url_single_fopen(), VoteCommand_call(), VoteCommand_master(), VoteCommand_parse(), wordwrap_cb(), XonoticCrosshairPreview_configureXonoticCrosshairPreview(), XonoticCvarList_updateCvarType(), XonoticHUDExitDialog_fill(), XonoticHUDWeaponsDialog_fill(), XonoticMapList_g_maplistCacheToggle(), XonoticMiscSettingsTab_fill(), XonoticMutatorsDialog_fill(), XonoticResolutionSlider_addResolution(), and XonoticServerInfoDialog_loadServerInfo().
string substring (string s, float start, float length)
Referenced by _dumptree_close(), _getcommandkey(), _MapInfo_Generate(), _MapInfo_GlobItem(), _MapInfo_Map_ApplyGametypeEx(), _MapInfo_Parse_Settemp(), ACCUMULATE_call(), animdecide_load_if_needed(), attach_sameorigin(), Ban_GetClientIP(), Ban_Insert(), BanCommand_unban(), bd_load_level(), BGMScript_InitEntity(), bot_cmd_eval(), bot_cmd_if(), bot_decodecommand(), bot_getplace(), bot_queuecommand(), bot_setnameandstuff(), CampaignFile_Load(), car(), cdr(), centerprint_generic(), charmap_cellToChar(), CheatCommand(), CheckCategoryForEntry(), CheckPlayerModel(), ClientCommand_minigame(), ClientCommand_say(), ClientCommand_say_team(), ClientCommand_selfstuff(), ClientCommand_sentcvar(), ClientCommand_tell(), ClientCommand_voice(), Cmd_Scoreboard_SetFields(), CSQCModel_AutoTagIndex_Apply(), CSQCModel_Hook_PostUpdate(), CSQCPlayer_LOD_Apply(), CTX(), cvar_string_campaignwrapper(), CvarList_Revert_Click(), CvarList_Value_Change(), DamageText::DamageText_update(), detach_sameorigin(), Drag_MayChangeAngles(), draw_UseSkinFor(), drawBackground(), expr_evaluate(), find_last_color_code(), findinlist_abbrev(), FixPlayermodel(), fixPriorityList(), formatmessage(), GameCommand(), GameCommand_bot_cmd(), GameCommand_gettaginfo(), GameLogEcho(), GENERIC_COMMAND(), GenericCommand(), GenericCommand_maplist(), GenericCommand_markup(), GenericCommand_nextframe(), GenericCommand_rpn(), get_model_parameters(), Get_Notif_CvarName(), getAllHUDSkins(), getDemos_for_ext(), GetFilteredEntity(), getHUDSkinFiles(), GetIndexedEntity(), GetPlayerScoreString(), getScreenshots_for_ext(), GetTeamScoreString(), getwelcomemessage(), getWrappedLine(), getWrappedLineLen(), HUD_QuickMenu(), InputBox_draw(), InputBox_enterText(), InputBox_keyDown(), isCaretEscaped(), isGametypeInFilter(), IsServerInList(), json_parse(), KeyBinder_Bind_Edit(), LoadMenuSkinValues(), Local_Notification(), LocalCommand_sendcvar(), NexBall::m_generate_mapinfo(), m_init_delayed(), MapInfo_Get_ByName_NoFallbacks(), MapInfo_ListAllAllowedMaps(), MapInfo_ListAllowedMaps(), MapList_Add_All(), MaplistMethod_Shuffle(), mapPriorityList(), MapVote_AddVotable(), matchacl(), minigame_getWrappedLine(), minigame_tile_letter(), minigame_tile_number(), mmsss(), mmssss(), MUTATOR_HOOKFUNCTION(), notif_arg_spree_inf(), OnlineBanList_URI_Get_Callback(), PM_check_specialcommand(), precache_playermodel(), Process_Notif_Line(), QuickMenu_Page_Load(), QuickMenu_skip_submenu(), readplayerstartcvars(), rewrapCampaign(), sandbox_Database_Load(), saveCvarsMulti(), Say(), Score_NicePrint_Player(), Score_NicePrint_Team(), ServerList_TypeSort_Click(), skipIncompleteTag(), startsWithNocase(), STATIC_INIT(), strwords(), substring_range(), swapInPriorityList(), textLengthUpToLength(), textLengthUpToWidth(), textShortenToLength(), textShortenToWidth(), XonoticServerList::toggleFavorite(), unescape(), unquote(), UpdateNotification_URI_Get_Callback(), vercmp_recursive(), VoteCommand_checkargs(), VoteCommand_extractcommand(), VoteCommand_parse(), W_FixWeaponOrder_BuildImpulseList(), waypoint_load_links(), waypoint_load_or_remove_links_hardwired(), waypoint_loadall(), wordwrap_cb(), xdecode(), xencode(), Xonotic_KeyBinds_Read(), XonoticCampaignList_campaignGo(), XonoticColorpicker_mouseDrag(), XonoticColorpickerString_loadCvars(), XonoticColorpickerString_saveCvars(), XonoticCreditsList_drawListBoxItem(), XonoticCvarList_updateCvarType(), XonoticDemoList_demoName(), XonoticKeyBinder_drawListBoxItem(), XonoticKeyBinder_editUserbind(), XonoticKeyBinder_setSelected(), XonoticMapList_g_maplistCacheQuery(), XonoticMapList_g_maplistCacheToggle(), XonoticMapList_keyDown(), XonoticMapList_refilter(), XonoticPlayerList_drawListBoxItem(), XonoticPlayerModelSelector_loadModels(), XonoticPlayList_removeSelectedFromPlayList(), XonoticScreenshotImage_load(), XonoticScreenshotList_screenshotName(), XonoticServerInfoDialog_loadServerInfo(), XonoticServerList_drawListBoxItem(), XonoticServerList_refreshServerList(), XonoticSkinList_getSkins(), XonoticSoundList_soundName(), XonoticStatsList_convertDate(), XonoticStatsList_drawListBoxItem(), XonoticStatsList_getStats(), and XonoticWeaponsList_toString().
float tokenize (string s)
Referenced by _getcommandkey(), CampaignFile_Load(), HUD_Minigame_InputEvent(), HUD_Panel_InputEvent(), HUD_Radar_InputEvent(), KeyBinder_Bind_Clear(), nmm_in_mill_string(), QuickMenu_InputEvent(), replace_bind(), XonoticKeyBinder_drawListBoxItem(), and XonoticKeyBinder_keyGrabbed().
void traceoff (void)
void traceon (void)
float validstring (string str)
vector vectoangles (vector v)
Referenced by aim_vec(), angleofs3(), bot_aimdir(), bot_cmd_aimtarget(), compressShortVector(), CSQC_Demo_Camera(), FireGrapplingHook(), havocbot_bunnyhop(), info_autoscreenshot_findtarget(), InterpolateOrigin_Note(), jumppad_push(), monster_makevectors(), Monster_Move(), navigation_shortenpath(), Projectile_Draw(), steerlib_beamsteer(), SUB_CalcMove_controller_think(), train_wait(), vehicle_aimturret(), vehicles_damage(), viewloc_PlayerPhysics(), and W_Nexball_Attack2().
vector (void)
float vectoyaw (vector v)
Referenced by CheatCommand(), and Portal_ApplyTransformToPlayerAngle().
float vlen (vector v)
Referenced by _MapInfo_Generate(), _Movetype_LinkEdict_TouchAreaGrid(), attach_sameorigin(), bobmodel_ofs(), bot_aim(), bot_aimdir(), bot_cmd_eval(), bot_shotlead(), botframe_autowaypoints_fix_from(), CheatCommand(), compressShortVector(), CPM_PM_Aircontrol(), CreatureFrame_FallDamage(), CSQC_UpdateView(), CSQCPlayer_LOD_Apply(), ctf_CalculatePassVelocity(), ctf_CheckPassDirection(), ctf_Handle_Throw(), Damage(), determine_force(), dist_point_line(), Drag_Begin(), Draw_ShowNames(), findtrajectorywithleading(), fireBullet(), FireRailgunBullet(), formatmessage(), GameCommand_trace(), GetCurrentFov(), GetOrthoviewFOV(), GrapplingHookThink(), havocbot_bunnyhop(), havocbot_checkgoaldistance(), havocbot_chooseweapon(), havocbot_ctf_calculate_middlepoint(), havocbot_dodge(), havocbot_keyboard_movement(), havocbot_movetogoal(), havocbot_role_ctf_defense(), HUD_Physics(), HUD_Radar(), InitGameplayMode(), MUTATOR_HOOKFUNCTION(), ons_Nearest_ControlPoint_2D(), pathlib_astar(), pathlib_g_euclidean(), pathlib_g_euclidean_water(), pathlib_h_diagonal2sdp(), pathlib_h_euclidean(), pathlib_makenode_adaptive(), pathlib_walknode(), pathlib_waypointpath(), pathlib_wpp_opencb(), pathlib_wpp_openncb(), PlayerDamage(), PlayerJump(), PM_Accelerate(), PM_AirAccelerate(), PM_check_punch(), PM_jetpack(), Portal_WillHitPlane(), race_GetFractionalLapCount(), RadiusDamageForSource(), sandbox_ObjectFunction_Touch(), Spawn_PreDraw(), Spawn_Score(), steerlib_arrive(), steerlib_attract(), steerlib_attract2(), steerlib_dodge(), steerlib_repell(), steerlib_standoff(), SUB_CalcAngleMove(), SUB_CalcMove(), SUB_CalcMove_Bezier(), SUB_NoImpactCheck(), sys_phys_land(), sys_phys_simulate(), sys_phys_simulate_simple(), tracewalk(), trigger_impulse_touch_radial(), trigger_push_calculatevelocity(), trigger_push_test(), TrueAimCheck(), turret_draw2d(), vehicle_altitude(), vehicles_damage(), vehicles_findgoodexit(), vehicles_impact(), W_CalculateProjectileVelocity(), W_Nexball_Think(), W_SetupProjVelocity_Explicit(), WarpZone_Fade_PreDraw(), WarpZone_FindRadius_Recurse(), WarpZone_Teleport(), WarpZone_Touch(), WarpZone_TraceToss_ThroughZone(), waypoint_gettravelcost(), and waypoint_spawn_fromeditor().
void ()
void (float keynr, float ascii)
void (float mode)
void (float bufhandle, float sortpower, float backward)
void (float bufhandle, float string_index, string str)
void (float bufhandle, string pattern, string antipattern)
string vtos (vector v)
Referenced by _Movetype_UnstickEntity(), bot_execute_commands_once(), botframe_showwaypointlinks(), CheatCommand(), compressShotOrigin(), CSQC_UpdateView(), GameCommand_gettaginfo(), GameCommand_trace(), havocbot_moveto(), havocbot_movetogoal(), MUTATOR_HOOKFUNCTION(), pathlib_expandnode_star(), pathlib_makenode_adaptive(), pathlib_walknode(), PlayerJump(), PutPlayerInServer(), relocate_spawnpoint(), Spawn_Score(), STATIC_INIT(), waypoint_load_links(), waypoint_remove_fromeditor(), waypoint_save_links(), waypoint_saveall(), waypoint_spawn_fromeditor(), waypoint_unreachable(), and WeaponStats_LogItem().
void WriteAngle (float data, float dest, float desto)
Referenced by clientcamera_send(), ons_camSetup(), vehicles_enter(), and vehicles_exit().
void WriteByte (float data, float dest, float desto)
Referenced by accuracy_send(), ClientData_Send(), ClientInit_misc(), cpicon_send(), CSQCModel_Send(), CSQCProjectile_SendEntity(), CSQCVehicleSetup(), ctf_FakeTimeLimit(), FixIntermissionClient(), GameTypeVote_SendOption(), generator_send(), GrapplingHookSend(), MapVote_SendEntity(), MapVote_SendOption(), MapVote_SendPicture(), MapVote_Tick(), MapVote_WriteMask(), minigame_SendEntity(), MUTATOR_HOOKFUNCTION(), Nagger_SendEntity(), ons_camSetup(), ons_Link_Send(), PingPLReport_Think(), PlayerScore_SendEntity(), PutClientInServer(), PutObserverInServer(), race_ClearTime(), race_ImposePenaltyTime(), race_send_rankings_cnt(), race_send_recordtime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendNextCheckpoint(), race_SendRankings(), race_SendStatus(), race_SendTime(), ScoreInfo_SendEntity(), Send_WeaponComplain(), SendAuxiliaryXhair(), SpawnEvent_Send(), SpawnPoint_Send(), SpectateSet(), TeamScore_SendEntity(), vehicles_enter(), vehicles_exit(), and WriteSpectators().
void WriteChar (float data, float dest, float desto)
Referenced by Nagger_SendEntity(), PlayerScore_SendEntity(), and TeamScore_SendEntity().
void WriteCoord (float data, float dest, float desto)
Referenced by ClientInit_misc(), CSQCProjectile_SendEntity(), ctf_FakeTimeLimit(), MapVote_SendEntity(), and race_SendNextCheckpoint().
void WriteEntity (entity data, float dest, float desto)
Referenced by PutClientInServer(), PutObserverInServer(), SpectateSet(), vehicles_enter(), and vehicles_exit().
void WriteLong (float data, float dest, float desto)
Referenced by MapVote_WriteMask(), and minigame_SendEntity().
void WriteShort (float data, float dest, float desto)
Referenced by fpscounter_update(), MapVote_WriteMask(), minigame_SendEntity(), MUTATOR_HOOKFUNCTION(), PingPLReport_Think(), PlayerScore_SendEntity(), race_ImposePenaltyTime(), race_SendRankings(), race_SendStatus(), RandomSeed_Send(), and TeamScore_SendEntity().
void WriteString (string data, float dest, float desto)
Referenced by ClientInit_misc(), GameTypeVote_SendOption(), MapVote_SendEntity(), MapVote_SendOption(), MapVote_Tick(), minigame_SendEntity(), Nagger_SendEntity(), race_ImposePenaltyTime(), race_send_speedaward(), race_send_speedaward_alltimebest(), race_SendNextCheckpoint(), race_SendRankings(), race_SendStatus(), race_SendTime(), and ScoreInfo_SendEntity().
void writetofile (float fhandle, entity ent)
Variable Documentation
float CRYPTO_IDSTATUS_EMPTY = 0
Definition at line 362 of file menudefs.qc.
float CRYPTO_IDSTATUS_OUTOFRANGE = -1
Definition at line 361 of file menudefs.qc.
float CRYPTO_IDSTATUS_SIGNED = 2
Definition at line 364 of file menudefs.qc.
float CRYPTO_IDSTATUS_UNSIGNED = 1
Definition at line 363 of file menudefs.qc.
float CS_CONNECTED = 2
Definition at line 71 of file menudefs.qc.
Referenced by m_gamestatus().
float CS_DEDICATED = 0
Definition at line 69 of file menudefs.qc.
float CS_DISCONNECTED = 1
Definition at line 70 of file menudefs.qc.
Referenced by m_draw().
float CVAR_TYPEFLAG_ENGINE = 8
Definition at line 431 of file menudefs.qc.
float CVAR_TYPEFLAG_EXISTS = 1
Definition at line 428 of file menudefs.qc.
float CVAR_TYPEFLAG_HASDESCRIPTION = 16
Definition at line 432 of file menudefs.qc.
float CVAR_TYPEFLAG_PRIVATE = 4
Definition at line 430 of file menudefs.qc.
float CVAR_TYPEFLAG_READONLY = 32
Definition at line 433 of file menudefs.qc.
float CVAR_TYPEFLAG_SAVED = 2
Definition at line 429 of file menudefs.qc.
float DRAWFLAG_2XMODULATE = 3
Definition at line 79 of file menudefs.qc.
float DRAWFLAG_ADDITIVE = 1
Definition at line 77 of file menudefs.qc.
float DRAWFLAG_MODULATE = 2
Definition at line 78 of file menudefs.qc.
float DRAWFLAG_NORMAL = 0
Definition at line 76 of file menudefs.qc.
float drawfont
Definition at line 137 of file menudefs.qc.
void end_sys_fields
Definition at line 12 of file menudefs.qc.
void end_sys_globals
Definition at line 7 of file menudefs.qc.
float ERR_BADDRAWFLAG = -2
Definition at line 98 of file menudefs.qc.
float ERR_BADFILENAME = -4
Definition at line 93 of file menudefs.qc.
float ERR_BADSCALE = -3
Definition at line 99 of file menudefs.qc.
float ERR_BADSIZE = -3
Definition at line 100 of file menudefs.qc.
float ERR_CANNOTOPEN = -1
Definition at line 90 of file menudefs.qc.
float ERR_INVALIDMODE = -3
Definition at line 92 of file menudefs.qc.
float ERR_NOTCACHED = -4
Definition at line 101 of file menudefs.qc.
float ERR_NOTENOUGHFILEHANDLES = -2
Definition at line 91 of file menudefs.qc.
float ERR_NULLSTRING = -1
Definition at line 97 of file menudefs.qc.
float FALSE = 0
Definition at line 44 of file menudefs.qc.
float false = 0
Definition at line 50 of file menudefs.qc.
float FIELD_ENTITY = 4
Definition at line 524 of file menudefs.qc.
float FIELD_FLOAT = 2
Definition at line 522 of file menudefs.qc.
float FIELD_FUNCTION = 6
Definition at line 525 of file menudefs.qc.
float FIELD_STRING = 1
Definition at line 521 of file menudefs.qc.
float FIELD_VECTOR = 3
Definition at line 523 of file menudefs.qc.
float FILE_APPEND = 1
Definition at line 37 of file menudefs.qc.
float FILE_READ = 0
Definition at line 36 of file menudefs.qc.
float FILE_WRITE = 2
Definition at line 38 of file menudefs.qc.
float FONT_CENTERPRINT = 5
Definition at line 133 of file menudefs.qc.
float FONT_CHAT = 4
Definition at line 132 of file menudefs.qc.
float FONT_CONSOLE = 1
Definition at line 129 of file menudefs.qc.
float FONT_DEFAULT = 0
Definition at line 128 of file menudefs.qc.
float FONT_INFOBAR = 6
Definition at line 134 of file menudefs.qc.
float FONT_MENU = 7
Definition at line 135 of file menudefs.qc.
float FONT_NOTIFY = 3
Definition at line 131 of file menudefs.qc.
float FONT_SBAR = 2
Definition at line 130 of file menudefs.qc.
float FONT_USER = 8
Definition at line 136 of file menudefs.qc.
float GECKO_BUTTON_DOUBLECLICK = 3
Definition at line 379 of file menudefs.qc.
float GECKO_BUTTON_DOWN = 0
Definition at line 374 of file menudefs.qc.
float GECKO_BUTTON_PRESS = 2
Definition at line 377 of file menudefs.qc.
float GECKO_BUTTON_UP = 1
Definition at line 375 of file menudefs.qc.
float KEY_GAME = 0
Definition at line 29 of file menudefs.qc.
Referenced by m_hide().
float KEY_MENU = 2
Definition at line 30 of file menudefs.qc.
Referenced by m_display(), and m_draw().
float KEY_MENU_GRABBED = 3
Definition at line 31 of file menudefs.qc.
Referenced by m_draw().
float KEY_UNKNOWN = -1
Definition at line 28 of file menudefs.qc.
float MSG_ALL = 2
Definition at line 57 of file menudefs.qc.
Referenced by MUTATOR_HOOKFUNCTION(), ons_camSetup(), race_deleteTime(), race_SendStatus(), and race_setTime().
float MSG_BROADCAST = 0
Definition at line 55 of file menudefs.qc.
Referenced by CSQCProjectile(), GrapplingHookSend(), Monster_Damage(), PingPLReport_Think(), PlayerCorpseDamage(), PlayerDamage(), send_CSQC_teamnagger(), train_wait(), and vehicles_damage().
float MSG_INIT = 3
Definition at line 58 of file menudefs.qc.
float MSG_ONE = 1
Definition at line 56 of file menudefs.qc.
Referenced by ClientInit_misc(), ClientInit_SendEntity(), CSQCVehicleSetup(), ctf_FakeTimeLimit(), FixIntermissionClient(), MapVote_SendPicture(), MapVote_Tick(), MUTATOR_HOOKFUNCTION(), ons_GeneratorThink(), PutClientInServer(), PutObserverInServer(), race_ClearTime(), race_ImposePenaltyTime(), race_SendNextCheckpoint(), race_SendStatus(), race_SendTime(), Send_WeaponComplain(), SpectateSet(), vehicles_enter(), and vehicles_exit().
float MT_CLIENT = 2
Definition at line 64 of file menudefs.qc.
Referenced by m_display(), m_draw(), and m_hide().
float MT_MENU = 1
Definition at line 63 of file menudefs.qc.
Referenced by m_display(), and m_draw().
entity null_entity
Definition at line 84 of file menudefs.qc.
float PRECACHE_PIC_FROMWAD = 1
Definition at line 414 of file menudefs.qc.
float PRECACHE_PIC_MIPMAP = 8
Definition at line 416 of file menudefs.qc.
float PRECACHE_PIC_NOTPERSISTENT = 2
Definition at line 415 of file menudefs.qc.
entity self
Definition at line 4 of file menudefs.qc.
float SLIST_HOSTCACHETOTALCOUNT = 1
Definition at line 105 of file menudefs.qc.
float SLIST_HOSTCACHEVIEWCOUNT = 0
Definition at line 104 of file menudefs.qc.
Referenced by XonoticServerList_draw(), and XonoticServerList_setSelected().
float SLIST_LEGACY_LINE1 = 1024
Definition at line 112 of file menudefs.qc.
float SLIST_LEGACY_LINE2 = 1025
Definition at line 113 of file menudefs.qc.
float SLIST_MASK_AND = 0
Definition at line 124 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_MASK_OR = 512
Definition at line 125 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_MASTERQUERYCOUNT = 2
Definition at line 106 of file menudefs.qc.
float SLIST_MASTERREPLYCOUNT = 3
Definition at line 107 of file menudefs.qc.
float SLIST_SERVERQUERYCOUNT = 4
Definition at line 108 of file menudefs.qc.
float SLIST_SERVERREPLYCOUNT = 5
Definition at line 109 of file menudefs.qc.
float SLIST_SORTDESCENDING = 7
Definition at line 111 of file menudefs.qc.
float SLIST_SORTFIELD = 6
Definition at line 110 of file menudefs.qc.
float SLIST_TEST_CONTAINS = 0
Definition at line 114 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_EQUAL = 4
Definition at line 118 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_GREATER = 5
Definition at line 119 of file menudefs.qc.
float SLIST_TEST_GREATEREQUAL = 6
Definition at line 120 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_LESS = 3
Definition at line 117 of file menudefs.qc.
float SLIST_TEST_LESSEQUAL = 2
Definition at line 116 of file menudefs.qc.
float SLIST_TEST_NOTCONTAIN = 1
Definition at line 115 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_NOTEQUAL = 7
Definition at line 121 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_NOTSTARTSWITH = 9
Definition at line 123 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLIST_TEST_STARTSWITH = 8
Definition at line 122 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLSF_CATEGORIES = 4
Definition at line 575 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLSF_DESCENDING = 1
Definition at line 573 of file menudefs.qc.
Referenced by XonoticServerList_refreshServerList().
float SLSF_FAVORITES = 2
Definition at line 574 of file menudefs.qc.
float TRUE = 1
Definition at line 43 of file menudefs.qc.
float true = 1
Definition at line 49 of file menudefs.qc.