Xonotic: server/client.qh File Reference
client.qh File Reference
#include "utils.qh"
#include <server/intermission.qh>
#include <common/replicate.qh>
#include <common/sounds/all.qh>
Classes
class Client
class Observer
class Player
class Spectator
Macros
#define GAMETYPE_DEFAULTED_SETTING(str)
#define INDEPENDENT_PLAYERS (autocvar__independent_players ? (autocvar__independent_players > 0) : independent_players)
#define IS_INDEPENDENT_PLAYER(e) ((e).solid == SOLID_TRIGGER)
#define MAKE_INDEPENDENT_PLAYER(e) (((e).solid = SOLID_TRIGGER), ((e).frags = FRAGS_PLAYER_OUT_OF_GAME))
#define SPECTATE_COPY() ACCUMULATE void SpectateCopy(entity this, entity spectatee)
#define SPECTATE_COPYFIELD(fld) SPECTATE_COPY() { this.(fld) = spectatee.(fld); }
#define UNWIND(class) MACRO_BEGIN if (this.instanceOf##class) { METHOD_REFERENCE(class, dtorimpl)(this); } MACRO_END
Functions
void calculate_player_respawn_time (entity this)
void ClientData_Touch (entity e)
void ClientInit_misc (entity this)
void ClientInit_Spawn ()
void ClientState_attach (entity this)
void FixClientCvars (entity e)
void FixPlayermodel (entity player)
int GetPlayerLimit ()
void Join (entity this)
bool joinAllowed (entity this)
int nJoinAllowed (entity this, entity ignore)
Determines whether the player is allowed to join.
void play_countdown (entity this, float finished, Sound samp)
void player_powerups_remove_all (entity this)
bool PlayerInList (entity player, string list)
void PlayerUseKey (entity this)
void PutObserverInServer (entity this, bool is_forced)
putting a client as observer in the server
void RotRegen (entity this, entity current, float limit_mod, float regenstable, float regenfactor, float regenlinear, float regenframetime, float rotstable, float rotfactor, float rotlinear, float rotframetime)
void SetSpectatee (entity this, entity spectatee)
void SetSpectatee_status (entity this, int spectatee_num)
bool Spectate (entity this, entity pl)
STATIC_INIT (g_players)
STATIC_INIT (g_initforplayer)
void (entity this, entity player) init_for_player
Variables
float alivetime
int autocvar__independent_players
bool autocvar__notarget
int autocvar_g_balance_armor_start
float autocvar_g_balance_pause_armor_rot_spawn
float autocvar_g_balance_pause_fuel_rot_spawn
float autocvar_g_balance_pause_health_regen_spawn
float autocvar_g_balance_pause_health_rot_spawn
bool autocvar_g_botclip_collisions
bool autocvar_g_forced_respawn
bool autocvar_g_fullbrightplayers
int autocvar_g_maxplayers
float autocvar_g_maxplayers_spectator_blocktime
string autocvar_g_mutatormsg
bool autocvar_g_nodepthtestplayers
float autocvar_g_player_alpha
float autocvar_g_player_brightness
float autocvar_g_player_damageforcescale = 2
bool autocvar_g_playerclip_collisions
bool autocvar_g_respawn_delay_forced
float autocvar_g_respawn_delay_large
int autocvar_g_respawn_delay_large_count
float autocvar_g_respawn_delay_max
float autocvar_g_respawn_delay_small
int autocvar_g_respawn_delay_small_count
bool autocvar_g_respawn_ghosts
float autocvar_g_respawn_ghosts_alpha = 1
float autocvar_g_respawn_ghosts_fadetime = 1.5
float autocvar_g_respawn_ghosts_speed
float autocvar_g_respawn_ghosts_time = 4.5
int autocvar_g_respawn_waves
string autocvar_g_xonoticversion
float autocvar_gameversion
float autocvar_gameversion_max
float autocvar_gameversion_min
string autocvar_hostname
int autocvar_spawn_debug
float autocvar_sv_foginterval
float autocvar_sv_maxidle
bool autocvar_sv_maxidle_alsokickspectators
int autocvar_sv_maxidle_minplayers = 2
float autocvar_sv_maxidle_playertospectator = 60
int autocvar_sv_maxidle_slots
bool autocvar_sv_maxidle_slots_countbots
string autocvar_sv_motd
int autocvar_sv_name_maxlength = 64
float autocvar_sv_player_scale
bool autocvar_sv_servermodelsonly
bool autocvar_sv_showspectators
int autocvar_sv_spectate
bool autocvar_sv_teamnagger
float blockSpectators
entity clientdata
IntrusiveList g_initforplayer
IntrusiveList g_players
bool independent_players
float jointime
bool just_joined
int killcount
const int MAX_SPECTATORS = 7
const int MIN_SPEC_TIME = 1
float motd_actived_time
float nickspamcount
float nickspamtime
float pauseregen_finished
float pauserotarmor_finished
float pauserotfuel_finished
float pauserothealth_finished
bool player_blocked
int playerid
string playermodel
string playerskin
int pressedkeys
float respawn_countdown
const int RESPAWN_DENY = BIT(2)
int respawn_flags
const int RESPAWN_FORCE = BIT(0)
const int RESPAWN_SILENT = BIT(1)
float respawn_time
float respawn_time_max
int spectatee_status
float spectatortime
float startplaytime
const int SVC_SETVIEW = 5
bool wasplayer
string weaponorder_byimpulse
bool zoomstate
Macro Definition Documentation
GAMETYPE_DEFAULTED_SETTING
#define GAMETYPE_DEFAULTED_SETTING (str)
Value:
((gametype_setting_tmp = cvar(strcat("g_", GetGametype(), "_" #str))), \
    (gametype_setting_tmp < 0) ? 0 \
    : (gametype_setting_tmp == 0 || autocvar_g_respawn_delay_forced) ? max(0, autocvar_g_##str) \
    : gametype_setting_tmp)
Definition at line 353 of file client.qh.
Referenced by calculate_player_respawn_time().
INDEPENDENT_PLAYERS
#define INDEPENDENT_PLAYERS (autocvar__independent_players ? (autocvar__independent_players > 0) : independent_players)
Definition at line 314 of file client.qh.
Referenced by PutPlayerInServer(), and ScoreRules_basics().
IS_INDEPENDENT_PLAYER
#define IS_INDEPENDENT_PLAYER (e) ((e).solid == SOLID_TRIGGER)
Definition at line 315 of file client.qh.
Referenced by accuracy_add(), buff_Inferno_CalculateTime(), buff_Touch(), calculate_player_respawn_time(), Damage(), Fire_ApplyDamage(), havocbot_ai(), havocbot_chooseenemy(), MUTATOR_HOOKFUNCTION(), PlayerPreThink(), PlayerUseKey(), Portal_Customize(), Portal_Damage(), Portal_Think(), Portal_Touch(), and target_init_use().
MAKE_INDEPENDENT_PLAYER
#define MAKE_INDEPENDENT_PLAYER (e) (((e).solid = SOLID_TRIGGER), ((e).frags = FRAGS_PLAYER_OUT_OF_GAME))
Definition at line 316 of file client.qh.
Referenced by PutPlayerInServer(), race_AbandonRaceCheck(), and race_SendTime().
SPECTATE_COPY
#define SPECTATE_COPY () ACCUMULATE void SpectateCopy(entity this, entity spectatee)
Definition at line 404 of file client.qh.
SPECTATE_COPYFIELD
#define SPECTATE_COPYFIELD (fld) SPECTATE_COPY() { this.(fld) = spectatee.(fld); }
Definition at line 405 of file client.qh.
UNWIND
#define UNWIND (class) MACRO_BEGIN if (this.instanceOf##class) { METHOD_REFERENCE(class, dtorimpl)(this); } MACRO_END
Referenced by Player::Player ::~ Player().
Function Documentation
calculate_player_respawn_time()
void calculate_player_respawn_time (entity this)
Definition at line 1304 of file client.qc.
References autocvar_g_forced_respawn, ceil(), FOREACH_CLIENT, GAMETYPE_DEFAULTED_SETTING, IS_INDEPENDENT_PLAYER, IS_PLAYER, MUTATOR_CALLHOOK, respawn_countdown, respawn_flags, RESPAWN_FORCE, respawn_time, respawn_time_max, teamplay, and time.
Referenced by PlayerDamage().
 {
     if(MUTATOR_CALLHOOK(CalculateRespawnTime, this))
         return;
     float gametype_setting_tmp;
     float sdelay_max = GAMETYPE_DEFAULTED_SETTING(respawn_delay_max);
     float sdelay_small = GAMETYPE_DEFAULTED_SETTING(respawn_delay_small);
     float sdelay_large = GAMETYPE_DEFAULTED_SETTING(respawn_delay_large);
     float sdelay_small_count = GAMETYPE_DEFAULTED_SETTING(respawn_delay_small_count);
     float sdelay_large_count = GAMETYPE_DEFAULTED_SETTING(respawn_delay_large_count);
     float waves = GAMETYPE_DEFAULTED_SETTING(respawn_waves);
     float pcount = 1;  // Include myself whether or not team is already set right and I'm a "player".
     if (teamplay)
     {
         FOREACH_CLIENT(IS_PLAYER(it) && it != this, {
             if(it.team == this.team)
                 ++pcount;
         });
         if (sdelay_small_count == 0)
             sdelay_small_count = 1;
         if (sdelay_large_count == 0)
             sdelay_large_count = 1;
     }
     else
     {
         FOREACH_CLIENT(IS_PLAYER(it) && it != this, {
             ++pcount;
         });
         if (sdelay_small_count == 0)
         {
             if (IS_INDEPENDENT_PLAYER(this))
             {
                 // Players play independently. No point in requiring enemies.
                 sdelay_small_count = 1;
             }
             else
             {
                 // Players play AGAINST each other. Enemies required.
                 sdelay_small_count = 2;
             }
         }
         if (sdelay_large_count == 0)
         {
             if (IS_INDEPENDENT_PLAYER(this))
             {
                 // Players play independently. No point in requiring enemies.
                 sdelay_large_count = 1;
             }
             else
             {
                 // Players play AGAINST each other. Enemies required.
                 sdelay_large_count = 2;
             }
         }
     }
     float sdelay;
     if (pcount <= sdelay_small_count)
         sdelay = sdelay_small;
     else if (pcount >= sdelay_large_count)
         sdelay = sdelay_large;
     else  // NOTE: this case implies sdelay_large_count > sdelay_small_count.
         sdelay = sdelay_small + (sdelay_large - sdelay_small) * (pcount - sdelay_small_count) / (sdelay_large_count - sdelay_small_count);
     if(waves)
         this.respawn_time = ceil((time + sdelay) / waves) * waves;
     else
         this.respawn_time = time + sdelay;
     if(sdelay < sdelay_max)
         this.respawn_time_max = time + sdelay_max;
     else
         this.respawn_time_max = this.respawn_time;
     if((sdelay + waves >= 5.0) && (this.respawn_time - time > 1.75))
         this.respawn_countdown = 10; // first number to count down from is 10
     else
         this.respawn_countdown = -1; // do not count down
     if(autocvar_g_forced_respawn)
         this.respawn_flags = this.respawn_flags | RESPAWN_FORCE;
 }
ClientData_Touch()
void ClientData_Touch (entity e)
Definition at line 171 of file client.qc.
References CS(), entity(), FOREACH_CLIENT, IS_REAL_CLIENT, and IS_SPEC.
Referenced by race_AbandonRaceCheck(), race_SendTime(), SetSpectatee(), SetSpectatee_status(), SetZoomState(), and SpectateSet().
 {
     entity cd = CS(e).clientdata;
     if (cd) { cd.SendFlags = 1; }
     // make it spectatable
     FOREACH_CLIENT(IS_REAL_CLIENT(it) && it != e && IS_SPEC(it) && it.enemy == e,
     {
         entity cd = CS(it).clientdata;
         if (cd) { cd.SendFlags = 1; }
     });
 }
ClientInit_misc()
void ClientInit_misc (entity this)
Definition at line 843 of file client.qc.
References autocvar_g_trueaim_minrange, autocvar_sv_foginterval, cnt, compressShotOrigin(), count, g_nexball_meter_period, hook_shotorigin, MSG_ONE, serverflags, world, WriteByte(), WriteCoord(), and WriteString().
Referenced by ClientInit_SendEntity(), and STATIC_INIT().
 {
     int channel = MSG_ONE;
     WriteHeader(channel, ENT_CLIENT_INIT);
     WriteByte(channel, g_nexball_meter_period * 32);
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[0]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[1]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[2]));
     WriteInt24_t(channel, compressShotOrigin(hook_shotorigin[3]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[0]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[1]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[2]));
     WriteInt24_t(channel, compressShotOrigin(arc_shotorigin[3]));
     if(autocvar_sv_foginterval && world.fog != "")
         WriteString(channel, world.fog);
     else
         WriteString(channel, "");
     WriteByte(channel, this.count * 255.0); // g_balance_armor_blockpercent
     WriteByte(channel, this.cnt * 255.0); // g_balance_damagepush_speedfactor
     WriteByte(channel, serverflags);
     WriteCoord(channel, autocvar_g_trueaim_minrange);
 }
ClientInit_Spawn()
void ClientInit_Spawn ()
Definition at line 882 of file client.qc.
References ClientInit_CheckUpdate(), ClientInit_SendEntity(), entity(), new_pure, and setthink.
Referenced by spawnfunc(), and STATIC_INIT().
 {
     entity e = new_pure(clientinit);
     setthink(e, ClientInit_CheckUpdate);
     Net_LinkEntity(e, false, 0, ClientInit_SendEntity);
     ClientInit_CheckUpdate(e);
 }
ClientState_attach()
void ClientState_attach (entity this)
Definition at line 46 of file state.qc.
References _cs, accuracy_free(), accuracy_init(), anticheat_init(), anticheat_report_to_eventlog(), bot_clientdisconnect(), ClientData_Attach(), ClientData_Detach(), DecodeLevelParms(), entcs_attach(), entcs_detach(), entity(), InventoryStorage_attach(), NEW, PlayerScore_Attach(), PlayerScore_Detach(), W_HitPlotClose(), and W_HitPlotOpen().
Referenced by Client::Client ::Client().
 {
     this._cs = NEW(ClientState, this);
     // TODO: fold all of these into ClientState
     DecodeLevelParms(this);
     PlayerScore_Attach(this);
     PlayerStats_PlayerBasic_CheckUpdate(this);
     ClientData_Attach(this);
     accuracy_init(this);
     entcs_attach(this);
     anticheat_init(this);
     W_HitPlotOpen(this);
     InventoryStorage_attach(this);
     StatusEffectsStorage_attach(this);
 }
FixClientCvars()
void FixClientCvars (entity e)
Definition at line 935 of file client.qc.
References autocvar_g_antilag, FixClientCvars(), MUTATOR_CALLHOOK, and stuffcmd.
Referenced by ClientConnect(), FixClientCvars(), and MapVote_Finished().
 {
     // send prediction settings to the client
     stuffcmd(e, "\nin_bindmap 0 0\n");
     if(autocvar_g_antilag == 3) // client side hitscan
         stuffcmd(e, "cl_cmd settemp cl_prydoncursor_notrace 0\n");
     if(autocvar_sv_gentle)
         stuffcmd(e, "cl_cmd settemp cl_gentle 1\n");
     stuffcmd(e, sprintf("\ncl_jumpspeedcap_min \"%s\"\n", autocvar_sv_jumpspeedcap_min));
     stuffcmd(e, sprintf("\ncl_jumpspeedcap_max \"%s\"\n", autocvar_sv_jumpspeedcap_max));
     stuffcmd(e, sprintf("\ncl_shootfromfixedorigin \"%s\"\n", autocvar_g_shootfromfixedorigin));
     MUTATOR_CALLHOOK(FixClientCvars, e);
 }
FixPlayermodel()
void FixPlayermodel (entity player)
Definition at line 412 of file client.qc.
References argv(), autocvar_sv_defaultcharacter, autocvar_sv_defaultcharacterskin, autocvar_sv_defaultplayercolors, autocvar_sv_defaultplayermodel, autocvar_sv_defaultplayermodel_blue, autocvar_sv_defaultplayermodel_pink, autocvar_sv_defaultplayermodel_red, autocvar_sv_defaultplayermodel_yellow, autocvar_sv_defaultplayerskin, autocvar_sv_defaultplayerskin_blue, autocvar_sv_defaultplayerskin_pink, autocvar_sv_defaultplayerskin_red, autocvar_sv_defaultplayerskin_yellow, CheckPlayerModel(), CS(), FixPlayermodel(), floor(), M_ARGV, model_randomizer, MUTATOR_CALLHOOK, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, oldskin, player_getspecies(), setcolor, setplayermodel(), stof(), strcat(), strlen(), strstrofs, substring(), teamplay, tokenize_console, UpdatePlayerSounds(), and vector().
Referenced by FixPlayermodel(), PlayerThink(), PutObserverInServer(), PutPlayerInServer(), and STATIC_INIT().
 {
     string defaultmodel = "";
     int defaultskin = 0;
     if(autocvar_sv_defaultcharacter)
     {
         if(teamplay)
         {
             switch(player.team)
             {
                 case NUM_TEAM_1: defaultmodel = autocvar_sv_defaultplayermodel_red; defaultskin = autocvar_sv_defaultplayerskin_red; break;
                 case NUM_TEAM_2: defaultmodel = autocvar_sv_defaultplayermodel_blue; defaultskin = autocvar_sv_defaultplayerskin_blue; break;
                 case NUM_TEAM_3: defaultmodel = autocvar_sv_defaultplayermodel_yellow; defaultskin = autocvar_sv_defaultplayerskin_yellow; break;
                 case NUM_TEAM_4: defaultmodel = autocvar_sv_defaultplayermodel_pink; defaultskin = autocvar_sv_defaultplayerskin_pink; break;
             }
         }
         if(defaultmodel == "")
         {
             defaultmodel = autocvar_sv_defaultplayermodel;
             defaultskin = autocvar_sv_defaultplayerskin;
         }
         int n = tokenize_console(defaultmodel);
         if(n > 0)
         {
             defaultmodel = argv(floor(n * CS(player).model_randomizer));
             // However, do NOT randomize if the player-selected model is in the list.
             for (int i = 0; i < n; ++i)
                 if ((argv(i) == player.playermodel && defaultskin == stof(player.playerskin)) || argv(i) == strcat(player.playermodel, ":", player.playerskin))
                     defaultmodel = argv(i);
         }
         int i = strstrofs(defaultmodel, ":", 0);
         if(i >= 0)
         {
             defaultskin = stof(substring(defaultmodel, i+1, -1));
             defaultmodel = substring(defaultmodel, 0, i);
         }
     }
     if(autocvar_sv_defaultcharacterskin && !defaultskin)
     {
         if(teamplay)
         {
             switch(player.team)
             {
                 case NUM_TEAM_1: defaultskin = autocvar_sv_defaultplayerskin_red; break;
                 case NUM_TEAM_2: defaultskin = autocvar_sv_defaultplayerskin_blue; break;
                 case NUM_TEAM_3: defaultskin = autocvar_sv_defaultplayerskin_yellow; break;
                 case NUM_TEAM_4: defaultskin = autocvar_sv_defaultplayerskin_pink; break;
             }
         }
         if(!defaultskin)
             defaultskin = autocvar_sv_defaultplayerskin;
     }
     MUTATOR_CALLHOOK(FixPlayermodel, defaultmodel, defaultskin, player);
     defaultmodel = M_ARGV(0, string);
     defaultskin = M_ARGV(1, int);
     bool chmdl = false;
     int oldskin;
     if(defaultmodel != "")
     {
         if (defaultmodel != player.model)
         {
             vector m1 = player.mins;
             vector m2 = player.maxs;
             setplayermodel (player, defaultmodel);
             setsize (player, m1, m2);
             chmdl = true;
         }
         oldskin = player.skin;
         player.skin = defaultskin;
     } else {
         if (player.playermodel != player.model || player.playermodel == "")
         {
             player.playermodel = CheckPlayerModel(player.playermodel); // this is never "", so no endless loop
             vector m1 = player.mins;
             vector m2 = player.maxs;
             setplayermodel (player, player.playermodel);
             setsize (player, m1, m2);
             chmdl = true;
         }
         if(!autocvar_sv_defaultcharacterskin)
         {
             oldskin = player.skin;
             player.skin = stof(player.playerskin);
         }
         else
         {
             oldskin = player.skin;
             player.skin = defaultskin;
         }
     }
     if(chmdl || oldskin != player.skin) // model or skin has changed
     {
         player.species = player_getspecies(player); // update species
         if(!autocvar_g_debug_globalsounds)
             UpdatePlayerSounds(player); // update skin sounds
     }
     if(!teamplay)
         if(strlen(autocvar_sv_defaultplayercolors))
             if(player.clientcolors != stof(autocvar_sv_defaultplayercolors))
                 setcolor(player, stof(autocvar_sv_defaultplayercolors));
 }
GetPlayerLimit()
int GetPlayerLimit ()
Definition at line 1977 of file client.qc.
References autocvar_g_maxplayers, g_duel, GetPlayerLimit(), M_ARGV, and MUTATOR_CALLHOOK.
Referenced by bot_fixcount(), GetPlayerLimit(), MapHasRightSize(), nJoinAllowed(), and STATIC_INIT().
 {
     if(g_duel)
         return 2; // TODO: this workaround is needed since the mutator hook from duel can't be activated before the gametype is loaded (e.g. switching modes via gametype vote screen)
     int player_limit = autocvar_g_maxplayers;
     MUTATOR_CALLHOOK(GetPlayerLimit, player_limit);
     player_limit = M_ARGV(0, int);
     return player_limit;
 }
Join()
void Join (entity this)
Definition at line 1953 of file client.qc.
References autocvar_g_balance_teams, autocvar_g_campaign, campaign_bots_may_start, IS_PLAYER, netname, NULL, PutClientInServer(), team, team_selected, TeamBalance_JoinBestTeam(), teamplay, and TRANSMUTE().
Referenced by ClientCommand_join(), ObserverOrSpectatorThink(), and PlayerPreThink().
 {
     TRANSMUTE(Player, this);
     if(!this.team_selected)
     if(autocvar_g_campaign || autocvar_g_balance_teams)
         TeamBalance_JoinBestTeam(this);
     if(autocvar_g_campaign)
         campaign_bots_may_start = true;
     Kill_Notification(NOTIF_ONE_ONLY, this, MSG_CENTER, CPID_PREVENT_JOIN);
     PutClientInServer(this);
     if(IS_PLAYER(this))
     if(teamplay && this.team != -1)
     {
     }
     else
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_JOIN_PLAY, this.netname);
     this.team_selected = false;
 }
joinAllowed()
bool joinAllowed (entity this)
Definition at line 2095 of file client.qc.
References CS(), jointime, lockteams, MIN_SPEC_TIME, MUTATOR_CALLHOOK, nJoinAllowed(), ShowTeamSelection(), teamplay, and time.
Referenced by ClientCommand_join(), ObserverOrSpectatorThink(), and PlayerPreThink().
 {
     if (CS(this).version_mismatch) return false;
     if (time < CS(this).jointime + MIN_SPEC_TIME) return false;
     if (!nJoinAllowed(this, this)) return false;
     if (teamplay && lockteams) return false;
     if (MUTATOR_CALLHOOK(ForbidSpawn, this)) return false;
     if (ShowTeamSelection(this)) return false;
     return true;
 }
nJoinAllowed()
int nJoinAllowed (entity this, entity ignore)
Determines whether the player is allowed to join.
This depends on cvar g_maxplayers, if it isn't used this function always return true, otherwise it checks whether the number of currently playing players exceeds g_maxplayers.
Returns
int number of free slots for players, 0 if none
Definition at line 1993 of file client.qc.
References autocvar_g_forced_team_otherwise, FOREACH_CLIENT, GetPlayerLimit(), INGAME, IS_PLAYER, IS_REAL_CLIENT, maxclients, min(), Player_GetForcedTeamIndex(), TEAM_FORCE_SPECTATOR, and time.
Referenced by joinAllowed(), and WinningConditionHelper().
 {
     if(!ignore)
     // this is called that way when checking if anyone may be able to join (to build qcstatus)
     // so report 0 free slots if restricted
     {
         if(autocvar_g_forced_team_otherwise == "spectate")
             return 0;
         if(autocvar_g_forced_team_otherwise == "spectator")
             return 0;
     }
     if(this && (Player_GetForcedTeamIndex(this) == TEAM_FORCE_SPECTATOR))
         return 0; // forced spectators can never join
     // TODO simplify this
     int totalClients = 0;
     int currentlyPlaying = 0;
     FOREACH_CLIENT(true, {
         if(it != ignore)
             ++totalClients;
         if(IS_REAL_CLIENT(it) && (IS_PLAYER(it) || INGAME(it)))
             ++currentlyPlaying;
     });
     int player_limit = GetPlayerLimit();
     int free_slots = 0;
     if (!player_limit)
         free_slots = maxclients - totalClients;
     else if(player_limit > 0 && currentlyPlaying < player_limit)
         free_slots = min(maxclients - totalClients, player_limit - currentlyPlaying);
     static float msg_time = 0;
     if(this && !INGAME(this) && ignore && !free_slots && time > msg_time)
     {
         Send_Notification(NOTIF_ONE_ONLY, this, MSG_CENTER, CENTER_JOIN_PREVENT);
         msg_time = time + 0.5;
     }
     return free_slots;
 }
play_countdown()
void play_countdown (entity this, float finished, Sound samp)
Definition at line 1436 of file client.qc.
References ATTEN_NORM, CH_INFO, floor(), frametime, IS_REAL_CLIENT, sound, TC, time, and VOL_BASE.
Referenced by player_powerups(), and STATIC_INIT().
 {
     TC(Sound, samp);
     if(IS_REAL_CLIENT(this))
         if(floor(finished - time - frametime) != floor(finished - time))
             if(finished - time < 6)
                 sound (this, CH_INFO, samp, VOL_BASE, ATTEN_NORM);
 }
player_powerups_remove_all()
void player_powerups_remove_all (entity this)
Definition at line 1445 of file client.qc.
References ATTEN_NORM, CH_INFO, CH_TRIGGER_SINGLE, IS_CLIENT, items, sound, time, and VOL_BASE.
Referenced by ClientDisconnect(), player_powerups(), reset_map(), and STATIC_INIT().
 {
     if (this.items & IT_SUPERWEAPON)
     {
         // don't play the poweroff sound when the game restarts or the player disconnects
         if (time > game_starttime + 1 && IS_CLIENT(this))
             sound(this, CH_INFO, SND_POWEROFF, VOL_BASE, ATTEN_NORM);
         stopsound(this, CH_TRIGGER_SINGLE); // get rid of the pickup sound
         this.items -= (this.items & IT_SUPERWEAPON);
     }
 }
PlayerInList()
bool PlayerInList (entity player, string list)
Definition at line 984 of file client.qc.
References autocvar_sv_eventlog, boolean, entity(), etof(), GameLogEcho(), IS_REAL_CLIENT, netaddress, playerid, PlayerInIDList(), and PlayerInIPList().
Referenced by Player_DetermineForcedTeam().
 {
     return boolean(PlayerInIDList(player, list) || PlayerInIPList(player, list));
 }
PlayerUseKey()
void PlayerUseKey (entity this)
Definition at line 2336 of file client.qc.
References DAMAGE_NO, entity(), IS_DEAD, IS_INDEPENDENT_PLAYER, IS_PLAYER, IS_VEHICLE, MUTATOR_CALLHOOK, NULL, origin, PlayerUseKey(), SAME_TEAM, vehicle, vehicles_enter(), vehicles_exit(), VHF_MULTISLOT, vlen2, and WarpZone_FindRadius().
Referenced by IMPULSE(), PlayerPreThink(), and PlayerUseKey().
 {
     if (!IS_PLAYER(this))
         return;
     if(this.vehicle)
     {
         if(!game_stopped)
         {
             vehicles_exit(this.vehicle, VHEF_NORMAL);
             return;
         }
     }
     else if(autocvar_g_vehicles_enter)
     {
         if(!game_stopped && !STAT(FROZEN, this) && !IS_DEAD(this) && !IS_INDEPENDENT_PLAYER(this))
         {
             entity head, closest_target = NULL;
             head = WarpZone_FindRadius(this.origin, autocvar_g_vehicles_enter_radius, true);
             while(head) // find the closest acceptable target to enter
             {
                 if(IS_VEHICLE(head) && !IS_DEAD(head) && head.takedamage != DAMAGE_NO)
                 if(!head.owner || ((head.vehicle_flags & VHF_MULTISLOT) && SAME_TEAM(head.owner, this)))
                 {
                     if(closest_target)
                     {
                         if(vlen2(this.origin - head.origin) < vlen2(this.origin - closest_target.origin))
                         { closest_target = head; }
                     }
                     else { closest_target = head; }
                 }
                 head = head.chain;
             }
             if(closest_target) { vehicles_enter(this, closest_target); return; }
         }
     }
     // a use key was pressed; call handlers
     MUTATOR_CALLHOOK(PlayerUseKey, this);
 }
PutObserverInServer()
void PutObserverInServer (entity this, bool is_forced)
putting a client as observer in the server
Definition at line 238 of file client.qc.
References accuracy_resend(), alivetime, alpha, angles, autocvar_g_balance_armor_start, autocvar_g_playerclip_collisions, AuxiliaryXhair, avelocity, bot_attack, bot_relinkplayerlist(), CHAT_NOSPECTATORS, CS(), DAMAGE_NO, damagedbycontents, damageforcescale, DEAD_NO, deadflag, death_time, DPCONTENTS_PLAYERCLIP, DPCONTENTS_SOLID, dphitcontentsmask, drag_undraggable(), drawonlytoclient, effects, entity(), etof(), fade_time, fixangle, FixPlayermodel(), FL_CLIENT, FL_NOTARGET, flags, frags, FRAGS_SPECTATOR, func_null(), g_bot_targets, g_damagedbycontents, g_monster_targets, GetResource(), IL_REMOVE(), IS_PLAYER, IS_REAL_CLIENT, iscreature, istypefrag, items, just_joined, killcount, LOG_FATAL, MAX_AXH, MAX_WEAPONSLOTS, model, monster_attack, MOVETYPE_FLY_WORLDONLY, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, nextthink, NULL, oldvelocity, origin, pain_finished, pauseregen_finished, pauserotarmor_finished, pauserothealth_finished, PlayerState_detach(), Portal_ClearAll(), punchangle, punchvector, pushltime, ReadyCount(), RemoveGrapplingHooks(), RES_HEALTH, respawn_flags, respawn_time, revival_time, scale, SelectSpawnPoint(), set_movetype(), setmodel, setorigin(), SetPlayerTeam(), SetResourceExplicit(), SetSpectatee(), SetSpectatee_status(), setthink, solid, SOLID_NOT, SVC_SETVIEW, takedamage, TEAM_CHANGE_SPECTATOR, TELEPORT_SIMPLE, teleportable, time, TRANSMUTE(), Unfreeze(), UNSET_DUCKED, vec2, vehicle, vehicles_exit(), velocity, view_ofs, viewloc, vote_called, VoteCount(), warmup_stage, weaponentities, weaponmodel, WriteByte(), and WriteEntity().
Referenced by ClientKill_Now_TeamChange(), GameCommand_allspec(), GameCommand_moveplayer(), minigame_addplayer(), ObserverOrSpectatorThink(), PlayerPostThink(), PutClientInServer(), SpectateSet(), and STATIC_INIT().
 {
     bool mutator_returnvalue = MUTATOR_CALLHOOK(MakePlayerObserver, this, is_forced);
     PlayerState_detach(this);
     if (IS_PLAYER(this))
     {
         if(GetResource(this, RES_HEALTH) >= 1)
         {
             // despawn effect
             Send_Effect(EFFECT_SPAWN_NEUTRAL, this.origin, '0 0 0', 1);
         }
         // was a player, recount votes and ready status
         if(IS_REAL_CLIENT(this))
         {
             if (vote_called) { VoteCount(false); }
             ReadyCount();
         }
         entcs_update_players(this);
     }
     entity spot = SelectSpawnPoint(this, true);
     if (!spot) LOG_FATAL("No spawnpoints for observers?!?");
     this.angles = vec2(spot.angles);
     this.fixangle = true;
     // offset it so that the spectator spawns higher off the ground, looks better this way
     setorigin(this, spot.origin + STAT(PL_VIEW_OFS, this));
     if (IS_REAL_CLIENT(this))
     {
         msg_entity = this;
         WriteByte(MSG_ONE, SVC_SETVIEW);
         WriteEntity(MSG_ONE, this);
     }
     // give the spectator some space between walls for MOVETYPE_FLY_WORLDONLY
     // so that your view doesn't go into the ceiling with MOVETYPE_FLY_WORLDONLY, previously "PL_VIEW_OFS"
     if(!autocvar_g_debug_globalsounds)
     {
         // needed for player sounds
         this.model = "";
         FixPlayermodel(this);
     }
     setmodel(this, MDL_Null);
     setsize(this, STAT(PL_CROUCH_MIN, this), STAT(PL_CROUCH_MAX, this));
     this.view_ofs = '0 0 0';
     RemoveGrapplingHooks(this);
     Portal_ClearAll(this);
     Unfreeze(this, false);
     SetSpectatee(this, NULL);
     if (this.alivetime)
     {
         if (!warmup_stage)
             PlayerStats_GameReport_Event_Player(this, PLAYERSTATS_ALIVETIME, time - this.alivetime);
         this.alivetime = 0;
     }
     if (this.vehicle) vehicles_exit(this.vehicle, VHEF_RELEASE);
     WaypointSprite_PlayerDead(this);
     if (CS(this).killcount != FRAGS_SPECTATOR && !game_stopped && CHAT_NOSPECTATORS())
         Send_Notification(NOTIF_ONE_ONLY, this, MSG_INFO, INFO_CHAT_NOSPECTATORS);
     accuracy_resend(this);
     CS(this).spectatortime = time;
     if(this.bot_attack)
         IL_REMOVE(g_bot_targets, this);
     this.bot_attack = false;
     if(this.monster_attack)
         IL_REMOVE(g_monster_targets, this);
     this.monster_attack = false;
     STAT(HUD, this) = HUD_NORMAL;
     TRANSMUTE(Observer, this);
     this.iscreature = false;
     this.teleportable = TELEPORT_SIMPLE;
     if(this.damagedbycontents)
         IL_REMOVE(g_damagedbycontents, this);
     this.damagedbycontents = false;
     SetResourceExplicit(this, RES_HEALTH, FRAGS_SPECTATOR);
     SetSpectatee_status(this, etof(this));
     this.takedamage = DAMAGE_NO;
     this.solid = SOLID_NOT;
     set_movetype(this, MOVETYPE_FLY_WORLDONLY); // user preference is controlled by playerprethink
     this.flags = FL_CLIENT | FL_NOTARGET;
     this.effects = 0;
     SetResourceExplicit(this, RES_ARMOR, autocvar_g_balance_armor_start); // was 666?!
     this.pauserotarmor_finished = 0;
     this.pauserothealth_finished = 0;
     this.pauseregen_finished = 0;
     this.damageforcescale = 0;
     this.death_time = 0;
     this.respawn_flags = 0;
     this.respawn_time = 0;
     STAT(RESPAWN_TIME, this) = 0;
     this.alpha = 0;
     this.scale = 0;
     this.fade_time = 0;
     this.pain_finished = 0;
     STAT(AIR_FINISHED, this) = 0;
     //this.dphitcontentsmask = 0;
     this.dphitcontentsmask = DPCONTENTS_SOLID;
     if (autocvar_g_playerclip_collisions)
         this.dphitcontentsmask |= DPCONTENTS_PLAYERCLIP;
     this.pushltime = 0;
     this.istypefrag = 0;
     setthink(this, func_null);
     this.nextthink = 0;
     this.deadflag = DEAD_NO;
     UNSET_DUCKED(this);
     STAT(REVIVE_PROGRESS, this) = 0;
     this.revival_time = 0;
     this.draggable = drag_undraggable;
     this.items = 0;
     STAT(WEAPONS, this) = '0 0 0';
     this.drawonlytoclient = this;
     this.viewloc = NULL;
     //this.spawnpoint_targ = NULL; // keep it so they can return to where they were?
     this.weaponmodel = "";
     for (int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
     {
         this.weaponentities[slot] = NULL;
     }
     this.exteriorweaponentity = NULL;
     CS(this).killcount = FRAGS_SPECTATOR;
     this.velocity = '0 0 0';
     this.avelocity = '0 0 0';
     this.punchangle = '0 0 0';
     this.punchvector = '0 0 0';
     this.oldvelocity = this.velocity;
     this.event_damage = func_null;
     this.event_heal = func_null;
     for(int slot = 0; slot < MAX_AXH; ++slot)
     {
         entity axh = this.(AuxiliaryXhair[slot]);
         this.(AuxiliaryXhair[slot]) = NULL;
         if(axh.owner == this && axh != NULL && !wasfreed(axh))
             delete(axh);
     }
     if (mutator_returnvalue)
     {
         // mutator prevents resetting teams+score
     }
     else
     {
         SetPlayerTeam(this, -1, TEAM_CHANGE_SPECTATOR);
         this.frags = FRAGS_SPECTATOR;
     }
     bot_relinkplayerlist();
     if (CS(this).just_joined)
         CS(this).just_joined = false;
 }
RotRegen()
void RotRegen (entity this, entity current, float limit_mod, float regenstable, float regenfactor, float regenlinear, float regenframetime, float rotstable, float rotfactor, float rotlinear, float rotframetime)
Referenced by STATIC_INIT().
SetSpectatee()
void SetSpectatee (entity this, entity spectatee)
Definition at line 1823 of file client.qc.
References ClientData_Touch(), enemy, entity(), etof(), IS_BOT_CLIENT, MAX_WEAPONSLOTS, SetSpectatee_status(), and weaponentities.
Referenced by ClientDisconnect(), PutClientInServer(), PutObserverInServer(), Spectate(), SpectateNext(), SpectatePrev(), SpectateUpdate(), and STATIC_INIT().
 {
     if(IS_BOT_CLIENT(this))
         return; // bots abuse .enemy, this code is useless to them
     entity old_spectatee = this.enemy;
     this.enemy = spectatee;
     // WEAPONTODO
     // these are required to fix the spectator bug with arc
     if(old_spectatee)
     {
         for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(old_spectatee.(weaponentity).arc_beam)
                 old_spectatee.(weaponentity).arc_beam.SendFlags |= ARC_SF_SETTINGS;
         }
     }
     if(this.enemy)
     {
         for(int slot = 0; slot < MAX_WEAPONSLOTS; ++slot)
         {
             .entity weaponentity = weaponentities[slot];
             if(this.enemy.(weaponentity).arc_beam)
                 this.enemy.(weaponentity).arc_beam.SendFlags |= ARC_SF_SETTINGS;
         }
     }
     if (this.enemy)
         SetSpectatee_status(this, etof(this.enemy));
     // needed to update spectator list
     if(old_spectatee) { ClientData_Touch(old_spectatee); }
 }
SetSpectatee_status()
void SetSpectatee_status (entity this, int spectatee_num)
Definition at line 1806 of file client.qc.
References ClientData_Touch(), CS(), g_cts, g_race, race_InitSpectator(), and spectatee_status.
Referenced by PutObserverInServer(), PutPlayerInServer(), SetSpectatee(), and STATIC_INIT().
 {
     int oldspectatee_status = CS(this).spectatee_status;
     CS(this).spectatee_status = spectatee_num;
     if (CS(this).spectatee_status != oldspectatee_status)
     {
         if (STAT(PRESSED_KEYS, this))
         {
             CS(this).pressedkeys = 0;
             STAT(PRESSED_KEYS, this) = 0;
         }
         ClientData_Touch(this);
         if (g_race || g_cts) race_InitSpectator();
     }
 }
Spectate()
bool Spectate (entity this, entity pl)
Definition at line 1860 of file client.qc.
References entity(), M_ARGV, MUTATOR_CALLHOOK, SetSpectatee(), and SpectateSet().
Referenced by ClientCommand_spectate(), STATIC_INIT(), and superspec_Spectate().
 {
     if(MUTATOR_CALLHOOK(SpectateSet, this, pl))
         return false;
     pl = M_ARGV(1, entity);
     SetSpectatee(this, pl);
     return SpectateSet(this);
 }
STATIC_INIT() [1/2]
STATIC_INIT (g_players)
Definition at line 86 of file client.qh.
References IL_NEW.
 { g_players = IL_NEW(); }
STATIC_INIT() [2/2]
STATIC_INIT (g_initforplayer)
Definition at line 375 of file client.qh.
References ClientInit_misc(), ClientInit_Spawn(), FixPlayermodel(), GetPlayerLimit(), IL_NEW, play_countdown(), player_powerups_remove_all(), PutObserverInServer(), RotRegen(), SetSpectatee(), SetSpectatee_status(), and Spectate().
 { g_initforplayer = IL_NEW(); }
void()
void (entity this, entity player)
Variable Documentation
alivetime
float alivetime
Definition at line 66 of file client.qh.
Referenced by PlayerDamage(), PutObserverInServer(), and PutPlayerInServer().
autocvar__independent_players
int autocvar__independent_players
Definition at line 312 of file client.qh.
autocvar__notarget
bool autocvar__notarget
Definition at line 9 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_balance_armor_start
int autocvar_g_balance_armor_start
Definition at line 10 of file client.qh.
Referenced by PutObserverInServer().
autocvar_g_balance_pause_armor_rot_spawn
float autocvar_g_balance_pause_armor_rot_spawn
Definition at line 11 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_balance_pause_fuel_rot_spawn
float autocvar_g_balance_pause_fuel_rot_spawn
Definition at line 12 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_balance_pause_health_regen_spawn
float autocvar_g_balance_pause_health_regen_spawn
Definition at line 13 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_balance_pause_health_rot_spawn
float autocvar_g_balance_pause_health_rot_spawn
Definition at line 14 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_botclip_collisions
bool autocvar_g_botclip_collisions
Definition at line 15 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_forced_respawn
bool autocvar_g_forced_respawn
Definition at line 42 of file client.qh.
Referenced by calculate_player_respawn_time().
autocvar_g_fullbrightplayers
bool autocvar_g_fullbrightplayers
Definition at line 16 of file client.qh.
Referenced by Monster_Spawn(), player_powerups(), vehicle_initialize(), and vehicles_reset_colors().
autocvar_g_maxplayers
int autocvar_g_maxplayers
Definition at line 43 of file client.qh.
Referenced by GetPlayerLimit().
autocvar_g_maxplayers_spectator_blocktime
float autocvar_g_maxplayers_spectator_blocktime
Definition at line 44 of file client.qh.
Referenced by ClientConnect(), ClientKill_Now_TeamChange(), GameCommand_nospectators(), and PlayerPreThink().
autocvar_g_mutatormsg
string autocvar_g_mutatormsg
Definition at line 34 of file client.qh.
Referenced by getwelcomemessage().
autocvar_g_nodepthtestplayers
bool autocvar_g_nodepthtestplayers
Definition at line 33 of file client.qh.
Referenced by Monster_Spawn(), player_powerups(), vehicle_initialize(), and vehicles_reset_colors().
autocvar_g_player_alpha
float autocvar_g_player_alpha
Definition at line 18 of file client.qh.
Referenced by SetDefaultAlpha().
autocvar_g_player_brightness
float autocvar_g_player_brightness
Definition at line 19 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_player_damageforcescale
float autocvar_g_player_damageforcescale = 2
Definition at line 20 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_g_playerclip_collisions
bool autocvar_g_playerclip_collisions
Definition at line 17 of file client.qh.
Referenced by Monster_Spawn(), PutObserverInServer(), PutPlayerInServer(), and vehicle_initialize().
autocvar_g_respawn_delay_forced
bool autocvar_g_respawn_delay_forced
Definition at line 26 of file client.qh.
autocvar_g_respawn_delay_large
float autocvar_g_respawn_delay_large
Definition at line 23 of file client.qh.
autocvar_g_respawn_delay_large_count
int autocvar_g_respawn_delay_large_count
Definition at line 24 of file client.qh.
autocvar_g_respawn_delay_max
float autocvar_g_respawn_delay_max
Definition at line 25 of file client.qh.
autocvar_g_respawn_delay_small
float autocvar_g_respawn_delay_small
Definition at line 21 of file client.qh.
autocvar_g_respawn_delay_small_count
int autocvar_g_respawn_delay_small_count
Definition at line 22 of file client.qh.
autocvar_g_respawn_ghosts
bool autocvar_g_respawn_ghosts
Definition at line 27 of file client.qh.
Referenced by respawn().
autocvar_g_respawn_ghosts_alpha
float autocvar_g_respawn_ghosts_alpha = 1
Definition at line 28 of file client.qh.
Referenced by respawn().
autocvar_g_respawn_ghosts_fadetime
float autocvar_g_respawn_ghosts_fadetime = 1.5
Definition at line 29 of file client.qh.
Referenced by respawn().
autocvar_g_respawn_ghosts_speed
float autocvar_g_respawn_ghosts_speed
Definition at line 31 of file client.qh.
Referenced by respawn().
autocvar_g_respawn_ghosts_time
float autocvar_g_respawn_ghosts_time = 4.5
Definition at line 30 of file client.qh.
Referenced by respawn().
autocvar_g_respawn_waves
int autocvar_g_respawn_waves
Definition at line 32 of file client.qh.
autocvar_g_xonoticversion
string autocvar_g_xonoticversion
Definition at line 45 of file client.qh.
Referenced by GetClientVersionMessage(), PlayerPreThink(), and WinningConditionHelper().
autocvar_gameversion
float autocvar_gameversion
Definition at line 46 of file client.qh.
Referenced by GetClientVersionMessage().
autocvar_gameversion_max
float autocvar_gameversion_max
Definition at line 48 of file client.qh.
Referenced by ClientCommand_clientversion().
autocvar_gameversion_min
float autocvar_gameversion_min
Definition at line 47 of file client.qh.
Referenced by ClientCommand_clientversion().
autocvar_hostname
string autocvar_hostname
Definition at line 49 of file client.qh.
Referenced by getwelcomemessage(), OnlineBanList_SendBan(), OnlineBanList_SendUnban(), OnlineBanList_Think(), and WeaponStats_ready().
autocvar_spawn_debug
int autocvar_spawn_debug
Definition at line 50 of file client.qh.
Referenced by _StartItem(), PutPlayerInServer(), and SelectSpawnPoint().
autocvar_sv_foginterval
float autocvar_sv_foginterval
Definition at line 35 of file client.qh.
Referenced by ClientConnect(), and ClientInit_misc().
autocvar_sv_maxidle
float autocvar_sv_maxidle
Definition at line 36 of file client.qh.
Referenced by DecodeLevelParms(), PlayerPostThink(), and sys_phys_monitor().
autocvar_sv_maxidle_alsokickspectators
bool autocvar_sv_maxidle_alsokickspectators
Definition at line 39 of file client.qh.
Referenced by PlayerPostThink().
autocvar_sv_maxidle_minplayers
int autocvar_sv_maxidle_minplayers = 2
Definition at line 37 of file client.qh.
Referenced by PlayerPostThink().
autocvar_sv_maxidle_playertospectator
float autocvar_sv_maxidle_playertospectator = 60
Definition at line 38 of file client.qh.
Referenced by PlayerPostThink(), SetPlayerTeam(), and sys_phys_monitor().
autocvar_sv_maxidle_slots
int autocvar_sv_maxidle_slots
Definition at line 40 of file client.qh.
Referenced by PlayerPostThink().
autocvar_sv_maxidle_slots_countbots
bool autocvar_sv_maxidle_slots_countbots
Definition at line 41 of file client.qh.
Referenced by PlayerPostThink().
autocvar_sv_motd
string autocvar_sv_motd
Definition at line 51 of file client.qh.
Referenced by getwelcomemessage().
autocvar_sv_name_maxlength
int autocvar_sv_name_maxlength = 64
Definition at line 52 of file client.qh.
Referenced by PlayerPreThink().
autocvar_sv_player_scale
float autocvar_sv_player_scale
Definition at line 56 of file client.qh.
Referenced by PutPlayerInServer().
autocvar_sv_servermodelsonly
bool autocvar_sv_servermodelsonly
Definition at line 53 of file client.qh.
Referenced by CheckPlayerModel().
autocvar_sv_showspectators
bool autocvar_sv_showspectators
Definition at line 57 of file client.qh.
Referenced by ClientData_Send().
autocvar_sv_spectate
int autocvar_sv_spectate
Definition at line 54 of file client.qh.
Referenced by ClientCommand_clientversion(), ClientCommand_spectate(), MUTATOR_HOOKFUNCTION(), and PlayerPreThink().
autocvar_sv_teamnagger
bool autocvar_sv_teamnagger
Definition at line 55 of file client.qh.
Referenced by ClientConnect().
blockSpectators
float blockSpectators
Definition at line 335 of file client.qh.
Referenced by ClientConnect(), ClientKill_Now_TeamChange(), GameCommand_nospectators(), and PlayerPreThink().
clientdata
entity clientdata
Definition at line 62 of file client.qh.
Referenced by ClientData_Attach().
g_initforplayer
IntrusiveList g_initforplayer
Definition at line 374 of file client.qh.
Referenced by ClientConnect().
g_players
IntrusiveList g_players
Definition at line 85 of file client.qh.
Referenced by StartFrame().
independent_players
bool independent_players
Definition at line 313 of file client.qh.
Referenced by invasion_DelayedInit(), MUTATOR_HOOKFUNCTION(), rc_SetLimits(), and REGISTER_MUTATOR().
jointime
float jointime
Definition at line 64 of file client.qh.
Referenced by ClientCommand_join(), CommonCommand_who(), DumpStats(), havocbot_ctf_reset_role(), joinAllowed(), MUTATOR_HOOKFUNCTION(), ObserverOrSpectatorThink(), and PlayerPreThink().
just_joined
bool just_joined
Definition at line 74 of file client.qh.
Referenced by PutObserverInServer(), and SetPlayerTeam().
killcount
int killcount
Definition at line 318 of file client.qh.
Referenced by Damage(), Heal(), lms_RemovePlayer(), MUTATOR_HOOKFUNCTION(), Obituary(), PutObserverInServer(), and PutPlayerInServer().
MAX_SPECTATORS
const int MAX_SPECTATORS = 7
Definition at line 407 of file client.qh.
MIN_SPEC_TIME
const int MIN_SPEC_TIME = 1
Definition at line 400 of file client.qh.
Referenced by ClientCommand_join(), joinAllowed(), ObserverOrSpectatorThink(), and PlayerPreThink().
motd_actived_time
float motd_actived_time
Definition at line 67 of file client.qh.
Referenced by PrintWelcomeMessage().
nickspamcount
float nickspamcount
Definition at line 322 of file client.qh.
Referenced by PM_check_nickspam().
nickspamtime
float nickspamtime
Definition at line 321 of file client.qh.
Referenced by PM_check_nickspam().
pauseregen_finished
float pauseregen_finished
Definition at line 343 of file client.qh.
Referenced by CheatImpulse(), GiveItems(), player_regen(), PlayerCorpseDamage(), PlayerDamage(), PM_jetpack(), PutObserverInServer(), and PutPlayerInServer().
pauserotarmor_finished
float pauserotarmor_finished
Definition at line 345 of file client.qh.
Referenced by CheatImpulse(), GiveItems(), player_regen(), PutObserverInServer(), and PutPlayerInServer().
pauserotfuel_finished
float pauserotfuel_finished
Definition at line 346 of file client.qh.
Referenced by CheatImpulse(), GiveItems(), player_regen(), and PutPlayerInServer().
pauserothealth_finished
float pauserothealth_finished
Definition at line 344 of file client.qh.
Referenced by CheatImpulse(), GiveItems(), player_regen(), PutObserverInServer(), and PutPlayerInServer().
player_blocked
bool player_blocked
Definition at line 338 of file client.qh.
Referenced by ClientKill(), PlayerJump(), and PM_check_blocked().
playerid
int playerid
Definition at line 78 of file client.qh.
Referenced by anticheat_report_to_eventlog(), ClientConnect(), ClientDisconnect(), MapVote_Suggest(), PlayerInList(), and PlayerPreThink().
playermodel
string playermodel
Definition at line 80 of file client.qh.
playerskin
string playerskin
Definition at line 81 of file client.qh.
pressedkeys
int pressedkeys
Definition at line 76 of file client.qh.
Referenced by HUD_PressedKeys(), and PM_dodging().
respawn_countdown
float respawn_countdown
Definition at line 329 of file client.qh.
Referenced by calculate_player_respawn_time(), and ShowRespawnCountdown().
RESPAWN_DENY
const int RESPAWN_DENY = BIT(2)
Definition at line 333 of file client.qh.
Referenced by PlayerThink().
respawn_flags
int respawn_flags
Definition at line 325 of file client.qh.
Referenced by calculate_player_respawn_time(), PlayerThink(), PutObserverInServer(), and PutPlayerInServer().
RESPAWN_FORCE
const int RESPAWN_FORCE = BIT(0)
Definition at line 331 of file client.qh.
Referenced by calculate_player_respawn_time(), MUTATOR_HOOKFUNCTION(), and PlayerThink().
RESPAWN_SILENT
const int RESPAWN_SILENT = BIT(1)
Definition at line 332 of file client.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and PlayerThink().
respawn_time
float respawn_time
Definition at line 326 of file client.qh.
Referenced by calculate_player_respawn_time(), PlayerDamage(), PlayerThink(), PutObserverInServer(), PutPlayerInServer(), and ShowRespawnCountdown().
respawn_time_max
float respawn_time_max
Definition at line 327 of file client.qh.
Referenced by calculate_player_respawn_time(), and PlayerThink().
spectatee_status
int spectatee_status
Definition at line 71 of file client.qh.
spectatortime
float spectatortime
Definition at line 336 of file client.qh.
Referenced by PlayerPreThink().
startplaytime
float startplaytime
Definition at line 65 of file client.qh.
SVC_SETVIEW
const int SVC_SETVIEW = 5
Definition at line 340 of file client.qh.
Referenced by PutClientInServer(), PutObserverInServer(), and SpectateSet().
wasplayer
bool wasplayer
Definition at line 69 of file client.qh.
Referenced by ClientCommand_selectteam(), Player_SetTeamIndexChecked(), and ShowTeamSelection().
weaponorder_byimpulse
string weaponorder_byimpulse
Definition at line 60 of file client.qh.
Referenced by ClientDisconnect(), W_FixWeaponOrder_ForceComplete_AndBuildImpulseList(), W_NextWeapon(), and W_PreviousWeapon().
zoomstate
bool zoomstate
Definition at line 72 of file client.qh.
Referenced by ClientData_Send(), SetZoomState(), and SpectateCopy().