Xonotic: menu/xonotic/checkbox_string.qc File Reference
checkbox_string.qc File Reference
#include "checkbox_string.qh"
Functions
entity makeXonoticCheckBoxString (string theYesValue, string theNoValue, string theCvar, string theText)
void XonoticCheckBoxString_configureXonoticCheckBoxString (entity me, string theYesValue, string theNoValue, string theCvar, string theText)
void XonoticCheckBoxString_loadCvars (entity me)
void XonoticCheckBoxString_saveCvars (entity me)
void XonoticCheckBoxString_setChecked (entity me, float foo)
Function Documentation
entity makeXonoticCheckBoxString (string theYesValue, string theNoValue, string theCvar, string theText)
Definition at line 3 of file checkbox_string.qc.
References entity(), and NEW.
Referenced by dialog_hudpanel_common_notoggle().
 {
     entity me;
     me = NEW(XonoticCheckBoxString);
     me.configureXonoticCheckBoxString(me, theYesValue, theNoValue, theCvar, theText);
     return me;
 }
void XonoticCheckBoxString_configureXonoticCheckBoxString (entity me, string theYesValue, string theNoValue, string theCvar, string theText)
Definition at line 10 of file checkbox_string.qc.
References string_null.
 {
     me.yesString = theYesValue;
     me.noString = theNoValue;
     me.checked = 0;
     me.cvarName = (theCvar) ? theCvar : string_null;
     me.loadCvars(me);
     me.configureCheckBox(me, theText, me.fontSize, me.image);
 }
void XonoticCheckBoxString_loadCvars (entity me)
Definition at line 24 of file checkbox_string.qc.
References cvar_string().
 {
     if (!me.cvarName)
         return;
     if(cvar_string(me.cvarName) == me.yesString)
         me.checked = 1;
 }
void XonoticCheckBoxString_saveCvars (entity me)
Definition at line 32 of file checkbox_string.qc.
References CheckSendCvars(), and cvar_set().
 {
     if (!me.cvarName)
         return;
     if(me.checked)
         cvar_set(me.cvarName, me.yesString);
     else
         cvar_set(me.cvarName, me.noString);
     CheckSendCvars(me, me.cvarName);
 }
void XonoticCheckBoxString_setChecked (entity me, float foo)
Definition at line 19 of file checkbox_string.qc.
 {
     me.checked = !me.checked;
     me.saveCvars(me);
 }