Xonotic: XonoticCharmap Class Reference
XonoticCharmap Class Reference
Public Member Functions
ATTRIB (XonoticCharmap, inputBox, entity)
ATTRIB (Item, parent, entity)
ATTRIB (Item, tooltip, string)
virtual void cellDraw ()
virtual void cellIsValid ()
virtual void cellSelect ()
virtual void configureXonoticCharmap ()
virtual void configureXonoticPicker ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void draw ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void hideNotify ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void moveFocus ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void showNotify ()
virtual void toString ()
Public Attributes
float allowFocusSound = 0
float alpha = 1
vector charOffset = '0 0 0'
float columns = 14
float disabled = 0
float disabledAlpha = SKINALPHA_DISABLED
float focusable = 1
float focused = 0
vector focusedCell = '-1 -1 0'
float focusedCellAlpha = 0
float focusedCellTime = 0
vector origin = '0 0 0'
float preferredFocusPriority = 0
vector pressedCell = '-1 -1 0'
vector realCellSize = '0 0 0'
vector realFontSize = '0 0 0'
float rows = 10
vector selectedCell = '-1 -1 0'
vector size = '0 0 0'
Detailed Description
Definition at line 4 of file charmap.qh.
Member Function Documentation
XonoticCharmap::ATTRIB (XonoticCharmap , inputBox , entity)
Item::ATTRIB (Item , parent , entity) inherited
Item::ATTRIB (Item , tooltip , string) inherited
virtual void XonoticCharmap::cellDraw () virtual
Reimplemented from XonoticPicker.
virtual void XonoticCharmap::cellIsValid () virtual
Reimplemented from XonoticPicker.
virtual void XonoticCharmap::cellSelect () virtual
Reimplemented from XonoticPicker.
virtual void XonoticCharmap::configureXonoticCharmap () virtual
virtual void XonoticPicker::configureXonoticPicker () virtual inherited
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 295 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
void Item::destroy () virtual inherited
Reimplemented in XonoticMapList, XonoticLanguageList, XonoticHUDSkinList, XonoticPlayerModelSelector, XonoticScreenshotList, XonoticDemoList, XonoticSkinList, XonoticCampaignList, XonoticKeyBinder, XonoticCvarList, XonoticSoundList, XonoticStatsList, and XonoticCreditsList.
Definition at line 6 of file item.qc.
     {
         // free memory associated with this
     }
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 309 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void XonoticPicker::draw () virtual inherited
Reimplemented from Item.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void XonoticCharmap::focusLeave () virtual
Reimplemented from Item.
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void XonoticCharmap::keyDown () virtual
Reimplemented from XonoticPicker.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void XonoticPicker::mouseDrag () virtual inherited
Reimplemented from Item.
virtual void XonoticPicker::mouseMove () virtual inherited
Reimplemented from Item.
virtual void XonoticPicker::mousePress () virtual inherited
Reimplemented from Item.
virtual void XonoticPicker::mouseRelease () virtual inherited
Reimplemented from Item.
virtual void XonoticPicker::moveFocus () virtual inherited
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticCharmap::resizeNotify () virtual
Reimplemented from Item.
void Item::showNotify () virtual inherited
Reimplemented in Container, Slider, XonoticHUDSkinList, XonoticScreenshotList, XonoticDemoList, InputBox, XonoticSoundList, XonoticDamageTextSettings, XonoticStatsList, XonoticPlayerModelSelector, XonoticTab, XonoticCvarList, XonoticKeyBinder, Button, XonoticMutatorsDialog, XonoticGameCrosshairSettingsTab, XonoticGameHUDSettingsTab, XonoticGameMessageSettingsTab, XonoticGameModelSettingsTab, XonoticGameViewSettingsTab, XonoticGameWeaponsSettingsTab, XonoticCvarsDialog, and XonoticTeamSelectDialog.
Definition at line 56 of file item.qc.
     {}
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
Member Data Documentation
float Item::allowFocusSound = 0 inherited
Definition at line 24 of file item.qh.
float XonoticPicker::alpha = 1 inherited
Definition at line 14 of file picker.qh.
vector XonoticCharmap::charOffset = '0 0 0'
Definition at line 18 of file charmap.qh.
float XonoticCharmap::columns = 14
Definition at line 13 of file charmap.qh.
float XonoticPicker::disabled = 0 inherited
Definition at line 13 of file picker.qh.
float XonoticPicker::disabledAlpha = SKINALPHA_DISABLED inherited
Definition at line 15 of file picker.qh.
float XonoticPicker::focusable = 1 inherited
Definition at line 12 of file picker.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
vector XonoticPicker::focusedCell = '-1 -1 0' inherited
Definition at line 26 of file picker.qh.
float XonoticPicker::focusedCellAlpha = 0 inherited
Definition at line 27 of file picker.qh.
float XonoticPicker::focusedCellTime = 0 inherited
Definition at line 28 of file picker.qh.
vector Item::origin = '0 0 0' inherited
Definition at line 27 of file item.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
vector XonoticPicker::pressedCell = '-1 -1 0' inherited
Definition at line 29 of file picker.qh.
vector XonoticPicker::realCellSize = '0 0 0' inherited
Definition at line 24 of file picker.qh.
vector XonoticCharmap::realFontSize = '0 0 0'
Definition at line 10 of file charmap.qh.
float XonoticCharmap::rows = 10
Definition at line 12 of file charmap.qh.
vector XonoticPicker::selectedCell = '-1 -1 0' inherited
Definition at line 25 of file picker.qh.
vector Item::size = '0 0 0' inherited
Definition at line 28 of file item.qh.
The documentation for this class was generated from the following file:
menu/xonotic/charmap.qh