Xonotic: server/campaign.qc File Reference
campaign.qc File Reference
#include "campaign.qh"
#include "defs.qh"
#include "cheats.qh"
#include "miscfunctions.qh"
#include "g_world.qh"
#include "../common/campaign_common.qh"
Functions
float Campaign_Invalid ()
float CampaignBailout (string s)
void CampaignLevelWarp (float n)
void CampaignPostInit ()
void CampaignPostIntermission ()
void CampaignPreInit ()
void CampaignPreIntermission ()
void CampaignSaveCvar (string cvarname, float value)
float cvar_campaignwrapper (string theCvar)
void cvar_set_campaignwrapper (string theCvar, string theValue)
string cvar_string_campaignwrapper (string theCvar)
Variables
string campaign_index_var
float campaign_level
float campaign_won
string cvar_campaignwrapper_list
Function Documentation
float Campaign_Invalid ()
Definition at line 61 of file campaign.qc.
References campaign_gametype, campaign_mapname, CampaignBailout(), GetMapname(), MapInfo_CurrentGametype(), MapInfo_Type_FromString(), and strcat().
Referenced by CampaignPostInit(), and CampaignPreInit().
 {
     string thismapname, wantedmapname;
     thismapname = GetMapname();
     wantedmapname = campaign_gametype[0];
     if(MapInfo_CurrentGametype() != MapInfo_Type_FromString(wantedmapname))
         return CampaignBailout("wrong game type!");
     wantedmapname = campaign_mapname[0];
     if(wantedmapname != thismapname)
         return CampaignBailout(strcat("wrong map: ", wantedmapname, " != ", thismapname));
     return 0;
 }
float CampaignBailout (string s)
Definition at line 22 of file campaign.qc.
References autocvar__campaign_testrun, cvar(), cvar_normal(), cvar_set(), cvar_set_normal, cvar_string(), cvar_string_normal(), error, and LOG_INFO.
Referenced by Campaign_Invalid(), and CampaignPreInit().
 {
     cvar = cvar_normal;
     cvar_string = cvar_string_normal;
     cvar_set = cvar_set_normal;
     cvar_set("g_campaign", "0");
     LOG_INFO("^4campaign initialization failed: ", s);
     if(autocvar__campaign_testrun)
         error("CAMPAIGN FAIL AHAHAHAHAHAHAHAHAH))");
     return 1;
 }
void CampaignLevelWarp (float n)
Definition at line 281 of file campaign.qc.
References campaign_entries, campaign_level, CampaignFile_Load(), CampaignFile_Unload(), CampaignSetup(), and error.
Referenced by GameCommand_warp().
 {
     if(n < 0)
         n = campaign_level + 1;
     CampaignFile_Unload();
     CampaignFile_Load(n, 1);
     if(campaign_entries)
         CampaignSetup(0);
     else
         error("Sorry, cheater. You are NOT WELCOME.");
     CampaignFile_Unload();
 }
void CampaignPostInit ()
Definition at line 130 of file campaign.qc.
References autocvar__campaign_testrun, campaign_fraglimit, Campaign_Invalid(), campaign_timelimit, cvar_set(), cvar_set_normal, and ftos().
Referenced by spawnfunc().
 {
     // now some sanity checks
     if(Campaign_Invalid())
         return;
     if(autocvar__campaign_testrun)
     {
         cvar_set("fraglimit", "0");
         cvar_set("timelimit", "0.01");
         cvar_set_normal("fraglimit", "0");
         cvar_set_normal("timelimit", "0.01");
     }
     else
     {
         cvar_set("fraglimit", ftos(campaign_fraglimit[0]));
         cvar_set("timelimit", ftos(campaign_timelimit[0]));
         cvar_set_normal("fraglimit", ftos(campaign_fraglimit[0]));
         cvar_set_normal("timelimit", ftos(campaign_timelimit[0]));
     }
 }
void CampaignPostIntermission ()
Definition at line 258 of file campaign.qc.
References campaign_entries, campaign_index_var, campaign_message, campaign_name, campaign_won, CampaignFile_Unload(), CampaignSetup(), localcmd, LOG_DEBUG, and strunzone().
Referenced by DoNextMapOverride().
 {
     // NOTE: campaign_won is 0 or 1, that is, points to the next level
     if(campaign_won && campaign_entries < 2)
     {
         // last map won!
         LOG_DEBUG("^2test run: campaign looks GOOD");
         localcmd("togglemenu 1\n");
         CampaignFile_Unload();
         return;
     }
     CampaignSetup(campaign_won);
     CampaignFile_Unload();
     strunzone(campaign_message);
     strunzone(campaign_index_var);
     strunzone(campaign_name);
     campaign_name = "";
 }
void CampaignPreInit ()
Definition at line 74 of file campaign.qc.
References autocvar__campaign_index, autocvar__campaign_name, autocvar_g_campaign_skill, autocvar_sv_cheats, autocvar_sv_gravity, campaign_bots, campaign_botskill, campaign_entries, campaign_gametype, campaign_index_var, Campaign_Invalid(), campaign_level, campaign_longdesc, campaign_message, campaign_mutators, campaign_name, campaign_shortdesc, CampaignBailout(), CampaignFile_Load(), CampaignFile_Unload(), cvar(), cvar_campaignwrapper(), cvar_campaignwrapper_list, cvar_set(), cvar_set_campaignwrapper(), cvar_set_normal, cvar_string(), cvar_string_campaignwrapper(), ftos(), MapInfo_SwitchGameType(), MapInfo_Type_FromString(), strcat(), strunzone(), and strzone().
Referenced by spawnfunc().
 {
     float baseskill;
     string title;
     campaign_level = autocvar__campaign_index;
     campaign_name = strzone(autocvar__campaign_name);
     campaign_index_var = strzone(strcat("g_campaign", campaign_name, "_index"));
     CampaignFile_Load(campaign_level, 2);
     if(campaign_entries < 1)
     {
         CampaignBailout("unknown map");
         return;
     }
     if(autocvar_sv_cheats)
     {
         MapInfo_SwitchGameType(MapInfo_Type_FromString(campaign_gametype[0]));
         CampaignFile_Unload();
         CampaignBailout("JOLLY CHEATS AHAHAHAHAHAHAH))");
         return;
     }
     baseskill = autocvar_g_campaign_skill;
     baseskill = baseskill + campaign_botskill[0];
     if(baseskill < 0)
         baseskill = 0;
     cvar_set("sv_public", "0");
     cvar_set("pausable", "1");
     cvar_campaignwrapper_list = strzone(strcat("; ", campaign_mutators[0], "; "));
     cvar = cvar_campaignwrapper;
     cvar_string = cvar_string_campaignwrapper;
     cvar_set = cvar_set_campaignwrapper;
     cvar_set("g_campaign", "1");
     cvar_set("g_dm", "0");
     cvar_set("skill", ftos(baseskill));
     cvar_set("bot_number", ftos(campaign_bots[0]));
     MapInfo_SwitchGameType(MapInfo_Type_FromString(campaign_gametype[0]));
     // copy sv_gravity cvar, as the engine needs it too (sorry, this will mess
     // with the menu a little still...)
     cvar_set_normal("sv_gravity", ftos(autocvar_sv_gravity));
     if(Campaign_Invalid())
         return;
     title = campaign_shortdesc[0];
     title = strzone(strcat("Level ", ftos(campaign_level + 1), ": ", title));
     campaign_message = strzone(strcat(title, "\n^3\n", campaign_longdesc[0], "\n\n^1press jump to enter the game"));
     strunzone(title);
 }
void CampaignPreIntermission ()
Definition at line 191 of file campaign.qc.
References autocvar__campaign_testrun, autocvar_fraglimit, autocvar_timelimit, bprint(), campaign_entries, campaign_index_var, campaign_level, campaign_name, campaign_won, CampaignSaveCvar(), cheatcount_total, checkrules_equality, cvar_normal(), FOREACH_CLIENT, IS_PLAYER, IS_REAL_CLIENT, strcat(), and time.
Referenced by NextLevel().
 {
     int won = 0;
     int lost = 0;
     string savevar;
     FOREACH_CLIENT(IS_PLAYER(it) && IS_REAL_CLIENT(it), {
         if(it.winning)
             won += 1;
         else
             lost += 1;
     });
     if(autocvar__campaign_testrun)
     {
         campaign_won = 1;
         bprint("Campaign test run, advancing level.\n");
     }
     else if(won == 1 && lost == 0 && checkrules_equality == 0)
     {
         if(autocvar_timelimit != 0 && autocvar_fraglimit != 0 && time > autocvar_timelimit * 60) // checks if the timelimit has expired.
         {
             campaign_won = 0;
             bprint("Time's up! The current level has been LOST.\n");
             // sound!
         }
         else
         {
             campaign_won = 1;
             bprint("The current level has been WON.\n");
             // sound!
         }
     }
     else if(autocvar_timelimit != 0 && time > autocvar_timelimit * 60)
     {
         campaign_won = 0;
         bprint("Time's up! The current level has been LOST.\n");
         // sound!
     }
     else
     {
         campaign_won = 0;
         bprint("The current level has been LOST.\n");
         // sound!
     }
     if(campaign_won && cheatcount_total == 0 && !autocvar__campaign_testrun)
     {
         if(campaign_level == cvar_normal(campaign_index_var))
         {
             if(campaign_entries < 2)
             {
                 // I have won
                 savevar = strcat("g_campaign", campaign_name, "_won");
                 CampaignSaveCvar(savevar, 1);
                 // advance level (for menu to show it right)
                 CampaignSaveCvar(campaign_index_var, campaign_level + 1);
             }
             else
             {
                 // advance level
                 CampaignSaveCvar(campaign_index_var, campaign_level + 1);
             }
         }
     }
 }
void CampaignSaveCvar (string cvarname, float value)
Definition at line 151 of file campaign.qc.
References argv(), cvar_set_normal, error, fclose(), fgets(), FILE_READ, FILE_WRITE, fopen(), fputs(), ftos(), registercvar(), strcat(), and tokenize_console.
Referenced by CampaignPreIntermission().
 {
     float fh;
     float len;
     string contents;
     string l;
     registercvar(cvarname, ftos(value));
     cvar_set_normal(cvarname, ftos(value));
     // note: cvarname must be remembered
     fh = fopen("campaign.cfg", FILE_READ);
     contents = "";
     if(fh >= 0)
     {
         while((l = fgets(fh)))
         {
             len = tokenize_console(l);
             if(len != 3)
                 continue;
             if(argv(0) != "set")
                 continue;
             if(argv(1) == cvarname)
                 continue;
             contents = strcat(contents, "set ", argv(1), " ", argv(2), "\n");
         }
         fclose(fh);
     }
     contents = strcat(contents, "set ", cvarname,  " ", ftos(value), "\n");
     fh = fopen("campaign.cfg", FILE_WRITE);
     if(fh >= 0)
     {
         fputs(fh, contents);
     }
     else
     {
         error("Cannot write to campaign file");
     }
 }
float cvar_campaignwrapper (string theCvar)
Definition at line 47 of file campaign.qc.
References cvar_string_campaignwrapper(), and stof().
Referenced by CampaignPreInit().
 {
     return stof(cvar_string_campaignwrapper(theCvar));
 }
void cvar_set_campaignwrapper (string theCvar, string theValue)
Definition at line 51 of file campaign.qc.
References cvar_campaignwrapper_list, cvar_string_campaignwrapper(), strcat(), strunzone(), and strzone().
Referenced by CampaignPreInit().
 {
     if(cvar_string_campaignwrapper(theCvar) == theValue)
         return;
     string s = cvar_campaignwrapper_list;
     cvar_campaignwrapper_list = strzone(strcat("; ", theCvar, " ", theValue, s));
     strunzone(s);
     //print(cvar_campaignwrapper_list, "\n");
 }
string cvar_string_campaignwrapper (string theCvar)
Definition at line 35 of file campaign.qc.
References cvar_campaignwrapper_list, cvar_defstring(), p, strcat(), strlen(), strstrofs, and substring().
Referenced by CampaignPreInit(), cvar_campaignwrapper(), and cvar_set_campaignwrapper().
 {
     float p, q;
     p = strstrofs(cvar_campaignwrapper_list, strcat("; ", theCvar, " "), 0);
     if(p < 0)
         return cvar_defstring(theCvar);
     p += strlen(theCvar) + 3;
     q = strstrofs(cvar_campaignwrapper_list, ";", p);
     if(q < 0)
         return cvar_defstring(theCvar);
     return substring(cvar_campaignwrapper_list, p, q - p);
 }
Variable Documentation
string campaign_index_var
Definition at line 19 of file campaign.qc.
Referenced by CampaignPostIntermission(), CampaignPreInit(), and CampaignPreIntermission().
float campaign_level
Definition at line 17 of file campaign.qc.
Referenced by CampaignLevelWarp(), CampaignPreInit(), and CampaignPreIntermission().
float campaign_won
Definition at line 18 of file campaign.qc.
Referenced by CampaignPostIntermission(), and CampaignPreIntermission().
string cvar_campaignwrapper_list
Definition at line 34 of file campaign.qc.
Referenced by CampaignPreInit(), cvar_set_campaignwrapper(), and cvar_string_campaignwrapper().