Xonotic: lib/warpzone/util_server.qc File Reference
util_server.qc File Reference
#include "util_server.qh"
#include "common.qh"
Functions
void WarpZoneLib_ExactTrigger_Init (entity this)
Function Documentation
void WarpZoneLib_ExactTrigger_Init (entity this)
Definition at line 12 of file util_server.qc.
References angles, maxs, mins, model, movedir, MOVETYPE_NONE, origin, scale, set_movetype(), setorigin(), solid, SOLID_TRIGGER, v_forward, vector(), and warpzone_isboxy.
 {
     vector mi, ma;
     if (this.movedir == '0 0 0')
     if (this.angles != '0 0 0')
     {
         makevectors (this.angles);
         this.movedir = v_forward;
     }
     if(this.model == "")
     {
         // It's a box! No need to match with exacttriggers.
         this.warpzone_isboxy = 1;
     }
     else
     {
         mi = this.mins;
         ma = this.maxs;
         precache_model(this.model);
         _setmodel(this, this.model);
         // let mapper-set mins/maxs override the model's bounds if set
         if(mi != '0 0 0' || ma != '0 0 0')
         {
             // It's a box! No need to match with exacttriggers.
             this.mins = mi;
             this.maxs = ma;
             this.warpzone_isboxy = 1;
         }
     }
     setorigin(this, this.origin);
     if(this.scale)
         setsize(this, this.mins * this.scale, this.maxs * this.scale);
     else
         setsize(this, this.mins, this.maxs);
     set_movetype(this, MOVETYPE_NONE);
     this.solid = SOLID_TRIGGER;
     this.model = "";
 }