Xonotic: common/weapons/weapon.qh File Reference
weapon.qh File Reference
#include <common/resources.qh>
#include <common/items/item/pickup.qh>
#include <common/stats.qh>
#include <common/items/_mod.qh>
Classes
class OffhandWeapon
class Weapon
fields which are explicitly/manually set are marked with "M", fields set automatically are marked with "A"
class WeaponPickup
Macros
#define SPAWNFUNC_WEAPON(name, weapon)
Typedefs
using WepSet = vector
Functions
string GetAmmoPicture (int ammotype)
string W_FixWeaponOrder (string order, float complete)
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
string W_FixWeaponOrder_BuildImpulseList (string o)
string W_FixWeaponOrder_ForceComplete (string order)
string W_Model (string w_mdl)
string W_NameWeaponOrder (string order)
string W_NumberWeaponOrder (string order)
WepSet W_RandomWeapons (entity e, WepSet remaining, int n)
string W_Sound (string w_snd)
string W_UndeprecateName (string s)
int weaponslot (.entity weaponentity)
Variables
const int MAX_WEAPONSLOTS = 2
entity weaponentities [MAX_WEAPONSLOTS]
string weaponorder_byid
const int WEP_FLAG_BLEED = BIT(14)
const int WEP_FLAG_CANCLIMB = BIT(3)
const int WEP_FLAG_DUALWIELD = BIT(11)
const int WEP_FLAG_HIDDEN = BIT(5)
const int WEP_FLAG_MUTATORBLOCKED = BIT(8)
const int WEP_FLAG_NODUAL = BIT(12)
const int WEP_FLAG_NORMAL = BIT(4)
const int WEP_FLAG_NOTRUEAIM = BIT(15)
const int WEP_FLAG_PENETRATEWALLS = BIT(13)
const int WEP_FLAG_RELOADABLE = BIT(6)
const int WEP_FLAG_SPECIALATTACK = BIT(16)
const int WEP_FLAG_SUPERWEAPON = BIT(7)
const int WEP_TYPE_HITSCAN = BIT(2)
const int WEP_TYPE_MELEE_PRI = BIT(9)
const int WEP_TYPE_MELEE_SEC = BIT(10)
const int WEP_TYPE_OTHER = BIT(0)
const int WEP_TYPE_SPLASH = BIT(1)
const int WS_CLEAR = 0
no weapon selected
const int WS_DROP = 2
deselecting frame
const int WS_INUSE = 3
fire state
const int WS_RAISE = 1
raise frame
const int WS_READY = 4
idle frame
Macro Definition Documentation
#define SPAWNFUNC_WEAPON (name, weapon)
Definition at line 134 of file weapon.qh.
Typedef Documentation
using WepSet = vector
Definition at line 11 of file weapon.qh.
Function Documentation
string GetAmmoPicture (int ammotype)
Definition at line 214 of file all.qc.
References RES_BULLETS, RES_CELLS, RES_FUEL, RES_NONE, RES_PLASMA, RES_ROCKETS, RES_SHELLS, STAT_CELLS, STAT_NAILS, STAT_ROCKETS, and STAT_SHELLS.
Referenced by DrawAmmoItem(), and W_DecreaseAmmo().
 {
     switch (ammotype)
     {
         case RES_SHELLS:  return ITEM_Shells.m_icon;
         case RES_BULLETS: return ITEM_Bullets.m_icon;
         case RES_ROCKETS: return ITEM_Rockets.m_icon;
         case RES_CELLS:   return ITEM_Cells.m_icon;
         case RES_PLASMA:  return ITEM_Plasma.m_icon;
         case RES_FUEL:    return ITEM_JetpackFuel.m_icon;
         default: return "";  // wtf, no ammo type?
     }
 }
string W_FixWeaponOrder (string order, float complete)
Definition at line 101 of file all.qc.
References fixPriorityList(), WEP_FIRST, WEP_IMPULSE_BEGIN, and WEP_LAST.
Referenced by LocalCommand_sendcvar(), W_FixWeaponOrder_AllowIncomplete(), W_FixWeaponOrder_ForceComplete(), and XonoticWeaponsList_draw().
 {
     return fixPriorityList(order, WEP_FIRST, WEP_LAST, WEP_IMPULSE_BEGIN - WEP_FIRST, complete);
 }
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
Definition at line 186 of file all.qc.
References W_FixWeaponOrder().
Referenced by GetCvars().
 {
     return W_FixWeaponOrder(order, 0);
 }
string W_FixWeaponOrder_BuildImpulseList (string o)
Definition at line 171 of file all.qc.
References ftos(), heapsort(), NULL, strcat(), string_null, substring(), W_FixWeaponOrder_BuildImpulseList_buf, W_FixWeaponOrder_BuildImpulseList_cmp(), W_FixWeaponOrder_BuildImpulseList_order, W_FixWeaponOrder_BuildImpulseList_swap(), WEP_FIRST, and WEP_LAST.
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     int i;
     W_FixWeaponOrder_BuildImpulseList_order = o;
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST] = i;
     heapsort(WEP_LAST - WEP_FIRST + 1, W_FixWeaponOrder_BuildImpulseList_swap, W_FixWeaponOrder_BuildImpulseList_cmp,
         NULL);
     o = "";
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         o = strcat(o, " ", ftos(W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST]));
     W_FixWeaponOrder_BuildImpulseList_order = string_null;
     return substring(o, 1, -1);
 }
string W_FixWeaponOrder_ForceComplete (string order)
Definition at line 191 of file all.qc.
References cvar_defstring(), W_FixWeaponOrder(), and W_NumberWeaponOrder().
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     if (order == "") order = W_NumberWeaponOrder(cvar_defstring("cl_weaponpriority"));
     return W_FixWeaponOrder(order, 1);
 }
string W_Model (string w_mdl)
Definition at line 265 of file all.qc.
References angles, anim_set(), argv(), CLIENT_COMMAND, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, compressShotOrigin(), decompressShotOrigin(), entity(), FOREACH, frame, gettagindex, IS_REAL_CLIENT, LOG_INFO, LOG_INFOF, LOG_WARNF, M_ARGV, MASK_NORMAL, maxs, mins, model, movedir, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, name, NET_HANDLE, NULL, oldorigin, owner, ReadRegistered, REGISTER_NET_C2S, REGISTER_NET_TEMP, renderflags, RF_VIEWMODEL, setanim, setmodel, setorigin(), stov(), strcat(), v, vector(), view_ofs, viewmodelforclient, viewmodels, W_GunAlign(), W_Model(), Weapon_whereis(), weaponslot(), WriteByte(), WriteRegistered, WS_DROP, and WS_RAISE.
Referenced by W_Model().
 {
     string output = strcat("models/weapons/", w_mdl);
     MUTATOR_CALLHOOK(WeaponModel, w_mdl, output);
     return M_ARGV(1, string);
 }
string W_NameWeaponOrder (string order)
Definition at line 131 of file all.qc.
References mapPriorityList(), and W_NameWeaponOrder_MapFunc().
Referenced by XonoticWeaponsList_draw().
 {
     return mapPriorityList(order, W_NameWeaponOrder_MapFunc);
 }
string W_NumberWeaponOrder (string order)
Definition at line 142 of file all.qc.
References mapPriorityList(), and W_NumberWeaponOrder_MapFunc().
Referenced by bot_custom_weapon_priority_setup(), HUD_Weapons(), LocalCommand_sendcvar(), W_FixWeaponOrder_ForceComplete(), XonoticWeaponsList_draw(), and XonoticWeaponsList_toString().
 {
     return mapPriorityList(order, W_NumberWeaponOrder_MapFunc);
 }
WepSet W_RandomWeapons (entity e, WepSet remaining, int n)
Definition at line 197 of file all.qc.
References FOREACH, RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), result, and WepSet_FromWeapon.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     WepSet result = '0 0 0';
     for (int j = 0; j < n; ++j)
     {
         RandomSelection_Init();
         FOREACH(Weapons, it != WEP_Null, {
             if (remaining & (it.m_wepset))
                 RandomSelection_AddEnt(it, 1, 1);
         });
         Weapon w = RandomSelection_chosen_ent;
         result |= WepSet_FromWeapon(w);
         remaining &= ~WepSet_FromWeapon(w);
     }
     return result;
 }
string W_Sound (string w_snd)
Definition at line 258 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
 {
     string output = strcat("weapons/", w_snd);
     MUTATOR_CALLHOOK(WeaponSound, w_snd, output);
     return M_ARGV(1, string);
 }
string W_UndeprecateName (string s)
Definition at line 116 of file all.qc.
Referenced by W_NumberWeaponOrder_MapFunc().
 {
     switch (s)
     {
         case "nex": return "vortex";
         case "rocketlauncher": return "devastator";
         case "laser": return "blaster";
         case "minstanex": return "vaporizer";
         case "grenadelauncher": return "mortar";
         case "uzi": return "machinegun";
         case "hmg": return "okhmg";
         case "rpc": return "okrpc";
         default: return s;
     }
 }
int weaponslot (.entity weaponentity)
Definition at line 16 of file weapon.qh.
References MAX_WEAPONSLOTS, and weaponentities.
Referenced by client_hasweapon(), GrapplingHookSend(), Monster_Attack_Check(), W_Model(), W_Reload(), W_WeaponFrame(), and weapon_prepareattack_do().
 {
     for (int i = 0; i < MAX_WEAPONSLOTS; ++i)
     {
         if (weaponentities[i] == weaponentity)
         {
             return i;
         }
     }
     return 0;
 }
Variable Documentation
const int MAX_WEAPONSLOTS = 2
Definition at line 13 of file weapon.qh.
Referenced by AppendItemcodes(), bot_cmd_select_weapon(), CreatureFrame_FallDamage(), CSQC_UpdateView(), Damage(), DrawReticle(), findperpendicular(), FixIntermissionClient(), Freeze(), GetCurrentFov(), GetCvars(), havocbot_ai(), havocbot_movetogoal(), HitSound(), IMPULSE(), Monster_Remove(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), PlayerDamage(), PlayerPreThink(), PlayerThink(), PM_check_hitground(), PM_ClientMovement_UpdateStatus(), Portal_Think(), PutObserverInServer(), PutPlayerInServer(), REGISTER_MUTATOR(), RemoveGrapplingHooks(), SetSpectatee(), STATIC_INIT(), Unfreeze(), vehicles_enter(), vehicles_exit(), vehicles_spawn(), View_CheckButtonStatus(), W_DualWielding(), weapon_prepareattack_do(), weaponslot(), and X().
entity weaponentities[MAX_WEAPONSLOTS]
Definition at line 14 of file weapon.qh.
Referenced by AppendItemcodes(), bot_cmd_debug_assert_canfire(), bot_cmd_select_weapon(), CheatCommand(), CL_SpawnWeaponentity(), CreatureFrame_FallDamage(), Damage(), Drag_Update(), findperpendicular(), FixIntermissionClient(), formatmessage(), Freeze(), GameCommand_animbench(), GameCommand_gettaginfo(), GetCvars(), GiveBall(), havocbot_ai(), havocbot_movetogoal(), IMPULSE(), Monster_Dead(), Monster_Remove(), Monster_Think(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), PlayerDamage(), PlayerPreThink(), PlayerThink(), PM_check_hitground(), PM_ClientMovement_UpdateStatus(), Portal_Think(), PutObserverInServer(), PutPlayerInServer(), REGISTER_MUTATOR(), RemoveGrapplingHooks(), SetSpectatee(), TEST(), Turret::tr_precache(), Unfreeze(), vehicles_enter(), vehicles_exit(), vehicles_spawn(), W_DualWielding(), W_WeaponFrame(), weapon_prepareattack_do(), weaponslot(), and X().
string weaponorder_byid
Definition at line 205 of file weapon.qh.
Referenced by STATIC_INIT(), W_NextWeapon(), and W_PreviousWeapon().
const int WEP_FLAG_BLEED = BIT(14)
Definition at line 200 of file weapon.qh.
const int WEP_FLAG_CANCLIMB = BIT(3)
Definition at line 189 of file weapon.qh.
Referenced by PlayerDamage().
const int WEP_FLAG_DUALWIELD = BIT(11)
Definition at line 197 of file weapon.qh.
Referenced by client_hasweapon(), and W_WeaponFrame().
const int WEP_FLAG_HIDDEN = BIT(5)
Definition at line 191 of file weapon.qh.
Referenced by HUD_Weapons(), KeyBinds_Read(), Scoreboard_AccuracyStats_Draw(), want_weapon(), weapons_most(), and XonoticMutatorsDialog_fill().
const int WEP_FLAG_MUTATORBLOCKED = BIT(8)
Definition at line 194 of file weapon.qh.
Referenced by Dump_Weapon_Settings(), HUD_Weapons(), KeyBinds_Read(), NIX_CanChooseWeapon(), RandomItems_GetRandomVanillaItemClassName(), REGISTER_MUTATOR(), Scoreboard_AccuracyStats_Draw(), W_GetCycleWeapon(), want_weapon(), weapon_defaultspawnfunc(), weapons_all(), weapons_most(), and XonoticWeaponsList_drawListBoxItem().
const int WEP_FLAG_NODUAL = BIT(12)
Definition at line 198 of file weapon.qh.
const int WEP_FLAG_NORMAL = BIT(4)
Definition at line 190 of file weapon.qh.
Referenced by NIX_CanChooseWeapon(), want_weapon(), and weapons_most().
const int WEP_FLAG_NOTRUEAIM = BIT(15)
Definition at line 201 of file weapon.qh.
Referenced by TrueAimCheck().
const int WEP_FLAG_PENETRATEWALLS = BIT(13)
Definition at line 199 of file weapon.qh.
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
const int WEP_FLAG_RELOADABLE = BIT(6)
Definition at line 192 of file weapon.qh.
Referenced by havocbot_ai(), NIX_GiveCurrentWeapon(), PutPlayerInServer(), W_Reload(), and W_WeaponFrame().
const int WEP_FLAG_SPECIALATTACK = BIT(16)
Definition at line 202 of file weapon.qh.
Referenced by Dump_Weapon_Settings(), fixPriorityList(), HUD_Weapons(), KeyBinds_Read(), Scoreboard_AccuracyStats_Draw(), want_weapon(), weapons_all(), weapons_most(), and XonoticMutatorsDialog_fill().
const int WEP_FLAG_SUPERWEAPON = BIT(7)
Definition at line 193 of file weapon.qh.
Referenced by KeyBinds_Read(), STATIC_INIT(), and weapon_defaultspawnfunc().
const int WEP_TYPE_HITSCAN = BIT(2)
Definition at line 188 of file weapon.qh.
const int WEP_TYPE_MELEE_PRI = BIT(9)
Definition at line 195 of file weapon.qh.
Referenced by weapon_thinkf().
const int WEP_TYPE_MELEE_SEC = BIT(10)
Definition at line 196 of file weapon.qh.
Referenced by weapon_thinkf().
const int WEP_TYPE_OTHER = BIT(0)
Definition at line 186 of file weapon.qh.
Referenced by Scoreboard_AccuracyStats_Draw().
const int WEP_TYPE_SPLASH = BIT(1)
Definition at line 187 of file weapon.qh.
const int WS_CLEAR = 0
no weapon selected
Definition at line 30 of file weapon.qh.
Referenced by viewmodel_draw(), w_clear(), and W_WeaponFrame().
const int WS_DROP = 2
deselecting frame
Definition at line 34 of file weapon.qh.
Referenced by viewmodel_draw(), W_Model(), and W_WeaponFrame().
const int WS_INUSE = 3
fire state
Definition at line 36 of file weapon.qh.
Referenced by W_WeaponFrame(), and weapon_prepareattack_do().
const int WS_RAISE = 1
raise frame
Definition at line 32 of file weapon.qh.
Referenced by viewmodel_draw(), W_Model(), W_WeaponFrame(), and weapon_thinkf().
const int WS_READY = 4
idle frame
Definition at line 38 of file weapon.qh.
Referenced by bot_cmd_debug_assert_canfire(), DropBall(), GiveBall(), w_ready(), W_Reload(), W_ThrowWeapon(), W_WeaponFrame(), and weapon_prepareattack_check().