Xonotic: server/gamelog.qc File Reference
gamelog.qc File Reference
#include "gamelog.qh"
#include <server/main.qh>
Functions
string GameLog_ProcessIP (string s)
void GameLogClose ()
void GameLogEcho (string s)
void GameLogInit ()
Function Documentation
GameLog_ProcessIP()
string GameLog_ProcessIP (string s)
Definition at line 5 of file gamelog.qc.
References autocvar_sv_eventlog_ipv6_delimiter.
Referenced by ClientConnect().
 {
     if(!autocvar_sv_eventlog_ipv6_delimiter)
         return s;
     return strreplace(":", "_", s);
 }
GameLogClose()
void GameLogClose ()
Definition at line 48 of file gamelog.qc.
References fclose(), logfile, and logfile_open.
Referenced by NextLevel().
 {
     if (logfile_open && logfile >= 0)
     {
         fclose(logfile);
         logfile = -1;
     }
 }
GameLogEcho()
void GameLogEcho (string s)
Definition at line 12 of file gamelog.qc.
References autocvar_sv_eventlog_console, autocvar_sv_eventlog_files, autocvar_sv_eventlog_files_counter, autocvar_sv_eventlog_files_nameprefix, autocvar_sv_eventlog_files_namesuffix, autocvar_sv_eventlog_files_timestamps, cvar_set(), dedicated_print(), FILE_APPEND, fopen(), fputs(), ftos(), itos, logfile, logfile_open, strcat(), strlen(), and substring().
Referenced by anticheat_report_to_eventlog(), ClientConnect(), ClientDisconnect(), ctf_EventLog(), cts_EventLog(), dom_EventLog(), DumpStats(), end_minigame(), invite_minigame(), ka_EventLog(), kh_Scores_Event(), LogDeath(), LogNB(), LogTeamChange(), MapVote_CheckRules_2(), MapVote_Finished(), MapVote_Suggest(), minigame_addplayer(), minigame_rmplayer(), MUTATOR_HOOKFUNCTION(), NextLevel(), PlayerInList(), PlayerPreThink(), race_EventLog(), ReadyRestart_force(), Say(), spawnfunc(), start_minigame(), StartFrame(), VoteCommand_call(), VoteCommand_master(), VoteSpam(), VoteStop(), and write_recordmarker().
 {
     if (autocvar_sv_eventlog_files)
     {
         if (!logfile_open)
         {
             logfile_open = true;
             int matches = autocvar_sv_eventlog_files_counter + 1;
             cvar_set("sv_eventlog_files_counter", itos(matches));
             string fn = ftos(matches);
             if (strlen(fn) < 8)
                 fn = strcat(substring("00000000", 0, 8 - strlen(fn)), fn);
             fn = strcat(autocvar_sv_eventlog_files_nameprefix, fn, autocvar_sv_eventlog_files_namesuffix);
             logfile = fopen(fn, FILE_APPEND);
             fputs(logfile, ":logversion:3\n");
         }
         if (logfile >= 0)
         {
             if (autocvar_sv_eventlog_files_timestamps)
                 fputs(logfile, strcat(":time:", strftime(true, "%Y-%m-%d %H:%M:%S", "\n", s, "\n")));
             else
                 fputs(logfile, strcat(s, "\n"));
         }
     }
     if (autocvar_sv_eventlog_console)
     {
         dedicated_print(strcat(s, "\n"));
     }
 }
GameLogInit()
void GameLogInit ()
Definition at line 42 of file gamelog.qc.
References logfile_open.
Referenced by spawnfunc().
 {
     logfile_open = false;
     // will be opened later
 }