Xonotic: server/round_handler.qh File Reference
round_handler.qh File Reference
Macros
#define ROUND_HANDLER_H
#define round_handler_IsActive() (round_handler != world)
#define round_handler_AwaitingNextRound() (round_handler.wait)
#define round_handler_CountdownRunning() (!round_handler.wait && round_handler.cnt)
#define round_handler_IsRoundStarted() (!round_handler.wait && !round_handler.cnt)
#define round_handler_GetEndTime() (round_handler.round_endtime)
Functions
float () canRoundStart
void () roundStart
void round_handler_Init (float the_delay, float the_count, float the_round_timelimit)
void round_handler_Spawn (float() canRoundStart_func, float() canRoundEnd_func, void() roundStart_func)
void round_handler_Reset (float next_think)
void round_handler_Remove ()
Variables
entity round_handler
float delay
float count
float wait
float cnt
float round_timelimit
float round_endtime
Macro Definition Documentation
#define round_handler_AwaitingNextRound () (round_handler.wait)
Definition at line 22 of file round_handler.qh.
#define round_handler_CountdownRunning () (!round_handler.wait && round_handler.cnt)
Definition at line 23 of file round_handler.qh.
#define round_handler_GetEndTime () (round_handler.round_endtime)
Definition at line 25 of file round_handler.qh.
#define ROUND_HANDLER_H
Definition at line 2 of file round_handler.qh.
#define round_handler_IsActive () (round_handler != world)
Definition at line 21 of file round_handler.qh.
Referenced by forbidWeaponUse(), GrapplingHookThink(), ImpulseCommands(), Monster_Move(), Monster_Move_2D(), and reset_map().
#define round_handler_IsRoundStarted () (!round_handler.wait && !round_handler.cnt)
Definition at line 24 of file round_handler.qh.
Referenced by forbidWeaponUse(), GrapplingHookThink(), ImpulseCommands(), Monster_Move(), and Monster_Move_2D().
Function Documentation
float ()
void round_handler_Init (float the_delay, float the_count, float the_round_timelimit)
Definition at line 68 of file round_handler.qc.
References cnt, count, delay, entity(), fabs(), floor(), round_handler, and round_timelimit.
Referenced by round_handler_Spawn().
 {
     entity this = round_handler;
     this.delay = (the_delay > 0) ? the_delay : 0;
     this.count = fabs(floor(the_count));
     this.cnt = this.count + 1;
     this.round_timelimit = (the_round_timelimit > 0) ? the_round_timelimit : 0;
 }
void round_handler_Remove ()
Definition at line 115 of file round_handler.qc.
References round_handler, and world.
Referenced by round_handler_Think().
 {
     remove(round_handler);
     round_handler = world;
 }
void round_handler_Reset (float next_think)
Definition at line 105 of file round_handler.qc.
References cnt, count, entity(), nextthink, round_handler, round_starttime, and wait.
Referenced by reset_map(), and round_handler_Think().
 {
     entity this = round_handler;
     this.wait = false;
     if (this.count)
         if (this.cnt < this.count + 1) this.cnt = this.count + 1;
     this.nextthink = next_think;
     round_starttime = (next_think) ? (next_think + this.count) : -1;
 }
void round_handler_Spawn (float() canRoundStart_func, float() canRoundEnd_func, void() roundStart_func)
Definition at line 87 of file round_handler.qc.
References backtrace, entity(), nextthink, round_handler, round_handler_FirstThink(), round_handler_Init(), time, and wait.
 {
     if (round_handler)
     {
         backtrace("Can't spawn round_handler again!");
         return;
     }
     entity this = round_handler = new(round_handler);
     this.think = round_handler_FirstThink;
     this.canRoundStart = canRoundStart_func;
     this.canRoundEnd = canRoundEnd_func;
     this.roundStart = roundStart_func;
     this.wait = false;
     round_handler_Init(5, 5, 180);
     this.nextthink = time;
 }
void ()
Variable Documentation
float cnt
Definition at line 8 of file round_handler.qh.
float count
Definition at line 6 of file round_handler.qh.
float delay
Definition at line 5 of file round_handler.qh.
float round_endtime
Definition at line 11 of file round_handler.qh.
Referenced by round_handler_Think().
entity round_handler
Definition at line 4 of file round_handler.qh.
Referenced by round_handler_Init(), round_handler_Remove(), round_handler_Reset(), and round_handler_Spawn().
float round_timelimit
Definition at line 10 of file round_handler.qh.
Referenced by round_handler_Init(), and round_handler_Think().
float wait
Definition at line 7 of file round_handler.qh.