Xonotic: Mortar Class Reference
Mortar Class Reference
Public Member Functions
ATTRIB (Weapon, m_model, entity)
M: model MDL_id_ITEM.
ATTRIB (Weapon, m_pickup, entity)
virtual void describe ()
virtual void display ()
virtual void wr_aim ()
(SERVER) runs bot aiming code for this weapon
virtual void wr_checkammo1 ()
(SERVER) checks ammo for weapon primary
virtual void wr_checkammo2 ()
(SERVER) checks ammo for weapon second
virtual void wr_config ()
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
virtual void wr_drop ()
(SERVER) the weapon is dropped
virtual void wr_glow ()
(CLIENT) weapon specific glow
virtual void wr_gonethink ()
(SERVER) logic to run when weapon is lost
virtual void wr_impacteffect ()
(CLIENT) impact effect for weapon explosion
virtual void wr_init ()
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
virtual void wr_killmessage ()
(SERVER) notification number for kill message (may inspect w_deathtype for details)
virtual void wr_pickup ()
(SERVER) a weapon is picked up
virtual void wr_playerdeath ()
(SERVER) called whenever a player dies
virtual void wr_reload ()
(SERVER) handles reloading for weapon
virtual void wr_resetplayer ()
(SERVER) clears fields that the weapon may use
virtual void wr_setup ()
(SERVER) setup weapon data
virtual void wr_suicidemessage ()
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
virtual void wr_think ()
(SERVER) logic to run every frame
virtual void wr_update ()
(SERVER) update cvar based properties
virtual void wr_viewmodel ()
(CLIENT) weapon specific view model
virtual void wr_zoom ()
(BOTH) weapon specific zoom reticle
Public Attributes
int ammo_field = ammo_rockets
float bot_pickupbasevalue = 7000
int impulse = 4
int m_id = 0
string m_name = _("Mortar")
string mdl = "gl"
string model2 = "weapongrenadelauncher"
string netname = "mortar"
int spawnflags = WEP_FLAG_NORMAL | WEP_FLAG_RELOADABLE | WEP_FLAG_CANCLIMB | WEP_TYPE_SPLASH
string w_crosshair = "gfx/crosshairgrenadelauncher"
float w_crosshair_size = 0.7
string w_reticle = string_null
A: reticle : per-weapon zoom reticle.
WepSet weapons = '0 0 0'
A: WEPSET_id : WEPSET_...
vector wpcolor = '1 0 0'
Detailed Description
Definition at line 3 of file mortar.qc.
Member Function Documentation
Weapon::ATTRIB (Weapon , m_model , entity) inherited
M: model MDL_id_ITEM.
Weapon::ATTRIB (Weapon , m_pickup , entity) inherited
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void Weapon::display () inline virtual inherited
Reimplemented from Object.
Definition at line 132 of file weapon.qh.
References cvar_string(), and string_null.
{
         returns(this.m_name, this.model2 ? sprintf("/gfx/hud/%s/%s", cvar_string("menu_skin"), this.model2) : string_null);
     }
virtual void Weapon::wr_aim () inline virtual inherited
(SERVER) runs bot aiming code for this weapon
Definition at line 98 of file weapon.qh.
 {}
virtual void Weapon::wr_checkammo1 () inline virtual inherited
(SERVER) checks ammo for weapon primary
Definition at line 94 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_checkammo2 () inline virtual inherited
(SERVER) checks ammo for weapon second
Definition at line 96 of file weapon.qh.
Referenced by client_hasweapon(), and weapon_prepareattack_checkammo().
 {return false;}
virtual void Weapon::wr_config () inline virtual inherited
(ALL) dump weapon cvars to config in data directory (see: sv_cmd dumpweapons)
Definition at line 116 of file weapon.qh.
 {}
virtual void Weapon::wr_drop () inline virtual inherited
(SERVER) the weapon is dropped
Definition at line 127 of file weapon.qh.
 {}
virtual void Weapon::wr_glow () inline virtual inherited
(CLIENT) weapon specific glow
Definition at line 125 of file weapon.qh.
 { return '0 0 0'; }
virtual void Weapon::wr_gonethink () inline virtual inherited
(SERVER) logic to run when weapon is lost
Definition at line 114 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_impacteffect () inline virtual inherited
(CLIENT) impact effect for weapon explosion
Definition at line 110 of file weapon.qh.
 {}
virtual void Weapon::wr_init () inline virtual inherited
(BOTH) precaches models/sounds used by this weapon, also sets up weapon properties
Definition at line 100 of file weapon.qh.
Referenced by GrappleHookInit().
 {}
virtual void Weapon::wr_killmessage () inline virtual inherited
(SERVER) notification number for kill message (may inspect w_deathtype for details)
Definition at line 104 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_pickup () inline virtual inherited
(SERVER) a weapon is picked up
Definition at line 129 of file weapon.qh.
 {}
virtual void Weapon::wr_playerdeath () inline virtual inherited
(SERVER) called whenever a player dies
Definition at line 112 of file weapon.qh.
Referenced by PlayerDamage().
 {}
virtual void Weapon::wr_reload () inline virtual inherited
(SERVER) handles reloading for weapon
Definition at line 106 of file weapon.qh.
Referenced by IMPULSE(), and W_SwitchWeapon().
 {}
virtual void Weapon::wr_resetplayer () inline virtual inherited
(SERVER) clears fields that the weapon may use
Definition at line 108 of file weapon.qh.
 {}
virtual void Weapon::wr_setup () inline virtual inherited
(SERVER) setup weapon data
Definition at line 90 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_suicidemessage () inline virtual inherited
(SERVER) notification number for suicide message (may inspect w_deathtype for details)
Definition at line 102 of file weapon.qh.
References NULL.
Referenced by Obituary_WeaponDeath().
 {return NULL;}
virtual void Weapon::wr_think () inline virtual inherited
(SERVER) logic to run every frame
Definition at line 92 of file weapon.qh.
Referenced by W_WeaponFrame().
 {}
virtual void Weapon::wr_update () inline virtual inherited
(SERVER) update cvar based properties
Definition at line 131 of file weapon.qh.
 {}
virtual void Weapon::wr_viewmodel () inline virtual inherited
(CLIENT) weapon specific view model
Definition at line 123 of file weapon.qh.
References string_null.
Referenced by viewmodel_draw().
 { return string_null; }
virtual void Weapon::wr_zoom () inline virtual inherited
(BOTH) weapon specific zoom reticle
Definition at line 118 of file weapon.qh.
Referenced by CSQC_UpdateView().
{
         // no weapon specific image for this weapon
         return false;
     }
Member Data Documentation
int Mortar::ammo_field = ammo_rockets
Definition at line 4 of file mortar.qc.
float Mortar::bot_pickupbasevalue = 7000
Definition at line 7 of file mortar.qc.
int Mortar::impulse = 4
Definition at line 5 of file mortar.qc.
int Weapon::m_id = 0 inherited
Definition at line 57 of file weapon.qh.
Referenced by client_hasweapon(), PlayerDamage(), SpawnThrownWeapon(), TEST(), W_SwitchWeapon(), W_SwitchWeapon_Force(), and W_ThrowWeapon().
string Mortar::m_name = _("Mortar")
Definition at line 17 of file mortar.qc.
string Mortar::mdl = "gl"
Definition at line 9 of file mortar.qc.
string Mortar::model2 = "weapongrenadelauncher"
Definition at line 15 of file mortar.qc.
string Mortar::netname = "mortar"
Definition at line 16 of file mortar.qc.
int Mortar::spawnflags = WEP_FLAG_NORMAL | WEP_FLAG_RELOADABLE | WEP_FLAG_CANCLIMB | WEP_TYPE_SPLASH
Definition at line 6 of file mortar.qc.
string Mortar::w_crosshair = "gfx/crosshairgrenadelauncher"
Definition at line 13 of file mortar.qc.
float Mortar::w_crosshair_size = 0.7
Definition at line 14 of file mortar.qc.
string Weapon::w_reticle = string_null inherited
A: reticle : per-weapon zoom reticle.
Definition at line 79 of file weapon.qh.
Referenced by CSQC_UpdateView().
WepSet Weapon::weapons = '0 0 0' inherited
A: WEPSET_id : WEPSET_...
Definition at line 59 of file weapon.qh.
vector Mortar::wpcolor = '1 0 0'
Definition at line 8 of file mortar.qc.
The documentation for this class was generated from the following file:
common/weapons/weapon/mortar.qc