Xonotic: menu/anim/easing.qh File Reference
easing.qh File Reference
#include "animation.qh"
Classes
class Easing
Functions
float easingLinear (float, float, float, float)
float easingQuadIn (float, float, float, float)
float easingQuadInOut (float, float, float, float)
float easingQuadOut (float, float, float, float)
entity makeEasing (entity, void(entity, float), float(float, float, float, float), float, float, float, float)
entity makeHostedEasing (entity, void(entity, float), float(float, float, float, float), float, float, float)
Function Documentation
float easingLinear (float , float , float , float)
Definition at line 31 of file easing.qc.
     {
         return (animDelta * (tickTime / animDuration)) + animStart;
     }
float easingQuadIn (float , float , float , float)
Definition at line 36 of file easing.qc.
Referenced by easingQuadInOut().
     {
         float frac = tickTime / animDuration;
         return (animDelta * frac * frac) + animStart;
     }
float easingQuadInOut (float , float , float , float)
Definition at line 48 of file easing.qc.
References easingQuadIn(), and easingQuadOut().
     {
         if (tickTime < (animDuration / 2)) return easingQuadIn(tickTime, (animDuration / 2), animStart, (animDelta / 2));
         else return easingQuadOut((tickTime - (animDuration / 2)), (animDuration / 2), (animStart + (animDelta / 2)), (animDelta / 2));
     }
float easingQuadOut (float , float , float , float)
Definition at line 42 of file easing.qc.
Referenced by easingQuadInOut(), and Slider_setValue_allowAnim().
     {
         float frac = tickTime / animDuration;
         return (-animDelta * frac * (frac - 2)) + animStart;
     }
entity makeEasing (entity , void(entity, float) , float(float, float, float, float) , float , float , float , float)
Definition at line 13 of file easing.qc.
References entity(), and NEW.
Referenced by Keyframe::addEasing(), and makeHostedEasing().
     {
         entity this = NEW(Easing);
         this.configureAnimation(this, obj, objSetter, animStartTime, animDuration, animStartValue, animEnd);
         this.setMath(this, func);
         return this;
     }
entity makeHostedEasing (entity , void(entity, float) , float(float, float, float, float) , float , float , float)
Definition at line 6 of file easing.qc.
References anim, entity(), makeEasing(), and time.
Referenced by Slider_setValue_allowAnim().
     {
         entity this = makeEasing(obj, objSetter, func, time, animDuration, animStartValue, animEnd);
         anim.addAnim(anim, this);
         return this;
     }