Xonotic: common/deathtypes/all.qc File Reference
all.qc File Reference
#include "all.qh"
Functions
string Deathtype_Name (int deathtype)
Function Documentation
string Deathtype_Name (int deathtype)
Definition at line 3 of file all.qc.
References backtrace, DEATH_ISSPECIAL, Deathtypes_from, DT_FIRST, entity(), and ftos().
Referenced by LogDeath(), and Obituary().
 {
     if (DEATH_ISSPECIAL(deathtype)) {
         entity deathent = Deathtypes_from(deathtype - DT_FIRST);
         if (!deathent) { backtrace("Deathtype_Name: Could not find deathtype entity!\n"); return ""; }
         return deathent.nent_name;
     }
     return ftos(deathtype);
 }