Xonotic: common/weapons/all.qc File Reference
all.qc File Reference
#include "all.qh"
Macros
#define WEAPONS_ALL_C
Functions
WepSet _WepSet_FromWeapon (int a)
string GetAmmoName (int ammotype)
string GetAmmoPicture (int ammotype)
string W_FixWeaponOrder (string order, float complete)
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
string W_FixWeaponOrder_BuildImpulseList (string o)
float W_FixWeaponOrder_BuildImpulseList_cmp (int i, int j, entity pass)
void W_FixWeaponOrder_BuildImpulseList_swap (int i, int j, entity pass)
string W_FixWeaponOrder_ForceComplete (string order)
string W_Model (string w_mdl)
string W_NameWeaponOrder (string order)
string W_NameWeaponOrder_MapFunc (string s)
string W_NumberWeaponOrder (string order)
string W_NumberWeaponOrder_MapFunc (string s)
WepSet W_RandomWeapons (entity e, WepSet remaining, int n)
string W_Sound (string w_snd)
string W_UndeprecateName (string s)
Variables
float W_FixWeaponOrder_BuildImpulseList_buf [REGISTRY_MAX(Weapons)]
string W_FixWeaponOrder_BuildImpulseList_order
Macro Definition Documentation
WEAPONS_ALL_C
#define WEAPONS_ALL_C
Definition at line 3 of file all.qc.
Function Documentation
_WepSet_FromWeapon()
WepSet _WepSet_FromWeapon (int a)
Definition at line 53 of file all.qc.
References BIT, REGISTRY_MAX, and WEP_FIRST.
Referenced by STATIC_INIT().
 {
     a -= WEP_FIRST;
     if (REGISTRY_MAX(Weapons) > 24)
         if (a >= 24)
         {
             a -= 24;
             if (REGISTRY_MAX(Weapons) > 48)
                 if (a >= 24)
                 {
                     a -= 24;
                     return '0 0 1' * BIT(a);
                 }
             return '0 1 0' * BIT(a);
         }
     return '1 0 0' * BIT(a);
 }
GetAmmoName()
string GetAmmoName (int ammotype)
Definition at line 219 of file all.qc.
References RES_BULLETS, RES_CELLS, RES_FUEL, RES_NONE, RES_PLASMA, RES_ROCKETS, RES_SHELLS, STAT_CELLS, STAT_NAILS, STAT_ROCKETS, and STAT_SHELLS.
Referenced by formatmessage().
 {
     switch (ammotype)
     {
         case RES_SHELLS:  return ITEM_Shells.m_name;
         case RES_BULLETS: return ITEM_Bullets.m_name;
         case RES_ROCKETS: return ITEM_Rockets.m_name;
         case RES_CELLS:   return ITEM_Cells.m_name;
         case RES_PLASMA:  return ITEM_Plasma.m_name;
         case RES_FUEL:    return ITEM_JetpackFuel.m_name;
         default:          return "batteries";
     }
 }
GetAmmoPicture()
string GetAmmoPicture (int ammotype)
Definition at line 205 of file all.qc.
References RES_BULLETS, RES_CELLS, RES_FUEL, RES_PLASMA, RES_ROCKETS, and RES_SHELLS.
Referenced by DrawAmmoItem(), and W_DecreaseAmmo().
 {
     switch (ammotype)
     {
         case RES_SHELLS:  return ITEM_Shells.m_icon;
         case RES_BULLETS: return ITEM_Bullets.m_icon;
         case RES_ROCKETS: return ITEM_Rockets.m_icon;
         case RES_CELLS:   return ITEM_Cells.m_icon;
         case RES_PLASMA:  return ITEM_Plasma.m_icon;
         case RES_FUEL:    return ITEM_JetpackFuel.m_icon;
         default: return "";  // wtf, no ammo type?
     }
 }
W_FixWeaponOrder()
string W_FixWeaponOrder (string order, float complete)
Definition at line 95 of file all.qc.
References fixPriorityList(), WEP_FIRST, WEP_IMPULSE_BEGIN, and WEP_LAST.
Referenced by LocalCommand_sendcvar(), W_FixWeaponOrder_AllowIncomplete(), W_FixWeaponOrder_ForceComplete(), and XonoticWeaponsList_draw().
 {
     return fixPriorityList(order, WEP_FIRST, WEP_LAST, WEP_IMPULSE_BEGIN - WEP_FIRST, complete);
 }
W_FixWeaponOrder_AllowIncomplete()
string W_FixWeaponOrder_AllowIncomplete (entity this, string order)
Definition at line 177 of file all.qc.
References W_FixWeaponOrder().
Referenced by GetCvars().
 {
     return W_FixWeaponOrder(order, 0);
 }
W_FixWeaponOrder_BuildImpulseList()
string W_FixWeaponOrder_BuildImpulseList (string o)
Definition at line 162 of file all.qc.
References ftos(), heapsort(), NULL, strcat(), string_null, substring(), W_FixWeaponOrder_BuildImpulseList_buf, W_FixWeaponOrder_BuildImpulseList_cmp(), W_FixWeaponOrder_BuildImpulseList_order, W_FixWeaponOrder_BuildImpulseList_swap(), WEP_FIRST, and WEP_LAST.
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     int i;
     W_FixWeaponOrder_BuildImpulseList_order = o;
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST] = i;
     heapsort(WEP_LAST - WEP_FIRST + 1, W_FixWeaponOrder_BuildImpulseList_swap, W_FixWeaponOrder_BuildImpulseList_cmp,
         NULL);
     o = "";
     for (i = WEP_FIRST; i <= WEP_LAST; ++i)
         o = strcat(o, " ", ftos(W_FixWeaponOrder_BuildImpulseList_buf[i - WEP_FIRST]));
     W_FixWeaponOrder_BuildImpulseList_order = string_null;
     return substring(o, 1, -1);
 }
W_FixWeaponOrder_BuildImpulseList_cmp()
float W_FixWeaponOrder_BuildImpulseList_cmp (int i, int j, entity pass)
Definition at line 150 of file all.qc.
References Weapon::impulse, REGISTRY_GET, strcat(), strstrofs, W_FixWeaponOrder_BuildImpulseList_buf, and W_FixWeaponOrder_BuildImpulseList_order.
Referenced by W_FixWeaponOrder_BuildImpulseList().
 {
     int si = W_FixWeaponOrder_BuildImpulseList_buf[i];
     Weapon e1 = REGISTRY_GET(Weapons, si);
     int sj = W_FixWeaponOrder_BuildImpulseList_buf[j];
     Weapon e2 = REGISTRY_GET(Weapons, sj);
     int d = (e1.impulse + 9) % 10 - (e2.impulse + 9) % 10;
     if (d != 0) return -d;  // high impulse first!
     string s = strcat(" ", W_FixWeaponOrder_BuildImpulseList_order, " ");
     return strstrofs(s, sprintf(" %d ", si), 0)
         - strstrofs(s, sprintf(" %d ", sj), 0); // low char index first!
 }
W_FixWeaponOrder_BuildImpulseList_swap()
void W_FixWeaponOrder_BuildImpulseList_swap (int i, int j, entity pass)
Definition at line 143 of file all.qc.
References W_FixWeaponOrder_BuildImpulseList_buf.
Referenced by W_FixWeaponOrder_BuildImpulseList().
 {
     float h;
     h = W_FixWeaponOrder_BuildImpulseList_buf[i];
     W_FixWeaponOrder_BuildImpulseList_buf[i] = W_FixWeaponOrder_BuildImpulseList_buf[j];
     W_FixWeaponOrder_BuildImpulseList_buf[j] = h;
 }
W_FixWeaponOrder_ForceComplete()
string W_FixWeaponOrder_ForceComplete (string order)
Definition at line 182 of file all.qc.
References cvar_defstring(), W_FixWeaponOrder(), and W_NumberWeaponOrder().
Referenced by HUD_Weapons(), and W_FixWeaponOrder_ForceComplete_AndBuildImpulseList().
 {
     if (order == "") order = W_NumberWeaponOrder(cvar_defstring("cl_weaponpriority"));
     return W_FixWeaponOrder(order, 1);
 }
W_Model()
string W_Model (string w_mdl)
Definition at line 270 of file all.qc.
References alpha, angles, anim_set(), argv(), autocvar_chase_active, autocvar_r_drawviewmodel, CLIENT_COMMAND, CMD_REQUEST_COMMAND, CMD_REQUEST_USAGE, compressShotOrigin(), CSQCModel_server2csqc(), csqcplayer, decompressShotOrigin(), EF_ADDITIVE, EF_FULLBRIGHT, entity(), FOREACH, FOREACH_CLIENT, frame, gettagindex, gettaginfo, IS_REAL_CLIENT, IS_SPEC, LOG_HELP, LOG_INFOF, LOG_WARNF, M_ARGV, MASK_NORMAL, maxs, mins, model, movedir, msg_entity, MSG_ONE, MUTATOR_CALLHOOK, name, NET_HANDLE, nextthink, NULL, oldorigin, owner, player_localentnum, pointparticles, random(), ReadRegistered, realowner, REGISTER_NET_C2S, REGISTER_NET_TEMP, REGISTRY_GET, renderflags, RF_VIEWMODEL, scale, setanim, setmodel, setorigin(), setthink, shotdir, shotorg, spawn(), stov(), strcat(), time, v, vector(), VF_CL_VIEWANGLES, view_ofs, viewmodelforclient, viewmodels, W_GunAlign(), W_Model(), Weapon_whereis(), weaponslot(), WriteByte(), WriteRegistered, WS_DROP, and WS_RAISE.
Referenced by CL_ExteriorWeaponentity_Think(), MDL_GIB_ROBO_RANDOM(), and W_Model().
 {
     string output = strcat("models/weapons/", w_mdl);
     MUTATOR_CALLHOOK(WeaponModel, w_mdl, output);
     return M_ARGV(1, string);
 }
W_NameWeaponOrder()
string W_NameWeaponOrder (string order)
Definition at line 125 of file all.qc.
References mapPriorityList(), and W_NameWeaponOrder_MapFunc().
Referenced by XonoticWeaponsList_draw().
 {
     return mapPriorityList(order, W_NameWeaponOrder_MapFunc);
 }
W_NameWeaponOrder_MapFunc()
string W_NameWeaponOrder_MapFunc (string s)
Definition at line 99 of file all.qc.
References entity(), REGISTRY_GET, and stof().
Referenced by W_NameWeaponOrder().
 {
     int i = stof(s);
     if (s == "0" || i)
     {
         entity wi = REGISTRY_GET(Weapons, i);
         if (wi != WEP_Null) return wi.netname;
     }
     return s;
 }
W_NumberWeaponOrder()
string W_NumberWeaponOrder (string order)
Definition at line 136 of file all.qc.
References mapPriorityList(), and W_NumberWeaponOrder_MapFunc().
Referenced by HUD_Weapons(), LocalCommand_sendcvar(), W_FixWeaponOrder_ForceComplete(), XonoticWeaponsList_draw(), and XonoticWeaponsList_toString().
 {
     return mapPriorityList(order, W_NumberWeaponOrder_MapFunc);
 }
W_NumberWeaponOrder_MapFunc()
string W_NumberWeaponOrder_MapFunc (string s)
Definition at line 129 of file all.qc.
References FOREACH, ftos(), stof(), and W_UndeprecateName().
Referenced by W_NumberWeaponOrder().
 {
     if (s == "0" || stof(s)) return s;
     s = W_UndeprecateName(s);
     FOREACH(Weapons, it != WEP_Null && it.netname == s, return ftos(i));
     return s;
 }
W_RandomWeapons()
WepSet W_RandomWeapons (entity e, WepSet remaining, int n)
Definition at line 188 of file all.qc.
References FOREACH, RandomSelection_AddEnt, RandomSelection_chosen_ent, RandomSelection_Init(), result, and WepSet_FromWeapon.
Referenced by MUTATOR_HOOKFUNCTION().
 {
     WepSet result = '0 0 0';
     for (int j = 0; j < n; ++j)
     {
         RandomSelection_Init();
         FOREACH(Weapons, it != WEP_Null, {
             if (remaining & (it.m_wepset))
                 RandomSelection_AddEnt(it, 1, 1);
         });
         Weapon w = RandomSelection_chosen_ent;
         result |= WepSet_FromWeapon(w);
         remaining &= ~WepSet_FromWeapon(w);
     }
     return result;
 }
W_Sound()
string W_Sound (string w_snd)
Definition at line 263 of file all.qc.
References M_ARGV, MUTATOR_CALLHOOK, and strcat().
Referenced by SND_GRENADE_BOUNCE_RANDOM(), SND_HAGEXP_RANDOM(), SND_NEXWHOOSH_RANDOM(), and SND_RIC_RANDOM().
 {
     string output = strcat("weapons/", w_snd);
     MUTATOR_CALLHOOK(WeaponSound, w_snd, output);
     return M_ARGV(1, string);
 }
W_UndeprecateName()
string W_UndeprecateName (string s)
Definition at line 110 of file all.qc.
Referenced by GiveItems(), spawnfunc(), and W_NumberWeaponOrder_MapFunc().
 {
     switch (s)
     {
         case "nex": return "vortex";
         case "rocketlauncher": return "devastator";
         case "laser": return "blaster";
         case "minstanex": return "vaporizer";
         case "grenadelauncher": return "mortar";
         case "uzi": return "machinegun";
         case "hmg": return "okhmg";
         case "rpc": return "okrpc";
         default: return s;
     }
 }
Variable Documentation
W_FixWeaponOrder_BuildImpulseList_buf
float W_FixWeaponOrder_BuildImpulseList_buf[REGISTRY_MAX(Weapons)]
Definition at line 141 of file all.qc.
Referenced by W_FixWeaponOrder_BuildImpulseList(), W_FixWeaponOrder_BuildImpulseList_cmp(), and W_FixWeaponOrder_BuildImpulseList_swap().
W_FixWeaponOrder_BuildImpulseList_order
string W_FixWeaponOrder_BuildImpulseList_order
Definition at line 142 of file all.qc.
Referenced by W_FixWeaponOrder_BuildImpulseList(), and W_FixWeaponOrder_BuildImpulseList_cmp().