Xonotic: XonoticSoundList Class Reference
XonoticSoundList Class Reference
Public Member Functions
ATTRIB (Item, parent, entity)
ATTRIB (XonoticSoundList, filterString, string)
ATTRIB (XonoticSoundList, playlist, entity)
ATTRIB (Item, tooltip, string)
ATTRIB (ListBox, src, string)
virtual void clickListBoxItem ()
virtual void configureListBox ()
virtual void configureXonoticListBox ()
virtual void configureXonoticSoundList ()
virtual void describe ()
virtual void destroy ()
virtual void display ()
virtual void doubleClickListBoxItem ()
virtual void draw ()
virtual void drawListBoxItem ()
virtual void focusedItemChangeNotify ()
virtual void focusEnter ()
virtual void focusLeave ()
virtual void getFirstFullyVisibleItemAtScrollPos ()
virtual void getItemAtPos ()
virtual void getItemHeight ()
virtual void getItemStart ()
virtual void getLastFullyVisibleItemAtScrollPos ()
virtual void getSounds ()
virtual void getTotalHeight ()
virtual void hideNotify ()
virtual void isScrolling ()
virtual void keyDown ()
virtual void keyUp ()
virtual void mouseDrag ()
virtual void mouseMove ()
virtual void mousePress ()
virtual void mouseRelease ()
virtual void relinquishFocus ()
virtual void resizeNotify ()
virtual void scrollToItem ()
virtual void setFocusedItem ()
virtual void setSelected ()
virtual void showNotify ()
virtual void soundName ()
virtual void toString ()
virtual void updateControlTopBottom ()
Public Attributes
float allowFocusSound = 1
float alphaBG = SKINALPHA_LISTBOX_BACKGROUND
vector color = SKINCOLOR_SCROLLBAR_N
vector color2 = SKINCOLOR_SCROLLBAR_S
vector colorBG = SKINCOLOR_LISTBOX_BACKGROUND
vector colorC = SKINCOLOR_SCROLLBAR_C
vector colorF = SKINCOLOR_SCROLLBAR_F
float columnNameOrigin = 0
float columnNameSize = 0
float columnNumberOrigin = 0
float columnNumberSize = 0
float controlBottom = 0
float controlTop = 0
float controlWidth = 0
vector dragScrollPos = '0 0 0'
float focusable = 1
float focused = 0
int focusedItem = -1
float focusedItemAlpha = 0.3
float fontSize = SKINFONTSIZE_NORMAL
vector itemAbsSize = '0 0 0'
float itemHeight = 0
float lastClickedItem = -1
float lastClickedTime = 0
int listSound = -1
float mouseMoveOffset = -1
float needScrollToItem = -1
float nItems = 42
vector origin = '0 0 0'
float preferredFocusPriority = 0
float pressed = 0
float pressOffset = 0
float previousValue = 0
vector realFontSize = '0 0 0'
float realUpperMargin = 0
float rowsPerItem = 1
float scrollbarWidth = SKINWIDTH_SCROLLBAR
float scrollPos = 0
float scrollPosTarget = 0
int selectedItem = 0
bool selectionDoesntMatter = false
vector size = '0 0 0'
string src = SKINGFX_SCROLLBAR
vector tolerance = SKINTOLERANCE_SLIDER
Detailed Description
Definition at line 4 of file soundlist.qh.
Member Function Documentation
Item::ATTRIB (Item , parent , entity) inherited
XonoticSoundList::ATTRIB (XonoticSoundList , filterString , string)
XonoticSoundList::ATTRIB (XonoticSoundList , playlist , entity)
Item::ATTRIB (Item , tooltip , string) inherited
ListBox::ATTRIB (ListBox , src , string) inherited
virtual void ListBox::clickListBoxItem () virtual inherited
Reimplemented in XonoticGametypeList, and XonoticMapList.
virtual void ListBox::configureListBox () virtual inherited
virtual void XonoticListBox::configureXonoticListBox () virtual inherited
virtual void XonoticSoundList::configureXonoticSoundList () virtual
virtual void Object::describe () inline virtual inherited
Reimplemented in EffectInfo, and Gametype.
Definition at line 287 of file oo.qh.
References cvar(), and TC.
     {
         TC(Object, this);
         string s = _("No description");
         if (cvar("developer"))
         {
             for (int i = 0, n = numentityfields(); i < n; ++i)
             {
                 string value = getentityfieldstring(i, this);
                 if (value != "") s = sprintf("%s\n%s = %s", s, entityfieldname(i), value);
             }
         }
         return s;
     }
virtual void XonoticSoundList::destroy () virtual
Reimplemented from Item.
virtual void Object::display () inline virtual inherited
Reimplemented in Weapon, Gametype, GameItem, Nade, Buff, and Turret.
Definition at line 301 of file oo.qh.
References TC.
     {
         TC(Object, this);
         returns(sprintf("entity %i", this), "nopreview_map");
     }
virtual void XonoticSoundList::doubleClickListBoxItem () virtual
Reimplemented from ListBox.
virtual void ListBox::draw () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticScreenshotList, XonoticHUDSkinList, XonoticPlayList, XonoticWeaponsList, XonoticCampaignList, XonoticCreditsList, XonoticGametypeList, XonoticMapList, and XonoticServerList.
virtual void XonoticSoundList::drawListBoxItem () virtual
Reimplemented from ListBox.
virtual void ListBox::focusedItemChangeNotify () virtual inherited
Reimplemented in XonoticRegisteredSettingsList, XonoticRegisteredSettingsList, XonoticServerList, and XonoticGametypeList.
void Item::focusEnter () virtual inherited
Reimplemented in XonoticServerList, Nexposee, XonoticCreditsDialog, and XonoticWinnerDialog.
Definition at line 94 of file item.qc.
References m_play_focus_sound().
     {
         if (this.allowFocusSound) m_play_focus_sound();
     }
virtual void ListBox::focusLeave () virtual inherited
Reimplemented from Item.
virtual void ListBox::getFirstFullyVisibleItemAtScrollPos () virtual inherited
virtual void ListBox::getItemAtPos () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getItemHeight () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getItemStart () virtual inherited
Reimplemented in XonoticServerList.
virtual void ListBox::getLastFullyVisibleItemAtScrollPos () virtual inherited
virtual void XonoticSoundList::getSounds () virtual
virtual void ListBox::getTotalHeight () virtual inherited
Reimplemented in XonoticServerList.
void Item::hideNotify () virtual inherited
Reimplemented in Container, and XonoticCvarList.
Definition at line 59 of file item.qc.
     {}
virtual void ListBox::isScrolling () virtual inherited
virtual void XonoticSoundList::keyDown () virtual
Reimplemented from ListBox.
void Item::keyUp () virtual inherited
Reimplemented in Slider, Container, and Nexposee.
Definition at line 67 of file item.qc.
     {
         return 0;  // unhandled
     }
virtual void ListBox::mouseDrag () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticPlayList, and XonoticWeaponsList.
virtual void ListBox::mouseMove () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticServerList.
virtual void ListBox::mousePress () virtual inherited
Reimplemented from Item.
virtual void ListBox::mouseRelease () virtual inherited
Reimplemented from Item.
Reimplemented in XonoticCvarList.
void Item::relinquishFocus () virtual inherited
Definition at line 11 of file item.qc.
References entity(), NULL, and parent.
     {
         entity par = this.parent;
         if (!par) return;
         if (par.instanceOfContainer) par.setFocus(par, NULL);
     }
virtual void XonoticSoundList::resizeNotify () virtual
Reimplemented from XonoticListBox.
virtual void ListBox::scrollToItem () virtual inherited
virtual void ListBox::setFocusedItem () virtual inherited
virtual void ListBox::setSelected () virtual inherited
Reimplemented in XonoticServerList, XonoticRegisteredSettingsList, XonoticCvarList, XonoticCampaignList, XonoticKeyBinder, XonoticGametypeList, XonoticLanguageList, and XonoticScreenshotList.
virtual void XonoticSoundList::showNotify () virtual
Reimplemented from Item.
virtual void XonoticSoundList::soundName () virtual
void Item::toString () virtual inherited
Reimplemented in Slider, Label, CheckBox, Image, XonoticWeaponsList, and XonoticMutatorsDialog.
Definition at line 102 of file item.qc.
References string_null.
     {
         return string_null;
     }
virtual void ListBox::updateControlTopBottom () virtual inherited
Member Data Documentation
float ListBox::allowFocusSound = 1 inherited
Definition at line 19 of file listbox.qh.
float XonoticListBox::alphaBG = SKINALPHA_LISTBOX_BACKGROUND inherited
Definition at line 17 of file listbox.qh.
vector XonoticListBox::color = SKINCOLOR_SCROLLBAR_N inherited
Definition at line 12 of file listbox.qh.
vector XonoticListBox::color2 = SKINCOLOR_SCROLLBAR_S inherited
Definition at line 14 of file listbox.qh.
vector XonoticListBox::colorBG = SKINCOLOR_LISTBOX_BACKGROUND inherited
Definition at line 16 of file listbox.qh.
vector XonoticListBox::colorC = SKINCOLOR_SCROLLBAR_C inherited
Definition at line 15 of file listbox.qh.
vector XonoticListBox::colorF = SKINCOLOR_SCROLLBAR_F inherited
Definition at line 13 of file listbox.qh.
float XonoticSoundList::columnNameOrigin = 0
Definition at line 18 of file soundlist.qh.
float XonoticSoundList::columnNameSize = 0
Definition at line 19 of file soundlist.qh.
float XonoticSoundList::columnNumberOrigin = 0
Definition at line 20 of file soundlist.qh.
float XonoticSoundList::columnNumberSize = 0
Definition at line 21 of file soundlist.qh.
float ListBox::controlBottom = 0 inherited
Definition at line 34 of file listbox.qh.
float ListBox::controlTop = 0 inherited
Definition at line 33 of file listbox.qh.
float ListBox::controlWidth = 0 inherited
Definition at line 35 of file listbox.qh.
vector ListBox::dragScrollPos = '0 0 0' inherited
Definition at line 36 of file listbox.qh.
float ListBox::focusable = 1 inherited
Definition at line 14 of file listbox.qh.
float Item::focused = 0 inherited
Definition at line 22 of file item.qh.
int ListBox::focusedItem = -1 inherited
Definition at line 15 of file listbox.qh.
float ListBox::focusedItemAlpha = 0.3 inherited
Definition at line 16 of file listbox.qh.
float XonoticListBox::fontSize = SKINFONTSIZE_NORMAL inherited
Definition at line 6 of file listbox.qh.
vector XonoticSoundList::itemAbsSize = '0 0 0'
Definition at line 24 of file soundlist.qh.
float ListBox::itemHeight = 0 inherited
Definition at line 47 of file listbox.qh.
float ListBox::lastClickedItem = -1 inherited
Definition at line 52 of file listbox.qh.
float ListBox::lastClickedTime = 0 inherited
Definition at line 53 of file listbox.qh.
int XonoticSoundList::listSound = -1
Definition at line 16 of file soundlist.qh.
float ListBox::mouseMoveOffset = -1 inherited
Definition at line 18 of file listbox.qh.
float ListBox::needScrollToItem = -1 inherited
Definition at line 26 of file listbox.qh.
float ListBox::nItems = 42 inherited
Definition at line 46 of file listbox.qh.
vector XonoticSoundList::origin = '0 0 0'
Definition at line 23 of file soundlist.qh.
float Item::preferredFocusPriority = 0 inherited
Definition at line 26 of file item.qh.
float ListBox::pressed = 0 inherited
Definition at line 29 of file listbox.qh.
float ListBox::pressOffset = 0 inherited
Definition at line 30 of file listbox.qh.
float ListBox::previousValue = 0 inherited
Definition at line 28 of file listbox.qh.
vector XonoticSoundList::realFontSize = '0 0 0'
Definition at line 17 of file soundlist.qh.
float XonoticSoundList::realUpperMargin = 0
Definition at line 22 of file soundlist.qh.
float XonoticSoundList::rowsPerItem = 1
Definition at line 6 of file soundlist.qh.
float XonoticListBox::scrollbarWidth = SKINWIDTH_SCROLLBAR inherited
Definition at line 7 of file listbox.qh.
float ListBox::scrollPos = 0 inherited
Definition at line 23 of file listbox.qh.
float ListBox::scrollPosTarget = 0 inherited
Definition at line 24 of file listbox.qh.
int ListBox::selectedItem = 0 inherited
Definition at line 20 of file listbox.qh.
bool ListBox::selectionDoesntMatter = false inherited
Definition at line 37 of file listbox.qh.
vector ListBox::size = '0 0 0' inherited
Definition at line 21 of file listbox.qh.
string XonoticListBox::src = SKINGFX_SCROLLBAR inherited
Definition at line 8 of file listbox.qh.
vector XonoticListBox::tolerance = SKINTOLERANCE_SLIDER inherited
Definition at line 9 of file listbox.qh.
The documentation for this class was generated from the following file:
menu/xonotic/soundlist.qh