Xonotic: server/g_subs.qc File Reference
g_subs.qc File Reference
#include "g_subs.qh"
#include "antilag.qh"
#include "command/common.qh"
#include "../lib/warpzone/common.qh"
#include "../common/triggers/subs.qh"
Functions
spawnfunc (info_null)
void main ()
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
float tracebox_inverted (vector v1, vector mi, vector ma, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
void traceline_inverted (vector v1, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
vector findbetterlocation (vector org, float mindist)
float LOD_customize ()
void LOD_uncustomize ()
void LODmodel_attach ()
void ApplyMinMaxScaleAngles (entity e)
void SetBrushEntityModel ()
void SetBrushEntityModelNoLOD ()
void SetMovedir (entity this)
void InitTrigger ()
void InitSolidBSPTrigger ()
float InitMovingBrushTrigger ()
Function Documentation
void ApplyMinMaxScaleAngles (entity e)
Definition at line 327 of file g_subs.qc.
References max(), SELFPARAM, and vlen().
Referenced by SetBrushEntityModel(), and SetBrushEntityModelNoLOD().
 {SELFPARAM();
     if(e.angles.x != 0 || e.angles.z != 0 || self.avelocity.x != 0 || self.avelocity.z != 0) // "weird" rotation
     {
         e.maxs = '1 1 1' * vlen(
             '1 0 0' * max(-e.mins.x, e.maxs.x) +
             '0 1 0' * max(-e.mins.y, e.maxs.y) +
             '0 0 1' * max(-e.mins.z, e.maxs.z)
         );
         e.mins = -e.maxs;
     }
     else if(e.angles.y != 0 || self.avelocity.y != 0) // yaw only is a bit better
     {
         e.maxs_x = vlen(
             '1 0 0' * max(-e.mins.x, e.maxs.x) +
             '0 1 0' * max(-e.mins.y, e.maxs.y)
         );
         e.maxs_y = e.maxs.x;
         e.mins_x = -e.maxs.x;
         e.mins_y = -e.maxs.x;
     }
     if(e.scale)
         setsize(e, e.mins * e.scale, e.maxs * e.scale);
     else
         setsize(e, e.mins, e.maxs);
 }
vector findbetterlocation (vector org, float mindist)
Definition at line 204 of file g_subs.qc.
References trace_endpos, trace_fraction, vector(), and world.
 {
     vector  loc;
     vector vec;
     float c, h;
     vec = mindist * '1 0 0';
     c = 0;
     while (c < 6)
     {
         traceline (org, org + vec, true, world);
         vec = vec * -1;
         if (trace_fraction < 1)
         {
             loc = trace_endpos;
             traceline (loc, loc + vec, true, world);
             if (trace_fraction >= 1)
                 org = loc + vec;
         }
         if (c & 1)
         {
             h = vec.y;
             vec.y = vec.x;
             vec.x = vec.z;
             vec.z = h;
         }
         c = c + 1;
     }
     return org;
 }
float InitMovingBrushTrigger ()
Definition at line 436 of file g_subs.qc.
References modelindex, MOVETYPE_PUSH, objerror, SELFPARAM, SetBrushEntityModel(), and SOLID_BSP.
 {SELFPARAM();
 // trigger angles are used for one-way touches.  An angle of 0 is assumed
 // to mean no restrictions, so use a yaw of 360 instead.
     self.solid = SOLID_BSP;
     SetBrushEntityModel();
     self.movetype = MOVETYPE_PUSH;
     if(self.modelindex == 0)
     {
         objerror("InitMovingBrushTrigger: no brushes found!");
         return 0;
     }
     return 1;
 }
void InitSolidBSPTrigger ()
Definition at line 424 of file g_subs.qc.
References MOVETYPE_NONE, SELFPARAM, SetBrushEntityModel(), SetMovedir(), and SOLID_BSP.
 {SELFPARAM();
 // trigger angles are used for one-way touches.  An angle of 0 is assumed
 // to mean no restrictions, so use a yaw of 360 instead.
     SetMovedir(self);
     self.solid = SOLID_BSP;
     SetBrushEntityModel();
     self.movetype = MOVETYPE_NONE; // why was this PUSH? -div0
 //  self.modelindex = 0;
     self.model = "";
 }
void InitTrigger ()
Definition at line 412 of file g_subs.qc.
References MOVETYPE_NONE, SELFPARAM, SetBrushEntityModel(), SetMovedir(), and SOLID_TRIGGER.
Referenced by spawnfunc().
 {SELFPARAM();
 // trigger angles are used for one-way touches.  An angle of 0 is assumed
 // to mean no restrictions, so use a yaw of 360 instead.
     SetMovedir(self);
     self.solid = SOLID_TRIGGER;
     SetBrushEntityModel();
     self.movetype = MOVETYPE_NONE;
     self.modelindex = 0;
     self.model = "";
 }
float LOD_customize ()
Definition at line 236 of file g_subs.qc.
References autocvar_loddebug, lodmodelindex2, NearestPointOnBox(), other, SELFPARAM, vdist, and vector().
Referenced by LODmodel_attach().
 {SELFPARAM();
     if(autocvar_loddebug)
     {
         int d = autocvar_loddebug;
         if(d == 1)
             self.modelindex = self.lodmodelindex0;
         else if(d == 2 || !self.lodmodelindex2)
             self.modelindex = self.lodmodelindex1;
         else // if(d == 3)
             self.modelindex = self.lodmodelindex2;
         return true;
     }
     // TODO csqc network this so it only gets sent once
     vector near_point = NearestPointOnBox(self, other.origin);
     if(vdist(near_point - other.origin, <, self.loddistance1))
         self.modelindex = self.lodmodelindex0;
     else if(!self.lodmodelindex2 || vdist(near_point - other.origin, <, self.loddistance2))
         self.modelindex = self.lodmodelindex1;
     else
         self.modelindex = self.lodmodelindex2;
     return true;
 }
void LOD_uncustomize ()
Definition at line 262 of file g_subs.qc.
References SELFPARAM.
Referenced by LODmodel_attach().
 {SELFPARAM();
     self.modelindex = self.lodmodelindex0;
 }
void LODmodel_attach ()
Definition at line 267 of file g_subs.qc.
References autocvar_loddebug, entity(), find(), LOD_customize(), LOD_uncustomize(), loddistance1, loddistance2, lodmodel1, lodmodel2, lodmodelindex1, lodtarget1, lodtarget2, SELFPARAM, SetCustomizer(), targetname, vector(), and world.
Referenced by SetBrushEntityModel().
 {SELFPARAM();
     entity e;
     if(!self.loddistance1)
         self.loddistance1 = 1000;
     if(!self.loddistance2)
         self.loddistance2 = 2000;
     self.lodmodelindex0 = self.modelindex;
     if(self.lodtarget1 != "")
     {
         e = find(world, targetname, self.lodtarget1);
         if(e)
         {
             self.lodmodel1 = e.model;
             remove(e);
         }
     }
     if(self.lodtarget2 != "")
     {
         e = find(world, targetname, self.lodtarget2);
         if(e)
         {
             self.lodmodel2 = e.model;
             remove(e);
         }
     }
     if(autocvar_loddebug < 0)
     {
         self.lodmodel1 = self.lodmodel2 = ""; // don't even initialize
     }
     if(self.lodmodel1 != "")
     {
         vector mi, ma;
         mi = self.mins;
         ma = self.maxs;
         precache_model(self.lodmodel1);
         _setmodel(self, self.lodmodel1);
         self.lodmodelindex1 = self.modelindex;
         if(self.lodmodel2 != "")
         {
             precache_model(self.lodmodel2);
             _setmodel(self, self.lodmodel2);
             self.lodmodelindex2 = self.modelindex;
         }
         self.modelindex = self.lodmodelindex0;
         setsize(self, mi, ma);
     }
     if(self.lodmodelindex1)
         if (!self.SendEntity)
             SetCustomizer(self, LOD_customize, LOD_uncustomize);
 }
void main ()
Definition at line 21 of file g_subs.qc.
 {
 }
void SetBrushEntityModel ()
Definition at line 354 of file g_subs.qc.
References ApplyMinMaxScaleAngles(), InitializeEntity(), INITPRIO_FINDTARGET, LODmodel_attach(), maxs, mins, model, origin, SELFPARAM, and vector().
Referenced by InitMovingBrushTrigger(), InitSolidBSPTrigger(), and InitTrigger().
 {SELFPARAM();
     if(self.model != "")
     {
         precache_model(self.model);
         if(self.mins != '0 0 0' || self.maxs != '0 0 0')
         {
             vector mi = self.mins;
             vector ma = self.maxs;
             _setmodel(self, self.model); // no precision needed
             setsize(self, mi, ma);
         }
         else
             _setmodel(self, self.model); // no precision needed
         InitializeEntity(self, LODmodel_attach, INITPRIO_FINDTARGET);
     }
     setorigin(self, self.origin);
     ApplyMinMaxScaleAngles(self);
 }
void SetBrushEntityModelNoLOD ()
Definition at line 374 of file g_subs.qc.
References ApplyMinMaxScaleAngles(), maxs, mins, model, origin, SELFPARAM, and vector().
 {SELFPARAM();
     if(self.model != "")
     {
         precache_model(self.model);
         if(self.mins != '0 0 0' || self.maxs != '0 0 0')
         {
             vector mi = self.mins;
             vector ma = self.maxs;
             _setmodel(self, self.model); // no precision needed
             setsize(self, mi, ma);
         }
         else
             _setmodel(self, self.model); // no precision needed
     }
     setorigin(self, self.origin);
     ApplyMinMaxScaleAngles(self);
 }
void SetMovedir (entity this)
Definition at line 399 of file g_subs.qc.
References angles, movedir, normalize(), and v_forward.
Referenced by InitSolidBSPTrigger(), and InitTrigger().
 {
     if(this.movedir != '0 0 0')
         this.movedir = normalize(this.movedir);
     else
     {
         makevectors(this.angles);
         this.movedir = v_forward;
     }
     this.angles = '0 0 0';
 }
spawnfunc (info_null)
Definition at line 8 of file g_subs.qc.
 {
     remove(self);
     // if anything breaks, tell the mapper to fix his map! info_null is meant to remove itself immediately.
 }
void tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 89 of file g_subs.qc.
References autocvar_g_antilag, and tracebox_antilag_force_wz().
Referenced by W_SetupShot_Dir_ProjectileSize_Range().
 {
     if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
         lag = 0;
     tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, false);
 }
void tracebox_antilag_force_wz (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag, float wz)
Definition at line 36 of file g_subs.qc.
References antilag_restore(), antilag_takeback(), DPCONTENTS_BODY, DPCONTENTS_CORPSE, DPCONTENTS_SOLID, FL_MONSTER, flags, FOREACH_CLIENT, FOREACH_ENTITY_FLAGS, IS_PLAYER, IS_REAL_CLIENT, LAMBDA, time, and WarpZone_TraceBox().
Referenced by tracebox_antilag(), traceline_antilag_force(), WarpZone_tracebox_antilag(), and WarpZone_traceline_antilag_force().
 {
     // check whether antilagged traces are enabled
     if (lag < 0.001)
         lag = 0;
     if (!IS_REAL_CLIENT(forent))
         lag = 0; // only antilag for clients
     // change shooter to SOLID_BBOX so the shot can hit corpses
     int oldsolid = source.dphitcontentsmask;
     if(source)
         source.dphitcontentsmask = DPCONTENTS_SOLID | DPCONTENTS_BODY | DPCONTENTS_CORPSE;
     if (lag)
     {
         // take players back into the past
         FOREACH_CLIENT(IS_PLAYER(it) && it != forent, LAMBDA(antilag_takeback(it, time - lag)));
         FOREACH_ENTITY_FLAGS(flags, FL_MONSTER, LAMBDA(
             if(it != forent)
                 antilag_takeback(it, time - lag);
         ));
     }
     // do the trace
     if(wz)
         WarpZone_TraceBox (v1, mi, ma, v2, nomonst, forent);
     else
         tracebox (v1, mi, ma, v2, nomonst, forent);
     // restore players to current positions
     if (lag)
     {
         FOREACH_CLIENT(IS_PLAYER(it) && it != forent, LAMBDA(antilag_restore(it)));
         FOREACH_ENTITY_FLAGS(flags, FL_MONSTER, LAMBDA(
             if(it != forent)
                 antilag_restore(it);
         ));
     }
     // restore shooter solid type
     if(source)
         source.dphitcontentsmask = oldsolid;
 }
float tracebox_inverted (vector v1, vector mi, vector ma, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
Definition at line 112 of file g_subs.qc.
References entity(), ftos(), LOG_TRACE(), normalize(), trace_endpos, trace_ent, trace_fraction, trace_startsolid, vector(), vlen(), and vtos().
Referenced by FullTraceFraction(), and traceline_inverted().
 {
     vector pos, dir, t;
     float nudge;
     entity stopentity;
     //nudge = 2 * cvar("collision_impactnudge"); // why not?
     nudge = 0.5;
     dir = normalize(v2 - v1);
     pos = v1 + dir * nudge;
     float c;
     c = 0;
     for (;;)
     {
         if(pos * dir >= v2 * dir)
         {
             // went too far
             trace_fraction = 1;
             trace_endpos = v2;
             return c;
         }
         tracebox(pos, mi, ma, v2, nomonsters, forent);
         ++c;
         if(c == 50)
         {
             LOG_TRACE("HOLY SHIT! When tracing from ", vtos(v1), " to ", vtos(v2), "\n");
             LOG_TRACE("  Nudging gets us nowhere at ", vtos(pos), "\n");
             LOG_TRACE("  trace_endpos is ", vtos(trace_endpos), "\n");
             LOG_TRACE("  trace distance is ", ftos(vlen(pos - trace_endpos)), "\n");
         }
         stopentity = trace_ent;
         if(trace_startsolid)
         {
             // we started inside solid.
             // then trace from endpos to pos
             t = trace_endpos;
             tracebox(t, mi, ma, pos, nomonsters, forent);
             ++c;
             if(trace_startsolid)
             {
                 // t is still inside solid? bad
                 // force advance, then, and retry
                 pos = t + dir * nudge;
                 // but if we hit an entity, stop RIGHT before it
                 if(stopatentity && stopentity && stopentity != ignorestopatentity)
                 {
                     trace_ent = stopentity;
                     trace_endpos = t;
                     trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
                     return c;
                 }
             }
             else
             {
                 // we actually LEFT solid!
                 trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
                 return c;
             }
         }
         else
         {
             // pos is outside solid?!? but why?!? never mind, just return it.
             trace_endpos = pos;
             trace_fraction = ((trace_endpos - v1) * dir) / ((v2 - v1) * dir);
             return c;
         }
     }
 }
void traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 83 of file g_subs.qc.
References autocvar_g_antilag, and traceline_antilag_force().
Referenced by crosshair_trace().
 {
     if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
         lag = 0;
     traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
void traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 79 of file g_subs.qc.
References tracebox_antilag_force_wz().
Referenced by traceline_antilag(), W_HitPlotAnalysis(), and W_SetupShot_Dir_ProjectileSize_Range().
 {
     tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, false);
 }
void traceline_inverted (vector v1, vector v2, float nomonsters, entity forent, float stopatentity, entity ignorestopatentity)
Definition at line 190 of file g_subs.qc.
References tracebox_inverted().
Referenced by fireBullet().
 {
     tracebox_inverted(v1, '0 0 0', '0 0 0', v2, nomonsters, forent, stopatentity, ignorestopatentity);
 }
void WarpZone_tracebox_antilag (entity source, vector v1, vector mi, vector ma, vector v2, float nomonst, entity forent, float lag)
Definition at line 105 of file g_subs.qc.
References autocvar_g_antilag, and tracebox_antilag_force_wz().
 {
     if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
         lag = 0;
     tracebox_antilag_force_wz(source, v1, mi, ma, v2, nomonst, forent, lag, true);
 }
void WarpZone_traceline_antilag (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 99 of file g_subs.qc.
References autocvar_g_antilag, and WarpZone_traceline_antilag_force().
Referenced by FireRailgunBullet(), W_SetupShot_Dir_ProjectileSize_Range(), and WarpZone_crosshair_trace().
 {
     if (autocvar_g_antilag != 2 || source.cvar_cl_noantilag)
         lag = 0;
     WarpZone_traceline_antilag_force(source, v1, v2, nomonst, forent, lag);
 }
void WarpZone_traceline_antilag_force (entity source, vector v1, vector v2, float nomonst, entity forent, float lag)
Definition at line 95 of file g_subs.qc.
References tracebox_antilag_force_wz().
Referenced by WarpZone_traceline_antilag().
 {
     tracebox_antilag_force_wz(source, v1, '0 0 0', '0 0 0', v2, nomonst, forent, lag, true);
 }