Xonotic: menu/xonotic/languagelist.qc File Reference
languagelist.qc File Reference
#include "languagelist.qh"
#include "../item/modalcontroller.qh"
#include "mainwindow.qh"
Functions
entity makeXonoticLanguageList ()
void SetLanguage_Click (entity btn, entity me)
void XonoticLanguageList_configureXonoticLanguageList (entity me)
void XonoticLanguageList_destroy (entity me)
void XonoticLanguageList_doubleClickListBoxItem (entity me, float i, vector where)
void XonoticLanguageList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
void XonoticLanguageList_getLanguages (entity me)
float XonoticLanguageList_keyDown (entity me, float scan, float ascii, float shift)
string XonoticLanguageList_languageParameter (entity me, float i, float key)
void XonoticLanguageList_loadCvars (entity me)
void XonoticLanguageList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
void XonoticLanguageList_saveCvars (entity me)
void XonoticLanguageList_setLanguage (entity me)
void XonoticLanguageList_setSelected (entity me, float i)
Variables
const float LANGPARM_COUNT = 4
const float LANGPARM_ID = 0
const float LANGPARM_NAME = 1
const float LANGPARM_NAME_LOCALIZED = 2
const float LANGPARM_PERCENTAGE = 3
Function Documentation
entity makeXonoticLanguageList ()
Definition at line 12 of file languagelist.qc.
References entity(), and NEW.
Referenced by XonoticFirstRunDialog_fill(), and XonoticUserSettingsTab_fill().
 {
     entity me;
     me = NEW(XonoticLanguageList);
     me.configureXonoticLanguageList(me);
     return me;
 }
void SetLanguage_Click (entity btn, entity me)
Definition at line 182 of file languagelist.qc.
Referenced by XonoticUserSettingsTab_fill().
 {
     me.setLanguage(me);
 }
void XonoticLanguageList_configureXonoticLanguageList (entity me)
Definition at line 20 of file languagelist.qc.
 {
     me.configureXonoticListBox(me);
     me.getLanguages(me);
     me.loadCvars(me);
 }
void XonoticLanguageList_destroy (entity me)
Definition at line 133 of file languagelist.qc.
 {
     buf_del(me.languagelist);
 }
void XonoticLanguageList_doubleClickListBoxItem (entity me, float i, vector where)
Definition at line 115 of file languagelist.qc.
References m_play_click_sound(), and MENU_SOUND_EXECUTE.
 {
     m_play_click_sound(MENU_SOUND_EXECUTE);
     me.setLanguage(me);
 }
void XonoticLanguageList_drawListBoxItem (entity me, int i, vector absSize, bool isSelected, bool isFocused)
Definition at line 27 of file languagelist.qc.
References draw_CondensedFontFactor(), draw_Fill(), draw_fontscale, draw_Text(), draw_TextWidth(), eX, eY, getFadedAlpha(), LANGPARM_NAME_LOCALIZED, LANGPARM_PERCENTAGE, p, and vector().
 {
     string s, p;
     if(isSelected)
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_SELECTED, SKINALPHA_LISTBOX_SELECTED);
     else if(isFocused)
     {
         me.focusedItemAlpha = getFadedAlpha(me.focusedItemAlpha, SKINALPHA_LISTBOX_FOCUSED, SKINFADEALPHA_LISTBOX_FOCUSED);
         draw_Fill('0 0 0', '1 1 0', SKINCOLOR_LISTBOX_FOCUSED, me.focusedItemAlpha);
     }
     s = me.languageParameter(me, i, LANGPARM_NAME_LOCALIZED);
     vector save_fontscale = draw_fontscale;
     float f = draw_CondensedFontFactor(s, false, me.realFontSize, 1);
     draw_fontscale.x *= f;
     vector fs = me.realFontSize;
     fs.x *= f;
     draw_Text(me.realUpperMargin * eY + me.columnNameOrigin * eX, s, fs, SKINCOLOR_TEXT, SKINALPHA_TEXT, 0);
     draw_fontscale = save_fontscale;
     p = me.languageParameter(me, i, LANGPARM_PERCENTAGE);
     if(p != "")
     {
         vector save_fontscale = draw_fontscale;
         float f = draw_CondensedFontFactor(p, false, me.realFontSize, 1);
         draw_fontscale.x *= f;
         vector fs = me.realFontSize;
         fs.x *= f;
         draw_Text(me.realUpperMargin * eY + (me.columnPercentageOrigin + (me.columnPercentageSize - draw_TextWidth(p, 0, fs))) * eX, p, fs, SKINCOLOR_TEXT, SKINALPHA_TEXT, 0);
         draw_fontscale = save_fontscale;
     }
 }
void XonoticLanguageList_getLanguages (entity me)
Definition at line 138 of file languagelist.qc.
References argv(), buf_create, fclose(), fgets(), FILE_READ, fopen(), LANGPARM_COUNT, LANGPARM_ID, LANGPARM_NAME, LANGPARM_NAME_LOCALIZED, LANGPARM_PERCENTAGE, and tokenize_console.
 {
     float buf, i, n, fh;
     string s;
     buf = buf_create();
     fh = fopen("languages.txt", FILE_READ);
     i = 0;
     while((s = fgets(fh)))
     {
         n = tokenize_console(s);
         if(n < 3)
             continue;
         bufstr_set(buf, i * LANGPARM_COUNT + LANGPARM_ID, argv(0));
         bufstr_set(buf, i * LANGPARM_COUNT + LANGPARM_NAME, argv(1));
         bufstr_set(buf, i * LANGPARM_COUNT + LANGPARM_NAME_LOCALIZED, argv(2));
         string percent = argv(3);
         if(percent && percent != "100%")
             bufstr_set(buf, i * LANGPARM_COUNT + LANGPARM_PERCENTAGE, percent);
         ++i;
     }
     fclose(fh);
     me.languagelist = buf;
     me.nItems = i;
 }
float XonoticLanguageList_keyDown (entity me, float scan, float ascii, float shift)
Definition at line 121 of file languagelist.qc.
References K_ENTER, K_KP_ENTER, m_play_click_sound(), MENU_SOUND_EXECUTE, and SUPER.
 {
     if(scan == K_ENTER || scan == K_KP_ENTER)
     {
         m_play_click_sound(MENU_SOUND_EXECUTE);
         me.setLanguage(me);
         return 1;
     }
     else
         return SUPER(XonoticLanguageList).keyDown(me, scan, ascii, shift);
 }
string XonoticLanguageList_languageParameter (entity me, float i, float key)
Definition at line 177 of file languagelist.qc.
References LANGPARM_COUNT.
 {
     return bufstr_get(me.languagelist, i * LANGPARM_COUNT + key);
 }
void XonoticLanguageList_loadCvars (entity me)
Definition at line 79 of file languagelist.qc.
References cvar_string(), LANGPARM_ID, and SUPER.
 {
     string s;
     float i, n;
     s = cvar_string("_menu_prvm_language");
     n = me.nItems;
     // default to English
     for(i = 0; i < n; ++i)
     {
         if(me.languageParameter(me, i, LANGPARM_ID) == "en")
         {
             SUPER(XonoticLanguageList).setSelected(me, i);
             break;
         }
     }
     // otherwise, find the language
     for(i = 0; i < n; ++i)
     {
         if(me.languageParameter(me, i, LANGPARM_ID) == s)
         {
             SUPER(XonoticLanguageList).setSelected(me, i);
             break;
         }
     }
     // save it off (turning anything unknown into "en")
     me.saveCvars(me);
 }
void XonoticLanguageList_resizeNotify (entity me, vector relOrigin, vector relSize, vector absOrigin, vector absSize)
Definition at line 61 of file languagelist.qc.
References SUPER.
 {
     SUPER(XonoticLanguageList).resizeNotify(me, relOrigin, relSize, absOrigin, absSize);
     me.realFontSize_y = me.fontSize / (absSize.y * me.itemHeight);
     me.realFontSize_x = me.fontSize / (absSize.x * (1 - me.controlWidth));
     me.realUpperMargin = 0.5 * (1 - me.realFontSize.y);
     me.columnPercentageSize = me.realFontSize.x * 3;
     me.columnPercentageOrigin = 1 - me.columnPercentageSize;
     me.columnNameOrigin = 0;
     me.columnNameSize = me.columnPercentageOrigin;
 }
void XonoticLanguageList_saveCvars (entity me)
Definition at line 110 of file languagelist.qc.
References cvar_set(), and LANGPARM_ID.
 {
     cvar_set("_menu_prvm_language", me.languageParameter(me, me.selectedItem, LANGPARM_ID));
 }
void XonoticLanguageList_setLanguage (entity me)
Definition at line 166 of file languagelist.qc.
References cvar_string(), DialogOpenButton_Click(), GAME_CONNECTED, gamestatus, localcmd, main, and prvm_language.
 {
     if(prvm_language != cvar_string("_menu_prvm_language"))
     {
         if(!(gamestatus & GAME_CONNECTED))
             localcmd("\nprvm_language \"$_menu_prvm_language\"; menu_restart; menu_cmd languageselect\n");
         else
             DialogOpenButton_Click(me, main.languageWarningDialog);
     }
 }
void XonoticLanguageList_setSelected (entity me, float i)
Definition at line 73 of file languagelist.qc.
References SUPER.
 {
     SUPER(XonoticLanguageList).setSelected(me, i);
     me.saveCvars(me);
 }
Variable Documentation
const float LANGPARM_COUNT = 4
Definition at line 10 of file languagelist.qc.
Referenced by XonoticLanguageList_getLanguages(), and XonoticLanguageList_languageParameter().
const float LANGPARM_ID = 0
Definition at line 6 of file languagelist.qc.
Referenced by XonoticLanguageList_getLanguages(), XonoticLanguageList_loadCvars(), and XonoticLanguageList_saveCvars().
const float LANGPARM_NAME = 1
Definition at line 7 of file languagelist.qc.
Referenced by XonoticLanguageList_getLanguages().
const float LANGPARM_NAME_LOCALIZED = 2
Definition at line 8 of file languagelist.qc.
Referenced by XonoticLanguageList_drawListBoxItem(), and XonoticLanguageList_getLanguages().
const float LANGPARM_PERCENTAGE = 3
Definition at line 9 of file languagelist.qc.
Referenced by XonoticLanguageList_drawListBoxItem(), and XonoticLanguageList_getLanguages().