Xonotic: lib/urllib.qh File Reference
urllib.qh File Reference
Macros
#define MIN_URL_ID URI_GET_URLLIB
#define NUM_URL_ID (URI_GET_URLLIB_END - URI_GET_URLLIB + 1)
Typedefs
using url_ready_func = void(entity handle, entity pass, float status)
Functions
ERASEABLE void url_fclose (entity e)
ERASEABLE string url_fgets (entity e)
ERASEABLE void url_fputs (entity e, string s)
ERASEABLE void url_multi_fopen (string url, float mode, url_ready_func rdy, entity pass)
ERASEABLE void url_single_fopen (string url, float mode, url_ready_func rdy, entity pass)
ERASEABLE float url_URI_Get_Callback (int id, float status, string data)
Variables
const int URI_GET_CURL = 17
const int URI_GET_CURL_END = 32
const int URI_GET_DISCARD = 0
const int URI_GET_IPBAN = 1
const int URI_GET_IPBAN_END = 16
const int URI_GET_UPDATENOTIFICATION = 33
const int URI_GET_URLLIB = 128
const int URI_GET_URLLIB_END = 191
const float URL_READY_CANREAD = 2
const float URL_READY_CANWRITE = 1
const float URL_READY_CLOSED = 0
const float URL_READY_ERROR = -1
Macro Definition Documentation
#define MIN_URL_ID URI_GET_URLLIB
Definition at line 32 of file urllib.qh.
Referenced by url_fclose(), url_single_fopen(), and url_URI_Get_Callback().
#define NUM_URL_ID (URI_GET_URLLIB_END - URI_GET_URLLIB + 1)
Definition at line 33 of file urllib.qh.
Referenced by url_fclose(), url_single_fopen(), and url_URI_Get_Callback().
Typedef Documentation
using url_ready_func = void (entity handle, entity pass, float status)
Definition at line 18 of file urllib.qh.
Function Documentation
ERASEABLE void url_fclose (entity e)
Definition at line 207 of file urllib.qc.
References autocvar__urllib_nextslot, cvar_set(), error, fclose(), ftos(), LOG_INFO, MIN_URL_ID, NULL, NUM_URL_ID, strfree, URL_FH_CURL, URL_FH_STDOUT, url_fromid, URL_READY_CLOSED, and URL_READY_ERROR.
Referenced by MX_JLF_(), MX_Messages_(), MX_Nick_(), MX_Say_(), MX_Sync_(), MX_Typing_(), and WeaponStats_ready().
 {
     int i;
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_rbuf == -1 || e.url_wbuf != -1)     // not(post GET/POST request)
             if (e.url_rbuf != -1 || e.url_wbuf == -1) // not(pre POST request)
                 error("url_fclose: not closable in current state");
         // closing an URL!
         if (e.url_wbuf >= 0)
         {
             // we are closing the write end (HTTP POST request)
             // get slot for HTTP request
             for (i = autocvar__urllib_nextslot; i < NUM_URL_ID; ++i)
                 if (url_fromid[i] == NULL) break;
             if (i >= NUM_URL_ID)
             {
                 for (i = 0; i < autocvar__urllib_nextslot; ++i)
                     if (url_fromid[i] == NULL) break;
                 if (i >= autocvar__urllib_nextslot)
                 {
                     LOG_INFO("url_fclose: too many concurrent requests");
                     e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
                     buf_del(e.url_wbuf);
                     strfree(e.url_url);
                     delete(e);
                     return;
                 }
             }
             // POST the data
             if (!crypto_uri_postbuf(e.url_url, i + MIN_URL_ID, e.url_content_type, e.url_verb, e.url_wbuf, 0))
             {
                 LOG_INFO("url_fclose: failure in crypto_uri_postbuf");
                 e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
                 buf_del(e.url_wbuf);
                 strfree(e.url_url);
                 delete(e);
                 return;
             }
             // delete write end. File handle is now in unusable
             // state. Wait for data to come from the server, then
             // call the callback
             buf_del(e.url_wbuf);
             e.url_wbuf = -1;
             e.url_id = i;
             url_fromid[i] = e;
             // make sure this slot won't be reused quickly even on map change
             cvar_set("_urllib_nextslot", ftos((i + 1) % NUM_URL_ID));
         }
         else
         {
             // we have READ all data, just close
             e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);
             buf_del(e.url_rbuf);
             strfree(e.url_url);
             delete(e);
         }
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);  // closing creates no reading handle
         delete(e);
     }
     else
     {
         // file
         fclose(e.url_fh);
         e.url_ready(e, e.url_ready_pass, URL_READY_CLOSED);  // closing creates no reading handle
         delete(e);
     }
 }
ERASEABLE string url_fgets (entity e)
Definition at line 287 of file urllib.qc.
References error, fgets(), string_null, URL_FH_CURL, and URL_FH_STDOUT.
Referenced by MX_Messages_(), MX_Sync_(), and WeaponStats_ready().
 {
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_rbuf == -1) error("url_fgets: not readable in current state");
         // curl
         string s;
         s = bufstr_get(e.url_rbuf, e.url_rbufpos);
         e.url_rbufpos += 1;
         return s;
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         // stdout
         return string_null;
     }
     else
     {
         // file
         return fgets(e.url_fh);
     }
 }
ERASEABLE void url_fputs (entity e, string s)
Definition at line 312 of file urllib.qc.
References error, fputs(), print(), URL_FH_CURL, and URL_FH_STDOUT.
Referenced by MX_JLF_(), MX_Nick_(), MX_Say_(), MX_Typing_(), and WeaponStats_ready().
 {
     if (e.url_fh == URL_FH_CURL)
     {
         if (e.url_wbuf == -1) error("url_fputs: not writable in current state");
         // curl
         bufstr_set(e.url_wbuf, e.url_wbufpos, s);
         e.url_wbufpos += 1;
     }
     else if (e.url_fh == URL_FH_STDOUT)
     {
         // stdout
         print(s);
     }
     else
     {
         // file
         fputs(e.url_fh, s);
     }
 }
ERASEABLE void url_multi_fopen (string url, float mode, url_ready_func rdy, entity pass)
ERASEABLE void url_single_fopen (string url, float mode, url_ready_func rdy, entity pass)
ERASEABLE float url_URI_Get_Callback (int id, float status, string data)
Definition at line 28 of file urllib.qc.
References argv(), buf_create, entity(), error, fabs(), LOG_INFO, LOG_INFOF, MIN_URL_ID, NULL, NUM_URL_ID, strfree, tokenizebyseparator, URL_FH_CURL, url_fromid, URL_READY_CANREAD, and URL_READY_ERROR.
Referenced by URI_Get_Callback().
 {
     if (id < MIN_URL_ID) return 0;
     id -= MIN_URL_ID;
     if (id >= NUM_URL_ID) return 0;
     entity e;
     e = url_fromid[id];
     if (!e) return 0;
     if (e.url_rbuf >= 0 || e.url_wbuf >= 0)
     {
         LOG_INFOF("WARNING: handle %d (%s) has already received data?!?", id + NUM_URL_ID, e.url_url);
         return 0;
     }
     // whatever happens, we will remove the URL from the list of IDs
     url_fromid[id] = NULL;
     // if we get here, we MUST have both buffers cleared
     if (e.url_rbuf != -1 || e.url_wbuf != -1 || e.url_fh != URL_FH_CURL) error("url_URI_Get_Callback: not a request waiting for data");
     if (status == 0)
     {
         // WE GOT DATA!
         float n, i;
         n = tokenizebyseparator(data, "\n");
         e.url_rbuf = buf_create();
         if (e.url_rbuf < 0)
         {
             LOG_INFO("url_URI_Get_Callback: out of memory in buf_create");
             e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
             strfree(e.url_url);
             delete(e);
             return 1;
         }
         e.url_rbufpos = 0;
         if (e.url_rbuf < 0)
         {
             LOG_INFO("url_URI_Get_Callback: out of memory in buf_create");
             e.url_ready(e, e.url_ready_pass, URL_READY_ERROR);
             strfree(e.url_url);
             delete(e);
             return 1;
         }
         for (i = 0; i < n; ++i)
             bufstr_set(e.url_rbuf, i, argv(i));
         e.url_ready(e, e.url_ready_pass, URL_READY_CANREAD);
         return 1;
     }
     else
     {
         // an ERROR
         e.url_ready(e, e.url_ready_pass, -fabs(status));
         strfree(e.url_url);
         delete(e);
         return 1;
     }
 }
Variable Documentation
const int URI_GET_CURL = 17
Definition at line 7 of file urllib.qh.
Referenced by Curl_URI_Get_Callback(), GenericCommand_qc_curl(), and URI_Get_Callback().
const int URI_GET_CURL_END = 32
Definition at line 8 of file urllib.qh.
Referenced by GenericCommand_qc_curl(), and URI_Get_Callback().
const int URI_GET_DISCARD = 0
Definition at line 4 of file urllib.qh.
Referenced by OnlineBanList_SendBan(), OnlineBanList_SendUnban(), and URI_Get_Callback().
const int URI_GET_IPBAN = 1
Definition at line 5 of file urllib.qh.
Referenced by OnlineBanList_Think(), OnlineBanList_URI_Get_Callback(), and URI_Get_Callback().
const int URI_GET_IPBAN_END = 16
Definition at line 6 of file urllib.qh.
Referenced by URI_Get_Callback().
const int URI_GET_UPDATENOTIFICATION = 33
Definition at line 9 of file urllib.qh.
Referenced by updateCheck(), and URI_Get_Callback().
const int URI_GET_URLLIB = 128
Definition at line 10 of file urllib.qh.
const int URI_GET_URLLIB_END = 191
Definition at line 11 of file urllib.qh.
const float URL_READY_CANREAD = 2
Definition at line 16 of file urllib.qh.
Referenced by MX_Messages_(), MX_Sync_(), url_single_fopen(), url_URI_Get_Callback(), and WeaponStats_ready().
const float URL_READY_CANWRITE = 1
Definition at line 15 of file urllib.qh.
Referenced by MX_JLF_(), MX_Nick_(), MX_Say_(), MX_Typing_(), url_single_fopen(), and WeaponStats_ready().
const float URL_READY_CLOSED = 0
Definition at line 14 of file urllib.qh.
Referenced by MX_Messages_(), MX_Sync_(), url_fclose(), and WeaponStats_ready().
const float URL_READY_ERROR = -1
Definition at line 13 of file urllib.qh.
Referenced by url_fclose(), url_multi_fopen(), url_multi_ready(), url_single_fopen(), url_URI_Get_Callback(), and WeaponStats_ready().