Xonotic: common/gamemodes/gamemode/tdm/sv_tdm.qc File Reference
sv_tdm.qc File Reference
#include "sv_tdm.qh"
Functions
MUTATOR_HOOKFUNCTION (tdm, TeamBalance_CheckAllowedTeams, CBC_ORDER_EXCLUSIVE)
MUTATOR_HOOKFUNCTION (tdm, Scores_CountFragsRemaining)
spawnfunc (tdm_team)
void tdm_DelayedInit (entity this)
void tdm_Initialize ()
void tdm_SpawnTeam (string teamname, int teamcolor)
Variables
int autocvar_g_tdm_teams
int autocvar_g_tdm_teams_override
Function Documentation
MUTATOR_HOOKFUNCTION() [1/2]
MUTATOR_HOOKFUNCTION (tdm , TeamBalance_CheckAllowedTeams , CBC_ORDER_EXCLUSIVE)
Definition at line 63 of file sv_tdm.qc.
References M_ARGV.
 {
     M_ARGV(1, string) = "tdm_team";
 }
MUTATOR_HOOKFUNCTION() [2/2]
MUTATOR_HOOKFUNCTION (tdm , Scores_CountFragsRemaining)
Definition at line 68 of file sv_tdm.qc.
 {
     // announce remaining frags
     return true;
 }
spawnfunc()
spawnfunc (tdm_team)
Definition at line 13 of file sv_tdm.qc.
References cnt, g_tdm, and team.
 {
     if(!g_tdm || !this.cnt) { delete(this); return; }
     this.team = this.cnt + 1;
 }
tdm_DelayedInit()
void tdm_DelayedInit (entity this)
Definition at line 31 of file sv_tdm.qc.
References autocvar_g_tdm_teams, autocvar_g_tdm_teams_override, BIT, BITS, bound(), classname, find(), LOG_TRACE, NULL, NUM_TEAM_1, NUM_TEAM_2, NUM_TEAM_3, NUM_TEAM_4, tdm_SpawnTeam(), and teams.
Referenced by tdm_Initialize().
 {
     // if no teams are found, spawn defaults
     if(find(NULL, classname, "tdm_team") == NULL)
     {
         LOG_TRACE("No \"tdm_team\" entities found on this map, creating them anyway.");
         int numteams = autocvar_g_tdm_teams_override;
         if(numteams < 2) { numteams = autocvar_g_tdm_teams; }
         int teams = BITS(bound(2, numteams, 4));
         if(teams & BIT(0))
             tdm_SpawnTeam("Red", NUM_TEAM_1);
         if(teams & BIT(1))
             tdm_SpawnTeam("Blue", NUM_TEAM_2);
         if(teams & BIT(2))
             tdm_SpawnTeam("Yellow", NUM_TEAM_3);
         if(teams & BIT(3))
             tdm_SpawnTeam("Pink", NUM_TEAM_4);
     }
 }
tdm_Initialize()
void tdm_Initialize ()
Definition at line 53 of file sv_tdm.qc.
References autocvar_g_tdm_point_leadlimit, autocvar_g_tdm_point_limit, autocvar_g_tdm_team_spawns, GameRules_limit_lead(), GameRules_limit_score(), GameRules_spawning_teams(), GameRules_teams(), InitializeEntity(), NULL, and tdm_DelayedInit().
Referenced by REGISTER_MUTATOR().
 {
     GameRules_teams(true);
     GameRules_spawning_teams(autocvar_g_tdm_team_spawns);
     GameRules_limit_score(autocvar_g_tdm_point_limit);
     GameRules_limit_lead(autocvar_g_tdm_point_leadlimit);
     InitializeEntity(NULL, tdm_DelayedInit, INITPRIO_GAMETYPE);
 }
tdm_SpawnTeam()
void tdm_SpawnTeam (string teamname, int teamcolor)
Definition at line 21 of file sv_tdm.qc.
References cnt, entity(), netname, new_pure, and team.
Referenced by tdm_DelayedInit().
 {
     entity this = new_pure(tdm_team);
     this.netname = teamname;
     this.cnt = teamcolor - 1;
     this.team = teamcolor;
     this.spawnfunc_checked = true;
     //spawnfunc_tdm_team(this);
 }
Variable Documentation
autocvar_g_tdm_teams
int autocvar_g_tdm_teams
Definition at line 4 of file sv_tdm.qc.
Referenced by tdm_DelayedInit().
autocvar_g_tdm_teams_override
int autocvar_g_tdm_teams_override
Definition at line 5 of file sv_tdm.qc.
Referenced by tdm_DelayedInit().