Xonotic: common/models/model.qh File Reference
model.qh File Reference
Macros
#define MODEL_H
#define setmodel(e, m) _setmodel((e), (m).model_str())
Functions
if (s!=""&&s!="null"&&!fexists(s))
LOG_DEBUGF ("precache_model(\"%s\")\n", s)
precache_model (s)
Variables
this model_str = path
string s = this.model_str()
Macro Definition Documentation
#define MODEL_H
Definition at line 2 of file model.qh.
#define setmodel (e, m) _setmodel((e), (m).model_str())
Definition at line 4 of file model.qh.
Referenced by CheatCommand(), CL_SpawnWeaponentity(), cpicon_construct(), cpicon_damage(), DragBox_Think(), Freeze(), generator_construct(), generator_damage(), KillIndicator_Think(), Monster_Dead_Fade(), Monster_Spawn(), ons_generator_ray_spawn(), pathlib_showedge(), pathlib_showsquare(), pathlib_showsquare2(), Portal_Spawn(), PutObserverInServer(), turret_die(), UpdateChatBubble(), vehicle_addplayerslot(), vehicle_initialize(), vehicles_damage(), vehicles_setreturn(), vehicles_showwp(), WarpZone_Teleport(), waypoint_schedulerelink(), and waypoint_spawn().
Function Documentation
if (s! = "" && s != "null" && !fexists(s))
Definition at line 18 of file model.qh.
References LOG_WARNINGF.
Referenced by _Movetype_LinkEdict_TouchAreaGrid(), _Movetype_PushMove(), botframe_showwaypointlinks(), CSQC_Ent_Update(), CSQC_Parse_TempEntity(), GameCommand(), havocbot_goalrating_items(), HUD_Panel_DrawProgressBar(), HUD_Radar(), HUD_Weapons(), ImpulseCommands(), Label_recalcPositionWithText(), Nexposee_Calc_Scale(), Slider_mouseDrag(), Slider_mousePress(), Spawn_Score(), and VoteCount().
{
             LOG_WARNINGF("Missing model: \"%s\"\n", s);
             return;
         }
LOG_DEBUGF ("precache_model(\"%s\")\n" , s)
precache_model (s)
Referenced by CSQCPlayer_LOD_Apply(), CSQCPlayer_ModelAppearance_Apply(), GameCommand_animbench(), GameCommand_gettaginfo(), LocalCommand_debugmodel(), LODmodel_attach(), precache_playermodel(), SetBrushEntityModel(), SetBrushEntityModelNoLOD(), setplayermodel(), spawn_item_key(), STATIC_INIT(), and WarpZoneLib_ExactTrigger_Init().
Variable Documentation
this model_str = path
Definition at line 12 of file model.qh.
string s = this.model_str()
Definition at line 17 of file model.qh.