Xonotic: common/deathtypes/all.qh File Reference
all.qh File Reference
#include <common/notifications/all.qh>
#include "all.inc"
Macros
#define DEATH_ENT(t) (DEATH_ISSPECIAL(t) ? (Deathtypes_from(t - DT_FIRST)) : NULL)
#define DEATH_IS(t, dt) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)) == dt)
#define DEATH_ISMONSTER(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "monster")
#define DEATH_ISSPECIAL(t) (t >= DT_FIRST)
#define DEATH_ISTURRET(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "turret")
#define DEATH_ISVEHICLE(t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "vehicle")
#define DEATH_ISWEAPON(t, w) (DEATH_WEAPONOF(t) == (w))
#define DEATH_WEAPONOF(t) (DEATH_ISSPECIAL(t) ? WEP_Null : Weapons_from((t) & DEATH_WEAPONMASK))
#define Deathtypes_from(i) _Deathtypes_from(i, NULL)
#define REGISTER_DEATHTYPE(id, msg_death, msg_death_by, extra)
Functions
string Deathtype_Name (int deathtype)
Variables
const int DEATH_HITTYPEMASK = HITTYPE_SECONDARY | HITTYPE_SPLASH | HITTYPE_BOUNCE | HITTYPE_ARMORPIERCE | HITTYPE_RESERVED
string death_msgextra
entity death_msgmurder
entity death_msgself
const int DEATH_WEAPONMASK = BITS(8)
const int DT_FIRST = BIT(13)
const int HITTYPE_ARMORPIERCE = BITS(1) << 11
const int HITTYPE_BOUNCE = BITS(1) << 10
const int HITTYPE_RESERVED = BITS(1) << 12
const int HITTYPE_SECONDARY = BITS(1) << 8
const int HITTYPE_SPLASH = BITS(1) << 9
automatically set by RadiusDamage
Macro Definition Documentation
#define DEATH_ENT (t) (DEATH_ISSPECIAL(t) ? (Deathtypes_from(t - DT_FIRST)) : NULL)
Definition at line 37 of file all.qh.
Referenced by MUTATOR_HOOKFUNCTION(), and Obituary().
#define DEATH_IS (t, dt) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)) == dt)
Definition at line 36 of file all.qh.
#define DEATH_ISMONSTER (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "monster")
Definition at line 40 of file all.qh.
#define DEATH_ISSPECIAL (t) (t >= DT_FIRST)
Definition at line 35 of file all.qh.
Referenced by Damage(), Deathtype_Name(), door_damage(), Obituary(), Obituary_SpecialDeath(), PlayerDamage(), and RadiusDamageForSource().
#define DEATH_ISTURRET (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "turret")
Definition at line 39 of file all.qh.
#define DEATH_ISVEHICLE (t) (DEATH_ISSPECIAL(t) && (Deathtypes_from(t - DT_FIRST)).death_msgextra == "vehicle")
Definition at line 38 of file all.qh.
#define DEATH_ISWEAPON (t, w) (DEATH_WEAPONOF(t) == (w))
Definition at line 42 of file all.qh.
Referenced by Damage(), MUTATOR_HOOKFUNCTION(), PlayerDamage(), and vehicles_damage().
#define DEATH_WEAPONOF (t) (DEATH_ISSPECIAL(t) ? WEP_Null : Weapons_from((t) & DEATH_WEAPONMASK))
Definition at line 41 of file all.qh.
Referenced by Damage(), DamageText::DamageText_draw2d(), Fire_AddDamage(), MUTATOR_HOOKFUNCTION(), Obituary_WeaponDeath(), PlayerDamage(), RadiusDamageForSource(), vehicles_damage(), and W_SetupShot_Dir_ProjectileSize_Range().
#define Deathtypes_from (i) _Deathtypes_from(i, NULL)
Definition at line 6 of file all.qh.
Referenced by Deathtype_Name(), and Obituary_SpecialDeath().
#define REGISTER_DEATHTYPE (id, msg_death, msg_death_by, extra)
Value:
REGISTER(Deathtypes, DEATH, id, m_id, new_pure(deathtype)) { \
        this.m_id += DT_FIRST; \
        this.nent_name = #id; \
        this.death_msgextra = extra; \
        this.death_msgself = msg_death; \
        this.death_msgmurder = msg_death_by; \
    }
Definition at line 14 of file all.qh.
Function Documentation
string Deathtype_Name (int deathtype)
Definition at line 3 of file all.qc.
References backtrace, DEATH_ISSPECIAL, Deathtypes_from, DT_FIRST, entity(), and ftos().
Referenced by LogDeath(), and Obituary().
 {
     if (DEATH_ISSPECIAL(deathtype)) {
         entity deathent = Deathtypes_from(deathtype - DT_FIRST);
         if (!deathent) { backtrace("Deathtype_Name: Could not find deathtype entity!\n"); return ""; }
         return deathent.nent_name;
     }
     return ftos(deathtype);
 }
Variable Documentation
const int DEATH_HITTYPEMASK = HITTYPE_SECONDARY | HITTYPE_SPLASH | HITTYPE_BOUNCE | HITTYPE_ARMORPIERCE | HITTYPE_RESERVED
Definition at line 31 of file all.qh.
string death_msgextra
Definition at line 12 of file all.qh.
entity death_msgmurder
Definition at line 11 of file all.qh.
entity death_msgself
Definition at line 10 of file all.qh.
const int DEATH_WEAPONMASK = BITS(8)
Definition at line 23 of file all.qh.
const int DT_FIRST = BIT(13)
Definition at line 33 of file all.qh.
Referenced by Deathtype_Name(), and Obituary_SpecialDeath().
const int HITTYPE_ARMORPIERCE = BITS(1) << 11
Definition at line 28 of file all.qh.
const int HITTYPE_BOUNCE = BITS(1) << 10
Definition at line 27 of file all.qh.
Referenced by RadiusDamageForSource().
const int HITTYPE_RESERVED = BITS(1) << 12
Definition at line 30 of file all.qh.
const int HITTYPE_SECONDARY = BITS(1) << 8
Definition at line 24 of file all.qh.
Referenced by MUTATOR_HOOKFUNCTION(), RadiusDamageForSource(), and W_Nexball_Attack2().
const int HITTYPE_SPLASH = BITS(1) << 9
automatically set by RadiusDamage
Definition at line 26 of file all.qh.
Referenced by adaptor_think2use_hittype_splash(), door_damage(), MUTATOR_HOOKFUNCTION(), and RadiusDamageForSource().