Xonotic: common/items/item.qh File Reference
item.qh File Reference
Classes
class GameItem
Macros
#define ITEM_HANDLE(signal,...) __Item_Send_##signal(__VA_ARGS__)
#define SPAWNFUNC_ITEM(name, item)
Enumerations
enum { ITEM_FLAG_NORMAL = BIT(0), ITEM_FLAG_MUTATORBLOCKED = BIT(1), ITEM_FLAG_RESOURCE = BIT(2) }
Variables
const int IT_25HP = BIT(12)
const int IT_5HP = BIT(11)
const int IT_ARMOR = BIT(15)
const int IT_ARMOR_SHARD = BIT(14)
const int IT_CELLS = BIT(9)
const int IT_CTF_SHIELDED = BIT(18)
const int IT_FUEL = BIT(5)
const int IT_FUEL_REGEN = BIT(4)
const int IT_HEALTH = BIT(13)
const int IT_INVINCIBLE = BIT(20)
const int IT_INVISIBILITY = BIT(19)
const int IT_JETPACK = BIT(2)
const int IT_KEY1 = BIT(16)
const int IT_KEY2 = BIT(17)
const int IT_NAILS = BIT(7)
const int IT_PICKUPMASK = IT_UNLIMITED_AMMO | IT_JETPACK | IT_FUEL_REGEN
const int IT_PLASMA = BIT(10)
const int IT_ROCKETS = BIT(8)
const int IT_SHELLS = BIT(6)
const int IT_STRENGTH = BIT(22)
const int IT_SUPERWEAPON = BIT(21)
const int IT_UNLIMITED_AMMO = IT_UNLIMITED_WEAPON_AMMO | IT_UNLIMITED_SUPERWEAPONS
const int IT_UNLIMITED_SUPERWEAPONS = BIT(1)
const int IT_UNLIMITED_WEAPON_AMMO = BIT(0)
const int IT_USING_JETPACK = BIT(3)
Macro Definition Documentation
#define ITEM_HANDLE (signal, ...) __Item_Send_##signal(__VA_ARGS__)
Definition at line 89 of file item.qh.
Referenced by ctf_FlagTouch(), and Dump_Items().
#define SPAWNFUNC_ITEM (name, item)
Definition at line 78 of file item.qh.
Enumeration Type Documentation
anonymous enum
Enumerator
ITEM_FLAG_NORMAL
Item is usable during normal gameplay.
ITEM_FLAG_MUTATORBLOCKED
ITEM_FLAG_RESOURCE
Item is is a resource, not a held item.
Definition at line 82 of file item.qh.
 {
     ITEM_FLAG_NORMAL = BIT(0),
     ITEM_FLAG_MUTATORBLOCKED = BIT(1),
     ITEM_FLAG_RESOURCE = BIT(2)
 };
Variable Documentation
const int IT_25HP = BIT(12)
Definition at line 29 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_5HP = BIT(11)
Definition at line 28 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_ARMOR = BIT(15)
Definition at line 33 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_ARMOR_SHARD = BIT(14)
Definition at line 32 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_CELLS = BIT(9)
Definition at line 25 of file item.qh.
const int IT_CTF_SHIELDED = BIT(18)
Definition at line 38 of file item.qh.
const int IT_FUEL = BIT(5)
Definition at line 21 of file item.qh.
Referenced by PlayerThink(), and REGISTER_ITEM().
const int IT_FUEL_REGEN = BIT(4)
Definition at line 19 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_HEALTH = BIT(13)
Definition at line 30 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_INVINCIBLE = BIT(20)
Definition at line 42 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_INVISIBILITY = BIT(19)
Definition at line 41 of file item.qh.
const int IT_JETPACK = BIT(2)
Definition at line 17 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_KEY1 = BIT(16)
Definition at line 35 of file item.qh.
const int IT_KEY2 = BIT(17)
Definition at line 36 of file item.qh.
const int IT_NAILS = BIT(7)
Definition at line 23 of file item.qh.
const int IT_PICKUPMASK = IT_UNLIMITED_AMMO | IT_JETPACK | IT_FUEL_REGEN
Definition at line 48 of file item.qh.
const int IT_PLASMA = BIT(10)
Definition at line 26 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_ROCKETS = BIT(8)
Definition at line 24 of file item.qh.
const int IT_SHELLS = BIT(6)
Definition at line 22 of file item.qh.
const int IT_STRENGTH = BIT(22)
Definition at line 44 of file item.qh.
Referenced by REGISTER_ITEM().
const int IT_SUPERWEAPON = BIT(21)
Definition at line 43 of file item.qh.
Referenced by HUD_Powerups(), and player_powerups().
const int IT_UNLIMITED_AMMO = IT_UNLIMITED_WEAPON_AMMO | IT_UNLIMITED_SUPERWEAPONS
Definition at line 47 of file item.qh.
Referenced by buff_Available(), MUTATOR_HOOKFUNCTION(), readplayerstartcvars(), and TEST().
const int IT_UNLIMITED_SUPERWEAPONS = BIT(1)
Definition at line 15 of file item.qh.
Referenced by HUD_Powerups(), MUTATOR_HOOKFUNCTION(), player_powerups(), readplayerstartcvars(), and W_ThrowNewWeapon().
const int IT_UNLIMITED_WEAPON_AMMO = BIT(0)
Definition at line 14 of file item.qh.
Referenced by buff_Available(), CheckPlayerJump(), client_hasweapon(), HUD_Ammo(), HUD_Weapons(), instagib_ammocheck(), MUTATOR_HOOKFUNCTION(), NIX_GiveCurrentWeapon(), player_regen(), PM_jetpack(), readplayerstartcvars(), W_DecreaseAmmo(), W_Reload(), W_ReloadedAndReady(), and weapon_prepareattack_checkammo().
const int IT_USING_JETPACK = BIT(3)
Definition at line 18 of file item.qh.
Referenced by CheckPlayerJump(), player_powerups(), PM_jetpack(), sys_phys_update(), and vehicles_enter().