Xonotic: common/effects/effectinfo_buffs.inc File Reference
effectinfo_buffs.inc File Reference
Functions
DEF (relic_resistance)
DEF (relic_regeneration)
DEF (relic_vampire)
DEF (relic_ammo)
DEF (relic_damage)
DEF (relic_ssplashdamage)
DEF (relic_firingspeed)
DEF (relic_disability)
DEF (relic_disability_curse)
DEF (relic_teamboost)
DEF (relic_teamboost_boost)
DEF (relic_speed)
DEF (relic_jump)
DEF (relic_flight)
DEF (relic_radioactive)
DEF (relic_resurrection)
DEF (relic_vengeance)
SUB (relic_resistance)
SUB (relic_regeneration)
SUB (relic_vampire)
SUB (relic_ammo)
SUB (relic_damage)
SUB (relic_ssplashdamage)
SUB (relic_firingspeed)
SUB (relic_disability)
SUB (relic_disability_curse)
SUB (relic_teamboost)
SUB (relic_teamboost_boost)
SUB (relic_speed)
SUB (relic_jump)
SUB (relic_flight)
SUB (relic_radioactive)
SUB (relic_resurrection)
SUB (relic_vengeance)
Function Documentation
DEF (relic_resistance)
Referenced by SUB().
DEF (relic_regeneration)
DEF (relic_vampire)
DEF (relic_ammo)
DEF (relic_damage)
DEF (relic_ssplashdamage)
DEF (relic_firingspeed)
DEF (relic_disability)
DEF (relic_disability_curse)
DEF (relic_teamboost)
DEF (relic_teamboost_boost)
DEF (relic_speed)
DEF (relic_jump)
DEF (relic_flight)
DEF (relic_radioactive)
DEF (relic_resurrection)
DEF (relic_vengeance)
SUB (relic_resistance)
Definition at line 2 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                       {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x00ff80";
     MY(color_max) = "0x00ff80";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_regeneration)
Definition at line 20 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x00ffff";
     MY(color_max) = "0x00ffff";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_vampire)
Definition at line 38 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                    {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xff00ff";
     MY(color_max) = "0xff00ff";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_ammo)
Definition at line 56 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                 {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x80ff00";
     MY(color_max) = "0x80ff00";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_damage)
Definition at line 74 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                   {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xff0000";
     MY(color_max) = "0xff0000";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_ssplashdamage)
Definition at line 92 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xff8000";
     MY(color_max) = "0xff8000";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_firingspeed)
Definition at line 110 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xffff00";
     MY(color_max) = "0xffff00";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_disability)
Definition at line 128 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                       {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x0000ff";
     MY(color_max) = "0x0000ff";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_disability_curse)
Definition at line 146 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x000080";
     MY(color_max) = "0x000080";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_teamboost)
Definition at line 164 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                      {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xffffff";
     MY(color_max) = "0xffffff";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_teamboost_boost)
Definition at line 182 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x808080";
     MY(color_max) = "0x808080";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_speed)
Definition at line 200 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                  {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x80ffff";
     MY(color_max) = "0x80ffff";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_jump)
Definition at line 218 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                 {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xffff80";
     MY(color_max) = "0xffff80";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_flight)
Definition at line 236 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
                   {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x8080ff";
     MY(color_max) = "0x8080ff";
     MY(count) = 1;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_radioactive)
Definition at line 254 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0x00ff00";
     MY(color_max) = "0x00ff00";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_resurrection)
Definition at line 272 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, DEF(), gravity, and originjitter.
{
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xff0080";
     MY(color_max) = "0xff0080";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }
SUB (relic_vengeance)
Definition at line 290 of file effectinfo_buffs.inc.
References alpha_max, alpha_min, count, gravity, and originjitter.
                      {
     MY(airfriction) = 0.200000;
     MY(alpha_min) = 128;
     MY(alpha_max) = 256;
     MY(alpha_fade) = 256;
     MY(color_min) = "0xff8080";
     MY(color_max) = "0xff8080";
     MY(count) = 20;
     MY(gravity) = -0.100000;
     MY(liquidfriction) = 0.800000;
     MY(originjitter) = '8.0 8.0 32.0';
     MY(size_min) = 1.500000;
     MY(size_max) = 1.500000;
     MY(type) = "static";
     MY(velocityjitter) = '64.0 64.0 32.0';
 }