Xonotic: common/minigames/cl_minigames.qh File Reference
cl_minigames.qh File Reference
Macros
#define CL_MINIGAMES_H
#define FOREACH_MINIGAME_ENTITY(entityvar)
#define minigame_cmd(...) minigame_cmd_workaround(0,__VA_ARGS__)
#define minigame_hud_fitsqare(pos, mySize)
#define minigame_hud_panelarea(pos, mySize, panelID)
#define Minigames_from(i) _Minigames_from(i, NULL)
#define REGISTER_MINIGAME(name, nicename)
Functions
void deactivate_minigame ()
float HUD_Minigame_Showpanels ()
void HUD_MinigameMenu_Close ()
void HUD_MinigameMenu_CustomEntry (entity parent, string message, string event_arg)
float HUD_MinigameMenu_IsOpened ()
void minigame_cmd_workaround (float dummy, string...cmdargc)
void minigame_drawcolorcodedstring_trunc (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags)
vector minigame_drawcolorcodedstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags, float align)
void minigame_drawpic_centered (vector pos, string texture, vector sz, vector color, float thealpha, int drawflags)
void minigame_drawstring_trunc (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags)
vector minigame_drawstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags, float align)
vector minigame_hud_denormalize (vector v, vector pos, vector mySize)
vector minigame_hud_denormalize_size (vector v, vector pos, vector mySize)
bool minigame_hud_mouse_in (vector pos, vector sz)
vector minigame_hud_normalize (vector v, vector pos, vector mySize)
void minigame_hud_simpleboard (vector pos, vector mySize, string board_texture)
float minigame_isactive ()
void minigame_prompt ()
string minigame_texture (string name)
void (vector pos, vector size) minigame_hud_board
Variables
entity active_minigame
float minigame_playerslot
entity minigame_self
Macro Definition Documentation
#define CL_MINIGAMES_H
Definition at line 2 of file cl_minigames.qh.
#define FOREACH_MINIGAME_ENTITY (entityvar)
Value:
entityvar=world; \
    while( (entityvar = findentity(entityvar,owner,active_minigame)) )
Definition at line 109 of file cl_minigames.qh.
#define minigame_cmd (...) minigame_cmd_workaround(0,__VA_ARGS__)
Definition at line 95 of file cl_minigames.qh.
Referenced by HUD_MinigameMenu_ClickCreate_Entry(), HUD_MinigameMenu_ClickInvite_Entry(), HUD_MinigameMenu_ClickJoin_Entry(), and HUD_MinigameMenu_ClickQuit().
#define minigame_hud_fitsqare (pos, mySize)
Value:
if (mySize##_x > mySize##_y) \
    { \
        pos##_x += (mySize##_x-mySize##_y)/2; \
        mySize##_x = mySize##_y; \
    } \
    else \
    { \
        pos##_y += (mySize##_y-mySize##_x)/2; \
        mySize##_x = mySize##_x; \
    } \
    if(panel_bg_padding) \
    { \
        pos += '1 1 0' * panel_bg_padding; \
        mySize -= '2 2 0' * panel_bg_padding; \
    }
Definition at line 6 of file cl_minigames.qh.
#define minigame_hud_panelarea (pos, mySize, panelID)
Value:
pos = stov(cvar_string(strcat("hud_panel_", HUD_PANEL(panelID).panel_name, "_pos"))); \
    mySize = stov(cvar_string(strcat("hud_panel_", HUD_PANEL(panelID).panel_name, "_size"))); \
    pos##_x *= vid_conwidth; pos##_y *= vid_conheight; \
    mySize##_x *= vid_conwidth; mySize##_y *= vid_conheight;
Definition at line 25 of file cl_minigames.qh.
#define Minigames_from (i) _Minigames_from(i, NULL)
Definition at line 115 of file cl_minigames.qh.
#define REGISTER_MINIGAME (name, nicename)
Value:
REGISTER(Minigames, MINIGAME_##name, m_id, new_pure(minigame_descriptor)); \
    void name##_hud_board(vector, vector); \
    void name##_hud_status(vector, vector); \
    int name##_client_event(entity, string, ...); \
    REGISTER_INIT(MINIGAME_##name) { \
        this.netname = strzone(strtolower(#name)); \
        this.message = nicename; \
        this.minigame_hud_board = name##_hud_board; \
        this.minigame_hud_status = name##_hud_status; \
        this.minigame_event = name##_client_event; \
    } \
    REGISTER_INIT(MINIGAME_##name)
Definition at line 118 of file cl_minigames.qh.
Function Documentation
void deactivate_minigame ()
Definition at line 83 of file cl_minigames.qc.
References active_minigame, auto_close_minigamemenu, entity(), findentity(), HUD_MinigameMenu_Close(), HUD_MinigameMenu_CurrentButton(), minigame_autoclean_entity(), minigame_self, owner, and world.
Referenced by activate_minigame(), HUD_MinigameMenu_ClickQuit(), minigame_entremove(), minigame_player_entremove(), and Shutdown().
 {
     if ( !active_minigame )
         return;
     active_minigame.minigame_event(active_minigame,"deactivate");
     entity e = world;
     while( (e = findentity(e, owner, active_minigame)) )
         if ( e.minigame_autoclean )
         {
             minigame_autoclean_entity(e);
         }
     minigame_self = world;
     active_minigame = world;
     if ( auto_close_minigamemenu )
     {
         HUD_MinigameMenu_Close();
         auto_close_minigamemenu = 0;
     }
     else
         HUD_MinigameMenu_CurrentButton();
 }
float HUD_Minigame_Showpanels ()
Definition at line 697 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_IsOpened(), and minigame_isactive().
Referenced by HUD_Panel_CheckFlags().
 {
     return (HUD_MinigameMenu_IsOpened() && minigame_isactive());
 }
void HUD_MinigameMenu_Close ()
Definition at line 345 of file cl_minigames_hud.qc.
References autocvar__hud_configure, autocvar_hud_cursormode, entity(), HUD_MinigameMenu_activeitem, HUD_MinigameMenu_entries, HUD_MinigameMenu_IsOpened(), HUD_MinigameMenu_last_entry, p, and world.
Referenced by HUD_Minigame_InputEvent(), and HUD_MinigameMenu_CurrentButton().
 {
     if ( HUD_MinigameMenu_IsOpened() )
     {
         entity e, p;
         for ( e = HUD_MinigameMenu_entries; e != world; e = p )
         {
             p = e.list_next;
             remove(e);
         }
         HUD_MinigameMenu_entries = world;
         HUD_MinigameMenu_last_entry = world;
         HUD_MinigameMenu_activeitem = world;
         if(autocvar_hud_cursormode)
         if ( !autocvar__hud_configure )
             setcursormode(0);
     }
 }
void HUD_MinigameMenu_CustomEntry (entity parent, string message, string event_arg)
Definition at line 315 of file cl_minigames_hud.qc.
References entity(), HUD_MinigameMenu_ClickCustomEntry(), HUD_MinigameMenu_InsertEntry(), and HUD_MinigameMenu_SpawnSubEntry().
 {
     entity e = HUD_MinigameMenu_SpawnSubEntry(
         menumessage, HUD_MinigameMenu_ClickCustomEntry, parent );
     e.netname = event_arg;
     HUD_MinigameMenu_InsertEntry(e, parent);
     //dprint("CustomEntry ",ftos(num_for_edict(parent))," ",menumessage," ",event_arg,"\n");
 }
float HUD_MinigameMenu_IsOpened ()
Definition at line 339 of file cl_minigames_hud.qc.
References HUD_MinigameMenu_entries, and NULL.
Referenced by HUD_Minigame_InputEvent(), HUD_Minigame_Mouse(), HUD_Minigame_Showpanels(), HUD_MinigameMenu(), HUD_MinigameMenu_Close(), and HUD_MinigameMenu_Open().
 {
     return HUD_MinigameMenu_entries != NULL;
 }
void minigame_cmd_workaround (float dummy, string... cmdargc)
Definition at line 365 of file cl_minigames.qc.
References cmd(), localcmd, and strcat().
 {
     string cmd;
     cmd = "cmd minigame ";
     float i;
     for ( i = 0; i < cmdargc; i++ )
         cmd = strcat(cmd,...(i,string));
     localcmd(strcat(cmd,"\n"));
 }
void minigame_drawcolorcodedstring_trunc (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags)
Definition at line 350 of file cl_minigames.qc.
References drawcolorcodedstring(), stringwidth_colors(), and textShortenToWidth().
Referenced by HUD_MinigameMenu_DrawColoredEntry().
 {
     string line = textShortenToWidth(text,maxwidth,fontsize,stringwidth_colors);
     drawcolorcodedstring(pos, line, fontsize, theAlpha, drawflags);
 }
vector minigame_drawcolorcodedstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, float theAlpha, int drawflags, float align)
Definition at line 324 of file cl_minigames.qc.
References drawcolorcodedstring(), getWrappedLine_remaining, minigame_getWrappedLine(), stringwidth_colors(), and vector().
Referenced by HUD_MinigameHelp().
 {
     getWrappedLine_remaining = text;
     vector mypos = pos;
     while ( getWrappedLine_remaining )
     {
         string line = minigame_getWrappedLine(maxwidth,fontsize,stringwidth_colors);
         if ( line == "" )
             break;
         mypos_x = pos_x + (maxwidth - stringwidth_colors(line, fontsize)) * align;
         drawcolorcodedstring(mypos, line, fontsize, theAlpha, drawflags);
         mypos_y += fontsize_y;
     }
     mypos_x = maxwidth;
     mypos_y -= pos_y;
     return mypos;
 }
void minigame_drawpic_centered (vector pos, string texture, vector sz, vector color, float thealpha, int drawflags)
Definition at line 357 of file cl_minigames.qc.
References drawpic().
 {
     drawpic( pos-sz/2, texture, sz, color, thealpha, drawflags );
 }
void minigame_drawstring_trunc (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags)
Definition at line 343 of file cl_minigames.qc.
References drawstring(), stringwidth_nocolors(), and textShortenToWidth().
Referenced by HUD_MinigameMenu_DrawEntry().
 {
     string line = textShortenToWidth(text,maxwidth,fontsize,stringwidth_nocolors);
     drawstring(pos, line, fontsize, color, theAlpha, drawflags);
 }
vector minigame_drawstring_wrapped (float maxwidth, vector pos, string text, vector fontsize, vector color, float theAlpha, int drawflags, float align)
Definition at line 305 of file cl_minigames.qc.
References drawstring(), getWrappedLine_remaining, minigame_getWrappedLine(), stringwidth_nocolors(), and vector().
 {
     getWrappedLine_remaining = text;
     vector mypos = pos;
     while ( getWrappedLine_remaining )
     {
         string line = minigame_getWrappedLine(maxwidth,fontsize,stringwidth_nocolors);
         if ( line == "" )
             break;
         mypos_x = pos_x + (maxwidth - stringwidth_nocolors(line, fontsize)) * align;
         drawstring(mypos, line, fontsize, color, theAlpha, drawflags);
         mypos_y += fontsize_y;
     }
     mypos_x = maxwidth;
     mypos_y -= pos_y;
     return mypos;
 }
vector minigame_hud_denormalize (vector v, vector pos, vector mySize)
Definition at line 16 of file cl_minigames.qc.
 {
     v_x = pos_x + v_x * mySize_x;
     v_y = pos_y + v_y * mySize_y;
     return v;
 }
vector minigame_hud_denormalize_size (vector v, vector pos, vector mySize)
Definition at line 23 of file cl_minigames.qc.
 {
     v_x = v_x * mySize_x;
     v_y = v_y * mySize_y;
     return v;
 }
bool minigame_hud_mouse_in (vector pos, vector sz)
Definition at line 39 of file cl_minigames.qc.
 {
     return mousepos_x >= pos_x && mousepos_x < pos_x + sz_x &&
            mousepos_y >= pos_y && mousepos_y < pos_y + sz_y ;
 }
vector minigame_hud_normalize (vector v, vector pos, vector mySize)
Definition at line 31 of file cl_minigames.qc.
 {
     v_x = ( v_x - pos_x ) / mySize_x;
     v_y = ( v_y - pos_y ) / mySize_y;
     return v;
 }
void minigame_hud_simpleboard (vector pos, vector mySize, string board_texture)
Definition at line 4 of file cl_minigames.qc.
References BORDER_MULTIPLIER, draw_BorderPicture(), DRAWFLAG_NORMAL, drawpic(), panel, panel_bg_alpha, panel_bg_border, and panel_bg_color.
 {
     if(panel.current_panel_bg != "0" && panel.current_panel_bg != "")
         draw_BorderPicture(pos - '1 1 0' * panel_bg_border,
                     panel.current_panel_bg,
                     mySize + '1 1 0' * 2 * panel_bg_border,
                     panel_bg_color, panel_bg_alpha,
                      '1 1 0' * (panel_bg_border/BORDER_MULTIPLIER));
     drawpic(pos, board_texture, mySize, '1 1 1', panel_bg_alpha, DRAWFLAG_NORMAL);
 }
float minigame_isactive ()
Definition at line 89 of file cl_minigames.qh.
References world.
Referenced by HUD_Minigame_InputEvent(), and HUD_Minigame_Showpanels().
 {
     return active_minigame != world;
 }
void minigame_prompt ()
Definition at line 377 of file cl_minigames.qc.
References active_minigame, HUD_MinigameMenu_IsOpened(), and HUD_Notify_Push().
 {
     if ( active_minigame && ! HUD_MinigameMenu_IsOpened() )
     {
         HUD_Notify_Push(sprintf("minigames/%s/icon_notif",active_minigame.descriptor.netname),
             _("It's your turn"), "");
     }
 }
string minigame_texture (string name)
Definition at line 49 of file cl_minigames.qc.
References autocvar_menu_skin, minigame_texture_skin(), and precache_pic().
Referenced by HUD_MinigameMenu_ClickCreate(), HUD_MinigameMenu_ClickJoin(), and HUD_MinigameMenu_CurrentButton().
 {
     string path = minigame_texture_skin(autocvar_menu_skin,name);
     if ( precache_pic(path) == "" )
         path = minigame_texture_skin("default", name);
     return path;
 }
void (vector pos, vector size)
Variable Documentation
entity active_minigame
Definition at line 84 of file cl_minigames.qh.
Referenced by activate_minigame(), ClientCommand_minigame(), ClientDisconnect(), deactivate_minigame(), HUD_Minigame_InputEvent(), HUD_MinigameBoard(), HUD_MinigameHelp(), HUD_MinigameMenu_ClickCurrentGame(), HUD_MinigameMenu_ClickCustomEntry(), HUD_MinigameMenu_ClickJoin(), HUD_MinigameMenu_CurrentButton(), HUD_MinigameStatus(), HUD_WouldDrawScoreboard(), minigame_entremove(), minigame_player_entremove(), minigame_prompt(), MinigameImpulse(), and NET_HANDLE().
float minigame_playerslot
Definition at line 78 of file cl_minigames.qh.
Referenced by HUD_MinigameMenu_ClickInvite(), and minigame_player_entremove().
entity minigame_self
Definition at line 86 of file cl_minigames.qh.
Referenced by activate_minigame(), deactivate_minigame(), and NET_HANDLE().