Xonotic: common/state.qc File Reference
state.qc File Reference
#include "state.qh"
Functions
void accuracy_free (entity this)
void accuracy_init (entity this)
void anticheat_init (entity this)
void anticheat_report (entity this)
void bot_clientconnect (entity this)
void bot_clientdisconnect (entity this)
void ClientData_Attach (entity this)
void ClientData_Detach (entity this)
void ClientState_attach (entity this)
void ClientState_detach (entity this)
void DecodeLevelParms (entity this)
void entcs_attach (entity this)
void entcs_detach (entity this)
void GetCvars (entity this, int)
void Inventory_delete (entity this)
void Inventory_new (entity this)
void playerdemo_init (entity this)
void playerdemo_shutdown ()
void PlayerScore_Attach (entity this)
void PlayerScore_Detach (entity this)
void PlayerState_attach (entity this)
void PlayerState_detach (entity this)
void W_HitPlotClose (entity this)
void W_HitPlotOpen (entity this)
Function Documentation
void accuracy_free (entity this)
Definition at line 48 of file accuracy.qc.
Referenced by ClientState_detach().
 {
     remove(e.accuracy);
 }
void accuracy_init (entity this)
Definition at line 40 of file accuracy.qc.
Referenced by ClientState_attach().
 {
     entity a = e.accuracy = new_pure(accuracy);
     a.owner = e;
     a.drawonlytoclient = e;
     Net_LinkEntity(a, false, 0, accuracy_send);
 }
void anticheat_init (entity this)
Definition at line 238 of file anticheat.qc.
Referenced by ClientState_attach().
 {
     CS(this).anticheat_speedhack_offset = 0;
     CS(this).anticheat_jointime = servertime;
 }
void anticheat_report (entity this)
Definition at line 172 of file anticheat.qc.
Referenced by ClientState_detach(), and GameCommand_anticheat().
 {
     if(!autocvar_sv_eventlog)
         return;
     // TODO(divVerent): Use xonstat to acquire good thresholds.
     GameLogEcho(strcat(":anticheat:_time:", ftos(this.playerid), ":", ftos(servertime - CS(this).anticheat_jointime)));
     GameLogEcho(strcat(":anticheat:speedhack:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack), 240, 0, 9999))); // Actually this one seems broken.
     GameLogEcho(strcat(":anticheat:speedhack_m1:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack_m1), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m2:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack_m2), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m3:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack_m3), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m4:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack_m4), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:speedhack_m5:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_speedhack_m5), 240, 1.01, 1.25)));
     GameLogEcho(strcat(":anticheat:div0_strafebot_old:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_div0_strafebot_old), 120, 0.15, 0.4)));
     GameLogEcho(strcat(":anticheat:div0_strafebot_new:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_div0_strafebot_new), 120, 0.25, 0.8)));
     GameLogEcho(strcat(":anticheat:div0_evade:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_div0_evade), 120, 0.2, 0.5)));
     GameLogEcho(strcat(":anticheat:idle_snapaim:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_signal) - MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_noise), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_signal:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_signal), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_noise:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_noise), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m2:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_m2), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m3:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_m3), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m4:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_m4), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m7:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_m7), 120, 0, 9999)));
     GameLogEcho(strcat(":anticheat:idle_snapaim_m10:", ftos(this.playerid), ":", anticheat_display(MEAN_EVALUATE(CS(this), anticheat_idle_snapaim_m10), 120, 0, 9999)));
 }
void bot_clientconnect (entity this)
Definition at line 402 of file bot.qc.
Referenced by ClientState_attach().
 {
     if (!IS_BOT_CLIENT(this)) return;
     this.bot_preferredcolors = this.clientcolors;
     this.bot_nextthink = time - random();
     this.lag_func = bot_lagfunc;
     this.isbot = true;
     this.createdtime = this.bot_nextthink;
     if(!this.bot_config_loaded) // This is needed so team overrider doesn't break between matches
         bot_setnameandstuff(this);
     if(this.bot_forced_team==1)
         this.team = NUM_TEAM_1;
     else if(this.bot_forced_team==2)
         this.team = NUM_TEAM_2;
     else if(this.bot_forced_team==3)
         this.team = NUM_TEAM_3;
     else if(this.bot_forced_team==4)
         this.team = NUM_TEAM_4;
     else
         JoinBestTeam(this, false, true);
     havocbot_setupbot(this);
 }
void bot_clientdisconnect (entity this)
Definition at line 379 of file bot.qc.
Referenced by ClientState_detach().
 {
     if (!IS_BOT_CLIENT(this))
         return;
     bot_clearqueue(this);
     if(this.cleanname)
         strunzone(this.cleanname);
     if(this.netname_freeme)
         strunzone(this.netname_freeme);
     if(this.playermodel_freeme)
         strunzone(this.playermodel_freeme);
     if(this.playerskin_freeme)
         strunzone(this.playerskin_freeme);
     this.cleanname = string_null;
     this.netname_freeme = string_null;
     this.playermodel_freeme = string_null;
     this.playerskin_freeme = string_null;
     if(this.bot_cmd_current)
         remove(this.bot_cmd_current);
     if(bot_waypoint_queue_owner==this)
         bot_waypoint_queue_owner = world;
 }
void ClientData_Attach (entity this)
Definition at line 107 of file cl_client.qc.
References clientdata, ClientData_Send(), and new_pure.
Referenced by ClientState_attach().
 {
     Net_LinkEntity(this.clientdata = new_pure(clientdata), false, 0, ClientData_Send);
     this.clientdata.drawonlytoclient = this;
     this.clientdata.owner = this;
 }
void ClientData_Detach (entity this)
Definition at line 114 of file cl_client.qc.
References clientdata, and NULL.
Referenced by ClientState_detach().
 {
     remove(this.clientdata);
     this.clientdata = NULL;
 }
void ClientState_attach (entity this)
Definition at line 36 of file state.qc.
References _cs, accuracy_init(), anticheat_init(), bot_clientconnect(), ClientData_Attach(), DecodeLevelParms(), entcs_attach(), GetCvars(), IS_REAL_CLIENT, NEW, playerdemo_init(), PlayerScore_Attach(), and W_HitPlotOpen().
Referenced by Client::Client().
 {
     this._cs = NEW(ClientState, this);
     GetCvars(this, 0);  // get other cvars from player
     if (IS_REAL_CLIENT(this)) { PlayerStats_PlayerBasic_CheckUpdate(this); }
     // TODO: fold all of these into ClientState
     DecodeLevelParms(this);
     PlayerScore_Attach(this);
     ClientData_Attach(this);
     accuracy_init(this);
     entcs_attach(this);
     playerdemo_init(this);
     anticheat_init(this);
     W_HitPlotOpen(this);
     bot_clientconnect(this);
 }
void ClientState_detach (entity this)
Definition at line 68 of file state.qc.
References _cs, accuracy_free(), anticheat_report(), bot_clientdisconnect(), ClientData_Detach(), CS(), entcs_detach(), GetCvars(), NULL, playerdemo_shutdown(), PlayerScore_Detach(), and W_HitPlotClose().
Referenced by ClientDisconnect().
 {
     remove(CS(this));
     this._cs = NULL;
     GetCvars(this, -1);  // free cvars
     bot_clientdisconnect(this);
     W_HitPlotClose(this);
     anticheat_report(this);
     playerdemo_shutdown();
     entcs_detach(this);
     accuracy_free(self);
     ClientData_Detach(this);
     PlayerScore_Detach(self);
 }
void DecodeLevelParms (entity this)
Definition at line 732 of file cl_client.qc.
References max(), MUTATOR_CALLHOOK, parm1, parm_idlesince, sv_maxidle, and time.
Referenced by ClientState_attach().
 {
     // load parms
     this.parm_idlesince = parm1;
     if (this.parm_idlesince == -(86400 * 366))
         this.parm_idlesince = time;
     // whatever happens, allow 60 seconds of idling directly after connect for map loading
     this.parm_idlesince = max(this.parm_idlesince, time - sv_maxidle + 60);
     MUTATOR_CALLHOOK(DecodeLevelParms);
 }
void entcs_attach (entity this)
Referenced by ClientState_attach().
void entcs_detach (entity this)
Referenced by ClientState_detach().
void GetCvars (entity this, int f)
Parameters
f -1: cleanup, 0: request, 1: receive
Definition at line 413 of file miscfunctions.qc.
References argv(), cvar_cl_allow_uidtracking, cvar_cl_weaponpriorities, cvar_cl_weaponpriority, get_cvars_f, get_cvars_s, GetCvars_handleFloat(), GetCvars_handleString_Fixup(), MUTATOR_CALLHOOK, PS, ReplicateVars(), strcat1(), string_null, W_FixWeaponOrder_AllowIncomplete(), W_FixWeaponOrder_ForceComplete_AndBuildImpulseList(), and w_getbestweapon.
Referenced by ClientCommand_sentcvar(), ClientState_attach(), and ClientState_detach().
 {
     string s = string_null;
     if (f > 0)
         s = strcat1(argv(f));
     get_cvars_f = f;
     get_cvars_s = s;
     MUTATOR_CALLHOOK(GetCvars);
     Notification_GetCvars();
     ReplicateVars(this, s, f);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriority, "cl_weaponpriority", W_FixWeaponOrder_ForceComplete_AndBuildImpulseList);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[0], "cl_weaponpriority0", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[1], "cl_weaponpriority1", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[2], "cl_weaponpriority2", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[3], "cl_weaponpriority3", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[4], "cl_weaponpriority4", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[5], "cl_weaponpriority5", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[6], "cl_weaponpriority6", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[7], "cl_weaponpriority7", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[8], "cl_weaponpriority8", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleString_Fixup(s, f, cvar_cl_weaponpriorities[9], "cl_weaponpriority9", W_FixWeaponOrder_AllowIncomplete);
     GetCvars_handleFloat(s, f, cvar_cl_allow_uidtracking, "cl_allow_uidtracking");
     // fixup of switchweapon (needed for LMS or when spectating is disabled, as PutClientInServer comes too early)
     if (f > 0)
     {
         if (s == "cl_weaponpriority")
             if (PS(self)) PS(self).m_switchweapon = w_getbestweapon(self);
         if (s == "cl_allow_uidtracking")
             PlayerStats_GameReport_AddPlayer(self);
     }
 }
void Inventory_delete (entity this)
Referenced by PlayerState_detach().
void Inventory_new (entity this)
Referenced by PlayerState_attach().
void playerdemo_init (entity this)
Definition at line 16 of file playerdemo.qc.
Referenced by ClientState_attach().
 {
     this.playerdemo_mode = PLAYERDEMO_MODE_OFF;
 }
void playerdemo_shutdown ()
Definition at line 20 of file playerdemo.qc.
Referenced by ClientState_detach().
 {SELFPARAM();
     if(self.playerdemo_mode != PLAYERDEMO_MODE_OFF)
     {
         LOG_INFO("playerdemo: ", self.netname, " closed\n");
         fclose(self.playerdemo_fh);
     }
     self.playerdemo_mode = 0;
 }
void PlayerScore_Attach (entity this)
Definition at line 316 of file scores.qc.
Referenced by ClientState_attach().
 {
     if(player.scorekeeper)
         error("player already has a scorekeeper");
     entity sk = new_pure(scorekeeper);
     sk.owner = player;
     Net_LinkEntity(sk, false, 0, PlayerScore_SendEntity);
     player.scorekeeper = sk;
 }
void PlayerScore_Detach (entity this)
Definition at line 326 of file scores.qc.
Referenced by ClientState_detach().
 {
     if(!player.scorekeeper)
         error("player has no scorekeeper");
     remove(player.scorekeeper);
     player.scorekeeper = world;
 }
void PlayerState_attach (entity this)
Definition at line 6 of file state.qc.
References _ps, Inventory_new(), and NEW.
Referenced by PutClientInServer().
 {
     this._ps = NEW(PlayerState, this);
     Inventory_new(this);
 }
void PlayerState_detach (entity this)
Definition at line 13 of file state.qc.
References FOREACH_CLIENT, Inventory_delete(), PlayerState::m_client, NULL, and PS.
Referenced by PutObserverInServer().
 {
     PlayerState ps = PS(this);
     if (!ps) return;  // initial connect
     PS(this) = NULL;
     if (ps.m_client != this) return;  // don't own state, spectator
     FOREACH_CLIENT(PS(it) == ps, { PS(it) = NULL; });
     remove(ps);
     Inventory_delete(this);
 }
void W_HitPlotClose (entity this)
Definition at line 92 of file hitplot.qc.
Referenced by ClientState_detach().
 {
     if(player.hitplotfh >= 0)
     {
         fclose(player.hitplotfh);
         player.hitplotfh = -1;
     }
 }
void W_HitPlotOpen (entity this)
Definition at line 82 of file hitplot.qc.
Referenced by ClientState_attach().
 {
     if(autocvar_g_hitplots || strhasword(autocvar_g_hitplots_individuals, player.netaddress))
     {
         player.hitplotfh = fopen(strcat("hits-", matchid, "-", player.netaddress, "-", ftos(player.playerid), ".plot"), FILE_WRITE);
         fputs(player.hitplotfh, strcat("#name ", player.netname, "\n"));
     }
     else { player.hitplotfh = -1; }
 }