Xonotic: common/mapobjects/defs.qh File Reference
defs.qh File Reference
Functions
void (entity this, int act_state) setactive
Variables
int active
const int ACTIVE_ACTIVE = 1
const int ACTIVE_BUSY = 2
const int ACTIVE_IDLE = 2
const int ACTIVE_NOT = 0
const int ACTIVE_TOGGLE = 3
const int ALL_ENTITIES = BIT(1)
const int CRUSH = BIT(2)
const int INVERT_TEAMS = BIT(2)
const int NOSPLASH = BIT(8)
const int ON_MAPLOAD = BIT(1)
const int ONLY_PLAYERS = BIT(14)
const int SF_TRIGGER_INIT = BIT(0)
const int SF_TRIGGER_RESET = BIT(2)
const int SF_TRIGGER_UPDATE = BIT(1)
const int SPAWNFLAG_NOMESSAGE = BIT(0)
const int SPAWNFLAG_NOTOUCH = BIT(0)
const int START_DISABLED = BIT(0)
const int START_ENABLED = BIT(0)
const int STATE_BOTTOM = 1
const int STATE_DOWN = 3
const int STATE_TOP = 0
const int STATE_UP = 2
Function Documentation
void()
void (entity this, int act_state)
Variable Documentation
active
int active
Definition at line 34 of file defs.qh.
Referenced by conveyor_think(), DelayThink(), Teleport_Active(), Teleport_Touch(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), trigger_push_findtarget(), trigger_push_touch(), vehicle_initialize(), vehicle_use(), and vehicles_reset().
ACTIVE_ACTIVE
const int ACTIVE_ACTIVE = 1
Definition at line 37 of file defs.qh.
Referenced by conveyor_think(), Damage(), DelayThink(), Teleport_Active(), Teleport_Touch(), trigger_impulse_touch_accel(), trigger_impulse_touch_directional(), trigger_impulse_touch_radial(), trigger_push_findtarget(), vehicle_initialize(), and vehicle_use().
ACTIVE_BUSY
const int ACTIVE_BUSY = 2
Definition at line 39 of file defs.qh.
ACTIVE_IDLE
const int ACTIVE_IDLE = 2
Definition at line 38 of file defs.qh.
ACTIVE_NOT
const int ACTIVE_NOT = 0
Definition at line 36 of file defs.qh.
Referenced by conveyor_think(), DelayThink(), ons_TurretSpawn_Delayed(), TEST(), trigger_push_touch(), vehicle_initialize(), vehicle_use(), and vehicles_reset().
ACTIVE_TOGGLE
const int ACTIVE_TOGGLE = 3
Definition at line 40 of file defs.qh.
Referenced by DelayThink().
ALL_ENTITIES
const int ALL_ENTITIES = BIT(1)
Definition at line 8 of file defs.qh.
CRUSH
const int CRUSH = BIT(2)
Definition at line 11 of file defs.qh.
Referenced by plat_crush().
INVERT_TEAMS
const int INVERT_TEAMS = BIT(2)
Definition at line 10 of file defs.qh.
Referenced by Teleport_Active(), and trigger_push_touch().
NOSPLASH
const int NOSPLASH = BIT(8)
Definition at line 12 of file defs.qh.
Referenced by door_damage().
ON_MAPLOAD
const int ON_MAPLOAD = BIT(1)
Definition at line 9 of file defs.qh.
ONLY_PLAYERS
const int ONLY_PLAYERS = BIT(14)
Definition at line 13 of file defs.qh.
SF_TRIGGER_INIT
const int SF_TRIGGER_INIT = BIT(0)
Definition at line 22 of file defs.qh.
Referenced by conveyor_think(), door_reset(), LinkDoors(), train_next(), and trigger_push_findtarget().
SF_TRIGGER_RESET
const int SF_TRIGGER_RESET = BIT(2)
Definition at line 24 of file defs.qh.
Referenced by door_reset(), LinkDoors(), plat_reset(), and train_next().
SF_TRIGGER_UPDATE
const int SF_TRIGGER_UPDATE = BIT(1)
Definition at line 23 of file defs.qh.
Referenced by conveyor_think(), DelayThink(), door_init_startopen(), door_reset(), and LinkDoors().
SPAWNFLAG_NOMESSAGE
const int SPAWNFLAG_NOMESSAGE = BIT(0)
Definition at line 16 of file defs.qh.
SPAWNFLAG_NOTOUCH
const int SPAWNFLAG_NOTOUCH = BIT(0)
Definition at line 17 of file defs.qh.
START_DISABLED
const int START_DISABLED = BIT(0)
Definition at line 7 of file defs.qh.
START_ENABLED
const int START_ENABLED = BIT(0)
Definition at line 6 of file defs.qh.
Referenced by DelayThink().
STATE_BOTTOM
const int STATE_BOTTOM = 1
Definition at line 30 of file defs.qh.
STATE_DOWN
const int STATE_DOWN = 3
Definition at line 32 of file defs.qh.
STATE_TOP
const int STATE_TOP = 0
Definition at line 29 of file defs.qh.
STATE_UP
const int STATE_UP = 2
Definition at line 31 of file defs.qh.