Xonotic: common/gamemodes/gamemode/onslaught/sv_generator.qh File Reference
common/gamemodes/gamemode/onslaught/sv_generator.qh File Reference
Defines
#define GENERATOR_H
Functions
bool generator_send (entity this, entity to, int sf)
Variables
const vector GENERATOR_MIN = '-52 -52 -14'
const vector GENERATOR_MAX = '52 52 75'
const int GSF_STATUS = 4
const int GSF_SETUP = 8
Define Documentation
#define GENERATOR_H
Definition at line 2 of file sv_generator.qh.
Function Documentation
bool generator_send (entity this, entity to, int sf)
Definition at line 3 of file sv_generator.qc.
References ceil(), count, GSF_SETUP, GSF_STATUS, health, max_health, team, WriteByte(), and WriteCoord().
Referenced by generator_link().
{
    WriteHeader(MSG_ENTITY, ENT_CLIENT_GENERATOR);
    WriteByte(MSG_ENTITY, sf);
    if(sf & GSF_SETUP)
    {
        WriteCoord(MSG_ENTITY, self.origin_x);
        WriteCoord(MSG_ENTITY, self.origin_y);
        WriteCoord(MSG_ENTITY, self.origin_z);
        WriteByte(MSG_ENTITY, self.health);
        WriteByte(MSG_ENTITY, self.max_health);
        WriteByte(MSG_ENTITY, self.count);
        WriteByte(MSG_ENTITY, self.team);
    }
    if(sf & GSF_STATUS)
    {
        WriteByte(MSG_ENTITY, self.team);
        if(self.health <= 0)
            WriteByte(MSG_ENTITY, 0);
        else
            WriteByte(MSG_ENTITY, ceil((self.health / self.max_health) * 255));
    }
    return true;
}
Variable Documentation
const vector GENERATOR_MAX = '52 52 75'
Definition at line 4 of file sv_generator.qh.
const vector GENERATOR_MIN = '-52 -52 -14'
Definition at line 3 of file sv_generator.qh.
const int GSF_SETUP = 8
Definition at line 7 of file sv_generator.qh.
const int GSF_STATUS = 4
Definition at line 6 of file sv_generator.qh.