Xonotic: lib/warpzone/anglestransform.qh File Reference
lib/warpzone/anglestransform.qh File Reference
Defines
#define LIB_WARPZONE_ANGLETRANSFORM_H
#define fixedmakevectors makevectors
#define fixedvectoangles(a) (_fixedvectoangles = vectoangles(a), _fixedvectoangles.x *= -1, _fixedvectoangles)
#define fixedvectoangles2(a, b) (_fixedvectoangles2 = vectoangles2(a, b), _fixedvectoangles2.x *= -1, _fixedvectoangles2)
Functions
vector AnglesTransform_Apply (vector transform, vector v)
vector AnglesTransform_Multiply (vector t1, vector t2)
vector AnglesTransform_Invert (vector transform)
vector AnglesTransform_TurnDirectionFU (vector transform)
vector AnglesTransform_TurnDirectionFR (vector transform)
vector AnglesTransform_RightDivide (vector to_transform, vector from_transform)
vector AnglesTransform_LeftDivide (vector from_transform, vector to_transform)
vector AnglesTransform_Normalize (vector t, float minimize_roll)
vector AnglesTransform_ApplyToAngles (vector transform, vector v)
vector AnglesTransform_ApplyToVAngles (vector transform, vector v)
vector AnglesTransform_FromAngles (vector v)
vector AnglesTransform_ToAngles (vector v)
vector AnglesTransform_FromVAngles (vector v)
vector AnglesTransform_ToVAngles (vector v)
vector AnglesTransform_Multiply_GetPostShift (vector sf0, vector st0, vector t1, vector st1)
vector AnglesTransform_PrePostShift_GetPostShift (vector sf, vector t, vector st)
Variables
noref vector _fixedvectoangles
noref vector _fixedvectoangles2
Define Documentation
#define fixedmakevectors makevectors
Definition at line 9 of file anglestransform.qh.
Referenced by AnglesTransform_Apply(), AnglesTransform_Invert(), AnglesTransform_Multiply(), attach_sameorigin(), InterpolateOrigin_Note(), Portal_ApplyTransformToPlayerAngle(), Portal_FindSafeOrigin(), Portal_Remove(), Portal_Spawn(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), Portal_TeleportPlayer(), Portal_Think(), Portal_Touch(), skel_set_boneabs(), skeleton_from_frames(), and WarpZone_SetUp().
#define fixedvectoangles (a) (_fixedvectoangles = vectoangles(a), _fixedvectoangles.x *= -1, _fixedvectoangles)
Definition at line 11 of file anglestransform.qh.
Referenced by Portal_ApplyTransformToPlayerAngle().
#define fixedvectoangles2 (a, b) (_fixedvectoangles2 = vectoangles2(a, b), _fixedvectoangles2.x *= -1, _fixedvectoangles2)
Definition at line 13 of file anglestransform.qh.
Referenced by AnglesTransform_Invert(), AnglesTransform_Multiply(), attach_sameorigin(), CheatCommand(), detach_sameorigin(), InterpolateOrigin_Do(), InterpolateOrigin_Undo(), Portal_SpawnInPortalAtTrace(), Portal_SpawnOutPortalAtTrace(), skel_set_boneabs(), and skeleton_from_frames().
#define LIB_WARPZONE_ANGLETRANSFORM_H
Definition at line 2 of file anglestransform.qh.
Function Documentation
vector AnglesTransform_Apply (vector transform, vector v)
Definition at line 5 of file anglestransform.qc.
References fixedmakevectors, v_forward, v_right, and v_up.
Referenced by AnglesTransform_Multiply(), AnglesTransform_Multiply_GetPostShift(), AnglesTransform_PrePostShift_GetPostShift(), Portal_ApplyTransformToPlayerAngle(), Portal_TeleportPlayer(), skel_set_boneabs(), WarpZone_TransformOrigin(), WarpZone_TransformVelocity(), WarpZone_UnTransformOrigin(), and WarpZone_UnTransformVelocity().
{
    fixedmakevectors(transform);
    return v_forward * v.x
        + v_right   * (-v.y)
        + v_up      * v.z;
}
vector AnglesTransform_ApplyToAngles (vector transform, vector v)
Definition at line 128 of file anglestransform.qc.
References AnglesTransform_Multiply().
Referenced by CheatCommand(), Portal_TeleportPlayer(), WarpZone_TransformAngles(), and WarpZone_UnTransformAngles().
{
    v.x = -v.x;
    v = AnglesTransform_Multiply(transform, v);
    v.x = -v.x;
    return v;
}
vector AnglesTransform_ApplyToVAngles (vector transform, vector v)
Definition at line 135 of file anglestransform.qc.
References AnglesTransform_Multiply().
Referenced by WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
{
    v = AnglesTransform_Multiply(transform, v);
    return v;
}
vector AnglesTransform_FromAngles (vector v)
Definition at line 140 of file anglestransform.qc.
Referenced by attach_sameorigin(), Projectile_Draw(), and vehicle_aimturret().
{
    v.x = -v.x;
    return v;
}
vector AnglesTransform_FromVAngles (vector v)
Definition at line 150 of file anglestransform.qc.
Referenced by attach_sameorigin().
{
    return v;
}
vector AnglesTransform_Invert (vector transform)
Definition at line 21 of file anglestransform.qc.
References fixedmakevectors, fixedvectoangles2, v_forward, v_right, v_up, and vector().
Referenced by AnglesTransform_LeftDivide(), AnglesTransform_RightDivide(), skel_set_boneabs(), WarpZone_Accumulator_AddInverseTransform(), WarpZone_UnTransformAngles(), WarpZone_UnTransformOrigin(), WarpZone_UnTransformVAngles(), and WarpZone_UnTransformVelocity().
{
    vector i_forward, i_up;
    fixedmakevectors(transform);
    // we want angles that turn v_forward into '1 0 0', v_right into '0 1 0' and v_up into '0 0 1'
    // but these are orthogonal unit vectors!
    // so to invert, we can simply fixedvectoangles the TRANSPOSED matrix
    // TODO is this always -transform?
    i_forward.x = v_forward.x;
    i_forward.y = -v_right.x;
    i_forward.z = v_up.x;
    i_up.x = v_forward.z;
    i_up.y = -v_right.z;
    i_up.z = v_up.z;
    return fixedvectoangles2(i_forward, i_up);
}
vector AnglesTransform_LeftDivide (vector from_transform, vector to_transform)
Definition at line 70 of file anglestransform.qc.
References AnglesTransform_Invert(), and AnglesTransform_Multiply().
Referenced by skel_set_boneabs(), and vehicle_aimturret().
{
    return AnglesTransform_Multiply(AnglesTransform_Invert(from_transform), to_transform);
}
vector AnglesTransform_Multiply (vector t1, vector t2)
Definition at line 13 of file anglestransform.qc.
References AnglesTransform_Apply(), fixedmakevectors, fixedvectoangles2, v_forward, v_up, and vector().
Referenced by AnglesTransform_ApplyToAngles(), AnglesTransform_ApplyToVAngles(), AnglesTransform_LeftDivide(), AnglesTransform_RightDivide(), Projectile_Draw(), skeleton_from_frames(), WarpZone_Accumulator_AddTransform(), and WarpZone_FindRadius_Recurse().
{
    vector m_forward, m_up;
    fixedmakevectors(t2); m_forward = v_forward; m_up = v_up;
    m_forward = AnglesTransform_Apply(t1, m_forward); m_up = AnglesTransform_Apply(t1, m_up);
    return fixedvectoangles2(m_forward, m_up);
}
vector AnglesTransform_Multiply_GetPostShift (vector sf0, vector st0, vector t1, vector st1)
Definition at line 191 of file anglestransform.qc.
References AnglesTransform_Apply().
Referenced by WarpZone_Accumulator_AddTransform(), and WarpZone_FindRadius_Recurse().
{
    // we want the result of:
    //   t0 * (t1 * p + st1) + st0
    //   t0 * t1 * p + t0 * st1 + st0
    return st0 + AnglesTransform_Apply(t0, st1);
}
vector AnglesTransform_Normalize (vector t, float minimize_roll)
Definition at line 75 of file anglestransform.qc.
References rint().
Referenced by vehicle_aimturret(), WarpZone_TransformVAngles(), and WarpZone_UnTransformVAngles().
{
    float need_flip;
    // first, bring all angles in their range...
    t.x = t.x - 360 * rint(t.x / 360);
    t.y = t.y - 360 * rint(t.y / 360);
    t.z = t.z - 360 * rint(t.z / 360);
    if(minimize_roll)
        need_flip = (t.z > 90 || t.z <= -90);
    else
        need_flip = (t.x > 90 || t.x < -90); // for pitch we prefer to allow exactly -90 degrees for looking straight down
    if(need_flip)
    {
        if(t.x >= 0) t.x = 180 - t.x; else t.x = -180 - t.x;
        if(t.y > 0) t.y -= 180; else t.y += 180;
        if(t.z > 0) t.z -= 180; else t.z += 180;
    }
    return t;
}
vector AnglesTransform_PrePostShift_GetPostShift (vector sf, vector t, vector st)
Definition at line 198 of file anglestransform.qc.
References AnglesTransform_Apply().
Referenced by WarpZone_Accumulator_AddInverseTransform(), and WarpZone_SetUp().
{
    return st - AnglesTransform_Apply(t, sf);
}
vector AnglesTransform_RightDivide (vector to_transform, vector from_transform)
Definition at line 65 of file anglestransform.qc.
References AnglesTransform_Invert(), and AnglesTransform_Multiply().
Referenced by Portal_Connect(), and WarpZone_SetUp().
{
    return AnglesTransform_Multiply(to_transform, AnglesTransform_Invert(from_transform));
}
vector AnglesTransform_ToAngles (vector v)
Definition at line 145 of file anglestransform.qc.
Referenced by attach_sameorigin(), detach_sameorigin(), Projectile_Draw(), and vehicle_aimturret().
{
    v.x = -v.x;
    return v;
}
vector AnglesTransform_ToVAngles (vector v)
Definition at line 154 of file anglestransform.qc.
Referenced by attach_sameorigin(), and detach_sameorigin().
{
    return v;
}
vector AnglesTransform_TurnDirectionFR (vector transform)
Definition at line 38 of file anglestransform.qc.
Referenced by Portal_Connect(), and WarpZone_SetUp().
{
    // turn 180 degrees around v_up
    // changes in-direction to out-direction
    //fixedmakevectors(transform);
    //return fixedvectoangles2(-1 * v_forward, 1 * v_up);
    transform.x = -transform.x;
    transform.y = 180 + transform.y;
    transform.z = -transform.z;
    // pitch: -s +c
    // yaw:   -s -c
    // roll:  -s +c
    return transform;
}
vector AnglesTransform_TurnDirectionFU (vector transform)
Definition at line 53 of file anglestransform.qc.
{
    // turn 180 degrees around v_up
    // changes in-direction to out-direction
    //fixedmakevectors(transform);
    //return fixedvectoangles2(-1 * v_forward, 1 * v_up);
    transform.x = -transform.x;
    transform.y = 180 + transform.y;
    transform.z = 180 - transform.z;
    return transform;
}
Variable Documentation
noref vector _fixedvectoangles
Definition at line 10 of file anglestransform.qh.
noref vector _fixedvectoangles2
Definition at line 12 of file anglestransform.qh.