Xonotic: common/turrets/config.qc File Reference
config.qc File Reference
Functions
void Dump_Turret_Settings ()
float T_Config_Queue_Compare (float root, float child, entity pass)
void T_Config_Queue_Swap (float root, float child, entity pass)
Function Documentation
void Dump_Turret_Settings ()
Definition at line 28 of file config.qc.
References FOREACH, heapsort(), LOG_INFO, string_null, T_Config_Queue_Compare(), T_Config_Queue_Swap(), and world.
Referenced by GENERIC_COMMAND().
 {
     float x, totalsettings = 0;
     FOREACH(Turrets, it != TUR_Null, {
         // step 1: clear the queue
         TUR_CONFIG_COUNT = 0;
         for(x = 0; x <= MAX_TUR_CONFIG; ++x)
             { tur_config_queue[x] = string_null; }
         // step 2: build new queue
         it.tr_config(it);
         // step 3: sort queue
         heapsort(TUR_CONFIG_COUNT, T_Config_Queue_Swap, T_Config_Queue_Compare, world);
         // step 4: write queue
         TUR_CONFIG_WRITETOFILE(sprintf("// {{{ #%d: %s\n", i, it.turret_name))
         for(x = 0; x <= TUR_CONFIG_COUNT; ++x)
             { TUR_CONFIG_WRITETOFILE(tur_config_queue[x]) }
         TUR_CONFIG_WRITETOFILE("// }}}\n")
         // step 5: debug info
         LOG_INFO(sprintf("#%d: %s: %d settings...\n", i, it.turret_name, TUR_CONFIG_COUNT));
         totalsettings += TUR_CONFIG_COUNT;
     });
     // clear queue now that we're finished
     TUR_CONFIG_COUNT = 0;
     for(x = 0; x <= MAX_TUR_CONFIG; ++x)
         { tur_config_queue[x] = string_null; }
     // extra information
     LOG_INFO(sprintf("Totals: %d turrets, %d settings\n", (Turrets_COUNT - 1), totalsettings));
 }
float T_Config_Queue_Compare (float root, float child, entity pass)
Definition at line 12 of file config.qc.
References str2chr.
Referenced by Dump_Turret_Settings().
 {
     float i, r, c;
     for(i = 1; i <= 100; ++i)
     {
         r = str2chr(tur_config_queue[root], i);
         c = str2chr(tur_config_queue[child], i);
         if(r == c) { continue; }
         else if(c > r) { return -1; }
         else { return 1; }
     }
     return 0;
 }
void T_Config_Queue_Swap (float root, float child, entity pass)
Definition at line 5 of file config.qc.
Referenced by Dump_Turret_Settings().
 {
     string oldroot = tur_config_queue[root];
     tur_config_queue[root] = tur_config_queue[child];
     tur_config_queue[child] = oldroot;
 }