Xonotic: server/mutators/mutator/gamemode_ca.qh File Reference
gamemode_ca.qh File Reference
#include "../gamemode.qh"
Functions
bool CA_CheckTeams ()
bool CA_CheckWinner ()
bool ca_isEliminated (entity e)
void CA_RoundStart ()
REGISTER_MUTATOR (ca, false)
void SetLimits (int fraglimit_override, int leadlimit_override, float timelimit_override, float qualifying_override)
Variables
bool allowed_to_spawn
int autocvar_g_ca_point_leadlimit
int autocvar_g_ca_point_limit
float autocvar_g_ca_round_timelimit
bool autocvar_g_ca_team_spawns
int autocvar_g_ca_teams_override
float autocvar_g_ca_warmup
int ca_teams
float caplayer
const int ST_CA_ROUNDS = 1
Function Documentation
bool CA_CheckTeams ()
Definition at line 100 of file gamemode_ca.qc.
References allowed_to_spawn, BIT, bluealive, CA_ALIVE_TEAMS_OK, CA_count_alive_players(), ca_teams, NULL, pinkalive, redalive, total_players, and yellowalive.
Referenced by REGISTER_MUTATOR().
 {
     static int prev_missing_teams_mask;
     allowed_to_spawn = true;
     CA_count_alive_players();
     if(CA_ALIVE_TEAMS_OK())
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return true;
     }
     if(total_players == 0)
     {
         if(prev_missing_teams_mask > 0)
             Kill_Notification(NOTIF_ALL, NULL, MSG_CENTER, CPID_MISSING_TEAMS);
         prev_missing_teams_mask = -1;
         return false;
     }
     int missing_teams_mask = 0;
     if(ca_teams & BIT(0))
         missing_teams_mask += (!redalive) * 1;
     if(ca_teams & BIT(1))
         missing_teams_mask += (!bluealive) * 2;
     if(ca_teams & BIT(2))
         missing_teams_mask += (!yellowalive) * 4;
     if(ca_teams & BIT(3))
         missing_teams_mask += (!pinkalive) * 8;
     if(prev_missing_teams_mask != missing_teams_mask)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_MISSING_TEAMS, missing_teams_mask);
         prev_missing_teams_mask = missing_teams_mask;
     }
     return false;
 }
bool CA_CheckWinner ()
Definition at line 55 of file gamemode_ca.qc.
References allowed_to_spawn, APP_TEAM_NUM, autocvar_g_ca_round_timelimit, autocvar_g_ca_warmup, CA_ALIVE_TEAMS, CA_count_alive_players(), CA_GetWinnerTeam(), FOREACH_CLIENT, IS_PLAYER, LAMBDA, nades_Clear(), NULL, round_handler_GetEndTime, round_handler_Init(), ST_CA_ROUNDS, TeamScore_AddToTeam(), and time.
Referenced by REGISTER_MUTATOR().
 {
     if(round_handler_GetEndTime() > 0 && round_handler_GetEndTime() - time <= 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_OVER);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_OVER);
         FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(nades_Clear(it)));
         allowed_to_spawn = false;
         game_stopped = true;
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         return 1;
     }
     CA_count_alive_players();
     if(CA_ALIVE_TEAMS() > 1)
         return 0;
     int winner_team = CA_GetWinnerTeam();
     if(winner_team > 0)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, APP_TEAM_NUM(winner_team, CENTER_ROUND_TEAM_WIN));
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, APP_TEAM_NUM(winner_team, INFO_ROUND_TEAM_WIN));
         TeamScore_AddToTeam(winner_team, ST_CA_ROUNDS, +1);
     }
     else if(winner_team == -1)
     {
         Send_Notification(NOTIF_ALL, NULL, MSG_CENTER, CENTER_ROUND_TIED);
         Send_Notification(NOTIF_ALL, NULL, MSG_INFO, INFO_ROUND_TIED);
     }
     allowed_to_spawn = false;
     game_stopped = true;
     round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
     FOREACH_CLIENT(IS_PLAYER(it), LAMBDA(nades_Clear(it)));
     return 1;
 }
bool ca_isEliminated (entity e)
Definition at line 136 of file gamemode_ca.qc.
References FRAGS_LMS_LOSER, and IS_DEAD.
Referenced by REGISTER_MUTATOR().
 {
     if(e.caplayer == 1 && (IS_DEAD(e) || e.frags == FRAGS_LMS_LOSER))
         return true;
     if(e.caplayer == 0.5)
         return true;
     return false;
 }
void CA_RoundStart ()
Definition at line 95 of file gamemode_ca.qc.
References allowed_to_spawn, boolean, and warmup_stage.
Referenced by REGISTER_MUTATOR().
 {
     allowed_to_spawn = boolean(warmup_stage);
 }
REGISTER_MUTATOR (ca , false)
Definition at line 26 of file gamemode_ca.qh.
References ActivateTeamplay(), allowed_to_spawn, autocvar_g_ca_point_leadlimit, autocvar_g_ca_point_limit, autocvar_g_ca_round_timelimit, autocvar_g_ca_team_spawns, autocvar_g_ca_teams_override, autocvar_g_ca_warmup, autocvar_timelimit_override, BIT, bound(), CA_CheckTeams(), CA_CheckWinner(), ca_isEliminated(), CA_RoundStart(), ca_teams, cvar(), EliminatedPlayers_Init(), error, have_team_spawns, LOG_INFO, MUTATOR_ONADD, MUTATOR_ONREMOVE, round_handler_Init(), round_handler_Spawn(), ScoreInfo_SetLabel_TeamScore(), ScoreRules_basics(), ScoreRules_basics_end(), SetLimits(), SFL_SORT_PRIO_PRIMARY, ST_CA_ROUNDS, teams, and time.
 {
     MUTATOR_ONADD
     {
         // game loads at time 1
         if (time > 1) error("This is a game type and it cannot be added at runtime.");
         allowed_to_spawn = true;
         ca_teams = autocvar_g_ca_teams_override;
         if (ca_teams < 2)
             ca_teams = cvar("g_ca_teams"); // read the cvar directly as it gets written earlier in the same frame
         ca_teams = bound(2, ca_teams, 4);
         int teams = 0;
         if(ca_teams >= 1) teams |= BIT(0);
         if(ca_teams >= 2) teams |= BIT(1);
         if(ca_teams >= 3) teams |= BIT(2);
         if(ca_teams >= 4) teams |= BIT(3);
         ca_teams = teams; // now set it?
         ScoreRules_basics(teams, SFL_SORT_PRIO_PRIMARY, 0, true);
         ScoreInfo_SetLabel_TeamScore(ST_CA_ROUNDS, "rounds", SFL_SORT_PRIO_PRIMARY);
         ScoreRules_basics_end();
         round_handler_Spawn(CA_CheckTeams, CA_CheckWinner, CA_RoundStart);
         round_handler_Init(5, autocvar_g_ca_warmup, autocvar_g_ca_round_timelimit);
         EliminatedPlayers_Init(ca_isEliminated);
         ActivateTeamplay();
         SetLimits(autocvar_g_ca_point_limit, autocvar_g_ca_point_leadlimit, autocvar_timelimit_override, -1);
         if (autocvar_g_ca_team_spawns)
             have_team_spawns = -1; // request team spawns
     }
     MUTATOR_ONREMOVE
     {
         LOG_INFO("This is a game type and it cannot be removed at runtime.");
         return -1;
     }
     return 0;
 }
void SetLimits (int fraglimit_override, int leadlimit_override, float timelimit_override, float qualifying_override)
Definition at line 597 of file g_world.qc.
References autocvar_g_campaign, cvar_set(), ftos(), and limits_are_set.
Referenced by rc_SetLimits(), REGISTER_MUTATOR(), and spawnfunc().
 {
     if(!autocvar_g_campaign)
     {
         if(fraglimit_override >= 0) cvar_set("fraglimit", ftos(fraglimit_override));
         if(timelimit_override >= 0) cvar_set("timelimit", ftos(timelimit_override));
         if(leadlimit_override >= 0) cvar_set("leadlimit", ftos(leadlimit_override));
         if(qualifying_override >= 0) cvar_set("g_race_qualifying_timelimit", ftos(qualifying_override));
     }
     limits_are_set = true;
 }
Variable Documentation
bool allowed_to_spawn
Definition at line 15 of file gamemode_ca.qh.
Referenced by CA_CheckTeams(), CA_CheckWinner(), CA_RoundStart(), MUTATOR_HOOKFUNCTION(), and REGISTER_MUTATOR().
int autocvar_g_ca_point_leadlimit
Definition at line 6 of file gamemode_ca.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_point_limit
Definition at line 5 of file gamemode_ca.qh.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_round_timelimit
Definition at line 7 of file gamemode_ca.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().
bool autocvar_g_ca_team_spawns
Definition at line 8 of file gamemode_ca.qh.
Referenced by REGISTER_MUTATOR().
int autocvar_g_ca_teams_override
Definition at line 10 of file gamemode_ca.qh.
Referenced by REGISTER_MUTATOR().
float autocvar_g_ca_warmup
Definition at line 11 of file gamemode_ca.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().
int ca_teams
Definition at line 14 of file gamemode_ca.qh.
Referenced by CA_CheckTeams(), MUTATOR_HOOKFUNCTION(), and REGISTER_MUTATOR().
float caplayer
Definition at line 74 of file gamemode_ca.qh.
Referenced by checkSpectatorBlock().
const int ST_CA_ROUNDS = 1
Definition at line 17 of file gamemode_ca.qh.
Referenced by CA_CheckWinner(), and REGISTER_MUTATOR().