Xonotic: menu/xonotic/dialog_settings_bindings_reset.qc File Reference
dialog_settings_bindings_reset.qc File Reference
#include "dialog_settings_bindings_reset.qh"
#include "textlabel.qh"
#include "button.qh"
#include "keybinder.qh"
Functions
void XonoticBindingsResetDialog_fill (entity me)
Function Documentation
void XonoticBindingsResetDialog_fill (entity me)
Definition at line 7 of file dialog_settings_bindings_reset.qc.
References Dialog_Close(), entity(), KeyBinder_Bind_Reset_All(), makeXonoticButton(), and makeXonoticTextLabel().
 {
     entity e;
     me.TR(me);
         me.TD(me, 1, 2, makeXonoticTextLabel(0.5, _("Are you sure you want to reset all key bindings?")));
     me.TR(me);
     me.TR(me);
         me.TD(me, 1, 1, e = makeXonoticButton(_("Yes"), '1 0 0'));
             e.onClick = KeyBinder_Bind_Reset_All;
             e.onClickEntity = me;
         me.TD(me, 1, 1, e = makeXonoticButton(_("No"), '0 1 0'));
             e.onClick = Dialog_Close;
             e.onClickEntity = me;
 }